### PR TITLE
Removes Z-level 8

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes the 8th z-level, the so called "traitor station".

This has been inaccessible for literally months now and there's nothing on it anymore that anyone would want that's not already in science or the research station. The removal of telesci is kinda the final nail in the coffin for it.

Performance wise, this reduces total instances from 720,000 to 650,000--a 10% reduction.

Related
 - Fixes improperly named define.

### CODE REVIEW

**Comment by tigercat2000** [comment]
>This has been inaccessible for literally months now

Uh what
this is accessible via emagging the teleporter

**Comment by Fox-McCloud** [comment]
That hypothetically allows you to access it. There's nothing to teleport to on the that z-level, ergo, why it's been inaccessible.

**Comment by tigercat2000** [comment]
>There's nothing to teleport to on the that z-level, ergo, why it's been inaccessible.

what about the, you know, [syndicate beacon](https://github.com/ParadiseSS13/Paradise/blob/master/_maps/map_files/cyberiad/z8.dmm#L195), in the hall

**Comment by tigercat2000** [comment]
okay disregard, apparently that's a `bluespace_beacon`
why not just replace that with a radio/beacon with syndicate set to 1
instead of you know, nuking an entire z-level, on the grounds of it being outdated

**Comment by tigercat2000** [comment]
wait, no, bluespace_beacons are just holders for regular beacons

what are we even talking about, I am 99.9% sure that emagging a teleporter perfectly allows you to get onto the syndicate station

**Comment by Earthdivine** [comment]
Emagging the teleporter bungs you here, yes

**Comment by Fox-McCloud** [comment]
Because an entire z-level existing for a 2-3 jobs (the RD, HoP, and CE) to have a personal playground (that doesn't even really offer anything over what they can get on station) for that many additional instances is silly.

**Comment by tigercat2000** [comment]
>because teleporters aren't buildable, and the teleporter room is so secure

I get the point of it being next to useless with such little shit on it
but that means it's time for an upgrade, not nuking it
instances really don't fucking matter, it's not going to boost server performance that much

**Comment by Earthdivine** [comment]
I like the idea of a safe haven for antags, goodness knows they need it, my problem with it is more there's no way back to the station from it outside of space.

Why not have a traitor gear like the wormhole jaunter that teleports the traitor there? It would open it up to jobs outside of heads of staff, and it's an option to use it that's not tied to the overused emag.

**Comment by Spacemanspark** [comment]
I personally like it.
Only been to it once, but still.

**Comment by Regen1** [comment]
Agree with @Earthdivine 

:-1:

**Comment by taukausanake** [comment]
I would think that place would be used for antag training. If not that then the whole z-level could be converted into a training ground. I really want a place where I can just learn how to antag without the whole station trying to murder me. That implying we ever got a training round as per my suggestion but meh

**Comment by Amauros** [comment]
I definitely prefer an upgrade to z8 over nuking it.  Anything that gives antags a safe haven or even a place to coordinate their efforts is a welcome thing. In fact, I'd like to see a game mode that secretly involves the use of the traitor station as some objective.

**Comment by Dumbdumn5** [comment]
Agree with @Regen1 agreeing with @Earthdivine 
:-1:

**Comment by Flip-Sandwich** [comment]
:+1: A traitor safe haven's a decent enough idea but an entire z-level for it, a 90% empty zlevel is just straightup not worth the performance considering just how little people even know it exists and how little it is used

**Comment by Markolie** [comment]
I'm in favor of removing it. I've been the only person maintaining this shitty z-level, and it's still not functional. Heck, had anyone used this station anytime recently then they'd know that it's currently useless anyway because it runs out of power in no time due to the lighting power changes we made months ago.

Its removal does not mean that nothing can come in its stead: if someone designs a new traitor base that does work (and has solars for power), then I can assure you it'll be added.

**Comment by tigercat2000** [comment]
If this is removed, at least remove it fully; get rid of the teleporter code and all that

**Comment by Fox-McCloud** [comment]
@tigercat2000; actually, the teleporter code was added in to correct a legitimate issue; people were teleporting to syndicate bomb, singularity, and other assorted teleporter beacons. It wasn't implemented for the purpose of tatorstation.

**Comment by tigercat2000** [comment]
oh

**Comment by Earthdivine** [comment]
>If anyone had used it

That's the problem though, there's currently no reason to use it because you can't get to it without being a head of staff and when your there you can't leave it at all. The station is good for various villianry and getting a small breather, but it's current implementation calls for a redesign, not ripping it all out because of obtuse conditions (Being a head of staff and having a suit).

**Comment by Fox-McCloud** [comment]
There's plenty of traitor havens though, already. Maintenance, research outpost, mining station, engineering station, and the pirate radio station, to name a few. You have to invest in getting to them, sure, but they each have their own specific advantages/equipment and each are either barely monitored or totally unmonitored.

**Comment by Earthdivine** [comment]
>Invest in them

I don't see how hacking a door in secluded parts of the station is the equivalent of hacking a secure door in a public area, then leaving a big "SYNDICATES BEEN HERE" flag that is the Emagged teleporter, not to mention you need either a suit or hand teleporter to even get back. The outpost is not being used because there's no point in going, not because no one wants to use it. Why rip it out due to poor inplimentation?

>Research Outpost

This shouldn't be included in this also, it's even more useless then this and gives far more power to antags then the traitor outpost does (Free monkeys for cult and ling, emitter for traitors, lots of blood for any vamp who walks in with SE syringes.)

**Comment by Fox-McCloud** [comment]
please continue discussion here: https://github.com/ParadiseSS13/Paradise/pull/2185

**Pull request closed without merging**
