### PR TITLE
Improves 'Check my playtime' to show department playtimes

### PR DESCRIPTION
**Pull request by paulo-e**
## What Does This PR Do

Improves the 'Check my playtime' verb by showing the user's department-specific playtimes.

## Why It's Good For The Game

Players (like myself) like seeing their stats and feeling/seeing their progress in the game.
These values are already recorded, this would just be a way to show them to the users.

## Images of changes

image

## Changelog
:cl:
tweak: Improves 'Check my playtime' to show department playtimes
/:cl:

### CODE REVIEW

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
Its intentionally this way to avoid players ego-bragging with "I have xyz hours in this department, fucking listen to me"

**Comment by paulo-e** [comment]
@AffectedArc07 you can still say this without this PR. these changes are only for the client to see. I see what you mean but I don't think this PR changes anything

**Comment by AffectedArc07** [comment]
> @AffectedArc07 you can still say this without this PR. these changes are only for the client to see. I see what you mean but I don't think this PR changes anything

People will still hour brag in LOOC and use screenshots to back it up. Theres a reason the system is how it is.

**Comment by Sirryan2002** [comment]
People can request the breakdown of their hours from a mentor/admin if they want. The only current purpose of hour tracking is to bypass time restrictions for roles and to be eligible for mentor/admin applications. Outside of that, it's only to used for knowing for fun or to justify your opinion/stance on an issue.

Hell, the majority of the time when I give players their hour breakdown, the first thing they do is post their ludicrous hours in the public discord/OOC/LOOC to brag about it only for another player to post their own larger hour breakdown as if they need to maintain that they've played longer and are therefor more experienced/worthy of credibility.

**Comment by LordShekelstein** [comment]
> Its intentionally this way to avoid players ego-bragging with "I have xyz hours in this department, fucking listen to me"

This is definitely a valid argument, but I have seen people do this in the past with or without an hour checker -- albeit on sparse occasion. Whilst anecdotal, I had a chief engineer tell me that manual valves were worse than straight piping because it kept the pipes cooler, citing his quote, "300 hours as crewmember," as reason for me to blindly follow his orders; granted, as mentioned earlier, this isn't a regular case, so I don't really believe that hour bragging will be a thing in the future if this PR does eventually go through. Nevertheless, I think it would be a welcome change to be able to check these without being a mentor/admin. I'll keep bugging Woje anyways though. :)

**Comment by chafla** [comment]
If something like this goes through, can we get a readout of time spent observing as well?

**Comment by paulo-e** [comment]
> 
> 
> If something like this goes through, can we get a readout of time spent observing as well?

I could add this.

I understand the critics about this but to me this is harmless and *maybe* a rare nuisance at best. Yeah, someone could tell you their hours but if this person is this petty they are just going to say something else if they can't say their dep. hours. Sending links over LOOC is already breaking character IMO so I don't even see why not.
Doesn't really matter because this is most likely going to stay opened forever like some other PRs.

**Comment by Necaladun** [comment]
> Doesn't really matter because this is most likely going to stay opened forever like some other PRs.

This is the kind of sniping that has made myself and other maints so sick of dealing with the Github. If you have issues with how things are progressing, please bring it up directly with us instead of passive-aggressive remarks like this.

And remember - we never asked for this PR. If you had asked us first why we didn't perhaps do this in the first place, we could have explained it to you instead of you wasting both ours and yours time. This is another reason the Git can move so slowly - people like yourself not working with us and increasing the workload.

**Comment by paulo-e** [comment]
> 
> 
> > Doesn't really matter because this is most likely going to stay opened forever like some other PRs.
> 
> This is the kind of sniping that has made myself and other maints so sick of dealing with the Github. If you have issues with how things are progressing, please bring it up directly with us instead of passive-aggressive remarks like this.
> 
> And remember - we never asked for this PR. If you had asked us first why we didn't perhaps do this in the first place, we could have explained it to you instead of you wasting both ours and yours time. This is another reason the Git can move so slowly - people like yourself not working with us and increasing the workload.

No I only said this because a previous maint. said they didn't like it so it's either getting closed or "opened". I did the actual requested change but other than that I can't do much code-wise and if people didn't like te idea I can't do anything too

**Comment by Necaladun** [comment]
> No I only said this because a previous maint. said they didn't like it so it's either getting closed or "opened". I did the actual requested change but other than that I can't do much code-wise and if people didn't like the idea I can't do anything too

I don't care why you said it. Do not engage in this kind of passive-aggressive sniping. This is not a debate.

**Comment by paulo-e** [comment]
> 
> 
> > No I only said this because a previous maint. said they didn't like it so it's either getting closed or "opened". I did the actual requested change but other than that I can't do much code-wise and if people didn't like the idea I can't do anything too
> 
> I don't care why you said it. Do not engage in this kind of passive-aggressive sniping. This is not a debate.

I explained why I said it to show it wasn't me being passive-aggressive. It will not go through because a previous maintainer did not like it. It will not be straight-up closed, but it will not be merged. I don't know how I can be clearer. Will not try to be, anyways. There's no point in discussing this with someone who wasn't even involved and is saying nonsense

**Comment by Necaladun** [comment]
> There's no point in discussing this with someone who wasn't even involved and is saying nonsense

Maybe I wasn't clear. There is no discussion to be had. You are being directly told by a headmin to not post comments like that, regardless of the reason. Please keep your comments on PRs about the PR itself, not to complain about things staying open forever.

If you have a problem with how the github process works, how the maintainers are acting, or any problems with procedures/process, you can message us directly on the github. The Github is not the place for this, it's for discussing the code.

**Comment by paulo-e** [comment]
you got it boss 🙏

**Pull request closed without merging**
