### PR TITLE
Adds a new hud icon for non-DNR bodies with clients

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

Adds a new hud icon for non-DNR bodies with clients. If the body is DNR/has no soul/no mind, it will stay the skull hud icon. Otherwise, it will display a grey 30 second version of the flatline HUD.

## Why It's Good For The Game
It helps medical players indicate if someone who has gone over the 5 minute defib limit, if theres still a soul in the body. It would be primarily helpful when you have the 1000x stack of corpses in cloning.

## Images of changes

image
image

## Testing

Had 2 clients, killed the other and cloned a lot, left and rejoined the game over and over, works as intended.

Tested on a fakedeath cling, worked appropriately, almost like they were actually dead!

## Changelog
:cl:
add: There is a new medical hud icon that shows that body has a soul but is not defibbable.
/:cl:

### CODE REVIEW

**Review by Henri215 — COMMENTED** [review]
image
Houston, we have a problem

**Comment by Henri215** [comment]
> image Houston, we have a problem

Looks like a problem with icondiffbot?

**Comment by Contrabang** [comment]
> > image Houston, we have a problem
> 
> Looks like a problem with icondiffbot?

Yeah, I pushed an empty commit and wasnt able to fix it, but it all looked fine on my end. It might be because the time for the sprite is 30+ seconds. If thats a problem I can just remove the animation alltogether

**Review by S34NW — APPROVED** [review]
deconflict innit

**Comment by Contrabang** [comment]
Deconflicted

**Review by farie82 — APPROVED** [review]

**Pull request merged**
