### PR TITLE
Nerfs Centcomm away mission armour

### PR DESCRIPTION
**Pull request by SamHPurp**
So the Thunderdome armour that spawns in this away mission is Death Squad level OP.... Lets fix that....

Keeping title/changelog vague to reduce people abusing this oversight in the interim.

Probably also worth looking at the amount of fireaxes that are there too... but lets at least get this fixed ASAP.

:cl: Purpose2
tweak: Fixes an oversight in Centcomm Away
/ :cl:

### CODE REVIEW

**Comment by uraniummeltdown** [comment]
You just made the armor extremely shitty, worse than Sec armor, it's basically non-existent now

**Comment by Aurorablade** [comment]
You also edited the stats directly on the map..
And this is making me and a few other mappers foam at the mouth.

**Comment by KingPhilipIII** [comment]
Deathsquad OP or not, most people are brought down with tasers or batons. Not lethals. If this is to prevent validhunting. Well nerfing it into the ground is boring too.

**Comment by FalseIncarnate** [comment]
I'd make a sub-type of the armor and add that to the map, rather than var-editing the mapped object. If the mission gets edited, and that armor gets moved around, it's just going to be easier on the future mappers if you have the sub-type for them to use instead of having to remember to re-edit the stats.

**Comment by Fox-McCloud** [comment]
don't var-edit something like this, on a map--it makes it terribly confusing and difficult to adjust, for the future.

Also, the numbers are pretty bad; it should be at *least* as strong as regular security armor.

**Comment by Kyep** [comment]
Varediting the item in the map itself is not the way to go.

Two better options:
A) Simply remove the armor from the map entirely. I only left it in because I (wrongly) thought its stats were terrible. If I had known its stats were good, I'd have removed it entirely, as I removed most of the rest of the stuff from the Thunderdome area, and (AFAIK) all of the other high-power items from the away mission. 
B) Create sub-types that have dramatically nerfed armor values, and search/replace on the map to swap out the current ones for completely nerfed versions. Maybe give them custom names, too, e.g: "old <color> thunderdome armor". Just so it is obvious they don't provide the same defense as the regular versions.

Personally, I prefer (A).

**Comment by ktoma36** [comment]
I myself have not encountered this away mission but perhaps make the armor only effective in the gateway mission itself, kind of like the wireless charging lasers in the terror spider mission. Unless there is no combat that would entitle such an effective piece of armor. If that is the case nerfing its armor value a bit would be good. From personal experience though deathsquad armor isn't too over powered, on its own at least. Its not stun proof nor does it do anything against toxic damaging weapons (black terror spiders in particular wreck anyone wearing ds armor).

**Comment by SamHPurp** [comment]
@Aurorablade I edited this on the map because otherwise if I edited the actual Thunderdome armour, changing how those conflicts go on the actual T-Dome Arena

I could make a subtype and nerf it on there as @kyep suggests. Or just delete.

When tweaking numbers you're always going to have people unhappy and will never satisfy anyone, cc @Fox-McCloud @uraniummeltdown .

I'm going to opt for the removal of the armour, which as Kyep stated he would have done had he known its stats.

**Comment by sothangel** [comment]
Remove and replace in the future with something more appropriate. Crew don't need access to super-OP armour, especially not with the flimsy bullshit excuse of "gateway loot".

**Comment by SamHPurp** [comment]
@ktoma36 doesn't matter that it isn't space proof, this armour is better than any other you can get in the game legitimately, and there are 8 of them. Which is mental.

**Comment by uraniummeltdown** [comment]
That's implying that all 8 people who take the armor are antags, when it's more likely to be 1 or maximum 2 people who do. And even antags with sec-level armor aren't OP or broken or scary.

**Comment by Fox-McCloud** [comment]
Just replace it with regular security armor, IMO.

**Pull request closed without merging**
