### PR TITLE
Added XenoBorg sprite for C.O.R.G.I

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
I would like to have this sprite for my cyborg character. It does not have The three panels for when opened, cell removed, wires cut. Also add theultimatechimera-C.O.R.G.I to custom_sprites.txt Think I had the path wrong too.
Images:
xenoborg1
xenoborg2
xenoborg3
xenoborg4

### CODE REVIEW

**Comment by fj45** [comment]
Pictures?

**Comment by ZomgPonies** [comment]
I'll have to say no to that one, due to the fact that it WAS used in xeno gamemode in the past, and might be used again for the same reason in the future.

**Comment by Ultimate-Chimera** [comment]
Alright, is there any other sprite I could have with the same type of thing or something?

**Comment by ZomgPonies** [comment]
The AI sprites already have a vast selection of styles and weird sprites. Letting you use the XenoAI one is just one more weird sprite

I don't think anyone would build 'xenoborgs' other than xenos. Hence why I have to refuse that sprite on the basis that it could confuse the playerbase. If you're going to submit a custom borg sprite, make sure it looks robotic, is reasonably sized (for combat balance reasons), and can't be mistaken for an antag.

**Comment by Ultimate-Chimera** [comment]
Makes sense, but I don't know how to sprite so... I just won't even bother about it. Thanks though.

**Pull request closed without merging**
