### PR TITLE
Adds power-generating treadmills to brig cells

### PR DESCRIPTION
**Pull request by Tastyfish**
Based on [this thread](http://nanotrasen.se/phpbb3/viewtopic.php?f=12&t=7395&start=10).

Bored of having nothing to do in a cell? Do you wish you could be superficially rewarded for not breaking your light? NanoTrasen has a new solution for you! Introducing **treadmills**!

Preview

- They produce about 2kW when running at full health, hunger, etc.
 - A peacekeeper/combat droid in mobile mode could produce significantly more.
- The prisoner gets 1 arcade ticket about every 30 seconds, assuming they are running.
 - The tickets are printed upon release, or in the case of the holding and perma cells, immediately upon earning each one, as they have no timer.

:cl:
rscadd: Adds treadmills to brig cells, to give the prisoners something productive to do.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
WHY

**Comment by pinatacolada** [comment]
YES

**Comment by DaveTheHeadcrab** [comment]
ELLIOT CAMPBELL APPROVED

**Comment by Magikarpet** [comment]
A concentration camp with treadmills - the dream

**Comment by Spacemanspark** [comment]
...
:+1:
I still want VR though.

**Comment by ScratKnapp** [comment]
:100:  :100: :100:

**Comment by theColdflame** [comment]
why reward people for getting brigged?
I like the treadmill though.

**Comment by Fox-McCloud** [comment]
VR would admittedly be interesting---could give people an outlet to legally grief each other in a safe, confined space.

**Comment by TheDZD** [comment]
The permabrig probably needs one or two of these too.

**Comment by Spacemanspark** [comment]
I think it does, @TheDZD.

**Comment by TheDZD** [comment]
Screenshots only show them in the regular brig cells, and .dmm diffs are hell to read through.

**Comment by Dumbdumn5** [comment]
VR would be damn cool if we had a few mapped out areas for it like the holodeck. Could do a few actioney things for combat, few simulated lounges because why not? If we have the space in Z-levels, this could be phenomenal. (No suggestions thread yet, take this as a shitpost, but for now, more power to you!)

**Comment by Spacemanspark** [comment]
Maybe even put a little dungeon in it.
And I'll go create that thread.

**Comment by FalseIncarnate** [comment]
VR is something we've toyed with trying in the past, and having goon's released code to work with will definitely help us handle potential problems regarding it

**Comment by Tastyfish** [comment]
@TheDZD The permabrig and holding cell have one as well.

**Comment by TheDZD** [comment]
Wonderful.

**Comment by Crazylemon64** [comment]
Hmm, this might give sec officers strapped for power up in the brig something to do while lazy engineering mucks about with the engine/solars setup.

**Comment by Fox-McCloud** [comment]
>Hmm, this might give sec officers strapped for power up in the brig something to do while lazy engineering mucks about with the engine/solars setup.

Or worse, officers arrest for vague reasons just to get prisoners to generate power for them =p

Fight the system, don't use the treadmills.

**Comment by Keilden** [comment]
I bet someone will find a way to force mobs to run them all just to generate tickets for sec.

**Comment by Tastyfish** [comment]
That would be pretty hilarious, actually.

**Pull request merged**
