### PR TITLE
Add detectives revolver as theft objective

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

This adds the detectives revolver, the DL-88 energy revolver as a theft objective, on account of it being both unique and special

## Why It's Good For The Game

Adding more theft objectives is just good, and the detectives feels awfully safe regarding their revolver, and it would be a shame if something happened to it.

## Images of changes

image

## Testing

image

## Changelog
:cl: ppi
add: Certain antagonist may get steal the detectives revolver as an objective.
/:cl:

### CODE REVIEW

**Comment by ArcZelf** [comment]
Judging by the screenshot provided, it's not very clear for newer players where the DL-88 comes from, if the objective could appear in the same sort of format that the other steal objectives does where it tells the player which role the item belongs to and where it could be that would be really appreciated =). (example below)
image

**Comment by ppi13** [comment]
No, it does, its just that when the objective is admin given it doesnt show up
image

**Comment by Danchi299** [comment]
> Add detectives ***revovler*** as theft objective

**Comment by farie82** [comment]
The design team voted and voted against the PR with the following main reason:
- Does security *really* need another theft objective in their department. Also the one department which is constantly involving with hunting down antags and fighting them if anything should have less theft objectives than the others.

Due to this I don't see this PR being approved in it's current form.

**Pull request closed without merging**
