### PR TITLE
Makes staff able to convert m/ahelp tickets to the other type

### PR DESCRIPTION
**Pull request by farie82**
## What Does This PR Do
Makes staff able to convert tickets to the other type.
If no staff is available to answer the ticket then a warning will be given to the person that converts the question.

Also did some minor refactoring

## Why It's Good For The Game
Mentors get asked admin related questions quite often. A quick conversion button will help them deal with it and will save trouble for the person asking it.

## Images of changes
image
Player perspective
image
Staff perspective

## Changelog
:cl:
add: Makes staff able to convert tickets to the other type.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Thank You

**Comment by procdrone** [comment]
Oh yes

**Comment by farie82** [comment]
> Please add a response in which will alert staff if none of the other party are online (Mentors get a message if they try to convert it to an ahelp with 0 admins online)

All the mentors getting the message or just the one converting it?

**Comment by AffectedArc07** [comment]
@farie82 Just the person who clicked it

**Comment by farie82** [comment]
> @farie82 Just the person who clicked it

image

Updated with this as warning. Defaults to no

**Pull request merged**
