### PR TITLE
Titanium

### PR DESCRIPTION
**Pull request by uraniummeltdown**
titanium

Adds titanium and plastitanium, titanium can be mined, plastitanium is an alloy of titanium+plasma
Use titanium to make shuttle [false]walls that aren't invincible, shuttle airlocks, shuttle floors, use plastitanium to make a sleek black shuttle wall and the red syndie shuttle floors
Survival pod walls made to be a subtype of titanium walls
Shuttle windows have explosion_block = 3 on them to resist explosions
Titanium and plastitanium walls both have explosion block = 3 and 4 to resist explosions
A few RnD recipes now require titanium

:cl:
add: Added titanium and plastitanium. Mine the asteroid for titanium, make plastitanium by smelting together titanium and plasma
add: You can build shuttle floors and walls with titanium and plastitanium. Can also make shuttle airlocks by applying titanium to a non-mineral airlock
tweak: Shuttle windows have explosion resistance now
tweak: A few RnD recipes require titanium now
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
little question: did you check if red floor counts as brig floor?

**Comment by uraniummeltdown** [comment]
yes

**Comment by alexkar598** [comment]
~~is making custom shuttle the next thing on the list?~~

**Comment by uraniummeltdown** [comment]
i wish, no server has custom shuttles yet

**Comment by alexkar598** [comment]
tg is making progress by allowing shuttle expansions but this is getting offtopic

**Comment by FalseIncarnate** [comment]
Buildable shuttle windows using titanium and glass planned?

**Comment by uraniummeltdown** [comment]
Yeah it's planned, I was reluctant because of balance memes because people might deconstruct the shuttle windows on the pods for titanium, I don't really think it's a big deal though

**Comment by alexkar598** [comment]
13 minutes,6 comments

**Comment by FalseIncarnate** [comment]
Isn’t the survival pod a bit of an investment though? Seems like if they want to strip it down for parts it is a net loss for them

**Comment by FalseIncarnate** [comment]
Oh, you probably meant the escape pods... could be a non-deconstructable variant for mapped shuttles

**Comment by FreeStylaLT** [comment]
Oh yeah, escape pods being a non-deconstructable variant for mapped shuttles does sound like a good idea

**Comment by FreeStylaLT** [comment]
Survival pods do also seem like an investment, yes

**Comment by uraniummeltdown** [comment]
Yeah that's probably the best thing to do, just make the escape pod shuttle windows on the maps not drop titanium

**Comment by FreeStylaLT** [comment]
I agree, making the escape pod shuttle windows on the maps not drop titanium is a viable solution.

**Comment by alexkar598** [comment]
does it means we can build on shuttle now or is it still not allowed by the game?

**Comment by FreeStylaLT** [comment]
Yes, that is an excellent inquiry - are we now allowed to build on shuttle or is it prohibited by the game itself still?

**Comment by uraniummeltdown** [comment]
The shuttle doesn't restrict you from building on it anyway

**Comment by EldritchSigma** [comment]
Question: Any chance that the low capacity syringe and the cryostasis syringe alongside the utterly crappy mech mounted medibeam will be ported at some point? Considering Titanium will be a thing finally that gets my hopes up.

**Comment by alexkar598** [comment]
whoa whoa whoa.are you saying you want big features added to paradise?

**Comment by taukausanake** [comment]
Part of me likes this because it means new materials, but the rest of me thinks why and is it even good/needed. If being able to construct shuttles then awesome but it's not. The existing turfs aren't following these new functions, and rightfully so- you don't want people tearing up the escape pods at round start (or maybe you do if escape alone and memes).
Maybe it would be okay if you make designated areas that are okay to build shuttle turfs on and those are the only turfs that will move with the area. I can imagine a shuttle crafting bay (maybe for mechanic) that gives you so much area to work with and any shuttle turfs and objects on those turfs there will transport with it. The only thing I think I'm missing is the docking points which I have no idea how they work.

Would anything I just said above work the way I'm thinking it would?

**Comment by KasparoVy** [comment]
Hell yeah. More stuff for me to mine I will NEVER turn down.

**Comment by EldritchSigma** [comment]
But yeah without any new items construct from RnD this really seems like just another sci nerf with new walls you can build... really there should be some new items you can build with that titanium at least. Or you know... make mining more exciting so people actually bother mining consistently *cough*

I mean I do like Titanium and that it gets ported now.

**Comment by KasparoVy** [comment]
No idea. I feel there might be misunderstanding.

**Comment by FalseIncarnate** [comment]
Only way I can see this as being a nerf is if there is some hidden rarity to titanium ore that places it into the realm of anomaly cores... which there is not. It just diversifies the materials needed to make things, which is a fancy way of saying "iron is not the make-all resource so those miners will need to actually mine more types of stuff".

As for "making mining more exciting", you realize that mining can get fairly exciting if you move into the western portion of the asteroid, and not stay solely in the safe-space east side, as there are monsters that want to eat your face? Were making mining more interesting and involved actually be a goal being worked on, that would be in a separate PR anyways as that would be its own undertaking and well beyond the scope of an atomic PR.

Please keep comments relevant to the actual changes of this PR, and not tangentially related topics.

**Comment by EldritchSigma** [comment]
Actually... it has TGs rarity. I take it back what I said. Its slightly less common as plasma ore.

**Comment by FalseIncarnate** [comment]
For reference: there are a few types of mining turfs with different ore chances.

The base type random mine turf has titanium with a chance of 11. To put this in perspective, these same turfs have gold as chance 10, plasma as chance 20, BS crystals as chance 1, and iron as chance 40.

The high chance random mine turf has titanium as a comfortable 45, matching gold at the same chance. Plasma is 50 (only a little higher), BS crystals are at 20, and iron isn't even listed for this turf.

The low chance random mine turf has titanium at 4 (again matching gold), plasma at 15, BS crystals at 1, and iron at 40.

However, to truly put this in perspective, titanium gets a point value of 50 (equivalent to diamonds), which is just under triple the value of gold (18 points), so getting miners to actually pick this up shouldn't be too difficult as it isn't that rare and is definitely worth collecting. Plus, aside from being more common that diamonds, it also has a spread chance, meaning you can find veins of titanium and not just lone pieces.

**Comment by Citinited** [comment]
Does this mean we can deconstruct the shuttle / pods now? 🤔

**Comment by uraniummeltdown** [comment]
Nope, those are /turf/shuttle/wall, this is /turf/simulated/wall/mineral/titanium

**Comment by Fox-McCloud** [comment]
Last nitpick:

- don't forget to add titanium to to the power drill and jaws of life
- titanium on all the alien tools

Think you may have just forgot those

other than that 👍

**Comment by Fox-McCloud** [comment]
Stone-hard, machine gun, firing at the ones who runnnnn, stone-hard, thus bulletproof glassssssssss

**Pull request merged**
