### PR TITLE
Adds Grenade, Flash, and EMP in-hands

### PR DESCRIPTION
**Pull request by Fox-McCloud**
https://github.com/tgstation/-tg-station/pull/6473

- Updates the in-hand sprites of the EMP grenade, grenades, and flash

Basically all of these used the same icon, so you had no idea if someone was carrying a flash or a grenade of some sort.

- EMP has its own unique in-hand
- Flashes (toy and real) have their own unique in-hand
- Grenades (of all types) have their own unique in-hands

Other Stuff
- Adds in the memorizer--custom flash thing for admins to have fun with
- updates some text for using the flash and gives it a custom notification when someone AoE flashes with it
- Updates the traitor clown grenade to use the banana grenade sprite as opposed to the chemical grenade sprite.

Side note: we really need a refactor of our in-hands; it's becoming a mess.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I feel it is pertinent to note that I don't believe the inhands are very important, but more unique sprites is hardly a bad thing.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

I couldn't disagree more. Someone charging at you with an e-sword sprite yields far more of a reaction than charging at someone with a medical kit. People react differently to what they see a person has. Visual communication of gameplay elements is important.

**Comment by tigercat2000** [comment]
@Fox-McCloud I probably should have specified inhands for small items, which are harder to tell apart than just shiftclicking them, but you make a point. Anyhow.

**Comment by ZomgPonies** [comment]
:+1:

**Comment by Plotron** [comment]
Double yay!
I won't have to shift-click like a madman whenever I see someone with a grenade (flash? bang? EMP?! IED? VALVE?!). It's still a good habit, though.

**Pull request merged**
