### PR TITLE
Removes PDA Chatrooms

### PR DESCRIPTION
**Pull request by Kyep**
These are never used, except to spam invites in a way which lags the server.
This PR axes them for good.

🆑 Kyep
del: Removed PDA chatrooms. NTNet Relay Chatrooms, part of modular computers, still exist.
/🆑

### CODE REVIEW

**Comment by Allfd** [comment]
Big 👎 ,  this is a major nerf to my ability to bring down the server with chat invites.

**Comment by RyanSmake** [comment]
It might be beneficial to inform people with the CL that modular computers retain their superior chatroom program.

**Comment by Kyep** [comment]
Modular computers even have chatrooms?
Wasn't aware - I never touch modular computers, as I find them inferior to the regular versions.

**Comment by Fox-McCloud** [comment]
Good riddance.

**Comment by RyanSmake** [comment]
@Kyep That's what I am talking about, do not remove it. Use the CL to advertise it, as it is the already existing alternative, and people don't use those chatrooms because they do not know of it.

**Comment by Kyep** [comment]
@RyanSmake Done.

**Comment by Vivalas** [comment]
I enjoyed using it, since it is was an actually somewhat neat way to collaborate with other people. I managed to form a tunnel snakes group of freelance assistants once. There are probably more in depth uses, but I suppose performance is an issue

**Comment by tigercat2000** [comment]
We'd be better off just trying to implement NTNet chatrooms some time in the future. We're gonna remove these broken (and not very well made) ones for now.

**Pull request merged**
