### PR TITLE
Atmos grille purge

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Removes the superfluous grilles over the atmos holding tank walls.

## Why It's Good For The Game
These are ugly as sin, doubly so with the windows trying to connect to the walls under the grilles.

## Images of changes
image
image

## Changelog
:cl:
tweak: Removed redundant atmos grilles
/:cl:

### CODE REVIEW

**Comment by hal9000PR** [comment]
Soul removal

**Comment by Contrabang** [comment]
I'm pretty sure these grilles help stop meteors somewhat, so the tanks don't get breached every time there's a meteor storm.

**Review by SteelSlayer — APPROVED** [review]
Looks fine, just needs a deconflict

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Pull request merged**
