### PR TITLE
Plasmaman Lawyer Suit

### PR DESCRIPTION
**Pull request by uraniummeltdown**
https://github.com/d3athrow/vgstation13/pull/13759

plasmalawyer

:cl:
add: Plasmaman IAA/Lawyers now have a unique suit.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'm still kinda of the mindset that plasmamen should have a unique jumpsuit as opposed to a free spacesuit---it allows for better customization on player's behalf, but...that's a ways off.

**Comment by Aurorablade** [comment]
Anyway you can do a brown recolor and give it to the librian/jounalist? ...or want me to recoloring and link it here? cuase yeah i saw that one too...

**Comment by uraniummeltdown** [comment]
I'm no good at spriting, but if you could link librarian sprites here that would be great

**Comment by KasparoVy** [comment]
@Fox-McCloud Were you thinking of reflagging the plasmamaman suits as biosuits while maintaining all other existing features minus space protection or something?

**Comment by DesolateG** [comment]
So, why do plasmamen cost 100 karma?

**Comment by Fox-McCloud** [comment]
>Were you thinking of reflagging the plasmamaman suits as biosuits while maintaining all other existing features minus space protection or something? Just curious

They wouldn't spawn with their space suits at all; they'd have a unique helmet and a unique *jumpsuit*. If they had their unique helmet and unique jumpsuit, together, then it would prevent them from catching on fire. 

It would allow for much greater customization (and job mobility) for plasmamen.

**Comment by taukausanake** [comment]
I rather they stay with the spacesuit, as OP as it might be. You paid 100 karma for something, might as well be this even if not for the best reason. At the very worse a plasmaman is job-locked from any other uniform without better atmos and/or catching on fire

**Comment by fludd12** [comment]
>They wouldn't spawn with their space suits at all; they'd have a unique helmet and a unique jumpsuit.

At that point, players who wanted to play plasmamen would simply go to /tg/ or some derivative, I'd think. At the very least, the karma cost should be lowered if this happened.

**Comment by scrubmcnoob** [comment]
To be fair, Vox are space proof without a suit and I have yet to see a complaint about that. Not saying anything but just saying *cough*

**Comment by SamHPurp** [comment]
@Fox-McCloud Yeah because lets make more Human+ races.... This is a bad idea. Stop it.

**Comment by HugoLuman** [comment]
Besides, the helmet would still hide their features, so I don't see how much more customization that brings. We'd be better off letting them attach things to their suits

**Comment by Fox-McCloud** [comment]
>Yeah because lets make more Human+ races.... This is a bad idea. Stop it.

Axing the suit would be a *nerf* to Plasmamen, not a buff; having free, round-start parapen and syringe gun protection, space immunity, chemical penetration immunity, virus immunity, and temperature immunity and dropping that is "making them human+"

**Comment by Spacemanspark** [comment]
They're 100 karma points to purchase.
I know that you get all the karma things and then some for free, but to a normal player that can take upwards of a fucking year to get. Don't take away the damn suit, makes it even more pointless to play.

**Comment by Fox-McCloud** [comment]
>They're 100 karma points to purchase.

This is not a valid argument, at all; it has never been policy that a race is supposed to be a particular power level because of how expensive/cheap it is, karma wise. The pure intention of karma cost was a control to how many of that species we wanted on station (ie: rarity)--nothing more, nothing less.

**Comment by Spacemanspark** [comment]
Honestly it should.
If I'm going to spend almost a year on something it sure be damn well worth it.

**Comment by Fox-McCloud** [comment]
>Honestly it should.

Giving gameplay a mechanical advantage to players *purely* because they have more hours invested on a server (or managed to become admin) is poor game design; how well or poorly a player does in a game should be based on their merit and mechanical skill within a game, not just because they've managed to stick it out longer than everyone else. Establishing such a policy is grossly unfair; if someone is of equal skill level with someone else, but one gains the advantage purely because "I have 1000 hours on this server and you have 100" is, again, poor game design.

It's also a bit odd that for the stated *overall* goal of karma (rewarding roleplay), that you would want to link it to something that is largely irrelevant to roleplay (gameplay mechanics advantage)---which is often repeatedly stated by various individuals to be antithetical to roleplay.

**Comment by DesolateG** [comment]
Gotta disagree with your logic fox

**Comment by Spacemanspark** [comment]
Mechanics can help guide roleplay along, or destroy it.
I'm not suggesting making races super badass, I'm suggesting they be unique.

**Comment by Fox-McCloud** [comment]
>I'm not suggesting making races super badass, I'm suggesting they be unique.

And I never stated that they couldn't be--my argument was addressing his point of dropping the suit would make them "Human+", when that is clearly not even remotely what it would do, as they're farm ore like that *now*.

**Comment by DesolateG** [comment]
Why not just remove humans? Everyone knows how unrealistic humans in deep space is. Can't cooperate long enough to achieve that and will probably nuke eachother instead

**Comment by Spacemanspark** [comment]
How is removing their hardsuit and giving them a jumpsuit not making them Human+?

**Comment by Fox-McCloud** [comment]
How is going from having a spacesuit to not having a spacesuit an objective improvement?

**Comment by Spacemanspark** [comment]
Human+

**Pull request merged**
