### PR TITLE
High-Pop Job Slots

### PR DESCRIPTION
**Pull request by Kyep**
This PR adjusts job slots based on the number of players on the server.
Specifically, at roundstart, it checks if there are >= 80 players on the server. 
If this is true, it updates the available job slots based on the (new) jobs_highpop.txt config file.
In the **example** config provided, that adds the following slots:
- +2 doctors (5->7)
- +2 engineers (5->7)
- +1 atmos tech (3->4)
- +2 sec officers (7->9)
- +2 scientist (3->5)
- +1 cargo tech (4->5)
- +2 shaft miners (3->5)
- +1 janitor (1->2)

All-in-all, this adds +13 job slots to the server when there are lots of players connected.
It only adds these at roundstart, though. So, they will primarily be used by latejoin players.
This is intentional - it ensures that every department should have at least a basic level of staffing before additional slots are opened.

🆑 Kyep
add: Additional job slots are now available at 80+ server population.
/🆑

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
iirc there are only 8 total officer lockers in brig, not counting the Arrivals checkpoint one. Is the 9th one meant to use the Arrivals one with this change?

**Comment by Kyep** [comment]
They can do that. They can also have cargo order them gear.

**Comment by granodd** [comment]
>adding more atmos tech slots when it's high pop

More atmos hardsuits, WHEN?! But no seriously, this is really annoying that the max is 3 but there's only _2 hardsuits_. This will be even more annoying when there's 4 techs and only 2 suits.

**Comment by davidchan13** [comment]
How hard would it be to do a 'gamma armory' style sec locker room where if 9-10+ sec officers are active then a batch of lockers are bluespaced to the station? Or only triggers at 80+ population?

**Comment by Allfd** [comment]
Many thanks for this!

**Comment by Vivalas** [comment]
I think not everyone having equipment on high pop gives cargo a little more to do. It's the body and the access that's important, not so much the gear. Everyone starts with *basic* equipment to perform their role with.

**Comment by KasparoVy** [comment]
10 janitors.

**Comment by tigercat2000** [comment]
Some of these overrides don't really make any sense. Since we're going to end up playing with this config file, I can't give you "real" values yet -- So, @Kyep could you please just copy-paste `jobs.txt` into `jobs_highpop.txt` for now, so that any downstreams don't experience an issue if they somehow end up at 80 pop?

**Comment by Kyep** [comment]
@tigercat2000 Done. jobs_highpop.txt is now simply a copy of jobs.txt.

**Pull request merged**
