### PR TITLE
VG multitool menu port & more buildable atmos equipment

### PR DESCRIPTION
**Pull request by PJB3005**
ports /vg/ multitool menus, makes a lot more atmospherics equipment buildable & configurable with multitool menus (vents, air injectors, sensors, DP vents, Dvalves, etc...)

AAC: scripting atmos

### CODE REVIEW

**Comment by PJB3005** [comment]
*goes insane about merge conflicts

**Comment by ZomgPonies** [comment]
Fix the merge conflicts, make sure it's fox.dm and not Fox.dm in the dme for consistency and I'll make sure it's merged promptly this time.

**Comment by PJB3005** [comment]
done!

**Comment by Fox-McCloud** [comment]
@PJB3005 

We still need to discuss this at length; could you please notify me  (here or on the forums) of what day would be a good time?

**Comment by PJB3005** [comment]
I'm not the kind of person that's good with specific moments, it's probably just best if we ping eachother on IRC when it's convenient

**Comment by Markolie** [comment]
We've discussed the matter, and we've come to the conclusion that we'd rather not implement this feature on the server. The feature effectively allows you to do anything you want with the atmospherics system, as long as you have the board and know how to code. However, this knowledge is limited to a select number of people, and will probably not be used much, while those who do know how to use it will have a major advantage over others. While there's certainly a lot of "difficult" features in the game, we'd rather avoid adding another feature that requires extensive OOC knowledge.

**Comment by PJB3005** [comment]
really? rip 2500 lines of code ;_;

**Comment by PJB3005** [comment]
would it still be unbalanced if I removed the AAC?

**Comment by tigercat2000** [comment]
@PJB3005 for what it's worth, I would love to see this again now that we have LINDA

*dunno how much that is worth tho*

**Comment by PJB3005** [comment]
go ahead and reopen it, but I'm not coding anything for it anymore.

**Pull request closed without merging**
