### PR TITLE
Removes A* call and Fixes Blood Virus Infections

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/tgstation/pull/28197

The less we rely on A* the better....

Also means that blood that has viruses in it will actually be infectious now (previously blood that had viruses in it just sat there and did nothing while processing forever).

:cl: Fox McCloud
fix: Blood (on the floor) that has viruses in it will now properly infect you, if you get near
/:cl:

### CODE REVIEW

**Comment by pinatacolada** [comment]
Surgery uses a* for similar purposes in https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/surgery.dm#L203 and below

**Comment by Fox-McCloud** [comment]
I'll let you change those.

**Comment by taukausanake** [comment]
Little bit of background for those of us who don't know what A* ( AStar() ) does? I like learning new things

**Comment by pinatacolada** [comment]
actually I wanted to refactor a thing or two around the surgery germs, i'll include it in it, I'll look at it sometime this week

**Comment by Anticept** [comment]
@taukausanake A* is a search/pathfinding algorithm. Quite expensive, but it would allow contracting disease without a direct line of sight. It gets exponentially more expensive in complex corridors though if it doesn't use any optimization. In large part, players won't even notice this change.

Here's a visual example of it:

https://upload.wikimedia.org/wikipedia/commons/5/5d/Astar_progress_animation.gif
image

**Comment by tigercat2000** [comment]
A* is a bit intensive for something that almost always has a range <2.

**Comment by Anticept** [comment]
And incredibly intensive as soon as you introduce an obstacle and a range larger than that.

**Pull request merged**
