### PR TITLE
New Lavaland Outpost (First Time Mapping) [ReAdded]

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
Change Old Look of Lavaland Outpost to new one

## Why It's Good For The Game
It will create better experience and give more area to explore and commit your crimes.

## Images of changes
Before:
image

After:
ameno

## Testing
Tested on Local server using copy of paradise files.
Only issue found on test server was dissapearing catwalk.

## Changelog
:cl:
add: Added whole new lavaland outpost.
/:cl:

My Previous "pull" request got messed up so i placed NEW one to fix my first time mistake (my first time using github).
The previous "pull" request got better feedback, so i suggest check it: https://github.com/ParadiseSS13/Paradise/pull/19757

### CODE REVIEW

**Comment by Henri215** [comment]
twofreezers
Duplicated freezer here.

**Comment by GDNgit** [comment]
The theming on this is soooo fucking good

**Comment by S34NW** [comment]
image

This section could probably do with it's own APC and wiring, and be scoped into `/area/mine/abandoned`

The following air alarms are custom placements and should use the "[direction] bump" instance instead:
image
image

The following crate and custom placements can just be replaced with a single `/obj/structure/closet/crate/freezer/iv_storage`
image

This light is pixel shifted south for no reason:
image

Please go through the security cameras and update the `c_tag` variable to include `Mining Outpost -` before whatever was already there. This makes it much easier to search for mining outpost cameras. Most if not all of these need updating, sorry.
image

Please standardise the pixel offsets for the mining APCs, they should only be 24 in _either_ `pixel_x` or `pixel_y`
image

You don't actually need the `/turf/simulated/floor/mech_bay_recharge_floor` floor type here if you don't want it. The sudden transition from dark tiles to those is a little jarring. That's up to you though I'm not going to demand you change it.
image

The area incorrectly includes a bit of outside here:
image

This area boudnary should be done at one of the doors in this corridor, not in the middle of the corridor.
image

I know we do this on the current map but we should just delete this light and remove the area too, it causes weirdness with the weather otherwise.
image

I _really_ like this, we should look into why it collapses routstart as catwalks are supposed to be lafa-safe
image

**Review by S34NW — CHANGES_REQUESTED** [review]
Some blocking changes above that need addressing please

**Review by S34NW — CHANGES_REQUESTED** [review]
A few more things:

image
All light switches have lost directions, they should have relevant directions.

image
APC on the same wall as a light, please shift the light somewhere else

image
This room has no APC

image
Cobweb is not in the corner

image
Some double walls, could do with slimming down?

image
This area has been var-edited

image
This room uses the same area as another part of the outpost, please just smack it in the EVA area and drop the air alarm.

image
The cameras still do not have "mining outpost" in their `c_tag` variable. In this example it should be: `"Mining Outpost - Dinner Room"`

image
You have properly added a node here, but lost the wire leading to the terminal.

image
Medbay should use the `/area/mine/sleeper` area, currently it shares the same area as the hallway and leads to double APCs.

image
Mech bay shares an area with the hallway, leading to double APCs


You should also do a merge master, the new catwalks seem to be unloading for me when I open the map.

**Review by S34NW — CHANGES_REQUESTED** [review]
Revoking approval while line endings are sorted

**Review by S34NW — APPROVED** [review]

**Review by SteelSlayer — COMMENTED** [review]
Please add `req_access_txt = "54"` to the two double-tile airlocks to keep consistent with the access the airlocks had before.

**Comment by Venuska1117** [comment]
> req_access_txt = "54"

what about other airlocks? (other than double doors)

**Comment by SteelSlayer** [comment]
Yeah, the other airlocks might need that access to. IIRC, they were all mining access locked. I would go over them on master to see if you need to change them in your remap.

**Comment by Venuska1117** [comment]
> Yeah, the other airlocks might need that access to. IIRC, they were all mining access locked. I would go over them on master to see if you need to change them in your remap.

how about now?

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
