### PR TITLE
Begins to add departmental protolathes

### PR DESCRIPTION
**Pull request by Crazylemon64**
Still a WIP, wait for more.

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
You ninja'd the crab!

**Comment by Crazylemon64** [comment]
Welllllllll

I guess, that if @TheDZD wants to do this, they can.

**Comment by TheDZD** [comment]
I was tossing the idea round and was planning on implementing it myself, but if you want to do it your own way, that's fine with me.

**Comment by Crazylemon64** [comment]
Alright, I'll see about getting this back on its feet, then.

**Comment by Fox-McCloud** [comment]
Not really sure the purpose/goal of this PR?

**Comment by Crazylemon64** [comment]
It's to handle the problem of distribution, with science things - this way, people can acquire tools from research without the impedance of needing to visit a central locale, and specific departments can receive things they need at will - like engineering being able to build machines as they need to, or medical getting the newest scalpels and HUDs without the risk of science forgetting/not caring because they got their greentext already.

**Comment by taukausanake** [comment]
You mean with the distribution of the tech discs in your other PR?

**Comment by Crazylemon64** [comment]
Well, this will also help deal with the "many gun designs see no use" issue, since currently, the warden/anyone else with armory access needs to go from wherever they are, all the way to R&D, ask the scientist for a gun, and walk back either with the gun in their inventory, or in some mass storage object of some form, such as a closet. The latter being rather risky, gun distribution is often very rare. With this, the more mundane weaponry will have a chance to shine, especially with the science nerf PR making it difficult to raise combat to the point where you can make the "OP" weapons (X-ray, in particular).

**Comment by Fox-McCloud** [comment]
Have quite a few thoughts on this, but I'll update/share later.

**Comment by Fox-McCloud** [comment]
Alright.

I don't like this at all. It's going to decrease the amount of co-operation between departments even more, not to mention wind up having every single department (if even only the heads) clamoring for access to the ore redemption machine---and you can bet your butt that security, by virtue of having most of the force on the station, is going to take most of the minerals so they can have every officer walking around with a bluespace stun baton and 5+ guns in backpack and all fully augmented+implanted because they have their very own field medic to do so.

This also means that if you're a traitor, the optimal path is to *nod* to R&D because it increases the power of your biggest adversary, security. 

This is akin to allowing science/medical order+approve crates themselves if they can manage to get ahold of an "medical cargo console" or something similar. At the end of the day, it's going to decrease the amount of co-operation amongst departments, generate animosity, and increase the whole "stay in my department and never interact with anyone" syndrome.

If you have medical issues, you go to medical---if you have security issues, you go to security--if you have logistics/supplies issues, you go to cargo---if you have repair/damage issues, you go to engineering-----if you want better upgrades, you go to science.

The station functions 100% fine without R&D doing anything (aside from maybe the chef on high pop)--what science produces are largely luxury items that make things easier to do/easier to complete.  The sole exception is some machinery for when bombs go off.

Another issue is that this is going to turn engineering into science 2.0: Why do your actual job when you can just make cool machines on the outpost (like genetics and the likes) and utilize those to your advantage? 

I know there is some general frustration with not getting things from science, but I generally find that if things aren't being given out:

- R&D wasn't done to begin with
- Mining never delivered on materials
- No one bothered asking for things.

I've generally found that when R&D actually did research and they had the materials for it, I'd get that item--yes, there's a few assholes out there who refuse, but in general, the biggest reason why I didn't get something was usually because R&D wasn't done to begin with.

**Comment by Crazylemon64** [comment]
You have good points! @TheDZD, you can take this on if you want!

**Pull request closed without merging**
