### PR TITLE
Clarify what the sleeper chemical bars mean.

### PR DESCRIPTION
**Pull request by moxian**
## What Does This PR Do
Add a bit of verbosity to the chemical bars display on the sleeper.

## Why It's Good For The Game
It was just today that I found out that the bars on the sleeper display represent the current amount of chemicals *in the occupant*. Before that I believed those were the chemicals *in the sleeper* and the bar slowly decreasing represented the transfer of chemicals from the sleeper to the occupant.
On discord three people told me that they had the same belief for quite a while.
Hopefully being a bit more descriptive here would slightly reduce malpracticebay occurrence rate.

## Images of changes
20201025-022656-C0njDtUBr8

## Changelog
:cl:
tweak: Clarified the meaning of chemical bars in the sleeper UI
/:cl:

### CODE REVIEW

**Comment by Kiyahitayika** [comment]
Yes! It took me a while to figure this out too when I started. Definitely a good idea to add a tooltip for this.

**Comment by Carthusia** [comment]
For the longest time I always thought it was slowly injecting chems into people, rather than just instantly doing it.

This will help newer people learn this INSANELY USEFUL FACT, much quicker

**Comment by ppi13** [comment]
People thought the sleeper is automatic?
That... kinda explains a few things.

**Comment by procdrone** [comment]
Hm, I never had that kind of problem myself. 

Also a reminder to everyone, syndicate sleeper can be operated from the inside - that means you can inject yourself with chems yourself.

**Pull request merged**
