### PR TITLE
Sprite: Stage 1 - Cleanup - AIBOTS

### PR DESCRIPTION
**Pull request by Oyu07**
## What Does This PR Do
Removes unused sprites
- Farmbot
- HonkBuddy
- MineBot OLD
- Bot Proxy
- Unused Medibot sprites
- Fetchbot
- Servoskull

## Why It's Good For The Game
General Sprite cleanup

## Testing
Check code for any and all references

## Changelog
:cl:
imagedel: Deleted Unused bot sprites, Farm, Honbuddy, Minebot old, servoskull, fetchbot, bot proxy, unused medbot sprites
/:cl:

### CODE REVIEW

**Review by Henri215 — COMMENTED** [review]
image

Forgot to remove these?

**Comment by Oyu07** [comment]
> image
> 
> 
> 
> Forgot to remove these?

Appears that way. Will update tonight

**Review by Henri215 — APPROVED** [review]
Lewcs good to me now

**Review by Sirryan2002 — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Comment by S34NW** [comment]
No need for ramon input, this is tech debt

**Pull request merged**
