### PR TITLE
Purges Unused Mining Files

### PR DESCRIPTION
**Pull request by Fox-McCloud**
We're never going to use any of these, and I'm tired of them cluttering up the mining folder.

### CODE REVIEW

**Comment by Twinmold93** [comment]
@Fox-McCloud Labor camp uses the old system, if I'm not mistaken. You might want to ensure this doesn't utterly destroy that, or update labor camp to use ore redemption.

**Comment by Fox-McCloud** [comment]
none of these files are even compiled into things....

**Comment by Twinmold93** [comment]
Then there shouldn't be an issue. Alloy itself appeared as a flag for me, considering if I'm not mistaken it's the same system that was originally used, and the machines in labor camp appear almost identical to the original set up.

**Comment by FreeStylaLT** [comment]
Looks like Fox went down the _shaft_ to get rid of the trash

**Comment by FreeStylaLT** [comment]
You could say my puns _rock_

**Comment by FreeStylaLT** [comment]
The redundancies were _mined out_

**Comment by FreeStylaLT** [comment]
I'm glad we got rid of all this extra weight before it all _caved_ in on itself

**Comment by TheDZD** [comment]
I honestly don't know why I left these in the folder after making them not be compiled into the .dmb.

**Pull request merged**
