### PR TITLE
Borg QOD improvements

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
Quality of death: Power warning is on a 2 second cooldown.

:cl: Tayyyyyyy
tweak: Borg power warning is on a 2 second cooldown
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
Make it 5 seconds

**Comment by Tayyyyyyy** [comment]
Unfortunately we have a thing where emote CDs must have 2 second cooldowns, or else it'd require further snowflake code. It's obviously doable but I don't want to spaghettify the code further unless it's really necessary.

**Comment by Tayyyyyyy** [comment]
Well, I think there might be some interesting ways to make cooldowns more flexible, but it might be outside the scope of this PR. I'll think about it...

**Comment by Birdtalon** [comment]
@Tayyyyyyy `handle_emote_CD(50)`

It should be already handled on that proc.

**Comment by davidchan13** [comment]
Could do without the power warning (they already get an icon on their HUD, if they can't see that what is a chat notification going to do?), but having a persistent GPS on every borg would be cool.

**Comment by Tayyyyyyy** [comment]
@Birdtalon you're right. I don't know how I didn't see that.

**Comment by alexkar598** [comment]
But but how can I do an SOS in buzzes if its on 2 sec cool down?

**Comment by Tayyyyyyy** [comment]
Borgs communicating with Morse code was too powerful, this PR will slow down the rate of Morse code communication 😛

I think a 5 second cooldown probably wouldn't hurt. Will update when I have a chance.

**Comment by Fox-McCloud** [comment]
The power warning having a cooldown makes sense, but borgs being able to see their own position, to a T? Not keen on that.

**Comment by Tayyyyyyy** [comment]
@Fox-McCloud the only times I've found myself pestering the AI for my location is when trying to find a downed borg or crew member in maint somewhere, so I don't think it'll be that big a deal. If we're afraid borgs will start doing space exploration the z coordinate could be hidden, maybe?

**Comment by davidchan13** [comment]
It'd be more balanced if it functioned as a built in GPS, so other players could track the borgs, perhaps with the option to turn the beacon off to save power?

If borgs are exploring space they are most likely ignoring their laws though.

**Comment by Tayyyyyyy** [comment]
> If borgs are exploring space they are most likely ignoring their laws though.

This is a good point. I don't see too much room for abuse here, but then again maybe I'm not thinking of something.

> It'd be more balanced if it functioned as a built in GPS, so other players could track the borgs

The robotics console provides this functionality already!

**Comment by davidchan13** [comment]
@Tayyyyyyy I get what you're saying, but the GPS is available to a wider group of people, and if say a Pod Pilot or Miner is looking to track a rogue borg, it's harder to counter or predict if someone doesn't have to use their radio to relay that info, channels the borg/AI likely have access to anyways.

It's not huge but being able to track the borgs might make GPS units more desirable to have, and would also amusingly make borgs targetable by BSA, giving them incentive to ensure the engineers set it somewhere secure.

**Comment by Tayyyyyyy** [comment]
Oh, I get what you're saying. That's an interesting idea. It would probably involve giving borgs some internal GPS devices...

Unfortunately my laptop's touchpad is having issues so doing anything complicated is a pain right now. I also think that it could be more balance altering than this change, so I will put your idea outside of the scope of this PR, for now 😛

**Comment by tigercat2000** [comment]
Please remove the x/y/z coord tracker. If you would like to replace it with something, display the area of the cyborg, like the AI status panel does.

**Comment by Tayyyyyyy** [comment]
@tigercat2000 can I do an x/y coord tracker instead? The issue is that it's hard to find someone in scimaint (150, 100) even if you know that you're already in scimaint.

**Comment by tigercat2000** [comment]
@Tayyyyyyy We would rather avoid absolute value coordinates being available to borgs in a raw form such as this.

**Comment by Tayyyyyyy** [comment]
@tigercat2000 I've updated the PR to not include the QOL stuff...gonna do that stuff in a different PR

**Comment by DarkPyrolord** [comment]
👍

**Pull request merged**
