### PR TITLE
Revert "Removes ability to put collars on jumpsuits"

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Reverts ParadiseSS13/Paradise#15155

This was merged before the 24 hour mark, and, furthermore, it was labeled as a controversial PR.  It was only up a total of ~10 hours and 12 minutes before being merged.

Controversial PRs require a higher amount of consensus reached before they can be merged, even post 24 hours, but an actual feature change shouldn't have been merged before 24 hours, let alone a *controversial* feature removal.

### CODE REVIEW

**Review by AffectedArc07 — APPROVED** [review]
Even though I don't agree design wise, I'm agreeing with this PR for the sake of procedures and proper processes being upheld.

**Comment by Spacemanspark** [comment]
Ansari is bant

More seriously, is the consensus for the actual feature being drawn from this PR, or are we reverting it and making a new PR afterwards to place the feature back in with proper procedure again?
Asking so it's clear for everyone what's happening.

**Comment by S34NW** [comment]
As long as the PR is immediately reopened for visible discussion. As I think the majority opinion was in favour of the PR

**Comment by procdrone** [comment]
I bet Fox just wants to ERP

**Comment by Spacemanspark** [comment]
Not really appropriate.

**Comment by Necaladun** [comment]
Procedure is important yes.

**Comment by Dumbdumn5** [comment]
Procedure over design in this case as well. Speedmerging something on the grounds of a design decision without leaving time for deliberation and actual consideration of the feature removal with community input is a shitty thing to do, even if it would likely have resulted in the same outcome. :+1:

**Comment by AffectedArc07** [comment]
Merging because procedure.

**Pull request merged**
