### PR TITLE
Procedural Map Generator System (Port from -tg-)

### PR DESCRIPTION
**Pull request by tigercat2000**
This ports tgstation/-tg-station#7751.

Players; You may see admin events or away missions with entirely randomly generated parts to them.

Admins; This allows you to generate a lot of new turfs, objects, and items via coded modules quickly- Currently, only an example 'nature' module is coded, likely more to come later. The flexibility of this system is fairly wide, but it is going to rely on coders creating more modules.

Coders; This is a mostly self-contained system to generate randomized content based on a set of 'modules' that define what the content can spawn. Read 
code/modules/procedural-mapping/mapGeneratorReadme.dm
for more details. Currently, only one example module is coded as a basis.

image of nature mapgen

__Original Post by Remie:__
 * Adds mapGenerator datum
 * Adds mapGeneratorModule datum
 * Adds some misc defines for objects that had sprites but never existed, for a test case

The mapGenerator datum takes a rectangular region defined by the user, and spawns atoms/turfs in that region based on certain settings. 
Admin (R_DEBUG) Test verb added using a nature themed generator.

The mapGenerator datum contains many mapGeneratorModule datums, which do the actual heavy lifting work. The system is organised in such a way that ordering your mapGeneratorModule(s) like layers in a graphics program is encouraged, to give people an existing concept to base off of using this.

Some template modules are included.

a Full Readme and Mapper Guide is included.

Using this on an entire Z level while the rest of the game is running (untested in lobby and world gen) will lock up the game for about 30 seconds, but small regions (20x20 -> 100x100) are fairly smooth.
I see this as a non issue because this isn't supposed to be run in such large sizes or atleast not while the rest of the game is running you butt. (if necessary I could have the main beefy generate() proc postpone all subsystems while it builds)

### CODE REVIEW

**Comment by Midaychi** [comment]
This is currently possibly going to be used on vg for a dorf map, https://github.com/d3athrow/vgstation13/pull/3862 
For medium and low pop rounds. Entire zlevel except the starting area is randomized.

**Comment by tigercat2000** [comment]
@Midaychi I was planning to port that when it is finished, along with any new mapgen modules from -tg- :P

**Comment by fj45** [comment]
Oh man, I was thinking of bugging someone to port this! Amazing!

**Comment by RemieRichards** [comment]
>The flexibility of this system is fairly wide

You flatterer you :3

**Comment by RemieRichards** [comment]
@tigercat2000 *loud whistle* https://github.com/tgstation/-tg-station/pull/9252

**Comment by fj45** [comment]
Thanks for that Remie!

Might take a little bit to port as I would think Tigercat is busy fixing up LINDA.

**Comment by tigercat2000** [comment]
@fj45 actually we use identical code to -tg- on the mapgen, so it's just a few commands to update it

**Comment by fj45** [comment]
Great!

**Pull request merged**
