### PR TITLE
Fix: Typos with a crowbar and a sign Fixes #22033

### LINKED ISSUE #22033: Typos with a crowbar and a sign
**Issue Description**:

The description has an " ' " typo at the end.
image

The word crowbar is spelled wrong.
image

**What did you expect to happen**: 

For there to be no typos

**What happened instead**:

My eyes burned

**Why is this bad/What are the consequences**:

Grammar is good

**Steps to reproduce the problem**:

Go over the structures/signs.dm and customitems/item_defines.dm to verify the changes.
OR
Spawn the screenshot items and examine them

**When did the problem start happening**:

Probably forever

**Extra information**:

EASY

### PR DESCRIPTION
**Pull request by PraveenShinde3**
Fix: Typos with a crowbar and a sign
 Fixes #22033

grenncrossFix
crowbarFix

### CODE REVIEW

**Comment by DGamerL** [comment]
Please try to keep to the template that is provided

**Review by Henri215 — APPROVED** [review]
Grammar team approves this

**Comment by DGamerL** [comment]
Also, please try to put `Fixes #22033` somewhere in the PR description so the issue automatically closes

**Review by S34NW — APPROVED** [review]
Minor PR does not require verification this time. Please look to do so for any future PRs and use the supplied template.

**Pull request merged**
