### PR TITLE
Removes Art storage, Revamps Port Emergency Storage

### PR DESCRIPTION
**Pull request by fj45**
All items from art storage have been moved into the locker room and
emergency storage is now much bigger and has a few extra bits of
equipment.

### CODE REVIEW

**Comment by Markolie** [comment]
Screenshot please.

**Comment by Fox-McCloud** [comment]
Agreed; will need screenshots of both areas that were changed.

**Comment by fj45** [comment]
http://i.imgur.com/9QwZndc.png

**Comment by PJB3005** [comment]
still need the picture of dorms

**Comment by fj45** [comment]
Sorry, the LOCKER room. Nothing has changed at the dorms.

**Comment by Fox-McCloud** [comment]
*shrug*

I kinda like the art supplies room but that's meeeee

No strong opinion either way.

**Comment by PJB3005** [comment]
eh we could replace it with that vendor suggestion somebody made on the forums

**Comment by fj45** [comment]
Yeah thats what this was kind of made for. Really hate the entire arrivals area to be honest.

**Comment by fj45** [comment]
Is this going to be merged or should I just close it?

**Comment by ZomgPonies** [comment]
Get somebody to sprite an art-vend vending machine, code it in, add it to the locker room on the map and I'll merge in the PR. FoS can probably help you with that.

Until then I'm listing it as DNM, as it is incomplete.

**Comment by Spacemanspark** [comment]
There's already an art-vend, courtesy of 1Block.

**Comment by fj45** [comment]
I very much lack the coding skills to implement basic items, let alone any kind of proper vending machine. All items from art storage are still around, just moved a bit.

**Comment by fj45** [comment]
https://github.com/ParadiseSS13/Paradise/pull/531

Can I get a merge now that this is a thing?

**Comment by fj45** [comment]
Thanks!

**Pull request merged**
