### PR TITLE
Spacepod Tweaks

### PR DESCRIPTION
**Pull request by TheDZD**
Also removes some relative pathing, because fuck relative pathing.

:cl:
fix: Fixes spacepods being able to shoot through walls.
tweak: Lowers spacepod weapons fire delay.
tweak: Increases spacepod weapons energy costs.
tweak: Makes spacepods move at speeds not rivaling those of photon beams. They are now a hair bit faster than a person with a jetpack.
tweak: Reduces battery costs for spacepod movement.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:+1:  x :100: 

Very nice.

**Comment by pinatacolada** [comment]
how's the speed compared to things like space carp and blob spores?

**Comment by TheDZD** [comment]
Low enough that those are an actual threat now.

**Comment by Aurorablade** [comment]
....spriteesss.......

**Comment by Gummin** [comment]
Nice! :+1:

**Comment by Robertha89** [comment]
First up, does pods float.
Second up, can the cost for flying the pod be reduced.
Third up,  if no to the first and second up, then the cost increase should not be that harsh.
Fourth up, move delay is what affects the speed of the pod right.
And lastly, do they move properly between z-levels?

**Comment by TheDZD** [comment]
@Robertha89 
- Pods cannot do not float in space when no movement keys are pressed.
- Pods used to cost 3 power per tile moved, now cost 1 power per tile moved.
- Yes, move_delay affects the speed of the pod, higher means slower.
- They still have a few issues moving between Z levels, although that's due to the fact that they're 2 tiles wide, which is they same reason they don't work well with spacemove.

**Comment by KasparoVy** [comment]
Dude that's mint

It's like upgrading from a 1984 camry to a 2016 civic

**Comment by lolzyking** [comment]
The only flaw I see in this is pods would have a REALLY hard time catching someone in space who threw something to gain speed, Used a fire extinguisher+chair to launch into space, or a mass driver

**Comment by Earthdivine** [comment]
That's good then. Spacepods have been king of space for far too long. This will make them manageable to take down as Nuke Ops as well.

**Comment by pinatacolada** [comment]
Kinda concerned if it's slow enough that carps can catch up to it while firing at them. They're also a HUGE target for nukies, it might make them point and u ded with their ion carabine, but we'll see how it plays out

**Pull request merged**
