### PR TITLE
Small sound updates and improvements

### PR DESCRIPTION
**Pull request by E-MonaRhg**
## What Does This PR Do

Changes and updates some of the oldest sounds in the codebase, making them more pleseant to the ear.

## Why It's Good For The Game

Old sounds are not good.

## Images of changes

Some, but not all, changes to sounds (also excuse me, I am not good at making presentation videos):

https://user-images.githubusercontent.com/71735193/113226373-4f669180-9290-11eb-824a-5059d4e89eed.mp4

## Changelog
:cl:
soundadd: Updated the oldest sound effects in the codebase. Certainly not an april fools PR... certainly.
/:cl:

### CODE REVIEW

**Comment by Adrer** [comment]
image

**Comment by SteelSlayer** [comment]
Wow these are really immersive, good job.

**Comment by warior4356** [comment]
Wait, is that handholding comment kyet?

**Comment by AffectedArc07** [comment]
> Wait, is that handholding comment kyet?

Yes

**Comment by AffectedArc07** [comment]
Im calling DNM on this one. Me nyaaing is already unfunny, and it doesnt make sense to swap the door sounds to it, or to swap them to kyet saying handholding. 

If you had made runtime nyaa ocasionally that would have been fine.

**Comment by Carthusia** [comment]
The doors remind me of the ones aboard the Heart of Gold

**Comment by E-MonaRhg** [comment]
Missed the test merge + do not merge, welp, had a good run(not).

**Pull request closed without merging**
