### PR TITLE
Laaaast Christmas

### PR DESCRIPTION
**Pull request by FreeStylaLT**
**What does this PR do:**
Change up Cyberiads to be more christmas-themed. Adds a bunch of department-related fluffy items.

Each department, bar and dorms get their own christmas trees with gifts, each department gets their own special minor gifts (mostly winter coats).

Cargo:
img

Captain's Office:
img

Engineering:
img

Brig:
img

Escape:
img

Dorms:
img

Bar:
img

**Changelog:**
:cl: FreeStylaLT
add: Christmas!
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
That's a lot of trees

**Comment by Mitchs98** [comment]
> That's a lot of trees
AN EXCESSIVE AMOUNT OF TREES IN THE WORKPLACE? 
I KNOW HOW TO SOLVE THIS
_CHAINSAW NOISES INTENSIFY_

But seriously. Yay presents.

**Comment by Pennwick** [comment]
I want this but aren't we under a mapping freeze until the #10403 gets through? Though there hasn't been a lot of activity in that PR recently.

**Comment by datlo** [comment]
Nah, the bonfire is part of the SS13 christmas spirit. Don't nerf it. :eyes:

**Comment by tylerh95** [comment]
Speed merge needed people, it's already the 16th. No time to wait!

**Comment by Citinited** [comment]
Can you move the Bob Ross painting from behind the tree in the captain's office? The happy little trees need love too

**Comment by FreeStylaLT** [comment]
@Citinited It was moved in the PR:
img

**Pull request merged**
