### PR TITLE
Makes Gas Less Dusty More Gassy

### PR DESCRIPTION
**Pull request by Chakirski**
Ports phor- I mean plasma and N20 sprites from Apollo.

:cl: Chakirski
tweak: Plasma and N20 look more gassy.
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
I honestly thought this was something Vox-related at first. On a more serious note, the N2O sprites seem to hardly be visible on normal floor tiles.

**Comment by tigercat2000** [comment]
dunno that i really like the new sprites

**Comment by FlattestGuitar** [comment]
You can embed pictures in github comments. Use ``.

Also, that indeed seems a bit hard to notice.

**Comment by Chakirski** [comment]
It's okay, I can make it more opaque.

**Comment by Earthdivine** [comment]
I kinda like them, it's better then "lots of spots".

**Comment by Chakirski** [comment]
They are giffs though, I don't know how to embed them without breaking them.

**Comment by TheDZD** [comment]
The standard embedding that FlattestGuitar recommended should still work for gifs.

**Comment by Chakirski** [comment]
https://gyazo.com/c6cfc76d092a248a9179d5332f23e965

Much better?

P.S. It seems I just can't embed gyazo pics :(

**Comment by TheDZD** [comment]
That's much more visible now, thanks. Overall these sprites are pretty nice.

**Comment by Plotron** [comment]
Personally, I prefer the retro look of our current sprites.

**Comment by Chakirski** [comment]
I'm not going to do anything about it now, but would you rather toxin canisters also be changed to purple?

**Comment by DaveTheHeadcrab** [comment]
Personally, I like it

**Comment by Ar3nn** [comment]
Looks good, and I'm always tempted with the current sprites to crack a joke about it "snowing" nitrogen/plasma.

**Comment by Fox-McCloud** [comment]
as long as the laughing gas is super visible, I'm ok with it, but that first sprite is a no-go.

**Comment by Chakirski** [comment]
Fox the opacity for the N20 is now the same as the plasma, it's just white.

**Comment by Ar3nn** [comment]
@Chakirski a tip, if you visibly change something in-game that can be shown between commits, update your original screenshots when applicable.

**Comment by Chakirski** [comment]
I did... it's common sense.

**Comment by Spacemanspark** [comment]
I like it a lot. :+1:

**Comment by TullyBurnalot** [comment]
Oh dear lord, this is awesome.

**Comment by Twinmold93** [comment]
Better looking sprites than just spots. Makes the game look better, for sure.

**Comment by Belario** [comment]
:+1:  Much easier on the eyes, and it actually looks like noxious gas as opposed to miniature snow storms.

**Comment by Fullofskittles** [comment]
I actually like the original better? I never really understood why it was so visible in the first place.

**Pull request merged**
