### PR TITLE
Disposals/Recycling Remap

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Remaps recycling/disposals.

This is basically TG's disposals. The advantages it has are clear; it's more accessible for maintenance, it has an automatic stacking machine (that can also deliver the metal it stacks), and allows for a less cramped working area/easier item retrieval (especially bodies).

Pic:

disposals

Other/related
- Fixes an infinite loop in disposal routes
- adds in a TG var for conveyor belts that allows for more customization of directions and icons.

### CODE REVIEW

**Comment by Markolie** [comment]
:+1:

**Comment by Spacemanspark** [comment]
Where was the infinite loop?

**Comment by KasparoVy** [comment]
Does this fix the issue where welding disposal pipes apart (or trying to fix broken pipes, even attaching a completely new pipe) gives you a sprite different to the actual flow of items through the pipe?

**Comment by Fox-McCloud** [comment]
@KasparoVy 

No, it does not.

**Comment by veganzombeh** [comment]
Where does the disposals pipe next to the stacking machine go to? (I'm assuming it delivers stacks of materials to cargo or something?)

**Comment by Fox-McCloud** [comment]
Back to sorting.

**Pull request merged**
