### PR TITLE
[BALANCE][BUGFIX] Singuloth Knight item balance & Small Bugfixes

### LINKED ISSUE #282: Issues with returned shipping manifests
The [code](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/supplyshuttle.dm#L208-L213) to handle shipping manifests sent back in crates on the supply shuttle is as follows:
```
if(find_slip && istype(A,/obj/item/weapon/paper/manifest))
	var/obj/item/weapon/paper/slip = A
	if(slip.stamped && slip.stamped.len) //yes, the clown stamp will work. clown is the highest authority on the station, it makes sense
		points += points_per_slip
		find_slip = 0
	continue
```

The continue statement at the end there has some odd consequences:
* Any non-stamped shipping manifests the code sees before a valid one are returned on the shuttle.
* The first stamped shipping manifest found will add supply points, and then *get returned on the shuttle*, after which it can be sent back for *more points*.
* Any further shipping manifests in that crate, regardless of stamp presence, are deleted.

This is a bit nonsensical, and probably not the way they're intended to work.

Simply removing the continue statement will cause all manifests to get deleted, though it may make more sense to only delete ones that are actually converted into points.

### PR DESCRIPTION
**Pull request by ZomgPonies**
SK Hammer:
- Dual-hand forced downed from 50 (20+30) to 30.
- Single-hand attacks can now knockback, but only cause 5 damage.
- Gibbing critted players still possible, but only with dual-wield.

Claymore:
- Replaced regular claymore with ceremonial version that does half damage, will update with new sprite from FoS when she works her magic.

This should bring SKs in line with the idea that event (as opposed to adminboose) equipment should be at most 25-50% stronger than regular crew gear.

Bugfix:
- Fixes alternate job title jumble.
- Fixes #282 regarding supply manifest bugs

### CODE REVIEW

**Comment by Regen1** [comment]
Changes seem fine for balance, now we need to work out how to make these actually usable in an event without being instakilled because the entire sec team has insta stun

**Comment by adrkiller59** [comment]
Yesh, good balance, for slap-hammering without insta-critting. As for the security team with insta-stun, a glorious CHAAAARGEEE to run to them and caress their cheek with the hammerhead before they have time to shoot would help a lot.

**Comment by Markolie** [comment]
Ah, the alternative job title fix is long, long overdue! Thanks!

**Comment by Fox-McCloud** [comment]
Seems fine to me.

**Pull request merged**
