### PR TITLE
rename all station files and datums, consolidate types into one file

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
This PR moves all station maps to a `stations/` subdirectory and makes their datum and file names consistent. As far as I can tell this shouldn't break anything on the backend in terms of what gets stored in the database; only the `technical_name` field is stored for round data (which is why those haven't been modified).
## Why It's Good For The Game
Consistency is good. Everything else about our map filenames are organized; space ruins are in `SpaceRuins/`, shuttles are in `shuttles/`. Having individual per-station directories with single map files in them is silly and pointless, and mixing in-game names like Cyberiad with technical names like Metastation is another pointless inconsistency that we're not forced to maintain.
## Testing
Will see what CI thinks.

## Changelog
NPFC

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]
DLGTM

**Review by AffectedArc07 — APPROVED** [review]
Let the webmap changes begin

**Review by Contrabang — APPROVED** [review]
lgtm

**Comment by AffectedArc07** [comment]
Closing and reopening to make CI work

**Comment by AffectedArc07** [comment]
Oh I am a muppet
image

**Pull request merged**
