### PR TITLE
Update station nuke sprite

### PR DESCRIPTION
**Pull request by DogsParadise**
## What Does This PR Do
It adjusts the current nuke sprite to make it less flat, adds better shading and hueshifting.
Changes the animation just slightly, but tried to keep it as original as I could to our current nuke.

## Why It's Good For The Game
Sprite will fit better when we import more TG sprites.
Adds quality of improvement changes to the current sprites and adjusts it ever so slightly.

## Images of changes
New:
image

Nuke off in game:
image

Nuke timer running in game:
https://user-images.githubusercontent.com/48732029/113063381-84ea7c80-91b5-11eb-8eb6-cb7c056c2595.mp4

Just before nuke explodes:
https://user-images.githubusercontent.com/48732029/113063327-6be1cb80-91b5-11eb-9c94-14074cee20e9.mp4

Old:
image

## Changelog
:cl:
tweak: updated the nuke sprite
/:cl:

### CODE REVIEW

**Comment by hal9000PR** [comment]
Change the changelog to say something like

Tweak: updated the nuke's sprite

**Comment by DogsParadise** [comment]
> Change the changelog to say something like
> 
> Tweak: updated the nuke's sprite

Thanks done, terrible at making these.. Couldn't even get the videos working

**Comment by hal9000PR** [comment]
> > Change the changelog to say something like
> > Tweak: updated the nuke's sprite
> 
> Thanks done, terrible at making these.. Couldn't even get the videos working

Don't worry, we are here to help. Sprite looks great

**Comment by Dumbdumn5** [comment]
I actually really like this, even if it does make my brain think the nuke is now a strange shade of olive and Mountain Dew. 👍

**Review by hal9000PR — COMMENTED** [review]
it would appear that you have reverted some sprite changes by accident

**Comment by DogsParadise** [comment]
DONT MERGE IT YET BROKEN!

**Comment by DogsParadise** [comment]
> it would appear that you have reverted some sprite changes by accident

Fixed, please check if it's still the case

**Review by hal9000PR — APPROVED** [review]
looks good now

**Comment by variableundefined** [comment]
The styling and shading in particular look very out of place with the rest of SS13's styles. 

Closing due to 2 maintainers objection.

**Pull request closed without merging**
