### PR TITLE
Restore a piece of history

### PR DESCRIPTION
**Pull request by tigercat2000**
Fixes #1736 

:crying_cat_face:

### CODE REVIEW

**Comment by Alex6511** [comment]
Why? Useless code is what causes code sphegettifaction. Bad coding examples aren't something you should be putting on display.

**Comment by Alex6511** [comment]
Lets just add the entire raw text of Twilight in there too while we're at it.

**Comment by tigercat2000** [comment]
@Alex6511 Why, hello Mr. Hostile. 

It's clearly marked as terrible. I find it to be great.

**Comment by Alex6511** [comment]
Hostile? I was making a joke. What the fuck.

**Comment by tigercat2000** [comment]
@Alex6511 Didn't come off that way to me :cat: :confused:

**Comment by Markolie** [comment]
I'm not sure if I see the point, to be honest. I've been making an effort to comment out less code and delete more - I don't think it's a good idea to keep comments around for the sake of them being "funny". There really is no point aside from bloating the codebase. Just my two cents though.

**Comment by tigercat2000** [comment]
@Markolie It's probably less than a kilobyte, and it made me laugh when I first saw it. I don't see the point removing tiny excerpts like it.

**Comment by Fox-McCloud** [comment]
This is pointless and stupid. THere's literally no reason to include it. It's not even clever or amusing like N3X15's rant about r-walls.

**Comment by tigercat2000** [comment]
@Fox-McCloud Is there a reason not to include it? There are larger commented out sections that aren't even funny elsewhere in the code.

**Comment by Markolie** [comment]
Well yes, but I do try to make an effort to delete them when I come across them.

**Comment by Fox-McCloud** [comment]
It's not going to educate anyone, it's not that amusing or humorous, and it's literally increasing the codebase size for your own personal laugh.

This is literally pointless.

**Comment by tigercat2000** [comment]
@Fox-McCloud This only takes up a kilobyte as a text file.

If I laughed at it, maybe another coder will laugh at it, and that's why it's worth keeping.
What is the point to anything if we can't have a kilobyte of code that might make someone laugh at the terribleness of old coders.

**Comment by Markolie** [comment]
I see where you're coming from, but I just disagree with keeping useless code on the Git. :-1: from me, as there's really no point.

**Comment by Markolie** [comment]
This is being closed per the comments made above.

**Pull request closed without merging**
