### PR TITLE
Allow Vulpkanin to eat Tajara, Farwa's, Vulpins, Runtime

### PR DESCRIPTION
**Pull request by tigercat2000**
I promised the IRC I would make this if Vulpkanin got merged. (plis don't hate me fox)

This commit allows Vulpkanin to eat Tajaran, Farwas, and Vulpins (it's a
dog eat dog world out there.), And Runtime. This means that Vulpkanin can eat any
Tajaran, Farwa, or Vulpin like a xenomorph can eat any
carbon mob.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Um...
What.
Is this a joke PR.

**Comment by veganzombeh** [comment]
Runtime too, please.

**Comment by FreeStylaLT** [comment]
all my yes

**Comment by Earthdivine** [comment]
Let's not please.I do not want them playing Vulpakinns to get back at tarjan players. All I can see coming from this is grief and griff. Not even Kidan can do that to Diona, only the nymphs.

**Comment by tigercat2000** [comment]
Please note that Woof Larkens is testing all of these whitelists to ensure maximum functionality.
woof!

**Comment by Fox-McCloud** [comment]
Yeah, no.

**Comment by Mijhead** [comment]
Catbeasts eat mice, fo- dogbeasts eat cats, nothing wrong here :+1:

**Comment by Finalsong** [comment]
makes sense

**Comment by Fox-McCloud** [comment]
Yeah, no. :-1: 

Canines don't eat cats and they aren't known to eat mice either---this feature still rubs a lot of Tajaran players the wrong way. LIkewise, let's not encourage rivalry between players because of some little snippet of code. 

This makes literally no sense and is purely here for "lol", just 'cause".

@tigercat2000 

I will fight you til the bitter end on this one; it's not something I want players, at all, to be encouraged to do with the race and I'm pretty confident to say that the sprites' designer, Full of Skittles, would be very heavily opposed to this 'feature', as well.

**Comment by Spacemanspark** [comment]
Come on, Fox, have some spirit!
This is what you wanted with Canines- a strong, better race than Tajaran, after all!
:+1: :+1: :+1:

**Comment by Mijhead** [comment]
<SAA18> someone post this for me
18<SAA18> canines might not eat cats or mice sure but it's Space in 2559 with Not-Fox-Caninepeople and Not-Cat-Catpeople, who says Not-Fox-Caninepeople can't eat Not-Cat-Catpeople
18<SAA18> and have you not watched tom and jerry? rivalry between cats and dogs is very realistic and will add to the lifelike roleplay experience

-Not me, read the thing

**Comment by TheDZD** [comment]
I would be fine with them being able to eat species-specific monkeys (Kidan can basically do this with nymphs), or even with them being able to eat Runtime (heck, Tajara can eat mice), but definitely not eating Tajara.

**Comment by tigercat2000** [comment]
wat eve
Woof Larkens. Eating cat people.

**Comment by Spacemanspark** [comment]
Darn it, Tigercat, you should have let the joke run.

**Comment by tigercat2000** [comment]
@Spacemanspark I accidentally mentioned it in a public chat, ruined it. Sorry :(

**Comment by fj45** [comment]
RIP racial wars.

**Comment by fj45** [comment]
Ahh, what could have been.

**Pull request closed without merging**
