### PR TITLE
Removes the machinery pipe dispenser from the codebase

### PR DESCRIPTION
**Pull request by Sinestia**
## What Does This PR Do
Removes the last of the machinery pipe dispensers from the maps, and purges it from the code 

A couple have been replaced with RPDs

I removed the sprite as well as this was the only thing it was used for. 
## Why It's Good For The Game
* https://github.com/ParadiseSS13/Paradise/discussions/18493

Motivated by a mention here.

Also progresses
* https://github.com/ParadiseSS13/Paradise/issues/14968

Machinery Pipe Dispensers are extremely cumbersome to use, require power unlike RPDs, and still have an archaic UI. 

While they could be converted to tgui without too much pain (it's just a list) I don't think it's worth the effort because players will never use them unless forced to, which is a fairly painful experience.

This thing has already been *mostly* removed, you won't find it in any of the station's atmosias. 

## Images of changes
MDB should be sufficient.

## Testing
I pressed F5 
I searched for all instances of the obj

## Changelog
:cl: Froststahr
del: The machinery pipe dispenser has been removed in its entirety. 
/:cl:

### CODE REVIEW

**Comment by Sinestia** [comment]
NOTE: Wiki changes

**Review by Sirryan2002 — APPROVED** [review]
Code and Sprite changes are fine, map changes look fine aswell

**Comment by Denthamos** [comment]
I believe there was someplace that still used this due to no access to a RPD, ruin wise.  But my memory is foggy.

**Comment by Sinestia** [comment]
> I believe there was someplace that still used this due to no access to a RPD, ghost role ruin wise. But my memory is foggy.

they were given an rpd

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
