### PR TITLE
[DNM] Uplink bundle rebalance

### PR DESCRIPTION
**Pull request by Markolie**
**What does this PR do:**
To be merged after the chameleon overhaul (https://github.com/ParadiseSS13/Paradise/pull/11428) is merged. 

Unlike the surplus kits, the uplink bundles are always supposed to contain useful objects. They're not intended as a randomized purchase, but instead force its purchaser into a certain specialization. 

Right now, however, some kits aren't really that useful and pretty much screw you over. This pull request balances some of the weaker bundles to provide more value. Most of these were based on how /tg/ rebalanced their kits. 

Some of these may seem like they add a lot of telecrystal value, but keep in mind that certain items are worth a lot less than their actual telecrystal value. Those should probably be rebalanced at some point as well.
```
**Bloodyspai** (+ 13TC)
+ Noslip chameleons (2TC)
+ AI detector (1TC)
+ Syndicate encryption key (2TC)
+ Chameleon projector (8TC)

**Thief** (+ 10TC)
+ Smuggler's Satchel (2TC)
+ Thermal goggles (6TC)
+ Syndicate encryption key (2TC)

**Bond**
~ Unchanged

**Sabotage** (+ 11TC)
+ 2 C4 (2TC)
+ Camera bug (1TC)
+ Detomatix cartridge (6TC)
+ Syndicate encryption key (2TC)

**Payday** (+ 2TC)
+ Syndicate encryption key (2TC)

**Implant** (+ 6TC)
+ EMP implant (0TC, but worth about 2TC)
+ Explosive implant (2TC)
+ Syndicate encryption key (2TC)

**Hacker** (+ 5TC)
+ AI detector (1TC)
+ C4 kit (4TC)

**Dark Lord** (+ 2TC)
+ Syndicate encryption key (2TC)

**Gadgets**
- Removed, as it was very bad and not truly a specialization.

**Professional** (+ 4TC)
This one requires some additional information. The goal of this kit when it was implemented on /tg/, was to allow you to assassinate your target through a wall using thermals and penetrator rounds. However, on Paradise it uses only soporific rounds. That means you're stuck with a huge sniper rifle and you have to waltz into a room to get your target and you can only put them to sleep.
- Soporific sniper rifle (16TC)
- 2 Soporific magazines (6TC)
+ Penetrator sniper rifle (16TC)
+ Penetrator magazine (5TC)
+ Soporific magazine (3TC)
+ Syndicate encryption key (2TC)
```
**Changelog:**
:cl: Markolie
balance: The Syndicate uplink bundles have been rebalanced to provide more value to operatives.
/:cl:

### CODE REVIEW

**Comment by Markolie** [comment]
I'm open to feedback on how we can further rebalance these and perhaps add new ones!

**Comment by Mitchs98** [comment]
Not a fan on the sniper bundle getting penetrator rounds since those can delete brains/heads. They're nukie only for a reason imo. Sure there's plenty of ways to delete heads/brains already, but I don't really feel traitors should get a one click brainus deletus option that literally goes through walls. Sure the sopor rounds may not be that strong...but still.

**Comment by Markolie** [comment]
@Mitchs98 The penetrator rounds don't actually dismember at all (and the regular ones only dismember, but don't blow up the brain). So neither of those instantly force you out of the round.

**Comment by Mitchs98** [comment]
> @Mitchs98 The penetrator rounds don't actually dismember at all (and the regular ones only dismember, but don't blow up the brain). So neither of those instantly force you out of the round. Otherwise I'd agree they'd be much too strong.

I distinctly remember hearing about one of the two bullet types deleting brains/being capable of doing so. I dunno. May be AP I'm thinking of? Just know that nukies use 'em is all.

**Comment by Markolie** [comment]
Let me just double check to make sure.

**Comment by Markolie** [comment]
@Mitchs98 It's a good thing you asked, because they do actually delete the head. Let me think about how to best solve that.

**Comment by Mitchs98** [comment]
> @Mitchs98 It's a good thing you asked, because they do actually delete the head. Let me think about how to best solve that.

I thought so. Genuinely wasn't sure WHICH, but I knew nukies used them...and thought it was penetrators.

**Comment by TDSSS** [comment]
That's a lot of syndie encryption keys. I approve.

**Comment by Markolie** [comment]
Okay, turns out the penetrator sniper rifle can't actually blow up heads. Guess I tested it incorrectly. The sniper now spawns with a sniper rifle with one penetrator mag loaded and one penetrator and one soporific magazine in reserve.

**Pull request merged**
