### PR TITLE
Spritefixes, Underwear and Berets

### LINKED ISSUE #3234: Beret has Orange Pixels
The north-facing sprite for standard berets, like the one the mime gets, has random orange pixels.

https://github.com/ParadiseSS13/Paradise/pull/1390 I think fixed the sec berets but not the other ones and nobody has really bothered making a report about this one for some reason.

### PR DESCRIPTION
**Pull request by KasparoVy**
Fixes #3234 and #3235.
Adds some TG underwear.
Adds an on-head sprite for the night vision science goggles.
Bottom right guy shows off the fixed beret and the new goggles.
Also ports Bay/TG berets.

*Underwear and NV Sci-gogs.*
noice

*Fixed NV Sci-gog sprite.*
noicer

*Ported TG/Bay Berets.*
noicest

---------------------------------------------------------------

Just a side-comment, IDK which PR did it but all of a sudden after updating my branch a couple hours ago, starting up a local server to test stuff is WAAAY faster. Just something I noticed. Yay for all those speed enhancement PRs

### CODE REVIEW

**Comment by Plotron** [comment]
Gorgeous.

**Comment by kylejen** [comment]
Yay. After long last, the beret has been fixed. All we need now is the hair.

**Comment by Fox-McCloud** [comment]
You might as well jsut port over TG's beret on-mob sprites; they were requested anyway.

**Comment by KasparoVy** [comment]
@Fox-McCloud Want ALL the TG berets ported? (incl. the Warden and 'officer' berets as well as the standard. The HoS one is already in)

**Comment by Plotron** [comment]
@KasparoVy 
I think we should consult the forums.

**Comment by tigercat2000** [comment]
@Plotron i think we shouldn't consult the forums and the answer is "yes please"

**Comment by KasparoVy** [comment]
http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=6458&hilit=beret, the general consensus was good

I'll put the berets in, brb

**Comment by KasparoVy** [comment]
Every beret but Spark's special green one was changed to new Bay/TG standard

**Comment by Plotron** [comment]
@KasparoVy 
That's exactly what I meant by *consulting the forums*.

**Comment by Fox-McCloud** [comment]
Thanks, @KasparoVy

**Comment by KasparoVy** [comment]
No problem!
@Plotron http://nanotrasen.se/phpBB3/posting.php?mode=post&f=12 thread relevant

**Comment by Fox-McCloud** [comment]
looks like the offset on the engie beret is wrong?

**Comment by KasparoVy** [comment]
Updated the picture, all looks well

**Comment by Fox-McCloud** [comment]
Yes; no more beret smooshing into people's eyes!

**Comment by Finalsong** [comment]
nice nice gotta love them berets

**Comment by kylejen** [comment]
I just wish we had a beret for each job. Medical, Science, Captain, HoP etc.

**Comment by Nienhaus** [comment]
@Finalsong Thanks bby.

**Pull request merged**
