### PR TITLE
Removes "muh valids" Graffiti

### PR DESCRIPTION
**Pull request by TheDZD**
No description needed.

### CODE REVIEW

**Comment by lordpidey** [comment]
Do you REALLY need to edit fourty six files to change this?

**Comment by Fox-McCloud** [comment]
@lordpidey 

Yup. Technically this happens on TG, as well, it's just all unseen because of your guys' auto-patcher+watchdog.

**Comment by lordpidey** [comment]
Oh, I was just looking at the title of the PR, not the actual contents of it.  I didn't realize what it was actually doing.

**Comment by Fox-McCloud** [comment]
@lordpidey 

It's a running gag/meme/joke here to make controversial titled PRs for changelog generation.

**Comment by Lady-Luck** [comment]
all changelog PRs are meme PRs

**Pull request merged**
