### PR TITLE
Secborg

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Secborg: The Nerfening

Borgs are a 300 health, uncrittable, nigh unstunnable (flash, flashbang, and laser pointer) mob with a self-recharging taser--they literally outclass officers in every way, and emagged/hacked secborgs had the egregious stun and laser combo that was seen on the previous egun iteration.

-Removes secborg's taser
-Gives secborg a disabler instead
-taser cooler is now a disabler cooler

TG in Design

### CODE REVIEW

**Comment by Markolie** [comment]
I believe /tg/ is also going to (or has already?) remove the taser completely when the borg is emagged. That may be wise as well.

This is definitely a desperately needed nerf though; one emagged borg was capable of robusting a group of people.

**Comment by Regen1** [comment]
I agree to this change, sec borgs are really powerful, especially if emagged.

**Comment by Fox-McCloud** [comment]
@Markolie 

They decided against the other change as it was too easy to metagame: "borg; fire your taser/disabler! No? AI IS ROGUE/BORG HAS BEEN EMAGGED!"

The disabler PR and removal of taser when emagged PR were competing PRs and meant to be mutually exclusive.

**Comment by ZomgPonies** [comment]
Looks good, I agree that secborgs shouldn't be WAY better than humans. This will also help balance the robot fabricator in the Malf AI rounds.

**Pull request merged**
