### PR TITLE
Removes Tajaran and Unathi Glove+Shoe Restriction: Loadout Change

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Bay and Polaris already did this--I don't see any reason not to do the same---brought this up on the Discord and people seemed to like it too. It really doesn't have any negative balance implications and helps cut down on meta, as well.

- Removes species restriction on gloves and shoes for Tajaran and Unathi
- Adds sandals to the loadout
- Glove clipping removed (shoe clipping still in)
- Clipping black gloves will now make them fingerless (picketpocket gloves retain their ability to picketpocket, even fingerless)

Tajaran and Unathi can now wear all glove types and shoe types. Shoe clipping is intact and still changes the sprite. Glove clipping is gone (except for the case of black gloves, which can be made fingerless, by clipping them). 

Should cut down on meta of "hey, that's a Tajaran with brown shoes, he's wearing syndi galoshes" or "well, it was a Unathi because these were mangled insulated gloves" and the likes.

Of course, I'm well aware that people will still very much like to easily have sandals available to them for these species, and to that end, I've added sandals as a loadout option.

:cl: Fox McCloud
tweak: Tajarans and Unathi can now wear all shoe and glove types
tweak: Glove clipping removed except for black gloves, which makes them fingerless gloves
add: Adds sandals as a loadout option
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
+1

Never understood why vulps can wear them, but taj cannot.

**Comment by KasparoVy** [comment]
I think Vulpkanin being able to wear shoes/gloves just fine was oversight. I'm neutral on this, but I agree with all the points made.

**Comment by Fox-McCloud** [comment]
>I've always thought Vulpkanin being able to wear unmodified shoes/gloves was oversight

It wasn't, acually--I did it intentionally 'cause I didn't want the meta issues with them and also wanted to give players the option to pick sandals or shoes based on their preference since it doesn't have any balance implications (unlike Kidan+glasses).

**Comment by KasparoVy** [comment]
Thanks for clearing that up, I've been wondering about it all this time haha

**Comment by Lady-Luck** [comment]
Cutting holes in latex gloves has always bothered me. "Hold on one second patient, I need to make sure my sharp-ass claws are exposed before performing surgery on you"

Plus there were a lot of shoes that were unable to be clipped.

**Comment by Belario** [comment]
RIP species differences I guess.

**Comment by Aurorablade** [comment]
As a player of both races..I actually do not like this change. I mean i liked the flavor it gave my character, you had to modify something to fit, It wasn't as one size fits all thing. 
Now your shoe meta i can see the point of, but there HAS to be some other solution.
And anyone can managle gloves...so useing that as meta is kinda silly.

Reallly fox, i will try to brainstorm with you if you want..but i am not a fan of this change. I am sorry i am not.

**Comment by Lady-Luck** [comment]
I'm a player of both races too. It sounds nice on paper, it really does. But those differences lead to metagaming as Fox said, things that don't make proper since, and having to create special versions of every glove and shoe item in the game that are clipped or else the races just can't use them.

And if we want to talk about things not fitting, why does everyone on the space station have the same shoe size? Why can't rubbery materials fit over claws?

It's a lot of work to maintain a feature that most people playing other races will not even notice or appreciate.

**Comment by Aurorablade** [comment]
its not a lot of work. It might be a minor inconvience SOMETIMES but its easily dealt with. The glove issue is minor to me if you useing that for meta you are silly....There HAS to be a solution to the also silly shoe meta.
I loved the feel of it..and yes i do WISH some other races had to do things like this...but eh... :(

**Comment by Lady-Luck** [comment]
>its not a lot of work.

We don't even have clipping for more than half the shoes in the game. So perhaps it's more accurate to say 'it's work that no one wants to do'.

**Comment by Fox-McCloud** [comment]
And if you want to wear sandals, you're more than free to do so--again you can even start off with them, if you like.

The gloves thing is just an annoying time sink for the same of having a time sink. Nothing is gained or made more interesting by having to clip the gloves, it just forces the player to grab a pair of wirecutters to fit their gloves for no other reason than they picked that species.

There's not even good RP that can come of this--about the best I've ever seen is "I can't wear those, I need to clip them first". Hardly stellar quality RP.

Aesthetic and customization (when they don't have any balance ramification) > pointless time sinks/customization restrictions for no good reason.

**Comment by Aurorablade** [comment]
@Lady-Luck try minor inconvinence SOME PEOPLE don't want to do. I would gladyly do it

@Fox-McCloud as i said, not the same. I liked the feel of how it is currently. The only thing i could think of for the shoe meta, is make a no-slip shoe kit, same cost as no slip shoes but could be applied to ANY set of footware to make them no slip. I really disagree, It dosen't have to be steller rp. I would often make quips or emotes about the glove thing when i think of it, even if its just one line. I mean even if i crank about it IC, OOC i don't mind.

I do not see how its a time sink, and sometimes you shouldn't remove ALL time sinks... please :(. No really i loved the flavor of it.

**Comment by Lady-Luck** [comment]
We have loadouts now though. Just spawn with sandals. A lot of unathi and taj players, like myself, will just select that option on the loadout screen, because we do like our tradition of sandals.

With that in place, the only reason for keeping this around is for FORCING the snowflakey shoes on people that have absolutely no difference other than you had to grab a pair of wirecutters.

**Comment by Aurorablade** [comment]
not all snowflake is bad, I like the flavor of being forced to do it. To me it add something to the race feel wise.

**Comment by IcyV** [comment]
>not all snowflake is bad, I like the flavor of being forced to do it. To me it add something to the race feel wise. 

When it's randomly applied to only specific races and not all the others that should reasonably have it based on their build, I'd rather not have it at all. It's just extra steps for no real reason.

**Comment by Fox-McCloud** [comment]
>is make a no-slip shoe kit, same cost as no slip shoes but could be applied to ANY set of footware to make them no slip

Once some flag refactors are done, I plan on implementing the full chameleon kit (can disguise a mask+shoes+hat+suit+uniform as anything), so that's really not necessary here and only further re-inforces what's already been said.

**Comment by Lady-Luck** [comment]
@Fox-McCloud Could you add dress sandals to the loadout as well? For jobs with the 'dress shoes' starter. NT Rep has it in their locker, Magistrate does not. There might be other jobs with dress shoes I'm not aware of...

**Comment by Aurorablade** [comment]
then maybe we need to add stuff like this to OTHER races? and i could wait for the chameleon kit...just please don't take mah gloves and shoes...:( :( :(

**Comment by theColdflame** [comment]
identifying species based on species characteristics is not metagaming

**Comment by Lady-Luck** [comment]
>identifying species based on species characteristics is not metagaming

"hey, that's a Tajaran with brown shoes, he's wearing syndi galoshes"

**Comment by theColdflame** [comment]
>"hey, that's a Tajaran with brown shoes, he's wearing syndi galoshes"

admittedly, cases such as that could be considered metagaming, though the real question is why tajarans can wear noslips without snipping them

>"well, it was a Unathi because these were mangled insulated gloves" 
is not metagaming

**Comment by Spacemanspark** [comment]
Eh.
Not worth fighting to keep, honestly, even if it was neat.

**Comment by Fox-McCloud** [comment]
I'd also point out it's an easy way to identify changelings, as well.

Tajaran or Unathi with regular jackboots? 100% they're a changeling.

**Comment by theColdflame** [comment]
then the changeling fucked up

I don't play either race so I won't claim an opinion either way on this, but claiming that the racial restrictions having impact on gameplay is metagaming just isn't true

**Comment by Lady-Luck** [comment]
It creates a lot of fiddly little problems, annoyances, workload, inconsistencies, all for what?

**Comment by LightningLynx** [comment]
+1

The only real argument for this is individual preferences and "but my flavor" which is still more than accessible to you if you truly want to continue doing so. Ultimately it boils down to you wanting to force your preference for flavor on others.

**Comment by Aurorablade** [comment]
I am not going to stop fighting for this. Metaing someone over gloves is silly and the shoe issue just needs another solution like my suggestion

**Comment by Spacemanspark** [comment]
Perhaps just have it auto-remove shoes if a ling transforms into a catbeast/ unathi.

**Comment by Aurorablade** [comment]
thats an option there spark..

**Comment by Faryaa** [comment]
Oh, god, yes! Yes! Finally I can play jobs like security officer as unathi without slowly setting up before starting to actually work. No more stupid clipping.

**Comment by Belario** [comment]
So can we get the tarajan claw bleeding removed too?

Once this goes it leaves them a straight upgrade overall aside from the slight temperature vulnerability/automatic cat mafia membership.

**Comment by Spacemanspark** [comment]
There are many better tools you can use to make someone bleed.

**Comment by Lady-Luck** [comment]
Humans have higher alcohol tolerances

**Comment by MindLeaker** [comment]
This is a yes and no for me.

First and foremost, a new balance feature _needs_ to be added to the Vulpakanin, Tajaran, and Unathi races. Because once this passes the way it stands is anyone can racechange from Human to Tajaran and get a flat unarmed damage boost AND Cold Resistance all for a measly small increase in heat damage. Because of how our server treats lore there is no penalty for playing a catbeast exactly as you would a human and still earning all buffs.

But, on the other hand this method of balance was just lazy and didn't solve any of the problems already present.

Shaky :+1: for this PR, and I implore someone to take a hard look at racial balancing in the future

**Comment by Belario** [comment]
NT sponsored discrimination when?

I would be 100% fine with cat/dogbeasts having 10 brute damaging bone-breaking internal-bleed inducing claws _and_ nerve pinching too in return for species quotas.

**Comment by tigercat2000** [comment]
fuck species quotas, literally never

**Comment by Spacemanspark** [comment]
Only humans can be the captain. :^)
Do it do it do it.

**Comment by IcyV** [comment]
>First and foremost, a new balance feature needs to be added to the Vulpakanin, Tajaran, and Unathi races. Because once this passes the way it stands is anyone can racechange from Human to Tajaran and get a flat unarmed damage boost AND Cold Resistance all for a measly small increase in heat damage. Because of how our server treats lore there is no penalty for playing a catbeast exactly as you would a human and still earning all buffs.

I find it kind of funny you have issues with specifically these races when there are several others that have the tiniest disadvantage ever and a list of advantages. These races get the most minimal advantage to fully unarmed combat that won't ever matter if an opponent has a weapon and cold resistance that will never come into play in any actual atmospheric dangers. They're the next closest to base humans of most races. There's no reason not to play an IPC, using your logic. They take a tiny bit more brute for being immune to nearly every other kind of attack or damage and being hard to kill via sheer brute anyway.

The snipping was a dumb mechanic that got selectively applied to certain races at a single point in time and really is neither an advantage or disadvantage given the ease of finding a tool to do it anyway. It is just an annoyance that wastes time.

**Comment by MindLeaker** [comment]
@IcyV 
> I find it kind of funny you have issues with specifically these races when there are several others that have the tiniest disadvantage ever and a list of advantages

You misinterpreted my entire statement, I chose those races from the top of my head, _all_ races require balancing reworks. And that "minimal advantage", having played as a Tajaran for most of my time in SS13, is anything but minimal, unarmed combat with a damage buff has the benefit of both the flat damage and the weaken punch which can essentially turn an entire fight around, though that again wasn't the point I'm making.

The point is that races need to have an _actual_ penalty versus humans, else there is, as you say, no reason for me not to choose an IPC. Cold/Heat weakness is not one of them. And for that matter the "tiny" bit of extra brute they is way more significant than you put it, not to mention their susceptibility to EMPs. Honestly, I find IPCs have some of the biggest penalties and biggest advantages, which seems fair to me overall.

As for snipping; yes it was a dumb mechanic and I didn't disagree with it's removal, what I want is an _actual_ disadvantage in it's place

**Comment by Lady-Luck** [comment]
But the claw thing is so ridiculously minor.

Humans being able to outdrink other races is going to come up more than than your slight extra bit of unarmed damage.

Chill out.

**Comment by IcyV** [comment]
@MindLeaker 

I've played Tajarans primarily since pretty much the moment I started SS13 as well. While you're not wrong that they're "unbalanced", it is by so little that they're essentially the most balanced next to default human vars. All of the races certainly need to be looked at in terms of balancing but I don't believe snipping needs to have something replacing it. The bonus of claws is so tiny that every proposed disadvantage I've seen heavily outweighs it.

Unless [#93](https://github.com/ParadiseSS13/Paradise/pull/93) changed and I missed it somehow, the only advantage of claws is essentially the chance to bleed. I can't think of a single time ever that bleeding has had an impact on a fight before plain damage did.

**Comment by Lady-Luck** [comment]
If you land a killing blow with your claws there's a chance to decapitate, which is rather funny, but quite rare.

**Comment by FlattestGuitar** [comment]
That's actually incorrect. You used to be able to, but it's been a looong time since that hasn't been a thing. Claws deal no additional damage, their only difference is a chance to make the person bleed, which will not provide any significant combat advantage unless the fight lasts for two hours.

**Comment by Spacemanspark** [comment]
Claws decapitating was horrifying.

**Comment by sasanek12** [comment]
Definitely :+1:  for this from me. Shoes/gloves restrictions are for sure annoying, but are not really any form of an actual penalty other than visual. I would rather see an actual nerf in it's place.

**Comment by tigercat2000** [comment]
tangerines and lizards aren't meant to actually have any significant downsides or upsides

that said, i don't see the point in removing this, it's just like, mildly annoying in super rare cases (who the fuck uses syndi galoshes)

**Comment by Aurorablade** [comment]
I has a major sad

**Pull request merged**
