### PR TITLE
Adds Enforcer crate to Cargo supply

### PR DESCRIPTION
**Pull request by Ty-Omaha**
## What Does This PR Do
Allows for Enforcers and their magazines to be ordered at Cargo

## Why It's Good For The Game
It would allow security (and antags) a wider variety of weaponry to deal with threats.

:cl:
add: Enforcers can be ordered from cargo
/ :cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Crew really don't need more ballistic weapons--the designation between syndicate having them but not NT is both a thematic and balance reason.

Energy has the advantage of being easy to recharge (typically) and unlimited amount of times, but cumbersome and time consuming to do so--in order to "stand and deliver" you have to sacrifice a lot of space and resources.

Ballistics are the opposite. They're limited, but extremely easy to "stand and deliver", not to mention incredibly space efficient. Your magazine runs out and you slap another one in and you're right back at it.

Generally keeping the existing balance of security having to have retreats and advances is better for the overall game balance than them being able to "stand and deliver" constantly.

This derives from the nature of antags vs the station. Typically antags are always vastly outnumbered, so they need some mechanic that allows them to have a break and not be relentless pursued.

Sec rifles push the limits of this as is--but they're intentionally hamstrung by low damage and low firing rate as a downside---something these don't have.

Shotguns have the limitation of effectively being short range melee weapons with how they work---and even so, shotguns have *repeatedly* wound up as problematic in the past.

Crew having ballistics is just not a great thing, at the end of the day.

**Comment by Landerlow** [comment]
The thing is though, crew already has access to ballistic weapons through cargo.

**Comment by Spacemanspark** [comment]
Honestly we should just replace the 'auto rifles' with enforcers.

Let's be real, the 'auto rifles' are just pistols with a front grip, stock, and top loaded cartridge. There's very little 'automatic' anything to them.

**Comment by Kyep** [comment]
I'm actually sympathetic to @Spacemanspark 's idea. What, exactly, is "auto" about the "auto" rifles? If enforcers are seen as more interesting, and balance-wise, are not stronger (is this the case?) then why not have enforcers instead of the auto rifles?

**Comment by MRgaty** [comment]
Revolvers are badass

**Comment by variableundefined** [comment]
I object to giving security more ballistics. 

Closing due to two maintainer and one head objection.

**Pull request closed without merging**
