### PR TITLE
Ports Backpacks from TG, until we can resprite them individually per.

### PR DESCRIPTION
**Pull request by Alecksohs**
## What Does This PR Do

Ports the backpacks from TG. Also includes vox refits, may be a bit sloppy in some backpacks as it was a lot of grunt-work.

I am a vox player, I refit my work to vox, I am simple person.

## Why It's Good For The Game

We needed backpacks in place of the bad ones.

## Images of changes

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

## Testing

I checked a few backpacks, the others was tested in Aseprite.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

I don't think this is controversial, others asked me to do it.

## Changelog

:cl:
tweak: Resprites backpacks, satchels, and duffel bags to their TG counterparts, updates Geneticist colorscheme
/:cl:

### CODE REVIEW

**Comment by Alecksohs** [comment]
As previously stated in the discord, this is an older PR cleaned up and dusted off. I'll be fixing the conflicts for now.

**Comment by Alecksohs** [comment]
I believe that solves the merge conflicts. 
image

**Comment by Bm0n** [comment]
might also want to consider stealing TGs leather satchel

**Comment by Alecksohs** [comment]
Can't work on this at this very moment, got sick from Thanksgiving (i fucking love thanksgiving!!!!!!) But in the next few days I'll be ready.

**Comment by Alecksohs** [comment]
image
image
image
image

**Comment by Alecksohs** [comment]
What does this PR require by the maintainers to get proper approval? Select resprites aren't off the table.

**Comment by Burzah** [comment]
> What does this PR require by the maintainers to get proper approval? Select resprites aren't off the table.

This PR currently has no design objections or sprite objections, but does require one more vote and a review. I will be taking a look at this today.

**Review by Christasmurf — APPROVED** [review]
LGTM

**Review by Burzah — APPROVED** [review]

**Pull request merged**
