### PR TITLE
Logs playtime history for ALL departments

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Logs data in the `playtime_history` table for all departments, not just `living` and `ghost`.

Realistically we should:
- Make this one table with exp_type and a value as another column, but that can wait
- Track this on a per-job basis for stupid detail on stats

But this will do. 

## Why It's Good For The Game
More stats are always good.

## Testing
Loaded up the server and selected RD
image

## Changelog
Nothing player facing

### CODE REVIEW

**Comment by spacegeese** [comment]
Will you be able to port this to the "View my playtime" verb in special verbs?

**Comment by AffectedArc07** [comment]
> Will you be able to port this to the "View my playtime" verb in special verbs?

Nope - thats intentionally only crew hours to avoid elitism over hour counts

**Comment by GDNgit** [comment]
> > Will you be able to port this to the "View my playtime" verb in special verbs?
> 
> Nope - thats intentionally only crew hours to avoid elitism over hour counts

~~every time I think to change this I get a reason not to lol~~

**Review by lewcc — APPROVED** [review]
LGTM

**Pull request merged**
