### PR TITLE
/vg/ / -tg- asset_cache

### PR DESCRIPTION
**Pull request by tigercat2000**
tgstation/-tg-station#13050, tgstation/-tg-station#13315
Port of -tg-'s port of /vg/'s asset cache
Funny thing is, this actually replaces an old version of /vg/'s asset
cache we already had
IT'S A PORT OF A PORT REPLACING A PORT
POOOOOOOOOOOOOORTCEPTION

Basically, gets rid of the 30-40 second interface lag when you first join,
via *mumblemumble* MAGIC!

Also moves a few nano files around.

### CODE REVIEW

**Comment by SirBloodBuske** [comment]
plz merge no more miss round join :D

**Comment by Spacemanspark** [comment]
Or it's just an update and not a port at all.
:^)

**Comment by Tastyfish** [comment]
In before this inevitably breaks some esoteric UI or something

**Comment by tigercat2000** [comment]
it shouldn't, @Tastyfish, I tested the more likely to break UI's (cough telecomms IDE, a few nano UI's, admin panels)

**Comment by tigercat2000** [comment]
also not sure if this fits under the feature label
(or more importantly, the 24 hour waiting period associated with such)

**Comment by Fox-McCloud** [comment]
it probably doesn't, TBH--if anything...

**Comment by Fox-McCloud** [comment]
Refactor fits better.

**Comment by tigercat2000** [comment]
We need a bright pink "UI Shit" tag

**Comment by Fox-McCloud** [comment]
There was a port of a port to replace the ported port so we put a port in your port 'cause we heard you like ports.

**Comment by tigercat2000** [comment]
port.

**Comment by Fox-McCloud** [comment]
anotherport

**Comment by Spacemanspark** [comment]
Don't touch my ports.

**Comment by Fox-McCloud** [comment]
ports

**Comment by Spacemanspark** [comment]
U wanna fite me m8

**Comment by Fox-McCloud** [comment]
anotherport

**Comment by Plotron** [comment]
I remember we had a similar PR previously, but it ultimately did not work and was closed.

**Comment by TheDZD** [comment]
@Plotron You might be thinking of #2697, which was slightly different, and instead had all of the UI assets be downloaded into the .rsc, adding another ~4-5 MB to the resource download before joining the server, rather than have the UI assets be downloaded every time you got to the main menu.

**Pull request merged**
