### PR TITLE
New Newspaper Icon

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Replaces the old newspaper icon, as seen here:
oldpaper

With a new icon that is almost certainly objectively better, as seen here:
newspaperfull

At 64x:
newspaper

_EDIT:_ Due to the criticisms of a few folks, I've re-done the icon a bit in terms of color scheme.
I think it looks a lot better now. OP images updated accordingly.

:cl: DaveTheHeadcrab
rscadd: Upgrades the newscaster's liquid paper printing apparatus. Newspapers printed are higher quality now.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
Looks like an ancient stone tablet with carvings in it.

Probably an improvement and more fitting to our space cavemen-minded crew atmosphere.

**Comment by CrAzYPiLoT-SS13** [comment]
It has always bothered me that newspapers looked like scrap paper. Thank
you.

**Comment by LittleBigKid2000** [comment]
I'd kind of like it if SS13 was a bit less retrofuturistic and more like Deus Ex style future or something. That'd be cool

**Comment by Iamgoofball** [comment]
This doesn't even look like a fucking newspaper

**Comment by DaveTheHeadcrab** [comment]
full_icon

imgres

I mean, if you don't see the very clear semblance that's fine but there definitely is one.

**Comment by Iamgoofball** [comment]
It looks like stone, not paper. Just make it a paper back and the engravings ink

**Comment by Aurorablade** [comment]
@DaveTheHeadcrab add a rolled up version for reasons...

**Comment by DaveTheHeadcrab** [comment]
@Iamgoofball 
See?
That's much more constructive than "It looks like shit", and actually helps to make improvements.
I'll make adjustments, because a few other folks have said they also feel it's too dark.

**Comment by DaveTheHeadcrab** [comment]
@FreeStylaLT 
Stone tablets no more, my friend!

**Comment by Nienhaus** [comment]
Looks much better lighter.

**Comment by Earthdivine** [comment]
Rolled up newspapers to assert dominance over Kidan when.

**Comment by IcyV** [comment]
Definitely not a terrible idea to update our sprites for the newspaper. I'm just not feeling this one though. I kind of like the messy feel of the current one over the flawless square we have now. Maybe it could change into a messier sprite once it gets read but starts printed and fine?

**Comment by Dinarzad** [comment]
I like 'em now that you've lightened the sprites up a bit. +1

**Comment by Plotron** [comment]
@IcyV: maybe it could get messy once you throw the newspaper? Would add even more immershiuns, when that postman boy goes rogue on ya!

**Pull request merged**
