### PR TITLE
Gives blob a fighting chance

### PR DESCRIPTION
**Pull request by Robertha89**
From what I have seen, most blobs die due to there being too few at
start, thus i propose this to made the minimal ammount of cores 2, and
decrease the needed players per core, it is a tentative change at best
as this can easily tip into the favor of the blob, but due to the fact
that a fairly low amount of players are ready at round start, that
should hopefully not be an issue.

Also, updated the Quarantine law the ai get with the one on the station.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Blob needs a lot of work, but this isn't the way to do it, IMO.

**Comment by fj45** [comment]
Yeah, kill off low pop blob. 

But even with pretty high population and multiple people fighting the blob, having two blob cores (that are maybe at opposite ends of the station) very often results in a blob victory, due to people fighting one blob, killing it and then turning around to an unkillable blob.

**Comment by Iamgoofball** [comment]
just port tg blob, it's great for the high end pop rounds and loads of fun

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

That was one of the three projects a departing maintainer+coder had planned; he was going to fix up mining, blob, and cult; unfortunately, it didn't pan out.

**Comment by Robertha89** [comment]
If you build an Ultra AC 2 at Robotics to prepear for gamma, or have mining and science work to build a durand or gygax, and give it and Ultra AC 2, then blob will lose, time and again. Unless gravity is down. also, considering ERT got pulse weaponry, and they often get called early on.

**Comment by fj45** [comment]
So you "fix" that by making those steps the only way to win blob?

I can agree that parts of blob rounds need rebalancing, but this isn't how it should be done.

**Comment by ZomgPonies** [comment]
:-1:  This isn't the way to go about rebalancing it as @Fox-McCloud said.

**Comment by Robertha89** [comment]
Very well, reverted that part for now, but would like to keep the updated law bit, as it prevents AI from murdering everyone who wanna escape to mining or science outpost, or generally out into space.

**Comment by Finalsong** [comment]
I believe the AI should be allowed to kill deserters. It makes sense, and even then that updated law allows it.

**Comment by ZomgPonies** [comment]
Yeah I am :-1:  the whole PR. 
Quarantine means quarantine. If the AI can't harm them, then the quarantine gets broken and the disease 'spreads'.

**Comment by Fox-McCloud** [comment]
Yeah...no. :-1:

**Pull request closed without merging**
