### PR TITLE
Buff wizard apprentice, limits to one per wizard

### PR DESCRIPTION
**Pull request by datlo**
## What Does This PR Do

This PR significantly buffs wizard apprentices loadouts, aswell as adding a new one. However, apprentice contract is now limited to one apprentice per wizard, and cannot be purchased during raging mages.

Before  => After
newbeforeafter
## Why It's Good For The Game

Apprentices are currently not worth their cost. While teamwork is beneficial for all antags, wizards dont benefit as much due to their gameplay loop of offense into escape into offense into escape.

On top of that, playing a wizard, even an apprentice, should be the satisfaction of a power fantasy, which apprentices fail to achieve due to their lackluster loadouts.

This PR makes all apprentice types a threat in their own right by giving them the rough equivalent of 5 to 6 spell points worth to fight with, which should encourage wizards to buy apprentices. However, as apprentices are now much stronger, they are limited to a single one per wizard. Other than the Fire type, which is its own gamble to take for a wizard (*COUGH* FIREBALL *COUGH*), all other apprentices loadout focus more on being support to the wizard or being an annoying distraction for the crew to deal with, so I'm not *too* worried as far as balance goes. The Restoration set might be too strong in the hand of a competent wizard/apprentice duo and is the only one I'm worried about. Will likely nerf before release.

I've considered increasing the cost to 3 spell points for the wizard, but I did not want to discourage purchasing this new buffed apprentice. 

## TODO
Code the Restoration 'Teleport to Teacher' spell.
Likely nerf the Restoration apprentice one way or another. Likely remove the wand of healing, at least.
Test thoroughly
## Testing

TODO : Not everything tested yet

## Changelog
:cl:
tweak: Significantly buffed all apprentices, giving them extra mobility.
tweak: Wizards can now only have a single apprentice.
tweak: Can no longer buy apprentice contract on raging mages.
add: Added the Honk apprentice!
/:cl:

### CODE REVIEW

**Comment by datlo** [comment]
I will likely bring back healing apprentice and some additional tweaks to these sets later

**Comment by Henri215** [comment]
image

🤣

**Comment by Henri215** [comment]
image

No need for that line if you are already describing all apprentices on the changelog

**Comment by datlo** [comment]
Will heavily nerf the restoration apprentice soon. This first draft is way too powerful in the hands of a competent wizard/apprentice duo.

**Comment by ATP-Engineer** [comment]
Make a lesser contract so you can have 12 low-geared Wizards jumping you at once in maintenance

**Comment by datlo** [comment]
Will come back to this soon TM with a new PR, git momento

**Pull request closed without merging**
