### PR TITLE
maidbot

### PR DESCRIPTION
**Pull request by Belsima**
image

Adds a service sprite for cyborgs.

🆑 Belsima
add: A new sprite for service cyborgs.
/🆑

### CODE REVIEW

**Comment by Twinmold93** [comment]
Needs description of pull request, what this is for, changelog, and what not. I'm guessing a service or janiborg skin.

**Comment by Citinited** [comment]
You need to do the changelog like *this* ```
:cl: YourNameHere (if different from your github username)
add: Things
del: Other things
tweak: even more things
fix: that last thing
/ :cl:
```
And not by manually editing the changelog file itself

**Comment by TravellingMerchant** [comment]
Can we get an up-scaled view? 500% normally works wonders.

**Comment by Belsima** [comment]
image

**Comment by TravellingMerchant** [comment]
Some notes. Please do not take this the wrong way, these are just notes with the aim of helping in mind.

1: The legs are incredibly thin. They look quite out of place with the rest of the body, especially when compared to the large hands.

2: The colour palette of the robot itself is quite different from the other cyborg colours. Which are dark grey to silver. (Black for syndicate)

3: Robo-Rack

3: The clothes shading seems quite messy. Colours do not contrast enough, especially on the legs.

**Comment by granodd** [comment]
Zoomed in that far the little pixels that are the feet seem a bit strange. I do enjoy the eyes on it, gives me an "EVE" vibe from Wall-E. Though perhaps if the color palette with the brown was shifted to something grey or silver it might look a bit more cohesive.

**Comment by taukausanake** [comment]
I think it looks nice for what it is but yeah, what TravellingMerchant said is valid. I can see this being an amazing cyborg fluff though.

~~We need robo titties~~

**Pull request closed without merging**
