### PR TITLE
Supports +1 Detective job slot

### PR DESCRIPTION
**Pull request by Kyep**
Adds an additional job slot for Detective.
Initially I was hesitant to do this as Fox was opposed to it. But, when I raised the issue during a staff voice discussion, literally every single member of the staff team present supported the idea. So, now its a PR. Discuss.
Adds: 1 job slot, 1 start position, 1 spare copy of most standard-issue detective gear (including scanner closet, flash, cuffs, gun, ammo, camera, recorder) to Det office.

In the event that Free, or anyone else, has a mapping PR that affects brig, merging that PR takes priority over this, because this PR's map changes are easy to re-do, while theirs might not be.

🆑 Kyep
tweak: changed detective job slots from 1 to 2. 
/🆑

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
We need it.
150 people, tons of crime, much problem. We need this.

**Comment by Anasari** [comment]
Gotta solve all those crimes. + 1

**Comment by taukausanake** [comment]
I want to think up a scenario that has existed (in fiction) that concerned two detectives having to work together, but all I could really think up is [this](https://youtu.be/4qBz9tIYEYs?t=5s)

**Comment by Jovaniph** [comment]
I still think Security Officer should have the same capabilities as the detective and just get rid of detective job entirely... Security is hard as it is and I wouldn't be surprise during low pop that there is two detective and no security officers in a round.

**Comment by Necaladun** [comment]
Detective is a great low stress security job, where you're not expected to be out hunting and fighting all the time. 

Two job slots also allows for buddy-cop stuff.

**Comment by jughu** [comment]
@kyep make them spawn with a box and their gun instead of the locker saves room

**Comment by SamHPurp** [comment]
I cannot support this while he gets a gun.

The rubber bullets are super strong, and are often misused by detectives... Adding another detective, and especially another rubber bullet gun, is a huge buff to Security.

**Comment by tylerh95** [comment]
@SamHPurp it seems like your issue is with the detectives loadout and not with how many detectives there are. Detectives all ready aren't supposed to be chasing criminals to arrest, they're supposed to be investigating. It seems like being against this PR just because some detectives don't play the job right and hunt criminals to attack is in poor tastes. 

As stated by others, with our high pop lately we need this. Security will benefit from having another person to handle large cases that require forensic followup.

**Comment by SamHPurp** [comment]
@tylerh95 I see what you're saying... but its like saying, "blobs currently auto-win, but we're gonna add another blob anyway".

There is an outstanding issue in my mind, that'll only be extenuated by this PR, which I otherwise wholly support.

**Comment by davidchan13** [comment]
Frankly the Revolver(s) should be Detective spawn gear and not in the locker. Can't even begin to count the number of times playing as a latejoin detective that I did not receive my revolver because A) The HoS Stole it. B) The previous Detective cryo'd with it (cryodorms are broken as fuck when it comes to limited supply equipment) or C) Some tator emagged open the office and locker and stole it long before the detective joined the round.

More detective slots makes sense, Security in general can use more bodies though balancing out the armory or adding a high pop armory that spawns in if more than 80 players are on the server (somewhat like the gamma armory).

Detectives traditional work in pairs as is, two sets of eyes catch more details than just one, they can watch each others back and typically a veteran detective is paired with a rookie to show them the ropes and skills they will need to survive the job.

**Comment by Kyep** [comment]
@davidchan13 The issue with that is: what if someone gets a job transfer to detective? Then they would not have a gun, and there would not be one in their office to issue them. I'm not sure they'd be able to get a revolver at all in this case. Are you fine with that, as a consequence?

**Comment by jughu** [comment]
>implying warden cant give you a taser gun was for self defense anyways taser can do the same job

**Comment by davidchan13** [comment]
@Kyep Nobody ever transfers to security. SOP specifically says HoS has to permit it and any HoS wortht heir salt knows that if you didn't join as sec role you're probably an antag so :-1: from the start. And that still doesn't address the problem of other people taking the job's item through illicit access. Sec officers spawn with tasers for a reason, detective just gets a baton that should be in his locker to begin with.

**Comment by Kyep** [comment]
@davidchan13 This PR is about job slots. Not whether the Det has gear in his room, or on his person when he spawns. I have considered making another PR that makes Detectives spawn with their revolver/ammo. It would solve some issues. Unfortunately, it would introduce others. What happens if someone transferrs to Det? How do they get their gun then? I'll think about it.

**Comment by Fox-McCloud** [comment]
`_maps/map_files/cyberiad/cyberiad.dmm.fixed.dmm `

What in the world.

**Comment by Kyep** [comment]
@Fox-McCloud Fixed.

**Comment by Fox-McCloud** [comment]
With the recent downward pressure on player population, this longer is really necessary.

**Comment by SamHPurp** [comment]
"People no longer want to play on Paradise anymore, and thats working as intended :tm: "

**Pull request closed without merging**
