### PR TITLE
Purges Poop from the codebase.

### PR DESCRIPTION
**Pull request by tigercat2000**
Removes Shit. Literally SHIT. I DON'T EVEN.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:-1: Like I've always said, it has a legitimate use as both a vector and symptom of virology.

**Comment by Fox-McCloud** [comment]
:-1: 

While a bit silly at times, this almost never shows up and is a valid virus/medical symptom.  It almost never shows up anymore, as is.

**Comment by Finalsong** [comment]
I approve.

**Comment by Spacemanspark** [comment]
This wasn't even given a day. What.

**Comment by Robertha89** [comment]
im fairly certain this was already discussed last week.

**Comment by ZomgPonies** [comment]
Two maintainers thumbed it down, feature removals are held to a much higher standard to pass.

**Pull request closed without merging**
