### PR TITLE
Restores the karma verbs tab

### PR DESCRIPTION
**Pull request by tigercat2000**
Tons of people have been complaining about this ever since it was done. 

:cl:
tweak: Karma returned to the Special Verbs tab
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Yes please. 🎉

**Comment by FlattestGuitar** [comment]
How about a `Karma` tab instead?

**Comment by tigercat2000** [comment]
@FlattestGuitar Giving them a completely unique tab seemed like overkill for three verbs. This at least can be feasibly used for other things in the same vein, unique paradise features.

**Comment by Krausus** [comment]
Putting the karma verbs in their own special tab (with an unnecessarily long name) is silly.

We already have a button dedicated to the Karma Shop, which is probably used *way* less than the actual karma verbs. How about changing that to a generic "Karma" button, make it pop up an alert box that gives access to the verbs and karma shop, and then use its color to indicate whether your karma is unspent. You could even make it flash at the end of the round.

**Comment by Fox-McCloud** [comment]
I'll second @Krausus suggestion.

**Comment by AffectedArc07** [comment]
Special verbs had other uses, like change-view-range and other admin-y things. I fully support this PR.

**Comment by taukausanake** [comment]
> Giving them a completely unique tab seemed like overkill for three verbs

> Sees three verbs unique to one another

I too think a `karma` tab would be better than `Special Verbs` but a `Karma` button sounds interesting too. The flash feature at least. The button itself seems a little out of place if you ask me? Maybe not if considered alongside the `Karma Shop` but still it's weird

**Comment by tigercat2000** [comment]
I believe changing the control scheme of Karma to work based off of the button where the karma shop is now would only cause more confusion.

**Comment by Krausus** [comment]
> changing the control scheme of Karma to work based off of the button where the karma shop is now

You wouldn't get rid of the existing verbs, you'd be adding another, more visible way to access them.

> would only cause more confusion

Adding a new way to access the karma functions would be *less* confusing than moving the verbs away from where people are used to them being right now.

**Pull request merged**
