### PR TITLE
Makes borer more likely to occur

### PR DESCRIPTION
**Pull request by Crazylemon64**
<a href=http://nanotrasen.se/forum/viewtopic.php?f=12&t=7002>From here.</a>

:cl:
tweak: Increases the frequency of the cortical borer event.
/:cl:

### CODE REVIEW

**Comment by Plotron** [comment]
More likely than spiders?
You sure?

**Comment by Crazylemon64** [comment]
Can tweak it if it's crummy. 60, perhaps?

**Comment by Plotron** [comment]
40-60 sounds right considering that Brand Intelligence and other cool events are at 50.

**Comment by pazneria12** [comment]
how about 50? split the difference

**Comment by Plotron** [comment]
Drones are 40, some anomalies are 50, swarmers are... over 100? And revenants too.
I'm slightly confused, but yeah - I think that borers should be as common as spiders, but not substantially more.

**Comment by pazneria12** [comment]
it was 20 before this right? man im really glad i asked about this

**Comment by NTSAM** [comment]
remove borer when

**Comment by Robertha89** [comment]
:-1: Borers was removed as a gamemode for a good reason, plz less borers.

**Comment by pazneria12** [comment]
not a gamemode, still a random event, just increased chances

**Comment by Plotron** [comment]
Borers are fun because they pose unique challenges and they're highly dependant on the players controlling them. Plus - symbiosis is not only feasible, but optimal.

If anything, swarmers are more of a destructive force.

**Comment by NTSAM** [comment]
nothing will change my opinion

**Comment by Plotron** [comment]
@NTSAM That's a bad thing to say in a debate.

**Comment by NTSAM** [comment]
good

**Comment by TheDZD** [comment]
Might be worthwhile to bump up the amount is scales per security member up a little bit (by 5-10), and leave the base rate at something like 40. That way you should end up with borer rounds occurring, but moreso when the station can afford to combat them.

**Comment by Plotron** [comment]
@TheDZD probably has a good idea.

**Pull request merged**
