### PR TITLE
Rework Delta's Operating/Patient Rooms

### PR DESCRIPTION
**Pull request by Vi3trice**
## What Does This PR Do
Reworks the area next to the CMO's office to have the patient rooms closer to the main medbay hallway, and puts two operating rooms and their backrooms in. The two rooms in starboard maintenance and the solar array are shifted to make space.

## Why It's Good For The Game
Considering Delta's size, it's surprising there's only one operating room. Two would make it parity with Boxstation and Metastation.

## Changelog
:cl:
add: Two operating rooms, their backrooms and linked observation room
tweak: Moved the patient rooms up and added doors down toward the operating rooms
tweak: Moved the theater, detective room in maintenance, and the solar array to make extra space for the medbay.
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
Good work. One of the biggest problems about delta was the lack of two operating rooms.

**Comment by S34NW** [comment]
much more efficient use of space, good work

**Review by Kyep — APPROVED** [review]

**Comment by S34NW** [comment]
Please add `/obj/machinery/holosign/surgery` with the appropriate id var onto the surgery doors at `x188, y083` and `x192, y083`.

Also fix the missing disposal pipe at `x192, y089`.

**Review by S34NW — CHANGES_REQUESTED** [review]
See above

**Comment by S34NW** [comment]
this is quite possibly the smallest nitpick ever, but the light and surgery holisign buttons in the OR have different pixel offsets. OR2 has -22 pixel_x, and OR1 has -23. Can these be made consistent?

**Review by S34NW — CHANGES_REQUESTED** [review]
as above

**Review by S34NW — APPROVED** [review]
LGTM

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
