### PR TITLE
Contributer Banned from Paradise

### PR DESCRIPTION
**Pull request by Kiyahitayika**
## What Does This PR Do

- Attempts to fix the window atmos leak issue when you move fulltile windows
- Attempts to fix the problem with atmos leaking under windows when you pry up their tile - resolves https://github.com/ParadiseSS13/Paradise/issues/2913
- Deletes the `fulltile` variable, replaces the very few instances where this was referenced with `is_fulltile()`
- Makes `window/full` a proper subtype with overrides (except for CanAtmosPass(), my arch nemesis)
- Tidies up the Clockwork window types

## To Do

- [ ] Ensure that directional windows only block atmos from an exterior-facing direction, not an internal-facing direction - currently they are doing both as seen in the linked video
- [ ] AND that they will only do that when Secured()

## Why It's Good For The Game
- Nice and airtight once it's done

## Images of changes
**Current Iteration:**
https://user-images.githubusercontent.com/69871346/114944669-0aa53380-9e16-11eb-9588-6462d3bf9705.mp4

## Changelog
:cl:
tweak: Makes properly-secured windows airtight again
/:cl:

### CODE REVIEW

**Comment by Kiyahitayika** [comment]
Linter failed trying to call `CanAtmosPass()` on a turf at the edge of a Z-Level as per @AffectedArc07 's apropos forewarning to me!

` src: the asteroid sand (255,29,3) (/turf/simulated/floor/plating/asteroid/airless/cave/volcanic/has_data)`

**Comment by TheYeetster1** [comment]
This may or may not be helpful but what I have found is that if you crowbar a floor tile adjacent to a full window, then replace it, the window then becomes air tight, I'll try to get a video soon.

**Comment by Adrer** [comment]
Possibly a fix to #2913? If it is, you should probably add it to PR description.

**Comment by TheYeetster1** [comment]
What happened here?

**Pull request closed without merging**
