### PR TITLE
Replaces Illegal R&D Gear with Other Implants

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/tgstation/pull/28124

Replaces the uplink/syndicate freedom and adrenaline implants with the far more legal chem and tracking implants.

:cl: Fox McCloud
rscdel: Remove adrenaline and freedom implants from R&D
add: Added chem and tracking implants to R&D
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Stuff leads to horribly one-sided antag v sec duels and pretty much never anything interesting.

:+1: x :100:

**Comment by deep-fried-faceplant** [comment]
8tc and 5tc traitor implants for practically free was a bad idea in the first place, I'm glad to see them go. The contraband wiki page will need to be updated again.

**Comment by Spacemanspark** [comment]
Yes, please. I'm growing rather tired of the powergaming.

**Comment by Kyep** [comment]
Yeah, adrenaline/freedom implants should be removed from R&D.

1. NT R&D machines would not be programmed with the ability to manufacture illegal syndicate contraband. Space Law doesn't permit crew to have these items. There's no good reason for NT to make these items producible with their equipment, given that they do not want these items on their stations. If you want to be able to buy, or make, syndie items, logically, you should have to use syndie equipment to do so. I don't think NT is dumb enough to allow their own machines to be used for this purpose.

2. Mechanically, adrenaline/freedom exist to help antags fight security. To recover from stuns, and escape cuffs, respectively. Non-antags shouldn't be fighting security. Nor should they be acting like such jerks they *assume* security is going to try to arrest them eventually. Nor should they be loading up on illegal implants just because tehy *can*. They don't need access to these items. Actually *using* these items to escape the consequences of antagonizing security, as a non-antag, is arguably self-antagging. Loading up on them for no good reason is a waste of time. And there is no good reason for crew to be implanted with these. Just about the only good reason I can think of is a magistrate authorizing security to get adren implants to prevent shadowling-thralled officers from stunning and converting the remaining officers... but that's such an unlikely situation I don't think I've ever seen it happen. The station is better off without these implants being manufacturable in R&D.


The addition of chem/tracking implants is a somewhat meaningless change, given that sets of each spawn in the brig, and they're never used anyway. Its probably good to have NT tech in there for completeness, but they'll probably never be used.

**Comment by drizzlemutt** [comment]
I do agree with this change, but with the recent changes to RnD it makes it impossible to obtain these items anyways. (Without having insane RNG and finding three illegal tech items in maint with a rating of 3+) 

People are just going to use the chem implants to make, in my opinion, better versions of Adrenals without the Illegal cost to it. You guys gotta get ready for the microbomb-esq antags if this goes through.

**Comment by KasparoVy** [comment]
Yes please. I'm interested in seeing ridiculous chem implant cocktails.

**Comment by granodd** [comment]
Removing adrenals: overall good idea. Replacing it wtih the chem implant that can be filled with anything: questionable at best and horribly bad at worse. Sure it may not achieve quite the same effect, but I can see people already making pseudo-adrenals with it.

As for the other, it's more of a security QoL thing that trackers can be printed, so that's fine.

**Comment by Tayyyyyyy** [comment]
> Sure it may not achieve quite the same effect, but I can see people already making pseudo-adrenals with it.

This is still more interesting than a generic adrenals implant, though, that also happens to magically work on IPCs.

Was there any source for replenishing tracking implants earlier? If not, this might have some interesting balance implications.

**Comment by Anticept** [comment]
Pills already act as pseudo adrenal implants.

**Pull request merged**
