### PR TITLE
Fixes up the mining outpost, remodels it a bit.

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do

Does what the title says. Numerous mapping errors were fixed plus I made the outpost a lot less blocky and expanded the lava river in front of where the shuttle docks, I wanted it to look more river like if that makes any sense

The mining shuttle was made bigger to accommodate more seats, yes it still fits in all docks.

Also added a mapper only lavaproof railing similar to the lavaproof catwalks.

## Why It's Good For The Game

looks better overall, plus map bugs fixed.

## Images of changes

image

image

## Testing

In game
## Changelog
:cl: Bmon
tweak: The mining outpost has been slightly remodelled
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
I think the current shuttle looks better, that single propulsion in the middle is too ugly now that my eyes are no longer used to it.

**Comment by Bm0n** [comment]
> I think the current shuttle looks better, that single propulsion in the middle is too ugly now that my eyes are no longer used to it.

ill see what i can do when i get back from my trip

**Comment by Bm0n** [comment]
Whenever you want TM this PR just DM or message me here. It's quite the involved process to deconflict a map on an AMD graphic card, SDMM is very bugged right now and I'd need to do multiple driver downgrades to get it working.

**Comment by hal9000PR** [comment]
1 design team objection and nobody in favour after 30 days

**Comment by Bm0n** [comment]
> 1 design team objection and nobody in favour after 30 days

Why? Most of this is just mapping fixes/making the outpost less boxy

**Pull request closed without merging**
