### PR TITLE
Makes containment grid more obvious for newbie engineers

### PR DESCRIPTION
**Pull request by SamHPurp**
This is a **quality of life** update for Engineering. This changes the colour of the cable on the containment grid to yellow, keeping red for the main power grid. This is already how it works on Metastation.

This does a few things:

- Makes it more obvious to newbie engineers the separate grid.
- Lets you know which cables absolutely NOT to touch without gloves.

This does not:

- Effect anything in any way other than aesthetics.

image

:cl: Purpose2
add: The containment grid on Boxstation is now clearer that it is hotwired. We can't afford to keep sending flowers to the families of these engineering interns....
/ :cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
hugbox reee

**Comment by Spartan6** [comment]
Engineers should learn by becoming a pile of dust. 

On topic, good change, would rather have it a less natural colour, like blue.

**Comment by Fox-McCloud** [comment]
conflicts.

**Comment by SamHPurp** [comment]
@Fox-McCloud As I've had to do lots of conflict fixing over and over lately, could you let me know when this is close to being merged, and I'll update then?

**Comment by Fox-McCloud** [comment]
yup.

**Comment by matt81093** [comment]
I actually like the nice yellow wire. Good change

**Comment by tigercat2000** [comment]
PR has been approved; Pending merge conflict resolution.

**Comment by SamHPurp** [comment]
image

**Pull request merged**
