### PR TITLE
Adds mining hardsuits

### PR DESCRIPTION
**Pull request by Kyep**
Simple map edit to change the number of mining hardsuits on the mining outpost from 3 to 5. 
Prevents additional miners from starting out without hardsuits.
Mining slots are commonly increased, to help avoid having 20+, or sometimes 50+, assistants. This supports that.

Before:

After:

🆑 Kyep
tweak: added two more mining hardsuits to the mining outpost.
/🆑

### CODE REVIEW

**Comment by Xantholne** [comment]
I honestly don't know why the other suits where even removed. Can't really relcaim them if a miner cryos either or anything. So this is going to be fairly nice.

**Comment by Aurorablade** [comment]
Theres more then the base number on the map. I just can't remeber where ti is on the map...

ANYWAY i would actually rather it be an option for cargo to be able to order more hardsuits or something from the mining vend.

**Comment by Kyep** [comment]
I looked. I did not see any more suits on the map. Hence, this PR.

We regularly get 100+ players. The amount of job slots, and equipment, we have, needs to reflect this.
It would be a miserable experience for players if everyone had to get some of their roundstart equipment from cargo.
Hence, more mining hardsuits by default.

**Comment by FlimFlamm** [comment]
Is that button accessible over a wrenched canister?

**Comment by Kyep** [comment]
@FlimFlamm Yes.

**Comment by Spacemanspark** [comment]
:+1: yes please

**Comment by Davdichan** [comment]
:+1:  To more hardsuits, how ever the room seems a bit cramped. Move them to the aux storage on the west end of the outpost perhaps?

**Comment by Aurorablade** [comment]
Still maintain it should be orderable via cargo rather then on map.

**Comment by taukausanake** [comment]
I say have the extras but also have crates be ordered. You never know when you'll need to mine the asteroid clean and more miners means exactly that

**Comment by Davdichan** [comment]
@Aurorablade Mining vendor would be a better place for them, but that would  require cooperation between miners.

**Comment by Fox-McCloud** [comment]
merggge conflicts.

**Comment by Kyep** [comment]
@Fox-McCloud Merge conflict resolved.

**Comment by Crazylemon64** [comment]
Sure

**Pull request merged**
