### PR TITLE
Removes the cargo shuttle firelocks (Without conflicts)

### PR DESCRIPTION
**Pull request by AffectedArc07**
Cargo is unplayable without a crowbar, which while you can make them ,its a bit impractical carrying one round all the time.

This PR removes them god damn firelocks from the cargo shuttle on cyberiad. Metastation doesnt have this issue.

:cl: AffectedArc07
tweak: Removes the firelock on the cyberiad cargo shuttle doorwa.
/ :cl:

_**AND YES I KNOW I USED MY MASTER BRANCH, I KNOW**_

### CODE REVIEW

**Comment by SamHPurp** [comment]
> tweak: Removes the firelock on the cyberiad cargo shuttle doorwa

So good that you're already off unloading cargo to finish the sentence.

**Comment by Birdtalon** [comment]
You used your Master Branch @AffectedArc07 😉 

But good job, this change has been needed for ages. 👍

**Comment by alexkar598** [comment]
While this has nothing to do this this pr ,but what dose the bunch of characters at the end of each map files do?

**Comment by SamHPurp** [comment]
@alexkar598 Its encoding. so the top is telling the game that anything that is `aaa` to understand that as an empty space tile. Whereas `aab` might be a space tile with a lattice on it... etc.

**Comment by alexkar598** [comment]
Ah, thanks

**Comment by Citinited** [comment]
Just as a note, my PR #7735 fixes behaviour of firelocks to close when a shuttle arrives, so this PR is sorta redundant. However, I'm still fine with the firelocks being removed in addition to that being merged.

**Comment by AffectedArc07** [comment]
Oh fuck now it has conflicts.

**Comment by SamHPurp** [comment]
@AffectedArc07 Just do as I taught you last time, should be fine.

**Comment by AffectedArc07** [comment]
I am doing it, thank god discord search exists.

**Comment by Ralta** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEES.

I don't play cargo _super_ often, but YEEEEEEEEEEEEEEEEEEEEEEEES.

**Comment by Fox-McCloud** [comment]
conflicts.

**Comment by AffectedArc07** [comment]
MORE FUCKING CLONFLICTS?

**Comment by Fox-McCloud** [comment]
Pics, please.

**Comment by SamHPurp** [comment]
@Fox-McCloud this has been mapmerged, this is extremely clear what this does from reading that. Infact, the thing you are looking for in this pic will be hidden by an airlock... you're just delaying for the sake of delaying now, this is not a legitimate request.

**Comment by AffectedArc07** [comment]
I have to agree with purpose. Do I really need pics of two removed firelocks?

**Comment by AffectedArc07** [comment]
**MORE CONFLICTS?**

**Comment by Citinited** [comment]
Welcome to map editing hell!

**Comment by SamHPurp** [comment]
You both merely adopted the hell, I was born in it.

**Comment by AffectedArc07** [comment]
Closing due to unforseen circumstances

**Comment by alexkar598** [comment]
Guess il just remove them each round I play as cargo

On 2017-09-05, at 11:06 AM, "AffectedArc07" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing due to unforseen circumstances

**Pull request closed without merging**
