### PR TITLE
Adds Vox Specific Tourettes

### PR DESCRIPTION
**Pull request by joniroq**
## What Does This PR Do
Tweaks the Tourettes disability so that Vox actually swear like Vox, using a simple species check and choosing the appropriate list. Currently there is only three options for the Vox to say, but I can easily alter that list and add/remove if need be before any merging occurs. (Comment if you have any ideas!)

Also first PR, so _highly_ likely I've messed up the commit or branch or fork or whatever cutlery Github uses.

## Why It's Good For The Game
A minor change to keep Vox more in line with their lore based epithets and slurs. Mainly for added flavour than anything actually game changing.

## Changelog
:cl: Joniroq
add: Added Vox specific swears for Tourettes.
/:cl:

### CODE REVIEW

**Comment by meow20** [comment]
Now how do you diffrentiate mad vox player salting on common channel from a vox with tourettes?! Amazing pr! 👍

**Comment by Shadeykins** [comment]
As a suggestion: "STUPID MEATS" "IS BADS!" and "SKREKKING MEATS"

**Comment by Carthusia** [comment]
another suggestion "SKREK THE SKREKKING SKREKKERS!!!"

**Comment by joniroq** [comment]
Added a couple more by Shadey's suggestions plus another of my own, now Vox have as many options as other species.

**Review by dearmochi — APPROVED** [review]

**Comment by Fox-McCloud** [comment]
👎

**Review by Kyep — APPROVED** [review]

**Comment by variableundefined** [comment]
Closing due to two maintainers objection. The code add a special exemption for Vox and the snowflakey code is not justified by the substance it add to the game.

**Pull request closed without merging**
