### PR TITLE
Engineering Drip

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Adds a dress shirt and dress skirt for both Engineering and Atmospherics
Changes the sprites of the Engineering and Atmospherics berets (no real reason, can be removed if unwanted)
Changes the sprite of the Chief Engineer's mantle to make the gradient less jarring
Adds backpack and satchel variants for atmospherics.
Adds bomber jackets for Engineering and Atmospherics
(Includes relevant species sprites for each clothing item)
(Also adds all items to lockers/vending machines where appropriate)

## Why It's Good For The Game
Once again, more variety for clothing

## Images of changes
Engineering and Atmospherics dress shirts
image

Engineering and Atmospherics dress skirts
image

Engineering and Atmospherics bomber jackets (with unzipped sprites)
image

Engineering and Atmospherics beret resprites
image

Atmospherics backpack and satchel (satchel item sprite made by atteria#4221 in discord)
image
(Now with improved backpack based on LightFire's comment)

CE mantle resprite
image

## Changelog
:cl:
add: Added 4 uniforms to engineering/atmos
add: Added 2 bomber jackets to engineering/atmos
add: Added satchel and backpack for atmos
tweak: Changes the sprites of the CE mantle and engineering/atmos berets.
/:cl:

### CODE REVIEW

**Comment by atteria** [comment]
Really like the beret and CE mantle changes. Thank god that horrible gradient will be gone.

The dress shirt/skirts still seem very questionable to me.

**Comment by SteelSlayer** [comment]
You might consider changing the default atmos tech equipment so that they spawn with your new backpack and satchel sprite. To do that, you'd need to modify these lines and change them to that of your new backpack/satchel.

Code_vKEgqn8rF4

**Comment by LightFire53** [comment]
The backpack having a different shade of yellow significantly is a little off-putting, to be honest. I think that I should be closer in line to the colouring of the satchel

**Comment by Christasmurf** [comment]
> The backpack having a different shade of yellow significantly is a little off-putting, to be honest. I think that I should be closer in line to the colouring of the satchel

I'll try to sort this tomorrow (or later today at this point)

> The dress shirt/skirts still seem very questionable to me.

I'll try out some other ideas after I sort the backpack

> You might consider changing the default atmos tech equipment so that they spawn with your new backpack and satchel sprite. To do that, you'd need to modify these lines and change them to that of your new backpack/satchel.

Just committed, thank you

**Comment by SteelSlayer** [comment]
Your most recent merge commit added a bunch of unrelated code changes. You're going to need to fix that.

**Comment by Christasmurf** [comment]
Right so apparently the last commit added a bunch of unrelated shit? Unsure what that's about but either way I've made a total of 0 progress on this since I last commented to I'm just going to close this for now

**Pull request closed without merging**
