### PR TITLE
Revenant update, event weight tweaks

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Buffs revenants per this PR on /tg/: https://github.com/tgstation/-tg-station/pull/11187.
2) Moves revenants to a moderate event, making them much less likely to spawn.
3) Xeno suits/helmets can now spawn in mining treasure caves, making facehuggers much less likely.
4) Moves the xeno event to a major event, making them considerable less likely to spawn.
5) Adds follow links and logging to telepathic messages/alien, slaughter demon and revenant whispers, and ghosts can now see cultist messages.
6) Fixes https://github.com/ParadiseSS13/Paradise/issues/1779, missing SMES light.

Fixes https://github.com/ParadiseSS13/Paradise/issues/1702, https://github.com/ParadiseSS13/Paradise/issues/1747.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
You beat me to it, it would seem.

:+1:

**Comment by Krausus** [comment]
> ghosts can now see cultist messages.

Huh, I wondered why seeing cultist messages wasn't a thing, and just assumed it made it too easy to talk to ghosts without having to risk spending time ghosted. Probably not a big enough difference to matter, though.

Speaking of ghosts seeing messages, do you know if the direct messages from aliens, revenants, and slaughter demons show up for ghosts like telepathic messages do?

**Comment by Markolie** [comment]
I know aliens do - they use their own hivemind Xenomorph language, and these are handled through broadcast() which always notifies ghosts. I don't think slaughter demon/revenant messages show up though - they use custom procs to send direct messages.

**Comment by Krausus** [comment]
I'm referring to aliens' Whisper ability, actually... which, no, does not notify ghosts. Hm.

**Comment by Ultimate-Chimera** [comment]
:-1: for xeno suits spawning in treasure

**Comment by Markolie** [comment]
Xeno suits are already available in the little Xeno station on the asteroid, so they're not exclusive as they are right now.

**Comment by Ultimate-Chimera** [comment]
True, but since you gave the secret off completely right there could you actually remove it from there now?

**Comment by Markolie** [comment]
Ehm... We're an open source codebase. Nothing's secret.

**Comment by Ultimate-Chimera** [comment]
It kind of is a secret though, who knows about it really? Not many people, if you think about it... Nobody really knows about that station at all.

**Comment by Ultimate-Chimera** [comment]
Maybe make the xenohide spawn instead of the full xenos suit..? And make it spawn in random treasure places.

**Comment by Markolie** [comment]
Well, mind you that the xeno suit spawn is *only* in Xeno treasure caves, because right now it's a facehugger 100% of the time, and most miners can't resist getting infected. It's still very rare, and you'll only get either the suit or the helmet. 

DNM for now until https://github.com/tgstation/-tg-station/pull/11258 is done.

**Comment by Ultimate-Chimera** [comment]
Oh, so you will not get both at the same time?

**Comment by Markolie** [comment]
No, and it's still fairly rare. We just need some kind of an Xeno alternative to facehuggers spawning in the caves all the time. I'm more than open to replacing it with something else Xeno related (if you know of anything).

**Comment by Ultimate-Chimera** [comment]
Good idea though... Maybe make a piece of xeno hide spawn... Would make a bit more sense.

**Comment by Ultimate-Chimera** [comment]
Or... Toy huggers! Haha, scare them! :)

**Comment by Markolie** [comment]
I'll add xeno hide as well - that makes it even less likely for suits/heads to spawn.

**Comment by Ultimate-Chimera** [comment]
Okay. :)

**Pull request merged**
