### PR TITLE
Mineral Floors

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Added mineral floors and floor tiles from TG.
Use 1 sheet of any mineral in your hand to make 4 floor tiles. Floor tiles (metal and mineral) can be welded (need 4 in a stack) to create mineral sheets, except for plasma floor tiles which will just burst into flames. Plasma floors will catch fire if welded, uranium floors will irradiate on being hit or stepped on.
mineralfloors

:cl:
add: You can now create floor tiles from minerals. Be careful around plasma and uranium floors though.
/:cl:

### CODE REVIEW

**Comment by uraniummeltdown** [comment]
Nevermind I solved the issue, they were missing singular_name
I'll update the PR tomorrow
Apologies for the formatting changes in the same commit, I was working on this before I saw tiger request they be separated

**Comment by Fox-McCloud** [comment]
The `objects.dmi` file is hugely overbloated; you may want to move the floor tiles/sheets to their own `tiles.dmi` file, like TG did.

**Comment by SamHPurp** [comment]
This'll encourage people to decorate their snowflake work spaces rather than using it for science or anything.

**Comment by uraniummeltdown** [comment]
If Mining is on point Science and Robotics receive more than enough minerals, also the eastern part of the asteroid where there are hardly any minerals but no monsters could always be changed to be like the western part so that 1/3 of the asteroid isn't mostly rock with the occasional mineral once in a while

**Comment by Fox-McCloud** [comment]
Science usually has a *glut* of minerals---way more than they could ever use, unless they're hellbent on producing something like 5+ Durands.

**Comment by Fox-McCloud** [comment]
👌 @uraniummeltdown doing God's work.

**Pull request merged**
