### PR TITLE
Fixes for Modular Computers

### LINKED ISSUE #7347: Can't print forms
**Problem Description**:
Modular computers do print without using the [field], making it impossible to print forms with it.

**What did you expect to happen**: 
Able to write where [field] formatting was used.

**What happened instead**:
[field] formatting was ignored.

**Why is this bad/What are the consequences:**
You would need to copy-paste anything written on a computer by hand for the formatting to survive completely

**Steps to reproduce the problem**:
Make a form, be fast to print it as of  #7049, cry as you can't use your printed forms.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: [sign] also does get dropped, understandable that it does get ignored from the computer, though.

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Whole bunch of fixes to make modular computers less broken.

Fixes #7347, #7910 and #7049. Also, #7349 should be re-tested after this PR is merged. 

I also discovered a bunch of bugs myself and fixed them without raising issues.

:cl:AndrewMontagne
fix: Modular computers now print fields correctly.
fix: Files on modular computers no longer vanish shortly after editing.
add: Modular computers printers now make printing noises.
fix: You can no longer try and buy a tablet with a printer.
fix: Cloning a file now works.
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Ah, your changelog is not in the proper format!
Example:
:cl:AndrewMontagne
fix: Modular computers can now print paper fields again
/:cl:

**Comment by AndrewMontagne** [comment]
Amended the changelog. Missed a link when reading CONTRIBUTING.md.

**Comment by AndrewMontagne** [comment]
Fixed the issue with files vanishing, turns out it's a garbage collection issue. Single line fix. 💙

**Comment by AndrewMontagne** [comment]
Added fix to the laptop/tablet vendor where it would let you try and buy a tablet with a nanoprinter when a nanoprinter can't fit into a tablet. It'd still charge you for it, though.

**Comment by AndrewMontagne** [comment]
Added a fix for the clone file button. Now it **actually** clones files and prompts you for a filename.

**Pull request merged**
