### PR TITLE
Fixes Blob Zombies

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This is an alternative to: https://github.com/ParadiseSS13/Paradise/pull/964

Fixes:

- Blob zombies won't be able to convert corpses at a huge distance; they'll only be able to zombify corpses they're on top of or adjacent to.
- Blob spores/zombies will smoke "spores" into the air when killed.
 - Spores is not to be confused with "spore". Spores cause blurry vision and minor tox damage; it doesn't have a chance to make the person infected into a blob.

Other: 

- Blob zombies now randomly groan

Balance
- Factory nodes produce blob spores every 10 seconds as opposed to 15.

### CODE REVIEW

**Comment by fj45** [comment]
Everything looked good until "Factory nodes produce blob spores every 10 seconds as opposed to 15."

One of the big issues with spores/blob thingys is that they can be spammed to high hell, do a good deal of damage, take a bit to put down and move very rapidly. 

https://github.com/ParadiseSS13/Paradise/issues/826

**Comment by Fox-McCloud** [comment]
Given that they can't re-animate corpses 5-6 tiles away anymore--this is uh..kinda fair; especially since it effectively means the blob is going to have to spend even more resources to get zombified blobs up and going.

**Comment by Robertha89** [comment]
If the blob zombies have no spores, what is the point of the biohazard alert and law? It seems silly for the ai to try to stop an infection that can't spread. I

**Comment by fj45** [comment]
@Fox-McCloud 
No, considering how fast blob spores move...and how the player blob can all send them to one location with a click...and the fact that blob spores are already highly spammable and easily tear through anything.

@Robertha89 
Lore should not affect balance/gameplay.

**Comment by Bad-Apple797** [comment]
Blob Spores without a zombie are pretty weak, like one lasershot or something, as opposed to the ton it takes for a blob-zombie with sechardsuit + sec jumpsuit. I'd say this will probably make blob's still much weaker overall. Their main strength before is that in swarms, as soon as you killed a zombie, another spore would take up the body instantly.

I was thinking that maybe people "Infected" with spores could not necessarily be blobified, but still be tracked. Then if the blob dies really early/blob pays for a new blob core, the game/admins could choose from the infected players to be one, just to give more options for the mode. Tracking them for statistics for right now would be nice as well.

**Comment by ZomgPonies** [comment]
I like this idea of the infection being latent to limit the number of active blobs.

**Comment by Fox-McCloud** [comment]
@Robertha89 

The "spore" reagent was designed by UC_Guy, if I recall correct--and wasn't really intended for primary gameplay; it exists purely as an 'adminbus' tool, more or less. The reason there's an infection is because of the blob itself.

**Comment by Bad-Apple797** [comment]
It would be nice if we could track the infected for the AI objective, using them rather than crew simply because it kinda sucks for them to get red text 100% of the time.

**Comment by ZomgPonies** [comment]
Someone else can add infections and tracking mechanics. This is good for merge for now.

**Comment by tigercat2000** [comment]
@ZomgPonies I'm not sure this was really ready to merge- @fj45 brought up a valid point about blob spores being extremely spammable already, even without the zombies.

**Comment by fj45** [comment]
Agree, I don't see much reason to rush through PRs.

**Comment by ZomgPonies** [comment]
The difference is with the fixes to blob zombies, you can expect a lot less danger from their end e.g. you'll be able to drag corpses away. We'll see how this goes and adjust from there.

**Comment by fj45** [comment]
Factory nodes produce blob spores every 10 seconds as opposed to 15.

That was one of the big issues, and even without that I don't think this PR goes far enough to fix the issues with blob thingys.

**Comment by Fox-McCloud** [comment]
Regular blobs do next to no damage---the bigger problem with them was re-animating corpses who were literally 10 tiles away from the blob itself--once they were animated, their damage went WAYY up which made them much harder to deal with.

Now blobs will have to be on the same tile or adjacent to a corpse to re-animate them--and blobs will actually have to spend resources to rally their minions to the corpses in a lot of cases.

Also the chemicals that blobs spew everywhere when killed are significantly less harmful; no brain damage, no knockout, no confuses movement, etc; it's just ultra minor tox+blurry vision.

I think it's only fair that production is increased when you factor in these two major nerfs to the blobs.

**Comment by Spacemanspark** [comment]
/tg/ reagent blob when?
I'm kidding please don't.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Now that we have LINDA, that's a distinct possibility--I know Mark was planning on porting TG's blob, but he got busy.

**Comment by Robertha89** [comment]
I want to see a few round of this in action before, and if questions of rebalance is to be picked up, as the spores are only efficient early on when peole ain't suited up proper, thanks to spess being cold, Considering spores essentially killed you before, i see no reason for it to not be sarin, for instant kill for those who don't use internals. idk, the spore part of the blob is only relevant in the beginning.

**Comment by Spacemanspark** [comment]
Oh God.
That would be horrifying here.

**Pull request merged**
