### PR TITLE
Desolate's fluff name fix, no longer dancing fluff item

### PR DESCRIPTION
**Pull request by shazbot194**
~~This adds in Desolate's newest fluff item, which is a button to spawn in a dance machine. This does not add in any new icons, and instead uses the big red button to act as a spawner for the dance machine. Any questions about the fluff item should be directed to @DesolateG, and any code questions to me.~~

After talking this over with Desolate, this PR will just fix his name on his fluff items, and no longer adds in a new fluff item.

🆑 shazbot
Fix: Fixes up Desolate's name on his other items.
/🆑

### CODE REVIEW

**Comment by DesolateG** [comment]
@DarkPyrolord

**Comment by DesolateG** [comment]
Thank you shaz

**Comment by shazbot194** [comment]
My pleasure to help

**Comment by Aurorablade** [comment]
No. I am against this. Fluff items should not be used for the following: Admin spawnable items (this currently is), items that can be used in future content (dance machine can be used on a shuttle template if i recall), or items that have potional to be used in some player accessible form.

You pretty much just plagiarized an admin only/future use item for your own fluff.
Its not a sprite edit, its not something unique, its not a new sprite.
Its giving yourself access to admin/future use content.

Not cool in my opinion.

**Comment by DesolateG** [comment]
Considering that no one is saying " I made this", I'd appreciate if you keep that accusation out of this PR.

**Comment by Aurorablade** [comment]
I am saying its a port from TG, I am saying its probaly more then not going to be used on a shuttle template later.
Making it a fluff item prevents admins from spawning it in good conscious (i mean the disco ball) and admins spawning the disco ball devalues the fluff item.

**Comment by Spacemanspark** [comment]
Doesn't the dance machine cause people to sieze out and fly around?
That's a bit much for a fluff item.

**Comment by Birdtalon** [comment]
You need to fix your master branch. Every PR has leading merge commits.

**Comment by Spartan6** [comment]
100% against it. Could be used anywhere on any shift and completely breaks any immersion if used during those moments.

**Comment by KasparoVy** [comment]
Mucho problemas.

**Comment by Necaladun** [comment]
Way too much. Fluff items are meant to be a hat or something, not a button to summon a dance machine.

**Comment by Ty-Omaha** [comment]
https://nanotrasen.se/forum/topic/9058-fluff-items/

>Regarding fluff items, they should be primarily wearable attire that has no direct impact on gameplay.


- A dance machine would have a direct impact on gameplay

- The dance machine is limited to 4 songs unless we VV and add in more, which I assume would be a common request

- The dance machine can and **will** get quite old if overused

**Comment by taukausanake** [comment]
This might be okay if you make a subtype of the dance machine if it makes only you dance to it rather than everyone. I think that would be neat. The ability to break dance at any time you want.

Or if only for bartender have it spawn a dance machine that doesn't make anyone dance but rather just create the atmosphere for such. Maybe that was the desire from the beginning. Still need a subtype for it

**Comment by Fox-McCloud** [comment]
Yeah, this is beyond crazy for a fluff item.

The Dance machine is something that's meant to be admin only or related to the Disco Inferno shuttle (not implemented yet, albeit). This impacts the round in a rather dramatic way and is going to make something otherwise meant to be special and limited...something seen nearly every few rounds.

**Comment by tigercat2000** [comment]
:+1: as grammar fix

**Pull request merged**
