### PR TITLE
Strange objects resprite

### PR DESCRIPTION
**Pull request by Us3rn4me228**
## What Does This PR Do
this PR changes most of the relics sprites (except electropack one)

## Why It's Good For The Game
The old relics sprites are badly outdated, so I decided to redo them to match the current visual style of the build

## Images of changes
image

## Testing
PR successfully tested, no errors detected

## Changelog
:cl: Username228
tweak: Changed the relics sprites
/:cl:

### CODE REVIEW

**Comment by Us3rn4me228** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 


I've already registered on the forum.

**Comment by Us3rn4me228** [comment]
Please remove "On Hold" label

**Comment by Fordoxia** [comment]
> Please remove "On Hold" label

Don't worry, the label doesn't actually do anything.

**Review by Fordoxia — CHANGES_REQUESTED** [review]
Sprite update is blessed, god knows we've needed to update them for a while.

That said, should probably use duct tape instead of scotch tape for sticking everything together (both to make them look less flimsy, and because we actually have lots of duct tape lying around on station - and no scotch tape).

**Comment by Contrabang** [comment]
i like the scotch tape, allows you to actually see the components

**Comment by SteelSlayer** [comment]
Author has linked their account.

**Comment by EmeraldCandy** [comment]
> i like the scotch tape, allows you to actually see the components

I think the scotch tape gives a hilariously flimsy look, and just looks good in general. 👍 from me

**Comment by Scribble-Sheep** [comment]
I like the idea of them being taped together, but I agree with crunch that duct tape would make more sense thematically, and on top of that, the like, scotch tape is kind of bright on the sprite itself. Gray tape would be less so.

**Comment by DGamerL** [comment]
image

Is this IconDiffBot fucking up and is the sprite correct in the code?

**Review by Sirryan2002 — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
