### PR TITLE
Adds Five new IPC accessories. 

### PR DESCRIPTION
**Pull request by TravellingMerchant**
# **New from Shellguard Munitions Manufacturing **

Adds Five new IPC accessories. 

Pictured below with the bog standard IPC frame.

Here are a few pictures of it with other brands and in game.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
I spy Cyberman handles in there...

image

YOU WILL BE UPGRADED.

**Comment by KasparoVy** [comment]
Looks really nice.

**Comment by granodd** [comment]
Neat. Always like me some more robit accessories.

**Comment by taukausanake** [comment]
Just tossing this out there. Wouldn't it be a little easier if you had different specie icons in different files? I tried it myself a while back messing around with things but I forget how I got it to work. I do know I made a mess of it though

**Comment by TravellingMerchant** [comment]
@taukausanake It would be a lot easier, but don't ask me how it would work.

**Comment by taukausanake** [comment]
I think I'll mess with it then if no one else says they have free time and/or wants to do. Quoting  @Crazylemon64: "WHAT COULD POSSIBLY GO WRONG?"

**Comment by TravellingMerchant** [comment]
Sooo any news about this?

**Comment by Fox-McCloud** [comment]
conflictssss

**Comment by TravellingMerchant** [comment]
Yup, conflicts cause of the other PR. Let me fix it.

**Comment by TravellingMerchant** [comment]
Or.. maybe that didn't fix it..?

**Comment by Fox-McCloud** [comment]
still conflicts.

**Comment by Crazylemon64** [comment]
welp you're using master so I can't help you

**Pull request closed without merging**
