### PR TITLE
Add alarm sound to display case

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds an alarm sound to the display case which plays three times when it's broken.

Alarm is in the public domain. The implementation isn't too pretty (due to the sleep set to the length of the clip) but I couldn't find any procs that let me play sounds after the previous one finished.

Sound can be listened to here: https://raw.githubusercontent.com/Markolie/Paradise/ca05be75362a1e20a4ee290878b72369ff6f1783/sound/machines/burglar_alarm.ogg.
From: http://www.freesfx.co.uk

### CODE REVIEW

**Comment by tigercat2000** [comment]
What's the original source of the alarm sound anyhow?

**Comment by Markolie** [comment]
The prestigious website "freeSFX": http://www.freesfx.co.uk/sfx/burglar%20alarm.

**Comment by tigercat2000** [comment]
_[whistles casually](http://www.freesfx.co.uk/info/eula/)_

**Comment by Markolie** [comment]
I just credited it in this PR.

**Comment by tigercat2000** [comment]
Would probably be best to credit it in a comment, see [a](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/hydroponics/trays/tray_tools.dm#L361) [couple of](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/newchem/pyro.dm#L154) [examples.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/emote.dm#L117)

**Comment by Markolie** [comment]
The odds of them actually owning the rights to this sound are next to nothing. There's plenty of other places I can retrieve it from, such as https://www.youtube.com/watch?v=hFIJaB6kVzk. It was uploaded by a random user to that random website, who have these random terms of use that vaguely say that "you can credit them however you want", which I just did.

**Comment by tigercat2000** [comment]
It is generally better to err on the side of caution but [insert a damn whatever face here since I can never find a github emote appropriate]

**Pull request merged**
