### PR TITLE
Buffs duffs

### PR DESCRIPTION
**Pull request by taukausanake**
Creates a new duffel bag for Atmospherics. It is a resprite of the Engineering bag with light blue lines on it and a dark blue strap.
Also adds colored strips to each of the Medical duffels apart from Medical duff itself (Chem, Gene, Viro) as well as to Toxins as they all seemed a little lacking in their special color. Can undo if desired as they are different from before but the same between all sprite types.
Also edited Vox sprites.

In-hand and on-mob sprites have been updated accordingly. Atmos duffel bag spawns in Atmospherics "technician's locker". There was also a missing toxins duffel bag icon for both in-hand DMIs while each other bag had one so I made those too.

Fixed captain's duffel bag lefthand west sprite. Looked like security bag for some reason

PICS:
image

:cl: 
add: Adds an Atmospherics duffel bag that is yellow and blue
tweak: Adds sub-department colors to medical duffel bags and purple to Science duffel bags
fix: Captain's lefthand west sprite corrected
/:cl:

DID I FUCK UP ANYTHING?

### CODE REVIEW

**Comment by MarcellusPye** [comment]
Pics please

**Comment by taukausanake** [comment]
@MarcellusPye I had the snip ready but forgot to paste it when I made the PR. Fuck

**Comment by MarcellusPye** [comment]
Woot, more Atmosian pride! Special atmos bags and satchels would be nice for continuity but they can be added later.

**Comment by taukausanake** [comment]
Satchels were tough as I tried spriting some but couldn't get the colors to play well. Same for the bags at least when trying to match them up to engineering packs. Disappointed me but as you said, future PR

**Comment by FlattestGuitar** [comment]
Duffel bag powercreep.

Who will bother using leather satchels when everyone knows stripes make things go faster?

:-1: x :100:

**Comment by MarcellusPye** [comment]
A note, you should change the atmos tech loadout so people will spawn with these if they have department duffel selected.

**Comment by taukausanake** [comment]
@MarcellusPye Oh yeah, good catch I would have missed it completely. Doing that now

**Comment by MarcellusPye** [comment]
Only reason I caught it is because they didn't even get engineering bags until recently.

**Comment by Fox-McCloud** [comment]
conflicts.

**Comment by taukausanake** [comment]
WHO THE FU- give me a sec, I was out all weekend and tired

**Comment by taukausanake** [comment]
Here's to hope I didn't break anything

**Pull request merged**
