### PR TITLE
Pineapple Salad Fluff Item:Bluespace bunny ears

### PR DESCRIPTION
**Pull request by Aurorablade**
CKEY is PineappleSalad
Character: Dan Jello
Name and desc from user: "Bluespace rabbit ears", and the description is "A pair of sparkly bluespace rabbit ears, with a small tag on them that reads,"Dan Jello~". Yuck, there's some pink slime on the part that goes on your head!""

Relvent Screensho

:cl:
add: Pineapplesalad fluff item
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
These fluff items really are getting far out.
The lightning effect, although being what seems to be the whole premise of this fluff item, seems quite much

**Comment by variableundefined** [comment]
While I do not technically have a say in this...

Please limit the bluespace sparkles to the ears only. Putting it on the entire body is way too over the board and could be mistaken for genetic effects.

**Comment by Ty-Omaha** [comment]
Yeah...the ears themselves don't have any of the effects but the person does.

**Comment by Ralta** [comment]
> Yeah...the ears themselves don't have any of the effects but the person does.

It's also really overstated, imo. I just...don't really like it. At all. I get that's it's fluff, but still...

**Comment by Aurorablade** [comment]
I did not make the sprite. You are gonna have to take that up with the sprite author, Which is PineappleSalad. I personally do not see the harm in them.

**Comment by Denthamos** [comment]
Yeah, this is way too much for a fluff item.

**Comment by FreeStylaLT** [comment]
Yeah, the glowing electric effect is far too much for a fluff item -- if you want the ears to have a more toned down and subtle effect, that's fine, but a cueball effect like this is going too far, unfortunately.

**Comment by Aurorablade** [comment]
Commit incoming, the sprite now consists of whiskers.

**Comment by variableundefined** [comment]
I'm ok with the new change

**Pull request merged**
