### PR TITLE
Normal tomatoes can now be sliced. Tomato Meat now functions as meat.

### PR DESCRIPTION
**Pull request by Mitchs98**
## What Does This PR Do
Allows chefs(or anyone) to slice normal tomatoes for tomato slices. Tomato Meat from Killer Tomatoes now functions as meat in any meat based recipe.

## Why It's Good For The Game
More variety for food is good. Up until I butchered a Killer Tomato earlier I forgot we even had tomato slices in-game. They should be possible to find without risking a trip to medbay farming Killer Tomatoes. Botanists or a daring chef may now instead farm Killer Tomatoes for a source of renewable meat.

## Images of changes

dreamseeker_TIR13pxkFy

## Testing
1. Compiled it.
2. Ran server.
3. Sliced a tomato.
4. Butchered a Killer Tomato
5. Made a steak.

## Changelog
:cl:
tweak: Tomatoes can now be sliced for 4 slices each. Perfect for a sandwich!
tweak: Tomato Meat from Killer Tomatoes now functions as meat for any recipes that call for meat.
imageadd: Tomato Slice sprite added. Tomato Meat sprite tweaked to look more meaty.
/:cl:

### CODE REVIEW

**Review by Contrabang — APPROVED** [review]
LGTM

**Comment by ATP-Engineer** [comment]
probably needs a smaller sprite to differentiate killer tomato slices and normal slices but both serve the same purpose

**Comment by Mitchs98** [comment]
> probably needs a smaller sprite to differentiate killer tomato slices and normal slices but both serve the same purpose

Yeah it's the same sprite, same type-path and all. I just straight up used the killer tomato path for this. Qwerty mentioned it late last night, I'll see what I can do. May be able to slap it into my sprite editor and resize it. Also intend on modifying it overall, because the current typing has a lot of protein in it and ideally tomato slices would only have plant matter. I'll get to it later today or tomorrow, not a hard change just feel bleh atm.

**Comment by Mitchs98** [comment]
Sprites updated with better sprites than original attempt. Tomato Meat is now properly pathed as meat, rather than its own thing, and as such function fully as meat. Tomato slices now also have plant matter in them rather than protein.

**Review by Burzah — APPROVED** [review]

**Comment by spacegeese** [comment]
is this technically vegan?

**Comment by Mitchs98** [comment]
> is this technically vegan?

Technically maybe! It doesn't have any traits like that though :p

**Review by S34NW — APPROVED** [review]

**Pull request merged**
