### PR TITLE
Ports action button refactor from /tg/

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Ports changes implemented in https://github.com/tgstation/tgstation/pull/65180.
See the PR for details on the changes and the rationale behind them, I pretty much brought this over wholesale, save for the preference saving for positions. I didn't really want to futz with that, at least not yet.

The big changes:
image

- Meet the action palette, your new best friend.
  - Hover over the palette (the button that looks like [....]) to see the options.
  - Instead of having the binary choice of either seeing all of your actions or none of them, you can now hide some actions inside the palette.
  - You can click the palette to un-hide those hidden buttons, or just click anywhere else, and it'll hide them again.
  - You can drag buttons into them and out of them. It's pretty nice. Cheers, lemons.
- Action button code is a lot nicer
  - If you're not a coder, you probably won't care about this, but...
  - action buttons are now created dynamically per hud (read: per user seeing them).
  - this doesn't do much yet, but will be very useful down the line (wink, wink)

I really didn't want to do this originally, but https://github.com/ParadiseSS13/Paradise/pull/24382 drove me crazy enough that I figured I had to.

## Why It's Good For The Game
This should make action button usage a LOT easier, and helps with things down the line. 
It's some QoL that's not that hard to implement, and vastly overdue.

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/89928798/7d47fe0b-5b13-48b6-95fa-482b9a2fbc0d

## Testing
Also pending! See video, however.

## Changelog
:cl:
add: Meet the action palette! Hover over the bar in the top left with your mouse to see options, and try dragging action buttons around.
tweak: Dragging buttons around is much cleaner, and provides a lot more feedback.
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
To avoid crowding out the PR, here's more or less how it looks with a bunch of buttons. Note the up/down arrow icons are supposed to be next to each other, I just need to replace them with non-placeholders
image

**Comment by McRamon** [comment]
Add 2 pixel gaps vetween rows
Also i think ill do a bit different icons for this

**Comment by lewcc** [comment]
https://github.com/ParadiseSS13/Paradise/assets/89928798/48b0652f-fdb2-4232-927c-a521b62850ae

Added mouse-wheel support.
At this point, I think it's probably ready for review and TM.

**Comment by HMBGERDO** [comment]
image
enabling tank makes something funny

**Comment by Coolrune206** [comment]
The Action Pallette is a large lad. Any option to disable its visibility?

**Comment by Danchi299** [comment]
was this reported yet?
image

**Comment by 1080pCat** [comment]
image
oopsie doopsie, you've replaced the `stop pulling` icon with the page up button

**Comment by lewcc** [comment]
> The Action Pallette is a large lad. Any option to disable its visibility?

I mean, maybe? It's kind of large by design, so you have a target to hit and some information on how to hit it/hide/show buttons. I can probably do that, but you'd probably have to lose that ability? I can mull it over



> image enabling tank makes something funny disabling it fixes icon

Should be fixed in https://github.com/ParadiseSS13/Paradise/pull/24482/commits/59c3cc186a9bbec2f29e745550f51fb2d48457e0



> image oopsie doopsie, you've replaced the `stop pulling` icon with the page up button

likewise, should be fixed

**Comment by SteelSlayer** [comment]
This is being taken of TM for now so the server/other TMs can be updated.

**Comment by CinnamonSnowball** [comment]
Shift+Clicking action buttons to reset their position seems to also trigger them, which is a bit unfortunate

**Comment by lewcc** [comment]
> Shift+Clicking action buttons to reset their position seems to also trigger them, which is a bit unfortunate

oh, yeah. that's a bug on my end. sorry! Should be fixed in the next TM update.

**Review by S34NW — APPROVED** [review]
This has been issue-free on TM for a little while now, quick scan of the code and nothing looks out of place.

**Pull request merged**
