### PR TITLE
Removes the privacy shutters from R&D and Robotics

### PR DESCRIPTION
**Pull request by Lady-Luck**
Given the extreme power of Science, allowing them to work entirely in private is just too much. They're disconnected enough from the station as-is. This suggestion got a very positive response in Discord, even among the admins.

Also, because this greytide thing came up in the comments below, I'm gonna state my opinion here: Science doesn't need 'Immunity to Greytide' buttons. Call Security like you're supposed to.

### CODE REVIEW

**Comment by Earthdivine** [comment]
Pictures!

Though this leaves the shutters in front of the regular science entrances, right?

**Comment by Lady-Luck** [comment]
There's no picture to show, other than the button  not being there anymore. The shutters aren't visible in the map editor, I just right clicked, went to shutters, and removed.

>Though this leaves the shutters in front of the regular science entrances, right?

Eh?

**Comment by Deanthelis** [comment]
The shutters aren't there to keep people from seeing what Science is doing. The vast majority of Science isn't visible from the shutters anyway - and it's those unseen places that have the power, i.e. Chemistry and all the nice open spots to build Telescience or whatever you like.

The shutters are there to keep Shitlord McBaldy #22293 from breaking in through the front window and grabbing whatever he can stuff in his pants before disposaling himself.,

**Comment by taukausanake** [comment]
I kind of like having the shutters but it is annoying when someone needs their attention. I'd rather turn them into a lockdown feature like what Medbay has but I think it's fine as it is right now

**Comment by Lady-Luck** [comment]
Regardless of what they were meant for, that's not what they are being used for. If you're having issues with greytide, call security.

**Comment by Lady-Luck** [comment]
>I'd rather turn them into a lockdown feature like what Medbay has but I think it's fine as it is right now

There already is a lockdown feature. Biohazard shutters.

**Comment by Earthdivine** [comment]
@Lady-Luck Yea I was mistaking the Biohazard shutters for the other ones. Whoops.

**Comment by Ar3nn** [comment]
:-1:  x :100: from me. Without the shutters, its way too easy to greytide into science with little to no repercussions if security is its usual not paying attention to common radio, which is where 90% of the things they need to hear will be anyway (cries for help, crime reports by concerned citizens etc)

**Comment by Lady-Luck** [comment]
MedChem doesn't have shutters and they do just fine. Call Security.

**Comment by Iamgoofball** [comment]
@Lady-Luck you dont understand how this game works

**Comment by Lady-Luck** [comment]
This greytide thing is the biggest overexaggeration I've seen. Why should Science have 'Make Security unnecessary while also hiding everything I do' buttons.

**Comment by Iamgoofball** [comment]
Do you even play scienc3? Go play 20 rounds of high pop science, you'll find out quickly how this shit works.

**Comment by Lady-Luck** [comment]
I've played plenty of science and I only like to play on high-pop. Science doesn't need the luxury of immunity to greytide. Call Security like you're supposed to.

**Comment by Ar3nn** [comment]
Refer to previous comment. Actually read previous comment, especially in reference to Security /NO LONGER ANSWERING COMMON CHANNEL CALLS/

**Comment by Lady-Luck** [comment]
>Refer to previous comment. Actually read previous comment, especially in reference to Security /NO LONGER ANSWERING COMMON CHANNEL CALLS/

I read it.

**Comment by Dinarzad** [comment]
> Refer to previous comment. Actually read previous comment, especially in reference to Security /NO LONGER ANSWERING COMMON CHANNEL CALLS/

I have no opinion on this PR either way, but to be fair.
That's a problem with Security, and a player issue at that, not really a reason to deny the PR. If Sec is fucking off their job, then that's not on them.

That said, again, I don't really give a whit if the shutters stay or go.

**Comment by Fox-McCloud** [comment]
:-1: to this.

People almost never break into chemistry, even on high pop (for whatever reason), but they absolutely do try to break into R&D and do so quite frequently.

Breaking into science/robotics also doesn't just give access to that particular department, it gives them easy access to science proper---medical, due to the way its machines are set up, doesn't fall into this category.

**Comment by Lady-Luck** [comment]
What exactly is there to gain to breaking into R&D? An autolathe? You can't use the console without proper identification. Robotics is more vulnerable to this if anything, and I started the server as a pure Roboticist, almost no break-ins.

Here's an idea for when someone breaks in. CALL SECURITY. Greytide breaks in LOTS of places. There's no good reason to give Science a Greytide Immunity button.

**Comment by Spacemanspark** [comment]
@Fox-McCloud Half the shifts I play scientist in I end up tabling some civilian for making lube/ thermite and trying to get away with it.

**Comment by Lady-Luck** [comment]
I have a plan that will make everyone happy but it will require some work.

Grille Shutters

**Pull request closed without merging**
