### PR TITLE
Fluff item - Dar'Konr's camo bandana.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Adds a camo bandana for Dar'Konr.

   

Only head sprites here, because that's the only way sane people use those.

...to be fair Dar is the only one to ever use one anyway.

### CODE REVIEW

**Comment by sasanek12** [comment]
:banana:

**Comment by Ty-Omaha** [comment]
I wanted to see what his tacticool camo bandanna looked like but I guess I won't since there's no **_PICTURES_**!

**Comment by Alexshreds** [comment]
Add sprite pr without pics label plz plz plz

**Comment by Dumbdumn5** [comment]
:ear_of_rice:

**Comment by Fox-McCloud** [comment]
Dar is pink. This is now canon.

**Comment by KasparoVy** [comment]
Hey @FlattestGuitar, whipped up a Vox version just to maintain sprite parity. I'm pretty sure there won't be any code changes necessary, just a drag and drop of the mask.dmi in this zip to the icons/mob/species/vox folder and replacing the current icon file that's in there. Think you could put it in this PR?

_Camo Bandana Up - Vox Version_
voxcamobandanaupsmaller

_Camo Bandana Down  - Vox Version_
voxcamobandanadownsmaller

**Comment by FlattestGuitar** [comment]
Sas and I silently agreed birbs wouldn't get a sprite, because he was too lazy to make on more set. 

Guess there's no escape, eh? 

Don't merge until I add those, might take a while.

**Comment by sasanek12** [comment]
@KasparoVy  :heart: :heart: :heart:

**Comment by FlattestGuitar** [comment]
I'm gonna flay a Vox on the bridge on time just to prove a point

**Comment by FlattestGuitar** [comment]
In a galaxy far, far away there was a species that didn't have a custom sprite template.

But that galaxy collapsed and everyone died.

The end.

**Pull request merged**
