### PR TITLE
Adds Lumi's fluff vox suit

### PR DESCRIPTION
**Pull request by iantine**
Adds Lumi's fluff vox bodysuit.
Thanks to @shazbot194 for the help in making this work! I couldn't have done it without them.
Approved by Kyet.

**What**
The item is a fluff bodysuit for a vox, sits in the jumpsuit slot, and behaves as a regular pair of athletic shorts would (scarves, etc can be attached, it cannot be rolled down, can be removed as normal). It is animated.

gangelwaefre:voxbodysuit is the phrase needed in custom_sprites.

**Images**
preview

Update 26/March: Updated sprites to be less of an eyesore.

**Changelog:**
:cl:
add: Adds Lumi's vox suit fluff
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
I need the DEEP LORE- how does it make their body glow rainbow

**Comment by taukausanake** [comment]
> DEEP LORE

Bluespace. Always Bluespace

**Comment by Spacemanspark** [comment]
Reminds me of the psychadelic jumpsuit we once had, still sad we removed it all those years ago :^(

**Comment by MrMagolor** [comment]
> > DEEP LORE
> 
> Bluespace. Always Bluespace

NOT DEEP ENOUGH

**Comment by Kyep** [comment]
Confirming this was approved by me.

I would still prefer it to look more like a piece of clothing, and less like an effect.
Still, it is just a cosmetic effect. Plus it lets us make jokes about how the vox is radioactive.

**Comment by KasparoVy** [comment]
Slippery slope man, how far do we wanna go on these fluff items

**Comment by iantine** [comment]
Update; put significantly more work into the sprites. Apologies for master branching and other things I forgot in my haste to get this up.

**Comment by iantine** [comment]
Per that commit, just updated to be in line with the vox undergarments PR

**Comment by Fox-McCloud** [comment]
😱

**Comment by KasparoVy** [comment]
Blindness trait me STAT

**Pull request merged**
