### PR TITLE
R&D Research Levels Unification

### PR DESCRIPTION
**Pull request by jack-fractal**
This unifies the product and the design for all the research objects that I could find. About 92 of them. This should make R&D a little different.

No more or less powerful, just more consistent.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Can you provide a more complete description of what this actually does? Usage examples?

**Comment by jack-fractal** [comment]
Sure, this is pretty much just a bugfix. Or more accurately, a collection of bugfixes. 

Because of the way R&D is coded, you have Design datum objects used by the machines to produce objects. These design datums have specific tech level requirements for them to be built. Like, say, {materials 5, programming 1}.

They _should_ create an object with the same tech requirements ({mat 5, prog 1}), and _most_ of them do, but about 92 of them, the ones I modified here, don't. For example, they might make an object with {materials 5, programming 2} or {bluespace 1, programming 1} or something else entirely. 

I suspect most of these are artifacts of people just not keeping the object and the design object up-to-date with each other. I know this for _certain_ with the posibrains, and looking through things the rest look like the same thing. The whole system should be rewritten to store the information for the tech level in only one place, but that's outside of the scope of this bugfix.

There were also a lot of just straight up data entry bugs, things like missing semi-colons or commas in places, making them add or remove a requirement randomly.

The upshot of this is that R&D will be slightly more coherent then before.

**Comment by Fox-McCloud** [comment]
Just for reference, I have a PR up to revert this, but that doesnt' mean it won't necessarily be a denied PR; this just need to be viewed and look at by the community, especially some of our experienced R&D players (ie: @Markolie  being one of them, before it gets accepted.

**Comment by Fishocalypse** [comment]
While I might not be some professional RnD expert, the durand board only giving out combat research 2 would make it physically impossible to hit combat 5 without combat shotguns or advanced energy guns(both requiring you to at least run back and forth to security, not to mention the high chance of security shrugging you off)

Also, you can max materials research with just gold. Combine with a sheet of plasma for maxing RnD with plasma pistols and ai boards.

Antimov is also a huge boost to research, and there's quite literally no reason to have the antimov board when you could just get free syndi research too.

Now that I think about it I'm probably wrong in a lot of places, going to edit this out in the morning.

**Comment by Krausus** [comment]
I've spent a fair amount of time plotting out how to ~~powergame~~ efficiently finish R&D, so I guess I'd count as an experienced R&D player.

First off, I don't agree with calling this a bugfix. Picking whether the origin or requirement tech levels are "correct" for any given mismatch is often a matter of opinion, rather than a simple fix. Only changing one or the other would at least be consistent, but this changes many origin levels while also changing some of the requirement levels, and provides no explanation for why one was picked over the other. In most cases, this is probably fine, but there's some changes I'd like to know the reasoning behind.

Anyway, my observations:
* The origin tech on SMES boards is broken - `powerstorage` was changed to `power`, which is invalid.
* The origin/requirement mismatch on mech boards' combat level was a bit ridiculous, but why drop to 2 instead of raising to 4? They have hefty material requirements anyway. Also, the Phazon weapons board doesn't even require combat, which seems weird.
  * Just to note, it *is* still easy to get combat to 5 without cheesing it using weapons boards.
* Gold-based AI modules should probably be at materials 4 rather than 6, even though it's largely irrelevant considering you can hit materials 7 without any minerals anyway.
* Antimov's illegal tech level really doesn't make sense, considering it exists in the AI upload.
* The origin/requirement mismatch on artificial bluespace crystals and posibrains is most likely intentional. They require diamond, and so should require diamond-level materials research, but having good origin levels would just encourage scientists to destroy important things that aren't easily replaced.
* Super-capacity cells require the same power storage level that hyper-capacity cells do. Their requirement level was explicitly increased, rather than lowering their origin level. Why?
* The shield generator **machines** have origin levels. I'm pretty sure you can't stuff those things into the analyzer.
* I'm not sure GPS units are really intended to provide bluespace 3, since R&D will just gobble up the GPSes that Telescience starts with, but getting past bluespace 3 is enough of a nuisance that I'm totally okay with this.

**Comment by Earthdivine** [comment]
I'm all for this, a lot of times some things didn't make sense when it comes to RnD and Tech Levels, plus it would be a little nice to have Science actually leave it's station to get some of it's research levels again.

**Comment by Fishocalypse** [comment]
@Krausus For bluespace tech you can use a tracking beacon, relay mainframe, teleporter board from telesci, make two teleboards and deconstruct one, and a telehub though, bluespace is one of the most isolated and easier research levels to get up

@Earthdivine Forcing science to interact with other departments might sound like a good idea in theory, but in practice it will lead to science being ignored/threatened depending on the roundtype
(good luck getting a plasma pistol lockbox opened on a rev/nuclear emergency), not to mention the huge rising number of shitty members of command that ignore lockbox opening requests, and even on upgrading medbay/security/engineering I frequently get ignored unless I actively harrass members of said department.

**Comment by Krausus** [comment]
> For bluespace tech you can use a tracking beacon, relay mainframe, **teleporter board from telesci**

I know. I said it was a nuisance, and this is why. You have to temporarily cripple another wing of science, which is fine if nobody is using it. If someone is, odds are good they'll be less than thrilled. Have you ever had to explain to security why you're "stealing" from your own department?

> it would be a little nice to have Science actually leave it's station to get some of it's research levels again.

As far as I'm aware, this PR won't actually change this. They'll still only need outside help for opening a single Plasma Pistol, and Fishocalypse pretty much summarized the problem with that. Getting a single lockbox opened really is that bad.

**Comment by jack-fractal** [comment]
I picked the design option for the tech levels (unless it was specifically called out like the artificial bluespace crystals), because I was under the impression that R&D scientists usually dealt with the design levels and not the object levels. I wanted to have as little effect on the existing gameplay as possible. 

I posted about this on the forum and it's had zero responses in over 24 hours. I don't think anyone really cares about this all that much.

In addition, it should be stated again, most of the objects in the R&D ecosystem DO match, these were the exceptions.

I'm open to any changes, I really don't have significant opinions about any of this, other then I don't want to spend much time on this. My goal was consistency of code, not balance.

I am uninterested in doing a full R&D tech level overhaul. I just wanted to fix something that I saw was broken.

It IS a bugfix, because the bug was 'the levels between the design and the object are different' was the bug. Not 'the levels are arbitrary and silly', which is a statement I agree with. Revising the tech level requirements for almost 100 items, most of which changed by maybe one or two points, is WAY beyond the scope of what I wanted to get into.

@Krausus
RE: SMES - Thank you for pointing out the SMES thing. Typos!

RE: Mecha Targeting Boards - Changed this to your suggestions. They're bloody awful to work with because they don't use full paths.

RE: Gold boards - Changed this to your suggestions.

RE: Antimov - I agree, it doesn't make much sense, but that's what it's design was. I suspect that the syndicate level was thrown in there to stop arse-buckets from making the AI go crazy after a little research. I'm guessing this won't be a huge problem in practice. Regular scientists usually don't have access to the AI upload. If they do nab the Antimov board, it's still illegal for them to have it. Self-antagging etc.

RE: Cells - Yeah, not sure what happened there. Fixed that.

RE: The Shield Generators - OK, these were completely fucked. The reason they were fucked is that they would _never_ have worked. Their design/datum built the _machinery_ path, not the _circuit_ path. I've no idea what would happen if you tried to print one out from the circuit printer. I imagine _shenanigans_. 

I was mostly on autopilot while doing the standardization, so I added the origin_tech to the thing that they built, which was itself wrong. I've fixed this. Hurray. I guess we can make new shield generators now!

@Earthdivine
I agree, getting science to interact more rather then just running a cookbook would be nice, but they can still do it with practically everything with this changelist, and the way R&D works now, they're pretty much always just begging. That's never a fun position to be in, and as Krausus and Fish pointed out, people are jerks about this.

@Fishocalypse
Yeah, I've never really been in that position yet (I usually play Geneticist when I'm in there, and I'm only interested in getting my cloner upgraded and getting out) but I can imagine that getting the Head of Sec to give you a gun would be a challenge. I have a hard enough time getting them to answer things like "What do I do with this murderer?" which is, nominally, their job. 

New pull request is here: https://github.com/ParadiseSS13/Paradise/pull/755

**Pull request merged**
