### PR TITLE
Enable MMI/posibrain speakers by default.

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do

This PR enables the speaker for MMIs/IPCs by default.

## Why It's Good For The Game

Posibrains are fairly indestructible and survive dismemberment of the host chassis, leaving the player alive but—by default—unable to speak or do anything. By enabling the speaker by default, free posibrains can alert other players to their plight and hopefully get them back into a chassis quicker.

## Changelog
:cl:
tweak: MMIs and posibrains now have their speakers enabled by default.
/:cl:

### CODE REVIEW

**Review by AffectedArc07 — APPROVED** [review]
I stand by my words

**Comment by warriorstar-orion** [comment]
Tested this with speaking and comms of a live IPC, a dead IPC still in its chassis and an IPC dismembered by a blood-drunk. There didn't appear to be any issues with crosstalk or duplication of messages with the live IPC. The dead IPC was unable to speak, but the dismembered IPC was, which I believe is the desired behavior.

**Review by dearmochi — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Comment by Fox-McCloud** [comment]
I'd much rather create a system that allows for positronic brains to ghost, under certain conditions.

Human brains can't speak or get peoples' attention when they're on the ground for hours or covered under clothing/viscera---why should IPCs be any different?

**Comment by warriorstar-orion** [comment]
What would happen if someone turned the posibrain's speaker on while the player was ghosted? Would they get a notification similar to a soul being called back to a cloned body?

**Comment by Necaladun** [comment]
Debraining people should silence them, unless you want them to talk. Objecting to this.

**Comment by warriorstar-orion** [comment]
Fair enough. Withdrawing.

**Pull request closed without merging**
