### PR TITLE
Asthetic changes to arrivals and science

### PR DESCRIPTION
**Pull request by orelbon**
Arrivals:
* Edits floor tiles by finishing the blue and white pattern
* Add some direction signs 

Medical:
* Adds warning stripes to locations that have blast doors 

Science:
* Edits floor tiles by removing black tiles and placing warning tiles.
* Adds more signs indicating danger/location 
* Moves the cargo drop off point in the maintenance tunnel under RD's office. 
* Edits space between science and xenobiology. 

capture2

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
before and after in the op please?

**Comment by orelbon** [comment]
https://dl.dropboxusercontent.com/s/82zf6gfnmo8qacx/cyberiad.dmm.0-27-9-15.png?dl=0

take a look at the same areas as above.

**Comment by Norgad** [comment]
That mulebot stopping area is a really good idea!

**Comment by Fox-McCloud** [comment]
`Edits floor tiles`

This is incredibly ambiguous. It's akin to making code changes and says "changes stuff in this file".

**Comment by orelbon** [comment]
There i made it more specific.

**Comment by Fox-McCloud** [comment]
Conflictssss

**Pull request closed without merging**
