### PR TITLE
Remove fart based mechanics

### PR DESCRIPTION
**Pull request by Allfd**
Based on a discussion over the last few weeks on the admin forums.

This PR removes fart based mechanics from the game other then those related to the bible.  You may still use the emote, you may still use the bible.  But no more super powers and the in game sound is gone.

:cl: Alffd
del: Removed fart based mechanics.
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
yes pls

**Comment by FalseIncarnate** [comment]
I have no issue with farting being played down significantly like this, but I would like to suggest just altering Rathen's Secret to be less fart-themed but still retain the overall effect of the ability (blowing limbs off targets without being destructive to their surroundings) instead of outright removing it.

Call it Sorium Blast or something, and let wizards keep their ability to blow the arms and legs off would-be hunters without blowing a hole in the floor.

**Comment by datlo** [comment]
Can't support this PR if you remove rathen's secret without any alternative to it, it's a useful spell (if underused) and I wouldn't want to see it gone.

**Comment by Mitchs98** [comment]
Rathen's doesn't delimb? It removes the appendix, breaks ribs, and causes brute. Though I agree I see no reason to remove Rathen's.

**Comment by datlo** [comment]
Rathen's delimbs if you've already removed the appendix (% chance per limb).

**Comment by Mitchs98** [comment]
> Rathen's delimbs if you've already removed the appendix (% chance per limb).


Summons a powerful shockwave around you that knocks everyone down for a moment, forcing all victims to emit a small smoke cloud and defecate their appendix. If you've already taken the liberty to remove the victim of their appendix, they instead take 10 brute damage, with a possibility of breaking their ribs if they are already hurt. (Loud spell) <-- Not according to the wiki?

**Comment by Allfd** [comment]
Reworked Rathens, it is the same except without the sound and the language.

**Comment by KasparoVy** [comment]
Wow, RIP

**Comment by datlo** [comment]
with rathen's reworked i'm ok with this pr

**Comment by Birdtalon** [comment]
Super fart is hilarious. If you are going to remove it then please rework into something with the same effect.

**Comment by TDSSS** [comment]
Maybe a super scream, instead?

**Comment by Ty-Omaha** [comment]
Super burp

**Comment by KasparoVy** [comment]
Slippery slope mate, slippery slope

**Comment by Couls** [comment]
end of an era

**Comment by KasparoVy** [comment]
It's as if a thousand farts sounded out at once then were suddenly silenced

**Pull request merged**
