### PR TITLE
Cell Weight Class and Tech Fixup

### PR DESCRIPTION
**Pull request by Fox-McCloud**
- Fixes the origin tech on the mech plasma cutter
- Fixes origin tech on a few cells
- Adds in some missing origin tech on the camera bug and syndi magboots
- Reduces w_class of cells from 3 to 2

### CODE REVIEW

**Comment by orelbon** [comment]
So we can put cells in boxes now? :+1: x :100:

**Comment by Fox-McCloud** [comment]
@orelbon 

Yes.

**Comment by FalseIncarnate** [comment]
Reducing the w_class of cells is a HUGE :+1: from me. It never made sense that something that fits inside a stick or gun would be unable to fit inside a pocket. Plus, this means engineers and scientists can build new APCs, SMES units, and upgrade existing cells much faster, since they can carry the batteries easier.

**Comment by HereticChurch** [comment]
:+1: :100:

**Comment by tigercat2000** [comment]
>Reducing the w_class of cells is a HUGE :+1: from me. 

so like dis

**Comment by Crazylemon64** [comment]
Ah, yes, now I don't need to keep cells in my satchel when upgrading cyborg cells

:+1:

**Comment by orelbon** [comment]
marge pls

**Comment by Regen1** [comment]
Only reason for it being a higher weight class was for people to not have their box filled with "magazines" for their egun, back when you could switch the cell.

Huge :+1:  from me as well, since we no longer have that feature

**Comment by orelbon** [comment]
this is for all power cells right? Do potato batteries count as cells?

**Pull request merged**
