### PR TITLE
Resprites handheld defib, uglymines, and trauma/burn kits

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Resprites a few things in items.dmi, three of which being medical stuff.

## Why It's Good For The Game

Blends better with constant changes to other older sprites, the handheld now looking on the same level as the regular defib, trauma and burn kits kind of just look nothing like an actual medical kit, and landmines being ugly as hell.

## Images of changes

KITS
image
image

(REVISED KITS DUE TO FEEDBACK)
image
image

LANDMINES
image

HANDHELD DEFIB
image

## Testing

Works as intended.

## Changelog
:cl:
imageadd: Updates Landmine, Trauma/Burn kits, and Handheld defib sprites
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
Although personally I don't see why advanced kits need to look like medkits over simple packs of band-aid-like medicine, either way the burn kit should probably keep its old unique symbol - no reason to remove a detail that helps differentiate them

**Comment by Contrabang** [comment]
Yeah, I agree, the kits look more like some kind of flat storage container, and look a lot bulkier than they actually are.

Also can you please update your changelog to reflect what the PR is about?

**Comment by matttheficus** [comment]
Mirroring above, I dont like that the kits look like storage containers.

**Comment by ATP-Engineer** [comment]
Take into account, that the epi pens are larger than these. The size scale doesnt really add up well, even if they'd SOMEHOW be mistaken for storage medkits, they dont have the same shape/coloring, And most times than not, would be found INSIDE one.

So this update will make them look more like an actual first aid kit (seeing as its actually really useful when you arent spamming automenders), and stand out more when left abandoned outside of a storage medkit.

**Comment by TravisAngeI** [comment]
This comment isn't gonna help any and I don't mind if you brush past it, but I think the trauma/burn kits look fine as is.

They don't really make a big difference in differentiating between menders and kits, it's just that the sprite is bigger.

Sorry to bother, I suppose.

**Comment by Christasmurf** [comment]
> and landmines being ugly as hell.

bro they're literally called "uglymine" what did you expect smh
defib and mines are good, idk about the medkits

**Comment by McRamon** [comment]
Handheld is good, mine is fine.
Kits are not though, they look flat, tge details you tried to represent dont really represent themselves well and look like random squares. Colors are also not great either. 
You can either remove them from this pr, or contact me on discord so we make something nicer looking to replace them

**Comment by ATP-Engineer** [comment]
Revised sprites from feedback are listed above in PR description.

**Review by Henri215 — APPROVED** [review]
LGTM

**Comment by Screampuff** [comment]
As someone with colorblindness, it's *really* hard to tell the kits apart.  The contrast difference plus the change in symbols on the old one made it extremely apparent without staring at the name/examine text.

**Comment by matttheficus** [comment]
Brought up the colorblindness issue with the Dev Team, posting this for Denthamos as they don't have access to the tracker/git at the moment:

image

**Review by S34NW — CHANGES_REQUESTED** [review]
Not even a vote issue, this won't get merged without accessibility compliance as a technical issue.

**Comment by ATP-Engineer** [comment]
image

**Comment by ATP-Engineer** [comment]
> 

done

**Review by S34NW — APPROVED** [review]

**Pull request merged**
