### PR TITLE
Refactors and Documents Powernet, Wirenet, Engine, and Power Machinery Code

### PR DESCRIPTION
**Pull request by Sirryan2002**
## What Does This PR Do
Needs #19991 to be merged first as a prereq to this being pull out of draft
Refactors and thoroughly documents the following:

- `/datum/powernet` - converts it into `/datum/regional_powernet` and documents/improves code
- cable - bringing code up to date and improving code
- `/machinery/power` - moves some of its procs/code off of this type and offloads the heavy lifting onto powernets
- engines - engine code needs to be brought up to standards code-wise and should be better documented
- SSmachines way of handling powernets

Also finally kills `/obj/machinery/logic` you will not be missed

## Why It's Good For The Game
Higher quality documented code opens the doors (and makes it easier) for stuff like #19786 and #19734

## Testing
Compiled, ran on a test server

- Started Round
- APCs are charging properly
- Laid wires and cut wires
- Checked SMES to make sure they were charging and outputting power

No changelog as there are no player-facing changes

### CODE REVIEW

**Review by S34NW — COMMENTED** [review]
Any chance you can do some local testing before I get to reviewing this?

**Comment by Sirryan2002** [comment]
> Any chance you can do some local testing before I get to reviewing this?

Yeah, it compiles and runs fine on my test server without runtimes. Power is working how it should, I'm just waiting for my other PR to get merged so I can fully tie this into the APC refactor.

**Comment by Sirryan2002** [comment]
now that #19991 is merged, I'm gonna get this pull out of draft soon

**Comment by Sirryan2002** [comment]
update, Im gonna get started this week. Lots of stuff going on so I have been delayed

**Comment by Sirryan2002** [comment]
Closing this until I can back to working on it

**Pull request closed without merging**
