### PR TITLE
Plasmamen Softsuit Fixes

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Civilian/Assistant plasmaman softsuit fix
- Gave karma jobs non-generic softsuits
- Removed slowdown from eva suits -- Since ALL plasmamen tech has been geared towards developing these suits, they already have enough debuffs.
- Fixed suits not being removable
- Fixed people picking up suits from cryo and not being able to drop them
- Fixed armor values of suits (similar to equivalent hardsuits for the appropriate job).
- Fixed missing suits in suit.dmi

### CODE REVIEW

**Comment by TheDZD** [comment]
Might want to look at the armor values of certain suits and make them match up with their corresponding RIG suits, particularly the engineering ones. Slowdown values and pressure resistance may also be worth looking at, using the corresponding RIG suits as a baseline as well.

**Comment by ZomgPonies** [comment]
Yep doing that now, also looking at why suits/helmets can't be removed.

**Comment by Fox-McCloud** [comment]
Pressure_resistance ratings are useless here on Para; they're a value unique to VG.

**Comment by ZomgPonies** [comment]
Removed.

**Pull request merged**
