### PR TITLE
Ports TG reflector sprites

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Ports TGs newest reflector sprite

## Why It's Good For The Game
Rest in piss last fragment of the old walls

These sprites are visually better.

## Images of changes
image

## Testing
I ran it.

## Changelog
:cl: Bmon
imageadd: Ported reflector sprites from TGstation.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
The slight change of shade on the blue is throwing me a bit
image

Like I get that one is diamond and one is glass but it kinda looks off to me.

**Comment by Bm0n** [comment]
> The slight change of shade on the blue is throwing me a bit image
> 
> Like I get that one is diamond and one is glass but it kinda looks off to me.

This was the case with the old sprite too lmao. The inner part was always deep cyan blue

**Comment by AffectedArc07** [comment]
> > The slight change of shade on the blue is throwing me a bit image
> > Like I get that one is diamond and one is glass but it kinda looks off to me.
> 
> This was the case with the old sprite too lmao. The inner part was always deep cyan blue

I am a sane individual

**Comment by Sirryan2002** [comment]
Could you have those sprites touched up a little bit. The shadows on the base are quite sharp and could be dialed back a bit.

**Comment by Bm0n** [comment]
> Could you have those sprites touched up a little bit. The shadows on the base are quite sharp and could be dialed back a bit. This isn't an approval-blocking request btw :).

I'll see what I can do when I wake up tomorrow

**Comment by Bm0n** [comment]
> Could you have those sprites touched up a little bit. The shadows on the base are quite sharp and could be dialed back a bit. This isn't an approval-blocking request btw :).

Please let me know if you prefer these, if not we can keep the current sprites.

image

image

image

image

**Comment by Bm0n** [comment]
sorry i forgor, ill probably get to changing the sprites

**Comment by Bm0n** [comment]
I didn't forget! also cleaned up the reflector sprites, they were pretty badly skewed before

image

**Pull request merged**
