### PR TITLE
Adds in an importent piece of medical gear

### PR DESCRIPTION
**Pull request by Aurorablade**
this will change...EVERYTHING!

:cl: Fethas
rscadd: Adds medical gowns to medical wardrobes.
/:cl:

### CODE REVIEW

**Comment by HeadyBucket** [comment]
I like it, great view of the ayys butt

**Comment by FalseIncarnate** [comment]
Get a bike from the arcade and you too can recreate this scene in the halls!

image

**Comment by LightFire53** [comment]
Why not have a locker of these in cloning, so we get less naked clones when people have their clothes stolen

**Comment by Aurorablade** [comment]
I added it to the medical wardobe in cloining...

**Comment by granodd** [comment]
Honestly replace the pajamas in the closets near surgery with these

**Comment by Birdtalon** [comment]
I don't see any reason why not! These look good changes in the diversity of clothing is always appreciated.

**Comment by Ralta** [comment]
Awesome! Now to refuse surgery to anyone who doesn't strip and put one of these on :thumbsup:

**Comment by tigercat2000** [comment]
These are terrifying. I love them. 👍

**Comment by PhantasmicDream** [comment]
These will be a great asset to medbay.

**Comment by ZN23XZ** [comment]
I'm just imagining some traitor with a chainsaw hopped up on meth running around killing everyone wearing nothing but this and bunny slippers.

**Pull request merged**
