### PR TITLE
Ports over Airhorns

### PR DESCRIPTION
**Pull request by Fox-McCloud**
WHYYYY FOX WHYYYY

Ports over air horns from TG

You can make them if you manage to get your hands on bananium...and some low tech levels in R&D. 

They have a longer cooldown than bikehorns, but play your stereotypical air horn sound...of course.

Goodness help you all if the damn clown gets ahold of one.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
No extra functionality, except for leading people to believe there is a H.O.N.K. mech on the loose.
Why not. :+1:

**Comment by KasparoVy** [comment]
RIP ears :+1:

**Comment by TheDZD** [comment]
You are a terrible person.
:+1:

**Comment by Robertha89** [comment]
Add knock over EVERYONE if emagged. so you can build one, emag it, and give it to the clown.

**Comment by Keilden** [comment]
HONK squads should come with those

**Comment by Robertha89** [comment]
Alternativly, emagged ones have no cooldown.

**Pull request merged**
