### PR TITLE
Auto Nuclear War Declaration

### PR DESCRIPTION
**Pull request by Ty-Omaha**
## What Does This PR Do
Automatically declares war during nukeops if the population is big enough.

## Why It's Good For The Game
Stealthops is so unbelievably boring for everybody except the 5 nukies. They usually take an hour to get on to station, then get spotted right away anyways. Admins have their hands tied and can't add stuff, contrary to extended. The only time stealthops are successful is really during blitzops.

:cl:
balance: Nuclear Emergency will now automatically always declare war unless there is not enough people
/ :cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
Would this auto timer only trigger say, 3-5 minutes after round start to give the nukies time to gear up?

Basicly if its auto, rather than the "Declare war get points", if it auto war decs, you are given the points upfront and told why, and told you have "blank" time to plan, prepare and equip before the station is alerted due to the high population/security presence

**Comment by Ty-Omaha** [comment]
@Carthusia Nukies can choose to go to the station whenever they want and are ready. There is no need to give them time to gear up since they are the ones who decide when they go to the station.

**Comment by farie82** [comment]
Maybe have a delay on the declaration. I forsee a lot of instant cryos when this happens at round start

**Comment by Ty-Omaha** [comment]
>Maybe have a delay on the declaration. I forsee a lot of instant cryos when this happens at round start

Those same people will just go to cryo anyways even with a delay

**Comment by Carthusia** [comment]
Nono i dont mean force them to stay for 3-5 minutes, basicly since they dont get the choice to try to sneak aboard, they get their points up front, but the station isnt alerted to their presense for a couple of minutes to give them proper time to get their bearings.

The first minute or two of a nuke ops is pretty hectic for the team, even more so if they dont get that choice to hold off on a war dec for a minute or two to get things in order.

**Comment by Ty-Omaha** [comment]
>The first minute or two of a nuke ops is pretty hectic for the team, even more so if they dont get that choice to hold off on a war dec for a minute or two to get things in order.

@Carthusia I don't see the problem since they choose when they go to the station. 

The first few minutes of nukies is them discussing stealth/war if the leader doesn't instantly declare war

**Comment by Cazdon** [comment]
Tentatively for this. The interactivity for the mass majority of players during stealth ops is really low. Only problem I can see is how this might work during rounds with so much low-pop that war can't even trigger.

**Comment by Ty-Omaha** [comment]
>Tentatively for this. The interactivity for the mass majority of players during stealth ops is really low. Only problem I can see is how this might work during rounds with so much low-pop that war can't even trigger.

Then it will just be how it is now, which is stealth

**Comment by Cazdon** [comment]
Wait does this mean war ops can bypass the original time limit that prevents them from coming on the station before 20 minutes? Normally that's in place to give the crew prep time.

**Comment by AzuleUtama** [comment]
I don't see why we have to limit the antagonist's choices just because some stealth ops teams haven't done very well in the past. While I do agree that war is _generally_ preferable as it gives both the crew and the nuke ops team something to do for the round, it should be up to the nuke ops team as to how they want to approach the mission.

This would also kill any kind of Gimmick Ops rounds they want to play with, since everyone will know they're coming and just gun them down instantly.

**Comment by Ty-Omaha** [comment]
>Wait does this mean war ops can bypass the original time limit that prevents them from coming on the station before 20 minutes? Normally that's in place to give the crew prep time.

No

**Comment by Ty-Omaha** [comment]
>I don't see why we have to limit the antagonist's choices just because some stealth ops teams haven't done very well in the past. 

The majority of stealthops is the same failures with the crew doing nothing for an hour. Not "some"

**Comment by AffectedArc07** [comment]
So youre saying that stealth traitors are now boring in highpop? 
Are you saying that any antag that tries to stealth in highpop is "unbelievably boring"?

Theres a reason that the war declaration is on a choice device. Picture yourself as a first time nukeop player, stealth would probably be good for you to get your bearings. If youre a first-time player in highpop and you auto have war declared, your experience is going to be **extremely** shitty and will probably discoruage newcomers from playing the role.

The only thing I can see this PR doing is creating more administrative hell as the entire station descends into all-access anarchy because of the forced war-declaration.

**Comment by datlo** [comment]
If this were done, which I disagree with, the war declaration should be 2 to 5 minutes after the start of the round, at random, not at roundstart. Give sec and command the time to at least get dressed up ad basic gear out of their locker and vendors before alarms start blaring and the station falls to chaos.

Either way, I disagree with this change. If stealth ops are an issue because they get too long to get moving, an admin should be there to push them to move, same as when a wiz takes too long to move out. 

If they are too strong for sec staff and the clown to deal without an advance warning, the amount of free shit they get in the op base and the shuttle should get reduced, perhaps with extra TC compensation for war ops. The box of meth donks is probably the biggest offender here, as ops cant even buy those, and the closest equivalent, adrenal implant, is 8 tc. I wouldnt mind seeing the bulldogs and the PDA bomb cartridge go either (Why is that there?!). Perhaps reduce the bonus TC per crew that stealth ops get if necessary.

**Comment by MRgaty** [comment]
Again I really dont see why we should limit the options of the antags, why cant they make a vote like always, that way they can even choose to go blitz or use stealthy options, I really dont see why we should enforce WAR when the nuke team may not want to do that.
If Nuke ops is already a repetitive gamemode, limiting the ways to attack the station to just ONE will make it even MORE repetitive.

**Comment by Ty-Omaha** [comment]
>If Nuke ops is already a repetitive gamemode, 

Not repetitive, boring.

**Comment by Ty-Omaha** [comment]
>So youre saying that stealth traitors are now boring in highpop?
Are you saying that any antag that tries to stealth in highpop is "unbelievably boring"?

As the rules say, traitors should make an effort to _add_ to the round.

If they were undetected and nobody knew the results of their actions then yes, they would be unbelievably boring. At least for the rest of the crew.

**Comment by SplinterGP** [comment]
Undeclared nuke ops inst just stealth ops, there is very normal to see nuke ops just going totally boom even if not declared war, so they have less gear and so does crew, also auto declaring woulndt make you have a clown ops for example

**Comment by Fox-McCloud** [comment]
I vehemently opposed to this.

If we're going down the logic trail of "5 people stealthing to kill people is bad and boring and not good design", then you might as well half the game modes, as that exactly what they push for.

War is about having loads of resources but an uphill battle. 

Stealth ops is about precision and extreme cohesion for a battle that will probably spiral out of control if they don't plan things exceedingly well.

**Comment by variableundefined** [comment]
Closing as I also object, two objections.

**Comment by Ty-Omaha** [comment]
>Stealth ops is about precision and extreme cohesion for a battle that will probably spiral out of control if they don't plan things exceedingly well.

should use what happens in reality rather than theory when discussing this

they get spotted breaking into the airlocks

then they get lynched by the crew and security. there's hardly any real "battles" like in war ops

**Pull request closed without merging**
