### PR TITLE
AI Vox Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Came up after a discussion of on the coderchat over Vox voice sounds.

REQUIRES A CLEAN COMPILE TO TAKE ADVANTAGE OF!

Either case, here it is:

- Updates AI voice to actually be a female voice (like it says it is).
 - More consistent with the overall AI voice structure that we currently use
 - phrases are (IMO anyway) easier to understand and progress quicker, so they're not as disruptive to crew or admins (not as incredibly loud either).
 - Several of the more abusive/irritating long voxtest sound have been removed ( @Necaladun  will appreciate this, I'm sure)

Other
- Cleans up the old vox/redundant sound files.

### CODE REVIEW

**Comment by tigercat2000** [comment]
> Several of the more abusive/irritating long voxtest sound have been removed

list of what you removed, please?

**Comment by Fox-McCloud** [comment]
All the voxtests

**Comment by tigercat2000** [comment]
@Fox-McCloud Did the female voice actually have any of them? Because, like, if it did, I think you should keep them. test2 was discussed in the past and people claimed it had valid uses.

**Comment by Fox-McCloud** [comment]
It does not include them; had it included them, I would have included it as well.

**Comment by tigercat2000** [comment]
Alright, fair enough; Female voice best AI voice.

**Comment by Krausus** [comment]
It looks like this new voice has 94 fewer lines, 4ish of which would be the "test" lines. One of the words we'd lose is "changeling". Do you have a list of all the ones that would be lost?

**Comment by Fox-McCloud** [comment]
No, because I'm not going to spend multiple hours of my time cross comparing literally 1511 sound files.

**Comment by Krausus** [comment]
Fair enough. I've gone ahead and taken a moment to diff the files. The new voice uses "centcom" instead of "centcomm", has a new "vox_login" sound, and is missing the following:
* andy
* antimov
* atmospherics
* bar
* bizwarn
* bloop
* bomb
* bombs
* borer
* borers
* botanist
* botanists
* brain
* brains
* brawl
* brig
* buzwarn
* cage
* can
* cancer
* catbeast
* ce
* changeling
* changelings
* changer
* chef
* chefs
* chemist
* chemists
* clowns
* cmo
* comdom
* conflict
* court
* cunts
* dadeda
* dead
* death
* department
* departments
* desk
* doctors
* doop
* dorms
* engineer
* engineering
* engineers
* every
* execution
* hacking
* hop
* hos
* humans
* iaa
* kitchen
* lawyer
* lizard
* love
* mommi
* monkey
* monkeys
* ninja
* ninjas
* or
* qm
* quarters
* rage
* rd
* recommend
* request
* requested
* respond
* roboticist
* robotics
* rogue
* shirts
* shitcurity
* skipjack
* smoke
* stations
* suffering
* tajaran
* telecomms
* traitors
* vampire
* vampires
* vox_420
* voxtest2
* voxtest3
* wankers
* weed
* wiggle
* wizard
* wizards
* woop

**Comment by fj45** [comment]
The AI cannot malf if you disable its vulgarities!

Not sure why a minor voice change would be worth loosing so many words.

**Comment by tigercat2000** [comment]
Consider my opinion changed, I guess, That's... a lot to loose, actually.

**Comment by Spacemanspark** [comment]
I'd say yes if we weren't losing so many words.

**Comment by Iamgoofball** [comment]
re-add all of those

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

They don't exist under this voiceset--if they did, they would have been included. It's a bit non-sensical to have a female voice suddenly turn into an extremely harsh roboticized male voice mid announcement because of mixing the two systems.

**Comment by Iamgoofball** [comment]
@Fox-McCloud You do realize we can generate those words, right?

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

I wasn't aware of that; if you can get your hands on them, I'll gladly include them here.

**Comment by Flip-Sandwich** [comment]
buzwarn and doop and bloop and co are just alarm bells that can be readded at will (please readd them, they are vital for singing 99 johnson and para rangers)

**Comment by Fox-McCloud** [comment]
re-added the alarms/bells--this time in .ogg instead of .wav

**Comment by Fox-McCloud** [comment]
puttin' DNM on this until I can get ahold of the replacement files.

**Comment by Fox-McCloud** [comment]
OKi doke, thanks to @tigercat2000 the old Vox files have been re-generated to the same voice as the female Vox.

The only sounds that will *not* be included are the voxtests and 420weed every day.

**Comment by tigercat2000** [comment]
@Fox-McCloud I don't think that's a good idea. Especially the 420 one, because that is hilarious.

**Comment by Spacemanspark** [comment]
I'm with tigercat2000 on that, please don't remove those.

**Comment by Necaladun** [comment]
Re: Voxtest2 - it was funny the first 10 times, the next 990 just make me groan. I see no really good reason to use it. At the very least it should be called something different. 

I'd much prefer people come up with something original. I've very rarely seen it used properly, just randomly. It's almost getting like WGW.

As for generating new words - is this all made by a program then?

**Comment by Iamgoofball** [comment]
@Necaladun Mhm.

**Comment by Earthdivine** [comment]
VoxTest2 can burn in a fire, neca hit it home with the fact that it has been used far too much for very little purpose. The AI can spew something original if it wants to be insultin towards someone.

**Comment by tigercat2000** [comment]
Well, I guess voxtest2 was kinda bad. But, I'm really not happy about removing the rest of the voxtests, because they are short and fun.

**Comment by tigercat2000** [comment]
And @Necaladun Yes, it's all made by a N3X15 program.

**Comment by TheDZD** [comment]
Removing vox_420 doesn't really matter, considering the words "smoke," "weed," "every," and "day" are all available for use.

**Comment by Fox-McCloud** [comment]
Likewise, "ass blast USA" is also able to be reproduced.

**Comment by tigercat2000** [comment]
True, but voxtest3 cannot be reproduced.

**Comment by Iamgoofball** [comment]
what was voxtest3

**Comment by Iamgoofball** [comment]
https://github.com/N3X15/ss13-vox

here's the shit for generating words

**Comment by ZomgPonies** [comment]
Well, since the wordlist is kept, this is good to go as far as I'm concerned.

**Comment by Svej** [comment]
While we're at it, could we have the old welcome sound? I tried to commit it once, but you said it wouldn't fit the current ai voice, but now it does.

**Comment by Fox-McCloud** [comment]
@Svej 

It still doesn't; the AI voice you're referring to it the one that Baystation uses, which is vastly different from the one we use.

The announcer voice is different from the AI voice.

**Pull request merged**
