### PR TITLE
Adds Improved Tatortot Sprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Implements @Fullofskittles Improved Tatortot sprite! Credit to her for them.

5da819fa1ef152d1b0d10a1023e2e954 1

:cl: Fox McCloud
tweak: improves the tatortot sprite
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
It looks like a frowning smiley

**Comment by taukausanake** [comment]
I don't get the joke... I mean I THINK I do but I really don't

**Comment by Fox-McCloud** [comment]
The original tatortot sprite also has a face on it; that aspect is unchanged; this is just a much higher quality sprite.

**Comment by jughu** [comment]
Remove the face its a meme i do not tolerate taitortot frowning face memes i want a real TATORTOT not one with a face but one potato fried into a delicious tot!

**Pull request merged**
