### PR TITLE
Adds an explosion buildmode

### PR DESCRIPTION
**Pull request by Crazylemon64**
I wanted a quick way to make a lot of explosions for testing, maybe this will be handy for others.
:cl:Crazylemon
rscadd: Adds an explosion buildmode
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I like.

**Comment by monster860** [comment]
Now, we wait for an adminbus to adminbus explosions following someone running as fast as they can to the emergency shuttle

**Comment by Crazylemon64** [comment]
"It's a load bearing shuttle!"

**Comment by Ar3nn** [comment]
All the keks

**Pull request merged**
