### PR TITLE
Bunch o' Fixes

### LINKED ISSUE #821: Respawn as NPC bug/ oversight.
If you click on observe before a round starts, you can click on 'respawn as NPC' and actually start playing an NPC before the round starts. Perfect for trolling the HoP as Ian by flipping over tables and moving lockers, to see their faces when they actually do spawn in.

### LINKED ISSUE #825: Clicking "follow" as a ghost on the labour camp beepsky teleports you to botany bees.
See above. I have no idea.

### LINKED ISSUE #925: Cannot Centre on Robots Making Announcements as AI
While playing as AI you cannot centre on a robot by clicking its name when it makes an announcement; you will _always_ get an error message, even if that robot is within sight of a camera. You can, however, centre on them via the 'track' command in the Robot Control window.

### LINKED ISSUE #965: Magnetic Gripper cannot be used to change permissions on Airlock electronics
Using the gripper on itself doesnt open up the permission panel for the Airlock electronics meaning that drones and Engineering cyborgs cannot build doors or windoors with permissions set

### PR DESCRIPTION
**Pull request by Krausus**
Various fixes. One of these is enabling the grouping of contents of pill bottles, which I'm pretty sure was only disabled because contents grouping didn't work with pills; it does now, so I consider enabling grouping on them a fix, but I can revert it if it's an issue.

* Fixes AIs and ghosts not being able to track/follow bots that make announcements over the radio. (Fixes #825, fixes #925)
  * This required adding an override to several bits of the saycode, *just* for bots.
    * At least I used named arguments, so it shouldn't cause too much trouble if even more arguments get added to those procs.
* Fixes AIs not being able to track people who hold papers/PDAs up to their cameras.
* Fixes cameras not properly updating when upgraded.
  * Upgrading a camera with x-ray vision wouldn't update its visibility until something else caused it to do so.
  * Upgrading a camera with motion sensing wouldn't make it process and actually work
  * These upgrades *would* work if applied by the malf AI's Upgrade Camera ability, because the necessary updates were there, *instead* of in the upgrade procs, where they belong.
    * Also, this ability doesn't seem to actually let you pick a camera, but I'm too lazy to try and fix it. The important thing is that it doesn't runtime.
* Fixes engineering borgs not being able to change permissions on airlock electronics held by their magnetic gripper. (Fixes #965)
* Fixes observers spawning as an NPC or drone before the round has started. (Fixes #821)
  * Usually, you wouldn't be able to spawn as a drone because the drone fabricators took too long to prepare one, but a delayed round start would give them time to do so.
* Fixes the captain's medal of captaincy not properly attaching to his jumpsuit when spawned.
  * This caused an issue where clicking the jumpsuit would teleport the medal into your hand, regardless of where it was.
* Fixes black powder decals not being deleted when they **literally explode**.
  * This made it impossible to apply a fresh coat of black powder to a previously exploded area, and that's terrible.
* Fixes numbered contents grouping things with the same type, but different names.
  * This was causing plants grown using the new botany system to all be grouped together into one, since they all use a single type now.
  * This also made contents grouping unusable for pill bottles, since all pills are the same type.
* Fixes pill bottles not grouping their contents.
  * The only reason they didn't already do so was because grouping didn't handle pills right, at all.
  * They look so neat and tidy now!
  * delicious pills
  * Contents grouping seems to occasionally cause some weird ghosting when items get shuffled around. Not sure how to reproduce it reliably, but it doesn't seem to cause any actual problems.
* Fixes aliens not having an attack cooldown when attacking space pods.

I've been testing these as I went, and it looks like everything's working good.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:100:

**Comment by Spacemanspark** [comment]
Plot twist: He doesn't even play here.

**Comment by Krausus** [comment]
Krausus. I pestered you a few times before I got around to actually using the github.

> Plot twist: He doesn't even play here.

Sure I do... just, not consistently.

**Comment by Spacemanspark** [comment]
Oh... I just noticed, no more pre-round start Ian trolling.
:+1: -cries-

**Comment by ZomgPonies** [comment]
Mind getting online for a few minutes?

**Pull request merged**
