### PR TITLE
You have 30 seconds to live

### PR DESCRIPTION
**Pull request by Crazylemon64**
With this PR, vox should die so quickly that nobody will have any opinions on whether they are imbalanced or not.
:cl:Crazylemon
fix:Voxes is Poxes!
/:cl:

### CODE REVIEW

**Comment by Jovaniph** [comment]
They had it coming.

**Comment by KasparoVy** [comment]
What a beast

**Comment by SamHPurp** [comment]
Skrek!

**Comment by DarkPyrolord** [comment]
The perfect PR, exactly what we needed.

**Comment by Spartan6** [comment]
Finally, perfect balance.

**Comment by Birdtalon** [comment]
Perfect, now we can get back to our lives.

**Comment by Necaladun** [comment]
yeah inb4 fucking metafriends go as atmos and leave full nitro bottles at the shuttle for them

we should just make nitrogen as poison as o2 to them

**Comment by Crazylemon64** [comment]
@Necaladun Oh, that's right, that makes this PR literally unmergable. Back to the drawing board!

**Pull request closed without merging**
