### PR TITLE
Simplify some wall code and minor cult changes

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Added sheet_amount and girder_type vars to walls
Cult girders have a bigger and clearer icon from tg
All girder subtypes should be named properly now, no more "reinforced" it's "reinforced girder"
Cult girder is a subtype of /obj/structure/girder now
Summoned cult walls do not drop a girder or runed metal to prevent runed metal farming
Fixed not being able to make cult walls with runed metal + runed girder
Harvesters can smash down more things, they also get to summon cult floors and walls
Removed the human remains and blood from cult walls, they were really ugly and those things are unremovable
Runed girders need to be deconstructed with a welder instead of a wrench. Cultists can use their tomes to insta-decon them.

:cl:
tweak: Runed girders have a clearer and bigger icon
fix: Girder subtypes are properly named, "reinforced girder" and not "reinforced"
tweak: Summoned cult walls do not drop a girder or runed metal to prevent runed metal farming
tweak: Cult walls no longer have blood or human remains in them
add: Harvesters can smash more things and can summon cult walls and floors
fix: Fixed not being able to make a cult wall with runed metal + runed girder
tweak: Runed girders will need to be deconstructed with a welder (or plasma cutter or jackhammer) instead of a wrench. Cultists can hit them with their tomes to instantly demolish them.
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Curious if this is outside the scope of the PR, but currently there is no way to 'reverse' taking apart a reinforced wall. If you use wirecutters on a reinforced wall, it pretty much looks fucked up forever until you take it apart fully and then rebuild it.

It would be nice if you could perform the steps in reverse to repair a reinforced wall that has been tampered with.

**Comment by Aurorablade** [comment]
Okay the making walls and floor is kinda the builder constructs niche and giving them that high of an a environment smash may be too much. I would not be opposed to the harvesters being able to pry doors open after a delay.  

I also liked the flavor of the walls leaving at least blood behind cult Wise.

**Comment by uraniummeltdown** [comment]
I don't think giving Harvesters environment smash 3 and cult floor+wall spells, because they only appear at the end of the round when the cult has won. A lot of the time you see harvesters stuck in a room at roundend because there are no windows out, their purpose is to bring bodies to Narsie so I don't think giving them env smash 3 is too bad. Also gave them the cult construction spells so they can paint the station culty in celebration.
As for the cult walls having blood, if you try and build a serious cult base it just looks really tacky when you remove the walls later

**Comment by KasparoVy** [comment]
Revenant-style nightvision for Harvesters? 😛

**Pull request merged**
