### PR TITLE
Fixing an old atmos error

### PR DESCRIPTION
**Pull request by DarkPyrolord**
As was bought to attention in tgstation/tgstation#37116 and requested after internal discussion.

As was bought up in that PR, atmos hasn't worked as intended in a very long time, around 10-15 years in terms of SS13 as a whole, plasma fires won't burn nearly as hot as they do now at lower temperatures due to this bug being fixed, this will also have a large impact on maxcap toxins bombs in terms of power in a way that nerfs them.

As also explained in the /tg/ PR, this is how it works it out right now and how it is actually meant to work:
```DM
temperature_scale = (temperature-PLASMA_MINIMUM_BURN_TEMPERATURE)/(PLASMA_UPPER_TEMPERATURE-PLASMA_MINIMUM_BURN_TEMPERATURE)
```
So with our current numbers which are sorted out with these numbers:
```DM
#define PLASMA_MINIMUN_BURN_TEMPERATURE 100 + T0C //T0C = 273.15
#define PLASMA_UPPER_TEMPERATURE 1370 + T0C
```
Which then adds up to:
```DM
temperature_scale = (temperature- 100 + 273.15)/(1340 + 273.15 - 100 + 273.15)
```
Or,
```DM
temperature_scale = (temperature + 173.15) / (1816.3)
```
This is waaaaay off compared to what is actually intended for plasma, which you can see the difference in this:
```DM
temperature_scale = (temperature - 373.15)/(1270)
```

If you do wish to buff plasma back to this state as this is simply a bug fix, a PR can be made in the future by someone else which does it through a way that isn't a bug, I'm open to seeing it.

🆑 DarkPyrolord
fix: Fixes a ten year old atmos bug, fix will cause toxins bombs and plasma fires to be a little less lethal
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Need to get

```
#define FIRE_MINIMUM_TEMPERATURE_TO_SPREAD	150+T0C
#define FIRE_MINIMUM_TEMPERATURE_TO_EXIST	100+T0C
```

Too.

**Comment by DarkPyrolord** [comment]
And covered, I am blind!

**Comment by Allfd** [comment]
I would be interested in seeing this in game as a test merge.

After 15 years, its not really a bug anymore.

[
Microsoft Support: Microsoft Excel incorrectly assumes that the year 1900 is a leap year. This article explains why the year 1900 is treated as a leap year, and outlines the behaviors that may occur if this specific issue is corrected.](https://support.microsoft.com/en-us/help/214326/excel-incorrectly-assumes-that-the-year-1900-is-a-leap-year)

**Comment by Anticept** [comment]
It should be test merged. This has long and deep consequences. I was thinking about bringing this over here, but was really unsure if it was even going to be necessary.

Bombs will especially be affected by this. This could be considered positive or negative.

**Comment by tigercat2000** [comment]
This does deserve the balance tag.

However, that doesn't change the definition of a _fix_. This wasn't intentional and the amount of time a bug sits dormant doesn't make it no longer an issue. If this causes balance issues, they need to be addressed in other ways (changing the intentionally tweakable fire defines or adjusting the math used to calculate it, same deal with toxins bombs).

**Comment by Allfd** [comment]
I agree with @tigercat2000 , however this is fundamentally a balance PR unless accompanied with the mentioned changes.

**Comment by matt81093** [comment]
Bug fix with balance implications.. not too complicated to understand. I wouldn't mind seeing this in action as-is pre-altering. (... I could just do this local.. but where is the fun in that..)

**Comment by optimumtact** [comment]
we merged this and literally had no ill effect other than people having to rejig and rework their bomb meta anyone claiming this has "deep and long consequences" is pants on head stupid.

**Comment by variableundefined** [comment]
It took us nearly six months for the six pairs of parenthesis in this PR. Miscalculation like this impairs future improvement to the atmos code, too.

This PR has been approved by a head and maintainer. No one complained during the test merge. It is going in.

**Pull request merged**
