### PR TITLE
Restore drone law order

### PR DESCRIPTION
**Pull request by tigercat2000**
#1913 changed the drone laws, staffchat is having a fit over it, so whatever

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
This would be necessary if anyone even respected the no interfering law. It
is almost always broken - by one mean or another.

**Comment by ZomgPonies** [comment]
And we perjobban people from drones for interfering with the crew.

**Comment by tigercat2000** [comment]
@ZomgPonies Don't blame me, multiple seniormins put up a fit (I'm glaring at you, @Bram961) over it

**Comment by CrAzYPiLoT-SS13** [comment]
In all my time on the server, I haven't seen anyone get banned cause of
this, but that may just be me.

**Comment by Bram961** [comment]
The lawset the way it is now became an issue when a drone attempted to protect someone when it confused the "don't harm" part of the lawset, with a "keep harm from happening" kind of law (which the way it is now takes priority over not interfering), I can understand their confusion hence why they are currently unbanned.
Were the law to be updated as stated in this commit there wouldn't be any issues like this.
Loopholes would be gone as well so banning people for breaking the interference law would be much easier.

**Comment by Fox-McCloud** [comment]
I personally favor the old lawset, as well.

**Comment by Plotron** [comment]
@CrAzYPiLoT-SS13 
Read ban appeals, you lazy person!

**Comment by CrAzYPiLoT-SS13** [comment]
Hahah, yeah sorry, I just joined back the community after a long time.
Probably in the meantime the ban rates for this type of violation has gone
up. Sorry again.

**Pull request merged**
