### PR TITLE
Removes Changeling Bloodtest

### PR DESCRIPTION
**Pull request by TheDZD**
Requested by @Earthdivine.

[Forum Post](http://nanotrasen.se/phpBB3/viewtopic.php?f=48&t=4391)

This was introduced back when loyalty implants still made people 100% loyal to the corporation and security would implant every suspected changeling without question, turning every changeling into a friendly antag, and making for a boring round.

Currently, security just goes around blood testing everyone to root out changelings, and stun + testing everyone who refuses. This results in all of the changelings being lynched and/or cremated, making for a boring round.

Note: The administration staff are currently looking into a spam-proof and suitable replacement for this, however thus far one has not been found. The concept of confirming a changeling is fine, but the current implementation is a bit... lacking.

@ The maintainers - Might want to tag this as controversial.

### CODE REVIEW

**Comment by SamCroswell** [comment]
Replace it with a heat-based reaction. That would solve the problem.

**Comment by TheDZD** [comment]
The problem with a heat-based reaction is that it would only add the requirement of carrying around a welding tool to heat the beaker.

**Comment by Robertha89** [comment]
Ling ability that turns them 100% human for a 3 to 5 mins having 3m lose all powers. Thus being undetectable but can be permanently killed in that form. Alternatively chance normal blood having that reaction.

Having a good way to confirm lings is great. But a good non-a bus able alt is hard if not,  impossible.

**Comment by Iamgoofball** [comment]
Dude, with a ling test what stops me from announcing mandatory testing for all crewmembers under a "if you're on thr manifest and don't show you're obv a ling" clause?

remove the antag tester, any kind of antag testing is never fun at all.

**Comment by Fox-McCloud** [comment]
Mixed feelings.

Even on Goon, there's rules for metagaming antag-testing. Going around stun-testing everyone for being a vamp or changeling is going to get you banned--even on Goon.

That said, if admins can't/won't/are too busy to enforce a rule like this, then it would probably be best to comment this out for the reason goofball has outlined.

**Comment by ZomgPonies** [comment]
Pretty much all antags have a tester, even if it's a loyalty implant...

**Comment by tigercat2000** [comment]
@ZomgPonies Loyalty implants aren't a way to test antags anymore

**Comment by Spacemanspark** [comment]
Unless it's a rev.

**Comment by tigercat2000** [comment]
Unless it's a *head rev

**Comment by Spacemanspark** [comment]
Aye.

**Comment by adrkiller59** [comment]
My input: http://nanotrasen.se/phpBB3/viewtopic.php?f=48&t=4391#p27981

Also the vote right now is 1 for keeping the test, 17 for removing/changing it. Not bad.

**Comment by Artorp** [comment]
:+1: 

A ling should never be found out unless he messed up and got in trouble / committed a crime / someone saw him linging. The current implementation of the test is too spammable.

**Comment by veganzombeh** [comment]
I think I've said this before somewhere, but I think the test shouldn't be removed, just nerfed. It shouldn't always correctly identify changelings, the probability should be 20+(genomes*10) or something.

**Comment by Robertha89** [comment]
Here is an replacement test, lings absorbs implants, and it can take 10-20 minutes, making it impossible for a ling to be implanted for long.

**Comment by ZomgPonies** [comment]
Alright if someone wants to come up with a new, unabusable test go right ahead. For now voting pushes this through.

**Pull request merged**
