### PR TITLE
Adds new sprites for toolboxes

### PR DESCRIPTION
**Pull request by FreeStylaLT**
img
They look pretty good. I'd say out with the old, in with the new. 🙆‍♂️

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
Oh Jesus christ.
Oh *Jesus* christ.
I can feel the storm brawing.

**Comment by Lady-Luck** [comment]
How about letting us carry toolboxes in bags?

**Comment by Necaladun** [comment]
While certainly...fancier sprites, I think they lack the simple, robust charm of the current one. They don't look like they could carry all the tools they do to me, nor look like they could crush someones skull.

**Comment by SamHPurp** [comment]
Honestly feel as though they are a downgrade from the current ones.

**Comment by FlattestGuitar** [comment]
The colors look kinda bland.

👎, but I'd like to see a version where they're more saturated.

**Comment by tigercat2000** [comment]
i actually agree with @SamHPurp 

what the fuck did you do free

**Comment by KasparoVy** [comment]
But can you put them in a guy's chest?

**Comment by Fox-McCloud** [comment]
img

I dunno, these are pretty sexy.

I am no obligated to downvote everyone in this thread, including myself.

**Comment by Spacemanspark** [comment]
Not really a fan, unfortunately. Kinda agree with Sam.

**Comment by SamHPurp** [comment]
@tigercat2000 truce?

**Comment by tigercat2000** [comment]
@SamHPurp for the moment :eyes:

**Comment by FlattestGuitar** [comment]
What if we come up with artstyle guidelines that define what our sprites should look like?

We already have consistency issues which aren't helped by the fact that new sprites are rarely looked at in the context of the whole game.

**Comment by Norgad** [comment]
These look like they've fallen over

**Comment by AndriiYukhymchak** [comment]
Toolbox has to save its original orientation, IMO
So I'm all in for a toolbox update, just don't make me tilt because of the tilt

**Comment by FreeStylaLT** [comment]
😢

**Comment by LightFire53** [comment]
Only issue I have is that they are kind of diagonal. They don't sit on tables like that.

**Pull request closed without merging**
