### PR TITLE
Updates shotguns sprites.

### PR DESCRIPTION
**Pull request by TravellingMerchant**
Adds the general shotgun barrel sprite improvements from the previous shotgun axe PR, without the shotgun axe parts.

From this weird blob:

To this:

On most shotguns.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Could you take a screenshot of the whole shotgun rather than just the tip? It helps to actually tell what the change does for the overall theme of the weapon.

**Comment by TravellingMerchant** [comment]
Before

After

**Comment by taukausanake** [comment]
Oooo, kind of tough. On the one side that barrel looks nicer now, but on the other I like how rounded the old sprite is

**Comment by Ralta** [comment]
I actually prefer the old barrel to be completely honest. Sorry :/

**Comment by TravellingMerchant** [comment]
The old barrel had no clear definition between the magazine tube and the barrel itself. Now it does.

**Comment by taukausanake** [comment]
Try an experiment. How does it look with that top pixel on the barrel removed? A little of both worlds, maybe that will work better?

**Comment by ProperPants** [comment]
rightreducedcqbshotgun
The new one actually looks like a combat shotgun, with barrel clearly longer than tube.

**Comment by TravellingMerchant** [comment]
Looks like this if its the same length:

image

image

**Comment by Fox-McCloud** [comment]
Don't think this is necessary to be honest; it makes it look more like something from an 8-bit game and really isn't worth a change for a pixel or two.

**Pull request closed without merging**
