### PR TITLE
Alphabetical preferences menu

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
Re-orders the preferences menu to be alphabetical. The window is also slightly taller so you dont have to scroll now
Requested as part of Ansari's list
image

**Images of sprite/map changes:**
Before (Taken on live server, so I dont see the admin options):
image

After:
image
*Some things are also reworded slightly to make more sense*
**Changelog:**
:cl:
tweak: Preferences are now in alphabetical order
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I think I would have sorted them by type of special role, but I can't think up of how that would go. This is good though

**Comment by Ralta** [comment]
Love it.

**Comment by MrMagolor** [comment]
Ironically, I think this would be best as its own thing that you can toggle in the preferences menu for the sake of muscle memory, though I don't know how feasible that would be.

**Comment by FalseIncarnate** [comment]
@MrMagolor Feasible, but ultimately not worth the time to code. You'd essentially have to maintain two lists for any time a new preference is added/removed/renamed, and I'd imagine the preferences probably aren't something you are altering frequently enough for "muscle memory" to really be a significant factor for the average player. It would pretty much just be code-bloat at that point, which is something we strive to avoid when possible.

**Pull request merged**
