### PR TITLE
Alt_Body system

### PR DESCRIPTION
**Pull request by tigercat2000**
This is a system which allows for preference-saved alternate 'bodies'. Currently, the only availible body is a snake-lower-body. Adding a new body, however, is as simple as sprites + 6-7 lines of code.
Similar but not identical to #1472 
Currently limited to admins, changing the preference requires R_ADMIN.

This would require SQL changes if merged;
`ALTER TABLE database.characters ADD alt_body MEDIUMTEXT`
`ALTER TABLE database.characters ADD alt_body_colors_red SMALLINT(4)`
`ALTER TABLE database.characters ADD alt_body_colors_green SMALLINT(4)`
`ALTER TABLE database.characters ADD alt_body_colors_blue SMALLINT(4)`

A few explanations for coders: 
 - Yes, it does hook into the tail layer and therefore the tail_update proc, this is for a reason; Adding a new layer at the same position as the tail layer would be more complicated and messy than simply using the tail layer, as the layer is situated at the correct level for a 'body'.
 - No, this PR isn't sarcastic.

Images:
uniformswork! robosnek antsnek
sodohardsuits! sidemage 
sidemage sidemage
couple species
rest

### CODE REVIEW

**Comment by TheDZD** [comment]
I still think the sprites look horrible. You might want to try asking @Nienhaus or FullOfSkittles if they can sprite better ones.

**Comment by Dumbdumn5** [comment]
*SCREAM *SCREAM *SCREAM *SCREAM *SCREAM

**Comment by Regen1** [comment]
Can we please NOT have a fucking fetish in our codebase?

**Comment by Markolie** [comment]
As long as it's admin only, why not.

**Comment by TheDZD** [comment]
> Can we please NOT have a fucking fetish in our codebase?

Too late, ponies and assless chaps are already in.

**Comment by FreeStylaLT** [comment]
Hiss~ :see_no_evil: I am fine with thissss~

**Comment by Fox-McCloud** [comment]
For all intents and purposes, this is the same PR uploaded as last time: https://github.com/ParadiseSS13/Paradise/pull/1472

Still going to say the same thing.

:+1:  For customizeable tails

:-1:  to the horrible bodies.

**Comment by tigercat2000** [comment]
@Fox-McCloud This doesn't have customizable tail support at all, nor ever will. That's not what the system is intended for. It's not "the same for all intents and purposes".

**Comment by Fox-McCloud** [comment]
If it's never going to support customizeable tails, then :-1: from me,f or reasons covered in the previous PR. DZD said it best there:

>:+1: to the datum-based tail system.
:-1: to the weird animal bodies, partly because they look weird being glued on to a species, and partly because the sprites are low quality.

**Comment by Robertha89** [comment]
Snake body sprite looks fine tbh
No worse then Lamia cosplay. I see nothing wrong here.

**Comment by KasparoVy** [comment]
Snake and shark're the only good ones
+supp, though I'm disappointed about "doesn't have customizable tail support at all, nor ever will"

Don't know why I had the delusion this'd make that possible but w/e

**Comment by Aurorablade** [comment]
better sprites but as admin only perfect for that one silly prayer you get...LOOK YOUR GOD GAVE YOU THE LOWER BODY OF A SNAKE REJOICE 'but i wanted a honk mech' SNAKE BODY

**Comment by Fox-McCloud** [comment]
It's worth mentioning that Skittles already has a few extra tail sprites and has wanted to work on more of them--but that kinda fell through when the prior PR got closed.

**Comment by KasparoVy** [comment]
SKITTLES!? Noice. Now I know they're gonna' be good

**Comment by Flip-Sandwich** [comment]
:-1: for the purpose of *scream

**Comment by Iamgoofball** [comment]
>As long as it's admin only, why not.

REMEMBER WHEN LIZARDS ON TG WERE "ADMIN ONLY FOREVER"

**Comment by tigercat2000** [comment]
The DNM tag can be removed, the code works fine, just a bit lacking in content and good sprites.

**Comment by taukausanake** [comment]
If I may add on to this, would it be possible to add in other alt_body options? I do understand the general dislike of "furry" components (ie: ears and tails) but I do think they would make for a nice addition to this and make it more fulfilling.

Question: does this affect legs in any way? Do they still exist and be interactive with? I don't want to find a stray leg fly off of someone who is only supposed to have a snake lower body

**Comment by tigercat2000** [comment]
@taukausanake It would be endlessly complicated to play with the organ system to support that, so technically, yes, that would happen. However, not really an issue, since this is currently an admin-booze only system.

**Comment by Nomzosha** [comment]
What regen said.
SOMEONE PLEASE PUT THE DNM LABEL BACK ON, WHOS CRAZY IDEA WAS IT TO REMOVEIT
:-1:  :-1:  :-1:  :-1:  :-1:  :-1:  :-1:

**Comment by Fox-McCloud** [comment]
Adding the controversial label do this until a conclusion can be reached.

**Comment by tigercat2000** [comment]
So far, I count 4 clear "No", 2 screaming, 2 neutral, and 3 yes.

**Comment by Elysian-Prince** [comment]
If you want my formal opinion on it--consider it done. :+1:

**Comment by TheDZD** [comment]
Not certain what you counted me as, but I'm going to :-1: unless better sprites for the alt bodies are provided.

**Comment by tigercat2000** [comment]
5 clear "No", 2 screaming, 1 neutral, and 4 yes, then.

**Comment by Nomzosha** [comment]
My formal stance is :-1: if that wasn't clear.

**Comment by Mijhead** [comment]
:+1:

**Comment by Earthdivine** [comment]
It's admin only, it's not like well be seeing 6 or 7 of the things on station unless someone gets really bored. Plus it could lead to some fun new things down the line, hopefully. :+1:

**Comment by Fox-McCloud** [comment]
If the scope of this PR is changed to allow for customized tails in addition to cusomizable bodies (with the latter remaining admin only), then I could support this--otherwise, still a definite :-1: from me.

**Comment by HereticChurch** [comment]
I see no problem with it as long as its admin only. Has potential for fun adminbus and events. :+1: from me.

**Comment by MactoPerFuror** [comment]
:+1:

**Comment by Alex6511** [comment]
Maybe with custom tails, :-1: for now.

**Comment by Spacemanspark** [comment]
As long as it's not used on me, I don't care.

**Comment by Dinarzad** [comment]
Thumbs up from a random nobody.

But I don't much see the "Fetish" part of it. It's a snake body. If you don't want a 'fetish' in your codebase, then why do you have Anthropomorphic "Furry" Cat people, Lizard people and Fox people?
I don't see much difference between this and having Vulps, Tarjans or Unathi personally.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

The difference is, Unathi, Tajarans, and Vulpkanin weren't explicitly designed on a fetish codebase for fetish codebase players----this feature was designed and built by vorestation for vorestation players--that's part of the reason why people are taking issue with this.

**Comment by tigercat2000** [comment]
Vote is currently 9 yes to 6 no, 2 unclear/neutral, and no comments in the last 4 days.

**Comment by dreadweaver** [comment]
I'd like to leave a comment. I honestly see no reason why this should not be merged. The 'fetish' argument is plain invalid, both because ERP is strictly forbidden on the server and because it won't be available to players. And needless to say, admins shouldn't use the tail for non-event characters either.

**Comment by TheDZD** [comment]
Merge conflicts.

**Comment by tigercat2000** [comment]
Already fixed in my latest local version, just waiting on a few things before pushing it.

**Comment by tigercat2000** [comment]
Alright. Rewrote the entire thing, past the point where I am comfortable with just updating this PR, so going to make a new one. Snake tails still included, but alternate tails for players also included.

**Pull request closed without merging**
