### PR TITLE
Chem Lab Re-map

### PR DESCRIPTION
**Pull request by SamCroswell**
chemlabcompletecomplete

- Re-maps the chem lab. I have attempted to keep the balance of the previous chem lab intact.
- Removes the mostly (If not entirely) unused firing range from the lab.
- Hopefully reduces the number of angry Xenobiologists with holes blown in their lab.

Note the human in the test lab is actually a monkey, and will look like one when the round starts.

### CODE REVIEW

**Comment by Keilden** [comment]
Sweet, somthing to vent gas with!

**Comment by tigercat2000** [comment]
Uh... You do realize that a scrubbers pipe between the vent and scrubber won't work, right?

**Comment by SamCroswell** [comment]
@tigercat2000 
This is exactly how the xenobio scrubber loop is set up.

**Comment by tigercat2000** [comment]
@SamCroswell It probably doesn't work either. Scrubber pipes are hardcoded to not connect to vents, only scrubbers.

**Comment by Fox-McCloud** [comment]
I like it.

**Comment by TheDZD** [comment]
Yeah, I tend to see xenobiology breached because of this quite often. :+1:

**Comment by fj45** [comment]
Great.

**Comment by ZomgPonies** [comment]
Fix the scubber pipe thingamajig and I'll merge it.

**Comment by Plotron** [comment]
How about the single door to the test chamber? The old chem lab uses two, to work as a proper airlock. The stairs are ugly and the water/fuel tank number has been cut in half (not like it wasn't an overkill previously).

Everything is placed alongside the walls, making it look like an oversized corridor. The 1 tile crawlspace in the corner (test chamber windows) looks like a joke.
These are just my initial thoughts.

**Pull request merged**
