### PR TITLE
Minor Genetics Balance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Some genetics balance tweaks:

- Removes genetics side-effects
 - Simply put, these are not intuitive, at all to the user that something major has gone wrong; you suffer some bad thing and, unless you've looked at the code, have no idea how to correct it--sometimes you end up getting turned into a monkey as well, which can kinda ruin your ongoing round identity....not to mention that sometimes the side effects will trigger for no reason at all, even if you counter them.
- Ups the radiation an injector gives you to compensate for these side effect removals

### CODE REVIEW

**Comment by Earthdivine** [comment]
I kind of liked the side effects, as the made the Genenticists have to be aware of what's going on and to also talk to their coworker then mindlessly shoving needles in them and taking anything that's anti tox. You get surprised once and you know what to expect. I would say the only one that should have something done to it is the Monkey, as it is definatly a round ruiner.

Though it's probably harder with Goonchem to keep up with radiation damage, and I don't know how well these side effects play with the new chem either.

**Comment by TheDZD** [comment]
Higher radiation damage means that their genes often get messed up by RNG if they keep injecting themselves without pause, which means that making yourself a superpowered monster is just slightly more difficult.

**Comment by Robertha89** [comment]
Personally I would add in ye ol RNG of getting powers at all 50% chance, thus empty blocks hurt more.

**Comment by TheDZD** [comment]
@Robertha89 Injecting yourself with a power block already has an RNG chance to give you a power for most of the high-end ones (hulk, and x-ray for example).

**Pull request merged**
