### PR TITLE
Removes photos from medical and sec consoles

### PR DESCRIPTION
**Pull request by Crazylemon64**
Does as advertised.

:cl:Crazylemon
rscdel: Photos from medical and security consoles, as well as ID cards, have been removed, as they've got a knack for crashing clients.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Also IDs. Those crash people as well.

**Comment by Vivalas** [comment]
At least until this gets fixed. All for removing a novelty feature to stop crashing.

**Comment by Fruerlund** [comment]
Don't feel the crashes are occuring enough to remove this IMHO.

**Comment by Lady-Luck** [comment]
>Don't feel the crashes are occuring enough to remove this IMHO.

Play a warden. You will change your mind. I had a dozen crashes one round.

**Comment by Sky-Ping** [comment]
> Play a warden. You will change your mind. I had half a dozen crashes one round.

Yep.

**Comment by Spacemanspark** [comment]
I used to print people's records off when they were next to a console, as an AI prank.
This was living hell due to this bug.
However, please re-add this when it's fixed.

**Comment by Crazylemon64** [comment]
Oh - I didn't remove printing records - should I do so?

**Comment by Spacemanspark** [comment]
No, no.
It doesn't print a picture.
The reason it was hell was because, to print it, I had to view the record (including the picture).
Records are just fine.

**Comment by tigercat2000** [comment]
an alternative was suggested to this by using goonchat's bicon/icon2base64 for displaying images instead of the varying methods currently

**Comment by Lady-Luck** [comment]
>an alternative was suggested to this by using goonchat's bicon/icon2base64 for displaying images instead of the varying methods currently

A nice idea, if someone wants to actually do it.

**Comment by TheDZD** [comment]
Should now be unnecessary with #4910 merged.

**Pull request closed without merging**
