### PR TITLE
New sprites for O2 wall lockers

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Upgrades wall lockers to modern colorful palette and style

## Why It's Good For The Game
Trust me

## Images of changes
image

## Testing
I went out and checked every wall locker on Cyberiad to make sure i like them

## Changelog
:cl:
imageadd: New sprites for O2 wall lockers
/:cl:

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]
LGTM

**Comment by Aylong220** [comment]
Does it look a little too... toyish?
It's better like this
image

**Review by Burzah — APPROVED** [review]

**Comment by McRamon** [comment]
> Does it look a little too... toyish? It's better like this image

yeah these look great, but they are from eris and i am personally not porting anything from other servers.
Also the "toyish" or "cartoonish" look is what i am aiming for. Though i might play around with sprites a bit, i like the techniques of these sprites.

**Comment by Samman166** [comment]
Why orange? I like the sprite but the orange seems a bit off. An emergency red or another shade of blue might make more sense.

**Comment by McRamon** [comment]
> Why orange? I like the sprite but the orange seems a bit off. An emergency red or another shade of blue might make more sense.

dunno, orange seems absolutely fine and attracts attention. Red is fire extinguisher/firefighting color.

**Review by S34NW — APPROVED** [review]
thank GOD

**Pull request merged**
