### PR TITLE
Re-Adds Ninja Gear

### PR DESCRIPTION
**Pull request by SamCroswell**
Note: This is _not_ feature complete, by any means. The only reason I'm opening a PR as early as I am is because I want to avoid merge conflicts in the eyes and glasses icon files.

- Create the file for ninja gear.
- Add all items for basic ninja gear.
- Add an additional icon in glasses.dmi and eyes.dmi for the off state of the ninja eye implant.
- Fully implement the ninja eye implant.
 - The implant fits in the eye slot, and does absolutely nothing if not on the eye slot of a ninja with his suit enabled.
 - When the ninja turns his suit on he can use a verb to open a menu which allows him to select vision modes. He can enable as many of these modes as he wants, but enabling any of the vision modes will put an increased drain on his power cell per tick. The vision modes are as follows:
  - Night Vision, 2E/tick
  - Meson Scanning, 2E/tick
  - Material Scanning, 4E/tick
  - Thermal Scanning, 4E/tick
  - Antag HUD, 6E/tick

### CODE REVIEW

**Comment by SamCroswell** [comment]
Any and all icons I expect to add have been added in this PR. I request someone merge this before a conflict appears.

**Comment by ZomgPonies** [comment]
2 late, merge conflict.

**Comment by SamCroswell** [comment]
*Is furious*

**Comment by SamCroswell** [comment]
Conflict resolved.

**Pull request merged**
