### PR TITLE
Medical chemistry rebalance

### PR DESCRIPTION
**Pull request by FlattestGuitar**
As one of the frequent medical chemistry players I've noticed some flaws in the current assortment of medicine avaiable. I've made this PR to try to give more use to the rarely seen chems and to nerf the ones used extensively. My main aim is to give doctors and chemists more choice, while not buffing the jobs or making their lives any easier.

I'm expecting a lot of discussion in the comments, the current state of this PR is by no means final. Please do voice your opinion on the changes I've made and suggest others.

Full list of changes:
- saline-glucose now heals more realiably, but is about 25% less effective.
- charcoal now removes reagents more reliably, is less random
- calomel now deals 60% less toxin damage, but requires pentetic acid to make and has a dangerous mixing reaction
- potassium iodine now heals small amounts of toxin damage 
- pentetic acid is now 50% as effective at removing reagents from patients to account for less lethal calomel being a thing
- salbutamol no longer requires salicylic acid in its recipe, making it much easier to produce
- morphine is now five times less likely to addict someone, previously a syringe of morphine had a 85% chance of getting the person addicted, now it's around 25%
- epinepherine will now heal toxin, brute and burn damage even if you fall below -65% health
- strange reagent will deal much more damage to living patients now, it's viable as a poison
- mutadone no longer acts instantly, instead has a 15% chance every cycle to do its thing
- degreaser also purges pure synthanol now
- rezadone no longer acts instantly but requires mutadone instead of carpotoxin, making it a normally available chem instead of having silly requirements

I've also moved around the code a bit to make it less messy, all the "removed" reagents in the diff are still there, no worries.

No changelong, because I feel I'll have a lot of things to tweak here before this has any chance for a merge.

### CODE REVIEW

**Comment by Taaketa** [comment]
Thank flip for the for the Salbutamol change. Making Perfluorodecalin was always easier to do and I never bothered to make Salbutamol because of the extra steps for the Salicylic Acid.

**Comment by theColdflame** [comment]
I'd save the mutadone change for after the genetics nerf.

Aside from that, :+1:

**Comment by IcyV** [comment]
>charcoal now removes reagents more reliably, is less random
calomel now deals 60% less toxin damage, but requires pentetic acid to make and has a dangerous mixing reaction

Kinda makes these both super amazing. Calomel was already top tier for anything chemical related. Coupling it with Charcoal will have essentially no downside and be absolutely absurd.

>epinepherine will now heal toxin, brute and burn damage even if you fall below -65% health

Ehhhh. Not terrible I guess. I kinda always imagined epi for being the last attempt to save people, not a good healing drug all the way through.

>mutadone no longer acts instantly, instead has a 15% chance every cycle to do its thing

RIP single defense against hulk monsters

**Comment by FlattestGuitar** [comment]
>Kinda makes these both super amazing. Calomel was already top tier for anything chemical related. Coupling it with Charcoal will have essentially no downside and be absolutely absurd.

Currently any chemist worth their saline won't touch calomel with a stick because it is inferior to pentetic acid in every way, while charcoal takes too much time to make compared to the already-necessary pentetic acid so there's not much point in bothering anyway.

While the chems will be more powerful after this patch, there will be more options and diversity, letting people choose. 

Also, calomel still deals toxin damage faster than charcoal can heal it, so you can't efficiently couple them to make a heal-all medicine, not mentioning the fact that they'll both purge each other very efficiently.

>Ehhhh. Not terrible I guess. I kinda always imagined epi for being the last attempt to save people, not a good healing drug all the way through.

By "-65%" health I mean being 35% away from death, already deep in hard crit. For some reason epinepherine stops acting at that point, I removed that restriction.

>RIP single defense against hulk monsters

A syringe of mutadone has a 99.7% chance to get rid of all mutations, the only real difference is the time it takes for it to act.

**Comment by Fox-McCloud** [comment]
:-1: x :100 by far my least favorite PR that I've seen in months.

This is effectively the same PR as you uploaded before, and I'm completely and totally set against it for similar reasons; I don't support a single change here outside of coding re-organization.

This ruins a number of recipes that were otherwise accurate and realistic.

A lot of these medical chems don't need to be touched, as they're perfectly fine as is and each have their own independent niche. A lot of them have no need for change and function just fine without any issues.

For example calomel is meant to be an offensive purgative+situation poison, but is also meant as an easy to make medical purgative to be used in high risk situations where you don't have time to make pentetic---it's also excellent for use with individuals who have robotic limbs as it avoids the brute damage dealt with them. Making it require pentetic not only puts it solidly in the category of "never going to be made, ever", but it's now non-effective as a situational poison.

I could go on, but this is an example of nuance here that you're wiping out, in addition to buffing/nerfing chems that aren't problematic, at all, ATM.

**Comment by FlattestGuitar** [comment]
This is actually my first chem PR, soo...

>This ruins a number of recipes that were otherwise accurate and realistic.

I don't see why that would be bad.

>A lot of these medical chems don't need to be touched, as they're perfectly fine as is and each have their own independent niche. A lot of them have no need for change and function just fine without any issues.

My problem is that many chems that exist in-game are rarely used, when there's obvious potential for making playing medbay more interesting. Each chem having its own small niche leads to a situation in which playing medbay isn't about making choices based on your judgement, but going down a flowchart and always doing the same thing in a given situation.

>Calomel blerb

I have personally never seen calomel used that way. I was subjected to it a handful of times by a few chemists who had no idea there was a better alternative. As it stands there really is no reason to make it when you have sleepers at your disposal in an emergency

Also, as I said, there's a lot of room for changing things around in this PR.

>nuance that you're wiping out

I absolutely don't see how making more chemistry recipes viable to add to the game's diversity is "wiping out nuance".

**Comment by Fox-McCloud** [comment]
>I don't see why that would be bad. We're not a realistic game, which you have stated yourself numerous times.

This is true, to a degree, but intentionally making things unrealistic, when there's no reason to otherwise do so is also bad---ie: you expect shooting a gun at someone to fire bullets, not pizzas---you expect water to be made of two parts hydrogen and one part oxygen.

One of the big pushes of Goonchem was for a more diverse, deep, and realistic chem system, overall.To that end we've managed to be pretty much 1:1 with them and it's worked out very well for us in the 1.5 years that we've used it now.

You're always going to have chems that outclass other chems in some situations---there's really no point to making silver sulfa when you can make synth flesh, for instance if you look at the raw numbers----but there's other factors here, as well; silver sulfa is super easy to make on the fly, where as synth flesh requires additional equipment and external resource expenditure.

Some other chems are in the category of "meant to be pre-stocked, but superior chems are available" (and to this, I do think you could make the argument that potassium iodine should be in the fridges by default)--salbutamol, for instance, falls within this category.


Either case, I could go on and on, but I am 110% set against this PR. Not trying to sound melodramatic, but words can't really describe how much I dislike this.

**Comment by Lady-Luck** [comment]
The morphine change needs to happen.

Carpotoxin isn't even on the chemistry wiki, meaning Rezadone functionally doesn't exist. Either the wiki needs to be updated, or it should use Neurotoxin or Cyanide.

The mutadone change probably should happen for consistency's sake and to keep chemists from just making a million 1u pills of it.

Degreaser change, sure.

Everything else I'm fairly neutral on.

**Comment by Lady-Luck** [comment]
Sorry what I meant to say was https://www.youtube.com/watch?v=EddX9hnhDS4

**Comment by Da-Dman234** [comment]
> I absolutely don't see how making more chemistry recipes viable to add to the game's diversity is "wiping out nuance
Not to try and make a big deal out of this, but all that you're doing is switching around what's viable and what's not. You claim to be making it more diverse, but all this will do is make people use Synthflesh instead of Saline Glucose, Calomel instead of Penetic, ect. You can't really claim to be trying to diversify things when you're just switching up the status quo, because people are always going to use the strongest chem available to them, there's just no reason not to. I promise you if these changes go through all you will see is Calomel in the fridge instead of Penetic, and how exactly does that diversify things?

Each chemical we have fills a certain niche, there's no point to "balancing" because people will ALWAYS use the most effective chemical that fills that certain niche, so you can't really diversify, and it's pointless to try and add more chems, because why bother with them when X does it however many times better and you can fill the fridge completely in 15 minutes if your competent.

Also, unrelated to my little argument up there, clone damage is supposed to require a medbay visit to fix. It's a rare form of damage that's meant to be debilitating, and I don't think it's really something that should be able to be made easily, all changing the recipe will do is buff science so they literally never have to visit medbay. Carpotoxin isn't even that hard to obtain, since every other round it spawns in the floor-pills.

**Comment by FreeStylaLT** [comment]
rest in formaldehyde

**Comment by FlattestGuitar** [comment]
I've talked to Fox about this and he's justified why exactly this PR is bad.

I'm not saying the chemistry system is in a perfect place, but with things like the genetics nerf coming into play soon I think it's better to give things some time and see how they develop.

**Pull request closed without merging**
