### PR TITLE
Adds Airlock System to BoxStation Supermatter Engine

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Adds an airlock system (like xenobiology) for the supermatter engine on Cyberiad that contains showers and rad suits. Also adds an airlock system that lets atmospherics enter the engine area as well.

As a result, it meant the engine SMES area was shifted in size, as well as rezoned to it's own area (/area/engine/engine_smes) that already existed in the code. That area has also now been adjusted to require power so it's APCs actually function properly.

## Why It's Good For The Game
 Currently the showers for radiation are on the other end of the map, as well the engine room wasn't necessarily true to the rad risk you ran when it came to distance. @Denthamos and I played around with the idea of an airlock system that isn't obtrusive, but gives a radiation area close to a large source of radiation. This also is a QOL update to atmospheric technicians who sometimes need to get into the supermatter room.

## Images of changes

Main station engineer airlock:

image

Atmospherics airlock:

image

Engine SMES Area:

image

Engine Repiping:

image

Re-Areaing:

image

## Changelog
:cl:
add: Station engineers now have a radiation airlock to access the NSS Cyberiad supermatter engine
add: Atmospherics now has a radiation airlock to access the NSS Cyberiad supermatter engine
add: Engine SMES is now in it's own area
tweak: Engine Room now has less chaotic piping
tweak: Breaks up engineering a little more in regards to areas
tweak: the "engine_smes" area now requires power
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
Note: Denth and I want to just try Cyberiad first to see how the playerbase reacts, and this would probably be a good candidate for a TM.

**Comment by Contrabang** [comment]
image
Doesn't this maint door here kind of make the whole side airlock kinda useless since you can just bypass it?

**Comment by LightFire53** [comment]
> image Doesn't this maint door here kind of make the whole side airlock kinda useless since you can just bypass it?

If you have engineer access, then yes. Atmos techs don't though

**Review by S34NW — CHANGES_REQUESTED** [review]
image
The scrubbers pipes here can be simplified

image
This is a bit painful, why do it like this when there is ample room on the tiles one to the south?

image
Not sure I like this here either, when there is ample space on the floor for them. No issues with the distro pipes on the other side, however, due to complex pipe setups there.

image
This area strikes me as a bit awkward, perhaps lose the rack and have the closets face the south window?

image
undocumented (albeit fine) changes

image
carp spawn here got deleted for no reason, poor carp :(

image
Seems there are some layering issues here with the sign and shower head

image
Don't think this is your fault, but this is a third alarm for this area, the others being by secure storage and the SM. Perhaps we can subdivide the areas further?

image
This airlock randomly has `ACCESS_CONSTRUCTION`, but the other doors leading into the room and connected rooms have `ACCESS_ENGINE`

**Comment by AffectedArc07** [comment]
I assume the cycle here is like the xenobio style one, not a full air cycling one?
image

**Comment by S34NW** [comment]
> I assume the cycle here is like the xenobio style one, not a full air cycling one? image

There are no linked vents or air sensors to the airlock controller, so it just doors the doors.

**Comment by Dafrek** [comment]
Atmos techs having access to the SM is nice, would also be nice if they were able to access the SM monitoring computer, but I can understand if thats not done. Also having 3 doors leading to engineering from atmos maints makes it look a bit weird.

**Review by hal9000PR — DISMISSED** [review]
you re-added the syringe guns to medical. please remove them again

**Review by S34NW — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]
LGTM

**Pull request merged**
