### PR TITLE
Nuclear Ops now have one normal EVA space suit to sneak in the station.

### PR DESCRIPTION
**Pull request by Emanthealmighty**
**What does this PR do:**
Nuclear Operatives now get one standard non-suspicious space travel equipment bundle that one single member can use to sneak in the station without having to bring in any obviously traitorous equipment.

This includes:
A small enlargement of the equipment room to the north
The addition of a new suit storage unit that contains a normal EVA suit, a jetpack and magboots.
The enlargement of the table, and the addition of a suppressor to fill in the empty table space.

**Images of sprite/map changes:**

**Changelog:**
:cl: EmanTheAlmighty
add: Added a non suspicious space travel bundle in the Nuclear Operatives' ship to be used for sneaking in the station. 
This includes: a new standard suit storage unit containing standard space travel equipment (EVA helmet, suit and mask), normal magboots and a jetpack.
tweak: Enlarged the Nuclear Ops' equipment room to make space for their new stealthy gear.
add: Added one free suppressor in the equipment room.
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Cue newkies accidentally using the wrong SSU and taking that instead of their hardsuit. I'd suggest putting it somewhere else, instead of in a line with identical SSUs with different content. Maybe in the equipment room on the base itself? Also, can't you put the jetpack and magboots in the SSU anyway?

**Comment by Emanthealmighty** [comment]
> Cue newkies accidentally using the wrong SSU and taking that instead of their hardsuit. I'd suggest putting it somewhere else, instead of in a line with identical SSUs with different content. Maybe in the equipment room on the base itself? Also, can't you put the jetpack and magboots in the SSU anyway?

I wanted to keep things the same way they are on the station. There's a bunch of SSUs, and then the magboots and jetpacks are in another place near them.  I'd have to make another variant of the unit to have the magboots and jetpack appear in the unit just for this one occasion, and didn't really feel like doing it.

**Comment by TDSSS** [comment]
It's like that on station because station has more suits than it has jetpacks/magboots

**Comment by Emanthealmighty** [comment]
Alright, put everything in the suit storage, I also decided to add in one tiny suppressor to fill in an empty space in the elongated table.

**Comment by AffectedArc07** [comment]
You forgot to use mapmerge

**Comment by Emanthealmighty** [comment]
I've never done a map PR before, could you explain to me how to do them properly? 

Couldn't find anything special about how to make map PRs earlier...

**Pull request closed without merging**
