### PR TITLE
TCC Cult walls

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Ports cult walls from TCC

## Why It's Good For The Game
We're using TCC walls, I have no idea why TCC cult walls were left out.

Actually while writing this, it crossed my mind that we in Paradise have multiple different types of cults and that these walls might be a _little_ too narsieish. So, I want to hear your feedback, I can zap the brown and make it a more monotone grey colour to fit in reaper cult and the like or I can just keep it brown.

## Images of changes
image

## Testing
Ran in-game.

## Changelog
:cl: Bmon
imageadd: Cult walls ported from TCC.
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
Code looks fine to me, smooth groups are accurate.

**Review by S34NW — CHANGES_REQUESTED** [review]
Actually, upon further thinking I have to revoke the approval.

Please see the `wallglow` effect in `icons\effects\cult_effects.dmi` as this will need to be refactored to work for these new patterns and shapes. TCC has a file for this https://github.com/TauCetiStation/TauCetiClassic/blob/6e9c61ea429f3c78494aff3c092f984e21c11135/icons/turf/walls/cult/runed_anim.dmi

**Comment by Bm0n** [comment]
> Actually, upon further thinking I have to revoke the approval.
> 
> Please see the `wallglow` effect in `icons\effects\cult_effects.dmi` as this will need to be refactored to work for these new patterns and shapes. TCC has a file for this https://github.com/TauCetiStation/TauCetiClassic/blob/6e9c61ea429f3c78494aff3c092f984e21c11135/icons/turf/walls/cult/runed_anim.dmi

little bit of a different glow effect but easy enough, probably work on it later today

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Comment by Bm0n** [comment]
i am lazy so i am not going to make a gif, go look at icon diff

image

**Review by S34NW — APPROVED** [review]

**Pull request merged**
