### PR TITLE
Revert "ERT Gloves"

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Reverts #5211

Didn't want to stir crap on Ty's first PR, but them not having combat gloves at that level was *most certainly* intentional on my part when I first designed the current ERT system.

Each member of the ERT isn't supposed to have every answer to every problem, much less so at code red. Discourages diversification of the ERT roles and gives people even less reason to pick anything other than sec as their ERT specialization.

I expect lots of unnecessary drama over this.

Commander keeps the gloves.

Spiffy new combat glove icon, very tacticool:
combat_gloves

:cl: DaveTheHeadcrab
tweak: ERT gloves reverted to how they used to be.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
Alright then

**Comment by DaveTheHeadcrab** [comment]
No, Styla, you're doing it wrong.
You're supposed to get unnecessarily bent out of shape about this, and start telling me how I hate fun.

**Comment by TullyBurnalot** [comment]
@DaveTheHeadcrab You ruined it.

You preempted all the jokes.

You monster.

**Comment by FreeStylaLT** [comment]
Oh no Dave let me tell you how essential the gloves are to everything ERT you literal stalitler.

**Comment by Krausus** [comment]
> Alright then

What? That's it? Not going to mention things getting out of hand? Or perhaps that it's shocking they don't all need insulated gloves?

Who are you, and what did you do with the Styla we know?!

**Comment by Chakirski** [comment]
> What? That's it? Not going to mention things getting out of hand?

Well I guess you could say...
*Puts on sunglasses
Things already are out of hand.
YEAAAAAAH!

**Comment by FreeStylaLT** [comment]
Someone ban him please

**Comment by TullyBurnalot** [comment]
In all seriousness, I would not be averse to the Commander getting Combat Gloves on Code Red. They are a singular role, and are, nominally, **the** highest ranked individual on the entire station if the ERT gets called.

**Comment by Regen1** [comment]
Hello I am a concerned citizen and I am here to riot

**Comment by Davdichan** [comment]
#DaveHatesERTs #DaveNerfsERTAgain

**Comment by Regen1** [comment]
No fun allowed fucking dave

**Comment by Aurorablade** [comment]
hold on gonna make an alternative PR that makes ERTs spawn without hands..

**Comment by Fox-McCloud** [comment]
>hold on gonna make an alternative PR that makes ERTs spawn without hands..

Hey, maybe the crew would finally start trying to solve their own problems instead of relying on the sissy squad then.

**Comment by Lady-Luck** [comment]
I'm against this. Combat gloves was a good idea. A special ops squad should be prepared to handle one of the most basic obstacles in the game without getting fried.

**Comment by DaveTheHeadcrab** [comment]
A shocked door isn't a "basic obstacle", it's a fairly rare (The occasional EMP or a malfunctioning AI are the only two thing that will typically permanently shock a door) and idiosyncratic occurrence specific to one branch of the ERT. Moreover, a shocked door is never an instant kill that "fries" said person even if it does crop up, unless the engine has been hotwired. *If* the engine has been hotwired there are larger issues, like the APCs shooting electricity at everyone, and much like ERT members that aren't medical don't have the tools readily available to them to fix a viral outbreak, ERT members that aren't engineering don't have the tools readily available to them to fix a hotwired engine.
If noone signed on as engineer for an engineering emergency such as that then the team, as they should, will have to do some basic hunting to find the tools neccessary to get it done.

Your mistake is assuming that the ERT, especially at code red, (At Gamma medics are the *only* team members susceptible to door shocks), are some form of catch-all superheros that should be able to counter everything thrown at them regardless of how they've decided to compose the team.

We had that system for two years. It's never fun for the opposition, and it's _rarely_ fun for the crew except that they get to be on the "winning" side.

**Comment by IcyV** [comment]
Pretty much what Dave said. ERT is called all the time and makes most situations trivial as is. Any group of prepared and good ERT members is pretty hard to beat for the majority of antags that don't go to some large powergaming extents. They were always meant to be an *assistance* to the station, not a solve-all easy solution available at a moments notice with a single press of a button by the crew.

Not a lot of people still around probably remember the times that they couldn't just call a super-well geared ERT anytime they wanted here. When they were actually reserved for when things were screwed to a crazy degree and were pretty much there to make sure the crew didn't die horribly and help out where possible instead of just hanging around and killing all the antags for people.

**Comment by FreeStylaLT** [comment]
Commander probably deserves to get Combat gloves, as Tully said, though

**Comment by Taaketa** [comment]
Although CAN the APCs overload anymore? I've tried several times on MALF AI to hotwire the engine and never seen the APCs overload at 2million watts.

No problem with the reversion. But just pointing out I don't think overloaded APCs are actually a problem anymore.

**Comment by TheDZD** [comment]
Yeah, commander probably should still have shock-proof gloves.

**Comment by Ty-Omaha** [comment]
TACTICOOL SPRITE!!!!!!!!!! :D :+1:  :x: :100:  but there's 1 thing missing, the knuckle reinforcers.. :(
Either way they are level 4 tacticool now

**Pull request merged**
