### PR TITLE
Stops shadowlings from targeting simple animals (mice)

### PR DESCRIPTION
**Pull request by Ty-Omaha**
There's no reason to have shadowlings targeting mice and simple animals

This makes it so they can only target "humans". Humans as in any playable species like vulp, slime, diona, grey, etc. 

This also makes it so they cannot target robots. Their spells don't even work on the robots anyways.

🆑 
tweak: Shadowlings no longer are able to target simple animals (mice)
/ 🆑

### CODE REVIEW

**Comment by Taaketa** [comment]
I take their scream or whatever still works in Borgs?

**Comment by Ty-Omaha** [comment]
It only sets enthrall, glare and revive thrall to humans only, things that pop up with a list of targets.

Screech is an aoe not a targeted so it doesn't touch that

**Comment by KasparoVy** [comment]
THE RAT FOLK WILL RISE!!!

Vite in umbra

**Comment by Regen1** [comment]
Var name might be a bit misleading.

What about "exclude_simple_mobs", or "carbon-humans-only"

**Comment by variableundefined** [comment]
carbonhumanonly (not sure if BYOND allowed dash in variable name) or carbon_human_only seems to be a better variable name as Regens said. Otherwise looks good.

**Comment by variableundefined** [comment]
LGTM

**Pull request merged**
