### PR TITLE
Botany Map Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Remaps botany a bit. 

This is partially so botanists don't get bumped around when using the machines, but its mostly about so that :bee::bee::bee: don't get hung up, forever, wanting to kill the pig/chicken/cow.

Only thing lost is a floodlight, which I contend isn't a big deal.

img1
This is why losing a floodlight isn't a big deal--this is a single floodlight with every other light on station broken:
img2

Mapping additions/removal
- Removed a bush and gave another soil plot in the shared garden
- Removed one floodlight

:cl: Fox McCloud
tweak: Re-maps botany a bit to make it more bee and botanist friendly
/:cl:

### CODE REVIEW

**Comment by Mijhead** [comment]
:+1:

**Comment by FalseIncarnate** [comment]
As long as all the wall mounted stuff is still accessible (namely that request console), :+1: from me

**Comment by Fox-McCloud** [comment]
>As long as all the wall mounted stuff is still accessible

It is, I tested for this when I did the floodlight test.

**Comment by KasparoVy** [comment]
Why not just move the second floodlight into the back room and let it sit ontop of the valve-pipe apparatus thing there?

**Comment by Fox-McCloud** [comment]
Because I kinda question why Botany should even get floodlights to begin with and because they're used, more often, to hunt for shadowlings, than an actual help for botany.

Also, one of them covers the entirety of botany and then some.

**Comment by FalseIncarnate** [comment]
Botany having just one light is fine with me, they are really meant to keep the plants alive if the power goes out, since you can just use tray lights and lids if the normal lights are out but you still have equipment power.

However, being without power is uncommon since we don't have the power outage random event in rotation.

**Pull request merged**
