### PR TITLE
TGUI 4.2: TGchat + Refactor Asset Delivery + Yarn Berry

### PR DESCRIPTION
**Pull request by Aylong220**
## What Does This PR Do
Port and adaptation of TGchat and yarn berry
Following PR's were are used:
https://github.com/tgstation/tgstation/pull/52426
https://github.com/tgstation/tgstation/pull/52947
https://github.com/tgstation/tgstation/pull/53011
https://github.com/tgstation/tgstation/pull/53012
https://github.com/tgstation/tgstation/pull/53075
https://github.com/tgstation/tgstation/pull/53141
https://github.com/tgstation/tgstation/pull/53294
https://github.com/tgstation/tgstation/pull/54517
https://github.com/tgstation/tgstation/pull/54895
https://github.com/tgstation/tgstation/pull/54971
https://github.com/tgstation/tgstation/pull/56575
https://github.com/tgstation/tgstation/pull/59843
https://github.com/tgstation/tgstation/pull/66220
https://github.com/tgstation/tgstation/pull/66299
https://github.com/tgstation/tgstation/pull/69211
https://github.com/tgstation/tgstation/pull/72514
https://github.com/tgstation/tgstation/pull/77228
https://github.com/tgstation/tgstation/pull/52955
https://github.com/tgstation/tgstation/pull/53026

At this point, there are the following critical issues that need to be addressed:

- [x] ScrollTracking - dead. Chat is at the very top, new messages do not scroll the chat and accordingly the "Scroll to bottom" button does not appear if you start scrolling up. Can be temporarily fixed only on 514 Byond if you open and close KitchenSink in chat (Double F12).
- [x] ~~Fix Chat doesn't work on 515 Byond, it just kills chat.~~ (It was a personal issue)
- [x] ~~tgui-dev-server: Unstable working on Byond 514 and complete failure to work on 515~~ (It was a personal issue)
- [ ] Traitor's codewords hightlights. Due to too many differences in the code compared to TG, I couldn't get the chat to highlight code words. In all likelihood need someone to write new logic and most likely a refactor. I'm skill issue.
- [x] ~~Test all interfaces and correct regressions. (Partially completed already, partically will be fixed wth next stages of the project)~~ (It's better to do it when everything is ported)

I tried to fix all of the above, but unfortunately failed and wasted a VERY long time. In other words, I'm unable to can

## Why It's Good For The Game
New beautifull chat, with filters and bright future

## Images of changes
image

## Testing
Painfully

## Changelog
:cl:
add: GoonChat replaced to TGchat
del: GoonChat is gone
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Nit: Prefix localstorage and cookie entries with `para-` to avoid history merges with TG and every other downstream.

Is this also adding the chat telemetry?

**Comment by Aylong220** [comment]
> Nit: Prefix localstorage and cookie entries with `para-` to avoid history merges with TG and every other downstream.
> 
> Is this also adding the chat telemetry?

I don't quite understand what "Nit" is but yes, telemetry should be there as it is a full port from TG, I don't understand why the history from other servers is in the way, in the future we can add "clear chat" button

**Comment by AffectedArc07** [comment]
> > Nit: Prefix localstorage and cookie entries with `para-` to avoid history merges with TG and every other downstream.
> > Is this also adding the chat telemetry?
> 
> I don't quite understand what "Nit" is but yes, telemetry should be there as it is a full port from TG, I don't understand why the history from other servers is in the way, in the future we can add "clear chat" button

Nit = nitpick

If this is telemetry is the SQL change going in this PR or the full one?

**Comment by Aylong220** [comment]
> If this is telemetry is the SQL change going in this PR or the full one?
> 
> Reference: [tgstation/tgstation#63435](https://github.com/tgstation/tgstation/pull/63435)

It's definitely won't be part of this PR. Personally I don't want to touch SQL, at least not in the near future

**Comment by S34NW** [comment]
> Nit: Prefix localstorage and cookie entries with `para-` to avoid history merges with TG and every other downstream.


Done

**Pull request merged**
