### PR TITLE
Add carrot seeds to perma

### PR DESCRIPTION
**Pull request by datlo**
Add 3 carrot seed packets to perma.

Two reasons for this : 
- Allow prisoners to heal eyedamage from flashes/other sources
- Allow prisoners to sharpen the carrot using a glass shard from the glass table to make a carrotshiv (already doable just never used since no carrots available in perma)

permacarrot

🆑
add: Added 3 carrot seed packets to perma.
/🆑

### CODE REVIEW

**Comment by KasparoVy** [comment]
What's up doc' 🐰

**Comment by Pennwick** [comment]
This makes me somewhat sad that knives can't embed when thrown. We can't have a mysteriously vanished officer show up in the perma showers with several sharpened carrots staking him to the wall.

**Comment by KasparoVy** [comment]
Yeah, embedding was seeeeeeriously gimped. Used to be able to do stuff like that (and embed a full box of glass shards in people as fast as you could throw) and I suppose it is a somewhat better alternative, but the odds are SO low.

**Comment by Pennwick** [comment]
The chance is actually decent for items that can embed. The reason more things don't is because they need to be above a speed threshold of 4 to embed as well. Its rare that objects have both a throw speed of >=4 and that they're sharp.

**Comment by KasparoVy** [comment]
But no slingshots to fill the void in a more controllable manner?

**Comment by variableundefined** [comment]
I approve this

**Pull request merged**
