### PR TITLE
Tail Wagging System

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in a Tail Wagging System

Simply put, this adds in a system that allows for animated tail wagging; if your species has the proper flags (in this case TAIL_WAGGING), then you can use the *wag emote to start wagging your tail and the *swag emote to stop wagging your tail. If additional species ever require animated tail wagging animations, in the future, then all that would be further required would be an animated sprite and adding the proper flag to that species (species would require a tail to begin with).

Putting on a suit that hides your tail will automatically stop your tail from wagging and prevent use of the *wag emote as long as you're wearing that suit.

For now, only Tajarans are capable of wagging their tails: animated sprite courtesy of Full of Skittles!
image
Tail waggin' in action.

And no, absolutely not a port =p

### CODE REVIEW

**Comment by Spacemanspark** [comment]
>*Swag emote.
Dammit.
Love this, though.

**Comment by tigercat2000** [comment]
This is.. absolutely horrifying... but I kinda want it.. perhaps a gif of it's actual appearance would be good to have?

**Comment by Spacemanspark** [comment]
Tigercat: https://dl.dropboxusercontent.com/u/96894922/Saf2.gif
FoS posted this on his topic.

**Comment by tigercat2000** [comment]
Not sure that is fully accurate of these sprites, but, uh, I see no.. problem per say.. it's kindof horrifying, but, why not have it?

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Short for "stop wag"; I was going to originally use "wags", but the problem with this is that it just registers it as "wag"--and having *stopwag is irritating to type out every time; it should be something that's quick and easy to type out in a fraction of a second.

**Comment by Spacemanspark** [comment]
I know, I was just messing with you.

**Comment by Fox-McCloud** [comment]
Fixed dead Tajarans tail waggin'

**Comment by Spacemanspark** [comment]
Out of curiosity, how does this effect Tajaran/ whatever other animals with tails that have on modified hardsuits? Are they still able to swings-his-tail or no?

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

No tail wagging with hardsuits on ever.

**Comment by Nienhaus** [comment]
Oh my god. This is amazing.

**Comment by Fox-McCloud** [comment]
The tails will wag.

**Comment by Regen1** [comment]
There is WAY to much wagging in this PR http://puu.sh/g6xhX/3a116f9e85.png

**Comment by StreakyHaddock** [comment]
THIS IS HERES

**Pull request merged**
