### PR TITLE
Changes the Escape Shuttle Security doors to basic Security access

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

**[Remake of #13979, with added standardisation!]**
Changes the required access level on all shuttle brig doors and the departures holding cell from `2`*(Equipment Storage)* to `63`*(Sec front doors)*.
This also effects the 'foyer' doors, but all heads have basic sec access anyway so it shouldn't make any difference for them.

## Why It's Good For The Game

Security/Support staff should be allowed to sit ~~away from the rabble~~ with the rest of their department on the way to Centcomm.

### Before:
***(Green marks doors that can be accessed by these roles, red is inaccessable.)***
Old

### After:
New

**(For clarification, changed doors are marked in cyan:)**
image

## Changelog
:cl:
tweak: Changed the access on all escape shuttle brig doors to be basic sec access, rather than equipment access. (Detective, Blueshield, IAA, etc. have access now.)
/:cl:

### CODE REVIEW

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
image
Making these security only is an absolute no from me.
Although, it appears you didnt do that in your diff. Could you make your screenshots clearer?

**Comment by SabreML** [comment]
Sorry, I pretty much just copied them from the old PR. Green is the doors that the Detective/BS/IAA can access, from their point of view.

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
As per map standardisation, please remake these changes on the other 2 maps.

**Comment by SabreML** [comment]
Meta doesn't have a direct route from escape to the Security section, so no changes are needed there.

**Review by AffectedArc07 — APPROVED** [review]
Approving now, obviously waiting on mapping queue

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
