### PR TITLE
Adds the Tourist Outfit as a wearable shirt.

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds the blue shirt that observers wear as something that you can buy from the AutoDrobe.

## Why It's Good For The Game

The sprite was already in the game, but only used in one situation.

More customisation choices, and a new spooky outfit.

## Changelog
:cl:
add: Added the Observer clothing as a wearable shirt from the AutoDrobe. Named 'Tourist Outfit'
tweak: Made some of the sprites in `icons\obj\clothing\uniforms.dmi` more alphabetically ordered.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Literally everyone ded label def. Appropriate

**Comment by Spacemanspark** [comment]
You madman

**Comment by SabreML** [comment]
> I'd rather observers have a unique outfit/look.

I could make it harder to get if that would help, gateway or space loot maybe.

**Comment by Kyep** [comment]
Not really.

**Comment by Dumbdumn5** [comment]
@Kyep Ghosts already take on the appearance of the corpses of their dead, and those who start as roundstart observers don't really have any mechanical or administrative difference. I have never had a situation in six years as an admin where I've needed to know if somebody was a roundstart observer or not, and when I *do* need to determine anything regarding ghosts, the already more than available BDY follow verb in the player panel makes it easy to tell they're a player. 

More elements to customize your character in the game aren't exactly a bad thing and I'd personally support this unless there's a solid mechanical/administrative reason as to why we'd need to make _certain_ that somebody is an observer at a glance.

**Review by Kyep — COMMENTED** [review]
Retracting my objection to this.
While I still think it is a bad idea, I'm willing to let it pass.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
