### PR TITLE
Cigarette Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors cigarettes and makes a few tweaks to them. Also implements a new reagent from Goon and a new cigarette flavor. Lastly, simplifies cig packet availability.

How cigarettes receive reagents was....really strange. It was handled on the packet. I get why; you could inject a packet and lace all the cigarettes at once, but it made making custom cigarettes weird and contradictory at times.

Cigarettes having reagents is now completely handled on the cigarette itself, using a reagent list; you can still inject cigarettes directly, but not their packets.

This also adjust the cigarette and cigar smoke time and reagents.

Cigarettes now have 40 units of nicotine in them, up from 15---that said, their smoke time has been lowered from 10 minutes to 5 minutes, max--mostly for flavored cigarettes.

For plain old cigs, the smoke time will be around 3.3 minutes.

Cigars have 120 units of nicotine in them and havana cigars have 180 units.

Additionally, regardless of smoke time, if a cig runs out of reagents, it goes out.

These changes are to help prevent cigs from having a "dead zone" for delivering nicotine; with current cigarettes, you can run out of nicotine, but continue to smoke them for a while---this is likely why so many people haven't adjusted to the new addiction system; they don't notice the text of "the cigarette loses its flavor" (which means no more reagents in it) and just continue smoking---only for the nicotine addiction to creep up on them.

With this change, if you're smoking a cig (that has nicotine in it anyway), as long as it's active, you should never start suffering from addiction symptoms.

This also technically buffs syndi cigs, as they now have 20 omnizine in them instead of 15. *Typically*, the standard for flavored cigarettes, post merge, should be 40 nicotine and 20 of the flavoring agent.

Other things:
- Added menthol reagent from Goon
- Added menthol flavored cigs
- Simplified cigarette vendor offering and prices; they now have robust packets, uplift smooths (menthols), and embellished enigmas (mystery flavors)

:cl: Fox McCloud
tweak: Cigarette reagent amount and smoke time altered to deliver more consistent nicotine delivery
tweak: cigarettes and cigars have much higher amounts of nicotine in them
tweak: syndi cig omnizine altered from 15 to 20
add: Adds menthol reagent
tweak: Simplified the cigarette vendor offerings: now only has robusts (regular), uplift smooths (menthol), and embellished enigmas (random).
/:cl:

### CODE REVIEW

**Comment by Darkmight9** [comment]
anyone else feel there should be a nicotine free cig pack? One for those who just like the look of it. Question is, what to have the burn regent be though?

**Comment by Darkmight9** [comment]
Oh! could make a more expensive fake cigarette that doesn't do anything other than turn on and off, basically be a mask. Could call it the Tricksterette. "Tricksterette, trick your friends into thinking you're a chain smoking bad ass without the addiction or lung cancer."

Also Trickgar the cigar version.

**Comment by Fox-McCloud** [comment]
implemented menthol reagent from Goon.

Also simplified the cig vendor to reduce cig packet offerings; it'll now have robusts, uplift smooths (menthol), and embellished enigmas (random).

**Comment by Carthusia** [comment]
Does this have any effect on pipes?

**Comment by Fox-McCloud** [comment]
No.

**Comment by Carthusia** [comment]
Will these new changes eventually be applied to pipes, or are they already within these thresholds/would that require a seperate PR?

**Comment by Darkmight9** [comment]
> Also simplified the cig vendor to reduce cig packet offerings; it'll now have robusts, uplift smooths (menthol), and embellished enigmas (random).

Eh I'm not a big fan of that one personally. Some players I feel have a specific 'brand' they like

**Comment by Cazdon** [comment]
```"fuel","saltpetre","synaptizine","green_vomit","potass_iodide","msg","lexorin","mannitol","spaceacillin","cryoxadone","holywater","tea","egg","haloperidol","mutagen","omnizine","carpet","aranesp","cryostylane","chocolate","bilk","cheese","rum","blood","charcoal","coffee","ectoplasm","space_drugs","milk","mutadone","antihol","teporone","insulin","salbutamol","toxin"```

For the possibilities in embellished enigmas. I find the idea of a vampire smoking a cigarrette, catching fire and dying because of the holy water inside very comical.

**Pull request merged**
