### PR TITLE
Security Sunglasses / Sec Hud Distribution

### PR DESCRIPTION
**Pull request by Jovaniph**
The suggestion came from: https://nanotrasen.se/forum/topic/10590-security-lockers/

So basically this PR allows security officers (especially ones who join late game) to be equipped with security sunglasses upon joining. The reason being is that normally during round start Blueshield/HoP/Captain/Detective, would try to obtain security sunglasses from the security lockers leaving a security officer not fully equipped to do their jobs if they join late game.

~~In addition, I replace the security sunglasses inside the lockers with security HUDs. If any of them wants to obtain a SecHUD, they can, but they will lack any flash protection as a downside. In addition, this will still allow antags to emag lockers to screw with security using sechuds instead.~~

🆑  Jovaniph
tweak: Security Officer starts with security sunglasses upon joining the round
tweak: remove security sunglasses from security locker
tweak: added security HUD in security vendor (3 per vendor)
tweak: added security HUD in detective locker
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Science can print them. This is unnecessary imo, people don't start with all their gear for a reason.

**Comment by Jovaniph** [comment]
They still need to get there belt, baton, flashlight, flashbang, pepperspray. The argument you try to make about that is unclear.

**Comment by karmapay2win** [comment]
>people don't start with all their gear for a reason
State the reason.

**Comment by Necaladun** [comment]
:thinking: 

This is interesting and I think I like it but will need to put more thought into it however I'm low on coffee.

**Comment by SamHPurp** [comment]
What about considering other options, such as adding a few sechud's to the armoury, adding them to the blueshield office / detectives office... or just straight up telling Blueshield and detective they aren't sec officers and should fuck right off?

**Comment by Anoonki** [comment]
> Blueshield and detective they aren't sec officers and should fuck right off?

I'm totally on board with the blueshield not having these, mostly because the Advanced MedHUD is so much cooler, but if the detective can't have them, why do the greytides at the IA office get them?

**Comment by SamHPurp** [comment]
> but if the detective can't have them, why do the greytides at the IA office get them?

Valid point. If this PR was to add a sec hud to the Detective's office, or remove it from the IAA, I'd support either ;)

**Comment by Jovaniph** [comment]
I can make the change. if this post gets thumbs up

**Comment by Jovaniph** [comment]
You want the detective to have Sec Sunglasses or Sec Hud?

**Comment by ZN23XZ** [comment]
Wanted to chime in cuz I started the post on the forums. SecHUDs were a big part of my request but overall it was because the locker room starts becoming empty of ALL gear including stuff science can't replicate. Especially relevant in high pop rounds where a few officers go SSD or cryo with all their gear and get replaced by fresh blood off the shuttle. I'd love it if there was just 2 more full security lockers added to the armory just in case.

**Comment by ZN23XZ** [comment]
Also like the idea of detective getting one and the IAA losing it. Sorry for double post, couldn't figure out how to edit.

**Comment by deep-fried-faceplant** [comment]
IAAs need those glasses, they're limited in what tools they have as it is. IAAs abusing their glasses deserve to be fired on the spot, or given a job ban.

**Comment by Fullofskittles** [comment]
Cant people just order more gear from cargo or did all of the security gear cargo crates get removed?

**Comment by Anoonki** [comment]
@deep-fried-faceplant I'd argue the detective needs them more, IA should be in few scenarios that they need something *immediately* and can't use a laptop or what have you to look at the records, unless they somehow lack access to that module.

**Comment by Ralta** [comment]
I like having them as a Detective, but they aren't hugely necessary. To some extent, I feel that having them as a Detective makes me more likely to go outside of my role without realising.

Back on topic, I'm not sure how I feel about spawning with them. Sechuds are a pretty important piece of equipment, but if we look at Engineers for example, they spawn with a full toolbelt but they don't get insulated gloves, hardsuits, magboots, multitools or any of the other things that many Engineers would consider essential to daily work.

Doctors don't spawn with that equipment either; when the medhuds, belts and nitrile gloves are gone, that's it. That's just the nature of these things, and I would argue that a medhud is of equal importance to a sechud. 

I don't think I can get on board with this because you'd then have to balance the issue with all other departments, and part of your initial round setup is getting the gear you need to do your job. If you don't have it, tough luck. Be resourceful and find it, or make do without. That just feels like part of the SS13 experience to me.

**Comment by Jovaniph** [comment]
@Ralta The problem is Sec Sunglasses are exclusive. You can't recreate them or find them in game.

**Comment by Jovaniph** [comment]
There so I made some changes

**Comment by deep-fried-faceplant** [comment]
Could you not remove them from the IAAs please. No one except for Anooki has given a reason as to why they want the legal office to loose the HUD. If this change is to curb greytiding IAAs, the behavior of a few shitty agents should not reflect upon the entire department. IAAs have a hard enough time as it is, making them even less legitimate by removing their access to the HUD will only further encourage the greytide+ mentality. Furthermore, if agents really are deleting/falsifying records and arrest statuses, please adminhelp it and work to fire the guilty agents. There are people who want to do the job right, and players who pick IAA for the flash, security access, and glasses should be weeded out. 

I feel like the desire to remove the HUD from IAAs also stems from many officers feeling the need to get back at IAAs, because of the many IAAs who are either new or misinformed about the job, and as such hamper security's ability to do it's job, rather than helping security by working as a mediator, advisor, and consul. IAA is perhaps one of the most difficult jobs to learn, because it requires a comprehensive understanding of SOP, SL and station culture, it's primarily a RP oriented job, and is very situational in it's purpose. It's all too easy to assume that the job is just "be Ace Attorney in SPESS", especially considering how similar IAA is to the lawyer on tgstation, who really is just greytide+ in most situations. Because of the difficulty in learning the job, as well as the impression that it's just a reskinned lawyer, most new players will learn the job by getting into fights with security and goofing off as an assistant. The players who play IAA as Spess Lawyer really don't need the SecHUD, I will admit. But the ones who do manage to learn the role properly consider the HUD to be indispensable.

**Comment by Jovaniph** [comment]
@deep-fried-faceplant I'll change it back, but I'm going to wait a few day for further feedback.

**Comment by Tayyyyyyy** [comment]
This is going to be harder to implement, but what if we had a security records HUD that allowed people like IAA and magistrate to view the records of people but not see/change their wanted status? This would solve the issue with overreaching detectives and IAAs.

**Comment by Jovaniph** [comment]
revert the changes with IAA sunglasses...I will no longer accept any feedback about IAA having sec sunglasses. That can be done with another PR or in a discussion in the forums. Any other feedback is allowed.

**Comment by Fox-McCloud** [comment]
"the way it is works functionally perfectly fine; the detective, as enumerated before, doesn't need sechuds"

**Comment by Jovaniph** [comment]
I was going to update this PR to reflect the one that got closed.

**Pull request closed without merging**
