### PR TITLE
Reveals Emergency Cabinet

### LINKED ISSUE #7527: Hidden Emergency Locker
**Problem Description**:
There is an emergency locker hidden beneath a time display.

You won't know it even exists unless you right click. I found it by utter accident some shifts ago.

hiddenlocker

B/W morgue and cloning, right of that other room.

### PR DESCRIPTION
**Pull request by KasparoVy**
It was hidden behind a time display, now it isn't. Resolves #7527.

:cl:
fix: Moves a hidden emergency locker to where it is visible.
/:cl:

_Before_
hiddenlocker

_After_
unhiddenlocker

### CODE REVIEW

**Comment by granodd** [comment]
Wow that's a good hiding spot. I never knew this was here until this PR.

**Comment by LightFire53** [comment]
Inb4 antags abuse it as a hiding spot before merge

**Comment by SamHPurp** [comment]
One of us is gonna get merge conflicts :(

**Comment by KasparoVy** [comment]
I'll fix them if they come up, no big deal.

**Comment by KasparoVy** [comment]
@LightFire53 I doubt even that will speed a merge.

**Comment by SamHPurp** [comment]
@KasparoVy damnit its me.

**Pull request merged**
