### PR TITLE
This, hopefully, gives overheal to nanopaste or at least can be a staging point for more experienced coders. This is my first time coding so feedback is very welcome 

### PR DESCRIPTION
**Pull request by Darkmight9**
…ging point. This is my fisr time coding so advice and impute is aprecated.

**What does this PR do:**
This, hopefully, gives nanopaste overheal or at least can act as a spring board for more experienced coders. This is my first time coding so feedback is very welcome.

**Changelog:**
*Remove this line, and appropriate fields from the changelog*
:cl: Gives nanopaste overheal
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
I hope you didn't just copy and ~~nano~~paste that code 😄

**Comment by datlo** [comment]
You need to fix your changelog as below. Also it seems the PR does not compile properly.
🆑 
add: Gives nanopaste overheal
/🆑

**Comment by ScratKnapp** [comment]
And what is nanopaste overheal..?

**Comment by Denthamos** [comment]
@ScratKnapp Basically, its going to work like advanced trauma/burn kits where it heals the primary part you place it on, but say nanopaste heals for 40 total damage and the chest you apply it on, only has 20 damage, it will spill that heal to connecting body parts to heal the lower body/head for the rest of the 20 points.

Really its just making it work just like the organic version of it, so good change.

**Comment by variableundefined** [comment]
This can be opened again when it is in a ready state.

**Pull request closed without merging**
