### PR TITLE
[DNM] Arrivals ferry! The arrivals shuttle actually carries arrivals now

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
Port of: https://github.com/tgstation/tgstation/pull/24694 and https://github.com/tgstation/tgstation/pull/19017

Frees up space on z2 by removing all the pre-made transit shuttle zones, instead loads up transit areas dynamically using markers. The arrivals shuttle now docks with the station and carries latejoiners with it.

**Images of sprite/map changes (IF APPLICABLE):**
http://puu.sh/E7Hg2/0140fce332.mp4

**Changelog:**
:cl:
add: Arrivals shuttle now docks with the station
del: transit space and transit ports in z2
tweak: transit space and ports are now dynamically loaded based on demand
del: station airlocks no longer bolt when a shuttle departs
/:cl:

### CODE REVIEW

**Comment by JohnBigless** [comment]
This would prevent space vines and blobs from spawncamping the everloving fuck out of the arrivals shuttle.
And add some realism. Gone would be the days of people popping up out of nowhere on the arrivals shuttle.

**Comment by datlo** [comment]
'del: station airlocks no longer bolt when a shuttle departs'

Does that mean that the arrival shuttle airlocks can be opened to space when the arrivals shuttle isnt docked? This will lead to SO many spaced and/or gibbed by shuttle civilians and might fuck up arrivals atmos semi regularly which is already a pain in the ass to fix due to how arrivals is mapped.

**Comment by AffectedArc07** [comment]
```
Frees up space on z2 by removing all the pre-made transit shuttle zones, instead loads up transit areas dynamically using markers. The arrivals shuttle now docks with the station and carries latejoiners with it.
```

The thing that killed parallax

**Comment by Couls** [comment]
The shuttle doesn’t actually leave quick enough for you to get fastmos’d out into space but the airlocks won’t be bolted no, I’ll see what I can do about bringing that feature back

**Comment by AffectedArc07** [comment]
Shouldnt the bolting the airlocks feature still be in, assuming you didnt just overwrite the file with the TG contents?

**Comment by taukausanake** [comment]
Literally the only thing I really wanted from /TG/. Arrivals ship _actually arriving_.

I am going to miss the hyperspace transit areas when traveling but I think Parallax killed that already

**Comment by AffectedArc07** [comment]
@taukausanake If its porting the TG shuttle system it means it dynamically creates the shuttle areas instead of having them mapped in, freeing some space on Z2

**Comment by Couls** [comment]
See, that’s the strange thing. With the new code when ur bolted the doors it seemed to bolt every door on station regardless of ID tag, I was more focused on implementing the system so I removed the bolting in order to get it working

**Comment by FreeStylaLT** [comment]
This actually has a lot of potential for changing the OOC safe haven aspect of Arrivals and I've always wanted this

**Comment by Ty-Omaha** [comment]
The shuttle doors are open in transit, a new player will just walk right out into space

They should be bolted closed too

**Comment by KasparoVy** [comment]
Lmfao. Welcome to space station 13, enjoy your stay.

**Comment by Mitchs98** [comment]
Should most definitely fix the doors not bolting thing for reasons listed above. Otherwise kinda like it~.

**Comment by Jovaniph** [comment]
I got a question. This is more of a possible oversight issue. But what about players joining the round as ghost (observe)?

**Comment by Couls** [comment]
They should spawn at the center of the station instead

**Comment by Couls** [comment]
That’s no problem, I still have to fix the issue with door airlocks bolting

**Pull request closed without merging**
