### PR TITLE
Removes the 50+ unnecessary APC instances from Cyberiad's map

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Replaces them with the proper pre-set bumps.

Please only use these when mapping in the future, unless your APC is meant to have something special about it.

before:
img

after:
img

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Free, dear, have you ever been shanked by a merge conflict in the face?

**Comment by FreeStylaLT** [comment]
yes

**Comment by taukausanake** [comment]
APCs get their name from the area they are part of I recall. This is nice QoL

**Comment by Twinmold93** [comment]
I would like to note that certain APCs DO have higher (and lower in rare cases) power cells than the default, which is noticeable as for example the hallways. Most APCs do not require a specific APC, as their power level is the same, but before utterly tearing out all APCs, you'll want to check each APC's power cell level... Otherwise, you're actually making it so certain areas can run out of power sooner if no engine is set up within a reasonable time (say war is declared and engineering starts focusing on defense), which I believe engineering is in fact one of those areas.

**Comment by taukausanake** [comment]
That shouldn't stop one person from setting up the engine as without it the station is as fucked as if they never set up defenses. Still, you might as well make a few extra instances that have higher power cells. I always thought every APC had a high cap cell myself. Why not basic, aside from engine not being online fast enough, made me wonder

**Comment by FreeStylaLT** [comment]
Re-did the 'special' cases of APCs in Engineering, important areas and Cryogenics + Engine. This should be all of the unique cases.

**Comment by Fox-McCloud** [comment]
Did you ensure all the APCs that were shockproof are still shockproof?

**Comment by Fox-McCloud** [comment]
Is this ready, @FreeStylaLT ?

**Comment by FreeStylaLT** [comment]
This should definitely be ready now, yeah

**Comment by Norgad** [comment]
I neeeeeed this for mapping.

**Pull request merged**
