### PR TITLE
Arcade map

### LINKED ISSUE #8107: Assorted shower bugs
**Problem Description**:
Showers spawn with the incorrect orientation.

dreamseeker_2017-09-15_20-21-49

Mist effects are produced infinitely when the shower is set to "hot" and never despawn

dreamseeker_2017-09-15_20-23-01

**Why is this bad/What are the consequences:**
It's a bug

**Steps to reproduce the problem**:
Load the map. Showers seem to spawn in the incorrect orientation, despite showing correctly in DM.

dreammaker_2017-09-15_20-27-53

Use a wrench twice to set the shower to "hot."
Turn the shower on and off again as many times as desired to generate "mist" objects.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

### LINKED ISSUE #8334: New Medbay has 2 Chemistry APCs
Causes quite the power issues

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds an arcade to both Cyberiad and Metastation (moves prize counter to new arcade from previous locations)
- Cyberiad:
image

- Metastation:
image

The carpet found in the arcades can now be purchased in stacks of 20 from the arcade prize counter for 150 tickets.
- Turf sprite credit goes to Goonstation

Adds a bottler unit to Cyberiad bar office (hot drinks machine moved out into bar area where prize counter was)
image

Adds a bottler unit to Metastation abandoned bar
image

Adjusts the holodeck, fitness room (dorms), and bits of surrounding maint on Cyberiad to accomodate the new arcade (sorry free):
image

Adjusts the showers to actually start on the walls and gives them better mist handling logic
- Fixes #8107

Removes the extra APC from Cyberiad chemistry
- Fixes #8334 

:cl:
rscadd: MANDATORY FUN! Arcades added to both stations!
rscadd: Bottler units have been spotted on board both stations!
rscadd: Arcade carpet tiles added to the prize counter for 150 tickets (credit to Goonstation for the turf icon).
tweak: Cyberiad bathrooms should have 100% fewer floating showers (behind curtains).
bugfix: Showers have been fitted with mist-reducing showerheads. They should no longer generate infinite mist if rapidly toggled.
bugfix: Cyberiad chemistry has had the extra APC removed. Now they only have one as standard.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
I was wondering if you were going to go through with your arcade room plan.
Good shit. :+1:

**Comment by SamHPurp** [comment]
@FalseIncarnate please map merge.

**Comment by FalseIncarnate** [comment]
Cyb fucked up the merge, of course

**Comment by taukausanake** [comment]
Nice, I like. I do wonder a little about it though. Doesn't look arcade-y enough. I'd go for carpet floor instead of tiles. I also wonder about even having an arcade at all on the station even though it would be great.

Man, if only the arcade could be closer to the bartender. I feel that would make everything perfect. Maybe in another map

**Comment by FalseIncarnate** [comment]
Updated original post with picture of slightly altered Cyberiad arcade

**Comment by taukausanake** [comment]
You want space carpet? I mean we kind of already have that. I guess I could try and make some that is a little purple-y.

Hmmm. I wonder if you could make dynamic carpet that works like space tiles

**Comment by taukausanake** [comment]
[That actually looks pretty nice](https://wiki.ss13.co/File:Arcade1.png). I say use Goon sprites

**Comment by FalseIncarnate** [comment]
I'll look into goon's sprite later, can't view the link to it at work anyways

**Comment by taukausanake** [comment]
@FalseIncarnate
image
I could clean up the edges because snipping tool but I'm too lazy

**Comment by FalseIncarnate** [comment]
That is perfect and exactly the kind of thing I was looking for. Plus, they seem to have put effort into making it tile smoothly, which will really make it extra cheesy looking. I might even add this to the prize counter as an alternative to the space carpet so people can actually replace it when it inevitably gets stolen/destroyed.

**Comment by pinatacolada** [comment]
Any chance to remove the windows to space and have the arcades be sort of dark? Idea is to have the arcades give out most of the light of the room, it makes a nice mood trust me i'm qualified

also I dont suppose theres any space near the dorms to have the cyb room at, it's kinda in the middle of nowhere in escape. like maybe have the holodeck pushed slightly north, enough to make room for like a 2 or 3 tile wide hallway connecting the dorms to that maintenance behind the holodeck, the one with the airlock, and moving the arcade there, idk

**Comment by taukausanake** [comment]
I don't think you'd be able to get it up there without moving a bit more than what would be wanted. You could turn the holodeck sideways but then all the areas would need to turn too. Then you'd be able to get in down there but it wouldn't be worth it. Way too cramped. I think the locations they're in right now are fine enough.

Too bad we can't downsize the bar to fit it in. I could see it working but only if an assistance constructed it, not mapped in

**Comment by FalseIncarnate** [comment]
I picked the escape location because it remains both easily accessible to the public and required the absolute minimum amount of actual tweaks to existing structure to add. Metastation didn't have that luxury due to how compact everything is.

The windows were not so much for light but actually to grant a breach point for space-faring threats. Removing one of the light fixtures in the room would do more to darken it than the windows, to be quite honest.

I considered stools in front of each machine but was worried it might make the room feel too cramped, though the flip side is the room feels very open. I'll play with the idea again to gauge how it feels with the darker flooring tonight after work.

I also had initially considered moving the laser tag lockers into the arcade, but ultimately decided to leave them in the fitness room. VR stuff could potentially be added to the arcade in the future.

**Comment by FalseIncarnate** [comment]
Updated with the following:
- Removed one light fixture from the Cyberiad arcade
- Added stools to both arcades
- Added a security camera and holopad to the Metastation arcade
- Added arcade carpet to both arcades and additionally adds stacks of arcade carpet to the prize counter offerings
  - Arcade carpet sprites credit goes to Goonstation

**Comment by SamHPurp** [comment]
imo just make the arcade lights be bulbs, not tubes. It'd be much darker and grungier... even if you have to use a few of them.

**Comment by FalseIncarnate** [comment]
Im sticking with the tubes, each arcade only has one. I don't want to make the arcade too dark because diona DO exist.

**Comment by taukausanake** [comment]
Yeah but the bulbs have a special feel to them that the tubes just don't have. Can we at least get a compare and contrast of the two possible setups?

**Comment by FalseIncarnate** [comment]
Will fix map conflict tonight

**Comment by FalseIncarnate** [comment]
Holding off on fixing merge conflict for now, will fix prior to merge. There's been some concerns about the Cyberiad's arcade placement that Tiger and I have been trying to figure out, so no sense fixing these conflicts until a decision is reached on whether or not this might be merge-ready on that front.

Also this means I won't have to do a merge fix for every single map-edit PR that potentially gets merged by then and can get them in one fell swoop.

**Comment by taukausanake** [comment]
I kind of like where they are right now. Out of the way, in no way a center-piece for the station. A Research Station at that. What's so bad about the current locations?

**Comment by FalseIncarnate** [comment]
The issue raised was mostly with the Cyberiad's arcade, which some believe feels "tacked on". Unfortunately, we haven't been able to reach any sort of agreement on how to correct that, since some of the suggestions proposed involve either replacing existing areas (Vacant office) or some significant mapping changes near the dorms to accommodate, neither of which are particularly ideal or easy to pull off well.

**Comment by taukausanake** [comment]
You might be able to move out the Holodeck and put the arcade in there. Maybe even connect the maint tunnels there to it. Then you could have the Holodeck connect to it horizontally. Need to edit the areas to match it but doesn't /tg/ already have it like that?

**Comment by FalseIncarnate** [comment]
I really want to avoid touching the holodeck right now. That area of the station is already somewhat tight to work with, and messing with the holodeck would require more map edits on more levels.

One idea was to possibly swap it with Mr. Changs, but then Mr. Changs gets the issue of feeling "tacked on". The whole matter is being discussed still since we can't reach any sort of consensus on what exactly is wrong and how it can be fixed.

**Comment by Jovaniph** [comment]
I don't like the placement of where its located on the Cyberiad. For 1, it seems a bit isolated and could be merged inside the dorms, and 2 It would make remodeling Science a bit difficult in the future, which of course the same PR can do it later as well.

**Comment by FalseIncarnate** [comment]
After discussion with heads/maintainers, the Cyberiad arcade will be getting moved closer to the dorms. Since this involves messing with the holodeck's placement and surrounding maint, new pictures will be added once slotted in.

**Comment by FalseIncarnate** [comment]
Hope to have this updated this weekend, haven't had the chance to update yet due to other projects

**Comment by FalseIncarnate** [comment]
Merge conflicts fixed, original post updated to show new Cyberiad arcade location and surrounding changes

**Comment by tigercat2000** [comment]
Looks good to me

**Pull request merged**
