### PR TITLE
[DNM] Adds the PTC

### PR DESCRIPTION
**Pull request by AffectedArc07**
# What does this PR do
This PR adds the PTC, the power transfer crystal, inspired off of goons power transfer laser. The basic premise is that you can sell surplus power to CentCom, for extra cargo points. It has 4 base tiers, and 5 if you emag it. It was designed to look like a crystal instead of a laser for a few reasons, mainly because if we have an instakilling laser firing into space, its gonna make life for the pod pilot hard. The crystal will automatically shut down if there is not enough power (unless emagged), and will shut down if it is disconnected from a wire (even if emagged).

When emagged, an admin log is sent because this thing can become a full powersink
image
*Yes I know the wording sucks*

# Images of sprite/map changes
Map Change:
image

UI:
image
Also shows what power levels are available

UI (Emagged):
image

Crystal sprites
*Huge thanks to @Vivinet for these, please send them your love*
Crystal when off:
image

Crystal sending power at T1:
vMZw8R0HBH

Crystal sending power at T2:
dj7ZpPn21K

Crystal sending power at T3:
v4a2ZO3dIw

Crystal sending power at T4:
7961iNTpWU

Crystal sending power at T5 (Emag mode):
Lf5SWF0THN

# Changelog
:cl: AffectedArc07
add: Power Transfer Crystal - Sell excess power to CentCom for cargo points.
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
I see you changed the map, you probably want to include a picture of the changed map.
Also, can it be destroyed/deconstructed?

**Comment by AffectedArc07** [comment]
@TDSSS shhhh

**Comment by Kyep** [comment]
A few questions:

- How is this balanced with regards to cargo points? Currently people set up the tesla and just leave it every round. Doing that, and setting this to a high value, would mean LOTS of effectively free cargo points.

- You say this can act like a power sink on the highest setting. Does that include draining APCs, SMESes, etc? Or do you just mean it takes all the power in the grid? What's its power priority? If there isn't enough power in the grid, will this charge first, last, or in a random order?

- Why place it in a hidden room in maint, outside Eng?

- Is there any reason to adjust the setting on this thing during the shift? Or is it set-and-forget?

**Comment by AffectedArc07** [comment]
@Kyep 
- It was hard to balance with cargo points due to the issue with cargo points being a very strong currency. If cargo was like TG cargo using station balance, this would probably balance a ot more.
- It only drains APCs, and as for priority, I do not know yet
- Its in a hidden room because this makes sense, and it could be useful for traitor QMs
- The SMES maxed only output 600KW, so for this to be usable fully it would require engine tweaking, and probably monitoring. If you set it lower, it is set and forget

**Comment by Citinited** [comment]
1MW is really nothing when the roundstart engine pumps out nearly 2MW.

Likewise for 100kW - you could set the crystal to drain 100kW at roundstart and nobody would even notice. I'd definitely look at rejigging those numbers.

**Comment by AffectedArc07** [comment]
@Citinited I aint good with numbers, but if you got ideas then please do suggest

**Comment by AffectedArc07** [comment]
And this also borked my `paradise.dme`. Again. I even added the file with the DM client. @variableundefined Any ideas?

**Comment by Kyep** [comment]
@AffectedArc07 
- I think you may need a way to rebalance cargo points in this PR, then. Otherwise having this added just makes cargo points meaningless because easy power from the engine + this = as many points as you want.
- Putting it in a hidden room only accessible via maint doesn't really make sense when its the most power-hungry machine on the entire station, responsible for part of the station's budget, and so forth.  I realize mapping it into Eng may be tough, but I think a machine that does this much deserves a room. 
- For this to be fully usable, it requires science to upgrade SMESes to output more power?

**Comment by AffectedArc07** [comment]
@Kyep 
- Again, if someone who is better with numbers wants to help I will appreciate it. If the station had a bank balance itself, that is what this would pay into
- I feel like I could do that, but I need help actually mapping that in, might ask free
- Yes, but that means that science have slightly more to do

**Comment by TDSSS** [comment]
- For this to be fully usable, it requires science to upgrade SMESes to output more power?
Or just, you know, hotwire the engine. Or run a hotwired connection to that specific room while leaving the rest of the station on normal SMES power.

**Comment by Vivinet** [comment]
Hey guys, trash spriter here.

@AffectedArc07

Here's some of my thoughts on the PTU since you had come to me for artwork. So far all the criticisms are valid, but not too difficult to fix!

Personally, I think the table room to the right (displayed in the first screenshot) should be converted to look like it's part of engineering, and the PTU placed in there. There's a lot of wasted space, and it is directly connected to engineering.

As for the power draw - cargo point comment, I think the power draw should be incredibly high while the points gained are relatively low until you hit level three. To keep the math simple, I think each power level should draw 1/5th of the total average power output that engineering can generate without having to resort to homebrew methods (like creating a SME, more solars, etc.). As for the points gained per level, I feel as though it should be: 1, 2, 4, 8, 16 points per minute, making it not really worth while to use at the lower levels, but making higher levels something worth trying for.

Just my 2¢, hope this helps!

**Comment by datlo** [comment]
I am about 99% sure that this room is where the SIT shuttle lands on the engineering entry spot and the shuttle would crash in it. This is obviously an issue even if the SIT is rarely used.

**Comment by AffectedArc07** [comment]
@Vivinet will probably end up doing the points, and possibly the remap too

@datlo I saw a docking port, but it was labled "Engineering Shuttle", so I just assumed it was horribly offset, now you mention this, it should be moved

**Comment by Fox-McCloud** [comment]
>not using Goon's Sprite

>>not having a crazy death laser that sets you on fire and dusts you if it's powerful enough

Shame. Shame.

**Comment by KasparoVy** [comment]
Power drain the station by sending all power to the crystal hahahah

**Comment by Citinited** [comment]
@AffectedArc07 I think Fox sort of covered it but I'd suggest starting at like 5MW for 1 point / minute (because you have to actually do work to get to this level), then like +1 point every time you double that (so 10MW = 2 points, 20MW = 4 points etc.)

**Comment by AffectedArc07** [comment]
@Citinited Youre aware that the APCs overload and shock everyone at 5MW? You may want to re-think your values?

**Comment by Dave-TH** [comment]
@AffectedArc07 Correct, 5MW into the grid. Not 5MW into the SMES units or hotwired into the PTC.

**Comment by AffectedArc07** [comment]
@Dave-TH The Tesla makes 2.5MW, and the engineering APCs are fed off of the engine directly. I will probably make the crystal run off the engine instead of the grid though

**Comment by AffectedArc07** [comment]
Things that make me feel like closing this:
- Its hard to balance with cargo points
- Its overpowered no matter what
- Its set and forget
- It should be better remapped

Things that are making me keep this open:
- Vivi spent time doing sprites and I feel bad

**Comment by taukausanake** [comment]
To be honest, maybe Cargo needs a revamp as well, if not for this PR then for itself

**Comment by Dinarzad** [comment]
I feel this is potentially a really good idea and a good mechanic for both Cargo and Engineering and those two departments also having some more interaction.

However. I also feel that to properly implement this, will require a lot more work, primarily a more thorough overhauling of how our cargo system functions and perhaps some tweaking to engine power outputs as well so that it's not quite so easy to get massive power outputs, an makes Engineers get creative, or provides a more tangible reason to order a supermatter crystal or TEG.
Cargo working off of the station's budget and not it's own nebulous point system also seems like a bit of a must with this system in place.

Problem being all of these are going to need their own PRs an some of them are gonna be pretty big ones and controversial ones.  So perhaps it's better to tuck this idea away for now,and even if it doesn't come to pass, these sprites could see use elsewhere.

**Comment by davidchan13** [comment]
I like the idea of excess power having a use and cargo having more options to make 'money' ontop of some meaningful interaction with engineering beyond "Here is today's shift project, miners put metal in the ORM. Bye."

What I dislike is that this is basically 0 effort for both departments. Our engines don't have enough variance in their outputs (peaks and lows) and there is relatively little danger in running the engine at high outputs since Tesla can not break free on it's own and singuloth can only break free if it absorbs enough energy to get to phase 4.

Aside from completely rehashing how Engineering operates (which is something I'd love to do but is so far outside of the scope of this PR) I'd suggest an alternative of moveable battery banks that could be built or ordered, something akin to a SMES on wheels that could be charged up and exported for points, or kept around as an emergency backup battery.  Conversion rate would have to be reasonably, 1 point for a few MJ of energy (bear in mind a bluespace power cell is only 40KJ and a typical Singulo/Tesla setup starts between 1-2MJ output)

The problem I foresee with that is Engineering has very little they can get from cargo they can't just get from science, so few would be willing to do the footwork to acquire, assemble and export the power for points. Cargo doesn't have many toys engineering would want to play with they don't already start with, so we'd need a companion PR with an expansion to cargo and things only they can acquire that departments would desire to improve their job, and thus encourage cooperation and export of excess goods to afford them (I'm looking at you Botany.)

**Comment by Kyep** [comment]
In order for me to support this PR, it would have to not be mapped in. The code for it could be added, so that people could work on balancing it and doing a more general re-work of cargo points with it... but it can't be mapped in yet. That also assumes no other major bugs/etc with it, and the only issue is balancing power use / cargo points.

**Comment by MrMagolor** [comment]
Yeah, I mean, completely rebalancing Cargo and Engineering (and maybe even Science) is definitely beyond the scope of this PR.

**Comment by AffectedArc07** [comment]
Closed because:
- Its hard to balance with cargo points
- Its overpowered no matter what
- Its set and forget
- It should be better remapped

Sorry Vivi. Might try make something with these sprites, but theres no promise. ;=;

**Pull request closed without merging**
