### PR TITLE
Makes Permabrig Plasmamen and Vox proof

### PR DESCRIPTION
**Pull request by FreeStylaLT**
By "cleverly" making windows directly inaccessible without tools or external help.
Before:
img

After:
img

I do realize that this may be too much or otherwise redundant considering the recent-ish glass shard changes, but I always wanted to juggle this idea around.

🆑 FreeStylaLT
tweak: Shuffled Permabrig's windows around in a way that prevents non-assisted escape.
tweak: Tweaked permabrig's internal layout slightly.
/🆑

### CODE REVIEW

**Comment by Xantholne** [comment]
Wait did you thumbs down your own thing

**Comment by sothangel** [comment]
I'm not sure how I feel about this. This does effectively make permabrig unescapable for basically everyone now.

Also, does the table with the bedsheets on actually restrict access?

**Comment by SirBloodBuske** [comment]
Unless you have tools, you won't be able to move most of the things out of the way.

**Comment by taukausanake** [comment]
Bravo
Bravo good sir. Bravo.

However I do agree with @sothangel even though most breakouts will be done by a third party from the outside. All because it's permabrig doesn't mean people _shouldn't_ be trying to get out, at least from an IC point

**Comment by SamHPurp** [comment]
This is not the way to deal with this.

**Comment by FreeStylaLT** [comment]
@SamHPurp Why do you think this is not the way to deal with this? Do you have any other solutions in mind, at least map-wise?

**Comment by granodd** [comment]
You can still climb onto the table that has the laundry basket to break the window there. Also I don't know if you can climb onto the game table or not, but there as well.

@SamHPurp How do you propose a fix? The alternatives to this is "No windows at all", "Special rooms specifically for Vox/Plasma Men", or the already executed (albeit poorly so) "Just Execute them".

**Comment by FreeStylaLT** [comment]
"Fixed" the basket issue:
img

**Comment by AffectedArc07** [comment]
I do not like this idea.

**Comment by Necaladun** [comment]
Please don't comment with your like/dislike etc without reasons. The thumbsup are there for that. 

While this serves to fix the problem of vox/plasmamen escaping easily, it does this at the cost of other prisoners escaping without at least a wrench. I don't like the idea of all other races being stymied because of those two (oh and dionas derp). I think them being thrown in solitary is acceptable atm compared to stopping escape for everyone else.

**Comment by Tayyyyyyy** [comment]
I think, IC wise, Nanotrasen, being a human company, probably would have designed their prison without thinking about spaceproof species. Part of playing sec is having to deal with the various situations that come up, including dealing with species diversity. And part of selecting vox at character creation is that you know a competent security team will take more measures to secure you, in exchange receiving massively increased freedom of movement. Making everyone permabriggable is sort of just a fire and forget solution that removes some of what makes living on a station with a bunch of different alien species interesting.

**Comment by SamHPurp** [comment]
@Necaladun Provided deeper suggestions and theorycrafting is not what a Github thread like this is for. Its for commenting on the proposed solution.

I am against this because this aesthetically makes it look terrible, this utilises 'oversights and silly shit' to stop it. As an example, one of the blockers is a chess board. Because its not been coded that you can climb onto them, even though you totally should. Same again with a washing machine. These aren't large things. This is not the right solution.

As for the right solution, I don't know. But if you like, sure, lets think out loud.

Plasma/voxygen tanks that only work within a tile radius of a 'hub', and install that hub in Perma.... think Wifi internals. This'd require anyone coming to break them out, have to get replacement internals.

Internals that you can rig up to an assembly/signaller to be able to remotely disable them.

Are these the right solution either? Maybe not... but I do not support the proposed one, even actively detract from it.

**Comment by Birdtalon** [comment]
I don't think this is a good idea just because this change, while meaning that spacefaring races cannot escape permabrig as easily, you are also making it impossible for anyone to escape it without help or more likely without prior preparation. I think there should be at least an option for a skilled person to escape the permabrig solo without having to make false walls everywhere first,

**Comment by Anticept** [comment]
Just let us execute the vox and plasmamen so we don't have to deal with them. They chose that race And also get their drawbacks.
/meme

Anyways, make a plasma /vox breather that they have to drag around. Something too unwieldy to be able to pick up and hit glass with.

**Comment by granodd** [comment]
Well chances are if you didn't have any outside help to begin with and you got thrown into perma, you're likely not getting out. This might even give some traitors the incentive to go help others who are trapped in perma with the knowledge that they'd be stuck there without them, unless of course the person in question somehow robusted an officer and then worked their way from there.

Another option is to have a larger solitary cell that's designed specifically for vox/plasma men that has no windows at all while keeping the current perma as it is.

**Comment by taukausanake** [comment]
> solitary cell that's designed specifically for vox/plasma men

That's racist. Also I doubt NT would bother with such a prison. They want their threats just contained, not necessarily comfortable

**Comment by Xantholne** [comment]
You know you could put it as the thing before with the table and bedsheet basket where you could climb on as a break out point. It'll require you to use your noggin more on the one viable interior way to escape.

**Comment by jughu** [comment]
This will be all a joke anyways when this damage tg refactor is done anyways

**Comment by granodd** [comment]
@taukausanake How is that racist? It's not saying "Vox and plasma men are beneath us!" No, it's being practical and putting them in a room where they can't use their required internals tank as a blunt instrument to break windows. They can't break windows in a room where there isn't any, and we already have solitary. The suggestion is to make another one that's bigger, or to make the already existing one larger, which arguably is a QoL improvement as the room as it is is only 2x2 at the moment.

**Comment by Spartan6** [comment]
I really don't understand the hate for this.

When you are in perma, you've essentially already lost, you've been caught, tried and prosecuted. You have been an antag and you have failed and have to hope for a miracle to continue. But now you have to push so hard or try and loophole the law to favour you, because then security will always push to execute because perma is perhaps even easier to escape from than a normal cell.

Especially now with perma being further away from the heart of brig (so would take longer if they even managed to spot something happening), something needs to be done.

It is still easier for space faring to escape. Fuck, my vox can escape there in under a minute flat easily. If you want truly for the execution to be a less spammed option, you need to make perma viable. A friend can break another friend out of perma just fine still, which is how it should be.

**Comment by SamHPurp** [comment]
@Spartan6 the rules around executions have changed in the last few days, ensure you are up-to-date with them...

**Comment by Spartan6** [comment]
I am up to date with them, but this had to be changed because perma was so piss easy to break out of.

**Comment by sothangel** [comment]
If, somehow, there could be a sort of randomised method of being able to escape from permabrig (The neccessary tools or special items to facilitate escape) hidden in random places, I could support it, perhaps.

So say, adding some used chewing gum found in a vent to a metal rod could make a very shitty ghetto screwdriver, one time use that you can use to pry something open which might lead you to the next thing, etc etc blah blah. But that's outside of the scope of the PR.

Ultimately, I do not want Permabrig to become the endzone of the majority of antags where nothing happens from there.

**Comment by SamHPurp** [comment]
@sothangel every round, warden's would just come in and remove these because they knew about them via meta-knowledge.

**Comment by Spartan6** [comment]
All it takes is prior preparation and you can very easily still escape.

**Comment by sothangel** [comment]
Kind of hard to prepare priorly if you get all your gear removed when you actually get permabrigged.

And yes that would be a concern, but I can't really think of anything that appeals to all parties.

**Comment by Spartan6** [comment]
Well it's not hard to prepare. Bluespace implants, leaving gear planted in perma, experienced traitors can break out of it with ease. Make redundancies and don't be surprised that when you get thrown in a cell that you suddenly can't escape it. 

Fail to prepare, prepare to fail.

**Comment by granodd** [comment]
@SamHPurp With the recent changes to executions, Vox/Plasma Men are expected to be stuck into perma more often now, as executing them on the basis of "cannot contain" is now a punishable offense in the rules. By extension that's beneficial to them because now they hold an advantage if you decide to place them into Perma instead of Solitary. Or if you decide to place them in there without closing the blast doors to their cell and just not letting them near the windows. May as well keep Perma a level playing field for the prisoners.

**Comment by deep-fried-faceplant** [comment]
If the purpose of this change is to reinforce permabrig, so that space-worthy races can't just bust out, why not just add another solitary cell? While I am in favor of making permabrig harder to break out of without outside help (If there's a reliable way for people to break out, they will use it every round without fail, regardless of skill), @SamHPurp does bring up a good point that most of the items that block the windows should be climbable. Not being able to scoot around a chessboard seems silly.

**Comment by FreeStylaLT** [comment]
Closing this due to it being, well, unwieldy from a design perspective.
I have _other plans_ that could be used to solve this.

**Pull request closed without merging**
