### PR TITLE
Public Senõrgi Cyborg Sprites

### PR DESCRIPTION
**Pull request by The-Driker**
Due to popular demand after submission of my personal burger sprites, I bring you 
THE SENÕRGI MODULES!

We here at **Chef Excellence**, come to you today to continue our neverending task of bringing you the products you love and deserve. After extensive research and information provided to us by _the syn-_ various crewmembers working for Nanotrasen through the galaxy. It has come to our attention that you wonderful people love corgis. You just can't get enough of the wonderful little balls of fluff! So much so that we constantly hear reports of your various cargo crews across the system requesting shipments of them. 

So we say, why order live animals that you have to feed, bath and clean up after? When you instead could be enjoying our newest line of **completely inoffensive robot frames**, designed specifically for you dog lovers out there! Never again will you have to worry about whether that corgi you own loves you or not when you can simply program it to! 
`Chef Excellence guarantees that none of our robotic Senõrgi modules will attempt to swallow crew.`

 
ezgif com-resize 1

- [The Frisky Fixer] Whether repairing a hole in the station or that hole in your heart, you can always count on him to be there. 

ezgif com-resize 2

- [Deputy Doge] Very stern, much arrest, bark[Due to limited frame space, it's disablers are built into it's eyes. You're welcome]

ezgif com-resize 3

- [The Miracle Mutt ] Whether patching up skinned knees or dragging a drunken patreon to the medbay. You can always count on this unit to do what your doctors wont! [Aka their job]

ezgif com-resize 4

- [The cuddly cleaner] Whether this unit is chasing mice or eating leftover food off the floor, you can count on him to keep your station clean. 

ezgif com-resize 5

- [The Siesta Senõrgi] 

From napping in the bar, to rolling around on the bridge floor, you'll never find yourself for wanting company with this completely culturally appropriate borg by your side. 
ezgif com-resize 6

- [The Emergancy Cuddle Senõrgi] When things have hit the fan, the station is on fire and you are in desperate need of a hug. The ECS will be there for you! 

ezgif com-resize 7

**We at Chef Excellence will continue to strive to bring you products that are safe and inoffensive to crews across the galaxy and hope that we can continue our long, prosperous relationship.** 

`Chef Excellence and affiliates takes no responsibility for property damage or death due to malfunctioning synthetic handymen. Any and all supposed affiliation with crime syndication’s is completely non-existent, and such claims will be dealt with to the full extent of space law.`

### CODE REVIEW

**Comment by SigholtStarsong** [comment]
... This is so lite RP it might actually float away.

**Comment by Xantholne** [comment]
I lost it at the deputy doge 👍

**Comment by Birdtalon** [comment]
I think they're actually quite funny and considering they're only sprites it's an 👍

**Comment by Fruerlund** [comment]
Too much for me. The sprites are awesome and I'd love to see your more **serious** work aimed at some more standard / med RP.

**Comment by The-Driker** [comment]
@Fruerlund What?

**Comment by The-Driker** [comment]
doge

Just a look at what giving them a bit more color coding would look like. Not sure if this helps or not, but I figured I'd put it out there.

**Comment by karmapay2win** [comment]
If only one player runs around in these I could ignore it easier, if everyone will I will be hard.

**Comment by alexkar598** [comment]
Love all the sprites with exception of the medical one it dose not seem like a medical one

**Comment by SamHPurp** [comment]
These look amusing sure... do they have a place on the server in my view/mind? No.

**Comment by The-Driker** [comment]
corgibots

I went and made some adjustments. 
So far it seems the majority doesn't like them, but here's the updated look none the less.

**Comment by Taaketa** [comment]
Give the Engineering dodge a hazard vest.

Also, no mining Dodge?

**Comment by The-Driker** [comment]
@Taaketa Oh wow! I completely forgot about the mining module. I'll put one together now.

**Comment by Spacemanspark** [comment]
I don't really feel this fits the server, sorry. Gave me a good laugh though.

**Comment by The-Driker** [comment]
@Taaketa How about these?

mining and engineer

**Comment by Necaladun** [comment]
Absolutely adorable, but too far out from the theme of borgs in general and just a bit too silly.

**Comment by scrubmcnoob** [comment]
You're a really good spriter though don't know if this is suited for us.

**Comment by taukausanake** [comment]
I think I'll take this over #7579 actually

**Comment by Cactus2388** [comment]
Love the idea, Secorgi needs a darker hat to differentiated from the corgi's body a bit better. But either way +1 from me! I love chef excellence products.

**Comment by deep-fried-faceplant** [comment]
These look fantastic, but like what others have already said, are just too silly for Paradise. I'm okay with being goofy, but I draw the line at getting arrested by a Mexican Corgi McSecborgi.

**Comment by LightFire53** [comment]
WhIle I love these, and would absolutely use them for admin abuse, its just way too out there to have standard in game.

Although, if they were used for the gateway at the wizard hotel as some sort of NPC staff/robot thing....

**Comment by ZomgPonies** [comment]
Someone will probably pay you for these to be able to use them as a fluff item, which we would allow. So they wouldn't go totally to waste....just not public.

**Comment by The-Driker** [comment]
Thank you everyone that commented. I'm closing this as it's now clear that they just wont fit in with the setting.

**Comment by Taaketa** [comment]
Add them in as Fluff item! I never took a Fluff one but I'd takes these!

**Comment by taukausanake** [comment]
I was literally serious when I said I'd take these over the cyborg dogs. That PR is not going anywhere any time soon even though I support some implementation of it. Besides, I think robo corgis fit our style

**Comment by The-Driker** [comment]
@taaketa if you're a Paradise Station donator, and you want these as your custom cyborg skin, I'll gladly make a pr of it for you. Also if there's anything you want changed, let me know.

**Comment by optimumtact** [comment]
@The-Driker can I use these sprites for a pr on /tg/ station?

**Comment by The-Driker** [comment]
@optimumtact 
I don't mind, just note where they came from.

**Pull request closed without merging**
