### PR TITLE
Adds head patting

### PR DESCRIPTION
**Pull request by Robertha89**
Helpfull intent
aim head
click person to pat
Pat pat
:cl: PPI
rscadd: Adds head patting
/:cl:
Re-make of #3534

### CODE REVIEW

**Comment by NTSAM** [comment]
Head Pats 3: Ecletic Pataloo

**Comment by Iamgoofball** [comment]
as stated in the last PR, literally useless

:-1:

**Comment by NTSAM** [comment]
We have tons of useless features. Pretty much any emote is useless, but we won't remove most of them.

**Comment by Iamgoofball** [comment]
So that's an excuse to add more?

**Comment by NTSAM** [comment]
:\

**Comment by DaveTheHeadcrab** [comment]
There's no reason for this to be integrated into help intent actions.
Just make it an emote.
*pat-target

**Comment by NTSAM** [comment]
remove hyperboles, they confuse me

**Comment by Yukiona** [comment]
I like it :+1:

**Comment by CrAzYPiLoT-SS13** [comment]
SS13 is useless in everyone's lives. Should we remove it because of that,
@Iamgoofball?

**Comment by DaveTheHeadcrab** [comment]
@CrAzYPiLoT-SS13 
Once again. Hyperbole.

**Comment by TheDZD** [comment]
@Robertha89 Converting this to an emote like @DaveTheHeadcrab suggested might be a good idea, but I'll leave that up to you.

**Comment by Fox-McCloud** [comment]
I second @TheDZD statement; this would probably be best reserved as an emote--kinda slipped my mind.

**Comment by Gummin** [comment]
True, I kind of agree.
But if that's the case, can't we just press F4, and type "pats Nar'Steve the Ian Overlord the Second on the head." ect?
But there could be something special to it I suppose, like when you scream or slap.

**Comment by Robertha89** [comment]
while making it an emote seems somewhat reasonable, i mean, slap is mostly used for slapping yourself, thus putting pat in the same boat, would just by adding something that would not be used, and going the emote route, why not just me it, basically to simplify it. It's easier to do, everyone can do it, it brings no negative sides, and promotes rp. i mean *slap-super complicated name, i'd rather it be like this in it's simplicity.

**Comment by Spacemanspark** [comment]
I kinda like it the way it currently is.

**Comment by Gummin** [comment]
Yeah, I would prefer it to be the way it is now.

**Pull request merged**
