### PR TITLE
Emergency patch, fixes asset_cache interfering with verbs

### LINKED ISSUE #2834: OOC and ahelp verbs
When joining the server after round ends, or just joining in in general, the ooc and ahelp verbs take forever to load they usually appear at 80 seconds left in the round count down. probably caused by #2824

### PR DESCRIPTION
**Pull request by tigercat2000**
(probably) fixes #2834 
I am 99% sure this is the reason
however I can't reliably test connection delay on a local system
sooooooooooooooooooooooo
worst that happens is that NOTHING CHANGES! whoo #tigerworstcoder2015

### CODE REVIEW

**Comment by NTSAM** [comment]
THAAAAAAAAAAANK

:clap:

**Comment by orelbon** [comment]
#tigerforpresident2k16

**Comment by Fox-McCloud** [comment]
tested---appears to work.

**Comment by tigercat2000** [comment]
good nuff
now someone stab mel and ponies

**Comment by orelbon** [comment]
just noticed that branch name lol

**Comment by Tastyfish** [comment]
nice

**Pull request merged**
