### PR TITLE
Slip staff removed

### PR DESCRIPTION
**Pull request by Nazsgull**
## What Does This PR Do
Removes Staff of Slipping from Lavaland Clown ruins and adds a DNA injector (comic) there.

## Why It's Good For The Game
Balance reasons.

## Images of changes
staffOSlippOff

## Changelog
:cl:
add: DNA injector (comic) at Clown ruins at Lavaland.
del: Staff of Slipping from Lavaland Clown ruins.

/:cl:

### CODE REVIEW

**Comment by shmabuu** [comment]
Improve don't remove.

**Comment by shawnhind** [comment]
If it's too annoying as it is, I think it'd be cooler to just nerf it and give it a cooldown or a limited number of charges rather than removing entirely.  I don't personally see it get overly abused too often and when it does it tends to get confiscated by sec fairly quickly.

**Comment by Carthusia** [comment]
I'm with shambuu on this, while it can be annoying, change the staff then, improve the ruin then, its best not to simply remove it and slap a temporary solution on it, as removing an item people WANT, with one they DONT, and can obtain via genetics, is far far less fun for players who make their way through the clown maze

**Comment by Mitchs98** [comment]
Why, though? Just because something is 'annoying lately' isn't a valid reason to remove something. The times I've played I've rarely seen it 'abused' in any fashion, and simply used to vaguely annoy people or between friends to have fun. And I've been quite active up until recently.

If it is genuinely _that_ much of a problem making a lavaland variant with less charges or etcetra is a far better idea than removing a fun somewhat gimmicky item and replacing it with an injector you can easily get from genetics if you want it.

I'm aware some items on lavaland are overpowered, but there's a difference between nerfing an item and exchanging it for something utterly useless and making yet another pointless area somewhere, and frankly out of every single item on lavaland the slip staff is by far the least annoying and overpowered thing you can get there that's commonly gathered.

**Comment by MRgaty** [comment]
It always has been a big annoyance whenever someone found it in my experience and most of the times it has been used to mess with random people for no reason.
We're better without it.

**Comment by Nazsgull** [comment]
I heard you guys. I thought this was going to be met in a different way, I did not know so many people wanted the staff there... It will stay there but will be harder to get and have fewer charges. Middle ground.

**Comment by Mitchs98** [comment]
I'm a bit confused by the code. It has 5 charges but has a max_charge of 1?

**Comment by SteelSlayer** [comment]
Not every ruin needs to be jam packed full of fun and useful items. Remember the old asteroid? Yeah, that had hardly any loot compared to lavaland. There's really no reason to have all of this combat-related loot for miners anyway. It always ends up being brought on station and fucks with the balance of the game. 

But of course, lavaland has been around for a while, and everyone is used to all the new powergamer toys. Trying to take them away is going to make some people mad, that's just the way it is.

@Nazsgull Reminder that you do not have to listen to anyone if they're not a maint or head. So, I suggest you stick to the total removal, and see what they think first. Or not, your choice.

**Comment by Mitchs98** [comment]
For the record; Idon't even play miner, I have no personal stake in this. I just see no reason to outright remove it when there's many other glaring items on lavaland that _aren't_ fun and gimmicky that are a much bigger problem.

**Comment by Spacemanspark** [comment]
Should have just stuck with removing it, frankly.

**Comment by procdrone** [comment]
I personally agree with the removal. Staff of Slipping is a very powerful magic artifact, that is because its designed to be useful to a wizard whos goal is to combat the whole station.

That means, balance wise, the staff is incredibly OP in every situation. Now add to the fact it can stun anyone, even borgs and has no real counterplay - during a normal round it makes things very unbalanced. Imagine a sec officer with no drop using this to fight changelings or traitors. Or just traitors having infinite instant stun on top of other powerful items brought from Lavaland.

Just to point out, Lavaland was ported from TG and most of the balance applies there due to how their rounds go. In most cases this balance fails when meeting station balance. (we've all seen the miner antags being able to take on whole crew and come out on top)

And having wizard items which generally are quite OP available to crew/miners in my personal opinion shouldn't be a thing.

**Comment by MRgaty** [comment]
Also the "improve dont remove" thing does not contribute very much to the PR so yeah, better go ahead and wait for the maints and heads response, dont worry bout possible negative feedback from the community for now.

**Comment by Nazsgull** [comment]
I get that community feedback is important but balance should come first. I intend to remove the staff not because I find it annoying but because I want to balance the game (and yes, I wrote "has been annoying lately" but that was because I was in a hurry and could not elaborate at the moment the PR was published).

**Comment by GentleManners** [comment]
Make it unusable on the station maybe?Or maybe just remove the entire ruin now that its only a waste of space, too many of those

**Comment by Denthamos** [comment]
This and a few other items from lavaland which essentially/directly wizard class items have always been running on that line of being abused too easily in certain ways.  The clowns staff, the healing staff, and the tarrot cards do highly impact gameplay.  The mining scarab eggs I was more okay with due to the clear distinction sprite wise while the tarot cards guardian sprite is the wizard guardian sprite which is known EOC.

Something I have been considering with this item in specific, the clown staff, is that to use it you _have_ to have either the wizard or clown flag in the mind datum for the mob.

**Comment by Carthusia** [comment]
If the staff is set for removal, perhaps somthing a bit more tangable then for the reward than a clown accent syringe?

Fancy clown robes and mask, gold clown shoes that have a different pitch of squeak and have no slowdown. Stuff like that where the reward, while not an advantage like the staff, is still a fun little reward.

Perhaps the reward could be:

Fancy clown mask, fancy clown robes, gold clown shoes with a different squeek sound and normal walking speed, a book of Honk (Just a clown bible) , and a clown accent, basicly your reward is an outfit and items to RP a preacher of honk.

**Review by Kyep — APPROVED** [review]

**Comment by AffectedArc07** [comment]
Not in favour. The staff has already been nerfed and this just makes the ruin boring and not worth exploring.

**Comment by procdrone** [comment]
> If the staff is set for removal, perhaps somthing a bit more tangable then for the reward than just the clown accent syringe?
> 
> Fancy clown robes and mask, gold clown shoes that have a different pitch of squeak and have no slowdown. Stuff like that where the reward, while not an advantage like the staff, is still a fun little reward.
> 
> Perhaps the reward could be:
> 
> Fancy clown mask, fancy clown robes, gold clown shoes with a different squeek sound and normal walking speed, a book of Honk (Just a clown bible) , and a clown accent, basicly your reward is an outfit and items to RP a preacher of honk after braving the prank filled halls of the clown dome.

and propably some spare bananium to make a honk mech.

**Comment by Kiyahitayika** [comment]
> I get that community feedback is important but balance should come first. I intend to remove the staff not because I find it annoying but because I want to balance the game (and yes, I wrote "has been annoying lately" but that was because I was in a hurry and could not elaborate at the moment the PR was published).

I find trying to re-balance things almost fun. It's hard, but it's fun in the way that you can get so many people from the community involved.

I hear you on not getting the feedback you expected. Sometimes the people you talk to aren't the same people who review. Or they change their minds or who knows? I am pretty big on sharing my stuff in the Discord and I love getting feedback from folks. Sometimes it hurts and I can feel a bit dumped on, but I try to bounce back quickly. Some people offer up intentionally silly ideas and they make me laugh! Others sometimes have more "sane" and "reasonable" suggestions xP Paradise is a fun community at its heart.

**Comment by variableundefined** [comment]
Objection on the same ground as Affected, closing.

**Pull request closed without merging**
