### PR TITLE
Fixes cyborg bolting so it is no longer instant. Again.

### PR DESCRIPTION
**Pull request by Adrer**
## What Does This PR Do
Makes it so that cyborgs can no longer instantly bolt doors, unless emagged or malfunctioning, as intended in #22084
fixes: #22278

## Why It's Good For The Game
It'll work completely, for sure this time, I swear.

## Testing
Be a cyborg
Try and bolt a door, it takes 3 seconds
Add the "syndicate" faction to my faction list
Bolting is now instant

## Changelog
:cl:
fix: Cyborgs can no longer instantly bolt doors unless emagged or malfunctioning.
/:cl:

### CODE REVIEW

**Review by DGamerL — APPROVED** [review]
Third time's the charm!

**Comment by Fordoxia** [comment]
The cyborg bolt timer is an absolute pain and I do not agree with its (re)addition. They can't instantly jump around the station like the AI can and really shouldn't be getting hit by a nerf that is addressing a problem mainly caused by AI.

I would suggest -at most- applying the timer specifically to the AI.

**Review by Fordoxia — CHANGES_REQUESTED** [review]
Have bolt timer only apply to AI. Cyborgs cannot immediately jump halfway across the station to bolt someone in a room.

Cyborgs also have to physically navigate through the environment, including through bolted doors on occasion (especially when going through external airlocks) and will be slowed down by having to babysit a door until the timer is finished.

**Comment by Henri215** [comment]
> Have bolt timer only apply to AI. Cyborgs cannot immediately jump halfway across the station to bolt someone in a room.
> 
> Cyborgs also have to physically navigate through the environment, including through bolted doors on occasion (especially when going through external airlocks) and will be slowed down by having to babysit a door until the timer is finished.

This is a change for another PR, dont request it to be done here.

**Review by SteelSlayer — APPROVED** [review]

**Comment by GDNgit** [comment]
> The cyborg bolt timer is an absolute pain and I do not agree with its (re)addition. They can't instantly jump around the station like the AI can and really shouldn't be getting hit by a nerf that is addressing a problem mainly caused by AI.
> 
> I would suggest -at most- applying the timer specifically to the AI.

This is a fix pr, the burden of making this change is on you, not the author. 
I would generally suggest against using the request changes feature for comments like this.

**Pull request merged**
