### PR TITLE
Phantasmic Dreams Victorian Clothing

### PR DESCRIPTION
**Pull request by Aurorablade**
Coming to a autodrobe near you:
Victorian suits (Red, Red/Black, Black)
Victorian Dresses (Red,Black)
Tailcoats
Victorians Ladies Coats(red,black)

Ingame sprites(Note I hade a bug with the black dress this one..so i got it fixed):

Sprite Editor previews:

(Note:I still think Dreamy needs a unitard version of the vest suit)

:cl: Code Fethas and Sprites Phantasmicdream
rscadd: Fancy Victorian Clothes
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Thanks for keeping up species sprite parity.

**Comment by Aurorablade** [comment]
Its why i don't have a shot of the blackdress fix up..its late and i got frusterated setting up the first shot.

**Comment by Aurorablade** [comment]
Obligatory Vox in a dress:

**Comment by HereticChurch** [comment]
Gonna class up the station a bunch. Awesome.

**Comment by Necaladun** [comment]
CLASS BLAST USA
(lovely, :+1: )

**Comment by Dinarzad** [comment]
Gotta be a dapper chapper.
Now station MVPs can have a proper butler.

**Comment by PhantasmicDream** [comment]
Worry not @kasparoVy I edited up the sprites to fit the different body types of the respected races that have the different body types, and only went partly insane.

**Comment by Ralta** [comment]
VOX IN TAILCOATS YEEEEEEEEES.

Now if only I could get some of these as a loadout option...

**Comment by ModDownloading** [comment]
I love Victorian style, so I of course approve! Admittedly, I will stick to wearing my trenchcoat still, but I do appreciate this garb as an option.

**Comment by Dinarzad** [comment]
I will probably use these to make a Glitch-esque IPC who dresses in Victorian outfits and constantly speaks in the olde tongue.

**Comment by SamHPurp** [comment]
> Ingame sprites(Note I hade a bug with the black dress this one..so i got it fixed):

Its still bugged, on live server right now.

**Pull request merged**
