### PR TITLE
Fix: invincible computer frames / hostile NPC cheese

### PR DESCRIPTION
**Pull request by Kyep**
Currently, computer and machine frames are invincible, and ignored by hostile simple_animals because of this.
This enables you to use them as indefinite cover from hostile NPCs, as well as potentially trapping the NPCs by placing frames around them.

This PR modifies them such that they can now be destroyed - by animal attacks, explosions, and regular projectiles. When they are destroyed, they drop their base material (typically metal), wiring (if wired) and circuit (if one is installed).

This PR also modifies simple_animal AI such that if an NPC is trapped, and it is trying to destroy its surroundings to free itself, it will now damage adjacent frames.

:cl: Kyep
fix: Computer and machine frames are no longer invincible, and can now be destroyed by hostile NPCs.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Does this affect the invincible holodeck computer?

**Comment by Kyep** [comment]
This only affects frames, not built computers.

**Comment by Birdtalon** [comment]
While I can't argue against making things destructible (everything should be imo). It's a shame this removes one of the few ways of dealing with AI mobs.

**Comment by Kyep** [comment]
Update: this PR now also applies the same rules to machine frames. IE: they can be destroyed, drop the same stuff when they are destroyed, and angry NPCs can destroy them.

**Comment by KasparoVy** [comment]
Fantastic

**Pull request merged**
