### PR TITLE
Makes firelocks more lethal

### PR DESCRIPTION
**Pull request by Markolie**
As discussed in https://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=9898.

Firelocks are now more lethal: it takes thirty seconds to open them by hand (you can't move) and it will autoclose in five seconds if there's still an air alarm present. It will also crush players that are standing in the firelock when it closes. Firelocks can no longer be closed by hand.

Heavy firelocks (constructed using plasteel, on the map by default) can not be forced by hand.

If an airlock is hand-attacked with the help intent (and isn't a heavy firelock that doesn't have glass), you'll knock on the glass. Otherwise you'll start forcing it.

Firelocks will now also start blinking with a red alarm when they are autoclosing due to an atmos alert.

Also fixes a runtime in the central atmospherics computer which prevented atmospherics technicians from remotely accessing air alarms.

🆑 Markolie
tweak: Firelocks are now more lethal.
rscadd: Firelocks now crush players standing inside them when they finish closing.
rscadd: Firelocks can no longer be instantly opened by hand: it requires thirty seconds and will autoclose in five seconds if there is still an atmospherics alert present in the area. They can no longer be closed by hand. Heavy firelocks can not be forced by hand.
fix: Atmospherics technicians can once again remotely modify all settings on air alarms through the central atmospherics console.
/🆑

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
A true saint for this code base.

**Comment by Twinmold93** [comment]
Atmos techs (and perhaps engineering) should have no issue just opening them if they have their ID, and perhaps crowbarring is faster to open.

**Comment by Markolie** [comment]
Crowbarring is still instant - seeing as atmospherics technicians always carry a crowbar I don't really want to also allow them to just open the door with their ID card. I feel like firelocks are more mechanically operated doors.

**Comment by Necaladun** [comment]
I'm sure Saint Buck approves of this. You're doing God's work, Markolie. Atmosia bless you.

**Comment by Twinmold93** [comment]
In terms of closing the firelocks, can anyone still just do this, or does it require a crowbar/fire alarm now? This, as a note, doesn't just prevent people from cancelling the alert to open the doors, and 30 seconds seems too long to open a door to have it open for only 5 seconds.

**Comment by scrubmcnoob** [comment]
This PR is supposed to make fire alarms more than just that annoying thing that comes down from time to time.

30 seconds seem like a good thing if you only have hands.

**Comment by Fox-McCloud** [comment]
>It will also crush players that are standing in the firelock when it closes.

This is the one I"m concerned about, since doors don't do this by default. Yeah, I know doors don't close *on* you like firelocks do, but this is the one that I have concerns about.

**Comment by Fraility1** [comment]
My issue with this is there is no mention of it taking time or access to close a firelock. Currently everyone can close them so what is to stop a person running throw and instantly closing them behind themselves to stop pursuers. so 30 seconds is a long time to open a firelock as well.

**Comment by Markolie** [comment]
Closing firelocks requires a crowbar/fire alarm, correct. If you cancel a fire alarm the doors will re-open as it previously.

@Fox-McCloud I wanted to make firelocks feel more like blast doors (that also crush players inside of them). If it's given the order to close, it just closes, unlike airlocks which are much more advanced.

@Fraility1 It requires a crowbar to close a firedoor, so you do need equipment for it.

**Comment by scrubmcnoob** [comment]
I'm liking these game hardening PRs. Make it less plushy and more deadly, especially for breaches.

**Comment by Fraility1** [comment]
@Markolie is there a time period to close the firelock with a crowbar or is it instantaneous?

**Comment by Markolie** [comment]
It is instanteneous.

**Comment by Fraility1** [comment]
so it takes no time to close it with a crowbar but 30 seconds to open it for 5? i feel it should be along the lines of 5 seconds to close it with a crowbar and 10 seconds to open it.

**Comment by Markolie** [comment]
@Fraility1 It does not take any time to open a firelock with a crowbar: it only takes thirty seconds to open it by hand. 

Also added an additional changes: heavy firelocks (constructed using plasteel, these aren't on the map by default) can not be forced by hand at all.

**Comment by Necaladun** [comment]
Honestly I'm mostly interested (from an atmos side) in the auto closing. That's a fucking marvel. Maybe even 3-4 seconds?

30 seconds does feel like it's too long.

Crushing is...prolly too much.

**Comment by Markolie** [comment]
Well personally I think you shouldn't be able to open it by hand at all. Thirty seconds is there to really heavily discourage it and also not allow players to easily escape dangerous atmospherics.

**Comment by Anticept** [comment]
@Markolie the fact you made them autoclose by itself is a huge help.

We should put lights on the firelocks showing they are about to close as a warning to anyone about to run through them if you have the crush factor. I MUCH approve of this though.

**Comment by Markolie** [comment]
Mhm, we could always reduce the time and/or reduce crushing. I'm personally in favour of what we currently have, but if most people prefer different options I'm certainly open to it.

**Comment by FalseIncarnate** [comment]
Assuming this utilizes progress bars for hand-forcing, right?

**Comment by Markolie** [comment]
That's correct.

**Comment by Anticept** [comment]
What happens when shitters play with the fire alarms?

**Comment by Markolie** [comment]
I think that'll be a lot more unlikely now. If they do, I think it can be dealt with IC.

**Comment by SamHPurp** [comment]
I really like this change, @Markolie . Doing God's work.

**Comment by scrubmcnoob** [comment]
The messiah of the code.

**Comment by Anticept** [comment]
Security already has too many problems dealing with a busy station and shitters WILL run through the halls pulling every alarm because "kek".

I like the idea of them being like bulkheads. But I really think there needs to be an indicator of when the firelock is about to close. Or have them close more slowly so people can get out of the way.

**Comment by Markolie** [comment]
Something like that can be implemented, but I'd need sprites for it.

**Comment by Anticept** [comment]
How many steps would you need? It would seem pretty easy to justtake the existing ones and add more iterations.

**Comment by Markolie** [comment]
Well, we'd need warning sprites that it's about to close. I'd rather not slow down the animation.

**Comment by Allfd** [comment]
I don't mind the crushing I guess.  The fire lock exists to protect the station, <s>from an IRL engineering perspective I would probably just install a flashing light and alarm klaxons and warning signs everywhere.</s>

[I looked it up](https://www.youtube.com/watch?v=a1CJ8LBgDyM)

👍

**Comment by Markolie** [comment]
How's something like this (I stole the sprites from the airlock emergency access effect): 
Firedoor alarm

**Comment by Anticept** [comment]
@Markolie yes. They should autoclose in all conditions until the area alarm is deactivated. It's not that hard for the crowbaring person to crowbar them back open anyways.

That said, here's a new approach. Is it possible to overlay light sprites on top of the door sprite? Here's what I have in mind:

Warning lights begin to alternate flashing left and right side, each one lit up for half a second, indicating the door will be closing and to clear the firelock. 5 seconds to do so. This flashing would also occur when manually opened.

On the last 2 seconds, both rapidly start flashing indicating firelock is closing. Flashing continues during the closing.

While closed, the flashing is slow as you have shown.

**Comment by Markolie** [comment]
What I fear is that airlocks not closing immediately allows the atmospherics danger in question (e.g. a raging fire) to spread. That being said, I do think it's a pretty cool idea so it'd definitely be something I'm willing to implement.

**Comment by Anticept** [comment]
What I fear, is shitters pulling the alarms and crushing people randomly. This negates MUCH of that problem.

**Comment by Allfd** [comment]
I think the flashing is nice.  My feeling is when they close, everything should be in favor of them remaining closed as much as possible.  

While I fully understand why they were made easier to open, the mechanics of this could be fun and in general exposure to space is not something people worry about anymore.

**Comment by taukausanake** [comment]
Every time I see something that relates to atmos code, I remember the days of ZAS. Nothing will ever be as deadly as those glorious days...

**Comment by Markolie** [comment]
Additional changes:
* Firedoors forced with a crowbar will now also autoclose.
* The red alarm light has been added.
* Attacking a firedoor with glass (aka not a heavy firedoor) and help intent active will have you knock on the firedoor. Any other intent will have you force it.

**Comment by taukausanake** [comment]
Is it the same red alarm light from the gif you used earlier? It works but it's a little weird when you notice all the other airlocks have light fixtures for those glows and the fire doors do not

**Comment by Markolie** [comment]
Well, the light fixture is for door bolting (firelocks do have a light fixture for that, but that won't show when the doors are open). This one is the same as the emergency lights for airlocks. If someone's willing to sprite a better light I'd gladly use it though!

**Comment by Anticept** [comment]
What is a firedoor border?

**Comment by FalseIncarnate** [comment]
Firedoor Borders I assume is referring to the "skinny" firedoors that occupy a similar position as a one-direction window pane. I believe Metastation is the only map we currently use them on.

**Comment by Fox-McCloud** [comment]
LGTM 

@Crazylemon64

**Comment by SigholtStarsong** [comment]
Speedmerge 10/10

**Comment by Anticept** [comment]
@Markolie there might be one more tiny thing. It would be annoying to try and open a firedoor and be pushed by moving air. If you got your hands on the door, perhaps it should lock you in place?

**Pull request merged**
