### PR TITLE
Unarmed Attack+Martial Arts Update+Golem Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Most of this is from various TG PRs: this is a case of one thing led to another--what was a simple golem refactor led me to updating the unarmed attacks to allow for that, which led to updating the martial arts datum because of the unarmed attack refactor impacting them...which led me to go ahead and update the rest of martial arts since it's simple....which led to me seeing how we handle plasma fist differently than TG, which reminded me of the double-brain Ei Nath bug.

Refactors Unarmed attacks
- Unarmed attacks now are based off of 3 specie's vars for damage: the lowest damage an attack can do, the highest, and the point at which it will weaken someone
 - No Species have been impacted by this, except Golems (more on that below)

Updates Martial Arts Datums
- Learning/unlearning martial arts will now give you specific help verbs which will tell you the combos for a martial arts style
- Basic attacks now factor in a species' attack sounds/damage/verbs in addition to the new unarmed attack refactor
- Fixes it so you can't attack yourself or others, then switch targets for a combo (no more storing plasma fist gibs)
- Rebalances the Bo Staff and Sleeping Carp martial arts datums
 - In general, the stuns are generally longer and the bo staff damage is more; keep in mind that this martial arts is for the Sleeping Carp gang, which is 100% melee oriented.
 - Sleeping Carp martial arts grants bullet immunity; anyone with it will not be hit by bullets unless they're already stunned or they have hulk

Golem Refactor
- Refactors Golems to push as many stats into the species as possible, in addition to making some balance adjustments (Again, from TG)
- now heat immune
- now cold immune
- now pressure immune
- now virus immune
- now radiation immune
- can be cloned now
- deals increased unarmed damage with increased chance to knock you down
- Golems are now immune to parapens and syringe guns attacks
- Golem armor adjusted to be 55 melee armor and nothing more
- Slip immunity removed
- Pain immunity removed (can now tell how much damage they have)
- Slightly slower than before (1 level)

Fixes
- Fixes Ei Nath generating two brains
- Fixes the necromatic stone making the aesthetic skeletons as opposed to actual real skeletons
- Fixes not being able to remove ID/PDA's from Golems (Fixes https://github.com/ParadiseSS13/Paradise/issues/3566)
- Fixes Wyrn attacks doing *extra* damage as opposed to being wimpy

:cl: Fox McCloud
tweak: Updates unarmed attacks to allow for more customization
tweak: Updates martial arts so they factor in specie's attack messages and sounds
tweak: Re-balances Sleeping Carp fighting style
tweak: Re-balances Bo Staff
tweak: Rebalances Golem: they should now be spaceproof, fire+cold proof, rad proof, virus immune, clonable, parapen+syringe gun immune, deal increased melee damage. Their armor has been reduced to 55 melee across the board, their slip immunity removed, pain immunity removed, and they're slightly slower
bugfix: Fixes Ei Nath generating two brains
bugfix: Ensures the Necromatic Stone generates actual skeletons
bugfix: Can now strip PDA/IDs from Golems
bugfix: Fixes sleeping carp grab not being an instant aggressive grab
/:cl:

### CODE REVIEW

**Comment by lolzyking** [comment]
what the fuck? this sounds fun.

**Comment by KasparoVy** [comment]
Lmao, funny how little jobs can end up so much larger than expected, huh? Wicked wicked stuff here.
If it gets down to it, this means that there's another factor by which to balance species, too. Chems that make you temporarily stronger, even. You opened some doors!

**Comment by Dumbdumn5** [comment]
Well, it's not ninjas, but it's at least got an element of it. Take this thing and have my :+1: https://www.youtube.com/watch?v=P1ITMTbd5_8

**Comment by DaveTheHeadcrab** [comment]
@Dumbdumn5 
Damn you, I'm working as fast as I can without tanking my grades or ignoring any of my papers.

**Comment by theColdflame** [comment]
Complete immunity to bullets seems very strong, considering they dominate in melee and bullets are the only ranged options afforded to gangs.

**Comment by KasparoVy** [comment]
Aren't golems made out of some seriously dense stone?

**Comment by Earthdivine** [comment]
@theColdflame That means they have jack against most of security though, so they would need to play nice with them more then the other gangs would, I believe.

**Comment by theColdflame** [comment]
I see your point, but I'm still not sure next-to-immunity to other gangs whilst still being able to stack up to sec if they play tactically is good from a balance perspective.

Seeing how it works out in live play is the best way to test these things, though.

**Comment by Fox-McCloud** [comment]
@theColdflame 

Gang's are generally veryyyy gun based, with the exception of the sleeping carp gang---said gang has strong melee attacks, but they are literally incapable of using guns (all guns, including pseudo guns like the pneumatic cannon); if bullets can hit them, that means they can't really do jack against another gang or sec.

They're still as vulnerable to melee attacks as other mobs are.

**Comment by theColdflame** [comment]
If bullets CAN'T hit them, other gangs can't do anything to them. There's probably a middle ground to be found.

**Pull request merged**
