### PR TITLE
Nutriment and subtypes inherit food taste

### LINKED ISSUE #9956: Everything is bitter
Almost every food in the game tastes like bitterness because it has the nutritional reagents in it, which are all set to taste like bitterness. They should taste more interesting and not misguide people into thinking they're bad cooks.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: Flatty
fix: Thanks to breakthroughs in nanogastronomic technology Food™ will now taste less like bitterness and more like food.
/:cl:

fixes #9956 

I think this is a fix, but I understand why one would disagree. I am at thy mercy, maintainers.

The reagents touched by this are the basic nutriment types (plantmatter, protein, what have you), as well as the weirder subtypes of this, mostly because I didn't want to repath the entire reagent system (ethanol, why?).

You can then grind the food items down or do whatever else you please, and the data will stay!

Also, I still actually need to add the tastes to all the food types. Or figure out a smarter way to inherit that. I'll wait until the Maintainers let me keep this PR open with that work, though.

### CODE REVIEW

**Comment by taukausanake** [comment]
👍 Life is still bitter

**Comment by tigercat2000** [comment]
I'm hesitant about this code, it seems like the taste system should have been better designed...

**Comment by FalseIncarnate** [comment]
Personally think it might be better to just alter the reagent taste messages for now to resolve the base issue while you work on the expansion/improvement/refactoring of the wider system.

That said, being able to say a steak tastes different than a salmon steak based on the food item itself is a nice goal... Just doesn't seem like it is worth holding up a fix of unintended inheritance while you scale that mountain.

**Comment by FlattestGuitar** [comment]
If we want salmon steak to taste like salmon steak, we'll have to either make a specific salmon steak reagent or do what this PR does. I think this is a better solution than adding hundreds of new reagents.

**Comment by variableundefined** [comment]
We're closing this PR as we believe that porting over TG's taste system with its weighted list of taste in its entirety would be the best solution

**Pull request closed without merging**
