### PR TITLE
New benches, colourable sofas

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Resprites regular sofas to remove random crusty noise, enables recolouring.
Recolouring is done with a crayon (inherits crayon colour) or spray can (you can choose any colour), dark colours are prevented so you cannot have jet black sofas.
Adds bamboo benches.
Adds bamboo stool.
Adds benches, with recolourable seat covers.
Updates electric chair sprite and zap animation.
Updates comfy seat sprites.
Added corporate comfy seats.
Added inverse corners to regular and corporate sofas.
~~Added player rotateable beds~~ Sprite directions in, but not letting players edit this yet due to mob dir jank and bedsheet stuff.

## Why It's Good For The Game
Some of these sprites are a bit crusty, this brings existing sofa and comfy chair sprites into a more unified and clean look.
Recolourable sofas is also really neat, and allows custom builds to go the extra mile.

New bench types also make builds and mapping cooler, hopefully.

## Images of changes
Some sprites courtesy of @PestoVerde322 from Beestation, rest are just nicked from TG.

image

image

image

https://user-images.githubusercontent.com/12197162/174156863-f5983706-b0cb-408e-b706-016976fe4d80.mp4

## Changelog
:cl: S34NW, PestoVerde322
add: Added bamboo benches and stool, added regular benches with recolourable covers using crayon or spraycan, added corporate comfy chairs
add: added inverse corners for corporate and regular sofas
tweak: Tweaked sofa and comfy chair sprite, made sofa recolourable using crayon or spraycan
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
HOW AM I CONFLICTED ALREADY

**Comment by LightFire53** [comment]
The corner of the 2 benches is weird considering it share a tile apparently and it colours both? What happens if you try buckling on the corner?

**Comment by Bm0n** [comment]
why does the bench side sprite look like it's floating? I mean look at it compared to the forward facing sprite
image

**Comment by CinnamonSnowball** [comment]
image
These two clash a fair bit, the bench is very bright and has very sharp shading

**Comment by S34NW** [comment]
> image These two clash a fair bit, the bench is very bright and has very sharp shading

Hmm, good point. However they won't really ever be in the same sort of area. One is for an office style area, one is for an more public area.


> The corner of the 2 benches is weird considering it share a tile apparently and it colours both? What happens if you try buckling on the corner?

Buckling works as intended

> why does the bench side sprite look like it's floating? I mean look at it compared to the forward facing sprite image

Hmm, that could do with tweaking yes

**Comment by S34NW** [comment]
> The corner of the 2 benches is weird considering it share a tile apparently and it colours both? What happens if you try buckling on the corner?

I've removed corners because they are causing more trouble than not currently.

> why does the bench side sprite look like it's floating? I mean look at it compared to the forward facing sprite image

Tweaked it to have a leg

**Comment by S34NW** [comment]
> Not 100% sure about removing _all_ of the color noise from the leather couches, new sprites look a bit unnaturally smooth for leather, and the sprite ends up a bit bland; corporate sofas have a bunch of shading and highlighting that help sell the material and make the sprite visually interesting.

I always assumed the sofas were fabric, not leather, whereas the corporate sofas are clearly leather with the shine. I personally think the cleaner sprites look fine but if enough people have issues then I suppose something can be done.

> Also, having looked at the spray can coloring video, do you have to pick the color _each time_ you want to color something? Feels like it'd be better to make the color selectable separately and have it remember the setting as you apply it to different things (or different parts of one big sofa), similar to a floor painter?

Good point, I'd forgotten that the spray can has a built-in colour picker. I've made it use that now.

**Comment by PestoVerde322** [comment]
> Not 100% sure about removing _all_ of the color noise from the leather couches, new sprites look a bit unnaturally smooth for leather, and the sprite ends up a bit bland; corporate sofas have a bunch of shading and highlighting that help sell the material and make the sprite visually interesting.
> 
> Also, having looked at the spray can coloring video, do you have to pick the color _each time_ you want to color something? Feels like it'd be better to make the color selectable separately and have it remember the setting as you apply it to different things (or different parts of one big sofa), similar to a floor painter?

To answer why i opted to make fully clean sofas, is pretty much what S34NW said, they are *supposed* to be made of cloth, not leather, one solution i tried was to add some noise, but that made the palette too clogged for it's own good, however i'm considering to make some parts more sharp to make the sofa to look more pillow-y.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
