### PR TITLE
Enabled the admin-only snake body with sprites from @johannhawk <3

### PR DESCRIPTION
**Pull request by tigercat2000**

### CODE REVIEW

**Comment by johannhawk** [comment]
my OCD doesnt like it but....oh well, i hope nobody else notices.

**Comment by NTSAM** [comment]
As long as it's admin-only

:+1:

**Comment by Regen1** [comment]
Yay

Now we're adding Lamia fetishes to the game, what's next?

 ~~furries~~ oh wait

**Comment by NTSAM** [comment]
You won't even see it most of the time, I don't see how it's that fucking horrible, Regens.

You'll probably see it maybe once then everyone will forget we even had it.

**Comment by TheDZD** [comment]
I still don't really like the sprites.

**Comment by Regen1** [comment]
Oh, well i'm going to add some tentacle porn then, don't worry you won't see it often

**Comment by johannhawk** [comment]
same here DZD, i see two clipping issues that are barely noticable...

at least its not a flying pixel

**Comment by Fox-McCloud** [comment]
>I still don't really like the sprites.

**Comment by Iamgoofball** [comment]
:-1: stop adding furry bullshit

**Comment by tigercat2000** [comment]
@Fox-McCloud @TheDZD Well, apologies, I tried to get multiple artists to help, @johannhawk is the only one that actually responded to me.

**Comment by NTSAM** [comment]
does goofball even play this server

**Comment by Spacemanspark** [comment]
No.

**Comment by HereticChurch** [comment]
I think the sprites are fine, they just need a touch up. :+1: because it could lead to some fun adminbus stuff + it makes Goofball uncomfortable which is fun.

**Comment by Magikarpet** [comment]
Please no. This seems like a thing that treads where we shouldn't tread.

**Comment by tigercat2000** [comment]
@Magikarpet How, exactly? An admin-only tail, how exactly does that tread where we shouldn't tread? Is it because the sprite is modified from vorestation's sprites? Because I am pretty sure the fat people and xenomorphs eating people crosses that line way further than a single fucking sprite.

**Comment by Magikarpet** [comment]
Not only does it attract bad association(due to most people outright blacklisting anything from vorestation as disgusting/disturbing), it brings about the behaviour @Regen1 references in their post towards paradise in furry fandom fetishism and how willingly it's embraced. Even being an admin only feature, people will use this as a lightning rod for hate.

**Comment by tigercat2000** [comment]
You're fucking kidding me, right @Magikarpet 
Adding a silly fucking sprite for admins to use isn't a goddamn lighting rod for hate, and furry fandom fetishism, I don't even know what the fuck you are trying to say, but oh my fucking god it will not be the end of the world that I added a fucking sprite

**Comment by Spacemanspark** [comment]
Can everybody just calm down.

**Comment by Dinarzad** [comment]
If it's an admin-only feature, nobody will ever see it anyway.
Wrynn get use maybe once every few months.
Nucleations never even get used.
It's just something to be in the repetoire for an Admin to use, 's it. Unless people follow github religiously, they'll never even know it exists.

**Comment by Aurorablade** [comment]
i like the sprites. Just as heratic said needs touch up.

**Comment by Iamgoofball** [comment]
The problem with admin only furry shit is that 3 months down the line it gets added as a normal thing because "no one ever uses it"

**Comment by tigercat2000** [comment]
And if a PR to do that passes, it fucking passes.

**Comment by Injazz** [comment]
:+1:
snek where are you going, 
snek, stahp

**Comment by FlattestGuitar** [comment]
I think we should add this just to spite goofball. That's the only sensible argument here.
:snake: :+1:

**Comment by NTSAM** [comment]
also to clarify :+1: because it makes people twist their nips in frustration and because it's admin only.

**Comment by DaveTheHeadcrab** [comment]
Because admin-only features never get abused.
IDGAF about furry drama being incited by this PR being merged or whatever, but it literally serves no purpose other than to be another 'boose-ey admin tool.

*OR* it's an attempt to get it slowly merged as a regular playable race, which I also don't agree with, so.

:-1:

**Comment by tigercat2000** [comment]
I don't want any fucking snake races. My fucking god. Even if I did, a PR to do so would require exactly the same amount of fucking discussion, what the fuck is the goddamn problem if it is discussed and goes through in the future?

**Comment by Regen1** [comment]
>OR it's an attempt to get it slowly merged as a regular playable race, which I also don't agree with, so.

Basically this, the "BUT IT'S ADMIN ONLY" just makes me cringe at the though of a future "makes snake race available to players"

**Comment by CrAzYPiLoT-SS13** [comment]
I think people don't want to turn Paradise into a Furry Paradise, even if
it's admin- only, because that's what this server is on the way of
becoming. I think that this shouldn't be merged. If you want snek bodies,
go to vore. :-1:

**Comment by Iamgoofball** [comment]
we had this exact same cycle at tg

TWICE

"adds lizard race"
coder: "its admin only fam dnt worry"
*3 months later*
"makes lizard race availale to players"
coder: no one uses it, why not fam dnt worry"
now half of tg is lizards and every other round ahelps flood in over lizard vs human shit, and we attracted people who unironically defend furries on our forums

then IT HAPPENED AGAIN
"adds catpeople ears and tail mutation"
coder: "its admin only fam dnt worry"
*3 months later*
players: "make cat ears and tails available by default, they aren't ever used wheres the problem here dnt worry"

and now even more furries showed up and use the game as erp central

**Comment by tigercat2000** [comment]
@Iamgoofball First off. We are not -tg-. Second off. You still don't play here. Why do you fucking care so much about a server you don't play on?

@Regen1 Seriously? You actually think adding an admin-only system will lower the bar for future pull requests? Do I need to get @Fox-McCloud and @TheDZD to sign a fucking contract that says "We will never merge anything making this a player accessible thing"? Because I'm pretty sure they fucking would.

@CrAzYPiLoT-SS13 Are you actually kidding me? Because if you aren't, We are already a fucking furry paradise to most of the SS13 community, what with our fucking huge race selection. "Go play on vore if you want tails", fuck off. You are outright being a cunt for no reason.

**Comment by LiquidNightfury** [comment]
You're really in the wrong place if you think this adding furry characters and things to paradise changes anything at this point. Do you even fucking play here, Goofball?

Quite honestly, a lamia or naga race properly implemented would be a good deal more interesting than most of the ones we already have. I don't see why people are bitching about this on a server that contains the bloody vulpkanin and tajaran. Furry paradise? **Do you even play here?**

**Comment by CrAzYPiLoT-SS13** [comment]
@tigercat2000 
I wasn't trying to be a cunt, I was trying to make a point. The one being a cunt is you. I just want to defend what is good for our community and my personal opinion, no need to tell me to 'fuck off'.

**Comment by tigercat2000** [comment]
@CrAzYPiLoT-SS13 I'm not telling people to `If you want snek bodies, go to vore. :-1:`

**Comment by Necaladun** [comment]
Ok, the level of debate here has gotten pretty bad. Please, try some semblance of niceness. A proptip for improving tone: Cut down the amount of use of "fucking". It's far from professional, nor is it likely to get anyone to engage reasonably.

Now to individual points:
@Iamgoofball - There are many, many, admin only things that have never become regular races. That might be how it is on tg, but it's not here. I'm incredibly grateful for the contributions to the code of paradise you've made, but I don't know why you care about what we do with the server as you're not a player. Whether it's furry stuff, or if we became the #1 server for folk music and line dancing RP, I don't see how it concerns you.

@regens - I don't see why this is a fetish thing, any more than adding Kidan was an ant fetish thing. Is it to do with the boobs being shown, or something? This is one of the fetishes I actually have very little knowledge of - honest question here.

@tigercat2000 - Cut out the abuse. Calling people a cunt, etc, is not productive. I don't want rules to have to be put in place for github conversation, but this attitude is becoming borderline toxic.

@CrAzYPiLoT-SS13 - I see nothing about this making a furry paradise - see my comment to regens.

**Comment by Necaladun** [comment]
Now as for my actual opinion on this, it's a weak +1. I see no particular need or use for this, there's no lore for it, and I have no idea how it would ever be used except maybe to fuck around with in an event or in the admin room. I don't see it doing any harm at all though, so "sure why not".

**Comment by CrAzYPiLoT-SS13** [comment]
Is that a worse thing to say than telling someone to fuck off for
expressing their opinion? I think not, I may be wrong.

**Comment by Necaladun** [comment]
@CrAzYPiLoT-SS13 I was addressing your points, not comparing it to telling someone to fuck off. Completely separate things there. I completely disagree that adding this race would make or is a step towards making Paradise a Furry Paradise, but I don't see anything wrong in the way you brought up the point.

**Comment by CrAzYPiLoT-SS13** [comment]
I was replying to Tiger.

**Comment by Spacemanspark** [comment]
I see no reason to get worked up over this, honestly. This is, after all, just a 2D spessmens game.

**Comment by ZomgPonies** [comment]
1. Stop it with comparing every little thing to furries or vore for crissake. Do snakes have fur? Do ants? Nobody thinks Kidan are a furry race, get over yourselves. I am really tired of people finding ways to persecute furries for the most far-fetched bullshit.

2. @Iamgoofball Stop shitting up our PR comments and instigating drama or I'll make sure you're unable to comment on our codebase in the future.

3. +1 for me, event species are fun especially if they are given special mechanics to go along with it.

4. @Regen1 Lamia fetish? How fucking obscure is that? Nobody gave a fuck when I added slime people as a species, and I'd say Slime Girl fetishes are definitaly more prevalent and yet it's never been a real issue. Seriously, what the hell dude.

**Comment by tigercat2000** [comment]
@Necaladun 
I apologize for not maintaining any sort of professionalism with this pull request.
It's fairly obvious that I have let my temper get the best of me with responding to baseless accusations over a minor feature.
We already have rules moderating the discussion of pull requests, located [here](https://github.com/ParadiseSS13/Paradise/blob/master/.github/CONTRIBUTING.md#commenting). 

@CrAzYPiLoT-SS13 
Perhaps not. I do, however, believe that it is very blunt to say "if you want snake tails, go play vorestation". Vorestation is not Paradise, in any way. It's a very heavy roleplay server with a community that will outright shun anyone that isn't actively participating in their big virtual circlejerk, and that isn't just an expression. I want to add these because I think they could make for fun events.

@Regen1 @DaveTheHeadcrab 
I apologize for not responding to your accusations appropriately;
Do you really believe that adding these sprites will in any way affect the possibility of "a snake race being added for players"? I don't agree with that, but, entertaining the thought; Why would it be a problem?
Any pull request must go through discussion. This one, obviously, has. Previous pull requests have no direct effect on future requests. Sure, it's possible a maintainer *could* see this pull request and say "Hey, the community let this be merged, why not this too?", but the problem is, why do you consider that such a bad thing? Just because you don't personally ever want to see something like that on the server?
I don't want to add a snake race. If I wanted to, I would have made a pull request to add a snake race. I'll promise to never make a snake race pull request, if that would alleviate your supposed concerns.

**Comment by CrAzYPiLoT-SS13** [comment]
I'm sorry too, for being harsh in my wording, but I just fear that people
might genuinely start waving the server off as some kind of joke. That's
probably just me though.

**Comment by ZomgPonies** [comment]
I'm not against the idea of a snake race, as long as it's got unique mechanics associated with it. Never say never, if the art quality gets improved and the mechanics are fun.

**Comment by taukausanake** [comment]
I have nothing wrong with the sprites and think it works compared to the previous ones made. Besides, this isn't doing anything with organ code as I recall would have been a nightmare to do, let alone with whatever changes were recently made, and in no way leads to nagas being a species here. I'd like to see what other colors this would take but I guess I could run the .dmi through Paint.NET some.

I do worry a little that most sprites will look awkward on them, requiring the torso and legs for most respects. They can't wear bottom undergarments and you can't leave them naked. Only a few clothes would work on these and most if not all are female clothes. I guess the undergarment shirts are the only solution to this though so not too bad an issue

**Comment by arthurdayneparadise** [comment]
okay so I'm conflicted. I want this to be merged because it's funny watching goofball, who doesn't even play here lol squirm, but I don't want it to be added because atm paradise is already furstation 13. literally citadel without vore and sex.

also where was the speshul snowflek tag for the vulpkanin pr? after all that was nothing but one single maintainer who wanted it added because it's his fetish not naming names but ill give you a hint he's obsessed with a fictional character lol

**Comment by TheDZD** [comment]
Evidently people are incapable of having a civilized conversation without throwing out accusations that are completely irrelevant to the issue at hand (and even have to stoop so low as to create alt accounts to do so *cough cough*). I am locking this thread and any decision on this will be debated internally. If you wish to continue discussion of this somewhere, create a thread on the forums, and at least try to keep it civil, otherwise that will be locked as well.

**Comment by TheDZD** [comment]
:eyes:
...
:fu:

**Comment by Fox-McCloud** [comment]
*screams!*

**Pull request merged**
