### PR TITLE
Update to Custom cyborg sprite system.

### PR DESCRIPTION
**Pull request by shazbot194**
This update to the cyborg sprite system to have more features has been something I made a while ago for drones and made to work for normal cyborgs. It has been remade a couple times so there might be some odd parts to the code so please feel free to point them out and give suggestions. This update allows four big changes from the current code: have multiple custom sprites for one module, use custom sprites for spawned borgs, go back and forth between previewing custom and default sprites, and allow people to share the same custom icon without having a set for each person. It also removes the name requirement to have a custom sprite.

The main way this works is by expanding the list in config/custom_sprites to have each line to have a player key, module, sprite name, and open overlay name. An example of this file would be;

Key:Engineering:Engibot:customengi;
Key:Medical:medbot:custommed;
Key:Standard:eyebot-standard:eyebot;
Key:Minerwisewill-Miner:wisewill

It is important the last line does not have a semi-colon.

Because every line is only for one module and one key, it can take some more time to go though every line, but when testing it with a full list for myself it took less then a second. I can't imagine there will ever be so many people it would take more then 5 seconds to go though all lines. 
🆑 
rscadd: Adds in the ability to have custom sprites as a spawned borg (ie syndicate)
rscadd: Adds in the ability to have multiple custom sprites for any module
rscadd: Adds the ability for one custom sprite to be used by multiple people.
rscadd: Lets you go back and forth between custom skins and default skins while previewing.
/🆑

### CODE REVIEW

**Comment by shazbot194** [comment]
Closing due to lack of interest from anyone and I have other projects I would like to work on and submit.

**Comment by taukausanake** [comment]
I didn't even know this thing existed to be honest

**Comment by Lady-Luck** [comment]
Sounds good to me?

**Comment by shazbot194** [comment]
I wouldn't re-doing this and making sure it works with the current borg script if anyone is interested.

**Comment by The-Driker** [comment]
SO I CAN HAVE TWICE THE BURGER?

A+++++++++++++++++++++++

**Pull request closed without merging**
