### PR TITLE
Expands Banhammer

### PR DESCRIPTION
**Pull request by Aurorablade**
Kinda a back end change by by request from Tully.

Adds NT Rep to command roles and Magistrate to sec roles, This means they will be affected by approtiate job bans.

Assumeing i did this right...

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
img

**Comment by KasparoVy** [comment]
50f_quarter

**Comment by Aurorablade** [comment]
....can yall not.

**Comment by tinfoiltophat** [comment]
if it's not already considered command, magistrate should probably be added to the command list too.

**Pull request merged**
