### PR TITLE
THE AI VERSION OF BILLY MAYS HERE

### PR DESCRIPTION
**Pull request by Aurorablade**
AND HAVE I GOT A DEAL FOR YOU!

TIRED OF THE SAME OLD QUANTAM PADS?!

INTRODUCING THE ALL NEW PORTABLEPORTAPOTTY!

:cl: Fethas
rscadd: Reskin of the quantam pad, ADMIN SPAWN ONLY, with sprites by kluys
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
what

**Comment by FalseIncarnate** [comment]
No directional sprites, cannot support.

**Comment by tinfoiltophat** [comment]
i need the teleportapotty in my life

**Comment by Birdtalon** [comment]
I'm confused. Is this a meme PR?

I don't really understand the reason behind adding admin spawn only items which will get used perhaps once or twice by an admin and then never seen again.

**Comment by SamHPurp** [comment]
Just bus the sprite change in the round.... this is pointless.

**Comment by tigercat2000** [comment]
This isn't a very complex thing to edit. Administrators are more than capable of creating this on demand, just by changing the icon variable with varedit. As such, we really don't need to add yet another typepath purely for this.

**Pull request closed without merging**
