### PR TITLE
Removes metastation

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
Removes metastation. Meta isn't being maintained and is unlikely to be used anytime soon. When box isn't used it's for a delta testmerge, after all. (and the last of those is a few months back iirc) So there's no point having an old, unmaintained map in the codebase. As Ansari said in #11236 , we already have too many unused maps, so let's get rid of a crap one and make some space.

This also means that changes to turfs/paths, etc that affect stuff on meta don't need to also edit an additional map, reducing effort for future prs.

But wait, you say, what if we get a map rotation system and an influx of coders and mappers that want to fix meta? Wouldn't it be better to leave it in the code for that?
**No.** In such a (imo rather unlikely event), they can always restore the map from the git history, restoring it in its current state. No information or anything is lost in this, after all.

Note, this compiled locally just fine, but travis might have an aneurysm or something

**Images of sprite/map changes (IF APPLICABLE):**
I was going to post a picture of empty space here, but I am too lazy. Imagine metastation without any of the station parts. :P

**Changelog:**
:cl:
del: Metastation, may it rest in peace
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Inb4 the ***IMPROVE, DONT REMOVE*** argument.

I am working on map rotation as we speak, like literally I have it open in vscode right now, so its not really a `rather unlikely event`. The map may not be maintained or tweaked, but that can be said for 90% of the things here.

- Remove genetics because it hasnt been changed in forever
- Remove mechanic because it hasnt been changed in forever
- Remove anything else that hasnt been changed in forever

I fail to see how having this in the codebase makes any harm, and I would like you to explain why

**Comment by TDSSS** [comment]
@AffectedArc07 
Map rotation isn't the unlikely event, having a bunch of people suddenly ready to maintain meta is. And mechanic and genetics haven't changed, but are in use. Metastation is neither being updated nor used, at all.

And it does harm in that it prevents the addition of new maps, since the existence of meta was used as an argument against #11236

**Comment by taukausanake** [comment]
The only reason no other map is used is because it requires a recompile of the code to switch. Once map rotation is put into place then there will be more push to keep maps updated and used. I feel only after that can you can have a valid argument to remove a map because then it'll be based on its own merits. If there isn't a push to update maps then you can remove them

**Comment by Twinmold93** [comment]
The issue is paired on top that if we had anyone who cared to maintain Meta to the fullest and, essentially rebuild it just to fix the numerous bugs, it would still, from what it sounds like from one of the last posts on my map, is they'd still rather have it maintainable to TG (which ends up breaking the map again without manual re-reworks). And even if someone dedicates to the map, it isn't evident to remain maintained.

**Comment by Aurorablade** [comment]
What specifcally needs to be fixed on meta at this time?

**Comment by Spacemanspark** [comment]
You stay away from my favorite map you

**Comment by SkeletalElite** [comment]
Meta station is actually a crowd favorite on servers other than para that have map rotations, Im very highly against it as its a very good map.

**Comment by Twinmold93** [comment]
For paradise, my understanding for Meta being broken right now is some tiles (randomly) are just crashing the game. This was suggested to be due to a recent PR, as I found out, so it's unknown if Meta is just more borked for it or if it's just the code in general. Could be poorly coded tiles (for whatever reason, it's Byond). There are still active (just like for any map) issue reports up, so I'd take a look at those.

**Comment by Aurorablade** [comment]
I will go through the git issues soonish and see if i can figure out problems.

**Comment by Twinmold93** [comment]
Luckily there don't seem to be many, most are map inconsistencies, it looks like.

**Comment by Ralta** [comment]
I actually really like Metastation but the reason for this PR is that, after a discussion with a maintainer on Discord about why we can't have more maps (such as Ragnarok), the reason given is that it would be _yet another map_ to add to the list which needs maintaining. 

Delta is practically ready as it is, but has someone working on it to bring it to full readiness. 

Ragnarok was denied recently on the basis of Paradise having too many maps that aren't maintained. 

Removing Metatstation isn't the best solution but even if someone is working _right now_ to bring it up to standard, they can still continue to work on it; nothing is lost forever this way. 

In spite of everything I've said above, I'm pretty ambivalent about this. It's no great loss if Meta is removed right now, but we do have rotation in progress (SoonTM) :man_shrugging:

**Comment by variableundefined** [comment]
We echoes the reasons above for keeping Meta. Closing the PR.

**Pull request closed without merging**
