### PR TITLE
Fixes Misaligned Areas on Metastation

### PR DESCRIPTION
**Pull request by Norgad**
At some point during development, people forgot to move areas when they moved rooms.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I smell fastDMM, which we've rejected, in the past, unless it was map-merged.

**Comment by Spacemanspark** [comment]
Why is FastDMM bad again

**Comment by Norgad** [comment]
It keeps commit lengths down by putting all new keys at the bottom. This is ""bad"" because the keys are not alphabetically ordered anymore.

Personally, I don't think it's a very good reason, as dream maker can handle them being out of order just fine.

**Comment by Krausus** [comment]
> It keeps commit lengths down by putting all new keys at the bottom. This is ""bad"" because the keys are not alphabetically ordered anymore.

It makes the diffs *look* shorter by dumping any changed keys at the bottom. Since this guarantees none of the diff lines will be in context, it makes the diff harder to actually read. Map-merging generally keeps some lines in context, though it's more by chance than explicit effort. Still, better than nothing.

Also, it doesn't actually make the diff shorter anyway - your first commit was +75, -87; the final diff is +72, -84. What are those 3 extra lines FastDMM changed? Why did it change them? It is a *mystery*.

**Comment by Norgad** [comment]
By shorter, I mean shorter than if you had never used map merge in the first place. Either way, the resultant file is all the same then you're using it, so why not use the faster method?

Also, map merge is tedious to use, especially now that there are like 5 times as many '.dmm's in the folders.

**Comment by Krausus** [comment]
> Either way, the resultant file is all the same then you're using it, so why not use the faster method?

Because we care about how readable the diff is. If we didn't, we wouldn't map merge at all, and the diff would always be completely useless.

**Comment by monster860** [comment]
They are still kept in order, but the keys are randomly picked out of the set of unused keys. This is to reduce the possibility of merge conflicts, since the probability of using the same key twice is low.

**Comment by Norgad** [comment]
This has been sitting ready for over a week, what's holding it?

**Comment by Fox-McCloud** [comment]
@Crazylemon64

**Comment by Crazylemon64** [comment]
LGTM

**Pull request merged**
