### PR TITLE
Adds hidden files.

### PR DESCRIPTION
**Pull request by dapocalypse**
**What does this PR do:**
This PR adds hidden files in code, these cannot be made and cannot be interacted with. This is to make way for user accounts, and system files. In the future there will be a way in which these are interacted with and can be viewed. These will mainly consist of system files.

**Changelog:**
*Remove this line, and appropriate fields from the changelog*
:cl: Dapocalypse
wip:Greetings NSS CYBERIAD crew! With our new 2.01 update to NTOS, we have added special hidden files to OS, however, this is currently not functional and will be worked on by our team INTENSIVLY! GLORY TO NANOTRASEN!
/:cl:

### CODE REVIEW

**Comment by dapocalypse** [comment]
now merge

**Comment by tigercat2000** [comment]
Don't manually add a changelog, just use the inline changelog.

**Comment by dapocalypse** [comment]
Oh okay, done

**Comment by datlo** [comment]
I think you should wait ntil you have a feature that actually needs those hidden files before you get this merged.

**Comment by dapocalypse** [comment]
the features are supposed to be atomic, hidden files is a required feature before i start my next thing.

**Comment by datlo** [comment]
You can code your next feature before getting this merged then make two PRs if you really want to keep them separated (which isn't even necessary, if a system is required by a feature it's perfectly fine to group them in a single PR...)

**Comment by dapocalypse** [comment]
Alright

**Comment by Fox-McCloud** [comment]
Side note, as well. Don't roleplay in the changelog.

**Pull request closed without merging**
