### PR TITLE
Shazbot's new fluff item

### PR DESCRIPTION
**Pull request by shazbot194**
This PR adds in a conversion kit for a fluff nerf gun. The kit works on all nerf pistols, such as the stechkin and enforcer nerf guns. 
The nerf gun starts as a bulky carbine, but can be shortened with a screwdriver into a normal sized nerf gun. While bulky, it can be worn on the back, or when shortened, on the belt.

This has been approved by Freestyle about two weeks ago, and this is just the earliest I could make it.

The internal magazine can be used for anything else, I just ask it be moved out of the fluff section if someone wants to make a different caseless revolver.

CKey: Sniperfairy
Character: P.A.T.C.H.

image

🆑 Shazbot194
Adds: Adds in Shazbot's custom nerf gun and it's conversion kit.
/🆑

### CODE REVIEW

**Comment by SkeletalElite** [comment]
So this shoots foam darts right? Can it load riot foam too?

**Comment by shazbot194** [comment]
It works just like a normal foam dart shooter. So it can.

**Comment by FalseIncarnate** [comment]
Remove the ability for this to load riot darts. Fluff items should not be capable of using them, that's just straight up power-gaming and pay-to-win mentality waiting to be unleashed if we allow people to spawn with actual weapons.

That, or we label this particular fluff item contraband and you get to have sec on your ass every round for carrying a firearm without permit.

When free gave the okay on this, he did not realize this would be compatible with riot darts and I'm willing to bet would not have signed off if he had been aware.

**Comment by shazbot194** [comment]
I’m asking free about further actions as what is currently being asked for is a lot harder to implement then it sounds. 

But I would like to ask if you plan on making all foam force guns contraband since they all can load riot foam?

**Comment by taukausanake** [comment]
Yeah, trying to make this not fire riot darts sounds kind of stupid. Aren't those as simple as just sticking pens inside a dart anyways? If anything the darts should be counted as contraband and not the thing they were fired from

**Comment by FalseIncarnate** [comment]
The point was that we really don't want you getting free weapons as "fluff". Hell, we get kinda itchy about giving free tools as fluff. The contraband thing was more a joke than a serious suggestion, but hopefully got the point across of "yea, we really don't want you having a gun capable of actually being an even moderately effective weapon at round-start unless you get it as part of your job/role"

Now, before anyone comes in whining "but its just stamina damage", you gotta remember stamina damage does stuns. And in SS13, stuns are the king of combat. Combo that with a job in science or cargo and suddenly you have easy access to a lathe to print off all the riot darts you can shove in your bag.

If you really want to get around having to customize the code to reject the darts, just make this into a modkit that reskins a foam gun you have to buy/obtain in round, rather than handing you one right out of the gate. Though you'd be giving up the collapsible storage aspect unless there is a foam gun that can already do that, in which case you'd ideally want to limit the modkit to reskinning that gun so you don't end up mismatching appearance and actual functionality.

**Comment by variableundefined** [comment]
Fluff items should not affect game balance at all. This fluff item doesn't fit into that criteria.

**Comment by Shadeykins** [comment]
"Regarding fluff items, they should be primarily wearable attire that has no direct impact on gameplay" is the first line of our fluff item guidelines.

Having a weapon that can apply stamina damage at long ranges violates this. I am certain Free just neglected to recall that foam weapons can fire riot darts.

**Comment by AffectedArc07** [comment]
*"Having it able to shoot riot darts is bad"*
This is the problem with every foam gun. Riot darts still have to be obtained, they dont start with them. Same how normal guns dont start with riot darts. If riot darts are so much of an issue, then why can normal guns shoot them at all.

**Comment by Allfd** [comment]
Yeah this is dumb.  Every foam weapon has this ability.  Adding checks for it would get shot down as snow flaking.

I find it hard to come up with a situation, in which you would have access to riot foam darts, but not a foam gun.

**Comment by variableundefined** [comment]
The solution is to not start with a gun, or start with a gun retexturer.

**Comment by Ty-Omaha** [comment]
Simple solution

Make it a retexture kit that works on foam guns

**Comment by Ty-Omaha** [comment]
Nevermind it has it's own code so idk.

**Comment by datlo** [comment]
Make it a foam gun modification kit that requires a foam gun and changes the foam gun to the fluff?

**Comment by Pennwick** [comment]
I looked into this a bit. It seems a little superior to the other easy access foam toys. Foam shotguns, ebows, and tommyguns, all need to be cocked between shots. Foam force pistols ARE available through cargo but at 40 points and need a modified console, they shoot semi-automatic with a clip of 8.

I believe this weapon can have its regular darts swaped for riot foam, just requires access to an autolathe.  It has a cylinder of 7 so its pretty comparable. Though reloading may be a bit more tricky its still putting out a significant amount of stamina damage.

**Comment by Aurorablade** [comment]
Quick and dirty code modification to allow it to only fire a certain kind of ammo as i fend a cat off from eating my food:
so what we need to try it just to simply add another case in the attackby to check for this
`if(istype(A, /obj/item/ammo_casing/caseless/foam_dart))
   chamber_round()
else
   <somemessage about you can load it>
   return`

This is kinda quick, untested, made when i got home working at other code while trying to settle in from work thing.
Another path is to make a list of allowed ammo on the base gun type and check on the list.

**Comment by Aurorablade** [comment]
Oh and i can't tab on this..please tab...PLEASE TAB DON'T BE ME

**Comment by shazbot194** [comment]
The only issue I see with that is what if I load it with an ammo box, as that wouldn't stop ammo boxes.

**Comment by Aurorablade** [comment]
you can add a istype check for the box also. The shotgun does this i think.

**Comment by shazbot194** [comment]
Nothing else is made to not use riot darts.

**Comment by shazbot194** [comment]
Ok, so I added the conversion kit, and I will deal with the conflict when I wake up tomorrow.

**Comment by KasparoVy** [comment]
DAT DIFF

**Comment by shazbot194** [comment]
*Sigh*

What the hell github, why must you do this.

**Comment by variableundefined** [comment]
We're more than happy to accept a modkit. A modkit doesn't alter existing behavior of an item in any way, only its appearance. We will accept a PR that does just that.

See this example:
https://github.com/ParadiseSS13/Paradise/pull/10477/files

**Comment by shazbot194** [comment]
Is there no way to have the current modkit be accepted? The current sprites would not work as a pure reskin.

**Comment by variableundefined** [comment]
Why does it not work as a pure reskin?

**Comment by variableundefined** [comment]
A fluff item should stay a retexture rather than becoming mechanically different, even if revolver is worse than a semi-auto nerf gun.

**Comment by shazbot194** [comment]
I would like to ask, if riot darts weren’t a thing, would there be any issue with the original item, having a fully custom nerf gun.

**Comment by variableundefined** [comment]
I don't see a problem with that, but you're not going to remove riot darts for a fluff item are you?

**Comment by shazbot194** [comment]
So I originally talked to the recently retired Free, and want to hear from the current heads if they agree with everything that has been said here.

**Comment by Necaladun** [comment]
I am in agreement with Ansari here, yes.

**Comment by shazbot194** [comment]
Well, I am closing this PR for three reasons, the main one being the the PR itself somehow added a ton of stuff that I can't get rid of.

The second being that I don't have the sprites for a reskin. The pistol requires an empty sprite, which I don't have for these.

The third reason being that I never asked for a reskin, never got permission for a reskin, and this all has been less then pleasant. I have been berated, and talked down to in this PR for someone else forgetting something when approving of my fluff, to then be force to change everything into something that I don't want to do, flat out makes no sense, on top of not having the sprites for the needed changes.

**Pull request closed without merging**
