### PR TITLE
Adds? Fixes? Coroner job icon.

### PR DESCRIPTION
**Pull request by Xantholne**
Add/Fix? Coroner's job icon. Makes it into a black grey and white coffin. Alternative was a very large skull.
bf4a526f2f4bf2d9a833b482e646b021

🆑  Xantholne
fix: The Coroner now has an actual job icon.
/🆑

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
Apparently this is a general morgue icon
https://thumb9.shutterstock.com/display_pic_with_logo/615538/459876262/stock-vector-morgue-mark-long-shadow-vector-icon-style-is-a-flat-morgue-mark-white-iconic-symbol-on-a-gray-459876262.jpg

thanks shutterstock

**Comment by Xantholne** [comment]
I tried a foot tag icon but because of the size it literally became a skull.

**Comment by Xantholne** [comment]
I'll just leave it as the coffin style icon and see what people think after a while.

**Comment by SamHPurp** [comment]
@Xantholne this is fantastic.

Fixes #7360

**Comment by Crazylemon64** [comment]
Simple enough and important enough to pass through the 24h mark

**Pull request merged**
