### PR TITLE
Department Shuttle Update

### PR DESCRIPTION
**Pull request by Kyep**
## What Does This PR Do
Reworks the alternative emergency shuttle, the department shuttle, originally added in: https://github.com/ParadiseSS13/Paradise/pull/7504 
The new design is based on our new standard shuttle https://github.com/ParadiseSS13/Paradise/pull/13727 (same dimensions, ship frame)
The concept is the same as it was originally: a shuttle designed to offer the crew a safer ride after a chaotic round.
The difference is that this new design is much bigger (more space, more seats, etc) and better (prettier, more functional with dual-gated bridge, separate cell room, etc).

## Why It's Good For The Game
Nice to have alternatives to the main shuttle which aren't radically smaller.

## Images of changes
dreammaker_MiU9sqkSln

## Changelog
:cl: Kyep
tweak: the alternative emergency shuttle, the department shuttle, is now bigger and better designed.
/:cl:

### CODE REVIEW

**Comment by Balthusdire** [comment]
The one thing that jumps out at me is that there arent a ton of seats in the general seating area. Maybe changing the bar stools to shuttle seats to help? Makes sense as well that a shuttle would have more than just stools in its bar area.

**Comment by Asmerath** [comment]
I like the shuttle updates, after many years of seeing the same shuttle its nice to see we are expanding it.

**Comment by lolzyking** [comment]
For the love of all that is holy cut the engineering, science and medical sections in half at least, so much wasted space.....

**Comment by Asmerath** [comment]
> 
> 
> For the love of all that is holy cut the engineering, science and medical sections in half at least, so much wasted space.....

what would you use it for? I like it as is

**Comment by lolzyking** [comment]
More general seating you could cut the first three rows off of each section and you'd still have more room than the round start job counts for those departments.

General seating doesn't have enough room for the average number of Civilians+clown+Mime+Botany,+Chaplain+Librarian+Janitors+Chef+barber

**Comment by Asmerath** [comment]
fair, medbay and science are brobably the largest staff departments tho and they might need that room

**Comment by Asmerath** [comment]
7 scientists, 2 robo and 2 genetics. Then medbay is 7 docs, 2 chems, paramedic, viro and phyche

**Comment by Kyep** [comment]
The department-specific seating is intentionally large, so that people can pass by each other.
The non-department seating is intentionally smaller, to encourage people to actually use the department seating.

**Comment by Pixelzilla** [comment]
Doesn't this make it harder for antags who may need to finish objectives on the shuttle by giving the crew department-access-only seating? Making it that much harder to eliminate a target who may have been unable to be located prior to a shuttle call?

**Comment by AffectedArc07** [comment]
emergency_dept-1
There are some things I dislike about this design, so I have made edits so I can put my money where my mouth is. I feel like there was a complete lack of civilian space (The role that is normally filled on highpop), and the lack of symmetry between medical and the brig threw me off. Also having medical seating and the medical area on opposite sides of the shuttle really didnt seem right to me.

This is not a polished version, its merely a concept, but I can send the DMM if needed.

**Comment by BakKeener** [comment]
Is that a beepsky in the corner @AffectedArc07 ?
That's gonna kill a few hijacks but also don't seem terribly useful as beepsky doesn't detain/arrest people who attacks people in its sight who isn't security which would sound like a nice addition but that's another PR.

I personally like the affected version better over the one that the PR is suggesting since I personally find it actually ugly, no offense or anything but even affected version is throwing me off with a lack of walling in the civilian area and I can't think of a easy fix for that since that would remove alot seating since we have 107 shuttle seats, 114 if you count the bar stools and that's counting up Affected since Kyet Version has has 95 shuttle seats, 102 including bar stools.

IMO I just think it needs some more work.

**Comment by Kyep** [comment]
Updated to new design:
dept_shuttle_v2

**Comment by Carthusia** [comment]
it just hit me, but this shuttle lacks the EVA port, somthing i found VERY usefull to not get left behind while exploring space, where we could just enter an EVA area of the shuttle

**Comment by Kyep** [comment]
@Carthusia
I'm not going to remove the medical seating area. I feel its important that be there, because:
- Every department should have a department-access-only seating area, that's part of the point of this shuttle, and I don't want medical to be left out.
- Combining the medical seating area with the treatment area would, I feel, be too chaotic.

I removed the EVA area as it is generally not used. I might re-add a very small (read: 3 tile) EVA access point. Maybe, maybe not. I'm not generally convinced by the argument that since one person finds it useful, it should be added. I'm trying to aim for every room being useful to a good portion of the crew. Rooms that are only useful in rare cases (like the old storage room, or EVA) I will generally cut out.

**Comment by Carthusia** [comment]
For some reason, it never dawned on me that was the medical seating room, for some reason my mind defaulted to it being just a medbay waiting room for wounded lol

But i see your points, even a 3 tile entry would be nice, just some way for the spacer people in suits to get aboard when required or make last minute rescues for people who get bluespace nannered out, and where that usually was 100% certain death, now its 75% certain death

**Comment by Balthusdire** [comment]
The only thing I would want is the supply and engi rooms to be swapped. Seeing rooms that are 4-5-5 tiles wide hurts, 5-4-5 please.

**Comment by Fox-McCloud** [comment]
Really like @AffectedArc07's design.

**Comment by Kyep** [comment]
AA's design lacks a medical seating area, which I feel is essential.
The current design is based on AA's design, though.

**Comment by taukausanake** [comment]
Well why does there need to be a bar in the shuttle? You could remove that and justify a better shaped medical section while also giving the general area more seating as well. A second cyborg charger might be nice, and maybe you can put in that external airlock (even though I don't like the idea of one). The bar is really out of place in a shuttle that is meant for different departments

**Comment by Asmerath** [comment]
> 
> 
> Well why does there need to be a bar in the shuttle? You could remove that and justify a better shaped medical section while also giving the general area more seating as well. A second cyborg charger might be nice, and maybe you can put in that external airlock (even though I don't like the idea of one). The bar is really out of place in a shuttle that is meant for different departments

because we need a bar, I am all for keeping the bar.

**Comment by MRgaty** [comment]
I feel like science and engineering are a bit empty, maybe putting the borg rechargers in the science areas and some spare tools and fire extinguishers (I dunno) in the engineering one would make it look prettier and less empty.
In my personal opinion.

**Comment by procdrone** [comment]
as for EVA port i think that would be nice thing to have.

**Comment by Spacemanspark** [comment]
I would prefer AA's design over this. I feel the medical seating area is either pointless and/ or trying to reduce the shuttle chaos a little _too_ much.

Don't get me wrong, places for specific departments to sit down and a bar to keep people occupied for periods of time is a good thing, but I think there's a nice bit of charm in the medical area getting potentially overwhelmed with injured people, desperate to stay alive after barely crawling onto the shuttle.

**Comment by TDSSS** [comment]
I think an EVA port would be more useful for hijackers, letting them enter the shuttle from space.

**Comment by Carthusia** [comment]
Not only that, I feel alot of people would bail on the ship if a hijacker was trying to murderize them all pre-launch

**Comment by Kyep** [comment]
Updated to this:
dept_shuttle_v2

Note:
1. The medical seating area has been moved, and dramatically reduced in size to the absolute minimum size I will accept.
2. The shuttle has been made symmetrical.
3. The public seating area in the middle has been expanded... to the point it is probably 4-5 times the size it was originally meant to be in this PR.
4, The whole PR has already been completely rebased to be based on AA's design, and updated multiple times after that.
5. This is NOT ever going to be the standard shuttle. It is only a rarely-used, adminspawn-only shuttle for use after chaotic rounds. This shouldn't be a controversial PR, its an update to a rarely used adminspawn-only thing.

**Comment by Kyep** [comment]
Updated to this:
dept_shuttle_v2

Note:
1. The medical seating area has been moved, and dramatically reduced in size to the absolute minimum size I will accept.
2. The shuttle has been made symmetrical.
3. The public seating area in the middle has been expanded... to the point it is probably 4-5 times the size it was originally meant to be in this PR.
4, The whole PR has already been completely rebased to be based on AA's design, and updated multiple times after that.
5. This is NOT ever going to be the standard shuttle. It is only a rarely-used, adminspawn-only shuttle for use after chaotic rounds. This shouldn't be a controversial PR, its an update to a rarely used adminspawn-only thing.

**Comment by Spacemanspark** [comment]
Much, much better +1

**Comment by Terilia** [comment]
I like the shuttle - and considering its an AdminBus Shuttle I like it even more. Someone should also rework the Clown Shuttle. #asking for a friend

**Comment by Kyep** [comment]
Yeah, I've thought about adding EVA access to it... but that would break the symmetry, and given the amount of work it took to make it look nice and symmetrical, I am not keen on that. Probably the only place where I could put an EVA access without breaking the symmetry would be in the Eng section, where the middle window is, going south. But that would trap anyone actually using it in the Eng section.
Plus there's still the fact that I really don't want to encourage people to rely on having EVA access to the shuttle.

**Comment by AffectedArc07** [comment]
Could you update this to master for the sake of a new commit to make MDB re-run?

**Pull request merged**
