### PR TITLE
Terror Spiders 5 - Fixes & Tweaks II

### LINKED ISSUE #6792: Terror Spider Hallucigen Debuff persists after cloning
I'm not 100% on how terror spiders work, but I do know they do something that makes you hallucinate. I got hit by it, died, got cloned, and still hallucinated.

### PR DESCRIPTION
**Pull request by Kyep**
Fixes:
- Spiders can no longer get stuck in vents, because they cocooned a mob on top of a pipe, and it broke the pipe. Similarly, spiders can no longer cocoon anchored objects of any kind. Fixes bug #6221 properly.
- Spiders will no longer ignore mechs and space pods. This was leading to people cheesing the away mission with a ripley and a mech-mounted drill.
- Prince, Queen, etc in away missions no longer stand still like statues. Grays still stay on their vents.
- White spider in away mission can no longer infect people in a way that makes it possible to transfer spiderlings to the main station.
- White spider eggs no longer exist for two minutes longer than they should after hatching from someone.
- Signs in the away mission no longer contain the text 'improper'.
- Spiderlings that hatch in the away mission with an opened queen lair no longer get stuck.
- Two misplaced lights in the away mission have been fixed.
- Queen nests in the away mission which live for a very long time can no longer depressurize their area by smashing walls.
- Fixed a method of cheesing your way into the away mission room containing the prince miniboss.
- Ventsmashing now notifies people around the vent, and takes a few seconds. Fixes bug #6709.
- Reds no longer do the wrong amount of damage on the first attack after regenerating above 50% HP.
- Fixed a bug that could cause spammy "glares at" messages.
- Fixed bug #6793 - queen being able to lay eggs after dying for a short period of time.
- Fixed a bug causing the "Terror Spiders" category to show up in the Check Antagonists panel, with no entries, when there were TS, but none of them were player-controlled. Commonly happened when the TS away mission was loaded.
- Terror Queen spit's hallucinogen no longer lasts for ages due to a depletion bug. Fixes #6792 
- Fixes invisible floor tiles in terrorspiders.dmm. Also removes some unused variables (heat_capacity, etc) that were left over from UO45, and no longer needed here. Yeah, its a big diff for the map file, but it was still map merged. 

Tweaks:
- Webs spun by white spiders will infect humans who are silly enough to walk into them. Hardsuits protect against this. You can tell these apart from normal TS webs, as they have 'sharp' in their names.
- Spiders will now be quicker to open doors. This should stop them getting hung up on doors they can open.
- Empress has been tweaked to have an 'erase brood' ability (wipes infestation, for adminbus), and her spit does BURN instead of TOX. Empress remains adminbus-only.
- Slightly tweaks the number of spiders in the TS away mission, to account for static placement spiders.

🆑 Kyep
fix: Fixed several Terror Spider bugs. Including the notorious 'spiders can get stuck in vents' bug, the 'spiders ignore mechs' bug, and the 'prince is cheesable' bug. 
tweak: Adjusted White & Empress spider abilities - webs spun by white spiders are now infectious.
/🆑

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Can you make the hallucinate effect not last like, FOREVER?

**Comment by Kyep** [comment]
I will take a look. No promises, though. Queen spit is meant to be very robust, and I'm not sure people have adapted to the new hallucinations yet. In away missions, there are anti-hallucination drugs provided, as well as opportunities to dodge or take cover from her spit. In station infestations, killing the queen effectively ends the infestation, and hallucination takes some time to kick in. If you kill the queen but go mad from doing so, that's still a major win for the station.

**Comment by Lady-Luck** [comment]
The new hallucinations cause exceptionally long periods of stun, occurring at just about every door. The hallucinations persist through cloning. And I was still hallucinating like 20 minutes after getting spit on.

Like seriously, the new hallucinations aren't just freaky, they're crippling. you spend a lot of time on the ground and there's no way to get rid of it.

**Comment by Kyep** [comment]
@Lady-Luck I'm not sure that's a bug with TS. It might be a bug with hallucinations. I have pinged the guy who changed the hallucination system on #6792 so that he's aware. If it turns out that hallucination values are very different now, I will adjust the queen's spit. May not make it into this PR, though. This PR already has a lot of fixes.

**Comment by Lady-Luck** [comment]
Apparently Alex Rockwall got hit with spit early on into a shift yesterday and was hallucinating for roughly an hour and fifteen minutes.

**Comment by Kyep** [comment]
@Lady-Luck Fixed.

**Comment by TYoung86** [comment]
I know why you sick fucks like to do shit like this without making visual appearances.

>Webs spun by white spiders will infect humans who are silly enough to walk into them. Hardsuits protect against this. You can tell these apart from normal TS webs, as they have 'sharp' in their names.

Clearly. Screw you. No one will know about this until it starts a rage fest. Whatever. Not cool.

**Comment by Kyep** [comment]
Walking into a terror spider web is risking death. It always has been. Everyone knows they're dangerous at this point. There are already spider types that are designed specifically to lure you into webs, trap you, and kill you. If you STILL insist on walking into the webs, well...

**Comment by TYoung86** [comment]
This isn't about insisting on walking into webs.
Of course everyone who reads the PRs will know ahead of time.
Of course anyone who walks into one will figure it out after it's too late, or they won't.
This is what I mean by I _know_ why you want to do this. You get off on this crap.
You know what the effect is gonna be, and you can't wait to see this in the game.

I'm calling you on your bullshit. And no. Nobody knows walking into terror spider webs is risking death.
https://nanotrasen.se/wiki/index.php/Terror_Spider
Add a different sprite for the webs, or don't. Add some general warning, or don't.

This is a new avenue for newbies and greytides to greif with a free pass. Good job.

**Pull request merged**
