### PR TITLE
Lets you gib butterflies and lizards for keks

### PR DESCRIPTION
**Pull request by Crazylemon64**
Butterflies don't actually give you meat
:cl:Crazylemon
rscadd: You can now gib butterflies and lizards with a knife
/:cl:

### CODE REVIEW

**Comment by NTSAM** [comment]
I originally thought you could butcher lizards already but nope I'm wrong

:+1:

**Comment by CrAzYPiLoT-SS13** [comment]
Gib fish when?

**Comment by Dumbdumn5** [comment]
*Squeesh*

**Comment by Gummin** [comment]
:+1:x:100:

**Comment by KasparoVy** [comment]
rip unathi

**Comment by taukausanake** [comment]
Will butterflies still make gibs? I'm all for more gibs even if it's weird for butterflies. Also wow that was an easy edit you did there

**Pull request merged**
