### PR TITLE
thrown objects now phase through the thrower instead of hitting them

### PR DESCRIPTION
**Pull request by Couls**
## What Does This PR Do

From TG

See title
## Why It's Good For The Game

Hitting yourself with things you throw isn't really fun for you and it also makes no sense

## Changelog
:cl:
fix: you no longer hit yourself with things you throw
/:cl:

### CODE REVIEW

**Comment by Leanfrog** [comment]
So does this fix the age old issue of walking forward while casting fireball and blasting yourself?

**Comment by Fox-McCloud** [comment]
I do this all the time to myself when throwing away my space cola.

It's irritating to say the least.

**Comment by Fox-McCloud** [comment]
Any reason you didn't implement the full PR? https://github.com/tgstation/tgstation/pull/44208

**Comment by Couls** [comment]
We don't have mirror shields for cult last I checked and we don't yet want people being knocked over by mobs they throw, thats a TG thing

**Comment by Fox-McCloud** [comment]
"Knocked over by mobs they throw"? What do you mean?

You can throw mobs into other mobs and it knocks them down; on para and on TG.

**Comment by Couls** [comment]
Yes, but you can't be knocked down by the mob YOU throw, it phases through you already and that'd be a balance change if it collided with you if you threw it from behind you

**Comment by Fox-McCloud** [comment]
Ahh, right. Yeah, I don't want that implementation; it's hilarious, but problematic, for us.

Thanks for the clarification.

**Comment by Couls** [comment]
> So does this fix the age old issue of walking forward while casting fireball and blasting yourself?

doubt it, fireball is a projectile not a thrown object

**Comment by KasparoVy** [comment]
The amount of time I've embedded shit in myself by accident I cannot count
Spears, mining implements, cutlery, glass shard ninja stars, years ago and now lmao

All this time I never knew just how much I've been aching for this to be fixed

Thank you kind Sir!

**Pull request merged**
