### PR TITLE
Delta Station - Remaps Medbay and Virologist

### PR DESCRIPTION
**Pull request by DogeDogIs**
## What Does This PR Do

This PR entire remaps the Delta Medbay and Viro. We need something new there.

## Why It's Good For The Game

The current medbay in Delta is confusing, as it has many corridors and no objective explanation of where the rooms are. We have to provide objectivity and simplicity in the medbays, so that it is accessible for both experienced players and much more for inexperienced players.

We also have to consider that our current medbay has never even been touched for some time, the same with Virologist. Both being more compact and objective for use.

It is of great importance that areas with many uses need to be well developed in terms of mapping, considering that the more used the area, the more it influences the player's experience, and when you have a confusing and non-objective area, you certainly have a negative response regarding the map.

## Images of changes

Last Image Update: 01/05/2024

image
## Testing

Jumped into game, pressed buttons, tested access and yea, works
## Changelog
:cl:
tweak: Remaped Delta Medbay
/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
some errors on other regions of the map but this will be solved with the hook in another branch update

**Comment by DogeDogIs** [comment]
and that little guy in the garden is Sins
say hi to sins
🤩

**Comment by DogeDogIs** [comment]
i have no ideia what this error means 👍

**Comment by DogeDogIs** [comment]
what the fuck i just made

**Comment by DogeDogIs** [comment]
> what the fuck i just made

okay nothing to worrie

**Comment by CinnamonSnowball** [comment]
Would be neat if there were a couple of radsuit lockers stashed somewhere, ideally storage or secondary storage (though they'd need some resizing tweaks to fit them).
A wheelchair would be nice, either in storage or in reception, both have an open spot for one.
Seems the straitjacket+blindfold are also missing, and while not super important, would be neat for consistency

**Comment by DogeDogIs** [comment]
i just realized that somethings is virology is missing, will fix later

**Comment by DogeDogIs** [comment]
image
you say how, i say yes.

**Review by 1080pCat — COMMENTED** [review]
The only 'issue' i can see is this part here, and thats really only an issue for people that have xray/ghosts.(or for mappers)

image

**Comment by DogeDogIs** [comment]
> The only 'issue' i can see is this part here, and thats really only an issue for people that have xray/ghosts.(or for mappers)
> 
> image

Yea, they are in the same wall but different sides. I don't see a _real_ problem here, but if is needed to change that I can 100% do.

**Comment by DogeDogIs** [comment]
S34NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN!!!!

**Review by S34NW — APPROVED** [review]
Mostly fine, users can find missed flaws and report them

**Pull request merged**
