### PR TITLE
Adds shoe/glove requirements to Vulpkanin

### PR DESCRIPTION
**Pull request by tigercat2000**
Alternative to #5089

Adds the shoe/glove requirements of tajaran/unathi to vulpkanin
They have claws, they get flaws!

### CODE REVIEW

**Comment by IcyV** [comment]
Out with the feature altogether, in my opinion.

**Comment by Spacemanspark** [comment]
:+1:
YOU DON'T GET TO ESCAPE.

**Comment by IcyV** [comment]
And yes, I know its changelog, but I really *really* hate the feature.

**Comment by Kyep** [comment]
No.
Shoe/glove requirements are stupid for any race.
Instead of having them added to Vulp, simply remove them from Taj.

**Comment by Spacemanspark** [comment]
...It's a changelog PR, guys.

**Pull request merged**
