### PR TITLE
Fluff borg sprites for Sigholt Starsong

### PR DESCRIPTION
**Pull request by FlattestGuitar**
The ckey is SigholtStarsong.

  

A few more, but I can't be bothered to spam the screenshots, they all look similar.

### CODE REVIEW

**Comment by DesolateG** [comment]
cute, be sure to add the 500 sprites for combat module.

**Comment by FlattestGuitar** [comment]
🤔

**Comment by TravellingMerchant** [comment]
The other variants are Sec, NT and Syndicate. It was very fun spriting these!

**Comment by FlattestGuitar** [comment]
The Syndicate ones are not in, as they do not work with the custom borg sprite system.

**Comment by TravellingMerchant** [comment]
Aw that's a shame.

**Comment by DesolateG** [comment]
Huh... @FlattestGuitar  is name pick not possible after you spawn in as a syndicate borg?

**Comment by FreeStylaLT** [comment]
:ok_hand:

**Comment by Fox-McCloud** [comment]
Signed off by Free. Mergin'

**Pull request merged**
