### PR TITLE
Additional chef slot and kitchen revamp

### PR DESCRIPTION
**Pull request by owenowen212**
//New to using github, apologies for errors.
//Hopefully no conflicts this time.

I've found that because the chef role is often taken by new players unfamiliar with the game, often little to no food actually gets made. With this in mind, adding a second chef will hopefully help the crew get fed properly.

- Adds an additional chef slot and updates the kitchen layout to support this.
- Adds an additional box of eggs, flour and rice to help support an additional starting chef.
- Adds an additional rolling pin, kitchen knife and salt/pepper shakers.
- Each chef gets a small beaker, with a large beaker being in the locker and grinder respectively.
- Donk pockets moved to locker.

http://i.imgur.com/X0gOZuH.png

_Thanks to Kyet and Flattest for their help with map merging._

### CODE REVIEW

**Comment by Kyep** [comment]
Does this include a second chef spawnpoint?

**Comment by owenowen212** [comment]
Yes

**Comment by Kyep** [comment]
config/example/jobs.txt should probably be updated too.

**Comment by owenowen212** [comment]
Done

**Comment by Anasari** [comment]
I support this. One step closer to solving world hunger.

**Comment by Fox-McCloud** [comment]
>I've found that because the chef role is often taken by new players unfamiliar with the game, often little to no food actually gets made.

And that won't change under this PR; the job is going to attract generally low skill or new players; there just isn't a whole lot you can do with the job once you've "mastered" it---additionally, it's not very user friendly; you mess up a recipe and get burned mess from it--and you are completely dependent on the wiki for making food.

As for the layout of the kitchen?

The layout is very poor and isn't really conducive to how things typically flow, in the kitchen.

**Comment by owenowen212** [comment]
> Lastly, your map isn't map merged.

Alright, I'll try to figure that out then.

**Comment by LordJike** [comment]
I think it is a good idea to get a second chef slot, it is true that sometimes there just isn't enough food being produced in enough time, also, the kitchen can be quite a lonely place sometimes.

...a-also, I wouldn't mind increasing my chances of getting that job.

**Comment by Rurik123** [comment]
I do not quite think two chefs will increase food production, as there is quite spare resources most of the time. Unless they both are well coordinated, they will end up getting in each others way a lot. Just imagine one chef using said resources on their own without letting you know, ruining that awesome thing you had planned. Alternatively, what if one slaughters a animal that you needed without asking? Frustration for both chefs would be paramount.

While I speak from experience, as HoP hires a second chef without ever asking the first 90% of the time, I could be wrong. Perhaps people will be more coordinated then I expect.

**Comment by Birdtalon** [comment]
I think at least having two chefs increases the chances of at least one of them knowing some basic things for food making and able to share it with the second chef. Also the fact that we have 50+ civilians at high population I support this entirely.

**Comment by Fox-McCloud** [comment]
Still not map merged.

**Comment by owenowen212** [comment]
> Still not map merged.
My most recent commit? Tsk. I've done something wrong again then.

**Comment by Ssirius** [comment]
Those microwaves in the corner are going to get really annoying, as it currently is the sink is there and its pretty annoying to get water out of it when you need it, I cant imagine how it would be to have the most key cooking machine stuck in that same corner, also two microwaves is not enough for two chefs.

**Comment by pinatacolada** [comment]
this layout feels very inconsistent and random. You have an oven and a grill per table, but then the microwaves and fryers are together, at opposite sides of the room too.

I put my mspaint skills to good use to wrap up what I think would be more suitable for the kitchen
who needs photoshop
Ran out of space for the food cart though, I'd just ram it in the freezer, should have enough space there

**Comment by LordJike** [comment]
Ohh, I like @pinatacolada 's design, I was just about to conjure something up myself.

**Comment by Citinited** [comment]
Speaking of kitchen redesigns, can we have another sink or something in the bottom right of the kitchen? It'd be nice to not have to traipse over the entire kitchen just for some water.

@pinatacolada looks decent, but each chef will only have a maximum of three table spaces, which feels rather cramped. Can you make it more spacious?

**Comment by taukausanake** [comment]
Ugh, I can't stand what Pinatacolada made. It just looks nasty to me. I like the concept of what Owen has but it does seem a little cramp and more difficult to get to your cookers. Maybe the kitchen needs a little more room before you can make another chef position but that might be tough without messing with other areas around it

**Comment by Fullofskittles** [comment]
> often little to no food actually gets made.

This probably isn't anything to do with inexperienced chefs as it is that paradise has a very high population most rounds and depends on botany and science to actually be able to produce any decent amount of food. If inexperience is the problem then the solution might just be to make sure that new chefs are aware of the wiki's location and can easily access the food and drink guide. 

> With this in mind, adding a second chef will hopefully help the crew get fed properly

The amount of limited resources a chef has to start with can absolutely never be made into 'enough' food to fill the demands of a high population server without kitchen upgrades and a large amount of produce from botany.

An additional chef will merely cause conflict in the kitchen and make it more likely that those starting resources will be wasted. It's far more enjoyable to be the only chef because then it's your kitchen and you can easily stick with a theme and keep things organized and running smoothly.

> Alternatively, what if one slaughters a animal that you needed without asking? Frustration for both chefs would be paramount.

I used to play chef a lot and often this was an issue i encountered. I also encountered plenty of problems when HoPs would hire a new chef without asking as well. There is nothing more frustrating than trying to make a variety of good food and then a random new chef shows up and starts slaughering animals in the kitchen and trying to chop up bodies. It's just not fun when there's two people in the kitchen.

**Comment by Fox-McCloud** [comment]
No updates on this in over 2 weeks, and this is internally universally opposed; closing this.

The kitchen is just not very well suited for for than one chef, in terms of mechanics.

**Pull request closed without merging**
