### PR TITLE
Adds a rod smite

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Adds a portable rod smite that spawns a rod from 10-20 tiles away from your target, swooping in and hitting them specifically, and then promptly disappearing before causing catastrophic harm.

This will still mess up the people standing around them, but it won't be full station destruction.

## Why It's Good For The Game
More smites fun. I was inspired.

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/89928798/c9b42837-1764-42e0-9930-07afea8b98ca

## Testing

See images

NPFC :smirk:

### CODE REVIEW

**Comment by matttheficus** [comment]
CLANG!

**Comment by Komrad822** [comment]
I wish this was already a thing so Matt coulda yeeted like 5 at me during the previous round.

**Comment by spacegeese** [comment]
is there a version that DOES cause mass destruction? what if an admin really hates the bridge hobos and wants to get a multikill

**Comment by Coolrune206** [comment]
Don't give me this.

**Review by DGamerL — APPROVED** [review]

**Review by Burzah — APPROVED** [review]

**Pull request merged**
