### PR TITLE
medhud fixes

### PR DESCRIPTION
**Pull request by Aurorablade**
fixes https://github.com/ParadiseSS13/Paradise/issues/8645

### CODE REVIEW

**Comment by Aurorablade** [comment]
hold on got to work on some simple animal logic here.

**Comment by Aurorablade** [comment]
okay i may need some help fixing the health calculations on simple animals.

**Comment by Aurorablade** [comment]
...fixed it...

**Comment by KasparoVy** [comment]
I still can't get over how funny the comments in [this file](https://github.com/Aurorablade/Paradise/blob/2921d3503770cc864d7224c9affd17f43e424349/code/game/data_huds.dm) are :rofl:

Good catch on the fix here.

**Comment by DesolateG** [comment]
So runtime won't be alive and dead any more?

**Comment by alexkar598** [comment]
He always be,the rd made an error in quantum calculations

**Comment by taukausanake** [comment]
Does this not also fix #8639?

**Pull request merged**
