### PR TITLE
Removes broken 'challenge' away mission

### PR DESCRIPTION
**Pull request by Kyep**
This mission:
- Doesn't actually work, and hasn't for a long time. It isn't currently in the rotation, and for good reason.
- Is fundamentally badly designed, having no random elements, and being easy to cheese. E.g: it contains syndie mobs whose bullets get stuck on glass walls, while you can shoot them freely.
- Is a loot pinata, containing a Syndie L6 SAW machinegun, deathsquad armor, a unica auto-revolver, amongst other things. This wouldn't be such a big problem if the mission was challenging, but it has easy-to-memorize solutions.

🆑 Kyep
rscdel: Deleted 'challenge' away mission.
/🆑

### CODE REVIEW

**Comment by tigercat2000** [comment]
I'd normally say "fix it then if it's broken".... but, nah, fuck this away mission, it's awful and literally defines what we never want away missions to become.

**Comment by Spacemanspark** [comment]
Yaaaaaa this mission can burn in hell.

**Comment by Fox-McCloud** [comment]
>Is a loot pinata

That's really what all the away missions are, even the ones that present so called "challenges".

**Comment by jughu** [comment]
I mean it wasnt realy broken first place but it never got maintained we kep adding features which allowed this cheese so meh...

**Pull request merged**
