### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Atmospherics alarm temperatures can now be set to 0. Fixes part of https://github.com/ParadiseSS13/Paradise/issues/1402.
2) Fixes observers being unable to see silicon antag status: https://github.com/Baystation12/Baystation12/pull/11077.
3) Fixes me being a derp (rad suits will now protect from radiation damage in radiation events). Fixes https://github.com/ParadiseSS13/Paradise/issues/2016. Players with full radiation armor will also no longer get mutations during the radiation event.
4) Replaces a regular window with a reinforced window at arrivals botany for consistency.

### CODE REVIEW

**Comment by tigercat2000** [comment]
NOOO MARK WHY

**Comment by Markolie** [comment]
WELP.

**Comment by tigercat2000** [comment]
At least it isn't a issue report? #2016 could have taken it if it was like, 3 minutes later.

**Comment by FalseIncarnate** [comment]
For the record, this only fixes roughly half of the issue reported in #1402 

The remaining portion of that issue report will still be an active issue (being unable to set negative values on server room setting) due to how the code handles temperature checks.

**Comment by Markolie** [comment]
Right, that should be an easy fix too (which I actually just fixed). Here's the issue though: do we really want people to be able to set rooms to absolute zero?

**Comment by Alex6511** [comment]
I believe the server coldroom is supposed to be at -20C.

**Comment by TheDZD** [comment]
2k15, year of the bugsplatting.

**Comment by SamCroswell** [comment]
We need less reinforced windows, not more.
I don't think that counts as a fix.

**Pull request merged**
