### PR TITLE
Fix surgery on organic limbs on IPCs

### PR DESCRIPTION
**Pull request by monster860**
This bug fucked up an IPC body permanently.

:cl: monster860
bugfix: Doing surgery on organic limbs attached to IPC's is no longer broken. 
/:cl:

### CODE REVIEW

**Comment by Ar3nn** [comment]
just don't allow organic limbs to be attached? Organic limbs are a bit harder to get just for this stupidity than just printing a new cyberlimb. The only use for this is replacing limbs on Zeng-Hu or whichever one is replica flesh. Even then, don't support it.

**Comment by Krausus** [comment]
Yeah... it doesn't sound like the real bug here is that you can't do surgery on organic IPC limbs, it's that IPCs can end up with organic limbs in the first place.

**Comment by IcyV** [comment]
First one here to very thoroughly test organic/IPC surgery combinations. Very much a bug and should not be a thing. All kinds of issues come from this. May as well just disable organic limbs from being put on IPCs and call it a day.

**Comment by TheDZD** [comment]
Yeah, this isn't a bug, the bug is that IPCs can get organic limbs in the first place.

**Comment by monster860** [comment]
Well, for now, let's not have any more IPC bodies get irremovable organic limbs.

**Comment by IcyV** [comment]
Or we could just turn it off in the first place instead of doing it a step at a time. It'll be harder to get people to fix the root issue if it's not blatantly broken.

**Comment by Fox-McCloud** [comment]
The underlying issue of this needs to be addressed, not a bandaid fix.

**Pull request closed without merging**
