### PR TITLE
fixed the rescue jaw not spawning... whomstve really?

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Dunno how but the way to create it never had a build path....
Now it does

**Changelog:**
:cl: Farie82
fix: You can now actually make the rescue jaws
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
Not sure why a fix is being downvoted? 😕

**Comment by Spartan6** [comment]
Some of us are non-binary gendered, please don't assume all guys please 😡

**Comment by TDSSS** [comment]
Ooops, my bad lol. How'd that get through review 😆

**Comment by Spartan6** [comment]
Okay, much better, you have my support.

**Comment by KasparoVy** [comment]
LMFAO that turned out better than expected.

In all honesty I downvoted on accideny. Woops mobile

**Pull request merged**
