### PR TITLE
Adds ability to create droppers from glass

### PR DESCRIPTION
**Pull request by Varelion**
## What Does This PR Do

Dropped can now be made in-hand from glass. 

## Why It's Good For The Game
Dropped can now be made in-hand from glass. This is good for bartender, as many drinks are made much more readily with droppers, as to use a single unit of something. This also allows rapid drink population.

Leaving your station to hunt for a dropper isn't optimal for the enjoyment of the job as a Bartender; round start you man the bar, as chemists will come asking for wine. Within a few minutes others typically come in, asking to be tipped-off on mugs or flasks, and asking for drinks. The down time in which you are sure that the bar is good to be left alone is not certain. Allowing this to be made at the bar ensures that, as a bartender, you are allowed to stay at your station, interacting with people, while proliferating drinks. This increases interaction, not minimizes it.

Med is typically too busy to interact, even. Taking the time to hunt tools and hack a nanomed, too, will remove you from your primary role which is serving at the bar.

I should note that some maps start with a dropper in the back, because they understood how it was useful for a bartender, and what leaving your station to hunt for one would mean. 

## Testing
Launched game, and tested it.

## Changelog
:cl:
tweak: Dropped can now be made in-hand from glass.
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
Does Bartender really need a way to make medical tools on demand? They're not exactly scarce resources, asking for one from a Doctor shouldn't be too difficult.

Considering the above, this PR just kinda reduces player interaction.

**Comment by Varelion** [comment]
> Does Bartender really need a way to make medical tools on demand? They're not exactly scarce resources, asking for one from a Doctor shouldn't be too difficult.
> 
> Considering the above, this PR just kinda reduces player interaction.

One tool, that doesn't have powergaming medical use. This tool is very useful for bartenders, and you can't get it on autolathe from supply.

**Comment by CinnamonSnowball** [comment]
Yes, you can get it via player interaction with basically any Medical job. Or if you're really shy, simply hack a NanoMed Plus and disable the access requirement

**Comment by AdamPrime314** [comment]
> Or if you're really shy, simply hack a NanoMed Plus and disable the access requirement and grab one of the 20 available

**FACT CHECK:** There are 3 droppers available in a single NanoMed Plus vendor, they were implying that most stations posses 6 Nanomed Plus which allows for potentially infinite droppers in your possession if you are willing to hack all of them.

**Comment by DGamerL** [comment]
> One tool, that doesn't have powergaming medical use. This tool is very useful for bartenders, and you can't get it on autolathe from supply.

You could also add it as a recipe on the autolathe

**Comment by firstghost** [comment]
Well, what's the recipe now? Is it craftable?

**Comment by Varelion** [comment]
> Yes, you can get it via player interaction with basically any Medical job. Or if you're really shy, simply hack a NanoMed Plus and disable the access requirement and grab one of the 20 available

This isn't optimal for the enjoyment of the job as a Bartender; round start you man the bar, as chemists will come asking for wine. Within a few minutes others typically come in, asking to be tipped-off on mugs or flasks, and asking for drinks. The down time in which you are sure that the bar is good to be left alone is not certain. Allowing this to be made at the bar ensures that, as a bartender, you are allowed to stay at your station, interacting with people, while proliferating drinks. This increases interaction, not minimizes it. 

Med is typically too busy to interact, even. Taking the time to hunt tools and hack a nanomed, too, will remove you from your primary role which is serving at the bar.

**Comment by DGamerL** [comment]
You could also ask the AI or a cyborg, or PDA a doctor/CMO.
I still don't see why making this an autolathe recipe would be the worse of the two options, seeing that you'd need to leave the bar anyways to grab glass

**Comment by Varelion** [comment]
> You could also ask the AI or a cyborg, or PDA a doctor/CMO. I still don't see why making this an autolathe recipe would be the worse of the two options, seeing that you'd need to leave the bar anyways to grab glass

Glass usually spawns within the bar's backroom, with wire and metal.

**Review by Sirryan2002 — APPROVED** [review]
approved for code

**Review by S34NW — APPROVED** [review]

**Pull request merged**
