### PR TITLE
Port Polaris alt language system

### PR DESCRIPTION
**Pull request by tigercat2000**
- Most species languages are no longer an inherent always-present
   language. They are, instead, selectable as an alternate language. To
   account for this, any species with their own language is allowed two
   alternate language picks. You can use these for any language.
 - Refactored mob/language.dm into mob/language/*.dm
 - Refactored HIVEMIND languages to use a new proc, hear_broadcast.

 

SQL changes (preserves current alt languages, but not species languages :( ):
```
USE paradise;
ALTER TABLE 
	characters
CHANGE
	language languages MEDIUMTEXT NOT NULL
```

:cl:
rscadd: Most species now may choose to replace their species language with a different alternate language. (Vox are exempt due to issues with raiders.)
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
I both like and fear what this PR may bring. :+1: for clique-busting, but :-1: for knowing what @Fox-McCloud is saying again.

**Comment by FlattestGuitar** [comment]
So can Eli now speak Sol and NOT SPEAK Canilunzt?

**Comment by taukausanake** [comment]
Forget Fox, I fear for what any vulp may be saying. Not that I'll ever use this. I don't even use Canilunzt on my vulp character. And what Flattest said. Can I actually remove Canilunzt from my vulp now?

Bets for any vulp players getting salty over their language not being so special anymore! Any takers?

**Comment by FlattestGuitar** [comment]
I don't even care about not hearing vulp chat. I just want my snowflek lore to match up.

**Comment by Fox-McCloud** [comment]
:-1: on allowing any species to speak any other species' language--we've tried this before and it got shot down, before.

Other seems interesting though---like foregoing your native species language.

But again, no to species speaking their non-species language.

**Comment by Krausus** [comment]
> Most species languages are no longer an inherent always-present language.
> Removed restricted flag from Skrellian, Sinta'unathi, Siik'tajr, Canilunzt, and Sol Common.

So, there will be no way to know who can or can't understand/speak a particular language, even if it's the native language of their species. That's completely nonsensical. Why even have alternate languages if they devolve into some Tower of Babel nonsense?

**Comment by KasparoVy** [comment]
:-1:. I think leaving the feature at being able to de-select your species-specific language in order to adopt an extra would be alright, but species-specific should remain the way they are. I know that means you'll only be able to have clownish + gutter, clownish + tradeband or tradeband + gutter as additional language setups, but that's as far as I feel alright with it going.

**Comment by FlattestGuitar** [comment]
>My family comes from Germany, but I can't speak German therefore I am a paradox. 

The lore will perfectly adjust the amount of languages used. If your Drask comes from their icy homelands he should expect not being able to communicate in that language normally and cherish being able to drone at another icecube. On the other hand densely populated Sol, from where many characters come from will have a much larger user base. 

Restricting languages to species that aren't biologically different can't be justified in a lore-friendly manner and for a mechanic that is purely RP it makes no sense to do that.

**Comment by Aurorablade** [comment]
i like it....

**Comment by Doukhan** [comment]
Isn't half of tarajanese head and tail movements or something?

I'd be all for a shitty "common" version for other species which misinterprets it into spess enrgish but that's probably beyond the ability of the code.

**Comment by Necaladun** [comment]
Lore stuff can always change - the whole tail movement stuff makes no sense as to why it can be spoken over the radio.

In general I think it'd be a good way to break up species groups a lot.

**Comment by Aurorablade** [comment]
if we could fix the spoken over the radio bit ALA Grey psionic comms for tail movments...

**Comment by KasparoVy** [comment]
^ Like have parts of the speech show up as asterisks like with the Skrell language (parts that just aren't comprehensible at all) for species that aren't the native but can speak it

**Comment by theColdflame** [comment]
how about being able to pick an off-species language as listen-only?

**Comment by Lady-Luck** [comment]
>In general I think it'd be a good way to break up species groups a lot.

There are most definitely race-cliques present on the server. I could see this helping with the Vulp and IPC ones.

**Comment by tigercat2000** [comment]
http://nanotrasen.se/phpBB3/viewtopic.php?f=48&t=8408

**Comment by Fox-McCloud** [comment]
>I could see this helping with the Vulp and IPC ones.

Only, it won't, because Vox and IPC still have their own language that no one else will ever be able to pick.

**Comment by Aurorablade** [comment]
we need to think up something for that then....Its either gonna invovle making a snowflake language for raiders..or making it so if you are not that race you 'mishear' a word...if anyone has seen the monty python hungarian phrasebook sketch think of that..

**Comment by sasanek12** [comment]
I generally really like this idea. Nothing really limits most of species from learning other languages since they no longer involve tail/ears stuff. I feel like it would add some positive variety to the game.

**Comment by Vivalas** [comment]
On one hand I love to break the cliques, on the other hand it makes no sense that a human can mrowl or warble. I would support a "listen-only" format.

**Comment by MindLeaker** [comment]
As Necaladun said, this solves some pretty bad problems we've got going on with our status quo currently

:+1:

**Comment by LittleBigKid2000** [comment]
Pretty sure there's already a flag for languages that makes the language garbled without line of sight. ~~No idea if it actually works or not.~~ Actually, I know it doesn't, but it's just a simple fix.

Also, I think only Unathi should be able to speak Sinta'Unathi, Siik'tajr and Canilunzt should be garbled when spoken by a non-fluffybutt or over radio, and Skrellian should be garbled for non-Skrell (Hearing or speaking), for lore reasons.

Also, pros and cons for me, personally, because why not:
Pros:
Entchtut's fiance/lizard husbando can learn and speak her language and have this represented in game mechanics
I.D.E. can download the language of the fluffybutts that he likes so much, if it's possible for an IPC to have Trinary and Canilunzt with this
Cons:
Not guaranteed to be able to speak privately to my fellow Vulpkanin

**Comment by GeneralGoose** [comment]
tfw all crew will  now know im ERPing

**Comment by Dumbdumn5** [comment]
A huge :+1: to me, we had this before and didn't seem to actually have that many problems, at least from my own experience. Then, one day, it was gone and replaced by the newer alternate languages. I actually enjoy the thought of races learning alien languages, and I don't think that the prospect of an impossible to learn language makes much sense. Rootspeak and bubblish might be the only two that make sense to be near impossible to figure out due to one race being a conglomeration of a ton of plants and the other one making sounds that are probably incredibly painful to make as any other race. It'd do well to make language not a guaranteed privacy factor in addition to actually making for some interesting exchanges or, for the people who only speak one, non-common language, a chance for some of the outsiders to actually pick up on the information being exchanged. Complete and total exclusion from a language seems like a somewhat ridiculous prospect, as, while not everybody is a language expert, it's hard to think that there would be absolutely no translations for any language other than common (and the secondary languages) across races.

**Comment by Krausus** [comment]
> clique-busting

> break up species groups

> There are most definitely race-cliques present on the server. I could see this helping with the Vulp and IPC ones.

> I love to break the cliques

Wow. Cliques are a normal part of human social behavior. There will **always** be cliques, because it is literally impossible to get rid of them, because that's not how our brains work. Race cliques, department cliques, RPer cliques, robustness cliques - players will always pick other players they prefer to interact with, for one reason or another.

Not only is it dumb to think that "aha, now we can listen to what those fuzzy weirdos are barking at each other!" will magically get rid of racial cliques, but it's sad that people are even trying to screw with specific groups of players who happen to prefer interacting with each other.

You want to try to get rid of cliques? Get rid of alternate races, alternate languages, character customization, and non-random names, and then be baffled as cliques *still* form every round.

**Comment by IcyV** [comment]
>"aha, now we can listen to what those fuzzy weirdos are barking at each other!" will magically get rid of racial cliques,

I think most people are probably more annoyed by a single species or two always taking up the majority of comms than they are the actual cliques. Things that actually impact everyone's round. I've gotten quite a bit of ingame and out of game hate thrown my way for starting a minor trend of converting everything to common over comms.

I'm not in favor of allowing anyone to speak cherry-picked racial languages but I do think that allowing racial languages over comms is one of the inherent issues with most complaints about this kind of thing. None of this ever really would be an issue if it was restricted to actually having to be by someone instead of just needing a headset.

**Comment by Krausus** [comment]
> I think most people are probably more annoyed by a single species or two always taking up the majority of comms than they are the actual cliques.

Then why would they be in favor of this? There will still be languages they can't understand, because you can't understand every language.

If the radio getting clogged up with species-specific languages is an issue, we don't even need to make code changes, we just need to make "don't pollute station-wide radio channels with non-common languages" part of SOP. It would be perfectly reasonable, since it's just noise for anyone who can't understand it.

**Comment by KasparoVy** [comment]
^

**Comment by IcyV** [comment]
>Then why would they be in favor of this? There will still be languages they can't understand, because you can't understand every language.

Being able to understand more is a step in the direction of less clutter of something that the majority of a round won't be able to understand. I don't think this is good or an entirely elegant solution to any of the issues, but still.

Really all this PR does is destroy the point of having racial languages if you aren't a special karma race.

>we just need to make "don't pollute station-wide radio channels with non-common languages" part of SOP. It would be perfectly reasonable, since it's just noise for anyone who can't understand it.

Please god. I've wanted this forever. I'm in the minority for that from everyone I've spoken to though. It makes a lot of people mad if you even suggest it.

**Comment by Spacemanspark** [comment]
>we just need to make "don't pollute station-wide radio channels with non-common languages" part of SOP. It would be perfectly reasonable, since it's just noise for anyone who can't understand it.

>Please god. I've wanted this forever. I'm in the minority for that from everyone I've spoken to though. It makes a lot of people mad if you even suggest it.

I would be fine with this.

**Comment by Norgad** [comment]
This is a bad idea. If everyone has possible access to a language, what is even the point of using it. Race languages are specifically for having a known group of crew that you can **privately** talk with. Having access to a private language is an important feature of each race, both lore wise and mechanics wise. This won't solve cliques, those happen anyway

**Comment by Fullofskittles** [comment]
I don't really like the idea of everyone being able to pick racial languages if they're not part of that race. 

Sometimes speaking in your racial language is the only way to get people who make their entire round about being racist to leave you alone. It's not very fun for many of them if they cant understand what their current target is saying. I've had plenty of people who tried to initiate fights give up quickly once they realized they didn't know what I was saying.

I just don't really see allowing anyone to learn racial languages as being a positive thing. It also removes a whole lot of the 'i need a translator here' RP that sometimes happens in the station currently with races that aren't generally played much.

I'd be absolutely fine with someone opting to not know their own racial language. I'd be perfectly fine with there being some brand new non-racial languages that anyone could learn too (sign language when?). I also agree that languages besides common shouldn't be allowed over comms with the exception of an emergency.

**Comment by jughu** [comment]
What about we yoy can understand 1 other species langauge but nnot be able to speak it

**Comment by Lady-Luck** [comment]
>we just need to make "don't pollute station-wide radio channels with non-common languages" part of SOP. It would be perfectly reasonable, since it's just noise for anyone who can't understand it.

What is making this SOP going to accomplish? Civilians have absolutely no incentive to follow SOP, and everyone else is going to be too busy to enforce it.

**Comment by Lady-Luck** [comment]
>Only, it won't, because Vox, IPC, Slime People, and Kidan will all still have their own languages that won't be able to be selected by other races.

I didn't realize IPC's wasn't on the list, but I didn't say Vox, I said Vulp. Not sure I see a good reason to leave any language out that isn't Vox (due to raiders).

**Comment by KasparoVy** [comment]
Lmfao, you're not going to be able to speak like '0110001021 22010 00121110 202' to a guy if you're not a computer in any reasonable span of time.

**Comment by IcyV** [comment]
>What is making this SOP going to accomplish? Civilians have absolutely no incentive to follow SOP, and everyone else is going to be too busy to enforce it.

The option would be there for people to actually deal with the issue. Taking a random example, let's say a traitor is going around and killing everyone. It makes it a lot more difficult if some random person got really sassy and annoyed and decided to make every other line of comms only their language. What can anyone do about it? By the law and SoP, nothing. 

In any reasonable place or area of work, you'd be punished pretty hard for making communication lines more difficult to work with. It only makes sense that there should be a similar case for that here.

**Comment by Lady-Luck** [comment]
>Lmfao, you're not going to be able to speak like '0110001021 22010 00121110 202' to a guy if you're not a computer in any reasonable span of time.

that's assuming you're pronouncing the numbers in galactic common. people understood R2D2 just fine.

**Comment by IcyV** [comment]
>That's assuming you're pronouncing the numbers in galactic common. People understood R2D2 just fine.

I'm not going to go full SW nerd in here, but that's...not comparable.

**Comment by Spacemanspark** [comment]
Didn't they have translators on their ships to see the droids statements?

**Comment by IcyV** [comment]
>Didn't they have translators on their ships to see the droids statements?

Basically they spoke gibberish robot noises that other droids understood and some computers could translate still. Other than that most understanding of droids was "Shhhh, force powers and special people."

**Comment by ExitGame** [comment]
:+1: What Necaladun says.

_Also, totally not upvoting this just for the salt coming from cliques._

**Comment by Spacemanspark** [comment]
Been about a year since I've watched the Star Wars movies.

**Comment by tristan1333** [comment]
I think this should go through. On one hand it might hurt the cliques which I'm neutral towards, but it would help to make the cliques more welcoming. You might have Jim here be friends with a group of dog beasts who like to speak muh speshul snowflek language. With this, Jim would be able to fully enjoy his dog beast friends and their speshul snowflek language.

**Comment by Norgad** [comment]
Remember when someone wanted to let everyone have access to the service channel? This is a bad idea for the same reason that was. If everyone could potentially hear the message in your special channel, what is even the point of using that channel?

**Comment by Dumbdumn5** [comment]
I don't understand the argument about being special or unique in the case of languages, we alreay have some of the additional languages (clownish, tradeband, gutter, etc.) that seem to work just find with no real arguments about privacy or the potential for another person to just pick up and learn the language out of the character select screen. What is gained from having a racial language that's walled off only to that race in comparsion to the additional languages that aren't locked at all?

**Comment by jughu** [comment]
I rather have them only able to understand the langauge then speak

**Comment by Fullofskittles** [comment]
Does no one else remember years ago when secondary languages were broken and you could pick other species racial languages but they didn't work? Remember when they got fixed and everyone everywhere was using secondary languages and people who had chosen racial ones could hear and speak those languages? I sure remember that.

As a vox my character could speak and understand Siik'tajr and 90% of the people talking were random non-tajarans being jerks and just saying things like "meow meow meow" + other random things and most of the tajaran players were reasonably annoyed since they were basically being mocked/harassed in their own language that other races shouldn't have known.

I distinctly remember mentioning that to Ponies and him doing something to revert secondary languages so people didn't have racial ones they shouldn't selected. Lets be honest here, this isn't going to help people "befriend" other races. This is going to be used to harass races that already aren't going to be protected by any sort of OOC harassment rule because "lol it's an ic issue".

If you truly really want to understand a racial language you can just get a universal translator, pAI or a helpful nymph/borg to translate for you. At least those options require you to have another person willing to participate.

**Comment by Dumbdumn5** [comment]
I remember that time, years ago, but nothing bad from it on my end. I ended up learning Siik'tajr on my very first character and having no real issues with it. Yes, there was the occasional attention getter being a pricklord, but the majority of the time, it really was more of a backing fluff. It was a language that wasn't galactic common, so it wasn't used very much, and when it was, it was assumed that anybody who could speak the language could hear it and respond. Acting like a toxic jackass is against ooc rules, and if people really are going around just screaming in racial languages about "OHMYGAWD, FUCKIN' 4IES! DIE!" Responding to that with a player complaint or an ahelp so we can note it down is probably more likely to do something nowadays than it was before. I personally think that the intrigue of a more complicated language base is worth the added risk of greytide mcracialsuperiority acting like a nerd and then hopefully getting pinged for it. OOC or IC harassment is  against the rules in certain cases, such as following somebody around and continually messing with them, playing as a head or other higher up position specifically to negate, demote, or limit other players, etc. I don't see it as much of a stretch to say that, if they act like a complete jerk, they'll get the boot.

**Comment by IcyV** [comment]
>Acting like a toxic jackass is against ooc rules, and if people really are going around just screaming in racial languages about "OHMYGAWD, FUCKIN' 4IES! DIE!" 

Like a bunch of people do here and there already that have been around for a good amount of time?

**Comment by Fullofskittles** [comment]
The community on paradise was very different back then when that happened compared to what it is now. It seems far more likely that it will be worse now compared to what it was then.

Like I said though. I'm all for brand **new** secondary languages. I am absolutely ok with people opting to not know their own racial language to be able to pick another non-racial one. I just don't think racial languages should be opened up to anyone besides characters of that race.

What does opening up racial languages actually solve? Who actually benefits? Who doesn't?

**Comment by Doukhan** [comment]
The way species languages are actually used in game are nigh exclusively to intentionally exclude other would be on-lookers, it's not something you can really anticipate either and is especially annoying when it happens in groups (Vulp sec is worst sec, roundstart tcomms script to auto-translate when).

You can of course get a pAI/ntmph/hassle the AI but that's something that requires the aid of another player.
Being able to counter an advantage as big as what is effectively code-speak on your own is reason enough to have this IMO.

**Comment by Norgad** [comment]
@Doukhan 
You don't need access to every conversation. The entire point of languages is to exclude certain onlookers, just like whispering. 

> You can of course get a pAI/nymph/hassle the AI but that's something that requires the aid of another player.

Then go get another player, and stop getting upset that people don't want you to hear to them. At the moment you're asking people to hand their conversations over on a silver platter

**Comment by Ty-Omaha** [comment]
This is basically what a lot of people are saying:  "you're talking in a different language and you are excluding **_complete_** **_strangers_** from your conversation, how dare you!! muh cliques!!"

If someone comes up and says "hey" or there's different races in the current "group" and they cant understand fluffyfoxpersonspeak, the "cliques" aka "group of friends" (because that's exactly what a "clique" is, a group of friends) I've been with usually switch over to something where everyone can understand and be included

And people can just switch over to PDA chatrooms too

and 

>Restricting languages to species that aren't biologically different can't be justified in a lore-friendly manner

Different vocal chord muscles/setup

**Comment by MindLeaker** [comment]
> Different vocal chord muscles/setup

Lore is a pile of fluff we found down the couch. 
Since it's nothing more than a pile of fluff it can be altered pretty much at will, we could easily say the vocal cords match because we evolved very similarly due to the same bacteria that hit earth hitting the other planets, 
Lore as a justification for preventing new mechanics is dumb.

**Comment by Ty-Omaha** [comment]
That was a response to
>can't be justified in a lore-friendly manner

**Comment by MindLeaker** [comment]
My point still stands for both sides of the argument, Lore is a useless front to argue from, both for and against.

**Comment by Dumbdumn5** [comment]
> What does opening up racial languages actually solve? Who actually benefits? Who doesn't?

Personally, I don't think it should be done to solve anything. It's more interesting to have more people understand a language because of the odd moments or conversations that arise from it. Why specifically racial ones? Because I'm thinking that it would upon up a bit more in terms of backstory for people, or perhaps it could be used to complement a character's longstanding relationship with one group who exclusively speaks such a language, or maybe, in terms of a lore argument, they were born and raised in Sol, so why not speak Sol Common? The people who wouldn't benefit are obviously going to be those affected by people who abuse the language for harassment, and hopefully there are enough people around to tell the guy to choke on it. I'm not saying there won't be rude nerds coming in with this, as with all changes, but I am saying that, if they do, it's probably more likely that it'll die out within a week or so and leave most of what I hope is the better RP situations.

**Comment by Doukhan** [comment]
@Norgad Yeah and unless you're a borg/npc nymph you can't access every one, 2 is the limit right?
People were wondering why this might be a good change, opening up code-speak seems to be a decent one that doesn't actually sacrifice anything of value whilst giving a chance for more interesting gameplay.
You can always just whisper if keeping muh sekrits is really that important.

Also the poll on the forum is in favour of this, speed merge pls.

**Comment by Norgad** [comment]
@Doukhan
The problem is that everyone knows that borgs, AIs, and such can understand them, so you can just not have conversations around them. If every crew member could potentially understand you, the only way to know your message is safe is to speak in private with nobody else around. And at that point, why even use the language?

**Comment by tigercat2000** [comment]
@Norgad Why is that such a big deal? Real languages have the same drawback- you can't know someone does or doesn't understand what you're saying, so don't talk about private shit near them

**Comment by Spacemanspark** [comment]
The shitters that go take the language and use it to be asshats to other races was an issue when we had this awhile back.

**Comment by taukausanake** [comment]
How about instead of two languages you give someone only one alternative language? And then if possible give certain jobs, maybe Librarian and Psychiatrist and extra alternative language, former because all that reading they do, and latter because their job could require or benefit from being multi-lingual.
I think it would be nice if different species had language barriers that would require a third party to translate unless you yourself also knows the language. Still for removing your own default language but don't give people more than two to speak unless their role would expect it I say

**Comment by tigercat2000** [comment]
@taukausanake Everyone already can have three languages. Galactic Common, their species language, and an alt language. I'm not going to take that away just because you can get rid of your species language now, that's ridiculous.

**Comment by Dinarzad** [comment]
> If every crew member could potentially understand you, the only way to know your message is safe is to speak in private with nobody else around. And at that point, why even use the language?

The solution to that is to not talk about shit near people if you want a sensitive conversation. If two chinese guys are in a bar, talking in chinese about a potential plan to bomb a place  or planning something no one else should hear or might get them into trouble if overheard, then they probably should not have gone into a public place to talk about it.

If you wanna talk in Sol Common with your human brothers about this Vulpkanin dude an how he's a total prick ass, guess what? Maybe he knows Sol Common an calls you out on it. Or maybe someone takes the Vulp language just to be a massive dong-lord to Vulps having a vulp meet. But how is that -any- different then screaming "FURFAG" in common around them? You can still understand them, they're still gonna do it, all that changes is the text color or font they do it in, unless you were talkin' shit about them in your private speak, at which point, that's... that's roleplay man, that shit just happens.

**Comment by Fox-McCloud** [comment]
The fact that half these posts and alt languages specifically mentions specifically and only a singular race says a lot about the underlying motives here, IMO.

**Comment by Spacemanspark** [comment]
IMO if that race didn't have bunches of clique-related issues we wouldn't be bringing it up.
Final comment before I leave and it's about God damned vulpkanin cliques.
You know what? Try this feature, and see how it goes. Revert it if the vast majority doesn't like it after it goes in.
If this gets rid of the bar cliques or the cliques that hang around maintenance flirting and validhunting every round, God bless.

**Comment by IcyV** [comment]
>IMO if that race didn't have bunches of clique-related issues we wouldn't be bringing it up (more than any other race, even IPCs and humans!).

Vulps absolutely do not have the most clique issues. Do they maybe have some more notorious players? Sure. They don't compare to some of the clique issues that go on with humans and IPCs though.

>You know what? Try this feature, and see how it goes. Revert it if the vast majority doesn't like it after it goes in.

That's a terrible idea in every regard. It's much harder to get something removed than it is to get it added in the first place. Putting something controversial in on the basis of "Well, let's see how it goes" should absolutely not be happening.

>If this gets rid of or at least helps to get rid of the bar cliques or the cliques that hang around maintenance flirting and validhunting every round, God bless.

Language has absolutely zero impact on these cliques that everyone loses their minds over. It's the community and general playstyle that drives people to act and play the way they do. Want to know what it would be with this or even without languages at all? Just more whispering and PDA messages with people still hanging out. 

And on top of what Fox said earlier, I know for a fact that a lot of the people that are for this wouldn't be affected in the slightest if this were to go through. Many karma-race only players that only stand to benefit while facing none of the potential harassment and annoyance that has been proven to come with this.

**Comment by Doukhan** [comment]
@Norgad Maybe don't speak in public? Using your species language shouldn't guarantee you privacy to the level it currently does IMO.

I really like the idea of the edumacated jobs like librarian/chaplain/maybe psychologist getting more languages, might actually give people a reason to play them.

**Comment by Norgad** [comment]
@Spacemanspark 
>Try this feature, and see how it goes. Revert it if the vast majority doesn't like it after it goes in.

That is a bad idea and you know it. We had enough shit about PDA slots after those got removed when people didn't want it.

**Comment by Dumbdumn5** [comment]
Saying that we should merge a PR and then revert it if people don't like it can end up in the same BS that happened with the viewrange issues, after that, the merge and revert thing has undergone a lot of criticism because it didn't work for the larger part of the vote and stayed in anyways. 

Now, as a player who does play only karma races I'd say that I'm completely, 100% fine with it if you decided that you wanted to extend this to all races regardless of karma cost for sake of fairness. The more languages available, the better it'd be in my opinion. I'm not the first to do this as well, as said by Dinarzad "Hell if opening up even the other languages that don't make much sense is what it takes, I'm okay with it.
Use the fuckin translator implant idea or whatever to rationalize the lore if need be, but opening up languages to everyone can make sense, not just for speaking languages you CAN understand, but NOT speaking ones a character shouldn't." Yes it's reluctant to agree, but the point still stands that I'm not the only one to suggest just throwing the lot of karma races in as well. Again, the more languages there are, the more opportunities for roleplay we have. The clique-busting nonsense doesn't contribute to the arguments for merging because that's not what this is meant to solve, nor is it likely that this is what it is going to solve.

**Comment by Fullofskittles** [comment]
> The more languages available, the better it'd be in my opinion.
> Again, the more languages there are, the more opportunities for roleplay we have.

Isn't the better solution then to just create more _**new**_ languages for everyone instead of just recycling racial ones? Wouldn't that then accomplish the same thing and make everyone involved happy since racial languages would stay as racial languages but there would be more secondary languages to choose from?

I am absolutely in favor of people being able to de-select their own racial language to pick up another secondary (non-racial) one if they want. I think that'd be interesting and would make for fun backstories.

**Comment by Dumbdumn5** [comment]
I'd be all for that suggestion, we'd just need some themes and where they're from to fit the aesthetic.

**Comment by Dumbdumn5** [comment]
I'd be all for that!

**Comment by Necaladun** [comment]
As things are, people seem pretty split on this. I don't see a consensus happening anytime soon, and thus will have to say stick with the status quo.

**Comment by Norgad** [comment]
I've figured out a better title for this PR:

### Removes racial langauges, adds an equal number of optional langauges

Because at this point if this PR goes through, those languages are for all intents and purposes not related to the races in any way besides lore.

**Comment by Draconic-saint** [comment]
Remove all languages, Mimetide worldwide

**Comment by FlattestGuitar** [comment]
Honestly, the only mechanical issue I see here is that if a species has a language restricted to them, it will be encouraged to interact with members of that species. This is mostly visible in IPCs and Vox, but often happens to Tajaran and Vulpkanin, from what I've seen.

Merging this PR won't change much other than the occasional "Glory to Synthetica" or any other fluff things that people shout on comms and it won't help bust any cliques or do anything other that impacts the game mechanics severely.

I want this PR merged solely because I play a Vulp character that grew up on Mars and my :snowflake: backstory should have him speaking Sol, but cannot because of the way the game works.

Languages are really something that HRP servers pay way more attention to than LRP ones, and I think if we're supposed to keep moving up on the scale, this PR would help us encourage building more interesting characters with deeper backstories.

**Comment by LittleBigKid2000** [comment]
Like Flattest, I want this PR to be merged solely because it means my lizard husbando can learn his fiancee's language and have it be game mechanics instead of just RP. Also so IDE can download the fluffybutt language. And Rissa can speak Trinary.

**Comment by Aurorablade** [comment]
I do t care about cliques I just this the system is neat can we try it

**Comment by Krausus** [comment]
> Readd restricted flag to species languages

Now that that's out of the way, we can focus on this:

> preserves current alt languages, but not species languages :(

Completely unacceptable. You are screwing up the languages of **literally every character that exists** to add the option to *remove* their species-specific language. If you can't do this without requiring literally everyone to change their language settings to *not* lose their language, we're probably better off without the feature.

**Comment by Ty-Omaha** [comment]
>What if choosing another species' language had a whitelist that players must apply to be on via the forums.

I like this idea

**Comment by IcyV** [comment]
I'm totally for this given the current changes.

**Comment by FlattestGuitar** [comment]
While the idea would do wonders for our RP level and probably be liked by many of the experienced players, whitelisting literally anything would discourage most newcomers. 

This has been discussed many times and the answer has always been a no. Until we get a better lore base and gain more support for more RP-y type of gameplay this just won't work.

**Comment by tigercat2000** [comment]
@Krausus if you'd like to figure out how the hell to make that work, by all means; I couldn't think of any reasonable way to do it without forcing people to remove their species language every time they open the character menu.

**Comment by FlattestGuitar** [comment]
Uh, can't we just do a query to add the right language depending on the species..?

**Comment by tigercat2000** [comment]
@FlattestGuitar that'll work for existing clients, not new ones

**Comment by Krausus** [comment]
> if you'd like to figure out how the hell to make that work, by all means

Null languages in the params list are currently treated as unselected languages, right? What if unselected languages were stored with a name like "None", and null languages were automatically filled in with the appropriate racial language? So, if someone has `Sol+Common;None`, it means they intentionally haven't selected a second language, but just `Sol+Common` means they have one language, and a gap that should automatically be filled in. In theory, you only have to add this special handling to when saving/loading to/from the database.

... by the way, this will work for existing secondary languages with spaces in their names, right? You've tested that?

**Comment by Dumbdumn5** [comment]
> I'm totally for this PR as it stands given the current changes.

**Pull request closed without merging**
