### PR TITLE
Adds All Vox Shoes and Gloves + Code Reformat

### PR DESCRIPTION
**Pull request by KasparoVy**
Title says it all. Here's some pics:

Shoes:
voxshoes

Gloves:
voxgloves

Some sprites might be missing from these pictures, but regardless of that, every usable pair of gloves and shoes now has a working Vox version.

This resolves part 1 of #1862.

Ready to go unless there's something I missed. However, I'm unable to make any further changes as my HDD's health nosedived and files are getting corrupted, RIP

### CODE REVIEW

**Comment by KasparoVy** [comment]
Some of the shoe sprites might look janky because I had to restart my local and I ended up getting stuck with rainbow socks that clip with most footwear

**Comment by Aurorablade** [comment]
@KasparoVy Feel free to adjust the vox sox if you need to, not the best sprites in the world there but i tried.

**Comment by KasparoVy** [comment]
All good lmao I was just too lazy to go through character creation again to remove/change the socks I was wearing

**Comment by Fox-McCloud** [comment]
Is this ready yet?

**Comment by Fox-McCloud** [comment]
Is this ready yet?

**Comment by KasparoVy** [comment]
Sorry for the crazy late response, yeah this was ready the moment I put it up (unlike every single other PR I've put up ahaha)

**Comment by CrAzYPiLoT-SS13** [comment]
P
11.09.2015. 04.25, "KasparoVy" <notifications@github.com> је написао/ла:

**Pull request merged**
