### PR TITLE
Additional Requests Console Functionality

### PR DESCRIPTION
**Pull request by Crazylemon64**
This PR causes the Ore Reclaimer to put a message to all relevant departments on the request consoles when ore is placed inside. The bulk of the functionality is imitated off of -tg-'s ore reclaimer announcements, with a slight enhancement. In a related note, I also added a Request Console to various places on the map:
Requests console in Brig Medbay - 
brigmedbay_requests
3 requests consoles in Security - 
security_requests1
security_requests2
security_requests3
Requests console in the warden's office -
warden_requests
Requests console in Mechanic's Workshop -
mechanics_request_console
2 Requests consoles in main Atmospherics -
atmosrequests

So, if metal, glass, or plasma were placed in, in addition to notifying the standard departments (Science, Robotics, Mechanic), the engineers or atmos techs would also get a notification, so that they can pay cargo a visit if they need more plasteel for the 10th time science has blown apart the test lab.

The other materials will notify only Science, Robotics, and the Mechanic, as those are the only departments those materials are relevant for (Chemistry isn't expected to be making Surge or EMPs, as they're a pharmacy, not a drug or bomb lab).

In addition, the MULE delivering crates will now send a notification to all relevant departments relative to each beacon on delivery.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Now, to fix those merge conflicts... *grumble*

**Comment by Fox-McCloud** [comment]
I always wanted this, as it's really helpful.

Is there anything else in TG that uses this system? If so, might as well port that too.

**Comment by Crazylemon64** [comment]
Unfortunately, it looks like the only machine they have that does this is the ore reclaimer. As for other things that might benefit by using this... I can't think of any other two distant places that need to share resources.

**Comment by Crazylemon64** [comment]
I think I might be able to rig up something nice with the mulebot. Gimme a bit.

**Comment by Fox-McCloud** [comment]
Hmmm. What about the bartender? I know he has access to the mineral ore redemption machine; he uses the plasma and uranium quite a bit--that said, not sure if it's a good idea or not.

**Comment by Crazylemon64** [comment]
Mm - reckon I COULD do that, but then yeah, you risk the possibility of a jerk stealing all the minerals as soon as they come in. Plasma, the bartender can get from chemistry much as they would get radium, so I don't much see the purpose of that bit, but uranium... Sure, I'll tack that on.

**Comment by Crazylemon64** [comment]
Quick question: How do I copy a list entirely, instead of creating a reference to it?

**Comment by Fox-McCloud** [comment]
to be honest, I'm not sure if the announcements for MULEbots would be that interesting, to be hoenst; they can already check their PDAs, and Ibelieve they make radio announcements, as well; having console announcements isn't particularly useful for them, TBH.

**Comment by Crazylemon64** [comment]
They only make radio announcements to cargo, not the relevant department. Playing a few rounds of medical made me notice that for instance, the virology crates had a nasty habit of sitting in the MULE dropoff zone, ignored, because medical didn't know the crate had arrived. With this in mind, other departments where the MULE dropoff zone is out of sight of the main work area include engineering, Hydroponics, the Kitchen, and pretty much every other one that I can note besides cargo's delivery office itself. And the MULE PDA interface looks to be broken - I get a syntax error from something called "receiveUpdateData" when I try to look at a specific one through the QM's PDA cartridge.

**Comment by Crazylemon64** [comment]
This PR is complete as far as I am concerned - feel free to merge after the review period is complete, unless you have further suggestions

**Comment by Crazylemon64** [comment]
Looks like you might be missing the map edit tag - let me get the pictures of all the requests consoles I added ready, a moment

**Pull request merged**
