### PR TITLE
Weapon sprites consistency pass + New in hand sprites for laser weapons that lacked them.

### PR DESCRIPTION
**Pull request by Stokes52**
## What Does This PR Do
**Adds completely new in-hand sprites for laser weapons that did not have an in-hand sprite of their own:**
These weapons were defaulting to the laser sprite since they didn't have their own sprites which looked really bad.
* Retro laser
* Laser tag gun (red/blue)
* Laser cannon (Accelerator laser cannon)
* Immolator gun (and variant)

**Style and shading pass on security weapons and shotguns** 
The changes are mainly to make sure that all the weapons in the armory or on the station fits the style of the new sprites that were merged in this PR: https://github.com/ParadiseSS13/Paradise/pull/15871

The changes are very minor in most cases, but the overall effect is REALLY nice when you see it in-game.  Mostly what I've done for the sprites: 
* Use a consistent color palette for an overall cleaner and more consistent look.
* More pronounced contrast and shading.
* Very minor edits here and there to make the shapes more appealing.

So here's some screenshots!

## Why It's Good For The Game
Missing in-hand sprites are bad, and style consistency is good.

## Images of changes
In-hand sprites:
inhands

Style consistency pass. Comparison:
comparison

Ingame examples:
OLD:
old

NEW:
ingame2

ingame

Flashlight:
flashlights

## Changelog
:cl:
add: In hand sprites for retro laser, laser tag gun, laser cannon, immolator
tweak: Shading and style consistency pass on security weapons and shotguns
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
Some improvements, but you downgraded some sprites as well... adding a few bad habits

**Comment by Stokes52** [comment]
> Some improvements, but you downgraded some sprites as well... adding a few bad habits

Feel free to let me know which sprites can be improved so I can make it better. Can PM me on discord too if it's easier.

**Comment by S34NW** [comment]
These look good, seeing the unshaded ones next to the new ones really shows the change.

**Comment by DogsParadise** [comment]
> > Some improvements, but you downgraded some sprites as well... adding a few bad habits
> 
> Feel free to let me know which sprites can be improved so I can make it better. Can PM me on discord too if it's easier.

I'll go in more detail when I have a tad bit more time.

**Comment by Stokes52** [comment]
Here's a sample of further improvements after talking with some more spriters.  With some more time I can look at making the other models match something like the one on the right:

double barrel v2

**Comment by S34NW** [comment]
> 
> 
> Here's a sample of further improvements after talking with some more spriters. With some more time I can look at making the other models match something like the one on the right:
> 
> double barrel v2

Thats nice, but it needs a sling since it can go on your back.

**Comment by Stokes52** [comment]
> > Here's a sample of further improvements after talking with some more spriters. With some more time I can look at making the other models match something like the one on the right:
> > double barrel v2
> 
> Thats nice, but it needs a sling since it can go on your back.

ah yes, I'll re-add one!

**Comment by Stokes52** [comment]
Closing in favor of new version: https://github.com/ParadiseSS13/Paradise/pull/16105

**Pull request closed without merging**
