### PR TITLE
Vox free

### PR DESCRIPTION
**Pull request by chesse20**
🆑 
Lowers karma price of vox to 1 karma
/🆑 
I refuse to play paradise as one of 6 boring as hell species and be a kiss ass to everyone and play medical and run around saving people constantly to farm karma just to play as my favorite ss13 species. It's absolute bs. only other medium rp server i can play vox on is vg station but they refuse to make their server public on the hub or reddit so its almost always lowpop.

### CODE REVIEW

**Comment by Kyep** [comment]
We really shouldn't make karma unlocks super-easy to get.
Doing so would defeat the point of having a karma system.

**Comment by KasparoVy** [comment]
Join a clique my dude. Rake it in.

**Comment by Superhats** [comment]
In that case, let's just remove the karma system altogether, because else people can't play as their favorite race.
The karma system is here for a reason. I think 45 is a fair price for one of the most RP-heavy species.

**Comment by Superhats** [comment]
If it lowered it to 40, or even 30, i'd understand, but 1 is just being ridiculous.

**Comment by Superhats** [comment]
You can get karma without, as you say, being a kiss ass and playing medical. I've gotten a fair amount of karma by just playing normally.

**Comment by DesolateG** [comment]
MemePR I see.

**Comment by Citinited** [comment]
*aflap

**Comment by Shadeykins** [comment]
@Birdtalon @KasparoVy Please do not do this or promote this. That would be pretty much the definition of karma-trading.

**Pull request closed without merging**
