### PR TITLE
Alternative to #9130

### PR DESCRIPTION
**Pull request by Aurorablade**
Alternative to #9130

:cl:
tweak: PDA chatroom invites now have a 10 second delay between invites.
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
Now note, the mod comp chatroom is nice, and maybe we can make PDA and modcomp mesh a bit later. But that is later.

**Comment by Ty-Omaha** [comment]
Someone can still just sit there and mass invite people if they've got nothing better to do..

A limit of the number of users would be better than this imo

**Comment by Aurorablade** [comment]
No the issue is the invites. and i know WHY its an issue. with a delay its not putting pressure on what the issue is, and delays can be increased if needed. it up to the powers that be to decide what one they like more.

**Comment by alexkar598** [comment]
Eh,it doesn't send messages half of the time,I am not sad to see a broken feature go away

**Comment by theColdflame** [comment]
this just makes a barely used feature even less usable

**Comment by tigercat2000** [comment]
We'd be better off just trying to implement NTNet chatrooms some time in the future. We're gonna remove these broken (and not very well made) ones for now.

**Pull request closed without merging**
