### PR TITLE
Compile new changelog

### PR DESCRIPTION
**Pull request by Couls**
Updates the changelog to the latest version

### CODE REVIEW

**Comment by Citinited** [comment]
Thanks for picking up the legwork on this!

**Comment by KasparoVy** [comment]
Did something bork the autocompile? Did we ever have autocompile? I can't recall us having done this for ages, for better or for worse

**Comment by Arkatos1** [comment]
Speedmerge or bust

**Comment by AffectedArc07** [comment]
@KasparoVy It broke when we migrated to the new host, and wasnt fixed. I made a few PRs to update this along the way, but the script really needs fixing.

**Comment by KasparoVy** [comment]
Thanks for clearing that up, always been curious about how this was handled

**Comment by AffectedArc07** [comment]
@KasparoVy Its simply a script that needs to run every hour or so, thats what I did for mine. I assume it got overlooked since of its simplicity.

**Pull request merged**
