### PR TITLE
Reduces the amount of round-start uncubed monkeys in Virology to 1

### PR DESCRIPTION
**Pull request by Lady-Luck**
**Originally this PR was to remove all round-start monkeys (NOT the 25 cubes) from Virology, now it just reduces the amount of them to 1.**

I got to admit, it's pretty fun as a xeno to be able to get the ball rolling pretty quickly by taking advantage of virology's round-start monkeys, but I think it makes it just a bit too easy for them to snowball. Virology is still a great place for them to start because of how well they can harass medical, but it won't be the end-all-be-all best place for them to start anymore.

:cl: Lady-Luck
tweak: Reduces the amount of round-start uncubed monkeys in Virology to 1
add: A sink has been added to the monkey containment room in Virology, how convenient!
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
>removing legit tools for a single problem that's hardly a factor in overall Xeno balance.

**Comment by Lady-Luck** [comment]
>removing legit tools for a single problem that's hardly a factor in overall Xeno balance.

That room has like 5 boxes of monkeys.

**Comment by FreeStylaLT** [comment]
I don't know why you want to balance an entire job's mapping location around like a single _event_ mob

**Comment by Lady-Luck** [comment]
>I don't know why you want to balance an entire job's mapping location around like a single event mob

This does not affect Virology in the slightest. They have 25 monkey cubes in that room. This just makes this event mob not always start in virology.

I imagine they will migrate to always favoring the turbine. In fact, a lot of antagonists favor the turbine. But that's outside the scope of this PR.

**Comment by monster860** [comment]
Antags are already underpowered enough as it is.

**Comment by Lady-Luck** [comment]
>Antags are already underpowered enough as it is.

I don't see xenos lose very often.

**Comment by FlattestGuitar** [comment]
In my opinion this doesn't change the virologist's toolkit in the slightest, considering there are cubes they can use and monkeys aren't even that useful altogether. 

Seeing as xenos use virology very often, I'd say it's at least worth considering. 

I think a better fix would be a larger maintenance overhaul with more rooms to hide in.

**Comment by Lady-Luck** [comment]
As someone who does a lot of virology, this does not affect virology in even the slightest iota. All this is going to affect is xenos. They are already an exceptionally strong antagonist, giving them five monkeys to work off of for free really isn't necessary.

**Comment by Chakirski** [comment]
Every time I've been an xeno I crawl all the way to med maint solely due to the fact that I am guaranteed monkeys. However, the atmos piping is isolated from the rest of the station, meaning you would have to break in by melting walls and doors.

**Comment by theColdflame** [comment]
xenos actually having to attack people before they start snowballing is a good thing, and this has absolutely no balance implications for viro itself :+1:

**Comment by Earthdivine** [comment]
While I have no issue with removing the monkeys since Virology barely uses 5, much less 30, Xeno balance has some more problems then just getting 5 free Hunters. Removing all of the monkeys as well may gut their start entirely and never let them actually get off the ground unless Xeno-Bio has monkey's lying around. Cutting it to just a few monkeys, like 1 or 2, might be better off then just removing all of them.

**Comment by Chakirski** [comment]
So the only way to get off the ground is useless monkeys...
Sounds like a lack of skill.

**Comment by Lady-Luck** [comment]
>Every time I've been an xeno I crawl all the way to med maint solely due to the fact that I am guaranteed monkeys. However, the atmos piping is isolated from the rest of the station, meaning you would have to break in by melting walls and doors.

Try going in through the scrubber piping. It is much, much easier to get into virology through scrubber piping.

>Cutting it to just a few monkeys, like 1 or 2, might be better off then just removing all of them.

Could definitely do that, yeah.

**Comment by Draconic-saint** [comment]
I do think it's a good start to diversify xeno nest locations. I like the idea behind this, probably could use some tweaking.

**Comment by Lady-Luck** [comment]
@TheDZD This is not a revert or feature removal.

**Comment by KasparoVy** [comment]
Monkeys present at roundstart is a feature, isn't it?

**Comment by tigercat2000** [comment]
@Lady-Luck It absolutely is feature removal. It's a feature for virology to have a monkey in it. Presumably specifically for xenomorphs.

**Comment by Lady-Luck** [comment]
>It absolutely is feature removal. It's a feature for virology to have a monkey in it. Presumably specifically for xenomorphs.

But it still has monkeys in it. Just in cube form.

**Comment by TheDZD** [comment]
Feature removal tag is generally reserved for when code is removed, removing a feature.

**Comment by Lady-Luck** [comment]
>I do think it's a good start to diversify xeno nest locations. I like the idea behind this, probably could use some tweaking.

I am open to suggestions.

**Comment by Doukhan** [comment]
:-1:  for Hugbox 25XX.

A better solution would be giving viro/xenobio their own separate vent network that requires a bit of effort to get into (public vent, maybe have to acid into one of the atmos rooms?).
This is just cheap and dirty.

**Comment by Lady-Luck** [comment]
>A better solution would be giving viro/xenobio their own separate vent network that requires a bit of effort to get into (public vent, maybe have to acid into one of the atmos rooms?).
This is just cheap and dirty.

But that would negatively affect non-xeno antagonists.

**Comment by Draconic-saint** [comment]
As has been suggested, giving them more viable alternatives instead of making the current ones not viable would be a better aproach, but that'd require a bigger mapchange, and can't be  combined with this PR due to atomicity standards. I wouldn't mind seeing this tweaked in the way earthdivine suggested and merged myself to start things off.

**Comment by Doukhan** [comment]
@Lady-Luck Only antags I can see it affecting would be morphs changelings and borers an-
Ehhh, quite a lot.
Still though viro/xenobio are ostensibly secure areas, they've got double airlocks and are covered in r-walls, it's kinda odd their pipes are wide open.

**Comment by Lady-Luck** [comment]
As per @Earthdivine's suggestion, I've reduced the amount to 1. That will still give the queen a leg up.

**Comment by Davdichan** [comment]
Eh, starting monkeys are generally annoying and xeno rounds are rare enough I'd rather the queen to just be able to hydrate cubes somehow (slashing a water tank near a pile of cubes maybe?)

Less mobs to track is less lag.

**Comment by Lady-Luck** [comment]
>Eh, starting monkeys are generally annoying and xeno rounds are rare enough I'd rather the queen to just be able to hydrate cubes somehow (slashing a water tank near a pile of cubes maybe?)

That would be ridiculous. Even if I removed all the boxes from virology, we'd then have to consider other areas of the station where the boxes are abundant. There needs to be a box for every species for surgery purposes in Genetics, and Xenobiology has to have monkeys too. There's also more monkeys in SciChem.

**Comment by Davdichan** [comment]
Because giving Xenos more options to make their nests and become less predictable is a bad thing?

**Comment by Lady-Luck** [comment]
>Because giving Xenos more options to make their nests and become less predictable is a bad thing?

It's less the fact there's more variety and more the fact that it'd make them snowball even harder than they do now. We're talking a LOT of biomass, far more than they have access to right now in Virology, spread all over the station.

If this accompanied a xeno rebalance, sure, but that's outside the scope of this PR.

**Comment by fludd12** [comment]
Solution: Port goon monkies, put them randomly spread throughout the station.

**Comment by IcyV** [comment]
> too easy for them to snowball.

That's honestly the only time I've ever seen xenos reliably win. With the nature of everyone instantly grabbing 3 guns and half the station swarming to where a xeno might have been seen, numbers is their only advantage. We don't have the variety of something like CM xenos that can actually deal with unique problems. It's pretty much a crap shoot if you don't keep up a certain number of xenos as soon as you can. 

They don't really get anywhere else to start if they can't get a lead in Viro. Genetics is borderline guaranteed suicide to attempt to convert the monkeys there. Xenobio is out entirely most of the time with the computers and the teleporting. The problem isn't that Viro is the best start for them, it's that Viro is pretty much the only viable start without risking everything on people you might be able to get in maint.

**Comment by Lady-Luck** [comment]
Well, DZD just added the meme ded tag so this probably isn't going to get merged now.

**Pull request closed without merging**
