### PR TITLE
Fixes power gloves lightning not calling bullet_act.

### LINKED ISSUE #1263: Powergloves Do No Damage
Basically as the title says; power gloves currently do not do any damage; the beam arcs and the target is definitely hit (as it plays the sear sound), but the damage isn't actually registering on them.

### PR DESCRIPTION
**Pull request by veganzombeh**
This calls bullet_act if lightning from power gloves hits something. Power gloves will now correctly deal damage. Fixes #1263.

### CODE REVIEW

**Comment by Krausus** [comment]
I just noticed that there's two identical copies of /obj/item/projectile/beam/lightning, one right after the other. Might be best to just delete the second one.

**Comment by Fox-McCloud** [comment]
The second one is commented out; it's leftoever from when we switched from icky hitscan beams to projectile beams.

**Comment by Krausus** [comment]
Ah, my editor's syntax highlighting doesn't actually handle nested comment blocks properly. Why do we even have large chunks of identical commented-out code?

**Comment by Fox-McCloud** [comment]
Did...you test this? I just did and it doesn't work.

**Comment by veganzombeh** [comment]
It was working fine when I tested it last night. I'll test it again shortly.

**Comment by veganzombeh** [comment]
It is working, but the lightning only seems to check for collisions for 2 - 3 tiles, which I didn't realise, so your target has to be fairly close.

**Comment by Fox-McCloud** [comment]
Pretttty sure that's not intended; it's meant to be a long range weapon.

**Comment by veganzombeh** [comment]
This should be better. I moved the bullet_act to the bump proc and also prevented it breaking floor tiles when the lightning doesn't even reach them.

**Pull request merged**
