### PR TITLE
Additional AI Sprites

### PR DESCRIPTION
**Pull request by ParaGitV**
## What Does This PR Do

Adds more AI core sprites courtesy of FullOfSkittles.

Update: Also adds more holograms now as well.

## Why It's Good For The Game

More AI core & hologram variety.

## Images of changes

Provided by FullOfSkittles:
ai-cheese ai-borb ai-rainbowslime ai-nadburn ai-darkmatter ai-liz ai-vox ai-tiger ai-fox ai-bee ai-voiddonut

AI-holo-borb AI-holo-biggestfan AI-holo-angel
AI-holo-rollermonkey AI-holo-frostphoenix AI-holo-donut

Provided by: https://github.com/yogstation13/Yogstation/pull/8058
ai-catamari

## Testing

Tested and confirmed they all show and act as expected on an AI.

## Changelog
:cl:
imageadd: Adds new AI core sprites
imageadd: Adds new AI holograms
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
These are pretty great!!

I’ve actually been meaning to PR the following ai core from yogstation, would you be interested in adding it in too if you like the look of it? https://github.com/yogstation13/Yogstation/pull/8058

**Comment by S34NW** [comment]
oh god an amogus AI

**Comment by procdrone** [comment]
the among us AI is too memey in my opinion, others look good

**Comment by PacifistDalek** [comment]
do the ai holograms have that hologram face behind them in game? looks kinda awkward.

And RIP amogus we hardly knew ye

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
