### PR TITLE
Fixes 8584

### LINKED ISSUE #8584: Strange Reagent and Plant trays not interacting
**Problem Description**:
Strange Reagent does not react with Hydroponics trays or Soil Plots

**What did you expect to happen**: 
A tree or Killer tomato to be spawned.

**What happened instead**:
Nothing.

**Why is this bad/What are the consequences:**
You can't channel your inner Poison Ivy and summon hordes of ravenous plants.

**Steps to reproduce the problem**:
Obtain Strange Reagent
Pour it in a tray
Observe nothing

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
The proc that should be triggering is in  Paradise/code/modules/hydroponics/hydroponics.dm
if(S.has_reagent("strangereagent", 1))
This is probably due to the chem actually being strange_reagent

### PR DESCRIPTION
**Pull request by Pennwick**
Fixes #8584 

Missed underscore in original file.

### CODE REVIEW

**Comment by alexkar598** [comment]
You need to put

Fixes #8548

**Comment by alexkar598** [comment]
It's not even the right id..

**Comment by alexkar598** [comment]
It's 8584

**Comment by Pennwick** [comment]
I apologize. Its my first pull request in years. Should be correct now.

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
