### PR TITLE
Makes NT-Rep and Blueshield offices smaller

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
add: The Blueshield and NT-Rep have been resized.
/:cl:

2016-07-09-14_30_20-greenshot

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Gig empty spaces like tunnel are bad.

**Comment by Norgad** [comment]
@Fox-McCloud 
...but it's not empty.

**Comment by Spacemanspark** [comment]
I personally like the way it was before.

**Comment by IcyV** [comment]
I just don't really see the reason for this. Nothing is really wrong with how they currently are. Not everything has to be changed just to change it up.

**Comment by Lady-Luck** [comment]
>I just don't really see the reason for this. Nothing is really wrong with how they currently are. Not everything has to be changed just to change it up.

Not true. As someone who plays NT Rep, few people ever notice me when I'm at my desk. The distance of the windows to the door makes it so people can just barely see me if they're right up next to it, but I'm also obstructed by UI elements.

This is a very welcomed change.

**Comment by Plotron** [comment]
Then move the god-damned desk!
Blueshield's office sure could be smaller, but NT Representative requires some space to house people.

**Comment by Lady-Luck** [comment]
What, does your Rep throw a party in their office or something? That's still more room than the Magistrate has.

**Comment by Plotron** [comment]
Yes.
Magistrate also has IAA room available for use.

**Comment by IcyV** [comment]
>Then move the god-damned desk!
Blueshield's office sure could be smaller, but NT Representative requires some space to house people.

Honestly I agree with that. Blueshield doesn't need a big office. They're pretty much one and done once they get their gear most of the time. NT Rep is still useful with the space on the occasion they need multiple people in there. Being out of sight of people is just an issue of someone not wanting to move their chair or be more active than just waiting at the bottom of their room.

**Comment by Lady-Luck** [comment]
>Being out of sight of people is just an issue of someone not wanting to move their chair or be more active than just waiting at the bottom of their room.

That's where your shit is...

This is depressing.

**Comment by IcyV** [comment]
>This is depressing.

Emotional appeals instead of arguments.

It's pretty rare to see an NT Rep get solicited for a meeting while they're sitting in their office ever. The primary point of the Rep is to report on the stations condition as a whole and items of major importance. This, more often than not, won't be a singular person wanting to report something. That would be going to IAA or the Magistrate.

The Reps office is moreso for their own luxury and being able to write their reports in peace while still holding the potential for hosting quite a few people at once in case it needs it. This proposed design squishes everyone involved into a small few tiles of space with nowhere to move. It just doesn't look good and it would feel extremely awkward in practice.

I'm not saying that the office couldn't be redesigned to fit your concern, but I think taking that much space away for a literally pointless hidden hallway isn't the way to do it.

**Comment by Lady-Luck** [comment]
>Emotional appeals instead of arguments.

Not making an argument. Just don't care anymore.

**Comment by FreeStylaLT** [comment]
come on man empty spaces are terrible from both practical and design perspective

for example, look at this thing next to surgery: 
img
That looks like crap, serves no purposes and can be very easily replaced with a maint or medbay room, but it's there. Still there. Has been for a while. Literally wasted space.

Same thing with your tunnel. You have a single tile opened up for tech storage, high-tech storage, fricking anything. Use it. Don't leave it there.

**Comment by Norgad** [comment]
@FreeStylaLT Personally, I think that patch of space near med looks really nice....

**Comment by FreeStylaLT** [comment]
Well, then take my advice with a grain of salt, since I personally try to utilize all space I get in my mapping as efficiently as possible.

**Pull request closed without merging**
