### PR TITLE
Chameleon flag now explodes immediately

### PR DESCRIPTION
**Pull request by datlo**
- detonation happens immediately on being lit on fire (as the description implies) instead of when the flag finish burning which is minutes later and will never hit the guy that actually lit the flag on fire

🆑
tweak: Chameleon flag now explode immediately upon being lit on fire
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
so the flag is similar in strength to the boomy pizza box so I'm gonna leave the balance as it was and only fix the bug

**Comment by Citinited** [comment]
Won't this make the flag basically useless? Nobody is going to light it on fire by hand if it'll just explode directly next to them.

**Comment by Kyep** [comment]
I've never seen the camo flag be lit on fire, and given to someone, as a way to kill them.

I have seen the flag used as a booby trap for whoever lights it, though.

**Comment by Nicaragua1** [comment]
I have never tested this but i always thought it worked like piza bomb. It makes more sense that way.  If it does explode when the fire is consumed then its just like a regular bomb but worse because it can be extinguished by anyone

**Comment by Nicaragua1** [comment]
https://github.com/ParadiseSS13/Paradise/commit/28d63f03d0c5b4072f0718bec09280f854927ed1

**Comment by datlo** [comment]
Huh. I guess it's not. Wonder why it was coded to be that way. I'll close the issue. I still think this should be changed.

**Comment by Ty-Omaha** [comment]
"Hey light that flag on fire"

versus

lights flag on fire, runs away / throws at

This is strips all practicality from this, apart from hoping someone randomly lights it on fire

**Comment by datlo** [comment]
... So you paid 3 extra tc to have a minibomb that looks like a flag and takes forever to detonate. Congrats?

This item is NEVER used because it has no point as it is now. Making it an actually effective booby trap would make it actually have a purpose, similar to the pizza bomb. Leave the booby trapped clown flag outside sec, angry shitcurity light it on fire, boom. it's SOMETHING.

If this isn't changed this might aswell be removed because as it is it's useless uplink junk.

**Comment by datlo** [comment]
I have an idea to improve the flag better. Closing this for now, will make new PR either tonight or tomorrow

**Comment by Citinited** [comment]
May I suggest giving it a variable timer? What I envisage is that while the flag is undisguised, you can set the timer to anything between 0 and 20 seconds (its current burn time). This should solve the issue you have with the flag, while also allowing it to continue to be a slow-burning bomb.

**Pull request closed without merging**
