### PR TITLE
Plasmamen Shadowlings no longer burn to death

### PR DESCRIPTION
**Pull request by TullyBurnalot**
Exactly what it says on the title, again. Shadowlings are rejuvenated immediately after hatching, clearing prior status effects (such as the Plasmamen fire stacks).

:cl:
add: Shadowlings are extinguished after hatching, allowing Plasmamen Shadowlings to not burn to death.
/:cl:

### CODE REVIEW

**Comment by The-Driker** [comment]
So does that mean that anyone attacking them while they hatch is wasting their time?

**Comment by TullyBurnalot** [comment]
I am unsure if dying during the process actually stops it, but yes, assuming that they do not die, then it would be useless to attack them.

**Comment by Birdtalon** [comment]
The code will still run yes so if they die before `H.rejuvenate()` is called then they will be revived.

**Comment by TullyBurnalot** [comment]
@Birdtalon You still retain the fire stacks accrued during the transformation. Which means that unless you pack a fire extinguisher and are particularly quick about it, odds are you'll burn to death when hatching as a Plasmaman.

If, however, there's a proc available that does nothing but remove fire stacks, feel free to point it out.

**Comment by Birdtalon** [comment]
@TullyBurnalot try `ExtinguishMob()`

**Comment by taukausanake** [comment]
Doesn't `ExtinguishMob()` do more than just remove firestacks? Like _extinguishing_ the mob? Might work either way

**Comment by Birdtalon** [comment]
It extinguishes the fire on the mob and removes all fire stacks.

**Comment by KasparoVy** [comment]
Can't see why you wouldn't just use ExtinguishMob() in this case

**Comment by Shadeykins** [comment]
Does ExtinguishMob() reset the temperature of the mob as well? Because that's part of the issue too.

**Comment by tigercat2000** [comment]
Not really a balance thing anymore, now that it just puts out the fire.

**Pull request merged**
