### PR TITLE
Three new vehicles from Urist and vehicle folder tree restructuring.

### PR DESCRIPTION
**Pull request by tigercat2000**
This PR does the following:
 * Two new vehicles from UristMcStation - Currently only admin-obtainable
  * Motorcycle (UristMcStation/UristMcStation#204)
  * Sports Car (UristMcStation/UristMcStation#222)
  * Four-wheeler/ATV (UristMcStation/UristMcStation@a3410ae02fd5467bda7e840a573a63bb37691ce0)

  Image of vehicles
  Image of vehicles with humans in them

* Restructures vehicle folders to make a bit more sense and follow the object tree more closely
 * Hopefully this will help with organizing new vehicles.

  Image of folder structure

### CODE REVIEW

**Comment by Nienhaus** [comment]
Glloyd also added in 4 Wheelers 
https://github.com/UristMcStation/UristMcStation/blob/master/code/modules/urist/vehicles/fourwheel.dm

**Comment by adrkiller59** [comment]
>I will upvote any PR that adds new "useless" content rather than PRs that remove "useless" content.

:+1:

**Comment by Spacemanspark** [comment]
HOLY SHIT YES. :+1: x :100:.

**Comment by TheDZD** [comment]
Do they look any different when somebody is riding them, or will players see an empty ghost car driving around?

**Comment by tigercat2000** [comment]
@Nienhaus will port asap

**Comment by ZomgPonies** [comment]
Why are cars and motorcycles a child of trains/cargo? If they're not pulling any wagons, they should be a child of vehicles directly.

**Comment by tigercat2000** [comment]
as far as I can tell it's to reduce the amount of code actually defined in the files, cargo trains already have everything defined that they need

**Comment by ZomgPonies** [comment]
Also, ALL the vehicle code is extremely borked at the moment, as you can see from ambulances. An overhaul would be needed to clean it up.

Without this overhaul, I need to :-1: at adding new content to a broken mechanic.

**Comment by tigercat2000** [comment]
@ZomgPonies I didn't see anything specifically borked about vehicle code, could you specify what you are talking about with the ambulance?

**Comment by Glloyd** [comment]
Yeah, they're defined like that on Urist until somebody writes better vehicle code that is more modular and OOP. Until then ¯\_(ツ)_/¯

**Comment by ZomgPonies** [comment]
Ah fuckit, it's not like they're map-spawned. Just note that I am very concerned at the quality of vehicle code in general.

**Pull request merged**
