### PR TITLE
Updates NOBLE Cyborg sprites.

### PR DESCRIPTION
**Pull request by TravellingMerchant**
Adds improvements to the Shellguard NOBLE series Cyborgs, General shading is improved and their arms are no longer lopsided on the side views. Minor animation details added to the mining version in the form of blue striplights along the claws. One minor difference between the PR version and the preview below is that the janitor version has its neck holes plugged with two purple pixels, to reflect the fact it has a backpack. That is all.
Before:
noble-1

After:
nobleupdatetypes

### CODE REVIEW

**Comment by SamHPurp** [comment]
Please include before photos alongside the after.

**Comment by TravellingMerchant** [comment]
Added

**Comment by taukausanake** [comment]
It's reeeeally tough to find the difference in sprites when the rotating gifs aern't in-sync. That being said I found the difference that is the wire going between the arms on either side. It really makes a difference, the arms looked weird before just jutting off the side like that

**Comment by SamHPurp** [comment]
From what I can tell from the out-of-sync gifs, I think these are an improvement 👍

**Comment by TravellingMerchant** [comment]
Sorry, that gif is the old one from the first NOBLE PR, only one I had to hand.

**Pull request merged**
