### PR TITLE
[PORT] Fullscreen Port from BayStation12 / TG

### PR DESCRIPTION
**Pull request by Spaghetti-bit**
## What Does This PR Do

Adds the fullscreen verb, allowing people to full screen their game.

## Why It's Good For The Game

More pixels. :)

## Images of changes

Main menu:
image

Knockout:
image

Awake:
image

TGUI Example (works with multiple monitors, doesn't cursor lock to the window):
image

## Testing

Loaded a local server, clicked the fullscreen verb. Went ooooh! Ahhhh! Then clicked again.

## Changelog
:cl:
add: Added fullscreen for clientside.
/:cl:

### CODE REVIEW

**Comment by Spaghetti-bit** [comment]
Fixed the merge conflict.

**Review by 1080pCat — APPROVED** [review]
i dont see any issues

**Review by lewcc — CHANGES_REQUESTED** [review]
Can you add a to_chat telling the user how they made their window fullscreen, so that they know how to undo it if they accidentally push it?

**Comment by Spaghetti-bit** [comment]
> Can you add a to_chat telling the user how they made their window fullscreen, so that they know how to undo it if they accidentally push it?

image

image

**Review by lewcc — APPROVED** [review]

**Pull request merged**
