### PR TITLE
Adds a special grenade launcher for nuclear operatives

### PR DESCRIPTION
**Pull request by shazbot194**
image

This PR adds a dedicated grenade launcher as requested by sparten, and agreed apon by me. Currently, it acts like a single barrel shotgun, and costs 12 points, which is 6 less then the M-90, which also has a grenade launcher. This is enough to buy a box and a half of ammo. Although I would be happy to adjust the price.

🆑 Shazbot
Adds: Adds in a stand alone grenade launcher.
/🆑

### CODE REVIEW

**Comment by Decemviri1** [comment]
I'm not saying a security one which fires tear gas would be awesome.... But I'm totally saying a security one which fires tear gas or a flashbang would be amazing

**Comment by shazbot194** [comment]
I fully support this, but I think baby steps is needed.

**Comment by tigercat2000** [comment]
Title is inaccurate, `Adds a special grenade launcher for nuclear operatives` would be better.

**Comment by Denthamos** [comment]
Ooh, a grenade launcher for sec that fires tear gas or capsican gas would be interesting.

**Comment by shazbot194** [comment]
This can be either reloaded by taking out the old shell and putting a new one in, or just putting the new one in and doing a 'tactical' reload.

**Comment by shazbot194** [comment]
This has sat here for months with no word, and I don't want to fix the merge conflicts again, so I am closing this. Please ask for permission if you want to use my assets, but feel free to remake this PR.

**Pull request closed without merging**
