### PR TITLE
AI Optimization, SNPC Removal 2.0

### PR DESCRIPTION
**Pull request by variableundefined**
**What does this PR do:**
Remake of #10307, which sat around for half a year and was kinda accumulating loads of conflicts and all. Also because I accidentally corrupted the PR.

Dead Mobs & Playsound performance PR not included.

- [x] Implement tgstation/tgstation#31778 - Replace AIStatus
- [x] Remove old NPCAI
- [x] Rename NPCAI and NPCPool
- [x] Remove SNPC & associateds features
- [x] Add in IdleNPCPool
- [x] Minor refactor of shuttle move to accomodate 33216
- [x] Implement tgstation/tgstation#33216 - Player Z-tracking
- [x] Implements tgstation/tgstation#33574 advanced mob laziness 

**Changelog:**
:cl:
tweak: Simple animals actually use the new subsystem now 
tweak: What was NPCAI is now renamed to NPCPool - Its the functional equivalent of what it is in tg
tweak: Simple animals actually run on subsystem instead of a process now.
add: idleNPCpool has been added reducing performance impact of hostile simple animals
del: NPCAI Process (That run both SNPC and SimpleAnimals) that was somehow left out by me
del: SNPC & assocaited NPCAI Subsystem
del: Some of space hotel's functions.
del: Bodysnatch gland.
tweak: process_ai has been deprecated
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
Quick merge it before it starts conflicting again!

**Comment by AffectedArc07** [comment]
More PS killing 

*oh yes*

**Comment by Fox-McCloud** [comment]
SNPCs, you will be missed.

o7

**Comment by KasparoVy** [comment]
RIP SNPCs, too funny for this world

**Pull request merged**
