### PR TITLE
Baton Fixes and Cattleprod Buff

### PR DESCRIPTION
**Pull request by Fox-McCloud**
- fixes a rare runtime with batons
- adds some sanity to dropping a cell with batons
- returns the cattleprod to its original status (can fit in backpacks)

Poll:
stunem

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:-1: To the backpack stunprod.
That should be further discussed via forums/ admins and not just done with a vote ingame.
Everything else looks good.

**Comment by Fox-McCloud** [comment]
It was discussed amongst the current maintainers and neither of us are opposed to seeing it come back. 

Relevant points:
- Cargo already has infinite stun batons
- engineers and scientist already have overcharged flashes, which force out a stun
- Security still dominates the field with their ranged instant-stun tasers.
- You can already pre-assemble this in your backpack and slam it together anyway if you want to carry it around in your backpack.

**Comment by tigercat2000** [comment]
@Fox-McCloud I fully agree with letting it come back.
But @Spacemanspark still makes a point, it should be fully discussed among the staff and forums, not just the maintainers.

**Comment by Necaladun** [comment]
Yeah, have to agree the vote is kinda meaingless there.

However, stunprods are basically useless right now. Concealing them would be great to make them useful and give non-lethal improvised weapon options.

**Comment by SamCroswell** [comment]
Don't see why not.
:+1:

**Comment by Earthdivine** [comment]
Already told my opinion but yea, stun prods are in a bad place where they are useless now but giving them back pack space might push them to being overly used.

**Comment by KasparoVy** [comment]
I feel as soon as this pull goes through there'll be stun prods everywhere, it'll be do-it-yourself stunbatons with no downside to them

A lot of valid points have been made but I wish a middle ground could be struck on this sort of thing, but I've not got a clue what it'd be

**Comment by Spacemanspark** [comment]
Have them be two- three use before you have to replace the cell.

**Comment by M3hillus** [comment]
I agree with spacemanspark, Bring back the backpack, up the cost per stun.

**Pull request merged**
