### PR TITLE
New pipes sprites

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do

New sprites for disposal pipes. Sean asked for it during his PR but i couldnt finish it before it was merged.
## Why It's Good For The Game

Upgrade
## Images of changes

image
dreamseeker_h9rRsDbBuC

## Testing

Started the game, looked at pipes.
## Changelog
:cl:
imageadd: new disposal pipe sprites
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
These are good sprites, but I feel like the shading makes them look like they're made out stone.

**Comment by McRamon** [comment]
> These are good sprites, but I feel like the shading makes them look like they're made out stone.

well big chunks of old rusted metal kinda looks like stone

**Comment by S34NW** [comment]
Superb

**Review by S34NW — CHANGES_REQUESTED** [review]
conpipe-j2
image

Seems to have swapped side-arrow directions,. Please double-verify this, as it seems you have correctly fixed some of the incorrect north-south states.

**Comment by McRamon** [comment]
> conpipe-j2 image
> 
> Seems to have swapped east-west directions,. Please double-verify this, as it seems you have correctly fixed some of the incorrect north-south states.

fixed

**Review by S34NW — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
