### PR TITLE
Intercom construction and Deconstruction.

### PR DESCRIPTION
**Pull request by SirBloodBuske**
Intercom construction and Deconstruction. Adds the ability to construct and deconstruct intercoms!

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by SirBloodBuske** [comment]
Welp worked on my end, Lets retry!

**Comment by SirBloodBuske** [comment]
loading paradise.dme
loading interface\skin.dmf
loading maps\cyberiad.dmm
saving paradise.dmb (DEBUG mode)
paradise.dmb - 0 errors, 0 warnings

**Comment by Krausus** [comment]
You added a new file without #including it in `paradise.dme`, so as far as the compiler being run by Travis is concerned, that file doesn't exist, which means the object defined in it doesn't exist, which is bad.

It's building fine locally because, by default, Dream Maker will simply try to include every file it can. Go into build->preferences and disable automatically setting FILE_DIR to get it behaving properly.

**Comment by SirBloodBuske** [comment]
Found it

**Comment by SirBloodBuske** [comment]
I need to redo this whole pull, It's brokes

**Pull request closed without merging**
