### PR TITLE
Adds Plasmaman to Karma Shop

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Allows players to purchase Plasmamen for 100KP

- Please not this species is still a WiP, balancing and suggestions are welcome in a single thread on the forums.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
I guess it's neither a fix nor a feature, just adding them to the shop. Not sure how to tag this.

**Comment by Spacemanspark** [comment]
Hell ya, I know what to aim for now.

**Comment by TheDZD** [comment]
Guess it'd technically be a feature, considering they weren't normally available. Also, may be worth checking if there is a runtime/crash caused by extinguishing a plasma person, as I remember a month or so ago somebody extinguishing a burning plasmaman (I believe it was Necaladun) and a server crash following immediately afterward, although it could've just as easily been caused by something else.

**Comment by ZomgPonies** [comment]
I tested it, there are no runtimes. The crash was unrelated.

**Comment by Fox-McCloud** [comment]
As long as their suits have NODROP on them, I'm ok with them being playable; might as well add NOCLONE to them though--people are inevitably going to clone them and be like "um now what" as they burst into flames and die with no way to get them into new clothing.

**Comment by ZomgPonies** [comment]
Gonna wait for https://github.com/d3athrow/vgstation13/pull/3301 before merging, and resolve any bugs we have.

TO DO: Add in the plasmamen language, which will also solve the random name runtime.

**Comment by SkowronX** [comment]
Most recent commits adds the last of the planned suits.

**Comment by ZomgPonies** [comment]
No special language for Plasmamen for now, until lore is confirmed. Should fix random names.

**Comment by ZomgPonies** [comment]
This is ready for merge.

**Comment by TheDZD** [comment]
Just noticed this now, might want to tone down the armor values on plasmaman softsuits, as the engineering and atmos ones are more armored than they're equivalent RIG suits. The HoS's plasmaman spacesuit might also need to be a bit better than the regular sec one to make up for the fact that plasmamen cannot wear the armored coat.

**Pull request merged**
