### PR TITLE
Adds spraycans, fixes lipstick, modifies scleaner

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit does the following:
 - Adds spraycans as a subtype of crayons.
   - Slight crayon overhaul to make room for this
   - Can spray graffiti, runes, and letters on floors & walls
   - Can spray mobs and paint their face
   - Made in autolathe

 - Fixes & overhauls lipstick
   - Lipstick is now overlay and Blend() based.
   - Also fixes a few bugs with the system.
   - Updates paper code to accomodate for wiping off spraypaint as well

 - Slight modification to space cleaner
   - Space cleaner now cleans your face of lipstick and spraypaint

Player Notes: You can now obtain spraycans for your nefarious gang violence! You can even out-do the clown with your ability to write on the walls! And when he attacks you because his rainbow crayon is pointless, you can spray him in the face and literally make him red-faced! (note: tiger industries is not responsible for any deaths caused by suggestion) 

Admin Notes: Nothing really special.

Coder Notes: The spraycan stuff isn't very self-contained, by necessity. This touches update_body. Crayon code has been changed slightly to allow for letting certain types of crayons write on walls. 

I almost forgot: PICTURES SECTION!
no picture 4 u
no picture 4 u
no picture 4 u
no picture 4 u
no picture 4 u
no picture 4 u

### CODE REVIEW

**Comment by Earthdivine** [comment]
Might wanna comment out the face spraying, I don't know if anyone's fixed the "unable to remove paint from people" thing and we were having people literally get lynched for doing that to others.

**Comment by Fox-McCloud** [comment]
keep the face spraying in---just allow space cleaner and showers to clean it off.

MAI SNOWFLEKE.

**Comment by tigercat2000** [comment]
you can clean it off via a piece of paper or spacecleaner, made sure it worked, no need to comment it out

**Comment by Earthdivine** [comment]
As long as it's remove able, don't need that happening all over again

**Pull request merged**
