### PR TITLE
[Fix][Feature?] Botany Fixes and Telescopic Scythes

### LINKED ISSUE #1011: Botany overhaul issues
Bugs:

Crowbarring spread 1 plants makes hydroponics trays

Potential balance issues:
Botany might need a scythe to start with.
Spread 1 plants obstruct vision if they grow too big.

### PR DESCRIPTION
**Pull request by FalseIncarnate**
- Ports https://github.com/Baystation12/Baystation12/pull/9184

- Prevents deconstruction of soil and invisible soil
 - Fixes #1011

- Fixes spread 1 plants (like glowshrooms) obstructing vision
 - Also mentioned in #1011 

- Adds a verb to eject tanks from hydroponics trays if one is inserted (future functionality)
 - Can't currently put a tank in, but this will be more useful once the atmos portion of botany is working and doing so is enabled.

- Fixes grown items not leaving behind their trash
 - Notably banana peels and corn cobs. Clowns and hillbillies rejoice!

- Adds 15% chance for a watermelon to leave behind a pack of it's seeds when eaten.
 - Slicing watermelon will not produce seeds ever

- Replaces the Janitorial ERT members' plant-b-gone sprays with new Telescopic Scythes!
image
image
 - Can be collapsed to fit on a belt or fit in pockets/bags
 - While collapsed, it loses a large amount of it's damage, is not considered sharp or as having an edge, and cannot cut vines like a normal scythe.
 - While extended, it is functionally identical to normal scythes
 - Extending and collapsing a telescopic scythe has some awesome sounds from Freesound.org (credits in code comments)
  - Unobtainable by crew without stealing it from the ERT or admin-spawning

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
New fixes/adjustments:

- Fixes Diona Nymphs getting a color overlay, which was causing them to become darker and look terrible.
 - They now look like they did pre-#980

- Adjusts the equation for hydroponics trays calculating light level based on their turf (lid down)
 - All trays in hydroponics should now have a light level of 3 or higher, this is subject to further adjustments to fine-tune

- Fixed messages from the eject tank verb to not say things like "the the tray (#45)"

**Comment by Fox-McCloud** [comment]
Thanks about the Nymph change; they looked so ugly.

**Comment by FalseIncarnate** [comment]
Not a problem, the same thing affects other mob harvests like killer tomatoes and walking mushrooms, but i left those alone since, in theory, adjusting the product color could result in different colored versions of them (blue killer tomatoes? i'd have to test more).

Also, the adminbuse clown pods still get the green overlay that diona nymphs had, which gives them a somewhat zombie-like green tint. it's appropriately creepy enough to leave be.

**Comment by fj45** [comment]
Do you have any pictures of how those overlays look?

**Comment by FalseIncarnate** [comment]
they apply a flat color over the sprite, just like how it works for plants. the problem is the mob sprites are already colored, so they just stack/blend and look bad in most cases.

**Pull request merged**
