### PR TITLE
Ports TG antag alert sounds

### PR DESCRIPTION
**Pull request by datlo**
Ports antag alert sounds that plays at roundstart from tg for the following antags : 
- Traitor
- Traitor AI
- Nuke Ops
- Changeling
- Cult
- Wizard

Zip of audio files :
[antag.zip](https://github.com/ParadiseSS13/Paradise/files/2591910/antag.zip)

🆑
add: Added antag alert sounds that play at roundstart for most major antagonists, ported from TG.
/🆑

### CODE REVIEW

**Comment by variableundefined** [comment]
Haven't had a sound PR for ages. I like most of those sounds.

You could probably play the wizard sound by using addtimer to make it delayed instead? It is best to use it rather than leave it in unused forever.

**Comment by datlo** [comment]
I'll see if I can use addtimer on all the sounds, actually. It's an issue for all the sounds, it's just the wizard is the only one short enough that it's really noticeable.

**Comment by variableundefined** [comment]
It's probably best to use addtimer. Much more kosher.

**Comment by datlo** [comment]
Added wiz alarm with a timer delay. The others sound fine as it is, and I don't wanna add unneccessary delays to the procs.

**Comment by KasparoVy** [comment]
Man some of these are fantastic. Tator > Bloodcult > Ops > Ling definitely my favourites of the bunch.

**Comment by datlo** [comment]
SEND_SOUND didn't work when I tried it; i probably fucked it up. i'll look at the code and try it again.

**Comment by variableundefined** [comment]
SEND_SOUND is a define macro that in turn call DIRECT_OUTPUT that essentially is just <<.

You cannot use a macro in an addtimer, only an actual proc.

**Pull request merged**
