### PR TITLE
Adds in E-Daggers

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over e-daggers, from TG: https://github.com/tgstation/-tg-station/pull/11232

Simply put, a stealth weapon that looks and functions like a pen. That said, when activated, it reveals its true nature; an energy blade will extend from the pen.

Has a force of 18 when active---will set you back 2 TC.

### CODE REVIEW

**Comment by Markolie** [comment]
:+1:

**Comment by Spacemanspark** [comment]
Nice.

**Comment by KasparoVy** [comment]
Woah, that's wicked! Great stuff.

**Comment by M3hillus** [comment]
I have to ask though. Do they make for great thrown weapons?

**Comment by Regen1** [comment]
@M3hillus It has a throwforce of 35, so yes!

**Comment by Spacemanspark** [comment]
https://github.com/tgstation/-tg-station/pull/11550 <-- Might wanna check that out.

**Comment by Spacemanspark** [comment]
Unless you already have that, can't review the code with my phone.

**Comment by Fox-McCloud** [comment]
They have in-hands.

**Comment by Spacemanspark** [comment]
Ah, alright.

**Comment by Regen1** [comment]
Ready for merge?

**Pull request merged**
