### PR TITLE
Adds Coroner role in its own right

### PR DESCRIPTION
**Pull request by SamHPurp**
Building on the back of a few great PRs, namely:

* NTPS: Requests Console Based Shipping #6178
* Autopsies No Longer Need Surgery #6937
* Adds stuff to autopsy #6613

This makes the Coroner its own role on the station and no longer an alt text of regular doctor.

The coroner loses Surgery access, but otherwise can functionally perform as a MD if the situation requires it. This'll mean that functionally the CMO gains an additional doctor they can call on, and the Detective will get proper autopsy reports.

image

- [X] Coroner code changes

- [X] Office remapping

- [x] SQL for database to scrub 'Coroner' alt text

SQL queries required:

`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, 'Medical+Doctor=Coroner&', '') WHERE INSTR(player_alt_titles, 'Medical+Doctor=Coroner&');`
`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, '&Medical+Doctor=Coroner', '') WHERE INSTR(player_alt_titles, '&Medical+Doctor=Coroner');`
`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, 'Medical+Doctor=Coroner', '') WHERE INSTR(player_alt_titles, 'Medical+Doctor=Coroner');`

Misc intentional considerations:

- Kept the bin away from the autopsy table
- Limited formal wear for the bodies
- Medical records laptop
- Left the scalpel, even though its no longer necessary for autopsies.

:cl: Purpose2
del: Coroner no longer alt title for MD
add: Adds Coroner job as its own job.
add: Adds a swanky new office for the Coroner.
/ :cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
I'm actually not salty about this.

**Comment by DesolateG** [comment]
@SamHPurp I assume it's adding an extra, not subtracting from doctor?

**Comment by SamHPurp** [comment]
@DesolateG Correct. This adds 1 additional job to the station.

**Comment by Taaketa** [comment]
Would it be worth to add a Fax for the Coroner to use so he can fax reports to the Detective? Actually does the Detective have a fax?

**Comment by SamHPurp** [comment]
@Taaketa the detective doesn't. It could be added, but I think, if you were to do that, you'd be better off making an office for the Coroner out of the Exam room.

**Comment by DesolateG** [comment]
huh.. would be neat to map the examining room into the coroners office.

**Comment by Taaketa** [comment]
@SamHPurp I suppose that'd be cool, although having the Body scanner in there moved to somewhere else would be good including the locker with the spare medkits.

**Comment by SamHPurp** [comment]
I think for now, and for Boxstation, lets leave it without their own office, but maybe it'd make sense in @Twinmold93 's Ragnarok or similar.

**Comment by Fruerlund** [comment]
Support from here. 

I would also support shrinking the exam room and expanding the morgue. Perhaps an airlock to connect an examination room and the morgue itself.

**Comment by tigercat2000** [comment]
simply removing the alt title will break things, this will require complicated SQL queries to fix any existing characters with the coroner alt title

**Comment by SamHPurp** [comment]
@tigercat2000 Who would know this well enough to lend me a hand?

**Comment by Anticept** [comment]
SQL would be nice for a one time fix, or you could just put in check code to change them to doctor...

**Comment by scrubmcnoob** [comment]
Maybe connect the exam room and morgue like @Fruerlund said.

**Comment by Jovaniph** [comment]
Aside from the technical issues...I like this...this is good...yaya

**Comment by Fox-McCloud** [comment]
Not a big fan; Coroner doesn't have enough "meat" to it, to be its own independent job, especially since the detective already has morgue access.

The request console seems like a good idea *maybe* the body scanner, but this still doesn't really give the job enough "meat" for it to be independent.

Also, map PR without pics 😠

**Comment by SamHPurp** [comment]
@Fox-McCloud Updated with an image, highlighting the only changes.

People already treat this like a job already, since it comes as an alt text. At worst, all this does is add an additional doctor.

Only outstanding issue that I'm conscious of is the SQL that @tigercat2000 mentioned. Of which I unfortunately know nothing about.

**Comment by Tayyyyyyy** [comment]
If this does get merged, can "Medical Examiner" be added as an alt text of coroner? Irl, [coroners don't perform autopsies](http://www.npr.org/2011/02/02/133403760/coroners-dont-need-degrees-to-determine-death).

**Comment by Doukhan** [comment]
Can't really see this as necessary, they just don't do enough ATM to justify a separate role.

**Comment by Anticept** [comment]
@Fox-McCloud Compared to barber & psychologist, coroner is a good step up.

**Comment by Lady-Luck** [comment]
>Compared to barber & psychologist, coroner is a good step up.

Let's not pretend those jobs are anywhere near acceptable quality.

**Comment by Lady-Luck** [comment]
Okay, so, I'm against this PR for a few reasons.

#1: It's essentially just a stripped down version of the Medical Doctor job. Paramedic has an ambulance, Psychiatrist (which is not a well designed role) at the very least has an office with access to a straight jacket and happy pills. There is absolutely nothing unique they're capable of that an MD can't do.

#2: Making it easier to have the IDs and PDAs of the dead returned to the HoP is a pretty hard nerf to antagonists looking for a non-violent approach for additional access.

#3: That we essentially already can have this role via the alt text should be an argument _against_ adding this as a full fledged job, not for it. Until there's more reason for it to be more than an alt text, it should stay an alt text.

**Comment by taukausanake** [comment]
I already know the argument against what I'm going to say, but this feels like a karma job and one I would get. It _does_ still need some fleshing out but I like the concept of coroner being it's own job. As it is, it's more like a lazy medical doctor job, just pay attention to the dead bodies and maybe on your offtime make Frankenstein monsters. I wouldn't mind that though, sounds like fun.

Before someone says it, this won't be karma because it's a job that was technically already on the station and you don't turn existing things into karma things

**Comment by Fruerlund** [comment]
We should be coming up with new jobs instead of shooting them down. Even if they offer just a bit it is still better than nothing.

We should be trying to help battle our playercount and to come up with unigue new features(terror spiders, space pirates, new map, species)  and jobs so we don't end up behind stale with our only thing keeping us alive is the playercount. Otherwise we are going to die, just as every other game that becomes old AND never updates. 

Frankly the argument that a coroner does not have enough to do to be a separate job is in my opinion not valid. Hell, the libarian has less to do(until we get devils)  The coroner is a requirement for a succesfull forensic office. It has its own items/area and features related to the job. It has potential for roleplay, and he can also function as a medical doctor when there are no dead bodies.

**Comment by Lady-Luck** [comment]
Making our least fleshed out jobs the baseline for acceptance is flawed thinking in my opinion.

**Comment by Fruerlund** [comment]
But is that not exactly what we are countering here by giving the coroner more tools to do his job, while allowing for more players to participate in the shift.

**Comment by Lady-Luck** [comment]
If that's what you want, add another doctor slot.

**Comment by Tayyyyyyy** [comment]
I think it's a good idea to add this job, even if it's not the most fleshed out at the moment. The popularity of shows like Bones is a testament to the fact that forensic pathology can definitely be fun and interesting. We may not be there yet, but adding the job slot is a good first step to creating something potentially great.

**Comment by Lady-Luck** [comment]
There's an important difference between 'not the most fleshed out' and 'not fleshed out at all'.

It's just a doctor with less access. We can add more doctor slots at any time.

Something that makes them unique should come with the implementation, not something that is to be thought out at a later date.

**Comment by Dinarzad** [comment]
Adding another doctor slot does nothing, because as a Doctor alternate title you're not exactly going to see that slot used ONLY for Coroners.  You could well end up with an additional nurse or surgeon, rather then a Coroner.

Splitting the Coroner off into it's own job means you will have precisely ONE Coroner, if one at all, so you're not over crowding the Morgue (AKA: Rounds where all the MD crew had coroner for their alt title.) and Medical staff gets another full fledged doctor on top.
The job is more fleshed out then some of the basic roles right now, yes it could use some TLC in the future, but there's no reason NOT to start the process now. It'll be okay if it's somewhat imperfect for a bit, because it is right now already.

**Comment by Fox-McCloud** [comment]
>Compared to barber & psychologist, coroner is a good step up.

The existence of one poorly fleshed out job is not a legitimate excuse for the existence of another.

Medical doctors and detectives can already do what the coroner does; that's a lottt of overlap; this is inherent in the psychologist role, as well (which is one of the reasons it's not a particularly good job).  

Barber at least has his own unique mechanics (in an incredibly low responsibility job). 

Coroner doesn't have anything unique about them; they fit *very* well into the niche of alt-job as opposed to actual job.

**Comment by Anticept** [comment]
I would argue that we need more jobs even if just semi-fleshed out, than hold things back because it's not considered "complete". There's still just not enough jobs for the high pop that is on paradise, and the speed in which things are being adopted is slower than the growth.

There may be overlap, but I fail to see why that in itself is a problem. There's absolutely nothing wrong with that, as long as people aren't stepping on each other's toes. In addition, the coroner job slot adition doesn't just add one extra medical staff, it also prevents the loss of a doctor who might be trying to fill the coroner role.

That and, we still have the issue where the detective is far too damn busy once the killings begin.

**Comment by KingPhilipIII** [comment]
While we're on the subject of the morgue and its associated care and such, I'd just like to say I quickly run out of room in the morgue as roboticist on busy rounds. Eventually I give up on every corpse having its own thing and just start labeling body bags and throwing them in for time's sake. 

If we're having someone dedicated to body handling it could actually get quite busy.

**Comment by Doukhan** [comment]
Officially I think it's the chaplains job to dispose of superfluous corpses, not that they ever do mind.

**Comment by Tayyyyyyy** [comment]
I feel like at this point, since it's sort of in a grey area between alt-title and real job, it's a matter of whether we want coroner/medical examiner to be a bigger role or not. If we're content with it being a pseudo-job, then this PR is unnecessary. But if we want to encourage people to build on this role and make death investigation more interesting, then it's a good idea to move the role to full job. It's hard to get a new job right right away. I think making coroner a full job and then iterating on it is better than waiting around for the perfect PR that will birth a fully formed coroner job onto the station.

**Comment by tristan1333** [comment]
@Doukhan Wrong, it's actually the chefs. And they definitely do when they can.

**Comment by taukausanake** [comment]
@tristan1333 They would if they still had morgue access

**Comment by Lady-Luck** [comment]
>I feel like at this point, since it's sort of in a grey area between alt-title and real job, it's a matter of whether we want coroner/medical examiner to be a bigger role or not.

Don't get me wrong, I would love that. But they need _something_ unique about them in their initial implementation.

**Comment by SamHPurp** [comment]
@Lady-Luck like?

**Comment by SamHPurp** [comment]
So, I built the coroner an office. This has obviously harmed the Exam room, turning this even more into a bit of a store room.

Thoughts?

image

**Comment by Fox-McCloud** [comment]
>Finally, people aren't going to want to make autopsies interesting or complex as long as it's a half-job, as this would only push people away from spending the time on it.

This is literally circular.

"We need to have the job so we have a reason to have the job".

"we need to add the job so people have a reason to develop it so there's a reason for the job".

**Comment by taukausanake** [comment]
@SamHPurp Can you move the office one tile to the right (and the supply pipe) so that the Exam room has a little more space? Two tiles for a room is awful and I see no problem with having the glass wall and door right against the two airlocks

**Comment by Anticept** [comment]
@Fox-McCloud I'm talking about people development and expanding the role, but since it doesn't officially exist, it's difficult to do any development of it. It's actually a catch 22. You don't want to make this its own job because it doesn't have enough "meat". I'm arguing that changes to the coroner "half-role" already have an uphill battle, because small changes are always going to have to contend with where it fits with the detective and the rest of medical. Committing to the idea it should be it's own role, and taking steps towards that, will be far more effective in making progress on it than being defeatist about it.

In addition, I would be afraid of doing any serious work expanding the tasks of the coroner due to the tendency around here for major changes to get shot down if they aren't already demonstrated on other servers. There's almost no spark in paradise's spirit to dive into uncharted territory, and it's frustrating. It's to the point where there's now a meme that if you want to try something new, you have to first develop it on /TG/, then port it.

That's one of my motivations on why I wrote the proposal process that I sent the server administration and you. I'm hoping it will help with some of that 'spark'. I'd even say the coroner can be one of those jobs that could go through that process to see where it could go. But first, there has to be movement on officially adopting that proposal process in order to take advantage of it.

**Comment by Fox-McCloud** [comment]
>I'm talking about people development and expanding the role, but since it doesn't officially exist, it's difficult to expand and develop any of it. It's actually a catch 22. You don't want to make this its own job because it doesn't have enough "meat". I'm arguing that changes to the coroner "half-role" already have an uphill battle, because it's always going to have to contend with the context of where it fits with the detective and the rest of medical. Committing to the idea it should be it's own role, and taking steps towards that, will be far more effective in making progress on it than being defeatist about it.

This has been disproven time and time and time again. We've added a number karma jobs that have little to no "meat" to them for various reasons or justifications; none of them have generated any new mechanics or additional gameplay; the mechanic and barber may be the sole exceptions to this (and neither of them has gone anywhere).

This is the crux of what I'm getting at. You're suggesting that merely by making it's own job, it's going to encourage and give justification to additional features, gameplay, and mechanics being added for the role. I think that's absolute and utter nonsense, because that hasn't happened in the past. Making this its own job is just a +1 medical job, effectively, with not much future potential (especially, again, due to overlapping with not one, but two other jobs). 

Additionally, the argument could also be made that nothing is stopping individuals from expanding or adding to that specific current avenue of medical...but again, this is hardly occurring, and I would posit, still is unlikely to occur given the past.

And that's why it's circular to suggest that this needs to be its own job so that more meat can be added to it; coders aren't doing that *now*. There needs to be justification and meat for a job to exist *first*, not the other way around.

**Comment by Anticept** [comment]
> This has been disproven time and time and time again. We've added a number karma jobs that have little to no "meat" to them for various reasons or justifications; none of them have generated any new mechanics or additional gameplay; the mechanic and barber may be the sole exceptions to this (and neither of them has gone anywhere).

If you are talking about the ones that are available now? They do bring their own unique elements, and to say otherwise is fucking disingenuous and an absolute total crock of malarkey.

- Brig phys - handles treatment of prisoners and fills the role of physician presence during executions, and is the extra hand to get prisoners to medical and back again if more extensive treatment is required. Due to the karma cost, brig phys are also usually more capable than medical players. Enterprising brig phys even set up some extra things in brigbay so the trip doesn't have to be made. This is actually an **incredibly USEFUL job** for security; and it SHOULDN'T be a karma locked job, just one with steep playtime requirements in medical and sec.

- NT Rep - clever admins have taken advantage of the NT Rep's role, and they have acted as the IC bridge between centcomm and the station when the captain is unavailable. In addition, they often fill the role of workplace mediator, mainly because the IAAs really should be a higher playtime requirement job... players in this role are often unreliable due to lack of understanding of rules and SOP). This role has found a comfortable place in the game despite clearly being overlapped by IAAs and the Captain.

- Blueshield - Do I really need to explain this one?

- Sec Pod Pilot - They are the ONLY security officer that can effectively fight in space without having to jump through hoops and raid eva (they come with a jetpack). Often the ones that have to hunt down the "run to spess" antags. Yes, security has hardsuits, but they often need engineering/AI's cooperation to actually get outside the station due to the way airlocks work. Sec pod pilot is the only one who can do that non-destructively AND quickly.

- Magistrate - Largely useless job due to how most gamemodes function, but when traitors and changelings are running amok, these players are incredibly useful to security when overwhelmed. In addition, some of us actually like handling legal matters and create gameplay out of it.

All that said, I can also tell you, using karma jobs as an example is terrible. There's a negative stigma about changing karma jobs at all.

> And that's why it's circular to suggest that this needs to be its own job so that more meat can be added to it; coders aren't doing that now. There needs to be justification and meat for a job to exist first, not the other way around.

There is justification, and we just told you what it is. I'm sorry that you don't see it, but 12 people disagree with you, and those are the ones that just bother to come participate on github. This isn't just about giving the job unique elements in code, but that it's also a role that we've said repeatedly is needed for various reasons. To reiterate some of them, should they be unclear:

1. The detective is often too busy working with security officers in the field. If he finds the body first, great! But that often isn't the case. Because of how busy the detec is, I find it a bullshit reason to argue against a dedicated coroner slot. Which comes to point 2.
2. We have multiple people responsible for recovering bodies in the station, but there is NOT ONE JOB in medical who's responsibility is to report foul play. As such, some murders go unreported amongst the chaos. I'd even say a large number of them go unreported. That's one of the primary reasons I've personally advocated for making the coroner a dedicated job; it would finally be someone's responsibility to be investigating causes of death and reporting them to security. Which brings us to point 3.
3. Making it a dedicated slot ensures that there's always potential for a coroner to be on station. Right now, I could pick the coroner alt-title, and it would be a dice roll to get it especially during peak hours when it's needed most.
4. Someone who is keeping an eye on the indicator lights in the morgue trays. Not a big problem but it's still useful.
5. Someone who is responsible for ensuring ID cards get terminated appropriately, and can return items to their departments. Right now it's a damn mess.
6. Antag potential. A coroner antag could be quite beneficial to a team of antags in some cases. They could sneak ID cards and items off the dead a little bit easier than other medical staff can. In fact, a coroner carrying an assortment of card in his or her backpack could quite easily say he was turning it in for termination, and it would honestly be believable as long as they aren't caught red handed. I would even argue that they could get caught in a department and say they used the card from the dead to return equipment and still possibly get away with it.

That enough reasons?

**Comment by jughu** [comment]
Buff deteciv gameplay 👌

**Comment by ZomgPonies** [comment]
Agreed, as someone who plays coroner regularly, I'd like to see this be a dedicated slot.

**Comment by Lady-Luck** [comment]
Let it be known that after one too many shifts recently where I was up to my armpits in corpses I have changed my mind. The addition of a Coroner's office also remedies my main complaint.

**Comment by SamHPurp** [comment]
Imma stab someone.... well at least I fixed it.

------

Right, so... I've updated this with an office, incorporated all the feedback.... and this is what I'd love for @Necaladun @FreeStylaLT @ZomgPonies @Crazylemon64  to review if you would please. I've updated the original images at the top. 🎉

**Comment by deep-fried-faceplant** [comment]
Anticept hit the nail on the head. There's demand for what the job does, and enough content for the job to exist.

**Comment by Anticept** [comment]
There is one thing I would miss though if this gets merged.

The hilarious RP when your surgeon is the coroner.

**Comment by SamHPurp** [comment]
@Anticept Scrubs did this too if I remember right... the incompetent as fuck doctor became a mortician.

**Comment by taukausanake** [comment]
@Anticept I'm sure you can still do it. Aren't you considered a backup surgeon in this PR? You can totally say you've worked on enough bodies to know there is a good chance the patient will come out alright.
"Yeah, I've practiced rearranging organs and setting bones on a number of people. Granted they weren't alive but hey! I got this"

**Comment by SamHPurp** [comment]
@taukausanake I actually took off Surgery access from the Coroner. I'm not totally opposed to adding it back in if people feel the need.

**Comment by taukausanake** [comment]
@SamHPurp Yeah but you said they can still function as an MD so nothing really changes. They got their surgery table after all and with lack of anesthetics or the computer with surgery instructions I can see this being the dreadful last resort to getting surgery done on yourself

**Comment by SamHPurp** [comment]
@taukausanake Yep, fine to /do/ surgery, but I did remove their immediate access to that door.

**Comment by ProperPants** [comment]
Could you change the name of those little things that store bodies? They're currently called "morgues," which is... uninspired to say the least. Maybe "storage units?"
2017-04-21 22_18_40-space station 13

**Comment by SamHPurp** [comment]
2 weeks on since I last asked for feedback, I'll try again.

Feedback please @TullyBurnalot @Necaladun @FreeStylaLT .

Even if its a "give me a week", some sort of response would be nice....

**Comment by SamHPurp** [comment]
@Cid777

**Comment by Necaladun** [comment]
@SamHPurp 

Pinging me on github doesn't seem to send me an email anymore or anything, you're better off pm'ing me if you want direct feedback on things. 

I do like the look of the morgue as a lot more professional, but otoh I've always liked the morgue as a dark, tucked away area. It can be a great place to steal some items and IDs from for traitors, or just hide away in for a smoke break for regular doctors. The creepy ambience there wouldn't suit it anymore if it's so lit up and occupied.

I don't really think there's enough here to justify this as it's own job however. There's very little work for autopsies specifically, and it doesn't take long to do. Taking surgery access away makes them less useful than a normal doctor, in some ways just another psych. It's just not a large enough niche to justify a dedicated job role like that. 

If autopsies were more detailed or more often actually required, I can see the niche, but in general I just don't see this being needed enough to justify a job dedicated to it.

**Comment by SamHPurp** [comment]
@Necaladun 

Thank you for taking your time to feedback. This area is still dark, it is certainly not well lit:
image

I feel as though there is more meat on the bones than not an insignificant number of jobs already on the station. You obviously disagree.

Is there any middleground we can reach on this? Or is the goalpost for this reworking Autopsies? In which I'll close this PR.

**Comment by Fruerlund** [comment]
At this point I feel it is pretty clear to me atleast. 

As a coroner it is correct that there may not be lots of stuff to do as much as some of the other jobs have. 

However I feel that it would be a dissapointment to kill this Pull Request just because it doesn't add hundreds of different things. It is true that this PR may not add a lot of new features but it adds a LOT of features on the roleplay front.

In the end, we should not kill something that improves our quality even if it is just a little bit or something that makes paradise unique from other codebases.

**Comment by Anticept** [comment]
@Necaladun did you see the big wall of text I posted? There's more to the coroner than autopsies.

And while I agree the morgue is practically a free place to nick ids and equipment, it also would make a coroner antag very powerful, as well as the coroner being a valueable target. I feel as though there's a lot of give and take here, and we should at least *try* it for a week.

**Comment by tigercat2000** [comment]
@Anticept It's not really feasible to "try" a job for a week, it'll be injected into not-easily-editable fields across the SQL database. Alt titles, job preferences, etc.

**Comment by Anticept** [comment]
@tigercat2000 point taken.

That said... would it not be a good idea anyways to have a bit of sanity check code that if someone has an invalid job set, default them to assistant, and if invalid title set, default to the first?

**Comment by ZomgPonies** [comment]
@Necaladun  Autopsies should be a side-job to the coroner, for when there's nothing else going on. His primary task is taking care of cloning, and this is VERY important to the server. Having someone dedicated to bringing dead players back into the round is needed with the populations we have. An efficient cloning process is of benefit to all non-antags.

**Comment by SamHPurp** [comment]
@ZomgPonies and everyone else. The concepts been approved. 

I'm going to fix the conflicts... but getting the SQL query may take a bit longer. Any one with experience with SQL, I'd love a hand / guidance.

**Comment by SamHPurp** [comment]
Much love to @FlattestGuitar for help with testing the SQL queries.... this SHOULD work.

`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, 'Medical+Doctor=Coroner&', '') WHERE INSTR(player_alt_titles, 'Medical+Doctor=Coroner&');
UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, '&Medical+Doctor=Coroner', '') WHERE INSTR(player_alt_titles, '&Medical+Doctor=Coroner');
UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, 'Medical+Doctor=Coroner', '') WHERE INSTR(player_alt_titles, 'Medical+Doctor=Coroner');`

Does this get captured and ran by yourselves on merge, @Fox-McCloud @Crazylemon64 ?

**Comment by Anticept** [comment]
@ZomgPonies and it's a benefit to antags when the coroner is one. A coroner antag is a HUGE benefit to them.

**Comment by StubbsPKS** [comment]
I like to play coroner, and I usually end up relatively busy with just doing autopsies so I can see adding an SOP for the Coroner to be in charge of cloning keeping the role pretty busy throughout the round.

You'll need to find a way to stop people from just dropping bodies at the cloner for cloning though since you can't see that area from the coroner's office.

**Comment by SamHPurp** [comment]
Don't panic. I'm terrible with Git apparently. Hang on...

**Comment by taukausanake** [comment]
@SamHPurp can't be worse than me. I accidentally made a pull request to Paradise on a meme number. Fox was disappointed in me

**Comment by SamHPurp** [comment]
@Fox-McCloud @Crazylemon64 @TullyBurnalot So, assuming you guys are happy with my pidgeon SQL queries, this is now good to merge. 🎉

**Comment by Necaladun** [comment]
The name seems to imply autopsies, so there -might- be a better name.

Could I get some form of sample job description and role, and a bit of SoP? Doesn't have to be perfect, just a rough outline.

**Comment by Anticept** [comment]
@Necaladun you already have a lot here:

https://nanotrasen.se/wiki/index.php/Standard_Operating_Procedure_(Medical)#Coroner_Procedures

https://nanotrasen.se/wiki/index.php/Guide_to_Cadavers

In addition, you have tidbits from my post up there (https://github.com/ParadiseSS13/Paradise/pull/7014#issuecomment-292079708)

**Comment by TullyBurnalot** [comment]
@Necaladun Ran this by the Portuguese version (Médico Legista), Coroner is spot-on for what they do.

**Comment by SamHPurp** [comment]
Coroner still seems to me to be the best term. Perhaps Mortician, but that seems even more the wrong way.

**Comment by Anticept** [comment]
Coroner isn't just autopsies.

Per wikipedia: "A coroner is a person whose standard role is to confirm and certify the death of an individual within a jurisdiction. A coroner may also conduct or order an inquest into the manner or cause of death, and investigate or confirm the identity of an unknown person who has been found dead within the coroner's jurisdiction."

A quick google search for coroner definition resulted in "an official who investigates violent, sudden, or suspicious deaths."

I think coroner is spot on.

**Comment by Tayyyyyyy** [comment]
Coroners in the US don't perform autopsies (in fact, in many states they're elected, so there are no requirements to have a medical degree). In SS13, it helps that the surgery aspect of autopsies was removed so coroner could work. "Medical examiner" would be the more precise term for the medically licensed professionals that actually conduct the autopsies. I'm also a fan of "forensic anthropologist" but not all medical examiners have a degree in forensic pathology.

**Comment by Anticept** [comment]
@Tayyyyyyy depends on the state.

**Comment by taukausanake** [comment]
Make Mortician an alt-title. The ones Tayyyyyy said also sound good

**Comment by Necaladun** [comment]
What would their duties involve (Things they can be fired for refusing to do), what can they do but aren't expected to, and what are the specifically not expected to do (surgery) I think clarifies what I mean.

**Comment by taukausanake** [comment]
If in charge of cloning then they can be fired for not cloning people if the cloners are not exploded or keeping a mess of dead bodies around their workspace/maybe Medbay. They _can_ do surgery but are not expected to because that's the surgeon's job unless they are short on surgeons. I think something they are not expected to do would be to make Frankenstein monsters but that would take away from the job and honestly what else would be done with useless bodies besides be sent to the chef for more meat?

This is all my understanding of it though. I'd play this job just to practice surgery and Frankenstein-ing and help out with the pile of bodies because someone has to do it and keep order about it

**Comment by Anticept** [comment]
The Coroner SoP is pretty much a huge start to begin with, and add cloning oversight.

The coroner must also report to the relevant head of staff, except civilians, that one of their subordinates have irreversibly expired, and will not be returning to duty.

**Comment by coldud13** [comment]
One thing that I noticed while playing as a coroner recently, they don't spawn with an internals box in their bag.

**Comment by Crazylemon64** [comment]
here we gooooooooooooooo

**Pull request merged**
