### PR TITLE
Removes Icy Veins

### PR DESCRIPTION
**Pull request by theColdflame**
As title. Shadowlings are incredibly powerful compared to other antagonists and have a very high winrate, Icy Veins is a significant part of this but it's not a core part of a sling's kit. There's little skill involved in using this ability, and its highly damaging nature runs contrary to the general style of the gamemode (capturing people alive and converting them).

🆑 Coldflame
tweak: Shadowlings no longer have the Icy Veins ability
/🆑

### CODE REVIEW

**Comment by KasparoVy** [comment]
Tellem

**Comment by Regen1** [comment]
Could we perhaps tone it down, so it does minimal damage while still slowing down / incapacitating them?

**Comment by theColdflame** [comment]
I could remove/remove the frost oil instead but that still leaves the issue of 'click a button to stun everyone on screen' as a base tier ability with a 25s cooldown.

**Comment by Regen1** [comment]
I'm not sure if it should stun, but a "reduce combat effectiveness of those around me"

**Comment by davidchan13** [comment]
Remove screech. Vampires and Clings both have have it, multiple antags having the same ability is goofy. Just lower the range of icy veins so its only going to affect people within 2-4 tiles of the sling.

**Comment by DesolateG** [comment]
sonice screech and blindsmoke are abilities that take quite a few thralls to achieve, so please stop attempting to compare icey veins, a starter defensive power, to them.

**Comment by Fox-McCloud** [comment]
`Robust Coffee is also very easy to get, it stops icy veins.`

This is a very good point, and now that I think about it, yeah, I think this has convinced me.

**Comment by davidchan13** [comment]
@Aracino If that's true then the PR should be to fix it so that jaunt stops all other sling powers from being activated, not removing them.

**Comment by bigfatbananacyclops** [comment]
Because shadow walk its self is OP, you can do abilities while jaunting, im aware of that, so, the PR should be at fixing jaunting.

**Comment by tigercat2000** [comment]
With how easy it is to counter this plus the fact that this is just the starter defense ability, it really doesn't need to be removed. 

We do, however, agree that using it while jaunting is a problem.
Feel free to make a new PR doing that.

**Pull request closed without merging**
