### PR TITLE
Players job banned from syndicate can no longer play emagged drones

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
:cl: Tayyyyyyy
fix: Players job banned from syndicate can no longer play emagged drones
/:cl:

### CODE REVIEW

**Comment by HugoLuman** [comment]
To be fair, the wording of drone laws imply more to me that drones _ignore_ other beings, not avoid them.

**Comment by Tayyyyyyy** [comment]
I think it's pretty clear from the text you are given upon becoming a drone that you should try to avoid other beings whenever possible:

drone

Either way, this won't affect you as a regular drone in any way. Just make it so that people will stop trying to get emagged on purpose.

**Comment by Birdtalon** [comment]
No. This kind of idea is horrible. You've punishing all players for the actions of a few. The only thing here that should ever make it into the game is respecting the antagonist ban. Kicking all players out because a few people look to get themselves emagged is like trying to demolish a single building with an atomic bomb.

**Comment by Tayyyyyyy** [comment]
This isn't punishing players at all. If you like playing drone, you can continue playing drone. You can just rejoin as a drone.

If you're playing drone so you can have a chance to get emagged, then you're already doing something problematic. Being emaggable should not be a part of your motivation to play drone.

I'm actually in favor of removing emaggable drones entirely, but I thought this was a fair compromise.

**Comment by Ralta** [comment]
Initially I was against it for similar reasons to Birdtalon, but after re-reading it, I feel like it is a good compromise. I disagree that the laws imply a drone should actively avoid a dangerous situation unless it puts them in the way of a being; they have no self-preservation law, so they should just be going wherever there's damage. That said, this change would prevent intentional attempts at being emagged while still allowing the antag the possibility of getting a little helper.

I'm gonna read that thread you posted to see some more opinions first 😁

**Comment by DesolateG** [comment]
@Tayyyyyyy  does it ghost the player AND THEN proc the offer?

**Comment by Tayyyyyyy** [comment]
It works the same as an antag ban, it offers first, and then when someone accepts, it ghosts the player. Maybe it should ghost the player first...

**Comment by SamHPurp** [comment]
Outside of just removing emagged drones from even being a thing - this is a good compromise.

**Comment by DesolateG** [comment]
@Tayyyyyyy ghost the player first then proc and I'd find this fine.

**Comment by Tayyyyyyy** [comment]
Okay! That does make sense. I'll have time to implement and test that tomorrow, I think. Should be as simple as moving the ghostize call but I'm paranoid.

**Comment by Spartan6** [comment]
Yeah, ghost the player. It then let’s the player who got emagged a chance of being the drone.

Have the text say the drone suddenly sparks and shuts down, attempting to reboot.

If it gets a player, some flavour text of it whirring back to life with a deathly red eye.

If nobody goes for it, just gib it.

**Comment by FalseIncarnate** [comment]
This reeks of antag-fishing.

For things like borers, swarmers, aliens, etc it makes sense to offer control to ghosts. These usually are either entirely new mobs or (in the case of aliens) avoiding the issue of people throwing themselves at aliens to become one.

This is kicking out someone who CHOSE to play a normal drone in favor of someone who only may be interested in being an emagged one. Further, the person who CHOSE to play a drone is then subjected to the drone respawn timer again without having actually been killed.

Making this the behavior of handling the antag ban just like with cultists and such is fine. Making this the default is just outright backwards.

**Comment by Tayyyyyyy** [comment]
> This reeks of antag-fishing.

I don't understand how observing and waiting for a ghost role is antag fishing. So if you sit around and wait for ghost roles like holoparasite or the aliens at 13:30 you should be banned for antag fishing?????????????

The player who chose to play a normal drone chose to play it because they like fixing stuff. If they picked normal drone because they're slightly hoping for a chance to get emagged in the back of their minds, then that's bad. And in my playtests, getting forcibly ghosted does not seem to proc the drone timer. You shouldn't be rewarded with massive power for failing to get away from other beings.

Think of this like a dynamically created holoparasite. The drone is arguably more powerful than the holoparasite anyways, making it a HUGE issue that you can hit respawn and basically choose to help an antag out.

> Making this the behavior of handling the antag ban just like with cultists and such is fine. Making this the default is just outright backwards.

There is a difference between cultists and this. Drones are infinitely respawnable and have meta information about the round. They're also extremely powerful and hard to regulate. And if you look at the thread, it's a discussion about how this should apply to slings, too, which I don't think is a bad idea at all.

Also, drone is a ghost role that's not really meant to affect the round at all. Being able to emagged literally directly contradicts this. Emagging drones should be taken out entirely.  This PR tries to remove that conflict of interest instead of taking that drastic step.

**Comment by Fox-McCloud** [comment]
This is pretty awful.

Making it so antag job-banned players get offered up to ghosts, when emagged? Yeah; that's more than acceptable.

This won't really resolve the problem, to be honest; there won't be anything stopping the player from still engaging in the same behavior as before; yeah, they might not get *personally* rewarded for it, but it'll still be helping an antag in some way.

Likewise, it also means those who are following their laws and still get emagged? They're punished, quite sharply for it.

I'd rather see the ability to emag drones get removed entirely than have a jarring, confusing, and punishing system like this.

**Comment by Tayyyyyyy** [comment]
> This won't really resolve the problem, to be honest; there won't be anything stopping the player from still engaging in the same behavior as before; yeah, they might not get personally rewarded for it, but it'll still be helping an antag in some way.

You're right. This can still be abused, but in my opinion, will be abused less often, because personal reward is often what people are going after, rather than wanting an emagged drone to be in the round. Because emagged drones aren't fun for anyone except the drone player.

> Likewise, it also means those who are following their laws and still get emagged? They're punished, quite sharply for it.

There's no timer for being forcibly ghosted from a drone, so you can actually rejoin as a new drone right away. I'm also working on making it so that the ghosted player has an equal chance of joining as a drone, though I'm not sure if you think that's better or worse, so I would love to have an opinion from you on that.

> I'd rather see the ability to emag drones get removed entirely than have a jarring, confusing, and punishing system like this.

I agree 100% with this. I just felt like people would be really really unhappy if emagged drones were entirely removed. This system, while not 100% effective, is slightly better than before, which is all I'm aiming for.

**Comment by HugoLuman** [comment]
If you can respawn as a new drone right away, I don't see a problem with this. However:

> And if you look at the thread, it's a discussion about how this should apply to slings, too, which I don't think is a bad idea at all.

HELL no. Get permanently removed from your character just because the slings caught you? That is literally the worst idea I've heard in months.

**Comment by Tayyyyyyy** [comment]
> HELL no. Get permanently removed from your character just because the slings caught you? That is literally the worst idea I've heard in months.

This is definitely something you should post in the forum thread instead of here!

**Comment by bigfatbananacyclops** [comment]
I support the removal of drones, there's no point in being a engineer with them.

**Comment by Tayyyyyyy** [comment]
> 1.Emag would probably be useless towards drones because there can be sometimes where noone takes the drone spot.

This applies to other ghost role antags, like holoparasite. The emag is useful for other things, though, so it's not like you're wasting TC.

> 2.You're taking a player out of the game.

You can immediately rejoin as a drone, and optionally, the person being ghosted could be a candidate as well, though I'd like @Fox-McCloud or another maintainer to make the call on whether this is better or worse.

> 3.We should just remove drones entirely really, there's no point in being a engineer or janitor with them.

I can see your point here, but we're kind of going down the list of more and more unpopular PRs now 😛

**Comment by deep-fried-faceplant** [comment]
I would like to expand upon my thoughts on this subject before the discussion is closed, as well as offer some counter arguments to the ones that have arisen here, but finals are coming up and I should try to focus on studying rather than contributing to a discussion regarding code changes on a server I no longer play on. Still, I'll keep an eye on this thread and read all responses to it. Tay, thank you for authoring this PR, I had almost forgotten about that thread and was nearly certain that I would not hear from it again.

**Comment by Dinarzad** [comment]
> 3.We should just remove drones entirely really, there's no point in being a engineer or janitor with them.

I wouldn't necessarily oppose this
IF
pAI got made a bit more of an active role in exchange.  The reason drones are so popular isn't strictly for the antag fishing, it's because, despite not being able to participate actively with other characters in a round, you are still actively playing. You are still actively doing janitorial and construction and actively playing the game, the player has to DO things.
If drones were removed, the "Keep ghosts from shitting up deadchat" aspect of why drones exist, wouldn't be taken over sufficiently by anything.  If pAI had more of an active role in what they do, they'd probably serve the same role without as much antag fishing.

But that's moving debate to a hypothetical PR that may not ever exist.
Regardless, as someone that's been playing Drone a LOT the past few months cuz I never feel up to being activei n a round, wouldn't hurt my feelings to see Emagged Drones go away. I hate going into a relaxed zen mode only to find out I now have to butcher half the station.

**Comment by Kyep** [comment]
Instead of ghosting the original drone player, why not just instantly respawn them as a new drone?

From their point of view, they've teleported to the drone fab, and their drone number has changed, but neither of those things matter. You aren't attached to your drone number in the same way you're attached to your crew character. Your crew character is unique. You chose the name, the story, the appearance, etc. Your drone isn't. It is exactly like any other drone. Being put into a new drone body just moves you and changes your ID number. That's it.

This solution would still give drones a disincentive to let themselves be emagged, whilst at the same time, minimizing the amount of actual disruption they suffer. Sure, they're effectively moved to Engineering and their ID number is changed, but given how quickly drones move anyway (all access + ventcrawl), and how nobody actually cares about the ID number, it seems to be a VERY minor inconvenience for them.

**Comment by Tayyyyyyy** [comment]
> Instead of ghosting the original drone player, why not just instantly respawn them as a new drone?

Not at a bad idea, though I have to emphasize that they can immediately respawn and don't have to wait for the timer, since ghosting doesn't count as dying.

The only thing is that some people are in favor of the player ghosted also having a chance to throw their hat in the ring for the emagged drone, which I think could be fair, though it does slightly increase the incentive to get emagged (but imo, by very little). I'm not sure what to do with this and would like maintainer input if possible.

**Comment by Ziiro** [comment]
I actually argue for the idea that **all** antag conversion methods should shunt the player out. It gives incentive to not get caught and not try to be converted. Win win.

With regards to drones specifically: this is a fine solution, so far as you also change it that you can emag a drone you're holding in your hand(last i checked, it doesn't emag them). This would allow you to pick one up, emag, and then hide it in your bag while it gets the new player.

**Comment by Tayyyyyyy** [comment]
Right now, you still have to emag them while they're on the ground, but they'll still get killed/replaced if you're holding it. Is that good enough? I don't really want to change balance unless I have to...

**Comment by Ziiro** [comment]
That works, yeah. Fast hands and keybinds will be fine!

**Comment by HugoLuman** [comment]
> I actually argue for the idea that all antag conversion methods should shunt the player out. It gives incentive to not get caught and not try to be converted. Win win.

Is that really such a huge problem that you have to use the nuclear option?

**Comment by FlattestGuitar** [comment]
* It's basically impossible to catch someone antag fishing. There are a handful of people who spend almost half of their time playing as an antagonist, while the average player should only get around 10-12%, based on some calculations I ran back in the day. The numbers could be outdated, but there was a clear and obvious difference between certain people.
The amount of bans handed out for antag fishing by the Paradise staff team as far as I'm aware isn't even higher than like five, because even with the numbers supporting your claim that someone *is* antag fishing, there isn't a definitive way to prove anything unless the other person outright states it as a fact.

* An emagged drone that knows what they're doing is horribly powerful and ridiculously hard to get rid of. They can listen in on comms, they can hide in pipes making themselves indestructible, they can remotely operate ANY equipment the AI can, and their tiny-ass sprites make them half-decent at getting away from any attacker.

* If you didn't become a drone for the sole purpose of becoming an antagonist, then being teleported back to the drone fabricator makes literally zero difference to you aside from having to get back to where you were nabbed. It's only punishment if you only became a drone to try to get to be an antagonist. No promise - no loss.

* If the only reason you play drone is to be an antag, shame on you.

Just remove emagging drones, will you?

**Comment by taukausanake** [comment]
I'd only support removing emagging drones if emagging them instead made them pop. Maybe you are tearing down a wall or window and the drone keeps repairing it. Swipe, pop, no more trouble

**Comment by Tayyyyyyy** [comment]
There seems to be more support for removing emagging than I thought. That'll be the next PR if this one is closed!

> I'd only support removing emagging drones if emagging them instead made them pop. Maybe you are tearing down a wall or window and the drone keeps repairing it. Swipe, pop, no more trouble

Technically, if the drone were following its laws, all you have to do is to tell it not to interfere and it should go away, but I guess drones are generally pretty bad at following laws. Replacing emag_act with just a call to death and gib is probably the best solution.

**Comment by HugoLuman** [comment]
Another possibility would be to make then just like regular drones, but antag. Cuz seriously, their borg-like access is powerful enough on its own. They really don't need extra tools or that freaking drill, which makes them _capable warriors_.

**Comment by Joseph-Case** [comment]
Remove drones, problem solved

**Comment by tigercat2000** [comment]
@Tayyyyyyy We would rather that this PR is solely targeted at fixing the problem with antag bans on drones- offering up control if they're syndicate jobbanned. In addition, you could also make it so that emagged drones can still be remotely shut down via the drone fabricator (https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/silicon/robot/drone/drone.dm#L248) to help even it out. If you would rather not retarget this PR to do so, please let us know, so that it can be closed.

**Comment by Tayyyyyyy** [comment]
Sure, I can take a stab at that.

**Comment by Tayyyyyyy** [comment]
@tigercat2000 disclaimer: haven't gotten a sql server set up, so I haven't tested that this works. But it's pretty much the same PR as #8215 so hopefully it does

**Comment by Tayyyyyyy** [comment]
Rebased, but @Aurorablade, would it be a good idea to just wait till datum antags is merged and then port this to datum antags?

**Comment by tigercat2000** [comment]
Datum antags isn't really necessary for this.

**Pull request merged**
