### PR TITLE
Borer enhancements

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
bugfix: Borers will now properly detach upon death of a mob they are controlling
tweak: Borers can now see their chemical count while in control of a mob
rscadd: Borers can now silently communicate with their host - this is not available to the host until the borer has either begun to communicate, or has taken control at least once - this is to avoid spoiling that the borer exists
tweak: Borers won't be able to talk out loud inside of a host, by default - they can remove this safeguard with a verb under their borer tab. Borer hivespeak is unaffected.
tweak: Borers infesting and hiding are now silent.
tweak: Made borer's chem lists more nicely formatted
/:cl:

### CODE REVIEW

**Comment by Gummin** [comment]
Well, sense no one else has, I'll go ahead and comment.
Nice. :+1:.

**Comment by DaveTheHeadcrab** [comment]
Not sure the sugar sedative should have an upside.
Otherwise looks good.

**Comment by FalseIncarnate** [comment]
Gonna agree with Dave, the Chem boost while sedated seems strange. Honestly, if you said it reduced the production rate while sedated it would make more sense (something something slowed biological functions), but to increase it makes it more difficult to keep an ass-tier borer in check since they are far more powerful when the sugar metabolizes.

**Comment by Crazylemon64** [comment]
I'll remove the enhanced metabolism when sedated, then

**Comment by fludd12** [comment]
I feel like the enhanced metabolism worked well for it, but if there's too many objections, I guess I'm a minority on that issue.

Everything looks great to me! We've needed this for a long time.

**Comment by Crazylemon64** [comment]
No, the ability to talk with the host silently after assuming direct control is something this patch adds - it doesn't exist on live, right now.

**Comment by KasparoVy** [comment]
Lmao, aww. "rscadd: Borers can now silently communicate with their host - this is not available to the host until the borer has either begun to communicate, or has taken control at least once - this is to avoid spoiling that the borer exists"

Endless laughs were had the last time I got a borer.. He was TOTALLY new, and he tried like 10 times consecutively to talk in hive chat but failed-- talking in LOCAL instead. After a while, he literally said 'fuck it' and we just screwed about while he learned how to borer hahaha. Hilarious.

**Comment by Fox-McCloud** [comment]
Still going to eat sugar the split second I get a wiff of one of these guys in my head.

**Pull request merged**
