### PR TITLE
Tweaks Wizard Academy

### PR DESCRIPTION
**Pull request by Kyep**
Tweaks Wizard Academy to make it more interesting:
1) Moves mimics from bear room to robotics room across the hallway, ensuring that both rooms are dangerous.
2) Added a second weeping angel, near the Bridge.
3) Changed metal stack east of the costume lockers to contain 50 metal.
4) Added 20 bars of silver to the bridge bedroom.
5) Moved two spawn points out of toxins room (why do wizards even have a toxins room?). Placed one in southeast thruster room, and one in the botany room. Makes it less likely that a team of explorers will spawn together. Increases chance they'll wander aimlessly and get killed while trying to group up.
6) Fixed some air leaks.
7) Adds single-use spellbooks of summon item(library) and charge (Bridge office).
8) Adds named Megacarp to asteroid directly west of the airlocks on the west side. Attempting to hide in space around the wizard academy will give you a nasty surprise.
9) Added 5 bars of gold to the weapons testing room (the room with several mimics).
10) Added a hostile creature (the green mouth creature, as wizard starting room has) to the freezer.
11) Added atmos system.

Overall:
A) Makes wizard academy more dangerous, by having more hostile mobs, and more diverse spawn points.
B) Makes wizard academy more rewarding to raid, by having it contain some base minerals (metal, gold, silver - but you have to fight to get them), and a couple of working spellbooks (for non-combat, utility spells).

Screenshots:

🆑 Kyep
tweak: Adjusted Wizard Academy to make it both more lethal, and more rewarding.
/🆑

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Should this have a CL entry?

**Comment by Kyep** [comment]
Yes. Added one.

**Comment by Necaladun** [comment]
more risk more reward :+1:

**Comment by jughu** [comment]
Why does everything need loot REEE ISNT THE REAL treasure THE ADVENTURE

**Comment by DesolateG** [comment]
Any chance of a little bit of bananium?  Not enough for a honk, but maybe smaller items

**Comment by jughu** [comment]
Add the virus wizardtitus to it 👌

**Comment by Kyep** [comment]
I am trying to keep the loot themed for each mission. I may have bananium in the clown planet away mission. Wizards have no reason to keep bananium, though.

**Comment by DesolateG** [comment]
Hmm true. Though maybe tranquilium for research on invisible walls, though I don't know what small items you can make with it

**Comment by DesolateG** [comment]
Wait! Hmm no that request would be an entirely different pr

**Comment by Spacemanspark** [comment]
The clown planet away mission needs to be brought back

**Pull request merged**
