### PR TITLE
radial menu vendor circuits

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
title

## Why It's Good For The Game
it looks nice and you get a better idea on what you're gettin
also input() bad

## Images of changes
Screenshot 2023-02-06 170834
Screenshot 2023-02-06 170900
Screenshot 2023-02-06 170942
Screenshot 2023-02-06 171000
Screenshot 2023-02-06 171020
Screenshot 2023-02-06 171040
Screenshot 2023-02-06 171101
Screenshot 2023-02-06 171120

## Testing

yes

## Changelog
:cl:
tweak: Vendor circuits now use radial menus 
/:cl:

### CODE REVIEW

**Comment by Adrer** [comment]
While I do like the look of this, I'm personally not particularly a fan of having to go through 7 radial menus to find the vendor I am looking for, especially if they have identical sprites.

**Comment by GDNgit** [comment]
> While I do like the look of this, I'm personally not particularly a fan of having to go through 7 radial menus to find the vendor I am looking for, especially if they have identical sprites.

They're two different items, smartfridges are less distinct because they share the same sprite for most of the different smartfridges

**Comment by procdrone** [comment]
Maybe a TGUI with a searchbar would be more fitting here?

**Comment by TrashDoxx** [comment]
> Maybe a TGUI with a searchbar would be more fitting here?

I agree.

**Comment by DoctorDrugs** [comment]
a couple of the design team aren't fans of a radial menu with a huge amount of options like this that require sorting through. A searchable list of proper names (Medicine Smartfridge, Produce Smartfridge, etc) with a search bar would fit this much better than a radial menu we feel.

**Comment by GDNgit** [comment]
I got another idea...

**Pull request closed without merging**
