### PR TITLE
Paint everything

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR allows you to paint objects with slime paint

## Why It's Good For The Game

Painting is funny, why dont we have it?
image

## Testing

Compiled, painted

## Changelog
:cl:
tweak: Slime Paint can be used to paint objects now.
/:cl:

### CODE REVIEW

**Comment by DGamerL** [comment]
How does it look when you paint something like a baton?

**Comment by HMBGERDO** [comment]
image

**Comment by Sirryan2002** [comment]
leaving an objection on this PR. Object coloring like this is ugly and makes the game environment actively look worse, not a fan of making this easier to do (I also really hate color grenades).

**Comment by farie82** [comment]
The teams responsible for voting have voted against this PR being merged:
- Changing colors like this never looks good, and it never will with our setup, colors applied to sprites just ruin them.
- There's not a particularly good reason to add this and contributes to parts of the game looking ugly AF
- this looks terrible on certain sprites, and just ugly on most

I'll be closing the PR due to the issues listed above. Allowing any object to be recoloured will make a ton of things not work with our current recolour system and sprites.

**Pull request closed without merging**
