### PR TITLE
The Utensil of the future!

### PR DESCRIPTION
**Pull request by IK3I**
Prepare yourselves for the next great innovation in food consumption technology!

I present to you, the one, the only, the
# SPORK!
Spork Preview

:cl:
rscadd: Next gen dining is now available at your local autolathe!
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
Much better than #8576

10/10

**Comment by Necaladun** [comment]
I think we need splades and foons, or this is very unbalanced.

But it's a good start, merge asap pls.

**Comment by alexkar598** [comment]
^^^^^^translation

This needs changes to be acceptable
Merge now
Lol memes

**Comment by Ralta** [comment]
Can confirm: Best PR 2018.

Insta-merge.

**Comment by davidchan13** [comment]
This pr has been open for 10 hours and not merged yet. Fire the maintainers for failing to live up to their responsibilities.

**Comment by FreeStylaLT** [comment]
Instantly downvoted for Spork. 😠

**Comment by Vivalas** [comment]
Damn beat me to it :-1:

**Pull request merged**
