### PR TITLE
Adds recipe recording

### PR DESCRIPTION
**Pull request by yorii**
## What Does This PR Do
Adds ability to record your button presses on the chem dispenser for later replaying the same recipe.

## Why It's Good For The Game
Makes chemistry fun.

## Changelog
:cl:
add: Added chem recipe recording
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
Yes

**Comment by yorii** [comment]
I need to figure out how to do tgui again, hence why this is a draft atm

**Comment by Calyxman** [comment]
Ah, figured it wasn't done. you're doing good work out here though!

**Comment by roarbark** [comment]
pr that makes it so that people who roll chemistry dont have to suffer playing chemistry as much? i dont get what problem this solves.

**Comment by CinnamonSnowball** [comment]
As someone who plays chemistry often, I.. don't really think we need this? We don't have many super-complex-yet-commonly-used chems that would beg for automatic recorded recipes, a vast majority of them is easy and quick to make even without this.
As long as this is faster than a human (**instant**, as I've heard), I also don't like how this removes the skill of remembering how to quickly and efficiently mix reagents for chems, and I feel like it might also slow down the learning process for new players, since they might be tempted to just record a recipe instead of actually working to memorize it. 
Plus, frankly, I can see it making chemistry more boring rather than fun, since it removes a considerable part of the job - you just record a given recipe once then just press the "more" button, with all of the interactive steps inbetween removed. I'd also be scared of chemists being **expected** to record their recipes so someone else can step in to quickly make medicine, reducing the value of having an experienced chemist (or a chemist at all).

**Comment by meow20** [comment]
Chemistry should be about being able to make various chems quickly in large quantities, not about making a recipe once from wiki and then spamming it? Medchem already gets boring as hell with the overstocked fridges in medbay so im against it if I understand what it does well.

**Comment by Sirryan2002** [comment]
If I had any preliminary advice. I would avoid using `alert` and native BYOND popups for inputs/confirmation for a TGUI menu, we currently have built in support for using modals. Once you get your TGUI working I'd be happy to help you figure it out.

**Comment by procdrone** [comment]
I agree with others while this seems QoL, I don't think its really needed

**Comment by AffectedArc07** [comment]
Closing due to:
- PR going stale
- PR being entirely untested
- PR being made with the web editor
- PR doesnt even compile

Feel free to remake in the future should you wish to do this properly.

**Pull request closed without merging**
