### PR TITLE
Grey Smokeables

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
rscadd: Greys now use re-positioned smokeables. They no longer smoke out the eyes.
/:cl:

Someone requested it in OOC. An oversight on my part, I forgot that Greys are shorter than Humans and have bigger heads.

### CODE REVIEW

**Comment by ScratKnapp** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
about 2 weeks ago, I was ICly teasing a grey about just this "wow, look at that grey; he's smoking out of his EYES."

The grey just said "yep. it's normal" or some other rather humorous response acknowledging it.

**Comment by NTSAM** [comment]
:alien::+1:

**Comment by KasparoVy** [comment]
@Fox-McCloud Yeah, that's the thing with Greys. They've been slipping under the radar quite a lot lately. I'll sort out the rest of their masks in another PR, then do hats for everyone. To really polish off the Greys, however, they'll need adjusted uniforms/suits due to their SLIGHT height disadvantage-- something that makes their shoulders look demented (sort-of like they're a hunchback) when wearing any uniform.

**Pull request merged**
