### PR TITLE
Reworks minor addictions to be less severe to the user

### PR DESCRIPTION
**Pull request by AzuleUtama**
## What Does This PR Do
Changes the addiction system to have separate effects on players for all stages of the addiction should the items they're addicted to be classed as a "minor addiction". The changes make the messages displayed to the user in chat less severe than normal addictions and also removes the slowdown effect from stage 5 entirely, meaning minor addictions will no longer cause negative effects on gameplay. This would affect the following reagents:

- Coffee
- Iced Coffee
- Soy Latte
- Cafe Latte
- Tea
- Iced Tea
- Nicotine
- Capsaicin Oil
- Fake Cheese
- Weird Cheese

I did consider also adding omnizine as a minor addiction given how you can get addicted from eating a single donk, but that does have pretty strong healing properties and is used much more for gameplay reasons than RP. I feel that should be PR'd separately.

## Why It's Good For The Game
It was discussed on the second community meeting that the addiction changes introduced this year were a huge annoyance for recreational drugs such as coffee and cigarettes, making people actively avoid ever using these items. Both of these are used more for RP or character flavour than as an actual gameplay altering drug. Additionally, since they use the same addiction system as regular chems besides causing slowdown rather than a stun at stage 5 addiction, people get bright red warning messages telling them things like "You would DIE for some coffee right now!", which seems a tad overboard for something like that. This PR makes minor and regular addictions have their own set of hopefully more appropriate messages.

## Changelog
:cl:
tweak: Minor addictions reworked to be less severe and no longer have effects on gameplay.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
I appreciate you

**Comment by TDSSS** [comment]
IMO, we should just give different reagents different addictions entirely, I don't get why this was the same for all of them.

**Comment by Darkmight9** [comment]
Will this innately affect the listed chems? I don't see any other changes other than adding in the minor addiction check and results to reagents.dm

**Comment by AzuleUtama** [comment]
> Will this innately affect the listed chems? I don't see any other changes other than adding in the minor addiction check and results to reagents.dm

All the chems listed either have "minor_addiction" set to true or are subtypes of a chem which has it set (iced coffee for example). I did a quick test with coffee and nicotine and both worked as expected, so it should affect all chems listed.

**Comment by Mitchs98** [comment]
Please, god, yes. Moi can go back to chainsmoking more regularly now. 😓

**Comment by ZN23XZ** [comment]
This will also fix the issue where nicotine addiction is SO POWERFUL it causes my jetpack to suffer from the slowdown effect 😅
I'll no longer have to slap a nicotine patch on my jetpack to relieve it of its symptoms

**Review by Kyep — APPROVED** [review]
While I am okay with this, I would also be okay with nicotine, caffiene, etc just having no addiction whatsoever.

**Comment by Darkmight9** [comment]
Eh it's just messages now, semi annoying but doesn't have any game play affects. Also acts as a bit of a reminder that maybe you should have just a little bit more 😈

**Comment by Varghh** [comment]
I really love this idea, but please we need to delete the sneezing emote from addictions, most of the time people just believe you're sick or have a cold when you do that, and it gets not only annoying but immersion breaking when i'm like, playing detective, i have people in my office while we discuss a case, i have not smoked for 2 minutes and i just start sneezing like crazy. I love this idea and i would absolutely love if sneezing is out of the addiction emotes.

**Comment by AzuleUtama** [comment]
> I really love this idea, but please we need to delete the sneezing emote from addictions, most of the time people just believe you're sick or have a cold when you do that, and it gets not only annoying but immersion breaking when i'm like, playing detective, i have people in my office while we discuss a case, i have not smoked for 2 minutes and i just start sneezing like crazy. I love this idea and i would absolutely love if sneezing is out of the addiction emotes.

This change removes most of the emotes associated with addictions if it's a minor one. The only emote you'll do from now on with stuff like cigarettes and coffee is twitching at stage 5, everything else is just a blue message in the chat.

You'll still sneeze and shiver if you're addicted to something stronger, like meth or space drugs.

**Comment by TDSSS** [comment]
Part of me wants coffee addiction to make you yawn when you haven't had your fix. Cue all the addicts freaking out thinking they've been sleepypenned

**Comment by Varghh** [comment]
> > I really love this idea, but please we need to delete the sneezing emote from addictions, most of the time people just believe you're sick or have a cold when you do that, and it gets not only annoying but immersion breaking when i'm like, playing detective, i have people in my office while we discuss a case, i have not smoked for 2 minutes and i just start sneezing like crazy. I love this idea and i would absolutely love if sneezing is out of the addiction emotes.
> 
> This change removes most of the emotes associated with addictions if it's a minor one. The only emote you'll do from now on with stuff like cigarettes and coffee is twitching at stage 5, everything else is just a blue message in the chat.
> 
> You'll still sneeze and shiver if you're addicted to something stronger, like meth or space drugs.

Excellent

**Review by farie82 — APPROVED** [review]

**Pull request merged**
