### PR TITLE
Magic Eight Ball

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds in a new toy: Magic Eight Ball!
- Discern your fate with the wondrous Magic Eight Ball!
- Obtainable from Claw Game prize orbs

Adds in the mighty MAGIC CONCH SHELL.
- Submit to the will of the all-knowing Magic Conch. Let it guide your every action with its infinite wisdom.
- Admin-spawn only

image

:cl:
rscadd: Adds in the Magic Eight Ball toy, found in Claw Game prize orbs.
rscadd: Adds in the Magic Conch Shell, an admin-only shell of power.
/:cl:

### CODE REVIEW

**Comment by HereticChurch** [comment]
Fuckin' magic conch. :+1: :x: :100:

**Comment by NTSAM** [comment]
aLL HAIL THE MAGIC CONCH

**Comment by Plotron** [comment]
add pliz

**Comment by Glorken** [comment]
:+1:

**Comment by Gummin** [comment]
PRAISE THE MAGIC CONCH! :+1:

**Pull request merged**
