### PR TITLE
Buffs the changeling armblade

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
Increases the changeling armblade's base damage to 25, gives it 20 AP, and knocks down for 3 seconds on a target (2 second stun for cyborgs).
This is a very slight buff against armored targets, on average dealing 15 damage rather than 11 from the old armblade against riot armor.
The armblade has been changed to a more defense focused option rather than an offensive option, with a short knockdown allowing you to escape more easily, and perform better in 1 on 1 fights.
This is not mirrored to the dark blessing (do not the chaplain)

## Why It's Good For The Game
Cling is sad currently
It told me it cuts through people like hot butter, but it really just feels like beating someone with a rock
Changeling should also be able to actually capitalize on having their target near them
This also absolutely fucks borgs, which is totally deserved as they have a valid license against them

## Testing
Apply armblade (very hard)
## Changelog
:cl:
tweak: Armblade now knocks down for 3 seconds and has some slight AP
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
Needs a bit of a redesign because there are no glove armors

**Comment by Peakwastaken** [comment]
increased armor pen to have a better chance against riot armor is good, but I'm confused about the knockdown part - does this mean every single hit against a standing opponent will knock them down/stun borgs ?

**Comment by GDNgit** [comment]
> increased armor pen to have a better chance against riot armor is good, but I'm confused about the knockdown part - does this mean every single hit against a standing opponent will knock them down/stun borgs ? If so, it sounds kind of problematic

Yes, it functions similarly to the contractor baton. Mind you, the reason why items like that are very useful are due to the powerful other options that people with those types of items have, compared to the extremely limited tools changeling has. 

> How about giving it a pushback like disarms (because the strength of the swipe is so great !) so that it's offensive utility is more strategic (tables/walls etc) while also having the ability to be more defensive with the pushback

This would make the item frustrating to use frankly. Banking so much on hoping you hit someone in the right way isn't great for an item which should be pretty simple.

> Or, maybe on a slightly bigger scope, give it some similar treatments to tentacles with effects based off of intent - help intent to caress people with the blade a la xeno for extra creepiness, disarm to shove on top of regular damage, grab to swipe at the legs for a slowdown or guaranteed feet damage, and harm for some slightly increased damage, or something to that effect?

This would be much better suited to a new item, and maybe some sort of martial art than building off of what the current armblade is

**Comment by Peakwastaken** [comment]
> Yes, it functions similarly to the contractor baton. Mind you, the reason why items like that are very useful are due to the powerful other options that people with those types of items have, compared to the extremely limited tools changeling has.
> 

Contractors are very limited in the tools they have early, and later on don't really have much more ressources (or they're limited in their uses) compared to clings. 

Clings have built in antistuns, heal, detox, speed, even a tentacle to pair the armblade with, shield, armor, great stealth capabilities, and even full rejuvs protecting them from IBs/broken bones, which don't suffer from attrition on the long run. I don't think they have limited tools by a longshot, their only limit is how much they can use all of these tools in a short amount of time, and the armblade is often used as a toggle and forget thing that then don't require any chems to use. And it can't be dropped, contrary to the contractor baton.

Fighting constant unconditional knockdowns sounds very unfun, and a single hit against a lone crew/officer renders any chance of escaping basically null, no matter how weary of the danger or noticeable the cling might've been. Yes, they're hunter, and should be able to hunt targets efficiently, but I think it should be by using their other abilities in combination of their murder tool to do so, rather than the latter being able to do both without any further thought/resources required.

> This would make the item frustrating to use frankly. Banking so much on hoping you hit someone in the right way isn't great for an item which should be pretty simple.
> 

That's what disarms are, and they can be used very effectively against an armed opponent, so much so that people think shoving while horizontal gives too much of a chance to your run-of-the-mill greytider vs security. 

The intent behind my proposal is that you can skillfully set up situations where you can use knockdowns (or even tables, making a deadly combo) to your advantage, without being oppressive because you can do it with a single click anywhere anytime, repeatedly. 

Furthermore, a one tile knockdown can still be a pretty good get-off-me tool without the knockdown, and in crowded fights/maintenance areas it really isn't that hard to get it anyways.

**Comment by GDNgit** [comment]
> Contractors are very limited in the tools they have early, and later on don't really have much more ressources (or they're limited in their uses) compared to clings.
>
> Clings have built in antistuns, heal, detox, speed, even a tentacle to pair the armblade with, shield, armor, great stealth capabilities, and even full rejuvs protecting them from IBs/broken bones, which don't suffer from attrition on the long run. I don't think they have limited tools by a longshot, their only limit is how much they can use all of these tools in a short amount of time, and the armblade is often used as a toggle and forget thing that then don't require any chems to use. And it can't be dropped, contrary to the contractor baton.

Correct, these are also all tied to the same resource system. If you just have enough people attacking a changeling they are pretty much dead with zero counterplay. This sucks for obvious reasons, but without outright reworking their charge system this isn't going to change.
These traits also don't straight up make you KOS no strings attached. Which is a big difference.
On average, if you use three of your abilities you're out of gas and a sitting duck, so even though contractor/other antags may technically have more limited uses, those uses can actually be used more effectively when it's needed.

> Fighting constant unconditional knockdowns sounds very unfun, and a single hit against a lone crew/officer renders any chance of escaping basically null, no matter how weary of the danger or noticeable the cling might've been. Yes, they're hunter, and should be able to hunt targets efficiently, but I think it should be by using their other abilities in combination of their murder tool to do so, rather than the latter being able to do both without any further thought/resources required.

If you're fighting someone with just the armblade you are going to lose more than likely. You can be out ranged with a disabler, stam crited with a baton, and a whole bunch of other things. You are not defenseless fighting a changeling with an armblade.

> That's what disarms are, and they can be used very effectively against an armed opponent, so much so that people think shoving while horizontal gives too much of a chance to your run-of-the-mill greytider vs security.

Yeah but this should not be applied to a weapon for the following reasons:
1. Not everyone gets this weapon, not everyone is going to instantly know the effects of this weapon. Bad first impressions matter and this will give them a truly awful one.
2. Most people who have the weapon will be forced to stay in and straight up murderbone fishing for the right angle to knock someone into an object.
3. If they do manage to actually hit someone into an object there is no reason to just not kill them at this point, so we have more murderbone issues.

> The intent behind my proposal is that you can skillfully set up situations where you can use knockdowns (or even tables, making a deadly combo) to your advantage, without being oppressive because you can do it with a single click anywhere anytime, repeatedly.

This won't be oppressive against carbons, if anything it will just remove knockdown RNG that changelings currently *need* to fish for in order to do well, and that creates more unfun and murderbone-y situations.
It's going to be hard on silicons. It should be hard on silicons. Silicons should not be a combat role anymore.

> Furthermore, a one tile pushback can still be a pretty good get-off-me tool without the knockdown, and in crowded fights/maintenance areas it really isn't that hard to get it anyways.

Then just use the disarm in that case? You always have that open.

> And I don't think because an ability is simple in concept doesn't mean that it can't have depth in its use

Forced depth != Emergent Depth. Depth in use is only fun if the interactions between different systems creates more opportunities. Giving one thing 5 different mechanics in one isn't going to do that.

Also, reliability is important and should not be understated. There should be at least one tool in your kit that you know what it's gonna do, no strings attached. The point of this PR is to remove that knockdown fishing style of gameplay from changeling, so they aren't mechanically encouraged to murderbone because they just can't get out otherwise. I have actually considered dropping the DPS of the armblade to help with this, as the main concern with changeling right now IS that it's a murderbone antagonist.
By removing as much possible RNG from their kit, we can actually start to effectively balance them.

**Comment by Peakwastaken** [comment]
>If you just have enough people attacking a changeling they are pretty much dead with zero counterplay.

Then again, I think antags do need some weaknesses, and any without any teleportation abilities will and should be dead in the water with enough people attacking. They have a lot of mobility at their disposal, and can run around security quite easily, especially with the chemical regen buff.

>Then just use the disarm in that case? You always have that open.

Changelings are actually quite prone to not have it open, especially when using the armblade - if they use an offhand shield or are grabbing people for example - since chemical management is important you can't really afford to toggle it on and off, maybe that'd be something that could be improved on to help alleviate the forced murderbone situations ! Because I don't think making their murder tool have that much more guaranteed utility is gonna alleviate that, it might even make it worse, that's my fear with your proposal.

>Forced depth != Emergent Depth. Depth in use is only fun if the interactions between different systems creates more opportunities. Giving one thing 5 different mechanics in one isn't going to do that.

I really fail to understand how a mechanic which interacts with the rest of the sandbox would be less emergent than one that doesn't.

I think the way we both perceive changelings are very different, and that's fine ! It's good to have people approaching such gameplay questions in different manner, and I appreciate that you're trying to turn the armblade into less of a straight up murderboney tool while giving it a slight touch up, but I don't think this is the way !

Thank you for engaging with me nonetheless and giving me more depth in your train of thoughts !

**Comment by GDNgit** [comment]
Converting this to draft because after thinking about it for a long time I think peak's idea of having it also function as a disarm is a better idea, so I'm gonna be revising this after finals are done for me

**Comment by hal9000PR** [comment]
PR has 4 objections after a month. I know this is in draft, but if you want to completely change the affect of a PR please make a new PR.

**Comment by SpringSkipper** [comment]
Armblade automatically outs you as a non-crew and makes you fully KoS. It needs to be stronger.

In my opinion, the three buffs it needs is damage, a faster door prying speed, and a lower chemical cost.

However an instant knockdown is pretty strong and a permastun on borgs is just obnoxious. Cling already gets spammable EMP for 1 point and the disorienting shriek to deal with silicons. They might not be combat roles anymore but they are still players who deserve to have fun, and that sounds miserable.

**Pull request closed without merging**
