### PR TITLE
New Wizard item - Bottle of Ooze!

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
Adds my entirely new item for Wizards - Bottle of Ooze! Costs 1 point in their spellbook.

When Bottle of Ooze is used on the station, it awakens all-consuming Morph, ready to eat everyone and everything on the station! Be careful though, as Morph diet also includes Wizards..

Functionality is very similiar to Bottle of Blood/Tickles and slaughter/laughter demons.
But I believe Morph is far more fun to play as and against than demons, and the chaotic nature of Morph exactly fits into the Wizards rounds. In images section, I have added image introduction and objectives they get when they spawn from Bottle of Ooze, and also image of the custom icon for the bottle.

Some important information about Morphs:
1) Like demons, they do NOT permakill their victims. When Morph dies, he can be butchered (with kitchen knife or cleaver, for example) to get back all the victims and items Morph ate.

2) Instead of magically appearing and doing boring hit-and-run in split second like demons, Morphs use vent crawling ability, which can be countered considerably by welding vents, pumping hot gas into the pipes, or even disassembling some parts of the pipe network. Morphs also have a timer, before they enter vents, so they need to think carefully before their strike, as escape might prove hard.

3) Morphs spawn in secluded parts of the station, to have time to get into vents and/or disguise themselves. I would also add that aliens use the very same system.

4) Unlike demons, Morph can do much more than mindless killing - If crew is not careful, they might find out that Morph ate entire RnD while they were distracted and is currently disguised as a painting on wall in Captains's office, creating fun for all sides.

I have also updated Morph introduction, so it is properly broken into paragraphs now for better readability, along with some improved phrasing.

Tested locally without any issue.

**Images of sprite/map changes (IF APPLICABLE):**
Image of the Morph introduction and their objectives:
IntroMorphFinal

Image of the new custom icon for Bottle of Ooze (its not showing a glow animation, which is similiar to which bottle of blood/tickles has):
VialOoze

**Changelog:**
:cl: Arkatos
add: Added new Wizard item - Bottle of Ooze! This powerful item awakens all-consuming Morph, ready to eat everyone and everything on the station! Be careful though, as Morph diet also includes Wizards.. Costs 1 point in the spellbook.
imageadd: Added custom icon for Bottle of Ooze
tweak: Morph introduction is now properly formatted
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Man I'll take morphs any shift over those goddamn demons. Great idea

**Comment by AzuleUtama** [comment]
Interesting proposal which I can see wizards making use of.

**Comment by TDSSS** [comment]
Will wizards actually go for this over a demon? I'd expect a demon to murder far more crew and generally be a lot more dangerous than a morph. though I admit I haven't gotten to play one yet.

**Comment by SkeletalElite** [comment]
I think it would need to summon more than one to actually be used, there's not really much reason to use this over a bottle tickles.

**Comment by Citinited** [comment]
Morphs kind of get countered by suit sensors too so this doesn't seem very powerful... still it's only 1 point so I guess some wizards might use it.

**Comment by SkeletalElite** [comment]
> Morphs get countered by suit sensors which every crew member has so this doesn't seem very powerful... still it's only 1 point so I guess some wizards might use it.

Laughter demon also only costs 1 point

**Pull request merged**
