### PR TITLE
fix me() verb

### PR DESCRIPTION
**Pull request by tigercat2000**
whoops

### CODE REVIEW

**Comment by tigercat2000** [comment]
to be specific I didn't change this before, I removed the 'me' emote from humans
but that was an insane way to use a verb so

**Comment by Spacemanspark** [comment]
Thank you.

**Comment by KasparoVy** [comment]
Thanks!

**Comment by Spacemanspark** [comment]
But I can narrate things now!
"Walter had a fetish for paperwork." Is probably a highlight of my week.

**Pull request merged**
