### PR TITLE
Adds in a R&D lab to the research outpost and adds a few pets!

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
Since xenoarch is completely useless (too lazy to remove it ALL) now I
decided to change the anomaly lab to a R&D lab. I also added a kitten and fox to the Research Outpost and a Pug and Corgi Puppy to the Mining Outpost. :)

ss 2015-08-29 at 02 43 30

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Whoops, need to move that chem heater somewhere else.

**Comment by KasparoVy** [comment]
Chem lab to research outpost just makes it even more of a traitor heaven

Now it's even less of an effort to find a safe spot to make your deathchems and such

**Comment by Ultimate-Chimera** [comment]
I can remove the lab if you want. :)

**Comment by Ultimate-Chimera** [comment]
Reverting the chem lab back to what it used to be.

**Comment by Fox-McCloud** [comment]
Not sure if the R&D equipment can store any data as it requires a server.

Kinda tend to agree with @KasparoVy this just makes it traitor heaven even more than it already is.

**Comment by Ultimate-Chimera** [comment]
Hey fox, I think it does work. I went in-game and there was a sync option.

**Comment by Ultimate-Chimera** [comment]
If not, I could add a server to the outpost too.

**Comment by Ultimate-Chimera** [comment]
Not sure why it did a commit twice, but I think it didn't affect anything.

**Comment by Ultimate-Chimera** [comment]
Yuppers, it does sync with the station server! :)

**Comment by Ultimate-Chimera** [comment]
Ready to merge?

**Comment by Regen1** [comment]
I disagree with this PR, it is not needed, and the extra pets doesn't really add anything.
If we start adding pugs and corgies everywhere they loose their charm.

**Comment by Ultimate-Chimera** [comment]
What is needed then? I really wanna spice up the Asteroid a bit.

**Comment by Alex6511** [comment]
More antag friendly areas on the station proper would be nice if you want to map something, I don't think we need any xenoarch station changes right now, mainly because the job doesn't work at the moment.

**Comment by Ultimate-Chimera** [comment]
The asteroid could use something though.

**Comment by Fox-McCloud** [comment]
I really don't personally think this is a good idea---at the end of the day.

Research Outpost is already almost completely unmonitored, most of the time---and the perfect spot to do blatantly horrendous antag actions with little to no ramifications (is it any surprised cultists always go here to farm their words when they're scientists or the RD?); giving them their very own R&D on top of that is a step too far, IMO.

**Comment by Ultimate-Chimera** [comment]
Well, I want to add something to the asteroid, I can revert all the changes to the research outpost, just give me ideas what the asteroid really needs, Fox.

**Comment by Ultimate-Chimera** [comment]
Closing for now till I get ideas on what the asteroid really needs.

**Pull request closed without merging**
