### PR TITLE
deletes pAI pony sprite

### PR DESCRIPTION
**Pull request by hal9000PR**
## What Does This PR Do

Deletes the unused pony pAI sprite

## Why It's Good For The Game
Ponies were purged, I assume this was overlooked. It serves no purpose, it just exists. I highly doubt anyone will want to use these sprites in the future.

## Images of changes
image

## Changelog
:cl:
del: removes unused pony pAI sprite
/:cl:

### CODE REVIEW

**Comment by PidgeyThePirate** [comment]
Huh. I've never seen it, what does it even look like?

**Comment by datlo** [comment]
brb logging on my 50 alternate accounts to downvote this

**Review by dearmochi — APPROVED** [review]

**Comment by SabreML** [comment]
> del: removes unused pony pAI sprite

`imagedel:` might be more approproate for this.

**Review by Kyep — APPROVED** [review]

**Comment by MRgaty** [comment]
Not muh ponies

**Comment by Kiyahitayika** [comment]
@hal9000PR I'm sorry, but what are you replacing this with? Are you seriously considering removing this sprite without even bothering to think about considering possibly maybe ostensibly mulling about potentially trying to be working on a replacement sprite? I cannot believe this! This is completely destroying my faith in this codebase and ruining my immersion into the SS13 universe. Are you saying that ponies don't _exist_ in SS13? What about horses? What about pegasi? Unicorns?! Terrible, I say, terrible! What are the repercussions and what's _next_? Removing the Atmos pipe freezer sprite? Honestly, I can't even. /s

**Review by AffectedArc07 — APPROVED** [review]

**Comment by AffectedArc07** [comment]
Get out my codebase

**Pull request merged**
