### PR TITLE
Thrown Object Spinning

### PR DESCRIPTION
**Pull request by Fox-McCloud**
thrown
thrown2
https://www.youtube.com/watch?v=PGNiXGX2nLU&feature=player_detailpage#t=61

Sometimes simple things are the best.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Your pictures ain't working.
If you be using photobucket again...

**Comment by Spacemanspark** [comment]
But, uh, I know this from Goon so :+1: .

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Idea definitely originated from there, but it's utilizing a proc that TG designed for ammo casing ejections---of all things.

**Comment by Spacemanspark** [comment]
Aye, gotcha.
And the pictures work. Ahahaha.

**Comment by RemieRichards** [comment]
@Fox-McCloud that's a bit unfair Fox, it was made for that yes but it's nice and generic, deliberately so we can do funny stuff like this :P

**Comment by Fox-McCloud** [comment]
@RemieRichards 

Fair enough!

**Comment by fj45** [comment]
AHAHAHHAHAHAHAHA YES BEST FEATURE 2015!!!!


Love hurling canisters into the void with this.

**Comment by adrkiller59** [comment]
Ohhh yesss, I always wanted this little thing on Para since I saw it on some youtube video.
Also I find your test subject choice amusing.

**Comment by SamCroswell** [comment]
If you wouldn't mind a var to determine if an item spins when thrown might not be a bad idea so things like spears don't spin wildly when thrown.

**Comment by ZomgPonies** [comment]
What dave said. Needs a var, spears spinning would look shitte. Can be merged once that little bit's added.

**Comment by Fox-McCloud** [comment]
items that have "no_spin set to 1 will NOT spin.

Only items that currently have this, ATM, is the spear.

**Pull request merged**
