### PR TITLE
Death squid hitbox

### PR DESCRIPTION
**Pull request by SkullyRoberts**
I added a sprite offset to the death squid so that the hitbox is actually in the middle of the sprite

### CODE REVIEW

**Comment by Birdtalon** [comment]
You really need to sort out your master branch.

**Comment by Kyep** [comment]
Per https://github.com/ParadiseSS13/Paradise/wiki
_PRs should not have any merge commits except in the case of fixing merge conflicts for an existing PR. Use git rebase or git reset to update your branches, not git pull._
Your first 7 commits in this branch are merge commits, which will probably result in this PR being closed.

Here is my suggestion for how to fix this issue:
1) Close this PR. It is based on a bad copy of your master branch, and its easier to recreate it properly than it will be to fix this branch.
2) Save the code changes you made to deathsquid.dm into notepad.
3) Delete this branch.
4) Switch branch to your master branch.
5) In the Git client, click the cog/settings icon, and open GitShell.  You should have a prompt that includes the word 'master', indicating that you are on your master branch.
6) In Gitshell, enter the following: "_git reset --hard 7d60fcdfd1a2fb9384ff53ec6c0cd59a13d73a70_". This will forcibly reset your master branch to the last proper Paradise commit it had, before you started doing bad merges that corrupted your master. That long SHA hash I provided is based on looking at the last good commit from https://github.com/SkullyRoberts/Paradise/commits/master
7) Once you have done the git reset, enter in gitshell: "_git push -f_". This dangerous command (which you should not normally use!) will rewrite the history of your branch, wiping your incorrect commit to master from the history books. Any branch you create from your own master after this point will no longer have the rogue commits in it and no longer create these sorts of problems for you when you create PRs.

In future, here is the *correct* way to update your master (and branches)
1) Open Gitshell
2) Enter: git remote -v
3) You should have upstream remotes named either 'ParadiseSS13', or perhaps 'upstream'. If not, add them. Henceforth I will assume your upstream is named 'ParadiseSS13'.
4) _git fetch ParadiseSS13_
5) _git merge ParadiseSS13_
6) _git push_
The above sequence of commands will cleanly update your master to match the latest Paradise master, without creating bad merge commits or other problems.
You can also use them on branches you create to update them, but in the case of merge conflicts you will need to manually fix the conflicts between steps 5 and 6.

**Comment by tigercat2000** [comment]
There's an easier way to fix the commits, gimme a minute to figure it out, I'll post another one

**Comment by tigercat2000** [comment]
So, easy way to do what Tzo said without having to reopen this PR-
1. Open git shell
2. `git fetch upstream` or `git fetch ParadiseSS13` - Updates your remotes 
3. `git merge upstream/master` or `git merge ParadiseSS13/master` - Merges the latest changes to prepare for a rewind
4. `git reset --soft upstream/master` - Rewinds to upstream/master -- preserving all of your work in the working index
5. `git commit` - Creates your new commit (since the old ones got deleted and your changes are in your index)
6. `git push origin DeathSquadHitbox -f` - Updates your repo with the changes. The -f flag makes it so that it ignores update safety since you changed the git history with the above commands.

To prevent this from happening in the future-
1. Open git shell
2. `git checkout master` to switch to your master branch
3. `git fetch upstream` or `git fetch ParadiseSS13`
4. `git reset --hard upstream/master` or `git reset --hard ParadiseSS13/master`
5. `git push origin master -f`
6. Do this every time before you make a new branch.

**Comment by alexkar598** [comment]
''Git rebase -i'' then replacing all the ''pick''s(except the first one) to ''squash'' works too

**Comment by alexkar598** [comment]
``Git rebase -i`` then replacing all the ``pick``s(except the first one) to ``squash`` works too

**Comment by alexkar598** [comment]
Also when wanting to get the new code into a clean branch(no commits made by you yet) you can do:
1)``git checkout branch_to_update``
2)``git fetch upstream``
3)``git merge upstream/master --ff-only``
4)``git push origin``

**Comment by SkullyRoberts** [comment]
Okay. Sorry. I tried to rebase this before I did the PR, but it didn't seem to work.

**Comment by tigercat2000** [comment]
@SkullyRoberts So, you've accidentally picked up a few extra commits - something got merged between the time you did `fetch` and `reset --soft`. At this point, you'll probably just want to `reset --hard upstream/master` and redo your work by hand, then `push -f` again.

**Comment by Fox-McCloud** [comment]
Closing in favor of the newer version.

**Pull request closed without merging**
