### PR TITLE
Updates Summon Guns

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates summon guns+magic to include a lot of new guns we've ported

Also helps further prevent casting on the CentComm z-level during Ragin' Mages

I was half tempted to implement TG's version of summon guns (where it gives 25% of the crew the objective to survive at all costs+steal 5 guns), but I kinda doubt people want that.

Also fixes it so that the name checks for ragin' mages actually works (it was capitalized, when it shouldn't be).

:cl: Fox McCloud
rscadd: Updates Summon Guns and Magic to include many of the new guns
tweak: Summon Guns/Magic can no longer be used during Ragin' Mages
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Remember when we had it so people would get the survive at all costs objective here?
That was horrible.

**Comment by Earthdivine** [comment]
I would ask to have this, and Summon Magic, striken from Ragin, to be honest.

These spells are meant to be challenge mode for the Wizard, and casting this on Raging Mages makes it incredibly hard for incoming wizards, as the crew has a massive arsenal to use on them. The last time this was given out on Ragin, the wizards all got killed extremely quickly. Atleast when used by the solo wizard he knows whats happening, its a rude awakening for other wizards to teleport in and get Wand of Death'd or all of Security using Pulse Rifles + Healing Wands.

As for keeping the Den magic proof, I understand why but we have so little people with wizard experiance, they use it to get a feel for the den. The Spawn rate is wide enough its a not much of a problem of wizards spawning on one another now, and we could always antag ban  + Rez wizards who were killed in the den.

**Comment by HereticChurch** [comment]
Earthdivine's pretty much said how I feel about it.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

There's already checks in place to prevent wizards from casting during ragin' mages, in the wiz den--this just solidifies that more so there's not a way around that.

**Comment by Earthdivine** [comment]
Ah alright. Still would like the Summon X spells to be regulated to regular wizard though.

**Comment by Crazylemon64** [comment]
Lines 357 and 372, in spellbook.dm - you can do a gamemode check here

**Pull request merged**
