### PR TITLE
Held mice sprite fix

### PR DESCRIPTION
**Pull request by taukausanake**
FoS made notice that dead mice don't have a sprite when held. An oversight on my part but I fixed it. Shouldn't cause anymore problems.

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
The file you committed was objects.dmi, and I don't see any inhands in there.

**Comment by taukausanake** [comment]
That's because the holder object uses the icons/obj/objects.dmi file by default, but mice are using the icons/mob/animal.dmi file as a workaround to their different sprites. The edited objects.dmi file was to remove the holder mouse sprites in there in favor of the sprites already existing in animal.dmi

**Comment by Fox-McCloud** [comment]
shouldn't this have in-hand icons, like @DaveTheHeadcrab said?

**Comment by taukausanake** [comment]
The issue was when you pick up a mouse that was dead it didn't have a sprite in your hand. You ended up with an invisible object in your hand. FoS does have sprites for mice in inventory slots and hands but that's not what I wanted to do here

**Comment by Fox-McCloud** [comment]
@taukausanake 

You should get them from her or use the ones Bay has.

**Comment by Fox-McCloud** [comment]
What are the changes to objects.dmi for?

**Pull request merged**
