### PR TITLE
Metastation: Maintenance Rework [Part 1]

### PR DESCRIPTION
**Pull request by Venuska1117**
I suggest to TM it first, just in case something broke.

## What Does This PR Do
Expand small suffocating death tunnels to be more expanded, with include changing shapes of nearby rooms/departaments

Fixes: #22664

If you are interested, join this discord "forum" and join discussion: https://discord.com/channels/145533722026967040/1151146052796285069

## Why It's Good For The Game
Less traffic inside maintenance, more walking area.

## Images of changes
_Download for high resolution_
This image will be updated every time i push changes:

_dont worry about public botany, for now it got moved to arrivals in place of toilets_
image
_huh the toilets? what about them? don't worry about then now, they will be added later._

## Testing
Not compiled yet.

## Changelog
:cl: Venuska1117
tweak: Rework and Expand Metastation Fore and Fore-Starboard Maintenances.
/:cl:

### CODE REVIEW

**Review by Henri215 — CHANGES_REQUESTED** [review]
1. Any idea why this area is like this?

image

2. This zippo is a fluff item, i dont think we are allowed to use it.

image

**Review by 1080pCat — COMMENTED** [review]
<details>
<summary>Just a general review of personal things, i'll make it clear if it's a propper issue</summary>
<br>

Could probably do with windows facing space here, like the cells on box

image

Looks like a welder bomb went off in here, could probably do with less damage since its a maintained station

image

bit of an issue here, unsure if you intended to touch this or not, but these are space facing ungrilled windows

image

Any chance you can straighten this back out? It doesn't look very good.

image

This window here is a electrochromic despite the other ones around it not being as such (and isn't grilled)

image

**Review by Bjamcham — CHANGES_REQUESTED** [review]
<details>
<summary>Some issues I noticed</summary>
<br>
1. An extra Keycard authentication device placed on the wall.
image

2. No attached wire to the labor shuttle window
image

3. Wire to the detective office is not connected
image

4. This passthrough between the magistrate and IAA offices needs a light.
image

5. Lights on top of a fire alarm and the APC in Chang's.
image

6. Light on top of an APC and a camera on top of an air alarm.
image

7. Lots of wall devices stacked on both the north and south wall. I would add a wall or two to the space facing side for some of these devices.
image

8. This airlock does not have an attached canister.
image

9. This injector is in an unpowered area and will not work. It either needs to be in a station area or replaced with a passive vent.
image

10. There is an normal wall in between reinforced walls on the shooting range. If the intent is to add a weakpoint, I think it would be better done as an actual maints door. 
image

11. This pipe leads nowhere, not sure if that's intentional or not.
image

12. The arcade room does not have a camera.
image

13. Camera coverage does not fully show the sec briefing room.
image

14. Incomplete coverage here as well.
image

15. I think the stacked wall devices in the firing range could be spread out some.
image
</details>

<details>
<summary>Personal Nitpicks</summary>
<br>
1. This area feels really empty and the HOS office could use some windows instead of walls here.
image

2.  The HOS office tables seem empty(books, folders, mug) and could do with having a set of lockdown control buttons on the wall. Personally I would put the security management console in the HOS office instead of the break/briefing room, but meta does already have this placement.

3.  I would either give the detective office this space(it could really use it) or add in some vendors or a table.
image

4. I know this was pre-existing, but I would make this front airlock for the IAA office glass.
image

5. I would face this toilet east like the rest of meta does because the north sprite is ugly as sin, but this is really just preference.
image

6. I would give the mime and clown offices windows. There's also no camera in either office but I assume that's intentional.
image

7. I would make this corner a reinforced wall for consistency as the south end of the holodeck has a reinforced wall on the corner.
image

8. I think maints above the fitness room and between engineering could use a few more lights. As it stands it is completely pitch black. 
image


</details>

I hope this is of some use, and if I've commented on fixed, pre-existing issues, or non-issues, I do apologize.

**Review by Bjamcham — CHANGES_REQUESTED** [review]
<details>
<summary>A few more minor things</summary>
<br>
1. Light left over from moving the armory.
image

2. The injector to the right of solars still needs to be in a powered area.
image

3. You've replaced three plasma windows with walls here, if it was intended then there's no issue with it.
image

4. This section could use maybe one or two lights spaced, although this is more opinion than issue.
image

5. The IAA office airlock needs a polarized airlock helper.
image

6. The garden is missing the apc here.
image


</details>

Besides those, I don't see any other issues left.

**Review by Bjamcham — CHANGES_REQUESTED** [review]
Hopefully the last of it

1. Armory section is missing scrubber and distro pipe connections
image

**Comment by Venuska1117** [comment]
> Hopefully the last of it
> 
> 1. Armory section is missing scrubber and distro pipe connections
>    image

god damn, this smooth bain moment i sometimes get.

**Review by Git-GoR — CHANGES_REQUESTED** [review]
- These two airlocks have the old "Fitness Room Shower" name, and an `id_tag` that links them to the button (yellow circle) to lock them.  Please remove the names and tag, and also the button. On top of that, the top maintenance airlock is the base color, not maintenance.
imagen

- Mime's Office and Clown's Office airlocks have both an autonamer helper, and varedited name. Won't break anything, but it's cleaner to only use the helper.

- At the Detective's office, in the Maintenance door there's an atmos universal connector that connects to nothing.
imagen

- Single non-reinforced wall north of Det's office. There's also two wall items in the wall, you may want to move the console one tile to the right.
imagen

**Comment by Venuska1117** [comment]
> * These two airlocks have the old "Fitness Room Shower" name, and an `id_tag` that links them to the button (yellow circle) to lock them.  Please remove the names and tag, and also the button. On top of that, the top maintenance airlock is the base color, not maintenance.
>   imagen
> * Mime's Office and Clown's Office airlocks have both an autonamer helper, and varedited name. Won't break anything, but it's cleaner to only use the helper.
> * At the Detective's office, in the Maintenance door there's an atmos universal connector that connects to nothing.
>   imagen
> * Single non-reinforced wall north of Det's office. There's also two wall items in the wall, you may want to move the console one tile to the right.
>   imagen

ah i remember what was that pipe adapter for now, when i made it first i wanted for security to have separate air system, but to give more maintenance space i just connected it to one, but later forgot it and tryied to remove because someone said "there is random pipe leading to nowhere" and i just removed it, woops, but thanks for remainder. (that mean if vent-antag spawn at sec it cannot escape)

**Review by S34NW — APPROVED** [review]

**Pull request merged**
