### PR TITLE
Personal Crafting Nano-UI-ification

### PR DESCRIPTION
**Pull request by davipatury**
:cl: davipatury
rscadd: Personal crafting now uses Nano-UI.
/:cl:

Port's /tg/ display and tooltip styles.

<details> 
  <summary>Crafting menu</summary>
  non_compact
</details>

<details> 
  <summary>Crafting menu (compact)</summary>
  compact
</details>

### CODE REVIEW

**Comment by tigercat2000** [comment]
Please ensure that the CSS files you have included are either not licensed under MIT or get permission from the developer of them; NanoUI is by the most part licensed under AGPLv3, whereas TGUI is primarily licensed under the MIT license.

**Comment by Markolie** [comment]
Very nice!

**Comment by davipatury** [comment]
@tigercat2000 Isn't MIT compatible with AGPL?

**Comment by Fox-McCloud** [comment]
Let us know when this is ready!

**Comment by davipatury** [comment]
It's ready.

**Comment by Lady-Luck** [comment]
I didn't realize it until it was in-game, but I notice you kept the whole arrow navigation system. Why not just have a button for each category instead?

**Pull request merged**
