### PR TITLE
Alphabetizes sheet crafting menus

### PR DESCRIPTION
**Pull request by Cartlord**
## What Does This PR Do
I alphabetized the crafting menus that show up when you use metal sheets in-hand, like the one that pops up when you use Iron in-hand. 
This was webedited, and partially tested - I was unable to get administrator permissions working on a downloaded copy of Paradise Station's code, so I tested the menus for Uranium, Titanium, Iron, Plasma, Glass, all alloys thereof, leather, cloth, and cardboard. I tested those because I was able to obtain all of them without excessive effort. The game ran fine and all those menus worked, but I'm not sure if the crafting menus for the other minerals worked - though I see no reason why they wouldn't.

## Why It's Good For The Game
Makes it easier to find stuff in the crafting menus.

## Changelog
:cl:
tweak: Sheet crafting menus are now alphabetized
spellcheck: Changed one reference to "Tranqillite" to "Tranquillite"
spellcheck: Hairless hide's description now says "its" instead of "it's"
spellcheck: "Breakdown into sand" is now "Break down into sand"
/:cl:

### CODE REVIEW

**Comment by Cartlord** [comment]
i wanted to give this a silly name but the people in ooc said i shouldn't swear in pull request titles

**Comment by dearmochi** [comment]
Not a super fan of this PR - messing with the order of recipes can really mess with people's muscle memory, and the fact this was web edited doesn't inspire much confidence.

A better alternative would be to port the stack menu to TGUI and sorting on the client side. Objecting for now.

**Comment by Cartlord** [comment]
If confidence is what you want, I can mention that this is the second server I've made these changes to, and the last one got accepted after some people helped me find where I'm screwed up in my code. I've checked over this P.R., and ensured I didn't make the same mistakes as I did on my first try.

**Comment by dearmochi** [comment]
Different codebases have differing standards and guidelines, and I'm still not convinced this PR would benefit the players as it is.

**Comment by Cartlord** [comment]
Understandable. I was mainly trying to convey that _I'm pretty sure this will work_.

**Comment by Denthamos** [comment]
Putting an objection in on this, echoing reasons above made by Mochi.  The main objective with such menus should be to turn them to TGUI to finish up that conversion project.  With TGUI a search bar on such menus would be nice to quickly find what you are trying to create.

**Comment by Cartlord** [comment]
That's understandable, I just figured alphabetical sorting would be generally more navigable for newbies and I don't know how to do T.G.U.I. code.

**Comment by Denthamos** [comment]
> 

Oh do not mis-understand me.  Its a good objective to make this easier for new players entering the game, but at the same time should not make it harder for something so ingrained with how the players have been using it for years on end.  In the end the current organization of it is not detracting from the experience of the game as well, so it is not something that is required per say.

**Pull request closed without merging**
