### PR TITLE
Maintenance Overhaul Part Two

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This is a continuation of: https://github.com/ParadiseSS13/Paradise/pull/1242

maintenance2

Yes, abandoned bar is in-tact; it's not going anywhere any time soon.

Other changes:

maint1
- added some static loot to arrivals overhauled maintenance
 - Nothing really noteworthy, at all.

poolssss
- Pool has been moved a bit due to the increased size of maintenance.
- Added in the wrestling masks and boxing gloves closet
- replaced the advanced trauma kits with a medical first aid kit

Fixes
- Fixes an improper area tag placed in arrivals maintenance.

### CODE REVIEW

**Comment by tigercat2000** [comment]
>removes pool
>doesn't show that part of the map in screenshot

I sense a problem here, and people on the other PR still had concerns. 
@monkeysfist101
@JaxSiran
@fj45

**Comment by fj45** [comment]
This is better then the last one but still has issues...

Maint bar is far too isolated now, great for antags, not very good for any RP.

Remove the bit with the blast doors and tiny rooms with lockers, it will allow you to make the entire area a little more compact. Ditch the poker machine and the lockroom next to it.

Then just pull it all in to be a little more compact.

**Comment by tigercat2000** [comment]
Okay, I've looked over this, I have a few questions

First, why is the library maintnance double-walled? Doubled up walls don't smooth correctly, and as far as I know are considered bad mapping practice when unnecessary, not to mention that it was two plating before with storage.

Second, what's with the huge slowdown from the blast doors? It would make so much more sense to just go straight across where the windows are. And, if those blast-doors are closed, it's even more of a delay, a pointless delay if you ask me.

Third, moving the holodeck is asking for trouble honestly, although I can see why you did. 

Fourth, why is there an unlocked external access door there? That's not consistant with the rest of the map at all, we use cycling airlocks everywhere, and style breaks like that are bad. Not to mention the potential for abuse, having locked airlocks is a good thing.

Fifth, the station exterior is horribly janky like this, another style break from the relatively smooth surface of the rest of the station external walls, it's a really annoying delay to spacewalkers, and I don't see the point of most of it like the chair against a window sticking out 5 turfs.

**Comment by fj45** [comment]
Another thing I just thought of:

With the chapel mass driver going to the right, I will be unable to expand the escape podbay. I should have done it far sooner, but something like this:




Would be impossible with that mass driver setup.

**Comment by Krausus** [comment]
> added some static loot to arrivals overhauled maintenance

Like what? You can't just say "I did things to this thing" and expect people to download and compare the maps to find out what you actually did.

> * unfortunately, to fit this these map changes in, I had to remove the pool area
>   * it can be re-mapped in, again, in the future--for now, though, people can use the beach.

You *what?* No. *Hell* no. You didn't have to remove anything - you did it because it was easier than doing the job right. If you can't copy-paste stuff in without having to bulldoze something else, **don't**. If you can't be arsed to actually put effort into mapping new stuff in, **don't**. 

In fact... please just stop copy-pasting stuff from Boxstation. :-1:

**Comment by Fox-McCloud** [comment]
Oki doke, to address a few things

- Airlock type has been updated to be the cycling style
- double-walled hallways has been changed to be single walled
- I tested holodeck; the different ones teleport in properly and there's no issues with i
- I dare say the south east and west side of the station are just as jagged as this is; there's lots of juts and points that stick out at various places--Xenobio and Viro just plain just out into space, themselves--- and that leave lots of little nooks because of it.

- The blast doors are precisely there to create situational bottlenecks; you can't make the entire place into a fortress or island immune from entrance (any more than any other spot, anyway), but you can alter the path someone has to take to get to you, if you so desire.


@fj45 

Pods are exclusively the the property of karma-locked jobs, so..the prospect of there being a publicly available construction bay for pods isn't good; that said, if the Bay is expanded in the future, then that can be addressed then. Unless a map-change is very shortly coming up, there's not a point in holding off existing potential map-changes for hypothetical future ones (ie: this also occurred with the engineering shuttle).

**Comment by Aurorablade** [comment]
*turns off lurk mode* dunno how i feel about losing the pool. I did like that area. not sure how to add it back in thouhg unless you shrunk some of the planned maintance area here (it does seem a bit big).

for the old bar, maybe swap it with that abandoned engineering area (so it can be closer to the chapal/library area. then maybe scoot that engie area over toward the solar acess a TINY BIT.

on the podbay, Lets not look as it as construction but more like parking/repair (for the pods found in the wilds of space) so no construction features but enough to repair and land if needed (for people like me who play sec pilot sometimes..go against carp..the carp like to move to dodge my lasers and munch on my armor.) i know i can repair inside my cockpit but need to recharge my battery and welder at some point...and getting to that pod bay is more convenient.  

But yeah..just my thoughts...i will just..go..over...*hides in locker, resumes lurk mode*

**Comment by ZomgPonies** [comment]
I'm alright with expanding the maintenace -- Although I'd prefer to see a large use of 'rusted' walls which we have spirtes for, and more 'abandoned' rooms rather than a 'maze & secret enclosed' rooms structure personally

**Comment by Fox-McCloud** [comment]
Oki doke, updated it; pool has been re-mapped.

**Comment by Fox-McCloud** [comment]
Added in some rust to make it feel/look even more rundown.

**Comment by tigercat2000** [comment]
The major problems have been fixed, but, I just don't like the style nor the pointless slowdown- and I don't think we really need a random chokepoint in maintnance. I don't see the point in it. I don't get the point of placing another atmos cutoff point there either.

**Comment by monkeysfist101** [comment]
It's great and all that you took the time to yank this from another server, but do you have any idea how a space station works? If not, let me enlighten you. Stations are built from the center out. The stuff in the middle (grav gen, bridge, etc...) came first. It was built as the inner ring. From there, cargo, engineering, medbay, and residential came next as they were vital to the running of the station. Lastly, security, science, arrivals, departures, and the library/chapel came last as they were not vital to the stations functioning. This maze of maintenance is idiotic at best mechanically and realisticly. The further out you go, the more refined the station should be. That and the fact that the station now looks like hundreds of sewing needles stuck to a magnet.

**Comment by veganzombeh** [comment]
I absolutely love the use of rusty walls. I'm not sure I like the placement of the abandoned bar though. That looks very much tacked onto the end of the station. Perhaps move it more to the left so it doesn't look like it's hanging off the station?

**Comment by Fox-McCloud** [comment]
@monkeysfist101 

I don't think "realism" is a good argument, in this case---if that were the case, then the engine, atmos, and gravity generator would all likely be in the very center of the station, as those are, by far, the most important aspects of providing for an expandable space station---it's also unlikely that science would be nestled as far away as it is, as it it was commissioned as a research station. This is definitely the pattern the ISS followed, as well (http://en.wikipedia.org/wiki/Assembly_of_the_International_Space_Station)

As for realism of the maintenance? I believe the area is meant to be an area that is actively been constructed (and is unfinished) or construction began, but was later abandoned (I believe these are meant to represent apartment complexes). But I don't think realism is as important of an argument here as mechanics:

Mechanically, it's an area that provides tremendous roleplay opportunities for people interested in on-station building projects (I dare say building projects on station are better than ones at the derelict, as far more people can get involved)--it also provides a lot of nooks and crannies to duck into and hide out it from the AI/security/a traitor---a route that doesn't have heavily pre-defined and predictable escape paths.

Lastly, Metastation is coming: https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-02-04%2015-18%20MSv40A%20Full.png

It has the same style maintenance and allows for the same "maintenance games" as this map edit allows; it makes map designs more cohesive between the two and helps eliminate players wanting to pick one map over the other because of a singular feature.

@veganzombeh 

I can move it, potentially yes--I'll defer a bit to @SamCroswell, as the bar is his design.

**Comment by Krausus** [comment]
Huh, I think this centered pool actually looks nicer than the off-to-the-side pool. Not sure if the pool controller will still link with all the tiles at that distance, though.

As for the design of the maintenance... yeah, it does feel fairly nonsensical. Had the same feelings about the previous port, too. Twisty tunnels and rooms thrown together for the sake of "look at all these twisty tunnels and rooms to hide in!"

> Lastly, Metastation is coming

Maybe...

> It has the same style maintenance

Metastation's maintenance seems to have lots of storage rooms, plus weird things like a maintenance medbay, garden, mech fab, etc. I wouldn't say it's the same style at all - it feels *mostly* purposeful, whereas this just feels random.

Also, the abandoned bar just kinda jutting into space like that looks terrible. I'm pretty sure you'd need more than one full roll of cable just to get it powered, though I suppose there's plenty of cable over there to the left, with the... conveniently-placed grenade-making supplies? Really?

**Comment by Fox-McCloud** [comment]
The pool controller has an edited range of 7 to ensure it can hit all the tiles; pretty sure 6 would have covered it, but I wanted to be safe.


As for pre-spawned loot; a lot of that is getting replaced with lootdrop, eventually (once meta is merged or my patience for it to be completed, expires); there's very little in terms of pre-spawned loot, ATM; anything that can be obtained in there (minus the sunglasses and some fluff clothing) are already obtainable, en masse, elsewhere.

**Comment by Fox-McCloud** [comment]
Moved the bar so it's more cohesive with the rest of maint.

It helps fit in with the slot machine too.

**Comment by ZomgPonies** [comment]
This is fine for now. I did comment to fox that I'd like to see less mazes and more purpose to the abandoned rooms, but someone else can go over it for a 2nd pass from here on out. This is just to get people talking, because otherwise maint will remain as if for the forseeable future as noones wants to get involved.

**Comment by Plotron** [comment]
I agree with "the station now looks like hundreds of sewing needles stuck to a magnet" and @Krausus.

In fact, it's put so perfectly that I have nothing to add.

**Pull request merged**
