### PR TITLE
Add dmisort.sh script, and sorts all icons in .dmi files

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds a new Shell script to the dmitool folder called "dmisort.sh". Running this script will prompt you to enter a subfolder of the dmitool folder. Once you enter it, all .dmi files in that folder will have its icons sorted alphabetically. It's probably a shitty script as I've never used Shell before, but it works.
2) Sorts all icons in all of our .dmi files (that are in the /icons/) folder.

This is a 30MB or so change, so it'll conflict with everything. Therefore, be sure to pull once this is merged. May also require all users to download resources when they join the server (not sure though).

Hopefully this won't have any side effects, but I don't see why it would.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I don't think this is a good idea.
Icons being sorted alphabetically are not necessarily a good thing.
I know a lot of icon files are sorted by relevance to each other.

**Comment by Markolie** [comment]
Mhm, haven't seen those before. Can you give me an example file?

**Comment by tigercat2000** [comment]
mob/Alien.dmi is a good example. It's not in alphabetical order, but it's sorted to make as much sense as possible. Each alien class is stuck together, walls and weeds and objects are all sorted together.
Off the bat, if you were to sort this alphabetically, Xenoborgs would be seperated from their module sprites, I'm sure there are other things.

**Comment by Markolie** [comment]
Don't think that's very relevant. You will still be able to find both sprites if you look. In the end, the upsides of having everything alphabetical far outweigh any "relativity" that may be in certain icon folders. If you want stuff to be grouped together, give it a similar name. 

Also, in the example you gave there's alien sprites (dead, unconscious) all over the place. So the file already isn't relative anymore.

So I see no reason not to move forward with this.

**Comment by tigercat2000** [comment]
Because it's pointless and is going to conflict with any PR that touches an icon?

**Comment by Markolie** [comment]
Except there's none open right now, and there's a neat feature called "Pull" which will prevent any such conflicts.

And trust me, it's not pointed. I spent hours sorting through inhands folders to find certain sprites.

**Comment by tigercat2000** [comment]
Then run it on the huge files. I still don't think you should blindly modify every icon file to be alphabetical with a script.

**Comment by Markolie** [comment]
Unless you can give me a concrete example where this would cause any sort of an issue, I really don't see the point in NOT doing it.

**Comment by Iamgoofball** [comment]
Alphabetical sorting in icons will make my life so much easier. :+1:

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

Hopefully /TG will do it, some day.

**Comment by Fox-McCloud** [comment]
As an addendum.

This was merged in quickly because it was agreed upon by all three maintainers, didn't add or take away anything from the game, and would conflict with literally *ANYTHING* and everything that touched sprites.

**Pull request merged**
