### PR TITLE
Grey uniform sprites

### PR DESCRIPTION
**Pull request by StreakyHaddock**
Fixes all easily accessibly uniforms for the grey species. 
Important thing to note: Greys are so skinny that there is a vertical strip of negative space between the back of the sprite and regular backpacks. This is covered up by most external suits. In addition, this sprite error doesn't occur with satchels or dufflebags. It's on my list of fixes, which will probably come at about the same I give the coats/jackets/vests etc a sprite fix.

Adds:

- Blueshield
- Blueshield Skirt
- Pod Pilot
- Security Corporate, Formal and Dispatch Alternate Uniforms
- Warden Formal Uniform
- Psychiatrist Uniform
- Psychiatrist Turtleneck
- Soviet Uniform
- Coroner Scrubs
- Red Pants
- Khaki Pants
- Female Black Suit
- NT Rep Skirt
- Blue and Yellow Performer Outfits
- Jester Uniform
- Gladiator Uniform
- Sun Dress
- HoP Alternate "Whimsy" Uniform
- Sailor Dress
- Navy Executive Suit
- Brig Physician Skirt
- NT Diplomatic Uniform

Previews:

Backpack Glitch, Security Loadouts, Psych Uniform, Blueshield + Skirt, Pod Pilot, Black Scrubs(Coroner)

https://imgur.com/a/VSTos

All Others

https://imgur.com/a/9llla

### CODE REVIEW

**Comment by taukausanake** [comment]
inb4 this PR gets closed in favor for a new one with more fixes. Good work though, 👍

**Comment by StreakyHaddock** [comment]
Nah, these are aaaaall the uniforms. There may be some I missed, but they're probably obscure or old ones. I'm temptedto just re-add the back line so it doesn't gross out backpacks that much but I decided that I'd really rather just revamp everything. I'm not going to open any more PRs or make any more edits until a maintainer/headmin/popular opinion makes me.

**Comment by KingPhilipIII** [comment]
Grey powercreep. Human Master Race. Downvote to build a wall.

**Comment by KasparoVy** [comment]
☠️

**Comment by taukausanake** [comment]
What happened? I was only joking about the PR getting closed

**Comment by StreakyHaddock** [comment]
Becau

**Comment by StreakyHaddock** [comment]
I must have closed this by mistake when I was trying to clear up the fucktons of duplicate branches I made.

**Pull request merged**
