### PR TITLE
Makes floorcluwnes dress you up as a cluwne instead

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Felt a bit overkill to fully remove you from the round. Instead it now dresses you up as a cluwne. So they will have to do some work if they want to keep your old body.

**Changelog:**
:cl: Farie82
balance: Floor cluwnes now only dress you up as a cluwne. Their little cluwne pet
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
It only cluwnes smite targets constently. If its wild floor cluwne its a prob(50) code chance so it half and half (probs are tricky to get right sometimes).
From what i know only smite cluwnes have been used so far.

Honk.

**Comment by farie82** [comment]
Knoh.

So the admins wanted to stop me from living... I see how it is. :P

**Comment by Ty-Omaha** [comment]
This is a bad idea.

Having people be _dressed_ as a cluwne while not actually being a cluwne? 

"adminhelp: "SO AND SO KILLED ME BECAUSE I WAS IN CLUWNE CLOTHING"

If people are in cluwne clothes they can't take it off, and telling people you aren't allowed to kill people in cluwne clothing because _technically_ they aren't actually a cluwne is not something that is logical.

There's no difference between the two apart from the honk tumour, name change and cluwne voice.

**Comment by farie82** [comment]
well you probably won't be in cluwne clothing to be honest. The floor cluwne removes every limb and spits it out. Only part you have on your body is the suit.
I can see the reasoning though but it's just a bit lame to be permanently removed from the game by a feature that is really cool.

**Comment by Aurorablade** [comment]
Thats..Actually the point of the mob..to violently and scaryly kill you
trust me. If this thing was untargetted and wild...You don't want to come back..

**Comment by Ty-Omaha** [comment]
The mask and the suit are the most prominent things about being a cluwne, shoes and gloves are secondary.

Lots of features result in being permanently removed; antags permanently remove you, space permanently removes you. The whole game has things that permanently remove you.

**Comment by tigercat2000** [comment]
The point of these things is to violently murder you. It's up to admins to decide when that's appropriate. I'm against these changes.

**Comment by KasparoVy** [comment]
I ded

Pls ###revert

**Comment by farie82** [comment]
Gonna close this one. I got what I wanted and yeah these things should be horrifying.

**Pull request closed without merging**
