### PR TITLE
Construction site v2

### PR DESCRIPTION
**Pull request by Kyep**
This is a follow-up PR that makes various further improvements to the construction site, on top of #8493 - based on feedback from players that have been playing with the new csite.

There are three substantial changes in this PR:
1) The engineering outpost airlock that leads to the csite has been moved. It is now a full, separate airlock, and placed to the north, by the mass drivers, rather than next to the engie shuttle dock. This was done because someone mentioned they were annoyed that use of the airlock was potentially depressurizing the engie shuttle dock.
2) The csite itself has had its engine room completely revamped. In particular, it now starts with enough equipment to create a functional engine setup. The intention here is to to allow people to experiment with crazy engine builds without putting the main station at risk from containment failures.
3) Many minor issues have been fixed. 

Detailed changelog:
- fixed issue where one SMES in engine room was storing 150% of its capacity
- fixed issue where eng APC could shock you with engine running as it lacked shock_proof = 1
- added emitters (wrenched/welded), field gens (wrenched, welded, wired), rad collectors, PA and south-facing engine smes to make setting up the engine less of a chore
- added power grid monitors so you can easily see what is powered, and what isn't, as well as testing powergrid output (important QoL thing for people testing new engine setups)
- added vent above engineering but below glass airlocks, to prevent weird pressure issues in this area
- set atmos primary air console to 5066 output pressure so it no longer tries to fill everything at half normal speed
- deleted atmos volume pump as it was pointless - replaced with air meters so you can see when/where gas is flowing now
- added some portable heaters and air tanks to atmos room
- modified ai core room to connect the little hallways for atmos purposes, and also install lights
- fixed a glass airlock east of the bridge, which had the wrong type of floor plating underneath it
- fixed an incorrect setup of the atmos air mixer which was outputting 80% O2 and 20% N, rather than the other (correct) way around
- sealed the eng south hallway and added a vent to the (full of holes) medbay area

There's one more change that I want to make on this branch before this is merged: I want to replace all air alarms with the modified ones provided by https://github.com/ParadiseSS13/Paradise/pull/8495 so that the csite won't be prone to air alarms going straight into panic syphon mode due to atmos weirdness.

csite_v3
csite_v3_atmos
csite_v3_bridge

🆑 Kyep
tweak: Further modified construction site layout, fixing various issues and making it easier to test new engine setups there.
/🆑

### CODE REVIEW

**Comment by Kyep** [comment]
This is a follow-up PR that makes various further improvements to the construction site, on top of #8493 - based on feedback from players that have been playing with the new csite.

There are three substantial changes in this PR:
1) The engineering outpost airlock that leads to the csite has been moved. It is now a full, separate airlock, and placed to the north, by the mass drivers, rather than next to the engie shuttle dock. This was done because someone mentioned they were annoyed that use of the airlock was potentially depressurizing the engie shuttle dock.
2) The csite itself has had its engine room completely revamped. In particular, it now starts with enough equipment to create a functional engine setup. The intention here is to to allow people to experiment with crazy engine builds without putting the main station at risk from containment failures.
3) Many minor issues have been fixed. 

Detailed changelog:
- fixed issue where one SMES in engine room was storing 150% of its capacity
- fixed issue where eng APC could shock you with engine running as it lacked shock_proof = 1
- added emitters (wrenched/welded), field gens (wrenched, welded, wired), PA and south-facing engine smes to make setting up the engine less of a chore
- added power grid monitors so you can easily see what is powered, and what isn't, as well as testing powergrid output (important QoL thing for people testing new engine setups)
- added vent above engineering but below glass airlocks, to prevent weird pressure issues in this area
- set atmos primary air console to 5066 output pressure so it no longer tries to fill everything at half normal speed
- deleted atmos volume pump as it was pointless - replaced with air meters so you can see when/where gas is flowing now
- added some portable heaters and air tanks to atmos room
- modified ai core room to connect the little hallways for atmos purposes, and also install lights
- fixed a glass airlock east of the bridge, which had the wrong type of floor plating underneath it
- fixed an incorrect setup of the atmos air mixer which was outputting 80% O2 and 20% N, rather than the other (correct) way around

There's one more change that I want to make on this branch before this is merged: I want to replace all air alarms with the modified ones provided by https://github.com/ParadiseSS13/Paradise/pull/8495 so that the csite won't be prone to air alarms going straight into panic syphon mode due to atmos weirdness.

🆑 Kyep
tweak: Further modified construction site layout, fixing various issues and making it easier to test new engine setups there.
/🆑

**Comment by Quantum-M** [comment]
Would it be possible to have the pipes present in the Atmos room appear above the tiles (similar to the Cyberiad Atmos loop)?

**Comment by The-Driker** [comment]
This will save a lot of time and give people more reason to actually experiment on the construction site. I support this. 

Now if we could just combine the engineering outpost with the construction site, that would save even more time, instead of shooting materials through space, we could just take the engineering shuttle and be there.

**Comment by Kyep** [comment]
@Quantum-M Unfortunately, the visible subtypes of the plain grey atmos pipe lack corners.

**Comment by KingPhilipIII** [comment]
Just a note. If you have two consoles on each side of the PA can’t reach the middle component to set it up without deconning one or pushing stuff around. Not that big a deal but more QoL

**Comment by Kyep** [comment]
@KingPhilipIII done

**Comment by KingPhilipIII** [comment]
:ok_hand:

**Comment by Citinited** [comment]
You need to offset the field generators so they don't accidentally connect through the middle of the containment area - I had this problem crop up before. The room also needs scrubbers for that inevitable plasma leak 👍

**Comment by Kyep** [comment]
@Citinited done.

Also, I've installed a bunch of glass windows throughout the csite, so its harder to use it as an impossible-to-find cult base. The windows mean that anyone transiting the site has much greater visibility into the different rooms.

**Comment by tigercat2000** [comment]
I love this.

**Pull request merged**
