### PR TITLE
Unathi EVA Suit

### PR DESCRIPTION
**Pull request by Jovaniph**
Unathi now has an EVA suit. Did some minor tweaks to the code for consistency.

189725cc44845875e0031e63cc0d70dfbettere4ed5d86503e4d96885bd45c4d5092342371dff1adb5784da3ee8d05840cdeac

:cl: Jovaniph
rscadd: Unathi EVA suits
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
side views are darker

**Comment by Jovaniph** [comment]
I hate you

**Comment by Anticept** [comment]
Needs waggables too.

**Comment by KasparoVy** [comment]
@Anticept Not a feature of any space suit in the codebase

**Comment by Anticept** [comment]
@KasparoVy alright? That really isn't... helping. Jovan already took what I said and mentioned he might add it to all suits.

**Pull request merged**
