### PR TITLE
Remaps Cere (Farragus) Janitorial Closet

### PR DESCRIPTION
**Pull request by Onyxarias**
## What Does This PR Do
Remaps the Janitorial Closet on Cerestation (Farragus). Moves the APC inside, as well as mildly remapping the maint room right next to the closet.

## Why It's Good For The Game
The Cere janitorial closet is a boring, grey box with janitorial objects placed in it wherever they will fit. This remaps it to be more interesting and thematic, while adding a couple of things useful to every janitor. This also moves the APC to inside of the closet and out of maints, moving the MULE delivery windoor to it's previous place.

## Images of changes
image

## Testing
Spun up a test server, checked to make sure everything loaded in correctly and that the MULE was still pathing well. Marvelled at how far interior design has come.

## Changelog
:cl:
tweak: remapped Cere (Farragus) Janitorial Closet
/:cl:

### CODE REVIEW

**Review by Spaghetti-bit — APPROVED** [review]

**Comment by warriorstar-orion** [comment]
I'd like to avoid more dead-end maint areas leading from the primary hallway, so a tube here to service maints would be welcome. Post-freeze it may be worth revisiting.

2024_07_12__18_22_23__paradise dme  cerestation dmm  - StrongDMM

I'm a fan of this hallway alcove. Could you put some items on the table? Nothing too fancy.

2024_07_12__18_10_03__paradise dme  cerestation dmm  - StrongDMM

Other than that this looks great.

**Comment by Onyxarias** [comment]
> I'd like to avoid more dead-end maint areas leading from the primary hallway, so a tube here to service maints would be welcome. Post-freeze it may be worth revisiting.
> 
> 2024_07_12__18_22_23__paradise dme cerestation dmm - StrongDMM
> 
> I'm a fan of this hallway alcove. Could you put some items on the table? Nothing too fancy.
> 
> 2024_07_12__18_10_03__paradise dme cerestation dmm - StrongDMM
> 
> Other than that this looks great.

Added a janitor figure to the outside table, as well as a medkit, since Box has one in the dorms area as well

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
One of the medkits in medical storage had its pixel bump changed. Can you undo this?

2024_07_14__21_33_09__paradise dme  cerestation dmm  - StrongDMM
2024_07_14__21_37_27__cerestation dmm (Pull Request) (d__ExternalRepos_third_party_Paradise__maps_map_

**Comment by Onyxarias** [comment]
> One of the medkits in medical storage had its pixel bump changed. Can you undo this?
> 
> 2024_07_14__21_33_09__paradise dme cerestation dmm - StrongDMM 2024_07_14__21_37_27__cerestation dmm (Pull Request) (d__ExternalRepos_third_party_Paradise__maps_map_

Oh gosh, whoops, I'll fix that right now

**Review by warriorstar-orion — APPROVED** [review]

**Review by Burzah — APPROVED** [review]

**Pull request merged**
