### PR TITLE
Updates the ERT laser carbine sprites

### PR DESCRIPTION
**Pull request by Stokes52**
NOTE: This PR will conflict with my security guns update (https://github.com/ParadiseSS13/Paradise/pull/15871) because they both modify guns_lefthand.dmi and guns_righthand.dmi.  I can rebase and fix merge conflicts after either one is merged, or if this PR gets approved too I can combine them beforehand, just let me know and I'll take care of it.

## What Does This PR Do
Following in the footsteps of my security laser update (https://github.com/ParadiseSS13/Paradise/pull/15871), I've decided to update another gun that sorely needed a visual rework, the ERT laser carbine.

The design is inspired by the PDW handgun carried by the ERT, but lengthened and modified to accommodate the unique laser magazine that the ERT carbine uses. This is the only gun on paradise that uses a magazine but fires laser ammo, so it provides an opportunity to do some cool things with animations to show off how unique this gun is.

ERT_comparison

The old ERT carbine has a new animated sprite, updated description, visible ammo state changes on the gun and magazine, and new sprites for both spent and unspent casings

## Why It's Good For The Game
The ERT laser is another highly used weapon with a poor sprite. This fixes that to make it into something unique and interesting and hopefully on par with the other great gun sprites on Paradise.

## Images of changes
Animations! Glowy ammo, ammo counting magazines
ERT_gun

Hand sprites!
ERT_hands

Description!
ERT_description

Action shot!
ERT_shooting

## Changelog
:cl:
add: New sprites for the ERT laser carbine, magazine, ammo, and in-hand sprites
add: Code that makes the ERT laser carbine magazine and in-hand sprites update based on ammo
/:cl:

### CODE REVIEW

**Comment by Pyrodes** [comment]
The greenish coloration for the carbine feels kind of weird for a space station environment but other than that it looks amazing.

**Review by dearmochi — APPROVED** [review]

**Comment by E-MonaRhg** [comment]
To be honest I like the more military, practical-ish look of the IK-60 that we have now rather than the funky sci-fi look of this PR. This looks a bit too much out-there. 
However if you want to keep going with this one I will say that the green doesn't fit, black or navy blue would look better.

**Comment by Stokes52** [comment]
I can definitely see the point about it being a little too sci-fi or out. After all, this weapon is very conventional (magazine, cartridge based ammo, traditional casing extraction) despite firing "lasers".

After sleeping on it, I want to play with a few more designs myself.  Maybe I can come up with something similar in spirit while leaning closer to a conventional firearm.

Closed for now. Expect this one to return in a different form someday.

**Comment by S34NW** [comment]
sad

**Comment by hal9000PR** [comment]
i love this :C

**Comment by Stokes52** [comment]
Thanks for the support, this will return soon, I promise!

**Comment by Stokes52** [comment]
Check out my updated sprites here: https://github.com/ParadiseSS13/Paradise/pull/15894

**Pull request closed without merging**
