### PR TITLE
Adds vox quill rustle emote

### PR DESCRIPTION
**Pull request by ExitGame**
After troubleshooting, I came to the conclusion that I pressed spacebar one too many times.
Tested on private server and works 100%.

Adds vox quill rustle emote (backed by lore) (INCLUDES SOUND).
Replaces instances of horrible if(species.name == "") with if(get_species() == "")

Here goes my first (successfull) PR.

🆑 
add: vox quill rustle emote
fix: species check
/ 🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
you may want to make this *quill or something

*rustle sounds like it distinctively belongs to Diona.

The sound sounds like a freaking rattlesnake.

**Comment by taukausanake** [comment]
Yeah, *quill would be better than *rustle. Not agreeing it's more Diona though, last I noticed they don't have leafs. ~~(Diona leaf hairs when)~~

That _is_ a rattle snake. Maybe something more fluffy would work better? But that might sound a bit weird too...

**Comment by MischievousGremlin** [comment]
Quill rattling to get VOX ANGER across! Now we can finally challenge the captain for their leadhats!

**Comment by ExitGame** [comment]
The rattlesnake sound effect is the cloest I came to quill rustling, I haven't founda ny other.

**Comment by davidchan13** [comment]
If we get *quill I'd also like *skrek and *skree (/s but not /s)

All the same, :+1:

**Comment by KingPhilipIII** [comment]
SKREEEEEEEEEEEE

**Comment by tigercat2000** [comment]
Where is the sound from?

**Comment by ExitGame** [comment]
It's in the code.

**Comment by tigercat2000** [comment]
Missed that, 👍

**Comment by tigercat2000** [comment]
LGTM

**Comment by adamkad1** [comment]
but we allready for *scream for shriek, what other skreks we would get?

**Pull request merged**
