### PR TITLE
Fixes weird identity problems

### LINKED ISSUE #10567: security bots see arrest status trough all possible cover
**Problem Description**:
What is the problem?
security bots see arrest status trough all possible cover
**What did you expect to happen**: 
Why do you think this is an issue?
Punishes being stealthy.
**What happened instead**:
How is what happened different from what you expected?
Secbot should not ignore different id, hidden face, different suit, and see arrest status with bluespace powers
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Punishes stealthy playstyles.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Hide your face with mask. Wear different ID, whole different suit.
2. Sec bot uses bluespace powers to find out that you are wanted, and goes to arrest you

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Fixes a few things
1. Beepsky now will respect your identity like expected. He no longer will look right through your disguise and check your face even if disguised.
2. Fixed the medical and security logs using the old and insufficient way to get the identity. 
3. Fixed PDA's not giving you a job icon when put in the ID slot

Fixes #10567

**Changelog:**
:cl:
fix: Beepsky will now respect your disguise again. No more looking right through that gasmask
fix: Medical and security HUDs now use the correct way to identify somebody. They will see the same as you do on your screen.
fix: You will now get a job icon in the sec HUD when you use your PDA as ID. It'll use the PDA's assigned job.
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
Not sure on #3 since it removes the ability to hide IDs in your PDA.

**Comment by farie82** [comment]
@shadeykinds untrue. You can hide them in your pda and put the pda in your pda slot. This only holds for when your pda is in your ID slot. Then you will also be known anyway. Just not by the HuDs

**Comment by Shadeykins** [comment]
> 
> 
> @Shadeykins untrue. You can hide them in your pda and put the pda in your pda slot. This only holds for when your pda is in your ID slot. Then you will also be known anyway. Just not by the HuDs

Ah, alright. I figured this also covered an ID hidden in the PDA when the PDA is in the PDA slot.

**Comment by farie82** [comment]
If somebody else wants to take on the PR feel free.

**Comment by variableundefined** [comment]
wot

**Pull request merged**
