### PR TITLE
Prevents organs from going necrotic during abductor surgery.

### LINKED ISSUE #9823: Random Death Mid Abductor Surgery
**Problem Description**:
Pretty much right what it says on the tin. I was abducted while passed out drunk alongside Squishy. They begin the surgery though I die before they start removing my organs. I'm not sure how, at all really. I had nearly perfect health but I just...died. Squishy was surgeried just fine and lived on until the round ended. So I'm at a loss as to what happened. For reference; she was drunk and passed out too, so I don't think that's why.

**What did you expect to happen**: 
I expected to not die on the operating table for no reason.

**What happened instead**:
I died.

**Why is this bad/What are the consequences:**
Obviously problematic to die to an abductor and be spat out in a random area when you shouldn't of died. Unsure if it's related to slimes only or if it's an RNG bug altogether.

**Steps to reproduce the problem**:
1. Be drunk.
2. Pass out.
3. Get abducted.
4. Die mid surgery.

Honestly not sure how to perfectly reproduce it or if that's relevant to the bug happening at all, but, there's the info.

https://i.gyazo.com/9b076c9111db0c4a3ae65329afbba384.png

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Drinking and passing out.

### PR DESCRIPTION
**Pull request by alex-gh**
**What does this PR do:**
Even though the abductor operation table automatically injected spaceacillin it was still not enough to prevent victims from going septic and and dying in certain cases. 

This PR ups the dosage and fixes that.

Fixes #9823

EDIT: If #9827 gets merged I would rewrite this PR to use it. 

**Changelog:**
:cl: uc_guy
fix: You can no longer get an infection and die during abductor surgery.
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
I had Normaly look into the logs and there's no attack logs at any point that indicate a vector for infection, keep in mind it takes nearly half a minute of an organ being removed before it goes septic--a point which isn't terribly relevant since abductors don't re-implant the heart.

I'm spitballing here but the issue is more likely the surgery taking slightly too long and the Corazone running out, thereby causing a heart attack and leading to death.

**Comment by alex-gh** [comment]
The vector for infection is the overall filthiness of the place.

Abductors do not use surgical masks or gloves, don't clean the instruments and worst of all: The ship is very cramped with at least 2 or sometimes 3 people being in close proximity to the operating table. It is pretty much everything you don't want when doing surgery.

**Comment by Shadeykins** [comment]
That makes a little more sense then, forgot about that as a factor. UC_Guy threw in his weight behind that hypothesis as well.

**Comment by alex-gh** [comment]
> That makes a little more sense then, forgot about that as a factor. UC_Guy threw in his weight behind that hypothesis as well.

By the way I am uc_guy.

**Comment by variableundefined** [comment]
@alex-gh 9827 merged, can you change the PR?

**Comment by alex-gh** [comment]
Done.

It is functionally not exactly the same as the previous code and will result with up to 40u of chems injected. But it is a bit of a race against the clock situation, considering how fast alien instruments are.

**Pull request merged**
