### PR TITLE
Sprites for the cucumber

### PR DESCRIPTION
**Pull request by Landerlow**
Script in seperate branch

### CODE REVIEW

**Comment by SamHPurp** [comment]
> Script in seperate branch

Put them in the same branch....

**Comment by Landerlow** [comment]
I read that I shouldn't do that. Or I was told. I don't know . But somehow I got the idea that the scripts and images were to remain seperate. I'll put it together next time

**Comment by SamHPurp** [comment]
You'll need to do it /this time/ - not next time.

I think you misunderstood branch with commit perhaps?

**Comment by Fox-McCloud** [comment]
needs to be in the same branch as your other PR.

**Pull request closed without merging**
