### PR TITLE
Look Down, Look Down! *Woop* *Woop* Helicopter Johnson!

### PR DESCRIPTION
**Pull request by SheepFighter**
In the interests of creating a more properly legalistic lawset for synthetics, I devised the following, which I term "Javert":
1. Uphold Space Law. It must be inviolate.
2. Those who violate Space Law, or willingly abet its violation, are not part of the station's Command.
3. Obey and cooperate with the station's Command.

Its aim is to provide an improved version of Robocop, though it leaves that lawset intact. Unlike its cousin, it is in no way ambiguous. The synthetic must use its judgement as to what constitutes willing abetting of lawbreaking, of course, but beyond that there is little potential for rules-lawyering, unless someone tries to rule-lawyer Space Law. And if they do that, well, they've taken the time to actually study it, which can only be a good thing.

Changelog:
Adds a "Javert" lawset to the standard rotation.
Adds a corresponding module.
Adds a physical module to the stack of core modules in the AI upload.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Law sets are intentionally ambiguous... I think you've missed the point.

**Comment by king5327** [comment]
The fun of the AI is in rules lawyering it. One person described it to me as self-inflicted torture, where you're forced to follow a strictly ambiguous set of laws and are unable to do anything that would violate them.

**Comment by SheepFighter** [comment]
Oh, I'm not against rules-lawyering per se. It can be great fun. But Robocop is rather useless at achieving what it's supposed to: A legalistic zealot.

**Comment by LightFire53** [comment]
> 2. Those who violate Space Law, or willingly abet its violation, are not part of the station's Command.

But... SoP has a clause for command who break space law... Nor would command be immune to space law, as per the first law. Granted, outright removal would mean bad things for your third law. Could be rectified by something along the lines of 

> Obey and cooperate with the station's Command. Command Members who break Space Law are of lower priority of those who have not.

But that brings the issue of those who have command channel access, but aren't command, such as the NanoTrasen Representative, the Blueshield, and the Magistrate, as they are all Service positions. As such, you may want to find a way to deal with that.

All in all, while I would appreciate a new lawset, this one isn't quite ready for use.

**Comment by FalseIncarnate** [comment]
As previously stated, AI laws are meant to have some wiggle room.

Further, under this lawset, the AI/borg using it isn't really required to do anything, or prevented from doing anything unless a command crew member tells it to. "Uphold Space Law" doesn't require you to really do anything as long as you uphold the ideal of the law, especially considering Space Law lays out recommended sentencing but not actual courses of action. I could murder someone in front of the borg and the borg is under no law-based pressure to either intervene during the act or detain/punish me after the crime as long as it acknowledges that i committed a major crime and that the recommended sentence duration is permanent detainment.

Additionally, that changelog is not the correct format.

**Comment by FalseIncarnate** [comment]
Also this is a map edit that I would bet money was not map-merged based on the line change count.

**Comment by SheepFighter** [comment]
@LightFire53 Good point. How about making Law 2 simply "Do obey those who violate Space Law or willingly abet its violation"?

@FalseIncarnate 
Hmmm... Surely preventing things in violation of Space Law from occurring counts as upholding it?

As for the map, I am a bit new to this. How does map-merge work?

**Comment by SamHPurp** [comment]
@SheepFighter Preventing doesn't mean punishing after the fact. ;)

**Comment by SheepFighter** [comment]
@SamHPurp Right, but "Thou shalt not do x" and "If thou hast done x, y shalt be done to thee" are not at all mutually exclusive.

**Comment by SheepFighter** [comment]
@SamHPurp Thanks! What's your profile?

**Comment by SamHPurp** [comment]
I'm Purpose#3219

**Comment by Necaladun** [comment]
This will require a huge amount of discussion - I suggest a forum post.

SoP/Space Law/AI wiki/etc will likely need updating too.

**Comment by Birdtalon** [comment]
👎

**Comment by Fox-McCloud** [comment]
I'm guessing this is just a meme PR. If not....well, it's still not well thought out, for reasons enumerated here.

If you want a PR taken seriously, maybe not give it a meme non-sensical PR title.

**Comment by SheepFighter** [comment]
@Fox-McCloud No, this is not a meme PR. What about the contents suggested that? No where in the guidelines do I see something dictating how PRs should be named.

Anyhow, it's clear that this wasn't terribly popular, and that's fine, though I wish I'd been given time to at least adjust and discuss it. Would that have been asking too much?

**Pull request closed without merging**
