### PR TITLE
Xantholne Cyborg Fluff

### PR DESCRIPTION
**Pull request by Xantholne**
53845350b46e3200567f9bf266b78c2c
Cyborg Fluff Sprites

### CODE REVIEW

**Comment by Anasari** [comment]
\o/

**Comment by Anoonki** [comment]
\o/

**Comment by SigholtStarsong** [comment]
...Wut am I looking at.

**Comment by Draconic-saint** [comment]
I blame @Aurorablade, but these like literal dicks.

Phallus-bot 4001

**Comment by Aracino** [comment]
Shit they do look like dicks.

**Comment by Anasari** [comment]
Adminhelp: NewToThisGame/(Rublux McDoofus) (?) (PP) (VV) (SM) (FLW) (CA) (REJT) (PP) (TAKE) : HELP A REDDICK IS CHASING ME DOWN THE HALLWAY AND SHOOTING LASER AT ME

**Comment by Birdtalon** [comment]
\o/
 ()

**Comment by Birdtalon** [comment]
Penisbot

**Comment by FlattestGuitar** [comment]
The colors don't really match departamental colors, and that should be rather obvious to any observer.

fixpls

**Comment by taukausanake** [comment]
I just want to see directional icons for these. Jumping into the .dmi is fine and all but what if I'm feeling lazy?

**Comment by MrFroztee** [comment]
I personally think they're a bit skinny in design, leaves them looking a bit lacking. The perspective is also a bit weird, as is most with SS13, where the view varies with sprites. Mostly just the pencil neck is an issue.

**Comment by Xantholne** [comment]
You people are your obsession with phalic objects is worrisome

**Comment by Draconic-saint** [comment]
It's all that ERP we're subjected to, during adminduty. Scarred for life...

Doesn't make it look less like a dick tho, also please provide side-view pics, so we can ~~determine if it also looks like penis from the side~~ have a full view of what the model would look like

**Comment by Aurorablade** [comment]
BWAHAHAHAHAHA

**Comment by Xantholne** [comment]
I'm going to beat you up for making people think this, Aurora

**Comment by SamHPurp** [comment]
"I'm being arrested by a literal cock!"

**Comment by taukausanake** [comment]
So the side icons look like a swan and a mantis had a baby. No penis head in that regard. Really weird. Might use a bit more detail maybe? I know I can't make anything better however

**Comment by KasparoVy** [comment]
Everything from the legs up looks sick. I feel the legs could be done differently, as right now I get the vibe that they detract from what is, otherwise, a pretty dope looking set of sprites.

**Comment by TravellingMerchant** [comment]
If this gets in I'll eat my hat.

**Comment by Xantholne** [comment]
You don't even have a hat you fuckin clown

**Pull request closed without merging**
