### PR TITLE
Dog Beds

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Added Dog Beds from tgstation, constructible with 10 wood planks, deconstructed with a wrench. Also added "Ian's Bed" to Cyberiad and Meta.
dogbed

:cl:
add: Added dog beds! Can be made with 10 wood planks and deconstructed with a wrench. Ian's Bed added to Cyberiad and Metastation.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
:cl:
Increases Vulpkanin ERP
/:cl:

**Comment by Jovaniph** [comment]
While I do like the bed for Ian...I don't like where the copier is positioned.

**Comment by scrubmcnoob** [comment]
i think an essential and critical feature of this PR is missing
there needs to be a gibbing factor somewhere in there when any crewmember attempts to use the bed

**Comment by SamHPurp** [comment]
@scrubmcnoob braindamage would suffice.

**Comment by ConflagratedCanine** [comment]
The bed should slowly heal quadrapeds that rest in it.

**Comment by Fox-McCloud** [comment]
conflicts.

**Comment by Anticept** [comment]
@ConflagratedCanine you joke... but honestly thats damn useful.

**Comment by ConflagratedCanine** [comment]
@Anticept I wasn't joking. It can be really hard to get fed as Ian sometimes. :(

**Comment by Anticept** [comment]
Usually when ian emotes sticking his nose in the box of donuts, I know what he wants.

**Comment by ConflagratedCanine** [comment]
You're a good man, but many others will murdle Ian for eating thier crisps after being kicked. 

The bed is a safer, but slower alternative! 

Also super adorable. Resting sprites when?!

**Comment by uraniummeltdown** [comment]
I'll see if I can make it heal pets buckled in

**Pull request merged**
