### PR TITLE
Adds Deathsquid. Also, Deafsquid.

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
add: Added deathsquid.
/🆑

Two variations: normal and joke.

The normal variant ("death squid") is an eldrich horror sent by the dark gods. It is akin to megafauna in power (ie: very, very strong). Perhaps slightly stronger then that. It will wreck you.

The joke variant ("deaf squid") is an elderly, hard-of-hearing horror that got lost on the way to pick some food at the cosmic drive-through. It has dentures instead of proper teeth. It is intended to be a counter-meme, spawned and offered to ghosts when they keep chanting 'send the deaf squid!!!' in deadchat.

Both of them are adminspawn-only. 

Screenshot:
deathsquid

Credit to FoS aka FullofSkittles for the sprites.

### CODE REVIEW

**Comment by taukausanake** [comment]
Sexy sprites as always. I like this.

Do they get any powers like megafauna by chance?

**Comment by Kyep** [comment]
No powers. Just 10-100 brute melee attacks on the non-joke version, and 10-20 brute melee attacks on the joke version.

I did experiment with a version that spit out pulse lasers, but I had targeting issues, possibly due to the size of the sprites. Also, since these are meme mobs, there isn't much point coding abilities for them, as they'll be used very rarely.

**Comment by Quantum-M** [comment]
Clearly, you are confusing it for Nanotrasen's top hit live drama _Deafsquid: The Galactic Journey_.

(The sprite is awesome, by the way. Is it animated by any chance?)

**Comment by Kyep** [comment]
Yes, the sprite is animated. All credit to FoS for the sprites. I did none of that work.
I just added simple in-game entries to define them as mobs, and tested them. That's it.

**Comment by RyanSmake** [comment]
I disapprove, because it's admin only. This means it will do nothing other than gathering dust.

Please make it a random event or something.

**Comment by KingPhilipIII** [comment]
Consider it’s power and realize why making that randomly spawn would be terrifying.

**Comment by taukausanake** [comment]
Turn it into a megafauna and throw it onto the mining asteroid. No different than Lavaland almost

**Comment by Kyep** [comment]
I'm not going to make this into a megafauna, or place it on mining, or pre-spawn it anywhere else.
In terms of megafauna, that type has other properties I may not want this to inherit.
In terms of mining asteroid, miners have no hope of killing this. More generally, we don't have lavaland mining, and we shouldn't be pretending we do. We should just port lavaland.
In terms of not spawning this anywhere else except by manual admin spawn... this is, frankly, a meme, and while the odd meme can be funny, prespawning it anywhere will make it lose its humor value. So, no prespawns.

**Comment by RyanSmake** [comment]
Then we don't need this. We already have a lot of meme mobs and such in the code without anyone ever using them, and no, use once a year does not count.
I think we should have less useless admin-only things. But I do agree this is kind of funny, but please, find a way to place it somewhere. A major event maybe... With extreme rarity.

**Comment by Ralta** [comment]
I see no reason to decline this purely on the basis of _we already have a lot of admin-only things_.

God forbid we add more things to make the odd round more flavourful than the usual array of antags. Like sending in a Death Squid to fuck with a crew who BSA'd the cult attempting to summon Nar'Sie. Or sending a Deaf Squid in response to a clown's prayer for a Death Squad (admins can be hard of hearing too, y'know).

**Comment by RyanSmake** [comment]
While that is certainly an amusing thought I am most certain it will still happen only on the "once in a year" basis I mentioned. The problem with this is that even admins will not know about it and if they do they will forget it pretty quickly.

We see regular megafauna relatively frequently because they are used on other servers, and thus it is hard to forget them. There is nothing that would remind people about this existing though.

**Comment by taukausanake** [comment]
I kind of agree with @RyanSmake, I'm all for adding more things in but admin only things aren't going to be touched nearly enough for the sake of keeping them special and maybe the amount of work needed to make an event happen. These will be used for a bit right after getting merged maybe but not the month and so on after.
And no matter how you look at it this is an original megafauna that doesn't want to be one. It's not special in any way except for its amazing sprite and that's a little more sad than admin only meme

**Comment by Spartan6** [comment]
You guys realise there’s no harm in adding it, right?

Like, it’s more damaging not to add it. Admins have less tools to work with if you don’t add it. You don’t want to add it on the basis you will rarely see it, but then you’ll never see it if it gets denied.

This isn’t some admin gun or admin clothing, it’s a mob, the most used thing by admins to get an event going. The more stuff we have the merrier, and it doesn’t effect you to have it added to their toolbox.

**Comment by RyanSmake** [comment]
This very thing can be easily created with VV. Should it be something extremely unique or interesting I wouldn't have an issue with it. But as of now this is just a glorified spacecarp.

**Comment by tigercat2000** [comment]
This has enough unique behaviors to be difficult-to-impossible to completely replicate by admin tools, such as being explosion-proof and moving in space, plus it has a lot of changed variables, and JSON deserialization is still a beta project. Additionally, just because this is being added as an admin-spawn only creature does not mean that it will never be able to be used in the future. Besides, it's interesting (and hilarious) enough to warrant hardcoding in.

**Pull request merged**
