### PR TITLE
Upadates Patch's Jacket icons and adds some more colors

### PR DESCRIPTION
**Pull request by shazbot194**
Quite a small PR, just updates the icons for my custom item and adds in a couple more colors. No CL since it isn't an item that effects anyone but me. 

patch_jacket

### CODE REVIEW

**Comment by Aurorablade** [comment]
Did you clear this with the heads first, normally making several colors for one fluff can be met with some discontent. While it seems you are already adding colors to a fluff with multiple I would still get head consent before a PR. Unless you did then ignore me.

**Comment by shazbot194** [comment]
I did forget to get head approval before hand, as this started as an update to a fluff item, but I have since asked Pyro, and he has given me the go ahead.

**Comment by tigercat2000** [comment]
@DarkPyrolord affirm pls

**Comment by tigercat2000** [comment]
he affirmed

**Pull request merged**
