### PR TITLE
Firstresponder

### PR DESCRIPTION
**Pull request by Landerlow**
🆑 
Add: Adds the job title of First Responder as alternative to doctors and paramedics.
/ 🆑

### CODE REVIEW

**Comment by LightFire53** [comment]
I would only do that for paramedic, not medical doctors

**Comment by Landerlow** [comment]
Yeah. Also I get that remote tracking branch crap again, I do not know WHY that keeps happening. I used a CLEAN master file. GRR. Will do it for only paramedic later. WIthout that Merge remote-tracking branch thing.

**Comment by Landerlow** [comment]
IF anyone knows how to prevent that by the way, please explain

**Comment by Landerlow** [comment]
But I do like it for doctors though, too. It's not just for paramedics IRL either. It could als obe some form of ER certified doctor, after all.

**Comment by tylerh95** [comment]
Doctors aren't first responders. First reponders are those that traditionally travel to active emergency scenes.

**Comment by Ty-Omaha** [comment]
The term "First Responders" is generally acquainted to EMS, Firefighters and Police. People who _respond_ to a scene. Not in-hospital care

**Comment by Birdtalon** [comment]
Leading merge commits 👌

**Comment by alexkar598** [comment]
Do you use git GUI or GUI bash?

If you have git bash and you have your upstream setted,run these commands

Git fetch upstream
Git reset upstream/master --hard

These will clean your branch of any changes that happend on your branch

**Pull request closed without merging**
