### PR TITLE
Swaps metastations toilets and cryo dorms around. 

### LINKED ISSUE #22664: NSS cerebron - Cryodorms are too close to engineering, can be in SM blast radius
**Issue Description**:
See 
image

Cryodorms are too close to engineering and have a possibility to get caught in the blast radius. 

**What did you expect to happen**: 

**What happened instead**:

**Why is this bad/What are the consequences**:
Given that SM delaminations are not uncommon, it can regularly impact cryo capabilities for players.

**Steps to reproduce the problem**:
Yes. 

**When did the problem start happening**:

**Extra information**:
This is not a 'bug' but rather a flaw in station design. Or oversight. Or just unforseen consequence.

### PR DESCRIPTION
**Pull request by 1080pCat**
## What Does This PR Do

Swaps metastations cryo dorms, and also touches a bit of maints, the areas directly outside cryo dorms, and a nanomob battle terminal, to fit around the moving.
## Why It's Good For The Game

Currently, if a delam happens on meta, theres quite a high likely hood that it'll hit the cryo dorms, damaging, or even entirely making the area not safe for people no longer in the round, so this will Resolve #22664.
## Images of changes

StrongDMM_BMnv8zaAz6

image

image

## Testing

Compiled, had a look at the areas, nothing was broken.
## Changelog
:cl:
tweak: Changed the locations of cryo dorms, and the toilets on metastation, as well as slightly remaps the maintenance tunnels around them to fit.
tweak: Moves a nanomob battle terminal, so the above changes don't cover it on a mapping level/if you have x-ray. 
/:cl:

## Additional notes 
I am aware of how cursed the toilet looks, however sadly this is the cleanest way to currently do this, as the north facing sprite(the one that'd look towards the door) is unusable, and refuses to abide by my pixel shifts.

### CODE REVIEW

**Comment by warriorstar-orion** [comment]
I recommend holding off on merging to HEAD locally until #22737 is in, or disabling the git hooks (though I can't say how badly that would go)

**Review by Henri215 — CHANGES_REQUESTED** [review]
Looks like someone wants a free unum deck :D

1. This camera has been removed, worth checking if there are any blind spots on that area.
image

2. Is there no better place for that nanomob battle terminal blue? Its in front of a closet.

3. This sleep room area should be the maints one next to it? I dont know, at least it is like that with the old meta cryo (toilets got the same "issue").
image

**Comment by Henri215** [comment]
https://github.com/ParadiseSS13/Paradise/pull/22488 Is going to conflict with your PR, good luck :D

**Comment by 1080pCat** [comment]
> #22488 Is going to conflict with your PR, good luck :D

Mainly this, and after chatting with ven and doing some testing, we've mostly made the cryo dorms not blow up.

**Pull request closed without merging**
