### PR TITLE
[SPRITE] Security Greatcoat - Papers Please!

### PR DESCRIPTION
**Pull request by Spaghetti-bit**
## What Does This PR Do

Adds a new security greatcoat, looks nifty. Fits the color pallette of security that the spriting team is looking to normalize across departments.

## Why It's Good For The Game

More drip, is another example for spriters to copy a color pallette off of. Gives off that 'papers please' vibe.

## Images of changes

All races wearing their coats. Specific races with diff. sprites: (Vox, Kidan, Drask, and Grey)
image

## Testing

Local server, started a round, ooo'd and aaa'd at a secdrobe. Went to admin testing like 20 different times over the different iterations of this coat.

## Changelog
:cl:
add: Added security great coat. Identical armor stats to security jacket.
/:cl:

### CODE REVIEW

**Comment by TravisAngeI** [comment]
we setting a security checkpoint up at arrivals with this one

**Comment by Daylight2** [comment]
Also functions as security bathrobe

**Review by Sirryan2002 — APPROVED** [review]

**Review by Fordoxia — APPROVED** [review]
I approve of this drip.

**Comment by Spaghetti-bit** [comment]
Closing this branch, I messed up a rebase.

**Pull request closed without merging**
