### PR TITLE
Fancy Footwear Rebalance

### PR DESCRIPTION
**Pull request by Jountax**
Does anyone actually blow all their loadout on these?

The fancy sandals and dress shoes are both dropped to 2 loadout points.

In the process of making this I learned that dress shoes are actually identical to laceup shoes in all but name and description, too. If I had the spriting mojo to do so, I would fix that.

:cl: Jountax
tweak: Fancy shoes no longer cost one's entire loadout.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Fancy shoe power creep.

:-1: x :100:

**Comment by Kyep** [comment]
Are these available in vendors in locker room?
If yes, why spend 5 LP on something that you can pick up just after arriving for free?

**Comment by Jountax** [comment]
@Kyep Laceup shoes are available in the vendors, which was my reasoning for adding them to the loadout system in the first place. With that in place, however, it makes it quite hard to justify getting the fancy 5 loadout point shoes, hence this PR.

Plus I had the idea while making that other one and felt like finally seeing if it would go over well with the community.

**Comment by Shadeykins** [comment]
If you're a donator you have ten points rather than five, but this is a digression.

Job restrictions exist for items that are actually restricted to those jobs, IE: uniforms specific to a department. I'd rather just see a net TC reduction (1-2), rather than being unable to use these 99% of the time because of job restrictions (which will make it an even rarer choice, I'm not sure about anyone else but I sure don't dynamically modify my loadout choices prior to picking a different job).

**Comment by taukausanake** [comment]
I blow out my points for Fancy Sandals. Not like I use them to get anything else, vulps aren't supposed to wear shoes so I need something on my feet.

Make cheap sandals and I'll be okay with this change

**Comment by Jountax** [comment]
I would be up for dropping the access restrictions and just making the shoes cost less than 5 but more than 1, if that sounds like it'd work better than this.

As far as loadout points go, I tend to view the loadout system as a way to have an 'outfit' that is uniquie to your character upon spawning, and an item that takes up the entire loadout is not conducive to that. I was not aware donators got 10 points, though.

**Comment by Jountax** [comment]
Went ahead and dropped the role restrictions and just made the things cost 2 points each.

**Comment by tigercat2000** [comment]
Sure why not (who made them so expensive?)

**Pull request merged**
