### PR TITLE
It's opposite day!

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
rscadd: It's opposite day!
/:cl:

### CODE REVIEW

**Comment by king5327** [comment]
Why would you think this is a good idea?

**Comment by taukausanake** [comment]
This is CrazyLemon talking. It's in his name and most PRs he merges

**Comment by king5327** [comment]
See, if there were some sort of flag that let admins enable it for certain mobs (maybe strange reagent could have a chance to apply this effect for 10 seconds?), that would be cool. As it is now, no.

**Comment by mrturkeytoe** [comment]
Nice changelog :upside_down_face:

**Comment by AndriiYukhymchak** [comment]
meme?

**Comment by jughu** [comment]
Does staff of healing become staff of death?

**Comment by alexkar598** [comment]
so with this if you bleed to low blood level and your on fire you can spacewalk?

**Pull request closed without merging**
