### PR TITLE
Fix for Riot Foam Darts

### PR DESCRIPTION
**Pull request by shazbot194**
- Separates Riot Foam darts from normal foam darts so they work
- Still lets you load pens into both riot foam darts and normal foam
darts

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This doesn't really explain what this PR dose, at all.

**Comment by shazbot194** [comment]
My bad, looking back it isn't quite as clear as I thought it was.
When running a test server I noticed that the riot darts for the DonkSoft weapons were shooting the wrong foam darts and needed their caps removed in order to work properly. After looking in the code and fiddling with it, I found out the way the foam darts are coded only really works for the main blue capped darts with the red tipped riot darts kinda tacked on. I did copy the code to make them two separate items that function similar while still having the riot darts keep their stamina damage.

**Comment by Fox-McCloud** [comment]
Uh...riot foam darts work just fine---they properly deal stamina damage--their icons don't update properly, but that's the only bug that I can see---and this is certainly not the proper way to fix it (copy-pasting the code).

**Comment by shazbot194** [comment]
Ok, when I tested it I guess it bugged out on me, I will try again to fix the icon and be more original.

**Pull request closed without merging**
