### PR TITLE
Ports icons for Vents & Scrubbers

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Ports this PR from Eris https://github.com/discordia-space/CEV-Eris/pull/3707 (Looks like they ported it from bay, who knows the author gives no credit)

I was going to redo how the update_icons are handled for these two atmos devices, but on consultation with headcoders it was decided this isn't the PR to start refactoring that.

## Why It's Good For The Game
3/4th perspective vents and scrubbers? Madness!
For real though, only when you look at these nice, smoothly animated sprites do you realise quite how _crusty_ out vents and scrubbers currently are. Good bye soul.

## Images of changes
In order:

~~Holopad: Unscrewed | Inactive | Call connected | Incoming Call~~ People not keen on these, will shelve this bit for another time.
Scrubber: Filtering | Filtering Extended | Siphoning | Siphoning Extended | Plating (shows the frame it has)
Vent: Sucking | Blowing | Plating (shows the frame it has)

https://user-images.githubusercontent.com/12197162/176035537-e3a9ca28-c81c-4b84-9e05-e6a03f6b7fe6.mp4

## Changelog
:cl: S34NW, AlexMorgan3817
tweak: Updated sprites for Vents and Scrubbers
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Oh this also adds sprites for an as of yet unsupported vent mode similar to extended for scrubbers. Watch this space.

**Comment by CinnamonSnowball** [comment]
The vents and scrubbers are quite pretty! It's sad the holopads lose the nice parallel between their scanline animation and the hologram's scanline animation, though

**Comment by AffectedArc07** [comment]
I love these a lot more than the TG ones

**Comment by Qwertytoforty** [comment]
Vents / scrubbers are nice, however as AA said, not sure on the holopads. Current holopads have a animated light pattern when active, that lines up with the light distortion on the hologram. It would be nice to have a holopad sprite that keeps that.

**Comment by Denthamos** [comment]
Agreeing with AA and Qwerty here.  The vents and scrubbers are top notch.  The holopad though feels a bit off.  Can you post a video of the holopad in action with someone using it to call an area and what the holopad callers sprite looks like with it?

**Comment by S34NW** [comment]
I'll just yeet the holopad changes

**Comment by SteelSlayer** [comment]
Correct me if I'm wrong, but we don't have expanded mode for vents, so the `in_expanded` and `out_expanded` states are not needed.

**Comment by S34NW** [comment]
> Correct me if I'm wrong, but we don't have expanded mode for vents, so the `in_expanded` and `out_expanded` states are not needed.
> 
> 

Not yet no, I thought I'd port them in case we added it. Don't have to though

**Review by SteelSlayer — APPROVED** [review]

**Review by hal9000PR — COMMENTED** [review]
image
the double vent in the middle doesn't get a frame

**Comment by S34NW** [comment]
> image the double vent in the middle doesn't get a frame

Thanks, addressed

**Review by SteelSlayer — APPROVED** [review]

**Comment by Dafrek** [comment]
image
Passive vents and unary vents seem to have very similar sprites now, this isn't a huge deal, but it would be nice to be able to tell the difference between a passive vent and a regular vent that is off without examining them closely.

**Pull request merged**
