### PR TITLE
Make "Reply" PDA messenger button clickable without scrolling

### PR DESCRIPTION
**Pull request by moxian**
## What Does This PR Do
Makes the messenger app a bit less tall.

## Images of changes

(please also note the lack of a rightmost scrollbar compared to the video above)

## Changelog
:cl:
fix: PDA messenger "Reply" button is now clickable without scrolling
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
The QOL update that no one ever remembers we need ♥️

**Comment by Christasmurf** [comment]
Finally
Small messenger

**Comment by Carthusia** [comment]
YES! god this has been bugging me since we switched the UI over to this type

**Comment by AffectedArc07** [comment]
While you're in here can you make the bgcolour property for the bottom buttons work?

It used to in older commits of the initial PR but a code review suggestion made it not work and I didnt realise.

**Comment by moxian** [comment]
Done, thanks for mentioning it worked in your previous PR. For some reason styled `background-color` on react elements gets ignored, so you have to use the html equivalent. I have no idea why, but it works now:

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
