### PR TITLE
Minor hunger sprite adjustment

### PR DESCRIPTION
**Pull request by png103**
## What Does This PR Do

Fixes the hunger sprite to remove a weird extra pixel that shouldn't be there, and adjusts the color of the full sprite, does the same for the vampire blood sprites

## Why It's Good For The Game

Looks a bit better

## Images of changes

hungry
full

## Changelog
tweak: Hunger sprite changes
/:cl:

### CODE REVIEW

**Comment by png103** [comment]
wait i spent 2 hours trying to upload this and i don't even think i uploaded the right thing give me like 10 hours i need to come back to this with a clear mind

**Comment by png103** [comment]
yeah i just checked i didn't even upload the right thing

**Comment by roarbark** [comment]
if you haven't been using it, https://www.paradisestation.org/wiki/index.php/Guide_to_Contributing is an incredibly good guide on github stuff, which can be pretty opaque especially if you have no larger coding background

**Comment by png103** [comment]
There we go that's it

**Comment by hal9000PR** [comment]
might be good to update the food one to the new TG burger sprite.

**Comment by png103** [comment]
image
not sure about you but i'm not sure if this works well as an ui icon, may just be me

**Comment by png103** [comment]
what's with the workflow check thing? last time i saw it checked automatically

**Comment by hal9000PR** [comment]
> what's with the workflow check thing? last time i saw it checked automatically

Your account has no merged PRs so its got to get a maintainer to run the checks.

**Comment by Miraviel** [comment]
> image not sure about you but i'm unsure if this works well as an ui icon, may just be me
> 
> not to mention we would probably have to change the rest of the ui icons to fit with the more fancy looking burger, else it'd just stick out

I think it does not work because it lacks a clear outline, which is necessary with UI elements!

You can try adding the hunger bar's outline to it (`#191918`):
image

Or darken its outline, if you don't want to mess with colour shifts, then with a simple black overlay (just a quick example of 126 alpha opacity set to multiply with `#191918`):
image

I'm not sure how either of this looks like ingame, I'd leave it up to you to decide which one seems better!

**Comment by AffectedArc07** [comment]
Please deconflict

**Comment by moxian** [comment]
The conflict arises from the fact that #17603 moved the icons from icons/mob/screen_alert.dmi to icons/mob/screen_hunger.dmi

**Pull request closed without merging**
