### PR TITLE
Fixes the black suit jacket (from vendors and uplinks)

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

title
Issue caused by it having the wrong path.
## Why It's Good For The Game

Bug bad
## Images of changes

Before
image

After
image

## Testing

- Spawned both the jacket and its armored version to verify the sprite
## Changelog
:cl:
fix: Fixed the black suit jacket (from vendors and uplinks)
/:cl:

### CODE REVIEW

**Review by Contrabang — APPROVED** [review]
oops... LGTM

**Comment by Christasmurf** [comment]
oops

**Comment by Henri215** [comment]
> oops

Yeah, it could compile because the armored version existed :(

**Comment by Christasmurf** [comment]
> > oops
> 
> Yeah, it could compile because the armored version existed :(

i was gonna say i caught all the other stuff it told me about but it never said those nor did i have CI errors so i just forgor they existed (i was fully aware of the armoured jacket but i knew it used the same sprite (which i didn't change the name of) but not the same typepath so i didn't think it was an issue since it didn't pop up)

**Review by DGamerL — APPROVED** [review]
I think having it renamed to be the `iaa` jacket is silly, as it's used for more things than that

**Review by S34NW — APPROVED** [review]

**Pull request merged**
