### PR TITLE
(wip) Special maps

### PR DESCRIPTION
**Pull request by png103**
I know we're currently on a feature freeze, but this is a wip and i want to have admin aproval _BEFORE_ i lose another 2 weeks and my sanity trying to port more maps
## What Does This PR Do

Adds special maps!, these will only appear with a 25% chance at the end of map voting.
This would be used for more experimental/silly maps.

## Why It's Good For The Game

Adds a little more variation, if cyberiad, delta or the third map ever get boring, players have a chance to vote for something different.
## Images of changes

Currently only 1 map is available for voting/playing:
**Dababy 2**

this map contains

### **_Platforms_**

image
image
image
image

### **_Enviromental story telling_**
image

### **_Bell_**
image
_ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding ding_ 

### **_Big doors (oooo where will they take youuu)_**
image

### **_Friendship ruiner 2000_**
image

### **Cute pets!**
image
Garronte, the chaplain's owl

image
Major duck, the hos' son

### **_Map is huge_**
image

## Changelog
:cl:
add: Adds random special maps.
/:cl:

## To do

- fix dababy 2's colored windows
- finish porting the goon r4047 map, still don't know the name but it's been pain to port so far
- eventually make it so special maps are distinguishable from normal ones in the voting screen, maybe making the button a different color? or have it be in it's own section

### CODE REVIEW

**Comment by AffectedArc07** [comment]
General consensus from both heads and maints is that we don't want extra maps.

You also seem to have imported some Hispania commits.

**Comment by Sirryan2002** [comment]
Thumbs down bc this encourages more  maps to be added which will make map contributors and wiki contributors life hell atm.

**Comment by png103** [comment]
that's a shame, could we atleast use the map for ann event or something? i don't want my efforts to be _completly_  in vain

**Comment by png103** [comment]
i'll close it for now, hopefully i can do something with it later on

**Pull request closed without merging**
