### PR TITLE
Fixes wild west cheese

### LINKED ISSUE #4788: Look at this one simple trick to WIN wild west map!!!1 Mappers hate him!!
**Problem Description**:
There is a missing invisible wall in the wild west gateway map, this allows the cheesy nerds to skip the entire town area like the cheesemongering turdjugglers they are.

x = 129 
y = 17 
z = 8

**What did you expect to happen**: 
For the cheeseblocking magic to be actually cheeseblocking

**What happened instead**:
There's a hole for the pooper-snoopers to slip in from

**Why is this bad/What are the consequences:**
It skips the hard part of that place and allows the damn nerds to walz right into the wishgranter maze

**Steps to reproduce the problem**:
Jump to coords I gave, see that the magical cheesebuster wall is not there, cry.

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Fixes? Removes? Whatever the word is. This (hopefully) seals the holes in the wall of blockers preventing players from cheesing the town part of the wild west away mission by digging through the rock wall things.
Fixes #4788

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'd still like to see a pic of this, personally.

**Comment by LittleBigKid2000** [comment]
Before

After

Before

After

Before

After

**Comment by LittleBigKid2000** [comment]
Before

After

**Comment by Kevak** [comment]
This technically does not stop bluespace crystal cheesing. Might wanna disable crystal/tomato useage for the zlevel to halt cheeses.

**Comment by KasparoVy** [comment]
:mouse:

CHEEZE!?!?!

**Comment by Tastyfish** [comment]
:mouse:

**Pull request merged**
