### PR TITLE
[DNM] Radial menus for cyborg module selection

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds a radial menu for cyborgs choosing a module, to replace the current input menu system.

The cyborg won't get any module tools or abilities until both the module and the sprite have been chosen, allowing players to change their mind if they selected the wrong module.

Todo:
- [x] Proc documentation.
- [x] Radial menu icon for the Hunter and Combat modules.
- [x] Test the Hunter, Destroyer, and Combat modules.
- [x] Make sure fluff sprites are working.
- [x] Figure out how to test fluff sprites.
- [ ] Get new sprites for the module selection icons.

## Why It's Good For The Game

Far more intuitive and better looking than the current system, especially with the sprite selection. Rather than having to guess what the sprite will look like using a slightly janky 'x attempts left' system, the options will be immediately visible to the player.

## Images of changes

https://user-images.githubusercontent.com/57483089/134349435-d13317ef-b0b9-4c84-94b0-eff2f4b6ea41.mp4

<details>
<summary><b>Images:</b></summary>

Paradise Test NSS Cyberiad 2021-09-21 225615
Paradise Test NSS Cyberiad 2021-09-21 225701
Paradise Test NSS Cyberiad 2021-09-21 225705
Paradise Test NSS Cyberiad 2021-09-21 225625
Paradise Test NSS Cyberiad 2021-09-21 225655
Paradise Test NSS Cyberiad 2021-09-21 225711
</details>

## Changelog
:cl:
add: Added a radial menu system for cyborg module selection.
tweak: Renamed the 'Miner' cyborg module to 'Mining'.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Not sure about the job icons. Maybe an object from each of the jobs (Wrench for engi, medkit for medical, mop for janitor, etc)

**Comment by SabreML** [comment]
> Not sure about the job icons. Maybe an object from each of the jobs (Wrench for engi, medkit for medical, mop for janitor, etc)

I'll look into getting some different ones once I've done the main bits. These can just be placeholders until then.

**Comment by SabreML** [comment]
Just to clarify since it's a pretty important file, there are no sprite changes in `custom-synthetic.dmi`. Some sprites have just been renamed from 'Miner' to 'Mining' since that looks better in the radial menu, and the user's selection is used for the icon state.

I *did* remove the `wisewill-Miner+j` icon state, but only because it's identical to `wisewill-Miner`, and couldn't ever be used since there's no 'Miner+j' cyborg module.
https://github.com/ParadiseSS13/Paradise/blob/84d6a07fe6b74b8ed2d6669de86a075864366712/code/modules/mob/living/silicon/robot/robot.dm#L418-L419

**Comment by SabreML** [comment]
DNM until I get the time to look into module sprites.

**Comment by SabreML** [comment]
I don't have the time or the motivation to work on this at the moment, so I'll close the PR.
Sorry to anyone who was looking forward to this.

**Pull request closed without merging**
