### PR TITLE
Refactors vampire abilities, also some vamp fixes

### LINKED ISSUE #597: Couple Vampire Issues
Upon cloning, Vampires lose their abilities tab and cannot get it back by drinking blood, only way to fix it is to remove and re-give them Vampire antag status.

Upon acquiring 500+ units of blood, the Vampire only becomes immune to the Chapel, yet the description says that you become immune to "all holy things", which should include Holy Water, but doesn't, Holy Water still harms 500+ unit vampires when sprayed or consumed, as does space.

For the latter, I'd suggest either fixing the 500+ unit message or fixing the immunities, to reduce the confusion some people may have with the mechanics.

### LINKED ISSUE #2833: Vampires & Closets
According to CodenameGordan, who for whatever unknowable reason doesn't want to report this himself, when a Vampire closes themselves inside a closet or similar object, they lose access to the tab that displays their vampire abilities, meaning they can't hide in a locker to rejuvenate, summon bats from inside, etc.

I haven't tested this myself, because I don't like playing Vampire much. And by much, I mean ever.

### PR DESCRIPTION
**Pull request by Tastyfish**
- Fixes #597
- Fixes #2833 
 - Assuming that issue was the case beforehand, at least. Either way, it's not an issue now.
- There was an unreported issue where Hypnosis decided who could be affected or not by different rules for no reason.
- The vampire code isn't a tangled mess in general anymore, and doesn't pollute the `/mob` type with 5 different procs that are only called internally.
- Vampire abilities now use the nice spell system, allowing for action buttons and a decent selection panel. The buttons being darkened or not is responsive to recharge, if you've been nullified, and having enough blood.

P1
P2

:cl:
tweak: Vampire abilities are now in their own Vampire tab, as well being action buttons at the top, like spells.
bugfix: Cloning a vampire no longer makes them lose their abilities.
bugfix: Vampires can no longer hypnotize chaplains.
bugfix: Being a full vampire (500+ total blood) actually makes you immune to holy water reliably now.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Can't :+1: this enough.

**Comment by VampyrBytes** [comment]
:+1:

**Comment by Kerroman** [comment]
Very minor tweak.  It's spelled "rejuvenate" not "rejuvinate."

**Comment by TullyBurnalot** [comment]
Spells for vamps?!

WITH RED BACKGROUNDS!??!?!

*SCREAM

:100:

**Pull request merged**
