### PR TITLE
Add sunglasses to Captain HOP and NT Rep lockers

### PR DESCRIPTION
**Pull request by datlo**
## What Does This PR Do

With the PR adding job employment glasses to cap, HOP, and NT Rep their roundstart sunglasses were replaced. However, replacements were not provided if you preferred the style of standard sunglasses. This PR adds a pair in HOP, Captain's and Rep's locker.

## Why It's Good For The Game

Muh captain loadout was changed against my will, violating NAP and I want muh sunglasses back.
Also options are good, especially when it's an option that was already present before being removed.

## Changelog
:cl:
add: Added spare standard sunglasses to Captain, HOP and NT Rep's locker.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
It's a travesty that such a classic part of the Captain look was replaced with those uggo job glasses.

**Comment by FreeStylaLT** [comment]
Let them suffer.

**Comment by Spacemanspark** [comment]
Yeah, I was wondering why those were removed.

**Comment by Gatchapod** [comment]
I'm fairly confident Representatives would also appreciate standard sunglasses, which I believe they used to get.

**Comment by datlo** [comment]
Added to rep's locker too

**Review by SteelSlayer — APPROVED** [review]

**Review by Kyep — COMMENTED** [review]
Can't you still get sunglasses from elsewhere?
The ones these job get (the skills hud sunglasses) still function as sunglasses (flash immunity) but also show HUD icons and skills data.
If you really, really want to go without all of that and just use black shades... okay I guess. But I have to admit I don't understand why you'd want to. Sunglasses are pretty small on your sprite, I feel like they don't make that much difference to the look of your character.

**Comment by datlo** [comment]
Yes, I prefer sunglasses. Significantly so. It's a matter of character look, not what functions they do or don't have. The job HUD glasses dont say 'Authority', they say 'Accountant'. And I shouldn't have to go steal some or order from cargo (if even possible?) to get something that I used to have roundstart.

**Review by AffectedArc07 — APPROVED** [review]

**Review by Kyep — APPROVED** [review]
While I still believe that the skills hud glasses are strictly better than plain sunglasses, the community seems pretty clearly in favor of keeping plain black sunglasses as an option. 

So I'll approve this, based on it being what I think the community wants.

That said, be aware that we are NOT obliged to keep things looking or functioning the way they used to. So arguments of the form "it used to be like this, and you took it away" aren't very good arguments. If something is changed, its changed for a reason.

**Review by dearmochi — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
