### PR TITLE
The Long-Requested Nano-UI-ification of the ChemMaster

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
rscadd: The ChemMaster now uses NanoUI! Yey!
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
pics.

**Comment by Plotron** [comment]
pics pliz

**Comment by monster860** [comment]
There, pics

**Comment by Plotron** [comment]
meh

**Comment by Lady-Luck** [comment]
This fixes the awful delay when you first start to use the ChemMaster, right?

**Comment by monster860** [comment]
Nope, it does absolutely *nothing* to resolve the delay! However, I can attempt to resolve said delay.

**Comment by Taaketa** [comment]
That delay scares the crap out of me everytime. I always set my chem master to transfer as I've had 1 too many accidents sending stuff to disposal.

**Comment by Lady-Luck** [comment]
Please please do. I hate that delay so much.

**Pull request merged**
