### PR TITLE
Reverts Norgad's maintenance overhaul

### PR DESCRIPTION
**Pull request by Crazylemon64**
As per [this thread](https://nanotrasen.se/forum/topic/10097-reverting-norgads-maint-overhaul/).

:cl:Crazylemon
rscdel: Reverts Norgad's east maintenance overhaul
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Would it be too much to ask of the administration to provide a list of 'Dos & Donts' for the next maintenance iteration?

This feels like a result of conflicting visions of what maintenance should be more than anything else.

**Comment by FalseIncarnate** [comment]
We'll try and come up with one, but I can't guarantee a timeline for when that will be made available.

**Comment by Lady-Luck** [comment]
>We'll try and come up with one, but I can't guarantee a timeline for when that will be made available.

I don't suppose the timeline could be 'before this PR is merged'? I'm not excited about the idea of super-cramped maintenance for another year.

**Comment by FalseIncarnate** [comment]
Unlikely, and I also doubt we will be with the reverted maint for a full year.

However, in the interest of keeping things relevant, let's not continue that discussion here and leave the rest of the comments here to actual feedback regarding the revert and not the theoretical maints to come.

**Comment by Jovaniph** [comment]
I wasn't expecting a revert, but this works until a better one is made

I would like everyone to know that this isn't the end of maintenance being change.  Regardless if this gets merged or not, there will be something better that will replace maintenance i am sure. Don't see this as a bad thing.

**Comment by ExitGame** [comment]
Unless something better gets made than Norgad's new maintenance I really am not in favor of the old maints. It is way too cramped for Paradsise's population at the moment and also pretty stale.

**Comment by TravellingMerchant** [comment]
I'm for it. Norgads maints removed a lot of the fun secrets.

**Comment by Lady-Luck** [comment]
>I'm for it. Norgads maints removed a lot of the fun secrets.

I think he only moved them...

**Comment by SamHPurp** [comment]
Frankly, I'll probably drop my other projects to pick up this randomised maintenance design. @Crazylemon64 & @warior4356 might be good to catch up with either of you on utilizing the Map Allocator / Space Ruins stuff.

In the meanwhile, I might do a pass over maint first utilising #6910 tools.

**Comment by Ty-Omaha** [comment]
The old maint is small and cramped. A new one should be made rather than a revert.

**Comment by taukausanake** [comment]
@SamHPurp You mean the randomised maint thing that @monster860 was making but quit because the maintainers didn't like it? I'd like that to be finished too. Random maint tunnels sound fun if done correctly

**Comment by SamHPurp** [comment]
@taukausanake aye

**Comment by monster860** [comment]
I believe the technical term should be that it got "foxblocked"

**Comment by SheepFighter** [comment]
I'm ambivalent as to the actual content, and what Purpose has in store sounds better, but this begs the question: Why was this merged in the first place? I'd love it if we did test merges, but we don't. This is irregular and does not help the impression of the maintainers as secretive and arbitrary.

**Comment by taukausanake** [comment]
> I'd love it if we did test merges

We actually do, but in regards to more code extensive things I believe. I've only once ever helped with such test and I doubt I was much help. Maps though need a full pop to test. Consider the run we've had so far its "test" if you will and now it's getting a revert

**Comment by SheepFighter** [comment]
@taukausanake I would if there'd been any indication that it was. But I don't recall anything of that sort, and so it reeks of maneuvering on the maintainers' parts.

**Comment by granodd** [comment]
Appreciate the effort that went into making the new maintenance. Sadly they're just not very "flowy" as previously mentioned. The old maintenance had a very clear "path" that you could go through to get to places with rooms and such branching off from it, or splitting into two different paths that got to the same area. None of this "large rooms that have many ins/outs/obstructing objects" sorta deal. There were a few things I liked like the bolted doors leading into space (kinda) and then also the "office" area that was next to it, but aside from that, it made running through the maintenance in sweeps seem extremely tedious as there's a lot to it.

**Comment by Anticept** [comment]
What I liked about Norgad's maint overhaul:

Lots of extra rooms that felt like they served some kind of purpose. An engineering lunch room, in progress constructions, etc.

What I didn't like is that they should have still had simple tunnels running through them. As mentioned earlier, these extra rooms should be EXTRA. It would be like moving medbay north 3 tiles resulting in people having to pass through it to get over to science.

**Comment by Lady-Luck** [comment]
It would not be difficult to revise the new maintenance in a way that adds direct paths. Supposedly there is more to it than that, but the communication has been very vague as to what.

**Comment by Spartan6** [comment]
A lot of the love for old maint is nostalgia. Old maint is horribly cramped for the playerbase we have right now. The station needs to be expanded outward, not compressed backward because it's 'different' to the norm. If we had this current maint for the past years and we'd moved to the old maint, there would be this exact same issue and we'd try and get a revert then.

All in all, if you don't have a better merge sitting on the wings, don't step backwards when you feel the first step wasn't firm.

**Comment by TravellingMerchant** [comment]
My concerns mirror everyone elses.

Also the added fact there's less little easter eggs in the new maintenance

**Comment by Lady-Luck** [comment]
>Also the added fact there's less little easter eggs in the new maintenance

From what I've been told by one of the maintainers, fixed items that people really want are not something that's desired in any maintenance implementation.

**Comment by KingPhilipIII** [comment]
I'm in support of the prevailing argument against the reversion. For one thing he put in an awful lot of work to just scrap it, and like stated constantly the larger maintenance section is such a refreshing change.

**Comment by GelatinousGlob** [comment]
I wouldn't mind some improvements on the changes, but reverting it into the smaller cramped shit everyone knows like the back of their hand seems counter productive.

**Comment by Aracino** [comment]
Eh, I liked the changes, plus it's a lot nicer looking than what it's been in the past. I do wish the mait med bay was elsewhere, but not like it's a major issue.

**Comment by Bram961** [comment]
Concerning some comments here
@Lady-Luck "easy" is the wrong word when talking about making new maint make sense, first there are the layout issues which alone take up multiple hours to fix and that is not even mentioning all the mapping mistakes. Chapel maint surgery is literally duplicated on top of itself for example. Those mistakes are invisible in the map editor unless you right click every tile and check for them. 

@Spartan6 the situation wouldn't be the exact same because the things being complained about would be a lot different. The love for old maint is by no means nostalgia, new maint having both conceptual and mapping issues that aren't easy to fix is a big reason behind reverting it and making it better differently later.

@KingPhilipIII putting in work has little to no correlation to quality of the work delivered (I know that sounds harsh but I'm not here to consider peoples feelings over the server), things being different only lasts for about a month and we require the map to last for a lot more than that.

@GelatinousGlob same comment here regarding knowing things, people not knowing this maint will not last long and has in fact already stopped being a thing as far as I can tell.

**Comment by Lady-Luck** [comment]
>"easy" is the wrong word when talking about making new maint make sense, first there are the layout issues which alone take up multiple hours to fix and that is not even mentioning all the mapping mistakes. Chapel maint surgery is literally duplicated on top of itself for example. Those mistakes are invisible in the map editor unless you right click every tile and check for them.

There were PRs that fixed most of the mistakes you're talking about. I imagine they were closed because of this internal discussion for reversion.

**Comment by Lady-Luck** [comment]
I dislike that this merge was done during a server restart. It pretty much ensured the playerbase on at the time would not have a chance to see this PR and comment on it.

But whatever. In the wake of this getting merged, here are the maintenance mapping guidelines I've compiled by talking directly to those involved in getting this reversion passed:

```1. There needs to be a clear, obvious 'main paths' that are efficient and don't pass through decommissioned or derelict areas. This includes paths to the solars.
2. Wires & pipes need to be kept on or near the main paths. They may not pass through reinforced walls unless they absolutely have to.
3. Don't go overboard with abandoned or derelict areas, but do leave useful elements behind. The old bar is a great example.
4. Fixed item spawns (including secrets) should not powerful enough to where players are incentivized to memorize and try to rush for those items at the start of a round.```

Also, as far as randomized maintenance goes: While it sounds nice, it's not likely to pass. Monster860 had a very nice PR to do just that and it was rejected by Fox because it was felt only players should modify the main station map.

**Comment by Fullofskittles** [comment]
> I dislike that this merge was done during a server restart. It pretty much ensured the playerbase on at the time would not have a chance to see this PR and comment on it.

Correct me if I'm wrong but haven't there been multiple threads discussing new maintenance and the possibility of it being reverted in the future? I'm quite certain there was a discussion about it in march and on top of that there was also a thread about reverting it more recently.

How long exactly do you expect people to wait to merge things? Wasn't a recent complaint that PRs took too long to merge?

**Comment by SamHPurp** [comment]
@Lady-Luck Everything isn't a fucking conspiracy.

Also at the time the Discord API / Announcement bot was playing up. This shit happens.

**Comment by Lady-Luck** [comment]
I never said anything about Discord.

**Comment by SamHPurp** [comment]
@Lady-Luck afaik, its the same bot that announces in Discord and in game... because when one isn't working, neither work.

**Comment by Lady-Luck** [comment]
>@Lady-Luck afaik, its the same bot that announces in Discord and in game... because when one isn't working, neither work.

Only if the bot is actually down. It was a Discord API error.

**Comment by Spacemanspark** [comment]
...An announcement /was/ made, you guys missed it.
Like, really, I was busy dealing with a case of shuttle grief and still saw it.

**Comment by Lady-Luck** [comment]
>...An announcement /was/ made, you guys missed it.
Like, really, I was busy dealing with a case of shuttle grief and still saw it.

Was roundstart delayed or something?

**Comment by tigercat2000** [comment]
@SamHPurp It's not, the ingame script and Discord have separate github API event hooks. It was a coincidence that Discord's API was acting up at the time.

**Pull request merged**
