### PR TITLE
Paradise's soul removal part 7: engineering jumpsuits and accessories

### PR DESCRIPTION
**Pull request by ElorgRHG**
_A continuation of a series which had a two year long hiatus._

## What Does This PR Do
Resprites engineering (and atmos) jumpsuits, jumpskirts, berets, CE's mantle and adds _roll down_-able jumpskirts

## Why It's Good For The Game
New, slightly fresher looking sprites.
Also soul removal, that's always good.

## Images of changes

_Every jumpsuit has a skirt variant, I did not include them here because arranging these previews hurts. Check the files themselves on the IDB_

Engineering:
<details>

engineering
</details>

Atmos (just blue engineering):
<details>

atmos
</details>

Chief Engineer:
<details>

ce
</details>

Chief Engineer's mantle:
<details>

ce mantle
</details>

## Testing

Arranged all the species with all the clothing to make the  _Images of changes_

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imagedel: Resprited engineering jumpsuits, berets, CE's mantle.
tweak: Engineering and atmospherics jumpskirts can now be rolled down.
/:cl:

_I'm sorry medmains, I promised you a resprite two years ago and have not delivered, someone else has volunteered to take that cross and that's why I'm doing engineering now._

### CODE REVIEW

**Comment by 1080pCat** [comment]
New sprites look sick. shame magboots weren't included

**Comment by Stoniest** [comment]
The sprite for the Grey's CE outfit on the legs part looks kinda off, compare them to the other sprites and you'll totally see it as well.

**Comment by ElorgRHG** [comment]
> New sprites look sick. shame magboots weren't included

I was _kinda_ thinking about doing magboots in this PR, but there's more magboots than just regular, atmos and CE ones. Different PR maybe

<details>
Preview of the "Different PR maybe" (don't comment on those here, they're not related to this PR in any way)

image
</details>

>The sprite for the Grey's CE outfit on the legs part looks kinda off, compare them to the other sprites and you'll totally see it as well.

They do look kinda off huh? Well anyway, now they dont. Fixed. 
<details>
I'm not updating the image in the PR itself because I don't want to.

no more square ass
</details>

**Comment by Butlerblock** [comment]
The sprites look cool but it gives off a tracksuity vibe instead of a rugged material that might be more common with blue-collar work imo.

**Comment by Sayrbee** [comment]
These look great! any word on the work boots?

**Comment by ElorgRHG** [comment]
> These look great! any word on the work boots?

Work boots resprite will come in the next PR, part 7.25, alongside magboots, fire and rad suits, and maybe some other stuff, hopefully at least. It will be mostly TG ports because they've been cooking real good over there. Wanted to keep this PR jumpsuit oriented (+ CE's mantle).

**Comment by Dafrek** [comment]
Atmos orange beret has been rightfully returned, amazing PR.

**Review by PopeDaveThe3th — APPROVED** [review]
code seems fine

**Review by Christasmurf — APPROVED** [review]
Would change instances of "chief_engineer" to "ce" to be consistent with HoS, HoP and QM, however functions as intended.
Icons are good

**Review by Burzah — APPROVED** [review]

**Pull request merged**
