### PR TITLE
Adds monkeys to the vermin infestation event.

### PR DESCRIPTION
**Pull request by Divulf**
## What Does This PR Do
Adds monkeys to the list of possible spawns in the vermin infestation event.  Monkeys only have a 10% chance to spawn, making them rarer than the other spawns.  In addition, any monkey spawned via this event has a 10% chance to be a rare domesticated gorilla.  Includes custom announcement text.

## Why It's Good For The Game
More monkey = more funny

## Testing
Triggered event.  Monkeys appeared.

## Changelog
:cl:
tweak: Added monkeys to vermin infestation event.
/:cl:

### CODE REVIEW

**Comment by OctusGit** [comment]
I don't think your explanation for why its good for the game is constructive or actually elaborates WHY its good for the game.

**Comment by Sirryan2002** [comment]
Agreeing with Octus here, putting an objection on this PR unless there is a better justification. This just seems like a joke and not well thought through.

**Comment by Divulf** [comment]
> I don't think your explanation for why its good for the game is constructive or actually elaborates WHY its good for the game.
> Agreeing with Octus here, putting an objection on this PR unless there is a better justification. This just seems like a joke and not well thought through.

It has as much "justification" as the vermin infestation event has in the first place.

**Comment by farie82** [comment]
First of all, sorry for the late response to this PR.
The PR will be closed since the corresponding teams have voted against it. Reasons given:
- don't really see a point to randomly spawning monkeys like we do with mice/lizards. Seems like it's going to just cause issues for the crew without and real design reason.
- not a fan of adding monkeys to the vermin infestation event, monkeys are kinda large to be some how missed or looked over like rats or lizards would be due to the size
- Yeah, no real purpose for this and seems like it would just get annoying. Also monkies are not vermin.
- Not really into it, unless there is some cool reason to change my mind that I am not seeing right away.

Due to these reasons, I don't see any way this PR could be changed to be approved.

**Pull request closed without merging**
