### PR TITLE
DeltaStation Tweaks/Fixes

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do

- Adds a secure safe to the captain's office
- Adds the superior welding goggles to the RD office
- Adds ID tags to NT Rep, Chapel, and Robotics surgery electrochromic windows and dimmers
- Adds electrochromic spawners to Security Interrogation instead of panes
- Repipes security to make all pipes go under airlocks instead of windows
     - Repipes dormitories and the courtroom as well
- Adds requests consoles to areas that were missing, including the NT Rep office and Blueshield office to name a few spots
- HoS and Warden now have security newscasters
- Relabels some cargo cameras to fit the rest of the naming scheme
- Relabels the airlock to the room immediately before Fore Starboard Solars to Fore Starboard Solars, requiring solars access
- Relabels the exterior airlock set up in departures from Arrivals External Airlock to Escape External Airlock
- Removes an extra APC and air alarm that was a relic from me playing with areas when removing/moving security checkpoints around in Escape
- Replaces a few sets of 3 way manifolds to be single pipes so they no longer lead to nowhere
- CMO now has a stamp mapped in (I did double check this wasn't included in the other delta medbay fix before doing so)
- Replaces lots of light bulbs with light tubes in public areas to brighten up the main/central corridors
   - Also adds/adjusts the location of a few lights to brighten up some of the really dark spots
- Re-area's the security escape pod so it is no longer affected by the prison break event
   - This had the effect where it would also open up the external airlock, and while that provides a mean to fully escape, it did also have the unintended effect of venting the permabrig atmosphere. 
       - Not opposed to reverting this one if required though
-  Stools and barstools in the bar and dormitories now have proper `dir` variables

## Why It's Good For The Game
 Map fixes be fixey

## Changelog
:cl:
fix: Various map fixes on DeltaStation
tweak: Security escape pod is no longer considered a brig area
/:cl:

### CODE REVIEW

**Review by S34NW — CHANGES_REQUESTED** [review]
image
Missing supply pipe here

**Comment by S34NW** [comment]
Could you also do a favour and replace the newscasters in the warden and HoS offices with security ones. It's been something I've wanted to do for a while and always forgot.

Also, you did not do this either, but could you please make this run under the door too?
image

Apart from the one missing pipe, the PR looks good to me.

**Review by variableundefined — APPROVED** [review]

**Comment by variableundefined** [comment]
@LightFire53 Ping on Discord when concerns addressed.

**Comment by LightFire53** [comment]
Electrochromic windows to the other areas will be a different PR once the GitHub thaws out.

**Pull request merged**
