### PR TITLE
Chair Sprite Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the chair sprites to TG's chair sprites:

chairs

They're a bit larger so you can easily click on them to unbuckle yourself without resorting to alt-clicking.

### CODE REVIEW

**Comment by tigercat2000** [comment]
... don't like them, myself.

**Comment by Spacemanspark** [comment]
Never really cared for the sprite, but the idea behind it is nice.

**Comment by Markolie** [comment]
Sprite isn't as good, but I despise having to pixel hunt to unbuckle, so I'd say that outweighs it.

**Comment by Fox-McCloud** [comment]
Yeah, I don't like them either.

If we ever implement TG's dynamic HUD with "thrown alerts", then switching the sprites would no longer be necessary/this could be reverted (if this gets merged).

**Comment by KasparoVy** [comment]
I think the sprite we have right now looks far better-- this one makes me feel as though the character is child-sized in a gigantic novelty office chair

As for pixel-hunting, there're always large exposed areas of the chair by the legs and above the shoulders of your character unless you're wearing holiday priest

**Comment by Fox-McCloud** [comment]
Just going to wait for thrown alerts for this one.

**Pull request closed without merging**
