### PR TITLE
PDA free DLC: New ringtones!

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds multiple new PDA ringtones:

notif1 and notif2 (entirely new sounds)
boop (from the IPC emote)
gavel
smoke, pylon shatter, egloves, flare, interference, zap, blob attack and spider bite (sounds with the purpose of deceiving)

The two new sounds (notif1.ogg and notif2.ogg) are from https://freesound.org/people/sonically_sound/sounds/703380/ and https://freesound.org/people/Jofae/sounds/380482/.

**Suggest sounds that should be added/removed (and name suggestions too :) ).**
## Why It's Good For The Game

We have a limited amount of PDA ringtones that have been left without an update for a while.
## Images of changes

Video contains the boop, gavel and the two new sounds added.

https://github.com/ParadiseSS13/Paradise/assets/77684085/4548f400-8faa-402e-ad2c-d46497b05f06

## Testing

- See video above
## Changelog
:cl:
soundadd: Added new PDA ringtones
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
Could we get all the ringtones listed somewhere in-game? Bit silly to have to codedive to figure out what flavor sound effects even exist for your PDA

**Comment by Landerlow** [comment]
That's actually a good pont, I've been thinking about something similar when I suggested new ringtones to begin with. Also headset-to-headset phone system when? :D

**Comment by Henri215** [comment]
> Could we get all the ringtones listed somewhere in-game? Bit silly to have to codedive to figure out what flavor sound effects even exist for your PDA

I worry about the same thing, it should at least be a list on the wiki. Any good idea on how to include it into the game itself?

**Comment by Landerlow** [comment]
What about, instead of opening a box where you type the sound you wish to use, you get a fancy menu/UI with options?

**Review by lewcc — APPROVED** [review]

**Pull request merged**
