### PR TITLE
Adds in Pajama Closets

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in 4 pajama closets to the map

- Two in medical patients recovery bed area
- One near the pool/recreation area
- One in arrival dorms near the washing machines.

Adds in a linen basket
- Dispenses bedsheets; one in arrivals dorms, near the washing machines.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Can you add in a bedsheet dispenser thing (Similar to the one in perma) in the arrival dorms near the washing machines as well?

**Comment by Crazylemon64** [comment]
Hmm, what was the original intent of these?

**Comment by KasparoVy** [comment]
I think they were used on maps that had actual bedrooms in dorms instead of cryopods.

**Comment by Spacemanspark** [comment]
I kinda wish we had bedrooms alongside the cryopods.
Metastation has it, and it's pretty nice.

**Comment by Fox-McCloud** [comment]
added in the linen basket.

**Comment by Spacemanspark** [comment]
FUCK YESH.

**Pull request merged**
