### PR TITLE
Removes cancerous mass detected in the codebase.

### PR DESCRIPTION
**Pull request by Iamgoofball**
the sprite had no shading at all, for fucks sake

plus it looked like crap regardless

### CODE REVIEW

**Comment by Regen1** [comment]
Fuck no, I love that hairstyle

**Comment by tigercat2000** [comment]
:-1:, the sprite is fin

**Comment by Regen1** [comment]
Also, why would we remove the most used female hairstyle?

**Comment by ZomgPonies** [comment]
No. Just because we DIDN'T port crazy vg anime hairstyles doesn't mean we're going to start axing current ones. If you want to give the sprite some shading, go ahead and re-open a proper PR.

**Comment by fj45** [comment]
http://puu.sh/h6ALD/7732f4b734.dmi

**Comment by Iamgoofball** [comment]
fuck yes merge it

**Comment by fj45** [comment]
Sorry mate not a coder. Just a mapper.

**Pull request closed without merging**
