### PR TITLE
New Taj Head & Hair

### PR DESCRIPTION
**Pull request by K3Licia**
## What Does This PR Do
Replaces the head sprite of Tajaran and adds new hairstyles, both ported from Tau Ceti Station, along with making helmets and masks fit the new head better.

* [tajaran resprite 2 TauCetiStation/TauCetiClassic#9727](https://github.com/TauCetiStation/TauCetiClassic/pull/9727)
* [tajaran hair sprite tweaks TauCetiStation/TauCetiClassic#9986](https://github.com/TauCetiStation/TauCetiClassic/pull/9986)
All credits go to the original spriter!
## Why It's Good For The Game
As we all know, Tajaran are infamously known for their side profile, which makes them look like they ate a bee. However, that is now no longer real with this PR. We can finally have decent-looking cat people! And with a few more customization options for bonus character creation fun.

## Images of changes
image
image
image

## Testing
1. i connect to my private server
2. they are, in fact, there

## Changelog
:cl:
imageadd: Replaced Tajaran head sprites, edited mask/helmets, and added new hairstyles to match. 
/:cl:

### CODE REVIEW

**Comment by OctusGit** [comment]
Based

**Comment by SchrodingersWolf** [comment]
Thank god. No longer are taj head swollen. Please speedmerge this.

**Comment by XFirebirdX** [comment]
This change is really required as it makes the species unique, I always hated that GIGANTIC swollen head.

**Comment by Screampuff** [comment]
SPEEDMERGEEE

**Comment by Henri215** [comment]
image

**Pull request closed without merging**
