### PR TITLE
Asay Chat Mentions

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Allows admins to ping other admins in asay. This will make their name appear red in chat, as well as playing the priority announcement ding to them, in hopes of getting their attention.

## Why It's Good For The Game
Often an admin can be tabbed out, but needs something answering quickly (IE: Host may be tabbed out but things need queing for next round or something specific at end round)

## Images of changes
image

## Changelog
:cl: AffectedArc07
add: [Admin] You can now @Adminckey in asay to ping them
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Nice. Definitely a good change.

**Comment by farie82** [comment]
Only asay not msay as well?

**Comment by AffectedArc07** [comment]
> Only asay not msay as well?

Could implement it into there, but asay is kinda priority over msay. With msay you also have to deal with mixing permissions since you have to check for +ADMIN or +MENTOR and merge loop stuff together and my 10AM brain cant handle it. If you can generate an elegant solution I may implement it.

**Comment by SabreML** [comment]
You might need to change the sound to something more distinct, since `notice2` plays in-game quite often.
If you're tabbed out you're probably not going to interpret it as "Oh someone pinged me" unless you double check every time the sound plays.

**Comment by AffectedArc07** [comment]
> You might need to change the sound to something more distinct, since `notice2` plays in-game quite often.
> If you're tabbed out you're probably not going to interpret it as "Oh someone pinged me" unless you double check every time the sound plays.

I was thinking of this, but we dont have anything in the sound folder (I played like 60 different sounds before decieding on this). I was going to use a random piano key at one point before realising "thats shit dont do that".

If worst comes to worst, ill make a notify sound

**Comment by TDSSS** [comment]
You could always use the bwoink sound.

**Comment by Shockpoint** [comment]
Is this coming with a toggle or as-is

**Comment by AffectedArc07** [comment]
@Shockpoint I decided against it since disabling the ping defeats the purpose, and if anyone abuses this they can easily be punished.

**Comment by Shockpoint** [comment]
> @Shockpoint I decided against it since disabling the ping defeats the purpose, and if anyone abuses this they can easily be punished. 

If it gets abused, I'm bullying you

**Review by SteelSlayer — APPROVED** [review]

**Comment by Spacemanspark** [comment]
Just use the loud explosion sound or the tspiders siren sound :^)

**Comment by Spacemanspark** [comment]
Actually, as a slightly more serious response, most admins are rather desensitized to the bwoink sound. It would need to be something different.

**Review by variableundefined — APPROVED** [review]

**Comment by variableundefined** [comment]
Clearly we need to use the Garand ping sound for this

**Comment by Spacemanspark** [comment]
I could make a voice recording
"Bitch get yo ass over here"

Perhaps, however, the best sound might be something not normally heard in the game. A bell ringing or chimes or something?

**Comment by AffectedArc07** [comment]
Latest commit adds a new sound for the ping.

**Comment by Spacemanspark** [comment]
You pulled that out of fucking Minecraft didn't you

**Comment by AffectedArc07** [comment]
> You pulled that out of fucking Minecraft didn't you

Yes it is the `pling` sound which doesnt actually exist as a usable sound ingame.


I am glad you said that, because now I am worried over license concerns, and I may end up just making my own ping sound in FL Studio or similar.

**Review by Dumbdumn5 — APPROVED** [review]
I could've sworn I approved this already, but... here goes again!

**Comment by Spacemanspark** [comment]
My offer to record a voice clip of me screaming into the mic still stands :^)

**Pull request merged**
