### PR TITLE
Sprite fixes

### PR DESCRIPTION
**Pull request by WHOMANKIND**
## What Does This PR Do
-Replace r_slime.dmi and human_hair.dmi
-Change offset 2 hairstyle and remove extra pixels from slime person

## Why It's Good For The Game
Because it looked ugly and wrong

## Images of changes
slimeperson
Bobcurl
Curls

## Testing
Yes, with Dream Daemon

## Changelog
:cl:
imageadd: Remove extra pixels around the head (slime person). change offset hairstyle "bobcurl" and "curls"
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
A bunch of other hairs have been changed too, any idea why?

**Comment by WHOMANKIND** [comment]
> A bunch of other hairs have been changed too, any idea why?

oh, i change file from ss220club build, I didn’t notice that the number of hairstyles is different -_-

**Comment by WHOMANKIND** [comment]
> A bunch of other hairs have been changed too, any idea why?

I didn’t notice that some hairstyles were broken, I’ll try to fix it

**Comment by WHOMANKIND** [comment]
> > > A bunch of other hairs have been changed too, any idea why?
> > 
> > 
> > fixed, some hairstyles overlapped others for some reason -_-
> 
> Diffbot is still detecting changes on more than two hairstyles, any idea why?
Sorry, I started doing this for the first time, so maybe I did something wrong, I changed the sprites using Photoshop and then with a tweakpng, maybe I didn’t convert it correctly somehow.
Now I have changed them with Dream Maker.

**Comment by WHOMANKIND** [comment]
> > > A bunch of other hairs have been changed too, any idea why?
> > 
> > 
> > fixed, some hairstyles overlapped others for some reason -_-
> 
> Diffbot is still detecting changes on more than two hairstyles, any idea why?

Sorry, I started doing this for the first time, so maybe I did something wrong, I changed the sprites using Photoshop and then with a tweakpng, maybe I didn’t convert it correctly somehow.
Now I have changed them with Dream Maker.

**Review by Henri215 — APPROVED** [review]
Its looking goodd now

**Review by S34NW — APPROVED** [review]

**Pull request merged**
