### PR TITLE
Adds a medbay door access button to medchem

### PR DESCRIPTION
**Pull request by owenowen212**
A small quality of life feature that allows for med-chemists to grant access to those trying to get into medbay, without having to come out of medchem, as is sometimes necessary in the absence of anyone working the medbay reception.

This is sometimes an issue on either very busy or very quiet rounds when no one else in medbay is available to grant access but emergency access has not or will not be added to the medbay entrance.

- Replaces the reinforced walls on the eastern of medchem with reinforced windows, overlooking the medbay lobby.
- Adds a port medbay entrance doors access button inside medchem.
- Rearranges a couple of station intercoms and medbay signs.

**Image:**
The edit

### CODE REVIEW

**Comment by taukausanake** [comment]
I like the windows for Chemistry but I don't think the Chemists should have the permission to allow people in, at least from their seat. The reception desk is there for a reason. If it's not being manned properly then that's another issue.
Also yeah, those drugged up explosion ready man-children are going to pay attention to anyone outside their little fun lab. Most of them barely pay attention to people at their window, at least in my experience

**Comment by Birdtalon** [comment]
Chemistry is many times more likely to be manned than the reception desk as Chemists are doing their normal jobs. I agree, considering Medbay isn't exactly "high security".

**Comment by SamHPurp** [comment]
You shouldn't be letting people into Medical unaccompanied anyway, thats the whole point of having an access restriction.

If Chemists want to let them in, they need to be dealing with them once they are in medbay, which then makes the button useless.

My two pence.

**Comment by granodd** [comment]
I'm more to the kind of keeping the reinforced walls on the east side of chemistry for the sake of security. Of all the places in medbay that people should not be, chemistry is at the top of the list, and reinforced windows are objectively less secure than reinforced walls. Sure someone can break in through their desk already, but there's a windoor and a reinforced table in the way; the former not so easily disassembled by tools nor easily broken by "unga bunga, me want chems", and the latter also not so easy to disassemble while also needing to be climbed over, which takes time. Keeping the east side of chemistry as it is is preferred, and if they were to get a button to let people in, they would easily be able to tell if someone was wanting in from their lab anyways. People have a habit of spamming the button to get in, and most of medbay is visible from their desk anyways. Though I'm in agreement of the previous statement about the reception desk and it not being manned, as neat as a chem access door button would be.

**Comment by taukausanake** [comment]
Yeah, having windows there instead of the walls is a security risk. The extra visibility would be nice though, I'd think one window next to the windoor would be a compromise. Maybe keep a reinforced table under it too but I don't know

**Comment by owenowen212** [comment]
If security is an issue, I can add shutters or electrify the grilles within the windows if this is something people want. Re. @SamHPurp if button pressing leads to people not being attended into medbay, then it begs the question why we have these buttons in the first place. As a previous user has already mentioned, medbay isn't considered a high-security area and I simply see adding this button as a matter of convenience for people who may be bringing in someone in severe crit, for instance, and otherwise would have to tarry in the lobby waiting for someone to let them in.

**Comment by taukausanake** [comment]
It becomes a security issue when cryo and genetics turns into a gaping hole into space. That's normally the first area bombed in Medbay aside from Chemistry itself. As for electrifying Chemistry that might be a little bit of overkill. Maybe

**Comment by SamHPurp** [comment]
I do agree with the issue you have identified: Medbay lobby not always being attended, to allow a healthy patient flow.

I don't think I agree with your proposed solution however, the major reasons I stated above.

This might not be the right solution either, but how about a desk bell (http://www.clipartkid.com/images/40/desk-bell-clip-art-front-desk-bell-blank-W9Vx3X-clipart.jpg) that pressing it, pings all PDAs that have the Medbay cartridge... or it says something over Medical comms?

**Comment by taukausanake** [comment]
Actually now that I think about it, shutters for Chemistry could be a welcome buff to Chem antags unless others think it's too much. A full wall of glass like that though is still not safe, maybe one or two walls to windows going down from the windoor.
The desk bell would be nice but it'll have to ping all the PDAs with medical cartridges in them so as to not bother anyone who transfers out of Medical. Also give it a cooldown unless you want it to be spamable (if not for the in-person ringing then at least for the PDA notifications). Also make it a text prompt and not something in the PDA itself, as well as maybe toggleable.

Was it you Sam who suggested this in a previous PR? I forget

**Comment by SamHPurp** [comment]
@taukausanake It was... I'm up for doing it, but I haven't the freetime currently.

**Comment by Crazylemon64** [comment]
Rwindows are laughably less secure than rwalls. This lets you break into medchem in ~3 seconds flat if you have a set of tools that any greytider can get their mitts on (crowbar, screwdriver, wrench).

**Comment by FalseIncarnate** [comment]
For those mentioning the desk bell, I'd like to point out the intercom on the reception desk (the one at the windoor facing the main hall) is tuned to JUST the medical channel. Turning that intercom's microphone on will allow people to yell for aid in the lobby to everyone listening to the medical channel (aka: hopefully everyone in medical, plus captain and ai) for help.

A medibot in the lobby (common sight) also will announce when it finds a critical patient over medical comms, including the patient's name and the name of the area they are in ("Baldie McBlackeye is in critical condition in Medical Reception!"), so they also act as a sort of pager system.

As for the chemist having that button, I like the idea of the chemist being able to help the doctors if they are running on a skeleton crew, but think the chemist should leave their fortress in that case to ACTUALLY HELP the patient, rather than press a button and hope that the person doesn't just wreck up the place unattended. The windows are a big drop in security of the lab, which I both like and dislike. Maybe change a few of them back to walls, so there is a mix of windows (for visibility) and walls (for security). Shutters would be a stupid idea, because it would fortify the lab even more since it is WAY harder to get through a closed shutter than a wall.

**Comment by Vivalas** [comment]
The idea of chemists having a button to open medbay because they're too lazy to walk and open it kinda seems LRP to me. If no doctors are available don't open the door or get up and help them yourself. 

If we're at the point where people running in and speed-cheming themselves or auto-crying rather than having to wait a few extra minutes to interact with another player, then that speaks wonders of our medical system.

**Comment by Crazylemon64** [comment]
This guts the security of medchem. Closing.

**Pull request closed without merging**
