### PR TITLE
Removes Non-Human Species as Character Options

### PR DESCRIPTION
**Pull request by TheDZD**
Got you to look didn't I?
@Fox-McCloud

### CODE REVIEW

**Comment by Yukiona** [comment]
very funny!

**Comment by scrubmcnoob** [comment]
dank meme bro

**Comment by Spacemanspark** [comment]
I knew it would be changelogs.

**Comment by LittleBigKid2000** [comment]
Bamboozled again

**Comment by Crazylemon64** [comment]
For a moment I thought goofball went through with his claim

**Pull request merged**
