### PR TITLE
Brig Bugfix/tweak PR

### LINKED ISSUE #5136: Brig cells wiring
**Problem Description**:
What is the problem?
The brig cellblocks both don't have APC connected to mains power, and they run out pretty quickly.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Power goes out and cells won't hold prisoners.

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Because apparently a 10th commit was necessary to fix all of the issues. Damn it.
- Fixes #5136 
img

- Replaces bugged "lattices" in space with grilles, 

before: 
img

after:
img
- Fixed spooky dark corner:

before:
img

after:
img
- Adds windows to Processing entrance

img

- Fixes mystical evidence locker pen

img

- Re-adds the two missing lockers in Armory

img

- Adds missing basketball ( :clap: ) to basketball court

img

- @Bigtimetripod Fixes wrong cobwebs

img

Post any others you find

:cl: FreeStylaLT
fix: Fixed brig cell block APCs not getting power
fix: Fixed space buggery Kyet made :angry:
fix: Fixed missing light near labor shuttle dock
fix: Fixed wrongly placed cobweb in solitary
fix: Fixed basketball court not having a basketball
add: Added windows to brig processing entrance
add: Re-added the missing EOD and biohazard lockers in Armory
del: 6 gas masks from Armory
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
apparently you forgot to set the id on flashes and the timers.

**Comment by FreeStylaLT** [comment]
@Fox-McCloud conflict fixed

**Comment by FreeStylaLT** [comment]
windows are a feature :-1: :-1: :angry:

**Comment by Plotron** [comment]
I heard some people noticed that there's no EOD/Biohazard lockers in armory anymore.
Haven't checked that personally, maybe it got fixed somewhere along the way, I don't know.

Just putting it out there.

**Comment by FreeStylaLT** [comment]
@Plotron Those were removed during the original Brig PR when I was shrinking the secure hallway.

Neither of those lockers had an actual use (Biohazard suits don't do anything but protect from facehuggers, and if your situation required a bomb suit one really wouldn't help you given how bombs work) and I never saw them actually BE used, like, worn even for giggles. I had no room to put them elsewhere, so I just removed them.

**Comment by Fox-McCloud** [comment]
@FreeStylaLT 

You should have documented their removal, because bombs suits absolutely do have function. They reduce damage from miner's kinetic accelerators and do reduce bomb damage, not to mention that if you're diffusing a bomb and it blows up in your face, you won't be out and out gibbed from it, meanig it's far easier to recover you.

And the biosuits have armor on them, so it's not JUST about protecting facehuggers, it's doing so in addition to having a bit extra safety.

**Comment by Bigtimetripod** [comment]
MY EYES! 

http://i.imgur.com/2JPs3J1.png

**Comment by Belario** [comment]
I don't think I've seen the bomb/bio suits used, ever.
Science use their's all the time but sec? not once.

I don't see why they couldn't be squeezed into the equipment room though, those two tables are a bit redundant thanks to the racks.

**Comment by FreeStylaLT** [comment]
and Kyet forgot to include a basketball in the basketball court. :clap:

I'll be adding the lockers back, then, I think I found a spot. At the expense of two racks and six gas masks. Seriously Warden's Office/Armory are crrrrramped.

Will also be fixing the web.

**Comment by FreeStylaLT** [comment]
OP Updated.

**Pull request merged**
