### PR TITLE
Updates Custom Borg Sprites

### PR DESCRIPTION
**Pull request by shazbot194**
## What Does This PR Do

This PR has changed slightly from just updates a set of old sprites, and now is also removing potentially infringing sprites while also adding in sprites that are much more modern sprite standards while not touching anything else.

## Why It's Good For The Game

This PR now does two major things. It removes any possible issues that the old designs might have due to copyright issues. It also adds in sprites that are more modern without touching anything else. The latter helping to move the progress of having more modern sprites in accordance with the long-term goal of updating sprite standards, even if this PR is very limited in scope.

## Images of changes

cover_open_full

Removed modules are included as they haven't been deleted from the code nor sprite bank.

## Changelog
None

### CODE REVIEW

**Review by SteelSlayer — APPROVED** [review]

**Comment by FlattestGuitar** [comment]
The changelog is unnecessary. This does not impact players.

**Comment by shazbot194** [comment]
Fair enough, removing

**Comment by AffectedArc07** [comment]
Could you remove the empty CL blocks entirely? I dont know how the system handles it, if at all

**Comment by shazbot194** [comment]
Oh, forgot to mention it, but I did remove the CL block

**Comment by Necaladun** [comment]
lgtm

**Comment by Shadeykins** [comment]
Assets, if merged, should be CC-BY-NC-SA 3.0.

The originating artist that the designs are based on has indicated that they are to be used non-commercially.

**Comment by shazbot194** [comment]
If that is an issue, I have a second set of borg sprites not based on any active works that should be much more agreeable.

**Comment by shazbot194** [comment]
Still waiting to see if I need to swap the sprites to the new set.

**Comment by Necaladun** [comment]
Second set look fine to me now, LGTM 👍

**Comment by DoctorDrugs** [comment]
Sprites remind me a bit of DOOM marines and of the HECK suit but look good to me. 👍

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
