### PR TITLE
Pineapple Pizzas

### PR DESCRIPTION
**Pull request by Birdtalon**
Adds Pineapples and derivatives. Can be sliced and placed on pizza of course.

- Pineapple seeds added to botany.
- Pineapple can be sliced, juiced and ground.
- Sliced pineapple can be made into a hawaiian pizza.
- Adds hawaiian pizza to the pizza crate.
dreamseeker_2017-08-26_22-43-00

Pineapple sprites by Hylocereus:

dreamseeker_2017-08-26_22-28-55 dreamseeker_2017-08-26_22-34-30
dreamseeker_2017-08-26_22-35-49

🆑 Birdtalon & Hylocereus
add: Adds pineapples which can be grown in hydroponics, juiced or sliced and made into hawaiian pizza.
tweak: Adds hawaiian pizza to the pizza crate.
/🆑

### CODE REVIEW

**Comment by HereticChurch** [comment]
Absolutely amazing. As a note, Hawaiian Pizza generally also has ham on it, if memory serves. Might want to tweak the recipe/reagents. Unless I'm totally wrong and just eat weird Hawaiian pizza.

**Comment by tinfoiltophat** [comment]
good meme

**Comment by Spacemanspark** [comment]
What Heretic said, Hawaiian pizza has ham on it.
I've had to make it before.
It's nasty.

**Comment by Birdtalon** [comment]
@HereticChurch it does have ham.

The recipe is

- Flat Dough
- Tomato
- Cheese Wedge
- 2 Pineapple Slices
- Any meat

I could make it Ham only but any meat is a bit easier, what do you think?

**Comment by HereticChurch** [comment]
Oh, totally missed the meat in the ingredients list. The item itself lacks protein as a reagent though from the meat.

**Comment by Birdtalon** [comment]
That's true actually I missed that. I'll add it now.

**Comment by tigercat2000** [comment]
Fucking delicious.

**Comment by MarcellusPye** [comment]
😱

**Comment by LightFire53** [comment]
Only pizza? What about cake?

**Comment by Jovaniph** [comment]
You mad man.

**Comment by scrubmcnoob** [comment]
it should contain 1000 units of cyanide

**Comment by FalseIncarnate** [comment]
If you make a food recipe, it inherits reagents from the ingredients. So a chef-made hawaiian pizza would get protein from the meat ingredient. The cargo-supplied pizzas, however, would only use the reagents of the base food item, so adding the protein is fine.

Also, pineapple pizza is delicious.

We'll additionally need to make some new drink recipes to use pineapple juice, though that's not urgent.

**Comment by KingPhilipIII** [comment]
Ugh. Pineapple does not belong on pizza.

I do like the PR however.

**Comment by Fullofskittles** [comment]
One little thing that I wanna point out is that all of the sprites except for the pizza itself look a little blurry/anti-aliased. It's not as noticeable on the slices or plant itself but the harvested whole pineapple seems to have a lot more of it going on. It might be worth refining that one to have a crisper outline?

**Comment by taukausanake** [comment]
I am partly on @Fullofskittles side for the sprite but also think they look damn sexy. I think the pineapple food object could go for some more detail, not so much the others except maybe the slices.

Love pineapple on pizza, but only with pepperoni

**Comment by Jovaniph** [comment]
If this gets merged, then you can't argue with me that a hotdog is not a sandwich cuz it is.

**Comment by tinfoiltophat** [comment]
a pizza is a sandwich too

**Comment by Rumiluntti** [comment]
Replace pizza bombs with these

**Comment by Spacemanspark** [comment]
Pineapple pizza even SMELLS bad yo

**Pull request merged**
