### PR TITLE
Fixes #20816, missing vox helmet frame.

### LINKED ISSUE #20816: Missing west facing sprite on Judge helmet on Vox
Missing west facing sprite on the Judge helmet for voxes
The west facing sprite for the Judge helmet is missing for voxes

I expected all the sprites to exist.
Bugs are bad

West facing sprite was not there.
I expected all the sprites to show, on all sides.

Bugs are bad
Bugs are bad

Be a Vox, equip Judge helmet from SecDrobe vendor, face character to West.

Noticed the bug now, when playing Vox

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Fixes #20816 

GOD DAMNIT GDN, HOW DID YOU NOT NOTICE THIS.
## Why It's Good For The Game

Fixes #20816 

## Images of changes

image

## Testing

It just works

## Changelog
:cl: ATP Engineer
fix: Judge's Helmet on vox now has a left frame
/:cl:

### CODE REVIEW

**Comment by ATP-Engineer** [comment]
FIX IT FIX IT FIX IT FIX IT FIX IT FIX IT FIX IT!

**Comment by Henri215** [comment]
fix: Fixed judge helmet sprite on Vox

Use this on your changelog.

**Comment by Contrabang** [comment]
Would you mind changing your changelog to reflect what is fixed and not the issue? The changelog in game won't be a link to click to the issue. Something like
```
fix: Judge's Helmet on vox now has a left frame
```

**Comment by ATP-Engineer** [comment]
> Would you mind changing your changelog to reflect what is fixed and not the issue? The changelog in game won't be a link to click to the issue. Something like
> 
> ```
> fix: Judge's Helmet on vox now has a left frame
> ```

Done

**Review by hal9000PR — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
