### PR TITLE
Wires no longer gets destroyed by tesla

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

Stops tesla zaps from destroying wires

## Why It's Good For The Game

Wires won't be broken, and the tesla won't get loose as often as it has been.

## Changelog
:cl: ppi
tweak: The tesla will no longer destroy wires
/:cl:

### CODE REVIEW

**Comment by ManiacalSymphony** [comment]
But but, if the tesla doesn't get loose, what else am I gonna complain about

**Comment by ZanderDoggo** [comment]
I would like this, I personally enjoy making 1x1 teslas and the update done to it has made trying to do so extremely boring and a pain to actually make teslas anymore. I think that doing this will make teslas a viable option for engines again. P.S. Teslas are fun and removing the functionality to make complicated setups is boring

**Review by AffectedArc07 — APPROVED** [review]

**Comment by meow20** [comment]
I thought yesterday the tesla destroyed wires because the grounding rods were too far, is that not the case?

**Comment by ppi13** [comment]
kinda, but wires are not supposed to be destroyed by tesla, it's what caused nearly every single tesla release in the past couple of months.

**Pull request merged**
