### PR TITLE
Makes the area leading up to the engi escape pod a maintenance area proper (Boxstation)

### PR DESCRIPTION
**Pull request by Citinited**
**What does this PR do:**
Makes the area between engineering and atmos an actual maintenance area, with an APC. I changed this because it looks like maintenance but isn't. This also has the effect of protecting the engineering escape pod from radstorms, which is a good change IMO.

**Obligatory pics!**

Before:
image 

After:
image

:cl:
tweak: The small "maintenance" area between engineering and atmospherics is now a maintenance area, and has its own APC now.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Nice. No knock-off maint.

**Comment by Spartan6** [comment]
Screenshots needed.

**Comment by Citinited** [comment]
Oh right, gimme a few minutes

**Comment by Spartan6** [comment]
That should be fine, but I would recommend that now this has become a maintenance, you should replace the external airlock doors with normal maintenance doors and rename them appropriately, apart from the tube station and airlock of course.

**Pull request merged**
