### PR TITLE
Updates Food and Candy Sprites

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates some candy and food sprites---credit to Full of Skittles.

Sprites updated: jellybeans, gummy worms, gummy bears, toffee, and bacon sprites.

Also fixes telebacon

:cl: Fox McCloud and FullOfSkittles
tweak: Tweaks the gummy worm, gummy bear, jeallybean, toffee, and bacon sprites
fix: Fixes telebacon not properly acting as...well, a bacon beacon
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
> sprite update
> no pics
😠

**Comment by Fox-McCloud** [comment]
Use the icon dif you nerd.

**Comment by KasparoVy** [comment]
A bacon beacon LMAO

**Comment by taukausanake** [comment]
> Use the icon dif you nerd.

You made that "Need pics" tag specifically because I forgot pics, the least you could do is suffer as I did.
But I guess if sprite edits then it doesn't matter as much. I know how to use IconDiff after all

**Pull request merged**
