### PR TITLE
Interface cleanup

### PR DESCRIPTION
**Pull request by Crazylemon64**
Removes a lot of default entries from the interface file, and also finally gets rid of the IDE and chem-master interface definitions in there.

### CODE REVIEW

**Comment by LittleBigKid2000** [comment]
Removing the telecomms IDE = No more hot butt scripts

**Comment by tigercat2000** [comment]
@LittleBigKid2000 
>Removing the telecomms IDE = No more hot butt scripts

nah
the interface.dmf element for telecomms was the old UI
it uses the datum browser now

**Comment by LittleBigKid2000** [comment]
@tigercat2000 
(I'm making a joke about my butt-obsessed IPC named I.D.E.)

**Comment by tigercat2000** [comment]
oh

**Comment by Lady-Luck** [comment]
>(I'm making a joke about my butt-obsessed IPC named I.D.E.)

https://niceme.me/

**Pull request merged**
