### PR TITLE
Adds two requests consoles to the kitchen on Cerestation/Farragus

### LINKED ISSUE #21797: cerestation kitchen missing request console
**Issue Description**: Like it says on the tin.

**What did you expect to happen**: All other maps have a req console just for kitchen, not bar or botany, so I expect the same here.

**What happened instead**: No console.

**Why is this bad/What are the consequences**: Map consistency is good.

### PR DESCRIPTION
**Pull request by 1080pCat**
## What Does This PR Do

Title. closes  #21797
## Why It's Good For The Game

They lacked request consoles, they should have request consoles.
## Images of changes

Before
image

After
image

## Testing

Compiled, checked if they existed.
## Changelog
:cl:
add: Added two request consoles to the kitchen on Cerestation/Farragus
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
The cart wont block him from using the console, right?

**Comment by 1080pCat** [comment]
> The cart wont block him from using the console, right?

Does not block it, no.

**Comment by 1080pCat** [comment]
me when wrong branch D:

**Comment by 1080pCat** [comment]
gonna fix this at a later date.. darned it all

**Pull request closed without merging**
