### PR TITLE
Adds the oxygen grenade

### PR DESCRIPTION
**Pull request by datlo**
This PR adds two oxygen grenades to atmospherics lockers (6 in total) and 2 to the emergency equipment cargo crate.

oxygengrenade

The oxygen grenades releases pure oxygen to the atmosphere when detonated. It contains enough oxygen to make a depressurised room of ~20 tiles breathable, although it'll still be too low in pressure for people without spacesuits to stay in.

Note that this does not release an air mix but pure oxygen, it is meant to be used in emergency situations where people can't breath, NOT to fix the air after a breach.

~~Or you could just throw it at a plasmafire to add fuel to it~~

🆑
add: Added emergency oxygen grenades to atmospherics lockers and the cargo emergency equipment crate.
/🆑

### CODE REVIEW

**Comment by TDSSS** [comment]
I kind of feel like this kind of grenade/chemical reaction should be craftable in general. Maybe a new chem that reacts with oxygen in a grenade to make oxygen gas? But that's more a side note,good idea! Does it generate dangerous overpressure or spacewind if used in an already pressurized room?

**Comment by datlo** [comment]
It adds 500 kPa worth of oxygen to the tile it's on that then spreads to other nearby tiles (because that's how gas work), so yes, it'll overpressurize already pressurized rooms, but not by much unless it's a very small room.

**Comment by datlo** [comment]
Also, to the idea of custom gas grenades, the grenades would either hold too little gas to bother with or be horribly unbalanced unless they're a traitor item. And you can already get atmos clustergrenades as a traitor. So I don't think it's necessary.

**Comment by Ralta** [comment]
I like. 

Any chance of adding a crate to cargo? 6 really should be plenty for _most_ shifts, but a billion breaches isn't especially uncommon, and might be nice to have a way of obtaining more.

Or alternatively, adding a generic Atmos crate that includes a couple of these, a couple of metal foam grenades and some other basic 'Breach Kit' stuff? Might be beyond the scope of this PR, though...

**Comment by datlo** [comment]
This is actually added to the emergency equipment cargo crate, I didn't want to make a new crate when there's already something that fits. To be fair it is a pretty expensive crate and atmos could use a crate of their own.. I'll think about it.

**Comment by Ralta** [comment]
> This is actually added to the emergency equipment cargo crate, I didn't want to make a new crate when there's already something that fits. To be fair it is a pretty expensive crate and atmos could use a crate of their own.. I'll think about it.

ACK! Sorry, I completely missed the bit about it being added to the emergency equipment crate. That's totally fine then, good stuff :+1:

**Comment by FreeStylaLT** [comment]
excellent for fire.. _suppression_ :eyes:

**Comment by Agameofscones** [comment]
Nitrogen grenades would actually be great for proper plasma fire suppression, if you made that a variant I'm sure the atmos ~wizards~ mains would appreciate it.

**Comment by taukausanake** [comment]
I bet you anything Vox would abuse the hell out of nitrogen grenades

**Comment by datlo** [comment]
i'll think about N2 nades for another PR

**Pull request merged**
