### PR TITLE
Decemviri's fluff hardsuit modkit

### PR DESCRIPTION
**Pull request by FlattestGuitar**
character name: `Sylus Cain`
ckey: `Decemviri`

qlkzric2co

The gif shows the helmet shifted one pixel to the right when facing the camera. This has been amended, but I cannot be bothered to compile it again.

### CODE REVIEW

**Comment by Decemviri1** [comment]
💃

**Comment by Spartan6** [comment]
Everyone copying VoxxyHUD SKREEEE

**Comment by KasparoVy** [comment]
The subtle difference being the scanline doesn't bounce back and forth, just goes one way and repeats 👽

**Comment by taukausanake** [comment]
8/10 not enough yip

**Pull request merged**
