### PR TITLE
Added an arcade machine to the syndie space base

### PR DESCRIPTION
**Pull request by Pyrodes**
## What Does This PR Do
Adds an arcade machine to the syndie space base, above the window in the library.

## Why It's Good For The Game
It can help deal with boredom as a researcher in the base, plus provide one more thing to do in there.

## Images of changes
https://cdn.discordapp.com/attachments/759088045848395827/857201785114460180/syndie_space_arcade.png

## Changelog
:cl:
add: Added an arcade to the syndie space base
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
Good first PR. Looks fine map-wise to you, it's nice to see a small diff for once with a map change!

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — APPROVED** [review]
Could you please replace a bookshelf with it instead? The way the sprite looks, it looks like its facing right into solid glass.

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
image
Echoing kyet. Please put this somewhere where the sprite aligns better.

**Comment by Pyrodes** [comment]
Should I switch the arcade around with the bookshelf north of it? I think that would be ideal but it would probably make the window south of it pointless.

**Comment by S34NW** [comment]
I think the consensus is to just remove a bookshelf and pop the arcade in its place.

**Comment by AffectedArc07** [comment]
Please resolve merge conflicts

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
