### PR TITLE
Removes Tigercat from the list of current maintainers

### PR DESCRIPTION
**Pull request by Crazylemon64**
This file wasn't updated when tigercat stepped down, so I'm fixing that now.

### CODE REVIEW

**Comment by RyanSmake** [comment]
Do I see webeditor?

**Comment by Crazylemon64** [comment]
yeah but none of this is compiled and it's a single line change so who cares

**Comment by RyanSmake** [comment]
Maintainers doing edits with the webeditor! **These are truly the end times!**

**Comment by Spartan6** [comment]
Beginning of the end.

**Comment by Citinited** [comment]
Uh oh 

image

**Comment by SamHPurp** [comment]
RIP

**Pull request merged**
