### PR TITLE
Uses more intent defines

### PR DESCRIPTION
**Pull request by SamHPurp**
Just updating/standardising something thats often inconsistent in old code

The codebase now uses intent defines consistently, as well as adding movement defines. The Intent defines have been renamed for additional clarity

`INTENT_HELP` - over `I_HELP`
`INTENT_DISARM` - over `I_DISARM`
`INTENT_GRAB` - over `I_GRAB`
`INTENT_HARM` - over `I_HARM`

`MOVE_INTENT_WALK`
`MOVE_INTENT_RUN`

Backoffice stuff, no changelog.

### CODE REVIEW

**Comment by deep-fried-faceplant** [comment]
So this just changes a bunch of constants into defines? I'm still learning DM, but from what I can tell defines just take up less memory, right?

**Comment by Tayyyyyyy** [comment]
Not really, the defines are just defined as the string, so the compiler would just replace the define with the string itself. But it's better style and less error prone, since you'd get a compile error if you wrote an intent that didn't exist, whereas with a string you'd only figure out at runtime that you put in the wrong thing.

**Comment by SamHPurp** [comment]
@deep-fried-faceplant 'fraid not. Its more for readability, and as @Tayyyyyyy mentioned, it can be useful for catching errors.

A define is something replaced during compile

So...

`sum = 40 + 2`

is the same as

`#define FORTY 40`
`sum =  FORTY + 2`

**Comment by deep-fried-faceplant** [comment]
So it's sort of like enum in c++, only you can use strings too?

**Comment by Tayyyyyyy** [comment]
[C++ has defines too](https://gcc.gnu.org/onlinedocs/cpp/Undefining-and-Redefining-Macros.html#Undefining-and-Redefining-Macros). They're just part of a fancier macro system. I'm pretty sure defines in DM are only for constants.

**Comment by Fox-McCloud** [comment]
Might I suggest using TG's intent defines, for consistency between us? It's also more clear when it's `INTENT_HELP` as opposed to `I_HELP`. It's an intent, not a pancake restaurant or rejected Apple product.

Same for "walk" and "run"; these are intents that should probably be set, as well; again to the same defines TG has.

**Comment by SamHPurp** [comment]
@Fox-McCloud I simply used what was already in use.

I'll update this and the rest of the codebase. Leave this PR for the moment.

**Comment by Fox-McCloud** [comment]
Yeah, I know you are; I'm just putting in a request since you're already changing a lot.

**Comment by SamHPurp** [comment]
@Fox-McCloud Yep thats fine, and I agree with you. I'll get it done.

**Comment by SamHPurp** [comment]
@Fox-McCloud This is now done.

**Pull request merged**
