### PR TITLE
More bitflag cleanup

### PR DESCRIPTION
**Pull request by FunnyMan3595**
## What Does This PR Do
This is a follow-on PR to #24179, since I'd accidentally re-implemented it, and the changes didn't quite match.

* Caught a few more bitflags that weren't converted to `(1<<x)` notation.
* Deleted comment from `code/__DEFINES/admin_defines.dm` that seems to be stale, since it isn't reflected in the defines. Added another comment to help prevent the defines from desyncing.
* Unlabeled a non-bitflag in `code/__DEFINES/clothing_defines.dm` as a bitflag in its comment.
* Added comment to `code/__DEFINES/misc_defines.dm` to explain the -2.
* Added some parentheses around a few `(BIT | FLAG | COMBINATIONS)`.
* Made some bitflag whitespace more consistently pure tabs for aligning the values. Did a couple non-bitflags by accident, too, but it's an improvement, so I'll let it stick.

## Why It's Good For The Game
Code consistency is good.

## Testing
Compiles and runs OK.

## Changelog
NPFC

### CODE REVIEW

**Comment by Oyu07** [comment]
Seems duplicate of https://github.com/ParadiseSS13/Paradise/pull/24179 ?

**Comment by FunnyMan3595** [comment]
Yeah, but I'll leave it since this one is up-to-date, and that one's merge conflicted (and has been for weeks)

**Comment by FunnyMan3595** [comment]
I've updated the PR now that #24179 is in, since there were still some useful changes here.

**Review by Henri215 — APPROVED** [review]
Lewcs good to me

**Review by S34NW — APPROVED** [review]

**Pull request merged**
