### PR TITLE
Removes Cloning

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
 Removes cloning pods from the three main stations, the corresponding boards are now restricted to level 8 biotech. Adds a new item: "Salt of the damned" which is just a salt shaker.
(to be clear, this is a shitpost I made in like under an hour. Do not actually merge this)

## Why It's Good For The Game
 Its not, its really not. But I think it would be interesting to experiment what our server would adapt to no cloning. See screenshot.
image

## Images of changes

image
image
image

## Testing

It compiles, cloning is gone.

## Changelog
:cl:
experiment: Someone messed up and merged a shitpost
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
BA17D9DD-D4AE-480C-BD29-6A03B1722D18

**Comment by procdrone** [comment]
10862 is clearly a better alternative

**Comment by GDNgit** [comment]
👎 from me until we go the whole mile and just remove revival itself
*WHY WON'T YOU DIEEEEE*

**Comment by Henri215** [comment]
👎 from me until more salt is added.

**Comment by FloFluoro** [comment]
I don't think this is worth TMing even as a joke.

When cloning was removed from /tg/, they already:

* Had removed the defib timer, the thing that makes bodies permanently unrevivable after 5 minutes
* Had coronary bypass surgery for revitalizing decayed hearts
* Had revival surgery

We have none of that. I don't think a TM is required to figure out what would happen if SR became the only way of reviving corpses after the 5 minute mark; in a best-case scenario, medchem becomes a SR factory because this One Magical Pill is now the sole method of resuscitation available for late medbay arrivals. In a worst case scenario, medchem is incompetent and the morgue is filled with green trays.

**Comment by roarbark** [comment]
> I don't think this is worth TMing even as a joke.
> 
> When cloning was removed from /tg/, they already:
> 
> * Had removed the defib timer, the thing that makes bodies permanently unrevivable after 5 minutes
> * Had coronary bypass surgery for revitalizing decayed hearts
> * Had revival surgery
> 
> We have none of that. I don't think a TM is required to figure out what would happen if SR became the only way of reviving corpses after the 5 minute mark; in a best-case scenario, medchem becomes a SR factory because this One Magical Pill is now the sole method of resuscitation available for late medbay arrivals. In a worst-case scenario, medchem is incompetent and the morgue is filled with green trays.

people sometimes dying is an intended side effect. the issue this is supposed to touch on is that people dont really value their life in game at all, and rulewise we dont really allow antags to permakill all valid hunters etc., pp., and so on and so forth. 

players are actually supposed to think twice before charging an antagonist. "my character might actually die from this and wont come back"

also people in tg are much more fragile and become helpless much quicker there, our spacemen get a bunch of time to crawl away from something like a workplace accident, while being able to jab an odd epipen even at -60 health, for example.

**Comment by FloFluoro** [comment]
>rulewise we dont really allow antags to permakill all valid hunters etc., pp., and so on and so forth.

Rules don't have much to do with the reality that whatever the antag might've intended, it's very common for bodies to either be found 5+ minutes after death, or for medbay to fumble the bag past the 5+ minute threshold.

Also, as mentioned above removing cloning =/= "death is permanent"; it'll gate all late resuscitation through a single chem, strange reagent.

Medchem already has issues with people flowcharting the shit out of chem production at the expense of newbies who want to learn organically, I'd rather not have the **only means of late resuscitation** be gated behind medchem. I don't want "chemist is bald so i broke in and pushed him aside to make sr" to be a thing.

**Comment by Contrabang** [comment]
> 👎 from me until more salt is added.

salt added
image


> I don't think this is worth TMing even as a joke.
>  ...

I want to see if this hypothesis is true or not, this is now the scientific method

**Comment by meow20** [comment]
Hell yeah TM it

**Comment by AffectedArc07** [comment]
This isn't the kind of PR you should throw up randomly, **especially** not without a detailed discussion thread first. Posting an offhand discord screenshot is not instant justification for something this impactful. 

A **LOT** of work needs to be done around this, and many, many things need to be considered, just throwing the cloner out the window isn't going to fix it, as it will just make medical unplayable when there are terrors or a massive blob or similar.

--

> > 👎 from me until more salt is added.
> 
> salt added image
> 
> > I don't think this is worth TMing even as a joke.
> > ...
> 
> I want to see if this hypothesis is true or not, this is now the scientific method

This is also a **really** bad attitude to have here. Instantaneous objection from me. 


Oh, and since this is likely going to be the most controversial thing thrown on the git. I am not going to hesitate locking this the moment it gets toxic.

**Comment by AffectedArc07** [comment]
If you want to make a PR where you intend for actual results, plan it properly, write documents, actually consult people.

If you want to make shitpost PRs, stop wasting our time.

**Pull request closed without merging**
