### PR TITLE
Movable Telecomms White Ship

### PR DESCRIPTION
**Pull request by tigercat2000**
Inspired by -tg-, noticed it on tgstation/-tg-station#9467.
No actual code is taken from them, though.

This PR makes the large white telecomms ship into an actual shuttle, able to be piloted, provided that you can find the circuit board. 

It has three destinations:
Telecomms, where it starts
Next to permabrig.
Next to the engi station.

at the station
at engipost
![screenshot of circuit loc- wait, no, NO SPOILERS. Find it. 

### WHY!?, you ask?
Because, it's a new challenge for space, and I always thought that the white ship should have been a real shuttle. 
Who doesn't want to show up and show off to the captain, afterall?

oh, and the console will not work if you try to build it on-station, because that would BREAK THINGS!

### CODE REVIEW

**Comment by Mijhead** [comment]
:+1:

**Comment by fj45** [comment]
Very fun feature.

**Comment by Spacemanspark** [comment]
Yes please.
:+1:

**Comment by Robertha89** [comment]
... oh my god yes plz

**Comment by Finalsong** [comment]
Da

**Comment by Bad-Apple797** [comment]
Are we able to build on the floors of this ship?
 If not, can we add more regular floors so we can deck it out?

**Comment by Spacemanspark** [comment]
Does it use hyperspace to travel, or does it travel instantly? It'd be pretty neat if it used hyperspace.
We should do that with the mining/ research/ engineering outpost shuttles too, like /tg/...

**Comment by tigercat2000** [comment]
@Bad-Apple797 Yes you can build on the floors
@Spacemanspark It takes 2 minutes to travel between places with it, and yes it goes through the hyperspace like the emergency shuttle. (sidenote; centcomm Z cannot hold many more shuttle hyperspaces)

**Comment by Spacemanspark** [comment]
Hell ya.

**Comment by FalseIncarnate** [comment]
@tigercat2000 

I personally want to recommend putting the white ship onto the centcomm z-level for it's transit, given that you could in theory jump off mid-transit and get to centcomm or the admin station and hack your way into the armory rooms, unless there is some safeguard in place with a transition around the hyperspace sections.

Perhaps we should put hyperspaces onto a separate z-level if possible, so that we A: have more room for additional transit spots, and B: avoid potentially making centcomm level areas accessible to players.

**Comment by tigercat2000** [comment]
@FalseIncarnate The whole area is surrounded with teleporters that teleport you somewhere random in-bounds, and if you step outside of the ship, you get tossed at high speed towards them. In theory if you managed to break /turf/Entered(), you could get past them, but it's very unlikely.

**Comment by FalseIncarnate** [comment]
Alright, if there are measures in place to prevent people from jumping out the door and floating to the admin room or centcomm, I'm fine with that.

Though the suggestion for a "hyperspace" z-level to allow for more room still stands.

**Comment by tigercat2000** [comment]
I agree with that, if we ever want to add more shuttles, centcomm is getting full.

**Comment by Fox-McCloud** [comment]
Seems alright.

**Comment by M3hillus** [comment]
@tigercat2000  @FalseIncarnate  Didn't we just add a new Z-Level for the cubemap thing with #1012 ?

**Comment by FalseIncarnate** [comment]
@M3hillus , that z-level is part of the space cube and is thus normally accessible through floating in space. A hyperspace level would be just for the shuttle transits and would be otherwise isolated to prevent accidental access.

**Comment by M3hillus** [comment]
@FalseIncarnate So if you follow that up and add another Z-Level....would the PR be called Space cube 2: HyperCube?

**Comment by TheDZD** [comment]
@M3hillus No, space cube requires exactly 6 accessible z-levels, since a cube has 6 sides. Anything more and you'd have to do some weird math for a 7-sided 3-D object, when you can only move off of a z-level in 4 directions (works perfectly for a cube). The hyperspace z-level will be inaccessible outside of shuttles travelling through it, and if somebody drops out of the shuttle, they get teleported to an accessible z-level.

**Comment by tigercat2000** [comment]
we have 6 player-acessable z-levels. 1, 3, 4, 5, 6, 7. Number 2 is used for centcomm, number 8 is used for syndie station.

**Comment by ZomgPonies** [comment]
Technically if we ever move the mining asteroid to an underwater research/mining compound, we can free up a 'space' z-level for new content.

**Comment by tigercat2000** [comment]
@ZomgPonies Actually Z7 is entirely empty already, had to add it with the space cube requiring 6 accessable levels

**Comment by Robertha89** [comment]
I miss old z-level travel, and to properly add more would be to revert to that, or create a hyperdimensional cube a 4d cube with 30 sides.

**Pull request merged**
