### PR TITLE
Xray Cameras is now malf only

### PR DESCRIPTION
**Pull request by Varghh**
## What Does This PR Do
Make cameras no longer able to be upgraded with just an analyzer to make them Xray, so we no longer have engineers, cargo techs, civilians or whatever that can get easy access to analyzer (plus they can be mass produced inside an autolathe) the power to just go around and making not only all cameras super powerful but also filling maints with xray cameras so AI can watch your every move.
Also, xray is busted, we all know this, it's not fun to try and play antag while Robocop is just screaming about your every location and calls for security to murder you on crewsimov.

## Why It's Good For The Game
Antags often get fucked by power hungry AIs and/or players who just spamcameras in maints and upgrade them to Xray just to make antags life hell, even on green alert.

## Images of changes

Poor CE can no longer upgrade the cameras

xray 2
xray cam 1

Malf AI can still do that
xray4
xray5

## KNOWN ISSUE
Malf AI camera upgrade don't make the cameras get Night vision like they should, i did not figure out how to fix that without breaking everything.

## Changelog
:cl:
del: You can no longer upgrade cameras to xray with just an Analyzer, Malf AIs still have the power to upgrade them and watch your every move.
/:cl:

### CODE REVIEW

**Comment by Varghh** [comment]
**Paradise/code/game/gamemodes/malfunction/Malf_Modules.dm**

`/datum/AI_Module/large/upgrade_cameras/upgrade(mob/living/silicon/ai/AI)
	AI.lighting_alpha = LIGHTING_PLANE_ALPHA_MOSTLY_INVISIBLE //Night-vision, without which X-ray would be very limited in power.
	AI.update_sight()
	var/upgraded_cameras = 0

	for(var/V in GLOB.cameranet.cameras)
		var/obj/machinery/camera/C = V
		if(C.assembly)
			var/upgraded = FALSE

			if(!C.isXRay())
				C.upgradeXRay()
				//Update what it can see.
				GLOB.cameranet.updateVisibility(C, 0)
				upgraded = TRUE

			if(!C.isEmpProof())
				C.upgradeEmpProof()
				upgraded = TRUE

			if(upgraded)
				upgraded_cameras++

	unlock_text = replacetext(unlock_text, "CAMSUPGRADED", "<b>[upgraded_cameras]</b>") //This works, since unlock text is called after upgrade()`

I was unable to figure out how to fix AI night vision.

**Comment by Muhdi345** [comment]
I'd still leave an expensive option for a xray camera. As long as it needs diamonds instead of just a pinch of metal and glass.
You don't want the AI to be found out just because someone watched a single camera from a console.

Heck, I'd make new cameras only attainable from cargo crates too since they're basically made from bluespace anyway, but what do I know. If they actually worked off an APC and power instead of magic and emagging an APC could disable them it wouldn't be so bad.

**Review by SteelSlayer — APPROVED** [review]

**Comment by PacifistDalek** [comment]
I'm all in favour of this, but i have a stupid question: what do analyzers do now? Like, their functionality as I understand it is duplicated by pda cartridges if i remember correctly. Is there any other camera buff that an analyzer could still give? Or something else an analyzer could do? Probably out of scope of this PR, just some thoughts :)

**Review by variableundefined — APPROVED** [review]
Approved

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
