### PR TITLE
Revert "Merge pull request #4739 from monster860/vg-parallax"

### PR DESCRIPTION
**Pull request by tigercat2000**
This reverts commit 451c93437905afd666d37c504e4e159a29c558e4, reversing
changes made to 64f26d999f4ce606d245c18e6001e5ecca8f36b1.

Conflicts:
	SQL/paradise_schema.sql
	SQL/paradise_schema_prefixed.sql

@TheDZD 
:cl:
rscdel: Removes space parallax, due to server overhead, input lag & bugs 
/:cl:

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
OH MY GOD.

IT'S FULL OF STARS.

**Comment by TheDZD** [comment]
Reasoning being:
- update_parallax has incredibly high overhead, and with approximately 90 players, its Self CPU was only topped by human update_icons.
- If there are no space turfs on screen, darkness becomes space.
- Causes noticeable input lag while turned on for many people.

**Comment by KasparoVy** [comment]
I think it looks amazing, but the input lag is hella cripping for many people.

**Comment by TullyBurnalot** [comment]
@KasparoVy As hilarious as it is, it looks incredibly silly, and should not be a thing.

**Pull request merged**
