### PR TITLE
Ports Elite Syndicate Hardsuit and Uplink Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over TG's elite syndicate hardsuit

- Nukies only
- +20 armor for most categories (+10 for energy)
- Fire immunity 
- 8 TC

Uplink Refactor
- Uplink game mode inclusion/exclusion is now based on game-mode *type* as opposed to game-mode name
 - I dunno why I didn't refactor this a long time ago; the fact that it's name is dangerous; a single typo and it will fail to work--worse yet, it will still compile and you won't notice until its too late.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Next you need to port the device that tells the crew the operatives are coming, but gives the operatives a shitload of items/ TC.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

I plan on it.

**Comment by Deanthelis** [comment]
Oh, handy. With these, the nukies can break into atmos and cause a horrible plasma fire, and be just fine. Maybe grab some magboots too, of course, and at least one emag.

**Comment by Plotron** [comment]
Does it have unique visuals?

**Pull request merged**
