### PR TITLE
Map fixes. Incinerator coated walls, and some plates under doors

### PR DESCRIPTION
**Pull request by GeneralChaos81**
PA room north door. Plating replaced by floor
Door between garden and tool storage. Plating replaced by floor
Incinerator. Burn room walls replaced with coated rwalls. #5529 

garden
incin
pa

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Going to create conflicts with @FreeStylaLT PR.

**Comment by GeneralChaos81** [comment]
Yep. Just saw that.

**Comment by FreeStylaLT** [comment]
The timing..

**Comment by GeneralChaos81** [comment]
Shh! Perception check failed.

**Comment by GeneralChaos81** [comment]
Can you fix those floors in your PR @FreeStylaLT ?

**Pull request closed without merging**
