### PR TITLE
Updates In-Game Links

### PR DESCRIPTION
**Pull request by Fox-McCloud**
In-Game links need to be updated to coincide with new URL.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Should we just centralize all URLs to some variable/constant so that when we wanna change the base host it's just 2 seconds instead of having to check everywhere?

**Comment by Fox-McCloud** [comment]
>Should we just centralize all URLs to some variable/constant so that when we wanna change the base host it's just 2 seconds instead of having to check everywhere?

Likely, and it should probably be based on a `config.txt`

**Comment by tigercat2000** [comment]
This is unnecessary. The URL isn't permanently changing.

**Comment by Regen1** [comment]
you're jumping the gun

Paradise will continue to use nanotrasen.se

**Comment by Fox-McCloud** [comment]
will handle later once everything is sorted.

**Pull request closed without merging**
