### PR TITLE
Tweaks to Orion and Battle arcades ticket amounts

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Changed the way score is calculated for Orion and battle arcade:
* Battle arcade: HP + MP + 5 -> 35 tickets
* Orion arcade: crew + food/2 + fuel/5 + engine + hull + electronics - clings ->
10 * (crew - clings) + 5 * (engine+hull+electronics)

Feel free to suggest different numbers
## Why It's Good For The Game

Battle arcade: With the way this game is built i find it unlikely to find a way which will prevent the spam that players can do to accumulate scores. Turning into a random amount would be better, making the players play the game multiple times for tickets instead of just spamming "recharge power" until their stats are high enough.

Orion arcade: This will result in better amounts of tickets for this arcade and will incentivise players to keep their crew alive for more tickets (which is what makes sense for the theme of this game).

## Testing

- Played both games and won a few times
## Changelog
:cl:
tweak: Battle arcade: The amount of tickets is now a fixed number
tweak: Orion arcade: The amount of tickets now relies more on your crew and eng/hull/elects
/:cl:

### CODE REVIEW

**Comment by spacegeese** [comment]
this is so sad we can't farm tickets anymore for **useless toys that serve no real purpose other than being cool** (except for water balloons but that's debatable)

**Comment by Henri215** [comment]
> this is so sad we can't farm tickets anymore for **useless toys that serve no real purpose other than being cool** (except for water balloons but that's debatable)

image

What do you think would be a good amount? Because i want to make the rewards good without having to abuse the game.

**Comment by spacegeese** [comment]
My main issue is that toys aren't really particularly useful, no one uses the arcade to powergame with water balloons or fake chainsaws, and I don't really want RNG to tell me how many tickets I get for my efforts

**Comment by Henri215** [comment]
Values have been updated on the PR description after testing more and collecting feedback

**Review by Sirryan2002 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]

**Pull request merged**
