### PR TITLE
Update for the pig sprite

### PR DESCRIPTION
**Pull request by Draconic-saint**
### Updates the pig's sprite

New version on the left, now with 100% less asshole:

dreamseeker_2017-09-15_00-05-00

I felt the poor thing was due for an update, however he still turns into a nice ham upon death. Blaming bluespace on that one...

### CODE REVIEW

**Comment by Draconic-saint** [comment]
No assholes allowed

**Comment by FalseIncarnate** [comment]
At least the coloring is more consistent in all 4 directions. Old sprite was oddly darker in the back sprite (facing north), and had this "stare into the camera" deal going on in the other 3 direction. Now the pig can see where they are going (or who is slaughtering them) when moving/facing east/west.

**Comment by Draconic-saint** [comment]
Also pigs are no longer as tall as a person

**Comment by taukausanake** [comment]
Awww but i like the old sprite. It's cute and retarded looking. Can we at least still keep it in the dmi?

**Comment by Ralta** [comment]
Nice! I always thought the pig was a super weird sprite - the new one is much better imo.

**Comment by alexkar598** [comment]
Who gave a diet to the pig?

**Comment by taukausanake** [comment]
Make the new sprite a baby pig and the old one be adult so you have reason to kill it. Also pig breeding so you won't run out of meat.
I mean, unless you rather breed corgis instead. I don't mind, meat's meat.
I know what I'm doing as chef now :3

**Comment by Draconic-saint** [comment]
@taukausanake That's code-stuff and would go b(e)yond the scope of this PR.

**Comment by Twinmold93** [comment]
I like the new sprite, looks cleaner and generally better as it's not horrendous looking and is smaller.

**Comment by Bram961** [comment]
@Draconic-saint this affected the balance wrongly, please instead add the asshole back in and add another asshole at the front
 pigass

**Comment by Vivalas** [comment]
Just replace the pig with the two butt thing on the left. GMO animals

**Comment by Citinited** [comment]
That should totally be a mob that pops out from strange reagent / "incorrect" usage of the EXPERI-Mentor

**Comment by alexkar598** [comment]
Why not keep both sprites and make it a 50%/50% chance of getting it

**Comment by Rumiluntti** [comment]
Severe lack of pig asshole is harming my immursuns.
Emulsions spoiled.

**Pull request merged**
