### PR TITLE
An update to bar drink sprites

### PR DESCRIPTION
**Pull request by Balthusdire**
## What Does This PR Do
Updates for existing bar drink sprites, complete redo of others, as well as adding unique ones for drinks that use generic sprites.

## Why It's Good For The Game
More immersion, more fun for bartenders and patrons, unifying the perspective of bar drinks to make things look smoother. Some of the old sprites are...well you'll see when you scroll down.

## Images of changes
Here is some comparisons so people can see the differences.

Allies Cocktail
Old:
alliesold
New:
alliesnew

Aloe
Old:
aloeold
New:
aloenew

Antifreeze
Old:
antifreezeold
New:
antifreezenew

Banana Honk
Old:
bananahonkold
New:
bananahonknew

B&P
Old:
bpold
New:
bpnew

Bravebull
Old:
bravebullold
New:
bravebullnew

Congac
Old:
congacold
New:
congacnew

Erika Surprise
Old:
erikasurpriseold
New:
erikasurprisenew

Gin and Sonic
Old:
ginandsonicold
New: Sorry for the sizing, will fix asap
ginandsonicnew

Iced coffee
Old:
icedcoffeeold
New:
icedcoffeenew

Margarita
Old:
margaritaold
New:
margaritanew

Mead
Old:
meadold
New:
meadnew

Sbiten
Old:
sbitenold
New:
sbitennew

Screwdriver
Old:
screwdriverold
New:
screwdrivernew

Servo
Old:
servoold
New:
servonew

Silencer
Old:
silencerold
New:
silencernew

Suicider
Old:
suiciderold
New:
suicidernew

Syndiebomb
Old:
syndiebombold
New:
syndiebombnew

Trinary
Old:
trinaryold
New:
trinarynew

Uplink
Old:
uplinkold
New:
uplinknew

Wine
Old:
wineold
New:
winenew

Sake
Old:
sakeold
New:
sakenew

## Changelog
:cl:
tweak: tweaked many bar drink sprites
imageadd: added sake sprite, bacchus blessing

/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
lack of upgrade in sprite quality makes this pr unnecessary. and half of these sprites are far from acceptable.

**Comment by Balthusdire** [comment]
Whelp I'm going to have to disagree obviously. Half the sprites are bland still since they were just updates from a flat perspective to the usual slightly shifted one and the others match pretty closely to the style of many other drinks.

**Comment by Ionward** [comment]
A lot of the novelty glasses look really out of place or low quality. And changing the syndicate bomb to actually look like a grenade instead of a visual pun with tank transfer valves is rough. I do like the Bacchus Blessing, Sake, and Servo sprites though.

**Comment by ExusA** [comment]
I love these! The ones with dark outlines look a bit weird, though. Not a huge fan of the mead glasses, the uplink, the syndicate bomb and the silencer, and the suicider looks like it shouldn't be able to stand up... the others look _really_ good though. Also the syndicate bomb being a tank transfer valve is a detail I liked before, although now I'm intrigued by the idea of a minibomb themed drink.

**Comment by AffectedArc07** [comment]
This being a literal minibomb casing is not going to fly
image

**Comment by Qwertytoforty** [comment]
Shame, the syndicate bomb re sprite to that was my favorite of this batch,

**Comment by taukausanake** [comment]
Give it a handle and some animated fizz popping from the top. That'll fit the syndie bomb

**Comment by Balthusdire** [comment]
Actually minibomb casings fly all the time when tossed about! Oh ho ho ho...bad jokes aside, updated syndie bomb drink to a glass version to make it obviously not a bomb. 
syndiebombdrinkss13glass

**Comment by AffectedArc07** [comment]
Better, but I dont have a very good view on sprites, so this does not have explicit approval or objection from me.

**Comment by variableundefined** [comment]
Not enthusiastic about these sprites either, I don't think they add much or is of much better quality.

**Comment by variableundefined** [comment]
Reopening as I didn't realize it was not an objection.

**Comment by Varghh** [comment]
Drinks look really good, the minibomb being a full glass now looks awesome, we have many sprites of drinks who are a bit copy paste and i'm always up for some sprite changes.

**Comment by Balthusdire** [comment]
Alright I've done a bunch of updates. Updated the quality of all the drinks, dropped the mead horn as it was visually confused for a tulip glass, and shrank and adjusted silencer colours to make them actually glass.

**Comment by Varghh** [comment]
Looks even better now

**Comment by McRamon** [comment]
Better. Not a huge jump in quality, but at least not a downgrade. Some of the drinks don't look good still - Suicider, Trinary, Banana Honk, Sake - those could be improved (and the fact that previosu versions of some of them are literal garbage doesn't mean we should not try our best), but i guess they wont. Good job on Jin and Sonic, at least one drink with interesting approach. I removed my thumbs down.

**Review by Kyep — APPROVED** [review]

**Comment by variableundefined** [comment]
I'm giving approval to this and Affected is no longer objecting since the sprites quality are better than before.

Merging

**Pull request merged**
