### PR TITLE
Hotkey/interface update

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds proper configuration settings for the rules, donations and repository URL, rather than using defines.
2) The admin restart verb no longer has a confirmation - you can now cancel out of the time selection.
3) Adds a new hotkey mode, "Cyborg". This mode gets rid of unused hotkeys for cyborgs and adds other ones (partial port of https://github.com/tgstation/-tg-station/pull/3215 by MrStonedOne).
4) Updates hotkey help so it's up-to-date.
5) Adds the adminghost hotkey to F6, and moves the other ones one step up.
6) Adds other new hotkeys for humans see below).
7) Fixes the Admin PM hotkey.
Cyborg:
- 1-3 allows you to toggle modules 1-3.
- Q/END lets you unequip your active module.
- 4 lets you toggle intents.

All:
- t lets you say.
- m lets you me.
- o lets you OOC.
- b lets you resist.

*Configuration change: REPOSITORYURL, DONATIONSURL and RULESURL need to be set.*

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
I like the current hotkey placement for OOC, me, etc at the moment. :-1: on that, but :+1: for fixing everything else, this will mess up my macros as I have M binded to something for another server, shift + F2 is OOC, resist is C, etc.

**Comment by Markolie** [comment]
The placement does not change. The OOC hotkey is on top of the existing one.

**Comment by Ultimate-Chimera** [comment]
Ah, I see.

**Comment by Ultimate-Chimera** [comment]
Can you make it a toggle possibly?

**Comment by Markolie** [comment]
Sorry, but no. This is the standard on all /tg/ servers and will be on ours, I doubt it's too much effort to change your toggle.

**Pull request merged**
