### PR TITLE
'Lesser Form' transformation for Dionae

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Makes Diona turn into Diona Nymphs when monkeyfied, either through genetics or admemery.
Fixes: #2940

**This is only for turning into their lesser form (Genetics block 55), *not* for being gibbed in general.**

## Why It's Good For The Game

Allows Diona players to actually continue playing when turned into their 'Primitive Form', since most other species can.
Possibly more lore friendly, since Dionae are made up of lots of nymphs.
No Diona instakills from monkey syringes.

### Before:
zRNhIpU56N
### After:
*(Only the moving one is actually a nymph, all the others are internal organs because they don't have custom sprites.)*
2h133AtWow

## Changelog
:cl:
tweak: Dionae will now become Diona nymphs when monkeyfied, as opposed to just being gibbed.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
I really don't like this.
Exploding into a bunch of nymphs is bad enough.
But many of these organs (allegedly, I hear) don't even have sprites, so they look like nymphs even though they're not.
This would be very confusing.

**Comment by SabreML** [comment]
> I really don't like this.
> Exploding into a bunch of nymphs is bad enough.
> But many of these organs (allegedly, I hear) don't even have sprites, so they look like nymphs even though they're not.
> This would be very confusing.

Everything in the gif except for the moving one is an internal organ, so the sprite issue definitely exists.

Currently however if you shoot a diona with a monkey syringe they will simply get gibbed, and will have to hope someone finds their brain (which has the same sprite as everything else, and is called a 'Gas Bladder').

While this PR doesn't make it easier to tell what's what, it does let the players actually keep playing.

**Comment by Pixelzilla** [comment]
I am pretty sure we had this in early paradise and it was removed specifically because it was abused.

**Comment by Mitchs98** [comment]
> > I really don't like this.
> > Exploding into a bunch of nymphs is bad enough.
> > But many of these organs (allegedly, I hear) don't even have sprites, so they look like nymphs even though they're not.
> > This would be very confusing.
> 
> Everything in the gif except for the moving one is an internal organ, so the sprite issue definitely exists.
> 
> Currently however if you shoot a diona with a monkey syringe they will simply get instagibbed, and will have to hope someone finds their brain (which has the same sprite as everything else, and is called a 'Gas Bladder').
> 
> While this PR doesn't make it easier to tell what's what, it does let the players actually keep playing.

You can't shoot genetic syringes last I checked, unless something changed? And if that did change then we have some bigger issues.

**Comment by SabreML** [comment]
> You can't shoot genetic syringes last I checked, unless something changed? And if that did change then we have some bigger issues.

That's true actually, my bad.
Still an issue though, especially since there seems to have been a lot of monkey syringes spread around recently.

**Comment by Mitchs98** [comment]
> > You can't shoot genetic syringes last I checked, unless something changed? And if that did change then we have some bigger issues.
> 
> That's true actually, my bad.
> Still an issue though, especially since there seems to have been a lot of monkey syringes spread around recently.

Ooh alright. I was just making sure I didn't miss a PR or anything haha. And yeah I noticed that too. Definitely is a problem. Honestly think the other species need a lesser form too, monkey syringes are pretty cheesy as is. Though...Kidan, Grey, and Drask would need custom sprites made....a topic for another day.

**Comment by Kiyahitayika** [comment]
> I really don't like this.
> Exploding into a bunch of nymphs is bad enough.
> But many of these organs (allegedly, I hear) don't even have sprites, so they look like nymphs even though they're not.
> This would be very confusing.

@SabreML Any ideas for adding new sprites for the organs? Granted, Dionaea are a superorganism comprised of nymphs. Some organs (can't remember which species) use the alien claw sprite which always throws me for a loop when I play Medbay.

**Comment by SabreML** [comment]
> @SabreML Any ideas for adding new sprites for the organs? Granted, Dionaea are a superorganism comprised of nymphs. Some organs (can't remember which species) use the alien claw sprite which always throws me for a loop when I play Medbay.

I don't have any spriting skills myself, but the way I was thinking would be to make the organs look like Nymphs curled up into different shapes. I don't know how well that'd work in 32x32 though.

Even if there were new sprites for the organs I feel like that's out of scope of this PR, so it'd need to be added separately.

**Comment by Kiyahitayika** [comment]
(linking issue: https://github.com/ParadiseSS13/Paradise/issues/2940)

**Comment by Dashsora** [comment]
Huh I was convinced that organs looking like nymphs was intended... since they're made up of nymphs and all ?

I like this, and really wish every single race had a lesser mob to turn to.

**Comment by Fox-McCloud** [comment]
I'd rather see nymphs made into a monkey subtype, than this.

This is really snowflakey and inconsistent with literally everything else.

**Comment by SabreML** [comment]
> This is really snowflakey and inconsistent with literally everything else.

I wouldn't say it's snowflakey at all. It's designed around allowing species to have simple mobs as their 'Primitive Form' rather than just reskinned monkeys, so if anything I'd say it's *more* modular than the current system.

The only reason it seems out of place at the moment is because Diona are currently the only species with a simple mob form.
If Kidan for example got some sort of larva as their primitive form then it would make a lot more sense gameplay wise and code wise for it to be a simple mob, rather than having to override 90% of the monkey mechanics to support it.

**Comment by Spacemanspark** [comment]
@Pixelzilla yes and no.

A dead diona was able to split upon dying, becoming a series of nymphs. This _was_ a problem.

However, this is something else entirely with a more niche use. I'm fine with it

**Comment by variableundefined** [comment]
No maint approval forthcoming and the last two was either a no or a no approval. 

Closing.

**Pull request closed without merging**
