### PR TITLE
Makes french fries a deep fryer recipe instead of a processor recipe

### PR DESCRIPTION
**Pull request by LordJike**
Because it triggers me.

With this, in order to make french fries you will have to put the potato wedges inside the deep fryer instead of the processor, like god intended.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I detect web editor heresy.

**Comment by LordJike** [comment]
It's my literal first pull request ever, and as it was a really simple change I just used the web editor

**Comment by taukausanake** [comment]
@LordJike I respect your decision to use the webeditor AND playtest it on your own. That is what I would do and believe what would be done for such simple edits. Where this wouldn't be the simplest of edits, the playtest is what completes it

**Comment by Necaladun** [comment]
Yeah good work on the playtesting etc, tyvm!

This is how fries should be made. Anything else is heresy.

**Comment by FalseIncarnate** [comment]
Good catch, I had forgotten about fries when I made the deep-fryer special interactions.

**Pull request merged**
