### PR TITLE
Kills the Vox Metaclub

### PR DESCRIPTION
**Pull request by 13spacemen**
## What Does This PR Do
Adds "NO VOX ALLOWED" signs. Currently only mapped into Cyberiad, will add other maps later
You can screwdriver them to move them.

These are from /vg/station

## Why It's Good For The Game
NO VOX ALLOWED

## Changelog
:cl:
add: Added NO VOX ALLOWED signs
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Take it from me, the resident vox hater.

This is going to encourage far too much metagrudging behaviour that might even stray into selfantagging territory, with people beating up vox who enter.

**Comment by 13spacemen** [comment]
If people are actually beating up Vox (or any race) because of a meme poster they need to read the rules again. It's just a joke poster, it doesn't overrule self-antagging rules.
Also these signs are currently in maint mapped in a 1-tile wide space most players won't know about them, anyone who opens up the map or github to see the signs knows that metagrudging and self-antagging is not ok

**Comment by AffectedArc07** [comment]
> anyone who opens up the map or github to see the signs knows that metagrudging and self-antagging is not ok

You would be surprised.

**Comment by 13spacemen** [comment]
True, but seriously anybody who metagrudges and self-antags players based on what race they play doesn't need a poster to do it

**Comment by LightFire53** [comment]
The only way I could see this passing is if they ended becoming posters and were joining a series of No (species) Allowed posters as contraband (and even then that is a mighty if). This is typically not the type of content we are looking to add

**Comment by procdrone** [comment]
> True, but seriously anybody who metagrudges and self-antags players based on what race they play doesn't need a poster to do it

If that's the case why are you only adding anti vox posters? if there isn't any grudge or animosity intended, you surely would add them for all species right? And not downplay it down to a deep-rooted meme?

**Comment by 13spacemen** [comment]
> If that's the case why are you only adding anti vox posters? if there isn't any grudge or animosity intended, you surely would add them for all species right? And not downplay it down to a deep-rooted meme?

I didn't sprite these I found them on another server and thought they were neat.
I welcome spriters to make NO X ALLOWED posters for every race, that would be preferable. I can't sprite which is why I haven't done it

**Comment by Carthusia** [comment]
I mean, i kinda like the signs

**Comment by AffectedArc07** [comment]
2 heads and a maint objecting, no one in favour from either party.


Closing.

**Pull request closed without merging**
