### PR TITLE
Adds the Ocelot bundle to traitor bundles

### PR DESCRIPTION
**Pull request by datlo**
## What Does This PR Do

Adds the Ocelot bundle as an option for syndicate bundles. Contains two syndi revolver, two speedloaders, combat knife, encryption key, a holster, and appropriate outfit. Also fixed the TC cost comments on payday bundle.
image

## Why It's Good For The Game

Would be a cool reference and addition to syndi bundles, dual wield is fun. You could also trade with a fellow traitor to arm yourselves both. The Holo-cigar item was intentionally *not* part of this bundle for the sake of 1. balance 2. keeping human specific item to humans

E4IyrCPVUAUxvSr

## Testing

Spawned a buncha bundle beacons till I found the new ocelot bundle, spawned it, checked that everything was there.

## Changelog
:cl:
add: Added the Ocelot bundle to syndicate bundle selection.
/:cl:

### CODE REVIEW

**Review by 1080pCat — APPROVED** [review]
Code is fine

**Comment by 1080pCat** [comment]
I really feel like two .357s AND two speedloaders is way too much, thats 21 shots of nearly uninterrupted fire, i'd personally suggest one speed loader + a .357 ammo box.

**Comment by matttheficus** [comment]
Could you add the total un-bundled cost so that we know the exact % value its giving?

**Comment by Rayforx** [comment]
Technically, one magazine is free with each revolver. 
So you do not have to calculate those into the cost of the kit.

**Comment by Gatchapod** [comment]
I feel like if this bundle is to achieve its goal, it **needs** an agent ID. Without it, you might as well just scratch the whole idea.
How else are you going to pick your Kojima name?

**Comment by Henri215** [comment]
All thats left is the custom sprite?

**Comment by datlo** [comment]
Ready for review

**Pull request closed without merging**
