### PR TITLE
Adds Maids

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
...as an alt title for Janitor.
Also gives the janimaid uniform bio protection identical to that of the regular janitor uniform.

:cl: LittleBigKid2000
add: Adds Maid as an alt title for Janitor. Uniform sprite by Nienhaus, Vox version by KasparoVy.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
can we get some sweet pics

**Comment by Midaychi** [comment]
If you have this as your job title there should be a small chance on spawn that you start as a loyalty implanted infertile xenomorph wearing janitor gear with a valid id

**Comment by KasparoVy** [comment]
Lmfao, I knew I did the Vox version of that damn janimaid sprite for a reason...

**Comment by LittleBigKid2000** [comment]
Here's a picture of Entchtut as a maid

**Comment by Nienhaus** [comment]
Fun fact, I made the janimaid sprite based off my avatar.

**Comment by Spacemanspark** [comment]
Should probably credit Nienhaus, @LittleBigKid2000.

**Comment by LittleBigKid2000** [comment]
The janimaid outfit was already in the game, but okay.

**Comment by Iamgoofball** [comment]
stupid fetish content, news at 11

**Comment by taukausanake** [comment]
I only wish it was purple like jani-everything. Still, I think maid is a good role title

**Comment by Necaladun** [comment]
I uhm, can't believe this...

But I agree with Goofball.

I'm fine with the uniform being in a vending machine, but as a job title with equipment seems a bit too, well. Fetish.

And inb4 unathi as lusty maids.

**Comment by Dumbdumn5** [comment]
AHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAAHHAHAHAHAHAHAHAHAHAHAAHAHAHAHAHAHAHAHAHAHA! (:+1: sure, why the hell not)

**Comment by taukausanake** [comment]
In the realm of fetishes but maybe not completely related and most likely sexist, there is no gender check for this title, is there? I just don't think I've seen males ever as a "maid" per see...

**Comment by Iamgoofball** [comment]
there's a fetish for that too

**Comment by LittleBigKid2000** [comment]
There is no gender check. Males and attack helicopters can be maids and wear a maid uniform just as much as females can.

**Comment by MindLeaker** [comment]
Truly there's a first for everything; Goofball's right, this is nothing but an RP excuse for people to act out their silly fetishes and get away with it

Put it in a Vendor, not add a ridiculous replacement for the Janitor :-1:

**Comment by Davdichan** [comment]
Hippie as alt Botanist title when?

**Comment by Davdichan** [comment]
Hippie as alt Botanist title when?

**Comment by Fox-McCloud** [comment]
Think I'm going to have to agree with @Necaladun on this one. Sorry.

**Pull request closed without merging**
