### PR TITLE
Rissa's Fluff Item

### PR DESCRIPTION
**Pull request by Agameofscones**
This was harder to implement than I thought it would be.
Has fat and non fat sprites, etc, all the good stuff.

ckey: thatdanguy23
Character Name: Rissa Williams
Job: Bartender

image
alttext

:cl: Triiodine
add: thatdanguy23's fluff item
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
wait counterfeitguise is back?

**Comment by KasparoVy** [comment]
Paradise is like crack.

**Comment by Birdtalon** [comment]
@Agameofscones was it by any chance due to lack of documentation regarding adding clothing icons?

**Comment by taukausanake** [comment]
@Birdtalon it was probably with all the extra icons that are usually inherited. Also, "icon_state" "item_state" "item_color" is _really weird_.

> Paradise is like crack

lol

**Comment by Agameofscones** [comment]
> @Agameofscones was it by any chance due to lack of documentation regarding adding clothing icons?

More specifically what icons go where, the proper naming scheme for rolled down suits (_s & _s_d) and icon overrides. It was all quite silly.

**Comment by SamHPurp** [comment]
@Agameofscones conflicts

**Comment by Agameofscones** [comment]
Will fix conflicts soon, no worries

**Pull request merged**
