### PR TITLE
Adds higher quality version of title2.ogg music

### PR DESCRIPTION
**Pull request by Arkatos1**
This is a hot port from https://github.com/tgstation/tgstation/pull/43461, so credit to these guys.

**What does this PR do:**
In nutshell, this PR replaces title2.ogg music with a higher quality version. Previous version was highly compressed and sounded bad as a result.

For reference, [this](https://www.youtube.com/watch?v=dCPWE4WexM8) is our current, compressed version of the music.

And [THIS](https://www.youtube.com/watch?v=vHo7npmGcHU) is a high quality version, which this PR adds.

**Changelog:**
:cl: Arkatos
soundadd: Replaced title2.ogg music with a higher quality version
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
Eargasmic.

**Comment by Tails2091** [comment]
The current one has a sample rate of 11025Hz and a bitrate of 26kb/s just the right amount to be recognizable.

**Comment by Tails2091** [comment]
The current theme fades off, this one is an abrupt cut. Don't know if this will be an issue or not.

**Comment by Arkatos1** [comment]
I have tested the sound in-game and there are no problems with it not being recognizable or anything, it really just sounds better than the original file.

@Tails2091 You are absolutely right with the fade out. I have added the fade out effect to the music, aking to the original file. I have also turned volume down a bit to match the original file. I would not be afraid they are precisely the same now, except the higher quality in the proposed one.

**Pull request merged**
