### PR TITLE
Appveyor CI

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This PR adds compatibility for Appveyor CI. Now I know what youre saying, and yes I know we already have Travis. But Appveyor has something useful. Artefacts. Appveyor will build the current PR, and provide a zipped download to the compiled code to allow for testing. I havnt *fully* cut down on what files we dont need yet, but that will come soon (Its 00:20 AM).

No CL because this doesnt even change the game code

### CODE REVIEW

**Comment by craftxbox** [comment]
Appveyor is really nice, +1 for this pr.

**Comment by KasparoVy** [comment]
Far out.

**Comment by AffectedArc07** [comment]
If you see a lot of force pushing, thats me pushing to my fork so I can actually test this

**Comment by AffectedArc07** [comment]
Right after a lot of pushing, this is now ready.

**Comment by SkeletalElite** [comment]
I was hoping that travis was going to have a hard time with this one so I could joke about how hes mad that someone is taking his job.

**Comment by taukausanake** [comment]
I'm disappointed I missed Affected's last comment so I could have joked about needing to push harder

**Pull request merged**
