### PR TITLE
[DNM] Event test-merge PR, please ignore.

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Adds an event map and overrides current map datum to force it. For an upcoming event.

## Testing
It just works

## Changelog
:cl:
add: If this got merged someone screwed up
/:cl:

### CODE REVIEW

**Comment by YoureNotTheSharpest** [comment]
Robotics is not connected to the science grid on round start
image

**Comment by Adrer** [comment]
AI sat maintenance grille uses the grille/fence subtype. this causes an invisible grille to spawn in the marked location (Issue is mirrored on other side of AI sat) Regular grille should be used instead.

image

**Comment by Adrer** [comment]
X:199, Y:179
Supply/scrubber T-manifold leading nowhere.

image

**Comment by A-Medster** [comment]
i really liked the port, though i was only on for about 30 minutes and it was a late join job i had. from what i saw, my only real issues were a weirdly positioned firelock set at arrivals, but looks like it would ultimately work. and that you can mine into the Paramedic's office through an assumedly all access broom closet

image

this same issue appears to be happening in medical with the CMO's office, the janitors office, detective's office, the Chaplin's office, robotics, and EVA (to a degree). I can see there being an argument for that being by design, but why would the CMO get this major security risk, while every other head gets encased in walls. picks appear to be readily available everywhere on the station so some rock means not much more than décor to someone that wants into the CMO's office, robotics, or anywhere else where people would feasibly want to break into to steal things.

image

image

**Pull request closed without merging**
