### PR TITLE
Mushroom spreading removal

### PR DESCRIPTION
**Pull request by Gatchapod**
## What Does This PR Do
Removes the ability to spread of glowshrooms, glowcaps and shadowshrooms.
Map changes due to existence of `/obj/structure/glowshroom/single` on some maps, which was a non-spreading variety of glowshrooms. Now all glowshrooms should behave like that, so there's no need to keep it.

You can still place non-spreading mushrooms, either strategically or for aesthetic purposes, but they will no longer consume the entire station.

I really hope I didn't mess the map merger up. I hate mapping and I hate that thing.

## Why It's Good For The Game
For a long time, those were a problem for everyone. Crew suffers as mushrooms burn their eyes out, admins get worried over server performance, antags (especially shadowlings) end up defenseless against perfectly lit maints. Only botanists get some sort of questionable joy from ruining everything for everyone.
Given how Kyet expressed interest in removal of the mushrooms' ability to spread, I've decided it's worth to make this PR.

## Changelog
:cl:
del: Glowshroom, glowcaps and shadowshrooms will no longer spread by themselves
/:cl:

### CODE REVIEW

**Comment by hal9000PR** [comment]
Would you apply this to shadow shrooms as well? they are equally grief machines and annoying to deal with for the entire crew.

**Comment by Gatchapod** [comment]
> 
> 
> Would you apply this to shadow shrooms as well? they are equally grief machines and annoying to deal with for the entire crew.

Yes, all three self-spreading mushroom varieties are affected.

**Comment by Spacemanspark** [comment]
Thank fuck

**Comment by Krysonism** [comment]
The TG nerf is better; Making them die after some time and spread slower each generation.

**Comment by Krysonism** [comment]
The TG nerf is better; Making them die after some time and spread slower each generation. (Based on endurance)

**Comment by DeveloperLoser** [comment]
aw we don't get to lynch botany harder than viro when they plant shadow shrooms and it turns out to be slings :( That being said I think yea, maybe they should just spread slower so that shadow shrooms especially can be used by slings, seeing as how they could use the help if they get the chance to plant them.

**Comment by Krysonism** [comment]
https://github.com/tgstation/tgstation/pull/51023
https://github.com/tgstation/tgstation/pull/52120
https://github.com/tgstation/tgstation/pull/52169
https://github.com/tgstation/tgstation/pull/53652

Here is the tg glowshroom nerf and related bugfixes and optimizations.

**Comment by Gatchapod** [comment]
I'll allow myself to sound a bit smartass and say that in over 3000 hours spent on this server, I have seen shadowlings trying to use shadowshrooms once. This leads me to believe it's either too hard to pull off or plainly useless for shadowlings. Besides, they'll already greatly benefit from lack of glowshrooms. Shadowshrooms are a small price to pay here.

Regarding how /tg/ handles those, you're more than welcome to do it. I don't like the idea of skilled botanists still being able to reproduce, even if briefly, the issue I'm trying to address here.
I, personally, believe those mushroom should only exist on the tile/wall they were placed on. What we have is quite horrible and any change here is probably a good one.

**Comment by Spacemanspark** [comment]
I'd rather have no spreading than any at all.

**Comment by DeveloperLoser** [comment]
> I'll allow myself to sound a bit smartass and say that in over 3000 hours spent on this server, I have seen shadowlings trying to use shadowshrooms once. This leads me to believe it's either too hard to pull off or plainly useless for shadowlings. Besides, they'll already greatly benefit from lack of glowshrooms. Shadowshrooms are a small price to pay here.
> 
> Regarding how /tg/ handles those, you're more than welcome to do it. I don't like the idea of skilled botanists still being able to reproduce, even if briefly, the issue I'm trying to address here.
> I, personally, believe those mushroom should only exist on the tile/wall they were placed on. What we have is quite horrible and any change here is probably a good one.

Fair enough, i agree with @Spacemanspark  then

**Review by Kyep — APPROVED** [review]

**Comment by Fox-McCloud** [comment]
Let's not jump to extremes like this.

The nerfs TG has are quite reasonable---still spreading, but they decay is an excellent start.

**Comment by Gatchapod** [comment]
Does anything in TG version, in practice, prevents botanists from spamming those to create effectively endless tide of glowshrooms?
I fear like with some gene tweaking and minimal dedication, they'll be able to recreate the issue.

I do understand removal is a heavy-handed solution, but you can clearly see a lot of people are extremely tired of those mushroom floods. We might be overreacting here due to that.

**Comment by Spacemanspark** [comment]
I don't see this as an extreme tbh.

**Comment by Kepplerx** [comment]
This solves all the issues I saw with it when I posted about it, just wanted to say thanks for doing the coding for it I myself am unable to do

**Comment by Landerlow** [comment]
Thank god for this PR. Or rather, thank Gatchapod for this PR.

**Comment by Spacemanspark** [comment]
Godchapod

**Comment by Fox-McCloud** [comment]
>Does anything in TG version, in practice, prevents botanists from spamming those to create effectively endless tide of glowshrooms?

They decay, so they're going to die off, so yes.

Your PR just makes it more tedious to spam---there's nothing preventing them from carrying sackfulls of the of them and planting them everywhere still. 

Making them decay *does* resolve this issue.

**Comment by DeveloperLoser** [comment]
> >Does anything in TG version, in practice, prevents botanists from spamming those to create effectively endless tide of glowshrooms?
> 
> They decay, so they're going to die off, so yes.
> 
> Your PR just makes it more tedious to spam---there's nothing preventing them from carrying sackfulls of the of them and planting them everywhere still. 
> 
> Making them decay *does* resolve this issue.

Couldnt they still just carry a sack full? And it being more tedious to spam is good, means theyre in maint longer and theres much fewer to destory (50 per bag i belive)

**Comment by Gatchapod** [comment]
> 
> 
> > Does anything in TG version, in practice, prevents botanists from spamming those to create effectively endless tide of glowshrooms?
> 
> They decay, so they're going to die off, so yes.
> 
> Your PR just makes it more tedious to spam---there's nothing preventing them from carrying sackfulls of the of them and planting them everywhere still.
> 
> Making them decay _does_ resolve this issue.

If they carry sackfuls of those, you can still get security to forcefully demote them and put an end to the problem. Naturally, the same applies to the TG version, so it's not a strong argument.
Perhaps trying TG solution to the issue first would be more appropriate and total removal should only be considered if the problem persists.

I see your reasoning, but you can also see rather enthusiastic feedback for this PR. I think majority actually wants drastic measures to be taken.

**Comment by Sikroth** [comment]
> > Does anything in TG version, in practice, prevents botanists from spamming those to create effectively endless tide of glowshrooms?
> 
> They decay, so they're going to die off, so yes.
> 
> Your PR just makes it more tedious to spam---there's nothing preventing them from carrying sackfulls of the of them and planting them everywhere still.
> 
> Making them decay _does_ resolve this issue.

While I am fine with both ways of nerfing the shrooms, I believe the removal of spread is actually more sensible here. It removes the godawful spread whenever someone plants 1 shroom and half the station instantly becomes an eyesore. It also makes it so you can not just open a maint door and quickly plant a shroom cluster under the door to light up half of maints.

Sure the decay wouldn't be an awful solution, but realistically the tg implementation takes about 30 minutes to decay, so you'd just need to go back to botany, resupply and replant every now and then. I'd say that's about as tedious and solvable with sacksfull as the no-spread approach.

Having not-spreading plants means you'll at *least* need to walk into maints before making them bright as the sun, which involves a bit more risk than just planting 1 cluster and lighting half the station, even if temporarily. That's in my opinion better because one of the main issues with the shrooms is shadowling rounds immediately becoming unwinnable for the slings. This'd give them more of a chance to catch shroom-planters without a single cluster removing half of maints for them.

**Comment by variableundefined** [comment]
Two maintainer objections, no approval coming. 

Closing.

**Pull request closed without merging**
