### PR TITLE
Ports Lamias from ErosResearchStation

### PR DESCRIPTION
**Pull request by tigercat2000**
Features:
 - They have a tail organ instead of legs.
 - They can eat people.
 - Mobs now provide air to mobs inside of them. The oxygen and nitrogen is a static standard value, but the temperature is tied to body temperature.
 - Added Polaris BP_ defines.
 - The Lamia Tail is targetable by aiming at either leg or foot.
 - Robot tails.
 - Mobs in the stomach of a carbon will show on a health analyzer.
 - Lamias speak a subset of the Unathi Language.
 - You cannot help, disarm, or grab mobs that you are inside.
 - Clothes render on top of them. This is intentional.

:cl:
rscadd: Added Lamia race. They speak Sehlin, can eat people, and have a tail instead of legs.
bugfix: You cannot help, disarm, or grab mobs you are inside. You can punch them, though.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
h... hot?

**Comment by Keilden** [comment]
What happens if a lamia eats a lamia that has eaten a lamia?

**Comment by Spacemanspark** [comment]
Hahaha oh God.

**Comment by tigercat2000** [comment]
@Keilden that's for me to not know and you to test out :wink:

**Comment by sasanek12** [comment]
Maymay out of 10

**Comment by monster860** [comment]
I THOUGHT THE SNEKBODIES WERE SUPPOSED TO BE ADMIN ONLY.

NOW YOU HAVE SNEKBODIES.

**Comment by TheDZD** [comment]
[Nope](https://wiki.teamfortress.com/w/images/b/bd/Engineer_no01.wav?t=20100709022822).

**Comment by tigercat2000** [comment]
@TheDZD https://github.com/ParadiseSS13/Paradise/pull/4444/files#diff-b8ba05227a99d959bdb03d7c6c5c6ea8R43

**Comment by TheDZD** [comment]
@tigercat2000 :rage: :hocho: :tiger:

**Comment by tigercat2000** [comment]
@TheDZD rip lamias
died before they could live

**Comment by fludd12** [comment]
merge when

**Comment by tigercat2000** [comment]
i'm never deleting this branch :eyes:

**Comment by PJB3005** [comment]
@Tigercat2000 that's called an abortion.

Well deserved.

**Comment by TheDZD** [comment]
February 29, two thousand never.

**Comment by TheDZD** [comment]
Also, @PJB3005 I believe it's called chemotherapy.

**Comment by monster860** [comment]
@Tigercat2000 I haven't deleted ANY of my branches.

**Comment by tigercat2000** [comment]
@monster860 oh god

**Comment by Tastyfish** [comment]
I never deleted the buttbot one.

**Comment by Fox-McCloud** [comment]
>I never deleted the buttbot one.

Bring back buttbots 2016.

**Comment by Spacemanspark** [comment]
no

**Comment by tigercat2000** [comment]
> Bring back buttbots 2016.

never

**Comment by Iamgoofball** [comment]
# SLIPPERY SLOPE

**Pull request closed without merging**
