### PR TITLE
Fixes missing vent and scrubber in security checkpoint near brig on delta station 

### PR DESCRIPTION
**Pull request by Fluffyzack21**
## What Does This PR Do
adds scrubber and a vent in security checkpoint since there were none

## Why It's Good For The Game
Missing vent and scrubber are bad and its bad when the air alarm looks blank that does not control anything

## Images of changes

Screenshot 2024-07-22 181138

## Testing
Spawned as a atmospheric guy and checked if the vent and scrubber was working properly at security checkpoint near brig on delta station

## Changelog
:cl:
fix: Put a vent and a scrubber in security checkpoint near brig on delta station
/:cl:

### CODE REVIEW

**Review by S34NW — CHANGES_REQUESTED** [review]
We don't generally allow pipes under scrubber/vents due to historic issues where pipenets merge, please tweak the layout to avoid this happening here

**Comment by S34NW** [comment]
You have two of the same pipe on the same turf causing CI fails and runtimes

**Comment by Fluffyzack21** [comment]
> We don't generally allow pipes under scrubber/vents due to historic issues where pipenets merge, please tweak the layout to avoid this happening here

Okay I fixed it

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
There is an air vent in this wall
2024_08_05__05_26_09__paradise dme  deltastation dmm  - StrongDMM

**Review by warriorstar-orion — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
