### PR TITLE
Massive Race Sprite Reshading Project

### PR DESCRIPTION
**Pull request by Puckaboo2**
I'm just getting this all set up beforehand before I mess anything else up.

grey after
Currently, the changes I have made to grey are a reshade to the sides; that's pretty much it.

humans after
First-glance, I added a very slight blush to the females, lighter than the one before. And did I shade the shit out of the sides for humans. I also fixed the chests and bellies of the fronts and backs, and re-shaded the fat sprites.

skrell after
Skrell received a simple reshading treatment; they are now shaded 53, 53, 53, so they are now fully color-customizable. I re-shaded the tendrils to match the Skrell's skin color, so a Skrell's tendril color should match the color of their skin. You can also color a Skrell's eyes, now.

tajara after
I treated the kitties with different sprites for their chests, I cleaned their faces, I re-shaded the tails to be exactly the color as their fur, and I gave them claws (it's aesthetic; gloves cover them). Also, automatic pink noses and ears. They also have the option to choose male and female belly and muzzle patches in accessories, fully colorable, and the option to color the nose and inner ears at the same time. The fat sprites are placeholders in case anyone wants to code Tajara to be fat.

unathi after
I tried my very best to give Unathi scales all over their body, some sort of chest armor plating, scale patterns, and I also gave them a more whip-like tail. In addition, like Tajara, they have visible claws on their hands. You can now choose their muzzle and belly patch colors. Sadly, since most lizards store fat in their tails, I didn't make fat sprites for them. Unathi took the most time for me to perfect.

You can take a look at these beauties until I can get th before sprites up.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
needs a *before* and *after*.

Also, holy damn commits.

**Comment by Puckaboo2** [comment]
I know it needs a before and after, but I'm not done with the before, yet. Give me some time to make them and I will put them up.

**Comment by DesolateG** [comment]
I had a thought.. can we make nucleations have the same look as the glowing ones from fallout? Black skeleton seen through a glowing flesh?

**Comment by KasparoVy** [comment]
Looking pretty good! I was going to post a gripe about how the Tajara body's got too much contrast b/w the natural grey markings and the black of their fur but you can custom-colour those with the marking styles anyway, so it makes my point moot. I think you did a pretty great job!

I'm a bit iffy on the Unathi, however. Gonna admit that I like their current sprite a fair bit better..

I feel if there's any change to the Unathi sprite to be made, it should be as per **[this PR](https://github.com/PolarisSS13/Polaris/pull/2441)** from Polaris.

**Comment by Puckaboo2** [comment]
@KasparoVy. I tried a bit too hard with checkerboard, yes, but I don't know how else I can make scales work. I love the back sprite a lot, though.

**Comment by LightFire53** [comment]
I like it. They look nice.

Except fat kitties. Fuck fat kitties. #skinnykitty4life 😛

**Comment by KasparoVy** [comment]
I feel the way Unathi scaling is represented is adequate. If anything, the sprite only needs a minor touch-up. Perhaps **[this PR](https://github.com/PolarisSS13/Polaris/pull/2441)** might be a decent reference, however the hands seem somewhat awry.

**Comment by Puckaboo2** [comment]
@KasparoVy I could modify the Unathi so they look less checkerboardy, but I also would have to modify all the markings I edited for them. I am not sure if I am up for that task, right now. Either that. Or I remove Unathi from the PR because I modified suits and added masks for them.

**Comment by KasparoVy** [comment]
@Puckaboo2 I think reducing the checkerboardyness would be a good idea. I really dig the anatomical modifications/improvements you've made (claws, the legs/feet, arms/torso refinements etc) but I feel that meshed with scaling a hybrid of what you've got an what we got would be the best option.

Also, AFAIK, the Tajaran fat sprites will work right off the bat as they're already coded to be fat.

**Comment by Puckaboo2** [comment]
@KasparoVY I guess I have to work on Lizards again, or leave them alone. What do you think of the front chest pattern, thouvh?

**Comment by Aurorablade** [comment]
i have various reasons to be iffy on this but we shall see

**Comment by KasparoVy** [comment]
@Puckaboo2 I think the front chest pattern looks pretty great.

**Comment by Puckaboo2** [comment]
@KasparoVy I am going to need some help making the 'before' pictures, sprites blown up 5x
 I'm going to be working on Unathi again, so I feel a bit stressed. Could you could take the time to do some before sprite previews for me while I tweak on Unathi again? It'd really help me a lot.

**Comment by KasparoVy** [comment]
Sure thing, I'll do them all now.

**Comment by KasparoVy** [comment]
@Puckaboo2 Done

Before pictures.
humansbefore

greysbefore

skrellbefore

tajarabefore

lizardbefore

**Comment by KasparoVy** [comment]
After making the comparison b/w Tajara images, aside from seeing just how marked your improvements are, I was able to notice how truly prominent the darker Tajara nose and adjusted facial shading are. After looking up a picture of a black cat I was able to figure out why you picked that colour though, so that's fine haha

The sprites look fantastic, but I feel that keeping a bit of the shading around the cheeks from the previous version and adding a tiny bit more at the throat from the front would make this spot-on.

_Relevantcomparison_
tajaracomparison

**Comment by Puckaboo2** [comment]
@KasparoVy I appreciate what you have done, compiling the before sprites together and I realize I need to touch up the grey a bit.

I honestly like what you did with the front neck of the sprites, and I do suppose the nose could be lighter, so thanks for helping with that. but I do not like the dark speckles around the muzzle on the sides because I think about the people who want a light or pure white character; they wouldn't want dark speckles on their faces. I was honestly one of those people.. However, to compensate, I have decreased the shading of the patches on the 'new' Tajara by 15 rgb.

I am working on Unathi, right now. I will probably get the Unathi sprites uploaded after I am done with the full sprite and the markings. I think you will be satisfied with how I considered your and everyone else's concerns and incorporated them in the Unathi sprites.

**Comment by KasparoVy** [comment]
I'm looking forward to seeing it! Thanks for getting back to me on this. You're doing good work and it's wicked to see such old sprites getting a well-earned modernization

**Comment by Puckaboo2** [comment]
@KasparoVy Of course. You'll see results of v1 of my Tajara and v2 finalized Tajara in a few hours. Unathi may take a day or so.

**Comment by KasparoVy** [comment]
All in due time, no rush. Well worth the wait for the quality

**Comment by Puckaboo2** [comment]
I'll post the kitties on 1/16. I might also put up a preview for Unathi because I'm done with the non-deformed sprites and tails.

**Comment by Puckaboo2** [comment]
unathi after
Okay, this is the updated Unathi. Checkerboarding was on the legs and the chest to begin with, so I kept that relatively the same. I added only a little bit of checkerboarding on the face and the tail, and the back is somewhat checkerboard, but I consider it more detailed than checkerboard. Everything else is non-checkerboard. I consider this a final product, but I have not worked on the deformed sprites because I need approval, first. 

grey after
I made the female waists skinnier than the males'. That's it. I consider this finalized.

tajara after
I lessened the white patches by 5 rgb for each shade; it is not much of a change, but it is something. I also lightened the nose. I consider this finalized.

**Comment by KasparoVy** [comment]
Looks fantastic. Great work with the Unathi too. Excellent work :+1:

**Comment by Puckaboo2** [comment]
Awesome. Since you are the big Kahuna of race customization and mechanics, your opinion means a lot to me.

That said, I would now like like Fox's and Lemon's approval on these sprites before I go about editing the deformed Unathi sprites.

I would do Vulpkanin, but I think those sprites are considerer too 'new' for a revamp. They don't have deformed sprites or fat sprites... that bothers me.

**Comment by KasparoVy** [comment]
Oh, speaking of fat sprites. You might as well add ` | CAN_BE_FAT` to [**this line here**](url) and add "Unathi" to [**this line**](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/client/preference/preferences.dm#L801) and **[this line](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/client/preference/preferences.dm#L1069)**.

**Comment by taukausanake** [comment]
They really should have fat and deformed sprites. Keep them in line with other species

**Comment by Puckaboo2** [comment]
I would also like to update them to match the quality of the sprites I have right here.

**Comment by Puckaboo2** [comment]
Well, howdy-ho, folks! Here are the very, very final sprites!
[grey after](https://cloud.githubusercontent.com/assets/13158711/22049269/837525aa-dcef-11e6-91ff-4f2ab69ef024.png)
I removed that black spot from the chest.

humans after
I forgot to fix the speck of blush on the female's cheek when she faces the side; it's lighter, now.

skrell after
Skrell stayed the same.

tajara after
I lessened the RGB of the lighter patches on the fur by 10 rgb and I made the ears a bit more saturated and lighter.

unathi after
I don't think I changed anything in Unathi.

**Comment by Spacemanspark** [comment]
wait what

**Comment by taukausanake** [comment]
I was going to ask too. Reopening clean maybe?

**Comment by Aurorablade** [comment]
What happened

**Comment by KasparoVy** [comment]
Probably reopening clean with the before and after pictures all up in the main post.

**Comment by Puckaboo2** [comment]
Exactly. I always have several backups laying around. I might just make a new PR.

**Pull request closed without merging**
