### PR TITLE
Adds *yes and *no emotes to IPCs and other synthetics.

### PR DESCRIPTION
**Pull request by Spacemanspark**
Port of https://github.com/PolarisSS13/Polaris/pull/809
:cl: 
rscadd: Adds *yes and *no emotes to Synthetics. Glory to Synthetica.
/:cl:
Yes, I hooked this up to the cooldown system, so they can't go spamming wheeeooOOOOOP and WHEEOOOoooo noises. As much as that would amuse me.
I'll post a link to the sound files later, but they should be in the prior mentioned PR.
Thanks, and credit goes to @Earthcrusher.
@FalseIncarnate, Can you make sure I did this correctly?

### CODE REVIEW

**Comment by Spacemanspark** [comment]
I hate you too, Travis.

**Comment by ScratKnapp** [comment]
Pasting the links here for laziness' sake.

Yes: http://vocaroo.com/i/s07932xtjXYU

No: http://vocaroo.com/i/s0Y82mLsXpjX

**Comment by Spacemanspark** [comment]
@ScratKnapp Thanks.

**Comment by NTSAM** [comment]
Cute.
:+1:

**Comment by Crazylemon64** [comment]
At some point, we should refactor these kinds of emotes to be defined within species, rather than emote code, or - Oh! Perhaps, we could make datums for emotes, which help define who and what can use them, when!

**Comment by Gummin** [comment]
Glory to Synthetica! :+1:

**Comment by Dumbdumn5** [comment]
Oh Good lord this is wonderful.
Just add this to IPCs when they die. https://www.youtube.com/watch?v=gvsCDMfbu7s or this https://www.youtube.com/watch?v=5CsyGe4F8CQ

**Comment by CrAzYPiLoT-SS13** [comment]
Nah, the Windows shut down sound is better :^)

**Comment by Gummin** [comment]
@Dumbdumn5 @CrAzYPiLoT-SS13 yeah before we know it you'll be able to pick between every windows shutdown sound for each OS for when we die.

**Comment by NTSAM** [comment]
Or you can use the jammed hard drive click of death noise.

**Comment by Spacemanspark** [comment]
Ready for merging whenever.

**Pull request merged**
