### PR TITLE
Update headcrab.dm

### PR DESCRIPTION
**Pull request by dapocalypse**
#8703 
Apparently you have to press f12 to bring the ui back on. This will automatically do this.
If i am yelled at for this i am done.

### CODE REVIEW

**Comment by dapocalypse** [comment]
Compiler did it for me

**Comment by dapocalypse** [comment]
Compiler did it for you

**Comment by Citinited** [comment]
Can you test your code before making a PR please? This adds a single line and CI fails on it.

**Comment by FalseIncarnate** [comment]
This is why using the web editor is frowned upon; you can't compile and test through the web editor.

Your build failed because you are referencing a variable that does not exist on the object you are referencing it on.

**Comment by Fox-McCloud** [comment]
Please stop using the web editor, also stop submitting PRs without testing them or ensuring they compile first.

If you submit PRs after having tested them and ensuring they compile, they will be happily reviewed and analyzed on their own merit; if you continue to submit PRs without testing, compiling, or checking them properly first, then they will be closed immediately.

**Comment by tigercat2000** [comment]
This doesn't even work - changing hud_shown doesn't do shit without the right update procs being called.

**Comment by tigercat2000** [comment]
This needs to be updated or it will be closed.

**Comment by tigercat2000** [comment]
No updates or responses in 24 hours, feel free to reopen this *after* you test it and write working code.

**Pull request closed without merging**
