### PR TITLE
MetaStation V41A II port

### PR DESCRIPTION
**Pull request by tigercat2000**
This PR ports the popular map "MetaStation" from -tg-. Note, this will not replace Cyberiad by any means.

So, for those who do not know what MetaStation is; It is a map developed by -tg- specifically for high population servers. It's idea is to have a more efficent layout than box, which is what the Cyberiad is based off of. Being a -tg- map, it also comes with a number of differences that fit well with our current atmos system.

The basic layout could probably be described as a bit confusing, but efficent. It is also a very large map, occupying a considerably larger portion of the 255255 square than cyberiad does.

The reason I am attempting to port this is due to a few community members expressing interest in it, and I personally quite like the map as well.

Meta probably will not be avalible on paradise central until a significant amount of playtesting and bugfixing has gone into it, and probably not until we can integrate a map voting system into our code.

This is a relatively old image of the map, but the core layout is more or less the same: (from tg git's meta wiki)
credit to tg git wiki

Render of the map as of commit tigercat2000/Paradise@dd9f37f
dmmrender is great
Rest of the z-levels (7 & 8 are empty): http://imgur.com/a/kYoBU#0
would've included z1 on that, but imgur hates me.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Step_x stuff:

$ (! grep 'step_[xy]' _maps/map_files/**/*.dmm)

_maps/map_files/MetaStation/z3.dmm:"ev" = (/obj/item/weapon/stock_parts/cell{step_x = 0},/turf/simulated/floor/plating/airless,/area/AIsattele)

The command "(! grep 'step_[xy]' _maps/map_files/**/*.dmm)" exited with 1.

**Comment by tigercat2000** [comment]
@ZomgPonies Aah, yep, fixed and --amend'ed. Whoops. Should compile now.

**Comment by Robertha89** [comment]
oooh, yes plz I would like to see a slight modification all around to git it to paradise standards or better in all departments, I love the maintanace on this station, and would love to see that expanded, also, you would also need to modify the metastation map to the whiteship, and a few other ships, also ya need to change the centcom map too.

**Comment by tigercat2000** [comment]
Well. Just discovered that git shenanigans flushed the past 12 hours of fixing the map, so, uh, this is.. probably not going to be finished very soon.

**Comment by Finalsong** [comment]
Because I play a grand total of around two jobs, I'm curious as to where you think you'll put the NT Rep's and Blueshield's office? I know it's very far from completion and that's probably the least of your concerns, but I'm curious.
Feel free to tell me to go away

**Comment by tigercat2000** [comment]
@Finalsong no clue yet

**Comment by Iamgoofball** [comment]
@Metacide

**Comment by veganzombeh** [comment]
You could put at least one of the new offices in the spare office. I think the chapel can be moved down slightly to make room for a paramedic garage too. It's been a while since I've played meta though, can't remember the exact layout.

**Comment by Robertha89** [comment]
don't forget the mechanics office, and a few entrances for the pods

**Comment by Metacide** [comment]
Looks interesting, will keep an eye on this. Thanks for notifying me, @Iamgoofball

**Comment by veganzombeh** [comment]
Wow, I'd forgotten how much I'd loved the maintenance areas on this map.

**Comment by tigercat2000** [comment]
Preview
Finally got dmmrender to work again, so here's a preview of it in it's current state.

**Comment by Spacemanspark** [comment]
:+1:  :x: :100:

**Comment by tigercat2000** [comment]
Do not merge tag can be taken off of this. It's not fully player-ready due to balance issues, and the lack of podbays, but the major issues have been dealt with, it's ready to be merged for other people to contribute to.

**Pull request merged**
