### PR TITLE
Removes Goebbles from the last name list

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
As requested by @necaladun

### CODE REVIEW

**Comment by Iamgoofball** [comment]
why?

**Comment by DaveTheHeadcrab** [comment]
@necaladun requested it.
Don't ask me.

Pretty sure it has something to do with this:
https://en.wikipedia.org/wiki/Joseph_Goebbels

**Comment by Iamgoofball** [comment]
removing shit because a nazi happened to be related to it is bad form

if it's blatant intended "lol nazis" then ok sure but this is just a fucking last name

adolf is a common first name still, hitler doesn't have copyright on it

**Comment by Necaladun** [comment]
Goofball, this is an administrative decision. We don't want Adolf Hitlers either. 

This is no concern to you at all whatsoever. Please, stop commenting on issues that don't concern you at all. I'd love to hear your input in coding decisions in regards to technical details, and how they may be better coded, but your input in shit like this isn't needed, or wanted.

**Comment by Iamgoofball** [comment]
I have the right to ask why.

**Comment by Necaladun** [comment]
I've had numerous people speak of their displeasure about your comments on PRs for things that are irrelevant to you, as you are not a player on the server. 

Reading over them, your comments come across as trolling and flamebait.

You're being asked to stop such. If you're interested in the technical side of things, or you want to put your input in - as you just did for how to change it from the host side - that's fine, and welcome. Otherwise, your input is not welcome.

**Comment by Iamgoofball** [comment]
Everything in SS13 is relevant to everything else in SS13.

If a feature gets added at one server, people will want a port to other servers. That feature may attract players of all kinds who like that feature, and they'll either like it at that one server, or they'll want it at a different server. You need to stop thinking that paradise only effects paradise. It effects all servers, even if not directly.

**Comment by Fox-McCloud** [comment]
Since neither of you are going to back down on this and it's just going to end up being a giant post fest with ultimately both of you hating each others guts, I'm just going to lock this now.

**Pull request merged**
