### PR TITLE
Adds a toxic pill sprite, makes the toxin and cyanide pills use it

### PR DESCRIPTION
**Pull request by FreeStylaLT**
A less extreme alternative to #8471.

This fixes the issue of the pill sharing the same exact sprite as salicylic acid and basically anything else. This alternative should give you, hopefully, an immediate impression of the pill not being a regular one. It has a skull and everything.

Beyond that, I think having a dedicated "don't eat this" sprite for a pill can be useful for both chemists and antags, for sorting their own chems or other uses.

img
img

Closes #8471

🆑 FreeStylaLT
add: A dedicated toxic pill sprite, Cyanide and Toxin pills now use it by default.
/🆑

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
I'd nom that.

**Comment by KingPhilipIII** [comment]
Looks tasty.

**Comment by SamHPurp** [comment]
I'd still prefer the pill removed from nukies, but as more people have come out to defend it than comments across github over the preceeding month... I guess its not going away, and this'd have to serve in lieu.

Add `Closes #8471` to your original msg, to automatically close my PR when yours merges.

**Comment by FreeStylaLT** [comment]
@SamHPurp @KingPhilipIII @FlattestGuitar 
Changed the sprite to black
Pics updated

**Comment by Tayyyyyyy** [comment]
Aww the purple one was so pretty 🙁 I really like the idea of semantic pill sprites though, makes a lot more sense than "here's a bunch of random pill sprites".

**Comment by FreeStylaLT** [comment]
img
this was the purple one, for reference

**Comment by KingPhilipIII** [comment]
That looks considerably less tasty. It went from grape to black licorice I object. :thumbsdown:

**Comment by Allfd** [comment]
Could also do yellow lines against the black.  Make it look like a bee with a skull.

Waiting for "IT WAS NOT CLEAR I WAS NOT SUPPOSED TO EAT THE SKULL CANDY!"

**Comment by davidchan13** [comment]
Definitely prefer the purple to the black and white one. Though I do have to admit the pill seems kind of pointless when Nukies already have the implant.

**Comment by Jountax** [comment]
If nothing else I think chemists and whatnot will enjoy having a new pill sprite they can use. Finally one that really drives home the bad idea it is to take floor pills!

Still think the poison pill should be a dental implant though, but that's outside the scope of this PR.

**Comment by tigercat2000** [comment]
👍

**Pull request merged**
