### PR TITLE
Staff of Animation Additions

### PR DESCRIPTION
**Pull request by TheDZD**
Port of tgstation/tgstation#7203, tgstation/tgstation#11244, and tgstation/tgstation#12647. Also makes hostile mob ranged targetting code a little bit less shitty, you now only need to define either a projectiletype, or casingtype, instead of both.

:cl: tkdrg, Delimusca, Aranclanos, TheDZD
add: Gun mimics (including wand, staff, projectile guns, and energy guns) created by the staff of animation will shoot things.
add: Mimics created by the staff of animation now have googly eyes.
fix: Fixes the disturbing lack of death caused by wand of death projectiles.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Oh no you didn't.

AGHHH! 

Yessss, at last. We've talked ab out this for over a year now.

**Comment by taukausanake** [comment]
Those eyes though. Helpful to see something is weird but they're too weird for me

**Comment by TheDZD** [comment]
@taukausanake They're codersprites, as of yet nobody has made any better ones.

**Comment by taukausanake** [comment]
I don't know if you can make anything good for them. I mean what if you animate a cigarette bud? Way too tiny for anything

**Pull request merged**
