### PR TITLE
Emag Sprite Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the emag sprite so it doesn't look like crap---ie: someone who scribbled on a green ID card with MS Paint:

emag

- removes unused broken emag item type.

### CODE REVIEW

**Comment by Earthdivine** [comment]
Eh I prefer the other one, it's obvious at a glance it's an emag while this one looks more like the "scribbled on with crayon" then an emag.

**Comment by Spacemanspark** [comment]
I prefer the one we have SO much.
:-1:

**Comment by theColdflame** [comment]
:-1: The current emag's more identifiable and makes more sense visually.

**Comment by NTSAM** [comment]
:-1: This sprite reminds me of a clown pokemon card.

**Comment by Regen1** [comment]
:-1: just because it's from goon doesn't make it better

**Comment by Spacemanspark** [comment]
I think Fox is porting it from /tg/.
Although it might be used on Goon, I dunno.

**Comment by Spacemanspark** [comment]
Er, originated from Goon.

**Comment by Robertha89** [comment]
Oh hey, thats the other emag sprite, yeah, it looks like a normal id too much.

**Comment by tigercat2000** [comment]
This looks horrible compared to the current emag sprite. :-1:

**Comment by TheDZD** [comment]
I don't particularly like the new sprite either, current one looks fine.

**Pull request closed without merging**
