### PR TITLE
Medical Head Mirror

### PR DESCRIPTION
**Pull request by Quantum-M**
**What does this PR do:**
Adds a medical head mirror. Two added to the white medical clothes locker.

Also edited for Vox, Drask, and Grey, given to their different heads.
**Images of sprite/map changes (IF APPLICABLE):**
headmirror

**Changelog:**

:cl: Quantum-M
add: Medical Head Mirror, two spawn in the white medical clothes closet.
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
So, the only thing it does is have a reflection chance and looks?

I'd at least have it give off some level of light.

**Comment by Quantum-M** [comment]
@DesolateG It's a mirror piece, which is why it reflects. So no actual light source from it.

**Comment by DesolateG** [comment]
Yes, but realistically it was used to focus light at what the surgeon was looking at, making things brighter.

**Comment by Denthamos** [comment]
I feel like it would be better if instead it would reflect lasers while in the head slot, not while held.

**Comment by Fox-McCloud** [comment]
This having an actual impact on gameplay/balance is not good *at all*.

This should be a purely cosmetic item.

**Comment by variableundefined** [comment]
Echo concerns above. No reflect chance.

**Comment by Ty-Omaha** [comment]
It reflects light - if you're in darkness there would be no light to reflect

Also I had no idea that there was a deflect chance, glad it's removed.

**Comment by Nicaragua1** [comment]
changing the thumbs down for thumbs up up after removing the deflect chance 👍

**Pull request merged**
