### PR TITLE
Science Job Homogenization and Test Lab

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Homogenizes the Science Job and Adds in Testing Lab

This received some initial positive feedback on the forums and it wasn't that difficult to makes the changes, so here goes: 

- Axes the Xenobiologist job
- Adds Xenobiology access to Scientist
 - Adds "Xenobiologist" alt title to Scientist
- Increases total science job positions from 5 to 6
 - Increases total spawn positions (what can be joined at round-start as opposed to late-joined) for science job from 3 to 6
- Fixes scientist lockers so they have science labcoats (instead of regular labcoats).

There's really not too many reasons for Xenobiologist to be its own specific job (it was a decision Bay made for unknown reasons); the Xenobiology lab is gigantic and is one of the very research labs that can actually support more than 2 people working inside of it--this also offers more fluid opportunities for scientists to transfer their finds and discoveries from one sub-department to another (maybe the fossil revival machine will finally get used?) 

Test Lab
- Adds in a Testing Lab where Xenobotany is: misc research kinda got lost in the various update of things--this re-adds it; provides an area to test guns, chem grenades, gases, and perform various other experiments on monkies and co-workers a like. Design is heavily based off of TG's testing lab.

Other map changes:
- Moves Xenobotany to where Xenobotany storage currently is.
- Removes the Chem dispenser from the outpost; the testing lab has a chem dispenser which is used more by Xenobotanist and R&D than the Xenoarch, so it makes more sense for it to be in the test lab
- Added a single tile of shuttle wall to the toxin's test chamber so you can see how big bombs are, indefinitely (instead of blowing through the back chamber after 2 tests).

Screens:

testlab

xenobotany

### CODE REVIEW

**Comment by Artorp** [comment]
:+1: 

Sounds good to me!

**Comment by Fox-McCloud** [comment]
Major update to this PR.

Added in a Test Lab (aka the return of Misc research)

**Comment by Markolie** [comment]
Shouldn't use full windows: that's inconsistent with the rest of the station.

**Comment by tigercat2000** [comment]
Agreed with MarkvA, full windows are out-of-place on the station. Other than that, it looks good.

**Comment by Fox-McCloud** [comment]
Will change the full-szied windows, but generally, chamber doors are meant to be glass airlocks--it's been a standard to use glass airlocks for these since forever ago: http://wiki.baystation12.net/images/0/03/Toxins_Lab.png

http://wiki.baystation12.net/images/5/5b/Incinerator.png

**Comment by Markolie** [comment]
Sorry, should've been more clear: I don't mean that they should use the airlock sprite, but that they should act as an airlock (start bolted, and you can only open them using the airlock buttons/controller).

**Comment by Fox-McCloud** [comment]
Updated the windows.

Ahh, yeah, I thought about that, but there's blast doors on the inner test chamber to prevent "oopses" like that (plus I fully admit I have zero ideas how to map in those damn airlock types).

**Comment by Markolie** [comment]
Hehe, I'll take care of it once the PR is merged.

**Comment by Fox-McCloud** [comment]
oki doke!

**Comment by Artorp** [comment]
What about a space vent? Something like the blast door used in xenobio and the incinerator.

**Comment by Fox-McCloud** [comment]
@Artorp 

Would rather it not be *that* powerful; you can use the giant scrubbers in toxin's storage to quickly clear out the gases you potentially put in there.

**Comment by Artorp** [comment]
Fair enough.

**Comment by fj45** [comment]
Right water tank in xenoflora is unmovable without moving trays around. Small thing though.

Also, does misc research remove the maint tunnel around research? Might want to get a zoomed out pic with the mapper.

**Comment by Fox-McCloud** [comment]
@fj45 

Nah, the maintenance is still very much there; there's just not windows from maintenance to peer into the test lab.

**Comment by fj45** [comment]
Also, does research really need two chem stations? If one gets wrecked I would think it wouldn't be hard for research to make another one, and if one chemistry station is removed I could see about reworking the area to be a bit nicer.

**Comment by Fox-McCloud** [comment]
@Markolie 

Requesting a merge; will merge in Dave's immediately after you do.

**Pull request merged**
