### PR TITLE
Verb category changes, telecoms verb fix

### PR DESCRIPTION
**Pull request by Markolie**
Fixes https://github.com/ParadiseSS13/Paradise/issues/5855.

Also removes all verbs currently present in the "Special Verbs" tab to their dedicated tabs as a first step to get rid of verb clutter. All karma verbs were moved to "OOC", all event related verbs were moved to "Event" and all general admin verbs were moved to "Admin".

Also adds logging to the "Check Rune Words" verb (which will soon be removed anyway).

🆑 Markolie
tweak: Verbs have been cleaned up: all karma verbs can now be found under "OOC" instead of "Special Verbs". Most admin verbs have been moved out of "Special Verbs" as well.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
don't add the logging! It means i have to fix another merge conflict! AHHHHHHHHHHHHHHHHH

**Comment by Markolie** [comment]
https://github.com/ParadiseSS13/Paradise/pull/4392 should be merged before this! I believe that PR's ready anyway.

**Comment by GelatinousGlob** [comment]
Do not like, I prefer karma to have its own tab so its not lost in all the other pile of verbs.

**Comment by Markolie** [comment]
And why is that? Do you use the karma check option more than once per round? And do you not right click mobs to give karma?

**Comment by Plotron** [comment]
Context menu karma giving is fukken' unreliable. It's much safer to use the full menu to do that.

Normally, when I'm giving out karma at the end of the round, I'm in a hurry. There's not a whole lot of time at the end of the round.

'Special Verbs' are special because the karma mechanic is AFAIR unique to Paradise. We want people to give out more karma (and new players to notice this and stay on the server too), not less - some people may not even realize what the term 'OOC' entails. Karma being on its own tab is justified, as it's a unique speshiul snowflaek feature. But then again, the 'OOC' tab isn't heavy on verbs, so it's not a huge hindrance.

It's not grouped properly and with the variable size of the verb window (it gets reset when you switch servers) it's practically impossible to memorize locations. Have you noticed that "Auto-Accent" is in the 'OOC' tab, even though it's pretty much all about your IC character? And yes, I do realize that IC tab is mostly about action (say, pull, me, memory access, examine...), but I still found it odd when I found it under 'OOC'.

**Comment by Markolie** [comment]
The verbs tabs are a mess in general and really needs to be cleaned up. Perhaps I'll grab that as part of this PR then to make sure everything's consistent.

**Comment by Crazylemon64** [comment]
@Markolie Are there plans to further this PR?

**Comment by Markolie** [comment]
Not sure, I'm unsure what the overall feeling for the verb changes is.

**Comment by GelatinousGlob** [comment]
Im all for some verb reorganization but I think karma should still be relatively isolated for easy of use. I wouldn't mind if a few more things got added to the karma tab but moving the karma options into already convoluted tabs seems like a downgrade. There are tons of options that get pressed maybe once a month mixed in with verbs I might use multiple times a round.

If anything I would say we need more tabs, not less.

**Comment by Markolie** [comment]
Aight, karma has its own tab now. At least special verbs is still gone.

**Comment by Crazylemon64** [comment]
[boop](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/gameticker.dm#L414)

**Comment by Markolie** [comment]
Karma's back on the "OOC" tab - the maintainers and headmin discussed the changes, and felt like karma does not need its own tab.

Once the freeze is over (and if I remember and have time) I'll work on axing more verbs. For instance, a dedicated NanoUI screen for all preference toggles instead of verbs.

**Comment by Lady-Luck** [comment]
There has been an extremely noticeable lack of karma being doled out ever since this PR was pushed. I think this part of the PR should be reverted.

**Pull request merged**
