### PR TITLE
*flip

### PR DESCRIPTION
**Pull request by Fox-McCloud**
*flip

flip

flip2

### CODE REVIEW

**Comment by TheDZD** [comment]
I can see people complaining about this already because of MUH IMMERSHUNZ, or because it's a thing from Goon. 
:+1: x  :100:

**Comment by tigercat2000** [comment]
:-1: until people that *flip in lockers gain brain damage from hitting their heads. Then it will be :+1:. 
:P

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Markolie** [comment]
:fried_shrimp:

**Comment by Fox-McCloud** [comment]
:walking: :arrow_right: :arrow_upper_right: :arrow_up: :arrow_upper_left: :arrow_left: :arrow_lower_left: :arrow_down: :arrow_lower_right: :arrow_right:

**Comment by Glloyd** [comment]
Do a flip.

**Comment by fj45** [comment]
Well damn.

**Comment by Flip-Sandwich** [comment]
Oh my god

**Comment by ZomgPonies** [comment]
I actually really like Tigercat's idea. Can you add that in?

**Comment by Spacemanspark** [comment]
Just don't have a cooldown on it.
FLIPPING ALL DAY ERRY DAY.

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

There was actually a few other things I was wanting to do with this, but, for now, I just wanted it to be a plain old emote--with the other potentially added in later.

**Pull request merged**
