### PR TITLE
Kills Check Pulse

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
You know that check pulse verb that's been in the right click menu for however long? You know, the one that's visible even if you're a ghost?

This removes that.

## Why It's Good For The Game
It's almost something worse than useless? It gets in the way and clogs up the right click menu on every mob.
Good riddance.

## Testing
image

## Changelog
:cl:
del: Removes "Check Pulse" from the right-click menu
/:cl:

### CODE REVIEW

**Comment by spacegeese** [comment]
how am i gonna check if the dude who got weekend at bernies'd is alive now??? /j

**Review by Henri215 — APPROVED** [review]
The check pulse is dead!

**Review by Sirryan2002 — APPROVED** [review]
KILL IT, DIE!

**Review by Contrabang — CHANGES_REQUESTED** [review]
can you alter `/mob/living/carbon/proc/get_pulse(method)` to remove the method param? This is the only case of the param being used differently

**Review by S34NW — APPROVED** [review]

**Comment by YoureNotTheSharpest** [comment]
Man i laughed my ass off when i seen a baldie see me horizontle ricght clicked and checked my pulse to read it is 0 and they drag me (afk) to medbay thinking im dead

**Pull request merged**
