### PR TITLE
Admin Log Tweaks: Trialmin Visibility, Toggling, Spam Reduction

### PR DESCRIPTION
**Pull request by Krausus**
As far as I can tell, "admin log" messages were originally intended to be logs of admin activities, only visible to high-ranking admins with +SERVER, so they could easily see and judge the actions of lower-ranking admins. Unfortunately, some important notifications about player activity - setting bombs, opening hazardous gas canisters, etc. - were added in using admin logs, which is *mostly* fine, since *most* admins have +SERVER now. The noteworthy exception is trial admins, who may need to deal with such events, but don't actually get notified about them.

Rather than sift through and correct every non-admin admin log, this PR simply lets all admins see admin log messages. The only downside is that they can see what other admins are doing, but it's probably better for them to be aware of that stuff anyway.

And, just in case they (or any other admin) *don't* want to see that stuff, I've added a new "Toggle Admin Log Messages" preference to shut 'em off. I've added it as a "not" flag, so it defaults to on without us having to muck with the existing preferences in the database.

Finally, to reduce the unnecessary admin log spam a bit, I've disabled the messages for ghosted admins jumping around, since moving around as a ghost really doesn't bear mentioning. This **only** applies to ghosts (admins in control of living mobs still generate messages), and **only** to the messages (even ghosts still generate entries in the log files).

Since this PR affects admin privileges, I'll need @Earthdivine and @Necaladun in here to pass judgment on the changes.

:cl:
tweak: All admins can now see "admin log" messages.
rscadd: Admins can now toggle "admin log" messages on or off.
tweak: Admins will no longer be notified about ghosted admins jumping around.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
>And, just in case they (or any other admin) don't want to see that stuff, I've added a new "Toggle Admin Log Messages" preference to shut 'em off. I've added it as a "not" flag, so it defaults to on without us having to muck with the existing preferences in the database.

Thank goodness.

**Comment by Kyep** [comment]
I suppose this, because:
- Being able to see notices about explosions, opening dangerous gas canisters, etc is very helpful for trialmins, whose primary responsibility is rule enforcement.
- Being able to see admin logs in general is also very helpful for trialmins. Trialmins primarily learn through watching what fullmins do. Having greater insight into what fullmins do will help trialmins learn.
- Transparency is good. Admins should be able to see what each other are doing - regardless of their rank. It helps avoid two people dealing with the same situation in different ways. It promotes consistency in team actions. It makes teamwork easier.
- Getting notices about ghosts teleporting is pointless.

**Comment by Tastyfish** [comment]
>> And, just in case they (or any other admin) don't want to see that stuff, I've added a new "Toggle Admin Log Messages" preference to shut 'em off. I've added it as a "not" flag, so it defaults to on without us having to muck with the existing preferences in the database.

> Thank goodness.

**Comment by Necaladun** [comment]
QoL. Thanks, this is great.

**Comment by Earthdivine** [comment]
You already talked to me about it in staff chat, not much else I can put here other then for logging purposes.

**Pull request merged**
