### PR TITLE
Plasmameme fluff

### PR DESCRIPTION
**Pull request by Shadeykins**
**What does this PR do:**
Given the big 👌 by our resident Cowboymin PurpleGenie for many sleepless nights spent ruthlessly bullying mentors until they gave the staff team their lunch money (thanks for the pizza party, nerds).

It's a suit. It's pink. It has a tabard/skirt thing going on. 

It sparkles when you turn the lamp on.

Works via a single-use conversion kit in the bag that respects existing stats on plasmaman suits/helmets. After being used once on a helmet/suit, it becomes useless.

**Images of sprite/map changes (IF APPLICABLE):**
image
h1 inhands1

**Changelog:**
:cl:
add: fluff item for Star-Scattered Sky
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Give me back my lunch money

**Comment by taukausanake** [comment]
I like it. Needs more sparkles

**Comment by Exavere** [comment]
It's. . . . IT'S. . . . BEEEAAUTIFUUUUUL *HERRRNGH* I LOVE IT XD.

**Comment by KasparoVy** [comment]
🤔

**Comment by taukausanake** [comment]
What happened?

**Pull request closed without merging**
