### PR TITLE
Lavaland: Add "official" Boss Arena to lavaland

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
Add "official" arena for boss fights, with can be located far north in front of necropolis as sort of ancient arena where people fought with fauna for "lords" entertainment, now its remains of old times with can be used by miners

## Why It's Good For The Game
Add "official" arena for fight, before it was under outpost (at least what people use this large space for, to fight fauna) with remove sometimes issues where someone fight fauna there, dies, and enraged fauna just attack random passby person, with even didn't see fauna but fauna saw them, now it will be less "risky"

## Images of change
Close image of arena before adding "no_lava" helper:

<details>

</details>

whole map photo:

<details>

</details>

## Testing
Run VSC and didn't got errors from running it.

## Changelog
:cl: Venuska1117
tweak: Add "official" boss arena to lavaland and move empty space below outpost further away.
/:cl:

### CODE REVIEW

**Comment by Qwertytoforty** [comment]
That should use the mapping lava turf to match the rest of lavaland, rather than always being lava. Looks nice however!

**Comment by DGamerL** [comment]
Agreed on both of Qwerty's points, indestructable walls is a recipe for disaster usually

**Comment by Qwertytoforty** [comment]
Also probably should not remove the open space under the mining base 2 as a second fighting spot / open area

**Comment by Venuska1117** [comment]
All request granted, now walls are destructable and drop runic metal, helper was used for lava and its covered in no_lava helper.

And yeah, added new rock type to protect it from gibonite exploding more than necessery.

**Review by Sirryan2002 — APPROVED** [review]
approved for code

**Review by S34NW — APPROVED** [review]

**Pull request merged**
