### PR TITLE
Gives Permability Coefficiency to all spacesuits

### PR DESCRIPTION
**Pull request by Robertha89**
Also creates a base file to modify all spacesuits from.

This will make fighting blob less of a nightmare, still a nightmare, but less of one.

### CODE REVIEW

**Comment by TheDZD** [comment]
Currently not all spacesuits, just the captain's spacesuit.

**Comment by Robertha89** [comment]
Might fix being able to cryo people with spacesuits. maybe, dunno.

**Comment by Fox-McCloud** [comment]
- There's already a base files for all space suits and the Captain's space suit
- All space suits have a permeability coefficient already and is almost never overridden in any case.

**Comment by Robertha89** [comment]
Huh, what do you know, could not find it in search for some reason, why is the coefficience .02 instead of 0?

**Comment by Fox-McCloud** [comment]
for all intents and purposes, it is effectively 0.

**Comment by Fox-McCloud** [comment]
Going to go ahead and close this.

**Pull request closed without merging**
