### PR TITLE
Cyberiad: Rework Janitory Room (and Swap some Rooms in Process)

### PR DESCRIPTION
**Pull request by Venuska1117**
Originally Idea was to Swap Toilets with Janitor, but when i was actually going for it, i noticed that janitor need access to maintenance, so after longer thinking, i swapped janitor for cryo, and cryo for toilets *(toilets are in janitor place)*, after asking on discord, they said cryo is "too good spot" with make me think about placing it again... with end up this way...

I have no idea how to do it more fitting, i messed it more than i wanted...

## What Does This PR Do
Swap Rooms, because it went south more than expected.
**Before -> After:**
Barber Room -> Cryo Room
Cryo Room -> Janitor Room
Toilets -> Barber Room
Janitor Room -> Toilets

Swapped:
Cryo with Arcade.

## Why It's Good For The Game
Now Janitory Have more space and gear, so now its not for One Janitor, but for Two now.

## Testing
Run Code, checked if packages go correctly to janitorial, everything look fine.

## Changelog
:cl: Venuska1117
tweak: Swapped 5 rooms, Janitor, Toilets, Barber, Cryo and Arcade with each other, Janitory now is bigger and made for 2 Janitors.
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Based on the pictures, it looks like you left the barber's pole on the wall next to cryo.

**Comment by Venuska1117** [comment]
> Based on the pictures, it looks like you left the barber's pole on the wall next to cryo.

ye i noticed that, it got removed, but thanks for sayin.

**Comment by Screampuff** [comment]
> I think Janimobile should remain a singularly unique thing. Otherwise its powercreep, and reinforces the meta. Theres already lots of jani gear in the maints, including another cart and mop bucket. We should just stick with current amount.
> 
> All the other maps only have one janimobile. Painting having scarce items as being made for only one janitor assumes they'd all be horded by a single individual, really disagree with altering game design to reward bad behavior.

Farragus has two janicarts.
image

**Comment by SynthTwo** [comment]
some love for barber finally. we don't get a small lil room.

also i am unsure about cyberiad having two janicarts, i mean it WOULD make cleaning more proficient cause crew DESPISE mopping, but it's also so easy to clean with janicart. but then again, farragus DOES have two janicarts, and i never seen anyone complain about it.

**Comment by Christasmurf** [comment]
There's two mops in the new room, right? On some maps while I was adding the vendors I noticed that some maps have two of the mop carts, but only one mop, which kinda makes one of the carts just a waste of space in an already cramped room.

**Comment by Venuska1117** [comment]
> There's two mops in the new room, right? On some maps while I was adding the vendors I noticed that some maps have two of the mop carts, but only one mop, which kinda makes one of the carts just a waste of space in an already cramped room.

Yes in my one i added 2 mops and bucket, because i tough its strange there is only one of each

**Comment by Git-GoR** [comment]
Right, some issues and comments:

### Engineering
- Intercom and camera on top of this engineering airlock. Both should be brought to their original locations higher up on the hallway, check mapdiffbot for the exact tiles. You've also moved that scrubber/vent pair... which I guess is okey.
imagen

### Restrooms
- Showers in the same room as toilets? And the other room only for sinks... I find it a bit strange, but maybe in the future people are not as prude.
- Urinals are gone, which considering how useless and ugly they are nobody will complain about it. But just in case you were not aware of it.

### Barber room
- Barber room lacks an Air Alarm. Although old barber room also lacked one... whack.
- Rogue door control button in barber room, not linked to anything.
imagen
- Room looks a bit blocky and by making it bigger, the dorms hallway is now even longer before any geometry change occurs. I would however have to play on the map to see if it's that bad. Maybe making the room less of a rectangle would make it more visually appealing, but I admit it might be a bit too claustrophobic. Just a thought.
imagen

### Janitor closet
- Uses var-edited airlock access, but I believe this will no longer be an issue as all maps will be batch modified in the future.
- The navbeacon for the mulebot has the wrong `dir`, making it unload right under the flaps rather than the intended floor. Instead of `8` (west) it should be `2` (south), which is the default dir for all atoms.
- Holopad is missing.
- APC has a celltype of `25000` which is  the one given to the SM room. Please leave at the default `2500`.
- Scrubber is no longer under the table, which I believe was one of those "hidden vents" that gives ventcrawling antags an advantage so not all are welded easily. @S34NW would know more.

**Review by Git-GoR — CHANGES_REQUESTED** [review]
See requested changes above.

**Comment by Venuska1117** [comment]
If someone ask about "who made this toilets"
(https://www.bing.com/ck/a?!&&p=d8ac110782103906JmltdHM9MTY4ODE2OTYwMCZpZ3VpZD0wMDk4MDE3YS05ZjFkLTZhZTQtMDA1MS0xMzFhOWUwZjZiODgmaW5zaWQ9NTY0MQ&ptn=3&hsh=3&fclid=0098017a-9f1d-6ae4-0051-131a9e0f6b88&u=a1L2ltYWdlcy9zZWFyY2g_cT15b3UgaGF2ZSBvbmUgam9iIG1lbWUmRk9STT1JUUZSQkEmaWQ9RkQ3NEUyQkQzM0ZFRkE5NkIxMTRBMTNBODdFOTA1RjU3RjQ0MDYwRg&ntb=1)

**Review by S34NW — CHANGES_REQUESTED** [review]
image
This layout is a bit awkward, you'd be better off moving the far right row to be "back to back" with the middle row, and making the numbers even.

image
This camera is no longer in dormitories.

**Comment by Venuska1117** [comment]
> image This layout is a bit awkward, you'd be better off moving the far right row to be "back to back" with the middle row, and making the numbers even.
> 
> image This camera is no longer in dormitories.

image

image

Didn't have idea for camera name, so i made it "Toilets"
image

**Pull request merged**
