### PR TITLE
Port TG Sechud Icons

### PR DESCRIPTION
**Pull request by Kyep**
## What Does This PR Do
Ports TG's better sechud icons, and updates other job icons (like magi, blueshield, etc) to be consistent with them.
For example::
1. Cap/HOP/CE/CMO/RD/HOS/NTR/Magi icons are now in command's color, dark blue.
2. Scientist/Robotocist are now science purple.
3. MD/Paramedic/Psych/Viro are now medical light blue.
4. Geneticist is now half med light blue, half sci purple.
5. QM/CT/Miner are now cargo brown.
Also changes the health hud icon in the same file to TG's version (which isn't a red cross).
And tweaks some icons so they're easier to tell apart (e.g: CMO versus MD) or less like alert icons (RD/Scientist).

## Why It's Good For The Game
1. Consistency. All command jobs have blue icon, all medical jobs have cyan, all science have purple, etc. Instead of the current haphazard mess where sci is blue, command is yellow like eng, etc. Essentially, all jobs' icons now match their department color scheme. Even cargo now has brown cargo-themed icons.
2. Readability/intuitveness. E.g: all blue-background jobs have bridge access, magistrate has IAA legal icon but in command blue, NTR has "NT" icon instead of a weird "C", etc. No more CE and engineer having almost identical icons. This icon set should be much more readable and intuitive.
3. Removes warcrimes. No more red crosses on job or health icons.
4. Reinforces the authority of jobs like Magistrate, which are now properly identified as command-level jobs.

## Images of changes
At the bottom.
See where it says: "Diffs - Pull Request #13933 Successful in 8s — Icon Diffs "
Click "Details" to the right of that, then click on the "icons/mob/hud.dmi" filename.
That already provides a side-by-side comparison.
Summary:
icon_summary2

Health icon:
medical-healthhud

## Special Cases
1. Captain uses a "C" on blue, because I feel it is better than TG's star icon.
2. Psych uses the same light blue background as the other medical jobs, because I feel psych is a medical job, not a service job. TG's psych icon treats it as a service job.
3. Geneticist colors are split half and half between med and science, just like the job is. On TG, icon is all purple as geneticist is an all-science job.
4. NTR uses "NT" on blue, as TG has no NTR, and the individual letters "N" and "R" are taken by other status icons.
5. Magi uses a command blue version of the IAA sprite, because Magi is command. TG has no magi.
6. Xenobiologist (yes, I know the job was removed, but maybe we'll use it again someday) is converted to purple.
7. NT Recruiter and Ambassador icons have been removed due to being poor quality (ambassador is just a copy of assistant) and I don't expect them to ever be used again.
8. IAA hasn't been changed to the green icon TG uses, since here, they're considered part of security.
9. HUD icons for ERT haven't been ported from TG. I'm not sure I want to use them in this PR.
10. Blueshield becomes literally a blue shield icon. TG doesn't have BS.
11. imp_unknown (an unused sprite for unknown implants) is deleted, because aside from being unused, its also inconsistent with the other implant sprites, both in terms of look, and in terms of placement. If we ever need a new implant hud sprite, we can make a new one that's better than this.
12. RD/Scientist use McRamon's "microscope" sprites, as I feel those say "science" more clearly than the weird exclamation point sprites that we/TG currently use.
13. Brig phys colors are inverted, and all other icons that used to use a red cross on any background are updated. (health hud to TG version of blue on white/gray)

## Changelog
:cl: Kyep
add: Ported TG sechud icons for many jobs.
/:cl:

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Before/after images please

**Comment by taukausanake** [comment]
> Before/after images please

Same here. IconDiffBot is fine and all but we deal with small icons. It's not too much to ask for putting in a little more work

**Comment by Kyep** [comment]
@ZomgPonies @taukausanake Summary screenshot added.

**Comment by AffectedArc07** [comment]
> Before/after images please

This is like the one time IDB has ran properly. Use it while you can.

**Comment by shawnhind** [comment]
I really like the colour consistency and such.  However, I do think I like our current security officer icon better than the new one. Previously it looked like a gun/tazer.  Now it just looks like a weird blob and I'm not sure if it's supposed to be a beret or a gun but it doesn't really look like either. Just my opinion.  I'd love it if we could keep the old icon but with the consistent colours for command

**Comment by Kyep** [comment]
@shawnhind This PR does not change the sec officer icon.

**Comment by shawnhind** [comment]
@Kyep 
Sorry I might be confused.  Aren't the icons in the description of the PR the new icons?  Doesn't our current sec officer icon look like a gun and you can see a space with a trigger?  I don't see that on the icon in the PR description.  Am I misunderstanding?

**Comment by Kyep** [comment]
@shawnhind 
Originally the image I put in the PR description had only changed icons. However, Ramon was kind enough to do me a new image that had changed + unchanged icons together in one image so you can see how everything fits together. So now, I'm showing that.
If you want to see *only* what is changed, use the icon diff link explained above. It lists only changed icons, and shows before/after for all icons.
No, the security officer icon is not changing.
The only sec department icons that change are the HOS icon (which becomes like the current sec officer icon, but in blue) and the brig phys icon (which becomes a white cross on a red background, instead of the red cross).
Most of the command job icons simply are an icon from that department, but in command blue. The exceptions are icons like the CMO, where the graphics of the icon are exaggerated a bit so its easier to tell the difference between say, CMO and MD.

**Comment by shawnhind** [comment]
@Kyep 
I still don't understand, when I look at the diffs I see the two icons below

This is reported as the "old" Hos Icon:
https://camo.githubusercontent.com/1ccb64313b0f91429725096613ee538340902cc1/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f32373238363435322f3931333533323133372f31342f6265666f72652e706e67

This is reported as the "new" HoS Icon
https://camo.githubusercontent.com/4659e0c38856cf76fc4dd8fa5d8579edcb32e385/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f32373238363435322f3931333533323133372f31342f61667465722e706e67

Those are two different icons that differ by more than just colour and the second one is different from the current sec officer Icon by more than just colour.  I might just be completely lost, don't worry about it.  Sounds like the intention is to keep the same sec officer icon anyways which it sounds like what's being done.

**Comment by Kyep** [comment]
@shawnhind Thanks for the detailed report.
I've identified the issue, please check the image in the PR description now, it should match what you expect.

**Comment by shawnhind** [comment]
@Kyep 
Awesome, can't wait for these new icons.  Such a huge improvement

**Pull request merged**
