### PR TITLE
Faster atmospheric pda atmospheric scan refresh rate. 

### PR DESCRIPTION
**Pull request by Jey123456**
This is a small tweak to the atmospheric cartridge giving it an atmospheric scan refresh rate of 1 second instead of the current 10 seconds.

### CODE REVIEW

**Comment by Tastyfish** [comment]
I'd bet most people weren't even aware it did refresh without reopening it.

**Comment by Jey123456** [comment]
well, i most certainly was since i keep it open 99% of the time on a secondary monitor when im atmo tech XD.

**Comment by Fox-McCloud** [comment]
Not sure if this is a good idea or not; NanoUI is a bit expensive when it updates repeatedly--we've cut down on refresh rate before...and well; the question is do atmostechs realllllyyy need it to update this frequently?

**Comment by Jey123456** [comment]
its only on atmo tech who have the pda open so the cost should be pretty much close to 0 (unless we do an event with 50 atmo tech on board offcourse)

Especially with linda being very slow at equalising gas in room, being able to quickly see the status of a room by moving around it is a great tool to have for atmo tech.

**Comment by FalseIncarnate** [comment]
All PDAs actually have a basic atmos scan function if memory serves. The atmos cartridge allows you to scan tanks and canisters.

Additionally, almost every blue toolbox has an often ignored device called an analyzer, which scans the air on use (making it ideal for on-demand/frequent checks), which I believe tends to be more detailed reporting anyways.

I can support increasing the refresh rate, but maybe drop it to every 5 seconds or so. Keeps the analyzer as ideal checker, but makes the PDA more viable for basic things like pressure checking.

**Comment by Fox-McCloud** [comment]
I really don't think this is necessary; it's not hard to re-open your PDA or, even better, carry around a scanner, as @FalseIncarnate has suggested.

**Comment by Jey123456** [comment]
thats exactly my point on atmo having the gas checker. Atmo only has gas checker. Science has gas checker, reagent scanner, signaler system so why should someone ever use the atmo cartrdige ?

**Comment by Jey123456** [comment]
i did not know about that hand scanner, but its even less usefull than the pda xD. 

not sure who in their right mind would ever use that thing since it clog your chat and also imply clicking every step you take to check the area.

I'm not sure why your so convinced that the nano ui refresh rate is a problem on such a small scale. Id fully understand if we were talking on every single pda window. But were only talking about 1 page of a very limited population of pda

**Comment by FalseIncarnate** [comment]
> not sure who in their right mind would ever use that thing since it clog your chat, provide no extra infos and also imply clicking every step you take to check the area.

Literally any atmos tech worth their salt is going to know the analyzer is ideal for performing atmos checks on local conditions, AND that it can read the contents of canisters and such much like an atmos cartridge PDA. It's faster to update, provides the same information without requiring them to switch focus between the main screen and the PDA interface, is not subject to NanoUI blank-outs (though those have largely been corrected, not sure if anyone still gets them), AND can be utilized to deal with any anomaly that may pop up on station (especially the pyroclastic anomaly, aka sudden plasma fire event).

The only advantage the PDA one has is that it auto-refreshes. Nevermind that you can't do anything else with your PDA while that's open, and for people with one screen (yes, they still exist even in this day and age, those poor souls) you lose a chunk of your screen space to the UI.

Again, I can support reducing the time for the update, but 1 second updates are excessive.

**Comment by Jey123456** [comment]
well, i dont know about you, but for me, its the same time to get a refresh manually on the pda by pressing on it, and clicking on the air analyser, only difference is, air analyser completely clog up your chat if you use it more than once whereas pda remain clean and faster to read at a glance thanks to the coloring (not to forget inventory space). 

For me at least, 5 seconds is no different than 10seconds, its still too slow to be of any real use (not to mention 5 seconds is not possible in our case, since the nano ui are checked every 2 seconds, it would be either 4 or 6). Why bother with a refresh at all if its such a long time ?

As far as I'm concerned, atmospheric as a job need some love and that specific pull was something me, as someone who've been playing atmo tech for most of my ss13 playtime (which while recent on paradise, is not so recent on ss13 in general) would have found useful to reduce the annoyance of atmo. 

But at the end of the day, its not up to me, so feel free to just close the request and ill keep working on other stuff.

**Comment by FalseIncarnate** [comment]
So based on what you are saying, even your refresh rate of 1 second wouldn't be possible, as the UI updates every 2 seconds, causing the system to attempt an update twice before actually displaying it.

4 or 6 seconds is fine. I just said 5 since it was the middle-ground number between 1 and 10.

Yes, atmos needs some love, but most of the issues with the job are not the tools but rather the applications of which a non-antag atmos tech is allowed to utilize atmos for. I have played atmos quite extensively under both ZAS and LINDA, and am familiar with the pros and cons of both systems as a result of that experience. Under both systems, the tools were rarely an issue, so I don't think that it's the mechanics and applications of the job are what need the love more.

Additionally, you could argue that the spam of an analyzer is less impacting than that of medical's health analyzers. I'm not suggesting you just throw this away, but rather that you take our advice and feedback into consideration. The goal is not to shut down potential changes, but rather to ensure that they are balanced both from a gameplay and performance standpoint, as well as that they are as beneficial to the codebase as we can hope to refine them to be.

**Comment by Jey123456** [comment]
if you check the code, thats why i had a lil hack in place to attain the 1 second update. updating at every cycle is easy, updating every 2.5 cycle is a bit more hacky :P. 

on the medical analyser side, they at least get a pretty hud google thing to quickly see at a glance who is hurt and who is not. All atmospheric get to see the state of a room beyond whats right in front of the air alarm, is the atmo scan spam.  Its also pretty much the only way to track down hidden breaches under some doors and objects.

**Comment by Jey123456** [comment]
how about this then, when an atmotech has the atmo scan open on pda and an air analyser in hand, the pda update every seconds, rest of the time regular update time ?

**Comment by FalseIncarnate** [comment]
Hacky code, from a code maintainability standpoint, is less than ideal.

I'd say have it normally update every 4 seconds (2 nanoUI refresh cycles). If someone needs more frequent updates, then they can manually update or use a handheld analyzer. The vast majority of issues don't require such fine-precision updates, and the few cases that do are hardly the standard fare for an atmos tech's routine work.

**Comment by Jey123456** [comment]
well, its hacky code no matter what we do, since atmospheric scan is not an application on the pda, its a default option available on all pda. I could take 2 seconds, but 4 mean you still have to spam most of the time when you need it. As for standard fare, i could argue since i have to spam that damn thing at least twice a round, except offcourse round when absolutely nothing happen and i just get to walk around bored xD. Whenever theres air leak or increase that make no apparent sense.

**Comment by FalseIncarnate** [comment]
I mean make it act the same for all PDAs. The atmos cartridge doesn't necessarily require it's own unique functionality (though if you were intent on giving it something special, I'd say make it a more detailed read-out, like showing the number of moles of each gas present in addition to stuff like temp and pressure as opposed to just percentage composition).

I suppose whether or not your experience is truly standard or not would depend on how often other atmos techs (or just people with PDAs in general) find themselves in need of updated atmos scans from the PDA. As for myself, I normally make sure to carry around the handheld analyzer anyways to address the potential anomaly, as an atmos hardsuit makes me typically better protected from their effects than a scientist, so I rarely utilize the atmos scan of the PDA for anything other than checking canisters and such.

**Comment by Jey123456** [comment]
so wait, earlier there was a performance worry about making it every second for only a very small subset of the population (about 5% of the players in a round) , and now it would be "ok" to make it run every 4 seconds for 100% of the population ?

**Comment by FalseIncarnate** [comment]
First off, I'm not the one who was expressing the concerns regarding performance initially. However, as 4 seconds would fall on a natural nanoUI refresh anyways, and would still not be every cycle, I don't think there would be a large enough increase in overhead to warrant concerns. Fox would know better than me though.

As for giving it to everyone and not just atmos, that is more to avoid placing a snowflake check into a common section of code for only one cartridge (well, maybe 2 because of the CE, not sure how those are all defined off hand).

**Comment by Fox-McCloud** [comment]
This isn't acceptable in the snowflaked manner its handled here.

**Comment by Fox-McCloud** [comment]
Closing this due to the above and lack of updates.

**Pull request closed without merging**
