### PR TITLE
Fix disposals so the recycler will actually receive stuff flushed via disposals

### PR DESCRIPTION
**Pull request by SkullyRoberts**
Added reinforced windows along the conveyor leading between the disposals output and the recycler.
This fixes the bug where things flushed into disposals launches diagonally and misses the recycler entirely.

screenshot 7

### CODE REVIEW

**Comment by IK3I** [comment]
You may want to rebase your history so it's just the actual pr commit. Also, the map merge tool should be used any time you edit the map. It's in /tools and is pretty straightforward to use. Just prep prior to edits, then run the tool after edits. You can checkout the earlier version of the map to get your backups as well so you don't have to dirty up your history.

**Comment by Citinited** [comment]
1. what IK3I said, also you need to clean your branch so that you don't have so many leading merge commits
2. you should check that your branch is up-to-date before working on anything map-related so that you don't accidentally commit something that overwrites newer stuff that people have done to the map
3. what if you aimed it at a wall instead of adding glass windows (either by rotating it or adding an L-shape to the disposals room)?

**Comment by SkullyRoberts** [comment]
@FreeStylaLT yes, it does eventually shatter. This is a short term commit while I decide how to properly redesign disposals so it'll work.
@Citinited 1) Sorry, I forgot to rebase. 2) I updated immediately before doing the map edits. 3) That is the plan, but I'm trying to decide on a design that doesn't make disposals any larger.
@IK3I I honestly had no idea that existed. This is the first time I've done a map edit PR for any SS13 branch. Thanks! <3

**Comment by SkullyRoberts** [comment]
Eh, I just did the actual fix. So I'm gonna close this PR and PR the better version.

**Pull request closed without merging**
