### PR TITLE
Alt Account checking

### PR DESCRIPTION
**Pull request by ZomgPonies**
Thanks to https://github.com/Spoffy/LLA-Station-13/pull/280

Allows admins to easily check for alt ckeys using both IPs and computerID.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by Spacemanspark** [comment]
:-1: Now my epic VPN haxors will be busted!

:+1: :+1: :100:

**Comment by TheDZD** [comment]
:+1: * :100:

**Comment by SamCroswell** [comment]
Sounds amazing.
Will we then be able to ban based on computerID?

**Pull request merged**
