### PR TITLE
Makes coffee non-addictive.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattestGuitar
tweak: makes coffee non-addictive
/:cl:

Come oooooooon.

Most people that drink coffee will drink it for the RP value. If you genuinely drink it to reduce stun times you'll have a really large supply on your hands anyway and it's very likely you won't even get the addiction to trigger with the current 1% chance.

As per [this](http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=8215) thread, where everyone agreed it's silly.

### CODE REVIEW

**Comment by tigercat2000** [comment]
changelog

**Comment by FlattestGuitar** [comment]
*Shh*

**Comment by Lady-Luck** [comment]
hitler tier

**Comment by Iamgoofball** [comment]
salt_pile
www narconon org_drug-abuse_using-bath-salt
bigstock-sea-salt-34380128
salt

**Comment by Spacemanspark** [comment]
Lmao

**Comment by FlattestGuitar** [comment]
This PR is actually based on a true story that happened. 

I was ERPing the AI in maint, while getting absorbed by the chef, when all of sudden a xeno nukie vampire jumped the three of us. I completely robusted the nukie, not breaking off the session with the AI and just as I was about to thrall him I dropped to the floor because of a coffee addiction and he killed me and took over with the AI. 

😢

**Comment by Fox-McCloud** [comment]
img

**Comment by AceMcLazer** [comment]
@Fox-McCloud Good lord, man you took this picture, didn't you?

**Comment by Fox-McCloud** [comment]
@AceMcLazer 

Actually, no---I found it, of all things. I don't drink coffee.

**Comment by AceMcLazer** [comment]
I don't know why, but that felt like that would have been a Fox thing to to. "Ruin a cup of coffee but make a hilarious picture. worth it". Hey maybe i'm wrong :laughing:

**Comment by FlattestGuitar** [comment]
So, uh.

Anything?

**Comment by Lady-Luck** [comment]
"This branch has conflicts that must be resolved"

**Comment by FlattestGuitar** [comment]
*sigh

**Comment by Iamgoofball** [comment]
:-1: This is removing fun and interesting game mechanics because of a single salty player.

**Comment by Spacemanspark** [comment]
That's nice, Goofball.

**Comment by Plotron** [comment]
Remove pliz.

It's almost as bad as emag random fail chance, no?

**Comment by Lady-Luck** [comment]
Usually one puts sugar in coffee, not salt :^)

**Comment by Fox-McCloud** [comment]
>Usually one puts sugar in coffee, not salt :^)

Or clouds. :cloud:

**Comment by Fox-McCloud** [comment]
Not a big fan of this, Flattest; the chance of this happening for drinking a full cup of coffee is roughly ~10% (and that's if you drink 50 units) and it is a combat chem---not to mention it is rather hilarious to see someone RPing a total coffee addict.

**Comment by FlattestGuitar** [comment]
But it's coffee.

:coffee: doesn't make people do the things it does in spessmen...

it...makes...no...sense....

**Comment by Lady-Luck** [comment]
I kinda wish there were addiction thresholds, in which addiction doesn't have a chance to roll until you pass that threshold.

**Comment by Fox-McCloud** [comment]
Just going to go ahead and close this. The change doesn't seem popular, and the chance is sooo low, that it's not like it used to be where drinking a cup of coffee = addicted every time. Closing this.

**Comment by FlattestGuitar** [comment]
You monster.

**Pull request closed without merging**
