### PR TITLE
Replaces the Asteroid with "Water World"

### PR DESCRIPTION
**Pull request by SkullyRoberts**
What is water world, you ask?
It is a modified version of lavaland that I ported over. This is the absolute basics of WaterWorld.

What is here:
-A larger, randomly generated mining map filled with all the asteroid mobs, plus deep sea carp and mega deep sea carp.
- A boss monster, the Kraken. Which is basically a deathsquid that deals less damage and is allied to waterworld enemies.
- WaterGas, my way to make water actually act like water in waterworld. It uses a gas overlay (like plasma) in order to give the effect of being under water. In small amounts it is just the regular water vapor in the air.

bugs that currently exist that I know of:
-The watergas overlay doesn't work properly on all tiles all the time
-The walls with visible iron ore still use the rock iron ore sprite, so it doesn't match the rest of waterworld texture-wise
-The airlock in the main waterworld base doesn't actually siphon the water and fill with air.

### CODE REVIEW

**Comment by alexkar598** [comment]
You should squash these commits

**Comment by SkullyRoberts** [comment]
@alexkar598 I have no idea how to do that. ¯\_(ツ)_/¯

**Comment by Fox-McCloud** [comment]
A few problems:

- This doens't even compile
- We don't use `/turf/open` and `/turf/closed`. You can't just add these willy nilly and have them work; they're completely dependent on a larger system and turf refactor which we don't have.
- Water as a "gas" isn't even plugged into all the areas that gas gas (such as alarms, filtering, etc)
- Implementing a new gas like this is probably going to get you stabbed by @tigercat2000.
- We don't really want waterworld; we want lavaland. Nothing is even remotely coherently thematic with the stuff of lavaland being ported over but weirdly having water over all of it.

**Comment by SkullyRoberts** [comment]
@Fox-McCloud 
Sorry. I had those in when I was starting. They aren't actually used anymore. I'll delete em.

**Comment by EldritchSigma** [comment]
Not sure but Lavaland is thematicly much more fitting. What needs to be done on lavaland anyways? Mobs are done, all the sprites are ported over, most of the items (although probably outdated). Think lavaland had some weird xenobio dependency for the free golems which would need to be ported/adapted in some way, shape or form.

**Comment by alexkar598** [comment]
To squash you need to run the command:

git rebase fd8b650 -i

It will open the editor you configured o use with git,in that editor replace the second pick and the picks that will follow the second one to squash

**Comment by alexkar598** [comment]
Or you could go back before the first commit by using:
git reset fd8b650^ --soft

And recommit the changes in a single commitj

**Comment by alexkar598** [comment]
Or you can just not care because who ever looks at the commit page anyways

**Comment by KasparoVy** [comment]
This would be absolutely sick. I'd say something about Skrell being useful but, then again, wouldn't the depth be significant enough to crush?

**Comment by Ty-Omaha** [comment]
Pics?

**Comment by Chronarch2954** [comment]
I fully support this, as it makes Paradise more unique than it would be if it had lavaland instead

**Comment by taukausanake** [comment]
Yeah, fuck Lavaland \*_insert becoming /tg/ line here_\* this looks way more unique and interesting. We really should try to make Paradise it's own thing rather than more like everything else. Plus it'll make Skrell a lot less useless. :+1: :fish: 

I don't think I like liquid as a gas. What happens when you try to mix water and gas together then? What you should do is try to make a new environment that is water rather than try to wedge it into an existing system that doesn't suit it. That would required a new addition however and might be tougher to port than Lavaland itself. Then again didn't Europa Station have working-ish water at one point?

That adminbus squid might actually be worth something now. Awesome!

**Comment by SkullyRoberts** [comment]
Here are some pics I have from a relatively stable build earlier. There was a visual bug going on (that I fixed) so it's kinda super hard to see anything through the water.
screenshot 14
screenshot 15

**Comment by SkullyRoberts** [comment]
But yea. I hate using water as a gas, but I kinda just wanted to get something vaguely functional working, and then smooth over the water mechanics later.
Because, quite frankly, I don't have any idea how I would add liquid mechanics. It would probably be a gross copy/paste job if I was the one to do it.

**Comment by SkullyRoberts** [comment]
This project is quickly going into "learning as I go along" territory. And I think that if someone more experienced did it, it would probably be done better and faster. But until that someone shows up, I fully intend to struggle through all this!

**Comment by SkullyRoberts** [comment]
@Ty-Omaha I did pics, btw

**Comment by SkullyRoberts** [comment]
Also, WaterWorld has a forum thread here: https://nanotrasen.se/forum/topic/12980-waterworld-suggestionsdiscussion/

**Comment by Tayyyyyyy** [comment]
This is cool and different! There are a lot of reasons Lavaland is a good idea though, mainly cause tg has it and that simplifies future maintenance/balance. Though maybe you could have two asteroids, if this ends up working out, and if that doesn't kill the server. Worst case it could be converted to a gateway level when lavaland is finally ported?

**Comment by taukausanake** [comment]
I rather have rotating mining levels. That would be something cool and interesting

**Comment by Ty-Omaha** [comment]
I think this is cooler than what we have now

**Comment by tigercat2000** [comment]
I'm concerned about the addition of water to LINDA as-is. It's going to make it a pain in the neck to update LINDA to use modular gasses, I suspect.

**Comment by DesolateG** [comment]
2 things.

Seeing stuff with a water layer filter is going to be obnoxious.

With LINDA and fastmos, what happens when you mine a tile and suddenly fastmos kicks in to fill that now empty tile?

**Comment by alexkar598** [comment]
I may try to make a water system soon

**Comment by alexkar598** [comment]
Soon meant to be eventually

**Comment by Spacemanspark** [comment]
Holy shit this is awesome.
If you can pull it off, yes please.

**Comment by Spartan6** [comment]
The water needs to be a more transparent effect.

**Comment by SkullyRoberts** [comment]
Also, I've been thinking of adding a type of glasses that make the water overlay much more transparent. So that deep sea miners can have better visibility! :)

**Comment by Denthamos** [comment]
As others have said, like @taukausanake , it would be nice for paradise to become more unique and not just a TG/Bay rip off.  We have been having a big identity crisis issue for some time as most people refer to us as "TG but with longer rounds" for example.

How about for a change we not be TG and be paradise.  Something that we can actually call our own that no other server has.  Lavaland is nice and all but thats a staple of TG and TG code bases now.  Maybe lavaland could get its own gateway mission for it for people to tackle its challenges in the future, but when I see the idea of this, I see something we can finally call ours.

**Comment by taukausanake** [comment]
> I rather have rotating mining levels

@Ty-Omaha stop stealing my ideas >:(

**Comment by Ty-Omaha** [comment]
oh lmao didnt see

**Comment by Ratvar** [comment]
Make gas water disappear if pressure is low enough instead of permanently leaving vapours?

**Comment by taukausanake** [comment]
Actually now that I think of it water as a gas could work pretty good. One question is what to do if water fills up an area already with gas (say air) and then gets pumped out. The gas was displaced but where did it go and what filled up the area when the water was pumped out? If it automatically refills with a gas when pumping then I can see an atmos traitor having fun replacing air with plasma after a flood.
The real problem though is making water travel fast enough and continuous if it does breach. I don't think fastmos is as fast as it could be but at least it won't need ZAS levels of flooding. Another might be how to treat air alarms (maybe make them environment alarms) and what system to pipe liquids with (nightmare piping PR inbound) but this could push for even more systems to play with. Maybe finally sinks and showers won't use bluespace for their water

**Comment by Vivalas** [comment]
Liquids have a fixed volume, so I imagine they would compress the air in a room. Of course for this to happen you need a lot of water pressure. Otherwise water would displace the air. A good way to handle this is to have it so "liquid" "gases" are stored separately per tile from actual gases in tiles-- when the volume of the liquids in a tile increases the "volume" per tile needs to change-- this would require a minor change to atmos to allow tile volumes to be dynamic. In order for liquid volume to change, the pressure of the liquid needs to be above the ambient air pressure. When this happens the liquid volume increases and the "volume" available for gases in the tile decreases until the pressures equalize. Liquid volume could then be used to determine "height" of the water in a tile using a little formula.

**Comment by Vivalas** [comment]
This actually helps solve water displacing air as well. As air pressure increases from liquid volume increases, the air would flow towards surrounding air pressure. This might be a bit weird but eventually I imagine the air would flow completely out of a room to a neighboring room if the water volume rises to fill the tiles in a room.

**Comment by taukausanake** [comment]
@Vivalas I think airlocks are named such for a reason though. Maybe the "ceiling" will have pockets the air will flow into that you can't reach and then drown. Or the gas can flow out from the breach into the open and never return again like in space. That should be the best choice now, the other could be for closed rooms being flooded

**Pull request closed without merging**
