### PR TITLE
Makes Some Unathi Space-suits Less Fat

### PR DESCRIPTION
**Pull request by KasparoVy**
Security, Medical, Engineering, Syndicate.
Port of https://github.com/PolarisSS13/Polaris/pull/2426 by Redstryker from Polaris.

:cl:
tweak: Unathi Security, Medical, Engineering and Syndicate side-facing hardsuit sprites have undergone weight reduction.
/:cl:

_This only affects the east/west sprites of the hardsuits mentioned above._
slimmerunathispacesuits

### CODE REVIEW

**Comment by Anticept** [comment]
Thats remotely better. The damn sec one still looks freaking HORRIBLE.

**Comment by mrturkeytoe** [comment]
The engineering one is sexy as hell though. I wish the vulp ones were a little more stylized.

**Comment by Anticept** [comment]
Yes the engineering one is great. The vulp atmos ones are ADORABLE.

**Comment by mrturkeytoe** [comment]
I just wish they diverged a little more from the standard human hardsuit look some more.

**Comment by Anticept** [comment]
They are humanoid. You'd have to change the very way the species works for that.

**Comment by mrturkeytoe** [comment]
I just mean the aesthetic design, but I guess in looking at the unathi engineering sprite maybe it's just how the vulps sprites are that makes them not look as good.

**Comment by KasparoVy** [comment]
I get what you mean. I'll see about sorting that in the future (no ETA). A bit of spriting here and there when I can get it done will probably see me revamp all of the Vulpkanin spacesuit (and helmet) sprites while staying reasonably true to the OG design, not for this PR though.

**Comment by FlattestGuitar** [comment]
Those are some handsome lizards. :+1:

**Pull request merged**
