### PR TITLE
Generic ventcrawling + Bugfixes

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit makes the ventcrawling system operate independant of
ventcrawling verbs. Every type of /mob/living now has a ventcrawling
variable, which allows them to interact with the ventcrawling system if
set to 1 or 2. The AltClickOn() defines for each ventcrawling mob have
been removed, and replaced with a single AltClick() define on ventcrawl
machinery.

TL:DR; Adminbooze ventcrawling easily, New ventcrawl mobs easily, Odd bugs fixed

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Yay.

:+1:

**Comment by Crystalwarrior** [comment]
Before you merge you should look into a number of issues caused by ventcrawling, like how you can ventcrawl into cryo pipes or you can ventcrawl into the pipes when buckled to them (if you have that PR)

**Comment by tigercat2000** [comment]
@Crystalwarrior I'm unsure what you mean by ventcrawling into cryo pipes, and I'm pretty sure we don't have pipe buckling.

**Comment by Crystalwarrior** [comment]
@tigercat2000 Basically you can ventcrawl into cryo pipes by moving downwards.
Unless this is not a ventcrawling system that actually lets you physically crawl in the vents.

**Comment by tigercat2000** [comment]
@Crystalwarrior We do have the physical crawling, and I'm pretty sure I already fixed any accidental cases of ending up in the pipes randomly.

**Pull request merged**
