### PR TITLE
Add nutrient dispenser to Abductor ships

### PR DESCRIPTION
**Pull request by datlo**
Replaces one of the alien lockers in each ship by a Nutrient Dispenser
vending machine, which contains 20 chicken cup soups and 12 warm donk
pockets (15u omnizine when eaten).

Also contains two bottles of vodka if hacked.

Has sprite for the machine's various states.
nutrientdispenser

I believe abductors should influence their testing environment as little
as they can, and this includes station supplies. This vending machine
supplies both food and healing, cutting some of the Abductors' reliance
on stealing station supplies.

🆑
rscadd: Added nutrient dispenser to Abductor ships.
/🆑

### CODE REVIEW

**Comment by Superhats** [comment]
Add some sprites, perhaps?

**Comment by datlo** [comment]
Added a screenshot of how the vending machine looks like IG.

**Comment by davidchan13** [comment]
I'd rather it be a wall dispenser like the Janitor's Space Cleaner or Chemistry's Fuel tank. Recolor one and have it full of nutriment or some bio gel that sustains them. Also how does mouthless critter eat?

**Comment by lordpidey** [comment]
Could you rename/retexture the food items to something like "Nutrient slurry"?  Make it more alien-ish.

**Comment by datlo** [comment]
I'd rather keep the function of the healing items provided (warm donks) obvious. Could perhaps resprite and rename the chicken soup, though.

I'd also prefer to keep this as a vending machine rather than wallmount as this more obvious (Source of healing item is important).

**Comment by davidchan13** [comment]
I just am not fond of a vending machine amidst a ship full of alien surgical tools and equipment. A wall dispenser and a sleeper would be more appropriate than a machine full of chicken soup and hot pockets.

**Comment by Fox-McCloud** [comment]
Abdcutors are most definitely not purist hands off super objective scientists; they're you're stereotypical grey aliens who are liable to abduct or cause other sorts of trouble; shennanigans like capturing the captain and putting him in a maid outfit are perfectly within the realm of what Abductors can do (and given the whacky objectives the crew gets, this kinda reinforces that).

Nutrients aren't a big problem for them; they can eat the hearts of people they perform surgery on, and stealing food from other locations is fairly trivial. 

They could use ayylmao versions of the bonesetter, bone gel, and Fix-O-Vein though.

**Comment by Ty-Omaha** [comment]
This seems really out of place

**Comment by Plotron** [comment]
They could still get some emergency food items IMO. And yes, keep it immersive. You could even dispense pure nutrient in liquid form — that'd be the most straightforward way.

**Comment by datlo** [comment]
Alright, I'll see if I can make something that fits the ship better. I'll close this for now.

**Pull request closed without merging**
