### PR TITLE
Edit max line length

### PR DESCRIPTION
**Pull request by m-dzianishchyts**
## What Does This PR Do
Increases max line length from 80 to 120.

- [x] Reformat is the only thing I've done.

I wish I could keep line breaks...

> Semantic diff is probably needed to review this: https://app.semanticdiff.com/gh/ParadiseSS13/Paradise/pull/25071

## Why It's Good For The Game
This has already been touched upon in #14002.
I am pretty sure 16:9 displays can fit 120 characters in one line. Current 80 characters limit leads to different silly things like:
```dm
// Head colour check. Abbreviated to save on 80 char
const HCC = (role) => {
  // Return green if they are the head
  if (HeadRoles.indexOf(role) !== -1) {
    return 'green';
  }

  // Return orange if its a regular person
  return 'orange';
};

// Head bold check. Abbreviated to save on 80 char
const HBC = (role) => {
  // Return true if they are a head
  if (HeadRoles.indexOf(role) !== -1) {
    return true;
  }
};
```

It also increases the number of lines which leads to increased scrolling for navigation.
You can find more arguments here: https://github.com/ParadiseSS13/Paradise/pull/14002#issuecomment-686063232.

### CODE REVIEW

**Comment by FunnyMan3595** [comment]
It's a bit silly that we require this for JS, while simultaneously having no limit for DM.

**Review by S34NW — APPROVED** [review]
looks like this was already done ages ago but accidentally re-introduced https://github.com/ParadiseSS13/Paradise/pull/14327

Approved in principle but its gonna be a conflict magnet

**Comment by DGamerL** [comment]
Reopening because it's stale exempt

**Review by DGamerL — COMMENTED** [review]
Can you deconflict this?

**Review by lewcc — APPROVED** [review]
lgtm before this conflicts again

**Pull request merged**
