### PR TITLE
Wizard Update - Revenge of the Federation

### PR DESCRIPTION
**Pull request by Arkatos1**
_After a countless humiliating defeats, Space Wizard Federation decided to take major changes in their organizational structure. This is rare for such loosely aligned group._

**What does this PR do:**
This PR contains many additions, tweaks, fixes and other changes regarding Wizards, lets try to get through them, one by one:
1) **Ragin' Mages Gamemode**
a) Wizards are now properly polled in the Ragin' Mages gamemode, instead of ghosts being violently dragged into the role without any warning or prompt.
b) You can no longer buy Summon Ghosts spell in the Ragin' Mages gamemode, as this could hinder other Wizards.
c) You can no longer buy Bind Soul spell in the Ragin' Mages gamemode, as it does not work properly in this mode at the moment. I have plans to make it work in the future, but there is little point of keeping it in this mode, if it does not work at all.
d) Many grammar fixes and improved wording. Wizards should now clearly know that it is Ragin' Mages round, and that there might be more Wizards to come.
e) **Gamemode should now work properly without any admin intervention at all.**  Remaining number of Wizards should now be properly counted and displayed. General refactors across the board.

2) **Wizard Gamemode (General Wizard improvements)**
a) Deck of tarot cards renamed to Guardian Deck in the Wizard spellbook, to be completely clear what it is and what it does.
b) Rituals and Challenges categories merged into one in the Wizard spellbook, called Rituals. Added extra descriptions to some summon spells.
c) Removed Cursed Heart from the Wizard spellbook. This item simply does not work, or even fit the Wizards, and was even meant as some sort of punishment. Cursed Heart still remains in the code, as odd loot in the necropolis chests in the Lavaland and for admin purposes.
d) Ghosts made visible via Summon Ghost spell now have description about how they are oddly visible, to make it clear to everyone that it is intended behavior.
e) Bottle of Ooze now creates a magical morph instead of a normal one. Magical morph is capable of casting smoke and forcewall spells. This makes them worth the cost compared to the alternatives while still being fun to play as and against, as these spells, while being heavily underused, fit into the morph playstyle perfectly.
f) Improved spelling and minor refactors.

3) **Demons**
a) Slaughter and Laughter Demons no longer have duplicit objective shown at the Round End display.
b) Laughter Demon is now properly called Laughter Demon instead of Slaughter Demon in the role polls.
c) Laughter Demon is now slightly weaker compared to the Slaughter Demon. Laughter Demon intended "disadvantage" is supposed to be the fact that when they die, they release all their victims alive. Problem is that this very often does not happen at all due to their masterful escape abilities and high stats. This tones them a bit to be slightly weaker than their more expansive cousins Slaughter Demons, roughly by 25%.

Tested locally without any issue. Some changes ported from /tg/station13.

**Changelog:**
:cl: Arkatos
fix: Ragin' Mages gamemode should now be playable without any major issue
fix: Slaughter and Laughter Demons no longer have duplicit objective shown at the Round End
fix: Laughter Demon is now properly called Laughter Demon instead of Slaughter Demon in the role polls
spellcheck: Improved wording and fixed mistakes in Wizard and Ragin' Mages gamemodes
tweak: Wizards are now properly polled in the Ragin' Mages gamemode
tweak: You can no longer buy Summon Ghosts spell in the Ragin' Mages gamemode
tweak: You can no longer buy Bind Soul spell in the Ragin' Mages gamemode
tweak: Deck of tarot cards renamed to Guardian Deck in the Wizard spellbook
tweak: Rituals and Challenges categories merged into one in the Wizard spellbook
tweak: Laughter Demon is now slightly weaker compared to the Slaughter Demon
tweak: Bottle of Ooze now creates a magical morph instead of a normal one. Magical morph is capable of casting smoke and forcewall spells.
tweak: Visible ghosts will now get a special description about their visibility
del: Removed Cursed Heart from the Wizard spellbook
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Making the morph magical was a really neat idea, nice.

**Comment by taukausanake** [comment]
I think everything in here is fine. Still rather Ragin' Mages be in rotation but meh

**Comment by The-Driker** [comment]
I'm not sure I'm comfortable with nerfing Laughter Demons for the sole reason of making it easier for people to immediately jump back in to fight the wizard. All this is realistically going to do is make them a non-viable waste of points for a wizard, unless they are spending everything on summons. I'd only be okay with this if you balance it by removing the demon heart drop from them.

Everything else looks fine though.

**Comment by Ralta** [comment]
Beautiful changes. I do agree with Driker regarding the Laughter Demons though; I have a feeling they'll get summoned a lot less if this goes through.

**Comment by Imotepchief** [comment]
Request - Make slaughter demons that munch on someone burp out their body parts except torso when they are finished.
That way you could stick the player's head on a monkey or something and clone them to get them back.

**Comment by MrMagolor** [comment]
>Request - Make slaughter demons that munch on someone burp out their body parts except torso when they are finished.
That way you could stick the player's head on a monkey or something and clone them to get them back.

Isn't the whole point of a _demon_ that they would, devour your soul or something?

**Comment by Fox-McCloud** [comment]
Yeah, not keen on the laughter demon changes at all.

**Pull request merged**
