### PR TITLE
Modify radio channel colors for better contrast. Medical channel especially affected.

### PR DESCRIPTION
**Pull request by king5327**
A picture is worth a thousand words, so http://puu.sh/uQKUl/36b5ff094f.png

Inspired by the fact that Medical and Common are nearly indistinguishable in the chatbox, and extended to make some other channels fit the scheme as well.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Before/After comparison, perhaps?

**Comment by king5327** [comment]
I'll get a before too, but my priority was getting a screenshot which showed medical could pay attention to a different color and not have to skim chat all the time. Which I failed to do since I forgot common in that shot. Here's a fixed one: http://puu.sh/uQQZ6/e7a59b5e64.png

**Comment by Necaladun** [comment]
Might be my monitor/eyes, but I can't tell the difference, except for medical which looks better. So 👍 but my eyes aren't the best judge.

**Comment by king5327** [comment]
Affected channels are Medical (slighly bluer), Common (More vibrant, but slightly), Command (Slightly Darker), Supply (is now a bit less harsh, coming in line with the slight pastel of the other colors), and Service (touch of yellow, I'd argue it's easier to see).

**Comment by Lady-Luck** [comment]
I think tg/yog has an even better medical channel color, it's like a light blue, very little green in it.

**Comment by Lady-Luck** [comment]
#337296 is what tg uses for medical, it's nice.

**Comment by AffectedArc07** [comment]
If this gets merged please  PM me on discord so I can update my script

**Pull request merged**
