### PR TITLE
Permits hoodies to carry flashlights

### PR DESCRIPTION
**Pull request by Spacemanspark**
It was bothering me, ok?

🆑
rscadd: Permits hoodies to carry flashlights. 
/🆑

### CODE REVIEW

**Comment by tigercat2000** [comment]
i believe you do actually need to have the cl properly new-lined

**Comment by Spacemanspark** [comment]
Should be good now.

**Comment by taukausanake** [comment]
So they can carry only flashlights. Nothing else? Nothing smaller even?

You sure you don't want just a dedicated flashlight inventory slot?

**Comment by Spacemanspark** [comment]
Fairly sure they can carry oxygen tanks too.

**Comment by taukausanake** [comment]
Correct me if I'm wrong but doesn't declaring var "allowed", along with any other vars, overwrite their parent? Unless you're saying there is a proc that re-declares it with the parent values. Otherwise I might only know partially what I'm talking about

**Comment by Citinited** [comment]
@taukausanake It should only affect childs of that item, not parents

**Comment by RemieRichards** [comment]
@Citinited they're saying it overwrites the values it gets FROM its parent, which is true.

**Comment by tigercat2000** [comment]
@taukausanake is correct, this overwrites the whole list, it won't be automatically appended to the parent values. You'd have to put it in New() to do that.

**Comment by Citinited** [comment]
@RemieRichards Got it, seems I misunderstood their post

**Comment by taukausanake** [comment]
I guess I could have worded it better but thank goodness there are people here smarter than me who understand

**Comment by Spacemanspark** [comment]
I'll adjust that when I get home tonight then, my bad.

**Comment by Spacemanspark** [comment]
Fixed it.
@Crazylemon64 @Fox-McCloud

**Comment by Crazylemon64** [comment]
Mmmm it's something we'd need to update later if someone changed what basic suits could hold but I think it'll be fine either way, since there are already suits that need that treatment. Here we go!

**Pull request merged**
