### PR TITLE
Ports Wormhole Projector

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This is the third damn time I've attempted to port this thing---this time I was successful.

Ports over TG's Wormhole Projector gun (ie: portal gun).

Basically shoot once and it makes a blue portal--switch to the other mode and fire to make an orange portal; both portals are linked (portals do not last indefinitely; they last about 30 seconds).

Sprites by @Nienhaus 

Can be made at R&D as a high end, end-game item.

### CODE REVIEW

**Comment by Deanthelis** [comment]
>Can be made at R&D as a high end, end-game item.
So, at 12:30 if Mining and R&D are competent.

**Comment by Spacemanspark** [comment]
Kek.

**Comment by Fox-McCloud** [comment]
Also, just for those who scrutinize carefully---this doesn't automatically switch firing modes like TG's does; I can add that, but it means the in-hand sprite will be a mode behind what actual mode it is...granted, that's in-hand....so...

Lemme know if you guys would rather have automatic switching and incorrect in-hand icons (barely noticeable), or if you'd rather have the fully fledged automatic switching.

**Comment by fludd12** [comment]
Does the portal only last 30 seconds after both are shot, or does each portal only last 30 seconds? It doesn't seem useful if you only have a 30 second period of time to return to a marked point.

**Comment by Fox-McCloud** [comment]
Each portal lasts 30 seconds, independently

**Comment by Fox-McCloud** [comment]
added in the auto-switching; got the in-hand icon updating to work.

**Comment by Deanthelis** [comment]
I have to say, I used this in a round - Extremely helpful.

Bags of Holding fuck up your transit, though. Is that intentional?

**Comment by TheDZD** [comment]
Bags (and belts) of holding generally cause horrible things to happen when you use any sort of teleportation, be it the hand tele or the stationary teleporter, so I would assume it is intentional.

**Comment by Fox-McCloud** [comment]
>Bags of Holding fuck up your transit, though. Is that intentional?

Bags of holding mess with all teleports (portals, wormhole, teleguns, or teleporters)---bluespace crystals and such are a slightly different story.

**Comment by Deanthelis** [comment]
Right, I just didn't think of the portals as teleports. It depends on if you're going for a folded-space/extradimensional travel angle, or the Star Trek transporter atomic-disassembly-reassembly angle.

**Comment by Fox-McCloud** [comment]
*most* teleports use a proc called `do_teleport` which is part of a larger teleport datum--it's here that the bag of holding stuff is handled.

Localized teleports (like the bluespace crystals and the strange objects) just pick random turfs in a specific range and are not impacted by this.

hope that helps

**Comment by Deanthelis** [comment]
It does, thanks.

**Comment by Spacemanspark** [comment]
This thing gets beepsky called on you (I'm assuming it's a gun subtype), and it's rather obnoxious.
Other than that, it's really fun.

**Pull request merged**
