### PR TITLE
TS Awaymission Map Updates

### PR DESCRIPTION
**Pull request by Kyep**
This PR makes a few tweaks to the Terror Spider away mission, with the goals of:
1) Making it harder to cheese the mission.
2) Making the loot you get from it more likely to be useful to the rest of the station, as opposed to stuff that empowers the person who finds it.

The specific changes are:
1) The Mother room's vent has moved two tiles west, and three tiles north. This ensures it is visible from everywhere in the room, and upon slaying the mother, spiderlings are more likely to find their way out, and less likely to get trapped on corners.
2) The Combat RCD in Engineering has been replaced with 25 silver and 20 uranium. RCD-cheese was becoming too common, the combat RCD is very strong in general, and this was an opportunity to provide a reward (minerals) which can be used by the station overall, not just the people on the mission.
3) The Research Notes have been removed from the awaymission R&D and RD office rooms. They're now stored in the science storage vault, meaning you have to beat two bosses to get them. In addition, their combat/materials/eng/biotech levels have been changed from 2 to 4, to reflect the fact it now takes many times longer to get them. Additionally, there is now only one set of Research Notes, not two. I did this because people were using the notes to get R&D working right away in the gateway, then producing all the tools they need from within the gateway. I'd rather they got those tools from the station, or at least had to scavenge for them. I also don't want people running in, just to grab the notes and run out again, so now, they're harder to get (but more worth it when you do get them).
4) Invulnerable walls have been added around the Queen's room, and the hidden spiders behind blast doors removed. People were cheesing those spiders every round anyway by building walls in front of the doors they were behind, using metaknowledge. I would rather have more spiders in
the mission roaming around unpredictably, than having some endlessly waiting behind specific locked doors. The addition of invulnerable walls within the normal walls also prevents people making use of the caves to cheese spiders with suffocation - or setting up gauntlets there - which
is an extremely cheesy tactic I have seen used before.
5) The purple spider next to the bridge is no longer able to break through the wall, and get seen before the crew has even crossed the map once.
6) The small room between the main corridor and science no longer lacks vents/scrubbers.

1: ts_mother
4: ts-queenroom
5: ts_bridge_entry
6: ts_atmos_room

🆑 Kyep
tweak: Terror Spider away mission is now harder to cheese.
/🆑

### CODE REVIEW

**Comment by Anticept** [comment]
You could just prohibit building on this mission as well.

**Comment by Kyep** [comment]
Even if it were possible to prohibit building on just this zlevel, I don't want to make weird exceptions to the normal game rules just to patch over niche edge cases. It would come across as an immersion-killing Obvious Rule Patch. I'd prefer to solve the issues by tweaking the level such that the problematic condition is much less likely to happen.

**Comment by Anticept** [comment]
Still sounds kinda snowflakey to alter a map in response to an undesired issue to try and discourage it, instead of just outright stopping construction and solving the issue completely.

**Comment by Kyep** [comment]
The combat RCD is being removed because it makes it way too easy to spam welded glass airlocks, which is a cheesy strategy that negates the challenge of the mission. Trying to add "does zlevel allow construction?" checks into every construction method, including RCDs, would be enormously more complicated, and still arguably less effective, than just removing the combat RCD from the mission. Hence, this PR does the logical thing, and removes the combat RCD.

**Comment by Anticept** [comment]
The RCD bit is fine, I have no issue there.

What I mean is things like changing indestructible walls and removing hidden spider doors as a response to construction cheese.

Anyways, that said, I do see what you mean by how incredibly complex it would be to consider every construction method for checks.

**Comment by Kyep** [comment]
I changed the walls because, without them, it is easy under fastmos for people to depressurize the nest, killing all spiders there with no combat or challenge. This is another method for cheesing the spiders, and one I'm keen to eliminate, because it is extremely dull and risk-free.

I left the doors as-is. The only thing I changed there was to remove two spiders placed behind the doors. Originally they would rush out and ambush you when you killed the Queen. They were there to be a surprise. Now, however, everyone expects them, to the point they'll pre-emptively wall off those doors when they go past them. I don't like creating obstacles which are so easy to bypass with cheese, and, I must admit, having hidden enemies spawn on a trigger is a little too predictable - I am not sure why I put them there in the first place. So, I'm removing them.

**Comment by Kyep** [comment]
No, the doors have never been random, and realistically they can't be given the layout.

Yes, TS are vulnerable to vacuum. And fire, for that matter. It takes time, but it will kill them eventually. This did not use to be the case, and there are still some exceptions, but currently, it is a valid nest-clearing strategy.

**Comment by Fox-McCloud** [comment]
There's several unique items, like the research paper or partially charged cells, that should be defined in the code, then mapped in.

Var editing objects on the map to be unique is generally bad practice (there's exceptions, such as access on door, or some vars on turfs); it'd be better if they were defined as unique objects and put in a file that's with the rest of this away mission.

If you could do that, then this can be merged.

**Comment by Fox-McCloud** [comment]
Stale; update it please, or this will be closed.

**Comment by Kyep** [comment]
@Fox-McCloud I will update it on Monday or so.

**Comment by Kyep** [comment]
@Fox-McCloud The notes are now defined in the code. The cells no longer have custom charge values. If there are any other specific objects you want changed, please let me know.

**Comment by Fox-McCloud** [comment]
conflicts.

**Comment by Spacemanspark** [comment]
Yes, we need this.

**Comment by Kyep** [comment]
@Fox-McCloud Conflicts fixed.

**Pull request merged**
