### PR TITLE
Griddle addition, kitchen rework

### PR DESCRIPTION
**Pull request by tristan1333**
## What Does This PR Do
Replaces the grill with the griddle which actively cooks items that are placed ontop, if cooked and left on the griddle for too long after being done, the item burns. Recipes that relied on the grill have generally been moved into the microwave if the recipe isn't compatible with the griddle.  Details of all the changes are here: https://docs.google.com/document/d/1qVFvLX26DkcHS4yCONPCjIa7ZwGS0eor31hfGRxLFrQ/edit?usp=sharing
All the maps have the grill being replaced by the griddle. 
Currently need sprites for: Raw egg, Raw waffle, raw roffle waffle, all the raw kabobs
The code needs a cleanup, so putting this as a draft pr until it's all cleaned up, all functional ingame though.

## Why It's Good For The Game
The griddle is much more interactive than putting items into a magic box

cheef

## Testing
Cooked each item as I created them

## Changelog
:cl:
add: Griddle now replaces grill
tweak: Lots of recipes changed to incorporate the griddle
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
YES! IT BEGINS!!!!!!

God id love this kinda system to be implimented for...well everything kitchen related, no more magic "Stuff everything in the oven and MAGIC youve got 4 turkeys"

or "Microwave raw pasta and BAM 4 bowls of spaghetti!"

Instead Stovetop, 4 burners, pots and pans of different sizes all used to cook things a different way, from boiling up water to boil noodles in, while also cooking up a big ol pot of sauce to pour onto the pasta on the plate to make the dish.

An oven you need to actually bake things in instead of MAGIC and so on...the potential for the cooking system is huge if it went this route away from its MAGIC system now that relies entirely on RND to make it functional in any real capacity

**Comment by Aylong220** [comment]
You didn't have to remove all maps for the test
You can enable test map in the config
Just uncomment this line
You can also turn off lavaland in the config
image

**Comment by spacegeese** [comment]
add spatulas so we can flip it, your choice if it does anything or not but free cool animation

**Comment by McRamon** [comment]
Why not jsut keeping hte name grill?

**Comment by Carthusia** [comment]
> Why not jsut keeping hte name grill?

Different object.

Grills have open slots to allow open flames to touch the thing your cooking, griddles are solid surfaces that heat up to cook things

**Review by S34NW — CHANGES_REQUESTED** [review]
No changes in a month, PR marked as stale. It will be closed in 7 days if no substantial changes are made.

**Pull request closed without merging**
