### PR TITLE
Custom Item: Fox P McCloud

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Didn't ever think I'd really want a fluff item, but @Nienhaus just made me a set, out of the blue, and I absolutely loved it.

Fox's jumpsuit and jacket:

foxstuff

Approved and signed off by @Necaladun 

relevant fluff item parties for configuration: @TheDZD 

Character to appear on: Fox McCloud
Jobs: All

### CODE REVIEW

**Comment by Nienhaus** [comment]
I still want it to be dubbed Haus suit even if you going to use it for the idea I had but wont say.

**Comment by Iamgoofball** [comment]
needs a captain falcon outfit to knee this one off the station

**Comment by Nienhaus** [comment]
You did it SS! @Fox-McCloud

**Comment by Iamgoofball** [comment]
still needs a captain falcon outfit to knee this one off the station

**Pull request merged**
