### PR TITLE
Adds flagellant robe sprites

### PR DESCRIPTION
**Pull request by kugamo**
## What Does This PR Do
Adds unique sprites for the flagellant robes, which previously used the berzerker hard suit. Full credit goes to @Drakeven for the sprites, and this PR was made in coordination with her.  It has been made to avoid git problems she had with her last PR. https://github.com/ParadiseSS13/Paradise/pull/12996 And as well as fixing some minor issues with the sprites, it adds Grey versions too.

## Why It's Good For The Game
It gives a unique sprite to the flagellant's robe, which is much more fitting than the hard suit.

## Images of changes
**HUMAN**
OVZuH4SYOG

**DRASK**
ZO6YObxrLr

**GREY**
1Tbwfo3YEi

**VOX**
0hoRMZUmYu
(the mistiming between the pulses in the hood and suit have been fixed since this image was taken)

## Changelog
:cl:
imageadd: Adds unique flagellant robe sprites for Humans, Drask, Grey, and Vox
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
Yes please. People confusing the Champion hardsuit and Flagellant robes is over.

**Comment by kugamo** [comment]
This PR is failing map checks, because I had to change an item name in a cult structure. I renamed the flagellant robe item from "berserker" to "flagellant_robe", hopefully this won't be an issue.

**Review by Kyep — APPROVED** [review]
Yes, we need this.

**Review by AffectedArc07 — APPROVED** [review]
Im not letting this get conflicted for the 900th time

**Pull request merged**
