### PR TITLE
Adds new berets and jump skirt

### PR DESCRIPTION
**Pull request by Xantholne**
Adds a Medical Beret, Botany Beret, and Botany Jump skirt. All available from load out menu for pre selection.
472e072a71d9199ab473039c71a60689

### CODE REVIEW

**Comment by taukausanake** [comment]
I don't see why either of those jobs need berets but I see no reason for them to not have one. Same for the jump skirt. :+1:

**Comment by Xantholne** [comment]
Everyone needs a beret, and skirt. Everyone.

**Comment by LightFire53** [comment]
I could see the main departments getting them as part of a formal uniform... but I don't see a reason for service to have it. Service is meant to be a little more lax in their uniform/workplace clothing.

**Comment by taukausanake** [comment]
I can agree with LightFire here but if the whole station is expected to be in some formal wear then it doesn't hurt to have some hanging around. Now if only we had someone in charge of all the clothing. Maybe another cargo job? Uniform supervisor or clerk? Might make a nice karma job

**Comment by KasparoVy** [comment]
@LightFire53 I suppose that's why they're available solely from the loadout screen.

**Comment by Xantholne** [comment]
I don't see why we can't have even more berets available :eyes: Berets are very stylish

**Comment by Spacemanspark** [comment]
I don't see why not, I suppose.

**Comment by Fox-McCloud** [comment]
conflict for hats.dmi. 

You may want to wait on this; we have too many hat sprites at the moment--I don't mean that from a personal perspective, I mean it from an objective perspective; I believe we're over the .dmi limit for the amount of sprites we can have in a single file.

**Comment by taukausanake** [comment]
@Fox-McCloud are all the hats in there actual hats or just head things? It sounds like we might have to start sorting icons around a bit

**Comment by Fox-McCloud** [comment]
They're all head things. There's a lot of icons that don't belong there, as well--like the plasmamen and Vox sprites.

**Comment by Xantholne** [comment]
That may explain why Travis still isn't happy with me.

**Comment by Fox-McCloud** [comment]
Conflictssss

**Comment by Fox-McCloud** [comment]
Going to have to put this on hold until the heads/hats dmi's are refactored a bit and the species icons are moved out of them. Seeing as there's also conflicts, going to go ahead and close this---once the refactor occurs, please, feel free to re-open this.

**Pull request closed without merging**
