### PR TITLE
Allows Leather Satchel Strap Switching

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just a minor aesthetic feature. This only applies to the leather satchel, specifically. Adding it in for every single satchel isn't feasible.

Allows you to switch which shoulder you wear the leather satchel's strap on.

img
img

:cl: Fox McCloud
add: Allows you to switch strap sides on leather satchel
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
It's not a purse, mom, it's a book bag!

**Comment by KasparoVy** [comment]
Not sure if there's a Vox-specific sprite for the leather satchel. Hopefully not and hopefully it won't break.

**Comment by Shadeykins** [comment]
> 
> 
> Not sure if there's a Vox-specific sprite for the leather satchel. Hopefully not and hopefully it won't break.

Is nots purse, skrekking dustlungs, is bookbags yaya!

**Comment by KasparoVy** [comment]
Perfect! LMAO

**Pull request merged**
