### PR TITLE
Implements TG's Vastly Improved Close Button

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Implements TG's vastly improved close button, which is far more consistent with storage icons than our current one is

img

:cl: Fox McCloud
tweak: updates the storage "close" button to be more consistent
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
don't like it, smaller and harder to click

**Comment by theColdflame** [comment]
:+1: muh immersions

also it looks a lot better

**Comment by Crazylemon64** [comment]
I'd say it looks nice, but its small visual hitbox might be a negative.

**Comment by fludd12** [comment]
I like our :x:. It's nice, IMO.

**Comment by Spacemanspark** [comment]
:-1: I'd prefer the easier to click X.
More aesthetically pleasing too.

**Comment by Glorken** [comment]
I agree with Crazylemon. Looks nice, but way too small.

**Comment by QQCucumber** [comment]
:-1: 2smol

**Comment by Mijhead** [comment]
I prefer the :x: too, :-1:

**Comment by KasparoVy** [comment]
Looks mint and it's still reasonably sized.

**Comment by QQCucumber** [comment]
If it were twice as wide I'd consider it an improvement

**Comment by CrAzYPiLoT-SS13** [comment]
I like our :X:, but if you make the button bigger, it would be a :+1: from me.

**Comment by Kyep** [comment]
I too prefer the larger and clearer X.

**Comment by Regen1** [comment]
I like the X much more

**Comment by FlattestGuitar** [comment]
If this thing was bigger and easier to click, sure. The X seems very out of place.

**Comment by Iamgoofball** [comment]
just make it a full sized X with the midnight theming

**Pull request closed without merging**
