### PR TITLE
Removes the Autodrobe

### PR DESCRIPTION
**Pull request by LynxSolstice**
## What Does This PR Do
Removes the costume vendor (Autodrobe) from the maps and cannot be built.

## Why It's Good For The Game
The costumes are frankly LRP and do not fit in the current MRP atmosphere of Paradise (for example the maid dresses, slutty witch costumes, and other items found in the vendor all share the LRP atmosphere they came from.)

## Images of changes
image

## Testing
Spawned in, no runtime errors, it stopped existing and cannot be built as the supply item was removed as well.

## Changelog
:cl:LynxSolstice
del: Removed the autodrobe and it's supply crate.
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
1. Don't make shitty meme PRs trying to push your own narrative 
2. Econ rework and this changes vendors

**Comment by SpringSkipper** [comment]
This makes sense to me. Low RP items are a huge impediment to Paradise's MRP atmosphere and I'm frankly tired of vampires and contractors running around in chicken costumes. PLEASE merge this.

**Comment by Sirryan2002** [comment]
I'm objecting to this, if this isn't a meme PR I genuinely question the rationale behind removing cosmetic RP-oriented items as a way to improve Paradises RP environment

**Comment by AffectedArc07** [comment]
If I could still formally veto PRs I would veto this in a heartbeat.

**Comment by ItsMarmite** [comment]
You'll have to take my vampire halloween costume from my cold dead hands.

Besides, customization good.

**Comment by LynxSolstice** [comment]
> I'm objecting to this, if this isn't a meme PR I genuinely question the rationale behind removing cosmetic RP-oriented items as a way to improve Paradises RP environment

How are they RP orientated? It's a vendor that vends LRP cosmetic items on par with the pet collar (ie. maid dress). It has no place in the MRP evironment.

**Comment by hal9000PR** [comment]
If you want to make a joke atleast make it funny

**Comment by DoctorDrugs** [comment]
This is certainly something that should've been brought up to a Headcoder or a Headmin before making, in addition to that even then this PR would be delayed for the Econ PR being merged/finalized first. formal objection from myself on this PR.

**Comment by OctusGit** [comment]
ab0

**Comment by AffectedArc07** [comment]
Locking before this descends into too much shitslinging

**Pull request closed without merging**
