### PR TITLE
Health scanners disease cure be gone

### PR DESCRIPTION
**Pull request by LynxSolstice**
## What Does This PR Do
This PR removes the old code from the advanced health scanner that told the possible cure for a disease (from pre-pandemic 3000 days I assume) which is jjust a smal qol change meant to facilitate RP interactions between medbay and virology because as of now, any doctor with an advanced scanner instantly knows the cure which makes virology un-interacted with unless medchem is gone or something. (it gets lonely as a virologist) But yeah, the PR just removes the code that gave the possible cure from the advanced medical scanner.

## Why It's Good For The Game
Adds a bit more legwork for medbay to have to interact with the virologist isntead of just completely sidestepping them due to old code still being in use from the old medical system (I assume before virology was a thing) thus increasing RP between the virologist and the other members of the medbay.

## Images of changes
https://youtu.be/ApIBURj5OGU
https://youtu.be/yYu3r4prwbA
https://youtu.be/A0SV6H1kMEw
(apologies for the high contrast, my monitor is HDR and idk how to record in HDR)

## Testing
I opened a local server, used the advanced scanner on a healthy freshly spawned skrell, it did not break the UI, next I spawned fungal TB, infected the skrell, scanned him, and it did not brick the UI and the possible cure section was gone, next I went to the pandemic machine and tested the blood and the cure showed up.

## Changelog
:cl:LynxSolstice
del: Deleted possible cures being shown for viruses on advanced health scanners (remnant of old medical system)
tweak: The only way to get possible cures for diseases is by using the Pandemic 3000 now, should facilitate more RP between virology and medbay (I hope.)
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
You've inherited different changes unrelated to your PR, please revert those changes

**Comment by LynxSolstice** [comment]
Fixed, thanks!

**Comment by Xsingular** [comment]
Disease cures are only visible on Scanner for viruses of Stealth 1 and lower.
A higher Stealth value would necessitate the use of the PANDEMIC machine, as it's the strongest virus detection on station.

This is the current implementation, the Health Scanner and PANDEMIC are not identical in function, despite there being an overlap that gives such an impression.

Additionally, under the implementation of this PR, you are actually making diseases that are **only visible** on the Health Scanner and **not** the PANDEMIC machine needlessly difficult for inexperienced Medbay crew to cure.

**Comment by Butlerblock** [comment]
It's already a TOTAL hassle to deal with viruses as is and currently only exists for more work-fluff for medbay to do, and it often leads to crew screaming at medbay anyways. Virology should already be used since the "possible cure" is slow, random(sometimes can't fix with 5u), and sometimes can be harmful(ethanol). Compared to vaccine which is instant and can easily be made using virology. Viruses almost never do anything other than make your character bald a good 95% of the time anyways.

**Comment by PacifistDalek** [comment]
> Virology should already be used since the "possible cure" is slow, random(sometimes can't fix with 5u)

**Comment by LynxSolstice** [comment]
At the moment viruses are entirely, medbay scans, they print 300 pills of the cure, and virology is never interacted with at all. It would provide Viro with more inter-department RP with the medbay, and removing part of an old system that has no need to remain as of now.

**Comment by Xsingular** [comment]
> At the moment viruses are entirely, medbay scans, they print 300 pills of the cure, and virology is never interacted with at all. It would provide Viro with more inter-department RP with the medbay, and removing part of an old system that has no need to remain as of now.

> At the moment viruses are entirely, medbay scans, they print 300 pills of the cure, and virology is never interacted with at all. It would provide Viro with more inter-department RP with the medbay, and removing part of an old system that has no need to remain as of now.

As I said earlier, the two systems do not replace each other.
There are diseases whose cure can ONLY be found by the PANDEMIC machine, and others whose cure can only be found by the Health Scanner.

Naturally, a lot of overlap exists between them in the form of diseases whose cure can be identified by both, however even then, it's more common for Medbay in the vast majority of cases to cure the disease via Vaccine pills, which can only be made in Virology via the PANDEMIC machine, so virology gets its interaction anyway. 

So what happens normally is that a patient comes in, doctors identify the cure in the case that it's not stealthy enough to be only viewable on the PANDEMIC, and leave it on the hands of the Virologist.
Or sometimes they'd source the cure, cure the disease, and then hand a vial of the blood containing the antibodies to the virologist to synthesize a vaccine.

The virologist gets his interaction anyway, as in the end he is the sole source of vaccine pills. 

Vaccines pills remain the favored method of curing diseases, since they can be produced en masse with no loss of resources, are guaranteed to work instantly, only need 0.1 us to work, as opposed to an average of 10u of the cure, and contain no negative side effects to their consumption.
Additionally they are almost always easier to produce than the cure, since a lot of the cures for the diseases fall into three categories: 

A) materials that Medbay has no access to, this is the most common cure type by variety.
B) materials that Medbay has access to, but isn't easy to mass manufacture and/or causes negative effects on consumption, this is the second most common by variety.
C) materials that Medbay can safely "pump out three hundred pills of" with no strain on resources or effort, comparative to just pressing the "Make Vaccine Bottle" button on the PANDEMIC machine. This is actually the rarest type by variety.

Let's look at Advanced Diseases first and their 11 possible cures:

In category A (no access) you have: 
* Gold: no one in medbay has ORM access, more often than not the doctors have to enlist the aid of Science anyway, since the ORM is rarely fully stocked suffeciently to pump out cure pills en masse, without compromising the other uses this resource has in the station.
* Silver: same as gold.
* Lipolicide: cannot be synthesized by Medbay, has to be isolated from the only source in the game that has it: Weight-Loss Shakes from the slow-acting Hot Drinks vendor machine. Pretty awkward to produce en masse, compares to doing it once, then pressing the "Make Vaccine Bottle" button a couple of times.
* Orange Juice: cannot be made in Medbay, more often than not if no Virologist is on board to press the magic button a couple of times, patients are sent to the Bar to get some OJ, inevitably sending contagious individuals to one of the main centers of crew presence only leads to more infections, and more people making the round trip to medbay, followed by a trip to bar to spread the disease anew and complete the cycle.

In category B (difficult access and/or harmfull) you have:
* Diphenhydramine: prohibitively difficult to mass produce on chemistry, limited supply in MedVendors (enough to cure 27 crew members, which is a far cry of the amount of vaccine needed for a station of 100 people as is often the case with Paradise)
* Teporone: non-standard chem, you won't find it in the MedVendors, nor in any chemists Fridge unless this specific disease occurs, even ignoring the uncommon recipe, it's I'll advised to use it as a cure as it has an overdose limit and an pretty sizable addiction chance. (Which any miner would be happy to confirm to you, is very debilitating should you be unlucky enough) 
* Ethanol: makes you highly drunk as 10u of Ethanol contains more Ethanol than 10 of any other alcoholic drink on station, which just makes sense since it's pure Ethanol. The alternate method of mass production is to ask people to go to bar, read the entry on OJ if you wanna see how that ends up usually.
* Spacelline: extremely limited quantity, All MedVendors start with enough Spacelline when combined guarantees a cure to 18 patients. To put it this way, a single press of the magic "Make Vaccine Bottle" on the PANDEMICachine makes enough cure for more than *ten times* that. More cannot be synthesized in medbay, instead one must brave maints and the myriad of dangers and antags it houses to get more should the Vendors run out (which also sucks on another level, since Spacelline is required for treating other ailments unrelated to diseases.)

In category C (harmless and spamable) you have:
* Salt: readily available
* Sugar: highly common
* Sal Glu: the combination of both, with water, another extremely common chem. Or even acquired by getting in a sleeper or punching yourself in front of a Medbot.

The score only gets worse when we start including the naturally spawning special diseases and their cures, as only two special diseases can be said to have cures that are easily spammable by Medbay, those being Magnititis (Iron) and Brain Rot (Mannitol), with the other diseases introducing a myriad of new and aforementioned category As (Manly Dorf, Milk, Glycerol Bananas, etc...) and Category Bs (Spacelline, Diphenhydramine, Spaceline, Haloperidol, Spaceline, God so much Spaceline).

It's getting incredibly late here, so I'll try to wrap this up by saying that virologist will get his interaction regardless of what happens, since vaccine bottles are still the most accessible way for anything to be cured. It's brutally efficient and completely non-dependant on station resources or upgrades.

If anything, there being no virologist (and CMO) causes a LOT of potential RP and inter-department interaction to happen as the station struggles to come up with a suffecient supply of cure to go around, since you need at least 10u per person cured, a lot of consideration also has to be given to the allocation of these resources, versus the other uses they can have.

This is, of course, assuming the disease in question is detecetable without a PANDEMIC machine, something that is not guaranteed at all, since a lot of the new random advanced diseases can have such a varied combination of symptoms, that their Virus Stealth value will render them invisible to the Med Scanners, necessitating the use of a PANDEMIC machine by a virologist or CMO anyway, before the vaccine production step can even begin.

I'm not saying to remove Virologist to facilitate interaction and inter-department interaction. I'm saying that the Virologist should not be turned into a role that only exists in order to justify its existence, the potential good and peace of mind that a (competent) virologist brings to the station is already great, this is only made **more** apparent to the station through the absurd amount of work they have to go through to cure outbreaks when Virology is unmanned, not less.

Especially with the sheer flood of diseases each shift gets since the last rework. 

It always feels good to see a virologist on the crew manifest, even when you don't get the urge to call the shuttle when you *don't.*

**Comment by CinnamonSnowball** [comment]
> There are diseases whose cure can ONLY be found by the PANDEMIC machine, and others whose cure can only be found by the Health Scanner.

As someone with a lot of Medbay experience, I'm not sure I've ever seen a disease that's _only_ visible via Health Scanner, even if it's technically possible in code; feel free to correct me with an example.
> [the entire section on cure availability]

Cures rarely need more than 10u to cure a virus. Most commonly 5u is all you'll need, and in the odd case that 5u won't work, another 5u pill will almost always solve the problem.
The only cures that are actually tricky to acquire are quite honestly just Gold and Silver. Chemistry _can_ synthesize Lipolicide and it's also commonly available in hot drinks vendors; Diphenhydramine is really not that hard to make (even though it's _not_ available in NanoMeds Plus anymore); Teporone is arguably even easier (the overdose doesn't really matter since you're only taking 10u at most at a time, and the addiction is not only very rare but also very mild); Ethanol is not that bad if you just subject yourself to 10 units of it at most; and as for Spaceacillin, NanoMeds Plus have tons of it and can be refilled via restock crates from cargo even if MedChem does not feel like going on a maintenance dive. The rest, even including Orange Juice, are indeed very easy to get (for that last one, just.. send sick people over to the bar).

On an individual note, personally I think it's safe to call the situation a problem when during a **virus** outbreak _Chemistry_ is the first to be asked for a response (making a cure), rather than **Virology**. While Virology usually _does_ eventually get poked for help, it's often after MedChem has already cured one of the patients and Virology is given a blood sample to create a vaccine (which involves pushing two buttons). Besides, while a vaccine _is_ objectively better (instant, guaranteed to work) than a cure, it's mostly just a Quality of Life thing - none of the cures are truly dangerous, and in fact a lot of viral outbreaks are mainly fought using cure pills, with a vaccine being created in the aftermath as a safety net.

Besides all that, I do believe current Health Analyzers simply show way too much info, and are a bit of a magical "tell me everything" device - and the exact virus cure is one of the things that could easily be removed, since working with viruses and analyzing them is already supposed to be Virology's job.
The removal would obviously have its pros and cons: Chemistry would have a harder time just bypassing Virology's part of the job, but as a downside, curing viruses would become a fair bit harder if there's no Virologist or good CMO around (low population hours). Whether that's something we desire or not is a more difficult question that is not just up to one person, though. Perhaps down the line viral outbreaks could be made less common, or maybe require an active Virologist, like some other events do with other jobs.

**Comment by Xsingular** [comment]
> As someone with a lot of Medbay experience, I'm not sure I've ever seen a disease that's _only_ visible via Health Scanner, even if it's technically possible in code; feel free to correct me with an example.

Example: Appendicitis.
It cannot be seen on the PANDEMIC machine at all.

The fact that visibility flags are treated separately opens the door for a lot of other procedures to be added, if someone feels like expanding the Random Event functionality in the future, some TG downstreams already have implemented a variety of medical crisis as happens in real life, and having separate recognition methods opens the road for a lot of variety.\

But more importantly, the reason why I pointed that out was to dispel the repeated statement on this PR that this is "old" or "deprecated" code: It's not, the machines implemented to work with each other, neither was coded to completely replace the other.

> [entire section on how easy it is to make cures]
Which one of these are easier then going to Virology, and pressing "Make Vaccine Bottle" on the PANDEMIC?
You mention asking Cargo for crates, mixing an uncommon 7 step chemical agent, or draining all of medbay's supply of precious Spacelline, your one tool to combatting widespread septic contaminations in the organs of recently SR's patients.
None of these are actually easier than just walking up to the virologist and requesting their specialized assistance.
I cannot think of a situation, outside of extreme spite against the current Virologist, where it's easier to sidestep their assistance completely.

In the vast majority of time, if Medbay ever stocks a cure, it's a stopgap measure until the virologist finishes the vaccine.
Synthesizing 5u or 10u is a moot point, when the virologist can make the equivalent of **2000u** with a single press of a button (since you only need 0.1u of a vaccine for it to work, instantly with zero downsides), it's just the better solution, and I have no problem with that. However, pretending that it goes unused and that virologists are useless under the current implementation could not be farther from the truth.

Another point is that even should the chemists make 300 pill of Salt (10u), this still does not make Vaccines redundant simply because of the fact that Vaccines are retroactive; you don't need to fall sick first to get the vaccine. You can just immunize yourself before ever getting infected by consuming the Vaccine first, a feat that no cure can replicate.

> Chemistry is the first to be asked for a response (making a cure), rather than Virology.
Under the implementation that this PR suggests, Chemistry _will continue to be the first_ to be asked for a cure.
Changing visibility matters little since (as I listed in my previous post) a sizable amount of cures are actually unavailable to the Virologist without MedChem cooperation. The RP and intra-department cooperation requirement is unchanged with the implementation of this PR.

A good Virologist like a good Medical Doctor, they are defined by how proactive they are. It's not uncommon for good virologists to be the first ones on the scene (Med Scanner in hand, yes) when a virus is discovered, or declared on comms.
Having the virologist around as an extra doctor with no Surgery access (let alone their unique job title) ensures that usually they are the person that CMO or Captain usually charge with locating Patient Zero in the case of an outbreak, or at the very least, finding an infected individual to identify the cure.

> Besides all that, I do believe current Health Analyzers simply show way too much info
An alternate implementation would have been to show diseases on a separate tab, or toggle. Since the current Med Scanner is capable of having different scanning modes.
In a perfect world, the Stealth value of a Virus would not be so binary, and there would be yet another Stealth value to denote viruses that can be seen Medical Scanner, but NOT the MedHUD (there was once a PR that actually suggested such a change, if my memory serves me well), so as to allow some viruses to slip by inattentive doctors that don't bother checking for diseases using the hypothetical "Viral Agent" mode on their Medical Scanners.

The problem with such an implementation is that it would unfortunately block Shock, Cardiac Arrest and Cardiac Failure from showing on the normal function of the Health Scanner, which can cause serious complications due to sheer regularity of these diseases (they are programmed to be as such in the code)

> pros and cons
I agree that virology needs some expansion, and that Advanced Disease symptoms values need some serious decompression, but I do not agree with this PR's proposed solution.

Especially not when the stated goal is to "increase interaction" with virologists, because as explained in detail over several posts, this PR does not actually accomplish that, the virologist will still get their interaction and their moment in the spotlight under the current implementation, as under this PR's implementation.

There's no replacing Vaccines, there's no replacing Virology.

**Comment by CinnamonSnowball** [comment]
> Example: Appendicitis.

Appendicitis being a disease is only an implementation detail. It's not really a disease and is not meant to be treated as such; it's more similar to an infection. A Virologist will never even have to bother with it, it's a condition fixed by surgery (though, this raises an important point that with this PR, the `cure_text = "Surgery"` will no longer show up).
Besides that, it seems there are no diseases that are exclusively hidden from the PanDEMIC, and no possibility for a random disease to have that kind of stealth either.
> Which one of these are easier than going to Virology, and pressing "Make Vaccine Bottle" on the PANDEMIC?

To even have the option to make a vaccine, you need to make the cure first (which often you don't even need to ask Virology for); after the first batch, it's easier even for an inexperienced chemist to just make another, and at that point, why not just make a bunch of it? Only reason to stop would be if/when Virology brings a vaccine, which sometimes can take a while.
> Under the implementation that this PR suggests, Chemistry will continue to be the first to be asked for a cure.

They'll be the first to be asked to _make_ the cure, but they won't know what the cure _is_ until they do a bit of extra cooperation with Virology/CMO properly analyzing the virus.
> It's not uncommon for good virologists to be the first ones on the scene when a virus is discovered or declared on comms.

The problem is that they can simply be completely ignored in this case, and often are; it's part of a Medical Doctor's job to always be on the scene, and they're often the first ones to encounter the virus since analyzing it is just as easy for them as it is for the Virologist. From that point, even if the Virologist _is_ being proactive, they still have to wait for Chemistry to produce a cure first before they can do anything! The only moment a Virologist actually gets to do something unique to their job in most viral outbreaks is when it comes to clicking two buttons on their PanDEMIC a few times, which is... a little depressing. Making it so Virology _has_ to be consulted before Medbay can properly start treating sick people would give it a bit more spotlight.
> An alternate implementation would have been to show diseases on a separate tab, or toggle.

The problem is not that the info is overwhelming due to being all in one spot, it's that it simply gives you so much info in the first place, invalidating a bunch of other tools in the process. Radiation? Why use a geiger counter when your Analyzer will tell you if the patient has a dangerous amount of rads? Broken bones, infections? Your Analyzer will tell you about most of them. A virus infection? Fear not, the trusty Analyzer will tell you exactly how to cure it. One could argue it's a Quality of Life thing, but too much QoL can be unhealthy too.
> In a perfect world, there would be yet another Stealth value to denote viruses that can be seen Medical Scanner, but NOT the MedHUD

That sounds like a cool extra stealth step, and I _would_ actually like to see that, yeah.

**Comment by Xsingular** [comment]
> [Appendicitis]

Appendicitis is a nice appetizer for a myriad of conditions that can be added, or even just ported from other codebases.
It makes sense that non-viral issues would not be visible on the PanDEMIC machine, and there can be a lot of those added so suit different cases.
Snowflaking the Appendicitis isn't the way to go at it, and again this completely neglects to discuss the cases for when a Virus is indeed stealthy enough to necessitate PanDEMIC analysis, this PR makes stealthy and non-stealthy viruses practically identical.
Yes, the "non-stealthy" viruses will be visible on the Scanner without a cure listed, but you don't need a Scanner to tell you that you're infected: the patient continuously gets repeated warning messages displayed in bright red telling them that they are infected. Sometimes even accompanied by audio prompts (coughing, sneezing) and visual prompts (sniffs, shivers etc... visible on RuneChat)
The one difference between stealthy and non-stealthy viruses is the method of the discovery of the cure, not the infection. Which this PR completely disposes of.

> ... after the first batch, it's easier even for an inexperienced chemist to just make another ...

As listed in my posts above, no, it's not easier. Sometimes, it's even impossible; a bar of silver/gold gets you 30u when used in the grinder, that's enough to cure three people, and then you're out.
And even if it was one of the cases where it is "easy", that leaves the harmful side effects that I also posted earlier.
AND EVEN THEN, if it is easy, abundant and harmless, you still cannot immunize people using it.
Let us dispel the illusion that Cures and Vaccines are interchangeable, they are not, neither functionally nor mechanically.

> They'll be the first to be asked to make the cure, but they won't know what the cure is until they do a bit of extra cooperation with Virology/CMO properly analyzing the virus.
Under the current implementation it's:
"They'll be the first to be asked to make the cure, but they won't know what the cure is until they do a bit of extra cooperation with **Doctors**/Virology/CMO properly analyzing the virus."
As indicated, the PR doesn't change that much, nor add a critical RP interaction, or departmental cooperation. All it does is make all non-stealthy viruses become functionally identical to stealthy viruses, removing depth and variety from the game.

> [the issue of ignoring Virologists]

This is not an issue unique to Virologists, it is part of the game's design to have several solutions to the same problem, usually it's the most proficient/proactive solution that gets used.
Power can be provided without an Engineer starting up the engine, the station can be re-atmos'd and bad gases scrubbed without an Atmospheric Technician, genetic defects can be cleared without a Geneticist, corpses can be stored and even autopsy'd without a Coroner, IPC can be repaired without a Roboticist.
And yet, each and everyone one of these roles bring something unique to the table, as does the Virologist. This is not by chance, SS13 is an incredibly complex game that simulates life and crisis management on an advanced research station in space, with a nigh infinite amount of variables and changes between shifts, including the type of natural threats and shortages faced, crew presence/absence, different skill levels and knowledge of various professions, on top of several different bad actors and provocateurs. 
If you want a beneficial advanced virus made, or a vaccine that can immunize the entire station against whatever dangerous infection roaming there **ahead of time**, or the analysis and discovery of any stealthy viruses, or even a specialized pair of hands to attempt all different cures for the viruses that are so stealthy not even the PanDEMIC can see, you have the Virologist. 
You cannot have any of those things while ignoring the Virologist.

> [Analyzer being too good]

While I somewhat agree, the reality of the situation prevents me from fully supporting that opinion: The biggest issue when it comes to balancing Medbay, is that you have to adjust for the lowest common denominator.

Medbay is already notorious for having inexperienced players manning it. Cargo may get neglected, Engineering may delam every once in a while, Science can blow up.
And yet none of those have a nickname equivalent to the notoriety of "Malpractice Bay".

I'm not saying that it's a bad thing that new players try to learn Medbay, or that Medbay is an outlier in how many accidents resulting from lack of experience happen.
The nickname, I would argue, comes from the sheer desperation of the crewmembers that require Medbay's services, a single wary stab or bullet can cause you Internal Bleeding, which will eventually lead to your death if Medbay (over the course of many many minutes) fails to stem the flow. Even drinking too much at the bar can get you killed if Medbay isn't on the job. Every single PR addressing Medbay balances had to acknowledge that no one wants to be removed from a 2 hour shift, by an issue that would take an experienced doctor 15 seconds to solve.
And this is what has to be taken into consideration here, the beginner that has no idea what is going on, as we as the low-pop shifts that have no CMO or Virologist (and sometimes, even no AI), the shifts were everything goes wrong in such a spectacular fashion that certain functions and services are inoperable... etc

The Health Analyzer when upgraded, serves as a good first stepping stone to understand what kind of reaction is required from the doctors. Internal Bleeding detected, you can skip the Body Scanner completely if the patient tells you what hit him, and where.
Broken limbs? same thing. Radiation? sometimes you don't even need the scanner, they glow extremely brightly when contaminated enough, deducing the presence of radiation with it isn't rocket science... etc
And yet, there is always the elevated level of complications, the one that the Analyzer doesn't tell you.
Patient dead, so you have to locate the IB and broken bones and fix on your own before reviving? Septic internal organs? **Stealthy Virus**? Missing organs? For these, you have to investigate deeper. This is the elevated level of investigation and identification.
Back to the topic of this discussion, PanDEMIC serves the purpose of the elevated Viral investigation, the unique role it fulfills which cannot be replaced by any other machine on the station.

> That sounds like a cool extra stealth step, and I would actually like to see that, yeah.

It indeed would be a better solution to this issue without removing depths or adding unnecessary obtuseness.

Just off the top of my head, here are some other nice solutions/additions: 

* Adding more symptoms that don't change the experience of the infected patient, but only modifies the statistics of the virus (think more symptoms like Viral Evolutionary Acceleration, and Viral Adaptation, Eternal Youth etc...)
* Rebalancing of existing symptoms weights and modifiers on Stealth (as well as other values) to make random occurring viruses naturally more stealthy, indirectly reducing the effectiveness of the health analyzer.
* Decompression of the Stealth stat, changing the flags from simple visibility to visibility and visibility+cure, and adding a whole new tier for MedHUDs: A virus can vary from detectable by everything to ==> only undetectable by MedHuds to ==> only undetectable by MedHud + cure unidentifiable by Analyzer to ==> undetectable by MedHuds and Analyzers completely to ==> undetectable by MedHuds and Analzyers + Cure cannot be seen on PanDEMIC ==> Cannot even be detected by anything.
* Making the PanDEMIC a Machine-type instead of a Console-type, with upgradable parts, which increase its capability of detecting stealth levels. Another part would govern how quickly the PanDEMIC can synthesize Vaccines, or how many symptoms can be included in a synthesizes Virus vial... etc
* ANY combination of the above, sky's the limit.

I've been playing SS13, and Paradise specifically, and Virology more specifically for more than 6-7 years now, and I have a lot of experience with this codebase and others (even if I rarely submit to it). I hope I've been able to demonstrate my familiarity with these things in the course of this discussion. **AND YET** I am certain that there are people (with more playtime or less) that have even better and more unique solutions to give Virology more zest, more flavor, more fun.
 
In so many words: this list is not exhaustive.

Simply deleting two lines of code because "Virologist doesn't feel important enough." is the bad way of going about it, it's oversimplifying a (admittedly minor) problem and going for the most superficial solution.

**Comment by LynxSolstice** [comment]
So these are all cool great ideas you bring up but my pr just addresses what I personally can code, please write up a design doc asap because my pr is going to be lost in a sea of other MINOR CHANGES. I hate to say it, but you're wasting your time typing all this stuff up on a relatively small PR that just seeks to add a relatively minor qol change for the virologist that I ran into as a viro, people always considered me as an afterthought (ouch) because they can just, mass produce cures for anything that comes up without ever consulting me on the possible cure. So I saw it as a minor issue between medbay and virology that doesn't have a place anymore as I was told it was a remnant of a former medical system before viro existed.

**Comment by LynxSolstice** [comment]
My pr was not and never would have been intended as a rework of virology or the virus system, it's merely removing a small part of an old system in order to encourage working with the viro during an outbreak beyond just scanning someone, curing the virus, asking viro for a vaccine and then never speaking to them again.

**Comment by Xsingular** [comment]
I don't mean to discourage you from coding or contributing. But as it stands this "minor QoL improvement" will only lead to a very very small increase of interaction with Viro, while bringing major downgrades to different aspects of the game design.
I've played virologist really often, it's one of two professions I have set to "Medium" on my main character, and yet anecdotally, I've never had a case were people went through so much effort to avoid interacting with me, only to get an inferior result, since cures can never match vaccines.
Maybe it's the way I make my presence known on comms when I'm making a virus In virology, or maybe it's my constant presence at the frontline with them the moment I'm done distributing my healing virus.


I mentioned lack of variety on the stealth values, and I'll be honest with you, the same problem exists with the cure difficulty values; it's not uncommon for the cure of the virus to be salt, most of the time.

If people were going out of their way to not get the amazing invention that is Vaccines by ignoring an absent or non-proactive virologist, the same people are probably just as likely to spam the most common cures at the front desk anyway, again going out of their way to avoid to ignore interacting with a slow or non-proactive virologist.

I don't think the price is worth it, an imperceptibly small increase in forced interaction with the virologist, in exchange of causing a lot of undue hassle for not just doctors, but literally anyone infected.
Simultaneously raising the skill floor (for Doctors) and lowering the skill ceiling (for Virologists) just adds needless frustration for patients dealing with new Doctor hires, and removes depth from the virologist role that we both agree is already lacking depth as is.

It is my personal opinion that the best solution for the problems you encountered remains within the boundaries of the game itself, not on GitHub. Try to change your approach, make a name for yourself, perfect your art beyond the point that is deemed suffecient, people notice these things. Why, "Henk De Fries" is still considered a legendary virologist despite not playing that role regularly for years, people have surprisingly long memories. I believe the most recent balance pass that Viro had was authored by him.

Unfortunately, there will always be people who just won't like it no matter what you do, and will avoid interacting with viro at any cost anyway. Nothing can change that, _not even this PR_. But that's just how people are sometimes...

With time, and enough passion for the role I am certain you'll make a legendary Virologist, and maybe even make that Viro re-work we've all been dreaming of.

**Comment by LynxSolstice** [comment]
> Additionally, another point we haven't brought up is the wiki. Since the disease is visible on the Scanners anyway, unless it's a randomized Advanced Disease, any doctor can literally know the cure instantly by using the wiki to look it up, again side-stepping virology completely. Assuming the wiki is edited to remove the cure for those diseases, unfortunately this GitHub will always have them visible, so again it's simply a matter of typing the non-advanced disease's name in the search bar.

I had the full intention of completely removing the virus code from the scanner entirely, however it was mentioned that if a doctor could not see the disease name they would be unable to efficiently administer a vaccine, so the only thing affected was the section that showed the cure.

**Comment by LynxSolstice** [comment]
I wasn't expecting this to be such a disputed issue but I suppose next time I should keep in mind that touching medbay in any shape or form pisses people off, I just hope it perhaps gets by and hopefully we can see if it affects anything at all in the medbay meta. I think the discussion here was good but ultimately out of scope.

**Comment by hal9000PR** [comment]
1 objection nobody in favour after 30 days. closing

**Pull request closed without merging**
