### PR TITLE
Nuke Op items discount & rebalance

### PR DESCRIPTION
**Pull request by Anasari**
Reduce cost for some underappreciated items in the nukie arsenal. Also remove syndicate hardsuit from the nuke op purchase list, as it is just a redundant noob trap. Traitor items split off into #8315

Feedback highly welcome, since I am not an expert on this. No cost increase are intended, I'd rather see underappreciated items used more. 

List of price changes:

**Nuke op:**
Flamethrower (For nukie): 11 -> 8 (The fact that they cost as much as a SMG seems to make em a bit too costly, given their much lower destructive potential. They do have CC potential so I am not sure though)
Viscerator: 8 -> 6 (Too costly for its effect and vulnerability)
Assault pod: 30 -> 25 
Teleporter: 40 -> 20 (Way too expensive for something you can do for free)
Soporific .50: 6 -> 3 (For some non-lethal round that doesn't even fit with a loud as fuck sniper, they are 50% more expensive than normal ammo.)
Sarin gas: 15 -> 12 (Compared to atmos nade, they are more expensive and less mass destructive, even though you get four of them. Besides, they are also timed and not cluster) 
Combat Medkit: 9 -> 7. Stetho & lethal syringe removed. Burn & brute patch replaced with four synthflesh patch. 
Syndicate Hardsuit: **Removed from nuclear op due to being a noob trap**
Dart gun: Removed from nukie
Rapid Syringe Gun: Added to nukie for 4 TC

🆑
tweak: A lot of underused nuke op items made cheaper.
tweak: Syndicate hardsuit removed from nuke op because you already got one free.
tweak: Tactical medkit give you four synthflesh patch, no more stetho or lethal syringe.
add: RSG added to nuke op uplink. Dart gun no longer available.
/🆑

### CODE REVIEW

**Comment by Spartan6** [comment]
The stetchkin is under-appreciated? I see users of it daily.

**Comment by Anasari** [comment]
Reverted the stetchkin change. Made syndicate hardsuit unpurchasable during nuke op. It was serving no purpose other than that of a noob trap.

**Comment by SamHPurp** [comment]
`Binary Translation Key: 5 -> 3 (Underused, though one can argue it is really powerful)`

Unsure I agree on this one. Super duper powerful.

**Comment by Kyep** [comment]
Yes. There are probably even more items beyond this which are mispriced.

**Comment by TDSSS** [comment]
The Binary Translation Key costs 5 to the Syndicate Key's 2. I'd argue the latter is a lot more useful than the former. Listening in on the AI and borgs shouldn't cost 250% as much as listening in on command, sec and communicating with other traitors.

**Comment by SamHPurp** [comment]
@TDSSS You clearly haven't had a binary key and subverted the AI then ;)

**Comment by SamHPurp** [comment]
Also @Anasari anyone send you my excel file - which details tot item purchase rates. Its a bit outdated as its 2016 data, but not much as really changed since then.

**Comment by TDSSS** [comment]
> @TDSSS You clearly haven't had a binary key and subverted the AI then ;)

And you couldn't simply talk to the AI via PDA messages and save yourself 25% of your total TCs for something else?

**Comment by Anoonki** [comment]
@SamHPurp The binary translator's a really counterproductive item *on it's own* though, without a subverted AI. 
With a subverted AI, the combo is brutal, but without, all it does is gets the AI to rat on you, and with the current Sillycon players, listening to what's being said in binary isn't the most helpful thing ever.

**Comment by Anasari** [comment]
@SamHPurp I did get the excel file. I'm going to look through it and see what other items need rebalancing.

**Comment by mrturkeytoe** [comment]
@Anasari Minibomb is stupid over priced.

**Comment by imsxz** [comment]
C4 is definitely underused but I've got no clue why. It's already 1 TC and is fairly strong if you don't have access to thermite, or need a locker open without wanting to spend 6 TC for the emag... Perhaps make it always destroy the reinforced walls it's on, and make it work on airlocks too?

**Comment by ktoma36** [comment]
The one time I ever saw C4 being used was when I was a janitor. Walked into maint, saw it, went huh, and tried to mop it. It only knocked a few of my limbs off, didnt even hurt me enough to throw me into hard crit.

**Comment by Anasari** [comment]
New changes pushed with nuke op items cost reduced. The combat medic kit also has its contents reworked. The rationale for removing the three items is that they're useless, save for combat defib which make for a very poor weapon at best.

**Comment by jughu** [comment]
@Anasari it isnt a nuke trap the syndiehardsuit its needed to hardsuit up any bought reinforcements

**Comment by Anasari** [comment]
I'm pretty sure our codebase don't have any feature to buy new operatives. If one is spawned by a badmin, they can always be clothed properly

**Comment by imsxz** [comment]
Combat defib is a great weapon IMO. It's a guaranteed 5s stun at the LEAST. If your target has a heart, it's an effectively infinite stun, and is certain death for the victim provided their heart isn't restarted within a minute or so. Additionally, it has infinite charge, and also can shock targets through hardsuits. I'm not even sure it can be blocked by shields, though I'll have to check.

While its actual medical capabilities may be limited on a team of operatives who explode on death, it *can* be used to save the ones who's hearts have been stopped by chest trauma, or similar defib cheese (which I have seen recently, as any defib can have its safeties disabled, and the syndie Depot has a tactical medkit which people have been raiding frequently).

Finally, while there's been talk of removing the syndie depot, antagonists who raid it can make great use of the combat defib. For reasons stated above, it can easily be used to assassinate a target if they have a heart to stop, as it will immediately knock them unconscious from the heart attack. They can also use it in normal combat against targets without hearts too, for reasons stated above.

**Comment by Ssirius** [comment]
The only thing I would disagree with is the removal of the combat defib from the combat medkit since it makes an amazing, challenging, and fun weapon after emagging as mentioned before, everything else seems quite reasonable although most of these items even with the new prices are still not worth it.

**Comment by mrturkeytoe** [comment]
I feel like the stethoscope and combat defib should stay

**Comment by Shadeykins** [comment]
The combat defib requires you to give up your belt slot (which is what's going to be holding all your ammo/weapons, removing it is a loss of 6 item slots), must be wielded in both hands (meaning no shield usage with it), snaps back if you're knocked over and drop the paddles (meaning you need to toggle and re-double hand it if you get even remotely stunned), is melee range only, and requires emagging to be weaponized.

Its effects can also be immediately blocked by the use of a single, easy to produce chem (Corazone).

It is a pretty awful tradeoff that greatly hinders both the operative using it as well as their team-mates, especially since people who take the kit are ostensibly trying to play 'support'. The lethal syringe and stetho are genuinely useless as well.

Great for assassination? Sure.

Great for ops who are almost universally engaged in firefights, are a team-based antagonist, and face enemies with tasers and disablers? Not really.

**Comment by taukausanake** [comment]
> ass-ass-i-nation

I can't ever unsee that

~~Ass Nation when~~

**Comment by mrturkeytoe** [comment]
@Shadeykins Actually the combat defib comes emagged by default.

**Comment by imsxz** [comment]
I don't actually know if I've ever seen corazone produced, much less used, *much less* carried around by a doctor and ready to be used in time to save someone from a heart attack.

I've never used the combat defib as a nukie, and can't imagine it would be too useful outside of a silly gimmick weapon for a veteran player to use. Though, I've used it quite a few times as a normal traitor with large success, even in combat when paired with some stun resist or speed enhancement.

I guess I'm just trying to say, I dislike that it's being removed entirely from the medkit, without even being issued reimbursement, just because "it's useless". It has its place, even for non nukies, and I don't wanna see it removed without a substitute. If it's such an underpowered item that I'm just giving too much credit, then at the very least keeping it included won't affect balance or discourage anyone from buying it.

Perhaps if people are willing to remove it so much, we could find a replacement for it? Otherwise I don't see the purpose in removing it, as it's not being replaced with anything, and clearly isn't overpowered or otherwise demanding removal.

**Comment by taukausanake** [comment]
@mrturkeytoe Wait, the stethoscope _actually_ has a use outside of making you look more like a doctor? I must know what this is

**Comment by mrturkeytoe** [comment]
@taukausanake You can crack the vault safe code with it. And I agree with imsxz on keeping the combat defib in the medkit, it's a !!!FUN!!! gimmick

**Comment by Anasari** [comment]
I didn't expect the defib to be that popular. So here it is, re-added. The discount might make a lil bit more viable.

**Comment by KingPhilipIII** [comment]
Maybe reduce the cost of dehydrated space carp too. For a friendly space carp that most people can easily kill without any severe bodily harm, three crystals is way too expensive.

**Comment by Shadeykins** [comment]
@imsxz @mrturkeytoe @taukausanake 

It's re-added courtesy of Ansari, but you guys DO realize this is a nukie-only item right?

You can't get this shit as a regular tot sans the outpost, which remained unchanged.

**Comment by imsxz** [comment]
Yes but I've raised the outpost for it loads

**Comment by Regen1** [comment]
>Binary Translation Key: 5 -> 3 (Underused, though one can argue it is really powerful)

It IS really powerful, don't nerf it to 3, and make it an item that all traitors get always

**Comment by Anasari** [comment]
Reverted the change to binary translator key price.

**Comment by jughu** [comment]
Binary key isnt powerfuller then a syndikey

**Comment by TDSSS** [comment]
Revert that revert, Binary Key has no right costing 5 TC

**Comment by uraniummeltdown** [comment]
Yeah the binary key is not really powerful at all. Syndikey is way more useful, being able to hear every radio channel and get a dedicated traitor channel is way more useful than hearing the AI and borgs talk about stupid meatbags

**Comment by jughu** [comment]
Binary key is pure situational when you murder with borgs but again you can get the same affect by changing frequencies

**Comment by ktoma36** [comment]
Also takes up one of the two encryption keys for your headset and while that could be countered by simply wearing another headset it looks a bit conspicuous

**Comment by Varghh** [comment]
Lovely, I need to check the whole list to see of anything else has a weird price.

**Comment by KingPhilipIII** [comment]
@Varghh

Dehydrated space carp. 

A single use fish that can be killed quite easily with melee or a laser gun if available has no right costing 3 TC.

**Comment by taukausanake** [comment]
I think having an army of spesscarp (even if they all die quickly) would be fun to do as an antag. Maybe something fun could be done with it and something else. I could imagine making a kill room filled with carp and teleporting people into it. That would be cool

**Comment by Doukhan** [comment]
Keep the price the same and have it spawn a megacarp, then it's fair and balanced (tm).

**Comment by Jountax** [comment]
I feel like the whole kerfuffle about the combat defib overlooked the fact that nukies can go stealth. They almost never do, but I for one would like for the option to exist.

**Comment by Bigtimetripod** [comment]
RSG for nukies is great and all... but where do they get the syringes for it?

**Comment by Kyep** [comment]
Bioterror syringes?

**Comment by Bigtimetripod** [comment]
Bioterror are mostly for stealth missions. Maybe add a box or two of empty syringes in the shuttle so a more knowledgeable Nukie could mix some other stuff. Beaker or two also, where to mix the stuff.

**Comment by Shadeykins** [comment]
You can't mix traitor chems, which means what the bioterror syringes have is already superior to anything an op could dream up in a reasonable amount of time.

**Comment by Bigtimetripod** [comment]
Who said i would be mixing traitor chems? Its known from the dawn /tg/chem that traitor chems cannot be mixed. I was thinking something about a lone operative runs around the station with RSG filled with sarin/cyanide syringes. Without medical aid, can kill in about a minute. Bioterror syringes just long stun, they do not kill.

**Comment by TDSSS** [comment]
Maybe just add a few syringes with some nasty but not traitorchem level chems to the rapid syringe gun, so it's actually useful on its own? Buying a weapon means it comes loaded too, after all.

**Pull request merged**
