### PR TITLE
AI control beacons for mechs

### PR DESCRIPTION
**Pull request by uraniummeltdown**
https://github.com/tgstation/tgstation/pull/23320

AIs can jump to and from the mech at will, unlike malfunctioning AIs that dominate mechs.
Malfunctioning AIs must dominate mechs if applicable and cannot control one through the beacon.
If the mech has a pilot, it cannot be controlled.
Created from the exosuit fabricator with 1000 metal, 500 glass, and 200 silver. Research levels are programming 3, magnets 2, and engineering 2. 

:cl:
add: AI control beacons are a new item created from the exosuit fabricator. When installed into a mech, it allows AIs to jump to and from that mech freely. Note that malfunctioning AIs with the domination power unlocked will instead be forced to dominate the mech.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Does this get added on a mech like the tracking beacon or like an equipment slot?

**Comment by uraniummeltdown** [comment]
Like a tracking beacon

**Comment by Spacemanspark** [comment]
Interesting.
:+1;

**Comment by Xantholne** [comment]
I like this idea well. It makes a subverted AI even more scarier along as makes AI even more helpful and more interactive rather than a voice over comms that can open doors like magic. Can allow an AI to take control of an Oddysseus to rescue people in need.

**Comment by Crazylemon64** [comment]
Looks good me too

**Pull request merged**
