### PR TITLE
Adds a new cyborg skin, "Rover"

### PR DESCRIPTION
**Pull request by ExusA**
## What Does This PR Do

Adds a new selectable cyborg skin, "Rover".
The design of this cyborg is based on two of the more popular models people use in-game, Standard and Mop Gear Rex. On one side, I think Standard has a slightly cutesy look to it that people enjoy, while Mop Gear Rex is ultra-functional and looks like a purpose-built machine. The Rover is meant to look a bit cute and a bit functional. 
I aim to add a version of this for each normal module, but I'm starting small to keep things simple.
This one is for the Engineering module.

## Why It's Good For The Game

While there are quite a few cyborg models available, this one aims to fill an otherwise unfilled niche. On the other hand, having too many models could end up being bloat. I think some of the ANCIENT ones that nobody ever picks could stand to be gotten rid of, since a good few of them cover the same ground design wise.

## Images of changes
Roverborg1
roverborg2
roverborg3
roverborg4
roverborgempty
roverborgoff
roverborgopen
roverborgopen2
RobotRover2

## Testing

Opened and closed panel, exposed wires and replaced cell with empty cell to see unpowered sprite.
Took screenshots in different lighting environments.
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imageadd: Added a new cyborg model, "Rover".
/:cl:

### CODE REVIEW

**Comment by ExusA** [comment]
Okay, I've linked my account now. (I hope)

**Comment by Scribble-Sheep** [comment]
Nice. A lot of the borgs feel very "anthropoidal," while this one feels like it's an actual like. Machine. Fills a niche that I'm sure a lot of people were missing~

**Comment by Fordoxia** [comment]
I love them! A good lil' guy. An adorable construction equipment.

**Comment by ExusA** [comment]
Thinking on it, I'm not in love with the name, if anyone has any better suggestions? Here's a picture of an _early_ draft I have for the Janitorial module to clarify the features each module are going to have in common.
Janirover

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
