### PR TITLE
Increases most radiation dose amounts

### LINKED ISSUE #15819: Radiation is extremely slow.
**Issue Description**:
Do note. I'm not exactly sure if this is a bug or not, it _seems_ to me that it is, but it might not be. Bare in mind this is NOT taking into mind contaminated objects, I did not test this, just straight radiation.

Essentially, damage from radiation is basically nonexistent until you reach 500 rads. Even at that point it's so extremely minor that it's a mere inconvenience, by this I mean like. 1-2 toxins here and there and nothing more. It took me roughly 18 minutes for hair to fall out, 816 rads, and toxins to reach 56 damage, bare in mind at this point it was more the toxins from the liver damage that was damaging me more than the radiation. It took 23 minutes, 1.1k toxins, and around 30 liver damage to finally enter crit. 26 minutes to kill, and that death was mostly because RNG deemed it so.

**What did you expect to happen**: 
I expected radiation to be a tad more lethal, rather than something you can not care about. This test was done standing next to uranium golem, naturally radiation will scale higher with more radiation producers. The golem also did not irradiate any objects at all, other than the test mob.

**What happened instead**:
It took roughly 1/4th of the round to actually die from radiation exposure, and most of the death wasn't radiation related.

**Why is this bad/What are the consequences**:
If this is a bug, it makes essentially any form of radiation barring massive doses I.E the SM trivial.

**Steps to reproduce the problem**:
1. Get radiated.
2. Wait

**When did the problem start happening**:
Presumably since the radiation refactor.

**Extra information**:
If this ISN'T a bug, then that's my bad. Do note this isn't intended, in any capacity, to be a feature request. From my point of view, this seems like a bug.

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR makes people take 10x as many rads from all sources bar the SM crystal. This is done by multiplying radiation by RAD_DOSAGE_MULTIPLIER (currently 10), this number is easy to tweak in future for balancing and affects all rad sources to keep them consistent.
The SM delamination rad dosage is now also 4-40x as powerful depending on the engine power (EER) at detonation.
This somewhat fixes #15819

## Why It's Good For The Game
Since the rad refactor in #15331 most radiation sources give such trivial amounts of rads, you won't feel a thing. You could make a full uranium room and be fine.
This brings radiation values in line with the SM dosages, as that was the only source that was properly implemented into this new system with the rad refactor.
This does not mean that radiation leads to instant death, and it does not tweak the SM radiation doses as they are fine, but it does mean that radiation is no longer just a joke.

The 10x value comes from looking at how many rads you get from the SM, plus how many rads you currently get. In #15447 anti-rad chems were made 10 times more effective to deal with the SM rads.
Both these chems and old rad sources didn't get updated with the refactor, so the SM rad doses were nearly impossible to fix. The change to the chems however further invalidated other rad sources. This PR balances this all out.

## Changelog
:cl:
tweak: Non-SM radiation doses are now stronger
tweak: SM delamination now more strongly irradiates the station.
/:cl:

### CODE REVIEW

**Comment by Wojz** [comment]
Once more xray laser spam, when reflected at crew, becomes an actual danger, instead of a minor annoyance. Blobs rejoice. Oh and this also fixes radblob and a bunch of chems, cool.

**Comment by AsrielFBI** [comment]
:thumbsdown: just use TEGs

**Comment by Wojz** [comment]
> 👎 just use TEGs

but what does this have to do with the SM, that's like the one thing that is staying the same in this PR

**Comment by AsrielFBI** [comment]
> 
> 
> > 👎 just use TEGs
> 
> but what does this have to do with the SM, that's like the one thing that is staying the same in this PR

instead of using the rad of the sm for energy production, use the heat of the sm for energy production. And thats accomplished by using the chad TEG instead of the virgin rad collector

**Comment by S34NW** [comment]
> 
> 
> > > 👎 just use TEGs
> > 
> > 
> > but what does this have to do with the SM, that's like the one thing that is staying the same in this PR
> 
> instead of using the rad of the sm for energy production, use the heat of the sm for energy production. And thats accomplished by using the chad TEG instead of the virgin rad collector

The actual hell are you on about

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
