### PR TITLE
Rebalances CQC, add extra features

### PR DESCRIPTION
**Pull request by datlo**
Alternative pr to #10327

Cost of CQC raised to 10 due the added features below and that after testing it on live/discussing with other players it's pretty damn robust against non-security.

Block nerfed, now only works with both hands empty.

New features : 

- CQC can now be used when holding a pistol in hand. (10mm, HOP mini energy gun, ecrossbow, mime Finger Gun, and wizard wands). Combos will be added to your gun bash, and grabs will work but go on your other hand, if empty.

- If you know CQC, you can attach a knife to any of the pistols above, minus finger gun, in order to wield the pistol and the knife at the same time. You will shoot with the gun, and attack in melee with the knife. Click on the pistol with an empty hand to take the knife back.

- Added the survival knife in the code, force of 15. (for reference, Kitchen knife has force at 10 and combat knife has force at 20). It will also be spawned at a low% chance in maintenance.

- A new syndicate random bundle is added to the list, containing the CQC manual, a silenced pistol, 3 mags of various ammo types for it, a survival knife, a bandana, a thermal eyepatch disguised as a regualr one, and a cigar.

tacticalespionageaction

- Bond bundle buffed to also have various ammo types (ie more ammo) so it doesn't feel left out.

🆑
tweak: CQC cost raised to 10 TC.
tweak: CQC block now only works with empty hands.
add: You can now use CQC combos while attacking with a small pistol in hand (10mm, mini egun, ebow)
add: If you know CQC, you can now attach a knife to the pistols mentionned above in order to boost their melee damage
add: Added the Tactical Espionage Action bundle to the random syndicate bundle.
add: Added the survival knife, found in the Tactical Espionage Action bundle and in maintenance.
add: Added the disguised thermal eyepatch, found in the Tactical Espionage Action bundle.
tweak: Bond bundle buffed to have additional ammo magazines.
/🆑

### CODE REVIEW

**Comment by KasparoVy** [comment]
Now we HAVE to re-add Big Bossed.

**Comment by ScratKnapp** [comment]
Much better.

**Comment by datlo** [comment]
@KasparoVy Afraid I'll have to keep you waiting, still thinks it's best not to have it on paradise.

**Comment by davidchan13** [comment]
Needs inflatable decoys.

**Comment by ScratKnapp** [comment]
Decoys that say "You're pretty good" and "Kept you waiting huh" on loop.

**Comment by datlo** [comment]
Attach_melee could easily be used for stuff such as attaching bayonets in the future, but I get you. Should I change the code to have the procs in CQC itself and not in the gun object?

**Comment by datlo** [comment]
Rebalancing of CQC is still being discussed, I'm closing this for now.

**Comment by shazbot194** [comment]
[there is a is pistol check, why not use that?](
https://github.com/datlo/Paradise/blob/667c44fd3c1e6a9d5ec4a598aba70aeeca6732df/code/modules/projectiles/guns/projectile/pistol.dm#L1)4

**Pull request closed without merging**
