### PR TITLE
Fire Cult sprite overhaul

### PR DESCRIPTION
**Pull request by SteelSlayer**
## What Does This PR Do
Sprites by @McRamon

Overhauls most of the fire cult's sprites. The new theme is more of a demonic/underworld/hell theme. Purely a sprite change, no gameplay changes. However the fire cult's constructs have new names now:
- Artificers are now **Summoners**
- Juggernauts are now **Incarnations of Pain**
- Wraiths are now **Hell Knights**
- Shades are now **Ifrits**
- Harvesters are now **Lost Souls**

## Why It's Good For The Game
Higher quality and more cool looking sprites. Also adds thematic sprites for some of the fire cult's buildings and items that didn't exist before and were just copies of the Nar'sie things.

## Images of changes
Line-up of most of the new sprite changes:

The constructs from left to right: Incarnation of Pain, Hell Knight, Summoner, Ifrit, Lost Soul.

GIF

The fire cult's new god, Kha'Rin and his summoning animation:

ee

## Changelog
:cl: SteelSlayer, McRamon
tweak: The fire cult's construct, harvester and shade names have been changed.
imageadd: Completely overhauls most sprites related to the fire cult theme, including airlocks, buildings, the tome, constructs and more.
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
This looks absolutely amazing. Yes.

**Comment by nok-ko** [comment]
All the yes.

**Comment by datlo** [comment]
This can be merged before blood cult, there will be small conflicts but fairly easy to fix.

Also this is some good shit

**Comment by SteelSlayer** [comment]
Yeah sorry about those conflicts. At least I got all of the framework done with the reaper one so I only have to touch 1 file this time.

**Comment by datlo** [comment]
dw bout it this is great

**Comment by KasparoVy** [comment]
That's badass as fuck. Even if the cult donks out at least they look goddamn legit

**Comment by Aurorablade** [comment]
this seems like its own cult subtype cause i would much perfer to keep fire cult a fire cult then REND AND TEAR DOOM

**Comment by McRamon** [comment]
i support this 🌚

**Comment by MRgaty** [comment]
so metal

**Comment by McRamon** [comment]
@kyep but death cult is already renamed, so whats the difference. New names support aesthetics of mobs. And i doubt that is really that hard thing to learn compared to other things in game. Though we (i) probably should update wiki to include cult types names

**Comment by Fox-McCloud** [comment]
Big thumbs up 👍

**Comment by trololiver112** [comment]
Next time the cult wins we could instead of fleeing for our life just take a moment to enjoy the show.

Yes please

**Comment by Spacemanspark** [comment]
Holy fuck, yes

**Comment by Dinarzad** [comment]
E1M1 intensifies.
Seriously, those are dope as hell.

**Pull request merged**
