### PR TITLE
Improves human race sprite reshading

### PR DESCRIPTION
**Pull request by Puckaboo2**
:cl: Puckaboo2
tweak: Improved shading of human sprites.
/:cl:

image

At first glance, you won't see most of the changes I have made right away, but I will explain all of them, one by one.

I shall start with the female's head.
image
As a warning, I don't really need to show the male's head comparions. As you can see, I modified the blush on the south, east and west sides to make it a bit more pleasant to look at. It is mathematically shaded to be the exact color of each shade of the human skin, but minus ten hue; as a result, the blush is not too intrusive to the overall facial features, but it is not darker than the actual skin tone, either. Additionally, I added a bit of shading to the back of the head of the females and males, while giving the males a little shiny area to their head, cuz sweg.

I want you all to look at the female's body, next.
image
Nothing much changes from the front of the normal female sprites, or the back, aside from the one-pixel reduction to the side of the waist, to give a more slim appearance (clothes don't need to be re-sprited) and the shading on the buttocks. Most of the modifications appear when you turn the female to the side, because there were some anatomical and shading issues.

Just to point out, I am showing you just the torso of the before picture, not with the arms and not with the hand. As you can see, in the before picture, you can clearly see the outline of the arm (which makes it appear the arm is still there when it is supposed to be absent), while you can see the empty socket of where the arm should be. 
image
In the after picture, I resolved the issue by removing the outline of the arm, shading the side, and making the amputated arm's socket more noticeable. Additionally, I made the shading around the front and near the breasts a lot more pleasant to look at. 

Now, let's look at the male's torso.
image
It always struck me as odd how little detail there always was in the chest and torso area of the male when he faces south...There was just nothing there, just two nipples and a belly button. So, I decided to spice up the south sprite a little bit by adding very subtle pectoral muscles and a very tiny four pack. Beefcake.

Not much changed on the sides, aside from the change of shadowing to the rear. I also shaded a little bit of where the groin should be, just to close a small shading gap that doesn't look pleasant when viewed up close. I also patched up the shading to where you can see the indent on the sides when the arm is removed.

Additionally, I updated the shading of the fat sprites.

Let's start with the females.
image
I did not modify much of the front and the back sprites, other than smoothing out the belly, reducing the shading of the back, and making the buttocks appear more smooth and defined. Aside from smoothing out the shading on the belly, the sides received heavy modification:

The 'obvious-arm' issue was not present, but the glaring reddish blob where the hand should be, perplexed me. 
image
You should only see bare skin on waist and hip after an entire arm amputation, not a huge red blob...So, I removed it. I also fixed the female's breast to the side because it resembled a male's man boobs more than anything else.

Finally, the fat males.
image
Pudgy males don't have pecs, anymore! They have bonafide, certified, moobies! Aside from the change in the shape of the chest (or now, moobies,) males are pretty much a mirror image of the females, including the removal of the red blob. I also modified the breast to the side so it doesn't look like a slab of flappy skin and more of a massive male mammary.

Well, that's it! Maintainers, I am willing to make further changes if you don't find some of the current ones to your liking.

### CODE REVIEW

**Comment by taukausanake** [comment]
You just wanted to give males abs, admit it. 😛 
And apparently females slimmer waists? Is this going to do anything to clothing sprites? I'm thinking it doesn't matter about smaller mobs but I have to ask still

**Comment by Ty-Omaha** [comment]
I dislike the abs tremendously, it makes it look too busy, and I don't think everyone on the station should have a 4/6 pack including humanized monkeys.

**Comment by KasparoVy** [comment]
We're space men. We have two settings: buff or blob

**Comment by Puckaboo2** [comment]
@taukausanake No, no modifications need to be done. I can revert to the old shape easily if people have too much of a problem.

@Ty-Omaha That is possible, and I think thst would be for the best, but there is coding involved in it and I don't want to mess with the code too much. @KasparoVy Wanna hit me up on Discord and we can work this out?

**Comment by Necaladun** [comment]
That weird missing hand red blotch thing is weird. Looks like itd be there for a reason but fair chance it isnt too, want some confirmation on that.

Can you put some shots of them in game so i can see it not in isolation? I think im over analyzing every pixel. 

The abs i do find a bit weird but it might work in game more than on a white background

**Comment by IcyV** [comment]
I honestly don't think I really like it too much. I would also appreciate the male head comparison you don't want to include just to have it. Each little thing is important, especially in the context of sprites.

- The abs don't really look that great and feel a bit unnecessary. I could see them maybe being an option that people can choose but it's weird as the default. It also means every non-fat human male is in good physical condition which takes away a level of character creation.

- The female body doesn't really seem like it needs to be narrowed even more. I personally think it should be widened to be the same shape as the male body. Your waistline also looks like it just teleports in now and suddenly goes straight up rather than being a slope in. Your way with the square between the arms and the torso is extremely eye-catching as well. It's hard to not be drawn to this large gap in the middle of the body.

- There is now a lot of focus on the breasts with the shading. I don't really see why that is a needed change. The side view for the female also has a raised breast for some reason. It makes it looks much more flat or perkier but I don't really see a corresponding change to the other views.

- The makeup change is odd too but that's more my personal preference. I think the makeup should be taken out altogether and made more reliant on the actual makeup in-game.

- Removing the emphasis on the top dot on the back for both torsos makes it seem like there are breasts on the back. The raised dot in the middle helps to not give that impression when it was more defined.

All of these changes make me kind of wish we had multiple types of bodies to pick from rather than a single style. It would add a ton of variety to humans and would be a nice breath of fresh air for their design.

**Comment by Puckaboo2** [comment]
I might close this and post it again after I make the proper changes.

**Pull request closed without merging**
