### PR TITLE
Revert "Cyborg Rebalance"

### PR DESCRIPTION
**Pull request by Regen1**
Reverts ParadiseSS13/Paradise#494
There was still discussion about this change, why was it merged?

### CODE REVIEW

**Comment by Earthdivine** [comment]
In addition to discussion, people who might have issue about this may not have the chance to log on in the day this was put up.

**Comment by fj45** [comment]
While I had no issues with the change, it was merged a little early unless there was some reason for the sudden merge.

**Comment by Fox-McCloud** [comment]
The change passed the 24 hour mark and the reception to the changes were overwhelmingly positive on the forums, with no objections, and only a couple minor concerns (combat borg and engiborg, which were both addressed); the only real objection was the emergency full destruct removal you brought up.

**Comment by Earthdivine** [comment]
You all kept citing that Contraversal pulls would be discussed at length until they were good enough to be pulled. Don't mark something Contraversal then treat it like any other Pull, that contradicts the point of it. The removal of the full on explosive button is a HUGE change to e glossed over because only two people mentioned it.

**Comment by ZomgPonies** [comment]
Except it WASN'T controversial if the change was overwhelmingly positive on the forums. My apologies for not removing the controversial tag on it before merging. If there's additional balancing to be done from there on that's fine and can be done in a seperate PR, a full revert is not required.

**Pull request closed without merging**
