### PR TITLE
ORM Fix

### PR DESCRIPTION
**Pull request by Jazz23**
**What does this PR do:**
Ejects ID on destroy and stores the leftover points in the circuit board.

**Changelog:**
:cl:
tweak: ORM ejects ID and stores points on circuit board
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I don't think you should get your points back if the thing is destroyed, to be honest.

Sure, it sucks, but it sucks when R&D loses all their progress when they save their designs and lose their server and there's no backup.

If you forget to eject your ID or you forget to claim your points (which are even more trivial than R&D saving), and it gets blown up or deconned in the time remaining...again, that's kinda on you.

**Comment by Jazz23** [comment]
This was designed for when the ORM is deconstructed, not destroyed (although obviously it does apply when it is actually destroyed).Having your ID deleted doesn't seem very realistic/a part of the game, hence me calling it a fix. Why should the materials not be deleted but your ID does?

**Comment by Kyep** [comment]
I agree that it should eject your ID if destroyed.
I am skeptical it should save points. Really, miners should just claim their points as they use it, not leave points in the machine. And the ORM is rarely destroyed anyway.
Your changelog requires update to actually say when it does these things.

**Comment by Kyep** [comment]
Hey there. 
We've decided to close this, as we aren't okay with the points change.
If you'd like it re-opened so you can remove the points change and just keep the fix, we can do that if you let us know.

**Comment by KasparoVy** [comment]
:O I watched this get closed in realtime

Far out, man.

**Pull request closed without merging**
