### PR TITLE
Adds 'Gateway Explorer' (Supply Edition)

### PR DESCRIPTION
**Pull request by razekpraxis**
Adds 'Gateway Explorer' to Shaft Miner titles and gives them Gateway access. Also yes I spelled the branch name wrong oh well.

### CODE REVIEW

**Comment by razekpraxis** [comment]
MOTHERFUCKER i messed it up

**Comment by monster860** [comment]
I don't think anyone would have noticed the fucked up "explroer" thing if you hadn't mentioned it

**Comment by monster860** [comment]
Also, you still have the same problem: You're giving science free access

**Comment by razekpraxis** [comment]
yeah, like i said, i fucked it up. bad commit. LAST TRY. I PROMISE.

**Pull request closed without merging**
