### PR TITLE
Fixes bots not being trackable using the chat link as AI

### PR DESCRIPTION
**Pull request by farie82**
## What Does This PR Do
Makes bots like beepsky trackable as ai when clicked on the name in chat when they say something

## Why It's Good For The Game
It's currently broken

## Changelog
:cl:
fix: Makes bots like beepsky trackable as when clicked on their name in chat
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
This has been broken since forever, good work 👍

**Comment by Shockpoint** [comment]
Will this work for ghosts too, or just AI?

**Comment by farie82** [comment]
> Will this work for ghosts too, or just AI?

It should fix it for ghosts as well seeing that the track target was null and I assume that the ghosts also use that

**Comment by Spacemanspark** [comment]
I think at the time of the last bot changes, it was said this was some unfortunate side effect.

Thank fuck if you've managed to fix it.
Now all we need is for the AI to be able to click on floor tiles when moving bots around once again...

**Comment by farie82** [comment]
> Now all we need is for the AI to be able to click on floor tiles when moving bots around once again...

Thanks for bringing that up. Kinda forgot about it myself. Fixed in #12968

**Comment by Spacemanspark** [comment]
Yay

**Pull request merged**
