### PR TITLE
Add New Reagents to ChemMaster's Safe List

### PR DESCRIPTION
**Pull request by Arthri**
## What Does This PR Do
Adds the following reagents to ChemMaster's safe list, allowing patches made with them(or along with other safe reagents) to be applied instantly.
- Diphenhydramine - Antihistamine. No overdose limit or overdose effects. Causes tiny amounts of drowsiness but overall pretty safe
- Ephedrine - Similar to Epinephrine but has a higher overdose limit(35u).
- Iron - No overdose limit or overdose effects. Completely safe
- Sanguine Reagent - Restores blood but has an overdose limit of 15u. Somewhat safe. Can be retracted from the PR if requested

## Why It's Good For The Game
All of the aforementioned reagents(apart from Ephedrine, which is 0.3u/cycle) have a metabolism rate of 0.4u/cycle. Putting them in patches has the benefit of making them last longer, as well as benefiting from instant application

## Testing
Created a patch from each reagent and checked that they can be instantly applied to a monkey and that they have the signature white color

## Changelog
:cl: cdui
add: Added Diphenhydramine, Ephedrine, Iron, and Sanguine Reagent to ChemMaster's safe reagent list
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
> * Iron - No overdose limit or overdose effects. Completely safe

???????
why in the world was this counted as harmful??

**Comment by Danchi299** [comment]
> why in the world was this counted as harmful??

it's not that it was counted harmful
it's that it was not counted safe

**Review by DGamerL — APPROVED** [review]
LGTM, don't forget that OD thresholds don't really matter because patches usually won't reach any buildup higher than 10, with a standard metabolism rate and multiple patches

**Comment by DGamerL** [comment]
On second thought, Haloperidiol should probably be removed due to it's anti-stimulant properties, as was noted by a design team member. Could you remove it?

**Comment by ItsMarmite** [comment]
Do be aware that instant application is incredibly strong due to certain factors of how our chem system works. Iron seems totally fine although haloperidol as pointed out above and certain overdose chems can be problematic.

Even if patches aren't a problem due to how patches function with overdose, multiple instantly applied patches? You can see how it may become an issue.

**Comment by Ionward** [comment]
the chemmaster doesn't care what you make with it, i've made meth patches, iron patches, whatever, for ages. the safe option is for hyposprays or is completely unused on the chemmaster itself

**Comment by DGamerL** [comment]
Don't forget to remove halioperidol from the description!

**Review by lewcc — APPROVED** [review]

**Pull request merged**
