### PR TITLE
Fixes Bugs with Shining Eyes, Disembodied Heads and Admin-Reviving Beheaded Humanoids

### PR DESCRIPTION
**Pull request by KasparoVy**
**What does this PR do:**
Been noticing a weird issue where character eyes are darker than they should be under circumstances. I narrowed it down to the issue occurring only for characters with shining eyes. Bit more troubleshooting & comparison to Polaris code revealed eyeshine's render plane/layer needed to be updated.

Took the opportunity to do a bit of cleanup and fix another long-time issue preventing the rendering of appearance features (hair, eyes, etc.) on disembodied heads.

These fixes were salvaged from a really old ass branch I have on my fork and figured it was better they actually see the light of day.

Admin-reviving a decapitated body will now regrow the head with the ears organ and all the appearance features (hair, eyes, etc.) it used to have according to the mob's DNA.

**Images of sprite/map changes (IF APPLICABLE):**
_Before and after fixing the plane/layer_
para ss13 shining eyes colour fix

_Gotta roll some heads - sometimes your own_
para ss13 reheader fix

**Changelog:**
:cl:
fix: Resolves an issue causing shining eyes to be rendered darker than intended.
fix: Resolves an issue preventing appearance features (hair, eyes, etc.) from rendering on disembodied heads.
fix: Resolves an issue preventing Admin-revived decapitated bodies from having appearance features or ears.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Travis freaking out over changelog somehow, a bit confused 🤔

**Comment by AffectedArc07** [comment]
Should be fixed now @KasparoVy

**Comment by KasparoVy** [comment]
Thanks!

**Comment by Fox-McCloud** [comment]
One thing you might want to look into that I suspect is related to this.

If you get our head cut off as a Taj/Vulp with markings, then revive the body, the head will be back on the head, but it won't have any markings....andd uh, you'll be deaf.

**Comment by KasparoVy** [comment]
I'll see if I can reproduce that issue and try to correct it in this PR, thanks for letting me know

**Pull request merged**
