### PR TITLE
Ahelp and Mhelp QOL

### PR DESCRIPTION
**Pull request by FunnyMan3595**
## What Does This PR Do
Lots of small adjustments to ahelp/mhelp, see changelog.

## Why It's Good For The Game
Mentors will better be able to track what's been mentor-ed to players, and tickets will display a more useful set of messages.

## Testing
I will be hearing the bwoink sound in my sleep now, because I've sent so many combinations of ahelps, mhelps, replies, and PMs. Quinn in Discord may also be a victim, as they helped me with the testing that needed a normal player.

## Changelog
:cl:
add: Mentor PMs now have their own chat type, and can be filtered into tabs accordingly.
tweak: Replies to mentor and admin tickets (from both sides) are now bound to the specific ticket you replied to.
fix: Mentors should more consistently see mhelp replies from other mentors.
tweak: PMs between non-admin mentors and players are now shown to other mentors, and attached to any of the player's open mentor tickets.
tweak: Only PMs between an admin and players will be attached to the player's open admin tickets, not non-admin mentor PMs.
tweak: The player is now informed when their ticket is reopened.
tweak: Other mentors/admins are now informed when tickets are converted.
tweak: Discord relays of mhelps/ahelps now get a "Ticket 3, " or similar prefix.  Not useful by itself, but will be with the following PR.
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
"Non-ticket PMs between non-admin mentors and players are now shown to other mentors, and attached to any of the player's open mentor tickets."
Someone like eavesdropping :)

**Comment by 1080pCat** [comment]
> Mentor PMs now have their own chat type, and can be filtered into tabs accordingly.
bless.

**Comment by Danchi299** [comment]
> "Non-ticket PMs between non-admin mentors and players are now shown to other mentors, and attached to any of the player's open mentor tickets." Someone like eavesdropping :)

hold on, I am pretty sure it is already a thing? need to double check this somehow

**Comment by FunnyMan3595** [comment]
> > "Non-ticket PMs between non-admin mentors and players are now shown to other mentors, and attached to any of the player's open mentor tickets." Someone like eavesdropping :)
> 
> hold on, I am pretty sure it is already a thing? need to double check this somehow

It's not, the PM needs the "Mentorhelp" tag to be attached to a ticket. In fact, non-Mentorhelp PMs will get attached to open *admin* tickets right now, even if the person sending it is only a mentor.

**Comment by Nerfection** [comment]
Is it possible to either 1. Get the ahelp/mhelp boxes back or 2. Change the font colour of ahelps? At the moment they're a very similar font to sec radio and no longer in the nice, new boxes that were added.

**Comment by FunnyMan3595** [comment]
> Is it possible to either 1. Get the ahelp/mhelp boxes back or 2. Change the font colour of ahelps? At the moment they're a very similar font to sec radio and no longer in the nice, new boxes that were added.

I've got the code to change this, but since it's not an issue with this PR and is outside of scope, I've filed it as PR #24597.

**Review by S34NW — APPROVED** [review]
Not been made aware of any issues after 5 days on TM

**Pull request merged**
