### PR TITLE
Fixes god emperor of mankind disk

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Looks like this, don't know if that's correct.

:cl: 
bugfix: The God Emperor of Mankind disk now works properly
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Removing a feature, and fixing a bug, should be done in 2 separate PRs.

**Comment by LittleBigKid2000** [comment]
Removing a feature that's broken and too hard for me to fix

**Comment by Crazylemon64** [comment]
Then I'll fix it. In what manner is it broken, anyways?

**Comment by LittleBigKid2000** [comment]
The UI is incomplete. SE might be, too.

**Comment by Crazylemon64** [comment]
The fix portion of this PR is obsoleted by #5584

**Comment by KasparoVy** [comment]
Still makes sense to have a description for the disks

**Comment by Fox-McCloud** [comment]
Won't be merging this with the map changes.

**Comment by fludd12** [comment]
I always wondered if this disc was intended to give all the powers or something, considering the name and source. I do like the Unique Identifiers it gives, though.

**Pull request merged**
