### PR TITLE
Nuke update

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Makes the nuclear bomb use the wires datum.
2) Adds some admin messaging to the nuke.
3) Engaging a nuke will now set Delta alert level, unless it's a syndicate nuke (e.g. nuke ops).
4) Nuclear bombs can no longer be anchored in space.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I'm not really sure the nuke should automatically set Delta. Especially given scenarios like Epsilon or Gamma being called, it shouldn't downgrade from that.

**Comment by Markolie** [comment]
Epsilon and Gamma are actually downgrades from Delta - Delta being the highest alert level available (#6). If the Deathsquad enables the nuke to self destruct the station, the level will be raised to Delta due to imminent destruction. If the Deathsquad/crew disables the nuke, it'll downgrade to Epsilon again.

**Comment by KasparoVy** [comment]
So alert levels are in like a pyramid sort of thing? Raising from green to delta and falling again to gamma/epsilon?

**Comment by Markolie** [comment]
Yup:
#define SEC_LEVEL_GREEN	0
#define SEC_LEVEL_BLUE	1
#define SEC_LEVEL_RED	2
#define SEC_LEVEL_GAMMA	3
#define SEC_LEVEL_EPSILON 4
#define SEC_LEVEL_DELTA	5

0 being the lowest, 5 the highest of course

**Comment by Earthdivine** [comment]
While setting the nuke to Delta sounds cool, we already had this except with Gamma, and it was removed to still allow Nukkies to successfully stealth the nuke without the station knowing.

**Comment by Markolie** [comment]
It's possible to set it so it only goes Delta if the station's nuke is set.

**Comment by Earthdivine** [comment]
That sounds good.

**Comment by Fox-McCloud** [comment]
Provided the non-syndie nuke doesn't trigger this? :+1: 

I know TG had an interesting take on the nuke; they turned it into a stationary object and made it able to be taken apart+made it into a unique objective.

**Comment by Markolie** [comment]
Yea, I was going to port that, but there's quite a few differences between our nukes so it wasn't as quick as I had hoped. I might do it later.

Syndi nuke doesn't trigger it.

**Comment by Robertha89** [comment]
It would be interesting to see what would happened if the captain spawned with the nuke code again...

**Comment by Fox-McCloud** [comment]
@Robertha89 

Captain never spawned with the nuke code, AFAIK.

@Markolie 

That's pretty much why I didn't port it yet, but yeah, it's a pretty interesting addition.

**Comment by Robertha89** [comment]
He did at one point half a decade back or so.

**Pull request merged**
