### PR TITLE
Adds selected character below Setup Character button

### PR DESCRIPTION
**Pull request by Lady-Luck**
Screenshot

### CODE REVIEW

**Comment by AceMcLazer** [comment]
Neat! should help fight the tide of "Halp wrong toon" That I KNOW admins get. good times

**Comment by Spacemanspark** [comment]
Genius.
Now I won't forget which character I have selected when I wake up in the morning.

**Comment by NTSAM** [comment]
this would have helped back when i accidentally joined the game as "butt" which i used to get rid of one of my older chars

;-;

**Comment by Signmark** [comment]
you da real MVP

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by Twinmold93** [comment]
Smart idea. I like it.

**Comment by Lady-Luck** [comment]
You guys sure? It's not too late to tell me this ruins the game and makes everything baby mode forever. I've been getting with that a lot lately. :p

**Comment by VampyrBytes** [comment]
This ruins the game and makes everything babymode forever

but seriously :+1:

**Comment by Bigtimetripod** [comment]
Unplayable, scripts broken, ready button moved.

But seriously, this will help people who play with multiple characters. Good job.

**Comment by Twinmold93** [comment]
While we should be trying to implement things that make the game more interest/complex/new, this is an OOC feature that really could help out a lot of people, as it doesn't affect the actual IC of the game.

**Comment by tigercat2000** [comment]
I think this would look better _above_ the setup character button, but :+1:

**Comment by Lady-Luck** [comment]
>I think this would look better above the setup character button, but :+1:

That's actually what I did initially, and I didn't end up liking it as much. I wanted to make Setup Character and the character name look 'grouped'. It's an easy change if someone wants to tweak it later.

**Pull request merged**
