### PR TITLE
Supports +1 Scientist job slot

### PR DESCRIPTION
**Pull request by Kyep**
- Adds +1 job slot for Scientist. (6 -> 7 slots)
- Adds 1 scientist locker in scichem. (2->3 lockers)
- Tags: config change, map edit.

🆑 Kyep
tweak: changed scientist job slots from 6 to 7. Added one additional scientist locker. 
/🆑

### CODE REVIEW

**Comment by davidchan13** [comment]
I can't say I like more science slots. Robotics feels cramped with two people (three if Ganda- err RD is making mecha) RnD and Toxins are one man jobs due to equipment. Xenobio is better with one but two can cooperate, scichem is viable as two. EXPIR-mentor can hardly be called a job, at least long term for a two hour shift. 

This is going to either put one person as a designated gopher at best and have people fighting over work area at worst, as often happens in RnD even without the RD or Cap trying to print personal use stuff. Sci needs more work areas or work to do before adding more job slots.

**Comment by Kyep** [comment]
I am not adding a robotics slot.
Just a Scientist slot.
As-is, science is always full, and you always get some people transferring over, or the HoP/CC simply opening more slots. We actually run with more Scientist slots a lot of the time as is.... this just formalizes it.

**Comment by davidchan13** [comment]
I never said you were, but the point about the roboticists is also a point against your 'The HoP does it anyways.', I've seen plenty of rounds with 3+ Roboticists or if the Science half of Research is overstaffed then the RD naturally gravitates towards robotics if they don't run off to Tcomms or the bridge.

The point also still stands there is barely enough to do in science for non-antags scientists, adding another scientist slot is just going to make the science op/tator workshop meme even worse as a fully crewed science will always have someone standing around waiting to blow something up.

**Comment by jughu** [comment]
Barmaid job when

**Comment by Kyep** [comment]
@davidchan13 
- Civilian slots depend on sec officers. This is an automatic way of limiting greytide.
- Cargo tech is a job I have considered adding another slot for. I have not yet, because I've seen some feedback that Cargo doesn't get enough work to justify another tech slot. Do you play cargo tech regularly? Could they use another slot?
- Chef/Botanist/Librarian... I am not sure about. I never play these jobs, so I'd like to talk to people who do before I consider adding slots for them. At minimum, I need to understand what, if anything, I'd need to add/map in to make more slots viable for these jobs.
- Chaplain: I never considered adding another Chaplain slot, because chaplains are OP validhunters as is. Nobody plays Chaplain for the RP, which is the point of the job. I'd rather nerf Chaplains than have more of them. If I did do a PR to add another Chaplain, they'd get a bible and holy water bottle, but no null rod or armor.

**Comment by FreeStylaLT** [comment]
I do not see the benefit of adding an additional Scientist slot to a department that already has too few locations for their amount of slots, assuming each slot can / should take up a single room.

Science has 5 locations, not counting the outpost, to "work" at and 6 slots to distribute that work across. Beyond scavenging for strange objects / wallrot / upgrading the station, there is little reason for them to leave the department. 

Each subjob within Science can be handled by a single person, with arguable exceptions being made for SciChem or Xenobiology. I do not see much merit in adding a slot which would not really have a purpose / use in the department which is currently based around isolated tasks and little external interaction with the crew.

**Comment by Kyep** [comment]
@FreeStylaLT 
The station overall needs more slots. That means more slots in every department.
Each slot does not fill a room. My most played job is RD. I often see at least one person in R&D, two people in scichem, two in xenobio, at least one in toxins, and at least one on EXPERIMENTOR, or the outpost. That's 7-9 slots. Not counting those who go roaming, die in accidents, etc, which increase scope further. Science can definitely handle an additional slot. Realistically, it can probably handle more than one. This PR only adds one, though.

**Pull request closed without merging**
