### PR TITLE
Add AI text announcements

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Lets AI's makes text announcements.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Is this using the request console that's right next to their core like Baycode has, or using the Communication's console?
Either way, :+1:, although it'd be really neat if it was with the request console.

**Comment by tigercat2000** [comment]
compile failed due to #defines not being available
https://github.com/Markolie/Paradise/blob/s2/code/modules/mob/living/silicon/ai/ai.dm#L1003-L1004

**Comment by Markolie** [comment]
It's a unique verb.

**Comment by Spacemanspark** [comment]
Oh, even better.

**Comment by Markolie** [comment]
Ready.

**Pull request merged**
