### PR TITLE
Respawner Machine

### PR DESCRIPTION
**Pull request by fludd12**
A simple respawner machine which reincarnates any ghost who clicks on it on top of it. Mostly for adminbus, such as making ghost bars. Might make future subtypes for making other respawners, such as an easy way of spawning factions. No changelog because it literally has no change for players.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
An actual ghost bar would be neat...
Perhaps it could go where the old space ninja prison is.

**Comment by fludd12** [comment]
I am most certainly not going to attempt mapping, no sir.

**Comment by Fox-McCloud** [comment]
Having two merge commits in your PR isn't going to fly; you'll have to to get rid of them.

**Comment by fludd12** [comment]
Ah, alright. I'll real quick rebase.

**Comment by fludd12** [comment]
oh god I broke everything

**Comment by fludd12** [comment]
One moment!

**Pull request closed without merging**
