### PR TITLE
Allows for painting of pods.

### PR DESCRIPTION
**Pull request by tristan1333**
You can paint pods any color. Uses overlays, and is only usable on the civilian pod. Examples:  https://s9.postimg.org/qdn3d3c5r/PCIOF.png
:cl: tristan1333
add: Allows you to paint spacepods
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
changelog

**Comment by CrAzYPiLoT-SS13** [comment]
We don't use file changelogs anymore. The bot does that automatically. Instead, use autocl. Look at other PRs to see how it's done. It's the part starting with :cl:

**Comment by taukausanake** [comment]
Does this kind of leave #4708 a bit moot? It was closed after inactivity and/or merge conflicts

**Comment by tristan1333** [comment]
Ok nevermind I'm going to close this and fix it all cos I fucked it up

**Pull request closed without merging**
