### PR TITLE
Updates Mining Loot Crates

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates Mining Loot Crates to TG's versions.

Instead of being a simple 1 digit password to guess (and you get 3 chances), this is a 4 digit password that you get 10 tries to guess.

Loot from these is better and more diversified.

Related:
- Changes Ian costume to be normal, again---super hero variants are available which have NO_DROP on them still (regular Ian costume is crate loot) 
- Adds in cursed Katana, which has its slot flags removed (available in mining loot crates)
- Fixes up katana so its sound behavior is consistent with other weapons
- Cash seed can be admin spawned as an object

:cl: Fox McCloud
Add: Updates mining loot crates to feature far more actual loot
Tweak: Mining loot crates are now opened by inputting a 4 digit password and have 10 tries to guess the password string
/:cl:

### CODE REVIEW

**Comment by QuinnAggeler** [comment]
I think I'm for it. Mining crates currently give little of use and are easy to guess the password to. However, given the now greatly increased odds of guessing wrong, are we able to use something like a multitool to increase our chances?

**Comment by Fox-McCloud** [comment]
@QuinnAggeler 

You've always been able to use a multi-tool...even on the current ones. That doesn't change with tehse (which is why I didn't list it in the changelog).

Essentially these are like playing a game of mastermind.

**Comment by Spacemanspark** [comment]
I really think these should do actual damage when they blow up, but other than that, 
:+1:

**Comment by Dinarzad** [comment]
OH sweet we got the Goon style mining locks?
Those were fun little puzzles.

**Comment by KasparoVy** [comment]
Pretty awesome quality of life change, I don't mind not being able to cheese open every single loot crate. Wicked! Looking forward to coming across these.

**Comment by Bigtimetripod** [comment]
I like that this add kind of a treasure hunter feeling to mining. I know there were crates before, but most of the time i saw em being tossed a side for containing nothing useful usually.

**Pull request merged**
