### PR TITLE
Give syndi toolbox insulated gloves

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Gives the syndi toolbox red insulated gloves, based on /tg/. It replaces the toolbox's wires.

### CODE REVIEW

**Comment by TheDZD** [comment]
Just to note, this removes the cable coils from said toolbox to make room for the gloves.

**Comment by Markolie** [comment]
Whoops, forgot to mention that.

I'm sure those'll be dearly missed.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by tigercat2000** [comment]
Um.. but.. why? They have insulated gloves on the ship, why make a redundant resource?

**Comment by tigercat2000** [comment]
Disregard my previous comment; I forgot what syndi-toolboxes actually are.

**Comment by FalseIncarnate** [comment]
Update the uplink description for this item to reflect that insulated gloves ARE included now.

**Comment by Spacemanspark** [comment]
Oh no not the cable coil!
:+1:

**Pull request merged**
