### PR TITLE
Removes clown

### PR DESCRIPTION
**Pull request by Vivalas**
Seriously, who wants to work on their engifort all round just to be griffed and slipped by some griefer with an excuse to do nothing but cause trouble and mayhem? Why is this job even part of our code?

Seriously, why would a state-of-the-art research station have a clown anyways?

Maps out clown office and removes the job.

### CODE REVIEW

**Comment by Magikarpet** [comment]
:^)

**Comment by Vivalas** [comment]
image
 
New clown office.

**Comment by NTSAM** [comment]
april fools

**Comment by Fox-McCloud** [comment]
Much improved.

**Comment by Kerroman** [comment]
*sad honk*

**Comment by NTSAM** [comment]
viva la mime

**Comment by Necaladun** [comment]
Doesn't go far enough. Can we also perma anyone who ever played as a clown?

**Comment by monster860** [comment]
WHOA. You can't have spessmen without cluwnes.

**Comment by tristan1333** [comment]
I know it's not going to get merged, but if you have that much of an issue with clowns go to high rp lmao

**Comment by ninjacha** [comment]
needs 'i ded' tag

**Comment by TheDZD** [comment]
Remember to check your system clocks.

**Comment by NTSAM** [comment]
oh god it's almost 1 hour and 10 minutes until today is over here

**Comment by ZomgPonies** [comment]
*cue sad trombone*

**Comment by KasparoVy** [comment]
tbh all april is going to be april first

**Pull request closed without merging**
