### PR TITLE
Cerestation power issue mitigation 

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

Due to the engineering SMES starting with an output of 190k they will drain in less then 10 minutes due to the due 8 departmental SMES having an input of 95k each meaning engineering needs an output of 760k to completly mitigate that.
This pr mitigates it by simply removing the modifer variables on SMES, making everyones output and input 50/50, which will provide most areas with a lengtier time of power
The only exceptions is areas directly powered by engineering:
image
Due to departmental SMES having higher power pririty then an APC they will be charged first untill they are full, so departmental teleporters will quickly depower, as well as door access to security disposals.

## Why It's Good For The Game

One of the reasons why many do not like farragus is the power issues, and only engineers can handle those issues, so you get punished by not being able to play the game.  
Due to the power issues, engineering is not a popular job on this map.
This mitigates these issues somewhat, and better shows the advtanges of departmental SMES

## Testing

Compiled, ran the map, checked the SMES settings to be 50 in and 50 out.

## Changelog
:cl: ppi
tweak: Tweaks SMES input/output in at Farragus Station (Cerestation) to default 50 input, 50 output.
/:cl:

### CODE REVIEW

**Review by S34NW — COMMENTED** [review]
have you ensured departments don't depower weirdly here due to departmental SMES running out of juice sooner?

**Comment by ppi13** [comment]
> have you ensured departments don't depower weirdly here due to departmental SMES running out of juice sooner?
Departmental SMES will actually run out slower, due to output being set from 95  to 50.
as well as charging longer, even if the input is lower, since engineering output changed from 760 to 200, which will prioritize charge to the departmental SMES over anything else, thus requiring them to also be setup for prolonged functional power.

**Comment by S34NW** [comment]
> > have you ensured departments don't depower weirdly here due to departmental SMES running out of juice sooner?
> > Departmental SMES will actually run out slower, due to output being set from 95  to 50.
> > as well as charging longer, even if the input is lower, since engineering output changed from 760 to 200, which will prioritize charge to the departmental SMES over anything else, thus requiring them to also be setup for prolonged functional power.

Yes but is there actually enough juice for them to properly power all APCs at that rate? or will APCs get drained sooner fighting for the juice they can get a hold of. The cynic in me would suggest you do a before/after timelapse with a long viewrange

**Comment by ppi13** [comment]
https://github.com/ParadiseSS13/Paradise/assets/21987702/db95280e-00b7-4626-bdbc-f64a7bdc3a2d

Yes, when an APC is fully charged, it does  reduce the overall drain on the smes, so mostly engineering is gonna lose power.  
This video is 20 minutes over 10 minutes, top SMES are from left to right Science, Security, Engineering.
It powers apcs in order,  with what it can, and as they get full, other aps gets charged.

**Comment by ppi13** [comment]
https://github.com/ParadiseSS13/Paradise/assets/21987702/5409a788-be7f-40db-9387-e9eb41486d2c

here is a comparison of it live. Both recording does not take into account the extra usage of power the departments normally use when... Uh, used.
But it mitigates the issues with powerloss quite a bit.

**Review by DGamerL — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
