### PR TITLE
Cyberiad: Maintenance & Service Rework [Part 3]

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
Changes old Dominatories, Service and Fore/Fore-Starboard Maintenances look to new one.

## Why It's Good For The Game
Expands boring dominatories and give more content for surrounding it maintenances.

## Images of changes
(This image will be updated every time there will be change)

(Download Image for full resolution)

## Testing
Run Code, didn't see to crash, (still need do disposal testing and stuff)

## Changelog
:cl:
tweak: Changed Cyberiad Service and Dominatory shape and accessibility.
tweak: Chanded Cyberiad Fore and Fore-Starboard Maintenances shape and content.
/:cl:

### CODE REVIEW

**Comment by YoureNotTheSharpest** [comment]
PETSHOP IS BACK!

**Comment by ArcZelf** [comment]
Looks neat. Just have some feedback & questions to ask.

What's the reason behind placing an N2O canister & CO2 in a tiny atmos-locked room under the detective office? I'm a little worried about having these quite accessible compared to having to break into the toxins storage room or atmospherics/engineering.
image


What's the idea/implication of this area? Is it some sort of museum?
image

Why a sexy mime mask instead of the default one? The mask behind the clown's office is the default one but the one behind the mime's office is a sexy one?
image

**Comment by DGamerL** [comment]
So just quickly my thoughts:

- Dorms has become more of a hallway than a cozy spot to hang out in
- Any chase here can be easily ended by shooting down the hallways with disablers
- Maintenance looks to have shrunk considerably in size
- Catwalk tiles are not only quite ugly inside, they're also not consistently laid in other maintenance tunnels
- My poor boy, Electrical maints. Now:
- 1. Very easy to hear anything out of the ordinary from closeby
- 2. It becoming a checkpoint .... not so sure how to feel about that
- Any Arczelf review I've missed

**Comment by Venuska1117** [comment]
Considering negative response from Design Team, this PR will be closed.

**Pull request closed without merging**
