### PR TITLE
Lets you wear the NukeOps Pinpointer in PDA slot.

### PR DESCRIPTION
**Pull request by razekpraxis**
As title says. IDK why this wasn't a thing before.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Merge commits aren't allowed on your first commit--you'll either have to squash or remake without the merge commit.

**Comment by Crazylemon64** [comment]
You've got a leading merge commit. See how to fix it [here](https://github.com/ParadiseSS13/Paradise/pull/5933#issuecomment-264594234)

**Comment by razekpraxis** [comment]
important information: i dont know how to use git

**Comment by Fox-McCloud** [comment]
Technically this is a fix; this should have been re-added when PDA slots were specifically re-added, but it was forgotten.

**Pull request merged**
