### PR TITLE
Adds proper access controls to mech fabricator

### PR DESCRIPTION
**Pull request by warior4356**
## What Does This PR Do
Applies an ID restriction to the mech fabricator, locking it to robotics access.

Allows the emagging of the mech fabricator and space pod fabricator to remove access requirements.

## Why It's Good For The Game
First off, it's a design inconsistency, that the space pod fabricator is locked and the mech fabricator is not. Further, the general R&D machines are locked, but the mech fabricator is not.

This allows scientists to effectively function as robotics+, as there is nothing stopping them from doing robotic's job, while robotics is not allowed to interact with the R&D setup. This should help encourage science and robotics to cooperate and "Stay in their lanes" so to speak, rather than building machines to do the other's job.

This also prevents any random person who walks into robotics from making whatever they want on the fabricator, making it harder for greytiders and griefers to annoy robotics. They already can't make whatever they want in R&D so this is just consistency in my mind.

Further, it's a positive option for interaction to let emags bypass the access restrictions on both of these machines.

## Changelog
:cl:
add: Added the ability to emag into mech fabricator and space pod fabricator
add: Locked mech fabricator to robotics (and golem) access.
/:cl:

### CODE REVIEW

**Comment by PidgeyThePirate** [comment]
Where does this leave golems? Is it possible to get public access versions of the fabricators?

**Comment by warior4356** [comment]
> Where does this leave golems? Is it possible to get public access versions of the fabricators?

I could add a subtype that is public access yes. I'll make sure the RD has to approve it getting tech levels.

**Comment by ppi13** [comment]
So Robotics can build a full RnD setup, but science can't built mech fabricators?  
Unless mechfabricators gets connected to a computer, this is a hard no for me.

**Comment by warior4356** [comment]
> So Robotics can build a full RnD setup, but science can't built mech fabricators?
> Unless mechfabricators gets connected to a computer, this is a hard no for me.

Robotics will be losing upload access in the techwebs PR, so their R&D setup will be nerfed to what science decides to buy.

**Comment by Fox-McCloud** [comment]
Not a fan of this, at all.

ID locks are typically to prevent base, entry level nonsense from outside your department---and even then, it's *usually* better to rely on the doors being the thing that blocks people, and not the machines (there's always exceptions of course).

The mech fab having an ID lock is definitely edging into that territory. If someone can managed to break into the department, then, IMO, they should be able to access it---quite frankly, same goes for the R&D Console.

Also, as pointed out, this just means that robotics can end up becoming the "better R&D" than R&D can---yeah...not great.

**Comment by hal9000PR** [comment]
Can you hack the fabricators for access? If you can then sure, if you cannot then nah.

**Comment by Fox-McCloud** [comment]
>Can you hack the fabricators for access? If you can then sure, if you cannot then nah.

You cannot.

**Comment by PidgeyThePirate** [comment]
I find myself agreeing with Fox, I'd rather purge the access restrictions on the R&D console. Anything really harmful comes out in a lockbox anyway.

**Comment by AffectedArc07** [comment]
2 maintainers against, no one in favour from either party. Closing.

**Pull request closed without merging**
