### PR TITLE
Resprites ice cream machine and food cart

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Moves these over from uggers sprites to 3/4ths ones.

EDIT: Ramon made me new ones with full directionality support. Praise be!

## Why It's Good For The Game
3/4th sprite project progression

## Images of changes
image
image

## Changelog
:cl: McRamon S34NW
imageadd: The food cart & ice cream cart have been given new coats of paint
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
dear god yes! A proper ice cream cart!

**Comment by McRamon** [comment]
does it have directional sprites?

**Comment by S34NW** [comment]
> does it have directional sprites?

no

**Comment by S34NW** [comment]
> does it have directional sprites?

yes

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
