### PR TITLE
Stops Syndicate Space Base from abusing NT patented Heater-TEG-Freezer Physics Distortion engine

### PR DESCRIPTION
**Pull request by NethIafin**
## What Does This PR Do
Replaces Heater-TEG-Freezer with a proper, indirect heating (so safest to train on), TEG setup. Should also allow to nerf atmos heater-freezers with impunity

## Why It's Good For The Game
Makes setting up engine for Syndicate Space Base take more than 3 clicks

## Images of changes
Starts like this:
teg_start
Example of it in work:
teg_working

## Testing
Hello aspiring Syndicate employee! This is the guide for our new Thermoelectric Generator Setup!
South of it you can find 8 canisters. Start by connecting one of N2 Canisters to the Connector Port that is connected to space cooling loop. You can find it in the South-East of the room. After this N2 Canister is drained into the loop, you can un-wrench it and bring another N2 Canister and add it to the mix.
Now take O2 Canister and fully drain it into Burn Chamber using pump at max pressure. Do that with second O2 Canister.
Connect CO2 Canister to the topmost Connector Port - it will be our Hot Exchange Gas.
By this time second O2 Canister should be done draining into the Burn Chamber. Set our Burn Chamber pump to as small pressure as you feel okay - we recommend starting at 6kpa. Now only after that - connect a Plasma Canister to the Burn Chamber.
Wait until you can see Plasma particles in the Burn Chamber.
Press IGNITE.
Now maximize pumps that are right near TEG (remember not to touch the pump that feeds Burn Chamber for now!) and enable them.
Use multitool on both sides of the TEG to reverse their Inlet position. **This is intentionally set wrong so you know that you can do that!**
Use multitool on the TEG itself to switch Hot and Cold side. **This is intentionally set wrong so...** you got the drill, employee
Open valve on the Hot Exchange Gas
Watch both turbines on the TEG - they should start rotating. If they do - congrats - you have power.
Set up SMES to max input and 30kW output both, you won't ever need more.

Remember, employee, this is not one of those cases where you need to burn entire planet worth of Plasma gas to power a Bluespace Harvester. The needs of your station is below 30kW, rarely more than 50kW spike. This is a marathon, not a sprint. Let burn chamber burn slowly and at a low temperatures. The hot exchange shouldn't jump much above 500C, otherwise you are making more power, yes, but there are no SMES to store it.

## Changelog
:cl:
tweak: Syndicate Space Base TEG no longer violates laws of physics
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Think you could map in a sheet of paper explaining how to configure the setup in place, or make sure the rundown in your testing hits the wiki? I can imagine people who join the space base mid-round might not know how to set up a TEG.

**Comment by NethIafin** [comment]
> Think you could map in a sheet of paper explaining how to configure the setup in place, or make sure the rundown in your testing hits the wiki? I can imagine people who join the space base mid-round might not know how to set up a TEG.

I will make a section in wiki

**Comment by AffectedArc07** [comment]
Any chance you can find an IC "on a piece of paper" means of saying "This isn't going to work off the bat and needs manual configuration?"


I cannot begin to imagine the flood of ahelps for `Why wont the space base TEG work?`

**Comment by NethIafin** [comment]
> Any chance you can find an IC "on a piece of paper" means of saying "This isn't going to work off the bat and needs manual configuration?"
> 
> I cannot begin to imagine the flood of ahelps for `Why wont the space base TEG work?`

Paper added with detailed steps

**Pull request closed without merging**
