### PR TITLE
Display case update

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Implements /tg/'s display case burglar alarm: if you break a display case by hitting it, a burglar alarm will trigger in the area of the display case. This will cause a fire alarm effect in the area and bolt down all doors, and will send an alarm message to all alarm consoles/AI's/cyborgs similar to motion alarms. This should make stealing the captain's antique laser gun a bit more tricky.
2) The captain's display case will now automatically have its fingerprints set to the captain when they spawn.
3) Also adds some forceMove()s based on Bay.

### CODE REVIEW

**Comment by Alex6511** [comment]
:+1:

**Comment by Earthdivine** [comment]
Eh I worry this will make stealing the gun TOO hard. The office is already in a centralized area so most AIs move over it quite often, not to mention the captains who stay in the bridge with the Blueshield. The way in is also in a very visited hallway that anyone seeing you mess with the wall/door will robust you near immediately.

**Comment by Markolie** [comment]
Well, the point is to add more challenging objectives than "emag door, emag locker, take item". This requires some serious planning (getting the captain's UE/fingerprint and his card). It's meant to be challenging.

**Comment by Alex6511** [comment]
@Earthdivine I like the idea of it being difficult, traitor objectives shouldn't be easy.

**Comment by Fox-McCloud** [comment]
I like the idea of this locking down the room if you break it---I can definitely get behind that, as it makes it a lot more challenging for your average "lol emag->grab".

The thing I'm a bit iffy on is the automatic fingerprint assignment; but that has less to do with traitors and more to do with grabbing the gun in a time of emergency when it's absolutely needed, and Captain is down/dead/gibbed; you wont' be able to grab it, even if you've been promoted to Captain and have all access without the entire room locking down on you.

**Comment by Markolie** [comment]
You still can - breaking the glass triggers the alarm. Once the glass is broken (or the case unlocked) you can smash the fingerprint control in about two hits, which will lets you grab the gun and doesn't trigger the alarm. The gun is as such still accessible to everyone, as the fingerprint scanner can easily be fixed (but probably won't be if there's an emergency). 

The fingerprint scanner really is more fluff than anything else, as it only controls the hoverfield.

**Comment by Fox-McCloud** [comment]
Ok, maybe we're not on the same page, so I'll try to explain where I'm comin' from.

Ok, Captain spawns in, he later dies. Hero-person has all access from the Captain and rushes into the Cap's office.

Is he able to get the laser gun without smashing the case, by virtue of his all access? That's the main point I guess I'm concerned about---smashing it = lockdown seems more than fine, but having all access and having to still smash it (and therefore lock yourself into the Captain's office) seems a bit troubling.

**Comment by Markolie** [comment]
Breaking the glass triggers the alarm. Breaking the fingerprint checker does not. The glass is opened with the captain's access, which means the acting captain only has to break the fingerprint scanner which is very easy. 

So yes, they can get it without triggering the alarm. You'll just have to fix the fingerprint scanner.

**Comment by Fox-McCloud** [comment]
@Markolie 

Ok, thanks. Wasn't aware that you could even bypass the fingerprint scanner.

Don't really have a problem with it, then.

**Comment by Markolie** [comment]
I'll double check it tomorrow either way, as there's a few tweaks I need to make anyway.

**Comment by Markolie** [comment]
Okay, added some extra checks to make sure the fingerprints can be circumvented under all circumstances.

Also made it so that adding a proximity sensor while constructing a display case enables the burglar alarm.

**Pull request merged**
