### PR TITLE
Remove sling dethrall surgery

### PR DESCRIPTION
**Pull request by datlo**
This PR will need to have Space Law/Server rules updated accordingly if approved.

This might also need some sort of announcement, either OOC or IC from CC, so the playerbase is aware since this is a major change to how the gamemode functions.

With this PR, shadowling thralling is now permanent. The only way to be dethralled is now cyborgification. 

Shadowling thralls are no longer crewmembers; and must be killed on sight when security knows they're thralled either by face inspection or by the thrall obviously helping shadowlings against security.

Why : 

1. Playing security against shadowlings is extremely frustrating because on one hand you've got a round-ending EOC that's one of the most dangerous antags in the game, but on the OTHER hand you also have crewmembers you're supposed to handle nonlethally.

With this change, security can take the kiddy gloves off. All thralls are now valid, bring out the shotguns, the lasers, they help slings? They go down with them.

2. Thralling is supposed, IC, to suck. You lost your freedom, and effectively, your life. OOC, though, meh, whatever, you get to antag for a while until sec catches you or slings win/die, and you can go back to your job if dethralled. If anything, there's little reason NOT to go get thralled, except self antagging server rules and RP.

Now, if a shadowling catches you and enthrall you, you either win with your masters, rot in maintenance or the morgue, or end up borged.
This will make people think twice before going into maintenance when shadowlings are called out.

3. If you DO get thralled, and hate being one currently, it's pretty easy to underperform, get tased by sec, and after a quick trip to the OR, go back to doing your job as if nothing happened.

Now, you either do your best to help your new masters, or die with the rest. If you REALLY don't want to play as a thrall, you can do so and not mess up the round in progress by ahelping to have your body taken over by a ghost.

🆑
del: Removed dethralling surgery (shadowlings). Shadowling thralls are no longer to be considered crewmembers.
/🆑

### CODE REVIEW

**Comment by variableundefined** [comment]
A clever solution to the problem of self-antagging on shadowling rounds, but I am not sure if this is a good idea.

I'm neutral on this.

**Comment by Denthamos** [comment]
Not sure how to feel about this either.  It is an interesting topic.

Personally I hate having to keep an eye on everyone while trying to play, due quite a few people that 'just so happen' to wander into maintenance when its known there are shadowlings.  It would add a deal of threat to the player once they get thralled.  However would this also make players generally not want to play anymore once they do get thralled?

On the other hand with this for people not liking this change, keep in mind shadowlings can still revive thralls/turn them into greater thralls.  So technically even if thralls gets killed its not perma death for them if their body is taken back to a shadowling.

Perhaps in exchange the required amount of thralls for that should be decreased slightly?  Or separate that ability into two.  With the revive part for thralls being lowered and the empower part being 9 still?

Then outside of being borged/gibbed/cremated the dead thrall can be brought back into the fold.  And shadowlings would have incentive to use the empower ability more at this point then in order to have their thralls help them in the battle.

**Comment by Breenland** [comment]
If splitting Black Recuperation, their ability which creates Lesser Shadowlings or revives a dead thrall, can happen, I would be up for supporting this.

**Comment by datlo** [comment]
I'm hesitant to attach any extra balance changes to this PR because I'm not even sure if this is a shadowling buff or nerf in practice, as security can now lethal with much less worries against slings and their thralls.

**Comment by TDSSS** [comment]
I'm not sure turning sling rounds into a bloodbath/deathmatch is the right way to fix slings. i agree that thralling should come with negative consequences, but this is too much. What if being dethralled caused significant brain damage or something? And if medbay's too busy fixing other thralls, you get to be a drooling idiot for a bit as punishment for just "happening" to be in maint, without being dead forever.

**Comment by datlo** [comment]
Yeah no adding "eat a mannitol pill" to the list of the surgery steps to dethrall is not enough.

**Comment by Bram961** [comment]
Not for this at all, just giving security open season sounds like a very boring round type.

**Comment by TullyBurnalot** [comment]
We already had a roundtype where Security and loyalist crew were set up against a conversion antagonist that subverted people for the sake of getting stronger.

It was called Revolution. And it was removed from rotation **for a very good reason**.

If the _actual intent_ of this PR is to turn Shadowlings into, essentially, a Rev-style deathmatch where the metaphorical "Rev Heads" are also eldricht shadow horrors from beyond the veil, then I'm absolutely certain this PR will accomplish just that. However, that's exactly why I oppose this; we _**removed**_ the deathmatch-style round type from rotation for a reason, and I don't think it'd do us much well to bring another one back, except the leaders of one side also have superpowerful Bluespace magic.

**Comment by datlo** [comment]
Rev actually has a deconversion system so that's a bad argument. Shadowlings is ALREADY reskinned revs RIGHT NOW, with the difference that the leaders are easily spottable slings and the thralls can easily be tested by face checking.

Slings as a gamemode needs SOMETHING to change. This might not be the best change, but the status quo is not okay. If you have better ideas, please share.

**Comment by Birdtalon** [comment]
This would be a good change. Security should be able to kill thralls and vice versa, If it makes the round shorter then even better.

**Comment by TullyBurnalot** [comment]
@datlo If you yourself are saying this "might not be the best change", then why make it? We shouldn't be aiming to alter the status quo just for the sake of altering it, but rather to actually have a defined idea of where we want the idea to go.

Again, if this is just meant to approximate it to a reskinned Rev, then sure, but that doesn't make it any better as a concept, and is just liable to turn Shadowling into a high-chaos, short-duration round.

**Comment by Mitchs98** [comment]
Wholesale against this. Security is already 'murderbone the valids' enough as it is. We don't nees to encourage murderboning, at all. Thralls can already be declared KoS as needed anyway. This'll only make people hate the game mode more and encourage security murderboning.

**Comment by datlo** [comment]
@TullyBurnalot 
I'm making the change because a change has to be done and I do not have a better one. 

During all of 2018, I can only find two merged prs that try to improve slings balance as a gamemode : The warning when slings are close to ascend, and the reduction to how long sling dethralling takes. 
Both are good changes but they're bandaids on an open wound.

In my 100% subjective opinion, slings need radical changes such as this one to try and improve it or it needs to go as a main antagonist gamemode (which I'm perfectly fine with if we'd rather go that way, I cannot stand the gamemode as it is now. I'll gladly make the PR to remove it if headmins ask for it.)

**Comment by Bram961** [comment]
> I'm making the change because a change has to be done and I do not have a better one.

I don't agree with that, any gamemode has a win/loss rate. With nukies requiring 4 people to work together closely, knowhow is basically required for all 4 and just because of sheer numbers the winrate is obviously very much in favor of the crew.
With slings that happens to be the other way around.

Not every roundtype needs to have a 50/50 winrate for it to be a fun roundtype.

**Comment by Shadeykins** [comment]
> 
> 
> > I'm making the change because a change has to be done and I do not have a better one.
> 
> I don't agree with that, any gamemode has a win/loss rate. With nukies requiring 4 people to work together closely, knowhow is basically required for all 4 and just because of sheer numbers the winrate is obviously very much in favor of the crew.
> With slings that happens to be the other way around.
> 
> Not every roundtype needs to have a 50/50 winrate for it to be a fun roundtype.

In the community survey, Shadowlings were the least popular antagonist next to swarmers, Rev, and Morph, and voted as the most overpowered antagonist by a margin of 2:1. I am fairly certain we should probably do something with them given that information, I mean we have quite a few people who outright cryo when they discover it's a Shadowling round.

This change is interesting, I'm just not sure it's a solution.

The issue with turning thralls valid, is that other people by extension (non-thralls) become valid as well. I can see this devolving very quickly into a Rev-esque situation where people get killed more than they get converted.

**Comment by datlo** [comment]
@Bram961 This isn't about winrate. An antagonist could have a 0% winrate or a 100% winrate and although that'd probably be an issue to solve, the roundtype can still be fun to play for crew and antags.

Sling rounds suck. And I'm a part of the group that will likely cryo the moment slings are called out, or hell the moment I see somebody smashing lights repeatedly in maintenance, as mentioned above.

I'm closing this since it seems this is not a popular solution.

PLEASE dm me on discord (Three Point Fourteen) if you have a good idea for a sling fix (that isn't a massive pain in the ass to code). I would LOVE to fix the antagonist and make these rounds worth playing, I am not opposed to the thematic idea of shadowlings. Just its sucky ass execution.

**Pull request closed without merging**
