### PR TITLE
Makes Paramedic's Door a Regular Door

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Paramedic's door is now a regular medical door instead of a *diamond* airlock.

No more free minerals for you, science nerds.

:cl: Fox McCloud
tweak: Paramedic door is no longer diamond
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Those abusive bastards

**Comment by EldritchSigma** [comment]
People actually broke down that door? Ugh...

**Comment by Citinited** [comment]
How did that even get through to the codebase in the first place?

**Comment by Fox-McCloud** [comment]
It's probably recent.

Diamond doors, as far as I know, didn't actually have any minerals in them, at one point.

**Comment by granodd** [comment]
Wait.... the paramedic's door was made of _diamonds_? _Since when_?

**Comment by SamHPurp** [comment]
@Fox-McCloud looks like the mineral door refactor @Markolie did in #6693

**Comment by DarkPyrolord** [comment]
People did break down that door for diamond... I saw it in action not that long ago (as in last night before I left to sleep), bought it up about half an hour ago in discord and now this PR is up.

**Comment by deep-fried-faceplant** [comment]
I always thought it was just a teal door, wow. A station engineer at CC is getting fired for this.

**Comment by Kyep** [comment]
Suggestion: alter the changelog to be something like "Paramedic doors are no longer made out of solid diamond. In unrelated news, CC Engineer Dave McAdams has been fired by NT due to 'aggressive misuse of company resources'."

**Comment by SamHPurp** [comment]
👍 for IC themed changelog messages

**Comment by LightFire53** [comment]
Always want IC themed changelogs. However, I see this as a Steve from Accounting thing.

**Comment by DesolateG** [comment]
Remind me to deconstruct that door in disbelief before those gets merged.

**Comment by Crazylemon64** [comment]
LGTM

**Pull request merged**
