### PR TITLE
Cyborg Rebalance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Cyborg Rebalance-Definitely Controversial

I'll make no attempts to sugar-coat this, this is largely a nerf to borgs; that said, the ACTUAL impacts will really only be on sec and combat based borgs.

One of the biggest problems cyborgs have is the sheer amount of damage they can take before anything bad happens to them; they don't even die until you deal 300 damage to them--they can't be stunned (except by flashes and ion rifles), and they don't even start taking damage to their internal components until they've taken 60 brute; even then, unless the camera or actuator is hit, they're still more than capable of tanking through everything; in actuality, they can typically take ~250 damage before they reach a critical state. They're nigh impossible to deal with and suffer none of the downsides that humans do when they're in a combat situation.

Day to day this shouldn't impact regular borgs much, but it goes a longgg way to bringing secborgs, syndiborgs, and traitor/emagged/hacked borgs in line with being fought against for crew and antag alike. Gone are the days where the Syndiborg or emagged secborg can solo the entirety of security and still limb out alive.

What Does this patch do? It rebalances them to have similar health to humans and adds in legitimate downsides for having damage on your systems.

Changes:
- Reduces cyborgs current health from 300 to 100; they'll die once they hit 200 total damage, just like humans.
- Increases the armor rating of cyborgs from 60 to 100; this means you won't be able to damage their internal components until they take over 100 damage (soft crit for humans)--if this patch goes through and internal component damage is too detrimental, then the armor rating can easily be upped.
- As a borg is damaged, it loses functionality of its slots; at 50 damage it loses its 3rd slot; at 100, it loses the 2nd, and at 150 damage it loses its 1st slot (this does NOT apply to drones).
- When borgs have less than 100 units of power they cannot use any slots; this will also encourage them to head to a recharge station when they're low as opposed to running out of power in the middle of nowhere
 - Cyborgs with less than 100 power consume power at a very very low level
- Cyborgs are impacted by gravity
- Shifts the energy consumption of borgs more towards how many slots are active rather than their internal components.
- Cyborgs that are destroyed via a console will actually explode (very small explosion)
- Medical and Sec borgs will not have the CANPUSH flags.
- Cyborg Disabler shot recharge cost is now 50 instead of 500* (see explanation below)
- Cyborg Laser shot cost is now 83 instead of 830* (see explanation below)
- Cyborg stun baton is now a loaded baton that costs 1000 charge instead of 500 (fixes a sprite issue as well) 

Cyborg Related Change
- Updates the Robotics Control Console to be a bit cleaner
 - Emergency full destruct of all cyborgs removed (can still blow individual borgs)
- Robotic's control program removed from laptops
- Updates some borg code to not be so crappy

Fixes
- Fixes an issue with the cyborg's stunbaton sprite
 - The instacharge issue with borg rechargers seems to have vanished when the stunbaton was updated

Other
- Adds in the Ion Carbine; made at R&D; can fit on your belt or in your backpack unlike the full Ion rifle
- Ion Rifle cannot be impacted by EMPs
- Custom firing sound for ion rifles.
- Fixed some improper stamp icons
- added in a hilarious way to suicide with a stamp

*Explanation on energy changes: On Paradise, our energy gun costs and cell charges are REALLY wonky and messed up; while it seems like a huge "buff" to cyborgs with lasers/disablers, it's really just returning them to where they were supposed to be; the laser shots are normally supposed to cost 83--but when we had upgradeable cells, all energy gun usage as multiplied by 10--this was fine for non-cyborgs when the feature existed, but the same treatment was given to borgs, who had their own cell..thus it dramatically limited their impact with tasers, disablers, laserguns, etc.

### CODE REVIEW

**Comment by fj45** [comment]
Burn in hell you robotic abominations! 
Borgs were always a bit silly with their damage, I am half sad to say goodbye to whacking a cyborg several hundred times over just to kill it.


"Emergency full destruct of all cyborgs removed (can still blow individual borgs)"
Why was this removed? Kinda fun to have "the big red button"

"added in a hilarious way to suicide with a stamp"
Because why not!

**Comment by Regen1** [comment]
I disagree with this PR, why? Because emagging a cyborg should be rewarding, and they have SO many downsides to a human that having higher health and being more robust just balances the scales.
Cyborgs has no arms, they are slaved unless special circumstances and are slower than humans.
I also see no reason _what_so_ever_ as to why you would remove the Emergency full destruct button, it adds the ability to blow all borgs without having to go through the panel 10 times (As when the roboticist churns out cyborgs left right and center, or when the malf AI places a robot factory)

**Comment by Fox-McCloud** [comment]
Emagging a cyborg would still be incredibly rewarding; they're still and all-access unstunnable murdertank when emagged (they also can't be killswitched); a cyborg will outgun anyone 1v1 any day of the week, even with these changes; they are slower, yes, but that doesn't really matter when you have lasers, disablers, and ebows at your disposal. I could elaborate on this further in detail, if you'd like or have concerns, but it basically boils down to this: borgs have only two counters and can sustain through damage way better than a human can without any consequences; the goals of this are to make it so borgs can't walk over an entire team of armed security officers.

And yeah, I'd be more than happy to explain the full destruct thing thing. Since borgs will be weaker now, I wanted more counterplay to blowing borgs; once the full destruct is engaged, all the person has to do is screwdriver the console and there's literally nothing to prevent it; an AI that's observant
will still have the *chance* to prevent at least a couple of his borgs from being blown under this scenario; as he can blow the console and prevent any further of his borgs from being killed, rather than there being an "I win, you lose" full destruct button. 

Laptop was in a similar vein to this and pretty much gives any RD or Captain who buys a laptop the chance to have a hard counter to teh AI---with the AI not really haven't any way to stop it, what with laptop's mobile nature and all.

**Comment by Regen1** [comment]
Thats not even true though, a malf AI is still incredibly powerful even without it's borgs, and the "blow all borgs" button is just a counterplay against the AI.
If the AI does NOT disable the APC / Blow the RnD console then it is his fault, no reason to keep holding their hand on that matter, their fault, they take the blame.

**Comment by Fox-McCloud** [comment]
@Regen1 

He can't exactly blow the console if he got a robot factory.

**Comment by Regen1** [comment]
I still believe there should be a change to it instead of a complete removal, I like the feature and it has been in our codebase for a really long time. 
Why not make it stop the timer if the console is screwdrivered?

**Comment by Fox-McCloud** [comment]
Updated some cyborg gun energy usage.

**Comment by Spacemanspark** [comment]
I agree with Regen.

**Comment by Earthdivine** [comment]
A day isn't long enough for a controversial pull to be disussed, there are people who haven't even gotten on today who might have issue with this.

**Pull request merged**
