### PR TITLE
Adds me to `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Move me up a few lines of code

## Why It's Good For The Game
I wanna get over my fear of heights this way

## Testing
The higher up in the dev chain you go, the less testing you (have) to do

## Changelog
add: 🍇

### CODE REVIEW

**Review by Burzah — APPROVED** [review]
Purple

**Review by Contrabang — CHANGES_REQUESTED** [review]
Keep yourself also on the review team

**Comment by DGamerL** [comment]
> Keep yourself also on the review team

But stinky 🟠 :(

**Review by GDNgit — APPROVED** [review]

**Review by Contrabang — APPROVED** [review]
APPLY YOUR REPO GIVEN RIGHT TO SELF-MERGE

**Comment by DGamerL** [comment]
HOLD TIGHT, SELFMERGE INCOMING

**Pull request merged**
