### PR TITLE
Changes meteor sound to a new sound file.

### PR DESCRIPTION
**Pull request by Aidenzack1**
## What Does This PR Do

Changes the OGG file for the meteor event from siren.OGG to a new soundfile scifi_alarm.OGG

## Why It's Good For The Game

Stops confusion from people thinking its warops

## Changelog
:cl:
tweak: tweaked a few things
soundadd: added a new sound thingy
/:cl:

### CODE REVIEW

**Comment by SpookSpooky** [comment]
*sneeze* coding nerd, happy to see this change and happy to see you do something that is nice like this.

**Comment by Fox-McCloud** [comment]
We already have quite a few alarms--I'm not really keen on adding a new sound for a *single* game mode that is not played 99.9% of the time---especially since we have quite a few sirens of different variety already.

**Comment by Kyep** [comment]
Maybe this would be better if:
- it was shorter, e.g: 2 seconds rather than 6
- it was also used for the meteor event, so there's a distinct sound for "incoming meteors" that people learn to recognize

**Comment by Fox-McCloud** [comment]
There's already an AI voice line for that.

**Comment by variableundefined** [comment]
Objecting on the same ground as Fox, closing.

**Pull request closed without merging**
