### PR TITLE
/vg/ Lighting

### PR DESCRIPTION
**Pull request by monster860**
It's been a month since /vg/ did it, so don't yell at me about early adoption
===

Anyways, I'm continuing #4670!

:cl: monster860
rscadd: Adds fancy smooth lighting from /vg/
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Yes.
:+1:

**Comment by TheBeoni** [comment]
You got my blessing

**Comment by Jaywings** [comment]
Hell yeah.

**Comment by Plotron** [comment]
I wish I could compare it to that rather (and reverted) old lighting change that kept crashing BYOND for some (including myself). It's just a digression, don't mind me. :P

**Comment by Spacemanspark** [comment]
Actually, it wasn't completely reverted, just certain things were removed from it.

**Comment by Plotron** [comment]
Like the fancy lighting itself?

**Comment by Bigtimetripod** [comment]
It would be like a whole new game...

**Comment by TheDZD** [comment]
@Plotron The way it calculated light brightness (which made the station darker than it was before) and smoothed lighting overlays were disabled.

**Comment by PJB3005** [comment]
> smoothed lighting overlays were disabled.
Smoothed lighting transitions*

**Comment by Spacemanspark** [comment]
We liked the darker setting, though...

**Comment by PJB3005** [comment]
I did indeed like the darker too but the issue is that with this system it has to be a linear calculation, because the lighting overlays themselves work linearly.

**Comment by Xantholne** [comment]
Yes please

**Comment by Belario** [comment]
So very pretty :-1: :100:

**Comment by Fox-McCloud** [comment]
It's pretty, but insanely expensive.

**Comment by PJB3005** [comment]
>  insanely expensive.

Nah

50 pop /vg/ at 0.33 tick lag is 35 CPU above average.

**Comment by TheDZD** [comment]
Looks like your image link is dead. I recommend using another host, or just copy+pasting a screenshot directly onto your PR description (it'll upload to Github and be hosted on their servers).

**Comment by monster860** [comment]
It looks fine to me

**Comment by TheDZD** [comment]
Oh, huh, it's back. 

On an unrelated note, how thoroughly have you tested these for runtimes? Because when VG implemented goonlights, they ended up with a few 500 MB runtime logs (although that was before they made duplicate runtimes not be saved in runtimes logs).

**Comment by PJB3005** [comment]
The reason for the 500 MiB was because the shuttle code was copying some lighting tracking variables, so when the runtimes did happen it happened on huge gigantic, for each entry in the list.

It still happens, but to a much lesser degree.

**Comment by Vivalas** [comment]
Only thing I don't like is how the smooth lighting contrasts with the blocky obscura squares BYOND uses for LOS. Although you can't really fix that. :+1:

**Comment by PJB3005** [comment]
> Although you can't really fix that.

Oh you so can.

It's just that that implies effort and a ton of hacking.

**Comment by Lady-Luck** [comment]
Not gonna lie, with the pure black blocks in the middle of all the smooth lighting, this looks incredibly ugly now.

**Comment by Fox-McCloud** [comment]
After reviewing and analyzing the performance on this, we'll be closing this--it's a 250% increase in total performance cost, which is incredibly significant.

Additionally, the lighting system is likely to change, again, once 511 is fleshed out, making this system out-dated.

**Comment by PJB3005** [comment]
> Additionally, the lighting system is likely to change, again, once 511 is fleshed out, making this system out-dated.

If you're talking about europalights you're incredibly wrong. Lummox isn't fixing the performance problems with `KEEP_TOGETHER` so it's completely unfeasible. 

> which is incredibly significant.

I dunno we took it just fine and still only barely manage to break 40 CPU at 50 pop so I dunno `¯\_(ツ)_/¯`.

**Pull request closed without merging**
