### PR TITLE
Adds Guardian phase in/out effect

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
Ported from /tg/station13.

This PR adds phase in/out effect for Guardians, which plays when Guardian manifests or is recalled back to his host. Improves aesthetics.

Tested locally without any issue.

**Images of sprite/map changes (IF APPLICABLE):**
<a href="https://gyazo.com/bab461404db21e658ccc83b5dec82393">Image from Gyazo</a>

**Changelog:**
:cl: Arkatos
add: Added phase in/out effect for Guardians
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
paradise: Become TG

**Comment by Ty-Omaha** [comment]
that is so cool

**Comment by AzuleUtama** [comment]
Rule of cool says yes please!

**Comment by Bookdrizzt** [comment]
Could I ask what the phase in looks like? The phase out effect is the only one in the gif. Just wanna ask/see.

**Comment by KasparoVy** [comment]
Just gotta watch it, but backwards. See in reverse.

.ti eeS

**Pull request merged**
