### PR TITLE
Adds Airlock System to MetaStation Supermatter Engine

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Adds an airlock system (like xenobiology) for the supermatter engine on MetaStation that contains showers and rad suits. Also adds an airlock system that lets atmospherics enter the engine area as well. As well, the engine's SMES has been rezoned to engine_smes and the piping in the engine room itself has been cleaned up. Some light bulbs have been swapped for tubes for better lighting.

## Why It's Good For The Game
Currently the showers for radiation area distance away from the engine, as well the engine room wasn't necessarily true to the rad risk you ran when it came to distance. @Denthamos and I played around with the idea of an airlock system that isn't obtrusive, but gives a radiation area close to a large source of radiation for each map. This also is a QOL update to atmospheric technicians who sometimes need to get into the supermatter room. 

## Images of changes

Main overview

image

Atmospherics Access and EVA Access

image

There are a few more minor tweaks in other areas, but MapDiffBot under the checks tab will highlight those.

## Changelog
:cl:
add: Station Engineers now have a radiation airlock to access the NSS Cerebron supermatter engine, as well as an external airlock to the cooling loop
add: Atmospherics now has a radiation airlock to access the NSS Cerebron supermatter engine
add: Engine SMES is now it's own area on NSS Cerebron
tweak: Engine room has less chaotic piping on NSS Cerebron
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
I'm curious what your thoughts are on putting a little emergency nanomed inside the airlocks with some charcoal or KI. The showers handle the external radiation, but it's still pretty easy to pick up a few extra internal rads by being around the SM, and it'd be nice to have a way to make sure you're all patched up.

**Review by Bm0n — CHANGES_REQUESTED** [review]
image

The engine outlet needs its area set as engineering or it won't work.

**Review by S34NW — COMMENTED** [review]
image

Apart from this, and the doors using variable access instead of helpers like the rest of meta, G2G.

**Review by Bm0n — COMMENTED** [review]
i got a mapping review for you

<details><summary>Review</summary>

can you readd the warning stripes on both sides of the two maints doors leading to the SM. there's a hobo sign system in place of meta that basically marks maintenance paths with stripes while leaving deadends unmarked

image

These are using the wrong subtype

image

image


Use this instead

image

mind making the y pixel nudge for the SM APC 24, I fucked it up.

image

this looks awkward, consider outright removing the far left light as the area is well lit already

image

rogue mesons hidden under this engi spawnpoint

pr1

What's the point of an airlock system if I can just walk around it up here?

image

Room areas should yield to maints like on the rest of meta

image

</details>

**Review by S34NW — APPROVED** [review]
Not really sure why it is shouting merge conflict despite there not being a merge conflict....?

**Comment by Bm0n** [comment]
you know I had a bit of a thunk about this and just realised that the maintenance here will break the whole airlocking system you have in place for the SM. not really sure how to solve this other than just removing the doors and opening the area up. beside that  you also put maintenance helpers on the doors meaning anyone with just basic engi access can get into the SM chamber

image

**Comment by LightFire53** [comment]
> you know I had a bit of a thunk about this and just realised that the maintenance here will break the whole airlocking system you have in place for the SM. not really sure how to solve this other than just removing the doors and opening the area up. beside that you also put maintenance helpers on the doors meaning anyone with just basic engi access can get into the SM chamber
> 
> image
> 
> besides that looks good to me

Same sort of thing as Box. Maintenance access needs to exist for traitorous stuff and for radiation event reasons.

**Review by S34NW — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Comment by Bm0n** [comment]
one of these airlocks has firelocks the other doesn't

image


image

other than that looks good

**Comment by S34NW** [comment]
Airlocks shouldn't have firelocks TBH, but it's whatever

**Comment by Bm0n** [comment]
agreed, it is probably best to remove them, just pointing out a discrepancy

**Pull request merged**
