### PR TITLE
Adds Species Sprites For The HOS Suit (Plus Bonus Drask Helmet)

### PR DESCRIPTION
**Pull request by BardTheBard**
## What Does This PR Do
This PR adds suit and helmet sprites for the HOS suit for Drask, Skrell, and Vox. It also changes the helmet for the regular Drask Security Hardsuit.

## Why It's Good For The Game
These sprites were missing from the game, resulting in players of the above three species not having sprites while wearing the HOS suit. It also changes the helmet for the regular Drask Security Hardsuit, as it was an old sprite that was asymmetrical and it felt odd to just create a new one for the HOS suit but not have an updated version for the regular suit, so I did both.

## Images of changes
hossuits
With lights on:
hossuitlights

The new Drask helmet on the regular security hardsuit:
draskhelmet
With lights on:
draskhelmetlights

## Changelog
:cl:
add: Head of Security hardsuit sprites for Vox
add: Head of Security hardsuit sprites for Skrell
add: Head of Security hardsuit sprites for Drask
tweak: Replaces Security hardsuit helmet sprites for Drask
/:cl:

This is my first PR, so I apologise if anything's not done right or the likes!

### CODE REVIEW

**Comment by S34NW** [comment]
My crimes are finally undone

**Comment by Adrer** [comment]
> My crimes are finally undone

The sins of the father are to be laid upon the children.

**Comment by AffectedArc07** [comment]
Could I get an update on this, specifically why its still a draft.

**Comment by BardTheBard** [comment]
Closing this PR to replace with one that comprehensively revamps the Head of Security hardsuit.

**Pull request closed without merging**
