### PR TITLE
New pAI spiderbot color palette and fixed snake chassis eye and added holding sprites.

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
Change sprite of spiderbot to fit pAI theme and fix snake chassis eye offset.

## Why It's Good For The Game
make you less confused if spiderbot is a pAI or just brain in temporary body.

## Images
image

## Testing
Compiled, go pAI and choosed spiderbot chasis.

## Changelog
:cl: Venuska1117
tweak: Changed color palette for spiderbot and give it new "dead" state sprite.
tweak: Changed snake eye when looking south to correcly "look" south.
imageadd: New Visible pAI Snake holding sprites for: Left Hand, Right Hand, Ears and Head.
/:cl:

### CODE REVIEW

**Review by Henri215 — COMMENTED** [review]
image

You ended up touching this when solving your sprite conflict.

**Comment by Henri215** [comment]
pAI.dmi changes look good.

Do you plan to make the snake pAI head and in hands sprites to be the same as the "pai-repairbot"? Ideally it should be fixed by giving it a custom sprite like others.

**Review by Burzah — APPROVED** [review]

**Comment by Burzah** [comment]
For reference:
 This will partially fix part of https://github.com/ParadiseSS13/Paradise/issues/9328

**Comment by Henri215** [comment]
image

"imageadd:" instead of "add:" over the changelog, and make it say its the pAI snake, not simply snake.

**Comment by Venuska1117** [comment]
> image
> 
> "imageadd:" instead of "add:" over the changelog, and make it say its the pAI snake, not simply snake.

got it

**Review by S34NW — APPROVED** [review]

**Comment by Venuska1117** [comment]
> For reference: This will partially fix part of #9328

sorry but i cannot TAG it as fix, because i dont know how to fix missing hand holding sprites.

**Comment by Burzah** [comment]
> > For reference: This will partially fix part of #9328
> 
> sorry but i cannot TAG it as fix, because i dont know how to fix missing hand holding sprites.

It is fine. It shouldn't be tagged as a fix at the moment anyway, as it only fixes part of the issue from that report.

**Review by lewcc — APPROVED** [review]

**Comment by YoureNotTheSharpest** [comment]
damn shame, I liked the goofy aaa snake pai moving the right eye one pixel to look south sprite :)

**Pull request merged**
