### PR TITLE
Darksight Number Balancing

### PR DESCRIPTION
**Pull request by Aurorablade**
The Darksight number balance as i pleaed to wait for in https://github.com/ParadiseSS13/Paradise/pull/8468

Lowers Taj/Vulp Darksight from 8 to 6
Wolpin/Fawa remain at 8 and perma colorblind

the 6 may go to 7 or stay at 6 this is subject to flux.

ALL  DARKSIGHT VALUES OF CURRENT(unless i miss one):
Normal value: 2
Mech Assisted Eyes: 2
Unathi: 3
Grey: 5
Taj/Vulp: 6
Wolpin/Fawa:8
Shadowlings:8

:cl: Fethas
tweak: Taj/Vulp Racial darksight value is now 6.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
So you still plan to uncouple it and give all Tajs/Vulps an enormous amount of dark-sight with zero downside (but the colourblindness)?

**Comment by Aurorablade** [comment]
if by enormous amount you mean 'one value up from Grey' then yes.

**Comment by SamHPurp** [comment]
False equivalence. You cannot compare them to Greys. Compare them to their closest race in balance: Humans.

**Comment by Aurorablade** [comment]
Whats the difference between them and Greys besides being locked by karma?

**Comment by Tayyyyyyy** [comment]
You can kill a grey with one spray of the fire extinguisher under the right circumstances.

@Aurorablade thoughts on #8489 and some variant of #8491? I think most people would be okay with this if you indicate that you'd like those PRs merged along with this one.

**Comment by Aurorablade** [comment]
I am looking at eye balance not overall racial balance. That would be an whole nother hill of salt to swallow.
All races are a subtype of humans. and are infact human+ in that respect.

Now on the PRs mentioned the eye shine is cool, and i was going to actually do that in this PR but our ICON UPDATE CODE IS HORRENDOUS AND REALLY NEEDS AN UPDATE POSSIBLY OFF TG..PLEASE GOD SOMEONE FIX IT! AHHHHHHHHHHHHHHHHHHHHH!
AAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!

*clears throat* I have concern on the flash PR that i will address in that PR.

**Comment by SamHPurp** [comment]
You can't touch balance of one area without giving it due consideration of the whole pie. Jesus Christ, you know better than that, surely.

**Comment by AristoVagrant** [comment]
Let's give the race with an unarmed attack that's sharp the best base race dark vision without adding in a counterbalance.

**Comment by Squirgenheimer** [comment]
#8491 
Are we forgetting this isn't the only PR up addressing the issue?

**Comment by Aurorablade** [comment]
Some things you take in chunks, and in this area you can. Focus on the eyes for this.

Also please leave the sarcastic comments out of the PR please, if you have a actual suggestion make it.

**Comment by Keluandrie** [comment]
The issue was never with the numbers. It was with buffing a race without adding a downside to it. 8 is with colorblindness, 6 would be the new eyesight WITHOUT colorblindness, whereas the present without colorblindness is 2. This doesn't make sense from a game balance sense of view, and I'm not sure how you're not seeing it.

**Comment by AristoVagrant** [comment]
Right, so they still get the best base race dark vision with no effort, and the only nerf suggested is already being critiqued by the author of these PRs. 

The issue isn't the eyes here. You're basically trying to give Vulp and Tarj players a huge buff without any cost. A race that already teeters on the edge of being the more powerful race, having a sharp unarmed attack that does the same damage at any other race (which also has no downside).

**Comment by bigfatbananacyclops** [comment]
just leave it like it is and don't make a change

**Comment by Aurorablade** [comment]
okay what counter balance do you want for unathi also then cuase https://github.com/ParadiseSS13/Paradise/blob/c799ed6e429c27bc7caba4c0e5627c6b5e7ab230/code/modules/mob/living/carbon/human/species/station.dm#L32 
and they have a darksight of 3.

I could lower vulp and Taj darksight to 3 to make them equal to unathi then?

**Comment by AristoVagrant** [comment]
That would honestly work a lot better that what you're suggesting right now. 

On the topic of sharp claws, removing their ability to decap is sensible from a balance standpoint.

**Comment by AristoVagrant** [comment]
Ooops can't edit comments, and maybe to make up for the fact they cause bleeding, lower the damage by two points or so.

Human= Not human+

**Comment by Tayyyyyyy** [comment]
> I could lower vulp and Taj darksight to 3 to make them equal to unathi then?

Vulps would still be better than unathi, because they're not affected by temperature, i think. Honestly I think it's better if you leave it at 6-8, that way they can have the glowy eyes, and it makes them more than just a better version of unathi.

**Comment by Aurorablade** [comment]
No race is truly affected by temperature outside of drask i thought. NOW Taj are supposed to be affected by heat i believe just not to an extreme as bay.

On the subject of claws, any claw can do that its a part of the RNG and dismember code. HOWEVER again, this is for the PR is for the Eyes, the suggestion can is here for future use and consideration however.

**Comment by AristoVagrant** [comment]
Aurora, you asked about what to do with unathi also having sharp claws, I commented on the claws.

The problem here isn't just "The eyes". The problem is you are buffing a race that already has a good amount of buffs without drawbacks. 

If you wanted to give them 3 Darksight sure, do that. That's much more reasonable than 6 Darksight without a drawback. That's focusing on the eyes.

**Comment by Tayyyyyyy** [comment]
I disagree with lowering down to 3 darksight. Nerfing everything to the same level doesn't make things that interesting. As long as the PRs that add drawbacks to darksight are merged along with this one, darksight will be a net neutral. Vulps will still be a slightly better version of unathi, but by the same amount they were before.

**Comment by Aurorablade** [comment]
and i left comments on at least Tays pr...i like the eye shine bit and tiger has some of the code review covered there.

**Comment by KasparoVy** [comment]
I didn't write #8489 to make this or #8468 worth having, I wrote it because it was an interesting idea and I want these to go away.

**Comment by davidchan13** [comment]
>Some things you take in chunks, and in this area you can. Focus on the eyes for this.

With no roadmap, no suggestions on how you will balance this, not even a time table to go by, your statement leaves very little faith you intend to do anything but buff eyes.

Balance always needs to be considered as a whole, if someone were to give darksight to Borgs or IPCs with a promise to balance it out soon, you can bet the push back would be massive.

Darkness is a huge obstacle players are expected to overcome. The tunnels are dark, power surge and outages leave the entire station dark, slings and vampires break lights intentionally because of their powers to see through the dark, as do Xenos and spiders. Going into the dark you need flash lights which expose your position if you're hoping for stealth or night vision with powers or high level RnD gear which not everyone can get.

With dark vision 6 you can still see someone from outside the range of a flashlight without exposing yourself, and without the danger of walking into a hazard or another player fumbling about in the dark. In rounds where hostile roam the station anyone with dark vision has a flat and undeniable advantage that can't be taken away, only negated. And when that hard advantage is on a species with no drawbacks, then it's pretty clear the advantage should be removed or offset with something that inhibits as much as the advantage helps.

**Comment by Birdtalon** [comment]
>Taj/Vulp: 6

You're funny.

**Comment by scrubmcnoob** [comment]
> The Darksight number balance as i pleaed to wait for in #8468

Can you please reword this? As you are pleased to wait for? As you plead to wait for?
I'm confused, what is the objective of this PR? Couldn't these number changes have been done on 8468? Is this PR assuming that the former PR will get merged and that this is an adjustment to 8468?
Also, as said by others, why do you want a race to get a straight buff but no downsides? You should always be mindful of the scale. 
Balance is important.

**Comment by Ziiro** [comment]
Unfortunately, you can expect serious pushback unless you make a large effort to rebalance **all the races at the same time** and take careful measure in doing that. Doing it piecemeal could lead to problems.

**Comment by Allfd** [comment]
My personal preference is strong race buffs canceled by strong nerfs.  ReSkinned humans are boring.   

Giving Taj/Vulp darksigh 3 which is just 1 higher then humans makes them more like humans not less.

I think races can be changed individually, however all strengths + weaknesses should = human.

Not just, race = human.

**Comment by SamHPurp** [comment]
@Allfd Agreed. You play alternative races for alternative experiences.

**Comment by Rumiluntti** [comment]
Wait wait, the 6 is with or without colorblind?

**Comment by Rumiluntti** [comment]
Well that's absolutely retarded

**Comment by SamHPurp** [comment]
@Rumiluntti an accurate summation

**Comment by Aurorablade** [comment]
heh merge conflicts that can wait. Anyway Tays is correct in the potinonal of some other PRs.

**Comment by davidchan13** [comment]
"Oh we'll balance it out soon. This won't effect game balance at all."

**Comment by Aurorablade** [comment]
for races in general i am looking for CONSTRUCTIVE feedback here https://nanotrasen.se/forum/topic/12317-suggestion-non-karma-racial-stuff/

**Comment by Denthamos** [comment]
No race should be considered a direct upgrade without any downsides.  This is something that helped lead to the massive amount of paradise shitposts we see on reddit.  

The human race is the baseline, no good or bad.  Other races in the game if they are going to actually affect gameplay with their styles, should be balanced around that fact with neither being better or worse.  Just an alternative.

**Comment by DarkPyrolord** [comment]
With the other forms of balancing that are in and are in the works, this PR is a little pointless now, going to be a no from me.

**Comment by KasparoVy** [comment]
Whew.

**Pull request closed without merging**
