### PR TITLE
Shadow demon gets double burn damage

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR makes shadow demon recieving double burn damage

## Why It's Good For The Game

The way you should kill shadow demon is shoot it with laser, not rush with 15 flashlights.
Default laser gun shot now applies 40 damage, same as demon recieving on the light.

## Testing

Compiled, shot

## Changelog
:cl:
tweak: Shadow demon gets double burn damage(5 shots with laser rifle to kill now)
/:cl:

### CODE REVIEW

**Comment by Somniworld** [comment]
I think this is the wrong way of weakening a major midround (remember, this shadow demon could have been a blob!).

This just makes shadow demons need extreme care to play as it makes them vulnerable to being game ended in 3 seconds while in complete darkness (you know, the place where they're meant to reign?). This means that a failed grapple, which does put demons in shitty situations, but which's risk can be aliveated by properly positionning yourself and planning, now gets you killed, period.

Also, doesn't being in the light deal burn damage? It feels like you're just halfing the amount of time a demon can spend in the light, which wasn't a lot to begin with, making using one of the core shadow demon abilities a bloody death trap.

I wish to reiterate that this is a major midround, it could have been a slaughter demon, which are much beefier and don't need to be in the darkness. This essentially neuters them and turns them into a loot piñata that gets killed in 10 seconds tops.

**Comment by Mitchs98** [comment]
Fully disagree. Shadow demons can already be extremely squishy as it is. They're already quite hard for players to play in general from what I've seen(no personal experience, mind). As listed above this turns them less from scary mid-round into "Zerg the funny squishy dark creature for their funny heart."

**Comment by HMBGERDO** [comment]
> Also, doesn't being in the light deal burn damage? It feels like you're just halfing the amount of time a demon can spend in the light, which wasn't a lot to begin with, making using one of the core shadow demon abilities a bloody death trap.

no, it does brute damage
image

**Comment by HMBGERDO** [comment]
> I think this is the wrong way of weakening a major midround (remember, this shadow demon could have been a blob!).

The thing im trying to make is normal way to fight this antagonist instead of trying to avoid fight and waiting for them to fuck up

> This just makes shadow demons need extreme care to play as it makes them vulnerable to being game ended in 3 seconds while in complete darkness (you know, the place where they're meant to reign?). This means that a failed grapple, which does put demons in shitty situations, but which's risk can be aliveated by properly positionning yourself and planning, now gets you killed, period.

Yes, demon suiciding instead of being killed is a problem, i probably should have moved all in one PR

> I wish to reiterate that this is a major midround, it could have been a slaughter demon, which are much beefier and don't need to be in the darkness. This essentially neuters them and turns them into a loot piñata that gets killed in 10 seconds tops.

Shadow demon is healing passively if its staying in darkness which allows them to take free damage and to not think about it
Slaughter demon, homever, need to eat a body to heal and thats the only way they can heal damage, making them strong at start and weaker in couple iterations



> Fully disagree. Shadow demons can already be extremely squishy as it is. They're already quite hard for players to play in general from what I've seen(no personal experience, mind). As listed above this turns them less from scary mid-round into "Zerg the funny squishy dark creature for their funny heart."

At start, they were funny dark creature for their funny heart but with some changes and shadow cocoons they became monster you never fight. Your one mistake(and by mistake i mean even staying still and getting pulled into darkness with grapple) and you are mostly dead with not much chance to survive.

Shadow demon current status is "wait until it grapple into light and die", not something you really fight. 

I think im gonna close those splitted PRs, add more changes that should be there and make new PR for you to look into.

**Pull request closed without merging**
