### PR TITLE
Fancy-nanoUI revert

### PR DESCRIPTION
**Pull request by tigercat2000**
legitimately
fuck nano
i'm so done
what the fuck is wrong with all this shit why DOES IT BREAK EVERYTHING!?!?!?!?!?!??! AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

🆑
remove: Fancy NanoUI no longer hot shit
fix: NanoUI's Fancy Mode now less broken as hell
remove: 512 support for Nano dev tools
/🆑

### CODE REVIEW

**Comment by Spartan6** [comment]
😰

**Comment by Crazylemon64** [comment]
Changelog please

**Comment by Crazylemon64** [comment]
What adjustments will this need to the preferences table?

**Comment by AffectedArc07** [comment]
@Crazylemon64 nothing (By the looks of things). I think this just reverts the PR that added the edges to the UI

**Comment by Crazylemon64** [comment]
Yes, but there is a preferences option for whether to use the "fancy" NanoUI edges or not, and this has an entry in the preferences table
Would we then want to remove that configuration from the table?

**Comment by AffectedArc07** [comment]
FancyNanoUI switch was in before, and it switched from the windows having their own close buttons (Where the top bar doesnt show), and having it in a normal frame (Like the changelog).

**Comment by Crazylemon64** [comment]
Oh, I've not kept on top of what's been going on - alright

**Comment by Crazylemon64** [comment]
heck wrong button

**Pull request merged**
