### PR TITLE
Adds Xantholne Cyborg Fluff Chimichonga Edition

### PR DESCRIPTION
**Pull request by Xantholne**
Adds fluff item. Had to Re PR because of the destination change and new sprites in it.
Old preview from last one.
e1552c90-079e-11e7-89d8-f408d11b54de
Side view from the standard one
f92f04a06e00ad6d3fe8fbfd26f5741b

### CODE REVIEW

**Comment by Fruerlund** [comment]
Can we have side views too?

**Comment by Xantholne** [comment]
Only because I'm trying to find more reasons to stay up and finish my whiskey bottle

**Comment by SamHPurp** [comment]
_they still look like dongs_

**Comment by Xantholne** [comment]
no one is ever going to let that go goddamnit aurora

**Comment by TravellingMerchant** [comment]
My biggest worry is that they are way too thin. This could make them hard to click. 

(This was a big concern with the Noble borgs added recently so I had to bulk them up.)

**Comment by Xantholne** [comment]
Weeeell. The side views are about the size of the Engineering Landmate but taller. Front view is a bit smaller. A fix for that is just adding 0% pixels around it to increase hitbox size similar to how the scarab swarm and other guardians pretty much take up the entire tile.

**Comment by taukausanake** [comment]
@TravellingMerchant The Noble borgs were too thin? The ones that looked like mechs? How?

@Xantholne Those invisible pixels on anything are annoying unless they are surrounded by not-invisible pixels. If you do end up adding some then you might as well fill the whole icon with them. Some posts you can click though while others you can't will get annoying fast

**Comment by TravellingMerchant** [comment]
@taukausanake The originals were, not the ones that got in.

He's also right, the invisible pixels can be super annoying.

**Comment by SigholtStarsong** [comment]
They're still dongs. 

Any borg you play must be named Cyberdong, Dongbot, or Dong-u-tron.

**Comment by KasparoVy** [comment]
Roboned

**Comment by taukausanake** [comment]
Too many dong jokes?

**Comment by SamHPurp** [comment]
@taukausanake it all got a bit too _hard_ to take

**Pull request closed without merging**
