### PR TITLE
Refactors Gloves of the North Star. Adds Gloves of Headpats

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors gloves of the North Star to be var-editable.

You can now var edit these properties:
- Which intents it works with
- How much click delay it sets.

You could feasibly do any number of things with this, like `NO_DROP` gloves that apply to all intents and double your click delay, or be super adminbusy and have a pair of gloves that removes the click delay from all intents.

Adds and adminbus varient to the code, directly, to go with the laser glasses, ACJ, and Advanced Protective Suit.

Lastly, adds a gimmick variety of these gloves, called "Gloves of Headpats" that is available as a premium item from the pet vendor (only 1) that removes the click delay for help intent.

:cl: Fox McCloud
tweak: refactored gloves of the North Star to be more adminbusy
add: Adds Gloves of Headpats to the pet vendor as a premium item
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Holy shit lmao this is going to be awesome.

**Comment by Mitchs98** [comment]
Time to get these gloves as Goobina and pat literally everyone.

**Comment by Spacemanspark** [comment]
Time to tase Goobina every round

**Comment by AffectedArc07** [comment]
Speedmerge

**Pull request merged**
