### PR TITLE
Adds inhand sprites for the jaws of life and hand drill.

### PR DESCRIPTION
**Pull request by Aquilar**
## What Does This PR Do

~~originally i was gonna port TGs inhand sprites for these two, but as it turned out they were unfinished so I touched them up and made them look consistent.~~
Ionward made some better sprites.

no coding was required as the entries already had the correct item_states.

## Why It's Good For The Game

you can now see your character holding the jaws of life and hand drill.

## Images of changes

image

## Changelog
:cl:
add: inhand sprites for jaws of life and power drill
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
I don't like the jaws of life sprites. The red has no shading at all and it doesnt really have much detail. And when it is facing the front the main thing visible would be the cutter/pryer, not the red handle.

image

**Comment by shawnhind** [comment]
I personally like the idea of this PR and think it's an improvement over having no sprites but I'm not really a fan of the sprites themselves.

**Comment by Aquilar** [comment]
> Just fix conflicts and will merge

waiting on some sprites then will.

**Comment by Aquilar** [comment]
@variableundefined

**Pull request merged**
