### PR TITLE
The Great Delta Secpoint Removal

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do

This PR removes the security checkpoints from around the NSS Kerberos, and converts them to break rooms in most cases. In the case of medical, I moved the psychiatrists office down, and converted the unused space into a maintenance closet area. I also added a radiation shower space below the psych office to make it not seem so huge. For science, since they had an existing break room, I removed the existing one and made it "run down" to fit the general grunge feel to maintenance. Engineering had a break nook that I adjusted to just be some extra tools and a free floorbot.

This PR also (as a result of me adding some extra disposals) fixes a the CE and Engineering disposal junctions, as well as making it so that garbage doesn't end up in the law office.

I also added some extra holopads to medbay where they seemed to be lacking, as I was already adding holopads to parts of medical.

## Why It's Good For The Game

Map parity. Cyberiad doesn't have security checkpoints, Kerberos shouldn't either.

## Images of changes

**Old Research**
Research Old

Research Old 2

**New Research**
Research New

Research New 2

**Old Engineering**
Engi Old 2

Engi Old

**New Engineering**
Engi New

Engi New 2

**Old Cargo**
Cargo Old

**New Cargo**
Cargo New

**Old Psych**
Psych Old

**New Psych**
Psych New

## Changelog
:cl:LightFire53
add: NSS Kerberos departmental break rooms
del: NSS Kerberos departmental Security Checkpoints
tweak: NSS Kerberos Psych Office
/:cl:

### CODE REVIEW

**Review by variableundefined — APPROVED** [review]
We tried departmental security before and removed it. 

Approved.

**Comment by SteelSlayer** [comment]
> Map parity. Cyberiad doesn't have security checkpoints, Kerberos shouldn't either.

This is a bad way to go about things in my opinion. These sort of features set maps apart from cyberiad. If we use the above reason to make all maps conform to it, we’ll essentially just have cyberiad v2, cyberiad v3, etc.

**Comment by Coolrune206** [comment]
I like departmental Sec checkpoints - it was pretty much the only thing about the map that made me think "this is a good thing".

Map feels large and sparse enough that I think the checkpoints work.

**Comment by LightFire53** [comment]
> > Map parity. Cyberiad doesn't have security checkpoints, Kerberos shouldn't either.
> 
> This is a bad way to go about things in my opinion. These sort of features set maps apart from cyberiad. If we use the above reason to make all maps conform to it, we’ll essentially just have cyberiad v2, cyberiad v3, etc.

These are also for a role we don't have/support, therefore just kinda making them dead space. By converting them to break rooms, we make them usable space, and still maintain something Cyberiad doesn't.

**Comment by S34NW** [comment]
Erm, can I request you move the psych back into maints? @LightFire53 
Psych being in a main hallway is really good, because medbay psych makes it an utter pain for people to go there voluntarily.

**Pull request merged**
