### PR TITLE
fix for l6 description and paper hat sprites

### PR DESCRIPTION
**Pull request by shazbot194**
Changes the description of the L6 from 7.62 to 5.56 so it matches both
its ammo and magizine caliber.
Adds in paper_words sprites to head, and hands so when you have a paper
that is writen on, it can both be seen when holding and when wearing as
a hat.
🆑 
fix: Changes the caliber in the L6 description from 7.62 to 5.56
fix: Adds paper_words hat icon to prevent paper hats from being invisible
/🆑

### CODE REVIEW

**Comment by Crazylemon64** [comment]
`shazbot194:master` :eyes:

**Comment by shazbot194** [comment]
I'm still quite new to github and uploading to it, how do I add the change log tags?

**Comment by KasparoVy** [comment]
To denote the start of a changelog you type :CL: and, for the end, /:cl:. For fixes you can do :fix: (description here), :tweak:, :rscadd: (feature added), :rscdel: (feature removed), :imgadd:, :imgdel: (for sprites added/removed), and I think the same thing for sounds too. I advise you look at the other PRs (both pending and merged) to get a better idea.

The CL has to be in the body of your PR where you said "changes the description ...."

**Comment by Fox-McCloud** [comment]
I doubt the paper words sprite is necessary for in-hands, as the `item_state` of paper is explicitly fixed and doesn't inherit what the `icon_state` is.

**Comment by shazbot194** [comment]
You were right, I somehow messed up when testing, but it did change the item_state to null, while I'm a little confused as to why, just adding an item_state to the main item did the trick.

**Pull request merged**
