### PR TITLE
Redesigns the Listening Post ruin

### PR DESCRIPTION
**Pull request by Addust**
i had this lying around on my drive for like idk a year or so now probably might be more idk

## What Does This PR Do

Heavily updates the Listening Post ruin, making it feel more "syndicate" while also giving it proper power systems.
Also gives it the bespoke GPS tag of Encrypted Signal since it uses a unique area now.
image

## Why It's Good For The Game

The old one is pretty bad from what I can tell, having no access locks for a syndicate guy's house, and being far too bland.

## Testing

i dont remember if i ever did, might later

## Changelog
:cl:
tweak: The Syndicate has made some updates to their listening posts in Nanotrasen space, hopefully increasing security.
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
syndie toolbox, rest is still the same pretty much except i swapped the air tank for an oxygen tank

**Comment by Henri215** [comment]
The changelog should probably be "tweak:" instead of "add:".

**Comment by DGamerL** [comment]
> syndie toolbox, rest is still the same pretty much except i swapped the air tank for an oxygen tank

👍

**Comment by Addust** [comment]
updated it just to make the post a little stealthier because logically if NT knew about it it would've been shot down by now
image

**Comment by Henri215** [comment]
Did look at it over the map editor, it looks good.

I would just recommend moving the space suit to the telecomms room, since theres an enemy there (or add another item there to incentivise explorers to go inside the dangerous room).

**Review by S34NW — APPROVED** [review]
LTGM, just needs to pass CI

**Pull request merged**
