### PR TITLE
EXPERI-Mentor Addition--Telesci Removal

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in the EXPERI-Mentor

The Experimentor is a machine that is an alternative to R&D or that can be used in addition to it. Simply put, you place items inside the machine and perform various types of experiments on it; you can irraddiate it, poke it, freeze it, burn it, etc. Each type of item only responds to one type of experiment on it.

That said, it's not all fun and games; the machine can and will fail (often comically); it can spew toxic gas all over the lab, irradiate in an area, release an EMP, or steal Ian/Runtime  (this is just a small list). The better the parts in the machine, the less of a chance it has of failing and the more of a chance of the experiment being "successful".

So why would you want all that risk? Well, for the side-effects; performing a successful experiment can reward you with rare chemicals or materials--it can also duplicate items. On extremely rare instances, it will take a blood sacrifice from you and push the tech levels of an item higher than it otherwise would be.

There is a manual on the the EXPERI-Mentor that will be included in the lab, itself.

Lab itself? Where is the EXPERI-MENTOR placed? Well, it completely replaces the telescience lab.

Alright, so this has been discussed, internally, for quite a long time, with this gaining a lot of support from @Necaladun and a few others (such as myself and @TheDZD). @Markolie also supported this, provided telesci was still buildable (more and that later!)

Telescience is too powerful; there's no feasible way of limiting it without lots of checks here, there, and everywhere. That or constantly keeping an eye on it as an admin. It's pretty much just: steal whatever you want when nobody is looking---literally 10-15 minutes into the round.

Furthermore, it really negatively impacts things like Malf AI, Blob, Xenos, etc.

But, Telesci will be gone forever! Nope; I'll stress that this does NOT remove the ability to *build* your own telescience console, pad, and the likes; if you can get the resources for it from mining, you're free to build it, but it will not be available to utilize at round-start.

Admins
- Experimentor has investigate logging that tracks exactly what the machine has done and by who. Relics and their effects are also tracked, in addition to who uses them.

Other changes
- Adds in poison bees, which relics can *hypothetically* generate.
- Fixes instance of mindbreaker with LSD (mindbreaker was replaced by LSD long ago).
- Fixes hellwater grenades
- Re-adds the stun to Beepsky Smash
 - In practice, this isn't really a stun, due to how reagents and stuns are processed; it just makes you drop things.

### CODE REVIEW

**Comment by Markolie** [comment]
:+1: Per our discussion. Interested to see how this plays out.

**Comment by tigercat2000** [comment]
Did you update Metastation?

**Comment by Fox-McCloud** [comment]
I did not--I'll get that up, soon.

**Comment by M3hillus** [comment]
So can Mining/xenoarch find these relic things? or how does that work?

**Comment by Fox-McCloud** [comment]
@M3hillus 

Relics spawn in maintenance; they have a very distinctive look about them--if that's not enough of a give away, their description will "What mysteries could this hold?".

**Comment by NTSAM** [comment]
This sounds really cool and it sounds like it'd be an awesome telescience replacement.

**Comment by Fox-McCloud** [comment]
Dramatically lowered the reagents contained within the smoke cloud to account for the fact our smoke is different.

TG's smoke puts around 35-40 units of the 50 into you, but you can move away from the machine to lessen the amount. Factoring in health/reaction time, this generally means you wind up with around ~15 units in you, total---which is what I've adjusted ours to.

**Comment by Keilden** [comment]
:+1:  More nerds stalking the maint tunnels!

**Comment by Spacemanspark** [comment]
Oh fuck, this.
:+1: this will be hilarious.

**Comment by Dinarzad** [comment]
As long as TSCI can be built manually, that's A-okay by me.
Experimentor will give me chuckles.

**Comment by Mijhead** [comment]
:+1:, although I'll miss telesci for when I play AI

**Comment by veganzombeh** [comment]
Good riddance, telescience. :+1:

**Comment by KasparoVy** [comment]
Doesn't this cover all the experiments xenoarchaeology used to do on the artifacts? Is this related in any way?

**Comment by Alex6511** [comment]
:+1: @Markolie Now can we find a replacement for that /other/ job we discussed?

**Comment by Fox-McCloud** [comment]
@KasparoVy 

Not really; Xenoarch had you perform different things on an artifact--such as gassing it/hitting it with electricity, exposing it to energy beams, touching it, etc.

This machine just has a number of different buttons that have different flavortexts and different failure messages+effects that are themed around what the button name is (ie: exposing something to gas typically has failure messages+effects that revolve around releasing smoke).

**Comment by Spacemanspark** [comment]
Wait, @Fox-McCloud, did /tg/ ever remove the abilities to do the REALLY wacky shit with this, such as... uh... making Syndiborgs/ xenos/ calling in meteor event?. I never kept up with the development of this thing.
Either way, I still think this will be fun.

**Comment by Fox-McCloud** [comment]
At one time you could make xenos--that's long gone.

You could make nanomachines with their version--since we don't have that, I changed it to itching powder.

If we ever get TG style diseases back, I'll b e sure to add in nanomachines.

**Comment by Spacemanspark** [comment]
Not sure whether to sigh in relief or say "Damn it.".

**Comment by Fox-McCloud** [comment]
@Markolie 

This should be ready.

**Pull request merged**
