### PR TITLE
We need badges!

### PR DESCRIPTION
**Pull request by Allfd**
Updates the github readme file to bring us into the github tradition of having build badges!

Badges

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
:o

**Comment by Necaladun** [comment]
Obligatory we don't need no stinking badges

**Comment by Aurorablade** [comment]
:badger:

**Comment by Fox-McCloud** [comment]
I'd like this one in a big banner, if possible: http://forthebadge.com/images/badges/60-percent-of-the-time-works-every-time.svg

https://github.com/tgstation/tgstation/blob/master/README.md

Kinda like how TG has here. Some of their badges provide pretty neat stats too, if it's possible to implement those, here.

**Comment by Fox-McCloud** [comment]
👌

**Comment by Keilden** [comment]
Read badgers first, oh well I guess this will also do.

**Comment by taukausanake** [comment]
[We can have both...](https://s-media-cache-ak0.pinimg.com/736x/31/b5/f5/31b5f5daa95a61c903e1bfa5ed8fbe20.jpg)

**Pull request merged**
