### PR TITLE
Cautery Sprite Update

### PR DESCRIPTION
**Pull request by Ionward**
**What does this PR do:**
Changes the existing cautery icon to a new one, based off reference images. The old sprite is still in there, as cauteryold. 

**Images of sprite/map changes (IF APPLICABLE):**
c1706b7328b0529affac6292ee9fbbf5
cauteryb
cauterybr

**Changelog:**
:cl:
imageadd: Updated the cautery sprite!
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This looks less like a cautery and more like a grill lighter:

img

**Comment by Ionward** [comment]
> 
> 
> This looks less like a cautery and more like a grill lighter:
> 
> img

I can try and make the heating loop into a hook, and change the button spot? I do see what you mean, but I went off of "cautery tool" pictures off google.
26D4AFB91F6E87F916B27A64CE246341

**Comment by KasparoVy** [comment]
It is as intended, especially if you need to use it on a plasmaman :rofl:

**Comment by Ionward** [comment]
Alrighty, updated it. Hopefully it looks less like a grill lighter!

**Comment by Mitchs98** [comment]
I like it.

**Comment by MRgaty** [comment]
At last, my prayers have been listened to.

**Comment by variableundefined** [comment]
Grill, patients, they're all the same

**Comment by taukausanake** [comment]
The hook looks a little weird, but it doesn't matter I suppose. Rather make it straight or how it was like a pointed loop

**Comment by farie82** [comment]
No longer looks like a hot iron bar. Will take a bit to get used to but it looks better :P

**Pull request merged**
