### PR TITLE
fix eswords / cleaving saws not being sharpenable

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Increases force after check of it being a transforming weapon, rather than before.
removes force check, force_on should always be increased when force_off is increased

## Why It's Good For The Game

Sharpening the cleaving saw should work like before

## Testing

sharpened the saw
worked as intended.

## Changelog
:cl:
fix: fix eswords / cleaving saws not being sharpenable
/:cl:

### CODE REVIEW

**Comment by Danchi299** [comment]
how do you sharpen an *energy* weapon, does it make sense to sharpen the light with a grindstone?

**Comment by Sirryan2002** [comment]
Labeled with permission of headcoders

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Fordoxia** [comment]
Sharpening an esword on a whetstone sounds extremely cursed.

**Comment by Qwertytoforty** [comment]
> Sharpening an esword on a whetstone sounds extremely cursed. I think it being impossible to sharpen is perfectly reasonable and what most people would assume it would behave like.

It can only be sharpened with cult whetstones, which are magic, to be fair. The main function is the cleaving saw, which at the moment is a subtype of an energy transforming weapon

**Review by S34NW — APPROVED** [review]

**Pull request merged**
