### PR TITLE
Improves human race sprite reshading

### PR DESCRIPTION
**Pull request by Puckaboo2**
:cl: Puckaboo2
tweak: Improved shading of human sprites.
/:cl:

image

At first glance, you won't see most of the changes I have made right away, but I will explain all of them, one by one.

I shall start with the female's head.
image
As a warning, I don't really need to show the male's head comparisons because the only difference is a few pixels of shading and you can see the changes in the full body image. As you can see, I modified the blush on the south, east and west sides to make it a bit more pleasant to look at. It is mathematically shaded to be the exact color of each shade of the human skin, but minus ten hue; as a result, the blush is not too intrusive to the overall facial features, but it is not darker than the actual skin tone, either. Additionally, I added a bit of shading to the back of the head of the females and males, while giving the males a little shiny area to their head, cuz sweg.

I want you all to look at the female's body, next.
image
Nothing much changes from the front of the normal female sprites, or the back, aside from the shading on the buttocks and groin. Most of the modifications appear when you turn the female to the side, because there were some anatomical and shading issues.

Just to point out, I am showing you just the torso of the before picture, not with the arms and not with the hand. As you can see, in the before picture, you can clearly see the outline of the arm (which makes it appear the arm is still there when it is supposed to be absent), while you can see the empty socket of where the arm should be. 
image
In the after picture, I resolved the issue by removing the outline of the arm, shading the side, and making the amputated arm's socket more noticeable. Additionally, I made the shading around the front and near the breasts a lot more pleasant to look at. 

Now, let's look at the male's torso.
image
Yes, I got rid of the pecs and the four pack. I would like to add them as a torso option for males, but I do not know how I would code it in. @KasparoVy wanna work with me on this?

Anyway, much changed on the sides, aside from the change of shadowing to the rear. I also shaded a little bit of where the groin should be, just to close a small shading gap that doesn't look pleasant when viewed up close. I also patched up the shading to where you can see the indent on the sides when the arm is removed.

Additionally, I updated the shading of the fat sprites.

Let's start with the females.
image
I did not modify much of the front and the back sprites, other than smoothing out the belly, reducing the shading of the back, and making the buttocks appear more smooth and defined. Aside from smoothing out the shading on the belly, the sides received heavy modification:

The 'obvious-arm' issue was not present, but the glaring reddish blob where the hand should be, perplexed me. 
image
You should only see bare skin on waist and hip after an entire arm amputation, not a huge red blob...So, I removed it. I also fixed the female's breast to the side because it resembled a male's man boobs more than anything else.

Finally, the fat males.
image
They have bonafide, certified, moobies! Aside from the change in the shape of the chest (or now, moobies,) males are pretty much a mirror image of the females, including the removal of the red blob. I also modified the breast to the side so it doesn't look like a slab of flappy skin and more of a massive male mammary.

Well, that's it! Maintainers, I am willing to make further changes if you don't find some of the current ones to your liking.

### CODE REVIEW

**Comment by taukausanake** [comment]
As per the previous PR, because I didn't have good Internet this weekend, maybe the 6-pack can be a modification for when your character "feels stronger/more buff" when they get the mutation that shows that message. I think it would be a nice little addition. Just spit balling things here

**Comment by Puckaboo2** [comment]
@taukasanake That can be a possibility, in addition to having the pectoral muscles and the 6 pack as some sort of body type, if I can find someone to help me code it in.
@KasparoVy bby I miss you.

**Comment by tigercat2000** [comment]
After discussion between the Heads of Staff and Maintainers, it was decided that it would be best if this PR was restricted to bugfixes, as the feature changes enacted are not seen as ones we would like to merge into the codebase.

This refers specifically to the fixes detailed in these images: 


The mistake with the arm and the blood spot on fat people.

**Comment by Puckaboo2** [comment]
@tigercat2000 I've made a git amend with everything you've requested. I've re-shaded and re-shaped everything on the sprites according to the old shading. The fact we had 20 colors for one skin tone bothered me.

**Comment by Fox-McCloud** [comment]
@Puckaboo2 As detailed in @tigercat2000 's message, we are _**merely**_ looking for fixes; therefore, rather than manually re-shading everything to fit the requirements, it would be best to simply return to the initial blank state and provide the requested changes.

**Comment by tigercat2000** [comment]
Stale. Needs to be updated to Fox's request by 2017-09-12 or this will be closed.

**Comment by tigercat2000** [comment]
Considering the Stale tag, and the lack of any further development despite requests, this PR is being closed.

**Pull request closed without merging**
