### PR TITLE
Minor HUD changes

### PR DESCRIPTION
**Pull request by orelbon**
Changes Pod pilot HUD, and edits chemistry HUD.
pod
chem

### CODE REVIEW

**Comment by ZomgPonies** [comment]
merge conflicts, because of nations 2.1. Sorry buddeh

**Comment by orelbon** [comment]
ill see if  can fix it.

**Comment by orelbon** [comment]
@Fox-McCloud how do i set myself as admin in the server i use to test changes? i've tried a lot of different combinations.

**Comment by Fox-McCloud** [comment]
Need to have admin_ranks and admins in the config folder---then just follow the instructions in the admins file.

**Comment by Fox-McCloud** [comment]
Input, thoughts? Anyone?

@Markolie  @TheDZD

**Comment by TheDZD** [comment]
Eh, I don't really have much of an opinion on it.

**Comment by ZomgPonies** [comment]
I'd need to see the old ones next to them, but these look fine

**Comment by orelbon** [comment]
@ZomgPonies 
vurrent chem
vurrent pod

**Comment by Fox-McCloud** [comment]
I like the current chem better--it looks more like a flask; the one you designed looks more like a round flask, which is less stereotypical/recognizable.

Dunno about the pod pilot one.

**Comment by orelbon** [comment]
the current chemistry hud looks too flat too me, and i have never seen a flask that looks like that.

**Comment by Robertha89** [comment]
First up it's a Erlenmeyer flask, and anyone can recognize that, considering the flat bottom, conical body, and cylindrical neck. Now, the Securit pod pilot hud is basically a simple spaceship. Yours look like a bomb, while the chemist hud is more like a Buchner flask without the neck tube, or a short-necked volumetric flask. 

To sum it up, the current chemistry one is better, due to the iconic shape, while your pod pilot one seems, eh, its not as iconic, and I have troubles seeing what it is supposed to be, I mean Cross for Medical, cause medical cross, gun for security, because security got guns. So I can't really say any of these would be a suitable replacement.

**Comment by orelbon** [comment]
welp i'll be closing this then.

**Pull request closed without merging**
