### PR TITLE
Fixes some armour value oversights

### PR DESCRIPTION
**Pull request by Aquilar**
## What Does This PR Do
Fixes some oversights with various values of security armour
I consider the value changes for the berets and wintercoat fixes since the original values were probably never intended to be as high as they were so the security officer berets were brought to be inline with security soft cap because the accidentally inherited the same values as the hos and warden berets, as the general intention is your sacrificing protection for looks. 
while the security winter coat is an alternative the security jacket but ended up inheriting the armour values of the captains winter jacket, this in turn make it unintentionally better than the armour vest when accounting for the jumpsuit due the increased coverage it provided, it's also a load out item.

so the numbers:
- security and officers beret had their melee resistance lower by 5 and bomb resistance removed
- the HoS' beret get it's laser resistance increased by 5 to match the warden's
- security soft cap has it's armour values brought up to the berets along with removing the explosion resistance
- the armour values for the security winter coat were lowered to match the security jacket.

## Why It's Good For The Game

This solves some unintentional buffs to security head and suit gear.

## Changelog
:cl:
balance: fixes armour values across pieces of security gear, specifically berets and wintercoat
/:cl:

edit: removed all the changes related to the plasmamen helmets for another PR, cleaned up text.

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
What exactly is "Fashionsec"?

**Comment by Ty-Omaha** [comment]
These look more like balance changes not fixes / oversights

**Comment by Aquilar** [comment]
> What is "Fashionsec"?

security officers that are wearing the sec jacket/winter coat, the wintercoat is pretty strong and is a load out only item, and wearing the beret rather than the helmet because at the moment, there is zero reason to ever wear the helmet outside of being set on fire. 

and in response to this issue https://github.com/ParadiseSS13/Paradise/issues/12807

**Comment by Ty-Omaha** [comment]
All of these values are not the same as what the security helmet currently has. 
https://github.com/ParadiseSS13/Paradise/blob/5936bb98fea2bc46769df7ee6bdf57a5f3f3db37/code/modules/clothing/head/helmet.dm#L8

**Comment by Aquilar** [comment]
because they been pulled down to the values of the soft cap.

**Comment by Ty-Omaha** [comment]
So it is not fixing any oversight at all, but changing the balance.

**Comment by Aquilar** [comment]
The armour values for beret and wintercoat were added 4 months ago, the oversight here is the values were implemented without consideration or notice of 3 existing pieces of sec gear, the security cap, security jacket and security helmet. this ended up making the security wintercoat better than the standard armoured vest because similar armour values and better coverage, this is clearly unintentional, and the same goes for the beret. 

the additions to the plasmamen helmets were purely to bring them line with the regular head gear on the jobs those belong to.

**Comment by Cazdon** [comment]
Why not make all the hat values on par with the helmet? I can at least see the reasoning behind the winter coat being put on par with the security jacket because it covers the arms, and the regular armor does not.

Why not just put all the hat values on par with the helmet and leave the players with more freedom of expression? Why make them strictly worse? I understand that they're not hard helmets, so maybe they shouldn't be as strong, but we already make big stretches in logic, and making another one as small as armor values for better freedom of expression isn't a bad trade at all. There's no reason to kill fashionsec.

Also you might want to explain why you view this as a fix in the original post, most people don't know why you would consider this a fix and it comes off as passive aggressively calling your balances changes fixes, despite the fact that I agree the Winter Coat thing is a fix.

**Comment by Aquilar** [comment]
Duly noted, though many people would consider trading protection for looks a while worth trade. 
To be honest, it's 5 points of difference in armour has little impact in practice until you start hitting the bigger numbers. yeah lets make all the values same but keep the explosion resistance removed and lessened fire resistance, helmets needs to have a reason to be worn.

**Comment by Krysonism** [comment]
> Why not make all the hat values on par with the helmet? I can at least see the reasoning behind the winter coat being put on par with the security jacket because it covers the arms, and the regular armor does not.
> 
> Why not just put all the hat values on par with the helmet and leave the players with more freedom of expression? Why make them strictly worse? I understand that they're not hard helmets, so maybe they shouldn't be as strong, but we already make big stretches in logic, and making another one as small as armor values for better freedom of expression isn't a bad trade at all. There's no reason to kill fashionsec.

If you want to wear a nice hat but you choose not to because it has less stats, you have a powergaming mindset that should not catered to on a RP server.

Even a lower RP level server like tg, has substantially lowered stats for the standard security berets and soft caps because it just makes sense.

This is a role playing game not an arena shooter, lower armour values have never stopped me from wearing a softcap on tg.

**Comment by Denthamos** [comment]
Mmn, Aquilar has a point however.  The armor values being changed was an unintentional change and buff which was not listed nor detailed in the previous PR.  If a buff should be given to security gear then that should be handled in a separate PR for deliberation because I believe a security buff would be highly contested by people.

In the meantime a fix should be implemented so things are back to how they should be.

**Comment by Aquilar** [comment]
> Mmn, Aquilar has a point however. The armor values being changed was an unintentional change and buff which was not listed nor detailed in the previous PR. If a buff should be given to security gear then that should be handled in a separate PR for deliberation because I believe a security buff would be highly contested by people.
> 
> In the meantime a fix should be implemented so things are back to how they should be.

so do I send the berets down to the softcap's original level or bring them in line with the helmet?

**Comment by MRgaty** [comment]
I think there is no reason to not give all the hats the same armor values, even if it makes no sense ICly, I dont see a reason to punish the players who simply want to wear a hat with less armor.

**Comment by Necaladun** [comment]
Armor values should be fairly consistent, this looks like oversight and mistakes, so it's good they're corrected.

**Comment by Fox-McCloud** [comment]
please fix conflicts.

**Pull request merged**
