### PR TITLE
[Ready for Review]Adds different looking organs to each species, some blood color changes, and MMI changes

### PR DESCRIPTION
**Pull request by Quantum-M**
**What does this PR do:**
Gives each species different looking organs (that is only sprite changes, **NO** mechanic changes) based on how they look by their blood color and lore.

Adds different MMI sprites based on different species brains.

The intent here is to attempt to make each different species a bit more alien to each other, by giving them different looking organs.

Suggestions will be appreciated.

**Organs:**
- [X] Unathi
- [X] Skrell
- [X] Tajaran
- [X] Kidan
- [X] Plasmaman
- [X] Grey
- [X] Vox
- [X] Vulpkanin

**MMI Stuff:**

- [X] Create different MMIs sprites based on different brains.

**Images of sprite/map changes (IF APPLICABLE):**
More to come (Please note that the images shown may not be a final product):
image
Plasmaman
image
Unathi
image
Grey
image
Skrell
image
Kidan
image
Vox
image
Tajaran
image
Vulpkanin

**Changelog:**

:cl:
imageadd: Different organ sprites for each species
imageadd: Different MMI sprites based on different species brains.
/:cl:

### CODE REVIEW

**Comment by Quantum-M** [comment]
Unathi and grey MMIs animated: 
unathimmi
greymmi

**Comment by datlo** [comment]
Don't forget that ears are also an organ now. And the current sprite isn't great, either, imo it can definitely  use the update even for humans

**Comment by dovydas12345** [comment]
Oh my! That is nice and once again nice.

**Comment by Fox-McCloud** [comment]
I would prefer Vulpkanin blood color be left alone, as is. Colored blood purely because "mai ayliums" isn't particularly compelling.

**Comment by variableundefined** [comment]
I think Vulpkanin & Tajaran blood in particular should be left alone as they're both mammal and should bleed red. The same actually goes for Unathi - Most species of lizard also bleed red.

**Comment by KasparoVy** [comment]
I dig the blood difference.

**Comment by KasparoVy** [comment]
Maybe when it's dialed in you can spill a bunch of blood for the blood gods (and review)

**Comment by Quantum-M** [comment]
Added sprites for skrell and plasmaman organs, images updated accordingly.

**Comment by Quantum-M** [comment]
image
@variableundefined 
H is for human blood, U is for the Unathi blood, and T for tajaran blood.
I should probably make it lean more towards red.

**Comment by FlattestGuitar** [comment]
On Oracle the entire point of changing the color was to help stress the difference of the blood types. On here everyone uses human blood, so I don't think it makes much sense.

**Comment by taukausanake** [comment]
Huh. _Actually alien blood_. That's something that never came to my mind. Might be nice to consider some day

**Comment by KasparoVy** [comment]
@FlattestGuitar YES PLEASE

**Comment by taukausanake** [comment]
Is it possible to make blood more crimson than the already red human blood? Some how a more deeper red? I think that would go best for Vuplkanin and have the least resistance from fox-mains. Also I kind of agree with it

**Comment by datlo** [comment]
Could you also update abductors to use the new grey organ sprites? They're related and the sprites also fit them. :alien:

**Comment by Quantum-M** [comment]
More work pushed, all organs for the main races has been created (sprite wise) along with the blood color. Only things that remain is the MMI thing and fixing some odd bug that keeps popping up in regards of organs.

**Comment by Quantum-M** [comment]
Finished fixing a few bugs/mistakes that popped up, touched up the vox lungs, tested, PR is ready for review.

**Comment by taukausanake** [comment]
It looks like Vulpkanins bleed tomato juice now. I'm okay with that

**Comment by KasparoVy** [comment]
Rest in Pizza

**Comment by variableundefined** [comment]
So here's what we (Fox & I) think of this PR:

Vulpkanin, Tajaran & Unathi should all stay red-blooded with the same coloured organs, or the same colour as their earthly counterpart, because they are in fact, based on real life animals and should stick to that theme. As far as I am aware fox, cats and lizards mostly bleed red. I don't think it make sense to have them bleed different just because "alien".

Grey, Kidan, Plasmaman and Skrell make sense to have differentiated blood colour / organ colour where appropriate.

However from what we see, it feels like all of the organ sprites are just a simple re-color without any proper shading or real difference besides color. We'd like this to be more than a simple re-color, and for the changes for Tajaran, Vulp & Unathi to be dropped.

**Comment by Pixelzilla** [comment]
I kinda feel like this is change for the sake of change and that it doesn't really make things feel alien by slapping different colors on things.

It makes perfect sense that most of the species that breathe oxygen would have blood that is the same color. Hemoglobin carries oxygen around and the iron in it makes it red. It's that way irl after all and if we're gonna deviate to make it 'alien' we should probably have a good understanding of why things are different colors and what makes them that way to make it convincing vs "magical spess aliens!"

There are other creatures that have blue or even yellow blood but they're certainly the minority. It's nice to have some species with the same blood coloration - it makes it a lot more interesting to investigate a crime-scene and not always possible to tell who/whats blood is covering something.

As for the organ sprites I think they could use a wider variety of color on them and more contrast instead of a simple palette swap. Even human organs are not the same shade of a single color, there is a wide variety of colors. It'd be nice to see some of that.

**Comment by Quantum-M** [comment]
> However from what we see, it feels like all of the organ sprites are just a simple re-color without any proper shading or real difference besides color. We'd like this to be more than a simple re-color, and for the changes for Tajaran, Vulp & Unathi to be dropped.

@variableundefined , you want me to discard all the changes, blood and organs, for Unathi, Tajaran, and Vulpkanin and change the sprites for the other species?

> Vulpkanin, Tajaran & Unathi should all stay red-blooded with the same coloured organs, or the same colour as their earthly counterpart, because they are in fact, based on real life animals and should stick to that theme. As far as I am aware fox, cats and lizards mostly bleed red. I don't think it make sense to have them bleed different just because "alien".

> It makes perfect sense that most of the species that breathe oxygen would have blood that is the same color. Hemoglobin carries oxygen around and the iron in it makes it red. It's that way irl after all and if we're gonna deviate to make it 'alien' we should probably have a good understanding of why things are different colors and what makes them that way to make it convincing vs "magical spess aliens!"

I would argue that, while yes they are based on earthly creatures, it doesn't mean they _are_ earthly creatures. While they may share some appearance things and biological functions, it doesn't mean they have the same exact biological mechanisms as the earth counterparts, since, lore wise, they are all from different planets, such differences could include blood color.

**Comment by variableundefined** [comment]
Basically, yes.

Another potential issue is that we can see who got hurt much more easily without everyone sharing the same blood color.

**Comment by HugoLuman** [comment]
I love it! Just one thing: Vox already have their own brain sprites, which are kept in some weird dmi. They use cortical stacks, which are vulnerable to emps can afaik can't be slotted into mmis

**Comment by Shadeykins** [comment]
> 
> 
> Basically, yes.
> 
> Another potential issue is that we can see who got hurt much more easily without everyone sharing the same blood color.

Isn't this already the case for several species? Drask, Vox, IPC, etc.? That would appear to be something that actually changes up/differentiates species in a somewhat meaningful matter (for the purposes of forensics).

**Comment by Necaladun** [comment]
Disclaimer: I am shit at art and graphics and all that.

In general I love the idea of differentiating the organs and giving them a unique feel, and I like the more "normal" races having similar red bloods.

The actual colouring on the organs however still feels a bit off to me. I think they're good enough to go in, however, some form of...shading? might be nice, and perhaps getting them not so bright would be preferred.

**Comment by Spartan6** [comment]
Vox organs are... the wrong colour.
The organs should be the same colour as the blood. That's how colouration works.

**Comment by taukausanake** [comment]
@Spartan6 they... are blue? The name is under the sprites. It was weird for me to read it but if you start from the bottom and go up you notice how they are

**Comment by Spartan6** [comment]
@taukausanake Oh. Right. That's silly :eyes:

**Comment by variableundefined** [comment]
@Quantum-M Sorry for the late response. I've discussed this with Purple - This should be good to merge if vulp / taj / unathi blood color is made to be the same as human again. We don't think it is necessary and it'll make the whodunnit game much easier.

**Comment by Breenland** [comment]
This is all fancy and nice! Do you think you could
get a drask MMI sprite in the future? Unless it already is, and I just missed it.

**Comment by Quantum-M** [comment]
@variableundefined , only those bloods and nothing else? If so, I'll see if I can change it a bit later.

@Breenland drasks already had a MMI sprite.

**Comment by Quantum-M** [comment]
Tajaran, Unathi, and Vulpkanin now has regular blood color, the red human one that is.

**Pull request merged**
