### PR TITLE
[WIP] Add Shuttle Navigation Computers to all syndicate shuttles

### PR DESCRIPTION
**Pull request by datlo**
Add a shuttle navigation computer ported from tg to : 
- The Nuke Ops shuttle
- The SIT and SST shuttle
- The Vox Skipjack
- The Administration Shuttle

These computers allow you to set a custom destination to go to. Pictures below for details

Additionally, syndicate shuttle consoles are now indestructible and impossible to deconstruct.

The White Ship navigation computer is coded but not quite functional yet, so it's not mapped in. I'll probably make it functional and add it to the maps in another PR since it has additional balance concerns aswell.

navigation1

Once you use the computer, you enter a remote view of the area you're going to set as landing
navigation2

You can then select any area that is 1. Space turfs only 2. Not used by another shuttle as a docking port 3. Not otherwise restricted (syndicate depot)

navigation3

You can then use that destination using the shuttle console, as you'd usually move

navigation4

And you're there!

navigation5-5

If you try to select any area you can't go to, the relevant turfs will be highlighted in red.

navigation5

You can also choose another zlevel to move to. Syndicate shuttles cannot go to the derelict. (no NT installations there + balance concern with the depot being in that zlevel)

navigation6

TODO : 
Fix being able to view objects using the navigation computer (you should only be able to see turfs), must be done before merge/testmerge

Fix offsets for the administration shuttle so it's centered properly and doesn't go offscreen

Fix any map conflicts when christmas cyberiad will be removed (i learned how to do it this time I'll try not to fuck it up so much)

Write full changelog once this is completed

### CODE REVIEW

**Comment by datlo** [comment]
I'm not sure why map diffs borked. Is it because I modified different maps in the same PR?

**Comment by Mithrandalf** [comment]
oh wow

**Comment by datlo** [comment]
Due to map diffs not liking 2much in one pr, I'll make changes to delta and meta in other PRs to make this function on these maps if this PR goes through, in the meantime the shuttle will still function using the existing set docks.

Still working on this!

**Comment by datlo** [comment]
I'm closing this for now. I might revisit this in the future, and it's really not that far from completion if I can just fix that one issue that lets the user see everything and not just turfs, but right now thinking about getting back to this stresses me out and I'd rather have it closed and not give people false hopes.

I'm hoping to get back to this, but not right now.

**Pull request closed without merging**
