### PR TITLE
BoxStation: Cargo Remap

### PR DESCRIPTION
**Pull request by DogeDogIs**
This PR make a cargo remap, causing the QM office to be moved, the bay has been modified, a new part for the maints and changing the miners' area.

## What Does This PR Do

This PR makes the Cargo a little bit restored and taken out of the grave, with this remap, the QM office is more evident, thus making it have greater visibility over the entire charge and at the same time having a better importance across the board. your department. Another change that also occurred was that now the Old Vault, instead of being a big box, became a 2x5 vault, with a small change of maints and adding a new room in the maints where was the old room of the QM, which is now a " Old Shop", a place where you can open the Shutters and turn that little room into a place to sell your products and has direct access to the hallway.

## Why It's Good For The Game

This change brings the appearance that the Quartermaster now has more importance in every position, since as he is practically in the middle of the Cargo, so at the same time that the QM has a complete view of the Cargo, the QM also has more importance over the whole Department. The place that used to be the office was very closed and secluded just for the Miners area, but as the QM doesn't only deal with the miners and also wants to have a view on the events of the Bay, the change was made so that he has all this view , being from the Miners, Bay and the Lobby. The mains were also modified and a new point was added, and about the Vault having reduced its size, I think 2x5 is more than enough.
## Images of changes

cargo5
image
image
image
image
image
## Testing

entered in my local host server, joined as qm, clicked buttons and walked in areas, they are good. And walked as assistant in maints to see if all doors had the access

## Changelog
:cl:
tweak: Remapped Cargo
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
Can't really proper review at the moment, but would look at changing the solid wall on the bottom left of the cargo bay to be glass windows as well, I think. Opens it up, lets more lighting in.

**Comment by Tokorizo** [comment]
I really liked the spacious vault in cargo maints, nice place to make a hideout. But alas it wasn't very impactful except letting people practice hacking into a vault door. Either way yeah this looks pretty good.

**Review by S34NW — CHANGES_REQUESTED** [review]
image
The double lever, non corner belt gives the impression that these are separate belt systems. I'd drop the lever count to one and center it for this run as it is short, and make the corner belt one an actual corner.

image
We have firelocks under all four of these doors right now, maybe we could tone it down a smidge? (Not your fault AFAIK)

image
The camera layout here makes the far-left one somewhat redundant, perhaps it would be better to delete that one and move the one labelled "Cargo Bay South" further down?

image
image
Please take the time to sort out the horrific mess that is disposals in this area, while you are here. There is no need for it to behave like this

image
lastly, please add some brown siding to this side of the room, it feels a bit spartan and grey

**Review by S34NW — APPROVED** [review]

**Comment by Bm0n** [comment]
image
Maints area here should be over the door not on a random wall

image
This one cent hall area should be port maints.

image
The right side of the QMs office around the door should be areaed to the QMs office not mining/cargo office.

image

Missing firelocks here on the left side of the shuttle dock

image

None of these lattice here are nearspaced

image

Same but down by solars now.

image

I recommend replacing this single polarized window here in the QMs office with a normal wall to give the room a more rounded look

image

I know a door used to be here in an older version of this PR so that's probably why this wall is still here. Perhaps replace the wall with a girder as I think it fits better for maints.

image
This random window spawner in maints seems to have been placed in error(i think?). If not it just looks weird.


Should be it, overall looks better than old cargo.

**Comment by S34NW** [comment]
> Missing firelocks here on the left side of the shuttle dock

This is fine, two sets of fire doors are not needed here, it just clutters the area.

**Comment by DogeDogIs** [comment]
> image This random window spawner in maints seems to have been placed in error(i think?). If not it just looks weird.
> 
> Should be it, overall looks better than old cargo.

Yea this window was a missclick, lol

**Comment by Bm0n** [comment]
image
Two dirt decals stacked ontop of each other.

image
Light fixture on a grille, should be good after that.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
