### PR TITLE
Sprites for C.O.R.G.I the cyborg!

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
Just some more custom synthetic sprites for my cyborg, you will have to
put theultimatechimera;C.O.R.G.I in custom_sprites.txt like how it is
for my AI sprite, in the config folder. It must be a semi-colon.

Updated Images: There's a color change to them all but it's hard to notice at a glimpse, you will be able to notice it very well in-game.

Standard: standard

Engineering: engineering

Janitor: janitor

Medical: medical

Miner: miner

Security: security

Service: service

### CODE REVIEW

**Comment by Earthdivine** [comment]
Isn't this mostly the same as using the Xenoborg sprite, except with a color change?

**Comment by Ultimate-Chimera** [comment]
Mostly, there's blue eyes but Dumbdumn is figuring out the eye thing so it's not always blue when I'm dead and stuff.

**Comment by Ultimate-Chimera** [comment]
Need to edit the sprite a bit more, should be done soon.

**Comment by Ultimate-Chimera** [comment]
Still needs a unpowered sprite.

**Comment by Dumbdumn5** [comment]
Fixed the eye sprite, should be working now.

**Comment by Ultimate-Chimera** [comment]
Nope, gotta fix something.

**Comment by Ultimate-Chimera** [comment]
Ready to merge.

**Comment by Fox-McCloud** [comment]
I dislike this, for a number of reason:

(1) All the borgs are completely indistinguishable from each other--communicating what type of borg someone is playing as is fairly important, so people no how to approach that borg or what it's capable of.

(2) the sprite is incredibly close actual Xenomorphs, which could induce confusion for players--yes, I realize that there's the costume you utilize, but there's quite a few telltale signs about its design that very very quickly communicate that it's "not a xeno". Effectively the only difference between this sprite and an actual Xeno is color tone.

**Comment by tigercat2000** [comment]
@Fox-McCloud Last I checked, borgs told you what module they were on examine().

**Comment by Ultimate-Chimera** [comment]
There's lights that flash on it, I couldn't get it to work properly because the modules are different than bay, which I got the guide from, I have removed the modules like Surgeon, Crisis, Construction and Clerical. I could ask Dumbdumn to change the color tones, but I still can't figure out how to get it to work on these modules.

**Comment by Ultimate-Chimera** [comment]
Can I have this as "Do not Merge" for now?

**Comment by Dumbdumn5** [comment]
Remade all borgs with varying color scheme, as for Identification purposes, you want me to make a few more obvious lights? Could make its rib cage glow a bit.

**Comment by Dumbdumn5** [comment]
Welp, got a request to do the lights on the rib cage. Doing that now.

**Comment by Ultimate-Chimera** [comment]
Okay, it must be something to do with the code preventing it from working, does anyone know where the custom synthetic code is?

**Comment by Ultimate-Chimera** [comment]
I figured it out! I looked through the code and found out that the default "-" for cyborgs was changed to ";" so, yeah! Remove the "Do not Merge" label.

**Comment by Fox-McCloud** [comment]
@Ultimate-Chimera 

It will be removed when this is more thoroughly discussed and settled with the administrative team.

**Comment by Ultimate-Chimera** [comment]
Alright.

**Comment by Fox-McCloud** [comment]
Alright, some new information has come up about this, and after discussion of this matter with the staff, I'm afraid this PR is unacceptable--I've also been informed that you attempted to submit this in the past, and it was also denied--that still stands, I'm sorry.

**Comment by tigercat2000** [comment]
@Fox-McCloud This wasn't submitted in the past- a PR to let him use an already-made xenoborg sprite from the xenomorph gamemode was submitted, and denied because ponies didn't want a sprite with potential used. This sprite was designed by him and dumbdumn, with actual colors for each module, I think your discussion may have been misinformed, correct me if I'm wrong.

**Comment by Robertha89** [comment]
This is what @Ultimate-Chimera told me when he requested a sprite from me regarding xeno borgs a few weeks back. Essentially Pony said no due to the use of the white xenoborg sprite, rather then a new one.

**Comment by Ultimate-Chimera** [comment]
I feel bad for all the hard work I put on dumbdumn.

**Comment by Fox-McCloud** [comment]
This was discussed over in the senior administrative chat, and it was still agreed that it was too close to the Xenoborg sprite in appearance (despite the color change), still didn't have enough differences between models, and @ZomgPonies still indicated it's a "no" thing--- @Earthdivine stated the same thing.

**Comment by Ultimate-Chimera** [comment]
@Fox-McCloud It does have some animated flashing lights all over it but fine.

**Pull request closed without merging**
