### PR TITLE
Making the jump to 512 time bois

### PR DESCRIPTION
**Pull request by tigercat2000**
512 512 512 512 512 512
👏 👏 🎆 🔥 🍾 🌳 

:cl:
add: We're going 512 boisssssssssssssss
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
Rip

**Comment by SamHPurp** [comment]
There are other sections worth updating too... for example...

https://github.com/ParadiseSS13/Paradise/blob/73091bf78c29d6699348b17a5412cf3b2a2a3b17/code/game/world.dm#L1

**Comment by variableundefined** [comment]
Maints and host agreed unanimously on this.

HERE WE GO.

**Comment by KasparoVy** [comment]
512 OR COMBUST

**Pull request merged**
