### PR TITLE
Fixes (Missing) Wiring + Vent and Scrubber (Paramedic)

### PR DESCRIPTION
**Pull request by Twinmold93**
Simple fix... Would have fixed it with the other PR had I been aware of the issue. If there are other mapping issues as well, I can include them to this PR just so we have fewer PRs filling up the space for mapping fixes.

:cl:Twinmold
Fix: Wiring to brig firing range now a node instead of a curved wire.
Fix: Missing medical wire under recovery ward door.
Add: Vent and scrubber to paramedic's room.
/:cl:

### CODE REVIEW

**Comment by Pennwick** [comment]
There are actually two more things I noticed as a drone, One is a scrubbers pipe south of Operating room 2 in maintenance. Second is a wire under the doors between medbay and the recovery ward in surgery.

**Comment by Twinmold93** [comment]
@Pennwick The scrubber issue will be resolved next patch. I'll look into the wires in that area quick.

**Comment by Twinmold93** [comment]
Added that missing wire. Also added in missing vent and scrubber from paramedic's room.

**Comment by GelatinousGlob** [comment]
It makes sense to have piping in the incinerator, especially with the scrubbers concentrated closer around the burn airlock door. Even without someone being dumb, that window always gets busted open and the only entrance is from maintenance which also does not have air vents.

**Comment by Twinmold93** [comment]
I do note that it can be kind of a 'meta' changer/balance changer for vent-crawling mobs, as it is another location that the AI cannot see. I would like a maintainer/head of staff's go-ahead if I should add it in.

**Comment by Pennwick** [comment]
Found another one. Theres a missing air supply pipe under one of the doors in the AI MiniSat Antechamber. The three vents furthest to the north are not hooked up to hooked up to the AI Atomospherics system.

**Pull request merged**
