### PR TITLE
Adds/fixes the xenomorph transformation disease.

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
I don't know honestly... *shrugs*

### CODE REVIEW

**Comment by tigercat2000** [comment]
Disease datums aren't a thing anymore..

**Comment by Ultimate-Chimera** [comment]
Oh, they aren't? How do I fix/add this then? :P

**Comment by tigercat2000** [comment]
Not easily. You would have to make it a stage 4 virus effect under the virus2 system, which frankly, I don't even know how to do properly.

**Comment by Ultimate-Chimera** [comment]
Actually, I did that before with messing around with the code, but I could only do alienize() but yeah...

**Comment by Ultimate-Chimera** [comment]
Wait, wouldn't this datum disease work with xenomicrobes? Because they make a path to this exact destination.

**Comment by tigercat2000** [comment]
Xenomicrobes don't work as far as I know.

**Comment by Ultimate-Chimera** [comment]
Ah, so I have to do this another way... I'll figure it out and make another PR. Thanks for letting me know about this, tiger. :)

**Comment by Ultimate-Chimera** [comment]
Also please fix me(). :(

**Comment by Fox-McCloud** [comment]
If/when we ever get around to re-implementing TG styled diseases, this would be included.

**Comment by Ultimate-Chimera** [comment]
Oh, alright fox.

**Pull request closed without merging**
