### PR TITLE
Tweaks the HUD to be more blue 2

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
PR #18242 remade. This was a somewhat controversial PR, please read the comments from the old PR.

>Makes the health doll blue when at full HP like on TG.

>The mindshield flashy icon thingy is now blue when active like on TG.

>The new blue icons come from TG.

## Images of changes

>image

>image

>image

## Changelog
:cl: Bmon
tweak: The health doll is now blue at full health
tweak: Mindshield implants now display as blue on sec huds
/:cl:

### CODE REVIEW

**Comment by moxian** [comment]
The health doll and the mindshield border are completely unrelated; I don't see why they would be bundled in the same PR.

**Comment by Bm0n** [comment]
> The health doll and the mindshield border are completely unrelated; I don't see why they would be bundled in the same PR.

Because blue means active full or complete for the rest of our HUD. A mindshield being active indicates that thus this is a consistency change and both are lumped in together

**Comment by moxian** [comment]
The green border of the mindshield does not mean "mindshield active". It just means "mindshield".
Same way as green background of librarian icon does not mean "librarian active".
Chemical implant displays as blue on sechud, but not because it's "active" - merely because we decided to use blue to represent it. Same way tracking implant is not red because it's "inactive", but only because it's the color for tracking implant.

I don't have strong opinions on either change being good for the game, but there's no meaningful connection between the two.

**Comment by Bm0n** [comment]
> The green border of the mindshield does not mean "mindshield active". It just means "mindshield". Same way as green background of librarian icon does not mean "librarian active". Chemical implant displays as blue on sechud, but not because it's "active" - merely because we decided to use blue to represent it. Same way tracking implant is not red because it's "inactive", but only because it's the color for tracking implant.
> 
> I don't have strong opinions on either change being good for the game, but there's no meaningful connection between the two.

Okay chemical and tracker implants are a whole other thing, they need to be different colours to differentiate them, same with job icons, you cannot draw comparisons between the two.

I really don't get your point, the border does mean that a mindshield is active in someone.

**Comment by hal9000PR** [comment]
This PR has 3 design objections and nobody in support after half a month, closing.

**Pull request closed without merging**
