### PR TITLE
People with squishy limbs can now squish

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:
rscadd: People with slime people limbs can now *squish
/:cl:

### CODE REVIEW

**Comment by NTSAM** [comment]
PR OF THE YEAR AWARD GOES TO @Crazylemon64
:clap: :clap: :clap: :clap:

**Comment by johannhawk** [comment]
inb4, slime limb donors, to spread the squish!

**Comment by johannhawk** [comment]
ok, i have a question, what if its a cybernetic limb that comes from a slime person, that has been attached to a non-slime person?

presumably it would be partially covered in slime muck to be able to be manipulated by slime people...

**Comment by Crazylemon64** [comment]
I figure it's not really important, though I should really fix up robotic limbs to not take the DNA of the person they're attached to...

**Comment by johannhawk** [comment]
just semi-worried about slime people players with every one of their limbs being cybernetic and not being able to squish...or other people who have attached a slime persons cyberarm not being able to squish...

why am i worried about this?

**Comment by Crazylemon64** [comment]
I mean, you can't robotize a torso, so they should be fine
And if you're fully robotized, can you be said to be a member of your original species, at least genetics-wise?

**Comment by Tastyfish** [comment]
The code in this PR keeps the species check, and then if you're not a slime person, checks the organs, so you'd still be able to squish if you were genetically slime but heavily cyborgified.

**Comment by johannhawk** [comment]
well, im just thinking if it would be reasonable to ask that cybernetic limbs that originate from slime people could be squishable on non slimes...

probably not reasonabe, really.

**Pull request merged**
