### PR TITLE
Dead humans are now no longer able to emote

### PR DESCRIPTION
**Pull request by Crazylemon64**
With this fix, there's now a check at the beginning to make sure that dead humans aren't doing any emotes. I wasn't sure, however, if I should have taken precedent from the simple_animal code for emotes, which only lets them do so when conscious. To keep it safe, I left it so that unconscious humans could still emote.

There isn't anything that needs a dead body to do an emote, right? I'll leave this here while I do a search to make sure that's the case.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Mmm, this will prevent bodies from deathgasping, too. Alright, let me see if I can move things around...

**Comment by Crazylemon64** [comment]
Is there anything else that needs a fix? And did I make a mistake with the rearrangement of the deathgasp emote?

**Comment by TheDZD** [comment]
Fixes #2406.

**Comment by Fox-McCloud** [comment]
Just to make sure, this does still display "seizes up and falls limp", correct? That was the problem we had the first time; dead emotes were stopped, but so was deathgasping.

**Comment by Crazylemon64** [comment]
Now that I've got the sleeper sufficiently tested, I'll grab this branch and do a quick test to make sure it works fine. I'll leave another message here when I've done so.

**Comment by Crazylemon64** [comment]
I've tested it, and it looks like it works. I thought I saw a bug when testing that the person died twice, but I wasn't able to replicate it, and I don't think my fix would have caused it anyways.

Merge away.

**Pull request merged**
