### PR TITLE
Fixes Cargo Disposals

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes cargo disposals not properly recycling items/objects.

Easily accomplished by adding a single pane of glass.

img

This: https://github.com/ParadiseSS13/Paradise/pull/8605 wasn't updated in forever and is seemingly dead; my solution also solves it with far less remapping.

Closes: https://github.com/ParadiseSS13/Paradise/pull/8605

:cl: Fox McCloud
Fixes: Fixes cargo recycler never recycling items on its own
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
Glass window will break

**Comment by alexkar598** [comment]
Also,did you test it?

**Comment by Fox-McCloud** [comment]
Yes, I tested it, many times. No the glass doesn't break.

**Comment by Crazylemon64** [comment]
This SHOULD be OK since it only modifies the value of a single unique key

**Pull request merged**
