### PR TITLE
Custom Items - Diemos Vezzati

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds in their custom jumpsuit, armor vest, and sec mask.

### CODE REVIEW

**Comment by fj45** [comment]
Sprites?

**Comment by Fox-McCloud** [comment]
I hope there's a way to ensure that the vest only spawns if he's playing a particular job--otherwise always having a vest, regardless of the job he plays is selling power.

**Comment by Spacemanspark** [comment]
If you look at the Custom item sprites topic buried in the forums, there is a part that asks "What job will these spawn in? Be reasonable". So I would assume...

**Comment by FalseIncarnate** [comment]
Yes, the vest and gas mask are limited to sec department + blue shield. The gas mask is like the old full-face security one (the HoS still has one) that has a built in compileronator.

The jumpsuit is for all classes. Ponies will be handling that portion since that is all DB stuff. This PR just gets the sprites and item paths in place so he can reference them for the actual spawning.

**Comment by jack-fractal** [comment]
The object names should be changed. You need to namespace them. They're too generic, "bloody" and "customblue" are not good names. Use your byond key as part of the name, so something like "/obj/item/clothing/under/fluff/falseincarnate_blueshieldundersuit".

**Comment by FalseIncarnate** [comment]
First, these items are not for me, so including my own ckey would be improper.
Second, the jumpsuit is meant to be generic sounding: it's for all jobs, not just blueshield.
Third, I based my path names off how some of the other items in the file are done (see labcoat/fluff/pink). This however is inconsistent throughout the whole file, some include names, some do not.

**Comment by jack-fractal** [comment]
Sorry False, I thought these were yours. I do think you should flag them with the name of the player and character who they're for, but that's probably my OCD talking.

**Pull request merged**
