### PR TITLE
Reformat of Prize Machine & Merch Store List

### PR DESCRIPTION
**Pull request by Tails2091**
Makes both machines readable by getting striped tables working, the code was there just not working, window size matches vending machines now too. List were also edited, reordering least to greatest by price, also changing some typos and capitalizations.

Before:
prizebefore

After:
prizeafter

:cl:
tweak: Made Prize Machine & Merch Sore readable.
typo: Fixed capitalizations and typos in both lists.
/:cl:

### CODE REVIEW

**Comment by pinatacolada** [comment]
I would remove the black border, the light/dark grey background already separates each line, and i dont think blacl borders are used anywhere else in nanoui

**Comment by Tails2091** [comment]
I wasn't sure if I should keep the border or not, I'll change it now.

**Comment by FalseIncarnate** [comment]
Gonna recommend you give the merch store console (located in cargo) the same love you did here, since they are practically the same interface. The offset stuff bugged me when I made the prize machine but at the time I didn't have the patience to try and pretty it up.

Otherwise looks a LOT better!

**Comment by Tails2091** [comment]
Thanks and I can take a look at it!

**Comment by Denthamos** [comment]
Very nice, that interface has always been a tad annoying to work with.

**Comment by Tails2091** [comment]
I have the cargo merch store updated with this, don't want to post the pr until this one has no issues with anyone. I'd like to convert them to NanoUi eventually but I think this is better for now.

**Comment by Fox-McCloud** [comment]
Just post them together, because the current UI is so awful on both of them.

**Comment by Fox-McCloud** [comment]
I'm personally a fan of the previous implementation. Having the black lines around things gives further definition and makes things really "pop" so to speak.  While the interface is 100% better, have very defined borders, for buttons is generally desirable.

**Comment by Tails2091** [comment]
So I should put borders back in?

**Comment by Tails2091** [comment]
@Fox-McCloud Outside borders are in.

**Pull request merged**
