### PR TITLE
Removes unused audio/music

### PR DESCRIPTION
**Pull request by FloFluoro**
## What Does This PR Do
This PR removes 12 unused audio/music files from the game folder, freeing 6.38MB total.

<details>
<summary>List of files removed:</summary>
<br>

- **b12_combined_start.ogg** - Baystation leftover. Has not been used on Paradise in many years, if ever.
- **traitor.ogg** - Baystation leftover. Has ~~never been used on Paradise.~~ been unused since #13635.
- **clouds.s3m** - Baystation leftover. Has never been used on Paradise.
- **main.ogg** - Unused ambience track. Sounds identical to the dozens of other paulstretch ambience tracks that're actually used.
- **song_game.ogg** - Yet another Baystation leftover. I think this was called as asteroid ambience at one point, but that was a long time ago.
- **ambifailure.ogg** - Unused "failure" track. Doesn't really fit SS13's current audio design.
- **ambivapor1.ogg** - A "vaporwave" ambient track that splices together samples from _Floral Shoppe_. Unused, and has no place where it'd be appropriate to play.
- **pretenddemoc.ogg** - Part of what I assume is a novelty announcer that's never called in code and, in the 3 years I've played on Para, I've never seen utilized by admins.
- **shuttlehere.ogg** - Ditto
- **weneedvote.ogg** - Ditto
- **copier.ogg** - A very low quality sound effect for the copier. Unused in Paracode in favor of a much nicer variant.
- **burp_alien.ogg** - Goonstation carryover that's never called in code. Considering humans don't have a burp sound on Paracode, I don't think anyone will be rushing to add this one back to Xenomorphs.
</details>

## Why It's Good For The Game
1. Reducing filesize by culling unused assets which are very unlikely to ever be used is good
2. Several of the songs removed in this PR are copyrighted and/or used without consent; respecting copyright is generally a good thing to do, doubly so when Paradise gains nothing from retaining these files

## Testing
None of these sounds are called by the game, but I loaded into a round in debug mode anyways

## Changelog
No player-facing changes

### CODE REVIEW

**Comment by S34NW** [comment]
Please leave b12 combined start and traitor.ogg

**Comment by Bm0n** [comment]
> 2. Several of the songs removed in this PR are copyrighted and/or used without consent; respecting copyright is generally a good thing to do, doubly so when Paradise gains nothing from retaining these files

What was copyrighted that you removed?

>del: Removed unused audio. No player-facing changes

Also why changelog this if there are no player facing changes

**Comment by FloFluoro** [comment]
> What was copyrighted that you removed?

[Dwarf Fortress - Fortress Mode theme](https://www.youtube.com/watch?v=-6FXeupOp04)
[Dwarf Fortress - Intro](https://youtu.be/jNbTQJUAYT0?t=6)
[Minerva - Zhaytee Absconditus](https://www.youtube.com/watch?v=tDGCJrOO4II)

Dwarf Fortress is copyrighted by Tarn Adams [(as of 2010, at least)](http://www.bay12games.com/dwarves/dev_next.html), and Minerva's soundtrack was distributed under CC-BY, which has not been fulfilled by Paradise as the song has gone uncredited.

**Comment by Bm0n** [comment]
> Minerva's soundtrack was distributed under CC-BY, which has not been fulfilled by Paradise as the song has gone uncredited.

I mean a lot of our sounds are already in violation of a license in one way or another

thunderdome.ogg is CC BY-NC-SA 3.0 (same license as goon actually)

title0.ogg is CC-BY 3.0 

title1.ogg is copyrighted but under some weird custom license/agreement(?). Either way, it's masquerading CC BY-SA 3.0

title2.ogg seems to be copyrighted

oh and ambidet1.ogg/ambidet2.ogg are both also CC-BY 3.0 as it's a cut-down Kevin MacLeod song. Usually, CC-BY 3.0 can have its license changed but I don't think making it shorter is enough of a change to relicense it as CC BY-SA 3.0

Carp deflection sounds(bulletflyby+2 and 3) are also CC-BY 3.0

The sad part is they're actually properly attributed on TG but not on Para. I assume this has something to do with people porting stuff without realising they are other licenses at play

**Comment by AffectedArc07** [comment]
> The sad part is that most of these are actually properly attributed on TG but not on Para. I assume this has something to do with people porting stuff without realising they are other licenses at play

Basically this. Some of the files have the metadata in them, but a lot dont.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
