### PR TITLE
Fixes stray pixels on multiple hardsuits

### PR DESCRIPTION
**Pull request by Tortoise-Dakota**
## What Does This PR Do

This PR deletes some random stray pixels from hardsuits in player's hands.
## Why It's Good For The Game

Removes annoying pixels that show up over top of player models.
## Images of changes

https://i.imgur.com/qNmVMPU.png
https://i.imgur.com/ON9EaP4.png
https://i.imgur.com/2bbukqe.png
## Testing

Tested in game, gets rid of those pesky pixels
## Changelog
:cl:
fix: Fixed in_hand hardsuits, making them no longer have floating pixels
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
Note only a few actually fit wrong, namely the clown, mine, wizard and atmos tech hardsuits. The rest fit perfectly fine
image

**Comment by Tortoise-Dakota** [comment]
> Note only a few actually fit wrong, namely the clown, mine, wizard and atmos tech hardsuits. The rest fit perfectly fine !
Okay, then maybe the issue that Im seeing is specific to certain species? Particularly on vulps, I'll see that the CE's hardsuit will show over top of the tail. Maybe there's something with the layering if that's the case.

**Comment by Bm0n** [comment]
> Okay, then maybe the issue that Im seeing is specific to certain species? Particularly on vulps, I'll see that the CE's hardsuit will show over top of the tail. Maybe there's something with the layering if that's the case.

Huh yeah, I think I see what you mean. Appears to be a layering issue with the tail layer and in-hand layer. 

Going to need to mess with the layers to fix it.

**Comment by Tortoise-Dakota** [comment]
> Huh yeah, I think I see what you mean. Appears to be a layering issue with the tail layer and in-hand layer.
> 
> Going to need to mess with the layers to fix it.

I'll put this on hold for now then, as its not a sprite issue necessarily. I'll look into the layering issue (though im still very new to coding so it's probably best if someone more competent looks at it other than me)

**Review by S34NW — CHANGES_REQUESTED** [review]
Any update on this?

**Comment by hal9000PR** [comment]
No response from author in 3 weeks. Feel free to reopen with changes requested

**Pull request closed without merging**
