### PR TITLE
Tweak: Mr Chang's vending machine now refillable

### PR DESCRIPTION
**Pull request by DrunkDwarf**
Changed the Mr Chang's vending machine to be able to be refiled with a new Chinese vending refill canister crate that can be ordered by Cargo.

:cl:
tweak: Set the Mr Chang's vending machine to be refillable
rscadd: Added a Supply Crate to the Vending section of the Cargo Request Console for Chinese Refill Canisters
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
Need. Game is unplayable without right now

**Comment by DesolateG** [comment]
I don't like Chang's being considered junk food when the damn chef isn't doing their job.

**Comment by taukausanake** [comment]
So instead of cheesing the costume vendors now everyone will cheese Mr. Chang's so they don't have to go to the chef.
But this is needed. It's a vendor and needs stock. We just need a better way of stocking them...

**Comment by fludd12** [comment]
finally I can have unlimited ~~breadsticks~~ MSG

**Pull request merged**
