### PR TITLE
Good heavens look at the time it's SEC REMAP O' CLOCK

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Yes I tried my hand at this messy tumorous shittily designed department.

Main goal: make it less shit, less convoluted, slightly less cramped, remove the areas that were never used and either repurpose them or keep them removed.

behold my iteration:

New Lobby + New processing + evidence storage
 img
Removed the red schlong, removed temp. detainment, replaced with processing (the room with 3 chairs/tables) and put evidence storage underneath, directly connected to Detective's office.
The processing room may look odd, but those chairs are _strategic_ as heck, allowing for literally more flexibility than current processing in a similar space.

Evidence: You no longer will have to, as Detective, trek from your office all the way up to the Observation room to get to Evidence storage, it's now literally right next to your office and right next to processing.

Conference room and Equipment storage rooms remapped:
img
Made an actual, PROPER locker room, added a separate eq. storage area

Courtroom added where that oddball hallway was before for labor camp. Clown office moved down.
img
We never properly had one, and this area was never used. The little glass box is for WITNESSES. NOT the defendant. He's meant to sit on the upper sec side with a lawyer. Glass door on the right has brig access, left is public access.

Shuffled some cell timers around to put more windows in.
img
Literally to make brig escapable from any cell to some extent. If you let someone throw the fucking shoes at all those windows for that long they deserve to escape. Windows are lockdownable, of course.

Removed current Interrogation, Evidence Storage and Observation.
img
Interrogation and Evidence storage were put elsewhere. Observation never used, never will be. Gone.

Re-purposed current processing into an interrogation room with slightly more practical observation, added a door between secondary armory and prisoner lockers (Warden only):
img
There's that button on the wall which turns on the privacy shutters in the windows. I think this is a better interrogation/observation to those tucked-away rooms.

Added a disposal chute to Brig Physician and set it as a cargo destination, made it one tile shorter to make room for new interrogation:
img
This should have been a thing a long time ago, imo.

Full view of most of the changes:
img

Area map for supernerds (a bit outdated regarding objects inside areas, but areas are the same):
img
The icons got updated by yours truly.

also added pink handcuffs hidden in brig and a toy honk mech hidden under clown's office.

Leave your feedback here, though if you complain about the chairs and shit being wrongly turned I won't necessarily prioritize your critique

:cl:FreeStylaLT
add: Added courtroom, left of brig.
tweak: Remapped brig
tweak: Moved prisoner processing and evidence storage to the right of brig, next to Detective's office.
tweak: Changed current processing to Interrogation and a hallway.
tweak: Re-mapped Conference and Locker rooms.
tweak: Lots of other minor tweaks to brig.
tweak: Seriously, way too many small changes to list here, go and have a look at the brig yourself.
del: Removed temp. detainment and observation from brig.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
OH MY GOD IT DIDN'T FIND CONFLICTS
@TheDZD HOLY SHIT PRAISE JAYZUS :pray: :pray:

**Comment by pipextiny1** [comment]
Far too much glass for me. I don't want some shit coming up and getting his meta friend out

**Comment by FalseIncarnate** [comment]
@pipextiny1 first off, if someone attempts to bust a guy out, sec is allowed to arrest them too, just like if someone tries breaking out on their own. second, this actually encourages the warden and sec to pay attention to the prisoners to avoid people doing just that. If sec is too busy shoving batons into clowns to notice someone taking apart their windows, they deserve to have their prisoners escape on them.

as weird as it is to say, the glass encourages gameplay.

**Comment by Dumbdumn5** [comment]
PRAISE

**Comment by pipextiny1** [comment]
If science does got get lockboxs added to sec huds and other items why should sec get windows?

**Comment by tigercat2000** [comment]
the fuck is that logic

**Comment by Magikarpet** [comment]
@pipextiny1 
Security is meant to have intentional vulnerabilities, it should never be designed as an impregnable fortress that nearly no-one can breach. Otherwise, the argument can be raised for chemistry/science/robotics/cargo/engineering having unnecessary glass to allow people to greytide in and do god knows what with the machine. The end result would be muuuch worse as civilians/metalads could easily break into robotics and make themselves mechs, atmos flood, release the engine, or destroy medbay with the chem machines. As FalseIncarnate also said, it forces security to actually watch their prisoners and not leave them to rot in the brig cells for an eternity.

**Comment by theColdflame** [comment]
This generally seems to put practicality ahead of aesthetics. If that's a good or bad thing is subjective.

Aside from that:

I like:
-The courtroom.
-Removal of redundant space in the brig
I dislike:
-Moving processing and removing temp holding. 
-The overuse of windows, as @pipextiny1 said. Cell coridoors and prisoner clothing storage especially. As far as the easier escaping goes, I'm not entirely convinced it'll do much but encourage busting your metabuddies out given how long it takes to get through an rwindow without tools.

I'm also not entirely sure _why_ sec needs a remap. It's pretty functional as it stands, and this remap doesn't do much to significantly shake it up. 

I'm fairly neutral on this, so I won't pass an overall opinion.

**Comment by IcyV** [comment]
I don't think the courtroom is really all that necessary to have given the holodeck is where that should be done, if I'm not mistaken. Also not entirely sure what you were going for with the processing room. Three individual tables with a single chair? I assume its for cuffing prisoners in and officers can just stand nearby.

Other than that I do honestly like it quite a bit.

**Comment by FreeStylaLT** [comment]
@IcyV Holodeck's one is crap, it's hardly practical and you have to drag the defendant, who is usually a capital crime suspect, all the way out into dorms. No wonder it was never used. I find this to be a better alternative. Also, if it turns out to be unused, then I will have changed an unused hallway into an unused courtroom. Not exactly a big loss.

**Comment by IcyV** [comment]
@FreeStylaLT Fair point on the courtroom. Personally I'd go with making the holodeck courtroom not awful instead of placing in a large permanent one in Sec, but whichever way.

No real issues with the processing, just making sure that is what it was intended for. Hard to make rooms like that look good with limited space.

**Comment by Cobradude** [comment]
Sec doesn't need a nerf. Sec doesn't need a buff. This brig looks pretty ugly, I like the current one.

**Comment by Konater** [comment]
That back line of chairs in the courtroom could be moved to where the intercom is and the room made shorter to take the view range into consideration

**Comment by Krausus** [comment]
firefox_2016-07-01_15-48-18
... how long has security had to open/move a locker to get access to deliveries? Looks like you could move these two lockers to where the chairs above them are (which appear to be leftovers from moving the spawns). You'd still be missing lockers, though - you went from 8 security officer lockers to 5.

> windows

I realize the windows are supposed to make it more convenient to break into/out of the cells, but... isn't it kinda weird that there are a bunch of windows for anyone to come look at the prisoners? Makes it look more like a zoo than a brig.

**Comment by theColdflame** [comment]
@Krausus since forever, the delivery hatch has been obstructed for a long time

fixing that issue in a remap might be smart, though

**Comment by FreeStylaLT** [comment]
@Krausus
oh woopsy daisy, there's the conflict from my copy pasterino, also fixing courtroom FOV problem.
THIS was meant to be the new locker room:
img

**Comment by monster860** [comment]
@FreeStylaLT You can install the bay mapmerge driver if you get merge conflicts a lot.

**Comment by FreeStylaLT** [comment]
OP Updated with correct pictures of new locker room (current conf. room)

**Comment by KingPhilipIII** [comment]
My biggest issue is probably where you put evidence storage. Since cultist writings and traitor gear tends to wind up there, it would be ridiculously easy to thermite the wall and steal it for most people, since it is placed in a room on the exterior of the brig. Otherwise, I have no current complaints.

**Comment by TullyBurnalot** [comment]
Quite honestly, I would rather see Processing lose the power it has now. Security relies too much on it, to the detriment of (ironically enough) expedient prisoner processing. I would much rather it be a secondary thing kept out of the way to encourage speedy brigging.

Secondly, aesthetics should take a backseat to practicality, which is the whole point here. Looking ugly is irrelevant if it ends up working out better.

Thirdly, as much as I believe a prison should not be deliberately constructed with loopholes, this is still a game. We have a Warden for a reason, as well. We even gave them Krav Maga gloves.

Finally, I approve of this general design, especially the courtroom. No one used that empty hallway anyway, so may as well have a dedicated area that looks nice AND is useful for something besides vending machines.

**Comment by Vivalas** [comment]
I like all of this except the extra windows. It is extremely easy for people to break in and break people out, when it is not locked down. The Brig is supposed to be secure, and sometimes security is too busy to keep an eye on prisoners 24/7, and with a setup like that somebody with insulated gloves could bust someone out in under 20 seconds. Maybe even 10. You're just deconstructing two windows. If you wanna make escape easier remove the doors leading into the cell halls, which would have the added effect of making it easier for released prisoners to be let out

**Comment by FreeStylaLT** [comment]
Those are not window-windows, but rather spawners of those 4-separate-windows with grille inside window boxes. It's just how they appear in the mapmaker.  The actual amount of windows to be broken is 4 to bust someone out or bust out through the bottom

**Comment by Vivalas** [comment]
Yes, but it is still super easy to quickly deconstruct those while using hotkeys and a toolbelt. I'm not at all concerned about people breaking out with this setup, as you said, they deserve it if they go unnoticed for that long, but to break IN is stupid easy with the right gear. And stocked toolbelts + insulated gloves are not hard to come by. I think I might post a video illustrating my point, I could easily break someone out of this setup in 20 seconds, from any cell (maybe a bit longer in the rear cell due to walking time). You're not punishing security forgetting about prisoners, you're punishing security not standing constant vigil over all cells. Which is neither fun nor practical.

**Comment by FreeStylaLT** [comment]
Also interesting proposal regarding removing cell block doors, will see about it when I wake up tomorrow

**Comment by Da-Dman234** [comment]
Time to go full nerd here!

http://prntscr.com/bnsn9v
I don't know how to make it all fancy and have my pictures immediately show up, but anyways. I dunno if DreamMaker is just being a dick and not showing it, but it looks like you missed some wire connections. Also, I may have missed it but the lobby doesn't seem to have a lightswitch.

Conference room doesn't have an air alarm. Equipment storage is just a square lined with stuff, while this isn't really a huge deal, if you would like the mess around with the way you arrange the lockers I certainly think you could make some improvements. Also, the table in the top left is awkward behind the vending machine and second table (I know I'm being literally hitler when it comes to details, but someone has to do it, feel free to ignore whatever), also you should totally put something on those racks near the door if you're going to have them.

This isn't a huge deal either, but evidence being one tile bigger so it's easier for officers to move prisoners around would be nice as well.

Also, if it's not too much of a problem could you upload a picture of the zoning too?

_*also, I love you for putting fuzzy cuffs in_

**Comment by Kyep** [comment]
There are many things I like here, including:
- Removing temp detainment
- Having evidence connected to the Det's office
- Swapping briefing and equipment rooms, giving equipment room more space
- Adding courtroom
- New interrogation room with better observation sideroom
- Tempbrig cells being more escapable. I do think it will bring more excitement to the game, and offer an incentive to grant parole. I do think it will need to be watched carefully though. I can see this going very wrong on greytide-heavy rounds.

My only suggestions are:
- Making sure that the MULE delivery point in the equipment room is not blocked by a locker.
- Making sure that the NE corner of the equipment room does not have 3 lockers together. Maybe move one to where one of the empty racks is currently placed.
- Consider changing the disposals system so cargo can send mail to brig medical.

Overall, a great set of changes.
Way better than what I was thinking of doing.
Fully support.

**Comment by FreeStylaLT** [comment]
hey the eagleeyed nerds have come out of the woodwork, yay, my own testing didn't help me find some of those things

@Kyep MULE point was fixed, check OP, NE corner will be fixed somehow, I'll see about reshuffling stuff in the room. 
Disposals - oh god I have no clue how those destinations work, I don't know if I'd be able to add one more.

@Da-Dman234 Wire in lobby will get fixed, conf room and locker room are currently working off of a single air alarm and APC, I just sort of kept that to retain consistency. New equipment room will be reshuffled as said, tables included.

**Comment by Da-Dman234** [comment]
I'll try to nerd harder tomorrow :p 

One other question... _for now._

http://prntscr.com/bnsz0p
Why are those 3 APCs so close? I'm under the impression that's all covered under 1 area code (If it's not it probably should be), so it seems unnecessary and a little confusing.

**Comment by FreeStylaLT** [comment]
oh those.. are actually 3 separate areas

**Comment by Da-Dman234** [comment]
Well, I guess if you went through the effort of doing it it's not like it's a bad thing. I was just a bit confused, in that case you're gonna wanna throw an air alarm in evidence storage.

**Comment by FreeStylaLT** [comment]
@Da-Dman234 @Kyep OP updated with changes to new locker room, fixed light switch in lobby, wiring in lobby, gave NerDman his area map

**Comment by Fruerlund** [comment]
Processing room is too small. Either it needs to be made larger using the space between the interogation and firing range or.

There needs to be a holding cell close by.

**Comment by Da-Dman234** [comment]
Dunno if it's intentional, but with the way you zoned the prison lockers (Which still needs its' own air alarm), the fire alarm in the hallway won't proc the firedoors for the room. 
With the courtroom, you need to pull two fire alarms to secure the whole room (Though I'm again being nitpicky, since the doors fall automatically). I would personally make that into a singular zone that's a part of sec.

Also, the lockers in equipment are blocking the mule entrance (Not that it's ever used) I like what you did with it though.
http://prntscr.com/bntvfa

In my opinion I think you should replace one of the warden's doors with a desk and table like it was. Maybe you'd consider axing the door in the HoS' hallway and putting it there? That seems a little awkward though. I'm really quite tired though so maybe I'll look at it again in the morning and think differently

**Comment by FreeStylaLT** [comment]
THAT FUCKING MULE BOT POINT I SWEAR TO CHRIST ALMIGHTY

**Comment by Kyep** [comment]
@FreeStylaLT 
From memory:
- Add your destination LAST IN THE LIST on https://github.com/ParadiseSS13/Paradise/blob/ad364232d2ff92606ee22e70733054208179bd19/code/_globalvars/lists/flavor_misc.dm
- Add a new filtering disposal tube in the right place in the disposals circuit, with the branching off pipe going to the disposals unit in brigbay. There is a special number var on these filtering disposal pipes that determines which entry in that list they divert mail for - you should be able to find it by looking up some in the map editor and seeing which var they have is custom and matches their position in that list.

**Comment by FreeStylaLT** [comment]
img
LOOK

LOOK AT THAT

WHAT THE FUCK

**Comment by FreeStylaLT** [comment]
Updated OP with relevant pics. Tweaked the conference room -again-. Fixed disposal chaos under the floor in new locker room, added brig physician to disposal delivery list, added a disposal there. What's left is discussing evidence room and windows, maybe processing, perhaps they are too small/exposed? Should I add ID locks to the evidence room lockers? Add a second layer of reinforced wall to evidence storage? Make processing bigger? (Only slightly, I am constricted to the current lobby/det's office, which I'd rather not quite change yet)

**Comment by KingPhilipIII** [comment]
Okay, I'm glad my concerns about evidence storage did not just fall between the cracks. Not really certain how to go about fixing it, but ID locks might be more efficient as thermiting two walls is about as difficult as one.

**Comment by KingPhilipIII** [comment]
Perhaps I am overestimating the availablility of thermite, or other wall destroying agents, but my point still stands.

**Comment by FreeStylaLT** [comment]
@KingPhilipIII Here are the possible options for evidence storage I've come up with:

-  img
Double reinforced walls, though looks like ass to me, and wouldn't do much good against thermite anyway.
-  img
Lockers with identical access as interrogation (basic brig access)
-  img
make that shit roomier with more lockers + ID lockers from earlier.
- change nothing, keep as is.

I'd like more input than just from one guy, I'm not sure if others view evidence storage here compromised to the extent that it'd require additional security measures. @kyep @theColdflame @Da-Dman234 @Vivalas @TullyBurnalot opinions pls. 

Regarding brig cell windows, seems like a lot of you are skeptical about them, whereas some of you think brig is meant to have SOME weakness. Perhaps windows aren't the best way to go about it, so I will most likely revert the windows back to walls.

**Comment by theColdflame** [comment]
As far as evidence storage goes, I think that an r-wall is secure enough. Literally thermiting a wall IN the brig lobby is ballsy enough that it should probably be rewarded. 

As far as the brig cell windows go- A button similar to the medbay doors being present in the cell and main coridoors  that lets the brig be exited from the inside is what I'd suggest- this also removes the problem of prisoners not being let out after their timer's up.

I still think removing temp detainment might not be smart- it's not common than it's needed, but it is still needed from time to time.

**Comment by KingPhilipIII** [comment]
The reason I feel it's so compromised is before it had two guardians. The Warden, you'd have to get past him, and the vacuum of space. That's if you choose to circumvent the Warden. It didn't really need much more protection than that. People broke in and looted the room occasionally, but that wasn't frequent. 

Honestly, locks on the lockers should suffice. It keeps confiscated weapons, gear, magical artifacts and other stuff out of reach for the general populace, but if a traitor has the nerve to go for it, can just Emag the lockers open for the treasure within.

**Comment by Vivalas** [comment]
The medbay button thing is NOT a good idea for security. I really hope that we haven't strayed so close to LRP that you can't be assed to wait 30 seconds or so for an officer to let you out or for the AI to. The brig is a jail, guards discharge the prisoners from jail. I don't wanna salt this thread up but adding an auto-exit button makes it way too easy for people to yakety sax out, and continues this dangerous hugbox-creep trend the server has been on. Everything is NOT supposed to be easy.

As for evidence storage, it will never be fully secure in a location like that, so sec will have to store tator items elsewhere. Not a huge problem, but probably not the best place to leave an emag and a cham projector lying around.

As for the cell hall windows, I am firmly against those. Not only is it very easy to break out, as I mentioned earlier, if the greytide hits with that setup, believe me it will hit HARD. Everything else is cool though. Map changes always have a lot of friction because people get used to the current layout of things and get attached to it. Everything new always looks 'wierd', give it some time and everyone will get used to this new layout.

**Comment by Da-Dman234** [comment]
Evidence storage should probably remain the size it is (Since I don't like the idea of it eating into the hallway), and I don't see a problem with locking the lockers though. It'd help stop sci powercreep, since you'd need more than thermite to just get the goods, indirectly evening out the playing field for science vampires/lings.

**Comment by Belario** [comment]
Finally a sec re-map that's aesthetically pleasing/not horrifically blocky!

Only thing that stands out to me is the disposal outlet in the brigbay, maybe put it to the immediate right of the sleeper? It's currently position is a bit ugly being right above a bed and all

Otherwise :+1: 

I appreciate the concern people have about the abundance of r-windows, but it can't help to try out having them, might have a positive impact and we can always just replace them if it goes terribly wrong.

**Comment by FreeStylaLT** [comment]
OP updated with newest additions (new-new evidence storage, processing made wider), also added an updated area pic. As far as I am concerned, this is pretty much finalized barring those fucking random misplaced area tiles that keep popping up. I'll test it more when I wake up, but its pretty much done, as far as I am concerned, @TheDZD @Fox-McCloud

**Comment by Fruerlund** [comment]
I'm not seeing the wider processing room. Maybe I'm just dummy but (Y)

One last thing I'd like to suggest. Consider changing some of the glass in the courtroom to standard walls I'm thinking about a lot of the glass below the firing range. Additionally if the courtroom could be moved one tile left I'd be possible to pass around those 3 judgy chairs.

**Comment by Fox-McCloud** [comment]
The little cut in to sec lobby is incredibly odd.

I still content sec doesn't need a spare advanced medkit for themselves.

The warden should probably have the desk+windoors back to the sec briefing room, or something similar. I see that used a *lot* by sec players for handing out weapons (yes I realize there's one already there, on the opposite side, but it's in an awkward location).

**Comment by FreeStylaLT** [comment]
@Fox-McCloud Medkit is outdated and gone, my bad on not keeping OP properly fresh. (it is a lot of pics to update okay ;w;)

Lobby turned into this: img

Warden returned to being a secondary receptionist with all the tables.

OP updated with correct pics, like as many as I think were warranted.

**Comment by Vivalas** [comment]
@Belario The controversy over the cell hall windows is not for the concern of people breaking out, but people breaking in.

**Comment by Plotron** [comment]
Courtroom is amazing, I like the new interro, but I dislike the swapped conference/equipment rooms due to warden access.

I don't think there should be windows between the docking sleeve/corridor and the courtroom.

I'm glad you surgically cut out the tumors. Interrogation observation room was made for corpses, not people.

I believe it'd be better to adjust/trim the firing range rather than Brig Medbay, considering that it becomes rather congested during emergencies. The firing range is too big for what it's worth, seriously.

I love the idea of moving the evidence storage. It's a very welcome change, but I have to agree with others that it's in a rather unfortunate spot, making it prone to break-ins.

**Comment by Belario** [comment]
@Vivalas Yeah, it'd probably be a bit too easy for someone with a toolbelt/fireaxe to tide their way in, it is right across from the law office and well without hearing range for half the brig though.

Something like that is what the warden is for as well, it's why he's a masta of fightan magik.
And there's always portable flashers/barriers.

**Comment by FreeStylaLT** [comment]
oh god why did you reference this precious PR in that mess tully you desecrated a holy site

**Comment by FreeStylaLT** [comment]
WAIT NO SHIT AREAS OVERLAPPING HOLD ON A MINUTE NEEDS FIXES

**Comment by FreeStylaLT** [comment]
Bugs fixed, OP updated with new pics.

Added pepper spray refiller to physician's office, as he would have no access to it if #4888 goes through:
img

@Plotron Tweaked courtroom to remove sleeve windows and that airlock leading to labor shuttle sleeve.
img

**Comment by Belario** [comment]
Whoop whoop.

All we need now is a prettier execution chamber :+1:

**Comment by FreeStylaLT** [comment]
I mean.. wh-- why. It's not exactly a lobby.

**Comment by FreeStylaLT** [comment]
@Belario 
img
can't say I don't deliver though

**Comment by Fruerlund** [comment]
Good work Freestyla!

Also please merge new executionchamber

**Comment by monster860** [comment]
What if someone explodes the execution chamber?

**Comment by FreeStylaLT** [comment]
@monster860 
Protective measures were taken
img

**Comment by Belario** [comment]
@FreeStylaLT :+1: :100:  for that rolling pin.

Pls quick patch

**Comment by FreeStylaLT** [comment]
(the two latest pics do not reflect what is in the actual PR)

**Comment by SpaceTimeNow** [comment]
I already explained my reasoning here https://github.com/ParadiseSS13/Paradise/pull/4747 ,so i will keep it short: I still think that the 2x3 cells are shite. 

--

Also i think that the Brigbay layout just feels odd, it is way to cramped. You can't even store a box you got from cargo because it will always be in the way. 

It seems to have a unproportional amount of beds: 1 roller bed, 1 sleeper, 4 normal beds. Brigbay is just a temporary stop, either you can be fixed there and go back into the cell or you go to the medbay. I would remove the beds entirely and add a few roller beds which you can fold together if you don't need them. 

Aditionally since you mostly deal with prisoners you need more options to organise stuff but also keep it secure. Curently everything ends up piled in the one secure locker. I would like it to either have a small backroom for storage (seperated by a airlock) or have the tables on a side wall and like 2 cabinets on top of them (like in the small medbay room next to the reception). 

--

You kinda removed the one room are that could actually be used to process suspects / prisoners (the room left of the warden). I think we need that back, if not two of those. So you don't have to process multiple people in one room anymore.

**Comment by FreeStylaLT** [comment]
Brig physician was not a priority for me. He can receive a separate map update in the future.I am open to suggestions, but given #4888 I would rather not risk it right now, as any changes would likely conflict, I shrunk the thing, added a refiller, and would rather leave it at that until either this one gets merged or #4888 does. Afterwards, absolutely am willing to make it less lame.

As for processing, it was put on the right of lobby. It was supplied with more than just two chairs and has the evidence storage right next to it.

**Comment by SpaceTimeNow** [comment]
I don't think any of the three options for processing are of any practical use. You probably can't get it right with such a small area, especially if it needs to share the space with evidence storage.

I think we need at least two chairs on the opposite of a table and like two empty tables near it to store shit on and some space for people to stand and navigate around it. Also i would very much prefere to have two seperate rooms so you don't have like 8 people in one room argueing about two different cases. The previous processing was pretty much pefect, execpt for the fact that it was also a hallway. Two of the previous processing rooms seperated by a solid wall would be the dream.

**Comment by Vivalas** [comment]
Ugh I love the rest of the PR but those windows are a TERRIBLE terrible idea. The warden can't react to someone breaking their friend out in no time at all. I suppose it can always be reverted but no sane person drinks poison even if they have the antidote with them.

**Comment by FreeStylaLT** [comment]
They do for science

**Comment by Robotonic** [comment]
As much as I like the idea of testing the windows one issue will probably crop up fairly quick - the Warden being in Processing and not hearing the left cell block window being broken because they're so far away.

Other than that, my only particular issue is that if someone got thrown in Processing and the officer didn't tell the Warden, the Warden may not even know. It's also possible that the Warden is also too busy to patrol which means it'd suck for the prisoner if they had no headset. And also I kinda like prisoners in Processing being able to just tell me things such as how Officer McBaton beat the shit out of them, or complaints or something whilst quickly putting an EotC to arrest on the records, but still being in my office so I can sort of watch the Armoury.

I actually forgot just a couple more things: If at all possible Processing may want a 'random shit table', for the fuckin' hats people leave around and lastly maybe have Processing's south wall be reinforced, so if you break it down you atleast have to do the west wall in the Brig lobby? Not sure if we should even bother with that one.

...Eck, damn it. <i>Actual</i> last thing is the conference room only has enough for officers and a HoS but no-one else if you genuinely did wanna use it... this comment was ment to be short, oops.

**Comment by FreeStylaLT** [comment]
Naw it's fine. I'm re-re-re-re-re-_re_-mapping the fucking conference/locker room combo. 

yes I counted. Those two rooms are my nemesis at this point. 

As for processing, I cannot get it closer to Warden without remapping like all of brig


all of it

and I don't want to do that just quite yet

**Comment by FreeStylaLT** [comment]
OP updated with a new Conference/Locker room combo, I swapped them back to their original positions, changed shit around.

img

**Comment by Robotonic** [comment]
I think that works pretty well, and as the new Brig gets some active playtime I'm sure anything that goes weird can be tweaked. I like the look of the Brig too.

By the way it might just be some pod-related thing that uses the same sprite but is that a pin-pointer on the sec escape pod door?

**Comment by FreeStylaLT** [comment]
that's some dreammaker hocus pocus regarding escape pods

**Comment by Fox-McCloud** [comment]
@Robotonic 

Shuttle docking ports utilize the pinpointer sprite. You can normally never see them in game, as a player.

**Comment by FreeStylaLT** [comment]
Fixed bugs relating to piping, access, missing lights. Tweaked most of the wall-items to be in better spots. Made floor patterns consistent. Added some more fluff. OP updated with new pics, but I doubt you'll notice any real differences. As done as it can be at this point, extensively tested, everything SHOULD work.

**Comment by FreeStylaLT** [comment]
THERE IS NOTHING LEFT TO FIND THAT IS OUT OF ORDER, I SWEAR. I SWEAR ON MY COPTER HAT. I AM SURE OF IT. AAAAAAAAAAAAAA.

**Comment by Da-Dman234** [comment]
Did you manually reset all the camera names so they are accurate to the area they're in? Common mistake is to just re-use cameras and assume they automatically reflect the zone they're in

**Comment by FreeStylaLT** [comment]
All cameras, both on the live server at the moment and in this PR do not have any set names, they are all just "security camera", they do not get a custom name set depending on the area they're in, if that is what you meant.

**Comment by FreeStylaLT** [comment]
oh my jesus christ I hooked up my entire brig to a single wing of solars.. another commit coming up

**Comment by Kyep** [comment]
@FreeStylaLT check the 'c_tag' variable on your cameras. Verify they show up correctly in the list when playing as AI.

**Comment by FreeStylaLT** [comment]
OF COURSE SOMEONE HAD TO FIND MORE SHIT FOR ME TO TEST

**Comment by Fox-McCloud** [comment]
Is this ready? Have you checked for every unique area to have a light, proper camera tag, etc?

**Comment by FreeStylaLT** [comment]
if this ISN'T ready then I can just be fricking lynched since I couldn't fix everything in 11 fucking commits

**Comment by FreeStylaLT** [comment]
you know next time I make a big map PR I'll just

not PR it until everything works

cus fucking hell

**Comment by Fruerlund** [comment]
Don't worry about it. The PR is only 13 days old!

**Comment by monster860** [comment]
@FreeStylaLT Make sure you didn't break disposals. Here's what I mean:

The T-shaped disposal pipes, the non-straight direction should lead to exactly *ONE* destination. If it leads to another T-shaped disposal pipe, you dun fucked up something.

**Comment by monster860** [comment]
@FreeStylaLT 
:eyes:

**Comment by FreeStylaLT** [comment]
OP hasn't been updated properly, that thing's been long fixed

**Pull request merged**
