### PR TITLE
Fluffpocalypse 🎉

### PR DESCRIPTION
**Pull request by FlattestGuitar**
This moves around all the fluff items I could move around into the right .dmi file. There's no pretty way to move the mob icons into the right files without changing bits about the human icon updates, so I'll leave that alone for now.

Also, new floofs:

```
/obj/item/device/fluff/rapid_wheelchair_kit
item: Vox wheelchair
what it does: It's a swanky Vox wheelchair.
ckey: Rapidvalj
character: Hakikarahiti
```

```
/obj/item/clothing/suit/hooded/fluff/bone
item: Skeleton suit
what it does: It's a spooky suit. Comes with a hoodie. Doesn't work well on skeletons.
ckey: Doru7
character: Jack Bone
```

```
/obj/item/clothing/under/fluff/jay_turtleneck
item: Mar's Pattern Custom Turtleneck
what it does: It's a swanky turtleneck.
ckey: Jayfeather
character: Jay Wingler
```

```
/obj/item/clothing/glasses/monocle/fluff/trubus
item: Gold Thermal Eyepatch
what it does: It's a swanky eyepatch. Does nothing.
ckey: Trubus
character: Wolf O'Shaw
```

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@FreeStylaLT For the fluff items

**Comment by Rapidvalj** [comment]
THE MADMAN ACTUALLY DID IT, A TURTLENECK WITH VOX BLOOD

**Comment by DesolateG** [comment]
That's a pimpin wheelchair

**Comment by FreeStylaLT** [comment]
:ok_hand: x 3

**Comment by taukausanake** [comment]
That Gold Thermal Eyepatch, we had something like that before didn't we? I forget if it was a fluff or not but I know I've seen a round monocle and it had code similar to thermals

**Comment by DesolateG** [comment]
You're thinking of lens of truth. It's basically reskinned mesons

**Comment by FreeStylaLT** [comment]
:ok_hand: x 3 + 1

**Comment by Allfd** [comment]
Added to the DB @FlattestGuitar

**Comment by KasparoVy** [comment]
That wheelchair is actually pimped out hardcore, these sprites are dope. Good work yall

**Pull request merged**
