### PR TITLE
Removes Wryn

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Not really a feature removal since this unused, but it's the closest thing we have.

Removes Wryn, their references, and associated codes.

The sprites for these guys are terrible and their basis as a species just doesn't fly on paradise anymore; a space resistant race that has a hivemind for a language and informs every single other player who's playing Wryn that they've died---they're also yet *another* race that would require copious amounts of sprites just for clothes and other equipped items to work. They were added *years* ago on a whim and have never been utilized; they just collect dust, and, quite frankly, don't have a good fit here; moths are better than this, IMO (don't count that as an endorsement).

A more nuanced race, like Ethereals, is a much better fit; they have their own unique mechanics, behaviors, and nuances, without delving into the territory of "super overpowered" while still remaining distinctly unique.

:cl: Fox McCloud
del: removes Wryn and associated code
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Wasn't marginalorb revamping wyrns? It might be best to talk with them first before doing this. They might be able to redeem the race, perhaps.

**Comment by thatdanguy23** [comment]
if we can wait several years for a supermatter port, we can wait for wryn to be finished. just leave it alone.

**Comment by Marginalorb** [comment]
> Wasn't marginalorb revamping wyrns? It might be best to talk with them first before doing this. They might be able to redeem the race, perhaps.

I'm literally waiting on sprites from Drake for the next PR I was going to put up here, and I was never consulted before this PR got put up. I would've appreciated at least a quick "hey Marg still working on wryn?" before you decided to put this up

**Comment by Varghh** [comment]
Fox you're the first one to jump about "Don't remove, improve". Maybe this is the only scenario I feel you should follow that.

**Comment by Dumbdumn5** [comment]
> I'm literally waiting on sprites from Drake for the next PR I was going to put up here, and I was never consulted before this PR got put up. I would've appreciated at least a quick "hey Marg still working on wryn?" before you decided to put this up

Objecting due to this, let the nerd improve em, eh? :-1:

**Comment by MRgaty** [comment]
I think Marg deserves a chance to make Wryms playable, at least they are the only one crazy enough to try it.
Got some confidence on them.

**Comment by Fox-McCloud** [comment]
I'll close this, for now, but I get distinct hostile vibes from some of the comments. 

All I can say is, if you engage in a major project without really informing maintainers, then they move to change/alter it in the mean time, before you work on it youreslf, jumping to the conclusion they did it on purpose, to spite you, or for other <insert nefarious reason here> is not great--it's more likely they didn't notice.

This is why if you're going to engage in a project, it's best to actually discuss it with the people most deeply involved in the approval and design process first.

**Pull request closed without merging**
