### PR TITLE
Deluxe soap for ERT

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

ERT janitor belt now starts with the deluxe soap (4 seconds cleaning time).
## Why It's Good For The Game

ERT Janitors are the special forces of cleaning, they should get the best soap NT has available.

## Testing

- Spawned a janitor ERT to look at their soaps.
## Changelog
:cl:
tweak: ERT janitor belt now starts with the deluxe soap (4 seconds cleaning time)
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
Im still not exactlty for making janiborgs MORE effective than normal janitors than they already are, they all still currently invalidate the existance of organic janitors by simply one janiborg being on station.

The ERT though is fine to have better stuff, their supposed to be better

**Comment by Henri215** [comment]
> Im still not exactlty for making janiborgs MORE effective than normal janitors than they already are, they all still currently invalidate the existance of organic janitors by simply one janiborg being on station.
> 
> The ERT though is fine to have better stuff, their supposed to be better

I do think they could receive this slight better version of the soap mostly because they dont have space cleaners, until janiborgs get the floor buffer upgrade they are left with only the basic soap if  in a situation where wetting the floor should be avoided.

**Comment by Carthusia** [comment]
Their sprayer was removed? 

If the sprayer is gone, then this is fine

**Comment by WalmartianCheese** [comment]
> > Im still not exactlty for making janiborgs MORE effective than normal janitors than they already are, they all still currently invalidate the existance of organic janitors by simply one janiborg being on station.
> > The ERT though is fine to have better stuff, their supposed to be better
> 
> I do think they could receive this slight better version of the soap mostly because they dont have space cleaners, until janiborgs get the floor buffer upgrade they are left with only the basic soap if in a situation where wetting the floor should be avoided.

they can stand on tiles and instantly clean them without soaping them up though and it needs no upgrades

**Comment by Coolrune206** [comment]
> > > Im still not exactlty for making janiborgs MORE effective than normal janitors than they already are, they all still currently invalidate the existance of organic janitors by simply one janiborg being on station.
> > > The ERT though is fine to have better stuff, their supposed to be better
> > 
> > 
> > I do think they could receive this slight better version of the soap mostly because they dont have space cleaners, until janiborgs get the floor buffer upgrade they are left with only the basic soap if in a situation where wetting the floor should be avoided.
> 
> they can stand on tiles and instantly clean them without soaping them up though and it needs no upgrades

https://github.com/ParadiseSS13/Paradise/pull/20133 removed the aforementioned functionality until the Borg is upgraded

**Comment by DoctorDrugs** [comment]
so from the design team there's two of us who don't like the idea of Janiborgs getting deluxe soap, ERT is fine to get the soap. If the Janiborg is in a position where cleaning with water is dangerous then there's probably a good chance they can get upgrades for better/easier cleaning at that time or within a reasonable amount of time. The old soap should hold them over till that time applies if it's a short amount of time

**Comment by Henri215** [comment]
> so from the design team there's two of us who don't like the idea of Janiborgs getting deluxe soap, ERT is fine to get the soap. If the Janiborg is in a position where cleaning with water is dangerous then there's probably a good chance they can get upgrades for better/easier cleaning at that time or within a reasonable amount of time. The old soap should hold them over till that time applies if it's a short amount of time

I agree with that reasoning and the change was reverted.

**Review by farie82 — APPROVED** [review]

**Pull request merged**
