### PR TITLE
Giving Pancuronium a recipe, now from different branch

### PR DESCRIPTION
**Pull request by Lime-7**
## What Does This PR Do
Added recipe of pancuronium in code/modules/reagents/chemistry/reagents/toxins.dm

recipe for pancuronium is - cyanide, bromine and capulettium, proportions are 1:1:1 

## Why It's Good For The Game
pancuronium is a very interesting reagent with unique properties what could be used in very different interesting ways, but getting normal amount of it is pain in the ass, so I made recipe to it, so it's easier to get it

## Testing
NO, but I hope it works _breathes even more than before copium_, hope this THIS time nothing going to go wrong...

Edit: tested it, works perfectly

## Changelog
:cl:
add: Recipe for pancuronium
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Looks good this time 🙌

**Comment by CinnamonSnowball** [comment]
> Testing
NO, but I hope it works *breathes even more then before copium*, hope this THIS time nothing going to go wrong...

Is there any particular reason you've decided not to test your changes? We require PRs to be tested for a reason, just saying "no" without even saying why isn't a great excuse and frankly comes off as a bit disdainful to the process that ultimately just tries to keep the game as stable as possible for the players.

**Comment by Lime-7** [comment]
> Is there any particular reason you've decided not to test your changes? We require PRs to be tested for a reason, just saying "no" without even saying why isn't a great excuse and frankly comes off as a bit disdainful to the process that ultimately just tries to keep the game as stable as possible for the players.

Because I didn't have an ability to check it when I did this PR, I'll try to check it soon

**Comment by Lime-7** [comment]
Tested - worked

**Comment by Fordoxia** [comment]
If you have capulattum, why make pancuronium?

**Comment by Lime-7** [comment]
> If you have capulattum, why make pancuronium? IMHO this recipe for pancuronium is too demanding for that reason. Especially since nanomed vendors have it..

A) As I understand it, pancuronium has no taste, so if you poison food or drink, the victim will not understand that he ate/drunk something wrong

B) pancuronium has lower metabolization rate, so it will last longer

C) with pancuronium you can speak with your victim, what might be useful for RP purposes

D) pancuronium has no symptoms before paralyzing you

E) recipe what I made is not absolute and can be changed, if you have any suggestions I will love to hear them

**Comment by Adrer** [comment]
Minor request: Please also include the recipe in the PR description. Just makes it easier to get a feel for what is being added in the PR without needing to look at the code.

**Comment by Lime-7** [comment]
> t easier to get a feel for what is being added

yep no problem

**Comment by Fordoxia** [comment]
> > If you have capulattum, why make pancuronium? IMHO this recipe for pancuronium is too demanding for that reason. Especially since nanomed vendors have it..
> 
> A) As I understand it, pancuronium has no taste, so if you poison food or drink, the victim will not understand that he ate/drunk something wrong
> 
> B) pancuronium has lower metabolization rate, so it will last longer
> 
> C) with pancuronium you can speak with your victim, what might be useful for RP purposes
> 
> D) pancuronium has no symptoms before paralyzing you
> 
> E) recipe what I made is not absolute and can be changed, if you have any suggestions I will love to hear them

A/D - You can drool as a symptom.

B - Pancuronium has twice the metabolic rate of sulfonal (0.2 Vs. 0.1)

C - Why should it be harder to make because you can RP with it?

E - Bromine should be an ingredient. The chemical's full name is "Pancuronium Bromide" (also stated in the code) and none of the current ingredients contain bromide.

**Comment by Lime-7** [comment]
> > > If you have capulattum, why make pancuronium? IMHO this recipe for pancuronium is too demanding for that reason. Especially since nanomed vendors have it..
> > 
> > 
> > A) As I understand it, pancuronium has no taste, so if you poison food or drink, the victim will not understand that he ate/drunk something wrong
> > B) pancuronium has lower metabolization rate, so it will last longer
> > C) with pancuronium you can speak with your victim, what might be useful for RP purposes
> > D) pancuronium has no symptoms before paralyzing you
> > E) recipe what I made is not absolute and can be changed, if you have any suggestions I will love to hear them
> 
> A/D - You can drool as a symptom.
> 
> B - Pancuronium has twice the metabolic rate of sulfonal (0.2 Vs. 0.1). Additionally you can just make a larger batch of capulettium since you're already making it.
> 
> C - Why should it be harder to make because you can RP with it? If anything that's a reason to make it easier.
> 
> E - Bromine should be an ingredient. The chemical's full name is "Pancuronium Bromide" (also stated in the code) and none of the current ingredients contain bromine.

A/D didn't see it…
B/C - OK, it makes sense.
E -  yea ok, I will replace sulfonal with Bromine, it should make recipe easier and more logical.

**Comment by Lime-7** [comment]
> ## What Does This PR Do
> Added recipe of pancuronium in code/modules/reagents/chemistry/reagents/toxins.dm
> 
> recipe for pancuronium is - cyanide, sulfonal and capulettium, proportions are 1:1:1
> 
> ## Why It's Good For The Game
> pancuronium is a very interesting reagent with unique properties what could be used in very different interesting ways, but getting normal amount of it is pain in the ass, so I made recipe to it, so it's easier to get it
> 
> ## Testing
> NO, but I hope it works _breathes even more then before copium_, hope this THIS time nothing going to go wrong...
> 
> Edit: tested it, works perfectly
> 
> ## Changelog
> 🆑 add: Recipe for pancuronium /:cl:

**Comment by Lime-7** [comment]
oops....

**Comment by Fordoxia** [comment]
> A/D didn't see it…

`/datum/reagent/pancuronium/on_mob_life(mob/living/M)
	var/update_flags = STATUS_UPDATE_NONE
	switch(current_cycle)
		if(1 to 5)
			if(prob(10))
				M.emote(pick("drool", "tremble"))
		if(6 to 10)
			if(prob(8))
				to_chat(M, "<span class='danger'>You feel [pick("weak", "horribly weak", "numb", "like you can barely move", "tingly")].</span>")
				M.Stun(2 SECONDS)
			else if(prob(8))
				M.emote(pick("drool", "tremble"))
		if(11 to INFINITY)
			M.Weaken(40 SECONDS)
			if(prob(10))
				M.emote(pick("drool", "tremble", "gasp"))
				M.AdjustLoseBreath(2 SECONDS)
			if(prob(9))
				to_chat(M, "<span class='danger'>You can't [pick("move", "feel your legs", "feel your face", "feel anything")]!</span>")
			if(prob(7))
				to_chat(M, "<span class='danger'>You can't breathe!</span>")
				M.AdjustLoseBreath(6 SECONDS)
	return ..() | update_flags`

For the first 5 cycles (10 seconds) there is a 10% chance per cycle to drool or tremble.
For the next 4 cycles (8 seconds), you have an 8% chance per cycle to suffer a 2 second stun or have an 8% chance to tremble or gasp.

**Comment by Lime-7** [comment]
> > A/D didn't see it…
> 
> In `/datum/reagent/pancuronium/on_mob_life(mob/living/M)` (which I would show, but GitHub ruins the formatting).
> 
> For the first 5 cycles (10 seconds) there is a 10% chance per cycle to drool or tremble. For the next 4 cycles (8 seconds), you have an 8% chance per cycle to suffer a 2 second stun or have an 8% chance to tremble or gasp.

I meant, I didn't see it BEFORE... but anyway thank you

**Review by Spaghetti-bit — APPROVED** [review]
Code wise? Looks fine. It'll be interesting how this plays out.

**Review by Sirryan2002 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]

**Pull request merged**
