### PR TITLE
Add Welding Goggles and Prescription Glasses to Autolathe

### PR DESCRIPTION
**Pull request by Idobtknowlife**
:cl: Idobtknowlife
add: Welding Goggles to Autolathe Tool Section.
add: Prescription Glasses to Autolathe Medical Section.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Welding goggles are meant to be rare; there's really almost never a reason to pick a welding helmet with a change like this.

**Comment by Citinited** [comment]
I like welding goggles being the "rare" option, with helmets being the standard option.

👍 to glasses being added to the autolathe, though.

**Comment by SkeletalElite** [comment]
I don't really see why not. I think this perception of them being "rare" is pointless, what advantage does having the goggles be reproducible provide. I guess you could wear a helmet with them but I don't think this is going to cause an epidemic of Hard hat wearing civilians with welding goggles. Security has helmets that they use but their sec huds are already flash proof so they don't have any reason to use goggles. Engineers as it is tend to just walk around in hard suits anyways and even if it encouraged engineers to walk around without a hard suit to use the goggles I don't think that would be a bad thing. Considering the goggles take a slot where you could be putting a HUD I don't think this really affects anyone but civilians, who wont even be affected that much because really it makes little difference to them anyway.
I actually prefer the welding helmet over the goggles because I can wear some swag 3D glasses instead

**Comment by taukausanake** [comment]
> Welding goggles are meant to be rare

[Hmmmmmm](https://github.com/ParadiseSS13/Paradise/pull/7151#issuecomment-296396395). But yeah, I agree that the goggles maybe shouldn't be construct-able. I mean it would make sense to be able to make them but then the welding masks serve no purpose. Are there any other ways to get welding goggles besides stealing them from the department that starts with at least one?

**Comment by Birdtalon** [comment]
Welding helmets are actually much better mechanically as they can be worn by all races and allow you to also wear a HUD/sunglasses. So... it doesn't make sense why welding goggles are rare at all.

**Comment by ktoma36** [comment]
Goggles aren't some sort of special technology either. Keeping them rare just seems arbitrary given how simple they are structurally. Perhaps giving welding mask a buff to welding speed would be good if people are really worried about them becoming useless. It would make sense given that the welding mask would protect your whole face, allowing you to work faster without burning yourself. Also why not make welding do a small amount of burn damage if you aren't wearing protection? Those sparks hurt like hell and burn through clothing if you aren't careful.

**Comment by HereticChurch** [comment]
Just make goggles require plastic. That'd make them rare but still reproducible.

**Comment by ktoma36** [comment]
I dont even know how to make plastic so that would work. Actually is plastic even a thing people can get without deconstructing plastic flaps?

**Comment by taukausanake** [comment]
@ktoma36 Yes but it's so annoying that no one actually makes it. Requires Botany and Chemistry. You CAN however order it from Cargo so there's that

**Comment by Jountax** [comment]
@Tau I think I remember trying to make plastic a while back and failing, and looking at the wiki's chemistry page now I don't even see the plastic recipe anywhere anymore. Are you sure the ability to make plastic wasn't removed?

**Comment by taukausanake** [comment]
@Jountax if you're going to @ someone make sure you type in the full name otherwise you might be @ ing someone else

**Comment by TullyBurnalot** [comment]
First off, apologies for letting this sit for so long.

Due to the intentional rarity of the welding goggles, it would be preferable to have them moved to the Protolathe, under Engineering 3 or above, in order for the PR to be merged. Perscription glasses are fine in the Autolathe.

@Idobtknowlife

**Comment by Fox-McCloud** [comment]
Please update or this will be closed.

**Comment by tigercat2000** [comment]
No updates in a week, and still has merge conflicts.

**Pull request closed without merging**
