### PR TITLE
[AFD] Adds true British cuisine. 

### PR DESCRIPTION
**Pull request by SynthTwo**
## What Does This PR Do

Brings a bit of home to British players.

Microwave Recipes:
**Yum Yum**: 5u Milk, 5u Sugar, 1 Dough Slice

Oven Recipes:
**Belgian Bun**: 5u Milk, 10u Sugar, 1 Dough, 1 Cherry
**Sausage Roll**: 1u Salt, 1 Flat Dough, 1 Sausage
**Vegan Sausage Roll**: 1u Salt, 1 Flat Dough, 1 Soy Dope
**Steak Bake**: 1 Flat Dough, 1 Steak, 1 Onion Slice
**Sausage, Cheese and Bean Melt**: 1 Flat Dough, 1 Cheese Wedge, 1 Beans, 1 Sausage

## Why It's Good For The Game

https://github.com/ParadiseSS13/Paradise/assets/127706731/fe639157-8334-4ec4-a54f-08b3bb1b7864

## Images of changes

image
Sprites that would make McRamon cry.

## Testing

I spawned it and cooked it in game. What do you want from me?

## Changelog
:cl:
add: Adds six British cuisines. Check the PR for the recipes.
/:cl:

### CODE REVIEW

**Review by AffectedArc07 — APPROVED** [review]
Fuck AFD - this should be a mainline thing

**Comment by SynthTwo** [comment]
> Fuck AFD - this should be a mainline thing

If we get proper sprites for it, perhaps.

**Comment by LouiseIsntHome** [comment]
why mostly oven recipes? greggs only use microwaves
but fr, keep this after afd i beg

**Comment by SynthTwo** [comment]
> why mostly oven recipes? greggs only use microwaves but fr, keep this after afd i beg

We gotta have some _class_

**Pull request merged**
