### PR TITLE
.357 nukie price fix

### PR DESCRIPTION
**Pull request by shazbot194**
This PR adds in a new entry for the .357 for nukies only. I made this PR because it was mentioned that the .357 costs 13 points for nukies, where other, much more powerful weapons, like the 50 caliber sniper rifle only costs 16, 3 points more. Not to mention no nukie I have ever seen or heard has ever used a .357. So this PR lowers the cost for the .357 to 7 points for nukies. I want to emphasis that this in no way affects the traitor .357 cost, nor the surplus chance for .357s, it only makes the nukie .357 cheaper to make it more competitive with other weapons in price. Now, if 6 is too low, I would be more then happy to raise it.

🆑 Shazbot
Adds: Lowers the price of the .357 for nukies
/🆑

### CODE REVIEW

**Comment by Regen1** [comment]
Reducing it by over 50% might be a bit drastic.

**Comment by shazbot194** [comment]
Very true, I'm not quite dead set on any price, other then less, hopefully 10 or less. I do think about 6 or 7 would be fair, but I am more then open to suggestions.

**Comment by AdamElTablawy** [comment]
It does 60 damage per shot, if i'm not mistaken. That's pretty damn powerful.

**Comment by Shadeykins** [comment]
@AdamElTablawy It also only holds six shots and nukies lack access to a lathe to get more ammo, which means they have to buy it at a cost of .5TC per bullet.

At 13TC it's simply not economical, an M-90gl costs 18TC IIRC, has an under-barrel grenade launcher, has a 30 round magazine in 3-round burst, and additional ammo is 5TC for another 30 rounds. The M-90gl does 35 damage a shot (one bullet), which is 105 damage per burst. The end result of a full magazine is 1,050 potential damage. Assuming you buy no magazines, you get 58 damage per TC spent with misses being far more economical (a single miss costs you .16TC in ammo value).

For contrast, the revolver is 13TC with 3TC speedloaders. Each shot does 60 damage, which means disincluding a reload you get a potential of 60 damage per shot for 13TC. The end result of a full chamber is an output of 360 potential damage. Assuming you buy no magazines, you get 27.7 damage per TC spent with misses coming at a steep TC cost (A value of .5TC lost per shot).

This doesn't take into account the revolver's sloppier reload either which requires a speedloader for every 6 shots (meaning you take up way more inventory space for ammo). The revolver also has a lower rate of fire in comparison to the burst mode. In the time the revolver can dish out 360 damage (6 shots), the M-90gl is capable of dishing out 630 (6 bursts).

For 13TC, the revolver is absolutely useless to an operative. It's arguably still useless even with a severe TC reduction due to inventory space being limited and the revolver requiring a staggering amount of ammo to compete with other ranged weaponry.

**Comment by shazbot194** [comment]
I would like to point out that it does have 7 per cylinder, and not 6, but that doesn't help too much. This means that per TC, and at my 7 TC price, your first load is 1 TC = 60 damage, which is very close to the M-90GL at 1 TC = 58 damage (not including the grenade launcher, which ups the value a lot). However, for re-loading, it still misses out. For the M-90GL, you get 1 TC = 210 damage, where the revolver gets 1 TC = 140 damage. This could be solved by lowering the ammo cost to just 2 TC, which puts it on par with the M-90GL at 1 TC = 210 damage.

**Comment by DarkPyrolord** [comment]
Alrighty then, just in advance I will say if you want more information regarding this, feel free to contact me on discord, which you already know how to get me through there.

With this, it is going to be a no, nuclear operatives already have access to a wide variety of weapons which are much more helpful with their uplinks already, but this is only really part of the reason. The one major thing is that many due to how clunky it is compared to taking any other gun and much less versatile it is, plus with how expensive the ammo is to buy along with it as well, even with this reduction of price of the main gun would just become more of a noob trap than anything and we don't really need any more of those with an already large choice of weapons available to nuclear operatives.

**Comment by tigercat2000** [comment]
..... I pressed the wrong button lmao what the fuck

**Comment by shazbot194** [comment]
So if it is such a noob trap, why have it on the roster at all if it's going to remain such a horribly expensive price?

**Pull request merged**
