### PR TITLE
Gives the mechanic EVA access

### PR DESCRIPTION
**Pull request by MarcellusPye**
Since the pull to give the mechanic their own softsuit seems to be dead this is still needed

🆑 MarcellusPye
add: EVA access to the mechanic
/🆑

### CODE REVIEW

**Comment by DesolateG** [comment]
I'd rather this than having to beg MY OWN DEPARTMENT or the HoP for access to a suit.

**Comment by Bigtimetripod** [comment]
Add a changelog note also since it impact ingame.

**Comment by taukausanake** [comment]
I'd personally give them their own softsuit but make it a normal suit, not some steampunk mesh, no offence to the original PR. I think they could get something pretty cool and special. Maybe I'll take a swing at it later; go another thing I have to test first

**Comment by MarcellusPye** [comment]
@Bigtimetripod I've only done bug fixes before, how do I add change-log notes?

**Comment by MarcellusPye** [comment]
@taukausanake I made this because the Pull to give them their own softsuit appears dead and I'm too lazy to map a normal one in.

**Comment by Bigtimetripod** [comment]
Seems ye already got it, but im sure Fox can help ye in the future. Im just a amateur who can read the code and change values and stuff. Usually if the changes impact ingame, changelog note is needed to log and keep track of different changes. Backend stuff like cleaning up the code and Admin changes do not need a change log note IIRC.

**Comment by MarcellusPye** [comment]
Hmm, some of my fixes should probably have had changelogs... oh well.

**Comment by Fox-McCloud** [comment]
Just add an engineering hardsuit+helmet+oxygen tank to a rack in the mechanics office/locker, instead, please.

**Comment by tigercat2000** [comment]
This needs to be updated to do as Fox said or this will be closed.

**Comment by taukausanake** [comment]
Question: Would it be bad if to re-purpose one of the existing EVA suits to be a Mechanic suit? I kind of like the black and yellow one, might work nice for the job

**Comment by MarcellusPye** [comment]
I have no idea how to map and it's completely different to the original pull so I'el just close it.

**Pull request closed without merging**
