### PR TITLE
Adds the Staff of Slipping and Clown wizard outfit

### PR DESCRIPTION
**Pull request by datlo**
Adds the Staff of Slipping to the wizard spellbook, for 1 spellpoint. Sprited by Mithrandalf, thanks a lot.

icon

Shoots bananas that will slip humans and stuns cyborgs (if not already stunned), including through noslips.
Does not leave peels behind.

Made the staff of the honkmother a subtype of the staff of slipping.

Added a new "magical" var to clothing, and replaced type checks on wizard spell cast to check for that var instead.

Added a clown wizard outfit, along with magical clown shoes to the wizard magivend.
wizclown

Also comes with specie sprites for the mask
voxclown

🆑 
Add: Added the Staff of Slipping to the wizard spellbook for 1 spell point, sprites by Mithrandalf.
Add: Added the wizard clown outfit to the wizard vending machine.
/🆑

### CODE REVIEW

**Comment by Mithrandalf** [comment]
magical var is long overdue tbh

**Comment by Mithrandalf** [comment]
I'll do the sprites if you want dude

**Comment by Ralta** [comment]
The outfit kinda looks like Ronald McDonald wearing a sombrero 🤔

**Comment by datlo** [comment]
And that's an issue, why? 🤔

**Comment by Ralta** [comment]
> And that's an issue, why? 🤔

Who said it's an issue? Wondering if that was the intent.

It's not very 'wizardy' imo, but it's a big ol' meme, so I suppose it doesn't matter all that much.

**Comment by datlo** [comment]
You'd have to ask the person who originally made the sprites, I only added the items in the machine.

Anyway, I was just jokin', might not have gone through the screen. The outfit is unique and wizardy enough to be recognised as a wizard, which is ultimately what matters.

**Comment by datlo** [comment]
Alright, this should be ready now.

**Comment by KasparoVy** [comment]
Honk

**Pull request merged**
