### PR TITLE
Add pAI and Ghost Spawns buttons for ghosts

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

Adds buttons for configuring pAI or choosing a mob spawn, hidden by default and can be toggled with a separate button next to the others

## Why It's Good For The Game

Hopefully it'll result in more players playing pAI. It'll also make it more convenient rather than use a verb/wait for a message to show up

## Images of changes
cZ1Dpw2p4D

## Changelog
:cl:
add: Add buttons to configure pAI or choose a mob spawn while observing
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I don't believe it's off center when you factor in that the HUD is missing an element; on TG there's a pAI button.

It was more of a challenge to implement for the person that ported this HUD--I'd love to see it ported as it'll encourage more people to play pAI.

**Comment by AffectedArc07** [comment]
@Fox-McCloud this is the current measurements of the HUD
image
Personally I would much rather a button to show available ghost spawns on the HUD instead of a pAI signup button.

@dearmochi thoughts@

**Comment by dearmochi** [comment]
@AffectedArc07 What do you mean by ghost spawns?

Maybe implementing **both** would be a good alternative as well? pAI are pretty underused and I'd also like to see them more.

**Comment by AffectedArc07** [comment]
@dearmochi Ghost spawns = things like free golem, old station, etc. Adding a button for those instead of the verb only we have now could be nice.

**Comment by dearmochi** [comment]
Hopefully that responds to both of your wishes:

cZ1Dpw2p4D

(This was my first attempt at spriting something - I think it went ok!)

**Comment by AffectedArc07** [comment]
image
Is this my perfectionist side being too picky?

**Comment by dearmochi** [comment]
@AffectedArc07 no worries, I just fixed it now

**Comment by Spacemanspark** [comment]
AffectedOCD

**Pull request merged**
