### PR TITLE
[AFD] HONKable TGUI

### PR DESCRIPTION
**Pull request by AyIong**
## What Does This PR Do
Makes your eyes bleed if you open any TGUI
And interacting with him makes you want to go deaf

## Why It's Good For The Game
HONK

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/69762909/d469782c-b889-4a31-886d-92d5409200d3

## Testing
HOOONK

## Changelog
:cl:
tweak: TGUI now have better color palette and beautifull interact sound
/:cl:

### CODE REVIEW

**Comment by Oyu07** [comment]
my eyes are bleeding

**Comment by Pythbit** [comment]
the honkmother blesses this PR

**Comment by AyIong** [comment]
Wrong cherry-pick branch

**Review by Burzah — APPROVED** [review]
This is cursed. Approved.

**Comment by Contrabang** [comment]
My personal opinion, but I'm not so sure about this one. It seems really bad visually for interfaces that are required, and I feel we should maintain standards about visibility of UIs, specifically the WCAG standard.

https://webaim.org/resources/contrastchecker/

**Comment by AyIong** [comment]
> My personal opinion, but I'm not so sure about this one. It seems really bad visually for interfaces that are required, and I feel we should maintain standards about visibility of UIs, specifically the WCAG standard.

image

**Review by S34NW — COMMENTED** [review]
This is gonna get a round or two of separate TM within the day, as opposed to all day, due to the major implications on my eyes.

**Comment by AyIong** [comment]
xdd

**Comment by S34NW** [comment]
Merging for one shift

**Pull request merged**
