### PR TITLE
Plant Bags of Holding

### PR DESCRIPTION
**Pull request by imsxz**
This is mostly a convenience thing for botany. I didn't realize how restricting only being able to hold 100 plants was until a recent botany traitor shift where I ran out of space in my plant bag, and wasn't able to hold my desired amount of combat plants.

Lots of room for suggestions, and this is my first pull request ever so if I goofed anywhere be sure to tell me. Infinity might be a bit much so I can turn that down a bit too.

Just tossing this idea out there because it can be a bit cumbersome late-game botany when messing around with countless plants.

🆑Imsxz
add: adds the plant bag of holding item
add: adds the plant bag of holding design to protolathe
/ 🆑

### CODE REVIEW

**Comment by KasparoVy** [comment]
Merge at your own peril

**Comment by Spacemanspark** [comment]
You mean your obnoxious tesla bolt tomatoes?
...You don't need to be carrying around an infinite number of those.
:-1:

**Comment by imsxz** [comment]
If a botanist is running around spamming thousands of shock plants, job ban him for self antagging 👀

**Comment by imsxz** [comment]
Also they were berries, not tomatoes. My tomatoes were my teleporting ones.

**Comment by Aurorablade** [comment]
The teleporting one still falls under what spark said. Pretty much sparks arguement can apply as such:

> You mean your [annoying plant mutation]?
...You don't need to be carrying around an infinite number of those. The botany bag lets you hold as much as you need. Sorry, but...

**Comment by Spacemanspark** [comment]
@imsxz As Fethas said, my point really doesn't change.

**Comment by SamHPurp** [comment]
Code-wise I don't see any immediate problems. (Just a picky complaint that its just a copy paste with a word changed from the mining satchel in the description).

Balance-wise, I think thats terrifying. Nooooo thank you.

**Comment by imsxz** [comment]
I'll just continue stealing all the plant bags and carrying 500 of my plants anyways 😢 
This was mostly supposed to be for convenience, I can still carry a shitload of plants without it, I understand the worries about it though.

**Comment by pinatacolada** [comment]
Needs a , just copy paste it from.any other pr

**Comment by FlattestGuitar** [comment]
I commend the effort involved in making this PR, seeing as you bothered with the GitHub editor, but I really don't like the idea of buffing botany.

Additionally, I believe plant bags should be nerfed to disallow carrying 500 grenades on your person at once.

**Comment by Spacemanspark** [comment]
I can literally make batteries from potatoes that have a 9999999999999 rating.

**Comment by imsxz** [comment]
Each plant bag can carry 100 plants. From a non antag perspective, its still tiring late-game when you've got a bunch of yield 10 plants that you're moving around. All of the negative responses to this PR are assuming that the botanist is both knowledgeable in botany AND a traitor, which most likely wont occur very often.

**Comment by Aurorablade** [comment]
>  All of the negative responses to this PR are assuming that the botanist is both knowledgeable in botany AND a traitor, which most likely wont occur very often.

I am not even factoring that into this. But i know how some people on our player base are.

**Comment by Fox-McCloud** [comment]
Botany doesn't really need buffs at this stage of the game.

**Comment by FalseIncarnate** [comment]
You can produce more plant bags with the biogenerator already present in hydroponics AND the public garden.

While a BoH for botany seems nice, it also is a bit unnecessary, and probably not too likely that you'd get science to actually make you one of these. Between your basic plant bags/portaseeders and the smart fridge, plant storage isn't a big concern for botany, except for when you are trying to literally carry around a greenhouse in your pocket to throw at people. If you ARE trying to carry around a greenhouse in your pocket, you probably need to reconsider whether or not that is your best option... as a traitor you get access to some powerful equipment and as a non-traitor why would you need more than 100 meme plants in your pocket outside botany?

**Comment by imsxz** [comment]
Again, it's not supposed to be one of those required things, it's supposed to be a nice reward from scientists if you get them to bio 7 and combat 6 with dank plant research. X of holdings in general aren't required, but they exist for convenience sake.

Side note, one of these would have been useful during Purplegenies event when he wanted loads of Gaia as a slaughter demon, wasn't able to bring all of it

**Comment by imsxz** [comment]
Also I agree with Fox, botany is super strong currently

**Comment by SamHPurp** [comment]
@imsxz For your example with the event, this is a simple var-edit that could be done with a sufficient pray. ;)

**Comment by taukausanake** [comment]
What if you lower the amount that a normal plant bag can carry but have the bluespace bag hold the 100 the normal would? I do like being able to transfer so much at once but I like the feeling of progression. That there is something better I can get later. Would that maybe work?

**Comment by TullyBurnalot** [comment]
Following discussion, it was decided to close this PR; Botany, at this time, does not really require any extra buffs, and the current equipment already handles immense amounts of food storage, in addition to being easily reproducible in one of Botany's own machines.

**Pull request closed without merging**
