### PR TITLE
Resprites areas, fixes areas covering more rooms than needed [MAP EDIT]

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
Resprites all internal area sprites to be a consistent and easy to read, along with changing their color to department/access based. Removes some used area sprites, adds new ones for places with no proper sprite, and renames some of the old ones to be accurate too. It also fixes some areas being invisible by giving them a proper icon (I checked all the maps, they should all be fine). It also changes/add areas on maps where they should be.

I.E.
- Delta toxins launch room is now its own area
- All medbays are "medbay" instead of medbay2 or medbay3 where applicable
- Delta exam room is now properly labelled instead of medbay2
- Delta medical storage is now medical storage instead of medbay3
- Delta medical break room is now its own room with APC and Air alarm
- Delta and Meta AI sat exteriors are now properly named and area'd
- Box "patient ward" is now a surgery waiting room
- Meta's cargo hallway is now North-east central hall

## Why It's Good For The Game
Readability is good, along with areas being properly named what they are.

## Images of changes
Meta
image
Delta
image
Box
image
Altered space and nearstation sprites
image

## Changelog
:cl:
tweak: Areas on all 3 stations have been changed to be more accurate.
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
Why are you renaming the cargo hallway to the central primary hallway? That's the exact same name the area right beside it has. Not to mention the hallway isn't even central, it's fore port.

image

image

>Delta and Meta exteriors are now properly named and area'd

Please elaborate, mapdiff sucks ass at showing area changes and won't highlight them.

As for the new area icons ehhh... I don't think this going to help much with areaing. Keep in mind areas are not something a mapper is constantly staring at and are only turned on when you're actually areaing a place.

The colours you selected are very dull and just bleh. Ideally, we should use as many colours as we can and they should switch to different hues in between subareas and be more noticeable in between actual departments. For example, in your PR main hallways and maints both have grey dominant icons or that all of the dorms, locker room, fitness etc share the same grey colour with main hallways which is a direct downgrade from before.

Look at TGs, areas shift from lighter to darker colours all the time, even in between maints, and overall the colours are more vivid with wording having an opaque boarder. This really helps with differentiating areas and lessens mapping errors.
image

image


pr1

That and TG also made their space area icon completely blank which helps with nearspacing. I really don't know why this PR instead makes the nearspace icon darker when it's something that needs to be visible.

I hate to be the person who always points at TG and goes 'look it's better!' but in this case I genuinely think it's important as mapping errors are really common on Paradise and propper area icon colouring is a good way to avoid them.

**Comment by Contrabang** [comment]
> Why are you renaming the cargo hallway to the central primary hallway? That's the exact same name the area right beside it has. Not to mention the hallway isn't even central, it's fore port.
I'm trying to get rid of var-edited areas in favor of them having their own sprites, I agree that it probably be its own hallway name and area, but that is for a future PR (probably one where I also rename the different central hall locations with northeast, southeast, etc as their subtypes detail.
> > Delta and Meta exteriors are now properly named and area'd
> Please elaborate, mapdiff sucks ass at showing area changes and won't highlight them.
This is my bad, I meant to say ` Delta and Meta AI sat exteriors`, since we have a proper type for those.
> As for the new area icons ehhh... I don't think this going to help much with areaing. Keep in mind areas are not something a mapper is constantly staring at and are only turned on when you're actually areaing a place.
> 
> The colours you selected are very dull and just bleh. Ideally, we should use as many colours as we can and they should switch to different hues in between subareas and be more noticeable in between actual departments. For example, in your PR main hallways and maints both have grey dominant icons or that all of the dorms, locker room, fitness etc share the same grey colour with main hallways which is a direct downgrade from before.
Yeah, I'll add more colors to general areas and try to swap up the colors some more. I basically wanted to make it colored based on access requirements and remove a lot of the random excess colors we had. As for dull, I think the originals were a bit of an eyesore, I think being less saturated is good.

**Comment by Contrabang** [comment]
Images updated on PR, no touching areas should have the same color now, fixed the space and nearstation thing too.

**Comment by Bm0n** [comment]
> I'm trying to get rid of var-edited areas in favor of them having their own sprites, I agree that it probably be its own hallway name and area, but that is for a future PR (probably one where I also rename the different central hall locations with northeast, southeast, etc as their subtypes detail. This PR is trying to minimize of all those random areas with just colored areas and no letters on them.

Let me be very clear, both of these areas now have the exact same name. They are both being called "Central Primary Hallway" in-game.
image

image
A var edited area isn't ideal but it works so long as there aren't any of the base areas zoned on the map. If you're just after colour var edit the name on the new area back to what it was before. It has always been a var edited area (yes even before the remap) so no harm there.

**Comment by Contrabang** [comment]
Merged master, delta is fixed @S34NW

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
