### PR TITLE
Animated Cloner

### PR DESCRIPTION
**Pull request by tigercat2000**
on the tin more or less, makes cloning people animate them being slowly created, proper icons and stuff

Demonstration video, because cloning takes too long for a gif; http://youtu.be/wfrvWlx0Y20

meh image of half-complete clone
gif of new scifi blue-bar builder thing

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Weren't we going to use the new cloning machines?

**Comment by tigercat2000** [comment]
my previous PR upgraded cryo tanks, this one updates the cloner- Albiet, not with bay's fancy multiple-pod stuff, simply because we use nanoUI whereas bay uses the old system, and I have no idea how to port the differences into nanoUI

**Comment by Spacemanspark** [comment]
That's pretty impressive.

**Comment by Fox-McCloud** [comment]
need the green water and bubbles that the normal cloner has.

**Comment by tigercat2000** [comment]
not feasible to extract that animation, really

**Comment by ZomgPonies** [comment]
Can't you use overlays to keep the green water and bubbles and just add the people slowly being created on top of it?

**Comment by tigercat2000** [comment]
that would require an overlay of bubbly green water, the only one of which also contains a dark spot that looks human-ish, and i am not able to modify/make an even okay-looking overlay for it with my coderart

**Comment by SamCroswell** [comment]
I love the new cryo icons, but I *vastly* prefer the old cloning pod icon to this one.

**Comment by tigercat2000** [comment]
@SamCroswell Is there anything specific about the new sprite you dislike? These sprites are just codersprites more or less, always open to modification

**Comment by adrkiller59** [comment]
The fetus shadow submerged in green bubbly goop is better than this?

alternate text

Well i sure like that it lets you see how the clone is being reconstructed. It would also allow the doctors the estimate the completion progress by just looking at it.

**Comment by SamCroswell** [comment]
Firstly, I'm not a fan of how large the person is in relation to the pod, secondly I really do a cloning pod that makes it look like the person is being 'grown' as opposed to 'put together', and I think the old cloning pod accomplishes this very well.

I just don't see why we'd replace a pretty nice sprite with codesprites, as you put it, for the sake of novelty.

**Comment by Spacemanspark** [comment]
No, you click on the pod, don't examine it.

**Comment by adrkiller59** [comment]
Well, personally I prefer to have more original and unique content in the code rather than just porting stuff from the major codebases. And i can hardly see people saying "Booo the old sprite was betteeeeer!". And again, the old pod doesn't accomplish any "growing" look because it's one single animation which doesn't change. How is that supposed to look like "growing" ?

Maybe it would be possible to use the TED code to make it so the clone is formed pixel by pixel instead of being "printed".

**Comment by SamCroswell** [comment]
@adrkiller59 
'More content' is not a reason to not have standards when it comes to the content we put in our code. 

You don't see people disagreeing with the implementation of the new icon because you like ii. Same way I don't see people agreeing with it because I dislike it.

And I beg to differ -- The old pod absolutely does accomplish that look. If we want to be able to check the progress at a glance (And, according to spaceman, we already can by just clicking the pod) we could always change the bar at the bottom into a progress bar fairly easily.

**Comment by tigercat2000** [comment]
I'd like to get more comments, but, if the general consensus is that the sprites really aren't any better, I suppose I'll close this.

**Comment by Spacemanspark** [comment]
I like the idea of seeing them form together inside the pod.

**Comment by ZomgPonies** [comment]
As much as I love new content, I don't think this sprite is really better than what we currently have. I strongly recommend you try to port Bay's bigger, multi-pod cloning stuff and poke PsiOmegaGamma or whatever his name is to make a nanoUI interface for it, maybe using our interface as a basis. :)

**Comment by tigercat2000** [comment]
After.. further testing further testing oh god why 32 cpu
 I think I will just close this PR and.. do something that doesn't burn my computer

**Pull request closed without merging**
