### PR TITLE
Additional job names

### PR DESCRIPTION
**Pull request by orelbon**
Adds new Job titles.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Feature freeze (#5651)

**Comment by orelbon** [comment]
i know but i'm gonna forget about this if i don't leave it posted. I don't expect it to be merged any time soon.

**Comment by Fox-McCloud** [comment]
Re-submit this after the freeze ends, or re-open it once it does so.

**Comment by tristan1333** [comment]
ya think ya could get fancy shmancy names through the freeze did ya kid? Well I got news comin' to ya fella, we ain't lettin' none feature, that meanin' ya fancy names ya rootin' tootin' hooligan you.

**Comment by orelbon** [comment]
Lol.

**Comment by orelbon** [comment]
@Fox-McCloud would you open this again and let me close it, i can't reopen it if you're the one who closed it.

**Comment by Crazylemon64** [comment]
> update medical.dm

fee fi fo fum
I smell the blood of the github editor

**Comment by orelbon** [comment]
@Crazylemon64 i was doing the editing straight on the website cause i was too lazy to do it from my files.

**Comment by taukausanake** [comment]
Yeah, simple file edits like this should be okay on the site. Little messy with a commit per file edit but no harm done.

These names do look good but I don't know how "Medical Assitant" (missing an 's' by the way, "assiStant") for the paramedic might not fit. They don't help out doctors, just perform emergency medical treatment and/or get them to Medbay so they can get full proper treatment.
"Clinical Scientist" for scientist also sounds a bit off. Yeah you're going to have some of those guys in the test lab making exploding lube drugs and rarely medical chemicals. Doesn't really fit for the title.
All the others are fine. "Chemical Engineer" gave me looks but it all the same works

**Comment by Spacemanspark** [comment]
Polaris has an alternate title for captain called "Station Administrator".

**Comment by orelbon** [comment]
@taukausanake thanks for the correction, medical assistant could be used for the paramedic because most EMTs are required to complete some type of medical assistant program. Remember these names are totally just for RP so if a scientist wants to spend the game researching medicine they would pick clinical scientist if they wanted. They are under no obligation to pick it.

**Comment by taukausanake** [comment]
@Spacemanspark I'm under the assumption that it would take a little more code to change any heads titles, especially the captain's as he's not supposed to have it changed. And I think of a Station Administrator more like Telecomms or some second or third in command who is not a head. Just my two cents.

@orelbon Okay I can understand that but I guess I also forgot to mention my slight worry that as "assistants" they might be compared a little to the gray shirts. Just a slight worry. As for Clinical Scientist I also thought it felt too much like Medbay and Science and we all know what people think of Geneticists

**Pull request closed without merging**
