### PR TITLE
Adds Vox-fitted Hydroponic HUD (nightvision version incl.)

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
imgadd: Adds Vox-fitted Hydroponic HUD (nightvision version included).
/:cl:

Must've missed the PR when it was originally made. Woops.

voxbotanyhud

### CODE REVIEW

**Comment by KasparoVy** [comment]
Oh God, I forgot to take a picture of the west facing NV

BRB

**Comment by IcyV** [comment]
Hail Kasparo, hero of the Vox

**Comment by taukausanake** [comment]
Fuck why did I not know this

**Comment by Davdichan** [comment]
Cause yous a duslung meatlover

**Pull request merged**
