### PR TITLE
Mining Cyborgs get NOTHING (But the mining vendor gets rearranged and gets a new cell)

### PR DESCRIPTION
**Pull request by PidgeyThePirate**
## What Does This PR Do
- Reorganizes the mining vendor into categories for easier navigation (once people relearn it).
- Adds the Thermal Cell, costing 600 points from the vendor. It is a 10k capacity cell that charges at a rate of 50 units/tick (compared to 125 per tick for the slime core) when outside in lavaland or in other high temperature environments.

[Vendor Appearance](https://imgur.com/a/zBxbQO0)

## Why It's Good For The Game
The mining vendor has a crappy UI, and I improved it a bit. The thermal cell is a hold-over from the previous version of this PR, but I left it in because it still may have some value in future mining cyborgs or mechs.

## Changelog
:cl:
add: The Thermal Cell: 10k power, recharges 50 energy/tick in lavaland or hot environs.
add: Added the Thermal Cell to the mining vendor for 600 points.
tweak: The mining vendor UI has been reorganized and category spacers added.
/:cl:

### CODE REVIEW

**Comment by PidgeyThePirate** [comment]
I think there may be a better way to handle the borg points, but I'm not certain what the correct approach is.

**Comment by Fox-McCloud** [comment]
I'm extremely skeptical of cyborgs being able to earn upgrades for themselves, since they're not crew, but the station's equipment slaved to the AI; it also means even more free mining gear if you're buddy-buddy with a mining cyborg.

**Comment by PidgeyThePirate** [comment]
I really don't know what else to do about mining cyborgs though. If you make them start off with all the fun stuff then they'll be better than miners, and if you don't give them anything they're just going to languish forever. All the other borgs play by their own department's rules to some extent, mining should too.

You get more mining gear if you're buddy buddy with a cyborg anyway because all those points have to go somewhere even if the borg can't take them. The only reason this isn't relevant now is because NOBODY plays mining borg.

My original idea was an "upgrade booth" of sorts where the roboticist can choose upgrades for you using your points, but that felt like unnecessary bloat when we already had vendors.

**Comment by craftxbox** [comment]
The whole vendor UI redo thing would probably have done better off in its own PR

**Comment by PidgeyThePirate** [comment]
Eh, I'll just split it off if (more like when) this gets denied. I did it while I was trying to figure out where to put the new cell.

**Comment by craftxbox** [comment]
PR's should really be made atomically anyways, these are two separate features, one of which may not be wanted but the other definitely is, mixed into one PR which makes it annoying to have to make a second pr to remove the stuff that isn't wanted in the first place

**Comment by PidgeyThePirate** [comment]
Whatever. I'll deal with it once I get back to my computer, probably. Everything I've worked on other than two-line fixes has been flatly rejected so far, even the relatively minor QoL stuff. My motivation is starting to flag.

**Comment by craftxbox** [comment]
You've had one PR given a no, (#12425), One pr given a "maybe?" (#12424), and one PR you outright closed because a maint made an **alternative** (#12460), and two pending decision from maints (#12423,#11927). Making less than 25% of your actual feature pr's flatly declined, You not having motivation is not a result of prs being declined, as, you've really just been closing them on yourself and not giving them a chance.

**Comment by PidgeyThePirate** [comment]
Maybe I'm massively misunderstanding the dynamic here, but as far as I know a maint making an "alternative" means I might as well close mine. Similarly the head of staff coming straight out and saying that they don't like an idea sounds to me like I might as well stop wasting my time. 

I really am trying my best but I feel like there's something about the whole business I'm just not getting, and that's a disheartening feeling.

**Comment by PidgeyThePirate** [comment]
I'm not sure how to read or deal with this conflict though.

**Comment by taukausanake** [comment]
I like the sound of that thermal cell. Will it work in anything that takes a battery and not just cyborgs?

**Comment by PidgeyThePirate** [comment]
Yeah, I've tested it in cyborgs and in bags. It should work fine as long as the object holding it is in the right zone.

**Comment by variableundefined** [comment]
Closing due to objections

**Pull request closed without merging**
