### PR TITLE
Removal of Deprecated Flags, Addition of New Flags [Refactor] [Ready to Merge] [Conflicts with Almost Everything]

### PR DESCRIPTION
**Pull request by TheDZD**
- As per Baystation12/Baystation12#7924 and tgstation/-tg-station#2192
 - Removes TABLEPASS and FPRINT flags. The former was no longer used as it is handled via pass_flags. The latter was used once, however was redundant, as literally EVERYTHING had the flag.
 - Sorts some of the setup.dm flags so they're in order.
 - Replaces 'flags & 2' in policetape.dm with pass_flags & PASSTABLE,
should have the same effect.
- Also adds ABSTRACT and NODROP flags in preparation for removal of
canremove and abstract vars.
- [x] Add NODROP flag from TG to replace canremove var as per tgstation/-tg-station#2772.
 - [x] Add to needed objects and change code where needed.
 - Renames the u_equip proc to unEquip.
 - Gets rid of the before_take_item and drop_from_inventory procs, unEquip proc slightly changed and now replaces these.
 - Gets rid of some of the needless copypasta in inventory code.
- [x] Add ABSTRACT flag from TG to replace abstract var as per tgstation/-tg-station#1802.
 - [x] Add to needed objects and change code where needed.

### CODE REVIEW

**Comment by TheDZD** [comment]
One Monster Hunter binge, many merge conflicts, and 8 hours of work later. Just needs testing now.

**Comment by ZomgPonies** [comment]
2 compile errors:

code/game/objects/items/weapons/defib.dm:414:error: canremove: undefined var

code/game/machinery/vending.dm:310:error: usr.drop_from_inventory: undefined proc

**Comment by TheDZD** [comment]
Should about fix it, would prefer it not be merged just yet though, as I haven't had a chance to do much testing on a local server.

**Comment by TheDZD** [comment]
Should be ready to merge now, may want to wait for Travis just to be sure though.

**Pull request merged**
