### PR TITLE
Reorganizes and Adds Items to the Clothing Vendors

### PR DESCRIPTION
**Pull request by Herder05**
## What Does This PR Do
Changes amount of items in clothes mate from 1 ---> 2-3
Items changed to 2
Fedora,Overalls,waistcoat,strippedDress,SailorDress,RedEveningGown,BlackTango,IanShirt
Items changed to 3
Classic Jeans, Camo Jeans, Black Jeans, Khaki Jeans, White Jeans, Red Pants, Black Pants, Tan pants, Blue pants, Track pants, miljackets,Scarfs,Ties,bandanas

Additions:
Hydroponics Winter Coat(hydrodrobe)
Black Trenchcoat(ClothesMate)
Brown Trenchcoat(ClothesMate)
Black and Blue Jacket (ClothesMate)

Move:
Black Skirt (Autodrobe --> Suitlord9000)
Jackboots (Autodrobe --> Shoelord9000)
Olive/White/Navy/Desert Military Jacket (Autodrobe --> ClothesMate)
Blue/Red/Black Tie (Autordrobe --> ClothesMate)(also its labled just accessory)
Laceup Shoes (ClothesMate --> Shoelord9000
Bandana/Black Bandana (Autodrobe --> ClothesMate)

Order Changes:
Move Glasses/Sunglasses above fingerless gloves (ClothesMate)
Move Navy Suit jacket below overalls to the other suit jackets

Removals:
Monocole(ClothesMate) Reason: already in the Autodrobe & fits autodrobe better
Kilt(ClothesMate) Reason: already in the Autodrobe & fits that
Black Shoes(ClothesMate) Reason:Found in a nearby vendor and all over the floors.
Waistcoat(Autodrobe) Reason: already in the ClothesMate & fits that better
Poncho&Sombrero(ClothesMate) Reason: it along with different colored versions already present in the autodrobe.

## Why It's Good For The Game
Gives players more options with clothing because there is no reason that there should only be one red scarf and the black jacket/hoodie is not even in the vendor
also cleans it up a tiny bit for it to just make a bit more sense

## Testing
Ran the game it launched fine and the objects were in the vendor

## Changelog
:cl:
tweak: moved things around in clothing vendors, check PR for details
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

PR author has now linked their account

**Comment by hal9000PR** [comment]
@Herder05 I'm going to be putting this on hold until 
#19209 is in. I really want to see the economy actually exist and this pr is completely conflicting with it.

**Review by S34NW — APPROVED** [review]
While it is on hold, the code looks fine to me

**Comment by Herder05** [comment]
Closing this as I no longer have the hard drive this was written on and the economy update will require it to be completely redone.

**Pull request closed without merging**
