### PR TITLE
Screw my life. Blueshield Coat.

### PR DESCRIPTION
**Pull request by TheBeoni**
Added blueshield coat to code. Added Blueshield coat to locker, added jacksandals to locker.

### CODE REVIEW

**Comment by TheBeoni** [comment]
I am sorry for my screw ups. Finally this is complete. I am still not able to work with github without doing all the damn mistakes.

**Comment by Fox-McCloud** [comment]
The collars should still not be a part of this PR; that was already merged into the codebase and they're not currently in, anymore; the last time we merged in a PR like this, it ended up causing problems for future PRs in that they would be merged in and mysteriously disappear.

You need to fork from Paradise (which you've done)...then make a new branch on that fork. Make necessary code changes on that branch then commit those changes you've made to that specific branch. Once you've done that, then make a pull request from that branch.

There shouldn't be any changes that you didn't make in a pull request. 

If absolutely necessary, I or another coder can handle this, but if you'd like to make PRs in the future, it would be best to learn how to do things yourself =3

**Comment by ZomgPonies** [comment]
The collars don't -really- matter since they're not in the vendor anymore. It's actually a cleanup. But yes, the problem is if he isn't up to date and there was changes to the suit icons files in between, those changes will be lost.

**Comment by Fox-McCloud** [comment]
Went ahead and got you covered this time! https://github.com/ParadiseSS13/Paradise/pull/1313

**Pull request closed without merging**
