### PR TITLE
Supports +1 Eng and +1 Atmos tech job slots

### PR DESCRIPTION
**Pull request by Kyep**
- Changes Engineer slots from 5 to 6, and atmos tech slots from 4 to 5.
- Adds an additional eng hardsuit (4->5), atmos hardsuit (2->3), eng locker (3->4), and atmos locker (3->4). All of these are positioned next to the existing ones.
- Tags: config change, map edit.

🆑 Kyep
tweak: eng/atmos now support an additional job slot each.
/🆑

### CODE REVIEW

**Comment by Necaladun** [comment]
AVE ATMOSIA PRAISE SAINT BUCK

**Comment by DesolateG** [comment]
I think I'd rather see +2 engineering over additional atmos.

**Comment by Kyep** [comment]
@DesolateG I considered that, but there is already an imbalance between Eng and Atmos slots, and I was not sure I wanted to make that divide bigger.

**Comment by davidchan13** [comment]
Why? Rarely if ever does engineering need more than four people to repair tator work. If it's bad enough to require more a shuttle ERT gets called.

Also curious why you would ever want or need more than three atmos techs.

**Comment by DesolateG** [comment]
Atmos doesn't need that many. 7/10 atmos techs don't do their job anyways.

**Comment by Kyep** [comment]
@davidchan13 @DesolateG I'd like us to be able to handle major damage without shuttle/ERT every time. We also BADLY need more job slots. Having more atmos techs can't hurt, and we need the slots.

**Comment by DesolateG** [comment]
I understand. I'm simply stating that most people who get atmos fuck off and don't do atmos at all, meanwhile those that do can't due to all the equipment being taken by the shitters. 

It's a surprisingly small department that does better with smaller numbers.

**Comment by davidchan13** [comment]
I can applaud the idea of more slots and more responsibility on the crew to maintain the station instead of abandoning ship the second she leaks atmos.

BUT adding slots to a department whose job load is criminally low as is when its totally acceptable for the CE to take their department into space and never be seen again is not a good idea.

We already have a number of people who use it as an excuse to get free tools and greytide, which is bad enough by itself but is even worse when we limit the number of civilians based on sec roster, plenty of people just roll engine if assist isn't an option because there is no expectations or requirements

**Comment by Kyep** [comment]
I've never seen an issue with engies/atmos greytiding. Even if it happened, the solution is simple: demote them.
We need more job slots. Not just in Eng, but in every department. Eng/Atmos shouldn't be exempt.
We also need more events that damage the station, and give Eng/Atmos something to do. That discussion, though, belongs in the events PR, not here.

**Comment by DesolateG** [comment]
Why not just add it so we have 5 roboticists and 5 virologists while we're at it?

Atmos does not need this many people in it  just for the sake of more job slots.

**Comment by FreeStylaLT** [comment]
Boosting the slots of Engineering does not seem to be a good idea. I cannot be certain of this, but is there really a need for additional Engineers / Atmos Techs? 

Is the current amount, when full, not sufficient to maintain the station, especially given the unreliable and occasional nature of incidents that require more than one Engineer at a time?

I do not see much benefit from this other than artificially boosting how many people our station supports, which the current amount of slots fulfills well enough, when taking the current station's size and performance impact from a 100+ number of players actively playing into consideration.

**Comment by Kyep** [comment]
@FreeStylaLT 
Boosting the # of people our station supports is a worthy goal by itself. We can end up with 50+ assistants during ultra-highpop. There's huge scope for more slots.
That aside, "need" is an illusion. If we're concerned that an extra engineer/atmos won't have enough to do, we can simply increase the chances of the station-damaging anomalies, which would be more than enough to ensure they have work to do.

**Pull request closed without merging**
