### PR TITLE
Gave hop long-range fax

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
This PR changes the HoP's fax to be a long-ranged fax instead. Why, you might ask?

1. The HoP is the second in command of the station. Should the captain be incapacitated or go mad with power, it falls to him to run things or fax CC about a captain abusing his power, should there be no NT Rep or IAA around. The wiki page on the job does explicitly mention upholding the right of crew members. This is mostly relevant in low-pop rounds.
2. The duties of the HoP sometimes require a fax to CC. Examples include promotion to karma roles, hiring more clowns and other HR-style paperwork. It is pretty awkward to ask the captain to fax something for you.
3. The HoP already has access to the law office, since the IAA are (kind of) his subordinates, so he already has fax access, this just makes it more convenient for him to send faxes.

**Changelog:**
:cl:
tweak: Gave the HoP fax long-ranged faxing capabilities.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
The ID computer already colors karma jobs in green if the transfer is okay, or gray/red if not. The HOP never needs to fax CC for those.

They probably don't need to fax CC for clown slots either (the answer is always no).

The other reasons seem valid, though.

**Comment by TDSSS** [comment]
Right, I forgot the ID computer does that now, the wiki should probably be updated on that, since it still mentions faxing.

There's still probably a few other job slot related faxes the hop can send. Maybe if a command member is missing and can't be recovered, they can fax to ask for another job slot to be opened, for example.

**Comment by SomeSortaSquid** [comment]
Missing command members should probably be reported by the captain or representative. Since, you know, they're sort of responsible for ensuring each department has a head, be it proper or acting one.
If the captain is missing, you are an acting one and you are allowed to use their long-range fax.
Now that karma jobs are obvious, there's no reason for HoP to interact with the Central Command. They are a direct subordinate of the captain and, as such, they don't need a direct line of communication with it.
Captain going mad with power can, and should, be dealt with station-side. It's much more fun and engaging than asking admins to magically solve the issue.
Finally, HoP office is already a popular greytide spot. I believe making assfaxing possible would increase the amount of break-ins. And, very rarely, HoP will succumb to this temptation themself.

**Comment by Crazylemon64** [comment]
This only adds the fax to the boxstation map. Also, why are there modified space tiles?

**Comment by TDSSS** [comment]
Yeah I didn't want to touch any of the other maps, since I think someone else is working on them and they're also not really being used?

The mapmerge script changed the space tiles by reordering stuff somehow, I don't know why it did that but it shouldn't change anything.

**Comment by variableundefined** [comment]
We approve this PR, but conflicts need to be solved and there's multiple map editing PR waiting at the moment, I apologize for any delays.

**Comment by TDSSS** [comment]
Uh, nevermind that. Stupid map merge... A tad too many file changes

**Comment by TDSSS** [comment]
There we go, that should be ready to merge now @variableundefined

**Pull request merged**
