### PR TITLE
Shadowling Fixes

### PR DESCRIPTION
**Pull request by TheDZD**
- Fixes shadowling thralls not showing up on Check Antagonists.
 - Also adds vampire thralls to Check Antagonists
- Fixes veil ability not turning off hardsuit helmet lights.
- Fixes shadowling hatch dropping organs.
- Adds job such as blueshield, NT rep, and pod pilot to the list of jobs  that cannot be shadowlings, I had this previously but accidentally nuked it when I was reverting other changes.
- Remove ascended shadowling commune, transfers the shadowling's languages to the ascendant instead, meaning they will have the regular shadowling hivemind.
- Fixes intercept not being sent to the station on shadowling rounds.
- [x] Fixes ghost AntagHUD not showing an icon over shadowlings.
- Shows (Shadowling) or (Shadowling Thrall) before messages in the shadowling hivemind.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
probably also check AntagHUD for shadowling_thralls also

**Comment by Regen1** [comment]
Make sure veil turns if things such as lamps from mining etc

**Comment by Earthdivine** [comment]
That would depend on if our lamps are electric or gas, Regens, since Veil isn't supposed to work on non electric sources which is why Flares are immune to it.

They probably are electric but eh, would like some more stuff to be immune to it, assuming I'm talking about the right power.

**Comment by wotan90** [comment]
I would also suggest to make it obvious if a shadowling is speaking in hivemind or a thrall. Something like this:
Shadowling Hivemind, Thrall Ian McDog: "Can i suicide?"
Shadowling Hivemind, Shadowling Urist Shadowworth: "Do not dare to suicide you little worm!"

**Pull request merged**
