### PR TITLE
Bumps up traitor telecrystal count to 30

### PR DESCRIPTION
**Pull request by monster860**
Antags have gone through too much nerf.

:cl: monster860
tweak: Traitors now have 30tc
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Can we do TC based on starting profession instead

**Comment by FreeStylaLT** [comment]
Oh dear this can't happen without a full rebalance of all the items prices

**Comment by Regen1** [comment]
Why not 40?

**Comment by monster860** [comment]
@Regen1 That would kind of be pushing it.

**Comment by Lady-Luck** [comment]
As an example, off the top of my head:

CMO, CE, HoP, RD, Scientists, Roboticists would have the lowest TC, 20.

Chemists, Engineers, Atmos, Quartermaster would have a medium TC, 25.

Everyone else would have the highest TC, 30.

**Comment by Regen1** [comment]
@monster860 naaa buddiiiii

It's not like our current TC count is based of a balanced gear cost or anything

**Comment by Lady-Luck** [comment]
Jeez louise these downvotes. I think the idea needs work but I am confused by the kneejerk reaction given that traitors are relatively weak right now.

**Comment by Mijhead** [comment]
:fire: :fire:

**Comment by tigercat2000** [comment]
Traitors are fine.

**Comment by FreeStylaLT** [comment]
Nothing like being able to buy sleeping carp and a chainsae

**Comment by Lady-Luck** [comment]
>Traitors are fine.

Curious how many people agree with this.

**Comment by monster860** [comment]
Last I checked, the only way to success as traitor is to be an RD/scientist and to powergame the shit out of your items.

**Comment by Lady-Luck** [comment]
bags of holding op

**Comment by TullyBurnalot** [comment]
@monster860 Plenty of traitors accomplish their objectives without once touching Science.

They are not as underpowered as people want to believe they are.

**Comment by Earthdivine** [comment]
Traitors are fine, other antagonists need help more then they do (Vampires come to mind). Allowing 30 TC is just a huge improvement to Traitors to the point you will see combination of Sleeping Carp/HoloParasite/Chainsaw with a side of Emag being more prominent based on the objective. This is just making Traitors into Nuclear Operatives more then anything.

If there is need to help antagonists, upping their buying pool is not to the way to go and is a bandaid that would just need to be ripped off later.


And plenty of traitors succeed without Science. Just because you don't see them doesn't mean it doesn't happen.

**Comment by Regen1** [comment]
>People are downvoting a change that they don't like, what a kneejerking reaction!!!!!

@Lady-Luck grow up, it's not a kneejerk just because people is against it, the fact that there's "so many downvotes" might also show that it is you who are wrong, not everyone else.

**Comment by monster860** [comment]
Sure, if you're *really* good at the combat system, you could succeed as a
non-scientist. However, *some* people suck at combat in this game.

**Comment by TullyBurnalot** [comment]
@monster860 Not all antagonist action is based on combat.

**Comment by Earthdivine** [comment]
It's a good thing combinations like Sleeper pen + Syndibomb/ESword for instant death, Emag and Ai-Watching Multitool for stealing, Ebow-Mind Slaving someone else to do it and other ways of neutralizing targets are in the game that's not entirely focused on combat.

**Comment by Alexshreds** [comment]
So this is 100TC worth of gear in surplus crates. gg folks gg

**Comment by Lady-Luck** [comment]
>So this is 100TC worth of gear in surplus crates. gg folks gg

those crates fucking suck. I bought a lot of them on my private server and did the math, they everaged at around 22 TC and there was rarely ever a good combo in them. The bundles were even worse.

**Comment by TullyBurnalot** [comment]
@Lady-Luck Bundles at least are static. Surplus Crates are for true madmen.

**Comment by Lady-Luck** [comment]
>@Lady-Luck Bundles at least are static. Surplus Crates are for true madmen.

Out of the 10 or so I got, only 1 was any good. I would gladly get them every round I was traitor if they just weren't so godawful.

**Comment by tristan1333** [comment]
Traitors are just fine without rules, with rules though... They're on the weak side

**Comment by Fox-McCloud** [comment]
You could purchase the surplus crate with this AND still purchase 1 of just about whatever you wanted.

THis is OP as hell.

**Comment by Alexshreds** [comment]
> those crates fucking suck. I bought a lot of them on my private server and did the math, they everaged at around 22 TC and there was rarely ever a good combo in them. The bundles were even worse.

Every time I've used them I am never disappointed. Once I got the telegun as an engineer and killed both my targets within a 10 minute span at the blink of an eye. Another time I was made traitor after getting permaed, needless to say the perma brig exploded three different times and Jay got mad at me for cuban peteing everyone inside. Another time I didn't even need to do a single thing with all the gear I bought just being a medical doctor.

**Comment by Regen1** [comment]
>getting mad at a random gear box

I'm sorry did you not understand what random means?
We didn't design it to be good and always suit your needs.
Sometimes it's good for you and you can make it work, other times you have to bite the bullet.

**Comment by Lady-Luck** [comment]
>I'm sorry did you not understand what random means?
We didn't design it to be good and always suit your needs.
Sometimes it's good for you and you can make it work, other times you have to bite the bullet.

I'd have better luck at the casino than with those crates.

**Comment by Spacemanspark** [comment]
And?

**Comment by Lady-Luck** [comment]
They suck.

**Comment by Spacemanspark** [comment]
I've gotten some great things from them.

**Comment by TheDZD** [comment]
I'm not sure what more you want from a box that gives you 50 TC worth of random traitor items other than it automatically giving you greentext.

**Comment by Lady-Luck** [comment]
>50 TC worth of random traitor items

it doesnt do this

**Comment by TheDZD** [comment]
> it doesn't do this

[It most certainly does.](https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/uplink_item.dm#L1297-L1323)

**Comment by Lady-Luck** [comment]
I don't know what to tell you other than I bought several on my test server and it averaged around 22 TC with a bunch of junk items.

**Comment by Doukhan** [comment]
More toys pls.

The cost of gear should probably be looked at in line with any TC changes though, the current amount is apparently very finely "balanced".
Antags of all stripes tend to lose but that's got more to do with who is playing as/against them more than anything else IMO.

@Lady-Luck The crates are very random, they're usually worth it for me.
Except when you get two chainsaws and some syndie soap, that's the beauty of them.

**Comment by GeneralChaos81** [comment]
@Lady-Luck Those insulated gloves were 10TC electro gloves.

**Comment by Lady-Luck** [comment]
>Those insulated gloves were 10TC electro gloves.

...huh. so everything in the crate is a traitor item? I thought it was just tossing out junk.

**Comment by Earthdivine** [comment]
@Lady-Luck Correct, the Crates give you a total 50TC of any traitor gear, including things that are job specific.

**Comment by fludd12** [comment]
So, why not just... increase the cost of the surplus crate? It *was* meant to take up ALL of your TC.

**Comment by KasparoVy** [comment]
Telecrystal inflation?

:money_with_wings:

**Comment by IcyV** [comment]
Traitors need more tools to accomplish their goals. They don't need more points to buy what tools are already available. There aren't exactly a ton of viable buys if you want to do anything more than goof off or hope to god that you don't get meta'd or powergamed to hell by the crew (which is guaranteed).

**Comment by tristan1333** [comment]
As I said, with rules traitors are pretty weak and hard to play. Changelings are alot easier thanks to powers + they can basically do what they want without as much worry about overhead admin stuff.

**Comment by Rumiluntti** [comment]
git gud. That's all

**Comment by monster860** [comment]
Easy for you to say, you don't have to deal with lag caused by being *very*
far from the server.

**Comment by Rumiluntti** [comment]
Buffing shit because people might suffer from lag? Seems reasonable.

**Comment by Da-Dman234** [comment]
> Buffing shit because people might suffer from lag? Seems reasonable.

For the sake of fairness, all NA players now by default start as a hulked scientist and get 40 telecrystals whenever they roll traitor, you know, cause lag.

**Comment by KingPhilipIII** [comment]
If you ask me, if you can't accomplish your objective with twenty crystals you're doing something wrong or you need a better plan. I've hijacked the shuttle with just an energy dagger, an Emag and a mind slave, and it wasn't through emagging the doors shut. 

People need to be more resourceful. With regards to the crate, I love it. Unless I need a very specific set of tools for my plan I always buy it. That's how I got a briefcase of syndie bees, an energy sword, an ebow and an Emag. It was a glorious shift for me and a bloody shift for the two security officers that made up Sec.

**Comment by Fox-McCloud** [comment]
This isn't going to fly.

**Pull request closed without merging**
