### PR TITLE
Fancy shmacy new hairstyle

### PR DESCRIPTION
**Pull request by FishStix4Dayz**
**What does this PR do:**
A Simple update to my hairstyle I made, added lots of detail to make the Admins happy, even though they already approved of it
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
conflicts.

Also, did you ever bother fixing up the other hairstyle I told you to?

**Comment by FishStix4Dayz** [comment]
it has conflicts because it uses an older fork of the code, and no, i did not update this myself, i had help from another person, i will not take their credit

**Comment by Fox-McCloud** [comment]
Then why didn't you credit them?

**Comment by FishStix4Dayz** [comment]
Cause i dont know there name

**Comment by FishStix4Dayz** [comment]
Fox, how can i fix my conflict so you can merge my update?

**Comment by variableundefined** [comment]
The sprite was already improved previously, and I don't see a need to further modify the hairstyle. When it was submitted it was very dull and unshaded and the name seemed to be a self-insert of a character. Merging it in was a mistake in the first place.

In addition, we would no longer accept further contributions from you, due to your snarky and disrespectful attitude from your previous attempt to update the hairstyle, in addition to your lack of skills. During all three PRs you demonstrated that you are not competent enough to do this on your own, and when you were given help, you were unable to give due credits to people who helped you - If I am correct in guessing, it is Nicaragua1 who helped you. Frankly, after multiple hours was spent in an attempt to get you to follow basic instructions for your first PR, I have no confidence you can be a successful long-term contributor to the codebase at all.

**Pull request closed without merging**
