### PR TITLE
Dynamic HUD

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This paves the way for a better transition to 15x15, but is still useful if that gets shot down.

Dynamic HUD Support

- Fixes a number of HUD item locations so they're DYNAMICALLY based instead of based on a fixed location. This means that depending on the size of your screen, certain elements will always be in their proper spots and centered around the correct location. It also makes things like Dither (welding mask) and flashes properly scale with screen size

Pics of this in action:

15x15

29x29

- As you can see, the HUD elements are perfectly placed, despite the huge difference in number of viewable tiles. There's one thing it doesn't scale though, and that's the damage indicator, O2 "tunnel", and blind/in-crit images; those are static, unfortunately (and you can tell by the brute damage overlay).

Related

- Removes some outdated title screens
 - The current title and the old 480x480 title both remain

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
*Removes all unused title screens

Does this mean I won't be able to set the title screen to a rad wizard floating in space in a car?
Because that's disastrous.

Otherwise, I support this change, especially if it will allow change view range to function properly when shrinking the range.

**Comment by Fox-McCloud** [comment]
@FreeStylaLT 

Nah, you can still do that; this is some title screens taht are in the misc. folder (the old clown one, the pony one, and some others).

**Comment by fj45** [comment]
If its this or the lighting overhaul, ditch the lighting overhaul. (Sorry tiger)

Still can't really support this.

**Comment by ZomgPonies** [comment]
:-1: I just started talking directly with Lummox about our crashing issues. This feels like piggybacking on a problem everyone knows about (lighting) to merge in something the majority doesn't want (small viewsize).

**Comment by Krausus** [comment]
I thought the balance of opinions on this change were already tipped in favor of "no" after the previous PR. I know I'm still in that camp.

> Haven't been able to crash with this, but that's hardly scientific.

If the crashes could be reliably reproduced, this could be tested by simply reducing your view range on the live server. They're not reliable, though, and I'm not sure if they even can be reproduced on a local server with minimal latency.

> That said, this is 65,536 less pixels being rendered/displayed to clients, so it WILL help with client-lag, I just don't have an scientific measure of how much.

That's... not really how it works. The cost of actually pushing pixels is negligible, even if you somehow don't have graphics acceleration; even if it wasn't, people who run stretched will be rendering the same number of pixels anyway.

What matters more are tiles - someone who jumps to a fully unloaded area will need ~22% fewer tiles sent to them, and someone simply walking in one direction will load ~12% fewer tiles (though unless they're moving incredibly fast, they won't be loading many tiles anyway). Depending on how Byond handles sending out tiles, though, the actual number of tiles may very well matter much less than a client's latency to the server.

Trying to solve the crashing by reducing the number of tiles loaded is pointless anyway - Byond simply isn't supposed to be crashing, and Ponies is in talks with Lummox (main Byond developer) to try and sort out what's causing it. This would be a permanent solution to a temporary problem.

**Comment by ZomgPonies** [comment]
Here is the BYOND post related to this issue: http://www.byond.com/forum/?post=1866730

Lummox has been contacted, I expect feedback from him very shortly. If you want to contribute, provide more of these crashlogs from Windows Event Manager when your game crashes. Until then, this PR shouldn't be merged.

**Comment by Fox-McCloud** [comment]
The performance thing was a minor reason for the PR to begin with; it was brought up as a hypothetical when you specifically mentioned it as being a supporting point for it until you brought it up and requested metrics for it: https://github.com/ParadiseSS13/Paradise/pull/1231#issuecomment-107103517
https://github.com/ParadiseSS13/Paradise/pull/1231#issuecomment-107315081

While the PR may still not get merged in, due to lack of support/opposition, it shouldn't be based around the crashes, as that's not even why this PR was made by DZD to begin with, nor was it any of the supporters primary argument's for it.

**Comment by ZomgPonies** [comment]
Indeed, but right now unless people read back to the previous PR and it's comments, it appears that the sole advantage of this PR is a hypothetical performance boost, so that's what I was commenting on.

**Comment by tigercat2000** [comment]
First question, why remove the unused title screens? Are unused icon files so big that we have to delete them? I don't see any reason to remove them other than "because".

Second question, why make the title screen the sign screen again? Is it so difficult to resize our current lobby image and put it there?

**Comment by Robertha89** [comment]
I'm actually suprised that you forget the real issue behind lag, it is not the amount of pixels that count, it is the amount of objects, set your view range to 64 in the station, and it will go slow, set it to 64 in space and it will be okay, but look weird due to pixel distortion. 
So reducing the range by 1 would not have any big effect at all, cause if the botanist got 10000 bananas, and suddenly the singularity and server crashes.
Removing icons and sounds seems kinda pointless, because, correct me if im wrong, say the old singularity icon set that's about 15-20 mb, it will not cause any performance issues unless it's used ingame?
And as far as i know, the current performance issues are caused by the new lighting system that still needs an unknown fix.

**Comment by Earthdivine** [comment]
Already said I would give a :+1: to this if it was made sure this was a super smooth transition.

In my own opinion this is 100% preference now rather then anything really technical

**Comment by Spacemanspark** [comment]
No.
:-1:

**Comment by KasparoVy** [comment]
Yeee '+1'

**Comment by ZomgPonies** [comment]
From the latest discussion on the Staff skype chat, here are the vote numbers:
1 maintainer for, 1 maintainer against
1 headmin for, 2 headmins against
2 staff coders against
1 admin for, 1 admin against

Unless there's a large player majority in favour of this change, I don't see it getting merged.

**Comment by KasparoVy** [comment]
I wish the UI scaled (say a guy chose to go 64x64, it wouldn't rekt the buttons). That'd be a satisfying compromise, letting a player choose-- but IDK if it's even possible to implement that.

**Comment by Robertha89** [comment]
technically it is, there is a verb called Change-View-Range which changes your view range from 1-128 i believe, making a new verb limited to either 15 or 17 would not be too problematic, but the ui does not scale with view range automatically, so there is that.

**Comment by KasparoVy** [comment]
Yeah, in practice that's the same as choosing 64x64-- atleast with my rez. It drops a square of view range.

if only ui scalign!1

**Comment by Robertha89** [comment]
UI Scaling would fix the issues with Marauder, and L.W.A.P too...

**Comment by fj45** [comment]
Kas, thats untrue, it is easy to tell if a server has an extended view distance.

**Comment by KasparoVy** [comment]
Sorry I was unclear, what I meant to say is that from my point of view as a player running at 1080p, using 64x64 setting produces the same 'view distance' as 15x15 tile-- 15 tiles view distance, but with 64x64, it produces UI scaling issues on servers that have view distance greater than 15x15.

**Comment by Fox-McCloud** [comment]
even if the UI scales properly (it does on TG), there's still one very glaring problem: overlays aren't scalable.

**Comment by ZomgPonies** [comment]
Wait. Could they though, with a proper application of scale? I'm jsut drunk spitballign here though.

**Comment by Fox-McCloud** [comment]
Added in dynamic HUD scaling, like what TG has--meaning if youre view range is 15x15, the HUD elements are all centered and in-place---if you have 29x29, then the HUD elements will still be centered and in their proper spots---currently this doesn't happen and your HUD elements end up staying static at a single location (on live).

**Comment by Robertha89** [comment]
How about a stretch to fit for things like being in crit, near blind, etc, would that be possible to do too? Or is it included?

**Comment by Fox-McCloud** [comment]
Went ahead and updated the initial description to better match what this PR does, exactly.

Basically, even if 17x17 falls through, having dynamic HUD is a VERY VERY good thing as it means that we never have to fiddle with proper scaling of HUD elements again---and if we should decide, in the future, to go with 15x15, it would literally involve changing 4 files.

**Comment by Robertha89** [comment]
how about being able to switch between the two sizes by making a new toggle verb?

**Comment by Fox-McCloud** [comment]
There's no point to that unless the overlays scale--otherwise players will pick one or the other based on specific situations rather than personal preference.

Also a number of things are hardcoded to by by world.view---so having one be default over the other (but being able to wratchet it up) could potentially cause some issues.


That said, the biggest thing is scaling of the O2+Burte+Blind overlays.

**Comment by tigercat2000** [comment]
I will support the scalable HUD, but not the view range change. I would request that you move the dynamic HUD things to a different, uncontroversial PR.

**Comment by ZomgPonies** [comment]
Indeed, please split view range change from dynamic HUD, as one is controversial while the other is not.

**Comment by KasparoVy** [comment]
humungous +support to dynamic view range change, thanks loads for implementing that

**Comment by tigercat2000** [comment]
This PR probably should not be deleting the fullscreen.dmi stuff.

**Comment by Fox-McCloud** [comment]
There's only one I removed that's compatible with 17x17 and that single one is one that we're unlikely to use again because it's a giant clown face and it bothered a few people; I suppose I could probably remove the sign one, for consistency's sake though as it's not compatible with 17x17 either.

Unlike the singularity sprites and stuff (which were moved instead of delete), these *don't* have a prospect for future use (especially with the art contest coming up), and the nature of splash screens means any admin with var edit can easily throw up a customized image for April Fools or other holidays..meaning having them stored centrally on the codebase is redundant and unnecessary.

**Comment by KasparoVy** [comment]
idc so long as i can 64x64 setting (top left corner of screen) and have it scale :B

**Comment by ZomgPonies** [comment]
Looks good

**Pull request merged**
