### PR TITLE
[Should] Fix "Cyberiad: Maintenance Rework [Part #1] (Fixed merge issue)"

### PR DESCRIPTION
**Pull request by Venuska1117**
-- ! Test Merge before Merging ! --  (just in case something broke again)
 
## What Does This PR Do
This PR Fix mapping issues from #20648

## Why It's Good For The Game
Pipes are now connected to system with should not create more issues.
And map part got copy-pasted to actuall map, so there [should] not be more issues.

## Images of changes
image
image

## Testing
Compiled and Runned, didn't get crash notification from VSC.

## Changelog
:cl:
fix: Fixed problems related to the Cyberiad maint rework
/:cl:

### CODE REVIEW

**Comment by Venuska1117** [comment]
New Branch to be sure it fix issues from #21038

**Comment by Venuska1117** [comment]
@SteelSlayer Should be fixed for now, so it can be now test-merged

**Comment by SteelSlayer** [comment]
Testmerge started.

**Review by SteelSlayer — APPROVED** [review]
TM'd for a few days with no issues reported, or that I could see myself.

**Pull request merged**
