### PR TITLE
Nanotrasen Career Trainers + Procedure Department

### PR DESCRIPTION
**Pull request by matttheficus**
## TODO Stuff
- [x] Finish the Job Datum
- [x] Get mentor/admin-only working
- [x] Vendor for Basic Departmental Equipment
- [x] Give them `ACCESS_TRAINER`
- [x] Create a mechanic to temporarily give access that matches their mentee [NCT Access Chip!]
- [x] Sprite the NCT Trainee Access Chip
- [x] Finish the outfit code-wise
- [x] Finish the outfit sprite-wise
- [x] Fill the Vendor with Berets + Basic Uniform
- [x] Ensure Procedure functions as its own Department
- [ ] **GET JOB PREF/SELECTION TO WORK AHHHHHHHHH**
- [ ] Map in a place for them to work
- [x] Create SoP for the NCT
- [x] Move all Procedure Department SoP to their own file/page + prune from other SoP
- [ ] [TDB] Create a pop-up for new players to inform them of IC (NCT) and OOC (F1 > MentorHelp) to assist in learning the game.

## What Does This PR Do
Adds Nanotrasen Career Trainers + makes Procedure its own proper Department under command of the Captain.

This role functions as an IC way for Mentors to assist in teaching new players how to play the game/how to do their jobs in a more natural and personal way. They act as the other side of the coin to the IAAs, helping TEACH new players instead of looking for chaos/SoP breaking.

They will be mindshielded and stand out from the rest of the Crew via a special Mantle that they wear at all times while on duty. ~~They will also be coded as an "off-station role" so that their main focus is well and truly on teaching others and NOT getting converted/rolling antagonist.~~

They are provided with a NCT Data Chip, which allows them to copy the access of their scanned Trainee's ID. This chip ONLY works for the registered NCT. When you scan a new ID, it removes all of the old access.

## Why It's Good For The Game
This was something that just very recently got discussed within the Staff Team and there seemed to be large interest in it.

Im pulling a LOT of stuff from #13398 as well as stuff that was pondered by Staff.

## Standard Operating Procedures [WIP]
`1. NT Career Trainers are to wear their company-provided uniform and jacket at all times while on duty. They are free to choose a beret that best matches their primary field of knowledge if they so desire.`

`2. NT Career Trainers are to be available to all Crewmembers, regardless of Department. You may not only assist a singular Department.`

`3. NT Career Trainers are to use NCT Data Chips only to assist in the training of prospective Trainees. They are not to do a Trainee's work for them - they always strive to improve a Trainee's knowledge and skills.`

`4. In the event of a lost or stolen NCT Data Chip, the NT Career Trainer is to report the incident to their local Nanotrasen Representative or Station Captain.`

## Testing
TBD

## Changelog
:cl:
add: Adds the Nanotrasen Career Trainer.
tweak: The Procedure Department is now a full Department under the purview of the Captain.

/:cl:

### CODE REVIEW

**Comment by Onyxarias** [comment]
Wow uhh, holy crap, I love this. Will absolutely make for some chill, worthwhile mentor rounds.

**Comment by Christasmurf** [comment]
What sprites would you need for this role?

**Comment by Miraviel** [comment]
I volunteer as a tribute for the mapping part

**Comment by silverplatedelta** [comment]
One thing I will suggest real fast is that the procedure department should report to the NTR. I've always seen procedure as oversight of the station, and should not directly report to anyone on it. There's a bit of a conflict of interest in reporting to someone to may well be investigating. 

Other than that, I'm really glad to see this PR being developed!

**Comment by matttheficus** [comment]
> One thing I will suggest real fast is that the procedure department should report to the NTR. I've always seen procedure as oversight of the station, and should not directly report to anyone on it. There's a bit of a conflict of interest in reporting to someone to may well be investigating.

I'm considering Procedure to be a rather "special" Department. The Captain is still the defacto "Head" of it, but the Magistrate and NTR both have access to the Departmental Accounts.

The NTR shall overlook and manage the NTCs and the Magistrate shall overlook and manage the IAAs.

**Comment by OctusGit** [comment]
Respectful and though out criticism coming through. I'm not entirely a big fan of the concept of having IC mentor roles, this role lacks any weight or necessity to exist, when the system we already had worked fine, My main concerns are-

1. How frequently do new players' hands have to be held? New players exist and need some form of guidance, but I'm pretty sure it's not something that needs a constant in-round presence. I find it hard to believe that a role is necessary to teach the basics of a job when most of the teachings are already on the well-structured wikis. Are you telling me new players struggle to read or access our wikis? Most of the time mentor roles are asked singular questions, we don't need a role when a majority of the time their niche or quick answers, new players exist but I don't need a mentor to exist in the game and help me with something when they can just quickly answer my question or point me to the wiki with the all the information I need. The point for this is I think making an entire role with systems and extra work to teach "new" players is weak and unnecessary. Asking for help naturally in-game already existed before mentors roles, it was called, communicating with your department or other people in the game to help you. 

2. I don't like the idea that a singular role is given exclusive privileges because its existence encourages people to become a mentor for the role first, and to help as a secondary, which is a bad mentality. Admin roles are the exception because they have more responsibility, and a lot of authority because they are referees in the sense, but mentors? Aren't they just supposed to be knowledge players with occasional input for questions? My issue is giving mentors this role is going to become more a flex than a useful tool for "new" players, it's going to lead to problems I've seen in other communities where whitelist perms form a sense of superiority among mentors, which I am strongly opposed to. Mentorship never had this problem because the rank didn't have much weight or benefits, at most you got a color name and the ability to take questions. Now with the addition of a role that has antag immunity because it is technically off-station, and exists to orbit people for rounds to teach them comes off as incredibly snowflakey. Essentially a privileged assistant that only is obtainable from a whitelist system. Procedure or not.

3. The current system for mentorship works fine, I know innovation and new features are always going to exist in an open-source game, but I think this is the wrong approach we should take for it. Instead of making a new role, completely changing how some departments work, new sprites, and the issues that I elaborate above will arise if this PR is merged, why not simplify it to something less that achieves what you're looking for without uprooting so much, some alternatives that wouldn't have these issues could be-

- I heard this from somewhere and it was referenced to goon, the idea of having a small pet rat that only the mentor and questioner can hear or communicate to via psionics. The rat isn't necessary aside from answering questions. It doesn't need a role, doesn't need too much maintenance or work in terms of mechanics and sprites, and isn't as impactful as having someone essentially be the adoring fan from Oblivion. It's not as natural as the goal of this PR, but there is a potential for roleplay between new people and the new friend on their shoulders.

- We could just make an already existing feature better that is supposed to help players, it's called PAI's. They exist for a reason. Their whole point is to be personal AIs that help and interact with you in the game. Why not push PAIs to be more focused on being a more natural form of mentorship? A majority of the players who play that niche role have a habit of being very intelligent and helpful people. It just feels like we're ignoring a similar system we could work on and improve instead of adding more role bloat to the game. PAIs did this issue fine before, the issue is they felt aimless and directionless. We should have an ability for new players who need actual mentorship to be given free PAIs to an actual mentor help them. You get natural dialogue, a teacher, and a role that doesn't suffer from potential issues that come from whitelist.

Closing thoughts, I am probably in the minority of all this, I know my opinions have no weight to whether this PR is merged or closed, but I believe my points are valid, and I think that this PR is unnecessary as a whole and we should avoid this route and pursuit simpler less impactful options.

**Comment by matttheficus** [comment]
> How frequently do new players' hands have to be held? New players exist and need some form of guidance, but I'm pretty sure it's not something that needs a constant in-round presence. I find it hard to believe that a role is necessary to teach the basics of a job when most of the teachings are already on the well-structured wikis. Are you telling me new players struggle to read or access our wikis? Most of the time mentor roles are asked singular questions, we don't need a role when a majority of the time their niche or quick answers, new players exist but I don't need a mentor to exist in the game and help me with something when they can just quickly answer my question or point me to the wiki with the all the information I need. The point for this is I think making an entire role with systems and extra work to teach "new" players is weak and unnecessary. Asking for help naturally in-game already existed before mentors roles, it was called, communicating with your department or other people in the game to help you.

IC learning is one of the best and most engaging ways to learn in SS13. A role to assist in this, as servers like CM for example have with Senior Enlisted Advisors, is a fun and engaging way for people to get help with learning the game. It also fosters good RP by allowing new players to learn in a more grounded way than going back-and-forth from a mhelp chatbox or the Discord.

> I don't like the idea that a singular role is given exclusive privileges because its existence encourages people to become a mentor for the role first, and to help as a secondary, which is a bad mentality.

I dont see this as an issue. If you want to help new players, become a Mentor. If you think there are Mentors that are using their status as a clout-stick to hit people with, do tell the CMs/Heads, as they should be removed from Mentorship.

However, I see the issue with the Off-Station bit and will remove that. The mindshield should be enough of a deterrent.

> We could just make an already existing feature better that is supposed to help players, it's called PAI's.

The average new player to Paradise has no idea what a pAI is. The average regular player does not interact with them at all. That, and I really dont care for expanding the pAI role as I dont believe they can do as well of a job of teaching a job as an actual person can.

**Comment by matttheficus** [comment]
On the topic of a whitelist instead of Mentor-only.

We have a whitelist for the Role. Its called being a Mentor.

The requirements for being a Mentor are IMMENSELY simple:
- Have Departmental knowledge.
- Be in good-standing with the Community.
- Be someone we want representing Paradise to new/regular players.
- Be an active player.

None of these requirements are difficult to accomplish. I did so within my first year of coming back to Paradise in 2020. If we had a whitelist, it would just be exactly these requirements anyway.

**Comment by matttheficus** [comment]
## Sprite Time!
image
image
image

## TODO Stuff to Go
- Beret (will likely copy the Captain's White/Gold beret)
- MAYBE a White/Gold NT Flag for their Office

**Comment by Landerlow** [comment]
I love this idea but personally I think that the NTR should be the direct superior to the NCT's. It's literally in the name. The captain is the head of the station, yes. But the trainers are sent by Nanotrasen and the NTR makes sure NT's interests are met. It would also give the NTR something else to do/keep an eye on.

**Comment by matttheficus** [comment]
> I love this idea but personally I think that the NTR should be the direct superior to the NCT's. It's literally in the name. The captain is the head of the station, yes. But the trainers are sent by Nanotrasen and the NTR makes sure NT's interests are met. It would also give the NTR something else to do/keep an eye on.

The NTR is the direct superior to the NCTs. The Captain is simply the "Head" of the Procedure Department, as their main job other than being the Head of the Station is ensuring it is functional and well-run.

The NTR and Magi share responsibility as "pillars" of the Procedure Department, with the NTR keeping an eye on the NCTs and the Magi keeping an eye on the IAAs. The Captain being the Head is mostly due to the Magi/NTR not truly being a direct part of the Command structure.

**Comment by matttheficus** [comment]
# Waiting on #22439

**Comment by matttheficus** [comment]
This has sat in draft for too long and I dont have time to finish it reasonably soon. Ill pick this up in a month or two once some other obligations are done - probably gonna just re-code it all since its so disgustingly out of date.

**Pull request closed without merging**
