### PR TITLE
Cyberiad: Maintenance Rework [Part #1] (Fixed merge issue)

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
This PR changes maintenances, this is part 1 with change one of three grouped maintenances
If it success, it will be expanded in next PRs

## Why It's Good For The Game
Change Shape of Maintenance and Add new "Atmospheric constelation" to maintenances giving more access for vent-crawl Entities.

Now maintenances are changed to be more interesting:

- Maintenances now offer mostly 2 paths to move, of course some of them require destroying intended walls.
- APC got moved from tunnel to nearby abandoned "gambling" room.
- If Area have "new maintenance air system", it will always contain APC inside designed room.

## Images of changes

-- Fore-Port Secondary Maintenance
-- Fore-Port Maintenance

In Game:
image

Old Image from Editor:
image
**There is new Image below in Discussion.**

_Previous PR's:_
#20396 

## Small Lore for this Change and one what will follow.
_After many years of station functionality, station was in many meteors storms, rebuilding and refilling lost air cost us a lot of money! 
We can't eliminate meteors storms, so we decided after many rebuilding to make maintenance with more walls (with lead to maze look) to stop meteors from reaching deeper parts of usable part of station.
Addionaly decided to create separate atmospheric system inspired by virology one, with allow for quick opening and closing air flow, with help with reducing oxygen lost and saving our money for next rebuilds!_

## Testing
Tested on Test server and it work.

## Changelog
:cl:
tweak: Cyberiad Fore-Port Maintenance has been updated to be more complex and rich in loot
tweak: Cyberiad Fore-Port Maintenance air system is now connected to the main air supply system
/:cl:

### CODE REVIEW

**Comment by Venuska1117** [comment]
New Image From Map Editor:
image

Removed around 50% of Random Stuff and changed spawning chance:
Grille: Maybe -> Often
Space Fungus: Maybe -> Often
Rusted Walls: Maybe -> Always

**Comment by Fox-McCloud** [comment]
Not a fan of how many hidey-hole areas this removes to be honest.

**Comment by Venuska1117** [comment]
> Not a fan of how many hidey-hole areas this removes to be honest.

image
Removed 50% wall grids, is this better?

**Comment by Venuska1117** [comment]
> Not a fan of how many hidey-hole areas this removes to be honest.

what "hidey-hole areas" it remove?
i think it have more than it have before?

**Comment by Venuska1117** [comment]
image

THIS WAS ADDED WHEN FIXING MERGE ISSUES

**Comment by Henri215** [comment]
image

These tiny shards are intended?

Tested it and i think it has too much of rust/grilles/space fungus, i would suggest swapping these for lower chances versions (and to decrease the amount of random grilles around since they do leave a broken grille when the roll is not successful).
image

**Comment by Venuska1117** [comment]
Changed Maintenance to Henri Suggestion:
image

Removed Few broken Grilles
Decreased Grilles to 5 on walkable paths

Set Grilles Chance to "Often"
Set Fungus Chances to "Maybe"
Set Rusted Walls Chance to "Maybe"

**Comment by Henri215** [comment]
Tested and the chances do look good now. 

Could you please update the changelog to this?
tweak: Fore-Port Maintenance has been updated to be more complex and rich in loot
tweak: Fore-Port Maintenance air system is now connected to the main air supply system

**Comment by Venuska1117** [comment]
> Tested and the chances do look good now.
> 
> Could you please update the changelog to this? tweak: Cyberiad Fore-Port Maintenance has been updated to be more complex and rich in loot tweak: Cyberiad Fore-Port Maintenance air system is now connected to the main air supply system

Thanks you, sen-sei 🙏

**Comment by Henri215** [comment]
I would remove those "maybe" rust, that wall is not connected to the maints and because of that doesnt have to follow the theme.
image

Good idea to change those guaranteed space fungus into "maybe" versions too? (there is a number close to 5 inside the maints).
image

Think by removing one more broken grille there it would make the total amount perfect.
image

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Venuska1117** [comment]
Please wait, i need to add henry suggestion (mentioned above this post)

**Comment by Venuska1117** [comment]
Done, it should be ready for merge, if any suggestion of change, please say it.

**Review by farie82 — APPROVED** [review]

**Pull request merged**
