### PR TITLE
Remaps the Delta AI Sat

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
Applies some remapping to the AI sat on Delta. The meat of this change is making a proper foyer area and adding a cycling airlock. Also adds intercomms to all the AI sat rooms, untangles the vents and scrubbers, and fixes a non functional pair of vents and scrubbers in the transit tube access area.

The power cable that connects the AI power grid to the station has been tweaked: there is now a larger gap in space, but a cable coil has been provided to bridge it. The foyer-side of the connection has also been mostly pre wired, with a single node needing to be spliced, this node has been helpfully marked with a yellow square showing the exact tile to lift.

## Why It's Good For The Game
The AI sat is superior.

I'm pretty sure that most non-maint rooms are supposed to have intercoms.

The new foyer being its own room means that a small hole on the other side of the satellite will not completely depressurise the airlock and transit tube area.

Having an actual airlock with cycling instead of a single door means that using it won't immediately start venting the AI sat's atmos.

The increased gap between the station power grid and the AI power grid means pulse demons need to actually gain power before they can survive jumping the gap to the AI sat. The wiring on the inside means it's also easier to connect to the station now when it's actually needed.

## Images of changes
image
image
image
image

## Testing
Compiled.
All the cameras worked.
Vents and everything worked.
It's airtight.
Airlock is good.

## Changelog
:cl:
tweak: Tweaks the Delta AI sat.
/:cl:

### CODE REVIEW

**Review by DGamerL — CHANGES_REQUESTED** [review]
image

Can you elaborate on this?

**Review by DGamerL — COMMENTED** [review]
image
Could you make this not a doubled wall?

**Comment by Fordoxia** [comment]
> Can you elaborate on this?

Elaborated.

**Comment by Fordoxia** [comment]
> Could you make this not a doubled wall?

Also done.

**Review by Sirryan2002 — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Comment by DGamerL** [comment]
!merge_upstream

**Comment by Fordoxia** [comment]
> !merge_upstream

Fixed airlock spawner access helper.

**Review by Burzah — APPROVED** [review]

**Pull request merged**
