### PR TITLE
Fix invincible spiderbots and cryo bags

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Fixes cryo bags not resetting properly: Fixes https://github.com/ParadiseSS13/Paradise/issues/1972.
2) Fixes invincible spiderbots (this must've been a thing for ages).

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Thank you very much, that invincible spiderbot thing was obnoxious.

**Comment by KasparoVy** [comment]
Tfw spider bot gets the nuke disk

Never dies

**Comment by Markolie** [comment]
Actually, if they'd hold the nuke disk they would die. They only didn't die if they had nothing in their hand due to a runtime.

**Comment by dagilbert** [comment]
Yay! Stasis curse is not gone xD

**Pull request merged**
