### PR TITLE
Seafood sprite updates

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
New seafood sprites!

## Images of changes
Three new fish fillet sprites that were originally from goonstation, the artist who created them, @binarysudoku , agreed to relicense them for our codebase/license (like a year ago. It took me a bit to get around to these files :P). Thus the three different types of fish we chop up now have distinct sprites!
image

I made a new salmon steak based on the above:
image

New sashimi sprite from Citadel Station:
image

And I made a new cuban carp sprite:
image

## Changelog
:cl:
imageadd: New seafood sprites
/:cl:

### CODE REVIEW

**Review by variableundefined — APPROVED** [review]

**Comment by variableundefined** [comment]
Great sprites

**Comment by matttheficus** [comment]
Thank god, salmon steak isnt caviar anymore ❤️

**Comment by iantine** [comment]
These are gorgeous. I love it.

**Comment by Carthusia** [comment]
yes! Cuban carp is fixed!

**Comment by variableundefined** [comment]
banned for making me hungry

**Pull request merged**
