### PR TITLE
Darkmode by default, disable status bar

### PR DESCRIPTION
**Pull request by dj-34**
## What Does This PR Do
Enables darkmode in chat and in stat panel by default for new players
Also disables status bar in down left corner by default, as we have screentip now

## Why It's Good For The Game
Most users use the dark theme wherever possible (so you don't burn your eyes out with flash), I just gave the option to stick with it as standard for new players. 
The status bar has been disabled so as not to clutter up the interface since we have screentip.
Also, all TGUI interfaces default to an unchangable "dark theme", so this would be a nice improvement towards matching.
No changes for old players, new players could re-enable everything if they want.

## Images of changes
image

## Testing
Tested on my local

## Changelog
:cl:
tweak: Darkmode is now default for new players
tweak: Disables status bar by default, because we have screentip now
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
> The status bar has been disabled so as not to clutter up the interface since we have screentip.

..what about players who don't use screentips?
Maybe remove it only if you have screentips enabled, if possible?

**Comment by Sirryan2002** [comment]
> Most users use the dark theme wherever possible

On what data/evidence are you making this claim? Dark theme is common but not ubiquitous, it may even be true that more users use light mode in-game.

I did contrast checking on the chat box. Unfortunately I have found that there are several accesibility issues with our styling in general regardlesss of theme While dark mode has improved contrast on Asay, Dchat, and certain radio frequencies, other default texts on light mode dwarf dark mode, you really can't beat black text on a white background.

**Standard LightMode**
Stat Panel: 21:1
Tabs: 18.42:1
Ext Link Buttons: 18.42:1
Header Text : 21:1
Standard Text: 21:1
Notice Text: 14.38:1
Danger: 3.99:1 **<- Fail**
Debug: 8.8:1
Common: 4.86:1  **<- Almost Fail**
Asay: 6.34:1 (fails WCAG AAA)
Dchat: 8.08:1

**Dark Mode**
Stat Panel: 8.2:1
Tabs: 9.02:1
Ext Link Buttons: 4.53:1 **<- Almost Fail**
Header Text : 9.02:1
Standard Text: 9.02:1
Notice Text: 5.32:1 **<- Almost Fail**
Danger: 3.05:1  **<- Fail**
Debug: 2.03:1  **<- Fail**
Common: 6.34:1  (fails WCAG AAA)
Asay: 13.15:1
Dchat: 11.35:1

Light mode is the standard acrossed the Internet, it's much more likely to ensure that web accesibility is being met and its easier on the eyes for people with antistigmatisms. It may be uglier in some aspects but it's the proper default choice. Light mode supports colors being able to pop more and won't get washed out when there's a ton of external light shining on the computer screen.

I'm not saying that it's stylistically better (I personally like the look of light mode in many cases), just that it's more performative and accesible for users. Such is why I don't really support this change.

**Comment by Alecksohs** [comment]
Holoparasite doesn't have Screentips yet and neither do many other things. No reason to get rid of the little status bar which takes up so little of your screen that I didn't notice it was missing until you said it was missing. Iunno, just keep that one in. As a darkmode enjoyer, I'd say keep lightmode Default. Unless you ported TG's Winforms DarkUI.

**Comment by Gaxeer** [comment]
> > Most users use the dark theme wherever possible
> 
> On what data/evidence are you making this claim? Dark theme is common but not ubiquitous, it may even be true that more users use light mode in-game.
> 
> I did contrast checking on the chat box. Unfortunately I have found that there are several accessibility issues with our styling in general regardless of theme. While dark mode has improved contrast on Asay, Dchat, and certain radio frequencies, other default texts on light mode dwarf dark mode, you really can't beat black text on a white background.
> 
> **Standard Light Mode** Stat Panel: 21:1 Tabs: 18.42:1 Ext Link Buttons: 18.42:1 Header Text : 21:1 Standard Text: 21:1 Notice Text: 14.38:1 Danger: 3.99:1 **<- Fail** Debug: 8.8:1 Common: 4.86:1 **<- Almost Fail** Asay: 6.34:1 (fails WCAG AAA) Dchat: 8.08:1
> 
> **Dark Mode** Stat Panel: 8.2:1 Tabs: 9.02:1 Ext Link Buttons: 4.53:1 **<- Almost Fail** Header Text : 9.02:1 Standard Text: 9.02:1 Notice Text: 5.32:1 **<- Almost Fail** Danger: 3.05:1 **<- Fail** Debug: 2.03:1 **<- Fail** Common: 6.34:1 (fails WCAG AAA) Asay: 13.15:1 Dchat: 11.35:1
> 
> Light mode is the standard across the Internet, it's much more likely to ensure that web accessibility is being met and its easier on the eyes for people with antistigmatisms. It may be uglier in some aspects but it's the proper default choice. Light mode supports colors being able to pop more and won't get washed out when there's a ton of external light shining on the computer screen.
> 
> I'm not saying that it's stylistically better (I personally like the look of light mode in many cases), just that it's more performative and accessible for users. Such is why I don't really support this change.

As person with astigmatism, I would say that light theme is not easier on my eyes, they hurt constantly.

**Comment by dj-34** [comment]
> > Most users use the dark theme wherever possible
> 
> On what data/evidence are you making this claim? Dark theme is common but not ubiquitous, it may even be true that more users use light mode in-game.
> 

I'm judging from the first polls I found on the internet [this](https://community.spiceworks.com/topic/2456118-light-mode-vs-dark-mode-which-do-you-prefer), [this](https://css-tricks.com/poll-results-light-on-dark-is-preferred/) and [this](https://www.reddit.com/r/TrashTaste/comments/yg5kgv/light_mode_vs_dark_mode_poll/), and my personal experience. 
In our CIS region (including Paradise fork 220 (ex666) & WyccStation) it is just a common thing that the majority of players here use exclusively dark theme. It was a revelation to me that on the official Paradise as it seems to me prefer a light theme. And that's weird to me, since you're already using half of the dark theme, on the TGUI interfaces.

**Comment by TrashDoxx** [comment]
I'm also astigmatic and dark theme better for me lol

**Comment by Sirryan2002** [comment]
https://www.boia.org/blog/dark-mode-can-improve-text-readability-but-not-for-everyone

There's a few different articles that discuss issues with reading text with an antistigmatism and potential further issues for those with dyslexia. If you like dark mode, so be it, but just have it as a switchover option, not the default.

Also, two of those polls are from tech heavy website or sections which have a serious sampling bias. I'm just not convinced that the casual player here fits into the same demographics.

**Comment by dj-34** [comment]
I think it's partly/fully solved in TGUI4 update

**Pull request closed without merging**
