### PR TITLE
All helmets now hide hair

### LINKED ISSUE #9472: Sec Helmet Doesn't Hide Vox Head Quills
**Problem Description**:
Your quills still appear even though you're wearing a helmet with a closed top.

**What did you expect to happen**: 
The Quills to not stick through the top of the helmet.

**What happened instead**:
Quills are not hidden by the helmet

**Why is this bad/What are the consequences:**
It looks weird, and doesn't make sense.

**Steps to reproduce the problem**:
Be vox, have quills, wear helmet.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was using Vox Quill Mohawk but it happens with other styles too.

### PR DESCRIPTION
**Pull request by 1080pCat**
## What Does This PR Do

Title, helmets hide hair now, as well as cleans up a tad of white space, and removes useless flags since the base item has the flag now.

## Why It's Good For The Game

Was bug reported back in 2018, quills and such poking through helmets look ugly as HECK too, so. this Fixes #9472

## Testing

Checked if i had hair when i had a helmet on, i was so very bald.

## Changelog
:cl:
tweak: Helmets hide hair now.
/:cl:

### CODE REVIEW

**Comment by spacegeese** [comment]
I felt a great disturbance in the Drip, as if hundreds of SS13 stylists cried out in horror and were suddenly not drippy anymore. I feel something terrible has been opened.

(this will be a very big issue for the non-bald security population)

**Comment by Onyxarias** [comment]
Security took my quills, can't have skrek in Nanotrasen

**Comment by Christasmurf** [comment]
further evidence that the helmet is the most non-drip item sec has

**Comment by 1080pCat** [comment]
> (this will be a very big issue for the non-bald security population)

I'm rather surprised people are iffy on this.. helmets not hiding hair has always been an annoyance for me personally, are people really THIS upset about needing to tie their hair up now?

**Comment by Somniworld** [comment]
> > (this will be a very big issue for the non-bald security population)
> 
> I'm rather surprised people are iffy on this.. helmets not hiding hair has always been an annoyance for me personally, are people really THIS upset about needing to tie their hair up now?

I'm mostly thinking about non-human species like Skrell, who can't exactly tuck 30m² of tendrils into their helmet, does the "block_hair" flag only applies to specific species? Furthermore, the stupidly long haircuts like "bedhead long" would not fit into a helmet no matter how hard you try I reckon.

**Comment by 1080pCat** [comment]
The push back on this caught me quite off guard, and after thinking about it for a bit, i think it might be best to close this until a better fix is put up.

**Comment by spacegeese** [comment]
honestly my comment was intended to be a joke but maybe you could make it toggleable, like how the hoodie is toggleable and hides hair
i was basing my comment on how ugly the hoodie makes people whos looks rely on their hair look but i think the helmet would look fine, but it being toggleable would make it much better for those of us who care about their hair

**Pull request closed without merging**
