### PR TITLE
Adds Unidentified Gas in Deep Space

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds an unidentified gas tank in deep space.

Go find it, fill up a canister, and experiment with it! See what it does, what creative new ways can you use it to ~~help the station~~ kill your fellow employees! 

:cl: Fox McCloud
add: Adds in unidentified tank filled with an unknown experimental gas in deep space. Find it and experiment!
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
Interesting...? :thinking:

**Comment by AffectedArc07** [comment]
Sadly this wont be as secret as people would hope, due to open source nature, but I like the sound of thsi

**Comment by TDSSS** [comment]
Interesting, a new trace gas? Didn't think they'd be this easy to add.

**Comment by Kyep** [comment]
I don't feel like I understand what this does well enough to vote on it.

**Pull request merged**
