### PR TITLE
medical now starts with (a bit of) mito, alternative to #21780

### PR DESCRIPTION
**Pull request by Sadhorizon**
## What Does This PR Do
This gives medical 10u of mito roundstart.
Due to the mapping freeze, I am adding two 5u mito vials into the anesthetic lockers for now, could possibly change it after the freeze is over.
Additionally, it slightly resprites the vials, so they don't have a large unclickable gap in the middle.

## Why It's Good For The Game
**This PR is an alternative to #21780**
Mostly, I find solution to problem presented... not ideal.
I believe this here to be a better solution - maybe it's not and I'm wrong, it's for you all to choose after all.

I chose 10u total, as it is enough to perform _some_ surgery with, while also not being enough to heal organ damage through ingestion with. If medical needs more (aka, highpop, when chemistry SHOULD be present), or to feed it to people, chemistry still needs to be involved.

As for another point original PR brought up, aka, burn wounds and antagging - you still can very easily get ointment to fix them the hard way.

## Images of changes
obraz
obraz

Also, why a vial and not a bottle? Just look at this lil cutie! 
obraz

(No real reason, thought it'd be cooler)

## Testing
Spawned in, took the above screenshots.

## Changelog
:cl:
add: Medical now starts with trace amounts mitocholide, inside of anesthetic lockers.
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
I'm heavily against this, we gradually make the Chemist job more and more irrelevant. First with NanoMed Pluses having the more complicated chems (I haven't mixed oculine in the entirety of 2023 due its widespread availability), now we just straight up add things to the surgery rooms.

The more you make a job irrelevant, the less people will play it. If you make an already unpopular job less popular, it'll go into a death spiral.

It takes 30 seconds to make mitocholide for both surgeries, which usually lasts for the entire shift. If you play medbay and you cannot do it and sorely miss it, go practice chemistry. If you don't play medbay and die due to not having mito, consider playing medbay. If there is no chemist and someone needs it for revival, ask the CMO/AI/captain for temporary access and make it.

**Comment by meow20** [comment]
Chemistry is already near useless with how little it brings to medbay, it needs more reasons to exist, not less.

**Comment by S34NW** [comment]
Just ask chemistry?

**Comment by Sadhorizon** [comment]
I believe #21801 to be an even better solution to original problem, thereby I'm closing this PR.

**Pull request closed without merging**
