### PR TITLE
Fixes a thunk runtime

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
Fixes a thunk runtime, gotta do your istype check

## Why It's Good For The Game
things that aren't carbons lack dna and runtimes bad

## Testing
Thunked in 4k
## Changelog
NPFC

### CODE REVIEW

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Comment by Sirryan2002** [comment]
This needs to wait for MC refactor, it will conflict the TM

**Comment by GDNgit** [comment]
> This needs to wait for MC refactor, it will conflict the TM

Feel free to slap DNM on it until the refactor is in

**Comment by GDNgit** [comment]
> @GDNgit mc refactor was merged

pr should be ready now

**Pull request merged**
