### PR TITLE
Ports TG's Datum Pooling

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/-tg-station/pull/10068

Simply put, this allows for the pooling of all datums (this includes images). We currently don't use pooling of datums (or images), but this  preps the way for us to, should we desire to do so. Fully compatible with pooling of existing atoms with no changes required for them to function.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Side note---it REALLY irks me how inefficient pooling is, or rather TG's implementation of it.

When and object is pooled, it's always done via qdel---this means that when something to be pooled is qdel'd, it's Destroy() is ran on it---that said, when it's about to be placed in the pool it's Destroy() is ran on it AGAIN....after that all its vars are reset (as should be).

Then a dumb thing is done...when a new object is pulled OUT of a the pool its vars are reset a second time.

This comes across as terribly inefficient, as you're calling the same thing twice on two separate things---which is effectively increasing the cost far more than it should be (and reset vars is NOT a cheap proc, either!)

This made sense on TG and VG where Destroy procs there (at one point in time) didn't call parent Destroys....the the calling of reset vars twice is incredibly curious as you can't alter the var of something in the pool.....

**Comment by PJB3005** [comment]
Whoosh pooling on /vg/ is sanic.

**Comment by Fox-McCloud** [comment]
Yeah, it's because of @clusterfak's superior implementation of resetvars.

**Comment by Fox-McCloud** [comment]
Went ahead and removed the duplicat reset vars---it literally makes zero sense to have.

**Pull request merged**
