### PR TITLE
Minor HUD changes

### PR DESCRIPTION
**Pull request by orelbon**
Changes the HUD for geneticist,security pod pilot, and edits the chemist HUD.

chem
gen
pilot

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
don't think that's a very good indicator for being sick. It doesn't really scream "this person is sick", to be honest (the current one does do that very well).

**Comment by orelbon** [comment]
Well i mean doesn't it only show up when someone has a virus? So more than half of the time you won't see the sick symbol, and when you do it'll stand out weather it has a sad face or a virus icon.

**Comment by orelbon** [comment]
@Fox-McCloud what you think
ill
made it so it looks like a virus under as microscope

**Comment by Fox-McCloud** [comment]
The problem is, that icon isn't just used for a virus; it's used for medical ailments as well---andddd on the offhand chance that we ever get diseases again ,it would be used for that as well.

A frowny face that's green is a pretty clear indicator that "hey, something is wrong with this person"; a line isn't; it just says "oh, new HUD icon".

**Comment by orelbon** [comment]
@Fox-McCloud what do you think of this
wanted

**Comment by orelbon** [comment]
@Fox-McCloud which one of these do you like the most?
pod 4
pod5
pod3
pod2

**Comment by Plotron** [comment]
We had new security icons added not long ago. 
I seriously think you shouldn't be messing with stuff that works. I agree with Fox on the virus thing.

Your proposed security HUD icon is confusing me. What we have now - a gun - is all we need IMO.

**Comment by orelbon** [comment]
@Plotron this is for the security pod pilot because the current one for him does not make sense at all

**Comment by ZomgPonies** [comment]
I see a lot of commits....I don't even know if -any- of these changes are necessary...

**Comment by orelbon** [comment]
they're not necessary but why not, it can't hurt. and what do the commits have anything to do?

**Comment by ZomgPonies** [comment]
I can hurt if the quality or readability of the changes is worse than what we already have. Change for change's sake isn't what we're looking for.

**Comment by orelbon** [comment]
this isn't change for change's sake, for one the pod pilot HUD makes no sense, you can check it out yourself, the geneticist hud is the same thing as the HoP, and roboticist just recolored, and all i did for the chemist was edit it because it looked a bit too flat, this isn't just changing sprites for the lolz i'm doing it cause it would improve them.

**Comment by Fox-McCloud** [comment]
I'd recommend squashing your commits, or...if you're uncomfortable about that, updating master and making a new branch and re-submitting; this has wayyy too many commits for changing 3 tiny sprites.

**Comment by orelbon** [comment]
alright ill get to it.

**Comment by Plotron** [comment]
Yeah, sorry for failing to read that the icon is for the pod pilot specifically.

**Pull request closed without merging**
