### PR TITLE
Add view-range changing verb

### PR DESCRIPTION
**Pull request by tigercat2000**
By request of @Melandor0
menu
verb
confirm

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by melandor0** [comment]
A majority vote wanted 17x over 15x. In complete violation of maintainer guidelines the change was merged within 24 hours, and the un-merge was closed after the consensus was that 17x was better, with a 10% vote majority towards 17x over 15x. Since it is obvious that they will not revert to 17x no matter what guidelines or consensus says, this is a solution that will make everyone happy.

I would advocate for 17x to be the default so mobs can see that far, but that will be a separate PR in that case.

**Comment by Earthdivine** [comment]
I would recommends making this a Lobby only option, similar to disabilities, so once you get in game you can't swap between them for the combat benefits, if it's at all possible.

**Comment by tigercat2000** [comment]
@Earthdivine It's possible, but I think being able to change is nice, and easier to make a decision between.

**Comment by melandor0** [comment]
@Earthdivine I feel that if you can change it when needed the "it's unbalanced towards 15x players" argument becomes even less valid.

**Comment by Earthdivine** [comment]
I know what you mean, but the original counter argument against having this was the combat balance issue. I posted that as an option to alleviate that concern.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Alex6511** [comment]
:-1: We should have a standardized view range.

**Comment by melandor0** [comment]
@Alex6511 Elaborate, why is one viewrange preferable to the current "15x for all, despite the majority wanting 17x"

**Comment by Alex6511** [comment]
One view range for is required to maintain balance in my opinion. 15x15 is preferable for this as it keeps us in line from other code bases.

**Comment by Iamgoofball** [comment]
What the fuck is this shit?

This is "do you want to gimp your view range and see less or see more"

fuck no :-1:

**Comment by melandor0** [comment]
@Iamgoofball That's precisely how I felt when 15x was merged against maintainer guidelines. We won't see 17x make a comeback as the only choice, it's already been decided that 15x is preferable. But a lot of people hate how it looks, and this is the only solution that doesn't give the middle finger to most of our playerbase (15x alone) or slightly less than most of our playerbase (17x alone)

**Comment by Markolie** [comment]
Krep this discussion calm or I will lock it. This will NOT become another shitfest. 

:-1: from me. 17x17 gives players an advantage in terms of what they can see, so people will just have to ger used to 15x15. All decision making past the point of the semi-early merge was completely valid and in line with our guidelines. A majority means nothing, not is this codebase a democracy.

**Comment by melandor0** [comment]
@Markolie I don't know if it's possible but I would rather you lock someone out from commenting if they're misbehaving than lock the entire discussion because of it.

**Comment by Markolie** [comment]
Not possible, no. Even banning someone from a Github requires you to e-mail their staff.

**Comment by melandor0** [comment]
@Markolie "A majority means nothing, nor is this codebase a democracy." Which people have a say in what goes onto the codebase? That is, which people actually get together and decide what is to be merged when there is a conflict? When there is a controversy which people get together and decide what passes and what does not?

**Comment by Markolie** [comment]
The three maintainers, as that's what we've been appointed to do. We do the majority of coding for this server, and as such have a good idea of what direction the server should be taken into in terms of code. Additionally, due to the sensitive nature of this subject we also checked with the headadmins to see what they thought (Earth being the only active one), and she also gave us the go-ahead.

When there's consensus with regards to certain features, then it'd certainly be out of line for us to add the features anyway. When there's not, the very reason maintainers exist is so that we can make the executive decision with regards to these features.

**Comment by Fox-McCloud** [comment]
Nope :-1: 

We've already been over this; an option is a false choice; nearly everyone will pick the option that maximizes view range as it gives them an advantage over someone who picks the lesser view range.

Likewise, the amount of things in  the code that are explicitly tied to view range just can't be changed. You can't change throw ranges, projectile ranges, blackout ranges, etc on the fly---likewise, you just can't get certain things to dynamically adjust (cinematics, overlays, etc).

There should be one and only one view range.

**Comment by KasparoVy** [comment]
Been loving 15x15, and people in-game've been pretty quiet about it
Don't think this is even a problem anymore

**Comment by veganzombeh** [comment]
This gets a :-1: from me. There are issues with 17x17 that were never fixed, and not that we've returned to 15x15, *won't* be fixed.

**Comment by M3hillus** [comment]
@ Everyone In regards to the poll, It was made prior to the 15x15 shift. Its more or less outdated opinion as far as I can see. Remake the poll now that people have had the chance to use both.

:-1: from me, because of the false choice it gives, but I remain in my position for :+1:15x15.

**Comment by TheDZD** [comment]
> This is "do you want to gimp your view range and see less or see more"
Iamgoofball

This is pretty much on the mark. Anyone whose view range is set to 17x17 will have a direct advantage over players that have it set to 15x15. Furthermore, you then have the issue of hostile mobs to deal with, if you up their view range to match, 15x15 players get screwed over, if you don't, 17x17 players have an advantage.

When the 15x15 revert PR was closed, the forum poll was approximately 44% against changing to 15x15, and 35% for changing to 15x15. Neither of those is a significant majority, and although 17x17 had an 8 vote, all three maintainers felt that it would be better to stick with 15x15 because of the issues it fixed (such as the malf round end animation, nuke animation, hostile mob view ranges). Before anybody brings up that those issues could easily be fixed, let me bring up the fact that *nobody cared enough to do so for the past year or so, not even when this first came up as a controversial topic*.

Now, keep the discussion civil. The PR discussion will be locked if people start with ad hominem attacks. At the end of the day, this is about a *1-tile radius in view range in a virtual space man game*.

**Comment by SamCroswell** [comment]
Robust people will keep in on 17x17, then bind a macro to swap to 15x15 and use that when engaging in melee combat.

**Comment by Spacemanspark** [comment]
do you even know how macros work.

**Comment by Robertha89** [comment]
nobody ever put up an issue with the 17x17 problems, thus why it was not fixed, of them the squished icon look could be fixed by adding like two lines of code.

**Comment by SamCroswell** [comment]
Yes, I do.
Logged onto the server, and it took me all of thirty seconds to figure out how to make a macro that swaps me from stretch-to-fit to 64x. It would be just as easy to do this with the commands here.

**Comment by Robertha89** [comment]
Also, if the fear of abuse is high, make it only changeable only before and after a round ends, or only once per round

**Comment by SamCroswell** [comment]
Then people will just stay on 17x17. It's still a false choice.

**Comment by tigercat2000** [comment]
Don't want to get involved in this too much, had enough arguments about this, but I will point out that any macros would still just pop up the input window due to how this is coded.

**Comment by SpaceTimeNow** [comment]
I feel this comment went by with out the attention it deserves.

___
@TheDZD:
All three maintainers felt that it would be better to stick with 15x15 because of the issues it fixed (such as the malf round end animation, nuke animation, hostile mob view ranges). Before anybody brings up that those issues could easily be fixed, let me bring up the fact that nobody cared enough to do so for the past year or so, not even when this first came up as a controversial topic.
___

We have to think about how much work it means to push for 17x17 and if we (and by we, i actually mean the coders) can support that. The fact that one year past this change we still have view range related issues, is reason enough not to continue to try to be unique at the cost of incoherent gameplay.

We can barely keep up with integrating cool features from other code bases and most implementations simply have to be rushed out the door and are not properly integrated into the rest of our codebase, yes, I am looking at you LINDA!

A poll with such low number of voters can hardly be a acurate representation of our current server polpulation. I literally could have turned the vote around with 9 fake accounts. From a coder/maintainer point of view there is no reason to implement and support a feature like this when there is a good chance that half the playerbase dislikes it. 

We should rather focus on pushing updates through the door that everyone can appreciate.

**Comment by Markolie** [comment]
Closing this as it hasn't been discussed in nine days, and overall people oppose it.

**Pull request closed without merging**
