### PR TITLE
Changes View Range to Default of 15x15

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Changes the view range to the SS13 default of 15x15.

Polled the live server multiple times about this--from low pop to high pop: each time 15x15 beat out 17x17. While I don't have every stat recorded, I do have this one: http://gyazo.com/fe8c86d93509f50a20b95fdb7a73ccbd (~35 players on).

Reasons:

- The whole reason for 17x17 was because of action buttons: This has been fixed/remedied by a modular action button system that's also collapsible.
- Puts us in line with every single SS13 codebase on the planet--who all use 15x15
 - I don't believe 17x17 make Paradise unique; we were considered unique long before 17x17.
- Should help cut down on crashes due to long jumps/travels (like here: https://github.com/ParadiseSS13/Paradise/issues/1671) this won't completely eliminate them, but it will reduce them. Technically should improve overall client performance by a tiny bit.
- Fixes a few quirks with mob vision range not being displayed properly
- Fixes cinematics not being displayed properly
- Fixes a few edge cases of being able to abuse simple animal vision range
- Fixes some oddities about projectile and other item ranges
- subjectively makes sprites look better
 - SS13 was designed, built, and sprited around 15x15; it's of no shock that 15x15 presents for better images
 - Reduces the amount of squashing of sprites if you utilize stretch to fit 
 - 1920x1080 resolution users and up can finally enjoy 64x64.
- Makes it far easier to click on things
- Makes chasing/hiding a bit more dynamic.
- Better HUD damage overlays

I'm sure I'll think of some things later that I'll post.

Picture comparisons: 
15x15: 

17x17:

### CODE REVIEW

**Comment by Alex6511** [comment]
Yes please.

**Comment by Ultimate-Chimera** [comment]
:+1: I completely support this :100: because the sprites are WAY too small and they are nearly impossible to click and the quality is low.

**Comment by Flip-Sandwich** [comment]
A very greedy :+1: so I can finally have my 64x64 and not the horrid de-pretty-fication of the station that is Stretch to Fit.

**Comment by FalseIncarnate** [comment]
I support this on at least a trial-basis.

While your points and screenshots are informative, my reservations regarding the change are things that would require live-testing of the code to settle.

If this helps improve performance / reduce crashing / improve visuals, as you have said it might, I will wholeheartedly support the continued use of 15x15.

:+1: for the sake of testing the impact on live code.

**Comment by Spacemanspark** [comment]
I'm going to say :-1: more or less because I personally like the 17x17 look better, but if everyone else wants it, then sure why not. Not a world changing issue.

**Comment by M3hillus** [comment]
:+1:

**Comment by FreeStylaLT** [comment]
You mean I'll be able to use 64x64 without adminbusing myself? I didn't even know that, that's excellent.

Totally support this :+1:

**Comment by Nienhaus** [comment]
:+1: Actually makes sprites how the spriters, or atleast me, want them to be seen.

**Comment by tigercat2000** [comment]
@ZomgPonies @Krausus @Robertha89 @fj45 @TheDZD @Earthdivine @Plotron This concerns all of you.

**Comment by tigercat2000** [comment]
> - The whole reason for 17x17 was because of action buttons: This has been fixed/remedied by a modular action button system that's also collapsible.

That may have been the original intent; @ZomgPonies already voiced that even with that, resizing down to 15x15 will still limit screen space arbitrarily

> - Puts us in line with every single SS13 codebase on the planet--who all use 15x15

We don't have to be `in line` with every other SS13 codebase on a visual detail.

>  - Should help cut down on crashes due to long jumps/travels (like here: #1671) this won't completely eliminate them, but it will reduce them. Technically should improve overall client performance by a tiny bit.

I still have yet to see empirically measurable evidence that this does so in any way. Crashes due to loading things should be reported to the byond forums; It shouldn't be happening at all, especially since we got rid of animate().

> - Fixes a few quirks with mob vision range not being displayed properly

This could easily be fixed with some number adjustments.

> - Fixes cinematics not being displayed properly

The only thing preventing cinematics from not working is that no one has been bothered to update them.

> - Fixes a few edge cases of being able to abuse simple animal vision range

This could also be fixed with number adjustments.

> - Fixes some oddities about projectile and other item ranges

Number tweaks?

>  - subjectively makes sprites look better
  - SS13 was designed, built, and sprited around 15x15; it's of no shock that 15x15 presents for better images
  - Reduces the amount of squashing of sprites if you utilize stretch to fit
  - 1920x1080 resolution users and up can finally enjoy 64x64.

Most players don't mind the stretch to fit squashing, from what I hear; And this point is indeed subjective- I think it looks much worse at 15x15.

> - Makes it far easier to click on things

I think calling it far easier is overstating it.

> - Makes chasing/hiding a bit more dynamic.

I'm not sure what your definition of `dynamic` is, because I don't quite understand this point.

> - Better HUD damage overlays

Icon tweaks?

**Comment by Nienhaus** [comment]
How could a crisp 64x64 look worse then the sprites being scaled down in a weird way.

**Comment by Markolie** [comment]
:+1:

**Comment by MindLeaker** [comment]
I'm going to go for :-1: on this, due to the fact 17x17 just /feels/ better in my opinion. But, if the community prefers it, I can live with the reduced view-distance

**Comment by TheDZD** [comment]
I don't really have much of an opinion on this. It will allow people using 1080p monitors to use 64x64, which looks significantly better than stretch to fit. If people want this more than 17x17, then I'm fine with it, otherwise leave it as it is.

That said, I'm staying out of the discussion for this because a lot of the arguments here keep getting reiterated. There aren't really a lot of objective improvements of using one over the other, it is mostly a matter of preference. Any quirks fixed by changing to 15x15 could be fixed in other ways, but in all likelihood will not be simply because the people who can do so are either too lazy or do not care enough.

**Comment by Markolie** [comment]
"because the people who can do so are either too lazy or do not care enough."
That's kind of the entire issue with 15x15, too. It was a poor solution to a problem that should've been solved in a different way, and it was done without any community approval at the time (as Ponies was the only maintainer). And as usual, we are now dealing with the consequences of a broken system and we are the ones required to fix it.

17x17 isn't inherently better. The only reason people would want to stick with it is because they're used to it. But, trust me on this one, 15x15 doesn't take much getting used to. It's the other way around. 

God knows how many references are made for 15x15. visible_message, oview, rview, say, hear_say, and the list goes on.

17x17 is terrible. 17x17 should've never been on the server. 17x17 was poorly implemented. There's no reason to keep 17x17 around except that it'll take people some time to get used to 15x15.

**Comment by Mijhead** [comment]
:-1:

**Comment by tigercat2000** [comment]
@Markolie None of those should be based around a magic number anyways- every single one of the things you listed should or *do* use world.view.

There are plenty of reasons to keep it around more than "because it will take people some time to get used to it being changed"- namely, having an extended view range lets you see more- it plays differently- a lot of people like that. 

I don't want to stick with it `just because they're used to it`, I want to stick with it because I like having a non-cramped view space.

**Comment by Markolie** [comment]
Not sure how 15x15 is less cramped, especially looking at the screenshots above. Again, the primary argument against this is *it feels better*, and yes, having a "non-cramped view space" is part of that. The arguments made in favor so far (and in the past) far outweight that.

**Comment by tigercat2000** [comment]
@Markolie The primary concern of the view range has nothing to do with systemic problems- It's an aesthetic difference, and anything else that is broken because of it obviously isn't worth anyone's time to fix.

**Comment by Markolie** [comment]
See the first post, Tiger. There's evidently more than just aesthetical issues.

**Comment by tigercat2000** [comment]
@Markolie I saw the first post, and responded to it- Most of the listed items are bullshit. The crashes are non-replicable by nature, and there isn't currently a way to objectively measure client lag. Cinematics haven't been fixed in months because no one can be bothered! The rest of the issues are things needing number tweaks, which is another thing no one can be bothered to do.

**Comment by Markolie** [comment]
Exactly. And since the last PR no-one has bothered to change it. And when this was implemented, they weren't fixed either. There's been plenty of opportunities for people to fix these issues when they feel very strongly about 17x17, and they haven't.

And cinematics for example are not easy to fix. Nor all the edge cases that may be around.

Why? Because it's a broken system we alone use.

**Comment by tigercat2000** [comment]
@Markolie There isn't anything inherently broken with 17x17 - only what we haven't accounted for. Edge cases are *edge* cases.

**Comment by Markolie** [comment]
I use 1920x1080. I have to use stretch to fit. 64x64 looks like garbage.

**Comment by SamCroswell** [comment]
I approve.

**Comment by Earthdivine** [comment]
I must say, having the argument "These are all thing's that can be fixed, so this is not a problem", and then blatantly ignoring them, hoping someone else fixes them is....a very poor stand for an argument. I see no reason not to switch over if someone will put their time and effort into fixing said problems with the HUD and Cinematic, as I play for the experience and not looks, but if that's not the case then why make things intentionally ugly looking because of one extra square.

When this argument went up last time to change it back, Fox put in the time and effort to add in the Dynamic HUD's to make sure things were still good from a HUD point of view. Will you all put the time and effort into making sure everything that is broken with 17x17 will get fixed? If not then please do not use that argument, as it's an incredibly pointlessly thing to argument about.

>I still have yet to see empirically measurable evidence that this does so in any way. Crashes due to loading things should be reported to the byond forums; It shouldn't be happening at all, especially since we got rid of animate().

While having the data from one person is very bad data, I literally could only play the game in 15x15 back before the lighting optimizations. The lower view range did help me a lot back then.

**Comment by KasparoVy** [comment]
I've +supported every single time this' come up and I'll more than happily +support again
:+1:

**Comment by tigercat2000** [comment]
@Earthdivine If anyone can be bothered to make an issue report for each thing that is actually borked because of 17x17, I would gladly do my best to fix them; I'm sure other coders would do the same.

**Comment by Earthdivine** [comment]
> I would gladly do my best to fix them; I'm sure other coders would do the same.

But it sounds like they have been known issues already, why would a Issue Report needed to be made to get it fixed. I don't mean to be rude but sounds like a excuse to not do work then anything.

Either way that is my one and only stance on this. I dont rightly care what we end up with, but if we stick with 17x17 I request that it's issues get fixed, other wise then there was literally no point to defending it, and thusly no point to not switching over other then for aesthetics.

**Comment by tigercat2000** [comment]
@Earthdivine Issue reports are always helpful. Common knowledge issues can be difficult to track down, especially as the exact issue gets muddled.

**Comment by Krausus** [comment]
Ugh, this again? I thought we shot this down [less than three months ago](https://github.com/ParadiseSS13/Paradise/pull/1231), but I guess the very recent change in maintainers means Fox is confident he can get it through this time. And he's probably right.

I'm still not in favor of it, mainly because it's a significant reduction in visible tiles (~23% of what you can see, gone) for little real benefit, especially now that BYOND updates and lighting optimization have basically eliminated the main source of crashing... but there's enough higher-ups in favor at this point that it's most likely a lost cause.

If the view range is going to be reduced, however, it should be done properly. Set `world.view` to 7, and **don't use 7 anywhere else** - insert the value of the client's `view` instead. There's no point swapping out hardcoded values when they can just compensate like they should.

@Earthdivine 
> But it sounds like they have been known issues already, why would a Issue Report needed to be made to get it fixed. I don't mean to be rude but sounds like a excuse to not do work then anything.

Here's the thing - the reason there are neither issue reports nor fixes for these things is because _nobody actually cares._ Players don't care about minor weirdness at the very edge of their vision, and coders don't care to fix stuff players don't care about. "The squeaky wheel gets the grease".

**Comment by Earthdivine** [comment]
>Here's the thing - the reason there are neither issue reports nor fixes for these things is because nobody actually cares. 

That's the point I was making, if no one cares about fixing it, the don't use it as part of an argument.

**Comment by KasparoVy** [comment]
15X15 2015 its the year of the 15s brud.

**Comment by tigercat2000** [comment]
Why was this merged? It had a controversial tag, not to mention issues like Krausus pointed out about the proper world.view implementations.

**Comment by Markolie** [comment]
Those aren't issues, those are suggestions on how to best implement view range. If we ever want to improve variable view range or switch back to 17x17, then we can implement this. As it stands, values are already hardcoded for 7. Right now world.view is supposed to be 15x15.

Concensus:
http://nanotrasen.se/phpBB3/viewtopic.php?f=48&t=5582
https://gyazo.com/fe8c86d93509f50a20b95fdb7a73ccbd

**Comment by tigercat2000** [comment]
@Markolie Whatever. I'm not going to make a deal out of this, even though I damn well should, controversial PR's shouldn't be merged after a single day.

**Comment by Fox-McCloud** [comment]
It was merged because of the strong and universal consensus, regardless of location--this isn't the first time a controversial PR got merged fairly quickly after the 24 hour mark.

It had far more supporters than detractors both here and on the forums itself--likewise, multiple polls conducted on the live server (not just a single instance of a poll, either) at multiple times of the day, on multiple days, also bore the same, exact results demonstrated on the forums and here on the Git.

Something similar happened with the borg rebalance PR--it was controversial, but met with only some detractors--therefore it was merged in relatively quickly once the 24 hour mark was reached.

**Comment by melandor0** [comment]
Fix the problems with 17x. Don't ruin most people's vision because some people have super-low-end computers. This is bullshit, and I will not let this pass like the taser bullshit passed Fox.

**Comment by Krausus** [comment]
> this isn't the first time a controversial PR got merged fairly quickly after the 24 hour mark.

Uhh, this was before the 24 hour mark. Submitted Aug 13th, 12:19 AM, merged Aug 14th, 12:03 AM. 24 hours is a bare minimum to give everyone time to look at and discuss a change, not something to be shrugged off just because it's _pretty_ close. Not that controversial PRs are supposed to be merged in 24 hours anyway. We may as well not even have [rules for merging PRs](https://github.com/ParadiseSS13/Paradise/wiki#instructions-for-maintainers) if they're not going to be followed.

**Comment by Fox-McCloud** [comment]
There's a distinctive different between a PR that was self-merged the split-second it was published with no community say, input, or feedback, and one that has passed muster...that is to say, one that had more support than opposition on the live server, forums, and github and had the backing of two of the three maintainers.

**Comment by Flip-Sandwich** [comment]
@melandor0 How does this ruin most people's vision. How does this break gameplay. If anything there's a few things it fixes so not sure where you're coming from here.

**Comment by Mijhead** [comment]
@Fox-McCloud After one of the maintainers that originally was against it disappeared.

**Comment by Flip-Sandwich** [comment]
Before it was merged the conversation was roughly 1.4 comments per hour, so  16 minutes equates to about 0.35 comments lost

**Comment by melandor0** [comment]
@Flip-Sandwich Because honestly the game should be using even more than a 17 tile wide viewing area. Why stop at 15x? Go 13. 11. 9. The sky's the limit when you don't care about making every player so short-sighted they wouldn't be legally allowed to drive a bicycle.

**Comment by Robertha89** [comment]
The max pixel height on Windows 10 Paradise Station is 954, this being not a round number, will cause squashing of pixels at 15x15, or pixels out of view at 64x64, lets say the task bar is hidden for maximum height, and you got 994 max pixels, even then it will be squished or hidden. To make it look good in 1080p, we should have 56x56.

**Comment by Flip-Sandwich** [comment]
There are several good, definitive reasons to have it 15x15 instead of 13x13 or 11x11, and frankly the slippery slope strawman is rather ridiculous.

The entirety of space station 13 is built for 15x15. Every codebase but paradise is built for 15x15. And even now there arise issues from 17x17. Space carp and other mobs don't attack you if you are at the very edge of your vision because they are built for 15x15.

Also 15 * 64 = 960, so at 994 max pixels nothing will be squished or hidden and at 954p so little will be hidden that it's negligible

**Comment by Robertha89** [comment]
Or we can add 48X48, removes squishing, lemme show:
image

**Comment by Dumbdumn5** [comment]
The lower one actually makes me feel sick and I have no idea why. It just looks a bit too enclosed and shut off :-1: Also note that chasing and hiding is quite a bit better when you can actually see what's in front of you, as well as the crap ton of hostile mobs that are much faster than you. The higher view range makes the slow walk speed bearable.

**Comment by TheDZD** [comment]
What the actual fuck. This should **not** have been merged in early regardless of how the polls were going. There are a fair number of people against this in both the administrative team and the community against this. The numbers on the poll currently look like this:
theactualfuck

**Pull request merged**
