### PR TITLE
Ports Goonstation solar panels

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Ports solar panels from Goonstation using TGs implementation of the sprite since TG used to use the same solar code as us and Goon uses dir on their panels.

These are not [TGs new solar panel sprites](https://user-images.githubusercontent.com/1185434/155786832-3c603545-eeb2-4a97-b356-870d3d8f1190.gif), those look iffy IMO.

## Why It's Good For The Game
It's basically the old solar panels but with better colouring and shading.

Replacing r4407 sprites is a good thing.

## Images of changes
Please excuse my choice of green cable, I have no soul.
image

## Changelog
:cl: Bmon
imageadd: New solar panels from Goon!
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
closing for now

**Comment by Bm0n** [comment]
Goon is fully licensed under CC BY-NC-SA 3.0 which is the non-commercial version of CC BY-SA 3.0 that we use for our assets. Paradise is not commercial and everything is attributed to the goons folder which is CC BY-NC-SA 3.0. Hal scared me into thinking I needed permission from the goons to port assets from their codebase which is only true for code as far as I am aware.

Reopening this.

**Comment by Bm0n** [comment]
Icondiff will report that I modified teg-op11's icon. It should be reverted but icondiff is too dumb to realise that it is.

**Comment by tigercat2000** [comment]
horrible edge case, diagnosing
metadata on master:
```
state = "teg-op11"
    dirs = 1
    frames = 2
    delay = 1,1,0.5,0.5
```
metadata on this branch:
```
state = "teg-op11"
    dirs = 1
    frames = 2
    delay = 1,1
```

**Comment by Bm0n** [comment]
I copied the power.dmi file from master then back into my branch and redid my changes. how the actual fuck?

**Comment by Bm0n** [comment]
> we haven't used dir on our panels for like 2 years lol 
> also at least could ask first jeez

I did check the Goonstation sprites but they're formatted differently and still have directional sprites(even if they're not used).

I wasn't really aware of Goon's policy on other codebases porting from them and didn't want to bother you guys over nothing considering other codebases have already ported these sprites.

I know I don't necessarily have to ask for permission so long as everything is properly credited and in the goonstation folder but if that's what you guys want I'll do it next time for sure.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
