### PR TITLE
Makes gameboard circuits printable

### PR DESCRIPTION
**Pull request by CrAzYPiLoT-SS13**
Whoops! Speed merge go

### CODE REVIEW

**Comment by monster860** [comment]
Eh, there's been faster merges.

Once, @TheDZD screwed up the CSS.

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, I remember the 'FUCK' commit.

**Comment by CrAzYPiLoT-SS13** [comment]
What's the hold up? It's kinda important, as without it, it can't be built without adminbus

**Comment by monster860** [comment]
Maintainers probably not home.

**Pull request merged**
