### PR TITLE
Improve Tyrant lawset from good, too best lawset.

### PR DESCRIPTION
**Pull request by Robertha89**
:cl: ppi
tweak: Improves Tyrant lawset for it to improve the standing of crew.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:-1: Not all lawsets need to bind you to all of the crew.
This lawset in particular is a pretty large gamble to use, and should stay that way.

**Comment by Regen1** [comment]
:-1: 

Also grammar

**Comment by DaveTheHeadcrab** [comment]
:-1: 
Tyrant is to Paladin as Antimov is to Crewsimov.
Lawset is working as intended.

**Comment by NTSAM** [comment]
:-1: 
Dude no

**Comment by theColdflame** [comment]
tyrant's supposed to be a flawed lawset that lets the AI pretty much do whatever they want

**Comment by KasparoVy** [comment]
You're supposed to be the grand glorious technetic leader dictator out for your own benefit/antaggery

I think it's important we keep that in mind

**Comment by Fox-McCloud** [comment]
ewww, no.

:-1:

**Comment by Tastyfish** [comment]
The whole point of Tyrant is that the crew is worthless unles it's furthering the authority's standing.

**Comment by TheDZD** [comment]
The lawset is supposed to be the arsehole version of PALADIN. :-1:

**Comment by Spacemanspark** [comment]
This PR is being tactically nuked.

**Comment by Fox-McCloud** [comment]
>This PR is being tactically nuked.

https://www.youtube.com/watch?v=aCbfMkh940Q

**Comment by Iamgoofball** [comment]
:-1:

**Comment by NTSAM** [comment]
ah shit Fox linked what i was gonna link

**Comment by Fox-McCloud** [comment]
No support--downvoted by 2 maintainers.

**Pull request closed without merging**
