### PR TITLE
Fixes penlights being unable to write

### PR DESCRIPTION
**Pull request by Divulf**
## What Does This PR Do
Fixes a bug with penlights that made them unable to write.  This occurred because the check to see if a pen was in the user's hand was incorrectly using istype() instead of is_pen().  The offending line was last modified 3 months ago, and was likely when the bug was created.  No issue about this was ever opened.

## Testing
Wrote on paper using a penlight, a normal pen, and a crayon.  All functional.

## Changelog
:cl:
fix: Fixed penlights being unable to write
/:cl:

### CODE REVIEW

**Comment by Hostail** [comment]
I thought this was intentional cause... Penlights are not pens.

**Comment by ArcticValor** [comment]
> I thought this was intentional cause... Penlights are not pens.

that's exactly what I also thought

**Comment by Divulf** [comment]
> I thought this was intentional cause... Penlights are not pens.

They are.  If you use them on a piece of paper they bring up the 'write' text, it's just that the check for whether the pen is in your hand at writing time doesn't include them.

**Comment by DGamerL** [comment]
As far as I'm aware, a penlight IRL is just a tiny flashlight that looks like a pen, so you can easily put it in a coat/lab pocket.

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
