### PR TITLE
New Fire Extinguisher Sprites (updated)

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
Replaces our old fire extinguisher sprites with new ones.

Big extinguisher is a mid-point between TG's extinguisher and Eris's extinguisher.
Little extinguisher is a brand new one, based on how real-life mini extinguishers look.

## Why It's Good For The Game
Looks better, and as everyone knows, the better they look, the more fire they extinguish.

## Images of changes
image
image
(the grey band on the in-hand has since been tweaked and isn't as big as it looks here)

## Changelog
:cl:
imageadd: New fire extinguisher and mini-extinguisher sprites
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
An overall improvement, however I feel the shading on the updated version makes the fire extinguisher appear to have a bunch of flat faces, like a hexagon, instead of a smooth cylinder.

**Review by dearmochi — APPROVED** [review]

**Comment by PacifistDalek** [comment]
image

image

Modified it to make it less hexagonal!

**Comment by Fox-McCloud** [comment]
Please implement the tiny fire extinguisher sprite, while you're at it.

**Review by Kyep — APPROVED** [review]

**Comment by PacifistDalek** [comment]
> Please implement the tiny fire extinguisher sprite, while you're at it.

As in the grey mini extinguisher that comes in the red toolboxes? I'll take a look at coming up with something for it, the spriting chat consensus was that TG's version was comparatively bland so I don't want to directly port their version.

**Comment by Fox-McCloud** [comment]
Please directly port, we're in the middle of TG's respriting project, so we're using them as a basis--deeper evaluation is to take place *later*.

**Comment by PacifistDalek** [comment]
Made a totally new mini extinguisher, since the old one was potentially confusing to new players as it didn't really look like any kind of extinguisher. I was careful to not make it look like the pepper spray or a grenade, and gave it a bit of the atmos colour since mostly it'll be atmos techs handling them: 
image

**Comment by Fox-McCloud** [comment]
Re-iterating my above statement.

**Comment by PacifistDalek** [comment]
> 
> 
> Re-iterating my above statement.

Anyone with some coding skill can blindly port sprites, but i'm here to edit and create new sprites. It's what I enjoy about contributing to Paracode. If we're not making new sprites and are just porting every TG sprite, then i'm not sure why I'm here...

And also not sure why that isn't noted anywhere. When I returned to Paradise after a 6 month gap, I made sure to read the forum announcements, code discussions, the pinned posts in the spriting discord channel, and the pinned github posts, because I wanted to contribute in ways that were beneficial and wouldn't lead to any major waste of my or anyone else's time. I saw nothing about a TG respriting that indicated that I shouldn't work on new sprites.

Finally, I'm more than happy to admit that while I think my sprites are an improvement over our old sprites or the TG sprites in this PR, others may disagree, and if that's the case, I have no problem with either the current Paradise or current TG sprites being used. However, "deeper evaluation is to take place later" runs up against the fact that while yes, much of TGs sprites are great, some of TGs sprites are _garbage._ Why waste the time porting a clearly garbage sprite when we already have a better one (say, fish and chips), or can easily snag a _clearly_ better one from another codebase (citadelstation's tacos, which I was hoping to port soon), or if we have spriters excited to make better ones?

**Comment by PacifistDalek** [comment]
@Fox-McCloud Hey Fox, I want to apologize. I realize I was being a bit aggro in my responses, and that was uncalled for. I have my opinions, but there's no justification for me to be a dick about them.

I would still love to see this in game of course, but I'm more than happy to swap in the tg mini extinguisher sprites and save the my replacement sprites for a separate PR, either right after this one is merged, or further down the line when the tg project is wrapping up, whichever makes more sense!

**Comment by variableundefined** [comment]
@PacifistDalek PR can be merged if you swap it back for the original TG sprites - the other sprite can be added in in a separate PR to be debated later.

**Comment by PacifistDalek** [comment]
TG sprites all set

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
