### PR TITLE
Resprites the Automender

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do
Resprites Automender icons

## Why It's Good For The Game
Automender is one of the few remaining medical items that retains its old icon. This just cleans things up, without putting it through the soul-mulcher device.

## Images of changes
image
image

## Testing

It just works.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imageadd: Resprites the Automender
/:cl:

### CODE REVIEW

**Comment by Christer2222** [comment]
Might want to change the red cross to a green one because of the Geneva convention, while you're at it

**Review by Contrabang — CHANGES_REQUESTED** [review]
Move the icons out of the goonstation dmi since theyre no longer from goonstation

**Comment by Contrabang** [comment]
> Might want to change the red cross to a green one because of the Geneva convention, while you're at it

I'd say its already more pink than red. Look at the pink medkits they come in. Changing the color of the automender would also require changing stuff like those medkits + maybe also brute patches.

**Comment by Christer2222** [comment]
> > Might want to change the red cross to a green one because of the Geneva convention, while you're at it
> 
> I'd say its already more pink than red. Look at the pink medkits they come in. Changing the color of the automender would also require changing stuff like those medkits + maybe also brute patches.

It is red enough that some people, like myself, could mistake it. Most people don't analyze sprites with a color picker when determining if something is red. I believe its mostly an honor thing though, not like anyone will come after a video game if they use a bunch of red crosses and dilute the Red Cross' iconography. 

Also not that medkits and patches are relevant at all, as its better to fix 1 thing than none, but medkits have blue crosses and brute patches are purple with a diagonal black cross, so no need to change either of them.

**Comment by ATP-Engineer** [comment]
Until the brute/burn menders get actual seperate icon states that isnt just a color'd overlay. This stays as is until later changes.
image


> > > Might want to change the red cross to a green one because of the Geneva convention, while you're at it
> > 
> > 
> > I'd say its already more pink than red. Look at the pink medkits they come in. Changing the color of the automender would also require changing stuff like those medkits + maybe also brute patches.
> 
> It is red enough that some people, like myself, could mistake it. Most people don't analyze sprites with a color picker when determining if something is red. I believe its mostly an honor thing though, not like anyone will come after a video game if they use a bunch of red crosses and dilute the Red Cross' iconography.
> 
> Also not that medkits and patches are relevant at all, as its better to fix 1 thing than none, but medkits have blue crosses and brute patches are purple with a diagonal black cross, so no need to change either of them. Non-brute patch patches have green crosses and green corners by the way.

**Comment by Bm0n** [comment]
> Might want to change the red cross to a green one because of the Geneva convention, while you're at it

we tend to use the blue cross more than the green cross

**Pull request closed without merging**
