### PR TITLE
Removes cyborgs

### PR DESCRIPTION
**Pull request by tigercat2000**
```
    src.emag = new /obj/item/toy/sword(src)
    src.emag.name = "Placeholder Emag Item"
```
^ THIS SHIT RIGHT HERE :scream:

https://github.com/ParadiseSS13/Paradise/tree/master/code/modules/mob/living/silicon/robot/robot_modules.dm

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
kek.

**Comment by TheDZD** [comment]
I shouldn't have shown you the horror that is/was robot_modules.dm.

**Comment by Regen1** [comment]
speedmerge when

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/5477

Cyborgs are saved!

**Pull request closed without merging**
