### PR TITLE
Adds Laser carbines

### PR DESCRIPTION
**Pull request by Regen1**
Adds laser carbines, nanotrasens response to the syndicates burst fire weapons
DNM for now, I still need to figure out where to place these in the game

This is nowhere balanced, and the sprites are shitty, I am making the PR so people can (hopefully) come with some ideas on what would balance this weapon, and where it'd be added (ERT or Science mainly)

Gun shoots a burst of 3 laser shots, each doing 20 damage each.
The magazine holds 30 rounds, basically making it the laser equivalent of the Saber SMG (without the fancy ammo)
This might not be balanced..

Codersprites are shitty and generally reused, the magazine isn't completely done because I still need to add the math to count the icon state at 100(99)%, 66% and 33%

The laser carbine
lasercarbine

Laser carbine empty
lasercarbine empty

Laser carbine magazine, yes that is the RCD ammo recolored
Lasercarbine magazine

Laser carbine casing
Lasercarbine casing

Casing spent
Lasercarbine casing spent

### CODE REVIEW

**Comment by pinatacolada** [comment]
sounds gamma ERT to me

**Comment by taukausanake** [comment]
Maybe extend the stock another pixel? I think they are good sprites. Just get another sprite for the mag

**Comment by TheDZD** [comment]
Merge conflicts, probably due to your immolator laser PR.

**Comment by Fox-McCloud** [comment]
I'm personally not a fan, to be honest--it's a ballistic gun that looks like a laser gun, but doesn't behave/act like it.

An EMP won't impact it, you won't be able to recharge it in a recharger, it'll eject casings (what), the laser projectiles will travel sanic fast (bullets travel faster than laser/energy shots, IIRC), and you'll have to use magazines with...bullets, to reload it.

Because we have super outdated TG guncode and not their newest iteration, our energy guns operate off of a sort of magic, instead of ammo casings and internal energy refactors.

**Comment by Regen1** [comment]
That's true fox, it's a super hacky way of doing it, so I am in no way expecting it to be added as-is

I like the idea of it, but not currently how it's done, I might have to tinker a bit more with it

**Pull request closed without merging**
