### PR TITLE
Changes Medbay's treatment center, Virology hallway entrance

### PR DESCRIPTION
**Pull request by FreeStylaLT**
BEFORE:
img

AFTER:
img

- Wider entrance to fit the lobby's
- Double doors to Virology, now **public access**
- Table with misc. treatment stuff moved to the IV room.

These changes are meant to help higher pops handle movement easier in and out of Medbay, as the two-wide entrance / exit was causing quite a few medical moshpits, and surgery patients could only leave that way. Now there are alternatives.

🆑 FreeStylaLT
tweak: Medbay treatment center now has a wider entrance
tweak: Virology hallway is now publically accessible from Surgery waiting room, entrance is now double-doors.
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Dunno if I agree with the table being moved, to be honest. If you could work it in, somehow, to the original location, it would be better, in my opinion.

**Comment by FreeStylaLT** [comment]
Table was moved back to roughly the same position, Treatment center has been opened up further.

**Comment by Pennwick** [comment]
So now the IV room requires no access? Can't say I'm in favor of that. People will just steal boath soaps and pssibly the IVs and blood.

**Comment by Fox-McCloud** [comment]
There's a very simple solution to preventing people from taking the soap.

Pick it up. Put it in your pocket/backpack.

Blood bags have been public access before, with old medbay; people were hardly raiding them 24/7/365 except to give themselves blood when they actually needed it

**Comment by Plotron** [comment]
I liked the separation between IV room and Sleeper/Exam area. It actually gave me a reason to RP some treatment. This PR makes it look messy again.

**Comment by Fox-McCloud** [comment]
I'd resolve the conflicts on this one, first, @FreeStylaLT.

**Comment by Fox-McCloud** [comment]
You tried map diff bot, you tried.

**Pull request merged**
