### PR TITLE
docs(grammatical): correct typos and improve grammar

### PR DESCRIPTION
**Pull request by AbhineshJha**
## What Does This PR Do
This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.

## Why It's Good For The Game
Typos are bad

## Images of changes
None

## Testing
None required

## Changelog
No player facing changes

### CODE REVIEW

**Comment by Contrabang** [comment]
I appreciate the grammatical corrections, but its required for you to follow our PR format, I can give you a simple example of what this should look like this below. If you have any questions, you can ask them here and I will hopefully respond, or you can join our discord at https://discord.gg/YJDsXFE and ask questions in our #coding-chat
```
<!-- By ticking or leaving ticked the option "Allow edits and access to secrets by maintainers" you give permission for repository maintainers to push changes to your branch without explicitly asking. -->

<!-- Write **BELOW** The Headers and **ABOVE** The comments else it may not be viewable. -->
<!-- You can view Contributing.MD for a detailed description of the pull request process. -->

## What Does This PR Do
<!-- Include a small to medium description of what your PR changes. -->
<!-- Document all changes, as not doing this may delay reviews or even discourage maintainers from merging your PR! -->
<!-- If your PR fixes an issue, add "Fixes #1234" somewhere in the PR description. This will automatically close the bug upon PR submission. -->
This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.

## Why It's Good For The Game
<!-- Add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding. -->
Typos are bad

## Testing
<!-- How did you test the PR, if at all? -->
None required

## Changelog
No player facing changes.

<!-- Both :cl:'s are required for the changelog to work! You can put your name to the right of the first :cl: if you want to overwrite your GitHub username as author ingame. -->
<!-- You can use multiple of the same prefix (they're only used for the icon ingame) and delete the unneeded ones. Despite some of the tags, changelogs should generally represent how a player might be affected by the changes rather than a summary of the PR's contents. -->
<!-- If a PR has no impact on players (i.e. a code refactor that does not change functionality) then the entire Changelog heading and contents can be removed. -->
```

**Comment by AbhineshJha** [comment]
Updated the desc , can you check @Contrabang

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Contrabang** [comment]
> Updated the desc , can you check @Contrabang

Thank you, looks good to me!

**Review by Contrabang — APPROVED** [review]

**Comment by AbhineshJha** [comment]
Can u merge @Contrabang sir..

**Comment by S34NW** [comment]
> Can u merge @Contrabang sir

He cannot, but I can. I've run CI and will merge once it is completed.

**Review by S34NW — APPROVED** [review]

**Comment by AbhineshJha** [comment]
Oh ! 😀

**Pull request merged**
