### PR TITLE
Adds a recipe, that allows making syndicate toolboxes

### PR DESCRIPTION
**Pull request by improvedname**
Adds a recipe, that allows you to paint  a toolbox and turn it into a syndiecate toolbox, known as well "suspicous toolbox"  its not contrabrand i know, its just a cool toolboxx honestly and i hate they are super rare n stuff, and you easily be tell the difference by examining it

:cl:
add: Adds a recipe for the toolbox to make it a suspicous toolbox
/:cl:

### CODE REVIEW

**Comment by Agameofscones** [comment]
It'd be better if the description was written as `Danger. Very Robust. The paint is still wet.` Having still at the end makes it read like a fragment, which isn't ideal. Otherwise looks good to me, doesn't inherit the 15 brute from real sus toolboxes, so it's a nice bit of flavor and trickery. Why not right?

**Comment by Denthamos** [comment]
As scones stated, make sure its denoted as a regular toolbox but just painted so it does not get that 15 brute damage.

**Comment by improvedname** [comment]
>not checking the code before commenting 😠

**Comment by KasparoVy** [comment]
I was about to say ohhh fuuuuck mateee that does a lot of damage but nah it's typed properly

good good

**Pull request merged**
