### PR TITLE
Combines martial art combo files

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
 Combines combos into their corresponding files, instead of each combo being separate files for each single combo.

## Why It's Good For The Game
 It is difficult to read through all the current combos, having them together in files and not folders makes them easier for coders to access.

## Testing

All the combos still work, an entire kitchen of skrell was slaughtered

## Changelog
Nothing player facing

### CODE REVIEW

**Comment by Sirryan2002** [comment]
> Its better to have less but longer files than, than more but shorter files files aka code readibility

why is this better?

**Comment by Contrabang** [comment]
If you want to read through the combos currently, you need to open all the files. Its a lot of hassle for when they could just all be in one corresponding file for each martial art.

**Review by Sirryan2002 — APPROVED** [review]
The code is fine and everything was transferred over correctly, so from a code review standpoint this PR is fine so I will put an approval on it. What I would like to see is some input from the review/maint side of the dev team on whether or not this actually increases code readability, because I'm of the opinion that it really makes no difference here.

**Review by hal9000PR — CHANGES_REQUESTED** [review]
after discussing this with affected and farie we have determined that this is a regressive change. 
splitting the combos up into files makes them more organised.

**Pull request closed without merging**
