### PR TITLE
Adds the box subtype to fancy storage containers & Gives the ability to fold and craft to 5 items.

### PR DESCRIPTION
**Pull request by dovydas12345**
**What does this PR do:**
Adds the box subtype to fancy storage items. Gives the ability to fold items back to cardboard for donut boxes, crayon boxes, candle boxes, egg boxes and cigarette packets as well as crafting possibility using cardboard.

**Changelog:**
:cl: Dovydas12345
add: Added box subtype to fancy storage items.
add: Added the ability to fold items back to cardboard for donut boxes, crayon boxes, candle boxes, egg boxes and cigarette packets as well as crafting possibility using cardboard.
/:cl:

### CODE REVIEW

**Comment by dovydas12345** [comment]
Not exactly sure whats wrong with Map Diff Renders check (never had to deal with it). I have a feeling i missed a step when doing this PR?

**Comment by FalseIncarnate** [comment]
The map check failure seems to be an error with the Map Diff Bot, not your changes. A little digging found this same error was reported to Map Diff Bot's issue tracker already by someone on TG

**Comment by dovydas12345** [comment]
I see that would make sense.

**Comment by dovydas12345** [comment]
oops didn't mean to do that....

**Comment by variableundefined** [comment]
You're free to reopen this PR when deconflicted

**Pull request closed without merging**
