### PR TITLE
LINDA Performance Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
re-upload of: https://github.com/ParadiseSS13/Paradise/pull/13786

Refactors `process_cell` to perform a lot better, ports: https://github.com/tgstation/tgstation/pull/15218

Instead of adjacent turfs constantly being recalculated and it looping through through every turf and doing and istype check on them, it caches those turfs on a list of every turf.

There's one downside to this though---because it's a cached list, it's not going to play nice with melting walls;  walls melting are dependent on looping through *every* turf in order to work.

As such, melting walls have been removed---and to be honest, I think that's for the better; while there is some interesting notion to fire spreading in this manner, it also means fires tend to burn themselves out *very rapidly*; they just get too hot in a confined area, melt the walls, then rapidly spread out and dissipate not too long after. I don't consider this a net positive, as it means that, while yes, the fire may spill into other areas, it also means that a fire is far far more likely to breach to space and extinguish itself.

On that note, I also removed insulated floors--superconduction is a pretty important part of LINDA: being able to have temperatures that go to obscene levels because there's no temperature conduction with walls, the floor, or space just leads to *ridiculous* numbers that really shouldn't exist---this will be even more problematic now that we use the Supermatter. I wouldn't be all surprised if it is playing its part in atmospheric oddities from time to time, as well.

I'd like this test merged on live before merging to make sure everything functions as intended.

:cl: Fox McCloud
tweak: Improves LINDA's performance, overall
del: walls can no longer melt from fire
del: insulated floors have been removed
/:cl:

### CODE REVIEW

**Review by dearmochi — APPROVED** [review]

**Comment by S34NW** [comment]
This means plasma fires will remain in the room they began unless someone opens a door? Can't say I'm a massive fan of this consequence personally, that's a big balance change to fires

**Comment by AffectedArc07** [comment]
I am fine with losing the ability to melt walls for the sake of performance. Active turfs commonly bloat to 4000 in rounds, which can really slow the entire system down. Being able to tackle that list more efficiently is a benefit I would much rather have.

**Comment by Wojz** [comment]
Is it walls specifically that won't melt anymore? In other words, do doors still melt? Because then I'm completely fine with this since a proper fire will just turn the room into a burn chamber until the door is no more.

**Comment by Spacemanspark** [comment]
Not too keen on removing functionality of burning walls. Plasma fires being so easy to hold off in a singular room doesn't sit so well with me.

**Comment by FreeStylaLT** [comment]
The consequences on plasma fires due to this PR will be extremely noticeable and sometimes, non-sensical.

IE, pictured, aftermath of a plasma fire in toxin storage:
image

**Comment by TDSSS** [comment]
Free did a test on how a plasma fire in toxins storage goes without melting walls and...well, I think this is pretty sad:

image

Toxins storage is now completely safe unless some dummy opens the door and forces the firelock.

**Comment by TDSSS** [comment]
Is there really no way for wall melting to stay in? If not, IMO it would be better to then remove floor melting so fires can't breach space and burn out prematurely. I guess a room full of very hot CO2 is a decent threat at least.

**Comment by DevL-Whats-a-jpg** [comment]
Wouldn't this make burn chambers extremely impractical? Atmos already has no fire fighting, no reason to make power now, no SM, and this removes the ability to make burn chamber TEG's, leaving Atmos as a room with a few pumps that no one cares about, unless you plan on doing whacky shit with air alarms and air under walls. I don't have really and weight here, but I very much don't like this.

**Comment by matttheficus** [comment]
agreeing with @DevL-Whats-a-jpg here, if this breaks Burn Chambers, the Turbine AND most TEG setups will become nearly pointless, making Atmos even more massively useless than it is with the SM being brought into the standard Engineer's access.

**Comment by S34NW** [comment]
Perhaps a fire rework is in order before/right after this one goes through?

**Comment by Fox-McCloud** [comment]
>Is it walls specifically that won't melt anymore? In other words, do doors still melt?

They do

>floor melting

This happens when fires are already on their way out; as long as the fire is burning, there won't be a hole burnt in the floor---this happens once their fuel is exhausted and the hotspots start disappearing---then it finally burns *through* the floor.

>Wouldn't this make burn chambers extremely impractical?

Uh, no. Burn chambers, the TEG, and the turbine have all been working for years prior to the addition of insulated floors; they'll be fine, after, too.

**Comment by Sikroth** [comment]
> As such, melting walls have been removed---and to be honest, I think that's for the better; while there is some interesting notion to fire spreading in this manner, it also means fires tend to burn themselves out very rapidly; they just get too hot in a confined area, melt the walls, then rapidly spread out and dissipate not too long after. I don't consider this a net positive, as it means that, while yes, the fire may spill into other areas, it also means that a fire is far far more likely to breach to space and extinguish itself.

Most fires breaching to space do so through windows before rwalls are even damaged. This is just going to make fires inside the station laughably irrelevant, even more than they already are 90% of the time, anyway. I know para maints have a hardon for anything performance wise but if it comes at the cost of making the game noticeably duller I feel like it starts to be an issue.

Not commenting on the removal of insulated floors depending on how burn chambers deal with fires. If we end up having holes left and right it's definitely going to be an issue but we'll see.

**Comment by TDSSS** [comment]
> They do

A door melting is, sadly, pretty meaningless, because every door on the station bar some maint doors comes with a firelock which is totally invulnerable to fire. Effectively, any plasma fire is getting stopped by a door unless a greytide decides to crowbar the firelock open.

**Comment by Rurik123** [comment]
It should be said, regardless of if this is merged or not, plasma fires for a while have been harmless. A relic of its former glory back when glorious death blenders were a thing. Unless someone suicides into it or makes a series of oblivious mistakes, it is pretty hard to unintentionally die or be threatened by one. Whether or not the fire can go through walls or not hardly matters at this point, it'll scarcely cause harm. 

Only real question is if the performance gain is worth prying a claw from an already clawless feature, and, judging by the pr's existence and arc's comment, it seems worth.

**Comment by Wojz** [comment]
> It should be said, regardless of if this is merged or not, plasma fires for a while have been harmless.

Hell no, a plasmafire in toxins storage can currently eat robotics and make R&D inhospitable. The PR removes that unless atmosia or the AI decides to flood them with a deadly neurotoxin. The danger hasn't been direct to spessmen for a while, but it's definitely there.

> A door melting is, sadly, pretty meaningless, because every door on the station bar some maint doors comes with a firelock which is totally invulnerable to fire. 

Makes me wonder if we need all these firelocks then.

**Comment by Rurik123** [comment]
> Hell no, a plasmafire in toxins storage can currently eat robotics and make R&D inhospitable. The PR removes that unless atmosia or the AI decides to flood them with a deadly neurotoxin. The danger hasn't been direct to spessmen for a while, but it's definitely there.

I'll defer to your experience there since I haven't been able to play much lately, though from what I remember most of the time the fire fizzles out in the hallway, yes? Been a while since I've seen a fire eat into RnD or robotics itself. Then again, also been awhile since I've seen a plasma fire.

**Comment by S34NW** [comment]
What sort of performance gains are we looking at from this PR? Like, actual numbers?

**Comment by Spacemanspark** [comment]
Plasma fires are devastating in science mostly because of how many canisters there are.
Even then, they typically burn through the walls to wreck the havoc they do.

**Comment by Kepplerx** [comment]
Plasmafires dont happen that often, and when they do they are usually not that big either, unless intentional. To say they would make it run smoother seems weird to me, because they happen so rarely, and burn out so fast.

I also agree with what has been said above, there becomes less and less need for a Atmos department at all, there are few viable projects, no issues to really fix, no real power over station (Noone would notice if noone even worked there). Might as well just PR out Atmos Techs soon.

**Comment by AffectedArc07** [comment]
> Might as well PR out atmos techs

This is how you get people to stop taking your seriously.

**Comment by AffectedArc07** [comment]
After a round today where the active turf count managed to reach a staggering **21,000**, I am even more inclined to merge this, given that we need optimisations to beat through that stack, before it multiplies out into this fucking mess

image
Context: This is a grid that is a z-level. If a square is red, its an active turf.

**Comment by TDSSS** [comment]
That's lavaland, right?

**Comment by Wojz** [comment]
> That's lavaland, right?

It is. Happened today. But hey, it IS lavaland, let's just remove that please. Please? :^)

**Comment by AffectedArc07** [comment]
> That's lavaland, right?

Your point? Active turfs are active turfs wherever you put them, we don't categorise by Z. Having this many ATs means ones on the station never get processed because of how big the queue already is.

**Comment by Kepplerx** [comment]
> > Might as well PR out atmos techs
> 
> This is how you get people to stop taking your seriously.

It may perhaps not be my smartest comment, so will take that, just a frustration as Atmos appears to become more irrelevant, that is a whole another point however. 

As to this PR, I did not even consider Lavaland using as much processing power as ya say it does, due to atmos, but I must ask if there are other ways to solve that issue? Does Lavaland need atmos at all?

**Review by AffectedArc07 — APPROVED** [review]

**Comment by AffectedArc07** [comment]
> > > Might as well PR out atmos techs
> > 
> > 
> > This is how you get people to stop taking your seriously.
> 
> It may perhaps not be my smartest comment, so will take that, just a frustration as Atmos appears to become more irrelevant, that is a whole another point however.
> 
> As to this PR, I did not even consider Lavaland using as much processing power as ya say it does, due to atmos, but I must ask if there are other ways to solve that issue? Does Lavaland need atmos at all?

It does need atmos because its designed (correct me if I am wrong) so the pressure is low enough for the KA to function, but not too low that you start taking pressure damage. This allows people to wear different suits and armour combinations to aid fighting megafauna. 

I would like to point out that the station turf number also still swells to 2000, so I am still going to accept any optimisation we can get.

**Comment by TDSSS** [comment]
> > That's lavaland, right?
> 
> Your point? Active turfs are active turfs wherever you put them, we don't categorise by Z. Having this many ATs means ones on the station never get processed because of how big the queue already is.

Well, it opens the door for potential optimisations, like giving ATs on lavaland less priority than ones on the station.

Or in the most extreme case, make lavaland unsimulated turfs set to the right pressure for KAs, though that has some undesirable side effects.

**Comment by Wojz** [comment]
Is there actually a reason why floors should melt when walls don't, then? Feels kind of odd icly that floors and walls have different durability when we consider this is a space station which has to be durable in every direction. If plasmafires don't space themselves they'll need atmos to come put them out.

**Comment by Fox-McCloud** [comment]
This has a ~20% improvement to `process_cell`; one of the most expensive procs, in the entire game, and a ~30% improvement to `share_air`.

This has the effect of making the entire air system roughly ~9.26% cheaper, overall; fairly sizable, to say the least.

**Comment by S34NW** [comment]
> Is there actually a reason why floors should melt when walls don't, then? Feels kind of odd icly that floors and walls have different durability when we consider this is a space station which has to be durable in every direction. If plasmafires don't space themselves they'll need atmos to come put them out.

This is starting to become more appealing, since it gives people more incentive to interact with a fire (and not just closing that room off while it spaces itself), while also saving a decent performance cost as Fox outlined above.

**Comment by Kepplerx** [comment]
> > Is there actually a reason why floors should melt when walls don't, then? Feels kind of odd icly that floors and walls have different durability when we consider this is a space station which has to be durable in every direction. If plasmafires don't space themselves they'll need atmos to come put them out.
> 
> This is starting to become more appealing, since it gives people more incentive to interact with a fire (and not just closing that room off while it spaces itself), while also saving a decent performance cost as Fox outlined above.

If the fire burns through the floor, it dissipates, as it cannot burn the firelocks. For example, a fire started in Science Toxins storage will burn, but not breach the wall nor firelocks, then burn the floor and dissipate. As such these fires would be a lot less dangerous, unless in maints where there are no firelocks

**Review by Kyep — APPROVED** [review]
I know this is going to be deeply unpopular with players, but I am approving this regardless, because:
- Our server is stuck at 100% CPU usage most of the time. Not just on the primary core (used by byond) but also on the secondary core (used by offloaded processes). As I write this, its green alert with <100 players... and we're still at 100% on both cores we (due to the limited, single-threaded nature of byond) are able to use. Imagine how much demand there is for server CPU when its 150 pop and the station is in chaos. To put it bluntly, we NEED performance optimizations, and this is a 10% performance optimization to atmos, which is typically THE most CPU intensive thing on the server. Nobody I've talked to likes the idea of losing the fire-burns-walls feature... but the performance gain is worth it. As server host I am deeply uncomfortable with byond running at 100% CPU usage at all times. 
- We cannot simply upgrade the server's CPU itself to solve this problem. I've been looking into that idea, and while we could get up to a 10% improvement if we rebuilt the server on the best available hardware, 10% improvement is probably not enough to get our CPU usage under 100%. We need to optimize the codebase, and given how much CPU atmos takes, we must start with atmos.
- This PR opens the way for more optimizations later, which will improve performance even more. Potentially we might get further broad improvements to the whole atmos system - but those would require this PR as a foundation. So future work depends on this PR.
- The main problem with this PR is the fact it sorta deprives atmos techs of a job. They no longer need to fight fires as much. However I think this is solvable. We could give them roundstart SM access so they can help with that, or other things to do - other things that don't have such a severe performance impact on the server. Plus even with this PR they'll still need to repressurize areas burned out by fires.
- This PR currently has map edit priority on boxstation... which means its holding up the rest of the substantial queue of map edit PRs.... as such we need to get it out of the way sooner rather than later as its delaying other things being merged.

**Comment by SabreML** [comment]
Is this really the only possible way to improve performance? Surely there's some other solution to this that doesn't involve making our atmospherics system even weaker than it already is.
Where is the line on removing features for (relatively) small gains?

<hr>

>We could give them roundstart SM access so they can help with that, or other things to do - other things that don't have such a severe performance impact on the server.

Most supermatter setups don't actually need much maintenance, and only involve actual work in the first 20 minutes or so. There's also the fact that there's six engineers *(Or more realistically, three)* who will be butting in to do the same thing.

> Plus even with this PR they'll still need to repressurize areas burned out by fires.

How often do you actually see an atmos tech repressurising a room or fixing a breach? Nine out of ten times there's an engineer with a RPD who fixes everything before you can even turn up.

**Comment by S34NW** [comment]
> 
>     * The main problem with this PR is the fact it sorta deprives atmos techs of a job. They no longer need to fight fires as much. However I think this is solvable. We could give them roundstart SM access so they can help with that, or other things to do - other things that don't have such a severe performance impact on the server. Plus even with this PR they'll still need to repressurize areas burned out by fires.

Give them an actual firefighting role by making fires contained but persistent if this PR is being forced through. Repressurising areas almost always gets fixed by engineers who have access to air alarms and can easily make an RPD. If atmos is to stay relevant outside their little room, having fires not space themselves out and requiring atmos firefighting intervention would go a long way in my personal opinion.

**Comment by Spacemanspark** [comment]
If the game itself lacks functionality, all the optimizations in the world mean nothing.
Yes, that may sound a tad extreme, but we're talking about gimping the hell out of plasma fires. One of the more 'classic' of SS13 disasters. And while the removal of classic things can sometimes be fine--I was happy with the removal of roundstart singularity/ tesla because it added something a lot more interesting to toy around with instead, for example--I don't think removing features like this for the sake of 'optimization' is something that should become common practice. I'm sure that many features could be tossed out that would improve performance, but then we lose out on the factor of features and fun that the playerbase can enjoy or use.

**Comment by Cocacolagua** [comment]
I understand the concern this PR tries to aliviate, yes atmospherics is a buggy piece of garbage, yes the server needs the optimization it can get and yes this PR probably does optimize it by a lot;

However, I raise concerns on the following:
- Time-wise, how long will plasma-fires last if say, we destroyed a plasma-tank in a 5x5 room?
- Damage-wise, how much structural and player damage will plasma-fires cause if we take the former example?
- Functionality-wise, how does this affect the turbine, burn-mixes and the TEG?

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
