### PR TITLE
New admin freeze sprite

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This changes the admin freeze sprite to something that makes a little more sense. The current one has the issues of just looking like someone is shocked, the text has a 50% chance of being upside down, and it isnt incredibly obvious. 

This PR replaces that with a no entry sign. The benefits of this are it is incredibly obvious, and will always be in the correct orientation due to how it is designed.

**Images of sprite/map changes:**
j4N8ah7GUo

**Changelog:**
:cl:
tweak: Admin-frozen players have a new overlay
/:cl:

Ideally, I would like mainly administrators to comment on this, since its going to impact them the most.

### CODE REVIEW

**Comment by Shadeykins** [comment]
Uncertain. It looks good, but part of the issue with freezes is that they are jarring. They destroy any sense of atmosphere when they're performed because they're quite glaringly obvious as is.

I'm not sure if there's a tidy fix for that though other than making admin prison work again (even then, telepoofing can be a little jarring).

**Comment by KasparoVy** [comment]
Looks way too wack for me man. I can appreciate the idea but the current one seems so obvious already but this taking up an entire tile with an eye-searing immershun-destroying whatsit is just too much

I'd sooner have it changed to 'bluespace-ice' and just legit freeze the dude in a block of suspended disbelief. At least that feels a bit more in with the vibe.

**Comment by AffectedArc07** [comment]
You know what, the bluespace ice sounds like a good idea. I will test with sprites later

**Comment by Ralta** [comment]
I honestly don't mind it being glaringly obvious. Either you make it subtle and people don't realise, or you make it obvious and slightly affect immersion. I'd much rather people didn't fuck with someone that's frozen than `muh mersion`.

That said, the ice block idea sounds hilarious and I'd love to see it sprited.

**Comment by MrMagolor** [comment]
>That said, the ice block idea sounds hilarious and I'd love to see it sprited.

Iceblock sprites already exist, I'm pretty sure? As the TOUCH effect for cryostylane on a mob.

**Comment by SkeletalElite** [comment]
I don't really thing it makes much of a difference, but a new player might not understand what this means, at least the "admin" text on the old one makes it fairly obvious to new people an admin is doing something. With this they might just think its some wacky weird in game effect and start doing something to them because they can. I know sometimes the text isn't the right way but I think most people can tell what it says fairly easily.

**Comment by Tayyyyyyy** [comment]
SkeletalElite brings up a good point. Most experienced players at this point already know for the most part what admin freeze is. The new sprite should keep the "admin" text for people who don't already know.

**Comment by Ty-Omaha** [comment]
This is going to have the exact of the intended effect because it is so out of place, people will want to click it to figure out why they have a giant no entry sign on them.

**Comment by Ty-Omaha** [comment]
What if the current sprite was kept and it was just mechanically impossible to interact with an admin-frozen person

**Comment by variableundefined** [comment]
I also agree that this is way too jarring and people may not even get it is an admin freeze sprite. They'll definitely get there's a sprite.

**Pull request closed without merging**
