### PR TITLE
Removes a gas chamber space ruin

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do
Removes `gasthelizards.dmm` from the codebase.

## Why It's Good For The Game
Unless I am missing a subtle inside joke of SS13, this is a gas chamber with a medical facility to do live experiments on a specific race, also known as a concentration camp.

This is the name of this zone: `Disposal Facility 17` in case someone might mistake it for anything else.

## Images of changes
This is the ruin, it spawns on the live server.

image

## Changelog
:cl:
del: Removed a space ruin.
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
Unit test fails here:
```
FAIL: /datum/unit_test/config_sanity 0.6s
	REASON #1: Space ruins exist in the game config that do not have associated datums
```
No clue how to fix this, the config file is not tracked to my knowledge? So I cannot edit it.

**Comment by Sirryan2002** [comment]
You'll need to edit the example folder config

**Comment by Miraviel** [comment]
> You'll need to edit the example folder config

That worked, much appreciated.

**Comment by lewcc** [comment]
Just for the record, /tg/ replaced it with a somewhat charming ruin that's a decrepit gas station instead of...well, what it currently is here.

https://github.com/tgstation/tgstation/pull/64304

I know @Contrabang has expressed interest in porting it over

**Comment by S34NW** [comment]
Good, this and the nazi crap can all go

**Comment by LiberatedWaveMan** [comment]
been to this ruin before and tbh it was actually kinda jarring to see the setup and its implications; we absolutely don't need a concentration camp ruin

**Comment by TORE01** [comment]
>gasthelizards.dmm
What in the space fuck?

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
