### PR TITLE
Adds smoothing to plating, add shadows to give depth.

### PR DESCRIPTION
**Pull request by SamHPurp**
This PR smooths plating and adds shadows so you get the impression that the plating is lower.

image

This extends to Asteroid turfs too, so the asteroid turfs look lower than the main station's turfs.... Checkout the shadows.

image

:cl: Purpose & AndrewMontagne
add: Adds tile smoothing to plating. Plating should now be a bit more of a 3d look...
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
It's beautiful :')

**Comment by Bram961** [comment]
Love the shadows, don't like the new plating icons, they look a bit bland would it be at all possible to apply a bit of shading to the inside of the plating? as in you have the crossbars with 4 metal squares inbetween, I think it might look quite nice to have the crossbars look slightly higher than the squares.

**Comment by SamHPurp** [comment]
@Bram961 I'm not a great artist, if you'd like to send me a new version please do.

**Comment by tigercat2000** [comment]
I agree with Kluys. Try adjusting the old plating sprites to smooth over replacing them with this.

**Comment by Bram961** [comment]
nah I tried the white but Ill send those when I wake up again because I'm tired and drunk right now.

**Comment by SkeletalElite** [comment]
I prefer the first ones that were posted.
They look nice.

**Comment by KasparoVy** [comment]
Same, first was blessed

**Comment by Bram961** [comment]
https://puu.sh/BH5q8/7c59eb2dd9.dmi @SamHPurp old plating icons with new shading to make the middle sections deeper.

**Comment by SamHPurp** [comment]
I don't think you've understand this Bram, but I appreciate the attempt

**Pull request merged**
