### PR TITLE
Removes Stamina Damage from Mech Scattershot

### PR DESCRIPTION
**Pull request by matttheficus**
## What Does This PR Do

Removes Stamina Damage from Mech Scattershot.

## Why It's Good For The Game

Removes the stamina damage from the Mech Scattershot. Adds an additional 5 brute per shot in return.

midbullet > midbullet2

## Changelog
:cl:
del: Removes Stamina Damage from Mech Scattershot
/:cl:

### CODE REVIEW

**Review by hal9000PR — APPROVED** [review]

**Comment by RagingLemons1** [comment]
The only thing it's good at is killing people, and does that very well. Leave it in, for use against full power newvampires or nukies.

**Comment by Wojz** [comment]
> The only thing it's good at is killing people, and does that very well. Leave it in, for use against full power newvampires or nukies.

There's many more actually balanced weapons a that work against both of these. Nukies shouldn't be one shot stamina critted by a crew mech. Vamps aside from one spec, at full power, already suck at fighting mechs.

**Review by SteelSlayer — APPROVED** [review]

**Comment by Denthamos** [comment]
With the stamina damage removed from it I can agree to that bringing it more in line with the rest of the mech weapons.  Just verifying since the original projectile was just a buckshot form a CR20, this does not change the stamina damage on the Cr-20 correct?  If it does not, then my approval is on it.

**Comment by matttheficus** [comment]
> With the stamina damage removed from it I can agree to that bringing it more in line with the rest of the mech weapons. Just verifying since the original projectile was just a buckshot form a CR20, this does not change the stamina damage on the Cr-20 correct? If it does not, then my approval is on it.

C20r is unchanged. `/obj/item/projectile/bullet/midbullet` is unchanged (the c20r round). It now uses `/obj/item/projectile/bullet/midbullet2` which is just 25 brute per hit (instead of the 20 brute + stam damage).

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
