### PR TITLE
Secure Armory - last time i swear 

### PR DESCRIPTION
**Pull request by orelbon**
Adds Blast doors, making for easy access, also gives the racks windoors so the armory doesn't all vent when there's a breach.

ok here's my reasons why this is a good idea; 1. the warden is not forced to open the shutters, if he wants to distribute weapons by hands it's his prerogative, this also makes it easier for the warden if he doesn't want to distribute everything by hand, and so he won't have to get a locker and pack it with things because he can't carry all the thing needed in the armory 2. it gives the security officers easy access in case the warden, HoS, etc.. are not available, so the Ai just needs to press a button 3. security officers have no reason to take more than they need, i dont see security officers taking more than they need when i put all the riots suits, masks, and guns on the tiny table in the warden's office, also the warden or HoS can monitor them if they feel it necessary.

**Not Finished, Still a work in progress** 

@SamCroswell Thanks for the suggestions

Im open to suggestions on what to put in the hallway between the warden and the armory.

new armory

### CODE REVIEW

**Comment by orelbon** [comment]
@tigercat2000 @Fox-McCloud any opinions?

**Comment by Fox-McCloud** [comment]
Still not a fan, to be honest.

Also, adding an EMP box to the armory is a badddd idea.

**Comment by orelbon** [comment]
@Fox-McCloud Why would adding a box be a bad idea?

**Comment by TheDZD** [comment]
Because EMP grenades cause severe damage to station electronics in a wide area, murderkill IPCs in a wide area, and generally for station crew, there shouldn't really be any situations where they're preferable over the alternatives.

**Comment by Spacemanspark** [comment]
Because EMP's + security == idiot officers that toss them like flashbangs, killing IPC's, or human crew with mechanical parts.
I do like the way you've placed the armory, though.

**Comment by orelbon** [comment]
I see what you mean ill remove it in the next commit.

**Comment by orelbon** [comment]
oh god please merge before something conflicts

**Comment by Fox-McCloud** [comment]
This hasn't even been up 24 hours....please don't mergebeg before that.

**Comment by orelbon** [comment]
@Fox-McCloud im just kidding, but yeah im nervous that something will cause a conflict and i probably won't be able to fix it.

**Comment by Fox-McCloud** [comment]
you put firelocks over the top of doors--that's a no no in terms of mapping.

**Comment by orelbon** [comment]
@Fox-McCloud i though the automatically went below the doors, ill fix it now.

**Comment by orelbon** [comment]
well i dont know what happened to the saved .dmm file i had with the changes because it changed back to the regular map, i cant fix it now, it would mean remapping the whole armory, and considering no one really cared much for this im closing it.

**Pull request closed without merging**
