### PR TITLE
Stamina damage no longer bypass some checks

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR moves most of `adjustStaminaLoss` procs to `apply_damage(damage, STAMINA)`
affected:
all stamina damage, caused by weapons and attacks, such as batons, power gloves, slimes, xenos
all stamina damage, caused by magic(cult)
all stamina damage, caused by abilities(revenant, vampire)
all stamina damage, caused by martial arts
stamina damage, caused by EMPd robotic chest

not affected:
all stamina damage, that HEALS instead of damaging
all stamina damage, caused by reagents(there is not many though)
suicide stamina damage(it exists??)
critical stamina damage(it sometimes adds more damage to force you lay down longer)
all stamina damage, caused by illness
stamina damage, caused by parrying

## Why It's Good For The Game

stamina damage, caused by weapons and such, bypassing checks is not good
with the same damage numbers, stunbaton and disabler would deal different damage? that shoulnt be here

since there is not many items, adding stamina mod to physiology, those will work better:
Blood-Drunk status effect, reduces stamina damage
Blood Swell status effect, reduces stamina damage
forceshield status effect, slightly reduces stamina damage(i dont know what is this but its in code)
Revved up! status effect, reduces stamina damage(traitor chainsaw effect)
aranesp reagent effect, reduces stamina damage
Sealed Joints Implant, slightly increases stamina damage

## Testing

compiled, tested vampire's blood swell, i hope i shoulnt test all that

## Changelog
:cl:
fix: Weapons, xenos attacks and many other no longer bypass some stamina damage checks. Blood swell and other status effects, that reduces stamina damage, now works on batons and such.
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
Stamina damage by illnesses should probably stay the same, for the same reason as reagents in that is not really affected by armor, or whatever you're wearing

**Comment by HMBGERDO** [comment]
> Stamina damage by illnesses should probably stay the same, for the same reason as reagents in that is not really affected by armor, or whatever you're wearing

sure, im fine with that

**Comment by S34NW** [comment]
Please merge `upstream/master` into your branch to fix CI failing due to external factors.

**Review by DGamerL — CHANGES_REQUESTED** [review]
Seems fine, just needs a merge master and a doublecheck if any new weapons have been added that do stamina damage

**Comment by HMBGERDO** [comment]
should be fine

**Review by Contrabang — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]
LGTM, haven't seen or heard of any issues on live

**Review by S34NW — APPROVED** [review]

**Pull request merged**
