### PR TITLE
Adds tracker electronics to the autolathe (for solar tracker)

### PR DESCRIPTION
**Pull request by RudiPardieck**
This adds tracker electronics to the autolathe (for solar tracker)

Also moves desttagger and handlabeler out of the hacked section of the code. Has no in-game effects.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Given that tracker electronics are otherwise only obtained in a cargo crate that comes with their assembly, and that the assembly is only obtainable via cargo, I am unsure about this.

No issues with the other bits (though hand labellers can be gotten from the art vend machine in dorms), especially when that one tech takes the tagger and goes SSD or gets spaced. Replacing that or hooking up the chef with one would be nice.

**Comment by RudiPardieck** [comment]
Solar trackers use the assembly of a normal solar panel. Meaning you can just dismantle a working solar panel and add the electronics to it. Having to order a crate from cargo with 16 solar panels just for one little electronic board felt like overkill to me. 

I think you misunderstood my second change. It is just refactoring.

**Comment by FalseIncarnate** [comment]
I didn't misunderstand it, was just stating how having hand labellers available in the auto lathe wasn't a major concern to begin with. Making the destination tagger more accessible is nice too.

I am aware that the tracker goes in a normal solar assembly. I was pointing out that it's rare you need JUST the electronics, and would still need an otherwise unbuildable assembly to build a tracker. Combined with the fact that typically the only times you need a new tracker is if you are building a new array or massively repairing an array that got bombed / meteor'd, you usually need assemblies to go with it anyways to build solar panels too.

For clarity, not shooting down that addition, just wondering if it makes that big of a difference to have them outside crates.

**Comment by Fox-McCloud** [comment]
Inclined to agree with @FalseIncarnate and his analysis here.

**Pull request closed without merging**
