### PR TITLE
Restricted Cult Summon Areas

### PR DESCRIPTION
**Pull request by uraniummeltdown**
3 rooms on the station are selected at roundstart. They must be actual rooms, no maintenance or maint areas like Incinerator/Turbine/Disposals/Electrical Maint, no space, no Solars, no Toxins Testing Area, and no Cryodorms because it's Cryodorms. The cult has to summon Nar'Sie/demons in one of those rooms, if the room is too small walls can be taken down by welders/juggs/artificers.
This should make the summoning phase more interesting than just teleporting everybody to Virology or Xenobiology every time and stealth summoning it

:cl:
balance: Cult can only summon Nar'Sie or demons in 1 of 3 random rooms on the station
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
This feels like a mad indirect nerf. What happens if you roll three mad rooms like the HoS office, AI sat and Bridge. Cult already can feel like swimming against the tide due to communication issues. I don't see this making the gamemode more interesting, rather making it much harder to win.

**Comment by taukausanake** [comment]
Yeah, maybe if instead you get a hint to where the location is that would be better. Don't remember how it's done currently. Also might want to remove the head offices and AI Sat/Upload too from rooms to select.

Is there an issue with only having one room to summon at? If the crew/AI pays attention they should be able to find out where the cult is easy enough, unless they go murdercult

**Comment by SamHPurp** [comment]
This seems like a terrible idea.

**Comment by uraniummeltdown** [comment]
Cult as of now is too easy to win, you can convert a whole department (Science or Medbay) easily and stealthily and then summon in a place where nobody has any chance of stopping you.
If you roll something like HoS Office, AI Sat, Bridge, you just adapt to it, it keeps the summoning part fresh rather than it being the same heavily fortified areas over and over again.

**Comment by KingPhilipIII** [comment]
If cult is so easy to win... Why is it the vast majority of the cults I see fail? 

I personally support the change, because they do it on TG, and outside of maxcap bomb memes blasting the cult into oblivion, it's a bit more interesting watching Security try to stop the cult from summoning while they try to get on the rune in an orderly manner. Granted TG uses the Cult Master system where one individual can summon all the cultists, which makes gathering your fellow cultists far easier.

If anything,this will just stop the one person with eight manifested spirits from summoning because an officer will go blast their chest in with a shotgun and be done with it.

**Comment by uraniummeltdown** [comment]
@KingPhilipIII In my experience most cults on Paradise tend to win, only losing if they were really unlucky and spotted by a Secborg or AI in the wrong place at the wrong time, or if all cultists are newbies

**Comment by Birdtalon** [comment]
>I personally support the change, because they do it on TG

That doesn't mean its the right change for Paradise.

**Comment by KingPhilipIII** [comment]
@Birdtalon  I'm not saying that because they do it on TG it's right for us, but rather I've seen the changes in action and in general I believe it's a positive one. TG might be more chaotic but they do a lot of stuff right.

@uraniummeltdown  I see most cults fail in the end, and I don't consider a single cultist pulling off the summon two minutes from shuttle arrival as success, even though that is a technical victory.

**Comment by Aurorablade** [comment]
I was considering do this before but was trying to focus on my cult balance pr I have up. You do need to cut some areas from being picked. But yes I did see tgs thing with this.

Also I did the redo I PURPOSELY left the summon annoucement vauge. No annouceing location. I want the crew to panic and scramble. I cannot support the PR with that included. I will go over this more later.

**Comment by uraniummeltdown** [comment]
I understand that you want the crew to panic but it leaves the Summoning stage with no counterplay, non-cultists wouldn't lose hope and give up if they still had a shot. The station is just way too big and there are many heavily fortified areas that take ages to get too, surrounded by reinforced walls and slow double airlocks. Plus, cultists have easy access to teleport runes, they can be from Sci Maint to Arrivals Maint in an instant and set up wall runes.
Also, when they summon they're surrounded by shields, Sec can't instantly mow them down.

**Comment by Aurorablade** [comment]
They only have shields around them when scribing. And limiting the summon location to an area makes for some counterplay. I know how hard the crew can tide am area. I did it to prevent that.

**Comment by uraniummeltdown** [comment]
But that gives the cult an incentive to convert more of the crew, so that they face less opposition when summoning and ensures that the cult interacts with the crew more

**Comment by FalseIncarnate** [comment]
This sounds like the reverse of the typical "I ded pls nerf"... "I won pls nerf"?

First off, this is added difficulty without a good in-game reason to support it. If anything, I could see blacklisting certain "protected" areas (like making it so you can't summon in the chapel or permabrig), but arbitrarily requiring a random area makes no sense.

Secondly, announcing the name and location is pretty much the worst way of handling this. Vague announcements like "blood magic detected on the southern half of the station" or "a doctor is scribing a giant sigil" leave some ambiguity and preserve panic while helping people focus their search. Saying "Muckledarned Cultist is drawing a Nar'Sie rune in the Vault" is going to have everyone, their brother, their brother's friend, and their dog bum-rushing that spot faster that you can say "valid".

Finally, if a game has a perceived high win-rate, there's usually 2 or 3 things to consider:
1. Potential Observer Bias: You only are sampling from your own limited data set, which may make it seem higher than it is. I'd like to see some official statistics on this if possible, since game-mode win rates is actually very useful data in general.
2. Player Skill: Some people are generally better at certain modes than other. A successful traitor requires different levels and areas of skill than a successful cultists, and this means you may have a strong lone wolf who is a poor fit for the team-based modes on your side. Just like in Overwatch, team comp does affect your win chances (we don't need widow AND hanzo, one of you pick a damn tank and be useful!). A cult of newer or inexperienced cultists is going to typically perform poorly in comparison to a cult of veteran powergamers. Same goes for the chances of defeating the cult. Hardcore sec mains are going to crack down on a cult much more efficiently than a handful of newbies, even if they have the same resources available, by pure virtue of experience.
3. "The Meta": An established "meta" strategy likewise will see varied results as people learn and adapt to it, causing a surge in win-rates followed by increasing counters to the strategy returning the win-rate to normal until the new "meta" is found. Inventive strategies may fail more often than the tried-and-true, and even the tried-and-true requires a degree of coordination that can be lamentably lacking in any team endeavor.

If your goal is to reduce win-rates for the mode... well, this is bringing an armed nuke to a knife fight.

**Comment by Fox-McCloud** [comment]
I see this as potentially interesting, for a number of reasons.

Stealth cult, as far as I'm concerned, isn't that great. Unlike nuke ops, who have to go for specific hostile objectives and account for a wide variety of factors to stay stealthy from start to finish, cult can pretty much just play the "hide in a corner in maintenance and summon before much of anyone has a clue"

This is a bit of a simplification, but it's the way I've seen it go quite frequently, and that's not something I think is good for the overall game.

Ultimately, this will generate more crew vs cult conflict---and it will also encourage a build up on the cult's behalf (of weapons, armor, and constructs) to help defend and fight against those who are trying to prevent the summoning. That's a good thing, in my opinion, while also giving those who want to avoid the conflict an idea of where to *avoid* so they don't bump into a mess of cultists.

**Comment by scrubmcnoob** [comment]
I echo @Fox-McCloud on the benefits of this PR.
Cult is too easy right now. You could literally one man summon nar'sie as a cultist if you had enough golems at your disposal, etc.
There's no incentive to go loud, just get golems, a few guys, and summon in some random maint where no one will find you and you're done. It's not a challenge and honestly just ends the round really stopping much of the crew vs cult situation.

**Comment by Birdtalon** [comment]
I completely understand the above comments from @Fox-McCloud and @scrubmcnoob and I wish there was more incentive for cultists to go loud. However the general sentiment from the staff team in the past has been admonishment of go-loud cult players who were able to cause a large amount of devistation and chaos. As I understand it the senior staff see cult as being a game-mode which is supposed to be played as stealthy. Perhaps I have got this completely wrong but that's certainly how it has felt in the past for this particular game-mode

**Comment by Anasari** [comment]
I think we should give this PR a go and adjust it if it turn out to make cult too hard. 

I've seen too many cult round where the cult just steamrolled over the rest of the crew by...well, not doing anything. No convert, just a bunch of golem.

Hell, I've seen a round won by a single diona and 8 ghosts.

**Comment by Aurorablade** [comment]
okay as a note this picks 3 possible areas, I DO NOT like how you are snowflaking on a var on some areas to return false.
I am pretty sure there has to be a way like TG does to get areas on the station z level in a list, though the maintainers might be okay with.
Recall the objectives are gated, summon is always last.

I will NOT stand by the announcement naming the location.

**Comment by Pathid** [comment]
The way I look at it, win-rate being too high isn't the problem. It's winrate **AFTER THE OTHER OBJECTIVES** being extremely high. When the summoning is trivial to pull off once the other objectives are through, it becomes an anti-climax, not really the highlight of the round. Hopefully there's room somewhere in there for middle ground between murdercult and rewarding total non-interaction with the non-cult after you secure those objectives.

**Comment by KingPhilipIII** [comment]
I generally play the murder cult to be honest. One man army, I can take down half of security before they know why their officers are disappearing, and then I can usually keep the survivors busy hunting me down while my allies convert and conspire.

**Comment by scrubmcnoob** [comment]
Where is the consensus coming from that cult has to be quiet? The new cult literally encourages loud cult as you need a whole base and all their new gear that isn't very obscure or concealable.
The objectives of saying spread blood does this too, if you need more blood, go cut people once and let them run around bleeding everywhere.

9/10 cult rounds are either all cultists are incompetent and never played, sec captures them all, or the cult simply uses xenobio or some obscure place and quickly summons their objective with the bare minimum even though rest of sec was geared and still kicking.
In my opinion, it's not very interesting for both sides. Why should sec build up an arsenal while cult can summon in any unknown location and why should cult build up an arsenal of constructs and other stuff if they're just summoning and then restarting the round in like five minutes.(Shuttle is insta called and then sent to CC)
Where's the fun action the game mode should bring of open crew vs cult?

**Comment by TullyBurnalot** [comment]
@uraniummeltdown Due to the significant change this poses, the global announcement would have to be removed in order for the PR to be merged.

**Comment by uraniummeltdown** [comment]
@TullyBurnalot Removing the global announcement entirely? Or just reverting it back to what it was like before

**Comment by TullyBurnalot** [comment]
@uraniummeltdown If you wish to keep the announcement in some form, it'd have to remain vague, as per what Fethas said. Something like "North area of the station" or somesuch, rather than a direct laser pointer.

**Comment by Dualzed** [comment]
The biggest problem with summoning nar'sie is getting all 9 people to stand still in each spot.
While I believe that Cult gamemode is currently unbalanced favoring the cult, this would really kill it, there will be no summoning nar'sie at the shuttle, no summoning nar'sie in the bar, because the cult have such total control, and so on, it's this or that room that needs to be prepared, in most cases the rooms used have enough space without having to expand.

Making it harder just provokes more meta and powergaming, play to win, cheese every mechanic, and really that just makes the game frustrating to play.

You keep forgetting this is a game, and you need to ask your self, is this actually fun, or is this just a "I ded, plz nerf."

I suggest to take a step back and look at the current issues, that is, the strength of their runes, and their ease of communication.

**Comment by uraniummeltdown** [comment]
@TullyBurnalot Ok I'll revert the announcement back to being "Somewhere on the station", although I don't really want to...but I will

**Comment by Fox-McCloud** [comment]
once conflicts are fixed, I'll merge this.

**Comment by TullyBurnalot** [comment]
@uraniummeltdown

**Comment by Ralta** [comment]
Oh good, more controversial merges - my favourite.

**Comment by TDSSS** [comment]
I realize it's probably too late for changes to this, but have you considered determining the three rooms and just...making summoning in them A LOT easier than outside of them? Like maybe make it need twice as many people as before to summon outside of them, and increase the summoning time?

So that people are strongly encouraged to go for those rooms, but aren't strictly speaking forced to?

**Comment by uraniummeltdown** [comment]
Done @Fox-McCloud

**Comment by Spacemanspark** [comment]
I've been in support of a cult nerf for awhile.

**Comment by mrturkeytoe** [comment]
https://www.youtube.com/watch?v=umDr0mPuyQc

**Comment by mrturkeytoe** [comment]
OH GOD NO. GOD NO.

**Pull request merged**
