### PR TITLE
Adds in BS12's fancy chat prefix icons

### PR DESCRIPTION
**Pull request by ZomgPonies**
- What it says on the tin, fancy, subtle icons replacing OOC, LOOC, DEAD, ADMIN, and MOD chat prefixes.
- Did not include code for the PM stuff, since we use mutiple channels and don't have the right icons yet.

### CODE REVIEW

**Comment by fj45** [comment]
Blerh, don't like these at all.

**Comment by Nienhaus** [comment]
I found these pretty stupid when I tried Bay. You have the preference to turn it off right?

**Comment by Spacemanspark** [comment]
I like it.
But yeah, I'd have a setting to disable it for those who don't.

**Comment by Fox-McCloud** [comment]
I've seen these before and I don't personally like them either; if they're a config option, it wouldn't be as bad.

**Comment by ZomgPonies** [comment]
There's no config option right now, and quite frankly I'm not the biggest fan of them either.

**Comment by Glloyd** [comment]
Yeah, they're not the greatest. Some people like them though, and I know on Bay there's a preference toggle between them and the classic style.

**Pull request closed without merging**
