### PR TITLE
Donksoft Sniper Rifle now available in STORE! - The Punisher!

### PR DESCRIPTION
**Pull request by Terilia**
### Donksoft is pleased to announce our new product, the Donksoft Sniper Rifle is now available in various Stores!!!!!

image
### With our matte plastic color coating it looks and feels just like the real deal! 

You can load it up with either our new Foam Force Sniper Darts, or the Donksoft Riot Control Sniper Foam Darts! 

Just load the magazine, and off you go! Nothing will stand in your way - not even your **Neighbour's cat**! Just look through our patented scope (no lenses included!) and shoot away.

### BUY TODAY AND RECEIVE A FREE MAGAZINE PRELOADED WITH OUR FINEST RIOT FOAM DARTS FOR FREE! CALL 555-2391-112 OR YOUR TRUSTED LOCAL RETAILER.

<br>
<br>
<br>

This PR adds the Donksoft Sniper Rifle into the spawnpool of the trader event, so it can be acquired in game. 
:cl:
add: Added the Donksoft sniper into the Trader spawnpool.
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
Shouldn't it be also added to the lavaland donksoft vendor at the syndicate base? Or is it already there?

**Comment by Spacemanspark** [comment]
I don't care if this thing shoots instakill bananas or something, that poster makes me immediately :+1: this just because of how much it made me laugh

(Just kidding lmfao, but still plz merge I want this)

**Comment by Terilia** [comment]
> Shouldn't it be also added to the lavaland donksoft vendor at the syndicate base? Or is it already there?

Good point, I will bring it up and if greenlit adjust it.

**Comment by Terilia** [comment]
Important update to the PR - I made the Selling Box that has nothing to do with the PR and is just there as a joke 3d!

**Comment by MrMagolor** [comment]
You should probably add the info on it being in donksoft vendors to the changelog, too.

**Pull request merged**
