### PR TITLE
Atmos control computer typo fix

### PR DESCRIPTION
**Pull request by Burzah**
## What Does This PR Do
Fixes a small typo with Atmospheric Tank Control computers where the wrong unit of measure was being displayed for temperature.

## Why It's Good For The Game
Provides clarification.

## Images of changes
Qhqb2hYbXj

## Testing
Examined multiple tank controls and checked if the units representing temperature had changed. 

## Changelog
:cl:
spellcheck: Fixed a a typo on atmos supply control computer to display proper unit of measure
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
```
Error: our build differs from the build committed into git.
Please rebuild tgui.
```

**Comment by Burzah** [comment]
> ```
> Error: our build differs from the build committed into git.
> Please rebuild tgui.
 
Today has been a learning experience. Updated and retested the fix.

**Review by Sirryan2002 — APPROVED** [review]
good once TGUI is rebuilt

**Review by farie82 — APPROVED** [review]

**Comment by Burzah** [comment]
> good once TGUI is rebuilt

Rebuilt and retested

**Pull request merged**
