### PR TITLE
[s] Adds Contrabang to Commit Access

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

Adds Contrabang to Commit Access

## Why It's Good For The Game

Updating documents good

### CODE REVIEW

**Review by SteelSlayer — APPROVED** [review]

**Review by S34NW — APPROVED** [review]
Let him cook

**Review by GDNgit — CHANGES_REQUESTED** [review]
Why is he grape flavored

**Review by lewcc — APPROVED** [review]
self merge you won't

**Comment by Contrabang** [comment]
Stale, please reopen once review are addressed

**Comment by Contrabang** [comment]
reviews addressed, looks good to everyone else

**Review by AffectedArc07 — APPROVED** [review]
You need to selfmerge this, its the rules

**Pull request merged**
