### PR TITLE
Actually Fixes Those Stupid Plants (By Fixing Alternate Appearances)

### LINKED ISSUE #4972: Permanent Disguises 2.0---Houseplant Edition
It's still possible to get permanently stuck as a plant.

Dunno how it happens, but it's still happening.

### PR DESCRIPTION
**Pull request by Krausus**
I can't believe I didn't notice this sooner. Alternate appearances store a list of the mobs they're visible to, but when they iterate through that list to hide the alternate appearance from them, they use a nice, fast, typeless for loop, which never bothers to check whether the mob is null before blindly trying to access mob vars on it. This means that, if an alternate appearance gets applied, a mob in the viewer list gets deleted, and then the alternate appearance is deleted, it'll runtime when it gets to the deleted mob, and not remove the alternate appearance from any others that came after it in the list. This is easily reproducible, and solved by ~~simply using a typed for loop~~ actually adding the missing code to make mobs remove themselves from the viewers list of alternate appearances they're viewing.

~~I did *not,* however, put a type in the `display_to` for loop; if someone makes the mistake of passing a non-mob in there, I *want* it to runtime.~~ I also did a couple other minor tweaks.

I'm sorry for making your immaculate alternate appearance code even slower, @RemieRichards. We're just tired of becoming stuck looking like plants forever. If it's any consolation, this is probably what was causing tgstation/tgstation#16860 and tgstation/tgstation#18941.

Oh by the way, fixes #4972.

:cl:
bugfix: Players will ALMOST DEFINITELY never get stuck as plants anymore. I mean it this time!
/:cl:

### CODE REVIEW

**Comment by RemieRichards** [comment]
This isn't the real fix, viewers of AAs are supposed to remove themselves during deletion, preventing nulls, the real issue is those nulls being there, this just puts a plaster over it.

**Comment by Krausus** [comment]
... they remove themselves during deletion? But I never touched that code, which means... it still tries to loop over the now non-associative list by key...

 :disappointed::gun:

**Comment by RemieRichards** [comment]
yes of course they remove themselves during deletion, they're referencing the AA and the AA is referencing them, preventing GC on both sides, this removal is (supposed) to prevent nulls also, the true issue will be with that code.

**Comment by RemieRichards** [comment]
ARRRGHH
Atoms clean up their AAs on destroy, but mobs never clean up the ones they're seeing, that's the real issue, it's a missing section of code.

**Comment by Krausus** [comment]
Ah, I see the issue with that code now. That code *never existed.* On deletion of a-- yup.

But, without the previous fix to viewing AAs clobbering each other, they'd still only delete the most recent one. Adding that code should fix it fully...

**Comment by RemieRichards** [comment]
Anyways, I'll be fixing this up for /tg/, preventing clobbering and nulls, thanks for helping me find them.

**Comment by RemieRichards** [comment]
also I am SO glad I encapsulated everything behind procs, meaning I can happily change the list of AAs to an assoc list of lists of AAs without any of the other code noticing it.

**Comment by Krausus** [comment]
> an assoc list of lists

But... but *why?*

**Comment by RemieRichards** [comment]
well you removed the Assoc nature of it, making the main list the "list of AAs", I chose to keep the Assoc nature of it, as that was part of the initial design, being able to grab things fast (Assoc list key accesses > looping for things)

it makes setting up a bit slower, removal a bit slower, but all accesses faster, it's just a thing I wanted to keep around (I *DID* write that bit intentionally :P)

**Comment by Krausus** [comment]
Ah, fair enough. Just seems like needless complexity to me, though.

**Comment by RemieRichards** [comment]
Also I didn't really mention but this is only for ```viewing_alternate_appearances```, atoms have no reason to have multiple of the same type of AA except for when they're viewing the AA instead of owning it, owned AAs are still just an assoc list of AAs

**Pull request merged**
