### PR TITLE
Bugfix: Adds UI button for blob splitting

### PR DESCRIPTION
**Pull request by DogsParadise**
Fixes

## What Does This PR Do
It makes me an artist, Blob Ross.

- Fixes the UI Button, there was never a sprite for the button but it was very much in-game.
I am actually suprised noone has noticed before.

## Why It's Good For The Game
The button.. was always there.. but there was no Icon.
- It actually shows newer blob players a button to split instead of going into a random tab and needing to search for it.
Some people have no clue they can even split.

## Images of changes

image

image

image

## Changelog
:cl:
fix: Fixes UI button blob
/:cl:

### CODE REVIEW

**Comment by shmabuu** [comment]
While the concept is nice and I do like making things easier to learn/understand, a UI button at is one use only and stays there  isn’t great (far as I know, if it does go away please correct me.) If it disappears after the one use that would be very nice

**Comment by DogsParadise** [comment]
> While the concept is nice and I do like making things easier to learn/understand, a UI button at is one use only and stays there isn’t great (far as I know, if it does go away please correct me.) If it disappears after the one use that would be very nice

That's something a coder can best do and I imagine not me ;p

**Comment by AffectedArc07** [comment]
Please make sure your PR sprites are actually up to date in the future. I thought it wasn't symmetrical till I looked at the icondiff
image

**Comment by DogsParadise** [comment]
> Please make sure your PR sprites are actually up to date in the future. I thought it wasn't symmetrical till I looked at the icondiff
> image

:eyes: it was just one pixel.. and i had to load in the game again. I'll make sure to update it next time ;p

**Comment by SabreML** [comment]
Not 100% sold on the arrow marking being pitch black, personally.
It works just fine as it is of course, but it might look better as a more blob-like colour.

**Comment by DogsParadise** [comment]
> While the concept is nice and I do like making things easier to learn/understand, a UI button at is one use only and stays there isn’t great (far as I know, if it does go away please correct me.) If it disappears after the one use that would be very nice

- Button now removes itself after being succesfully used.
- Button now doesnt appear if your a split

**Comment by DogsParadise** [comment]
To fix CI

**Comment by Sikroth** [comment]
Tangentially related, does the Blob UI have a button for the **resource storage** nodes? I feel like there was 1 missing thing I noticed last I played blob and that might've been it? But it's been a while.

Good PR either way, not having to check the verbs to make sure you use all your abilities when some have a button is good.

**Comment by DogsParadise** [comment]
> Tangentially related, does the Blob UI have a button for the **resource storage** nodes? I feel like there was 1 missing thing I noticed last I played blob and that might've been it? But it's been a while.
> 
> Good PR either way, not having to check the verbs to make sure you use all your abilities when some have a button is good.

No it does not have a current sprite, Yes there is current code for the UI.
But the same way as what I fixed with this PR, it just exists and fails.

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
