### PR TITLE
Ports TGs Syndicate HUD icon

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do

Ports the syndicate hud icon from TG and in turn also updates the syndicate ID card
## Why It's Good For The Game

because I forgot to change it in my IDs PR. The old one looks like a 5 year old drew it and has been bothering me.
## Images of changes

PR1

Shading removed on the ID card. Needs to be flat for a card.

image

## Testing

I didn't, it's a DMI change
## Changelog
:cl: Bmon, TG
imageadd: Ported the Syndicate HUD icon from TG.
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Does this update the syndicate balloon as well? Might be worth changing that as well since it's kind of the bit

**Comment by Bm0n** [comment]
> Does this update the syndicate balloon as well? Might be worth changing that as well since it's kind of the bit

can do

**Comment by Bm0n** [comment]
> Does this update the syndicate balloon as well? Might be worth changing that as well since it's kind of the bit

nevermind the ballon is already using this newer sprite lmao

**Review by S34NW — APPROVED** [review]

**Review by Sirryan2002 — APPROVED** [review]
sprite diffs look good

**Pull request merged**
