### PR TITLE
Re-enables revolution.

### PR DESCRIPTION
**Pull request by gt33**
🆑 Reeeeimstupid
tweak: Re-enables rev in secret. Has about same chance of occuring as Slings.
/🆑

### CODE REVIEW

**Comment by Danielhuren** [comment]
I WANT THIS TO HAPPEN

**Comment by Spacemanspark** [comment]
It was removed from the rotation for good reason. And from the occasional time that the admins run it, it's easy to see why.

**Comment by Danielhuren** [comment]
also on a serious note it will be hilarious if this goes through

**Comment by tigercat2000** [comment]
You can't change this. It's a config option, changing the example configs will not be reflected on the server. Petition the administrators.

**Comment by Crazylemon64** [comment]
This does nothing except for downstream repos - the server team would need to directly change the file themselves.

**Pull request closed without merging**
