### PR TITLE
Makes emagged drones more identifiable

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kluys, Kyep & DarkLordpyro
tweak: Emagged drones are now readily identifiable, as their lights turn red.
/🆑

Sprite credit: Kluys

syndi-drones

drones-inhand

drones-onhead

### CODE REVIEW

**Comment by Bram961** [comment]
Like the idea, dislike the icon and the fact that this clearly wasn't tested.
Drones use 3 icons, a base one, a movement one and an "eyes" icon.

Let me make a new dmi file for a moment.

**Comment by Bram961** [comment]
https://puu.sh/wItwG/e3bcdea809.dmi

**Comment by Kyep** [comment]
Updated sprites to use Kluys' ones.

This also fixes a off-by-one pixel in the non-emagged ones eyes.

Updated screenshots in the PR description.

**Comment by ktoma36** [comment]
Fantastic, now all we need is to make it so drones cant interact with airlocks from pipes

**Comment by deep-fried-faceplant** [comment]
Is the sprite for wearing drones as a hat changed as well? Traitors carry drones on their head all the time, and it's impossible to tell if the drone is emagged or not.

Side note, why the hell can drones even be worn as hats, other than rule of cool or cuteness factor?

**Comment by Kyep** [comment]
@Bram961 Sorry for the inconvenience, but in order to make this work, I'm also going to need sprites for:
- An emagged version of the 'drone' in icons/obj/objects.dmi 
- An emagged version of the 'drone' in icons/mob/head/dmi.

**Comment by Bram961** [comment]
Ill do that in a few, this old and senile senior admin needs to get out of bed first which is a major task. Will edit this comment into the one with the file and pictures once I"m done

**Comment by Kyep** [comment]
Thanks Kluys.

Screenshots in OP updated.

**Comment by matt81093** [comment]
Looks good. I agree that there should be some indication of change. Maybe occasional sparking as well? Just throwing out the idea. This does seem nicely sprited regardless.

**Comment by Kyep** [comment]
Not going to add random sparking. 
You can tell they're emagged at a glance, now.
Sparking doesn't add much - except for the potential for plasma fires.

**Comment by Ar3nn** [comment]
I agree that it being completely stealth is bad, but making it such a stark color-change seems too heavy-handed a change. I'd agree more with the sparking, because all synthetic things spark when damaged anyway, so it'd be possible for crew to assume it's something else. This completely ruins any chance of maint drones going undetected, because it's blatant and unmistakable, nothing else changes the color of the drone. 👎

**Comment by Very-Soft** [comment]
I've got to ask... why do the drones need to be super easily identifiable as emagged? I get that there should be some sign, but that usually comes from their actions. Such an obvious change makes it extremely easy to tell at a glance from 3 of the 4 movement directions, and makes it impossible for a drone player to act with any manner of stealth if anyone has any idea what that sprite change means.

I'd like to ask, if there's such an obvious indicator of an emagged drone, then should there should be a similarly obvious indicator on borg sprites too? Just as a matter of comparison.

**Comment by Kyep** [comment]
@Very-Soft I was discussing with the staff team, about what they thought of how OP emagged drones can be. We all agreed they needed a nerf. I put up a poll with many options. "Give emagged drones more obvious sprite" got the most votes.

**Pull request merged**
