### PR TITLE
The Skill Level is now sk_baby - Nerfs Bloodcrawl

### PR DESCRIPTION
**Pull request by SchrodingersWolf**
## What Does This PR Do
This PR nerfs Bloodcrawl by adding in a 2 second cooldown before it can be recast, but ONLY if the bloodcrawler is phasing in. (i.e. The bloodcrawler will have to stay on the station for 2 seconds before they can leave via bloodcrawling again.)
To compensate for this., all slaughter demon variants' (Except for shadow demon) health has been increased by 40 HP.

**Exact values below**
Slaughter demon (From wizard blood vials): 200 -> 240
Lesser Slaughter demon (The type that spawns in midrounds): 130 -> 170
Laughter demon: 175 -> 215
Cult Slaughter demon: 500 -> 540

## Why It's Good For The Game
Personally I feel like slaughter demons are fine, but there is a vocal push to nerf slaughter demons' instant escape abilities (The whole appear/hit someone/sink back/repeat routine is a bit cheesy indeed), and Rurik already signed off on the 2 second cooldown/health increase, so I'm putting it in as well.

## Testing
Tried bloodcrawling into the bloody mess I made. No cooldown was incurred. Tried bloodcrawling out of the bloody mess I made. I was stuck on the station for 2 seconds before I can go back into the Blood Realm(?).

## Changelog
:cl:
tweak: Slaughter and laughter demons now has a 2 second cooldown before it can sink back into blood
tweak: Slaughter and laughter demons now all have 40 HP more compared to before
/:cl:

### CODE REVIEW

**Comment by Edan52** [comment]
I don't think the health increase compensates for the weakness this provides, it makes instant clean strategies much more effective.

**Comment by SchrodingersWolf** [comment]
> I don't think the health increase compensates for the weakness this provides, it makes instant clean strategies much more effective.

It probably will, but it is a nerf after all.

Though if demon hits a person, said person would likely be bleeding profusely for demon to have an avenue of escape.

**Review by Sirryan2002 — APPROVED** [review]
code is good

**Review by lewcc — APPROVED** [review]
Code looks good

**Pull request merged**
