### PR TITLE
Baseball Bats, Baseball Burgers

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Adds baseball bats and burgers from tgstation. Bats are crafted from 5 wood sheets, move mobs a few tiles away, do 10 damage. Baseball burgers are made from a bat and bun, either microwave or table crafting.
baseball

:cl:
add: Baseball bats added to the game, are craftable from 5 wood planks.
add: Baseball burgers can be made with a baseball bat and a bun, either microwaved or table-crafted.
/:cl:

### CODE REVIEW

**Comment by MrFroztee** [comment]
Excellent. Shame the bats aren't from Hippie, that's the good stuff.

**Comment by Draconic-saint** [comment]
1) pics pls
2) Since I assume the bat is in the centre, and the ball is the "bun", wouldn't a joke hotdog item be more apt?

**Comment by FalseIncarnate** [comment]
gonna agree with jedr on that one, you typically have hot dogs at ball games too, so thematically that would fit even better. Unless the entire burger is recolored like a giant baseball... hmm....

**Comment by MrFroztee** [comment]
> Since I assume the bat is in the centre, and the ball is the "bun", wouldn't a joke hotdog item be more apt?

Now why the hell would anyone eat a baseball bat on a hotdog bun

**Comment by tylerh95** [comment]
It seems we've been dropping / changing meme features lately, I feel like a baseball bat and a bun should not be food but idk

**Comment by theColdflame** [comment]
a 10 damage weapon with knockback that carries enough plausible deniability that sec will catch a demotion/jobban for taking it off people before they use it?

**Comment by taukausanake** [comment]
Need hotdogs and baseballs. I wonder if you can use a bat on a ball in your hand to throw it out a good distance the direction you are facing. Maybe have a bit of RNG with distance and direction too

**Comment by Lady-Luck** [comment]
>a 10 damage weapon with knockback that carries enough plausible deniability that sec will catch a demotion/jobban for taking it off people before they use it?

Don't toolboxes do similar damage?

**Comment by Draconic-saint** [comment]
that burger looks nasty

**Comment by Fox-McCloud** [comment]
I think you guys are missing the point of the burger.

It's a ball and bat---the bat is...a bat, obviously. The burger is the ball. It's white, it has red stitching.

The recipe for it is about as close as you can get, especially in the context of spessmen food/kitchen logic.

**Comment by Fox-McCloud** [comment]
Batter up.

**Pull request merged**
