### PR TITLE
Nerfs Electric Guitar Volume

### PR DESCRIPTION
**Pull request by Birdtalon**
This PR reduces all the sounds for the new electric guitar by 7db each. Many people have been complaining that the sounds are incredibly loud and drown out all other noise. Compared with the other instruments, the electric guitar is almost double the amplitude. A whole bunch of people have had to disable their instrument noises in preferences because of this new guitar.

audacity_2017-07-14_09-05-29
audacity_2017-07-14_09-05-52

I have attached a screenshot of a sound from the old electric guitar, my reduced sound, and the regular non-electric guitar for comparison. 
You can also listen to all the sounds: original and quieter ones here: [http://server.birdtalon.com/eguitar/](http://server.birdtalon.com/eguitar/)

🆑 Birdtalon
tweak: Reduces the volume of the electric guitars
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Seems a bit quiet now; should be similar amplitude to the regular guitar.

**Comment by Spacemanspark** [comment]
Ya, that's a bit too quiet.

**Comment by Birdtalon** [comment]
@Fox-McCloud @Spacemanspark I pinged you both on Discord, but how about this? This is reduced by -7db instead of -10db and is more in line with the regular guitar. Top is electric, bottom is acoustic guitars.

audacity_2017-07-12_23-32-18

**Comment by Ataman** [comment]
@Birdtalon for "loudness" comparisons I recommend using the dB waveform in Audacity as it reflects our perception of loudness more realistically. 

g_comp

Apart from that, it looks (or rather sounds) pretty good now.

**Comment by Birdtalon** [comment]
@Ataman Great. I'll take a look at that tonight and see how they compare. Thanks.

**Comment by Birdtalon** [comment]
I have updated this to make the sounds slightly louder more in line with the acoustic guitar. Link in the OP has been updated with the new sounds now reduced by 7db. @Fox-McCloud @Spacemanspark

**Comment by Fox-McCloud** [comment]
update your pics, too!

**Comment by Birdtalon** [comment]
My mistake, I thought I had updated them. I have updated them now, with screenshots both in "Waveform" mode and "db Waveform" mode.

**Comment by Birdtalon** [comment]
@Fox-McCloud & @Spacemanspark  I have updated the sounds and pics for the -7db slightly louder sounds. Mind giving it a listen and see if it's still a bit quiet for you?

**Pull request merged**
