### PR TITLE
Adds 17 new posters. 

### PR DESCRIPTION
**Pull request by TravellingMerchant**
posters

All with unique names and descriptions. There are both legit and contraband posters.

### CODE REVIEW

**Comment by Anasari** [comment]
Nice addition to the flavour of the station. +1

**Comment by Aracino** [comment]
Is that a mauzer poster 0.o

**Comment by FlattestGuitar** [comment]
Marry me.

**Comment by Fruerlund** [comment]
Gives Paradise something unique. Very nice!

**Comment by Spacemanspark** [comment]
Leave the honk borg module poster out, as it's a fluff item for a specific player.
Other than that :+1:

**Comment by SamHPurp** [comment]
Remove the Honkborg fluff one as @Spacemanspark says, but the rest look good.

**Comment by LightFire53** [comment]
No communist canada poster, can not condone.

**Comment by Fox-McCloud** [comment]
What's up with the `PET` thing? Also, the "clean" and gun posters don't look so good.

The Noble series is a bit *too* specific for a poster, especially when it's essentially elevating one borg sprite module over the others.

**Comment by TravellingMerchant** [comment]
The pet posters were something in the works long ago, those pest killing drones that were talked about. They were being coded by Crazylemon. I thought it a shame for the sprites to go to waste as the work stopped, so I stuck them in the poster.


I will change the gun posters to other Borg types.

**Comment by TravellingMerchant** [comment]
posters

**Comment by ktoma36** [comment]
Are these going to be added to the list of items that can be ordered from the cargo computer?

**Comment by SamHPurp** [comment]
Still very much against all the borgs, including your rejected fluff borg.

The Pet ones don't make much sense without the related thing implemented.

Also your terror spider one appears bigger than all other posters, is this intentional?

**Comment by Fox-McCloud** [comment]
Believe, train, both airs, and probably honk all fit well; the others just don't seem to fit the general poster themes well.

**Comment by TravellingMerchant** [comment]
Don't fit the original poster themes?












I would say they are pretty close.

**Comment by Fox-McCloud** [comment]
Would you midn splitting off each of the posters into a separate pic? It will be easier for us to decide which ones are 👍 and which ones are 👎

**Comment by TravellingMerchant** [comment]
posters-sheet

**Comment by SamHPurp** [comment]
Using the following format, Five = Put this in!, One = Please do not add this. Three is neutral, Two and Four are positively/negatively neutral.

1. One - too much focus on your borg sprites already.
2. One - as 1.
3. One - this is your rejected fluff sprite and it just looks silly...
4. One - dull, uninteresting and out of place for a science station
5. Three - a bit out of place to focus on a mining cyborg.
6. Four - Looks cool, weird that it is larger than the other sprites though, and could maybe do with a little lightening.
7. Two - Focus on the validhunter chaplain mode, no thanks.
8. Two - could be made more interesting than simply a Mediborg and the word 'Heal' ala the style of the Obama HOPE posters...
9. One - not in the game currently, and if they were they'd be better as advertisements?
10. One - as 9.
11. Three - No strong feelings either way
12. Two - seems far too simplistic for what you're trying to say...
13. One - as 12, but an even less common colour.
14. Two - This is the opposite of good advice or advertisements, which is what the posters should be... and for a very rare antag. If It said Don't Blink, this'd be a three.
15. Four - A little dull but is inoffensive, would be fine.
16. One - Joke ERP reference, no.
17. One - I don't even understand what this one is supposed to be? Some meme I'm unfamiliar with?

Don't take all this negative critism too much to heart, I think its great to add more posters, but could maybe be done with a bit more thought behind them.

**Comment by TravellingMerchant** [comment]
These are not all legit posters. The valid hunting one is a contraband.  The angel one is also a contraband item.

3 can be removed I suppose. Mining cyborg and medical cyborgs were added so it wasn't just a focus on the Noble borgs. (It would also make sense for Nanotrasen to advertise new things.) The gun is the same as the other gun advertisements. Just adds more variety. 

Most people seem to like the No ERP poster in the discord.

Coins are just an album cover.

**Comment by jughu** [comment]
The erp poster must go trough

**Comment by Necaladun** [comment]
General conensus here seems to be yes to some posters no to others, I'll hopefully get a more detailed one soon, but I doubt this'll pass with all of these.

Might wanna do a PR with the more basic ones (air, dig, heal, train, honk), and wait on others

**Comment by Necaladun** [comment]
Sorry for letting this one slip past!

I'd say remake the following in a PR: 5, 6, 7, 8, 11, 12, 13. 
All simple and good additions.

The others Sam raises some good points with an in general add to clutter. The above 7 mentioned though should be no issue.

**Comment by Crazylemon64** [comment]
There's no response for like 12 days so if you wanna get the posters in - make a new PR with the posters Neca mentioned above, and we can go ahead

**Pull request closed without merging**
