### PR TITLE
Removes Thanksgiving/Fall Decorations--Adds Christmas Tree

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Marked as High priority because of the delay of the previous PR due to fixing bugs with shuttles.

original PR: https://github.com/ParadiseSS13/Paradise/pull/2882

- Removes fall decorations
- Adds a Christmas tree to the bar
- adds 2 wrapping papers to cargo

Other
- Updates the Christmas presents
 - Removed the bag of holding and manuals
 - Added in a bunch of plushies/toys/etc.
 - Not mapped; just for if admins want to use it.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
No presents?
Ehhhhh.

**Comment by Tastyfish** [comment]
@Spacemanspark Cargo can wrap small things in that gift wrapping paper that nobody ever uses :gift:

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

I thought about that, but then I was reminded of last year's behavior; one person rushing all the presents at round start and taking as many of them for himself as possible.

**Comment by TheDZD** [comment]
Yeah, Thanksgiving decorations have been around for too long.

**Comment by orelbon** [comment]
so uh....wheres ponies, christmas is tomorrow...

**Pull request merged**
