### PR TITLE
Grenades should more reliably trigger heat-based reagents now

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
tweak: Chemistry grenades should now more reliably trigger reactions based on it being super hot
/:cl:

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
Beaker assemblies exist for this precise reason.

**Comment by Crazylemon64** [comment]
I mean, amping temperatures up seemed to be the intent of the original grenade code, but it never called reaction code. Should I rip it out in its entirety?

**Comment by DaveTheHeadcrab** [comment]
Personally I don't see any point in artificially ramping the temperatures up.

**Comment by ProperPants** [comment]
@DaveTheHeadcrab What is a beaker assembly? Do you mean a crafted grenade with two beakers in it?

**Comment by Crazylemon64** [comment]
@ProperPants A beaker assembly is a beaker with an igniter-trigger assembly latched on top; When "tripped", it raises the temperature of the beaker by 30 degrees. The reason why your pyrosium-oxygen grenade isn't working, by the way, is that oxygen and pyrosium react comparatively slowly, which is not enough time in the 2-4 seconds it has to react to have any meaningful effect. It's better as a payload chem, rather than a trigger chem.

**Comment by Fox-McCloud** [comment]
:-1: 

This is what beaker assemblies are for. If you're wanting to do heat-related chemical shenhanigans, that's what you should be using; grenades are for foam or instantaneous reactions---it also doesn't make any sense that the temperatures get added t together when every single other instances of temperature behavior runs counterpart to this.

**Comment by Crazylemon64** [comment]
Alright! I'll strip out the broken functionality, then!

**Comment by DaveTheHeadcrab** [comment]
@ProperPants 
Pyroisum and oxygen heat up over time, it's not instant. Moreover, it doesn't actually cause a fire if that's what you were expecting.

**Comment by ProperPants** [comment]
@Crazylemon64 Thanks for the info!
@DaveTheHeadcrab I was expecting them to maybe be able to trigger stabilized chems when used in a grenade, but that might already happen in grenades. I haven't played around with them too much.

**Comment by Fox-McCloud** [comment]
Status on this?

**Comment by Crazylemon64** [comment]
I mean, what I would change by completely excising any vestige of this behavior is absolutely nothing, so I'll just close this.

**Pull request closed without merging**
