### PR TITLE
Removes peacekeepers

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
del: Removed peacekeeper borgs.
/🆑

This PR reverts https://github.com/ParadiseSS13/Paradise/pull/7465

There are only two changes introduced in 7465 that this PR keeps, and they're both entirely back-end / codebase clarity things that are invisible to players. The changes kept are:
- nations borgs being /mob/living/silicon/robot/nations instead of /mob/living/silicon/robot/peacekeeper. This path change is kept simply for clarity.
- the  icon for the emagged engineering borg module "electrically-charged arm" stays in icons/mob/robot_items.dmi. I agreed with Fox that this was a better place for it than the general items.dmi, since the latter already has a metric ton of other icons in it.

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
let's hope we can... keep the peace in this pr.

**Comment by uraniummeltdown** [comment]
It hasn't even been a month since they were merged, they fill a niche of crowd control and non-lethally stopping harm. Sure people memed with them but it's the same with any new feature

**Comment by jughu** [comment]
Peacekeepers are just less chaotic secborgs admit it

**Comment by SamHPurp** [comment]
Peacekeepers were a piece of satire that wasn't understood properly

**Comment by KingPhilipIII** [comment]
Long live the egg bots.

**Comment by Spacemanspark** [comment]
I was willing to try them.
Unfortunately, I don't see any use being made of them. There's one total player I've seen consistently play the damn things (outside of being a meme), and they also seldom play. Outside of that, it's just memes. They were created as a literal meme at first, in addition.

**Comment by uraniummeltdown** [comment]
How about this:
No Secborgs on Code Green, only Peacekeepers
On activating Code Blue they turn into Secborgs and only Sec module is available
And the other way round when dropping to Code Green

This way, Peacekeepers on Code Green with no threats, and Secborgs when there is a known threat to the station
In my opinion the station does not need big tanky Secborgs on Code Green

**Comment by Varghh** [comment]
Yes, please and thank you.

**Comment by Ziiro** [comment]
>let's hope we can... keep the peace in this pr.

**# HUMAN HARM**

**Comment by Spacemanspark** [comment]
The problem isn't one of balance at this point.
It's the part that it's a literal joke borg and is being treated/ used as such.

**Comment by alexkar598** [comment]
I don't see peacekeeper borgs being abused anymore but this is a change I can get behind

**Comment by DesolateG** [comment]
Seems like it would be better to deal with the players going around using them like that. Rule 0 violations.

**Comment by Necaladun** [comment]
In their current implementation, they're really not filling the niche we'd hoped for - a kinda light secbot. The way they're set up is too different, silly and memey to really do that. While they could be changed to do that, all the discussions I've seen of how to do that would involve basically completely reworking them - changing the modules on them, and the sprite for them. Additionally, taking up a slot other borgs could be using to be less effective ones hampers a lot of sec/borg work.

While I'm certainly interested in some form of "light" secborg, especially for code green only, this isn't at all filling that niche, and is frustrating and annoying many people. 

Discussions and polls on this seem to show this as a pretty divided issue, with about 40/40/20 keep/remove/don't care, so whatever we do here, ~40% of people aren't going to get their way, which is a shame. However, after the first week or so of their overuse (as any new feature gets), their impact and usage appears to be very minimal, while still having the problems of using up borg slots and being generally useless.

Thus, it's mine (and the other heads, with some slightly different reasoning), opinion that we're better off without them in their current implementation. If someone wants to work on a new version with different modules/sprites/etc, we'd be interested, although because of the amount of impact and division this version has had, I highly, highly encourage you to make posts on the forums/discord/etc about it before comitting too much to the PR and possibly putting lots of work in for naught.

**Comment by Allfd** [comment]
I think its just a replacement for Service borgs really.

I have not noticed any sec borg players playing then like sec borgs.

They are a new twist on service borgs, just instead of cash they have cookies.

**Comment by Vivalas** [comment]
I support this PR since it doesn't set a precedent where secborgs would be limited to peacekeepers below green.

I also don't like it though since peacekeepers are kinda fun to meme as, even if that's the whole point the PR exists.

**Comment by Tayyyyyyy** [comment]
I don't ever see service borgs anymore! I think if the wholesome fun parts of the peacekeeper borg were merged into the service borg, then everyone could be happy.

Right now peacekeepers are just meme machines that turn into overpowered killers when subverted.

**Comment by Allfd** [comment]
If you made the service Borgs eggshaped and gave them a harm alarm they would basically be peacekeepers that gave out cookies instead of cash.

I may be a bit thick, but I really don't understand the problem with peacekeeprs outside of possibly the chem dispenser.  They are essentially just resprited service borgs.

**Comment by Doukhan** [comment]
Service borgs are completely useless that's why you never see them.
Peacekeepers at least have the memes, and are also incredibly deadly when emagged hence the current popularity.

I don't see why we can't just tone down the harm alarm/cookie dispenser and slap them along with the hug module onto the service borg, maybe keep the egg sprite too.

**Comment by jughu** [comment]
If you remove it atleast make the sprite selectable by secborgs egg of justice!

**Comment by Kyep** [comment]
The sprite isn't good either. Total removal is the best option.

**Comment by DesolateG** [comment]
Why not just nerf them to the point that no one will use them?

**Comment by Kyep** [comment]
Because they mainly exist to be annoying, and making them even more useless makes them even more annoying. Therefore nerfing them doesn't solve the issues with them.

Because they should never have been merged in the first place.

Because nerfing them to the point that nobody uses them is just like removing them, except they're still part of our codebase, can still generate bugs, still require maintenance, etc. In short, nerfing to the point nobody uses them is inferior to simply and cleanly removing them.

**Comment by DesolateG** [comment]
"Because nerfing them to the point that nobody uses them is just like removing them, except they're still part of our codebase, can still generate bugs, still require maintenance, etc. In short, nerfing to the point nobody uses them is inferior to simply and cleanly removing them."

It seemed to work for the Missionary Staff.

**Comment by Kyep** [comment]
The heads/maints wanted it that way. Had I done otherwise, the PR would have been rejected.
Don't assume my PRs always reflect my wishes. Almost every PR gets at least one update/change that the heads/maints want, but I don't. Sometimes those are minor, like replacing "if (" with "if(", but sometimes they completely change the PR.
If you're still salty about the missionary staff, then do your own PR, and try to get it passed.

**Comment by tigercat2000** [comment]
I was initially for the removal of peacekeepers, but I'm not anymore; while, yes, they could probably do with some sprite and fluff changes, they really aren't _that_ bad.

**Comment by adamkad1** [comment]
the maint staff hates huh?

**Comment by KingPhilipIII** [comment]
NOOOOOOOOOO MUH EGG BOT

**Comment by alexkar598** [comment]
...yay

On 2017-12-05, at 6:13 PM, "Crazy Lemon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #8283<https://github.com/ParadiseSS13/Paradise/pull/8283>.

**Comment by scrubmcnoob** [comment]
rest in peaces

**Comment by alexkar598** [comment]
In pieces rather

On 2017-12-05, at 7:20 PM, "scrubmcnoob" <notifications@github.com<mailto:notifications@github.com>> wrote:


rest in peaces

**Comment by MrFroztee** [comment]
God rest the souls of the poor eggboys. A legacy cut short by the loud minority, I sympathize with your plight.

**Comment by MrFroztee** [comment]
@alexkar598 also no he meant peaces

**Comment by Domkek** [comment]
Hugbots were my favorite thing. RIP

**Comment by DesolateG** [comment]
@Donkek well you can thank the loud minority and the coders within that loud minority who's only unironic cocky response to criticism is "code it yourself then".

**Comment by Allfd** [comment]
It is still not clear to me how the downsides of peacekeepers are any different then service borgs.

**Comment by DesolateG** [comment]
They're not. Standard and service borg in fact. 

Speaking with others about it last night I hope for tweaks to be made and reintroduction. Sprite change, cookie limit before needing to recharge, and having the harm alarm only be "near"deafening as the red text suggests.

**Comment by jughu** [comment]
Can we make the sprite to be added to secborgs

**Comment by DesolateG** [comment]
The egg borg sprite was one of the complaints

**Comment by alexkar598** [comment]
I'm happy they are gone,I play ai a lot and I see almost every round some Borgs who play peacekeeper instead of actually going medical to heal people or going engineering to fix holes or going security to help get rid of the antags. Egg bots were a waste of metal,cyborg positions and posibrains

**Comment by KingPhilipIII** [comment]
I don't know, I've seen eggbots break up bar fights before. They're not entirely useless.

**Comment by DesolateG** [comment]
Time to set cyborg to high and play service

**Comment by jughu** [comment]
>eggbot sprite was one of the complaints

When you really want something removed

**Comment by Fox-McCloud** [comment]
>I'm happy they are gone,I play ai a lot and I see almost every round some Borgs who play peacekeeper instead of actually going medical to heal people or going engineering to fix holes or going security to help get rid of the antags. Egg bots were a waste of metal,cyborg positions and posibrains

Using this logic, we should remove the service and standard models, as well, since they're both "screw around" models.

Someone going around playing music or spamming cheese is arguably *less* useful than someone who is capable of breaking up fights.

If Paradise is going down the road of "forcing players to play 'useful to the station' roles", that's a dangerous precedent.

**Pull request merged**
