### PR TITLE
Adds a plain white beret

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Something quick and easy that could be entirely separated from the service stuff - A plain white beret
Adds it to the mime locker, chefdrobe and loadout for all to use
Also adds the black beret to the mime locker and bardrobe

## Why It's Good For The Game
More customisation options

## Images of changes
image

## Testing
Booted server, spawned with beret from loadout, walked to mime locker, chefdrobe and bardrobe to make sure all items were present

## Changelog
:cl:
add: Added white beret - in loadout, chefdrobe and mime locker
tweak: Added black beret to bardrobe and mime locker
/:cl:

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]
lewcs good to me

**Comment by SchrodingersWolf** [comment]
This is a Medical Beret nerf 😔

**Review by DGamerL — APPROVED** [review]
Code LGTM - Do grey use different hat sprites?

**Comment by Christasmurf** [comment]
> Code LGTM - Do grey use different hat sprites?

They haven't got beret sprites in their thing so I assume they're fine, nobody has complained in my previous PRs where I haven't added grey beret sprites + no current open issues regarding it

**Comment by DGamerL** [comment]
> > Code LGTM - Do grey use different hat sprites?
> 
> They haven't got beret sprites in their thing so I assume they're fine, nobody has complained in my previous PRs where I haven't added grey beret sprites + no current open issues regarding it

Neat, LGTM then

**Review by Burzah — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
