### PR TITLE
Terrorspiders Part 2

### PR DESCRIPTION
**Pull request by Kyep**
This is part 2 of Terror Spiders.

It adds:
- Spiderlings, and spider eggs
- Green spiders, the nurse type, which focus on lair building, blooddrinking, then egg-laying
- White spiders, the infector type, which focus on infecting crew with spider eggs
- Mother spiders, a boss type, which creates an infestation when killed

Notes for maintainers:
- This currently includes the code for part 1, but once part 1 is merged, this will be rebased on the post-merge master such that all part 1 code is deleted from the diff, and there is only one commit.
- I am doing it this way because I talked with DZD, and he said it was preferable to do it this way.
- There is no map file, no AI, etc in this PR.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/5651

**Comment by Crazylemon64** [comment]
https://www.youtube.com/watch?v=qQRWfxkCdU4

**Comment by Kyep** [comment]
Oh, that was set an hour ago, while I was working on this, and did not notice. Oh well.

**Comment by Crazylemon64** [comment]
Winter is over! @Kyep

**Pull request closed without merging**
