### PR TITLE
Tweaks codeowners

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Makes me codeowner of tgui executable files (HC vote was had beforehand to agree this)

## Why It's Good For The Game
These shouldn't be changed without thorough review, so we're adding some more protection to them.

### CODE REVIEW

**Review by GDNgit — APPROVED** [review]
shawn what if you codeownered the nian file

**Review by DGamerL — APPROVED** [review]
Why stop here, I think you should also codeowner the TGUI bundle

**Comment by Oyu07** [comment]
> Why stop here, I think you should also codeowner the TGUI bundle

> Paradise/tgui

**Review by Contrabang — APPROVED** [review]
can we have someone codeown `.github/CODEOWNERS`?

**Comment by AffectedArc07** [comment]
> can we have someone codeown `.github/CODEOWNERS`?

~~Me~~

**Review by Burzah — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
