### PR TITLE
Makes the "lightbulbs don't burn you" thing less awful

### PR DESCRIPTION
**Pull request by tigercat2000**
you can now remove lightbulbs regardless of intent if you are able to
remove them, if you're on disarm or grab you'll burn yourself if you
aren't able to, if you're on help or harm you'll get a message of "too hot
to touch!"

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
It's a bit weird that the most hostile of intent doesn't result in you burning yourself.

**Comment by Necaladun** [comment]
We all know disarm is the most hostile intent.

**Comment by fludd12** [comment]
I imagine it's so you don't punch directly upwards into an incandescent bulb, rather than punching the person standing below it.

**Comment by KasparoVy** [comment]
That feeling when you're in a life-or-death fight with a guy and you can't stop hugging them 'cuz you're too caught up in the moment to switch intent

**Comment by LittleBigKid2000** [comment]
Harmfulness of intents:
Disarm > Grab (With a table nearby) > Harm > Grab (With no table nearby) > Help

**Comment by FlattestGuitar** [comment]
The PR I made was a bit rushed in the end and didn't make a lot of sense. :+1: to this.

**Pull request merged**
