### PR TITLE
Nukes Jungle Module

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes the entirety of the Jungle module. It's 99% unused, Cael code, and has no general use....plus....

Tribesmen are invincible for whatever reason--dunno why; either case, that fixes that.

Things kept:
- Jungles animals
- bushes

### CODE REVIEW

**Comment by Plotron** [comment]
No big loss.

**Comment by Earthdivine** [comment]
....We had these?

**Comment by Spacemanspark** [comment]
@Earthdivine Yep.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

They use Goon's martian sprites....and Cael turned them into "Tribesmen" for whatever reason.

**Comment by Kerroman** [comment]
There was a blob round recently where I jumped into "Observe" mode and eventually spawned as a tribesman in Xenobio and ran off to try to fight the blob.  An emitter had been set up north of the blob core and I was south of the core trying to fight my way to it.  Though the blob didn't manage to kill me the emitter did (once the blob core was out of the way.)  Fox I believe you were there as I actually watched you dodge an emitter beam or two after I died.

**Comment by Taaketa** [comment]
They looked like floating zits anyway.

**Comment by Crazylemon64** [comment]
Ooh, yeah, lots of the "jungle" module code seems to be largely disfunctional - we should probably rip it out

**Comment by Fox-McCloud** [comment]
went ahead and did @Crazylemon64's suggestion and nuked the vast bulk of jungle code.

Moved the icon files to their more appropriate location.

**Pull request merged**
