### PR TITLE
You can now deep fry the nuke disk... If you dare.

### PR DESCRIPTION
**Pull request by gt33**
Basically, if you deep fry the nuke disk, a primed feral cat grenade is given instead of a "deep fried nuclear authentication disk". Better run.  
  
🆑 Reeeeimstupid
rcsadd: You can now deep fry nuclear authentication disks, although it is quite dangerous.
/🆑

### CODE REVIEW

**Comment by Spacemanspark** [comment]
This is gonna end very badly.
:-1:

**Comment by gt33** [comment]
Although it will be hilarious to watch.

**Comment by Crazylemon64** [comment]
why tho

**Comment by taukausanake** [comment]
DEEP FRY EVERYTHING!

**Comment by Crazylemon64** [comment]
deep fry this PR

**Comment by LightFire53** [comment]
That begs the question, what happens to the disk then? Is it deleted? Is it ejected? Why does it have cats built in?

While I enjoy a good joke, this "feature" isn't one that we need, or should desire to have in a MRP server.

**Comment by tigercat2000** [comment]
> someone says "MRP" again

😆

**Comment by gt33** [comment]
honestly the disk will do the thing it does when destroyed - recreate itself in a random location.

**Comment by Fruerlund** [comment]
muh RP, seriously my response is the same as with the loafer PR, no thanks

**Comment by gt33** [comment]
Awwww I wanted to trick the captain into frying the disk, but ok

**Pull request closed without merging**
