### PR TITLE
ERT Spawn Tweaks

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
add: ERT spawn area now shows ERT request reasons, and admins can enable the use of a teleporter or grav catapult without mechs.
/🆑

This PR optimizes ERT spawning in 3 ways:
1) Centcom messages and ERT requests are now printed out at comms consoles in ERT spawn areas. This both saves them (currently, they are not saved anywhere) and also allows ERTs to quickly get up to speed on their mission.
2) ERT spawn area now splits apart the catapults and mecha, so its possible for normal ERT to use the drivers without mecha access. There is a button in the specops office to allow this. When used, ERT are launched through portals to land on the bridge.
3) ERT spawn area now includes a teleporter room. Unlike most teleportation effects, this still works on Z2. It is locked by default, but can be enabled via a button in the specops office.

ert_spawn

### CODE REVIEW

**Comment by taukausanake** [comment]
For 2. so you mean that the mass drivers NEVER just shot you towards the station like badass space marine space diving, let alone inside a mech like a drop pod? That is a whole new level of disappoint. I never thought portals were so lazy until today

**Comment by Kyep** [comment]
@taukausanake What I mean is: previously admins had to unlock mechs for people to use the catapults / mass drivers, but now the drivers can be unlocked separately. The way the drivers work is that they catapult you to the left. When you hit the tile marked with the blue X you enter warp and appear on the Cyberiad bridge. It is the closest we can get to basically shooting you over with a cannon. Or basically pushing you into a warp portal. It is not possible to physically make you fly the whole distance, because the CC zlevel is physically disconnected from the others. Even if you went shooting off into space there, you'd eventually just hit the map edge and wouldn't move any further. The difference between warping using the teleporter and using the drivers/catapults is that the latter teleports one person at a time to a beacon (usually bridge beacon, but you can pick others), while the latter launches everyone on the pads to the bridge (always the bridge) simultaneously. This means that the teleporter is better for surgical insertions, say, beaming the whole ERT directly to scichem to combat a blob in scimaint, but the catapults / mass drivers are better for having your whole team arrive on the bridge in a co-ordinated fashion. Plus, the catapult s / mass drivers just look far cooler.

**Comment by taukausanake** [comment]
@Kyep I mean it could have shot you to the outer area of the station level. That would have been a little more believable at least. Directly to the station though, _lazy_

**Comment by Kyep** [comment]
If we started flinging people across z2, some wiseass is going to throw something, go off course, and not end up on the Cyberiad at all. Instead, they'll end up in one of the other restricted z2 areas, which players aren't meant to be able to get to. So, that won't work. Even if it did work, though, I don't think it would look as good as you think. From the launched person's perspective, instead of a momentary sensation of being flung through space and then being there, you'd instead be floating through space for a bit.... only to eventually encounter what seems like a huge edge/wall/void in space (the map edge) at which point you'd vanish and appear on the bridge. That doesn't seem better.

**Comment by Twinmold93** [comment]
The issue I see with two is that, realistically, they smash through the ceiling, and flinging people into these locations, while impressive, makes no logical sense. They'd splat on hitting the roof. Yes, I know how the code actually works, but from a realism side, it makes no sense.

Also, with the teleporter is a redundant system.

**Comment by Twinmold93** [comment]
Also, thanks for both 1 and 3. Those definitely should be added.

**Comment by taukausanake** [comment]
@Kyep I mean use the portals at the end of the mass drivers but have them send you to the outer area of the station rather than directly to the bridge. Have nothing to do with any space area or wall in z2.

Fuck I hate having to explain myself in extra detail

**Comment by Kyep** [comment]
@taukausanake Sending them to the edge of the station would have no benefit over using the shuttle/teleporter.

**Comment by pantherpusher** [comment]
I just really like the concept of space paratroopers

**Pull request merged**
