### PR TITLE
[TGUI] BotStatus.js for tidier TGUI code for bots

### PR DESCRIPTION
**Pull request by Oyu-De**
## What Does This PR Do
Adds a "BotStatus.js" in common page, cuts copy pasted code from bots making them shorter and easier to import to new bots.
Working on (VERY slowly as I suck) at converting rest of the bots to tgui, this makes it easier and tidier.

## Testing
- Load locally and test as AI

### CODE REVIEW

**Comment by Oyu-De** [comment]
Going to check on failed checks in few days.

**Comment by S34NW** [comment]
Your TGUI needs rebuilding after an update from upstream master

**Comment by Oyu-De** [comment]
oops, didnt see the merge conflict
Fixed now and ready for review

**Comment by Oyu-De** [comment]
oops, didnt see the merge conflict
Fixed now and ready for review @S34NW

**Review by S34NW — APPROVED** [review]

**Pull request merged**
