### PR TITLE
Give atmos techs engineering bags

### PR DESCRIPTION
**Pull request by MarcellusPye**
Makes atmos techs full citizens of engineering by giving them engineering bags. No more being mistaken for graytide with a suit!

### CODE REVIEW

**Comment by taukausanake** [comment]
They should get special atmos bags instead. ALL HAIL ATMOSIA

**Comment by MarcellusPye** [comment]
If you're proposing to sprite some...

**Comment by Keilden** [comment]
> They should get special atmos bags instead. ALL HAIL ATMOSIA

It should be charcoal black!

**Comment by MarcellusPye** [comment]
Engineering with cyan highlights would be keeping in pattern but if anyone wants to sprite some I'el support a pull request.

**Pull request merged**
