### PR TITLE
Fixes issue #2690

### PR DESCRIPTION
**Pull request by VampyrBytes**
Monkeys will now change first time. Also fixes a problem where any dna
changes in species were getting overwritten with human dna afterwards -
you can now change species dna to give abilities rather than having to
hardcode the verbs in

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Oh! Oh! You're back! Hello!
I had a similar fix in the works, but I never got around to publishing it -
while you're at it, you may want to make <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/game/dna/dna2.dm#L416>this line</a> use the .Copy() feature of lists, so the two are actually different lists. Primo!

**Comment by KasparoVy** [comment]
Wicked stuff, this will be much much appreciated. Thank you!

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
@VampyrBytes 

Thank you so much!

**Comment by VampyrBytes** [comment]
No Worries :) Would have fixed Hulk at the same time if I'd realised it was broken. Not sure how 'back' I am yet... A thread on the forums suggested that someone pm an active coder and they pm'd me lol, The email made me think of the game again, so I log on as geneticist, try to humanise my monkey, go ssd and dive into the code lol

Did enjoy tracking it down and fixing it though, so if nothing else I'll probably hunt some more down :)

**Comment by Plotron** [comment]
Finally I won't have to use clean monkey SEs.

**Comment by Crazylemon64** [comment]
Ah, when I implemented this fix on my own end, giving monkeys mutadone and a random mutation humanized them... This should be interesting

I also remember being able to gib monkeys by injecting them with a mutagen/mutadone mixture 3x at once, but maybe I changed something else, too...

**Pull request merged**
