### PR TITLE
Preventing blob attack spam

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR adds default blob attack cooldown when it attacks someone on the blob tile

## Why It's Good For The Game

Without this attacks per second were limited only by amount of clicks you can do in a second(or maybe server ticks), which allowed blobs, for example, kill DS unit in less than a second

Once someone is down, when you attack them, you can place blob tile under them. Imagine what happends next? Yes, instant death because you click as fast as you can. 

Imagine, what sorium blob can do? Yes, warcrimes.

## Testing

Compiled, spawned as blob, clicked

## Changelog
:cl:
fix: Blob attacks on the mob that is on blob tile now has cooldown
/:cl:

### CODE REVIEW

**Comment by meow20** [comment]
Acceptable change if it doesn't affect how blob attacks mechs, if it does, then mechs are completely unkillable (they are already hard to kill)

**Comment by meow20** [comment]
So i can still attack a mech 50 times a second cuz i clicked my mouse 50 times?

**Comment by HMBGERDO** [comment]
> So i can still attack a mech 50 times a second cuz i clicked my mouse 50 times?

wtf that is not how you currently hit mech as blob?
blob has default attack_cooldown which works every time you click on tile(object) which is not blob tile
unless you currently somehow place blob tile under the working mech, you have this cooldown when you attack it, meaning its not 50 clicks per second

**Review by Sirryan2002 — APPROVED** [review]
approved for code

**Comment by farie82** [comment]
Sorry for the long wait, the balance team has voted against this change with the following reasons:
- Their comparison was with DS (we dont balance around DS) and sorium usage (which makes sorium the problem). Id prefer being downed atop a blob tile to remain cooldownless when it comes to attacks
- Blob itself is already janky as hell and in a weak spot with only the blobbernauts when player controlled making it have any staying power. It really does not need nerfs to itself.

Due to this, I don't think the PR in its current form has a chance to be approved.

**Pull request closed without merging**
