### PR TITLE
New Taj Head & Hairstyles

### PR DESCRIPTION
**Pull request by K3Licia**
## What Does This PR Do
Replaces the head sprite of Tajaran and adds new hairstyles, both ported from Tau Ceti Station, along with making helmets and masks fit the new head better.

* [tajaran resprite 2 TauCetiStation/TauCetiClassic#9727](https://github.com/TauCetiStation/TauCetiClassic/pull/9727)
* [tajaran hair sprite tweaks TauCetiStation/TauCetiClassic#9986](https://github.com/TauCetiStation/TauCetiClassic/pull/9986)
All credits go to the original spriter!

(p.s: apologies for the random closing of the og PR wtf)
## Why It's Good For The Game
As we all know, Tajaran are infamously known for their side profile, which makes them look like they ate a bee. However, that is now no longer real with this PR. We can finally have decent-looking cat people! And with a few more customization options for bonus character creation fun.

## Images of changes
image
image
image

## Testing
1. i connect to my private server
2. they are, in fact, there

## Changelog
:cl:
imageadd: Replaced Tajaran head sprites, edited mask/helmets, and added new hairstyles to match. 
/:cl:

### CODE REVIEW

**Comment by Screampuff** [comment]
SPEEEEEEEEEDMEEEEEERRRRRGEEEEEEEEEE

**Review by SteelSlayer — CHANGES_REQUESTED** [review]
You've mistakenly removed some sprites: 

image
image
image

**Comment by K3Licia** [comment]
> You've mistakenly removed some sprites:
> 
> image image image

I'll re-add those. The plague doctor sprite was removed for being a duplicate which I believed was unnecessary. Speaking of, this made me realize there were more helmets (modsuits) I didn't touch, so I'll have to tinker with those later.

**Comment by McRamon** [comment]
Missed this PR
I am going to object to it, i don't like the design of a tabby cat with human body. Id live to see a resprite with taj head being close to big wild cats like panther/lion, but with some alienness added to it

**Comment by K3Licia** [comment]
merge conflict resolved, just waiting for the label to be taken out

**Review by SteelSlayer — APPROVED** [review]

**Review by S34NW — DISMISSED** [review]
This PR is not currently approved despite the label saying it is awaiting merge. Ramon is currently in objection and that will block the merge of this PR until he changes his position.

**Pull request merged**
