### PR TITLE
Port -tg-'s port of /vg/'s smoothwall.

### PR DESCRIPTION
**Pull request by tigercat2000**
tgstation/-tg-station#9535
This commit ports -tg-'s port of the /vg/ smoothwall system. An important
thing to note is that we have extra code on top of the -tg- port to make
it work at all, and therefore, it may not be as efficent.

Things changed from -tg-:
 - Smoothwall.dm, ~~removed "optimizations" of not smoothing nearby walls if the turf can't be smoothed with them. But, this didn't work, at all, because deleted/replaced turfs would just simply not update nearby walls.~~ Changed this, the optimizations were obviously put in place for efficency on New(), not on Destroy- just added an argument flag to skip the optimizations for updating on del.

 - ChangeTurf- this system integrates with /turf/simulated/wall/ChangeTurf, as Destroy() is not called at any point by it.

Other minor things:
 - False r-walls no longer have 40~ lines of override code just to keep their icon_state out of the standard format.
 - False r-walls sprite icon_states have been corrected to be in the right format, sister to the above

For players: This is mostly just behind the scenes work, at best, you might see a slight bit of performance improvement when breaking walls.

### CODE REVIEW

**Comment by Robertha89** [comment]
Does this mean if a wall is say removed, the connecting walls will finally update their sprites?

**Comment by tigercat2000** [comment]
@Robertha89 yes, although it is mostly efficency upgrades

**Comment by Fox-McCloud** [comment]
Try making some false R-walls and false regular walls...We used to have a super early implementation of this code, but it caused so many problems and was so finicky that Mark ended up ripping it all out and putting TG's code for smoothwalls back in.

**Comment by tigercat2000** [comment]
@Fox-McCloud Tested every possible scenario I could think of involving walls, rwalls, false walls, false rwalls, everything smoothed just fine.

**Comment by Fox-McCloud** [comment]
great.

**Pull request merged**
