### PR TITLE
Makes Cerestation only randomly selectable with 80 players online

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Increases the threshold of online players required for Cerestation.

## Why It's Good For The Game
Due to the massive drop in players (which in turn causes Cerestation to be borderline unplayable), even with 60 online players, you'll often see that only 30 signed up for the round. This PR to alleviate the problem a bit.

## Testing
It compiled, if the previous PR worked, this should work just as well

## Changelog
:cl:
tweak: Increased the required players for Cerestation to be chosen on random map days
/:cl:

### CODE REVIEW

**Comment by warriorstar-orion** [comment]
What is it specifically about Cere that makes it "unplayable" with fewer players? Is it that the distances between departments are so great that people have less time to do their jobs because they're spending so much time traversing the station? Is it that the individual rooms in each department require more hands to operate? Is it that the lower population makes it more likely that security's job will be harder because they can't adequately patrol the map?

I'd rather fix specific problems with the map than reduce the chance of it being selected even more.

**Comment by Probablyjay19** [comment]
> What is it specifically about Cere that makes it "unplayable" with fewer players? Is it that the distances between departments are so great that people have less time to do their jobs because they're spending so much time traversing the station? Is it that the individual rooms in each department require more hands to operate? Is it that the lower population makes it more likely that security's job will be harder because they can't adequately patrol the map?
> 
> 
> 
> I'd rather fix specific problems with the map than reduce the chance of it being selected even more.

The issue I've noticed is that the station is quite literally just too large to traverse and the telepads are way too slow to keep up with the traversal needed for a regular working round of the game. Security response time is at the forefronts of these issues, as officers can't reach crime scenes fast enough to catch antagonists before they're long gone, which is dramatically heightened when there's only 4 officers on station. This is the leading issue to the playerbase keying the term "cerepop" and "fargsec" etc

**Comment by warriorstar-orion** [comment]
> > What is it specifically about Cere that makes it "unplayable" with fewer players? Is it that the distances between departments are so great that people have less time to do their jobs because they're spending so much time traversing the station? Is it that the individual rooms in each department require more hands to operate? Is it that the lower population makes it more likely that security's job will be harder because they can't adequately patrol the map?
> > I'd rather fix specific problems with the map than reduce the chance of it being selected even more.
> 
> The issue I've noticed is that the station is quite literally just too large to traverse and the telepads are way too slow to keep up with the traversal needed for a regular working round of the game. Security response time is at the forefronts of these issues, as officers can't reach crime scenes fast enough to catch antagonists before they're long gone, which is dramatically heightened when there's only 4 officers on station. This is the leading issue to the playerbase keying the term "cerepop" and "fargsec" etc

Traversal time is definitely a problem, which I'm attempting to improve with transit tubes. The idea of having the quantum pads start upgraded has also been floated. But it's still not clear to me how server population is involved.

Regarding security forces, if the idea is that the higher population means there's more security distributed around the station, that still doesn't make sense, because from lowpop (less than 80) to highpop, the number of security slots is only increased by one, whereas the number of antags will continue to scale, which would only make the problem worse. You also can't guarantee that a higher server population would result in more sec officers, since people's desired roles are not concentrated in one department.

**Comment by DGamerL** [comment]
With Cere being improved, I hope that people will enjoy Farragus more, as it is a good map already

**Pull request closed without merging**
