### PR TITLE
Fixes #15718 - All bottles now smash and spill their contents on impact.

### LINKED ISSUE #15718: Reusable Molotov Cockatail
**Issue Description**:
After throwing a molotov cockatil, it would light that square on fire but drop the intact molotov cockatil-->

**What did you expect to happen**: 
I expected the molotov to create a broken bottle, as is on other servers-->

**What happened instead**:
The square briefly was flames and the monkey hit by it was covered in burning fuel, with the intact bottle nearby-->

**Why is this bad/What are the consequences**:
Molotovs should be one use items, limiting their effectiveness. That same shift, I tossed the molotov at terrors and kept on picking up the bottles and filling them back up. It seems it didn't do much against the terrors (they didn't burn, just made that square burn for a short time), but I never tried molotovs against terrors before.-->

**Steps to reproduce the problem**:
I used the griffeater gin bottle, if that changes anything. I filled the molotovs with vodka from the bar's booze dispenser. I also refilled them with a bucket full of vodka at some points.-->

**When did the problem start happening**:
I never really used molotovs on Paradise before. This was my first time I think. Will test it more.-->

**Extra information**:
I never used Github before. If this makes no sense or something like that, tell me and I'll try to fix it.-->

### PR DESCRIPTION
**Pull request by PidgeyThePirate**
## What Does This PR Do
Fixes #15718

All bottles smash and spill their contents over what they hit when thrown, including molotov cocktails. If this is a problem the code can be modified to only smash molotovs.

## Why It's Good For The Game
Fixes some unexpected behaviors. I expect that several bottles will be accidentally smashed, but tossing around fragile containers never made much sense anyway.

## Changelog
:cl:
add: All thrown bottles and cartons now smash, spilling their contents over whatever they hit.
tweak: Molotovs now smash properly on hit and set the target on fire if they're burning.
/:cl:

### CODE REVIEW

**Comment by Necaladun** [comment]
Unsure on this - if I throw a bottle full of a deathmix at someone, whats going to happen? I can't remember the exact code for splash vs inject/consume etc, but I worry this could be pretty nasty with the right superheated mix.

**Comment by Wojz** [comment]
> Unsure on this - if I throw a bottle full of a deathmix at someone, whats going to happen? I can't remember the exact code for splash vs inject/consume etc, but I worry this could be pretty nasty with the right superheated mix.

You can already do this by attaching a rag to it and making it a "molotov" :P

**Comment by PidgeyThePirate** [comment]
What Wojz said. If you're taking the time to make a superheated death mix then finding and attaching a rag to the bottle is absolutely trivial. If you have a problem with this then you'd be better off removing molotovs entirely.

**Review by AffectedArc07 — APPROVED** [review]
Fuck it

**Pull request merged**
