### PR TITLE
Changes Gamma and Epsilon security level sounds

### PR DESCRIPTION
**Pull request by Ty-Omaha**
**What does this PR do:**
Changes the sound played when these two security levels are activated. Adding a bit more umpf and tension.

Gamma:
https://github.com/ParadiseSS13/Paradise/blob/a62233000443a5f57acfae6847748aabad5cdbdb/sound/effects/new_siren.ogg

Epsilon:
https://raw.githubusercontent.com/ParadiseSS13/Paradise/73091bf78c29d6699348b17a5412cf3b2a2a3b17/sound/effects/purge_siren.ogg

(Use firefox if the sounds wont play for you)

:cl:
tweak: Modified alert sounds for Code Gamma and Code Epsilon.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
Purge_siren.ogg is fine and appropriate for epsilon, since it pretty much is the purge. It is a deep stabbing sound, clear and distinct from any other siren type.

Siren-spooky.ogg is not really appropriate for gamma. It is used for terror spiders because it is the air raid siren for resident evil, and in the design of that game, specifically means "you are crossing from the mundane world to the nightmare world, where monsters will try to kill you". Functionally it is a warning, but its also atmospheric, its main atmospheric goal being to provide an atmosphere of horror. Everything about it, even its name (spooky-siren) was chosen with this in mind.

Gamma isn't a horror event, and so an ogg that inspires horror isn't really appropriate. The message isn't "be afraid" or even "monsters are coming". The correct message for gamma is "battlestations! The station is under attack! All crew take up arms and defend the station and your lives!".
An alarm like that has a totally different tone. It is sharp, clear, aggressive, hits hard immediately, seems aggressive and inspiring. It is commanding and purposeful. It sounds like a battle cry, or a general rallying their troops.
Here are some examples of the sort of alarm I mean:
https://www.youtube.com/watch?v=1GDeeonselA (the explicit version, used on military vessels under attack)
https://www.youtube.com/watch?v=_al9owcieHQ (the implicit version, with no words, but a sharp, stabbing siren that basically screams "wake up you nerds and fight for your lives")

Lots of thought goes into good sound design - you probably shouldn't just pick any sound because it sounds cool. Really think about exactly what message you want the siren to send, and look for the exact sound file that communicates exactly that message. It took me quite a long time to find the perfect sound effect for the terror spiders alarm sound. You shouldn't expect it to be easy to find the perfect alarm sound for gamma/epsilon. Getting it perfect will require some research.

**Comment by Ty-Omaha** [comment]
As someone who has never played resident evil it has no resemblance to be "spooky" and is just a siren to me and most likely many others.  I didn't want to use the nuclear emergency siren because that siren is iconic to that gamemode.

I will update it with a new siren.

**Comment by Ty-Omaha** [comment]
Updated siren

**Comment by Kyep** [comment]
Yeah, that sounds better.

**Comment by Ty-Omaha** [comment]
dont merge I found a better one laying somewhere on my computer lol

**Pull request merged**
