### PR TITLE
fixes the arcade power

### PR DESCRIPTION
**Pull request by Aurorablade**
It was missing a cable under the door

:cl: Fethas
bugfix:The engineering power weasels have found the source of the arcade power issues and fixed it.
/:cl:

### CODE REVIEW

**Comment by Jovaniph** [comment]
Did you get both of the sources? There is one at the APC and one below the airlock. The wire below the APC is facing the wrong direction.

**Comment by MarcellusPye** [comment]
@Jovaniph @Aurorablade Looking at the code, no.

**Comment by SamHPurp** [comment]
@Fethas while you're fixing the Arcade, could you also fix the `area` definition on the door into maintenance. It should be the area of the maintenance tunnel, to conform to the rest of the standard.

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
