### PR TITLE
Adds the magic mirror to the wizard den

### PR DESCRIPTION
**Pull request by datlo**
This PR replaces the mirror in the wizard den by a magic mirror, that lets you change your species to any playable ones you wish, customize your name, and your appearance.

Species are restricted to playable and karma unlocked only.

A spare plasmaman suit, plasma tank, and vox internals were added to the wiz robes racks for any wizard that wishes to change to them.

🆑
Add: Added the magic mirror to the wizard den, letting wizards swap to other species and change their appearance.
Add: Added spare plasmaman suit, plasma tank, and vox internals to wizard robes racks for any wizard that wishes to change to these species.
Fix: Made the snack machine in wizard den free to use. (wizards don't take silly credits as currency)
/🆑

### CODE REVIEW

**Comment by TDSSS** [comment]
Do you need to have a race unlocked with karma to select it?

**Comment by datlo** [comment]
Yes.

**Comment by datlo** [comment]
Yes, the mirror can only be used when your character is next to it.

**Comment by taukausanake** [comment]
If you start as a human and want to change to Plasmaman or Vox will you auto equip your needed gear or do you have to change into it before you transform?

**Comment by datlo** [comment]
You will not be autoequipped. For vox you can prequip the internals, for plasmaman you'll just have to quickly put on your suit after morphing which will extinguish you. There's mugwort tea in the wizard den that'll heal any damage you take from that.

**Pull request closed without merging**
