### PR TITLE
Adds Taj Striped Tail Marking, Allows Tiny+Short Tails for Taj, Renames Vulp Tails

### PR DESCRIPTION
**Pull request by KasparoVy**
**What does this PR do:**
* Resolves an issue where the current Wingler tail forces you to have bright stripes the same hue as your body by adding a marking derived from it you can set to whatever colour you like.
* Adds the species-ambiguous tiny & short tails for use by the Tajara (could've been docked, injured, etc.)
* Renames Vulpkanin tails to be more in line with other sprite accessory names, allowing you to make selections with the keyboard a bit more directly
* Cleans up the body accessories file a bit

**What does it look like:**
[_**Striped tail marking**_](https://anonfile.com/s7L0pe49nc/para_ss13_vahrr_hharar_with_striped_tail_marking_mp4)
[_**Small/Tiny tails on tajara**_](https://anonfile.com/rcL8pe4en2/para_ss13_junkra_vahmir_with_tiny_and_short_tails_mp4)

**Changelog:**
:cl:
add: Tajaran characters can now have the tiny & short tails (plus marking).
add: Adds a striped tail marking for Tajara derived from the sriped/wingler body accessory to allow more flexible colouration.
tweak: Renames Vulpkanin alt. tails for brevity and easier keyboard navigation.
/:cl:

**Required SQL Query:**
https://paste.merkoba.com/1566954446-funeta-1
```
#Update marking & body accessory names.
UPDATE characters SET
    body_accessory = REPLACE(body_accessory, 'Vulpkanin Alt 1 (Bushy)',          'Bushy Tail'),
    body_accessory = REPLACE(body_accessory, 'Vulpkanin Alt 2 (Straight)',       'Straight Tail'),
    body_accessory = REPLACE(body_accessory, 'Vulpkanin Alt 3 (Tiny)',           'Tiny Tail'),
    body_accessory = REPLACE(body_accessory, 'Vulpkanin Alt 4 (Short)',          'Short Tail'),
    body_accessory = REPLACE(body_accessory, 'Vulpkanin Alt 5 (Straight Bushy)', 'Straight Bushy Tail'),
    marking_styles = REPLACE(marking_styles, 'Vulpkanin+Short+Tail+Tip',         'Short+Tail+Tip');
```

_Tested successfully on local environment._
para ss13 sql tails rename and marking add query

### CODE REVIEW

**Comment by KasparoVy** [comment]
The reason why I removed the body accessory version was because you can replicate the effect on your character exactly with the marking by setting the colour, which made the body accessory redundant - but that did remind me I broke Wingler's comb since I didn't update it to set the marking instead.

I agree with you and think the changing of fluff items without player consent might be against policy so I'll re-add the body accessory

**Comment by KasparoVy** [comment]
Away until 2019-02-03, unable to respond

**Comment by variableundefined** [comment]
Uhh. Time travelling.

Ping me when this PR is ready to be reviewed.

**Comment by KasparoVy** [comment]
Lmao didn't realize I made a typo hahaha. Anyway, I made it back through the continuum. This is ready for review, thanks

**Comment by Fox-McCloud** [comment]
LGTM.

**Pull request merged**
