### PR TITLE
[Sprite][Balance][Slaughter demon]Bleeding is now illigal

### PR DESCRIPTION
**Pull request by Aurorablade**
Slughter demon icon changes and balance/nerf?

New icon based on: https://github.com/tgstation/-tg-station/pull/11457

Changed Slow down speed after inital pop up out of blood to 2

CONSIDERING: Make a prop so a victim can break free (low chance) while in crit BUT at either the cose of some brute damage, or they loose a limb. I would like opninon on prob() chance. The limb loss and Brute damage are iffy as the mob already needs to be in crit to be pulled into blood.

Any other balance suggestions?

### CODE REVIEW

**Comment by TheDZD** [comment]
Not sure if we suffer from the same bug as /tg/ where wizard-summoned slaughter demons don't get bloodcrawl, but tgstation/-tg-station#11545 is probably worth looking at if we do.

**Comment by Aurorablade** [comment]
yeah i saw that, the only way to test that is a wizard..some someone adminbuss spawninging the vial for it....

**Comment by Fox-McCloud** [comment]
Interesting; they speak the cult language.

**Comment by Aurorablade** [comment]
@Fox-McCloud well i figured i would do something like with some simple animlas like Ian where they can speak something (BARK, YAP), but are not easily understood. Cult seemed to fit. Can try to think of something else..but seemed to fit. also its either VG or Bay that DOES actually have a cultist language set up as an actual language. I think

Will probaly do the bloodcrawl as spell thing later.

**Comment by Fox-McCloud** [comment]
This ready to be merged, yet?

**Comment by Aurorablade** [comment]
@Fox-McCloud Yeah unless you think i should add that blowcrawl as a spell thing, though i am not sure if they have that run time as on TG

**Comment by Fox-McCloud** [comment]
Out of curiosity, what was the prompting to change that number (which I believe makes them slower?)

**Comment by Aurorablade** [comment]
I can revert it back but its pretty much first pop out of blood = fast, after a bit = slow down. And when this has been out during adminbus, people WERE mentioning how op it was, as it should be BUT my reasoning here is to give people A SLIGHT fighting chance...SLIGHT...i was also debating giving a SMALL chance for the demon to loose grip while pulling someone into blood..maybe at the cost of a random arm/leg...wasn't sure what number would have been good there. So just SMALL edge in running away screaming..until you bleed somewhere else...

**Comment by Fox-McCloud** [comment]
Let's see how this goes, currently.

**Pull request merged**
