### PR TITLE
Robust Harvest Reaction

### PR DESCRIPTION
**Pull request by Deanthelis**
Adds Robust Harvest to the reaction list, so that Chemistry can replace the rather limited supply the vending machines start off with.

Ingredients are Diethylamine and Radium, 1 part each, to produce 2 parts Robust Harvest - The idea is that the radium modifies the excellent fertilizer to become a yield modifier.

This is mostly a quality of life thing, for Botany and Xenobotany, to help produce larger amounts of a given plant than normal, so long as Chemistry (or the Xenobotanist, really) is competent.

I plan to add it to the wiki soon as well.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
If there wasn't a way to make this, I'd give a thumbs up.

But...botany can make as much as they want with the biogenerator.

**Comment by Deanthelis** [comment]
Well, this is awkward.

**Comment by Deanthelis** [comment]
At least I did the whole github thing right this time! Learning!

**Comment by ZomgPonies** [comment]
Sooooooo close this since there's already a way?

**Pull request closed without merging**
