### PR TITLE
Make advanced tasers fire only disabler beams.

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit makes the "advanced taser" permanently in "disable" mode. Requested by @Adrkiller59 & @SpacemanSpark, please direct all questions or arguments towards them. I'm just providing the code, I have no interest in taking part in this, so i'm out.

[8:12:34 AM] Adrkiller59: "Here it is as promised, now that the PR is open, the discussions will actually have consequences if something is decided. And please keep it civil."

### CODE REVIEW

**Comment by Krausus** [comment]
I have no idea where the discussion about this is taking place, but uh... we already have a gun that only fires disabler beams. It's called a disabler.

**Comment by FalseIncarnate** [comment]
:-1: from me on this.

If the issue is that people want to use disable over taser, I'd suggest either switching the default mode of the advanced taser to "disable" so that it's a purposeful choice to use the instant-stun, or to swapping the availability of the two guns.

Making the disabler the standard issue and the advanced taser one that they need to intentionally seek out would be a much better option than simply making 2 versions of the disabler as would be the result of this PR.

**Comment by Robertha89** [comment]
Ditto, from what I can see, this appears to be a way to deal with the instant stun, but you still have tasers, so it seems odd.

Instant stun is, and will always be a problem, changing it one way, will tip the balance a skew, the only modification i would like to see, is a delay of a second, second and a half of the stunner hitting you, before the effects are felt.

This seems to remove an issue that is not an issue at all, the Disabler is good for range, the stun is good for close, ofc the stun costs more to use, but it is instant, but it also does no stamina damage, which means even after regaining enough to stand up, you won't be able to run that far. Plus several other issues that ya should know.

:-1: 
This is a nerf for the sake of a nerf, and that is a bad way of balancing it, we tried pain for a while, and that did not work. Honestly people use the disabler over the taser, but removing it would be redundant. Stun is impossible to balance, look at the flash, it's basically useless now, and all it does is help rev convert more, cause it acts like a toy flash. sure, there is a small stun, but without the laying down, you have no visual indicators of it ending.

**Comment by Fox-McCloud** [comment]
:-1: 

Most people know my thoughts on this---largely, with the direction has headed and the huge amount of ports we have from TG, this is already *largely* balanced for--our tasers are even weaker than TG due to the nature of our implementation of Goonchem, which has a plethora more of anti-stun chems than TG does (that are far more accessible than on TG, as well).

> Instant stun is, and will always be a problem, changing it one way, will tip the balance a skew, the only 
> modification i would like to see, is a delay of a second, second and a half of the stunner hitting you, 
> before the effects are felt.

**Comment by fj45** [comment]
Insta-stun is awful and the weird hybrid tasing system is also crap, but this isn't how it should be done.

Removing insta-stun from sec would also require a large re-balance of other insta-stuns, chem and many other things. This is a nice step......but it would just mess with balance instead of really fixing the issue.

**Comment by ZomgPonies** [comment]
:-1: What everyone said.

**Comment by M3hillus** [comment]
:-1: The instant stun from the hybrid taser, In my opinion, is very balanced.

Short range, what seems to be (Relatively, or might just be me) a slower projectile, Cannot shoot through windows (and I think grilles), very low rate of fire, very high energy cost, and, importantly, its a VERY short stun.

If you are security, and simply only insta-stun someone, you have to either have cuffs already inhand, or you risk not cuffing someone before you get up. 
Where if you get those 3 or so disablers on them, which cost less, shoot faster, shoot through windows, and effectively stun longer and slow your target, you have all the time in the world to do as you please. 

That being said, both shot types have a time and place. Yes, instant stuns are kinda shitty, when in the wrong hands, but, the drawbacks to using the taser instead of the disabler make it worth the time to decide your engagement. I'd rather security have more ready access to them, than every other Urist McRobust with a little bit of game know how and social connections.
 
Final note, E-guns should still retain disablers only, because THAT was the worst thing ever.

**Comment by adrkiller59** [comment]
This PR is in relation to this thread: http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=4685&start=20#p31090

All technical matters regarding the actual balance are up to discussion, and will be changed as needed as the ideas develop. The PR was opened on my request as a significant part of the community seemed interested in discussing a re-balance of the inta-stun, with focus on tasers. This PR is meant to bring attention to this potentially game-changing matter.
I'm aware that the contents of this specific PR is not the way to balance it, and I state again that the technical part is up to change. 
If the discussions don't give any conclusive solutions then the PR would be just closed, so if the community wants to see any changes, this is your new chance.

**Comment by Spacemanspark** [comment]
I'm a little confused as to why we're turning the hybrid taser into a complete disabler when we already have a full disabler. We could just replace sec's starting gear with disablers and temporarily continue to keep the hybrid tasers in the armoury (Only three of them.).
But I am glad that we're moving a step in the right direction, at the very least.

**Comment by adrkiller59** [comment]
@Spacemanspark

Again, the contents of this PR are up to change, and nothing will be merged until the majority of people is happy with the results. Your suggestion would be a perfectly valid alternative which I personally support, so the PR would be updated to implement that.
Hybrid tasers are very powerful and too accessible. If sec got disablers as standard issue gear, and the hybrid tasers were kept in the armory, it would give them a better feeling to reflect how powerful they are. That, or make it an advanced RnD protolathe craft, like most guns.
Then again, RnD is stronk enough.

**Comment by melandor0** [comment]
As someone mentioned, give sec disablers instead of tasers since that's a thing that already exists.

Then remove advanced tasers and normal tasers, we don't need bloated code.

But yes, anything that reduces one-hit-bullshit is good.

**Comment by Surrealistik** [comment]
Stun batons for more effective, but melee range stun, tazers for longer range but less effective stun; maybe give them more shots as compensation.

The bottomline is that one hit wonders/OHKOs are bad, aren't fun to fight against/deal with, and we should not be balancing the server around them; I am all for a longer term, broader rebalancing away from haha-I-hit-u-now-u-ded-and-I-winrar bullshit mechanics.

Anti-stun chems are not especially accessible, and if people feel they're too accessible regardless, that accessibility should be reduced.

**Comment by Robertha89** [comment]
Nicotine is an anti-stun chem.

**Comment by Surrealistik** [comment]
Pretty sure its anti-stun effect is weak as fuck though, and if not, it should be, or better yet, it shouldn't have an anti-stun effect.

**Comment by Robertha89** [comment]
`if(prob(5))
		M << "<span class='notice'>[smoke_message]</span>"
	if(prob(50))
		M.AdjustParalysis(-1)
		M.AdjustStunned(-1)
		M.AdjustWeakened(-1)
		M.adjustStaminaLoss(-1*REM)
	..()
	return`
vs
`	if(prob(5))
		M << "<span class='notice'>[high_message]</span>"
	M.AdjustParalysis(-2)
	M.AdjustStunned(-2)
	M.AdjustWeakened(-2)
	M.adjustStaminaLoss(-2)
	M.status_flags |= GOTTAGOREALLYFAST
	M.Jitter(3)
	M.adjustBrainLoss(0.5)
	if(prob(5))
		M.emote(pick("twitch", "shiver"))
	..()
	return`

**Comment by Surrealistik** [comment]
Yeah, while I wouldn't call its effect strong exactly, that's a bit much for something so readily available. See above; nerf stick.

**Comment by Earthdivine** [comment]
Alright then, if we're doing this:

You need to remove Stun Revolvers as well. If not then this is one big hypocritical argument. Either that or make them NOT insanely cheap to research and make.

**Comment by Spacemanspark** [comment]
Oh shit, almost forgot about stun revolvers.

**Comment by Surrealistik** [comment]
Don't forget to nerf nicotine as part of this; ridiculously abundant and accessible for what it does.

**Comment by TheDZD** [comment]
:-1: to the current implementation of instant stun taser removal.

Most antagonists have access to instant stuns, removing sec's access to the same would requisite taking away most, if not all instant stuns from antagonists. Beyond that, most antagonists have easy ways to mitigate or entirely avoid instant stun tasers, as does anybody with chemistry access or even anybody with cigarettes. 

I'm not particularly fond of instant stuns as a game mechanic, but they have existed in SS13 for quite a while, and while I have not seen stamina damage stand on its own (halloss can go die in a fire), it does seem to be at least somewhat promising. The issue however is that if a few people have easy access to instant stuns, it's incredibly cheap, boring, and the go-to tactic (old changeling stings for example), while if everyone has them, combat becomes about who can avoid or mitigate stuns better/who stuns first. 

Frankly, if anything is going to be done about instant stuns, they either need to be entirely reworked, or flat out removed; taking them away from one group of people while others still have access to it will not alleviate the underlying issue with instant stuns as a game mechanic.

**Comment by Spacemanspark** [comment]
Perhaps have Mini Ebows use stamina damage and give them their old ability of being able to fire multiple shots, as well as give toxins damage.
Normal Ebows could possibly retain their instastun ability, as you don't see them very often.
Syndicate shotguns could run on stamina.
Come on, help me out here, what other antag instastuns do we have (I know it's a long list.).

**Comment by Surrealistik** [comment]
Again, I'm fan of getting rid of virtually all forms of OHKOs, sec and antag alike; there may be a couple that are justified, but as a rule these things should not exist.

**Comment by Iamgoofball** [comment]
@Surrealistik What? No, keep nicotine nerfs out of this. This is a security PR, not a chemist PR.

**Comment by Surrealistik** [comment]
Nicotine nerfs aren't chemist specific. Further, it's a nerf PR that's supposed to deal with instastun bullshit; part of dealing with instastun bullshit is dealing with the things that justify instastun bullshit like nicotine being way too good at stun amelioration relative to how common and accessible it is.

**Comment by Iamgoofball** [comment]
@Surrealistik have you even used nicotine in game with the purpose of antistun

**Comment by Surrealistik** [comment]
The code speaks for itself.

**Comment by Iamgoofball** [comment]
@Surrealistik there's a whole world of difference between what the code says on paper and how it works out in game, so no, the code does not speak for itself

**Comment by Surrealistik** [comment]
Being able to significantly blunt stuns by sucking down a chem that's readily available to everyone with pretty much no material downside also speaks for itself.

**Comment by Iamgoofball** [comment]
@Surrealistik You do realize that you're also running a 50% chance on it, right? And that if I hit you with a stun baton or some shit, I can just keep hitting you and setting the stun time back to the original?

There's way more factors to consider. Go actually play the game and test it out yourself before you call to nerf.

**Comment by Surrealistik** [comment]
Yes, you can waste a bunch of additional charges thumping someone who's down because nicotine is more powerful than it has any right to be; the fact is you shouldn't have to, not to mention that the nicotine is also likely to require getting additional hits in during a take down due to stun recovery assuming we remove instastuns for sec and go with a graduated, non-binary system. Again, way too powerful for its ease of accessibility and complete lack of a downside.

**Comment by Iamgoofball** [comment]
@Surrealistik 
>Go actually play the game and test it out yourself before you call to nerf.

**Comment by Surrealistik** [comment]
You seem to be confused; we're talking about nicotine nerfs _after_ instastun is removed from sec; for obvious reasons I can't test this out myself. That said I also don't have to jump off a hundred foot cliff to know it's a bad idea.

**Comment by Iamgoofball** [comment]
@Surrealistik Please explain your "obvious reasons" as to why you can't test it yourself, as they aren't exactly obvious.

Also, there's a huge difference between jumping off a 100 foot cliff and this.

**Comment by Surrealistik** [comment]
Because it pertains to a system we don't actually have in place; i.e. a wholesale removal of sec instastuns. Second, I would need to set up appropriate combat situations with others once we do have that in place. In short, it's a lot of hassle in order to figure out something that's painfully obvious: if you have graduated stuns, and you have a downside free chem available to everyone that reverts stun progression, it's going to result in more hits required to effect a takedown which means there's a powerful incentive for every antag to light up; i.e. it's a centralizing feature with no counterbalance. Rarity doesn't balance it, nor does averse effects, it's a pure gimmie to antags that has no justification for existing after Sec's ability to deal with them has already been substantially weakened.

**Comment by Iamgoofball** [comment]
1. I thought you wanted the nerfs to be done now before this new stun system is added apparently.
2. No. Don't ever set up combat situations. They always give weird results that don't turn out to be too accurate. Just let your combat situations occur naturally.
3. If a nerf absolutely needs done we can make it do some toxin and burn damage from sending scalding hot gases down your throat carrying things that are Bad 4 You(tm)

i'll get around to making nicotine cause carbon monoxide and tar for extra reals soon

**Comment by Surrealistik** [comment]
I don't mind Nicotine retaining some of its potency post stun-nerf _if_ it has a nerf that makes sense like yes, toxin damage, metabolizing the nicotine/cigarette into poisons and lung damage/reduced movespeed.

That said it probably should not reduce paralysis durations at all; stunned is iffy, weakened is fine in the short term.

**Comment by Iamgoofball** [comment]
@Surrealistik The reason it reduces all 3 is because paralysis, stunned, and weakened are all used interchangeably in random places for some weird ass reason and they all seem to do the exact same thing except that Paralysis also makes you sleep during it. So, to prevent weird instances where it stops some stuns and doesn't stop others,. it reduces all 3.

**Comment by Robertha89** [comment]
Here is what will happen, when no good suitable stun alternatives exist, harmbaton erryday.
There is also the fact that there is literally no reason to remove it other then, waa antag is hard, is the reason. Instastun is better then the alternative, and you should not get caught as an all, there is also the fact you can just smoke, then run away.
But since you seem so interested in the code
`/obj/item/projectile/beam/stun
	name = "stun beam"
	icon_state = "stun"
	nodamage = 1
	damage = 0
	agony = 40
	damage_type = HALLOSS`
stun beams vs
`/obj/item/projectile/beam/disabler
	name = "disabler beam"
	icon_state = "omnilaser"
	damage = 36
	damage_type = STAMINA
	flag = "energy"
	hitsound = 'sound/weapons/tap.ogg'`
there is also the fact that you can build a simple glass wall and bam, they have to get around it to shoot you, or switch to disabler, and as you see, they are about equally as good.

But wait, there is more! there is a delay on shooting the stun beam, a 15 tick delay, now lets say you switch the stunbeam to do stamina instead of agony, and it accordingly to it's cost of 2k vs the disablers .5k, and it does 144 stamina damage per hit.

But there is one thing that is important to remember, that reading the code can cause you to go blind to the actual differences.

also @Iamgoofball, i used meth to compare the effects of nicotine and meth. which codewise does not seem to be that big of a difference untill you know the difference between smoking, and processing internal chemicals.

**Comment by Necaladun** [comment]
I think it's best to keep this on topic - nicotine is another issue.

**Comment by Necaladun** [comment]
It seems people were highly against the original proposed change, are the feelings the same now with them being changed to just tasers? What ohko's does this leave for sec? Flashbangs and shotguns?

**Comment by Robertha89** [comment]
stun baton, pepperspray, flash and beepsky.

**Comment by Necaladun** [comment]
Pepper spray and baton have no complaints. Beepsky has always been op, and flash doesn't stun anymore

**Comment by adrkiller59** [comment]
Baton used to be stamina damage, with two hits needed to stun, the first one slowing you to a crawl, not sure how it is now, but that was pretty popular.
IMO pepper spray should just blind you, slow you and deal pain, it would be a crippling tool for self-defense or preventing the criminal from running too fast.
I'd be fine with flashes being like they used to be long ago, insta stun on click. They have a very obvious sprite in hand and can be completely blocked with gear that is easily avaiable to most jobs and antags. In reality it was mostly used to catch greytiders without using baton charge.
Beepsky is much slower on other servers i saw, so if you arent hungry you can outrun it, making him much less of an issue unless you run into or past it. 

Also @Surrealistik , anti-stun drugs should be discussed somewhere else, as this is a PR about security insta-stuns. Antag insta-stuns and chems would be discussed on other thread/PR, one thing at a time please.

**Comment by SamCroswell** [comment]
@Robertha89 
The flash is not a ohko. All it does is cause confusion. Pepper spray is also not a ohko. You can get hit by the spray and so long as you move instead of standing in it you'll only get blurred vision.

**Comment by fj45** [comment]
Rob, you say all that but miss the vital thing:

Everything you say that will cause balance issues can be adjusted. I completely agree that only doing bits here and there would unbalance the game, that is why anything to do with stuns needs to be looked at and rebalanced. All those numbers can be changed.

You claim that insta-stun is bad simply because it makes playing antags harder...well not at all. For one thing, antags have plenty of their own insta-stuns, and with a rebalance i'd assume many of those would get removed.

Insta-stun encourages shitcurity. It makes fights very fast. Ping factors into fights more then they should. Ect ect.

(Note, I do want playing as an antag to be difficult)

**Comment by Robertha89** [comment]
About 8 or 9 months ago, the instant stuns where replaced with affecting pain, and the period after had more shitcurity then ever, not of the arrest for no reason, but caus, Oh hey, not working, beat him to death reason. It has been tried, and it has been reverted, I am no fan of instant stun myself, but they are an important aspect of the game.

But again, that is not the big issue with instant stuns, the real issue is it disarms from range.

But you can always check what mode security uses the most, and more often then not they use disabler, due to the safety it gives at range, easier to hit with, shoots faster, and most importantly, it lasts longer, get in 4 hits, and every shot after that will be a instant stun.

Also, removing the antags various instastun methods would destroy em, you got cultists and their talisman, if it ain't instant, ya can wip out a stun baton and stun them, or even shout for help. They are needed, because it's them vs the station, and it's their only good non-lethal option, and if they get caught, they are either dead or deconverted.

Insta stun is only and issue in regards to one thing, and that is damage, damage and instastun is bad.

**Comment by Spacemanspark** [comment]
I think you're forgetting that there was a decent period of time where we didn't have that issue during the summer, Rob.
And halloss /was/ effective, just not a OHKO.

**Comment by Surrealistik** [comment]
As I've said repeatedly, this isn't a change that we can really do piecemeal; instastun should go but everything that validates it also needs to be changed, from sec nonlethals, to anti-stun chems to antag instastuns. Yes some instastuns may be warranted but these are going to be the exception, not the rule.

If we do decide to proceed piecemeal however, then all other required changes should be phased in as quickly as possible.

**Comment by Fox-McCloud** [comment]
Please limit discussion to the topic at hand: tasers.

While stuff like nicotine is relevant to discuss within the context of the strength of current tasers,  it's NOT relevant to discuss as being up for balance, at the moment---nor is the concept of bringing back HalLoss, hitscan beams, or any of the likes.

**Comment by Surrealistik** [comment]
The problem with discussing only tasers however, is that the surrounding context/balance wholly determines whether or not tasers should be nerfed in this way, and whether this PR should be merged, so that broader context must be a part of the discussion.

Bottomline, I don't think that tasers should have their instastun nerfed if we are going to be doing nothing else to address/revise that context, and the scope of changes concerning the balance of instastun will be restricted to the taser for an indefinite period.

**Comment by fj45** [comment]
Assuming more balance changes will follow.....I support this PR.

**Comment by ZomgPonies** [comment]
Seems like a strong :-1: to the current implementation of this PR. Someone needs to make a new one where tazers are simply replaced by disablers. And puts in the majority changes from these comments.

**Pull request closed without merging**
