### PR TITLE
Updates to rust, fungus, and rot

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
At the request of Denthamos:

- Removes wall rot event entirely
- Space fungus now uses wall rot sprites
- Rust now uses space fungus sprites

## Why It's Good For The Game
The temporary rust overlay looks really naff, denth requested I shuffle things about this way to improve the icons. While we do lose wall rot, the event and its consequences are so infrequently noticed or meaninfgul it won't make any difference in practical terms.

## Images of changes

Fungus seen on the left wall, rust on the right.
image

## Changelog
:cl:
del: Removed wall rot
tweak: Space fungus use old wall rot sprites
tweak: Rusty walls use old space fungus sprites
/:cl:

### CODE REVIEW

**Comment by Denthamos** [comment]
I know Bmon was interested in going for an entirely new sprite for rust spawner and possibly changing the space fungus as well due to the new wall depth textures with the 220 turf PR, so will hold off on approval of this until they get a chance to try and figure something out there.

**Comment by moxian** [comment]
I'm afraid fungus would now be exceedingly hard to hunt in maints. It's pretty subtle on the screenshot already, and would only get more so with poor lighting and if it happens to spawn on the "far" [from the light source] side of the wall.
And i'll second Denthamos here, in that the overlays should probably be showcased against the ss220 walls.

**Comment by S34NW** [comment]
This seems unwanted? Or at least going to be significantly held up by other factors. Will close with the view to reopen when it can be implemented.

**Comment by S34NW** [comment]
reopened at AA request so he could see who was objecting. Bye.

**Pull request closed without merging**
