### PR TITLE
Blueshield Beret Tweak

### PR DESCRIPTION
**Pull request by KasparoVy**
Resolves issue #3380.

Adds a navy blue version of the Centcom Officer's beret, giving it to the Blueshield.

Gives the Blueshield beret the exact same armour and strip-delay values as the SECURITY OFFICER'S beret.

:cl:
rscadd: Navy blue Centcom Officer's beret for use by the Blueshield.
rscadd: Adds the new navy blue beret to the Blueshield's locker.
tweak: Gives the Blueshield's berets (black and navy blue) the exact same strip delay and armour as the Security Officer's beret.
/:cl:

*Blueshield's Beret in Action.*
blueshieldberet

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
It having the same armor values and strip time as the sec beret is fine.

**Comment by KasparoVy** [comment]
Sweet, sounds good to me

**Comment by IcyV** [comment]
I agree fully with adding the armor to it, but I'm not sure how I feel on changing the color. The black version fits each version of their outfit fine. Whether it be the coat, armor, or just their bare uniform. The blue stands out as rather odd and doesn't fully match the theme.

**Comment by KasparoVy** [comment]
I had a similar thought, but it was a suggestion. BRB, I have a compromise. I should've done this to start with..,

**Comment by IcyV** [comment]
Similar to how they start with the armor and get a coat in the locker, you could potentially just have one of each version available. Spawn with the black or blue, the other would be a choice in the locker. Couple of ways to go about it perhaps. I don't mind the blue, I just feel the black fits a lot better.

**Comment by KasparoVy** [comment]
The idea was to readd the black beret so they could just choose.

**Comment by IcyV** [comment]
I'd be cool with that. Let people make their choice on how they want to accessorize.

**Comment by KasparoVy** [comment]
Thanks for bringing that up, bad oversight

**Comment by Plotron** [comment]
I like it. I really do.
Too bad I only play Plasmaman Blueshield!

**Comment by KasparoVy** [comment]
Duct tape it to your helmet! Where there's a will, there's a way.

**Pull request merged**
