### PR TITLE
Move free golems to lavaland

### PR DESCRIPTION
**Pull request by datlo**
Now that we have lavaland, we can move free golems back to their intended home. 

While having free golems being able to move around space sectors was interesting, in practice golems would stay parked near the mining asteroid almost all the time. I suspect this will remain the case if I changed the ship to be able to move to lavaland. It is better to standardise golems and have them work like other lavaland ruins, since that will not change their gameplay too much.

The golem ship was completely removed from the map, aswell as the small asteroid near telecomms. It will now spawn as a static space ruin in lavaland. No major changes to free golem gameplay other than the fact you cannot fly away from lavaland. Due to this change, free golems can now spawn on any roundtype, which should not be an issue as they are mostly confined to lavaland and follow the rules of other lavaland ghost roles in that.

Fixed a couple of issues with the golem ship itself, and removed the free KA the golem ship started with. I underestimated how fast golems could get setup working as a team, and they do not need more headstart than the upgraded resonator they still get. 

Another PR hopefully coming soon to add ashstorm/lava proofness to the appropriate golem subtypes, aswell as smash some golem bugs that are still around.

Changelog:
🆑
del: Free Golems can no longer fly to various space sectors.
tweak: Free Golems are now a lavaland ruin spawn. 
tweak: The Free Golem ship is now fully destructible.
tweak: Free Golems no longer get a free kinetic accelerator on their ship.
/🆑

### CODE REVIEW

**Comment by TDSSS** [comment]
Nooooo. Let golems fly around, why remove that part? I think it gives our golems a nice, unique touch.

**Comment by datlo** [comment]
Golems as they are right now cant go to lavaland so they are a bit stuck in terms of progress options. Ill look into an alternative PR that adds a docking point to lavaland but that adds its own issues... will look into.

**Comment by SkeletalElite** [comment]
> Golems as they are right now cant go to lavaland so they are a bit stuck in terms of progress options. Ill look into an alternative PR that adds a docking point to lavaland but that adds its own issues... will look into.

Can you make their spawn/ship a lavaland ruin and then they can take off from lavaland? I think it'd be cool if the console board to control their ship had to be bought from the vendor too as a kind of "repair cost" for the ship

**Comment by Sikroth** [comment]
I'm in favor of moving the golems to lavaland, as that's kinda where they belong to begin with.

That said, I guess they could also spawn at the old mining asteroid Z-level and have it entirely for themselves, if people are adamant in keeping them in space instead of on lavaland.

**Comment by datlo** [comment]
PR above is an alternative that keeps the option for golems to move the shuttle to the derelict or to the construction site by buying the shuttle board for 2000 points.

**Pull request closed without merging**
