### PR TITLE
Small fixes for foam force weapons and smg mags

### PR DESCRIPTION
**Pull request by shazbot194**
-Adds a new icon for the toy tommy gun with a blue muzzle, so it doesn't have to use the real tommy gun's icon or what is was using, nothing.
-fixes the rounding on the toy smg so it now doesn't have an invisable magazine when loaded and displays the correct amount of ammo.

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Can you fix the problem where reloading a loaded foam force shotgun doesn't eject a dart?

**Comment by shazbot194** [comment]
I'll look into it, I think it might be a tiny bit of code missing as the tommy gun functions the same and does eject the dart when cycled.

**Comment by shazbot194** [comment]
I think I found what is causing it's:

/obj/item/weapon/gun/projectile/shotgun/toy/process_chamber()
	..()
	if(chambered && !chambered.BB)
		qdel(chambered)

I'll see if that's the case when I get back on a computer.

**Comment by shazbot194** [comment]
After a bit of testing, I think I know what is wrong, but it will take a little bit to finish ironing it out and I think it would be better to make a new pull for it since it will be more invasive.

**Comment by shazbot194** [comment]
So any updates on if this will be merged or closed? All the code changes have been tested a lot and work perfectly.

**Comment by shazbot194** [comment]
So it turns out that the normal smg has only 21 rounds now, so I changed the both the way its rounded and the sprite names so the code is both smaller and is simpler. However, with all of this, the normal saber magazine would normally have a sprite error on a magazine with only one bullet since it would need to be shifted, this keeps it from having 1 round down to 0, but makes 21 round to 24, this means it needs another full ammo icon. I added it, but think it was worth mentioning.

**Pull request merged**
