### PR TITLE
"Fixes" PDW9 Gun Sprites and Description

### PR DESCRIPTION
**Pull request by Fox-McCloud**
By removing them.

Seriously, what the heck is this sprite?

img

More seriously, Blueshields revolver (the parent type) is now functionally identical to energy guns at this stage---I pondered replacing it, but the archetype is so strong, I opted not to (for now).

That said, ERT don't really have an archetype. 

This solves the description and sprite issues of the PDW9---and gets rid of freaking sprite bloat to begin with.

:cl: Fox McCloud
tweak: ERT have energy guns instead of PDW9's (same number of shots and both have disable and laser)
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
I feel like this gun was meant to be a reference to the mass effect pistol https://static.wikia.nocookie.net/masseffect/images/2/20/ME2_HP_-_Predator.png/revision/latest?cb=20140823153532

**Comment by Norwes1** [comment]
The PDW-9 also fits in a holster, which IIRC the regular laser rifle does not. It's a useful side bonus, especially since NT is /supposed/ to favor lasers over ballistics.

**Review by SteelSlayer — APPROVED** [review]
Code's fine.

**Comment by SabreML** [comment]
It may just be me who's confused about this since nobody else has brought it up, but I have to ask: Should this really be labeled as a fix?
The description says it's a removal, the changelog says it's a tweak, and the "Fixes" in the title is in quotation marks. While this *does* technically fix the issue, surely it should have the `Revert/Feature Removal` and `Sprites` labels instead, or at least `Tweak`.

It wouldn't usually matter what labels a PR has, but the implementation of GBP as well as the current feature freeze means it's a lot more important now that everything is properly categorised.

**Comment by AffectedArc07** [comment]
Subtypes for the sake of it have no purpose. If it's functionally identical to an energy gun, and it just has a worse sprite, why are we keeping it?

As for the holster argument, the roles that get this don't have holsters (afaik) so it's a moot point.

Tagging this as a fix isn't something I necessarily agree with but that's not my issue to fight against anymore.

**Comment by dearmochi** [comment]
Closed at their request.

**Pull request closed without merging**
