### PR TITLE
Nerfs holy water.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattestGuitar
tweak: Holy Water will no longer make you stutter for ages if you're not a cultist
/:cl:

After we had to turn someone's stutter down from 20 minutes, this had to happen.

### CODE REVIEW

**Comment by Plotron** [comment]
:(

**Comment by Jaywings** [comment]
OH MY GOD YOU FUCKING NERFED THE ALREADY UNDERPOWERED WEAPON IN THE GAME PLEASE GET OUT OF HERE

**Comment by tigercat2000** [comment]
technically you could argue this is a buff

**Comment by Lady-Luck** [comment]
Can you give this min treatment to flashbangs too? I got hit with a cluster flashbang the other day and I had to be admin rejuvenated

**Comment by Kyep** [comment]
Why not cap the maximum stutter time holy water can give you?

After all, what if sec gives someone a zillion units of holy water, e.g: via pills? They'd still stutter for ages - unless the maximum time was capped.

**Comment by Fox-McCloud** [comment]
>Why not cap the maximum stutter time holy water can give you?

That's....exactly what this PR does.

**Comment by Kyep** [comment]
Ah, got thrown off by the "if you're not a cultist" in the description.

**Pull request merged**
