### PR TITLE
blocks space from anomaly events.

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

blocks space from anomaly events.

## Why It's Good For The Game

anomalies should not spawn in space. Fix 23556

## Testing

Compiled, now in list of blocked areas. Event ran.

## Changelog
:cl:
fix: blocks space from anomaly events.
/:cl:

### CODE REVIEW

**Comment by DGamerL** [comment]
Does this fully fix #23556?

**Comment by Qwertytoforty** [comment]
> Does this fully fix #23556?
It should, I suspect it spawned on a tile next to toxin testing, and moved to it instantly, since it was reported as space.

**Comment by DGamerL** [comment]
> Fix 23556
```suggestion
Fixes 23556
```
This should make it autoclose

**Comment by Qwertytoforty** [comment]
> > Fix 23556
> 
> ```
> Fixes 23556
> ```
> 
> This should make it autoclose

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Fix is a valid word for autoclosing. I pick one at random usually

**Comment by DGamerL** [comment]
I see the issue, it's missing the `#` in front of the number

**Review by DGamerL — APPROVED** [review]
LGTM

**Review by SteelSlayer — APPROVED** [review]

**Comment by Screampuff** [comment]
I believe this also fixes #23294

**Pull request merged**
