### PR TITLE
fixes #3421

### LINKED ISSUE #3421: Rig Combat/Travel Modes bugs
If you activate travel/combat mode on a helmet that is attached to a suit, you're able to simply remove the helmet with your hand. You cannot place it back on your head unless you use the toggle helmet verb.

Additionally, changing to combat/travel mode on the elite syndicate hardsuit changes the name of both the suit and helmet to blood red hardsuit helmet.

### PR DESCRIPTION
**Pull request by VampyrBytes**
Fixes name and description of elite syndie suit after toggle mode

Don't close #3421 yet, I'm looking into the other part but need more info

Edit - Both parts now fixed in this pr

### CODE REVIEW

**Comment by VampyrBytes** [comment]
Ok, that's both parts fixed :smile:

**Comment by Fox-McCloud** [comment]
You need to update your local branch via the command line before making changes, otherwise, you're going to bloat your commits with "merge remote" commits that should *only* be in PRs with conflicts (and initially submitted PRs should *never* conflict).

**Comment by VampyrBytes** [comment]
@Fox-McCloud Ah right. Was updating my master through the gui, and yeah, was getting one of those merge remote commits each time.

Figured out how to avoid them in the future, so shouldn't be anymore

**Comment by Fox-McCloud** [comment]
Won't this cause issues if you remove the suit, but the helmet still has NO_DROP?

**Comment by VampyrBytes** [comment]
Hmmm, yeah, you're right. Ok, I can sort that

**Comment by VampyrBytes** [comment]
Tested and no, it doesn't, that's handled in rig. If you remove a rig while pieces are deployed they are retracted back in first

**Pull request merged**
