### PR TITLE
[AFD] Reverts Pet Collar Accessory Removal

### PR DESCRIPTION
**Pull request by chuga-git**
## What Does This PR Do

Pet collars are now a wearable accessory again. 

## Why It's Good For The Game

This will improve RP quality and fashion freedom of expression, which have been sorely missing since this accessory's removal.

## Testing

works great
ohgod
## Changelog
:cl:
add: Pet collars can now be worn as an accessory again.
/:cl:

### CODE REVIEW

**Comment by SynthTwo** [comment]
degenrat

**Comment by Onyxarias** [comment]
Based. Keep it after April Fools

**Comment by ATP-Engineer** [comment]
image

**Comment by S34NW** [comment]
I hate you

**Pull request merged**
