### PR TITLE
Blueshield Coat

### PR DESCRIPTION
**Pull request by TheBeoni**
Adds Blueshield coat to code(resprited detectives coat). Adds Blueshield Coat and Jacksandals to Blueshields locker.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Stillll not right. =x

**Comment by TheBeoni** [comment]
I have no damn idea why did it remove collar

**Comment by KasparoVy** [comment]
:+1: if you fix dat collah

**Comment by TheBeoni** [comment]
I would fix it its easy. But i cant edit it.

**Comment by ZomgPonies** [comment]
Since the collars were removed from the merch computer, consider this a cleanup at the same time.

**Comment by TheBeoni** [comment]
Also added it to closet in blueshieds office...erm i also added jacksandals(which Unathi and Tajara Blueshields are missing) there i hope you dont mind.

**Comment by ZomgPonies** [comment]
Update the PR description with all the changes please.

**Comment by TheBeoni** [comment]
I hate my life....

**Pull request closed without merging**
