### PR TITLE
Makes non-station z-levels generic 🗺️

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattestBanjo
tweak: MetaStation now has all the same off-station z-levels as Cyberiad, whatever the differences were.
/:cl:

Because I hate fun

I also hate having to map two of the same map at once; why would you do
that!?

### CODE REVIEW

**Comment by tigercat2000** [comment]
Deleting z2 is an absolute no-no, Cyberiad's Shuttle does not fit in the metastation dock and will destroy things when it lands.

Aside from that, Metastation has unique aspects to *all* of it's off-station z-levels, I don't see why we should just scrap them.

**Comment by Crazylemon64** [comment]
Sounds like a good idea to me

**Comment by Aurorablade** [comment]
its annoying flat but theres a lot of things to consider when having the two z levels mesh with each other and this might best be left for another point in time

**Comment by Fox-McCloud** [comment]
I'd also worth pointing out that telecomms is on z-level 2 on the Cyberiad, but it's on station for Meta.

That's going to cause issues.

**Comment by FlattestGuitar** [comment]
Would you say it'd be acceptable to make all non-z2 levels generic, then?

I don't think there's anything station-specific here...

**Comment by Fox-McCloud** [comment]
>Would you say it'd be acceptable to make all non-z2 levels generic, then?'

Z-level 5 is also problematic.

**Comment by tigercat2000** [comment]
@Fox-McCloud Cyberiad telecomms is z3, not z2

**Comment by taukausanake** [comment]
z2 is all of CentComm and other things you should never get to

**Comment by FlattestGuitar** [comment]
I give up.

There is no saving of the z-levels.

Farewell, PR, we hardly knew ye...
👋 🎻 🎶 😢

I should do better research next time, I think.

**Comment by Kyep** [comment]
@FlattestGuitar Please don't give up on this.

Yes, some things about metastation (e.g: shuttle, telecomms) will need to be moved to make the other z-levels compatible. However, I think that this is well worth doing.

Right now, we have a situation where any change to any zlevel other than the cyberiad has to be effectively made twice - one for the cyberiad map, and once for the metastation map. That almost doubles all the work of those map edits. Both to make them, and for the maintainers to review them.

Any PR that doesn't do this dual-editing results in divergence between metastation and boxstation. Typically this manifests in things people expect from box, simply not working with meta. For example, ERTs and various other teams. This is bad, because if we do ever switch to metastation, we have to deal with a bunch of things people are used to, suddenly not working anymore. That sucks.

Moving telecomms, changing the shuttle, etc, might be a hassle, but it is a one-time change that significantly reduces the hassle of future mapping PRs. In my opinion, it is well worth doing.

Yeah, we lose a little bit of the uniqueness of metastation, but IMHO that does not matter one bit. Meta can be as unique as we like, but that's irrelevant if we never use it. Standardizing the non-z1 levels makes it far more likely we'll actually be able to use Metastation without a bunch of stuff breaking. It is a buff, not a nerf, to metastation, even if meta becomes a little less unique in the process - what we gain is well worth it.

**Comment by Crazylemon64** [comment]
After I get the space allocator ported and operational, I'll look into making z2 special role lairs get their own spaces.

**Pull request closed without merging**
