### PR TITLE
Prevents pulling live terror spiders

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
tweak: Live terror spiders can no longer be pulled around.
/🆑

The ability to drag live terror spiders allows them to be dragged away from vents they're trying to crawl into, which makes them too easy to kill. It also doesn't make much sense, given that they're bigger than the average humanoid, have many legs, and have a low center of gravity.

### CODE REVIEW

**Comment by Plotron** [comment]
Can you pull dead spiders, though?

**Comment by Kyep** [comment]
No, but that arguably doesn't matter, as dead spiders naturally gib after after some time, so their corpses won't remain there forever.

**Comment by Kyep** [comment]
Changed.

**Comment by tigercat2000** [comment]
This is being declined, for multiple reasons;
1. This implementation is not ideal, we would highly prefer porting https://github.com/tgstation/tgstation/pull/39556 over a boolean flag that prevents spiders from being pulled.
2. We don't view this as a positive balance change; Vent-crawling has a delay for a reason. If a spider has gotten itself caught so badly that someone is actively attacking it while it's trying to crawl away, they fucked up. They need to find other options, either running further, or trying to kill the person pulling them away.

**Pull request closed without merging**
