### PR TITLE
Add autolathe to science

### PR DESCRIPTION
**Pull request by theo-3**
## What Does This PR Do
Adds an autolathe to the science department.

## Why It's Good For The Game
Science needs an autolathe to make stuff like tools or prox sensors for bots and they always build one as soon as possible anyways.

## Images of changes
ezgif com-gif-maker

## Changelog
:cl:
add: Added an autolathe to science/robotics
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Ultimately I'm neutral towards this.

On one hand, I get very annoyed with roboticists that run off to steal the autolathe board from engineering five seconds after the round start.

On the other... this can be built fairly early on in, fairly cheap.

I'm also not sure how I feel about its placement in this PR, but perhaps I just need to adjust. I typically replace the reinforced table with an autolathe whenever I run robotics, so this looks a bit off kilter to me.

Overall, eh, I can definitely understand the logic behind this PR and appreciate it. I do, however, believe that roboticists should lose access to engineering tool storage, regardless of whether or not this change goes through. There is absolutely no need for them to have it, and engineering has far more immediate use for an autolathe than robotics or science.

**Comment by theo-3** [comment]
I didn't remove the table because it's useful for giving stuff (like iron or yellow cores) to robotics without dropping things on the floor or waiting for them to come open the door

**Comment by theo-3** [comment]
Also, I mostly added this for scientists to print tools. I placed it in robotics because that allows both robotics and science access to it without letting scientists into robotics

**Comment by Fox-McCloud** [comment]
They had this before, and it was remove for a reason; they don't need it back.

Science is already the most overtuned department; returning it to its former glory is not in the cards.

**Comment by AffectedArc07** [comment]
#7379


We removed it for a reason. 

In my honest opinion, R&D should be producing their own autolathe, not stealing the one from tech storage. 

Not in favour of this PR

**Comment by FreeStylaLT** [comment]
img

**Pull request closed without merging**
