### PR TITLE
Resprites the Hand Tele

### PR DESCRIPTION
**Pull request by ExusA**
## What Does This PR Do
 Updates the sprite for the Hand Tele. Here's an explanation of the new design:
The hand tele works by carefully applying electric pulses to a big bluespace crystal. It only has one slider and two buttons to adjust your destination, since the hand tele only lets you pick a few options from a list.
The buttons would scroll through possible destinations, and you would pull the slider to generate a portal.

## Why It's Good For The Game

The hand tele sprite is really old and could use a refresh.

## Images of changes
Normal:
Hand Tele
EMP:
Hand Tele EMP
Old:
Old Handtele

Edit,
The design has been changed to this as per feedback:
Hand Tele EMP
Hand Tele

Edit,
The design has been changed a second time at request:
Hand Tele 2 EMP
Hand Tele 2 Idle
Hand Tele 2

## Testing

Compiled and looked at the hand tele in game.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imageadd: Resprited the hand tele.
/:cl:

### CODE REVIEW

**Comment by ExusA** [comment]
Also, I removed some unused detective scanner icons from device.dmi since I was working on it. They're old codersprites that we won't be able to repurpose for anything else, so I hope it's alright for the sake of cleaning things up.

**Comment by 1080pCat** [comment]
Not the biggest fan of this respite tbh. It kinda looks like a toy more than a prototype hightech item.
i will say, that i like that the EMP state is more clear. Though the wire being broken is a little odd

**Comment by ExusA** [comment]
After discussing it in spriting, here's a new design that resolves some of the issues with the old one. It's made of plastitanium this time, has a more sensible grip, and has a wire panel coming out the side.
Hand Tele EMP
Hand Tele

**Comment by ExusA** [comment]
Drafted pending requested changes.

**Comment by ExusA** [comment]
I've redone the sprite again on request. These are the new sprites:

Idle:
Hand Tele 2 Idle
EMP:
Hand Tele 2 EMP
On opening the destination menu:
Hand Tele 2

**Comment by ExusA** [comment]
Redrafting this until I'm able to nail down a perspective and look that's consistent with other new ingame items.

**Comment by ExusA** [comment]
Alright, thanks everyone who's taken the time to consider this PR. 
I'm going to close it for the time being, because I don't feel the shading and styling is in line with what the server is aiming to produce, and I don't want to try push for badly-fitting sprites to go in the game.

I'll open a new PR if I'm able to produce something closer to the current direction, but by all means if anybody ends up respriting the hand tele in the interim, I'm satisfied the wasted effort will have been a good learning excersise and I wouldn't mind.

**Pull request closed without merging**
