### PR TITLE
'Who' verb chat spam improvement

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Split up the 'Who' verb into two separate parts, so that the player list is hidden behind a prompt.

## Why It's Good For The Game

Using 'Who' currently fills your chat up with the ckeys of everyone on the server, generally 70-150 lines.
Splitting the player numbers and the player names into two separate things makes the verb actually feasable to use.

## Images of changes

e
*(Obviously there would be more than 1 on the live server)*

## Changelog
:cl:
tweak: Split up the 'Who' verb into two separate parts, so that the player list is hidden behind a prompt.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Why don't we just put the player count in the status pane of the stat panel instead of changing who to require extra button clicks and more mouse movement to view a player list (which most people use it for)

**Comment by SabreML** [comment]
> Why don't we just put the player count in the status pane of the stat panel instead of changing who to require extra button clicks and more mouse movement to view a player list (which most people use it for)

Personally I'd rather keep it out of the status tab if possible, since that shows ingame stuff like synced borgs, GPS location and active internals; I feel like it'd be out of place there.
And I've always used the verb to check player numbers rather than who specifically is online.

**Comment by AffectedArc07** [comment]
I have always used it to see whos on, and I feel like this would be better, since a lot of servers already do it
image

Disclaimer: This is by no means me saying we need *all* of these things, but I feel like playercount could easily go in here instead

**Comment by Fox-McCloud** [comment]
Going to second @AffectedArc07 on this one; having it in the stat panel would be better.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
