### PR TITLE
Dismembering now uses health of the limb instead of damage of the weapon!

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
Prior to this PR, the probability of you dismembering a limb that reached max damage(head's maximum damage is 75) was the damage of the weapon divided by 2, this means a fireaxe had a 12% chance of dismembering the head even after it reached 75 damage. This change makes it so it bases the chance off the damage of the organ divided by 5 this means that a fully damaged head has a 15% chance of dismembering per swing. Though do note that it makes it slightly harder to dismember hands and feet at max damage(these have a 6% chance at max damage) and arms and legs(these have a 10% chance at max damage).
**Changelog:**
:cl:
add: Dismembering uses the health of the limb instead of the damage of the weapon
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I don't think we need to make dismemberment a *primary* combat mechanic.

Having people straight up lose combat, instantly, because they had over 35 damage to the head is pretty BS.

Dismemberment should largely be a fluff mechanic rather than a *primary* combat mechanic.

**Comment by Couls** [comment]
Yeah, after some initial testing leaving it at max damage seems like the way to go

**Comment by Fox-McCloud** [comment]
I smell web editor.

Stop.

**Comment by MrMagolor** [comment]
Shouldn't dismemberment be based more on the SHARPNESS of a weapon than direct damage? Probably already a thing, but a chainsaw should be better at dismembering than a hammer, generally.

**Comment by Couls** [comment]
A weapon that is not sharp has a significantly lower chance of dismembering

**Comment by taukausanake** [comment]
> A weapon that is not sharp has a significantly lower chance of dismembering

:thinking: And your point...?

**Comment by Couls** [comment]
The code doesn't really have a sharpness variable, the weapon is either sharp or it isn't

**Comment by taukausanake** [comment]
I think that's what was implied by Magolor. If going just on damage you can dismember someone with a toolbox. You should probably only ever dismember with just something that is sharp, anything sharp by that

**Comment by Couls** [comment]
That’s what I meant when I said a weapon that is not sharp has a significantly lower chance to dismember I didn’t change how blunt weapons are handled simply sharp ones

**Comment by variableundefined** [comment]
I echo Fox's concerns - We shouldn't make cutting off limbs easy.

**Comment by Couls** [comment]
RIP

**Pull request closed without merging**
