### PR TITLE
Adds flipped poker table sprites (And fixes other flipped table sprite shenanigans)

### PR DESCRIPTION
**Pull request by Adrer**
## What Does This PR Do
- Adds sprites for flipped poker table so it will no longer go invisible upon flipping
- Minor consistency fixes in other flipped table sprites 
*(I swear to god ALL flipped tables had ONE missing pixel and it was driving me insane, plus whoever did the sprites for the flipped wooden tables was very sloppy.)*

fixes: #8122

## Why It's Good For The Game
While making a poker table seemingly disappear into thin air makes for a neat party trick, I personally like it when flipped poker tables remain within the visible light spectrum.

## Images of changes
Poker table sprites
image

For other minor sprite fixes please check IconDiffBot 
~~(It's 3 am please I cannot be bothered to add in more images)~~

## Changelog
:cl:
tweak: added state for flipped poker table to table code
imageadd: added flipped poker table sprites
imageadd: fixed minor inconsistencies in other flipped table sprites
/:cl:

### CODE REVIEW

**Comment by Dashsora** [comment]
Fancy tables have this exact same problem if you're feeling up to the task !

**Comment by Adrer** [comment]
> Fancy tables have this exact same problem if you're feeling up to the task 

Probably something I'll pick up if I get the chance, but unlike these tables it'd be a bit more spriting work, so another time.

**Review by variableundefined — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
image
Phantom pixels in sprites

**Comment by Adrer** [comment]
> image
> Phantom pixels in sprites

Guess this is why you should use dark mode

**Comment by AffectedArc07** [comment]
> > image
> > Phantom pixels in sprites
> 
> Guess this is why you should use dark mode

I mean why wouldn't you

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
