### PR TITLE
Adapts TG's version of Metastation for Paradise

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Massively overhauls Metastation to be nearly on par with its modern TG version while bringing it in line with the Cyberiad balance and department wise.

Kills an unlistable amount of map-related bugs with Meta.

Expands maintenance from the baseline TG version.

Adds a few new zones for Meta and renames the breakroom zone to Medbay Breakroom.

Adds a nameplate for the station.

Adds a red collision beacon used on the map.

Moves some unused floor decals out of floors.dmi and into decals.dmi so that they may be used.

## Why It's Good For The Game
I personally have played a lot of Meta from my time on TG, it's probably one of the top played maps over there, so I was disappointed to see the state Paradise's version was in. With this in mind, I decided to manually remap a good chunk of our version of Meta using TG Meta as a guide, bringing one of SS13's most iconic maps up to current day standards.

I believe that this version of Meta will fix most of the outstanding issues players have with the map.
## Images of changes

oldtgnew

CEREBRON
## Changelog
:cl:Bmon
add: Massively overhauls all of Metastation based on TG's version of the map (please play it I swear it is good now)
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
Morgue has been reworked to be a bit bigger and medmaints is now connected to the rest of maints!

image


Also fixed a few piping/wiring bugs and bump errors with the APCs

**Review by LightFire53 — CHANGES_REQUESTED** [review]
### Security

Permanent Detention should have blast door lockdown, all I could find were some shutters called "lockdown shutters". They should be on all the entry/exit points, including windows.

Warden's office needs a light switch and intercomm.

Firing range needs an intercomm, same with the gear room and the security office.

Perma should also have some form of riot control installed as well, be it wall mounted flashes or N2O gas.

Brig shutters only block the station side access to the brig, not the space facing windows. Should become a proper brig lockdown.

As much as I love the maintenance bar by the brig, IAA could use a bit more space to comfortably fit two

image

Vent heresy in evidence. As well, we need an intercomm and light switch in here

image

Scrubber heresy in interrogation

image

And more

image

And the armory. The armory security camera seems to have a big hole on the left side, if it swaps to the other side of the room it should clean that up. Speaking of, as well the external security camera is traditionally part of the secure armory area. 

image

image

And the justice center. And solitary.

image

And the detective's office, which also doesn't have a camera while we are here.

image

We try to avoid pipes under windows where possible, these can run under the airlock

### Supply

QM office needs a light switch and fire alarm, as per mapping standards for areas. They also need a firelock on their airlock. May also be nice to give them a supply shuttle status console

The lobby area for the main supply desk should probably get a security camera.

image

Should run under airlocks, not windows. Also while it technically doesn't require an intercomm in this room (as there is one in the room next door in the same area), may want to add one here.

Warehouse needs an intercomm as well (map standards)

Primary tool storage needs a fire alarm.

### Service

Janitor should have a second spawn point

image

Chapel has shutter control button, but no shutters/windows it's linked to

Mime and Clown offices need: firelocks, fire alarms, light switches, intercomms, and maybe a window to make it less dreary?

Barber needs an intercomm

In a weird twist, the theatre almost has _too many_  light switches, 2 in each "room". Still needs a fire alarm

Bar needs an intercomm

Kitchen is missing the oven

### Engineering

image

Pipes under windows again can be moved under airlock at gravity. Firelocks needed as well, same with an intercomm.

Same pipes under plasma glass with the supermatter engine room, but I'm not sure if this serves an atmospheric purposes or someone's disdain for mapping standards (since box is guilty of this more heinously)

Intercomm in secure storage

image

Vent heresy

CE should have electrochromic windows, not blast doors. Also not sure how secure it is to have the chief engineer's locker by a window facing a public hallway.

image

Windows again. Also need an air alarm and intercomm

Intercomm in engineering shared storage

Drone room needs a light switch and intercomm

Won't really delve on atmospherics as it's outside my knowledge, but we have some more pipe heresy culprits.
image
image
image
image

### AI Sat

image

Unhooked scrubber, and AI sat has shutters on areas where they aren't needed (entrance and window in front of primary AI core)

This AI core set up also experiences the same issues as Delta where turrets don't actually provide defenses for the AI itself.  #17723 may provide ideas for a potential remap/Denthamos's criteria

image

Heresy being elevated to new levels, power cables under walls

image

Telecomms section needs firelocks, plus a light switch for both rooms, a fire alarm and an intercomm for the server room proper

image

Railings on the end of these beams need to be near space area

### Science

image

Vents on pipes

image

I'm not 100% certain on how this one interacts, but I think it's fine?

image

IMO, either go all tinted window or not, but wouldn't do this mix and match. And TBH, if tinted windows are used this way you may as well swap to just walls instead. Alternatively, electrochromics?

image

See above

image

Robotic storage needs a robotic storage console nearby. Also need a firelock between the mech bay and the robotics lab

image
image

More scrubber heresy

image

This feels really empty at the end, maybe throw some vending machines?

### Medbay

Chemistry should get the wall welding tanks, as well as the chemistry disaster counter. _(Side note: I'm 3 hours into this review, and I don't want to go back to put it in the appropriate spots, but the other disaster counters are missing too: Toxins, Supermatter, Sci-Chemistry)_

image

Maybe one way all access helpers to let people out?

image

Scrubber heresy continues

image

Vent heresy continues

image

Heresy part 394, presumeably

image

If what we had before was heresy, this is blasphemy.

Medical storage beside exam room needs an intercom.

Exam room needs an air alarm and an intercomm

Surgery 1, Surgery 2, the storage room by them, and secondary storage also need intercomms

image

Stray disposal pipe in medical break room

### Command

image

May have to move this dimmer, these typically have a range of either 7/8 tiles, and I don't think it will reach all the way to the other side. Either that, or adjust the range.

Light switch needed in the gateway

Intercomm at the teleporter

image

Should go under airlocks

image

3 cameras seems overkill here. Also needs firelocks, fire alarm, and light switch.

Vault needs an intercomm, fire alarm, and firelocks

### General Areas

image
image
image
image

Would appreciate a widening of these maintenance area

image
image
image

More vent/pipe related shenanigans

Light switch and intercomm in Mr. Changs

I'm sure there is more, but that is my initial review for the moment.

**Comment by Bm0n** [comment]
I am surprised piping under scrubbers or vents is an issue. All the pipes are done that way on TG, even in older versions before they switched over to smart pipes and I don't seem to be getting any runtimes from it. Either way, I'll set to work on fixing it

**Comment by ItsMarmite** [comment]
> I am surprised piping under scrubbers or vents is an issue. All the pipes are done that way on TG, even in older versions before they switched over to smart pipes and I don't seem to be getting any runtimes from it. Either way, I'll set to work on fixing it

The issue with overlapping scrubbers and supply pipes / vents with scrubber pipes is scenarios can occur where those pipes merge and you end up with plasma coming out of vents. Its a known issue with devices and pipes.

**Comment by Bm0n** [comment]
Fixed all of the errors LightFire mentioned plus a few that I caught on my own. I'll see about widening areas tomorrow after I get some sleep.

**Comment by Bm0n** [comment]
I redid all of the hallway atmos, every vent/scrubber on the station, and expanded the IAA's office, maints and the cooling loop.

If there's anything still missing do let me know if not I believe this is ready for review.

**Comment by Bm0n** [comment]
Tweaked the AI core a little bit by moving two of the outer turrets closer to the core which should provide greater coverage on the side flanks, also added two windoors to the secondary AI core locations

image

**Comment by Bm0n** [comment]
Did a little theming thing for the map that should help newbies learn it. Basically, if a maint door doesn't have a yellow warning stripe beside it that means it's a dead end. Warning stripes point to rooms that lead to other rooms or hallways

**Review by S34NW — CHANGES_REQUESTED** [review]
<details><summary>Images of changes within</summary>

image
this area is not big enough for admin square shuttles, they will clip the beacons (template brings them right up to the wall)

image
random railing outside abandoned bar?

image
another outside disposals

image
this in arrivals maint is a bit confusing, can the wire node be placed horizontally?

image
Near AI upload and in its entry area there are dark floors coloured with four white decals.

image
also present here in AI sat

image
and in CE office

image
and tech storage

image
these are decals too, but I don't see another way of getting this pattern so I think it is okay

image
more decals here

image
image
and here

image
morgue too

image
unconnected wire under the HoPs desk

image
missing wire here in arrivals south maint (although this area has two feeds running in parallel, it doesn't need them to be honest
</details>

**Comment by Bm0n** [comment]
> image this area is not big enough for admin square shuttles, they will clip the beacons (template brings them right up to the wall)
> 
> image random railing outside abandoned bar?
> 
> image another outside disposals
> 
> image this in arrivals maint is a bit confusing, can the wire node be placed horizontally?
> 
> image Near AI upload and in its entry area there are dark floors coloured with four white decals.
> 
> image also present here in AI sat
> 
> image and in CE office
> 
> image and tech storage
> 
> image these are decals too, but I don't see another way of getting this pattern so I think it is okay
> 
> image more decals here
> 
> image image and here
> 
> image morgue too
> 
> image unconnected wire under the HoPs desk
> 
> image missing wire here in arrivals south maint (although this area has two feeds running in parallel, it doesn't need them to be honest
 
1: The area is big enough for the shuttle, I tested it.

2 and 3: It's just detailing for space, a railing for a spaceman to hold onto and the same as it is on TG.

4: Sure I'll move it.

5, 6, 7, 8, 9: That's how TG gets those darkgrey tiles on the older version of the map. No, I am not kidding. At least I am not using decals for every floor detail as TG does, overall way fewer turf decals than TG for that sole reason.

10 and 11: Wires fixed.

**Comment by Bm0n** [comment]
Alright, a lot of the tile decals are removed now. Also, I did some performance checks and my version of Meta is using about the same amount of ram as Box and a lot less than Delta. We should be good on the performance front.

**Comment by Bm0n** [comment]
Improved the escape departures lounge for security, it now connects to the security side of the shuttle like in Box and holds a lot more people. 

image

I should be done now, going to leave the rest up to reviewers or feedback but everything to me looks a okay.

**Comment by Bm0n** [comment]
Xenobio got extended a little bit and medbay has lockdown blast doors now
image

**Comment by AffectedArc07** [comment]
Comments below this point correspond to the testmerge during round 31471
---

**Comment by serinuku** [comment]
commenting as i go but one mistake i noticed so far is that for some reason civilians dont have access to the outside supply console and couldnt order stuff.

**Comment by Bm0n** [comment]
> commenting as i go but one mistake i noticed so far is that for some reason civilians dont have access to the outside supply console and couldnt order stuff.
Good catch, it's fixed in the latest branch along with the bridge and HOP's office console now being the private type

**Comment by GDNgit** [comment]
Screenshot 2022-05-27 160201
Screenshot 2022-05-27 160358
Screenshot 2022-05-27 162028
Screenshot 2022-05-27 160909
Should probably be changed to a normal wooden door, rather than a reskin

Screenshot 2022-05-27 161120 (2)

Odd smoothing

You can also get into the HOS office from the main vent network, which might not be good.

**Comment by Hostail** [comment]
Experimentor is lacking an R&D console to link to, so it can't do anything.

**Comment by Bm0n** [comment]
forgot to mention this in my commit but some lattice detailing was added here in space
image

**Review by S34NW — APPROVED** [review]

**Comment by Bm0n** [comment]
Another feedback change. Cryo now is bigger and has more stasis pods.
image

**Review by AffectedArc07 — APPROVED** [review]
You only live once

**Pull request merged**
