### PR TITLE
Item stumbling

### PR DESCRIPTION
**Pull request by Crazylemon64**
Any item that is not tiny is now capable of tripping you when you step on it, with a probability that starts out low for small items, that increases with the size of the item. This can either be negated by walking, or keeping your environment clear of detritus. 

Other items that trip or slip you have been refactored to work with this new system.

For normal objects, the rates are as follows:
* Tiny: 0%
* Small: 3%
* Normal: 5%
* Bulky: 10%
* Huge: 20%
* Gigantic: 40%

Other objects capable of possibly inducing a slip are pens, and paper, at 3% and 5% respectively.

:cl:Crazylemon
feature: Clutter that is Small or larger is now capable of causing you to stumble if you run on it. Keep your workplace tidy!
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
This sounds hilariously annoying and terrible, on the same level as mob trampling and Tajaran hairballs. God no.

**Comment by ProperPants** [comment]
Stand at disposals. Gather garbage. Drag it in locker. Open it in front of someone. Server chugs while it processes 69 billion instances of tripping.

Seems like it will be neat/funny though. Would be hilarious to see an antag trip over hallway garbage and get caught by sec.

**Comment by TravellingMerchant** [comment]
Totally, whole heartedly against this. Sorry.  Nope. No. Nada.

This is just a feature that will annoy players without bringing anything positive.

**Comment by Citinited** [comment]
This PR certainly does affect "Balance"... 😄 

In any case, my trampling PR didn't go through, and I'd expect this not to for the same reasons. 🤷‍♂️

**Comment by Fox-McCloud** [comment]
I bet the powergamers will carry stacks of floortiles or some other equally useless, but high density item just to throw at people chasing them; it'll hit the person that's chasing (making them take damage), drop in front of them, then give them a 5% chance to fall down because they'll probably step on it in the chase.

**Comment by Crazylemon64** [comment]
I'll close and re-open now that this is largely just a refactor, so people don't get the wrong idea

**Comment by KasparoVy** [comment]
I wish there was an "I concur" reaction emoji.

**Pull request closed without merging**
