### PR TITLE
Adds custom fluff cyborg sprites for travellingmerchant

### PR DESCRIPTION
**Pull request by TravellingMerchant**
As per patron reward. Adds a modified Noble Cyborg as a fluff for myself. 

Sprites already seen by Neca and were well received. If you need an example of the sprites before merging, shoot me a PM on discord. 

Here is an example of one.
noblehonkengineering

### CODE REVIEW

**Comment by MarsM0nd** [comment]
Didn't know that borgs had a horror module. I don't want to run into that borg in maintenance.

**Comment by SamHPurp** [comment]
A really cool HONK Mech fluff sprite.

Oh.

**Comment by Spacemanspark** [comment]
What the fuck

**Comment by Lady-Luck** [comment]
honk

**Comment by taukausanake** [comment]
A perfect representation for what a clown truly stands for. Sheer terror. Clown modules for cyborgs when? It would be amazing to have something else to abuse than another flesh being

**Comment by jughu** [comment]
!!FUN!! module if so traitor only gives borg a whole clowning arsenal

**Comment by Twinmold93** [comment]
This is... Absolutely... Fucking horrifying. Also, honestly, doesn't seem like something that 'should' be default to the different borg types. I can see that as a service borg, but not really anything else. Just my opinion.

**Comment by TravellingMerchant** [comment]
Just to clarify,  this is for me only.  It's not a public item. All it is,  is the dmi for my patron reward.

**Comment by Twinmold93** [comment]
I'm aware. I'm merely saying... It's horrifying to see a clown mask on a security mech that has an opening and closing gapping mouth.

**Comment by TravellingMerchant** [comment]
Exactly.  Time to arrest some new best friends!

**Comment by Twinmold93** [comment]
If I ever see that, I will run... And if you come after me, I will take you down.

**Comment by TravellingMerchant** [comment]
If only I could play carnival music..

**Comment by SigholtStarsong** [comment]
I'm with Twinmold on this one. This is an abomination that will result in your destruction.

**Comment by Fox-McCloud** [comment]
@FreeStylaLT @Necaladun

**Comment by Necaladun** [comment]
This is a fantastic sprite, and terrifying, but I don't think it's suitable for a borg.

Maybe a honk mech or laughter demon, but this is not something people will look at and see a borg. I can already see people opening fire on it and I can't blame them. The mouth is a big part of that, it's size covers up most of borgyness of it, and the movement is very eye catching. Maaaybe as a service borg or if honk borgs existed (and they should).

So I'm really sorry but I have to give this a 👎  on those reasons.

**Comment by TravellingMerchant** [comment]
@Necaladun In the same way that theres a custom borg that looks exactly like a human?

**Comment by SamHPurp** [comment]
Too snowflakey

**Comment by TravellingMerchant** [comment]
All fluff items are snowflakey.

**Comment by FreeStylaLT** [comment]
To my knowledge, that borg skin has been in the code since we branched off from BestRP. It wasn't added as a fluff skin for a player due to donating at the time. I may be wrong, but the player is an ex-Admin who hasn't been online for.. well, years - three or more, at least. 

I really wouldn't use that as an example of a precedent, as the current Heads of Staff, Neca included, had no say on that going in. Like I said, it seems to just been ported over and is a legacy leftover, along with some other fluff items, like lighters, jumpsuits, etc you can find among older fluff files in the code, meant for players that don't exist or have never played here.

As for the sprite, my concerns are mirrored by Neca, especially concerning the mouth's animation.

**Comment by Birdtalon** [comment]
While I think you're fantastically talented this just seems a bit too "memey" for my liking is all.

**Comment by Fox-McCloud** [comment]
Closing due to unanimous rejection by headmins.

**Pull request closed without merging**
