### PR TITLE
Mining Outpost Ore Redemption Update!

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
Updates the Mining Outpost to include the Ore Redemption Machine.

ss 2015-08-19 at 09 11 04

ss 2015-08-19 at 09 11 18

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Trying to remove a file from being commited.

**Comment by Ultimate-Chimera** [comment]
Done.

**Comment by Markolie** [comment]
This also seems to modify sprites - is that intentional?

You'll have to re-do the PR by the way - 11 commits for a map change is too much.

**Comment by Ultimate-Chimera** [comment]
I have fixed the sprite thingy, I forgot that I had a modified dmi in the thing but I updated it to the normal one to remove it.

**Comment by Ultimate-Chimera** [comment]
By the way, how do I re-do the PR? I closed it but it did not say I have commits ready to merge again.

**Comment by Ultimate-Chimera** [comment]
Markolie? I need help!

**Comment by Spacemanspark** [comment]
You done fucked up.

**Comment by Ultimate-Chimera** [comment]
S.O.S

**Comment by Ultimate-Chimera** [comment]
How does it look though, Spark? First time mapping.

**Comment by Markolie** [comment]
Eh, it's a bit difficult if you don't know GIt. You'll have to squash the commits into one. Can't really explain as I'm on mobile, try Googling it and see if you can work it out.

**Comment by Ultimate-Chimera** [comment]
Could I try closing this, making a change to the map thingy and see if it gives me the option to commit again? Because I forgot a arrow tile thingy beside the disposals thingy...

**Comment by Ultimate-Chimera** [comment]
Not commit, I mean make a pull request.

**Comment by Ultimate-Chimera** [comment]
git rebase -i?

**Comment by Markolie** [comment]
That's the one IIRC - I can assist more tomorrow.

**Comment by Ultimate-Chimera** [comment]
Crap, it does not work! Help! C:\Users\REDACTED\AppData\Local\GitHub\PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad\bin\rebase.exe: unknown option -- i

**Comment by Ultimate-Chimera** [comment]
Can you close this please?

**Comment by Ultimate-Chimera** [comment]
This is too confusing, I just wanna write another PR.

**Comment by Ultimate-Chimera** [comment]
Allow me to try and figure this out.

**Comment by Earthdivine** [comment]
While the old furnace system did need to go, this is a lot of open space not really being used for anything and the windows compound that empty look it has now, making it look bad.

Once you get an idea of what to do, I would recommend remaking it and try to make it less empty.

**Comment by Ultimate-Chimera** [comment]
Sure, I can make it less empty looking, want me to add a waiting room of the sorts? Like add a few chairs and tables? Maybe a few posters?

**Comment by Ultimate-Chimera** [comment]
Or a... Couch! There's only one in the entire map so...

**Comment by Ultimate-Chimera** [comment]
This just made it worse! I can not squash the commits! Help me! :(

**Comment by Ultimate-Chimera** [comment]
Can this just be closed so I can make a new PR? This is annoying!

**Pull request closed without merging**
