### PR TITLE
Pixel-coords laserpointer

### PR DESCRIPTION
**Pull request by tigercat2000**
Was originally going to also contain the kitchen spike stuff, turned out too difficult to implement.
tgstation/-tg-station#11994

~~Shamelessly stolen~~ original PR gif:
can'tbebotheredmakingmyown

The gif sums it up pretty much, laser pointers now appear where you click.

### CODE REVIEW

**Comment by theColdflame** [comment]
does this impact use as a weapon, out of interest?

**Comment by tigercat2000** [comment]
@theColdflame Nah, it just controls the pixel offset of the image generated, actual calculations are done before that.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by bustygoku** [comment]
>Paradise mirror PRs end up getting merged before PRs on /tg/

Why don't I just code for you guys instead, honestly?

**Pull request merged**
