### PR TITLE
Grey Blueshield Uniform fixed

### PR DESCRIPTION
**Pull request by StreakyHaddock**
Fix for #8592 which fixes the horrendous translation issues. Also, since I've actually tested the sprite IN SERVER now, 

Thanks to FreeStylaLT for being my Github Sherpa when I somehow created six branches that merged into themselves and MarcellusPye for being a helpless witness to the carnage.

greyblueshield

Tested it, actually works, thank fuck. It's not a perfect sprite, but it's functional.

### CODE REVIEW

**Comment by MarcellusPye** [comment]
THE NIGHTMARES! BURN IT! BURN IT ALL!

**Comment by Shadeykins** [comment]
Brings new meaning to the term "turtleneck"

**Comment by FreeStylaLT** [comment]
img

**Comment by Necaladun** [comment]
<3 LGTM :+1:

**Comment by StreakyHaddock** [comment]
Closing this since it's packaged in with #8635 which is a bigger commit

**Pull request closed without merging**
