### PR TITLE
The Ice Age (for cryodorms at least)

### PR DESCRIPTION
**Pull request by TheDZD**
After repeated complaints about this from some admins, I decided to send this feature to the cooler. Players that used to use this as a respawn mechanic will now have to chill in deadchat like everyone else.

:cl:
del: Cryodorms will no longer kick you to lobby if you have logged off when they despawn your body, they will now always ghost you.
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
my issue with cryo..is people cryo ghosting for the specific reason of waiting for antag pops, or doing this at round start..i can understand if someone does this cuase omg irl...but otherwise.

**Comment by Tastyfish** [comment]
Hopefully this will cause people to cool it on abusing cryo.

**Comment by Twinmold93** [comment]
Definitely a good thing, too, as people who cryo/ghost at round start and would get respawned may be able to find out what/who the antags are from deadchat. Also, as Aurora said, plus added to, people not getting antag going to cryo, (possibly respawning and then hit observe?) and going for a chance at mid-round antags.

**Comment by Spacemanspark** [comment]
Actually, you had to log off after entering the pod for the respawn to work, Twinmold.
That said, there were quite a few other ways to abuse it.

**Comment by Magikarpet** [comment]
I'm happy this is being removed, but it might be annoying if your co-workers are cryo happy and toss you in after a short interruption.

**Comment by tigercat2000** [comment]
do not like, i would rather this is extended to take a while rather than "kek no you're not getting back in the game"
what is the point of cryodorms over suicide otherwise

**Comment by Spacemanspark** [comment]
One gives back a jobslot and the other doesn't.

**Comment by Fox-McCloud** [comment]
:+1: 

Needed to happen.

**Pull request merged**
