### PR TITLE
Adds hydrocodone to medical borg hypospray

### PR DESCRIPTION
**Pull request by Landerlow**
Adds hydrocodone to the cyborg hypospray (medical)

🆑  
Add: Adds hydrocodone to the Cyborg Hypospray
/ 🆑

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Needs a changelog.

Also, little concerned hydrocone might be too strong (especially if the pain surgery goes through), though you don't really have a ton of other options for painkillers.

Sal acid is the weakest of the pain killers, but also heals burns. Morphine is addictive but a good mid-ground for power. Tough to say which of the three is the ideal.

**Comment by Landerlow** [comment]
Ether can be abused. I think hydrocodone is fine. Making CL in a moment

**Comment by Birdtalon** [comment]
Hydrocodone seems a bit strong to me to add to all medborgs.

**Comment by Landerlow** [comment]
What alternatives do you have? And how can it be ' too strong ' ?  Just inject a mere 5u and you'll be fine. You could add ether, of course. I wouldn't mind ether either. Or there should be a new painkiller made. Can't very well perform surgeries as borg without painkiller. It also makes no sense that borgs wouldn't have painkillers when they do have some other chemicals.

**Comment by FalseIncarnate** [comment]
Painkillers are a very weird thing in our code currently. They reduce the traumatic_shock of the mob by a set amount. Hydrocodone reduces it by 200, Morphine by 50, and Sal Acid by 25. With the proposed pain surgery PR, hydrocodone reduces the failure chance due to pain to 3% (basically non-existent except for the unluckiest of people). Hydrocodone also has the interesting effect of pretty much suppressing any "pain" messages the patient would receive during surgery, plus has no downsides. It cannot be overdosed or cause an addiction, so there is no downside to loading a person up on it.

Morphine could be a reasonable midground, a borg can't just fill someone with it without paying attention due to the addiction possibility, yet it still reduces the shock a fair bit. Might want a maintainer to chime in on that

**Comment by Landerlow** [comment]
Hydrocodone might make it a bit too easy indeed in that case. Morphine could be abused too though, because of the overdose effect. On the other hand, players who don't play responsibly as synthetic, should get a jobban from that role. I think most of the people who play a medical borg have an intricate knowledge about surgery and medicine in general, so I  think you could trust them with morphine.

**Comment by Landerlow** [comment]
I could change it to morphine? It's also more realistic. The addiction afterwards (if a patient even gets addicted) can be cured in a sleeper.

**Comment by FalseIncarnate** [comment]
Again, would be best to get one of the maintainers to weigh in on which reagent to use.

**Comment by Crazylemon64** [comment]
Yeah morphine sounds like a good idea

**Comment by uraniummeltdown** [comment]
I don't really like the idea of giving borgs reagents like morphine or ether. It's not like medborgs are forced to stay in medbay and do medical stuff If a medborg is on Paladin and a traitor is running around killing people then they can easily walk up to the traitor, 1-click hypospray them, and unless the traitor powergamed coffee he's going to be forced to sleep. Morphine's addiction chance is also a problem.

**Comment by mrturkeytoe** [comment]
I would not suggest morphine. It's literally unusable in it's current state, it either metabolizes out in a couple seconds and addicts them or metabolizes out in a minute or two and still addicts them.

**Comment by Landerlow** [comment]
Morphine is perfectly usable. Addictions can be cured after surgery. As to medical borgs not doing medical jobs but validhunting, it's in the name. Validhunt / abuse it and you get a borgban. That goes for all modules.

By your logic, we should also remove surgical tools because you can kill someone fast with it, same for engineering borgs' equipment.

**Comment by uraniummeltdown** [comment]
@Landerlow Why would you get a borgban? If you're on Paladin or Robocop and there is a madman killing people, why can't you morphine them? It doesn't go against borg laws. Engineering borgs CAN in fact kill people if it doesn't go against their laws.

**Comment by Birdtalon** [comment]
The PR should be judged based on the merits and detractors of adding the feature, not judged by a prevalent behaviour unrelated to the code.

**Comment by Fox-McCloud** [comment]
Due to the rather significant combat potential of morphine, allied with an instant injection system, we would rather this add hydrocodone instead.

**Comment by Landerlow** [comment]
Hydrocodone was my initial thought too. Changing it back to hydrocodone.

**Comment by Landerlow** [comment]
Done

**Comment by Hylocereus** [comment]
Would it perhaps be possible to add a new reagent that's weaker than traditional hydrocodone or has downsides? While morphine in a hypo is indeed way too abuseable and not entirely efficient, I kind of feel like hydrocodone is TOO efficient for borgs to have a limitless, 1-click supply of and it takes away a job from chemists that isn't pump out 90820934093 meds in 10 minutes and twiddle your thumbs for the rest of the round.

Synthetic Hydrocodone or something, stops working and deals small amounts of oxyloss damage on overdose, suppresses pain better than morphine, but worse than proper hydrocodone. That way you can't just load someone up with it, but rather than being directly abusable in that it can debilitate somebody it's just annoying and doesn't work when spammed.

**Pull request merged**
