### PR TITLE
Deletes Xenobio SIT docking port

### PR DESCRIPTION
**Pull request by Kyep**
Currently, Xenobio looks like this:
xenobio_current

This is all well and good, except, when the Syndicate Infiltration Team (SIT) shuttle docks to the east of it, the windows ensure that the shuttle is ALWAYS spotted by any xenobiologist:
xenobio_sit_dock

~~This PR moves the two windows from the bottom right to the top left. The SIT shuttle can now dock in scimaint without being seen by xenobiologists every single time.~~

This PR deletes that docking port, so that the SIT shuttle can no longer dock there. It still has on-station docking ports at arrivals maint, and eng maint. It simply loses one of its three possible docking ports, as docking there tends to get the SIT instantly seen/busted by Xenobiologists.

🆑 Kyep
tweak: SIT shuttle can no longer dock in scimaint.
/🆑

### CODE REVIEW

**Comment by granodd** [comment]
I'm not a fan of this. This removes the ability for savvy xenobiologists to make a killzone for slimes with the window and help automate it to be less tedious. If the windows were moved to somewhere where they couldn't see the shuttle, but still allow for this slime-kill box, then I'd not mind.

**Comment by Kyep** [comment]
This was requested by @Shadeykins due to concerns about the SIT shuttle being easy to spot.

As to the killzone for slimes, don't you already have a killzone? You can use the airlock between any two pens for a killzone. A few sprays of an extinguisher in an enclosed space kills any slime.

I could always simple move the windows to the NW side of xenobio. That would allow xenobio and maint to see each other, though.

**Comment by tigercat2000** [comment]
I'm not sure that this is the best solution for something that could probably be resolved by just moving the SIT shuttle landing location.

**Comment by taukausanake** [comment]
I'd just remove the windows. I don't like them in a part of the station that is supposed to be a containment chamber filled with dangerous creatures. Sure they die in space but that's not really the point and really isn't an argument if you get xenos

**Comment by Anticept** [comment]
Fire extinguishers annoy the ever-loving hell out of everyone in science. Unless we get a better way to kill them, I don't want to see the windows removed completely.

**Comment by Fox-McCloud** [comment]
Not a good idea; when there's a problem, you want to change the absolutely minimum you can do resolve the issue, and typically when you introduce something new, and it creates a problem, it's better to change the new thing added rather than what existed prior---with exceptions of course.

It'd be better to move the shuttle or alter where it docks than to change the window.

**Comment by Kyep** [comment]
Yeah, I thought about that, but there aren't many places the SIT shuttle can dock whilst having any degree of stealth. Most of the ones that do exist are outside of the station, too. This is the only one within the station's walls. (ie: the only one that won't be found by a mechanic in a pod)

**Comment by Jountax** [comment]
If we just made the one cell that's off by itself in the top right of xeno a freezer cell you could comfortably remove the windows entirely. Scientists can then just plop slimes into the cell to kill them and don't have to intentionally breach the station every shift to build a makeshift one.

**Comment by taukausanake** [comment]
@Jountax I never thought of setting up a cell as a freezer room, but I guess only because of the work that would be needed and wouldn't be worth it in the long run. I'd go for a pipe setup at most for one of the cells, that top one specifically, and maybe a machine frame. Science doesn't need to have everything handed to them for free, not when they can make it all whenever they want

**Comment by Allfd** [comment]
@Kyep  It is not entirely cosmetic, it allows Xeno Bio to create a kill chamber for slimes, since they don't ever have to be interacted with directly, it lets you use consoles to go through the entire process without ever taming the slimes or exposing yourself to risk from not taming them.

When I saw the PR title I assumed it was to fix that issue.

**Comment by Kyep** [comment]
The window still allows a kill chamber in its new location. Moving it shouldn't make any difference for Xenobio.

**Comment by Draconic-saint** [comment]
I wish you didn't buckle to the xenobiologists for taking away their cheesy way of killing slimes, but otherwise it's good that the SIT now can enter without having the chance to be instantly spotted

**Comment by Fox-McCloud** [comment]
>Prioritizing old stuff over new results in stagnation, as old things constrain the design space for new things.

Ignoring old stuff for the sake of adding in new designs results in old strategies, paradigms, and designs getting overwritten for the sake of "progress". Stagnation happens when old features are never changed or never updated.

This isn't a case of an old design just not being updated; this is a case of a new design completing destroying an older one---worse yet, this new change has absolutely *nothing* to do with the old one.

**Comment by EvadableMoxie** [comment]
Moving the window there isn't just cosmetic and not just because of a kill chamber. Having it there means you can bypass the xenobiology airlock and science department doors via maintenance with a quick space jaunt.  It means people who want to break into Xenobio will be making breaches and destroying the Xenobiologist's kill chamber, which I expect will be highly annoying.

What about moving it up to where the intercom is, just below the top right pen? Would that be far enough away to make the SIT shuttle out of sight? You're also going to have to remap the area of Xenobio, otherwise the shuttle will still be easily spotted by scrolling the console through the wall.

**Comment by Kyep** [comment]
Update: this PR has been changed. It no longer alters Xenobio in any way. Now, it simply deletes the SIT docking port from SciMaint, so the SIT shuttle can no longer dock there. While docking within the station was a neat idea, in practice, it usually results in the SIT shuttle being spotted instantly by Xenobiologists. Since apparently its impossible to move a window in Xenobio, the PR has been updated to simply remove the docking port there instead.

**Comment by Spacemanspark** [comment]
Honestly those windows should be removed too.

**Comment by Anticept** [comment]
Only if there's an alternative to being annoying with fire extinguishers.

**Comment by Kyep** [comment]
This PR will no longer edit xenobio.
It simply removes the docking port. That is it.
Given the amount of hassle it was to simply move a window, I'm unwilling to make any changes to Xenobio now.

**Comment by tigercat2000** [comment]
Well that works I guess

**Pull request merged**
