### PR TITLE
Updates Mining Outpost to have Ore Redemption Machine and add a break room

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
Makes the mining outpost have the ore redemption machine to make miner's lives easier and adds a cool alternative to the dorms area. :) And I finally got it fixed!

ss 2015-08-20 at 12 22 31

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
How did it fail? Can somebody tell me what happened?

**Comment by tigercat2000** [comment]
@Ultimate-Chimera 
`The command "(! grep 'step_[xy]' _maps/map_files/**/*.dmm)" exited with 1.`

The step_x/step_y check failed; you need to open the map files in a text editor and mass replace 'step_x' and 'step_y' with 'pixel_x' and 'pixel_y'

**Comment by Ultimate-Chimera** [comment]
Which map files? z5.dmm? I am searching for the lines and can not find them.

**Comment by Ultimate-Chimera** [comment]
Nevermind.

**Comment by Ultimate-Chimera** [comment]
All fixed, ready to merge or change anything.

**Comment by Ultimate-Chimera** [comment]
Actually, I might move that holopad somewhere else, one second.

**Comment by Ultimate-Chimera** [comment]
Done.

**Comment by TheDZD** [comment]
I don't really see much of a point in having an ore redemption machine inside of the mining processing area, considering the point of it is that people are supposed to be able to come and grab minerals from it if they want, assuming they have access.

**Comment by Ultimate-Chimera** [comment]
Well, they could fill up crates and RCS them, etc.

**Comment by Fox-McCloud** [comment]
Don't like the idea of the ore redemption machine being there. It discourages interaction between miners and the crew (even if it's only their own department), and it's inevitably going to mean science gets its materials less reliably. 

Aside from that, way way too much open space.

**Comment by KasparoVy** [comment]
Doing this makes the entire belt/pipe system on the asteroid null and void, and it's extremely useful if only for transport. Why fix what isn't broken?

**Comment by Ultimate-Chimera** [comment]
Actually, I only removed the belts for the old smelting system, all other pipes are still there.

**Comment by Alex6511** [comment]
:-1: from me, the ore redemption machine is where it is for a reason, so people who need the materials can go up to it and get them.

**Comment by Ultimate-Chimera** [comment]
There are many points here you are missing 1. This is an easy way for miners to get points without going back to the station all the time 2. It can be used to make coins in that money machine 3. There is an RCS on the table YOU CAN TELEPORT resources to R&D via telescience so this is not pointless at all.

**Comment by Markolie** [comment]
I'm in agreement with the reasoning above. :-1: from me.

**Comment by Ultimate-Chimera** [comment]
Fine, when I get back home I'll just make it a totally different room.

**Pull request closed without merging**
