### PR TITLE
Flamethrower tweaks

### PR DESCRIPTION
**Pull request by LynxSolstice**
## What Does This PR Do
It excludes the tiles adjacent to the user when it spawns the fuel mix from the flamethrower, thus making it impossible to torch your face immediately unless you walk into it, or stand still.

## Why It's Good For The Game
This is pretty much just a QoL change for flamethrower users so it acts more like a proper flamethrower and doesn't immediately burn your face off.

## Testing
I opened it in a local server and tested the improved flamethrower, it whacks people within 1 tile of yourself no matter your intent, and it does not spawn the fuel if you do not click atleast 2 tiles away, thus it works properly.

:cl:LynxSolstice
tweak: Flamethrowers will now only spawn the heated plasma/gas if you click further away than one tile from yourself, similar to how guns work.
/:cl:

### CODE REVIEW

**Comment by Tokorizo** [comment]
Any chance we can get a video of the new changes?

**Comment by LynxSolstice** [comment]
> 

Yes, I'll get it recorded for reference

**Comment by LynxSolstice** [comment]
https://user-images.githubusercontent.com/112824777/189747626-5506f196-741d-4a28-b8d6-8ce0062f6977.mp4


https://user-images.githubusercontent.com/112824777/189747680-b8640de6-4b11-4df4-851e-b4f1a7fe53ef.mp4

**Review by LynxSolstice — COMMENTED** [review]
**revert this**

**Review by LynxSolstice — COMMENTED** [review]
Don't include this

**Review by LynxSolstice — COMMENTED** [review]
This is the proper commit

**Comment by LynxSolstice** [comment]
> Having an entire tile gap between the flame and the user doesn't seem like a good change to me. From my own usage of a flamethrower I found it hard to actually set myself on fire unless I stood in place, where plasma spread, or ran into the flames.

It's to more accurately be a flamethrower, throwing the flame in front, rather than just dumping it in front of you, in your face,
Plus in my personal experience with the current flamethrower, sometimes the plasma spreads to the user tile near instantly and you can't avoid immolation

**Comment by LynxSolstice** [comment]
Why can't I just, fix the commits??

**Comment by LynxSolstice** [comment]
Finally fixed the commit issue.

**Comment by AffectedArc07** [comment]
Not really sold on this. The whole point of a flamethrower is it being a chaotic weapon, not something you want surgical precision with. Most operators are in atmos hardsuits anyway, and its not exactly quiet. If you have one of these, you are wanting maximum collateral damage and protecting yourself as such, and given how fire can spread, it doesnt make sense to have a clear region.

Also given most people run-n-gun with these, it wouldnt solve much because people would end up walking into their own fire anyway.

---

Not in favour.

**Comment by hal9000PR** [comment]
this PR has 2 objections and nobody in favour after 20 days. closing

**Pull request closed without merging**
