### PR TITLE
Nerfs Neurotoxin

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Nerfs Neurotoxin.

This really should have been done a long time ago. This is nothing more than a nigh-uncounterable infinitely reproducible instant knock-out chemical; it outclasses and generally outperforms even the ultra-high end traitor-only knockout chems.

Neurotoxin now stuns after 55 cycles instead of being an instantaneous knockout.

:cl: Fox McCloud
tweak: Neurotoxin knockout has a very long delay as opposed to being instant
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
I hate chems, and I still think thats too long of a delay.

**Comment by Fox-McCloud** [comment]
Ether knocks out after 36 cycles, and it's intentionally a purely knockout chemical--this is meant to be a drink---it also gets you drunk incredibly rapidly because of its very very high alcohol content. It's a bit on the high side, but the drug purges at a regular rate *and* it has other deleterious effects.

Being a quick knockout+mess you up chemical, in one, isn't desirable, for balance, at all; we had that drug once--it was called Chloral Hydrate.

**Comment by Lady-Luck** [comment]
Neuro-toxin is a drink, Neurotoxin is a chemical.

This PR is addressing Neuro-toxin.

I'm going to have to agree with SamHPurp, the nerf hammer is being swung way too hard.

**Comment by Vivalas** [comment]
I thought Neurotoxin drink just knocked you down? I think the actual Neurotoxin chemical should be buffed a little and the drink nerfed, honestly it's alcohol, not a chemical designed to knock you out, and Ether should be clearly better by a wide margin than an alcoholic drink.

**Comment by Lady-Luck** [comment]
>Ether should be clearly better by a wide margin than an alcoholic drink.

Ether is a component to the drink. If it's worse than ether than it's going to lose all relevance.

**Comment by Kyep** [comment]
I love neurotoxin. It is one of the most useful chems.
Unfortunately, Fox is right that it isn't remotely balanced. Something anyone can make with a bar drink and 30 seconds in chemistry shouldn't be stronger than the antag-only chems that are restricted and expensive.

However, I also think that this is a bad way to nerf it. If you make it worse than ether, which half the station has access to, yet still more difficult to make... then nobody will use it. Ever. It is rather like just removing it from the game entirely, but way less clean.

IMHO, there are two better options here:
A) Rebalance neurotoxin to be somewhere between ether and the traitor chems in power. Definitely not worse than ether.
B) Rebalance neurotoxin to have no stunning effect at all (or at least, only a temporary stun regardless of volume)... but buff ether, and for that matter, consider buffing the traitor chems too. Right now, both ether and the traitor chems are quite weak, relative to the stuff anyone with access to a chem set can make.

**Comment by Kyep** [comment]
Also, we shouldn't compare other chems to ether. IMHO, ether is a ridiculously weak chem. Only med/sci have access to it, medical typically via syringe or non-rapid syringe gun. If you give someone a syringe of it, it takes over a minute to knock them out, and the fact you're trying to tranq them is obvious well before then. Due to it taking AGES to take effect, and being highly obvious, and being somewhat restricted in how it can be delivered, ether is really only useful as a knockout pill for vox undergoing surgery. It is useless as an abduction chem.

What would be a better comparison? The stunprod. Unlike ether syringes, EVERYONE can build a stunprod using commonly found parts in maintenance. It isn't restricted to med/sci. Like neurotoxin, and unlike ether, it stuns INSTANTLY, with NO WARNING. You can keep it armed in your pack at all times and just whip it out to stun someone whenever you please.

Yes, neurotoxin guns are a bit stronger than a stunprod - but they're also harder to obtain. You need a bar drink, a syringe gun AND chem access to make one. Versus ANYONE being able to construct a stunprod with commonly found items in maint. 

Neurotoxin is stronger than the stunprod, but also harder to obtain.
It is ridiculously stronger than ether, but that isn't a problem with neurotoxin - that is a problem with ether being silly-weak in comparison to stuff anyone can find/make in maint.

**Comment by theColdflame** [comment]
a bar drink outperforming the actual stun chems is incredibly retarded

**Comment by Lady-Luck** [comment]
>a bar drink outperforming the actual stun chems is incredibly retarded

It's made with 'actual chems' so I don't really understand this criticism.

**Comment by Doukhan** [comment]
It's a bit OP considering it's availability and mass producability, it should still be a valid option though and this'd make it objectively inferior to everything else.
And the name is appropriate I think, Neuro-Toxin/Neurotoxin is great for fucking with people and is a versatility of it's own.

**Comment by AndriiYukhymchak** [comment]
@Lady-Luck you dilute ether with alcohol, so logic-wise it is fine to have weaker stun than ether
It should have other effects... maybe your language becomes completely unreadable? not just slurring but not yet silence. Everyone (who has metaknowledge about this behavior) will know, that you are drugged. But you won't be able to say where or who in understandable way

**Comment by DesolateG** [comment]
You aren't diluting the ether, it's being added to an already extremely potent mix of alchohols.

**Comment by Davdichan** [comment]
@theColdflame To be entirely fair the drink is half ether to begin with, and half a fictional drink so potent if you have more than two you can't remember your name.

Difference being that Ether full sleeps you while Neuro-Toxin just floors you and makes you stutter a lot with brief moments of blackout.

**Comment by Fox-McCloud** [comment]
Adjusted it drink so it kicks in sooner (36 cycles); at 12 cycles or greater it makes you dizzy.

**Comment by Bigtimetripod** [comment]
Oke... This bothers me... Yes Neuro-tox is kinda OP, but its the only knock-out chem you can relay on. All other chems take atleast 15-30 seconds to have effect. In a fight or trying to capture someone that time is enough to do all kinds of things. This even gives enough time for the victim to retaliate and kill you if robust enough. What help is a knock-out drug that just get you killed? I usually use Neuro-tox for kinda as a staged knock-out mix. Have Neuro-tox knock-out and give enough time for some other chemical to take effect. I would say to leave it since its the only chem that even if smart enough, a civi can make. Yes it hard to make it as a civi and bot get caught, but its possible. For Scientist or medical doctor is easy. 

Now for the other topic, poison bottles. Lets just start by sayin that not every traitor gets em. Poision bottle is only obtainable by Research Director , Chief Medical Officer, Medical Doctor, Psychiatrist, Paramedic, Virologist, Bartender. Even if you try and get the chemical you want. Its REALLY REALLY RNG. You can get a multiple bottles of the same stuff, cost is too high and for 2 tc you can get two clips of ammo for the pistol. Maybe make the poison bottle for everyone and make a subcategory when buying the bottle. 

Knock-out chems 2-3 TC
Damage chems 3-5 TC
Lethal chems 5-8 TC

Have something like Pancuronium and Sodium Thiopental as knock-outs. Damage chems maybe Sarin and Coniine. Lethal chems Initropidril, Prions or nanomachines. The poison bottles are the rarest to see traitor take just because of their high cost and randomness. They are not worth it. Since they are also in limited supply, there is no point to take em. 4 bottles of random or e-mag with unlimited and much more uses? 3 bottles or gun with 2 mags? 6 bottles of random and maybe same useless stuff for a crossbow with unlimited stuns and guaranteed knock-down pluss toxin damage. 

Personal opinion? Chems are being hugboxxed... Still havent got over that Phlogiston doesnt ignite people anymore and now this... Whats next? Omnizine nerf? Oh wait... it already was... SGS gets removed? Perfluorodecalin no longer mutes? Why not gives Stun batons stun delay? Stun baton + Bluespace battery = Stunlock forever basically

**Comment by Vivalas** [comment]
I actually didn't know ether was an ingredient in Neurotoxin, my bad.

**Comment by Kyep** [comment]
Ether is a useless chem, compared to other, non-chem stunning options (like stunprods, tasers, even a tele baton is better because it is instant).
Traitor chems are borderline useless too, because they're random, and also not much stronger than chems you can make. Last time I bought poison bottles, I ended up with bottles of Sarin and other chems I could make myself anyway. I think I got one traitor-only chem, and looking at its stats, it wasn't better than the stuff I could make myself. Poison bottles are a total waste of TC.
 
If Neurotoxin is nerfed to the point it no longer knocks out the target, and quickly (ie: within a few seconds) then it too will become a useless chem.

It won't stop people running around with stun weapons. They'll just switch to the stunprod, which is easier/faster to make, doesn't require you to interact with anyone to get it, doesn't require ammo, and is less likely to get you labeled as an antag just for having one.

**Comment by Lady-Luck** [comment]
Kyep is quite right. Neuro-toxin in its current state is definitely overpowered compared to everything else, but every other chem meant to do its job is woefully underpowered.

It wouldn't feel right to correct this by swinging the nerf hammer at it so hard that there's no nonlethal chem solutions left. A larger balance pass should be made, and I think Neuro-toxin should be left alone until then.

But seriously, either Neurotoxin or Neuro-toxin needs to be renamed.

**Comment by Doukhan** [comment]
@Lady-Luck If someone can't tell then difference between them they kinda deserve to drink the Neuro-Toxin.

**Comment by Mijhead** [comment]
ich bin tot, nerf bitte

**Comment by Davdichan** [comment]
Close PR. Make other chemistry dangerous to piss off again.

**Comment by Fox-McCloud** [comment]
>Make other chemistry dangerous to piss off again

Because chemistry isn't horrifyingly overpowered enough.

Looks like the powergamers win this one.

**Comment by Lady-Luck** [comment]
>Looks like the powergamers win this one.

You know.. we pretty much ALL agreed that neuro-toxin does need to be nerfed. The problem was twofold: The nerf is too severe, and every other nonlethal chemical is the shits.

This sort of dismissiveness to a lot of well thought out feedback is sad to see.

**Comment by Aurorablade** [comment]
> Adjusted it drink so it kicks in sooner (36 cycles); at 12 cycles or greater it makes you dizzy.

That was a well enough compromise. @Fox-McCloud this did not need to be closed. Please reconsider reopening it.

**Comment by Lady-Luck** [comment]
>That was a well enough compromise. @Fox-McCloud this did not need to be closed. Please reconsider reopening it.

It wasn't though.

**Comment by Aurorablade** [comment]
he put it as the same cycles at ether. Thats good enough.

**Comment by Lady-Luck** [comment]
>he put it as the same cycles at ether. Thats good enough.

I'm not gonna reiterate all the feedback. All the nonlethal chems are terrible except for one which is absurdly good. The solution should not be to make the absurdly good one also terrible. A more balanced approach is needed.

**Comment by Aurorablade** [comment]
you use that word but i don't think you understand what it means.

**Comment by Lady-Luck** [comment]
Which

**Comment by Aurorablade** [comment]
the word 'balance'

**Comment by Lady-Luck** [comment]
Ok, since you're being extremely condescending I diagrammed it for you.

http://i.imgur.com/2ELGCpi.png

**Comment by Vivalas** [comment]
>Looks like the powergamers win this one.

This honestly makes me wonder if this isn't some kneejerk reaction to something.

Comments like this are half the reason why I rant about maintainer conduct.
Lack of feedback is the other half.

Looks like you nailed those both square on the head.

**Comment by Davdichan** [comment]
@Vivalas When coders/maintainers are targeting the few viable stun options to most crew (stunprods and neuro-toxin) it really comes down to some kneejerk reaction

**Pull request closed without merging**
