### PR TITLE
Adds Flagellant Robe Sprite

### PR DESCRIPTION
**Pull request by Drakeven**
##What Does This PR Do

Adds a sprite for the flagellant's robes, which previously used the berzerker hard suit.

##Why It's Good For The Game

It gives a unique sprite to the flagellant's robe, which is much more fitting than the hard suit.

##Images of changes

https://imgur.com/a/wZW0ho8
(Sorry for the link, GitHub was having issues with me uploading image files)
Changelog

This is a re-add of the last PR I did about this: https://github.com/ParadiseSS13/Paradise/pull/12635  and had to be re-made because I lost the original repo. 

🆑
imageadd: Unique sprite for Flagellent's robe.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
How does this look on greys? :alien:

**Comment by Drakeven** [comment]
Here's how it looks- 
Human
https://gyazo.com/8fb82f4c6fda49c2b704d155bd12de2b 
https://gyazo.com/99825eeae200d3c4638f839af36ae3c5 
https://gyazo.com/53fdd08774c3367c924ea4852d75e675

Drask- 
https://gyazo.com/ec7017b8fdbace2ff8e88aa0cc8b3c67 
https://gyazo.com/1ad6f3a8fee9aebb6b177089f5a68263  
https://gyazo.com/a4b5460335d7b91779ba55e5c9bd0e65

Vox- 
https://gyazo.com/167d5bc7507f9da4dfe0d7ca6f0601d8 
https://gyazo.com/5018e259653bcc3ea7862fb4cadb6535 
https://gyazo.com/4b841ad11e1c644734939f4123971d3a 

And Greys look... Fine in human. I think. Anyway, shouldn't have any more conflicts and is TESTED AND READY TO MERGE! :D

**Comment by Spacemanspark** [comment]
If you don't add an Ian variant I'm downvoting this PR

**Comment by Drakeven** [comment]
Oh god... Ian code... 💦 I'LL SEE if I can, perhaps if this PR gets accepted first.

**Comment by Fox-McCloud** [comment]
Please fix conflicts.

**Comment by Drakeven** [comment]
Nope. Welp, back to the drawing board.

**Comment by AffectedArc07** [comment]
This can be merge once its deconflicted.

**Comment by datlo** [comment]
These sprites have been added as part of the Blood Cult rework with Drakeven's permission.

**Comment by Drakeven** [comment]
I'm a lazy nerd who gave up, forgive me code gods. This PR should work! https://github.com/ParadiseSS13/Paradise/pull/14183

**Comment by Drakeven** [comment]
I realised I can close this with a comment, so I shall do so now. https://github.com/ParadiseSS13/Paradise/pull/14183

**Pull request closed without merging**
