### PR TITLE
Increases nanomed restocking unit cost

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR increases cost of nanomed restock unit in cargo from 100 credits to 400

## Why It's Good For The Game

Having portable medbay with everything you need for 100 units sounds... powerful. We dont have all departments ordering nanomed just to have it(100 credits cmon) yet, but we better fix the price before it happens.

## Testing

Compiled

## Changelog
:cl:
tweak: Nanomed restock unit now costs 400 credits.
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
While, I could agree the vendor crate could use a cost increase to balance it out more, it doesn't need to cost over 6x its current cost and more than the majority of the gun crates do. Especially with the argument presented here for this PR being that departments will order and spam them for free healing supplies. In practice, the crate has been 100 credits for a really long time and you see cargo and *maybe* security order one every 10-30 rounds. I've only seen security with one like two or three times at most over the course of at-least 50 rounds. 

Cargo is the most frequent buyer of them and I can't say it's not exactly justified for them to buy one with mining or such.

Increasing the cost to 300 would be much more reasonable, I feel. Otherwise this is more or less just shooting medvendors in the foot and medbay as a whole. Medbay is often in a terrible state as it is in terms of chemistry not performing well/putting out medicine at all in favor of making drugs. This is partly a chemical mechanic issue but it's an issue medbay faces constantly nonetheless.

**Comment by HMBGERDO** [comment]
Security and Cargo should not order nanomeds for themselfs at all, same as cargo shouldnt build RnD console. Unless medbay is bombed and can no longer be used, this should be not allowed. Price only makes it harder to order it. 

I made price 650 with intent that no crewmember, that just arrived, could buy it by himself. You would need others money or to save your money during shift to order this. If medbay is fucked and it needs help, i honestly barely see them ordering nanomeds but even if so, i see no problem with cargo assisting them with funds same as other departments assist cargo when they order guns for biohazards.

**Review by DGamerL — APPROVED** [review]
Code LGTM

**Comment by Cress67** [comment]
> Security and Cargo should not order nanomeds for themselfs at all, same as cargo shouldnt build RnD console. Unless medbay is bombed and can no longer be used, this should be not allowed. Price only makes it harder to order it.
> 
> I made price 650 with intent that no crewmember, that just arrived, could buy it by himself. You would need others money or to save your money during shift to order this. If medbay is fucked and it needs help, i honestly barely see them ordering nanomeds but even if so, i see no problem with cargo assisting them with funds same as other departments assist cargo when they order guns for biohazards.

Man, Medbay routinely orders two or three of these per shift to refuel their NanoMeds because they have to keep going through all the basics medicine within due to Chemistry being non-present.
Like with the crate slowdown, this is shooting everyone in the foot because a handful of people do something that... doesn't hurt anyone else, in this case.

**Comment by HMBGERDO** [comment]
Alright, given that medbay account has 750cr +250cr every 30mins, price of 650cr would be too high. 
Reduced cost to 400cr

**Comment by matttheficus** [comment]
Medbay’s economy is kinda wack. Blood costs a SHIT ton to buy too. Given this would smack lowpop a bunch I can’t really support it.

Medbay is one of those areas that needs a BIT of unbalanced “help” to ensure players can keep being revived in lowpop/mass chaos without falling apart instantly. Someone would need to look at the macro levels of Medbay gameplay in all amounts of population to fix that I feel.

**Comment by HMBGERDO** [comment]
> Medbay’s economy is kinda wack. Blood costs a SHIT ton to buy too. Given this would smack lowpop a bunch I can’t really support it.
> 
> Medbay is one of those areas that needs a BIT of unbalanced “help” to ensure players can keep being revived in lowpop/mass chaos without falling apart instantly. Someone would need to look at the macro levels of Medbay gameplay in all amounts of population to fix that I feel.

Lets buff medbay account stats instead. It has the lowest payday and 750 credits from start, lets buff it instead

**Comment by Inferno1882** [comment]
400 is more reasonable, but I feel just putting this behind a MD approval would rectify the issues as well
or even changing most NanoMeds to a SmartFridge that allows Medbay (if they are performing well) to come by and resupply when needed.
That's out of scope of the PR, though.

**Review by Sirryan2002 — APPROVED** [review]
approved for code

**Comment by Komrad822** [comment]
We dont have an issue, preventative nerfing isnt something im comfortable with. People making psuedo departments is player behavior and we already handle this administratively with like another RND in maints etc.

**Comment by SteelSlayer** [comment]
This PR has failed the balance team vote with 4 against and 0 in favor. Here are the objection reasons:

**Member 1:** We dont have an issue, preventative nerfing isnt something im confortable with. People making psuedo departments is player behavior and we already handle this administratively with like another RND in maints etc.
**Member 2:** Medbay will need increased funds overall to validate this increase to me. MedVend restocks are a near necessity on LowPop rounds.
**Member 3:** Medbay's capabilities do not need to be picked away at even more. What does it add to the round to make it harder to refill necessities like this? I do not understand why this PR needs to exist.
**Member 4:** I agree that 100 credits is cheap and if this was a PR to make it closer to 300 then ide be for it. this just creates more issues

**Pull request closed without merging**
