### PR TITLE
(WIP) Procedural Maintenance Room Generation

### PR DESCRIPTION
**Pull request by monster860**
Basically, this PR strips down maintenance a bit, and then at roundstart, runs a ~~fancy~~ algorithm to generate more maintenance

Currently, this only generates the rooms, it doesn't generate the stuff *inside* the rooms.

Oh yeah, and it won't break metastation

### CODE REVIEW

**Comment by Aurorablade** [comment]
this mostly for mapping and space reasons..seems like a bad idea.

**Comment by Fruerlund** [comment]
Cut down maintence meta? yes yes.

**Comment by Necaladun** [comment]
In theory this is absolutely fucking amazing and I love it.

In practice, I have no idea how it will work.

**Comment by fludd12** [comment]
I absolutely love the idea, can't wait to see how it pans out. Will there be a mapping indicator that shows where generation might be, so additions to the station don't *kill everything*?

**Comment by monster860** [comment]
Yes, you mark places where it's okay to generate with /area/space/maintgen

**Comment by Necaladun** [comment]
How is it for performance when the server starts?

**Comment by monster860** [comment]
It takes a few seconds

**Comment by Fox-McCloud** [comment]
Big :-1: on this.

One of the main points of the primary map being static is that it allows players to know where things are and where to go from one location to another. Nooks and crannies can specifically be accounted for, checked, or utilized for antagging or specific building purposes. Every time you go into maintenance, it's going to be confusing and unaccounted for.

This completely destroys that---it additionally is going to make further additions to the map (bound to happen later) even more difficult---it's also going to look ugly as sin because of having little control over just what it'll look like.

Furthermore, it means that the the NanoUI map is never going to be trustworthy or accurate.


It sounds neat, in theory, but this is going to generate a lotttt more problems than its worth.

Randomized mapping is good for locations off station that are meant to be explored, dangerous, and largely not part of day-to-day traitoring/tactics/antics, but when it comes to the main station, the vast majority of things should be static and unchanging, *especially* layout and rooms.

Imagine if medical was in arrivals one day and in security the next? I realize it's not this extreme, but the principle is the same--it's just a bad precedent.

**Comment by monster860** [comment]
```
it additionally is going to make further additions to the map (bound to happen later) even more difficult
```

Sure, maybe you'll have to move some maintenance generation areas out of the way, but it shouldn't make future changes that difficult.

Besides, as it is, maintenance already looks like the engineers weren't exactly looking at their blueprints when they built the thing, considering all the 1x1 spaces.

**Comment by fludd12** [comment]
@Fox-McCloud The way I see it is, the general purpose of Maintenance is still maintained - a 'secret passage' of sorts that's unmonitored, that links most, if not all areas on station. Besides, the existence of areas that are always used for antagging makes things boring and predictable. And, for any areas that we want to maintain, we could just disable the generator for, such as the [Mankanshoku Back-Alley Surgery](https://dailyanimeart.files.wordpress.com/2014/01/kill-la-kill-wallpaper-1920x1080-by-asharl.jpg) in arrivals.

**Comment by Fox-McCloud** [comment]
@fludd12 

The whole point of the map being fixed is to allow areas to be used for designated purposes and allow for decision choices in paths taken. When you generate a map on the fly, this all goes away. It doesn't make it more useful for antags OR regular station crew because nothing is guaranteed or set. The hall could be blocked off, there may be no room at all, or there may be piss-poor locations to hide bodies---etc.

There's a plethora of problems that this will bring up, and quite frankly, it's not worth maintaining them in the long run, especially relying on it to be maintained by someone actively permabanned from the server.

**Comment by Lady-Luck** [comment]
>There's a plethora of problems that this will bring up, and quite frankly, it's not worth maintaining them in the long run, especially relying on it to be maintained by someone actively permabanned from the live-server.

You know, you have a good enough case to not need to rely on a low blow. Not very classy of you.

**Comment by IcyV** [comment]
I don't think pointing out that he's perma'd is a low blow in any sense. He can't be actively aware or know first-hand how it affects the rounds or plays out. It makes any kind of upkeep required by him very hard to do when it would be entirely reliant on feedback from other parties. It's not an attack, it's just a fact of the matter.

I think the idea of procedural maintenance could be interesting when applied in a conservative way. I'd like to see for certain sections of maint to always be the same, but this could spice up other more generic areas or generate more outwards. I have no idea on this when it comes to performance and such, just that the concept could potentially add for a lot more variety in a round.

**Comment by GeneralChaos81** [comment]
How aggressive is this? I'm with fox that it should not change the overall layout of maint...

BUT. Having certain sections which have randomized could be quite enjoyable. Like in the new engineering maint - those two new open areas. The bedrooms near that. Contents of the sealed medical room. Maint bar. The little viewing area near the space bridge.

**Comment by monster860** [comment]
Keep in mind, the main maintenance tunnels stay the same, and the algorithm
doesn't overwrite anything it shouldn't

**Comment by pazneria12** [comment]
Im all for this, Imagine assistants who get bored exploring maint instead of crowding the bar or doing illegal activities, or a traitor that finds a REALLY well hidden maint room that he uses as a base, or a lair of sorts that security can not find.

**Comment by GeneralChaos81** [comment]
Is it working enough that you could show us example pics?

**Comment by taukausanake** [comment]
I see this, I think of Metroid Fusion map. The one where you get a downloaded map of an area but there are a ton of secret tunnels that have either been closed off, forgotten, or carved by escaped creatures. This sounds like that and I like it. However, I don't think it should be applied to the main station. This should be merged, for sure. It's a great utility if it works and can be used on an experimental station, something secondary to Metastation too even. Maybe Paradise can even get its own personal station one day and use this

**Comment by Fox-McCloud** [comment]
Going to go ahead and close this. DZD and I are in agreement that the main station map really shouldn't be changed, except by players.

**Pull request closed without merging**
