### PR TITLE
Space Law/SOP/Legal SOP Roundstart Messages

### PR DESCRIPTION
**Pull request by TullyBurnalot**
Regardless, each job now receives a link to General SOP, as well as a link to their Department SOP on roundstart.

Security, Magistrate and IAAs also get links to Space Law and Legal SOP.

The end result is players receive a face full of links when they join the game, which should hopefully encourage at least some people to actually read up on stuff. It also kills off plausible deniability, as ignorance is even LESS of an excuse.

:cl:
add: Jobs receive links to SOP and their Department SOP at roundstart. Space Law and Legal SOP links added to Security members, Magistrate and IAAs
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
Why not make it a pop up window

**Comment by Aurorablade** [comment]
Wait that could get annoying nevermind

**Comment by TullyBurnalot** [comment]
It would also be immensely simpler to click that "X" button and remove said popup window.

**Comment by TullyBurnalot** [comment]
EDIT: Courtesy of @Krausus ,, the links are now actually embedded. Will probably resort to using single quotes if https://github.com/ParadiseSS13/Paradise/pull/6118 goes through.

**Comment by Fox-McCloud** [comment]
@Crazylemon64

**Comment by AndriiYukhymchak** [comment]
@TullyBurnalot what about "space law"? Or we assume everyone read it?

**Comment by Crazylemon64** [comment]
LGTM

**Pull request merged**
