### PR TITLE
Tape removes AI inbuilt Camera while Carded

### PR DESCRIPTION
**Pull request by Komrad822**
## What Does This PR Do
This PR makes it so when applying tape to a Carded AI, the built in camera no longer functions until that tape is removed OR its placed back into its Core.

On request by Qwerty, the carded AI can remove the tape after a 2 minute resist. If the card is moved in any way during this, it stops the removal of the tape. There is a notice for the AI that it is being removed and an audible tape removal sound effect for everyone nearby.

## Why It's Good For The Game
Currently, the AI steal objective for any antag is the worst objective to get as an antag. Not only do you have to worry about borgs being told locations through binary chat from the AI but also anyone at a camera console can just sit down and callout the location of the holder, refreshing it without delay. This issue in turn makes it so most antags either wipe the AI and restore later OR wait till the last 5 minutes to do it which either option is not fun.

EDIT: Grammar "delay. This issue in turn makes it"

## Testing
1. Spawn in as AI. 
2. Move soul to a body that can handle a card.
3. Tape card and remove tape.
4. Then card the ai and check that its camera works from a camera console (it uses the name given to the AI on round start, not the name they choose, Paracode moment.)
5. Tape the card and check the console again, both roundstart name and AI name, doesn't show up.
6. Remove the tape and recheck both names (it updates to the NEW name of the AI this time but otherwise works as normal)
7. Place AI back in the core and check its built in camera works which it does.

Tape removal
1. Be the carded tape\d AI and use resist verb in IC tab
2. Wait two minutes
3. Tape is removed and camera works again.

## Changelog
:cl:
tweak: Tape removes AI inbuilt Camera while Carded
/:cl:

### CODE REVIEW

**Comment by DGamerL** [comment]
Is there a visual indicator that the Intellicard is taped?

**Comment by pismorizzo** [comment]
Finally a fix for a classic baldie trap. Any shot you can add a mention of the camera to intelcards. Always bugged me that it gives no indication it exists until someone tells you that fact or you die to it.

**Comment by GDNgit** [comment]
> Is there a visual indicator that the Intellicard is taped?

Yes, you can see tape on the intellicard

**Comment by ppi13** [comment]
This is amazing, and a good change.

**Comment by Kuzo1971** [comment]
Does this force the AI to remain alive as pretty much a posi-brain without a choice? I like the idea but I also hope it doesn't leave them with no way to wipe themselves.

**Comment by Komrad822** [comment]
> Does this force the AI to remain alive as pretty much a posi-brain without a choice? I like the idea but I also hope it doesn't leave them with no way to wipe themselves. 
Wouldn't a better solution be to just not allow them to use binary comms when carded? That's the issue 99% of the time when they're carded.

Sadly The thing with binary comms is there IS counterplay to binary since you can subvert the AI, disable all its borgs, emag the borgs so they dont bother you. But the camera does not have any. The best you can do is destroy all camera consoles on station and hope someone doesnt remake them. 

In regards to wiping themselves, if the AI is wiped, they will fail the objective, so its best to not enable a spiteful carded AI to just redtext an antag last minute or right after carding. They'd have to ghost so the antag doesnt lose the AI since itll just leave a catatonic AI.  Before and after this PR, the AI would have to do the same thing either way if they dont want to stay a carded AI, likely asking the admins if they can be ghosted but still be eligible for mid rounds. 

This PR makes the objective not be a "Hide on another z-level", "card early and wipe, fix later", or "wait till shuttle and then rush the AI" kind of objective. I want the ability to USE the AI while on station without constantly being tracked by someone sitting on a console with nothing better to do but make callouts.

**Review by farie82 — APPROVED** [review]

**Comment by farie82** [comment]
image
The label is a lie

**Pull request merged**
