### PR TITLE
Fix traitors/operatives/mindslaves losing their status upon reconnect

### PR DESCRIPTION
**Pull request by Markolie**
Whoops, that's something I hadn't thought of. Robots can most certainly be traitors and operatives, and why should mindslave status be removed when someone's borged - the brain itself is still slaved.

Fixes https://github.com/ParadiseSS13/Paradise/issues/5765.

### CODE REVIEW

**Comment by lordpidey** [comment]
Which is supposed to be more powerful though?  A cyborg's laws, or the mindslave implant on the mind?

**Comment by lordpidey** [comment]
I admit, I'm unfamiliar with this codebase, but won't you also run into problems if you take a revhead/similar, borg them, remove the MMI/brain, and put it back in the old body, and defib the old body?

**Comment by Markolie** [comment]
The cyborg's laws would still take precedence, however, if what their Traitor master orders them falls within the boundary of those laws, then the cyborg should obey... probably? I don't think this is something that has ever happened.

Revolutionary's have had their rev status removed upon being borged for a while now. Seeing as their revolutionary status is completely wiped when they're borged, if you'd put the brain back into the body they'd indeed no longer be a revolutionary.

**Comment by FlattestGuitar** [comment]
Having the mindslave implant removed from your body removes your mindslave status. 

Why would your brain keep it if it's no longer affected by the implant?

**Comment by Markolie** [comment]
Also a good point: I'm not sure what the best option is then.

**Comment by FlattestGuitar** [comment]
❄️❄️❄️❄️❄️❄️ < this.

**Pull request merged**
