### PR TITLE
Goon process scheduler

### PR DESCRIPTION
**Pull request by ZomgPonies**
Adds in the goon process scheduler. Replaces the master controller for everything right now except:
- Garbage Collection -- Will be added in once vg GC is ported properly
- Event controller
- Bot AI controller

### CODE REVIEW

**Comment by Spacemanspark** [comment]
This thing is amazing, next to no lag with two or three singularities running around the station.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

It's a huge help, but it's not a catch-all; an updated garbage controller and LINDA will round out Paradise's optimizations and very likely make things almost lag free.

**Comment by TheDZD** [comment]
This is probably more of a refactor than a feature, but otherwise, great!

**Comment by Markolie** [comment]
Are the garbage collector, event manager and bot controllers working? If so, I think we can merge this in.

**Comment by ZomgPonies** [comment]
Garbage collector will be included in when I update it to the vg standard. Event and bot controllers added, can be merged in now.

**Pull request merged**
