### PR TITLE
Makes human meats flavor more accurate to the feelings of the owner

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Based on peoples requests, human meat, IE, meat made from gibbered / meat cleaver'ed / chainsawed people are now salty like the owner.

## Why It's Good For The Game

A more detailed flavor to the food of those that have fallen victim to the gibber, or traitorous murderers with specialized tools

## Changelog
:cl:
tweak: Human meat is now salty to be accurate to the dead owner
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
Ahahahahaa, thats great

**Comment by Cocacolagua** [comment]
high priority tag and speedmerge

**Comment by AffectedArc07** [comment]
Remind me to re-run travis in 1 hour

**Comment by Balthusdire** [comment]
There is nothing we need more than this.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
