### PR TITLE
Rermove "100" from the list of power options in telesci

### PR DESCRIPTION
**Pull request by monster860**
It's completely impossible to get the power option, let's not have it sitting there taunting us.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by tigercat2000** [comment]
kek

**Comment by fludd12** [comment]
Cue 'unironic science buff' meme

**Comment by Spacemanspark** [comment]
Technically it's a nerf.

**Comment by monster860** [comment]
No, it's a "tg you dun goofed" (Or wherever we ported this from)

**Comment by Spacemanspark** [comment]
>Technically.

**Comment by theColdflame** [comment]
unironically fixing bugs with science

**Comment by TullyBurnalot** [comment]
:-1: Let Telescience taunt Science with their inherent inability to truly master Bluespace.

(seriously though, :+1: )

**Pull request merged**
