### PR TITLE
Changes the color palette of the HoP suit to something better looking

### PR DESCRIPTION
**Pull request by orelbon**
-Props to SkowronX for adding more depth to the suit
final hop suit props too skowronx

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Not better looking :-1: 

Nienhaus sprite is way better than this and goes perfectly well with the hat; this looks like something a host of a fancy dinner party would wear as opposed to a an head officer.

It would be fine if this replaced one of the suits in his locker, but this absolutely should not replace what the HoP starts out with.

Also, merge conflicts.

**Comment by tigercat2000** [comment]
I don't like it either.

**Comment by orelbon** [comment]
it is teh suit in his locker

**Comment by orelbon** [comment]
its not what he spawns with its the suit he has in his locker. @Fox-McCloud

**Comment by orelbon** [comment]
And the golden arm bands make sense since the HoP's locker has a dark gold line across it and a female uniform in the locker is completely gold and orange.

**Comment by Nienhaus** [comment]
I should point out this is replacing "hopwhimsy_s" so this will not replace my sprite, which goes with the hat. @Fox-McCloud

**Comment by orelbon** [comment]
@Nienhaus lol i think they mostly disagreed because it didn't match the hat :laughing:

**Comment by tigercat2000** [comment]
@orelbon I disagreed because I don't like the sprite. Simple answer. :-1: from me, because I don't like the look of it.

**Comment by orelbon** [comment]
@tigercat2000 its fine i was making a joke everyone has their tastes. im not forcing you to like it but since bay liked it i thought some of the players here would as well.

**Comment by Nienhaus** [comment]
qz0mlwx
Left is new, right is current.
This is so people can do a side by side look. I personally like the old more a bit more because the classic "Nanotrasen Blue" color.

**Comment by orelbon** [comment]
nano

new one matches the logo better tough

**Comment by Nienhaus** [comment]
nanotrasen

**Comment by orelbon** [comment]
"you must let go of the past to progress into the future"-me trying to make you like it better

**Comment by Nienhaus** [comment]
Well, I just like cyan.

**Comment by Nienhaus** [comment]
You could just add it as a new uniform.

**Comment by orelbon** [comment]
@Nienhaus if they were too add it there a merge conflict which i don't know what caused it.

**Comment by Fox-McCloud** [comment]
realNT

**Comment by Necaladun** [comment]
Cannot condone those pants with that jacket.

**Comment by veganzombeh** [comment]
I like it more than the old one suit, personally. *Maybe* it would be better suited to being a parade costume, a la the captain's parade tunic though.

**Comment by Fox-McCloud** [comment]
If you'd like to resubmit this, feel free to, but closing for now due to lack of support+resolving of merge conflicts.

**Pull request closed without merging**
