### PR TITLE
Disables Challenge Map

### PR DESCRIPTION
**Pull request by TheDZD**
See title.

The challenge map is poorly designed and makes for a pretty shitty away mission. The only ways people really get through the emitter area are by burn patch spam, slowly walking past the lasers while surrounded by un-anchored airlocks, or by going around the emitters on the side. Most other attempts to do this away mission end in death because it is simply a hallway of death.

Then there is the issue with the syndicate NPCs. Due to the fact that the mob AI is braindead, they often end up killing themselves by breaking the windows and walking into space. And then comes the gear available, nuke ops weapons and armor... Yeaaaaaaah, no, that's not the kind of reward you give people for being able to cheese an away mission.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:+1:  x :100:

**Comment by Spacemanspark** [comment]
thank you.

**Comment by Robertha89** [comment]
well, since the energy cannons doesnt work, and the turrets does, the only way is iehter spam burn patch or some construction like airlocks to block shots, without the turrets, you could carefully time it. 
And the gun at start is enough to destroy one turret, which is kinda enough to set to disable everything else, including turrets and energy cannons. If you do not have the gear the challenge map is a challenge, but the rewards are meh.
Only good if you are an antag to begin with, otherwise it's somewhat pointless.
Im meh either way.

**Comment by KasparoVy** [comment]
Yes please remove

**Pull request merged**
