### PR TITLE
Wizard Touch Attacks and Staff Fixes

### PR DESCRIPTION
**Pull request by TheDZD**
- Flesh to Stone and Disintegrate are now actual touch attacks. Instead of targeting somebody next to the wizard, it summons a NODROP | ABSTRACT item to one of your hands (your active hand if possible), that then requires you to touch somebody to activate the spell on them.
 - This makes targeting easier in large crowds, as you don't have to navigate a dropdown menu, although it gives a warning that the spell is going to be used, requires you to click the target, and cannot be used while stunned or cuffed, and takes up one hand during use.
 - Spell can be used while active but not used up to refund the charge and remove the hand "item."
 - Port of tgstation/-tg-station#10583
- Fixes issue with in-hands and back sprites missing for the staff of animation.
- Fixes missing right-handed in-hand for the staff of healing.

### CODE REVIEW

**Comment by Robertha89** [comment]
I would like to see Ei'Nath, reverted back to it's original self of gibbing everyone around him instead of just one. While I am fine with the flesh to stone working like that, disintegrate i am kinda icky about due to previous statement regarding it. Mostly cause you can't use it while cuffed, and that is a massive nerf.

**Comment by TheDZD** [comment]
Disintegrate is a spell that immediately takes somebody out of the round and cannot be mitigated, and is taken by almost every single wizard. It does not need to be any stronger, and making it gib everyone around you would be ludicrously bad balance. There are other offensive spells available, nobody ever picks them though because Disintegrate is by far the most powerful. 

Being unable to use it while cuffed just moreso seals the deal for bad wizards, as with spells such as magic missile, blink, and ethereal jaunt available, you should not be getting handcuffed in the first place.

**Comment by SamCroswell** [comment]
You might look into the use of this instead.
This is the kind of thing it was intended to be used for.
https://github.com/ParadiseSS13/Paradise/pull/1534

**Comment by Fox-McCloud** [comment]
:+1: 

Instakill spell that doesn't even require you to click on the person? Pretty OP. Glad to see this ported over.

**Comment by Earthdivine** [comment]
:+1:

No more accidentally friendly firing someone you didn't want to gib.

**Comment by Fox-McCloud** [comment]
Merge conflicts. Damn icons (guessing it's back.dmi).

**Comment by Alex6511** [comment]
:+1: Unconscious wizard can gib anyone within 3 blocks? How about no.

**Comment by TheDZD** [comment]
Should be ready to be merged once reviewed.

**Pull request merged**
