### PR TITLE
Make upgrading experimentor not make it worse

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
tweak: Upgrading the experimentor will no longer reduce the chance of upgrading an item's tech
/:cl:

### CODE REVIEW

**Comment by Regen1** [comment]
:+1: finally

**Comment by Fox-McCloud** [comment]
No. This is insanely rare and annoying for a reason; it's the gate for stuff like adrenaline implants and the chancey method for upping combat and other things to their max levels if mining doesn't pull through. It's not meant to be easy.

**Comment by FlattestGuitar** [comment]
It's not meant to be easy, but upgrades making the machine worse are counter-intuitive. 

Adjust the numbers, but make the system work the way it does in this PR. 

10/10

**Comment by Crazylemon64** [comment]
The entire premise of the experimentor seems flawed.

The one useful feature, upgrading tech levels of items, is considered so imbalancing, that any attempt to make it not LESS likely to happen, even though it's at it's most likely to happen by default, is wholesale disapproved.

Also, this is a 13% chance of a 20% chance, now - meaning, a 2.6% chance per experiment to occur - this is lower than the present 3% chance (15%*20%) - this might be offset by the reduced amount of item destruction, but whatever, the whole shebang seems dreadfully boring, grindy, and frustrating.

**Comment by Davdichan** [comment]
If I'm reading this right, +1. It doesn't make the chance of an item being upgraded higher, it only makes the chances of the item being destroyed go away.

**Comment by CrAzYPiLoT-SS13** [comment]
IMO, the whole Experimentor thingie is horribly bad. I don't like the
machine at all and I feel like it should be replaced with something more
useful or refactored. That said, this is the next best thing. :+1:

**Pull request merged**
