### PR TITLE
Granted Detective/Blueshield access to the SecVendor and Equipment Room

### PR DESCRIPTION
**Pull request by TullyBurnalot**
Gives Detectives and Blueshields access to the SecVendors and the Security Equipment Room. 

Does NOT grant access to the various SecurityLockers, just the SecVendor and the room it is currently in.

This should allow the Blueshield to have access to spare handcuffs, flashes, flashbangs and another way to charge their advanced stun revolver.

Simultaneously, this should allow the Detective to have access to spare handcuffs (no more zipties!), flashes and evidence bag boxes, in addition to allowing cheap/poor Detectives to charge their laptops.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Hell no.

This was removed for a reason.

You're not an officer, you're not enforcement, you're not meant to arrest or lead the charge. 

You're a detective.

**Comment by TullyBurnalot** [comment]
The reason I made this is due to the fact that everything available in the SecVendor (sans flashbangs) are things that Blueshields/Detectives get by default. The point of it was to let them get spares if they ever run out/break things without having to get someone to open the door for them. Which is why I limited it to the SecVendors and the room, not the Lockers.

After all, if Detectives/Blueshields want stuff from the Lockers, literally all they need to do is ask and they'll get it most of the time. Hell, I see Detectives being handed Sec Belts without even asking most of the time.

**Comment by Bigtimetripod** [comment]
Yes x100

**Comment by Fox-McCloud** [comment]
Yes, they ask for them and usually get them, but I don't want to grant legitimacy to it (which they currently do not have).

It's like the HoS/Blueshield that asks for all access and usually gets it.

"let's just give them both all access since they ask and usually get it". That situation is not a valid argument for a base job having something they inherently should not and do not need to complete their jobs.

Blueshield and especially detective shouldn't generally be arresting people--Detective had a telebaton and revolver for defensive and not offensive purposes.

**Comment by TheDZD** [comment]
Honestly, have to agree with Fox here, detective-curity and blueshit-curity were specifically curbed down on because the jobs are **not** supposed to be security officers, yet players play them as if they are. At best, the detective and blueshield have access to cuffs/flashes so they can restrain somebody in an emergency, or if there is no security around. 

Just because players will give them things they ask for does not mean you should give them the access to said things by default, it's a player mentality issue (this was one of the major reasons RD loyalty implants were disliked, because players implicitly trust jobs that cannot be antags, and give them access to things they really shouldn't).

**Comment by pipextiny1** [comment]
b8e7b808e657d77b0156a1205c2299e7

**Comment by TullyBurnalot** [comment]
Apologies if I was misunderstood, but I was not making the "they always get it, might as well" argument.

The crux of the issue is, really, streamlining. Rather than having to drag someone to open a door to get a spare pair of cuffs because the Warden forgot to return them, you can just open the door, get a pair, and get out, saving everyone's time.

I would, however, have to make the argument that Bluesec and Detectivecurity are more than capable of being shits without having access to spares on their existing equipment, as demonstrated by the many, many incidents logged on the Banlist. I do not really believe that being capable of having spare cuffs/flashes/bangs would suddenly encourage more Detectivecurity or Bluesec. They have their jobs defined and laid out, and contrary to popular belief, most Security teams do not really enjoy Bluesec. 

Detectivecurity is... iffy. Again, being me, take it with a couple of Mont Blancs of salt, but I cannot see how access to spares would change anything. The tools in the Detective's reach at the start of the round are _more_ than sufficient for Detectivecurity to rear its ugly head. What honestly made it bad before was access to stuff like SecBelts or Stunbatons, hence why I did _not_ give them access to them.

**Comment by KingPhilipIII** [comment]
I personally approve of this change. I like to play Blueshield a lot, and while normally nothing happens to the heads and I sit in my office with a drink for a couple hours, I do occasionally have to rush to someone's rescue. I've had a couple instances where I'm arresting someone beating a head's head in. And I find I never got my cuffs back after arresting the first person to attack a head of staff.

**Comment by Spacemanspark** [comment]
No, for the exact reasons Fox stated.
Sorry, Tully.

**Comment by HereticChurch** [comment]
All I've really seen for the argument against this is "Wah wah bluecurity and detectivecurity wah", nothing really to support why a detective and blueshield shouldn't have access to spare cuffs and flashlights. If letting them into the equipment room is such a big deal, move the secvend to somewhere they can access it. This isn't throwing stun batons and belts to the powergaming detectives, it's letting them restock occasionally.

If the issue is detectives stocking up on flashbangs or something and spamming them we should either remove flashbangs from the secvend or maybe even just yell at people that do that. Y'know, administrate it.

**Comment by IcyV** [comment]
Without fail a lot of Blueshields will rush straight for anywhere they can get more equipment (Looking at you nerds that rush into cargo to print off ammo).There is a reason they get a full setup from their locker. They don't need access to these areas. If a blueshield isn't just shooting and arresting everyone ever, they shouldn't really have any need for more materials. If it's that much of an issue a warden or anyone else with access is more than capable of giving them the supplies they need.

Same idea goes for detectives. They have everything they need. Anything extra should be given at the discretion of a higher power or someone with the access.

**Comment by FlattestGuitar** [comment]
I support this PR. There's no reason to not let people have access to those items. If a Blueshield or Detective wants to play a rampant vigilante they already have all the tools they need for the job. Brig Physician has access to all the equipment already and there's barely a problem on that front, I fail to see how those two jobs would somehow make more of a mess.

If they can access a single one of those items, I don't see why they shouldn't be able to restock without someone else using their ID.

**Comment by TullyBurnalot** [comment]
After giving it some though, I have two other points I would like to bring up:

1) When population goes down, paradoxically, the Detective tends to be one of the few Sec slots that always gets filled up. And when there's only one Officer around, the Detective at least has half an excuse to do Officer duty. This would streamline that process and not require the Detective to go wait for a Head of Personnel that may not even be there.

2) Like Flattest pointed out, the Brig Physician has had to both the SecVendor **and** the Equipment Lockers (the latter of which, again, is untouched by this change), and yet no attempts have been made to remedy this, despite the Brig Physician being **the** last person on Security to have any real excuse to be carrying around flashbangs, cuffs and stunbatons.

In addition, and in relation to what HereticChurch said, if the issue here is Blueshields/Detectives _not doing their job_ and exceeding their power, that honestly falls under the purview of Server Rules. It would not be the first time Detectivecurity or Bluesec get Jobbaned, and it certainly wouldn't be the last, regardless of these changes.

**Comment by Lady-Luck** [comment]
I don't like this PR. Wouldn't it be better just to have more zipties or whatever in their respective offices?

**Comment by IcyV** [comment]
>This would streamline that process and not require the Detective to go wait for a Head of Personnel that may not even be there.

It's still by no means required or always necessary though. A job should get, by default, what they would likely need for a given optimal shift. They shouldn't get a billion supplies "just in case" outside of relevant vendors. In this case, a detective has virtually no reason to ever be the one performing an arrest, so they shouldn't get immediate access to all of securities tools and vendors.

People should need to rely on other people sometimes. Sure, it may suck if that person is slow or lacking in general. But otherwise all we're slowly moving to is giving everyone access to everything so they can just be prepared at all times for whatever they may need to do.

>point 2

See, but a Brig Phys with any of these things is a major no-no to anyone paying the slightest bit of attention. There is no reason for them to ever, for any reason, have any of these supplies. This is more of an oversight in terms of lockers, but makes sense given they need good security access to be able to do their job at all.

A detective/Blueshield don't need into the vendors or equipment rooms ever unless someone else needs them in there. A Brig Phys needs to be able to assist someone anywhere in security in a moments notice given that is literally their only purpose.

**Comment by Belario** [comment]
If they need gear top-ups there are a half dozen people they can ask :-1: 
This would just be a detectcurity enabler.

**Comment by Fox-McCloud** [comment]
Going to go ahead and close this; the negative support on this is very clear and it does not have either @TheDZD or I's support.

**Pull request closed without merging**
