### PR TITLE
Tweaks Centcom away mission to make it viable

### PR DESCRIPTION
**Pull request by Kyep**
Attempts to make centcomAway.dmm into a viable away mission:
- Deletions: centcom ID (all-access ID!), mateba gun (auto-revolver!), centcom ID console, comms console, centcom officer's jumpsuit, HoS' locker (yes, with spare HoS gun), tons of riot shields, retro energy guns, etc. Basically all the combat-oriented loot a greytider could ever want that WAS free for the taking in this mission.
- Additions: powergrid, russian looters, RCD+ammo.

🆑 Kyep
tweak: Adjusted the centcom away mission to make it viable.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
i don't know about this one enough to say if the combat edge was needed or not so..

**Comment by Kyep** [comment]
Given the amount of items on the map, I feel that some combat difficulty is required for it not to be a loot pinata. The existing map was a horrible loot pinata. It even had CC ids, good guns, etc. I've removed the worst offenders, but even as-is it has some useful stuff. I feel like there should be some challenge to overcome to make use of that useful stuff.

**Comment by Draconic-saint** [comment]
Any idea of the estimated "completion" time right now?

**Comment by Kyep** [comment]
@Draconic-saint This isn't a linear mission. It doesn't really have a set end point. Certain areas are more interesting than others, but exactly which are interesting depends on the person. Also on the route you take - there are some shutters you need to lift, or bypass. Also, doors to hack. In short: completion time will vary a lot depending on the person, the route they take, where they go / want to go, etc.

**Pull request merged**
