### PR TITLE
Updates: drink sprites - Adds: New types glasses [WIP] don't merge

### PR DESCRIPTION
**Pull request by DogsParadise**
This is a WIP pr, pring mostly to get a vote going and get the heads opinion on PR.
This PR will take me a lot of time to create and is still a little early in development.

## What Does This PR Do
Includes new types of glasses to fill with delicious drinks.
Updates all drink sprites:

## Why It's Good For The Game
Better sprites

## Images of changes
old:
image

new (very much WIP):
image

## Changelog
:cl:
add: Adds new types of glasses
tweak: Changes drink sprites
wip: Changing all drink sprites
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
wait..
no..
it prd my mosquito branch aswell..

well fuck

**Comment by DogsParadise** [comment]
Fixed

**Comment by SabreML** [comment]
Could you also get some pictures of the glasses in context? On a table or something.
It'll be a bit easier to judge them with a reference point.

**Comment by DogsParadise** [comment]
> Could you also get some pictures of the glasses in context? On a table or something.
> It'll be a bit easier to judge them with a reference point.

Can do

**Comment by AffectedArc07** [comment]
Drafted because WIP

**Comment by variableundefined** [comment]
No head or maint approval for over 90 days. Still in draft. Closing.

**Pull request closed without merging**
