### PR TITLE
Makes xenomorph stuns factor in melee armor

### PR DESCRIPTION
**Pull request by TheDZD**
Instead of always stunning for a full 5 seconds, xenomorph leaps and disarms will now be reduced by the target's melee armor, specifically the chest melee armor for the former, and whatever area is "hit" by the disarm for the latter.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Should probably be a thing.

**Comment by Ultimate-Chimera** [comment]
This broke xenomorph's disarms and pouncing completely.

**Comment by Robertha89** [comment]
Lets run the numbers shall we:
Captain on spawn: 2.5 seconds
Captain Armor: 1.75
HoS: 1.25
Hos in riot suit: 0.5
Officer on spawn: 2
CE Hardsuit: 3
Maxed out Mining: 1
if you add the armor of security suits a wooping 10 puts the stun to last for 0.5 seconds.
lets just never have xenomorphs win again! 

Slower stripping, hardsuit is a must to strip first, melee armor reduces stuns.

Lets just kill them instead.

**Comment by Ultimate-Chimera** [comment]
Basically this made it so if you attempt to pounce on somebody, armored or naked they just get pushed back and disarming only lasts like a millisecond.

**Comment by TheDZD** [comment]
Disarming should only be lasting a short period of time if you disarm somebody who is decently armored. As far as the pounce thing, yup, I did something stupid, fixing it now.

**Comment by Ultimate-Chimera** [comment]
Right, disarm should be like that though, but maybe a tiny bit longer than a millisecond?

**Comment by TheDZD** [comment]
Xenomorph disarms tackle down 80% (!) of the time, and against somebody in a riot suit and security jumpsuit, it'll be reduced from 5 seconds to 0.5 (although due to the nature of ticks, it's going to be longer a majority of the time). The point of the nerf is so that a lone hunter can't leap + disarm spam even some of the most heavily geared people on station.

**Comment by Ultimate-Chimera** [comment]
Makes sense.

**Comment by TheDZD** [comment]
Just as a sidenote, more than two xenos attacking the same person should be about as effective, as with one constantly spamming disarm, you should be able to keep even a riot suit wearing person down, it's just that you can't keep them down AND do something else if you're by yourself.

**Comment by Robertha89** [comment]
remember security uniform grants 10 melee to chest, which stacks with the riot suit. And here is how it is: Ranged win vs xeno, close combat loses vs xeno, not to forget that stripping takes longer time depending, and in general, a single xeno vs any single crew memer, the xeno should always win, unless the guy has a laser gun of sorts.

I mean, I am fine with this, infact, I want this on ALL stuns, so stuns can be buffed again. 

Do remember that this will cause aliens to go for the kill instead of infecting since stripping is harder, and stunning is harder.

**Comment by TheDZD** [comment]
@Robertha89 I'm aware of the armor bit. That said, it's intentional that xenos will really have to go for a kill if they're trying to 1v1 somebody in a riot suit, which will be very difficult in the first place considering they will be doing all of 3 damage per hit. If said riot suit wearing crewmember also has a laser gun, they will likely have little trouble dispatching a single hunter, but multiple xenos will still be a problem, given that one can continually stun them while the other strips/attacks them.

**Pull request merged**
