### PR TITLE
Gunshot Sound Overhaul

### PR DESCRIPTION
**Pull request by rzen1th**
## What Does This PR Do
Overhauls all of the gunshot sounds.  All of the sounds that I changed were produced by myself, so copyright will not be an issue.  The resources that I used to produce these sounds were all either free or provided by stock libraries.

## Why It's Good For The Game
On top of being a breath of fresh air, these sounds were specifically designed to fit into the environment and improve immersion.  I made them with the engine's reverb system as well as the fact that most of the firearms in the game would be discharged in an interior space in mind.

## Changelog
:cl:
soundadd: Redid most of the gunshots from scratch.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'm not sure a lot of these fit---as they're just....actual gunshot recordings.

They have artifacting in them, echo, and a number of them you can actually hear the slide or the hammer. 

Echo really should come from the game engine, not the recording itself.

**Comment by hal9000PR** [comment]
Please post the sounds on the PR so i dont have to download it just to listen to them.

**Comment by rzen1th** [comment]
The audible mechanism sounds were intentional.  I added them in myself.  The interior tail I added works nicely with the in-game sound engine, at least to me.  I can't hear any artifacting at all on my end.  Thank you for pointing out what you weren't too happy with, though.  It'll help me to improve in the future.

**Comment by rzen1th** [comment]
> Please post the sounds on the PR so i dont have to download it just to listen to them.

.ogg files are not attachable on GitHub, sorry.

**Comment by AffectedArc07** [comment]
CI cant pass because BYOND is dead

**Comment by S34NW** [comment]
> > Please post the sounds on the PR so i dont have to download it just to listen to them.
> 
> .ogg files are not attachable on GitHub, sorry.

You have to convert them to MP4 and upload that

**Comment by E-MonaRhg** [comment]
Since there are no examples of the sounds given, 

https://user-images.githubusercontent.com/71735193/125195227-13f73e00-e255-11eb-9826-a8c3a7b75020.mp4

Here you go.

**Comment by warior4356** [comment]
My big issue with hearing the slide and the hammer is that because of how sound works here, having the slide/hammer as part of the sound means that people half a screen away will hear the slide as loud as the gunshot. If they were changed so the slide/hammer were a separate, much quieter sound I would be more in favor of this.

I would also personally like to know where you got these sounds for attribution and license purposes since we have to follow a strict open source license.

**Comment by rzen1th** [comment]
> My big issue with hearing the slide and the hammer is that because of how sound works here, having the slide/hammer as part of the sound means that people half a screen away will hear the slide as loud as the gunshot. If they were changed so the slide/hammer were a separate, much quieter sound I would be more in favor of this.
> 
> I would also personally like to know where you got these sounds for attribution and license purposes since we have to follow a strict open source license.

All of these sounds were constructed by myself using Audacity as well as two stock libraries (specifically BOOM Library's Assault Weapons Construction Kit and Intervention).

As for the mechanical sounds being separate, this can be done, although it would require me to remake all of these from scratch. Unfortunately, I did something very stupid and did not save any of the .aup's. :(

**Comment by variableundefined** [comment]
Objection on the same ground as Fox. 

Closing.

**Pull request closed without merging**
