### PR TITLE
 Fix DAT and Iframes for Books 

### PR DESCRIPTION
**Pull request by shugnk**
With NanoTrasen changed to Nanotrasen as well

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Probably should have a changelog on this like "fixes books" or something.

Additionally, I noticed this brings back the contents of the chef and bartender recipe books. Do you mind checking these for accuracy and updating as necessary?

**Comment by shugnk** [comment]
I can and will report back to you. Apologies for the double uploaded file
on the pull and commit. Its the first time ive used github as a platform

**Comment by Citinited** [comment]
Hope nobody edits all the wiki pages to WGW 😄

**Comment by tigercat2000** [comment]
No idea why these were disabled, but uhh, I guess we'll see what happens?

**Pull request merged**
