### PR TITLE
New Icons for guns

### PR DESCRIPTION
**Pull request by shazbot194**
all

So this rather large (size wise) PR redoes a lot of the current guns sprites. it doesn't get all of them, and some of them are still up for debate, such as the Arg (see bellow), and the baton.

This PR has few mechanical changes, most of which are under the hood so to speak, such as changing the number of charge slots on the HoS's laser gun, and the degal's sprite code. The biggest change is to the Arg, which now has it's own magazine. I did change all the needed code so when you spawn things in with the Arg, it spawns with the correct ammo.

Speaking of Arg mags, I am debating the current magazine style, and if enough people want one style, I will switch it, currently, I am using the 5th sprite.
acr-mags

Massive thanks to @TravellingMerchant for help with both the style, and making a lot of these sprites with me.

🆑 Shazbot and Travelling Merchant
Change: Changes a lot of the gun sprites and the telescoping baton's to new sprites.
/🆑

### CODE REVIEW

**Comment by tigercat2000** [comment]
First off:
 Most of these look worse than the original.
Secondly:
 You should absolutely not include mechanical tweaks in this PR.

**Comment by KasparoVy** [comment]
It's a shame that taste is subjective.

**Comment by TravellingMerchant** [comment]
Can you specify what you like and what you don't like @tigercat2000 ? Which ones look worse?

**Comment by shazbot194** [comment]
> with the old sprite on the right, and the new sprite on the right

> but left and right

Shhhh

**Comment by TravellingMerchant** [comment]
The laser gun redesign was well received in the discord when shown off. It was changed entirely as players had been asking for a laser gun sprite redesign for a very, very long time.

**Comment by tigercat2000** [comment]
It's gone from laser _gun_ to laser _cannon_, and the way the sprite looks, there's no goddamn way you're supposed to hold it with one hand - the other one has the grip in the center to account for this. It's lost a ton of detail on the main body of the gun, despite the size being increased, and it looks more like the silly thing from Judge Dredd than it does a retro laser gun.

**Comment by TravellingMerchant** [comment]
It was designed to look more pistol-shaped. Compare it to the energy gun or captain/hos laser, it's not that big.

**Comment by shazbot194** [comment]
I would like to say, a lot of those are subjective, this is respriting the weapons, not just a small update to the sprites, so yes, they will be different, that is kinda the point. But to go in more detail;

> Shaded extremely weirdly
Significant loss of detail

Both of these are due to the style change. And I would disagree with them. While there may have been some detail lost, most of it was in shading, and not in the actual details of the weapon.

> Been redesigned to make less sense (the laser gun is a prime example of this)

I don't think so. Most of these make just as much sense, as they are still all based off the original sprite. If anything, the lot make way more sense. If you look at the orginal laser gun sprite, it looks about as big as the mini outside of just how big the sprite is. In addition, if you look at something like the degal, it actual has a hold open now, not just an icon change if you remove the magazine.

> Had unwelcome details added to them (there's more than one gun that has been turned red for no apparent reason)

The two guns that were turned red were the combat shotgun and the old rifle, the latter of which isn't even in game. The shotgun was changed to help differentiate it from the riot shotgun, as they do look more similar now without the shells on the side. 

> New sprites are too harsh
New sprites are too soft

This isn't really helpful without pointing to sprites, as you just countered your own point.

> Arbitrarily resized

A lot of the sprite's sizes are already arbitrarily. Look at the sawn off shotgun vs the .357 revolver, or the sniper rifle. There is no standard size for sprites.

**Comment by tigercat2000** [comment]
`This isn't really helpful without pointing to sprites, as you just countered your own point.`
I said "one of the following" as a way to not review every single sprite. However, I'll give you a few examples to help.

 Too soft. All of the fine detail is lost because of the "style".

 Too hard. The sprite looks too solid, the edges are outlined harshly. 

`A lot of the sprite's sizes are already arbitrarily. Look at the sawn off shotgun vs the .357 revolver, or the sniper rifle. There is no standard size for sprites.`
Arbitrarily resized relative to themselves. They should be roughly the same dimensions at the end, not significantly larger.

`Both of these are due to the style change. And I would disagree with them. While there may have been some detail lost, most of it was in shading, and not in the actual details of the weapon.`
So you agree with me that the shading is a problem and there is therefore lost detail? I'm not sure how you're countering my point here.

**Comment by TravellingMerchant** [comment]
The baton I was unsure about when making, thank you fot specifying. I am totally OK with the baton being dropped if need be.

**Comment by shazbot194** [comment]
> Arbitrarily resized relative to themselves. They should be roughly the same dimensions at the end, not significantly larger.

With the exception of the laser rifle, I don't see any that are way bigger, most are about if not the exact same size. The sawn offs are smaller since they are a different style of sawn off, sawing off the stock and the barrel. The degal is also a little smaller in order to actually fit in more detail on what is the largest handgun. 

> So you agree with me that the shading is a problem and there is therefore lost detail? I'm not sure how you're countering my point here.

I didn't say it was a problem, I just said that details that were lost is mostly shading, which I think does make the guns look better. As the sole maker of the enforcers, I will say I like the one of the left much more then the one on the right. 
enforcer_ovn

And ya, we can drop the baton, but I would like to ask the community before we do so.

**Comment by Ty-Omaha** [comment]
the laser gun looks super weird, its not a pistol

**Comment by TravellingMerchant** [comment]
Both the ion carbine and rifle exist looking like that, with just a scope difference already. That's just updated the shading.

Purple grip was requested by the heads of the server.

**Comment by Ty-Omaha** [comment]
ion carbine
its slanted/rounded

**Comment by shazbot194** [comment]
Ok, after a fair amount of testing and talking with people, I have made all new, non smooth cylinders for the revolvers.
cylinder

**Comment by Shadeykins** [comment]
Is that a suppressed revolver?

**Comment by shazbot194** [comment]
It is a Nagant revolver. It uses special ammo, namely 7.62x38mmR, which is long enough to have the brass stick out of the cylinder. The cylinder also moves back and forth, which allow for a gas seal, allowing it to be one of the only revolvers to be suppressable. 
image

**Comment by Fullofskittles** [comment]
I cant really tell what the overall goal of this PR really is. There are some guns that seem scaled up only a tiny fraction but their finer details seem to be removed. The revolver is a good example of this.
                            
481_or | 481_pr
Original Revolver (left) & PR's Revolver (right)

It comes across as just a silhouette, imo. There is hardly any contrast when viewing it at the actual size it will be instead of the blown up scale the example images are at. I feel it's very important to do both blown up and actual size because...actual size is what matters most.

38b82
This is another good example of details being removed, shading being simplified but then other defining details being added.

I actually like the darker outlines defining the lower parts of this one but why did all of the tiny details from the top part of the gun get outright removed? It actually looks pretty nice to combine both.
38b82_b

I realize you said not all guns are touched but the syringe gun/dart pistol and things don't have any changes but were included in the PR image which is a little confusing since there are no changes there at all.

I also am concerned that there don't seem to be any in-hands for any of these revamped weapons. Some of them have been changed quite a bit in both color and design. It's a bit important to have them be accurately reflected that way. Even more so since they are weapons and need to be easily identifiable. It doesn't really make much sense to change only the item sprites and not the ones that you'll see being wielded by players. They should be the same.

**Comment by Fullofskittles** [comment]
@TravellingMerchant

I compared this pr's .dmi to the original .dmi and they absolutely are removed. It's exactly the same as the PR image.

**Comment by shazbot194** [comment]
There was some miscommunication between me and Merchant, we will be talking about this when we are both free and decide how to handle this, sorry for the confusion.

**Comment by DarkPyrolord** [comment]
Alright, after internal discussion on this PR it has been decided that this one will be closed.

Out of all the maintainers and heads who have viewed it, there is minimal support for this PR as it does remove a huge amount of shading and small little details from many of the weapons in this and while a huge amount of effort when into this PR, even PRs with a huge amount of effort have the risk of being closed.

If you wish to push changes such as this as well, I recommend doing it in smaller batches, nuclear PRs such as this one have a much higher chance of being declined compared to smaller PRs which can be picked apart more easily.

**Pull request closed without merging**
