### PR TITLE
Randomized Maintenance

### PR DESCRIPTION
**Pull request by RyanSmake**
_NOTICE: The PR does not add it to the map yet!_ 

Well, here it is.
Keep in mind it does not generate any piping, wiring, or `/area`s, thus those should be pre-mapped. It can use some fine tuning, you are free to make recommendations to weights and ratios.
I did not touch actual random loot drops! Maintenance contraband is exactly as rare as before.
You can test it from admin build mode -> MapGen.

**Pros:**

- On station cults!
- Every round is a new adventure!
- Nerfs metagaming: no longer wandering in maint in the dark because you memorized every route!

**Neutral:**

- Easier to hide in.
- Very easy to get lost.

**Cons:**

- Buffs shadowlings.
- Most of the time hallways go nowhere, and can feel unnatural.

### Todo (optional - without them the PR is merge ready):
- [ ] Spawn unique rooms (eg. surgery)
- [ ] Make it build itself automatically on roundstart

### Notes to self (must do - without them the PR is **not** merge ready):
- [x] Separate window generation (Generate windows last?)
- [x] Make sure that windows don't get blocked (Generate windows last?)
- [ ] Lower the chance of dense items blocking hallways
- [x] `Obj`s in a `turf` counter proc
- [ ] Give non-dense items a higher chance to spawn on tables and racks, lower chance to spawn elsewhere

### Examples:
https://imgur.com/a/h6JElmP
(It makes a lot fake walls too, many areas that seem blocked can actually be accessed.)

_Please don't tear me apart too much._

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Not to discourage you, but this has been attempted before with less than favorable reactions from maintainers (https://github.com/ParadiseSS13/Paradise/pull/5600)

The idea of mixing things up is nice, but I think it would be better to have specific rooms which are randomized rather most/all of maint.

Also, the PR title was a bit confusing, I thought you were adding borg modules to maint. Maybe re-title to something like "Modular Maintenance" or such?

**Comment by RyanSmake** [comment]
@FalseIncarnate I was not around in 2016, thanks for point it out though. I read it through.

Retitle also done.

To answer some concerns from the other PR:

- It is not mapped in yet. It can be merged as-is, and can be used for adminbus only.
- As I stated in my post, this does not put wires and piping in, they must be mapped in default; thus it can be made so that those have their static hallways (Honestly,  I wanted to map it in such a way anyways; we don't want to punish engineers).
- To my knowledge no-one addressed this, but it's been mentioned that security and antags metagame maintenance alike. Most of the discussion though it was only regarding antagonist difficulty. This is a nerf to BOTH groups.

**Comment by Aurorablade** [comment]
I agree it needs to be specific random rooms..and not all of maint. This is not what needs to be done.

**Comment by Kyep** [comment]
Agreed that if maint is to be randomized, that should affect specific rooms, rather than randomizing it so hard that it becomes difficult to even path through it.

As an admin, I don't see myself using this fill mode as-is, even for filling existing rooms, because it creates walls where I might not desire them.

**Comment by taukausanake** [comment]
I don't think it needs specific rooms. What, you want maint to be mining ruins then? That's dumb.

What I would like this to be more of is _incomplete_ maintenance halls. Like walls that were put up but not completed, airlocks and airlock frames placed around but never gotten to, in addition to the random loot. Stuff that makes it look like the station was under construction but was never finished and yet CentComm decided to sent everyone to work anyways. Make them finish construction and do their job, two birds with one stone

**Comment by bigfatbananacyclops** [comment]
Its a station though, its always the same structure. But this might work out, should give a few tests.

**Comment by bigfatbananacyclops** [comment]
Those examples shows sort of a mess everywhere, im at a yes and no.

**Comment by RyanSmake** [comment]
I am after an exam and thus brain dead right now, but I will address every concern tomorrow.

**Comment by Deelite34** [comment]
I think that randomization would work either as new gateway destination, or in one of station maintenances, but it needs one, main, non-randomized path.

**Comment by tigercat2000** [comment]
I'll always support expanding the procedural mapping module, but it's *very* doubtful that we'll ever want to use this automatically.

**Comment by Fox-McCloud** [comment]
It's highly doubtful I'll ever support randomized maintenance; as a system that can be utilized elsewhere? Hypothetically, but, on station? I don't feel it's the adequate place for it.

**Comment by Vivalas** [comment]
I think this would be cool if you whipped up or found a neat algorithm that somewhat attempted to emulate what maintenance should feel like. Otherwise it is a tad bit dungeon like, but I love the idea.

**Comment by RyanSmake** [comment]
_Whew, this is long._

@Kyep

`You end up having to search every wall for false walls, which is tedious and makes maint into a nightmarish maze.`
Ratios can be edited; remove the false walls from the list and suddenly now you have a lot more open doors.

`As an admin, I don't see myself using this fill mode option.`
I didn't see use for the death squid either, but it apparently went used; and unlike that, this is something you cannot do otherwise.

`I wouldn't be able to use this on large patches of maint anyway (due to pipes)`
It does not delete objs while building itself, in fact it won't put walls on objs.

`and using it on rooms could result in them being subdivided or blocked in unwanted ways.`
False, it would destroy the room below and rebuild it from sratch.

Everything else of your comment is out of the scope of this PR, but I might take a look at them later.

@taukausanake
Out of scope of this PR, but to note, this generator places a lot of incomplete stuff, like girders, half-made airlocks and a lot more.

@bigfatbananacyclops
To quote my own PR: `It can use some fine tuning, you are free to make recommendations to weights and ratios.` So uh, you are right?

@Deelite34
`I think that randomization would work either as new gateway destination`
Yepp. If people don't want this on station, this works fine for a space ruin or an away mission.
`or in one of station maintenances, but it needs one, main, non-randomized path.`
My final intention is this.

@tigercat2000 @Fox-McCloud
`I'll always support expanding the procedural mapping module, but it's very doubtful that we'll ever want to use this automatically.`
`As a system that can be utilized elsewhere? Hypothetically, but, on station? I don't feel it's the adequate place for it.`
Fine by me. In this case the PR is merge ready. I am sure this will find some use. Heck, I love mapping, if this doesn't go for station, I might make an away mission for it myself.
Also, Fox, you said on the 2016 PR that this borks NanoUI maps. I tried it out, and the generated rooms are far too clustered to make any sense from that resolution.

@Vivalas
`I think this would be cool if you whipped up or found a neat algorithm that somewhat attempted to emulate what maintenance should feel like. Otherwise it is a tad bit dungeon like, but I love the idea.`
The only thing that works a bit funny with this is the actual room generation. I wrote about three algorithms for this, and the first one gave the best results, thus that's what I pushed. It works fine without rooms too, but it just makes open spaces around, and that makes not much sense, yes?
I see you are a contributor, if you run into some algorithm you want me to try with this, drop me a DM or comment here.

@Dumbdumn5
Would it make sense to try a round or two with this test-merged and then asking the people if they liked it or not? ... I making a forum post.

**Comment by RyanSmake** [comment]
_Note: Added another checklist, I have new ideas to improve quality, will work on them in the upcoming days._

**Comment by RyanSmake** [comment]
You already get a map that is useless, and honestly the proc which creates NanoUI is... Unique to say the least.

**Comment by chesse20** [comment]
PUT THIS IN PLEASE

**Comment by Vivalas** [comment]
@RyanSmake Procedural generation isn't one of my strong points, but what I mostly mean is that if you are able to tweak this to where it feels like what maintenance should kinda be like, it would be a great addition.

I think your to-do list is a great start. Stopping tables from blocking halls and otherwise having clear routes around as well as other paths that are "blocked", along with rooms and such and unique ones will be good.

**Comment by Spacemanspark** [comment]
It gives me that Mystery Dungeon vibe and I totally dig that, although I do feel it's a bit too cramped.

**Comment by RyanSmake** [comment]
I might return to this, but surely not in the close future.

**Pull request closed without merging**
