### PR TITLE
Nudge the glasses inventory icon slightly to align with actual glasses

### PR DESCRIPTION
**Pull request by moxian**
## What Does This PR Do
Moves the HUD icon for the glasses one pixel to the right to fix the funky misalignment with the underlay when wearing sunglass item - see 
20220626-015545-dreamseeker

## Images of changes
20220626-015041-dreamseeker
20220626-015047-dreamseeker
20220626-015051-dreamseeker
20220626-015055-dreamseeker
20220626-015059-dreamseeker
20220626-015103-dreamseeker

## Changelog
:cl:
tweak: Adjust the HUD sunglasses icon to the same position as sunglasses item
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
wait so instead of moving the sunglasses icon one pixel left you moved ALL OF THE HUD GLASSES ICONS ONE PIXEL RIGHT?

It wasn't centred before now it's REALLY not centred.

image

**Comment by moxian** [comment]
Instead of moving ALL the sunglasses variants one pixel left, i moved six HUD icons one pixel right, yes. That seemed to be less work.

Whether or not the icon is centered is a hard/subjective question, since the icon is so unbalanced to begin with. The shades part is more centered now, the temples part is less.
Honestly i don't have an opinion on which way i prefer those to be - to me both are equally fine, unironically.

If you feel strongly about this, feel free to shift the sunglasses the other way, and i'll close this PR.

**Comment by Bm0n** [comment]
> Instead of moving ALL the sunglasses variants one pixel left, i moved six HUD icons one pixel right, yes. That seemed to be less work.

I mean you could have just opened the glasses.dmi file where the icons are stored and pushed a single button to nudge the icons left. There are only like what 4 or so sunglasses subtypes? Surely that's easier than redoing all of the HUD glasses icons and making sure all of the shading is intact. 

> Whether or not the icon is centered is a hard/subjective question, since the icon is so unbalanced to begin with. The shades part is more centered now, the temples part is less. Honestly i don't have an opinion on which way i prefer those to be - to me both are equally fine, unironically.

When I look at the new one I think it leans more right than the old one and looks off-centred, but that's subjective.

> If you feel strongly about this, feel free to shift all the glasses the other way, and i'll close this PR.

I am just trying to point out an easier way this could have been done, if someone else wants to do this they can. Either way, I do not care enough to remake this.

**Comment by moxian** [comment]
> I mean you could have just opened the glasses.dmi file where the icons are stored and pushed a single button to nudge the icons left
THERE IS A BUTTON TO MASS-MOVE SPRITES IN A FILE???? WHERE???


> There are only like what 4 or so sunglasses subtypes? 

20220626-075042-dreammaker

things like mesons suffer from the same problem and also need to be shifted. So it's a bit more than 4 sprites.

**Comment by Bm0n** [comment]
> THERE IS A BUTTON TO MASS-MOVE SPRITES IN A FILE???? WHERE???

there's the nudge button here but you can't do it en masse.
image

You could however use keyboard navigation to achieve the same effect quickly. So arrows to select a sprite, enter to open it and once in the sprite editor arrows to move the sprite then backspace to get out and then you're back to selecting with arrows.

> things like mesons suffer from the same problem and also need to be shifted. So it's a bit more than 4 sprites.

Debatable. The mesons are actually centred as you'll get with 32x32 but could be nudged one left

image

Meanwhile, sunglasses aren't really centred measuring from the nearest points

image


This is currently how mesons look.

image

HUD nudged right

image

Mesons nudged left with current HUD

image

**Comment by AffectedArc07** [comment]
Have the HUD icon be centered and center things around that

**Comment by moxian** [comment]
"Being centered" is very up to interpretation with the imbalanced sprite such as sunglasses.

So far it's me vs bmon on which version (the hud or the glasses item) is "more centered", so I'd need an extra vote to break the tie.

**Comment by moxian** [comment]
I want to fix it eventually, but given the current state of things, I'm unlikely to pick it up any time soon.
Closing for now.

**Pull request closed without merging**
