### PR TITLE
Part 1: The declusterification of pipes in medbay and atmospherics 

### PR DESCRIPTION
**Pull request by orelbon**
This PR is one of hopefully a few that are gonna try and organize the mess of atmospheric pipes that we have right now. At the moment a lot of pipes are placed all over the place, making life for engineers a pain in the ass. Instead of going through doors they pass through walls, etc..  

The places that were edited were Medbay And atmospherics.
 All of the atmospheric pipes here are hidden, but they show up as visible because of the program used to take the image. 

capture2

 🆑
Tweak: Atmospheric pipes in medbay and atmospherics have been organized 
/🆑

### CODE REVIEW

**Comment by pinatacolada** [comment]
Not a fan of the additional piping in atmos, its more pipes to unwrench for when messing around with the setup, but otherwise, yew

**Comment by orelbon** [comment]
I was aware about the extra piping in atmos but the alternative is having them go through all the walls. 

Also you dont need to remove the floor tiles in order to change the set up.

**Comment by pinatacolada** [comment]
What i mean is that if you try to place a pipe in game over another pipe that is under a floor type, the game wont alliw you saying 'theres already a pipe in this place', i think. Theres also scrubbers in places that usually get touched a lot when atmos gets revamped, it just that its an annoyance having to turn the thing off and then removing it so you can do your wacky atmos magic

**Comment by orelbon** [comment]
Alright, if it ends up being a big problem ill just place the pipes in the wall.

**Comment by taukausanake** [comment]
> any program that can let me take higher quality screenshots

inb4 @monster860 comes in with FastDMM.

Otherwise, this will be great. Vent crawling is way too much of a maze when you don't end up dying in the pipes. And it would make sense that the pipes wouldn't be so wild.
I do think some of the admins will have something to say about any edits in this field however. If it was a mess for this long then it's possible they left it that was for a reason. Maybe not a good one but when can you argue with the maintainers?

**Comment by orelbon** [comment]
Lol @taukausanake i check it out and it actually is pretty good, i managed to get a map image.

**Comment by taukausanake** [comment]
@orelbon Try to get the areas affected circled or cropped out. It'll be way easier to see either way, not just with a dump of the whole map

**Comment by FalseIncarnate** [comment]
Let's play spot the loop!

image

**Comment by taukausanake** [comment]
I don't see a loop. Unless you think that purple pipe is coming from the scrubber

**Comment by FalseIncarnate** [comment]
I realized my mistake and deleted my comment because I had mistaken the blue and purple pipes as both being blue. I should have zoomed in and paid better attention before posting that.

**Comment by FreeStylaLT** [comment]
If your goal is to make all pipes more practically accessible in Medbay, please don't neglect the power cables as well:

img

As for the pipes, Why did you make them loop into themselves 4 times?

**Comment by Twinmold93** [comment]
Too many redundancies in the pipes. No consistency with the rest of the station. Not really a good move.

**Comment by monster860** [comment]
Yeah, the map is tree-like and this adds loops making it not tree-like.

**Comment by orelbon** [comment]
@FreeStylaLT I don't wanna touch the wires at the moment because it was already complicated enough to make sure the pipes were in order, perhaps in another PR. 

Ill remove some of the redundancy and looping.

**Comment by Anticept** [comment]
Pipes actually aren't a problem in walls. The t-ray scanner can see into the walls, and then you can wrench them while they are lit up. Clicking a wall with a pipe also lets you install it without deconstructing it.

What we need is the ability to do that shit with wire too, but I realize it's outside of the scope of this PR.

**Comment by orelbon** [comment]
The problem is that there's no organized method of pipes placement, rooms are using pipes that don't even have anything to do with that department. Thats what makes it a pain in the ass for engineers.

**Comment by Markolie** [comment]
You can't put pipes of the same type (i.e. two scrubber, two air supply or two regular pipes) on the same tile, but you can put two or even three of different types on the same tile. So don't worry about that.

This is a great change though, you're doing god's work. I'd even recommend a map freeze while you get this done. Arrivals has great piping because we ported that from Bay after we got the option to put scrubber/air pipes on the same tiles, but the rest of the station desperately needs this.

**Comment by Citinited** [comment]
I'm all for improving our current atmospherics network, which is pretty crappy right now.

@monster860 It actually loops around the station as a whole, so it's not exactly branch-like.

The scrubbers and vents in atmos could probably be hooked up to the pipes in atmos without much difficulty, like this: https://s2.postimg.org/sa7ahj9g9/atmos.png

**Comment by orelbon** [comment]
@Citinited thats actually a good idea.

**Comment by orelbon** [comment]
@Markolie is it possible to wire up the vents and scrubbers the way citinited said?

**Comment by DesolateG** [comment]
As a person who rolls atmos and knows it quite well, unless we get multilayering pipes I really don't like this change.

As is is right now you cannot have multiple pipes going in the same direction, and it's very simple to place and remove pipes from walls.

A. You drill the pipe into the wall by clicking on the wall with pipe in hand and B. disconnect pipe on both ends and it will unwrench the pipe in the walls.

**Comment by Markolie** [comment]
We do have multilayering pipes though, don't we? You can put a scrubber, air supply and regular pipe on the same line.

**Comment by DesolateG** [comment]
You can't lay the same type of pipe in the same direction. So no.

**Comment by Markolie** [comment]
Not the same type of pipe no, but that's not the case here I believe. There's only air supply/scrubber pipes stacked.

**Comment by DesolateG** [comment]
My point exactly. The picture shows those pipes in atmos running through the doorway. What if I wanted to make a super cooled triple redundancy waste loop? Suddenly I can't because there are now a crap ton of pipes clogging up space.

**Comment by orelbon** [comment]
@Markolie like i asked before, it is possible to simply connect the vents and scrubbers the way @Citinited showed?

**Comment by Markolie** [comment]
That picture's not entirely clear to me. But moving the vent/scrubber pipes to the walls may work.

**Comment by orelbon** [comment]
Hes basically saying that you can connect the vents and scrubbers right onto the supply and scrubbing loops.

**Comment by Markolie** [comment]
I'm no atmos expert, but it seems iffy to directly connect them. Someone that plays a lot of atmos should probably answer it.

**Comment by Anticept** [comment]
There's nothing wrong with directly connecting them. The vents self regulate, and waste is waste, period.

**Comment by orelbon** [comment]
Alright ill hook up the vents and scrubbers onto the system itself.

**Comment by DesolateG** [comment]
@orelbon minimalist approach when messing with pipes in atmos. The system starts out sufficient but can be optimized. However, this requires a lot of floor space since we don't have multilayering pipes.

I believe @anticept will agree.

**Comment by Anticept** [comment]
Multilayering pipes when? Hehehehehe.

Question though... how exactly would that work? How does the other servers do it?

**Comment by orelbon** [comment]
@Anticept screen shot is up, see if the connections are good.

**Comment by DesolateG** [comment]
@anticept iirc it allows 5 layers of pipes facing the same way on a single tile.

If you want more info on it go take a spin on /vg/.

**Comment by Anticept** [comment]
@orelbon virology has pipes going under glass.

That IS a pain.

What's going on with that glass up in the morgue? Mistake in the screenshot or did you mistakenly put glass instead of a vent?

**Comment by orelbon** [comment]
@Anticept virology was like that before i modified anything and there's limited space so i don't wanna mess with those. The morgue glass and an incorrect pipe were fixed in the c253443 commit.

**Comment by Anticept** [comment]
If dual port vents were fixed, we could use those in a lot of places.

**Comment by Anticept** [comment]
@orelbon why was this closed?

**Comment by orelbon** [comment]
Too many merge conflicts, also, i cant spend a month waiting without any dev feedback.

**Pull request closed without merging**
