### PR TITLE
Actually makes half the scrubbers function

### PR DESCRIPTION
**Pull request by AffectedArc07**
Ever since the medbay remap, half of the scrubbers on the station have not been connected. All of service, security, cargo, arrivals, and the bridge scrubbers are disconnected. This PR fixes that.

Before:
image

After:
image

Confirmed checking this, by putting air into the scrubbers pipes, 100KPA across one half, 0KPA across the other. You can also see it disconnected from the webmap.

🆑 AffectedArc07
fix: Half the scrubbers actually work now
/ 🆑 

Edit: I swear I mapmerged this, nani the heck?

### CODE REVIEW

**Comment by Citinited** [comment]
I mean technically they would work, that pipenet is still large enough to hold a huge amount of gas.

Also IIRC scrubbers still work even with over 9000kPa of pressure in the connecting pipe (been a while since I checked this). Still though, this should be fixed.

**Comment by FreeStylaLT** [comment]
..woopsie... doopsie?

how the fuck..

**Comment by Taaketa** [comment]
See #8469 which is doing this stationwide.

**Comment by Ty-Omaha** [comment]
#8513 
Wow I completely forgot about this.

**Comment by Agameofscones** [comment]
This would explain why the waste out system has only ever had ~900 kPa vs the standard 3333 kPa in.

**Comment by Crazylemon64** [comment]
LGTM

**Comment by FreeStylaLT** [comment]
gonna rudely interject and totally wash all blame by saying that
https://github.com/ParadiseSS13/Paradise/pull/4774

was probably the PR _actually_ responsible for this disconnect

**Comment by AffectedArc07** [comment]
@FreeStylaLT I would like to deny that statement and provide this:
https://www.youtube.com/watch?v=I0fnR9zaCOk
image
This was long after that PR was merged, yet before the medical rework. And I can be seen ventcrawling around the cargo area and on the other half of the scrubbers network.

Sorry chief, you been had

**Comment by Crazylemon64** [comment]
oh wait this wasn't map-merged
i'm awake

**Pull request merged**
