### PR TITLE
Cyberiad: Replace old Freezers in Medical Storage with IV Freezers.

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
Replace Freezers with Premade IV bags to IV freezer what contain all IV bags

## Why It's Good For The Game
When starting game as medical, people tend to steal Slime Jelly IV bag from public freezers (its source for bartender and chef food/drinks) and medical "storage" with IV bags its normal freezer with placed IV bags, so when someone steal from public one, you dont have "buckup" slime jelly IV bag when slime person appear drained from Blood early game.

## Images of changes
bb1

## Testing
Runned test, map worked.

## Changelog
:cl:
tweak: Replace Cyberiad Medical Storage Freezers with IV Freezers.
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]

**Comment by Venuska1117** [comment]
Test merge before merge, so if something broke i can fix it. (so mistake dont repeat again)

**Comment by Venuska1117** [comment]
wait stop
aaaa

**Comment by SteelSlayer** [comment]
@Venuska1117 Could I have you merge master into your branch again? Since I just merged #21042. Mapdiffbot is showing some crazy diffs, but actual code changes look good. Probably doesn't need a TM but we'll see.

**Comment by Venuska1117** [comment]
> @Venuska1117 Could I have you merge master into your branch again? Since I just merged #21042. Mapdiffbot is showing some crazy diffs, but actual code changes look good. Probably doesn't need a TM but we'll see.

Updated branch, i think it should be okay?

**Pull request merged**
