### PR TITLE
Vampire Holy Water Balancing

### PR DESCRIPTION
**Pull request by SamCroswell**
Balances vampires and their reaction to holy water as requested by several people in the admin chat and on the server

Reactions to holy water are now as follows:

If holy water is applied to the skin (IE sprayed with a fire extinguisher, splashed via beaker, etc) the vampire will become weakened for a time and will be unable to use his powers in a similar manner to how the null rod affects him. 
There is no outward indication this occurs and the vampire will be protected from these effects if he is fully powered or wearing a mask or helmet that covers the face.

If holy water is ingested (IE syringe, drinking, etc) the vampire will get several messages indicating they feels something sizzle in their veins.
 If the reagent has remained in his veins after this message shows three times he will get another message stating they feel an intense burning inside of them, and they will take fire damage. 
If the reagent remains in their system after that message shows six times they will burst into flames with a message stating they suddenly ignite in a holy fire.
Note that the vampire is immune to these effects if he is fully powered.

Lastly, this PR will change our null rod icon to match /TG/'s. See below.
nullrod

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by tigercat2000** [comment]
:+1: to the vampire balancing
buuut I don't really like the null rod icon. :disappointed:

**Comment by fj45** [comment]
What's our current one?

**Comment by Fox-McCloud** [comment]
a skinny black stick with no details.

**Comment by tigercat2000** [comment]
which looks lovely, IMO.

**Pull request merged**
