### PR TITLE
Removes Vox EVA suits

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Having 2 suits on the station only one 45 Karma race could wear (and doesn't really need) was stupid.
Vox can now wear EVA suits with the sprite fitting them, replaced the Vox suits with EVA Suit SSUs and renamed the Xeno Hardsuits airlock to Softsuits
softsuits

:cl:
add: EVA has 2 more EVA Suits
del: Removed Vox-only EVA suits (the grey ones in EVA)
tweak: Vox can now wear EVA suits
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
>(it will clip unless new sprites come in but shrug)

Definitely not.
We're not killing these off *and* introducing sprite errors just because you can't be bothered to make sprites or get someone to make them for you.

**Comment by uraniummeltdown** [comment]
A lot of Vox sprites already clip because of the beak

**Comment by tigercat2000** [comment]
That's not an excuse to add more clipping sprites.

**Comment by Lady-Luck** [comment]
Why not just not have Vox EVA suits?

**Comment by uraniummeltdown** [comment]
alright I'll revert the restriction removal

**Comment by Lady-Luck** [comment]
👍 Might wanna update the changelog

**Comment by Lady-Luck** [comment]
Oh, could you add a couple vox breath masks to Medical's Secondary Storage (where the spare nitrogen tanks are)? The vox EVA suits made for a fallback when for some reason a vox breath mask was unrecoverable.

**Comment by uraniummeltdown** [comment]
Vox can actually wear normal breath masks, Vox breath masks just have a different obj sprite and are restricted

**Comment by Lady-Luck** [comment]
Ahh, didn't know that.

**Comment by davidchan13** [comment]
>Vox don't need space suits.

They don't take pressure damage from space, true. But they still take slowdown and can suffer from the AI pumping plasma or if a considerable amount of the station is breached having the spare suits lets them still maneuver around similar to their fellow crew (particularly in the case of a Vox HoP, Blueshield or NT Rep.)

**Comment by Lady-Luck** [comment]
>They don't take pressure damage from space, true. But this statement is still misleading at best and dishonest at worst. They still take slowdown and can suffer from the AI pumping plasma or if a considerable amount of the station is breached having the spare suits lets them still maneuver around similar to their fellow crew (particularly in the case of a Vox HoP, Blueshield or NT Rep.)

Vox aren't particularly bad off right now and engineering jobs already have vox compatible suits.

**Comment by jughu** [comment]
remember when we had hardsuit mod kits and removed them and just made the sprite whatever race you were couldn't we do that for vox

**Comment by davidchan13** [comment]
>Vox are considered one of the more powerful races right now,

Diona have every perk vox have at a minor debuff and way better healing. Vox are in a good spot, lets fix the races that aren't and stop trying to bring everyone down to the same mediocre standard of vulps.

>Engineering/mining jobs already have vox compatible suits if you absolutely need them.

Engineering and Mining is the key point here. EVA is set aside for civilian and misc crew when the hardsuits run out. Since the one thing about this PR that made sense (making Vox able to wear softsuits) was removed there isn't a good reason to remove the softsuits for the race that can't wear the others.

**Comment by Lady-Luck** [comment]
>Diona have every perk vox have at a minor debuff and way better healing. Vox are in a good spot, lets fix the races that aren't and stop trying to bring everyone down to the same mediocre standard of vulps.

You mean aside from being slow as mollases and dying to a common maintenance item that doesn't produce any significant noise in two hits?

**Comment by davidchan13** [comment]
> slow as mollases 

You mean like a Vox in vacuum?

>doesn't produce any significant noise in two hits

You mean the one that requires you to be in melee range and can be blocked by the biosuits and firesuits publically available in even larger quantities?

**Comment by Lady-Luck** [comment]
>You mean like a Vox in vacuum?

If you don't see how diona's downsides are far more significant I don't know how we're supposed to have a conversation.

I would be all for the softsuits being able to form fit any race, I'm not sure why that was removed in the first place. But I had to choose between having two vox suits in EVA and two more normal suits, I'll pick the latter.

**Comment by uraniummeltdown** [comment]
@davidchan13 Vox CAN wear EVA suits/softsuits, just not ones they don't have sprites for like the syndi suits and voidsuit since the beak clips through the sprite

**Comment by Lady-Luck** [comment]
Wait, they can wear the normal EVA suits? Why did we ever have the vox-only suits in EVA then?

**Comment by davidchan13** [comment]
They can not, I just tried last week. Softsuit, Voidsuit and most Syndie suits are not compatible.

**Comment by uraniummeltdown** [comment]
They couldn't before, they had this snowflake suit, this PR changes it so they can wear normal ones with the sprite fitting them and removing the snowflake suits

**Comment by Lady-Luck** [comment]
Oh okay, that makes sense.

**Comment by Fox-McCloud** [comment]
Way better; having snowflaked clothing for a singular race is generally bad; species fit sprites are better.

**Comment by uraniummeltdown** [comment]
do not merge yet i forgot to remove the restriction from eva suits

**Pull request merged**
