### PR TITLE
New Shadowling Ability - Null Charge! (replaces Drain Life)

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
This PR removes Shadowling Drain Life ability and replaces it with a new ability - Null Charge!

Null Charge is an advanced Shadowling ability unlocked as a third tier upgrade for the Shadowling. (requires 7 thralls, not counting any high-population scaling).

Null Charge allows Shadowling to completely drain an APC of its power after roughly 20 seconds. APC is disabled in meantime. Shadowling has to be careful while doing so, as if he is interrupted, the whole process fails, APC immediately repowers and Null Charge ability goes on lenghty cooldown.

But should Shadowling succeed and drain the APC without interruption, following will happen:
1) APC stays disabled
2) All lights in that APC area will overload
3) APC battery will be completely drained of it's power
4) APC charge mode will be toggled off

In order to fix the fallout, main breaker has to be toggled back on, drained battery must replaced with a new one (or toggling charge back mode on, and waiting while drained battery slowly recharges) and lights in the APC area replaced with a new ones. Engineering or AI involvement is highly recommended.

I firmly believe this new ability will push Shadowlings in a right direction, as something as they should have always been, instead of what we currently have.

Ported from yogstation13.

Tested locally without any issue.

**Images of sprite/map changes (IF APPLICABLE):**
Null Charge

**Changelog:**
:cl: Arkatos
add: Added new Shadowling Ability - Null Charge! This new ability allows Shadowling to completely drain an APC of it's power after a moderate delay. Shadowling must not be interrupted, or the whole process will fail.
imageadd: Added custom icon for the Null Charge ability
del: Shadowling Drain Life ability removed
/:cl:

### CODE REVIEW

**Comment by Diegoflores31** [comment]
drain life its good and why they would want that if the spare is so easy to get and the "meme the ligths" ability is there too lel
?

**Comment by Twinmold93** [comment]
Seems like it could be an interesting assault ability for shadowlings, giving them a better chance to get out of maintenance and go into the station proper, which would make for at least slightly more interesting gameplay

**Comment by Necaladun** [comment]
While I like this in theory, I don't want shadowlings more buffed.
While removing drain life for that helps, I really like abilities that fuck up thralls, and want to encourage that to make it less tempting for people to rush into maint to get made a thrall.

So I'm on the fence here. Is there a way more downsides could be added or something else removed instead of drain life?

**Comment by Arkatos1** [comment]
@Necaladun I agree that people rushing to maints in order to get thralled is a problem (that is quite a general problem for all conversion based gamemodes), but I would rather not solve it by giving Shadowlings abilities that are detrimental to their own team, as it would feel rather.. shitty for both ends. This PR is more to push Shadowlings from magical powerhouse rev heads back to their intended design of stealth, subterfuge and crew paranoia.

I have some ideas that could help with problem above, but that is for another PR.

**Comment by Necaladun** [comment]
Stealth, subterfuge, and crew paranoia are all great things - although this makes me thing shadowlings could be more aggressive, able to take out lights in departments/halls for a long time and thus be, I guess, less stealthy.

That's not to say I'm against this, it's just removing drain life I don't per se like...partially thematic. I like the idea that being a thrall is not really a good thing, and something people want to avoid.

**Comment by variableundefined** [comment]
I think we can consider whether to add back in drain life after the PR is merged in or another downside to being a thrall, but this idea fits in with Shadowling's purpose.

**Pull request merged**
