### PR TITLE
Adds Hawaiian Shirts

### PR DESCRIPTION
**Pull request by Aurorablade**
I told dreamy i would get around to adding these eventually.
Sprites by her.
Kidan may need a tweak....

:cl:Fethas
rscadd:Hawaiian Shirts in pink, red, blue and orange are now in the autodrobe.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Made by PhantasmicDream: Immediate :+1:. These will go great with beaches

**Comment by Citinited** [comment]
:thumbsup: from me on this, also when will we see Scarface re-enacted in SS13?

*Say hello to my little friend!*

**Comment by taukausanake** [comment]
> Scarface re-enacted in SS13

Probably when we can get fully automaic weapons working instead of murdering a computer mouse

**Comment by Ralta** [comment]
Love it. Any chance you could add maybe a closet full of these to the beach? That'd be neat.

**Pull request merged**
