### PR TITLE
Adds in Stubble facial hair, and other things.

### PR DESCRIPTION
**Pull request by orelbon**
stubble

mecha
ripley

### CODE REVIEW

**Comment by Keilden** [comment]
Now we can be generic FPS soldier!

**Comment by Plotron** [comment]
Yupee.

**Comment by orelbon** [comment]
i might have overdone it with the commits...

**Comment by Plotron** [comment]
Even better with the lights.

**Comment by Fox-McCloud** [comment]
you edited icon/mob/mecha.dmi---which is unused.

**Comment by orelbon** [comment]
i'm just gonna close this for now.

**Pull request closed without merging**
