### PR TITLE
Reduces Shaft Miner Positions to 3

### PR DESCRIPTION
**Pull request by Fox-McCloud**
There's way too many shaft miner positions at the moment---there can be 6 at round start, and up to 2 more that can late join, for a massive total of 8.

The positives of this are that there's 5 more jobs to do, overall---but the downside far outweighs the benefits. Five more assistants (at worst---there's still a decent likelihood people will join as another job) isn't going to dramatically increase greytide...but 5 more shaft miner positions has a number of very detrimental impacts on overall round progression, enumerated below.

Lavaland was built, designed, and balanced around there being only 3 round-start shaft miner positions available---additional equipment either had to be ordered via cargo or a shaft miner would have to invest his precious mining points for a recruit----or if someone was truly crazy enough, to transfer to mining and only mine things with just a pickaxe and work their way up, slowly to better equipment.

The high amount of shaft miners reduces the risk of mining, as there's far more buddies, it generates a huge overflow and overabundance of minerals to science, makes fighting megafauna easier, and leads to lavaland becoming depopulated of loot  and danger a lot faster (if you have to handle more tendrils and monsters yourself, it means inherently more risk).

Some of lavalands threats, such as ash walkers, also are a moot point in terms of threat with so many shaft miners--when there's 8 miners and only a few ash lizards, there's not much that can be done but get steam-rolled--when the grounds are more even, then it makes the place more of a challenge and more dangerous (a good thing! Lavaland has no tolerance for the weak).

Of course some of this does depend on the skill of the miners, but overall, this flattens lavaland's progression quite heavily. Less loot on station, less of a material overflow, more of a challenge, more of a feeling of reward, and more co-opreative teamwork with existing miners (or cargo) to get more individuals onto lavaland.

map changes:

Moved some stuff on the lavaland base around to be more in line with how hte base used to be before there were so many positions---also removed all the shaft miner landmarks on Cyberiad.

No changes are necessary on meta or delta as they're appropriately 3 landmarks.

https://mdb.affectedarc07.co.uk/Files/27286452/748156061/1/after.png

:cl: Fox McCloud
tweak: reduces shaft miner positions from 8 to 3
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Any chance we could get a picture of map changes?

overall, I like the idea of reducing miner slots, though 3 might be a tad too low, imo.

**Comment by Qwertytoforty** [comment]
Personally, I would go with 4 round start miners. I still see miners constantly dying out, and see threats like ashwalkers still overwhelming the miner team, as they will pick off miners one by one, and reducing the miner slots will only make it more likely, as less people means people will not group as much. Not to mention, with less miner slots, and antagonist like a cling or vampire on the mining team taking out 1 -2 miners isnt bad with 6-8 miners, but with 3, that's all of the station resources gone.

**Comment by AzuleUtama** [comment]
Pretty sure the increase to 8 was originally done when lavaland first got merged so people could get chance to play the role. It's kinda just stuck as the norm ever since.

I agree there's too many right now though, which is leading to a stupid amount of materials at the ORM sometimes.

**Comment by Fox-McCloud** [comment]
@Qwertyotoforty

I don't view that as inherently a bad thing. It makes individual decision more impactful and adds more importance to the job itself--which makes the reward all that much more enticing.

The game doesn't really *have* to have as much progression as it does with regards to science--the majority of the shifts, just basic materials is enough to get out really good upgrades to most of the station (heck, we operated fine with 0 upgrades at all for a decent portion of Para's functioning).

It's still possible to transfer to mining if things go awry (scientists used to do this all the time back in the day--get those sci nerds out and their butts moving out of their fortress!); the HoP can encourage people to transfer to mining, and, of course, the HoP can also open additional miner slots if he really needs to.

This doesn't prevent additional people from joining mining--it just flattens out most of the potential of mining on the majority of shifts and slows down its progression---which is a *good* thing for overall health of the game.

**Comment by procdrone** [comment]
I strongly disagree, even if I hate mining, this kind of balancing is a very wrong way to do it.

Few points:

- Fewer starting miners means with overall death turnover for miners, mining will most of the time bring no resources as everyone will be dead most of the time.

- With people who obviously go for loot and nothing else, will ignore mining entirely, and that means these few power-gamers will still rush and hoard everything, and bring no minerals to the station, and there aren't any spare to compensate for few power grabbers.

- A lot of departments depend on resource wealth in order to react to global antags - good luck making mechs and advanced weapons and tools against xenos, blobs, terrors, even nukies if enough time/lucky.

Also, to counteract few of the arguments Fox made.

> The high amount of shaft miners reduces the risk of mining, as there's far more buddies

This rarely happens unless someone metagames, as antags are incredibly powerful on lavaland. Vampires and Changelings transferring to mining for easy DNA, Absorbs or blood is a common strat.
Not to mention all these powergrabbers that dont want to share any loot.

They might bunch up (and when i say that 2, three at most) on a high level threat like a dragon, with these numbers nothing changes if you drop miner amount.

> Some of lavalands threats, such as ash walkers, also are a moot point in terms of threat

Most engagements, with what I said above, only really happen in 1v1 setting, or even 2(ashers)v1. Maybe even more if miner is unlucky. 

Ghosts love playing ash walkers and with this i only see miners being at a total disadvantage here to strong Ashies. Miners will be dead and no minerals mined most of the time.

The Ashwalker wipe only really happens if ashwalkers are dumb and die off to fauna, or get targeted to be cleared out by miners to avoid fighting them later alotogether, which again isn't common. 

---

If you really want to limit, maybe 8 is too much, but 3 is way too low. I'd settle for 5.

There is another way to handle this. Drop (and rename) lavaland explorers to two, and restore mining asteroid for asteroid miner job with a different limit, but no exotic resources.

I am missing the free space pod.

**Comment by Balthusdire** [comment]
I think a reduction is needed, though I think 3 is too few. I'd personally argue for 4, but I can see why some say 5.

**Comment by KasparoVy** [comment]
40 janitors.

**Comment by Rurik123** [comment]
> Given how we struggle to find enough job slots for our pop, we cannot afford to reduce the number of available job slots.

A weak reason. Dare I say three less slots won't impact those at the start screen much, and as for the two that are latejoin only, if ya want to get the job you desire you need to be there roundstart. Its always been that way.

> * Fewer starting miners means with overall death turnover for miners, mining will most of the time bring no resources as everyone will be dead most of the time.

Not necessarily a bad thing. Balance on the whole between sec vs antags is improved when science doesn't get their fancy little toys and mechs for both sides. The sole exception being terrors and blob midrounds, the former sometimes needing a little mech help from time to time and the latter a guaranteed win for blob if they play right (assuming RnD is out of the question). I leave out xenos because, unless I'm mistaken, they're still out of midround rotation. 

Better that antags have less to feed on at the lavaland too, since cling/vamp miners camping lavaland is just as bad as clings/vamps camping gateway. Both get a lot of free food from a boring and safe strategy.

**Comment by Spacemanspark** [comment]
I think reducing the slots is alright, but I think 3 is a bit too low. Perhaps four would be best.

While lava land _was_ built for three players initially, it was made on a server with a far more capable and robust playerbase to handle that.
Not to knock our own playerbase, of course, but we are a fair bit squishier.

That said, the idea overall is alright. As is, eight people (+ any cyborgs) is enough to decimate mobs that are already very easy to cheese or otherwise manipulate, especially megafauna.
I don't think science should always be able to reach or create max tier gear every round, either. Miners dying and being unable to give science resources, thusly making science be more careful with RnD/ robotics activities and available resources, creates a much more dynamic experience.

Losing is part of the game. How one person dying or living creates an impact on the rest of the round is somewhat beautiful to me at times.

**Comment by ppi13** [comment]
Lavaland was built, designed and balanced on another server for another playerbase, like it's not untill quite recently that there are even nerfs to the megafauna.

High amount of miners also means greater chance of antags, that increases the risk, cause you usually trust your fellow miner, since they are the ones most likely to send you to medbay, secondly against ANY megafauna, having more miners makes it harder since you can't control the aggro, and you can very fast loose all controll over the fight, nothing is like someone aggroing bubblegum away after fighting it for several minutes, and you got no good way to aggro it back without being safe.

Ash walkers are a huge threat, assuming three people spawn as an ashwalker at round start, and top 2 miners will go together, and even then, it's about who is the better player, and really i usually see the same player getting nearly all the loot and mining everything thats needed quite often, pluss Ash Walkers can multiply really fast if they get a hold of Legion bodies, since they can make more eggs.

Again, this only hurts new players, and less experienced play, while helps experienced players.
Reducing miners will just put everything else sentient at a greater advantage.

In reality this will change nothing, the people who are good at mining will just get all the loot anyway, and that is just much bigger of a power creep, with 8 miners the loot is often spread out.

**Comment by AzuleUtama** [comment]
> Again, this only hurts new players, and less experienced play, while helps experienced players.
> Reducing miners will just put everything else sentient at a greater advantage.
> 
Experienced players aren't more likely to get the role over anyone else who has their miner preference set to high. In fact, it's way easier for an experienced miner to get the role right now due to how many openings there are when the round starts. Making it so the people who powergame through lavaland and rush all the ruin / tendril loot aren't practically guaranteed to get mining anymore isn't a bad thing.

> In reality this will change nothing, the people who are good at mining will just get all the loot anyway, and that is just much bigger of a power creep, with 8 miners the loot is often spread out.

It's still pretty much the people who are good on lavaland getting all the loot as of right now. The difference is that there's usually a lot more of these players due to the high number of starting jobs so the loot just gets more spread out between them, not to all the miners.

**Comment by ppi13** [comment]
He means transfer via HoP

**Comment by DashCee** [comment]
Miners die at incredible rates since it's a job newbros like to take, precisely because it's easy due to the amount of slots limiting the impact of one person's fuck-up.

8 is a lot, sure, but every other department is either directly effected or indirectly effected by the efficiency of miners. The chance of all 3 of those miners spawning being proficient at that role is very low, the chance that none of them do anything but mining all round? Even lower. 

Reducing slots to 3 is just going to result in the majority of departments being supply blocked after some of the miners inevitably cryo or die, and it's going to be fun for specifically no-one.

Even at the number of slots currently, metal and glass runs out fast due to the lack of incentive for miners to go out and get them, it's just going to make it worse multiple times over.

**Comment by KasparoVy** [comment]
> Miners die at incredible rates since it's a job newbros like to take, precisely because it's easy due to the amount of slots limiting the impact of one person's fuck-up.
> 
> 8 is a lot, sure, but every other department is either directly effected or indirectly effected by the efficiency of miners. The chance of all 3 of those miners spawning being proficient at that role is very low, the chance that none of them do anything but mining all round? Even lower.
> 
> Reducing slots to 3 is just going to result in the majority of departments being supply blocked after some of the miners inevitably cryo or die, and it's going to be fun for specifically no-one.
> 
> Even at the number of slots currently, metal and glass runs out fast due to the lack of incentive for miners to go out and get them, it's just going to make it worse multiple times over.

Sounds like I need to start mining again lol. Get things back to the good old days of completely wiped out asteroids.

**Comment by Necaladun** [comment]
8->3 is too much of a sudden drop I think. 8 is excessive for sure. I'd go with 5.

**Review by variableundefined — APPROVED** [review]
I'm on board with this PR if this is tweaked to 5 shaft miners per Necaladun's suggestion

**Comment by AffectedArc07** [comment]
3 heads against. Closing.

**Pull request closed without merging**
