### PR TITLE
Alternate to #7008 gives traitor chainsaw blockchance

### PR DESCRIPTION
**Pull request by jughu**
Gives 20% blocking melee attacks this doesnt include guns/projectiles
why are you running with a telebaton upto a chainsaw murderer anyways?

#7008

### CODE REVIEW

**Comment by theColdflame** [comment]
chainsaw doesnt need a buff

**Comment by jughu** [comment]
this isnt about buffing the chainsaw this is against a plastic batton gaurantee knocking down the guy with the giantic dangerous chainsaw of doom and dead besides even eswords has blockchance and thats 50 so how bad can it be

**Comment by theColdflame** [comment]
click them with the chainsaw

**Comment by Anoonki** [comment]
Chainsaw does kind of need *something* considering it's a double esword without any block that you can't conceal.
Especially considering all this does is put a slight hamper on the lolbatonning, and thematically makes sense.
Who in their right mind would rush a chainsaw wielder with a melee weapon?
Ranged weapons still have full effect though.

**Comment by jughu** [comment]
@theColdflame yeah but they have the same chance of stopping you with a click of a baton/stunprod
besides this is a more expensive esword you cant conceal and eswords already get 50 blockchance i dont see the problem

**Comment by Machofish** [comment]
I just looked up the dual-esword in the repository - am I reading this right? It says the dual-esword has a 75% block chance?

As already mentioned, the dual esword is concealable in a backpack, does enough brute damage to have a reasonable chance of knockdown already, makes slightly less noise - which is also less distinctive due to the common toy esword's noise, and only costs 3 more telecrystals. As it stands it seems like the sole situation that makes a chainsaw preferable to a dual-esword is that the chainsaw leaves 7 TCs for a stimulant autoinjector. Even then, there's cheaper and more sustainable ways for a traitor to get their hands on stun-proofing chems, especially if they're in medbay/sci.

When taking on someone wielding a chainsaw, absolutely no part of the plan should start with "Get in close to them." If @jughu is being forthcoming about the change, 20% to block melee in specific is still a pretty minor boost in the grand scheme of things.

**Comment by Anoonki** [comment]
>As already mentioned, the dual esword is concealable in a backpack

*Concealable in anything in the game, as a small item

**Comment by jughu** [comment]
yes but a esword (not double) has 50 blockchance takes 1 hand slot besides you cant hide the chainsaw or backpack it so why wouldnt it atleast get some blockchance

**Comment by Fox-McCloud** [comment]
Not a big fan, personally. Chainsaw is probably my all-time favorite traitor weapon, both thematically, and in how it "feels"...though this is really not relevant.

In either case; the chainsaw is meant to fill a different niche than the double-bladed energy sword. Dual e-sword is a very anti-ranged weapon; it blocks most on-station ranged weapon and out and out reflects it.

The Chainsaw does more melee damage (7 more), can't be disarmed thanks to its NODROP, and instantly stuns. 

While the esword is undeniably good in melee combat as well, the chainsaw is superior, and I'd really prefer to keep it that way so there's an actual reason to go with one over the other.

Adding block chance to this will increase its effectiveness against ranged weapons, which, I don't think is an inherently good idea, to be honest....and it's anti-melee capabilities are incredibly strong, already.

**Comment by jughu** [comment]
@fox-mccloud this doesnt affect ranged

**Comment by Fox-McCloud** [comment]
Right, didn't look close enough.

Even so, I'm still not really sure the chainsaw needs to be even *more* godly in melee combat.

**Comment by jughu** [comment]
Yeah i agree but you still gotta add a tiny chance of risk considering stunprods/telebatons can easily end your line

**Comment by Lady-Luck** [comment]
So the idea behind buffing the already powerful chainsaw is the psychological deterrent of the stun attempt having a low chance of being blocked so less people try to be a hero and try to stop them?

Call me crazy but I don't think the majority of the playerbase is even going to be aware of this. Hell, I doubt most of the playerbase is even aware that the chainsaw is nodrop.

**Comment by jughu** [comment]
This is just a alternate double esword thats two times more horrible sure it does 60 brute but does that really matter when you break yer bones and scream on the ground in pain

**Comment by granodd** [comment]
The chainsaw doesn't need a deflect chance. It already deals one of the highest amounts of brute damage in the game in addition to a guaranteed stun. Add in the fact that it has a very high decap rate and you'll understand that it doesn't need a deflect chance nor does it need the ability to be concealed.

It is _the_ "going loud" traitor weapon.

**Comment by theColdflame** [comment]
click on them with the chainsaw

**Comment by jughu** [comment]
You better of be going loud with a double esword 75% blockchance reflects 100% energy shots 32 brute? It will most definitly delimb kill in 4 hits there isnt a big difference in murder rates

**Comment by DaveTheHeadcrab** [comment]
Chainsaw already has nodrop, which is absurdly powerful. It's an offensive rampage weapon to the double esword's defensive style -- you can charge into crowds without fearing a wayward disarm turning your rampage into a massive joke that puts even the clown to shame.

**Comment by jughu** [comment]
Yeah but a taser stunprod telebaton can end your run instantly even bolas

**Comment by Lady-Luck** [comment]
>Yeah but a taser stunprod telebaton can end your run instantly even bolas

Hence costing 3 less TC. Use that to buy some syndipockets.

**Comment by jughu** [comment]
And why cant it give a little blockchance normal esword has 50 thats like a coinflip

**Comment by Lady-Luck** [comment]
>And why cant it give a little blockchance normal esword has 50 thats like a coinflip
Because it does far more damage and has nodrop.

**Comment by jughu** [comment]
nodrop wouldnt matter when you get a stun on you and esword is a super rare chance to get disarmed

**Comment by DaveTheHeadcrab** [comment]
Like I said in the previous comment thread. You need to invest in stun resist if you plan to rampage. Always. You're inevitably going to get screwed otherwise.

**Comment by jughu** [comment]
Remov stun based combet

**Comment by Fox-McCloud** [comment]
Chainsaws are already enormously strong for the niche they fill; I think this would be delving too far into the territory of the double bladed energy sword in addition to making an already strong item *too* strong.

**Pull request closed without merging**
