### PR TITLE
Meth debuff

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR reduces meth stamina healing to `stimulative_agent` (adrenals) level and adds chance to get confused for 2 seconds while using it

## Why It's Good For The Game

Meth is currently best fight chemical. It spawns on psychologist, it has 40 stamina regen (20 on adrenals), it gives you speed with some withdraws such as hunger, brain damage and longer knockdown.
Hunger and brain damage doesnt make sense if meth user gonna prepare a bit. Hunger is fixable by sugar IV self, brain damage is fixable by mannitol which is 3 reagents chemical. 
Longer knockdown is a problem, sure, but not really big, currently you have huge stamina regen which allows you to crawl fight forever. 
Knockdown on adrenals usually makes you arrested if you dont have another charge, cause it is real to stunlock adrenals with just two(or even one) officer. With current meth its much harder(or even impossible), due to its double stamina regen.

So whats my point? 0 TC station chemical that spawns at roundstart and can be made without big troubles should not be better than 8 TC 3 uses syndicate item. Reducing its stamina regen makes it at worse than adrenals in fights but still keeps lesser free version of adrenals.

## Changelog
:cl:
tweak: Methamphetamine stamina regen is now at stimulative agent level. While meth is in your blood, you get a little chance to get confused for 2 seconds.
/:cl:

### CODE REVIEW

**Comment by HMBGERDO** [comment]
fixed

**Comment by cybercapitalism** [comment]
having a 30% probability per cycle to confuse for 2 seconds is going to make you confused pretty much permanently. if you're going to add the confused status at all, i would drastically lower the chance or meth will become effectively unusable.

**Comment by HMBGERDO** [comment]
> having a 30% probability per cycle to confuse for 2 seconds is going to make you confused pretty much permanently. if you're going to add the confused status at all, i would drastically lower the chance or meth will become effectively unusable.

It has 0.1*0.3 chance to be applied which is 0.03, not really big

**Comment by Leanfrog** [comment]
I'm not exactly a fan of just making meth bad because it just has an RNG chance of making you lose a fight. While I do agree that it's pretty strong adding RNG isn't the correct way to nerf it. Perhaps make it atrophy your movement overtime from tearing your muscles apart by running too hard.

**Comment by Leanfrog** [comment]
> How would little confusion make you loose the fight? The only it does is running random directions for 2 seconds that's it

In a game where every moment matters for combat, effectively losing control of your character even for just 2 seconds can spell a death sentence, let's take look at games that have stun mechanics, for example McCree from Overwatch 1, this was a stun that lasted not even a full second (0.8 seconds for the record), but was devastating to get hit by as it left you extremely vulnerable. 

Now obviously the same metrics don't fully apply here as Overwatch is an FPS while SS13 is SS13, however the same underlying principles still carry over here. Additionally, much of the balancing done in recent memory has removed RNG rather than adding it, we've been trying to move towards a more skill based system which this essentially contradicts. And finally, as with anything that is RNG based, there's always going to be someone who has even that "really not big" 0.03 chance apply near constantly as well as the inverse, someone who never has the effect proc meaning there's essentially no downside to it.

**Comment by HMBGERDO** [comment]
> > How would little confusion make you loose the fight? The only it does is running random directions for 2 seconds that's it
> 
> In a game where every moment matters for combat, effectively losing control of your character even for just 2 seconds can spell a death sentence, let's take look at games that have stun mechanics, for example McCree from Overwatch 1, this was a stun that lasted not even a full second (0.8 seconds for the record), but was devastating to get hit by as it left you extremely vulnerable. 
> 
> Now obviously the same metrics don't fully apply here as Overwatch is an FPS while SS13 is SS13, however the same underlying principles still carry over here. Additionally, much of the balancing done in recent memory has removed RNG rather than adding it, we've been trying to move towards a more skill based system which this essentially contradicts. And finally, as with anything that is RNG based, there's always going to be someone who has even that "really not big" 0.03 chance apply near constantly as well as the inverse, someone who never has the effect proc meaning there's essentially no downside to it.

I wont take this seriously, little chance for confusion, which still allows you to move, is not the big problem

Comparing overwatch and ss13 is useless, different game types, defferent effects, different ttk

Little confusion chance for 0 tc adrenals is fair

I will not change this

**Comment by lewcc** [comment]
NGL I definitely keep reading this as moth debuff and wonder what Komrad managed to get up to

**Comment by lewcc** [comment]
NGL I definitely keep reading this as moth debuff and wonder what Komrad managed to get up to

**Comment by lewcc** [comment]
NGL I definitely keep reading this as moth debuff and wonder what Komrad managed to get up to

**Comment by Rurik123** [comment]
> Knockdown on adrenals usually makes you arrested if you dont have another charge, cause it is real to stunlock adrenals with just two(or even one) officer. With current meth its much harder(or even impossible), due to its double stamina regen.

Meth is supposed to be "much harder" to stunlock. You are supposed to lethal them. That is the point behind the design. 

>So whats my point? 0 TC station chemical that spawns at roundstart and can be made without big troubles should not be better than 8 TC 3 uses syndicate item. Reducing its stamina regen makes it at worse than adrenals in fights but still keeps lesser free version of adrenals.

If anything, you gave a good argument for buffing adrenals stamina regen. As for meth stamina regen, it seems its doing its job like its supposed too.

The confuse addition might work alone, although I question if its needed. Currently meth only poses an issue if its combo'd with something like cult gear or chainsaw. Meth alone can be defeated with a baton since the increased knockdown times, and if they're really troubling you a single laser (neither of which can be said for adrenals). 

I'm not against nerfing meth since it is (and always has been) dominant for a reason, but trying to make it more vulnerable to stun weaponry—the very thing its supposed to excel against—is a bad way to go about it.

**Comment by HMBGERDO** [comment]
https://github.com/ParadiseSS13/Paradise/pull/21349

**Pull request closed without merging**
