### PR TITLE
Reduces the size of the rollerbed, allows them to be deployed through left-clicks

### PR DESCRIPTION
**Pull request by Somniworld**
## What Does This PR Do
This changes the size of the collapsed roller beds from "Bulky" to "Normal", so as to make them fit inside backpacks.
This also makes them deployable on a targetted turf through the use of a left click, allowing, for instance, to deploy them directly under the person you want to move, without needing to pull said person onto the bed's tile.

## Why It's Good For The Game
The medical roller beds were extremely clunky to use due to requiring the user to hold them in their hand, they are now much less infuriating to use for, say, a paramedic, by leaving both their hands free.

Additionally, deploying roller beds with a left click on an adjacent tile, rather than below yourself is good quality of life that might make the item shine more.

:cl:
tweak: medical roller beds are now normal-sized and can fit in storage items, paramedics rejoice.
add: roller beds can now be deployed on adjacent tiles by left-clicking with the item in your hand.
/:cl:

### CODE REVIEW

**Comment by Somniworld** [comment]
shitfuck I included two different branches in this PR, closing it.

**Comment by Somniworld** [comment]
hehe hoho I'll reopen that in a second

**Comment by Contrabang** [comment]
great PR, sad it got closed by a maintainer

**Comment by atteria** [comment]
this was not closed by a maintainer, it was self-closed

**Comment by Contrabang** [comment]
just a joke, maintainers will never see this 👀

**Pull request closed without merging**
