### PR TITLE
Ports TG's Improved Attack Animations

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports TG's improved attack animations---these are in use, even on Baystation. @Neersighted @RemieRichards.

Port of: https://github.com/tgstation/-tg-station/pull/10314 and https://github.com/tgstation/-tg-station/pull/13298

Implemented better attack animations for when hitting people with an object in your hands. Often times, in the midst of battle, you don't have time to react to what you're being hit with by reading the chat; this rectifies that issue and also lets you know, better, who's doing the attacking. Not surprisingly, for this reason, even Bay utilizes this system, these days.

To that end, since things are far more clear who's doing the attacking and with what, the "hit twitching" has been removed, as its no longer necessary and just makes for visual clutter.

img
From @Neersighted's PR
img2

:cl: Fox McCloud
add: Improves attack animations with items, making it more clear who's attacking you and with what
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
i think on a purely aesthitic value i would miss the hit twitch..but thats me. otherwise is good.

**Comment by CrAzYPiLoT-SS13** [comment]
I don't really like the look of it, but whatever, it's useful. :+1:

**Comment by Dumbdumn5** [comment]
I would really prefer what we have now, for aesthetic reasons. A good way to tell who's hitting who is that the hit twitch looks relatively different from the attack animations, one guy is screaming, one guy is bleeding and getting more bloodied, and one guy is trying to disarm the other, on top of text saying NAME attacks NAME with ITEM! I very much dislike a floating nonsensical ghost object hovering over me as I get my brains bludgeoned out, mostly because it takes away from the feel of it in general.

**Comment by Fox-McCloud** [comment]
>Forgot to ask, would this also show pens, emergency autoinjectors, patches, etc. due to them using what looks to be the attack animation?

No. This will only trigger on things that trigger your mob to move towards someone--that is to say, generally hostile actions.

**Comment by Dumbdumn5** [comment]
Alright, was worried that the parapens and other stealth objects would be showing up.

**Comment by Fox-McCloud** [comment]
Oh, I'd point out, this works, universally---so when you hit something like a wall or a camera or something, it'll display for that too, so this isn't just for mobs.

**Comment by tigercat2000** [comment]
Ah, god, please no. The giant item appearing over them is hideous.

**Comment by QQCucumber** [comment]
>Ah, god, please no. The giant item appearing over them is hideous.

Seriously? It only lasts for a moment. It's a quick, useful, and intuitive. I really hope this gets added.

**Comment by DaveTheHeadcrab** [comment]
Prefer the twitch stay, otherwise :+1:

**Comment by tigercat2000** [comment]
@QQCucumber I don't like the appearance. It's an eyesore, if you ask me, and it somewhat defeats the purpose of the inhands; The jerk towards people and the subsequent overlays, alerts, and shaking on their screen is plenty to tell you've been attacked.

**Comment by ProperPants** [comment]
I don't like how it looks either, but the concept seems nice. It looks like something that belongs in an RPG, like the older Pokemon games.

**Comment by KasparoVy** [comment]
Makes loads of sense to have this. Thank you!

**Comment by Fox-McCloud** [comment]
>Makes loads of sense to have this, but RIP stealthy attackerinos

Nah, anything that doesn't have an attack animation currently (sleepy pens, auto-injectors, syringes, hypo-sprays, etc). Will not get an overlay with these; items that are intentionally stealth, already, will remain so.

**Comment by Spacemanspark** [comment]
Keep the hit twitch.
Otherwise :+1:

**Comment by QQCucumber** [comment]
> @QQCucumber I don't like the appearance. It's an eyesore, if you ask me, and it somewhat defeats the purpose of the inhands; The jerk towards people and the subsequent overlays, alerts, and shaking on their screen is plenty to tell you've been attacked.

I think this is less about being able to tell you're being attacked and more for you being able to survey other people attacking each other.

**Comment by FalseIncarnate** [comment]
Not really a fan of the ghost-item animation. While it does better communicate what is being used in a visual sense, it kinda detracts from the combat in my opinion. The hit-twitches I felt were a better indication of who was being hit, since the movement would catch the eye without appearing overly goofy.

Hit someone in real life, they're most likely going to recoil or flinch slightly from the impact, which is what the hit-twitch mimicked. The floating item I feel just makes it too silly, without really adding anything that wasn't already present, except for maybe exposing pranks where the clown smacks a window with a "Nuclear Authentication Disk" paper/book.

**Comment by fludd12** [comment]
Experimental merge? I like it on other servers.

**Comment by KasparoVy** [comment]
I rescind my comment about rip stealth entirely, won't make much of a difference at all except looking loads better

If we kept the hit twitch it'd be mint

**Comment by neersighted** [comment]
Just gonna take a moment to point out that I wrote these animations for Bay and then ported to TG... :p

**Comment by RemieRichards** [comment]
@neersighted it credits /tg/ as the first Attack animations of this style (ghost items performing a movement) are my own, from /tg/, before this PR paradise only had weird hit-twitching, so it's all an improvement.

**Comment by Dumbdumn5** [comment]
Bah, but the hit twitching isn't bad!

**Comment by Fox-McCloud** [comment]
>Bah, but the hit twitching isn't bad!

I'm the one who added it and implemented it, and even I think it's bad.

**Comment by Spacemanspark** [comment]
You're pretty much the only one that thinks it's bad.

**Comment by FlattestGuitar** [comment]
Hit twitching might look bad with the ghost item thingy, but I'd be for keeping it as well. It looks good on its own, might as well at least try it with this system.

**Comment by Mijhead** [comment]
I like the hit twitching, personally.

**Comment by Dumbdumn5** [comment]
Eh, from outside the port, it looks good aesthetically, which is the only thing it really affects.

**Comment by theColdflame** [comment]
oh god please no

this looks fucking awful, kills immersion and forces the 'whacky chaos' atmosphere that's supposed to be developed naturally over the course of the round

**Comment by QQCucumber** [comment]
>this looks fucking awful, kills immersion and forces the 'whacky chaos' atmosphere that's supposed to be developed naturally over the course of the round

That's some hyperbole if I ever saw it.

**Comment by theColdflame** [comment]
you're probably right about that one, I shouldn't really be posting on git tired

seriously though, this really should be a preference if it ends up getting  merged

**Comment by Dumbdumn5** [comment]
I'm talking about the hit twitch above, not this.

**Comment by pipextiny1** [comment]
"Improved" "Animations" This is neither of them. It does not look good and the argument that you don't have time to react to what you're being hit is dumb, You are getting hit fight back. If you don't have the ability to glance at the chat something is wrong with you not the game

**Comment by SammyC666** [comment]
Pretty lame, so now a phantom version of the object you are hitting someone with phases out of your hands onto them. Needless to say it looks really crap. Maybe there could be an option to turn it off if you're capable of reading text on a screen and controlling a 2D sprite at the same time.

**Comment by DavidRossii** [comment]
> Maybe there could be an option to turn it off if you're capable of reading text on a screen and controlling a 2D sprite at the same time.

Yea make it an option in preferences to disable this, best of both worlds.

**Comment by Fox-McCloud** [comment]
Re-added hit twitching.

**Comment by tigercat2000** [comment]
_I_ still don't like this, but, @Spacemanspark @KasparoVy @Mijhead @KasparoVy what'd y'all think

**Comment by KasparoVy** [comment]
I think with the hit-twitch back it's loads better. I personally don't mind the floating graphic of what you're attacking the person with, and think that instead of it being unappealing it's a pretty decent quality-of-life change. However, that said, I don't mind whether it exists or not-- I've no real preference, there

But my personal opinion doesn't reflect that of everyone else
I agree with DavidRossii in saying that making the floating graphic optional would be a good idea, however for the most part I feel it'll be a setting that's left enabled

**Comment by Kevak** [comment]
I don't like the graphic. It looks weird and not particularly clean. Make it optional (and off by default) or don't add it at all. And keep hittwitch.

**Comment by Mijhead** [comment]
I still dislike the change. The aesthetic of _**THE PHANTOM OBJECT**_ isn't one I like. Still a :-1:

**Comment by tigercat2000** [comment]
@Kevak It's not really fair to ask for it to be off by default. People will never know about it.

**Comment by Fox-McCloud** [comment]
This will be getting a toggle so you can toggle it on or off, just not in this particular PR.

It'd be inane to oppose it at that point.

**Comment by tigercat2000** [comment]
After reviewing the code and confirming that is infact possible to just shove in a "turn preference off, you won't see the weird ghost sprite", I'll give this a :ok_hand:

**Comment by theColdflame** [comment]
If it's getting a preference setting I'm not particularly opposed to this. 

I'd rather it be included in this PR or a PR that gets merged at the same time, though.

**Comment by Spacemanspark** [comment]
Since hit twitching was readded and this is a preference, :+1:

**Comment by QQCucumber** [comment]
While we're on the subject, I wouldn't mind a toggle to turn off the hit twitching myself. I'm not overly fond of it unlike a lot of people here.

**Comment by FalseIncarnate** [comment]
Perfectly fine with this being a preference option. I personally won't use it (i like what we have now), but as long as I can toggle it I have no reason to complain.

**Comment by KasparoVy** [comment]
With #4274 up I'd just like to restate that I completely support this PR. Looks even more wicked, now, and with the preference it means it'll be appealing to even those who just don't like floaty graphics

**Comment by Spacemanspark** [comment]
@QQCucumber It'd be a lot harder to turn the twitching into a preference, I don't believe that's a client side thing.

**Pull request merged**
