### PR TITLE
Adds flashes maintnence loot

### PR DESCRIPTION
**Pull request by imsxz**
Flashes are generally a robust self defense item, and can also be turned into robotics to assist with Borg creation. I propose that flashes spawn as maintnence loot as both a buff to antagonists to help deal with the new fast borgs, and to add a self defense option that ISNT a stechkin, alongside interactions between the maintnence dwellers and robotics.

The spawn rate of them is the same as no-slip shoes, so still pretty rare. 

🆑 Imsxz
add: Adds a small chance for flashes to spawn in maintnence
/🆑

### CODE REVIEW

**Comment by Necaladun** [comment]
Rare enough that it won't be a huge thing, but also gives plausible deniability as to where you stole it from.

I toyed around with the idea of them being accessible and legal for everyone back when we had rev to give rev heads a bit less chance of being noticed.

I can't see any huge problems here, except maybe them being overcharged?

**Comment by FalseIncarnate** [comment]
Aside from overcharging flashes being stupid easy (we should probably revisit that), this seems like a reasonable thing. The rarity is enough where it won't turn into "everyone has one", but while still making it a plausible excuse for having one.

Additionally, since flashes don't stun anymore (they just white-flash your screen and make you dizzy), these don't pose as much of a direct threat to antags as a stunprod might.

**Comment by SamHPurp** [comment]
I think this is reasonable.

Do note however, with your implementation this makes all other items slightly rarer too. If you wanted to add it with no impact to the other items, you'll need to lower `""` to `68`.

**Comment by imsxz** [comment]
@SamHPurp got it, thank you

**Comment by FlattestGuitar** [comment]
- Flashes are not a weapon. Jobs that don't at all need them get access to them for seemingly random reasons - Engineers in Tech Storage.
- Flashes are useless most of the time against anything else than Cyborgs. Security and Command will likely have sunglasses and making people swirl around instead of running straight is only really useful in self-defence.
- Flashes look cool.

I think this should be a thing and it should happen way more often than it currently does in this PR. It shouldn't be on par with the syndicate space suit. 

I'd set that weight to at least 20.

**Comment by SamHPurp** [comment]
@FlattestGuitar I certainly wouldn't put it at 20. They are powerful tools against Cyborgs, and the safest way for you to emag them. 5 most.

**Comment by Birdtalon** [comment]
How has such a simple PR been sitting for almost three months without any decision?

**Comment by tigercat2000** [comment]
Following discussion between the Heads of Staff and Maintainers, it was decided to close this PR; flashes are versatile tools capable of highly effective crowd control, not to mention being capable of disabling cyborgs entirely and, as such, should not be so easily obtained via randomised loot spawning.

**Pull request closed without merging**
