### PR TITLE
Cyberiad: Maintenance Rework [Part #2] (Need Feedback)

### PR DESCRIPTION
**Pull request by Venuska1117**
**- | Test Merge before Merging | -**

This is next Maintenance Rework, if you spotted something you dont like, please give feedback below and describe issue.

## What Does This PR Do
This PR changes maintenances, this is part 2 with change second of three grouped maintenances
If it success, it will be expanded in next PRs

Targeted Maintenances in this PR:
Aft-Port Maintenance
Aft-Port Secondary Maintenance
Aft Maintnenance

## Why It's Good For The Game
Change Shape of Maintenance and Add new "Atmospheric constelation" to maintenances giving more access for vent-crawl and antagonist will have now more rooms to hide in.

## Testing
Runned VSC, errors Eliminated

## Changelog
:cl:
tweak: Cyberiad: Aft-Port Maintenance, Aft-Port Secondary Maintenance and Aft Maintnenance has been updated to be more complex and balanced in loot
tweak: Cyberiad: Aft-Port Maintenance, Aft-Port Secondary Maintenance and Aft Maintnenance air system, is now connected to the main air supply system
/:cl:

### CODE REVIEW

**Comment by pismorizzo** [comment]
Good changes, only thing I dislike is in Aft-Port Maint Blue shield and NT rep offices were moved and expanded significantly, at the cost of the mini maint shop with shutters. Neither the Bluey or NT rep office like ever get used, I can’t think of one time the Bluey would need an office that big. I see the maint shop to hallway get used every few rounds and would like to see it stay in some form.

**Comment by Venuska1117** [comment]
> Good changes, only thing I dislike is in Aft-Port Maint Blue shield and NT rep offices were moved and expanded significantly, at the cost of the mini maint shop with shutters. Neither the Bluey or NT rep office like ever get used, I can’t think of one time the Bluey would need an office that big. I see the maint shop to hallway get used every few rounds and would like to see it stay in some form.

Ahem, the shop got moved above cargo. it did not got removed, just moved.

**Comment by Venuska1117** [comment]
> Good changes, only thing I dislike is in Aft-Port Maint Blue shield and NT rep offices were moved and expanded significantly, at the cost of the mini maint shop with shutters. Neither the Bluey or NT rep office like ever get used, I can’t think of one time the Bluey would need an office that big. I see the maint shop to hallway get used every few rounds and would like to see it stay in some form.

@pismorizzo 
Ahem, the shop got moved above cargo.
It didn't got removed, just moved.

**Comment by pismorizzo** [comment]
> @pismorizzo Ahem, the shop got moved above cargo. It didn't got removed, just moved.

I am not going to curse but I am going to say I am very silly and managed to miss it after looking over the pictures 3 times. Oopsie

**Comment by Venuska1117** [comment]
> > @pismorizzo Ahem, the shop got moved above cargo. It didn't got removed, just moved.
> 
> I am not going to curse but I am going to say I am very silly and managed to miss it after looking over the pictures 3 times. Oopsie

Its hard to spot, yeah.

**Comment by Contrabang** [comment]
I feel like engi maintenance has a lot of spots where there its basically only one spot wide roundstart. There also seems to be a LOT of girders, more than other placed on the map
image

**Comment by Venuska1117** [comment]
> I feel like engi maintenance has a lot of spots where there its basically only one spot wide roundstart. There also seems to be a LOT of girders, more than other placed on the map [image]


@Contrabang  Grinders can be wrenched to remove them and they are to cover antags when they run away from lasers/disablers 
(this is why they go to maintenance when chased in first place)

And this corner is intentionally 1 gap wide, because its not main walkable path (its just dead end, so making smaller hole to indicate it)


If you wish i can increase distance between wall grinders so its more room for lasers to fly.

**Comment by Venuska1117** [comment]
Grilles are "maybe" chance, so they spawn rarely, if its too much i can decrease them a little

**Comment by Venuska1117** [comment]
Here new pictures with removed grilles, yellow X are "removed".
237390747-a4788b8b-4eb7-49a0-a300-0a7043fbc5d7
237389384-1da34cdd-c360-4383-855c-412e5503c7cd
237388359-e756db5f-4988-434d-addb-6164f8b6531c

**Comment by Mooballoono** [comment]
this is kind of a personal thing but i really liked the little hidden 3 tile room near the locker bathrooms (red) and since that isnt there anymore maybe making the wooden boards into a wall (blue) could serve as a replacement to the old hidden room for antags such as cult to use as a little teleport spot like the old hidden room at locker bathrooms. 
237389384-1da34cdd-c360-4383-855c-412e5503c7cd

**Comment by Mooballoono** [comment]
> this is kind of a personal thing but i really liked the little hidden 3 tile room near the locker bathrooms (red) and since that isnt there anymore maybe making the wooden boards into a wall (blue) could serve as a replacement to the old hidden room for antags such as cult to use as a little teleport spot like the old hidden room at locker bathrooms. 237389384-1da34cdd-c360-4383-855c-412e5503c7cd

this is the 3 tile room i meant
image

**Comment by Venuska1117** [comment]
> > this is kind of a personal thing but i really liked the little hidden 3 tile room near the locker bathrooms (red) and since that isnt there anymore maybe making the wooden boards into a wall (blue) could serve as a replacement to the old hidden room for antags such as cult to use as a little teleport spot like the old hidden room at locker bathrooms.
> 
> this is the 3 tile room i meant image

Sure! i don't see issue to make this 2x6 room a hidden room.

**Comment by Venuska1117** [comment]
Forgot type in changes that "airlock"(?) for miners with forced you to go trough two doors got removed, so now miners will stuck less in airlock.

**Comment by DGamerL** [comment]
image
Old style windows?

image
Not sure if we need active air supply to a room that's technically hidden away

image
While I agree that the roundstart setup shouldn't be the most efficient, this cyan pipeline looping back to where distro has already been seems .. unnecessary.
image
Same as above.

image
Uhhhh a xeno spawner?

Powergrid and pipenets seem to all be connected, so no comments on that.

**Comment by Venuska1117** [comment]
> image Old style windows?
> 
> image Not sure if we need active air supply to a room that's technically hidden away
> 
> image While I agree that the roundstart setup shouldn't be the most efficient, this cyan pipeline looping back to where distro has already been seems .. unnecessary. image Same as above.
> 
> image Uhhhh a xeno spawner?
> 
> Powergrid and pipenets seem to all be connected, so no comments on that.

Done, i don't do "pipes" thing, because cyan ones are for maintenance, and blue ones are not supposed to be connected to maintenance air vents.

**Review by S34NW — CHANGES_REQUESTED** [review]
- The windows for BS office have the wrong id var set.
- The doors for BS and NT offices has plating under it
- Please consider using access helpers for the door access var setting, this is our standard moving forward
- This area transition happening in the middle of open space has always bugged me, can you put this section in it's own room? (Maybe join it across to the showers with a wall+door?)
image

- this wire
image

- this disposal pipe under a wall

image

**Review by Sirryan2002 — APPROVED** [review]
as long as S34N's requests were properly fulfilled this PR is good to go

**Review by S34NW — APPROVED** [review]

**Pull request merged**
