### PR TITLE
Donator PAI Sprite - Driker

### PR DESCRIPTION
**Pull request by The-Driker**
PR for my personal Personal Artificial Intelligence sprite. The following is all fluff in line with my previous sprite – The Burger Borg

**Ladies, Gentlemen, Robots, and those of unidentifiable gender!**
Do you ever find yourself growing bored with your various pocket talkin buddies? Do the various shades of black on green that your normal product line of PAI's use; wear on your eyes? Do you consider yourself a patriot of old world values? Do you work extended shifts on a space station and often forget to eat!?
If you answered yes to any of these **q**uestions, we have the **p**erfect produ**c**t for you! One again, after extended experimentation and product testing, **w**e here at Chef Excellence proudly **b**ri**n**g you...

THE POCKET BURGER!

A **j**oint effort **d**esign that appears frien**d**l**y** and de**l**icious! This model is no slacke**r** either, bei**n**g **z**ipp**e**d **a**nd packed ful**l** with the standard software suits that **y**ou will fin**d** yourself using in **y**our daily business dealings. Whether just chatting it up with your new found friend or **q**uickly checking up on your team's health, the Pocket Burger has your back! 
burger 
burger resting 
burger dead
Order now and receive a coupon for your nearest Chef Excellence diner for 10% off a full family meal!
 
_[Chef Excellence and affiliates takes no responsibility for property damage or death due to Improper usage of personal artifical devices. Any and all supposed affiliation with crime syndication’s is completely non-existent, and such claims will be dealt with to the full extent of space law.]_

Byond Key - Driker
Much like the cyborg sprites, I am unable to edit the file that allows me access to use this in game and would need someone to do that for me if it's accepted. 

syndicate message

### CODE REVIEW

**Comment by taukausanake** [comment]
You sir deserve all the 🍔s. Next thing you know you'll get your own 🍔 food you can make as chef. Or a 🍔 AI sprite?

I think the dead 🍔 pAI sprite needs to be more mangled. Maybe put a bite chunk in there? 😛

**Comment by The-Driker** [comment]
Like this?
untitled

**Comment by taukausanake** [comment]
I thought more on the side. The original dead sprite looks better than that one

**Comment by The-Driker** [comment]
How about this then?

**Comment by taukausanake** [comment]
That's pretty good. Big bite though

**Comment by The-Driker** [comment]
How about this? 


Also yes, some dead pAI sprites do have animations.

**Comment by taukausanake** [comment]
Now THAT is perfect

**Comment by The-Driker** [comment]
Groovy. Now I just have to hope it gets accepted, so I can arrive in station with nuclear operatives and scream about America until someone shoots me to death

**Comment by The-Driker** [comment]
After outside discussion, this pAI model was deemed unfitting for the theme of Paradise. Going ahead and closing it.

**Pull request closed without merging**
