### PR TITLE
NSS Ragnarok [DO NOT MERGE - Waiting for PR #11099]

### PR DESCRIPTION
**Pull request by Twinmold93**
Waiting on affected's PR #11099 for Standardization (to updated Z2 to support the larger shuttles and bound_ignores).

Viewable release of the NSS Ragnarok. This station has the goal and focus of being better suited for over 120 players, with more availability of space for various roles. This PR adds the map to the database, and as far as I know does not directly add it to the map rotation.

Standard View: https://affectedarc07.co.uk/ParaMapGen/Images/41.png
Pipenet View: https://affectedarc07.co.uk/ParaMapGen/Images/42.png
Minimap (by Mr. Rogue Ace): Pending
(*If the links aren't working, give them a few minutes. It means they are finishing processing on affected's renderer.*)

*Notice for Merging: Current iteration would require config/jobs_ragnarok.txt to be added (found in the example files) and the noted lines for defining the job loader in job_scaling.dm being set to run.*

Differences between Ragnarok vs Cyberiad:

1) The Entrance: Arrivals and Escape are in the same area, the aft (south) side of the station. Arrivals sits between Docks 1 and 2, on the far left, where the ferry, ERT shuttle, white ship, and admin shuttle dock. Escape, which is much larger, docks between Docks 3 and 4, with the Sol Trader dock being at the end of Dock 4.

2) Shuttle and Pods: Two larger escape pods and a larger escape shuttle (which require PR #11099) better host having a larger player base. One of the larger pods is up at Medbay, and one over by Security. They also include some simple medical sleepers.

3) Second ERT Docking Port: It's by Security, so the ERT can decide which side of the station to spawn on, rather than having arrivals as the generic default.

4) No Turbine: Instead, there is more space for atmospherics and engineering to do the Thermal Electric Generator. Atmospheric's is also larger with the 'fluff' in the center pulled out so they have a template to make their own projects, and all the machines are still on the north wall of Atmospherics.

5) Additional Spawns: More spawn points throughout the station for all roles add a bit more random spawn generation patterns, but more importantly support larger populations, most importantly for civilians (especially in the bar and cafeteria).

*This still requires a decision on how we'd like to approach the spawn changes for specific maps, whether making it a map_config or hard-coded specifically for Ragnarok to spawn with more of each role (snowflake).*

6) Power Sub-Stations: Instead of directly being hooked into the powernet, all departments (excluding Service) is now routed through a power sub-station. This has advantages of allowing us to monitor what departments take up the most power, but as a player side allow antags to knock out power to specific departments more easily and quicker for power, but also change that on default power, electric grills aren't out-right over-powered by the engine/engineering SMES.

7) Security Changes: There is now a full cell block of 7 cells for the increased players who will be causing issues. The prison wing is also larger, with a unique execution section allowing for witnesses (more RP-oriented change).

8) Larger bar and new cafeteria: More space for bartenders and chefs to serve people, sit and relax. More space better supports larger changes to the area for both to make it their own, but also wait staff as an additional role, appointed by the Head of Personnel.

9) Visitor Lodging: Dedicated sleeping quarters allows some people to have a hide away, especially for antags, out of the prying eyes of the security cameras, but also for a larger station supports the idea of long-term crew onboard the station. Speaking off...

10) Head Quarters: All heads now have their own bedroom, which is where their locker is. Included are the head's action figure and bed sheet for the clown to steal.

11) Legal Wing: Just off the left side of security is now a hallway with legal services. Slightly separated from security verses the Cyberiad, there are now additional officers for Internal Affair Agents to talk privately with people needing consoling for various things.

12) Isolation Wing to Virology: With additional rooms, this also includes bringing back the isolation rooms, but aimed more for psychological isolation so the Psychiatrist can check in on multiple patients requiring monitoring.

13) Port and Starboard Pod Bays: There are now pod bays on either side of the station, and the mechanic's workshop is directly adjacent to the starboard pod bay, so the mechanic can now more directly give services to the crew.

There are many, many other changes, which are shown through the maps. Questions are expected, and there are still things to add, I'm more than sure. Feedback will be appreciated, especially on where things could be added.

Current Edits:
- 4/5 12:13a : Made Sci Chem slightly smaller, increasing the size of the maintenance in the area with an extra room. Removed palette that was still sitting near the SST shuttle.
- 4/11 3:44p : AI now faces south rather than north;
Gravity generator now has solid walls and non-glass door;
HoP's Quarters now separated with wall;
CE's Office has only one Engineering Management Console;
Additional Solars added to current arrays;
More signs, pointing from most departments towards medical and security, added additionally to where the evac signs were also placed;
Door locks in visitor lodging rooms;
Detective has access through the front of medical for the morgue, everyone else has to sneak in/ask to be let in through reception;
Condensed OR's, added cryo tube to each as they are further away but also otherwise had fewer cryo tubes. Removed maint access doors to back of surgery, left room for storage/pre-op. Third surgery added;
RD's Office and Xenobotany flipped, xenobotany has 2 additional trays now;
Toxins vent moved, made blast doors 3-wide instead of 1 (idea stolen from Fox's PR).
Secure armory moved to right of briefing room in security. Larger. Tasers moved to regular armory for Warden to easily reach. Additional energy guns, lasers, shotguns, space suits, riot suits in secure armory. Includes WT-50 submachine (x3) in secure armory now;
Cell block now has Cell Management Console, Camera Console, and Record Console; Buttons per cell now in area. Should initiate flash and open/close the door;
New room at front of security: Visitation! Made lobby smaller to add room. Used for giving prisoners, specifically from the Prison Wing, the opportunity to talk to people on the station, if Security/Warden permits;
Changed pod pilot rack of stuff to the suit storage unit now. Changed pod bay slightly due to security armory being moved next to it;
Prison Wing no longer has windows that are not being blocked by something that requires a wrench to move, making it not species specific for break-out, unless the prisoner gets lucky to have a wrench spawn in the maintenance shed like on Cyberiad, and get Rad-storm to open the door for them;
Incinerator has been moved, so now the Prison Wing is detached from the maintenance of the station, outside of the maintenance door heading into the Prison Wing;
Prison guard station now has a coffee machine, potted plant, and windoor to his little area, to make it slightly more secure.
- 4/17 10:45p : Bartender now has a door to his backroom from the Bar;
Added missing wires under some doors, AI Core, and under Secure Tech Storage;
Added lights to various parts of the station that were missing;
Added more camera coverage across station to reduce blind spots;
Removed Prison tag from non-prison cameras;
Switched cameras in Secure Armory to non-motion alarmed ones;
Added Medbay reception doors;
Added missing APC to Science Hallway;
May have fixed the buttons in the Brig Cell Block;
Increased Kitchen size and decreased Cafeteria size;
Correct energy guns now in BS Emergency Armory;
Added one recharger to BS Officer and one to Cell Block;
Removed rust off (plasma) reinforced walls;
Changed V. Dorms door to glass airlock;
Electrified windows that weren't in perma;
Added third beaker for cryotubes in Medbay;
Switched bookshelf and disposals in Meeting Room;
Fixed air alarm in HoP's office;
Fixed Surgery 3 holo-sign;
Switched Security ERT dock and Security Escape Pod locations.
-4/24 8:31p : Changes the job_scaling.dm code to have the Ragnarok specific lines noted on the GitHub, as the GitHub doesn't have the appropriate config file for defining that loader. In order to utilize it, we would need to unmark those lines and add in the config file to the Paradise server, OR a complete refactor of all job code would need to be commenced based on number of job slots and likely a new variable to jobs of `limited=[value]` for things like Head roles.

:c:lTwinmold
Add: NSS Ragnarok, a new station, with a focus of holding over 120 players more comfortable than the NSS Cyberiad.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Stoked to see what this looks like after that nasty tease not too long ago.

**Comment by Couls** [comment]
lavaland AND ragnarok? lavanarok? 👀

**Comment by Fox-McCloud** [comment]
I'm skeptical of adding more maps, at this time, when we can't even maintain the 2 extra ones we have now.

**Comment by Mitchs98** [comment]
Looks good. My main complaint is that if this map is supposed to be to support more players the OR's need to be smaller in order to have more OR's there, no point in having huge OR's in my opinion when in that same space there could be 3-4 OR's. Other thing I don't really see a point in is the patient rooms with sleepers that again could be OR's or something, just seems way to far out of the way of the OR's and cryo to be of much use beyond perhaps dragging light injuries/an antag kill room.

The huge size will also be a hassle to get around and just make things easier for antags in my opinion...but...eh. 

Overall though I really like how the map looks, looks better than Delta and Meta combined. Just not sure how it'd be in practice. Could be good to test merge I guess, certainly needs a few edits in my opinion.

**Comment by Twinmold93** [comment]
@Fox-McCloud There are various reasons why Delta and Meta aren't maintained, mostly that there is very little desire for people to do the maintaining for us. You could argue that for Ragnarok down the road, though my plan is while I'm here, I'm going to work on it.

@Mitchs98 There is space below the OR's for the crew to very easily build an additional OR, with the goal in mind that they will. I actually allowed a couple of areas near the departments to maint to have the goal of being expanded upon (or at least look like it) if necessary. Cryo is a little bit away, I understand that, though the growth (and space available with larger OR's), does mean they can have cryos added to them if we need to.

The size of the station is massive, that does have a negative side effect of merely that, but more space means more space for the population we've been seeing. Science's teleporter system will be very much more important.

I agree, there are edits that should be made, things I need to add still that I missed in my last look, and more I would like to do with maintenance, though would like input and feedback about by players.

**Comment by Darkmight9** [comment]
spotted something 
image

**Comment by Twinmold93** [comment]
THanks, forgot about my palette.

**Comment by taukausanake** [comment]
> Power Sub-Stations

That's going to be my only real worry on this map, but with the shear size of the station I don't see any way around it. Powersinking the station might have less effect now. And what of power disruption events? That hits the main station grid but these sub-grids might not? That's the argument that came around with breaker boxes and I think this station had those in mind. Here you are using SMESs but I think the same result might occur?

That's a lot of Donkpockets:tm: in the dorms. Also each one gets a microwave? AND private bathroom? Damn that's some high quality ~~ERP space~~ crew accommodations. Bit too much if you ask me though.

No on-station telecomms but I can't remember the decision on that matter.

I like this station, it's _THICC_ af

**Comment by AffectedArc07** [comment]
@taukausanake Power event wont be an issue as that just force empties every APC and SMES on Z1. Powersinkin will still probably be an issue

**Comment by Twinmold93** [comment]
@taukausanake The disruption event will still hit the entire station. As for power sinks, you can either hook it up to a singular department, which does allow the power sink to be more viable for quicker attacks rather than waiting, as it should de-power a department much faster. Or you can use it on the main grid and knock out half the station still as all of service, hallways, and maintenance are still hooked up to the main grid. You won't have the access inside the departments themselves, but you'll have the access to get into any room with maint access.

The visitor lodging is supposed to be pretty nice, almost like a hotel of sorts. Which reminds me, I need to add locks to the doors because I don't believe I did.

Tele-communications is just to the left of the gravity generator, below the bridge. This is in mind for #11099 .

**Comment by Agameofscones** [comment]
@Twinmold93 Hey man, could I get a detailed preview of your atmos setup? I'd like to give it a review. If I'm not busy this weekend, I'll grab your branch and check it out manually

**Comment by farie82** [comment]
Looks pretty nice. I love the bar and security. I also love that virology is a bit more secluded. Since yeah you know. Viruses and dead.
Spare surgery set is also neat in medbay.
Escape is also less of a mess due to the multiple entrances. 
One minor thing though
The AI is reachable by xray now I think. AI rogue? Make xray and shoot into wall till AI ded

**Comment by TDSSS** [comment]
A few thoughts:
The AI seems rather exposed to the crew on this map.
Perma is no longer spaceproof race proof, I think? Since there's windows they can break again.
I like having more than one solitary cell.
Secpod's hardsuit is back on a rack, I see? Interesting decision. Guess there was no space for a SSU?
Perma seems rather easy to break someone out of undetected, just weld/burn through an rwall from maint. Not that this is necessarily bad.
There's a few shuttles I don't recognise.  What's the one near virology with the two sleepers?
Why does science have its own botany setup? Seems like it discourages department cooperation.
Morgue is only accessible via medbay or maint, which makes it a lot harder for robotics, chaplain, chef to access it (they all have access)
I like the podbays.
Your 2 is messed up in the arrivals docking ports.

**Comment by taukausanake** [comment]
Science used to have its own Xenobotany which would study alien plants or plants with weird properties. I'd almost argue that they should have been the ones to get the DNA splicer rather than just mash it in with Hydroponics but I think it was that people didn't see a reason to have them separate. I don't know though, I don't feel like a simple farmer would know any of that fancy smancy technology and Hydroponics should just be in charge of growing food for the station while Science would do the researching and modification of plants

**Comment by EvadableMoxie** [comment]
I agree maintaining 4 map would be a bit much, but ideally this would be a replacement for at least meta and probably delta, too.  We're going to have much better results with a station designed from the start for the type of numbers we get when we're at high pop than we will with trying to convert stations initially designed for a fraction of that population.

This is specifically a high pop station and designed for that purpose from the ground up.  It's something we need, in my opinion, in a way we really don't need Delta or Meta.

**Comment by Dinarzad** [comment]
I agree almost fully with Evadable's above comment.  Maintaining so many maps is a little strenuous, but with the way this map is designed, I think we'd actually be able to cut Meta and Delta. So losing 1 map having to be maintained in total.

  I mean I'm also all for just making this the main map, but that's my singular opinion.

**Comment by Twinmold93** [comment]
@Agameofscones I do have the atmospheric and disposal map uploaded in the main description, which shows all pipes on the station. Due to the fact this also includes all overlaid items, it does mean you'll have to piece a few things together, but until everything is finalized and finished being filled in to better accommodate what has changed since this project started and really got into high-gear (the last month or two), a just piping map isn't being made.

@farie82 @TDSSS Instead of having an AI satellite off station, I had decided to add it directly too the station, to attempt to keep the map close to centered as a satellite off the station would have shifted the entire station over (and that would mess with the nuclear device more than the size of the station already does). This station was also started and designed with the idea that the AI would be accessible on station. AI antag is a bit more exposed, but also easier to get to and fix in general if the AI is taken out. I may slightly adjust the AI to make it facing south rather than north, though I felt since it's a shorter walk to the AI, it gave the AI more protection to face it north.

To TDSSS, solitary is generally easier to break into/out of with planning or help, and with solitary further away, it's much smarter to have an officer stationed there as a Prison Guard, helping ease the Warden's job. Since a larger population is expected to be on this station, it makes sense to have more officers available, and this would mean another officer who can potentially watch the total Prison Wing. That meaning said, I believe in the current Prison Wing, the windows there are not infinite health, but I can check and see if they have increased integrity over standard r_windows.

The two shuttles you don't recognize are escape pods that are increased in size. They, along with the escape shuttle's increased size, are why I need Affected's PR without either making a custom Z2 or forcibly making smaller shuttles, and with a station meant to house more players, it's only smart to have the space to allow them to escape.

Science gets Xenobotany/Xenoflora with the intended purpose of more science jobs, and a more inclined position for people looking to grow the exotic stuff and test different methods and chemicals rather than taking up the beginner-friendly position of regular botany. This allows us to save those positions on Ragnarok for newer players, or those who rather just RP a regular botanist rather than the scientific botanist *that makes weed on round start rather than anything for the chef*. Especially since it's possible the crew may want two chefs on this station, much like two bartenders. Nothing on Cyberiad has ever actually stopped scientists from just being separate on their own, and really, from an RP-sense, would make sense so they focus on their research work. That being said, botany will still have all the equipment at this time so support the capability to still do genetic testing on plants, but depending on how things turn out, those machines could be moved to the bare basics to support more trays.

Regarding the morgue, while the chaplain and chef do have access on Cyberiad by default, and the don't lose the door access on Ragnarok, it's much like the Clown and mime space suits in EVA. They have access, doesn't meaning they should have it/be in there. What I mean with that is, from an RP-sense, the chef REALLY shouldn't have morgue access as the source of meat is questionable at that point, so him sneaking in through the back to get soylant green just adds to the fact it's morally wrong. He can still ask to be let in through medical, so at the very least they know why a body is missing. For the chaplain, it's much the same way, though allows for a checking out of a body for funeral services rather than just taking one for a service. Even in real life, a chaplain can't just walk into a morgue without checking in with the front desk (though in real life he himself wouldn't be going to get the body). This applies to robotics, too, though they will have an easier time just going in through the back. The detective should have access to the morgue through medical, and I may need to add the access to the main doors of medical for the detective if he doesn't already have access.

The two in arrivals is wrong in the renderer, same as the four, due to the renderer not having the floor tile I used, which is added in Ragnarok's overall files.

The security pod pilot suit unit is an oversight on my part, and needs to be turned over to the storage unit.



I'll be keeping a list of suggestions as I read them and updating my list with yes's, maybe's, and no's as I go so I have something as a development platform for the map itself. While it may not necessarily be a public list, it's purpose is so I can keep track of what has been suggested and see if it fits into something I can do or feel should be avoided for the map.

**Comment by taukausanake** [comment]
For the case of the morgue, because I think the chef should have easy access to it, could you switch its place with that of the break room/bathroom and maint hall directly south of the front desk? I can't decide whenever it would look bad or not but that would allow for easy access. Might even give it more room for dead bodies. Otherwise I'm kind of okay with where the morgue is so long as the chef can get good enough access to it

**Comment by Twinmold93** [comment]
I personally don't feel like they should have easy unchecked access to the bodies. They can still get to the bodies without checking in with medical, but it's a bit more of a trek. How hard would it be to check in with medical reception and say you are here for the bodies? If someone cannot be bothered to do that, they can take the dangerous path of going to maintenance to grab the body. Robotics has a short trek, since they just have to jump into the west-maint of science and go straight down, chef and chaplain for unchecked access just go through the back.

Outside of those, having it in the back does make it easier for other antags to get to the bodies, too, honestly, so that's a thing.

**Comment by TDSSS** [comment]
@Twinmold93 
>That meaning said, I believe in the current Prison Wing, the windows there are not infinite health, but I can check and see if they have increased integrity over standard r_windows.

The windows in the current station don't have increased health, no. But every window in perma that leads to space has a botanical tray or drying rack in front of it. You cannot move those without a wrench, with prisoners don't have. You also can't climb on top of them. This makes it impossible for a prisoner to just bash the window in and escape into space.

See #10403 where this was added. To quote the PR description:

>The trays in front of windows in Perma also have their irrigation system turned on - meaning you can't break out to space all on your own.

**Comment by Twinmold93** [comment]
I looked at the map in the PR you posted and see what you are talking about, @TDSSS . I have made an update note to ensure only where the trays are are there windows (so the only way to move them is for the prison maint to have a wrench spawn in it and a radstorm event trigger), and just remove the extra windows, making perma more secure even against space carp.

**Comment by Kyep** [comment]
I have deep, deep reservations about this.

Before we even get to the map itself:

- We already have a map designed for highpop: Metastation. Meta is easier to maintain than this would be (because can port improvements from other servers which use it). Its also easier for new people to learn than this one is (because its already used on other servers). For this to be preferred during highpop over metastation, it would have to be MUCH BETTER than meta. I don't see how this is MUCH BETTER than meta - like clearly, indisputably better by a wide margin.

- We already have issues with old maps that aren't kept up-to-date. This happened to some degree with meta, delta, and others. I don't know if, assuming we did merge this, Twin would still be updating this in 6 months, or 12 months, or 24 months from now.

- I'm not sure about adding more /areas that are only used on one map file, especially a map file that is not going to be in regular rotation.

-  Making the map actually support higher job slots (the point of having a bigger map) requires a per-map-job-slot-config system, which this PR doesn't add. It sorta needs that, or at least there needs to be a plan for that. Otherwise... you haven't really made a map that supports more people.


Now, as to the map itself:

- I worry that this is going to get the same reaction that metastation does (ie: lots of people, including me, hate it). Primarily because they don't want to re-learn the whole map from Box. This map doesn't even have departments in the same compass directions. Trying to learn this map is like starting over from scratch. While I have given some suggestions to make it a bit easier to learn (like conventions with regards to large hallways, colored lines on the floor, etc)... I still feel like the general layout makes it feel like a completely different station, not just a bigger / higher cap version of Box.

**Comment by KasparoVy** [comment]
BigBox(tm) :rofl: 

Call me crazy, but I like being able to navigate the station fluently with the blind disability on. From a players perspective though, "yay variety".

Going to take me a very very long time to get to that level with any of the other maps.

**Comment by TDSSS** [comment]
TBH, I love exploring a new map instead of Box where I remember every maint room and every hiding place.

**Comment by Bookdrizzt** [comment]
Just some minor nitpicks: you’ve got some issues with console replication, in Engineering for the most part. CE in there has 2 Engi Management consoles when there should only be one. 

As a suggestion, the prison guard area looks really barren at the moment. Maybe put some consoles in there so the guard has something to do? Security Camera Console, Record Console, ESPECIALLY a cell management console.

**Comment by Twinmold93** [comment]
@Kyep With Meta, from most of what I've heard, it feels too cramped to fit as a high-pop map. When it comes to Meta, as well, just because it's easier to port stuff from other servers doesn't mean those ports fully work compatible with Para Code, which means the ports would have to be modified anyway, regardless of what we do. As for defining what is 'clearly, indisputably better by a wide margin.' That is completely subjective to the person. It's also up now for feedback and suggested changes so that it CAN get better, rather than no visibility. Transparency on the project, as it were.

Again, with maintaining, it requires someone who is dedicated to the map or code. You're dedicated to Terror Spiders, you fix it as we keep going, but when you have the time which is expected. This map is my project, though I feel there are a few people who would help once the capability of having it more accessible is a thing. Not including myself being able to update the map when changes occur that remove and add equipment to Cyberiad.

Extra /areas that are for a map now can also be expanded upon into Cyberiad if we really wanted to, such as a proper dormitory. Nothing suggests we cannot expand Cyberiad in that regard. But I personally feel that may be an unnecessary limiter to limit areas in that way, when sections are too large to be a singular area (arrivals itself on Ragnarok, which is larger and different named for reference points).

Did I not suggest to you one or two ways regarding making this support more players on round start with config changes/code changes? I recall that interaction between us.

You've told me of your hatred towards the map before. I still went through with it against fire. Yes, some of your conventions you suggested, like making secondary hallways smaller and adding some sort of color coding to the halls near departments have been added, and the signs do point to the departments, starting front the main spine of arrivals out to the department. I can and probably should add more signs throughout the station, which with their placements already allow this to easily be a thing. I can say, though, that getting to this stage has shown at least some level of dedication towards the map and trying to give us something unique.

**Comment by Mitchs98** [comment]
> * I worry that this is going to get the same reaction that metastation does (ie: lots of people, including me, hate it). Primarily because they don't want to re-learn the whole map from Box. This map doesn't even have departments in the same compass directions. Trying to learn this map is like starting over from scratch. While I have given some suggestions to make it a bit easier to learn (like conventions with regards to large hallways, colored lines on the floor, etc)... I still feel like the general layout makes it feel like a completely different station, not just a bigger / higher cap version of Box.

This is also a concern of mine. Though I do like the map. I wasn't sure how to properly say this, but Kyet summed it up well.

**Comment by TDSSS** [comment]
Other servers manage to have a map rotation without issues, I somehow doubt that our players can't adapt and remember the layout of 2 maps.

**Comment by Mitchs98** [comment]
Beautiful medbay :+1:

**Comment by KasparoVy** [comment]
The more I look at it the more I'm loving it. Stoked

**Comment by MechaMaestro** [comment]
Love the map, I'd just like to some of the bar space turned into a more dance-club esque atmosphere (Light floors that can't be turned off by people)

**Comment by Twinmold93** [comment]
@MechaMaestro I actually had that in an earlier design, but when I tested it myself, it looks... Wierd... Just didn't turn out the way I had hoped, and err'd on the way of just removing it. The bartender has more enough space to make one him/herself, however.

**Comment by KasparoVy** [comment]
Eh, let the barfolk renovate it how they please.

**Comment by Nopm** [comment]
Uh... the captain's office, more specifically, the bathroom, seems to be too exposed. What's stopping the tide from welding tool + crowbar-ing their way in?

**Comment by TDSSS** [comment]
On current station you can just weld into the little maint area connecting captain's office and teleporter, then crowbar into his office. It's exactly the same.

**Comment by Spacemanspark** [comment]
The shuttle area is inspired by the Northern Star map from Polaris, I see :p

Excited to see where this map goes.

**Comment by Markolie** [comment]
Make sure all turfs underneath engines/propulsion use /turf/simulated/shuttle/plating and that all propulsion have plating underneath them.

**Comment by PigeonsSuck** [comment]
I really liked the look of the bar, though I question its functionality. I think if you just moved the booze dispensers onto a side bit instead of in the middle so people can dodge around it and your bullets then I think that would fix the problem. I do really like the look of it, though, very bar-like.

Security I didn't have much of a look at because I don't really go to security often, heck, I've been here 2 years and barely know the layout to security on the Cyberiad.

Sciensia I love but I think it should be moved a bit closer to the shuttle, which I know is borderline impossible so just pretend I didn't say much about that. I really like how they made sci-chem, I much prefer it over the Cyberiad's sci-chem. I do still hold the opinion I have on the other station that you should have a small containment area one block large that just contains plasma so you don't burn all the boxes of syringes and beakers and shit because, frankly, that shit's annoying, and I also hold the opinion that you should move the table farther away so fucking up phlogiston doesn't do the same thing for the same reason, but other then that I love its layout. Didn't see much of anywhere else because I'm a shitter, frankly.

Hallways look lovely, I can't comment much on command because I didn't see much of it due to not having a captain ID for most of the shift, due to no fault but my own.

The kitchen to me just looked like a copy of the Cyberiad's kitchen but with double the tools and double the fryers and shit, though I don't play chef and I couldn't get there before people fucked it up, so I can't comment too much on this.

Didn't see engineering at all because, as I said, I was pretty much just a shitter shooting phlogiston at people.

Medistan seems like a mixture of metastation and the Cyberiad's medical area. As someone else pointed out on the discord, the front desk seems kinda badly designed in that the windoor to get in is placed where the chokepoint will be, which just seems like a bad idea. Um... seems a lot more space-y, which is a good thing. Don't have much else to say about it because I just had a quick glance at it.

And that's it! I personally loved going on this station, I got a tiny bit of a headache at the start from looking at it (in my opinion the starting area is a tad bit too big and you could've had more signs showing you where to go), but I think it's the perfect size for the player count and I look forward to being able to go on this station, whether it be officially or unofficially. The fact that one person made this is kind of staggering. Sorry for rambling a lot, I'm bad at writing and I just like rambling. Anyways, good job mate!

**Comment by bookofguns** [comment]
currently the map is under small group testing phase hammering out bugs and bigger map design problems before even a larger group testing takes place.

as of the last test I was apart of I note a few things

-  found and had some door access permission fixed
-  tested and made sure engine, solar, and power distribution all worked 
-  tested and fixed spawn location of jobs and increase of job position before round start.
-  AI turrets of the stun variety were fixed so they are now properly attached to their proper console
-  Disposal was tested found a funny bug if things going to bar but was fixed.
-  Most discussion after testing was around station map layout and placement. Most of it was a mixed bag of seeing if something would work or not came down to needing larger test groups. More testing still needed non the less.
-  Although medical was questioned a bit further discussion and tested needed to see if it actually has any bigerish problems.

This is most of what I remember or tested not a full list of everything that happened and noted to fix, improve, or change. Map is coming together quite well from what I seen and seems to run smoothly even when local. Needs quite a bit more testing but I'm liking the direction of it.

**Comment by variableundefined** [comment]
Unfortunately, this PR will be closed. We already have other high pop map like Metastation and Deltastation, which has the advantages of being better known and maintained. 

However, even these two maps are barely kept up to date or maintained, and adding a fourth map will not help the issue. Even on TG where there is a much larger team, they have issues maintaining all map outside of Box, Meta and Delta, and Paradise with its smaller contributor base will most likely struggle even worse. 

The existing two maps are also not really popular compared to Boxstation, Paradiser are a conservative bunch. 

I appreciate all the works you've put into the map, but I feel it is better that we close the PR early so to not waste any more of your works.

**Comment by Twinmold93** [comment]
@variableundefined  A suggestion that was brought up was that rather than keeping stations around we don't use or maintain, we'd remove them, lowering the number of maps we have to 2 (Cyberiad and Ragnarok). MetaStation and DeltaStation, while having advantages of being better known, are not in fact maintained by our codebase, and if they were to be, require changes for each change outside the codebase just to keep it up to date, which also limits the capability to, to maintain standards to other servers that use said made, relying on those other codebases first (something we already don't maintain for).

I myself have been maintaining the map, but without addiitonal testing to be done on a larger scale, it is hard to see what additional changes need to happen or could happen, a map designed specifically for Paracode from the ground up. This map hasn't seen many yet, though those who have tested, after about 45 minutes, found it wasn't too difficult to work with, from initial testing. Of course Cyberiad is going to be more popular and easier to work with: We very rarely switch from it, because we currently don't maintain the other maps, and I personally don't see that changing to better support those maps (nor have I in a very long time, months or even a year).

**Comment by AffectedArc07** [comment]
F

**Comment by Couls** [comment]
Isn't it a little late for april fools?

**Comment by Aurorablade** [comment]
@variableundefined i do not feel this PR should have been closed as this map needed more testing and was in fact being maintained by twinmold.

**Comment by Mitchs98** [comment]
I concur with @Aurorablade

**Pull request closed without merging**
