### PR TITLE
Add mutadone autoinjector to Blueshield, HoS and Captain closet.

### PR DESCRIPTION
**Pull request by Anasari**
The only sensible solution to the debate we have on forums. Add a six-pack of mutadone injector to their closets with usage instruction. /S

🆑 
add: Mutadone Autoinjector to BS, HoS and Captain's closet.
/🆑

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
No disabilities allowed. :100: speedmerg

**Comment by Jovaniph** [comment]
This is not a sensible solution and can very well be abused. Autoinjectors work instantly and without warning. I rather not having a stealth mutadone injection while playing something not related to command or security.

**Comment by TullyBurnalot** [comment]
@Jovaniph *woosh*

**Comment by Jovaniph** [comment]
If this was a memePR I missed the joke entirely. I don't deserve to be forgiven =(

**Comment by TullyBurnalot** [comment]
*Loud gameshow noises*

**Comment by Jovaniph** [comment]
shh.

**Comment by taukausanake** [comment]
Honestly you wouldn't be alone @Jovaniph. I don't get half the meme PRs because to me spessmens in spess are serious bwuisness

**Comment by Spartan6** [comment]
Straightjacket-bola for the psychiatrist as well.

**Comment by tigercat2000** [comment]
ABLEIST SCUM!

**Pull request closed without merging**
