### PR TITLE
<span class='reallybig'>WHY ARE MEGAPHONES TINY ITEMS</span>

### PR DESCRIPTION
**Pull request by SamHPurp**
:cl: Purpose2
tweak: Increases the size of Megaphones.
/ :cl:

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
Code in a soapbox while you're at it.

**Comment by SirBloodBuske** [comment]
Craftable Paper bins when

**Comment by FlattestGuitar** [comment]
It's a change.

Log the change.

In a changelong.

**Comment by Spacemanspark** [comment]
Noooooo

**Comment by Spacemanspark** [comment]
Not my pocket scream machine
You monster
(It makes sense though. I guess)

**Comment by Tayyyyyyy** [comment]
If you want to expand this PR to be a general megaphone fix PR: you can hear megaphones in space.

**Pull request merged**
