### PR TITLE
BoxStation: Armory Remaped

### PR DESCRIPTION
**Pull request by DogeDogIs**
… Gamma Shuttle now docks with the Secure Armory.

The Secure Armory now have all items from non-secure Armory, and Gamma shuttles now docks directly with the Secure Armory. The non-secure armory was removed to make place for Gamma Shuttle.

This PR remakes the Secure Armory and removes the non-secure Armory, for better mapping, since all items inside the unsecured Armory were of good importance and at the same time, repositioning the Gamma shuttle to a better location, connected to the Armory, where it might make more sense.

## What Does This PR Do

The change is a benefit to the game as at the same time it makes the important items move, at the same time, the Gamma shuttle will go to a place that makes more sense to be connected, along with the Secure Armory. Placing some implants together with the Secure Armory also helps the Security Officers' work, making them not waste time for the AI ​​to open up to take, for example, a tracking implant for perma prisoners.

## Why It's Good For The Game

The change is a benefit to the game as at the same time it makes the important items move, at the same time, the Gamma shuttle will go to a place that makes more sense to be connected, along with the Secure Armory. Placing some implants together with the Secure Armory also helps the Security Officers' work, making them not waste time for the AI ​​to open up to take, for example, a tracking implant for perma prisoners.

## Images of changes

-- NEW CHANGES -- 
armory_new1
armory_new2
armory_new3

## Changelog
:cl:
tweak: Remaps BoxStation secure armory
del: Removes BoxStation non-secure armory
tweak: Gamma armory now docks with secure armory on BoxStation

/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
PR re-opened because I made a mistake in the last PR

**Comment by Coolrune206** [comment]
How is the Armory visibility from the Warden's office/Equipment room? Will this make it easier to break in from space?

**Comment by Miraviel** [comment]
I agree the gamma armory should dock with the secure armory, however, there is a tiny issue - what Coolrune said. This change greatly decreases the visibility of the warden's for the secure armory. Before the change, only one line of racks were invisible from the room, now one third of the armory is.

> How is the Armory visibility from the Warden's office/Equipment room? Will this make it easier to break in from space?

Current visibility:

image

New visibility:

image

Here are my ideas on how to improve it:

1. Remove these walls, they look cool against the suit storages, but they block visibility by a great degree. Replace them with racks, perhaps, and move some gear there. If you want to cater to antags, move the APC to the northern side of the armory; if they blow it up/disable it, the door between the warden office and the armory should depower, giving them a few seconds of advantage while the warden is looking for their crowbar.
2. If possible, bring down the whole thing at least one, preferably two tiles. The warden is currently unable to see 1/3 of the armory from the top of their office.
3. Make use of this tiny place. I doubt we really need handcuffs and an 18th flash... (secoffs already start with two). Feel free to move less important things here, maybe the L3 and L4 closets? Just make sure whatever you move here does not render the pepperspray refiller unreachable (or if they do, move the refiller a bit).
4. Feel free to move the secway to the warden's office. It's their toy, after all, and you get a free tile for the armory!

image

**Comment by DogeDogIs** [comment]
> I agree the gamma armory should dock with the secure armory, however, there is a tiny issue - what Coolrune said. This change greatly decreases the visibility of the warden's for the secure armory. Before the change, only one line of racks were invisible from the room, now one third of the armory is.
> 
> > How is the Armory visibility from the Warden's office/Equipment room? Will this make it easier to break in from space?
> 
> Current visibility:
> 
> image
> 
> New visibility:
> 
> image
> 
> Here are my ideas on how to improve it:
> 
> 1. Remove these walls, they look cool against the suit storages, but they block visibility by a great degree. Replace them with racks, perhaps, and move some gear there. If you want to cater to antags, move the APC to the northern side of the armory; if they blow it up/disable it, the door between the warden office and the armory should depower, giving them a few seconds of advantage while the warden is looking for their crowbar.
> 2. If possible, bring down the whole thing at least one, preferably two tiles. The warden is currently unable to see 1/3 of the armory from the top of their office.
> 3. Make use of this tiny place. I doubt we really need handcuffs and an 18th flash... (secoffs already start with two). Feel free to move less important things here, maybe the L3 and L4 closets? Just make sure whatever you move here does not render the pepperspray refiller unreachable (or if they do, move the refiller a bit).
> 4. Feel free to move the secway to the warden's office. It's their toy, after all, and you get a free tile for the armory!
> 
> image

Thanks for the ideias, I will make it now.

The handcuffs box are there because all armorys have to be standardized, so unfortunately some items are mandatory to be installed, I'll change the armory and see how I can improve it and visibility too, thanks for the feedback!

**Comment by DogeDogIs** [comment]
> Gamma armoury dock needs some solid walls on the left where the other door is, to stop people spacing themselves out of it.

Got it!

**Comment by AffectedArc07** [comment]
Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.

Please link your account at [https://www.paradisestation.org/forum/custom/link_github_account.php](https://www.paradisestation.org/forum/custom/link_github_account.php)

*If you are seeing this multiple times due to multiple PRs you only have to link once*

**Comment by DogeDogIs** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _If you are seeing this multiple times due to multiple PRs you only have to link once_

I linked the account

**Comment by AffectedArc07** [comment]
> > Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> > Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> > _If you are seeing this multiple times due to multiple PRs you only have to link once_
> 
> I linked the account

Label removed

**Review by S34NW — CHANGES_REQUESTED** [review]
image

Looking mostly good, please swap this APC and wall safe so the under-floor terminal is not under a scrubber.

image

Also please remove the external cam from the prison net, that net is for permabrig cams.

**Comment by DogeDogIs** [comment]
> image
> 
> Looking mostly good, please swap this APC and wall safe so the under-floor terminal is not under a scrubber.
> 
> image
> 
> Also please remove the external cam from the prison net, that net is for permabrig cams.
> 
> image
> 
> You have two directional windows here

image
image
image


Changed!

**Review by S34NW — APPROVED** [review]
Good to go

**Comment by Contrabang** [comment]
Just a nitpick but this area should be changed to something like the barrier grenades with in the 2nd screenshot with the bottom left being on the topmost layer and topright being on the bottom layer with about 2 pixels of shift between each object. It makes it much easier to tell how many objects are on a rack and able to pick up the one you want
image

image

**Comment by DogeDogIs** [comment]
> Just a nitpick but this area should be changed to something like the barrier grenades with in the 2nd screenshot with the bottom left being on the topmost layer and topright being on the bottom layer with about 2 pixels of shift between each object. It makes it much easier to tell how many objects are on a rack and able to pick up the one you want image
> 
> image

made!

**Review by S34NW — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Review by Contrabang — APPROVED** [review]
I want my stamp of approval on here too :)

**Pull request merged**
