### PR TITLE
Fixes some minor cyberiad issues

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Fixes https://github.com/ParadiseSS13/Paradise/issues/17022
Fixes perma arcade machine facing a wall
Fixes random floor tile in bar maints
Tweaks Ass. Line maint doors to use engi colours to telegraph their access.
Fixes https://github.com/ParadiseSS13/Paradise/issues/16332

## Changelog
:cl:
fix: Fixed various box station issues
/:cl:

### CODE REVIEW

**Comment by Adrer** [comment]
Hehe

> Ass line

**Comment by hal9000PR** [comment]
I don't see a reason for 2 random maint doors to have exclusively engineering access.

**Comment by S34NW** [comment]
> 
> I don't see a reason for 2 random maint doors to have exclusively engineering access.

It's the maint doors for assembly line, an engineer area

**Comment by hal9000PR** [comment]
> > I don't see a reason for 2 random maint doors to have exclusively engineering access.
> 
> It's the maint doors for assembly line, an engineer area

all maints are engineering areas. by this logic they should all be only engineering only. by the same logic, medmaints should be med access only. its not even like it leads into a room. its just a hallway. it makes no sense.

**Comment by S34NW** [comment]
> > > I don't see a reason for 2 random maint doors to have exclusively engineering access.
> > 
> > 
> > It's the maint doors for assembly line, an engineer area
> 
> all maints are engineering areas. by this logic they should all be only engineering only. by the same logic, medmaints should be med access only. its not even like it leads into a room. its just a hallway. it makes no sense.

I don't disagree, but this is not the PR to handle that. I am simply making the doors clearer so people don't bump into them going "why won't it open"

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
