### PR TITLE
Removes extraneous lattices from weird spots

### PR DESCRIPTION
**Pull request by Ar3nn**
:cl: Ar3nn
del: gets rid of those weird lattices north of the station
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
How the heck do you have *that* many merge commits on a brand new PR?

**Comment by Ar3nn** [comment]
Dear god what have I done.

**Comment by TheDZD** [comment]
Also, you didn't untick "Automatically set FILE_DIR" under Build > Preferences.

**Comment by Ar3nn** [comment]
kill it with fire its a monster

**Comment by Kyep** [comment]
Also: Stray lattices outside the external walls of the station are actually placed there deliberately to smooth the edges of the station. They're a feature, not a bug.

**Comment by Ar3nn** [comment]
Not the ones attached to the walls, the ones floating near the firing range.

**Pull request closed without merging**
