### PR TITLE
[WIP] Port two detective outfits based on Disco Elysium

### PR DESCRIPTION
**Pull request by datlo**
TODO : 
Species sprite for uniform (Grey, vox)
Species sprite for glasses (Grey, drask, vox)

Fixes for freeze : 
https://github.com/ParadiseSS13/Paradise/pull/17091
https://github.com/ParadiseSS13/Paradise/pull/17086
https://github.com/ParadiseSS13/Paradise/pull/17087

## What Does This PR Do

Port two detective outfits based off the detectives from Disco Elysium from tg/vulp. Sprites by D4n0w4r. 
Some of the descriptions/item names have been changed to fit the server better.
They are available in the detective's clothing vendor.

## Why It's Good For The Game

More customisation options are always welcome and the outfits, in my opinion, fit well into the setting.

## Images of changes

disco1

## Changelog
:cl:
add: Added two new outfits to the detective clothing vendor.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
1. Did you get explicit approval for this.
2. Where are your fix/refactor/performance PRs?

**Comment by datlo** [comment]
I didn't, I wasn't aware it was necessary considering I took the sprites from tgstation which is open source. I can look into it if needed, let me know.

https://github.com/ParadiseSS13/Paradise/pull/17091
https://github.com/ParadiseSS13/Paradise/pull/17087
https://github.com/ParadiseSS13/Paradise/pull/17086

I think one of those might not have registered with the system because it's been merged before the label was applied.

**Comment by Fox-McCloud** [comment]
The explicit approval is relating to the freeze---all feature PRs submitted during the freeze need explicit maint/head support.

The fix thing is one of those, please post the PRs in question so we can verify things.

**Comment by datlo** [comment]
Apologies, I wasn't aware I needed that. I'll close this for now and re-open this in the future doing it right, it turns out I'm going to be a little busy in the coming days anyway.

**Comment by datlo** [comment]
I hate having ADHD and being bad at sprites. Might revisit this, feel free to use for your own PR if you wanna finish it.

**Pull request closed without merging**
