### PR TITLE
Tristan1333 Stuff

### PR DESCRIPTION
**Pull request by tristan1333**
Adds a bunch of stuff. Throwing Knives, buff for Vox Hardsuits... Or more making it a proper hardsuit and the most important update of all, making berry juice from grapes.

### CODE REVIEW

**Comment by tristan1333** [comment]
The xeno police tape thing doesn't actually do anything. It improves the vox hardsuit to act slightly more realistically.

**Comment by Fox-McCloud** [comment]
No to the knife; the esword already has a throwforce of 20 and the syndicate cards fill the niche of "throw something at your enemies at range"; a throw force of 30 is going to nearly always break bones---we used to have virus snap pops that did this and it was pretty much one hit, one bone break.

Too much overlap with existing weapons (and edging into the meat cleaver) and way too overpowered.

**Comment by tristan1333** [comment]
Yeah I thought that, I'll revert the changes now. I tested the Syndicate cards... They're so weak, they're really not worth using. And the kit comes with 5, so y'know... The sword is pretty much irrelevant since you're not going to throw your precious sword at a victim :P. I totally agree on the overpowered part however.

**Comment by tristan1333** [comment]
@Fox-McCloud Ready to be merged

**Comment by Fox-McCloud** [comment]
I suggest you remake this PR, to be honest. There's 9 commits when only 5 files have been changed (and a 6th which is a spacing change). Also for the space suits, in particular, I suggest you take a look at their parent item; take note of the flags they do or do not have vs the flags the children you're modifying have. A lot of the changes you made here are redundant as the parent has it--and in some cases may even damage the aesthetic looks of the suit as they add unnecessary flags, which they don't really need.

For facehuggers, the only flag you care about is HEADCOVERSMOUTH; the suit that really needs changed in this case is  /obj/item/clothing/head/helmet/space/vox and the only thing that you'd have to add is the HEADCOVERSMOUTH flag and that's it.

**Pull request closed without merging**
