### PR TITLE
More Fudge Flavors

### LINKED ISSUE #4457: Fudge Recipe Bug
**Problem Description**:
Recipe for Fudge doesn't match wiki

**What did you expect to happen**: 
2 sugar, 5 cream, 1 chocolate barin candymachine = fudge

**What happened instead**:
An unholy abomination.  
Found out on the git,  it's 5 sugar 5 cream which is the same a Caramel.

**Why is this bad/What are the consequences:**
Cooking.

**Steps to reproduce the problem**:
Read wiki, compare to code, notice it's wrong.  Try to make it, get Caramel instead (if you follow the github recipe) or poopy cooking if you follow the wiki recipe.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing really...

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds 4 new fudge flavors!

image
From left to right: Normal fudge, Peanut fudge, Turtle fudge, Cherry fudge, Cookies 'n' Cream fudge

Recipes:
- Peanut Fudge:
 - Made with 5u milk, 5u sugar, 1 chocolate bar, and 3 peanuts
- Cherry Fudge:
 - Made with 5u milk, 5u sugar, 1 chocolate bar, 3 cherries
- Cookies 'n' Cream Fudge:
 - Made with 5u milk, 5u sugar, 5u cream, 1 chocolate bar, 1 cookie
- Turtle Fudge:
 - Made with 5u milk, 5u sugar, 1 chocolate bar, 1 peanut, 1 caramel

Also adjusts the standard fudge recipe
- Now 5u milk, 5u sugar, 1 chocolate bar
 - Fixes #4457

REMINDER: Fudge uses chocolate bars made via reaction, not the candy bars you make / buy from machines

:cl:
rscadd: Adds 4 new types of fudge for the chef to make: Peanut, Chocolate Cherry, Cookies 'n' Cream, and Turtle Fudge.
tweak: Normal fudge recipe now uses milk instead of cream.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

modularize fudge and make it reagent based fudge

CLF3 fudge

**Comment by Fox-McCloud** [comment]
>modularize fudge and make it reagent based fudge

I love me some sarin fudge.

**Comment by Iamgoofball** [comment]
exactly

**Comment by DaveTheHeadcrab** [comment]
Fractal fudge when?

**Comment by AceMcLazer** [comment]
New Cheft Title in pref screen: confectioner

**Pull request merged**
