### PR TITLE
Re-integrates noble clothing patreon reward.

### PR DESCRIPTION
**Pull request by PandaCG**
Re-integrates noble clothing seemingly accidentally removed in https://github.com/ParadiseSS13/Paradise/commit/78c67b9a1fa2b26a09fba859f324070c068810a3#diff-e7d3475367708b3b8aae5e2e41a8c07d. Never done a proposal before but hopefully I did it right!!

**What does this PR do:**
Fixes accidental removal of noble clothing from: https://github.com/ParadiseSS13/Paradise/commit/78c67b9a1fa2b26a09fba859f324070c068810a3#diff-e7d3475367708b3b8aae5e2e41a8c07d

**Images of sprite/map changes (IF APPLICABLE):**
N/A??

**Changelog:**
:cl:
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
Unfortunately, it doesn't look like we'll be able to re-add these.
Apparently they were removed from the patreon item list based on the wishes of the original spriter.

**Comment by AffectedArc07** [comment]
https://github.com/ParadiseSS13/Paradise/commit/b860fe72c9e889717653535ebfa333ff1c80cf0a#diff-69ecb4c2714234092304b94f764e2e0f

**Comment by PandaCG** [comment]
> Unfortunately, it doesn't look like we'll be able to re-add these.
> Apparently they were removed from the patreon item list based on the wishes of the original spriter.



> [b860fe7#diff-69ecb4c2714234092304b94f764e2e0f](https://github.com/ParadiseSS13/Paradise/commit/b860fe72c9e889717653535ebfa333ff1c80cf0a#diff-69ecb4c2714234092304b94f764e2e0f)
> 
> image

Do we know if it was just the admiral sprites or was it the noble sprites too?

**Comment by DarkPyrolord** [comment]
It was both of them

**Comment by PandaCG** [comment]
> It was both of them

That sucks :/ 
I figure re-making them entirely is out of the question in-case there's some form of copy prevention. It was a good try lads

**Comment by taukausanake** [comment]
I was wondering if that issue was related to those sprites. I was trying to figure out why the sprites still exist in the branch. I would think those would need to be removed if it's the _sprites_ that had the wrong license

**Comment by tigercat2000** [comment]
The original artist had some issues with allowing their sprites to be licensed under the terms of AGPL with another codebase, which means that any AGPL codebase can't really use them

**Comment by KasparoVy** [comment]
SHIT, hey @Spacemanspark are these the boots you used for that Kei Shen puss in boots cosplay that one time?

LMAO

**Comment by KasparoVy** [comment]
Almost flipped my lid because I thought the Noble Boots were going away lmao. Those are too awesome. I still remember Spark's old Kei'Shen puss-in-boots shenanigans

**Comment by PandaCG** [comment]
> Almost flipped my lid because I thought the Noble Boots were going away lmao. Those are too awesome. I still remember Spark's old Kei'Shen puss-in-boots shenanigans

yeah that's why I'm confused about the noble outfit in particular, if the boots still exist what happened with the actual jumpsuit?

**Comment by taukausanake** [comment]
So if no AGPL codebase can use them, shouldn't [both](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/clothing/suits/miscellaneous.dm#L856-L861) [items ](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/clothing/head/misc.dm#L437-L441)and the sprites themselves be removed completely?

**Comment by PandaCG** [comment]
I’d like to try and keep the boots considering they’re one of the best donor items, but it does make me wonder whether or not the noble outfit is properly unusable due to licensing or not. It existed up until Kyet accidentally (to their knowledge) removed it so I wonder if whoever was contacted about the admiral sprite answered improperly on behalf of the noble jumpsuit sprite :thinking:

**Comment by AffectedArc07** [comment]
@PandaCG 
Few things:
Alffd was the one that removed them, and it was by intention
image
PR: #8510

Licensing is tricky with any project, this being no exception. I am pretty sure (correct me if I am wrong) the staff dont want to deal with a license crisis / DMCA / C&D / any legal bullshit.

**Comment by PandaCG** [comment]
That merge only removes the admiral outfit, not the noble outfit. I can edit this pull request in a second to remove the admiral addition, I’m in mobile currently though so I can’t pull up the merge in which Kyet accidentally removed the noble jumpsuit, which has existed up until that point about a week or so ago

**Comment by PandaCG** [comment]
Edited the original post and the file changes.

**Comment by DarkPyrolord** [comment]
As far as I know only the coat and hat were the only things that were removed due to the licence. To the best of my knowledge the noble clothing was not part of the licence issue and is probably safe to merge.

**Comment by variableundefined** [comment]
I'd rather stay safe on this.

**Pull request closed without merging**
