### PR TITLE
Changes Mechanic's maintenance access to Mechanic only

### LINKED ISSUE #4811: Mechanic Workshop Maintenance
The second half of the Mechanic Workshop Maintenance has a major oversight in the latest Incinerator and Engineering Maintenance update as it allows anyone with Maintenance access to walk through. The problem with this as it literally lets anyone completely block access for pods in the mech workshop by just standing there in the middle even. Or going so far as a Clown or any Shittler would and build walls/move objects infront of it that permantely block the Mechanic Workshop without being removed.

Easiest way to fix this is to add Mechanic Workshop access requirement for those other two Maintenance doors to prevent people from blocking the pods completely from just leaving the Workshop.

### PR DESCRIPTION
**Pull request by FreeStylaLT**
img
These two doors are now mechanic access only.

Fixes #4811 

Why? Because this is the only instance of maintenance access going through an actual workplace without a proper lobby-like connection, like with Xenobiology/Toxin Mixing bits.

I also fully realize this change eliminates the ability for someone to walk through one maint right into another. Whether it is worth making this one exception to our maintenance mapping standards for fluidity in maint wandering is not up to me, but this has been raised as an issue, so a discussion is best to be had.

:cl: FreeStylaLT
fix: Mechanic's maintenance is now mechanic's access only.
del: Removed inner podlock from Mechanic
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
If those are mechanic only access now, might as well remove the inner podlock since that was only needed for preventing general crew from walking into the workshop from that part

**Comment by DaveTheHeadcrab** [comment]
Very much disagree, this cuts engie maint in half for no real reason, and as mentioned above the inner podlock exists for this exact reason.

**Comment by Taaketa** [comment]
Yeah. There is an inner podlock that prevents people entering the Mechanic's bay proper. I don't get why all the hate for this maint access.

**Comment by FreeStylaLT** [comment]
It was an open issue. I fix issues. If it turns out this isn't an issue and everyone agrees - then excellent, this can get closed along with that issue. No real biggie.

**Comment by Spacemanspark** [comment]
I don't view this as an issue.

**Comment by IcyV** [comment]
This change makes sense to me. I thought it was rather odd that maint suddenly got so much larger via connection through a workplaces area. It makes the airlock a rather dangerous or annoying thing to use when anyone can be in there at any given time.

**Comment by Doukhan** [comment]
It's the same consistency science/medbay get with their side-maint access, even then it's not really worth cutting off maint access IMO.

**Comment by Norgad** [comment]
OH MY GOD. As the person who made the maintenance expansion, I have explained way to many times that the extension to the garage should be treated as a maintenance area.

**Think of it like a footpath going across a driveway.**

Don't pack a hissy fit if someone blocks the pod's path either, there is a maintenance door so you can go around the pod door and clear the way.

**Comment by Fox-McCloud** [comment]
Don't really like this change either--I've...not really seen the "blocking off" behavior that is hypothetically possible.

**Comment by FreeStylaLT** [comment]
Well, then! I'd consider the #4811  a non-issue, then. Or at least something requiring a much bigger remap of either Mechanic or the maint.

**Pull request closed without merging**
