### PR TITLE
Fixes half the server crashing, removes canvases

### PR DESCRIPTION
**Pull request by Ty-Omaha**
Originally from: https://github.com/tgstation/tgstation/pull/39401 until I just fully deleted the files as tiger recommended

These cause so many people to crash all the time.

I would love for someone to be able to fix them but right now nobody has fixed them and we need to have not half the server crash

🆑 
del: Removes canvases due to everybody crashing from them.
/ 🆑

### CODE REVIEW

**Comment by Mitchs98** [comment]
Since when are people crashing from these? I've not seen them crash before and Squishy and I draw on it a lot o.o. Odd....definitely sad :/

**Comment by Ty-Omaha** [comment]
Everytime they are placed, probably something to do with the beta. But we cannot just alienate half of the server and tell them "go off the beta", that's not realistic

stupidgithubwhywontyouembedthisyourself


stupidgithubwhywontyouembedthisyourself

**Comment by Mitchs98** [comment]
Ah I see. Yeah I understand. I'm on beta and it doesn't effect me, but yeah I get your point. Hopefully it can be fixed soon, drawing while a hassle was pretty fun.

**Comment by variableundefined** [comment]
This has been approved by a head and a maintainer.

Merging.

**Pull request merged**
