### PR TITLE
Adds Modular Receivers to Loot Table and Hacked Autolathes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds modular receivers to the maintenance lootdrop table.

Also ports my own PR: https://github.com/tgstation/tgstation/pull/25401

Should provide for a few more interesting opportunities for maintenance dwellers to get their hands on a potential experimental weapon. Shoot your coworkers! Shoot your friends! Shoot the clown! Hell, shoot *everyone*.

This also adds receivers to the autolathe, albeit at a premium; making them will set you back 15,000 metal--yeah, they're not locked behind R&D anymore, but they won't be cheap. Receivers will no longer be available as a research item in protolathes/R&D.

:cl: Fox McCloud
add: Adds modular receiver to the maintenance loot system
add: Receivers can now be produced in hacked autolathes; no longer available in R&D protolathes.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Yessssssss. But how often you think this will drop?

**Comment by Fox-McCloud** [comment]
As often as you see emergency oxygen tanks, you'll see this.

**Comment by SigholtStarsong** [comment]
... So all of the freaking time?

**Comment by Lady-Luck** [comment]
I think he means emergency oxygen tanks that occur outside of O2 closets.

**Comment by Fox-McCloud** [comment]
>I think he means emergency oxygen tanks that occur outside of O2 closets.

Correct, the ones in maint.

**Comment by SamHPurp** [comment]
Twice as often as you find wirecutters. This is way to frequent... might as well give everyone guns.

**Comment by Lady-Luck** [comment]
There's a lot of wirecutters in maintenance because there's a lot of toolcutters in maintenance. Stray wirecutters aren't that common.

**Comment by Fox-McCloud** [comment]
went ahead and ported my own PR; receivers will now be a hacked item available in autolathes--no longer available in R&D.

Cost is now 15,000 metal, however.

**Comment by taukausanake** [comment]
Now all we need are more improvised gun constructions

**Pull request merged**
