### PR TITLE
Health Analyzer Upgrading

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in the ability to upgrade health analyzer; a rework of an existing system

- Health Analyzers no longer display reagents by default (neither negative nor positive)
- Health Analyzers can be upgraded with the aptly named "health analyzer upgrade"
 - Upgraded health analyzers will display ALL reagents in a mob and how much of that reagent

- Medvends start out with as many health analyzer upgrades as they do health analyzers
- Can research+produce more health analyzer upgrades at R&D

Huge huge big thanks and shout to Haine of Goonstation for letting us use the health analyzer upgrade sprites

Other
- Updates the slime scanner code
- Adds 2 slime scanners to the map in Xenobio
 - Slime scanners can tell you how hungry a slime is, its chance to mutate, age, what it can mutate into, and its chance of shocking you

### CODE REVIEW

**Comment by TheDZD** [comment]
Would it be possible to have the slime scanner also display the friendliness level of the slime? For clarification, I mean the friendliness level attained by feeding it plasma bars or KOing a monkey that it is eating.

**Comment by Fox-McCloud** [comment]
Looking at the code, it doesn't seem there's a friendliness level per say, so much as the slime tracks who is or isn't a friend; could be wrong though---not really dealt with slime code before.

**Comment by ZomgPonies** [comment]
Merge conflict

**Comment by TheDZD** [comment]
You are correct about it tracking friends, it does this in a list, and has object references that ALSO have numerical values. ([EG](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/metroid/metroid.dm#L561))

**Comment by Fox-McCloud** [comment]
merge conflict fixed

**Pull request merged**
