### PR TITLE
Newspaper re-sprite (lightens, colorizes)

### PR DESCRIPTION
**Pull request by FlimFlamm**
This commit updates "bureaucracy.dmi" with a recolored version of the "newspaper" sprite located within in "icons/obj/bureaucracy.dmi". Specifically the sprite is changed from gray and black (non color news-paper look) to a more modern white and black /w color headline and photo. This is the second sprite change in a series of informally planned PR's designed to improve the quality of news delivery in SS13.

This sprite is lighter and therefore more eye-catching, hopefully not too bright either...

EDIT 2: pushed third commit to fork. Attempt to satisfy my desire for some contrast and the desire of others for old-school looking papers

news33

Side by side comparisons of old and new sprites (respectively) seen above.

### CODE REVIEW

**Comment by KasparoVy** [comment]
I thought the dingy greyed out traditional newspaper sprites looked excellent, but I guess it's all down to personal preference. The coloured one looks sweet, too.

**Comment by Nienhaus** [comment]
Newspapers do have colour normally now on the front and stuff, it's just dull a lot of the time though. I think the white background actually helps it from not looking to bright. However you used solid black for the outlines which is normally a big no-no. Switch that to the same gray as the text.

**Comment by FlimFlamm** [comment]
@Nienhaus I can see exactly what you mean with the black border issue. Is this a bit better?

@KasparoVy I don't dislike the newspaper sprite, but I loathe how it blends in so blandly with the common gray station floor. The design of the sprite is pretty good though, all credit to them; all I did was use the painting tool... (Dave El-Headcrab updated it last year if my Git interpretation is correct)

**Comment by Nienhaus** [comment]
Looks great.

**Comment by Fox-McCloud** [comment]
Bit iffy on this one, to be honest. On one hand, it does look ok, but on the other, I'm kinda with @KasparoVy the drab dingy look is kinda the stereotypical newspaper most people are used to--that and and kinda wonder which fits better with SS13's "retro 80's space theme" better.

**Comment by FlimFlamm** [comment]
@Fox-McCloud I can see what you mean about the dingy aesthetic. The main thing that still bugs me about the current newspapers are that they blend in too well with the floor.

For now, I pushed a very minimally modified version of the old sprite to preserve the old-school style while making a slight difference to visibility. (it emulates old school news-papers which used red-ink in logos)

news3

My heart isn't set on modifying the existing newspapers so much as it is on improving news delivery overall. I'm hoping to get into modifications to the newscaster code itself in the near future if I can decipher enough paracode (adding a header field for newscasts, time-stamps, and options for selecting which feeds to print), so maybe when I do finally get into that I will try and make an option for selecting between various newspaper sprites. 

P.S, i know you're legend code wise, got any coding resources/info you could point me to?

**Comment by Fox-McCloud** [comment]
>P.S, i know you're legend code wise, got any coding resources/info you could point me to?

Just the usuals: http://www.byond.com/docs/guide/ http://www.byond.com/docs/ref/
https://github.com/tgstation/tgstation/blob/master/CONTRIBUTING.md

**Pull request merged**
