### PR TITLE
Removes Secborgs, ports -tg- peacekeeper borgs

### PR DESCRIPTION
**Pull request by tigercat2000**
https://github.com/tgstation/tgstation/pull/17355
https://github.com/tgstation/tgstation/pull/18209

```
It has the following modules:
Flash
"Harm Alarm" that confuses in normal use,
Cookie dispenser (That does not have to be on the borg, as it can work outside of a borg"
Chem injector to confuse but not outright stun people.
It can also make fragile energy barriers (Goes down in 1 hit, might be too fragile, but we'll see)
Hug module.

When emagged:
Energy barriers electrocute on touch with a 1 second cooldown
Chem injector with knockout/knockdown drugs
"Harm Alarm" becomes a stunning changeling shriek.. .only it also stuns changelings!
Hug module gains "shock" and "crush" modes. These have a relatively high power cost and a slight cooldown.
Cookie dispenser can be hacked to put a delayed varient of Chloral Hydrate in them.

Thoughts comments concerns?
```

cute
so cute

### CODE REVIEW

**Comment by Vivalas** [comment]
10/10 (hoping this is a joke)

**Comment by Ar3nn** [comment]
Not gonna lie, the sprites look cool, but yeah, this is totally a meme.

**Comment by Vivalas** [comment]
Well there was a rediculous suggestion on the forum to actually remove sec borgs and add these things.

**Comment by Earthdivine** [comment]
Thats adorable. I want it.

**Comment by Spacemanspark** [comment]
Oh, I'm sorry, I didn't give the sprite proper justice.
Walking /cat eared/ eggplants.
That said, I'm willing to try these if you keep secborgs. No reason not to, I suppose.

**Comment by Vivalas** [comment]
It would be funny to add these without removing secborgs, I would meme around with these in game.

**Comment by TheDZD** [comment]
For those of you that are too lazy to check files changed, or read into the comments...

**Comment by Ar3nn** [comment]
Not even that, just read the name of the branch it came from :^)

**Comment by Davdichan** [comment]
I ree'd

**Pull request merged**
