### PR TITLE
Big Bad Bag Re-Sprite and Redundancy Reduction

### PR DESCRIPTION
**Pull request by Agameofscones**
This PR is very simple, I have made new sprites for all bags that were just a recolor of the mining satchel (Because that's very lazy 'spriting')

image
Left being the new sprites, right being the old sprites and references used.
image

Both the storage implant and mining satchel do have an animated bluespace pocket.

The new descriptions are:
Book Bag: `A bag of books, and by extension, the deepest lore and knowledge of all things. Ever.`
Mining Satchel: `A rugged, if limited space satchel for ore transport.`
Plant Bag: `A large sack for moving around anything and everything a botanist can and could make, namely: plants.`
Portable Seed Extractor: `A handheld seed extractor that can, by its namesake, extract seeds from the inserted contents.`

Mostly done with heavy input & suggestion from @R1f72r  and a few passing comments on the para-discord. Thanks lads, I really appreciate the input. **Speaking of which if you want to see one of these sprites changed, have at it in the comments, I will happily make edits.**

:cl:
add: New sprites for bio-bag, plant bag, portable seed-extractor, mining satchel, mining satchel of holding, storage implant, and chem-bag
add: New description for the bio-bag (now bio-box), portable seed-extractor, mining satchel, and book bag
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
:snowflake: 🛑 🙅‍♂️ :snowflake:

**Comment by Agameofscones** [comment]
I am well aware of the feature freeze and have already contributed a few bug fixes, as explained that fixes could be 'exchanged' for feature PRs

**Comment by RichardJones1** [comment]
Looks nice
Have you done there  sprites for them?
Btw plantbag looks a bit weird

**Comment by R1f72r** [comment]
I obviously like it, so weh!

**Comment by Crazylemon64** [comment]
Could you cite the fixes you are "spending" for this PR?

**Comment by Agameofscones** [comment]
Sure https://github.com/ParadiseSS13/Paradise/pull/9471 which I realize I implemented really sloppily and am currently refactoring with smarter implementation.
https://github.com/ParadiseSS13/Paradise/pull/9429 This dead pixel.
Not much of course, if more is needed I'll gladly go hunt up some things I can fix

**Comment by Agameofscones** [comment]
@RichardJones1 I have not done in hand sprites for them yet no, I should surely get on that.

**Comment by Taaketa** [comment]
Aren't you supposed to get approval before submitting any PRs that aren't fixes?

**Comment by Birdtalon** [comment]
I thought it was at maintainer discretion whether things counted or not?

**Comment by Agameofscones** [comment]
Considering that only an outline was given of how the system would work and no concrete rules were ever placed down I have _no idea either_ so really this is a big shot in the dark.

**Comment by Fox-McCloud** [comment]
The problem I have with these:

- Some of these imply they're already holding something, when they're not
  - Medical bags don't come with pill containers by default. nor bottles or patches.
  - Likewise, plant bags don't have produce in them

- Bags being consistent is a *good* thing. It implies universal behavior. Right now players can look at a bag, and if they understand the function of one bag, go "Oh, this must rapidly pick up, hold, and drop some type of material"

This PR really unhinges that. While there are pre-existing items that violate this (Trash bag and food tray), these are usually so grounded in real life, they're just organically understood to function in a certain way; not so much for these.

I'm 👍 for the implant icon, as it's not....a bag at all, but I think all storage bags need to essentially be the same, structure wise, with minor variations to them.

I'm not saying there can't be improvements made (these sprites are pretty old), but consistency is needed for design reasons.

**Comment by Agameofscones** [comment]
Going to close and open a new PR with just the implant icon.

**Pull request closed without merging**
