### PR TITLE
Atmos techs can get minerals and touch engineering equipment now

### PR DESCRIPTION
**Pull request by Crazylemon64**
Yup

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Don't personally think this is necessary, especially the minerals---not even engineers get that; only the CE.

That's my opinion though.

**Comment by Regen1** [comment]
No, atmos techs != Engineers

**Comment by CrAzYPiLoT-SS13** [comment]
I agree that the atmos techs need more access but minerals, no.

**Comment by TheDZD** [comment]
Yeah, this really isn't necessary, because at that point they're bordering on being engineers with better (*cough* legitimate *cough*) access, but without the responsibility of being CE.

**Comment by Crazylemon64** [comment]
Alright, I'll shut this down!

**Pull request closed without merging**
