### PR TITLE
UwU disability

### PR DESCRIPTION
**Pull request by FlattestGuitar**
## What Does This PR Do
Adds an UwU disability. I can make this a toggle in prefs to help support player choice in building their characters.

## Why It's Good For The Game
It's funny.
It's not an april fools joke. I actually want this added permanently.
With the playerbase being mostly furries, weeaboos or Americans I think this is more relevant than swedish or chav mutations.

## Images of changes

A single run is around 0.0000175s, so don't worry about regex performance.

Flatty
:cl:
add: Your genes got a lot more uwu
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
`uwu: 0.0389999 ms`
For 1 iteration of the proc, which is fine. I just dont like BYOND regex from the issues its had in the past.

**Comment by S34NW** [comment]
more regex disabilities is good, also how could you defame chavs like that.

**Comment by FlattestGuitar** [comment]
@AffectedArc07 

I'm not sure what you're talking about outside of the one version of BYOND that could crash when regex was used on a linux-hosted DD. 

Can you lay out the concerns you have here?

**Comment by AffectedArc07** [comment]
> @AffectedArc07
> 
> I'm not sure what you're talking about outside of the one version of BYOND that could crash when regex was used on a linux-hosted DD.
> 
> Can you lay out the concerns you have here?

I was under the impression regex was unstable from all the issues it used to have with our code, and we were running on windows at the time.

However, if this PR is merged, this is a better solution than the rust one since this wont insert unicode faces into chat, and the rust one did.

**Comment by S34NW** [comment]
> 
> 
> > @AffectedArc07
> > I'm not sure what you're talking about outside of the one version of BYOND that could crash when regex was used on a linux-hosted DD.
> > Can you lay out the concerns you have here?
> 
> I was under the impression regex was unstable from all the issues it used to have with our code, and we were running on windows at the time.
> 
> However, if this PR is merged, this is a better solution than the rust one since this wont insert unicode faces into chat, and the rust one did.

the rust one converted all sentences to sentence case, so you cant type in all caps or use any caps apart from the first letter

**Comment by SabreML** [comment]
Since this is apparently meant to be taken seriously:

This would maybe work as a way for admins to smite someone as a cluwning alternative or something, but as a roundstart disability choice (Or even a genetics SE) this will just get abused into oblivion and *massively* decrease the RP standard on the server.

**Comment by Wojz** [comment]
I could not think of a less RP friendly addition than this. Our standards are already low. This is literally just memespeak.

**Comment by FlattestGuitar** [comment]
To respond to some criticism:
- There is absolutely nothing stopping you from talking this way if you want to already. This will not make people give themselves the disability, because that provides no advantage whatsoever, outside of maybe typing being a little bit easier.
- This is a genetic disability, it's meant to be funny and it's a reference to cultural artifacts the playerbase is already familiar with. Things like funny swedish speak, the hulk mutation and gaining the ability to eat tables don't take you out of the experience because they're a part of the world and your suspension of disbelief can absolutely handle them.

**Comment by markop-wd** [comment]
Speaking only from a player perspective - while I find this mutation really funny I have to concede with lowering the RP standards point, this is not in line with the server trying for the MRP status.

**Comment by TheYeetster1** [comment]
> Since this is apparently meant to be taken seriously:
> 
> This would maybe work as a way for admins to smite someone as a cluwning alternative or something, but as a roundstart disability choice (Or even a genetics SE) this will just get abused into oblivion and _massively_ decrease the RP standard on the server.

Definitely agree this should only be an admin smite thing.

> * There is absolutely nothing stopping you from talking this way if you want to already. This will not make people give themselves the disability, because that provides no advantage whatsoever, outside of maybe typing being a little bit easier.

Correct me if I am wrong, but I'm pretty sure most admins would stop you from speaking this way.

I think this is something that is generally not wanted on the server, Cat ears have already been removed because of poor RP gimmicks it caused and having a round start, or genetics option to obtain this disability would just encourage people to play in a similar fashion that we have already deemed unwanted.

On a personal note, uwu speech outside a meme makes me a little uncomfortable, and during the April 1st fools day PR many people were just attacking vulps when they spoke. 

Just to reiterate, I am for adding this as an admin smite thing, it sounds quite fun. Just against having it as a genetics or preference disability.

**Comment by FlattestGuitar** [comment]
I think those are fair points, @TheYeetster1.

I'm closing this PR.

**Pull request closed without merging**
