### PR TITLE
Nuke disk change

### PR DESCRIPTION
**Pull request by realtaac**
**What does this PR do:**
This PR changes the nuke disk to a better icon that does not look like a plant disk.

**Images of sprite/map changes (IF APPLICABLE):**
nuke disk
nuke disk final

**Changelog:**
:cl:taac
imageadd: added new nuke disk
imagedel: old plant based nuke disk
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Obsoleting all the get dat fukken disk memes

Not worth it!

**Comment by datlo** [comment]
I feel like the nuclear disk is more iconic than plant disks and the plant disks should be changed instead.

**Comment by Fox-McCloud** [comment]
As I told you when you asked.

The Nuke disk is *iconic* at this stage. Changing it isn't a good thing.

Also the plant disk is distinctively different from the nuke disk; it's entirely green, all over; the nuke disk has a white label.

The two are not the same. Similar, but not the same. A better change to plant disks would be to use the same green disk, but use the genetics animation on it (which are DNA strands) instead o the nuke one.

**Comment by realtaac** [comment]
the current nuke disk has atleast what I see as a nuke disk has a DNA icon. Also I tried to have a nuke logo however it is pretty much impossible to made in pixel art of this res. and fox I posted this PR then you contacted me to reply to my question.

**Comment by Citinited** [comment]
You could probably do a crappy trefoil by arranging three black dots in a triangle shape, on a yellow background... but I agree with others that the disk shouldn't be changed as it's very very easily recognisable and an icon of the game.

**Comment by TinnCatt** [comment]
I dunno, I really like it! 
Make something new to be iconic, y'know? Why completely follow what everyone else does.

**Comment by taukausanake** [comment]
This gets a downvote from me because as Fox put it that disk IS iconic. That being said, you _could_ get away with slightly modifying it.
> the current nuke disk has atleast what I see as a nuke disk has a DNA icon

It's more of a "data" icon and not so much DNA but if you kept the same colors and changed the "DNA" icon on it to the 'N' you have here I think it might work. You can't change the colors but maybe changing the icon on the disk could work.

What should really be done after this PR whenever it is merged or not is to make sure no other disks share the nuke disk icon. Make them all different.

I've only seen so many "get dat fukken disk" memes that use the current disk icon. The most noticeable of these images is [this one](https://img.fireden.net/v/image/1487/38/1487381520445.png) and I don't even know where that disk came from. If this image isn't the more "iconic" get dat fukken disk then I don't know what other ones are

**Comment by Fox-McCloud** [comment]
>Why completely follow what everyone else does.

You work for Butttrasen now then. Oh and the Syndicate is a fanatical mayonnaise lobbying organization that wants to nuke Buttrasen because of their ban on mayo.


My larger point:

Having a consistent base underlying theme allows you to build on something, and icons and established tropes helps us build on that; certain things are going to become established to what people believe is the "core' of SS13. This can and will shift over time, but a number of things are probably not going to change much when it comes to stuff that has achieved the "iconic" status.

**Comment by Mitchs98** [comment]
While I like the sprite. Disk should stay as it is. It's always been that way, and as stated it's an iconic thing to SS13. If anything, as said, the plant disks should be chosen if your issue is with plant disks being the same color/similar as the nuke disk.

**Comment by Spartan6** [comment]
While I do agree the two look very similar, this isn’t the way to go about it. Change the plant disk, not the nuke disk.
But the sprite does look good. If it weren’t such an iconic item, I’d be for this.

**Comment by realtaac** [comment]
I'll find another use for this sprite. maybe a new tech data disk but it is already very obvious this gets a no go.

**Pull request closed without merging**
