### PR TITLE
New Lavaland Ruin And Language Book

### PR DESCRIPTION
**Pull request by Leanfrog**
## What Does This PR Do
This PR introduces a new ruin to lavaland with the goal of adding flavor to the experience as well as introducing a new single use book that teaches the Unathi language.

## Why It's Good For The Game
The ruin adds to the "story" of lavaland making the whole situation feel less "gamey", the addition of the book will allow for more potential interaction between Ash Walkers and miners.

## Images of changes
Screenshot (20)

## Changelog
:cl:
add: New lavaland ruin containing notes and a unique tome
add: A new tome that teaches the Unathi language
/:cl:

### CODE REVIEW

**Comment by Quantum-M** [comment]
I think the concept to the ruin sounds interesting.

Some suggestions I have though, is maybe adding more decorative things?

E.g. wooden chairs, candles (either unused or melted), more wooden tables around and so forth.

**Comment by Fox-McCloud** [comment]
Adding an entire ruin just to give a single language isn't great.

Ashwalkers are largely supposed to be antagonistic in nature--they're not generally supposed to be someone you just make rainbow and pony cutouts with---and this pushes them more in that direction.

Also, re-using the sprites from the ashwalker base like this and making it this large---again, for a singular book....is not great.

**Comment by Leanfrog** [comment]
Hm, I see what you're saying, I felt like adding a ruin that was more flavor based than mechanically based would be good for the overall feel of lavaland, from my experience and other's lavaland is basically just a powergamer's dream, it doesn't have any inherent reasoning as to why it exists other than being "The place you go to dig rocks and hunt monsters", I've been as of late working on giving lavaland a proper story to it, making it more fitting in the game world, I know lore isn't something of focus at all, but I honestly feel like it would improve the general air around lavaland.

In regards to the language and making friends with the ash walkers, myself and several others have found ash walkers to be a generally unfun experience, you either ignore each other or you kill each other, and unless you the miner make the first attack, you're leaving yourself at risk, being able to talk with them imo would allow for some actual interaction that isn't just complete disregard or valid times would allow for some more interesting experiences.

The reason for using the ash walker textures is that in the story I'm building it was built many hundreds of years by the ancestors of the current Ash Walkers, like I said earlier I've been working on expanding what Lavaland is, this only part of a larger story I've been hoping I could properly introduce over time.

**Comment by MRgaty** [comment]
> In regards to the language and making friends with the ash walkers, myself and several others have found ash walkers to be a generally unfun experience, you either ignore each other or you kill each other, and unless you the miner make the first attack, you're leaving yourself at risk, being able to talk with them imo would allow for some actual interaction that isn't just complete disregard or valid times would allow for some more interesting experiences.
> 
I think ashwalkers are supposed to do that, like valid miners aka invaders, hunt beasts for the tendril and go unga unga.

**Comment by variableundefined** [comment]
Concurs with Fox above, second objection.

Closing PR.

**Pull request closed without merging**
