### PR TITLE
Access Giveth, Access Taketh Away

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Giveth:
-Magistrate is granted power to the RC announcements. Will need one adding to their offices in a mapping PR for full utilisation.

Taketh away:
-The Nanotrasen Representative, HoP and Blueshield can no longer waltz into the Detective's office

## Why It's Good For The Game
People should have access that makes sense for their job duties.

## Images of changes
image

image

## Testing
See above images

## Changelog
:cl:
tweak: Magistrate can now use RC announcements
tweak: NTR, HoP and BS have lost detective's office access
/:cl:

### CODE REVIEW

**Comment by Dafrek** [comment]
Is evidence included in the access removed for heads of staff? If not it might be worth considering taking it away from general heads of staff since it doesn't make much sense for most heads to have access to any contraband that sec has locked away.

**Comment by Christasmurf** [comment]
> Is evidence included in the access removed for heads of staff? If not it might be worth considering taking it away from general heads of staff since it doesn't make much sense for most heads to have access to any contraband that sec has locked away.

No, evidence is due to the doors being set to normal brig access so normal command and IAAs can walk in there as they have access to all the basic doors. This would require a mapping PR to change the access on the doors to something only security members have (like prison/cell timers).

**Comment by ATP-Engineer** [comment]
Can you also make it so detective has medbay/Cloning access on farragus so they can actually reach morgue?

**Comment by Christasmurf** [comment]
> Can you also make it so detective has medbay/Cloning access on farragus so they can actually reach morgue?

Again, a mapping issue. The detective shouldn't need to be given medical/cloning access across all maps just so they can access the morgue on one of them - The morgue on Farragus should be in a place where they can access it from a public area, as it is with the other maps.

**Review by Sirryan2002 — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
