### PR TITLE
Adds 4 new IPC screens: Scanline, RGB, Glider, and Console

### PR DESCRIPTION
**Pull request by Crazylemon64**
scroll_screen
rgb_screen
glider_screen
console_screen
I thought I'd try my hand at spriting, here's a few new IPC screens.

In order, they are: Scanline, RGB, Glider,  and Console.
The last three are going about 10x as fast as they will IG because I couldn't figure out how to get DM to export the frames with the delays as a gif.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:+1:

**Comment by Spacemanspark** [comment]
:+1: x :100:

**Comment by orelbon** [comment]
:+1:

**Comment by Crazylemon64** [comment]
I added a fourth: Glider: glider_screen

**Comment by Plotron** [comment]
I'm lovin' the references.
Especially the Glider.

Visually, I find Console and RGB appealing.

**Comment by Crazylemon64** [comment]
I'm grayscaling most of these so they look good on a colored IPC; the problem with most screens is  that they get tinted along with the rest of the head, so stuff like nature and shower become unintelligible. Hopefully these see good use!

**Comment by orelbon** [comment]
lol i hope no one gets a seizure from RGB

**Comment by Crazylemon64** [comment]
@orelbon It's a very slow pulse, the screen switches every 1-2 seconds

**Comment by orelbon** [comment]
ah right its slower in game.

**Comment by Spacemanspark** [comment]
Yippie.

**Pull request merged**
