### PR TITLE
Add slot_collar, remove simple_animal add_inv/remove_inv

### PR DESCRIPTION
**Pull request by tigercat2000**
This is being done to remove the simple_animal/Topic() override, because that broke default languages.
Somehow also fixes using the language prefixes. Not sure what I did, but hey!

### CODE REVIEW

**Comment by fludd12** [comment]
Sometimes code is magic.

**Comment by taukausanake** [comment]
And for a second I thought this was either a meme PR and/or was giving Vulpkanins and Tajarans a collar inventory slot. Am disappoint but fixes are nice

**Comment by Spacemanspark** [comment]
Vulp don't need anything remotely resembling a collar slot.

**Comment by taukausanake** [comment]
Mine does. I put her ID on her collar on her suit and security is always giving me shit about it. Got to code in HUD support and machine verification for that one day...

**Comment by Spacemanspark** [comment]
No.

**Pull request merged**
