### PR TITLE
Adds a jobs board to the newscaster

### PR DESCRIPTION
**Pull request by SamHPurp**
This adds a jobs board, that lists what jobs are available through the Newscaster. No longer (hopefully) should people enter the HOP line saying "I'm a doctor, engineer and world renowned scientist!" they can enter the queue and proudly say "gimme dat Janitor job you got going".

I'm still wrestling with the CSS, because 50% of the time it ignores my styles entirely.

:cl: Purpose2
add: Adds a jobs board to the Newscaster. See what roles are available before seeing the HoP!
/ :cl:

### CODE REVIEW

**Comment by deep-fried-faceplant** [comment]
Could we get pictures of the UI?

**Comment by Fox-McCloud** [comment]
Is this still WIP? Working on it still? Given up? Ready to review?

**Comment by SamHPurp** [comment]
@Fox-McCloud  It /works/ and can be reviewed and implemented... but it does physically look dull, its literally just a list. My CSS abilities are abysmal.

**Comment by Fox-McCloud** [comment]
Mind posting pics?

**Comment by SamHPurp** [comment]
@Fox-McCloud 

image

image

**Comment by Fox-McCloud** [comment]
That honestly looks fine to me, for what this is.

**Comment by SamHPurp** [comment]
@Fox-McCloud alright. I'll probably improve its aesthetic in a followup PR sometime in the future when I can stomach CSS again.

**Pull request merged**
