### PR TITLE
Build time for aquariums

### LINKED ISSUE #13809: Fulltile windows, directional windows, wall aquariums, and fish tanks can be made instantly
**Issue Description**:
As said in the title, anything it seems with glass can be made instantly, allowing for people to make an instant barricade blocking pursuers.  This is the reason instant table construction was nerfed.

**What did you expect to happen**: 
For there to be a timer attached to building anything glass related.

**What happened instead**:
Instant barricades against people chasing the builder preventing people from following/shooting them.

**Why is this bad/What are the consequences**:
As said above, it is horrible balance wise and the reason tables/racks were nerfed with the build timer long ago.

**Steps to reproduce the problem**:
Get glass, run, build anything glass related while running in a chokepoint.  Profit.

**When did the problem start happening**:
Since forever, just never really realized until now.

**Extra information**:

### PR DESCRIPTION
**Pull request by TDSSS**
## What Does This PR Do
This adds a short build time for fish bowls and aquariums, fixes #13809

## Why It's Good For The Game
You can't flee from sec and instantly drop dense items behind you to stop people chasing you. 

## Changelog
:cl:
tweak: fish bowls and aquariums now take some time to make.
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
How much time exactly? 

Personally ive never seen them used in such a way but i can imagine them doing so, but the time is not going to be as long as building a wall segment is it?

**Comment by TDSSS** [comment]
It's deciseconds, so 40 means 4 seconds I believe. It's definitely a very short amount of time for all of them.

**Comment by Carthusia** [comment]
ahh alright, its basically no time at all, but just long enough to make it not a viable tactic to drop in the middle of a chase due to you needing to stop at all.

**Comment by Drobe50** [comment]
What about inflatable walls and doors? Those can be used to instantly create a barrier to escape from someone.

**Comment by TDSSS** [comment]
IMO, those are a lot less abusable. It's trivial to get a stack of 50 glass and have more instant windows than you'd ever need, but inflatable walls are a lot less common.

**Comment by Carthusia** [comment]
You can also just pop the inflatable ones

**Comment by procdrone** [comment]
inflatable wall takes few seconds to deflate

**Comment by Carthusia** [comment]
Really? I thought you could just shoot them or stab them and they pop?

**Comment by Fox-McCloud** [comment]
Fishtanks make sense, but windows start off unanchored, are easy to decosntruct, or can easily be rotated; they take time cause trouble---so I kinda raise an eyebrow at this, I guess, unless you've actively seen this abused quite often.

**Comment by procdrone** [comment]
> could just shoot them or stab them and they pop?

Alright I tested it quickly and appears my knowledge on inflated walls is outdated. Previously when you used a screwdriver it would PUNCTURE the wall and it would deflate after few seconds. now, you can smack it more(need to cause enough damage), but it deflates immediately.

**Comment by TDSSS** [comment]
PR has been updated to remove the changes to windows. It's only fish bowls and aquariums that have a buildtime.

**Pull request merged**
