### PR TITLE
Fixes Derp Fox

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Actually, derp fox cannot be fixed, but: https://github.com/ParadiseSS13/Paradise/issues/1923 can.

### CODE REVIEW

**Comment by Nienhaus** [comment]
There is a way to fix derp fox, but it's the same way you'd "fix" deer >:C

**Comment by Spacemanspark** [comment]
RIP Fox.

**Comment by KasparoVy** [comment]
rip aeronuatics

**Comment by NTSAM** [comment]
rip focks micclud

**Pull request merged**
