### PR TITLE
Adds Hissing Emote for Unathi

### PR DESCRIPTION
**Pull request by KasparoVy**
Original PR by @TravellingMerchant. Just a re-up of their PR and all credit is theirs to have
:cl: Travelling Merchant
rscadd: Adds a hiss emote for Unathi.
/:cl:

Adds a hissing emote that sounds like a large lizard, or crocodile.
https://www.youtube.com/watch?v=O3icLHTmLcE&feature=youtu.be

Original sound from http://www.freesound.org/people/Jamius/sounds/41531/ with the "attack" game like sound effect edited out. It is free to use and edit.

It is used with *hiss and *hisses, with its *hiss-(mob) line too.
Prints "Unathi1 hisses." and "Unathi1 hisses at DudeA." in chat, respectively.

### CODE REVIEW

**Comment by tigercat2000** [comment]
you somehow have a lot of unrelated commits on this branch

**Comment by KasparoVy** [comment]
Interesting. Perhaps I should've disabled edits from maintainers.

**Comment by KasparoVy** [comment]
There we go.

**Comment by TravellingMerchant** [comment]
The same thing is happening on my other PR? Strange commits

**Comment by SamHPurp** [comment]
I realise its really hard to get a good hiss, but I'm not really a massive fan of this one either.

**Comment by Rurik123** [comment]
Im not much of a fan either, but with relatively low volume and positional audio it should come off as just a generic average hiss.

**Pull request merged**
