### PR TITLE
New Fox Sprites

### PR DESCRIPTION
**Pull request by DarkPyrolord**
As said in the title, new fox sprites which have been made by FullofSkittles, not much else to say about this PR but the updated sprite will be on show in the gif below.

🆑 DarkPyrolord
add: Brand new fox sprites provided by FullofSkittles.
/🆑

### CODE REVIEW

**Comment by PhantasmicDream** [comment]
Aww I didn't know Fox McCloud could look so cute.

**Comment by davidchan13** [comment]
Updating Renault, the pet that is literally forgotten by everyone, before Ian? For shame.

**Comment by Ty-Omaha** [comment]
I don't like how when sitting it looks like the fox plushies

**Comment by DarkPyrolord** [comment]
> I don't like how when sitting it looks like the fox plushies

I wonder how many people would be fooled by that now... I must test this.

**Comment by ID404-NotFound** [comment]
can they be single frame? it's weird to be animated so much...

**Comment by KasparoVy** [comment]
Most of our other mob animations have numerous frames. This doesn't stick out at all in that regard

Blessed sprite

**Comment by ID404-NotFound** [comment]
What over stuff uses so many frames? I'm actually curious

**Comment by Aurorablade** [comment]
Some Borgs, Nymphs, some game machines, The bar sign, Cats i think, Mushroom mobs from botany, Swarmers, i need to look the others up...OH DRONES..

**Comment by KasparoVy** [comment]
Blobs, otherthings, humanoids with tails, Poly, some pAIs

**Comment by ID404-NotFound** [comment]
I'm talking more than 2 frames

**Comment by KasparoVy** [comment]
Yes, we are talking more than two frames. :thinking:

**Comment by Fox-McCloud** [comment]
@DarkPyrolord please make sure these work with collars.

**Comment by taukausanake** [comment]
So you basically gave life to the fox plushies. This does look nice and all, but I think I like the old sprites more

**Comment by variableundefined** [comment]
@DarkPyrolord Hello. I'll be closing down PR that is not merge-ready to clean up the issue tracker. The only issue we have is that the pet collar is not reflected properly. If this can be addressed the PR should be re-opened and will be merged in quickly (If it is ready codewise). I am no expert in sprite, but perhaps investigating overlay on an animated plushie might be possible.

**Comment by KasparoVy** [comment]
RIP superior sprite

**Pull request closed without merging**
