### PR TITLE
Resprites suit storage units to 3/4 perspective

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Takes the sprites from https://github.com/shiptest-ss13/Shiptest/pull/500 and https://github.com/shiptest-ss13/Shiptest/pull/713
(Also ported to TG at https://github.com/tgstation/tgstation/pull/65098)
Applies them to paradise.
Adds "industrial" subtype for SSUs featuring the bulky square versions.
Engineering SSU's now use the industrial sprites.

## Why It's Good For The Game
3/4th sprite project marches on. This is one of the more "obvious" object sprites we have left that is clearly not 3/4ths.

## Images of changes
2022-04-30 20_10_58-Paradise Station 13
("Super UV" from hacking the SSU's is animated, this image poorly captures the doors "pulsing" with heat)

### EDIT: "Chonkified" industrial SSU with grey pallet swap (the original spriter, retlaw32, pointed me in this right direction here)
image

## Changelog
:cl: retlaw32
add: Industrial suit storage units (SSUs) with new icons
tweak: Existing SSUs ported to new sprites
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
I'm not really digging these, however that may just because of the framing of them and the fact that most sprites around it aren't also 3/4. Could we see some wider screenshots of them in engineering?

**Comment by S34NW** [comment]
> Could we see some wider screenshots of them in engineering?

image
image
image

**Comment by Sirryan2002** [comment]
Thank you, the cylinder ones look awesome. The other more rectangular ones in engineering feel a bit awkward though, but they're definitely a stylistic improvement to what we have, I'm sure they'll fit in more and more as we move to 3/4. Good port 👍

**Comment by Miraviel** [comment]
The cylinder one looks amazing, I am absolutely in love with it!

The rectangular one looks like it is not tilted as the same degree as the other objects. I can be totally wrong though, but that is what feels off for me...

Here is an example next to a crate for comparison (I am not sure how it looks in-game, but this is my guess why it feels off):

image

image

**Comment by S34NW** [comment]
image

chonkification complete

**Comment by procdrone** [comment]
i like the boxy ones

**Review by AffectedArc07 — APPROVED** [review]
We need gas tanks next good god

**Pull request merged**
