### PR TITLE
Adds the ability to disable subsystems with the config file

### PR DESCRIPTION
**Pull request by MINIMAN10000**
**Reason:**
I was tired of waiting 10 seconds for atmospherics to start when I don't rely on atmospherics. But I figured if I was going to do this I'd rather not hardcode it in, instead allow people to use the config file to pick and choose, figure it would come in handy for someone or if some name changed or is added.

**Whats it do:**
Allows you to go into config and disable subsystems by name comma delimited
Example: DEVELOPER_DISABLE_SUBSYSTEM Atmospherics,Shuttle

This is my second attempt at this because the first time caused the server to run time and not start any subsystems so I thought "What could cause a runtime" to which I figured well if I just remove the DEVELOPER_DISABLE_SUBSYSTEM flag, does it break. The answer was yes. It was trying to run length against something that didn't exist and giving off a run time. So now it needs to check if it exists before doing so.

I feel I should note while I know how to change the example config I don't know how to change the live server config. But at least this prevents failure in the event that the flag doesn't exist.

**Changelog:**
:cl: MINIMAN10000
add: The ability to remove subsystems from the config
fix: Failing to start subsystems if there is no config option at all
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Sounds like a great way to break everything
I love it

**Comment by AffectedArc07** [comment]
image
Travis Failed

**Comment by MINIMAN10000** [comment]
Well neat it appears for whatever reason config.dm is missing well the related code

**Comment by Fox-McCloud** [comment]
The last time you tried this, it did break everything.

**Comment by MINIMAN10000** [comment]
Obviously I as much as anyone want my code to function.
I had only learned about the merge having to be reverted after searching pull requests regarding subsystems.
Previously my only experience in configuration options were boolean. Booleans are great because they either exist, or they don't exist which prevents runtimes from happening.
It wasn't until looking over my code and testing my suspicions that without the config existing checking for length is an operation which will cause a runtime. This halted master before it got to proceed to initializing any subsystems thus obviously breaking everything.
By putting that same boolean check if a config exists as boolean configuration opens do prevents it from running anything, thus preventing runtimes and fixing the problem.
> Leave the subsystems alone; they all need to be active for a reason.

I mean technically you're not wrong, but each subsystem is in charge of a specific task, and that task is the reason it is active, as developers we don't need all tasks being performed when developing completely unrelated features.

**Comment by AffectedArc07** [comment]
I kinda have to side with fox here. A lot of these subsystems handle other things just by firing. Disabling the atmos subsystem **WILL** have a lot of unintended side effects.
Below is my chart of subsystems and what **I BELIEVE** they do, and what **I BELIEVE** will do if they are disabled
image


Not to mention how much of a finnicky bastard the master controller is, and how the server starting up takes about 40 seconds, if that, I really dont see a benefit to this. Not to mention it then takes effort to set the config. And again 90% of the things people may be adding are probably going to rely on some subsystem or another, so if its disabled, thats gonna be harder.

I dont like this

**Comment by Fox-McCloud** [comment]
the weather SS is only safe to disable as long as Lavaland isn't in.

The moment it gets added, you'll start to see runtimes all over the place due to ash storms.

Fires is hypothetically safe to disable; something would acquire the fire sprite, but it'd never burn.

That said, it has zero impact on startup time and it doesn't process 99% of the time unless you're specifically testing fires for something.

So that leaves...smoothing.

You'll save like 1-4 seconds, tops if you disable it....yeah no.

**Comment by Crazylemon64** [comment]
I really don't think this will work well at all. The codebase is written with the assumption that all subsystems are initialized and firing.

**Comment by Fox-McCloud** [comment]
Yeah, the potential for this to break things or be misused by coders is too high; the more and more we integrate the SMC into the codebase, the more dependent on subsystems we are...and well, I don't think disabling them, whilly nilly, is something that should be done.

**Pull request closed without merging**
