### PR TITLE
Definitely Not Ian

### PR DESCRIPTION
**Pull request by Robertha89**
Gives Ian a new hat, the fake mustache
image
image

### CODE REVIEW

**Comment by tigercat2000** [comment]
Did you test the lazarus injector? Because it might not work, and it's going to be touched by -tg- mining, so not a good idea to touch it at all.

**Comment by Robertha89** [comment]
Yes, I did test it, and if the lazarus injector disappears it can be readded at a later date.

**Comment by Fox-McCloud** [comment]
HELL no.

**Comment by Aurorablade** [comment]
Could make some kind of strange pet only defib thats like one time use.

**Comment by KasparoVy** [comment]
What the heck is lazarus for in TG mining? I'm confuzd and intrigued

**Comment by Fox-McCloud** [comment]
@Aurorablade 

That's exactly what it is, and that's exactly why it should never be easily available.

@KasparoVy 

It's an item that, under the coming TG mining, when used on a dead mob, will revive it to full health; it's a relatively expensive reward that requires a decent amount of ore to be mined to utilize it.

**Comment by Fox-McCloud** [comment]
side note, the mustache thing is 100% A-ok, though :+1:

**Comment by Earthdivine** [comment]
Would making a child of Lazerus that only works in simple mobs be alright? I haven't seen the Mining mobs yet but I don't think they are the same mob type as Ian and co.

**Comment by Fox-McCloud** [comment]
The lazarus only works on simple mobs; that's what it was explicitly designed for.

**Comment by Robertha89** [comment]
here is the value list per ore:
Iron 1 
Glass 1 
Diamond 40 
Plasma 40 
Gold 20 
Silver 20 
Uranium 20 
Bananium 100 
Plastic 1 
Fabric 20 

the price of the item in mining points is 1000 or one sheet of gold, silver, uranium, or half a stack of plasma.

**Comment by TheDZD** [comment]
Yeah, definite :-1: for the same reason Fox said, Lazarus injectors are meant as a reward for mining. 

Another thing that's also very relevant and wasn't mentioned here is that when used on a dead hostile mob, Lazarus injectors revives said mob and makes it friendly. When EMPed and used on a hostile mob, it makes it only friendly to the person who revived it.

**Comment by ZomgPonies** [comment]
:-1: for anything tg mining until it's properly ported, :+1: for the mustache.

**Comment by Spacemanspark** [comment]
The lazarus injector allows you to bring back mobs from the dead.
It ALSO makes said mob your personal bodyguard against other mobs and players that attack you.
Well, Ian, when injected, merely nuzzles those that attack. Kind of amusing.
Regardless, :-1: to the injector.

**Comment by Robertha89** [comment]
Ohright, Reverted the lazarus for now.

**Comment by Fox-McCloud** [comment]
:+1:  from me now that it's just for Ian.

**Comment by Keilden** [comment]
Fox did you not read? Thats Definitely Not Ian.

**Comment by Fox-McCloud** [comment]
OH DAMN IT, it's not IAN.

Now I'm going to have to revert this.

**Pull request merged**
