### PR TITLE
Character gender is now split into biological gender and gender identity.

### PR DESCRIPTION
**Pull request by tigercat2000**
You can customize the gender identities as much as you like, but the following are provided as presets.

 - Apache Helicopter
 - Wolfkin
 - MtF
 - FtM
 - Foxkin
 - Tigerkin
 - Bi

### CODE REVIEW

**Comment by NTSAM** [comment]
Excuse me but i identify as a civilian helicopter and this is triggering me you problematic cis white male scum

**Comment by LiquidNightfury** [comment]
Why must you hurt me in this way

**Comment by QQCucumber** [comment]
Changelog failed apparently? Neca reported an update but there is no changes listed.

**Comment by CrAzYPiLoT-SS13** [comment]
If I'm not wrong, this means we've patched, right? There's one PR that's been waiting for half a month now *whistles*

**Comment by Belsima** [comment]
ha apache helicopter! XD

**Pull request merged**
