### PR TITLE
Fix posibrains being unable to speak binary

### LINKED ISSUE #2124: Posibrains can't :b
Title

### PR DESCRIPTION
**Pull request by tigercat2000**
Resolves #2124

### CODE REVIEW

**Comment by veganzombeh** [comment]
I'm not sure if this is a good idea. Posibrains are *very* easy to obtain. There can be an active posibrain *seconds* into the round, and having them be able to hear binary is a substantial nerf to malf AIs, who primarily communicate with their borgs through binary. This would likely lead to posibrains screaming about malf AIs minutes into the round.

**Comment by tigercat2000** [comment]
@veganzombeh They can already hear binary. This just lets them speak it, which was caused by a bug.

**Comment by Spacemanspark** [comment]
:+1:
And ya, posibrains can HEAR it, just not speak it currently.

**Comment by Alex6511** [comment]
I think it would be nicer to just remove binary from them entirely. Could give them the ipc language instead.

**Comment by tigercat2000** [comment]
@Alex6511 That's a matter for a different PR. It's not a big deal.

**Pull request merged**
