### PR TITLE
Adds sugarcane to the MegaSeed Servitor

### PR DESCRIPTION
**Pull request by Jountax**
For months now botanists have had to raid the community garden or pester cargo to order a seed crate in order to acquire this most basic of crops. Well I say no more!

Seriously though, this just struck me as an oversight so here's a fix for it.

:cl: Jountax
fix: Sugarcane added to the MegaSeed Servitor. No more garden raids!
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Botany power creep. :-1: x :100:

**Comment by taukausanake** [comment]
I kind of feel sugarcane is special like that. You can't really get sugar any other way I've noticed I think. Not sure how I feel about this

**Comment by Jountax** [comment]
@taukausanake Sugarcane is available at round start in the public garden that everyone has access to. When I play botanist, and I plan to do anything at all with sugar (and halfway into the round if the chef requests sugar) I just go nab it from the garden.

Either it's an oversight for it to not be in the machine, or it's an oversight for it to be in the garden.

**Comment by jughu** [comment]
White beets make sugar

**Comment by KasparoVy** [comment]
But can it make moon sugar? 😼

**Comment by taukausanake** [comment]
@KasparoVy IT SHOULD! Then we could make Skooma! It could also be the drug that our Khajiiti/Tajaran catpeople need. Too bad it's more like a salt than a sugar though...

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
