### PR TITLE
Rename all "rigs" (hardsuits) to hardsuits

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Renames all hardsuits to hardsuits properly, removing any references to rigs. The actual rigs that go on your back are unchanged.

Repaths "rig" hardsuits to /hardsuit instead of /rig, rename rig.dm to hardsuit.dm, adjust icon states accordingly

ready for merge

:cl:
add: Wizard Hardsuit helmet and suit now have inhand sprites
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
So can someone define the different between hardsuits and rigs? I think one of them comes from Dead Space reference but I really don't know anything in these regards

**Comment by uraniummeltdown** [comment]
The ones that players can use are hardsuits which are mainly spacesuits with more armor/tesla protection/etc.
Rigsuits go on your back and have all sorts of modules, also I think you need surgery to take them off? They're admin-only

Both hardsuits and rigsuits are based on Dead Space RIG suits

**Comment by MarsM0nd** [comment]
I think there was an "emergency release" verb added, it will take some time, for one to stop people to use it in a spacefight i think, after that, the suit unseals and the backpack item can be removed.

**Comment by Markolie** [comment]
This was pretty confusing. 👍 from me.

**Comment by Necaladun** [comment]
yeah 👍 for clarity

**Pull request merged**
