### PR TITLE
New Fire Extinguisher Sprites - Round 2

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
#16431 Replaced our old sprites with TG's, so now here's my replacement for TG's with new ones I made.

## Why It's Good For The Game
TG's extinguisher looked almost hexagonal, so it's been rounded out. The small extinguisher looked barely like a fire extinguisher. I tried digging through google images for various types of extinguishers to see what its based on, but couldn't find anything similar. The new one is based on what real life miniature extinguishers look like. This should be helpful to newbies for understanding at a glance what the item is.

## Images of changes
Top row are the new ones
Capture

## Changelog
:cl:
imageadd: Brand new Fire Extinguisher Sprites
/:cl:

### CODE REVIEW

**Review by variableundefined — APPROVED** [review]
The new sprites are much better and fit thematically.

**Comment by Carthusia** [comment]
I dunno about the new mini, its supposed to be somthing you can easily fit into a bag thus the tiny box shape.

It just looks way to round and cumbersome to be a small pocket extinguisher

**Comment by Spacemanspark** [comment]
Indifferent overall; new sprites proposed here look fine enough.

**Comment by PacifistDalek** [comment]
Size comparison I was envisioning using real life extinguishers, for context
Screenshot_20210919-132954_Opera
Screenshot_20210919-132849_Opera

**Comment by Carthusia** [comment]
Which is fine, but looking at the sprite a bit more i notice a few oddities:

https://gyazo.com/780f8333d07230e21e2d4027f3efa543

It looks as if its handle is its sprayer or that there is no clear spray point.

The previous versions all have visible Handles, trigger/safties and sprayer points that are noticable at a glance, but the new version of the emergency one does not.

Personally: I like the older boxy white design to seperate it more from the full sized wall mount ones.

**Comment by PacifistDalek** [comment]
Good point on the handle, i'll change that, lets see how it looks after that.

**Comment by PacifistDalek** [comment]
@Carthusia Having had the chance to look at your notes finally, I can tell you that I have been interpreting the old sprite completely differently than you do, and that's probably the source of most of the confusion.

image

I'm gonna play around with the mini extinguisher design more, and see if I can come up with something more fitting

**Comment by PacifistDalek** [comment]
image
playing around with this (I'd ping you on discord, @Carthusia but i couldn't find you)

**Comment by PacifistDalek** [comment]
LETS GO DO THIS AGAIN

ok

new mini extinguisher design because @SabreML found a real life extinguisher that the old boxy design seems to be based on:

image

**Comment by Carthusia** [comment]
I like

**Comment by PacifistDalek** [comment]
one last mini extinguisher tweak to make the trigger look more like a button

image

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
