### PR TITLE
WIP - Wryn Larvae Cubes

### PR DESCRIPTION
**Pull request by Kiyahitayika**
## What Does This PR Do
Adds Wryn Larvae Cubes to the game.
They come in a "Wryn Cube Box".
This box can be ordered through Cargo and comes in a "Wryn Larvae Crate" that costs 20 points.

## Why It's Good For The Game
@Marginalorb is working on bringing Wryn up to modern standards so they can be added to as a playable race. The larva sprite existed in the same place as the Stok, Wolpin, Neara, and Farwa sprites. 

## Images of changes
I added a file called `r_larvae.dmi`. This file takes the `wrynkey1` sprite from `\icons\mob\monkey.dmi` and breaks it down into head, torso, and groin sprites to be used as a "monkeyized" form of Wryn in `\icons\mob\human_races\monkeys\r_larva.dmi`.

Groin:
image

Head:
image

Torso:
image

Ordering Crate of Cubes from Cargo:
https://imgur.com/a/DPiVP08

Hydrating Wryn Cubes into Larvae and using the DNA Modifier to make them into Wryn:
https://imgur.com/a/mHu6XHZ

## Changelog
:cl:
add: Wryn Larva Monkey Sprite, Wryn Larvae Cubes, Wryn Larvae Cube Box, Wryn Larvae Cube Box Crate, Code to Make Wryn from Wryn Larvae
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
This is nice, I'd love to have the Wryn as a playable race, but there is a reason that they haven't been treated as one and it's either because they are broken, featureless, or maints. Wryn can have some interesting things done with them, but it'll never be done and this will probably be blocked by virtue of that.

But I still want to see how this turns out. Maybe I'll be proven wrong

**Comment by Kiyahitayika** [comment]
> This is nice, I'd love to have the Wryn as a playable race, but there is a reason that they haven't been treated as one and it's either because they are broken, featureless, or maints. Wryn can have some interesting things done with them, but it'll never be done and this will probably be blocked by virtue of that.
> 
> But I still want to see how this turns out. Maybe I'll be proven wrong

@Marginalorb is working on bringing them up to modern standards and giving them the large amount of TLC they need. Just so happens they were working on this when a group of us elsewhere started on it too. So there's a few of us working on Wryn at the moment. 

There's a few things involved:

- Fixing up Wryn Sprites - @Marginalorb and I found out that the original tail sprite still exists and Margina has also been working on other tail ideas. They managed to script the code to make the tail work in-game!
- Removing OldCrit and Spaceproofness - Margina's got this!
- Giving Wryn Colors - Margina gave them RGB
- Adding New Sprites - Some folks have created more antennae for Wryn. These will be easy to add to the sprite file. We're also looking body markings and @Marginalorb 's working on other really cool ideas.

What started as separate hobby projects by individuals has turned into a collaborative group effort and it's pretty exciting. This WIP PR came about because I happened across the larva sprite and realized that there was an opportunity to add in "wryn cubes".

**Review by Kyep — APPROVED** [review]

**Comment by variableundefined** [comment]
@taukausanake 
In my two years as a maintainer and more as a staff, I've not recalled a single substantial, serious and viable proposal / PR until now to rebalance Wryn or make them viable. The same goes for nucleation. If you searched up nucleation and wryn, you'll see the PR field is more barren than the Sahara.

It is clear that until the past month the public or our contributors as a whole never had much interest in reviving the two species. In fact, reviving imply they were alive or viable at some point, but Nucleation and Wryn were a code stub, a leftover incomplete project since the beginning of Paradise as far as I recall. I don't know why you are trying to pin the maints as the boogeyman for them not being viable.

Also, how long has it been since you actually played on the server?

**Review by variableundefined — COMMENTED** [review]
I approve this for design. 

Is there any reasons I'm not aware of that Wryn has no kidney or liver? 

Also, this is PR still WIP and not ready for merge, or can this be merged in ahead of time?

**Comment by Kiyahitayika** [comment]
> I approve this for design.
> 
> Is there any reasons I'm not aware of that Wryn has no kidney or liver?
> 
> Also, this is PR still WIP and not ready for merge, or can this be merged in ahead of time?

Wryn still need work. @Marginalorb and I are working on them. The missing kidneys, liver, and lungs and other reasons are why this is still set as a WIP. The missing organs are due to the fact that we need new organ sprites for Wryn. The original code has them using standard human organs and we could certainly use Kida organs, but that's just cheating x3.To really usher this species back into the game, we were hoping to cover all our bases beforehand. 

Right now Wryn are also OldCrit. We know exactly what to do to fix that - I have a branch for that. I just need to get some organ sprites. :3

**Comment by variableundefined** [comment]
Closing. This has been WIP for way too long.

**Pull request closed without merging**
