### PR TITLE
Fixes to Meteor Gamemode

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Makes the waves actually work
- Warning about gamemode happens between 1 and 3 minutes into the round
- First wave begins at the 10 minute mark
- Waves last from 2.5 minutes to 5 minutes
- Pauses between waves last from 5 to 15 minutes
- It is up to crew to decide if/when to call the shuttle

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1: This is long overdue.

**Comment by ZomgPonies** [comment]
I'd rather not force minimum times for now while we test the balancing of the timings and once those are set in stone THEN we can give a minimum time before shuttle call or number of waves or whatever objective we want.

**Comment by taukausanake** [comment]
Slightly off topic question here. Would shield generators stop meteors from going past them? I've always wanted to build a shield around the station in an attempt to protect it from damage

**Comment by Earthdivine** [comment]
It does and breaks the mode mode a bit. I don't believe they lose power from being hit either.

**Comment by taukausanake** [comment]
Yeah but to get so many generators to protect the station, I'd imagine that to be a great achievement.

**Comment by Keilden** [comment]
Add a bananium meteor!

**Comment by ZomgPonies** [comment]
Once we've got a decent balance going, I'll take a look at shield generators and such.

**Pull request merged**
