### PR TITLE
ADD: Skins for mecha!

### PR DESCRIPTION
**Pull request by ErdGinalD**
## What Does This PR Do
Add MANY skins for Ripley, Odyss, Gygax, Durand and Phazon. All obtainable via Exosuit fabricator in new section "Exosuit Paintkits". Summary have 8 skins for ripley\firefighter, 2 for odyss, 6 for gygax, 5 for durand and 4 for phazon.

## Why It's Good For The Game
Style is critical part of our life, without skins life is not a life. For precious mechas this mean not less than for humanity.

## Images of changes
Ripley/Firefighter
image
image

Gyga
image
image

Ody
image
image

Durando
image
image

Phazon
image
image
image
image
image
image

## Testing
In-out as human
In-out as AI
Create, build, compile, repeat, again, reset

## Changelog
:cl:
add: Added paintkits for mechas. Obtainable via exosuit fabricator in new section "Exosuit paintkits"
/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
this give more fps to mechas?

**Comment by ErdGinalD** [comment]
> this give more fps to mechas?

Few of it animated, change only textures.

**Comment by McRamon** [comment]
Just like i said on discord, most of the sprites here are very low quality and cant be accepted. The framework of painting mechs is nice but it should at least uphold the current sprite quality (many of the mechs above dont even do that, and some also change shape entirely for some reason when its supposed to be just some paint on chassis).

**Comment by ErdGinalD** [comment]
> Just like i said on discord, most of the sprites here are very low quality and cant be accepted. The framework of painting mechs is nice but it should at least uphold the current sprite quality (many of the mechs above dont even do that, and some also change shape entirely for some reason when its supposed to be just some paint on chassis).
> 
> The painter item also low quality

painter was in code and not used in current PR

**Pull request closed without merging**
