### PR TITLE
Resprites the mech cursor icon

### PR DESCRIPTION
**Pull request by ExusA**
## What Does This PR Do
This resprites the combat mecha cursor icon down to a simpler crosshair, down from its current static radar image.

## Why It's Good For The Game
This is kind of a tough one, but the rationale is this:
The radar image is cool, but blocks your view of what you're shooting at. In a game where precise clicking is important, the cursor shouldn't get in the way of the thing you're trying to click on. The precise area where the click happens isn't too clear, and it's also generally a little too noisy as a sprite.
This went through a fair few iterations and we landed on this very simple green crosshair- the same design as the laser carbine, but vivid green for visibility and mecha color coding.

## Images of changes

https://github.com/user-attachments/assets/2f7b06e4-95a1-454c-8038-e9536691cd6e

## Testing
Walked around and shot stuff in a mech, clicked and dragged to make sure the states worked properly.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imageadd: Scaled back the design of the mecha cursor icon.
/:cl:

### CODE REVIEW

**Comment by ExusA** [comment]
Current:
crosshaircurrent-export
crosshaircurrent-export2

New:
crosshair-export

**Review by 1080pCat — APPROVED** [review]
Soul removal 😔 
100% warranted though, fuggly ass static radar was bad

**Comment by AffectedArc07** [comment]
Im gonna ask.

Why do we have a fancy cursor for when youre in a mech anyway? Seems like a holdout from "oh shit we can do this why the heck not" times.

**Comment by ExusA** [comment]
I'm not super invested either way- If folks think the cursor can go, by all means I'll do that instead.
There's a minor accessibility case to be made in favor of axing the fancy cursor, in that it's not fully colorblind-friendly.
#24998 added a similar cursor along with the full auto component that could be axed along with this one if that's the route to take.

**Review by Sirryan2002 — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
