### PR TITLE
Bones nerf

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
Alright, so here's the deal with bones. Prior to this PR if a limbs damaged exceeded the brute threshold that bone would break. This meant that if you received large amounts of brute damage over multiple limbs you would likely break multiple bones. Which is fine, until you look at the thresholds.

Hands and feet took 15 brute damage to break. If they are broken you are immediately slowed to a crawl or forced to drop what you are holding.

Arms and legs took 30 brute damage to break.

Torso, Head, and groin took 35 brute damage to break.

Someone could toolbox both your hands to essentially pacify you with no counter.

**So what did I change?**
Bones no longer break at the threshold. They start rolling for breakage after the bone has passed the threshold(This is normally when the bone would already have been broken). Each time you inflict damage to a limb past the threshold you roll for a chance of breaking that limb depending on the damage you inflict. This means larger amounts of damage have a much higher chance to break the bones. I believe a desword does 34 damage so that would be a 34% chance to break a bone per swing. These numbers can be changed to fit better down the line.

**Why do we need this change?**
It's not fun for anyone to not be able to hold items until they get a two minute surgery(usually longer with inexperienced surgeons) just because they were punched a few times. During more chaotic rounds making surgeons do bone surgeries for each bone takes away time they can use to clone and SR people and get them back in the round. This also raises survivalibility a lot for crew, being able to run away because your feet weren't immediately broken and being able to fight because your hands weren't immediately broken will help make a lot more people feel a lot less helpless.

Forum post for further reading and sharing ideas: https://nanotrasen.se/forum/topic/16071-rework-bone-breaking/

**Changelog:**
:cl:
tweak: change how bone breakage is calculated
/:cl:

### CODE REVIEW

**Comment by farie82** [comment]
Mixed feelings on this one due to it now being reliant on RNG. Meaning a punch can break a bone. Difference between a 5 minute jail time and a 15 minute jail time. Etc

I'd rather see that the chance goes up when the limb is more damaged. Keep the RNG but also make it a bit reliable. Maybe 1/2 of the already taken damage + damage to take as chance? Something the like

**Comment by Couls** [comment]
A punch has a 2% chance to break a bone and the limb still has to be past 15 damage so if you do end up breaking a bone from punches you’re either REALLY lucky or unlucky

**Comment by SkeletalElite** [comment]
TBH Arm and hand breaking is practically equivalent to literally removing it since you instantly drop anything when it's broken, I think arm/hand breaks should just be made less damaging. One time disarm and fail chance on picking something up, but once it's in your hand it just has a drop chance over time.

**Comment by KasparoVy** [comment]
Fuck. There goes my go-to self defense mechanic.

**Comment by Couls** [comment]
you make it sound as if antags can't use it against their targets to ensure they can't fight back at all

**Comment by KasparoVy** [comment]
I rarely recall dying to antagonists who haven't been prepared enough to slay dudes, hands or no

**Comment by Couls** [comment]
Then this won't change that at all unless you solely rely on breaking both the hands of anyone who tries to kill you all the time, which I highly doubt considering how hard it is to do like you said

**Comment by KasparoVy** [comment]
The occasions it works it's fucking fantastic, like breaking a dude's esword/stun hand and counterplaying off that event in the fight if you manage to score some proper hits and exercise clutch movement (as much as you can given lag/enemy stim users)

Being able to use that force, to have that effect in a fight where it isn't just ez mode get walked over is more than worth the difficulty. I do not feel it's worth putting down

**Comment by Couls** [comment]
The solution to your issue is to use disarm which still has a 60% chance of making your target drop your weapon I don't think breaking someones bones is called self-defense in most situations and it doesn't make much sense. Even as a game mechanic it may have been powerful but its definitely too powerful.

**Comment by Couls** [comment]
and you think permanently disarming someone from 4 direct punches to the hand is fair for the victim?

**Comment by KasparoVy** [comment]
Contextually I think it's very fair, wholesale it can be very unfair. With that polarity in mind I think I better understand your points and agree with the premise of the PR

**Comment by datlo** [comment]
Breaking bones is pretty much the only advantage that raw damage weapons have over stun based weapons like stunbaton/prod and tasers. This is an indirect buff to stun based combat. 👎

**Comment by Couls** [comment]
Raw damage weapons still have a very high chance of breaking bones, anything with higher damage than a stunbaton will have a relatively high chance of breaking bones PER HIT, a fireaxe will have a 20% chance of breaking a bone everytime you swing it past the threshold, this isn't a nerf to raw damage weapons its a nerf to low brute damage weapons. I think you're looking at it wrong. Before this change it didn't matter whether or not your weapon did damage it simply mattered whether or not the limb was damaged. ANTS could break bones if they were past the threshold.

**Comment by datlo** [comment]
Then change low brute damage weapons/effects to not break bones, if that is the issue that needs fixing. It doesnt matter that high damage brute weapons have a higher chance than low brute damage ones, this still nerfs them.

**Comment by Couls** [comment]
The issue is that would nerf lower damage weapons too far, theres no sweet spot where we can go "this weapon is allowed to break bones but this one can't" it's better to just give it a universal chance of bones breaking and just weigh it on the weapon being used, what would you recommend be the threshold for bones breaking then? I'm open to feedback in that regard. Set the threshold too high and only syndie weapons will break bones, set it too low and this PR becomes pointless because bones are still paper.

**Comment by MRgaty** [comment]
I like this, is better than having your bones broken in 2 hits.

**Comment by Xantholne** [comment]
I prefer this than having a Goliath break my hands in one hit on lavaland. The entire reason bone breaking has been brought up since it's merge. Hell even legion skulls break my hands in one hit sometimes. And on lavaland movement is key, but you can't really do much with a broken foot in one hit. Especially with crusher kits coming, crusher mining will become big and this will become a bigger issue than it currently is.

**Comment by MrMagolor** [comment]
>I prefer this than having a Goliath break my hands in one hit on lavaland. The entire reason bone breaking has been brought up since it's merge. Hell even legion skulls break my hands in one hit sometimes. And on lavaland movement is key, but you can't really do much with a broken foot in one hit. Especially with crusher kits coming, crusher mining will become big and this will become a bigger issue than it currently is.

The issue is: with all the damage goliaths do, they're likely to instantly break a bone in TWO hits instead of ONE. And your speed will still be slowed enough that it's inevitable anyways.

**Comment by Couls** [comment]
Yeah, so goliaths do about 25 melee damage. Prior to this PR that would be a 100% chance to break hands and feet, with this PR it is a 25% chance to break hands and feet per hit past the first hit. Chance is still high but its not guaranteed to happen every engagement

**Comment by Evankhell561** [comment]
I think you should double or even triple those probabilities. This pr will make the bones too strong in their current state. I also see less reasons to play with an ipc, has anyone thought of ipc?

**Comment by Couls** [comment]
You could just apply a welder and cable coil to repair broken IPC limbs, or have a friend reattach them if they happen to fall off, you don't need a long surgery or to apply splints. Treating a malfunctioning IPC arm or leg is entirely different from doing bone repair surgery. The reason to play IPC is to never have to get bone surgery in the first place

**Comment by Evankhell561** [comment]
Well, i should not have started a discussion about ipc because it distracts attention from the topic, so i will not continue arguing about it. The point is, this pr makes bones so much stronger than they are now i think this buff is excessive and that those probabilities.

**Comment by Couls** [comment]
The whole point of the PR is to make bones stronger as they are currently far too weak. It’s named bones nerf because it nerfs the ability to break bones

**Comment by AdamElTablawy** [comment]
bones are basically made of plasticine at the moment and it has become increasingly apparent that since even minor brute damage breaks hands and a broken hand basically incapacitates the person combat is functionally just as much rocket tag as it is with stun weaponry.

the first one to land a hit on your hand with a circular saw instantly wins the fight, because now the other guy can't hit you at all due to constantly dropping his shit. that's not great, tbh.

**Pull request merged**
