### PR TITLE
Morgue Access Fix

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Re-upload of: https://github.com/ParadiseSS13/Paradise/pull/6355

Fixes a longstanding oversight with morgue access.

Anyone with *just* morgue access ended up having access to main medical bay because of an error on the access of the *inner* morgue door.

This isn't supposed to be the case; having morgue access is meant to *only* grant you access to the morgue and not the entirety of medical bay.

:cl: Fox McCloud
fix: Fixes erroneous access on inner morgue door which was granting people with morgue access, access to the entirety of medical bay
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
I'll just repost my opinion here: This has been a thing for so long, I don't think you can just consider this a simple "fix" anymore. It's an unwelcome change to me, regardless.

**Comment by Anticept** [comment]
I approve of the fix because people are walking through the morgue into medical when they don't need to be.

**Comment by SamHPurp** [comment]
I would abuse this a lot of Chaplain to get easy access into medbay whenever I wanted.

I definitely support changing this... and I view this as a fix.

@tigercat2000 "We've always done it this way!"...

**Comment by tigercat2000** [comment]
@SamHPurp I'm not arguing that's a reason to keep it like this. I'm arguing it's inaccurate to call this a fix, because it isn't- it's a balance change to a long established feature.

**Comment by SamHPurp** [comment]
I see. I don't agree, but I do see what you mean.

**Comment by Davdichan** [comment]
@tigercat2000 see flashprotection

**Comment by Crazylemon64** [comment]
This one's clear to merge due to it being a re-upload of an older PR.

**Pull request merged**
