### PR TITLE
Adds mounted flashers to emergency shuttle.

### PR DESCRIPTION
**Pull request by AffectedArc07**
Adds a lot of mounted flashers to the shuttle. Enough to stun everyone at once. The button to activate it is in the command cockpit.

Apologies for the messy PR. I have no idea how to nice-ly merge map files.

### CODE REVIEW

**Comment by LightFire53** [comment]
This totally wouldn't be abused at all. What is the access on the button?

**Comment by tigercat2000** [comment]
this does nothing, the shuttle template is not loaded, the actual shuttle is on the map.

**Comment by AffectedArc07** [comment]
The access will be bridge access, and your  saying I need to modify the whole map instead of just the shuttle?

**Comment by SamHPurp** [comment]
This is entirely unnecessary.

**Comment by Twinmold93** [comment]
I can see this being used every round... To knock everyone done in end-round to kill them more easily. Huge no, since anything else security should just be able to flashbang easily: And in the off-times you would need this, you can't get into the cockpit anyway because you're dead to the riot and/or everyone is for some reason shuttle griefing and it's time to start banning people.

**Comment by Lady-Luck** [comment]
Can we just make the shuttle bigger?

**Comment by Birdtalon** [comment]
100% no. If security wants to set up portable flashers for some reason they can do. Flashing everyone on the shuttle would be horrific for all involved.

**Comment by Anoonki** [comment]
Instead of porting CM's "Settle the fuck down" button, how'sabout just put a wall flash on the tile beside the cockpit door?
It'd function in keeping the constant 'tiders from just running in all the time and being a nuisance, but would also be really limited in how abused it could be.

**Comment by taukausanake** [comment]
We need a "[calm the fuck down](https://www.youtube.com/watch?v=xoTzLLZMrKc)" admin command like the Man Up and Deal With It one. To bad I can't find a good one, the link above is the best YouTube could get me

**Comment by Fox-McCloud** [comment]
Closing; this is unecessary.

**Pull request closed without merging**
