### PR TITLE
BoxStation: Remaps Vacant Office

### PR DESCRIPTION
**Pull request by DogeDogIs**
This PR remaps Vacant Office in Arrivals. They are a quite ugly and empty, so a new touch would be nice to new players to see, even old players too.

## What Does This PR Do

This PR rempas vacant office.

## Why It's Good For The Game

It can improve people outside to have more safety to engage in the inside, and at the same the maint door can make the melee antags a better escape.

## Images of changes

image
image
image

## Changelog
:cl:
tweak: Remaps Vacant Office
/:cl:

### CODE REVIEW

**Comment by alex-gh** [comment]
Apart from the concerns with visibility from the main hallway. 
You should probably fix up that power wire coming in through the wall and not through the door while you are mapping around in that area.

**Comment by Miraviel** [comment]
Seconding, please make sure the vacant office is not visible from the north for Nefarious Purposes:tm:.

Otherwise a review:

## Vents

These vents are not connected to the main distro, please make sure you run the pipes under the airlock.

image

## Cables

These cables run below the wall, the current custom is to run wires under doors to make them easily fixable. Please make sure the cables run below the airlock when entering the room!

image

**Review by Miraviel — COMMENTED** [review]
Seconding, please make sure the vacant office is not visible from the north for Nefarious Purposes:tm:.

Otherwise a review:

## Vents

These vents are not connected to the main distro, please make sure you run the pipes under the airlock.

image

## Cables

These cables run below the wall, the current custom is to run wires under doors to make them easily fixable. Please make sure the cables run below the airlock when entering the room!

image

**Comment by DogeDogIs** [comment]
> Seconding, please make sure the vacant office is not visible from the north for Nefarious Purposes™️.
> 
> Otherwise a review:
> 
> ## Vents
> These vents are not connected to the main distro, please make sure you run the pipes under the airlock.
> 
> image
> 
> ## Cables
> These cables run below the wall, the current custom is to run wires under doors to make them easily fixable. Please make sure the cables run below the airlock when entering the room!
> 
> image

I fixed the pipes and the cables now go under a maint door that I added there! In a few moments I will update the PR

**Comment by DogeDogIs** [comment]
> I like the design a lot but my only personal worry is with the door placement. To me there's an appeal that you can't really see the room from the main arrivals hallway since it offers some privacy for antags & ne'er-do-wells. Having the door on the west side also gives people more than just the southern maintenance to duck into since it's regularly a murder hallway for shuttles coming in.

I added a normal Airlock now, and some tinted windows and a new maintece door in the south, now antags can go in disposals maints, and go in the Vacant Office and turn on the Tinted window, so no one can see inside, but if the west entrace was better I can change it!

**Pull request closed without merging**
