### PR TITLE
Removes the mysterious door to space in the prisoner shuttle dock: For Real This Time Edition

### LINKED ISSUE #4177: There's a door in the labor shuttle dock that leads directly to space
https://gyazo.com/4a959717a9332712e21068516910b818

How did this even happen? Why is it there? Who put it there?

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Now with 100% more mapmerge and no merge commits. One would think this would be easy.

Fixes #4177

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Poor @LittleBigKid2000. We appreciate your sacrifice.

**Comment by CrAzYPiLoT-SS13** [comment]
And, uh, the wall? Does it exist?

**Comment by LittleBigKid2000** [comment]
Yes, I replaced the door with a wall.

**Comment by CrAzYPiLoT-SS13** [comment]
Splendid

**Comment by LittleBigKid2000** [comment]
Here's a screenshot to prove it

https://gyazo.com/1a765c00d7065a93f6fc325f07ebf5ef

**Pull request merged**
