### PR TITLE
Fixes all of the relative pathing issues

### PR DESCRIPTION
**Pull request by Tastyfish**
Inspired by tiger's recent work, such as #4933, I created a script to fix all of the relative pathing inconsistencies.

:eyes:

### CODE REVIEW

**Comment by Taaketa** [comment]
I don't code, but this looks super pretty. Shame about Travis.

**Comment by FlattestGuitar** [comment]
I see nothing wrong with this.

**Comment by Regen1** [comment]
>mv: cannot stat `paradise.mdme.dmb': No such file or directory
mv: cannot stat `paradise.mdme.rsc': No such file or directory

**Comment by FreeStylaLT** [comment]
what can go wrong.

**Comment by Fox-McCloud** [comment]
Gosh damn it, @Tastyfish

**Pull request closed without merging**
