### PR TITLE
Fixes missing Tajaran fat torsos

### LINKED ISSUE #5481: Tajaran's fat body icons are the same as slim
fatvsslimfront
fatvsslimside
Although they can be fat, the two icons are the same, and so they do not visibly change when naked.

### PR DESCRIPTION
**Pull request by Ionward**
## What Does This PR Do
Fixes #5481, adding a proper fat torso to Tajaran body parts.
Also fixes two oversights, one with fat aqua jumpsuits, (they only had one direction) and one with Lasagna missing it's icon.

## Why It's Good For The Game
Finally, you can roleplay as Garfield. Also because graphical bugs are bad.

## Images of changes
GIF
(yes, there are 3 vertical pixels in the middle of their belly, unfortunately this is a side effect of their hands and is not easily remedied without removing those hand pixels which would cause more problems)
lasag

## Changelog
:cl:
fix: Fixed Tajaran fat sprites, they are no longer duplicates of their slim torso.
fix: Fixed fat aqua jumpsuit only using one direction.
fix: Fixed missing Lasagna icon.
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
great now I can be garfield and stuff my face with lasagna

**Comment by Ty-Omaha** [comment]
>fixed missing lasagna sprite path designation

thats hilarious this is actually the best PR

**Comment by Ionward** [comment]
> 
> 
> > fixed missing lasagna sprite path designation
> 
> thats hilarious this is actually the best PR

_Become Garf._

**Comment by taukausanake** [comment]
Now if only foxes could have fat sprites...

**Pull request merged**
