### PR TITLE
Nukes AI Multicam

### PR DESCRIPTION
**Pull request by AffectedArc07**
# Initial Note
Anyone who wants to whine "Improve, dont remove!!!11!1!" can go improve this feature themselves. Its sat around for multiple *years* with no tweaks or improvements, and has always been disabled due to how much of a powergamers fever dream the entire mode is. This entire implementation is clunky and needs to be refactored to use TGUI's `byondui` elements, similar to the camera console if it wants to stick around. 

TLDR: You will be clowned on if you try and chant "Improve dont remove"

## What Does This PR Do
Removes AI multicam. Its not even enabled, its a powergamers fever dream, takes up space on Z2, is a clunky mess, and hasnt been updated or improved in multiple years. AI HUD now looks like this.
image

## Why It's Good For The Game
There is 0 point keeping around clunky features which arent even enabled by default unless you varedit an AI mob

## Changelog
:cl: AffectedArc07
del: Removes AI multicam mode. You wont notice anything because it wasn't even enabled. 
/:cl:

### CODE REVIEW

**Comment by Cocacolagua** [comment]
improve dont remove, make it even more buggy

**Comment by FreeStylaLT** [comment]
Remove, don't improve.

**Comment by procdrone** [comment]
urge to "improve don't remove" intensifies

**Comment by Shockpoint** [comment]
I remember the reason it was disabled by default was because it was experimental or something, and something about being overwhelming to newer players? I don't recall anything about it being considered a powergamer's fever dream either.

That said, I have zero idea how functional this thing even is, but I have heard good things from AIs who have asked to have it enabled in the past.

**Comment by Fox-McCloud** [comment]
Mmm... wonderful

img

**Review by Kyep — APPROVED** [review]

**Comment by Spacemanspark** [comment]
@Shockpoint It's extremely broken, both gameplay balance wise and by how bugged it is.
@affectedarc07 can you get a screenshot of how it looks currently?

**Comment by procdrone** [comment]
> Mmm... wonderful
> 
> img

and ill do it again

**Comment by procdrone** [comment]
My bad jokes aside. 

Even if the feature was to be fixed, it would still be an atrocious power-gaming/valid-hunting issue. 

AI could just set cameras to several high risk places and just wait for antags to show up. that's neither fair nor balanced, given how it is already painful to do anything once AI is onto you.

So the effort to fix it is just not worth it, and we are all better off with it removed. so good purge.

**Comment by Kiyahitayika** [comment]
> @Shockpoint It's extremely broken, both gameplay balance wise and by how bugged it is.

I remember once seeing a screenshot and it's exactly what you say, @Spacemanspark - "extremely broken". 

> There is 0 point keeping around clunky features which arent even enabled by default unless you varedit an AI mob

It's not enabled by default, it's doesn't have a toggle. The only way to turn it on is with Admin intervention.  
Granted, a screenshot is worth a thousand words, but when something creates runtimes, yeesh.

**Comment by SteelSlayer** [comment]
Hmph, MDB is giving an error for the cyberiad z2 .dmm, but it works for the meta z2 file. I'm assuming the change is identical to the meta one, replacing the multi-cam room with space tiles.

**Comment by AffectedArc07** [comment]
> Hmph, MDB is giving an error for the cyberiad z2 .dmm, but it works for the meta z2 file. I'm assuming the change is identical to the meta one, replacing the multi-cam room with space tiles.

MDB doesn't work with 2 z-levels with the same name. It doesn't account for multiple directories because it just names the file Z2.dmm and Z2.old_map_diff_bot, which is why sometimes you get mixed map diffs. 

Yet another reason why I should standardise maps.

**Review by SteelSlayer — APPROVED** [review]
> MDB doesn't work with 2 z-levels with the same name

Good to know.

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
