### PR TITLE
HULK fixes and balance

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Fixes green overlay not showing up
- HULK slows you down by +1

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
Good Nerf, now it makes using ranged weapons more viable against these monsters.

**Comment by Plotron** [comment]
As much as I love DNA augmentations, I cannot disagree with the nerf.
It's horrible to be security during a hulk outbreak. Absolutely game-breaking.

Speaking of balance and changes:
why is hulk no longer a toggleable time-limited ability? At least you were able to wait it out as it wasn't a walking unstunnable monstrosity 24/7...

**Comment by Fox-McCloud** [comment]
I don't recommend making the RUN mutation give -1 speed, and I"ll tell you why---while it means the negative effects of a hardsuit (and other things) will be more prominent, it means and overall speed boost for the majority of the crew in the majority of situations. Considering how powerful movement speed is, I don't think giving a speed boost would be good, in this case.

**Comment by tigercat2000** [comment]
>I don't recommend making the RUN mutation give -1 speed, and I"ll tell you why---while it means the negative effects of a hardsuit (and other things) will be more prominent, it means and overall speed boost for the majority of the crew in the majority of situations. Considering how powerful movement speed is, I don't think giving a speed boost would be good, in this case.

I have literally no idea what you are trying to say here
powerful? is it too OP? wh
right now it literally cancels all slowdown, this is a gigantic nerf to it

**Comment by Robertha89** [comment]
removing all slowdowns vs be faster then everyone, while the first is more of a convienience, the later is more powerful, lets just say that every other way of increasing your movement speed, excluding coffee, is somewhat lethal.

**Comment by ZomgPonies** [comment]
Fox - The old RUN speed boost was = -1. Wich meant Diona went from like '5' to -1, a 6 point gain. This is a NERF to RUN.

**Comment by Robertha89** [comment]
it is a nerf, but it is also a buff, I mean, the always -1 meant that nothing slowed you down, which was great if you are a miner or engineer, with Diona it is amusing, because they gotta go fast

**Comment by Fox-McCloud** [comment]
RUN used to *return* -1; that, combined with its location (as opposed to being near the bottom as it currently is) meant that it effectively behaved the same as it currently does; it didn't allow for a speed boost, but it did prevent unencumberment.

**Comment by ZomgPonies** [comment]
At the end of the day this PR is about fixing HULK, not RUN. I can't be arsed to care so I reverted the RUN change. However HULK will NOT be affected by RUN, therefore the slowdown happens AFTER the RUN check.

**Comment by Robertha89** [comment]
Huzzah for that, overall i liked it, because I did not have to eat... or if i got wounded, i could drag my self to medbay, so yes, hulk fix is better, and yes to the hulk slowdown working after run.

**Pull request merged**
