### PR TITLE
Refresh the pods - Port TG/Shiptest sleeper/cryopod sprites and make the body scanner a sleeper subtype

### PR DESCRIPTION
**Pull request by Vi3trice**
## What Does This PR Do
Cleans up the code a bit by making the body scanner a sleeper subtype. While the same could be done with the cryopod, it involves touching some other parts I'm not confortable with ~~topic.dm~~

The sprites from https://github.com/shiptest-ss13/Shiptest/pull/779 and https://github.com/tgstation/tgstation/pull/66702 are ported as well, with the extra mile of being animated too. The survival pod sleeper also gets a proper panel sprite and animated entry/exit sprites.

Slight tweaks are made to the survival pod so it doesn't get to be rotated. It's made to be only one direction.

## Why It's Good For The Game
Sleepers/body scanners/cryopods aren't so foggy anymore, and fit 4 directions now. Survival pod is fancier too.

## Images of changes
Sleepers

https://user-images.githubusercontent.com/80771500/167714948-3f7533af-4677-418c-bcfd-8efb508edab2.mp4

## Changelog
:cl:
tweak: Sleepers and body scanners can be rotated in 4 directions instead of 2 with a wrench
imageadd: New sleeper/body scanner sprites
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
I love the shape of the pods, but the glasses bother me a bit for one reason: what kind of visual direction are we heading to? The latest sprites Sean ported went for a less traditional pixel art look and a more detailed one (suit storage, canisters, etc). This has a very traditional pixel art vibe to it.

I know we don't have a spriter overlord, but if we wish to go for a less clean-more realistic style, this looks like - again, just from this POV, the sprites themselves are great and would look great in a very polished, low palette colour pixel art game - a downgrade to our current ones.

**Comment by S34NW** [comment]
The glass on these is in-line with other glass sprites we ported, such as far collectors.

Not sure how I feel but I'm definitely in agreement they are better than current ones.

**Comment by CinnamonSnowball** [comment]
The lid's ending slant suddenly disappears when the lid closes, and the glass is super opaque and plain compared to current sprites.
Overall feels like a bit of a downgrade, it's essentially trading a decent design for a different decent design though with issues, and an animation that plays constantly while the machine is being used for an animation that plays only once (and has only one extra frame).
These new sleepers also _do_ look a bit blockier than our current ones, but I suppose that's a neutral change.

**Comment by TrashDoxx** [comment]
Whoa, man, that's not what I meant.

**Comment by S34NW** [comment]
Sad :(

**Pull request closed without merging**
