### PR TITLE
Fixes hair for IPCs

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

- Fixes a code issue introduced in #16172 that broke hair for all machine people.

## Why It's Good For The Game

- IPCs are no longer forcibly bald.

## Changelog
:cl:
fix: Fixes hair not appearing on IPCs
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
more IPC buffs?

**Comment by GamblerZ** [comment]
return my hair reeeeeeeeeeeee

**Comment by warriorstar-orion** [comment]
*buzz2

**Comment by variableundefined** [comment]
WAD

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
