### PR TITLE
Adds organ cleansing to surgery

### PR DESCRIPTION
**Pull request by Vivalas**
Salvaged this part of my previous PRs regarding spaceacillin, so there is at least an incentive to treat organ infections through surgery.

Now during surgery, you can inject 5u of spaceacillin into an organ via syringe to instantly cleanse any infection within the organ.

:cl:
tweak: It is now possible to directly inject spaceacillin into organs during surgery, and it only uses 5u to completely cleanse the organ,
/:cl:
`

### CODE REVIEW

**Comment by alexkar598** [comment]
Yay

**Comment by Ralta** [comment]
How is this done mechanically? Do you remove the organ, inject it, put it back in? Or is it a case of injecting during organ manipulation surgery once the selected region is open? Or something else?

**Comment by Vivalas** [comment]
@Ralta Inject during organ manipulation surgery.

**Comment by HugoLuman** [comment]
Holy shit. Finally! Every time I've gotten an organ infection, I've either died or spent an hour in surgery only to have the doctor just give up.

**Comment by Vivalas** [comment]
Despite the fact their hilariously easy to clean with spaceacillin injection?

@Crazylemon64 @tigercat2000 @Fox-McCloud Ready for review or some sort of comment.

**Comment by Vivalas** [comment]
🙏 praise be

**Pull request merged**
