### PR TITLE
Health analyzer - sprite update and animation

### PR DESCRIPTION
**Pull request by DogsParadise**
## What Does This PR Do
This pr updates the current sprite of the health analyzer, in hand sprite of the health analyzer and the sprite when slotted into the medical belt.

*Updates non-upgraded health analyzer
*Updates upgraded health analyzer
*Updates belt when health analyzer slotted
*Updates upgrade for the health analyzer
*Updates in-hand sprites for health analyzer

## Why It's Good For The Game

The old sprite:
The old sprite was outdated, still a coder sprite which was not shaded, had no animation as well as it did not have a realistic approach to the sprite.

What the new sprite aims to accomplish:
*Add a realistic approach to a health analyzer that could be viable on a space station.
*Stil maintain the basic shape of the old health analyzer so it feels less like a massive change
*Made it metallic to go a more realistic approach with the item.
*Animated screens to show what the item is used for, which references real-life tools.
*Create a bigger difference between non upgraded and upgraded version of the health analyzer
*Makes the health analyzer stand out more as an item with great importance.

What I aim to accomplish after this pr:
Update more of medical to the same metallic look and create overall better-looking sprites for medical.

## Images of changes

Images of old content:
image

image

image

Images of new content:
Below you can find the images and animation, see the general overview with animations for the best reference of how it will look like in-game.

General overview, all items with animation:
https://gyazo.com/a0f914170c0e01aa08c67a9e293d1091

Health analyzers and upgrade, static:
healthanalyzer overview still

Belt with health analyzer:
updated healthanalyzer belt

Inhand health analyzer:
inhand healthanalyzer

Animation non- upgraded health analyzer:
non upgraded healthanalyzer-Recovered

Animation upgraded health analyzer:
Upgraded healthanalyzer-Recovered

Traitor health analyzer:
traitor healthanalyzer-Recovered

## Changelog
:cl:
tweak: tweaked health analyzer
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
The Jumping error in the animation of the non-upgraded version is not like that in game. I made a slight error when exporting it. Will fix the gif tomorrow morning.

**Comment by Pixelzilla** [comment]
Not keen on changing the overall shape/design of such an old and recognizable sprite.

I'm not really crazy about the color choices. I think the white/blue theme is more visually appealing and the new design (color-wise) honestly makes me think of a battery. It also just feels really dark and I cant really think of any other items in medical that use a similar color scheme. It will probably look really out of place compared to other medical supplies.

**Comment by DogsParadise** [comment]
I might look into a more whitish plastic exterior for the health analyzer. The colors taken currently are reference how it is in real life.

**Comment by DogsParadise** [comment]
> Not keen on changing the overall shape/design of such an old and recognizable sprite.
> 
> I'm not really crazy about the color choices. I think the white/blue theme is more visually appealing and the new design (color-wise) honestly makes me think of a battery. It also just feels really dark and I cant really think of any other items in medical that use a similar color scheme. It will probably look really out of place compared to other medical supplies.

The design wasn't really altered it's only changed a few pixels. which is only when it's upgraded. The color palette indeed has and it has an animation added.

The color palette currently are a reference to how it is in real life. With an added touch of being more metallic, I was also looking into reworking more of medbay. But seeing as we do not have any guidelines, I am first throwing a few sprites up to get the general consensus.

I might look into a more whitish plastic exterior for the health analyzer. The colors taken currently are a reference to how it is in real life.

**Comment by DogsParadise** [comment]
> > Not keen on changing the overall shape/design of such an old and recognizable sprite.
> > I'm not really crazy about the color choices. I think the white/blue theme is more visually appealing and the new design (color-wise) honestly makes me think of a battery. It also just feels really dark and I cant really think of any other items in medical that use a similar color scheme. It will probably look really out of place compared to other medical supplies.
> 
> The design wasn't really altered it's only changed a few pixels. which is only when it's upgraded. The color palette indeed has and it has an animation added.
> 
> The color palette currently are a reference to how it is in real life. With an added touch of being more metallic, I was also looking into reworking more of medbay. But seeing as we do not have any guidelines, I am first throwing a few sprites up to get the general consensus.
> 
> I might look into a more whitish plastic exterior for the health analyzer. The colors taken currently are a reference to how it is in real life.

Maybe like this?
https://gyazo.com/3f457e774ac3279d7aa61d374a9bb994

**Comment by variableundefined** [comment]
Closing due to lack of updates and two maintainers objection.

**Pull request closed without merging**
