### PR TITLE
Increases playtime requirement for heads

### PR DESCRIPTION
**Pull request by TDSSS**
## What Does This PR Do
This came up in the meeting about the community survey and it became clear that a majority of players wants to increase the playtime requirement for command members.
While people said they want times like 50 hours or even more, I decided to go for a more conservative addition.
In detail:
CE: 5h engineering -> 20h
CMO: 5h medical -> 20h
RD: 5h science -> 20h
HoS: 5h sec -> 20h
Warden: 5h crew -> 10h as sec
Captain: 5h command -> 20h command
HoP: 5h command -> 20h command

## Why It's Good For The Game
There is a concern that heads often have no idea what they are doing or how their department really works. This contributes to the lack of real authority and respect those roles get.
The Warden requirement was increased, since wardens are next in line for acting HoS. Warden should not be unlocked at the same time as regular security officer.

The HoP's requirement was not increased since it needs command xp, and all command jobs are locked behind more playtime now, indirectly making the job harder to get. Also, HoP mostly needs you to have specific HoP knowledge that isn't gained anywhere else (aka how to use the ID computer)

## Changelog
:cl:
tweak: playtime requirement for Heads and warden increased
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
Obviously in favor of this as I made a PR for Warden and HoS times myself that's still up(#1376).
Truthfully believed all heads needed a higher timelock, and while I do agree 25-50 hours would be even better...this is more likely to be merged and will still likely help see an increase in players knowing at-least a bit more than they tend to do now going into head roles.

**Comment by TDSSS** [comment]
After a talk with Kyet, he's actually okay with the times being raised. And he asked for requirements for all heads to be the same.

**Review by Kyep — APPROVED** [review]

**Comment by SabreML** [comment]
Maybe it would be a good idea to add a time requirement to Quartermaster too?
5 hours as CT or something, since it's not a job that can really affect the round.

While it's quite rare, I have seen people who take QM as their first job, having seen the 'Randolph P. Checkers, Quartermaster' videos.

**Comment by ChewedPencil** [comment]
I am definitely totally for this as a basic player... Captain should have some basic knowledge of how all the departments work so they know how to react to different scenarios

**Comment by Sinestia** [comment]
I don't believe this is the right approach, past a point (probably 10 imo) the net gains from increasing hour requirements will be very marginal. These jobs have unique skill requirements and at a point, you're only going to become not-terrible by being a conscientious player and playing them yourself. 

 It's not that this doesn't cause harm either, long playtime barriers would be a turnoff for players experienced in other servers giving paradise a try. 

 Sorry, I hate to post without having any solutions in mind to go with it.

**Comment by Kyep** [comment]
Job prefs screen from TG (Basil, US-West):
tgstation_jobprefs
Note how even TG requires 15h of playtime in each department to play as the head of that department.
If TG requires 15, it really isn't that much of a stretch for us to require 20.
When the matter was brought up in the meeting today, the most common request from our community was that we should require 50 hours of playtime in each department to play as the head of that department.
Obviously 50 is perhaps too much, but 20 seems pretty reasonable, especially when TG already requires 15.

**Review by farie82 — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Comment by procdrone** [comment]
Looks good to me

**Comment by Sinestia** [comment]
> TG's job prefs screen for a new player (Basil, US-West):
> tgstation_jobprefs
> TG requires 15h of playtime in a department to play as the head of that department.
> If even TG can require 15h, its perfectly reasonable for us to require 20h.
> We are higher RP than TG, and we attract a lot of new players due to our position at the top of the server list.
> When the matter was brought up for player discussion today in the community meeting, players wanted a **50h** playtime requirement for head jobs. Not just 50h total, but 50h in that specific department. Obviously that is too much. But, 20h, I feel, is pretty reasonable.

That's a good counterexample

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
