### PR TITLE
Makes ceiling visible

### PR DESCRIPTION
**Pull request by Tastyfish**
For years, it has been an oversight that the ceiling of the station hasn't been rendered. This PR remedies that.
- Made it semitransparent and click-through to compromise with the pro-floorers.

:cl:
tweak: The ceiling is now visible.
/:cl:

## :rotating_light: Preview :rotating_light: 
Imgur

### CODE REVIEW

**Comment by TheDZD** [comment]
Hopefully this doesn't go over everyone's heads.

**Comment by Kerroman** [comment]
Things truly are looking up for this server now that we're getting PRs like this.

**Comment by Necaladun** [comment]
Huh? It's the wrong colour. The ceiling is dark grey.

**Comment by Spacemanspark** [comment]
Brb editing wiki to say the ceiling is white.

**Comment by Tastyfish** [comment]
Uhoh, better add the controversial tag :cold_sweat:

**Comment by tigercat2000** [comment]
:+1: :x: :100:
It's always hurt me to see no ceiling. Never before have we been in such a golden age of code. :sob:

**Comment by FalseIncarnate** [comment]
Came expecting a changelog, saw an actual ceiling... Mixed reaction.

**Comment by Keilden** [comment]
Now we can have xenos crawling on the ceiling! And we can add Wallmaster antags! 
Wallmaster

**Comment by pinatacolada** [comment]
so that's how it looked like after all these years

**Comment by KasparoVy** [comment]
if a tajara is on the ceiling does that mean they are ceiling cat

**Comment by Tastyfish** [comment]
@KasparoVy That is up to the lore czars.

**Comment by Spacemanspark** [comment]
@KasparoVy You just lost your meming rights.

**Comment by Spacemanspark** [comment]
Wow, really, Fox? Lame, man.
Also, @Keilden we can already have a wallmaster antag if we wanted to.
Take a look at Link to the past.

**Pull request closed without merging**
