### PR TITLE
Fixes #5449 - weird corpses in UO45 away mission

### LINKED ISSUE #5449: Away missions' corpse landmark is screwed
img
They're all naked greytide with no items. I also can't imagine any of my map tweaks having broken this, since I modified turfs only, I never touched objects or effects..

Landmark's typepath is /obj/effect/landmark/corpse

/modules/awaymissions/corpse.dm is the file. I am not entirely sure what's wrong there.

### PR DESCRIPTION
**Pull request by Kyep**
Currently, there are some weird, naked corpses in the UO45 away mission. https://github.com/ParadiseSS13/Paradise/issues/5449

This PR changes them so they're replaced with fewer corpses - wearing appropriate mining gear.

Before:

After:

🆑 Kyep
tweak: Dead miners in UO45 away mission are no longer naked.
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Line count on this was ridiculously high. How many corpses were there?

**Comment by Kyep** [comment]
Quite a few. I removed all of the broken ones from the away mission.
It was map merged, though.

**Comment by Kyep** [comment]
@Fox-McCloud Take a look now - its much cleaner.

**Comment by Fox-McCloud** [comment]
Thanks. I wonder what in the world happened the first time?

**Pull request merged**
