### PR TITLE
Delta station fixes and minor remap

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR:

- Fixes mislabeled cameras in: Virology (x5), Medbay south-east hallway.
- Rewires the spaghetti wiring in the service area/maints to be more logical.
- Fixes some fax machines being the wrong type.
- Fixes missing command keycard swipers.
- Pushes beer/soda dispensers back so they aren't nearly falling off the table
- Makes shuttle walls consistent
- Moves engi shuttle to reduce deadspace
- Adds IAA shutters
- Adds megaphones on the bridge for command
- Slightly remaps medbay to remove a redundant corridor, replaced with a creepy confectionary cult room (var edited rune to make it clear its _not_ a real one)
- Replaces centcomm doors with regular ones in chapel and morgue
- Fixes captain not knowing safe codes
- Standardises dirs and similar vars for: APCs, Fire alarms, air alarms, lights, cables, pipes, light switches, keycard swipers, newscasters, intercoms, fire extinguisher cabinets.
- Moves arrivals solar down to fill the void of podbay removal.
- Removes 2 of the 3 APCs in Engineering foyer.
- Adds message monitoring consoles to tcomms and RD office
- Stops sol traders from deleting half of arrivals upon landing
- Fixes random areas being illogically rad-storm proof, or not rad-storm proof
- Replaces all fake wood
- Adds tiny fans to escape pods (at the request of denthamos)
- Fixes holopads being offset, and sitting over scrubbers
- Fixes perma cams not showing up on perma cam monitor
- Removes duplicate cargo APCs
- Removes duplicate areas with APCs in each
- Fixes disposals mass driver only firing when toxins launch a bomb
- Fixes turrets on AI sat not being controlled by turret controller

## Why It's Good For The Game
These issues were minor but annoying. The medbay changes will be a big quality of life improvement to the cramped treatment room, giving doctors more breathing room.

## Images of changes

deltamedold__deltamednew

## Changelog
:cl:
tweak: Tweaked delta station medbay treatment room layout.
fix: Fixed delta station mapping issues.,
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I fail to see how this is an improvement, as you have significantly less space for treatment.

**Comment by S34NW** [comment]
> 
> 
> I fail to see how this is an improvement, as you have significantly less space for treatment.

That corridor was never used for treatment, it is a holdover from when we had a sec checkpoint there.
The way the map is played everyone just crams into the small area with 2 sleepers, and it gets massively chaotic. Spreading the sleepers out so they are not right on top of each other, same with defibs, massively eases congestion and pushing.

**Comment by LightFire53** [comment]
image

Isn't this a mapping sin, to have a disposal pipe going through a wall?

**Comment by S34NW** [comment]
> 
> 
> image
> 
> Isn't this a mapping sin, to have a disposal pipe going through a wall?

5oz8zd

**Review by SteelSlayer — APPROVED** [review]

**Comment by Samman166** [comment]
As someone who plays mostly medbay this is a welcome addition, treatment area was to small and to far from entrance to be used my most

**Comment by S34NW** [comment]
Please note https://github.com/ParadiseSS13/Paradise/pull/16789 should be after this in the queue, despite the actual PR order.

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
