### PR TITLE
-tg- buckling system

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit overhauls a bunch of systems so that buckling works for
any subtype of /obj. This means that space vines and chairs and beds all
use the same system. A lot of stuff has been touched.

Also included in this PR:
 - Buckling people to pipes!
  - Heat exchange pipes will burn/freeze people cuffed to them.
    - Bonus feature: Heat exchange pipes glow based on the temperature of air inside of them!
  - You have to be cuffed to be buckled to a pipe.
 - update_canmove update; Gets rid of shitcode.
  - Lying due to weakened/resting/etc is now handled based on turfs
 - Fixes the segway, and structure based janicart/ambulance.

### CODE REVIEW

**Comment by Markolie** [comment]
:+1: x :100:

**Comment by Regen1** [comment]
This opens for some real james bond scenarios right here.

"Now mister clown, before I turn this valve and let the burning plasma fill the pipe you're currently so passionately hugging, allow me to enlighten you of my masterplan"

**Comment by tigercat2000** [comment]
@Regen1 I intend to port tgstation/-tg-station#11937 next, hehe.

**Comment by tigercat2000** [comment]
# Oh god DNM

just discovered the broken vehicle system can fly in space too

**Comment by Robertha89** [comment]
Wait, thats actually working as intended!

How will you now travel under the field from the field emitters if you can't clean space, also thing about the blood splatter in space, ya need to clean that too, do not fix, plz merge.

**Comment by tigercat2000** [comment]
alright, fixed it best I could
not perfect, but it can be fixed better when we get -tg-'s space movement system

**Comment by tigercat2000** [comment]
@Markolie / @TheDZD / @Fox-McCloud This is merge ready now.

**Comment by RemieRichards** [comment]
@tigercat2000 I'd wait a few days if I were you, @AnturK just expanded it to ANY ATOM/MOVABLE
which allows mob buckling to mobs, which can 1. clean up some shit code (slimes, probably bay's grab+hostage if you guys have that (I know you're a weird tgcode+baycode base)) and 2. many features.

**Comment by tigercat2000** [comment]
@RemieRichards I was going to just add that on later, but it could be a good idea to put in on top of this.

**Comment by RemieRichards** [comment]
@tigercat2000 saves time in the long run, will make merging the tg fixes (for slime buckling) and stuff easier too.

**Comment by tigercat2000** [comment]
wweeeell guess i'll just add 11922 on top when it's done, then.

**Pull request merged**
