### PR TITLE
MetaStation SM Port

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do

Added SM to MetaStation.
Fixes the broken vents and scrubbers on MetaStation.

## Why It's Good For The Game

MetaStation is in dire need of some refreshing before map rotation, figured I'd help get the ball rolling.

## Images of changes

comparechanges

## Changelog
:cl:
tweak: Changed the tesla engine for SM on MetaStation
tweak: Fixes vents and scrubbers on MetaStation
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
oh god it was working a moment ago, time to go into draft while I fix it

**Comment by AffectedArc07** [comment]
Gonna make a rather large request here.

Please style the SM like this. with the emitters to the right, and freezer to the top, space loop below 
image

**Comment by Fox-McCloud** [comment]
I'd leave the brig alone---just make this about getting the Supermatter in.

Given that metastation is a *literal* 1:1 port (with only small adjustments where we *had* to), Yeah, do a 1:1 port of their supermatter layout, please.

**Comment by S34NW** [comment]
Sure thing @AffectedArc07, that does look better actually. I was worried the mirrored layout was going to confuse people, but thought I'd get that feedback

**Comment by S34NW** [comment]
MetaStationEngineAfter
This is the revised version, will do some testing before I pull this out of draft

**Review by Kyep — APPROVED** [review]

**Comment by AffectedArc07** [comment]
Could you add a pipe that gives an SM feed from atmos? 
image
Something like this, but not interfering with the HE pipes (iirc HE pipes and regular pipes used the same connection layer, meaning you cant stack them)

**Comment by Fox-McCloud** [comment]
You seem to have deleted a few station engineer spawns.

**Comment by S34NW** [comment]
@AffectedArc07 Yep, I can add an atmos to SM pipe. What do you think of a valved connection to the scrubbers network, like we have on cyberiad?

@Fox-McCloud A bunch of spawns are in the engineering lobby room around the table, you can see them in the bottom of the screenshot I took.

**Comment by S34NW** [comment]
Waste outlet is too tight to squeeze in the main chamber, so it has to go into the emitter room if it's wanted.
scrubberoutlet

Atmos pipe was simple to route around the HE pipes.
Atmospipe

**Comment by Kepplerx** [comment]
Does Atmos have access to SM here? I assume not, but they should have it

**Comment by S34NW** [comment]
> 
> Does Atmos have access to SM here? I assume not, but they should have it

Access is map-independent and controlled at /master/code/game/jobs/job

**Comment by S34NW** [comment]
Will deconflict when I hear that it's good to go

**Comment by AffectedArc07** [comment]
This is now in the front of the MetaStation queue, feel free to deconflict whenever

**Comment by S34NW** [comment]
should be good to go @AffectedArc07

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
