### PR TITLE
What

### PR DESCRIPTION
**Pull request by Ar3nn**
This is the first PR on the subject I dunno what your talking about.

goodbye lattices

:cl: Ar3nn
del: Gets rid of some weird lattices floating in mid-space
/:cl:

### CODE REVIEW

**Comment by Ar3nn** [comment]
Black magic abound.

**Comment by Spacemanspark** [comment]
I don't see a particular reason to remove them.

**Comment by Ar3nn** [comment]
An issue was put up and @TheDZD agreed they should be removed, so I went ahead and did it for them.

**Comment by Fox-McCloud** [comment]
fixes https://github.com/ParadiseSS13/Paradise/issues/4994

**Comment by Ar3nn** [comment]
Should be okay to merge it unless I missed something.

**Pull request merged**
