### PR TITLE
[Goonchem] More reagents

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just a few more reagents

Food Reagents
- Beans
 - Does what you expect
- Cheese Substitute
 - Will be utilized in other foods later; for now it's in cheesewheels (for irony)

Drinks
- Gin an Sonic
 - Decays into alcohol and meth; also gives silly flavor messages and makes you say silly things: Gotta go fast!

X-toniums
- Flaptonium
 - Makes a parrot on reaction
- Fartonium
 - Does what you expect 
- Fliptonium
 - Makes the mob that has it spin; the longer it's in the person, the faster they spin--also good at reducing stuns, but has a low OD level.

### CODE REVIEW

**Comment by Regen1** [comment]
Fartonium
Does what you expect

From the looks of it, most of the community doesn't like *fart, why is this being added?

**Comment by Spacemanspark** [comment]
Because we are all 6 years old.

**Comment by Iamgoofball** [comment]
Regen, they don't like the /sound/ which might not make it in.

Also, most the admins != the community

**Comment by Spacemanspark** [comment]
Players don't want the sound either.

**Pull request merged**
