### PR TITLE
Updates NanoUI so it includes new areas of maintenance

### PR DESCRIPTION
**Pull request by Citinited**
Because this hasn't been done since before the incinerator maintenance was redone.

:cl:
imageadd: NanoUI will now display the latest version of the NSS Cyberiad.
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
oww 4 commits

**Comment by Citinited** [comment]
Yeah, sorry about that, I fucked up my commits. Any way to fix that beyond restarting the PR?

**Comment by Crazylemon64** [comment]
`git checkout master`
`git fetch upstream`
`git reset --soft upstream/master`
`git checkout -b newmaps`
`git cherry-pick 805425f`
`git push origin -f newmaps:maps`

**Comment by Citinited** [comment]
That uh, closed the PR but didn't remove any commits

**Comment by Crazylemon64** [comment]
wait what

**Comment by Citinited** [comment]
I don't know either, git shell is not my strong suite

**Comment by Crazylemon64** [comment]
`git status` to see if something is amiss

**Comment by Citinited** [comment]
Okay I have a single commit and now I need to push it apparently

**Comment by Citinited** [comment]
Oh fuck it, I'll just restart the PR

**Comment by Citinited** [comment]
Done, look to 6989 for the new PR

**Pull request closed without merging**
