### PR TITLE
Fixes Fancy Table Smoothing

### PR DESCRIPTION
**Pull request by Dave-TH**
:cl: 
fix: Fancy tables now properly smooth.
/:cl:

Git closed #9921 automatically while I was resolving history problems, so here's try number two.
Fixes smoothing for red fancy tables, which is currently broken.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
@tigercat2000 It's been corrected now

**Comment by SamHPurp** [comment]
There is a git issue this closes, no?

**Comment by Dave-TH** [comment]
@SamHPurp Dunno, didn't look. I just knew it was a problem.

**Comment by SamHPurp** [comment]
Ahhhh its Gambling Table being flipped

**Pull request merged**
