### PR TITLE
Superhero Part 2: Owlman vs. The Griffin!

### PR DESCRIPTION
**Pull request by ZomgPonies**
- You get to choose from superhero: Owlman or supervillain: The Griffin
- Unique, unremovable costumes.
- Awesome Wing Toggle Action
- Refer to https://github.com/tgstation/-tg-station/pull/7942 for sprite images

### CODE REVIEW

**Comment by dannno** [comment]
gross :rabbit:

**Comment by pudl** [comment]
literally stolen

**Comment by ZomgPonies** [comment]
Stolen from a public codebase using GPL3 licensing? Get a grip, kid.

**Comment by pudl** [comment]
it's aGPLv3

**Comment by ZomgPonies** [comment]
Either way, it pretty much invalidates your comment. Well played.

**Comment by Dorsisdwarf** [comment]
I love this because it makes them actual superheroes instead of griefing wannabes

**Pull request merged**
