### PR TITLE
Keeps bumped windoors open if someone stands in front of them

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do

If you bump into a windoor and stay in front of it (or at least keep a live mob in front of it), it'll stay open. This doesn't impact the behavior of clicking windoors to keep them open indefinitely.

## Why It's Good For The Game
This should hopefully do away with the obnoxious shuffle of trying to keep a windoor open for long enough to hand someone something or reach something inside if you bumped it. Think chemfridge, for instance, or HoP's desk. Because it'll still automatically close after a little bit once you move away (shorter if the window's secured), this shouldn't cause any new security issues, but might lead to some interesting gameplay of having people hold a windoor open, like how you can jam open a normal airlock. 

## Images of changes

https://user-images.githubusercontent.com/89928798/189540259-463a84e0-d770-466e-a4d5-5ddb01b67e58.mp4

## Testing
See video.
Also, verified that clicking on the door would still keep it open.

## Changelog
:cl:
tweak: Bumped windoors will now be held open as long as someone stands in front of it.
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
Any particular reason standing _on_ the tile of the windoor doesn't also keep it open? I guess it comes up less often, but might be good to consider just for consistency on both sides of the windoor

**Comment by lewcc** [comment]
> Any particular reason standing on the tile of the windoor doesn't also keep it open? I guess it comes up less often, but might be good to consider just for consistency on both sides of the windoor

Yeah, I think that makes sense!

**Review by hal9000PR — APPROVED** [review]

**Comment by Denthamos** [comment]
Just to verify.  Someone without access to the area will not be able to keep open a windoor they do not have access to, correct?  This is a way to control people that do not belong in an area while being able to provide them a service.

IE, cargo desk, if handing an item out as the tech opens the windoor momentairly, a player that is on the desk that is not cargo should not be able to keep the windoor open.

**Comment by lewcc** [comment]
Added access control

https://user-images.githubusercontent.com/89928798/191375723-472bc743-0be7-44cc-83b6-1edb375d7076.mp4

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
