### PR TITLE
Add recipe for Iced Coco

### PR DESCRIPTION
**Pull request by biotear**
## What Does This PR Do
Adds a new drink recipe for Iced Coco.

## Why It's Good For The Game
It makes logical sense as the game already features Coffee, Hot Coco, and Iced Coffee. Having a set recipe for Iced Coffee but not Iced Coco is inconsistent. 

## Changelog
:cl: ThottieRisette
add: Added Iced Coco drink, which can be made from 1u Ice and 3u Hot Coco
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
Congrats on your first PR. Keep in mind that the changelog is what players will be seeing with the in-game changelog popup, and it should contain non-code related information. For example, to a non-coder, this doesn't make any sense:
```
7fb9517:
Added /datum/chemical_reaction/icecoco to code/modules/reagents/chemistry/recipes/drinks.dm
```
Your changelog should use the tags in the PR template you saw when making the PR: `fix`, `add`, `remove` and so forth. You can put the information you have in the changelog right now into the main body of the PR. 

Example changlog for this PR could be something like:

:cl:
add: Added the Iced Coco drink, which can be made from x, y and z
add: Added the Iced Coco reagent
/:cl:

**Comment by biotear** [comment]
> Congrats on your first PR. Keep in mind that the changelog is what players will be seeing with the in-game changelog popup, and it should contain non-code related information. For example, to a non-coder, this doesn't make any sense:
> 
> ```
> 7fb9517:
> Added /datum/chemical_reaction/icecoco to code/modules/reagents/chemistry/recipes/drinks.dm
> ```
> 
> Your changelog should use the tags in the PR template you saw when making the PR: `fix`, `add`, `remove` and so forth. You can put the information you have in the changelog right now into the main body of the PR.
> 
> Example changlog for this PR could be something like:
> 
> 🆑
> add: Adds the Iced Coco drink, which can be made from x, y and z
> add: Adds the Iced Coco reagent
> /🆑

Ah I see. Thanks for the advice, I've fixed that.

**Review by farie82 — APPROVED** [review]
Code looks good.
Not 100% on the name though. Since Hot Chocolate is written like that

**Review by variableundefined — CHANGES_REQUESTED** [review]
Approved with one reservation - Rename it Iced Cocoa. 

I cannot really find people who call it Iced Coco, but Iced Chocolate and Iced Cocoa are both name I've see nit referred to commonly.

**Comment by biotear** [comment]
> Approved with one reservation - Rename it Iced Cocoa.
> 
> I cannot really find people who call it Iced Coco, but Iced Chocolate and Iced Cocoa are both name I've see nit referred to commonly.

Alright sounds easy enough. Gimme a moment.

**Review by variableundefined — APPROVED** [review]

**Comment by variableundefined** [comment]
In the future, avoid using webedit only - try to test things out locally. It gives people confidence in your PR.

**Review by Kyep — APPROVED** [review]

**Pull request merged**
