### PR TITLE
Alternate to Bag of holding changes

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

Alternate to #20115. Bag of holding max item size has been decreased from huge (5) to bulky (4), the max weight has also been changed from 35 (7 huge items) to 28 (7 bulky items). 

## Why It's Good For The Game
BOH is a bit overpowered, but I dont think it needs a full on anomaly core for it to nerfed.

## Testing

Game compiles, changes work.

## Changelog
:cl:
tweak: Bag of holding can only hold bulky items instead of huge sized items now (no chainsaws, shotguns, etc.)
tweak: Bag of holding has a max weight of 28 instead of 35.
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
The BoH change is beautiful, absolutely love it. But the BoH change I think will lead to problems.

Wait a minute. Abbreviations don't work here. 
Uhhh, Bag of Holding changes good, don't think the Belt actually needs any changes as it does see quite regular use meaning it's performing it's function of being a minor and cheap belt upgrade effectively.

**Comment by Bm0n** [comment]
that's 7 eguns you can carry in your belt now. kind of why is wanted to remove the belt of holding was because if it were buffed it'd just be a bag of holding lite and not solve the problem at all.

**Comment by Gatchapod** [comment]
What if we just do not touch the belt of holding? I like its sprite and that is all it is good for. It doesn't need any changes, given how we're fine with satchels and trashbags of holding.

**Comment by Contrabang** [comment]
Belt of holding changes removed

**Review by Sirryan2002 — APPROVED** [review]
code is fine

**Review by farie82 — APPROVED** [review]

**Pull request merged**
