### PR TITLE
Fixes captain's disposals going straight to recycler

### PR DESCRIPTION
**Pull request by Daylight2**
## What Does This PR Do

Shifts around the disposals pipes so cappies trash doesn't get immediately recycled.

## Why It's Good For The Game
I threw my traitor objective down there once ):

## Images of changes

Before:
image
After:
image

## Testing
Rode the pipes.
Sent the captain a present.

## Changelog
:cl:
fix: Captain's disposals on the Cyberiad doesn't go straight to the recycler anymore.
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
> I threw my traitor objective down there once ):

i ded pls nerf??

**Review by 1080pCat — APPROVED** [review]
Changes are good, but wasn't caused by you, but since you're already touching this area, could you possibly remove these two random stray atmos pipes?
image

**Comment by Henri215** [comment]
Specify on changelog the station

**Review by Henri215 — APPROVED** [review]
LGTM (git gud Daylight!)

**Review by S34NW — APPROVED** [review]

**Pull request merged**
