### PR TITLE
Port over TG component improvements.

### PR DESCRIPTION
**Pull request by variableundefined**
Ports tgstation/tgstation#39864 Move signal registration from components to datums
Ports tgstation/tgstation#38798 Refactors component signals to properly register for specific signals
Ports tgstation/tgstation#38287 Signal Define

This port over various improvements made by ninjanomnom to components. 

Send Signal is assigned to a variable that is then used in a superfluous proc in order to avoid a false "Operator has no effect" & "variable defined but not used" error

http://www.byond.com/forum/?post=2374624

🆑:
tweak: Component refactor from tg made by ninjanomnom has been ported over. Report unexpected issue (with autolathe / ORM)
/🆑

### CODE REVIEW

**Comment by AffectedArc07** [comment]
and travis failed

**Comment by variableundefined** [comment]
I'm running into numerous "operation will have no effect here" and a missing parenthesis error that doesn't make sense and only appear on 511 instead of 512. The latter is fixed, but I am looking at how to fix the former, if possible.

**Comment by variableundefined** [comment]
The PR will not pass Travis on 511 due to an error that has only been fixed in 512.

**Comment by variableundefined** [comment]
Added in a way to circumvent it. It should be ready for 511 and pass Travis now.

**Pull request merged**
