### PR TITLE
The second coming of the Hyperion event

### PR DESCRIPTION
**Pull request by png103**
## What Does This PR Do
I accidentally deleted the old hyperion branch, so i made this slightly updated version of it

The crew begins in a station with the bare minimum to survive and from there, they'll need to build the rest themselves while finishing a list of objectives announced near round start

## Images of changes
hyperion

## Testing
Ran it on dream maker, walked around and everything works just fine

### CODE REVIEW

**Comment by png103** [comment]
huh i swear i already linked my account

**Comment by AffectedArc07** [comment]
Can we get some actual info on the PR please?

**Comment by png103** [comment]
how about that?

**Comment by png103** [comment]
i just realized why are there so many deletion in paradise.dm??

**Comment by Komrad822** [comment]
Well for one, command harduits, all of them need theirs (Hos, RD, CMO, Captain). CE needs to get their boots too. Saves the admins from having to spawn all these if they arent accounted for.

Also cyro cell for cloning would be a good idea since well, tier one cloning NEEDS that shit, otherwise why bother having cloning there.

**Comment by png103** [comment]
cancelling this because of personal reasons, i'm sorry

**Pull request closed without merging**
