### PR TITLE
Fix issue #10130 Claw Game gives double prizes

### PR DESCRIPTION
**Pull request by Henri23729**
## What Does This PR Do

Removed line 252 wich did execute the proc win() a second time, leading to double prizes.
## Why It's Good For The Game

Fixes https://github.com/ParadiseSS13/Paradise/issues/10130.
## Testing

- tested by playing (ALOT)
## Changelog
:cl:
fix: Claw game no longer gives double prizes
/:cl:

### CODE REVIEW

**Comment by Hematoma** [comment]
I feel like this will really change the balance of prize machines, and the whole tickets system. Is this really needed, and if so how would you keep the same balance?

**Comment by Henri23729** [comment]
> I feel like this will really change the balance of prize machines, and the whole tickets system. Is this really needed, and if so how would you keep the same balance?

From what i remember the chance for tickets to drop are only 1/5, most of the time one will only get plushies and toys coming from the claw machine.
The claw machine also has a chance to get the "Double Prize" event and can be upgraded by science for higher chances.

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Review by SteelSlayer — APPROVED** [review]

**Comment by Scribble-Sheep** [comment]
Oh, that was a bug? I thought it was just how the claw game worked.

**Comment by Henri215** [comment]
> Oh, that was a bug? I thought it was just how the claw game worked.

You forget one thing..Nanotrasen is greedy, no double prizes for the price of one :)

**Pull request merged**
