### PR TITLE
Fixes and Updates Goats

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes goats so they actually retaliate against you and attack you.

Also updates a few things from TG.

- Goats will now eat glowshrooms
- Goats attacking Diona nom their bodyparts

:cl: Fox McCloud
fix: Fixes goats not attacking people
tweak: Goats will eat glowshrooms
add: Goats will eat full grown diona
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
:eyes:

**Comment by FlattestGuitar** [comment]
>nom their boyparts

🤔

**Comment by Spacemanspark** [comment]
What

**Comment by Dave-TH** [comment]
That's meant to say "bodyparts", for the record. Big difference.

**Comment by Fox-McCloud** [comment]
Oops. Spelling corrected.

**Comment by Couls** [comment]
kyet is gonna love this

**Comment by Lunaimon** [comment]
I'm worried about random mobs having big bonuses to fighting specific player species.

**Pull request merged**
