### PR TITLE
Maps in Xenobio Advanced Cams

### PR DESCRIPTION
**Pull request by Fox-McCloud**
re-upload of: https://github.com/ParadiseSS13/Paradise/pull/4062 Minus the kill chamber

:cl: Fox McCloud
add: Maps in the slime management console to Xenobio
tweak: Reduces Xenobio monkey box count from 4 to 2
/:cl:

### CODE REVIEW

**Comment by Magikarpet** [comment]
:-1: Honestly, everyone complaining should just play a round on /tg/station with the slime console. It isn't a significant enough impact to label the PR as gamebreaking(as the 2 monkeycube box loss is already a huge enough nerf in exchange for the console by actually forcing and incentivising xenobiologists to use grey baby slimes for something), and it merely inconveniences people trying to use the console by forcing them to RCD out one of the useless chambers. 

You aren't going to use more than 5 chambers unless youre manually using the monkey recycler or hoarding extra slimes, as the return isn't enough for sustaining the slimes.The console's efficiency is 5 monkies for a cube, versus 4 monkies for a cube(with upgradable parts too.)

Also, this is ignoring mentioning that you can easily convert the kill chamber into a regular chamber with the freezer/heater availble as an extra chamber if you wish.

**Comment by fludd12** [comment]
So, er, why the -1? You seem happy with it.

**Comment by Fox-McCloud** [comment]
I think his objection is that the kill chamber should be included, not to the inclusion of hte consoles, in general.

**Comment by Earthdivine** [comment]
The general consensus was to remove the kill chamber, if you want it back you can very easily bug science to make a freezer in one, or just make it yourself since you got science access. No reason to have a room exclusively to kill Slimes when they take 3 fire extinguisher shots to kill.

I personally see this as making Xenobio extraordinarily lazy and no one will actually enjoy it, but I don't play this job so i don't care to be honest

**Comment by Magikarpet** [comment]
Seriously, just play a  round on /tg/station and try it out before you talk about it. It isn't some "ULTIMATE LAZY XENOBIOLOGIST MACHINE" with the kill chamber, @Earthdivine. if you are completley ignoring that this also scales back the monkey cubes, like on /tg/(which actually forces xenobiologists to maintain and keep a pen for grey slimes, or suffer running out of monkey cubes due to the inefficiency of the console/).

This completley ignores that actually building a freezer/heater array with proper piping requires atmos+engineering coordination in building/walling off the area and will essentially take half the round in application, not to mention that the map-detection on xenobiology consoles are incredibly incredibly incredibly awkward with newly built areas. Please, all your complaints will vanish if you actually try the thing out. I might've thought the same thing about being overpowered in the past, but just try it out and realize how many downsides there are to using the console.

To restate it, because I really do feel like putting an emphasis on them. 

1.You give up your chance to be friendly with the slimes if you exclusively use the console/freezer.

2. You actually need to go into the pen and use the slime analyzer to figure out mutation stats on slimes, so you can keep grey baby slimes with a low mutation chance, forcing you to enter into the pen regardless of method to boost your efficiency and not lose out on a dozen slimes.

3. The console recycles each monkey at a whopping 0.2 monkies per monkey recycled and cannot be upgraded. This translates to 5 monkey cubes for 1 monkey, meaning at most you will recycle and regain 2 monkies from the console. The default cubes will allow you to recycle 3, at a rate of 4 monkies for 1 cube.

4. Due to all of these, the console/freezer will actually force xenobiologists to use grey baby slimes for monkey cubes due to the change from 20 to 10 monkey cubes, actually encouraging less of the "Shove a slime you might use later into a pen" mentality, and forcing you to either go for a specific set of slimes or focus on a limited set(This will effectively leave you with 4 usable pens)

5. Xenobiology is already monotonous, boring, for next to no reward. This is why it is not played by anyone. The issue is that comparratively, every other department in science actually has a very powerful endgame set of equipment to reward those who take the time to learn, practice, and use it effectively. Chemistry has powerful chemmixes, chembombs, and healing stims. Toxins has maxcap bombs, which can easily devastate the station. RnD has the ability to print some of the most powerful high-tech gear available in the station. Xenobiology has gold slime cores for a mob army(Many of which get counted and immediately valided by greytiders who cry after hitting a blobbernaut twice and getting their face caved in... Ignoring the fact that many of the mobs are just carbon copies of eachother except hits harder and takes more damage), bluespace floortiles that require an ungodly amount of time and effort to obtain for such an ignorably weak item/value, and the ability to make speed and fireproof potions. There is no reward for preforming xenobiology well that can be compared decently to any part of the station that involves research or time.

6. Xenobiology is already monotonous, boring, for next to no reward. This is why it is not played by anyone. The issue is that comparratively, every other department in science actually has a very powerful endgame set of equipment to reward those who take the time to learn, practice, and use it effectively. Chemistry has powerful chemmixes, chembombs, and healing stims. Toxins has maxcap bombs, which can easily devastate the station. RnD has the ability to print some of the most powerful high-tech gear available in the station. Xenobiology has gold slime cores for a mob army(Many of which get counted and immediately valided by greytiders who cry after hitting a blobbernaut twice and getting their face caved in... Ignoring the fact that many of the mobs are just carbon copies of eachother except hits harder and takes more damage), bluespace floortiles that require an ungodly amount of time and effort to obtain for such an ignorably weak item/value, and the ability to make speed and fireproof potions. There is no reward for preforming xenobiology well that can be compared decently to any part of the station that involves research or time.

7.  Xenobiology is already monotonous, boring, for next to no reward. This is why it is not played by anyone. The issue is that comparratively, every other department in science actually has a very powerful endgame set of equipment to reward those who take the time to learn, practice, and use it effectively. Chemistry has powerful chemmixes, chembombs, and healing stims. Toxins has maxcap bombs, which can easily devastate the station. RnD has the ability to print some of the most powerful high-tech gear available in the station. Xenobiology has gold slime cores for a mob army(Many of which get counted and immediately valided by greytiders who cry after hitting a blobbernaut twice and getting their face caved in... Ignoring the fact that many of the mobs are just carbon copies of eachother except hits harder and takes more damage), bluespace floortiles that require an ungodly amount of time and effort to obtain for such an ignorably weak item/value, and the ability to make speed and fireproof potions. There is no reward for preforming xenobiology well that can be compared decently to any part of the station that involves research or time.

8. The kill chamber doesn't instantly kill slimes. The walking around bit for executing slimes has to be one of the worst functionalities of it. I would compare it to the "lol guess what plant stat this gibberish is xD" functionality of the old isolation centrifuge, the RNG radiation of viro2, the old "reliability" locking of items behind RnD, and the annoyance of having to walk to chemistry to ask chemists who either want to conserve chem energy for medicines or are dicking around for mutagen/acid. It does nothing to enhance or challenge anyone, it adds no substance, and it provides nothing of a net positive or negative. It's just another monotonous trek. The console will already ruin new xenobiologists who don't know how to manage their monkey cubes properly due to the rapid shift in the number of cubes, and the requirement of using grey slimes. 

This really feels like a lot of people who are afraid of change, thinking it'll be awful. I'd like to know an explanation for why people view the kill chambers/xenobiology console as this "epic unbalancing force" for a job that is superiorly powered to every other. It's really just another tool to aide xenobiologists if they wish to use it. They both have their downsides and benefits.

**Comment by tigercat2000** [comment]
@Magikarpet Copy-pasting a huge paragraph 3 times to increase the height of your post isn't acceptable, knock it off.

General consensus was "we would be more okay with this if the kill chamber was not included". It could be added at a later date if people get more used to the new camera console. You shouldn't expect people to "go play on -tg- and try it out".

**Comment by Rumiluntti** [comment]
Still unnecessary buff.

Getting friendly with the slimes in made obesole with this system anyways.
You can get enough monkey cubes from a single generation of grey slimes if you use a fully upgraded processor. The reduction in monkey cubes is super irrelevant.
Golems, loyal mobs, timestop, fireproof potions, weightlessness potions, mutation toxins (these are actually hilariously potent reagents). "qq no reward!!"

This is literally lazymode.

**Comment by Regen1** [comment]
:-1: No

This makes xenobio incredibly lazy and too damn easy for the things it can yield.

**Comment by Spacemanspark** [comment]
My opinion is till :-1:.
Like everyone else has said, this just makes it easy and lazy.

**Comment by Necaladun** [comment]
50/50 on this. Taking out monotony is good, but it's also reducing some of the challenge. It's good to get some use out of the advanced systems like this console.

The kill chamber being gone is good - that's something that there really should be some risk involved. Going to pick up a xenobiologist who is dying is kinda routine for paramedics, I'd hate to lose that.

This is one of those jobs (Well, aspects of science now, since it's no longer it's own job) that doesn't rely on anyone else, and serves only to get fun toys for yourself. Making it easier, and with less risk, I don't think is a good change...

So that'd make me at least 70/30 against, thus :-1:

**Comment by Fox-McCloud** [comment]
I really question how many here actively do or have played Xenobio for any length of time (aside from @Magikarpet). The job is a boring grind, to say the least that already has zero risks associated with it if you know what you're doing (unless, of course, you arrive halfway through the shift, then you have to put up with hostile slimes and getting glomped even if you're skilled).

This is QoL, at best, for Xenobio; instead of having to fight the glass doors opening and closing in your face 50 times in the shame shift, while dragging things back and forth repeatedly, for a single slime pen, you can move them around with this alternate way. 

You're still going to have to scan them for the best mutation rates and you're still going to have to dedicate extra time to raising grey slimes, as @Magikarpet has stated.

With the exception of @Fullofskittles every Xenobiologist I've spoken with or has gotten to demo this, in game (as it's already technically in the files) has enjoyed using the piece of equipment immensely.

**Comment by Mijhead** [comment]
I agree with @Rumiluntti 's points on this; And before you accuse me of not playing xenobiology a lot, I've actually taught a considerable amount of people how to play xenobiology, including how to befriend slimes. This would make the job quicker, lazier, and yield the same incredibly strong rewards at less time investment, which has also been something R&D has been worked on to prevent.

**Comment by Rumiluntti** [comment]
I play xenobio almost every time I play science.
Of course the xenobiologists would love the buff, it's just not needed, at all.

It's already easymoded to shit with the processor that can be upgraded to vomit 4x cores per slime.

**Comment by Necaladun** [comment]
As far as monkeys go - it's really not hard to order more from cargo. I don't see that as a problem.

The issue comes down to a risk/reward thing. Xenobio has always been one of the jobs with risks if not handled with high skill. If I'm correct that this removes the risk from it, then I have a major problem with it - jobs like this, with the potential rewards available, should have risks associated.

The QoL stuff for tedious shit is great, but if things like the glass doors are an issue, surely there are better ways to handle it.

**Comment by Fox-McCloud** [comment]
>The issue comes down to a risk/reward thing. Xenobio has always been one of the jobs with risks if not handled with high skill.

It's already a zero-risk job (unless you come in in the middle of the shift and they're starved half to death) though. Xenobio starts with 8 plasma sheets. Feed 4 sheets to both slimes--now they're your friends forever, as are all their offspring---they won't attack you, ever, unless you let them get insanely insanely hungry. On average it takes adult slimes 44 minutes and baby slimes 1 hour and 44 minutes for their nutrition levels to drop low enough that they'll start even rolling for the *chance* to lose one level of friendship....so in practicality, it's already a zero risk job.

**Comment by Spacemanspark** [comment]
Why are we making it less of a skill based job when it should be more of one, then?

**Comment by Fox-McCloud** [comment]
>Why are we making it less of a skill based job when it should be more of one, then?

What. It was never a skillful job to begin with.

**Comment by Spacemanspark** [comment]
And that's the problem right there.

**Comment by TheDZD** [comment]
@Spacemanspark Except this isn't a question of skill at all, it's quite literally just a knowledge barrier. If you know that you can feed plasma sheets to slimes, you are never in any sort of danger in xenobio anyways. If you don't, you might on an off-chance get glomped by slimes and waste 15+ minutes getting cloned/broken bones set.

**Comment by Necaladun** [comment]
I was quite unaware of the plasma sheet feeding thing myself, which really is a problem with removing the risk from the job all together.

If that's the case, then this doesn't make the job any less risky, just less tedious and perhaps faster...to a hesistant :+1: from me. I think it still needs a lot of work to make xenobio more...useful to the rest of the station, or at least have more risk for the personal rewards. 

But those balance features are outside of the scope of this PR, and I think this console would make it easier to add new features along those regards.

**Pull request merged**
