### PR TITLE
Soap QOL

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
:cl: Tayyyyyyy
tweak: You only need to click once to clean a floor
/:cl:

If you click on a turf, it cleans off all the cleanables off the turf. If you click on a blood spot on a turf, it cleans the entire turf too. This reduces the need to click each turf 10 times with soap to fully clean it.

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
I actually like having to click and scrub more for more dirtier floors

**Comment by alexkar598** [comment]
^^^^

**Comment by davidchan13** [comment]
Don't really care one way or another about this. Can already stack multiple clicks onto the same tile so this isn't a huge change. But it does make the mop pretty much obsolete.

**Comment by Tayyyyyyy** [comment]
@davidchan13 soap has a slower clean speed than the mop

**Comment by Vivalas** [comment]
We're on this slippery sloap again? Soapcreep is no joke.

**Pull request merged**
