### PR TITLE
Adds in Rings

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in rings (the kind you wear)

From SuperSayu station

Use a welder on a gold, silver, iron, uranium, or plasma coin and it will become a wearable ring; these don't do anything and are purely for decorative/roleplay reasons.

Para unique changes to them:
- Can socket rings with a diamond to make them a studded ring (non-reversible!)

Related

- Chaplain's locker starts off with 2 silver rings and 2 gold rings

pics:
ring1
ring2

Other
- Boxing gloves aren't species restricted anymore

### CODE REVIEW

**Comment by TheDZD** [comment]
Screenshots?

**Comment by Nienhaus** [comment]
So you can't wear a ring and gloves?

**Comment by Fox-McCloud** [comment]
Sadly no on-mob pixel and you can't wear them with gloves.

**Comment by SirBloodBuske** [comment]
Must haves shinies!

**Comment by Regen1** [comment]
Someone make some rings which leaves peoples face imprinted with the insigna
Phantom

**Comment by veganzombeh** [comment]
These are really nice. :+1: A tiiny mob overlay would be nice, though.

**Pull request merged**
