### PR TITLE
Refactors Simple Animal Death and Implements Spawners

### PR DESCRIPTION
**Pull request by Fox-McCloud**
TG's simple animal death refactor

- Mobs that need to be deleted on death now just have to have a var set instead of specifying `qdel(src)` and `ghostize`
- Adds in support for simple animal death messages to all simple animals
- Adds in supports for simple animal death sounds to all simple animals
- Removes the snowflake and unused Vox Armalis simple animal (we have the actual Armalis species for stuff)

Also adds in mob spawners--currently unused (:wink:), these are a simple animal sub-type that can spawn mobs at periodic intervals, up to a cap.

:cl: Fox McCloud
add: Adds in simple animal mob spawners
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Not a clue why that's failing, given that I can literally open every single metastation map.

**Comment by Fox-McCloud** [comment]
Ahh, just Travis randomly failing 4noraisin.

**Comment by Earthdivine** [comment]
Would we be able to spawn the Spawners and set what kind of mob would be spawned and how often or it is strictly a mapping tool?

**Comment by Fox-McCloud** [comment]
You can var edit the time and the mob they spawn (provided it's a simple animal)

**Comment by Spacemanspark** [comment]
There's no check in place to ensure it only spawns simple animals?

**Comment by Fox-McCloud** [comment]
We cannot account for every single case of admin var edit shenanigans, nor should we.

**Comment by Spacemanspark** [comment]
Fair enough.

**Comment by HereticChurch** [comment]
> Removes the snowflake and unused Vox Armalis simple animal

But that means I won't be able to lag the server to hell by accidentally killing one with spiders.

**Pull request merged**
