### PR TITLE
Removes Russian Revolver from Bartender and Cyberiad Map

### PR DESCRIPTION
**Pull request by Quantum-M**
## What Does This PR Do

Removes the Russian Revolver from the Bartender and the two mapped on the Cyberiad Map
## Why It's Good For The Game

The Russian Revolver seems to be very LowRP (that's not taking into account the potential excess medical attention/brain destroying chance it can have), along with it clearly being a noob trap.
## Changelog
:cl: Quantum-M
del: Removes Russian Revolver from Bartender
del: Removes Russian Revolver from Cyberiad Map
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
So, I'm just gonna ask why this is seen as such a big problem. It's a funny item with a good joke attached to it, on examine it even hints to what it does pretty blatantly. I've seen maybe ~3 people accidentally shoot themselves with it and none of them got mad about it, infact most thought it was hilarious. Frankly, I don't understand this and I would like to hear your reasoning behind this.

**Comment by AffectedArc07** [comment]
I'm not in favour of this, *especially* from someone who hasn't even logged in for over 4 years (You were last seen 2018-02-04, unless you are multikeying without informing us)

**Comment by meow20** [comment]
Honestly the game is filled with noob traps and at this point they are very iconic for ss13 and removing them would be like removing the clown.

**Comment by dearmochi** [comment]
In addition to what @AffectedArc07 said, the end of the feature freeze doesn't mean you can make pull requests with the expectation that they'll be merged. Consulting leadership over potential pull requests (especially feature removals) remains a crucial step and so far I've been disappointed.

For these reasons I am formally objecting to this.

**Comment by Quantum-M** [comment]
I have been playing for a while now recently, @AffectedArc07 .

Very well, @dearmochi , closing PR then.

**Pull request closed without merging**
