### PR TITLE
Paranoid sanitization now allows parentheses and common punctuation

### PR DESCRIPTION
**Pull request by Crazylemon64**

### CODE REVIEW

**Comment by LightFire53** [comment]
http://static.tvtropes.org/pmwiki/pub/images/weirdalfoil_2322.jpg

**Comment by LightFire53** [comment]
image

**Comment by Crazylemon64** [comment]
I have no idea what punctuation is safe but I do know that these: \`%$ are bad news

**Comment by Anticept** [comment]
It depends on the shell. Most of them follow a common standard, but what you should do is find some way to check what shell is running, and then the paranoid sanitation allows known safe characters for that shell.

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
