### PR TITLE
Medical Hypospray

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in medical hyposprays. Inspired by Goon.

Medical hyposprays differ from regular hyposprays in a major way; they can only be loaded with safe and approved medical chems. If they work in a medical patch, they work in the medical hypospray.

In addition to this, they will loudly announce to people in the area who has injected whom with what primary reagent in what amount, in addition to playing an injection sound.

If you emag a medical hypospray, it removes its safeties, and it can inject any reagent; that said, it'll still loudly announce who is doing the injecting and still play a sound, so it's still not exactly stealthy.

They can be made in an autolathe. Medical vendors come stocked with 2.

:cl: Fox McCloud
add: Adds in medical hyposprays
/:cl:

### CODE REVIEW

**Comment by Necaladun** [comment]
Possible to also then rename the cmos hypo to something like "prototype hypospray" to avoid confusion/add clarity?

**Comment by Fox-McCloud** [comment]
All of them already have different names.

The combat one is "combat stimulant injector", the CMO's is "Hypospray", and this one is "Medical hypospray", so they have differentiated named.

The medical hypospray has a different sprite, as well.

**Comment by Anasari** [comment]
I support this change, injectable is too weak compared to patch & pills in the current medical system, this should help make it more relatively useful.

**Comment by FalseIncarnate** [comment]
The theft objective lists "a hypospray", but specifically checks for the CMO hypospray path. You really need to rename the CMO one and adjust the theft objective text to match, or else you're gonna be causing a lot of confusion when people steal a medical one because they aren't aware it won't count based on the text and name.

**Comment by Renaultius** [comment]
Is the regular hypospray even worth being a steal objective at this point? It doesn't seem terribly different than the medical one from what I know of each thus far; it's certainly better, but that's about it. Especially since half the time stealing the hypospray actually means stealing it from Chemistry.

**Comment by Spartan6** [comment]
Do rename the CMO one, I’d go as far as to say get a sprite difference.

**Comment by R1f72r** [comment]
@Spartan6
Fox already said there was a sprite difference

**Comment by Spartan6** [comment]
So no sprite in OP REEEEE

**Comment by Fox-McCloud** [comment]
It uses the same sprite as the combat hypospray, since it's distinctively different and barely seen (outside of nuke ops).

the steal objective for the hypospray has been updated to clarify that it's the CMO's hypospray and not just "a hypospray".

**Pull request merged**
