### PR TITLE
Nerfs the basic plasma cutter. Yep.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## What Does This PR Do
- triples the charge required to fire one shot with the BASIC (read: **NOT ADVANCED**) plasma cutter. This means you now only get 13 shots (and 2% left) from a full mag. 
- removes a bonus shelter capsule from the plasma cutter kit (also renames it to just "plasma cutter")
- gives paramed a drill instead of a cutter

## Why It's Good For The Game
Remember #22153? I have SEVERELY underestimated basic cutter's power. I have, accidently, created a new meta and I'm not sure whether I like it.
I thought a while about how to make it more balanced - my idea was messing with it's charge.
The more a shot costs, the more you have to recharge. The more you have to recharge, the more plasma you waste. The more plasma you waste, the less points you get from ORM.
I don't want to fully kill the option - I just want to make it have SOME kind of a downside. Maybe it will still be meta, who knows. We'll see.

An alternative to this would be decreasing power gained from a plasma sheet, which is actually less of an early game nerf, so not exactly what I'm trying to do here.

As for the free shelter capsule removal - it was NEVER needed. I added it in fear this beast will be too weak, which was rather foolish of me now that I think about it.

I've been reminded in discord that paramed also gets a plasma cutter - since it will be worthless for paramed after the nerf, most people seemed to agree that they can just get a drill instead.

## Testing
Spawned in, redeemed my voucher for a cutter, shot into the void a bit.

## Changelog
:cl:
del: removed the free shelter capsule from plasma cutter kit in mining vendors
tweak: basic plasma cutter now takes 3x the charge to fire
tweak: paramedic now gets a drill instead of a plasma cutter
/:cl:

### CODE REVIEW

**Comment by Venuska1117** [comment]
if you are nerfing plasma cutter, can you at lease leave shelter capsules? considering you would need now more shoots with mean more time need to mine stuff, it kinda ask to get ash storm blasted in face. (at least from my experience)

**Comment by Sadhorizon** [comment]
Free capsule is REALLY irrelevant, and by all means a mistake with original PR.
You will get the advanced one anyways, before second storm hits, so it's not like it's relevant either.

**Comment by Venuska1117** [comment]
> Free capsule is, by all means a mistake with original PR. You will get the advanced cutter before second storm hits anyways, so it's not like it's relevant either.

hmm... what about low pop?

**Comment by ppi13** [comment]
Let me get this straight.  
So you are increasing the cost of firing the from 150% more then the advanced plasma cutter to 450% more
on top of the fact that the basic already has a 33% greater delay then the advanced version.
So change to 13 shots from 40, versus the advanced version, who has 100 shots.
And its still worth it for the paramedic, since you can also use ore to charge it with, more so since the paramedic dont even really need to connect it, sure its only charges for 500, so this makes the advanced plasmacutter 7.7 times better, just powerwise.  

This seems like a heavy handed nerf, of nerfing the basic cutter back into obscurity, and its not like points matter, at least not the amount you lose by using ore over sheets, even at this rate, its only 15 points or 20.5/25.5 depending on level of upgrade, and the only thing you really need point wise is a jaunter, since like you said, you will go back before the second ash storm, so you will still have your starting capsule.  

While nerfing something is fine, this is too heavy handed of a nerf.

**Comment by Sadhorizon** [comment]
> And its still worth it for the paramedic, since you can also use ore to charge it with, more so since the paramedic dont even really need to connect it, sure its only charges for 500, so this makes the advanced plasmacutter 7.7 times better, just powerwise.

The paramedic change was very chaotic, I might revert it.

> This seems like a heavy handed nerf, of nerfing the basic cutter back into obscurity, and its not like points matter, at least not the amount you lose by using ore over sheets, even at this rate, its only 15 points or 20.5/25.5 depending on level of upgrade, and the only thing you really need point wise is a jaunter, since like you said, you will go back before the second ash storm, so you will still have your starting capsule.
> 
> While nerfing something is fine, this is too heavy handed of a nerf.

The original design idea was for it to be an early game option that kinda sucks beyond that. triple the charge MAY be too much tho, yea. I might change it to 2x the cost + 1/2x the recharge rate, making it possibly less annoying to use?

**Comment by ppi13** [comment]
That could be possible, its hard to say, and dont forget that the range between the basic and advanced is different, basic has 3, and advanced 5

**Comment by Sadhorizon** [comment]
> That could be possible, its hard to say, and dont forget that the range between the basic and advanced is different, basic has 3, and advanced 5

Issue is, you can get the basic cutter for free, roundstart. I could just remove it from the voucher and forget about it, but I really like the concept.

Even in current state, it's WAY stronger than anything else in there.

**Comment by Sadhorizon** [comment]
After some thinking, paramed can have the drill roundstart. You can VERY fast get adv. plasma cutters from RnD - drill is meant to be more of a roundstart option, and roundstart option doesn't have to be good, it has to work.

**Comment by Rurik123** [comment]
You deadset on triple the charge cost?

As far as I understand the plasma cutter needs the nerf, but that might be bit heavyhanded. I will admit though, I'm not a mining main nor do I play mining, so perhaps triple is the way to go

**Comment by Venuska1117** [comment]
I have alternative how to solve issue with plasma cutter, i will write it later after work, and you will tell what you think about it.

**Comment by Sadhorizon** [comment]
> You deadset on triple the charge cost?
Not at all. I do believe it's not too much of a nerf however. I'm changing this with a free round start cutter in mind. As it is right now, you can cut through absurd 120 rocks before even needing to reload.

I may change it to twice the charge and half recharge rate instead, as it'd make it less annoying to use.

> I have alternative how to solve issue with plasma cutter, i will write it later after work, and you will tell what you think about it.

I'll be very interested to see it!

**Comment by Sadhorizon** [comment]
The point is not REALLY to nerf the cutter. Rather, I want to give it SOME kind of a downside.

The problem is not the material gain itself, it's material gain when compared to the price - 120 rocks for one refined plasma sheet. That's kinda absurd, and by all means applies to the advanced cutter too (500 for one)

**Review by Henri215 — APPROVED** [review]

**Review by Sirryan2002 — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
