### PR TITLE
Add option to reject adminhelps

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Mods and up can now reject adminhelps through the "REJT" button. This will send a clear message to the player that their adminhelp has been rejected and that they will have to try again. Ported from /tg/.
2) Clears up the singularity log message, which had a message that never triggered.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
:-1: to the ahelp rejection. this has been considered/discussed before, and was ultimately shot down because it would effectively encourage admins to ignore ahelps and lead players to believe admins held a grudge against them. the intent is good, but the method is highly questionable.

:+1: to cleaning up log messages though

**Comment by Earthdivine** [comment]
Just like False said, even if it's the same as ignoring the Ahelp, the player will know that it was rejected and that can cause far more problems then assuming the Admins are busy.

>The intent is good, but the method is highly questionable.

**Comment by Markolie** [comment]
The reject button shouldn't be used lightly though - it should only be used if someone's a derp and they adminhelp "OMG THIS GUY KILLED ME HALP ADMIN PLS". Instead of ignoring it, admins can reject it, which will explain to the user the requirements of a proper adminhelp. I trust our admins/moderators not to abuse/misuse the feature.

**Comment by SamCroswell** [comment]
I think clear communication of an adminhelp's status is better than simply ignoring it and leaving the player wondering.

**Comment by Alex6511** [comment]
For mentors and questions, can we just have a button to link the picture of the crab for when people ask to be antag? (or how to make baby)

**Comment by Earthdivine** [comment]
Thinking about it, I trust our admins to not abuse it and not use it as a means to not do work. 

Will this be logged under an admin log when it's used?

**Comment by Spacemanspark** [comment]
Looking through the commit, it seems to.

**Comment by Markolie** [comment]
Yes, it has full logging.

**Pull request merged**
