### PR TITLE
Adds a triple beep sound to a variety of assembly receivers

### PR DESCRIPTION
**Pull request by Toastical**
## What Does This PR Do
Adds a triple beep sound to a variety of beeping signal giving items. The sound was sourced from /tg/station and attributed in sounds/Attributions.txt

## Why It's Good For The Game
Gives auditory feedback and sounds nice!

## Images of changes

https://github.com/user-attachments/assets/23cd731c-9ddf-4029-8bd5-d02ddd1a419e

## Testing

Used a remote signaler alone, on a door and on a ttv. Enabled receiver on my own signaler and tried pinging it using itself. It does not ping itself.

Tested each signaling device on its own.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: Added a triple beep sound to a variety of assembly devices.
/:cl:

### CODE REVIEW

**Comment by chuga-git** [comment]
Where was this sound sourced from?

**Comment by Toastical** [comment]
> Where was this sound sourced from?

sound/machines/twobeep.ogg in the repo

**Comment by Bm0n** [comment]
steal the TG beep for this so i don't get PTSD every time someone uses the holopad call function

https://github.com/tgstation/tgstation/blob/master/sound/machines/beep/triple_beep.ogg

**Review by Burzah — APPROVED** [review]

**Review by BiancaWilkson — APPROVED** [review]
Looks good to me, thanks for the great testing video!

**Pull request merged**
