### PR TITLE
Terror Spider away mission pipes & vents

### PR DESCRIPTION
**Pull request by Kyep**
Fix number 3 fixes a bug that prevents most away missions from loading correctly.
Other changes in this PR affect only the Terror Spider away mission.

**1st fix: pipenets**
Right now, there are two of them, and not actually connected in the middle like they should be:
ts_aw_fix_middle_before

Fixed version:
ts_aw_fix_middle_after

This fix enables spiders to ventcrawl to the west side of the mission. Prior to this fix, the west side of the mission is safe from wandering spiders, which was not intended.

**2nd fix: gateway room vent**

The second fix relates to the Gateway room. Before, it was like this:
ts_aw_fix_west1_before

Now, I have deleted its welded vent:
ts_aw_fix_west1_after

The reason for this deletion is that the vent was originally there before I created brown terrors, but now brown terrors exist, it needs to be removed to prevent people getting jumped on the second they enter the mission, before they've had a chance to even draw a weapon.

**3rd fix: air alarm runtime**

Prior to this PR, https://github.com/ParadiseSS13/Paradise/commit/7d8c9a731aed533e3ed048fad50bec4c3b33d492 made some changes that broke air_alarms, resulting in runtimes/failures during map load, which looked like this: https://cdn.discordapp.com/attachments/262109452457476096/450406092036505602/unknown.png

This PR edits alarm.dm so that instead of these problems causing the entire away mission to fail to load, they instead generate 'soft' runtimes that show up in the log, and point out exactly what is going wrong, but don't stop the map loading, and don't cause any other issues.

Example: 
[2018-05-27T15:39:22] Runtime in code/game/machinery/alarm.dm,242: Air alarm /obj/machinery/alarm lacks alarm_area and areaMaster vars during proc/master_is_operating()

**Many away missions (MO19, UO45, blackmarketpackers, centcomaway, terrorspiders) completely fail to load, and must remain disabled, until this fix is merged.**

**1st tweak: unnecessary / bad setting queen room vents**
Before:
queen_old

After (simply deleted two pointless vents):
queen_new

**2nd tweak: ID upgrader light**
The ID upgrade machine in the second room now has a soft blue glow to make it more obvious. Before:
console_old

After:
start_new

**3rd tweak: nest size**
Before, the queen attempted to maintain a spider count of roughly 25.
Now, she will attempt to maintain a spider count of roughly 35.
(There are approximately ten vents on the west side of the map, vents that spiders could not crawl to before the pipenet fix. Now, they can. This tweak ensures that the density of spiders remains about the same, instead of the pipenet fix dramatically lowering spider density, and thus difficulty, for the whole mission)

🆑 Kyep
fix: The Terror Spider away mission now has spiders colonizing the west side of the map. Only the gateway room is safe.
/🆑

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
img
WHAT THE FUCK THAT'S A LITERAL SEXDECIMAL WALL

**Comment by FreeStylaLT** [comment]
YOU CAN FIT A FUCKING ROOM IN THERE WHO MAPPED THIS

**Comment by Kyep** [comment]
@FreeStylaLT I want to keep this as a fix PR. That means I probably shouldn't start doing unrelated improvements. If you really care about that bit, ask me again after this is merged. I'll edit improve it myself, or invite you to do so.

**Comment by KasparoVy** [comment]
I was wondering how long it'd take to detect the ascended architecture.

**Comment by Kyep** [comment]
@mapdiffbot

**Pull request merged**
