### PR TITLE
R&D Update: Implants and Autolathes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
An update to R&D, focusing on a lot of the missing items we lack from TG.

Minor things first:

- Adds the destination tagger and hand labeler to the autolathe

Major Things: 

Updates A lot of implants
- Most implants have an origin tech on them now
- Freedom implant buffed to always have 4 uses instead of random between 1 and 5
- Adrenaline implant updated to TG's version (a stimulative reagent instead of meth).
 - This uses a new reagent that makes you stun resistant, move faster, and minorly heals you if your health is lower (doesn't have negative side effects unless you OD, as well).
- Implant Cases and Implanters with implants inside them now have their origin tech set based on the implant they hold.
- Added the following implant related items to R&D:
 - Implanter
 - Empty Implant case
 - Adrenaline implant case 
 - Freedom implant case (this is far more expensive than the last time we had it, long ago).

Side note: Implant code is absolutely AWFUL.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Don't really like the destination tagger sprite, to be honest. Other than that, all great.

**Comment by Spacemanspark** [comment]
Eh, I prefer the current destination tagger sprite.
Other than that, :+1:

**Comment by Nienhaus** [comment]
@tigercat2000 </3

**Comment by theColdflame** [comment]
Wait, does this give R&D the ability to print off traitor implants? I don't really see why R&D should have access to them, unless they require a pretty high level in illegaltech

**Comment by Fox-McCloud** [comment]
Levels 5 and 6 respectively--the highest you can currently reach, without having access to uplink traitor gear is 4...so in order to produce these, a traitor is going to have to be active+caught or an R&D person is going to have to sacrifice some of his own gear.

**Comment by Fox-McCloud** [comment]
reverted the sprite.

**Pull request merged**
