### PR TITLE
Add the Zippo and the Feminine Jumpsuit to the loadouts.

### PR DESCRIPTION
**Pull request by PigeonLord**
37097427-082cccc6-21e1-11e8-94f5-56f2f9624577

Pretty self explanatory. These two items have been requested for a long time, so it seemed obvious to me i should've added them.
🆑  Piccione
rscadd: Added the Zippo and the Feminine Jumpsuit to the loadouts.
/ :cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
A... feminine jumpsuit? Aren't jumpsuits supposed to be one-size suits all? I've never seen it so I don't know what it is

**Comment by Aurorablade** [comment]
Yes they are supposed to be one size and you need to add a screenshot of the sprite

**Comment by Tayyyyyyy** [comment]
[Rompers are technically jumpsuits](https://misswilliamspetites.com/2014/07/03/whats-hot-right-now-jumpsuits-and-rompers/), and there are now male rompers...so a feminine jumpsuit could totally be a thing? Though I have no idea what it looks like so idk if it would be reasonable to call it a romper, since rompers are usually less than knee length.

**Comment by RyanSmake** [comment]
@Aurorablade He did not add a new sprite.

_This is apparently something that always existed._

**Comment by Aurorablade** [comment]
Considering I don't even know what it is it still needs a screenshot and we still maintain the one size fits all deal in regards to jumpsuits.

**Comment by Tayyyyyyy** [comment]
Agreed, it's still good practice to put in the screenshot. Here's what it looks like:

capture

I think that's rompery enough to be called a romper...

**Comment by taukausanake** [comment]
_This is so weird_

So there's only one color? That's weird. If we had all the colors of the rainbow I'd make it kind of like backpacks/satchels on character creation and give the option to having a jumpsuit or romper. Then again only assistants would have access to these so maybe not

**Comment by Spartan6** [comment]
I really do not like this.

**Comment by Citinited** [comment]
It only existed via the chameleon jumpsuit, which is probably why you lot have never ever seen it before :D

**Comment by PigeonLord** [comment]
>and you have to do some work to get the zippo (the superior option).
Which is why i made the Zippo cost 2 loadout points instead of one.

**Comment by Spacemanspark** [comment]
I'm fine with the jumpsuit but the zippo shouldn't be in the load out.

**Comment by Spartan6** [comment]
Replace the zippo with the cheap lighter.

**Comment by PigeonLord** [comment]
Give me one (1) good reason why the zippo shouldn't be in the loadout

**Comment by Spartan6** [comment]
Because not everything is meant to be fed to you. There are a few zippos on the station.

**Comment by Spacemanspark** [comment]
Because you're supposed to work for the Damn thing.

**Comment by Citinited** [comment]
> Which is why i made the Zippo cost 2 loadout points instead of one.

Not really the point but okay

**Comment by tigercat2000** [comment]
:-1: on the zippos. They're intentionally rare and more valuable than cheap lighters. 
As for the suit, it's kinda a meh sprite.

**Comment by tigercat2000** [comment]
Yeah, no. Zippos are meant to be rare and the "feminine jumpsuit" is just flat god-ugly.

**Pull request closed without merging**
