### PR TITLE
Add door locks to toilet stalls

### PR DESCRIPTION
**Pull request by datlo**
OCCUPIED! Can't a man buy a desword in peace?!

Add door locks to toilet stalls, bolting the airlock when pressed.
image

🆑
add: Added door locks to arrivals and dorms toilet stalls.
/🆑

### CODE REVIEW

**Comment by farie82** [comment]
finally a man can shit out his e-sword in peace.

**Comment by Spartan6** [comment]
I would rather you add dorm rooms.

**Comment by Superhats** [comment]
Is this where i'm gonna ~~ERP~~ RP taking shits?

**Comment by FreeStylaLT** [comment]
I highly suggest waiting until the christmas gets removed before adding something like this -- it'll prevent unnecessary headaches when reverting Christmas.

**Comment by datlo** [comment]
Fixing map conflicts.

**Comment by datlo** [comment]
I hate map conflicts SO much.

**Pull request closed without merging**
