### PR TITLE
Incinerator Access Adjustments

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ok, the grief is getting old, and this probably should have been done a long time ago.

Incinerator now has an atmos airlock on it that requires, naturally, atmos access.

The lootdrop spawner inside the incinerator was moved to the maintenance tunnel near the pod bay.

### CODE REVIEW

**Comment by Markolie** [comment]
Typo in the door name. Incent instead of incen.

**Comment by Fox-McCloud** [comment]
Yup, just pushed a fix for that as you mentioned it =p

**Comment by FalseIncarnate** [comment]
The incinerator is a nice concept that simply doesn't work. If items actually burned, I could see it being more openly accessible for the sake of burning trash, but that's not the case.

I would not be sad to see the room go entirely and be replaced with a new maint room or such.

:+1: for making it slightly more tedious to grief with it.

**Comment by Earthdivine** [comment]
If this is to stop Grief, wouldn't it be better to just remove the Giant canisters of Plasma and Oxygen and have ports there instead?

**Comment by TheDZD** [comment]
Merge conflicts.

**Comment by Fox-McCloud** [comment]
Just going to re-upload this; map conflicts are too tedious to resolve vs just doing it over.

**Pull request closed without merging**
