### PR TITLE
Cargo

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Cargo Restructuring

Cargo has been long overdue for reorganization and restructuring; lots of crates are poorly organized, and a terrible amount of crates (particularly security and medical) have a lot of overlapped items with other crates.

What this does is organize crates in a more logical fashion according to more well defined groups; this will not only make it a bit easier to find crates for players, but will make adding in additional new crates far easier for coders.

Notable crates that were removed: 

-Thermo Electric Generator (may be re-added later when it's functional and actually makes power)
-Cargo Tug (redundant with MULEs and chute delivery, not to mention this has a lot of abusive uses like traveling in space, blocking lasers, etc).
-shotgun shell crates (this is what the autolathe is for)
-fabric crate (literally useless)
-Cael's shield generators (the really overpowered ones that can cover half the station)

Notable Crate Additions
-Pug 
-Butterflies
-Security Clothing  (contains corporate jumpsuits and caps)
-Bulletproof helmets
-Exile Implants
-Plasteel
-Sandstone blocks
-Emergency supplies (medibots, floorbots and internals)
-Firefighting Equipment 
-Religious supplies

Crates will be vastly different in the supplies they contain, but the overall items that are available IN cargo are, overall, the same--meaning that You can still get Riot suits and helmets, but they won't necessarily be packed together with a whole ton of other supplies.

Other---Implemented a number of items tied with cargo, such as:
-Pug (another dog breed...far inferior to corgis =p)
-Butterflies (simple animal; great for spamming the halls with and making everyone want to murder them)
-A few lawyer jackets and suits
-a few suit jackets
-Formal assistant uniform

Known Issues/Bugs
-Had to disable supply pack datum garbage collection ("AM.loc = null") or else it would cause runtimes with every single cargo datum.
-"HEADER" appears as a crate under materials for some unknown reason; haven't been able to pin down why as it's exactly like every other header entry.

### CODE REVIEW

**Comment by fj45** [comment]
The shottie shell crate was sometimes useful for when you needed a good supply of shells, very quickly. Such as during a xeno round.

**Comment by Fox-McCloud** [comment]
@fj45 

It takes 4 minutes+shuttle warm up time+shuttle dock time+Bay's arbitrary 'make the shuttle late for no reason' to order some shotgun sheels. If you combine the former fact with the autolathe's ability to now print 10 and even 25 items? It's almost never worth it to order shells.

**Comment by fj45** [comment]
Ah, didn't realize the autolathe could stack up orders now, that's fine then.

**Comment by Artorp** [comment]
I think the autolathe multiplier only works on sheets (metal, glass, rods). The ability to stack up orders would be awesome.

**Comment by Fox-McCloud** [comment]
@Artorp 

I stand corrected. Yeah, would be a good feature to have, especially since the protolathe has it.

**Pull request merged**
