### PR TITLE
Gives the chaplain a soulstone on the Cyberiad

### PR DESCRIPTION
**Pull request by Markolie**
This gives the chaplain a soulstone on the Cyberiad map, like he currently does on MetaStation. It can only be used once though, so use it wisely. It's underneath the null rod on his desk.

I also replaced the soulstone path on MetaStation to our /soulstone/anybody/chaplain so that one can also only be used once.

This also changes the soul stone so only cultists are prevented from taking eachothers souls, instead of cultists being immune from all to prevent metagaming. Also changes the message players get when they attempt to do that.

I believe this is something /tg/ implemented a while back, so credit to them.

🆑 Markolie
rscadd: The chaplain on the Cyberiad map now has a one-use soulstone.
tweak: The chaplain's soul stone on MetaStation can now only be used once.
/🆑

### CODE REVIEW

**Comment by SheepFighter** [comment]
The chaplain is quite overpowered as it is. This merely compounds the problems with the role.

**Comment by Dinarzad** [comment]
A soulstone is used to capture a dead/dying person's spirit.
If you're a non-antag you can't exactly powergame with it, you can't go around murdering people just to stuff into the stone without a ding-dong bannu, more to use it as an alternative to reviving someone or capture an already dead Antag, and ask them to divulge information, something you can -already do- with Cyborging.

If you're an Antag, you can already murder people a dozen ways or enslave them ,this gives the Chaplain the ability to make a Shade, which are fairly shitty and is one use, hardly skewing the balance of power, as the stone can only be used -once-.
I am pretty unsure how you could powergame or push the Chaplain to OP territory with a single-use stone that you can use to make a Shade at best, unless there's something special about Soulstones I'm unaware of.

**Comment by SheepFighter** [comment]
The ability to commune with a dead player is potentially round-shifting, depending on what said player is allowed to say. Yes, it's a crapshoot, but it's one with significant possible consequences.

More to the point, it's yet another functional addition to what is already a jam-packed, power-gamey role. The chaplain is supposed to be the equivalent of a parish priest, not Buffy the Vampire Slayer.

I should also add that cloning, SR, and borging require at least a brain. This allows you to pluck a spirit from the ether whenever you feel it would be advantageous.

**Comment by taukausanake** [comment]
A shade is in all intents a ghost and can communicate with them and the living? Isn't that a problem with the shade then and not the use of a soul stone? And I thought soul stones could ONLY take the souls of those about to die, basically in crit. If it was a problem of pulling out ghosts from thin air then wouldn't golems be all the same?

This is at the very least in my eyes a last ditch attempt at saving someone's life if they cannot get to medical or their body would be destroyed or close enough to destruction. It can only be used once and I don't think you can get more? I know there are constructs but by that point I'm sure the chaplain would be breaking SoP and be turning into cult by that point

**Comment by SheepFighter** [comment]
@taukausanake A quick bit of research reveals that I am in error. So yeah, I suppose I'm not quite as opposed to this, then. It still strikes me as pointless, but not as game-wrecking.

As such I retract my complaint.

**Comment by SamHPurp** [comment]
Really don't think the Chaplain needs any more stuff... is my only real complaint to this.

**Comment by Necaladun** [comment]
Apart from increasing the power of the chaplain - something which I think we should be doing the opposite of - there's also going to be the problem of non-chaplains getting their hands on it.

The way things are going, it feels like the Chaplain should become an actual security job.

I might be ok with this if it was an option instead of the null rod, but the amount of magic the Chaplain is getting is, IMO, getting a little silly. It's going from a more RP focused role with no real responsibility to a valid hunting job. 

Additionally - does this make possession of soul stones and using them on people legal? Because that would be very interesting for cultists.

**Comment by Markolie** [comment]
I didn't really intend for this to be a powergamey tool. I noticed the stone on Meta and figured it'd be fun for chaplains to have a spooky harmless shade follow them. It'd certainly make the chaplain 2spoopy. 

If we're concerned about people using random stones we can limit stones to wiz/cult and this stone to the chaplain.

**Comment by Necaladun** [comment]
If not chap only, I see it getting stolen often so that'd be good.

I'd say it should be removed from meta for more consistency with the cyb than the other way round but I hate fun.

**Comment by jughu** [comment]
Arent shades faster and cant shades pull

**Comment by Markolie** [comment]
I do believe they can pull, and they deal about five damage per hit. I'm not sure about their speed though.

**Comment by jughu** [comment]
Dont forget chaplain can use it to capture the shades of cultists and make it their slave

**Pull request merged**
