### PR TITLE
Remaps Escape and Chapel

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Greetings, it's your local sewer-dwelling mapper here, coming in hot with another "did we really need this yo" remap!

This time, it's Escape & Chapel, let's get to it.

## OVERALL CHANGES:

**BEFORE:**

img

**AFTER:**
after

### ESCAPE:
img

The main attraction. As you can see, it's been made larger and with more chairs, no longer will 40+ people in the same room be forced to sit on 8 chairs and no longer will the space be as cramped as your luggage for a 4 month trip.

Garden has been moved to be more central and "look better", Escape Sec has gotten an entire dedicated corner that is more secure and private.

### CHAPEL:

img

Overall changes have been aimed to make it prettier and include a dedicated, fancier funeral area.
The incinerator was moved up North to give the Chaplain a more "personal" maint area and allow the office to have four access points, the maintenance Engineering power station thing has been moved up a few tiles and the hidden locker rooms were also moved around as a consequence. In essence, I just aimed to make the Chapel look fancier and more symmetrical.

Since the Chapel changes are almost entirely aesthetic / fluff, I'm completely prepared to just throw it all out if need be, it was not at all necessary and is close to the "change for the sake of change" territory.

Overall, the changes were aimed to make Escape larger and fit more people while making it prettier and improving the Security corner.

As for the pipes / cables, I'll be begrudgingly awaiting its #8469 merging / closing before I proceed with improving their logistics further (as otherwise either one of us would be dealing with even larger conflicts)

🆑 FreeStylaLT
tweak:Remapped Escape
tweak:Remapped Chapel
/🆑

### CODE REVIEW

**Comment by davidchan13** [comment]
Beautiful. Would adding a wall mounted flasher to the escape brig be a step to far? Have found from time to time that Sec has very few methods for dealing with multiple people causing trouble in their holding area.

**Comment by Spacemanspark** [comment]
This looks great.
:+1:

**Comment by alexkar598** [comment]
Escape brig door is way too close to upper airlock,escape is also too open,I feel that this will make boarding the escape shuttle even more painfull. Also this is just me but i feel that there is the same amount of doors in the chapel only than most departements.

**Comment by KasparoVy** [comment]
Actually look fantastic, I love that the pod bay is accessible even with a shuttle docked now. Big big improvements here

**Comment by Citinited** [comment]
While I quite like this aesthetically, I think that the 5 by 5 garden block and the two 1 by 3 windows to the south of escape will make the area feel much more cramped and impede movement (even though the area is bigger). Maybe single pane windows could make it more spacious?

**Comment by KasparoVy** [comment]
3 tile-wide feela more than adequate when considering there is now 31 available public seats instead of 8. Looks roomier and seems to be more suited for traffic flow

**Comment by Citinited** [comment]
Maybe you're right, I suppose 3 wide is fine elsewhere in the station. 🤔

**Comment by bigfatbananacyclops** [comment]
looks nice, though that sec escape airlock should have one more airlock like the others.

**Comment by taukausanake** [comment]
@bigfatbananacyclops Well what if Engineering gets their own little holding area? I think that might be a little important if they are trying to get something secure off the station and security is too busy upholding the law

**Comment by taukausanake** [comment]
@davidchan13 I can get behind that. Switch engineering and medical shuttle areas and give them a holding space, but I kind of like the setup as it is right now. Nice seating areas. Maybe you can use that empty space under the airlocks

**Comment by KasparoVy** [comment]
:thonkong: Dear God why

**Comment by tigercat2000** [comment]
@MapDiffBot

**Comment by FreeStylaLT** [comment]
Minor tweaks, added a palm-tree area. stairs.

**Comment by ID404-NotFound** [comment]
but does chapel confession intercom work?

**Comment by TravellingMerchant** [comment]
Having played with this area a bit. It's really really good! A HUGE improvement!

The only suggestion I have is adding a couple more tables in the middle, an intercom in the sec waiting room and a mirrored light in the grass area, (for aesthetic's sake.)

A handy image here, tables in red, light in yellow and intercom in green.

https://i.imgur.com/MWWMXLo.png

**Comment by davidchan13** [comment]
Some tables or a counter area so Chef/Bartender can set up temp shop in escape while people await shuttle would be a nice touch, but not necessary.

**Comment by Plotron** [comment]
Chapel has a built-in cross now? I'm triggered.

**Pull request merged**
