### PR TITLE
D&D Minifigures! 

### PR DESCRIPTION
**Pull request by tigercat2000**
Spoffy/LLA-Station-13#147

As requested by ZomgPonies: DnD minifigures! Currently obtainable by (to-be-made)

woot minifig pic

### CODE REVIEW

**Comment by tigercat2000** [comment]
I am waiting on #751 to be merged before adding it to the cargo computer, to prevent any possible merge conflicts.

**Comment by fj45** [comment]
Might also want to port TG's dice.

**Comment by Glloyd** [comment]
So cute, I may take these for Urist.

**Comment by Fox-McCloud** [comment]
Now with real D&D action!

"ROCKS FALL, EVERYONE DIES!"

**Comment by jack-fractal** [comment]
These are adorable. I endorse this wholeheartedly.

**Pull request merged**
