### PR TITLE
Removes Labor Camp / Gulag

### PR DESCRIPTION
**Pull request by FreeStylaLT**
We all know this was coming since the day it was shoved into a corner. It has heavy practicality issues to be useful or even used for anything that isn't a perma sentence, due to the amount of time it takes to get someone there and look after them. 

On top of that, it is not even secure, allowing prisoners to get to a frickin' pod and escape their sentence with the tools given to them in the camp.

Although the security could be theoretically fixed, the practicality of the camp is more or less unsolveable if a shuttle and a separate z-level is still to be used. Since that would require far larger remaps for a dubious benefit, it seems like the better option is to simply remove it entirely.

Cyberiad:

Before:
img
After:
img

Meta:

Before:
img

After:
img

Actual camp:

Before:
img

After:
img

🆑FreeStylaLT
del:Removed Labor Camp
/🆑

### CODE REVIEW

**Comment by Cactus2388** [comment]
This removes quiet a bit of mobility for security, no more being able to escape when nar'sie is summoned, no more going to the asteroid to raid cults (without bothering the likely now-culted QM). The asteroid will now be SUPER isolated like an antag outpost. If sec had a more reliable way to get to the asteroid I'd see no problem with this PR.

**Comment by Citinited** [comment]
Couple of notes:
- That mouse is going to die horribly every roundstart. Poor little guy ;_;
- That air alarm should be removed so it doesn't trigger every round due to lack of air.
- Free recharger! :D

**Comment by SamHPurp** [comment]
(might as well remove the red cross)

**Comment by Spartan6** [comment]
Bloody red crosses and their Geneva.

**Comment by taukausanake** [comment]
Awww, poor labor camp. I kind of don't want to see it gone but I am happy that it was removed **properly** with a nuke unlike the Science Outpost. @FreeStylaLT please share your mapping skills on nuking something like that, I really want to know

**Comment by FreeStylaLT** [comment]
@taukausanake 
img

**Comment by Jountax** [comment]
Isn't the small area where the prisoners are supposed to mine pressurized? I don't doubt that some people have managed to escape the gulag, but it seems to me that trying is like breaking out of perma by going through space. which means at least some level of preparation went into it, or they just gulag'd the wrong sort of antag,  and a security team that was on the ball could counter that.

**Comment by taukausanake** [comment]
If anything the asteroid is the sole property of mining now. Just think of how often Cargonia secedes from the station, now we might as well have the Mines of Asteroia. And let's not forget how often miners end up as cult, or is that not as common anymore?

**Comment by KasparoVy** [comment]
RIP the only other way to the asteroid.

**Comment by shazbot194** [comment]
Well there is still another way... hope you are good with directions.

**Comment by Vivalas** [comment]
Labor camp is technically breathable but that changes as more and more is mined out. The volume of the area increases so the air pressure decreases until it is no longer habitable. Although an air injection system exists it is not accessible to prisoners, which was why it almost always became uninhabitable. That and one bad apple could just break a wall to space.

**Comment by Necaladun** [comment]
Long overdue, the labor camp has just never worked the way we wanted it too, so I'm all for removing it.

**Comment by FreeStylaLT** [comment]
Replaces the empty space with a maint area around courtroom and the firing range:
img
OPs pics updated.

Slight updates to the labour camp, removing floating lights, etc.

New maint are shares the same area as the dorm maint.

**Comment by Dumbdumn5** [comment]
Considering the importance of multiple ways to the asteroid aside from space floating and the teleporter, it may be better to leave this as-is and not remove it. (Though holy shit, I love that maint). Not talked to anyone yet though, so just personal opinion 'ere.

**Comment by davidchan13** [comment]
@Dumbdumn5 Can't escape pods still be manually fired at the asteroid? Moving the engineering outpost to the asteroid would also alleviate such a concern while also benefiting the server balance as a whole.

**Comment by Spacemanspark** [comment]
Escape pods being manually fired is a /tg/ feature.

**Comment by Jountax** [comment]
If moving engineering outpost to the asteroid is deemed as enough of a way for security to get access to the asteroid, then why not just bring back science outpost? If science is a cult, cargo can let sec on the asteroid, if cargo is, science can. And it gives scientists a place to experiment with dangerous things again.

Would love to see xenobiology include studying the creatures that mining guns down rather than just messing with slimes, and on some stations xenobiology is on an outpost because of the danger slimes pose to the station if they escape.

This is out of scope for this PR though so I'll just go back to dreaming instead.

**Comment by Dumbdumn5** [comment]
@davidchan13 as @Spacemanspark said, there's no manual firing for escape pods on Para.

@Jountax thinking about a monster zoo a la Jurassic park with the old fossil collection and creature printing from old DNA that xenobio used to have?

Overall, I'd think that a re-addition of the sci outpost might be a bit much, only because security specifically needs a good way to monitor things themselves without necessarily relying on two potentially vulnerable or more compromised departments. The laborcamp serves more of this purpose in terms of at least being on the same Z-level for now, but a shift to an actual outpost instead of full on removal might help the whole 'meant to monitor the station and its faculties to ensure the upholding of spacelaw' thing.

**Comment by deep-fried-faceplant** [comment]
I want the 1-tile wide maintenance tunnel meme to die.

With those tunnels being a part of security, they're going to have balance implications. Every additional pathway added must be considered, as entry/exit points, as shortcuts, as backdoors, as places to hide, breach points, ect. I know that the point of this PR is to remove the laborcamp, which is understandable, but please don't breeze over minor details like these. speaking of minor details, I know that it's been a long-standing desire to revamp maintenance to make it more "focused". These new maintenance tunnels are right next to security, why not make them security themed? Throw in some dusty donuts, burnt out flashes, broken zip-ties, spare shooting range targets, ect.

Overall, the new tunnels should be outright removed, made to mimic the shuttle's structure to minimize the amount of change to the station's design, or properly designed with balance implications in mind.

**Comment by Quantum-M** [comment]
@FreeStylaLT
This is probably out of the scope of this pr, but would it be possible to expand the courtroom into the space left (on boxstation) and make it look nicer?

**Comment by Citinited** [comment]
If you're going to add that maintenance area, it should probably have a new area defined - it being part of dormitory maintenance would be confusing to people who don't know this and have to fix stuff in it for whatever reason.

Also I'm agreeing with @deep-fried-faceplant here - this really opens up the brig to all kinds of security issues the way it's made in this PR.

**Comment by granodd** [comment]
The removal of the science post on the asteroid and its shuttle made sense, seeing as scientists can actually roll antag and turn it into their supervillain base of operations that had to be raided by security at least once every shift, _on top of it being practically useless_.

The labor shuttle, while not used for its original purpose, does serve as another means of getting to the asteroid as mentioned before. Removing the sec shuttle would make rooting out asteroid cults or antags tedious, given the one shuttle, and an arguably bigger space to work with as compared to the engineering outpost, which is the next closest thing. Turning it into some kind of security outpost would be neat though.

**Comment by taukausanake** [comment]
Maybe as a side project it wouldn't hurt to have the white ship be able to fly to the asteroid too. I don't think it does currently.

I think I like the security outpost idea. That might work for something. Or maybe turn it into perma. At least if you have a friendly miner you might be able to escape

**Pull request closed without merging**
