### PR TITLE
Tweaks Event Odds

### PR DESCRIPTION
**Pull request by Kyep**
This PR tweaks the probabilities of many events, attempting to make the game more fun.
Essentially, fun events now have a higher chance, and pointless/overplayed events now have a lower chance.

Major Events:
- Increases chance of meteor wave events. (Engineers usually have nothing to do)
- Halves the chances of Xenomorph events. (They are too common)

Medium Events:
- Reduces chances of rogue drones (That does almost nothing currently)
- Increases chances of radiation storms (So, give people more reasons to duck into maint temporarily)
- Increases chances of most kinds of anomaly (So, more flux/bluespace/pyro/etc random fun times)
- Increases chances of meteor shower (So, engineering might sometimes have a real job to do)
- Decreases chances of meaty ores (They do almost nothing, unless they get a very lucky hit, and they're a bit of a joke event)

🆑 Kyep
tweak: Changed event probabilities, aiming for a more fun late game. In general, events that do very little (e.g: meaty ores, rogue drones) are less likely. Events that will keep people on their toes (e.g: anomalies) are more likely. Events that might cause people to observe rather than joining the round (e.g: Xenos) are less likely. 
/🆑

### CODE REVIEW

**Comment by Necaladun** [comment]
Carp Migration has been brutal lately - meteors good for engis, carp BAD for engis.

Xenos wayyyy too common for sure.

Rad storms are great and should be more common, good for antags to gank people in mate, or just a few mins of roleplay talking to your co-workers. Also a good idiot check.

Some of the anomalies are really brutal...not sure on that. Although pyro ones are great to give atmos something to do!

**Comment by tylerh95** [comment]
+1 on everything besides carp migration 

I haven't seen many, but they do seem particularly brutal, essentially agreeing with what @Necaladun said about that.

**Comment by taukausanake** [comment]
I rarely see xenos ever on the station. How common are they?

**Comment by Kyep** [comment]
Xenos are quite common.
If memory serves, they're one of, if not the, most likely major event, other than 'nothing'.
The reason for this is that their chance scales up based on certain crew factors, and with our high population...

**Comment by SamHPurp** [comment]
thumbs up on all accounts! Happy to have shit to do as an engineer again!

**Comment by sothangel** [comment]
How does increasing the odds for an anomaly impact the commonness of Phazons? Will we be seeing them much more with this PR?

**Comment by Ssirius** [comment]
Anomalies are rarely any kind of a real problem or threat considering how often science or anyone disarms them for the core(unless its the vortex, or a unattended bluespace anomaly). 
Also as Soth mentioned, more anomalies = more phazons, and that's not really a good thing for anyone involved, unless by some mad luck a traitor with mech fab access got one, its going to up the number of validhunting all access all powerful mechs going around running all the fun.

**Comment by uraniummeltdown** [comment]
I'd lower the weight of traders, the other major events apart from carp migration are way more fun than traders, in fact I'd be for moving it to moderate events since it's not really "oh shit" like the other major events

**Comment by KingPhilipIII** [comment]
I would support the xeno restriction if not for the fact most hives amount to nothing but a few dead monkeys in virology. Usually the crew stomps them.

**Comment by davidchan13** [comment]
Meaty ores are bad for pods. Least four times in the last month I've late joined Sec pod only to find it breached with cows outside.

I do feel vox traiders would be a good modeling and rarely see abductors despite the role being fun to play and deal with.

Meteors I'm iffy on as the pierce can be ridiculous and the core of the station will usually take as much of a beating as the outer walls that should take the brunt of it

**Comment by Fox-McCloud** [comment]
Traders are way too common--they do little to advance the round, offer little in terms of roleplay, and aren't very well fleshed out---I'd make them less common.

The points raised about anomalies very much applies here, as well. 

Rad storm? Probably too much of a tick up.

**Comment by Kyep** [comment]
Be aware:
- When I say "traders", I mean "Sol Traders", ie: human traders. I do NOT mean "vox raiders". Traders (the sol kind) are in the game, but have to be manually activated. While they're only a minor event, personally I love them, as they draw several ghosts into a round, create a mini-event that revolves around talking/bartering, and involve anyone who wants to be involved. For all these reasons, I think they deserve to actually be in rotation, rather than just be an adminbus event. It is literally not possible to reduce their chances in this PR, because right now, their chance is Zero. They can't happen without adminbus.
- With regards to anomalies, the vast majority of anomalies aren't successfully deactivated. Also, if memory serves, nobody builds phazons because their key feature, phasing, is currently completely broken. Right now they're effectively trophy mechs. Shiny, but useless.
- Still, I'll review the chances for anomalies and rad storms. Personally I like rad storm because it gets people out of their workspaces, at least briefly, and gives maint-lurking antags a chance to discover them, or be discovered by them. I'll update this if I change anomalies/radstorms.

**Comment by KingPhilipIII** [comment]
It's only the destructive anomalies that get disabled. Usually gravitational and bluespace anomalies are ignored while the ones that explode or eat crap get handled quickly.

My opinion about xenos still stands firm too.

**Comment by Necaladun** [comment]
Move trader stuff to a new PR, they need a few tweaks as it is before default.

Any chance of making xenos/borers/swarmers less likely to cause the other ones to spawn?

**Comment by Kyep** [comment]
@Necaladun Removed the Traders change.
To answer your second question: no.

**Comment by Lady-Luck** [comment]
I know it's a bit late, but I've been playing a lot of SS13 lately and have realized I've barely seen any abductors.

**Pull request merged**
