### PR TITLE
Fix vents in mechanic workshop

### PR DESCRIPTION
**Pull request by Luthix**
Turns on the vents in the mechanic's workshop and the one directly outside it.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Mapmerged?

**Comment by Luthix** [comment]
Sorry I'm very new to all this I didn't know how else to do it.

**Comment by monster860** [comment]
I am seriously considering making my own git client.....

**Comment by KasparoVy** [comment]
See https://github.com/ParadiseSS13/Paradise/tree/master/tools/mapmerge

**Comment by Luthix** [comment]
Thank you

**Comment by monster860** [comment]
I'd recommend fastdmm but then Fox McCloud would fox-block the PR

**Pull request closed without merging**
