### PR TITLE
Removes the tajaran meow emote

### PR DESCRIPTION
**Pull request by Coolrune206**
## What Does This PR Do

Removes the Tajaran "*meow" emote from the game. Sound file included.
Partially reverts https://github.com/ParadiseSS13/Paradise/pull/21296.

## Why It's Good For The Game

A. The emote is a rather jarring sound, quite out of place on the server. 
B. Tajaran communicate with "yowls and chirps", as per their language. It's the lesser form of Tajaran, Farwa, that meow when they speak.
C. It's not really used properly on the server (because it doesn't particularly have a place), it just kinda gets spammed.
D. The sound quality is not particularly good and I am not going to go find a new one, considering the above points.

## Testing

image

## Changelog
:cl:
del: Removed Tajaran *meow emote
sounddel: Removed Tajaran Meow sound file
/:cl:

### CODE REVIEW

**Comment by Sadhorizon** [comment]
Here is a funny screenshot
obraz

Good change, I've already had enough of Taj players meowing.

**Comment by matttheficus** [comment]
Can we do this to slimes to? /s

**Review by JimKil3 — APPROVED** [review]
LGTM code-wise - as an alternate idea if this doesn't go through, maybe try replacing the tajaran meow with the same noise Runtime uses?

**Comment by K3Licia** [comment]
> LGTM code-wise - as an alternate idea if this doesn't go through, maybe try replacing the tajaran meow with the same noise Runtime uses?

as the person who made the tajaran emote PR, i'd much prefer that compared to removing the emote entirely. i believe that'd solve points A and D without erasing a well-enjoyed emote (by taj players) while making it less bothersome. i'd be willing to make a PR for it myself, even.

**Comment by Sirryan2002** [comment]
In support of this, I was on the fence about it in the original PR. The Hiss should definitely stay however.

**Review by Sirryan2002 — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
