### PR TITLE
Vox Rework

### PR DESCRIPTION
**Pull request by Fox-McCloud**
You knew it was coming; reworks Vox. 

After discussing this on and off for a very long time, it's finally been decided: Vox are going to lose their spaceproofness.

This is WIP, as I'm still not sure what they should get (if anything? Who knows) in place of the spaceproofnes; I'm open to idea and would like to hear some of them.

Vox keeping their spaceproofness, however, is not negotiable; it's going to go; as stated on the Discord: ***there will be no round-start space proof races***.

Removed their EMP weakness because it's really not necessary for them to retain that anymore, and, the more I saw this utilized to down a Vox, the more and more I disliked it.

:cl: Fox McCloud
tweak: Vox reworked
del: Vox are no longer spaceproof
tweak: EMP's no longer wreck cortical stacks
/:cl:

### CODE REVIEW

**Comment by dovydas12345** [comment]
> Removed their EMP immunity
I think you mean EMP vulnerability since you are adding EMP immunity to them since it no longer damages their stack?

**Comment by Fox-McCloud** [comment]
Yeah, that's correct.

**Comment by Ionward** [comment]
if suit sprites are needed for vox, ping me, i remember seeing most varieties in there but if they need anything extra i'm available 👌

**Comment by rb303** [comment]
They will very much need some buffs, given that spaceproofness was their only upside (I believe?), vs their downsides like no cloning and extra brute damage taken.
I'm not quite sure myself what they could be buffed with without making them too human-like, ideas like their stack providing minor benefits or a tiny bit extra speed (this could be looked down upon by a lot of people) come to mind, though.

**Comment by TheSardele** [comment]
I think they're going to need something to compensate, as their only positives would be starting on internals lasting them the entire shift (which can be turned against them), and of course KINSIES.

Just going to throw out some ideas:

**Space resistance:** Have them take less damage from space/low pressure, rather than being space immune.

**Have the stack slowly heal brain damage:** Brain damage is quite important with newcrit, so slowly regenerating it could come in handy. Of course, it shouldn't impede dying to crit, so it needs to be slow.

**Immunity to being deafened:** They spend their lives surrounded by other shrieking Vox, their ears can't be normal.

**Comment by Aurorablade** [comment]
Fox could we keep the reactions i put in somehow? I mean i agree with what you did on the EMP end..i just want to see the stack have SOME use or some kinda a flavor on if something goes wrong *i half like the brain damage heal idea*

**Comment by Necaladun** [comment]
@Ionward thanks! There's actually a whole heap of vox suits atm that people barely get to see, but more is better ofc. Will keep in mind.

I'd like to keep the brute weakness to encourage a cowardly playstyle from vox. Ideas for buffs in return:

Reduced toxin damage (Something about a highly efficient toxin processing from all the crap they eat)

Pressure resistance but not immune? 

Deafened immunity, sure why not?

These kinda feel like minor cookies in exchange for some pretty strong nerfs, something more solid will be needed unless it's a whole bunch of minor things.

**Comment by Fox-McCloud** [comment]
>Space resistance: Have them take less damage from space/low pressure, rather than being space immune.

I don't mean to sound like a jerk, but....I just said "space-proofness being gone is non-negotiable", what would make you think this would  be something as an acceptable suggestion?

Thank you for the other suggestions though.

**Comment by Necaladun** [comment]
@Fox-McCloud reduced damage from space, but not immunity? Or perhaps resistance to high pressure?

**Comment by TheSardele** [comment]
Yeah, the idea was that breaches are still dangerous and they still really don't want to be exposed to space, but they could last a little longer if they were.

**Comment by Necaladun** [comment]
Stack buff ideas:

Having the stack cause buffs is a cool idea - being a bit more than just a minor detail would be great.

Brain damage regen/resistance - Maybe quite powerful not sure

Hallucination resistance - too situational to be really useful?

:thinking: too early for me to think of more so outsourcing this to everyone else

**Comment by rb303** [comment]
Since stacks are basically just a fluff vox thing, I think it might be a nice idea to give some bonuses to them. What comes to mind (including previous mentions) with stacks could be:
-reduced hallucination time?
-slow self-healing brain damage?
-no clouded vision from damage?
-moderate pain resistance?

(Tired and can't think of many other ideas for stacks, but I'd like to hear of more)
As a whole, I could see toxin damage resistance making sense, and makes me think of them possibly being more resistant to disease, dunno if that's possible but it might be a good idea.

**Comment by Kyep** [comment]
Ideas:

- Vox can be cloned, but the cortical stack must be removed from the previous body and implanted into the new body for the new body to wake up and the player to inhabit it. Vox clones without a cortical stack remain in a vegetative state. This would make it harder to revive vox, but still possible if medical knows how to do it. To prevent it taking vastly longer to revive a vox than other races, vox races could be cloned at a much faster rate, as their biology is optimized for cloning and unlike with normal cloning, you don't have to replicate the fine details (e.g: the brain) exactly as they were before, because the identity is given by the stack, not the brain. Or just have the stack be a subtype of brain and let them be cloned normally.

- The cortical stack has built-in functions that can aid the vox in some situations. For example, it can act as a filter, reducing the vox's ability to feel pain, tiredness, hunger, hallucination, and other minor negative status effects, for a brief time. Once per shift. It does this by releasing a small amount of stored chemicals that reduce these effects into the bloodstream, like a chem implant. Alternatively, it could be used as a bluespace communications device, transmitting a message that other vox (and only other vox) within a wide range can hear. This ability would be limited in usefulness / have a cooldown, but it would promote vox sticking together and clan tactics.

- Vox tails have an intricate capillary network used for temperature control. As such their body temperature restores to normal faster than most races. This is useful as it can minimize heat/cold burns on them.

- Vox have the ability to shriek once per long period at glass-shattering volume, capable of breaking windows and being heard from a long distance away. This does no damage to humans (due to high pitch) but does shatter any windows or other glass objects in tiles directly adjacent to the vox.

All of these ideas come from the lore.

**Comment by taukausanake** [comment]
>- Vox clone

omg hell yes please

>- Need their stack transplanted

Hell yes too as this makes them less human AND it makes sense lore-wise (but since when has that ever mattered)

>- stack built-in functions

Little ehhh on this. Depends if anything else is getting changed first

>- tail temperature control

This sounds neat. I'm for this

>- glass-shattering shriek

More ehhhhhh on this but less if it break all glass things (like beakers and glasses) and ONLY IF the shriek is them screaming "SKREEEEEEEEEE"

**Comment by BakKeener** [comment]
I had countless times of where a vox gets brought in too late to be defibbed only to either be gibbed by SR by a new or incompetent doctor or to have them get SR'd only to get RNG'D hard with dead torso or groin _yes I have seen it before and I have no idea how to deal with it_ or their body is almost beyond recovery taking 15 if lucky or 30 minutes to a full hour just to treat which is very stressful and annoying to deal with but also makes SR less relevant as the only people who now need it is slimes if they do become cloneable since the plasmaman rework is also fixing the cloner issue.

I do not believe Vox should have the shriek ability as it will be very powergamey and extremely dangerous to those around them as if they did this on the bridge  windows in order to escape sec, fastmos will most certainly kill someone who is a passerby, sec or even themselves and cause a bunch of unneeded stress for medbay and the players who are caught up in this with a ability that only revenants and vampires have.

As for the tail reducing burn/cold damage I do not believe that is how it should or would work. Instead it should give them a higher Temperature threshold against heat and cold which would fine since it wouldn't be a major buff as it would simply give them resistance to not the damage type but instead to heat and cold itself.

**Comment by KasparoVy** [comment]
Fuck. I was really REALLY holding out hope that the buck would stop with the other races.

This race is the vast majority of my experience on the server nowadays and not mincing words it SUCKS to see this happen.

@Kyep 's ideas make sense and will make it more palatable but goddamn I wished this day would never come so, so much.

**Comment by Imotepchief** [comment]
All I can really say is that this, the standardization of races, along with various other opposed changes, is just making me sad.

**Comment by Fox-McCloud** [comment]
@Ionward 

The regular space suits (the superrrr old kind that you can only get in crates from cargo), the Syndicate Suits, and the NASA voids suits are the ones that I do not believe there are sprites for yet.

Only reason those don't "fit" Vox is because it'd look atrocious if you put them on.

**Comment by taukausanake** [comment]
>Robotic internal organs
> it'll make fixing them a huge pain

It'll also make them not a viable cloner race. Those cybernetic organs will just be replaced with fleshy ones if at all. I don't think cyber organs would be good either way as Vox bodies are kind of meant to be cheap while getting the job done. I think I would like them to be cloneable but require that their stack be transplanted like what Kyep said

**Comment by Sikroth** [comment]
> * Claws do toxin damage instead of brute

Embracing the vox are pox meme, I like it.

Honest answer though, while I'm sad to see spaceproofness gone, I like some of these ideas. I'd personally play more with that idea that was also thrown around of giving the cortical stack some sort of active utility, but I like most of the ideas here in some way or another.

**Comment by Drakeven** [comment]
I'd like to put in my two cents of what suggestions we've seen so far, to be honest, they all seem pretty small differences rather than the alien-ness of having such vulnerability to EMPs, and not bothering about space. A big problem I'm seeing is that these changes are basically making the varied races of the game close to human. I think that 'Extreme differences, bigger disadvantages, bigger advantages' is better than just dulling their edge. It's all about playstyle and lore.

>Cloneable Vox
I like the idea of the cortical stack being more important, and needing to be transferred, and being able to clone them would certainly make a few trips to medbay a lot easier when there's no other vox around, but it really doesn't fit the flavour. 

>Built in Cortical functions
I think this is a good idea, however having it only usable once per shift would result in a lot of 'too good to use' syndrome, it would also make them a race which is given more of a disadvantage the longer a shift is. I think certainly some more passive buffs that are constant throughout the shift would be nice, or having the ability on a long cooldown. As far as making them be able to communicate secretly to other Vox, well, Vox do that pretty much anyway with Vox-pidgin. I think if the stack was going to do anything, it might, as Fox said, very slowly regain toxin damage or the like. 

>Vox Tail temperature control 
This is neat and very much fits with the feel of Vox. Though temprature isn't exactly that much of a problem unless it's- Space, or a plasmafire. So this seems quite small of an advantage. To be honest, I also agree that possibly some space 'resistance' would... well, still keep the essence of Vox, but Fox has already made it clear how this isn't an acceptable suggestion. 

>Vox with the ability to shriek 
I don't like this idea in the least, it would make Vox really tiresome to deal with, and they're small little creatures anyway, so being able to produce such a loud sound would be strange. It also doesn't help the station at all, just hinders it, and I'm not sure NT would be that encouraged to hire small little birds that can break equipment so easily. Making this change would create quite a bit of disdain for Vox in my opinion. 

>Attacks doing toxin instead of brute
Not a fan of this one either,  it would be really inconvenient if you tried to help someone up with help intent but accidentally gave them some damage that is just a real pain to get better. Sure, it might fit with the lore of them being small so not much brute damage, but the main problem is: IPCs would be immune to any Vox bullying. 

> Limbs/organs cannot go necrotic
I like this, it's an interesting idea for a change and would make Vox the second creature to be able to be revived indefinitely (Like IPCs) 

> EMP Proof
I think one of the major features of flavour for the Vox is their vulnerability to EMPs, even though it's been my death more often than not, I think it adds a lot to their foreignness, and it's always a good time trying to explain in risky situations 'MED!!' 'SOMEONE!!' 'GUNS!!' To change this would be to change a lot of what is core to Vox, and if changed would need to be done so carefully. 

As far as suggestions of my own, I may have a few that I have briefly been thinking on. However, my main objective was to say something about the suggested changes, as I would feel bad if I didn't voice my opinions. To be honest, I quite dislike this change and think there are other ways of making space more threatening. I don't think anyone should be shot down for suggestion space-resistance inappropriate after space-immunity being so in-graned into Vox. I think the next few changes to them will have to be done with the utmost care, as Vox are some of the more roleplay intensive races of the station and many players deeply care about the lore. Heck, they do the accent all by themselves. 

SUGGESTIONS- 

-Making the Cortical Stack more than flavour. Possibly having it act like a very, very simple MMI, allowing the 'personality' of the Vox to speak in very confused bursts (Much like the effect of being EMPed currently 'THINK!!' 'LIKE!!' 'THIS!!')
-Making them slightly faster. I think this would be a huge benefit, on the level of being space-proof, and allow one to keep the heavy disadvantages of Vox. 
-Giving Vox a connection to the other Vox on the station, not extreme like greys, but a small message that possibly might pop up after a Vox dies on your same Z-level, just saying something like 'You feel a presence of Kin fade'. This could be related to the Stack and would tie into the closeness of Arkships. Vox are known to care for other Vox. 

Obviously, these are all quite significant, and only one would really be implemented, but I prefer trying to find another advantage as large as space-proofness while keeping the major disadvantage of EMP vulnerability and cloning troubles, because I don't really want to see those disadvantages go either. 

Anyhow, there's my two cents. I'll take some time trying to think of more, possibly better suggestions than this. I wish you luck with this balancing act!

**Comment by Denthamos** [comment]
For all the people salting about their space immune races loosing such, this has been a long time coming.

Since I became an admin it became startling clear just how often such races were used with antags and caused massive amounts of chaos, simply because they had such an easily available escape route to them limited to very few races or jobs.

The area of space outside the station Z levels wise is huge and space immune races as antags have been abusing that aspect for a very long time since really there was only a single job which could hunt them down semi-reliably.  This has led to a frustrating meta when combined with fastmos that you either joined in on or had to deal with because there was no way to handle it otherwise.

You could say "Oh security should just carry around space suits then" however that is not and easy or good solution at all when an entire department has to carry around space suits which does not fit in their backpacks and slows them down, all for these races in specific.  

The game as a whole should not be balancing itself around these races, but instead the races need to be balanced around the game and in the current state they are not.

**Comment by iantine** [comment]
Personally I'd like to see the EMP weakness remain. While it would no longer act primarily as a viable reliable takedown on a race that would otherwise get away far too easily, it creates an potentially present workplace hazard that vox have to fear in the same manner IPC do, which creates interesting RP opportunities. In combat, I suppose it could work as a counter for their speed, if something of an overkill.
As for balancing the nerf of losing spaceproofness, I think the idea of a minor buff or two, rather than something major, sounds interesting in the interest of making vox slightly underpowered species which rely on their speed and evasiveness to get around a situation.

**Comment by Kyep** [comment]
I too would prefer all currently spaceproof races, including vox, to stop being spaceproof.

I look forward to seeing what we come up with in terms of a suitable alternative thing for vox to keep them unique, but in a different way.

**Comment by Necaladun** [comment]
@Fox-McCloud toxin for claws seems a bit of a debuff in some ways. How about keep the brute, but also add 1-2 tox per hit?

**Comment by TDSSS** [comment]
I like the idea of vox being clonable but needing a stack transfer, it sounds neat. 

As for other buffs, maybe allow them to start with some kind of special, cybernetic organ that provides buffs, similar to the stack? I don't really see the stack providing chems personally, but some other implant that they can start with that helps you out would be very neat. Ideally one that NT can't replicate.

**Comment by JKnutson101** [comment]
A suggestion for a minor cookie for Vox, would be giving them the ability granted by TG's Skittish Quirk. Here it is...

> "You can conceal yourself in danger. Ctrl-shift-click a closed locker to jump into it, as long as you have access."
> Ctrl-shift-clicking on a locker will, if you can open it, cause you to jump in and lock the door behind you.

I think this would fit the Vox's nature quite well, and would be a nice little addition to some of these other suggestions. This also adds to the wonderful Vox in a Box joke quite nicely.

**Comment by Drakeven** [comment]
Aw how neat, that might be nice, though I can't see many situations where it'd be useful, but it IS very good flavour, cowardly Vox that love to hide in dark places and lockers.

**Comment by Carthusia** [comment]
Some of this I agree with, though some I don't.

I still feel the EMP should affect vox, as it is quite fun having to keep that kind of thing in mind and makes perfect sense lore wise, vox primalis are basically the IPC's of their race, mass produced, not exactly the strongest, short little workers who work in most every field.

While I will miss the space proofing, I do get where its coming from, from a balance perspective and will miss it dearly, many a life was saved by being able to just jump out into space to pull someone back in.

The idea of a Vox being cloneable is nice, so long as the stack is implanted in the new body. I've always viewed the stack as basically the vox itself, while the brain acts as basically a CPU, you can kill the brain, but the stack if still intact, the vox is still very much "alive" so long as it can be implanted into a new body, as by the lore during times of population decreases they pick and choose which dead vox to bring back from stored stacks. 
I noted a point on how NT doesn't quite know how to clone vox and how they are cybernetic, I think this only applies to the Armalis and anything higher than the Primalis, they are the ones who are basically 90% cybernetic 6-8ft tall vox soldiers, with self terminating sub systems that burn out anything of use in them should they die to prevent anyone from analyzing the body.
Side note: Talking vox stacks like IPC brains, would be friggin hilarious to play as, I explode, and all you hear is "AGHHH!!!!NOO!!!!VOXXIE!!!!CHUNKY!!!!SOUPS!!!!"

I dislike the idea of vox loosing their brute damage and gaining toxins damage for melee instead as noted above: IPCs are immune to it which prevents them from harming them at all, and accidental toxin damage is much more annoying to get rid of than accidental brute or burns. Ontop of just the lore lacking any real mention of vox being poisonous, maybe Armalis, though id doubt Primalis

I do like the idea of a slight speed increase, they are supposed to be fast little 3-4ft birdlike people,which always made me wish vox had the option to start with the dwarfism gene, so if people wanted to RP the size difference properly, they really could as anytime that gene comes up, I snag it just for the proper vox appearance.

**Deafened immunity**: While I find it funny that vox live around screeching so much, that they become immune to ear damage over time, I also feel this wouldnt make to much sense, a vox screech is one thing, a flashbang going off next to you is another.

**Vox tails have an intricate capillary network used for temperature control. As such their body temperature restores to normal faster than most races. This is useful as it can minimize heat/cold burns on them.**
I do like this, as while they would no longer be space immune, they do control temperature better than most.

**Vox being unable to go necrotic**
I'm 50/50 on them being 100% unable to go necrotic, perhaps just it takes longer than usual? 2x? Could be due in part to their semi-manufactured nature.

**Comment by Imotepchief** [comment]
The idea of vox losing EMP vulnerability is something I'm against, as has been mentioned, it is a fun thing more than a real detriment and adds character to the race.

I also like the idea of vox not going necrotic, but I believe that the immunity should only apply to their organs and not their limbs - not that necrosis is hard to fix anyway.

Increasing vox base speed isn't something I think would be particularly balanced, but what I would like to see a hide mechanic, such as the ability to jump into lockers, or even hide under tables, after all, vox are supposed to be tiny.

**Comment by Carthusia** [comment]
Imotepchief-

What would your opinion on vox getting the option to start with the dwarf gene to make them tiny, if a player wished to go the true vox apperance route from the get go?

Sept maybe remove its ability to crawl under desks for balance reason unless they get the super small gene to add said a bility back.

Just throwen it out there as i always found it confusing when I read that vox are 3-4ft tall, but they look 5-6ft tall

**Comment by taukausanake** [comment]
> dwarf gene to make them tiny
> true vox apperance

We already have tiny spess raptor birbs in SS13 and those will forever be known as RESOMI. But besides my undying love for those things I don't like the thought of smaller Vox. They've always been a human-sized mob and changing that right now would be weird

**Comment by Carthusia** [comment]
Its not so much a forced change idea, but an option for players who wish to be the smaller version.

Like a box you can tick: Do you wish to be fun sized Y/N, that you can turn off at anypoint before a round starts kind of thing.

**Comment by BakKeener** [comment]
Well if vox were shrunk down to dwarf gene proportions, that would be a huge buff as we would have less to click on making it harder to fight them in melee combat and even more annoying if they were given a slight speed buff which is being suggested in the comments here. I don't believe any race and especially vox with their already smaller then standard sprite to be shrunk down any further.

**Comment by Carthusia** [comment]
Fair point and well made Iksnay on the dwarfyness then.

**Comment by Fox-McCloud** [comment]
Yeah, they're not getting the dwarfism gene by default.

**Comment by Carthusia** [comment]
Fox-McCloud

How possible/likley though are some of the changes suggested here?

Obviously space immunity is out, and I can live with that.

But what about other such things:

Cortical stack implant/clone: Makes being a vox less suicidal, where even all critical effects more or less equal perma death if not treated immediately.

Reintroduction of the EMP damage:  Its a negative effect to playing a vox, but its one i do wholly enjoy and makes them feel more unique to play. It also perfectly fits in with the Primalis as they are not like the Armalis, are more or less in a sense, mass produced and besides the Stack/Brain connection, by default have no cybernetics to speak of. 

Reduction in Necrotic Speed or immunity to necrotic

Claws remaining with brute damage instead of toxins.


Drakeravens idea of: Cortical Stack Basic MMI
-Making the Cortical Stack more than flavour. Possibly having it act like a very, very simple MMI, allowing the 'personality' of the Vox to speak in very confused bursts (Much like the effect of being EMPed currently 'THINK!!' 'LIKE!!' 'THIS!!') If you are able to have both the brain and the stack together, combining them like this would lead to some basic communication. This would also encorage doctors to take the Stack WITH the brain, instead of just leaving the Stack which is arguably more important than the brain in lore.

and Kyps idea of:

Vox tails have an intricate capillary network used for temperature control. As such their body temperature restores to normal faster than most races. This is useful as it can minimize heat/cold burns on them.

**Comment by Drakeven** [comment]
Yeah giving Vox dwarfism isn't a good idea, not just for balance, but it would drastically reduce the quality of the sprites, which is something I wouldn't like to see. It's find every round or so, but not being able to ever get a clear look at Voxxy would be sad.

**Comment by SomeSortaSquid** [comment]
I'll appear as a contrarian and say that I don't like the idea of clonable vox. I'm fine with rewriting the entire dionae lore just to remove their spaceprooness, because I find it hardly interesting. Vox lore is, however, too good to just overwrite it for the sake of a really desperate buff meant to compensate for the nerf.
The challenge reviving a vox right now presents illustrates quite well how alien they are. You have these familiar people whom you all treat the same, asking yourself how come all life in the galaxy shares the same design. Then a dead vox arrives and you have to throw everything out. Time to use SR, make use of organ revival mechanics and generally struggle. This is part of what makes vox truly alien. It goes well with the lore of non-vox having barely any understanding of the race. Honestly, you will botch vox revivals at first, until you familiarize yourself with their alien natures.

Regarding potential compensations for losing spaceproofness, I'll mention an idea of another user that is, in my opinion, worth consideration: Giving vox a roundstart department-related implant. There would be some obvious choices, like medical getting medHUD implants, security secHUD implants, etc. There would be some that require a bit of thinking or perhaps adding something new, life chef or bartender.
The reasoning behind this idea comes from vox fondness of cybernetic augmentations. It would remain lore-friendly while giving vox only a tiny advantage early into the round, before other races can catch up with implants from RnD.

It's too late for me to come up with creative ideas for a compensation right now. I just wanted to protest against clonable vox and share someone else's idea that I think might have potential.

**Comment by Carthusia** [comment]
mmmm, i see that point of view now squid and never really thought about it like that, and you've kind of swaid me, though i think when the aboves say cloneing a vox, they don't mean like schlop them into the cloner and that's that like with other races, it just makes a new body like SMing a monkey, they still need to conduct a surgery to transplant their stack to make them "alive" again. 

This would almost be a prefered route to go, as i've heard talkings about the potential removal of SM due to abuse, though i'm unsure how true this is.

Though by god would it be helpful if there was a poster, that was a 100% spawn rate in the medbay near the cloner door, that just read "If a vox comes in, READ YOUR MANUAL!"

So many times, and no doubt anyone who plays a vox has had this at least a dozen times in the last month.

You get brought in, doc tosses you into the cloner, doesnt work, tosses you in the morgue, while the little box shows green saying you can be revived, and you scream at the screen.

If they made it so it clones the body, and maybe a little message that informs them that surgery still needs to be done to complete the process, that kind of would go a long way in preventing needless malpractice deaths.

**Comment by MrMagolor** [comment]
>Vox tails have an intricate capillary network used for temperature control. As such their body temperature restores to normal faster than most races. This is useful as it can minimize heat/cold burns on them.

Yeah. that sounds reasonable- like a slightly more versatile (but less overall advantageous) version of drask/kidan temperature properties.

**Comment by Carthusia** [comment]
I dono about archaic, vox tech is kind of beyond NT in many respects, id chock the EMP vulnerability of the primalis down to their somewhat mass produced nature as they are the worker caste.

**Comment by TDSSS** [comment]
Even swarmers who were created by some super high-tech precursor whatever aliens are still emp vulnerable. I don't think tech has to be archaic or shitty to be vulnerable to it.

**Comment by Ralta** [comment]
Good. Even as a Vox player I felt being space-proof was terrible. +1.

**Comment by Wolfsyndrome** [comment]
While I do understand the need to remove spess-res, I am saddened to see it go, simply because it made the Vox so very unique, and I do feel they'll need SOME good buffs to make up for it. Here's an idea that I had;

Quicker movement in Zero-G - Because Vox are a spess-living species I don't think it's too out there to say that the Vox have learned how to move more quickly in zero-g environments. Claws for feet can be very grippy on floors, or they could simply be able to launch themselves 'further' from points of contact due to their smaller stature compared to other, bulkier races (i.e. walls, doors, etc.).

**Comment by SynthNumerics** [comment]
There have been some good replacement ideas suggested here, specially things like the stack MMI, cloning but needing to put the stack in the new body, temperature resistance etc. The former two place more importance on the stack which is the one thing that makes them really unique, so giving focus to that keeps their alien feel.

 I'm too exhausted to go completely im depth on things, but I want to at least mention EMP.

Vox raiders would use EMPs when they would go out on hunts, it seems ill advised that they would do so if it had the potential to kill their own party. The immunity makes sense, though I wouldn't mind the confused speech- perhaps until the stack "repairs" its own "damage"? This could be a space of 10 mins easy, but not rely on getting nanopaste to be able to function once more. In effect the stack gets momentarily shorted slightly and stops sending every signal, instead of breaking. Primalis are mass produced, their stacks aren't perfect- but they wouldn't send them out just to die by their own tools. They're still too useful for that.

**Comment by Fox-McCloud** [comment]
Something went side-ways. Re-opening.

**Pull request closed without merging**
