### PR TITLE
Adds a Science beret, obtainable via the loadout system.

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
rscadd: Adds a Science departmental beret that you can obtain via the loadout system.
/:cl:

Done at Duckchan's request. Colour-matched to the uniform.
Sorry it took so long, I kept forgetting.

_The mock-up._
scienceberet

_The description and the loadout entry._
scienceberetloadout

_The in-game preview. Obtained via the loadout system._
scienceberetingame

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
I am not sure if every department needs a beret..

**Comment by KasparoVy** [comment]
Me neither, but it's not my call to make. This was a rather persistent request. It's harmless enough.

**Comment by Faryaa** [comment]
You forgot robotics. Why dont they get the beret too?

**Comment by jughu** [comment]
Robotics get tacticool jumpsuits and gloves

**Comment by KasparoVy** [comment]
Going to resolve the conflicts in a sec', doing the same for another PR first

**Pull request merged**
