### PR TITLE
Welding a tile away now gives a new message

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Welding a tile now gives a more clear message to the user

**Changelog:**
:cl:
tweak: Welding a tile away now gives a more useful message when doing so.
/:cl:

### CODE REVIEW

**Comment by JohnBigless** [comment]
Gone would be the days of accidentally breaking plating with welders during blob rounds.
And gone would be the possibility of stealthily removing floor tiles under someone and watching them get annihilated by Fastmos.
+1

**Comment by Lunaimon** [comment]
Don't you already need to use a screwdriver before the welder to remove plating? #12002

**Comment by Citinited** [comment]
Agreed with Lunaimon -- this seems unnecessary given #12002 is in

**Comment by farie82** [comment]
It still confused me after I tried to deconstruct something. Since it was a notice and not a warning that i was about to space myself

**Comment by variableundefined** [comment]
I think the screwdriver should be enough. Just change the span class of the tile removal?

**Comment by farie82** [comment]
Would be nice to get a direction in how we do dangerous deconstructions. As some use the harm which means you're about to do something harmful or potentially dangerous.

I myself think this is a good thing to have. You can also prime floorings now and have people accidently hit them

**Comment by Fox-McCloud** [comment]
yeah, just add a warning/danger class

**Comment by variableundefined** [comment]
Changelog no longer accurate. I think it's better to just stick with to_chat for now.

@farie82

**Comment by farie82** [comment]
Updated to just be a changed to_chat

**Pull request merged**
