### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Replaces the floors below grilles in the new virology with plating, for consistency.
2) Adds rights checks/proper logging for diagnostics admin verbs.
3) AI's can no longer go into transit tubes.
4) Fixes bent pipes not saving their state when unwrenching. Fixes https://github.com/ParadiseSS13/Paradise/issues/2192.
5) Atmospherics tanks and huge scrubbers can now be scanned by atmos analyzers/PDA's.
6) Removes the PDA JFLOG, as it's never been used (as expected).
7) Prevent dead/unconscious people from emoting. Fixes https://github.com/ParadiseSS13/Paradise/issues/2189.
8) The EXPERIMENTOR and mechanics consoles are now linked to a server.
9) Ghosts can once again access the R&D console.
10) LOOSE PIPE.
11) Fixes outlet injectors on the map being unpowered.
12) Removes spammy logging from AI law procs.
13) New robots will no longer have to wait for several seconds until they can see/can move. To fix this, robot components now start powered instead of unpowered, and will instead depower on the first life tick if they're without charge.
14) Makes sure icons update when players spawn in.
15) Prevents shadowlings from hatching on non-turfs (i.e. lockers). Fixes https://github.com/ParadiseSS13/Paradise/issues/2195.
16) Plasmamen nuke ops suits are now identical to their normal counterparts.
16) Admins without +MOD will now also receive questions.
17) Flavor text (and records) now properly save in SQL (although semicolons will still be stripped for security purposes). Fixes https://github.com/ParadiseSS13/Paradise/issues/2200.
18) Gunlights and plasmamen lights are now disabled by Veil. Fixes https://github.com/ParadiseSS13/Paradise/issues/2199.
19) Fully removes passive vents from pipe dispensers, as they're not even in the codebase. Fixes https://github.com/ParadiseSS13/Paradise/issues/2198.
20) Adds a box of vials to virology. Fixes https://github.com/ParadiseSS13/Paradise/issues/2201.
21) Changes a few in world's for admin verbs to in view().
22) Fixes mining drones not dropping ores. Fixes https://github.com/ParadiseSS13/Paradise/issues/2202.
23) Fixes some runtimes.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
damnit, Travis.

**Comment by tigercat2000** [comment]
>3) AI's can no longer go into transit tubes.

Why?

**Comment by Robertha89** [comment]
Cause if you push them in, how do you get them out? They can activate a bumpact. Also cause CE did this with me as an ai earlier today, and it was horrible.

**Comment by Alex6511** [comment]
Yeah... it causes problems.

**Comment by Spacemanspark** [comment]
It also kills the AI IIRC, because it's not connected to the power supply.

**Comment by tigercat2000** [comment]
Oh.

**Pull request merged**
