### PR TITLE
Adds two extra safety cables to the engine room

### PR DESCRIPTION
**Pull request by datlo**
The engine as it is setup right now is wayyy too easy to release. All it takes is insulated gloves, a crowbar, a multitool, and wirecutters. You don't even have to get into the engine room itself.

This PR adds two extra cables that links the tesla energy production directly into the emitters, making the tesla harder to release : You now have 4 cables to cut instead of 2, 2 of which are only in the engine room.

Does not affect the singularity engine.

extracable1

extracable2

🆑
add: Added two cables linking tesla energy production to the emitters, making the tesla engine harder to release.
/ 🆑

### CODE REVIEW

**Comment by Taaketa** [comment]
The Tesla is already on the grid for the emitters. The wire goes into the PA.

To be honest the wiring here can be done by any half competent Engineer and I think that is the way it should be.

**Comment by datlo** [comment]
Yes. But the wiring goes outside of the engine room, making it easy to cut for anyone breaking in. hence, the pr. The wires being redundant is the entire point.

And yes, it can and should be done. It never actually is unless i'm setting up the engine and i'm not feeling lazy that round. It'd be better to have it consistently there.

**Comment by DesolateG** [comment]
Server rules deal with anyone releasing the engine without the proper context. Theven double redundancy wires are... redundant and hugboxing. 

If you want to secure it more do it in shift, not something that is already round start.

**Comment by datlo** [comment]
Fair enough. Don't think that server rules should be justification for something lacking in security IC, but sure.

**Pull request closed without merging**
