### PR TITLE
*fart

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in a sound to the fart emote.

This was added in for a few days about 5 months ago--an admin didn't like it, at all then, and it was quickly removed. The community's opinion was far less clear; a good portion was upset at its removal, some didn't care, and others were glad to see it go.

In any event, since then, farting from hugs has been removed, and the only thing that can make you fart, other than emoting yourself, is eating eggs--and there's now a way to silence people from doing the emote with a medical reagent called Simethicone.

Still consider this highly controversial; would like admin and community input/opinions on this one.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Thumbs up, wayyyyyyyyy up yo butt.

Fix it so that superfart genetic makes a really loud fart sound.

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

Will probably do so when superfart is moved over to a spell rather than being tied to the emote.

**Comment by tigercat2000** [comment]
:-1: Oh god please no, I fully agree with Mel, it's horrible

**Comment by FreeStylaLT** [comment]
I don't see any reason why not have it if *squish exists

**Comment by adrkiller59** [comment]
Just one quick question:

W H Y ?

**Comment by melandor0** [comment]
Because the squish sound doesn't make all those people around me look at me as if I'm a 10 year old laughing at fart sounds on my computer just because I wanted to play spacemen.

**Comment by fj45** [comment]
No, I feel that even on Goon its terrible.

**Comment by adrkiller59** [comment]
When did this seem like a good idea?

Keep it for goon.

like... really.

**Comment by Fox-McCloud** [comment]
Squish sound is pretty obnoxious and gross sounding in and of itself.

**Comment by Spacemanspark** [comment]
Ehhhhhhhhhhhhhhh...
:-1:

**Comment by Fox-McCloud** [comment]
Have an idea for this that will remove the controversy tag---will add later today.

**Comment by Finalsong** [comment]
WELCOME TO GOONSTATION PART TWO.

NO. NO THANK YOU.
PLEASE TAKE YOUR FARTS SOMEWHERE ELSE, LIKE BACK TO GOONSTATION.

**Comment by Bram961** [comment]
No.

**Comment by SamCroswell** [comment]
Personally, I think it's a bad idea for our server.

**Comment by TheDZD** [comment]
At the very least make these have a cooldown.

**Comment by melandor0** [comment]
Where did my original comment go?

**Comment by ZomgPonies** [comment]
Don't you dare touch my *squish.

**Comment by Regen1** [comment]
No thanks, I think we are waaaay better off without farting

**Comment by ZomgPonies** [comment]
I guess that's a hard no then.

**Pull request closed without merging**
