### PR TITLE
Prevents new players from attacking or looting SSDs

### PR DESCRIPTION
**Pull request by Kyep**
Changes:
- Very new players (those with under 5 hours of playtime) who try to attack, or loot from, an SSD player, are prevented from doing so. Instead, they get a message telling them to read the server rules.
- Anyone who has 5 hours or more of playtime, is an antag that round, or is a member of security, can still attack/loot SSD players. This prevents someone attacking an antag then going SSD to prevent them retaliating, prevents members of command being unable to get a SSD Captain's nuke disk, etc.
- Again: **If you have 5 hours or more of playtime on Paradise, this system won't affect you.**
- This entire system is a config option - and it is disabled by default. 
- Admins also get a new player panel option, "Toggle SSD Guard", which lets them disable the guard for an individual person. So, if a new player does really have a legit reason for stripping a SSD player, they can ahelp it, and get permission.

Why do we need this?

Because people messing with SSDs happens _every round_. And it is almost always new players doing it. And it adds up to a big time-sink for admins, dealing with these cases. Not to mention the hassle of cases where it isn't caught, and someone comes back to the game to find their ID/etc has been stolen. New players will learn not to mess with SSDs far faster if they're prevented from doing so early on, than if they're (maybe/hopefully?) bwoinked for doing so after the fact. 
We shouldn't be forcing admins to handle these cases manually, when this code can handle 90% of the cases for us, freeing up admin time *and* resulting in a better experience for new players.

🆑 Kyep
rscadd: SSDs are now protected against new players messing with them. This protection only works against new players. Anyone who has played on the server for 10 hours or more, or is an antag, is expected to know the rules, and is still able to interact with SSDs.
/🆑

### CODE REVIEW

**Comment by Anasari** [comment]
Seems good.

**Comment by scrubmcnoob** [comment]
Yee Haw

**Comment by Twinmold93** [comment]
Would be appreciated greatly.

**Comment by Lady-Luck** [comment]
To pre-empt a complaint I know maintainers will have... this should probably be a config option, as not all servers that use Paracode have SSD rules like ours.

**Comment by Lady-Luck** [comment]
Oops. Disregard me. Good PR.

**Comment by Kyep** [comment]
@Lady-Luck In the PR as-is, it is already a config option. And it is disabled by default.

**Comment by fludd12** [comment]
If it doesn't already, could you make it still trigger an admin log (maybe make it say that they tried, but could not, x?) This way, we can provide advice to the person if they repeatedly try it.

**Comment by Kyep** [comment]
I thought about that. Then I wondered, what would we tell them? Go read the rules? It already tells them that. If they have a specific question, they can always mentorhelp it.

**Comment by Fox-McCloud** [comment]
This is akin to preventing someone from doing rulebreaking action X because they're not an antag/new.

This is hand holding in the most extreme, and likewise, the codebase is *not the place to enforce the rules*. The codebase is to give tools to govern players, observe players, allow them to deal with rulebreakers, detect rulebreakers, but it's nto the place to enforce rules explicitly.

This is a bad precedent to set.

**Comment by Twinmold93** [comment]
Fox, that's saying that you want someone to handle it explicitly because you would rather a person say 'knock it off, go read the rules, or be banned' rather than pre-emptively stop a situation that we know is an issue and a very common one at that that still tells them to go read the rules. It sounds that you don't want any form of automation for these things, in direct disregard of burn out of admins for having to continuously having to tell individual players to cease and read the rules, on top of us them having to fix said player.

The ONLY two exceptions I can see is a doctor needing to fix up someone who went SSD who legitimately needs to strip them of their backpack/mask and put the new stuff on them/interact with them with the tools and the extremely off-chance someone without at least 10 hours of play time needing to strip a Command member of important gear before cryoing them.

**Comment by Kyep** [comment]
@Fox-McCloud

SS13 is a game with a horrible learning curve, where, if you screw up and die, you can be out of the round for *two hours*. If you screw up and attack an SSD, you can get banned. Only a small fraction of bans are appealed. Most people who screw up once... just never come back. A little hand holding for new players is a *good thing*. It reduces the learning curve. It gives new players a better experience (ie: not being bwoinked). It allows them to learn the rules as they go, like a good tutorial does, rather than forcing them to read through a book before they can play at all. It saves admin time. It results in less issues that admins have to deal with. It is good on every measure. Look at: https://www.youtube.com/watch?v=BCPcn-Q5nKE
"Handholding" isn't bad. Most games have a tutorial. Some of the best games, like Portal, are mostly tutorial! Handholding isn't the enemy of fun, in fact, done well, handholding, especially at the start, is exactly how you build an experience that people can get into comfortably. From the POV of the new player, I'm sure they'd much rather be told "X is probably not OK, please read the rules" than be allowed to do X.... then probably warned or banned for it. 
That doesn't mean we need to apply this approach for everything, but when something happens *every single round*, its easy to solve with automation, and the automation results in a better experience for players and less time-consuming unnecessary issues for admins... there is no good reason not to do it.

There is no divide between rules and code, except in your mind. The rules and the code are merely tools in the same toolbox, being used together towards the same end. To identify a problem and say "ok, even though this could be solved easily with a pair of pliers, I insist we deal with this using only a hammer" makes no sense. It would be like eating every meal with a spoon because you refuse to use a fork, even when it is the best tool for the job. It makes no sense, and, at best, seems really weird.

**Comment by Jovaniph** [comment]
Anyone play club penguin? There is an automated system for cursing and getting ban...

**Comment by Kyep** [comment]
Jovaniph, that is not remotely relevant to this discussion.

This discussion is about: do we want to continue wasting admins' time handling what are typically honest mistakes by new players? Or do we want to automate that so that the new players don't accidentally get themselves in trouble, and admins aren't wasting time dealing with this issue *every round*?

Having automated systems which limit or discourage undesirable behavior is *expected*. We have many of them already. Heck, we just recently merged a PR that prevents people using click macros. Automated systems that detect people doing things they almost certainly shouldn't, and steer them away from doing that, are very helpful, and should be strongly considered.

**Comment by Anasari** [comment]
I agree with what Kyet says, while bwoinking people for SSD touching was fun during the say, first month of me being admin, at this point it's becoming nothing but dredging repetitive work for me, often getting in the way of me enjoying the round myself.

I am not too certain about the idea of adding an exemption for medical doctor, though from my experience most people who strip SSD are civilians, so it won't reduce coverage greatly.

**Comment by theColdflame** [comment]
what happens is a player is in one of the reasonably common situations wherein stripping/attacking an SSD is valid and happens to be sub-10 hours?

**Comment by SamHPurp** [comment]
Attacking or stripping an SSD ISN'T reasonably common... I think I've done it all of 2-3 times ever in my entire time playing Paradise.

**Comment by tigercat2000** [comment]
I strongly disagree with this PR. :-1:
There are far too many common scenarios in which anyone needs to be able to strip or otherwise interact with an SSD player. You are making a huge assumption in that anyone with less than 10 hours of playtime will only be breaking the rules doing so. 

I would also like to bring up the following:
1. The fact that the only way that an administrator can allow this behavior is by var-editing the configuration controller is outright bad.
2. This has no exception for administrators. This will be a significant problem for anyone using our codebase that isn't actually playing on our server. It also doesn't obey the config option for applying time based restrictions to administrators.
3. Directly snowflaking this restriction into the main onclick code is absolutely awful. No, there isn't a better place for it, but that doesn't change that it's awful.


@Kyep 

Comparing this pull request to the one removing .click macros is a false equivalency. Using .click macros literally is breaking the game, especially as we discovered that you can *click anyone on the map at any time* with them. Quite literally, a global aimbot. That is something that should be prevented in the code, because it affects everyone that uses it. 

Fox's main point is not "we should ban all those who break our rules"; It's the fact that our more abstract and arbitrary rules should not be enforced by harsh code limitations. This is something I agree with.

**Comment by SamHPurp** [comment]
When is there a legitimate reason for you to fuck with an SSD in your first few games of playing Paradise?

There isn't.

**Comment by SamHPurp** [comment]
Alternative suggestion:

Option in Preferences: "I understand the server rules around SSD, allow me to touch SSDs"

If they haven't ticked it, they can't interact with SSDs.

And if they break the rules while having that enabled, its swifter for the admins to be able to ban them.

**Comment by Kyep** [comment]
Situations where you really need to attack/strip a SSD player are rare. When they do happen, they usually happen to Command staff (who require 10+ hours playtime already, and are thus always bypass this system), or Security staff (who require 5-10 hours playtime). I play head roles all the time, and I almost never have to strip or attack an SSD player.  I really don't see this as an issue. It barely ever comes up, and even if it did come up, valid attacks/strips on SSD players are almost exclusively something that happens to heads of staff, and members of security.

I will, however, include something that makes admins bypass the check in a future PR. I'm also considering including something that makes members of security bypass the system.

I would argue that people attacking SSDs is more impactful than people using .click macros is. How many people use .click macros to shoot people across the map, etc? Barely anyone. Yet, we considered that an emergency. How many people attack SSDs when they shouldn't? It happens *every round*. The fact that one is an aimbot and the other isn't, doesn't matter. Admins spend VASTLY more time/effort dealing with SSDs, and I'd wager SSD-related issues are by far and away more significant in most rounds. The fact that they're different kinds of issue is irrelevant. As far as "should we have code prevent this" goes, they're the same. Code should prevent both.

I don't consider this code limitation particularly harsh. I don't see any situation where a <10h player is going to need to attack/strip a SSD. If people can point out valid examples, I will certainly address them.

I did consider making this a preference. I ultimately decided it wasn't worth it. That would require a SQL change, possibly everyone to update their preferences, etc. I decided that was not worth it. Almost all regular players have 10+ hours playtime, and won't be affected by this PR at all, as written. It only affects new players, and stops them doing something which is almost certainly rule-breaking, at least until they have a few hours under their belt and are in a better position to know if they're allowed to do this thing.

**Comment by Citinited** [comment]
Reducing admin overhead is generally a good thing.

Besides it's a toggle; if the admins don't like they can just turn it off.

**Comment by theColdflame** [comment]
other side of a fight disconnects

playing security and a criminal disconnects

latejoin as and someone disconnected with unique job items 

I could probably think of some more

**Comment by SamHPurp** [comment]
@theColdflame Its a 10 hour timer before you can do these things.

Do you really think people will be playing roles (similarly behind a timer wall) that require them to have the unique job items?

Also most of these job items are retrievable from the Cryo console.

Security has a timer too remember.

**Comment by Kyep** [comment]
Updates:
- There are now exemptions for unarmed clicks on help intent (to shake SSDs) and grab intent (to put them in cryo).
- There is also an exemption for security. Sec is never affected by this system now.
- There is also an exemption for admins now. It follows the existing config directive with regards to admin immunity from playtime requirements.
- Lastly, there is now a 'Toggle SSD Guard' option in the Player Panel for admins. Clicking this enables a player to loot/attack SSDs regardless of playtime restrictions for the rest of the round. The default message has been changed to "AdminHelp (F1) to get permission before stripping players who are suffering from Space Sleep Disorder / disconnected from the game. Read the server rules for more details.". This ensures that players who want to do this, and have a legit reason, can quickly get permission.

@theColdflame 
If the other side of a fight disconnects, you'll still be able to finish them off most of the time. This system will only stop you if you're a new player, who isn't an antag, or a member of command/security. Even then, you can still quickly ahelp it and get permission.

If you're playing security and a criminal disconnects, the system won't affect you. There is now an exemption that covers all of security.

If you latejoin as a new player, find the other person in your job SSD with the necessary items, and try to loot them, it will tell you to ahelp for permission. You ahelp it, get permission, then loot them as normal.

**Comment by Necaladun** [comment]
10h sounds a bit long, tbh. 
6 hours would be their first 3 full rounds.

This is honestly a huge amount of admin work that this would cut out. I'm all for automating something like telling new players not to fuck with SSDs.

A default off config option means I can turn it on when there's 140 players on and i'm the only admin.

Otoh, people attacking and clicking on other people is a lot and I'm not sure of the costs involved there.

**Comment by theColdflame** [comment]
in the context of a fight, ahelping, getting the ahelps read by an admin, and the admin responding and lifting the restriction is an incredibly long time

this system also assumes admins will, without fail, respond to every single ahelp in a timely manner. this isn't the place to discuss admins but that's a very idealistic assumption

**Comment by Kyep** [comment]
@Necaladun Reduced to 5h.

@theColdflame If they stay SSD the whole time, then it doesn't matter if it takes a minute or two for an admin to respond, because they're SSD, and no threat to you, during that time. You can walk away at any time. Or, if you're security, you can simply arrest them. On the other hand, if they go SSD during a fight, then come back, you can resume fighting them without waiting for an ahelp response. And this all assumes you're a new player. 90%+ of players won't even notice this system as they have far exceeded the amount of playtime required to be totally immune. All this does is stop completely new players from beating on SSDs, or stealing their stuff, without asking us first.

**Comment by moonheart08** [comment]
Why not make the timer configurable @Kyep as another config option

**Comment by Kyep** [comment]
@moonheart08 No reason to over-complicate it. A simple on/off is enough.

**Comment by MrFroztee** [comment]
Fox and Coldflame make good points, honestly, there are some processes that shouldn't be automated.

**Comment by FalseIncarnate** [comment]
Controversial tag when?

I'm gonna have to agree with the dissenters on this one: this should not be automated.

Already you have made it so it's painfully obvious there are cases where exceptions are to be made. Security, medical, command, antags, admins, grab code... what is next? Stripping an ID to move an SSD out of a room to safety from emergency situations? Slapping a patch or autoinjector onto a dying SSD from a public access first aid kit? Exceptions for people who TRANSFER into security or medical?

The intent is good; the execution is horrifyingly terrible. If an admin can't be bothered to do their job on even this basic level, don't do it for them; get rid of the slacker.

:-1:

**Comment by shazbot194** [comment]
What if we had a compromise where if you try to attack an SSD person while under the time limit, it will pop a warning that you might be breaking the rules with a yes or no answer, and if you acknowledge you might be breaking the rules, it will let you do whatever you were trying to do and save this for the rest of the round, and if you do not, you will get the same popup window next time you try to attack/strip an SSD, and after the time is up, it doesn't give the pop-up anymore. . This way admins don't have to be directly involved, but the admins still get a warning that someone might be breaking the rules, and it allows people who didn't read the rules still know that they might be breaking the rules but doesn't limit them.

**Comment by Kyep** [comment]
@shazbot194 
This PR:
- Provides an option, which is disabled by default.
- When enabled, only affects a small number of players (those with under 5 hours time played on Paradise).
- Never affects Command or Security.
- Never affects empty-handed use of grab or help intent.
- Is easily turned off for a specific player if they just ahelp and get permission, as they are told to do.

The rules are very clear on this point:
https://nanotrasen.se/forum/topic/9646-server-rules/
"If you believe an SSD person needs to be interacted with (such as an SSD Captain needing to have their equipment removed), ask the Administrators first."

People are *already* supposed to ahelp and get permission before messing with someone who is SSD.
This PR doesn't even go as far as to enforce our SSD rules as written.
All it does is push the people who have the least legitimate reason to mess with SSDs (new players not in command or sec positions, who are deliberately trying to harm or strip SSDs) to ahelp for permission.
Cases like the above SSD Captain aren't covered, because under this system, Command/Security are immune and can still interact with SSDs. This system only seeks to address the clearest cut cases where someone is messing with an SSD, and they obviously shouldn't be doing it.
That's it. That is all this PR seeks to do. It helps admins (not having to deal with all these cases manually). It helps new players (better to be told "hey, don't do X", then do it and get bwoinked / possibly banned). It reduces the chances of SSDs being messed with in general, which is good for the server (realistically, admins cannot catch every case).

This PR already uses compromise to address specific objections raised. It is already fairly minimal, structured to have no impact at all on anyone who'se been around for 2-3 shifts or more (ie: everyone commenting here). At the same time, it is still addressing a long-running problem in a way that seeks to educate new players, rather than simply bwoink them.

The main reason for resistance to this PR seems to be nothing more than anti-automation dogma. If you drop the dogma, and evaluate the idea on its merits, you will see it is better for admins, better for new players, and better for the server as a whole. It doesn't even fully automate - there is still an easy-to-use manual override for admins. This PR just flips the logic so that instead of every case having to be done manually, easy cases are handled automatically, and admins need only step in if an exception is required. This is more efficient for everyone.

Let the system handle the easy cases.
Admins can still handle the complex ones.

**Comment by MrFroztee** [comment]
The best way for new players to learn is to get a slap on the wrist, and as such they won't learn it's bad to mess with SSDs unless they're caught in the act. Might be easier on the admins, but I don't see this being better for new players, other than putting baby bumpers on the corners of the server. 

If getting bwoinked/banned for breaking the rules turns a new player away from the server, they probably don't belong here anyways.

**Comment by shazbot194** [comment]
@MrFroztee I fully agree on your first point, we shouldn't limit players, but we should inform them what they are doing wrong. By just limiting them we open the system to abuse. I like the idea behind this PR, but I don't think an outright stopping of new players from all interaction to SSD personnel minus cryo-ing  is a good idea.
@Kyep Like I said, I do like the idea behind this PR, but I think locking away interactions from new players without admin help is a bad idea. How many new players use mentor help? I am betting its way less then how many need to/should use it, and using admin help is probably even less. In addition, what if an admin forgets to flip the switch back off, while yes, they have a better understanding of the rules, it does negate the time limit which could now be replaced with some questions.

**Comment by Kyep** [comment]
@MrFroztee I think they're more likely to learn from an automatic notice telling them to read the rules, than they are from *maybe* getting bwoinked for doing it. Certain interventions work better than chance-based ones. 

@shazbot194 This PR specifically pushes them to ahelp if they have a valid reason to do it. If your objection is 'new players don't mentorhelp/ahelp', then this PR is good, because it pushes them to do so. Also, admins don't have to 'flip the switch back off'. A player who gets 5h or more playtime becomes immune automatically. Additionally, toggling the switch for them in a round only lasts for that round, at most. There is no need for admins to manually turn it off again later. IMHO, them having a better understanding of the rules is a good thing.

**Comment by Necaladun** [comment]
Yeah, the "maybe" being bwoinked is a bit big too. To be honest, I think we'd miss maybe...50% of them  on high pop rounds?

**Comment by Dumbdumn5** [comment]
I myself do have to agree with those stating that the process shouldn't be automated. It's not about the PR locking away interaction or doing things that are more often than not, the wrong thing to do, but it's mostly about frequency of this occurring. These situations arise commonly in that they appear maybe once or twice every other round or with more space than that between them, and are often fixed with a simple "place the item back onto the person, please" or a "quit touching the guy" which is generally simple. I can understand the system being meant for solomins on 120+ pop, but as I've personally been one before, as have many if not all of the current administrators, the SSD problem is somewhat rare on its own. Much of the time, ahelps about SSDs are security members, doctors, etc. trying to fix something or a situation in the game, and the issues involving new players under five hours are either baldies who've begun beating on other people for seemingly no reason, or somebody simply doing something illogical. 

The reasons False has provided are common scenarios that I, as a medical doctor and even a civvie trying to get somebody to medical, have experienced on more occasions than I can count, and while I may be an experienced player, new players or players returning from prior to the January patch involving the time code may find themselves unable to perform the regular functions they used to. 

On top of this, it would feel somewhat lazy on my end if I had to use this to prevent the highly visible cases of SSD touching, as they are highlighted by the neon red {SSD!) tag currently in place. As I'm writing this hastily, I likely haven't taken into account some facts about this PR, and will edit my views accordingly when I return and have the ability to reread the arguments presented in this PR previously. I will say that this PR does take much of the workload off of administrators for these cases, but I'm not certain that this is the way that I would see it as being beneficial. A prompt may be the better option as suggested above.

**Comment by Anticept** [comment]
@Kyep Possible idea if this remains highly controversial. If a person goes to open the inventory of an SSD, they get a popup warning about the rules, that the action is admin logged, and touching SSDs without permission can result in a ban.

**Comment by Kyep** [comment]
IMHO: just merge it as is. Say goodbye to maybe 50-80% of problems resulting from new players messing with SSDs. Problems. Solved. Solved. We can always tweak it later if we want. But that's no excuse for not having a solution now.

**Comment by TullyBurnalot** [comment]
Not a lot we can say to excuse how long this took, so I'll just cut to the chase:

This is not something we want to see automated in this manner. We apologize it took so long, but I'm afraid it's getting closed; we would prefer handling this manually.

**Pull request closed without merging**
