### PR TITLE
Chief Engineer Hardsuit Fix

### PR DESCRIPTION
**Pull request by KasparoVy**
Figured I'd tackle point 5 of #1862.
This PR adds object and worn sprites for the light-on states of the Tajaran, Skrell and Unathi CE suits-- porting the CE rig sprite from Bay. A couple sprites got renamed for this to work.

-snip-, changed at the request of @Fox-McCloud. Now it's a proper CE hardsuit instead of a recycled sprite

UPDATE: Edited all Vox rig-white icons and changed the colour scheme to be as close to the other Chief Engineer hardsuits as possible without completely going out-of-phase with the other Vox Hardsuits.

newchiefengineers

Because the majority of Vox hardsuits don't have light-on states (i.e. rig1-[_color] is the exact same sprite as rig0-[_color]). I'll save that for another PR.

--- However, I noticed something off when I was working through this. It appears that, although the sprites are named correctly and in the correct places, the **HELMET** icon in the *top-left* of the screen and on the *bottom-left* in your player doll thing never changes despite the suit being modified (read as: uses the human sprite), while the **SUIT** icon does (even in the top-left corner, seen when using a species-modded DS hardsuit that just got merged in).

This issue is common across ALL hardsuits and species, with the exception being Plasmaman suits (because I think those are handled differently and in another location).

[picture WOULD go here, but my Dream Daemon doesn't work so I can't reproduce the issue on local]

It's a shame that is, because there's all these helmet icons left unused as a result. ---

### CODE REVIEW

**Comment by TheDZD** [comment]
As far as I know, the rig-whiteold sprite isn't meant to be for CE hardsuits, but was from the white Skrell-only hardsuit we used to have in EVA.

**Comment by KasparoVy** [comment]
Figured I may as well use it, saved me from having to make a sprite from scratch
Follows the theme reasonably enough as well.

**Comment by Fox-McCloud** [comment]
Yeah...the Vox and Skrell ones definitely don't match.

**Comment by KasparoVy** [comment]
I'll see what I can do about it. They were there, and I figured it'd be better than stuffing a human suit on someone it won't fit or having to use the standard engineering hardsuit for the working sprite

Might take me a bit now that Dream Daemon's not working

**Comment by KasparoVy** [comment]
The Vox one is the exact same as the engineering and atmospherics suit except it's coloured white and black, most like the rest of the suits. Comparing the Vox hardsuits to the hardsuits of every other species better defines this difference.

I agree with the Skrell one, and I'll change that. The idea I have for it is to reskin the engineer hardsuit to have the white highlights like the rest of them. Sound better?

**Comment by KasparoVy** [comment]
@Fox-McCloud Got started on a Skrell sprite, using the exact same colour scheme as the human helmet (comparing the colour changes from the engineer and CE versions of the suit)

skrellce

Wanted to show you where it's at before I continue. Acceptable or nah?

**Comment by Fox-McCloud** [comment]
You may want to check Bay or VG for the Skrell one--they may have already done one.

If they don't have one, it looks like the work you're doing on the current one is progressing nicely.

**Comment by KasparoVy** [comment]
Sweet, glad you approve. And yeah-- unfortunately they don't have one. I'll keep at it, I guess.

**Comment by KasparoVy** [comment]
Alright, done. I'll see if I can do some photoshop wiznerdry to get the new sprite in the picture.. Curses, Dream Daemon!

**Comment by KasparoVy** [comment]
I kept in mind what you said about the Vox sprite looking pretty crap, so I fiddled about and tried to put it more in-theme with the human CE uniform.

The new sprite called 'VOX CE' in the picture doesn't use any colours not found in either the Human or the Tajaran unless it complimented the existing colour scheme
humanvoxces

The difference is minor because the old vox sprite that I put in as the CE already shares so many colours with the human sprite.

**Comment by KasparoVy** [comment]
I'll try to finish the Vox CE sprite today, although I'll be out most of the afternoon.

**Comment by KasparoVy** [comment]
Almost finished, gotta' finish the helmet and some object icons and I'll post the pictures.

**Comment by Alex6511** [comment]
I think the bigger arm sceen lookers cooler.

**Comment by KasparoVy** [comment]
Dream Daemon just doesn't want to co-operate. I open the program but the window just never pops up. This'll make field-testing the sprite impossible, unfortunately-- but I can still photo-shoop it into the main picture.

**Comment by KasparoVy** [comment]
Alright, that's it. Here's a pic. Still can't track down what's wrong with my Dream Daemon, but this picture should suffice.

newchiefengineers

**Comment by Markolie** [comment]
Looking good.

**Pull request merged**
