### PR TITLE
Vulpakanin can now only be neon green

### PR DESCRIPTION
**Pull request by Aurorablade**
Also bees

### CODE REVIEW

**Comment by KasparoVy** [comment]
nice dude, just what we need

**Comment by Spacemanspark** [comment]
Don't forget hot pink.

**Comment by Fox-McCloud** [comment]
secretly, we're all Trip Fuzzball.

**Comment by KasparoVy** [comment]
:green_apple:

**Comment by tigercat2000** [comment]
>not limiting it to #00FFFF
worst pr ever

**Comment by Spacemanspark** [comment]
I'm quoting that, Fox.

**Pull request merged**
