### PR TITLE
Hydro & drone

### PR DESCRIPTION
**Pull request by CrAzYPiLoT-SS13**
1. Fixed a notice, fixes https://github.com/ParadiseSS13/Paradise/issues/683.
He pretty much solved his own issue. Dunno why this wasn't fixed earlier
2. Added drones ability to grip metal so they don't drift off into space in low gravity places.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:-1:  to the snowflake drone thing; they already have no slipping for this reason.

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, but if in space, they have no mean of coming back without this.

**Comment by M3hillus** [comment]
They do. Rods on space tile ahead of them.

**Comment by Fox-McCloud** [comment]
Remove the drone code and this can be merged at the appropriate time.

**Comment by CrAzYPiLoT-SS13** [comment]
Sure, didn't know they had it already.

**Comment by CrAzYPiLoT-SS13** [comment]
Do not merge this when I remove the drone code, I want to add the requested colorful reagent-splashing-corgis or whatever you wanna call it.

**Comment by CrAzYPiLoT-SS13** [comment]
Opening a new one

**Pull request closed without merging**
