### PR TITLE
Adds Secondary (Facial) Hair Colours to Genome

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
rscadd: Adds secondary (facial) hair colours to the genome (UI). There are 6 new blocks.
fix: Characters with secondary (facial) hair colours won't find they've turned black after cloning anymore.
/:cl:

_Cloning myself with extremely obvious secondary hair & facial hair colours.
I definitely kept them through the cloning._
secondarygenes

_The UI interface showing 6 new blocks._
genemodsecgenesblocks

Some day I'll get around to turning the r_, g_ and b_ mob vars into one per set that'll store hex values like how markings are handled. The problem is ensuring no-one loses their character colours in the process by developing a script or whatever to convert and preserve them.

### CODE REVIEW

**Comment by KasparoVy** [comment]
This'll come with an update to the Genetics wiki page since it adds new UI blocks.

**Comment by Lady-Luck** [comment]
I recall the Genetics wiki having some inaccuracies regarding the UI blocks as well.

**Comment by KasparoVy** [comment]
Then I'll be going through to correct them all when I deal w/ this, won't be a problem afterward hopefully

**Comment by KasparoVy** [comment]
Wiki updated.

**Pull request merged**
