### PR TITLE
Supports +1 Cyborg job slot

### PR DESCRIPTION
**Pull request by Kyep**
- Changed cyborg job slots from 1 to 2.
- Added additional cyborg spawnpoint in robotics mech bay.
- Tags: config edit, map edit

🆑 Kyep
tweak: changed cyborg job slots from 1 to 2. 
/🆑

### CODE REVIEW

**Comment by Markolie** [comment]
I don't agree with another cyborg, as it'll give the all seeing, powergaming AI even more chances to rek antags and destroy fun.

**Comment by Spacemanspark** [comment]
Master of Synthetics approves. I /might/ recommend removing the posibrain from the robotics area if enough people see it as too powerful, but I don't see it being an issue.
:+1:

**Comment by KingPhilipIII** [comment]
At last. More easily emagged cyborgs as the roboticist.

**Comment by davidchan13** [comment]
@Markolie /tg/station is that way. You'll find that attitude is pretty prevalent despite borgs being borderline useless secborg removed from play.

I'm biased but I do feel more borgs is a good thing. Not only do/does traitor/subverted/malf AIs have to deal with 100+ people they generally lack the resources to properly survive and fight the crew should the need arise, having more default borgs would probably help them out. I mean, the alternative would be to increase the number of AI slots.

**Comment by Markolie** [comment]
My issue isn't about traitor AI's though, it's about the powergamey attitude 75% of our AI's have that ruin antag plays. This'll only make it worse.

**Comment by Spacemanspark** [comment]
I find that powergamey AIs tend to not even use their borgs to get things done, surprisingly. Perhaps they're going off the quote "If you want something done, you have to do it yourself.".
I don't think adding a second borg at roundstart (which generally already comes into existence anyways with the posibrain in robotics) is going to effect much.

**Comment by Kyep** [comment]
95% of the time, borgs act independently from the AI. As such, I don't think adding more borgs is a substantial buff to most AIs. Sure, some might benefit from having a second borg, but an AI that is really on top of its borgs is probably going to get additional borgs made, even if there is only one at roundstart. So, I don't expect this to have a big impact on AIs. Antag AIs (by which I mean actual roundstart antag AIs, not merely 'subverted later in the round' AIs) are so rare that even if this buffs them, I consider that a bonus.

The reason I want to increase cyborg slots, is that cyborgs are unique in that they can effectively become a mini-engineer, mini-doctor, mini-miner, mini-secofficer, etc. Not only that, but they can (and usually do) choose to help whichever department is understaffed. This can make them a great balancing force to shore up shorthanded departments, as well as adding a fun additional job slot.

**Comment by Markolie** [comment]
We should probably remove the posibrain from robotics then.

**Comment by Kyep** [comment]
I'm not inclined to remove the posibrain from robotics.
Actually, if I was to change this PR at all, my inclination would be to up the borg slots from 2 to 3. We have the population for it, and unlike most jobs, borgs can fill in for whatever department(s) are shorthanded, or simply want the help. That makes them a very good candidate for more slots.
I only kept the slot increase to +1 to minimize the controversy of this PR. Personally, I would prefer more than two borg slots.

**Comment by Markolie** [comment]
Well, I still wholeheartedly disagree. More synthetics will hamper with antags.

**Comment by pazneria12** [comment]
The Greytide already hamper with antags, so I honestly dont see what you mean.

**Comment by Fox-McCloud** [comment]
With the recent downward pressure on player population, this longer is really necessary.

**Pull request closed without merging**
