### PR TITLE
Adds in Aloe Vera and Comfrey and Random Seeds

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in Aloe Vera and Comfrey to botany.

- Aloe Vera has silver sulfadiazine in it and can be made into a poultice (attack self)
- Comfrey has styptic powder in it and can be made into a poultice (attack self)
 - Poultices are basically just alternate skin bruise packs/oinment packs that heal based on the potency of the grown item. By default, they heal slightly less than a regular advanced trauma/burn kit, but have the potential to be even more powerful, with a little time and effort.
 
Other
- Adds two random seeds to hacked hydro vendor

These were basically Baystaiton's old Tajaran herbal treatments; I just repurposed them into actual herbs.

### CODE REVIEW

**Comment by Earthdivine** [comment]
Which one does what?

**Comment by Fox-McCloud** [comment]
Aloe Vera is for burns, comfrey is for brute.

**Comment by Iamgoofball** [comment]
>not knowing aloe vera heals burns

**Comment by Aurorablade** [comment]
>not knowing aloe vera heals burns
>>Not knowing that not everyone is a uber martha stewart plant expert..

**Comment by Mijhead** [comment]
:+1: :heavy_multiplication_x: :100: finally, i can heal people without making them obese

**Comment by KasparoVy** [comment]
legit tajaran botanism

**Comment by Plotron** [comment]
Bartender's got milk and tomato juice and with proper access - he could make natural medicine pills.
Finally some love for the herbal department.

**Comment by Iamgoofball** [comment]
>not knowing aloe vera heals burns

>>Not knowing that not everyone is a uber martha stewart plant expert..

>>>using 2 periods

**Pull request merged**
