### PR TITLE
Adds AI Holopets

### PR DESCRIPTION
**Pull request by Chakirski**
What? More AI holograms?

Well, I said I would do it, and I did it...

If you want a full list of added animals, click the "Files changed" tab.

:cl: Chakirski
add: Added animal AI holograms.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Malf/emagged AIs getting syndifox/syndicat AI holograms? ;)

**Comment by Chakirski** [comment]
Maybe, plus a little extra. *wink

**Comment by Davdichan** [comment]
Where's mah corgi sprites with 30 different hats?

**Comment by Dumbdumn5** [comment]
@KasparoVy Bah, too obvious.

:+1: to PR

**Comment by taukausanake** [comment]
You forgot diona nymphs ;)

**Pull request merged**
