### PR TITLE
Make the lighting plane master respect client color and other lighting fixes

### PR DESCRIPTION
**Pull request by Markolie**
**What does this PR do:**
The lighting plane master currently doesn't respect the client color, which means that lighting is still colored for mobs with color blindness. This pull request makes the lighting plane master respect the client color.

With the new plane_master system, the noir sunglasses no longer display blood color. Sadly enough I don't see a way around this, aside from putting blood on their own plane which would be a bit overkill. As such, I've removed the NO_CLIENT_COLOR appearance flag from blood, as it doesn't do anything anymore. This wasn't a very good solution anyway, as I believe this also means that blood would still still be colored for color blind mobs with the old lighting system.

As a bonus, this also fixes pAI flashlights not working (which wasn't caused by the lighting update) and fixes minebot mesons not working either.

Fixes https://github.com/ParadiseSS13/Paradise/issues/11503.
Fixes https://github.com/ParadiseSS13/Paradise/issues/11531.

**Changelog:**
:cl: Markolie
fix: Lighting now respects color blindness again.
fix: pAI flashlights now work properly.
/:cl:

### CODE REVIEW

**Comment by Markolie** [comment]
If somebody wants to go about fixing the noir sunglasses, you could port over the NOIR_BLOOD_PLANE that /vg/ uses for their glasses. I don't really want to invest the time for that though, plus it seems like a messy solution just to have blood show up colored for a single pair of glasses.

**Comment by taukausanake** [comment]
What about the color blind that Vulpkanin and Tajaran get when they have normal eyes? Does this mean they don't get their true colorblindness? I don't assume to know anything about the lighting/color planes but thought I'd bring this up just in case

**Comment by Markolie** [comment]
Their color blindness is unchanged: this fixes the issue where lighting would still be colored when color blind.

**Comment by KasparoVy** [comment]
@Markolie Yeah you're totally right, colourblindness used to mean you could see blood just fine anyway

Geat job as usual, thank you for fixing it so fast! I tried looking over it myself and all I got out of it was a headache. Glad to see it was just some appearance flag manipulation.

**Comment by SkeletalElite** [comment]
TBH Blood showing up colored in noir sunglasses is pretty stylistic, considering they're the detectives glasses.

**Comment by Fox-McCloud** [comment]
In my opinion, this is for the better; blood showing up colored in noire is not consistent with the genre/time period, in relation to film.

Having an entire plane dedicate purely to blood decals would be pretty ridiculously, in my opinion.

**Comment by KasparoVy** [comment]
Yaaay

**Pull request merged**
