### PR TITLE
Zippos can light Cigars

### PR DESCRIPTION
**Pull request by Mooballoono**
## What Does This PR Do
It makes it so that all Zippo lighters can light all Cigars

## Why It's Good For The Game
it just doesnt make sense why a classy zippo lighter is said to be too uncivilized to light a cigar

## Testing
i booted up the code and tried lighting all cigars with all zippos and then checked to make sure cheap lighters couldnt light the cigars

## Changelog
:cl:
tweak: You can now light cigars with zippos
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
"tweak: You can now light cigars with zippos" I would recommennd this for the changelog.

**Comment by Mooballoono** [comment]
> "tweak: You can now light cigars with zippos" I would recommennd this for the changelog.

I was thinking of doing that but couldn't decide. I changed it though

**Comment by Mooballoono** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

I swear I already linked this but I linked it again.

**Comment by SteelSlayer** [comment]
Author has linked their forum account.

**Review by Sirryan2002 — APPROVED** [review]

**Pull request merged**
