### PR TITLE
Adds new sprites for skills huds

### PR DESCRIPTION
**Pull request by kugamo**
## What Does This PR Do
Fixes https://github.com/ParadiseSS13/Paradise/issues/14449
This PR adds unique sprites for the skills huds, and the skills sunglassers. Species specific sprites for drask, grey, and vox too! 

## Why It's Good For The Game
The skills huds will now have their own unique sprites, instead of using the same sprites as the material hud. And thats good.

## Images of changes

SkillsHudsExample

skillmedcompare

## Changelog
:cl:
imageadd: Adds sprites for skills hud, and skills sunglasses.
/:cl:

### CODE REVIEW

**Review by SteelSlayer — APPROVED** [review]

**Review by variableundefined — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Comment by AffectedArc07** [comment]
image
Not sold on these to be truly honest. It seems to have too steep of a gradient
image
Like it looks really off to me

**Comment by kugamo** [comment]
> 
> 
> Not sold on these to be truly honest. It seems to have too steep of a gradient
> Like it looks really off to me

I tweaked these a bit, I think it an improvement.
AAcritique

**Comment by AffectedArc07** [comment]
> > Not sold on these to be truly honest. It seems to have too steep of a gradient
> > Like it looks really off to me
> 
> I tweaked these a bit, I think it an improvement.
> AAcritique

I would still make the lightest part of the gradient darker. Use of pure white on a sprite doesnt always look good, and it sohuld be tinted a little.

**Comment by kugamo** [comment]
>
>
> I would still make the lightest part of the gradient darker. Use of pure white on a sprite doesnt always look good, and it sohuld be tinted a little.

thats not pure white, the old ones were. the lightest part is now 'F4F6FF'. I understand it looks pretty bright, but thats the effect I want to display.

**Pull request merged**
