### PR TITLE
Removes Mutiny

### PR DESCRIPTION
**Pull request by Fox-McCloud**
It's been broken about 2-3 times by now and never has been fixed (For over a year)--it's long overdue for this mode to be properly stripped from the code. It's also been removed on Bay/Polaris, so there's really no direction we can go with this. Also the code isn't...good.

Other
- Removes RP Rev objective
- Updates config to reflect the live-server

### CODE REVIEW

**Comment by Jaywings** [comment]
Had to happen

**Comment by Vivalas** [comment]
"ocnfig"

Sorry but I can't help being a grammar Nazi.

**Comment by Earthdivine** [comment]
When the HRP server removes the Roleplaying Game Mode, you know there's problems that cant be solved.

**Comment by Plotron** [comment]
Should be titled "Improves Mutiny" [By Removing It]

**Comment by Spacemanspark** [comment]
Stops all mutiny against the server.
Fox McCloud has greentexted

**Comment by TheDZD** [comment]
Rest in pieces.

**Pull request merged**
