### PR TITLE
Race rebalance PR

### PR DESCRIPTION
**Pull request by Anasari**
People keep complaining about other races being human+ so now I'm making them human-.

Human shall by design become the new master race! 

Jinrui no kagaku wa sekai ichi!

🆑
fix: Human now superior race, able to howl, beep, buzz and click unlike other inferior alien species.
fix: HUMAN SCIENCE IS THE BEST IN THE WORLD!!!!!!!oneoneone1111
/🆑

### CODE REVIEW

**Comment by tigercat2000** [comment]
Best PR.

**Comment by MarcellusPye** [comment]
10/10

**Comment by TullyBurnalot** [comment]
Speedmerge.

**Comment by taukausanake** [comment]
You got my hopes up there for a little bit. I don't think we'll ever have true specie differentiation at this rate

**Comment by Regen1** [comment]
Whoever taught Ansari how to make PR's; You brought this upon all of us

**Comment by Rumiluntti** [comment]
Change human scream sound to vox skree.
Clearly an oversight

**Comment by tigercat2000** [comment]
The Vulpkanin association has deemed this PR unacceptable. As such, it shall be terminated swiftly.

**Comment by LittleBigKid2000** [comment]
FUCKING 4RRY MAINTENARS FORCING THEIR FETISH ON US!!!!!!!

**Comment by Doukhan** [comment]
God damn Vulvakin mafia strikes again.

**Pull request closed without merging**
