### PR TITLE
AI is rogue, blow the borgs!

### PR DESCRIPTION
**Pull request by RyanSmake**
:cl:Bxil
rscdel: You can no longer mass destroy all cyborgs.
/:cl:

Traitors are far too trigger-happy nowadays.

### CODE REVIEW

**Comment by Birdtalon** [comment]
Borgs don't need even less weaknesses. No.

**Comment by granodd** [comment]
What a deliciously vague change log. How exactly does this prevent the mass destruction of borgs? I assume removing the "detonate all" button, if there was one (I can't remember).

**Comment by DesolateG** [comment]
@Birdtalon  and Antags don't need a meta that ruins a player's round at the single touch of an easily created button.

**Comment by bigfatbananacyclops** [comment]
Yeah no

**Comment by DesolateG** [comment]
Of course you'd say no Mike.. this is one of your biggest cheese tactics.

**Comment by KasparoVy** [comment]
LOL tellem

**Comment by RyanSmake** [comment]
For the record, I am going for the **Most Unpopular Contributor of the Month**.

Also, you can still blow them, but you gotta do it one at a time.

**Comment by Fox-McCloud** [comment]
They can blow individual cybrogs; this is effectively just a shortcut. There's no reason to remove this, but keep the ability to blow individual cyborgs (and no, removing that won't fly either, as far as I'm concerned).

**Comment by alexkar598** [comment]
I'd say to make it lock down the borgs instead of blowing them up

**Comment by RyanSmake** [comment]
There is one reason, fox, which is people blow them because it's too easy. As Alex said, why do we have a "blow all" when we don't have a "lock all"?

**Comment by Fox-McCloud** [comment]
Feel free to add it.

**Comment by Aurorablade** [comment]
There's no reason to remove it. If you blow all the borgs for no reason you are in deepshit as a non antag. As antag you still should have a good reason.  This would also buff traitor ais immensely.

**Comment by davidchan13** [comment]
@Birdtalon play borg before you think they have too few weakness and shortcomings.

@RyanSmake make it so borgs need to be lockdown before they can be blown so there is at least some warning and chance to react on the part of the AI, realistically an AI should get a very noticeable message anytime one of their borgs is locked down via the robotics console.

**Comment by Birdtalon** [comment]
I have played borg. They have too few weaknesses and shortcomings.

**Comment by Plotron** [comment]
It's an interesting (albeit useless) PR, but at least it provoked some discussion.
I agree with @davidchan13 that we could revisit this feature and make it better.

**Comment by RyanSmake** [comment]
Don't close this yet, I will come up with something different in a few days.

**Comment by Shadeykins** [comment]
I think if we want to have a useful compromise, turn it into a self-contained EMP like it is with the exosuits. All the borgs receive heavy damage and a fairly lengthy stun, thereby dramatically reducing their effectiveness.

**Comment by SilvernKell** [comment]
I feel like it shouldn't be removed but switched to lockdown all to encourage people to, you know, lock them down and let them be recovered instead of just mass blowing holes in the station and hurting all the people you are nearby as much as the borgs themselves. It would also be kinda nice if blowing the borgs made the borgs have a 5 second alarm for people to atleast try and move away from them as it was incredibly sad that I blew the limbs off my secbuddy out of nowhere one time

**Comment by RyanSmake** [comment]
Closing in favor of #8953.

**Pull request closed without merging**
