### PR TITLE
Revert "Changes View Range to Default of 15x15"

### PR DESCRIPTION
**Pull request by TheDZD**
Reverts ParadiseSS13/Paradise#1728

#1728  should **not** have been merged in early. I was fine letting this go through after a few days assuming discussion had taken place and the overall consensus was for the change. That did not happen, it was merged early despite a numerous amount of players and admins voicing their complaints against the change.

EDIT: Poll numbers were significantly different when #1728 was merged, with only ~3 votes against 15x15 and ~15 for it. That said, it was evidently too short a time period for people to contribute their opinions, given the complete 180 the poll took over approximately 12 hours after the merge.

Currently DNM for a ~2 week trial period of 15x15, vote on the [forum poll](http://nanotrasen.se/forum/viewtopic.php?f=48&t=5582) as to whether or not you would like to see the 15x15 view range remain.

**Keep ad hominem attacks outside of both the comments here and the forum topic, you're arguing over a vision radius increase of 1 tile.**

### CODE REVIEW

**Comment by adrkiller59** [comment]
There, well done.

IF I GET MY CHAT SPAMMED AGAIN WITH YOUR CODER DRAMAS HEADS WILL ROLL. I GAVE YOU A CODERCHAT FOR A REASON.

OR I WILL FIGURE OUT HOW TO DISMANTLE THE MAINTAINER SYSTEM AND PUT FREESTYLALT AS HEAD CODER. I SWEAR I WILL. 

STICK TO YOUR OWN RULES, YOU FUCKWITS.

**Comment by Robertha89** [comment]
If this passes, I will fix: 
Animal Vision Range
Cinematics, either by resizing or just remaking
Sprite Squshing and Squashing

**Comment by FreeStylaLT** [comment]
oh boy here we go :corn:

**Comment by Spacemanspark** [comment]
Ohhhhhh boy.

**Comment by melandor0** [comment]
Yes. Stop this madness, revert this shit.

**Comment by SamCroswell** [comment]
17x is objectively more powerful*

**Comment by Mijhead** [comment]
@SamCroswell Didn't a slippery slope get used last pull too, but the other way around?

**Comment by SamCroswell** [comment]
@Mijhead 
The point I'm trying to make is not that our view range is going to keep getting bigger. I severely doubt we'll get any larger than 17x.

The point I'm trying to make is that seeing more is more powerful. And we shouldn't confuse more powerful with better.

**Comment by tigercat2000** [comment]
@SamCroswell I don't think we should confuse more powerful with worse, either.

**Comment by Ultimate-Chimera** [comment]
17x17 is shitty because 1. You can NOT click sprites at all, I aim my cursor and mash my mouse and NOTHING happens 2. the sprites look HORRIBLE because they are made for 15x15 3. it's just ONE tile difference, big deal? 3. Everything will look bigger.

**Comment by SamCroswell** [comment]
@tigercat2000 
I never said it was, but the argument being made here is more powerful = better.

**Comment by Ultimate-Chimera** [comment]
Maybe make a thing in the icons menu to either have 17x17 or 15x15.

**Comment by Nienhaus** [comment]
This was based on if you are using a monitor that is 1920 x 1080. I'm sure the measurements are a bit off but imo the point still stands.
http://i.imgur.com/5pfjYdb.png 17x17 32x32
http://i.imgur.com/iNOlLsb.png 15x15 32x32

http://i.imgur.com/s48YLXJ.png 17x17 64x64
http://i.imgur.com/HYM9rnG.png 15x15 64x64

http://i.imgur.com/GfVgGra.png 17x17 Stretch to fit -Note, looks a bit different ingame as I can't recreate Byond's shitty scale down to well.
http://i.imgur.com/HYM9rnG.png 15x15 Stretch to fit -Note, same picture as 64x64 because it fits the screen

**Comment by Mijhead** [comment]
@Nienhaus Don't forget the recent https://github.com/ParadiseSS13/Paradise/pull/1733

**Comment by Nienhaus** [comment]
But Mijhead, I closed things already :C

**Comment by Nienhaus** [comment]
http://i.imgur.com/nPqIDox.png 17x17 48x48
http://i.imgur.com/liIOGF9.png 15x15 48x48
Same thing as before, based off a 1920x1080 screen.

**Comment by Robertha89** [comment]
Reposting this here
56x56 at 17x17
image
VS 
64x64 at 15x15
image
This would be my fix to the icons being squished and hard to click

**Comment by Nienhaus** [comment]
Is it bad I just noticed all my 17x17 is actually 19x19?

**Comment by Nienhaus** [comment]
http://i.imgur.com/5pfjYdb.png 19x19 32x32
http://i.imgur.com/Irx7zOT.png 17x17 32x32
http://i.imgur.com/iNOlLsb.png 15x15 32x32

http://i.imgur.com/HYM9rnG.png 19x19 64x64 -Note, These all look the same so one image is needed.
http://i.imgur.com/HYM9rnG.png 17x17 64x64 -Note, These all look the same so one image is needed.
http://i.imgur.com/HYM9rnG.png 15x15 64x64 -Note, These all look the same so one image is needed.

http://i.imgur.com/GfVgGra.png 19x19 Stretch to fit -Note, looks a bit different ingame as I can't recreate Byond's shitty scale down to well.
http://i.imgur.com/KXSFXpW.png 17x17 Stretch to fit -Note, looks a bit different ingame as I can't recreate Byond's shitty scale down to well.
http://i.imgur.com/HYM9rnG.png 15x15 Stretch to fit -Note, same picture as 64x64 because it fits the screen

http://i.imgur.com/nPqIDox.png 19x19 48x48
http://i.imgur.com/pPxnEEr.png 17x17 48x48
http://i.imgur.com/liIOGF9.png 15x15 48x48

**Comment by SamCroswell** [comment]
@Robertha89 
Doesn't fix 'em looking like crap.

**Comment by MindLeaker** [comment]
:+1: for this, there was a 50/50 split on the PR, completely ignored

**Comment by TheDZD** [comment]
@MindLeaker At the time the PR was merged, it was heavily in favor of 15x15, over the last ~16 hours that has changed significantly.

poll

**Comment by Alex6511** [comment]
:-1:

**Comment by Flip-Sandwich** [comment]
:-1:

attack the argument not the person , the code not the coder, and likewise, the feature, not the github pull request process

**Comment by Dumbdumn5** [comment]
:+1: Vote did not have enough time to go through, one day is not enough to tally in all of the votes, some people need more than one way to decide.Vote as of today. http://imgur.com/R2mPVwp

**Comment by Dumbdumn5** [comment]
Wait a minute, just thought of something... why not use the changeviewrange verb in special verbs, restrict the values to view ranges 15x15 and 17x17, and then make it available to users? If you use 15x15 you know the risks, but you get to appreciate the artwork and click on bigger sprites, would be much better if mobs were a bit slower so they didn't have to worry about getting murdered by a passing carp that breaks the sound barrier.

**Comment by M3hillus** [comment]
So, an optional zoom verb?

**Comment by Dumbdumn5** [comment]
Yup.

**Comment by Markolie** [comment]
Sorry for the delay on this - due to timezone differences between the maintainers and heads of staff it occassionally gets difficult to make decisions that have the full backing of the team. Either way, we've come to what we consider to be an amicable solution to this problem.

First off - let me apologize for merging the pull request early. At the time, I believed there was a concensus between the community and the coders and figured we should merge it in on time to get people to get used to it. As it turns out, the poll went from 15-3 to 15-21 over a matter of hours, which was something neither I nor anyone else had quite expected.

However, had I not merged the pull request two days ago it would've gone through regardless, despite opposition from some people. I strongly believe that until hell freezes over, we will never come to an agreement with regards to the view range, no matter what arguments people bring up. At that point it is the responsibility of the maintainers to decide what happens with the pull request, and whether or not it is merged. Because, after all, the executive power is a necessity in any system to make sure decision making actually happens, rather than having endless bickering. And we believe, that in the best interest of the server, that 15x15 is indeed a preferable solution that puts us in line with other servers, and resolves several longstanding issues with the 17x17 view range.

I realise that some may not like this, and that is why this is not a permanent change - there will be a two week trial (maybe a bit shorter or longer depending on time needed) where these changes can be tested so players can form a proper opinion, rather than jumping on the bandwagon for either side. At the end of the trial period we will determine whether or not the view range change has a positive impact on the server.

Finally, I want to urge you all to consider that we are arguing in a very heated manner over two tiles of view distance in a 2D spessman game on an open source codebase. Let's all try to keep a calm head in the future - and steps will be taken to ensure that such heated discussions will be a thing of the past. No-one is making changes just for the sake of annoying others, everybody makes change with the server's best interest in heart and to make it a better place. Please keep that in mind.

**Comment by SamCroswell** [comment]
@Dumbdumn5 
That has been discussed to death.
It's a false choice, anyone who is robust will be on 17x up until they engage in melee combat, upon which they will switch to 15x for easier clicking of the person they are toolboxing.

**Comment by Flip-Sandwich** [comment]
@SamCroswell Then why not make it a preference setting option, locked in for the round?

**Comment by SamCroswell** [comment]
Then everyone will pick 17x17. Having an extra tile of view range is an awesome benefit.

**Comment by Mijhead** [comment]
But they'd have the disadvantage of a harder time clicking on people to robust.

**Comment by KasparoVy** [comment]
wtf brud 15x15 life

**Comment by Spacemanspark** [comment]
How does this spark such controversy.
I personally like 17x17. There. Done. That's all that I need to say.

**Comment by KasparoVy** [comment]
I wish there was an option to choose b/w 15x15 and 17x17
I'd be happy giving up the square, regardless of whether or not others get it as an advantage
64x64 with that hud clip just didnt cut it

This way everyone'd clam up about it

**Comment by sasanek12** [comment]
in my opinion, on 15x15 Tajaran sprites look at least broken, also meyes start to hurt after few minutes

**Comment by Necaladun** [comment]
I think Mark has said it best here. It's such a minor difference I'm having a lot of trouble caring as much as anyone else is and am rather confused as to why this is such a controversial issue with people so worked up.

**Comment by Robertha89** [comment]
If it was a minor difference then this pull would merge, or the previous one not being merged at all. For me it's just tics me to remove something because of x, instead of fixing x, I find that to be a terrible game choice, but as was mentioned, there will be a trial period of a week or two, but i doubt people will care as much cause the change already exists, had the previous pull not been merged ahead of time, it would have ended up not getting merged cause it already existed.

**Comment by Markolie** [comment]
It still would've been merged, Robertha, per my previous statement.

**Comment by Dumbdumn5** [comment]
Been two weeks, vote at the time of writing stands at. http://imgur.com/oA32EDd
29 for 15x15
40 against
7 for "Not this again"
and 12 for either one.

**Comment by Spacemanspark** [comment]
That image is broken, @Dumbdumn5.

**Comment by Markolie** [comment]
The two week trial period has passed, and we have reached a decision on how we're moving forward with the view range issue. Before I give the reasoning for the decision, let me remind everyone to read the post I wrote earlier and to stay level-headed. We will lock this discussion and enforce the rules if the discussion becomes too heated.

So, based on the trial period, we have decided to stick with the 15x15 view range. While there are members in the community that still prefer the 17x17 range, there's no clear concensus or majority for either side. The poll on the forums has been equalizing as of late, with currently 33 votes in favor and 40 votes against (and 18 people that don't care either way). As such, due to a lack of concensus and overwhelming majority, the choice whether or not to revert this change lies entirely with the maintainers. All three maintainers have voted in favor of retaining 15x15, as well as one of two head admins (the other one abstained). 

As such, we'll be closing this pull request as well as the poll on the forums. Of course feedback with regards to the view range is still appreciated, but try to keep the discussion from getting heated.

**Pull request closed without merging**
