### PR TITLE
Clean up mob code a bit

### PR DESCRIPTION
**Pull request by tigercat2000**
Does the following:
 - Cleans up how gravity works, a little bit
 - Pushes duplicated procs for slimes/xenos/humans up to carbon/Life()
 - carbon/Life() is now a thing, it handles the non-special stuff for all
   carbons
 - Mob controller no longer ticks a seperate entity, mob_master is now
   just a reference to the mob process, which ticks.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Oh, and simple animals will now resize correctly.

**Comment by Earthdivine** [comment]
>simple animals will now resize correctly

All hail Polygod.

**Comment by Fox-McCloud** [comment]
I noticed you moved a few of the procs to be out of order from what they used to be. Why?

**Comment by tigercat2000** [comment]
@Fox-McCloud Can you specify what you are talking about?

**Comment by Fox-McCloud** [comment]
For example, in humans, things are processed in this order (with procs in between, of course):

- Chemicals
- Regular Status Updates
- Updatecanmove

That said, you changed this around to status, chemicals, updatecanmove in carbon.

**Comment by tigercat2000** [comment]
Probably because the carbon/Life() is more or less copy-pasted from an older -tg- version. tgstation/-tg-station@05e3c30

I can change the order back around, if it matters.

**Pull request merged**
