### PR TITLE
Fixes #9622 by not giving plasmemes an extra penlight.

### LINKED ISSUE #9622: Plasmafolk doctors spawn with two penlights
Related PR: #9621 
Look for that PR on how to fix it.

Details:
When a plasmafolk doctor, you will get two penlights, instead of one.

### PR DESCRIPTION
**Pull request by dapocalypse**
**What does this PR do:**
Removes the extra penlight given to plasmamen.

**Changelog:**
*Remove this line, and appropriate fields from the changelog*
:cl: Not giving plasmamen extra penlight.
balance:  Removed extra penlight given to plasmamen.
/:cl:

### CODE REVIEW

**Comment by dapocalypse** [comment]
#9622 for the reference on the issue.

**Comment by Birdtalon** [comment]
You need to clean your master branch for these leading merge commits.

**Comment by dapocalypse** [comment]
how do I do that

**Comment by Crazylemon64** [comment]
while checked out onto your branch:
`git reset --soft upstream/master`
`git commit -m "Fixed double penlights for medical plasmafolk"`

**Comment by dapocalypse** [comment]
`fatal: ambitious argument 'upstream/master': unknown revision or path not in the working tree`

**Comment by Birdtalon** [comment]
Replace upstream with whatever this remote is named.

**Pull request closed without merging**
