### PR TITLE
[Ready for Review]Updates sprite for the library/old computers, and adds "old" looking machinery to the old station.

### PR DESCRIPTION
**Pull request by Quantum-M**
**What does this PR do:**
Updates the sprite for the library/old computer icon, along with replacing the computers of the old station with said computer, and making the RnD machinery look more old, as the station has been in hibernation for around 100 years.

**NOTE!** Needs some testing to make sure nothing broke, along with more in game examples of the items, more images and testing will come tomorrow.

**Images of sprite/map changes (IF APPLICABLE):**
oldcommand
solarsoldcomp
oldsecurity
oldmech
oldrnd

oldcircuit
olddestructor1
olddestructor2
oldprotolathe

image

**Changelog:**

:cl: Quantum-M
add: Old looking sprite RnD machinery
tweak: Replaces the computers in old station with the new library computer sprite.
fix: Fixes a missing button in the old station prototype room.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'm not really a fan of these sprites, to be honest.

The most consistent sprite themes that exist, to date, are from TG and Goon.

Given that Goon's sprites are still all over the place and that anything new is technically not something we're supposed to use...well, it just makes sense to go more with TG for sprites, to be honest.

SS13 is retro future, not dilapidated junk.

**Comment by AffectedArc07** [comment]
I really like the look of these, especially the imprinter

**Comment by Citinited** [comment]
Nice to see beige is back in fashion in the 2500s

:smile:

**Comment by Ty-Omaha** [comment]
I like the old computer sprites better

**Comment by Quantum-M** [comment]
> 'retro future', not 'dilapidated featureless junk'.

@Fox-McCloud , that's literally what the old station is, since it has been abandoned for a very long time.
All the sprites here, with exception of the old computer, are _only_ used in the old station, because it has been left almost fully abandoned for _almost 100 years._

It wouldn't make sense for styles of items and machinery to last that long and be the same, and the station itself has items that are "prototypes" of what the station has, like the hardsuit, the HoS' gun, and the health analyzer.

And I am not sure what you mean by goon, none of these sprites are based on their sprite work when I worked on it.

**Comment by taukausanake** [comment]
I hate these sprites to be honest. I like the theme for the old machines but not the style. I never liked the front boxy look. I much more enjoy the more side view we have with all the current sprites. These would stand out in relation.

If you're going to introduce sprites like these then your going to need to make all other sprites match up. That's going to be a dark day in my opinion

**Comment by Agameofscones** [comment]
Guys guys these sprites are only for old station, the ghost role area, 😅

Stylistically I think it's a great direction to be taking things, I mean we can argue SS13 is 'retro-future' all we want, but that theme has long been departed from on most stations into a weird mash of super sci-fi and cutting edge alongside tape-deck driven universal recorders.

And @Fox-McCloud , I'd argue CEV Eris, Bay, & CM, have the most consistent sprite themes, having things appended to specific palettes, written documentation on how shading is supposed to be done (Mostly CEV Eris though, oh my lordy they're uniform). Hell most new TG sprites _come_ from CEV Eris with minor modification. As well, saying Goon & TG are all over the place is saying the same about Paradise, (Which _is_ all over the map)

@Quantum-M Your sprites are quite nice, the shading is consistent, the outline pattern isn't broken from. It's a shame they aren't that appreciated, you've clearly put quite a bit of effort into them. The animations are also quite good. I hope you imported those and didn't use the horrid tools the Byond IDE offers.

@taukausanake 'Front boxy look', I think you refer to 3/4 forced perspective? I would agree it's not a great fit for Paradise since we've still non-perspective walls, so having objects as such doesn't make too much sense. At the moment most object styles are a stilted top-down or rotated low angle like the auto-lathe with some implied depth. Again, all over the map.
Also, personally I think hate is a bit of a strong word for a set of sprites! Surely you don't loathe them as much as you state you do no? Perhaps more constructive feedback on what makes them not work would be a better call in this situation. Opening a dialogue wherein modifications can be made to satisfy all parties involved is a great way to adapt new sprites and keep a consistent style! Let's not push away our contributors, they do work for free after all.

Personally I think these sprites would be an _exceptional_ bit of fluff for the Old Station (Again note this is not for regular ol' R&D) and would be a nice treat for players that do wind up taking the ghost roles, as it'd really sell the idea of _Hey kid you just woke up out of 100 years of cryo sleep, it's the future that ran on tape-decks and monospaced fonts and raytube TVs, it's crap, you gotta make it work for you_

**Comment by taukausanake** [comment]
@Agameofscones It's true, I don't hate these sprites as they are but I hate the concept that every time new sprites are being introduced it's normally these type of sprites. I never liked the 3/4 perspective and quite enjoy the rotated ones we have now. I will always be completely against the 3/4 perspective sprites

**Comment by Ty-Omaha** [comment]
>Guys guys these sprites are only for old station, the ghost role area, 😅

No it changes the library computer

**Comment by shazbot194** [comment]
[As a dev for CEV Eris, /TG/ does use a fair few of our sprites, as does a lot of other servers. ](https://github.com/tgstation/tgstation/pull/28285)

**Comment by Agameofscones** [comment]
> > Guys guys these sprites are only for old station, the ghost role area, 😅
> 
> No it changes the library computer

This can easily be changed if the author intends so, with just a flick of the wrist and a copy and paste the two computers can refer to different icon states. Perhaps that would make a decent compromise. 

I propose that the old computer be shifted to the new palette and re-shaded accordingly. It isn't the most well looking of the sprites, but hardly the worst. It could do for improvements. This would address the perspective concern, while modernizing and updating an objects look and feel to better match content going forward. While we cannot uniform-ify Paradise, as a collective we can push for a consistent theme going forward in all new sprite sets.

**Comment by Ty-Omaha** [comment]
Yes I agree it can be easily changed if the author intends to

**Comment by Quantum-M** [comment]
Thank you @Agameofscones , I do use the BYOND dream seeker, but it did have a recent update and it's way nicer to use (even if it still has some bugs).

If it's a issue, I can change the library icons back to their old sprites, @Ty-Omaha , because the library sprites are in a different .dmi file to the computers in the old station. Mind, I am not sure if I can make the sprite nicer in the current slanted perspective, as I am more better with 3/4 perspectives.

**Comment by taukausanake** [comment]
I think I'd be okay if they are just old station but I still dislike how they clash with what is already established. Rather have icons that match the rotated one but don't change the on-station computer

**Comment by Quantum-M** [comment]
The library computer has been changed to it's previous, slanted sprite. All sprite additions _should_ only stay at the old station.

**Comment by Agameofscones** [comment]
It appears I've been using the wrong terminology this entire time, my apologies if I've caused any confusion! 3/4 perspective _does_ actually refer to the current machine sprites that we have at their stilted look with a front and fake depth and top. 

What @taukausanake is against and what these sprites are, if I'm not mistaken, (and I could still be wrong, it's been awhile since I've taken figure drawing), is an orthographic projection perspective at a 45 degree profile from an elevated camera, where in all parts of the object's scale are relative to itself first, and secondly to the camera.

**Comment by taukausanake** [comment]
Yeah, I'm not going to pretend I know which is which. I like the ones that have three sides (front, top, right) and dislike the ones that have two sides (front, top). The latter just look too flat and boring to me

**Comment by Quantum-M** [comment]
Added a mech fabricator sprite for the old station, along with testing images, only one oddity is left before this is ready for review.

**Comment by MrMagolor** [comment]
based on the GIF you posted, I feel like the animation for the old protolathe plays for a bit too short of a period, but maybe that's just because the example item (science goggles) are quick to print anyways.

**Comment by Quantum-M** [comment]
Fixed conflicts (hopefully), and added a button that seemed to be missing in the old station prototype room.

**Comment by variableundefined** [comment]
Nearly all sprites of machines and vending machine on Paradise has a 3/4 view instead of a front-and-above viewpoint (Correct me if my terms is wrong). 

Old machines **should** look visually different, however, it shouldn't be inconsistent in perspective compared to the rest of the machines. This will only add to the problem of inconsistent sprites on Paradise.

**Comment by Kyep** [comment]
I can't support this, as I don't feel like the sprites look good.

**Comment by MrMagolor** [comment]
> I can't support this, as I don't feel like the sprites look good.

I thought you said in your forum post that you'd also provide explanation, as well as possible fixes, in your PR comments relating to votes.

Saying "I don't like it", isn't exactly in-depth. At least say _why_ you think the sprites don't look good?

**Comment by Kyep** [comment]
@MrMagolor The sprites look like a computer from the 80s. In the time period that SS18 is set in, their definition of "retro" shouldn't match ours. The sprites themselves don't look good visually, they're grey, boxy, and use a non-standard (for us) perspective. To obtain my support for this PR, the sprites have to be replaced with different ones.

**Comment by Quantum-M** [comment]
As it seems this PR won't go through due to the sprites, and that I prefer to not re-sprite the sprites to a perspective I am not good at, I am closing this PR.

**Pull request closed without merging**
