### PR TITLE
Resprites Sleepers, Cryopod, Bodyscanners, and Cryogenics console

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
Ports updated sprites for the [cryopod, cryogenic console](https://github.com/shiptest-ss13/Shiptest/pull/779), sleeper, syndicate sleeper, and bodyscanner from [Shiptest](https://github.com/shiptest-ss13/Shiptest/pull/1065) (though the body scanner predates shiptest, not sure which server it originated with). I made adjustments to the pods' left and right closed sprites so the angles matched the open sprites (and our old pod sprites), plus I redid the animation on the bodyscanner.

## Why It's Good For The Game
The old pod sprites were smudgy and oooollld. The cyro console also was ancient. And it's nice to have a bodyscanner that isn't just a duplicate of the cryopod sprite!

## Images of changes
image
image
image
image

## Testing
Checked that the sprites worked, including closed an open states and the screwdrivere'd state. Also checked the cryoconsole lightmask.

## Changelog
:cl: PositiveEntropy, SomeAngryMiner, Quantum-M, PacifistDalek
imageadd: New sprites for cryopod, sleeper, body scanner, syndicate sleeper, and cryogenics console
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
The new sleeper sprites look a bit uncommonly shiny, and it's a lil unfortunate that we'd also lose a fairly prominent animation (while occupied) in the process. Not a fan at all of the new body scanner either; its style is very out of place and it frankly looks like some kind of fancy shelf when empty.
New cryosleep console looks great, though!

**Comment by PacifistDalek** [comment]
For the shininess, do you refer to the metallic base of the machine or the glass?

I was curious to see people’s response to the body scanner, I could always just make a different colour sleeper instead for it.

Thanks for the feedback!

**Comment by McRamon** [comment]
We will need to work on.these, especially scanner

**Comment by hal9000PR** [comment]
author is unable to continue with this PR due to IRL situations. filing as closed. anyone is free to pick this PR back up with the requested changes.

**Pull request closed without merging**
