### PR TITLE
TGUI-ise and optimize all instrument code

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

This commit replaces instrument's NanoUI by TGUI. It also adds some optimizations:
- No longer constantly update the UI every MC tick. Sending the entire song to the UI is costly. The UI is only updated when needed. This means the UI won't have a stroke when someone imports a song anymore
- When playing a note, cache `fexists` result into a static associative list. In my benchmarks it caused the brunt of Self CPU in the proc, which is now gone with the cache.
- When playing a note, replace `hearers()` by a loop through `GLOB.player_list`. Uncontrolled mobs don't hear the sound anyway (perhaps there could be some behaviour tied to that, but...)

## Why It's Good For The Game

Instruments no longer laggy for the player and (presumably) the hearers

## Images of changes

5laWf8yX13

## Changelog
:cl:
add: Overhaul instruments UI with TGUI
fix: Major optimizations to instruments
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
ohhohoohhooh i hope this means i can get longer songs in this, and they dont glitch out as much if to many notes play! Cant wait to test this

**Comment by dearmochi** [comment]
@Carthusia The final BPM is currently calculated as such (I didn't touch that part but I might look at doing so if it doesn't break songs): `600 / x` where `x ∈ {0.5, 1, 1.5, 2, 2.5, ...}` (basically every multiple of 0.5, you get it). That has problems if you wish to fine-tune because you can't go in-between. Regardless, I'll take a look tomorrow for that issue

**Comment by Mitchs98** [comment]
Aided Mochi in testing it privately. Unsure of how it will perform on live, but it handles even the longest songs from the Tau Ceti wiki with absolutely zero lag and no song breaking. It's 100% better than anything we have by far. I love it.

**Comment by dearmochi** [comment]
Closed while I look at a look at a [PR that might be worth adding.](https://github.com/tgstation/tgstation/pull/51459)

**Comment by silicons** [comment]
totally stealing this pretty tgui interface when that pr gets merged :heart:

**Comment by dearmochi** [comment]
@silicons glad you like it! I made a follow-up PR that is more up to date [here](https://github.com/ParadiseSS13/Paradise/pull/13865#pullrequestreview-451796447)

**Comment by AffectedArc07** [comment]
@silicons sidenote, I am honeslty surprised that name wasnt taken before. The real question is though, whos going to take kevinzz

**Pull request closed without merging**
