### PR TITLE
Serverside titlescreen icons.

### PR DESCRIPTION
**Pull request by tigercat2000**
(Port of https://github.com/tgstation/tgstation/pull/24563)
This adjusts our titlescreen system to allow for hosting title screens
seperately from the codebase, for licensing reasons and other. It
supports both per-map title screens and "rare" screens, which are both
done by parsing in the form of naming the file.

Usage is covered in config/title_screens/README.txt, to summarize:
 - All title screens must have unique names. These can be anything, so
 long as they do not use the + or . characters (in the name). Example: NewLobby.png,
 DeadCats.jpg.
 - Any format BYOND can read is supported, the file extension doesn't
 really matter; Only exception is that .dmi files must only have *one*
 state, and it must not have a name.
 - Map-specific title screens are parsed by adding the MAP_NAME to the
 start of the image. Example: MetaStation+NewLobby.png,
 Cyberiad+NewLobby.png
   - I changed the MAP_NAME of the NSS Cyberiad from NSS Cyberiad to
   Cyberiad for this reason, to avoid any compatibility issues between
   filesystems.
 - Rare title screens can be made by using the format rare+name.ext.
 Example: rare+NyanCat.gif, rare+Mrowl.dmi
   - You cannot use both map-specific and rare modifiers at the same
   time to reduce parsing complexity.

Does not provide any new title screens currently, nor are any planned. The flashing red lobby is still used.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I don't know how I got this far without realizing the title was hilariously inaccurate :man_facepalming:

**Comment by Fox-McCloud** [comment]
Really neat.

**Comment by Krausus** [comment]
> I changed the MAP_NAME of the NSS Cyberiad from NSS Cyberiad to
> Cyberiad for this reason, to avoid any compatibility issues between
> filesystems.

It's the 21st century. We probably don't need to worry about having spaces in filenames.

You can just get rid of the spaces anyway, by feeding the map name through `ckey()` instead of `lowertext()`. It might be better to add a completely separate "internal" identifier, though, so there aren't side effects to simply renaming the station.

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

Could you please make the server side changes required for this?

**Comment by Twinmold93** [comment]
Still waiting on this so we can have rotated lobby screens with no effort

**Comment by taukausanake** [comment]
Doubt there will be rotated lobby screens. More like easier to meme lobby screens.

Offtopic, but how does one turn the lobby screen into the field that was done once and then someone made all the tiles spin? That was cool, having a little world that the lobby could see

**Comment by Fox-McCloud** [comment]
@Crazylemon64 did you make the changes for this, yet?

**Comment by Crazylemon64** [comment]
Changes made

**Comment by KasparoVy** [comment]
@taukausanake Build mode and deleting the title screen object.

**Pull request merged**
