### PR TITLE
shuttle bay windows

### PR DESCRIPTION
**Pull request by orelbon**
changes the wall in the engineering shuttle bay to windows, because spess is beautiful.
windowss

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Sure, why not.
:+1:

**Comment by orelbon** [comment]
@Fox-McCloud im gonna wait to see if this gets merged so i can do a clean fork of the station code.

**Comment by Crazylemon64** [comment]
@orelbon The branch that's active when you create a new branch is used as the baseline for that branch; If you used this branch before you made your cyborg rechargers branch, I could see that causing the issue

**Comment by orelbon** [comment]
@Crazylemon64 i use the github desktop client, when you make a new branch it lets you choose what branch to base it off, whether its from the master etc...
but the github client is so shitty, i wonder what everyone else uses

**Comment by Crazylemon64** [comment]
@orelbon I use the command line version of git myself, both on Linux and Windows. On windows, I use "git bash", I think it is called. All your work vanishing is either a result of you not having all your work committed and stored before switching, or git keeping all your changes in your old branch; Does switching back to the old branch restore your work? Branches are stored in the .git folder, though not as directories that you can browse through. Doing something similar to "git checkout [branchname]" should let you get back to your original branches.

**Comment by Plotron** [comment]
Well, that's certainly going to make this place less 'private'.
Empower the sec pod pilot and EVA traitors! Yes!

+1, windows r fun.

**Comment by orelbon** [comment]
@Crazylemon64 I did commit all the changes to the previous brmanh before making the new one, can you explain how how work on multiple branches at the same time

**Comment by Crazylemon64** [comment]
@orelbon Are you able to switch to your old branch? Are you able to pull up a branching history of commits, corresponding to each branch? If so, can you click on one of the titles, to see if you can swap to that branch? I'm currently not able to switch to windows to test it out yet, but if it works, you should be able to change the branch you add your changes to.

**Comment by orelbon** [comment]
@Crazylemon64 yeah i can do all those things, but what i mean is that the files you edit for a branch don't get saved on my pc if you make a new branch, it does make the commit but it doesn't show the files on my hard drive

**Comment by Crazylemon64** [comment]
You mean they don't show up again if you switch back?

**Comment by orelbon** [comment]
the commits i made don't show up when i switch back to a different branch, yeah.

**Comment by Crazylemon64** [comment]
That's... weird. I'll try out the git desktop client and see if I can replicate that.

**Comment by ZomgPonies** [comment]
Conflicts.

**Comment by orelbon** [comment]
@tigercat2000 how do you resolve a merge conflict with the map .dmm file?

**Comment by tigercat2000** [comment]
not easily, it's almost always easier to just reset the branch and redo your work

**Comment by orelbon** [comment]
how do you reset the branch?

**Comment by orelbon** [comment]
welp i give up

**Pull request closed without merging**
