### PR TITLE
Autogibber, Gibber patches

### PR DESCRIPTION
**Pull request by tigercat2000**
This replaces the old autogibber with a spawnable version that is actually
an automatic gibber. This also fixes a few minor issues I did not notice
before with the gibber code. Namely, overlays getting messed up.

The autogibber is primarily intended for adminbooze things, and as such, is not on the map.

Autogibber stuff:

 - Has a set dir that links it to a turf 1 tile in that direction, autogibs any human that stands on that for 3 seconds or more. Warns the human first, with saying "FOOD DETECTED". So, entirely their fault.
 - qdel's any NODROP items, makes every other item on the human fly out in some direction, then gibs them
   - The items fly out 1 by 1 at a rate of roughly 10 per second, it is amazing to see it. I should make a gif at some point.

Other minor gibber stuff:
 - Gibs now fly out 1 at a time, about 10 per second. It's absolutely wonderful to watch.
 - Gibber keeps a log of all of it's victims, useful for admins to discover who exactly has used the gibber.
 - Fixed a minor bug that had potential to keep overlays around longer than they should stay

### CODE REVIEW

**Comment by Robertha89** [comment]
can you make a version that turns people into borgs? Or even set a var so what it turns the victims into can be changes via varedit? Would this be possible?

**Comment by Spacemanspark** [comment]
We already have that.

**Comment by tigercat2000** [comment]
@Robertha89 beyond scope of this PR, we have the robot fabricator, and yes I probably could make an admin machine to do that stuff

**Comment by Robertha89** [comment]
@tigercat2000 the robot fabricator is extremely limited due to cooldown, and state of the person going in. Thus having something more automatic and dangerous would be neato

**Pull request merged**
