### PR TITLE
Updates space catwalk sprite

### PR DESCRIPTION
**Pull request by DogsParadise**
This took way too much effort

## What Does This PR Do
Creates  a nicer looking catwalk sprite.
Perspective has been adjusted.
Colors have been adjusted to a more orang engineering, hazard colors of IRL are used.

## Why It's Good For The Game
In my opinion this is a better looking sprite than we currently have for catwalks.

## Images of changes
New catwalk:
image

Aseprite file:
image

In game:
image

image

image

Old sprite:
image

image

image

## Changelog
:cl:
tweak: Tweaks catwalk sprite
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
Maybe change the color / slight issues at corners. But that is something for tomorrow?

Kinda like the orange border but could also be my original yellow/NT colors?

**Comment by procdrone** [comment]
The old sprite looks better, IMO.

Also new sprite seems to bug out here and there.

**Comment by DogsParadise** [comment]
> The old sprite looks better, IMO.
> 
> Also new sprite seems to bug out here and there.

Mind telling me why you think so?

Is it due to color pallette? (which I think is the most likely cause)

Also where do you see the bugs, so i can go fix them.

Tbf, I think I pr'd this too early, probably gonna re-do this.

**Comment by shmabuu** [comment]
The catwalk looks nice, but it does look a tad out of place with the lattice sprites remaining the same. The colors not matching is a bit odd. But otherwise, nice catwalks 👍

**Comment by DogsParadise** [comment]
Needs adjustments, probably gonna resprite some more of out space before pr'ing this again.
Depends how long it takes.. we will see.

To do:
Change color palette
Change pattern to by symmetrical

CLOSED!  (that sounded cool)

**Pull request closed without merging**
