### PR TITLE
Possession Tweaks

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Minor fixes and tweaks to item possession.

 - Ghosts should retain the icon of the item after it dies now (Instead of being a ghost with no icon at all).
 - Possessed items now temporarily revert to their non-mob form when in containers or any other non-turf location.
 - Possessed items now get a few lines of explanatory text when the client first enters the mob.
 - Consolidated some redundant code into an update_icon proc.

Pardon the merge commits, can't be asked to fix them this early.

### CODE REVIEW

**Comment by Necaladun** [comment]
Is this rightclick->possess object or the click-drag possess?

**Comment by DaveTheHeadcrab** [comment]
Click-drag, the other kind never actually makes them a mob or anything.

**Comment by Necaladun** [comment]
sounds brilliant then, thanks

**Comment by tigercat2000** [comment]
oh dear god the spacing dave please

**Pull request merged**
