### PR TITLE
Brig Phys Can be Traitor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This change is likely to be more palatable than the alternative.

Brig Physician can now be a traitor.

Security has it a bit too easy when it comes to medical attention; they have a guaranteed go-to who can treat any wounds, throw them in cryo, do surgery on them, the works--and all without risk, as the brig phys can almost never be compromised.

One of the main gameplay aspects of medical is that just about everyone has to go to it to get help and entertain the risk of the doctor being a traitor or being a collaborator for one.

Brig Physician was never designed to be someone who treats security personnel; the position was meant for treating prisoners who got banged up by being apprehended.

What the job has become is sec's go-to fix-all, and this isn't particularly good for the flow of the game. This re-introduces some risk (in my opinion, still not enough) to Brig Phys so he's not automatically trusted as "safe".

:cl: Fox McCloud
tweak: Brig physician can now be a traitor and does not start with an implant
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
No thanks

**Comment by Tayyyyyyy** [comment]
This could make for some interesting prison breaks with assistance from the inside. Should there be a change to SoP so that the brig phys's role as security medic would be official?

Antag brig phys will also have round start access to a bunch of sec equipment (flashbang, box of flashbangs, hudglasses, stunbaton, handcuffs, etc), making antag brig phys pretty powerful and making sabotaging sec a lot easier. Maybe their access to this stuff should be removed?

**Comment by Rurik123** [comment]
Anything that makes specific roles less "safe" and not automatically trusted is good in my book. Perhaps this will also prevent brig phys being given a tazer at roundstart without a care in the world and them running around like impromptu officers.

**Comment by Spartan6** [comment]
The balance concerns on having a person start with security access in such a big thing, that I don’t think it’s worth it.

I’d rather us remove them altogether and scale down brigbay to be even more of an emergency treatment centre that security can use.

**Comment by Renaultius** [comment]
If Brig Physicians aren't going to be mindshielded anymore, they need to be treated way differently; at the moment, they are basically unofficial officers with different duties, like the Detective. After this pull, they'd need to have more restricted access, and basically be treated as what they are; a Medical Doctor who happens to work somewhere different than the Medbay.

+1, though; making Security a little less secure can have some novel and fun outcomes for antags that stick it out in the brig or perma.

**Comment by EldritchSigma** [comment]
New Meta: Fire brig Physician at roundstart. Treat Sec yourself.

**Comment by Citinited** [comment]
I think this change is good. I'm generally against the idea of security having their own doctor instead of going to medbay for bumps and scrapes. 

For people who are worried about brig physicians potentially being traitors and having unfettered access to security equipment, SOP is clear on what equipment the brig physician can and can't have, and their role in security. They are *not* meant to be officers (and shouldn't be allowed to carry most security equipment), and should they act in that way, it's well within an officer's right to confiscate said equipment.

**Comment by Regen1** [comment]
>No thanks

@DesolateG 👌 💯 feedback, I think your voice will absolutely be taken into consideration in this matter.

>New Meta: Fire brig Physician at roundstart. Treat Sec yourself.

@EldritchSigma And get the hammer for metagaming.
They're hired by NT, firing them because the code allows them to be traitors is just flat out gaming the system.

**Comment by Spacemanspark** [comment]
I read security officer at first and had a mini heart attack.
But brig physician? I'm willing to try it and see how it works.
:+1:

**Comment by davidchan13** [comment]
I feel this should be coupled with an access change to the BrigBay doors so you need medical to get in and use the machine, meaning unless HoS wants to put bandaids on Sec himself he can't just fire or chase out the BrigPhys so Warden and Sec can just make free use of his closet.

**Comment by Tayyyyyyy** [comment]
> For people who are worried about brig physicians potentially being traitors and having unfettered access to security equipment, SOP is clear on what equipment the brig physician can and can't have, and their role in security. They are not meant to be officers (and aren't allowed to carry most security equipment). Should they act in that way, it's well within an officer's right to confiscate said equipment and/or arrest the offending physician.

Most brig physicians I've seen don't abuse their access too much. That's not what I'm worried about. An antag brig phys isn't going to respect SoP. They can easily pocket flashbangs, stun batons, or an esword from evidence storage when nobody's looking. Brig phys doesn't need access to sec lockers and stuff anyways.

**Comment by Citinited** [comment]
@Tayyyyyyy The SOP enforcement is for officers / HoS. See the brig physician doing shady shit? Investigate him.

**Comment by Tayyyyyyy** [comment]
Except the only non-mindshielded person right now that can access the security equipment room is the HoP, and it's very conspicuous for a HoP to be visiting sec all the time to try to steal sec equipment, whereas it's much easier for the brig phys to do this stuff unnoticed. Obviously, even right now, a brig phys seen taking flashbangs and stun batons from sec equipment would be yelled at. I'm not concerned with that, I'm concerned with how easy it would be for antag brig phys to steal/sabotage sec equipment.

Why not remove access that the brig phys doesn't need anyways?

**Comment by Decemviri1** [comment]
I'm with Kyep on this. He summed up what I wanted to say but also the fact brig phys is a karma role makes it a pain to replace if the individual is a traitor. 

With most other roles, traitor Doctor or Engineer there's a whole department there who can fill in. If the brig doc is taken out of the round, suddenly you're left combing through people on the server, hoping someone has it unlocked, faxing it off to CC and going through all the hoops to get someone promoted to a Karma role. Brig Doc, at-least from my time on the server seems to be a reliable corner stone for security, suddenly this becoming a potential hostile actor could easily stress security more then intended.

**Comment by EldritchSigma** [comment]
Alot of access has to be removed then, including the access to the doors right before perma and solitary if sec werent to shoot EoCs on sight. If an engineer busts out perma inmates it involves work. If an HoP busts out perma inmates it involves work (and HoP outside of bridge and office is suspicous as fuck). If the AI and Paramedic bust out a perma inmate (only to get them gunned down shortly after) it involves work. If someone with intrinsic easy access to most of sec does that it involves no work whatsoever. Its frustrating at most. At worse it gives sec, being jaded for the most part on the more experienced people, another reason to just gun down people who are hostile instead of taking the risk of putting them into perma just for the physician to release them.

**Comment by Tayyyyyyy** [comment]
Now that @Kyep mentions it, I am wondering a little about what the end goal of this PR is. When security is robusted, are they recovering too quickly and easily?

If the problem is that the brig phys is neglecting their duties of treating prisoners and treating sec instead, I can see that maybe the unnamed "alternative" mentioned in the PR is removing the brig physician role altogether, and that this PR is sort of a middle ground. But this could have some unintended consequences, such as brig docs having more trouble doing their actual job because sec can't trust them to treat prisoners anymore. It's a tad bit problematic without adjustments because brig doc will be the only role without a mindshield that has access to perma.

There's also the perspective that security is tough enough as it is, and that the brig phys evolved into the security medic role because having your bones broken by an antag is harsh enough, and having someone reliable to fix you up isn't a bad idea. I can see the validity of this opinion as well, since most of the time, you only have a few instances of brigbay becoming mini-medbay (or even mini RnD in one particularly absurd instance). The rest of the time, for more advanced care, the brig doc usually takes the officer to medbay anyways.

**Comment by EldritchSigma** [comment]
While we are on the topic of security having it hard or not... If you have a decent team for once that is capable of beating a threat... immediatly a new one is created. Something you cannot beat for certain in 4 out of 5 cases (case 5 is abductors which is actually interesting to deal with). Have seen people start getting mechsuits after a cult has been beaten. That for "enjoyable events". If you need a mechsuit to "enjoy" an event it might not be a good event after all. Sec is getting punished for doing their jobs already. You can put it as you want, if its "to make the round more interesting" it still is received as punishingSsec for doing their job. This PR would make Sec even more frustrating than it is already. Now on top of neverending threats you get confronted with when doing your damn job you have the risk that one of the persons who are dealing with confirmed criminals by healing and treating them is a criminal themself.

Prison Doctors got more if not the most excessive screening in a prison for what they have to do and deal with. Hence I dont see how a Brig Physician could get hired by the syndicate... might aswell make all none sec roles elligable for antag at this point.

**Comment by Denthamos** [comment]
With the current access the Brig Phys has and their job overall I really do not see antag brig phys going well in the long run.  Even lore wise a brig phys would have more intensive screening than an officer due to them performing medical practices on prisoners in a high security area.

Its rare in the case that the brig medbay because a one stop treat all and it feels just removing the brig phys entirely would be a better change than making them a possible antag with as much sec access as the BP currently has.

**Comment by DesolateG** [comment]
Right, now that I have a proper keyboard to type on and not restricted by the badly limited Github mobile page.

Let's take a look lore wise. Why would NanoTrasen hire an unvetted, and un-mindshielded doctor to work in and have access to a highly restricted section of the station as the Brig? That just makes absolutely little sense. Sure you can argue that other heads have basic access to the Brig, but the Brig Physician actually works in there, and is a person that is expected by security to be in there. The HoP or CMO waltzing into security despite their basic access is going to turn heads of security, but not a traitor Brig Physician, who's workspace IS the Brig.

I highly doubt NT would just hire a random doctor with no solid credentials and a SECURITY RISK to operate in security.

While security might be able to handle a traitor doctor when it's fully staffed during a higher population, this PR would set up a traitor Brig Phys to be a super-traitor during lower server pop.

 Security during lower population is typically the very last position to be filled on the crew roster, because people don't want to handle the stress of being 1 or 2 people going up against 8-10 traitors, or slings, or whatever antag spawns for that round. It's stressful, not fun, and typically rage inducing to be security when you're literally outnumbered by the antags, who already have the advantage of being incognito amongst 40-70 other crew members.

Now add lower population lack of security staff and a traitor Brig Phys together; often times you'll see security department go for 10-15 minutes without anyone showing up for it. A round start Brig Phys traitor could raid the armory which is 2 emagged doors away from access for them. Then they could steal the Krav Maga gloves, steal the X-01, and have free reign in security, leaving any crew that shows up for that job already crippled by stolen equipment and not be any the wiser onto the fact that ONE OF THEIR OWN TRUSTED PEOPLE is probably going to kill them instead of having their backs, and was the one that raided the armory before they got there.

Finally, the argument that the Brig Phys is doing what Medbay should be doing: You can thank Brig Phys players for that, who go out themselves and order a surgery kit, and build their own surgery table, and stock their Brigbay with things they need to do full treatments like that.

As a person who frequents medbay doctor as well I can tell you that I see just as many Security crew into surgery and cloning as I do any other crew. So the argument that security never is susceptible to foul play from medbay is flawed as well.

Overall this is an unneeded and severe nerf to a department that already is disadvantaged, and could easily cripple them during lower population rounds. 

I'm strongly against this.. so once again @Regen1 

No thanks.

**Comment by Vivalas** [comment]
I main sec and ironically I almost never use brig phys and almost exclusively medical because in my experience brig phys is hard to find when I really need them. 

I support this because 1.) I never use brigdoc anyways and don't have too many issues in medbay and 2.) I personally wouldn't mind removing mindshields altogether and having security traitors.

Although honestly I think brigdoc is a bit more dangerous than medbay if subvertable. Medbay is a lot more public and almost always has at least 10 people in it at any one time, and brig can be pretty empty sometimes, and brigbay is kinda secluded.

**Comment by Renaultius** [comment]
Lore-wise, it checks out, honestly. Other non-mindshielded, traitor-able roles include the HoP (basically second-in-command with the ability to gain access to everywhere and give it to other traitors), RD (head of the research team, aka supposedly the reason the station exists at all, with barely-restricted access to the station's most sensitive places), CE (even less restricted access to the most sensitive places on the station), and CMO (well, he's command, I guess). If Nanotrasen was actually interested in securing the station properly, the Brig Physician would not be the priority recipient over Command roles.

Regardless, the comments have swayed me; I feel like Security doesn't need a knife in their back, especially during lowpop, when it's already a stressful and paranoid branch to work in as-is.

**Comment by Ty-Omaha** [comment]
Person A:"Hey brig phys can you patch me up?"
Brig Phys:"Sure"
\>knocks unconcious, puts in body bag, and cremates / spaces / hides/ does whatever
Person B:"Oh hey what happened to so and so?"
Brig Phys:"Dunno, they left a while ago"
Person C:"I bet it was the brig phys"
Brig Phys:"NO PROOF YOU CANT TOUCH ME"

or similarly - fingerprints on the body, but they're the brig physician so of course they're going to have prints and fibers on security. 
>Brig Physician was never designed to be someone who treats security personnel; the position was meant for treating prisoners who got banged up by being apprehended.

Should have been called a "Prisoner Physician" then.

Sec doesn't need an "insider" to sabotage them.

**Comment by Vivalas** [comment]
I would welcome the extra challenge but I can see how other players might not.

**Comment by StreakyHaddock** [comment]
You would be better off removing them. I love the brig physician playstyle, but ages ago when they were implemented, I was against it for the trusted medical professional angle. They must never be traitor because putting someone with access to all of security, who is EXPECTED to stay in security, access to traitor items or changeling/vampire/cultist/shadowling abilities is a horrible, horrible idea. It's already upsettingly common practice to never, ever hire from manifest for precisely this reason. Not to mention, security is NOT well equipped to handle a traitor from inside, at all.

**Comment by ZN23XZ** [comment]
Not sure if this has been mentioned yet. But currently brig docs have all the same access as sec officers. They can access the locker rooms and lockers, they can access all of the cells and perma. I think thier access would need to be reduced to balance this. An antag with access to the security locker room and the ability to release other antags from perma right from the start is a bit too powerful in my eyes.
Maybe reduce them to having similar access to IAA, just brig access, but they need someone from security to open cells for them and such. That way you wont have brig doctors looting the locker room and armory any time its open.

**Comment by Renaultius** [comment]
I do feel like the Brig Doctor has problems. A few possible solutions might be:
- Removing Brig Med and tacking the Brig Doc duties onto the Warden, giving them some excuse to stretch their legs for medical supplies and adding to their role as home base, since they can treat minor Sec injuries,
- Removing Brig Med and adding a Sec Medic role that has some Medical clearances and is authorized to carry doctor stuff, but is more or less an officer, not a doctor,
- Removing Brig Med entirely and just making Medical Doctors and Security Officers have to visit each other's departments once in awhile.

Er, not that this PR is meant to discuss removing the Brig Physician, though...

**Comment by davidchan13** [comment]
Or move Brig Med to medical department properly and have an office/infirmary located outside of the brig and basic security access so they can enter the brig but not open cells or lockers.

**Comment by tigercat2000** [comment]
I don't really agree with this PR;
 - While security having their own totally trustworthy medic may cause emergent design issues, it is not ideal to change them to being a potentially corruptible role.
 - The fact that they have significant amounts of security access is concerning to say the least.
 - This could be incredibly crippling if it occurs during a low-pop round.

**Comment by sothangel** [comment]
Totally in favour of this, I think it would be a good change.

**Comment by Vivalas** [comment]
I'll just remove my vote because reviewing this again I'm more on the fence. Unless it was reduced to a very low chance (which may or may not require weighting traitor distribution with respect to assigned job), I feel it would get annoying after a while, when you bring up the point of their access.

**Comment by EvadableMoxie** [comment]
Are there really problems being caused by the Brig Phys currently?  The Brig phys is treating sec that are already out of the fight. They aren't combat medics. They don't change the outcome of an encounter, all they do is get security back into the round.  With how difficult it is to get a well staffed security team as is, why is this even being considered?  

This won't have the outcome you all think it will. I think it's incredibly naive to think this change would mean sec keeps going to the Brig physician and sometimes the phys pulls antag shenanigans. More likely sec will simply stop going to the Brig for medical treatment. They already don't half the time simply because Medbay is closer.  The rest of the time, they can have another officer or the Warden treat them.  Or just have the warden watching, since the Warden most of the time has nothing better to do and no where else to be. 

This change is unnecessary at best and highly destructive to the role at worst,  I oppose it as vehemently as possible.

**Comment by DarkPyrolord** [comment]
I'm going to echo Tiger on this one myself.

Security does not need someone tearing it down from the inside, especially with the amount of access a phys has.

👎

**Comment by KasparoVy** [comment]
Relief!

**Pull request closed without merging**
