### PR TITLE
Virology and Science Maintenance Remap

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Remaps the current abomination that is Virology and adds in the much-requested science maintenance overhaul.

newviro
newviro2
hallway

Not only does this mean that Viro doesn't run out of power insanely qiuck, is no longer subject to repeated spacecarap attacks, keeps pesky non-virologists out of the lab, and doesn't takes up the same amount of space as a quarter of medbay...it sets the very important framework for continuing the maintenance remap (like what is seen near arrivals and north of library/chapel/botany). It also potentially means we can port and install the Gas Engine Turbine and hook it into atmos properly.

As for maintenance, there will be a few open spots here and there; in the future I plan on remapping portions of science; when this is done, it'll help make things appear more cohesive and more filled out; for now though, I'm quite happy with this--about the only thing I dislike is the Viro entry hall...but there's not much that can be done about that with current medbay; Bay medbay has always had an obnoxiously long hall/tunnel to virology module.

Related Map edits:
- returns Xenobio's deathsposals
- gets rid of the outlet to space in the last pen (as you're not really dumping into deep space anymore).

### CODE REVIEW

**Comment by Markolie** [comment]
I'm not too big of a fan. Virology definitely needs a remap, but the room between the lab and the airlock is completely empty, and the room with the test monkeys in it is also very barren. And, as you said, maintenance looks barren too. If we're making this change, it needs to be good from the get go.

**Comment by Spacemanspark** [comment]
I feel it looks a bit... bland.

**Comment by Earthdivine** [comment]
It also looks very cramped along with the bland, if there's anyone other then the Virologist in it, I get the feeling they will run into eachother often.

**Comment by Belario** [comment]
It's not perfect but it's a much better version than what we currently have.
Which is utterly fugly BTW and needs to be replaced ASAP.

**Comment by Fox-McCloud** [comment]
Alright, major update.

I tried to make Viro monkey pen look a bit nicer in addition to the hallway leading to viro---also added in some windows in surgery to look into spess.

Either case, people had been requesting of me to re-do science maintenance---so that's what I did; this is based on Boxstation's maintenance---and since both maintenance overhauls have proved incredibly popular, I figured I'd go ahead with this.

In the future (NOT in this PR, I'll be adding in the gas turbine and likely remapping portions of science--this will also help cut down on the empty space feeling around Xenobio).

**Comment by Dumbdumn5** [comment]
Know what we need? An entire map that's just maintenance with scattered departmental rooms. Maintstation best station. Still :+1: for the rework.

**Comment by Robertha89** [comment]
hmmm, this is much better, why not move the secure medbay storage with spacesuit thingy to the left of the viro hall, so the effing hallway is straight, and filled with chairs. 
Also, viro work space is still a bit small, you should be able to have space to work at 2 virus dishes at a time, and have the space for 2 crates at least.

I do like the wiring as it does something that is not done anywhere else on the station with two sabotage points to cut power too that part of the station.

**Comment by Fox-McCloud** [comment]
updated a bit more; re-adds the exam/isolation rooms that were removed; also helps cut down on the "ew empty rooms" feel.

**Comment by taukausanake** [comment]
@Dumbdumn5 What about a station that is still being constructed? Make it part of the crew's job to finish it up while doing their jobs.

[ontopic] I like this map edit. Gives the option to nuke Xenobiology whenever they finally infest the station with xenos :P

**Comment by tigercat2000** [comment]
a full render for your viewing pleasure
3 HOURS TO GET MAPRENDER TO WORK, TWO LINES OF FUCKING CODE IN THE END

**Comment by Dumbdumn5** [comment]
@taukausanake Well we did have a game mode called derelict a lon g while back that was that, and for the moment we've got construction station, though it's rarely ever used.

**Pull request merged**
