### PR TITLE
Reinforces Charlie and Theta Station

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
All external walls and windows, and the inner walls of the solar SMES and upper left transit tube area have been replaced with indestructible variants.

## Why It's Good For The Game
This stops explorers from cutting their way into Theta/Charlie and stealing stuff intended for the Charlie Station crew.

## Testing
Spawned with ruins, verified that ruin was not screwed up. Tried to disassemble walls. Couldn't. Proceeded to do a solo Theta run.

## Changelog
:cl:
tweak: Theta station now has vastly improved explorer resistance.
/:cl:

### CODE REVIEW

**Comment by warriorstar-orion** [comment]
This makes an overheated superpacman effectively a non-issue. It's much easier to refloor a 3x3 area than it is to deal with a blowout explosion:

2024_05_14__10_47_47__Paradise Station 13

There's also still several ways to get in, you can get in via the hivebot ship:

2024_05_14__11_04_53__Paradise Station 13

You can take the Beta Station access tube and destroy the poddoor:

2024_05_14__11_10_51__Paradise Station 13

You can rebuild the upper Theta Station access tube network towards the left or right:

2024_05_14__11_07_51__Paradise Station 13

I think we should be avoiding adding indestructible walls in player areas if we don't absolutely have to or trying to play whack-a-mole trying to prevent all the ways this can happen.

**Comment by warriorstar-orion** [comment]
@Fordoxia okay, some thoughts on how we can make some changes here that integrate into the game world.

We do have items on theta that are already indestructible: the spawner cryopods themselves. So let's take advantage of that and use them to reduce the ways explorers can take advantage of theta.

1. We don't want them taking the easily accessible weapons i.e. the laser guns. So we spawn them in the security officer's backpack.
2. We don't want them taking the R&D equipment. So we ID lock all of it to the Theta cards, and make an additional PR that preserves ID locks on boards even if they're from a disassembled machine. This is just a good idea in general.
3. We don't want them taking the prototypes. This I agree we should definitely lock down. We have indestructible pod doors we can use for this purpose, so we're isolating the amount of stuff that can't be destroyed. Have the APC/door opener in that room keyed to the engineer's ID. It's kind of silly in general that NT stored the prototypes near an easily breakable window so we'll move some things around.
4. We don't want them taking all the chems, so we put them in an ID-locked, indestructible chem fridge.

Obviously if we're splitting these important items among the cryopod inhabitants, we have an issue where a scientist might spawn and not have access to the laser guns, etc. There's some ways we could go about this:

1. We give thetans the ability to retrieve items from each other's pods.
2. We create an indestructible cryo oversight console like the one in station cryodorms, and key it to their IDs.
3. (kind of my favorite) That's just the way it is, so we allow players to choose which role they spawn in, and players are incentivized to work in groups to fully take advantage of the station, instead of one person just speedrunning the whole things, so some RP can be encouraged. But that's just my own wacky idea that most people probably wouldn't like.

The goal here is to minimize the amount of stuff we're locking down behind indestructible walls. Using the spawners themselves, ID-locked machines, and a few indestructible objects to store items important to using the station is a better tradeoff, I think, than trying to lock down the station.

**Comment by Fordoxia** [comment]
> @Fordoxia okay, some thoughts on how we can make some changes here that integrate into the game world.
> `snip`

True. The use of indestructible walls was mostly just following how the USSP station is handled, but I can see about doing it differently.

As far as I know, none of the Charlie crew actually spawn with a backpack. Restricting the laser guns to the secoff would also make them the meta because you kind of need the lasers to clear out Theta. Plus if no one else spawns in you're kind of boned, which wouldn't be fun at all.

The prototypes are generally stolen by just cutting through the hull and completely bypassing the blast doors. Diamond drills and sonic jackhammers can completely remove an Rwall in a matter of seconds, and even a basic toolbelt can let you get the good stuff in under 3 minutes.

**Comment by warriorstar-orion** [comment]
Sorry, completely forgot about this. I'll make sure I'll give this another look by the end of the week. My opinion on indestructible walls keeps changing as I keep working on my own ruins.

**Comment by FunnyMan3595** [comment]
A few indestructable walls around the major loot would be fine, but this is way overkill.

**Comment by Fordoxia** [comment]
> A few indestructable walls around the major loot would be fine, but this is way overkill.

_Looks at the USSP station..._

**Comment by FunnyMan3595** [comment]
The big difference is that USSP isn't _inhabited by players_. Indestructible walls don't discriminate between explorers and Theta denizens.

**Comment by Fordoxia** [comment]
> The big difference is that USSP isn't _inhabited by players_. Indestructible walls don't discriminate between explorers and Theta denizens.

The theta inhabitants have zero reason to start tearing holes in the outer hull of the station.

**Comment by FunnyMan3595** [comment]
> The theta inhabitants have zero reason to start tearing holes in the outer hull of the station.

There's a mechfab in Theta. How are they going to get a mech out without any way to open a hole in their hull?

**Comment by warriorstar-orion** [comment]
It looks like you've added more indestructible walls, this time to the hivebot ship?

I maintain my objection to so much use of indestructible walls on player-inhabited ruin. On PvE ruins with high value loot it makes sense to prevent cheesing to get to the reward, but not here. There are still many ways to ingress and it prevents players from renovation (as just one example, I typically tear out the southern transit tube and replace it with a hallway).

I'd prefer looking into more surgical solutions to prohibit explorers from taking high-value loot, even if it involves some remapping. Perhaps pull all the prototypes into the center of the science area and ID-lock them behind pod doors, and ID-lock the R&D equipment. ID-locking isn't fool-proof but neither is locking your front door. Isolating the weapons, chargers, and armor behind a smaller indestructible area with proper door access would be a good step, too.

Putting the weapons and armor into an access-restricted cryogenic oversight console may actually be foolproof since they're actually indestructible.

**Comment by asciodev** [comment]
Frankly, there are brave interpretations of Rule 0 that cover this kind of behavior without the need for a code or mapping solution.

**Pull request closed without merging**
