### PR TITLE
Makes tranquilizer darts actually useful.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
As per title. The tranq darts for the shotty you can find in the armory now have:

- 5u of mutadone, for dealing with those pesky hulks
- 5u of haloperidol for dealing with those geniuses that injected a marijuana (it removes pretty much all combat stims and drugs from the person's system)

:cl: FlattestGuitar
tweak: The tranquilizer darts now have an updated mix of chemicals inside. Contact your assigned Warden for more information.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Does security really need a "do everything in one dart" round of ammunition? I could understand haloperidol rounds *and* separate mutadone rounds, but this is literally a catch all for anyone who's difficult to deal with---and it knocks them out to boot.

It would seem better to add mutadone darts, specifically as a separate item.

**Comment by FlattestGuitar** [comment]
It's not *really* a do-everything dart. It's only useful against people with mutations or stimulants and the ether doesn't kick in after over a minute after the first shot connects.

Hitting someone with a single round like this in combat is hard enough, I'd say.

**Comment by Spacemanspark** [comment]
Nobody uses tranq darts anyways, buckshot, beanbags, or a combination thereof is generally more than enough. Maybe they'll see more use now.

**Comment by uraniummeltdown** [comment]
The Ether is way too powerful, even 15u of Ether knocks you out for several minutes (sleeping so you can't do anything).

**Comment by FlattestGuitar** [comment]
Alright, I'm assuming the numbers in #6085 may still be tweaked, but with the current ones the 20u of ether will put you to sleep only after 72 seconds (which point won't even be reached if you're not sated enough) and then make you sleep for at most 53 seconds, assuming you have the maximal "boost" from being full.

Right now it will only put you to sleep for 14 seconds after the 72 seconds, since the current reagent system doesn't change how quickly chemicals are processed.

Again, I think shooting someone with a shotty is hard enough. If you're the reason security had to bring these out, you should prepare accordingly or face getting rekt.

**Comment by Fox-McCloud** [comment]
@FlattestGuitar 

Keep in mind the other effects of haloperidol and ether. Halo has a 50% chance of inducing 2 cycles of drowsiness every cycle. Drowsiness not only *dramatically* slows the person down, but has a chance of causing them to fall asleep for 5 cycles.

**Comment by Crazylemon64** [comment]
Haloperi seems like it would make the tranq dart have enough bite to make it useful in the short term.

I'm eh on the mutadone myself

**Comment by Rumiluntti** [comment]
Yeah, give security a solution to the only counter against instastun tasers.

**Comment by Doukhan** [comment]
The ether/other chem is good, too many marijuanas going around.
Don't think it should have the mutadone in it though, rampaging geneticists are a thing and do happen occasionally but it shouldn't be as easy as grabbing a the all-in-one shotty, should be something sec need help from sci/med for.

**Comment by Fox-McCloud** [comment]
I'd just split it into two, to be honest.

**Comment by scrubmcnoob** [comment]
Can't security just grab buckshot and gat a raging hulk geneticist if they so desired? Tranq darts should be short in supply but at least give sec an option for non lethal force, without bugging medical for some mutadone, to deal with a raging hulk. Of course, they will need to land all their shots in the first place.

**Comment by FlattestGuitar** [comment]
Considering the sheer amount of non-lethal options security has available, I really don't think making tranquilizer darts ANOTHER alternative to the already not used rubber shot and beanbags would be silly.

I've wiped the ether from them, as it wasn't really impactful short-term. Right now the darts are a perfect option for stopping pretty much every chemistry- or genetics-related threat security can encounter.

I still severely doubt they will get much use, but maybe someone out there will scream "we have a hulk, get the tranqs!" instead of just beating their face in with batons or shooting with lasers.

**Comment by Fox-McCloud** [comment]
going to split the mutadone darts off separately orrrr?

**Comment by Fox-McCloud** [comment]
Been mentioned multiple times to split this up, both here and on the Discord--nothing has changed on this PR though; going to close this.

**Pull request closed without merging**
