### PR TITLE
Secure armory

### PR DESCRIPTION
**Pull request by orelbon**
Adds Blast doors, making for easy access, also gives the racks windoors so the armory doesn't all vent when there's a breach.

ok here's my reasons why this is a good idea; 1. the warden is not forced to open the shutters, if he wants to distribute weapons by hands it's his prerogative, this also makes it easier for the warden if he doesn't want to distribute everything by hand, and so he won't have to get a locker and pack it with things because he can't carry all the thing needed in the armory 2. it gives the security officers easy access in case the warden, HoS, etc.. are not available, so the Ai just needs to press a button 3. security officers have no reason to take more than they need, i dont see security officers taking more than they need when i put all the riots suits, masks, and guns on the tiny table in the warden's office, also the warden or HoS can monitor them if they feel it necessary.
**Not Finished, Still a work in progress** 
@SamCroswell Thanks for the suggestions

Im open to suggestions on what to put in the hallway between the warden and the armory.

new armory

### CODE REVIEW

**Comment by KasparoVy** [comment]
Looks much better and sneaking is still valid, :+1:

**Comment by NTSAM** [comment]
It looks cute.
The architecture cute.
The nicely-fit-in room kinda cute.

**Comment by orelbon** [comment]
ughh idk what happened but the github desktop app won't acknowledge that the "updates" commit is synced

**Comment by Tastyfish** [comment]
Did you run mapmerge on this? That's a lot of + and -'s.

**Comment by orelbon** [comment]
@Tastyfish i forgot to run it on the "updates" commit but the github app is shitting itself i cant revert it and i cant get it to sync

**Comment by orelbon** [comment]
fuck it im making a new PR

**Pull request closed without merging**
