### PR TITLE
Gambling never pay

### PR DESCRIPTION
**Pull request by Anasari**
Make it impossible, on average, to earn money from playing slot machine. Just like real gambling, the house always win.

The odd divisor (Whatever the term is) changed to 20,000 from 1,350.

The bet amount changed to 100 from 10. 

(Assuming I got the math correctly)
Before: 

After: 

:cl:Ansari
Slot machine no longer earn you money on average. Like real gambling.
:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I mean I guess that's fine and all, but it's not like money is even used for anything. Like, _literally anything_. And even if it was I wouldn't make it completely impossible to win big. Just really cut the chances down so someone doesn't win 1 million space bucks three times in a shift. Maybe once every three shifts?

**Comment by Anasari** [comment]
Money is going to take a lot of rework / new feature to make them useful. 

But removing the biggest, most obvious money printer in game will serve as a useful first step in my opinion.

**Comment by FalseIncarnate** [comment]
Another idea would be to implement an internal pot for the machine, so you can't win more than is in the pot at any given time. You could make this a shared pool between all machines (a global datum/var) that also grows over time, write it off as a "universal" pot pulling from slot machines on other stations/planets that is siphoning money from suckers off-station to fulfill winnings at any linked machine.

This could work by each bet adding to the pot and each win subtracting the reward from the pot, plus a regular addition to the pot of a set/random amount of bets. You could even do some dastardly odds manipulation so big wins are less likely with smaller pots, or even make wins impossible while the pot is negative if it gets overdrawn by a spectacular win.

**Comment by Vivalas** [comment]
I do have a big economy rework outlined somewhere and there wasn't much opposition from those who reviewed it, not sure what the rest would think though.

**Comment by KasparoVy** [comment]
It's not how many people you impress, but impressing the right ones :thinking:

I agree with this, personally

**Comment by Crazylemon64** [comment]
LGTM

**Comment by KasparoVy** [comment]
very nice

**Comment by Ty-Omaha** [comment]
Everyone will just ignore slot machines now, might as well have removed them

This should have been done in a money overhaul not on it's own

**Comment by Tayyyyyyy** [comment]
> Everyone will just ignore slot machines now, might as well have removed them

> This should have been done in a money overhaul not on it's own

In real life, slot machines also have a negative expected value. But tons of people still play them. Casinos all favor the house, or they wouldn't still be in business. You can still get lucky and win. It's just not a money printer anymore.

**Comment by Ty-Omaha** [comment]
right but this is not real life

**Comment by Tayyyyyyy** [comment]
> right but this is not real life

So what? All I'm saying is that gambling is still a thing even though people know it's irrational to gamble. The whole point of buying a lottery ticket is that you know you're probably just going to lose money, but the slight chance that you'll be set for life makes it worth it.

Also, in real life, your money actually kind of matters. In space station 13, not so much. So given the existence of casinos in real life, I would argue that people would be even more willing to gamble in a game where there's no consequences to losing money.

**Comment by Ty-Omaha** [comment]
If someone wants to be a trader and buy a bunch of stuff from the "misc" vendor they won't have enough money to buy a lot of things.

Or, if someone wanted a Synthesizer or any other thing but didn't have enough money for it they are essentially screwed unless someone gives them their money, since they can't go to the slot machine to get more.

If money doesn't really matter in space station, what is the point of making gambling realistic? 
What exactly does it achieve on it's own?

**Comment by Fox-McCloud** [comment]
>Also, in real life, your money actually kind of matters. In space station 13, not so much. So given the existence of casinos in real life, I would argue that people would be even more willing to gamble in a game where there's no consequences to losing money.

To what end? There's hardly anything worth spending your money on.

The increase in play cost by 10x, and the fact you will lose more often than not means it won't really be ever worth it to engage in it other than to waste time. Especially given that you typically start with 800-1200 dollars at round start.

It serves no functional purpose, anymore, other than wasting someone's time, now.

**Pull request merged**
