### PR TITLE
Gives the L.W.A.P in-hand sprites; Some tweaks to the gun, and the "toggle scope" action button

### PR DESCRIPTION
**Pull request by SteelSlayer**
## What Does This PR Do
Sprites by @Qwertyotoforty 
Making this PR at the request of Qwerty. The CL and sections below cover what is changed.

## Why It's Good For The Game
Fixes a bug. Gives in-hand sprites to a gun which actually had ***no*** in-hand sprites. Brings the gun in line with the other sniper rifle (the syndicate sniper).

## Images of changes
(This is just a small sample, see all of the sprites in the checks page)

GIF

# Changelog
:cl: SteelSlayer, Qwertytoforty
tweak: The L.W.A.P sniper rifle now requires your offhand to be free in order to fire, similar to the syndicate ballistic sniper or SAW
imageadd: Gives the L.W.A.P sniper rifle in-hand sprites
fix: The "toggle scope" ability for snipers and other guns is now only granted to you if you are wielding the gun in your hands. No more looking through its scope while its on your back.
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
I dont know what this means but travis is failing. I guess I'll give it some time and close/re-open.
`The command "sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"" failed and exited with 1 during .`

**Comment by AffectedArc07** [comment]
What in the name of fuck
image

**Comment by Qwertytoforty** [comment]
travis pls

**Comment by SteelSlayer** [comment]
Travis has been shitting the bed recently.

**Pull request merged**
