### PR TITLE
Renames Ice Peppers to Chilly Peppers

### PR DESCRIPTION
**Pull request by Jountax**
As the name suggests this is a simple name edit changing Ice Peppers, the mutant strain of Chili Peppers, to Chilly Peppers. The pun potential was here the whole time, staring at us, and I could bear it no longer.

**Changelog:**
:cl: Jountax
tweak: Renamed Ice Peppers to Chilly Peppers.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
priority:0 gamebreaking balance fix

**Comment by alex-gh** [comment]
Could you squash your commits? Just to make the commit history a bit cleaner.

**Comment by KasparoVy** [comment]
Can you even squash in the web editor? Those commit names

**Comment by alex-gh** [comment]
Oh, I missed that it was made using the web editor.
Guess it is up to the maintaner: https://blog.github.com/2016-04-01-squash-your-commits/

**Comment by Jountax** [comment]
I have the desktop thing but have never used it. Let me see if I can figure out how to do that.

**Comment by variableundefined** [comment]
24 hours. I like it.

**Comment by Jountax** [comment]
Yeah every command I look up to do this just gives me an error and one source said that squashing commits after sharing them could cause conflicts anyway so I'm a bit at a loss here.

**Comment by alex-gh** [comment]
If you are on discord and if you want to I can show you how to do it.
It is not hugely important in the case of this PR, but it is a useful skill to have.

**Comment by variableundefined** [comment]
I'll merge this in. Go on discord and seek instructions on how to set up git properly though.

**Pull request merged**
