### PR TITLE
Makes Jays old fluff tail public

### PR DESCRIPTION
**Pull request by Aurorablade**
On request from jay, makes jays old fluff of a tail open for public use by Tanagerines.

he just kept forgetting to ask someone to do it when he got his new one

:cl: Fethas
tweak: Public Wiggler Tail
/ :cl:

### CODE REVIEW

**Comment by SigholtStarsong** [comment]
Piiictuuuuures.

**Comment by Aurorablade** [comment]
its in the orignal pr for it https://github.com/ParadiseSS13/Paradise/pull/4983

**Comment by Jaywings** [comment]
sob

**Comment by taukausanake** [comment]
@Jaywings don't be sad, it's a nice tail. You're sharing it with the world now! Everyone can be more of a special snowflake thanks to you

**Comment by Spacemanspark** [comment]
Jokes on you Kei already has it

**Comment by KasparoVy** [comment]
I've been curious about the bootleg Wingler, now I understand. You've been stealing his tail!

**Comment by Spacemanspark** [comment]
Kei was around a long ass time before Jay was

**Pull request merged**
