### PR TITLE
[WIP] Chat tabs (and chat refactor)

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
I wanted to make chat tabs, but existing goonchat code was a nightmare so I rewrote goonchat in Vue.js. Before you panic:
- Setup and build is really easy (npm install and npm run build)
- Much less js than old goon chat (less than 100kb not counting twemoji and the emoji annotations, in comparison to over 300kb of javascript before).
- Fewer lines of code: 1134 total, including javascript and html templates, and tab code. Compared to 1194 lines of html and js in jquery goonchat
- Very few dependencies, and the dependencies I did pick didn't have any dependencies of their own (besides vue)
- No jquery
- Should perform better [See performance profile below in comments]
- 100% backwards compatible, so it's easy to make this opt in/opt out (probs a good idea to make this opt in at first), just by sending a different html (I try to have it fall back to old chat in cases of IE8 right now, but I haven't tested if that works since I don't have IE8 on hand)

Anyways, all the previous functionality is ported, I think, except highlighting (does anybody even use this feature?). I also removed a bunch of code that wasn't doing anything.

Filters are the new tab system! There are 8 categories right now: asay, msay, dsay, pm, logs, ooc, radios, other. Each tab can have its own set of filters. Here's a demo gif of what a use case might look like:

demo_fast

This is mostly for admins to try to divide up the clutter of chat. I would say non admins could use it to filter out ooc but it looks like that's going away anyways. Observers could split up dsay and IC, I guess.

Oh and the tabs are optional, if you only have one tab, the tab bar disappears.

Stuff that still needs to be done:
- [ ] Disable most filters for non-admins
- [ ] Fix scrolling issues introduced by tabs
- [ ] Middle click to close tab
- [ ] Unread count? Not sure if that would be too annoying, maybe toggleable unread count
- [ ] Tab configuration saveable via cookie
- [ ] Some preferences still need to be saveable via cookie (hide spam)
- [x] Performance profiling/testing. This probably uses more memory and I want to make sure it can handle a lot of chat
- [ ] Highlighting (please tell me nobody uses this feature)
- [ ] Toasts, maybe?
- [ ] Keyboard shortcuts for tab stuff? Could be useful maybe but it's tricky to find shortcuts that don't clash with macros

I will add more stuff as I think of it...Anyways would love feedback since I'm just guessing what would be useful right now!

### CODE REVIEW

**Comment by tigercat2000** [comment]
I am so not okay with using libraries like Vue or React.js for any of our UIs.

**Comment by Tayyyyyyy** [comment]
nano is way worse! It still uses bower 😡

Vue is fast and less complex than react so I picked it... And if you prefer jquery chat it's still there. I just feel like sticking to late 2000s web technologies is really limiting.

**Comment by tigercat2000** [comment]
Yeah, no, still. New-age HTML templating engines are *way* overcomplicated for the UIs we use. If you can't read the damn "html" files without learning an entire new language, they're too complicated.

**Comment by Ty-Omaha** [comment]
Are the PMs all the PMs that are being sent, or just the ones **you** are sending/receiving?

**Comment by Tayyyyyyy** [comment]
I hadn't used Vue before this PR and imo it seems pretty close to normal html. It's a far cry from the complexity of jsx. There's no new language involved, it's just xml and js.

I'd argue that the spaghetti code of jqeury goon chat is even harder to read. There are literally multiple areas with massive components hardcoded as strings.

**Comment by Tayyyyyyy** [comment]
The PMs are all PM conversation, so you don't lose the thread of conversation in the midst of chat log spam

**Comment by Ty-Omaha** [comment]
When you get PM'd it should flash the tab title box in red, to get your attention; instead of the light blue dot. and people should have to always have PMs enabled in at least 1 of the tabs

**Comment by Tayyyyyyy** [comment]
That's a good idea! First, non-admins won't be able to hide PMs at all (that filter will be disabled).

As for flashing, I think it might be a good idea to enable flashing for tabs that you want to be high priority. And maybe an unread message count for certain tabs too. That unread dot is definitely just the bare minimum...

I was also thinking about adding a toast at the bottom for when a new PM has been received on a non-visible screen, and then you could maybe click on it to go to the PMs.

**Comment by Decemviri1** [comment]
Admittedly my knowledge of technical side of this is limited but tabs for comm heavy roles (Captain, AI etc) would prove invaluable if you could seperate off the various channels.

**Comment by RyanSmake** [comment]
Highlighting is absolutely needed when you play something chat intensive, like AI or as a good captain turning with all channels on.

**Comment by Aurorablade** [comment]
While i appreciate your work into it, I am gonna have to echo tiger on useing external librarys, regardless of some people heres coding background we shouldn't have to force people to try to learn ANOTHER language, byond and DM is hard enough to keep right as it is. I am just a bit iffy on this.

**Comment by KasparoVy** [comment]
Regardless of whether we merge it, finish this so other servers can get it and we can backport it. :wink:

**Comment by Tayyyyyyy** [comment]
@Decemviri1 yup! That's totally possible though I'd have to probably add a submenu for radios to avoid polluting the menu with 1000 filters.

@RyanSmake thanks for the feedback, guess there's at least one user of highlighting out there 😒

@Aurorablade I definitely considered the maintainability issue when I was deciding whether or not to continue using jquery or do the refactor. I went for the rewrite because the current goonchat implementation is a messy 1000 line long function written in IE8 compatible pre-2005 javascript. This moves chat into ES2015+ javascript which is miles easier to use, adds linting to help support maintainability, and vue itself is easy to pick up and a useful, real world skill. jquery goonchat, on the other hand, will force you to spend hours trying to understand it (trust me, I had to go through every single line of goonchat to convert everything), and you'll pick up nothing in the long run besides maybe ptsd from the spaghetti.

React is almost 7 years old at this point. Declarative programming isn't just a fad, it's what the UI world has moved onto. Google just released [flutter](https://flutter.io/) which is a declarative way of writing android apps. Staying in the 2009 era of web programming is worse for maintainability in the future.

@KasparoVy Thanks, will do 🙂 yep, the duplicate squashing is in! Same animation and everything, but it's slightly faster because it doesn't append to the DOM every time it activates.

**Comment by Tayyyyyyy** [comment]
@Ty-Omaha you were right about the "to" side of PMs not showing up. It shows up now:

capture

**Comment by Tayyyyyyy** [comment]
Did some performance testing. Sent 1000 messages of varying classes:

# jquery goonchat
jquery_chat
Duration: 2880ms

# vue goonchat
vue_chat
Duration: 2631ms

The vue version wins out by over 200ms, and has less recalculate style (pink, expensive) events, and no repaint events at all (green, very expensive)

If we changed `to_chat` to send a plain text string along with a list of classes, instead of raw html, performance could probably be improved even more (all that yellow is html parsing).

**Comment by taukausanake** [comment]
How is this going to affect saving chatlogs? That's the most important feature I think is needed. Filtering them out would be great so you don't have to format them anymore, I think the best case for this however is saving separate files of chat that you have for each tab. Not sure how possible that would be but would be best case

**Comment by Tayyyyyyy** [comment]
> How is this going to affect saving chatlogs? That's the most important feature I think is needed. Filtering them out would be great so you don't have to format them anymore, I think the best case for this however is saving separate files of chat that you have for each tab. Not sure how possible that would be but would be best case

I ported chatlog saving before I implemented tabs, but how it should work right now is that saving the log will save the current tab you have selected (I'll try to make sure this is the case when I have more time). 

@IK3I can probs point out if I accidentally broke anything. I know there was also something he wanted to do that wasn't possible in IE8 that should be doable in this version.

**Comment by matt81093** [comment]
Personally, I like how it looks visually, and the ability to separate out chat tabs is something I've thought about more than once. Looking at the changes itself.. The code looks similar to existing languages and altogether, not that hard to pick up on. 

Regardless, I look forward to seeing this finished.

**Comment by tigercat2000** [comment]
I absolutely love everything visually about this, and all of the new features it provides. However, using newer web libraries like Vue.js is a significant hazard to both the maintainability and ease of modification-- not only do dependencies need to be kept up to date to avoid security hazards and incompatibility, but this adds yet another layer to debug if anyone has any issues with the embedded IE window. The advantage of using jQuery is that it's a rather simplistic library, and even as messy as the code gets, it's still not very difficult to debug and trace through. As such, we're just gonna have to bear with it for now, until someone can write a better UI system that doesn't use this kind of fragile complex newer library.

**Pull request closed without merging**
