### PR TITLE
Insane Atmos Buff

### PR DESCRIPTION
**Pull request by SchrodingersWolf**
## What Does This PR Do
Massively buffs Atmospherics roundstart by changing their APCs to be of the 'Important' subtype, which has 10000 charge compared to 2500 charge.

## Why It's Good For The Game
~~CRUNCH told me to do it or I would get borged, help~~
Atmospherics tend to run out of power roundstart while Engineering is still setting up the Engine and other power sources - Given that Atmospherics is quite important to SM and Turbine setup, more roundstart power would allow Engineering more time.

## Testing
I'll test it once I get home

## Changelog
:cl:
tweak: Atmospherics APCs on all maps now have more charge roundstart
/:cl:

### CODE REVIEW

**Comment by ArcticValor** [comment]
Honestly, this makes sense as of course, engi would make their department better suited for power outages as they are the ones in charge of it.

**Comment by Fordoxia** [comment]
> Honestly, this makes sense as of course, engi would make their department better suited for power outages as they are the ones in charge of it.



> Honestly, this makes sense as of course, engi would make their department better suited for power outages as they are the ones in charge of it.

Plus it's life support. It's kind of important.

**Comment by SchrodingersWolf** [comment]
> What's with that APC on boxstation? image

Good catch - I blame FastDMM

**Comment by SchrodingersWolf** [comment]
I don't want to manually resolve merge conflicts for this easy PR. I'll open a new one.

**Pull request closed without merging**
