### PR TITLE
Ports one of AA's PRs from TG

### PR DESCRIPTION
**Pull request by Sinestia**
## What Does This PR Do
Adds stockings as sock options.
https://github.com/tgstation/tgstation/pull/44274

(black stockings r absent because tg removed them for being similar to other pairs and this server also has v. . similar black stripe socks)

This was requested by pernicious individuals who shall not be named

## Why It's Good For The Game
Paradise has suffered from a lack of coders from what I've been told, this might get people into the mood to download a copy of vim and get crackin'

More character customization too!
## Images of changes
aaa

## Changelog
:cl:AffectedArc07, port by Froststahr
add: Stockings are now available in character preferences as socks. 
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I refuse to approve my own PR

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
You did a phantom diff
image

**Comment by Sinestia** [comment]
I dont even know how that happens with icons, but copy paste always exists

**Comment by farie82** [comment]
I am missing the feature where this is given to all maints and PR reviewers by default when they join

**Review by S34NW — APPROVED** [review]

**Comment by SabreML** [comment]
https://www.amazon.co.uk/programming-socks/s?k=programming+socks

**Comment by S34NW** [comment]
Not sure the CL should have `AffectedArc07, port from Froststahr`

**Comment by Sinestia** [comment]
> 
> 
> Not sure the CL should have `AffectedArc07, port from Froststahr`

I'm not sure what convention is, can put whatever

**Comment by S34NW** [comment]
> 
> 
> > Not sure the CL should have `AffectedArc07, port from Froststahr`
> 
> I'm not sure what convention is, can put whatever

Sorry, I just deleted this because it occurred to me that it is allowed, we just don't see it often!

**Comment by Sinestia** [comment]
> 
> 
> > > Not sure the CL should have `AffectedArc07, port from Froststahr`
> > 
> > 
> > I'm not sure what convention is, can put whatever
> 
> Sorry, I just deleted this because it occurred to me that it is allowed, we just don't see it often!

Ah, no prob. I just do it to try to give credit while also leaving something useful for people who want to discord ping and tell at me since my github name is diff. 

Looking at other PRs it does seem unusual :P

**Comment by Wojz** [comment]
are you trying to get more coders to play here

**Review by dearmochi — APPROVED** [review]

**Comment by AffectedArc07** [comment]
> AffectedArc07, port from Froststahr

`port by Froststahr` makes more sense here.

**Review by Dumbdumn5 — APPROVED** [review]
God I fucking hate it. 👍

**Comment by PacifistDalek** [comment]
Now we just need trans flag stockings

**Comment by Fox-McCloud** [comment]
Perhaps the worst PR I've ever merged.

**Comment by Sinestia** [comment]
> 
> 
> Perhaps the worst PR I've ever merged.

dont lie
i saved para

**Pull request merged**
