### PR TITLE
Remaps CC, changes z1 layout

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR does a few things, the main goal is remapping CC to appear more "lived-in" and hospitable for both ERT stuff and EORG. Every bit of immersion helps and our current CC is superbly barren.

~~This PR also tweaks when supply shuttles sell their goods, allowing admins to load supplies onto the cargo shuttle to send to station (as opposed to waiting until it was in transit).~~

The PR touches the solgov trader dock layout.

The PR disables dynamic lighting in: Syndie base alongside ninja and wizard dens. These areas did not need all the lights processing in them for no reason.

The PR reorganises where stuff is on the CC Z-level. (z1)

The PR makes some adjustments to how jungle flora is displayed in-editor.

The PR fixes no-creep grass being offset by 9 pixels.

The PR touches on CC door opacity and makes a new glass subtype.

The PR adds emag-proof multi tile blast doors (pod doors) and emag-proof door buttons.
_**(One of you little cretins managed to somehow get onto CC and helped yourselves to the ERT additional equipment and Gamma armoury, this is your fault)**_

## Why It's Good For The Game

I've always been of the belief that spaces should be designed well no matter how infrequently or briefly they are used. This applies to both the ERT and EORG areas on CC. They help contribute to the mindset of those who use these spaces and contribute to a better game atmosphere. All for no extra upkeep and performance. In addition, it reflects well on us as a codebase from a map-design standpoint. I want to be proud of our maps, not ashamed.

An issue with the previous remap attempt was superfluous areas, and the escape pod occupants being thrown right into the EORG, this remap attempts to tweak that by removing those superfluous areas and adding "one-way" doors to where the pods dock, so that occupants can choose if they want to move to the main EORG area or not.

The CC Z-level was a bit of a mess, so I've collected all the transit areas to one section and grouped the other structures together with enough gap so they can't be seen from each other.

## Images of changes
New CC:
image

New Solgov dock:
image

For more general Z1 layout changes, please see mapdiffbot. There are extensive changes, too many to document individually here.

## Changelog
:cl:
tweak: Remapped CC
tweak: z1 layout updated and reshuffled
fix: Fixed no-creep grass being offset
add: emag proof multi-tile blast doors
add: emag proof door control buttons
add: glass and non-glass CC doors (no sprite change)
/:cl:

### CODE REVIEW

**Comment by warriorstar-orion** [comment]
> I've always been of the belief that spaces should be designed well no matter how infrequently or briefly they are used. 

I 100% agree with this. It also makes sense to me that as we provide maps whose design is commensurate with increasing player populations, it's only natural to consider this when looking at CC as well.

Two nits:

- The shuttle airlocks don't have those light blue "SPACE" posters next to them (the ones that look like the DOORS posters you have in the center of the map) or striped yellow/black caution decals. May or may not be worth adding.
- The tile under this plant looks like sand? Should it also be one of the grass tiles used in the atrium?
154716892-151d31b6-c06a-433c-9342-b71f52a94fc7 png (3456×1856)-11_36_03

**Comment by AffectedArc07** [comment]
If you are going for fluff, then:

image
This needs doors on both sides

image
CC has to unload shipped packages

Other nitpicks:

image
This window seems very pointless, as it will almost always be facing a wall, and you can see if a shuttle is here from the other window by the shuttle console (where youd be looking from anyway)

image
This better be a grumpy fox


Its a lot less bad than the previous CC remap, but I am still not sold on adding to CC, especially given the event standards of some of the admins. Not really in favour, but not a full objection.

However, the shuttle changes should be in another PR. PRs should be atomic.

**Comment by Xsingular** [comment]
Awesome location for the new /landmark/shuttle_import, this will stop the custom fancy escape shuttles from cannibalizing parts of CC whenever they are spawned. 
Add this to the list of positive changes this PR proposes.

**Comment by Denthamos** [comment]
Given that the changes mostly effect ERT spawning and people arriving at round end, and the rest of the stuff inbetween is minor stuff for admins to use without a bunch of extra nonsense, a lot better than the previous version.

**Comment by Shadeykins** [comment]
Not sold on combining the shuttles w/ CC still, even w/ one-way doors. So much of EORG destruction is massive explosions, singulos, and generally unavoidable things.

Why do shuttles need to drop to the main CC area at all? Why is this, specifically, a design goal?

**Comment by S34NW** [comment]
> Not sold on combining the shuttles w/ CC still, even w/ one-way doors. So much of EORG destruction is massive explosions, singulos, and generally unavoidable things.
> 
> Why do shuttles need to drop to the main CC area at all? Why is this, specifically, a design goal?

Player choice, mainly.
Some people end up on pods but do want to engage in EORG, when this happens they tend to slaughter whoever is on the pod dock and cause chaos there. By giving them the option to move towards the large group brawl in the next room they are more likely to leave peaceful pod dwellers alone.

If bombs are set off on the shuttle or just after disembarking, even maxcaps will not fully damage the pod dock area. The windows and walls to there are indestructible. (The doors are not)

I do think this approach of consolidation is better in the long term for player choice.

**Comment by Shadeykins** [comment]
> > Not sold on combining the shuttles w/ CC still, even w/ one-way doors. So much of EORG destruction is massive explosions, singulos, and generally unavoidable things.
> > Why do shuttles need to drop to the main CC area at all? Why is this, specifically, a design goal?
> 
> Player choice, mainly. Some people end up on pods but do want to engage in EORG, when this happens they tend to slaughter whoever is on the pod dock and cause chaos there. By giving them the option to move towards the large group brawl in the next room they are more likely to leave peaceful pod dwellers alone.
> 
> If bombs are set off on the shuttle or just after disembarking, even maxcaps will not fully damage the pod dock area. The windows and walls to there are indestructible. (The doors are not)
> 
> I do think this approach of consolidation is better in the long term for player choice.

These people are generally immediately incapacitated by the majority of people there.

Are these doors hackable? Emaggable? What is there to prevent the doors from simply being forced open (or someone touching them from the opposite side) allowing the flood of EORG in? How does this solution fix the problem you've already presented? Why wouldn't someone on a pod just attack the people in their immediate vicinity anyways rather than use the doors? If they're happy to attack the randoms beside them because they want that sweet sweet EORG, why would they waste 20 seconds of it moving into an adjacent zone?

To me, this wants to resolve an issue but does so in a way that exacerbates the problem.

**Comment by S34NW** [comment]
> 
> Are these doors hackable? Emaggable?

No and Yes in that order

>
>What is there to prevent the doors from simply being forced open (or someone touching them from the opposite side) allowing the flood of EORG in? How does this solution fix the problem you've already presented?

As mentioned in the PR description, there is access control on the doors with an unrestricted south side (like you see in cyberiad brig or medbay) that permits you to leave but not to go in unless you have CC access.
In theory someone could "hold the door" open but I doubt this would happen in practice due to the nature of EORG chaos.

>
>Why wouldn't someone on a pod just attack the people in their immediate vicinity anyways rather than use the doors? If they're happy to attack the randoms beside them because they want that sweet sweet EORG, why would they waste 20 seconds of it moving into an adjacent zone?

That's already a problem now, but giving them access to more people to attack elsewhere incentivises them to head that way instead of sticking about. It's not going to take them 20s to reach the others either.

> 
> What's to prevent the mass of EORG from flooding in for fresh targets, especially when they have end-round guns/explosives?

Again, it's not going to be easy for them to do so without help from a borg. I'm gonna see about strengthening the doors so they can't be brute-forced with damage as easily.

**Review by dearmochi — APPROVED** [review]

**Comment by AffectedArc07** [comment]
#### Test Merge Deployed

##### Server Instance
paradise_main

##### Merged By
dearmochi

##### Revision
Origin: 137338f4dd3cb33124ab3fbd55a4865dd2bdab81
Pull Request: d2790a384e59f2e0ddad355292f801b1bed567d8
Server: 59637ded7fef794e4c769f15c11038dc0259c7bd

**Comment by AffectedArc07** [comment]
#### Test Merge Updated

##### Server Instance
paradise_main

##### Merged By
dearmochi

##### Revision
Origin: f061d281a102e2d7e5cdd810cef0450ed299240f
Pull Request: d2790a384e59f2e0ddad355292f801b1bed567d8
Server: 56bad662c1a885e46e9c18bfbcca9b45ec20c6c3

**Comment by datlo** [comment]
I feel like the solgov trading dock should have an entrance of some sort implied, and not just be a small dock in the middle of space. Some sort of teleporter that says 'access denied' if you try to use it? An airlock that can't be opened or hacked open by the traders?

**Comment by AffectedArc07** [comment]
#### Test Merge Updated

##### Server Instance
paradise_main

##### Merged By
dearmochi

##### Revision
Origin: f061d281a102e2d7e5cdd810cef0450ed299240f
Pull Request: 88e91ea985b534af65349c880e813621ac14b883
Server: 33ecb5e838964f5035c7fe5880916f8312559c43

**Review by AffectedArc07 — DISMISSED** [review]
You need to fix the issue with thunderdome spawning in the wrong spot. Arena in the top right needs updating.
image
image

**Comment by S34NW** [comment]
oh lord thats scuffed

**Comment by S34NW** [comment]
Tested locally, seems to work fine now

**Pull request merged**
