### PR TITLE
Removes Docking Controllers

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes the now unused docking controllers.

They're not used and never will be, again (long live TG shuttles).

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
Whats a docking controller...? >.<

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Whyyy, whyy does Metastation have a docking controller still on it?

**Comment by Spacemanspark** [comment]
Muahahahahahaha.
You must forever have docking controllers.

**Comment by Fox-McCloud** [comment]
It would appear there was a single one on metastation---and it doesn't appear to be hooked into anything; I didn't notice any doors or pumps with its ID tag; seems to be a leftover from before TG shuttles.

**Comment by FreeStylaLT** [comment]
Does this make those button cyclers for EVA access in danger of getting removed as well?

**Comment by Necaladun** [comment]
RIP Docking Controllers. Yay.

**Pull request merged**
