### PR TITLE
Converts the Russian gateway to a space ruin

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
Converts the Russian Gateway to a space ruin and changes the loot pool for it. Some stuff like the depressurized/depowered observatory and the glass directional windows (to give it the old CC feel) are done on purpose.<br><br>

While this loot might sound like a lot, keep in mind a majority of this stuff was either already on the original gateway mission or has been added due to the difficulty of this space ruin and to compensate with the removal of 7 fireaxes, 7 beartraps, mindshield implanter, telekinesis, 3 full security lockers, and lots of medical supplies.

### Notable contents
- 12 Russians
- 2 Space Bears
- A "XCC Commander" Russian with 150 Health and twice the shooting speed
- Comrade Cykasky
- A locked armory containing
     - 	Fireaxe (AWAY01 Access)
     - 	Beartrap
     - 	Lethal Injection Syringes (Yes the Old Z-Level had these too.) (AWAY01 Access)
     - 	Police Baton
     - A trick revolver
- A full kitchen and bar (Including 2 Whetstones, locked behind AWAY01 Access and the 2 Space bears)
- A XCC Commander Keycard with AWAY01 Access
- A "Cosmonaut Command Suit"
- A Military belt
- A Combat knife
- A pair of combat gloves
- A preloaded RCD
- An exosuit fabricator
- A Seraph and Ripley wreckage
- A pair of Superior Welding goggles
- A pair of Sunglasses
- A diagnostic, medical, and security hud (non-flash protection)
- Some normal night vision goggles
- Some Syndicate playing cards
- Some Syndicate soap
- An abandoned loot crate
- A Mysterious Medibot
- A surgery belt
- 4 different medical kits

## Why It's Good For The Game
Gateway is in the process of removal and this gateway is often complained about because they are given 8 fireaxes, 8 beartraps, free mindshields and 3 lockers of security gear, Ideally this amount of crazy loot should be minimized and swapped for more variable (but still good enough for how difficult this ruin is) loot.

## Images of changes
The new ruin

## Testing

Tested, compiled, played through all multiple times on a local server (I died a lot)

## Changelog
:cl:
tweak: The Russian gateway has been transformed to a ruin and is much smaller
tweak: Russian space ruin loot has been changed, check the PR for details
/:cl:

### CODE REVIEW

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
Map needs to use `/turf/template_noop` and `/area/template_noop`.

It should also be shrunk down to exactly fit the size of the zlevel.

**Comment by Contrabang** [comment]
> Map needs to use `/turf/template_noop` and `/area/template_noop`.
> 
> It should also be shrunk down to exactly fit the size of the zlevel.

Yeah using space as turf and area was just for convivence when creating it, that and the correct size will be implemented before the final version

**Comment by AffectedArc07** [comment]
I know this gateway mission needed a major cutdown, but I dont know if this is the right way to do it. 

Gonna let the design team (and some resident mappers) hash this out.

**Comment by hal9000PR** [comment]
currently, theres is nothing stopping someone from deconstructing/thermiting down the armoury walls, then baiting the simple mob into space, then looting it.

**Comment by Komrad822** [comment]
Wanted to mention this after discussing this in discord with @Christasmurf and the annoyance of the free sec gear came up.
Sec lockers provide 4 things (that we all know but should still be stated): 
1. Armor - Its slept on most of the time but can make a big difference in a fight on whether you get caught or make it out by the skin of your teeth.
2. SecHud - The information of your status, other peoples status and the ability to change it is quite useful. Also being able to tell if someone is implanted with tracker and/or chem implant is useful.
3. Sec Comms - Knowing whats going on in sec comms is HIGHLY useful as it tells who is with who, what higher command wants, where people are, who is getting chased, who got info on who, etc etc. Overall, information is a massive game changer in the hands of those who know how to use it.
4. Flashbang protection - Bowmans and sechuds provided in the lockers give this to anyone (except nians) and even with the flashbang changes is still very useful and if you want your antag round to go smoothly, this is a must have for most people. 

With these things listed out, in this PR there are three lockers with all of these benefits by just going into gateway (or space if this is evnetually moved to a space ruin is imho to strong. Ontop of that if it is moved to space, theres a chance that the z-level this spawns in has linked comms to the station, making sec comms key grab give you instant info as to what is going on with sec as compared to the gateway which is cutoff from it. 

The solution while still being a useful loot locker? Leave just the armor and flash protection. Replace the huds with sunglasses and remove the sec key from the bowmans. The armor is an almost non-issue since there are tons of times where armor is just left in arrivals shuttle anyway. If it is an issue still, replace it with theta armor, the one that slows etc. 

This is line of thinking is propagated by risk vs. reward for antags/explorer. Antag man wants flash protection so they can either steal from an officer(loud), steal a locker from sec(presence is known), find sunglasses and use ear muffs(stealthy, easy), or go off to space/gateway to get protection without the conveniences that come with the other gear (better but stealthy).

Please lemme know y'alls thoughts on this please.

**Comment by Contrabang** [comment]
I like the idea of the bowman's headset, and it is still pretty easy to obtain a non-sunglasses sec hud on station, so I'll add both of those. There was already some sunglasses but they were pretty easy to get so I've moved them. For armor, I don't think it would do much good to explorers since they have to wear space suits and there's already a security hardsuit in another ruin.

**Comment by Denthamos** [comment]
So looking at this I really am not a fan of the design in the theme aspect of it.  When we compare it to our other Russian ruin, the derelict which has such a startling change in design principle in comparison to NT and syndicate themed places this one just feels like another generic NT ruin.

I would prefer to see it match the Russian derelict in theme and design principle - additionally something neat that could be unique to said russian ruins is if it was made for the shuttle on the far left side of the russian derelict was changed from its current 'solfed' status to becoming a working shuttle for the USSP that can transfer back and forth between it and this ruin.

**Comment by Contrabang** [comment]
I may reopen this sometime in the future, currently very occupied with IRL stuff so won't be able to do any major changes to my PRs beyond fixing bugs, so I'm closing it.

**Pull request closed without merging**
