### PR TITLE
Re-adds Pyroclastic Anomally Event

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Re-adds the pyroclastic anomaly event.

Screw you, ZAS; your big sis, LINDA, has taken over.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Did you test this? [This line right here names flame_range, which is not a variable on our explosion proc.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/tgevents/anomaly_pyro.dm#L23)

**Comment by Robertha89** [comment]
It does need a buff, cause i tested it out, and it just damaged like 9 tiltes, some minor heat, and a slime spawns at the location. It used to be Ohgod firehelpmeimburning. Now it's like a fart, short, uneventfull,  and little lasting damage.

**Comment by Fox-McCloud** [comment]
It's been in for ~a year now with no issues, but was commented out a while back because ZAS+Pyroclastic = nightmare.

**Comment by fj45** [comment]
:100:

**Comment by Krausus** [comment]
> Did you test this? [This line right here names flame_range, which is not a variable on our explosion proc.](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/tgevents/anomaly_pyro.dm#L23)

As Tiger said, that line uses a named argument that doesn't exist. When that line tries to run, **it will runtime**. You have to test this stuff, and you have to pay attention to runtimes. You can't just ignore the goddamn runtimes.

**Pull request merged**
