### PR TITLE
Janitorial Drip

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Ports the galosh sprites from tg https://github.com/tgstation/tgstation/pull/73688
Resprites the default janitor uniform
Adds jumpskirt and overalls variants
Adds beret, grey and purple caps for janitor
Adds janitorial gloves - Rubber, but not insulated. Protects the hands from burning on lightbulbs.

All items available in janidrobe, gloves and galoshes cost nothing. 
Beret, caps and skirt available in loadout.
Jumpsuit and skirt can be rolled down, caps can be flipped or put on a corgi to make them look professional (get to work, slacker)

## Why It's Good For The Game
Better looking clothing, more variation in style

## Images of changes
Before:
image

After:
image

## Testing
Spawn in, walk to janitor office, buy all the items from the vendor and try them on
Spawn magic mirror, test all items on different species

## Changelog
:cl:
add: Added janitorial jumpskirt, overalls, beret, grey/purple caps, gloves.
imageadd: Resprited the default janitor jumpsuit and ported galosh sprites from tg
/:cl:

### CODE REVIEW

**Comment by datlo** [comment]
Perhaps consider partial insulation on the rubber gloves?
Good changes tho 👍

**Comment by Christasmurf** [comment]
> Perhaps consider partial insulation on the rubber gloves? Good changes tho 👍

That was the original plan but I spoke with the balance team back when I first coded the item and they said no insulation just the heat protection that the black gloves get

**Comment by Carthusia** [comment]
Are these just humanoid sprites or will other species versions need to be created for them?

**Comment by Henri215** [comment]
> Are these just humanoid sprites or will other species versions need to be created for them?

There are species versions.

**Comment by Christasmurf** [comment]
> Are these just humanoid sprites or will other species versions need to be created for them?

All species version are included I just don't put them in the screenshots

**Review by Henri215 — COMMENTED** [review]
image

image


Human overalls not 100% symmetrical because of that one pixel at the edge.
Everything else looks good.

**Comment by Christasmurf** [comment]
> image
> 
> image
> 
> Human overalls not 100% symmetrical because of that one pixel at the edge. Everything else looks good.

balls ass

**Review by Henri215 — APPROVED** [review]
LHTM (Looks Honkable To Me)

**Review by lewcc — APPROVED** [review]
LGTM (Let's Get This Mopped)

**Pull request merged**
