### PR TITLE
Paradise's soul removal part three: lawyers

### PR DESCRIPTION
**Pull request by ElorgRHG**
## What Does This PR Do

Ports https://github.com/tgstation/tgstation/pull/62961 and adjusts the sprites to our species
(suitskirts not included but they might be in a future PR 👁️ )

Draft until https://github.com/ParadiseSS13/Paradise/pull/19058 gets merged or closed. This PR is done, but it relies on that PR's removed reliance on hand holes.

## Why It's Good For The Game

Your honour, may I please prepare a file that has the dimensions of 192x128, I will place our current lawyer suit sprites on the top, and the herein proposed resprite at the bottom, then I shall screenshot that file and present it here.
image

Your honour, I have nothing more to say.

## Images of changes

image

## Testing

Took lawyer suits, arranged the image in `Images of changes`.

## Changelog
:cl:ElorgRHG, OctusGit
tweak: Red, blue and purple lawyer suits now have their color in their name.
tweak: Properly capitalises the blue suit.
imageadd: Resprited lawyer suits.
/:cl:

### CODE REVIEW

**Comment by maxlel** [comment]
Looks slick

**Comment by PacifistDalek** [comment]
OBJECTION!!


Your honour,  as the blue and red lawyer sprites are a reference to Ace Attorney, we ask the court: where is the ostentatious cravat on red?!

**Comment by procdrone** [comment]
Sprites good, although, im sad as this kills my drip. I often use IAA basic clothes. (the white shirt with a tie and pants, no jacket one)

**Comment by ElorgRHG** [comment]
The prerequisite has been merged, this PR is ready.

**Review by farie82 — APPROVED** [review]

**Pull request merged**
