### PR TITLE
Adds Supply section to manifest

### PR DESCRIPTION
**Pull request by Tastyfish**
Splits out QM, cargo tech, and shaft miner into seperate category in the manifest per [this suggestion thread](http://nanotrasen.se/forum/viewtopic.php?f=12&t=6951).
* I made Service (pretend all the screenshots say Service) and Supply exclusive categories, I can make the supply people also show up in Support if that is preferred.
* Colors:
 * Service didn't actually have a color for their category (the class was missing) so I made it purple since both clowns and janitors have purple, and botanists/cooks can use grapes I guess.
 * Supply is brown because cardboard, and dirt I guess.

#### The Various Flavors of Manifest
Preview
Preview
Preview
Preview

:cl:
rscadd: Cargonia now has its own section in the manifest.
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
:+1:

**Comment by NTSAM** [comment]
:+1: 
Bout time Cargonia got the respect it deserves

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by FalseIncarnate** [comment]
Changelog

**Comment by Norgad** [comment]
Isn't 'Support' called 'Service'?

**Comment by Tastyfish** [comment]
I could change that section to be called service, since it doesn't include supply anymore.

**Comment by Tastyfish** [comment]
Pretend all the screenshots say Service instead of Support now.

**Comment by Fox-McCloud** [comment]
>Pretend all the screenshots say Service instead of Support now.

SO REAL

**Comment by TheDZD** [comment]
The one thing that seems slightly out of place is that the QM appears in the same color as the heads of staff on the manifest, while the HoP is ultimately the boss man in cargo.

**Comment by Tastyfish** [comment]
I was actually unsure what to do for that, would you prefer the HoP show up in Supply too as the head, or there be no highlighted jobs in supply?

**Comment by BiberDark** [comment]
I think the Qm should be the boss in cargo not the hop. The Hop is the distributor of human ressources the QM the distributor of goods and raw materials.

PS: It looks like the HOP in this screenshoot is not a ahead at all beacause he is not listed as head.

**Comment by Regen1** [comment]
:+1:

**Comment by Tastyfish** [comment]
How about this for dealing with the HoP & QM?
preview

**Comment by TheDZD** [comment]
That works.

**Comment by Plotron** [comment]
Amazing!

**Pull request merged**
