### PR TITLE
Adds coughing and sneezing sounds for Drask

### PR DESCRIPTION
**Pull request by HugoLuman**
Whale cough NOW

It is terrifying.

:cl:HugoLuman
rscadd: coughing and sneezing sounds for the Drask
/:cl:

### CODE REVIEW

**Comment by HugoLuman** [comment]
Can someone review this please?

**Comment by SamHPurp** [comment]
@HugoLuman sorry its taken so long for any feedback at all. I'll give mine at least.

I think the coughing sounds good, the sneeze though sounds much closer to a purr than a sudden burst of (gross moist) air escaping your nose.

Its also important to check volumes of these against the human ones to ensure that the average & peaks are close - have you been able to do this?

**Comment by TullyBurnalot** [comment]
@HugoLuman 

While this does sound suitably... alien, there are a couple of issues:

- The cough ends up sounding more like a growl than anything else. Tiger offhandedly commented it sounded like something out of a Doom game, and I kinda have to agree;

- The sneeze is, shall I say, too slow and ponderous. It sounds like an odd sigh, rather than a sudden burst of expelled air

**Comment by HugoLuman** [comment]
I'll try some new ones on after Christmas, hopefully I'll have a new mic

**Pull request merged**
