### PR TITLE
Slime people can now regrow their limbs at a lower nutrition cost

### PR DESCRIPTION
**Pull request by Crazylemon64**
This also enhances the nutrition pump to allow them to reach a level of satiation where they can regrow a limb, if nothing is stressing them.

Since you lose 10 nutrition a life tick while your blood is depleted, down to 300 nutrition, this should let you get off at least one limb regrowth in case of brutal trauma.
:cl:Crazylemon
tweak: Slime people can now regrow limbs on a more lax nutrition requirement
tweak: Enhances the nutripump+ to let slime people regrow limbs with it active
/:cl:

### CODE REVIEW

**Comment by johannhawk** [comment]
hmmm, what about regrowing broken bones? we COULD make that slightly cheaper.

**Comment by fludd12** [comment]
I really think they shouldn't have bones - What with the organ changes to make boneless organs take more damage, I'd think that's balance enough.

**Comment by Crazylemon64** [comment]
Actually, that changelog thing was erroneous - I actually tore that out before getting that merged, so boneless organs function the same as boneful organs

**Comment by fludd12** [comment]
Oh, darn it.
Can we have the whole, slimes are easier to blow limbs off in exchange for no bones thing though? Might be outside the scope of the PR, but skeletal slime people are just really weird to me.

**Comment by HereticChurch** [comment]
I was gonna suggest this. :+1: 
Buffing the ability further to allow fixing of bones would be really neat.

**Pull request merged**
