### PR TITLE
Removes Stealing a RCD as an objective

### PR DESCRIPTION
**Pull request by Lady-Luck**
This one should be obvious. A boring objective for everyone involved.

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
Hack an autolathe
Ask for an RCD from it
Win the game

Pretty boring.

**Comment by Lady-Luck** [comment]
Go up to R&D.
"Hey can I get a RCD?"
"Okay here you go."

**Comment by Fox-McCloud** [comment]
If you're going to remove something, do it properly.

**Comment by Lady-Luck** [comment]
What did I do wrong?

**Comment by Fox-McCloud** [comment]
For one, you commented out the code instead of removing it. Secondly, this isn't even where the objectives are handled.

you need to look under `code/game/game_modes/steal_items.dm`

**Comment by Lady-Luck** [comment]
I'll fix it. I simply assumed I was supposed to comment it out given there's lots of other commented out objectives in this file.

**Comment by Lady-Luck** [comment]
>newobjective.dm isn't even compiled in.

Er... why do we still have it then?

**Comment by Fox-McCloud** [comment]
I haven't the foggiest. Probably because no one has bothered to get rid of it yet.

**Comment by Kyep** [comment]
Voted yes.

I'd actually suggest going further and removing the 'steal a tank of plasma' objective as well. It is equally boring.

**Comment by FlattestGuitar** [comment]
Unused slime extract should go too.

**Comment by Kyep** [comment]
Agreed.

**Comment by theColdflame** [comment]
'Steal a jetpack' is trivial as well.

**Comment by Davdichan** [comment]
voidsuits could probably be added to that list

**Pull request merged**
