### PR TITLE
Adjusts DeltaStation IA Office to support two IA Agents and other QoL changes

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Expands the DeltaStation Internal Affairs Office to support having two Internal Affairs Agents, giving them two desks as well as other Internal Affairs quality of life updates such as electrochromic windows, and an SOP library.

## Why It's Good For The Game
 We have two IA job slots, they should both have somewhere to call home. Also moves some wiring around to make it make more sense.

## Images of changes

Old IA Office

image

New IA Office

image

## Changelog
:cl:
tweak: Remaps DeltaStation IA Office to support double IAA jobslots
/:cl:

### CODE REVIEW

**Review by S34NW — CHANGES_REQUESTED** [review]
Please use the correct light switch dirs

**Comment by S34NW** [comment]
The camera is labelled as "Magistrates Office"

**Comment by S34NW** [comment]
The fire alarm is 24 pixels offset, not 26 as per the rest of delta's fire alarms

**Comment by S34NW** [comment]
image
This wire has a null tag

**Comment by S34NW** [comment]
image
This supply pipe is not connected

**Review by S34NW — APPROVED** [review]

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
