### PR TITLE
Cere station fix/tweak collection

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do

Remaps service asteroid

Adds many more intercomms, NT really skimped on them initially.

Expands the bar into the old library area, pushes the library down and reorganises it a bit.

Pyjamas added because of this angry rant that I was never pinged in:
image

Fixes https://github.com/ParadiseSS13/Paradise/issues/20350

Fixes https://github.com/ParadiseSS13/Paradise/issues/20352

Adds disposals to xenobio and robotics.

Reorganises robotics slightly to make more sense.

Adds air tank dispenser to armoury.

Adds RPD to SM chamber. Fixes https://github.com/ParadiseSS13/Paradise/issues/20527

Removes extra guest pass terminal in medbay, leaving only the one in the CMO office.

Adds patch pack and pill bottle boxes to medbay and medchem.

Removes hidden extra SMES in engineering.

Added a missing starter slime in xenobio.

Fixes 
image
image
image
image

## Why It's Good For The Game
Cere needs some fixes and love following it's full-merge. This fixes some of the more egregious issues.
There remains a bigger point around the bar layout and kitchen, but I need more help from people who play these roles before I attempt that.

Please let me know if there is anything else you noticed that needs fixing or tweaking so I can implement it.

## Images of changes
image

## Testing
Eyeball testing, waiting for PR to run CI tests.

## Changelog
:cl:
fix: Fixed numerous small mapping issues on cere station
tweak: Tweaked bar and library layout on cere station
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Drafting while i rework service layout

**Comment by ppi13** [comment]
Increasing the size of the custodial closet there, so janitors dont accidently get stuck.  
Library seems oddly huge, especially the librarians back office, and could maybe do with being shrunk.  
image
Missing vents and scrubbers here.
One weldertank is missing a watertank friend on west maint, and north east and south east, has zero weldertanks/watertanks.  
Kitchen could do with a bin for garbage outside.  
The signs in the hallways to the right 
image
Could have a command sign as well pointing north.
Botany could have a bell as well

**Comment by Git-GoR** [comment]
Some small issues:

- The gas pump going into the SM chamber has the default name, while the output is modified.
imagen

- The atmospherics pet has a typo in its description. Inteded?
imagen

- Pump named "Mix to filter", but it comes from Pure rather than Mix (and it's on by default). On top of that both this one and the pump north of it are connected to the connectors/cannisters, not filters.
imagen

- Both pumps named "North Canister to waste". I do not have a decent suggestion... "Gas to North/South Canister"?
imagen

- "Mix to Incinerator", but Cere has no Incinerator. This goes to the turbine. And speaking of turbine...
imagen

- Red is named "plasma tank pump", should be "O2 tank pump". Greens are "Incinerator to...", should be "Turbine to...".
imagen
 
- In the fitness room, holopad under a stool. Could be moved one tile down.
imagen

- Theatre APC hooked to the main electrical net, rather than Service's.
imagen

- All SMES room airlocks use the Engineering Yellow variant—except Medbay.
imagen

- Also, there are no fungus spawners anywhere on the station. Unsure if this is intended or not, as botany can grow it after all.

As a final remark, something that others have talked about already. The telepads room at arrivals and science do not save much time when travelling from one to another. Maybe move both a bit towards the edges? The one in Science could be moved to the space between AI Upload and Robotics, and the one in Arrivals could be switched with the Arrivals Emergency EVA storage.
That said, the later would break the norm of having windows towards space in all of them... Might require a bigger restructuring.

**Comment by warriorstar-orion** [comment]
Robo/mechbay seems to be missing a holopad.

**Comment by S34NW** [comment]
> Robo/mechbay seems to be missing a holopad.



> Some small issues:
> 
>     * The gas pump going into the SM chamber has the default name, while the output is modified.
>       imagen
> 
>     * The atmospherics pet has a typo in its description. Inteded?
>       imagen
> 
>     * Pump named "Mix to filter", but it comes from Pure rather than Mix (and it's on by default). On top of that both this one and the pump north of it are connected to the connectors/cannisters, not filters.
>       imagen
> 
>     * Both pumps named "North Canister to waste". I do not have a decent suggestion... "Gas to North/South Canister"?
>       imagen
> 
>     * "Mix to Incinerator", but Cere has no Incinerator. This goes to the turbine. And speaking of turbine...
>       imagen
> 
>     * Red is named "plasma tank pump", should be "O2 tank pump". Greens are "Incinerator to...", should be "Turbine to...".
>       imagen
> 
>     * In the fitness room, holopad under a stool. Could be moved one tile down.
>       imagen
> 
>     * Theatre APC hooked to the main electrical net, rather than Service's.
>       imagen
> 
>     * All SMES room airlocks use the Engineering Yellow variant—except Medbay.
>       imagen
> 
>     * Also, there are no fungus spawners anywhere on the station. Unsure if this is intended or not, as botany can grow it after all.
> 
> 
> As a final remark, something that others have talked about already. The telepads room at arrivals and science do not save much time when travelling from one to another. Maybe move both a bit towards the edges? The one in Science could be moved to the space between AI Upload and Robotics, and the one in Arrivals could be switched with the Arrivals Emergency EVA storage. That said, the later would break the norm of having windows towards space in all of them... Might require a bigger restructuring.

All of the above fixed, thanks for reporting

**Review by Sirryan2002 — APPROVED** [review]

**Comment by ppi13** [comment]
image
strip mine part of the astroid maybe?
image
the power requirements here does not require 2 smes, unless its for powering the powersink that is botany.
image
Is it intended for it to not have reinforced glass floor?
image
Fore-starboard could do with an extra smes, because of the powersink that is cargo.
image
Magistrate office is missing disposals
image
So is detective.
image
Security breakroom and HoS office is also missing disposals.
image
vacant could use one, but its fine either way.
image
RD office as well
image
research break room
image
Gravity generator smes should start fully charged, and not connected to the station powernet.

**Comment by S34NW** [comment]
>strip mine part of the astroid maybe? 
the power requirements here does not require 2 smes, unless its for powering the powersink that is botany. 
Is it intended for it to not have reinforced glass floor?
Fore-starboard could do with an extra smes, because of the powersink that is cargo.
Magistrate office is missing disposals 
So is detective. 
Security breakroom and HoS office is also missing disposals.)
vacant could use one, but its fine either way. 
RD office as well  
research break room 
Gravity generator smes should start fully charged, and not connected to the station powernet.

All points addressed bar 1, 2, 3, 4

Major upgrades to all departmental and head disposal routing, including disposal loops that actually deliver to robotics, R&D, QM, CE, atmos, engineering, CMO, medchem, genetics, Captain's office, HoP office, HoS office, Security, Detective.
No more do they just come out a single combined chute in some random location.

**Comment by ppi13** [comment]
There are a lack of fire extinguishers in medbay.

**Comment by S34NW** [comment]
> There are a lack of fire extinguishers in medbay.

Let them burn

**Comment by Contrabang** [comment]
Coroner has 2 sets of formaldehyde in their locker, if you could also touch up on that 👀

**Comment by Git-GoR** [comment]
All issues raised in both this PR comments and Discord fixed. Looks good to me.

A good bunch of changes, great work 👍

**Comment by ppi13** [comment]
image
Chapel got an random cable
image
East of bridge in maint, there is a random cable towards a tiny loot spawner room with no function
image
AI Core also have a random cable thats not used for anything, since the AI smes does not receive any power.
image
This part, makes it look like connecting the air to the powernet would be really easy, is that intended?
image
Same place but with nothing hidden.
image
Grav gen also got a random cable from the smes, is it intended or not to connect it to power easy or not`?
image
South-east solars, copypaste gone wrong.
image
Minor gripe, but this door should only have "23" instead of "19;23"
image
Second minor gripe, the cabling here for power that leads to south-eastern space disposals, could come from the east door of aft-starboard maintenance, instead of the west door.
Thats all for power issues,

**Comment by S34NW** [comment]
> Chapel got an random cable 

fixed

> East of bridge in maint, there is a random cable towards a tiny loot spawner room with no function 

fixed
> AI Core also have a random cable thats not used for anything, since the AI smes does not receive any power.

intended, allows hooking it up if required
> This part, makes it look like connecting the air to the powernet would be really easy, is that intended?

intended, allows hooking it up if required
> Grav gen also got a random cable from the smes, is it intended or not to connect it to power easy or not`? 

Same place but with nothing hidden. 
> South-east solars, copypaste gone wrong. 

fixed
> Minor gripe, but this door should only have "23" instead of "19;23" 

fixed
> Second minor gripe, the cabling here for power that leads to south-eastern space disposals, could come from the east door of aft-starboard maintenance, instead of the west door. Thats all for power issues,

fixed

**Review by ppi13 — APPROVED** [review]
Power ✔️
Pipes ✔️
Disposals ✔️
APC ✔️
Solars ✔️
RPD ✔️
As far as I can see, and find, there are no glaring issues, large or small left to fix/tweak, and outside of possible overlapping items, and some departments missing an item or two that they have on other maps, this is ready to go, and gets my stamp of approval!

**Review by Git-GoR — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Comment by Christer2222** [comment]
Is it too late to ask for changes? 
It would be nice if CMO could get a monkey cube box, like on Cyberiad.
The operating rooms in medbay are missing disposal chutes.

**Pull request merged**
