### PR TITLE
Removes vox & Vox raiders

### PR DESCRIPTION
**Pull request by hal9000PR**
## What Does This PR Do
This PR removes vox, the raiders gamemode, and associated areas on CC

If you bought vox, you can refund it for 45 karma points

## Why It's Good For The Game
With moths on the horizon, its worth getting these out now.

They were only added for a broken gamemode that was never even played, and the species just encourages toxic metafriending, no more yaya kinsies break my out of brigsies. It also snowflakes the code a lot and we may as well nuke them (I am sure leadership wont mind).

## Changelog
:cl:
del: vox and vox raiders. if you purchased vox you will be able to refund them in the karma store.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
**Reminder**

Anyone attacking PR authors over ideas can face gitbans. Criticising ideas is fine, criticising people is not.

**Comment by S34NW** [comment]
yes, this makes room for moffs

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
```
[2021-11-11T14:18:05] Runtime in unsorted.dm,1992: Gamemode heist has a probability in config, but does not exist!
  proc name: stack trace (/datum/proc/stack_trace)
  src: /datum/configuration_section/g... (/datum/configuration_section/gamemode_configuration)
  call stack:
  /datum/configuration_section/g... (/datum/configuration_section/gamemode_configuration): stack trace("Gamemode heist has a probabili...")
  /datum/configuration_section/g... (/datum/configuration_section/gamemode_configuration): load data(/list (/list))
  /datum/server_configuration (/datum/server_configuration): safe load(/datum/configuration_section/g... (/datum/configuration_section/gamemode_configuration), "gamemode_configuration")
  /datum/server_configuration (/datum/server_configuration): load all sections()
  /datum/server_configuration (/datum/server_configuration): load configuration()
  world: New()
```
Heist needs removing from default config

**Comment by AffectedArc07** [comment]
Forgot that one

**Comment by Necaladun** [comment]
lmao, madman actually did it. 

(Object for the record because obvious meme, but god this is gonna be funny.)

**Comment by ArdentSpark** [comment]
I hope everyone will be chill in git comments today

I think I only saw vox raiders ran once and the comment about why it wasn't ran often did seem to be about causing self-antag behaviour from vox characters on station so I definitely feel like scrapping that isn't a bad shout.

Scrapping vox entirely for toxic metafriending seems really off. If the problem is due to Vox lore dictating that they stick together and distrust non-vox, would it not be wiser to alter Vox lore or warn those players appropriately? Paradise vox are already significantly different from other server's portrayals as it stands so further alterations to prevent self-antag behaviour would totally be fine.

In terms of snowflake code, I can only see a few unique references outside of sprites, and that's with airalarm code. This also scraps the vox plushie, as well as quite a few donator cosmetic items which seems a little harsh

**Comment by matttheficus** [comment]
Can we request IPCs be axed too on the grounds that their bodies may as well be made from snowflakes since you can knock them over and they fall apart?

**Comment by EmilitiaEnnehrt** [comment]
This will majorly affect the robust fictional economy of Trans-Solar Government, though I, in the very moment, believe that Nanotrasen can replace their unpaid workforce with slimepeople and subjugate the moths provided IPC already have their own rights restricting us from imposing forced labor on them.

Perhaps the immediate neutralization of the IA department as a whole will be more positively contributed to overall company performance and profit rating.

**Comment by AffectedArc07** [comment]
> Can we request IPCs be axed too on the grounds that their bodies may as well be made from snowflakes since you can knock them over and they fall apart?

Listen here you little

**Comment by matttheficus** [comment]
> This will majorly affect the robust fictional economy of Trans-Solar Government, though I, in the very moment, believe that Nanotrasen can replace their unpaid workforce with slimepeople and subjugate the moths provided IPC already have their own rights restricting us from imposing forced labor on them.

I think the solution is humans-only then. Humantide worldwide. Cant cause issues if everyone's a bald human.

**Comment by meow20** [comment]
Now let's discuss cult balance.

**Comment by Necaladun** [comment]
> > This will majorly affect the robust fictional economy of Trans-Solar Government, though I, in the very moment, believe that Nanotrasen can replace their unpaid workforce with slimepeople and subjugate the moths provided IPC already have their own rights restricting us from imposing forced labor on them.
> 
> I think the solution is humans-only then. Humantide worldwide. Cant cause issues if everyone's a bald human.

Humans - especially bald ones, are actually the most likely to be banned. I think we should remove them too. ObserverStation13 is in line with a lot of our playerbase.

**Comment by BardTheBard** [comment]
My thoughts here reflect @ArdentSpark. Vox raiders are a gamemode that isn't used and removing it is probably a smart move.

As for the idea of the toxic metaclique... having played a vox character for a few hundred hours now, I have almost never noticed this happening. It is true that the vox lore encourages it and the distrust of aliens, but this does not reflect the current playerbase, nor does it promote the type of roleplay we want on this server. As such, I am in favour of a rewrite of the vox lore, but not their removal.

**Comment by Necaladun** [comment]
Psst. Read the comments before posting knee-jerk reactions.

**Comment by dearmochi** [comment]
Aye aye the joke's run its course already, everyone go home.

On a more serious note, things of this scale should always be discussed beforehand in a forum post, please and thanks

**Comment by ArdentSpark** [comment]
I mean. Most SS13 githubs are full of meme comments, while a PR is open there's a chance of it being merged until someone says
"Ayoo I have authority absolutely no you dingus."

But yeah I hope it was obvious that they weren't knee jerk reactions, there was definitely a strong attempt to be reasonable. Discord is for the loopy knee jerk reactions.

Oh hey look it happened sick. Cheers Jade.

**Comment by hal9000PR** [comment]
the weak fear the strong

**Comment by skeksis1** [comment]
I've only played vox raiders once in my entire time on Paradise, and i can't say it was a particularly engaging game mode so removing it would probably be for the best.

Regarding vox metaclique, having played vox quite a bit - i don't feel like i've ever had preferential treatment from other vox, other than yelling at sec for removing my mask. 
Not to say that this doesn't happen, just that i didn't encounter it myself.

My thoughts are that people tend to play along with you, if you're generally nice to them or have something to offer to the overall experience, which has little to do with the race you're playing as.
I will admit that vox have a tendency to talk in pidgin and bunch up a lot more than other races, which often times leads to the overall sentiment that they're always scheming together. 
I remember how i viewed vox before starting to play them, and it DOES seem that way. 

To dish out a practical example:
Let's say i work warden and officers drag in a vox for doing X crime. At that point, i'm likely to talk in pidgin to them and ask stuff like "how'd you get caught" or "i'm disappointed in you kins", which to the other people witnessing may very well look shady, but that doesn't mean that the vox gets preferential treatment. Space law is the same, but interactions are different based on lore, and i think that's a bit of the beauty of playing vox.
Other races could do the same, they just don't and i feel like that's because of how the solid player base of that race generally interacts with eachother.
New players tend to more or less try to emulate what the older ones of that race do, so if you have solid friendly vox player base, new ones will tend to act the same. When i originally started playing vox, i was more or less trying to "do" or "be" what the other vox were as well. It just so happened that most of them were very friendly and talked in pidgin a lot and that was fun and engaging for me as new to the race.
I had a completely different experience playing slime, however where most people who play it (in my experience) tend to work sec roles, or are really good antags who don't specifically RP their race that much.

Sorry for the very long comment, but i'm attached to vox in a biased way, because i feel like most of the vox community generally PLAYS the game differently, which lends to the overall sensation of a metaclique.

**Comment by Fox-McCloud** [comment]
img

**Comment by lectronyx** [comment]
finally, a good pr

instant merge, promote to headmin, give him $500

**Comment by hal9000PR** [comment]
> promote to headmin

Bold assumption i want this.

One day the world will be ready for my progressive ideas.

**Comment by AffectedArc07** [comment]
image

**Comment by hal9000PR** [comment]
> One day the world will be ready for my progressive ideas.

The time is now

**Comment by procdrone** [comment]
finally we have matured enough as a community to do such important steps!

**Comment by AffectedArc07** [comment]
One day ill do this as a serious PR

**Pull request closed without merging**
