### PR TITLE
Sec Remap

### PR DESCRIPTION
**Pull request by Kyep**
http://nanotrasen.se/phpBB3/viewtopic.php?f=2&t=7749&p=64744

Remaps Perma: http://i.imgur.com/HvAVS8O.png
- Botany area
- Basketball court
- More sensible atmos
- Split, isolatable cells
- Multiple arcade machines

Remaps cellblock: http://i.imgur.com/uUv8Iqr.png
- Brigbay moved and now a valid destination for cargo mail system
- Now 8 cells, split into two cell blocks
- Deletes labor camp & associated shuttle

Remaps Interrogation: http://i.imgur.com/P2tP1Rb.png
- Shared processing room with timers, to discourage prisoners being held over 10m with no charges
- Hearing room, for legal stuff
- Evidence/prisoner stuff storage combined into one, bigger room

This is a work in progress - please don't merge it yet.

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
Looks good to me, although, you maybe_should_ have left the labor camp in. Other than that :+1:

**Comment by monster860** [comment]
2 things stand out to me. There is a stray intercom an 2 stray fire doors

**Comment by theColdflame** [comment]
Evidence storage and interrogation should have non-glass airlocks. Probably solitary, too.

Aside from that, :+1:

**Comment by FalseIncarnate** [comment]
Looking good so far, still want to request that the perma bathroom either gets shrunk down by 1 tile or the cells get moved up one tile, to make the two halves even in their width/height/whatever dimension that is.

Some seeds would be needed to make that botany area usable, perhaps we can code a "prisoner botany vendor" that holds some low-threat seeds (like wheat, carrots, basically foods that don't contain drugs / toxins) and basic botany tools (pest spray, ez-nutriment, etc), then maybe toss a smartfridge in to hold their produce / extra seeds?

Monster is right, the cellblock image does show 2 firedoors just kinda floating in the remapped hallway, those will need to be moved to make it not look weird, and maybe move that light over one so it isn't on the door. There also is an air alarm and APC in cell windows, not sure where to move those to make them more accessible though... Maybe shrink the individual cells and connect the two blocks with a small hallway? Could shift the clown office down a tile or something to let you shrink the public hallway there to two tiles if needed.

Tempted to say swap the courtroom with the brigbay (maybe put the firing range where the court room is and the brigbay on the outside for more room) so you can make the courtroom open to the public for viewing (clown office would need to get moved a tile or two further out to make room for a door), but that's not really important

**Comment by Iamgoofball** [comment]
interrogation room needs 1 way glass.

**Comment by MindLeaker** [comment]
As Coldflame said, Interrogation and Solitary shouldn't have see-through doors
Also, I'd like to hear the reasoning for deleting the Labour Camp, I don't disagree that it's underused, but I still find it to be a nice addition and gives medium-high sentence prisoners something to do.

**Comment by FlattestGuitar** [comment]
As far as I know the labor camp is literally broken and cannot work properly. The machines simply don't do what they should, making the whole thing impossible to use.

Dedicating resources to ensuring labor camp prisoners don't run away somehow is a bad choice most of the time and I don't think the camp should exist as an option.

That said, what *is* happening to the labor camp in this PR? Possibly making it into another abadoned outpost on the asteroid would be a good idea?

**Comment by monster860** [comment]
@Iamgoofball If only. The only way I can think of to do this is to do weird snowflaked fake opacity overlays, which I know @tigercat2000 would hate.

**Comment by CrAzYPiLoT-SS13** [comment]
Probably could be done by checking the direction from the glass you are, if
anywhere in the blocking half, you would get the same visibility as if
looking to a wall, if on the other half, you could see like a window.
Probably wouldn't need to use anything else but the lighting system.

**Comment by monster860** [comment]
But then you run into the same problem you have with the space parallax.

How do you detect when the player is on one side of the glass?

**Comment by CrAzYPiLoT-SS13** [comment]
If I am not wrong, there are direction and triangulation helpers. Although,
this isn't really the best place to talk about this.

**Comment by KasparoVy** [comment]
Most of what I see the labour camp used for is a last-resort for mining when, inevitably, other departments steal the ore redeemer at round start during nations.

**Comment by FalseIncarnate** [comment]
Polarized glass could be used as an alternative to one-way windows, as it can be toggled as transparent or not.

**Comment by Vivalas** [comment]
There is debate as to whether solitary should be glass or not but without glass airlock you can't really see when a prisoner is about to bum rush out as soon as you open the door.

The day BYOND gets directional opacity will be amazing. I've wanted the feature for so long, it would allow cool things like walking side of walls. Or, you know, at the very least make opacity less of a hardcoded thing.

**Comment by Kyep** [comment]
Re: Labor Camp
I deleted it because it is terrible.
Mining has never been a viable labor option for prisoners - if space exposure doesn’t kill you, the monsters will - and the amount of time it takes to accrue points with low-value ores practically ensures you get killed before you can mine anything useful. Even if, by some miracle, you do mine ore, you can’t get to all the consoles/machines to redeem it, and even if Sec helps you with that, the chances they’ll take your ore and deliver it so it can be useful are nil. It is already such a hassle for Sec to use they don’t bother using it. You’d have more luck running through space to try to get to the northern pod to escape. All in all, sending someone to the labor camp is just an unofficial death sentence (if they try to do what they’re supposed to) or an escape opportunity (if not). Due to the random cave-gen algorithm active on z5, this is not fixable without completely uprooting the labor camp and moving it to a completely new asteroid, with air, no monsters, no cavegen, and precautions taken against escape (even by races like Vox). There is no point to doing that, though, because the amount of work it would take to completely redesign the labor camp to make it actually functional is better spent on creating a new, better-designed-from-the-start replacement.
I could have kept the gulag outpost in a ruined state, but I decided not to as I couldn’t think of any purpose it would serve. Keeping the science outpost in a nerfed state after the removal of xenoarch led to many problems. I did not want to make the same mistake with the labor camp that we already made with the science outpost… so I deleted it entirely. Nothing of value was lost, IMHO.

Re: Stray intercom / fire doors
Was fixed previously, but I forgot to update screenshot.
Updated screenshot: http://i.imgur.com/4xSzNO5.png

Re: Glass airlocks for evidence storage, intero, and solitary
Evidence storage I could go either way on. Is there a particular reason you want it to be solid? Most of the doors in brig are glass, so I'm going with glass for this as well unless there's a good reason not to.
Intero I can see a good reason for - you don't want them to be able to talk to other prisoners in the halls while being interrogated. Changed.
Solitary I'd like to keep glass. There's a real danger someone could be thrown in there and simply ignored for the rest of the round if the airlock is not glass. Aside from that, glass is safer as it enables the officer to disable-beam the prisoner through the door, and see ambushes being prepared for them.

Re: Perma bathroom reduced in height by 1
Changed. http://i.imgur.com/eXV89ph.png

Re: Seeds area for botany
They don’t show up in the screenshots, but 3x wheat, 3x rice and 3x apple packets are prespawned in the area.
There are also 4 bottles of ez-nutrient, a mini-hoe, a plant analyser, and two buckets.
This should be enough to practice safe botany.

Re: one-way glass, polarized glass
Changed. http://i.imgur.com/h59aBGO.png

**Comment by theColdflame** [comment]
Evidence is currently non-glass and should probably stay that way- it doesn't make much of a difference either way from a gameplay standpoint. but it makes the room feel more distinct from the coridoor and let's you handle evidence in peace. 

Solitary SHOULD isolate the prisoner, that's kind of the point of solitary confinement. They have contact with the AI and a camera on the inside.

**Comment by Davdichan** [comment]
Should just make the basketball court a full on holodeck.

**Comment by theColdflame** [comment]
doesn't a holodeck give perma prisoners access to stamina weapons?

**Comment by Fox-McCloud** [comment]
Don't like this at all. It takes a few problems with the current brig and exacerbates them, significantly.

Permabrig is a huge sprawling gigantic open room. Prisoner processing is overly gigantic and has back to back windoors which look really bad. 

overall, way too many, what I call "huge open square sprawling rooms". I realize that a lot of rooms and areas are inherently square, but how you break them up, place items, and decorate them can really make it feel like it's not (for example, medbay doesn't *feel* like it's just one big square, when it kinda is). The brig physician feels like a small medbay with how big it is.

I really question the need for a whopping 8 brig cells. It's rare that 4 cells are in used, let alone 6---8 is overkill in the vast majority of cases.

Just out and out removing the labor camp kinda seems like it should probably be in a different PR, to be honest. I realize it has a number of problems, as it currently stands, but just removing it, outright, comes across as a bit..wrong.

General mapping errors:

- Doors always go on top of firelocks or blast doors, not under them.
- having side by side walls is bad and should be avoided whenever possible
- windows that don't lead to anywhere or server a purpose are not well placed windows (like next to the firing range or in permabrig).


I'd recommend taking a look at both Bay and TG's brigs for overall design (though I personally think that Bay's communal brig is asking for trouble). I know Metastation's brig design was popular in terms of overall style, look, and layout. These could give you a better idea of a more logical/flowing layout while also avoiding pitfalls of "huge open sprawling rooms".

**Comment by Vivalas** [comment]
I don't think there should be any less than 6 cells, 4 is generally the most used and 6 is good for overflow during rounds with lots of tide.

Also @fox-mccloud would you care to explain what problems the brig currently has and how this design exacerbates them?

**Comment by FalseIncarnate** [comment]
Polarized glass will require buttons set up to work with them, so that the polarization can be adjusted (press button, glass goes dark. press again, glass goes clear).

Pest spray is still going to be needed for the botany, or else pest levels can't be lowered sentencing your plants to death much like how half the sec team wanted you to be sentenced if you are in perma.

**Comment by Kyep** [comment]
> Permabrig is a huge sprawling gigantic open room. 

It was originally smaller.
I expanded it 2 rows northwards because of @Nec’s request.
I don’t mind changing it back, but the two of you need to discuss this and agree which way it should be.
I don’t want to keep changing it back and forth.


>Prisoner processing is overly gigantic and has back to back windoors which look really bad.

It has to have enough room for Sec to process 3-4 people at once, plus space to put their items down, plus space for everyone to move around.
It also supports both “put people in processing cells with timer to discourage them being held over 10 minutes” and also “put people on the chairs right next to warden’s office” modes of operation. 
Given those requirements its size isn’t unreasonable. You can skimp on the requirements, but that just leads to the “can’t easily process more than two people at once” syndrome we have now. You can force people to use one mode or the other, but then you just get unhappiness from people who prefer the other way of doing things. 
Right now, we have a lot of rooms which are barely used, yet take up considerable space. Firing range, temp detainment, the entire labor camp (both on z5, and the connecting areas on the main station), the gamma armory, heck, I’d include one of the two storage rooms in this list.
If these rooms can take up such a large amount of space doing very little, I don’t see how the processing room (possibly the most used room in the entire security section) being a bit bigger is a waste of space. OK, you could argue that it looks bad because it is “too empty”, but in that case I’d be more inclined to put in some potted plants than to shrink the room. 

I don’t see anything weird about back-to-back windoors. Yeah, it looks a bit odd if you assume windoors are sliding out of thin air, but personally when I see multiple windoors open/close together next to each other I imagine them sliding down from the ceiling, rather like translucent shutters. If you think it is really a big deal, how about replacing two of the windoors in each block with rglass windows? Would that be an improvement?

> I realize that a lot of rooms and areas are inherently square, but how you break them up, place items, and decorate them can really make it feel like it's not (for example, medbay doesn't feel like it's just one big square, when it kinda is). The brig physician feels like a small medbay with how big it is.
I don’t feel like rooms being square is a problem. Most rooms are square, or at least rectangular. In both RL and videogames. This is normal and expected, to the point that when I’m in a room that isn’t at least rectangular I notice, and consider it a little weird. 
Heck, prisons are notorious for being dull and boxy places. If there is anywhere that sort of design is called for, it is here.
The brig phys room was too small originally, I think. That said, I could shrink it slightly if the general consensus is that it should be shrunk.
Not sure how I’d better use the space, but could be done. Most likely I’d move it right a bit, eliminating a row of cells, and just turn some currently station area to space.

> I really question the need for a whopping 8 brig cells. It's rare that 4 cells are in used, let alone 6---8 is overkill in the vast majority of cases.
Fair. That was more for symmmetry, and respecting the fact that sometimes they get broken, so having spares is handy.
Deleting two isn’t a problem. 

> Just out and out removing the labor camp kinda seems like it should probably be in a different PR, to be honest. I realize it has a number of problems, as it currently stands, but just removing it, outright, comes across as a bit..wrong.
Saying it “has a number of problems” is an understatement.
As a concept, it is bad: prisoners will never survive asteroid mining, with monsters and hard vacuum, unless you give them enough gear to compete with normal miners and/or escape with. That isn’t doable.
As an implementation, it is bad: doors were not set correctly, it is a massive micromanagement hassle to deal with, and even if you do everything right it isn’t very rewarding. 
It is so bad, it has no future: the best plans I’ve seen for dealing with it (Tully’s) involve removing it and replacing it with a new, license plate stamping idea.
Given that it is broken and bad, to the point it needs to be replaced with a different system… I would argue that *not* removing it seems wrong.

> windows that don't lead to anywhere or server a purpose are not well placed windows (like next to the firing range or in permabrig).
Firing range window will be fixed.
Windows in perma between console and vendors: not a bug, they exist right now in current version.
Single window next to console outside perma: not a bug, intended so people can see into that room. Could equally be replaced with a wall, though. Do people have a preference?

> I'd recommend taking a look at both Bay and TG's brigs for overall design (though I personally think that Bay's communal brig is asking for trouble).
I did. Frankly I did not like their design.
Looking at baystation12's map at https://www.dropbox.com/s/ak3d87plhdhm5r0/map.png?dl=1 I have to say it felt bizzare. Temp and perma cells combined. Huge meeting room and another huge equipment room, with a third large lobby. Substantial firing range for no obvious reason. Perma that appears to only have a reinforced window spawner between it and the main sec lobby. There are no clear "wings", everything is mushed together. I really don't like the design of it at all. 
Looking at TGstation's map (https://dl.dropboxusercontent.com/s/ne05vcmklaunftn/Boxstation.png) I have to say it is a lot better, but it still has a really big courtroom relative to its RP level, and a really small armory with very little walkable space. I do like the cell for the defendant, though, and some other features.
Overall the main thing I take from it is: if you can't coat the walls of a room with objects, consider shrinking the room.

@FalseIncarnate Intero room has button to control polarized glass already. I will add pest spray.

Current to-fix list:
- Remove window next to firing range
- Place perma cell doors on top of their firelocks
- Add potted plants to intero room
- Remove side-by-side walls on left side of hearing room
- Apply the object/wall principle to the room design
- Add pest spray for permabrig botany

**Comment by Kyep** [comment]
@Fox-McCloud @FalseIncarnate @monster860 

Changes:
- Removed window next to firing range
- Removed window/door next to perma
- Fixed Perma Cell Doors/Firelocks appearing out of order
- Added some more objects to processing, to make it seem more filled
- Removed side-by-side walls on left of hearing room
- Added pest spray to perma
- Replaced labor shuttle console on bridge with table
- Shrunk Perma
- Shrunk number of non-perma cells
- Shrunk brigbay

Current Screenshots:
- Perma: http://i.imgur.com/sUmuMl8.png
- Processing/Intero: http://i.imgur.com/UtAxQEn.png
- Cellblock: http://i.imgur.com/jEv8pgM.png

**Comment by Faryaa** [comment]
Brig phys brigbay is good but it still could be improved:
- Make a wall mounted medicine cabinet locked with Medical access. Move all medicine from brig phys locker here. Also could use tramadol pills. Medbay have them in examination room, so brig phys could have them too.
- There is just no need in so much of roller beds. Two or three will be more then enough.
- It could be nice to make reinforced windows aimed on cell blocks, so you can observe inmates from your brigbay. Just dont forget shutters.
- Could be nice to have medical wardrobe in brigbay, so you can choose your style from the very start of the shift.
- IV drip for stabilizing people with internal bleeding while you request paramedic to arrive. Spare blood would fit wall mounted closet perfectly.
- Nitrile gloves in brig phys locker. His a MD, but have to use latex ones which tend to become dirty too fast.
The last one is debatable but:
- could use body scanner in brigbay. It would allow to check health status of patient fully and decide if the medevac to medbay is needed.

**Comment by Kyep** [comment]
Re:
- Wall-mounted medicine cabinet: why lock the stuff in a cabinet? Most of the time, there is no brig phys, and officers might need it.
- I reduced the number of beds somewhat. Mostly the reason for the number is that I assume any that actually get used won't be returned to brig medbay, so spares are required.
- I'm not actually sure about letting people in brigbay observe the cells. Doesn't that mean prisoners can observe people getting medical treatment?
- Wardrobe... not sure what other clothes you'd want.
- IV drip and body scanner were specifically discussed but the heads don't want to make medbay obsolete, so they said this remap should not include any substantial buff to brigbay. Including of new, very useful equipment would count as a substantial buff.
- Nitrile gloves... do they really make a difference?

**Comment by Faryaa** [comment]
Because officers take stuff even when there is brig phys. I dont ask to put ALL of medicine here. Left those two medkits on the table in peace. Thats more then enought for first aid. Officer also could ask warden to use sleeper on them.
Nitrile gloves are much better than latex ones. So yes, they make difference.
And all clothes availible to MD would be nice. Surgical, MD, nurse ones. Because you can play brig phys differently. You could be just a very special doctor, nurse assigned for first aid or former surgeon.

And hardly just one brig physician with small brigbay could make fully staffed medbay obsolete. Even with new equipment. Its still just one doctor.

**Comment by Kyep** [comment]
@Faryaa 
- Isn't the medicine secure in the brig phys locker anyway?
- The benefit of nitrile is that you can use them more before you have to wash them? I'm confused.
- Doesn't brig phys have access to medbay and thus can pick up those uniforms anyway?

**Comment by FlattestGuitar** [comment]
I wouldn't buff the brig medbay, that seems unnecessary.

No offense, @Faryaa, but you play brig phys very often, which likely makes you biased here.

**Comment by Faryaa** [comment]
Medicine is not secure from everyone with officer access. Why brig phys is even needed if officers will just loot your medicine even if there is active doctor? That locker is also become very cluttered because thats just the only secure locker you have in brigbay. So just one locker where all of your still unchanged medicinal supply will be - would be a useful change. 
Yes, nitrile gloves seems to be getting dirty less frequently. Thats why medical have them instead of latex ones.

And yes, Im not calling body scanner change debatable for nothing. Thats really could be powerful addition so just forget it if its really dont needed.

**Comment by monster860** [comment]
@Kyep I see a stray wire just outside the firing range, that doesn't go anywhere.

**Comment by Fox-McCloud** [comment]
Having two magnetic targets in the same area is probably not going to work.

**Comment by Kyep** [comment]
@monster860 fixed
@Fox-McCloud fixed

http://i.imgur.com/W6KNQkZ.png

**Comment by Da-Dman234** [comment]
I still feel that two vent/scrubbers aren't necessary in the interro hallway left of Warden's office. Other than that I'm slightly confused as to why the chairs are directly next to the door in each holding cell, I'd stick them next to the table just for the sake of ease when searching someone. Also am not sure about how the table near the cells only allows one person to pass at a time, could get cramped if things are busy.

Also it looks like in the isolated interro you're missing a table and the vent isn't connected to anything? Other than that I'd also add ventilation to the courtroom (Unless you intentionally left it out for some reason) and possibly add an intercom on the side the magistrate presides on.

**Comment by Kyep** [comment]
@Da-Dman234 
- Vents/scrubbers yeah, arguable. Very minor thing, though, I don't want to do a commit just for that. Nobody seems to be pointing out any other issues, though. No other issues, guys?
- The chairs are where they are so the Warden can see people in them from his position in his office. Just barely in vision range.
- The tables don't limit to one at a time - there are two doors.
- The table doesn't show in intero, but it is there.
- The vent, yeah, good catch, will change once people have given more feedback.
- Also good catch on the courtroom.

**Comment by TheDZD** [comment]
@Kyep is this in a finished state now?

**Comment by TheDZD** [comment]
image1
image2

**Comment by Da-Dman234** [comment]
DZD pointed out what I meant when I mentioned the tables, sorry for being unclear.

Also, with the interro cells, keeping them in sight of the Warden is pretty important IMO, but it doesn't make sense to put the chair right in front of the door. At the very least I think you should move the doors somewhere else and stick a table directly next to the chair so they have somewhere to put things taken off someone during a search.

**Comment by Spacemanspark** [comment]
If you look at the current permabrig, DZD, we actually already have those windows there.

**Comment by TheDZD** [comment]
@Spacemanspark True, but seriously why the fuck are they there?

**Comment by QuinnAggeler** [comment]
**I think it would be best to keep this atomic by not removing the labor camp.**
While it is undeniably bad, completely nixing it here feels outside the scale, and would make attempts to replace with something else more of a hassle (since the shuttle would have to be re-added).

**Comment by Spacemanspark** [comment]
It doesn't really seem out of scope to me, it's part of security/ the brig.

**Comment by QuinnAggeler** [comment]
Still, removing the shuttle makes replacing the outpost with something else later a bit of a hassle.

**Comment by Spacemanspark** [comment]
Probably wouldn't be terribly difficult to re-add at a later point in time.

**Comment by Da-Dman234** [comment]
If the prison camp itself isn't removed the shuttle would be fairly easy to add back in.

**Comment by Kyep** [comment]
@TheDZD 

1) Re: Finished state:
- Yes, it is finished. I may tweak/bugfix it if people report any further issues, but other then that, done.

2) Re: Hearing Room:
- Hearing room size: it is far smaller now than it was originally. I don't think it can be shrunk further and remain functional, given the number of people who'd likely want to be present for a hearing, and the necessity to for these to include cuffed prisoners who you can't walk through.
- Hearing room hallway: Changed.
- Hearing room APC/area definition: Added.

3) Re: Processing room
- Hallway-like design: Necessary. Has to have access to all 3 processing areas, both hallways, and warden's office over table. Also requires tables/chairs that don't block path. Given these constraints, not sure another design is possible.
- Bottleneck: Changed. 

4) Re: Perma
- “What even is this”: it is the perma riot gas pipe. It exists in the current map. I've replaced it with solid walls and a sealed two-tile maint area. 
- Number of cells: Deleted one cell. Moved basketball court to the left.
- “This room is a giant hallway”: Do you have suggestions for improving it? The room functions well when it is long and thin - it is helpful for using disablers, riot gas, etc. It also fits well. When it was bigger, it got complaints for being too big.


@QuinnAggeler:
- The best plans for the labor camp I've seen are to replace it. E.g: http://nanotrasen.se/forum/viewtopic.php?f=12&t=7402
- I don't see any reason to leave it mapped in.


@Da—Dman234:
- Processing dual vents/scrubbers: Fixed
- Sec main corridor dual vents/scrubbers: Fixed
- Sec main corridor dual APCs: Fixed
- Bottleneck in processing room: Changed.
- Intero table missing: It is there. It is just a reinforced table - they don't show up in DM. (where I take this screenshot)
- Intero vent not connected: Fixed.
- Hearing room not ventilated: Fixed.
- Hearing room no intercom on magistrate side: Added security intercom next to Magistrate's chair
- Moving chairs next to doors: Changed

Bonus upgrades:
- Moved Cellblock A APC so it is no longer directly on top of a screen, as it is in Paradise currently.
- Made Processing timers default to 10 minutes to help discourage Sec from holding prisoners for ages without charges.
- Renamed all the cameras in the remapped areas to be sensibly named for the AI.

All:
- Current perma: http://i.imgur.com/HvAVS8O.png
- Current processing: http://i.imgur.com/P2tP1Rb.png

**Comment by DavidRossii** [comment]
The chairs by the windoors in processing are dumb.

Because you cannot buckle them and leave at the same time without having them walk onto the chair. (And we all know how compliant traitors and shitters are at doing that)

**Comment by Kyep** [comment]
@Fox-McCloud best way to resolve the conflict?

**Comment by Fruerlund** [comment]
I've got to agree on the chairs by the windoors being really dumb. Also it seems to lack atmosphere, maybe some more objects, plants etc planted area. 

Not sure about the amount of processing rooms, I'd say scrap the last one thats furthest up north and move the interogation there. Then make a prisoner holding room below the court for the trail procedures.

**Comment by Kyep** [comment]
@Fruerlund The commit I just did moved the chairs away from the windows.

**Comment by Kyep** [comment]
Closing, as another PR recently merged into master has created a merge conflict with this. Apparently the best way to resolve merge conflicts with map files is to re-create the changes on a new PR.

**Comment by monster860** [comment]
Just use the mapmerge driver...

**Comment by Spacemanspark** [comment]
Saw "Closed" and nearly paniced.

**Pull request closed without merging**
