### PR TITLE
Craftable brass sheets

### LINKED ISSUE #12173: Clockwork floor and wall Overlay sprite Bug
**Issue Description**:

The overlay sprite for clockwork floors and walls remain after you deconstruct/remove the actual wall/floor.

**What did you expect to happen**: 

The overlay sprite causes you not to see what is beneath it or touch anything on the tile.

**What happened instead**:

Players were deconstructing to space thinking clockwork walls/floors were there or to lava because the sprite was not gone.

**Why is this bad/What are the consequences**:

Overlay issue, prevents using of the clockwork sprites at all and causes problems with the clockwork ruin on lavaland.

**Steps to reproduce the problem**:

Spawn clockwork wall/floor, try to remove it with RCD or tools.

**When did the problem start happening**:

Before the dead god ruin with ported in specifically.

**Extra information**:

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Makes Brass a realistically usable construction material for station projects, by adding the ability to create it by splashing copper onto a stack of metal, the same as some other servers have it.
Also fixes a few layering issues with the fancy construction overlays, as well as fixing clockwork walls making a space tile under them when deconstructed (especially bad on lavaland), an makes deconstructing a wall return the correct amount of brass.
Also closes #12173 because I couldn't reproduce it.

(The .dmi edit was removing a stray pixel)

## Why It's Good For The Game

Brass and clockwork structures are, in my opinion, pretty cool looking. Admittedly that's mostly because of the fancy glowing overlays they have, but brass things in general have a really unique aesthetic which I *know* a lot of people have wanted to use in their own building projects, chapels especially.
Currently the only way to get any is to go down to lavaland, hoping that not only did the Ratvar ruin spawn but also that you can find it, and then spend ages painstakingly deconstructing everything while trying to avoid the two ash drakes who always seem to spawn in the same area. That or praying of course, but from what I've seen that second option doesn't seem to be too successful.

It doesn't offer any mechanical advantage that I can see, and it looks cool so... why not make it a bit easier to get?

## Changelog
:cl:
add: Added the ability to create brass by splashing copper onto metal.
fix: Fixed clockwork walls creating a space tile when deconstructed.
fix: Fixed some overlay layering issues with brass structures.
/:cl:

### CODE REVIEW

**Review by dearmochi — APPROVED** [review]

**Comment by Spacemanspark** [comment]
Time to make robotics look even more insane whenever I run it

**Comment by Aurorablade** [comment]
I kinda wanna leave it lavaland only but...ehhhh

**Comment by Spacemanspark** [comment]
It's hardly ever touched considering it comes from a lavaland ruin that doesn't always spawn... and lord the sprites are gorgeous. We don't need to let them go to waste.

**Review by Kyep — APPROVED** [review]

**Review by variableundefined — APPROVED** [review]

**Comment by Spacemanspark** [comment]
YES
YES
YESSSS

**Pull request merged**
