### PR TITLE
no more www

### PR DESCRIPTION
**Pull request by Gyaviste**
www is for faggots

### CODE REVIEW

**Comment by Rapidvalj** [comment]
🤔

**Comment by Gyaviste** [comment]
Just press this button now and get nothing. I've fixed it

**Comment by SamHPurp** [comment]
> www is for **faggots**

C'mon , really?

**Comment by Gyaviste** [comment]
Yes

**Comment by taukausanake** [comment]
I don't want to say server rules apply on the repo, but I think language rules should? Very rude otherwise

**Comment by Aurorablade** [comment]
Server rules do apply on got. Either make your description proper, close it or have it closed.

**Comment by Aurorablade** [comment]
On git rather yay mobile

**Comment by SamHPurp** [comment]
@taukausanake playing devil's advocate = self antagging

**Comment by taukausanake** [comment]
Not until the Devil PR gets merged @SamHPurp ;)

**Comment by Gyaviste** [comment]
So, if you want to see not working links in your repo it's your deal

**Pull request closed without merging**
