### PR TITLE
Adds PDA messaging to NTSL

### PR DESCRIPTION
**Pull request by monster860**
A bit of a cherry-pick from #3953

:cl: monster860
rscadd: NTSL can now send PDA messages via the following format: pda_message(recipient, message)
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
We already have a console that can do this, tcomms doesn't need to be more abusive.

**Comment by Fox-McCloud** [comment]
>We already have a console that can do this, tcomms doesn't need to be more abusive.

Couldn't have stated it better, myself.

**Comment by monster860** [comment]
But... Scripts that make beeping noises to you when your name is spoken!

**Comment by Regen1** [comment]
>We already have a console that can do this, tcomms doesn't need to be more abusive.

What? That's only accessible by the RD and never used, also it needs the password to access it.

This is apples and oranges

**Comment by Spacemanspark** [comment]
And only the RD and AI will use this feature as well.
And "they don't use it" isn't an excuse, they can easily use it if they want to, it's not difficult (and the passcode is handed to the RD on a silver platter).

**Comment by monster860** [comment]
You forget the CE.

**Comment by Spacemanspark** [comment]
Three people out of the entire crew.

**Comment by monster860** [comment]
The message monitor console resets whatever you put in it after it sends the message.

**Comment by Spacemanspark** [comment]
And?

**Comment by monster860** [comment]
That makes it really annoying to use

**Comment by Glorken** [comment]
What bad can this PR do? It adds extra features to PDA messaging and NTSL, and the most noticeable antag uses are already available to use by the PDA Messaging Console. Mute PDA messages? On the console already. Impersonate a head? On the console already. This adds a cool possibility to NTSL without buffing antags.

**Comment by Spacemanspark** [comment]
It takes all of 30 seconds to make a new message.

**Comment by monster860** [comment]
Keep in mind, this NTSL messaging is pretty limited - It's limited to being called "Common Server" (Or whatever the server happens to be named), and it can't receive messages. Sure, you can spam the shit out of people, but that's what ahelp is for.

**Comment by Spacemanspark** [comment]
If you made it so you can't spam people I'd be fine with it.

**Comment by Krausus** [comment]
> But... Scripts that make beeping noises to you when your name is spoken!

That actually sounds like it would be fairly annoying. In fact, I can't think of a general use for this that *wouldn't* be annoying - if you'd care about a message sent over the radio, you probably heard it.

Of course, I could see this being great for blatant abuse. Spoof PDA messages anywhere, without the inconvenience of having to touch a messaging console. Listen in on any channel, without the inconvenience of needing a radio tuned to a relay channel. Or just spam the PDA of someone you don't like.

The scripting language running on the radio broadcasting equipment should probably stay limited to handling radio messages...

**Comment by fludd12** [comment]
I like the idea. I hated having to either make a new server or use a broadcast to a non-accessible channel for script feedback. 
I'd actually advocate for a slightly wider range of control, such as being able to proxy a PDA in order to make replies possible, if only because this could allow for a script to mass-PDA a department, or form chariots.

**Comment by FlattestGuitar** [comment]
Frankly, I don't think there's much potential for abuse with this feature other than spamming someone, which is already possible in so many different ways on comms and it's just not being done.

:+1: from me, but I have the same reservations as with normal tcomms - nobody will use this thing and it bloats code for the 1% of people that have a remote idea of how this works.

**Comment by monster860** [comment]
You can spam someone with an ordinary PDA.

**Comment by Spacemanspark** [comment]
Yes and if I use an infinite loop I can spam someone about as fast as a car going 999 MPH.

**Comment by PJB3005** [comment]
If you want to spam you don't need this. This is exactly what ahelp is for. You can't make everything abuse proof and you shouldn't try either.

**Comment by fludd12** [comment]
And they can just toss that PDA. Besides, the AI would fix that in an *instant*, if the RD didn't already.

**Comment by Spacemanspark** [comment]
There are ways to cut off access to tcomms for the AI/ RD.
Fairly easy with tools.

**Comment by fludd12** [comment]
The 'toss the PDA' argument still stands, this is essentially the equivalent of turning off the messaging system, anyway.

**Comment by monster860** [comment]
> ADMIN LOG: GrifferRD uploaded scripts!
> AdminHelp from NormalPlayer: "I'm getting a fuckton of PDA spam."

**Comment by Spacemanspark** [comment]
And then we get into the BoH in BoH discussion and why we shouldn't balance features with admin intervention.

**Comment by fludd12** [comment]
We don't remove multiple because they can be used to steal the Captain's ID card. The ONLY function of a bag of holding in another one is to make a black hole. This has viable use.

**Comment by fludd12** [comment]
Multitools*. I despise mobile.

**Comment by Spacemanspark** [comment]
Give me an idea of something useful this can do besides powergame/ spam/ irritate other players.
The idea Monster said above isn't a very good one, as Krausus mentioned.

**Comment by fludd12** [comment]
Subtle feedback for scripts with command interfaces, a 'ping' command for getting the attention of distracted people (looking at you, genetics), suit sensor reminders that are somewhat automated.

These are just a few.

**Comment by Spacemanspark** [comment]
The latter two is going to irritate players, mostly the suit sensors one.
The first one is alright, but I don't view it outweighing the negatives.

**Comment by Glorken** [comment]
I don't know why we keep normal NTSL if this is too abusable. As stated
earlier, only three people can readily access this, so it's not like it
would always be spammed by the greytide. If admins can regulate bombs and
normal tcomms, I don't see the issue with this.

**Comment by Spacemanspark** [comment]
I'd personally rather remove tcomms scripting entirely but I don't think that will ever happen, honestly.

**Comment by monster860** [comment]
Fun fact: Telecomms scripts can actually display images.

Admins don't like it. I got bwoinked after I made spark do the NAR-SIE thing to not put images on telecomms

**Comment by Twinmold93** [comment]
The main console for T-Comms handles regular radios signals itself. PDA's are handled on another system, if I'm not mistaken (still in T-Comms, but has it's own server). The PDA messaging server already handles these things, albeit slower. But this sounds just as an 'ease of use' thing, with a huge antag buff for the RD with fake messages from the Captain/other supervisors/fake messages from people to these people to frame them for something they haven't done. And when people admin help these things, we have to drop whatever we are doing and dig deep into the logs because we may not even get the information we need from the in game logs (fingerprints on the console does not prove a source, less the console specifically reveals to us the sender). It's not a necessary thing, and we really don't need additional things added to the telecomm scripts, people people are already hitting a point that causes lag with telecomms with the scripts they already have.

**Comment by Norgad** [comment]
I'm with spark on this one. NTSL as a whole is just a bad time.

**Comment by fludd12** [comment]
@Twinmold93 Monster already said there wouldn't be a way to set the PDA messenger's name or job.

**Comment by Glorken** [comment]
Just imagine being like,  "Siri, set a reminder to space the clown at
13:30."
This could give rise to unintelligent personal assistants.

**Comment by SpaceTimeNow** [comment]
Tcom scripts should just be canned already, everyone who tries to fool someone over radio will just get shutdown by all this stupid transmitting job titles bulltshit. Not to mention "autotranslation", i mean what the actual fuck!

It wouldn't even be so bad if traitors would actually use it, but it's allways this powergamey crap.

**Comment by TheDZD** [comment]
> We already have a console that can do this, tcomms doesn't need to be more abusive.

Pretty much this. NTSL is irritating enough as is with the things people can do with telecomms scripts, there don't need to be even more things you can do with it.

**Pull request closed without merging**
