### PR TITLE
Adds some windows to the farragus engine room

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Adds some windows to the emitter room on cere, as well as the hallway adjacent to it.
There's no worry of seeing the engine itself without mesons, you won't be able to see that far.

## Why It's Good For The Game
I feel like it's cool to be able to stand by and see a little bit more into what's going on with the engine. I feel like this gives what would otherwise be a blank hallway a bit of a chance for wonder.
This also means that if the engine starts going supernova, it'll light up the hallway, which I think is especially interesting.

## Images of changes
image
image

## Testing
Loaded in, stood around.

## Changelog
:cl:
tweak: Farragus now has some windows to see into the engine.
/:cl:

### CODE REVIEW

**Comment by Fordoxia** [comment]
What if an enterprising antagonist grabs one of the many free spacesuits from the emergency EVA lockers that are all over Farragus and then unscrews and crowbars through the two windows?

**Review by 1080pCat — CHANGES_REQUESTED** [review]
Outer windows be space facing, use grilled windows

also this cam isn't needed, more than enough cams in this area lol
image

**Comment by 1080pCat** [comment]
> What if an enterprising antagonist grabs one of the many free spacesuits from the emergency EVA lockers that are all over Farragus and then unscrews and crowbars through the two windows?

nothing stopping this on any other map :p

**Comment by Cress67** [comment]
On every other map, the Emitters are behind reinforced walls and require space EVA to reach the other side of said walls at all. On Farragus, this would allow _literally anyone_ with a screwdriver and crowbar to reach the emitters because the amount of space exposure is trivial. It'd also let them charge into the SM chamber if they wanted to, because it's all windows on the other side of the emitters too.
Farragus already has the least secure and most aggravating Engineering and Atmospheric setups, but come on man.

**Comment by lewcc** [comment]
> On every other map, the Emitters are behind reinforced walls and require space EVA to reach the other side of said walls at all. On Farragus, this would allow _literally anyone_ with a screwdriver and crowbar to reach the emitters because the amount of space exposure is trivial. It'd also let them charge into the SM chamber if they wanted to, because it's all windows on the other side of the emitters too. Farragus already has the least secure and most aggravating Engineering and Atmospheric setups, but come on man.

In my view, if you do break in, at least it's really obvious that you're doing so. It's different.

Someone mentioned possibly adding the heat-treated screws from /tg/ for this, and I might consider that

**Review by Burzah — APPROVED** [review]

**Review by S34NW — CHANGES_REQUESTED** [review]
Please use the grilles as these are space-facing windows, as 1080p suggests

**Comment by lewcc** [comment]
Changed addressed

**Review by 1080pCat — APPROVED** [review]
Changes look good.

More on the camera side of things though (this area has a comical amount of them
StrongDMM_JTKIV2Wrf1
StrongDMM_1OjC4gPirv

I removed these four cams, and had next to xero(two tiles) of cam viability removal.
I don't want this to hold up the merge, but as the area is already being touched, having these cams removed couldn't  hurt..

**Review by S34NW — APPROVED** [review]

**Pull request merged**
