### PR TITLE
Xeno Bursting no longer gibs.

### PR DESCRIPTION
**Pull request by Mitchs98**
**What does this PR do:**
What it says right on the tin. Turns out, this was simply a true/false value that was easily toggled. I did not change that, rather, I turned it to false and made bursting do 200 damage to the mob on burst. This damage is spread between the chest, groin, and arms. Technically makes no sense for it to apply to the groin, but I didn't exactly think it made sense to nuke the arms either. More realistic regardless.

This was done as one of the smaller balance changes I feel helps xenos not be unbalanced, and may even get people to like it more. One of the _major_ downsides to xenos in my opinion was the gibbing, which really makes no sense at all. It bursts out of your chest, it doesn't explode you.

**Changelog:**
:cl:
balance: Xeno Larvae no longer gibs you upon bursting.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Might wanna have a chance to cause severe internal organ damage or cause organs to be dropped outright, though with that kind of brute if a lot is taken directly to the torso it'll probably happen anyway

**Comment by Mitchs98** [comment]
> Might wanna have a chance to cause severe internal organ damage or cause organs to be dropped outright, though with that kind of brute if a lot is taken directly to the torso it'll probably happen anyway

Ideally, I'd want it to target the torso...but I'm going to have to redo how bursting is handled to do that. I may end up doing that anyway.

Or going the lazy route and having it cause severe organ damage by default/delete lungs/heart(if applicable, obviously).

**Comment by farie82** [comment]
I'd give them a lot of internal organ damage aye. Since the gibbing was brought in to stop instant revivals.

**Comment by taukausanake** [comment]
#11111  :eyes: 

Kind of glad it's a real PR but also kind of sad it's not a quality _working_ meme PR. Kind of miss Tiger now...

**Comment by Ty-Omaha** [comment]
This is pr 11111? wow what a letdown 👎

**Comment by MrMagolor** [comment]
This gives me an idea for a traitor/admin poison - like Goon's initrobeedril, except instead of turning your heart into a bee, it turns it into a xeno larva which promptly leaves your body.

**Comment by Mitchs98** [comment]
I'll be updating this to include severe organ damage soon enough. I could also up the brute damage it incurs, if people prefer that as well.

**Comment by Kyep** [comment]
I really don't see the point to this.
Okay, so you're dead in the xeno nest, but not gibbed? I still highly doubt anyone will revive you.

**Comment by KasparoVy** [comment]
The number of times I get memed to the 9th layer by xenos is not the same number of times I end up dying in their nest. I've exploded in medbay plenty of times! Though, significantly less, proportionally speaking.

**Comment by Mitchs98** [comment]
> I really don't see the point to this.
> Okay, so you're dead in the xeno nest, but not gibbed? I still highly doubt anyone will revive you.

Basically what Kasper said. And if you do die in the nest after it's cleared there's quite a high chance you'll get revived then. A lot of people don't actually burst in the nest anyway, but rather after being infected.

There most definitely is a point to this, and I personally don't really consider 'There's no point in this, you won't get revived anyway', a valid reason against it. Not meaning this in any rude way...I'm just not good at wording things, sorry if it comes off as hostile >_<.

That said. I'll get the edit for it to cause organ damage up tomorrow.

**Comment by Mitchs98** [comment]
Update:

- Damage now targets Chest, Groin, and Left and Right arms specifically.

Unless I'm just entirely blind or dumb, I see no procs that allow you to target _internal_ organs for damage, unless I make one myself. I'd rather save that for another PR if I decide to do it(provided there isn't one, and I'm just that dumb and blind), as it is outside the scope of this PR.

**Comment by Fox-McCloud** [comment]
👎 

A quick defib with a few patches isn't an appropriate response to dealing with Xeno infections.

I don't think this is the proper way to balance Xenos--Xenos losing thier queen having a major impact on them would be better.

random fact of the day: doing the surgery to remove a xeno prevents them from actually gibbing the host.

**Comment by Mitchs98** [comment]
> A quick defib with a few patches isn't an appropriate response to dealing with Xeno infections.
> 
> I don't think this is the proper way to balance Xenos--Xenos losing thier queen having a major impact on them would be better.
> 
> random fact of the day: doing the surgery to remove a xeno prevents them from actually gibbing the host.

It's not a quick patch and a defib. You will have to undergo surgery, as the way the damage is applied it causes broken bones and internal bleeding. You will still need to treat them regardless. Xeno infecting you and bursting shouldn't effectively be a permakill, it makes absolutely no sense that you gib from something eating its way out of your chest.

The fact you can surgically remove the xeno also does not negate the reasoning behind this PR or in any way add merit to the fact they should still gib you.

**Comment by Quantum-M** [comment]
You have to consider those rounds were the xenos ends up being destroyed or cut down in numbers to the point that they go elsewhere for a nest on the station, and that you would have several people pretty much out of the round because their body has been destroyed (along with anything else they had on them like suits or bags), with any chance of getting their brain implanted into a new body being minimal considering how medbay tends to be incompetence, and even more overworked with xenos about.

And if not enough ghosts is a issue, xenos tend to appear later in the round, when there's usually ghosts/observers around in good numbers.

I suggest though that the bursting should cause either the heart and/or lungs to be destroyed, so a new one should be needed.

**Comment by Mitchs98** [comment]
Of course, Fox instead of giving much valid criticism added a memetag to a perfectly valid PR. I'd prefer actual real discussion and criticism, as opposed to professionalism by a maintainer of the server.

> I suggest though that the bursting should cause either the heart and/or lungs to be destroyed, so a new one should be needed.

I could look into doing that as a substitute until I make the organ damage proc(which, I really only intend to make if this gets merged as I have no real reason to do it otherwise).

On another note. If Fox is only going to apply a meme tag after I offer a perfectly valid counterpoint, I'd very much prefer a different maintainer review this. I've been nothing but respectful and professional in this PR, I'd expect the same from staff.

**Comment by Mitchs98** [comment]
I apologize for my previous comment, which has since been deleted. As far as the organ thing, I could do that as an alternative to the organ damage proc I intend to work on if this PR gets merged. That said, as far as the tag goes. I didn't make it because I die to them, I rarely have any interaction with xenomorphs whatsoever so that's not even in the equation. Yes, me being annoyed gibbing was a thing is what led to me getting community feedback before making the PR. I drew a general consensus, and the majority agreed that gibbing was no fun for anyone involved.

This PR was made due to the fact that, while yes most servers do have it gib you, they're also faster paced and more chaotic as well as lower RP than we are. Aurora, while a HRP server that could barely be compared to ours, employs chest bursting in more or less the same way this PR does. Colonial Marines also does not have you gibbed, you can in-fact be patched up and defibbed unless something changed over recent months I've not been aware of. 

Yes, we're not Colonial Marines, it is still a viable example given they deal with xenos. It's not the norm, no. Most servers you gib, sure. But it's really no fun for the person involved in the gibbing given how vastly over-powered xenomorphs are a lot of the time. Xenos can easily be steam-rolled but on the flipside they can easily devastate the crew. They're even more powerful than Terror Spiders. There's plenty of things already that permanently remove people from the round, being permanently removed isn't generally fun for the person involved either.

We have a few ghost roles, they can observe, or merely leave. True. Those are options. But, honestly does not seem a viable counterpoint to me.

If you're worried about people being revived bodies usually aren't safe to get/usually aren't gotten until after the nest is gone/destroyed and the xenos are dead anyway. Seems perfectly reasonable for the players killed to be brought back if they wish to be/can be, rather than having to sift through a ton of gore for their brain to attempt a transplant and such for revival; which if they ghosted to be an xeno or logged out wastes a huge amount of time and medical resources, if medbay even decides to revive them at all.

With this method implemented, medical still has to do their job. And depending on how RNG favors everything it would be more or less time. More tweaks can be done to the PR if you feel it's necessary to balance them not gibbing further, as mentioned before I'm up to suggestions on what to do to improve it. Anything is better than just being gibbed.

**Comment by SkeletalElite** [comment]
I wouldn't say they're more powerful than T spiders but rather more polarizing. Xenos tend to be absolutely squashed with no hope or just steam roll with no chance of defeat. There's a lot more middle ground with terror spiders.

**Comment by Ty-Omaha** [comment]
>Colonial Marines also does not have you gibbed
>Yes, we're not Colonial Marines, it is still a viable example given they deal with xenos. It's not the norm, no. 

Colonial Marines does not gib people you are correct.

Instead, they get a massive hole in their chest that is untreatable and they are permadead.

**Comment by taukausanake** [comment]
I think I'd like the massive hole and permadeath part that CM has to be honest. I think you'd want some visual representation that they are super dead. Gibbing does that job pretty well already

**Comment by Mitchs98** [comment]
> > Colonial Marines also does not have you gibbed
> > Yes, we're not Colonial Marines, it is still a viable example given they deal with xenos. It's not the norm, no.
> 
> Colonial Marines does not gib people you are correct.
> 
> Instead, they get a massive hole in their chest that is untreatable and they are permadead.
> 
> Unless it was recently changed it was always like that way ever since I started playing on it, which was well over a year ago.

It didn't used to be that way at all, no.

And it still makes no sense to make them permadead, not really. If that's an option you may as well keep gibbing as that goes against the _entire point_ of the PR.

**Comment by taukausanake** [comment]
Isn't it permadeath because the player becomes the xeno chest burster? Can't have a human mob to return to if you're already something else. I think that's also part of why the player would gib, so the illusion that there is someone to save is gone. Unless the infected character doesn't become a xeno anymore when they burst (I honestly can't remember if that was changed) then there shouldn't be a reason to try and revive the bursted player. Maybe I'm behind on xeno edits though

**Comment by Ty-Omaha** [comment]
@taukausanake nope the player doesnt become the xeno chest burster a ghost does

**Comment by Fox-McCloud** [comment]
>@taukausanake nope the player doesnt become the xeno chest burster a ghost does

Yes and no.

If there's no ghosts to pull from, the person does become the xeno.

**Comment by Ty-Omaha** [comment]
the larva burry into the ground now if nobody can take them

**Comment by Fox-McCloud** [comment]
the majority of heads and maintainers oppose this PR. We do not feel this pushes Xenos in the direction they need to go. Perhaps a better approach would bet tying the Xenos closer to their queen (this doesn't necessarily mean physical proximity).

We want the xeno numbers to increase over time and not just have players waiting around forever in the hopes that they get revived---all the while the xeno population stays stagnant.

**Pull request closed without merging**
