### PR TITLE
Inform ghosts of deaths

### PR DESCRIPTION
**Pull request by SamHPurp**
Helps keep the ghosts up to speed with things going on.

:cl: Purpose
add: Ghosts now get a notification when someone dies.
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
This definitely needs to be a preference or it's gonna be irritating as shit to admins.

**Comment by Kyep** [comment]
Suggestions:
- Include the name of the area they died in. E.g: "Captain McNewbie has died in the Bridge. (FLW)"
- Consider making it work for non-humans. I can think of some other mobs that it would be worth notifying about if they died (such as the AI)
- Make the message different if they suicide. It will avoid 'this guy died in the middle of nowhere... how did he die?'

**Comment by SamHPurp** [comment]
@tigercat2000 added the preference requirement for deadchat to show, mirroring TG's preference option.

@Kyep this now shows the area. If people start memeing it with suicide etc, then maybe we'll look at adding, but I don't think its needed.

**Comment by KasparoVy** [comment]
Aint there a way to check if a mobs got a ckey then just sgow notifications on death for that?

**Comment by Crazylemon64** [comment]
@KasparoVy It already does a `mind` check, so ckeyless mobs won't get announced (unless fsr you are concerned with SSD deaths being announced?)

**Comment by KasparoVy** [comment]
Left my brain at home, my bad

**Comment by SamHPurp** [comment]
If this merges, I'll probably extend this format to other things.... like Events triggering.... the result of E20 dice rolls.... any other ideas?

**Comment by tigercat2000** [comment]
@SamHPurp If you want to extend this any further, it absolutely needs it's own preference flag, not just tacking onto deadchat being enabled 😛

**Comment by SamHPurp** [comment]
@tigercat2000 if you're not interested in deadchat, you're not interested in these events... This is how TG-code handles these too. Ehhhhh I'd reaaaally rather not add -yet another- preference.... Para Preferences already feel super bloated.

**Comment by Bram961** [comment]
@SamHPurp as Tiger said the problem is log clutter for admins (things already require you to learn speedreading as is) Admins need to have the possibility of monitoring dchat without the extra clutter of death notifications.

**Comment by KasparoVy** [comment]
Might be wise to implement a prefs/verb search feature at some point ahaha. I wonder if that's even possible.

**Comment by variableundefined** [comment]
@SamHPurp Please address our concern - We need a separate preference option.

**Comment by variableundefined** [comment]
Please re-open the PR when the issue is resolved, a compelling argument can be made on why a preference is not needed, or a better solution is found.

**Pull request closed without merging**
