### PR TITLE
cere: Add transit tubes between cargo/medbay/evac maints

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
This PR adds two transit tube lines on Cerestation. They connect the maintenance tunnels between the Supply, Medbay, and Evac asteroids. This PR is localized to those asteroids because redirecting maints on other asteroids will be more complex, and due to other mapping efforts on other asteroids that need to be coordinated. For now I'm using the standard tube stations; depending on feedback (if people get frustrated with pod turnaround time) I may turn them into dispenser stations, but that would have to wait for #24045.

Transit tubes aren't used in mapping outside AI sat, so there's no super clear mapping standards for them. I'm adhering to the rules that they should not be placed in walls or rock, and, for now, should always be routed through space.

While the maint tunnels are still a little cluttered and it may be initially hard to find these, I was able to reliably navigate to them within a half dozen attempts.

## Why It's Good For The Game
A consistently mentioned Farragus issue is deadends in maintenance, and a major source of this is due to the noncontiguous asteroids. This attempts to be a minimally invasive fix for a few of them. It really remains to be seen if this is an effective solution, but I think it's worth a shot.

## Images of changes
Large images to include nearby hall/maintenance context.

2024_02_18__19_44_31__paradise dme  cerestation dmm  - StrongDMM

2024_02_18__19_44_57__paradise dme  cerestation dmm  - StrongDMM

In-game, observing:

2024_02_18__19_56_51__Paradise Station 13
2024_02_18__19_57_00__Paradise Station 13
2024_02_18__19_57_10__Paradise Station 13
2024_02_18__19_57_16__Paradise Station 13

## Testing
Spawned in, rode tubes.

## Changelog
:cl:
add: Farragus: Supply, Medbay, and Evac maintenance tunnels are connected via transit tube.
/:cl:

### CODE REVIEW

**Review by 1080pCat — COMMENTED** [review]
Recon you could add some lattices under the tubes to be more inline with how it is on the other maps to the ai sat?

Also im not the biggest fan of this spot here, as it clips into the rock.
image

on the cargo to med maints tube, you have four crossings all butted up, but then on the med to departures one, you have them much more spaced out.
image

also this crossing pipe is kinda useless
image

**Comment by warriorstar-orion** [comment]
> Recon you could add some lattices under the tubes to be more inline with how it is on the other maps to the ai sat?
> 
> Also im not the biggest fan of this spot here, as it clips into the rock. image
> 
> on the cargo to med maints tube, you have four crossings all butted up, but then on the med to departures one, you have them much more spaced out. image
> 
> also this crossing pipe is kinda useless image

Took a shot at addressing these, PTAL

2024_02_21__02_16_22__paradise dme  cerestation dmm  - StrongDMM
2024_02_21__02_17_15__paradise dme  cerestation dmm  - StrongDMM

**Review by 1080pCat — APPROVED** [review]
Could maybe continue the latices out like this, but otherwise it looks pretty good
 
image

**Comment by warriorstar-orion** [comment]
> Could maybe continue the latices out like this, but otherwise it looks pretty good
> 
> image

Good idea, added

**Review by Henri215 — APPROVED** [review]
Lewcs good to me

**Review by S34NW — APPROVED** [review]

**Pull request merged**
