### PR TITLE
Adds Blueshield, NT Rep, and Brig Physician skirts

### PR DESCRIPTION
**Pull request by Xantholne**
Adds three new skirts available in the loadout menu with the appropraite job restriction.

New skirts made to be more skirtsy and less shortsy
f6b8f55aee5f2da4c6f66c5b283aaf35

🆑  Xantholne
rcsadd: Adds a Blueshield, Nt Rep, and Brig Physician skirt available in the loadout menu.
/🆑

### CODE REVIEW

**Comment by KasparoVy** [comment]
Thanks for keeping up Vox sprite parity, much appreciated

**Comment by Xantholne** [comment]
It wouldn't be appropriate to make something that not all races can wear properly.

**Comment by granodd** [comment]
The blueshield one reminds me of all those pictures of anime girls in skirts but carrying around tactical equipment. But I won't try to stop fashion.

**Comment by deep-fried-faceplant** [comment]
The blueshield's skirt looks like a pair of shorts, and doesn't go very well with the shirt. The blueshield already has a jacket, why not give them a suit for formal wear? A skirt for a bodyguard doesn't seem very fitting.

**Comment by scrubmcnoob** [comment]
Do all the other skirts look like these models? They kind of look like shorts. Maybe I have not been paying attention to the other skirt sprites.

**Comment by Xantholne** [comment]
Skirts vary from skirt to skirt. Some have flanels some are a pattern.

**Comment by deep-fried-faceplant** [comment]
They look too straight, like pencil skirts. Perhaps making the sprite slightly​ bell shaped would help.

**Comment by Xantholne** [comment]
Gave the skirts a more fringey look so they're less shorts like.

**Comment by scrubmcnoob** [comment]
bueno

**Pull request merged**
