### PR TITLE
Seed Mutation Mutation Chems Removal

### PR DESCRIPTION
**Pull request by Fox-McCloud**
I'm sorry, but having a single plant harvest thrown at you and you win up beocoming a slime or shadow species isn't fun, fair, or balance to fight or deal with, especially for the mass levels of produce that can be generated once the reagent is found. It's just suddenly "oh, I'm this, and there's nothing I can do about it for the rest on the round".

finally fixes https://github.com/ParadiseSS13/Paradise/issues/2439

### CODE REVIEW

**Comment by Mijhead** [comment]
First of all, the title is redundant. The mutation chems are not from plant mutations, they are from strange seeds.

Second of all, you do realize that in the time that it takes for botany to both get the seeds from cargo, decode the genes so they can actually do something with the genes, AND actually roll the dice correctly so that of the -two- seeds per crate that they get from cargo, one of them actually has either chemical, xenobiology could already have green/black slimes? Hell, even if they don't, at that point they have access and potential access to a -lot- more stuff to use, such as the chemlab, R&D, toxins and other slime colors, such as gold?

 And it's not as if you need a lot of the reagent to fuck shit up, so what makes it acceptable for xenobiology, who can accomplish it WITHOUT having to rely on others, and has access to many more tools, to have this, whereas botany, who HAS to rely on others do their work, ALSO has responsibilities to do besides fucking around with the strange seeds, ie. grow plants for the chef, and DOESN'T have all those other tools to mess around with, not have them? The sudden "Oh, I'm this, and there's nothing I can do about it for the rest of the round" applies just as much to xenobiology, in your example.

This is also pretty reminiscent of the "dead pls nerf" thing often said, and it'd probably be well if you actually put some research into what you want nerfed, and trying it out yourself.

**Comment by Spacemanspark** [comment]
:-1:

**Comment by tigercat2000** [comment]
Normally, I would say something like "no more balance please"
However, jesus fucking christ, @Spacemanspark @Mijhead I don't ever want to fucking see multiple security staff, the HoS, and multiple crew members screaming bloody murder because a dumbass botanist managed to get his fucking hands on slime juice. I don't know which fucking staff would.

**Comment by Mijhead** [comment]
Then maybe the xenobotany equipment shouldn't've been put in botany, but kept back in science?

**Comment by Fox-McCloud** [comment]
The difference is, Xenobio can do that and then they would have to do something very explicitly to get that toxin into someone.

Those plants can literally be put onto things iwth the stinting trait and pumped out like no tomorrow. Was there luck in getting there? Yes. Was there skill? Yes. 

That said , someone just throwing a practically unlimited source of things and people and all of a sudden bam shadow person/slime for the rest of the round is neither fun for the person on the receiving end of it or really fair.

With Xenobio, supplies for that are much more limited and delivery methods are much less patterned around mass production or mass usage.

**Comment by Mijhead** [comment]
I understand your concerns, @Fox-McCloud and I'd like to suggest perhaps seeing if the code from https://github.com/ParadiseSS13/Paradise/pull/1002 could be used again; most of the codingwork has already been done, courtesy of @Iamgoofball , and it would be simple to add the mutation chemicals to the blacklist, dealing with both the concerns of "Unlimited immediate shadowman/slime" and with botany having to rely entirely on other departments do actually start doing anything with their genetical equipment, without removing the reliance entirely.

Oh, and maybe the "Juicy" trait would be a more suitable trait to use in your example, it's both easier to acquire and safer to use.

**Comment by Regen1** [comment]
>This is also pretty reminiscent of the "dead pls nerf" thing often said, and it'd probably be well if you actually put some research into what you want nerfed, and trying it out yourself.

Yeah I feel that this is more of a hugbox thing, and if a botanist did this without being a traitor, why are they not banned yet.
This would be amazingly fun when being a traitor botanist with escape alone objective.

**Comment by FreeStylaLT** [comment]
So we have plants able to spread infinitely and also able to forcefully turn you into a different, possibly debilitating, species with no way to counter them other than avoiding the area that is getting larger indefinitely.

I would rather not have something like that a possibility on the server, either remove the chems or make the plants unable to transmit their reagents through hardsuits, biosuits or anything of the sort. Even the singularity has magboots to somewhat counter one of its aspects, I do not see anything of that sort here.

**Comment by Mijhead** [comment]
They're not uncounterable, all you need to do is grab a hatchet/scalpel/goat/scythe to cull it.

**Comment by ZomgPonies** [comment]
Might want to tag this controversial

**Comment by Earthdivine** [comment]
>Not uncounterable

But you can't really get near them without them injecting you, as it ignores suits appearently.

The whole Xenobiology needs to be looked at far more then just a small slap like this, quite honestly.

**Comment by FalseIncarnate** [comment]
I plan on reviving the long abandoned chem blacklist PR that goofball started as a bare minimum of some of the changes to botany I'd like to do within the next week or two. The mutation chems would definitely be on said blacklist, though I may create an adminbuse seed that is contains them (would likely be unable to be mutated like diona nodes are) so they could be somewhat safely used for event stuff.

I plan (a little more long term probably) to look into finally fixing the infinite spread of vines, and possibly buffing the effectiveness of scythes in clearing them, as they don't seem as effective as they used to be. This is likely going to take longer since it is a bit more delicate, but is something I've been intending to correct for a while.

**Comment by Robertha89** [comment]
you got grenades that stops vines pretty hard, and scythes cut like 1x3 area per click.

**Comment by FalseIncarnate** [comment]
Scythes don't reliably cut that though, i've had to spam click sections sometimes over 10 times before it finally cleared anything. When they DO work though, yes, they are great.

Weed killer grenades are by far the fastest, but have the nasty side-effect of killing diona and poisoning everyone else that gets caught in it.

**Comment by Robertha89** [comment]
weed killer grenades should not be lethal to humans at all? and the reason you clicked it ten times to work, is cause you missed 9 times, check how syringes work regarding clickability, or just make scythe clear the area, irregardless of you clicking the vines or not, which is a problem, even so, every time the crew goes against the vines, they managed to destroy almost all of them before cargo can even get 2 weed crates.

**Comment by Mijhead** [comment]
@FalseIncarnate , I've personally never had that issue with scythes, they've always worked cleanly for me in decimating event-vines.

**Comment by FalseIncarnate** [comment]
I've had it happen, though it is possible that it was cutting through an actual plant before it hit the vines (this does make a difference and is a possibility), so could be just be they could use a buff vs plants.

As for weed killer grenades, they create atrazine smoke, and atrazine is toxic (though not necessarily lethal in small doses) to humans. For those of you who aren't sure what this chem is, it is the contents of the plant-b-gone bottles, and is intended to just kill plants rapidly, but also will ruin the days of any diona / diona nymphs hit by it.

**Comment by Mijhead** [comment]
Yeah, I believe you were hitting the plant instead of the vine, because hitting a vine has always annihilated it in my experience.

**Comment by TheDZD** [comment]
Not particularly fond of the fact that these can utterly destroy entire rounds by turning a large number of players into xenobio slimes/shadow people on a fairly massive scale. Xenobio has access to both of these chems, but they are fairly difficult to get a hold of, and they don't have a convenient way of injecting unlimited amounts of this into the entire station.

I do admit that I absolutely *abhor* the current botany genetic system as a whole, because of how ridiculously grindy, RNG-heavy it is, and how ridiculously powerful it can get if somebody either puts in a huge amount of time, or gets incredibly lucky. It is fairly reasonable that players should be rewarded for investing effort into something, there do have to be limits. Going to hold off another day before merging this, unless @FalseIncarnate is planning to get a different fix in for this by then.

**Comment by FalseIncarnate** [comment]
Go ahead and merge this, I won't be able to do any significant work by tomorrow because of work and existing plans, and this doesn't seem insignificant enough to put off until the blacklist is done

**Comment by Mijhead** [comment]
Yeah, I was mostly concerned that botany would've just been nerfed without anything done to actually improve on it, but those concerns are largely gone now. I'm for merging this.

**Comment by Mijhead** [comment]
Also, @TheDZD , just to say; It's not fairly difficult for xenobio to get ahold of these chems, they don't have to rely on other departments for it either, and once they have them, if R&D has been working, they could have an upgraded processor already, giving them more cores per slime, R&D can produce syringe guns, robotics can produce odys, which can scan these reagents and make unlimited amounts too, with a syringe gun to boot, so they -do- have convenient ways of injecting unlimited amounts of this into the station.

**Pull request merged**
