### PR TITLE
Allows IPC Assistants to benefit from Hooch too

### PR DESCRIPTION
**Pull request by WenlockTheBritishHobo**
## What Does This PR Do

Changes the Hooch healing so it works for IPC Assistants too, also causes IPCs to be able to get drunk from Hooch.

## Why It's Good For The Game

Similar reason to https://github.com/ParadiseSS13/Paradise/pull/26533, the drink heals based on gimmick rather than being organic, so it would be fixing an oversight.

## Testing

Spawned in as an Assistant Drask, dealt brute and burn to myself, drank Hooch, watched myself get healed and become tipsy.

Spawned in as an Assistant IPC, dealt brute and burn to myself, drank Hooch, watched myself get healed and become tipsy.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: Hooch now also heals IPC Assistants and affects them as other IPC alcohols do.
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
Hooch has no synthanol component, so why should IPCs be getting drunk off it?

Also IPCs just generally should not have drinkable regen liquids, passive regen on them isn't needed with how fast they are to fix.

**Comment by WenlockTheBritishHobo** [comment]
> Hooch has no synthanol component, so why should IPCs be getting drunk off it?
> 
> Also IPCs just generally should not have drinkable regen liquids, passive regen on them isn't needed with how fast they are to fix.

I couldn't really figure out how to not cause the drunk effect, though there is welding fuel in the recipe so that has something. I might see about the drunk effect on IPCs if possible though.

It heals based on job gimmick since it only healed assistants already, https://github.com/ParadiseSS13/Paradise/pull/26533 allows IPC Clowns and Mimes to be able to heal with their drinks as their drinks heal based on job gimmick.

**Comment by Coolrune206** [comment]
> I couldn't really figure out how to not cause the drunk effect, though there is welding fuel in the recipe so that has something. I might see about the drunk effect on IPCs if possible though.
> 
> It heals based on job gimmick since it only healed assistants already, #26533 allows IPC Clowns and Mimes to be able to heal with their drinks as their drinks heal based on job gimmick.
Clowns and Mimes are a lot more goofy and are also solo-jobs, unlike assistants. Honestly allowing IPC Clowns and Mimes to benefit from that is questionable too but it was considered to be an oversight so it is what it is. I'm no member of the design team, but Hooch only affecting organics doesn't seem much like an oversight to me.

**Review by PopeDaveThe3th — APPROVED** [review]

**Comment by WenlockTheBritishHobo** [comment]
Comments from design regarding the PR:
> Again what is the purpose of a robotic race if mechanically they react to things just like an organic.

>I am fine with magic chemicals (holy/unholy), admin, antag parity chemicals, and clown / mime ones, hooch however seems silly.

Ultimately, lost the vote 2 for to 3 against.

**Pull request closed without merging**
