### PR TITLE
christmas cheer

### PR DESCRIPTION
**Pull request by thatdanguy23**
## What Does This PR Do
As requested by @FreeStylaLT , I humbly offer my Christmas-themed Cyberiad for this year. Literally only makes aesthetic changes.
EDIT: now adds "snow" as a structure that can be welded away, like alien weeds. technically a code change, but works fine and shouldn't fuck with anything else.

## Why It's Good For The Game
It's for the holiday tradition.

## Images of changes

Cargo & Locker Room
image

Central Primary Command
image

Dorms & Bar
image

I don't want to give away _too_ much  of what I've added with these pictures, so I'll leave it at these - but if you want me to send you screenshots privately, or if you want to dive into the .dmm to ruin the surprises, feel free!

This is, of course, totally up to any other map editor to add whatever they like, but this is my attempt!

## Changelog
:cl: thatdanguy23
add: added christmas cheer
del: removed bad vibes
/:cl:

### CODE REVIEW

**Comment by fionalokhert** [comment]
I am Karri and I would love this, if only the tinsel would stick like it used to for decorations! (Plus it might save her a bit of time on her decoration rounds!)

**Comment by matttheficus** [comment]
as a note, a lot of bartenders enjoy setting up their bars, perhaps leave them some of the decorations to put up without there being anything they cant move/design as they wish?

**Comment by KasparoVy** [comment]
Happy holidays yall. Haven't played here in a bit but best wishes to u folks on the holidays, stay safe

**Comment by thatdanguy23** [comment]
> as a note, a lot of bartenders enjoy setting up their bars, perhaps leave them some of the decorations to put up without there being anything they cant move/design as they wish?

Good idea, actually. Might leave a cardboard box somewhere for them. Maybe with the decoration materials instead of just the decorations themselves.

**Comment by SteelSlayer** [comment]
The warden's office snow seems to be missing the frilly edges:

image

**Comment by thatdanguy23** [comment]
> The warden's office snow seems to be missing the frilly edges:
> 
> image

good catch thank you, fixed now

**Review by AffectedArc07 — APPROVED** [review]
SM port will be made around this

**Comment by Darkmight9** [comment]
Glad to see my decorations getting used 😄

**Review by Kyep — APPROVED** [review]

**Pull request merged**
