### PR TITLE
remap: Farragus Cargo.

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do

This PR remaps the Cargo Asteroid on Farragus, merging it with Medbay Asteroid. In doing so it attempts to address many issues with the department and asteroid design.

### Primary Features

**Much larger Cargo Bay**: Farragus Cargo Bay is excessively cramped, with not even enough room to have long conveyor belts. It has been expanded in size.

**Much larger everything**: Every room has increased in size. Expedition no longer needs to move lockers to access tank storage, QM's office now can fit all three expected computers, the number of stationside mining lockers has been increased, the lobby is more spacious, and so on.

**Dedicated Cargo Break Room**: An isolated area for supply crewmembers to hang out and complain about the QM.

**Public area and storefronts**: The hallway now provides a small public area as well as two storefronts for crew to use.

**Auxiliary Tool Storage**: The Cargo hallway now includes an Auxiliary Tool Storage room.

**Shortened hallway**: The size of the U-bend in between Cargo and Medbay has been shortened.

**Unified quantum pad station**: Medbay and Cargo's quantum pads have been moved into a single room allowing access to Security, Service, Science and Evac.

### Other Changes

Separate areas for the Cargo Break Room, Warehouse, and the Storefronts have been added. New icons have been added for the Break Room and Warehouse, as well as the Cargo Lobby and Mail Room.

A handful of new floor color combinations have been added for the Quantum Pad room.

## Why It's Good For The Game

<details>
<summary>Design Considerations</summary>

The design issues this PR addresses/considers:

- Cramped Cargo Bay: self-explanatory.
- Maints connectivity: maintenance now wraps around the entire asteroid, as well as Medbay and Cargo individually. This helps maints flow better as well as gives antags more options during pursuit, while giving sec more opportunities to flank suspects.
- Boring hallway traversal: giving crew an area to socialize, two places for storefronts/crew activity, as well as visibility into expedition, space, and the cargo shuttle help increase variety and opportunity for crew interactions. I've added a handful of windows to the supply shuttle itself as well.
- Lobby/Office layout: The Lobby and Office have a "staggered" separation because it helps to separate the space. It creates an alcove for the front desk line and order console and puts the ORM on a horizontal wall so that the sprite direction matches. It also allows most of the wall to be windows while using one of the corner walls to place the noticeboard. It also gives the office more horizontal lines to place lots of tables and machines (such as the north wall). I imagine people might take or leave the railing but Cargo is one of the most crew-renovated areas on the station.

</details>

<details>
<summary>Balance Considerations</summary>

The balance issues this PR addresses/considers:

- Maints-facing APCs: All APCs touched as part of this remap now face inwards, due to the many issues with maint-facing APCs (Malf and biohazard balance, ease of crew access, issues with radstorm tiles)
- Nukie-Cargo access: it is easy for nukies to access/bomb the cargo bay via solars, which puts them within a few tiles distance of the bay.
- Crew viewing illegal crates being delivered: marking this down to note that I did consider this, but I don't think it's that big a deal. In all honesty, illegal crates should probably be made inconspicuous in some way regardless.
- Easy access to break into Mining: Mining faces maints, allowing easy access to people who want to break in.
- Escape via disposals: if an antag or whoever survives the disposals ride through space, they can get out of the Mail Room and abscond into maints very quickly.

</details>

## Images of changes

<details>
<summary>SDMM</summary>

StrongDMM-2024-07-17 00 16 00

StrongDMM-2024-07-17 00 16 10

StrongDMM-2024-07-17 00 16 43

StrongDMM-2024-07-17 00 17 06

StrongDMM-2024-07-17 00 16 57

</details>

<details>
<summary>AI Visibility</summary>

2024_07_17__00_18_43__Paradise Station 13

2024_07_17__00_18_50__Paradise Station 13

2024_07_17__00_18_58__Paradise Station 13

2024_07_17__00_19_12__Paradise Station 13

2024_07_17__00_19_19__Paradise Station 13

2024_07_17__00_37_41__Paradise Station 13

</details>

<details>
<summary>In-Game</summary>

2024_07_17__00_42_45__Paradise Station 13

2024_07_17__00_42_57__Paradise Station 13

2024_07_17__00_43_12__Paradise Station 13

2024_07_17__00_43_18__Paradise Station 13

2024_07_17__00_43_34__Paradise Station 13

2024_07_17__00_43_45__Paradise Station 13

2024_07_17__00_44_00__Paradise Station 13

2024_07_17__00_44_21__Paradise Station 13

2024_07_17__00_44_40__Paradise Station 13

</details>

## Testing

Most of these have been tested already but I want the whole list here in case I'm missing anything.

- [x] Airlock names
- [x] Airlock access
- [x] Shutters access: Mining
- [x] Shutters access: Warehouse
- [x] Shutters access: Emergency EVA
- [x] Quantum Pads
- [x] Solars powernet
- [x] Starboard Maints SMES and Power Monitor
- [x] Disposals: Other departments to trash
- [x] Disposals: Other departments to Cargo outlet
- [x] Disposals: Other departments to QM outlet
- [x] Disposals: Tagged mail to other departments
- [x] Disposals: Trash to Disposals
- [x] Camera visibility
- [x] Camera names and networks
- [x] Cargo and mining shuttles
- [x] Mulebot nav out of Cargo
- [x] Conveyor switches: Bay, Mail Room, Disposals
- [x] Ancient rock perimeters
- [x] Department Inventory
- [x] Maints loot
- [x] Exterior airlock canisters
- [x] Lockdown shutter names, position, access
- [x] Supply shuttle status displays
- [x] Firelocks and toggles
- [x] Holopads
- [x] Prisoner tube
- [x] Shuttle docking
- [x] Electrochromic windows

## Changelog

:cl:
add: Farragus: the Cargo department has been remapped, and its asteroid merged with Medbay's.
add: Farragus: the Cargo department now has a break room.
add: Farragus: there is auxiliary tool storage between Cargo and Medbay.
add: Farragus: two vacant crew storefronts are available across from Cargo.
tweak: The Cargo Shuttle now a few windows on its port side.
/:cl:

### CODE REVIEW

**Comment by autocephalophagy** [comment]
Where does this leave the psych office?

**Comment by warriorstar-orion** [comment]
> Where does this leave the psych office?

Between the CMO's office and Medbay lobby:

StrongDMM-2024-06-26 12 40 34

**Comment by Denthamos** [comment]
On the wall shown here between the QM office and the mining room, I would suggest a reinforced and electrified window of 1 tile or more so the QM can see into the mining dock.
image

**Comment by Denthamos** [comment]
This area here also feels like it could use a bit more theme to it to make it fitting of an abandoned area of cargo or mining.
image

**Comment by warriorstar-orion** [comment]
@Denthamos 

> On the wall shown here between the QM office and the mining room, I would suggest a reinforced and electrified window of 1 tile or more so the QM can see into the mining dock. image

Done:

2024_07_01__18_11_34__paradise dme  cerestation dmm  - StrongDMM


> This area here also feels like it could use a bit more theme to it to make it fitting of an abandoned area of cargo or mining. image

Decorated a bit more here:

2024_07_01__18_07_57__Paradise Station 13
2024_07_01__18_11_59__paradise dme  cerestation dmm  - StrongDMM

**Review by S34NW — CHANGES_REQUESTED** [review]
delwedd
Maybe you could fill the railing gaps in like this so it's obvious the gap is intentional?

delwedd
Pipes run into nothing at AI sat entry

delwedd
Gorilla stole the scrubber (there's also no vent in this room, it needs one)

delwedd
Scrubber pipe missing here

delwedd
missing manifold and pipes here

delwedd
random door pipes

delwedd
no vent/scrubber in cargo tele room

delwedd
gorilla stole cargo bay airlock access helpers on these doors

**Cargo is missing a cargo telepad `/obj/machinery/telepad_cargo`**

**Review by 1080pCat — CHANGES_REQUESTED** [review]
You've used grilled windows for every window, including non-space facing windows.

Mining dock appears to be missing an air alarm

The recycler room lacks a tiny fan, or air vents to refill the lost air from using the mass driver.
Also the sheet stacker lacks its console

All three of these doors are named "medbay SMES access"
image

This area feels really bland, i think adding some grills and or girders to 'cut up' the straight uninterrupted line would do good
image

The delivery office could use another light by the outlet
image

Same with the cargo bay. its very dark with night shift on
image
two lights added by the table, and camera helps alot
image

The cargo lobby and shop area could use some intercoms
image
should probably add one here too
image
and here
image

The last solar array has a wire going to nowhere
image

The psych office has firelocks over the windows. Something i personally like, but its inconsistant
image

This area(outside psych) could also use a fire alarm, as it currently lacks one.
image

These doors lack firelocks
image

Cargo break room lacks fire locks
image

The cargo office lacks fire alarms

The first tiny fan at the mining dock could go, as its redundant
image

And finally, the store front could use some fire alarms, and locks. as its not really maintenance.

**Comment by 1080pCat** [comment]
Oh also, add to the CL/images of changes that you've slightly edited the cargo shuttle

**Comment by warriorstar-orion** [comment]
> You've used grilled windows for every window, including non-space facing windows.

Fixed, here's the filtered view of the new non-grilled window placements:

2024_07_17__00_03_11__paradise dme  cerestation dmm  - StrongDMM

> Mining dock appears to be missing an air alarm

Fixed:

2024_07_17__00_04_11__paradise dme  cerestation dmm  - StrongDMM

> The recycler room lacks a tiny fan, or air vents to refill the lost air from using the mass driver. Also the sheet stacker lacks its console

Fixed, I've pulled a vent down from the north and added the sheet stacker, rearranging it so it properly gets fed from the conveyor:


2024_07_17__00_48_51__paradise dme  cerestation dmm  - StrongDMM


> All three of these doors are named "medbay SMES access" image

Fixed:

2024_07_17__00_04_40__paradise dme  cerestation dmm  - StrongDMM

2024_07_17__00_04_45__paradise dme  cerestation dmm  - StrongDMM

2024_07_17__00_04_48__paradise dme  cerestation dmm  - StrongDMM

> This area feels really bland, i think adding some grills and or girders to 'cut up' the straight uninterrupted line would do good image

I've spiced this up a bit, adding some grills/girders as you suggested, added some more litter/detritus, and made the path serpentine a little bit. The SDMM version and one with just the floors to see the shape of the path:

2024_07_17__00_51_03__paradise dme  cerestation dmm  - StrongDMM

2024_07_17__00_51_18__paradise dme  cerestation dmm  - StrongDMM

> The delivery office could use another light by the outlet image
> 
> Same with the cargo bay. its very dark with night shift on image two lights added by the table, and camera helps alot image

I've added lights to these areas as well as the cargo office. Night mode versions:

2024_07_17__00_22_17__Paradise Station 13

2024_07_17__00_22_25__Paradise Station 13

2024_07_17__00_27_06__Paradise Station 13

> The cargo lobby and shop area could use some intercoms image should probably add one here too image and here image

Fixed, new intercom placements:

2024_07_17__00_54_37__paradise dme  cerestation dmm  - StrongDMM

> The last solar array has a wire going to nowhere image

I've flipped these all around so they face the controller:

2024_07_17__00_55_51__paradise dme  cerestation dmm  - StrongDMM

> The psych office has firelocks over the windows. Something i personally like, but its inconsistant image

Fixed:

2024_07_17__00_06_40__paradise dme  cerestation dmm  - StrongDMM

2024_07_17__00_06_45__paradise dme  cerestation dmm  - StrongDMM

> This area(outside psych) could also use a fire alarm, as it currently lacks one. image

Fixed:

2024_07_17__00_56_38__paradise dme  cerestation dmm  - StrongDMM

> These doors lack firelocks image

Fixed (with airlocks hidden):

2024_07_17__00_57_49__paradise dme  cerestation dmm  - StrongDMM

> Cargo break room lacks fire locks image

Fixed:

2024_07_17__00_06_57__paradise dme  cerestation dmm  - StrongDMM

> The cargo office lacks fire alarms

Fixed:

2024_07_17__00_59_10__paradise dme  cerestation dmm  - StrongDMM

> The first tiny fan at the mining dock could go, as its redundant image

Fixed:

2024_07_17__00_07_07__paradise dme  cerestation dmm  - StrongDMM

> And finally, the store front could use some fire alarms, and locks. as its not really maintenance.

I've outfitted these with all the normal room bumps and atmos:

2024_07_17__01_00_43__paradise dme  cerestation dmm  - StrongDMM

> Oh also, add to the CL/images of changes that you've slightly edited the cargo shuttle

I've added the cargo shuttle screenshot and updated every screenshot in the description.

**Review by 1080pCat — APPROVED** [review]
Only this window being grilled as an issue
image

Aside from that, looks good to me. Cant wait for cargo to become a solar storm death box

**Review by S34NW — COMMENTED** [review]
delwedd
This junction is var-edited as opposed to using the `y` subtype

**Comment by S34NW** [comment]
There's also a bunch of segment pipes that should be the `corner` subtype

delwedd

**Comment by warriorstar-orion** [comment]
> There's also a bunch of segment pipes that should be the `corner` subtype
> 
> delwedd

Fixed, and var-edited junction fixed.

**Comment by warriorstar-orion** [comment]
Sec telepads have been updated, removing the defunct medbay one and arranging the signs.

2024_07_25__16_26_08__paradise dme  cerestation dmm  - StrongDMM

**Review by S34NW — APPROVED** [review]
Update for merge

**Review by S34NW — CHANGES_REQUESTED** [review]
After further discussion internally, it's generally agreed that the APC move needs to be done station-wide at once, not per department, so as to avoid confusion.
Please move them back for now and we can follow up later with a station wide change.

**Comment by warriorstar-orion** [comment]
The following APCs have been pulled into maints:

- Cargo Bay
- Mail/Delivery Room
- Cargo Bay Warehouse
- Mining Dock
- Quartermaster
- Disposals
- Cargo Break Room
- Auxiliary Tool Storage
- Cargo Quantum Pads
- Fore East Hall

2024_07_30__13_58_36__paradise dme  cerestation dmm  - StrongDMM
2024_07_30__13_58_43__paradise dme  cerestation dmm  - StrongDMM
2024_07_30__13_58_52__paradise dme  cerestation dmm  - StrongDMM
2024_07_30__13_59_00__paradise dme  cerestation dmm  - StrongDMM
2024_07_30__13_59_07__paradise dme  cerestation dmm  - StrongDMM


The following APCs were not moved due to lack of proximity to maintenance:

- Expedition Room
- Storefronts
- Cargo Lobby
- Cargo Office

**Review by Burzah — APPROVED** [review]
I am good with this how it is. It has run through a bunch of test rounds, with no glaring issues. Anything that comes up can be spot fixed. If you can, update the testing section before we send this. Good work overall!

**Review by S34NW — APPROVED** [review]

**Pull request merged**
