### PR TITLE
Glass tables!

### PR DESCRIPTION
**Pull request by tigercat2000**
This PR adds glass tables.

Credit to WalterJe for the sprites (https://tgstation13.org/phpBB/viewtopic.php?f=11&t=1659)

Glass tables can be summed up in the following points;
 * Fancy transparent sprite
 * Shatters into table parts and glass shards when flipped
 * Can be constructed by making a frame with metal, then adding glass

Notes for players;
 * Tables are not currently integrated into the map, but you can construct them.

Notes for coders;
 * No specific notes for coders, other than pointing out how terrible the table sprite system currently is.

Example picture;
pics of tables

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1: Can't wait for idiots to try climbing on them.

**Comment by tigercat2000** [comment]
actually you can still climb on them, mainly because playing with that code is a pain. Besides, something like 'yeah it's strong enough to hold people but if you suddenly impact it against the floor..'

**Comment by Spacemanspark** [comment]
Awwwwwwww.
Still a :+1:

**Comment by Fox-McCloud** [comment]
:+1: 

Would like to see the tableclimb proc rewritten though---and yes, I know that's outside of the scope of this PR, but our version is pretty bad compared to TG's.

**Comment by fj45** [comment]
Personally, they should never be added to the map, just be buildable.

**Comment by jack-fractal** [comment]
They'd look good in medbay. 

Do they block hiding creatures or can you see through them?

**Comment by tigercat2000** [comment]
@jack-fractal You can see anything through them, they are transparent.

**Comment by Fox-McCloud** [comment]
:+1:

Glorious glass tables.

**Comment by M3hillus** [comment]
Please Please PLEASE make it so if you throw someone on one of these it smashes it.

**Comment by CrAzYPiLoT-SS13** [comment]
Ooh, I could do it. Maybe a glass shard gets stuck in a wound?

**Pull request merged**
