### PR TITLE
Antag Hud updates

### PR DESCRIPTION
**Pull request by Aurorablade**
Based on TG updates, makes my solo antag hud stuff neater (Again from TG)

Still some bugs with nations hud i know.
If anyone spots anything i can fix just slap me with some eyeballs..

:cl: Fethas
rscadd:Antaghud Updates
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
yeah someone..is gonna have to help me figure shit out...

**Comment by Tastyfish** [comment]
I think the duplicate HUD additions here https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/implants/implant_traitor.dm#L67-L75 where `update_traitor_icons_added()` is called, followed by `add_serv_hud()` (which seems to be for thralls) is what is breaking mindslave HUD icons.

**Comment by Aurorablade** [comment]
@Fox-McCloud the mindslave by traitor implant is working on my end.

**Comment by Lady-Luck** [comment]
Could this be related to #4277?

**Pull request merged**
