### PR TITLE
Fixes Lazy Syndicates

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes those lazy ass syndicates giving those lazy ass engineers even more excuse to be lazy ass engineers.

(fixes engineers getting the plasma tank objective).

### CODE REVIEW

**Comment by Earthdivine** [comment]
While your at it, would you mind making the objective look for the tank itself rather then the 28 moles (whatever that means in game), since the detection on that seems very janky?

**Comment by Fox-McCloud** [comment]
that's actually intentional; it allows for clever traitor to fill up an oxygen tank with plasma and get a "success" out of it---which is great, IMO; sec gets insta-mad when they catch you with a plasma tank, but they never--ever suspect when you have an oxygen tank in your backpack.

**Comment by Earthdivine** [comment]
Alright that's fair, would you mind making it something more coherent with ingame terms, I see traitors failing this objective while having a tank and I'm sure it's because no one wants to figure out what Moles is in pressure (Google, what is that?)

**Comment by Spacemanspark** [comment]
28 moles is a full tank.
1013 units, in other words.

**Pull request merged**
