### PR TITLE
Wardens HATE him! Local Officer exposes SHOCKING truth about holobadges. Not reading this can KILL YOU.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattestGuitar
tweak: HoS, Warden, Pod Pilot and Officers now get a complementary holobadge to their standard harmbaton kit. Check your backpack!
/:cl:

Adds holobadges to the normal sec loadout of HoS, Wardy, Poddy and Officers. Why was this not already a thing?

### CODE REVIEW

**Comment by taukausanake** [comment]
Not click baity enough :)

**Comment by Spacemanspark** [comment]
Yes.

**Comment by FlattestGuitar** [comment]
There, upgraded.

**Comment by CrAzYPiLoT-SS13** [comment]
Is it a normal one or the hangy-necky type? I demand my neckwear.

**Comment by FlattestGuitar** [comment]
I... didn't consider the necky ones. Darn.

You're going to have to bother the warden for those, I'm afraid. I don't see a proper way of letting people choose, and giving everyone both will be annoying as hell.

**Comment by DaveTheHeadcrab** [comment]
:-1: for clickbait.

**Comment by FlattestGuitar** [comment]
Okay, this was @DaveTheHeadcrab's terrible idea. You now have a 33% chance to get a cord badge instead of a normal one in your backpack. No refunds.

**Comment by TullyBurnalot** [comment]
I demand badges for everyone.

Seriously though, this is cool.

**Comment by Davdichan** [comment]
Detective is the only one who needs a badge, and yet they are specifically excluded here? Dafuq.

**Comment by taukausanake** [comment]
> Detective is the only one who needs a badge, and yet they are specifically excluded here? Dafuq.

Huh. That actually sounds like a bigger issue than sec not having any. Then again why would either use badges when they have Security IDs?

**Comment by Davdichan** [comment]
@taukausanake The badge is mostly a fluff item, but you can key them to yourself and then use a badge on someone to 'violate their personal space' or something like that where you basically shove your badge in their face to tell them to shut up.

**Comment by FlattestGuitar** [comment]
The detective doesn't have the access to imprint the badge with his details. If he wants one he'll need a trip to the HoP anyway.

**Comment by Fox-McCloud** [comment]
Honestly, this would be better served as part of the Bay/Polaris loadouts thing.

**Comment by Vivalas** [comment]
The badges are really useful if you go undercover. The neckbadges are just a nuisance though because you can't smoke while wearing one. That's a minor thing of course.

**Comment by CrAzYPiLoT-SS13** [comment]
I put my necky ones on my jumpsuit, I don't know about you guys.

**Comment by Fox-McCloud** [comment]
Now that the Loadouts is in, you can move this to that.

**Comment by FlattestGuitar** [comment]
Righty right. 

I'll have a PR coming *soon™* with badges, pink harmbatons and fuzzy cuffs. Cheers.

**Comment by taukausanake** [comment]
DON'T FORGET THE CLICKBAIT

**Pull request closed without merging**
