### PR TITLE
Ports TGs new crates! (not really)

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Resprites the Garbage bin, Secure garbage bin with a TG style version. (Does not contain the originals animation cycle between opening/closing, specifically because of our current ones layer-code)

## Why It's Good For The Game

The TG style garbage can sprite is way better in contrast to the current one, current one is just a grey oval tube.

## Images of changes

OLD
image

NEW
image

IN GAME
image
image

## Testing

All layers appeared to work without issue. (despite how weirdly its coded compared to crates in the .dmi, AND the file size conversion)

## Changelog
:cl:
imageadd: Ports TG garbage bin
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
I got jebaited by the title

**Comment by matttheficus** [comment]
For some reason they look a LITTLE too shiny in my opinion.

**Comment by ATP-Engineer** [comment]
> For some reason they look a LITTLE too shiny in my opinion.

Spot on in my opinion
image

**Comment by OctusGit** [comment]
impressive-very-nice


Now lets Paul Allens trashbin

**Comment by Sirryan2002** [comment]
I dont know if its me, but the lighting on the can feels off

**Review by Sirryan2002 — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
