### PR TITLE
Computer Lighting Update

### PR DESCRIPTION
**Pull request by SamCroswell**
- Brings our computers to an overlay-based system courtesy of tgstation/-tg-station#9931 This cuts down on the size of our computer.dmi file by an insane amount.
 - Tones down the light emitted by computers, it will now emit light in a one tile radius while on.
 - Puts computer overlays on a layer above darkness. The result: Computer screens, while on, are always as bright as if they had full light shining on them. This effect looks pretty kickass:

bridge
warden
captain
fukkinxenos

 - Moves the Captain's ID one tile over, it is now ontop of the recharger. Due to the overlays being over the lighting layer, items that are on top of the computer will appear to be underneath the screen. The only thing this might be an issue with, so far as I know, is Poly. She has a tendency to perch on top of computers.

Second Round of Commits:
- Bluespace Crystals and GPSes now eject to be under the user rather than ontop of the console.
- Poly will no longer perch on consoles.

_Edit:_
One important note I forgot to mention: This will not work with power monitors or solar monitors, as they are not subtypes of computer for whatever reason. In the event they get converted to a child of computer they will have this as well.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Reduces the .rsc and makes computer lighting look infinitely better?

:+1:

**Comment by Nienhaus** [comment]
10/10 cool as fuck.

**Comment by fj45** [comment]
Looks great.

**Comment by PsiOmegaDelta** [comment]
While the darkness overlay trick definitely is nifty doesn't that mean that screen would cover most things that could happen to share a turf with a computer?
Teleporting ninjas, ethereal wizards, hand-teleporting crew members, ghosts, etc.?

**Comment by Nienhaus** [comment]
If it does @PsiOmegaDelta then it clearly means everything in the SS13 world is translucent to computer light.

**Comment by SamCroswell** [comment]
@PsiOmegaDelta 
It does, yes. I said that myself in the description of the PR.
I've taken steps to make sure that computers that eject things eject them into the user's hands or onto the floor if the hands are unavaiable rather than on top of the computer.
Wizards cannot jaun ontop of dense objects, and when I (Eventually) re-add Ninjas they will act in the same way.
People who use the hand teleporter to get ontop will, however, be partially covered, yes.

**Comment by orelbon** [comment]
:+1: :x: :100:

**Comment by ZomgPonies** [comment]
Looks great. Beautiful idea.

**Comment by orelbon** [comment]
can we more electrical overload events so we can see this beautiful new effect in action :p

**Comment by Bram961** [comment]
I think it would be better to have a broken screen be dark instead of how it looks in that last picture. Other than that this looks awesome

**Comment by Fox-McCloud** [comment]
@Bram961 

It's still operation; there's still power being supplied to the machinery, so it would still be lit.

**Pull request merged**
