### PR TITLE
Dark mode tweaks v1.1

### PR DESCRIPTION
**Pull request by Deelite34**
## What Does This PR Do

Tweaks few colours of things I have missed in #14115 : OOC has a bit brighter colour in both light and dark mode, mentor colour will be slightly brighter to be easier to differentiate from new ooc colour, dark mode ert radio is slightly brighter, fixes few occurences of "blue" colour I have missed and few dark mode colours

changes

## Changelog
:cl:
tweak: Fixes few missed bad dark mode colours
/:cl:

### CODE REVIEW

**Review by Kyep — APPROVED** [review]
Approved, but I'd prefer light-mode OOC color to be a bit darker than it is now.

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
image
This needs to be a little darker, after speaking with a lot of lightmode users.

We also need an example of what the new mentor colour looks like on both.

**Comment by Deelite34** [comment]
Here's visualisation of mentor colour and darkening of OOC colour. Anything darker than #2C4FB8 will make ooc text unreadable again in dark mode. I'll change OOC colour to #275FC5 by suggestion by AffectedArc.
darkeroocchanges2408

**Comment by AffectedArc07** [comment]
image
This OOC colour works

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
