### PR TITLE
Ports TG's Nar'Sie

### PR DESCRIPTION
**Pull request by RyanSmake**
Time to settle this debate once and for all.

### CODE REVIEW

**Comment by Superhats** [comment]
This is a game-changing port, merge immediately

**Comment by tigercat2000** [comment]
lol

**Comment by Regen1** [comment]
I disagree with this PR

**Comment by RyanSmake** [comment]
@Regen1 That's sexist

**Comment by Tayyyyyyy** [comment]
`to_chat(target, "<span class ='cultlarge'>[uppertext(ticker.cultdat.entity_name)] HAS CHOSEN YOU TO LEAD HER TO HER NEXT MEAL</span>")`

Narsie was already female! Though you might wanna change "HER" to use the pronouns lib

**Comment by Ty-Omaha** [comment]
This will just make people get cooties, which we all know, nobody wants.

**Pull request merged**
