### PR TITLE
Adds 4 epin auto injectors to medbay vending machines

### PR DESCRIPTION
**Pull request by jughu**
Adds 4 epin autoinjectors to medbay machines
In trade for 2 epin bottles 

You would really think medbay would have atleast some epin autoinjectors

   :cl: Improvedname
   rscadd: Adds 4 epinephrine autoinjectors to nanomedplus vending machines
   /:cl:

### CODE REVIEW

**Comment by Plotron** [comment]
Well...

It's usually a part of Emergency NanoMed Vendors.

**Comment by jughu** [comment]
This adds them to the main machines which qre auctally a better version of those this is clearly a improvement i say you run out of epin injectors very fast

**Comment by Plotron** [comment]
Yeah, I get you.

**Comment by Lady-Luck** [comment]
why tho

**Comment by FalseIncarnate** [comment]
Medical lockers come with a box of auto-injectors. There is no shortage of them.

**Comment by jughu** [comment]
Wait they do? I never saw them despite playing doctor regulary?

**Comment by FalseIncarnate** [comment]
https://github.com/ParadiseSS13/Paradise/blob/ecd12bee630c24d0a272c5ca5ea5176aea1d894f/code/game/objects/structures/crates_lockers/closets/secure/medical.dm#L15

they tend to end up beneath the box of syringes in the medical supplies lockers

**Comment by jughu** [comment]
Altough then just removing the box adding them to the vending machine woukd make them more noticible tho

**Comment by jughu** [comment]
I think its really a better idea removing them from the lockers adding 7 of thfm to the vending machines since i think 1 box includes 7 injectors x2 lockers

**Comment by FalseIncarnate** [comment]
each box contains 6 or 7 injectors. One box practically provides the same number as 2 machines, and there are multiple boxes in medical. Additionally, they are in the emergency nano-meds (as previously mentioned) which are located in the sleeper rooms as well as in other areas around the station (like engineering)

**Comment by jughu** [comment]
But it be still a good idea to remove the box auto injectors from the lockers and put them in the medbay vending machines so they are more noticible

**Comment by jughu** [comment]
But the emergency machines are mostly on the unoticable places

**Comment by jughu** [comment]
The idea here is now to remove the boxes and put them in nanomedplus

**Comment by FalseIncarnate** [comment]
Locations of emergency nano-meds:
exam room, each sleeper room (2 total), surgery observation(2 total), one in each isolation room (3 total)
additionally, outside of medical: engineering foyer (1), engineering hall between PA and CE (1)

Yes, unnoticeable might apply to the isolation rooms in medical, and maybe the exam room depending on who is in medical. The rest of these are right on the walls of decent traffic areas.

I'm not necessarily saying that putting them in machines is bad, but I am saying that these are common enough both within medical and outside of medical that your initial statement of "You would really think medbay would have atleast some epin autoinjectors" is a bit off-mark.

Oh, and let's not forget the sleepers can inject epinephrine as well even without upgrading, and is an infinite source of instant injection (once you get them in) as well as being considered an emergency chem in the sleeper (so it can be injected as long as they are slightly alive, even critical). Medical has a great assortment of ways to fill you up with epi.

**Comment by jughu** [comment]
I guess

**Comment by jughu** [comment]
Does this do it?

**Comment by Fox-McCloud** [comment]
A PR using the old changelog system isn't going to get merged in.

**Comment by FalseIncarnate** [comment]
no, we don't use the changelog files anymore, instead we use the auto-generation ones using the :cl: stuff like you'll see in other PRs

**Comment by jughu** [comment]
Aaa i dont know how 2 changelong

**Comment by FalseIncarnate** [comment]
https://tgstation13.org/wiki/Guide_to_Changelogs#Online_auto-creation

**Comment by jughu** [comment]
Ahh i see

**Comment by jughu** [comment]
I do it tommorow then

**Comment by FalseIncarnate** [comment]
That's better (personally I'd have just done "tweak: Replaces epinephrine bottles in Nano-Meds with Emergency Auto-Injectors", but either way gets the change across)

**Comment by Plotron** [comment]
I'd love the new change - no more boxes, less chance of someone hoarding supplies.

**Comment by Ty-Omaha** [comment]
What if I need to pump someone full of epi? Then i'd have to carry 4 or 2 auto injectors instead of a bottle or 2, and doctors already carry a lot of medications and other equipment on them.

**Comment by jughu** [comment]
Epin bottles are still here just lowered from 4 to 2 and added 4 epin injectors as a trade off

**Comment by Ty-Omaha** [comment]
Oh lol

kek

coolio then

**Comment by Fox-McCloud** [comment]
Iffy on this--not a huge fan, not hugely opposed, but I hardly ever see most doctors carry spare medipens on them, despite them being commonly available.

**Comment by Plotron** [comment]
I'd rather just move the injector boxes to medvendors.

**Comment by Fox-McCloud** [comment]
If you're going to do this, don't reduce the amount of epi bottles.

**Pull request merged**
