### PR TITLE
VV can now also fix robotic limbs.

### LINKED ISSUE #9517: AdjustBruteLoss() & AdjustBurnLoss() do not work properly for IPC
**Problem Description**:
The above two function doesn't work on IPC if used to heal. It works when used to damage them.

I found out about this while attempting to fix #3814

However I stopped attempting to fix it and I am putting this out here for anyone interested as it is not a simple & easy bug to fix.

**What did you expect to happen**: 
It is supposed to heal & damage

**What happened instead**:
You want to love but you only know how to hurt.

**Why is this bad/What are the consequences:**
Causes #3814 . Admin cannot use VV to heal IPC either and I assume a lot of other things are also broken. 

**Steps to reproduce the problem**:
1. Make an IPC
2. Burn / Hurt them with VV 
3. Attempt to unburn / hurt them
4. Fail
5. Background IPC main buzzing.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
It also applies to support guardian.

### PR DESCRIPTION
**Pull request by alex-gh**
AdjustBruteLoss() & AdjustBurnLoss() now have the "robotic" parameter, allowing them to repair robotic limbs.

When called from the VV panel they will also heal robotic limbs.

Fixes #9517 

:cl:uc_guy
fix: It is now possible to heal robotic limbs and IPCs through View Variables
/:cl:

### CODE REVIEW

**Comment by variableundefined** [comment]
Will this work for holopara? You can test that by multikeying locally

**Comment by alex-gh** [comment]
Not yet, holopara fix will be a separate PR.

**Comment by variableundefined** [comment]
Sounds good

**Comment by alex-gh** [comment]
OT for this PR, but you might need to explain the commit author stuff to me. Are you in coder_chat discord channel?

**Comment by variableundefined** [comment]
Actually, I just got myself confused. Usually when no profile pic show in your commit message it won't count toward contribution but I am clearly wrong on this.

**Pull request merged**
