### PR TITLE
Make Sake,Kahlua, and Soy Sauce Recipe more realistic

### PR DESCRIPTION
**Pull request by ArgyleSweatshop**
Soy sauce is definitely not made from acid, so I made the recipe more realistic, using the INTERNET!

Also, Kahlua is made from rum or vodka in addition to the ingredients already included, so I added that.
Sake is made from rice alcohol and it is by and large always diluted by water, so that was added to the recipe.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Flour isn't an obtainable reagent.

**Comment by Earthdivine** [comment]
Flour isn't available in the kitchen anymore?

**Comment by Fox-McCloud** [comment]
It's an object, not a reagent.

**Comment by ArgyleSweatshop** [comment]
It is a reagent. The flour packets are considered drinks by the code, and I think you can pour them. I would test this if I was able to get on

**Comment by ArgyleSweatshop** [comment]
Flour packets are definitely treated as reagent containers. I know that putting flour in the reagent grinder puts out flour(reagent), so flour is accessible.

Im fine with removing flour as an ingredient if that's the only way to the others being approved.

**Comment by Fox-McCloud** [comment]
It's not obtainable. 

There's even a line under drinks.dm that specifically says "flour is not a reagent anymore".

The reagent itself WAS re-added, but purely for the vent-gunk event--it's not obtainable in any way, shape, or form---currently; flour boxes only ever have nutriment in them.

**Comment by Regen1** [comment]
#makeflourareagent2k15

**Comment by ArgyleSweatshop** [comment]
I'll ask for your opinion then- do you want me to change flour boxes to contain flour or do you want to remove flour from the recipe? Or neither and you want me to give up?

**Comment by Fox-McCloud** [comment]
you could probably make it so if you grind flour you get it or something, but making it into a reagent container, right now, is probably not a good idea until False's stuff is ironed out.

**Comment by ArgyleSweatshop** [comment]
I can't find the id for flour(object) in the code and can't find flour right now. I'll be on tomorrow, but if someone wants to add that to the pull request or at least point me to where it is, I'd be thankful.

**Comment by veganzombeh** [comment]
https://github.com/ParadiseSS13/Paradise/blob/22180af1c0f9a7d22b108ecd1312c37b805263fb/code/modules/reagents/reagent_containers/food/snacks.dm#L620

**Comment by ArgyleSweatshop** [comment]
Okay, the needed changes are made. I made it so flour packets now contain flour; they previously contained 1 unit of nutriment. This makes it so grinding flour packets(which was already possible) now gives 5 units of flour. 

If no one else has any problems with this, might I suggest the "do not merge" label be removed? There are no bugs in the code.

**Comment by Fox-McCloud** [comment]
I have no problem with this; if False doesn't see any potential conflicts with his changes, then I think this is safe to merge.

**Pull request merged**
