### PR TITLE
PiP Multivis

### PR DESCRIPTION
**Pull request by tigercat2000**
:cl:
add: PiP Hud Elements
experimental: AI PiP Multicam - Enabled by admins
fix: Calling /New( with excess arguments is now properly directed to /Initialize(
/:cl:

First commit just fixes a bug I noticed - Initialize( is supposed to get all of the arguments from /New( when generated normally, but it was broken. No one noticed because we don't use Initialize yet.

tgstation/tgstation#28360
tgstation/tgstation#37695

This adds a system for picture-in-picture UI windows using
vis_contents, a new feature to BYOND 512. Essentially, it allows you to
make UI windows that show an area of turfs. It also refactors how
cameranet visibility works, and makes the Adv. Camera Console code a bit
cleaner and more inheritance-based, especially with it's action buttons.

Currently, this is hesitantly implemented on AIs. They gain two new
UI buttons - "Enter Multicam Mode", and "Create Multicam". When they go
into Multicam Mode, they see a background of animated binary numbers,
and they are allowed to create an infinite amount of these picture in
picture windows, which subsequently creates an aiEye for each one. They
are able to control each AI eye individually, by first clicking on the
PIP window to select it as "active" and then using the normal arrow key
controls. The PIP windows can be freely resized and moved around the
area.

The AI implementation may be considered controversial; Thus, it's locked
by default, requiring an administrator to var-edit "multicam_allowed" on
the AI before it is able to use the function. Otherwise, the buttons
just do nothing and alert the user to "Contact an administrator to use
these". There's not really any easy way to completely hide the UI
elements until they are available.

As this relies on 512 features, Travis has been bumped up to use 512.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
take my money

**Comment by Tayyyyyyy** [comment]
I definitely think AI should get by default purely because this will make AI more AI-like and increase the depth of the game in a really cool way, and it's worth sacrificing "balance" for that. Cameras will be destroyable by simple weapons soon and we can always add more anti-AI tools if it becomes too overbearing.

**Comment by KasparoVy** [comment]
Holy shit this AI feature is absolutely unreal

Genius

**Comment by Fox-McCloud** [comment]
`I definitely think AI should get by default purely because this will make AI more AI-like and increase the depth of the game in a really cool way, and it's worth sacrificing "balance" for that.`

This hardly adds more depth to the game. This doesn't add anything new in terms of gameplay mechanics or gameplay behavior; it just flat out increases how ubiquitous the AI is, so I don't really buy the argument here that it adds "depth". 

Furthermore, the balance implications of this will be considered, especially in light of Paradise's server culture.  TG's server culture is very uh "powergamey" or mechanically focused. Despite this, their attitudes towards AIs are very strict in terms of their function and what they're allowed to get away with. Furthermore, the laws typically in place relegate it far more to observer rather than an active agent on station.

Paradise, by contrast, has AI's that have incredible amounts of freedom and a culture in which this is neither punished nor looked down upon; an AI that is active and valid-hunty is encouraged and considered something to be aimed for; Lawsets that encourage passiveness are actively maligned. The AI is *expected* to be the problem solver to end all problem solvers.

This has consequences for AI here that grant it more power than is, what I feel, healthy, for the game. Exacerbating this status is something that will be factored into the overall decision on if AI's should have this, or not.

**Comment by Tayyyyyyy** [comment]
I agree AI has lots of issues in Paradise. A lot of players play the same power tripping validhunty AI despite lawset, and having corporate on 50% only worsens the situation. However I still think it's worth trying this out to see how adverse the effects are. With cameras being easy to destroy and players only having so much attention span it may not be too terrible.

**Comment by Vivalas** [comment]
_literally unable to speak_

**Comment by tigercat2000** [comment]
It's worth noting that this is still a WiP on /tg/ due to balance concerns. There's been a few suggestions, including:
 - Limiting the amount of open windows further (it's currently at 6)
 - Making camera icons turn red when a PiP window is focused on them

**Comment by theColdflame** [comment]
this increases the skillcap of AI and doesn't make things particularly worse on the antag-facing side of cameras, since you couldve gotten caught doing illegal shit in front of a camera anyway

benefits outweigh the downsides imo

**Comment by SamHPurp** [comment]
The AI power-creep, I'm not a fan personally.

**Comment by Vivalas** [comment]
Yes, you could have always been caught with a camera. This extends the probability of being caught, however, because the AI can now watch multiple places at once, and can monitor all high security areas.

Which frankly, is realistic, but probably unbalanced. I like the /tg/ idea, maybe you could also make a "multivis" mainframe or something that can be destroyed, otherwise I think AI will just become more of a target with this.

**Comment by theColdflame** [comment]
>this extends the probability

if you leave your plan to chance it's only yourself to blame

**Comment by Markolie** [comment]
It's a really cool idea and implementation, but as has been said this would be blatantly overpowered and make things even harder for traitors and other antagonists. The AI is already incredibly powerful, and this would make it even worse (especially because many AI's just ignore their laws to play super cop). Giving it to traitor/malfunctioning AI's would be fine though.

Saying we "will add" anti AI/camera tools isn't good enough. Add them before this is made available to all AI's.

**Comment by davidchan13** [comment]
I think people are kind of freaking out over nothing here. Yes this lets the AI monitor more locations at once, but with limited field of view. The AI can monitor very specific areas, but depending on how they position their PiP view, they might not even be able to see the camera offering that view making it even easier to sabotage the AI in some cases, and makes it all the more important for antags TO cut the camera (something the AI can't fix remotely and only 1 borg module can repair)

**Comment by Citinited** [comment]
AI can just follow all its borgs at once right? Could make it really irritating to emag them

**Comment by Denthamos** [comment]
This would be interesting on security camera consoles too.  They are essentially 8k computer monitors that when you think about it, should be able to show multiple cameras at once instead of just one giant picture.

Think something along the lines of this - https://imgur.com/32Zf9Ak

This has potential not only for say, a warden that just wants to sit there and monitor cameras, but antags working together and using their comms in order to constantly relay where a target or people who might see them commit a crime are in the area, sort of like how abductor agents and scientists currently work.

**Comment by tigercat2000** [comment]
@Citinited Following is tracked by a single variable on the AI mob itself -- so no, they can only track one mob at a time in one viewport.

**Comment by Dinarzad** [comment]
People are focusing on the AI issue a whole lot, but are ignoring the fact it doesn't HAVE to be AI only.

You could just as easily make this available to antags by adding a form of advanced camera monitor console or encourage the use of Camera Bug. you also have an AI detector as an Traitor for a very good reason.
So balance is really not nearly as much a concern as some are making it out to be.

**Comment by RyanSmake** [comment]
When the AI requests the use of this, it probably should say `"This function requires [command_name()] approval. Send request?"` With giving admins a prompt. Give this a 10 minutes or so cooldown.

_Muh immersion_

**Comment by davidchan13** [comment]
>When the AI requests the use of this, it probably should say "This function requires [command_name()] approval. Send request?" With giving admins a prompt. Give this a 10 minutes or so cooldown.

>Muh immersion

Only if security needs CC approval to pull lethals from harmory.

**Comment by RyanSmake** [comment]
@davidchan13 Really now? Currently it just gives you an error message, my solution makes more sense.

Bring your passive aggressiveness to the person who deserves it, for I would be the happiest if AIs got this by default.

**Comment by Shadeykins** [comment]
Has the capacity to revolutionize our admittedly awful camera system. It makes AI more powerful, and conversely makes traitor/subverted AI's far more of a threat.

A system like this could also be a dramatic boost to the camerabug tool if it was added to it.

**Comment by Plotron** [comment]
I'd love to see this on camera consoles more than anything else. AIs can teleport easily, while navigating using the clunky camera console UI is hard. Would make monitoring more realistic, intuitive, and helpful.

**Comment by Ziiro** [comment]
Just port lavaland and attach it to the combat upgrade, ezpz

**Comment by alexkar598** [comment]
Lets port every single bug fix tg made while we're at it!

**Comment by DarkPyrolord** [comment]
Love the idea of this feature, it has a 👍 from me.

**Comment by Taaketa** [comment]
As a minor balance change and for my sanity if I was AI. Could you make unfocused windows black and white?

**Pull request merged**
