### PR TITLE
[BORG UPDATE] Add GPS BORG0

### PR DESCRIPTION
**Pull request by PhantornRU**
## What Does This PR Do

Port of the refactor and new tools from "SS220 WyccStation".
We played with these changes for 2 years and don’t touch them anymore, since we fully tested them for balance, usability and user response. We hope you will like them too and improve the gameplay of robots.

- This cyborgs is expensive, so it has a built-in GPS for faster location.

## Why It's Good For The Game

ALLOWS you to find lost expensive cars at the station.
For example, if the antagonist hid our cyborg in a locker.
True... If they get the signal among the other BORG0

## Testing

Tested for 2 years on the SS220 WyccStation on live servers.

## Changelog
:cl:
add: Added Cyborg GPS
/:cl:

### CODE REVIEW

**Comment by Cress67** [comment]
This is already fairly trivial for the AI, Robotics, and Research Director to do. The RD has a computer that tells them the exact coordinate position of every cyborg on the station's Z-level at all times, the AI gets the name of the room that the cyborg is in listed in their Status tab (and can access the RD's computer), and Robotics can get information from either or just build their own computer that does the same. They're the only people that really need to know or care about where the borgs are.

All this really does is make it trivially easy for anyone with a GPS to immediately know how many borgs are on station as well as their locations... which can really mess with a Malf AI's day, or make an emagger's day much easier by letting them hunt lone borgs. Basically, it's purely for the benefit of antags and detriment of Malf AIs.

**Comment by Fordoxia** [comment]
> This is already fairly trivial for the AI, Robotics, and Research Director to do. The RD has a computer that tells them the exact coordinate position of every cyborg on the station's Z-level at all times, the AI gets the name of the room that the cyborg is in listed in their Status tab (and can access the RD's computer), and Robotics can get information from either or just build their own computer that does the same. They're the only people that really need to know or care about where the borgs are.
> 
> All this really does is make it trivially easy for anyone with a GPS to immediately know how many borgs are on station as well as their locations... which can really mess with a Malf AI's day, or make an emagger's day much easier by letting them hunt lone borgs. And GPSs fit in pockets so they can be referenced constantly, while the computers require you to head to a static location to get the information. Basically, it's purely for the benefit of antags and detriment of Malf AIs.

To be fair, there is another use case for universal GPS: cyborgs getting spaced if they accidentally wander through an uncalibrated teleporter -this happens somewhat often and it's a royal pain to try and get the cyborg back to the station afterwards.

Unless they're a mining borg, because they have GPS. They orient themselves and get back/let an explorer know their exact location.

**Comment by Zorazi-Teo-Daedalus** [comment]
In all fairness it would enable cyborgs to far more reasonably recover dead people on lavaland or in space, assuming it's a module that the borg could access.

**Comment by farie82** [comment]
The balance team has voted against this PR for the following reasons:
- Could fuck with malf. AI can already locate borgs, they don't need a postion tracking system that every miner/explorer can see
- Even if the borgs can turn the GPS on and off like regular gps's it makes me think of the situation of "oh, the borg disabled its GPS. It must be rogue now"

Due to this I'm closing the PR. Thank you for making the PR though!

**Pull request closed without merging**
