### PR TITLE
Cleans Up Icons

### PR DESCRIPTION
**Pull request by Fox-McCloud**
REQUIRES A CLEAN COMPILE TO TAKE ADVANTAGE OF!

Cleans up a few icons--overall RSC reduction of ~0.5 MB

- Removes pre-colored fire sprites (unused as we color greyscale fires)
- Removes lying sprites (we rotate sprites; no need for these)
- Removes screen1_action.dmi (duplicate of actions.dmi)
 - the single sprite that still needs to be converted has been moved to actions.dmi
- Moves roach from livestock.dmi to critter.dmi 
- Removes livestock.dmi (old old old unused icons that have since been updated)
- Removes duplicate sprites in critter.dmi

### CODE REVIEW

**Comment by tigercat2000** [comment]
screen1_action.dmi is not a duplicate of actions.dmi- it contains some unused sprites that I didn't get around to touching.

I don't like removing any icons honestly, especially for only .5 MB. Unused icons have potential.

**Comment by Fox-McCloud** [comment]
lying icons have no potential, neither do horrendously outdated cow icons with gigantic heads...or 0.3 MB fire icons that are unused because we post-color our fires.

I'll re-add the two action button icons you don't have (blind and flesh to stone)

**Comment by tigercat2000** [comment]
@Fox-McCloud Horrendously outdated cow icons with gigantic heads sounds perfect for a crazy event to me. My point is that removing icons for less than 1MB of rsc space is a bad practice.

**Comment by Fox-McCloud** [comment]
Keeping unused icons that have been updated or are deprecated by a refactor (colored fires, no need for lying spritse at all) is bad practice.

**Comment by tigercat2000** [comment]
Old icons aren't inherently bad. If you really want the tiny amount of rsc downsize, I would strongly urge you to move old icons to a specific old icon dmi.

**Comment by Fox-McCloud** [comment]
There's literally no reason to have them around. It's stupid to keep them--unlike the singularity sprite (which is high res and has *hypothetical* use), old icons that have been updated unanimously never see use; there's no reason to have either of those around.

If you want to keep them, feel free to.

**Comment by orelbon** [comment]
theres a roach sprite?

**Comment by Fox-McCloud** [comment]
@orelbon 

Yep--indeed there is.

**Comment by orelbon** [comment]
Wow why aren't they in game like mice?

**Comment by Fox-McCloud** [comment]
because no one has bothered to code them =p

**Comment by orelbon** [comment]
Why not copy the code from mice but ad a roach sprite?

**Comment by ZomgPonies** [comment]
This is fine, none of those icons will ever see future use since they all have current alternatives.

**Pull request merged**
