### PR TITLE
Fixes #3425

### LINKED ISSUE #3425: Shuttles Depressurize Over Time With Use
This issue has to do with a small error of calculation when shuttles go to launch. Unlike the previous shuttles, which shut the doors prior to launching (and therefore bolt), when the shuttles currently launch, they shut the doors only a moment after the shuttle actually launches. This leaves a small duration where the air of the shuttle in transit will leave the shuttle, and over time, since the doors don't stay open, don't re-pressurize properly. A simple fix would merely be to force the doors to close BEFORE launching the shuttle, not after. This, to me, merely seems to be a timing issue, but over multiple uses, will cause depressurization of shuttles (especially since people don't either shut the doors themselves before launching or leave the airlocks open long enough for the shuttle to full re-pressurize... Thanks LINDA...).

### PR DESCRIPTION
**Pull request by VampyrBytes**
There were a couple of things going on... the spawn(-1) which should have ensured the door was closed before continuing was being negated by the sleeps. Also, if the door had just been used it was marked as operating and the close would fail

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@tigercat2000

**Comment by VampyrBytes** [comment]
Whoops. I'll split the pull requests when I get home

**Comment by Fox-McCloud** [comment]
I strongly recommend not making PRs from your master, so you can work on multiple things, at once, more easily.

**Comment by VampyrBytes** [comment]
Yeah, figured that out. Will close this and resubmit from a branch

**Pull request closed without merging**
