### PR TITLE
Removes Space Ninjas

### PR DESCRIPTION
**Pull request by SamCroswell**
Removes Space Ninjas entirely, pending re-implementation in a more maintainable and less god-awful manner.

Ordinarily I'd discuss this before dreaming of posting the PR, but since Ninja is borderline adminspawn-only anyhow, I don't think it'll be an issue.

Feel free to call me literally Hitler in the comments if you disagree. (Or reasonably voice your opinion. That works too.)

### CODE REVIEW

**Comment by Markolie** [comment]
Hitler.

**Comment by tigercat2000** [comment]
Hit- actually this is probably for the best

**Comment by TheDZD** [comment]
"Showing  43 changed files  with 68 additions and 3,930 deletions."

That's 3,930 less lines of some of the snowflakiest code we have.

**Comment by SamCroswell** [comment]
Yes, I am a fun-ruining SuperHitler. Until I re-code them.

**Comment by Spacemanspark** [comment]
We should recode Space Ninjas, but better than they were before.

**Comment by ZomgPonies** [comment]
That's the goal.

**Comment by SamCroswell** [comment]
That's what I said I'd do, both in the comments and in the PR body.

**Comment by Markolie** [comment]
[Dave right now](http://i.imgur.com/I0t0I.gif)

**Comment by Fox-McCloud** [comment]
Still need to kill off every snowflake ability his energy sword has, as well.

**Comment by fj45** [comment]
Ahahaahah well holy hell its finally gone!

**Comment by SamCroswell** [comment]
Unfortunately, Fox, the energy blade has to stay. It's the only Ninja ability I haven't thought of a way of a way to modularize, due to the fact it needs to both bludgeon people and slice open doors. (Causing the NOBLUDGEON flag coupled with an afterattack proc to be unviable as an option)

**Comment by Artorp** [comment]
What about splitting it up into two items? The energy blade which can be used to slice people and walls, and an energy card which can be used on doors only.

Activating the blade turns it into a card, and vice versa. Kind of like guns and their modes, but with two items.

**Comment by Fox-McCloud** [comment]
@SamCroswell 

Well, one way around that could be to give him a reskinned emag, as that already accomplishes (more or less) the same exact thing.

**Comment by Flip-Sandwich** [comment]
rip in piss

**Pull request merged**
