### PR TITLE
Fixes mapping issue in arrivals maint

### PR DESCRIPTION
**Pull request by Norgad**
This was a problem accidentally introduced during tuning of the remap.
ejwnyueohcamamc_8ackral4g4iejuojrdndzv--znw-5umxwc2u2mqf2a5j3dcryj2wbatzuxjsh9jen0tvmpy7vxvadg4mdmsydireaqhdohrvpgnj4_uzh6eelt_vtlrm7w8fsslv

Now fixed.
2017-03-24 16_23_57-greenshot

### CODE REVIEW

**Comment by SamHPurp** [comment]
I mean.... do we want that spot to be observable? IT was a nice little area you could do dodgey shit right in front of sec.

**Comment by Norgad** [comment]
@SamHPurp That was precisely the reason it was added, this PR simply fixes me accidentally moving it too far to the left

**Comment by SamHPurp** [comment]
So with you fix it is now viewable? Or isn't now viewable?

**Comment by Norgad** [comment]
As you can see in the images provided, it re-adds visibility.

**Comment by SamHPurp** [comment]
Then yup, thats what I'm against.

**Comment by SamHPurp** [comment]
Fix the fact that people in maintenance can watch surgeries going on in OR2 if you want to fix something silly, imo.

**Comment by Norgad** [comment]
This is a **fix** to my own PR.
If you care about surgery add the blast doors yourself.

**Comment by FreeStylaLT** [comment]
img Is how it is right now. The windows vertically line up with the bottom part.

img They still do, despite the upper room being expanded 1 tile.
Why did you expand the lower one / not show how you've expanded it?

**Comment by Norgad** [comment]
I did show it, it's visible in the screenshot, and it's so it still lines up. If it got thinner near the exit it would feel more enclosed, which the admins didn't want.

**Comment by FreeStylaLT** [comment]
img
I would wager that the lower portion doesn't have to be moved at all. I am not sure why those two rooms have to be vertically aligned with their outlines. 

In addition, I am unsure whether this really is a fix, rather than a tweak, similar to the ones I have made for maint at the moment.

**Comment by Crazylemon64** [comment]
obsolete

**Pull request closed without merging**
