### PR TITLE
Update some old food sprites with TG ones

### PR DESCRIPTION
**Pull request by Varghh**
## What Does This PR Do
Updates many food sprites with TG ones.

## Why It's Good For The Game
They look really neat, also the old taco sprite was comically massive and the muffin one was super pixelated.

## Images of changes
From left to right
Taco - Muffin - Friedegg - meatball - meatstake - meat - xenomeat - bearmeat
foodz

foodzold

## Changelog
:cl:
add: Change a few food sprites with TG ones
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
Something is weird with the rotten meat sprite:

DqSxHBh

**Comment by Varghh** [comment]
> Something is weird with the rotten meat sprite:
> 
> DqSxHBh

Huh weird, we don't use rotten meat anyway so yeet

**Comment by Varghh** [comment]
Requested by @SabreML now you can see the old sprites too in the PR

**Comment by Mitchs98** [comment]
This is great. I want this x.x

**Comment by PacifistDalek** [comment]
Looks great! Only thing I'll note is that with the fried egg, I had edited TG's sprite to remove the second yolk, since it made more sense to me that a recipie made from 1 egg would have 1 yolk as an end result (I know there are 2 yolk eggs, but they're rare!). If you feel strongly that the single yolk egg sprite doesnt look as good, then feel free to change it, but that was my reasoning for editing it to what we have now!

**Comment by Varghh** [comment]
> Looks great! Only thing I'll note is that with the fried egg, I had edited TG's sprite to remove the second yolk, since it made more sense to me that a recipie made from 1 egg would have 1 yolk as an end result (I know there are 2 yolk eggs, but they're rare!). If you feel strongly that the single yolk egg sprite doesnt look as good, then feel free to change it, but that was my reasoning for editing it to what we have now since it made more sense to me!

I personally went with "which of those sprite actually makes me hungry", eggs are one of my favorite foods so it make sense I jumped immediately on the double yolk one in a matter of "tastiness". You are right and we should stay  the one yolk version.

**Review by Kyep — APPROVED** [review]

**Comment by S34NW** [comment]
The new taco one especially is so much better, the old one was almost as big as a person. Thanks for porting these!

**Comment by AffectedArc07** [comment]
Please remove these
image

**Comment by Varghh** [comment]
@AffectedArc07 Done

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
