### PR TITLE
removes color from bulb

### PR DESCRIPTION
**Pull request by Robertha89**
:cl: ppi
tweak: Removes bulbs having a light color
/:cl:
Not sure why light bulbs had a color that is not even visible.

### CODE REVIEW

**Comment by tigercat2000** [comment]
1. this is now how you fucking remove the color, you didn't even remove the set_light() code
2. jesus fucking christ NO

**Comment by Fox-McCloud** [comment]
That? Why?

There's nothing inherently wrong with colored lights; the only reason I even remotely suggested removing colored light from hotspots is because it's insanely expensive.

If light is colored, but *static* it's not expensive; it's when you're constantly changing the color, rapidly, that it gets expensive. Most colored lights on bulbs are a fixed color and stay that color 99% of the time, and the few times they do change, it's only 1-2 lights that change ONCE.

With hotspots, there's usually hundreds upon hundreds of them, and they're all changing their color every 2 seconds, which is why it's so expensive.

This has no performance benefit at all.

**Comment by Robertha89** [comment]
Consistency, the other fixtures does not have color, while these does.

**Comment by tigercat2000** [comment]
@Robertha89 you are actually fucking kidding me right

**Comment by Dumbdumn5** [comment]
Can we please leave them how they are? The more color, the more lively it looks, also the light yellow tinge makes an excellent maintenance aesthetic.

**Comment by TheDZD** [comment]
I would say that [there's a pretty noticeable difference between stark white and the current color](http://hexpreview.com/(a0a080)(ffffff)).

**Comment by Dumbdumn5** [comment]
Still enjoy the aesthetic.

**Comment by Fox-McCloud** [comment]
This ain't gunna fly.

**Comment by Gummin** [comment]
we still love you @Robertha89

**Pull request closed without merging**
