### PR TITLE
Updates computer sprites, adds in directional sprites and changes overlays - WIP

### PR DESCRIPTION
**Pull request by DogsParadise**
This is a Work In progress PR. Sprites are subject to change.
By far I am not finished with this PR, but I wish to measure the opinions before I move into implementing and wasting hours of my life on this. It's a rather big time investment, if the general heads/maints and players are in favor. I will invest the time into adjusting all the overlays/computers etc.

## What Does This PR Do
Changes the computer.dmi file.
-Changes the current computer sprite
-Changes the overlays for the computer sprite
-Adds in directional computer sprites
-TO DO: change way computers point (mapping)
-Changes pallette of computers to the ones used in new machinery imported from TG
-Changes perspective to 3/4th

To Do:
Will start work on this after heads feedback/approval
- [ ] rework all screens
- [ ] rework keyboard i originally made

## Why It's Good For The Game
It's an improvement to the overall sprite quality of paradise.
By making our own version on computers we are not just a 'tg' clone.
My version of the computer adds an extra pixel row for overlays, thus making it a lot less of a change to the overall game as it is currently as we will not need to adjust much of our current overlays for the screens. (Just remove the outer corners) see examples.
IMO my version fits in better with the current aesthetics paradise is going for. Old/new tech.

## Images of changes
WIP - more pictures to be added:

Old:
image

New (my version) :
image

TG VS Mine:
image

Old:
image

New:
image

Overview on (TG VS NEW mine *NO KEYBOARD* *KEEPS CURRENT SCREENS*):
image

Full overview example:
image

## Changelog
:cl:
add: Adds new computer angles
tweak: Tweaks current computer sprite
wip: WIP computer overlays and mapping
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
I really need to know maint/heads sentiment on this update, before i move into spending hours of time making this work in game. It's too much of an investment.

**Comment by Kiyahitayika** [comment]
I like the side-by-side comparison with the /tg/ sprites and appreciate the transparency on where the inspiration came from. I think yours have a tad bit more perspective than the /tg/ ones. I know you said there's a lot of work to be done and I definitely respect that. 

This said, you're not alone! Others can help you with the mapping once the sprites are done - for example, the sprites could be placed in a separate file for temporary holding and then merged once ready and a later PR could be done to map them in.

**Comment by S34NW** [comment]
These look superb, it might be worth shooting a PM with the link to the heads so they can let you know

**Comment by Dumbdumn5** [comment]
> These look superb, it might be worth shooting a PM with the link to the heads so they can let you know

After looking at this after he did just that, absolutely putting my 👍 here, though I know the process is gonna take a while. Best of luck and if you need any help I could see about trying my own hand!

**Comment by LordShekelstein** [comment]
Honestly, this looks incredible. But the more I look at it the more I want the north-facing computer sprite that /tg/ has.

**Comment by maxymax13** [comment]
these look rather like the goon ones :thinking:

**Comment by SteelSlayer** [comment]
The only thing I don't like about the sprites are the keyboards. They look like checkerboards, and have no depth. I would prefer TG's keyboards in this case.

**Comment by DogsParadise** [comment]
> The only thing I don't like about the sprites are the keyboards. They look like checkerboards, and have no depth. I would prefer TG's keyboards in this case.

the one keyboard that you see of TG in this picture. Isn't actually their keyboard, you do know this right?

**Comment by SteelSlayer** [comment]
> 
> 
> > The only thing I don't like about the sprites are the keyboards. They look like checkerboards, and have no depth. I would prefer TG's keyboards in this case.
> 
> the one keyboard that you see of TG in this picture. Isn't actually their keyboard, you do know this right?

I assumed it was, given that you wrote `TG VS Mine:` above the screenshot which showed the comparison.

**Comment by DogsParadise** [comment]
> > > The only thing I don't like about the sprites are the keyboards. They look like checkerboards, and have no depth. I would prefer TG's keyboards in this case.
> > 
> > 
> > the one keyboard that you see of TG in this picture. Isn't actually their keyboard, you do know this right?
> 
> I assumed it was, given that you wrote `TG VS Mine:` above the screenshot which showed the comparison.

For both it's the basic without keyboard ;p
For reference tho, I do like TG's keyboard. More than my current ones, think I need to re-do those when this PR gets. some approvals, so it's a good note either way.

TG consoles for reference:
image

**Review by dearmochi — APPROVED** [review]

**Comment by S34NW** [comment]
Is this still being actively developed?

**Comment by variableundefined** [comment]
This PR has been rendered moot by the TG consoles sprites being merged in.

**Comment by SabreML** [comment]
> This PR has been rendered moot by the TG consoles sprites being merged in.

I'm not sure I understand this closure reason. Has the spriting project changed to be a full 'TG sprites only' replacement, rather than having our own custom ones made for Paradise?

**Comment by PacifistDalek** [comment]
Seconded, now that the TG sprites are in, now is the time to start looking at improving on what tg had, and I'd say these sprites are a lot better. Or is it that the pr should start fresh now that the TG sprites are in?

**Comment by DogsParadise** [comment]
> This PR has been rendered moot by the TG consoles sprites being merged in.

Yeah I personally don't understand this closure either. This has just been on hold forever because I couldnt get a reaction and I am 100% sure the tg ones wasnt meant to replace this but as a step in the middle....

**Pull request closed without merging**
