### PR TITLE
[DELTA] Map fixes

### LINKED ISSUE #9680: [Delta] Mechanic missing fuel tank
No need for big text here, plain and simple as in title. Mechanic doesn't have any welding fuel tanks in their office.

### LINKED ISSUE #9681: [DELTA] No Null Rod for Chaplain
**Problem Description**:
The Chaplain has no null rod in his quarters, locker, or anywhere.

**What did you expect to happen**: 
I went to grab my null rod and expected to find it somewhere in the chapel and select my holy weapon

**What happened instead**:
No null rod found anywhere after looking around entire chapel

**Why is this bad/What are the consequences:**
Chappy needs his holy weapon for anti vamp and anti cult abilities.

**Steps to reproduce the problem**:
1: Spawn as Chaplain
2: Try to find your trusty obsidian whapping stick
3: Fail

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was not a case of me latejoining after it had already been taken. I was a brand new roundstart chappy and looked for it immediately.

### LINKED ISSUE #9682: [Delta] Invisible locker in dorms
**Problem Description**:
Invisible locker in Dorms

**What did you expect to happen**: 
The locker being visible when closed.

**What happened instead**:
The locker is invisible when it is closed.

**Why is this bad/What are the consequences:**
You could hide all sorts of stuff in there, and no one would find it since it is invisible.

**Steps to reproduce the problem**:
Go to dorms on delta station, next to the black, grey, green, pink and mixed wardrobe is a locker called "yellow wardrobe" which is invisible, the only way of opening and closing it is with the "toggle-open" command, or clicking on it with alt-clicking the floor first.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It is visible when opened, but not visible when closed.

### LINKED ISSUE #9685: [Delta] Medical Doctors Missing Patient Room Access, Which They Spawn Into.
noaccess

The patient rooms on the right can not be accessed by Medical Doctors/Nurses/Surgeons, who are the main people who need to use them.
They also spawn inside these rooms, trapping them until someone with access lets them out.

### LINKED ISSUE #9687: [Delta] Medbay Missing Items
I felt it'd be easier to lump these into one issue instead of dividing it into three or four separate ones.

Medbay is currently missing multiple items it needs to function round start.
- The OR does not start with a bone setter or fix-o-vein.
- There is no IV drip in the blood bag freezer in the OR.
- Medbay lacks a cell charger to recharge the defibrillators.
- Patient rooms have IV drips, but no blood bags.

I bring up patient rooms lacking blood bags because there is only one freezer of blood bags in Medbay, compared to Cyberiad's four freezers and Metastation's three freezers. Deltastation is woefully under-supplied with blood round start.

### PR DESCRIPTION
**Pull request by lass9030**
This should fix several issues noted on Delta.
Fixes #9680 - Fuel tank
Fixes #9681 - Null Rod
Fixes #9682 - Invisible locker
Fixes #9687 - Missing items in medbay
Fixes #9685 - Patient room access

#9686 My fix is only temporary, until someone better than me can fix it.

:cl: Alonefromhell
add: Delta - Added a fuel tank to mechanics room.
add: Delta - Added a Null Rod to Chapel office.
add: Delta - Added Bone Setter, Fix-o-vein and IV drip to OR.
add: Delta - Added a Cellcharger to Cryogenics.
add: Delta - Added freezer with blood bags to patient rooms.
tweak: Delta - Patient room doors are set to civilian access.
tweak: Delta - Morgue temporarily uses Medbay access.
fix: Delta - The yellow locker now has the correct icon.
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
Travis failed.

**Comment by lass9030** [comment]
Someone else will be taking over this.

**Comment by Spartan6** [comment]
I wonder who

**Comment by SamHPurp** [comment]
I am sorry, I apologied to author and promised I'd spend time helping him

**Pull request closed without merging**
