### PR TITLE
[DNM] Some absolute insanity performance hacks

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
POTENTIALLY unlocks a bunch of free performance

<details>
<summary>Nerd explanation</summary>

By default, rust compiles things in a way where they should work everywhere, meaning that the rust library could in theory run on a pentium 4. This is great for compatibility, but we get no performance gains for the plethora of new X86 instructions added on modern CPUs.
image

This PR adds a `rustlibs_prod.dll` compiled for the `raptorlake` target. This is a separate bundle, because I cannot guarantee compatibility for the devs with this, as if this uses instructions that only exist on the 14900K, we are about to get a ton of random ass compatibility issues, and I aint dealing with that.

To compile this, you just run: `RUSTFLAGS='-C target-cpu=raptorlake' cargo build --release --all-features --target=i686-pc-windows-msvc`

</details>

CI runs, documentation, and a bunch of other stuff will be done if this is proven to be stable.

## Why It's Good For The Game

Free performance

## Testing

Prod is my testbench

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

## Changelog

:cl: AffectedArc07
experiment: Added Performance
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
This seems to be stable, need to do the GHA build for it

**Comment by AffectedArc07** [comment]
!build_rust

**Comment by AffectedArc07** [comment]
@FunnyMan3595 so I reran the build to see if it uses the .yml from this PR, and, it doesnt, however the files have changed drastically and I want to know if you can see anything up with it.

**Review by FunnyMan3595 — APPROVED** [review]
LGTM, sorry for not responding sooner.

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
