### PR TITLE
Street Judge armor and helmet resprite

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Resprites judge dredd armor up to modern standards 

## Why It's Good For The Game
unification of style, quality and palettes

## Images of changes
image
image

## Testing
lined up security force, made them the Law

## Changelog
:cl:
imageadd: New sprites for street judge armor and helmet
/:cl:

### CODE REVIEW

**Review by Spaghetti-bit — APPROVED** [review]
approved for code.

**Comment by lewcc** [comment]
Screenshot_20240625-201450
Looks like you have some duplicate icon states in dmis.

**Review by Fordoxia — APPROVED** [review]
As a longtime reader of Dreadd, I approve.

**Review by lewcc — APPROVED** [review]
code lgtm

**Comment by ATP-Engineer** [comment]
LAW

**Pull request closed without merging**
