### PR TITLE
Adds a move intent button for Cyborgs and Maintenance Drones

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds a 'toggle move intent' button for Cyborgs and Maintenance Drones.

## Why It's Good For The Game

Cyborgs and drones seem to get stuck walking a lot, and currently the only way to fix it is to type `toggle-walk-run` into the bottom command bar thingy. Which isn't exactly common knowledge.

## Images of changes

aXoYVzi4xC
*(Fixed the scan lines changing but I can't be bothered to make another gif)*

## Changelog
:cl:
add: Added a 'toggle move intent' button for Cyborgs and Maintenance Drones
/:cl:

### CODE REVIEW

**Comment by moxian** [comment]
Can we instead disable robot walking altogether? I can't think of a single reason for it to be there.

(The icons are very cool though!)

**Comment by procdrone** [comment]
> Can we instead disable robot walking altogether? I can't think of a single reason for it to be there.
> 
> (The icons are very cool though!)

well, its not supposed to be a thing either way, if you want to go that way, look at this PR as a quick stopgap between a better fix and current mess

**Review by farie82 — APPROVED** [review]

**Comment by hal9000PR** [comment]
It could be used for a nukie sabotage Borg to blend in, because a borg moving at full speed round start is awfully suspicious.

**Comment by SabreML** [comment]
Finally thought of an actual gameplay reason for borgs to walk rather than run:
Holobarriers!

**Review by Dumbdumn5 — APPROVED** [review]
As I don't play borg, I didn't even know this wasn't a thing. That said, how the hell has this never been a thing? :+1:

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
