### PR TITLE
Adds a 6th Vulpkanin tail option v2

### PR DESCRIPTION
**Pull request by Allfd**
This adds a 6th Vulpkanin tail option.

4e1635013757818cad65403956b2887d

:cl: Alffd
rscadd: Added a 6th Vulpkanin tail option.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
There ya go, that's the proper way to do it.

**Comment by FlattestGuitar** [comment]
👌👌🐕🐩👌

**Comment by IcyV** [comment]
If I'm not mistaken after comparing it to the other sprites, isn't it just a slightly more straight version of one of them?

**Comment by Allfd** [comment]
@IcyV 

Essentially so, 

It is a shortened, straightened and reduced version of the primary one with a different animation on East/West.

Alternatively its the shortened one with a different angle and animation.

**Comment by IcyV** [comment]
Ah. Any chance for an individual gif for front/side/back? Harder to directly compare with it spinning away.

**Comment by Allfd** [comment]
@IcyV 

Added

**Comment by sasanek12** [comment]
@Allfd  Might want to correct the typo in changelog.
Apart from that, :+1: .

**Comment by Allfd** [comment]
@sassanek12

Done, thanks for pointing that out.

**Comment by FlattestGuitar** [comment]
Can we stop buffing Vulpkanin?

They're already an incredibly overpowered race with thir massive heat resistance and additional claw damage and now this?

**Comment by IcyV** [comment]
Thought on it a bit more and it just looks very rough and pixely. The current tails are fairly smooth in their animations and this wouldn't quite match them. It also feels like the tail changes entirely when it changes direction.

**Comment by KasparoVy** [comment]
I think the wagging and static sprites look fine-- but the only gripes I have are with the side-on views both static and animated. I feel you'd have an easier time making the tail look better if it was more like 
tailmockup

if you catch my drift.

**Comment by Allfd** [comment]
@KasparoVy 

Changed per your advice, tail resting shape changed from the side, animation changed also.

@IcyV 

Smoothed animations, also changed the texturing in the tail itself both at rest and on animations.

**Comment by IcyV** [comment]
@Allfd Looks a lot more consistent now, good work.

**Comment by KasparoVy** [comment]
Wow, looks way better. Good job! :+1:

**Comment by Allfd** [comment]
@IcyV 
@KasparoVy 
Thanks!

**Comment by KasparoVy** [comment]
Wait, hold on @Fox-McCloud, he didn't actually push the commit that had the new sprites in it!

**Comment by Fox-McCloud** [comment]
Derpppp, should have looked at that more closely.

Oops.

**Pull request merged**
