### PR TITLE
Smaller thunderdome.ogg with artist metadata.

### PR DESCRIPTION
**Pull request by Baa14453**
## What Does This PR Do
Replaces thunderdome.ogg with a much smaller file and artist metadata to satisfy the license requirements.

## Why It's Good For The Game
We gain the moral high-ground and reduced download times for new players.

## Images of changes
image

## Changelog
:cl:
tweak: Decreased download time for new players by reducing thunderdome.ogg filesize by 89%.
fix: Added missing metadata to thunderdome.ogg
/:cl:

## Other Details
The license of thunderdome.ogg requires artist recognition and now that we know who made it we can finally satisfy that!
thunderdome.ogg is licensed under [Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)](https://creativecommons.org/licenses/by-nc-sa/3.0/)

Song artist: MashedByMachines
Song title: Sector11
Song Source: https://www.newgrounds.com/audio/listen/312622

Other artist pages they'd like to plug:
https://mashedbymachines.bandcamp.com/
https://soundcloud.com/mashedbymachines
https://www.youtube.com/user/mashedbymachines

I've downloaded a new copy of the song from Newgrounds and re-encoded it to .ogg with 61kb/s bitrate, I've also halved the volume to match the change you made in commit 0d061463b05ba8f3ee5cb43779d80681f767b97b. This version is *way* smaller your file was huge compared to other codebases. The new file has a bitrate of 61kbps, your file had 499 kbps, for comparison Baystation had 64kbps.

### CODE REVIEW

**Comment by Deelite34** [comment]
>  Increased download time

You might want to decrease how long it takes to download it instead of making it longer in changelog :)

**Comment by Baa14453** [comment]
> > _Increased_ download time
> 
> You might want to _decrease_ how long it takes to download the file instead of making it longer in changelog :)

Fixed that lol

**Review by Dumbdumn5 — APPROVED** [review]
Finally, now I know who to look up to find more stuff like this.

**Comment by AffectedArc07** [comment]
I'll do a listen through of them later today, to ensure quality, but it's likely fine.

**Comment by AffectedArc07** [comment]
Ok so I listened to this myself and got a few others to listen to it, and we agreed that the quality has been crushed a little too much, specifically in places like 1:30 and 2:40, where theres all sorts of weird stuff going on with the volume, and it just doesnt sound right.

I 100% approve of the metadata adding, but maybe tone down the compression a little.

**Comment by Baa14453** [comment]
> Ok so I listened to this myself and got a few others to listen to it, and we agreed that the quality has been crushed a little too much, specifically in places like 1:30 and 2:40, where theres all sorts of weird stuff going on with the volume, and it just doesnt sound right.
> 
> I 100% approve of the metadata adding, but maybe tone down the compression a little.

Yeah sorry I really messed up that version, please try the new one and let me know.
That's what I get for only listening to the first 5 seconds to check it smh

I think what happened is I compressed it twice, once after I downloaded it, once when I reduced the volume

**Review by AffectedArc07 — APPROVED** [review]
Had a detailed listen, tabbing between both tracks in a DAW. The new version has a bit of a drop in quality, but its barely noticeable, and I am willing to take the 90% filesize decrease for it. I doubt most people will notice (or care anyways).

**Pull request merged**
