### PR TITLE
Makes lethal injection syringes far more deadly

### LINKED ISSUE #1705: It's possible to survive lethal injection syringes

### PR DESCRIPTION
**Pull request by Alex6511**
Should hopefully resolve #1705

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'd recommend just making it cyandie+neurotoxin (10+40 respectively)...it also means far less of a mess.

10 cyanide will deal over 150 TOX damage nad the 40 Neurotoxin will deal 40--that's 190--given the RNG nature of cyandie, it's likely to do over 200...even if not (next to impossible), they're still going to die from OXY from being in crit.

**Comment by Alex6511** [comment]
Done

**Comment by Fox-McCloud** [comment]
That should be pretty lethal, the majority of the time.

**Comment by FalseIncarnate** [comment]
Still won't affect Synthetics, which never was an issue anyways. Sec can execute with the ion rifle far most efficiently in that matter (and does so quite happily). :+1:

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by tigercat2000** [comment]
I don't really see a reason for this. If someone survives the pretty lethal neurotoxin2, should probably note how lucky they are. Or just finish them off with like, a single punch to the face.

**Comment by Alex6511** [comment]
Whether the person dies or not shouldn't be RNG in my opinion, it happened to 2 different people within the same round. I think the changes to chem made it easier to survive than it was previously.

**Comment by Fox-McCloud** [comment]
Previous LD50 syringes (under Trekchem) were letahl 100% of the time--it just took forever. The replacements here should be no different.

**Comment by tigercat2000** [comment]
@Fox-McCloud actually those were survivable by copious doses of antitoxin

**Comment by TheDZD** [comment]
@tigercat2000 The same can be said for shoving tons of poison into somebody, then filling them with healing chems to counteract said poison. Except venom, that because that shit can gib you.

**Comment by tigercat2000** [comment]
@TheDZD True.

I don't actually have a problem with this PR; Just felt it was worth noting that it's not neccessarily necessary.

**Pull request merged**
