### PR TITLE
C.O.R.G.I AI Death Sprite Update.

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
I have decided to change my current death sprite from the default BSOD
sprite to the Alien AI death sprite from /tg/. (Same PR as before but I
messed up badly. This one is fixed.)

Image: 
ai

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Also if I didn't need paradise.dme I'm an idiot, because I don't know much about github nor how to use it, I'm not sure how to uncheck once the change is already commited.

**Comment by Krausus** [comment]
In Dream Maker, you need to go into the Build -> Preferences for paradise menu option, and uncheck automatically set FILE_DIR, or else Dream Maker will vomit FILE_DIRs all over your paradise.dme, which we won't allow to get merged in.

> Also if I didn't need paradise.dme I'm an idiot, because I don't know much about github nor how to use it, I'm not sure how to uncheck once the change is already commited.

You either need to start from scratch *without* making a mess of paradise.dme, or make a new commit that **does not revert the whole previous commit,** but just replaces paradise.dme with its current contents in the master branch.

**Comment by Ultimate-Chimera** [comment]
Fixed.

**Comment by Fox-McCloud** [comment]
as this is a custom item related thing, I don't see any reason this needs to wait the 24 hours, to be honest, especially as this is just a minor aesthetic change.

**Pull request merged**
