### PR TITLE
Delete several kinds of unticked DM files.

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do

This PR deletes more unticked files.

`/proc/spawn_rivers` is what generates Lavaland rivers, not the Lavaland DM files being deleted here.

There's a symptom and a disease, "DNA Saboteur" and "Space Retrovirus", which are not included in the DME, this code has not changed since TG disease was ported 8 years ago.

This doesn't touch the largely unticked "ninja" game mode, as it seems some items in it are available in-game.

It also doesn't touch the TGS directories, since I assume these get enabled as necessary for production.

## Why It's Good For The Game

Having unused code/files lying around gunks up refactors, can turn into broken code quickly without being compiled regularly, and if any of this is ever really needed it's in source control.

## Testing

Built and ran CI

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Thoughts on a CI stage which can compare every #include line in the DME and throw up an exit(1) if files exist that aren't included in the DME?

Any language is fine, but preferably python or bash to keep CI deps sane.

**Comment by warriorstar-orion** [comment]
> Thoughts on a CI stage which can compare every #include line in the DME and throw up an exit(1) if files exist that aren't included in the DME?
> 
> Any language is fine, but preferably python or bash to keep CI deps sane.

Totally, I can spruce up the Python script I wrote to sniff these ones out.

**Comment by AffectedArc07** [comment]
> > Thoughts on a CI stage which can compare every #include line in the DME and throw up an exit(1) if files exist that aren't included in the DME?
> 
> > 
> 
> > Any language is fine, but preferably python or bash to keep CI deps sane.
> 
> 
> 
> Totally, I can spruce up the Python script I wrote to sniff these ones out.

Sounds good

**Review by Sirryan2002 — APPROVED** [review]
nothing here is actually affecting anything compiled/built so code is fine

**Pull request merged**
