### PR TITLE
Omega Weed Balance Changes

### PR DESCRIPTION
**Pull request by Dashsora**
## What Does This PR Do

This PR aims at accomplishing two things : 
**1) Bringing Omega Weed more in line with other plants by removing its snowflakey-memey volume**
     _- Removed 420 volume._ Other plants being 100.
**2) Making it harder overall to produce insanely strong stimulants/Initropidril**
     _- Changed every reagent from 15% to 5%._  Creates a lot of conflict with other chems with OD thresholds at 10% or 15%, and demands more plant harvesting/mid fight micromanagement
     _- Changed the mutation order so that Cannabis can mutate into Lifeweed or Rainbow weed, which then can themselves mutate into Death Weed or Omega weed._ While, yes, this gives a lucky botanist better chances at getting them, it increases the time commitment and amount of Unstable Mutagen required to do so in most cases.
     _- Removed Atropine._ Requires more chem work to actually produce Initropidril, and in smaller amounts.

## Why It's Good For The Game

Botany nerfs have been asked for a long time, and I think this is a pretty good and simple way to bring it down a peg without taking all the fun stuff away from that department. Yes, this only affects a single plant, but it truly is really good for pretty much everything at the moment. By itself, it has three stimulants, 90% of the chems for initropidril, one of the biggest meme chem in the game, and has the insanely big content volume to contain all of this without ever even needing densified chemicals.

## Changelog
:cl:
tweak: Changed Omega Weed's volume from 420 to 100
tweak: Changed every reagent in Omega Weed from 15% to 5%
del: Removed atropine from Omega Weed
tweak: Made it so cannabis can only mutate into Rainbow or Life Weed
add: Added the possibility for Rainbow Weed to mutate into Death or Omega Weed
add: Added the possibility for Life Weed to mutate into Death or Omega Weed
:cl:

### CODE REVIEW

**Comment by Cocacolagua** [comment]
The calm before the storm, good PR.

**Comment by SteelSlayer** [comment]
Good stuff, but keep in mind that the changelog is more for the front end users, so you need to write stuff that makes sense for someone reading the in-game changelog to understand. For example:
```
del: Removed volume = 420 under /obj/item/reagent_containers/food/snacks/grown/cannabis/ultimate
```
Chances are most people won't know what this means. So instead you can write something like:
```
tweak: Changed omega weed's reagent volume from 420 to 100
```
Same with your other lines in the CL.

**Comment by Dashsora** [comment]
> Good stuff, but keep in mind that the changelog is more for the front end users, so you need to write stuff that makes sense for someone reading the in-game changelog to understand. For example:

Ah figured the should've been convered in the what it do section and the changelogs were for a condensed of the code changes - fixed it, thanks !

**Comment by Necaladun** [comment]
420mergeit

**Review by Kyep — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Comment by Dashsora** [comment]
There was a dot missing on the omega weed's thc line somehow (005 instead of 0.05), fixed it.

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
