### PR TITLE
Makes the Engine not prebuilt at Roundstart

### PR DESCRIPTION
**Pull request by Norgad**
inb4 backlash

:cl: Norgad
tweak: The engine is no longer pre-built at roundstart. The components to construct it are located in secure storage.
add: Secure storage now has a conveyor leading to the engine room
/:cl:

Based on peoples opinions of engineers in this thread (http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=8011), as well as some threads that are too far back for me to find. This change makes engineers actually have to consider their engine setup, and makes the engineer job to not just be 'turn on tesla, build autism fort'.

engmap

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Pictures....

**Comment by Norgad** [comment]
They are things you look at

**Comment by CrAzYPiLoT-SS13** [comment]
This could work, but also may fail miserably. Neutral.

**Comment by Norgad** [comment]
As a note:
This does require there to be an AI, CE, Borg, or Captain on board to set up the engine, but in the event that none of those are present the solars can supply more than enough power for that kind of crew size

**Comment by FlattestGuitar** [comment]
Setting up the engine is hard enough for new players, this will make it near impossible, since most people have no idea what the parts for the tesla actually do. 

👎 from me.

**Comment by Norgad** [comment]
@FlattestGuitar It's really not that hard for a new player, and nine time out of ten they'll be learning how to set it up from an experienced engineer anyway. This is also make the Tesla have a higher initial cost to set up, time wise. That should stop people from defaulting to Tesla as much. This whole PR is to make engineering less 'follow the proceedure'

**Comment by Twinmold93** [comment]
This is a change I can get behind, if we had consistency in engineering.

**Comment by Fox-McCloud** [comment]
Big :-1: 

That's ugly as hell and this does nothing to solve the problme of "giving engineers something to do". 

This just makes Engine setup EXTREMELY tedious. It will take forever to get all the equipment out of the airlock, 1-2 pieces at a time.

This will just discourage engineers from setting up the engine even more and delay power coming online, horrifically, for those that do bother.

This is buyswork for the sake of busywork, which generally isn't a good way of making a job "fun".

**Comment by Norgad** [comment]
@Fox-McCloud That is assuming that engineers will construct the same engine each time. This change makes the other engines more viable to set up, allowing more variance between shifts. I could possibly even modify it to allow super-matter engines to be more easily installed, furthering the viable options available.

**Comment by Fox-McCloud** [comment]
Engineering has literally two choices of engines to set up, and both are 100% viable to set up at round-start. This isn't going to add any variation at all; it's just going to make things tedious.

**Comment by Norgad** [comment]
@Fox-McCloud Yes, but the Tesla used almost every time without fail because it is easier to set up, and requires zero maintenance.

With this setup, the tesla is harder to set up than the singulo, but runs with less maintenance. Maybe you could suggest something helpful, because if this doesn't get merged in some form, engineering is just going to stay stagnated. Perhaps I could add an area that is nicely shaped for a SM to be installed? The problem isn't that that there **arent** options available, it's that one of the options is vastly easier than all the others.

**Comment by Aurorablade** [comment]
speaking as a person who was a new engineer at one point, HAS fucked up engine setup more then once and still has engine setup anxity....no.  No. No. No. No. It just makes it harder for new people and people like me. I already panic enough AS IS about running out of SMES power for containment during set up, having to Beg the AI to open storage..or during low pop periods hope there even is an AI or its not SSD, THEN set it up. OR during low pop periods where theres jus low to NO ENGIENEERS

No. No. No. No. This solves nothing and makes it more tedious and would actually make me personally avoid engineering entirely.

**Comment by Norgad** [comment]
Okay, we've established that this change is not a good solution, but could someone suggest a possible alternate solution? I would like to fix this issue with the complete stagnation of engineering, but dropping this idea and leaving the problem isn't going to make it disappear. Any other solutions that I could work on?

**Comment by Aurorablade** [comment]
Change player mindset and habit and your have your solution.

**Comment by Aurorablade** [comment]
Actually the other thing to do is come up with fun things for engineers to do during the round..or useful things..Maybe make it so they can help upgrade things on station? Or migrate SOME of RnDs upgrading to engineering? Or make a lesser form of upgrades they can do? Make it so somethings have a chance to break and need engineers?

**Comment by Keilden** [comment]
Give engineering(and other departments) a protolathe that can print out stuff that their department uses once science has researched it(and while at it put those items in lockboxes if science prints them out). That way engineers can print out upgrade items and upgrade the machines like a engineer.

**Comment by Norgad** [comment]
@Aurorablade Your first comment is the main obstacle of improving the whole server ;v;
As for the second comment, would making engineering have an RnD server computer thing (that one you have to sync) and them giving them a printer which only makes components and RPEDs be a good idea, along with removing component fabrication from the protolathe? It always seemed dumb that science is the department upgrading the station, as opposed engineering, which would make a whole lot more sense and give engineers something to do.

@Keilden Kinda worked your suggestion into the one above.

Thanks to both of you for the suggestions.

**Comment by TullyBurnalot** [comment]
This falls under the "complexity for complexity's sake" category. It does not add anything to the game apart from an artificial time inflation. After a few rounds, everyone will be up to scratch on how to set it up, and then it'll just be exactly like it was before, except now it's a ridiculously tedious process involving the extensive use of 2x2 airlocks.

This will not increase the complexity of gameplay. Rather, it'll just frustrate Engineering players needlessly.

**Comment by tigercat2000** [comment]
this is literally just irritating as shit :-1:

**Comment by LittleBigKid2000** [comment]
:-1: What Fox said

**Comment by Regen1** [comment]
"wow I don't want to have to do all that BabyRage"

Suggest we add a silver platter item, which every engineer gets at round start, cause that's currently how their job is set up as it is now.

Tesla should be removed completely, IMO, I like the idea for a supermatter area though

**Comment by TheDZD** [comment]
If you're going to do this, at least make it so there's a better way to get all the parts through, otherwise either you're going to see engineering lacking air for the first 30 minutes of every round, or power never being set up before the SMES run dry.

**Comment by Spacemanspark** [comment]
Remove tesla being roundstart, re-add supermatter to the roundstart choices.

**Comment by Earthdivine** [comment]
To be honest field containment should always be there even if you want to remove the early round set up. That allows engineers to just drag the Singlo out if they dont want to take the time to make the safe engine, giving them a choice of the matter that is actually meaningful (Super easy set up that can escape versus longer set up thats completely safe).

Extend the size of the airlocks so if the engineers want to set up Tesla, they can get more then 2 parts through each time. 3x3 might take longer to cycle but you can fit 4 parts minimum in there so it's not a hassle in the slightest.

Might also want to add more energy to the SMES' so the station doesn't lose power with the longer set up as well.

As this PR stands right now, it won't get much backing because it makes the set up TOO long, in which engineers will be getting yelled at to set it up faster or the new players will get confused and overwhelmed.

**Comment by Regen1** [comment]
>Remove tesla being roundstart, re-add supermatter to the roundstart choices.

Yes please

**Comment by LittleBigKid2000** [comment]
Suggestion: Conveyor belts going to and from secure storage, with airtight flaps. I'd say make a room with engine parts that's basically a giant airlock with a garage door, but LINDA is too fucking slow.

**Comment by Iamgoofball** [comment]
>the plasma rad collectors are still set up by default

# biased towards singulo, please fix

**Comment by PJB3005** [comment]
@Iamgoofball of course the tesla is an awful engine game design wise. Being biased towards the singulo is a good thing.

Don't get me wrong I hate the singularity but the tesla? it's way worse.

**Comment by Iamgoofball** [comment]
@PJB3005 you wanna fuckin go????????

nah still tho

i feel all 3 engines should be equally accessable and have the same difficulty to setting up so that there isnt bias

**Comment by CrAzYPiLoT-SS13** [comment]
For once, I agree with Goofball. IMO, the best engine for the game is the
SM engine. Although it may be hard to learn how to set it up, most people
(smart people) just get an experienced engineer as a mentor and learn how
to do it. It involves both RP and know-how. It may be awkward during
low-pop rounds, but in that case, the HoP can just find someone who knows
how to set it up and give him engi access for the time-being. Like the good
old days.

**Comment by PJB3005** [comment]
@Iamgoofball now you're saying nonsense. One of the primary differences between engines is how hard they are to set up. Without this factor there will be absolutely no argument and the best engine will be even more clear cut.

If it takes an equal amount of skill to setup each engine people will always go for the best one. This is contrary to the situation we have on /vg/ where the SM is way better than the singulo but people still set up the singulo because it's a ton easier, and the AME gets set up no matter what because it's a good way to slow down the SMES discharge while a different engine gets setup, although it can't power the station itself and is high maintenance.

**Comment by Iamgoofball** [comment]
@PJB3005 well originally the tesla and singulo were supposed to be equal in power output but then memers got in the way

**Comment by PJB3005** [comment]
@Iamgoofball that still doesn't fix the fact that it's way less destructive and hugbox.

**Comment by PJB3005** [comment]
Take a look at this table of engines for /vg/:



Add the tesla as "high power, easy setup, medium expansion, indefinite reboot and medium danger"

As you can see, each engines has its ups or down. Goof right here is suggesting all of those have the same setup difficulty. Which will people go for?

That's right, the SME. (Leaving the R-UST out) Will there be much discussion on the subject other than "X is cooler and nostalgic"? No.

And like it or not that's currently how the station is setup in the way of tesla vs singulo. Singulo is just inferior.

**Comment by Iamgoofball** [comment]
ALSO, here's another kicker:

power output stops mattering BYOND the bare minimum to power the stations.

**Comment by PJB3005** [comment]
@Iamgoofball true, but there is a degree of satisfaction when you make a multi-GW engine. It's the same thing as building an autism fort.

**Comment by Iamgoofball** [comment]
exactly

thats what I was hoping for people would go for with engines is chaining them together or tinkeirng with them beyond the default setup, so that default setup was equally easy but actually tinkering for max power memes is what took effort

**Comment by PJB3005** [comment]
@Iamgoofball you're forgetting that there's a factor of danger however.

The tesla does some EMPs and explosive damage (from the shitty TG wiki article), the singulo eats fucking everything. Unless the tesla moves at FUCKING HYPERSPEED you can avoid it easily too, just like the singulo.

**Comment by monster860** [comment]
Also, the locker thing.

**Comment by PJB3005** [comment]
Oh don't tell my you can hide in lockers to survive being dusted by the tesla.

Please dear god don't tell me that.

**Comment by Iamgoofball** [comment]
@PJB3005 it doesn't do explosions but we're gonna make it do that

i want to fix the locker cheese but people will bitch a shitton that "tesla is 2hard to survive!!! u can run from the singulo"

**Comment by TullyBurnalot** [comment]
For a little bit of a reality check here, adding the SM at roundstart will result in... nothing, in the long run.

Most people don't know how to set it up properly, and it's ridiculously easier to use **ANY OTHER ENGINE**. Not to mention, Atmosia.

I'm not against giving back the SM, but realistically, the vast majority of Engie teams will ignore it.

**Comment by Spacemanspark** [comment]
Better than the tesla, in my opinion.

**Comment by Regen1** [comment]
>I'm not against giving back the SM, but realistically, the vast majority of Engie teams will ignore it.

That's just plain wrong, it's an "advanced" mode for engineers, it's fun to experiment with and it's not 100% reliable

I don't know where you're getting these assumptions from, so I will only assume that they're from your own rear end

**Comment by TullyBurnalot** [comment]
Having mainly played Engineering and Atmospherics back when the SM still showed up in that tiny corner, I can guarantee a lot of Engineering teams **tried** to set it up. They failed.

Towards the end of its life cycle, barely anyone touched it. And "Path of Least Resistance" is still a thing. I am not doubting that Engies will touch it. I am doubting that a significant number of Engie teams will think of it as a primary power source, when other Engines are "Flip Switch on, kinda check up again half an hour later"

**Comment by Lady-Luck** [comment]
Can this be dependent on population?

**Comment by Norgad** [comment]
Working on changes based on current comment feedback.
(rip my inbox)

**Comment by Taaketa** [comment]
The Supermatter is not correctly stable right now anyway. LINDA has messed up the Supermatter's operation. For example, you can't hot start it at all. You can fire over 300 emitter shots into it and it doesn't start raising alarm until an 1 and 30 minutes into the round. (I believe both the shard and SM beheave like this) Even then if you've fired over 300 shots into the SM. It's also the only real way to get it to generate a decent amount of power too. Eventually after 300 shots it just goes into runaway mode and blows up.

**Comment by TheDZD** [comment]
@Taaketa that's likely an issue with the SM itself, since it was removed, then shoddily re-added with Nucleations, and didn't get any actual testing, nor the improvements ported from VG.

**Comment by Norgad** [comment]
How is the current change? Now the Singulo is just as easy to set up as before, and the tesla has extra setup time to offset it's 'set and forget' nature.

**Comment by Fox-McCloud** [comment]
Just throwing this out there.

When we had two engines at once, it didn't suddenly and magically give all the engineers tons of things to do. 

You know what happened? 95% of shifts, it sat there doing nothing, even when people knew how to set it up.

Once in a great while you'd come across an engineer who cared about pumping lots of power into the grid, but this was hardly persistent across shifts.

Contrary to some of the rose-tinted views presented both in the forum thread and here, Engineering has *always* been a "set up engine, wait around for something to go wrong" job (on Paradise at least).

**Comment by TheDZD** [comment]
Merge conflicts.

**Comment by Davdichan** [comment]
@Fox-McCloud So any chance we can get additional, optional things that would consume large amounts of power? Maybe add a buildable orbital mining laser rig off of engineering that consumes power and would need atmos hook ups like SM to keep it's temperature at the ideal state.

Miners can buy targetting beacons from the vendor that the OML could lock onto. Power and configuration of the laser and possible variable coding/mode setting of the beacon would determine the cutting pattern or blast radius that results when firing, emagging the OML could allow the engineer/operator to override the transmitted program to attempt and kill/vaporize the miner.

**Comment by Fox-McCloud** [comment]
Still think this is a bad idea, to be frank. It increases the skill threshold of setting up either engine by an enormous amount, and it delays when the engine can come online by a very lengthy margin, as well. 

It doesn't make engineering any more fun to play and doesn't add a "choice". It just adds tedium and delays things getting online sooner than they otherwise should.

**Comment by Lady-Luck** [comment]
It also makes low pop even more of a pain in the ass. I've set up the engine as CMO before. This is only going to make it even more tedious.

**Comment by TheDZD** [comment]
Eh, I'm not particularly a fan of this, although for different reasons.

I don't mind that it raises the skill floor of engine setup, because it does so by an absolutely marginal amount, considering it just becomes a matter of dragging in the power coils and wrenching them down. That said, I don't think this really adds or changes much besides just increasing engine setup times, which is really just an exercise in tedium more than anything else. Engine setup remains a one-time thing, and engineers have still have almost nothing to do for the rest of the round, unless they want to fiddle with the TEG.

**Comment by Fox-McCloud** [comment]
Going to close this. Both maintainers opposed it, and it seems the general consensus is that this does nothing to resolve the ultimate issue, not to mention the points that have been brought up here.

**Pull request closed without merging**
