### PR TITLE
Moves magistrate to a 100 security hour lock instead of karma

### PR DESCRIPTION
**Pull request by AffectedArc07**
**OH BOY LETS BE CONTROVERSIAL TODAY BABY**

## What Does This PR Do
Moves magistrate to a 100 security hour lock instead of 45 karma. 

image

Why? Because I have seen a *staggering* amount of magistrates that don't even know spacelaw properly, despite the fact that this is what magistrate is meant to be for. I feel like having it be played be players who *actually* know spacelaw (as opposed to those with large metacliques) is better for atmosphere.

## Why It's Good For The Game
See above

## Changelog
:cl: AffectedArc07
tweak: Magistrate is now on a 100 hour security timelock as opposed to karma. Your 45 karma can be refunded in the karma store.
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
I'd go so far as to have both requirements personally. However I do feel this is a step in the right direction, and will hopefully ensure that Magistrate's actually know Space Law and their role properly before selecting it.

**Comment by LightFire53** [comment]
> I'd go so far as to have both requirements personally. However I do feel this is a step in the right direction, and will hopefully ensure that Magistrate's actually know Space Law and their role properly before selecting it.

Not opposed to this as an idea, but not sure if code supports that?

**Comment by AffectedArc07** [comment]
> > I'd go so far as to have both requirements personally. However I do feel this is a step in the right direction, and will hopefully ensure that Magistrate's actually know Space Law and their role properly before selecting it.
> 
> Not opposed to this as an idea, but not sure if code supports that?

I am unsure. It may be doable, but I still feel like one or the other is the better option, and I fear a _ludicrous_ requirement may encourage grinding.

**Comment by S34NW** [comment]
>
>Because I have seen a staggering amount of magistrates that don't even know spacelaw properly

Echoing this sentiment, I've had magistrates mislabel non-contraband and S class until it was pointed out. I hope this will lead to the desired improvement

**Comment by Mitchs98** [comment]
> I am unsure. It may be doable, but I still feel like one or the other is the better option, and I fear a _ludicrous_ requirement may encourage grinding.

This is also a fair point.

**Comment by ppi13** [comment]
Having it both be karma and timed would actually be a good solution, while the sentiment regarding grinding is valid, it is unlikely to be as much of a problem as you'd think, 100 hours requires 45-50 rounds, (the extra 10-15 minutes after shuttle call is included), and if people can grind it out, then they are probably more experienced then a cmo after 10 hours of therapist.

**Comment by matttheficus** [comment]
Honestly I'd prefer it get the hour count and karma requirement or a higher hour count. I know I've personally told 100+ hour Sec officers the difference between Battery and Assault before as Magi.

**Comment by Mitchs98** [comment]
> Honestly I'd prefer it get the hour count and karma requirement or a higher hour count. I know I've personally told 100+ hour Sec officers the difference between Battery and Assault before as Magi.

Perhaps have it require Warden or HoS hours also, it's what I'd do if requiring Karma as well is too grindy.

**Comment by LordShekelstein** [comment]
> I fear a _ludicrous_ requirement may encourage grinding.

Did the karma system ever _not_ encourage grinding for _those_ kinds of people? I think this change is a good step forwards all in all.

**Comment by Necaladun** [comment]
@AffectedArc07 - approve this, would prefer both. I'd like to know how many people are magistrates without the 100 hours as it is if you could DM me that? No rush, I'll approve this regardless.

**Comment by KrossarnTom** [comment]
I would even like it to have both the 100 hours of security hours as well as some command hours. As this is a command role and quite the important one. The magistrate have the final say with prisoners ruling and im not sure just playing security makes the person mature enough for the role.

**Comment by Landerlow** [comment]
I like this change. Personally I would be even more in favour of having both the karma *and* the playtime requirement. 
I feel for a role as magistrate, 100 hours is .. still not that much.

**Pull request merged**
