### PR TITLE
Implements Better Venus Human Trap Sprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
The previous human trap sprite was...a coder sprite. This is much much better.

Credit to FullofSkittles

:cl: Fox McCloud and FullofSkittles
add: Changes the Venus Human Flytrap sprite
/:cl:

### CODE REVIEW

**Comment by Ionward** [comment]
Hey, for being a coder sprite, it had shading at least. Looks much better though, very mean and green 👍

**Comment by taukausanake** [comment]
I like the old one. It has character but could do with directions

**Comment by Mitchs98** [comment]
What's the new one look like even?

**Comment by MRgaty** [comment]
An image could help us see the comparison.

**Comment by taukausanake** [comment]
I learned how to use the IconDiffBot so I don't have to go dmi diving anymore :D

**Pull request merged**
