### PR TITLE
Changes all .len to length() where applicable

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Changes all instances of `.len` to `length()` where possible.
Also slightly cleans up code wherever possible

## Why It's Good For The Game
It's our standard here, it handles extra nullchecks just in case and it's our standard here.

Regex used for the final push was 

```
(\w+)\.len([^a-zA-Z=\+\-]) // This, and some minorly changed versions to do the bulk of the changes

length\((\D+)\) =[^=] // To fix most of the mistakes

\+\+length\((\D+)\) // To fix more mistakes
```

## Testing
Loaded in, no runtimes, station wasn't cut in half

## Changelog
NPFC (Hopefully)

### CODE REVIEW

**Review by FunnyMan3595 — APPROVED** [review]
* Ran my own regex on the problem.
* Manually inspected diff from DGL's, cleaned it up, sent the extra stuff I caught in.
* Did a full pass through the PR scanning for obviously-wrong things.

LGTM, but I've requested a short TM due to the volume of changes, just in case.

**Review by Oyu07 — COMMENTED** [review]
length(list) // null list
Will just read 0, no need to do null checks

.len would runtime, length is fine

**Review by AffectedArc07 — APPROVED** [review]
Approved what I own

**Comment by FunnyMan3595** [comment]
> length(list) // null list Will just read 0, no need to do null checks
> 
> .len would runtime, length is fine
> 
> Edit: if my laptop wasnt running at -2 fps looking ay diffs, I would comment all here. I _can_ try

We should probably do this as a separate cleanup, because there are likely to be instances that already use length().

**Comment by DGamerL** [comment]
> > length(list) // null list Will just read 0, no need to do null checks
> > .len would runtime, length is fine
> > Edit: if my laptop wasnt running at -2 fps looking ay diffs, I would comment all here. I _can_ try
> 
> We should probably do this as a separate cleanup, because there are likely to be instances that already use length().

Yeah, I'll be applying the changes for now, but this preferably should all be done in a future PR

**Review by S34NW — APPROVED** [review]
TM has been fine, merge time

**Pull request merged**
