### PR TITLE
Makes wall lockers more consistent with other lockers

### PR DESCRIPTION
**Pull request by Spacemanspark**
## What Does This PR Do
Makes wall lockers more consistent with other lockers. Instead of clicking on them to get free items and having to sacrifice your firstborn to actually open the dang thing (which never dropped the items that you can obtain from it in the first place), you just click on it to open, items already inside.

## Why It's Good For The Game
Consistency!

## Changelog
:cl:
tweak: Yo yo those WALL LOCKERS now open when you CLICK on them. Amazing, huh?
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
wait what I tested and compiled this multiple times
travis I swear to fuck

**Comment by Spacemanspark** [comment]
get fucked travis

**Comment by Fox-McCloud** [comment]
This has been this way forever and is one of those little quirks I'd really rather not see go away, especially since these act more like dispenser.

I'm fine with the quirks and the time honored confusion of utilizing these that surrounds it.

👎

**Comment by ZomgPonies** [comment]
Consistency is good. I don't think "Because it's always been this way" is a really legit argument in it's favor. What are the clear advantages of the current system versus the benefits of more consistency?

**Comment by Spacemanspark** [comment]
>This has been this way forever

This has never been a legitimate argument for the removal or updating of any feature we've had here before. In fact, most people that make this argument are generally shot down pretty quickly.

>and is one of those little quirks I'd really rather not see go away, especially since these act more like dispenser.

It's a locker in name, code and form. If it wants to be a dispenser, it should have been named and coded around as such.

>I'm fine with the quirks and the time honored confusion of utilizing these that surrounds it.

I'm fine with quirks and even confusing ones... but, again, it's a locker. It should act like one, and codewise this is much cleaner.

**Comment by AffectedArc07** [comment]
image
You have offended Travis

**Comment by Spacemanspark** [comment]
He started it

**Comment by Spacemanspark** [comment]
Would like to note that this isn't really a feature removal, as it still works mostly the same as before.

Also, an update as to where this is headed would be appreciated, although I'm aware that this is a fairly low priority PR.

**Review by variableundefined — APPROVED** [review]
This minor change has been stuck for long enough. Approving it.

**Pull request merged**
