### PR TITLE
Science Goggle Analysers

### PR DESCRIPTION
**Pull request by Robertha89**
Ports https://github.com/tgstation/-tg-station/pull/12217

This adds an analyser to Science Goggles, and adds Night Vision Science Goggles, these allows a scientist to detect the components in a machine without having an RPE handy, it also allows for analyzing the research value of an item, how much materials you can gain from it, and so on.

Image below shows everything, it is also toggelable, for dem chemists.

image

A huge thanks to @GunHog for helping me with this, and creating this thing in the first place.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
As this is a WIP on TG, going to mark this as DNM.

**Comment by Earthdivine** [comment]
Finally a use for the dang things.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by GunHog** [comment]
I am sad you guys do not have the RD hardsuit. It is awesome, I think you should. Anyway, I will give you lot a ping when my PR on /tg/ is finalized. Note that it is trivial to give this ability to other mobs such as silicons. If your codebase has non-human mobs that often work in Science, I would recommend giving them such consideration.

**Comment by Robertha89** [comment]
This fixes the last issue in a less then elegant manner, currently everything is working as expected, and is ready for merge, unless there is a wish for cyborgs or drones to have this too.

**Comment by GunHog** [comment]
Please review my PR, I found an easier way to obtain the correct names!

**Comment by Robertha89** [comment]
Explains why it did not work when i tried that proc out.

**Comment by Fox-McCloud** [comment]
I'd go ahead and give it to borgs and drones---gives them something to do if they're really bored.

"oh, I didn't know that had that in it..."

**Comment by Robertha89** [comment]
What about AI's, give em that too?

**Comment by Fox-McCloud** [comment]
@Robertha89 

Nah--they have enough buttons and things to worry about.

**Comment by GunHog** [comment]
I would have added reagent container contents viewing, but such is not restricted on /tg/. My decision not to add them to the AI was quite simple: They cannot examine things easily. Examine for AIs only works near the core, and if you can get access to a carded AI, you could probably get a pair of Science Goggles somewhere.

**Comment by Fox-McCloud** [comment]
@GunHog 

I thought AI's could examine things with a shortcut?

**Comment by GunHog** [comment]
Only things within screen range of the physical core, so this feature would only be useful to carded or mech pilot AIs.

**Comment by Robertha89** [comment]
AI's here can examine anything holding CTRL+SHIFT i believe, and yes, we had that thing before too.

**Comment by GunHog** [comment]
Oh, that is interesting! Well, then it is up to you guys if you want to include the AI or not. Giving any non-human mob a built in scanner is a simple matter of adding ```scanner.Grant(src)```` to the target mob's New().

**Comment by Alex6511** [comment]
@Fox-McCloud Ai already has a button for this, toggle overlays. Just add it with the sec and medihud. No reason not to unless it's balance.

**Comment by Robertha89** [comment]
That gave me an idea, something i wanna add to it.

**Comment by Robertha89** [comment]
Actually, nevermind that, this is ready to merge.

**Pull request merged**
