### PR TITLE
First step Metastation Fix (Issue #13950 and more)

### PR DESCRIPTION
**Pull request by Varghh**
## What Does This PR Do
Multiple fix for issue #13950 , most of the problems there where fixed, all cables where changed, pipe-nets where remade and many more things where added, there's still a lot of work to do but i don't want this PR to be so big, i will keep working on the station in the future.

## Images of changes

Examples of minor fixes in Issue #13950 

Before
plat2

After
plat1

Before
engiwire1

After
engiwire2

Before
atmos2

After
atmos

---

Suit storages instead of hardsuit racks, departamental ID computers added for every head office.
captain suit storage
Id computer hardsuit

---

Cargo Sec Checkpoint is now a break room.
cargocheckpoint

Engineer Sec Checkpoint is now Drone Fabricator.
engisec1

Medbay Checkpoint was transformed into a bigger Paramedic room and a Blood bag storage.
medbaycheckpoint

Science checkpoint is now a "mad scientist" area for shenanigans.
sciencecheckpoint

---

Useless Tcomms room in engineer is now a Clown Mime old place
tcom

---

Small but now Clown and Mime has a room and new spawn areas.
clownmime

---

Morgue is still ugly has fuck and should change with a medbay remap, for now i added the coroner locker and re organized a lot of things.
morgue

---

Now useless Oil Tank in robotics moved and replaced with an Anesthetic locker.
robotics

---

Public Autolathe in science lobby got nuked and replaced with a cool plant
pautolat

---

I still need to separate Science Chem from Xenobio, it's going to be a big change because science chem needs to get a new bomb/grenade test area. For now i added the reinforced floor at the test area like AA asked.

xenobiochem

## Why It's Good For The Game
One step closer to map rotation, we have a lot of work ahead.

## Changelog
:cl:

ALL THIS CHANGES ARE FOR METASTATION ONLY.

add: New areas in maints, break room for cargo, clown and mime office, missing ID computers for heads and suit storages.
del: Removed Security Checkpoints.
tweak: tweaked many pipes, zones, cables and lot more crap.
fix: Cables, tiles, pipes, rooms.
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
Suggestions:
- Keep the reinforced flooring in xenobio pens.
- Add some departmental colored floors to: the drone fabricator room, the new IV area in medbay, and the paramedic's room. Just prevents these rooms from being plain white/grey.

**Comment by Varghh** [comment]
> * Keep the reinforced flooring in xenobio pens.
fix3


> * Add some departmental colored floors to: the drone fabricator room, the new IV area in medbay, and the paramedic's room. Just prevents these rooms from being plain white/grey.
fix1
fix2



Done.

**Comment by SteelSlayer** [comment]
A few issues/observations:

Pipes are a bit off here:
image

There's a suit storage unit blocking this door by the particle accelerator, and also the blast door that was here is gone:
image

There is a single tiled floor in secure storage. Not really a big deal but I thought it was a weird addition.
image

Scrubber T pipe that leads to nothing here in the dorms hallway above the clown and mime's office.
image

**Comment by Varghh** [comment]
> Pipes are a bit off here:
> image

fix5


> There's a suit storage unit blocking this door by the particle accelerator, and also the blast door that was here is gone:
> image

fix6


> There is a single tiled floor in secure storage. Not really a big deal but I thought it was a weird addition.
> image

fix7


> Scrubber T pipe that leads to nothing here in the dorms hallway above the clown and mime's office.
> image

fix4

**Review by Dumbdumn5 — APPROVED** [review]
Though it's a fix apparently this is also a map edit, consider this the head approval, n e r d :+1:

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
