### PR TITLE
New Lobby Music!

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
Adds in Sans theme (megalovania) from Undertale for a lobby song.

https://dl.dropboxusercontent.com/u/211463060/megalovania.mp3

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Messed up, one second.

**Comment by Spacemanspark** [comment]
Well, that's something.

**Comment by Ultimate-Chimera** [comment]
I hate github!

**Comment by Ultimate-Chimera** [comment]
If somebody told me how to remove commits and stuff to github, I wouldn't have to delete and reinstall it over all the time every time I want to make a PR.

**Comment by tigercat2000** [comment]
@Ultimate-Chimera why is that always everyone's first reaction instead of bothering to learn the github interface

I can't help with the 'github desktop' client, I use bash, and can probably tell you how to use tortoise git, but the github desktop client is, first, something I have never used, and secondly, a piece of shit.

**Comment by Ultimate-Chimera** [comment]
Tortoise git or bash? Tell me more please. I can also use the git shell thingy, I don't use the desktop part often. Half if it doesn't even work, for like "pulling" etc.

**Comment by tigercat2000** [comment]
I don't know tortoisegit that well, I always use git bash, aka git-scm
First thing you would want to do with the terminal is check if upstream is set, using this
```
git remote -v
```
if the printed list does not contain something named 'upstream', do this
```
git remote add upstream https://github.com/ParadiseSS13/Paradise.git
```

Moving on, to actually update (assuming upstream is set)
```
git checkout master (always update the master branch)
git fetch upstream (this downloads any updates)
git reset --hard upstream/master (this HARD resets to upstream/master - It will erase any and all work, always develop on a non-master branch.)
git push origin master (this pushes the applied changes to github)
```

Then to checkout a new branch
```
git checkout -b branch_name (makes and checks out a branch)
```

**Comment by Ultimate-Chimera** [comment]
git reset --hard upstream/master
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by tigercat2000** [comment]
did you make sure upstream is correct and present

**Comment by Ultimate-Chimera** [comment]
Let me check again.

**Comment by Ultimate-Chimera** [comment]
Yes, it is.

**Comment by tigercat2000** [comment]
and what does git fetch say

**Comment by Ultimate-Chimera** [comment]
You do the remote on ParadiseSS13/master right?

**Comment by Ultimate-Chimera** [comment]
Nothing at all.

**Comment by tigercat2000** [comment]
what does git branch -av say

**Comment by Ultimate-Chimera** [comment]
New-Music                   c6861cd New music
* ParadiseSS13/master         baf7b4f Merge pull request #2476 from Fox-McCloud/swarmer-event-hotfix
  master                      c6861cd New music
  remotes/ParadiseSS13/master baf7b4f Merge pull request #2476 from Fox-McCloud/swarmer-event-hotfix
  remotes/origin/HEAD         -> origin/master
  remotes/origin/master       c6861cd New music

**Comment by tigercat2000** [comment]
that would probably be more understandable in a screenshot

**Comment by Ultimate-Chimera** [comment]
I accidentally made the changes on the normal master branch, forgot to make the new branch.

**Comment by Ultimate-Chimera** [comment]
Hard to read, but sure. http://puu.sh/lb61w/5f933f79b8.png

**Comment by Ultimate-Chimera** [comment]
How do you revert changes you made to the master branch?

**Comment by tigercat2000** [comment]
by hard resetting, which doesn't work at the moment
what does
git remote -v
say

**Comment by Ultimate-Chimera** [comment]
Just git remote -v?

**Comment by tigercat2000** [comment]
yes

**Comment by Ultimate-Chimera** [comment]
It just displays those things again.

**Comment by Ultimate-Chimera** [comment]
git remote -v
ParadiseSS13    https://github.com/ParadiseSS13/Paradise.git (fetch)
ParadiseSS13    https://github.com/ParadiseSS13/Paradise.git (push)
origin  https://github.com/Ultimate-Chimera/Paradise.git (fetch)
origin  https://github.com/Ultimate-Chimera/Paradise.git (push)
upstream        https://github.com/ParadiseSS13/Paradise.git (fetch)
upstream        https://github.com/ParadiseSS13/Paradise.git (push)

**Comment by tigercat2000** [comment]
and you have run
```
git fetch upstream
git reset --hard upstream/master
```
right?

**Comment by Ultimate-Chimera** [comment]
git reset --hard upstream/master
HEAD is now at baf7b4f Merge pull request #2476 from Fox-McCloud/swarmer-event-hotfix now it's in red.

**Comment by Ultimate-Chimera** [comment]
for master

**Comment by Ultimate-Chimera** [comment]
http://puu.sh/lb6hd/736ab48ea2.png

**Comment by tigercat2000** [comment]
that means it hard reset correctly, so run `git push origin master`
if that command errors, run `git push origin master -f`

**Comment by Ultimate-Chimera** [comment]
Now it's blue, I had to do the -f thing.

**Comment by tigercat2000** [comment]
that's probably how the git shell indicates changes, as your master branch is now in sync with paradise's, I guess red means unpushed changes present, blue means synced

**Comment by Ultimate-Chimera** [comment]
So it should be all reset now? All I need to do is make the changes on my branch and then push origin to master?

**Comment by tigercat2000** [comment]
no, you push origin branch_name
```
git checkout -b branch_name
changeschangeschanges
git push origin branch_name
```

**Comment by Ultimate-Chimera** [comment]
Oh, so checkout changes to the branch and then I push origin to master? Or would I push to ParadiseSS13?

**Comment by tigercat2000** [comment]
git push has two components
`git push [remote] [branch]`
so `git push origin master` pushes to the remote origin, on the branch master
`git push origin branch_name` pushes to the remote origin, on the branch branch_name

**Comment by Ultimate-Chimera** [comment]
Say I have a branch named "Paradise-Changes" I would do git checkout Paradise-Changes and then git push origin ParadiseSS13?

**Comment by tigercat2000** [comment]
no, you would do
`git push origin Paradise-Changes`
because Paradise-Changes in the branch

**Comment by Ultimate-Chimera** [comment]
Ah, and then I make the pull request from my fork? I get it now! But what do I need to do with master, is that just the changes for already-made pull requests?

**Comment by tigercat2000** [comment]
whenever you make a new PR, you should update the master branch
think of it as a tether between your repo and this repo, it should always match this repo when in use
in case you forgot the steps
```
git checkout master
git fetch upstream 
git reset --hard upstream/master
git push origin master
```

**Comment by Ultimate-Chimera** [comment]
Thanks.

**Comment by Ultimate-Chimera** [comment]
So for every change I make I should make a new branch, correct?

**Comment by Ultimate-Chimera** [comment]
Well, change for a PR. Not for every single commit.

**Comment by tigercat2000** [comment]
Branches control what goes in PR's
so if, you, say, want to update a PR that is using branch `lol_branch`
you would run `git checkout lol_branch`, make changes, commit them (however the hell you do that), then `git push origin lol_branch`

So, whenever you want to make a new PR, make a new branch from an up-to-date master branch
*always* run `git checkout -b` from `master`, `git checkout -b` copies the current branch and all of it's commits to the new branch

**Comment by Ultimate-Chimera** [comment]
Makes sense.

**Comment by CrAzYPiLoT-SS13** [comment]
I have a much simpler way. Download the desktop client and download the
repo. Get sourcetree and log in. Find the last commit before you messed up,
right click, reset branch to this commit (or something like that), just
choose the defaults and click OK. Open the built in terminal, type 'git
push - f', no quotes,  type in your GitHub username and pass, and voila.

**Pull request closed without merging**
