### PR TITLE
Tweak chair perspective

### PR DESCRIPTION
**Pull request by dj-34**
## What Does This PR Do
Tweaks chair perspective to proper 3/4
Also removes the extra fake shadow under one of the chair dir (apparently someone forgot to remove it when porting?)

## Why It's Good For The Game
I personally don't like that the chair had the wrong perspective when turned forward

## Images of changes
Before
image

Now
image

image

## Testing
Tested in game

## Changelog
:cl:
tweak: Chair perspective
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
This is going to create an unusual look when people are buckled, as part of the sprite that should be obscured by their ass will be visible. Can you perhaps work with someone to split it in two and dynamically hide the relevant parts when someone is buckled?

**Review by Contrabang — CHANGES_REQUESTED** [review]
I agree with S34N, I think this needs the old chair facing upward sprite to be made into an overlay that is applied when a person sits in it. I recommend moving the GetArmrest() down to the main chair, and applying a static image overlay when someone sits in the chair. This is a lot, so if you need help, don't be afraid to ask in #coding-chat. You'll also need to override all the subtypes of the chair that don't use an armrest
image

**Review by S34NW — COMMENTED** [review]
No changes in a few weeks, marked as stale.

**Comment by DGamerL** [comment]
> No changes in a few weeks, marked as stale.

Working on it but had some IRL stuff, will get on it this week

**Comment by farie82** [comment]
PR has been stale for a prolonged period and thus will be closed. You can reopen the PR at a later moment after the review comments have been resolved.

**Pull request closed without merging**
