### PR TITLE
Further loadout tweaks.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattestGuitar
tweak: IAAs can now select the classic secHUD in loadouts
rscadd: adds bananas and suit jackets to the loadout system
rscadd: adds dress shoes and fancy sandals to the loadout system
fix: Miners can now get the mining coat from loadouts
/:cl:

Also added a bunch of missing slashes to bandanas.

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Ey @FlattestGuitar, could I get you to add dress sandals for NT Reps and Magistrate? They're dress shoe wearers.

**Comment by FlattestGuitar** [comment]
That's the kinda of a thing to add to their lockers, I'd say. I still don't like the idea of having sandals there.

**Comment by Lady-Luck** [comment]
NT Rep already has it in their locker. Magistrate doesn't have a locker.

**Comment by Spacemanspark** [comment]
Can you add dank memes to the loadout.

**Comment by LittleBigKid2000** [comment]
Add wallets

**Comment by Fox-McCloud** [comment]
>Add wallets

No.

**Comment by LittleBigKid2000** [comment]
Why?

**Comment by Fox-McCloud** [comment]
There's no reason not to take it really, it's just free storage space. It's like saying "add a toolbelt to the loadouts for everyone". 

There's never a reason why not to take it--it's more than just an aesthetic thing, unlike most of the loadout options (which are side,grades at best, usually).

**Comment by sasanek12** [comment]
> adds bandanas 


:heart: :heart: :heart:

**Comment by FlattestGuitar** [comment]
Lord no. I'm not adding those snowflakey triangular or square pieces of cloth tied around the head or around the neck for protective or decorative purposes. Learn to read. 
🍌

**Pull request merged**
