### PR TITLE
Remaps Robotics

### PR DESCRIPTION
**Pull request by thatdanguy23**
## What Does This PR Do
Reorganizes the Robotics Lab in order to give the robonerds more space and convenient access to everything, based on @Spacemanspark 's [ideas](https://www.paradisestation.org/forum/topic/18416-remapping-robotics/). Allows people to also offer suggestions on how to improve it.

## Why It's Good For The Game
Robotics prior was a little bit too cramped, causing people to complain about a lack of space. This offers a little bit more real estate to those working in Robotics without changing too much of the actual map.

## Images of changes
EDIT - 13 JUNE 2020
image

remapped to match changes suggested on the forums
summary:
- shrunk mech bay
- made operating room take up space under mech bay
- rearranged the main robotics room again

## Changelog
:cl:
tweak: reorganized robotics & mech bay in order to create more space
/:cl:

### CODE REVIEW

**Comment by Tokorizo** [comment]
Love the design, looks a lot more spacious than our current design and I always end up trying to make as much space as possible, also a box area for surgery so people cannot disturb you is something I like as well.

**Comment by Spacemanspark** [comment]
I'd prefer the fabs up against a wall. Looks alright otherwise.

**Comment by MRgaty** [comment]
There is indeed less trash and useless stuff all over the place, quite lovely

**Comment by Fox-McCloud** [comment]
I'm partial the the assembly line/industrial implementation--it harkens back to an hold design that was put in place eons ago (2011-2012 era):

!img](https://i.gyazo.com/e41b2b7566714b00f00815a9f4247353.png)

It also has the surgery in the corner which allows for more *shenanigans*.

**Comment by pinatacolada** [comment]
if you swap out the fuel tank with a wall tank, like the one in medchem, you free up some more space. i'd say the same about the oil tank but i dont think there is a wall version of it

**Comment by Fox-McCloud** [comment]
Any plans on updating this?

**Comment by thatdanguy23** [comment]
i do intend on updating it, yup! just looking across all of the suggestions here & on the forums and I'll get to work fixing it

**Comment by Fox-McCloud** [comment]
Quite stale. This'll have to be updated+ changed, please, or this will be closed.

**Comment by AffectedArc07** [comment]
You have wiped out the tcomms on the AI sat with your latest edit
image

**Comment by thatdanguy23** [comment]
> You have wiped out the tcomms on the AI sat with your latest edit

F U C K
I'll rectify it ASAP, sorrysorrysorry

**Comment by PacifistDalek** [comment]
Still hoping to see this after the map freeze is thawed!

**Comment by Kyep** [comment]
Withdrawing my vote for this, and instead voting for https://github.com/ParadiseSS13/Paradise/pull/15064 as the latter makes more improvements and the two PRs don't seem compatible.

**Comment by Fox-McCloud** [comment]
CLosing this, upon request of @thatdanguy23

**Pull request closed without merging**
