### PR TITLE
Added queue functionality to the autolathe

### PR DESCRIPTION
**Pull request by Artorp**
Added queue functionality to the autolathe, similar to the robotic fabricator

No items in queue:
emptylist

Items added to the queue:
filled

* Items are processed at the same speed as before (around 4 s per item at lowest upgrades)
* The queue is processed automatically, can't be paused, and is cleared if there's insufficient resources
* Stacks of metal/glass/etc can also be queued

### CODE REVIEW

**Comment by Markolie** [comment]
:+1: Great addition!

Ideally we'd eventually move the materials (metal, glass) to a materials tab like the protolathe and circuit imprinter, but that's probably for a different PR.

**Comment by ZomgPonies** [comment]
Awesome! A very useful optimization, especially when it comes to autolathing shotgun shells and repetitive stuff like that.

**Comment by FalseIncarnate** [comment]
Thank you so much for this. Refilling boxes of replacement lights was more mind-numbing than having a conversation with an SSD librarian.

**Comment by Artorp** [comment]
Glad to hear it's well received!

New commit: Fixed https://github.com/ParadiseSS13/Paradise/issues/328

**Comment by fj45** [comment]
Thank you very much, the autolathe has been needing some TLC.

**Pull request merged**
