### PR TITLE
Swarmer inconsistency fixes and tweaks

### PR DESCRIPTION
**Pull request by ExusA**
## What Does This PR Do
A heavily revised and reduced version of #14175, incorporating feedback from that PR to improve the swarmers experience a tad bit. Hopefully this is moving in a slightly better direction than last time!
1. Swarmers can now decon chem dispensers and turrets. Chem dispensers, because deconstructing them doesn't conflict with their laws and the IC reason previously given of "deconstructing this would cause a chemical explosion" is just untrue mechanically. Turrets, because the reason given was that "deconstructing this would cause an immediate counterattack", which is also mechanically untrue and handwavey. Keep in mind they can only decon non-lethal or disabled turrets, since an active lethal one kills them in two shots.
2. Swarmers can no longer destroy:
- The NTnet comms relay. I think this was an oversight, swarmers aren't supposed to break comms.
- The RnD servers. Swarmers can't destroy the messaging blackbox because it contains useful data. Why would they be allowed to destroy the research data too? One of the reasons swarmers are considered annoying is that they invariably destroy these specific hard-to-replace machines, so _hopefully_ adding them to the blacklist will help out with that while not impacting the swarmers' balance that much.
3. Changed the reasons swarmers can't destroy most things from "damaging this would kill us" when it mechanically wouldn't, to "this will be useful to our masters" or "destroying this will harm biologicals" etc.
4. Swarmers now die instantly to ion rifles. Why? Well, security lasers two-shot them. Ion rifles _also_ two-shot them. That's confusing, since ion rifles are explicitly designed to kill things like swarmers; they should be more effective than basic sec lasers for that.
5. Swarmers can also now only hold 60 resources, down from 100. Doesn't affect the balance much at all since resource storage is rarely an issue, just encourages swarmers to spend their resources more frequently instead of forgetting, and hoarding 100 resources when they could've replicated twice.

## Why It's Good For The Game
Small improvements and inconsistency fixes, minor-ish impact on balance.

## Changelog
:cl:
tweak: Modifies the list of things swarmers can and can't destroy
tweak: Swarmer resource cap 100 -> 60
tweak: Ion rifles are now more effective against swarmers.
/:cl:

### CODE REVIEW

**Comment by Cocacolagua** [comment]
Should probably add to the PR description that swarmers will now have 60 resources and they will die from a single EMP.

**Comment by ExusA** [comment]
Oh heck, overlooked that. Lemme fix

**Comment by Denthamos** [comment]
These....seem like pretty heavy handed nerfs to swarmers overall and feels a bit too over the top when combining them all into a single thing instead of doing it in a step process to see how it effects the antag over time.

Also, you generally should not be putting fixed and balance changes together like this.  As per our github rules for coders:  
 **Your pull requests should be atomic. Balance changes, bug fixes and new features should all be in separate pull requests.**

**Comment by ExusA** [comment]
Hmm, I do see your point, but it seemed silly to spread this out over multiple PRs, since all of these changes are related to consistency. Can do that if it's preferable, but not sure exactly which changes to separate out and which to leave together.

**Comment by AffectedArc07** [comment]
Calling this "inconsistency fixes and tweaks" is a dishonest PR title. The diff on this PR is exactly the same as the last one, just without the turret, and with some extra messages thrown in.

Its a balance PR.

**Comment by ExusA** [comment]
This wasn't intended to be a balance PR, hence the title. It was meant to be tweaks and consistency "fixes", which i had thought describes every change made here. I'm really not trying to be obtuse or impose things people don't want with either or any of these PRs, and am completely new to any kind of open source project at all, so not sure what the done thing is in terms of what to PR and how. I reopened this based on what people said might be good on discord and the comments for the last PR, cutting out everything people objected to. Should I have just reopened the last PR, is that why it's dishonest? It feels kinda disheartening to be given feedback like "that's already a no from me" without much explanation on the last pr, and to be called dishonest on this one. Would appreciate better feedback, even things like "this is too low-effort to merge" or "you're being too forceful in the PR comments" or "turrets are a no-no because x" or "don't do balance prs"  would be useful info, and help me PR better, less terrible stuff in the future.

**Comment by Spacemanspark** [comment]
(Dis)Allowing swarmers to interact with several objects impacts balance, regardless of whether or not you're claiming it's being done to keep consistency with game mechanics. It alters game mechanics in a way that changes how players play the game.

I don't think Arc has even given his opinion on the PR itself, merely making a statement that it would be best to be more clear with your titles.

As for my opinion, I'm echoing Denth. Separate PRs need to be made based on the scope they cover, whether that be fixes or balance changes, they're separate topics.
I also agree that these changes are fairly... eh? I see no reason to alter swarmers as they are. 
I've seen swarmers as more of a supplementary antagonist, something that goes alongside other things such as terror spiders, blobs, so on so forth, to make a very dangerous threat. Alone, however, they're only meant to be giant nuisances. Non harmful to any lifeforms they come across, merely shoving them out of the way to continue performing their mindless tasks. 
I don't feel they really need to be changed, frankly.

**Comment by ExusA** [comment]
Aaagh gosh, it's apparently much harder than it looks not to get emotional and irritable about a PR being shot down, so I'm sorry for going on a rant about not getting proper feedback on it. :pensive:  If the consensus _is_ that swarmers don't need touching, I won't keep pushing for it, needlessly. Thankyou everyone on both of these PRs for what _was, in fact,_ adequate feedback, and sorry for being a bit of a shitter about it. I will _TRY_ to do better in the future!

**Comment by AffectedArc07** [comment]
Apologies if my response was off-the-cuff, but it was mainly the concern with the ability to destroy turrets, and the material storage change, not to mention the ion rifle oneshot. These are balance implications, which stem further than tweak territory.

**Comment by ExusA** [comment]
Got it, will try to name things more accurately next time.

**Comment by Denthamos** [comment]
Mmn, do not misunderstand our comments for harsh judgement.  Its just that there has been situations in the past where large sweeping changes were done and it heavily impacted the balance of what it touched and was involved with.  All of these changes together would greatly impact how players would play swarmers at a baseline due to oneshots, no more taking out R&D, and the lower resource cap combined.

If need be if Hosts and maintainers can call for a a test merge of those balance changes together separated from the comms relay and turret deconstruction changes to see how it impacts the balance of the event overall.

The comms relay change however I do see as a proper fix considering swarmers before could not take apart comms systems machines at telecomms (If they somehow got there) so personally (from a non coder standpoint) I see no problem with that getting merged in.

**Pull request closed without merging**
