### PR TITLE
Removes USSP gateway, adds nothing

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Removes the USSP gateway, does not make it a space ruin.

Edit: Makes it an admin-placeable map template, without the mobs or thunderdome section.

## Why It's Good For The Game
This gateway was always the prime "crappy gateway" for everyone involved. Bland, cheeseable, full of tider gear, unengaging.
While the other away missions have been turned into space ruins, I don't see the need to convert this one or replace it, we _have_ an interesting USSP space ruin, the ring station with it's puzzle. We do not need another.

## Changelog
:cl:
del: Removed USSP gateway
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
Is there a way to simply disable it in the config for roundstart while keeping it as something that admins can link the gateway too?(Not actually sure if that's possible at all rn or not). I say this because I know several admins use it for events, and it is a pretty good map for events.

If that's not possible good riddance. Nothing of value is lost.

**Comment by S34NW** [comment]
Yes, it can be just disabled in config

**Comment by AffectedArc07** [comment]
Absolutely yes

**Comment by Denthamos** [comment]
A slightly slimmed down version of this minus the entire thunderdome section and NPC's would be nice as a map template for event use.

**Comment by S34NW** [comment]
> 



> A slightly slimmed down version of this minus the entire thunderdome section and NPC's would be nice as a map template for event use.

this can be arranged

**Comment by Miraviel** [comment]
The `/obj/structure/closet/secure_closet/courtroom` object is unique to this map, might want to consider removing it as well.

**Review by SteelSlayer — APPROVED** [review]

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
Remove the template.

Not only will it be a nightmare to handle placing, but it doesn't fit the style of the other USSP map, and its just going to be something else to stand in the way of repath refactors.

**Review by AffectedArc07 — APPROVED** [review]

**Comment by AffectedArc07** [comment]
MDB2 is broke dw about it

**Comment by Norwes1** [comment]
If it's possible, I'd definitely like it as an option for events. I've used it before in the past, and plan to again in the future (the S.T.A.L.K.E.R.-esque event in particular has been a big hit, largely due to this particular map being wonderful for that sort of exploration). I don't mind seeing it gone from regular rotation, but I'd like an option to pull it back on occasion too.

Alternatively, if we just delete the Sec gear and TK, it becomes mostly harmless in terms of causing on-station trouble, and is simply an option for off-station shenanigans. I've heard that bounced around for ages, after all.

**Comment by S34NW** [comment]
> If it's possible, I'd definitely like it as an option for events. I've used it before in the past, and plan to again in the future (the S.T.A.L.K.E.R.-esque event in particular has been a big hit, largely due to this particular map being wonderful for that sort of exploration). I don't mind seeing it gone from regular rotation, but I'd like an option to pull it back on occasion too.
> 
> Alternatively, if we just delete the Sec gear and TK, it becomes mostly harmless in terms of causing on-station trouble, and is simply an option for off-station shenanigans. I've heard that bounced around for ages, after all.

I've forwarded the map template to admin discord if you wish to use it as a ruin. However it's too late for it as a gateway.

**Pull request merged**
