### PR TITLE
Removes all one-way airlocks except for the ones in medbay and brig

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
At the request of the staff team I removed most one-way airlocks excluding the ones at cloning, medbay and brig

**Changelog:**
:cl:
tweak: there are much less one-way airlocks on station
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Thanks a bunch for hopping right on this.

**Comment by Kyep** [comment]
I think it might still be worthwhile to have one exit-allowed door in each of the maint areas. E.g. For medsci maint, the door next to janitor could let you out. That's at most one exit-allowed door for that enormous maint area, though. Not putting it on every maint door.

I don't really mind either way, though.

My main issue with the exit-allowed doors is the fact the 4 green lines look like a graphics glitch rather than an intentional overlay on the door.

**Comment by Couls** [comment]
In that case if anyone decides to make a better sprite for this I can add the one-way exits for maints, though for now I just wanted to get what was requested in a PR

**Comment by Evankhell561** [comment]
https://github.com/ParadiseSS13/Paradise/pull/11769#issuecomment-509743212

**Comment by Couls** [comment]
I guess you can say you told me so, I'm still glad it got tested out in its current form. There was literally no harm in trying it out like that and then deciding that wasn't the way to go with it

**Comment by Evankhell561** [comment]
> Supongo que puedes decir que me lo dijiste, todavía me alegro de que se haya probado en su forma actual. Literalmente no hubo daño en probarlo así y luego decidir que ese no era el camino a seguir.

Sorry, I couldn't help saying it. Although I do not agree with all your pr. I love how all your enthusiasm and the way you work for the game <3

**Pull request merged**
