### PR TITLE
Norstead's fluff : Soviet Casual Uniform

### PR DESCRIPTION
**Pull request by GunDOSMk1**
Adds Norsteads fluff, a soviet casual uniform. Pictures below. Thanks to @shazbot194 for helping me with the sprite!

back
front
side

### CODE REVIEW

**Comment by Spartan6** [comment]
First off those remote-tracking branches made me swallow a bit of sick.

Second, what does that clothing have to do with the Soviets.

**Comment by Serkket** [comment]
Блин! This pr looks like something straight out of Eris.

**Comment by GunDOSMk1** [comment]
> First off those remote-tracking branches made me swallow a bit of sick.
Not a clue how to fix that! But hey, better than my first PR. I know what I did wrong, won't make the same mistake next time.

> Second, what does that clothing have to do with the Soviets.
🤷‍♀️ 

> Third, there is no male version, so any human or vox is going to grow breasts, regardless of gender or race.
It can be done, but it's a fluff for a female character. Don't know why it needs one.

**Comment by Spartan6** [comment]
> Not a clue how to fix that! But hey, better than my first PR. I know what I did wrong, won't make the same mistake next time.

Blerg
> Ask norstead, who's this is.

I mean, I'm not here to chase up things for a PR. PR is meant to display it.
> It can be done, but it's a fluff for a female character. Don't know why it needs one.

You can argue that with voxxyHUD, or my gas mask, but it's generally not good practice to add something that only works for one gender of one species unless you try and negate the ability as much as you can.

**Comment by Fox-McCloud** [comment]
please resolve your conflicts.

**Pull request merged**
