### PR TITLE
Reworks xenomorph space ruin: Moonoutpost19

### PR DESCRIPTION
**Pull request by kano-dot**
## What Does This PR Do

Completely remaps moonoutpost19.

the list of valuable loot it currently contains:
<details><summary>List</summary>
<p>

- 3x abandoned crates

- 500 credits (RD office safe)

- double barreled shotgun (carried over from original ruin)

- sunglasses

- combat vest

**[Below here is the content of secure vault]**

- eyepro

- research notes (same one from TS gateway and trader stuff)

- mech core

- infinite capacity powercell

- random anomaly core

</p>
</details> 

In box wise, it has the same size as original ruin (80x58). Original ruin has 15 xeno simplemobs, this one has 27 (with addition of a few sentinel xenos). Alien empress varedited to deal 20 more melee damage than before (15 -> 35 maximum damage) as it could be easily cheesed in close-quarters.

Vault area is made with indestructible variant walls to prevent loot goblins skipping all the fun.

## Why It's Good For The Game

When this ruin was still a part of gateway concept, most of the players were inclined to get out of it as there was not much of a point going through all the hassle for no loot. Its size got halved after it became a space ruin. This PR aims to fix that by spicing things up a little bit more.

Oh and now it has some references in it, we all love that.

## Images of changes

<details><summary>Original</summary>
<p>

picture

</p>
</details> 

<details><summary>Rework</summary>
<p>

anotherupdate

</p>
</details> 

## Testing

replaced the original file in testserver, it indeed spawned

## Changelog
:cl:
tweak: remaps xenomorph space ruin (moonoutpost19).
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
```
loading ./map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
error: '[' should be escaped (\[) or followed by ']'
error: '[' should be escaped (\[) or followed by ']'
error: '[' should be escaped (\[) or followed by ']'
_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm:7745:error: expected }
_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm:7745:error: expected )
Failed to load map file /home/runner/work/Paradise/Paradise/_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm.
```

Please test your code

**Comment by kano-dot** [comment]
> ```
> loading ./map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
> error: '[' should be escaped (\[) or followed by ']'
> error: '[' should be escaped (\[) or followed by ']'
> error: '[' should be escaped (\[) or followed by ']'
> _maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm:7745:error: expected }
> _maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm:7745:error: expected )
> Failed to load map file /home/runner/work/Paradise/Paradise/_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm.
> ```
> 
> Please test your code

uhh how do i fix it?

**Review by Henri215 — COMMENTED** [review]
image
This note is empty?


What is the infinite power cell? Never seen it before, is it.. 100% infinite??

**Comment by kano-dot** [comment]
> image
> This note is empty?

i have varedited ```info``` variable in any note i added to the ruin. It works but i am unsure if this is how it's supposed to be done

> What is the infinite power cell? Never seen it before, is it.. 100% infinite??

it's a loot that can be obtained through abandoned crates, with capacity of 30kw. While yellow cores has  ```chargerate = 500```, the number we have for ```cell/infinite``` is 30000.

Honestly i don't have much ideas for the loot that will be worthy of going through 27 xenos/sentinels, one varedit buffed empress and two turrets while sustaining not being gamer loot

**Comment by Henri215** [comment]
> > image
> > This note is empty?
> 
> i have varedited `info` variable in any note i added to the ruin. It works but i am unsure if this is how it's supposed to be done
> 
> > What is the infinite power cell? Never seen it before, is it.. 100% infinite??
> 
> it's a loot that can be obtained through abandoned crates, with capacity of 30kw. While yellow cores has `chargerate = 500`, the number we have for `cell/infinite` is 30000.
> 
> Honestly i don't have much ideas for the loot that will be worthy of going through 27 xenos/sentinels, one varedit buffed empress and two turrets while sustaining not being gamer loot

Look at how other ruins PRs did it, its a good idea to create a subtype to make it easier to locate and edit the texts.

**Comment by kano-dot** [comment]
i noticed that at the moment this project is far from ready to be reviewed. I'll attend to it in a further date

**Comment by kano-dot** [comment]
i hope one day i can figure out how to use github, oups

**Pull request closed without merging**
