### PR TITLE
Borgs can now play a sad trombone emote

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## What Does This PR Do
Adds a *sad emote for silicons. This will play a sad trombone

## Why It's Good For The Game

https://github.com/user-attachments/assets/ed95bbaf-4def-4dc5-943e-5e41a9e83a61

## Testing

see why it's good for the game
<hr>

### Declaration
- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/feature_freeze/CODE_OF_CONDUCT.md#currently-changes-to-the-following-types-of-content-reuires-pre-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

## Changelog
:cl:
add: Nanotrasen has added a sad trombone sound to the speakers of borgs!
/:cl:

### CODE REVIEW

**Comment by Danchi299** [comment]
add a slow clapping module while at it :P

**Comment by lewcc** [comment]
This seems a little silly for every cyborg to have. I think it'd make more sense if only service borgs could use it. At that point, you're committing to the bit.

**Comment by FunnyMan3595** [comment]
I could see this as part of a "sound effects" module on the service cyborg, but it doesn't make sense to me as an emote for all cyborgs.

**Comment by Denthamos** [comment]
Agreeing with funny on this one.  I can see it for service but not all borgs.

**Comment by S34NW** [comment]
This PR has unfortunately failed to pass the relevant team vote, with 1 for and 3 against.
Some of the reasons for objection include (anonymised):

- Realistically: Makes sense. However I don't trust some cyborgs with it., will likely be abused too much

(Other reasons commented on the PR already)

Please feel free to discuss this with the relevant team and see if you can rework it into something acceptable to them.

**Pull request closed without merging**
