### PR TITLE
Makes cargo firelocks less painful

### PR DESCRIPTION
**Pull request by AffectedArc07**
Removes the god awful firelocks near the shuttle.

:cl: AffectedArc07
tweak: Cargo shuttle firelocks have been removed.
/:cl:

### CODE REVIEW

**Comment by Cid777** [comment]
It was a bit redundant anyway, since while the shuttle is docked there's no risk of depressurizing, and the dock airlocks bolt shut when it departs, so depressurizing can't happen.

**Comment by Citinited** [comment]
You've got a merge conflict

Updating your fork to the latest version of Paracode, then redoing your changes should fix this

**Comment by alexkar598** [comment]
Merge corn flakes!!!

**Comment by alexkar598** [comment]
Did you use map merge?

If not then use map merge that's what causing the merge cornflakes

**Comment by AffectedArc07** [comment]
I will use map merge then fix this

**Comment by AffectedArc07** [comment]
Closed as I am making a new one to fix metastation too

**Comment by SamHPurp** [comment]
@AffectedArc07 you shouldn't need to close to fix or anything. Just hit me up on Discord mate.

**Pull request closed without merging**
