### PR TITLE
Adds Hellhound, minor outfit tweaks

### PR DESCRIPTION
**Pull request by Kyep**
This PR adds a new monster - the hellhound.

It looks like this:
hellhounds2

Sprites are from FoS, and credited in the file.
The top left is its resting sprite, the top right is its dead sprite.

It comes in two varieties: lesser and greater.

The lesser version has slightly better health/damage to Sgt. Araneus, with three notable special abilities:
- The ability to demon whisper to nearby mobs, similar to other demons.
- While resting, he will lick his wounds to help close them, and regenerate health.
- While attacking a human, he will emit hellish smoke, which can paralyze them if they don't have internals active.

AI controlled hellhounds will intelligently use their resting/smoke abilities when the situation calls for it. IE: they will smoke enemy humans as soon as possible in the fight, then rest afterward the fight is over to heal damage, going back into combat mode if another target gets near them.
The greater hellhound is the same as the normal hellhound, except with higher health, damage, and an ominous red glow. The greater hellhound is adminspawn-only, primarily because the lesser hellhound is already dangerous to unprepared players. 

This PR also makes a few minor tweaks to admin outfits:
- The ancient vampire gets the ability to shapeshift into a lesser hellhound. He was the original inspiration for me to make the hellhound.
- The special ops officer loses their nodrop implant (it is no longer required) and has their centcom combined arms implant updated to use the M-1911P as its icon, rather than the old weird electrical arm thing. I did this because an admin did not seem to notice it on the hud, due to its icon.
new_specops_hud

:cl: Kyep
add: Added hellhound, a dangerous new monster.
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
SCREENSHOTS

**Comment by Kyep** [comment]
Screenshots were added less than 60 seconds after the PR was posted.
You just gotta allow a few seconds for me to upload them into the spots reserved for them.

**Comment by TDSSS** [comment]
So when/how do these monsters spawn?

**Comment by Kyep** [comment]
Greater: adminspawn only.
Lesser: can in theory be created in a hostile gold slime reaction, or in a dimensional tear. I feel like existing hostile mobs tend to go down in two hits from a common welder. I will make them purely adminspawn only though if people prefer that.

**Comment by tigercat2000** [comment]
@Kyep Could you redo the screenshots with nearest neighbor interpolation enabled? They look like shit from the sides due to the vertical anti-aliasing going on.

**Comment by Kyep** [comment]
Done.

**Comment by taukausanake** [comment]
South facing icon has weird looking back feet. They stick out a bit like duck feet

**Comment by Kyep** [comment]
I think they're okay.

**Comment by KasparoVy** [comment]
I dig the idea but the hard edges and back feet don't sit well with me. South facing back feet's toes sgouod probably be made less prominent

**Comment by KasparoVy** [comment]
Oh well.

**Pull request merged**
