### PR TITLE
RnD Console Permissions are more Persistent

### PR DESCRIPTION
**Pull request by Crazylemon64**
Screwdrivering the robotics console twice won't lock them out forever, and if something happens the RD can now swipe their ID past the console board to adjust its permissions between the four presets that already exist on the map. I've now also added a public console type if the RD wants to give a research console to a department that isn't one of the 4 existing types, or something.

* R&D console permissions don't vanish with a sneeze anymore; You can deconstruct the console, grab the board, and put it elsewhere and have it keep the same permissions
* The RD or equivalent can use their ID to reconfigure an existing R&D console board between the 4 pre-existing presets
* Locking an R&D console is obsolete, and thus I've made it superded to avoid confusion
* The RD swiping on the console board can now also create a public R&D console, for if they feel generous during nations or something

### CODE REVIEW

**Comment by Ar3nn** [comment]
Maybe make it so an emag would substitute for the RD's ID? Or make it somehow hackable, because locking the board to RD would be weird for, say, the mechanic on Nations, unless it can remember its former configuration now or something? I remember once during the Nations test, there was one engineer in atmosia, so I buddied up with them and tried to move my workshop, but ended up with a core RnD computer, so I couldn't use my equipment because there was no Mechanic RnD to sync up to.

**Comment by Fox-McCloud** [comment]
Don't really see the need for the lock change with the access change you made.

**Comment by Crazylemon64** [comment]
People were complaining that the lock was useless because of the double screwdriver trick - since I was already tweaking the research console file, I felt it was fitting to make that option to actually do something. Should I tear the lock function out entirely?

**Comment by Crazylemon64** [comment]
@Ar3nn You can take out the board of your console and it'll completely remember its permissions, and you can then reconstruct it elsewhere just fine.

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

AH! They were referring to the lock's uselessness back when there was no access check on the console.

Someone would lock the console---another player would come along and see that it was locked and couldn't be unlocked without a science ID, so they'd just screwdriver it, re-screwdriver it, and bam---console unlocked and no science ID required.

It's not a problem now that the R&D console actually checks for access, so I wouldn't worry about adding that extra functionality, personally.

**Comment by Crazylemon64** [comment]
Mmm, yeah. I'll see about obliterating that obsoleted functionality, then

**Comment by Crazylemon64** [comment]
Hold on, I'll see about creating a public R&D board type, if the RD is feeling generous during nations, for example

**Comment by Crazylemon64** [comment]
Oh, and @Ar3nn: An emag will remove all access restrictions on a R&D console, so there's not much need to let an emag also reconfigure the console board, since you can just construct it and swipe.

**Comment by Fox-McCloud** [comment]
>Hold on, I'll see about creating a public R&D board type, if the RD is feeling generous during nations, for example.

thanks.

**Comment by Ar3nn** [comment]
Well, certain machines only sync to certain server consoles, and they have to be in the same general area. Making an uber-secret science ripoff area would be pretty hard if you couldn't have all the servers without a dumb-as-rocks RD authorizing a core, robotics, etc board to be released at once.

**Comment by Crazylemon64** [comment]
The machines can link to all types of R&D console; as long as it is a R&D console, it can be linked to. @Fox-McCloud Is the existence of a public R&D console type a problem? I didn't see it coming up as much of an issue from the time before stricter console permissions...

**Comment by Fox-McCloud** [comment]
No, I like the idea a lot.

**Pull request merged**
