### PR TITLE
Wall Rechargers Cannot be Unwrenched.

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
You can no longer unwrench a wall-mounted recharger to drag it around.

## Why It's Good For The Game
Dragging these things around is all kinds of cursed.

You can still disassemble them.

## Testing
I couldn't wrench the wall chargers.

## Changelog
:cl:
tweak: You cannot wrench a wall recharger.
/:cl:

### CODE REVIEW

**Comment by Hematoma** [comment]
If items can't be disassembled, it becomes much harder to repair or reconfigure a space. Fixing something that can't be taken apart is nearly impossible, and if it's indestructible, that's even more problematic. I'm really not in favor of adding more such items to the game than we already have.

**Comment by Fordoxia** [comment]
> If items can't be disassembled, it becomes much harder to repair or reconfigure a space. Fixing something that can't be taken apart is nearly impossible, and if it's indestructible, that's even more problematic. I'm really not in favor of adding more such items to the game than we already have.

These only appear on a single tile outside the armoury. If something has destroyed that wall, you can bet your ass whatever did it has probably also destroyed the rechargers.

They're not indestructible (they also do not have density).

**Comment by Kenionatus** [comment]
What's the problem with people being able to turn them into normal rechargers?

**Comment by HMBGERDO** [comment]
> These only appear on a single tile outside the armoury. If something has destroyed that wall, you can bet your ass whatever did it has probably also destroyed the rechargers.

That is not true, there are more than just those two at the armory, various on map type. 
Why dont you block only unwrenching, let people disassemble them if they need to?

**Review by Sirryan2002 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]

**Pull request merged**
