### PR TITLE
Stops Araneus from breaking that one table every goddamn shift start

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Before:
img

After:
img

Result:
img

🆑 FreeStylaLT
tweak: Changed Araneus' spawn location so he wouldn't break tables at round-start anymore
/ 🆑

### CODE REVIEW

**Comment by Birdtalon** [comment]
He'll still break the Head of Security. 👍

**Comment by alexkar598** [comment]
Question would the spider break the window?

**Comment by Spacemanspark** [comment]
Not in one hit.

**Comment by SamHPurp** [comment]
How does this have no conflicts, yet the PR that merged an hour or two had map-edits?

Is this how we keep reverting fixes over and over and over? Whats going on?

**Comment by Vivalas** [comment]
If they're both mapmerged there shouldn't be any conflicts.

**Comment by SamHPurp** [comment]
@Vivalas thats not how that works.

**Pull request merged**
