### PR TITLE
Cyberiad dorms remap

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Well, the last thing on my immediate remap list is here, I'm sure the maints will be glad to hear.

The PR tackles dorms, attempting to reduce the weird state it is currently in as an empty space with no real use case.
This is done by:
Adding a new hallway for foot traffic that previously used the dorm, moved primary dorm functions into ancillary rooms.
Gave the Bar a more dorm-centric location.
The kitchen has its own outside area that is great for building projects, as it is not right in the primary hallway.
Changs is now an open "food court" style area.
Cryodorms moved out of the way, as it should not be used for anything other than cryo.
New "common room" that is intended as an out of the way area to relax and chill, hopefully moving people away from using the bridge hallway for that (in combination with the bridge rework).
Botany fridge for use to transfer things to the kitchen remains, despite both being disconnected now. Bartender, chef and botanists have access.
Chef has access to botany pasture for animals and grow plots.
Kitchen now has a window to bartender, not the main bar. Orders can be passed through them if patrons wish to eat in the bar. (Or they can shout at the chef through the door, I guess.)
Secmaints given some more love, instead of just being 1 unconnected corridor, there is a purpose for visiting it, and it connects to Fore Starboard maints.

## Why It's Good For The Game

Dorms has long been a failure of an area, it never sees any use (like has anyone ever used the stage or pool in dorms for anything?)
This makes the dorms an attractive area for various RP activities, with a cozy common room and spacious bar, alongside a kitchen that has expansion potential for projects.
Cyrodorms being in such a central location was also a bit silly, for a room that is used solely for OOC purposes during logoffs and such, it should not have been in a prominent position.
Changs, while a nice room for projects, was awkwardly sized and too open for use as a cozy room.

### Old
dormsold
### New (those aren't plasma windows, they are electrochromic, some dingus coded them in with the wrong icon for the mapping spawner)
dormsnew

## Changelog
:cl:
tweak: Remapped cyberiad dorms
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
My main complaint with it is the fact it now lacks an area big enough to make a chessboard. Though not entirely common for people to do, they do make them sometimes outside of me myself making it. It's a pretty fun thing that people tend to like when it's made, and that I intended to make more often outside of just making it when Squishy plays. 

The area in front of the holodeck is nearly big enough for it though isn't quite big enough vertically, just shy of the size needed by 1 tile. I guess it could be constructed in the fight ring area of the maints, though it would make it far less accessible to crew to use and enjoy.

However, it's overall an improvement though, and I like that. I just wish there was a way to be able to fit the chessboard there.

**Comment by Coolrune206** [comment]
Why does Holodeck Control have a window into maintenance? Seems a bit odd.

**Comment by S34NW** [comment]
> 
> 
> Why does Holodeck Control have a window into maintenance? Seems a bit odd.

Having just walls everywhere gets bland fast, it used to be space but I was asked to fill it in as maints, decided to keep the window and a bit of a weird unique feature of that area.

> 
> Also, why is the Sec Escape Pod now rotated?

To make it fit where I wanted it.

**Comment by PeppermintEclipse** [comment]
Looks great! I especially like the large room at the bottom left (looks like a perfect place to use as a game room) and the extra space in Service departments. Time will tell if Dorms can be made important or if it's a lost cause, but I would love to see this implemented either way.

The one thing I'm not 100% sold on is having the delivery chutes for Bar and Kitchen open to the central hallway like that, but hey, there's only so much that can be done sometimes.

**Comment by S34NW** [comment]
> 
> 
> Looks great! I especially like the large room at the bottom left (looks like a perfect place to use as a game room) and the extra space in Service departments. Time will tell if Dorms can be made important or if it's a lost cause, but I would love to see this implemented either way.
> 
> The one thing I'm not 100% sold on is having the delivery chutes for Bar and Kitchen open to the central hallway like that, but hey, there's only so much that can be done sometimes.

Yeah, it was giving me some trouble figuring out too. At least the flaps are opaque so nobody can see in the rooms through them.

**Comment by LightFire53** [comment]
image

I would add windows to these areas to make them feel less closed off/claustrophobic

**Comment by Spacemanspark** [comment]
Honestly my only complaint here is the boxing ring being in maintenance; we already have problems with people making 'rage cages', and I feel like that may make the issue worse. Also, the holodeck is pretty much right next to it--may as well just use that.

**Comment by PacifistDalek** [comment]
> 
> 
> Honestly my only complaint here is the boxing ring being in maintenance; we already have problems with people making 'rage cages', and I feel like that may make the issue worse. Also, the holodeck is pretty much right next to it--may as well just use that.
> 
> Maybe put the pool there instead? Good place for silly RP.

Coffee and Jeremy need a home!

> 
> 
> I would add windows to these areas to make them feel less closed off/claustrophobic

Up top for sure, but personally there's something about the empty space of that nook above the kitchen that invites decoration or conversion into a seating area or the walls being torn down to expand the bar into that space that I'd love to see people play around with

**Comment by AffectedArc07** [comment]
image
Cramming everyone down this corridor to get food is an awful idea. It also disconnects botany and the chef meaning they have to walk more just to check if something is in the fridge, which will slow things down.

---

image
This also isn't going to solve bridge hoboing. Thats a player issue not a mapping issue.

**Comment by S34NW** [comment]
> 
> Cramming everyone down this corridor to get food is an awful idea. It also disconnects botany and the chef meaning they have to walk more just to check if something is in the fridge, which will slow things down.
> 

Indeed, that hallway was one of the things I plan to tweak after getting feedback.

>
> This also isn't going to solve bridge hoboing. Thats a player issue not a mapping issue.

A large contributing factor to bridge hoboing is that there is no proper dedicated space for people to chill. Current dorms has that small little area next to cryogenics, but its got low capacity and is in the middle of a corridor. I really do think that this, combined with the bridge remap, will help. (Not a complete fix, but certainly reducing contributing factors is a good thing.)

**Comment by roarbark** [comment]
i have to say the new version of maints looks great to have fights and chases in. 

it doesn't rely too much on straight hallways, makes them spacious enough to dodge and gives enough turns to allow for cover and breaking line of sight, which is even better, since it's somewhat nonlinear- which means you could actually juke someone without them knowing which way you went, without using audio or visual cues. 

I wouldn't mind all of maints to look like this

**Comment by Spacemanspark** [comment]
>This also isn't going to solve bridge hoboing. Thats a player issue not a mapping issue

Providing incentives to go sit in more interesting places that aren't the front of the bridge may not 100% resolve the issue, but I think it's a good first step in the right direction.

**Comment by S34NW** [comment]
Updated to incorporate feedback, new image in the original post.

**Comment by PacifistDalek** [comment]
> Cramming everyone down this corridor to get food is an awful idea. It also disconnects botany and the chef meaning they have to walk more just to check if something is in the fridge, which will slow things down.

As a chef main I think the hallway is worth it, and I think if the smartfridge is in the chef's garden it's really not that far to walk (only a few extra tiles compared to walking across the kitchen). With bigger maps for higher pop, keeping the chef and botany sharing a wall is an unnecessary limiter in my book, and opens up more options for multi chef setups, bartenders accessing the smart fridge for brewing, more use of the chef's garden, etc.

**Comment by Mitchs98** [comment]
Actually didn't notice all the excess walking required for botany and chef now, definitely not a fan of that either. I like the design overall, but the fact of that and the fact there now isn't an area suitable to build a chess board for people to use makes me dislike this quite a bit. The latter is definitely less of an overall concern and more of a personal one, but a big enough one for me to dislike the remap.

**Comment by S34NW** [comment]
> 
> 
> Actually didn't notice all the excess walking required for botany and chef now, definitely not a fan of that either.

The chef having to go out and interact with people is not too bad really, it's 15 or so tiles to the kitchen supplies fridge that replaced a botany window. Or they could even arrange with botany to leave them a food crate in the pasture.
I understand it's additional walking, but the alternative is making anyone who wants to use the dorm cut-through in maints will have to take like 45+ additional steps, I'd rather one person have to take some additional steps to do their job, as opposed to everyone else have to take a long detour if they want to move to a certain location.

>
>I like the design overall, but the fact of that and the fact there now isn't an area suitable to build a chess board for people to use makes me dislike this quite a bit. The latter is definitely less of an overall concern and more of a personal one, but a big enough one for me to dislike the remap.

What're the dimensions of a reasonable in-game chessboard? You might be able to fit one in starboard primary if you take out the seating area in front of the kitchen/bar. There are other places on station with enough room: Departures without the garden section, for example.

**Comment by LightFire53** [comment]
> Actually didn't notice all the excess walking required for botany and chef now, definitely not a fan of that either. I like the design overall, but the fact of that and the fact there now isn't an area suitable to build a chess board for people to use makes me dislike this quite a bit. The latter is definitely less of an overall concern and more of a personal one, but a big enough one for me to dislike the remap.

I'm not sure that there is a huge demand to make life sized chess boards, if I'm to be honest.

**Comment by Spacemanspark** [comment]
...People have been making life size chess boards?

**Comment by Mitchs98** [comment]
> > Actually didn't notice all the excess walking required for botany and chef now, definitely not a fan of that either. I like the design overall, but the fact of that and the fact there now isn't an area suitable to build a chess board for people to use makes me dislike this quite a bit. The latter is definitely less of an overall concern and more of a personal one, but a big enough one for me to dislike the remap.
> 
> I'm not sure that there is a huge demand to make life sized chess boards, if I'm to be honest.

I mean that's only a minor part of it. What I mostly dislike is the awkward placement of botany in relativity to the kitchen. If I'm looking at the map right it seems you have to either go all the way around out of the kitchen to the front desk area of botany to get food, get it delivered by plant bag, or botany has to go through the bartenders' backroom to the fridge? Incredibly inconvenient, and inconsistent with the other stations, and something I'm not sure why is like that in general personally.

> What're the dimensions of a reasonable in-game chessboard? You might be able to fit one in starboard primary if you take out the seating area in front of the kitchen/bar. There are other places on station with enough room: Departures without the garden section, for example.

8 by 8. And I'm aware there are other places, it's just those are less central and less likely to be used by people. Which I guess isn't that big of a deal as they aren't that common to be made.


> ...People have been making life size chess boards?

I and a few others do occasionally, yes. Not too terribly often though.

**Comment by KerbalCitizen** [comment]
I play chef a decent amount, not a huge fan of the kitchen. The tables seem very strangely placed. Ideally, you could easily access all the tables and the machines (easy to travel between). On the current map, the microwaves and grill are right next to the big table in the center, with the oven nearby. On your redesign, you can access 5 tables at once, but it is a decent amount farther from the machines. Alternatively you could just use the 3 tables left of the microwaves, but that's one less than the current 4 wide table. It's not a huge difference, but when chefs are regularly not making enough food for the station, I don't think we should be making it harder for them.

I assume you chose that table layout due to lack of space, but I think you could save a bit. You might be able to remove the delivery area in the cold room, never really seen that get used. The fridge and freezer chest in the cold room could be moved below the chef vendor. That should allow you to shrink the cold room a lot, mainly making it shorter (vertical dimension smaller). That'd let you rearrange the machines and tables with a lot more room to work with. If possible, bring the two fridges closer to the tables and machines, but that's not super necessary.

Just as a disclaimer, never done mapping or anything like that before, just wanted to give my thoughts on it. Mildly annoyed that barber shop is now more visible, but it used to be far too strong as a place for antags, however, it was a good change honestly.

**Comment by Denthamos** [comment]
Not a fan of the fact that like mentioned above there is no easy way for botany to give ingredients to the chef since they are separated with no fridge in-between them and that the chef has lost access to the common garden between the two which was handy for the role when there was no botanists at all.  The chef could at least have simple stuff growing like rice for sushi, wheat/tomato's for pizza.

The sitting/dining area in front of the kitchen while nice idea wise just feels a bit too off with its tiny 2 1x2 tables surrounded by stools and nothing else while being open to the hallway without any sort of 'railing' style soft barrier to keep movement separated yet in sight and heard like the mall setting it feels aimed to be.

**Comment by S34NW** [comment]
> 
> 
> Not a fan of the fact that like mentioned above there is no easy way for botany to give ingredients to the chef since they are separated with no fridge in-between them and that the chef has lost access to the common garden between the two which was handy for the role when there was no botanists at all. The chef could at least have simple stuff growing like rice for sushi, wheat/tomato's for pizza.

Chef does have access to the botany garden/pasture, just not into botany itself. The fridge at the front of botany is restricted to service access only, so Botany, Barkeep and Chef are the only ones with access unless its hacked.

> 
> The sitting/dining area in front of the kitchen while nice idea wise just feels a bit too off with its tiny 2 1x2 tables surrounded by stools and nothing else while being open to the hallway without any sort of 'railing' style soft barrier to keep movement separated yet in sight and heard like the mall setting it feels aimed to be.

Yeah, It's generally intended to be functional if left alone but also a nice space for chefs to re-work if they want to. I'm a bit unsure how we could properly "fence it off" so to speak without making it look cramped or forced, perhaps I can ask in mapping chat about it and see if anyone else has ideas.

**Comment by AffectedArc07** [comment]
3 maintainer objections and no one in favour from either party. Closing.

**Pull request closed without merging**
