### PR TITLE
Removes Obj & Turf reactions from Plasma Dust

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
rscdel: Plasma dust no longer creates plasma gas on objects or turfs during reactions.
/🆑

Stops plasmadust grenade grief.

### CODE REVIEW

**Comment by Anticept** [comment]
https://drive.google.com/drive/u/0/folders/0B6xx36SnvIA8VVEtNE9kbDlPa0k

That's the damage done when it was tested to prove a point. It's not something new, but people were using the wrong chem mix to really maximize the damage.

**Comment by Crazylemon64** [comment]
No fun allowed

**Comment by Crazylemon64** [comment]
(A shame, because a chemical with a utility like this seems so interesting, although this is a bit over the line)

**Comment by Kyep** [comment]
For the record, I do like the idea of having a chem that creates gas/fires.
However, the implementation prior to this PR was massively OP, because you could use foam to duplicate the reagents, creating massive fires.
Fixing the duplication was too big a change for a hotfix - cleaning grenades, etc might break.
So, the hotfix was to prevent dust spawning gas. Then we can look at chem/gas interactions in another PR later, if we want.

**Comment by Anticept** [comment]
On top of that, it's possible to make cascading chems, where they would self duplicate with everyone who breathes them in, resulting in even more duplication foam duplication foam....

**Comment by SamHPurp** [comment]
That is astonishing. Thanks all involving fixing this... holy shit.

**Pull request merged**
