### PR TITLE
Expand Xenobiology, return surgery table

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit does the following:
 - Expands Xenobiology
  - New pen, more space.
 - Removes the Xenoflora machine in exchange for another disposal feeder
 - Readds a surgery table, scalpel, and saw to xenobiology, as it is far
   far faster than the processor for people that know how to use it.

## BEFORE
before
## AFTER
after

### CODE REVIEW

**Comment by SamCroswell** [comment]
If anyone complains about Xenobio getting breached due to the test lab after this edit I will personally blow them up myself.

**Comment by tigercat2000** [comment]
@SamCroswell Eh, I get that point- but it's probably far enough away to not be devastated unless the scientists blow up most of that section.

**Comment by TheDZD** [comment]
Even with the layout we currently have, large test lab explosions regularly breach xenobio.

**Comment by Spacemanspark** [comment]
Doesn't really matter either way, then.
As for the PR itself, sure why not.

**Comment by M3hillus** [comment]
Throw a few walls in the empty space as a buffer maybe?

**Comment by Markolie** [comment]
:+1:

**Comment by KasparoVy** [comment]
:'(, RIP xenoflora machine. I use its board all the time for that last material level, but 'tis no more if merge

**Comment by tigercat2000** [comment]
@KasparoVy When xenoarch is reimplemented, it won't be a thing anymore anyways.

**Pull request merged**
