### PR TITLE
Gives RCL an autolathe design

### LINKED ISSUE #7028: Rapid cable layer cannot be produced
**Problem Description**:
The RCL isn't in any of the design code, so it cannot be produced at this time.

**What did you expect to happen**: 
That clearly wasn't the intention when it was added. It was meant to be a useable item.

**What happened instead**:
It's missing from the design files. https://github.com/ParadiseSS13/Paradise/tree/master/code/modules/research/designs

The RCL itself: https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/RCL.dm

**Why is this bad/What are the consequences:**
Makes it unusable without adminbussing

### PR DESCRIPTION
**Pull request by davipatury**
:cl: davipatury
rscadd: Rapid Cable Layer now have an autolathe design.
/:cl:

Fixes #7028

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Kinda wonder if this should be hacked autolathe item, like the RCD and upcoming RPD.

**Comment by Lady-Luck** [comment]
Engineering is already pretty dependent on R&D for upgrades. Having it be a hacked autolathe item would probably be better and consistent with where the RCD is currently obtained.

**Comment by Taaketa** [comment]
I agree that it should be a hacked autolate thing. Othsrwise, we may as well get to the point where engineering will need a protolathe / science console at round start. Since most engineering teams are already doing that.

**Comment by Anticept** [comment]
I'm asking, why "hacked"? What is that supposed to be for?

**Comment by fludd12** [comment]
It already hides the RCD and RPD, the whole Rapid-[tool] thing mostly seems to be a hacked thing.

**Comment by Anticept** [comment]
The RCD and RPD are for good reason: they are potentially very destructive tools.

The cable layer is not.

**Comment by Fox-McCloud** [comment]
I'd lower the tech levels on this (The base item), and again, move it to the autolathe as a hacked item.

RPD is hardly "destructive"; it's just a rapid construction convenience item; sure you can use it to build destructive things; but you could also make that same argument for the RCL, as well.

**Comment by Anticept** [comment]
RPD can remove pipes rapidly, as I understand? Or is it only a pipe layer? If it only lays pipes, then it too shouldn't be "hacked" out.

**Comment by Fox-McCloud** [comment]
It can remove pipes only after you've wrenched them up; it can't just deconstruct pipes, rapidly, on its own.

it's more cleanup; the unwrenching is the "destructive" part.

**Comment by Anticept** [comment]
Ehhh that doesn't sound like something that needs to be under the "hacked" category then. That's how I see "hacked" items, things that have a higher potential danger if misused. RCDs can punch open floors and knock down pretty much any door, for example.

**Pull request merged**
