### PR TITLE
Makes the singularity more realistic

### PR DESCRIPTION
**Pull request by Citinited**
**What does this PR do**
Makes our singularity behave much more realistically, by ensuring the latest scientific theories are upheld. Approved by physicists everywhere!

Also gives engineering the ability to act as a makeshift kitchen

:cl:
tweak: Humans now get spaghettified when the singularity eats them
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
I don't joke when it comes to the singularity Kyep, it's a feature™️ 🔫 😄

**Comment by Spacemanspark** [comment]
I think Citinited broke

**Comment by taukausanake** [comment]
Is `death(gibbed)` called only when you die by singulo? It sounds like if you die via gibbed and I for one know you can gib people by other means (mainly badmin but still). I would think you'd need to put this is a `singularity_act` proc instead but I don't know everything

**Comment by Citinited** [comment]
@taukausanake Ahh right you are, should be under `singularity_act`. This will make anyone who gibbed turn into spaghetti. I'll change that as soon as I get home tonight. Good spot!

Stupid spaghetticode 😄

**Comment by Citinited** [comment]
@taukausanake fixed 🍝

**Comment by Fox-McCloud** [comment]
Closing, as this is likely a joke. If not, then uh, DM me about this.

Still absolutely hilarious though.

**Pull request closed without merging**
