### PR TITLE
Miming/Mute players now give a visible indicator of communion

### LINKED ISSUE #9861: Mime can Cult Commune without breaking Vow of Silence
**Problem Description**:
Mimes can can commune with the cult without breaking their vow of silence, making it a silent, safe way to talk with the cult.

**What did you expect to happen**: 
As a Mime, you're unable to talk or make most noise with your Vow of Silence intact. Thus, I expected to not be able to commune.

**What happened instead**:
I was able to commune without any whispering from my character, but the message still appeared in cult chat.

**Why is this bad/What are the consequences:**
While I'm not sure if it's important, I do believe that the cult whispers are one of the good ways to identify a cultist, and this could be a workaround. Additionally, this could work for mute characters, though I'm not sure.

**Steps to reproduce the problem**:
1. Be Mime Cultist
2. Commune
3. Watch your message appear silently!

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing I can think of.

### PR DESCRIPTION
**Pull request by Shadow-Quill**
**What does this PR do:**
Makes players who are either miming or have the mute block act out whispering. Under the watchful eye of Nar'sie, what they "say" are transmitted to other cultists.

AKA: Miming/Mute now give an emote instead of magic telepathy.
AKA: No more tricky book club meetings.

Edit: My advisor decided to tell me that I needed to say something. After I made the PR. Blame them for the ugly edit thing. Here goes.

*Ahem.*

THIS FIXES #9861

Thank you.

**Images of sprite/map changes (IF APPLICABLE):**
N/A

**Changelog:**
:cl:
tweak: Makes people who are miming/mute give a visible indicator of their communion.
/:cl:

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
My advisor decided to tell me I needed to say something.

Ahem.

THIS FIXES #9861.

Thank you.

**Comment by taukausanake** [comment]
:+1: for the screaming fix

**Comment by Aurorablade** [comment]
I still worry about this being made to bone out the cult in someway.

**Comment by Shadow-Quill** [comment]
The only issue is without _some_ indicator of cultiness, mute/miming can commune infront of _anyone_

**Pull request merged**
