### PR TITLE
Plant analyzer sprite update

### PR DESCRIPTION
**Pull request by DogsParadise**
## What Does This PR Do
Sprite update for plant analyzer

## Why It's Good For The Game
Old sprite is outdated, the old sprite isn't shaded correctly.
Old sprite looks a lot like the health analyzer in-game and nothing makes it stand out.
New sprite is animated.

## Images of changes

Old plant analyzer image:
Old Plantanalyzer

New plant analyzer image:
plantanalyzer3vibrant1

New plant analyzer animation:
plantanalyzer3vibrant

## Changelog
:cl:
tweak: updated plant analyzer sprite
/:cl:

### CODE REVIEW

**Comment by MRgaty** [comment]
Looks nice

**Comment by taukausanake** [comment]
I don't like it. The old sprite has charm but this looks like it would fit in /TG/ aesthetic. The Plant Analyzer also shares design with the health analyzer so if you're going to change one you might want to change the other as it too would be "outdated"

**Comment by DogsParadise** [comment]
Already updated health analyzer there will possibly soon be apr for it, because it indeed is outdated aswell. Thanks for your constructive criticism. But personally I am of the opinionthat bad sprites are not a "charm".

**Comment by Quantum-M** [comment]
I think the sprite looks rather neat. One suggestion I have though, is that it looks a bit thin/fragile looking, maybe make it look to have a bit more depth on the top and the glass portion?

**Comment by Pixelzilla** [comment]
Honestly not too keen on this. Yes, the plant analyzer is a recolor of the medical analyzer but that's not really bad or lazy that's pretty helpful for consistency.

It having the same shape makes it a lost easier to know at a glance what that thing is and what it does. Its shaped like health analyzer, its green, its for scanning plants. Its really straightforward.

I'm not against having some nicer updated things but i do think they should stick to the original design. Similar to how all ore satchels/plant bags/bio bags/ chem bags are all the same base sprite but recolored for that department. You can easily tell what they're for.

**Comment by variableundefined** [comment]
Closing due to lack of updates and two maintainers objection.

**Pull request closed without merging**
