### PR TITLE
Add BYOND member perks

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds perks for BYOND members (ported from /tg/, see below).
2) Adds some additional preferences to the setup screen.

* BYOND members now get a small BYOND logo next to their name in OOC.
* BYOND members now get a custom OOC color (dark green: #035417: http://www.colorpicker.com/035417).
* Adds an option to increase the number of save slots available to BYOND members. Currently the same as for normal members (10).
* BYOND member publicity can be toggled through a preference.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Please god no. Maybe, MAYBE the damn logo.

**Comment by Markolie** [comment]
The OOC colors are fully sanitized, which means that you can only use a limited set of colors that do not hurt the eyes. If need be I'll make it so these restrictions don't apply to admins so they can still pick whatever color they want.

The reason I'm suggesting these changes is because we are fully reliant on BYOND as a platform to function. They provide us with everything we need to run the server at no cost whatsoever. The only way BYOND survives is through donations and advertisements, and many players decide to be assholes and find ways to hide these advertisements through illicit means. I think the least we can do is give players some OOC benefits in-game in order to support the BYOND platform.

I realise many admins are very attached to their special, own, unique OOC color, but seriously, get over that.

**Comment by Markolie** [comment]
Yea, the character slots thing I don't like too much either (hence why that hasn't changed, both members and players get 10). The OOC colors players can choose are very limited due to the sanitization: it works well on /tg/, so I'm sure it'll work on Paradise as well.

**Comment by Alex6511** [comment]
Couldd also giveadmins a logo in chat so people not familiar with them can still identify them.

**Comment by Markolie** [comment]
Current plan is to instead give members a predefined color.

**Comment by Alex6511** [comment]
Okay

**Comment by FalseIncarnate** [comment]
Giving members a logo+predefined color will be better for consistency.

Color selection honestly isn't the worst thing, but I feel it would be best to leave that for actual staff. Giving staff logos might not be a bad idea for the future, but that's entirely separate from this.

:+1: for encouraging people to support BYOND without affecting anything in-game

**Comment by Markolie** [comment]
Member color: http://www.colorpicker.com/035417

I'm open to feedback though for better colors.

**Comment by Alex6511** [comment]
:+1:

**Comment by Iamgoofball** [comment]
Change it back to color selection, people will whine abiut it being forced to green.

**Comment by FalseIncarnate** [comment]
:+1:, good color choice that is clearly distinct from staff colors.

And @Iamgoofball, they are able to toggle the color off (though this also hides their logo) if they truly don't like it (or don't want people knowing they are supporting BYOND). The number of players who would complain about being forced to green for their OOC are going to be a small fraction of the community, and likely not an issue.

If anything, we can later add in a VERY limited selection of pre-defined choices (pick normal ooc blue, member green, or sneaky purple?) should there turn out to be more BYOND members than anticipated who also wish for it. Giving them access to the whole color grid thing to choose from just overly complicates things.

**Comment by Iamgoofball** [comment]
I don't get why it has to be a preset color.

What's wrong with BYOND members getting to pick any color they want?

**Comment by FalseIncarnate** [comment]
It doesn't really NEED to be, however OOC color selection has always been a staff-only feature.

Does it really change anything? No, not really. Aside from fringe cases where someone tries setting their OOC color to default admin red and attempts to lead others to (falsely) believe that they are staff when they are not, it really doesn't generate any issues to let them select their color.

I believe more than anything, it's maintaining the consistency that a normal player (which, effectively, a BYOND member still is) has a pre-defined OOC color to help differentiate them from server staff which they are unable to alter.

**Comment by Regen1** [comment]
Agree with False
Keep it to one predefined color, no changing

**Comment by Fox-McCloud** [comment]
I like the idea of a pre-defined color+an icon--color selection though, I'm inclined to believe should probably not be selectable to anyone but admins (I sometimes wonder if even mentors should have a pre-defined color? But meh, anyway).

:+1:

**Comment by Iamgoofball** [comment]
I feel your reasoning is really really really dumb but whatever

**Comment by Spacemanspark** [comment]
Oh hey this. I donated to Byond once when I was still a /tg/ regular.
:+1:
I thought the custom color thing changed the name color only, and not the actual text. I don't really see an issue with custom name colors.

**Comment by Iamgoofball** [comment]
Yeah, it just changed the name color

**Pull request merged**
