### PR TITLE
Conflicts with Everyone, Makes People Hate me, and Brings About the Apocalypse

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Therefore, I'm going to have to remove all your `/weapon`'s so I can defend myself.

More seriously, this removes the `/weapon` object type.

Quite frankly, it's unneeded, and as much of a good meme "hahaha, everything is a weapon" is, it's just typepath bloat that serves no functional purpose, what-so-ever. Having it gone means less to type in the future, and makes porting/implementing things from TG a lot easier as well. 

This will conflict with just about everything under the sun; should probably be merged sooner rather than later. The sooner the pain is done, the sooner this can be put behind us.

### CODE REVIEW

**Comment by Regen1** [comment]
>Files changed 1,100

😱

**Comment by Birdtalon** [comment]
Good change.

**Comment by Citinited** [comment]
This was always confusing to begin with. 👍

**Comment by Spartan6** [comment]
all prs ded

**Comment by SkeletalElite** [comment]
Beepsky has a setting that is set to arrest for unauthorized weapons, will this make that setting not do anything or is that done separately?

**Comment by Fox-McCloud** [comment]
Zero functionality is changed.

Like I said, the fact this path exists is completely and utterly pointless.

**Comment by taukausanake** [comment]
Would it be too much to have a freeze for something like this to limit the amount of conflicts? If anything you could make one to make other PRs merging not conflict with this rather than the other way around

**Comment by matt81093** [comment]
I mean, merging this asap would probably be best. Though this will be annoying for some of the bigger PR's..

**Comment by Anasari** [comment]
You did it. The end is nigh.

**Comment by taukausanake** [comment]
> /item/scalpel .. so beautiful

I think `/item/storage` is more beautiful than anything else in here

**Pull request merged**
