### PR TITLE
Add GPS devices to pod pilot and mechanic offices, take 2

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
GPS devices are pretty important to jobs that involve exploring space, so this PR gives pod pilot and mechanic a starting GPS. Playtested and it seems to work with no issues.

This is a redo of #6804

Pod Pilot Office

Mechanic Office

:cl: Tayyyyyyy
rscadd: Added GPS devices to pod pilot and mechanic's offices
/:cl:

### CODE REVIEW

**Comment by AndriiYukhymchak** [comment]
please attach screenshots for map changes... pleeeeease

**Comment by Tayyyyyyy** [comment]
@AndriiYukhymchak Sorry about that. Added!

**Comment by Fox-McCloud** [comment]
👍

**Comment by Anasari** [comment]
Make sense and looks good

**Pull request merged**
