### PR TITLE
Gives Nukeops Modsuits RSG immunity

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
Gives the basic and elite nukeops modsuits RSG immunity.

**This does not affect the versions available to traitors.**

## Why It's Good For The Game
No filling Gorlex's finest with secret sauces.

## Testing
It compiled.
A naked skrell was shot and injected.
A naked skrell wearing nukie armour was shot and not injected.

## Changelog
:cl:
tweak: Nukeops modsuits are RSG immune.
/:cl:

### CODE REVIEW

**Review by DGamerL — CHANGES_REQUESTED** [review]
Please use the current trait, not the one that needs another PR to be merged

**Comment by Fordoxia** [comment]
> Please use the current trait, not the one that needs another PR to be merged

Done.

**Comment by 1080pCat** [comment]
Not a fan.
If a nukie decides to bring a RSG with funny instant death chems, and they loose it? thats their fault, crew should be able to use the gear the nukies loose.

**Comment by PopeDaveThe3th** [comment]
> Not a fan. If a nukie decides to bring a RSG with funny instant death chems, and they loose it? thats their fault, crew should be able to use the gear the nukies loose.
> 
> Kinda extreme of an example, but it'd be like making nukies immune to antimatter shots

Would have to agree here, though I do think there's a good case for the Elite suit being RSG immune.

Basic bloodred should not be, however.

**Comment by ErdGinalD** [comment]
there is no way to obtain RGS not being tot or nukie, so i dont think to give RSG immune is need at all. If you fail to hold RSG as nukie, be prepared to consequences as losing sniper riffle. For defending from one-shot you have exosuits and shield module

**Review by DGamerL — APPROVED** [review]
Code LGTM - might consider only making the elite one immune

**Comment by chuga-git** [comment]
I'm not sure I understand the reasoning behind this. You're only ever going to see a nukie getting RSG'd if the crew gets their hands on one from another nukie. I don't think they should be made immune from the consequences of losing an RSG since they are definitely not immune to any other weapon.

**Pull request closed without merging**
