### PR TITLE
Adds new lobby songs

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Taken from Citadel:
Clickable images for vids:

- Carmen Miranda's Ghost
   [carmen](https://www.youtube.com/watch?v=D5p8YhhaVlA)

- Space Oddity
   [century21](https://www.youtube.com/watch?v=KaOC9danxNo)

- Red Alert 2 OST - In Deep
   [indeep](https://www.youtube.com/watch?v=8vs44mnswak)

- Moonbase Oddity - Vid audio quality is shit, source file's isn't. Probably the only one that arguably doesn't violate Copyright
   [moonbaseoddity](https://www.youtube.com/watch?v=cQByFjYczfE)

- Goodbye Moonmen
   [dankmeme](https://www.youtube.com/watch?v=liEHDMrnUcc)

- Space Asshole
   [asshole](https://www.youtube.com/watch?v=GISnTECX8Eg)

Why? Because fucking christ almighty we have like four fucking songs and they've gotten so irritatingly repetitive that I've muted lobby music, at the very least expanding the library could help alleviate this.

Upsides:
- More variety in music

Downsides:
- We gon' get sued, probably not, but possibly (?)
- Repo is like 10 mb larger now

### CODE REVIEW

**Comment by taukausanake** [comment]
The only one that has my vote right away is Space Oddity because a friend put it in his private server before. Almost thought of bringing it here but wasn't sure what the policy was on music

**Comment by FlattestGuitar** [comment]
We can't use stuff that we don't have permission to use. If something is not on a license that permits us to use it, it has no place in our codebase.

They're cool, but not that cool. 

_I'm sorry._

**Comment by Regen1** [comment]
Space oddity was on paradise a long time ago, I'd love to see it back, and I have no idea why it was removed.

**Comment by Fox-McCloud** [comment]
>increasing the .RSC by 14 MB

>>including songs that were yoinked, previously

:|

**Comment by scrubmcnoob** [comment]
@FlattestGuitar I don't think copyright laws work like that. We aren't charging money on the server and they're openly available. It be different if we were selling a game that had this music in it without asking etc.

Also maybe remove the moonbase alpha one? Seems too much of a meme with the voices.
Oh and this is a really good song for space themes.
https://www.youtube.com/watch?v=_lAfMT5FIZE

**Comment by Fox-McCloud** [comment]
@scrubmcnoob 

Before youtube ads were a thing, you could still get bonked with a copyright violation claim for uploading music on youtube.

The argument goes that by you making it publicly available, you're taking away *potential profits* from the company.

**Comment by scrubmcnoob** [comment]
@Fox-McCloud realistically will someone file a case to have us remove the music? And if someone does, then we'll just remove it. Also don't we already have copy right music?

**Comment by HereticChurch** [comment]
I approve of anything using literally any song from the RA2 OST. 👍 💯

**Comment by outbools** [comment]
yeeey 2 hours of meme song downloading


small request:
STATION MAN 🌊 😍 Take me by the hand ✋ lead me to the shuttle that you understand 🙌 🌊 STATION MAN 🌊 😍 The voyage 🚲 to the corner of the 🌠  CC is a real trip 👌 🌊 STATION MAN 🌊 😍 The crust of a spess man 👳 imbibed by the lube 👍 Soaking up the 💦 thirst of the spess 💯

**Comment by Aracino** [comment]
God yes. The current songs make my ears bleed.

**Comment by LittleBigKid2000** [comment]
But the existing songs give me a sense of nostalgia from when I first started playing SS13

**Comment by KasparoVy** [comment]
I like the music but, as stated, we've still got to avoid getting on the wrong side of someone's license.

Rsc size is irrelevant to me but then again so is my own conjecture as, given some of the comments, I can see no way this will be allowed to pass.

**Comment by Spartan6** [comment]
Red dwarf theme anyone?

**Comment by sothangel** [comment]
We'll run into issues with distributing IP that doesn't belong to us by including this, since it'll be available for download in the source code, no?

It'd be cool, but it'd also get us into deep shit *if* something ever came about of it.

**Comment by ktoma36** [comment]
Found another song that could be used :3 https://www.youtube.com/watch?v=EeHvEZuphIE&list=PLvshxktz4BRPpUjCcDGtqXqsWfY9uUoSn&index=143

**Comment by FreeStylaLT** [comment]
The sue is too strong, you'll have to settle with other songs later

**Pull request closed without merging**
