### PR TITLE
Converts "Listening Post" away mission into a space ruin

### PR DESCRIPTION
**Pull request by Kyep**
This PR deletes the "Listening Post" away mission.

Why, you ask?

- Take a look at the starting area for this away mission: http://i.imgur.com/TvqBhaw.png
- Now take a look at the actual content in this away mission: http://i.imgur.com/jneJgh9.png
- There's almost no content in this mission. You start in a dark room, surrounded by rock, with absolutely nothing around you. To say this mission lacks content/fun value is an understatement.

But... couldn't we improve it?

- I tried. I really did. I developed a whole new base for the gateway to connect to, complete with a second small asteroid containing a cult temple. Puzzles, too.
- Unfortunately, the entire theme of this map is 'remote listening post', so adding lots of stuff to it somewhat goes against its purpose.
- In addition, the map file appears to be corrupted somehow - whenever I try to edit it in DM, the result is that the map merge tool freezes. I don't have this problem with any other map - even doing similar edits to them. They work. This doesn't. I'll be able to re-use some of my work in other away missions, making them better. Trying to patch this seems to be a lost cause, though.

Removing this mission from rotation means you're more likely to get one of the other missions. The other, better missions. Which won't start you off alone, in a tiny, dark room, surrounded by tons of rock in every direction.

🆑 Kyep
rscdel: Deleted 'listening post' away mission.
/🆑

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
If you had put forth work to "expand" the mission, might as well propose that as a replacement, removing the remote listening post theme and instead making it into a new themed mission (albeit perhaps in a new PR if your map issues are the main reason for removing rather than improving here).

**Comment by Kyep** [comment]
The current listeningoutpost.dmm file crashes map merge tool whenever I try to update it in any way. Also, given the theme issues, it is easier to just put up a separate PR that introduces a new, much better away mission. That's my plan.

**Comment by Kyep** [comment]
Closing/reopening to force Travis rebuild.

**Comment by Kyep** [comment]
@Crazylemon64 This compiles fine for me, yet Travis keeps giving errors. I've closed/reopened it to force a Travis build, yet Travis still complains. Any idea what's going on?

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/_maps/test_away_missions.dm#L5

Travis uses this to test away missions, and it can't find it, so it's having a hissy fit.

**Comment by Kyep** [comment]
@Fox-McCloud Thanks. That did it.

**Comment by Aracino** [comment]
A cult-syndicate misiion coud be interesting

**Comment by Fox-McCloud** [comment]
>A cult-syndicate misiion coud be interesting

And really wouldn't make much sense; Syndicate just want to take down Nanotrasen; not destroy the entire universe; they're self-preserving, not suicidal.

**Comment by Spacemanspark** [comment]
Cult vs Syndicate mission?

**Comment by davidchan13** [comment]
NT outpost that's been culted and then sieged by Syndies?

**Comment by Fox-McCloud** [comment]
This would still make a good space ruin.

**Comment by Kyep** [comment]
@Fox-McCloud Added space ruin. 

Changes from original:
- Syndie mob is set environment_smash = 0, so he won't wreck his own living space.
- Lights added, so poor operative isn't stuck in the dark.
- Gas tank and jetpack added, so he at least in theory has mobility.
- Floor safe removed (it was problematic). Instead, his note and gun are hidden behind a false wall, behind his bed.
- Asteroid is a different shape.

**Comment by Kyep** [comment]
@Fox-McCloud Added space ruin. 

Changes from original:
- Syndie mob is set environment_smash = 0, so he won't wreck his own living space.
- Lights added, so poor operative isn't stuck in the dark.
- Gas tank and jetpack added, so he at least in theory has mobility.
- Floor safe removed (it was problematic). Instead, his note and gun are hidden behind a false wall, behind his bed. This does not show up in the graphic (false walls have no graphic in DM), but it is there.
- Asteroid is a different shape.

**Comment by Fox-McCloud** [comment]
Why does the safe cause problems?

**Comment by Kyep** [comment]
When I loaded it in, it did not populate correctly. Also, to be blunt, I think having a safe hidden under a door in the floor is a little cheesy. There's no clue it is there. The only way to find it is either a T-ray scanner, or foreknowledge. At least the secret door method, you can notice the wall isn't an rwall, which might encourage you to check. If you're observant. The floor safe method... there is no visual clue it is there.

**Comment by fludd12** [comment]
Not to mention that safehacking is literally the most tedious thing besides maybe the entire Engineering job.

**Comment by ktoma36** [comment]
Should probably make it so the operative doesn't space themselves somehow, maybe a button activated airlock system like the mining station has. I can't tell you how many times I have found the poor operative dead in space just outside the outpost. Although if you want to leave it in we can all just think that he had horrible depression and what not.

**Comment by Fox-McCloud** [comment]
The problem with safes should be addressed if they're not accepting items pre-placed.

Given that it's a Stetchkin, the floor safe is more thematic, I much prefer it. The wall is also purely just "pre-knowledge"; it's just a bit easier to find---it makes it more of a "loot pinata", which I don't agree with, at all.

**Comment by Kyep** [comment]
@Fox-McCloud Simply deleted the pistol/paper/secretroom. I still hate the floor safe for multiple reasons, and this PR isn't about it. Fixing it isn't within scope for this PR, and I'm frankly not sure I can. This PR is simply about getting the listening post out of the away mission rotation.

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

Lemme know when the config change for this has been made, then I can (or you can!) merge this.

**Comment by Kyep** [comment]
@Allfd Was the config change made for this?

**Comment by Allfd** [comment]
@Kyep It was not.

**Comment by Kyep** [comment]
@Crazylemon64 ?

**Comment by Allfd** [comment]
@Kyep @Crazylemon64 @Fox-McCloud 

Config change done.

**Pull request merged**
