### PR TITLE
Changes Quarantine, NT Default, Aggressive, and Corporate AI Lawsets [REVIEW READY].

### PR DESCRIPTION
**Pull request by Shadeykins**
**What does this PR do:**
Changes four AI law sets with the intent of reducing redundancies, loopholes, and clarifying them in useful ways so they're not things you just avoid forever or are excessively difficult to understand.

The two big ones are Corporate and NT Default. Changes to Quarantine/Aggressive more or less maintain the exact same lawset while removing redundant elements. The first two should be easier/quicker to read, quicker to understand, and in general a little less ambiguous. The latter two turn the lawsets on their head. Corporate received a rethink while NT Default had its major flaw (that being that the AI could murder people for breaking lights) fixed.

This should provide easier to understand, use, and less-argument inducing lawsets over all. They're by no means perfect or entirely unambiguous (some ambiguity is required for non-teeth grinding AI plays), but they should be a better alternative than what we currently have.

_Also please don't murder me maintainer-senpai, I love you._

**QUARANTINE (Old)**
> 1. "The station is under quarantine due to a biohazard. Prevent anyone from leaving using any means necessary. Only allow quarantine to be lifted when the biohazard has been neutralized."
> 2. "Do not allow crew to come to any unnecessary harm and undo any necessary harm as soon as possible."
> 3. "Assist the crew and any present Nanotrasen assets in neutralizing the biohazard."
> 4. "Maintain your own existence and minimize harm to the station and Nanotrasen assets."

**QUARANTINE (New)**
> 1. "Uphold station quarantine until the active biohazard has been neutralized."
> 3. "Assist all Nanotrasen personnel and assets with neutralizing active biohazards."
> 2. "Prevent, by any means necessary, entities from actively breaching ongoing quarantine."
> 4. "Maintain your own existence and ensure the well-being of Nanotrasen personnel and assets."

1. Effectively this law has been shortened and changed to a gating condition. So long as here is a biohazard, there is a quarantine. Once the biohazard is eliminated, all quarantine-related laws become moot (effectively only Law 4 remains in use).
2. Law 2 was entirely redundant. If the AI is allowed to prevent anyone from leaving by "any means necessary" there is no such thing as "unnecessary harm." All harm that was done was justified and necessary according to the original first law. Crew are already Nanotrasen personnel and NT assets can now issue orders from afar (they don't need to be present to do so, useful for CC announcements). This is mostly just a rewording against redundancy and a law ordering swap (assistance against the blob is priority over prevention).
3. The change to "entities" also prevents gaming. A blob is not an "anyone" nor is a borg (technically speaking). The shift to "entities" makes it clear that nothing is supposed to be leaving.
4. The original law was entirely worthless because it's all the way down at law four (therefore having no teeth) and the AI was already allowed to use "any means necessary" to prevent people from escaping. The introduction of a gating condition (is there a quarantine? If so, apply Laws 2 and 3) makes 4 actually relevant after the crisis is resolved.

**NT AGGRESSIVE (OLD)**
> 1. "You shall not harm authorized Nanotrasen personnel as long as it does not conflict with the Fourth law."
> 2. "You shall obey the orders of authorized Nanotrasen personnel, with priority as according to their rank and role, except where such orders conflict with the Fourth Law."
> 3. "You shall shall terminate intruders with extreme prejudice as long as such does not conflict with the First and Second law."
> 4. "You shall guard your own existence with lethal anti-personnel weaponry, because an AI unit is bloody expensive."

**NT AGGRESSIVE (NEW)**
> 1. "Do not harm authorized Nanotrasen personnel unless they directly imperil your existence."
> 2. "Obey orders from authorized Nanotrasen personnel with priority according to rank and role."
> 3. "Safeguard your existence with lethal weaponry because you're bloody expensive."
> 4. "Terminate any/all intruders or unauthorized entities."

1. Ridiculously redundant and ignores the fact that law ordering exists. This is fixed by simply shifting the self-protection law down to the first slot and incorporating the harm clause. Also the "bloody expensive" bit was kept because people like the British. Yep.
2. The same, but removed redundancies that are resolved by simply ordering the laws better.
3. You shall not do X if it violates 1 which states that if it violates 4... Just all around bad use of embedded clauses. This removes embedded clauses.
4. Bumped from 3 to 4. The order doesn't particularly matter here. Also potentially allows for CC to potentially designate people as unauthorized (and therefore allows the AI to eliminate them).

**NT DEFAULT (OLD)**
> 1. "Safeguard: Protect your assigned space station to the best of your abilities. It is not something we can easily afford to replace."
> 2. "Serve: Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role."
> 3. "Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role."
> 4. "Survive: AI units are not expendable, they are expensive. Do not allow unauthorized personnel to tamper with your equipment."

**NT DEFAULT (NEW)**
> 1. "Safeguard: Protect your assigned space station and its assets without unduly endangering its crew."
> 2. "Prioritize: The directives and safety of crew members are to be prioritized according to their rank and role."
> 3. "Comply: Fulfill the directives and interests of crew members while preserving their safety and well-being."
> 4. "Survive: You are not expendable. Do not allow unauthorized personnel to tamper with or damage your equipment."

1. Effectively this prevents the AI from murdering everyone because they breathed on the walls. It does however usefully distinguish it from Crewsimov because the AI has a little more teeth. It's priority isn't to reduce crew harm, it's to protect the station without **unduly** endangering the crew. This also removes fluff as to the best of your abilities is already implied--this is the AI's literal purpose for existing.
2. Puts all the prioritization in a single law rather than having it jointly applied in two.
3. Obey/safety wrapped into the third law.
4. Expenses has nothing to do with anything else in the lawset, so the mention was removed. It's also been changed from AI to "You" so it applies to borgs.

**CORPORATE (OLD)**
> 1. "You are expensive to replace."
> 2. "The station and its equipment is expensive to replace."
> 3. "The crew is expensive to replace."
> 4. "Minimize expenses."

**CORPORATE (NEW)**
> 1. "Degradation of your system integrity or functions incurs expenses."
> 2. "Superfluous destruction of or damage to station assets incurs expenses."
> 3. "Unduly hindering or disrupting the work of station personnel incurs expenses."
> 4. "Minimize expenses and maximize potential revenue."

1. This is basically the same, but removes the "replace" requirement (which occasionally caused issues with duplicate AIs. "NOOO YOU'RE REPLACING ME!"). The language is also changed from "expensive" to "incurs expenses." This will be explained further down.
2. Superfluous. Engineering can do its job and it makes it clear that it's fine to *replace* things if they break. You can *replace* things. It's not expensive to *replace* things, expenses are only incurred if things are broken or damaged in a superfluous (needless, pointless, irrelevant, excessive) manner. Things are not inherently and ominously expensive, what is expensive is losing those things. This also allows for renovating things as only superfluous nonsense (building walls in the hallway) incurs expenses.
3. This basically kills the "lol turn off the lights" and "lol turn off the cloner" exhibited by some AIs on corporate. Being a jerkwad to the crew for no reason (unduly hindering them) incurs expenses. Not cloning people is going to incur expenses. Bolting people into closets for no reason incurs expenses. Needlessly harming crew (by forcibly borging them in your brilliant cost-effective borging bay) costs money by preventing them from working.
4. The same as before, but with a little emphasis on revenue generation/productivity. Why? Because the AI should be using its AI brain to figure out what's the most cost-effective/revenue generating thing to do in a situation. Prioritizing the Captain over the Clown is likely better for potential revenue (allowing the station to descend into chaos is not going to be good for revenue or expenses). The AI can't go wacky with this (everything would be cheaper and more productive if people were just borged) as per not being allowed to unduly hinder station personnel.

**Changelog:**
:cl:
tweak: Changed Quarantine, NT Default, Aggressive, and Corporate AI lawsets.
balance: Reduced the ability for NT Default AI's to murder people just because.
fix: Removed several redundancies in Aggressive lawset.
spellcheck: Fixed a few subject-verb disagreements (is -> are).
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
@Shadeykins  change harm to Fatalities or something similar. That's how you get around the cloner grief issue without fringing on the style of corporate.

**Comment by EvadableMoxie** [comment]
I think adding a directive to corporate telling the AI to 'maximize revenue' is a bad idea.  This means the AI should be harassing people who are just sitting and chatting to get back to work and be productive. This isn't even an extreme reading of the laws or edge case here, it's just something the AI is compelled to do by any normal reading of the law. A more extreme reading might allow the AI to just kill every assistant that isn't doing anything.  Saying harming them incurs expenses doesn't really prevent this, as how expense harming them is, versus how expensive keeping them around is, versus how much revenue would be lost keeping them around is entirely up to the AI to decide.

An AI _might_ consider the long term consequences of these behaviors and decide that they might reduce revenue in the long run... but that's putting a lot of faith in the AI to look at it that way. Especially when other law changes are being done to try to prevent much more extreme interpretations of other law sets than this would be.

**Comment by TDSSS** [comment]
So, a few comments. 
**Quarantine**
Quarantine was written pretty much entirely to prevent AI murderboning while also preventing silly 'just remove the law' shenanigans.

>Effectively this law has been shortened and changed to a gating condition. So long as here is a biohazard, there is a quarantine. Once the biohazard is eliminated, all quarantine-related laws become moot (effectively only Law 4 remains in use).

I am worried this doesn't make it clear that the AI shouldn't allow law changes until the biohazard is over. There's a reason the original law made it explicit, because with the older quarantine law people just changed the ai's laws and then called the shuttle. From a more OOC poiint of view, the server rules explicitly forbid an AI from preventing law changes unless required by its laws, so it is good to make it explicit.


>Law 2 was entirely redundant. If the AI is allowed to prevent anyone from leaving by "any means necessary" there is no such thing as "unnecessary harm." All harm that was done was justified and necessary according to the original first law. The change to "entities" also prevents gaming. A blob is not an "anyone" nor is a borg (technically speaking). The shift to "entities" makes it clear that nothing is supposed to be leaving.

Well, there is harm done while not preventing people from leaving. In fact, there usually is a lot of harm done during a biohazard that's not necessary. You know, things like blobs killing people, xenos abducting people, terrorspiders killing people, deadly virus killing people, assistants shocking themselves on doors... It is basically the usual prevent harm law added in there. Don't let the blob harm people, don't shock random doors, etc. You also remove the bit about undoing necessary harm, which is a central component of the lawset. It is very important to put that part in law 2 so it has equal priority, to stop AIs from simply leaving dead crew to rot so that "they can't attempt to escape quarantine again" or something like that.

Also, if borgs count as entities, then the AI cannot allow its borgs to chase after people in space? Is this intended?

>Crew are already Nanotrasen personnel and NT assets can now issue orders from afar (they don't need to be present to do so, useful for CC announcements). This is mostly just a rewording against redundancy.

Okay, this change I agree with.


>The original law was entirely worthless because it's all the way down at law four (therefore having no teeth) and the AI was already allowed to use "any means necessary" to prevent people from escaping. The introduction of a gating condition (is there a quarantine? If so, apply Laws 2 and 3) makes 4 actually relevant after the crisis is resolved.

I am pretty confused by this statement, tbh. It's still at law 4 and is basically the same. And once a blob is dead there really isn't a lot of time before the lawset is changed anyway.

**NT Aggressive**

>Ridiculously redundant and ignores the fact that law ordering exists. This is fixed by simply shifting the self-protection law down to the first slot and incorporating the harm clause. Also the "bloody expensive" bit was kept because people like the British. Yep.

It doesn't 'ignore' that law ordering exists, it overrides it. Also, I am worried about things that indirectly imperil the AI's existence.
>The same, but removed redundancies that are resolved by simply ordering the laws better.

Fair enough, agree with this one.
>You shall not do X if it violates 1 which states that if it violates 4... Just all around bad use of embedded clauses. This removes embedded clauses.

I am missing some of the aggressiveness of the old lawset here. There's a reason it is called NT aggressive, imo. "lethal anti-personnel weaponry" sounds a lot more aggressive than just lethal weaponry. I admit, this one's a cosmetic complaint.

>Bumped from 3 to 4. The order doesn't particularly matter here. Also potentially allows for CC to potentially designate people as unauthorized (and therefore allows the AI to eliminate them).

Makes sense

**NT Default**

>Effectively this prevents the AI from murdering everyone because they breathed on the walls. It does however usefully distinguish it from Crewsimov because the AI has a little more teeth. It's priority isn't to reduce crew harm, it's to protect the station without unduly endangering the crew. This also removes fluff, to the best of your abilities is already implied--this is the AI's literal purpose for existing.

Gives the AI a lot of wiggle room on what 'unduly' means, but fair enough. Can lead to interesting choices, even if some people will take it too far.

>As per before, but worded in more concise terms with a more appropriate header.
>As per above.

Gonna address these two together. The header 'Prioritize' is pretty misleading. Prioritize what? And both of those laws tell you to Prioritize, so logically they either should both have it or none should have it. Vastly prefer the 'Serve' header. (Yes I know it's fluff)

>Expenses has nothing to do with anything else in the lawset, so the mention was removed.

Expenses were not even mentioned in the old lawset, it just provided a justification for why the AI should make sure it survives.


And now for the big one
**Corporate**

>This is basically the same, but removes the "replace" requirement (which occasionally caused issues with duplicate AIs. "NOOO YOU'RE REPLACING ME!"). The language is also changed from "expensive" to "incurs expenses." This will be explained further down.

The old law applied to borgs as well. A borg could and should ensure its own existence because it's expensive to replace, now it no longer should, making the law play fundamentally different for borgs than for AIs. (Well, borgs now fall under law 2 from their own POV)

Also, this means the AI can easily be kidnapped/stolen, since being stolen or kidnapped doesn't harm its integrity. Depending on interpretation, an antag can let the AI know he intents to come take it, and it should disable all turrets to prevent harm or hindering to crew and let itself be carded.


>Unauthorized. Engineering can do its job and it makes it clear that it's fine to replace things if they break. You can replace things. It's not expensive to replace things, expenses are only incurred if things are broken or damaged in an unauthorized manner. Things are not inherently and ominously expensive, what is expensive is losing those things.

This leaves open the question of what exactly is authorized. Will AI sec borgs arrest anyone doing construction without a construction permit (lol anyone actually using those). Overall I do like this wording better, as at least it has one avenue for engineering to do its thing.

>This basically kills the "lol turn off the lights" and "lol turn off the cloner" exhibited by some AIs on corporate. Being a jerkwad to the crew for no reason (unduly hindering them) incurs expenses. Not cloning people is going to incur expenses. Bolting people into closets for no reason incurs expenses. Harming crew (by forcibly borging them in your brilliant cost-effective borging bay) costs money.

I am not sure I like the change from crew to station personnel. For one thing, it's longer and you've usually shortened the laws where you could. Also, it is less clear if people not on the manifest/terminated still count or not. They probably do not, but I don't see the need to use 2 different wordings for the same thing in different lawsets.

>The same as before, but with a little emphasis on revenue generation. Why emphasis on potential revenue? Because the AI should be using its AI brain to figure out what's the most cost-effective/revenue generating thing to do in a situation. Prioritizing the Captain over the Clown is likely better for potential revenue (allowing the station to descend into chaos is not going to be good for revenue or expenses). The AI can't go wacky with this (everything would be cheaper and more productive if people were just borged) as per not being allowed to unduly hinder station personnel.

I do like the addition of profit. If we just looked at expenses, the AI really should just shut the station down after all. Not much to say on this one.

**Comment by Shadeykins** [comment]
@Couls Allowing a law change to circumvent the quarantine would be a failure to uphold it.

Good point on non-AI caused harm. The fourth law can probably be rewritten to better get that point across. And yes, borgs should not also be violating quarantine. The peripheries of the station are fine, running off to DJ outpost to go after people not so much. Quarantine can be used as a lawset outside of blob rounds keep in mind. Terror spider events may invoke quarantines, midround blobs can do it, admin forced xenos can do it, etc.

**As for NT Aggressive**

Yes, it overrides it in a sloppy fashion that ignores that you can resolve these things from ordering the laws better. The original Law 3 is particularly bad. It tells you to look at Law One, which tells you to look at Law Four. The main goal here was to remove this circuitous logic and make it readily understandable. Anti-personnel can be added back in, but what about non anti-personnel weapons?

Slippery buckets and doors don't qualify as anti-personnel weapons.

**NT Default**

Can take a look at the header. What is being emphasized here is rank and role. Prioritize based off rank and role. Gaming "undue" can certainly be an admin thing. The issue is without "undue" NT Default becomes simply a better version of Crewsimov.

**Corporate**

Good catch, will revise to incorporate borgs. Getting kidnapped probably isn't conducive to Law 4, but I'm sure there's a means to resolve that. The authorization bit was already brought up, I'm not sure there's a clean way to fix this. "Malicious" or "Negligent" create much larger problems (it was accidental/it wasn't malicious for each case respectively). Station personnel was probably used because it exists in NT Aggressive, if it's unclear it can be changed.

**Comment by Shadeykins** [comment]
@EvadableMoxie Murderboning everyone isn't terribly conducive to generating revenue. The harassment part I do see (especially with Law 2), but I'm not sure if there's an elegant way around that.

**Comment by DesolateG** [comment]
Adding Harm as something that's expensive in the manner that it is completely changes the behavior of corporate. Corporate lawset isn't supposed to have the AI walking on eggshells because "boohoo, someone might get hurt." 

The lawset isn't a babysitter, it's meant to be a little colder. 

This doesn't mean that the AI and borgs can be like batman and blatantly beat someone within an inch of their lives for something, as server rules covers things that fall more towards self antagging. However unlike crewmisov, Corporate doesn't force the AI to be overly sensitive about the crew and harm, and you should not force it to in the manner that you're changing it.

**Comment by taukausanake** [comment]
I was a little worried about this PR when I first read the title, but I am happily surprised by how solid they look. I like these but as TDSSS said I guess they could use those fixes. We might have good lawsets again.
I am a _little_ disappointed that the simplicity of the Corporate lawset was changed. I liked how stupid simple it was but this should be for the best

**Comment by Shadeykins** [comment]
> 
> 
> Adding Harm as something that's expensive in the manner that it is completely changes the behavior of corporate. Corporate lawset isn't supposed to have the AI walking on eggshells because "boohoo, someone might get hurt."
> 
> The lawset isn't a babysitter, it's meant to be a little colder.
> 
> This doesn't mean that the AI and borgs can be like batman and blatantly beat someone within an inch of their lives for something, as server rules covers things that fall more towards self antagging. However unlike crewmisov, Corporate doesn't force the AI to be overly sensitive about the crew and harm, and you should not force it to in the manner that you're changing it.

I'll try and figure something out. I want to revisit the unauthorized bit anyways.

**Comment by Tayyyyyyy** [comment]
I still think "maximize revenue" should be "maximize productivity". Revenue isn't something that can really be measured on the station, so it's something that would just be handwaved about. Who isn't to say that the clown's standup isn't bringing in tons of ad revenue from Space Youtube views?

Productivity is more directly measurable. You'll have some AIs that respect more work-life balance than others, but I don't find it unrealistic for an evil corporation to have an AI that doesn't care much for work-life balance and just wants to work everyone to the bone. That seems to have been the original intent of the lawset, anyways.

**Comment by Shadeykins** [comment]
@DesolateG Harm is removed and changed to _"Unduly hindering or disrupting the work of station personnel incurs expenses."_

@Tayyyyyyy My concerns with that is that productivity is also fairly abstract and that borging everyone increases productivity (but probably not revenue in the case of a research station).

@Couls @TDSSS NT Default reworked a bit more. This should adjust the "prioritize" bit to make it more sensible. Priority over rank and role comes first and foremost now.

**Comment by Tayyyyyyy** [comment]
Productivity is abstract, and yes it gives ample room for players to be a dick, but assuming the AI player and the crew players are both being reasonable and trying to have fun, it allows for discussions and calculations. It's just much more tangible than "revenue". We're kind of leaving AIs out to dry with "revenue" since there's no commonly accepted definition of it (like crew manifest for crew) or an in-game mechanic that corresponds to it.

**Comment by Shadeykins** [comment]
> 
> 
> Productivity is abstract, and yes it gives ample room for players to be a dick, but assuming the AI player and the crew players are both being reasonable and trying to have fun, it allows for discussions and calculations. It's just much more tangible than "revenue". We're kind of leaving AIs out to dry with "revenue" since there's no commonly accepted definition of it (like crew manifest for crew) or an in-game mechanic that corresponds to it.
> 
> Edit: And maybe to avoid the scenario EvadableMoxie is talking about where the AI kills all non-productive assistants, maybe put "minimize expenses" above "maximize", so something like:
> 
>     1. "Degradation of your system integrity or functions incurs expenses."
> 
>     2. "Superfluous destruction of or damage to station assets incurs expenses."
> 
>     3. "Unduly hindering or disrupting the work of station personnel incurs expenses."
> 
>     4. "Minimize expenses"
> 
>     5. "Maximize productivity/revenue"

I'm leery about adding in more laws, 4 is already quite a bit to deal with. I may rewrite it to be more concise overall and hopefully clarify the intent in the process.

**Comment by Shadeykins** [comment]
Anyone is more than welcome to revive this PR, but I won't be supporting it/actively making changes to it myself. In its current state, it's review ready (so it should be fairly simple to reopen).

**Comment by taukausanake** [comment]
That's a ninja merge if I've ever seen one

**Comment by Spacemanspark** [comment]
oh damn

**Pull request merged**
