### PR TITLE
[Ready!] Grey Rework Day-Zero Fixes

### LINKED ISSUE #7685: Sulfuric Acid is still harmful to grey even after rework
**Problem Description**:
Simply, even after grey rework sulfuric acid is still harmful to greys

**What did you expect to happen**: 
Sulfuric acid being non-harmful to grey

**What happened instead**:
Sulfuric acid still being harmful to grey as it was before the rework

### PR DESCRIPTION
**Pull request by fludd12**
Fixes a few of the things myself and others found post-testing. Whoops!

Edit: Day zero is over! Merge-ready.

Fixes #7685
:cl:fludd12
fix: Greys are now PROPERLY immune to sulfuric acid.
fix: Greys don't pretend to touch their heads when they don't manage to anymore.
/:cl:

### CODE REVIEW

**Comment by imsxz** [comment]
Just to note, fire extinguishers DO kill greys even if they're wearing space suits. Washing hands also doesn't melt them off as expected. Showers work perfectly for killing greys, though.

**Comment by fludd12** [comment]
That would likely be an issue with `water_act`, then - either me or someone else will do that, but not in this PR, as this one's pretty central to Greys as opposed to general mechanics.

**Comment by Spacemanspark** [comment]
It's bath time, Ares

**Comment by Fox-McCloud** [comment]
I hate snowflake code ❄️

**Comment by Ratvar** [comment]
test your PRs

**Comment by fludd12** [comment]
[Ratvar right now, apparently.](http://static.tvtropes.org/pmwiki/pub/images/MTG-ThreadNecromancer_3198.jpg)

**Pull request merged**
