### PR TITLE
[WIP][DNM] Non-Linear Surgery

### PR DESCRIPTION
**Pull request by alex-gh**
**What does this PR do:**
My attempt at rebasing Crazylemon64s non linear surgery (#7819) onto the current branch.

The non-linear surgery works. Things that need testing:
- Surgery(duh)
- Robo surgery
- Posibrain/MMI behavior

Things that are known to have problems:
- Operating computer inconsistent capitalization.
- You need a cautery to finish IPC surgery (apparently not but it still sometimes shows that message).
- Infections are possibly happening faster? (Not sure about that one)
- Eye surgery is broken - targets head instead.
- Arm surgery also possibly broken

**Changelog:**
Changelog will be added when ready.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Stupid question?
What is NLS

**Comment by alex-gh** [comment]
You no longer have so select which surgery you want to do before you start.
So you can do multiple things at once while you have them open.

**Comment by KasparoVy** [comment]
So you can turn a guy into a nugget in record time.

**Comment by Shadow-Quill** [comment]
Can't implant toolsets into arms, just whacks them with the toolset.
When mending bones, you have to apply bone gel twice before setting and applying gel once more.

**Comment by KasparoVy** [comment]
Couldn't attach a head to a stump by using scalpel then trying to hit the corpse with the head while targetting head.

**Comment by Crazylemon64** [comment]
@KasparoVy with this system you'd just use the limb/head directly, without the scalpel on the stump step

But I might have overlooked limb reattachment, lemme peek

**Comment by Crazylemon64** [comment]
https://github.com/ParadiseSS13/Paradise/pull/10255/files#diff-ee344821159fbe0e08cef7ed6ffb3333R124
This proc needs to be modified to allow organs

**Comment by KasparoVy** [comment]
Fantastic, thanks for the info

**Comment by Mitchs98** [comment]
1. You can no longer use a scalpel + cautery to mend incisions after you saw through bone, slowing down medical significantly.

2. Possibly unrelated; however it seems that genetic disabilities are persisting through profiles. Someone spawned with the seizure disability without having it ticked on that character, but had it ticked on another. I am unsure what this changes, however the fact that human mobs spawned without heads leads me to believe it's possibly related.

**Comment by alex-gh** [comment]
Thanks for looking it over and for the reports, I'll address them in the coming days.

**Comment by Crazylemon64** [comment]
@Mitchs98 IRT #1, That's working as-intended - you need to use bone gel to mend the bones after you cut and fold back the ribcage, before using the cautery

**Comment by Mitchs98** [comment]
That's a significant nerf to surgery imo. Quick mending is an amazing time saver. Realism over gameplay doesn't set well with me in this case :/

**Comment by alex-gh** [comment]
I really want to see this implemented, but I couldn't find the time to finish it.
And it looks like the amount of time I have will shrink even more in the coming days. 

Closing in hopes of revisiting it some time in the future.

**Comment by datlo** [comment]
I'll see if I can pick this back up and do somethin' with it then. Eventually. 👍

**Pull request closed without merging**
