### PR TITLE
Improves bomb logging and replaces single attack log msges with actual logging

### PR DESCRIPTION
**Pull request by farie82**
## What Does This PR Do
1. Improves logging on explosives. Since some where not properly logged and only messaged to admins
2. Adds the amount of chemicals to the create/prime chem bomb log
3. Replaced other `msg_admin_attack` calls with `add_attack_logs`

## Why It's Good For The Game
Better logging for the admins

## Changelog
:cl:
add: Bombs logs are now properly saved in the logging system
add: Chemical bomb creation and priming now logs the amount of chemicals in them
add: Misc attack log improvements that were not saved and only messaged to admins
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Not sure how I feel about this not broadcasting to people who have attack logs completely turned off.

Explosions are kinda in that same category of singularity releases--they're dire enough that most admins should probably hear/know about them, regardless of context.

**Comment by farie82** [comment]
> Not sure how I feel about this not broadcasting to people who have attack logs completely turned off.
> 
> Explosions are kinda in that same category of singularity releases--they're dire enough that most admins should probably hear/know about them, regardless of context.

I got no real experience with the logging levels myself. I used the logic that FEW means that the admin only wants to hear vital stuff. And none being that they don't want to admin for a round

**Comment by variableundefined** [comment]
That's how I use the attack log level personally.

**Review by variableundefined — APPROVED** [review]
@farie82 Deconflict please

**Pull request merged**
