### PR TITLE
[map] Bugfix for air alarms

### PR DESCRIPTION
**Pull request by RudiPardieck**
This removes incorrect tags from a small number of air alarms. These tags caused the atmos computer to access the wrong air alarm. 

Air alarms affected:
Armory Air Alarm
Prisoner Processing Air Alarm
Research and Development Air Alarm
Security Prisoner Shuttle Air Alarm
Virology Air alarm (2x)
Warden's Office Air Alarm

:cl: Certhic
bugfix: Corrected some air alarms so that atmos computer can access them
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
Erm, what?
I think the bigger problem here is the atmos computer interacting with the tag var at all

**Comment by RudiPardieck** [comment]
\ref[src] returns the tag if it's set, which is used to create the link to the alarm. It's not a problem if the tag is unique, but these were identical to each other. I don't know how to create the link without the \ref[src]

**Comment by tigercat2000** [comment]
... BYOND, why.

**Comment by TheDZD** [comment]
:cl: changelog tracking has not yet been implemented, fixes however don't require changelogs either way, so it's up to you whether or not to include a changelog for this PR.

**Pull request merged**
