### PR TITLE
Adds a suspicious multitool to the Syndicate toolbox

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
 Adds a new multitool thats basically just a red multitool thats 5% faster. Also, multitools basically never use speed anyways so... its mostly just for the **coolness**.

Inspired by Whitesands13/Whitesands/pull/64 and Whitesands13/Whitesands/pull/602

## Why It's Good For The Game
 Everything else in the box is red, grey, or black. The yellow multitool looks really out of place.

## Images of changes

Before:
image

After:
image

Multitool is about the same shade as the welder, crowbar, and red-stripe on the toolbox
image

## Testing

Open toolbox, use cool new multitool, no runtimes

## Changelog
:cl:
add: A new suspicious multitool, found exclusively in syndicate toolboxes, and is 5% faster (barely even noticable).
imageadd: Adds a new suspicious multitool sprite
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
Hmm, looking at this from another screen with different settings, the multitool looks slightly muted in color. I'll be able to do changes later but feedback is appreciated

**Comment by Contrabang** [comment]
(Current left, possibly new right? not yet pushed to PR) Left looks better on its own, has good shading and a bit of nice purple shadows. Right has similar colors to the syndi toolbox, red crowbar, and industrial welder. Feedback is appreciated.
image

**Comment by Tokorizo** [comment]
> Also, multitools basically never use speed anyways so... its mostly just for the **coolness**.

If the toolspeed isn't noticeable, why even have it? It would seem better if had the same logic as the screwdriver in having that small noticeable buff if it comes from a syndicate toolbox.

**Review by Sirryan2002 — APPROVED** [review]
code and sprite diff looks good

**Comment by Contrabang** [comment]
> > Also, multitools basically never use speed anyways so... its mostly just for the **coolness**.
> 
> If the toolspeed isn't noticeable, why even have it? It would seem better if had the same logic as the screwdriver in having that small noticeable buff if it comes from a syndicate toolbox.

Mostly because it's funny and that red mean fast. And multitool toolspeed is used like _**nowhere**_, and that makes it even more funny.

**Comment by Contrabang** [comment]
I'm going to be going with the darker, purple shaded one that is shown in the main PR because I think it looks better. Deconflicted now.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
