### PR TITLE
Esword and Desword removal (brand new arrived)

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Resprites eswords and deswords

## Why It's Good For The Game
They are:
- Old
- Ugly
- I fucking hate picking them up

## Images of changes
image
dreamseeker_5TnvsQBQu6

## Testing
with my eyes (and qwerty's eyes too)

## Changelog
:cl:
imageadd: New sprites for eswords and deswords
/:cl:

### CODE REVIEW

**Comment by TravisAngeI** [comment]
might wanna rename this PR so it doesnt sound like you're just deleting e-swords/deswords unless you did that on purpose

**Comment by GreatGatherer** [comment]
What do the in-hand sprites look like?

**Comment by McRamon** [comment]
> What do the in-hand sprites look like?

unchanged

**Comment by TravisAngeI** [comment]
> What do the in-hand sprites look like?

dont think there's a new in-hand because theres none in this picture
image

**Comment by McRamon** [comment]
> might wanna rename this PR so it doesnt sound like you're just deleting e-swords/deswords unless you did that on purpose

we do a little trolling

**Review by Henri215 — COMMENTED** [review]
image
Red double esword has a duplicated frame.

image
Rainbown energy sword static animation is only 4 seconds compared to non rainbown version (5 seconds), making it look fast, unless that was the intent.

**Comment by McRamon** [comment]
> image Red double esword has a duplicated frame.
> 
> image Rainbown energy sword static animation is only 4 seconds compared to non rainbown version (5 seconds), making it look fast, unless that was the intent.

The intent was me being lasy and not making 45 frames to line it up perfectly

**Review by Henri215 — APPROVED** [review]
Looking good now

**Comment by ATP-Engineer** [comment]
Ah, my new box of seclites are here.
image

**Review by Burzah — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
