### PR TITLE
Removes Fox McCloud from the game.

### PR DESCRIPTION
**Pull request by PJB3005**

### CODE REVIEW

**Comment by monster860** [comment]
:+1: :x: :100:

**Comment by Earthdivine** [comment]
Couldn't even wait for 6 more?

**Comment by monster860** [comment]
You need to actually do the `code/modules/karma/karma.dm` shit

**Comment by Spacemanspark** [comment]
I can't tell if this is a meme or not.

**Comment by PJB3005** [comment]
This is less a meme PR than you might expect.

I'm actually semi serious.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by DEATHRATTLERS** [comment]
i seriously vote for this

**Comment by monster860** [comment]
I want to see Fox McCloud merge this.

**Comment by PJB3005** [comment]
Because this is already getting more support than I imagined remember that we can all agree that Vulpkanin would've never gotten in if it weren't for Fox being maintainer.

**Comment by monster860** [comment]
Actually, this will do *nothing* to prevent Fox McCloud from being a vulpkanin. It will only prevent people from changing species to vulpkanin.

**Comment by Earthdivine** [comment]
Except it had been a thing we been talking about for about half a year. We had wanted a dog version of Tarjans. While they are more fox then dog, it was not merged in because of Fox.

Please close this if your not being memey about this.

**Comment by Spacemanspark** [comment]
People that are already vulp would stay vulp with this, I think.
Also, don't worry, I'm quite sure the downvote train will arrive soon.

**Comment by PJB3005** [comment]
I've actually heard from somebody (was it tiger?) that Vulpkanin really only existed because of Fox.

**Comment by Earthdivine** [comment]
That is entirely wrong.

As for why I am telling you this should be closed, is because not only is this obviously against a member of staff, your way of doing it targets the playerbase that have no bearing with this and have many people who quite enjoy the race, and doesn't even do it cleanly, as anyone with the race will still have the race. 

Don't half ass it if you mean it, but also don't drag the community into this if you got a problem. The amount of unprofessionalism this speaks is just staggering.

**Comment by TheDZD** [comment]
The PJSalt is real. This doesn't even remove them properly, just disables them from being a default unwhitelisted race.

**Comment by PJB3005** [comment]
I'm actually not salty I'm just doing it for the sake of it.

**Comment by LightningLynx** [comment]
"We had wanted a dog version of Tarjans. While they are more fox then dog, it was not merged in because of Fox."
No, they just ended up being more fox-like because of Fox

Just like how Vulpkanin just got another fur(tail) pattern that just so happens to allow him to cosplay the character he already got a special costume sprited in for

**Comment by PJB3005** [comment]
I hope you realize that bay has species whitelisted for a reason.

If you're still believing your server is medium RP I hope you wake up.

**Comment by Belario** [comment]
Species decentralisation please, Unathi are the omniversal scaled representatives, when are we getting an iguana version?

Call them Iguaeni give them NV and make them sanic fast, balanced debuff can their damage resistant (10% DR) scales causing a slight time increase for syringe injections.

**Comment by Spacemanspark** [comment]
Should have just taken /tg/'s corgi people that they never merged.

**Comment by PJB3005** [comment]
Even corgi people would've been better. At least people *like* ian.

**Comment by PJB3005** [comment]
> 13 upvotes, 4 downvotes.

Democracy says this should be merged clearly.

**Comment by Spacemanspark** [comment]
The vulp players themselves haven't looked at this/ voted on it, that's probably why.

**Comment by taukausanake** [comment]
I am a vulp player and I wouldn't mind completely if I had to buy vulp, but I'm a weird fuck who loves/hates everything. I would argue it depends what karma price they are set at. Seeing as they are fairly vanilla I'd put them at 5 karma because why not? Less features than every other karma race. You can be a special furry snowflake but for a meager price. I think it's fair given what everyone thinks the server has turned into.

Now how would this work with people who already have vulp characters? I recall this might not affect people who have them already. An SQL change would be needed, that or a grace period where you can unlock vulps while still having them available for everyone to use. After that anyone who doesn't have them unlocked will get the character slot wiped, but that implies I know how the SQL database works or that anyone would want to go through it and do all that

**Comment by tigercat2000** [comment]
Non-karma races will never be karma-locked. @taukausanake

**Comment by Allfd** [comment]
@LightningLynx 

Actually Fox had nothing to do with the new tail.  That was 100% me as I wanted to add an option that was less fox like. But by all means please use this as an example of "We could have actually gotten a dog-like race different enough  ...   but instead we got a race tailored specifically to one of the head staff member's obsessions".  

We could probably change the heads a bit as a sprite option for being more dog like if players so choose, but I have the feeling this is a red haring and we don't need to look any further then the name of the pull request.  As such I don't particularly feel the effort to go through with all the work that would be required as I anticipate heavy resistance to any changes as being too fox like.

This is unfortunate as I am actually a huge supporter of diversity of stats and appearances for the different races, I remember distinctly that originally they were going to have different stats and were under consideration for karma-lock but a large portion of the community wanted them to just be re-skinned Tajaran.  It is not lost on my what portion of the community now complains they are just re-skinned Tajaran or what portions of the community wants them removed and why.

I think its unfortunate how much politics ends up in these PRs, we end up in polarized positions and taking the safe route instead of taking the fun or interesting ones due in part to the politics.

**Comment by Spacemanspark** [comment]
They didn't want them to be reskinned, they just didn't want what Fox as giving them at the time.

**Comment by Necaladun** [comment]
Feel free to close this. 

If you want to discuss races being whitelisted or karma locked or anything, feel free to on the forums. 

If you want to make personal attacks and shitpost, feel free to on the reddit.

This is not the place for this.

**Comment by Vivalas** [comment]
I might actually put a suggestion on the forums to remove Vulp after seeing the support for this.

**Comment by tigercat2000** [comment]
Please don't.

**Pull request closed without merging**
