### PR TITLE
Add Brown & Black Webbing Vest to Biogenerator Designs

### PR DESCRIPTION
**Pull request by Idobtknowlife**
Figure it should be able to be produced somewhere mid-round, considering the number of people that ask for them.
:cl: Idobtknowlife
add: Adds brown & black webbing vest to biogenerator.
/:cl:

### CODE REVIEW

**Comment by ProperPants** [comment]
Add a changelog. It should look like this.

🆑 Idobtknowlife
add: Adds webbing vest to biogenerator.
/:cl:

Otherwise, looks good.

**Comment by Anticept** [comment]
I believe these did exist already in old botany?

**Comment by Fox-McCloud** [comment]
Storage creeeep.

👎

**Comment by Citinited** [comment]
If we're ever going to re-add webbing vests, they probably shouldn't be available at such a low price. With webbing, you basically never have to worry about storage again, you have a hard-to-remove storage item that is very easily missable, and you have a bunch of extra storage with no drawback (see duffelbags giving you two additional storage slots but with -1 slowdown).

Make them like 3000 biomass and they might be balanced (no but seriously 300 is much too low)

**Comment by FlattestGuitar** [comment]
Webbing vests are dumb.

You don't put a webbing under your armor, the two should be interchangeable.

Accessories in general are dumb. 

They are very easy to miss, not clearly indicated visually and really, really useful if you want to hide something. They also behave inconsistently with all other equippable items and are a pain in terms of design. Look - holsters. 

I don't like these. Make these a suit instead and I'd be cool with it, but that makes it the same thing as a hazard vest.

**Comment by shazbot194** [comment]
Going with what flat said, if there were re-made to go over a select number of suits or worn by themselves, I could see that working. Suits like armor, jackets, and maybe a couple special spacesuits. This would work better thematicly too, because why would security not be given some kind of pouch system for their vests.

**Pull request closed without merging**
