### PR TITLE
Changelings automatically destroys implants

### PR DESCRIPTION
**Pull request by Robertha89**
Basically makes changelings immune to implants, the time of two minutes is up for discussion.
+No more loyalty implants
+No more tracking implants
+No more chemical implants for remote gibbing
+No more mindslave implants
-No more Tator implants if tatorling
:cl: PPI
rscadd: Changeling automatically absorbs implants after a while
/:cl:

### CODE REVIEW

**Comment by Plotron** [comment]
Why the fuck?

**Comment by scrubmcnoob** [comment]
OOC:  Shadeykins: This PR will allow you to valid changelings with loyalty implants
OOC:  Shadeykins: Because they'll auto-destroy the implant

**Comment by johannhawk** [comment]
NO NO NO!

its implanting people to check if they are an antag all over again! except EVERY implant can be used!

**Comment by Spacemanspark** [comment]
:-1:
This is unnecessary.
I agree lings need a nerf, but not like this.

**Comment by TullyBurnalot** [comment]
So basically a changeling test, except easier and much more handy for Security?

Yeah, no.

**Comment by Plotron** [comment]
Timer is 1200. How long is that?

**Comment by scrubmcnoob** [comment]
How bout make it a chemical thing? So changelings can do it on their own accord??? Instead of just auto valid hunt.

**Comment by ScratKnapp** [comment]
1200 is about 20 minutes. And yeah, maybe the ling being able to do it by choice would be cool, but just forcing it after a certain time.. no.

**Comment by Earthdivine** [comment]
This is the Changling blood test all over again. No.

**Comment by Robertha89** [comment]
How about we remove cult and vampire test too? Why should there be tests for them, and not this?

**Comment by Plotron** [comment]
Cult tests? The only test is in place so you can deconvert them, and it takes so much time that you need to have them in interro anyway, especially considering they can make the water unholy with their book.

Vampires are a lore thing, I guess. Y'know, chapel 'n shits.

**Comment by CrAzYPiLoT-SS13** [comment]
Not every antag round type is the same.

**Comment by Robertha89** [comment]
@Plotron if you feed them holy water, they will spew out that they are a cultist after less then 30 seconds. 
Pluss this is also lore friendly, Changelings where based upon the movie The Thing, even the blood test is based on that movie.
Even if it is a changeling test, if they get away, the implant wont harm them, can't be tracked if tracking implant, and can't be exploded via range, 50 units is enough to gib a person easy. 
Lets put up some comparisons, cultist never kills unless target, and always convert, so you get to keep playing.
Vampire drain blood, cause clone damage, easy fix, easy clone.
Changelings husk people, and you can't clone husks unless cloning is upgraded, there is also the fact that they can hide so easy, at the drop of a hat. Vampires can do it even better.
Currently the timer is two minutes, which means changelings cant impersonate security or any implanted induvidual, thus balancing it out, it is both a buff and a nerf to them.

But here is the main the main thing, if you are caught, then it's game over, and there is literally no reason to implant everyone, unless the person has committed a crime that warrants it, or willingly agrees to it.

**Comment by Aurorablade** [comment]
No

**Comment by Aurorablade** [comment]
No

**Comment by Aurorablade** [comment]
Damn phone double tap

**Comment by scrubmcnoob** [comment]
Just pointing out that holy water to non cult people gives them brain damage, so feeding the whole crew holy water is not viable.

Where implants have zero side effects if you inject the crew willy nilly with them.

**Comment by Crazylemon64** [comment]
<a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/oldchem/reagents/reagents_water.dm#L238-L277>Holy water</a> doesn't actually cause brain damage, but <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/reagents/oldchem/reagents/reagents_flammable.dm#L28-L41>unholy water</a> does.

**Comment by Earthdivine** [comment]
>Cult
Have to be there shoving water down their throats, and even then that's a substantial loss of time to test them, this isn't something you can do en-mass to people like stun->Implant does. You will get bitched out by players and admins but you outed the ling! Good job!


>Vampire

>You cant use holy water, you need to stun -> Cuff to drag them to the chapel. This is also a loss of time for the officers and not worth it at all.

This? Stun ->Implant, tell surgery not to touch them. Hey, if the implants gone, that means they are a ling! This will cause FAR more accidentally valid kills then anything at all. Not to mention you literally get rid of the new space law that was just added with this. Not to mention this is a big "fuck you" to traitorlings, who get to ENJOY having the benefits of both.

You are assuming people WONT do it, when you need to assume THEY WILL. Average SS13 players will use what means they can to get antags. There's a reason we clipped Holy Water grenades when they got popular. There's a reason we yanked the blood test out even if its true to the movie.

**Comment by theColdflame** [comment]
Lings can use their powers over and over and plead innocence because of a complete lack of ways to ID them. I've seen it happen. If situations like that outweigh validhunting is up for debate, but I think there should be some way to verify a ling beyond testimony.

**Comment by scrubmcnoob** [comment]
We have a detective for a reason, to make a case and convict the person if they are being sneaking with their killings.

**Comment by Plotron** [comment]
Yes, sometimes there's insufficient evidence - even if all your gut feelings point to that person, you just can't do anything about it. Oftentimes it turns out that they really were a changeling.
It's just the way crimefighting works. I'm against implementing specific checks. In a 2-hour shift you've got plenty of time to gather forensics, testimonies. If all else fails, bluff, provoke.

I don't think this PR was meant to introduce a ling check, anyway.

**Comment by Spacemanspark** [comment]
You're not always going to win.
Nor should you.

**Comment by Fox-McCloud** [comment]
This is retarded and just an easy antag check.

**Comment by TheDZD** [comment]
Going to have to agree with everyone here, this is far from a good idea. Not going to reiterate what has already been said outside of the opposition to having yet another antagonist "test." It is a **terrible** idea. People will abuse it no matter which way you use it, it is already arguably horribly abused for vampires since people will just drag vampires into the chapel and watch them burn, with no risk of harming non-vampires.

Using the logic "well, X antag has Y, so why can't Z antag have it?" is nonsensical, you're comparing apples to oranges; yes they're both antagonists, but there is quite a bit differentiating antagonist types from each other.

Controversial tag because a large majority of the comments here are in opposition to this.

**Comment by FalseIncarnate** [comment]
I could potentially support this as a high-cost or long cooldown power, but not as a passive effect.

As a passive ability, it is too strong as it effectively renders every non-lethal means security has of handling a changeling utterly useless by letting them just break free of tracking, chem, or even the incredibly rarely seen exile implants with absolutely no effort on the changeling's part.

**Comment by Robertha89** [comment]
Currently you can already use implants to check such, implant one guy with that, oh hey, another guy we did not implant has it too.
This is intended as a way for changelings to actually survive implants, like i said, the timer is debatable, and should be 5-10 minutes, its both a buff and a nerf to lings.
If you are implanted, you can just wait for it to be destroyed, and then change your identity and get away scoot free, but again here comes another issue, the changeling can't see if the implant is gone without a hud, it also mean when heads of staff are lings and get implanted, nobody will wonder why Greyshirt McDeadbeat had a death alarm. And yes, the passive effect of this is strong, it's intended to be, as a side effect of the other use, which is a changeling test.

Here is the issue again, there is no such thing as non-lethal taking care of it, it can still scream, and get away safe and sound, or monkey + vent crawl away, or just break outta cuffs are armblade. It's like trying to take care of shadowling in a non-lethal fashion, it is impossible, and a bad idea.

Issue is, if it's a high cost or long cool down power, then it becomes too strong because it's up to choice when to destroy them, by making it automatic it has its own inherit weakness, but it also have many strengths, they don't completely balance out, but the scale tips both ways at the same time, to to say.

It is unbalanced, but more balanced then what the changeling powers are.

**Comment by Plotron** [comment]
So it adds another layer of randomness and luck...

**Comment by theColdflame** [comment]
As above, I'm on the fence with this one, but I feel there's certainly a case to be made for this addition. This is pretty much entirely from sec's standpoint, since I don't play ling, so take it with a mountain of salt

As has been stated above, lings being able to evade implantation can benefit them. It's undeniable there's still a net nerf here, but lings are already the strongest crew antag by far. 

This isn't a convinient test; in fact, it takes longer than sec can hold people for. The only application of the test effectively I can see is when sec catch a ling, know they're a ling, but can't actually prove it because lings produce zero evidence using most of them. If a ling is in that situation, they fucked up. 

I'm not going to give a yes/no on supporting this, but I'd encourage people actually consider it rather than just posting 'no'.

**Comment by Fox-McCloud** [comment]
Closing this due to two maintainers sayin' "nah" to it and the majority here saying "nooo".

**Pull request closed without merging**
