### PR TITLE
MrBarrelrolll Fluff Item

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Adds in a fluff item for MrBarrelrolll, the Viridi Protegat. It's functionally identical to the roman armor.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@Necaladun just to confirm

**Comment by Necaladun** [comment]
Yeah if its not messing with anything else and is just an admin thing atm then confirm

-----Original Message-----

**Comment by Fox-McCloud** [comment]
@Necaladun 

It's a fluff item for Mr.Barrel roll---need confirmation if he did, indeed donate and this was, indeed, approved by you.

**Comment by Necaladun** [comment]
...blame my phone, and yes confirmed

-----Original Message-----

**Comment by Fox-McCloud** [comment]
note to @TheDZD and @Necaladun 

This will have to be properly updated, server side, so he can get this.

**Comment by Necaladun** [comment]
@dzd has easier access to the db because of the tv bullshit so all yours 

-----Original Message-----

**Comment by MrBarrelrolll** [comment]
AYY thx bois

**Comment by Necaladun** [comment]
Bois? Unconfirmed. We're men! (manly men)

-----Original Message-----

**Comment by MrBarrelrolll** [comment]
AYY thx men

**Comment by MrBarrelrolll** [comment]
Yoo there was an update or two but the item still doesn't spawn with me. Anyone know why?

**Comment by LittleBigKid2000** [comment]
Whatever the reason is, it probably isn't my fault.

**Comment by Fox-McCloud** [comment]
@Necaladun @TheDZD this item will need to be added to the database.

**Comment by TheDZD** [comment]
Done.

**Pull request merged**
