### PR TITLE
Cyborg Rodeo

### PR DESCRIPTION
**Pull request by Aurorablade**
Refactors the Vehicles i ported from TG to TG riding datums.

This includes:
Riding Cyborgs(you cannot rid one with your hands full)
Piggy backing on players
Parrots riding human
Support for ridable simple animals.

Damageing has an chance to knock your off a cyborg or human.

Runtimes:
I was on this for a few hours so i am brain fried as of writing this. so any extra eyes on what i am doing or missed is nice.
[01:47:11] Runtime in riding.dm,30: Cannot execute null.has buckled mobs().

[01:47:11] Runtime in riding.dm,155: Cannot execute null.has buckled mobs().
Retesting drag and dropping was not working earlier
the spin emote is not working (it lets cyborgs buck people off!)

oh god it has a merge conflict from when i made this branch hours ago!

:cl: Fethas
rscadd: Ride cyborgs, people, the cow!
rscadd: refactors vehicle and riding datums
/ :cl:

### CODE REVIEW

**Comment by jughu** [comment]
🖓 this will naked vulpakhins mount eachother
Just joking this is awesome 🖒

**Comment by Dumbdumn5** [comment]
I am now imagining a janitor riding a janiborg dual wielding space cleaner bottles or copious amounts of the game 'chicken' being played.

**Comment by Spacemanspark** [comment]
YES.
:+1:

**Comment by taukausanake** [comment]
FINALLY WE CAN HAVE THIS!
FINALLY
Please tell me we can chain piggy back rides like this

**Comment by ProperPants** [comment]
How does riding a cyborg or piggybacking a person affect getting shot? Will the rider be more likely to get hit? If the person being ridden gets knocked down, will the rider also fall?
Really cool idea though, I look forward to seeing it implemented.

**Comment by scrubmcnoob** [comment]
yee haw

**Comment by Aurorablade** [comment]
questions answered:
No you cannot stack piggyback that high i do not beleive.
You cannot ride a borg with full hands.

Note to self (or people who want to nitpick the code and tell me what i a mdoing wrong):
runtimes:
01:16:32] Runtime in riding.dm,36: Cannot read null.dir
  proc name: handle vehicle offsets (/datum/riding/proc/handle_vehicle_offsets)
  usr: Marley Sealis (fethas) (/mob/living/carbon/human)
  usr.loc: The floor (69,141,1) (/turf/simulated/floor/plasteel)
  src: /datum/riding/janicart (/datum/riding/janicart)
  call stack:
  /datum/riding/janicart (/datum/riding/janicart): handle vehicle offsets()
  the janicart (pimpin\' ride) (/obj/vehicle/janicart): user buckle mob(Marley Sealis (/mob/living/carbon/human), Marley Sealis (/mob/living/carbon/human))
  the janicart (pimpin\' ride) (/obj/vehicle/janicart): MouseDrop T(Marley Sealis (/mob/living/carbon/human), Marley Sealis (/mob/living/carbon/human))
  Marley Sealis (/mob/living/carbon/human): MouseDrop(the janicart (pimpin\' ride) (/obj/vehicle/janicart), the floor (70,141,1) (/turf/simulated/floor/plasteel), the floor (69,141,1) (/turf/simulated/floor/plasteel), "mapwindow.map", "mapwindow.map", 

[01:17:33] Runtime in vehicle.dm,55: Cannot execute null.handle ride().
  proc name: relaymove (/obj/vehicle/relaymove)
  usr: Marley Sealis (fethas) (/mob/living/carbon/human)
  usr.loc: The floor (68,141,1) (/turf/simulated/floor/plasteel)
  src: the ambulance (/obj/vehicle/ambulance)
  src.loc: the floor (68,141,1) (/turf/simulated/floor/plasteel)
  call stack:
  the ambulance (/obj/vehicle/ambulance): relaymove(Marley Sealis (/mob/living/carbon/human), 8)
  Fethas (/client): Move(the floor (67,141,1) (/turf/simulated/floor/plasteel), 8)

Do not buckle to borgs properly, will get the hand equips.
Piggy backing not working right, has to do with grab state conditional. need to retest when my brain is not fried(help)

**Comment by taukausanake** [comment]
> You cannot ride a borg with full hands

What if you don't HAVE hands? Will this work?

**Comment by jughu** [comment]
No look borg have handles on their head you can grab them just like your bicycle! Occupying your hands

**Comment by Aurorablade** [comment]
Okay guys don't panic but I got to close this to refactor another related system but this will come back in some shape or form. Sorry.

**Comment by taukausanake** [comment]
_EVERYONE PANIC!_

I hope this comes back soon. I really like the idea of piggybacking/carrying others instead of dragging them around. And I _STILL_ want Vox security tower. Make it so!

**Comment by The-Driker** [comment]
I pray that this gets reopened and merged some day. 
So people `CAN RIDE THE BURGER`

**Comment by The-Driker** [comment]
@Aurorablade 
Only thing I care about is riding borgs. I need this so I can kidnap people and drive through the station with them on my burger, screaming.

**Comment by Spacemanspark** [comment]
Please

**Comment by adamkad1** [comment]
hope we can use weapons with that, just like on tg

**Pull request closed without merging**
