### PR TITLE
Balances thermite

### PR DESCRIPTION
**Pull request by jughu**
its kinda stupid if you press 3 buttons and you can instantly take a wall down 

:cl: Improvedname
tweak:Thermite is now harder to make
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
No. This pretty much removes thermite from the game, entirely. It'll never see use because of this.

It's an important aspect to a number of game-modes and strategies. Shouldn't be touched, IMO.

**Comment by Wheatley29** [comment]
Cornoil is stupid and makes no sense, and makes it so insanely difficult to get without pestering botany

**Comment by ppi13** [comment]
It would be nice if it made sense, like first iron and oxygen, heat it to 780 to creat iron oxcide, that then gets mixed with aluminium, or even create magnesium via combining iron water and oxygen and heat it up to a certain temp. Cornoil, hoonestly makes no sense.

**Comment by FalseIncarnate** [comment]
Thermite is literally rust (iron oxide) + aluminum powder, which gets heated to start the highly exothermic reaction.

This is both the real-life and in-game reaction recipe. Changing this diverts from that and honestly isn't needed. If someone is melting walks, they probably have a good reason, as well as it is quite easy to charge them with both vandalism and trespassing, if not also sabotage. Malf AIs can also destroy chem machines, so there's no need to complicate the recipe for that either

**Comment by LittleBigKid2000** [comment]
What Fox said. Also what FalseIncarnate said.
:-1:

**Comment by jughu** [comment]
*SCREAMS*

**Comment by jughu** [comment]
I cant argue real life logic

**Pull request closed without merging**
