### PR TITLE
Lowercase & Remove special characters from every BYOND file

### PR DESCRIPTION
**Pull request by tigercat2000**
This is designed to help us with linux compatibility.

Ignore the branch name, I decided against working on compilation time and icons...

### CODE REVIEW

**Comment by alexkar598** [comment]
So we do want to support Linux?

**Comment by FalseIncarnate** [comment]
I think it is more for compatibility with linux hosting than linux players

**Comment by KasparoVy** [comment]
Man if SS13 worked on Linux (without having to quest back and forth through the 8 layers of hell) that'd be a dream, but I also think it's more for the compiling/hosting.

**Comment by tigercat2000** [comment]
@FalseIncarnate is correct, BYOND provides no clientside tools, but does provide tools for hosting.

Additionally, this is just a good thing to do in general, because it makes it a bit easier to play with the file tree on any OS that's not using a case-insensitive folder structure.

**Comment by alexkar598** [comment]
That's not really what I meant. I was more asking if we want to make hosting on Linux compatible or we don't care about Linux.

**Comment by taukausanake** [comment]
We might need more than just file system cleanliness to run the server on a Linux machine. I think there are some systems included in the code that don't run well on Linux?

**Comment by matt81093** [comment]
@taukausanake any examples off the top of your head?

**Comment by taukausanake** [comment]
@matt81093 Some node or timer thing that Goon made way back when? Not even sure if it's relevant anymore to be honest but it was a few years ago I recall

**Comment by tigercat2000** [comment]
I just realized that Git didn't actually save any of the file names I changed because I used mv instead of git mv. Fuck it, I'll redo this all later.

**Comment by KasparoVy** [comment]
fuuuck, RIP

**Pull request closed without merging**
