### PR TITLE
Removes Clown Soldier/WWII Axis References from Game

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Removes the stalhelm, panzer cap, the literal Nazi uniforms, and the clown military/soldiers that use these items. The clown soldier spawns have been replaced with regular clowns.

## Why It's Good For The Game
 Considering that there are a ton of code comments with these items asking "Why?", I figure now is as good as a time as any to remove literal Nazi paraphernalia.

## Images of changes

Minor Cyberiad changes to fill holes 

image

image

image

## Changelog
:cl:
del: Removes Nazi references from the game
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
baycode
relevant screenshot

**Comment by TORE01** [comment]
Does this remove the clown army jacket from maints and the clown uniform from clown locker too?

**Comment by LightFire53** [comment]
> Does this remove the clown army jacket from maints and the clown uniform from clown locker too?

Yes from maintenance, and it didn't exist in the clown locker. It was just sitting on a table in the clown office.

**Comment by TORE01** [comment]
> > Does this remove the clown army jacket from maints and the clown uniform from clown locker too?
> 
> Yes from maintenance, and it didn't exist in the clown locker. It was just sitting on a table in the clown office.

Any chance you can leave the jacket in?
I have seen several people use it frequently. And it looks pretty cool.

**Comment by LightFire53** [comment]
> > > Does this remove the clown army jacket from maints and the clown uniform from clown locker too?
> > 
> > 
> > Yes from maintenance, and it didn't exist in the clown locker. It was just sitting on a table in the clown office.
> 
> Any chance you can leave the jacket in? Some people use it and imo it looks pretty cool.

Considering that the coat literally has a Nazi Germany armband on it, I'm personally inclined to say no. If server leadership desires it to stay, then I will look at re-adding it.

**Comment by AffectedArc07** [comment]
Im gonna play the somewhat controversial card here.

Obviously rename the stuff that is literally called `nazi`, and remove the red armband from that suit, but keep the items?

Why, see https://www.paradisestation.org/forum/topic/14662-banned-by-normalyman-kegsey-winters/?do=findComment&comment=119835

<summary>Images for those lazy</summary>
<details>

image

image

image

image

image

</details>

And no, I am no a neo nazi. Put your pitchforks down.

**Comment by procdrone** [comment]
this seems excessive, especially considering you don't intend to remove USSP stuff which is clearly inspired by USSR which was just as horrible as Nazi Germany. 

Not to mention this still exists in Lore https://paradisestation.org/wiki/index.php/Elysium_Republic

While I don't see the problem personally, if it's a problem for other people, I could agree with the suggestion Affected made.

**Comment by LightFire53** [comment]
Server leadership would rather rename/resprite the files vs. remove. Closing as it will be easier/faster to start from scratch

**Pull request closed without merging**
