### PR TITLE
Turns Ghosts into Literal Piles of Salt

### PR DESCRIPTION
**Pull request by TheDZD**
As opposed to just figurative ones. Well, it's not like anyone would notice the difference anyways.

### CODE REVIEW

**Comment by Earthdivine** [comment]
Yes please.

**Comment by tigercat2000** [comment]
fixes #5034 ;)

**Comment by Fox-McCloud** [comment]
Merging without Travis 'cause it blew up anddddd it's just a CL =p

**Comment by TheDZD** [comment]
And the build passes right after you do that. Thanks Travis, thanks.

**Pull request merged**
