### PR TITLE
Cqc blueshield

### PR DESCRIPTION
**Pull request by Jazz23**
**What does this PR do:**
Add's CQC to blueshield, direct response to [this suggestion](https://nanotrasen.se/forum/topic/15322-blueshield-buff/). If it's too OP what about krava maga?

**Changelog:**
:cl:
add: Blueshields now have CQC in their knowledge at round start.
/:cl:

### CODE REVIEW

**Comment by Jazz23** [comment]
Can somebody please tell me how to get rid of all those garbage commits

**Comment by Aurorablade** [comment]
BS don't need CQC i am sorry. They never had it before. Krav maga maybe but nto CQC. and you would need to squash commits.

**Comment by variableundefined** [comment]
I don't think they need CQC. Their job is to protect the heads and I don't think they need another powercreep either.

You should consider the merits of an idea suggested by someone before putting it to action.

**Comment by Jazz23** [comment]
> You should consider the merits of an idea suggested by someone before putting it to action.

11 separate people commented on the forum post saying they wanted this added, so I coded it. I've never even play blueshield, just seeing 11 people comment "please add this" in under 12 hours seemed good enough reasoning to me.

**Comment by Breenland** [comment]
I don’t see the harm in putting the PR out there.

Anyways, like others said, it’d be cool to have, though I’d be a bit worried about the Blueshield’s getting a bit more validhunty.

**Comment by ScratKnapp** [comment]
Krav Maga might seem like a better option when their job is defensive in nature.

**Comment by Pckables** [comment]
A Krav Maga implant, similar to the one in the "Bond" Syndicate Bundle would make more sense. Don't need a second pair of Krav Maga gloves on the station.

**Comment by Ralta** [comment]
This is absolutely positively irredeemably terrible. 

Blueshields are bad enough at acting like Security; don't give them more reason to do Sec's job.

**Comment by AzuleUtama** [comment]
As much as it does kinda seem like the BS should be properly trained in unarmed combat given his position, what it will likely lead to in a gameplay scenario is the BS teaming up with security more often since he now has access to powerful offensive abilities he can use on any antagonists he finds.

The krav maga implant might be one alternate option which a few people have mentioned, since the abilities are more defensive in comparison. It would be even better if the ability only worked as long as the BS is in the bridge to encourage them to actually stay there rather than run off and play redshield.

**Comment by Ty-Omaha** [comment]
I think krav maga is good too

**Comment by davidchan13** [comment]
Make it so it only functions if they are within 4 tiles of a VIP. :clown_face: /s

In all seriousness I don't think this is the direction BS should be taken. I'd put my support behind a code red armory or something for them but they are described as a corporate mercenary, not a kung fu agent.

**Comment by Citinited** [comment]
> It would be even better if the ability only worked as long as the BS is in the bridge to encourage them to actually stay there rather than run off and play redshield.

I disagree. Plenty of heads spend their time outside the bridge, which means that those heads will lose out on the Buttshield's protection (even moreso than it is right now).

IMO, spending your whole round on the bridge purely to benefit from the Blueshield makes for a rather boring experience and should be discouraged

**Comment by FlattestGuitar** [comment]
**> Unironic Blueshield buff**

**Comment by Spacemanspark** [comment]
Krav Maga would be a better idea, if anything.

**Comment by Dinarzad** [comment]
> but they are described as a corporate mercenary, not a kung fu agent.

In fairness that's why the initial idea was CQC over Krav Maga.
But even Krav, I mean. Learning hand to hand/unarmed combat, as a bodyguard seems kinda like a no brainer. You should be able to safeguard someone even in the event you are disarmed. I mean modern day soldiers learn martial combat, an even use belt color systems like martial artists do.

Balance is one thing, but in terms of "This doesn't make sense" I'd have to disagree on that point.

**Comment by Ralta** [comment]
> > but they are described as a corporate mercenary, not a kung fu agent.
> 
> In fairness that's why the initial idea was CQC over Krav Maga.
> But even Krav, I mean. Learning hand to hand/unarmed combat, as a bodyguard seems kinda like a no brainer. You should be able to safeguard someone even in the event you are disarmed. I mean modern day soldiers learn martial combat, an even use belt color systems like martial artists do. "MCMAP draws influences from several disciplines including Brazilian Jiu-Jitsu, Wrestling, Judo, Sambo, Boxing, Savate, Kickboxing, Isshin-ryū Karate, Muay Thai, Taekwondo, Kung Fu, Aikido, Hapkido, Eskrima, Sayoc Kali, Jujutsu, Krav Maga."
> 
> Balance is one thing, but in terms of "This doesn't make sense" I'd have to disagree on that point.

It makes perfect sense. From a 'realism' standpoint, a bodyguard at that level with no formal training is probably a bit worthless.

That said, it would make the Blueshield far more powerful than they should ever be, and would push them towards acting like Security. Would it be fun? Heck yeah it would. Is it a good idea? Absolutely not.

**Comment by Jazz23** [comment]
Alright what about a custom, nerfed item similar to the krav, a new custom martial art that only blueshields know that gives them the lore of being a trained agent but not too much of a powercreep. BS's could spawn with special gloves or just have this new martial art as their knowledge.

**Comment by datlo** [comment]
I don't think blueshield needs a buff, and definitely not a buff of that size. Any argument as to "why blueshield isn't able to fight unarmed" could easily apply to the HOS or even sec officers.

Have you ever played with CQC? It's an instant "I win" in any melee situation (as it's supposed to be... it's in the name). Definitely not okay for the BS to have.

**Comment by Citinited** [comment]
Give them CQC but make them honourable i.e. unable to shoot guns 😄

**Comment by Superhats** [comment]
:-1: for CQC
:+1: For a krav maga implant

**Comment by Mitchs98** [comment]
Krav Maga or a special version all to the Blueshield as Jazz said would be nice too. Personally I'm in favor of CQC, however, anything is better than nothing. And I do personally feel that they should get something. If the Warden of all people, who really doesn't have that much to 'guard' gets Krav Maga, why not the guy assigned to guard the station's supposed 'most expensive employees'?

**Comment by KasparoVy** [comment]
Nah mate sleeping crap so you can actually catch the bullets fired at El capitaine

I think this is a brilliant idea but will only go so far as Krav maga

**Comment by tylerh95** [comment]
Krav maga would be a good start.

**Comment by Fox-McCloud** [comment]
Blueshield doesn't need a buff.

His very experience already makes the most well equipped and hardest to take down targets on station all that much more difficult to deal with. This doesn't need to be pushed further.

**Comment by Mitchs98** [comment]
I mean. For the most part. Heads aren't well equipped nor that hard to take down. Really, only the HoS, Captain, and HoP are. So. Eh.

**Comment by variableundefined** [comment]
CQC is way too strong, and we don't believe that blueshield need more buffs either. This'll just encourage redshields more.

**Pull request closed without merging**
