### PR TITLE
Fixes the beekeeper suit and hat descriptions

### PR DESCRIPTION
**Pull request by CyrusJazzberry**
Just a minor text fix.

### CODE REVIEW

**Comment by Plotron** [comment]
https://en.wikipedia.org/wiki/Lil

lol

**Comment by CyrusJazzberry** [comment]
"lil" just angers me irrationally

**Comment by Fox-McCloud** [comment]
Yeah, this isn't a fix, this is a change.

Nothing wrong with a lil bit of silliness in SS13.

**Comment by CyrusJazzberry** [comment]
'little' has been changed back to 'lil', albeit with an apostrophe so i feel better about it's existence

**Comment by FlattestGuitar** [comment]
its*

**Pull request merged**
