### PR TITLE
VV Attack Log Fix

### LINKED ISSUE #8115: VV Attack Log
**Problem Description**:
It appears that the attack logs have been sanitized. This changes them from their lovely coloured state into a less lovely pure black state with HTML tags

**What did you expect to happen**: 
To see the aesthetically pleasing attack log section of the VV of a mob

**What happened instead**:
https://i.gyazo.com/d33edf507b41ed74f5eff94e104e95b5.png

**Why is this bad/What are the consequences:**
Change is bad.

**Steps to reproduce the problem**:
1. Find a mob with attack logs
2. VV the mob and search for the attack logs variable
3. ???
4. Profit

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

### PR DESCRIPTION
**Pull request by scrubmcnoob**
VV is no longer color blind friendly.
We have color on our attack logs now.
thank tiger for providing code cause fuck that i would've ever fixed
this lol
fixes #8115

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
oh right 
#8115

**Comment by taukausanake** [comment]
Fixes 8115. You need the keyword in OP

**Comment by SamHPurp** [comment]
Both of you did it wrong.

Fixes #8115

**Comment by taukausanake** [comment]
I did it wrong on purpose because I'm not the one trying to fix it :angry:

**Comment by tigercat2000** [comment]
lgtm

**Pull request merged**
