### PR TITLE
Nerfs Shotguns

### PR DESCRIPTION
**Pull request by Fox-McCloud**
I've said this was coming for a very long time, now--probably over a year. This is ongoing with the combat overhaul.

Nerfs shotguns--the crew will no longer have access to the readily available buckshot or slugs for combat shotguns or riot shotguns.

Shotguns are currently the be all and end all of ranged combat---they're fast firing, they have printable ammunition, they do obscene amounts of damage at close range, and they are crippling at medium range---they cause bleeding, broken bones, and internal bleeding---to say they're unparalleled is an understatement. They've been nerfed multiple times, but this is the best direction to take them in. This keeps them still quite viable for taking down non-lethally, however.

The second issue is they violate the base level theme of SS13 that was established long ago---syndicate primarily uses ballistics and NT primarily uses energy weapons. Right now it makes way more sense to arm up with shotguns than it does anything else, bar a few examples.  If ballistics are to exist in NT territory, they should be rare and quirky (like the WT).

This also adds tranqs to Meta, as it didn't have them.

Expect further changes in the future (buffs and nerfs), but this is the most egregious of shotgun abuse at the moment.

:cl: Fox McCloud
del: removes buckshot and slugs from the crew. Autolathes, cargo, armories; they're all gone.
add: Adds tranq rounds to MetaStation
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
Mapping wise this looks fine, some weird difs with mobs being shuffled about within their map key for no reason. But that won't actually affect anything.

**Comment by SabreML** [comment]
Are there any plans to testmerge this in order to test the balance implications?

I don't think anyone can disagree that the current shotgun meta is an issue, but such a big nerf could have a pretty serious effect on the balance of a lot of antagonists/gamemodes as well.
Specifically I'm thinking of Nuke Ops, since in every nukie round I can remember shotguns were used as the crew's primary weapon against the threat. And the same to a lesser extent with some other midround antags.

Just to be clear, I'm definitely in favour of this nerf. I just think it would be a good idea to see how much it affects the game's overall balance first, to avoid any possible situations such as nuke ops becoming practically unkillable.

**Comment by Darkmight9** [comment]
Admittedly been out of the balance loop for a while but what about Nuke ops and E-swords? What'll be used to combat against those since we won't have buckshot? There's the semi auto WTs (if I'm thinking of the right thing) but that's not gonna stop a nukie from slicing and dicing a bunch of crew

**Comment by Wojz** [comment]
> Admittedly been out of the balance loop for a while but what about Nuke ops and E-swords? What'll be used to combat against those since we won't have buckshot? There's the semi auto WTs (if I'm thinking of the right thing) but that's not gonna stop a nukie from slicing and dicing a bunch of crew

Buckshot has been dealing toolbox damage to nukies for months now ever since its armor penetration nerf. The removal of slugs though does kind of make me wonder. But, the stamina damage ammunition for shotguns still does fold nukies pretty handily, even with adrenals.

**Comment by Cocacolagua** [comment]
Considering that this drastically limits the usefulness of the shotgun, I suggest to also revert #15257 so shotgun users can atleast carry something else, too.

**Comment by hal9000PR** [comment]
> Considering that this drastically limits the usefulness of the shotgun, I suggest to also revert #15257 so shotgun users can atleast carry something else, too.

Being able to oneshot stamcrit someone from 3 tiles away is still powerful.

**Comment by matttheficus** [comment]
This leaves the Crew with beanbag and tranq shells for the Armory, yes?

And honestly, having the only main ballistic being the WT-Rifle would be nice. Gives it a purpose other than niche preferred usage.

**Comment by Mitchs98** [comment]
Yes.

**Review by variableundefined — APPROVED** [review]

**Comment by Coolrune206** [comment]
Oh boy, maybe those tech-shells from RnD will actually get some use now. Or the incendiary slugs from the autolathe - unless they're gone too.

**Comment by Darkmight9** [comment]
> Oh boy, maybe those tech-shells from RnD will actually get some use now. Or the incendiary slugs from the autolathe - unless they're gone too.

Seems it's only the standard slug and buckshot that are removed from the lathes. We'll have a tool for dealing with shielded hardsuits at least

**Comment by ItsMarmite** [comment]
> Are there any plans to testmerge this in order to test the balance implications?
> 
> I don't think anyone can disagree that the current shotgun meta is an issue, but such a big nerf could have a pretty serious effect on the balance of a lot of antagonists/gamemodes as well.
> Specifically I'm thinking of Nuke Ops, since in every nukie round I can remember shotguns were used as the crew's primary weapon against the threat. And the same to a lesser extent with some other midround antags.
> 
> Just to be clear, I'm definitely in favour of this nerf. I just think it would be a good idea to see how much it affects the game's overall balance first, to avoid any possible situations such as nuke ops becoming practically unkillable.

In regards to nukies, I've noted a general trend towards crew using disablers/stunbatons/plasma pistols against them in all honesty- mostly because adrenals do shit all against disablers, but that's a discussion for another time.

If I had to offer a suggestion to this PR, perhaps make it so rubbershot can be printed in hacked autolathes? As far as I'm aware, they're currently only available as a base ammunition inside riot shotguns.

**Comment by Mitchs98** [comment]
> > Are there any plans to testmerge this in order to test the balance implications?
> > I don't think anyone can disagree that the current shotgun meta is an issue, but such a big nerf could have a pretty serious effect on the balance of a lot of antagonists/gamemodes as well.
> > Specifically I'm thinking of Nuke Ops, since in every nukie round I can remember shotguns were used as the crew's primary weapon against the threat. And the same to a lesser extent with some other midround antags.
> > Just to be clear, I'm definitely in favour of this nerf. I just think it would be a good idea to see how much it affects the game's overall balance first, to avoid any possible situations such as nuke ops becoming practically unkillable.
> 
> In regards to nukies, I've noted a general trend towards crew using disablers/stunbatons/plasma pistols against them in all honesty- mostly because adrenals do shit all against disablers, but that's a discussion for another time.
> 
> If I had to offer a suggestion to this PR, perhaps make it so rubbershot can be printed in hacked autolathes? As far as I'm aware, they're currently only available as a base ammunition inside riot shotguns.

Rubbershot can be lathed, as can beanbags.

**Comment by Wojz** [comment]
> Seems it's only the standard slug and buckshot that are removed from the lathes. We'll have a tool for dealing with shielded hardsuits at least

Just shoot them with rubber it's overpowered anyways and will body them.

**Comment by Denthamos** [comment]
A tad concerned on how this would effect nuclear ops, double esword users with armored suits users in general, and simple mob antagonists which are balanced around that aspect with no projected timeline on when such changes may come.  

Going to want a few test merges done first with various round types before any decisions is made regarding this due to how integral shotguns are for dealing with armor and high health sponges.

**Review by Kyep — COMMENTED** [review]
I'm currently neutral on this.
I do agree that shotguns are very overpowered, compared to most other weapons.
I'm not sure that this is the best way to deal with it, though. While certainly effective, I do worry that this cripples the crew's ability to resist certain antags (e.g: nuke ops with eshields) too much.

**Comment by hal9000PR** [comment]
I do think people are missing the genuine power of rubbershot. 

Rubbershot in a combat shotgun would drop a nukie with a shielded hardsuit/elite hardsuit like a rock. This opens them up to having their weapons stolen or being unloaded on by lasers and autorifles. 

I do agree that maybe nukies should get a minor armour/TC nerf in order to compensate. But I don't think it's such a major issue.

**Comment by lectronyx** [comment]
If ballistics are syndicate and energy weapons are NT, then... what about energy crossbow? Why does the X-Ray Laser have Syndicate tech levels? What about M1911s, the aforementioned WT-550s, and Enforcers? Also, if I'm not mistaken, aren't Unicas often used by ERTs?

**Comment by Sikroth** [comment]
Skeptical on this, I don't know if this is the best way to go about things.

Sure shotguns are stronger than the other alternatives in most situations, but they're also basically the only good option in those situations. This PR might as well read "buffs nukies, deswords, terrors, slaughter demons, etc" because it's axing the main counter to those without any decent alternative.

I'd say at the very least testmerge before approving this, if only to see how those rounds go without shotties.

Side idea, add scatter shot laser rifles?

Another thought, while I personally don't mind it, the concept that NT relies mostly on energy weapons has really little to support it besides the "it's always been like this". I don't think there's any lore reason, and lore in paradise always has taken a backseat to gameplay anyway. I think refusing to explore options because they break some old, arbitrary convention is a bit narrow minded.

**Comment by hal9000PR** [comment]
> add scatter shot laser rifles? 

Let's not replace shotguns with energy shotguns. That defeats the entire purpose. 

> This PR might as well read "buffs nukies, deswords, terrors, slaughter demons, etc."

Terrors are normally delt with using AEGs. Shotguns aren't that useful against them aside from bursting down a queen which isn't exactly interesting. 

As I have stated previously, I do agree with the nukies one a little and I agree with the slaughter demon one alot. 
Rubber shot will dunk on nukies still, then you can steal their weapon. Two rubbershots will stam crit a nukie from a decent range. And 3 beanbags will from any range. Then you can steal their weapon/unload into them. 

Slaughter demons however, might be problematic. Recently I rolled slaughter demon and I was able to eat about 2/3 of the crew. And that is WITH all of sec having combat shotguns and having an ERT called. I would imagine that slaughter demons could do with a substantial health or healing decrease in order to compensate.

**Comment by Dafrek** [comment]
Since when have shotguns been the be-all end-all of combat? A traitor with a taser will beat a sec officer with a shotgun most of the time, especially if the traitor is running away from the officer and shooting behind them. I can understand removing the ability of lathes to print out lethal rounds, because that can make it too easy and quick to get them, but they should at least be left in the armory and cargo shuttle.

**Comment by Spacemanspark** [comment]
>A traitor with a taser

We're removing those too. Thank god.

**Comment by VynalDerp** [comment]
> > add scatter shot laser rifles?
> 
> Let's not replace shotguns with energy shotguns. That defeats the entire purpose.

Scatter shot lasers are nowhere near as good as buckshot. I'm not sure if they deal less damage per pellet or the as shotguns with buckshot or the fact that there are fewer pellets. It takes 2 buckshot from one tile away (all pellets hitting), while scattershot takes 4 shots from one tile away in order to kill with all pellets hitting.

Scattershot also sometimes bounces off of walls and things, not sure the cause, but pretty dangerous for the wielder and anyone nearby.

With all the testing I have done with humanoids (for my Xeno PR) recently I would say the best option would be to replace the shotgun with the scattershot, and leave the shotgun and it's ammo types as an order from Cargo for when nukies or other antags, such as spiders, roll into town. However, scattershot would need a nonlethal mode in order to make up for the lack of rubber bullets and tranq rounds. My suggestion for this is to make the alternative mode change from a laser rifle with less ammo to a disabler shotgun spread which is overall weaker than a single disabler shot (even if all pellets hit), counteracted by the fact that... it's easier to get hits.

>Terrors are normally delt with using AEGs. Shotguns aren't that useful against them aside from bursting down a queen which isn't exactly interesting.

Shotguns can be extremely effective against terrors with buckshot. Buckshot literally two shots a Red from one tile away, straight to gib. Takes three for a white. Even when not all pellets hit, it still does a considerable amount of damage. Worst case, it's the same as shooting them with lasers, best case, it's even better. The downside is higher risk of crew FF if you miss your target, or not all pellets connect.

Anyway, back on topic to the PR. If Buckshot and slugs are still available from Cargo to order as ammo (through crates), then I'm all in favor of this change. Shotguns have a niche against certain antags and shouldn't be removed from the ability for crew to access entirely, but should instead have a cost for the crew. This method could allow for better balancing, such as adding more shotguns per crate, more ammo per crate, or increasing/decreasing crate cost to filter 

NT does generally have a heavier sci-fi and energy weapon theme, and personally I would prefer to see the ballistic weapons from crew replaced with energy equivalents. ERTs would make sense to carry the best weapons to suit the job, and sometimes that might be ballistic weaponry - so I'd be willing to give a pass for them using non-energy weapons despite being NT.

**Comment by Sikroth** [comment]
> > add scatter shot laser rifles?
> 
> Let's not replace shotguns with energy shotguns. That defeats the entire purpose.

Just a quick note on this, for clarity. A scatter energy weapon would solve the issues with printable ammo spam, as well as bleeding/broken bones/IB. The damage values can always be adjusted, but by virtue of them being energy and thus not brute they would already be weaker and less problematic.

**Comment by cluwneythescourge** [comment]
why bother with all of this nerfing when you could just run TG and get it all at once

**Comment by AffectedArc07** [comment]
And nothing of value was lost.

**Pull request merged**
