### PR TITLE
Fixes Resisting Borers

### PR DESCRIPTION
**Pull request by Twinmold93**
This changes the captive brain's resist connection back to resist() from
resist_borer() (an invalid verb). Makes it so you can once again resist
borers.

:cl: Twinmold
Fix: You can once again resist borer control with the Resist verb.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
You need to get rid of the base proc

`resist_borer` under living.dm since it's unused and does nothing.

**Comment by Lady-Luck** [comment]
I recall someone I was borering not getting any message either, not knowing they should resist or not, irregardless of the resistance itself being broke.

**Comment by Twinmold93** [comment]
Odd... Why is it saying it's still a conflict...

**Comment by Twinmold93** [comment]
Yeah... I'm going to do something here and close this one and post a fresh one.

**Pull request closed without merging**
