### PR TITLE
Cleans up weird cable vars on maps plus floors dirs

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## What Does This PR Do

I hate this shit, it clutters the instance list and makes mapping needlessly complicated. Blah blah blah makes no actual changes. Also don't pixel shift cable by one pixel it's awful.

Edit: This is now floor dirs too. Stop dirring floors.
Edit edit: Removed dir 0 from some pumps. Dir zero isn't a real dir, it can't hurt you. (but it CAN be an extra line)

## Changelog
Blah blah blah players won't see it

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
I have to remove 1500 more instances of dirred floors at minimum. Stop with the goddamn dirred floors, I swear to god.

**Comment by GuiltyNeko** [comment]
Also there were a few instances of icon_state = carpet so I put carpet down instead.

**Comment by GuiltyNeko** [comment]
So for some fucking reason strongdmm isn't capable of cleaning ALL default vars so I get to do it manually on loot spawners, yay me.

**Review by S34NW — APPROVED** [review]
I swear to god whoever keeps putting these back in is going to get a slap

**Comment by AffectedArc07** [comment]
Please deconflict

**Comment by GuiltyNeko** [comment]
It has occurred to me that I have probably managed to conflict myself, somehow.

**Comment by GuiltyNeko** [comment]
Probably unconflicted. 90% certain there's no holes-in-shit, I checked the areas where stuff was changed in strongdmm.

**Review by S34NW — CHANGES_REQUESTED** [review]
image
Delta: You've changed instances of this in other parts but not here, might as well throw it in.

image
Meta: Missed dir floor tile where it shouldn't be

image
Meta: Whole bunch more of random directional floor tiles where they should not be

image
Meta: Another one

image
Meta: Another one

image
Meta: No other corridor has these down the middle, yeet them.

image
Cyberiad: This is wonky and looks off, please shove the highlight in the corner

image
Cyberiad: single tile of highlight, yeet it

**Comment by S34NW** [comment]
image

THE TAGS ARE BACK

**Comment by GuiltyNeko** [comment]
Swear to fucking god. Give me a bit more to work on it.

**Comment by GuiltyNeko** [comment]
Yeah so the cable dirs came back because, for some reason, those tiles were conflicted with master, again, for SOME reason, and I just overwrote the damn changes with the stuff from the master branch. Also, I had a hell of a time finding the thing next to the morgue, also also, I thought I would do this tomorrow, I was wrong. Also also also, can we put "don't dir dirless floortiles" in the contributing guidelines?

**Comment by S34NW** [comment]
> Yeah so the cable dirs came back because, for some reason, those tiles were conflicted with master, again, for SOME reason, and I just overwrote the damn changes with the stuff from the master branch. Also, I had a hell of a time finding the thing next to the morgue, also also, I thought I would do this tomorrow, I was wrong. Also also also, can we put "don't dir dirless floortiles" in the contributing guidelines?
> Edit: Not "cable dirs", you know what I mean.

It makes me worried that edits in the queue started before you have cleared these will bring them back again. It's not your fault it's how merging just seems to work, we've had similar issues of changes being reverted in the past

**Comment by S34NW** [comment]
> Swear to fucking god. Give me a bit more to work on it.

Thanks for taking the time to re-do all this, it's a nightmare but we appreciate it ❤️

**Comment by GuiltyNeko** [comment]
Some cruel person has put down many icon_state dark tiles when we have a perfectly functional dark variant, so I have to go get rid of THOSE too.

**Review by S34NW — APPROVED** [review]
LGTM

**Review by S34NW — APPROVED** [review]
edit: this duplicate was a review for another PR that somehow ended up here, sorry!

**Comment by GuiltyNeko** [comment]
Okay I deconflicted probably. And then I did some more stuff. Quick, merge it before I find more bad mapping trends. Also, it proooobably doesn't have issues but this is one of those situations where literally nobody could ever know, let's be honest. This shit is fucking esoteric.

**Review by S34NW — CHANGES_REQUESTED** [review]
Final bits:

image
This still has a blank tag

image
These still litter delta with needless dirs

image
This is var edited on meta instead of using /turf/simulated/floor/plasteel/airless

image
Two instances of full floor tiles with dirs on box

image
same on box

image
loads of these on meta

image
this is var edited on delta instead of using /turf/simulated/floor/plasteel/dark/nitrogen

image
dir 5 is not needed for these

image
dir 4 not needed on these, same with the "icon_regular_floor" var

**Comment by GuiltyNeko** [comment]
I didn't do anything about the "vacuum floor" because when I mentioned it to you you didn't say to do anything in particular to do with it, so of course, I ignored it because I dunno, mapping is fucking weird.

**Comment by S34NW** [comment]
> 

Yeah, you've done a lot of good work but it's inevitable there's gonna be something extra

**Comment by GuiltyNeko** [comment]
Anyways half of that stuff was stuff I didn't even look at from the incoming PR nonsense, because for some reason I just didn't think to look at it.

**Review by S34NW — APPROVED** [review]
Good to go

**Comment by S34NW** [comment]
@AffectedArc07 ^

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
