### PR TITLE
Maintenance Drone Vent Crawling

### PR DESCRIPTION
**Pull request by scrubmcnoob**
Allows Maintenance Drones to vent crawl around the station. 
Made a suggestion on the forums a while back and everyone was fine with it, it was a matter of finding some one to do it.
I finally went through the code and found the correct code for this change.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Prolly fine.

**Comment by Robertha89** [comment]
Oh right. Forgot about this.

**Comment by Plotron** [comment]
Yes yes yes! FINALLY!

**Comment by Davdichan** [comment]
https://www.youtube.com/watch?v=a8c5wmeOL9o

**Pull request merged**
