### PR TITLE
Cluwne Mask now allows internals usage

### PR DESCRIPTION
**Pull request by Ar3nn**
prevents cluwne curse from autokilling Vox because they can't breathe (plasmamen have other problems, but anyway)
🆑 Ar3nn
tweak: cursed cluwne mask now allows internals to be fed through it
/🆑

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
👏 cluwne powercreep

**Comment by Rumiluntti** [comment]
Yes, I don't think vox and plasmamen should get out from the torment that easy.
Suffer, you spess parrots and fart skeletons!

**Comment by Ar3nn** [comment]
Well, plasmamen will just burn to death. But Vox just suffocate because they cant get their nitro tanks to work with the mask so they just choke.

**Comment by taukausanake** [comment]
Seeing Plasmamen get a full cluwn spess suit would be great actually. Don't they get something for clown job anyways or do they?

**Comment by DesolateG** [comment]
Well, there is a cluwne mech

**Comment by Fox-McCloud** [comment]
This isn't the way to do it; it should be a subtype of the regular clown mask with the appropriate flags set, not adding the flags to it.

**Comment by Krausus** [comment]
> it should be a subtype of the regular clown mask with the appropriate flags set, not adding the flags to it.

The flags have to be overridden anyway, because the regular clown mask isn't `NODROP`. Plus, subtyping it would require overriding the `attack_hand` proc. Simply adding the flags is the cleanest way to do this.

**Comment by Doukhan** [comment]
Noooo! Isn't cluwning is meant to be an utterly incapacitating delayed gibbing? 9/10 they get lynched by the first crewmen they see anyway.
Pffft

**Comment by Spacemanspark** [comment]
:-1:

**Comment by Ar3nn** [comment]
Yes, but thats the fun of it. If the cluwne is already choking to death on the ground it takes the fun out ofi t.

**Comment by Ar3nn** [comment]
So...Do I need to change something or not?

**Pull request merged**
