### PR TITLE
Adds the Posters I entirely forgot about.

### PR DESCRIPTION
**Pull request by TravellingMerchant**
Adds the requested posters from that old poster PR I forgot existed because I'm an idiot. I know there is a rouge pistol in the preview but that isn't in the icons.

posterssmall

Names and descriptions below.

name += " - Spider Risk"
desc += " A poster detailing what to do when giant spiders are seen."

name += " - Kill Syndicate"
desc += " A poster demanding that all crew should be ready to fight the Syndicate."

name += " - Information on Air"
desc += " A poster providing visual aid to remind crew of air canisters"

name += " - Information on Air"
desc += " A poster providing visual aid to remind crew of air canisters"

name += " - Dig For Glory!"
desc += " A poster providing trying to convince crew to mine for ore."

name += " - Religious Poster"
desc += " A generic religious poser telling you to believe."

name += " - Stay Healthy!"
desc += " A healthy crew is a happy crew!"

### CODE REVIEW

**Comment by LightFire53** [comment]
Your heal poster has a random black pixel a couple of pixels down from the bottom in your gif, is this reflected actuality?

**Comment by FalseIncarnate** [comment]
I'm seeing a number of commits from another repo/account which seem entirely unrelated... care to explain those?

**Comment by TravellingMerchant** [comment]
Uh what the fuck are those? I certainly didn't do that.

**Comment by Fox-McCloud** [comment]
need to update your master, someone rogue direct committed to the codebase.

**Comment by TravellingMerchant** [comment]
Ah so I'll have to remake this PR. Will do it later.

**Comment by KasparoVy** [comment]
@TravellingMerchant I resolved it on my branch by using `git rebase <sha-here>` then the sha hash of the most recent commit here >> https://github.com/ParadiseSS13/Paradise/commits/master where <sha-here> is

**Comment by TravellingMerchant** [comment]
That is sadly gibberish to me.

**Pull request closed without merging**
