### PR TITLE
Alphabetizes character creation options (Hair, clothes, etc)

### PR DESCRIPTION
**Pull request by Darkmight9**
## What Does This PR Do
Alphabetizes the options in character creation(Hair, clothing, body markings, etc) 

## Why It's Good For The Game
This makes it easier to find a hairstyle or shirt you're looking for and makes things cleaner in the options while also making it so that future hairstyles and what have you are already alphabetized.

## Changelog
:cl:
tweak: Hair styles, body markings, clothes, and other character customization options are now alphabetized.
/:cl:

### CODE REVIEW

**Comment by variableundefined** [comment]
timmy

**Comment by Shockpoint** [comment]
Not all heroes wear capes, some code this stuff instead

**Comment by Darkmight9** [comment]
Travis please cooperate.

**Comment by Darkmight9** [comment]
Yeah I don't really know how I'd go about unsorting those

**Pull request merged**
