### PR TITLE
Better taste messages for ALL drinks and Rainbow Juice

### PR DESCRIPTION
**Pull request by DrawitRalph**
**What does this PR do:**
Ports some taste messages form other codes, and others I made up myself.
Also adds a new drink: Rainbow Juice, which can be made with the following recipe:
1 part Berry juice, 1 part Banana juice, 1 part Grape juice, 1 part Lemon juice, 1 part Orange juice and 1 part Watermelon juice.

**Images of sprite:**
rainbowjuice

**Changelog:**
:cl:
add: Added new drink: Rainbow Juice
add: Added taste messages to drinks that didn't have it
tweak: Changed taste messages for most drinks
imageadd: Added custom animated sprite for Rainbow Juice
/:cl:

### CODE REVIEW

**Comment by DrawitRalph** [comment]
@Ty-Omaha Most of these are meant to be jokes, but I guess I don't mind changing those.

**Comment by Citinited** [comment]
Did you port all of these from hippie or something

**Comment by DrawitRalph** [comment]
@Citinited I ported some from tg, some from bay, and made up some others. This is so the bartender can get creative when mixing drinks. For example:

15u Syndicate Bomb
10u Irish Car Bomb
10u Salt
Will give you a Syndicate Bomb with the following taste message:
**You can taste purified antagonism, delicious anger and salt.**

OR my personal favorite
10u Anti-freeze
10u Whiskey Soda
15u Irish Coffee
**You can taste poor life choices, mediocrity and your hopes and dreams.**

It's a fun way to make the role of the bartender more interesting to play.

**Comment by Citinited** [comment]
IDK if it's just me but it just seems so... low-brow? Like most of them are jokes instead of what the drink actually tastes like. Doesn't seem like a very good thing to have, IMO.

For example, the few times I've had sake I didn't think "oh wow this tastes like weeaboo shit".

**Comment by variableundefined** [comment]
Nearly all of the taste are not tastes, but rather crude, low-brow jokes, inappropriate for the roleplay level we are going for. This PR has been rejected by heads consensus and as a result will be closed.

**Pull request closed without merging**
