### PR TITLE
Makes DNA swapping methods more reliable and other appearance tweaks

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
bugfix: Makes heads keep hair on removal
bugfix: Amputated limbs from a DNA-injected individual now will keep their appearance of the DNA-injected person
bugfix: Wounds will vanish on their own now
rscadd: Admins now have an "incarnate" option on the player panel when viewing ghosts for quick player instantiation
bugfix: Fixes a runtime regarding failing a limb reconnection surgery
bugfix: Copying a client's preferences now overrides the previous mob's DNA
bugfix: A DNA injector is now more thorough, and affects the DNA of mobs' limbs and organs
bugfix: DNA-lacking species can no longer be DNA-injected
bugfix: Brains are now labeled again
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
While you're at it, would you mind fixing the bug where all brains are just "brain"?

It used to say "[mob]'s brain", so you coudl identify it...but not anymore.

**Comment by HereticChurch** [comment]
Not sure how realistic it is being able to identify someone's brain just by looking at it, but I've got no issues with it. :+1:

**Comment by Fox-McCloud** [comment]
>Not sure how realistic it is being able to identify someone's brain just by looking at it, but I've got no issues with it. :+1:

It's not realistic, for sure, but it's been a "thing" for literally years.

**Comment by Keilden** [comment]
In the future brains have nametags.

**Comment by KasparoVy** [comment]
I can tell by the very wrinkles in your grey matter!

**Pull request merged**
