### PR TITLE
Advanced structural roborepair fixes disfigured bits

### PR DESCRIPTION
**Pull request by Crazylemon64**
I mean replacing the head should work too but alright

Does this trivialize IPC face repair ya or na

What this does:
* Advanced cyborg limb repair (welding while the cover is opened) will repair disfigurement

### CODE REVIEW

**Comment by Ar3nn** [comment]
How did you used to do it before? Just curious so I can compare, I've never actually seen or performed face repair on IPC.

**Comment by fludd12** [comment]
I think you just popped the head off and back on again.

**Comment by Ar3nn** [comment]
Well, not having to cut the head off makes it feel less barbaric, if nothing else.

**Comment by KasparoVy** [comment]
Having to remove and reattach the head to fix disfigurement sounds like a bug
squash em

**Comment by Crazylemon64** [comment]
No, removing and reattaching the SAME HEAD does not fix the face. THAT would be a bug.
As it stands, you need a NEW head and swap it out with the OLD head to "fix" the face (and put the optics back in the new head if you're a decent roboticist).
The lack of ability to do so otherwise, combined with the apparent difficulty of expressing that you need a new head to actually repair the face, is more on the oversight side than a bug.

**Pull request merged**
