### PR TITLE
Cheeky Crenando's Fluff Item

### PR DESCRIPTION
**Pull request by Agameofscones**
CKEY: `CheekyCrenando`
Character Name: `Srusu Rskuzu`
Job: `NA, general clothing, no special attributes (besides lookin' snazzy)`

Sprites by the dude himself, I'm just here to git-fu the PR for 'em.

image

**Changelog:**

:cl:
add: Cheeky Crenando's Soviet Greatcoat Fluff item.
/:cl:

### CODE REVIEW

**Comment by Ionward** [comment]
Fits in good with the other soviet gear, I like it!

**Comment by KasparoVy** [comment]
Davaj davajjj 😂👌

**Comment by variableundefined** [comment]
@Agameofscones Need deconflict as the custom item before them has been merged.

**Comment by Agameofscones** [comment]
Alrighty gimme a bit

**Pull request merged**
