### PR TITLE
adds spork

### PR DESCRIPTION
**Pull request by Aurorablade**
...'s fluff item.

Fluff type:Ai hologram
Ckey:Spacemanspark

:cl: Fethas
rscadd:Spacemansporks ai hologram.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
I was ready to instantly downvote for spork. Now I instantly downvote for the bamboozle 😠

**Comment by Spacemanspark** [comment]
Credit to dumbdumn for the sprite!

**Comment by KingPhilipIII** [comment]
Downvote for clickbait title.

**Comment by outbools** [comment]
image

**Comment by Fox-McCloud** [comment]
0/10 not an actual spork item for the kitchen.

**Comment by Ralta** [comment]
Where's my spork, dammit?

**Comment by Spartan6** [comment]
Spork Syndicate item for the chef?

Aw it's just Spark being a snowflek

**Comment by Fox-McCloud** [comment]
Conflictsss

**Comment by Spacemanspark** [comment]
Conflicts terminated

**Pull request merged**
