### PR TITLE
Removes Christmas, keeps fixes

### PR DESCRIPTION
**Pull request by FreeStylaLT**
What it says on the tin, keeps the Arrivals fixed airlock, Medbay's fixed maint cable, missing nitrogen / plasma tanks and the fixed surgery light, but removes all of the Christmas doo-dads.

Also adds a camera near Medbay, which fixes a blindspot:
img

Closes #8500 
🆑Disgruntled HR Department
del:Cyberiad finally had its heating budget upped to melt all the snow.
del:Central Command's janitors cleaned up all the misplaced trees and gifts. Toys do not boost productivity.
fix:Keeps the fixes that were made in the Christmas version
fix:Adds an additional camera to the Medbay's side of the Central Hallway, eliminating a blindspot.
add:Added a cryo console to Robotics.
fix:Double doors in brig.
/🆑

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Muh holiday spirit.

**Comment by SamHPurp** [comment]
Freestyla has cancelled christmas

**Comment by LightFire53** [comment]
Free is scrooge.

**Comment by KasparoVy** [comment]
Didn't we used to have a garbagecan at the kitchen? Does this bring that back or is it gone 5ever?

**Comment by KingPhilipIII** [comment]
Glad to see we agree it’s a can, not a bin.

**Comment by Vivalas** [comment]
If possible please try to merge this after my 3 month old tiny map edit. #8075

**Comment by Spacemanspark** [comment]
Can we re-add the gift wrapping that was removed from cargo three years ago?

**Comment by alexkar598** [comment]
I think you can get it from the art vendor anyways and also thanks for that cam

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
