### PR TITLE
Adds Employment Record Laptop to HoP's Office

### PR DESCRIPTION
**Pull request by Twinmold93**
Adds in an employment record laptop to the Head of Personnel's office so they can now see people's previous employment records, making the records much more accessible to the Head of Personnel, whom should have easy access to these records. Removes the hand labeler and package wrap
from the Head of Personnel's office for the space. Hand labeler is already in the meeting room, and adds the wrap under the labeler in the meeting room.

:cl:Twinmold
Adds: Employment record laptop to Head of Personnel's Office. Moves package wrap that was there to meeting room to be paired with the hand labeler there.
/:cl:

### CODE REVIEW

**Comment by Markolie** [comment]
We should hold off on this until https://github.com/ParadiseSS13/Paradise/pull/6527 is done, then you can add the modular laptop there.

**Comment by KasparoVy** [comment]
@Markolie Would it be possible to have the laptop with the right modules serve as all 3 of thee computers?

**Comment by Twinmold93** [comment]
When it gets merged is not the most important thing: It's remembering - people would appreciate have access to employment records as HoP for obvious reasons.

**Comment by Markolie** [comment]
@KasparoVy: @davipatury would know for sure

**Comment by davipatury** [comment]
@KasparoVy Yes, it's possible, it's only necessary to create the missing modules. (camera module, security/medical/employment records)

**Comment by KasparoVy** [comment]
Thanks for the response, I was curious

**Comment by Twinmold93** [comment]
I'll be updating this to the new modular stuff now.

**Comment by Twinmold93** [comment]
So, it seems that modular computers don't actually have the programs yet to utterly remove computer3 yet...

**Comment by Twinmold93** [comment]
By the way... This isn't computer3... This is original computer code... Apparently. @Fox-McCloud

**Pull request merged**
