### PR TITLE
Fixes spelling error

### PR DESCRIPTION
**Pull request by Citinited**
RIP custom jon title

:cl:
fix: Spelling error in agent IDs
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
you can't just rscdel our boy Custom Jon like that :'(

**Comment by RyanSmake** [comment]
#SaveCustomJon2018 #CustomJonDidNothingWrong

**Comment by Citinited** [comment]
Customs was removed in 2015 though 🤔

**Comment by tigercat2000** [comment]
Fuck you jon!

**Comment by RyanSmake** [comment]
NO. YOU ARE ALL MONSTERS. MURDERERS!

**Comment by KasparoVy** [comment]
Unreal.

Greatest tragedy of 2018...

**Comment by alexkar598** [comment]
Lemme make a pr to re add custom Jon in the hop office

**Comment by Citinited** [comment]
```
That's Statue of Custom Jon.

A paragon of efficient customs practice, he stares accusingly at you,
as if you personally were responsible for termination of his contract.
```

**Pull request merged**
