### PR TITLE
Custom Items - The Flagbearer

### PR DESCRIPTION
**Pull request by TheFlagbearer**
Not entirely sure if I'm allowed to create a PR for my fluff items but someone suggested I should instead of waiting. Anyway, this PR adds my fluff items.

image

### CODE REVIEW

**Comment by TheFlagbearer** [comment]
Sorry if this is unprofessional but first time using Github. HELP WANTED with adding the .dmi files to the the pull request. Thanks.

**Comment by ZomgPonies** [comment]
Yes you can make a PR to add your fluff item content to the codebase -- However you'll still need DZD to make the database entries.

**Comment by fj45** [comment]
Going to need some screenshots of the sprites.

**Comment by TheFlagbearer** [comment]
Thanks for the advice. Basic screenshot added, I'll get different views up soon.

**Comment by TheFlagbearer** [comment]
Ah, all done. Ready to merge, according to my limited knowledge.

**Comment by Fox-McCloud** [comment]
approved by senior admins.

**Pull request merged**
