### PR TITLE
New power cells are empty.

### PR DESCRIPTION
**Pull request by TheDiode**
## What Does This PR Do
Made Protolathes, Exosuit Fabricators and Autolathes produce empty cells instead of fully charged ones.

## Why It's Good For The Game
It adds depth, if you print a cell, you need to charge it. Previously you could basically make power out of thin air. This makes chargers relevant for more than just guns.

## Changelog
:cl:
tweak: New power cells produced are now empty. Charge the cell or item.
/:cl:

### CODE REVIEW

**Comment by Inadvizable** [comment]
This prevents autolathes and fabricators being able to de facto make infinite power. Very good. But it would be pertinent to look at cell chargers, because, I will not mince words, they currently fucking suck.

**Comment by ItsMarmite** [comment]
I would have no issue this if a device existed to charge up multiple cells at once. As said above by Viz, cell chargers such.

This PR doesn't have those.

**Comment by Bm0n** [comment]
> I would have no issue this if a device existed to charge up multiple cells at once. As said above by Viz, cell chargers suck.
> 
> This PR doesn't have those.

can't you upgrade them with better parts? that's what I always do on TG

**Comment by TORE01** [comment]
> > I would have no issue this if a device existed to charge up multiple cells at once. As said above by Viz, cell chargers suck.
> > This PR doesn't have those.
> 
> can't you upgrade them with better parts? that's what I always do on TG

No, they dont have parts. There is no way to make these either.

**Comment by Bm0n** [comment]
> No, they dont have parts. There is no way to make these either.

oh my god you're right. they're not upgradable in paracode... what the fuck

we are actually living in the past

**Comment by Inadvizable** [comment]
> oh my god you're right. they're not upgradable in paracode... what the fuck
> 
> we are actually living in the past

Yeah. Our cell chargers are one of the most soulful things I know about. I think just doing away with them and making cells compatible with regular rechargers would be one way to do it. There's already a roundabout way with stun batons lol

**Comment by TORE01** [comment]
With the addition of upgradable cell chargers, I must say this is a very nice change. Printing power has always been a very weird feature and cell chargers has so far only been useful to medchem so they can swap cells when they are empty early in the game.

I don't have any position of power here but it's a yes from me. 🐵👍

**Comment by AffectedArc07** [comment]
Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.

Please link your account at [https://www.paradisestation.org/forum/custom/link_github_account.php](https://www.paradisestation.org/forum/custom/link_github_account.php)

*If you are seeing this multiple times due to multiple PRs you only have to link once*

**Comment by Leanfrog** [comment]
Frankly, I see this as needless tedium, it's likely handwaveable enough to say that the cells are charged in the process of construction, power is already basically infinite regardless of the fact that cells come out fully charged, between standard power sources producing massive quantities of power and yellow cores being quite literally infinite free power, auto/protolathes "creating" power from "nothing" doesn't seem particularly egregious, if this were to come as part of a larger power rework as a whole making it significantly more scarce I could see this fine, but as it is now it's an arbitrary extra step that really needn't exist.

**Comment by AffectedArc07** [comment]
No response from PR author in 7 days. Closing.

**Pull request closed without merging**
