### PR TITLE
Cryo Stations Galore

### PR DESCRIPTION
**Pull request by swordsith**
Will this even work, Hell if i know. lets see if i get 0 conflicts, I
doubt it. This add's four lil cryo sleep stations in the main
departments, Engineering, Medical, Science, and Security.
my first commit c;
of everything that is holy that was complicated to get this pull request crap to work, god save me.
I could care less if this get's merged it was more of a learning experience than anything else.

image

image

image

image

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Those are BIG. Also, where exactly is the engineering one located?

**Comment by swordsith** [comment]
> Those are BIG. Also, where exactly is the engineering one located?
>
The engineering one is located right above the engineering lobby:
image

**Comment by swordsith** [comment]
oh lor no conflicts

**Comment by Bram961** [comment]
I'd say these are to big, considering we are keeping the normal one only 1 or 2 pods should be necessary. as it stands you have enough for the entire engineering department to log out simultaneously.

Also you removed the testing area which gets used sometimes when atmos needs a small space..

**Comment by swordsith** [comment]
> I'd say these are to big, considering we are keeping the normal one only 1 or 2 pods should be necessary. as it stands you have enough for the entire engineering department to log out simultaneously.

Also you removed the testing area which gets used sometimes when atmos needs a small space..
>
:c I didn't know where i could stick it and have both atoms and engineering be able to use it.

**Comment by Bram961** [comment]
That last bit was a 50% a joke, the assembly line is there as well, Anyhow https://cloud.githubusercontent.com/assets/24737477/21743632/2fc248fc-d4d4-11e6-9120-0a2feeb3897e.PNG This is the only one I like although it as well could be 1 tile shorter.

**Comment by SamHPurp** [comment]
This then increases the number of locations that cannot be bombed, for very little gain.

**Comment by swordsith** [comment]
image
This any better @Bram961? I put it in the assembly line.

**Comment by swordsith** [comment]
image
security one also made smaller

**Comment by swordsith** [comment]
image
science one made smaller

**Comment by Fox-McCloud** [comment]
This is ugly and very "tacked on everywhere". We do need more cryopods, but placing them in every single department haphazardly isn't the way to go about this, least of all in a sloppy manner.

**Comment by swordsith** [comment]
Ignore the
"Merge remote-tracking branch 'refs/remotes/ParadiseSS13/master'" under the commits i have literally no idea how to remove that.

**Comment by KasparoVy** [comment]
Good job getting all this done for your first time, I'm glad to see you've gained a good bit of experience here. Though unfortunately I can't really support this for the reasons Fox brought up. One single cryodorm is all we need (which is what we've got) although yes we do get times where there's people waiting for a pod, it's only during extremely high-pop.

I feel a better way to solve this problem would be to add a second floor of the cryodorms.

**Comment by TullyBurnalot** [comment]
Alternatively, we could just extend the current cryodorms into that little tunnel to the left and add a second row of cryopods.

**Comment by Lady-Luck** [comment]
good fucking god no this is a horrible idea that sets horrible map editing precedents.

**Comment by Spacemanspark** [comment]
Don't need to have such a negative response about it @Lady-Luck. I'm sure a simple "I don't like this because X" would do.
I do like the idea of this PR, though it does look a bit big.

**Comment by Lady-Luck** [comment]
yeah yeah sorry I just dislike it a LOT!!!!

**Comment by Aurorablade** [comment]
i don't like per department cryopods. We have a cryodorm just expand it.

**Comment by Fox-McCloud** [comment]
>i don't like per department cryopods. We have a cryodorm just expand it.

Very much this; I know I added more cryopods in before the freeze, but in allll the map edits (sec map edits, etc), somehow they got overwritten...ooopsss

**Comment by swordsith** [comment]
@TullyBurnalot the only issue with that the cryo dorms even expanded would have issues unless you could manage to flip the cryo pod's around 180 degrees, otherwise it literally wouldn't be possible to get bit a large enough area for more facing west: 
image

**Comment by Fox-McCloud** [comment]
the cryo feeds are completely optional; it's a waste of space to include them; they're 100% aesthetic.

**Comment by swordsith** [comment]
>The cryo feeds are completely optional; it's a waste of space to include them; they're 100% aesthetic.
>
hmm didn't know i assumed they had some reason, but even still the pods would still be facing the wall, is there anyway to flip them without doing some crazy magic spiting stuff?

**Comment by Fox-McCloud** [comment]
an alternative: https://github.com/ParadiseSS13/Paradise/pull/6111

**Comment by swordsith** [comment]
>To answer your question; there's is a subtype of the cryopods that faces the opposite direction; there's even opposite direction cryofeeds, too.
>
really?
these sprites need to be organized. everything is hidden

**Comment by Fox-McCloud** [comment]
It's not really hidden; you have to look at the object itself; it's an explicit subtype of the cryopods

`crypod/right` is the subtype.

**Comment by swordsith** [comment]
welp this got solved in fox's PR~#6111

**Pull request closed without merging**
