### PR TITLE
Fluff Item

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
Adds fluff item I donated for. Approved by `PurpleGenie`

**Images of sprite changes:**
vnrysie6cq

**Changelog:**
:cl: AffectedArc07
add: Fluff item
/:cl:

*making this PR feels so wrong for some reason*

### CODE REVIEW

**Comment by TDSSS** [comment]
>_making this PR feels so wrong for some reason_
Feels like something only a nerd would do.

**Comment by FalseIncarnate** [comment]
Shouldn’t be an issue, but please include who approved this for record-keeping purposes.

**Comment by AffectedArc07** [comment]
@FalseIncarnate done

**Comment by Agameofscones** [comment]
Nice palette swap coderman

**Pull request merged**
