### PR TITLE
Delete nations.dm

### PR DESCRIPTION
**Pull request by gt33**
This should've happened a LONG time ago

### CODE REVIEW

**Comment by ZomgPonies** [comment]
HONK, no.

**Comment by Jovaniph** [comment]
speed merge. This would significantly increase game performance...its true, it totally will.

**Comment by Spacemanspark** [comment]
Uhhhhh no.

**Comment by tigercat2000** [comment]
The real sin here is using the github web editor and opening the PR before you're even done hitting "delete file"

**Comment by Jovaniph** [comment]
Don't forget about the paradise.dme #include stuff

**Comment by FlattestGuitar** [comment]
bby pls

**Comment by ZomgPonies** [comment]
This is a rage/vengeance PR made by a salty player because he got killed early in a Nations round through his own actions, and was then ignored by admins after salting at them for a bit. This isn't legitimate in any way, shape or form and this player's actions should NOT be legitimized by the maintainers.

Seriously, get a grip guys.

**Comment by gt33** [comment]
@ZomgPonies ick oock

**Comment by gt33** [comment]
I got banned for calling out @ZomgPonies's ick oock?

**Comment by ZomgPonies** [comment]
No, you got banned for ignoring Spark's warning. Take it to the forums, Github isn't the place for it.

**Comment by Psyentific** [comment]
this is some pretty great salt not gonna lie 👌👌👌

**Comment by IlyaIU** [comment]
Repoban this fucker he done nothing but shitting into major codebases

**Comment by AffectedArc07** [comment]
Nations can fuck itself

**Comment by taukausanake** [comment]
But then how do we have quality meme rounds? _Adminbus_?

**Pull request closed without merging**
