### PR TITLE
But the very next day.. (Snow / gift tweaks fixes)

### PR DESCRIPTION
**Pull request by FreeStylaLT**
**What does this PR do:**
Tweaks the snow on Cyberiad:
- It's now an instance of plasteel with a changed sprite rather than a subtype of plating
- It can now be crowbarred and removed (turns into regular plasteel tiles)
- Toned down the amount of gifts in each department (because each gift on the map spawns several)
- Fixes gifts appearing inside the windows in Brig
- Adds snow in Chang's.

**Changelog:**
:cl: FreeStylaLT
tweak: Snow / gift tweaks
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I'd rather snow be treated like dirt piles but with tile smoothing. Then you can dig up the snow and still have a floor under it rather than crowbarring the snow and getting a floor

**Comment by Citinited** [comment]
Either that or make it a subtype of `obj/effect/snow` that removes itself from processing upon spawning, and adds a border to itself

**Comment by Aurorablade** [comment]
I hate you so much for useing that song for PR titles.

**Comment by Aurorablade** [comment]
"Adds snow in changs"....
...Hey...hey free..Remeber the thing free..
hey..

**Comment by KasparoVy** [comment]
THIS YEeeeAR, TO SAVE ME FROM TEARS

I gave it to someone spe-shullll

**Pull request closed without merging**
