### PR TITLE
Ports on fire sprites from TCC/TG

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Ports new on fire animations from TCC PR https://github.com/TauCetiStation/TauCetiClassic/pull/9238 - but not really. I used the animations from TGs version of this PR https://github.com/tgstation/tgstation/pull/66746 due to TCC doing some weird layering stuff. This means that the fire overlay covers your face a bit more like on TG... however I didn't port the small or monkey on-fire animation states from TG that TCC isn't using. It's half TCC half TG.

## Why It's Good For The Game
TCC tends to look pretty good. I mean just look at the colours used in the new one compared to the old version.

## Images of changes
From TGs PR so the lighting might be a little different but it looks the same.

https://user-images.githubusercontent.com/92271472/178127045-d617e149-fad4-4b14-92c7-2f59b517b57f.mp4

Used on humans
68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836313436322f31383331312f343535323633353238353238333539333138392e676966

Used on borgs/aliens
68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836313436322f31383331312f383134393934343634393037343035353832382e676966

Old
PR1

New
PR2

## Changelog
:cl: Bmon, DarthSidiousPalpatine, Gandalf2k15
imageadd: New on-fire animation states from TCC/TG!
/:cl:

### CODE REVIEW

**Comment by roarbark** [comment]
doesnt tg have multiple animations depending on how many firestacks you have? 
i always liked the idea of that because it doesnt give you the full body immolation sprite for a single firestack.

**Comment by Bm0n** [comment]
> doesnt tg have multiple animations depending on how many firestacks you have? i always liked the idea of that because it doesnt give you the full body immolation sprite for a single firestack.

Yes and that's why I said this is a half port. TCC gives the full body on fire sprite right away while TG does as you described.

**Comment by AffectedArc07** [comment]
Its no doubt a wonderful sprite, but the amount of animation frames and intricate detail looks kinda out of place here.

I dont have a major eye for sprites though so ill leave this to someone else.

**Comment by Bm0n** [comment]
> Its no doubt a wonderful sprite, but the amount of animation frames and intricate detail looks kinda out of place here.
> 
> I dont have a major eye for sprites though so ill leave this to someone else.

I don't see why this is a problem when we porting TCC's welding animation which has even more frames than this.

**Comment by Bm0n** [comment]
> Guessing for tail races there is no fire effect on the tail itself?

Naturally. The old one didn't have sprites for tails either.

It still looks okay though. In TCCs PR which I linked you can see what a vox looks like on fire.

**Pull request merged**
