### PR TITLE
Adds electrical grid check to random events.

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Well, more like re-adds it.
:cl: FreeStylaLT
add: Added grid check into random events.
/:cl:

### CODE REVIEW

**Comment by Earthdivine** [comment]
For context, this event was removed when we removed the 4th SMES from engineering, causing the Singlo to always escape it's containment when this was up. Said SMES is back and containment has never been dropped in all the time's I've forced this event.

**Comment by Fox-McCloud** [comment]
I mean. It's not the worst thing, but it's not particularly fun to put up with either.

**Comment by FreeStylaLT** [comment]
It DOES provide some lovely opportunities for antags to engage in whatever schemes they want, given luck. Plus, doesn't even lag as much as it used to with the lighting.

**Comment by Fox-McCloud** [comment]
Well, the larger issue I have with it is ...essentially, it's "sit on your hands for 5-10 minutes" . Can't clone someone, can't use a slepeer, can't dispense medicine, can't make food, etc.

**Comment by Earthdivine** [comment]
Not much different then the Rad Storm event too in that regard.

Particullarly dont mind if it doesnt get readded, just glad it has a chance to

**Comment by Regen1** [comment]
@Fox-McCloud wrong way to think about it

It's also 5-10 minutes where traitors can make their move, crowbar open doors etc

**Comment by Taaketa** [comment]
I like this being back in. It's annoying and so it should be.

I will note that if an engineer hot wires the engine because of a power sink and this event triggers at the same time. That could be bad times.

**Comment by Aurorablade** [comment]
we need a honk check event..where air horns play alot..

**Comment by Belario** [comment]
:+1: for emag'less B&E.
I remember it being lag inducing though, never any crashes but how is it on performance?

**Comment by CrAzYPiLoT-SS13** [comment]
Just PACMANs :+1:

**Comment by FreeStylaLT** [comment]
@Belario Doesn't lag at all anymore from what I've seen.

**Comment by Davdichan** [comment]
Miss this event. Added some paranoia, a forced breather and helps encourage various deparments to plan ahead (crowbars, flashlights) and not rely entirely on power consuming objects(chemist should keep somepatches outside the smartfridge. Maybe make a way to retrieve objects from depowered fridges.)

**Pull request merged**
