### PR TITLE
сделатйте пожалуйтсо

### PR DESCRIPTION
**Pull request by pblp**
чтобы короче корованы грабить можно было

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
what in the world. I think you made a mistake.

**Comment by monster860** [comment]
Russian shitcode. Oh god

**Comment by Injazz** [comment]
oh shit im sorry

**Comment by Fox-McCloud** [comment]
Don't worry about it. It happens and has happened before.

**Comment by ITBlackwood** [comment]
Yeah, sorry, this happens.

**Pull request closed without merging**
