### PR TITLE
Fix unrespawnable swap victims

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Attemped to fix the bug where victims of changeling and wizard mind swaps will be forced unrespawnable

Can't fix it

### CODE REVIEW

**Comment by Markolie** [comment]
Will this still force them to become a ghost though? If not, this only fixes half of the bug as they still shouldn't be forced out of the wizard's previous body.

**Comment by Anticept** [comment]
They aren't forced out of the wizard's body. They never go into the wizard's body in the first place.

**Comment by Fox-McCloud** [comment]
Did you test this out, just to be sure?

**Comment by uraniummeltdown** [comment]
not yet, will when i get time later today

**Pull request closed without merging**
