### PR TITLE
Splits traitor items and nuclear agent items into seperate files

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

Splits up traitor and nuclear agent items into their own files for readability. It will hopefully help prevent stuff like #20619

## Why It's Good For The Game
Code quality
image

## Testing

Compiled, Took a quick peek through both nukies and traitor uplinks and made sure that restricted items were still there.

## Changelog
Nothing player facing

### CODE REVIEW

**Comment by hal9000PR** [comment]
I am also in favour but I might need to bribe @S34NW to review this 
image

**Comment by S34NW** [comment]
Oh lord have mercy I don't wanna review this

**Review by farie82 — APPROVED** [review]
Looks fine as far as I can tell. Thanks for the PR. Can be merged once it's deconflicted

**Comment by Contrabang** [comment]
Deconflicted, files are now up to date with
https://github.com/ParadiseSS13/Paradise/commits/master/code/datums/uplink_item.dm

**Pull request merged**
