### PR TITLE
Resprite Disco floors

### PR DESCRIPTION
**Pull request by AyIong**
## What Does This PR Do
Does the same thing it says in the title.

## Why It's Good For The Game
Less codersprites
More mappersprites

## Images of changes

https://github.com/user-attachments/assets/6216d4a3-5862-4a5a-94a3-e6d1c95f7904

## Testing
Nuh uh

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imageadd: Disco floors got new sprites 
/:cl:

### CODE REVIEW

**Review by Contrabang — APPROVED** [review]
uhhh code is fine

**Comment by AyIong** [comment]
> uhhh code is fine

Sorry :c

**Comment by Coolrune206** [comment]
Does this also change light tiles?

**Comment by AyIong** [comment]
> Does this also change light tiles?

Sure

**Review by DGamerL — APPROVED** [review]
Just needs a design vote

**Pull request merged**
