### PR TITLE
Spider nerfs

### PR DESCRIPTION
**Pull request by Robertha89**
Makes spiders less robust, weaker, and less likely to be a round ending event.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Either nerf their damage OR their health. Right now you've just made them 4x weaker than before. That's too weak.

**Comment by TheDZD** [comment]
The spider event is definitely very round-ending at the moment, despite only being a "moderate" level event. I'd honestly prefer that the event itself be made rarer/nerfed though, as this makes spiders weaker everywhere else that they're used as well (just changelings I think).

**Comment by ZomgPonies** [comment]
There, this PR is a more than 50% nerf to the deadliness of spiders. This is worth testing before going mental and nerfing EVERY aspect of spiders as discussed in staff chat.

**Comment by Fox-McCloud** [comment]
Going to concur with DZD on this one; I feel it would be better to nerf the event, itself, rather than spiders, in general--especially because spiders are used elsewhere.

**Comment by KasparoVy** [comment]
Spiders are pretty wicked, but rightly so. Now they're actually a threat people take seriously

Fox summed it up saying 'nerf the event', that'd probably work out alot better

**Comment by ZomgPonies** [comment]
Yeah the event balance PR is a better solution to this, due to fact spiders are used for other things than the event.

**Pull request closed without merging**
