### PR TITLE
Ports the megafauna boss sprites from TG station

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Ports https://github.com/tgstation/tgstation/pull/74299 's megafauna sprites, as those seemed to be the least controversial in general.

## Why It's Good For The Game

Cool sprites are cool. And now has directional sprites on colossus! Legion not ported as we don't have the splitting mechanic, was not part of that pr, and personally just looks silly to me.

## Images of changes

image

also look at checks megafauna don't like to stay still

## Testing

Confirmed things looked as intended.

## Changelog
:cl: Qwertytoforty, Mey-Ha-Zah
add: Ported new megafauna sprites from TG
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
Why not the sprites for tumor bosses? our current look pretty bad

**Comment by Qwertytoforty** [comment]
> Why not the sprites for tumor bosses? our current look pretty bad

Elites were liked, though the take on colours of goliaths were a bit more contriversal when asked around, which would make the broodmother stand out from the rest of the goliaths greatly combined with the baby goliaths. As such, not included in this pr, though elites could be done in a second pr.

**Comment by pismorizzo** [comment]
Love the bubblegum and hiero sprites but as someone said in the current tg pr the ash drake looks like a sprite from a different game. Is this like a fully packaged deal? The new ashdrake being that dramatically smaller and different looking from the original is jaring in style points.

**Comment by Henri215** [comment]
What i dont like the most about the current ash drake is the left/right view arms, makes it look a bit goofy. The new sprite does solve this for me.

**Review by Sirryan2002 — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
