### PR TITLE
Custom Item Addition: Pink Guitar

### PR DESCRIPTION
**Pull request by LiquidNightfury**
At Necaladun's request, added unique item and required sprites.
In addition, adjusted the guitar inhand sprite (left hand, facing north) one pixel to the left, to properly align with player sprites like the reverse.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Did you..submit this via the editor?

**Comment by monster860** [comment]
...... Gah!! Github editor!

**Comment by LiquidNightfury** [comment]
Kind of my first time with Git. Was there some other way to do it?

**Comment by Fox-McCloud** [comment]
@LiquidNightfury 

I'll handle this one.

**Pull request closed without merging**
