### PR TITLE
WIP -Adjustments to current sprites in space for solars, lattices and catwalks

### PR DESCRIPTION
**Pull request by DogsParadise**
These sprites are subject to change, removing errors etc.
Pictures will be updated.

## What Does This PR Do
This PR is focused around re-spriting the area around the solars and such.
Those sprites feel outdated, shading and perspective wise they are all over the place.

it's WIP

Including:
-Lattices
-Solars
-Solar bottoms
-Cat walks

## Why It's Good For The Game
Since we are moving to better quality sprites, this was next on my to-do list.
Current sprites feel outdated and shading makes no sense.

## Images of changes
Full picture solars:
image

lattices:
image

## Changelog
:cl:
tweak: Changes solar/lattice/solar bottom/catwalk sprites
wip: still wip sprites

/:cl:

The catwalk is the torment of humankind.
The bugs and issues in the catwalk are caused by the current way overlays work.
Not something I can fix easily.

So i might in the end leave the catwalks out and just update the outer ring on current ones and possibly move it into perspective, we will see.

### CODE REVIEW

**Comment by SteelSlayer** [comment]
I don't particularly like the two different styles of metal grille on the east/west catwalk sprite, or the circle in the middle of 4-way junctions. Solars the lattices are good though.

**Comment by McRamon** [comment]
Well solar panel melta part still blends in with solar panel base metal part, and i don't like the catwalk

**Comment by DogsParadise** [comment]
> d i do

It's on my to do list

**Comment by DogsParadise** [comment]
> Well solar panel metal part still blends in with solar panel base metal part, and i don't like the catwalk

It's on my to-do list

**Comment by procdrone** [comment]
Not a fan of this catwalk, way to irregular spacing.

**Comment by MRgaty** [comment]
Tbh I particularly liked the darker ones more than the ones we have currently, the lattice looks good tho.

**Comment by DogsParadise** [comment]
I axed myself a question, if i liked the catwalks enough.

And I don't. But I do like lettuce.
So lettuce is now seperate PR.
Solars need some fixing, might pr that later.

**Pull request closed without merging**
