### PR TITLE
Body Accessory system

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit adds a new system to character setup: Custom, selectable ~~tails.~~ body accessories. This means that anyone can select a ~~tail~~ body accessory if it is available to their race, and it will properly show up. Important note: If no ~~tail~~ body accessory is selected, the species default ~~tail~~ body accessory will be used.

## Oh. Right. Going to point out this needs an SQL update if it's merged.

> ## OUTDATED INFO:
There are currently only testing-tails, so DNM until sprites.
Included tails as of now:
 - Tajaran tail for all mobs
 - Restricted Tajaran tail for tajarans
 - Body class, Snake body

>Pictures
i'm pure evil, aren't I?

>Updated:
All species with tails now use a tail datum. The testing tails for humans have been removed, and normal players will see an empty menu.

>Other things:
 - Added more creepy-body sprites
  - @Earthdivine @ZomgPonies Made them admin-only; Only admins with R_ADMIN will be able to select them. 
 - Species now use the tail datum system as well.
 - Removed tail_wagging flag, because it shouldn't really matter if the species supports it; the important part is if the tail has an animated state.
 

>Picture:
oh god

Well the maintainers are boring. So this is now just a tail datum system. No fancy bodies or anything.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Ok, first things first....

(1) Absolutely no snake people or other such things; this PR should be limited to tails *only*
(2) Tails should be restricted to their respective mobs and that's it; absolutely no cross-species with non-species tails or out of species tails/etc.
(3) All current species with tails (Vulpkanin/Unathi/Tajarans) should utilize this system for future customization if so desired.

**Comment by tigercat2000** [comment]
@Fox-McCloud Alrighty, will fix as soon as I wake up.

**Comment by Earthdivine** [comment]
I was honestly like the snake tails kept in as admin stuff for now, sounds like a fun thing for us to mess with.

**Comment by ZomgPonies** [comment]
I like the idea of weird, admin-event tails like the snake tail that could be linked to special/custom bodyparts/external organs, but that should probably go in a separate PR.

**Comment by TheDZD** [comment]
The sprites for the snake, horse, and spider body parts look pretty bad. Also, oh god these are vorestation sprites.

my eyes

**Comment by Spacemanspark** [comment]
Uhhhh what.

**Comment by FreeStylaLT** [comment]
yes please

I want my lamia booty

**Comment by Aurorablade** [comment]
adminbus or viruses....CAN I MAKE THEM VIRUSES?!

**Comment by Fox-McCloud** [comment]
Save the "body sprites" for a separate PR. Most look like absolute trash; again, this should be a tail only PR if you want to get this merged.

**Comment by tigercat2000** [comment]
@Fox-McCloud I don't see why you would want this to be a tail only PR. Isn't the entire point customization? The system has been designed from the ground up to work with literally any icon you define, and now the body sprites are for adminabuse as @Earthdivine, @FreeStylaLT, and @ZomgPonies expressed interest in.

**Comment by Fox-McCloud** [comment]
Yes, and he expressly stated that it should be a separate PR, as well and didn't see how gosh damn awful those sprites are.

We're not vorestation and THAT kind of customization isn't something we should be utilizing here on Paradise.

**Comment by tigercat2000** [comment]
@Fox-McCloud I don't see a single bit of difference between letting all the tailed-races have custom tail sprites and letting admins have abuse sprites for creepy events.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Save it for another PR--likewise, it should be on a whole separate layer from tail, otherwise its going conflict with tail wagging and also cut short use of non-awful body customized sprites.

*IF* this is going to be a "thing" it should:

- (1) Be in a separate PR where it can be debated separately
- (2) Not be on the same layer as tails

**Comment by tigercat2000** [comment]
Requesting @TheDZD's input, might as well get all the maintainers.

And @Fox-McCloud, I see your point.

**Comment by TheDZD** [comment]
:+1: to the modular tail system.
:-1: to the weird animal bodies, partly because they look weird being glued on to a species, and partly because the sprites are low quality.

**Comment by KasparoVy** [comment]
Woah woah what the deuce

IDK what to say this is pretty cool bruh. Sounds like the tail bit and the possible customization associated with it in future implementation would be absolutely bomb

**Comment by Aurorablade** [comment]
Tarajan/Vulpakanin/Unathi/Vox Tail jewelery? EH EH?!

**Comment by KasparoVy** [comment]
"Tarajan/Vulpakanin/Unathi/Vox Tail jewelery? EH EH?!"
Yeah, that's what I'm thinking

**Comment by Fox-McCloud** [comment]
Just a few more suggestions:

- rename it from body accessory to tail (in the character creation anyway)
- move all tail related sprites to a singular.dmi please. Hair accessories follow this pattern; so should tails.
- is the commented out code for "if no tail is found, do this" necessary anymore?

**Comment by tigercat2000** [comment]
I'm closing this. I don't really want to continue any work on it, and there are more reasons that I just don't really want to elaborate on.

**Comment by KasparoVy** [comment]
Quite a few people'd love to have atleast the tail bit/framework in for customization at the very least. Is it worth axing the whole thing just because one part was disagreed with?

**Comment by tigercat2000** [comment]
@KasparoVy It wasn't closed for just that reason.

**Comment by KasparoVy** [comment]
Either way, I'm going to miss this PR :(
Quite sorry it didn't work out

**Pull request closed without merging**
