### PR TITLE
Gamma borgs are now reset when security level is dropped below Gamma

### PR DESCRIPTION
**Pull request by Markolie**
**What does this PR do:**
If the security levels drops below Gamma, all Gamma borgs (with the combat module) will now be reset. Epsilon and Delta are both higher level than Gamma, and as such will not reset Gamma borgs. Borgs with their crisis mode manually enabled will not be reset.

Gamma borgs are incredibly powerful. When the threat to the station is contained, they no longer have a need for their combat module. 

**Changelog:**
:cl: Markolie
balance: When the alert level drops below Gamma, Gamma borgs will now be reset.
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Can't any antag just steal a command level ID and manually lower the alert level at a console now? Or can you not lower from gamma that way? I've never tried lowering gamma as command, tbh.

**Comment by Taaketa** [comment]
Command can indeed lower from Gamma. I do not have a problem with that. It introduces a new tactic for antags and this provides a new element of emerging gameplay we might see.

**Comment by Markolie** [comment]
That is indeed possible, yes. However, Gamma is fairly exclusively called for blobs, terror spiders and xenomorphs who do not have that option. Keep in mind that this requires a captain-level ID card, however.

If a human antag had Gamma called against it somehow and they have captain-level access and access to a communications console, there's a good chance they'll also be able to subvert or blow the borgs anyway.

**Comment by Couls** [comment]
holy crap speedmerge this please

**Comment by Ty-Omaha** [comment]
Gamma should probably require keycard authentication to lower from

**Comment by Ty-Omaha** [comment]
>Or, logically, CC authorization: they were the ones who authorized it to be activated, why would they not be involved in deactivation?

Going down to code green or red doesn't unlock any special expensive gear for the station

**Pull request merged**
