### PR TITLE
Stock parts resprite

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Resprites stock parts, cleans up dmi from unused old sprites

## Why It's Good For The Game
i like cucumber sprite

## Images of changes
image

## Testing
pshhh

## Changelog
:cl:
imageadd: New sprites for stock parts
/:cl:

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]
Looks Honkable to me

**Comment by 1080pCat** [comment]
> ## Testing
> 
> pshhh

firefox_6z4yTZpULp

**Comment by Henri215** [comment]
> > ## Testing
> > pshhh
> 
> firefox_6z4yTZpULp [ firefox_6z4yTZpULp ](https://private-user-images.githubusercontent.com/96908085/327949696-fbf42cfd-a9df-45f0-925d-cf6b6cc5f019.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjgzODAsIm5iZiI6MTcxNDgyODA4MCwicGF0aCI6Ii85NjkwODA4NS8zMjc5NDk2OTYtZmJmNDJjZmQtYTlkZi00NWYwLTkyNWQtY2Y2YjZjYzVmMDE5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEzMDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMGQ3OWNlNWJjZDIxYWNhMzA5MjNmZjVmZDQ3MDEwODFjMzE4MWMwMTFiYWFhNDAxNjJiODY0N2ZmNGIyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xIFYyv7SkFdUHqa1F6gdYx4tLLZ8CEussU3LvNZpf6o) [ ](https://private-user-images.githubusercontent.com/96908085/327949696-fbf42cfd-a9df-45f0-925d-cf6b6cc5f019.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjgzODAsIm5iZiI6MTcxNDgyODA4MCwicGF0aCI6Ii85NjkwODA4NS8zMjc5NDk2OTYtZmJmNDJjZmQtYTlkZi00NWYwLTkyNWQtY2Y2YjZjYzVmMDE5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEzMDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMGQ3OWNlNWJjZDIxYWNhMzA5MjNmZjVmZDQ3MDEwODFjMzE4MWMwMTFiYWFhNDAxNjJiODY0N2ZmNGIyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xIFYyv7SkFdUHqa1F6gdYx4tLLZ8CEussU3LvNZpf6o)

Yep, icondiffbot and animated sprites, happens.

**Comment by McRamon** [comment]
> > ## Testing
> > pshhh
> 
> firefox_6z4yTZpULp [ firefox_6z4yTZpULp ](https://private-user-images.githubusercontent.com/96908085/327949696-fbf42cfd-a9df-45f0-925d-cf6b6cc5f019.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjgyMDgsIm5iZiI6MTcxNDgyNzkwOCwicGF0aCI6Ii85NjkwODA4NS8zMjc5NDk2OTYtZmJmNDJjZmQtYTlkZi00NWYwLTkyNWQtY2Y2YjZjYzVmMDE5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEzMDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDhjM2QyZTMxMWEyYjI0OWIzMmFlZjU4YzY4MTJlMWJlZWRjYWJjMTI5YjYyNDU0YjdjNDdkYmJkODk0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IQbV-C02Cfw2WxmENViHo7Qocapkh0IUh_rxbW0keo) [ ](https://private-user-images.githubusercontent.com/96908085/327949696-fbf42cfd-a9df-45f0-925d-cf6b6cc5f019.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjgyMDgsIm5iZiI6MTcxNDgyNzkwOCwicGF0aCI6Ii85NjkwODA4NS8zMjc5NDk2OTYtZmJmNDJjZmQtYTlkZi00NWYwLTkyNWQtY2Y2YjZjYzVmMDE5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDEzMDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDhjM2QyZTMxMWEyYjI0OWIzMmFlZjU4YzY4MTJlMWJlZWRjYWJjMTI5YjYyNDU0YjdjNDdkYmJkODk0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IQbV-C02Cfw2WxmENViHo7Qocapkh0IUh_rxbW0keo)

When i tested it in game all was fine, its icondifbot going insane.

**Review by 1080pCat — APPROVED** [review]
icon dif moment. sprites look good

**Review by Burzah — APPROVED** [review]

**Pull request merged**
