### PR TITLE
Fix 18746, Dedups cable coil description

### PR DESCRIPTION
**Pull request by Sinestia**
## What Does This PR Do
Removes the duplicate description from the line that describes the amount of cables in the coil

* https://github.com/ParadiseSS13/Paradise/issues/18746
## Why It's Good For The Game
Redundant info is bad

## Images of changes
I wanted the meme of posting this 3 minutes after the issue so I'll post a pic in a sec
image

## Testing
Not particularly relevant due to simplicity

## Changelog
:cl:Froststahr
fix: A duplicate description on cable coils has been removed
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
We could probably remove that whole section in total? It already says before the Alt-click part how many pieces of cable are in it.
image

**Comment by Sinestia** [comment]
> We could probably remove that whole section in total? It already says before the Alt-click part how many pieces of cable are in it. image

It may be better to yeet the OG desc itself since this is a dynamic field for what it is, since it's not always a coil if there's just one

**Comment by Sinestia** [comment]
image
This is how it is now with the desc erased and the old bit restored, with the amount cut from that string. 

As said before yeah, it inherits that bit from obj/stack

**Review by Sirryan2002 — APPROVED** [review]
Code is fine. There's not really a great alternative to this besides removal or refactoring of stack examination procs.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
