### PR TITLE
The Most Important Refactor Ever

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Quite possibly, the most important refactor to ever grace Paradise.

Cuts down on snowflake code: ✔️ 
More Object Oriented: ✔️ 
Allows for Expansion of future features: ✔️
Potentially usable for a future needs system: ✔️ 
Makes you question your own existence: ✔️ 

This PR is a total gas, and it would be shame if it would fall flat on its face when such a refactor has the potential to be a total blowout.

Biblefart gibbing is now a form of suicide; should cut down on admin annoyance and properly set the `suiciding` var to `TRUE`

@KasparoVy @FreeStylaLT 

:cl: Fox McCloud
tweak: Refactors the very core and soul of SS13 and enhances the code that powers it
tweak: Bible fartgibbing is now a form of suicide
/:cl:

### CODE REVIEW

**Comment by Drobe50** [comment]
_Oh no_

**Comment by Ty-Omaha** [comment]
✔️

**Comment by KasparoVy** [comment]
Literally the core mechanic of the game since it's inception, this PR's existence does all spacemen a great justice

**Comment by Mocha-Not-Latte** [comment]
✔️

**Comment by Lunaimon** [comment]
😕

**Comment by pinatacolada** [comment]
Cant wait to see what else i can fart on in the future

**Comment by AffectedArc07** [comment]
Inb4 the people scream about LRP

**Comment by AzuleUtama** [comment]
_Presses F on keyboard_

**Comment by taukausanake** [comment]
It's a fart refactor. Like when ghost spooking was refactored. Neat

**Comment by MRgaty** [comment]
✔️

**Pull request merged**
