### PR TITLE
Gives the NTV Arion a fresh coat of paint [Cargo Shuttle Remap]

### PR DESCRIPTION
**Pull request by ItsMarmite**
## What Does This PR Do
Changes the aesthetic of the Cargo Shuttle through a remap.

## Why It's Good For The Game
De-souls the shuttle slightly, gives it a fresh coat of paint and more importantly gives it a much more seedy industrial look as befitting cargo.

## Images of changes
image
image

## Testing
See screenshots.

## Changelog
:cl:
tweak: Remaps the cargo shuttle.
/:cl:

### CODE REVIEW

**Comment by Christasmurf** [comment]
image
Where these decals layer onto the wall at the bottom looks a bit odd

**Comment by ItsMarmite** [comment]
> image Where these decals layer onto the wall at the bottom looks a bit odd

Any suggestions?

**Comment by Christasmurf** [comment]
> > image Where these decals layer onto the wall at the bottom looks a bit odd
> 
> Any suggestions?

I guess just remove the decals from those specific tiles? It won't clip onto the wall and the grating kinda already does a thin hazard line so it shouldn't look too bad I don't think

**Comment by S34NW** [comment]
We do historically tend to reserve plastitanium for syndies (exceptions apply), but I'm okay with the pivot here

**Comment by Sirryan2002** [comment]
@ParadiseSS13/commit-access can someone re-run the MapDiffBot Test here?

**Comment by SteelSlayer** [comment]
MDB is not able to be reran. I suggest pushing an "update from master" commit.

**Comment by McRamon** [comment]
Yeah i feel like npt exacly plastitanium for syndies but more of a titanium for civillian crafts plastitanium for combat (ert shuttle, nukie ahuttle)
And cargo shuttle is definitely not a combat one

**Review by Sirryan2002 — APPROVED** [review]

**Review by Burzah — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
