### PR TITLE
New Whetstone Sprite

### PR DESCRIPTION
**Pull request by uraniummeltdown**
https://github.com/tgstation/tgstation/pull/22835
New whetstone sprite from TG
TG Whetstone
:cl:
add: Whetstones have been resprited
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
New one looks better. Yes.

**Comment by taukausanake** [comment]
Am I the only one worried that we are turning into /tg/ little by little? I mean I agree that the icons are nice, but are they Paradise?

**Comment by Spacemanspark** [comment]
I've been asking that for years.
Welcome to the club, here's your tin foil hat.

**Comment by uraniummeltdown** [comment]
Feel free to make a better whetstone sprite that's Paradise

**Comment by jughu** [comment]
This has more depth then my mechs

**Comment by Iamgoofball** [comment]
@taukausanake
@Spacemanspark

Fuck off, you retarded shits. You're the reason we haven't improved anything.

**Comment by Spacemanspark** [comment]
Nah, I'm good man.

**Pull request merged**
