### PR TITLE
Adds a wider variety of swear words to tourettes syndrome

### PR DESCRIPTION
**Pull request by Landerlow**
🆑 
Tweak: Added more swearwords to tourettes syndrome
/ 🆑

### CODE REVIEW

**Comment by alexkar598** [comment]
I think il use malpracticebay in game

**Comment by Fox-McCloud** [comment]
"shitcurity", "malpracticebay", and "comdom" are edging it, in my opinion---those I'd more closely associate with braindamage lines than tourettes.

**Comment by SamHPurp** [comment]
Agree with Fox. I'd also add that `retarded` is a bit retarded. I wouldn't include that one personally.

**Comment by Vivalas** [comment]
The change the server needs.

**Comment by VWetzels** [comment]
Feel free to add/remove certain swear words. I cannot do this at the moment since I am not at home until september 16th - 20th

**Comment by Crazylemon64** [comment]
I second fox's stance - those words seem more appropriate for brain damage rather than tourettes

**Pull request closed without merging**
