### PR TITLE
Stab your eyes out with style

### PR DESCRIPTION
**Pull request by FlattestGuitar**
## What Does This PR Do
Second attempt at making eyeblur blurry.

I pushed some extra stuff so new desc.

The PR also has the plane master controllers from https://github.com/tgstation/tgstation/pull/56717. Thanks, @AMonkeyThatCodes.

One thing I skipped was making all `/obj/screen` items `/atom/movable/screen`. I ran into a lot of issues and didn't feel like working through it all. I could've missed other PRs. I don't keep up with tg.

## Why It's Good For The Game
It looks cooler.
The last time it was stronger. This time the strength will scale between 0 and 2 depending on how damaged your eyes are.

I was wrong about BYOND not letting you go to sub-pixel blurs. You can totally do that.

## Images of changes
The worst blur possible. Slowly goes away as your eyes get better.
image

## Changelog
:cl: Punished Flattest
:tweak: Blurry eyes will now be blurry
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
Personally I never had any issues with the first version, so 👍 from me.

**Comment by S34NW** [comment]
Thank you for revisiting this, flatty. The effect is 100% superior to the current system.

**Comment by Mitchs98** [comment]
It still bothers my eyes, but not nearly as much as it did previously. It's tolerable, especially when compared to the current welder flash spam when welding down a wall.

Overall willing to try it out in-game for a bit to see how much it bothers me personally.

**Comment by Aurorablade** [comment]
i dunno the strong one has the right amount of suffering to it...

**Comment by Fox-McCloud** [comment]
You may want to consider TG's pre-plane master controller implementation of this, for consistency.

**Review by Kyep — APPROVED** [review]

**Comment by Wojz** [comment]
I definitely think this is better than the current "blur" overlay which personally tires me out trying to make stuff out. With this blur I can more or less navigate still, but it also looks better.

**Comment by FlattestGuitar** [comment]
@Fox-McCloud I also added /tg/'s plane master controllers to this PR. Is that okay?

**Review by dearmochi — APPROVED** [review]

**Comment by Sirryan2002** [comment]
Definitely going to need a TM before I decide whether or not I want this. I'm sure many other people feel the same way.

**Review by variableundefined — APPROVED** [review]
Was considering having it TMed, but I don't think it is needed. 

Everyone seems to like it and it is a vast improvement over the old blurry.

**Pull request merged**
