### PR TITLE
Modular Train/Tram System

### PR DESCRIPTION
**Pull request by tigercat2000**
# even if you could merge, don't, working tree is fucked, probably going to make a new PR
### So, What is MT/TS?
MT/TS is a modular train/tram system, which could really be more accurately named MTS. But, MT/TS sounds cooler, so I am going to go with that.

The intention of this system is to make a smooth-movement tram system using forceMove() and custom collision detection. Think spacepods or the ambulance on a larger, modular scale.

Currently, the system is very barebones, with only the basic modular-link, movement, and collision detection systems, with a very basic unpolished user-interface.

Demonstration video ~~to come.~~ http://youtu.be/bjyKLhJgnww
RnD one on the map: http://puu.sh/hSqtf/2dd4a2cf94.mp4

~~Heavily work-in-progress, this PR is only being put up as a way to keep track of said progress.~~

Added to map, removed the DNM tag. This will work fine enough for now.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
This came from Urist/ Tau Ceti station, right?
Big :+1:.

**Comment by tigercat2000** [comment]
@Spacemanspark Nope, this is all my code so far- although now I am interested in finding what they have

**Comment by Spacemanspark** [comment]
Oh no this is very different from what I thought, after viewing the video.
But holy shit that's original.
:+1:

**Comment by tigercat2000** [comment]
okay I managed to badly corrupt this branch, remaking the PR

**Comment by tigercat2000** [comment]
alright fixed it #1106

**Comment by Keilden** [comment]
Time to remake the Half-Life 1 intro!

**Pull request closed without merging**
