### PR TITLE
Nearby buckling

### PR DESCRIPTION
**Pull request by Aylong220**
## What Does This PR Do
You can buckle up to anything within a 1-tile radius.
I just copied the code from [here](https://github.com/ss220-space/Paradise/pull/1805). I'm ashamed.
UPD. Added a 1 second delay for mobs not under your control

## Why It's Good For The Game
No more pixel-hunting to sit down

## Images of changes
https://github.com/ParadiseSS13/Paradise/assets/69762909/1d6dd2e3-8c00-4f48-a7d9-9e933465ac41

## Testing
Buckle to everything

## Changelog
:cl:
tweak: You can now buckle up without standing on the chair, but simply by being next to it.
tweak: Buckling up anyone other than you is now on a 1-second timer.
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
Being able to buckle yourself from a tile away is a nice QOL change and just fine. Being able to buckle other people from a tile away will lead to it being used in combat more, which is not fine to me. Combat buckling is already prevalent here and doesn't really need to be made easier to do imo. 

"Just press B." is not really a valid counter-argument in my opinion given buckling is essentially a temporary rooting that always results in a few extra nigh-risk free hits for whoever buckles, possibly even a free stun depending on situations. Combat buckling can and has won many fights especially as it's very easy to not notice you're buckled in the heat of combat.

**Comment by Aylong220** [comment]
I'll try to prevent other people from buckling up, but I'm afraid my "knowledge" won't be enough here. It's gonna to take some time

**Comment by Contrabang** [comment]
You could make it only work if the person is restrained or doesn't have a client

**Comment by procdrone** [comment]
do_after for other people maybe? This way its useless in combat

**Comment by Sayrbee** [comment]
> Being able to buckle yourself from a tile away is a nice QOL change and just fine. Being able to buckle other people from a tile away will lead to it being used in combat more, which is not fine to me. Combat buckling is already prevalent here and doesn't really need to be made easier to do imo.
> 
> "Just press B." is not really a valid counter-argument in my opinion given buckling is essentially a temporary rooting that always results in a few extra nigh-risk free hits for whoever buckles, possibly even a free stun depending on situations. Combat buckling can and has won many fights especially as it's very easy to not notice you're buckled in the heat of combat.

might be able to stop combat buckling a bit by adding a half second progress bar for buckling someone else, but no progress bar for yourself.

**Comment by Aylong220** [comment]
Now this can't be used in a combat (I guess)
1 sec delay

**Comment by Aylong220** [comment]
I shit myself, you can't buckle onto the operating table.

**Comment by Rurik123** [comment]
I hate to be the anti quality of life guy, but I really don't see a reason to make this easier. Its hardly pixel hunting to control click someone, click the tile next to a chair, and then drag click them to the chair.

**Comment by Henri215** [comment]
> I hate to be the anti quality of life guy, but I really don't see a reason to make this easier. Its hardly pixel hunting to control click someone, click the tile next to a chair, and then drag click them to the chair.

Your problem is with it being usable on other people right? Because on yourself the pixel hunting is a suffering on certain kinds of chairs, having to face certain directions to expose more pixels most of the time.

**Comment by SteelSlayer** [comment]
PR has been open for a month and a half, and has 3 objections, no one in favor. Closing.

**Pull request closed without merging**
