### PR TITLE
[WIP] Alien Embryo Changes

### PR DESCRIPTION
**Pull request by Quantum-M**
## What Does This PR Do

- Alien Embroys/chest busters no longer gibs the host upon exiting, however, they have a chance to either cause severe damages to the organs in the host's torso, or destroying them all together, making it slightly harder to revive the host upon death (although cloning is still optional). **The Host still dies due to the severe brute damages they get, topped with lack of essential organs/organ damage.**
- The host must remain alive while the embryo is not past stage five, otherwise, if the host dies, the embryo also "dies" (aka won't burst).

Current Issues:
- [ ] Deal with the host's infection hud does not immedietely clear upon the larva bursting.
## Why It's Good For The Game

Response to PR #13292.

I have two reasons as to why the changes to the host bursting:
- Players that do not want to play as xenomorphs shouldn't end up permadead because they were unlucky, and shouldn't be expected to play as xenomorph. As a response to one of the comments the previous PR that tried to remove the gibbing from the xeno chest burster, were one of the arguments made that it would push people into play as aliens. My argument is that xenos already are interesting to play (for the xenomorph player) and that in itself is convincing enough, permadeath shouldn't be one of the convincing factors if people do not want to end up playing as a murderous alien.
- The xeno gibbing often ends up destroying items. These are usually suits, IDs, and bags, which sometimes may have some antag theft items.

For the changes on where the larva's host must be alive for most of the time the larva is in them:

- I have noticed previously on xenomorphs infecting and, once confirming the host has a larva, killing said hosts. This prevents that until the larva has grown enough (aka stage 5) to get ready to burst. This could be considered a nerf as xenos have to ensure their hosts remains alive for a while longer.

## Images of changes

N/A
## Changelog
:cl: Quantum-M
add: Xeno hosts must remain alive while their larva is not near bursting, otherwise the larva "dies" with them.
tweak: Xeno chestbursters no longer gibs their host, instead, they will either cause severe damages to the host's torso organs, or destroy said organs.
/:cl:

### CODE REVIEW

**Comment by VeteranKyl** [comment]
How will this effect bodies restrained in resin nests? Normally when a person bursts, the fact that their body is destroyed means the nest can be used again. Will the aliens have to manually remove the dead bodies in order to restrain a new person, or will the dead body automatically be freed from the nest?

**Comment by Quantum-M** [comment]
This shouldn't affect the code for the, xenos will have to unbuckle the dead bodies once they die, although I think I recently recalled unable to unbuckle anyone from the nests as a xeno. Will have to look into it and edit it accordingly.

**Comment by Carthusia** [comment]
It's a nice step towards bringing xeno up to par with terror spiders in terms of balance. Though I suspect a lot more will need to be done in future PR's

**Comment by Ty-Omaha** [comment]
This new "anti permadead" culture sucks.

**Comment by taukausanake** [comment]
> This new "anti permadead" culture sucks.

Isn't that literally the "culture" that the server has been following for a while? Not wanting to basically kick people from a round just because they died and most likely won't get revived. Hasn't perma-brig also been part of this argument, essentially being discluded from the round because you were antag.
~~You're just mad because xenos are getting fixed~~

**Comment by MRgaty** [comment]
I dont like this, cloning would remove the urgency of treating infected crew members and is so utterly easy to just stuck someone in cloning and have them back in 2 minutes that fighting xenos is no longer dangerous, but just a minor inconvenience idf you get killed.
The disarm spam may suck but I feel that permakilling people is necessary for the xenos.

**Comment by Carthusia** [comment]
> The disarm spam may suck but I feel that **permakilling people is necessary for the xenos.**

I have to ask: If this was the case, why is it not so for terror spiders? Terrors generate more spiders per host than a xeno could, yet don't kill the host unless the host is SEVERELY wounded, and even then, they are fixable.

So why would Xeno's need to destroy the host to be viable gameplay wise?

As for urgency, the urgency is still there as you need to prevent it from coming to term, in a mass infestation, if the host dies, and a xeno is created, even if the xeno is quickly killed, and the host body still intact, priority still lays with other hosts.

Granted yes, they can just be tossed into the cloner, but this is also the case for every other antag available should they be killed by them.

Clings ,syndicates ,vampires, terror spider, shadowlings, blob zombies, headcrab zombies, cultists (Excluding constructs), wizards (excluding body exploding spells) all result in recoverable deaths, should the body/brain be intact.

Perhaps the issue is at hand is not so much that antags need more perma death options, but that the cloning method available is to much of an easy button?

For some people, why bother spending the time and resources reviving a guy with 4 IB, 6 broken bones, and low blood, when they could just let him die, and toss him into the cloner.

For some races like vox and slimes this isn't an option, which is good as it forces people to be a doctor/surgeon.

Perhaps a more involved revamp of cloning in separate PR is the key? Make the cloning station a job within itself or perhaps a side job of genetics. They don't exactly have much to do most shifts?

 Proper monitoring of the clone, injecting of nutrients and making sure it doesn't go over or under thresholds to produce a properly formed clone with as little genetic damage as possible.

If cloning was more involved and required player interaction, it becomes more interesting and less of a "Shake and Bake" method, where you just toss them in and forget about them.

**Comment by lolzyking** [comment]
You seem to be missing a major issue with pre stage 5 embryo's not bursting

People will suicide out of it (not via suicide but harming themself into  crit and succumbing)

**Comment by Aquilar** [comment]
> You seem to be missing a major issue with pre stage 5 embryo's not bursting
> 
> People will suicide out of it (not via suicide but harming themself into crit and succumbing)

Suiciding to avoid an antag is already against the rules but you forgetting nests exist to stop that kind of behaviour from hosts, also neurotoxin spit and stun spam.
the change also stops xeno from venting parts of the station too since they'll need the hosts to be alive.

**Comment by Carthusia** [comment]
> Suiciding to avoid an antag is already against the rules but you forgetting nests exist to stop that kind of behaviour from hosts, also neurotoxin spit and stun spam.

As far as i'm aware, suiciding to avoid xenos is fully acceptable, and has been encouraged in some cases.

Reason for it: Your caught, your hugged, your dead, you have virtually no chance to escape, why make the player sit there for the next 5 minutes just waiting to die when they can konk out and be a ghost.

An alternative to suicide could be how Colonial Marines resolved this issue, you don't "suicide" you just enter a coma, the player leaves their body as a ghost like normal, cant re-enter it, but the body does not die, it remains alive and active but the player is no longer bound to the body and has to waste their time waiting for their death.

Xenos get their new xeno, player doesnt have to waste their time

**Comment by lolzyking** [comment]
Here's the thing though most of the time in the process of getting face hugged, swallowed by a hunter and vent crawled to the nest you end up in crit, If you get neurotoxin stunned that puts you into sleep while in crit


you can just type succumb in the chat right there.... and you won't hatch.

**Comment by AdamElTablawy** [comment]
@Carthusia 
Given that terror spiders are horribly balanced, I don't think bringing them up is a good idea. Those things are pathetic.

also, if you're going with the cloning thing, you could just do what tg did, remove it, add revival surgery instead, tada

**Comment by Mitchs98** [comment]
Xenos are far from horribly balanced, they are eons more balanced than xenos and far more fun to fight. They can definitely win and have won many times before. Xenos on the other hand are far, far to overpowered and the gibbing just doesn't make any sense. The only reason the PR to stop them from gibbing before was closed down was, as the OP states, that maints/heads wanted people to play as xenos more. If people are going to play as xenos, they'd play as xenos regardless of gibbing or not.

That said, I can see the issue in the embryo thing, however. If xenos are abusing their hosts and using cheese tactics to win in order to further give people no counterplay to them? Yeah they deserve some kind of downside to do so when they're already woefully unbalanced as they already are.

**Comment by SteelSlayer** [comment]
Keep in mind, as long as the hugger has infected a host, i.e. they have the little alien hud infection icon, the larva will burst from the host. It will take longer if the host is dead but it will still happen. People already suicide and succumb to avoid this but unless they do it the instant they are hugged, they will burst. Even if they do that, it still might not save them, I don't know the exact timing.

@Mitchs98 
When you said "**Xenos** are far from horribly balanced", you meant to say terror spiders right?

**Comment by Mitchs98** [comment]
> Keep in mind, as long as the hugger has infected a host, i.e. they have the little alien hud infection icon, the larva will burst from the host. It will take longer if the host is dead but it will still happen. People already suicide and succumb to avoid this but unless they do it the instant they are hugged, they will burst. Even if they do that, it still might not save them, I don't know the exact timing.
> 
> @Mitchs98
> When you said "**Xenos** are far from horribly balanced", you meant to say terror spiders right?

Yeah sorry. Thanks for that, edited my post. My brain derped on that.

**Comment by BakKeener** [comment]
I have a suggestion to add onto this, so you know how Larva can feed on hosts to speed up their evolution right? This can be done on corpses. If larva can just burst from their host, they will be able to evolve very quickly just from munching on their body. Can you add something that will make it so larva cannot gain evolution points from either biting corpses or people previously infected by an alien embryo.

**Comment by lolzyking** [comment]
The Death stopping bursting will be abused too much it should be removed from this PR, removing gibbing is fine, all a person has to do is punch themselves into crit and then sleep or get xeno nuerotoxin stunned and succumb preventing the xenos from growing in numbers.

Xenos have a rough enough time with having to rip off hardsuits, masks, and getting murdered by mechs.

**Comment by Mitchs98** [comment]
Saying that xenos have a 'rough time' against one of their main(and often only) counters isn't a counterpoint to the PR. They're meant to have a rough time against one of the few things that can counter them. While I do agree mechs are a bit too strong against them, they're also basically the only thing that stands a chance against a hive most of the time. 

Sure it can be abused, but at the same time, xenos definitely shouldn't be able to capture and kill people freely upon capture and expect to be able to get hosts. 

Something I'd suggest adding to this PR is to prevent xenos from being able to acid heads/brains(if they already can), or we'd be back at square one here. Unsure if they can disposal/toss people or not, but that's a possibility that should be looked into as well. If they no longer gib they'll simply dispose of bodies another way as they did on CM.

**Comment by taukausanake** [comment]
I once played xeno a long time ago. I vored a crew member and tried to take them to the hive location to be facehugged but I took too long getting there and the body dissolved inside me. Maybe take a look at that?

**Comment by Aquilar** [comment]
because said individual died while inside you.

**Comment by Mitchs98** [comment]
> I once played xeno a long time ago. I vored a crew member and tried to take them to the hive location to be facehugged but I took too long getting there and the body dissolved inside me. Maybe take a look at that?

This is also something to look into for sure. Xenos will just eat dead bodies.

**Comment by lolzyking** [comment]
Yeah but the thing is most of the time mitch, its not the Sentinels and queens killing the hosts, its some dipshit larvae trying to grow up faster. I think this change just has too big of a down side, xenos don't really have a way to stop a person from killing themselves while they're in the nest other than stunning and if they are already in crit (like most mid event hosts since the xenos have to subdue the hardsuit wearing attackers) they can just type in the magic word -succumb- while unconscious from the stun and in crit.

**Comment by Mitchs98** [comment]
Warriors can easily disarm spam the hardsuit wielders without using harm attack to subdue the hardsuit users. They don't HAVE to crit them, actually.  Disarm them, nest them, remove hardsuit. They can no longer succumb.

**Comment by lolzyking** [comment]
People in nest can still punch themselves and disarm xenos

**Comment by Mitchs98** [comment]
Disarming xenos has an astronomically low chance. Change nests to handcuff you too and you get around the punching problem.

None of this is impossible to change or fix.

**Comment by Quantum-M** [comment]
At the moment, in scope of this PR, I am largely focusing on chestbusters, how their hosts are handled, and larvas. Anything other aspects in regards of Xenos will warrant another PR.

**Comment by Mitchs98** [comment]
> At the moment, in scope of this PR, I am largely focusing on chestbusters, how their hosts are handled, and larvas. Anything other aspects in regards of Xenos will warrant another PR.

Yeah I figured as much. I'm just commenting on the negative points people are stating against the PR.

**Comment by Quantum-M** [comment]
Given the opposition of a head, and a maintainer, and that I am having some issues figuring the code, I am closing this PR, good luck to whoever tries to balance Xenos.

**Pull request closed without merging**
