### PR TITLE
NanoMed Plus nerf

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

NanoMed Plus contents amounts have been decreased.
## Why It's Good For The Game

While the contents amounts of one vendor isnt THAT excessive you should account that all cyberiad/kerberos medbays have 6 vendors  (someone please remove one!) and cerberos 5 and lets not forget about spawn supplies and medbay storage.

Auto-mender: Every doctor spawns with one, medical storage has more of it and its not a single use item. The amount of menders available should be decreased to encourage people asking for chemistry to refill it (or asking cargo to print empty ones) instead of using it like its an expendable single use item.

Amount suggestions are welcome.
## Images of changes

image

image

## Testing

- Used my eyes to look into nanomed plus contents.
## Changelog
:cl:
tweak: NanoMed Plus contents amounts have been decreased
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
This is gonna conflict with economy PR

I personally don't like this because medical already usually runs out of medical supplies even with multiple vendors during biohazards. Automenders are overrated and overused, but theyre still useful as a last resort. 1 is way too low per vendor for all of medical, especially considering antags sometimes steal them.

You've also decreased several other useful items, especially pills, which were already heavily nerfed in #18904. I think the patches and bottles should stay where they are because they are small amounts of healing which are good for distributing across multiple people. Trading out menders for more patches would be good imo. I would prefer if there was still 4 morphine bottles though because you need 4 morphine bottles for optimal hydrocodone creation as a chemist.

As for the pills, please dont decrease those more, I usually take 5 salb and 5 mannitol pills at shift start, which if everyone did that would drain the vendors pretty much immediately. I usually go through this medicine within the hour on non-extended shifts.

Keeping stuff like beakers even would also be preferred because you take 2 for dialysis and 2 for the surgery rooms.

Imo if you want to decrease the amount of automenders, it should be more atomized

**Comment by GDNgit** [comment]
I 100% agree this needs to happen, the raw abundence of medical supplies is really absurd. Got a few notes however
- Automenders really should have 2 in a vender, they're like... not great for actually healing people but they're good for new players. Having 1 in a vendor looks a bit weird.
- Hyposprays could be entirely removed, encouraging people to go to cargo to order one is not a bad thing
- Packs could be dropped to 2

**Comment by Carthusia** [comment]
Ive seen the bay run out of every single mainline med in the vendors more times than i can count, I dunno if lowering the meds they get at start is a good idea.

**Comment by Henri215** [comment]
> I 100% agree this needs to happen, the raw abundence of medical supplies is really absurd. Got a few notes however
> 
> * Automenders really should have 2 in a vender, they're like... not great for actually healing people but they're good for new players. Having 1 in a vendor looks a bit weird.
> * Hyposprays could be entirely removed, encouraging people to go to cargo to order one is not a bad thing
> * Packs could be dropped to 2

Going to increase menders to 2.

I think before removing hypos we would have to add a few to medical storage or lockers.

Going to drop packs to 2.

**Comment by Henri215** [comment]
> 

There are vending refills that cargo can order, and they are cheap. Please do go to cargo, give them work, if you empty 2 vendors shift start as a paramedic and dont order refills there should be consequences.

**Comment by Edan52** [comment]
I believe these vending machines should have the essentials and other equipment that aren't chemicals, and chemistry should be needed for the rest.

Back in the day, the vendors had much less and medical operated just fine, and I feel the gameplay between doctors and chemistry was also better this way.

**Comment by CinnamonSnowball** [comment]
I suppose I can go through them in order:
- Syringe number change is fine, pretty much every Medbay also has one or two syringe boxes somewhere, having an extra 12 _per vendor_ is indeed a bit ridiculous (very slightly out-of-scope, but IMO they could also be lowered in the list to near where beakers/droppers/etc. are)
- Patches I think should either stay at current number, or be replaced with the mini variants with the number available doubled or sth, as the default 30u variant is massive and most of its potential is wasted during in-Medbay use
- Menders being lowered to 2 sounds good
- No strong feelings regarding any of the medicine bottles nor Spaceacillin syringes
- While Calomel is severely underused, it's.. somewhat weak when taking into account the severe side effects, so I suppose drastically lowering its availability is not a big problem
- I'd *buff* Heparin syringes, if anything; Heparin is not only slightly weaker than Epinephrine, it's also drastically less available even currently (4×15u Heparin syringes vs. 4×30u Epinephrine bottles + 5×10u emergency injectors)
- For reasons stated above, I'd keep the current pill availability, as they have already been nerfed recently and doctors blow through them rather fast
- Similarly for reasons stated by others, advanced healing kits could also use one or two extra units, especially if we're lowering the number of available menders
- Bandages are already very underused, they don't need a further nerf
- No strong opinion on splints, usually if somebody in Medbay needs them they can just get the permanent surgery fix anyway
- I don't particularly think beakers and droppers need a nerf, but I suppose they're not used super often either; most maps have an extra box of beakers anyway
- No strong feelings for Health Analyzer change

With all that, as much as I too think current medical vendors have a bit too much stuff in them, keep in mind that Medbay is a somewhat important department to have running well during emergencies, and doctors shouldn't necessarily have to run to Cargo/Botany after ten minutes of treating a swarm of patients. Similarly, while having doctors rely on Chemistry is good, beware of overtuning it, as IMO Chemistry already has plenty of work to worry about (especially for new players), and they also deserve to have some free time to hang out with coworkers and such.

**Comment by Carthusia** [comment]
> I believe these vending machines should have the essentials and other equipment that aren't chemicals, and chemistry should be needed for the rest.
> 
> Back in the day, the vendors had much less and medical operated just fine, and I feel the gameplay between doctors and chemistry was also better this way.

I feel back then, we didnt have player peaks of 120-140 on a regular basis, so lower med counts made sense, as the population increases, so to does the bays starter meds to account for this, least thats my thought on that

**Comment by Carthusia** [comment]
Just going to throw an example out there to explain why i think the counts are fine as is:

Medbay has 5 vendors, say it spawns with 5 doctors, you get each of those doctors to drain an entire vendor for their kit, and then restock the vendors to full.

The moment you toss a major emergency onto the station like say, a serious blob, or terror spiders, the sheer amount of people flooding into the bay as wounded, or needing supplies to fight the threat will drain each of those doctors kits within 5-10 minutes, and the vendors and spare storage will be looted of every, SINGLE piece of useful medical supplies by the crew when you cant stop them from hacking the vendors due to being busy treating people, ontop of the fact Cargo will be to busy with weapons orders to focus on trying to get medical supplies shipped off quickly, and no one during an emergency that actually requires firearms for the crew is going to prioritize medbays supply orders over guns and ammo

Lowering the med counts I feel is just going to make this situation worse.

**Comment by Henri215** [comment]
CYBERIAD
1 CMO and 5 doctors (spawns with 1 first aid kit)
6 medical vendors
medical storage

auto-mender (brute) = 6x1 / 6x3 / 3 = 27
advanced pack (brute) = 2(from environment) / 6x4 / 2 = 28
patch (brute) = 6x1 / 6x4 / 7 = 37

TWEAKED
auto-mender (brute) = 6x1 / 6x2 / 3 = 21
advanced pack (brute) = 2(from environment) / 6x2 / 2 = 16
patch (brute)= 6x1 / 6x3 / 7 = 31

Thats how much medbay starts with for these items as an example.

**Comment by CinnamonSnowball** [comment]
Emergency NanoMeds are frankly an entirely different story. Some stations barely have any, some stations have them concentrated in Medbay, which doesn't make sense either - Medbay already has medicine in their big vendors.
They should be spread out over the station where emergency medicine supplies are actually useful and not widely available, but that's Out Of Scope for this PR, of course.

**Comment by Miraviel** [comment]
Please update the screenshots in your first post to reflect the changes.

I am impartial about this change, ideally, we should have stocks scaling with population. With your tweaked numbers, lowpop medbay won't feel the scarcity, but highpop medbay will feel it very much so.

**Comment by Henri215** [comment]
> Please update the screenshots in your first post to reflect the changes.
> 
> I am impartial about this change, ideally, we should have stocks scaling with population. With your tweaked numbers, lowpop medbay won't feel the scarcity, but highpop medbay will feel it very much so.

Updated screenshots.
Scaling stocks is a very interesting idea.

**Comment by lewcc** [comment]
I personally think you should go even further and completely remove automenders from medbay, leaving them only in the spawn kits for doctors (or made, empty, in lathes), but that might be for another PR.

**Comment by Sirryan2002** [comment]
can you check the make sure the nanomed refill canisters don't have more stuff in them than what can be maximally put into the vendor?

**Comment by Henri215** [comment]
> can you check the make sure the nanomed refill canisters don't have more stuff in them than what can be maximally put into the vendor?

Refill canisters amounts follows the vendor amounts.

**Comment by Calyxman** [comment]
Not a fan of this at all. Med already runs out of supplies a lot.

**Review by hal9000PR — APPROVED** [review]
We will see how this plays out

**Pull request merged**
