### PR TITLE
Kidan Rebalance

### PR DESCRIPTION
**Pull request by Kyep**
Currently, almost nobody plays Kidan, because their "unable to wear glasses" restriction is way too onerous.
- It prevents them wearing mesons, hurting their ability to do mining, engineering, and atmos.
- It prevents them wearing sec HUDs, which hurts them in all security jobs.
- It prevents them wearing medical HUDs, which hurts them in most medical jobs.
- It prevents them wearing science and diagnostic HUDs, which hurt them in science and robotics jobs.

In short, Kidan are at a big disadvantage in trying to play most jobs.
Yes, they get a 20% reduction in incoming brute damage, and better unarmed attacks.
Still, this isn't sufficient compensation for their loss of ability to wear eyewear/HUDs.
Both unarmed attacks and brute damage mitigation are situational benefits, but the inability to wear eyewear is a far more regular problem in most departments.
It is way easier to get extra brute damage mitigation (even civilians can get shields), than it is to work around the eyewear issue.

So, in this PR, I make two changes to Kidans, with the goal of making them a more viable race.
- First, they can now wear eyewear, like the other races.
- Second, to compensate for this, ~~they are no longer clonable~~ they now take 30% extra damage from toxins.

Yes, this leaves Kidan arguably stronger than they were before. That is intentional.
Right now they're seen as a crippled race that nobody plays.
My hope is these changes get them out of the doghouse, and get people to take them seriously as a race they might want to play.
They still cost 30 KP, so there is still a high barrier to playing them, but at least now people might actually see them as worth it.

kidan_officer
kidan_doctor

🆑 Kyep
tweak: Kidan can now wear glasses, but also take +30% more tox damage from all tox damage sources.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
I disagree with this. I personally can work around my kidan unable to wear glasses. and adding is unable to be cloned is meh as a debuff.

**Comment by Jountax** [comment]
I was working on a buff that simply gave kidans the ability to sense ores through walls, which I felt was a more interesting advantage to counterbalance their more interesting disadvantage of being unable to wear glasses. It also fixed the most glaring of the (I imagine unintended) side effects of the nerf, which was a total inability to play mining.

Security hudglasses can be reproduced with a welding shield and sechud implant, medhuds can be replaced by a medhud implant, and diagnostic huds, botanical huds, and science goggles are all unnecessary conveniences at best. Unless for some reason the roboticist is wandering the halls looking for borgs to fix instead of just building more things and waiting for damaged borgs to come/be dragged to them for repairs.

I also thoroughly dislike the inability to be cloned as a downside, as how much of a downside it actually is depends entirely on how competent medbay is, ranging from being revived even faster than cloning to never revived at all. That, and two other races already have it as a downside, which makes it less interesting overall.

**Comment by Kyep** [comment]
Fethas, how do you work around it?
The debuff is intended to not be as severe as the glasses exclusion is, on the grounds that it is a rarely played race that could use a bit of a rebalance to make people more keen on playing it. Also, you're an admin, so you get all karma races unlocked for free. That means you can try it out for zero cost. Normal players don't have that luxury. For them, they have to choose whether they want to spend 30 KP on it, without ever having played it before. For a lot of them, the inability to wear eyewear is a straight-up dealbreaker.

Jountax
I thought about giving them ore-sense, but I don't want this to be about mining. IMHO, their inability to wear eyewear applies to almost all departments. I don't want to address it for mining, but ignore it otherwise. Implants may be an option, but there are lots of shifts where they simply aren't available for various reasons.
I am open to changing the downside, though. I picked no cloning as I could not think of anything better at the time.

**Comment by davidchan13** [comment]
@Kyep outside the scope of this PR but given that their eyesight SHOULD be better than anyone else's, Them not being able to utilize eyewear makes sense given their multifaceted eyes. We could increase their darkvision as a start as well as give them more acute senses. Detecting ore would be one, while auto/free meson vision might be another if tremor sense is something someone wanted. 

More in depth/descriptive examine text might be a means to compensate for lack of medical HUDs. Able to see all external brute/burn injuries or detect pheromones in the air around a person to gauge if they might be suffering from asphyxiation or high toxicity in their system.

As they are based off Ants, giving them some manner of pheromone trails or markers they can place in the air that other Kidan can sense (and perhaps a high level science HUD or scanner that would be able to detect them)

IMHO we should perhaps make them pressure resistant due to their exoskeletons or allow their legs to function as magboots on command.

**Comment by Aurorablade** [comment]
Normally i use monocle/one eye version of huds as needed depending on job. We just do not have that for like mesons at the moment. It should be about the flavor of the race and not the mechanics. if you refuse to play something purely on a mechanical basis then flavor basis that is your choice. As a rp server we need to try to promote flavor and theme over mechanics where possible (though i know we need mechnics to support that code wise sometimes some necessary evil)

Kidan can eat diona nymphs, produce light in exchange for hunger, are a bit tanky and in exchange they cannot wear glasses due to both head shape and eye shape. The exclusion being they can wear over the eye huds. Now in sec that has the issue of the flash protection being missing. But we do have implants as needed for that.

So i don't think removing the inability to wear glasses is the way to go here. If anything you can add monocle/one eyed hud varients of anything missing. (mesons).

I like jouns ideas here. Expand it, think of it like a version of echolocation on a cooldown. it pings an area.  Maybe not just ore but can pick up creatures as well. To prevent some odd opness, if it picks up a creature maybe it could be a shape overlay thats not idenifiable. Its something to balance there.

Now i am not sure about the pressure resistant suggestion as we have a few races like that already. but the marker/trail thing is a interesting idea.

**Comment by Necaladun** [comment]
I really don't think noclone is a good enough counterbalance. Defibs and SR make it a pretty minor downside, and pretty circumstantial as it requires you to die - something that their advantage makes it harder to do.

If anything I'd look at something along the lines of + toxin damage.

**Comment by Tayyyyyyy** [comment]
Just throwing this idea out there, it's not mine but I kinda like it:

Kidan bones break more easily but their bones are also easier to fix (exoskeleton).

Has a bit of basis in reality, maybe? Physics is not my forte...from [the wikipedia article on Exoskeleton](https://en.wikipedia.org/wiki/Arthropod_exoskeleton) (which, content warning, has a terrifying gif of a moulting cicada):

> The outer layer is where most of the thickening, biomineralization and sclerotisation takes place, and its material tends to be strong under compressive stresses, though weaker under tension.[2] When a rigid region fails under stress, it does so by cracking.[2] The inner layer is not as highly sclerotised, and is correspondingly softer but tougher; it resists tensile stresses but is liable to failure under compression.[2]

**Comment by Regen1** [comment]
It'd be good to brainstorm some new ideas rather than just tweaking some damage values and adding some rather arbitrary flags to them, like noclone/noscan.

That's just kind of thinking out loud though, I don't have any brilliant ideas (yet), but I'd like to encourage it.

**Comment by Kyep** [comment]
Currently, the disadvantage is +30% tox damage.
I'm open to changing that, though, if people can come up with a better disadvantage.

The "can now wear eyewear" part I don't want to change, because I feel the eyewear restriction is so bad it makes people avoid the race entirely, and I feel that has to be removed for the race to be viable.

**Comment by Aurorablade** [comment]
I think we just need a better buff to them as in the suggestions thrown around and keep the eyewear loss.

**Comment by Aurorablade** [comment]
Regardless i think giving them some kind of attractive and flavorful buff might be better then removing the glasses thing in its entirety.

Key thing is i think the buff what ever it may be should be something that could lend to MORE to rp then over gameplay while still being something useful.

**Comment by taukausanake** [comment]
> terrifying gif of a moulting cicada

MAKE KIDA MOLT TO HEAL. I don't know if that's valid in real life bugs but it sounds cool for what are basically space ants. Gotta get naked first though.
Literally the only idea to come to my brain but I dare say it's a good one

**Comment by Tayyyyyyy** [comment]
> MAKE KIDA MOLT TO HEAL.

Just taking this thought experiment further, maybe it could kind of be like shadowing rehatch. Can't use normal means to heal but molting would fix them entirely. Not sure how to resolve them getting critted though, can't really molt while in critical. Or maybe let them molt while in critical?

**Comment by Citinited** [comment]
Oh god, imagine all the kidan leaving their old skins around the station D:

**Comment by Dinarzad** [comment]
> Oh god, imagine all the kidan leaving their old skins around the station D:

That little moment when a Janitor walks into a room to clean it and has to see heaping piles of dessicated, tossed aside old Kida skins.

**Comment by Kyep** [comment]
@Spartan6 Changelog updated. Even assuming implants exist for all the types, that seems a very complicated way of achieving little. It would be as if they could wear eyewear, but they can't change eyewear with a job transfer. Not really fun or interesting.

@Aurorablade I consider the race to be non-viable without the ability to wear eyewear, so this PR is going to stick with giving them that ability. I'm open to changing what new disadvantage they get in exchange for losing the eyewear disadvantage, though. Also, them being able to wear single-eye pieces but not glasses makes no sense to me.

@Ralta 
I did look into the practicality of doing this, but as I am not a medical expert, I'd want more people to comment on it. In addition, I worry that it essentially negates their +brute resistance. After all, if you end up going to medbay anyway, except its due to blood loss rather than brute damage, functionally, from your point of view, there's little difference.

@taukausanake Rather like shadowling rapid rehatch, or changeling revive? Except, not as strong? Meh, could do that, but I worry its just stealing the diona regeneration trait, just with a slightly different execution. Also, I'm not really looking to add more buffs to them. I consider them perfectly viable so long as they can wear glasses. Its mainly tweaking the corresponding new disadvantage I'm interested in.

@Dinarzad I'm fine with changing the toxin debuff, either now or later. The reason its there right now is that it was suggested by Neca (headmin) as a good option to counterbalance their gains in being able to wear glasses now. So far I haven't found any debuff ideas that seemed to be the obvious answer. I thought about making them vulnerable to pest killer chems, but they actually already have that, so it isn't an option here.

**Comment by Aurorablade** [comment]
Kyet you are getting one of your stubborn patches again. and yes we are going back and forth on it. I totally disagree with the removal of the inability of eyewear. There are VARIOUS alternatives to get around this as was stated, and if mesons is a issue with can add a one eyed varient to it like there is for med and sec huds. not being able to wear glasses DOES NOT make a race not viable.

I would much rather add another buff to them that was interesting to offset the current debuff.

**Comment by Kyep** [comment]
@Aurorablade Stubbornness is in the eye of the beholder. Just as you have no obligation to accept my suggestions on your PRs, so I have no obligation to accept your suggestions on my PRs. I get lots of suggestions, and ultimately I have to pick the ideas that I think are best, regardless of whether they please you or not. I think I understand your position just fine, I just don't agree with it, for two main reasons. First, I do not think that the current workarounds are adequate. If they were, people like Dinarzad wouldn't be saying that the eyewear restrictions are why they don't play Kidan characters.  Second, I do not think that adding yet more workarounds (custom implants, etc) is as good, effective or clean as just fixing the root cause of the problem. The way I see it, if the restriction cannot easily be worked around, it makes the race non-viable as a play option for many people. On the other hand, if it can easily be worked around, then the race effectively just requires awkward workarounds, and has additional complexity, for no good reason. Neither is a good position for the race to be in. Races can be unique without being given traits that seriously discourage people from playing them at all.

**Comment by Citinited** [comment]
@Aurorablade I don't really see the point of adding functionally identical glasses for kidan - if you're going to do that you may as well just remove the disability and not bother with the kidan-specific glasses.

**Comment by Aurorablade** [comment]
The problem is also in the eye of the beholder...as i do not see one. We have tons of alternatives and work arounds to make the lake of eye wear trivial at best. Dinarzard also said he could accept it if a feature was given to counterset it. andi still think you should look there.

**Comment by Kyep** [comment]
The question I am asking is: is the lack of ability to wear eyewear putting off players IN GENERAL from playing Kidan? Despite the claims of workarounds/etc?
If the answer is yes, I interpret that as a good reason for removing the restriction, and replacing it with something else, as this PR seeks to do. 
If the answer is no, then fair enough, I was wrong, I'll just close the PR.

**Comment by Aurorablade** [comment]
@Citinited i don't mean snowflake glasse for kidan, we already have one eyed huds for sec and med..why not meson and round out the group?

**Comment by Aurorablade** [comment]
As a kidan player, i do not have a problem with not being able to wear glasses. I mean sometimes i forget i can't but thats it. I roll with it. To me it adds to the races flavor.

**Comment by Aurorablade** [comment]
And don't close the PR we can just change the purpose and use it to add something else to the race if needed.

**Comment by Tayyyyyyy** [comment]
@Aurorablade I feel like Kyep is right that the monocle thing is an oversight, probably because of improper inheritance. It doesn't make any sense for one lense to work when two lenses doesn't.

**Comment by Aurorablade** [comment]
I aways was able to use the one eyes on my kidan last i did, Whats not working currently?

**Comment by Citinited** [comment]
@Aurorablade But then what's the point of making them unable to wear glasses if they have functionally identical items available to them, just under a different name?

**Comment by Aurorablade** [comment]
cuase some of the monocles style huds do not have the same protections as the full double eye/glasses huds do.

**Comment by Jountax** [comment]
If we had a trait system, I could see Kida evolving to have various 'roles' similar to an ant colony. there are soldier ants, forager ants, a queen ant, etc.

Where I'm going with this is that ore sense could be just the start in such a system. It would be the extra sense one of the kidan niches got, the 'digging.' There could also be 'nurse' kida who get an intrinsic health HUD, 'biochemical' kida that can sense what chemicals are in a beaker just by sniffing it, 'foragers' that get an intrinsic Botanical HUD, and so on. No sec HUD or diagnostics, obviously, unless some kind of fluff to make them work was come up with. These would all be missing one or more aspects of the normal HUD too, for example the ore sense can't defuse gibtonite and doesn't actually act as mesons, the health HUD wouldn't let you update records, etc.

**Comment by Ralta** [comment]
@Kyep Thanks for looking into it, mate. From what I understand. brute resistance should decrease the likelihood of bleeding outside of inescapable causes such as bladed weapons. In other words, having a higher brute resistance should also increase the resistance to bleeding purely from receiving brute damage.

As for causing bleeding to increase, we do have a reagent in the game which causes increased bleeding: Heparin. I'm wondering if it'd be possible to utilise that effect on the species somehow.

In any case, I appreciate you taking the time to review and respond to so many suggestions. There are some interesting thoughts coming up in this thread and while I don't currently play Kidan, I might check 'em out after whatever changes you go with get merged.

**Comment by imsxz** [comment]
>As a kidan player, i do not have a problem with not being able to wear glasses.

Found the pacifist. Any antag/sec player knows how vital flash protection is in combat, as any competent sec player will be throwing flashbangs versus a variety of threats.

The inability to wear glasses severely cripples a kidan players ability to play as and against security.

**Comment by Aurorablade** [comment]
> Found the pacifist

Well now i am a bit insulted...

**Comment by taukausanake** [comment]
The only reason I would ever play Kidan (I haven't bought it yet) is to farm Diona nymphs. I care not for anything else.

We really sure go through the trouble of making specie specific gear. I feel that would be best for all species in the long run. The problem I imagine, aside from code upkeep; that's always a problem with someone, is the work players would have to go through to get the gear. Hardsuit kits? Tearing shoes and gloves to fit on Vulps and Taj? I think at some point Vox also had torn up uniforms? I know they had different breath masks but not sure anymore

**Comment by Aurorablade** [comment]
okay so monocle huds on kidan need to be fixed as i just noted. Easy to fix.

**Comment by Jountax** [comment]
There are other forms of flash protection if I'm not mistaken. Sadly, all of them restrict vision a bit or require surgery, but I would not be surprised if a robust kidan were to simply toggle a welding mask on and off as needed midfight.

Half of what you robust folk do just seems like magic to me.

**Comment by tigercat2000** [comment]
I don't like this. tox-mod isn't a very prevalent downside, and it really isn't "impossible" to play sec or med without their HUDs. Lack of cloning is boring and overdone as well.

**Comment by ZomgPonies** [comment]
Unclonable is a lazy downside. The idea of Kidan not wearing sechuds was to make them not automatically be the best at sec due to their resistances. With the advent of eye implants, this debuff has been partially mitigated late-game.

If you want to play kidan sec, just partner up with a normie that can provide sechud information for you.

**Comment by Dinarzad** [comment]
Or.
Alternatively
Don't play Kidan and play something else more enjoyable with half the pain. That seems to be the option almost everyone is taking. That's a solid indicator that line of thinking doesn't work in application compared to on paper.

**Comment by Vivalas** [comment]
Eh, it's nice to try to bring the race out of the doghouse but I don't think this is the way. Not being able to wear glasses seems like a suitable disadvantage for a race-- inconvenient but by no means game-ending. It also makes sense, since like, they have big bug eyes.

I think a better way is to come up with a unique advantage rather than removing their very clever disadvantage and replacing it with a disadvantage that isn't very unique, isn't very characteristic of their racial design, and is kinda boring-- not to mention pretty mild.

**Comment by ManiacalSymphony** [comment]
What if since the eyewear doesn't fit them well, it just falls off when they fall down?

**Comment by taukausanake** [comment]
@ManiacalSymphony I think the case is a Kidan's head is so strangely shaped (think Skrell and full-head helmets) that eyewear would need to be retrofitted in order to even be useful. It is this reason that monocles would work instead, despite no face muscles or flesh skin to hold one in place.

Adding to that, HUDs don't work because IC: they fit over normal humanoid heads, and OOC: because they aren't sub-type monocle, yes?

**Comment by shazbot194** [comment]
I do quite like @Jountax 's idea of them being able to have half huds as organs, with the maybe exception of meson as that is a semi-vital part of engineering and mining and can't really have any features cut out. And while it would be a sizable bonus basically getting a free hud, its not like its that hard to get any of them already, if R&D even does half of their job they can give quite literally everyone every single hud  type with night vision if they wanted to (and if mining did their job). This would mean that while they aren't quite as crippled as they were, they are still much less versatile then anyone with a proper hud and can't really swap them out, however, one possible idea, taking another note from real ants, is that for a large cost of nutrition, they could change it from one style to another, as often ants can change their job in a colony. This change would give them some of that versatility back and not lock them into one job.

**Pull request closed without merging**
