### PR TITLE
Laser guns with magazines

### PR DESCRIPTION
**Pull request by shazbot194**
**Mark two is now here.**
This PR have changed massively. The most noticible to none coders is that there are now only three different sprites. The biggest code change is that it now is more or less a ballistic weapon that shoots lasers and can have its magazines recharged at weapon charging stations. They can still have several different setting such as having disabler beams or a kill beams. To switch between them you just a click the hud button. 

**Features:**

- Shoots just like Energy weapons.
- Can change between different kinds of beams/bolts.
- Magazines fit in sec belts, red space suits, military belts, and anything that can hold ballistic weapon ammo.
- Can be reloaded just like any magazine fed ballistic weapon, except the saw.
- Magazines can be examined to see how many shots are left. 
- Magazines can be charged at weapon chargers.
- Can be loaded with a +1 due to it being an offshoot of ballistic weapons.
- Can have indicator lights.
- EMPs now drain both the rifles and magazines.

d1ed0baa89a440249d6ea3b6b06044e7
The sprites having moving lights and look better in-game.

(In order)
**Mark 5 Laser Carbine:**
A relativity cheap laser rifle.
It has both lethal lasers and tazer rounds.
(mostly used as the default senergy icon and if someone really wants some warhammer.)
**SG-17:**
A rifle used by the Sol Goverment. It was made to look and feel like the standard Sol Goverment rifle that is used in terrestrial use.
It has both tazer rounds and lethal lasers.
**IK-59:**
A laser carbine.
It only has lethal lasers.
3af55feb1fe84e17830b817c57f425ba

Security Rifle
A weak rifle with a large magazine. It shoots just as fast as a normal rifle.
Has both weaker lethal and disabler rounds. (13 hits to kill and 4 to stun)
It also has magazines that can spawn without charge.

🆑 Shazbot194
rsadds: Adds in energy weapons with removable magazines.
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Those sprites don't fit with the existing laser gun's style *at all*.

**Comment by shazbot194** [comment]
That does look better, I will see about making something similar and also see about the sprites.

**Comment by Fruerlund** [comment]
Number 2, does not design wise seem to fit in, however if you recolor/shade the others into the same dark scheme as our other energy guns and fix the code issues pointed out, then I think this will have a better chance at getting merged. 

They look very cool

**Comment by shazbot194** [comment]
Ok, this version should be a lot better then the first one. It is also way less snowflaked.

**Comment by taukausanake** [comment]
I don't know, I like how the sprites look. Maybe the yellow disablers I think they are should be blue to match other disabler guns. A little bit of shading on the gray body maybe and all is fine

**Comment by shazbot194** [comment]
Ok, I will look into shading the lasgun, and the yellow is for tazer balls, I just used disabler as an example.

**Comment by Anoonki** [comment]
Space *AR-15s

* *it actually shoots super cool lasers*

**Comment by Spacemanspark** [comment]
Oh shit an M4 laser gun.
Give now.

**Comment by shazbot194** [comment]
New update, I got EMPs to work and made a prototype for a possible security version. 
3af55feb1fe84e17830b817c57f425ba
It has 30 rounds, does 15 damage on lethal, and 30 stamina damage on stun. This means it takes about 13 hits to kill someone, 10 to crit them, and 4 hits to stun someone.

I also improved the code some and icons should work a lot better.

**Comment by shazbot194** [comment]
Please everyone, give me some feedback so I can keep improving this pull. I will be working on some of the sprites to have some fit in better with other guns already in the codebase. I am also willing to keep adding features. They currently have all the functions of normal E-guns, even emp weakness, but I wouldn't mind giving them some more flair.

**Comment by taukausanake** [comment]
I want to say the security gun magazines look a little flat, but they really don't and it's weirding me out. It all looks good so far, I like it at least

**Comment by shazbot194** [comment]
The last update for the recharger code added EMP features for energy cells in rechargers, I realized this was rather vague after posting it.

**Comment by Allfd** [comment]
I strongly prefer this style to the current lasers.  These look like actual weapons as opposed to toys.

I am still a fan of lasers using actual casings, both due to realism, and balance.  But I wouldn't want the ideal to be the enemy of the good.

**Comment by Fox-McCloud** [comment]
While the concept is interesting, this still has a *lot* of duplicated code that's unnecessary. As went over earlier, this can largely be self-contained as listed here: 

https://github.com/tgstation/tgstation/blob/master/code/modules/projectiles/guns/ballistic/automatic.dm#L423
https://github.com/tgstation/tgstation/blob/f7c38a228d3be6a96a155dda56608c620ac8b85f/code/modules/projectiles/boxes_magazines/external_mag.dm#L381
https://github.com/tgstation/tgstation/blob/a0c435c765cbf41e0047042b7666f465b5ab395d/code/game/machinery/recharger.dm#L127

It would be better, if you should wish to continue working on this, to base the design off of the above code, as to avoid code duplication and messiness.

**Comment by shazbot194** [comment]
Fox, are you looking at the mark one code? I did remake it to follow the example you gave and then built on it so it wouldn't be missing several of the features inherent to laser guns. There isn't even that much duplicate code minus the initial values. Hell, it even takes EMP damage. Unless you mean just directly port the /TG/ code without adding any features, I think I already have.

**Comment by shazbot194** [comment]
I am closing this PR not because I want to stop working on it, but for several smaller, more annoying reasons. The biggest two are that the code has become kinda unworkable with github not wanting to sync anymore, and I want to work on other PRs for Paradise. So while this one will be closed, be on the lookout for the sequel to this PR, Shazbot's Armory.

**Pull request closed without merging**
