### PR TITLE
Paradise's soul removal part 2.5: rest of security

### PR DESCRIPTION
**Pull request by ElorgRHG**
## What Does This PR Do

Continues what https://github.com/ParadiseSS13/Paradise/pull/19333 did
resprites the rest of the security stuff, so, suits, hats, belts, the stuff, did this so new sprites wouldn't clash too much with the old.

Port of many TG PRs, adjusted to fit here.
## Why It's Good For The Game

SOUL BAD
BOTTOM TEXT

but really refreshing Paradise's sprites is really what this codebase needs in my opinion. 

## Images of changes

Ho boy,

in short: what you spawn with by default, small drip adjustments bottom:
(yes the warden now starts with the blue jacket, I never liked how they started with a blue hat and a blue jacket, the red jacket is still in the locker)

image

More images in details, just officers since the HoS and warden don't have much options compared to officers so the image above suffices.

<details>

Arranged what I think are the most interesting parts of the resprite.

image

For my sanity sake, I'm not going to arrange every single combination here, I'm sorry, if you want me to arrange a specific combination either ask in the comments or ping me on discord, thanks!

</details>

## Testing

Spawned as sec roles, took stuff from SecDrobes, was happy with desouled sprites, also arranged images in ` Images of changes`

## Changelog
:cl:ElorgRHG, OctusGit
add: Security variants of the bulletproof and riot armors.
tweak: The warden now starts with their blue jacket.
imageadd: Resprited security suits, belts and hats.
/:cl:

Also deletes some duplicate sprites in the files.

The security variants of the armors had to have been mapped in and touch _all_ maps, I can be kicked from the map queue if its required.

_Medical mains, you're next_

### CODE REVIEW

**Comment by S34NW** [comment]
HoS armoured shawl?

**Comment by ElorgRHG** [comment]
> HoS armoured shawl?

Now the thing with shawls/mantles is that I planned on respriting them all in a single PR when the neck slot PR would get merged... now seeing that that did not happen I'm gonna either wait a bit for the third time's a charm neck slot PR to pop up or the solution GDN was supposedly working on.

If neither of these happen, I'll resprite them as suit items somewhere down the line. But it remains unchanged in this PR, and out of all the mantles, the HoS one looks _fine_ so I dont think it conflicted much quality wise with the new sprites.

**Comment by ElorgRHG** [comment]
Species variants done, PR ready.

**Review by S34NW — APPROVED** [review]
Please keep doing these I love them

**Comment by ElorgRHG** [comment]
Will wait for the economy PR to get merged to resolve conflicts, no much point in doing this now since its being held up anyways.

**Review by SteelSlayer — APPROVED** [review]
This now leads the map queue for all stations (though it's not holding up anything for the moment). 

LGTM.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
