### PR TITLE
Make lockers use forceMove()

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Makes lockers use forceMove(), to ensure light sources inside them update properly.

### CODE REVIEW

**Comment by Regen1** [comment]
Why are so many lockers being deleted?

**Comment by Markolie** [comment]
They're not in the game. Those are unused.

**Comment by Regen1** [comment]
Unused in the map maybe, doesn't change the fact that you're removing them

From wiki
> Please document and explain your pull requests thoroughly. What each commit changes and why. We do not want to have to read all of your commit names to figure out what your pull request is about.

**Comment by Markolie** [comment]
These files have literally been unused for three years now. It's a code clean-up. They are not even being compiled in the code: if you'd try to enable the files in the dmi they'd throw errors. There's absolutely zero use in keeping them around, and it's not even worth mentioning them.

**Comment by Regen1** [comment]
TBH I don't care that they were unused, I just am a bit iffed that you didn't include it in the PR, as you are supposed to

**Comment by Markolie** [comment]
If a change has absolutely zero user-facing effects, I'm not going to mention it on the PR as there's zero use in doing so.

**Pull request merged**
