### PR TITLE
Adds in Unathi Tail Wagging

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in Unathi Tail Wagging

unathiwag

Pretty self-explanatory; due to the tail wagging system I implemented in an earlier PR, this was super easy to do.

Credit to Full of Skittles for the animation!

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1: about time Unathi get some love.

**Comment by ZomgPonies** [comment]
Slow down the wagging please, to make it feel different from Taj and more wizardlike. Something like wag left, pause, pause, pause, wag right pause pause pause. So it's more of a tail swish than a wag if you know what I mean.

**Comment by tigercat2000** [comment]
swish wag swag 

detachable tails when
:+1: :P

**Comment by Fox-McCloud** [comment]
You'll have to talk that over with Full of Skittles about that one--it is already slower than Tajaran tails, currently.

**Comment by ZomgPonies** [comment]
Why skittles? You don't know how to add pauses in animations?

As for behavior, just youtube lizards. They dont wag their tails in any way similar to mammals.

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

Nope; I almost never touch sprites, at all--and yeah, I realize that it's very different.

**Comment by ZomgPonies** [comment]
Downloading the dmi, I'll fix it up then send it back to you

**Comment by RemieRichards** [comment]
@Fox-McCloud each frame has a delay, just extend it on certain frames.

**Comment by Fox-McCloud** [comment]
@RemieRichards 

Thanks--yeah, I was just informed of that, appreciate it though.

Either case, updated it; Ponies added in a proper delay.

**Comment by RemieRichards** [comment]
@Fox-McCloud thanks, but I'll stick with the original animation (Had to do some edits to suit /tg/ lizards)
I can copy the delays at a later point if we want them.

**Comment by Krausus** [comment]
Are those... compression artifacts? In a GIF?
unathiwagging
I recommend GifCam for giffing.

**Comment by KasparoVy** [comment]
Hell yeah! Wicked to see this getting added in. Awesome stuff!

**Pull request merged**
