### PR TITLE
Exam Room Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Tweaks the Exam room a bit

- Adds in an advanced scanner
- Adds in some medical supplies to the pharmaceutical cabinet
 - stuff like painkillers, insulin, charcoal, bandages, etc.

- Exam room has its own special closet now
 - Closet has basic medical supplies for a doctor in addition to 1 of each type of medical kit.

Should be a fairly viable place to take in base level patients now.

### CODE REVIEW

**Comment by tigercat2000** [comment]
There are already three body scanners in medbay, I don't see why we need a fourth in the exam room. The rest of it seems pointless as I have never seen it be used for any actual patients being dealt with, but whatever.

**Comment by Krausus** [comment]
> Adds in some medical supplies to the pharmaceutical closet

You mean the "pill cabinet" that had literally nothing but a single spaceacillin syringe in it? I always wondered what was up with that.
> Closet has basic medical supplies for a doctor in addition to 1 of each type of medical kit.

Two brute kits, actually. Also, isn't a defibrillator a bit excessive for an examination room? If someone needs defibrillation, they're well past the point of a typical examination.
> There are already three body scanners in medbay, I don't see why we need a fourth in the exam room. The rest of it seems pointless as I have never seen it be used for any actual patients being dealt with, but whatever.

That's kinda the whole point. Nobody used it because *the room was useless.* All three existing body scanners are clustered near the very back of medbay (and two of those are meant for surgery use anyway), which made scanning people rather inconvenient. This makes the room actually good for something.

**Comment by Fox-McCloud** [comment]
Oops; only meant to be one kit.

Also, I gave them a defib because--well; I was trying to model this somewhat after a clinic/doctor's room---and a decent amount of them have one of those little defib units around. Obviously giving them a compact defib would be kinda unfair/OP, so this was the next best thing.

**Comment by ZomgPonies** [comment]
Defibs are already one of the most OP objects in the game. I want to keep the total amount of them on station low. As in, 1-2 max for the whole station.

**Comment by Fox-McCloud** [comment]
defib removed.

**Comment by Krausus** [comment]
> Defibs are already one of the most OP objects in the game. I want to keep the total amount of them on station low. As in, 1-2 max for the whole station.

Well, medbay gets 4 in addition to the CMO's compact defib. I'm not sure what the big deal is, though - they're fairly picky about damage and time of death, and don't fix any other problems a dead person usually has, so they're often worse than simply cloning someone.

**Comment by Deanthelis** [comment]
Strange Reagent and a bunch of Synthflesh work several times better than a defibrillator. Even just SR + cryo bath. Seriously, defibs are absolutely monstrous, and a lot of the time, you're better off cloning them anyway because the time they'd spend in surgery having their bones and organs repaired is much longer than the 3-5 minutes cloning+cryo takes. I'm not sure what all the fuss is about or why they're 'one of the most OP objects in the game' at all, I can think of several that beat it in spades.

Not to mention, R&D can print off as many defibrillators as Medbay wants, and can do so easily five minutes into a round with a competent RD. Seriously, 3 Mounted Syringe Guns and DEFIBS FOR EVERYONE! And handheld crew monitors, but that's another gripe of mine, and unrelated to this PR.

**Pull request merged**
