### PR TITLE
Add's Desolate's custom borg sprites.

### PR DESCRIPTION
**Pull request by Crazylemon64**
basic
mecborg
minerborg
secborg
test
Janitor and Combat are copies of existing sprites; Service has identical appearance to Standard

### CODE REVIEW

**Comment by DesolateG** [comment]
Hellz yeah

**Comment by taukausanake** [comment]
Give service a top hat. It NEEDS a top hat like the old service borg. Also, we have a janitor sprite that matches these?

**Comment by Fox-McCloud** [comment]
@FreeStylaLT

**Comment by FreeStylaLT** [comment]
👌

**Comment by SigholtStarsong** [comment]
...Dangit, now I want a Mr. Handy/Mr. Gutsy borg sprite!

**Comment by DesolateG** [comment]
I'll work on a janitor and service sprite to throw in later.

**Comment by DesolateG** [comment]
Also, @Crazylemon64 please give credit to IgnisCorvus for the sprites.

**Pull request merged**
