### PR TITLE
Nifty animated UI's

### PR DESCRIPTION
**Pull request by Tastyfish**
It's almost like porting tgui for 1/8 the effort. :fish: 

Preview
Preview
Preview

:cl:
experiment:  Progress bars, buttons, and several of the values in UI's are now animated.
/:cl:

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
Aw yiss :+1:

**Comment by Spacemanspark** [comment]
Yes.

**Comment by razekpraxis** [comment]
I.. literally just suggested this

**Comment by Regen1** [comment]
Someone give this man a medal

**Comment by tigercat2000** [comment]
fucking magical :clap:

**Comment by Glorken** [comment]
11/10

**Comment by fludd12** [comment]
Everyone is happy with this.

**Comment by sasanek12** [comment]
Yisssss :+1:

**Comment by Fox-McCloud** [comment]
=D

Thanks so much, @Tastyfish literally the best thing ever (for NanoUI anyway).

**Comment by Iamgoofball** [comment]
just port tgui

**Comment by Spacemanspark** [comment]
No

**Comment by tigercat2000** [comment]
@Tastyfish could you do the smooth button transitions too 
i mean not to push you to do any more this is fucking awesome

**Comment by PJB3005** [comment]
@Iamgoofball sure when it stops being useless at client performance.

**Comment by Dumbdumn5** [comment]
THIS IS FUCKING MAGIC :+1: :clap: :skull:

**Comment by Tastyfish** [comment]
@tigercat2000 You mean the animation when you hover on the link? maybe

**Comment by tigercat2000** [comment]
@Tastyfish iirc there's a fade when you click a button
so if you click a button and it turns green it doesn't do so instantly, it fades from blue to green

**Comment by Gummin** [comment]
:+1: :clap: x :100:
actually have been waiting for this for 3 years.

**Comment by PJB3005** [comment]
Now to make input tags not be reset.

**Comment by Tastyfish** [comment]
@tigercat2000 Button styles, hovering, etc now also animated. don't feel like making a gif since you probably get the idea.

**Comment by tigercat2000** [comment]
@Tastyfish 12/10 :heart: :blue_heart: :green_heart: :yellow_heart:

**Comment by PJB3005** [comment]
Honestly this makes it better than tgui IMO.

**Comment by CrAzYPiLoT-SS13** [comment]
Next step: animate progress bars

**Pull request merged**
