### PR TITLE
Buildable Deep Fryers

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Deep fryers can now be built and upgraded with some minor assistance from science.
- Board requires programming 2, just like the microwave and such
- 2 micro lasers + 5 cables
 - Upgrading the lasers decreases the cook time

:cl:
rscadd: Deepfryers are no longer arcane mysteries, and can be (de)constructed and upgraded.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
It looks like Fryers won't be


pre-baked anymore.

**Comment by FreeStylaLT** [comment]
You could say False has


cooked up yet another quality PR.

**Comment by fludd12** [comment]
These puns are
_fry_ing my patience.

**Comment by FreeStylaLT** [comment]
You can fry me a river.

**Comment by Spacemanspark** [comment]
That last one was really half-baked.

**Comment by FreeStylaLT** [comment]
This is becoming terrifrying

**Comment by TheDZD** [comment]
And I thought my ice puns were bad.

**Comment by Spacemanspark** [comment]
We baked the ice.
I sense some boiling water approaching.

**Comment by Lady-Luck** [comment]
meme pr

**Comment by FalseIncarnate** [comment]
This actually isn't a meme PR. Hawke just is a living meme.

**Pull request merged**
