### PR TITLE
Updates Delta Morgue [Ready]

### PR DESCRIPTION
**Pull request by Quantum-M**
Updates Delta Morgue to be nicer and more on par with the Cyberiad one.

## What Does This PR Do

Updates the Delta Station map to both be more in par with the Cyberiad morgue and making it nicer, instead of looking like some abandoned room.

## Why It's Good For The Game

Gives the Coroner a more nicer area (and tools such as the body scanner that is present in the Cyberiad but not in Delta)

## Images of changes

image

## Changelog
:cl: Quantum-M
tweak: Updates Delta Station Morgue to be more nicer and more on par with the Cyberiad Map.
/:cl:

### CODE REVIEW

**Comment by Quantum-M** [comment]
Marking this as Not Ready, I believe some elements on the map are outdated to the previous changes to Delta and I have to fix those.

**Comment by Quantum-M** [comment]
Checked on potential outdated map elements.

**Comment by BakKeener** [comment]
This looks great, I also love that you don't need to go into a maintenance room from medbay just to get to the morgue anymore.

**Comment by LightFire53** [comment]
A good expansion!

This scrubber shouldn't be placed on a disposal pipe due to the potential of atmospheric shenanigans, but if you flop it to under the table on the other side, you should be alright.

image

I'm also not sure we need to have an air alarm and a fire alarm on both ends of the morgue. Otherwise, looks fine to me!

**Comment by Quantum-M** [comment]
Moved the Scrubber, @LightFire53 

As to the air alarms and fire alarms, my reasoning to adding two of each is due to the Morgue being relatively big.

**Comment by AffectedArc07** [comment]
After a discussion within server leadership, we have decided to halt your PRs due to your use of multiple ckeys without informing server administration

```

Using multiple accounts for yourself during a round (Multikeying) is not allowed. Simply having multiple accounts, by itself, is permitted - but we require you to inform us so we can add a note that these accounts are both yours.
```

This block will be removed once the server administration have been informed of your alternative ckey.

**Comment by Quantum-M** [comment]
@AffectedArc07 

I have two ckeys, one as 'Bryanayalalugo', which I have always used for Paradise, and the other 'Quantum_m', which I have logged into paradise accidentally a few times as, but _shouldn't_ have any play time to it.

**Comment by AffectedArc07** [comment]
> @AffectedArc07
> 
> I have two ckeys, one as 'Bryanayalalugo', which I have always used for Paradise, and the other 'Quantum_m', which I have logged into paradise accidentally a few times as, but _shouldn't_ have any play time to it.

Info has since been added. PR block removed.

**Review by S34NW — CHANGES_REQUESTED** [review]
Hi, thanks for taking the time to touch up delta! You seem to have a minor issue however:
Two air alarms present in the morgue area, we only want one per area as per mapping standard.

**Comment by Quantum-M** [comment]
Air alarm removed, @S34NW

**Review by S34NW — APPROVED** [review]

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
