### PR TITLE
Adds "Muh Cliques" Graffiti

### PR DESCRIPTION
**Pull request by Iamgoofball**
Close reason was dumb so I re-opened it.

:cl:
add: Adds "Muh Cliques" Graffiti
/:cl:

Before you bitch, GPL is GPL is GPL.

00a52b36-62ea-11e6-9b53-09296cc167c9

### CODE REVIEW

**Comment by Necaladun** [comment]
I do have to admit it's funny as fuck.

The main thing I have against it is it's an OOC complaint I mainly see, I'm not sure if I can remember anyone ever saying it ICly, unlike shitcurity, etc. 

Overall it seems to be something that'll just encourage a shitty and toxic attitude towards people, and is just a bit too meme'y

**Comment by Iamgoofball** [comment]
did you just imply that graffiti can be "too memey"

also you shouldn't get legitimately offended by this, it's the spaceman equivalents to scrawling stupid shit on a bathroom wall.

**Comment by Mijhead** [comment]
Code is not dead which can eternal paste
And with strange PRs even cliques may die

**Comment by Necaladun** [comment]
I haven't been legitimately offended by anything in SS13. 

Memey might not be the best term - it almost feels like OOC in IC. I can't think of any graffiti that references such purely OOC complaints.

**Comment by IcyV** [comment]
It's a purely OOC meme/issue that will only be used for a long time to try and harass people that aren't even part of what it's supposed to referenced at. Two people hanging out for 5 minutes at the start of a shift before anything happens? Graffiti spam trying to rile them up because people still think they're hilarious. 

It just doesn't add anything beneficial. We really don't need more things that exist to insult people given the state of the community as is.

**Comment by Necaladun** [comment]
Thanks Icy, that's a better way of putting what I meant.

**Comment by Ty-Omaha** [comment]
@Iamgoofball  for a goofball you seem to get pretty passive aggressive over everything lol :smile:

And as I said when I closed it, this will just be used to harass people even more

**Comment by taukausanake** [comment]
Graffiti in general is used to harass people. Adding another one isn't going to change that. I personally think this is fine

**Comment by FlattestGuitar** [comment]
I have to agree with what Neca said. Clique complaints are purely an OOC thing, let's not add more memery for the sake of memery.

**Comment by Ty-Omaha** [comment]
>Graffiti in general is used to harass people. Adding another one isn't going to change that. I personally think this is fine

Not really, unless it's security.  I don't think I've ever seen anyone being "harassed" with graffiti

**Comment by taukausanake** [comment]
I made a pretty bar dance floor once and it got tagged up with graffiti. I was so sad. And I couldn't get any way nor a janitor to clean it

**Comment by Ty-Omaha** [comment]
>once
And you weren't harassed with graffiti from just being present talking to friends in the bar either, which what's going to happen with this.

**Comment by Davdichan** [comment]
No fleas allowed?

Spay N Neuter?

Bird Free Zone?

Solids Only?

No Monkeys?

Yip Yip?

**Comment by KingPhilipIII** [comment]
> I do have to admit it's funny as fuck.

Second. 
But yea, I think this is a bit too OOC to be put in. Gonna have to agree with them on this.

**Comment by Iamgoofball** [comment]
why does that bit of it matter? most the graffiti jokes are jokes about meme culture in SS13, memes from other games, or memes from movies and shit.

anyone who gets seriously offended over some graffiti needs to step back and rethink their status of being offended by pixels in a video game intended as a joke.

**Comment by IcyV** [comment]
>anyone who gets seriously offended over some graffiti needs to step back and rethink their status of being offended by pixels in a video game intended as a joke.

You keep trying to turn things like this into an argument of people being offended or not. I extremely doubt anyone is actually offended or will be offended in the slightest by this. What this does is just increase the toxicity of an already questionable issue that has, unlike other graffiti memes, absolutely no basis or root in the IC culture of a round. When you aren't an active player within the community, it seems a bit odd to come into this and try to put in very questionable content when you won't need to deal with any of the repercussions. 

There absolutely is no benefit or gain to be had from this other than the argument of "memes." That's just not a solid enough argument when the reasons against it are very clear and very real. 

Though, the list of things David suggested would be amazing to have. Actual sensible things that are related to something that actually exists on the server in an IC form.

**Comment by Iamgoofball** [comment]
But, cliques are an IC thing that occurs in every server and is directly relating to crewmembers hanging out together? It's the definition of IC. It refers to crewmembers who hang out all the time and help eachother out mostly.

>any of the repercussions.

What repercussions? The only repercussions that could come from this are if you guys MAKE issues about it.

**Comment by IcyV** [comment]
>It refers to crewmembers who hang out all the time and help eachother out mostly.

Definitely not. The "cliques" meme is very related to particular players always playing together in very questionable ways. It grew way out of proportion into this meme. Nobody cared a single bit about "cliques" and this sort of thing to this degree before.

>It's a bit of harmless fun injokes among all of ss13 servers.

It's a lot more than just "harmless fun" on this specific server. It's a very Paradise specific issue that other servers usually don't need to deal with.

I think we'll just need to agree to disagree on the issue given our different experiences.

**Comment by tigercat2000** [comment]
@IcyV it's definitely not just a paradise issue

**Comment by IcyV** [comment]
@tigercat2000 That was phrased poorly. I was referring to the clique meme. I've yet to see any other server so frothing at the mouth at the concept of a clique instead of just frothing at power/meta groups.

**Comment by KasparoVy** [comment]
It's just a graffiti, it's pretty funny, merge when? Fits right in with the rest of the graffittis we got to choose from. Nothing wrong with it.

**Comment by fludd12** [comment]
Considering we have a literal dorf and uboa, I don't see how this is nearly as memey as some of the graffiti.

**Comment by Ty-Omaha** [comment]
The difference is the other graffitis aren't used to harass people just standing around talking in the bar, which is what people will do with this graffiti. It's not people getting "offended lelz", it's the fact that they're going to be constantly harassed with this.

**Comment by Doukhan** [comment]
There's a shitcurity graffiti, this immortalises something else just as fittingly.
"Harassment" isn't anything that can' be dealt with IC.

**Comment by Davdichan** [comment]
Don't we also have cyka graffiti?

**Comment by Ty-Omaha** [comment]
Shitcurity graffiti is targeted towards a specific *depeartment* , not specific *players*

**Comment by fludd12** [comment]
Cyka doesn't target a specific department, and by definition, making fun of cliques cannot make fun of a specific player.

**Comment by Ty-Omaha** [comment]
Go to bar, see vulp talking, draw muh cliques around them
Round end
New round
Go to bar, see same vulp talking, draw muh cliques around them
repeat.
Or maybe someone else will go up to them and do that next round?

And player>**s**<

It *specifically* targets players who frequently hang out in the bar and talk to their friends in furpersonspeak.

**Comment by fludd12** [comment]
Not unless used like that, in the exact same way you can spray Cyka Blyat around anything vaguely russian, or "Vox are Pox" next to any Vox clique. Hell, we have "Muh Valids" and "Catbeasts Here" as sprays, too.

**Comment by Necaladun** [comment]
I don't see anything positive from this except enabling and encouraging harassment. 

Complaining about "muh cliques" can be taken to reddit. There is no reason to I see to allow it in an IC fashion.

**Comment by Iamgoofball** [comment]
so why would a player get legitimately offended over some greyshit walking up with a spraycan and spraying some shit about cliques on the ground?

why don't you beat their ass with a bar stool for being a dick?

this creates IC interactions

the only time anything OOC would be happening here is if you make it OOC out of your inability to fight your own battles

**Comment by Iamgoofball** [comment]
literally just go slug the guy in the face if he's spraying muh cliques shit next to you and you don't like it, that's roleplay

**Comment by taukausanake** [comment]
> why don't you beat their ass with a bar stool for being a dick?

We don't have this yet. :( We need it

**Comment by Mijhead** [comment]
On soft gray mornings furries cry;
The greytide shares a joke;
I run to grasp a spraying can;
To harass the furry clique;
The neon vulpa does not play;
But merely sits in bars;
And frowns as the graffiti builds;
In the court of the Bartender

**Comment by Rumiluntti** [comment]
Are people being SERIOUSLY offended by a fucking graffiti? Holy shit

**Comment by tigercat2000** [comment]
no one has been offended so far, but like 20 people have complained that this is too meta

**Comment by TheDZD** [comment]
Cyka isn't a graffiti that's available, but all of the following are: borgs rogue", "shitcurity", "catbeast here", "vox are pox", "securites eunt domus", "don't believe these lies", and "muh valids".

I honestly don't see a big difference between covering the bar with "muh cliques" and covering sec with "muh valids". It hardly qualifies harassment, and you'd have to be extremely thin-skinned to actually get offended by it.

**Comment by Vivalas** [comment]
When "muh valids" is a graffiti spray, you lose all footing for the "too meta" argument. This is obviously contested because of the numerous fur players on paradise that are offended by it. I agree it's pretty fucking funny but otherwise don't care if it gets merged or not. Just at least call it what it is.

**Comment by Iamgoofball** [comment]
@taukausanake fix this ASAP

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

He's incorrect; you've been able to pick up barstools for a while now and beat people over the head with them.

**Comment by Iamgoofball** [comment]
then there is no excuse

get those bar fights ready boys

IC conflicts, roleplaying situations around

**Comment by Deanthelis** [comment]
I see two camps. Allow me to suggest some constructive solutions to be selected by whichever side wins the argument.

Camp A: The graffiti is offensive and too meta. Solution: Replace all graffiti with the word 'GRAFFITI'. There is nothing meta as it is ICly graffiti, and there is nothing offensive about the word 'GRAFFITI' because it does not contain any meaning.

Camp B: Being offended is an IC issue, and there are already meta sprays anyway. Solution: Replace all graffiti with 'FUCK YOU', as it is far more direct and there will not be any confusion as to the meaning. It is also entirely an IC issue, and it will still not offend anyone in an unfair way, because 'FUCK YOU' is a very versatile phrase. In this way, aspiring graffiti artists can be as efficiently offensive as possible, without making anyone feel singled out.

**Comment by Necaladun** [comment]
No one has actually said they find this offensive. This is not the issue. I'm not sure why people keep bringing it up. Is it to infantalize those who disagree with them, are you unable to see how someone can dislike something without being offended by it, or is it something else?

This only serves to encourage a toxic mindset and endorse harassment of people for ooc reasons. As the screenshot clearly shows, it's aimed at furries, and so that people can harass perceived furry cliques.

This is not the atmosphere I want to encourage for the server.

I don't think the "muh valids" is a particularly good thing to have either, btw.

**Comment by Iamgoofball** [comment]
People are arguing that people in the future will be offended, therefore someonenfinds it offensive  by their logic.

**Comment by Iamgoofball** [comment]
This PR is not aimed at furries, this is aimed at all cliques. I lifted the example picture from the previous Pr

**Comment by Ty-Omaha** [comment]
No. People are arguing that people will be harassed constantly.  And yes this is aimed at the vulp who hang out at the bar and talk in vulpspeak, literally nobody complains about any other "clique" except for vulp cliques.

**Comment by Iamgoofball** [comment]
Not in my judgment and not in my PR. This is aimed at cliques everywhere.

Also have you considered taking IC steps against people harassing you yet? Stop dodging this question.

**Comment by Ty-Omaha** [comment]
Well given how you're not an active player within the community of course it wouldn't be in your judgement.

IC steps? You mean the ones that will get people arrested for breaking space law?

**Comment by Necaladun** [comment]
As I said, this is not the kind of culture I want for the server. Having to assault people - and probably serve brig time - will not stop such harassment. It's not the response I want to have to give to people feeling harassed. I'd prefer such harassment doesn't happen at all.

Such harassment is not done for IC reasons. It's done due to OOC dislike of furries and cliques. People who enjoy harassing others for such reasons are not welcome on the server. 

I would say if you don't like the culture of the server, find another - but that's not an issue, as you don't play here at all. Your interests here are shitstirring and trolling, not a positive contribution to the environment and culture of the server.

**Comment by Iamgoofball** [comment]
I think you're getting too angry over the potentials  here. It's just another shitty graffiti spray.

**Comment by Fox-McCloud** [comment]
After some internal discussion this has majority headmin disapproval. Closing this.

**Comment by Iamgoofball** [comment]
Overreaction. People shouldn't white knight.

**Comment by tigercat2000** [comment]
Get over yourself, goofy.

**Comment by Iamgoofball** [comment]
Them first.

**Comment by Iamgoofball** [comment]
Them first.

**Comment by Iamgoofball** [comment]
Whoops

**Pull request closed without merging**
