### PR TITLE
Removes Catwalks from SM Pipes and other injectors around DeltaStation and MetaStation Engineering

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Was requested to remove the catwalks from the SM cooling loops on DeltaStation and MetaStation due to how they process atmospherics. Also removes catwalks from injector ports on MetaStation. All removed catwalks were replaced with lattice.

## Why It's Good For The Game
Atmospherics simulator should process atmospherics properly, in ways we desire.

## Changelog
:cl:
tweak: Replaces catwalks with lattice from DeltaStation SM cooling loop
tweak: Replaces catwalks with lattice from MetaStation SM cooling loop
/:cl:

### CODE REVIEW

**Review by S34NW — CHANGES_REQUESTED** [review]
Catwalks are not turfs, they are objects just like lattices. This means they don't touch or change atmos stuff at all, which is handled by the space turf underneath...
The whole premise for this PR seems a bit dubious.

**Comment by Fox-McCloud** [comment]
need to review this.

**Comment by DeveloperLoser** [comment]
> Catwalks are not turfs, they are objects just like lattices. This means they don't touch or change atmos stuff at all, which is handled by the space turf underneath...
> The whole premise for this PR seems a bit dubious.

This, I made a max EER burn mix SM and covered the HE pipes with catwalks, worked just fine.

**Comment by LightFire53** [comment]
I had done this at the request of Denthamos, citing plasma fire issues. This has since been debunked as other madness, so at most this is now cosmetic/parity with box.

**Pull request closed without merging**
