### PR TITLE
Fixes Decalocks in abandoned crates

### PR DESCRIPTION
**Pull request by IK3I**
Refactors the lock code so it actually does what it's supposed to do when hit with a multitool. Enjoy your now fully functioning mastermind style minigame.

:cl:
fix: Using a multitool on a decalock now gives usable info
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
Doesn't compile.

**Comment by Citinited** [comment]
:+1: though I personally use gibtonite to open my lockers

**Comment by Kerroman** [comment]
@Citinited 
I don't like messing with gibtonite so I just shoot the crates with whatever kind of kinetic accelerator I have on hand.  Takes like 12-16 shots and you're in.

**Comment by Spacemanspark** [comment]
That's no fun.

**Pull request merged**
