### PR TITLE
Makes Metastation Fastmos ready.

### PR DESCRIPTION
**Pull request by SamHPurp**
This was a pain in the testicles.

~~Screenshots coming, of the map, not the testicles.~~

image image image image
image image image image image image image image image image image

:cl: Purpose2
add: Metastation is now fastmos ready with cycling airlocks.
/ :cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
> Screenshots coming, of the map, not the testicles.

Why not both?

**Comment by LightFire53** [comment]
scissor eggplant

**Comment by FreeStylaLT** [comment]
Oh christ this must have been a pain

**Comment by DesolateG** [comment]
Thank god

**Comment by Twinmold93** [comment]
Airlocks aren't as bad to do as people think, it's just hard if you have no idea what you are doing, like everything.

**Comment by Fox-McCloud** [comment]
First off, apologies for letting this sit here for so long. Unfortunately, due to the nature of cycling airlocks making them a maintainability pain in the ass, along with rather arcane and archaic code, it was seen as preferable to keep Meta's current non-cycling double airlock system

**Comment by taukausanake** [comment]
Can't wait to play on Metastation with Fastmos merged

**Comment by SamHPurp** [comment]
@taukausanake Yeah, I'm not happy with this.

The issue with Airlocks is that they are annoying to build in the map editor. That first and foremost is the biggest issue.

I've eliminated that issue by doing this.

Oh well...

**Comment by taukausanake** [comment]
Yeah, saying something is a "maintainability pain in the ass" is not a good excuse when there are people willing to do the work no one else wants to do. Or are just masochists. Isn't that one of the requirements to developing anything?

If it didn't take so much space I'd like to see the Toxins launch chamber turned into a cycling chamber. Think that could be done with windoors and glass? The magic fan is okay but I like having more function than easy

**Pull request closed without merging**
