### PR TITLE
Fixes a ton of bugs and annoyances with Box

### LINKED ISSUE #17810: Cyberiad HoS Office lacks electrified space-facing windows
**Issue Description**:

The Cyberiad HoS Office lacks cables under the windows bordering space, thus leaving the window grilles electrified.
image

**What did you expect to happen**: 

The HoS offices on Delta and Meta both have their space-facing windows electrified, and it just makes logical sense for one of the most secure parts of Brig to have this protection - especially when it's a tile away from Security's best hardsuit.
image
image

**What happened instead**:

As stated above, windows lack electrified grilles.

**Why is this bad/What are the consequences**:

Inconsistencies between maps for one thing, additionally makes poor sense for every single other window in Cyberiad's brig (not counting the ones in Brig Bathroom) to be shocked but not the HoS's windows.

**Extra information**:

I asked on #mapping if this was an intentional balance decision and it seems it's not, so I'm assuming it was a mapping oversight. If this was intentional, please disregard and close this.

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Fixes pipes running under vents(which can cause runtimes random linking to the scrubber network!!! or so I am told)

Moves most lights/cameras placed on windows

Fixes areas in the wrong place

Var edited shutters/blastdoors not using their proper preopen subtype have been fixed

Fixes general mapping errors with Box

Made it so biohazard and Xenobio aren't constantly dumping the waste loop into space(which is a leftover from a time when xenobio had its own independent scrubber network shhh)

CRYO CONSOLES AND PODS USE DIR NOW!

Also, I didn't fix anything that there is an open PR to fix so yeah

Fixes #17810 
## Why It's Good For The Game
die mapping bugs die

## Images of changes

<details><summary>VENT FIXES</summary>

before
pipefixbefore1
after
pipefixafter1
before
pipefixbefore2
after
pipefixafter2
before
pipefixbefore3
after
pipefixafter3
before
pipefixbefore4
after
pipefixafter4
before
pipefixbefore5
after
pipefixafter5
before
pipefixbefore6
after
pipefixafter6
before
pipefixbefore7
after
pipefixafter7
before
pipefixbefore8
after
pipefixafter8
before
pipefixbefore9
after
pipefixafter9
before
pipefixbefore10
after
pipefixafter10
before
pipefixbefore11
after
pipefixafter11
before
pipefixbefore12
after
pipefixafter12
before
pipefixbefore13
after
pipefixafter13
before
pipefixbefore14
after
pipefixafter14
</details>

<details><summary>AREA FIXES</summary>

before
before
after
after
before
before5
after(pretty sure nearstation should only be applied to structures not objects which is how tg does it)
after5
before
before6
after(see above)
after6
before
before7
after(passive vents don't need power :) )
after7
before
before8
after
after8
before
before9
after
after9
before
before27
after
after27
before
before30
after
after30
before
before50
after
after50
before
before51
after
after51
before
before52
after
after52
</details>

<details><summary>LIGHTING AND CAMERA FIXES</summary>

before(FLOATING LIGHT)
before31
after
after31
before
before32
after(moving lights/cameras off windows when we can get away with it is best, unless you like floating lights when a window gets smashed)
after32
before
before33
after
after33
before
before34
after
after34
before
before35
after
after35
before
before36
after
after36
before
before37
after
after37
before
before38
after
after38
before
before39
after
after39
before
before40
after
after40
before
before41
after(yes i see the buttons on the window, i don't care)
after41
before
before42
after
after42
before
before43
after(also bigger door now to fit in with the windows if you didn't notice)
after43
before(jesus)
before44
after(deleted)
after44
before
before45
after
after45
before
before46
after
after46
before
before47
after
after47
before
before49
after
after49
before
before54
after
after54
before
image
after
image
</details>

I hit the upload limit for git... oh my god. If you got to this early hold on I'll post the rest of the changes in a comment below
## Changelog
:cl:Bmon
fix: Many area and bug fixes on Boxstation
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
**EVERYTHING ELSE**

before(there used to be a pipes here when I first started playing. it's long gone now and all that remain are these meters)
before2
after
after2
before(a leftover from when xenobio had its own scrubber network)
before3
after
after3
before
before4
after(it's not longer dumping the waste loop into space by default, atmos can handle it)
after4
before
before10
after(var edited iconstate foam dispensers BEGONE)
after10
before
before11
after(same as above)
after11
before
before12
after(using correct subtype now instead of varedit)
after12
before
before13
after(same as above)
after13
before(someone used half iconstate dirty floortiles half actual cleanable dirt)
before14
after
after14
before(again with the iconstate dirty floor instead of actual dirt. iconstate dirt floor tiles are very old and really shouldn't be used since you can't clean them)
before15
after
after15
before
before16
after(same as above)
after16
before
before17
after(same as above)
after17
before(dir should be 2 by default)
before18
after
after18
before
before19
after(kabam now you can clean the floors)
after19
before
before20
after(more dirt tiles being replaced by cleanables, also, moved the stool to face the consoles)
after20
before
before21
after(same as above)
after21
before
before22
after(same as above)
after22
before
before23
after(same as above)
after24
before
before25
after
after25
before(two dirt stacked on top of each other
before26
after
after26
before(Look how ugly this looks, right? Well...)
before28
after(...I put lattice under all the solar arrays to stop that from happening, they all look much cleaner now)
after28
before
before29
after
after29
before
before48
after
after48
before(two lattice on top of each other, will bug out and not spawn a lattice)
before53
after
after53
before(as you can see this does not work and will bug out and not spawn a lattice)
before55part1
before55part2
after
after55
before(looks VERY ugly and has nothing under it)
before56part1
before56part2
after(put airless plating under it, way better)
after56part1
after56part2
before(pipe under window)
before57
after
after57
before
before58
after(same as above)
after58
before(lattice ontop of lattice)
before59
after
after59


That's it. Sorry I can't put images into a spoiler(i think? at least I tried it and it didn't work) github is just garbage like that

**Comment by CinnamonSnowball** [comment]
It would seem some of the "pipes running under vents/scrubbers" situations were actually placed that way to keep the vents/scrubbers symmetric within the room, or to otherwise gain some extra room appearance points. Will be a bit sad to see that go but I guess it's the lesser worry if the alternative can indeed bug out the pipenet.

**Comment by Bm0n** [comment]
> It would seem some of the "pipes running under vents/scrubbers" situations were actually placed that way to keep the vents/scrubbers symmetric within the room, or to otherwise gain some extra room appearance points. Will be a bit sad to see that go but I guess it's the lesser worry if the alternative can indeed bug out the pipenet.

Can you tell me which vent it is? I can maybe run the pipes a different way to keep the look the same.



also, I missed one area

image

Here's what it looks like now in my latest commit

image

**Comment by Bm0n** [comment]
found one more missing nearstation I found while fixing some weird compile thing
image
after
image

**Comment by Bm0n** [comment]
sorry for making more commits but I found one more case of decal stacking and latticeless grille's

decal stacking bad
DIRT

this looks ugly and floaty without lattice running under it
image

now fixed :)
image

I should hopefully(please) be done now

**Comment by Bm0n** [comment]
these potted plants get sucked up by the wall-mounted oxygen lockers at round start. The plants are now gone.
image

**Comment by Bm0n** [comment]
The HoSes office is now shocked
image

The prisoner lockeroom door leading to the gulag now has the same access settings as the main door
image

**Comment by Bm0n** [comment]
this body scanner is facing the right way now
image

flipped the gun stacking in the armoury so that they stack properly
image
AFTER
image

also moved the warning signs off the cuttable grilles and onto the more permanent walls.

connected the lattice in between the armoury and wardens back office
image

I have had to deconflict this PR **twice** now manually since this PR covers a lot of the station. I don't mind deconflicting stuff, but I worry that I might miss something along the way since this refractor is so big. If your PR was one of the PRs I had to deconflict with I'd greatly appreciate it if you checked to make sure I didn't miss anything, namely #17606 and #17624

**Comment by Bm0n** [comment]
This camera is no longer on the glass window due east
image

ATMs now use the correct X/Y pixel shift and are consistent with meta and delta

A var on an O2 locker near EVA has been fixed

**Comment by Bm0n** [comment]
Fixed the invincible window and rogue pipe at the south old bar
image

**Review by S34NW — APPROVED** [review]
LGTM

**Comment by Bm0n** [comment]
Hopefully the last thing.

Turbine. Pumps are now using the on subtype instead of varedits
image
Same with this atmos room near brig
image
And at incin
image

**Comment by Bm0n** [comment]
The Garden has been missing a tile under its door forever. It's fixed now.
image

**Comment by Bm0n** [comment]
The SM output is now using the on subtype. I Tripple checked to make sure the vars for volume and everything else are the exact same as before and test ran the SM on a local server. It should be good.
image

**Comment by Bm0n** [comment]
The layering for this warning stripe at the gateway was messed up
image
Fixed it now
image

I am sorry I keep making commits, I just keep finding more and more every time I decide to play a round or two on Para now that I am looking out for this type of stuff.

**Comment by Bm0n** [comment]
Viro areas cleaned up. Red is now a part of virology lobby area, blue is now fully virology lobby instead of half virology lobby and half patient ward
one last fix

**Comment by Bm0n** [comment]
This one must have slipped me when I was going through all the cams. Moved two tiles east
image

**Comment by Bm0n** [comment]
Cryo dorms had no intercom, fire alarm or air alarm. This is against our mapping standards and has been fixed.
image

**Comment by Bm0n** [comment]
Cleaned up the button nudges on the arrivals airlock. Placement is the same just the nudges have changed
image

**Comment by Bm0n** [comment]
Is now off the window and on the wall
image
This stool now has the correct dir and is facing the table
image

**Comment by Bm0n** [comment]
Camera and zone fix

BEFORE
image
AFTER
image

**Comment by Bm0n** [comment]
Both the mime and clowns offices had access points 46(Theater) instead of 43(Clown) and 44(Mime). This has been changed so no more mime breaking into the clowns office to steal their statue

**Comment by Bm0n** [comment]
This was nearspace when it shouldn't have been. Fixed now
image

Layering on the windows was kind of scuffed at the pool and music area in dorms. It is fixed.

**Comment by Bm0n** [comment]
there were a ton of doors around the newer parts of aft maints that didn't have proper maintenance access set. This is now fixed

**Review by S34NW — APPROVED** [review]
Looking back over it, all seems fine to me now.
<details>
  <summary>But, tut tut 😝 </summary>

image

</details>

**Review by AffectedArc07 — APPROVED** [review]
This is queue jumping

**Pull request merged**
