### PR TITLE
Port Mineral golems and Free Golems

### PR DESCRIPTION
**Pull request by datlo**
This PR ports mineral golems and free golems from tg. Free golems is a lavaland ruin. We don't have lavaland. Conveniently, tg's free golems are in a crashed shuttle.

freegolem8

This shuttle isnt crashed, here. It starts on its transit area and is locked until a free golem spawns and move it to one of its dock locations, which are : 

freegolem4
1. A new small asteroid on the telecomms zlevel. Small, but fairly rich in minerals, it's a safe way to start your mining and RND.

2. Above the abandonned mining station, at the top of the mining asteroid.

3. Close to the Derelict

The shuttle start with an autolathe, an ORM, a custom golem mining equipment vendor, mining gear crates and ore boxes, a special golem blueprints to claim new lands, a golem creation design disk, medkits, and various miscellaneous utilities. The mining vendor's extra items allow you to eventually make your own RND lab, botany, and xenobiology by yourself.

freegolem7

By default, there's a 75% chance that 4 adamantine free golem shells spawn on the ship, but cannot be spawned if the round is cult, wizard, nuclear, or blob. The % chance and restriction can be changed in the server configuration file.

If the shells don't spawn, the golem ship cannot be interacted with bar admin shenanigans.

Golems are now tougher with strong damage resistance (variable depending on material), and, to make mining less of a pain in the ass, are no longer slowed by the cold of space.
Golems now get golem-y names. Their stone face no longer hide their identity, showing them as "Unknown".

Mineral golems change how golems are made. You still use plasma dust on an adamantine extract, but now the reaction will give you a sheet of adamantine. This sheet can be used to craft a servant golem shell. Once you complete this shell with 10 of your prefered material, ghosts will be notified and can use the shell to become a golem, bound to their creator's will.

Depending on the material you use, you'll get a golem of the associated type. See below for the list.

Golems are able to use most completed golem shells to transfer their consciousness to a new golem body, in order to upgrade to a better or more appropriate material. This kills the previous body.

Free golems can create shells using metal in an autolathe with their unique design disk. These shells create new free golems.

List of golem types

- Adamantine : Leader, can resonate, speaking to all other golems
- Iron : No pros/cons
- Plasma : Flammable, explodes if burns too much
- Silver : Higher stun chance
- Gold : Less resist, higher movespeed
- Uranium : Irradiates nearby non-golems mobs
- Plasteel : Stun resistance, higher melee damage, low movespeed
- Titanium : Burn resistance
- Plastitanium : Higher burn resistance
- Diamond : Great allaround resistances
- Sand : Bullet invulnerability, great brute resistance, massive burn vulnerability, turns to sand on death
- Glass : Reflects lasers, great burn resistance, massive brute vulnerability, shatters on death
- Bluespace : Teleports to a random nearby tile on hit or when activated manually
- Plastic : Can ventcrawl if naked
- Wood : Regens in light, less brute resistance, can burn
- Abductor Alloy : Passive regeneration, faster movespeed, can only speak telepathically to other Alloy golems
- Bananium : HONK
- Tranquillite : ...

List of golems not implemented from tg, and if I'll add them in a later PR

- Runic : Maybe
- Bronze : Maybe
- Cloth : Probably
- Leather : Probably
- Durathread : Probably not
- Bone : Unlikely
- Clockwork : Maybe
- Capitalist : Unlikely
- Soviet : Unlikely

🆑
tweak: Reworked golems to use the ghost spawner system. Craft a golem shell with adamantine then apply 10 sheets of minerals to finish it.
add: Added golem subtypes. Each material has pros and sometimes cons. Type depends on the material used during construction.
add: Golems are now more resistant to damage and are no longer slowed by the cold of space.
tweak: Golems now get golem-y names.
fix: Fixed golem's stone face hiding their identity, showing them as unknown.
add: Added the Free Golems mob spawners and ship. Go do whatever.
add: Added a small asteroid on the telecomms zlevel.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
Yeah they do. That makes sense, i'll add it to the todo list.

**Comment by datlo** [comment]
I don't want the free golems to be something that pops up nearly every round. They're ported from a space ruin which has a % chance to spawn. If admins want the free golems to be commonplace, well, that's why I made the probability a config option, you can set it to 100% or 90% or whatever they think is best.

**Comment by datlo** [comment]
Golems now get their own IDs that only has access to the ORM. These IDs spawn in the mining gear crate and more can be printed using the mining vendor. They can be used to register your name and info on it.

The golem ship can now only be moved by golems, free or slaved. (I think cyborgs can still move it but that's fine.)

Claiming asteroid areas is now easier : You can use asteroid walls to define rooms with using blueprints, and once a room has been defined you can use floor tiles to place plating over sand tiles.

**Comment by Quantum-M** [comment]
I feel like the part on them getting the message from the liberator being "Yeah go do whatever" is a bit rather odd, otherwise 👍

**Comment by Dinarzad** [comment]
> I feel like the part on them getting the message from the liberator being "Yeah go do whatever" is a bit rather odd, otherwise

As I recall "the Liberator" is a Research Director. There's a statue to him somewhere an it;s identical to the RD statue you can make.
It's just a meme on how xeno sometimes makes golems an shit an just tell them to go do whatever/free them.

**Comment by Ralta** [comment]
Eyyyy. 

It's nice to have something to do when you're dead, and this is a chill way to get into various kinds of science without much risk to messing with the crew. 

I can see golems going to fuck with the crew on the regular (including fucking with T-comms), so admins may need to be a tad more vigilant with them.

**Comment by datlo** [comment]
Yeah the Liberator is just a research director that created them, that the golems started worshipping for freeing them.
There's a rule when you spawn mentionning that you should avoid interferring with the station for no reasons (can be seen in the PR's body), but maybe this'll need to be made into an explicit rule in the actual servers rules (follow your ghost role instructions.. something like that?). I ain't an admin tho so I'll let em decide how to best handle it.

**Comment by datlo** [comment]
Free golems can no longer spawn on cult rounds.
Changed the default % chance for golems to spawn to 100%. This still can, and perhaps should, be modified by admins using configuration file.

**Comment by MrMagolor** [comment]
Maybe there could be an admin button that allows the golem ship to dock near/at the station?

**Comment by datlo** [comment]
@MrMagolor Could be an idea for a later PR, but not in this one.

I added robotics, clown and mime access to golem IDs so golems can interact with robots/mechs.

Also added a couple of space cleaners to the ship since I don't think there's a way to make spray bottles and the ship was lacking a way to clean blood/dirt and whatnot.

As far as I can tell, all the bugs are fixed and all features are working, this PR is ready to be merged if there's no issues I missed.

**Comment by MrMagolor** [comment]
Are there bananium/tranquillite deposits on the tcomms asteroid? Otherwise the clown/mime access seems pretty useless.

**Comment by Pennwick** [comment]
I might be just missing it but I don't see any mining scanners. While you can mine without one its a real pain to do so. And if you hit Gibbonite near your ship you would have no way to stop it.

**Comment by datlo** [comment]
Golems get the standard mining scanner and mesons miners do in the gear crates at the top of the ship.

**Comment by MrMagolor** [comment]
Do golems need food? If so, you might want to add a nutriment vendor to the ship.

**Comment by datlo** [comment]
They already got vendor for snacks. If they want proper food, they can do botany and even cook by making the appropriate machines.

**Comment by MrMagolor** [comment]
Also, I notice that free golems are NOT disabled during Shadowling rounds. While highly unlikely for a Shadowling to reach the golems, was this deliberate?

**Comment by datlo** [comment]
Golems don't require oxygen and are 100% spaceproof.
the main worry with free golems on cult rounds is that the free golem ship is an ideal cult base. The golems themselves can already be made by xenobio, and I'm not too worried about sling rounds.

**Comment by MrMagolor** [comment]
I just had a thought: without the ability for golems to make the tiny floor fans/Atmos holofirelocks, how is it going to be possible to pressurize a tcomms asteroid base? I know golems don't need air, but it's always a nice touch

**Comment by datlo** [comment]
They won't be able to. They don't have any atmospherics stuff, nor do they need it. Trade with crew if you want to setup atmos in your base.

**Comment by MrMagolor** [comment]
Also, now that I'm thinking of it, is there a cooldown on golem bodyswap? I can imagine some asshole spamming that to mess with the ghosts that want golem bodies.

**Comment by datlo** [comment]
There isn't, but that'd be an admin issue, namely rule 0. 

Also, you can't bodyswap into the roundstart free golem shells.

**Comment by Diegoflores31** [comment]
Its very cool man Merge this

**Comment by MrMagolor** [comment]
You say that golems will be able to start their own R&D, however, neither the mining vendor nor the autolathe appear to have the ability to make the necessary circuit boards? (For R&D console, protolathe, analyzer, circuit imprinter)

**Comment by datlo** [comment]
Read the description; mining vendor can give you the boards.

Yes, this is working as intended.

**Comment by MrMagolor** [comment]
> Read the description; mining vendor can give you the boards.

Ah, I didn't realize "The Liberator's Legacy" was what contained the RnD boards.

**Comment by MrMagolor** [comment]
I learned recently that you cannot make solar panel frames, only order them from cargo or obtain them from Secure Storage. As I would prefer power more renewable than a PACMAN for any outposts I make, could a crate of the arrays be added to the golems ship?

**Comment by datlo** [comment]
Lemme look into that that's a good point

**Comment by taukausanake** [comment]
I think it would be nice to make solar power frames from some plasteel sheets. Maybe make them a little more expensive than just ordering them from cargo

**Comment by datlo** [comment]
After thinking/discussion, I don't think giving golems a way to get solar panels is necessary. They can use/salvage panels from the derelict, and they get infinite power from their shuttle.

Honestly solar panels could be autolathe craftable, but not gonna add that to this PR

**Comment by MrMagolor** [comment]
Would there be a way to make it so that in event of an extended round, golem spawn rate is changed to 100%? Or is that a bad idea?

**Comment by datlo** [comment]
this might be something for a later PR if it's requested, for now i'll leave it as is

**Pull request merged**
