### PR TITLE
Corrects math in ipc damage mod

### LINKED ISSUE #9566: IPCs take too much damage
**Problem Description**:
IPCs take about 15% extra damage.

**What did you expect to happen**: 
IPCs to take only 50% extra damage.

**What happened instead**.
IPCs take 65% extra damage.

**Why is this bad/What are the consequences:**
They take more damage then they are meant to.

**Steps to reproduce the problem**:
Shoot them with a revolver, it should do 90 damage, it instead does 99. Or review the code that dictates damage, [here](
https://github.com/ParadiseSS13/Paradise/blob/619885d35e5bcac95925ee585cc16433fa8ea820/code/modules/surgery/organs/organ_external.dm#L634) and [here](
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/species/machine.dm#L18).

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Nothing really, this is purely a code based issue.

This should probably either be fixed by adjusting the brute/burn mod to 2.27, or all documentation like the in code description and wiki to say 165%.

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
This corrects the math issue pointed out in #9566 which made IPCs actually take 1.65 times the normal damage, instead of only 1.5 times. They now take 1.4982 times normal damage, much closer to the stated 50% extra damage they should. (And it's impossible to get it to exactly 1.5 times damage unless we modify how much damage reduction robotic limbs give, which would have knock-on effects on augmentation and so on)

Fixes #9566 
edited since it was pointed out this should close the issue automatically if it gets merged.
**Changelog:**
:cl:
fix: IPCs now correctly receive only 50% more brute and burn damage
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Silly travis, let's try that again.

**Comment by TDSSS** [comment]
Aaand travis stalled for 10 minutes in nanoUI. Uh...third time's the charm?

**Comment by Breenland** [comment]
IPCs get excited for that 0.0018% damage reduction buff, wew! Glad to see some attention being given to our metal friends.

**Comment by TDSSS** [comment]
Also since this has been judged a balance PR and not a fix to restore things to intended behaviour, I'll close this since it's feature frozen and I don't have the points to get it merged. I'll maybe open it up after the feature freeze is over. Poor IPCs will have to deal with the extra damage for the time being.

**Pull request closed without merging**
