### PR TITLE
An Actual Surgical tray 

### PR DESCRIPTION
**Pull request by Oyu07**
## What Does This PR Do

Introduces an actual surgical tray that can hold surgical items inside it
Uses sprites from CM13
Not craftable

## Why It's Good For The Game

Medics/Robotics no longer have to grab a duffel bag from storage every time
So I propose an actual surgical tray. The current existing one is just a fancy table with a name. This gives proper storage for surgical items rather than a duffel bag from the storage

## Images of changes

image
Check MAP DIFF bot

## Testing
1. Spawn surgical tray
2. Insert everything in and out
3. They fit

## Changelog
:cl:
add: Surgical Tray - It hold surgical items and advanced kits
add: Added glove/mask/body bag boxes to robotics rooms that did not have one
tweak: surgical tools spawn inside the tray
tweak: ALL MAPS - very minor movement of items around in robotics
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
Please include that you are removing the table-trays as part of the PR desc/changelog.

For my personal opinion, but I don't want to see the tray-tables actually go, I think they're way more interesting than just having a gigantic storage object. I think the best comprimise would be keeping the tray-tables, and just implementing the storage as part of them, which might need some alterations to the sprite/new sprites.

**Comment by Henri215** [comment]
image

Already being done by another PR

**Comment by Oyu07** [comment]
> Please include that you are removing the table-trays as part of the PR desc/changelog.
> 
> For my personal opinion, but I don't want to see the tray-tables actually go, I think they're way more interesting than just having a gigantic storage object. I think the best comprimise would be keeping the tray-tables, and just implementing the storage as part of them, which might need some alterations to the sprite/new sprites.

Noted, will consider

**Comment by CinnamonSnowball** [comment]
I'm not sure why you're completely removing the surgical tray tables, they're a completely separate concept and do not conflict with your storage trays; if anything they could just be rebranded slightly to not be exclusively tied to medical.

I've seen players use them to move a cool display of items around a few times in my playtime, including a very clever "grab as much as you need" tray of auto-menders in the field of battle with a biohazard, so it's not like they don't have a use.

**Comment by Oyu07** [comment]
Ok so, you guys want the tray table to stay.
I will revert it and keep it in, just need a name change so there are no two "surgical trays" I guess.

**Comment by meow20** [comment]
the table trays are broken, you can store literally entire server in items and pop on it, removing that trash is a big +

**Comment by Oyu07** [comment]
Look what I found
This needs fixing I guess?

dreamseeker_0xsr3JKpVu

**Comment by Oyu07** [comment]
I am inclined to just add the surgical tray and handle the tray table seperately later

**Comment by Oyu07** [comment]
Ready for Review
Just implementing the surgical tray, thats it, alongside the map edits
Tray table remains, might touch it in the future in another PR

**Comment by DGamerL** [comment]
> Look what I found This needs fixing I guess?
> 
> dreamseeker_0xsr3JKpVu [ dreamseeker_0xsr3JKpVu ](https://private-user-images.githubusercontent.com/66401072/286134250-535e4a51-4125-4854-bae7-3af4c743079e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTYwODEsIm5iZiI6MTcwNDY1NTc4MSwicGF0aCI6Ii82NjQwMTA3Mi8yODYxMzQyNTAtNTM1ZTRhNTEtNDEyNS00ODU0LWJhZTctM2FmNGM3NDMwNzllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjI3N2M5NDA2MjYzZDBiNmY5ZjkyYzY4ZGUzMDJlNGRlNmJjNjU4NzAxMmQ4YzJkZTZhNjE2NTU1YzU2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcCys8gFPFoEL8hgOrttco1hkcvCWLb3pzxc_Fo33E0) [ ](https://private-user-images.githubusercontent.com/66401072/286134250-535e4a51-4125-4854-bae7-3af4c743079e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTYwODEsIm5iZiI6MTcwNDY1NTc4MSwicGF0aCI6Ii82NjQwMTA3Mi8yODYxMzQyNTAtNTM1ZTRhNTEtNDEyNS00ODU0LWJhZTctM2FmNGM3NDMwNzllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjI3N2M5NDA2MjYzZDBiNmY5ZjkyYzY4ZGUzMDJlNGRlNmJjNjU4NzAxMmQ4YzJkZTZhNjE2NTU1YzU2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcCys8gFPFoEL8hgOrttco1hkcvCWLb3pzxc_Fo33E0)

Is this fixed?

**Comment by Oyu07** [comment]
> > Look what I found This needs fixing I guess?
> > dreamseeker_0xsr3JKpVu
> >       
> >         [
> >           
> >             dreamseeker_0xsr3JKpVu
> >           
> >         ](https://private-user-images.githubusercontent.com/66401072/286134250-535e4a51-4125-4854-bae7-3af4c743079e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTYwODEsIm5iZiI6MTcwNDY1NTc4MSwicGF0aCI6Ii82NjQwMTA3Mi8yODYxMzQyNTAtNTM1ZTRhNTEtNDEyNS00ODU0LWJhZTctM2FmNGM3NDMwNzllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjI3N2M5NDA2MjYzZDBiNmY5ZjkyYzY4ZGUzMDJlNGRlNmJjNjU4NzAxMmQ4YzJkZTZhNjE2NTU1YzU2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcCys8gFPFoEL8hgOrttco1hkcvCWLb3pzxc_Fo33E0)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/66401072/286134250-535e4a51-4125-4854-bae7-3af4c743079e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NTYwODEsIm5iZiI6MTcwNDY1NTc4MSwicGF0aCI6Ii82NjQwMTA3Mi8yODYxMzQyNTAtNTM1ZTRhNTEtNDEyNS00ODU0LWJhZTctM2FmNGM3NDMwNzllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDE5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjI3N2M5NDA2MjYzZDBiNmY5ZjkyYzY4ZGUzMDJlNGRlNmJjNjU4NzAxMmQ4YzJkZTZhNjE2NTU1YzU2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcCys8gFPFoEL8hgOrttco1hkcvCWLb3pzxc_Fo33E0)
> 
> Is this fixed?

Ah the confusion :)


I am not touching the tray. Going to that in the future, also busy irl to work on it.

**Comment by DGamerL** [comment]
> > Is this fixed?
> 
> Ah the confusion :)
> 
> I am not touching the tray. Going to that in the future, also busy irl to work on it.
> 
> This pr only introduces the surgical tray + map edits, thats it

If this bug only happens with the surgical tray, it might be something that needs fixing.
However if this happens with all items then it should be fine, just open an issue report on it please

**Comment by Oyu07** [comment]
> > > Is this fixed?
> > 
> > 
> > Ah the confusion :)
> > I am not touching the tray. Going to that in the future, also busy irl to work on it.
> > This pr only introduces the surgical tray + map edits, thats it
> 
> If this bug only happens with the surgical tray, it might be something that needs fixing. However if this happens with all items then it should be fine, just open an issue report on it please

oh no no, it happens with the tray itself, not the surgical tray
but yes, I will open an issue report for the tray

**Review by S34NW — APPROVED** [review]

**Pull request merged**
