### PR TITLE
Gameplay rebalance

### PR DESCRIPTION
**Pull request by SamHPurp**
:cl: Purpose2
fix: Science
del: Science
/ :cl:

### CODE REVIEW

**Comment by Rapidvalj** [comment]
👍

**Comment by deep-fried-faceplant** [comment]
It's a masterpiece

**Comment by Hylocereus** [comment]
You are the hero we need

**Comment by Birdtalon** [comment]
👨‍🔬 👩‍🚀 🔕 🚳 ⛔️ 🚫 !!!! ??!!?!?!

**Comment by taukausanake** [comment]
So, I guess RIP Hydro and literally everything else that requires upgrades. That's cool I guess.

Question: Without Xenobio how are slime people canon?

**Comment by Crazylemon64** [comment]
eh, sounds abt right

**Comment by Ratvar** [comment]
This will buff R&D

**Comment by tigercat2000** [comment]
The amazing part is that this passes TRAVIS.

**Comment by alexkar598** [comment]
Clown will rule science now!

**Comment by SamHPurp** [comment]
> The amazing part is that this passes TRAVIS.

@tigercat2000 what, you think I'm some kind of amateur?

**Comment by Aurorablade** [comment]
@Crazylemon64 now i know we got more labels then that...

**Comment by matt81093** [comment]
#Speedmerge ftw?

**Comment by tigercat2000** [comment]
Needs more labels!

**Comment by tigercat2000** [comment]
*notices your science nerf* OwO wat's this? We can't nerf _science_! *pounces on close button*

**Pull request closed without merging**
