### PR TITLE
Allows IPC's to receive eye implants

### PR DESCRIPTION
**Pull request by monster860**
Glory to synthetica!

:cl:
bugfix: IPC's can now receive eye implants
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:-1:  No

**Comment by Spacemanspark** [comment]
Thanks for leaving a very nice description as to why the answer is 'no'.
:+1: this is more of a bug than anything.

**Comment by Crazylemon64** [comment]
This isn't going to do it, you're going to need to allow robotic organ manipulation to work on the eyes, too.

**Comment by monster860** [comment]
I'm starting to get the idea that Fox hates all my PR's.

**Comment by Crazylemon64** [comment]
Fox is not a fan of IPCs, from what I gather.

**Comment by NTSAM** [comment]
Could at least explain your no, Fox, instead of just flat out saying "no"

**Comment by Aurorablade** [comment]
The reason is IPCs have alot of shoddy snowflake code in places.

But you know what :-1: and heres why, the code how it is, will prevent the following: Installing brain implants or implants in the head (anti drop, CNS), prevent the instalalltion/extraction/repair of Optic Sensors of ipcs. The other reson is right here https://github.com/ParadiseSS13/Paradise/blob/12f987942ed1239bd8122d36167659e4a86de324/code/modules/surgery/organs/augments_eyes.dm#L7

All eye implants are attached to the eye parent organ/zone. yes i know eyes are in the head but that allows for quick surgical repair of eyes and brain in one fell swoop.

I apologize IPC players but the answer to this current inconvience lies in another castle.

**Comment by ProperPants** [comment]
I have absolutely no idea what Aurora is trying to say.

@Crazylemon64 Does this PR seem feasible to you?

**Comment by Crazylemon64** [comment]
@ProperPants I'm working on a stack-based surgery system that should resolve a lot of complaints with the current system right now.

**Comment by Dinarzad** [comment]
What Aurora is basically saying is: This wouldn't really fix it, it'd cause more problems then it would solve.

**Comment by Fox-McCloud** [comment]
For one, most augments are organic augmentations, not mechanical augments, so from that perspective it doesn't make much sense; also there's the fact of what @Aurorablade pointed out as being inherently problematic due to the hugely divergent nature of IPC "organs" when compared to your normal stock human mob.

**Comment by Crazylemon64** [comment]
IPC organs are all prosthetic, yet they are all insertable into a flesh-and-blood human. The parity, does not exactly match...

**Comment by Mijhead** [comment]
@Fox-McCloud , I honestly don't really see what implies that the augments this PR concerns are mostly organic, and even then, that can just be refluffed; I don't think that's a fair argument to make, especially considering that the prevalent idea is, or atleast seemed to be, "Fun/gameplay over realism" It just feels somewhat as if you have a bias towards IPCs.

Moving on from that, the other argument made seems more sound, so I believe that that is the best argument to be made against this particular PR, but not against the concept as a whole.

**Comment by ProperPants** [comment]
The only thing I have a problem with is that every race except IPC is capable of getting cool shit from genetics and implants. Of course there shouldn't be any sort of IPC genetics, but it's a bit unfair that they're the only race that can't be enhanced. After all, their paper-mache bodies still make them easy to overpower, even with implants.

**Comment by TheDZD** [comment]
Honestly I don't see an issue with giving IPCs the ability to use implants. Genetics makes a bit more sense not only from the fact that they are synthetic, but also because they're immune to the tox damage and get utterly murderkilled by the rare side effects. That said, I'd like to know what @Aurorablade means by her comment first.

**Comment by Aurorablade** [comment]
@TheDZD IPCs can already use chest/head based implants. Right now the proposed solution kinda creates issues with any sort of IPC repair surgery involving the head (eye repair and head implant insertion).

When i say the solution is in another castle i mean this: To get this to work properly, you need to make a set of cybernetic implant organs (optic mods..whatever you want to call them) that are IPC only, do what the hud implants do, and are parent_organed to the head rather then the eyes.

Before anyone asks why not just make all eye implants parents of the head...I can be overruled on it by a peer, but i much rather perfer the implants in the eyes then in the head for organics at least.

**Comment by Necaladun** [comment]
As always, from a perspective of potential buggyness/problems with future code/etc, my opinion here is worthless and defaults to the maintainers.

From a balance/gameplay perspective, I don't see the problems here. 

(I think I'm reading this right) From a lore perspective - if the implants are mainly meant to be semi-organic, then we can just say they aren't, or make an alternate version for IPCs...but I'd prefer to avoid that because of the IPC snowstorm. It makes sense lorewise in fact that IPCs could more easily have implants, or modifications.

**Comment by Aurorablade** [comment]
okay it was pointed out ot me, you can discard your other chances and try adding "eyes" to this list here and see if it works 
https://github.com/monster860/Paradise/blob/ipcimplantfix/code/modules/surgery/robotics.dm#L15

oversight...shhhh

**Pull request closed without merging**
