### PR TITLE
Adds minor armor to combat gloves and jackboots

### PR DESCRIPTION
**Pull request by TDSSS**
## What Does This PR Do
Adds very minor armor to combat gloves and security jackboots.

## Why It's Good For The Game
Combat gloves and jackboots are both tough garments designed to provide some protection. If even a jumpsuit can provide minor melee armor, then tough boots should do too. It also is a reason to wear them over just any normal shoes from a vendor. In other words, it's for consistency, it is counter-intuitive for them to not provide at least some protection, even if it's not a game-changer or anything.

## Changelog
:cl:
add: minor armor to jackboots and combat gloves
/:cl:

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
bone talisman is 5 melee

sec jumpsuit is 10 melee

sec armor is 25 melee, riot armor is 50 melee

so if you pair sec armor with a bone talisman, jackboots, combat gloves, and their jumpsuit, you'll end up with an uncomfortably high armor value

one that'll only get worse if they get augumented

**Comment by TDSSS** [comment]
Armor doesn't stack like that. Gloves only cover the hands, sec armor won't cover the hands, etc. You don't just add all the armor values together.

**Comment by Fox-McCloud** [comment]
Not keen on giving gloves or boots armor; currently only the bone bracers have it (and that covers the arms), and the combat boots have it, which are pretty much limited to ops and adminbus only.

**Comment by TDSSS** [comment]
I don't see why we should have some parts of the body that you just can't get armor for. Like, it doesn't make much sense from a fluff perspective and gameplay wise do we really want the optimal play to be targeting hands/feet even more? It feels very gamey to me.

TBH it feels like an oversight to me that was then post-hoc justified in some way, but maybe you have good reasons for it.

**Comment by craftxbox** [comment]
s t e e l   t o e   b o o t s

**Comment by Couls** [comment]
Why not just remove the jackboot sound? People put tape on their boots anyway and I think most players find the noise the jackboots make annoying more than anything

**Comment by TDSSS** [comment]
The noises are kind of cool, though. As long as there was a proper upside to jackboots. ~~Could always remove jackboot taping then~~

**Comment by AdamElTablawy** [comment]
@TDSSS _some_ armor doesn't cover the hands

other armor, like spacesuits, hos clothes, riot suit, etc, offer full body coverage, so it will stack

**Comment by Fox-McCloud** [comment]
Yeah, and that's generally the problem, especially for stuff like the boots--again, with antag things, it's less concerning, but I don't think things generally available to the crew should exacerbate the problem of "armor stacking that hits `X >= 100` for melee damage"

**Comment by TDSSS** [comment]
I mean in general, it probably makes sense to sanity check armor values and cap them somewhere high, IE don't allow 100% armor to most things? ~~Also can we just get rid of hands and feet as a separate zone in general?~~

**Comment by Ty-Omaha** [comment]
I think it would be cool if it was just melee and bullet protection

**Comment by Spacemanspark** [comment]
The sound is cool, don't remove it.

I have no real issues with this PR either way it goes, but it does make a bit of sense for those items, boots in particular, to give a very tiny bit of protection.

**Comment by variableundefined** [comment]
I agree with Fox on the armor stacking issues.

Closing for the reasons he's stated above.

**Pull request closed without merging**
