### PR TITLE
Adds methamphetamine to bear meat

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Replaces the morphine in bear meat with methamphetamine, makes it 5u

## Why It's Good For The Game
LOOK IT'S THE COCAINE BEAR (1985(2023))

## Testing
Yes

## Changelog
:cl:
add: Adds kinda-cocaine to bear meat
/:cl:

### CODE REVIEW

**Comment by ArcticValor** [comment]
what in god's name are you on?

**Comment by Coolrune206** [comment]
Funny, but if it means the experimentor is able to spam out methamphetamine bears...
We all know how that's gonna turn out.

**Comment by DGamerL** [comment]
> Funny, but if it means the experimentor is able to spam out methamphetamine bears... We all know how that's gonna turn out.

Tbf they can get meth faster by just making it, if they spawn bears they still have to kill them first

**Review by Contrabang — APPROVED** [review]
looks me to meth

**Comment by Cress67** [comment]
Why not make it full of morphine _and_ meth? Then they'll be speedballing with uppers and downers, for extra fun.

**Comment by DGamerL** [comment]
> Why not make it full of morphine _and_ meth? Then they'll be speedballing with uppers and downers, for extra fun.

Because the morphine will just sleep you and the meth is powerless against it - but it'll gladly give you brain damage still so you can die if you eat too much!

**Review by Burzah — APPROVED** [review]

**Pull request merged**
