### PR TITLE
[DNM] [WiP] - Sleep No More + Sleep Less in Space Battle

### PR DESCRIPTION
**Pull request by Kiyahitayika**
## What Does This PR Do

- This PR adds a new vitals stat called ANESTHETIZED which functions the same way as using the Sleep verb currently does for surgery.

- This PR makes it so you can no longer use the Sleep verb to get through MOST surgeries.
     - [x] Pain will not wake mobs who are ANESTHETIZED
     - [ ] This PR makes it so pain will have a CHANCE to wake up mobs who are UNCONSCIOUS --- to make ghetto surgery still viable

- The Anesthetic Tank now has a ***Six (6) Minute*** automatic shutoff, no more watching your doctor get killed off by antag while you're in Lala Land with Ryan Goosling (Voxxy, yaya, OH SKREK WHY VOXXY ON THE BAD AIRS?!)

## Why It's Good For The Game

- Mobs can no longer sleep through surgery.
- WakeUp() can no longer be called on SSD mobs, so more flopping around.
- Surgery now requires either painkillers, ether, Anesthesia gas mixture, or N2O.

## What Causes a Mob to become Anesthetized?

- Going SSD (so you can still do surgery on SSD people as you currently can)
- Sleeping Agent (N2O)
- Anesthetic Tank (it's freakin' anesthesia)
- Abductor Baton
- Morphine (if taken in high enough dosage), but not Hydrocodone (that one is straight-up pain killer)
- Ketamine (this is what is in Sleepy Pens)
- Neurotoxin (drink)
- Neurotoxin (toxin)
- Capulettium (toxin), but not Capulettium Plus (that one is straight-up FAKEDEATH)
- Curare (toxin) (used in an Italian film where a cat is the murder weapon)
- Pancuronium (toxin)
- Sodium Thipental (toxin)
- Sulfonal (toxin)
- .50 Soporific Sniper Rifle Bullet (bullet)
- Ether

## Changelog
🆑 
tweak: Mobs can no longer Sleep through surgery or Sleep through pain
/ 🆑

### CODE REVIEW

**Comment by Kiyahitayika** [comment]
This was a pain in the neck to structure code-wise and I'm not a fan of some of the variables I put on the `stat_procs`. 

The current version also requires 2+ people to properly test -  if you admin-spawn a mob and then AGHOST to take control and use the Sleep verb and then leave, the mob then goes SSD and becomes Anesthetized ... but then may wake up from Sleeping and still be Anesthetized. :eyes: So that's something to be accounted for.

Also, TGUI hates me.

**Comment by hal9000PR** [comment]
This was tried before in a different PR. But it was rejected because of the nerf to getto surgery. Maybe add painkilling affects to common alcohols, not alot, but something

**Comment by AffectedArc07** [comment]
```
Error: our build differs from the build committed into git.
Please rebuild tgui.
```

**Comment by Adrer** [comment]
> This was tried before in a different PR. But it was rejected because of the nerf to getto surgery. Maybe add painkilling affects to common alcohols, not alot, but something

This is actually already in code, I believe
https://github.com/ParadiseSS13/Paradise/blob/2aeaad0f695eccf2ed30a96ebdfb0283cec9e83b/code/modules/surgery/helpers.dm#L113-L130

**Comment by ppi13** [comment]
This has been tried with: https://github.com/ParadiseSS13/Paradise/pull/12082 and https://github.com/ParadiseSS13/Paradise/pull/8640
Surgery is already a pain in the ass, and being able to sleep stops validhunting surgeons from checking your backpack for contraband, just in case.
Plus this will kill ghetto surgery outright.

**Comment by Mitchs98** [comment]
> This has been tried with: #12082 and #8640
> Surgery is already a pain in the ass, and being able to sleep stops validhunting surgeons from checking your backpack for contraband, just in case.
> Plus this will kill ghetto surgery outright.

Pretty much this. As stated in datlo's PR this will just make ghetto surgery nigh useless. Besides that it's not like it has 100% no drawbacks, one of the main ones being you can wake up midway and cause more damage to yourself. Once you're asleep you're asleep, antag can still antag regardless or what have you.

Not only that you're just making things harder for Vox and Plasmamen unless chemistry has made hydrocodone. Chalk that up to one of the racial downsides, sure. But on the other hand a lot of bald surgeons don't even know what is an ether or morphine, and if they do they'll give you enough to put down a whale for eternity. 

Plus this only puts you more at risk for those surgeons that put an anesthetic tank on you then a terror spider or whatever else those surgeons managed to do happens and you're stuck on the table for 20+ minutes staring at a black screen hoping for death(which is something I for one am not a fan of).

**Comment by Carthusia** [comment]
I like this,

I've really never liked the idea of "click sleep"

or doctors telling me to sleep when im on the table.

Im in agonizing, bone breaking pain, i CANT sleep.

**Comment by Wojz** [comment]
The sad thing about this PR is that I will not be able to react to LRP surgeons with things like "What the fuck do you MEAN by 'sleep'"

**Comment by Kiyahitayika** [comment]
> ```
> Error: our build differs from the build committed into git.
> Please rebuild tgui.
> ```

Working on it. Can we get a Balance flag as well? I think this is more than a Tweak?

> being able to sleep stops validhunting surgeons from checking your backpack for contraband, just in case.

What. In all my playtime as Medbay, I have never looked in anyone's backpack. If you're validhunting as a surgeon, I hope to the GODS that Security AHELPs you themselves - how much of a loser can you be? No no, AHELP _yourself_, geez!

>Not only that you're just making things harder for Vox and Plasmamen unless chemistry has made hydrocodone. 

You said it yourself - Morphine and Ether. Besides, can you 

> But on the other hand a lot of bald surgeons don't even know what is an ether or morphine, and if they do they'll give you enough to put down a whale for eternity.

Completely valid. I'd rather have to scream at Baldbay to explain morphine/ether than be put on an Anesthetic tank as a Vox and this PR is one step in a series to move away from using anesthetic tanks in Medbay altogether.


> Plus this will kill ghetto surgery outright.

Look, someone somewhere opened an Issue saying people shouldn't sleep through surgery. I tried to make their request a reality. Maybe people who get ghetto surgery should be _prepared_ for pain and mistakes because, gods forbid, it's NOT SANITARY and it's NOT BEING DONE WITH PROPER MEDICAL TOOLS. I am sure the code already has mistake-chances for that, but gee whiz!

**Comment by Kiyahitayika** [comment]
> this PR is one step in a series to move away from using anesthetic tanks in Medbay altogether.

@Mitchs98 , @ppi13 

Okay, so imagine that we get the OR Computer to _take_ various "inputs" - morphine, ether, hydrocodone (etc), sleeping_agent - and be able to administer doses of those drugs/gases to the player/patient on the OR Table.

Each OR will start with a set amount that can be refilled/filled. It'll just inject/administer the drug/gas directly into the mob on the table -- for Anesthesia, I'll have to figure out how to set the mob's internals to that, for the other drugs, somehow add it to their system.

**Comment by Mitchs98** [comment]
> did that stop them from putting tanks on Vox? Heck no, it didn't! Nothing will!

> Completely valid. I'd rather have to scream at Baldbay to explain morphine/ether than be put on an Anesthetic tank as a Vox and

Please explain to me how this is in anyway whatsoever relevant to the PR at question, and how the PR in question will actually change any of this? Especially when you yourself say nothing will change it. And you are, very much so, making it harder for those races. Code touching them directly is irrelevant to the change impacting them or making certain aspects of the the game harder for them, I'm not quite sure why you claim otherwise.

> Maybe people who get ghetto surgery should be _prepared_ for pain and mistakes because, gods forbid, it's NOT SANITARY and it's NOT BEING DONE WITH PROPER MEDICAL TOOLS. I am sure the code already has mistake-chances for that, but gee whiz!

Or perhaps we can stop cramming realism into the game for realisms sake when the game isn't exactly meant to be terribly realistic in the first place. Ghetto surgery is already dangerous and unsafe for reasons other than not actually being able to undertake it due to lack of pain and painkillers for a many number of reasons. The prime one being infection, of which it is common, fail chance from the tools already that is already decently high without pain fail rate, and of course your surgeon just flat out killing you.

> Okay, so imagine that we get the OR Computer to _take_ various "inputs" - morphine, ether, hydrocodone (etc), sleeping_agent - and be able to administer doses of those drugs/gases to the player/patient on the OR Table.

This would make it relatively easier for surgeons to use the chemicals, but it won't really solve the problem of surgeons injecting far too much into you; which is the main problem I and many others have with doctors using ether/morphine in the first place.

> I think we're missing the point where now Vox and Plasmapeople are _**AWAKE**_ during surgery, just using painkillers.

Ether and Morphine sleep. Hydrocodone is far from being made every round. This is just flat-out untrue.

> Looks like a meme PR?

Read the full thing, based on the comments as well as concerns by Tayyy it was not, in-fact, a meme PR.

Nothing you've really said brings up valid points as to why this is a good PR or really needed, other than the fact someone requested it. I genuinely see no reason for it personally, nor any convincing reasons other than cries of 'LRP'.

**Comment by procdrone** [comment]
I agree with Mitchs, there is little to gain for the sake of realism, other than tedium.

**Comment by AffectedArc07** [comment]
```
This PR will be closed. Not only are you QC banned from the server, but you also tried to use your past contributions as a wager against you being banned, citing "Nice to know you ban your contributors".

Put shortly, we don't want your contributions if you're going to behave this way.
```

**Pull request closed without merging**
