### PR TITLE
Fixed the lighting when placing floor plating.

### LINKED ISSUE #1950: Lighting is a little wonky after rebuilding floor.
Far as I can tell, there was an explosion. Went in, re-tiled the floors, lighting shenanigans ensued. Portable lights like the seclite and PDA light didn't update the light on the tiles, but a drone building new lights did the trick.

Mesons
image

No mesons.
image

Standing in the infinite darkness with PA light on. (drone built one light to the east.)
image

### PR DESCRIPTION
**Pull request by Tastyfish**
When plating was being placed on a space turf, the tiles appeared to be completely unlit.

* This was because the lighting was reset to be dynamic again, but the light_sources thought they were already lighting it, and thus were not adding their luminescence back onto the turf's lighting.

Preview

Fixes #1950

### CODE REVIEW

**Comment by Crazylemon64** [comment]
:+1:

I found it incredibly annoying to find holes that I patched up greeted with complete blackness, this is extremely welcome.

**Comment by Fox-McCloud** [comment]
those commits.

**Comment by TheDZD** [comment]
> You really shouldn't have merge commits on a PR unless you've had merge conflicts some time after submitting it.

**Comment by Tastyfish** [comment]
Yeah, I accidentally pushed after merging locally. They don't harm anything anyway.

**Pull request merged**
