### PR TITLE
Weakens Vox Bones

### PR DESCRIPTION
**Pull request by KasparoVy**
**As per [the Vox wiki](https://nanotrasen.se/wiki/index.php/Vox).**
"_The Vox skeletal structure is unique with its light, porous, and flexible bones_" which, although granting 'enhanced flexibility, reduced weight and increased agility (tm)', would also mean the bones are also less resilient to damage.

This just makes it such that Vox bones break easier, i.e. 3 toolbox hits vs. 4 to the 'core' (head, chest, groin).
Rather than straight removing a pivotal feature of the race such as space resistance.
This does not mean Vox take more damage, just that it takes less damage to break their bones.

Might encourage players to avoid prolonged fights and choose to flee, as Vox should.

I was going to hold this for further testing and balance tweaks but was prompted to release it earlier than expected by another PR.

I had to redefine the limbs for Vox Armalis because as a child of the Vox species they'd inherit the weaker bones, which is an unintended side-effect. Vox Armalis are no different as a result of this PR due to this.

:cl:
tweak: Vox bones, being light, porous and flexible will break at a slightly lower damage threshold than those of other species.
/:cl:

### CODE REVIEW

**Comment by Rapidvalj** [comment]
Prefer this greatly as a nerf, over https://github.com/ParadiseSS13/Paradise/pull/6491

**Comment by ExitGame** [comment]
I don't even know how nerfing vox came up almost out of nowhere.
I would rather just leave it as is, because just needing a few hits to break chest or head bones seems like a major change, really.

**Comment by KasparoVy** [comment]
Cool. "Numbers can be easily adjusted, this was just an initial pass."
It's one less hit than standard organs.

**Comment by Anasari** [comment]
I support this PR, let's see how it goes. It is a minor nerf but it seems quite acceptable to me.

**Comment by Necaladun** [comment]
Makes sense from the lore, weakens them in combat, supporting them being cowards...I like it in theory.

In practice, idk.

**Comment by davidchan13** [comment]
I get where people are coming from but being able to shatter someone skull or chest in 3-4 hits has potentially lethal side effects. On a race that can't be cloned this just multiplies the nerf.

**Comment by scrubmcnoob** [comment]
In comparison to other races in the game, the Vox could use some type of downside besides just requiring to breathe nitrogen which inherently allows them complete space travel and immunity to airway chemicals.

Also if #6494 get's merged in, cloners will suck and humans will suffer just as much too.
This will really push medbay to start working harder, more efficiently, and quickly to save patients before they die. Makes death much harsher.

**Comment by Necaladun** [comment]
Yeah, i think the SR nerf will also nerf vox a lot, and it might be worth waiting to see how that goes. NOCLONE actually being a major downside would be good.

**Comment by KasparoVy** [comment]
@Necaladun Humans already take just 4 toolboxings to break bones. This makes Vox one less hit.

**Comment by Necaladun** [comment]
Ah thanks, it doesn't seem that major and means a vox would (probably) lose a one on one toolbox fight with a human/unathi/etc. That seems how vox should be to me.

**Comment by Regen1** [comment]
Vox having a skittering run away nature suddenly makes sense

**Comment by Fruerlund** [comment]
skreeee

**Comment by Fox-McCloud** [comment]
Let's keep this to whole numbers for thresholds, since most damage numbers are also whole.

I'd round down.

**Comment by KasparoVy** [comment]
Sorry, didn't notice you'd commented on this. I'll tweak and test.

**Comment by KasparoVy** [comment]
@Fox-McCloud Sorry, I didn't notice you'd commented. Busy week! Floored numbers that weren't whole.

**Comment by KasparoVy** [comment]
Opening a new PR based on feedback. :+1:

**Pull request closed without merging**
