### PR TITLE
Adds Henri215 to the review team

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds Henri215 to the review team
## Why It's Good For The Game

Its not.

## Testing

- Only used one of my eyes to verify the changes.
## Changelog
NPFC (Noteworthy Patch From Contributor)

### CODE REVIEW

**Review by Contrabang — APPROVED** [review]
lets get Thenri merged

**Review by GDNgit — CHANGES_REQUESTED** [review]
this is missing a home address to send letters to via carrier pigeon in the case a contributor lacks a functioning computer

**Comment by lewcc** [comment]
Looks 🫃 to me

**Review by lewcc — APPROVED** [review]
Looks 🫃 to me

**Review by farie82 — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]
Let's Go To Mergetown

**Pull request merged**
