### PR TITLE
Adds more meteor protection to the engine

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Before:
img

After:
img
:cl:FreeStylaLT
tweak:Engine shouldn't fail as easily from a single meteor attack. 
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
hmmm

**Comment by AffectedArc07** [comment]
Image

hmmm

**Comment by Superhats** [comment]
Trust no one
Not even yourself

**Comment by alex-gh** [comment]
Personally I think the station needs less protection from catastrophic failures / acts of RNGesus, not more.

Its not like meteors releasing the engine is a super common occurrence.

**Comment by Citinited** [comment]
I don't think this is necessary, because a) as said above, this doesn't really happen very often when meteors hit the station, and b) IMO the possibility of this happening in the first place is part of the excitement of meteor showers. It makes the event feel more dangerous which suits the event.

**Comment by Birdtalon** [comment]
The engine is already too fool-proof and hand holding as it is.

**Comment by TDSSS** [comment]
If the crew wants meteor protection they are free to add additional shielding to engine containment. It's not like engineers are very busy after the initial setup period. Seems pretty unnecessary.

**Comment by Ty-Omaha** [comment]
The game needs to have danger

**Comment by FreeStylaLT** [comment]
Fair 'nuff

**Pull request closed without merging**
