### PR TITLE
Fixes putting NODROP items onto humans

### LINKED ISSUE #2270: Sticky beaker
there was a beaker that got stuck in peoples hand, and kept duplicating adinfinitum.

image

### PR DESCRIPTION
**Pull request by Crazylemon64**
Fixes #2270, #2259 

I'm not too sure how qdel behaves with things like this. Did I do it right?

### CODE REVIEW

**Comment by tigercat2000** [comment]
uhhhh

**Comment by Robertha89** [comment]
eh, this is bad, because there are several nodrop items that are intended to be nondrop, like horse mask wizard spell, and a few items like poncho of shame. currently only the horse one is important as that, so check if the no drop is clothing, if it is, it does nothing, if it isnt, it deletes.

**Comment by tigercat2000** [comment]
@Robertha89 I have no idea what you are even talking about. This prevents people from using the inventory-transfer menu to steal NODROP items.

**Comment by Markolie** [comment]
Seems about right. Please test it in-game though to confirm.

**Comment by Crazylemon64** [comment]
Actually, this was to prevent people from placing nodrop items on people. The code in done() handles the blocking of removing NODROP items already. Anyways, I'll propogate this change to the other levels of mobs.

**Comment by Crazylemon64** [comment]
Oh, hmm. It seems part of the inventory placement code is handled in Topic(). I'll scour through there to fix all the cases.

**Comment by Crazylemon64** [comment]
Alright, give me a bit while I confirm this works.

**Comment by Markolie** [comment]
You rock!

**Comment by Crazylemon64** [comment]
Ah, I didn't actually confirm it - I spent a few hours trying to configure the server for my windows partition, but the place where I'm at doesn't let my windows partition connect to the network for whatever goofy reason, which I think caused dream daemon to spring an aneurysm or something, because it only let it connect for a moment. A good experiment, but unfortunately, as a result, I haven't been able to test this fix yet.

**Pull request merged**
