### PR TITLE
Updates the 357 box with a (better?) codersprite

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Moves from the uggo isometric 357 box to a match the style of the others

## Why It's Good For The Game
Sprites that look like each other.

## Images of changes
image

## Changelog
:cl:
tweak: 357 ammo boxes now use the right perspective
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
the old ones were unused??

**Comment by S34NW** [comment]
> the old ones were unused??

Nope

**Comment by Bm0n** [comment]
oof didn't know they were being used else I would have updated them when I ported all of TGs weapons sprites

**Comment by S34NW** [comment]
> oof didn't know they were being used else I would have updated them when I ported all of TGs weapons sprites

It got added here
https://github.com/ParadiseSS13/Paradise/pull/19553

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Pull request merged**
