### PR TITLE
Adjusts Ian's Wizarding Titles

### LINKED ISSUE #15648: Putting a Wizard hat on a Corgi grants them the title 'Grand Wizard'
**Issue Description**:

Putting a Wizard hat on a Corgi grants them the title 'Grand Wizard'

**What did you expect to happen**: 
When I put a cute wizard hat on the dog, I didn't expect him to become a white supremist.

**What happened instead**:
Ian became the leader of the KKK.

**Why is this bad/What are the consequences**:
In all honesty, this is the type of thing that will fly over a lot of peoples head, but I'd assume we don't want this stuff hard coded into the game.

**Steps to reproduce the problem**:
1. Place a wizard hat (collectable included) on a corgi.

**When did the problem start happening**:
It's possible that this has flown under the radar for a decade and we just never knew.

**Extra information**:

### PR DESCRIPTION
**Pull request by LightFire53**
Makes Ian have less controversial titles

## What Does This PR Do
Renames a corgi with the blue wizard hat on from Grandwizard to Archmage, to reduce potential racism. 

## Why It's Good For The Game
 An unintentional foresight, plus Archmage is cooler than Grandwizard. Fixes #15648 

## Changelog
:cl:LightFire53
tweak: Adjusts Ian's wizarding title from Grandwizard to Archmage
/:cl:

Babies first PR, let's see how it goes.

### CODE REVIEW

**Comment by SabreML** [comment]
...seriously? I didn't even know this was a thing. :eyes:
Well if nothing else it's a bit telling that the guy in charge calls himself a Wizard.

**Comment by procdrone** [comment]
While i don't have any issue with changing the title to archmage...  the reasoning behind this PR (#15648) is so unreal i can't even start to comprehend who in a sane mind could've done such comparison and how invalid it is...

**Comment by Shadow-Quill** [comment]
I... what?

**Comment by Dumbdumn5** [comment]
_What?_ Wait like, the dog in the blue hat being named Grand Wizard conveys the message of _racism_ because the looney bin racist hicks wearing bedsheets named their arch-bigot of scumfuck valley that? 

I understand that terms and symbology associated with an actual honest-to-God racial hate group should be removed, but it's not like Ian's wearing a bedsheet and deep-frying Vox to get the title, it _looks_ like the wizard in the actual game, the completely fantasy-based, fire-ball slinging, cluwne-cursing assgoblin that looks nothing like the racially charged dollar-store ghost costumed organization of white supremacists in real life. 

I don't have any issue at all with the title change, it makes absolutely no difference whatsoever thematically to the pixelated flacid-coned hat wearing dog in the game, but the leaps in comparisons from 'fantasy wizard styled hat on tangerine-toned fake corgi' and 'KKK because the title is the same', are a stretch massive enough to make a Death-Squad issued pulse-rifle enema look like the end of a pastry piping bag.

**Comment by Carthusia** [comment]
Im in the realm of "I dont really care what he's called" But i do fit into the realm of "I dont agree with changes made for questionable reasons, for the sake of that questionable reason"

I dont think I have EVER heard anyone mention this as even remotely a thing, not in passing, not as a joke, not even as a "Fun fact", infact your the first and had  you not mentioned it, I would have continued to not notice it.

Simply because some near dead racist group likes to call their leader a grandwizard does not make all uses of that phrase mean what they want it to mean.

I prefer the route of depowering offensive phrases by making its usage more common and used in ways not intended by the original creators: See Rap Music.

Overall the KKK hasn't been relevant since the 60's after their fall in the early 1930's and are reaching the point of near non-existence 

Early 1900s: An estimated 3-4 million members
Today: An estimated 3000.

They are irrelevant boogeymen who need to stop being given power over certain words.

**Comment by Spacemanspark** [comment]
Can we add a dumbdumn madlib machine to the game

**Comment by thatdanguy23** [comment]
on the one hand, i don't really care, but on the other hand, this is the weakest reason to change the name i've ever heard. weaker than 0.1% alcohol. weaker than purified water.

i believe it was mel brooks who said something to the effect of "if you can bring them down with comedy, you bring them down for good", and i think it's a good mentality to have. pearl-clutching over a video-game dog's cosplay wizard name isn't going to change anything in real life.

**Comment by Dumbdumn5** [comment]
As per a conversation with @LightFire53 , the intent of the PR was to change the name for change's sake and personal preference, though with the additional property of resolving the open issue as nobody had voiced opposition to the issue at their time of writing this. 

My issue stands with the reasoning as I've said above, and I've mentioned that the PR's description seems misleading if the intent was primarily an aesthetic change rather than one motivated by an attempt at improving racial sensitivity.

**Comment by LightFire53** [comment]
Going to throw my standpoint in this:
Been looking for something quick and easy to fix, to start to learn to put together minor PRs.
There was an issue report I saw a really quick, easy fix on, that had no input on it for almost 12 hours.
I saw a fix, and proposed fix. Personally reasoning is that Archmage is cooler than Grandwizard, rolls better off the tongue.
Reference issue in PR.
And get a slew of people who think I'm being super sensitive about white supremecy. 😢

**Comment by thatdanguy23** [comment]
> There was an issue report I saw a really quick, easy fix on, that had no input on it for almost 12 hours.
> I saw a fix, and proposed fix. Personally reasoning is that Archmage is cooler than Grandwizard, rolls better off the tongue.
> Reference issue in PR.
> And get a slew of people who think I'm being super sensitive about white supremecy. 😢

because this shouldnt have been an issue report in the first place, in that case. there's nothing wrong with the name inherently. people see PRs before they see issue reports, is why you're getting more backlash here. apologies if it's bothering you, but it's still kinda dumb.

**Comment by MRgaty** [comment]
I dunno... Its just a dog with a literal wizard hat, not even a white one.

**Comment by Sky-Ping** [comment]
As the one that tossed the issue report up in the first place, I'm going to clear up some of my stances on it and explain the context on how it happened.

Firstly, during an ss13 round, someone put a wizard hat on a corgi.  They also gave the dog a pet death alarm.  Therefore, when the pet died, I saw 'Grandwizard Corgi-of-Chemistry' (or something similar) on common.  My immediate reaction is 'alright, someones naming dogs after kkk members'.  However, when I messaged the player controlling the corgi PLUS the person that created the corgi in the first place, both players pleaded ignorance and had no real idea what was going on.  That's when I found out that this was something hard coded into the game.  I found the entire situation **absolutely** absurd and relatively comical.

And that is why the issue report I wrote is so overly exaggerated.  Do I honestly think that every single person looking at Ian wearing a wizard hat is going to be connected to the KKK?  Absolutely not, because that didn't happen: the dog survived for at minimum half the round.  It's simply silly.  But when I explained what was going on verbally to people in admin chat and in deadchat, the general reaction was 'Oh, shit, I didn't even realize that... Yes.  Yikes'.

We can go back and forth about whether it's right and proper to change the name.  The basis where I think that the name should be changed is that there are only two popular instances that name is used: The KKK, and a Pro Wrestler that was jewish that took on the nickname to try and take the name back.  There are no famous fictional wizards with the title because it's actively avoided (Adventure Time made up 'Grand Master Wizard', for example, instead of the simpler 'Grand Wizard' due to association).

I apologize for wording the issue in a way that makes it look like I was making a mountain out of a molehill, and it was nowhere near my intention.  This doesn't have to be as big of a deal as it's being made out to be.  I will stand by this being a perfectly reasonable and appropriate change, for the previously stated points.

**Comment by hal9000PR** [comment]
You know, before that issue was made, i had completely forgotten that grand wizard was what the KKK had called their leaders. 

That being said, arch mage is cooler and fits in with the adminbus 50 spell point wizard.

**Comment by lolzyking** [comment]
Removing it because it references one singular old use, not even the original use of a term, gives more power to the hateful use of the term. You may think you're being woke, being a good person, but you are cementing the hateful connotation by giving it power.

**Comment by S34NW** [comment]
seems like a bit of a non-issue, as others have stated

**Comment by PidgeyThePirate** [comment]
Archmage sounds better anyway.

**Review by dearmochi — APPROVED** [review]
Code looks fine

**Comment by Dumbdumn5** [comment]
In response to @Sky-Ping and what I'd heard from another admin about concerns regarding my original post, I'd like to address a few things.

First and foremost is that, by insulting and degrading the name of the KKK as 'hicks with bedsheets' it wasn't meant to imply that somehow they're a phantom of an organization or that somehow their threat in real life is a very real one, it was because I don't want to give any credit nor respect to an organization that terrorizes people for something as small as the color of their skin or the internal beliefs and religions they'd hold. They deserve to be made into a laughing stock and their ideology should be cast out, though I prefer my manner of doing so to be in the vein of Spring Time for Hitler rather than avoiding usage of words, as lending them power over language gives more power to an organization I would rather have no hold over myself or anyone else.

I would also like to note that, though my comments were flamboyant and over-done, they were meant to insult the argument and poke fun at the hate group in comparison to Ian in a hat, not to insult individuals making those arguments. With that said, the way my reply was worded could've easily been taken as a dismissal of concerns that would be taken personally, and I'd like to apologize in that case considering that I have no issue with Ping personally, even though I disagree with him as to the significance of this name's inclusion.

In response to the concern from the issue itself, the fact that you had to explain and even remind people that the name was used for that context in the first place for them to even get that there might be an issue lends credit to the idea that the context and usage of the term, coupled with the imagery in-game of the dog wearing a wizard hat and the presence of space-wizards, as they are used and united in-game, does such a good job of using the term in a proper context and connotation that the very thought that it had anything to do with a racist organization was secondary to the idea that it was the dog wearing a wizard hat, which I believe is a far better use of the name than for the leader of a hate group and I'm actually glad that people didn't get anything wrong with it until you had to actually explain it to them.

To me, the intention behind the use of a word, as well as the context in which it is used is far more important to judging the meaning of the word than its popular usage. Something as simple as  'let's eat grandma' vs. 'let's eat, grandma' is a good exercise in this, as the context changed and, thus, the meaning went from soon-to-be group cannibalism to a dinner invitation. In the same fashion, the orange dog in a science fiction setting which includes the presence of a body of people known as the Wizard's Federation wearing a blue, wide-brimmed, and flaccid conical hat is a far, far different context so well removed from the horrors and imagery of the KKK that the very name had been given a far more innocent meaning and association with the dog to those playing rather than to that hate group's leader. 

Given the context provided by the game, the elements present lore and gameplay-wise to show that the title relates nothing to the real life hate group, and the fact that you had to remind others as to what that term _meant_ for there to be any upset about it, I don't see why that should be considered a solid reason to change the name, as the context present and fully supports and entirely different and reasonable setting where that name has a far more innocent purpose.

I don't stand in the way of the changing of the name for the sake of aesthetic preference in any way shape or form, as archmage sounds pretty fucking rad comparatively, but I don't agree with the reasoning behind the original issue given my own view of language and the significance of context.

**Comment by Gatchapod** [comment]
Since the PR is supposedly made out of personal preference, I'll skip the whole racism discussion and talk about my preferences:

I'd rather keep the word "wizard" in the title, even if it's something like Archwizard.
It's a wizard hat associated with wizards from the Space Wizard Federation and feels weird to suddenly refer to its wearer as a "mage".

**Comment by LightFire53** [comment]
> Since the PR is supposedly made out of personal preference, I'll skip the whole racism discussion and talk about my preferences:
> 
> I'd rather keep the word "wizard" in the title, even if it's something like Archwizard.
> It's a wizard hat associated with wizards from the Space Wizard Federation and feels weird to suddenly refer to its wearer as a "mage".

In contrast, the red wizard hat retitles Ian to Pyromancer.

**Comment by McRamon** [comment]
By changing the title you give credit to KKK, i have never thought about kkk while playing ss13 ever up until the moment i saw this PR. Do we accept the fact some racist stole nice word  (grandwizard) from us and we can never use it again? I don't.

**Comment by BMane11** [comment]
> **And get a slew of people who think I'm being super sensitive about white supremecy. 😢**

Might have something to do with... "Renames a corgi with the blue wizard hat on from Grandwizard to Archmage, **to reduce potential racism."**

Context is everything. Have we got an influx of players dragging Grand Wizard Ian around while wearing ghost robes and uttering racist slurs? Do we have an influx of players controlling Ian himself while wearing the hat and uttering such slurs? I would argue that the white robes of the KKK are more prominent and synonymous with them than some silly titles that they gave themselves. Is white ghost robes now up for the hammer too?

> My immediate reaction is 'alright, someones naming dogs after kkk members'.
- Sky-Ping

I won't lie. It is slightly worrying that an administrator had immediately jumped to that conclusion without taking the context of it in mind, and there's a part of me that worries that if you had not found that element in the code, that player may be facing increased scrutiny. However I wanted to quote that because it signifies the issue here. That is sensibilities.

It's hard to see from someone's point of view on something like this unless you are in their shoes and able to observe why they feel this is a problem for them, and others.

There's plenty of things in spess that has double-meaning behind them and are derogatory in nature. Quickest example I can give is the Irish Car Bomb cocktail. Which is a rather on the nose reference to the Troubles and the IRA bombings. Yet I don't see any PR for that, which suggests sensibilities have not been offended by it. 

Are we going to dumpster-dive into the code every time something that may have double meaning is found? Because I'm sure with some considerable searching a lot of references can be found.

Again; to reiterate  what was said elsewhere, context matters here. There is a Space Federation of Wizards. There is a wizard hat. Putting the blue hat on Ian changes him to Grand Wizard. I'm not ignorant of the KKK's titles. But I don't look at Ian and think, _God damn you racist scumbag, Ian!_

So I don't see any merit in changing that based on what someone else may perceive it as, and I don't think it's fair to the rest of us if those who see this as racist are not taking in the whole picture.  There's enough silliness in my 2d spessgame than to be worried about this.

I would also like to point out that Grand Wizard has been used in a lot of mediums, minus any controversy.

- https://www.amazon.co.uk/South-Park-Toy-Collectable-Kidrobot/dp/B00CJEK6KY
- https://geppettosworkshop.com.au/products/the-grand-wizard
- https://www.amazon.ca/Merlin-Wizard-Dragon-Bronze-Finish/dp/B06XRPC8K7

Not to mention the dnd/fantasy element of it. KKK didn't just take Supreme Grand Wizard, they also took:
- Grand Dragons 
- Great Titan and his six Furies
- The Grand Giant and his four Goblins
- The Grand Cyclops
- The Ghouls
- The Grand Council of Centaurs
- The Lictor
- The Nighthawks
- The Exalted Cyclops

So are they all off the menu now? Because those are all titles that at one time or another the KKK had utilized. Since when have we become a society that rewards racism by banishing our own vocabulary because it was once used by a scumbag society? It's just silly. 

I would like to think we are all adults and are capable of understanding that context matters, words themselves have little power on their own except when used by others. And yes, some people do and will abuse that, but if we decided to deal with the word and not the person who is misappropriating it, what's the point?

**Comment by AffectedArc07** [comment]
Yeah this has been open a long time with no one in favour, and 2 maints against. Closing.

**Pull request closed without merging**
