### PR TITLE
Fixes every energy guns description implying it has self charging abilities

### PR DESCRIPTION
**Pull request by 1080pCat**
## What Does This PR Do

title, fixes a tiny oversight in #21313
## Why It's Good For The Game

misleading descriptions are bad

## Testing

checked if laser guns rambled on about being able to self charge, they didn't.
spike thrower still has it
## Changelog
:cl:
fix: Fixed every energy guns description implying it had self charge
/:cl:

### CODE REVIEW

**Review by silverplatedelta — APPROVED** [review]
Oops. LGTM (Legumes got totally mushed)

**Review by Henri215 — APPROVED** [review]
LGTM (Looks Garbage To Me)

**Review by lewcc — APPROVED** [review]
LGTM (Laser Guns, The Misery)

**Review by DGamerL — APPROVED** [review]
LGTM, Lol, great timing man

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
