### PR TITLE
Sprite update woodenfloor V2 - Different

### PR DESCRIPTION
**Pull request by DogsParadise**
Alternate PR to: #15946
Or as a new extra wooden floor tile?

## What Does This PR Do
Changes the current wooden floor sprites into a new one.
The old one is rather lacking, I imagine people are a tad used to them tho.

## Why It's Good For The Game
Better sprites that will fit more with the new sprites

## Images of changes
Old:

image

image

New:

image

image

image

image

## Changelog
:cl:
tweak: Tweaks woodenfloor sprite
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
they look too bright/shiny

**Comment by LightFire53** [comment]
And I think it is too busy, too much going on with the zig zag.

**Comment by FreeStylaLT** [comment]
yo I love this

**Comment by Mitchs98** [comment]
#15946 looks much nicer imo. This one fucks with my OCD, majorly. It looks good, just, yeah x.x

**Comment by Sikroth** [comment]
Personally prefer the other one but this is a fancy design. Maybe tone the highlights down just a bit if I had to say?

I wonder if it could be added later as a "fancy wood tiles". Just like you have two sets of tiles for silver and gold.

**Comment by hal9000PR** [comment]
I do feel like this would be better as a separate item. So we could have both normal and fancy floors.

**Review by S34NW — APPROVED** [review]

**Comment by SabreML** [comment]
Very good looking floor sprite, but I do agree with everyone else that it's far too visually active to be a full on replacement of the current one.

**Comment by AffectedArc07** [comment]
Two maints against, no one in favour from either party. Closing.

**Pull request closed without merging**
