### PR TITLE
Port and modify delta escape shuttle to cyberiad

### PR DESCRIPTION
**Pull request by datlo**
Port and updates the delta station escape shuttle to the cyberiad. It has much more open spaces, more chairs, and is just a better fit for a server with high pop.

The syndicate base was also slightly enlarged to fit the shuttle dock when hijacked, and some of the transit areas were shuffled to make space for the bigger transit necessary for this shuttle. Also I deleted the transit area for the science shuttle. *shrugs*

Screenshots with details where needed : 

Overview of the shuttle : 
shuttle7

Remap of the escape pod bay so that it doesnt get blocked by the escape shuttle : 
shuttle8

Cockpit, one chair for each command/vip minus the Blueshield : 
shuttle2

Security cell and cockpit foyer. Both command and security have access to the foyer. Comes with a chair for the Blueshield/security officer on guard to strap in.
shuttle3

The one room that is entirely new : The emergency external airlock. The external airlocks are public access and can be entered by any crewmember, however the internal white doors are security/command only and are see-through glass, meaning it will be difficult for antags to sneak in without being noticed that way. This also provides an alternative entrance to hijack antags who dont mind going loud to emag the shuttle away. The external airlocks (and only those) have atmos blocking tiny fans so the pressure doesnt get fucked whenever someone enters or exits the shuttle using them.
shuttle4

Cargo and medical. Oxygen crates contain 4 yellow emergency tank and breath mask, medical crate contains a few various medkits.
shuttle5

Pleb room
shuttle6

:cl:
add: Replaced the current escape shuttle with a larger, improved one modified from Delta station.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
datlo removing all the fun moshpits and disarm spam from escape smh

**Comment by Denthamos** [comment]
Finally, an end to shuttle mosh pits.  No longer will people be crammed in like sardines.

**Comment by TDSSS** [comment]
I just noticed there are no wall lockers on this shuttle, no more hiding in there I guess.

**Comment by Ralta** [comment]
RIP hiding in lockers.

Much better shuttle otherwise though.

**Comment by taukausanake** [comment]
Thicc shuttle. Not sure how much I like it but it's not bad. All this tells me though is that we can now make bigger shuttles in the future _(that'll never get merged)_

**Comment by Ty-Omaha** [comment]
oh yeah where are all the emergency O2 wall lockers

**Comment by datlo** [comment]
Gone. They werent in the delta shuttle and I dont really like them so I didnt map them back in.  If you need to hide, the shuttle is now bigger and should have enough space for you to run away from threats and fight them back without it being a moshpit. There's also potted plants for you to grab and hide behind which is less annoying as fuck to deal with for people looking for you.

**Comment by datlo** [comment]
Closing this PR because git is a pain in the ass with map conflicts, will reopen this in another.

**Pull request closed without merging**
