### PR TITLE
Adds in-hand sprites for baguettes.

### PR DESCRIPTION
**Pull request by JackoMallows**
## What Does This PR Do
This PR adds in-hand sprites for the baguette item.

## Why It's Good For The Game
More in-hand sprites are good. Also doubles as extra flavor and fashion for mimes on station.

## Images of changes
Before: Baguetteless, sad mime.
image

After: Baguetteful, happy mime.
image

## Changelog
:cl:
imageadd: In-hand sprites for baguettes.
/:cl:

### CODE REVIEW

**Comment by dearmochi** [comment]
This pleases my inner French

**Comment by Wojz** [comment]
No longer will the Clowns' banana in-hand tyranny threaten the proud Mime nation.

**Review by dearmochi — APPROVED** [review]
Thanks for doing my selfish request!

**Review by SabreML — APPROVED** [review]
Extra points for the sprite demonstrating the standardised Baguette Transportation Position™.
image

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]
Mochi would be proud

**Pull request merged**
