### PR TITLE
Add 48x48 option to dropdown menu

### PR DESCRIPTION
**Pull request by tigercat2000**
Suggested by @melandor0

This (probably) adds an option to the dropdown menu, to set the game to forced 48x48 mode.

### CODE REVIEW

**Comment by TheDZD** [comment]
Screenshots?

**Comment by tigercat2000** [comment]
sc
sc
sc
sc
sc

**Comment by KasparoVy** [comment]
I wish there was a way to get 64x64 to work in 1080 but, otherwise, what resolution(s) DOES it work in? (as in, shows the HUD instead of clipping)?

**Comment by tigercat2000** [comment]
@KasparoVy No idea. Just got the suggestion "there should be a middle ground between 32 and 64, like 48", happened to know how to do it.

**Comment by KasparoVy** [comment]
Thanks anyway, 48x48 looks great

**Comment by Nienhaus** [comment]
64x64 works in 1920x1080 or larger iirc.

**Comment by Earthdivine** [comment]
:+1:

**Comment by KasparoVy** [comment]
@Nienhaus Thanks, I didn't realize trying resolutions higher than native'd get me the result I'm looking for. I'll give it a go next time I get the chance (if that other PR doesn't go through, that is)

**Comment by Nienhaus** [comment]
Oh well, if you are playing on a different server with 15x15 tiles you would see all of it. I thought you were just meaning for the nice crisp look.

**Comment by Fox-McCloud** [comment]
:+1: 

Goon did this not too long ago.

**Comment by Markolie** [comment]
Going to merge this early so it can be patched in together with 15x15.

**Pull request merged**
