### PR TITLE
Sticking heads on spears

### PR DESCRIPTION
**Pull request by ZomgPonies**
- You can stick heads on glass spears. This will create an anchored spearhead object.
- Click the headspear to knock the head down and get the head + spear objects back

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Holy shit.

**Comment by Nomzosha** [comment]
Nomzosh seal of approval.

**Comment by Finalsong** [comment]
Arthur_Dayne approved

**Comment by Fox-McCloud** [comment]
Can you remove the head from the spear and the person's head can still be re-attached?

If not this is going to be *similar* issues to my "deadgibbing" with explosions; carrying a spears around will be an easy way take someone out of the round permanently once someone is dead--only unlike gibbing, there's zero chances of returning to the round.

**Comment by fj45** [comment]
Ouch.

**Comment by ZomgPonies** [comment]
Yes, the head object just gets hidden IN the spearstructure while it's in place. Nothing bad happens to it.

**Comment by tigercat2000** [comment]
:+1:, now I can actually have my head collection on display!

**Comment by TheDZD** [comment]
Perfect, now the revs can display the heads of the dead heads in front of the bridge.

**Comment by Spacemanspark** [comment]
Maybe that should be a thing to rev; make it so you have to spearhead the ones you kill.
Also, we can now recreate the last level of Doom 2.

**Pull request merged**
