### PR TITLE
Add sterile mask to General loadout category

### PR DESCRIPTION
**Pull request by blinkdog**
## What Does This PR Do
Adds the option for a Sterile Mask in the General section of the character preferences Loadout.

## Why It's Good For The Game
You never know when you might be travelling to a place with an epidemic in progress. We wouldn't want to make it more difficult for health care providers to get the masks they need.

## Changelog
:cl:
add: Sterile Mask is added to General section of Loadout
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
I almost feel this is a joke referencing the US medical board telling people to not buy up all the medical masks so doctors can still get theirs.

I don't think ive ever seen people run out of masks in the medbay, there are around 4-6 boxes of 8 each isnt there?

**Comment by blinkdog** [comment]
> I almost feel this is a joke referencing the US medical board telling people to not buy up all the medical masks so doctors can still get theirs.
> 
> I don't think ive ever seen people run out of masks in the medbay, there are around 4-6 boxes of 8 each isnt there?

The PR description is a nod to the American CDC advising against buying up all the medical masks.
The PR itself though is serious, I think it would be nice to have the option to spawn with a mask.

**Comment by datlo** [comment]
I believe the sterile mask has gameplay value in preventing infections when doing surgery, currently? Doing surgery outside of an OR, you should either need to get tools from medbay (which you might not have access to) or deal with the consequences of doing surgery in a ghetto environment. I don't like loadout items doing anything that isnt strictly cosmetic/RP.

**Comment by Carthusia** [comment]
I think this would be limited to medical jobs by default like other loadout items of department type

**Comment by MRgaty** [comment]
I think having it limited to the medical department would be fine.

**Comment by Fox-McCloud** [comment]
This has mechanical advantages, so it's not something that is really a good idea to add to the loadout.

Also making a joke about about a pandemic, while we're in the middle of one is, quite frankly, tasteless.

**Pull request closed without merging**
