### PR TITLE
Proper colored blood

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Updated to the BS12 colored blood system. All species can now have their own blood color
- Updated maps to use the new blood/gibs paths

- Would probably be useful for someone to also port the flesh color stuff so the gibs look proper but that's another PR.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Big :+1:

can't wait for flesh colored gibs, as well! Looks like you've actually got most of that in place already.

**Comment by FalseIncarnate** [comment]
It's good, but the mime needs grey blood and clown needs rainbow / confetti blood.

Otherwise, no complaints from me.

**Comment by Spacemanspark** [comment]
When the clown dies we should have it so confetti flies everywhere and some happy screaming kids, a la Halo birthday party skull.

**Comment by Fox-McCloud** [comment]
Going to consider this a fix instead of a feature; all the necessary vars were technically in the code already, this just allowed them to be properly used.

**Pull request merged**
