### PR TITLE
Language fix + Corgi health status fix

### PR DESCRIPTION
**Pull request by CrAzYPiLoT-SS13**
Fixes: https://github.com/ParadiseSS13/Paradise/issues/845
This now works. Simple as that.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Erm, thanks, never had time to track this down- I don't think a snowflake check is optimal, though.

**Comment by CrAzYPiLoT-SS13** [comment]
I know, but it won't work any other way because of the apostrophes. Are you wiling to shoot down lore for 4 less lines of code?

**Comment by tigercat2000** [comment]
I don't think it's that bad being just 4 lines, but I do wonder why an apostrophe would even break the text.

**Comment by CrAzYPiLoT-SS13** [comment]
I do too, but I see no other problem with this code other than that.

**Comment by tigercat2000** [comment]
I think the code is fine as a temporary workaround, but I'll have to investigate a better solution when I can

**Comment by CrAzYPiLoT-SS13** [comment]
Sure. I really don't know any other way to do this. On the other hand, I just came back from a sleepless 2-day trip and this is my relaxation.

**Comment by CrAzYPiLoT-SS13** [comment]
Fixed the issue at https://github.com/ParadiseSS13/Paradise/issues/818 too.

**Comment by Spacemanspark** [comment]
Yes yes yes no more dead corgi face until dead corgi.

**Pull request merged**
