### PR TITLE
Vox Mining-Loot (and Elite Syndicate) Hardsuits

### PR DESCRIPTION
**Pull request by Ionward**
## What Does This PR Do
Adds Vox versions of Battlemage, Paranormal, Inquisitor, Berserker, and Syndicate Elite Hardsuits, fixed a Battlemage Hardsuit action_type bug, allowing them to have an invisible, illuminating helmet despite the comment specifically stating they don't get a built in light.

## Why It's Good For The Game
Bug fix aside, it's fixing a graphical issue that came up when Vox were reworked, they had most normal space suit sprites, but were missing some. I'm going to work on the Syndicate softsuits, Voidsuits, and Mime/Clown EVA suits next, probably in chunks as well.

## Images of changes
These are separate only because I forgot about the Battlemage Hardsuit when taking the group shot.
wizturnaround
vox-rewardsuit-turnaround

## Changelog
:cl:
fix: fixed Battlemage armor having an unintended helmet light
imageadd: added Vox versions of Battlemage, Paranormal, Inquisitor, Berserker, and Syndicate Elite Hardsuits.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Is that a xeno in Imperium armor? _HERESY!_

**Comment by MrMagolor** [comment]
alt-species nukeops when

**Comment by KasparoVy** [comment]
Inquisitor is straight up the most bomb ass armour out there right now. Looks absolutely wicked on any species, but Especially Human, Unathi and now Vox

**Comment by Carthusia** [comment]
You
Are
A
GOD!

Please tell me you have plans to sprite vox sprites for the other spacesuits vox can't wear

**Comment by Ionward** [comment]
> 
> 
> You
> Are
> A
> GOD!
> 
> Please tell me you have plans to sprite vox sprites for the other spacesuits vox can't wear

I mentioned it in the post, but yes! I'll be working on the Syndicate softsuits, NASA Voidsuits, and the Clown/Mime softsuits when I get more time I can dedicate to a big batch of sprites.

**Comment by Carthusia** [comment]
Woops missed that you mentioned it, but cannot wait.

Clown/Mime EVA suited Vox is something i look forward to

**Comment by datlo** [comment]
https://github.com/ParadiseSS13/Paradise/pull/10537 @MrMagolor i dont think opinions of maints/admins changed on this but anyone is free to reuse the code from that PR if you want species nuke ops

**Pull request merged**
