### PR TITLE
Reverse direction of requests console messages.

### PR DESCRIPTION
**Pull request by FunnyMan3595**
## What Does This PR Do
Reverse direction of requests console messages.

Also fixes a bad error message.

## Why It's Good For The Game
Every time you open it, you have to scroll down to see the latest messages. That sucks.

## Testing
Got messages, order was reversed.

## Changelog
:cl:
tweak: Reversed the order of requests console messages.
/:cl:

### CODE REVIEW

**Comment by FunnyMan3595** [comment]
!merge_upstream

**Review by Oyu07 — APPROVED** [review]
Seems good

image

**Comment by Burzah** [comment]
!merge_upstream

**Comment by FunnyMan3595** [comment]
> Seems good
> 
> image

For the record, this was a joke, not actual annoyance.

**Pull request merged**
