### PR TITLE
Removes that conversion proc we didn't actually use

### PR DESCRIPTION
**Pull request by Crazylemon64**
I guess we gung-ho tore out the old roles but alright, here we are

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Does this really count as a "refactor"? Eh, doesn't matter much...

**Comment by Crazylemon64** [comment]
Also: I was trying to get something going with that proc, where if the "be_special" variable wasn't found in the DB, it would loudly and annoyingly message the admins about it, and ask the coders to take out the proc, but clearly that didn't fire. How would one go about that?

**Comment by Tastyfish** [comment]
I haven't tried this, but you could try `SELECT`ing the column, and then calling `query.ErrorMsg()` and see if it failed.

**Comment by Fox-McCloud** [comment]
>Does this really count as a "refactor"? Eh, doesn't matter much...

Not really, but it's not exactly feature removal either.

**Pull request merged**
