### PR TITLE
Adds the RPD to hacked Autolathes, Drones and Engineering Cyborgs

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Works fine. The autolathe price is pretty expensive, adjusted the RPD's materials to match.

:cl:
add: Engineering Cyborgs now have an RPD!
add: Maintenance Drones now have an RPD!
add: Hacked Autolathes can now print RPDs!
/:cl:

### CODE REVIEW

**Comment by granodd** [comment]
>Engineering cyborgs getting the RPD

Sure, this is fine.

>RPDs being available from hacked autolathes

Pretty sure there was a lot of controversy with this with its initial inception to **_not_** be added to hacked autolathes. Best to keep it that way, as I can't imagine anything good coming out of out-sourcing atmos's job to anyone with an autolathe.

**Comment by uraniummeltdown** [comment]
What's so bad about giving RPDs to hacked Autolathes? The price is quite high so it's not spammable roundstart, and tedious and long projects such as a disposals transport system can get done a lot faster if Engineers and Assistants can help too, vs the few Atmos Techs. And the way you put it makes it seem like Atmos Techs' whole job is to be the guys with RPDs. An Assistant can do everything an Engineer or Surgeon can do, but that doesn't make them useless.

**Comment by granodd** [comment]
The price of the RPD doesn't matter. All you need is one and it can produce infinite pipes. The point of keeping RPDs off the hacked autolathe's production list was so that people would actually _need_ atmos techs, rather than just keeping to themselves. It also makes sabotaging distribution systems not as easy, in addition to keeping the problem of a sabotaged atmos easier to pinpoint of "whodunit."

**Comment by FalseIncarnate** [comment]
I personally would love to see the RPD (or a watered-down version of it) added to maint drones in addition to engi-borgs.

As for the autolathe... eh. It's behind the hacked requirement with the RCD, which is an actual antag objective, though it doesn't have "ammo" like the RCD so there is a bit more "power" in the RPD being commonly available.

Still, most people see atmos pipes and are scared off, since that is the realm of the wizards in yellow and green. I'd be fine with adding it to the hacked autolathe with sufficient material requirements (at or above RCD cost)

**Comment by uraniummeltdown** [comment]
It costs more than double the RCD's metal to print, and it requires as much glass as the RCD needs metal. Also as for maint drones, yeah I guess I could add it to them too

**Comment by FalseIncarnate** [comment]
That is sufficiently high to prevent everyone and their brother's dog's best friend's evil twin from having one easily, so I'd say that should be safe enough to prevent the concern of "who messed with distro" from being a common thing as feared.

Drones having access to the RPD isn't a major point, more a QoL for those who actually try to build and fix blown out areas, since they can't move the big dispensers and shouldn't be asking someone to help them do so to pipe atmos to the maint bar or such.

This now gets me thinking about having multiple drone types...

**Comment by Jovaniph** [comment]
When I saw this PR, the first couple of things that came to my mind was "Whats the point of Atmospheric Techs if this gets mergers?" "If this does get merge, then Atmos Techs should just be removed and replaced with Engineers" "Oh god!!! Everyone is going to use them to make chutes!" etc etc etc

So yeah, I disagree with this PR a lot. When I used to play Atmos Tech religiously, I relied heavily on the RPD to do most of my job well. If Engineers get access to RPD, there will be no need to Atmos Techs. They'll have access to everything on the board to fix the station without them at that point. Removing Atmos Tech would just be something that would be a thing in the future (Which I wouldn't even salt about because It was something I kinda wanted to happen). Engineers will replace them.

**Comment by FalseIncarnate** [comment]
@Jovaniph that seems like a serious over-dramatization and exaggeration of what will occur.

Most engineers will outright refuse to touch pipes despite having access to TWO pipe dispensers for years. That's right, they've had access to the pipes longer than even I've played, since there is one in secure storage (which was regularly left open every shift prior to the tesla) and another on the engineering outpost.

That's akin to saying that doctors aren't needed because the chemist can put a beaker in cryo, or that the chef isn't needed because there is are snack vendors and botany, or that the warden isn't needed because an officer can set the timers. By saying those things, you are ignoring the parts that the base job CANNOT access/complete normally that the specialized job can (surgery for doctors, making superior and rare dishes for chef, managing the armory and paperwork for warden, or waste/filter loop adjustments and gas mixing for atmos)

It's not a question of availability but rather a question of motivation and knowledge. If it was availability, we'd have had engineers re-piping distro frequently since they've had all the same tools as atmos techs (minus the short-lived pipe freezer) for nearly the entire time. Please try and keep the drama contained.

**Comment by Jovaniph** [comment]
@FalseIncarnate Had I known your discord, I would of DM you about the difference between having an opinion and drama. But since you enticed it, I'll just tell you here. I'm not starting any drama. Had I started drama, I would of started would of started by attacking the person who made the PR and those who agreed with it.. I didn't do none of that. I said I disagree. Please educated yourself with the term before trying to come level with me.

**Pull request merged**
