### PR TITLE
adds planet ruin: crashed passenger shuttle

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
This PR adds a small Lavaland ruin, the crashed passenger shuttle. Its most valuable loot is the stock emergency medivend in the back, providing a handful of aid for planet denizens or miners in need of healing items. Besides that, it provides a full toolbox, a functional snack vendor, some emergency supplies and firefighter suits in its fire-safety lockers and emergency O2 wall locker, and that's about it.
## Why It's Good For The Game
More ruins good, more skeletons good.
## Images of changes
SDMM:
StrongDMM-2024-05-03 02 21 48

In-game, full dark:

In-game, full bright:
2024_05_03__02_21_37__Paradise Station 13

## Testing
Spawned in, confirmed existence.
## Changelog
:cl:
add: A new Lavaland ruin, the Crashed Passenger Shuttle.
/:cl:

### CODE REVIEW

**Comment by spacegeese** [comment]
image
lol which passenger decided to build a campfire on lavaland, the very hot planet?

**Comment by warriorstar-orion** [comment]
> image
> 
> lol which passenger decided to build a campfire on lavaland, the very hot planet?

It was the only thing they remembered from their survival skills training course and they were dying to show off.

**Review by Henri215 — COMMENTED** [review]
1. Which area you should be using: "/area/ruin/unpowered/misc_lavaruin" or "/area/ruin/unpowered"?

2. Missing areas over these two walls

image


Everything else is looking good

**Comment by warriorstar-orion** [comment]
> 1. Which area you should be using: "/area/ruin/unpowered/misc_lavaruin" or "/area/ruin/unpowered"?

That's interesting, I've never really noticed that subtype before. The PR that added it, #15108, says it's meant to prevent space ruins from having their baseturf affected by lavaruins modifying the baseturf of `/area/ruin/unpowered`, but the only lava ruins that use it are a handful of the soul maps; plenty other lava ruins don't use it at all while continuing to use `/area/ruin/unpowered`:

2024_05_05__11_49_46__code_game_area_areas_ruins_lavaland_areas dm - Paradise - Visual Studio Code

2024_05_05__11_50_02__code_game_area_areas_ruins_lavaland_areas dm - Paradise - Visual Studio Code

Since I've never seen the issue the PR purports to fix, it makes it hard to reason about how it's helping exactly. I'll swap over to it now but who knows. I have to dig deeper into making a consistent set of /area use conventions but I don't understand them as well as I should.

> 2. Missing areas over these two walls
> 
> image
> 
> Everything else is looking good

Fixed.

**Review by Henri215 — APPROVED** [review]
LGTM

**Review by 1080pCat — COMMENTED** [review]
These front windows dont have shuttle floors under them, just raw lavaland ash, this intentional?
image

**Comment by warriorstar-orion** [comment]
> These front windows dont have shuttle floors under them, just raw lavaland ash, this intentional? image

Whoops, good catch. Fixed.

**Review by Burzah — APPROVED** [review]
Looks good. Merge pending a config update.

**Review by AffectedArc07 — APPROVED** [review]

**Comment by ATP-Engineer** [comment]
image

**Pull request merged**
