### PR TITLE
Less RNG and more experimentation feel for virology (virology rework 1)

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Does a few things:
1. Makes symptoms activate on a timer dependent on the stage speed of the virus. With RNG of how long said timer is each time. The time between is related to the current activation probability.
2. Viruses needs to be evolved in a body before they can be cloned using the PANDEMIC. Meaning that you will have to infect a monkey and have the virus reach stage 3 before you can make a new culture. If the symptom has 6 or more symptoms it'll require you to get a humanoid test subject with a soul attached to it. Monkeys won't work. If a new culture is made then this culture will also be usable for creation of new cultures.
3. The health scanners will give less information according to the stage. Stage 1 will show that there is a virus. Stage 2 will show it's spreading method. Stage 3 the name and stage 4 will show the cure.
4. If somebody is infected with a new advanced virus and the victim already has one in his body then the viruses will fight each other trying to survive. In other words. The new virus will have to beat the other virus it's resistance using it's speed. Formula: newvirus.stagespeed > oldvirus.resistance. Or it'll fail if the old virus has antibodies.
5. Vaccines now require spaceacillin to be made. 15u of vaccine requires 15u of spaceacillin. The PANDEMIC can take spaceacillin from beakers and store it in the machine.

The activation needs some tweaking. Need more feedback on this to see what is balanced.

Link to the forum thread:
https://nanotrasen.se/forum/topic/15561-virology-rework-need-feedback/

Play tested it myself a bit and it took about 30 - 35 minutes instead of the 5-10 minutes it takes now. 

**Changelog:**
:cl:
add: Vaccines now require spaceacellin to make. The PANDEMIC can store spaceacillin from containers. 15u of vaccine requires 15u of spaceaccilin
add: Viruses now have to be hatched first in test subjects. A virus with 5 or less symptoms can be hatched by a monkey. Higher will require a humanoid victim with a soul attached to it.
balance: Health scanners will show information of viruses according to it's stage. Less info for a less developed virus
balance: Virus symptoms now activate after a delay which is dependent on the virus stage speed. The delay is based of the old activation chance
balance: If you're infected with another advanced virus it might override the old one inside of your body. Depending on the new virus it's stage speed and the old ones it's resistance.
/:cl:

### CODE REVIEW

**Comment by SpessX** [comment]
It looks to me like #2 wouldn't be too hard to split from the rest of the PR.

If the effort to get results increases due to it it'd probably go better along a few new symptoms or restoring some old ones, so people taking the job don't feel it's been nerfed with no reward.

**Comment by taukausanake** [comment]
Unironically pinging PR 2. As if PR 1 isn't so much a mess

**Comment by farie82** [comment]
> It looks to me like #2 wouldn't be too hard to split from the rest of the PR.
 
I put 2 in for the reason to give it more of a real experimentation job feel. Currently it's more muscle memory and with minimum interaction with the world around you. I wanted to change this by adding some more interacting to the job.

> If the effort to get results increases due to it it'd probably go better along a few new symptoms or restoring some old ones, so people taking the job don't feel it's been nerfed with no reward.

The job itself gets a bit nerfed in general due to this. But it won't nerf the total effect from virology on the crew. It will do the opposite and buff that part due to the decreased RNG in the symptom activation and in the reliance on speed.
I'm all for new symptoms and restoring old ones (Cough Sensory destruction Cough). These will be implemented in the next PR most likely. I first want to make the job a bit less static.

**Comment by Fox-McCloud** [comment]
As discussed earlier and mentioned in multiple PRs (and on the Discord). We'd really prefer TG's implementation of this. 

We'd like a system that has less "heal all unconditionally" styles of viruses that are more niche and only activate under particular circumstances. TG's system accomplishes this quite well.

Their system also allows you to tailor specific symptoms to specific situations by having particular stats be above a certain number to activate a stronger portion of that symptom.

In this way, there's still a lot of give and take for tailor-making a virus, but it stops it from being a universal heal all that is the optimal thing in every ideal situation.

As stated before, updating our virology to TG's is what we'd like at this point in time.

**Comment by farie82** [comment]
@Fox-McCloud porting TG won't fix the issues with virology. The issues you are describing will be fixed if my full idea is implemented. Just need to change the symptoms up.

Porting TG will only fix the end result of virology. The virus. Not the way to get it. Which is the issue at the moment on here.

I doubt that you have read the forum post seeing that you stated issues that I addressed in the post. Do please reconsider it after giving that a read since it can co exist beside the TG symptoms.

**Pull request closed without merging**
