### PR TITLE
Can Deconvert Mindslaves and Vampire Thralls

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Allows you to deconvert vampire thralls and mindslaves

- You can deconvert mindslaves by removing the implant
- You can deconvert vampire thralls by feeding them holy water
- Fixes mindslaves not having a HUD icon.

:cl: Fox McCloud
tweak: Can deconvert mindslaves by removing their mindslave implant
tweak: Can deconvert Vampire thralls by feeding them holy water
fix: Fixes mindslaves not having a HUD for the master and mindslave
/:cl:

### CODE REVIEW

**Comment by MindLeaker** [comment]
About damn time
:+1: x :100:

**Comment by FreeStylaLT** [comment]
This is so totally how it should have been a while ago. Also helps with Space Law, as the new version tells you to deconvert any brainwashed folk.

**Comment by Dumbdumn5** [comment]
This WASN'T how it worked already? WHO THE FU- :+1:

**Comment by Fox-McCloud** [comment]
Right, turns out there were *already* procs for deconversion of both mindslaves and vampire thralls...they were just never properly hooked in.

In any event, you can now deconvert both mindsalves AND vampire thralls.

Vampire thralls deconvert with holy water.

Also fixes the mindslaves HUDs not properly showing up.

**Pull request merged**
