### PR TITLE
Mice Worn Sprites

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Mice now have sprites when worn on your head or held in your hands (all 3 colors).

Sprites by @FullOfSkittles Thanksss!

pic:
img

:cl: Fox McCloud
add: Mice now have sprites when worn
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Now they should only be able to carry diseases on random events

**Comment by theColdflame** [comment]
game is literally unplayable without this

**Comment by Necaladun** [comment]
I cannot believe we played without this being a thing.

**Comment by FreeStylaLT** [comment]
the final feature PR before the freeze


is this

**Comment by Necaladun** [comment]
Well yeah, now this is in, we don't need any more features. The server is perfect.

**Comment by taukausanake** [comment]
I was wondering why these sprites look a little weird. It's because they are bigger than the pAI mouse icons. Kind of inconsistent but looks like I might be the only one bothered in the slightest. Might want to change one or the other eventually but again, only one here

**Comment by Plotron** [comment]
Damn it, merge when? I put a mouse on my head, but there were no sprites for it. :(

**Pull request merged**
