### PR TITLE
Shorten Change-mob-appearance name to ensure extra columns

### LINKED ISSUE #1640: New change mob Appearance is cluttering admin tab, did not replace the old one
image1
image2

As you can see, there is no need to have it two places, as well as it did not remove the original "Change appearance" button

### PR DESCRIPTION
**Pull request by tigercat2000**
@Regen1

Fixes #1640 (mostly)

The old `edit appearance` is still there, because I don't have the time to properly rip it out, but the big issue is solved.

### CODE REVIEW

**Comment by TheDZD** [comment]
I believe part of the complaint with #1640 was that the two verbs appeared in the already cluttered Admin tab, when they already usable by right-clicking a mob.

**Comment by tigercat2000** [comment]
@TheDZD Eh, with the shortened name, they won't be as much of an annoyance.

**Comment by Regen1** [comment]
I would rather just have them removed completely from the admin tab.
This doesn't fix the problem

**Comment by Markolie** [comment]
Removing the category might work.

**Comment by tigercat2000** [comment]
@Markolie It won't. Only way to hide something from the verb panel is setting 'hidden' to 1, which also removes it from the right click menu.

Removing the category simply makes it appear under a new tab, "Commands".

**Comment by Krausus** [comment]
> Removing the category simply makes it appear under a new tab, "Commands".

According to the docs, if you set the category to null, it doesn't show up in the verb tabs, but still shows up in the right-click menu. There's probably several verbs that should be set like that, really.

**Pull request merged**
