### PR TITLE
Adding and wiring some new guitar sounds.

### PR DESCRIPTION
**Pull request by azulez**
## What Does This PR Do
Changes:
- Added an additional lower octave of legacy guitar
- Added a synth version of legacy guitar
- Created a new set of guitar sounds for synth guitar

Discussion:
Legacy Low Octave:
These new files are just down-tuned versions of the lowest notes that already existed.  It adds some extra low end range that was very noticeably missing in legacy compared to synth.  Note that uptuning for a higher octave doesn't work for guitar, since the percussive component uptunes too and it's very noticeable.

Synth Version of Legacy Guitar:
This doesn't sound as good as legacy because of how the synth system works, however the bane of Legacy is what it does when you have a bunch of notes in a row.  Because legacy has individual sound files for every note and is not optimized like synth, you end up with.. I guess I'd call it a 'volume-crush', and the instrument will mute out almost entirely.
This is added to provide a generally somewhat worse sounding option for songs that have repeated 8th note sections to avoid the dip.

New Guitar Synth Voice:
Built these sounds from the ground up with Arturia Pigments' harmonics and noise engines, with a bunch of filters as a first attempt to try to emulate a guitar sound.  It turned out alright, and it's WAY LESS ANNOYING than most of the existing guitar synth sounds.

The range is larger than the other guitar synths, and the notes have been io-faded and normalized in a curve.  It's quieter than a lot of the existing synth instruments, but I consider that to be a feature.  People need to learn about the damned volume slider holy shit.

It's not perfect; min exponential sustain will silence the instrument, but a couple ticks down works nicely.

Some songs will definitely still sound better with the crisis muted synth, but the goal was to provide another synth option besides crisis muted that doesn't completely suck.

Notes have been normalized to try to give a relatively even perceived volume; modestly meaty bass and a high end that gives you a lead option, but doesn't cut to your soul.

File sizes/quality are also in line with existing sounds.

## Why It's Good For The Game

The crisis synth sounds are ugly and loud in most cases, with the exception of the crisis muted which is quite polite and should not associate with the likes of Steel and Nylon.

Additionally the legacy guitar, while having a comparatively very pleasant sound, uses the legacy system (which is has issues with dense scores) and is constrained to bout three octaves.

By adding an additional lower octave to the legacy guitar, adding a synth version of the legacy guitar, and adding a new set of synth voices to the drop down, it gives some additional flexibility when converting or composing scores and also allows use of the synth system while minimizing ear bleeds.

## Testing
I've run this through a bunch of the existing notations out there and some of my personal conversions, running around knocking on windows and spamming doors.  Max levels feel good to me.

For any additional testing and getting the intended vibe of the new instrument voice, I would recommend playing with exponential fade around 1.2%.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
add: Created new guitar synth voice
add: Added synth version of legacy guitar as a more efficient option for dense scores.

soundadd: Files for new guitar synth voice
soundadd: Files for lower legacy guitar octave
soundadd: Files for synth legacy guitar voice.
:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
What is the source of the new audio files? Are they just re-worked existing ones, or did you pull them from somewhere else?

**Comment by azulez** [comment]
> What is the source of the new audio files? Are they just re-worked existing ones, or did you pull them from somewhere else?

I occasionally do some instrument design as a hobby, so I created them in Arturia Pigments.  It's a couple harmonic signal generators, a short envelope filtered white noise for the 'pluck', some reverb to emulate the body of the guitar, and a number of filters to tweak the profile.

**Comment by lewcc** [comment]
> > What is the source of the new audio files? Are they just re-worked existing ones, or did you pull them from somewhere else?
> 
> I occasionally do some instrument design as a hobby, so I created the new ones from scratch in (fully licensed) Arturia Pigments. It's a couple harmonic signal generators, a short envelope filtered white noise for the 'pluck', some reverb to emulate the body of the guitar, and a number of filters to tweak the profile.

Oh, thanks for making them, and thanks for clarifying! Sorry for the assumption, from-scratch sounds for things like this aren't something we see that often!

**Comment by azulez** [comment]
> > > What is the source of the new audio files? Are they just re-worked existing ones, or did you pull them from somewhere else?
> > 
> > 
> > I occasionally do some instrument design as a hobby, so I created the new ones from scratch in (fully licensed) Arturia Pigments. It's a couple harmonic signal generators, a short envelope filtered white noise for the 'pluck', some reverb to emulate the body of the guitar, and a number of filters to tweak the profile.
> 
> Oh, thanks for making them, and thanks for clarifying! Sorry for the assumption, from-scratch sounds for things like this aren't something we see that often!

It's a good thing to verify!  I figured there could be issues if I went sound-library hunting or the like, plus it was fun to take a shot at making the effect.

**Review by Burzah — APPROVED** [review]
Looks good to me. As stated above, this are original sounds made by the author with a licensed copy of their software.

**Comment by SteelSlayer** [comment]
Author has linked their account.

**Review by DGamerL — APPROVED** [review]
Very good work, sorry for the holdup!

**Pull request merged**
