### PR TITLE
Add a confirmation to start the round

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Adds a confirmation alert to the "start now" verb.

**Changelog:**
:cl:
tweak: Adds a confirmation to the start now verb. Make it ansari proof
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I want to appreciate this commit hash
image

**Comment by variableundefined** [comment]
Requested by me after I accidentally mistook live for my test server and clicked start now like I always do.

**Comment by AffectedArc07** [comment]
Henk stop getting all the speedmerges

**Comment by Ty-Omaha** [comment]
wouldn't you just hit yes anyways though

**Comment by KasparoVy** [comment]
An extra hoop to jump through should make it slightly easier to catch.

**Pull request merged**
