### PR TITLE
Some more species suicide messages

### PR DESCRIPTION
**Pull request by Tastyfish**
I had a few more messages for #3461 from the thread, but it got merged before I could add them.

### CODE REVIEW

**Comment by Regen1** [comment]
>Downloading extra ram

Alright fine, you made me chuckle, let it pass
:+1:

**Comment by Tastyfish** [comment]
> Alright fine, you made me chuckle, let it pass

That one was @NTSAM's.

**Comment by NTSAM** [comment]
*bow

**Comment by Plotron** [comment]
I think that usually it's written/spoken *existential problem*, not *existential issue*.

**Pull request merged**
