### PR TITLE
Inert Bags of Holding

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do

You make inert Bags of Holding at the Science protolathe now. You can combine an inert BoH with a bluespace anomaly  to make a real Bag of Holding

Removes the Belt of Holding(because honestly it was kind of useless and I don't think anyone will spend a bluespace core on it)

## Why It's Good For The Game

The Bag of Holding should cost an anomaly core just like all the other very powerful and often anomaly core limited items from Science. It as a device allows you to carry a lot of items that you honestly really shouldn't be able to and can be mass-produced at the protolathe. This PR does not remove the Bag of Holding but simply requires you to have a bluespace anomaly core to activate an inert Bag of Holding via the crafting menu.

As for the Belt of Holding it was kind of just bloat and I rarely if ever see it used as it cannot hold any normal-sized items and only a limited about of small items. I don't think it's worth keeping around in the codebase.

Sprites and idea came from Necromanceranne and is credited in this PR.

## Testing

Yes.

## Changelog
:cl: Bmon, necromanceranne
tweak: The Bag of Holding from the protolathe has been replaced by the inert Bag of Holding. To activate the inert BoH simply craft a bluespace anomaly core with the inert BoH.
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
I think BOH needs a nerf, but this makes it basically the same availability as a Phazon. I know this is what TG did, but I dont think its good.

Also, I dont want to see belt of holding go, that one is at least somewhat balanced and is a fun item

**Comment by Bm0n** [comment]
> Also, I dont want to see belt of holding go, that one is at least somewhat balanced and is a fun item

Yeah the belt is not really a problem item it's just bloat. It can't hold any normal items unlike almost all the other belts so it makes it a rather pointless option imo

**Comment by Contrabang** [comment]
I dont think its pointless, its still pretty useful for carrying tons of belt shit

**Comment by Bm0n** [comment]
> I dont think its pointless, its still pretty useful for carrying tons of belt shit

i mean i guess if you only want to carry around small items but that's pretty niche. most people just rock a bag of holding

**Comment by Contrabang** [comment]
It should also be noted, removing the bluespace belt will fuck with its subtypes
image

**Comment by Bm0n** [comment]
> It should also be noted, removing the bluespace belt will fuck with its subtypes image

Oof, should have noticed that. I'll re-add but remove it from the protolathe

**Comment by Coolrune206** [comment]
Mixed feelings. I definitely agree that the BoH needs nerfs (and has seen nerfs in the last few months), but am not sure that this is the way to go about it. Due to the nature of anomaly cores on Paradise, this would become so rare to see, especially with how Science is absolutely going to favor making a Phazon out of BS cores rather than a bag.
Doesn't TG have some sort of way to specifically generate Anomaly Cores? That may be why this actually worked there.

**Comment by Bm0n** [comment]
> Mixed feelings. I definitely agree that the BoH needs nerfs (and has seen nerfs in the last few months), but am not sure that this is the way to go about it. Due to the nature of anomaly cores on Paradise, this would become so rare to see, especially with how Science is absolutely going to favor making a Phazon out of BS cores rather than a bag. Doesn't TG have some sort of way to specifically generate Anomaly Cores? That may be why this actually worked there.

Yes TG does have that but it's also never really done either lmao

The issue is on para rounds are longer and having the ability to make anomaly cores might be more troublesome than it is on TG

**Comment by Coolrune206** [comment]
> > Mixed feelings. I definitely agree that the BoH needs nerfs (and has seen nerfs in the last few months), but am not sure that this is the way to go about it. Due to the nature of anomaly cores on Paradise, this would become so rare to see, especially with how Science is absolutely going to favor making a Phazon out of BS cores rather than a bag. Doesn't TG have some sort of way to specifically generate Anomaly Cores? That may be why this actually worked there.
> 
> Yes TG does have that but it's also really never done lmao
> 
> The issue is on para rounds are longer and having the ability to make anomaly cores might be more troublesome than it is on TG
> 
> All it takes is a pretty mehish sized bomb to make a core and ordering packs of unpowered cores from cargo

Oh don't get me wrong, I'm not arguing for core creation as that's a terribly effective way to make all the cool core-locked items suddenly overpresent in rounds. I can't say much about how frequently TGs core creation is used as I've never had the misfortune of playing there, but I still think the fact you can manufacture it there is what makes their gating of items behind cores more viable.

**Comment by Bm0n** [comment]
> Oh don't get me wrong, I'm not arguing for core creation as that's a terribly effective way to make all the cool core-locked items suddenly overpresent in rounds. I can't say much about how frequently TGs core creation is used as I've never had the misfortune of playing there, but I still think the fact you can manufacture it there is what makes their gating of items behind cores more viable.

Yes and no. Inert BoHs were added before the imploder. I mean now you could use the imploder to make more cores but back then you couldn't so this is technically this was balanced around getting a core randomly from anomalies which are seemingly much rarer on TG.

**Comment by tipoima** [comment]
I actually use Belt of Holding in most of my Science rounds (when it's researched anyway). There are plenty of small items that I want to carry, but keeping them directly in the bag is a waste of space, while keeping them in a box makes it take too long to take out.
Honestly, the only reason I don't get one with other jobs, is not knowing when it's researched.

**Comment by jughu** [comment]
> I think BOH needs a nerf, but this makes it basically the same availability as a Phazon. I know this is what TG did, but I dont think its good.
> 
> Also, I dont want to see belt of holding go, that one is at least somewhat balanced and is a fun item

In TG its auctally super common since toxins can activate anomaly cores with x explosion

**Comment by farie82** [comment]
Closing this PR as the preference of the teams was towards #20116

**Pull request closed without merging**
