### PR TITLE
Adds a syndicate station, the Scorpion.

### PR DESCRIPTION
**Pull request by monster860**
This is the syndicate station, Scorpion, after having been raided by a deathsquad years ago. They ran in, gibbed the shit out of everyone, and left. They also left a marauder wreckage in a 1x1 space out of laziness. It's on z7.

*Also, this may be the first time I can get away with modifying a map without using MapMerge. Mostly because it would be absolutely useless to do so.*

Here's a list of the loot
- BROKEN emag
- Syndie toolbox
- Empty syndie medkit
- A fuckton of gibs
- Marauder wreckage
- 1 pirate intercom. (I was considering a illicit one, but I decided against that.)
- 2 syndicate space suits
- Surgery tools
- Chemistry
- Some broken turrets
- An empty AI core

:cl: monster860
rscadd: Adds a syndicate station, the Scorpion.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I'd much rather we have TG's randomized space ruins than this.

**Comment by Dumbdumn5** [comment]
Space Ruins? If we can get that working that'd be amazing, and I totally wouldn't be there every single shift!

**Comment by Fox-McCloud** [comment]
>Space Ruins? If we can get that working that'd be amazing, and I totally wouldn't be there every single shift!

For reference, space ruins is basically a list of pre-made mapped areas---it picks a number of these and positions them at several randomized locations--so it's always different, every shift.

**Comment by monster860** [comment]
Well, if that gets implemented, then this could be a possibility.

**Comment by KasparoVy** [comment]
If we know for a fact we're working on Space Ruins we should save this, otherwise it 'could' be nice to have in the meantime? Not entirely sure. Looks cool though.

**Comment by TheDZD** [comment]
Don't like the idea of having a pre-placed AI core where someone could easily shove a subverted AI and have it terrorize the station, someone should at the very least have to put in the time and materials into building a proper AI core. 
Outside of that, I don't really see the point of this. Static space ruins are kinda shitty, as you cannot put anything that nice into them because telescientists are massive shits, and as a result they end up being fairly boring.

**Comment by monster860** [comment]
> as you cannot put anything that nice into them because telescientists are massive dongs

Actually, z-7 is immune to telescience, unless you emag the console. Or you fuck around with values outside the 0-255 range, but then you need to actually figure out what is adjacent to z-7, which requires a spacepod, and also, you have the limitation of not being able to receive. Also, it's immune to hand-tele.

**Comment by TheDZD** [comment]
Closing this, as the space ruins PR is likely to be merged as it is nearing completion, and provides a better alternative to this.

**Pull request closed without merging**
