### PR TITLE
New sprites for AI modules

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds new sprites for AI modules, split between colors and danger levels.
Sprites made by @ATP-Engineer 
## Why It's Good For The Game

Modules like corporate and tyrant shouldnt be using the same sprite. With coloring and a way to show their danger levels it should make their differences more clear for newer players.
## Images of changes

image
image

## Testing

- Did look into all modules to observe the new sprites.
## Changelog
:cl: Henri237, ATP Engineer
imageadd: Added new sprites for AI modules, split between colors and danger levels
/:cl:

Feel free to suggest if you think a certain module should have a different color/danger level.

### CODE REVIEW

**Comment by procdrone** [comment]
just an idea here, i think like a more themed sprites would be cooler here. like a dollar sign for Corporate, NT sign for NT default, or an assistant icon sign for cresimov board, stunbaton for robocop, etc.

**Comment by Henri215** [comment]
> just an idea here, i think like a more themed sprites would be cooler here. like a dollar sign for Corporate, NT sign for NT default, or an assistant icon sign for cresimov board, stunbaton for robocop, etc.

Maybe, give your idea to ATP Engineer over discord.

**Comment by ATP-Engineer** [comment]
Leaving for clarification on the PR, 'Danger level' is the whole clearence/storage light for each category of law modules, green = 'default', orange = 'experimental', red = 'high-risk'. All of which are visible on the circuits new antenna bulb which was not part of the older sprite. Loved how these came out.

**Comment by Henri215** [comment]
Added custom sprites for the pranksimov and hacked modules.

**Review by Sirryan2002 — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
