### PR TITLE
Tweaks Stamina Regeneration

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/-tg-station/pull/15614

Tweaks stamina regeneration a bit so it doesn't take forever and a day to wear off--regeneration is now 3 per life cycle, up from 2.

Time to go from 100 stamina damage to 0 is now 1 minute 6 seconds---down from 1 minute 40 seconds.

:cl: Fox McCloud
tweak: stamina damage now regenerates slightly faster
/:cl:

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
No more sluggish "goddamnit, it's been ages since I was disabled" from random disabler rounds? :+1: 

I am assuming that in any realistic combat circumstance, such a difference would barely be noticeable, especially if it's a full disabler barrage from a taser or E-Gun. Seems good.

**Comment by KasparoVy** [comment]
How big a nerf to disablers?

**Comment by Fox-McCloud** [comment]
You're still going to be weakened for 5 cycles. That's not going to change--this only changes how quickly you regenerate stamina damage itself--meaning the rate at which stamina damage dissipates.

**Comment by Davdichan** [comment]
In short, doesn't nerf the stun, but does nerf how easy it is for you to be re-stunned ever so slightly.

**Pull request merged**
