### PR TITLE
Makes chem dispensers and masters upgradable

### PR DESCRIPTION
**Pull request by VampyrBytes**
As per http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=6845

I know it was decided that this was a feature request, not a bug, but there were only positive comments for it, and as him PM'ing me as an 'active' coder got me back I figured I'd do the pull request. I certainly can't see any harm in it and it adds consistancy if nothing else

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
There's actually a reason why this hasn't been done.

Constructable chem dispensers are veryyyy different for the preset ones; the preset ones don't really have much, recharge very very slowly, have less overall energy, and don't really have much in terms of available chemicals unless upgraded.

I think the proposition was largely that the current preset chem-masters be upgradeable so that, with tier 4 parts, they could dispense chemicals similar to the fully upgraded portable chem dispensers.

**Comment by VampyrBytes** [comment]
Ah yeah, I see what you mean. Should have looked closer at the code first. Ok, so making them upgradable to be able to dispense the other chemicals (and possibly a slight improvement on the recharge and energy) is certainly doable, but a bit more work... so before I start is there any reason not to?

**Comment by Fox-McCloud** [comment]
Not in particular, though the tier structuring of the parts upgrades is going to be weird---also it would likely be one of the few upgradable things you couldn't build (no inherent problem with that, it's just an odd man out).

**Comment by CupcakesNHacksaws** [comment]
IIRC I don't think you can even screwdriver the machines open ATM, so the current dispensers and the new ones would probably be entirely different entities, right?

**Pull request closed without merging**
