### PR TITLE
Syndicate Ship Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the Syndicate Ship to *mostly* TG's latest iteration.

- Places the air tank in the wall and increases the amount of vents from 4 to 6
 - airlock cycling is stupid; even with this change, it still takes a massive 22 seconds to cycle the airlock.
- Adds in the actual skeletal bar
 - I just never included this.
- Puts teleporter building instructions on the teleporter console
 - Leave admins alone! =p
- Adds in 3 turrets to the syndicate ship--two in the front and one guarding the enter/exit door.
 - Want to try to meta if there's nukies or steal their shit? Too bad, you or your pod is going to get chock full of lead. They don't shoot at actual syndies, of course.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
About time we got those turrets.
:+1:

**Comment by tigercat2000** [comment]
> - Removes the cycling airlock 

please no
Until we convert every airlock to a cycling airlock, I would really rather not remove it from any of the shuttles. Not to mention possible issues with the shuttle controller freaking out.

**Comment by Markolie** [comment]
:+1: to all but the airlock. Having an airlock-less ship doesn't make a lot of sense from any point of view except for gameplay. It does take up a lot of space, but it's not like the ship needs it that desperately. And you can always override it.

**Comment by mrsdobbins** [comment]
Please can we not get rid of cycling airlocks?
I love the sense of atmosphere you get from standing in an airlock as it slowly pumps out the air.
Plus it feels even cooler when you are a nukie.

**Comment by NTSAM** [comment]
I wanna keep the cycling airlocks too, mainly because with non-cycling ones you can easily end up spacing yourself if you're not super careful.

**Comment by Regen1** [comment]
>Removes the cycling airlock
We have LINDA now, so there's no need for this; it just slows Syndis down by a lot and takes up precious space.

So now we're throwing shit like cycling airlocks out the window because of Linda being super slow? This is a hacky solution to our current atmospheric system being utter shit when it comes to realism, and encourages lazy solutions.

This is becoming less and less a game about the atmosphere of playing for the RP and for the depth of the game, and more into what I would call a "call of duty" solution.

**Comment by Spacemanspark** [comment]
Ya, I'd prefer we kept the airlocks as they are now.

**Comment by taukausanake** [comment]
We need to keep cycling airlocks even if they don't matter. One day I'd like to have a slightly faster atmospherics that is actually dangerous

**Comment by KasparoVy** [comment]
@taukausanake Well said

**Comment by Fox-McCloud** [comment]
I can re-add it, but I"m quite frankly shocked at one of the most shitty feature of ZAS that wastes copious amounts of time for literally nothing (especially on LINDA).

**Comment by KasparoVy** [comment]
I guess it serves as a reminder of what once was. It feels a bit more realistic, as well-- which could be a factor. Although realism is a moot point in this game haha

**Comment by Fox-McCloud** [comment]
Increased vents from 4 to 6 and placed the air tank inside the wall so nukies have that one tile extra of precious space.

**Comment by Fox-McCloud** [comment]
@Mark and @TheDZD 

This is ready to go.

**Pull request merged**
