### PR TITLE
WetSkrell Lore Revamp: The Moistening

### PR DESCRIPTION
**Pull request by PopeDaveThe3th**
## What Does This PR Do
wetskrell's a federation psyop now

the TSF also gets a domain name
## Why It's Good For The Game
it's mildly humorous

## Testing
N/A, just text changes

## Changelog
:cl:
tweak: Rewrote wetskrell lore, also made capitalization consistent
/:cl:

### CODE REVIEW

**Review by Sirryan2002 — APPROVED** [review]

**Comment by lewcc** [comment]
but why

**Comment by PopeDaveThe3th** [comment]
> but why

Because it's really funny to imagine that one of sector's leading adult entertainment sites is operated by a psychological warfare unit for the purposes of spreading pro-Federation propaganda and sentiments via hot skrell ladies. (And men too, probably)

**Comment by Contrabang** [comment]
but why
also this ruins the wetskrell.net joke

**Comment by PopeDaveThe3th** [comment]
> but why
> 
> also this ruins the www.wetskrell.net joke

Because it was funny. Consistent capitalization is good too.

**Comment by PopeDaveThe3th** [comment]
> but why
> 
> also this ruins the www.wetskrell.net joke

Though if the .net joke is a dealbreaker I can switch the domains and make it less obvious a psyop

**Comment by McRamon** [comment]
it being nt website is funnier though

**Pull request closed without merging**
