### PR TITLE
The Foodening (Adjusts nutriment factors)

### PR DESCRIPTION
**Pull request by Shadeykins**
**What does this PR do:**
_**It's not even real chicken anyways.**_

**The Controversial:**
Hot Coco nutriment factor 3 -> 0 (full base nutriment reduction. Coco decays into sugar which provides its own nutrition. Hot Chocolate has been changed to use hot_coco as well).
Chicken Soup nutriment factor 2 -> 0.5 (75% reduction)

Why? The convenience of these items is so high due to their values (1 cup from nothing to full) that they disincentive people from ever engaging with other food sources (even other vending machine items). Ideally they could have a junkiness factor like other vending machine food, but this is not viable due to them being reagents. While they can still be abused (simply drink more), they are less convenient insofar as the metabolic rates are already relatively low (you will need to wait longer to get your bang for your buck whereas other foods satiate quicker).

**The (Hopefully) Uncontroversial:**
Protein (found in products containing meat) provides a greater satiety over nutriment (15 -> 20)
Plantmatter (found in products containing plants) provides a greater satiety over nutriment (15 -> 18)

Why? Both of these are more commonly found in chef's food. While chef's food already has higher nutritional values (and also contains vitamins which heal damage and restore blood), this is further weighting to the efficacy of the chef's food. There are also some types of junkfood that got a buff due to this (pistachios, jerky).

**The Potentially Controversial:**
Vitamins (found only in chef's food) have had their healing effects doubled. There is a 50% chance per tick of metabolism for vitamins to heal 1 brute/burn damage and restore 0.5 blood. This has been doubled to 2/2 brute/burn and 1 blood (the chance remains the same).

**The Goal**
We have awful chefs/botanists quite frequently. While a lot of this can be attributed to it being a starter role, I think a fair amount is that these roles are also easily made irrelevant through more reliable mechanisms (vending machines). There is no pressure for anyone in these positions to do their job nor any reason for the HoP to fire them (unless they're being borderline griefy). By making them have the ability to offer out-and-out superior options for satiety and clawing back some other convenient sources, there should be a natural predilection for people to scrutinize players in these roles more frequently.

This should, in turn, lead to more people using the chef and thereby increase the general quality of chefs as demand rises.

**Changelog:**
:cl:
tweak: Hot Chocolate/Hot Coco contains no base nutriment, only the nutrition from sugar decay.
Hot Chocolate changed to use hot_coco reagent, not pure liquid chocolate.
Chicken Soup 75% less effective.
Protein 33% more effective.
Plant Matter 20% more effective.
Vitamins 100% more effective.
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
> 
> 
> issue with this. The hot chocolate drink doesn't have hot chocolate in the drink. It has pure chocolate which gives a lot of nutrients due to itself giving a lot on it's own. But it also has a chance to spawn sugar.
> 
> This won't fix the OPness of the hot chocolate drink. It'll nerf the Dutch hot choco instead
> image

I have fixed this by making Hot Chocolate use hot_coco, because nobody actually means "a boiling cup of liquid chocolate" when talking about hot chocolate.

**Comment by taukausanake** [comment]
_It's all a controversy!_

Also chicken still isn't real chicken :-1:

**Comment by Corocan** [comment]
It's probably about time that hot chocolate/soup was removed as a moderate substitute to chef's food. I don't think this will increase the quality of chefs, however. I theorize it will only result in maintenance cafes and breaking into the chef's empty kitchen to make yourself a sandwich more prevalent.

**Comment by Shadeykins** [comment]
> 
> 
> It's probably about time that hot chocolate/soup was removed as a moderate substitute to chef's food. I don't think this will increase the quality of chefs, however. I theorize it will only result in maintenance cafes and breaking into the chef's empty kitchen to make yourself a sandwich more prevalent.

This is fine. I would like to make soda provide minor nutrition in the future so there's a reason to drink it, along with more useful effects for the chef in general.

@Kyep outlined some interesting potential buffs for chef to me that I think could be a benefit down the road. In the interim though, I see getting rid of the go-to bypasses as an important first step.

**Comment by Mitchs98** [comment]
Forcing people to go to the chef and have their character eat food they wouldn't touch with a ten foot pole isn't a good thing. Especially when 1. Antags and people drug the food decently often for the lols and 2. Most chefs suck/won't prepare food you ask them to or take 4ever to do it if they do. This won't change that. People that interact with the chef and eat their food already do that. 

Chicken soup and cocoa are also the main ways medbay is able to feed a slime person to regenerate their limbs/slime people can regenerate their limbs in any quick sense whatsoever.

Food isn't 'OP'. That's a ridiculous line of thinking. It makes absolutely no sense to nerf it so heavily. If you want to nerf it a more mild nerf would be sufficient. But making the item completely worthless isn't the way to go about it in my opinion.

**Comment by Shadeykins** [comment]
> 
> 
> Forcing people to go to the chef and have their character eat food they wouldn't touch with a ten foot pole isn't a good thing. Especially when 1. Antags and people drug the food decently often for the lols and 2. Most chefs suck/won't prepare food you ask them to or take 4ever to do it if they do. This won't change that. People that interact with the chef and eat their food already do that.
> 
> Chicken soup and cocoa are also the main ways medbay is able to feed a slime person to regenerate their limbs/slime people can regenerate their limbs in any quick sense whatsoever.
> 
> Food isn't 'OP'. That's a ridiculous line of thinking. It makes absolutely no sense to nerf it so heavily. If you want to nerf it a more mild nerf would be sufficient. But making the item completely worthless isn't the way to go about it in my opinion.

You're right, food isn't op which is why I never described it as such. I said the convenience of certain food items makes other food items meaningless. Many people don't even bother going outside of their department to check for other sources of food because there's an instant satiety dispenser in every department. This also buffs say, pizza, from Cargo.

As for slime people, that already seems like a bit of a bypass. Limb regeneration on slimes was intended to be slow from the outset to my knowledge, not something you can do away with by chugging soup. You can still chug soup mind you, it's just not as efficient. You could also grind down food and make nutriment pills to achieve the same effect.

I would love to do something else for the chef (a remap of the area with a smartfridge or something) to prevent easy and rampant poisoning, but we're on a mapping freeze.

**Comment by Shadeykins** [comment]
> 
> 
> _It's all a controversy!_
> 
> Also chicken still isn't real chicken 👎

It's probably corgi if we're going to be perfectly honest here.

**Comment by Shadeykins** [comment]
As per maint suggestion, hot_coco and chocolate have had all nutriment removed as they already decay into sugar and provide nutrition through that.

**Comment by Kyep** [comment]
I like the buffs to chef food.
I'd also like to see an order system where crew enter the food they want in a computer, or from a menu, and the chef then makes it. That would mean the chef spends more time making food people will eat, and has less wasted effort. 
All in all, I like these positive incentives to use the chef and wish there were more.

I dislike nerfing the alternatives, such as chicken soup. It is quite common that the chef isn't going to many any usable food, because:

- there is no chef 
- the chef is incompetent (very common, as its one of the first roles new players take)
- the chef never got mats from botany (again, very common, botany has a <50% competency rate)
- the chef is an antag and busy doing other things
- the chef's food got poisoned by someone walking past
- the chef's food all got taken by someone walking past
- the chef's food is all stuff that is going to screw up your character, like spider legs or eggs
- the chef is dead
- and so on

There are so many rounds where one of the above applies, I'd classify chef food as "not typically reliable". So, there needs to be an alternative which IS reliable. Currently, chicken soup is that alternative. If you want to encourage people to use the chef, then buffing the chef as above is fine.... but nerfing chicken soup and food vendor food in general is a bad idea, because there has to be a fallback for times when the chef isn't available, and lowering the quality of that fallback hurts everyone during times the chef isn't available. On the flipside, increasing the bonus for chef food still fulfills the goal of making chef food more attractive, without needlessly annoying the crew when chef food isn't available.

**Comment by Shadeykins** [comment]
Other food in the vendors still exists, it simply won't get you to 'full' satiety. You can also satisfy yourself with soup still, it's just not as efficient.

Part of what I would like to eventually do is to create more common areas in departments where staff can congregate at quieter hours and shoot the shit over coffee.

**Comment by TDSSS** [comment]
Hot chocolate and soup definitely need a nerf. You can argue they should be nerfed less, but it is absurd that taking two sips of hot choco can take you from starving to full. Vending machines still provide a backup food source in case the chef is shitty with these changes. On top of that, there are several other, alternative food sources:

1. Botany can just grow shittons of fruits and dispense those, especially if they increase nutrition of them.
2. Cargo can order pizza, they already do this lateround when bored and flush on points (maybe add a crate of 'emergency survival rations' to cargo that is less expensive than pizza crates but still feeds crew okay?)
3. Literally anyone can plant fruits in garden
4. You can just accept that you're going to go to starving. It doesn't actually kill you. Absolute worst case, where all food on station is eaten and somehow chef is still not doing anything, everyone just moves slower.

**Comment by davidchan13** [comment]
Vending machine food should be the last resort. The fact that it's not speaks volumes about the state of our nutrition system. IMO the portions of all vending machine food should be reduced (when's the last time an over priced candy bar from a vending machine filled you up more than a hot pocket?) or have side effects, but I don't see that happening soon.

Overall, +1. Making the Chef/Botanists actually relevant and someone pressured to produce food is a good thing, for the same reasons having doctors do their job rather than people relying on medbots is also a good thing.

**Comment by Shadeykins** [comment]
Closing/opening to re-proc icon dif bot. Ree icon-diff bot.

**Comment by The-Driker** [comment]
Now we just need some Chef Excellence products that give bonuses to robustness.

**Comment by KasparoVy** [comment]
🤔

**Pull request closed without merging**
