### PR TITLE
captain to Captain

### PR DESCRIPTION
**Pull request by yurivw**
Changed the text from: "All hands, captain" to "All hands, Captain."

The supervisors are now also proprly capitalised.

It kinda bugged me that they weren't to begin with.

### CODE REVIEW

**Comment by chopchop1614** [comment]
I love this and it bugs me as well!

**Comment by GeneralGoose** [comment]
you misspelled condom

**Comment by TheDZD** [comment]
"the captain" as supervisor is present in more than one file (all the heads of staff have it), so you would have to change those as well. Additionally, none of the other supervisors are capitalized ("chief medical officer", "research director", etc.), so this would really just create an inconsistency.

**Comment by Fox-McCloud** [comment]
About the only one that seems to be a valid change is "Captain <name> is on deck"; generally if it's just referring to a job/title it's not capitalized, but when it's a title preceding a name, it appears to be.

ie: "he's a Lieutenant in the army" would not be correct (and looks awkward).

**Comment by yurivw** [comment]
Updated it. I agree with you, Fox. 
I should've done a bit more research, but I just looked it up. You're right.

**Pull request merged**
