### PR TITLE
Adds floor painters to engineering cyborgs

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Nothing bad could possibly come from this

:cl:
add: Engineering cyborgs now have floor painters. Absolutely nothing bad can happen because of this.
/:cl:

### CODE REVIEW

**Comment by IcyV** [comment]
Should probably be something that has to be made rather than in there by default.

Also seems a little odd to give it to Maint drones when they probably shouldn't be using it in the first place.

**Comment by Earthdivine** [comment]
I wouldn't give it to Drones, they just repair the station, painting isn't repairing it.

**Comment by fludd12** [comment]
Could be considered improving it, though. Besides, maintenance drones need a little fun that doesn't affect people.

**Comment by Earthdivine** [comment]
I got no problem with that, just more worried they will use the paint for mini projects drones do when bored and ignore the station when things get bad or spend too much time repainting things that were destroyed.

**Comment by IcyV** [comment]
I...honestly don't see how it could be considered improving. At best it's personal taste and not objectively improving anything. 

It also very much affects people. Nor do I agree that they need more things that are "fun." The whole point of drones is to give people who are not in the round a way to contribute and help out without having a grand impact. Sometimes it's nice to just kind of be there mindlessly repairing things. It's annoying enough as is when people try to convince drones to build them a superfort with reinforced everything, god forbid they want drones to paint them a picture too.

At the very least it should definitely be an emagged module if not a default one.

All that and what Earth said. I predict a lot of random paint projects in hallways and escape while half of a department is missing from an explosion or someone destroyed all the windows in medbay, etc.

**Comment by Vivalas** [comment]
Oh god what have you done. As much as I like the idea this will inevitably lead to shitter cyborgs and drones painting the station a swath of shitty colors and get edgy when they get blown or locked down.

**Comment by Fullofskittles** [comment]
It's bad enough when lots of players get floor painters and do obnoxious things....imagine infinitely respawning drones. Everything will be stairs or worse.

**Comment by TheDZD** [comment]
Yeah, have to agree that the floor painter is fine for engiborgs, but not drones.

**Comment by Fox-McCloud** [comment]
Going to concur with @TheDZD

**Comment by Crazylemon64** [comment]
Don't forget to update the changelog

**Pull request merged**
