### PR TITLE
[DNM] I rebased TG and am now porting paradise features backwards

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
rebases to TG

This is kind of just a personal project of mine to see how much of paradise content I can port over to TG and if it would be more viable to rebase to TG than it would be to continue to port features from TG

things I have to do:

- [x] Port over spacepods
- [ ] Port over our races

- [ ] Port over terror spiders

- [ ] Port over our karma system

- [ ] Old goonchem

- [ ] Possibly more?

**Changelog:**
:cl:
add: TG code
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
No. This to far and something we have always been against. Just no.

**Comment by Aurorablade** [comment]
If its a personal project don't make a PR for it and just do it on your own repo.

**Comment by Mocha-Not-Latte** [comment]
Absolute Madman

**Comment by SteelSlayer** [comment]
Godspeed Coul

**Comment by taukausanake** [comment]
I've been saying we might as well rebase to /TG/, unironically (but I guess we haven't been pulling _that many_ features from them). For the push that is better SS13 code it would make sense. I hate the idea no matter what but not a bad thing to make either way.

See if you can use the version of /TG/ that still had catgirls. If you can then expand it to foxgirls with Vulpkanin ears. I can only promote this if these are met

**Comment by Mocha-Not-Latte** [comment]
Also stealin’ my ideas for moffs

**Comment by Dinarzad** [comment]
Based Couls
Unironically the hero we need

**Comment by Couls** [comment]
Rebased couls @Dinarzad

**Comment by Couls** [comment]
image
SPACEPODS ARE IN!

**Comment by KasparoVy** [comment]
They can port our features but they'll never port our spirit!

**Comment by Fox-McCloud** [comment]
backporting chemistry will not be easy.

More than anything else, it's been refined to be an absolute T; it's meant to mimic goon's system as best as possible, down to out and out quirks and oddities.

TG's system started out this way, but it diverged quick strongly.

**Comment by Couls** [comment]
Oh man, you just reminded me. I guess i'll refer to our old implementation of goonchem and try to replicate that

**Comment by Tayyyyyyy** [comment]
Rebasing on tg doesn't really help unless we become a downstream of tg, because at the rate they're going they'll outpace us anyways (what happened to Oracle). They're one of the top 10 most active repos on github.

Also I'm not sure that this is an actual rebase. It looks like you just replaced our files with their files, which wipes out all authorship information. This is plagiarism, and violates the CC attribution licenses as well as AGPL, which has a clause that requires you to preserve authorship information:

```
b) Requiring preservation of specified reasonable legal notices or
    author attributions in that material or in the Appropriate Legal
    Notices displayed by works containing it; or
```

If you want to rebase to tg, then you should just make a fork of tg's repo and do your changes on top of it.

**Comment by Couls** [comment]
Will change it to do that instead then

**Comment by FlattestGuitar** [comment]
@Tayyyyyyy is right on the licensing part. You'll probably need a new repo.

I disagree on this being pointless though. Paradise will grow in different directions to tg and porting features will still be much easier than it is right now if anyone acrually wants to do it. It's not like the server had to be up to date to vg or whatever this was even forked from in the first place.

Also, why spacepods? They suck ass.

**Comment by Couls** [comment]
> @Tayyyyyyy is right on the licensing part. You'll probably need a new repo.
> 
> I disagree on this being pointless though. Paradise will grow in different directions to tg and porting features will still be much easier than it is right now if anyone acrually wants to do it. It's not like the server had to be up to date to vg or whatever this was even forked from in the first place.
> 
> Also, why spacepods? They suck ass.

I'm trying to keep as much as original paradise as I can so that people are less uneasy about the whole conversion in general, spacepods were the easiest things to port over initially

**Comment by Fox-McCloud** [comment]
This will be a much larger project than you imagine.

While it has my *tentative* support, you really need to know what you're getting into before going through with this.

There are a number of gigantic challenges that have to be handled and a few things that we have to be willing to lose for this to go through; it's not something to take lightly (thus why I put extremely strong emphasis on "tentative support").

**Comment by Couls** [comment]
In that case I’ll work hard to get something presentable in the near future

**Pull request closed without merging**
