### PR TITLE
Adds the Bob Ross painting

### PR DESCRIPTION
**Pull request by Bram961**
Adds a nice calming painting to the captains office. Because we believe in him.
Image of captains office
Credit to jedr for the icon.
EDIT: New layout, new picture.
🆑 Kluys
Add: Bob ross painting in the captains office called "calming painting".

Also changes around the entertainment monitor and light switch to accomodate.

Fix: Clown painting was named "\improper mech painting"
/ 🆑

### CODE REVIEW

**Comment by Bram961** [comment]
Credit goes to jedr for the icon.

**Comment by SamHPurp** [comment]
I mean, if you're going to move the lightswitch and entertainment console around... why not stick the light switch by the door... like... normal light switches?

**Comment by Bram961** [comment]
Because then the entertainment monitor would be behind the potted plant which I'd like to keep because it is by far the most fun plant disguise on the station.

**Comment by SamHPurp** [comment]
@Bram961 stick it here then:
image

Sticking in that corner where you have it now makes zero sense.

**Comment by scrubmcnoob** [comment]
Clearly the calming painting is the only thing keeping the captain from going fully insane at the distant sounds of murder and the rumble of bombs on board the station.

**Comment by Spacemanspark** [comment]
Lets put a happy little clown over here...

**Comment by Spartan6** [comment]
Execute the prisoner, and as always, God Bless.

**Comment by Draconic-saint** [comment]
How dare you label Bob Ross as a meme, Fox, shame on you!

**Comment by KasparoVy** [comment]
That's an absolutely beautiful icon, I have to say.

**Comment by Kyep** [comment]
Too memey.

**Comment by KasparoVy** [comment]
:rofl: Is there a badge you get for being the first person to downvote a PR?

**Comment by SamHPurp** [comment]
@KasparoVy I'd be drowning in those badges.

**Comment by uraniummeltdown** [comment]
:+1: There is literally nothing wrong with subtle memes like this

**Comment by Bram961** [comment]
Will attempt to edit it [the light switch] later, really busy though.

**Comment by pinatacolada** [comment]
i believe this pr will be merged
[https://www.youtube.com/watch?v=YLO7tCdBVrA](https://www.youtube.com/watch?v=YLO7tCdBVrA)

**Comment by Bram961** [comment]
Dont know what to do with the lightswitch either. On one side it looks to low near the door because I have to move it down but it should probably be near the door....

**Comment by SamHPurp** [comment]
I don't think there is anything wrong with my proposed location.

Other examples of it being 'low down' already on the map:

image

image

image

Thats pretty much how they're used!

**Comment by Citinited** [comment]
And if you don't like SamHPurp's location, you could swap the entertainment monitor with your initial light switch location (so the monitor's behind the plant and the switch is by the door).

**Comment by SamHPurp** [comment]
@Citinited that was my initial proposal, and he didn't want a monitor behind a plant. ;)

**Comment by Citinited** [comment]
@SamHPurp Oh, right. Serves me right for not fully reading the thread before posting XD

**Comment by Bram961** [comment]
🤔 Ill see what I can do. Exams come first though so it will have to wait.

**Comment by Draconic-saint** [comment]
@Kyep What's wrong with a fun, innocent reference like this, that pays homage a great person.

When I first discovered ss13, this sort of jokes and references added a level of fun and relatability. It shows that the game doesn't take itself too serious. 

I believe that lately this game has been taken too serious by quite a few, so I'm all for PR's like this one.

**Comment by Kyep** [comment]
@Draconic-saint Bob Ross does indeed seem like a great person. And yes, his paintings are calming. But still, I can't think of a good reason that one of his paintings would be hanging on a wall in the office of a Captain of a space station in the year SS13 is set in. A subtle reference would be OK. Heck, even the painting itself somewhere on the station where art is expected. Given the location, though, and how different it is color-wise from its surroundings, it essentially looks like a giant 'hey, you're playing a videogame!' marker. It doesn't fit in, in other words. It looks and feels like something that was only put there to be a meme, and isn't really a plausible thing that could be there otherwise. Memes and references are OK, but they shouldn't stick out like sore thumbs. ED209s for example are a reference, but they are plausible on their own so they don't stick out. This isn't really plausible on its own.

**Comment by Bram961** [comment]
Actually I would expect the captains office to have some expensive conversation piece as a luxury. Its also called "calming painting" and examining it shows "We don't make mistakes, just happy little accidents." (I feel like I need to add this for people to lazy to check the changes)

Anyway bob ross is actually visibly in it but for the location... most of the captains conversation pieces are on the right so as for @samHPurp I could move the lightswitch back and the monitor back and hang the painting near the potted plant! Would fit better seeing the reference the painting is making as well and for @Kyep its visibility would be slightly reduced being in the corner.

**Comment by Bram961** [comment]
Layout changed, new picture added.
I am pleased to announce that the picture is in-engine content this time as well. Suck on that E3 presentations.

**Comment by Citinited** [comment]
I like the picture, but why does it have a string holding it up? All of the pictures are attached to the wall by screws, not strings, and to me the string looks kind of iffy (it's just a line of white pixels).

**Comment by LightFire53** [comment]
With Citinited on this one, the string is very out of place.

**Comment by taukausanake** [comment]
What if the string is held up by a screw? I think it looks alright. Why wouldn't the captain have something a little bit different than everything else?

**Comment by Fox-McCloud** [comment]
Merge conflicts.

**Comment by Citinited** [comment]
@taukausanake  Because every other sign does it that way, and there's not really a reason to have the string other than "to be a little bit different".

**Comment by Bram961** [comment]
@tigercat2000 merge conflicts should be gone now.

**Comment by Bram961** [comment]
@citinited it's a painting not a sign. 😉 the only other 2 paintings aren't even in the game so really it's one of a kind.

**Comment by Citinited** [comment]
@Bram961 There's a singulo painting on the engineering outpost ;)

By sign I mean it's a sign in the code

**Comment by Fox-McCloud** [comment]
What's up with the map edits? This seems to be changing around a lot of things that aren't related, at all, to the captain's office.

**Comment by SamHPurp** [comment]
Looks like @Bram961 tried to edit @Kyep 's merged Gamma shuttle PR changes into this PR, rather than rebaseing to resolve the conflict?

**Comment by Tayyyyyyy** [comment]
Is this being seriously considered? This is so gimmicky. It'll get old after the first day and then it'll just be an eyesore for the rest of time. At least take out Bob Ross's face. Love the dude but this does not work with the setting at all.

**Comment by Bram961** [comment]
@samHPurp @Fox-McCloud in my defense I never said I was good at this. I tried fixing the merge conflict by updating my own map to the most recent map and then doing the edit. I'm guessing thats not how it works.

**Comment by Kyep** [comment]
@Bram961 My suggestion, _assuming you are currently up-to-date with paradise master_:
1) Download a clean cyberiad.dmm from Paradise master, save it over your version.
2) mapmerge/prepare map merge
3) Open DM, re-do the edit that places the picture. Save.
4) Close DM completely.
5) Run map merge, select cyberiad.dmm.
6) Commit
7) Load https://github.com/ParadiseSS13/Paradise/pull/7629/files - the changes should have been reduced to a couple of lines, and there should be no references to Gamma-anything.

**Comment by Bram961** [comment]
Fucks sake. I'll go and go through the second list of things instead so its finally fixed then.

**Pull request closed without merging**
