### PR TITLE
Ports NT Station's Belt of Holding Sprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over NT Station's belt of holding sprite---currently it uses the medical belt sprite..wth.

Has an on mob sprite, too.
boh

### CODE REVIEW

**Comment by Markolie** [comment]
:thumbsup:

**Comment by tigercat2000** [comment]
Eeeeehhhhhh. 
I guess this is better than just using the medical sprite. I guess.

**Comment by taukausanake** [comment]
I kind of imagined it to look a little more bluespacy like the Bag of Holding. The matrix in the center could be a little bigger and more blue. I don't know, just doesn't seem "hip" enough.

What's the on_mob sprite look like? Is that something we already have?

**Comment by Fox-McCloud** [comment]
It's grey...like the bag of holding.and it has an animated little feature on it...like the bag of holding =p

**Comment by KasparoVy** [comment]
Looks more than good enough to me. Any more and it'd look bulkier/more clutterd than necessary imo

**Comment by Spacemanspark** [comment]
:+1:

**Comment by tigercat2000** [comment]
Holder post, going to make nice images and put them here

**Comment by Spacemanspark** [comment]
B-b-but muh NTstation nostalgia.

**Comment by tigercat2000** [comment]
@Spacemanspark meant i am going to take screenshots ingame

**Pull request merged**
