### PR TITLE
Labor Camp (Gulag) Rework

### PR DESCRIPTION
**Pull request by Varghh**
## What Does This PR Do
This PR is a complete rework and remap of the gulag, security can now use it to send both Temp and Perma prisoners there. 
The system is quite simple, if you have any prisoner with a 15+ minutes sentence, you can put a prisoner ID inside the "labor camp point manager", give them a "quota" of mining points they must achieve to be able to get out (I calculated with a couple of test runs and 150 points per minute is good enough), you then get them inside the labor camp shuttle, drop them there and they can start to work at lavaland to get those points, there is a set of mining for them to work and a personal ORM. Once they got enough points, prisoners are able to call the shuttle back, get in, swipe the ID on a console and move the shuttle back to the station, then they just need to walk inside the bridge and ask for security to let them out.

If you focus on work, you can get your 20 minute sentence done in just 10 minutes.
**You can get 1200-1600 points in 5 minutes if you focus.**

gulager4

This system works great if you have both temporary and perma prisoners in the same place, because the shuttle won't move unless there's only one person on board, so the temporary prisoners can't take the perma one to the station... unless he steals the ID with the points, so that's the tricky part ;)

The gulag can also counts with a special vendor who works with mining points, prisoners can spend them to get food, alcohol, smokes, toys and better mining equipment (diamond pickaxe) if they are going to stay there for a good time. Take in mind, those points are going to get reduced from your Quota, so if you need 2k points to get out and you buy a plushie because you're feeling alone, you are going to need more points to get out.

vendor1
vendor2

And about the ores, the prisoner can load them inside the crate and move them with him, if the prisoner is an asshole, security can go and retrieve them if they want.

Oh i also made a quick fix to the mining base, it was missing a scrubber under this table.
scrub

## Why It's Good For The Game
The gulag is a cool mechanic and zone, it has been in the code for many years and never got the love it deserve. I hope this PR will make people to use it more, either to send perma prisoners there or make normal ones work for his crimes, i also hope this is a step forward for more paroling, if you feel that syndicate agent should get paroled because he turned himself in, give him a big quota so he can work for his freedom.

## Images of changes

OLD GULAG
oldgulag
oldgulag2

NEW GULAG
gulag

Bathroom
bathroom

Breakroom
Breakroom

Central Area
central area

Dorms
dorms

Equipment room
Equipment room

Infirmary (Ancient medkit, 2 trauma kits, and a mini med on the wall)
Infirmary

Security Area
Sec area

"Gulager" equipment and fashion
Equipment
gulager 3
gulager
gulager2

"Go and work you scum"
gulager5

## Disclaimer
Because this PR makes minor changes to Cyberiad, it's going to be stuck for a good time.

## Changelog
:cl:
add: Labor Camp ORM, Labor Camp Mining Vendor. The gulag also has a new security camera net and a cryo pod.
del: Miner Stacker at the shuttle is useless now so i removed it.
tweak: Gulag Quota now works with mining points, "implant manager console" is now named "labor camp point manager".
/:cl:

### CODE REVIEW

**Comment by Varghh** [comment]
Cyberiad changes are not 100% needed for this PR to work, if wanted, i can rollback them and only leave the Lavaland map changes.

**Comment by PacifistDalek** [comment]
I love this. I've always wanted an excuse to use the gulag as sec, this seems like the perfect way to do so!

**Comment by Kiyahitayika** [comment]
About a week ago, you said you knew nothing about mapping. Seeing this PR fills me with excitement - it's clear that you've learned a _lot_. I can't wait to see this get merged and I can't wait to see what future projects you work on. 

What change did you make to the Cyberiad?

**Comment by Varghh** [comment]
> About a week ago, you said you knew nothing about mapping. Seeing this PR fills me with excitement - it's clear that you've learned a _lot_. I can't wait to see this get merged and I can't wait to see what future projects you work on.
> 
> What change did you make to the Cyberiad?

Thanks a lot for the compliment!

Cyberiad changed are:
Stacking Machine at the Gulag Shuttle is useless so i removed it
The south doors of the gulag ship have all access so prisoners can walk out and ask for security to leave

I think those can be reverted until we can actually merge cyberiad changes, i'm waiting for reviewers to check the PR and if it's they believe it's worth to merge, i can revert that so we get this soon.

**Comment by Dumbdumn5** [comment]
If for nothing else, I'm approving for the tasteful bathroom poster placement. :+1:

**Pull request merged**
