### PR TITLE
Surgery Quality-of-Life Remap

### PR DESCRIPTION
**Pull request by TullyBurnalot**
Simple additions, really:

- Removed Personal Lockers from OR Foyer (never used)
- Added one Pajama Wardrobe per OR (for patient items)
- Moved sinks closer to Surgical Tables (cleaner hands!)
- Moved Light Fixtures down one tile (OCD plis)
- Removed Records Computer from OR foyer (also never used)
- Added beds to OR foyer (more waiting lines)
- Added Pajama Wardrobes to the OR Foyer (for maximum comfy points!)
- Added NanoMed Vendor (SYMMETRY!!!)
- Removed central Disposals Chute (see below)
- Added table and cards (game with a show!)
- Added Disposals Chutes to each OR (DUNK THE LIVER)
- Made the tables that held surgical instruments made out of glass (pretteh)

Think that's all. For reference:

:cl: TullyBBurnalot
remove: Disposals Chute between the Operating Theaters, Patient Lockers, Medical Records Computer
add: More beds outside the Operating Theaters, Pajama Wardrobes outside and inside the Operating Theaters, an extra NanoMed Vendor, one Disposal Chute per OR, table with cards
tweak: Sinks moved closer to Surgical Tables, moved light fixtures in the Operating Theaters, tables with surgical tools now made of glass for maximum style points and Xenomorph Larva Whack-A-Mole
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Map PR without pics

I will shank you @TullyBurnalot

**Comment by KingPhilipIII** [comment]
Can I participate in this shanking? I also approve of this change.

**Comment by TullyBurnalot** [comment]
@Fox-McCloud How to directly paste into picture in das Git

**Comment by Lady-Luck** [comment]
The medical records have been broken for months and right now the bug causing crashing is JUST being fixed...

**Comment by TullyBurnalot** [comment]
You have about 3 other computers in Medbay, in better locations as well.

**Comment by TullyBurnalot** [comment]
ALso just realized this branch is named "DetectiveRequest".

...

?

**Comment by Lady-Luck** [comment]
Another thing, instead of having the OR rooms mirrored, how about having them be copies of one another? There is great clearance for the advanced scanner in the left OR, but not so much on the right.

**Comment by Lady-Luck** [comment]
No nevermind, I guess that wouldn't work with the outside seat configuration... oh well...

**Comment by TullyBurnalot** [comment]
B-but then they're not symmetrical!

Seriously though, yes, I am aware that the scanner stands out like a sore thumb,but I'd rather have that than have non-symmetrical dual ORs next to one another.

**Comment by Lady-Luck** [comment]
it's less that it sticks out more like a sore thumb and more like the right OR's advanced scanner has always been a pain to work with due to how it lines up in that room.

**Comment by TullyBurnalot** [comment]
Problem is, to make it work, I'd also have to move everything else so you wouldn't have to drag the patient across the room to get to the surgical table.

Again, it's really minor in regards to the whole thing, it probably takes just a second more than OR 1.

**Comment by Ar3nn** [comment]
I'd rather the beds in the hall be removed. They just tempt surgeons that don't know any better to lay patients on the bed, I've seen it happen. Anaesthetic is weird and you HAVE to be shaken awake after it wears off. If they just buckle you to the bed, you can't wake up.

**Comment by TullyBurnalot** [comment]
If a surgeon does not shake people up when off anaesthetics, lack of beds won't help them.

**Comment by Lady-Luck** [comment]
I think the beds should stay until we come up with a more useful function for all that space.

**Comment by IcyV** [comment]
>Moved Light Fixtures down one tile (OCD plis)

Kinda think that looks worse to be honest. If anything moving the right-side OR light fixture off of the window would be nice. 

>Removed central Disposals Chute (see below)
>Added Disposals Chutes to each OR (DUNK THE LIVER)

Now to live out my nightmare of everyone ever leaving surgery via that, especially prisoners that can get up for half a moment.


Not too bad other than those nitpicks.

**Comment by LittleBigKid2000** [comment]
Why not flip around one of the body scanners?

**Comment by Ar3nn** [comment]
I don't think body scanners flip

**Comment by LittleBigKid2000** [comment]
They do. Set the dir to 4 to flip them in DM, use a wrench to flip them in-game.

**Comment by Norgad** [comment]
@TullyBurnalot Your sink is not correctly offset. Otherwise, nice changes.

**Comment by Lady-Luck** [comment]
>They do. Set the dir to 4 to flip them in DM, use a wrench to flip them in-game.

My mind is blown. Please do this Tully.

**Comment by Fox-McCloud** [comment]
Not too keen on removal of the personal lockers, to be honest. They're not used a TON, but they are definitely used.

Not sure about the inclusion of the PJ's closets, to be honest, especially with some being in recovery. They're just...not going to be used much by virtue of them being available elsewhere.

**Comment by Belario** [comment]
:+1:  :100:  Beautiful symmetry.

Maybe dump couple of personal lockers in that small corridor to the immediate right of surgery?

**Comment by FreeStylaLT** [comment]
I am 100% certain you can flip the scanner though

**Comment by TullyBurnalot** [comment]
@IcyV Moved light fixtures so they wouldn't be on top of the sinks, just realized they are one tile below the other light fixture. Then realized that yes, we have a light fixture on a bloody window, so they've been placed on the same tile as the Surgical Drill and the empty Blood Bags. N/S, rather than E/W.

@Norgad Sink placement corrected.

@Fox-McCloud 

> Not too keen on removal of the personal lockers, to be honest. They're not used a TON, but they are definitely used.

> Not sure about the inclusion of the PJ's closets, to be honest, especially with some being in recovery. They're just...not going to be used much by virtue of them being available elsewhere.

I disagree. I have literally never, **ever**, seen the Personal Lockers used. And this is with hundreds and hundreds of hours of sitting my ass in front of the OR hoping someone would get maimed.

That said, I can always move the closets back into the OR foyer, though I would much rather not. Yes, they are available elsewhere. Still does not mean they ever get used. People rarely go into that tiny alcove to the right of the ORs anyway. In addition, they still HAVE lockers to be used, they just aren't ID-Locked, which tends to be meaningless anyway. That, and you can only ever have 2 patients being operated on at once, unless you start using tables/stretchers, and at that point, personal lockers are the least of your concerns.

As for the disposals pipes, how does this add a level of Security? You can just hop in and immediately hop out. 

@FreeStylaLT Body scanner flipped, found to need wrenching and to reset sprite direction on use. Needs new sprite. Sorry, @Lady-Luck 

Additional:

- Fire alarm in OR 1 flipped and placed on the other wall;

- Replaced Pajama Wardrobes with Medical Wardrobes

**Comment by IcyV** [comment]
Maybe -1 bed on either side from outside replaced with a closet again? It's rare they are used, yes, but it would still be nice to have available to a tiny degree at least.

And on the disposals, I more so mean the potential for prisoners and such to escape down the pipes and out to cargo immediately from surgery. Maaaany time surgery has seen bad people inside just doing their thing. Disposals being even more immediately available makes it absurdly easy to get out.

**Comment by TullyBurnalot** [comment]
> And on the disposals, I more so mean the potential for prisoners and such to escape down the pipes and out to cargo immediately from surgery. Maaaany time surgery has seen bad people inside just doing their thing. Disposals being even more immediately available makes it absurdly easy to get out.

Quite honestly, this applies for literally any disposals chute. I'd argue that the ORs being cramped makes it a bit harder to get the headstart required to get flushed down, honestly.

**Comment by IcyV** [comment]
It is true for all chutes, but not all chutes necessarily see a lot of vital traffic. Who knows. I just predict it being extremely knowing with handfuls of people that go through surgery.

**Comment by Lady-Luck** [comment]
Liking the new edit, although I have a request that I should have remembered to make before.

Could you make the tables that hold the surgery tools glass instead of metal? It would make them more visible, there's lots of gray used.

That or make the tables a different color with CR, but considering there's a lot of space cleaner use in medical, glass would be better.

**Comment by TullyBurnalot** [comment]
@Lady-Luck I too, dislike the Hemostat-On-Table contrast. Let's see how this looks...

**Comment by TullyBurnalot** [comment]
@Lady-Luck LOOK HOW PRETTY THIS LOOKS!

**Comment by Lady-Luck** [comment]
\o/

**Comment by Fox-McCloud** [comment]
conflicts.

No changelog.

**Comment by TullyBurnalot** [comment]
*scream

**Comment by TullyBurnalot** [comment]
@Fox-McCloud Conflict fixed, I'll be throwing myself into the fridge now.

**Comment by Lady-Luck** [comment]
Merge conflict again? Whyyyyy

**Comment by TullyBurnalot** [comment]
I hate my life. BRB.

**Comment by FreeStylaLT** [comment]
at least it's over now, shouldn't be as many merge conflicts all around anymore

**Comment by TullyBurnalot** [comment]
@FreeStylaLT If I get any more merge conflicts, I _**will**_ murder you for that.

**Comment by FreeStylaLT** [comment]
WHAT'S MORE IMPORTANT, SYMMETRICAL SURGERY OR HALF OF BRIG

**Comment by KingPhilipIII** [comment]
Symmetry of course.

**Comment by TullyBurnalot** [comment]
^

**Comment by TullyBurnalot** [comment]
...

Sigh.

Time to wait for the merge wave.

**Comment by Fox-McCloud** [comment]
You have errant commits again.

**Comment by Fox-McCloud** [comment]
merge conflict. Still has errant changes too.

**Comment by Lady-Luck** [comment]
why

**Comment by FreeStylaLT** [comment]
Will surgery become symmetrical? Will Tully rip _all_ his remaining hair out when he hears of the news?

Find out next time on Githuball Z.

**Comment by Spacemanspark** [comment]
Next ten episodes: Tully slowly reaching his hand to his hair.

**Comment by Ar3nn** [comment]
Poor tully

**Comment by TullyBurnalot** [comment]
WHY DOES ROBOT.DM KEEP GETTING INTO THIS!

WHY AHSDASHDASHD

**Comment by Spacemanspark** [comment]
Synthetica may not approve of your changes.
You might need to bring it up with them.

**Comment by Lady-Luck** [comment]
IT would seem pajama lockers have 4 sets of pajamas in them. In light of this, could you remove 4 pajama lockers and add in 4 personal lockers?

**Comment by TullyBurnalot** [comment]
NO ROGUE COMMITS

NO MERGE CONFLICTS

COME ON TRAVIS BBY

**Comment by TullyBurnalot** [comment]
@Fox-McCloud Merge conflicts FIXED, hopefully for the last time.

**Pull request merged**
