### PR TITLE
Adds internals to the syndicate spacesuit and hardsuit

### PR DESCRIPTION
**Pull request by datlo**
Buffs the syndi space/hardsuit by adding a syndicate mask and a dark emergency oxygen tank to their respective box. 
This makes it easier for a perma'd prisonner with an uplink/storage implant to escape, allow to carry a full EVA package in a single convenient box, and let you pretend you're part of the cool nuke ops kids with a sick tactical mask.

Uplink descriptions were updated to reflect the changes.

syndyinternals

Fix for freeze #9549 

🆑
add: Added syndicate themed internals to traitor spacesuit and hardsuit.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
Realised that the syndi oxy tank lacks in-hand and other sprites, will update.

**Comment by variableundefined** [comment]
Neutral on this.

**Comment by TDSSS** [comment]
Good change. If you're going to spend the TC for a spacesuit, it should come with internals.

**Comment by Birdtalon** [comment]
Much better utility for this. 👍

**Comment by variableundefined** [comment]
Approved. 24 hours passed.

**Pull request merged**
