### PR TITLE
Shuttle Console Nano-UI-ification

### PR DESCRIPTION
**Pull request by davipatury**
:cl: davipatury
rscadd: Shuttle Console now uses Nano-UI.
/:cl:

image

### CODE REVIEW

**Comment by Markolie** [comment]
I think these may look better if we left-align them. Great work though!

**Comment by davipatury** [comment]
@Markolie How about that?
image
or
image

**Comment by Markolie** [comment]
I personally do prefer it. Perhaps we could even add item labels to "Shuttle Locked" and "Authorized Personnel Only" so it fills up a bit more, akin to the old shuttle UI.

**Comment by davipatury** [comment]
image
@Markolie

**Comment by Markolie** [comment]
I like it!

**Comment by KasparoVy** [comment]
Looks sick

**Comment by Markolie** [comment]
One day we should re-add the cloaking option to the nuke ops shuttle. Sure, it wasn't that useful, but if you've declared war already it's cool to get the warning from Naval command.

**Pull request merged**
