### PR TITLE
Nuclear Ops Medbay Changes

### PR DESCRIPTION
**Pull request by Agameofscones**
_**I really gotta thank Lemon, Spartan, and FreestylaLT for helping me figure out the mess that was my github and actually making this work. Cheers to you guys.**_

Changes Nuclear Ops Medbay in its current state is rendered useless by a brute damage field and a TC bought auto surgeon. A bit more utility and options for surgery, limb replacement, and general recovery is probably for the best.

:cl: Triiodine
Tweak: Tidied up nuclear shuttle's mini-medbay to better utilize the space provided.
Add: Full Body-Scanner, surgery set, replacement limbs, bloodpacks to the nuclear shuttle's mini-medbay.
Del: One of the nuclear shuttle's sleepers.
/:cl:

image

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Please don't roleplay in PRs. It makes them obtuse and difficult to read.

Little side jokes are fine, but structuring most of your PR like a roleplay session isn't really acceptable. Your PR description should clearly lay out and define just what your PR does in both a technical and mechanical manner. 

Save the actual roleplay for the server.

**Comment by Agameofscones** [comment]
Noted for future reference. PR description changed.

**Comment by Agameofscones** [comment]
Annnnnd it made -9000 removals, holy FUCK I fucked UP. Yeah wow **DON'T FUCKING MERGE FOR THE LOVE OF ALL THINGS HOLY**.

**Comment by Fox-McCloud** [comment]
I'd condense your changelog to just a line or two, explaining, as concisely, as possible, the *generalized* changes made here. No need for the changelog to be this long.

something like "revamped medbay to make it more fit for surgeries by providing necessarily surgical tools and expanding first aid options" is something that will get the point across without itemizing every single change in the changelog (which you don't have to do unless it's especially contentious or SUPER important).

**Comment by Agameofscones** [comment]
Once I get the commit _actually_ working as intended I'll make sure to condense the change log for ya' Fox. Thanks for the heads up.

**Comment by Agameofscones** [comment]
Forgot to run merge, whoops

**Comment by Fox-McCloud** [comment]
Much much better changelog. Thank you.

**Pull request merged**
