### PR TITLE
Allows pulse rifle projectiles to destroy machinery and objects

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

This allows pulse rifles to destroy objects the same way it does to walls, via telling the object it exploded.
This allows the pulse rifle to destroy doors in 2-3 shots, and anything bomb proof, like many of the doors and shutters at centcom armory, centcom teleporter, centcom specop office, centcom mech storage, nuclear authentication disks, gravgen, and the gateway.

## Why It's Good For The Game

After object integrity got added, the amount of 'health' doors, computers and many other things had increased exponentially, having a death squad be stopped by some computers or bolted doors is just dumb, on top of destroying machinery like nobodies business.  

## Changelog
:cl: ppi
tweak: Pulse rifle can now destroy machinery and objects
/:cl:

### CODE REVIEW

**Comment by Denthamos** [comment]
The shutters at CC are pulse proof for a reason.  I hope this does not change that?

**Comment by githubuser4141** [comment]
I'm not a coder, so this doesn't make mechs or vehicles when hit, right?

**Comment by Fox-McCloud** [comment]
I don't think this is necessary as the pulse rifle already deals a lot of damage to objects, in general.

**Comment by ppi13** [comment]
Due to essentially two maintainers nay, this will be closed.

**Pull request closed without merging**
