### PR TITLE
Adds some new guest pass features

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
rscadd: Guest passes can now be attached to an ID card.
rscadd: Adds a HoP guest pass computer, which is like a normal guest pass computer, but using an ID with ID computer access will allow it to issue guest passes with any access.
rscadd: Adds the HoP guest pass computer to the HoP office.
rscadd: Moves the guest pass computer in robotics to RnD.
/:cl:

### CODE REVIEW

**Comment by QQCucumber** [comment]
1 hour guest passes please?

**Comment by Crazylemon64** [comment]
Err, doesn't robotics need the guest pass console to let people in for repairs? What does a scientist need to temporarily let someone in for?

**Comment by taukausanake** [comment]
To clean their messes or fix their explosions?

**Comment by QQCucumber** [comment]
Messes and explosions don't happen in R&D usually

**Comment by taukausanake** [comment]
Pretty sure guest passes aren't limited to just R&D.

No one even uses them really. If you need someone in your area you just open the door for them. Kind of a shame but I think I'm more okay with it that way

**Comment by Kyep** [comment]
Support.

Guest pass computer always made more sense in R&D, where more people have access to it.

Also, enabling HoPs to give guest passes gives them another thing they can do to be useful. It also increases the chances that janitors will get into kitchen to clean, eng will get into science to repair, etc. It solves problems and increases interaction.

**Comment by Fox-McCloud** [comment]
Could you explain this a bit more, @monster860, please?

**Comment by monster860** [comment]
The reason I moved the guest pass to computer to RnD is because anyone in science has access to the RnD lab (As in the actual room itself)

**Comment by Kevak** [comment]
I approve of the science guest pass machine relocation. Especially useful for xenobio golems.

**Pull request merged**
