### PR TITLE
Adds the ability to compile NTSL to all telecomms servers at the same time

### PR DESCRIPTION
**Pull request by monster860**
This will save a lot of time for anyone trying to compile a script to all channels. Keep in mind, if you're a traitor and managed to get into the room without being detected by the AI, and robusted by security, then it doesn't matter how long it takes to compile the script. And if you're a traitor with legit access, then the AI isn't gonna check on the code that you're writing usually.

### CODE REVIEW

**Comment by orelbon** [comment]
thank you so damn much :+1: x100

**Comment by Regen1** [comment]
This is a great addition, does it properly log to adminlog that all servers were targeted?

**Comment by monster860** [comment]
It adminlogs all 8 servers. A bit spammy, but it works, and making it less spammy means editing more files.

**Comment by monster860** [comment]
Keep in mind that the traffic control can only target servers within a certain range of it. So if only some servers are within that range, then only those servers will be targeted. You might want to know which of these servers were targeted.

**Comment by Fox-McCloud** [comment]
requesting review by @tigercat2000

**Comment by tigercat2000** [comment]
looks fine to me

**Pull request merged**
