### PR TITLE
Improved Vox Mask/Goggle sprites, adds Vox-compatibility for most suits, adds species-fitting for clothing accessories, fixes reactive armour sprite update bug...

### PR DESCRIPTION
**Pull request by KasparoVy**
Tidies up the code for mask adjustment, adds the ability to open/close the Clown officer and soldier coats, adds by-species tail hiding, refactors the way the Captain's space helmet shows Vox hair, adds species refit and icon-override handling to suit collars.

:cl:
imageadd: Adds improved Vox mask/goggle sprites.
imageadd: Adds Vox-compatible versions of most suits.
rscadd: Adds species-fitting and icon override handling to clothing accessories and suit collars.
rscadd: You can now open/close Clown Officer and Soldier coats.
rscadd: Adds by-species tail hiding.
tweak: Tidies up and refactors the way the Captain's space helmet shows Vox hair but hides every other species'.
fix: Reactive armour's sprite will now update as soon as you turn it on/off or EMP it.
/:cl:

**Adds improved versions of the Vox sprites for the following glasses and masks:**
- Welding goggles (only affects east/west direction sprites, sprites by **zxpr0jk** d3athrow/vgstation13#10841)
- Sechailer (affects all directions but north)
- Gas mask (only affects east/west direction sprites)
- All wrestling masks (just exposes a bit more of the beak, affects all directions but north).
- Plague Doctor mask (most of the design borrowed from **zxpr0jk** d3athrow/vgstation13#10841, namely everything but the tip of the beak on the east and west sprites and a small adjustment made to the bottom corner corner of the side of the mask towards the face on the east and west sprites)

updatedvoxmasks

**Adds Vox sprites (312) for the following suits and accessories:**
- Unathi robe
- Unathi mantle
- All ERT armour (not the spacesuits)
- Most armour vests (armour vest, reflective armour vest, Security armour vest, bulletproof armour vest, Detective armour vest, Blueshield armour vest, combat armour vest)
- Laser tag vests
- Ian shirt
- Suspenders
- Waistcoat
- Vest
- Most jackets (first responder jacket, bomber jacket, security bomber jacket, black suit jacket, blue suit jacket, purple suit jacket, IAA jacket, NT Rep jacket, forensics jackets, leather jacket, all military jackets)
- Overalls
- Captain's carapace
- Blueshield's coat
- Trenchcoats (black and brown)
- Detective's coat
- Pirate and old pirate coats
- HoS' coat and trenchcoat
- Warden's jackets
- All ponchos
- Hazard vest
- Brigphys' vest
- Reactive armour
- Riot/swat armour
- Heavy armour, thunderdome armour
- All knight armour
- All bombsuits (and a Vox fitted collar for the Security bombsuit)
- Regular and Atmos firesuits
- All biosuits
- Webbing
- Clown officer and soldier coats
- Captain's parade tunic

## MUAHAHAHAHAHA
voxsuits

### CODE REVIEW

**Comment by KasparoVy** [comment]
Suit image and changelog added.

**Comment by taukausanake** [comment]
and then that wall of Vox all skree at the same time...

**Comment by IcyV** [comment]
You are a god damn madman for doing this, Kasparo. In the best way.

**Comment by TheDZD** [comment]
Conflicts.

**Comment by KasparoVy** [comment]
Thanks for the heads up, I'll sort it now.

**Pull request merged**
