### PR TITLE
NT Recruiter: Tweaks and replacing gender with DOB

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Replaces the gender field with Date of Birth (It should match with the candidate age, else its wrong)

Adjusts the game over return to menu button size, making it easier to reach the begin shift right away.

Adds some employment records, all related to companies in our lore.
Removed employment record related to prospero order, it no longer exists.
## Why It's Good For The Game

Genders can no longer be utilized in the game after the PR related to its rework is merged, DOB can be a replacement to keep the number of checks.
## Images of changes

date

return

## Testing

- Played the NT Recruiter arcade and verified that the conditions for winning and losing are correct.
## Changelog
:cl:
tweak: NT Recruiter: Adjusted the game over button size
tweak: NT Recruiter: Some employment records have been added, one has been removed
tweak: NT Recruiter: The Gender field has been replaced with date of birth, you now must verify if it matches with the candidate age
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
> (It should match with the candidate age, else its wrong)

figuring out the current year is somewhat frustrating, there a chance you can add it to the tips tab?

**Comment by Henri215** [comment]
> > (It should match with the candidate age, else its wrong)
> 
> figuring out the current year is somewhat frustrating, there a chance you can add it to the tips tab?

Wont be a problem, you now get the current year at your face when the round starts and when the date of birth is wrong it will be at minimum be 25 years off (still thinking on the values, but i wont make it closer than that) so you dont have to do too much math

**Comment by 1080pCat** [comment]
> Wont be a problem, you now get the current year at your face when the round starts

you see that once at roundstart though..

**Review by Burzah — APPROVED** [review]
Good, following conflict cleanup.

**Review by S34NW — APPROVED** [review]

**Pull request merged**
