### PR TITLE
Blueshield armour no longer refers to the blueshield as a lieutenant

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do

Dishonourably demotes the blueshield from the rank of lieutenant for failing to ensure all the child locks are enabled on the station maint tunnels, allowing the captain to wander into the tunnels where he proceeded to get lost for more than 6 hours until a passing engineer found him curled up in the foetal position crying for help.

Fixes an oversight in #12701.

## Why It's Good For The Game
The blueshield is not worthy of holding the rank of lieutenant.

## Testing
Became a blueshield. Saw my armour. Was sad that I was no longer an officer of the Nanotrasen Navy.

## Changelog
:cl:
tweak: Blueshield's security armour no longer refers to the blueshield as a lieutenant.
/:cl:

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]

**Comment by Henri215** [comment]
> Do you have an actual reason for this?

https://github.com/ParadiseSS13/Paradise/pull/12701

Oversight from this PR.

**Comment by Fordoxia** [comment]
> Do you have an actual reason for this?

Tourte wanted it done and I happened to have VSC open at the time.

**Review by Contrabang — APPROVED** [review]
code is fine

**Comment by matttheficus** [comment]
Its kinda up to the Lore Team, but i actually enjoy having SOME military ranks on-board the Station. Ill be genuinely disappointed to see the title go if that's whats decided for em.

**Comment by Fordoxia** [comment]
> Its kinda up to the Lore Team, but i actually enjoy having SOME military ranks on-board the Station. Ill be genuinely disappointed to see the title go if that's whats decided for em.

Technically it was already #12701, this is just getting an instance that was missed by mistake.

**Pull request merged**
