### PR TITLE
Automatic 5% chance of AI Triumvirate

### PR DESCRIPTION
**Pull request by ZomgPonies**
- 5% default chance of any round starting with an AI triumvirate EXCEPT MalfAI
- Status of Triumvirate available for admins in game panel
- Toggling Triumvirate on/off still accessed via Secrets panel
- Config option to define percentage chance of TriAI happening

### CODE REVIEW

**Comment by Ar3nn** [comment]
YES

**Comment by Fox-McCloud** [comment]
Absolutely not :-1: 

Administratively, this is going to be a lot more difficult to moderate.

Gameplay wise, suprecopping AI's who don't listen to their laws has been a problem for a long while now that's largely not been addressed (as brought up in the admin section of our forums); this is going to make that literally 300% worse as you have far more players covering the same area--not to mention the problems this will bring up if one AI is rogue and the other is not, not to mention the increased confusion for borgs of who to listen to.

This is largely an adminbus tool for a reason for very specific purposes.

**Comment by ZomgPonies** [comment]
- Why would it be harder to morderate? AIs still leave fingerprints everywhere.
- You're talking about a 5% occurence, 1 out of 20 rounds. I fail to see the admin workload go wild over this.
 - Supercopping AIs should be dealt with at an administrative level, not stiffle innovation for a few bad apples.
- Borgs are linked to a specific AI for a reason, that is the AI they obey.
- One AI being rogue shouldn't happen. I'll happilly look over MalfAI to make sure that doesn't happen, or that triumvirate does not happen in a MalfAI round, which would lower the probability of Triumvirate to lower than 5% at the same time.

**Comment by Fox-McCloud** [comment]
- It's easy to say to handle it on an administrative level, but that's just not been the case, as is evidence by our own administrative forums--laws are *barely* enforced and supercopping is never harped on, ever.

- That's still 1 out of 20 rounds where antags aren't going to be able to do jack because of a 300% increase in an all-seeing near all controlling AI---yes, players can make additional AIs, but it requires quite a bit of time and effort to engage in.

**Comment by ZomgPonies** [comment]
- For the administrative concerns, I'd like to hear some feedback from active admins.

- 1 out of 20 rounds where antags have a more difficult time of it doesn't seem like a ridiculous unbalance. It's a 1/20 chance of having to alter your strategy in order to be more subtle.

**Comment by Fox-McCloud** [comment]
You can't exactly alter your strategy against an AI, for the vast bulk of the population---and the only antag that really has tools to deal with AI presence is regular traitor--everyone else just has to put up with 3 times the chance of getting caught.

**Comment by ZomgPonies** [comment]
You're saying that like it's a bad thing. Variety isn't intrinsically negative.

**Comment by Fox-McCloud** [comment]
Variety is very much a good thing, but not when it it makes it arbitrarily picks winners and lowers based on chance. A traitor/cult/shadowling/changeling should lose because of his lack of skill and not because a 5% probability deemed he had to put up with 2 additional all-seeing entities.

**Comment by Elysian-Prince** [comment]
My only  comment would be to nullify the chance during a Malf AI roundtype. A chance for three at the start of that isn't exactly great.

**Comment by FreeStylaLT** [comment]
I would be fine with this if there was a form of global announcement to everyone on the station regarding the occurrence. 

Otherwise, triple AI is not prohibited to be implemented by Research Directors, I do not see why it would be prohibited from happening randomly. 

Rarity can be increased, I would rather have this as rare as once per-two-days than 5%.

I have no grievances with increasing difficulty for antags arbitrarily and randomly, even if extremely rarely, as that is the nature of the game anyway, antags are not set on a linear path to the accomplishment of their objective every single time, there are things that alter their plans that are out of their hands all the time, adding to it just makes the game more fun, either by figuring out additional anti-AI countermeasures or by subverting one of them to sabotage the others, it just adds to the game from my perspective.

**Comment by ZomgPonies** [comment]
Fox - That's a logical fallacy to decide that it is suddenly impossible for antags to win a round due to increased AI presence. Unless you have actual evidence to support that claim, it remains an opinion not a fact.

I on the other hand have been running Triumvirate rounds all week, and from my personal and recent experience I have found no evidence of:

- Antags autolosing
- Increased AI supercopping

**Comment by Spacemanspark** [comment]
FUCK BALANCE, MERGE AHOY!
:+1:

**Comment by tigercat2000** [comment]
I'll toss my input in- I don't see an inherent problem with this, however, I think it once again falls into the territory of something that definitely needs practical testing before declaring it good or declaring it bad.

**Comment by Fox-McCloud** [comment]
I didn't say it was impossible; please don't misconstrue my arguments. I said their round is arbitrarily 300% harder because a 5% probability deemed it as such. There's no logical fallacy here. You have an increase in the amount of near all-seeing entities (that also have control of the station), and things are going to be objectively harder. 

Running it a couple times over the course of a week isn't going to instantly bring up "oh, this is balanced/unbalanced"--a lot of that takes times for it to sink in to players how something impacts the game and how to best utilize it; a number of problemed chemicals, R&D items, and traitor items were fine for the first month or so of their release, then players learned how to better use them and they became hugely problematic.

**Comment by tigercat2000** [comment]
Players don't give a fuck about balance, they give a fuck about how abjectly it fucks people over. Running with an actual 5% probability means that players can form their own opinions playing rounds as nonantags and antags, since it directly affects security, command, and science's jobs as well.

**Comment by ZomgPonies** [comment]
300% harder. I love how you pulled that number out of nowhere. Or am I misconstruing that also?

From my understanding, your solution to balance is "Let's not try anything new, because eventually people will figure it out and skew the balance." Is that correct?

**Comment by Fox-McCloud** [comment]
You regularly have a singular AI. You add two more, That's a 300% increase in presence and difficult for antags during the rounds that this gets selected--it's not that difficult to determine that. This can normally happen if the RD approves of it and finds someone willing, but it rarely happens, and usually doesn't happen until much later on in the shift, due to priorities and the resources involved in creating one.

No; people have been objectively complaining about antags toothlessness, and the AI gets mentioned a lot because of their ability to control the station and see as much as they can. This is a PR that goes in the opposite direction of that, which is why I'm stating what I am. Again, please do not misconstrue my arguments or put words in my mouth.

**Comment by ZomgPonies** [comment]
I will agree that more AIs mean more 'eyes'. Yes it will increase the overall difficulty. TRIPLE the difficulty? I think not. The presence of an AI is not the ONLY variable in determining the difficulty of accomplishing a mission, far from it.

If the fact that the AI is all-seeing is such an issue, perhaps it would be worthwhile to look at how disabling cameras works. Maybe make it easier to disable cameras without alerting the AI to the issue. I believe it's currently too easy for AIs to have a complete overview of what's happening on the station. But that's a discussion for a seperate PR.

Fact is, you can't know if people will like it without testing it out. I've tested it out 4 times in the last few days so far and have yet to encounter anything but positive comments. That's actual feedback, not wishful thinking. How it plays out 1 month, 2 months down the line I don't know, there may have to be adjustments done at that point but considering how little code this PR changes I don't see this as being 'unmaintainable'.

**Comment by TheDZD** [comment]
Just a few concerns with this that need to be addressed if they haven't been already.
- This shouldn't occur during malf AI rounds, because you then either have 3 malfunctioning AIs, or 1 malfunctioning AI and 2 that will completely ruin its plans.
- If at all possible, it would be ideal to increase the amount of cyborgs to 3 on triumvirate rounds, and make sure each AI only has one borg, as being an AI without any cyborgs can be a bit frustrating.
- Both due to the suggestion above, and the fact that there are more AIs, it may be worth increasing the number of antags that round to offset the increased number of AIs/borgs, or compensating the antags in some way (although you can only really do this with traitors and nuke ops, and nukes ops will certainly need more TCs/members.)
- Ensure that it works correctly with the AI assassinate objective.
- Might be a good idea to make sure all the AIs have the same lawset, as having multiple synthetics with conflicting laws can cause *issues*.

**Comment by ZomgPonies** [comment]
I'll update the PR with your suggestions, except for the last one. Right now AIs are assigned random lawsets at roundstart. It's trivial for command to reset them to all use the same one, but at the moment it's hasn't caused problems and has been beneficial for RP.

**Comment by tigercat2000** [comment]
@ZomgPonies I think @TheDZD meant to make sure that when the random lawset is chosen, every AI gets *that* lawsuit, so you don't have a crewsimov AI next to a paladin AI next to a corporate AI, since different lawsets can conflict.

**Comment by TheDZD** [comment]
What @tigercat2000 is correct.

**Comment by ZomgPonies** [comment]
@tigercat2000 Yes I know what he meant. The conflict itself can be a source of RP though.

**Comment by Ar3nn** [comment]
What Fox said about antags having to deal with AIs being an incredibly difficult part, I feel is rather wrong, and scales with player skill on the antag part. It takes about five minutes to learn and soft-memorize wires on doors and about twenty seconds per door once thats done to disable AI control, release bolts and open the door. I've had maaaaaany rounds where i felt entirely powerless because no matter how far ahead I was of the antag bolting doors, they could cut through my net whenever they felt like it, and I couldn't keep up with them delaying them and keep security appraised of their location, et cetera. Even if at this point I ignore crew requests to prioritize the antag, I don't really know how to counter a dude with a pair of gloves and cutters.

**Comment by Fox-McCloud** [comment]
*if* this is to go through, then please make this into a config option so it can be easily turned off, if wanted; much like how AI laws can be made random or the same thing every shift.

**Comment by Earthdivine** [comment]
I don't see where the "this will make antags jobs harder" argument comes into play. If this was the case, then you wouldn't be able to churn out AI after AI from RnD in less then 30 minutes into the round. All this really does is make those opening minutes harder, but after that it'll be the same as any other round that Robotics decides to go full ham.

**Comment by Robertha89** [comment]
I have antagged with 1 ai, and 11, the only antags that will have an problem is wizard, nuke squad and shadowling, but that was already thrown out the window when random lawset was introduced, and asimov turned into crewismov, remember originally, everyone had protection from the ai and it's borgs, even nukesquad, wizard, and any non-crew member, i mean, there is literally nothing that prevents a crewismov ai from outright murdering ert, cause they are not crew, but i digress, and it is outside the scope of this pr... 

So, lets get down to brass tacks as they say, will this allow for tripple malf AI?

Also, do remember this, just because tripple ai is activated, odes not mean there are 3 players that want to join as ai.

**Comment by Plotron** [comment]
The problem is that you get shitty AI half of the time. There is a handful of competent AI players, and usually they play a couple rounds in a row. Others go AFK quickly, are inexperienced, slow or unresponsive - warranting a replacement from RnD - and even then you need a good volunteer.
Most AI players are incapable of supercopping. It's better to assume that you won't get 3 highly competent AIs in a single round. It's more like getting a backup or a spare, or a higher chance of having a decent AI that will shine and do things efficiently.

**Comment by Spacemanspark** [comment]
As a player that's actually played in multiple rounds with 5 or more AI's, as one of the AI's, I can tell you it's not as bad as you might think. AI's tend to trip over each other trying to fulfill requests, as much as they try to work together. It's always hilarious, and quite honestly, I'd really be glad to have this.

**Comment by Keilden** [comment]
A 300% incease would be 4 ais.

**Comment by ZomgPonies** [comment]
Alright, updated desc

**Comment by Ar3nn** [comment]
COMPLETELY off topic, but I keep seeing in a bunch of places (including above on this thread) that asimov was removed. This is not so, I believe its on the bottom right of the AI upload, under OxygenIsToxicToHumans, OneHuman and Purge. I just checked, actually, and it is. @Robertha89

**Comment by Plotron** [comment]
Spacemanspark also pointed out one thing I haven't included in my first comment.
Having 3 AIs does not mean having 3 times the coverage. If something loud or big happens, it's guaranteed that you will have at least one AI tending to it. Since Ais do not see each other's eyes, cooperation via text would be necessary to cover more area: "You take care of the situation in Sec, I do crew requests".

**Comment by Markolie** [comment]
Just to have this on record as there seems to be controversy surrounding this: it's worth noting that I am very strongly against this. In the past I've already stated that I think there's way too many supercops AI on Paradise that ruin the gameplay of antagonists (just see some of my recent forum posts). Having a chance of having three AI's will make it even more difficult for antagonists to do their thing. Have fun dealing with three AI's with Nuke Ops!

Until we start properly enforcing AI laws and reduce the amount of supercopping going on (even AI's on crewsimov supercop) this is a bad idea.

**Comment by tigercat2000** [comment]
Is "practical testing" a term that everyone thinks actually means "terminal cancer"?
The **only** way to tell if this is a terrible idea is having it merged and fucking trying it out, 5% probability is extremely low.
If it's so fucking horrible that it ruins the server (it isn't) then it can be reverted with 6 clicks and a patch.

**Comment by ZomgPonies** [comment]
It's a config option, so downstream servers will be able to choose wither to use it or not, There's no reason not to merge in the -codebase-. However if you'd like to discuss it's use on Paradise itself, as Tiger said we'll need to test and see.

**Comment by FreeStylaLT** [comment]
As said earlier, I :+1: this, even if only for testing.

**Comment by Rumiluntti** [comment]
Why the hell not?
Would give more uses for that AI detector thingey that never gets any love unless got from surplus crate.

**Comment by Kharshai** [comment]
Was asked for opinion, so :+1: because it sounds pretty fun.

**Comment by Finalsong** [comment]
:+1: no reason not to

**Comment by Spacemanspark** [comment]
:+1: Just do it.

**Comment by Plotron** [comment]
Since it's a config option, add it just like we've been adding new Nations and paranormal things.

**Comment by ZomgPonies** [comment]
Two maintainers are against this. Two headmins, and about 10 other random people are for.

**Comment by Earthdivine** [comment]
Whoops I never actually said it, my bad, but I honestly don't like this. It makes the station radio feels cluttered when there's more then one AI when the RD decides to pull his stunt, I would rather it be a player decision to add more AI then an RNG thing.

Also 2 maintainers against, one for.

**Comment by Fishocalypse** [comment]
Shitty rng that decides a gamemode is already a huge shitstorm when it comes to disarms; as seen in how easy it is to fuck over nukeops with lucky disarms(this ignores that it requires you to go into CQC against an armed combatant with a gun, and likley a shotgun while being able to disarm them and win). 

Not to mention traitor AIs having the other two AIs will foil your plans at every step. Due to their access, they are essentially able to destroy your borgs and counter ALL the damage you can attempt to do. Good luck doing "Make sure no organic life forms get on the emergency shuttle"!

Also completley obviously ignoring how one or two retard AIs can get you destroyed/fucked over because of how they act.

This just seems like something to add because XD LOL RANDUMB SUPER FUNNY!!!!!

**Comment by ZomgPonies** [comment]
My new mantra is not to fight for shit that's not important, so...

**Pull request closed without merging**
