### PR TITLE
TG sprites for mining_drone

### PR DESCRIPTION
**Pull request by Tilk1**
TG sprites for mining drones

This Includes a new sprite set for the mining drone. In my opinion it looks a bit better.

**Needed to add movement** since TG mining drone DOESNT have movement sprite

minebot_old

minebot_new

Old sprite wasnt removed at all, just added  _old   at the end of each sprite

:cl:
imageadd: added mining drone sprites
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
Why sneak in the grevious bot sprite?

**Comment by Nicaragua1** [comment]
> Why sneak in the grevious bot sprite?
> 
> 

HOLY! that was a project i was working with. I feel so embarassed now. Sorry

**Comment by Ty-Omaha** [comment]
Ah lol

**Comment by Nicaragua1** [comment]
> Ah lol

wasnt there a honkbuddy sprite added too?

**Comment by KasparoVy** [comment]
Wait wtf we have like four more reactions

Brilliant. Big sprite upgrade

**Comment by taukausanake** [comment]
I really want General Grevsky. Rather name it Griefsky to be honest though

**Comment by Nicaragua1** [comment]
@taukausanake grievous is only used in the sprites. In game its general beepsky. Parody from star wars, general kenobi

**Comment by taukausanake** [comment]
I was under the assumption that he actually used the eswords and shredded criminals. In fact yeah, [that's what the PR did](https://github.com/tgstation/tgstation/pull/39382/files) unless they don't run it anymore

**Comment by taukausanake** [comment]
I was saying a better name would be one that paid more homage to Grievous rather than just another Beepsky. I mean We have Pingsky, Buzzsky, Armsky, and Ofitser apparently. I'd think a new member of their family would be nice

**Pull request merged**
