### PR TITLE
Makes Drones and Swarmers unaffected by radiation

### LINKED ISSUE #15567: Swarmers can be irradiated.
Swarmers can become irradiated,

**What did you expect to happen**: 
Swarmers shouldn't be able to become irradiated.

**What happened instead**:
They became irradiated.

**Why is this bad/What are the consequences**:
They can now break the law to not harm the occupants of the station if they become irradiated. Thus allowing them to passively kill if they become irradiated, and stun someone and just chill next to someone while repeatedly stunning.

**Steps to reproduce the problem**:
Stand near the supermatter as a Swarmer

**When did the problem start happening**:
Saw it during a swarmer round

**Extra information**:
This hasn't happened, but if I thought of it, others will think of it, and others might try and stretch the rules.

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds Maintenance Drones and Swarmers to the list of things unaffected by radiation.
Fixes #15567

## Why It's Good For The Game

Maintenance Drones shouldn't need to break their laws to fix the SM.
Swarmers shouldn't be able to kill people via radiation poisoning.

## Changelog
:cl:
tweak: Made Swarmers and Maintenance Drones unable to be irradiated.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This isn't the way to do it.

There's specific flags for it.

**Comment by SabreML** [comment]
> This isn't the way to do it.
> 
> There's specific flags for it.

Could you let me know what those are then? I'll change it to use them instead.

**Review by Kyep — APPROVED** [review]

**Comment by SabreML** [comment]
Pinging @Fox-McCloud for clarification so that this can get done.

**Comment by dearmochi** [comment]
Most likely giving the `TRAIT_RADIMMUNE` trait

**Comment by Fox-McCloud** [comment]
`flags_2 = RAD_PROTECT_CONTENTS_2 | RAD_NO_CONTAMINATE_2`

**Review by dearmochi — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
