### PR TITLE
Shadowstep and Mist icons improvement

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Updates sprites and animations for Shadowstep and Mist vampire abilities.

## Why It's Good For The Game
Abilities didn't really have vampire aesthetics, this PR fixes that.

## Images of changes
Screen Shot 04-04-21 at 01 14 PM
mist_out

## Changelog
:cl:
tweak: Update on sprites of vampire Mist and Shadowstep abilities 

/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
I REALLY like that mist animation, looking forward to seeing all the conflicts removed so this can be implemented

**Comment by McRamon** [comment]
Will remake the pr

**Comment by Necaladun** [comment]
Lovely.

**Comment by Fox-McCloud** [comment]
Please update or this will be closed.

**Pull request closed without merging**
