### PR TITLE
Ensures Tildes Properly Cause Brain Damage

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ensures tilde usage properly causes brain damage.

@Rumiluntti http://www.nanotrasen.se/forum/viewtopic.php?f=12&t=7756

Fixes a grave problem in the codebase and on the live server.

img

:cl: Fox McCloud
fix: Fixes the serial tilde abuse that exists that wasn't causing brain damage
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Lmfao, fuck yes. Please, this is something we actually need.

**Comment by QQCucumber** [comment]
Oh good, more ways for shitters to cause self-harm and confusion + work for medical. :-1:

**Comment by LittleBigKid2000** [comment]
RIP Neri

**Comment by KasparoVy** [comment]
It should be easy to tell who the tilders are, given some time. Plus, the tell-tale massive brain damage with no physical or toxin damage, of course.

**Comment by QQCucumber** [comment]
Bear in mind there are initiatives to try to remove the suicide verb on the forum and move the light bulbs out of containment cells so you can't kill yourself on them. I don't think this is going to be welcomed.

**Comment by KasparoVy** [comment]
People getting salty and overreacting from a light-bulb misclick or their wanting out of the round is hardly similar to punishing ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~memays-uguu

**Comment by QQCucumber** [comment]
As if the tide would think this is a punishment. They're going to love the extra attention from medical.

**Comment by KasparoVy** [comment]
"It should be easy to tell who the tilders are, given some time (if you don't know already). Plus, the tell-tale massive brain damage with no physical or toxin damage, of course."

**Comment by QQCucumber** [comment]
Again, getting extra attention isn't a punishment to some people.

**Comment by KasparoVy** [comment]
Different keystrokes for different folks.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by CrAzYPiLoT-SS13** [comment]
Oh my God, yes. This is the most useful feature that's been proposed to the
repo in a while. :+1:

**Comment by Rumiluntti** [comment]
Thank you Fox!

**Comment by fludd12** [comment]
Cue people going chemist or scientist just so they can use tildes forever.

**Comment by DavidRossii** [comment]
Yay!~

Merge already!~

P-Please?~

**Comment by DaveTheHeadcrab** [comment]
So when are we going to tell @QQCucumber that this PR is very obviously a joke?

**Comment by CrAzYPiLoT-SS13** [comment]
I very much want this PR to be real.

**Comment by Necaladun** [comment]
This wasn't already in? If not, then why did people who use them speak like they're brain damaged anyway?

**Comment by Aurorablade** [comment]
MERGE IT MERGE IT NOW

**Comment by johannhawk** [comment]
well, time to find a wickerdoll and force people to use tildes until they die from brain damage.

**Comment by NTSAM** [comment]
Make fake stuttering do this too pls

**Comment by CrAzYPiLoT-SS13** [comment]
Also, netspeak and emotes :DDDD

**Comment by NTSAM** [comment]
y-yeah :D ~

**Comment by KasparoVy** [comment]
"This wasn't already in? If not, then why did people who use them speak like they're brain damaged anyway?"

Raw as fuck Necaladun bahahaha

Reminds me of the time a rando said kek fam to my face

**Comment by ExitGame** [comment]
Yes.

**Comment by taukausanake** [comment]
Why is it the really dumb edits are so easy to code in?

You know what? Fuck it. Excessive tildes, alright but don't make it too crazy. 
> Fludd12: "Tildes used in moderation are nice."

Man, I can't believe I'm actually okay with something like this

**Comment by tigercat2000** [comment]
@taukausanake

**Comment by taukausanake** [comment]
But memes are eternal

**Comment by TheDZD** [comment]
100% necessary feature.

**Comment by fludd12** [comment]
Guys, it took me this long to realize that "grave problem" is a pun. " ` ", the symbol you shift-press to get a tilde, is a grave.

**Comment by Verarch** [comment]
you're slow

**Comment by monster860** [comment]
\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`

Now THAT'S a grave problem.

**Comment by monster860** [comment]
We've got Morgue Conflicts here!

**Comment by Tastyfish** [comment]
ᵯḛᵯḛs̃

**Comment by Fox-McCloud** [comment]
Merge conflicts fixed.

**Comment by Allfd** [comment]
:+1: x :100:

**Comment by KasparoVy** [comment]
Now that's what I'm talking about.

**Comment by Svej** [comment]
Yes please :+1:

**Comment by Asanadas** [comment]
:100: :+1:

**Comment by Iamgoofball** [comment]
porting this to tg

**Comment by KasparoVy** [comment]
:100: :+1:

**Comment by Earthcrusher** [comment]
> You feel dumber for having spoken in such a mannerism.

Manner, not mannerism.

**Comment by Fox-McCloud** [comment]
self-merging this now.

**Comment by TheDZD** [comment]
RIP the best meme PR that has ever lived on this repo. You died bravely.

**Pull request closed without merging**
