### PR TITLE
Shadowling Passive Healing now heals eye damage

### PR DESCRIPTION
**Pull request by TullyBurnalot**
Exactly what it says on the title.

EDIT: This is a response to the fact that spamming flashes near Shadowlings more or less turns into a battle of attrition that inevitably ends with the Shadowling going blind unless they also manage to get a thrall to perform eye surgery on them.

EDIT 2: Even with this change, blinding Shadowlings is fully possible, albeit only temporarily, so the flash spam is still a viable way of quickly getting rid of a Shadowling. They will not, however, be permanently fucked because of it.

:cl:
add: Shadowlings now passively heal eye damage, eye blurriness
/:cl:

### CODE REVIEW

**Comment by StreakyHaddock** [comment]
i like this way more than nerfing flashes. 10/10

**Comment by Birdtalon** [comment]
100% yes.

**Comment by SamHPurp** [comment]
I have two things to say:

Fuck yes.

And fuck you Mike Murdock.

**Comment by Hylocereus** [comment]
YES. There is nothing more frustrating than a validhunting IAA or civvy that nicked a flash just running into maintenance and spamming the flash AOE. It happens at least once a round. I eventually resorted to not even hatching as a shadowling until I had a stock of oculine pills, which is a bit of a nuisance. 

Saying that, while we're looking at shadowling passive healing, there's an... Issue? Currently where a shadowling attempting to heal themselves using rapid rehatch of clone damage will actually kill themselves. It gives you the "something is not right with your -body part-" and then you drop dead. It seems to mostly happen with the head and torso, though I also dropped dead trying to regenerate an arm as well after being mobbed by slimes.

**Comment by TullyBurnalot** [comment]
@SamHPurp Personal attacks are unwarranted and unnecessary.

**Comment by TullyBurnalot** [comment]
@Hylocereus That is currently outside the scope of this PR, as all I did was emulate the effects of Oculine. Gonna have to get someone who actually knows what they're doing to fix anything more complex.

**Comment by scrubmcnoob** [comment]
https://www.youtube.com/watch?v=xrqdduneB-o

**Comment by SamHPurp** [comment]
@TullyBurnalot Sorry, was meant more as an inside joke between the two of us, with zero ill will.

**Comment by TullyBurnalot** [comment]
@SamHPurp Apologies then. If it's an inside joke, then feel free to bring out the thesaurus.

**Comment by mrturkeytoe** [comment]
I worry this will make shadowlings even more OP. Flash spam was basically the only option people had and I think that's why it is so 'abused'.

**Comment by Birdtalon** [comment]
Flash spam which wrecks your eyes for the rest of the round and makes playing as a Shadowling miserable unless you make some Oculine is not the weakness they need however.

**Comment by TullyBurnalot** [comment]
@mrturkeytoe You can still blind Shadowlings for up to a _minute_ via flash spam. It's just that now they can actually lick their wounds rather than being screwed over semi-permanently.

**Comment by mrturkeytoe** [comment]
I'd make it take like, three minutes. Personally.

**Comment by TullyBurnalot** [comment]
The flash still works as an emergency Shadowling repellent. There is little reason to make it last that long beyond "Fuck you, Shadowlings".

**Comment by mrturkeytoe** [comment]
Well I'd imagine a conflict would go one of two ways, one side gets roflstomped or the ling gets blinded/seriously hurt then shadow steps/whatevers away . I think that damage should have some staying power so they have reason to be careful instead of instantly being back at full health in a few seconds.
As it stands this tips the balance even further in their direction than it already was.

**Comment by TullyBurnalot** [comment]
Assuming the worst case scenario, it's not "a few seconds", it's a full minute. This gives people plenty of them to run off and/or regroup.

It's one thing to have staying power, another to irrevocably screw over the Shadowlings unless they secure Oculine or an OR. Flashes are still functional, just not a be-all-end-all.

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
