### PR TITLE
[WIP] Medical Doctor Hypospray

### PR DESCRIPTION
**Pull request by Robertha89**
This adds a hypospray intended for medical doctors, and contains Saline-Glucose Solution on spawn. 
This is here to help doctors, and make it a bit easier for them, as it's already rough, and that little extra will help, and the list of drugs is a rough draft, some of the meds you can od on will probably be modified pending feedback.
Currently the allowed list does not work, i suspect due to it being a datum, and allowed is for objects.
Any help to get the restricted list of reagents to work would be greatly appreciated
Other changed to come include adding it to spawn in backpacks/pockets of medical doctors and paramedic, make sure it does not count as a steal objective, and possible give the CMO hypospray a minor makeover.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Make it buildable via RnD, otherwise if this spawns on doctors or in medbay it's a power creep.

**Comment by Robertha89** [comment]
Making it buildable by RnD was something I did not think about, but currently i need to figure out how to code something that checks if the reagent added is in the list of allowed ones, and denying other attempts.

**Comment by Fox-McCloud** [comment]
I like the idea, but not this particular implementation.

Ideally they should be this:
- remove banned reagents on insertion (while leaving the allowed ones alone)
- give a notification to all in the area of how many units were injected+the primary reagent injected (meaning if you had 16 units of charcoal and 14 units of mannitol, it would only say the person is injected with mannitol)---"Fox McCloud injects Joe McAssistant with 25 units of Charcoal!"
- play a sound on inject
- be emaggable, which would remove their ban list.

This resolves a LOT of issue with the current hypospray while still allowing it to be used as a viable medical treatment device---and as a less stealthy alternative to the sleepy pen.

**Comment by veganzombeh** [comment]
I think the best way of doing it would be that it draws in reagents in a similar fashion to syringes, and the check for allowed reagents would go there. I'd also agree with Fox's suggestions too.

**Comment by Krausus** [comment]
Reagent containers use `banned_reagents`, like so:
`banned_reagents = list("facid","sacid")`
Which results in messages like this:
> A chemical in the large beaker is far too dangerous to transfer to the hypospray!

You *could* fill that list with every reagent except the ones you want, but that'd be a bit ridiculous. Like Fox suggested, it would probably be pretty easy to give them an `attackby` that checks their reagents and deletes any that aren't whitelisted. I'm not actually sure whether `attack` (used by the beakers you'd be filling the hypospray with) is called before `attackby`, but I think a `spawn(0)` (or 1?) would make that irrelevant.

Checking for addiction/overdose thresholds is something you can do in the hypospray's `attack` proc; check how much of the reagent(s) would be transferred, compare to what's already in the target, and fail if the sum would hit one of the thresholds. Of course, if the safeties are disabled, this check would simply be skipped.

This is just nitpicking, but it seems silly for the CMO to be using an "Ancient Hypospray", especially since it's meant to be a high-risk theft target. I'd give them a fancy "Prototype Hypospray", with the safeties disabled for the purpose of "testing new, experimental medicines". It would be kinda weird for it to have no other advantages over the standard hyposprays, though.

**Comment by Fox-McCloud** [comment]
Don't use banned_reagents.

It's terrible, is only a minor stop-gap and is likely to get removed (I just haven't gotten around to it).

**Comment by Robertha89** [comment]
Currently trying out ```if(!istype(``` but I am not sure if what reagents are defined are or where they are. 
Im thinking about making a ```/var/healingchems = list(reagentshere)```, but not sure yet how it works regarding datums, so playing around with istype.

**Comment by veganzombeh** [comment]
You might want to try something like `if !(reagent.id in healingchems)`. That may be better than checking the type of each allowed reagent.

**Comment by Iamgoofball** [comment]
if(is_type_in_list(/datum/reagent/poo, poop_list))

**Comment by Fox-McCloud** [comment]
How's progress on this, or have you abandoned it?

**Comment by Robertha89** [comment]
Still working on it, and haven't progressed much farther, as the bit that checks the reagents against the list of allowed ones aint reading the list, got some tips from tigercat imma try out, but from what I see, it's not something i will finish any time soon.

**Comment by ZomgPonies** [comment]
Re-open the PR once this is ready for merge, if ever.

**Pull request closed without merging**
