### PR TITLE
Edits Arrival Cafe

### PR DESCRIPTION
**Pull request by orelbon**
Makes the Arrivals checkpoint viable. 
capture

### CODE REVIEW

**Comment by Lady-Luck** [comment]
I'd rather we just got rid of the checkpoint, honestly. Though lord only knows what should be there instead.

**Comment by Fruerlund** [comment]
Very cozy

**Comment by orelbon** [comment]
Could someone with more knowledge about Travis let me know what the error here signifies?

**Comment by Crazylemon64** [comment]
Did you happen to make this edit on an old version of the map?

The errors are about a lot of paths that don't exist anymore being in the map you've PR'd.

**Comment by SamHPurp** [comment]
Checkpoint is useful @Lady-Luck gives joining sec officers a place to gear up if sec is somehow compromised.

**Comment by orelbon** [comment]
@Crazylemon64 Ah yeah, probably. I made the edit and realized the branch wasent up to date.

**Comment by orelbon** [comment]
Ill close this and put it back up in a fresh branch.

**Pull request closed without merging**
