### PR TITLE
Removes war crimes from nurse hat

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Removes war crimes (red cross) from the nurse hat

## Why It's Good For The Game

war crimes are bad

## Changelog
:cl:
fix: Changes the nurse hat to not cause war crimes by changing it's colour.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
https://www.redcross.ca/about-us/about-the-canadian-red-cross/red-cross-emblem/it-may-just-be-a-game-to-you-but-it-means-the-world-to-us

**Comment by LightFire53** [comment]
People can thumbs down all they want, would rather not have to report emblem misuse to the people I am associated with through work

**Comment by AffectedArc07** [comment]
> People can thumbs down all they want, would rather not have to report emblem misuse to the people I am associated with through work

This.

I am not afraid to lock this PR if people start to argue over things.

**Review by AffectedArc07 — APPROVED** [review]
Speedmerge approved by @DoctorDrugs

**Pull request merged**
