### PR TITLE
Fixes a double airlock at the Syndicate jail

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Fixes this:
airlock bug
By removing one of the airlocks.

## Why It's Good For The Game

While the Syndicate jail *is* meant to be very secure, I'd argue that phasing two doors inside eachother is a bit much.

## Changelog
:cl:
fix: Fixed a double airlock at the Syndicate Contractor jail.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
You, sir, have angered the Syndicate.
You sir, go to _double jail_.

**Comment by Mitchs98** [comment]
Makes you wonder why the Syndicate needs to steal NT tech if they have mastered the art of door phasing.

**Comment by hal9000PR** [comment]
> Makes you wonder why the Syndicate needs to steal NT tech if they have mastered the art of door phasing.

you see, they need to get TRIPLE jail.... science has no limits

**Comment by Mitchs98** [comment]
> > Makes you wonder why the Syndicate needs to steal NT tech if they have mastered the art of door phasing.
> 
> you see, they need to get TRIPLE jail.... science has no limits

The horror.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
