### PR TITLE
Nano Obssession: Chromeless window, Styles

### PR DESCRIPTION
**Pull request by tigercat2000**
Does the following:
 - Adds 'chromeless' mode (NanoUI defaults to using this)
  - Window borders disappear, replaced by in-browser elements for
    minimize/close/move/resize.
  - You *must* move/resize slowly when using this mode, or it can have
    unexpected results, as the JavaScript cannot keep up as well as the
    native windows movement.
 - StatusGroups are now transparent: This looks nice. That's about it.
 - Body background switched to a .svg format for the NanoUI Logo.

 - Coder things:
  - Nano's JavaScript now has a new class, NanoWindow
   - NanoWindow handles all of the chromeless work. It'll be used to
     replace portions of NanoStateManager later.
 - Layout-based CSS has been removed. It was getting in the way, for basically no use, as every one of the 101 UI's we currently have use the default layout.

### Required SQL Changes:
```
ALTER TABLE `paradise`.`player`
ADD COLUMN `nanoui_fancy` smallint(4) DEFAULT '1'
```

### CODE REVIEW

**Comment by tigercat2000** [comment]
# Screenshot section
pretteh
pretteh
pretteh
pretteh
pretteh
pretteh
pretteh
pretteh
pretteh
pretteh

**Comment by Regen1** [comment]
Retro mode text is very hard to read, even more so if you're colorblind.

I suggest looking into brighter contrasts for that.

**Comment by Earthdivine** [comment]
>Retro Mode

Kinda the point of it, is it not?

**Comment by tigercat2000** [comment]
@Earthdivine No real way to trigger the fancy nano off from the PDA code

**Comment by Regen1** [comment]
>Kinda the point of it, is it not?

No, it's supposed to look like the old style, not be unreadable

**Comment by Fox-McCloud** [comment]
All the yes.

tgUI is so nice looking.

**Comment by tigercat2000** [comment]
@Fox-McCloud
tigerUI*
:smirk_cat: 

I'm not sure what you mean though, the fancy window is comprised completely of additions, all toggling back to the "old" mode does is give you back the default windows border and turn off a few elements.

**Comment by tigercat2000** [comment]
new retro PDA: rawr

**Comment by Tastyfish** [comment]
What happens when you scroll on windows that scroll?

**Comment by tigercat2000** [comment]
@Tastyfish a giant ugly IE scrollbar appears and it works fine

**Comment by Tastyfish** [comment]
I meant, does the titlebar disappear?

**Comment by Spacemanspark** [comment]
Only issue I can see with this is that those X buttons to close out are slightly difficult to click on, having messed with them on /tg/ a bit.
Otherwise, :+1:

**Comment by tigercat2000** [comment]
@Tastyfish Yeah, probably, the buttons are all position: absolute

**Comment by Tastyfish** [comment]
It should probably be `position: fixed` if ie8 handles that correctly

**Comment by tigercat2000** [comment]
@Tastyfish i doubt IE does, but more importantly, I would rather not fuck with the default template too much

**Pull request merged**
