### PR TITLE
Reroutes all Atmos pipes (Scrubbers / Supply)

### PR DESCRIPTION
**Pull request by FreeStylaLT**
It's been finally done!

A different, neutered version of #8469

This PR's goal is to establish and maintain an atmos piping standard for the map and maps to come.

### BEFORE:
img

### AFTER:
img

Main changes:
- Rerouted all atmos pipes to go under doors and almost never through walls unless there is no other choice.
- Connected all departments' atmos through the central hallways, you can now ventcrawl to any department reliably from the central hallway.
- Added redundancies to major departments through atmos, where the central hallway line connects to maint.
- Connected all (most, where possible) non-major areas through maint only.

Minor changes:
- Added a 'standard scrubber instance' -- to be used for, well, standard scrubbing. This is to reduce potential confusion / unfortunate accidents, as other instances have different settings.
img
- Replaced all vents with the '/on/' subtype, again to reduce potential misuse due to different settings throughout the instances.
img

This should result in a far **far** easier time understanding, following and ventcrawling through the pipes, and increase the reliability of major departments' atmos after emergencies, due to the added redundancies.
**Changelog:**
:cl:FreeStylaLT
tweak:Laid some pipes in the station. (Rerouted all atmos)
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
YOU MAD MAN
YOU DID IT
YOU KILLED THEM ALL

**Comment by datlo** [comment]
This might be out of scope for this PR, but could you fix the nonsense of virology being on a separate supply network but not separate scrubber network? It should either be connected or disconnected on both pipes.

**Comment by Superhats** [comment]
Makes vent crawling much less of a mess. :+1:

**Comment by rb303** [comment]
Yeeeesssss. No longer will medbay be a confusing mess to sneak into as a terror spider for my nefarious deeds.

**Pull request merged**
