### PR TITLE
Slot Machine Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Credit to Goon for the sounds and for the basic probability balancing

Updates the slot machines to be a lot more like Goon's in terms of probability, payouts, and sounds (our original slot machines seem to have come from Goon, it seems).

Jackpot is now 1,000,000 and the lowest you can win is now 10---that said, the cost to play is now 10, as well.

:cl: Fox McCloud
rscadd: Updates slot machines to have higher jackpots and more payouts with more interesting sounds
/:cl:

### CODE REVIEW

**Comment by Earthdivine** [comment]
I have to say the old sprites fit the bar better then blue on brown/grey.

**Comment by Kerroman** [comment]
Would it be possible to make these movable if they were, say, unwrenched from the ground?  I've seen lots of bar (and maint bar) redesigns get messed up because unmovable slot machines got in the way.  If there's a worry about people stealing the slot machines from the bar then make them ID-lockable (like the emitters in the engine containment room) but you have to have Bartender access to lock then in place and unlock them before they can be wrenched and moved.

**Comment by TullyBurnalot** [comment]
Mechanically, this seems better, but I do have to say I much preferred the old sprites over these ones.

Any way to simply use the old sprites?

**Comment by Fox-McCloud** [comment]
Yes, I can re-implement the shitty sprites if you guys are so damn attached to them.

**Comment by Earthdivine** [comment]
Who cares about low detail? It looks much more in tune with the bar background.

Blue does not work with brown, particularly that shade of it. It will stick out like a sore thumb.

**Pull request merged**
