### PR TITLE
Removes huge mapping inconsistency & headache / Free will strangle anyone who uses these fucking instances in the future

### PR DESCRIPTION
**Pull request by FreeStylaLT**
This PR removes all instances of turfs that have a warning stripe in their _icon_ for no fucking reason with the appropriate turf and actual decal in every map.

This does _not_ remove the actual sprites, I would rather leave that for another PR.

Specifically _these:_
img

## WE HAVE NO REASON TO USE INSTANCES WITH A BAKED-ON WARNING STRIPE

# IF YOU DO IT I WILL FUCKING FIND YOU

No changelog because as far as gameplay is concerned, nothing has changed. This is entirely back-end.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
While this is much appreciated (thank you!). I would note that your anger is a bit misplaced here.

These were almost never intentionally utilized over the decals; the decals just plain didn't exist for most of SS13's history; @nienhaus was kind enough to make the decal sprites and add them about 3 years ago.

**Comment by FreeStylaLT** [comment]
I'm not really upset at anyone I just felt like ranting because of how impractical the process for this PR was tbh

**Comment by taukausanake** [comment]
Makes me wonder if there is a way to better separate sprites apart from one another so you don't get duplicates in different turfs. I mean the floor file is already a nightmare, much like many other .dmi files

**Comment by SamHPurp** [comment]
Agree with this PR. but also agree with @Kyep, if nobody is to use them.... bin em.

**Comment by taukausanake** [comment]
If we're on the topic about turf icons, can someone explain the difference between the shuttle triangle corners that are by themselves and the same icons with a space background attached? Those too might be a bit confusing

**Pull request merged**
