### PR TITLE
Wizard den remap

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Gives the wizard den a remap to add theme and ambience, while not going overkill as to distract the wizard from his objective.

## Why It's Good For The Game
The current wizard den is a little lame, quite frankly. It's fully bright, surrounded by uranium, has poor flow, and doesn't feel "real".
This remap intends to get wizards into the wizarding mood by giving them ambience, a touch of comfort, and a sense that they are a real person in the universe.

Our CC z-level is big enough to support this comfortably. I did not make it too large so as to distract the wizard from the station, but made it just big enough to feel real.

Also, the wizard ghost council can now sit in a cooler location to discuss dchat salt.

## Images of changes
Untitled-1

## Testing
Loaded in, wizard-ed about

## Changelog
:cl:
tweak: Wizard den gets a facelift
fix: Fixed non-lockable cabinet doors being wonky
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
Minor nitpick, but could the room to the left from spawn be made a bit more obvious? The door might blend in with the walls and people could miss it.
Otherwise very nice looking remap

**Comment by Contrabang** [comment]
Ghost council needs 8 ghosts instead of 6 to summon a wizard? Clearly a wizard nerf smh /s

Also yeah, the sandstone doors are hard to distinuish from the walls. Maybe wood or curtains would be better?

**Comment by S34NW** [comment]
Also, the bookcases will be filled on live, I just don't have any books locally

**Comment by datlo** [comment]
Local grey wizard takes a shower and fucking dies before leaving his den.

:+1:

**Review by Miraviel — CHANGES_REQUESTED** [review]
- this tile has two doors:

image

- door names are not capitalised, it seems like a server-wide custom to have them capitalised (Changing Chamber, Main Chamber)

**Review by Miraviel — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
