### PR TITLE
Assorted Vox Masks

### PR DESCRIPTION
**Pull request by KasparoVy**
The first four commits are negligible and were done just to get the branch back up to date.

**Adds:** Security gasmask, sexy mime mask, bandanas, balaclava, welding gas mask and wrestling masks for Vox. Added adjusted-state sprite for the Vox breath mask.

**Removes:** A duplicate of the human balaclava sprite.

**Modifies:** Vox plague-doctor, fake moustache, sterile and medical mask sprites to fit the Vox anatomy and animates the Vox SWAT mask. Corrects the names of some Vox mask adjusted-state sprites.

>**PREVIEW:** *Image much too large to fit on this page.*
http://i.imgur.com/yqChWbL.jpg

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
You should have updated your branch before committing anything.

If you have a local clone set up as per the tutorial [here](https://help.github.com/articles/set-up-git/), you can utilize the git shell commands git pull upstream master and git push to automatically download, merge, and commit the latest revision of the code to your fork.

This will avoid having cases like this where you have 4 commits of "updating" that will just clutter commit history for the files.

**Comment by KasparoVy** [comment]
It's all set up already, I just forgot to do git pull upstream master
RIP

I'll definitely keep it in mind for next time

**Comment by TheDZD** [comment]
Also, if you want to update a branch and toss away any commits not on master (such as the first commit in this PR), simply use:
```
git fetch upstream
git reset --hard upstream/master
git push -f
```
This will sync you up with upstream entirely, and will mean you don't have any rogue commits. Also, it would be a good idea to make PRs off of branches other than master.

**Comment by KasparoVy** [comment]
Thanks for the tips, greatly appreciated. I'll work that stuff in for my next PRs and hopefully they'll be a lot cleaner

**Comment by tigercat2000** [comment]
@TheDZD depending on what git version they use, git push -f might not work, a safer option is `git push origin master -f`

**Comment by TheDZD** [comment]
@tigercat2000 according to the [Git documentation](https://git-scm.com/docs/git-push), it defaults to the origin, also you don't want to push to the master branch if the PR branch isn't the master branch.

**Comment by tigercat2000** [comment]
@TheDZD I guess so, but in my experience at least, git bash yells at me for trying to force-push without any remote and branch args

**Comment by KasparoVy** [comment]
Hopefully my version isn't too finicky.

**Comment by Tastyfish** [comment]
If you haven't pushed anything to github yet, you can update over your branches that already have new commits in them with:
```
git fetch upstream
git rebase upstream/master
```
and it'll update to latest, moving your commits to the end. Just don't do that if you've already pushed the branch.

**Comment by KasparoVy** [comment]
I'm going to save this page for reference, super useful. Thanks again!

**Comment by Fox-McCloud** [comment]
This is wayyyyy too many commits for such a small PR =/

**Comment by KasparoVy** [comment]
At least the sprites were nice. BRB.

**Pull request closed without merging**
