### PR TITLE
Adds the RPD (rapid pipe dispenser)

### PR DESCRIPTION
**Pull request by Citinited**
It's finally here!

This PR adds my own implementation of /tg/'s RPD, but made to work with all pipes on paracode. It should also be relatively straightforward to add pipes that are added to the codebase in future.

This RPD can manipulate pipes in a variety of ways, can dispense any type of pipe, and also deletes pipes. It also has its own NanoUI!

http://i.imgur.com/t6OUGwi.gif
http://i.imgur.com/5lmYxgA.gif
http://i.imgur.com/UNjlue8.gif
http://i.imgur.com/nsnOeK7.gif

I've added an RPD to each atmos closet, and I've also updated the autolathe file so that it contains the RPD.

:cl:
rscadd: Adds the Rapid Pipe Dispenser (RPD). One RPD starts in each atmospherics locker, and more can be constructed at a hacked autolathe.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Because of how redundant this makes Atmos techs, you might as well merge Engineering and Atmos into one job.

**Comment by Citinited** [comment]
They'll be about as redundant after this merges than they are right now...

**Comment by SamHPurp** [comment]
I'm not saying that adding it is a bad thing. I'm saying there might be further legitimate things we should/could be doing as well.

**Comment by Citinited** [comment]
Indeed, though fixing atmospherics' role in-game is not something that this PR can fix (and should be something that needs to be looked at separately).

**Comment by taukausanake** [comment]
Really shouldn't add this to the map. People argue about making jobs redundant but give them the tools to do such right away. You shouldn't get anything that useful at round start. If you need something that's a step above something you can already do then you should do something before getting it. R&D, as much as everyone hates it, is the only logical way to get these sort of advanced tools.
You add this into the map you might as well remove both pipe dispensers because they will never be used again. You make people wait until they can get this then the other tools get used first

**Comment by Citinited** [comment]
Oops Travis failed, going to need to fix that

**Comment by Fruerlund** [comment]
Pipes are supposed to be heavy and bulky in my opinion. Making it possible to lay them down using a small handheld device is not something I would like to see. 

I can however see this merged, if we make it a research device with high levels requirements otherwise no.

**Comment by Citinited** [comment]
On the topic of research and stuff, the RCD is already a roundstart item that can be constructed at an autolathe, and this basically does the same sort of thing so I don't see it as much of a problem.

@Fruerlund It can easily be made a bulky item by changing the weight class of the item. I need feedback from admins and maintainers primarily before doing that

**Comment by Necaladun** [comment]
This takes a lot of the annoyance and grunt work out of atmos which I like.

My worry is it makes the pipe dispensers absolutely useless.

**Comment by Fruerlund** [comment]
I could see this merged if you adjust the weight of the tool👍

**Comment by Citinited** [comment]
Closing this until I figure out github for windows

**Pull request closed without merging**
