### PR TITLE
Culinary QoL update

### PR DESCRIPTION
**Pull request by Darkmight9**
## What Does This PR Do
Adds in the new culinary tool apron: a belt slot apron able to hold almost every thing a chef could need. The chef starts with one and can get more from the vendor in the kitchen.
Adds a new paper that gives advice to learning chefs
The recipe book now links to the food guide wiki page
And lastly the sushi mat has been resprited

Later on down the line I plan to revamp the food cart (it's code is a mess, look at it and tremble! https://github.com/ParadiseSS13/Paradise/blob/9cb0adcda583c274978517556dd32da77a63c4cb/code/game/objects/structures/foodcart.dm )

And further down the line, once station mapping is unfrozen, I plan to remap the kitchen to be better and possibly allow 2 chefs to spawn and man the kitchen.

## Why It's Good For The Game
The chef has been in dire need of some love and attention and this PR aims to improve the lives of those who man the kitchen via improved inventory management with the culinary tool apron. Better learning of how to cook via a new note that chefs start with and learn new recipes via the recipe book now linking to the wiki. Also if a chef wants to charge people for credits they now start with an eftpos scanner. And lastly the sushi mat has been resprited

## Images of changes
The new culinary tool apron Edit!: Redid the sprites
image

the new sprites
image

## Changelog
:cl:
add: Added the new culinary tool apron, a belt slot apron that's able to hold almost everything a chef may need!
add: Added a new paper that gives some basic advice for beginner chefs, starts in the chef's backpack.
tweak: chef starts with the new apron along with the cooking advice paper, recipe book, and an eftpos scanner(for folks who want to charge people) 
tweak: the recipe book now links to the food guide wiki
imageadd: Added the new culinary tool apron and resprited the sushi mat to be better.
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
I love the idea of the apron belt slot item, but the sprite looks kind of off to me.

Its kind of a dirty grey color instead of clean white and it kind of looks like it has pockets running up the entire apron rather than 2-3 near the bottom and due to this it almost looks like one of those novelty muscle aprons with the abs on it

**Comment by variableundefined** [comment]
I agree the coloring and design of the apron look a bit off.

**Comment by Necaladun** [comment]
I just keep seeing a face with 4 eyebrows :/

Otherwise this is great and :+1:

**Comment by Darkmight9** [comment]
Well if requested I can do the apron's sprite again. But it does indeed have quite a few pockets on it

**Comment by Aquilar** [comment]
the apron looks like master mundi....

**Comment by Darkmight9** [comment]
And the apron sprites have been redone! Now better colored and styled!

**Review by variableundefined — APPROVED** [review]

**Comment by SteelSlayer** [comment]
I'll be honest, the face on the apron stands out *so much* that it makes it appear as a joke item to me, I can't take it seriously. It looks like a sentient cloud or something. Sorry to be negative.

**Comment by Kiyahitayika** [comment]
Sleepy apron <3

**Review by Necaladun — APPROVED** [review]
New sprites fine to me, all good to go

**Pull request merged**
