### PR TITLE
Mining station remap

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR replaces the mining station on lavaland with a new design that removes redundant areas, and makes the whole thing feel more hospitable.
Since SDMM sanitizes variables, the diff will be quite large as lavaland has a lot of redundant variables that got tidied. This does not affect anything in-game.

## Why It's Good For The Game
The old mining station has been in the game for ages, and while they say "if it ain't broke, don't fix it" that doesn't always hold true.
Here are some of the issues it has:

- "Living" area that is weirdly out of the way, meaning it's free real estate for antags with barely any counterplay.
- Bad camera names that make it next to impossible to see what's going on down there.
- Scrubbers network that doesn't actually work.
- All the coloured tiles are actually manually placed squares of colour. (Holy hell this was decal spam)
- The smelter room was totally useless and served only as a noob trap.
- The medbay was never ever going to get used because of how far out of the way and how ill-equipped it was.

These have all been fixed with this new station, the living area is central and cosy. This encourages miners to use it and gives them a place to RP between mining runs. Since it's the main passageway, antags have to get slightly more stealthy, using bathroom or bedrooms for their dirty business.
Consistent camera names for easy location.
A working atmos system.
Decal spam begone, could improve performance slightly.
Noob trap smelter straight up erased.
Medbay has a basic sleeper and a wall-mounted defib, for emergency situations. This potentially stops miners just being shoved into a cloner on-station.

### In-engine Render

image

## Changelog
:cl:
tweak: Remapped the lavaland mining outpost
/:cl:

### CODE REVIEW

**Review by Kyep — APPROVED** [review]

**Review by SabreML — COMMENTED** [review]
<details>
<summary>Should note that this makes any regular escape attempt from the Labour Camp pretty much impossible:</summary>

**Before:**
image
**After:**
image
</details>

<details>
<summary>A few odd pixel offsets:</summary>

image
image
image
</details>
<details>
<summary>These offsets on the map don't seem to transfer over into the game:</summary>

**StrongDMM:**
image
**Ingame:**
image
</details>
<details>
<summary>This whole room is pretty badly lit, even without night lighting: (Everything but the top corners starve Dionae)</summary>

image
</details>
<details>
<summary>Very much a nitpick, but could this ore crate be moved to the side of the room like the one on the left?</summary>

image
</details>
<details>
<summary>Not 100% sold on the layout of the comms area, with the door opening into the side. Maybe you could try flipping it?</summary>

**Current:**
current
**Badly edited idea:**
image

**Comment by S34NW** [comment]
> 
> Should note that this makes any regular escape attempt from the Labour Camp pretty much impossible:

Ah, yeah so now if you want to escape you basically have to go further up north where there is a two-tile gap to cross, then dig your way back.
Personally, I think this is fine, as breaking out of the labour camp should be harder than crossing a bit of lava and bashing a window in.

> A few odd pixel offsets:
> These offsets on the map don't seem to transfer over into the game:

Thanks, ill look into these.


> This whole room is pretty badly lit, even without night lighting: (Everything but the top corners starve Dionae)
> Very much a nitpick, but could this ore crate be moved to the side of the room like the one on the left?

Tube lighting time! Also, sure I can move that crate.

> Not 100% sold on the layout of the comms area, with the door opening into the side. Maybe you could try flipping it?

Definitely.

**Comment by S34NW** [comment]
reopening for CI

**Comment by variableundefined** [comment]
No forthcoming maintainer approval. PR has been stuck for a long time. Closing.

**Pull request closed without merging**
