### PR TITLE
Implements A Couple Goon Reagents

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Credit to Goon.

Just implements a few Goon reagents; nothing particularly exciting:

- Chromium. Inert and used to make other chems--found in dispenser
- Acetaldehyde. Chemical that acts as a very basic poison, can be used to make acetic acid
- Acetic Acid. Very very weak acid; easily blocked by masks or helmets; can't melt gear or objects.

New recipes:
- acetaldehyde: Chromium+ Oxygen + Copper +Ethanol + Heat
- Acetic Acid: Acetaldehyde + Oxygen +Nitrogen

Adds a bit more diversity to reagents and can act as a building block for others.

:cl: Fox McCloud
add: Implements a few new reagents: chromium, acetaldehyde, and acetic acid. Find chromium in a dispenser; acetaldehyde is a basic poison, and acetic acid is a super weak acid
add: Make acetaldehyde with chromium + oxygen + copper + ethanol + heat
add: Make acetic acid with acetaldehyde + oxygen + nitrogen
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
I don't really see those being used much, so not much of a point in adding them right now. If they're going to be used as building blocks later, then whatever PR adds those recipes can also include those, imo.

**Comment by MRgaty** [comment]
I canf think of an use for them right now.

**Comment by Ty-Omaha** [comment]
Put the acetic acid on fries

**Comment by Spacemanspark** [comment]
They won't fry you very well tho

**Comment by taukausanake** [comment]
I kind of want Chromium to act like paint but it makes everything a shiny chrome
image

**Pull request merged**
