### PR TITLE
Revert "Good heavens, judging by the clock, we should be seeing a [Medbay Remap] dock."

### PR DESCRIPTION
**Pull request by Crazylemon64**
Reverts ParadiseSS13/Paradise#7758

oops I didn't internally discuss this, right that's a thing we do

I'll keep the actual PR on the main server using the "test-merge" system, so you can still experience it in its full glory, though

### CODE REVIEW

**Comment by SamHPurp** [comment]
Sorry Free, I just don't agree with compacting the whole thing, including removing genetics maintenance.

**Comment by FalseIncarnate** [comment]
Clearly this is to allow the arcade to be merged in permanently first.

**Comment by FreeStylaLT** [comment]
@SamHPurp That's fine, we just have differing overall design directions for Medbay

**Comment by SamHPurp** [comment]
@FreeStylaLT 👍

**Pull request merged**
