### PR TITLE
Ultimate Revival Update

### PR DESCRIPTION
**Pull request by variableundefined**
**What does this PR do:**
Replaces medbay with a hole

Tested locally.

Supported by a maintainer.
**Images of sprite/map changes (IF APPLICABLE):**
Screenshot of hole:
image

**Changelog:**
🆑:
del: Medbay
add: A mysterious big hole in the station.
tweak: Reviving people is harder now.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
@variableundefined your CL is broke

**Comment by AffectedArc07** [comment]
Also you forgot this
image

**Comment by datlo** [comment]
This PR is garbage. You didn't delete : 

1. All medical jobs
2. The entire surgery module folder
3. All positive chems
4. Brigbay + brig phys

Please update this or I cannot support. 👎

**Comment by variableundefined** [comment]
I left genetics alone because they're just science pretending to be medical anyway

**Comment by TDSSS** [comment]
TIL we have a misdesign tag

**Comment by Superhats** [comment]
I don't agree with this. People spawn alive, this gives them an incentive to play the game. We can't have people playing. Make the entire station space, this'll make playing the game harder. Should encourage people to RP, since they can't play

**Comment by variableundefined** [comment]
@Superhats You make a good point, can you make a PR for that alternative solution?

**Comment by Superhats** [comment]
I would but I'm busy making a PR that deletes the game files

**Comment by variableundefined** [comment]
That's a shame. Have you consulted the heads about said PR?

**Comment by MischievousGremlin** [comment]
With this, maybe death will feel more impactful

**Comment by Bookdrizzt** [comment]
This is the perfect way to make death really have meaning. You get injured, you go to medbay, you float in the endless dark abyss until you die from the natural forces. Plus, no reliance on chemists/CMO for anything! You just die. Unless you’re a vox, then you just kinda float along.

**Comment by BiQndy** [comment]
We need this

**Comment by Citinited** [comment]
merge immediately

**Comment by Quantum-M** [comment]
Clearly medical budget cuts.

**Comment by Mitchs98** [comment]
No one can complain about not being able to be revived if there's no where to be revived. The ultimate solution and fair to all species. :thumbsup:

**Comment by Spacemanspark** [comment]
Looks good to me tbh

**Comment by AffectedArc07** [comment]
So when are we getting a testmerge?

**Comment by EvadableMoxie** [comment]
Do medical doctors spawn inside the hole at round start?  If so, how are we going to make sure we also kill the Diona, Plasmamen and Vox?  What if we filled the hole with lava?

**Comment by variableundefined** [comment]
@EvadableMoxie That's part of the species privileges

**Comment by Jazz23** [comment]
Political statement

**Comment by Ralta** [comment]
Insult about creator's coding ability, claim of a far better solution without offering to implement it, :thumbsdown:

**Comment by Landerlow** [comment]
Should delete the station, makes people play cause they have to build one from scratch!

**Comment by Agameofscones** [comment]
Labcoats imply medical professionalism. They should also be removed or reworked. Smh

**Comment by Fox-McCloud** [comment]
This had a good run.

**Comment by KasparoVy** [comment]
[But how far?](https://www.youtube.com/watch?v=otXGqU4LBEI)

**Pull request closed without merging**
