### PR TITLE
Adds Fiber Wire

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Adds a garrote to the traitor uplink for 12TC, functions is as follows:

The fiber wire is a razor-thin length of wire designed for discrete strangulation of isolated targets. To use it on your target you must take one handle in each hand (Wield the object) and approach your target from behind. Once behind your target using the fiber wire on them will replace the offhand of the wielded garrote with an aggressive grab on the target, and they will begin to accumulate oxygen damage as well as slight brute damage to the head (As garrotes tend to cause pretty severe neck trauma on those it is employed against). This damage will continue until the grab is removed (Either by being resisted out of or by being dropped by the attacker) or the wire is un-wielded. Throughout the course of this the person under attack will be unable to speak, but the attacker will also be very slow to move and have both hands occupied for the duration of the attack.

Also adds a non-traitor improvised garrote, which causes stuttering instead of silencing, starts the grab off as passive rather than neck, does half the damage, and is blocked by helmets/masks that cover the mouth. It is made by tablecrafting wood and cable together with a knife as the tool (To carve the handles with).

*EDIT*
Icons the wonderful work of @Nienhaus

### CODE REVIEW

**Comment by ScratKnapp** [comment]
Ooohh yes.

:+1:

**Comment by FalseIncarnate** [comment]
If it works as described, sounds like a pretty nice way of taking out targets that breathe. However, since it deals OxyLoss directly, I suspect this might cause some weird behavior on the non-breathing species like Slimes and such.

**Comment by fludd12** [comment]
Pull a Nethack Amulet of Strangulation, and make it work on non-breathing species that keep their brain in their head, since it cuts off the blood supply.

**Comment by FreeStylaLT** [comment]
There's already a "Hitman" bundle with a suit, shoes, silenced stetchkin, bodybag, trash bag and soap.

For 20 fucking TC. Those must be some expensive suit and shoes.

**Comment by Vivalas** [comment]
IIRC bundles are supposed to be a gamble as sometimes what you recieve can be worth more than 20 TC, Hitman sounds like a gimmick bundle.

**Comment by FlattestGuitar** [comment]
There's something called a 'surplus crate' and there are a bunch of different ones that can come. They're worth way more than 20TC you have to pay, but you don't get to pick which one you get.

I believe a 'hitman' bundle is one of the options.

**Comment by monster860** [comment]
Soooo you use this on someone next to a table? Fun.

**Comment by Nienhaus** [comment]
I made icons for this, what?

**Comment by DaveTheHeadcrab** [comment]
Not specifically for this, but you made the garrote icons.
IIRC.
My icon stash records are not the greatest, I won't lie.

**Comment by Nienhaus** [comment]
Oh, okay yeah.

**Comment by Necaladun** [comment]
Fantastically cool idea.
The victim is unable to speak - but are they able to still attack?
How long will it take to incapacitate a target?
Can you also use it to slice cheese?

**Comment by DaveTheHeadcrab** [comment]
@Necaladun 
No, resisting may work but it's a crapshoot.
Currently up in the air, shooting for ~60 seconds.
Unknown.

**Comment by FalseIncarnate** [comment]
It cannot slice cheese as it is not considered SHARP. You'd need to either give it this flag or snowflake an exception, both options having some notable drawbacks.

**Comment by DaveTheHeadcrab** [comment]
Tested and good to be merged, no longer applies oxy damage to species who shouldn't take it.

**Comment by CupcakesNHacksaws** [comment]
Can we have a wiki page for tablecrafting then? AFAIK it's non-existant

**Pull request merged**
