### PR TITLE
Adds waterfalls to the pool

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit adds a new machinery type, (poolwaterfall), which describes
itself, really. It is a waterfall-type-thing for the pool, integrated
fully into the pool controller and it's nanoUI.

Players: You can now turn on the pool waterfalls and almost feel like upper-middle-class NT workers.

Admins: Nothing special here. 

Coder notes; May need to update sprite in future, it looks.. eh.. alright.. in-game, could be better

wfon
wfoff
wfUI
actualspriteanims

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Going to have to :-1:  on this one.

**Comment by tigercat2000** [comment]
Well, alright, do you mind if I ask why?

**Comment by adrkiller59** [comment]
@Fawks

#lolcountered

:+1:

**Comment by Nienhaus** [comment]
I don't see the point of it.

**Comment by Fox-McCloud** [comment]
The sprites are pretty bad no offense (they look like blue lights), it doesn't really serve any particular purpose, and is largely for something players never use to begin with (the pool).

**Comment by Iamgoofball** [comment]
:+1: is pretty cool

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Midaychi** [comment]
It's pretty neat and theres really not much you can do about the sprite due to the pools orientation on the map.  Also I didn't know adding useless fluff to the map was illegal??

**Comment by CrAzYPiLoT-SS13** [comment]
Well, according to my digital camera being lynched (I am talking about my
first PR when it was just a sprite), adding fluff items is a bad idea if
it's the sole purpose of a PR. The sprites really can be improved a lot,
and as someone said, people rarely use the pool, I doubt they will even
notice this if we don't introduce a IG changelog, not one that leads to git.

**Comment by adrkiller59** [comment]
Alt Text

I will upvote any PR that adds new "useless" content rather than PRs that remove "useless" content.

Also it could use a better sprite, with directions and stuff, where is our spriter team?
Do we even have a spriter team?  

I swear we had one.

**Comment by CrAzYPiLoT-SS13** [comment]
If you count me in, the spriter count is 1. And my work isn't exactly the best. I don't even know how to sprite this one. BTW, maybe add a splashing sound effect?

**Comment by tigercat2000** [comment]
> BTW, maybe add a splashing sound effect?

That seems like a quick way to annoy everyone.

**Comment by CrAzYPiLoT-SS13** [comment]
How is that annoying? Add it that you hear it when you are in the pool. Problem solved.

**Comment by ZomgPonies** [comment]
You can make the sound effect really quiet. I agree that to complete this feature, it requires sound.

**Comment by veganzombeh** [comment]
:-1: in the current state. The sprites don't look quite right; they're much darker blue than the pool and it just looks a bit off if they don't match. Sound, and potentially having the waterfalls spawn mist, would be awesome though.

**Comment by ZomgPonies** [comment]
Yeah I don't mind a useless feature if you can at least easily tell what it is. Right now, without either sound or quality sprites it could be anything.

**Comment by CrAzYPiLoT-SS13** [comment]
I'll try doing the sprites, but I really don't know how to put them in a 2D game. WHY DID YOU HAVE TO DO THIS TO ME

**Comment by CrAzYPiLoT-SS13** [comment]
How about this one:
waterfall

**Comment by tigercat2000** [comment]
I suppose this can be considered DNM, I don't have the time to work on this any further for now.

**Comment by Nomzosha** [comment]
Don't see why not, just update the sprites and its good.
Maybe a sound as well.

**Comment by Fox-McCloud** [comment]
Discussed this over with Tiger; may be re-opened at a later date or re-created.

**Pull request closed without merging**
