### PR TITLE
Assault Surplus Crate and Knife Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over: https://github.com/tgstation/-tg-station/pull/13926

- Adds in an assault gear crate
 - Contains 2 spaceworthy swat suits that are heavily armored, 2 swat helmets, 2 swat sec hailers, 2 combat knives, and two military assault belts.
 - Military assault belts are like syndi military belts only they hold less
- Reduces the cost of the spacesuit crate from 80 to 30 and doubles the amount of spaces suits it has (from 1 to 2)
- Increases bandolier slots from 6 to 8
 - this notably means the bartender has +2 shells for his shotty

Knife Refactor

I got really sick of there being so many different types of knives--there was utensil/knife and kitchenknife....knives....this causes a lot of confusion and redundancy in the code as some knives would work on some things, but not others (we get ahelps about this all the time, too)...despite looking identical and having nearly identical names...so it's refactored so that all knives are just `/obj/item/weapon/kitchen/knife` and all subtypes (from plastic knives to butcher cleavers to meat cleavers) are children of that. 

This allows for 100% complete universal behavior on knives where they have it.

Why didn't I make them a child of utensils? 

You don't generally scoop food onto a knife to eat it...anddd generally if you're stabbing someone in the head with a knife you're not wanting to eyestab them, you're wanting to slice and dice.

The Full getup of assault gear:
img

:cl: Fox McCloud
rscadd: Adds in Assault Gear crate to cargo
rscadd: Adds in military assault belt
rcsadd: Adds in spaceworthy swat suits
tweak: tweaks bandolier to hold 2 additional shotgun shells
tweak: bartender starts off with +2 additional shells
tweak: Reduces the cost of the space suit crate and doubles its contents
rscadd: Refactors knives so their behavior is more universal
/:cl:

### CODE REVIEW

**Comment by Plotron** [comment]
My goodness, more power to cargo security.

I like the spacesuit cost change and the bandolier buff.

**Comment by Fox-McCloud** [comment]
>My goodness, more power to cargo security.

Gotta combat those nuke-op scum who declare war on you.

**Comment by NTSAM** [comment]
I think your title is misspelled a little.

**Comment by taukausanake** [comment]
I would TOTALLY stab someone in the eye with a kitchen knife. I'm just not robust enough to do it. Just saying

**Comment by Fox-McCloud** [comment]
Removes the "tack" knife. This was redundant with the combat knife and lacked a sprite---not to mention wasn't used anywhere.

**Comment by Regen1** [comment]
Can we also add the "Combat knife in boot" from CM? :V 
@apophis775

**Comment by Spacemanspark** [comment]
That would be hilarious to have, @Regen1.

**Comment by apophis775** [comment]
You want Ma combat Knives?

**Comment by Spacemanspark** [comment]
Yes.
Yes we do.
I once considered porting over those MG turrets, too, and making them an adminbus item only, obviously.
Even got it working on paracode and stuff.

**Pull request merged**
