### PR TITLE
Clown Piano

### PR DESCRIPTION
**Pull request by Deanthelis**
I made a horrible mistake with git in the last attempt at this because I really have no idea what I'm doing with git at all, but I fixed that, so let's try this again.

This PR adds the Clown Piano to the game, a version of the Space Piano in the bar that uses bikehorn sounds instead of piano notes to create songs. It functions identically to how the regular piano does, and has a 25% chance of being there, instead of the 50/50 split the Space Piano and Space Minimoog had. I may make another PR to create an 'advanced bikehorn' that's just a redo of the Space Violin, but with honking, but that's outside the scope of this one.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This should be a subtype, not a random probability. The honking is annoying as hell, ans the piano already irritates a lot of people; this will be several orders worse.

This should probably be something that has to be built with bananium.

**Comment by DaveTheHeadcrab** [comment]
@Fox-McCloud 

Agreed completely.

**Comment by Spacemanspark** [comment]
You monster.

**Comment by Fox-McCloud** [comment]
Also, how big are all those files, together?

**Comment by Dumbdumn5** [comment]
I love this idea, especially since you can just toggle the sound off for yourself in preferences.

**Comment by taukausanake** [comment]
Maybe make it a 10% prob just in case people really hate it? I personally have no problem with this idea at all

**Comment by tigercat2000** [comment]
I think it's fine with randomization, however, you should probably put the prob(50) in the `/something/dunno/piano/initialize()` proc so that only the round-start pianos will be affected

**Comment by Tastyfish** [comment]
@tigercat2000 The only pianos that exist are the ones at round start; you can't build them. I would be more in support of this if you could deconstruct and rebuild it. (Pulled it and it is pretty funny sounding though, would kill myself if I was bartender in a round with this running on repeat though)

**Comment by Tastyfish** [comment]
Although for the record it (generously) sounds like [this](https://clyp.it/vogjoj05).

**Comment by Fox-McCloud** [comment]
>Although for the record it (generously) sounds like this.

Yeahhhhhhhh, that needs to be locked behind bananium, for sure; that's not something that should be available, at round start.

**Comment by Plotron** [comment]
Bananium-powered piano FTW.

**Comment by taukausanake** [comment]
It sounds... beautiful... *cries of joy*

**Comment by Fox-McCloud** [comment]
@Deanthelis 

What's the size of all the music files combined. Also, you plan on adding this as a bananium recipe?

**Comment by CrAzYPiLoT-SS13** [comment]
IMO, that doesn't sound so bad. Maybe keep the chance to be there at
roundstart, but make it deconstructable?

**Comment by tigercat2000** [comment]
@Fox-McCloud The clownpiano music files are 3.2mb, compared to 1.1mb for the piano and 639kb for the violin

**Comment by Fox-McCloud** [comment]
3.2 MB? That's huge for something so minor; were these properly compressed, @Deanthelis ?

**Comment by Deanthelis** [comment]
These were compressed appropriately, yes. The violin flatly has fewer notes (and each note requires its own file. thanks BYOND.), and the piano sound files are exceedingly simpler and contain less information than the bikehorn versions.

I don't plan on making it a bananium recipe, mostly because I don't know how to do that, and I kinda doubt people would genuinely want this long-term. I might go back in and make it admin-spawnable rather than random chance, but with 3.2mb being a problem, I might not bother at all.

**Pull request closed without merging**
