### PR TITLE
Add in 79 polaris hairstyles

### PR DESCRIPTION
**Pull request by Anasari**
Port in 79 hairstyles from Polaris. Number approximated. Because of its tedious nature I haven't took screenshot of each hair individually with caption of which name is which. 

Click the image to zoom in. 

Image (With name & lazily drawn division line. Click to zoom in): 

If there's any hairstyle you particularly dislike, please cross them out in an image so I can figure out which is which.

The two hairstyle on the bottom of a large size with grey-ish shading is called "Shy" (Fluttershy) and "Long bedhead"

🆑 
add: 79 hairstyles ported from Polaris.
/🆑

### CODE REVIEW

**Comment by Anasari** [comment]
still WIP. Need to figure out some..inconsistency

**Comment by taukausanake** [comment]
Damn these look nice! Can't wait for this to be merged, I already see my new hairstyle in here

**Comment by Ralta** [comment]
Only has 79 hairstyles now. Pointless addition. Do not merge. Waste of time. End it.
👎

**Comment by taukausanake** [comment]
Hey, if it still has the same icons as in OC I care not. Should have just counted them from the beginning

**Comment by Ralta** [comment]
I think Ansari should make a PR for each individual hairstyle so that we can judge them all on their individual merits.

**Comment by Anasari** [comment]
The number of hairstyles changing from 77 to 80 to 79 was because it is objectively hard to count 82+ sprites and cross-reference them with 80+ entry in newly added hairstyyle and then cross-check them to make sure they are not redundant oh my god why.

At least it's easier than spriting 80 hairstyles.

**Comment by taukausanake** [comment]
@Anasari Except that one you totally forgot but don't want to admit because you'll have to count almost 80 sets of sprites again

**Comment by Belsima** [comment]
Are there any hairstyles Paradise has that Polaris didn't? I might go ahead and try to port them if there are.

**Comment by DarkPyrolord** [comment]
As a barber regular I approve of this PR

**Comment by Anasari** [comment]
Paradise seems to have more vox hairstyles.

**Comment by KasparoVy** [comment]
All we got on Polaris are Vox hairstyles and only one of them is actually ours :wink:.

**Comment by Ralta** [comment]
@KasparoVy VOX HAIRSTYLES? GIMME GIMME GIMME

**Comment by Varghh** [comment]
Why not 80? My ocd is fucking killing me in 79, do not merge, meme PR

**Comment by KasparoVy** [comment]
@Ralta [In here](https://github.com/ParadiseSS13/Paradise/blob/master/icons/mob/human_face.dmi) right after Skrell hairstyles, all icon states are prefixed with _vox__

**Comment by Anasari** [comment]
To address some concern regarding the effect of the whiteness in the country, shy and long bedhead hairstyles, here are some screenie of its effect. Basically make it whiter:

**Comment by taukausanake** [comment]
> regarding the effect of the whiteness in the country

No idea if racist joke or something about making hair colors brighter. Either way, I am so disappointed it went over my head like this

**Comment by Anasari** [comment]
It's the hairstyle called country.

That was unintended.

**Comment by taukausanake** [comment]
Why is that one hairstyle called "shy"? At first look it looks like Jessica Rabbit's hair and I can totally see someone rocking that appearance. I'd almost have its name changed to "Jessica" and save "shy" for something else

**Comment by MarcellusPye** [comment]
@taukausanake 

> The two hairstyle on the bottom of a large size with grey-ish shading is called "Shy" (Fluttershy) and "Long bedhead"

Literally in the OP

**Comment by taukausanake** [comment]
@MarcellusPye _SINCE WHEN?_ But I see it now, that is Fluttershy. Would have liked a Jessica Rabbit hair still

**Comment by MarcellusPye** [comment]
It's ok, you can call it Jessica hair

**Comment by KingPhilipIII** [comment]
Second hairstyle. Top left corner. 

Sergeant. Not sargeant. 

>triggered

**Comment by tigercat2000** [comment]
👍

**Pull request merged**
