### PR TITLE
Grey Helmet Sprites

### PR DESCRIPTION
**Pull request by The-Driker**
Modified some of the helmet sprites to fit Greys. No more seeing the front of a Grey's face sticking through the helmet while wearing one of these. 
grey helmets
_The lights on helmet sprites don't actually look like that. It just pasted like that into gimp when making this screenshot._ 

**These are just sprites and I haven't touched any code files. If I messed anything up with placement of the sprites, let me know and I'll try to fix it.** 

`**Full List of modified helmet sprites by file name.**`

1. Spacenew
2. syndicate-helm-black-orange
3. syndicate-helm-blue
4. ert_commander_rig_sealed
5. ert_security_rig_sealed
6. ert_medical_rig_sealed
7. ert_engineer_rig_sealed
8. ert_commander_rig
9. ert_security_rig
10. ert_medical_rig
11. ert_engineer_rig
12. syndicate-helm-black-red
13. hardsuit0-engineering
14. hardsuit0-mining
15. hardsuit0-sec
16. hardsuit0-white
17. hardsuit1-atmos
18. hardsuit1-engineering
19. hardsuit0-atmos
20. syndicate
21. syndicate-helm-black
22. syndicate-helm-black-blue
23. syndicate-helm-black-engie
24. syndicate-helm-black-engie1
25. syndicate-helm-black-green
26. syndicate-helm-black-med
27. hardhat0_atmos
28. hardhat1_atmos
29. hardsuit0-ert_janitor
30. hardsuit0-medical
31. hardsuit1-ert_commander
32. hardsuit1-ert_engineer
33. hardsuit1-ert_janitor
34. hardsuit1-ert_medical
35. hardsuit1-ert_security
36. hardsuit1-medical
37. hardsuit1-mining
38. hardsuit1-sec
39. hardsuit1-white

### CODE REVIEW

**Comment by Necaladun** [comment]
<3 <3 <3

**Comment by The-Driker** [comment]
I just realized that I neglected to modify all of the light activated versions of the helmets. I will rectify this and update the commit file asap.

**Comment by ProperPants** [comment]
@The-Driker 
Do normal medical hardsuits already look okay on Greys?

**Comment by The-Driker** [comment]
Added helmet sprites I felt were missing and worn enough to warrant adding. This should be good to go now. 
@ProperPants It's now added. Thank you for pointing out an often used helmet I missed.

**Pull request merged**
