### PR TITLE
Thiccer Police Baton

### PR DESCRIPTION
**Pull request by 13spacemen**
## What Does This PR Do
New police baton sprite from TG

## Why It's Good For The Game
Looks better than the current baton which is just a twig the Detective broke off a tree

## Images of changes
Old

New

## Changelog
:cl:
imageadd: Better police baton sprite
/:cl:

### CODE REVIEW

**Comment by 13spacemen** [comment]
> if you are gonna make a PR that tweaks sprites, please post said sprites in the `images of changes` section

Doesn't the IconDiffBot already do that?

**Comment by Sirryan2002** [comment]
> > if you are gonna make a PR that tweaks sprites, please post said sprites in the `images of changes` section
> 
> Doesn't the IconDiffBot already do that?

yes but non-contributors generally do not know how to check that.

**Comment by atteria** [comment]
IcondDiffBot is hidden behind multiple tabs and posts tiny, bilinearly scaled images. It's common courtesy to make your PR convenient.

also cursed PR title

also hooray for a clickable wood baton with some actual depth

**Comment by procdrone** [comment]
im one of the non coder commenters, and i have no idea how to access diffbot, images of changes plox

**Comment by AffectedArc07** [comment]
> im one of the non coder commenters, and i have no idea how to access diffbot, images of changes plox

For future ref, press this
image

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
