### PR TITLE
Bandolier shotgun shell stacking

### PR DESCRIPTION
**Pull request by E-MonaRhg**
## What Does This PR Do

Makes it so shotgun shells stack in bandoliers.

## Why It's Good For The Game

Quality of life change and makes bandoliers _somewhat_ worth using.

## Images of changes

image

## Changelog
:cl:
tweak: Shotgun shells stack in bandoliers.
/:cl:

### CODE REVIEW

**Review by dearmochi — APPROVED** [review]

**Comment by Mitchs98** [comment]
You beautiful man.

**Review by S34NW — APPROVED** [review]

**Comment by Dumbdumn5** [comment]
How did this not have head approval yet? :+1:

**Comment by Feasel** [comment]
Why no merge. Scream

**Comment by AffectedArc07** [comment]
> Why no merge. Scream

Merge nagging will get you gitbanned, or worse.

Do it again, and you wont be speaking here.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
