### PR TITLE
Adds testing of away missions to Travis.

### PR DESCRIPTION
**Pull request by Tastyfish**
- Makes Travis test the away missions as well, in case a refactor changed a path and forgot about the other maps.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
And then Travis took 10 years to finish.

**Comment by Tastyfish** [comment]
Thankfully, it does them concurrently and parsing the actual maps takes less than a second per map.

**Comment by Tastyfish** [comment]
I also realized that Travis includes python in the base VM, so I'm shaving a second or so by removing those apt gets.

**Comment by Tastyfish** [comment]
Now I also split the various file checks like the changelog and step_x sanity checks into a separate job because around 10 seconds is spent normally running pip.

**Pull request merged**
