### PR TITLE
Fixes wall lockers.

### PR DESCRIPTION
**Pull request by Spacemanspark**
-Fixes https://github.com/ParadiseSS13/Paradise/issues/2808
--Explanation: The lockers in medbay, emergency walllockers, are children of normal walllockers (Which aren't mapped anywhere). Normal walllockers function exactly like normal lockers (click to open/ close them), except they're on a wall, whereas emergency walllockers have some overrides, so clicking them dispenses stuff.
When the emergency walllocker was opened, it didn't have a icon_opened set, so it defaulted to the parent's icons, which was wallockers. Same for icon_closed.
As for the walllocker-is-now-a-wall issue, that was an issue with normal wallockers calling their parent, normal lockers, which, when closed, set density to 1. Walllockers don't do that anymore.
--Tested, and it works.
--Sprites for opened emergency wall locker:
yayfixes
--Not the best, but they get the point across.
-uncomments clerical borgs. :^)

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
May also want to fix the sprite for when it closes too.

**Comment by tigercat2000** [comment]
it should be fixed @Fox-McCloud

**Comment by Fox-McCloud** [comment]
Great, thanks.

**Comment by Spacemanspark** [comment]
Ya, @Fox-McCloud, that fix is included.

**Pull request merged**
