### PR TITLE
Garlic juice no longer rng stuns vampires

### PR DESCRIPTION
**Pull request by hal9000PR**
## What Does This PR Do
title.

## Why It's Good For The Game
botany shouldn't be able to make seemling harmless plants filled with AOE vampire metacheck/stun gas. They already have holy water, thats enough.
and its also silly.

## Changelog
:cl:
del: garlic juice no longer effects vampires
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
I mean, it is the sterotype that garlic has a negative affect on vampires, granted we dont want it to stun them, since stuns are goin away buuuuuuuuut, i mean somthing would be neat.

Maybe some stamina damage so long as its in system? Low, but somthing, maybe make it so once their powered it cant affect them anymore.

**Comment by Inadvizable** [comment]
What a soul-rending PR...
Yeah this "mechanic" is really dumb, I'm glad I've never seen it abused.

**Comment by hal9000PR** [comment]
```
I mean, it is the sterotype that garlic has a negative affect on vampires, granted we dont want it to stun them, since stuns are goin away buuuuuuuuut, i mean somthing would be neat.

Maybe some stamina damage so long as its in system? Low, but somthing, maybe make it so once their powered it cant affect them anymore.
```
if it retains any visible effects then its a metacheck. either way, its a cliché vampire "weakness"

**Comment by Carthusia** [comment]
> IF anything, if a victim has garlic in their system, should just have a little message that say "You feel full but that blood tasted off, wonder why?" or something of a similar nature.

Oohhh thatd also be good, just a funny little reference to give someone a chuckle, nothing that can be abused,  just a good chuckle when they realise what it was that caused it

**Comment by LiberatedWaveMan** [comment]
> IF anything, if a victim has garlic in their system, should just have a little message that say "You feel full but that blood tasted off, wonder why?" or something of a similar nature.

a harmless reference like this would be a lot more fitting, for flavour's sake, as long as it doesn't have any actual impact on gameplay

**Review by farie82 — APPROVED** [review]

**Pull request merged**
