### PR TITLE
Floor tiles, Warning stripes, signs.

### PR DESCRIPTION
**Pull request by orelbon**
Finishes putting in some department floor tiles, kinda looked like someone got tired halfway and never finished. adds warning stripes to corresponding areas, added a few warning signs.

finishes putting blue edge tiles in the hallway under the break room, and gives the recovery room pink floor tiles, also adds a few no smoking signs 
medbay

puts in green floor tiles in virology, and fixes warning stripes
virology 3

rearranges radioactive signs, and puts in high voltage signs, fixes warning stripes.
engineering 

fixes warning stripes, adds missing exterior access button to airlock.
escape

 added warning stripes to toxins mixing chamber
toxins mixing

Xenobio warning stripes fixed
xenobio

### CODE REVIEW

**Comment by orelbon** [comment]
@Fox-McCloud Here you go, all clean.

**Comment by Fox-McCloud** [comment]
Much better, thank you.

**Comment by tigercat2000** [comment]
The virology tiles look pretty odd, really.

**Comment by orelbon** [comment]
its because there aren't sprites for the corner tiles, i looked all over the object menu for them.

**Comment by Fox-McCloud** [comment]
I almost guarantee there are---there's probably just not any instances of them on the map.

**Comment by orelbon** [comment]
ill try again, if you think there are, if i cant find any i'll just use a different pattern.

**Comment by orelbon** [comment]
i think there are green corner tiles but for a darker floor not white like in virology.

**Comment by orelbon** [comment]
@tigercat2000 what do you think of this layout?
virology 2

**Comment by tigercat2000** [comment]
@orelbon It looks better, however, there *are* green corner tiles- they are another dir on the icon.
Right click on one of the tiles, and change the number in 'dir'. It can be anything from 1-8, then hit okay. 3, 5, 6, 7 should be the corners.

**Comment by orelbon** [comment]
Ah ok.

**Comment by orelbon** [comment]
@tigercat2000 
virology 2

**Comment by tigercat2000** [comment]
I think the patient rooms might look nicer with a stripe all the way around inside them.

**Comment by orelbon** [comment]
@tigercat2000 i tried it makes it feel clausterphobic

**Comment by tigercat2000** [comment]
Alrighty, it looks better now anyhow.

**Comment by orelbon** [comment]
alright making it a commit

**Pull request merged**
