### PR TITLE
Adds Glass Tables to the Map

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds glass tables to the map at these locations:

- CMO's office
- Genetics
- Chemistry
- Virology
- R&D
- RD's office
- Brig Medical Treatment

General clean/high-tech areas that would have them.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I am more or less neutral to this, but I will point out that replacing too many tables with glass ones will damage xeno hiding spots, since you can see through them (obviously)

**Comment by fj45** [comment]
They should be even rarer then that, maybe RD, CMO and viro.

**Comment by Spacemanspark** [comment]
/tg/ also has them in robotics, if I remember correctly.
At least, one of their maps does.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Yeah, which is why I opted against putting them in areas where you do surgery.

**Pull request merged**
