### PR TITLE
removes Supply SoP from the HoP's office 

### LINKED ISSUE #22431: HoP still starts with Supply SoP
**Issue Description**:
HoP still has Supply SoP on their office, at least on Cyberiad.

**What did you expect to happen**: 
For him to not have it anymore.

**What happened instead**:
He still had it.

**Why is this bad/What are the consequences**:
Oversight bad.

**Steps to reproduce the problem**:
Look at HoP's desk on cyberiad, possibly on other maps too.

**When did the problem start happening**:
Since QM became a head.

### PR DESCRIPTION
**Pull request by bakaf**
## What Does This PR Do
Removes the book containing the Supply Standard of Procedure from the Head of Personnel's Office in the Cyberiad map 
Fixes #22431 
## Why It's Good For The Game
Quartermaster supremacy
## Testing
image
## Changelog
:cl:
fix: Removes the Supply SoP from the HoP's office in the Cyberiad 
/:cl:

### CODE REVIEW

**Comment by DGamerL** [comment]
Could you make prefix into just "fix"?

**Comment by bakaf** [comment]
> Could you make prefix into just "fix"?

done

**Review by DGamerL — APPROVED** [review]

**Review by Henri215 — APPROVED** [review]
LGTM, could specify on the changelog that the fix is related to Cyberiad

**Comment by bakaf** [comment]
> LGTM, could specify on the changelog that the fix is related to Cyberiad

done

**Comment by bakaf** [comment]
Any reason why this isn't approved?

**Comment by DGamerL** [comment]
> Any reason why this isn't approved?

Things can take a while sometimes, in this case, headcoders have to assign PRs with a label (Which is a PITA because of a few reasons), and then it'll get the labels for it being ready for merge and such!

**Review by S34NW — APPROVED** [review]

**Pull request merged**
