### PR TITLE
Tesla Gun Implementation and Small R&D Change

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Partial port of: https://github.com/tgstation/-tg-station/pull/16974 by @KorPhaeron 

Implements the Tesla Revolver, a replacement to the shock revolver.

This is a high-risk lethal weapon that deal damage and stuns---only it has a very high chance of recoiling back to the user and shocking them, as well.

Other
- Removes SMG and ammo from R&D

Overall goals: 
- Add diversity in R&D for the weapons they produce instead of having weapons that are nearly copy-pastes of existing weapons or that don't do anything interesting.
- Give cargo the niche of ballistic weapons and R&D the niche of experimental/odd weapons.

:cl: Fox McCloud
add: Adds in the Shock Revolver, a replacement for the stun revolver
remove: removes the stun revolver
remove: removes the prototype SMG+ammo from the protolathe
/:cl:

### CODE REVIEW

**Comment by ScratKnapp** [comment]
:-1: 

This is basically just another R and D nerf. The shock gun sounds nearly useless when any other energy gun can do the same task without damaging the user.

**Comment by tigercat2000** [comment]
i highly disagree with this
it leaves RD with no non-lethal ranged weapons

**Comment by KorPhaeron** [comment]
>basically any other energy gun can fire aoe stuns

Sure

**Comment by Fox-McCloud** [comment]
>The shock gun sounds nearly useless when any other energy gun can do the same task without damaging the user. 

Considering the Shock revolver can AoE stun+damage multiple people, that's not true, at all. That's it's niche; it's a very limited capacity AoE stun.

Officers literally never ask for stun revolvers because their advanced tasers are objectively superior--and R&D, themselves, don't care about them because they can't access them, themselves....not to mention they're single-handedly the reason lockboxes even exist to begin with (and a major component/reason why we *re-implmented* lockboxes.

**Comment by Kyep** [comment]
Re: Tesla Revolver
How much damage do they do on hit?
Sec usually uses non-lethal weapons. I don't see them using high damage AOE weapons, especially an AOE weapon that does lethal damage, often. For AOE stun, they already have flashbangs which barely get used despite being starting equipment. Why would they want to use one of these over a flashbang?
The best use of these I can think of is destroying groups of hostile xenobio or gateway mobs - but even there, those are immune to stun and these would have to do notably more than a single-target weapon in total to be worthwhile.
Tesla guns may be cool, but are these intended to be something that actually sees regular use?

Re: Removal of SMG
I almost ever use the SMG, but it is a popular weapon amongst certain people. When I play RD, I actually get people request it regularly.
I don't see the new tesla gun as being that popular. Not unless it is very useful.

**Comment by KorPhaeron** [comment]
Also this was supposed to replace stun revolver, not the SMG

**Comment by Regen1** [comment]
Doesn't matter

The SMG was used extensively as a science / RD / captain weapon, I'd like to see more "experimental" weapons for RnD as well

**Comment by Fox-McCloud** [comment]
It's difficult to give it a solid number because it really depends on how it bounces---if two people are standing close together and one gets hit, both are going to get stunned and quite a decent chunk of damage. Of course, anyone wearing insulated gloves or an engineering hardsuit are going to take reduced damage. They're excellent for crowd control or dealing with grouped individuals (Rev, Shadowlings, Xenos, etc).

**Comment by TheDZD** [comment]
Honestly, I don't really see a problem with removing the stun revolver, considering sec's tasers are going to be better in most cases. RnD has no reason to be printing guns for themselves (unless you are a traitor RD/scientist, but in those cases you already have one of the most idiotically broken jobs for traitoring). I don't see these being hugely useful for sec either, unless you either have a nuke ops situation (hello chain-stunned and dead ops) or a cult that is running around with swords and armor.

**Comment by Fox-McCloud** [comment]
git being shit.

**Pull request closed without merging**
