### PR TITLE
Fires all Lifeguards, Bans Diving, and Forbids Swimming...

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes Pooling.

After fighting with TG for a long while on this, they finally gave in---on the plus side, their server performs better now; on the downside--this system isn't going to get improved upon any time soon--we currently have no use for it, and the edge cases that pooling is useful are difficult to utilize in BYOND; to say the least, it's not worth keeping this around anymore.

RIP Pooling.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Initially thought you were removing the scuba portion of the beach away mission (or the entire beach away mission). But no, just removing the pooling stuff like PutInPool (rip putin pool).

**Comment by KasparoVy** [comment]
Sometimes you just gotta take the plunge.

**Comment by FlattestGuitar** [comment]
🏊 🔫

**Comment by Keilden** [comment]
Pools closed?

**Comment by Crazylemon64** [comment]
Pool's closed.

**Pull request merged**
