### PR TITLE
Buffs atmos access

### PR DESCRIPTION
**Pull request by Birdtalon**
Gives atmos techs access to tech storage.
Gives atmos techs access to the inner engineering storage area.

Doors edited to `access_construction` to allow them access.

🆑 Birdtalon
tweak: Atmos techs have access to tech storage and inner engineering tool room.
/🆑

### CODE REVIEW

**Comment by taukausanake** [comment]
Atmos techs don't have any reason to go into inner Engineering unless there was Supermatter being constructed, which no where in Engineering is that supported by default.

I'd also kind of argue that they don't need access to the tech storage either. Nothing in there that they need access to. Is this an attempt of trying to give Atmos Techs some love?

**Comment by Birdtalon** [comment]
@taukausanake directly taken from the recent Paradise community survey. It's something that seems greatly requested and is more of a QoL feature for atmos techs. They don't have access to the whole engine bay, just the inner part where the tools are stored.

chrome_2018-04-05_18-11-34

**Comment by taukausanake** [comment]
What are the techs expected to do then with this new access then? What equipment do they need from Engineering to do their job that they shouldn't already have access to in Atmospherics? What parts do they need from Tech Storage, aside from the heater/freezer boards, would they need for construction?

Giving them more access isn't going to give them more of their job to do. Defining their job more will. I feel it's not defined enough that an Atmos Tech's job is to seal up breaches, with Engineer's donning their hardsuits to do it instead. Engineers are responsible for mechanical and electrical upkeep of the station while Atmos Techs are responsible for the environmental state

**Comment by Birdtalon** [comment]
Get things that they might need like tools, equipment and materials I imagine. What's the point in saying they can't have access to these things? What are they going to get from these two areas which means they can't have access there? For it to appear in the survey there's obviously a strong desire from people who play the job that they would like this access to make the job better for them. I really don't see the harm in giving them the access they asked for. There's nothing in these areas which is massively important that an atmospheric tech can't have access to. They're a part of engineering not a prisoner.

**Comment by Shadeykins** [comment]
@taukausanake They need to get in that room to get air alarm electronics. Tech storage access gives them access to a retinue of other useful tools (Gloves, Multitools, etc.) which they presently lack but are *absolutely* required if you're doing anything with air injectors.

**Comment by davidchan13** [comment]
Atmos techs definitely need access to the room with all the spare tools lying about. They shouldn't have to wait for the CE or an Engineer to do their job in the event that part of the station is damaged.

Also how do you justify them not having access to basic areas of their department (even Roboticists have Tech Storage access!) when Engineers have access to Air Alarms?

**Comment by granodd** [comment]
Honestly this is a well needed change. Sure you can forego much of the stuff in tech storage if you just, say, redo the piping in atmospherics. But then what? The more savvy tech will start doing atmos projects, which more often than not, require them to ask for aid from their friendly engineers.

Gloves, air alarms, the works, are also needed if they ever expect to set up something like a TEG room, which is essentially "Atmospherics: the Engine". _And let's not even mention the fact that fucking engineers have access to air alarms while atmos techs can't even unlock APCs._

**Comment by FalseIncarnate** [comment]
I admit that I'll commonly learn door wires as an atmos tech just to get into tool storage, so I can support this change.

I would recommend just double checking that the atmos techs can't open the electrical supplies lockers (as that is meant to be engineer territory), but I believe that operates off a different access anyways so it should not be an issue.

**Comment by DarkPyrolord** [comment]
This seems like a good change to me, all clear for merging
👍

**Pull request merged**
