### PR TITLE
Gives engiborgs atmos holofans

### PR DESCRIPTION
**Pull request by Superhats**
Adds Atmospheric Holofans to the engineering cyborg modules

:cl: Superhats
add: Added a Holofan to engineering Cyborgs

### CODE REVIEW

**Comment by Spartan6** [comment]
Yeah that's what we need.
Engineering borgs with RCDs having another ability to close off a breach.

NEIN!

**Comment by Citinited** [comment]
Yeah, engiborgs can just close off the breach in as much time as it takes to drop a holosign.

**Comment by KasparoVy** [comment]
Something something reposted argument about not being perfectly equipped for every job

**Comment by Taaketa** [comment]
Yeah as someone who plays borg all the time. This isn't needed.

Birds have ways to seal breaches and they should request crew members to build holofans when they are needed.

**Comment by davidchan13** [comment]
How is having the only tool capable of containing or preventing the spread of plasma leaks and fires 'perfectly equipped for every situation?'

**Comment by Crazylemon64** [comment]
After a discussion, we have decided to close this PR - Engineering cyborgs have plenty of tools to deal with breaches already, and aren't intended to be jacks-of-all-trades.

**Pull request closed without merging**
