### PR TITLE
Moves NanoTrasen Representative to 50 command hours

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Moves NanoTrasen Representative to a 50 command hours timegate. This is the last part of the karma purge, as Barber is being handled in #17584. 

I am not 100% sure on 50 hours yet, maybe drop it to 25, not 100% sure.

## Why It's Good For The Game
The karma job purge must continue.

## Changelog
:cl: AffectedArc07
tweak: NanoTrasen Representative is now gated behind 50 command hours as opposed to 30 karma. If you had previously purchased the role, your karma will be refunded.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
50 hours is fine IMO. You're the person Command goes to with troubles about doing Command stuff. You should be reasonably experienced in how Command as a whole works.

**Comment by Daylight2** [comment]
Is there any reason beyond "hour requirements good" we're removing all karma jobs? I feel like certain jobs being behind karma requirments gives people more incentive to roleplay and do cool stuff. This seems to incentivise joining as HoP or captain for a few weeks whilst watching YouTube or doing other things.

Also, why does NT rep, whose job consists of sitting on the bridge and maybe writing a fax once a shift, require more hours played that captain and AI combined? Seems quite extreme concidering the NT rep has little more power than an assistant with a fax machine. 

And lastly, could we please count hours already played in these roles towards the timegate? I feel like someone who already played around 25 rounds of NT rep before this change isn't going to become a whole lot more proficient at their job by playing other command roles.

**Comment by Calyxman** [comment]
> Is there any reason beyond "hour requirements good" we're removing all karma jobs? I feel like certain jobs being behind karma requirments gives people more incentive to roleplay and do cool stuff. This seems to incentivise joining as HoP or captain for a few weeks whilst watching YouTube or doing other things.
> 
> Also, why does NT rep, whose job consists of sitting on the bridge and maybe writing a fax once a shift, require more hours played that captain and AI combined? Seems quite extreme concidering the NT rep has little more power than an assistant with a fax machine.
You raise some really good points here. If we're removing all karma jobs and not adding new ones, why not axe the Jobs section?
Theoretically, NTR has power on the station. Theoretically.

**Comment by AffectedArc07** [comment]
@Daylight2 

> Is there any reason beyond "hour requirements good" we're removing all karma jobs? I feel like certain jobs being behind karma requirments gives people more incentive to roleplay and do cool stuff. This seems to incentivise joining as HoP or captain for a few weeks whilst watching YouTube or doing other things.

Yes. Your ability to play a job should be gated by your actual experience in a department, not the size of your metaclique, and leadership have agreed that they all need axing, hence they they have all been axed.

> Also, why does NT rep, whose job consists of sitting on the bridge and maybe writing a fax once a shift, require more hours played that captain and AI combined? Seems quite extreme concidering the NT rep has little more power than an assistant with a fax machine.

They need to be fully aware of SOP and how command operates at a proper level

> And lastly, could we please count hours already played in these roles towards the timegate? I feel like someone who already played around 25 rounds of NT rep before this change isn't going to become a whole lot more proficient at their job by playing other command roles.

We dont track hours on role, hence why its department based

---

@Calyxman 

> You raise some really good points here. If we're removing all karma jobs and not adding new ones, why not axe the Jobs section? 

Thats... thats the point

**Comment by Dafrek** [comment]
50 command hours makes sense to me, although I would prefer if the Blueshield had less command time required than the NT Rep.

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
