### PR TITLE
Changes Merchants Fluff item.

### PR DESCRIPTION
**Pull request by TravellingMerchant**
Changes my fluff item to a Shellguard Helmet, from a Steel Sallet. Actual item is a modkit for helmets. 

This PR changes the four states from four versions of open/closed to open/closed of two styles. Technician and soldier. It also changes the sound and changes the name/modify text. On top of that, it also adds the on ground icons that were missing from my original sallet. 

It has already been greenlit by all three heads.

https://i.imgur.com/wzdG6OC.png
https://i.imgur.com/e2eqyle.png
https://i.imgur.com/R23xten.png

I haven't made a PR in quite awhile. If I messed anything up code wise let me know.

### CODE REVIEW

**Comment by TravellingMerchant** [comment]
Whoops, didn't realize two of the image links were the same. Fixed.

**Comment by TravellingMerchant** [comment]
If there are no problems, is it ready to merge?

**Comment by tigercat2000** [comment]
👍

**Comment by TravellingMerchant** [comment]
Thank you!

**Pull request merged**
