### PR TITLE
Mafland - Lobby music

### PR DESCRIPTION
**Pull request by Heroo2012**
SRC: https://modarchive.org/index.php?request=view_player&query=48844
File size: 919KB
Duration: 2:44

Found a neat song from the web while playing global sounds on the server. It took me a whole day just to find a good file type and another to convert it into an ogg that is less than 1 meg. Apparently, there are no XM to MIDI converters anywhere. Sadly, the song quality dropped dramatically when lowering the size of the file, I am able to make the file quality better but the size would have to go above 1.3MB. The theme of this song sounds similar to our existing lobby songs, so I had to include it. Hope you like it!

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
heyyy that's pretty good

**Comment by granodd** [comment]
That's pretty snazzy. I like it.

**Comment by Fox-McCloud** [comment]
This sounds extremely low quality and out of place compared to the other titles.

It's also extremely ambiguous where you got it at and what license it has.

**Comment by taukausanake** [comment]
Wow it sounds good. I can't say it sounds like Paradise though, maybe something a little more meme-y and with the push of higher RP...
But I like it! I really do! It wouldn't hurt to have this as lobby music.

@Fox-McCloud how does it sound low quality? I think it sounds fine quality-wise. Doesn't sound too different from the other songs we have

**Comment by Heroo2012** [comment]
@Fox-McCloud 

> It's also extremely ambiguous where you got it

If you press the link at SRC, you are directed to a player where you see two buttons.The button above is the download link, which downloads a .XM file. I used a personal converter to convert it to the .OGG type with lower quality settings.

 buttons

> and what license it has.¨

The button below the download one, has relevant details of the file such as license. Feel free to have a look. I was sure that anyone interested in the song would notice this, but as clarification, I will include it here.
(https://modarchive.org/index.php?terms-upload)

According to the site license, the song has to be uploaded by a copyright holder or by a person holding distribution rights to the song. The rights holder has to agree that they hold the rights to distribute the file for free using the site. 

The non-XM version of the Mafland song was published using the Attribution Non-Commercial Creative Commons License. (https://creativecommons.org/licenses/by-nc/3.0/)

**Comment by granodd** [comment]
@taukausanake Memey? Hardly. It reminds me a lot of the stuff we already have, namely the swingy theme, but with a touch of "Endless Space" and then some techno/electronic elements.

**Comment by taukausanake** [comment]
@granodd guess I've had lobby music turned off for too long. I'll fix that next time I play

**Comment by SamHPurp** [comment]
@granodd the only memey one is the Highlander music.

**Comment by Vivalas** [comment]
Scotland the Brave isn't a meme.. also this sounds good but I don't think a song with a 2:39 duration like this should be hard to get around the 1 MB area with .ogg format. I might mess around with it.

**Comment by Vivalas** [comment]
http://www.mediafire.com/file/7026opwqr7cqk3d/samples.zip

Okay here I included the original, plus mafland1 and mafland2. Mafland1 is slightly lower quality but smaller. 1 is 1.1 MB and 2 is 1.2 MB.

**Comment by Ataman** [comment]
http://bhtp.net/paradise_sounds/sounds/mafland.ogg @ 985 kB
Better quality.

I recommend ffmpeg for all your future conversion needs.
Command for reference:
`ffmpeg -i mafland.xm -af "volume=6" -ac 1 -qscale:a 0 mafland.ogg`
Converts xm files to ogg with a 6 times volume boost, mono channel and 0 quality setting.

**Comment by SamHPurp** [comment]
@Ataman that is muuuuch higher quality.

Listening to it again now, I've changed my mind, I wouldn't mind it being added.

**Comment by Ataman** [comment]
@SamHPurp Glad to hear, I thought it deserved another chance.

**Comment by taukausanake** [comment]
omg yes I don't know how it sounded before but this new file sounds great. Make lobby music great again

**Comment by Fox-McCloud** [comment]
This doesn't really fit well with the existing songs, at all; it sounds like something that belongs in an eastern european game or pirateland.

The quality is also near midi levels for something that's nearly 1 MB in size.

**Comment by Vivalas** [comment]
Out of all the PRs closed today this one seems the most arbitrary. Things like lobby music are wholly subjective so maybe everyone lacks a good argument but this song was pretty damn good, at least maybe give it a chance so people can actually hear it on main.

**Pull request closed without merging**
