### PR TITLE
Event Announcement Chance

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
rscadd: Makes mid-round events have a chance to not be announced by centcom
/:cl:

This should make mid game events less "Unknown organisms? Time to weld the vents!", and more "There /probably/ isn't a giant xeno nest behind this door"

### CODE REVIEW

**Comment by Crazylemon64** [comment]
The overall principle is sound, yaya! :+1:

**Comment by theColdflame** [comment]
If xenos or a blob aren't caught early it's game over for the crew.

Some of the more minor events could go unannounced, but :-1: if major events can slip by

**Comment by Norgad** [comment]
@theColdflame I can always make the major events much less likely to go by unannounced. Also, blobs get STOMPED as soon as the announcement goes off.

**Comment by Norgad** [comment]
Someone with coding knowledge pleas tell me I've done nothing retarded

**Comment by theColdflame** [comment]
Something being less likely to happen doesn't make it less destructive. Even if unannounced 1% of the time, that's still 1% of the time the round gets ruined.

Midround blobs aren't supposed to 'win', they're there to cause the crew trouble. 

Aside from xenos/blobs, though, a chance for events to fly under the radar could be interesting

**Comment by CrAzYPiLoT-SS13** [comment]
@Norgad You added some garbage commits from two weeks ago. I am no experienced git user, so you should probably seek help about this from @Tigercat2000

**Comment by Norgad** [comment]
@CrAzYPiLoT-SS13 Ill try to revert those.

**Comment by Norgad** [comment]
@Crazylemon64 Yea, no. I'm gonna need @tigercat2000 to help me

**Comment by Keilden** [comment]
Maybe have a chance to announce the wrong event instead? Then after 5-10 minutes CC sends a "We are sorry but the vine infestion is really a blob" message.

**Comment by Fox-McCloud** [comment]
May be better to just delay the announcements more, rather than make it chance based.

**Comment by CrAzYPiLoT-SS13** [comment]
@Norgad Oh God, don't revert those. From what I see they are merge commits,
which will prolly get ya some conflicts if reverted, and will actually make
two more garbage commits

**Comment by Norgad** [comment]
@Fox-McCloud Hmm. Maybe. I thought that making the event announcement chance based would discourage meta, as no longer would you be absolutely certain that there are or aren't space-vines or a disease. Would keep the crew on their toes. I do see where you're coming from with just delaying the messages, but that may just make people wait around for an announcement to confirm it, rather than confirming it themselves.

@Keilden An interesting idea, though with still having an announcement the crew will still know /something/ happened. Maybe it could be implemented alongside the chance to not announce, to further mirage meta. Though I'd have to figure out how to code that.

**Comment by FalseIncarnate** [comment]
Unless we removed it, there used to be the "false alarm" event, which would falsely announce a random event without actually triggering it. Nothing scarier than hearing the announcement of a virus outbreak or aliens and not being able to find it.

**Comment by Norgad** [comment]
@FalseIncarnate Found it! https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/false_alarm.dm I'll re-implement it once I'm at a computer.

**Comment by Fox-McCloud** [comment]
Yeah, false alarm event would be better than this.

**Comment by Norgad** [comment]
@Fox-McCloud They would both work quite well in tandem

**Comment by tigercat2000** [comment]
I'd rather not have pretty severe `moderate` events go unannounced.

**Comment by Norgad** [comment]
Updated. "False Alarm" seems to be broken, so the inclusion has been commented out. I'd like some suggestions for the probabilities if they need to be adjusted.

**Comment by Norgad** [comment]
@TheDZD Can you please remove the 'Do Not Merge' and 'Work In Progress' labels?

**Comment by Norgad** [comment]
@TheDZD or @Fox-McCloud 
It's ready to merge if nobody adds any last minute complaints.

**Comment by tigercat2000** [comment]
i still don't like this
it's "RNG decides if you get to know something's about to fuck up your station"

**Comment by Fox-McCloud** [comment]
With @tigercat2000 on this one

I'm ok with False Alarm being fixed up and made functional though, because...players looking for an event that doesn't exist causes far less damage than than not looking for one that does exist.

**Comment by Norgad** [comment]
@Fox-McCloud @tigercat2000 The fact that you don't know what kind of danger is coming is part of what makes the game fun. Its the reason the gamemode is 'secret' and not announced each round; Could be vox traders, could be a wizard, you never know. Even of you don't agree with what I'm saying, all the major events have very small non-announce chances anyway, so it's not too bad.

**Comment by Regen1** [comment]
I agree with this, I want a small change of it not being announced, maybe the blob gets an extra 5 minutes of growing before the crew notices, so what? The blob got lucky and now the crew has to deal with it.

The game isn't supposed to be easy

**Comment by Norgad** [comment]
> The game isn't supposed to be easy
This is exactly my point. Too often, people complain about boring shift where nothing happens. The game would be nothing fun if everything went as expected every round.

**Comment by TheDZD** [comment]
Way this seems to be implemented looks a bit copy-pastey. Better way would just be to have both the announcement message and the probability of announcing be variables in `/datum/event`, and have `/datum/event/announce()` do the `prob()` check using the variable for announcement chance.

**Comment by Norgad** [comment]
@TheDZD That may be difficult. Several events use announce() to pull players from the ghost population, as well as for their centcom announcement. With your solution it may break the events by making it impossible to get the "Would you like to play as []" dialogue box.

**Comment by TheDZD** [comment]
@Norgad Except they don't. `announce()` is just used for announcing events, and only a few events have special handling that isn't either do nothing, or announcing the event (carp and swarmers are notable ones) and for such cases you can simply just overload the proc and not call `..()`.

**Comment by Norgad** [comment]
I don't know enough about datums to do what DZD is asking, and so I'm closing this. Might remake it some-other time later.

**Pull request closed without merging**
