### PR TITLE
Fix: Adds the clownish language to honksquad members

### PR DESCRIPTION
**Pull request by owenowen212**
This is just a small fix in response to r3valkyrie's issue here: https://github.com/ParadiseSS13/Paradise/issues/7737

🆑
add: Adds the clownish language to honk squad members.
/ 🆑

### CODE REVIEW

**Comment by alexkar598** [comment]
The honkmother surely approves

**Comment by SamHPurp** [comment]
Actually one thing missing @owenowen212 .... a changelog!

**Comment by taukausanake** [comment]
I'd almost says Clownish should be their default language but whatever. Good addition still

**Comment by SamHPurp** [comment]
you need to stick `add:` at the front of your changelog line

**Pull request merged**
