### PR TITLE
Makes dog barking grammatically correct

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Fixes the `.,` in dog barking.

## Why It's Good For The Game

🐶

## Images of changes

Old:
old
New:
new

## Changelog
:cl:
spellcheck: Dog barking is now grammatically correct
/:cl:

### CODE REVIEW

**Comment by Varghh** [comment]
Speed merge, this is unplayable now

**Comment by hal9000PR** [comment]
What Varghh said. I can no longer play this game without this.

**Comment by Cocacolagua** [comment]
don’t check gitblame please

**Comment by SabreML** [comment]
> don’t check gitblame please

*squint

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
