### PR TITLE
Monkey Shadowlings who Hatch will get their HUD changed to be the human HUD.

### PR DESCRIPTION
**Pull request by Emanthealmighty**
**What does this PR do:**
Small change that makes it so that if for any reason you use the "Hatch" ability as a shadowling but are also a monkey, your HUD will be changed to be the human one. 
(Code was copy and pasted from the Monkey to Human transformation code)

**Changelog:**
:cl: EmanTheAlmighty
tweak: Using the Shadowling ability "Hatch" as a monkey will change your HUD to be the human one.
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
How was this bug even found in the first place

It seems like such a strange, yet perfectly SS13, bug.

**Comment by Emanthealmighty** [comment]
You'd be suprised....

I literally just decided to possess a random monkey and turn myself into a shadowing from the traitor menu... Then when I hatched I noticed that the HUD didn't change and I went, "well, people CAN be monkeys and also be unhatched shadowings..."

And then this. These are the fine details, the fine things that *truly make this game*.

**Comment by Emanthealmighty** [comment]
I'm closing this so I can fix all the problems I accidentally caused, and then I'll make a new PR.

**Comment by Emanthealmighty** [comment]
I'm closing this so I can fix all the problems I accidentally caused, and then I'll make a new PR.

**Pull request closed without merging**
