### PR TITLE
Jackboots and black gloves resprite, THEY'RE ACTUALLY BLACK NOW WOOO

### PR DESCRIPTION
**Pull request by ElorgRHG**
## What Does This PR Do

Ports: https://github.com/tgstation/tgstation/pull/64863

So short story, ever since I started playing SS13 I always liked how the jackboots looked, thing is, I always thought that my characters' socks kept "clipping" through the sprite, and as such, never used them because that was kinda cringe.
Then I discovered I can check the sprite in the DMI to see what's wrong...
AND IT TURNS OUT ITS JUST SOME SHITTY "SHINE" SOMEONE ADDED TO THEM, if you're the one who originally sprited the jackboots and added the "shine", fuck you.

## Why It's Good For The Game

Actual black gloves that are not... gray... is good, also better jackboots also good :)

## Images of changes

THE SHINE IS CRINGE
image

Anyways, a comparison:
Old jackboots + "black" gloves 

<details>

image

</details>

New jackboots + black gloves 

<details>

image

</details>

Look at the linked PR for obj sprites.

## Testing

Saw jackboots without shitty shine, was happy.
Saw not gray black gloves, was happy.
Am happy.

## Changelog
:cl:
imageadd: Resprited black gloves, to be actually black, and jackboots and laceup shoes, to be mildly more black and fit with the gloves.
/:cl:

### CODE REVIEW

**Comment by roarbark** [comment]
the highlights on top of the boots really helped break up the black blob thing and gave it character, though removing the weird white grayish bits at the tips is good. the new ones look better than the old ones, despite it missing that a bit. the new gloves are better too. in total its an improvement, in my opinion.

also please show how these work with the rest of the sec wardrobe

**Comment by ElorgRHG** [comment]
> also please show how these work with the rest of the sec wardrobe

I'm not arranging like every single SecDrobe choice here (because I'm lazy), but I will do this

<details>

image

image

image


</details>

I'll just say that these most definitely will look better than their predecessors in every combination you can think of.
Also don't get attached to these sec jumpsuits, their time on this codebase is drawing to a close too :trollface:

**Comment by Contrabang** [comment]
Heres a few photos in game of a seccie with different darkness
image
image
image

Heres the new gloves (not shown in PR, because images of changes is for losers apparently), compared to other gloves. I think the colors are nice but the TG shading and adding of the circular thumbs look slightly weird compared to the other gloves.
image

**Review by Sirryan2002 — APPROVED** [review]
code looks fine, I'm not seeing anything wrong with the sprite diffs either

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
