### PR TITLE
Massively optimises the MC

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
This PR tweaks the MC so that it will process more efficiently

## Why It's Good For The Game
More performance is more better

## Changelog
:cl: AffectedArc07
tweak: Optimised the hell out of the MC
/:cl:

### CODE REVIEW

**Comment by Gatchapod** [comment]
Now it won't crash randomly.
It will stop working pseudo-randomly, as intended.

A small price to pay for the code working as intended.

**Comment by Terilia** [comment]
Why is this not merged yet? 

https://media.giphy.com/media/3ohzdIuqJoo8QdKlnW/giphy.mp4

**Comment by Fox-McCloud** [comment]
Someone wants shanked.

**Comment by KasparoVy** [comment]
`qdel(self)`

**Comment by AffectedArc07** [comment]
Ok its the second of april in this country now

**Pull request closed without merging**
