### PR TITLE
Removes asset logging

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Removes the logging of `asset.log`

Currently, we write a log line every single time we send an asset to a client.
image
Yes, that log is over twice the size of the log of everything happening in the game.

image
Why the hell are we logging this useless data?

(Fun fact, it used to be worse back when we still had nanoUI)
image
**Yes, that is 87mb of useless logs. In one file**

## Why It's Good For The Game
Why the **FUCK** are we logging this useless data

## Changelog
:cl: AffectedArc07
del: Removed asset logging. This thing consumed monsterous amounts of storage space for no reason at all.
/:cl:

### CODE REVIEW

**Review by farie82 — APPROVED** [review]
The only reason I can see for this being useful is when you're developing things surrounding the assets.
You *could* make this a debug mode only thing. But just removing it is fine

**Comment by AffectedArc07** [comment]
We have breakpoints for that

**Comment by farie82** [comment]
> We have breakpoints for that

Logging is usually used to note things down that happen in production. Where you don't have access to breakpoints or the like.
But as I said. We've not had any use for this logging in a while and prob never will since it is super basic and can only point out if something is not send

**Comment by AffectedArc07** [comment]
> happen in production. Where you don't have access to breakpoints or the like

You underestimate my level of shittery

**Comment by dearmochi** [comment]
> 
> 
> > happen in production. Where you don't have access to breakpoints or the like
> 
> You underestimate my level of shittery

unknown

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — APPROVED** [review]
I approve of this.
The asset logs are huge, and in the ~2 years I was host, never used once.
Good riddance.

**Review by Gmak4333 — APPROVED** [review]

**Comment by variableundefined** [comment]
Hmmm yes, logging

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
