### PR TITLE
Adds Pod Pilot Jumpsuit

### PR DESCRIPTION
**Pull request by TheBeoni**
Hola this is just VERY VERY late re upload of older PR https://github.com/ParadiseSS13/Paradise/pull/3648
:cl:TheBeoni
rscadd: Adds "unique" jumpsuit for Pod Pilot so they can finally stop using security one
            Added picture because i do not like that red label
/:cl:

013f42c2-d765-11e5-942f-f8d8806e5dda

### CODE REVIEW

**Comment by KasparoVy** [comment]
Here's the Vox one.
[vox pod pilot.zip](https://github.com/ParadiseSS13/Paradise/files/389728/vox.pod.pilot.zip)

**Comment by TheBeoni** [comment]
Why did i forgot about it

**Comment by KasparoVy** [comment]
Shouldn't require any additional code since the vox uniform species fitting is done at the most basic level

**Comment by TheBeoni** [comment]
@KasparoVy I actualy have the sprite in my PC already i just forgot about it.

**Comment by TheBeoni** [comment]
@Fox-McCloud will this get merged i think 24 hours passed and there are no objections :)

**Comment by KasparoVy** [comment]
Might need to get ingame pictures of the human and Vox version to clear up the Sprite PR W/o Pics label first

**Comment by Nienhaus** [comment]
Oh shit, I remember this.

**Comment by KasparoVy** [comment]
_Styling super similar to the Vox ERT uniform, as is the Human version to the Human ERT uniform._
resizedvoxpodpilot

**Comment by Fox-McCloud** [comment]
Still needs pics @TheBeoni 

Just posting the tiny sprite as it appears in the file doesn't really give people a good idea of how it looks.

**Comment by Nienhaus** [comment]
lwhsgt0

**Comment by LightningLynx** [comment]
cant wait for HoSes to start stealing this from their locker to look tacticool

**Pull request merged**
