### PR TITLE
Adds in Headphones

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in headphones as a loadout selection option.

Sprites from Polaris.

These don't do anything, at all, mechanically; they're just some ear-wear that gives little animated musical notes next to your head when you're wearing them and they're turned on

img

:cl: Fox McCloud
add: Adds headphones into the game as a loadout item
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Huh.

**Comment by Spacemanspark** [comment]
Oh neat, I have these set on my Polaris loadout.

**Comment by DaveTheHeadcrab** [comment]
OP.

**Comment by Earthdivine** [comment]
Time to spawn in as a Deaf person with these and act like I'm not caring what people say.

**Comment by Fox-McCloud** [comment]
>Time to spawn in as a Deaf person with these and act like I'm not caring what people say.

So mean.

**Comment by Earthdivine** [comment]
@Fox-McCloud I'm sorry I cant hear you over my music.

**Comment by IcyV** [comment]
Clearly when emagged they should should deafen someone entirely if turned on. Maybe then people will take not having your music up loud as a serious warning.

**Comment by Spacemanspark** [comment]
Maybe it should just play extremely loud music to break their ears IRL :^)

**Comment by Necaladun** [comment]
Fuck deafen. Do actual brute/brain damage as it cranks space-speed-metal into your ears at 20000dB.

**Comment by Davdichan** [comment]
Syndicate version that lets you eaves drop on people through walls?

**Comment by IcyV** [comment]
>Fuck deafen. Do actual brute/brain damage as it cranks space-speed-metal into your ears at 20000dB.

Literally melts your brain. I like it.

**Comment by taukausanake** [comment]
Looking at the code, does this also do the thing for an ear clothing item that fits both ears requiring both ears free? It has also bugged me you can only wear ear clothing on one ear and not the other

**Comment by Fox-McCloud** [comment]
@taukausanake 

I didn't touch the functionality of any ear items. I did a code cleanup only.

**Pull request merged**
