### PR TITLE
Rewrites confirmation prompt for touching SSD players

### PR DESCRIPTION
**Pull request by blinkdog**
## What Does This PR Do
Rewrite the confirmation prompt for touching SSD players, such that it specifies that you can take people to cryo, or give them medical treatment without ahelping for permission.

The above text is taken verbatim from [Kyet's Changes Wanted](https://www.paradisestation.org/forum/topic/18118-kyets-changes-wanted/).

**Old message:**  
Interacting with SSD players is against server rules unless you've ahelped first for permission. If you have, <ins>confirm that</ins> and proceed.

**New message:**  
Are you taking this person to cryo or giving them medical treatment? If you are, <ins>confirm that</ins> and proceed. Interacting with SSD players in other ways is against server rules unless you've ahelped first for permission.

## Why It's Good For The Game
Players are informed of commonly permitted ways to assist SSDs, without adding to admin workload.

## Changelog
:cl:
tweak: Changed the confirmation prompt for touching SSD players
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
Could I suggest adding an adjacency check to this, maybe not in this PR as you're doing one of Kyet's changes but what are people's thoughts? I've accidentally clicked an SSD before who is across the screen and get that prompt.

**Comment by Carthusia** [comment]
Perhaps add a note that providing medical attention to SSD players is allowed, can only imagine how many people who SSD'd, but came back say 3-4 minutes later, ended up dieing because people didnt treat them due to worrying about that message saying "Do not touch them"

**Comment by blinkdog** [comment]
> Could I suggest adding an adjacency check to this, maybe not in this PR as you're doing one of Kyet's changes but what are people's thoughts? I've accidentally clicked an SSD before who is across the screen and get that prompt.

I'll wait for Kyet to weigh in if it's okay to put that in this PR. If we don't do an adjacency check in this PR, I'll open an Issue to make sure it doesn't fall off the radar.

**Comment by blinkdog** [comment]
> Perhaps add a note that providing medical attention to SSD players is allowed, can only imagine how many people who SSD'd, but came back say 3-4 minutes later, ended up dieing because people didnt treat them due to worrying about that message saying "Do not touch them"

The new SSD message in this PR is:


Are you taking this person to cryo or giving them medical treatment? If you are, <ins>confirm that</ins> and proceed. Interacting with SSD players in other ways is against server rules unless you've ahelped first for permission.


When you read it quickly, does it communicate that medical treatment is okay? I say quickly because during a game, there are a lot of things competing for attention. Subtle wording is nice for novels, but not so nice if you need to know if you can heal this person before the terror spider stops munching the other guy and decides that you are next.

If the language is at all unclear, we can still change it easily.

**Comment by Carthusia** [comment]
Security can also continue an arrest/prisoner processing IF they were already in the act of doing it, perhaps a note showing this is allowed to?

**Comment by variableundefined** [comment]
I'm pro adding an adjacency check to this.

**Comment by Gatchapod** [comment]
In its current form (no adjacency check), doesn't it prevent people from shooting SSD players?

**Comment by Kyep** [comment]
I'm against adding an adjacency check to this, because it would lead to situations where someone could shoot an SSD player from across the screen without getting the prompt.

**Pull request merged**
