### PR TITLE
ACTUALLY ADDS "Gateway Explorer" TO SHAFT MINER.

### PR DESCRIPTION
**Pull request by razekpraxis**
ACTUALLY ADDS "Gateway Explorer" TO SHAFT MINER TITLES. ADDS GATEWAY ACCESS

### CODE REVIEW

**Comment by razekpraxis** [comment]
OKAY GOOD, I DIDNT FUCK IT UP THIS TIME

**Comment by QQCucumber** [comment]
:-1: This should be by the HoP's discretion, not a default part of the occupation options.

**Comment by sssfffee334ef** [comment]
Makes me want clown bots, someone make that.

**Comment by FlattestGuitar** [comment]
Miners should mine. This should be the HoP's thing to give out, not a job. :-1: from me, just as with the science version.

**Comment by razekpraxis** [comment]
There's not always going to be a HoP or captain to give this out.

**Comment by DaveTheHeadcrab** [comment]
If the station is so understaffed that it's lacking an HoP or Captain why in the flying assistant tits should we be allowing crew members to leave easily? :-1:

**Comment by razekpraxis** [comment]
Fine, whatever. Someone else can do it.

**Comment by mrturkeytoe** [comment]
If anything I'd say add gateway explorer as a karma job or a alt assistant job since assistants are useless fucks anyways it doesn't matter if they die

**Comment by Fox-McCloud** [comment]
:-1: 

Miners need to be doing their damn jobs, not faffing off at the gateway every shift.

**Comment by Vivalas** [comment]
This should be more of a science job really.

**Comment by razekpraxis** [comment]
Tell that to literally everybody who just whined at me for making it a science job

**Comment by Regen1** [comment]
Miner != gateway explorer
:-1:

**Comment by ScratKnapp** [comment]
Make it an actual karma job or civillian alt title.

:-1:

**Comment by QQCucumber** [comment]
I wouldn't even make it a karma job, then it would be harder to justify gathering people for gateway missions because there's now an official job for that. It's just something that should stay discretionary.

**Comment by KasparoVy** [comment]
:-1: Sorry. I just can't think of a way to justify this.

**Comment by Vivalas** [comment]
@razekpraxis they whined at you for making it a mining alt-title, which is a terrible idea, rather than a science job

**Pull request closed without merging**
