### PR TITLE
NSS Arrhodes - Shepard Station [Redux]

### PR DESCRIPTION
**Pull request by kugamo**
## What Does This PR Do
Shepard Station returns! After long deliberation by the design team they approved the opening of a PR for TMing, and this is it! 

#17710 was the initial PR of the station. Which was found to be nonviable due to lag, but with the new Maptick threading that the byond devs have introduced in the latest version of the engine this map could preform much better (hence this PR).

Since the old PR changes include:
- Addition of a small hallway that will grant scientists a shortcut to their department from arrivals. (Travel time for them was a serious concern)
- Removal of most of the catwalks and lattices strewn about space near the station (To cut down on atom count and hopefully lag).
- A connection between engineering and science maintenances that undeadends them.
- More direction signs and station maps, to hopefully better span the gap in the playerbase's lack of familiarity with the new map.
- Lastly replaced the SM engine with the boomer tesla/singulo as default (Design team feedback invited on this).

Its a completely unique map made original by yours truly for Paradise. It was purposefully not made to completely conform with the meta that players might be used to so as to enliven everyone's experience of the game. So experiment and have fun.

## Why It's Good For The Game
A new map to offer more wholly unique experiences that only maps can grant. Its unique to Paradise and offers many advantages and unique experiences that its design can offer that other maps dont.

**!SPECIAL NOTE!**
No the wires weren't a joke, I wasn't trying to pull a fast one. I genuinely wanted to see them tried, and thought such a minor aspect to the game wouldn't be greatly affected by the new meandering. My intention was to add some character to this part of map design that is more or less devoid of it, and thought itd be fun for everyone to experience. I have since regulated them to the maints due to the good points people made to me, and kindly ask those people who formulated their opinions of the map over this to reconsider.

**NOW WITH ARRIVALS AND DEPARTURES SWAPPED** -6-20-23

## Testing
Rigorously reviewed and playtested in the summer of 2022, plus far too many private debug sessions testing everything I could think of.

## Changelog
:cl:
add: Adds the NSS Arrhodes as a station map to the game (aka Shepard Station).
imageadd: Added more sprites for department signs, direction signs, and floor tiles.
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
Needs to be updated with the following PR changes (that are mine): https://github.com/ParadiseSS13/Paradise/pull/20397, https://github.com/ParadiseSS13/Paradise/pull/19076, https://github.com/ParadiseSS13/Paradise/pull/19131, https://github.com/ParadiseSS13/Paradise/pull/20517.

**Comment by SynthTwo** [comment]
LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Henri215** [comment]
image

What happened to the cables?

**Comment by kugamo** [comment]
> What happened to the cables?

They were wired by only the most skilled and patient Nanotrasen engineers, not sure what you mean :o)

**Comment by Sirryan2002** [comment]
so initial impressions with this map:

- It has a lot of personality which is nice and it's causing a few issues
- The silly wires are fine in places like maintenance or solar where you can follow the wire and it's not so ridiculous that it's impossible to work with. However, under tiles in the main hallways and the SMES room (jesus fucking christ) it's way too messy. I get the joke behind squiggly wiring but I think aspects of gameplay are being lost because of it. Engineering especially needs straightforward wiring.

spaghettiewiring

- Many parts of the station are a bit too much. Just observing, it can get really visually noisy regarding floor decals and overall decor/design choices. A lot of it feels very over-designed sometimes where it might just be better to have open space or no coloring. Overall, I think this map needs some more consistency and simple layouts. I still need to play a couple full rounds on this map to get a better view but this is how I feel about it now.
- I like the design of many service locations, the Kitchen and Bar are very nice. The security department is well done; Supply is pretty good aswell.

Spawning in as a player on the arrivals shuttle, I couldn't really easily navigate to the "center" of the map because the design of the hallways did not naturally direct me there. Instead I ended up at multiple dead ends and got turned around pretty quickly. The actual recreational part of the map intended for assistants... is very far away from the arrivals shuttle both distance-wise (which is fine) but the real issues lies in the difficulty getting there. Most of current maps operator on the principle that you can walk nearly in a straight line left -> right or top -> bottom to go from arrivals -> map center -> escape. But this map really doesn't follow it, I'm not sure if breaking the current map meta is really the best way to go here.

**Comment by A-Medster** [comment]
image
so we have a small issue with Atmos, there's no glass on the gas tanks..
so Atmos gets no gasses at round start

**Comment by SteelSlayer** [comment]
I've pulled Shepard from being TM'd. The map (and wiring) is obviously quite contentious. I think this map needs some work before we TM it again.

**Comment by kugamo** [comment]
> image
> so we have a small issue with Atmos, there's no glass on the gas tanks..
> so Atmos gets no gasses at round start

This is incorrect, and not a real issue. The tanks are completely enclosed despite how it might look

**Comment by S34NW** [comment]
> > image
> > so we have a small issue with Atmos, there's no glass on the gas tanks..
> > so Atmos gets no gasses at round start
> 
> This is incorrect, and not a real issue. The tanks are completely enclosed despite how it might look

We no longer map grilles on these tanks

**Comment by ppi13** [comment]
image
Sure is wires

**Comment by AffectedArc07** [comment]
> image Sure is wires

Better image
wtf

**What in the unholy name of christ do you call this**

**Comment by kugamo** [comment]
> > image Sure is wires
> 
> Better image wtf
> 
> **What in the unholy name of christ do you call this**

Too good for this world. 

Reworked version since first TM:

**Comment by HNIII-chili** [comment]
arrhodes botany space bridge misalignment
The Botany Space Bridge in maints is misaligned from the door to the left and cut off
Love the Arrhodes, simple as

**Comment by kugamo** [comment]
> arrhodes botany space bridge misalignment The Botany Space Bridge in maints is misaligned from the door to the left and cut off Love the Arrhodes, simple as

fixed in latest commit!

**Comment by AffectedArc07** [comment]
After a lot of fighting I finally have a Tracy profile of this map to try and investigate the performance issues.

**Comment by warriorstar-orion** [comment]
Remove the varedits on this fast food container at (109, 202):
2023_06_17__20_48_43__paradise dme  shepard dmm  - StrongDMM

**Comment by Sirryan2002** [comment]
Alright so, this is probably going to be controversial but I'm leaving an objection on the PR. Please allow me to explain myself as this is a pretty layered thing:

- First and foremost, like any map addition (Map Rotation(+delta, +meta) and cerestation), it's a massive undertaking and also represents a potential future source of technical debt. In this situation, if Shepard were to be merged, another station would need to be pulled from rotation. In this case it would be either meta or cere. I don't want to get rid of Cere as I think it's a very well-made map. So the bar for merge is that it would need to be better than meta station.
- The things that Meta gets right is that it's navigatable, newbie-friendly, and has a solid maintenance design. I don't feel like Shepard does these things well. When I first popped into the map, I was immediately hit with multiple dead-ends and no clear indication of where to go. Maps really should guide players to the places they're supposed to be going (i.e. the center of the map, escape, or a recreational area like the bar). Ultimately, players hit the first dead-end east of arrivals, get lost north in Engineering, or actually make it to security where they may end up getting lost in the bridge if they decide not to skip the next hallways they see. 
- I think maintenance on this map really has a lot to be desired. There's a few maintenance shafts that are large but ultimately dead-end due to access-locked doors or only have 2 solid entrances (which makes it super easy for sec to pincer antags). Finally, the northern maintenance shaft is cool but when boiled down, it's linear.
- Much of this map feels very disjointed, there's a lot of places where it looks like aesthetics was prioritized over game design. Just because shepard is "different" doesn't mean its better, nor does better-looking equate to being more playable. The 4 tiles hallways to the 2 tile shuttle connectors is an odd choice and the whole fiasco with the wire mess says a lot. I think you need to go back to the drawing board and think about what actually goes into making maps playable and very purposefully making mapping design decisions.

**Review by S34NW — CHANGES_REQUESTED** [review]
Some details I've seen that could be addressed:

- While the concept behind these is neat, it creates a lot of needless complexity and overhead. Please just stick to standard "canister on a port" setups for the airlocks.
It would also be worth removing the vents surrounding the arrivals shuttle as they are not functional airlocks, and removing the catwalks on plating obscuring the vents in the admin ferry dock.
image

- This airlock is not connected to any tank at all. It should also use plating to signal that it leads to space.
image

- Please try to leave a gap between vents and scrubbers to stop atmos going mad.
image

- Again, please remove catwalks here. They obstruct the clear vision of current cycle status.
image

- This is over-engineered as hell, please just do the normal canister on a port setup.
image

- This purple pipe system that runs through all of science can just be removed for canister on a port setups.
image

- Leaving a way for someone to punch into containment without even having any tools is a terrible idea. These are secure areas and not public galleries.
image

- You have a mix of var edited access doors and access helpers, please aim to unify us on access helpers.

- Your window tint control buttons are not standardized on 24 pixel offsets, please amend. 
image

- You have some APCs not using the bump format with random offsets. 
image

- This half invisible light in a wall.
image

- Newscasters are not appropriately bumped and are using custom offsets.
image

- Some fire extinguishers are using different offsets from the normal while still being labelled as bump instances. 
image

- Custom placement intercomms incorrectly labelled as bump instances, 
image

- Whatever this is. 
image


This is my opinion only now, but I really dislike these loopy wires. They will give us problems when we eventually think about smartcables.

**Comment by warriorstar-orion** [comment]
There are too many AI displays on this tile.

**Comment by kugamo** [comment]
Aseprite_oEutqJM7H2
NEW MAINTS

**Comment by kugamo** [comment]
@Sirryan2002 

> Alright so, this is probably going to be controversial but I'm leaving an objection on the PR. Please allow me to explain myself as this is a pretty layered thing:
>
> First and foremost, like any map addition (Map Rotation(+delta, +meta) and cerestation), it's a massive undertaking and also represents a potential future source of technical debt. In this situation, if Shepard were to be merged, another station would need to be pulled from rotation. In this case it would be either meta or cere. I don't want to get rid of Cere as I think it's a very well-made map. So the bar for merge is that it would need to be better than meta station.
> 
>The things that Meta gets right is that it's navigatable, newbie-friendly, and has a solid maintenance design. I don't feel like Shepard does these things well. When I first popped into the map, I was immediately hit with multiple dead-ends and no clear indication of where to go. Maps really should guide players to the places they're supposed to be going (i.e. the center of the map, escape, or a recreational area like the bar). Ultimately, players hit the first dead-end east of arrivals, get lost north in Engineering, or actually make it to security where they may end up getting lost in the bridge if they decide not to skip the next hallways they see.
>

Since you brought this point up with me, I've swapped arrivals and departures to direct people into the service department. 
I also removed the hallway east of arrivals like day 3 of the TM, so there are zero dead ends now for people to get "lost" down.

Indications of where to go include departments separated by space bridges, and marked with a signs there on the bridges. Each department having a unique floor coloring in the halls so you know where you are even if you ignore the department of the rooms along side them. On top of this the end of every hallway in a department there are direction signs towards every department on the station. Lastly theres station maps in arrivals/service/security/dorms as well as inside engineering. Anyone saying navigation is difficult is simply just inexperienced with the map, ignoring all the helpful hints I placed at every point of the hallways on the map, decrying the departure from the box-style layout that 3 of our maps share, or all of them. No one is going to be familiar enough with a map to easily navigate it from the get go, arguing this point against Shepard (and despite everything I've done to aide these people) is really unfair.

>I think maintenance on this map really has a lot to be desired. There's a few maintenance shafts that are large but ultimately dead-end due to access-locked doors or only have 2 solid entrances (which makes it super easy for sec to pincer antags). Finally, the northern maintenance shaft is cool but when boiled down, it's linear.

Meta maints are objectively some of the worst, completely linear 1 or 2 tile wide shafts with at most 3 entrances/exits. Farragus maints are even worse with maybe 1 or 2 maints not having only two entrances/exits... ontop of multiple dead ended maints across that map. I'd intentionally made the maints more minimal and pincerable to aide security since they are already at a disadvantage to travel times (purposefully made map decision). None of them were or are dead ends.. this is and was just factually incorrect. But despite all this I've humored you and remapped them. They are now some of the best maints of any of our stations, multiple paths through them at almost every point, expansive, and with many entrances and exits.

> Much of this map feels very disjointed, there's a lot of places where it looks like aesthetics was prioritized over game design. 
> Just because shepard is "different" doesn't mean its better, nor does better-looking equate to being more playable. 
>The 4 tiles hallways to the 2 tile shuttle connectors is an odd choice and the whole fiasco with the wire mess says a lot.

I'd like explicit points of how its disjointed, actually I'd argue its less of that compared with the box-clone designs. The only dead ended points on Shepard's layout are escape and arrivals (purposefully made map decision), all the other departments are locations along the main hallway loop that runs linearly between these key locations. On top of that I've placed the entrances to areas at horizontal points in the halls, to help emphasize them.

On the box-clones, departments are at the ends of spokes. There their only hints to whats at their end being floor coloring and direction signs.. and in no way does Shepard do this worse. It actually has the most directions of any map. On top of the departments being less segregated from eachother by dead ending hallways, they are organized better on Shepard (purposefully made map decision). All relevant areas for each are grouped together and organized apart from eachother by the space bridges that you call an odd choice (purposefully made map decision).

I've never argued it being different makes it better, the only way in which I brought this point up was to caution people from judging it worse because of it.

If places only **look like** they've had aesthetics prioritized over their game design, but done without impacting the game in anyway isnt that better???. I havent failed to notice you have never once made a point of how they actually do this anywhere, apart from just looking like it. I did make some aesthetic choices, but never at the expense of game design. And I dare anyone to show how this point is true in any way on Shepard, or at least how its done any worse than any of our other maps.

<details><summary>The **ONLY** case where this even might be true is the wiggly wires, and even then not ONCE has or has ever the wiggliness impacted the game in any real way.</summary> 
They simply wiggle 2-3 tiles from where they'd normally run if I mapped them conventionally. They are all clearly visible, and their route isnt obscured **at all**. The result is that they just look different, and I've expressly used this point to add to the aesthetic of the maints where they are now exclusively located. Immediately **ON THE FIRST ROUND** before even there was any evident problem people took offense to their existence simply because they looked messy. Calling it a fiasco because people called them ugly really makes me question your objectivity, its easy to hate a departure from the norm, as well as to buckle to the pressure of the crowd, but there never was or is any objective problem with them. It really fucking stings.</details>

> I think you need to go back to the drawing board and think about what actually goes into making maps playable and very purposefully making mapping design decisions.

I think you've given me way too little credit, and have gotten hung up on things that don't actually impact the game in any way. On the points you made that were valid I've improved the map, and since I've done this I'd encourage you to reconsider the efficacy of the design decisions I actually have made on the map.

**Comment by SteelSlayer** [comment]
We're sorry to say, but we are closing this PR, for a multitude of reasons.

The bar for merge on this PR was that it would replace one of the existing maps, as having 5 maps would be unmaintainable. However, we don't feel like Shepard is necessarily better than any of the other maps we have with multiple years of revisions put into them. 

Additionally, there are still numerous issues with the map when it comes to the review stage, and the general push-back on changes doesn't really fill us with confidence (prime example being how much of a push it took to get the wiring spaghetti removed). The map still has sub-par performance during highpop scenarios (even with the sauna removed), and is not practical to troubleshoot at the moment. We cannot expect AA to lease a server with 128GB of RAM each time we want to analyze a Shepard tracy file for example. And lastly, the unusual design choices, such as the overly complex cycling airlocks systems, and wires (as mentioned before).

There has been a **lot** of internal debate on this map, hence it taking so long for this closure reason, but ultimately, the design team has voted unanimously against this PR due to the aforementioned points.

**Comment by kugamo** [comment]
I removed the spaghetti wiring day 1 of the TM, what pushback? I even said I was perfectly willing to make them exactly like the other maps like 2 weeks ago, and no one said anything to me regarding them. You're making this a point as to why you're closing this? A "_problem_" that existed for ONE ROUND and fixed DAY ONE of the TM?! 

The "overly complex" airlocks you mentioned are two instances of 4 passive vents in a chamber where normally theres just the tank objects. And you're closing the PR when I said multiple times I am perfectly willing to remove them, no one said anything to me regarding them other than S34N (and I did remove the one he mentioned...).

Really, what pushback? The amount of attentiveness to feedback and dedication I have demonstrated here is astounding, I've corrected and altered hundreds if not thousands of details all based on real communications from people for over a month. No one demonstrated to me any sort of line regarding where my artistic freedom ends and the contribution standards begin, and I've moved against it many times to correct problems; where I held true to my vision over peoples feedback I even communicated my willingness to proceed against it if the development team said it was necessary. 

A grand total of ONE person from the design team took the initiative to reach out to me (Sirryan in the form of why hes disapproving of this map here on the PR page) and I listened to this and made drastic revisions on my map. You saying I gave an inordinate amount of pushback is rich when I barely got jack shit from anyone on the development team to pushback against. A grand total of ONE person from the review team bothered to talk to me regarding my map, and guess what!? I addressed and communicated to them regarding every single point they brought up. I don't know what you expect from me, I am not a god, I cannot read people's minds, if you wanted me to change something or improve something you all should have reached out to me.

**Comment by Sirryan2002** [comment]
It's really more than that Kugamo.

The development team in it's current state is somewhat undersupported, everyone on the balance & design team also serve in other roles on the server which take up their time and energy. We have a single dev staffer that is uniquely a review team member. I can't get into some of the other things we've been trying to work through this summer either to improve our response times and productivity on the repository. My point is, all of our energy is finite and has to be shared between however many 100 PRs are opened and merged each month.

Shepard from the start was a massive undertaking, for you and the dev team. I think with every contributor, especially ones that put in a lot of time and effort in large contributions like shepard are entitled to review and attention from the dev team, which is why I lobbied hard to make sure Shepard got the attention and platform it deserved; It's not entitled to approval from the dev team. The Shepard PR has been open for 2 months, in that time there have been multiple discussions a week over parts of the map, our thoughts, and what needed to change which then had to be communicated back to you. All of this takes our time away from things such as our other roles (such as being a head of staff), actively working to review and reduce the PR count, and otherwise giving support and communication to our other 15-20 active contributors.

Because of this, when we need people to make changes to their PR, we expect them to do just that without giving us pushback on things. So when dev team members give a suggestion and ask for a change, and then see that it's still on the map a couple days later being TM'd or is changed only minimally to avoid the actual expected change then it sends a very poor message. You may think the dev team's communication level was poor, I digress. Most design team members checked out on Arrhodes two weeks ago, about a month after Arrhodes starting being DM'd we were still finding issues that needed to be resolved and at that point most work the dev team members were willing to put in on the PR was exhausted. Several team members did not feel this "willingness" to proceed with change from our feedback and got burned out trying to work through it.

Your dedication to the map is clear, and is perhaps part of a larger problem. When contributors refer to their work as `my map` or `my creation` or whatever, it's an indication of how personal the project has become and they attach a lot of what they value on the server to it. You're contributing to a 1000 player community here on Paradise; Your creation needs to fit the needs of the community first and foremost, not the other way around. I've watched this mindset kill the motivation of multiple of our most talented contributors. You might feel like shit right now and like you just lost a lot of progress, maybe now you'll know how I feel every time somebody closes a PR like holomaps or another large PR that I've dumped 2-3 hours into reviewing that I'll never get back. Take some time off to process it if you're really feeling like you got hit hard.

**Comment by kugamo** [comment]
>The Shepard PR has been open for 2 months, in that time there have been multiple discussions a week over parts of the map, our thoughts, and what needed to change which then had to be communicated back to you.

first im hearing about it, when was this ever done even once?

> Most design team members checked out on Arrhodes two weeks ago, about a month after Arrhodes starting being TM'd we were still finding issues that needed to be resolved and at that point most work the dev team members were willing to put in on the PR was exhausted. Several team members did not feel this "willingness" to proceed with change from our feedback and got burned out trying to work through it.

Seriously no one communicated these issues or that they werent being resolved by me. If I had known i was neglecting something i would have resolved it immediately or explained myself. This getting communicated to me never happened. Its one thing to get burned out with working with someone when they are ignoring what youre saying, but you all didnt even give me a chance to. 

You all got burned out? From what? All you had to do was talk to me and you couldnt even do that much. It seems to me you all didnt want them resolved, so didnt contact me. If standing up for your vision gets you condemned as impossible to work with in this community; regardless of the quality of work ive actually made then i dont want to be in it. And by all my accounts thats what happened. 

I took a fucking chance and pushed the envelope forwards once in the tiniest way and you all never lived it down, no wonder every feature on paradise is ported.

**Pull request closed without merging**
