### PR TITLE
Updated SWAT suit and SWAT helmet icons

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

SWAT suit user no more looks like someone who really likes hamburgers

## Why It's Good For The Game

Since swat suit is no more spaceproof, making its icon less big and fat is good.

## Images of changes

swat

## Changelog
:cl:
tweak: Changes SWAT suit and SWAT helmet icons.
/:cl:

### CODE REVIEW

**Comment by HMBGERDO** [comment]
oh fuck i did something bad with icons

**Comment by ppi13** [comment]
What about vox, drask and grey?

**Comment by McRamon** [comment]
image
no need for this PR

**Comment by HMBGERDO** [comment]
Hi hello @McRamon 
My name is Riot Armor
I cover all bodyparts including hands and feets 
image

But my sprite also leaves the place for custom gloves/boots cause it just looks cool
image


Hi hello, my name is Bulletproof Armor and i confirm everything above
image
image


Now seriously. Leaving chance to show your cool red/yellow/black gloves or hands is good by my sight. Since this suit does not protect you from leaving fingerprints, there is no gloves.
Other full armor sets sprites also do not cover everything as i mentioned above.

SWAT suit needs change, its current sprite is disgusting, just look at those legs. 
image
It looks like bloated dead body, not like tactical unit.

**Review by Sirryan2002 — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
