### PR TITLE
Adds Chameleon Bombs

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Inspired by Goon's chameleon bombs.

Adds in chameleon bombs as syndicate gear for clowns! It'll set you back 10 TC a piece.

The chameleon bomb is a device that can be disguised to look like just about any item. Just mark the bomb to register it to yourself, then scan whatever you want the bomb to look like.

The next person to pick up the bomb (that isn't you) will be in for an explosive surprise. Honkkkk.

The user who marked the item can safely pick it up and re-configure it, if desired.

img

:cl: Fox McCloud
add: Adds chameleon bomb to the traitor uplink for clowns for 10 TC
/:cl:

### CODE REVIEW

**Comment by TravellingMerchant** [comment]
_This_ is what clowns have been waiting for. Great idea!

**Comment by Citinited** [comment]
Just checking, this is a syndicate minibomb in disguise, yes?

**Comment by Fox-McCloud** [comment]
@Citinited 

It's a syndicate minibomb that you can make look like just about any object you can pick up.

**Comment by FlattestGuitar** [comment]
>see gun on floor

>pick up

>immediately die; 15% chance you'll get revived from your brain alone because Medbay is operated by xenobio-escapee monkeys

>interesting and deep gameplay where failure is a consequence of your own poor decisions, not come at the hand of something completely out of your control, making you frustrated and salty so that another player can get a giggle

There isn't even anything interesting happening here, someone just blows up. Pizza bombs do a similar thing, but this only encourages this sort of an item to be used.

In my eyes, this will not lead to anything fun.

**Comment by taukausanake** [comment]
@FlattestGuitar Even a clown traitor needs to complete their objectives. But I can see this as an interesting way to breach a wall. Just put a thing people want right next to it

**Comment by FlattestGuitar** [comment]
>Even a clown traitor needs to complete their objectives.

True, but we shouldn't encourage these interactionless murders to be happening. It's not interesting to anyone if you just get killed out of the blue like that.

>But I can see this as an interesting way to breach a wall. Just put a thing people want right next to it

Why not use a ten times less expensive C4? Not to mention this won't even reliably destroy walls.

**Comment by outbools** [comment]
Well there is not so many things clown can easily get which would attract spessman. To get a gun you actually need to steal it... Or order it from uplink... So i think it need higher price so you can only spend it for bomb and something that not a traitor gun

**Comment by outbools** [comment]
Imagine people mass ordering bombsuits because *someone* spawned too many clowns again and guns begin to appear right in the hallway

**Comment by KingPhilipIII** [comment]
I think this is funny as fuck in theory, but I can see how quickly people would get salty when they instaboom when they pick up some harmless object.

**Comment by alexkar598** [comment]
Can you make it so that if you scan a banana peel it works like a normal one?

**Comment by scrubmcnoob** [comment]
Maybe make examining the item show something is off? There is literally zero counter to this.

**Comment by Ar3nn** [comment]
>making yet another reason for every powergamer to shift-click every item in the room
no thanks, find another way.

**Comment by SirBloodBuske** [comment]
Maybe make it use a battery for the cloak?

**Comment by Ar3nn** [comment]
That sounds a bit better. Maybe make a verb to disable the cloak to conserve charge if a ploy doesn't go off right?

**Comment by Regen1** [comment]
Examine to give it away will give it away and people will just examine everything ever.

What about a middle ground, if you pick up the item it'll glue to your hand and start a timer, when the time's out it'll explode, the only way to get it off is to screwdriver it and cut the correct wire, kind of like with a normal syndicate bomb.

The bomb should be unacidable, as to stop people from just using acid to remove it from their hand.

**Comment by deep-fried-faceplant** [comment]
How about using acid on the bomb to melt the glue off your hand, but the acid does damage to the victim, and a hefty amount of acid is required. The bomb would still be a problem, but at least the victim has a chance of surviving.

Alternatively, the entire arm could be removed.

**Comment by taukausanake** [comment]
:+1: to removing your arm to get rid of a bomb. That sounds hilariously unnecessary and necessary in this context

**Comment by fludd12** [comment]
*JC, it's a bomb! We have to amputate.*

**Comment by Rumiluntti** [comment]
Steal your objective, leave bomb disguised as it. HOOONK
There are so many things that have no counterplay already, I don't think one that punishes greed is a bad thing

**Comment by tigercat2000** [comment]
Following discussion between the Heads of Staff and Maintainers, it was decided to close this PR; the bomb item is not seen as being a thematically appropriate, interesting addition to the clown, in addition to the issues raised above by others regarding its use.

**Comment by PacifistDalek** [comment]
I don't know if I can still comment on this, with the PR being closed, but I want to say that I love a variation of this idea: A sticky bomb, in disguise. Specifically I love the mental image of someone picking up something, and then a blatantly obvious timer starts, which they have to either VERY QUICKLY get it removed through some (modestly complex) process, or, (more easily/simply) they must cut their own limb off. There's something very HONKy about that image, and there's gotta be some varation on this idea that would work with that (like, perhaps a limited list of items, though ones that people are likely to pick up, such as pens or the like). It'd probably need a decently high TC cost too, you wouldn't want it to be a common occurence, or it'd lose it's novelty. But a clever clown that can sneak into their target's office and plant the bomb...Such shenanigans it would create!

**Comment by HugoLuman** [comment]
Waaay late to the party but
Just set the bomb to look like a multitool, you WILL kill the first person that sees it.

**Comment by jughu** [comment]
When you use pizza bombs to justify chameleon bombs but everyone meta pizza boxes anyways

**Pull request closed without merging**
