### PR TITLE
Clothing (jumpsuit) DMI split, unused jumpsuit sprite purge along the way

### PR DESCRIPTION
**Pull request by ElorgRHG**
**Not completely finished yet**
**There's a LOT of repathing**

## What Does This PR Do

Splits the MASSIVE `uniform.dmi` file into smaller, departmental focused DMIs for better organisation and merge conflict reduction.

## Why It's Good For The Game

Its not pleasant to look through the `uniform.dmi`, or hell any of the clothing DMIs to find something, there's no search bar and alphabetical sorting doesn't help, if you don't know about the VSC extension to use a searchbar, its an immense pain to find anything, and is the perfect file to get conflicted too.

## Testing

Split the DMIs.
Went to every departmental clothing vendor.
Spawned human, grey, vox and drask.
Put all clothing that are in the vendors on them.

## Changelog
:cl:
tweak: You now need to wear a jumpsuit to adjust it.
/:cl:

### CODE REVIEW

**Comment by ElorgRHG** [comment]
>Purges everything that was **delted** up until this point

Clearly, I am not an educated professional

**Comment by ElorgRHG** [comment]
Beside MDB2 having a moment...
This PR is done, `uniform.dmi` has been defeated, it was a worthy opponent, all jumpsuits have either been moved to their new appropriate locations or have been purged.

May God, or whatever they believe in, have mercy upon those who will have to review this PR. I wish for your suffering to be over quick.

**Comment by ElorgRHG** [comment]
With the help of code of questionable quality, this... should... be fine to TM again?

Or I will witness the reason for my death, we'll see.

**Comment by SchrodingersWolf** [comment]
So, apparently this might have caused a bug with the 'Roll Down Jumpsuit' verb.

Now, no matter what jumpsuit you wear, trying to use the 'Roll Down Jumpsuit' verb would fail and tell you that 'You cannot roll down this uniform!'. Your sprite will also not update as well.

Since this behaviour is not seen on the testserver, it is likely that this PR, which is being testmerged, is the culprit.

Video of the bug. (I used two different jumpsuits, as well as tried to roll down the jumpsuit with or without a coat)

https://user-images.githubusercontent.com/108938550/193726588-f2683668-5403-44a0-87d1-1e3ed7c56276.mp4

### Credits to GoodApollo#6389 and WingedYordle#3277 on Discord for spotting the issue first.

**Comment by Miraviel** [comment]
QM clothing seems to be bork:

image

**Comment by HMBGERDO** [comment]
Is that the reason why i cant roll down security uniform?

**Comment by ElorgRHG** [comment]
@SchrodingersWolf, @HMBGERDO
>So, apparently this might have caused a bug with the 'Roll Down Jumpsuit' verb.
Is that the reason why i cant roll down security uniform?

It did, and yes. Thanks for the reports, it has been fixed.

@Miraviel
>QM clothing seems to be bork

Fixed

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
