### PR TITLE
cere: Move APCs out of maints.

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
This PR removes all the department APCs from Cere maints and brings them into their respective departments.

I attempted to keep this PR as surgical as possible; moving no other wallbumps, not filling in empty maint tiles with anything else, and not performing massive recabling changes.

The exceptions to this:

- Arrivals had many existing rooms not linked to the local powernet, and whose cabling setup made it difficult to run both local and grid power cables in a sensible way. I made several more adjustments to this area than the rest.
- Science had several local rooms (robotics and quantum pads) not linked to the local powernet. I moved these over.

Any APCs still in maints should only be maints APCs.

<details>

<summary>APCs Moved</summary>

### Security Asteroid
- Courtroom
- Magi
- IAA
- Locker Room
- Arcade
- Cryo Secondary
- HOP
- Bridge
- Fore North Hall
- Fore West Hall
- Security Lobby

### Service Asteroid
- Fitness Room
- Port North Hall
- Port East Hall
- Port South Hall
- Bar
- Kitchen
- Botany
- Library
- Chapel
- Theatre

### Science Asteroid
- Research Director
- Xenobiology
- Research Testing Chamber
- Research Testing Lab
- Aft West Hall
- Aft East Hall
- Research and Development

### Supply
- Aux Tool Storage
- Break Room
- Mining Dock
- Quartermaster
- Warehouse
- Cargo Bay
- Waste Disposal
- Delivery Office

### Medbay
- Medbay
- Break Room
- Genetics Lab
- Chemistry
- Paramedic
- Fore East Hall
- Starboard South Hall (remapped to local powernet)
- Morgue
- Virology

### Engineering

- Garden
- Central Primary Hall North
- Atmospherics Distribution Loop

### Arrivals
- Teleporter
- Security Checkpoint
- Departures
- Arrival Shuttle Hall North (remapped to local powernet)
- Arrival Shuttle Hall South (remapped to local powernet)
- Docking Quantum Pad (remapped to local powernet)

</details>

## Why It's Good For The Game
This is one of the longstanding complaints about Farragus. While maint APCs are a funny little personality quirk for the map, they have problems that interfere with balance and playability: they provide a massive advantage to biohazards by allowing them to rapidly take power out, they make it easier for malf AIs to hack more APCs because they're out of the way and less noticeable, they turn pulse demon into easy mode, and because they must be in the same `/area` as their department, there are tiles through maintenance that are subject to radstorms and unsafe. It's not worth keeping this quirk around.

## Images of changes

All before/after images are the same dimensions, so you can flip between them on different browser tabs.

See MDB for complete diff.

<details>

<summary>Arrivals</summary>

### Before

arrivals_before

### After

arrivals_after

</details>

<details>

<summary>Cargo</summary>

### Before

cargo_before

### After

cargo_after

</details>

<details>

<summary>Command</summary>

### Before

command_before

### After

command_after

</details>

<details>

<summary>Engineering</summary>

### Before

engi_before

### After

engi_after

</details>

<details>

<summary>Medbay</summary>

### Before

medbay_before

### After

medbay_after

</details>

<details>

<summary>Medbay Hall</summary>

### Before

medhall_before

### After

medhall_after

</details>

<details>

<summary>Science</summary>

### Before

science_before

### After

science_after

</details>

<details>

<summary>Security</summary>

### Before

sec_before

### After

sec_after

</details>

<details>

<summary>Service Top</summary>

### Before

service_top_before

### After

service_top_after

</details>

<details>

<summary>Service Bottom</summary>

### Before

service_bottom_before

### After

service_bottom_after

</details>

## Testing
- Visual inspection, maplint, and in-game map unit tests.
- Killed all power across station, repowered SMES and APCs, ensured that power reached all departments as expected.
<hr>

### Declaration
- [X] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/feature_freeze/CODE_OF_CONDUCT.md#currently-changes-to-the-following-types-of-content-reuires-pre-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

## Changelog
:cl:
add: Farragus: Department APCs have been moved out of maints, and into their departments.
/:cl:

### CODE REVIEW

**Comment by DGamerL** [comment]
Service
image
Science
image
Cargo
image
Left of AI sat
image

Maintenance APCs seem random wether they're in the substation room or in the maintenance shafts themselves

Is this AI room APC intended to be still in this maintenance bit?
image

LGTM otherwise

**Comment by warriorstar-orion** [comment]
> Service image Science image Cargo image Left of AI sat image
> 
> Maintenance APCs seem random wether they're in the substation room or in the maintenance shafts themselves
> 
> Is this AI room APC intended to be still in this maintenance bit? image
> 
> LGTM otherwise

Good calls, I actually hadn't thought about either of these. I've moved all the maints APCs inside the substations, if it sucks, we can move them back out, but I think that's an interesting configuration. The AI sat's APC has been moved out of its maints area too.

**Comment by warriorstar-orion** [comment]
Whoops, forgot the cargo/med substation is contiguous with two separate maints areas. I've moved the fore-starboard APC back into the maint tunnels for now, but every substation that can serve an APC now has one.

**Review by Burzah — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]
LGTM - great work!

**Pull request merged**
