### PR TITLE
Adds cryo pods to Perma

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Reshuffles some objects around to make them fit.
img

This is so Perma prisoners would be able to free up their job slots when they no longer want to play instead of committing suicide or going SSD, which not only keep job slots locked up, but also become an inconvenience for anyone who cares about keeping corpses / SSDs out of perma.

🆑 FreeStylaLT
add: Added Cryo pods to perma.
/ 🆑

### CODE REVIEW

**Comment by Taaketa** [comment]
Stupid question. Not really in this PR can someone choose to spawn in as a permanent prisoner?

**Comment by FreeStylaLT** [comment]
That's not an option right now, and unlikely to be one anytime soon (without another dedicated PR that changes Perma probably)

**Comment by Citinited** [comment]
It probably needs a cryo console to see who has cryoed and to recover any special items (unlikely I know, but it could happen)

**Comment by Quantum-M** [comment]
I think you should make it so it can also notify security radio when a prisoner fully cryo, to avoid security jumping the gun when they think the cryod prisoner escaped.

**Comment by datlo** [comment]
Yes, please. Perma prisoners should be able to remove themselves cleanly from the round just like regular crew can.

**Comment by Kyep** [comment]
Thank you for doing this.
Perma prisoners cryoing, rather than suiciding/ghosting, should result in a few additional job slots during highpop, which will be helpful.

**Comment by Birdtalon** [comment]
😱

**Comment by KasparoVy** [comment]
If only you could remove yourself cleanly with a craftable ceiling necklace

**Pull request closed without merging**
