### PR TITLE
Add combat syringe gun to syndicate medical borgs

### PR DESCRIPTION
**Pull request by datlo**
Buff bioterror syringes and add the combat cyborg syringe gun to medical syndiborgs.

List of changes : 

- Bioterror syringes now holds 5u of neurotoxin2 (the poison) instead of neurotoxin (the drink). This makes the syringes confuse and disorient the target and still be just as effective as a sleeping agent.
- Syndi medborgs now have a cyborg version of the syringe gun. Comes preloaded with 12 bioterror syringes, and reloads one syringe per minute passively. Can be reloaded faster by recharging at a station.

combatsyringe-b

🆑
tweak: Nuke ops bioterror syringes will now confuse the target on top of its muting and knocking out effects.
add: Syndicate medborgs now get a cyborg version of the combat syringe gun, firing bioterror syringes. Passively reload at a very slow rate.
/🆑

### CODE REVIEW

**Comment by Pennwick** [comment]
Not sure I agree with the cyborg getting a free syringe gun. A medical cyborg should stick with its team so it doesn't really need self defense options. And if one wandered away from its group then someone who encounters it should feel safer, as long as they stay out of the range of its energy saw. At the very least, adding a ranged weapon to the medical borg should increase its cost.

**Comment by datlo** [comment]
As far as I know the medical borg is currently considered underpowered for its cost compared to the assault borg, hence the buff. I am definitely not increasing its cost higher than the other borgs.

**Comment by datlo** [comment]
pinky swear to myself i'll get around to finishing this PR tomorrow or the day after

**Comment by datlo** [comment]
I decided to remove the syndicate combat syringe gun and make this PR only about the cyborg version.

I might get around to doing the combat syringe gun, but it needs much more code than I expected to work as you'd expect it to, so, not for now.

This PR is ready for review/merge

**Comment by Fox-McCloud** [comment]
I'd much rather see the syndicate borg pushed more firmly in the direction of a hard-support role, than a mixed one.

Ie: giving it the medigun, for instance, would accomplish this.

Syndicate mediborg isn't particularly strong; giving it something like the medigun would definitely push it towards the hard-support role.

**Comment by datlo** [comment]
that makes sense tbh

i'll close this for now and give it more thinking

**Pull request closed without merging**
