### PR TITLE
Vox-fitted Back Stuff, Adds Genetic Duffel, Fixing Typos and Refactoring Back-Icon Generation

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
rscadd: Geneticist duffelbag on-mob sprite (for all species).
rscadd: Vox-fitted backpacks, satchels, ERT backpacks, duffelbags and defib unit.
tweak: Refactors back-item icon generation.
fix: Typo in the description of Santa's sack.
fix: Missing punctuation and gender macros in the description of the bag of holding.
fix: The tweak to back-icon generation fixes a bug where the wrong sprite name was being used to generate back-item icons.
/:cl:

**Adds:**
- Geneticist duffelbag on-mob sprite.
- Vox-fitted backpacks, all varieties (incl. bag of holding and Santa's sack).
- Vox-fitted satchels (all of them).
- Vox-fitted ERT backpacks (all of them).
- Vox-fitted defibrillator unit.
- Vox-fitted duffelbags (all of them).

**Tweaks:**
- Refactors back-item icon generation to work like just about all of the other icon generation procs.

**Fixes:**
- Typo in the description of Santa's sack.
- Missing punctuation and gender macros in the description of the bag of holding.
- The tweak to back-icon generation fixes a bug where the wrong sprite name was being used to generate back-item icons.

Using species_fit and sprite_sheets now works properly for items that go on the back. Previously it was using the item_state name if it existed in order to generate the on-mob icon, which was wrong. I restructured it to work the same way as the rest of the icon generation procs, so species_fit and sprite_sheets now works the exact same with back items as it does with uniforms and such.

**_Before_**
voxpacksbefore

**_After - Backpacks/Satchels_**
voxpacksafter

**_After - Duffelbags_**
voxduffelsafter

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Are you surge changing the way it's handled was necessary? Did it work the other way? This seems like (though I could be wrong), it would increase the load of things as you're generating more icons.

Being nitpicky, I know, but I'm more curious than anything else.

**Comment by KasparoVy** [comment]
It worked in very certain circumstances the other way-- via a method which (I believe) was unintended and did not agree with the majority of back-worn items, but I'll be testing most of them when I get back on this today

What happened was that, if there was an item_state, it used that value to look for the icon_state icon-- which meant if you had an item_state ad all it would have to be the same as the icon_state in order for the on-mob icon to work, and if the in_hands icons didn't share the name, they simply wouldn't appear. But if you left it as-is, in a case like santa's sack-- where the icon_state is giftbag0 and the item_state is giftbag, when I species_fit and sprite_sheets'd it, what happened was I had the in-hands icon, I had the icon in the back slot and hand slot and such when it was supposed to be there-- but when I equipped the item, the on-mob sprite was invisible as because item_state existed, it was trying to use that as the icon_state-- but beause they were different (by a single character) it didn't work. But when I changed the item_state (via varedit) to giftbag0 and updated my player's icons, the giftbag appeared on my back with the intended sprite, but the in-hands icon no longer worked.

This might add the tiniest amount of load at most with icon generation as, realistically, it is only generating one additional image (the other one of which only if icon_override exists, which is pretty rare) but it cuts out the weird decision structure that used the item_state as the icon_state (thus breaking just about every back-worn item that uses a species_fit) in the manner described above

**Comment by KasparoVy** [comment]
Pics are up

**Comment by KasparoVy** [comment]
I.. Guess I'll start looking where that conflict is. This didn't conflict with anything until some time today.

**Comment by KasparoVy** [comment]
I accommodated 3601's changes to /icons/storage.dm with that last commit. I'll keep looking to see if there's anything else, but I'm pretty sure that was it.

**Comment by Fox-McCloud** [comment]
your github client should tell you what is in conflict.

**Comment by KasparoVy** [comment]
Aha, there it is. The client didn't show the conflict, but I rooted through all the PRs until I found what it was. Commit incoming

**Comment by KasparoVy** [comment]
Closing and re-opening in another pull.

**Pull request closed without merging**
