### PR TITLE
Thanksgiving Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just some Thanksgiving themed changed. All new sprites courtesy of @FullOfSkittles; Thank you so much!

- Adds in turkey mob
 - Can order them from cargo. Gobble?
- Adds in actual turkey recipe for the chef
 - No more icky Tofurkey (gross)
 - Mades with stuffing and regular meat (it's magic...don't question it)
- Adds in Mashed Potatoes 
 - made with a potato and gravy
 - Remember, gravy is already a recipe
- Adds Porktonium to Sausages
- Adds in some fall effects/decals/structures
 - Corn Stalk Bunches
 - straw residue
 - leaves
 - straw bails (climbable!)

Map Changes
 - Makes the bar more Thanksgiving/Fall oriented
 - Chef will start out with one turkey (this is only for the holidays)

Fixes
 - Fixes a missing window in the back of the animal pen
 - Removes a duplicate hot dog sprite (hot dog will now match what's on the wiki)

Map Pic:

map

### CODE REVIEW

**Comment by Dumbdumn5** [comment]
Murica'

**Comment by Fox-McCloud** [comment]
:us:

**Comment by Taaketa** [comment]
Allow the bar to have Festivus as the bar sign?

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by ZomgPonies** [comment]
Yeah this looks great :+1:

**Comment by orelbon** [comment]
:+1:  :bird:

**Comment by taukausanake** [comment]
Can we get autumn leaves instead of grass patches? That might require more edits than needed though for reasons (edit the plant seed color) but I think it would look nice to have leafy grass

**Comment by Tastyfish** [comment]
:tractor: :fallen_leaf:

**Pull request merged**
