### PR TITLE
Farragus: Remaps Service Asteroid and Locker Room Area

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
This PR remaps the Farragus Service Asteroid and part of the security asteroid (due to the movement of the bridge, and because it currently contains the locker room and arcade). The features are as follows:

### Rearranged Layout:
Unimportant infrastructure like the barber shop has been moved away from prime real estate in the centre of the asteroid, allowing for locations like the bar and chapel to feature more prominently. The quantum pad station has been moved out of the dusty corner it was hiding in and placed in amongst the middle for easy access to all the prime locations.

The space bridge between security and service has been relocated to help break up the long straight hallway (which has had a minor effect on security, the detective's office is now properly in the security plaza area.

The movement of the kitchen and chapel has allowed for the creation of a large plaza area in the middle of the service asteroid, affording a large public space for people to relax and hang out in, with easy access to the kitchen and some small green spaces. A similar space has been created at the north of the asteroid, which now features a swimming pool.

A few extra doors have been added to make the area more porous and provide more paths to navigate through, improving ~~options for running away from security~~ ease of travel.

### Kitchen & Bar Remodel:
The bar's backrooms now face maintenance, allowing the addition of windows and an entrance that faces the main hallway. This substantially improves the visibility of the bar and makes it much easier to find, especially for new players unfamiliar with the layout - it can be seen almost as soon as you walk out of the quantum pad station.

Due to the rearrangement of the bar, the Kitchen's area has been cut down, as a large portion of it existed purely because of the bar's placement of the private room.

### Expanded, Upgraded Chapel:
The chapel has been expanded substantially, with double the seating and plenty of room for chaplains to set up their space. A funeral parlour complete with a mass driver has been added so you can finally offer more than just cremation to the dignified dead.

There is now a MULE delivery point leading to the chaplain's office for easy receipt of ordered crates.

### Relocation of Fitness and Arcade
The arcade has been pulled from the command asteroid and placed into the service asteroid. The fitness room has been put in its place, reduced in size. As a part of this, the nearby bathrooms have been upgraded with showers (for the gym goers to wash with once they have finished a hard day's workout), and the locker room cryodorm was reshaped.

### Improved Maintenance
Maintenance is now more interconnected with the other parts of the station, with a transit tube connecting to security, and a mini space bridge joining onto the engineering asteroid. More space-facing windows gives more points to move between space and station. The escape pod is now harder to miss thanks to receiving a more obvious launch point. The Super Secret Clown HQ Secret Passage now also has a second exit into maintenance, for even more mischief and improved connectivity. More clutter and things to find have been added to liven up the tunnels.

### New Solar Array:
Replacing the now-lost Medical solars as the 4th array of the station, this allows the service asteroid to receive power independently of the main engine or turbine, as the other non-engineering departmental asteroids can.

### Ever So Slightly Less Complex Disposals Loop:
The Disposals Loop has been slightly simplified in the area that it was the most complex, merging the bottom of the S bend Plus Junction on the security asteroid into a simple T junction.

### Other:
More extinguishers have been added, some intercoms have been added. The Botany Condimaster is replaced by a Chemmaster in line with other stations, and they have received a second seed vendor. Adds nitrogen atmos wood flooring and carpet.

## Why It's Good For The Game
The asteroid is now easier to navigate, both in the main areas and in maintenance. The long hallway has been broken up by the addition of the plaza area outside the chapel, which along with the remodelling of the bar makes the area more visually appealing. All the service jobs and any visitors benefit from the new arrangements in various ways.

## Images of changes
Bar area
image
Kitchen and botany
image
Central plaza area
image
Chapel
image
Library
image
Upper plaza and Recreation Area
image
Solar and escape pod maintenance
image
Library Maintenance
image
Gambling den and engineering bridge
image
Lower Service Maintenance
image
Atmos checkpoint
image
Lower security and space bridge
image
Locker Room area
image

## Testing

- [x] Verified full AI camera coverage in appropriate areas.
- [x] Verified good lighting outside of maintenance.
- [x] Ensured the cold ancient rock still covers the entire perimeter of the minable portions of the asteroid.
<hr>

### Declaration
- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/feature_freeze/CODE_OF_CONDUCT.md#currently-changes-to-the-following-types-of-content-reuires-pre-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
image

<hr>

## Changelog
:cl:
tweak: Farragus' Service Asteroid has been remapped.
add: Solar Array added to Service.
add: Mass driver and associated room added to chapel.
/:cl:

### CODE REVIEW

**Review by S34NW — COMMENTED** [review]
Few points:

Crematorium placement seems too far away from everything in my opinion. Cere is already enormous so we should be trying to shorten the path to it for cling handling, it could also use a direct alternate entry such as from maints due to the room's functional importance.

Library could be reworked in my opinion, the front desk is not readily at the entry points despite being a front desk that should be right there as you walk in.

Avoid placing hallway doors like the left ones here that trap pockets of air with no vent/scrubber. (I'd remove the left door set)
delwedd

There's no vent in this room
delwedd

**Comment by Fordoxia** [comment]
> Few points:
> _snip_

Crematorium has been moved closer to the entrance of the chapel, much easier to access now.

Library layout has been flipped so the desk is by the door.

Doors in the tiny hallway have been removed.

The vents in the theatre/restaurant have been pulled out from under the furniture and are now visible.

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
This area needs more light

2024_08_19__07_31_10__Paradise Station 13

Would clear up standing counter space to put the trash can over in this alcove

2024_08_19__07_27_55__paradise dme  cerestation dmm  - StrongDMM

Lightswitch under window

2024_08_19__07_26_36__paradise dme  cerestation dmm  - StrongDMM

Floating camera

2024_08_19__07_24_00__paradise dme  cerestation dmm  - StrongDMM

No hallway light switches

2024_08_19__07_24_55__paradise dme  cerestation dmm  - StrongDMM

The camera coverage here seems poor, four shouldn't be necessary here

2024_08_19__07_25_08__Paradise Station 13

Hanging wall bumps

2024_08_19__07_13_45__paradise dme  cerestation dmm  - StrongDMM

These two switches are too close together. I typically make their offsets +/-5

2024_08_19__07_36_17__paradise dme  cerestation dmm  - StrongDMM

/area/station/hallway/primary/port/north has 9 fire alarms, which is too many. I'm not sure why there are fire alarms on both sides of these airlocks. If the intention is to make it so that people on either side of the airlock can toggle the airlocks, we don't do that, and the north pair are in separate areas so they aren't synced.

2024_08_19__07_38_11__paradise dme  cerestation dmm  - StrongDMM

2024_08_19__07_49_55__paradise dme  cerestation dmm  - StrongDMM

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
Whatever you're using to map edit is leaving empty pixel nudges in:

2024_08_19__08_01_38__Search_ pixel _ = 0 - Paradise - Visual Studio Code

If you're using SDMM, make sure that "Sanitize Variables" is checked in the Editor preferences. If you do that and then save the map, these should be automatically elided.

**Comment by Fordoxia** [comment]
Changes applied.

**Comment by warriorstar-orion** [comment]
The other telepads only use the floor lights for illumination, if that's not sufficient lighting we should adjust them all at once

2024_08_20__13_18_47__paradise dme  cerestation dmm  - StrongDMM

Light on airlock

2024_08_20__13_17_44__paradise dme  cerestation dmm  - StrongDMM

Remaining hallway lightswitch

2024_08_20__13_12_14__paradise dme  cerestation dmm  - StrongDMM

Floor bumps are awkwardly clustered here

2024_08_20__13_29_33__paradise dme  cerestation dmm  - StrongDMM

Lots of issues with floor tile decals either out of place, or facing the wrong direction

2024_08_20__13_30_42__paradise dme  cerestation dmm  - StrongDMM
2024_08_20__13_30_48__paradise dme  cerestation dmm  - StrongDMM
2024_08_20__13_30_55__paradise dme  cerestation dmm  - StrongDMM
2024_08_20__13_31_00__paradise dme  cerestation dmm  - StrongDMM
2024_08_20__13_31_05__paradise dme  cerestation dmm  - StrongDMM

Maintenance bar area boundary extends beyond the bar itself

2024_08_20__13_42_29__paradise dme  cerestation dmm  - StrongDMM

A lot of mapped intercoms are using a "custom placement" instead of one of the directional bumps



Library has a maintenance area tile on it, and the single unexplored maints tile below that should be changed to port maints

2024_08_20__13_44_46__paradise dme  cerestation dmm  - StrongDMM

Space tile

2024_08_20__13_45_51__paradise dme  cerestation dmm  - StrongDMM

Cable node overlapping other cable

2024_08_20__13_46_17__paradise dme  cerestation dmm  - StrongDMM

Double walling here, either move the chute and its walls up and to the left one tile, or resize the adjacent rooms to use the chute's walls as their walls

2024_08_20__13_46_26__paradise dme  cerestation dmm  - StrongDMM

Chap polarized door missing ID



Neither the name or cell type of this APC should be varedited



Is this meant to be a sort junction?

2024_08_20__13_52_03__paradise dme  cerestation dmm  - StrongDMM

Please verify package routing for the bar

image

**Comment by Fordoxia** [comment]
All raised issues addressed.

**Comment by warriorstar-orion** [comment]
@Fordoxia are you planning on retrofitting maints in another pass? Right now they're very barren and have poor signposting, there's nothing structural or decorative to distinguish them from other parts of maints. 

2024_08_23__15_55_16__paradise dme  cerestation dmm  - StrongDMM
2024_08_23__15_55_23__paradise dme  cerestation dmm  - StrongDMM
2024_08_23__15_55_30__paradise dme  cerestation dmm  - StrongDMM

**Comment by Fordoxia** [comment]
> @Fordoxia are you planning on retrofitting maints in another pass? Right now they're very barren and have poor signposting

Yes, I mainly wanted to ensure that the main rooms were all in concrete locations before adding proper dressing to all of maint.

**Review by warriorstar-orion — APPROVED** [review]
LGTM

**Review by Burzah — APPROVED** [review]

**Pull request merged**
