### PR TITLE
Smartfridges Accept IV Bags

### PR DESCRIPTION
**Pull request by Dave-TH**
This PR allows medbay smartfridges to accept IV bags. Chemists, put your favorite blend in an IV bag and let doctors ab(?)use it.
:cl:
add: Medical smartfridges now accept IV bags.
/:cl:

### CODE REVIEW

**Comment by Jazz23** [comment]
I mean you can put a beaker on an IV drip and use that, but this gives empty IV bags a more directly applicable use so I like this pr.

**Comment by davidchan13** [comment]
Unless it was hotfixed in the last day or so, IV drips don't accept beakers or other containers since the new IV bags were implemented, and you can't change the transfer rate anymore either.

**Comment by Dave-TH** [comment]
IV bags actually can adjust transfer rate. RMB > Set Transfer Rate just like any other reagent container!
David is right that beakers have not fit on IV stands since the update, though.

**Comment by davidchan13** [comment]
Oh they moved the transfer rate from the drip to the bags? That's... interesting.

**Comment by Dave-TH** [comment]
All of the processing is handled on the bags.

**Comment by Fox-McCloud** [comment]
IV bags function like the old IV drips.

IV Drips are just a holder item for the convenience of holding the bags, that's it, really.

**Comment by Mitchs98** [comment]
Is it unintentional that the drips no longer allow beakers or buckets? If so that's...incredibly annoying and I don't see why it was changed. If not, I'll look into trying to fix it. Because well...that shouldn't of been changed at all.

**Comment by taukausanake** [comment]
I don't think it matters that they can't hold other containers. You can fill the IVs with anything now, can't you? I feel it would be better to have it drip from the bag rather than a beaker. I rather it be like this

**Comment by Mitchs98** [comment]
Yeah I spoke to Dave. I mean, I guess it makes sense. Though it'll impact synthflesh and stuff a bit, not that much.

**Pull request merged**
