### PR TITLE
Removes fluffy cuffs

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This PR removes the fluffy cuffs. They have __way__ too obvious sexual connotations and are not aligned with the spirit of the rules against ERP/Sexual content. We have made several good strides with the removal of the ballgag & assless chaps. The fluffy cuffs serve the exact same functionality as regular handcuffs - meaning that there is no reason to keep them in game other than for nostalgic purposes. An argument which I believe to not be strong enough to outweigh the necessity to put forward a consistent stance on sexual content. There are other servers which can offer this kind of experience; and Paradise should be explicit in the fact that lewd roleplay should not be encouraged. Considering there are people that are as young as **ELEVEN** who play this game (And thats only as far as I know), stuff like this shouldn't be in here. Period.

**Images of sprite/map changes:**
Before: 
image

After:
image

**Changelog:**
:cl:
del: Removed pink fluffy handcuffs.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Requesting controversial tag

**Comment by TDSSS** [comment]
There is a freeze on mapping PRs until #11099  gets merged, nerd. :P

**Comment by AffectedArc07** [comment]
My own PR blocked by my own PR. How ironic

**Comment by Couls** [comment]
Improve don't remove, maybe we can make realistic fluff details?

**Comment by AffectedArc07** [comment]
@Couls [Yeah sure do it here](https://github.com/Citadel-Station-13/Citadel-Station-13)

**Comment by Birdtalon** [comment]
>Improve don't remove

Handcuffs 
Here you go

**Comment by Mitchs98** [comment]
Absolutely no reason to remove them. Many things in SS13 have very obvious and lewd and/or inappropriate meanings/purposes/uses/lines/sound effects/references. Assless chaps and the ball gag? Yeah I agree with that. The cuffs? Absolutely not. Name one good reason these should be removed but the five billion other things in the server won't ever be considered to be removed.

**Comment by AffectedArc07** [comment]
@Mitchs98 name one good reason to keep these in this game

**Comment by Mitchs98** [comment]
@affectedarc07 Comical value and a decently funny easter egg. Sure everyone mostly knows where they are, but that changes nothing. I'm super sick of people changing things 'just cause' or because it MIGHT be a good thing to do. Or the fact of 'why do we really need it anyway?'

**Comment by Mitchs98** [comment]
You also didn't answer my question. You in-fact avoided it. You don't answer a question with a question, not in this context.

**Comment by AffectedArc07** [comment]
I wanted you to give a reason of why to keep them. I named many reasons in the my PR opening post.

**Comment by Mitchs98** [comment]
You didn't name any reasons based on the context of my comment, at all. They are very much as aligned with the spirit of the rules as everything else I mentioned was.

**Comment by Birdtalon** [comment]
>They are very much as aligned with the spirit of the rules as everything else I mentioned was.

@Mitchs98 the only specific items you named were removed for the very reason these should be. AA07 stated in his OP why he wants them removed.

**Comment by Mitchs98** [comment]
Naming specific items would.

1. Take too long.

And 2. Possibly have some unneeded PR up to remove them as well. 

I agree on some things being 'unsuitable for children' to a degree, but still. As I said. There's far too many references and items in game already. If you're so hinged on removing things that could be considered 'lewd' or 'inappropriate', and thereby removing some of the charm this game has, based on some moral principals of making the world a bit more child friendly you should take a look at the game on a whole.

**Comment by Shadeykins** [comment]
> 
> 
> Naming specific items would.
> 
>     1. Take too long.
> 
> 
> And 2. Possibly have some unneeded PR up to remove them as well.
> 
> I agree on some things being 'unsuitable for children' to a degree, but still. As I said. There's far too many references and items in game already. If you're so hinged on removing things that could be considered 'lewd' or 'inappropriate', and thereby removing some of the charm this game has, based on some moral principals of making the world a bit more child friendly you should take a look at the game on a whole.

Which items are in and are sexually inappropriate? I am sure Affected can expand the PR to remove those as well.

**Comment by Dinarzad** [comment]
Not that I care one way or another if the fluffy cuffs are removed.
But.
I mean if this is being done in the name of 'child safety' given we're citing a player as young as 11 years old.

I'm just gonna point out that SS13 is a game where people literally explode into bloody gibs and gore, where you can hear the crack of breaking bones as someone beats you to to death via a crowbar, where you can throw acid onto someone's face as melt said face off, and such on and such forth.  All highly pixelated, but it's all there.

SS13 is not a kid friendly game. It never has been.  To say this should be removed to 'protect the youngins' well.... I... think they have bigger problems then a pair of fluffy handcuffs that I don't even think the sexual connotations of it are fully understood if at all, by someone that young.

Just sort of putting that out there.

**Comment by AffectedArc07** [comment]
This isnt cited as child protection, just stating it for extra reason. The real reason is this has no place in Paracode, hell it has less of a pace than the ballgag. That thing had legit uses, like shutting people up. This however does the exact same thing as normal cuffs, so it really doesnt need to exist, especially given the nature of our rules.

**Comment by Birdtalon** [comment]
>If you're so hinged on removing things that could be considered 'lewd' or 'inappropriate', and thereby removing some of the charm this game has, based on some moral principals of making the world a bit more child friendly you should take a look at the game on a whole.

It's nothing to do with children really. Lewd content is not necessary to enjoy the game. The rules of Paradise dictate that sexual content is not allowed. It's quite frankly tasteless and a slippery slope that people use to justify pushing the boundaries.

Servers exist which allow all kinds of sexual themes, games exist with sexual themes, porn exists. This server doesn't need it because sexual themes are prohibited.

**Comment by Spacemanspark** [comment]
...While we're at it, can we finally remove the ability to clip collars onto jumpsuits?
_meant to do it years ago but never got around to it_

**Comment by Rurik123** [comment]
> This PR removes the fluffy cuffs. They have **way** too obvious sexual connotations and are not aligned with the spirit of the rules against ERP/Sexual content.

It's a pair of handcuffs. That is pink. The only thing even vaguely suggestive is the description, which leaves it no more suggestive than a slimes *squish, or the sexy mime/clown outfit. Though that isn't fair to the pink handcuffs, when the sexy mime/clown outfit literally has the word sexy in the name.

Furthermore, I've never seen fluffy pink handcuffs used in a blatant lewd way. Usually only as _"Hey look the super dangerous murderer that killed a dozen people is in girly pink handcuffs! Isn't that funny?"_ Which, all in all, doesn't sound very lewd/sexual to me. 

I suppose this prevents characters that are married in-game from using the fluffy pink handcuffs on one another, so uh, yay I guess? Guess they'll just use regular cuffs with their pet collars and cat ears and continue on as normal. 

Honestly having a hard time seeing this as an issue, or someone else thinking "Them fluffy pink handcuffs are causing problems and this entire server would be better off without it, lets get rid of em!"

**Comment by MRgaty** [comment]
I don't think removing them will make any difference to be fair.

**Comment by Shadeykins** [comment]
> 
> 
> > This PR removes the fluffy cuffs. They have **way** too obvious sexual connotations and are not aligned with the spirit of the rules against ERP/Sexual content.
> 
> It's a pair of handcuffs. That is pink. The only thing even vaguely suggestive is the description, which leaves it no more suggestive than a slimes *squish, or the sexy mime/clown outfit. Though that isn't fair to the pink handcuffs, when the sexy mime/clown outfit literally has the word sexy in the name.
> 
> Furthermore, I've never seen fluffy pink handcuffs used in a blatant lewd way. Usually only as _"Hey look the super dangerous murderer that killed a dozen people is in girly pink handcuffs! Isn't that funny?"_ Which, all in all, doesn't sound very lewd/sexual to me.
> 
> I suppose this prevents characters that are married in-game from using the fluffy pink handcuffs on one another, so uh, yay I guess? Guess they'll just use regular cuffs with their pet collars and cat ears and continue on as normal.
> 
> Honestly having a hard time seeing this as an issue, or someone else thinking "Them fluffy pink handcuffs are causing problems and this entire server would be better off without it, lets get rid of em!"

Oh, pet collars. Forgot about those.

Both the pink handcuffs and wearable pet collars on humans are directly part of BDSM culture. I think the main issue here (personally) isn't that people are getting excitable over fluffy cuffs, but that they present a mechanical catch-22 where their existence undermines the rules as they exist.

**It's an object that directly invites/alludes to a certain kind of behaviour that can get you banned.**

Also I'm not sure we should confuse anime garbo (nya nya uguu) with literal sexual props. Kemonomimimimimi (???) is an entire enterprise that is not in and of itself a sexual one.

**Comment by taukausanake** [comment]
> they present a mechanical catch-22 where their existence undermines the rules

Have they been used in such a way that they undermine or outright break the rules? Cuffs and collars? If they haven't then that argument is invalid. You can argue that normal cuffs can be used for the same thing despite their intended use for retaining criminals. They haven't been used in such a way and haven't broken the rules. You're arguing something's existence breaks the rules and not the way it is used. Telescience existence doesn't break the rules but the way it has been used has been argument to remove it. Rules don't pertain to objects but the players that use them. If multiple players have abused an object, like Telescience, then you can argue that it needs to be removed. I haven't heard of anyone abusing or even using fuzzy cuffs

**Comment by Shadeykins** [comment]
> Have they been used in such a way that they undermine or outright break the rules? Cuffs and collars? If they haven't then that argument is invalid.

I would not be remarking on them being banbait if people didn't get banned for creepy things when using them.

**Comment by Couls** [comment]
May as well remove pet collars attached on jumpsuits while you're at it

**Comment by Birdtalon** [comment]
>Rules don't pertain to objects but the players that use them.

So if a massive dildo was in the code it would be okay because rules don't pertain to objects?

**Comment by taukausanake** [comment]
[Dildos?](https://github.com/ParadiseSS13/Paradise/pull/3333) I'd argue that, yes. But I also enjoy all the awful things in life because of how fucking retarded they make everyone. Case in point: this PR and everyone for and against it

**Comment by MRgaty** [comment]
I think we should also remove the "sexy outfits" from the wardrobes.

**Comment by Mitchs98** [comment]
Why do we need to remove the 'sexy' outfits? We have no reason to remove them just as we have no reason to remove thrse cuffs. People 'might' do lewd/bad things with practically everything in game, doesn't mean they do.

This is honestly ridiculous.

**Comment by AffectedArc07** [comment]
The sexy outfits dont have reason to be removed, as they arent even overtly sexual

**Comment by Mitchs98** [comment]
Neither are a pair of pink handcuffs.

**Comment by Spacemanspark** [comment]
An outfit that isn't intentionally made for fetishes is rather different than a pair of handcuffs specifically designed to encourage BDSM fetishes.

**Comment by Couls** [comment]
Visually appealing outfit

**Comment by Xantholne** [comment]
Weren't these handcuffs someone's fluff item? I remember that being mentioned around the time the ball gag was removed.

**Comment by AffectedArc07** [comment]
@Xantholne the assless chaps were, not sure about the cuffs though

**Comment by Corocan** [comment]
> 
> 
> An outfit that isn't intentionally made for fetishes is rather different than a pair of handcuffs specifically designed to encourage BDSM fetishes.
> 
Pretty sure that 'sexy maid' falls into a fetish. And were the fluffy pink cuffs put in the game to encourage BDSM fetishes?

**Pull request closed without merging**
