### PR TITLE
Moves bo-staff out from under claymore

### PR DESCRIPTION
**Pull request by Ar3nn**
This parenting, as explained in the removed comment, was done to inherit `IsShield` from claymore, and then `edge` and `sharp` were set to `0`, but then `IsShield` has its value changed on the bo-staff, making this parenting entirely pointless, since you are now overriding everything you get from claymore.

:cl: Ar3nn
tweak: Moves bo-staff back directly under null-rod, as opposed to under claymore.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This is a non-issue and it's going to conflict with the hit_reaction PR.

No.

**Comment by Ar3nn** [comment]
I guess it doesn't really matter either way, but it does look a little confusing to child it and then override everything it gets from the parent. Also, if you want me to wait until after hit_reaction, sure, I have no problem with that.

**Comment by Ar3nn** [comment]
Everything else it gets from claymore is inherited from nullrod, innit?

**Comment by TheDZD** [comment]
There is really no point to this. Also you shouldn't have merge commits before your PR is even up.

**Pull request closed without merging**
