### PR TITLE
Makes cans crushable by humans and janiborgs

### PR DESCRIPTION
**Pull request by Tastyfish**
Oddly, we already had the crush can item and its sprites.
- Humans can now crush cans by attacking themselves in the **head** with the can in **harm** intent.
- Janiborgs can now crush cans when they pick them up with their trashbag.

:cl:
rscadd:Humans can now crush cans by attacking themselves in the head with the can in harm intent.
rscadd:Janiborgs can now crush cans when they pick them up with their trashbag.
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
Pick up that can.

**Comment by Spacemanspark** [comment]
Crush a can for Jay Owen.

**Comment by TheDZD** [comment]
Also I have no idea how I misclicked that badly, wow.

**Comment by Spacemanspark** [comment]
It was quite clearly a bug in the fact that we could not do this before.

**Comment by Vivalas** [comment]
>Humans can now crush cans by attacking themselves in the head with the can in harm intent.

For whatever reason this made me laugh too much.

**Pull request merged**
