### PR TITLE
updates medals from TG

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Ports tgs newer medal sprites

## Why It's Good For The Game

I want shiny medals. More modern sprites are good.

## Images of changes

image

## Testing

see above, confirmed they looked like that

## Changelog
:cl:
imageadd: Add new medal icons from tg
imagedel: Deleted old medal icons

/:cl:

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]
Looks Good To M-what is that branch name?!

**Review by DGamerL — APPROVED** [review]
Bender B Rodriguez was here!

**Review by Contrabang — APPROVED** [review]
Code looks fine

**Review by lewcc — APPROVED** [review]
looks fine

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
