### PR TITLE
Sarin -> Tabun

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Converts Sarin into Tabun

- Harder/more time consuming to make, but better yield
- Wiki friendly, I guess
- same effects as Sarin and same treatment

### CODE REVIEW

**Comment by tigercat2000** [comment]
this is a feature request?

**Comment by Fox-McCloud** [comment]
Our tags are rather lacking; it's the closest thing I could pick.

**Comment by tigercat2000** [comment]
@Fox-McCloud pretty sure this would classify as a refactor, or like, refactor and feature, or like add a new spell-check one and mark it refactor, spell-check, feature.

**Comment by Fox-McCloud** [comment]
@Robertha89 

That...doesn't make any sense though; this recipe mimics Tabun synthesis as closely as possible, just as the Sarin recipe did. If there wasn't an equivalent of some of the chems, then substitution can be ok,but just slotting in random chems when you can make synthesis pretty realistic is...silly.

**Comment by IcyV** [comment]
So it's the same thing with about a minute of extra work. I fail to see how a change like this really matters. I don't disagree with the recipe change, but fail to understand the reason it needs to be looked at in the first place.

**Comment by Robertha89** [comment]
Herpdederp.
Only reason is i dislike making those chems, so just personal preference, well it's the ammonia and oil that i find annoying for some reason, but i digress, but if you wanted a realistic mix, it would be phosphourus 3, chlorine 1, oxygen 1, sodiumchloride 1, cyanide 1, dimethylamine 1, ethanol 1 .
as it's made from 4 precursor chems, phosphorus oxychloride, sodium cyanide, dimethylamine, ethyl acohol, same order for mix as this chems are, and you could add that it would consume itself if mixed in the wrong order, of if over 10 degrees over default reagent temp, or even have it turn into ???

Considering you need to heat chems to make dimethylamine.

**Comment by Surrealistik** [comment]
Pointless. Downvote. Keep Sarin, and keep it transparent on the wiki; it's already easier and faster to make deadlier killchem mixtures than Sarin. If we're going to make a change, have admins get warnings for kill chem synthesis.

**Comment by IcyV** [comment]
I have to agree here. Sarin isn't some super amazing chem. When we have an absurd amount of other choices at our fingertips that can make Sarin look like nothing, why touch sarin at all? It's nerfing either for the sake of not having to put it on the wiki in its current state, or just because you want people to have to work for it more because it's not your special secret chem anymore.

It's silly to change it at the moment.

**Comment by Iamgoofball** [comment]
just leave it as-is IMO

and then just revert the dumb changes people make to take the recipe off the wiki

**Comment by Earthdivine** [comment]
http://nanotrasen.se/phpBB3/viewtopic.php?f=48&t=5046&p=34055#p34055

Some insight to this

**Comment by IcyV** [comment]
I'm fine with a recipe change for the sake of being nice to Goon. God only knows their code is much more worthy of respect. I just dislike it for any other reason, especially given it's all too likely that a few people want it because it can't be their super secret special chemistry stuff anymore.

**Comment by Surrealistik** [comment]
How about we ask Goon first before using it as a justification?

BTW, it took me literally less than a minute to find a functional Sarin recipe via Google without referencing my edit.

**Comment by Earthdivine** [comment]
It's not about how easy it is to find, it's respecting how they do it. They obviously know how easy Sarin is to make, there's a reason it's still that same recipe regardless of ease of finding it, but they choose to do it this way.

**Comment by Surrealistik** [comment]
Either way, ask them if they care/want it kept secret on our wiki before we start using Goon as a justification for this PR.

**Comment by Earthdivine** [comment]
That honestly seems kinda...Pedantic?...to get them involved in our issues when it's concerning a well known policy of theirs, particularly when this PR is a minute change to the point of it being negligible for the sake of not having to worry about said Policy.

**Comment by Earthdivine** [comment]
For comparison, what your saying would be the same as when we took our songs down to avoid copyright. Should we alert the music companies that we aren't using their music anymore? Not really, they don't care as long as we aren't infringing on their terms. This isn't it's a justification for anything, we're merely respecting how they do things and doing some minor editing for that purpose.

**Comment by Surrealistik** [comment]
Goon is not a music company; it is an accessible alternate SS13 community; getting a response would be pretty much instantaneous; it's not pedantic to reference their perspective on this, and yes, 'respecting Goon' is the justification and sole reason we would be doing this.

**Comment by Earthdivine** [comment]
Goon is also a CLOSED SOURCE alternate SS13 community, and as such will have their policy's respected. If there's a greater asking for permission from them, I can get in contact with any of the Goonstation people fairly easily, albit out of my pocket, but for right now I would like more input from everyone else who left Comments on the previous PR.

**Comment by Surrealistik** [comment]
If we go ahead with this PR, use Robert's more realistic suggestion for the recipe and keep the name Sarin; the important thing, apparently, is we don't hand out the Goon formula.

**Comment by Iamgoofball** [comment]
IMO just do the tabun swap and use the suggested realistic recipe, goes well

**Comment by Fox-McCloud** [comment]
Reason why the recipe was chosen is specifically for realism: adding in proportions doesn't really introduce much other than needless additional memorization or fiddliness (and was largely eleminated in newchem)---as for phenol? Well, there's no direct good approximation of chlorobenzene---but chlorobenzene *is* utilized in makign Phenol, which we do have.

Phenol is barely used, as and adds time to making the recipe without delving into minutia.

**Comment by Earthdivine** [comment]
Considering the only things left to be asked before merge were about the recipe, I don't see any more reason to keep this from being merged.

(Also hi NSA!)

**Comment by Necaladun** [comment]
Yes, Hi NSA! :p 

This seems fine as it's wiki friendly and keeps the original substance pretty much the same....

Seems to solve all the problems raised here, so +1 from me.

**Comment by TheDZD** [comment]
Looks like a reasonable compromise to the issue of keeping Sarin a secret chem. I will hold off on merging until Ponies gives input on it, despite the fact that the current count is 2 Maintainers and 2 Heads of Staff for it.

**Comment by ZomgPonies** [comment]
:+1:

**Pull request merged**
