### PR TITLE
Admin Virus2 Creator

### PR DESCRIPTION
**Pull request by tigercat2000**
Basic Nano-module virus2 creator
Not feature complete, but good enough for basic use

Current features:
 - Make and delete virus datums
  - Randomized symptoms/effects on creation
 - Change effects for each stage
 - Change multiplier and chance for each stage
 - Spread to someone random or a specific chosen person (ignores bio
   protection)

pic

### CODE REVIEW

**Comment by Earthdivine** [comment]
:+1: x :100:

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by Plotron** [comment]
Adminbus Virus! yay!

**Comment by tigercat2000** [comment]
When I have the patience to fuck with this more, I'll make it so you can customize the antigens/spread/speed/affected species/etc, but I figured it would be better to release this now.

**Comment by Crazylemon64** [comment]
This was SORELY needed; :+1: for this. I'll be able to try out the species morph virus with actual efficiacy now, and this also gives me ideas for how to make further interfaces like this!

**Comment by Fox-McCloud** [comment]
Just a request, but could you please make the default species list for this what is already under virus2? That way an admin doesn't have to keep trying to get it to spread to the entirety of the crew, if they want.

**Comment by Fox-McCloud** [comment]
@tigercat2000 ?

**Comment by tigercat2000** [comment]
Got preoccupied with the HTML5 stuff, will do.

**Comment by Fox-McCloud** [comment]
Do you plan on doing more work on this PR, or will you be making a new PR, later? If so, I"ll go ahead and merge this.

**Comment by tigercat2000** [comment]
I'll make a new PR later for the rest of the functionality, wanted a working thing in as soon as possible for usability.

**Comment by Fox-McCloud** [comment]
oki

**Comment by tigercat2000** [comment]
Oh. I just realized this uses the default state, not the admin state.
I'll put a fix for it in my HTML5 PR, since this already has to be fixed for compatibility.

**Comment by Ultimate-Chimera** [comment]
Viruses are 100% broken now.

**Comment by tigercat2000** [comment]
somehow I doubt that
as this literally does not touch virus code, it just allows admins to make new viruses

**Comment by Ultimate-Chimera** [comment]
Odd, I was in my local server and the viruses didn't tick at all.

**Pull request merged**
