### PR TITLE
Buffs defibs

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Defibrillators play a very interesting role in SS13. The feature of being able to bring back people from the dead is a very interesting gameplay aspect. Combined with cloning, the two create what many may consider the classic SS13 experience, but I believe, personally, that SS13 is only what we make of it and we shouldn't be guided by the idealized picture of what people already believe the game to be.

I've spent a long time researching how to improve the current situation and I've been digging through a lot of data in order to help me achieve this.

On the following chart, you can see a very important metric, which I believe is the key to uncovering the deep design flaws the current system has.

Taking that data into account, I've crunched our database's death log and have come across another staggering relationship:

I believe, thanks to the data I've collected, that I can improve the general experience of Paradise players at little salt cost and in general improve the experience of every single human being in the universe, while simultaneously lessening the required administrative involvement to support related mechanics.

I present to you my Magnum Opus:

:cl:FlattestGuitar
tweak: defibs work even if you don't target the chest
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Uhh CMO, the Coroner is de-fibbing the patients crotch.

Nevermind, it worked.

**Comment by Aurorablade** [comment]
I dunno if this is such a good idea.

**Comment by granodd** [comment]
This is a QoL change I can get behind. It'd help save about three seconds when you're in the heat and chaos of medbay and trying to revive someone, get the defib ready, go to click them and then realize that you were fixing someone's arm not long ago so it gives you an error message, meaning you have to go down to that little damage doll and click the chest, then click them again.

**Comment by ProperPants** [comment]
I like this. 

Imagine having to target the lips to feed someone pills (or anything). You don't do that, because you can imagine your character is smart enough to feed someone properly regardless of the damage doll.

Good QoL change, Flattest.

**Comment by Jovaniph** [comment]
I like this. In my opinion the targeting mechanic should only be use if the object you are holding has different actions for different areas on the body. Since the defibrillator only has one action, it isn't necessary to make a player target the chest. Now only if you can do the same if player has a cigar on his mouth....hmm.

**Comment by SamHPurp** [comment]
I was originally against it, but now I think I agree with it.

If there was something you could do with it by targeting another area, then, absolutely the targeting should matter.... as there isn't, I think it should be location-agnostic.

**Comment by Anoonki** [comment]
I don't think this is inherently a meme pr just because of some Well made charts :tm:

**Comment by Jovaniph** [comment]
Yeah. I don't think this is a "Meme PR". It is very funny though.

**Comment by Anticept** [comment]
> Uhh CMO, the Coroner is de-fibbing the patients crotch.

> Nevermind, it worked.

... Oh god it was emagged my johnson is on fire.

**Comment by tigercat2000** [comment]
The "Meme PR" label does not disqualify something from being merged, so it's not inappropriate to use in this context, see https://github.com/ParadiseSS13/Paradise/pull/6525

**Comment by Ralta** [comment]
PLEASE
OMG
PLEASE PLEASE PLEASE
YES
PLEASE. PLEEEEEEEASE.
I play surgeon a lot, and I target limbs and such regularly. I've finally gotten into the habit of switching to chest to defib every time, but it really is a pain in the ass, and I don't care what anyone says; a couple of seconds in medbay is the difference between life and _a fuckload more surgery._

👍 x 💯

**Pull request merged**
