### PR TITLE
Relocates Entertainment Offices and Fore Hallway Reorganization on DeltaStation

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
This PR is an alternative to #17480 as we seem to have mixed/lukewarm reviews on that. This should still clean up the design concerns AffectedArc had in #17477, but now expands and adds to existing hallways to make it a main station hallway. This also allows me to add in a pet store which was lacking before hand while now keeping the old mime/clown space and truly transforming it to a backstage/dressing area. We now also have an arcade and swapped half of cryodorms with the barber to make a single, unified room.

There was also a single cable that had a tag that lord knows @S34NW would call me out for that was carried over back from the grave (even though it was in security)

## Why It's Good For The Game
 The custodian being in a maintenance tunnel proper was weird since it didn't match what occurs on MetaStation or BoxStation, and this now gives the clown and mime their own spaces. Now also allows Delta to have a pet store and arcade, and consolidates the cryodorms into a single room instead of two across a hallway.

## Images of changes
 I really, really recommend looking at the MapDiffBot stuff, however some quick screen grabs of some major changes

image

image

image

image

## Changelog
:cl:
tweak: Turns the old entertainment office space into a dressing space for the theatre next door on DeltaStation
add: Adds the Pet Store to DeltaStation
add: Adds the Arcade to DeltaStation
tweak: Adjusts the positioning of half of Cryodorms and the Barber Shop
tweak: Custodial Closet is back in it's previous location, which is no longer in a maintenance tunnel
add: Adds a hallway as an extension of the Fore Hallway for flow/access to modified areas listed above
/:cl:

### CODE REVIEW

**Comment by atteria** [comment]
I really like this PR more, but the three-wide hallway breaks road hierarchy. I don't think this is intended to be a main hallway.

**Comment by S34NW** [comment]
This is certainly a more appropriate edit than the previous one, no offence intended. I recognise that something needed to change, this seems to be it.

**Comment by S34NW** [comment]
@LightFire53 Could you bump the rooms down and right one, expanding maints, to make the corridor respect hierarchy?

**Review by S34NW — APPROVED** [review]
LGTM

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
