### PR TITLE
Mining GPSes are now deactivated at the start of the round.

### PR DESCRIPTION
**Pull request by Accinator50**
## What Does This PR Do
The mining GPS is now deactivated at round start.

## Why It's Good For The Game
The mining GPSes clutter up the whole GPS screen, even if they are not needed. This change will change that. This change only affects Mining GPSes (not the normal GPS that Explorer use).

## Testing
Ran it.

## Changelog
:cl:
tweak: Mining GPSes are now deactivated at the start of the round.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
Couldn’t you just set the range to “Local” instead of “Global”?

**Comment by Accinator50** [comment]
A little input:

I also considered deactivating the GPS at the beginning of the round, but many miners would probably forget to activate it, which is why I decided to go with this option. However, if this option is preferred then I can change that.

**Comment by Accinator50** [comment]
> Couldn’t you just set the range to “Local” instead of “Global”?

Unfortunately, there is no simple variable that can be set to true/false. So I'm going to simply deactivate it at the start of the round for the sake of simplicity.

**Comment by Accinator50** [comment]
>  One gps signal I do think should be z-level exclusive are the shelters, but I think those are already...?

They actually aren't! The main reason for this is that they use the normal GPS, which shouldn't be made z-level exclusive.

However, when I have finished my other PRs, I may see if I can change that.

**Comment by Accinator50** [comment]
Scratch that. I'll add Matt's suggestion once I have more time.

**Pull request closed without merging**
