### PR TITLE
Implements Nuke Ops Cybernetics

### PR DESCRIPTION
**Pull request by Fox-McCloud**
From TG

Adds some of the new augments to the uplink for nuclear operatives.

- X-Ray, Thermal, Reviver, and Anti-stun implants have all been added to the uplink for nuke ops
- Buy a bundle of them for 40 TC and get a discount
- Each augment (or the bundle) comes with an automatic implanter, which can implant the augments without need of surgery

:cl: Fox McCloud
rscadd: Adds X-Ray, Thermal, Anti-tun, and Reviver implants to the nuke ops uplink (augments come with one auto-implanter)
rcsadd: Adds in augment auto-implanter, which inserts and implant without surgery
/:cl:

### CODE REVIEW

**Comment by LittleBigKid2000** [comment]
I never asked for this

**Comment by Tastyfish** [comment]
Something to spend that extra War Declaration TC on that actually increases survival odds!

**Comment by Regen1** [comment]
Why would you get thermal if you already have Xray :V

**Comment by mrturkeytoe** [comment]
No megaman arm cannon?

**Comment by tigercat2000** [comment]
@Fox-McCloud when are you implementing droppods

**Pull request merged**
