### PR TITLE
Adds a new space ruin: The Lizard's Gas

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
Essentially ports tgstation/tgstation/pull/64304, with a few changes. Something I've been planning for a while, replaces the gap left by #18455. <br><br>
Notable Contents:
3000 credits
A security hardsuit and associated jetpack (from the old ruin)
Lots of **_contained_** plasma gas
A ton of snacks and cigarettes
Some janitorial equipment
A deactivated GPS
An abandoned lootcrate
Some rare seeds
Some donk-pockets
and some lizard skin boots (occasionally "mastercrafted" blue boots)
Blarpo the Space lizard

## Why It's Good For The Game
Having more variety in space ruins is cool, also space gas station. It helps fill in the gap left by removing the old ruin.

## Images of changes

The map itself

Seen in game upon discovery (no power)
image
After repowering it
image
Funny sign telling you where the next gas station is
image

## Testing

Loaded up the server, teleported there as an observer, spawned myself in and messed around in the ruin, no runtimes.

## Changelog
:cl:
add: Adds a new space ruin: The Lizard's Gas
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
```
_maps/map_files/RandomRuins/SpaceRuins/thelizardsgas.dmm:102:error: bad type or variable: slist
_maps/map_files/RandomRuins/SpaceRuins/thelizardsgas.dmm:102:error: expected )
```

Please test your PRs

**Comment by Contrabang** [comment]
To be clear, this was partly untested because it was in it's draft stage and I wanted feedback and wanted to sleep that night. It's properly tested now.

**Comment by Denthamos** [comment]
All the food on the racks will be infested by ants since racks do not count as a surface like a table to prevent ant infestation in food.

**Comment by Contrabang** [comment]
It was talked about on discord about how food on racks getting eaten by ants is weird, that might be getting changed in #19023 now

**Comment by roarbark** [comment]
its nice flavour to have a gas station but i would rename it because it kind of still alludes to you know what

**Comment by AffectedArc07** [comment]
> its nice flavour to have a gas station but i would rename it because it kind of still alludes to you know what

I mean, `lizardgas` makes it sound like something entirely else imho. I dont think a rename is needed here.

**Comment by Miraviel** [comment]
I am against getting this added with this name for the simple reason that it is a reference to #18455, which was literally a nazi ruin. Removing #18455 left no gap whatsoever, we still have enough ruins that not the same ones spawn over and over again.

This ruin can be as wholesome as it can get, it is still a reference to a ruin that had gas chambers and human(oid) experimentation in it.

**Comment by Sirryan2002** [comment]
To address the more political criticisms of this PR, yes this is a much healthier and less anti-Semitic ruin as compared to the ruin it was inspired by (or that this ruin seeks to replace). The old Gas Chamber ruin was problematic and awful, the fact that it took this long to be removed left a bad taste in my mouth. However, I'd prefer the memory of it not prevent us from replacing it with better alternatives. From a social justice perspective, we're not really doing the Jewish community any justice by preserving the memory of the gas chamber ruin through shooting down a much more tasteful replacement for it. The currently proposed ruin here does not have references to gas chambers or gassing people, I'd like for our representation of gas/lizard ruin to not represent an awful past going forward and this is a step in the right direciton.

Now for my actual code review comments on this. I'd like for the gas station signs from [TG #64304](https://github.com/tgstation/tgstation/pull/64304) to be included in the ruin. I think this adds a lot of personality to the ruin which increases its quality. Otherwise I do like the map.

**Comment by Contrabang** [comment]
I don't feel comfortable continuing this project anymore. Someone else may take it up if they want to. 

Also, we dont have TG's billboards so I would need to port nearly all of that logic and I don't want to do this for just this.

**Pull request closed without merging**
