### PR TITLE
Atmos room - add welding goggles

### PR DESCRIPTION
**Pull request by Jovaniph**
The reason is so that Atmos Tech can wear hard helmets (with the flashlights) while welding/repairing damaged disposal pipes in the dark. It becomes a big help when extreme pressure and temperature is not a factor, while not in hard suits.

🆑Jovaniph
add: Two welding goggles on in the atmos room
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I don't know. Goggles are supposed to be more special than the helmets, at least their existence on the station would say so. The only open set of goggles is in the assembly line and you have to break into it to get them, even as engineering technically. And it's not like you can't take off your hat or carry a flashlight if you need to weld

**Comment by Jovaniph** [comment]
As far as I can see it...Goggles doesn't make a significant impact in the game. You don't see it be a HUGE perk other than the fact that it goes over your eyes instead on the top of your head.

And I would like to make the argument that wearing a helmet already gives you a perk to hiding your identity. So this isn't a balancing issue as far as I can see.

**Comment by IK3I** [comment]
goggle are actually available in R&D, robotics, sec podbay, assembly, and additionly three pairs in the engine room. They aren't so much scarce as unknown.

**Comment by FalseIncarnate** [comment]
Goggles are much more easily hidden: a mere gas-mask will obscure the fact that a potential flash-victim is wearing goggles. A welding helmet, on the contrary, is more visible, as you can't hide it behind an insanely obtainable mask, meaning there are some serious considerations when it comes to flash protection.

The trade-off with a mask vs goggles largely boils down to visibility and armor: you can get the same flash protection with both, but the goggles let you stack them with helmets and masks for greater effect.

Adding more goggles will make this trade-off less meaningful, as you can have your cake and eat it too. Though frankly, as an IPC and fan of wearing hardsuits to be ready for inevitable breaches, I admittedly don't really worry about the eye damage from welding anyways. To that end, I'm neutral on this change, but think that the impact regarding equipment stacking and visibility should be kept in mind by those reading this.

**Comment by Keilden** [comment]
Leave on welding mask for the poor Kidans.

**Comment by Taaketa** [comment]
Kidans and Plasmamen need welding goggles to see. Plasmamen suits don't afford flash protection. I'd support adding goggles in or at least a pair or 2.

**Comment by Jovaniph** [comment]
I hate.....doing merge conflicts..I just hate...I rather close the PR and start all over, over a simple edit.

**Comment by TullyBurnalot** [comment]
@Jovaniph Following discussion, PR is approved pending:

1) Re-adding the masks. Just have both options, it's cool.

**Comment by Fox-McCloud** [comment]
Please make the necessary changes, or this will be closed very soon.

**Comment by Jovaniph** [comment]
Is good now. Thanks for waiting.

**Pull request merged**
