### PR TITLE
Adds in Skeleton Race

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in a skeleton race; this is modeled as closely after TG's skeletons as possible.

Fixes https://github.com/ParadiseSS13/Paradise/issues/3304

Maybeeee fixes (not sure): https://github.com/ParadiseSS13/Paradise/issues/3169 (kinda doubt it)

First off: please, don't ask this to be a playable race; it's not meant to be; it's meant for events and such.

What Special attributes do skeletons have?
- Spooky
- Scary
- Skeleton-y
- Radiation immune
- Heat immune
- Cold Immune
- High/low pressure immune
- Virus Immune
- No breathing
- No Blood

Related
- Recolors the skeleton sprites to be more yellowish than white, to help cut down on "I can't see them" when on white turfs
- Adds in the RADIMMUNE flag; give this to a species to make them 100% totally immune to all radiation.
- Removes the radiation immunity from NO_DNA_RAD
 - Gives IPCs RADIMMUNE. The only thing that changes here is that technically IPCs could get hallucinations from non-radiation sources now

Pics:
img

:cl: Fox McCloud
rscadd: Adds in a Skeleton race
tweak: Tweaks the skeletons colors to be more realistic and to blend in less with the floor
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Don't we already have a flag like that for IPCs?

**Comment by Crazylemon64** [comment]
NO_DNA_RAD. Prevents all forms of genetic modification, too. Should that be applied to these spoopy folk?

**Comment by Fox-McCloud** [comment]
We have some flag that's utilize as kinda a "catchall" for IPCs..but it has other effects too, such as not being able to alter DNA, not being impacted by some organic things---etc; it's not really appropriate for anything other than IPCs, TBH.

There's also a RAD_ABSORB flag, but it makes things heal in radiation (Diona thing), so it's also not appropriate.

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

That would also make them immune to clone loss and certain types of hallucinations--and, again, that flag is kinda used as a catchall for whenever something snowflakey for IPCs comes up.

**Comment by Crazylemon64** [comment]
Perhaps that flag should be broken down, then, into less snowflakey behavior...

**Comment by KasparoVy** [comment]
thankmr skelt

**Comment by FalseIncarnate** [comment]
Gonna agree with crazylemon.

Skeletons shouldn't be genetically modifiable through any means short of admin-tools.

Breaking down the IPC flag probably would be a smart move for paving the way for new potential species, but would be best done as a separate PR for obvious reasons.

Any chance for admin-transform option to "skeletalize" victi- I mean volunteers?

**Comment by Fox-McCloud** [comment]
>Any chance for admin-transform option to "skeletalize" victi- I mean volunteers?

As with all species, you can use the "set species" drop down

There's another very good reason they should be able to modify their DNA: Wizards. If we ever get around to porting Lichdom (which we probably will, one day), wizards should be able to have genetic powers and this spell at the same time (as there's spells for both).

**Comment by NTSAM** [comment]
clik clak

**Comment by Spacemanspark** [comment]
NYEH HEH HEH.

**Comment by HereticChurch** [comment]
Wonderful, we're closer to porting lich wizards!
So these things are spaceproof? Neat.

**Comment by Markolie** [comment]
I do think it's best to change NO_DNA_RAD to NO_DNA if you're adding a RADIMMUNE flag - I only really combined DNA/Radiation because of fear of running out of bitflags.

**Comment by Crazylemon64** [comment]
Should we try out a list-flag system?

**Comment by Markolie** [comment]
I think that's a good idea - we'll run out of bitflags eventually.

**Comment by Fox-McCloud** [comment]
NO_DNA_RAD no longer carries radiation immunity with it; that's all handled entirely by RADIMMUNE.

IPCs have RADIMMUNE now.

Things with NO_DNA can now be impacted by hallucinations (that said, RADIMMUNE things will not get hallucinations from the radiation event).

**Comment by TheDZD** [comment]
I'm assuming this affects the "Make Spooky" dropdown in VV?

**Comment by Fox-McCloud** [comment]
@TheDZD 

Actually, not; I plan on refactoring skeleton handling though, after this gets merged in (it's currently a snowflakey piece of crap that's handled in human update icons, primarily).

**Comment by fludd12** [comment]
@Spacemanspark 

[Hey there.](https://www.youtube.com/watch?v=VjB1HEYo7g0)

**Pull request merged**
