### PR TITLE
Makes lavaland outpost (and gulag) less annoying to fix.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## What Does This PR Do
Breaking floors in outpost or gulag now creates regular lavaland ash floors instead of lava/plasma/chasms.
It does it so by changing all of /baseturf_helper/lava_land/surface into /baseturf_helper/asteroid/basalt

## Why It's Good For The Game
Makes it way less annoying to fix in case something explodes/someone goes on an unscrewing spree.
Besides, why would NT build on unstable ground?

## Testing
Spawned in, messed around with floors.
TO-DO:
- [x] test more cause I have a feeling this can break things
- [x] fix wrong icons with plating explosions
- [x] fix wrong icons with plating deconstruction
- [x] test more

## Changelog
:cl:
tweak: Breaking tiles in lavaland outpost or gulag no longer creates lava/plasma/chasms. Instead, it creates regular ash surface.
fix: Removed an accidental air alarm from gulag.
fix: Icons no longer break if plating is destroyed on Lavaland.
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
good stuff

**Comment by Sadhorizon** [comment]
There is in fact a couple of bugs this introduces.
obraz
obraz

1) Lattices get created underneath the tiles.
2) Some tiles don't update their icons. On images above, platings I'm pointing to are actually vulcanic floors.

**Comment by Sadhorizon** [comment]
Lattices are in fact issue that is already a thing, I'm just gonna ignore those.

obraz

(also I don't know why is this burning)

**Comment by Sadhorizon** [comment]
I think it should be all working now.

**Pull request merged**
