### PR TITLE
Make diona nymphs space worthy

### LINKED ISSUE #6028: diona nymphs die from lack of oxygen in a space pod
**Problem Description**:
What is the problem?
diona nymphs die from lack of oxygen in a space pod

**What did you expect to happen**: 
Why do you think this is a bug?
The spacepod had oxygen

**What happened instead**:
How is what happened different from what you expected?
I expected For them not to die of oxygen deprevation in a spacepod

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Not a high priority issue, but def a bug.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be a diona nymph, be in someone's possesion, have them get in a space pod and fly into spac.e

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Flying in space.

### LINKED ISSUE #7807: Diona nymphs die without oxygen
**Problem Description**:
Nymphs die without oxygen unlike grown dionas.
 
**What did you expect to happen**: 
Not to die due to oxygen loss.

**What happened instead**:
Dying to oxygen loss.

**Why is this bad/What are the consequences:**
From time to time, oxygen in the vent or scrubbers is not available due to "unusual" circumstances. This prohibits any future travelling through the vents for dionas. Space walks or locations without oxygen atmosphere result in death as well.
Also, it doesn't make any sense.

**Steps to reproduce the problem**:
Be diona nymph, go into space.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
Simple bug really. Issue #6028 is probably related to this and fixing this bug should logically fix the other one.

### PR DESCRIPTION
**Pull request by Ataman**
This PR lets diona nymphs live in space like their gestalt form, instead of dying to cold and missing oxygen.
Fixes #7807 
Fixes #6028

I don't know what I did wrong on my last contribution but the changelog entry didn't show up in the actual changelog. Please confirm that I did it right this time. 

:cl: Ataman
fix: Fixed diona nymphs needing oxygen and getting cold.
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
Changelog looks fine

**Comment by Ataman** [comment]
Alright, thanks for confirming @Citinited

**Comment by SamHPurp** [comment]
@Ataman the problem was last time you didn't include the `add:` `fix:` etc. Should be fine now!

**Comment by Ataman** [comment]
Good to know @SamHPurp, I have no idea how I didn't get that the first time...

**Comment by Balthusdire** [comment]
I like it. It is really frustrating to merge with gestalt and then die when they walk into space.

**Comment by taukausanake** [comment]
I think you need separate lines for Fixes? Currently the keyword only says it fixes 7807

**Comment by Ataman** [comment]
@taukausanake 
Didn't even know that would work automatically! Fixed now.

**Pull request merged**
