### PR TITLE
TG Changeling Port [Feature] [Balance]

### PR DESCRIPTION
**Pull request by TheDZD**
# Changeling Overhaul
This PR ports changelings from [tgstation/-tg-station](https://github.com/tgstation/-tg-station) to replace the current changelings on Paracode.
Any powers not detailed below are either still around, or have direct/very similar equivalents. Some powers already present will be mentioned again due to minor changes to them.

## Notable Mechanical Changes
- Changelings no longer gain points to acquire additional powers through absorbing humanoids, instead they are given 10 points at the start, and may reassign their points upon absorbing a humanoid. Power costs are adjusted accordingly.
- After absorbing 4 genomes, a changeling must transform in order to process said genomes.
- Certain changeling powers, most notably shapeshifting no longer provide chat messages when used.
- Default sting range is 2, as such the ability to increase sting range is removed.
- After selecting a sting, you can alt+click or middle mouse click a person to sting them.
- [x] Mixing a changeling's blood and welding fuel serves as a test to see if they are a changeling. A normal person's blood will just break apart in the fuel, a changeling's blood will react in an unnatural fashion.
- [x] Syringes take time to extract blood, but still extract the full 15 units at once. This is to combat somebody going around and testing random people's blood, as well as somebody just walking up to, clicking a suspected ling, and testing their blood.
- [x] Slime people changelings disabled due to their lack of blood both making them immune to the test, and instantly murdering them if they change to a species with blood.
- [x] Races with the NO_SCAN flag are made immune to the transformation sting to prevent them from instantly dying. This includes IPCs (already immune anyway), Vox, and Slime People.

## Objective Changes
- Now required to get 6-8 genomes instead of 2-3.
- Objectives are as such:
 - Objective 1: 60% chance to get a Steal objective, otherwise they get a Debrain objective.
 - Objective 2: Chance of getting a Destroy AI objective that decreases the higher the number of players in the round. Will otherwise get an objective to assassinate somebody and escape with their identity (ID card and transformed into them).
 - Objective 3: If they do not already have an objective to escape, there is a 70% chance of being given a normal Escape objective, otherwise will be tasked with escaping with the identity of a specific crewmember.

## Notable Changeling Power Removals
- Death sting and paralysis sting are GONE. They were extremely cheap "I win" buttons.
- Change species as a power is gone, you now change species along with identities.
- Unfat sting is gone, you do have an alternative way to obtain DNA from people other than a neck grab absorb now, that will be detailed below.
- Deaf sting is gone, may be added again in the future, but it was fairly useless, there IS however another power that deafens people.

### Mutations
- Armblade: Changelings can grow a blade out of their arm that does 25 brute damage per swing. It costs 20 chemicals, drop it or use the power again to make it go away.
- Organic shield: Gives the changeling an organic riot shield, and will initially disappear after blocking a single hit, however as the ling gains more genomes, the shield becomes stronger.
- Organic spacesuit: Gives the changeling a spacesuit that constantly injects them with dexalin+ while in use, allowing them to remain in space indefinitely (although due to Bay code, you will still rupture a lung, this can be fixed through regenerative stasis. It slows down chemical regeneration while in use. Toggle-able ability, cannot otherwise be removed.
- Chitinous armor: Gives the changeling a suit of armor and a helmet that is fairly strong against melee attacks, but suffers greatly against just about everything else. Slows down chemical regeneration while in use. Toggle-able ability, cannot otherwise be removed.

### New Stings
- Cryo Sting - Injects the target with ice and frost oil, cooling their body temperature and slowing them to a crawl. Especially effective on enemies wearing a hardsuit. (NOTE: Disabled because it's nigh useless due to how Baycode handles mob temperatures, it will do nothing for a long time, then make you hungry, then suddenly freeze you out of nowhere.)

### Other Powers
- Panacea: Injects the changeling with ryetalyn, anti-toxin, and hyronalin. This purges their body of toxins, removes all mutations, and heals radiation and toxin damage. Also cures any viruses the changeling may be suffering from by generating an antigen for said viruses.
- Fleshmend: Rapidly heals the changeling of all damage types except toxins, will not fix internal organ damage and broken bones, those require Regenerative Stasis.
- Engorged Chemical Glands: Boosts the changeling's chemical storage by 25, and generation by 0.5.
- Resonant Shriek: Emits a high-pitched sound that deafens and confuses nearby humanoids, while also stunning nearby cyborgs. It also breaks nearby lights. Other changelings will not be affected.
- Dissonant Shriek: Generates an electro-magnetic pulse in an area round the changeling, damaging nearby synthetics and electronics (RIP Machine People).
- Strained Muscles: Toggle-able ability that allows the changeling to run at high speeds and ignore some of the slowdown caused by heavy armor and hardsuits. Prolonged use damages the changeling's stamina. Overuse will stun the changeling when he ends the ability, or is forced out of it due to excessive stamina drain.
- Augmented Eyesight: Toggle-able ability that provides the changeling with night vision and the ability to detect heat signatures (read, mobs) through walls.
- Extract DNA Sting: Is now given to the changeling by default, can be used to acquire genomes for their objectives.

## Semi-Related Bugfixes
- Makes it so UI code doesn't handle 0 as poorly by making it handle it as 1. This may result in nearly imperceptible color changes to hair, skin, etc. but will also prevent a person from getting pink-purple hair, skin, etc. due to cloning. This also means changelings will ACTUALLY look like the person they choose to impersonate.
- Identity Theft + Escape objective can be assigned via Traitor Panel.

I probably missed a few smaller details due to the fact that I royally screwed up and made all of the major changes in one commit, so I couldn't properly sort through and log them all.

# For the Hivemind!

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Massive :+1: So glad to see outdated game modes getting updated.

**Comment by ZomgPonies** [comment]
I'm okay with getting this merged in ASAP, ling has been needing an overhaul for the longest time.

**Comment by TheDZD** [comment]
Way to test changelings added as requested.

**Comment by Fox-McCloud** [comment]
@TheDZD 
Looks good; will merge in at the day mark.

**Comment by TheDZD** [comment]
Merge conflicts fixed, always the sprite sheets too.

**Comment by ZomgPonies** [comment]
This is okay to merge now I think.

**Pull request merged**
