### PR TITLE
Why Neca

### PR DESCRIPTION
**Pull request by Aurorablade**
adds a bag...for drinks...its like one of those bags in a wine box..but no box

Sprite by skittles

:cl: Fethas
rscadd: The booze o' mat now has wine..bags.
/:cl:

### CODE REVIEW

**Comment by Necaladun** [comment]
we're the real goonstation now

**Comment by Shadeykins** [comment]
As a Canadian I demand that the dispenser also dispenses milk bags.

**Comment by KingPhilipIII** [comment]
*scream

**Comment by DarkPyrolord** [comment]
I approve of this, I need my boxed wine ASAP

**Comment by DesolateG** [comment]
Bagged milk

**Comment by davidchan13** [comment]
If the bag can't be inflated from an O2 tank for use as a pillow I'll riot.

**Comment by taukausanake** [comment]
I mean I guess so. You can carry your drinks wherever without trouble now, but that's its only practical use?
To reiterate the title, why?

**Comment by davidchan13** [comment]
@taukausanake It's a meme. Bags of (cheap) wine are popular in Australia, referred to as 'Goon' and generally considered one of the trashier ways to get wasted, not the least of which because of how easy they are to hide/smuggle into public events where outside drinks aren't allowed.

These bags would be hilariously OP and coveted by most power gamers because of their 150u capacity, assuming no checks are in place to prevent them from being refilled.

**Comment by taukausanake** [comment]
Oh so it's THAT kind of bag. I thought it was a bag like book bag but for drinks. Ignore me I'm dumb

**Comment by DesolateG** [comment]
I think it should be boxed wine. American trash wine is clearly superior to Aussie.

**Comment by Aurorablade** [comment]
a 30u container could be abused by powergamers but fine.

**Pull request merged**
