### PR TITLE
Sol trader update

### PR DESCRIPTION
**Pull request by Kyep**
:cl: Kyep
add: Reworked Sol Trader event. Trade ships now represent a valuable opportunity for the crew.
/:cl:

Changes:
1. The trader shuttle now has items actually worth trading for, often items that the crew cannot obtain any other way. Trading shuttles are now a valuable opportunity for the crew, as opposed to before where they were a largely useless annoyance.
2. The shuttle now also has more space and a better design overall, with items organized in department-specific containers, and better security against boarders. Items actually spawn inside the containers, so this also skips the tedious 'packing phase' at the start of every trader event. 
3. The shuttle is no longer a special snowflake that requires specific permission to dock with the Cyberiad. Now it simply docks when told to at its shuttle console - like every other shuttle in existence. It also no longer has a useless secondary docking port that positions it a distance away from the station, in space. 
4. The Jupiter Station map area on z2 has been tweaked, adding cryopods so that successful traders can despawn themselves after they are done trading.
5. 'Sol Trader' is now defined as an admin outfit, enabling admins to manually spawn specific people as traders for the purpose of events. E.g. for better control of what is traded. To further increase the chances of traders actually knowing what they are doing, the minimum amount of play hours required to get the trader role has been increased from 5 to 20.

Trader shuttle example:
wip_trader_shuttle

Bear in mind that the exact items found in each trader shuttle are still randomized, so you may get quite different items each time.
Also bear in mind that many of the items are unique versions not otherwise obtainable. For example:

- The papers in the science crate are research notes, which are a re-done version of the research notes from the terror spider away mission. Now, instead of giving a bunch of low level techs from multiple tech trees, they instead give one tech to a high level, even beyond the normal tech limit of 7.
- The KAs are actually a unique version that is much stronger than a regular KA.
- The bottles can contain things beyond standard reagents, like omnizine, frost oil, or even virus cultures of specific symptoms/viruses.

Annotated version:
wip_trader_shuttle_annotated

Key for annotations:

- Green X = public access door
- Green box = public access area
- Orange X = trader-only access door, which can be opened remotely from the trader side using a button, enabling crew access to orange box areas
- Orange box = area that traders drop items and crew drop payment, enabling trades without either of them having to be in the same room, and without giving crew the opportunity to attack the traders
- Red X = secure barriers which normal crew should never pass
- Red box = secure area for traders that normal crew should not enter

Jupiter station:
new_jupiter

This PR was largely based on player feedback, obtained from: https://nanotrasen.se/forum/topic/14951-what-would-you-trade-for/
While I cannot accommodate all player suggestions, I have included many of them.

### CODE REVIEW

**Comment by TDSSS** [comment]
How many traders usually spawn in? Will 2 cryopods be enough for them?

**Comment by Kyep** [comment]
Usually 2, and as soon as the IC->Ghost the cryopod is free again anyway.

**Comment by datlo** [comment]
How big are the mineral stacks, how do they work exactly? How much bananium would I get if it spawned?

**Comment by Kyep** [comment]
@datlo The 'minerals' container contains 6 stacks of randomly chosen materials, 25 sheets per stack. Materials can be basic (wood, plastic, sandstone, plasteel, etc), advanced (all the mining minerals) or hybrid (plasmaglass, titaniumglass, etc). If bananium was chosen as one of the materials, you'd get a stack of 25 sheets of it.

**Comment by datlo** [comment]
Lright, sweet.

**Comment by datlo** [comment]
I recall the trader having a guaranteed spawn syndicate spacesuit that they could use if they needed to do EVA, is that still in?

**Comment by Kyep** [comment]
@datlo It isn't. It isn't needed anymore.

- They won't need to EVA to board the station, since they dock directly at it (no more permission request that can be denied, leaving them stranded in space). Further, they no longer have an EVA 'back door' into their shuttle for this reason.

- The area they dock at (north arrivals) is generally never bombed/destroyed, because its very hard to do so without also damaging the arrivals shuttle itself (which is a protected area). Even if the corridor they dock to is damaged, they can simply ask crew to repair it before they trade.

- They aren't going to get sucked out into space even if their docking port is completely destroyed, since they have a dual-airlock sally port system that both stops their air leaking out and stops pressure sucking them out.

**Pull request merged**
