### PR TITLE
Borg rebalancing

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR attempts to tackle some of the balance issues surrounding borgs. It does not fix ALL borg balance, especially secborg balance, but it's a step in the right direction.
~~Reduces VTEC speed boost by half.
Off-station borgs (ERT, Nukies) get faster VTEC speeds, the same as currently.~~
Security borgs can no longer get the VTEC upgrade.
Janitor borgs no longer start with a "floor buffer" functionality, it is now an upgrade module that also gives a speed boost that is 50% that of VTEC.
Janitor borgs have to choose between VTEC and Floor buffer upgrades, they cannot have both.
Janitor borgs advanced mop now starts with space cleaner by default.

## Why It's Good For The Game
Janitor borgs currently outstrip organic janitors in every possible way, to the point that organic janitors need not bother if there is a janiborg. This change will tackle that, meaning janiborgs can be fast but with default toolset (soap, adv. mop, etc.) or slower with the floor buffer upgrade (similar to janicart.) This should make the janitor job actually have a purpose when there is a janiborg.

Secborgs are a big balance issue, this is an alternative to things like #15862 that attempt to remove them entirely. One issue of contention is how fast they are, when they are intended to be _"Slow and cumbersome but strong."_ This PR disables VTEC choices for them, so they are still good at what they do, just slower.

## Changelog
:cl:
add: Janiborg floor buffer upgrade that, while incompatible with VTEC, gives a smaller speed boost (50% of VTEC)
del: Removed round-start janiborg floor buffer functionality
tweak: Janiborg mop starts with space cleaner
tweak: Sec borgs cannot have VTEC
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
This is just gonna cause a ton of floors to be slippery by janiborgs...
Slip station is reality, currently, if you even use the mop or anything.
People get overly frustrated because they slip over it.

**Comment by Calyxman** [comment]
Secborgs are fairly weak, they can die to a few hits, and they've got a severe weakness to flashing. Don't like this at all, but I'm not a coder or anything. 
Slipping is hell. No.

**Comment by S34NW** [comment]
> 
> 
> This is just gonna cause a ton of floors to be slippery by janiborgs...
> Slip station is reality, currently, if you even use the mop or anything.
> People get overly frustrated because they slip over it.

janiborg mop now starts with space cleaner

**Comment by S34NW** [comment]
> 
> 
> Secborgs are fairly weak, they can die to a few hits, and they've got a severe weakness to flashing. 

With all due respect, this is just factually untrue. Secborgs are much stronger than organic sec when played even semi-competently.

**Comment by procdrone** [comment]
> 
> 
> > Secborgs are fairly weak, they can die to a few hits, and they've got a severe weakness to flashing.
> 
> With all due respect, this is just factually untrue. Secborgs are much stronger than organic sec when played even semi-competently.

With all due respect, this is factually untrue. If you can easily disable a borg for long enough to kill it (not only flashes, laser points, EMP, flashbangs), without it being able to even speak. 

In direct combat, if you don't go for the *stun based combat* on a *stun based combat server* you, of course, will loose to a borg that does use the *stun based combat* and stun you... well, you can only blame yourself. If you want to blame that balance, I suppose Fox combat overhaul PR is what you should be looking towards.


Also, slipping? Please just leave the poor janiborgs alone, they did noone harm, they just zoom around making the station clean. Or occasionally are a nuisance to cults, but cult has multiple ways of dealing with it.

Additionally, we already spoke about this millions of times. Making borgs slower is not a solution, but a punishment. You want to punish all borgs (who, for example, are now slower than spiders, probably cant escape from blobs, nukies, or evade pretty much anything) just because you couldn't prepare a stun for that secborg. Not to mention that none of the hard counters are touched so they are screwed even harder now. Not just sec borgs. All borgs.

I remind, that by design a specialised borg unit was supposed to be a little better at the job of the module they load.

**Comment by LightFire53** [comment]
This is all fair. Sad for janiborgs, but also completely fair since they are just better than regular janitors. How costly is the floor buffer upgrade? Is it aimed as a "mid round upgrade" or is it relatively cheap?

**Comment by S34NW** [comment]
> This is all fair. Sad for janiborgs, but also completely fair since they are just better than regular janitors. How costly is the floor buffer upgrade? Is it aimed as a "mid round upgrade" or is it relatively cheap?

It's around the same as other materials. Research is Materials 4, engineering 4; same as floor buffer for janicart. Stock mech fab cost calls for 15k metal and glass each. The same or similar to many other cyborg upgrades.

**Comment by Mitchs98** [comment]
Disagree with the VTEC speed change and the nerfs to janiborg. Tossing on the change to secborg seems more like a shot at getting people to agree with the PR to me imo. VTEC changes should, if anything, be in its own PR. VTEC and Janiborg changes seem entirely out of scope to be in the same PR.

**Comment by S34NW** [comment]
> 
> 
> > > Secborgs are fairly weak, they can die to a few hits, and they've got a severe weakness to flashing.
> > 
> > 
> > With all due respect, this is just factually untrue. Secborgs are much stronger than organic sec when played even semi-competently.
> 
> With all due respect, this is factually untrue. If you can easily disable a borg for long enough to kill it (not only flashes, laser points, EMP, flashbangs), without it being able to even speak.

Saying "laser pointers exist so borgs are balanced" is like saying "syndie chainsaws exist so humans are balanced", when do you ever see laser pointers get used? Flashes, EMP and flashbangs are valid tools, but they have the same effect on organic targets, and that's where the list ends for borgs whereas it carries on significantly for organics.

> In direct combat, if you don't go for the _stun based combat_ on a _stun based combat server_ you, of course, will loose to a borg that does use the _stun based combat_ and stun you... well, you can only blame yourself. If you want to blame that balance, I suppose Fox combat overhaul PR is what you should be looking towards.
I'm not even sure what this argument is? Fox's combat overhaul is coming, like it or not. The options for stunning a borg are extremely limited vs an organic, and you can guarantee the AI will start screaming when its borg cam goes offline.

> Also, slipping? Please just leave the poor janiborgs alone, they did noone harm, they just zoom around making the station clean. Or occasionally are a nuisance to cults, but cult has multiple ways of dealing with it.

Slipping? What? This again is a nonsense argument. Janiborgs are significantly more robust at their role than janitors are, if you are a janitor with a secborg on-station, you might as well give up. The janiborg _will_ get there before you because it has AA, and _will_ clean the mess first. Not to mention rushing cult runes without fear of death, something a janitor would be shouted at for doing.

> Additionally, we already spoke about this millions of times. Making borgs slower is not a solution, but a punishment. You want to punish all borgs (who, for example, are now slower than spiders, probably cant escape from blobs, nukies, or evade pretty much anything) just because you couldn't prepare a stun for that secborg. Not to mention that none of the hard counters are touched so they are screwed even harder now. Not just sec borgs. All borgs.

This isn't making borgs slower, it's reducing the effectiveness of their upgrades. Borgs are already slower than spiders, blobs, nukies, what have you, because their round-start speed is their intended speed. Collecting all of the upgrades possible and going super fast is just powergaming. Players have to make decisions about what to carry and equip, borgs should too. They already have AA, a direct link to the AI, sec/med/diag hugs, a strong lamp and less accountability than regular crew. To say they are not in a broken state is laughable.

> I remind, that by design a specialised borg unit was supposed to be a little better at the job of the module they load.

A _little_ better is the key here. Janiborgs are obscenely better currently. Restricting them to an advanced mop with space cleaner at round start still means they have a leg up over regular janitors, who have normal mops that don't auto-regen space cleaner. The floor buffer can come later, and that is fine. Round-start is not.

**Comment by S34NW** [comment]
> Tossing on the change to secborg seems more like a shot at getting people to agree with the PR to me imo.

I don't appreciate the use of accusatory language like this, GitHub is not the place to try and sling mud on people. Suggesting I only did something to try and cheat the other changes through is not appreciated. It doesn't even make much sense, because both changes were going to be controversial to begin with.

> VTEC and Janiborg changes seem entirely out of scope to be in the same PR.

This PR is looking at borg balance as a whole, I don't think the other borgs need nerfing or buffing currently, they are in a good place. So these two changes are the ones I put forward to tackle the most problematic borgs.

**Comment by Mitchs98** [comment]
> I don't appreciate the use of accusatory language like this, GitHub is not the place to try and sling mud on people. Suggesting I only did something to try and cheat the other changes through is not appreciated. It doesn't even make much sense, because both changes were going to be controversial to begin with.

Yeah, fair enough. This is why I shouldn't comment on things as soon as I wake up.


> This PR is looking at borg balance as a whole, I don't think the other borgs need nerfing or buffing currently, they are in a good place. So these two changes are the ones I put forward to tackle the most problematic borgs.

The original PR was VTEC and Janiborg changes, and those are the only ones in the PR. Not sure how this is balancing borgs on a whole, unless you count making their lives miserable with VTEC changes balancing them.

**Comment by S34NW** [comment]
> 
> 
> > I don't appreciate the use of accusatory language like this, GitHub is not the place to try and sling mud on people. Suggesting I only did something to try and cheat the other changes through is not appreciated. It doesn't even make much sense, because both changes were going to be controversial to begin with.
> 
> Yeah, fair enough. This is why I shouldn't comment on things as soon as I wake up.
> 
> > This PR is looking at borg balance as a whole, I don't think the other borgs need nerfing or buffing currently, they are in a good place. So these two changes are the ones I put forward to tackle the most problematic borgs.
> 
> The original PR title was VTEC and Janiborg changes, and those are the only ones in the PR. Not sure how this is balancing borgs on a whole, unless you count making their lives miserable with VTEC changes balancing them.

Thanks for apologising.
Regarding the title, I suppose it isn't really a full-on borg rebalance in the true sense of the word, but since the other borgs are in a good way these are the only changes I thought were necessary. VTEC does touch on all borgs, although having slightly slower movespeed in exchange for the strong tools/benefits they get over organics is a tradeoff for this. The speed for station borgs with vtec can be tweaked now if it's too slow, its a simple process to tweak until it feels "right."

**Comment by Mitchs98** [comment]
I can see the merits in making the floor buffer for Janiborgs be an upgrade, but not where they have to choose VTEC over it. If anything, you could make VTEC slower for them due to having the floor buffer attachment as you're doing for secborgs in this PR.

I just don't believe VTEC needs any sort of speed decrease fullstop for every single module. It's already miserable to play a borg without VTEC as it is now due to being so slow, it's one of the main reasons I don't play borg that often at all.

**Comment by procdrone** [comment]
>Saying "laser pointers exist so borgs are balanced" is like saying "syndie chainsaws exist so humans are balanced", when do you ever see laser pointers get used? 

That doesn't seem like a fair argument. I'm outlying that there are tools that exist, and are easy to obtain. Why does it make any more valid to rebalance borgs?

> Flashes, EMP and flashbangs are valid tools, but they have the same effect on organic targets, and that's where the list ends for borgs whereas it carries on significantly for organics.

Borgs are different, and the different approach, is the point. They are annoying but you can as easily shut them down completly. (sometimes even outrun them if you prepared the area beforhand, for example, borgs cant go through fake walls, or holographic barriers) While, flashed, banged, or even EMPed organics can still scream, radio (unless EMP) and generally call for help. You can also easily subvert the borg. Play the laws. Play the emags. 

>and you can guarantee the AI will start screaming when its borg cam goes offline.

Using your own argument, this never happens. AI's almost never babysit their borgs. (i also might be mistaken but camera alarm happens like only if the borg is blown up, so even if you kill the AI, AI wont notice right away, unless its keeping active watch over its status bar/cyborg console.)

>I'm not even sure what this argument is? Fox's combat overhaul is coming, like it or not. The options for stunning a borg are extremely limited vs an organic.

Organic stuns options: 
-Shock Stun (either by melee stuns with stunbatons or golden bolts from range).
-Stamina Stun (disablers)
-Chemical (sleep chemicals, like Ether or Sleepy pen)
-Gasses (N2O, which also causes sleep)
-Abilities stun (glares, cult stuns, and other ability based stuns)

Silicon stun options:
-Flash Stun (Flashbangs, EMPs, and Flashes, also Laser Pointers. Do not forget that flash powder and the other chemical that makes the flashbang work too, albeit for a shorter duration)
-Removal of power source (taking the cell out)
-Lockdown (not handy but is still an option)
-Abilities stuns (yes, other antags have stun abilities that also affect borgs)
-Subversion (either by laws or emagging. not a "stun" per say but its still a method of getting rid of borgs as a threat)

Now, you might say, but i need access to remove the cell - Okay. you can buy agent IDs to steal that access, or emag to break it.
The same can be said about stuns from the organic sections. You can't get sleep chemicals without getting access to some area of the station or buying appropriate tools from uplink. Or asking another traitor working in that department for help. 

Having an antag friend help out is a perfect way to counter strong security, borgs or otherwise. Noone ever said you can't team up, and even strategize your uplink purchases. (or power unlocks, or whatever relevant for the antag) Your antag friend can even eat the so hated disabler shots that are sent your way in maint halls where you can't dodge them. (or well, drag a locker).

You are trying to say that ways to deal with a borg are very limited and personally, I just dont see it. 

>Slipping? What? This again is a nonsense argument. Janiborgs are significantly more robust at their role than janitors are, if you are a janitor with a secborg on-station, you might as well give up. The janiborg will get there before you because it has AA, and will clean the mess first. Not to mention rushing cult runes without fear of death, something a janitor would be shouted at for doing.

My Slipping argument was a reaction to people above complaining about floors being slippery. 

As for janiborg getting to you, you say you can't kill a borg that has a mop? they have to close into melee range to do you any harm. Just stun and kill them. Not to mention I dont think janiborgs have any business chasing antagonists around. (also noslips counter janiborgs making floors wet on you 100%)

If you are a cultist and you dont EMP and sacrifice janiborgs, i mean, you should rethink your strategy. (and even better, if you get the so powerful jani + sec duo, two birds with one stun with that EMP)

>Players have to make decisions about what to carry and equip, borgs should too. They already have AA, a direct link to the AI, sec/med/diag hugs, a strong lamp and less accountability than regular crew. To say they are not in a broken state is laughable.

While i have to agree, mutually exclusive upgrades are somewhat interesting idea, doing it just for the sake of nerfing borgs is misguided to me. But I would sure love to see the idea revisited with more, specialisation in mind, so the borg picks between the upgrades towards a specialized and niche goal. (for example, a med borg being able to synthesise advanced chems but being unable to surgery? just an idea).

As for the lamp, it might be strong on higher levels but drains power quite quickly, unless on a slime cell, borgs can't really afford to go on max lamp all the time. While, organics have limitless flashlights.

>This isn't making borgs slower, it's reducing the effectiveness of their upgrades. Borgs are already slower than spiders, blobs, nukies, what have you, because their round-start speed is their intended speed. Collecting all of the upgrades possible and going super fast is just powergaming. 

Which de facto makes them slower from their potential speed with VTEC. (i see VTEC as a kinda necessary upgrade to get since the "standard" speed is pain), a slow borg can't really do anything to run or defend itself from ANY threats. that includes even standard greytiders. (a slow speed borg has issues with "fastmoss" even) 

People only think that it will help borgs not chase antags as effectively but forget that borgs do a lot of running away as well, and well, now they wont be able to run from anything. given how weak HP wise they are and defenceless, it will just be peasy easy to murder. It personally makes me sad you think that to do that, would bring any balance.

**Comment by Wojz** [comment]
>Reduces VTEC speed boost by half.

Not sure if needed. Because speed is only an issue for secborgs, and...

>Security borgs can no longer get the VTEC upgrade.

Yea. I like this.

>Janitor borgs no longer start with a "floor buffer" functionality, it is now an upgrade module.

Very good. Power creep and powergaming isn't just limited to antag stuff and combat. Janitors got outcrept severely. They cannot compete.

>Janitor borgs have to choose between VTEC and Floor buffer upgrades, they cannot have both.

A bit excessive though. Being a janiborg comes with limitations.

>Janitor borgs advanced mop now starts with space cleaner by default.

Cool. That's a nice niche for them to have it.

I like it.

**Comment by S34NW** [comment]
I've been thinking more about this and done some testing, and I think I now see that the overall VTEC speed debuff for all borgs is too harsh. I will amend the PR to remove that change specifically. I'm still on the fence about the janiborg buffer vs vtec issue, and welcome more feedback on it.

**Comment by MRgaty** [comment]
I think sec borgs are fine as they are and I dont really like the changes either so not a fan of this 👎.
Btw please lets be respectful with each other.

**Comment by LightFire53** [comment]
Personally, I do think VTEC needs tweaking down in speed still, but janiborg adjustments are still Gucci.

**Comment by Butlerblock** [comment]
Speed is honest not the issue, it’s what they can combine with the speed that makes secborgs so toxic in gameplay. 
Making them perma slow is just going to force them to rely on disabler spam and bolting doors, which is currently the main issue.
 I can guarantee that if this gets merged the main course of action sec is going to take is drag the borg around so they can a free instant bolting door opening disabler spamming machine of bullshit.

**Comment by S34NW** [comment]
> 
> I can guarantee that if this gets merged the main course of action sec is going to take is drag the borg around so they can a free instant bolting door opening disabler spamming machine of bullshit.

I mean, this is what happens anyway right now. This change will at least reduce the solo sec borg hunting that happens. I've not been able to think of a way to balance door opening/bolting, unfortunately.

**Comment by LightFire53** [comment]
> > I can guarantee that if this gets merged the main course of action sec is going to take is drag the borg around so they can a free instant bolting door opening disabler spamming machine of bullshit.
> 
> I mean, this is what happens anyway right now. This change will at least reduce the solo sec borg hunting that happens. I've not been able to think of a way to balance door opening/bolting, unfortunately.

Could be that there is a 1-2 second "cast time" on bolting/opening doors remotely for cyborgs only, maybe? Or maybe include the door remotes? I think AI should still be able to access and open them as quick as they can click though.

**Comment by Butlerblock** [comment]
Remove the hotkey for every synthetic (including AI) for either bolting or both opening and bolting. It would require the synthetic to manually opening the menu, making it much less viable/possible in a chase and making them less omnipotent on the station.(as much as I love pre-opening doors, it’s pretty broken and lets you get to be anywhere on the station SUPER fast)

**Comment by Samman166** [comment]
> Speed is honest not the issue, it’s what they can combine with the speed that makes secborgs so toxic in gameplay.
> Making them perma slow is just going to force them to rely on disabler spam and bolting doors, which is currently the main issue.
> I can guarantee that if this gets merged the main course of action sec is going to take is drag the borg around so they can a free instant bolting door opening disabler spamming machine of bullshit.

I hate how right you are. It would be better to make bolting doors work like access tuner does and take time. Or make dragging a Borg slow you down.

Also @procdrone you are not wrong that Borgs can be dealt with easy but most of the options require melee range (that is probably for the best) If we want to make things easier to prepare for a craft able one time use flash would give people of any job a way to deal with sec borgies. On laser pointers I disagree that they are a viable counter for antags since there is so few of them 2 for IAA 1 for RD 1 for librarian and I think miners had laser pointers removed from the vendor, 3 of those are hard to get targets and the librarian well I find they usually lose the laser pointer but could just be my in my experience.

But even if you do kill a Borg it can be back in less than 5 minutes sometimes, this is good and bad because means sec can't be completely wiped out but some sort of a cool down would be nice. 

Also also I am quite biased since I never play Borgs

**Comment by shawnhind** [comment]
I would like this PR more if it just removed the floor buffer upgrade for janiborgs and made it an upgrade but didn't touch VTEC at all.  Also why shouldn't janiborg be able to get VTEC and floor buffer upgrades?

Is cleaning really too overpowered?  If the only reason for nerfing janiborgs is to make organic janitors more useful then why not just make organic janitors more useful?  Is cleaning really something that needs close balancing since in 90% of rounds it has no real purpose other than making the station look nice?  Doesn't more effective cleaning for everyone just make the role more fun as a whole?

**Comment by procdrone** [comment]
>most of the options require melee range

I'd say there is an equal number of ranged and melee options to pick out.

>On laser pointers I disagree that they are a viable counter for antags since there is so few of them 2 for IAA 1 for RD 1 for librarian and I think miners had laser pointers removed from the vendor, 3 of those are hard to get targets and the librarian well I find they usually lose the laser pointer but could just be my in my experience.

They are still available in the mining vendor (for 300 points)

**Comment by hal9000PR** [comment]
> They are still available in the mining vendor (for 300 points)

balancing things around one job isn't ideal.

> I'd say there is an equal number of ranged and melee options to pick. 

just because there is equal amount of options doesn't mean that the rarity is the same. EG. a flash is more common than a laserpointer or ion rifle by an order of magnitude.

**Review by Kyep — CHANGES_REQUESTED** [review]
I really don't like this. I'm not a fan of nerfs to borgs in general, and I'm especially not a fan of making them even slower than they already are. I also feel like janitor borgs, for example, might not be played without the floor buffer upgrade. Maybe I'm wrong, but this makes me skeptical.

**Comment by S34NW** [comment]
> 
> 
> I really don't like this. I'm not a fan of nerfs to borgs in general, and I'm especially not a fan of making them even slower than they already are. I also feel like janitor borgs, for example, might not be played without the floor buffer upgrade. Maybe I'm wrong, but this makes me skeptical.

Thanks for giving it some thought. I'm not sure what is meant by "slower than they already are" since with VTEC they move just as fast as organics. With this PR, vtecs would not be available to secborgs, the "slow, heavy hitting" force of a sec team.

I could easily remove the conflict between janiborg buffer and vtec to allow them both, but I feel strongly about buffer being an upgrade. I could also buff janiborg mop to clean faster than normal so they have even more of an edge over roundstart janitors. Then when they get upgrades they still keep pace with an upgraded janitor (buffer+slime speed janicart)

**Comment by S34NW** [comment]
Stale PR. Might incorporate some of the ideas in a future PR adding upgrades to janitor and service borgs.

**Pull request closed without merging**
