### PR TITLE
MetaStation Perma Remap

### PR DESCRIPTION
**Pull request by DogeDogIs**
Remaps Perma in MetaStation. This remap is fineshed but change can be made with sugestions and reviews.

## What Does This PR Do

This PR completely changes the Perma of MetaStation, making it more space for prisoners, and better visibility and security for security officers, and at the same time, better construction to implement on the map.

## Why It's Good For The Game

This PR is made for the perma to be completely redone, since the current perma in MetaStation is bad for both sides, both for those who are in prison, both for the Seucurity Officers, where they have very little access to take care of the prisoners, and the prisoners have very little space.
## Images of changes

Before:
metastationpermaremap
After:
metastationnnn

## Testing

Started Dream Deamon.
Entered the local Host server.
Went to MetaStation, entered as HoS and tested buttons and the map.

## Changelog
:cl:
tweak: Remaped MetaStation perma.
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
Excellent!! Meta needs some reworks, but it’s not as bad as some say. Definitely worth reading perma! May i suggest taking some inspiration from our recent [remap of boxstation perma](https://github.com/ParadiseSS13/Paradise/pull/18272) ?

**Comment by DogeDogIs** [comment]
> 

Yes, I am taking the entire inspiratoin from the BoxStation perma ramap! The Kitchen is entire based on the box station perma. I am going to upddate the files and the pictures shortly, making some final changes!

**Comment by DogeDogIs** [comment]
> > 
> 
> Yes, I am taking the entire inspiration from the BoxStation perma ramap! The Kitchen is entire based on the box station perma. I am going to upddate the files and the pictures shortly, making some final changes!

**Comment by Bm0n** [comment]
This breaks a lot of the stylictic mapping decisions made for Meta and just from a cursory glance I can see quite the number of mapping errors.

Meta isn't Box and I honestly didn't like the fact that Box got a Meta style perma brig in the first place. Now this PR makes both of the maps even more of the same, something I cannot agree with.

**Comment by DogeDogIs** [comment]
> This breaks a lot of the stylictic mapping decisions made for Meta and just from a cursory glance I can see quite the number of mapping errors.
> 
> Meta isn't Box and I honestly didn't like the fact that Box got a Meta style perma brig in the first place. Now this PR makes both of the maps even more of the same, something I cannot agree with.

Well, I don't think that makes the map appear more BoxStation, since it's just a whole place on the map that I've messed with, having the importance of improving the gameplay and conditions for both who is trapped and who is taking care of that place. And besides, I did my best to keep the same "style" as the perma, following the concept of the hallway, which leads to the kitchen, with the rest to the sides, as you may have noticed. And since you saw mapping errors, I think it's good of you instead of just criticizing without giving a suggestion of how to improve, it would be better to criticize and give a suggestion of how to improve, just criticizing will not make any change.

**Comment by LightFire53** [comment]
> This breaks a lot of the stylictic mapping decisions made for Meta and just from a cursory glance I can see quite the number of mapping errors.

We don't have a specific stylistic design written down anywhere for each map. While I'm not opposed to it's creation, holding things to an invisible standard is bad. Mapping errors can be fixed easily, and adjusting things to style is not impossible.

**Review by LightFire53 — CHANGES_REQUESTED** [review]
image

I would recommend making this area not part of perma, and moving the perma blast doors off the lower airlocks and into the perma entrance ones.

image

For parity reasons, this should probably become armoury access to match Cyberiad.

image

A touch overkill on the amount of lights here.

image

This could also be downsized to either one tube or two bulbs. As well, should run some atmospherics into this room

image

Lights on windows is something we are moving away from, could either be moved or the light sources in the room adjusted so we don't have 4 in that area

image

Fire alarm in execution could be relocated to not share a wall with a light

image

Two fire alarms on the same tile in the prison oversight area

image

We could probably make an argument for turning that APC in prison oversight into an important area APC considering the amount of stuff it's powering.

Last thing is that we (more or less recently) learned that apparently the exterior cameras don't need to be in a traditional area, and can function in space/nearspace (I think nearspace anyway)

**Comment by DogeDogIs** [comment]
image
it is now a important APC*

writing mistake lol

**Comment by Bm0n** [comment]
> We don't have a specific stylistic design written down anywhere for each map. While I'm not opposed to it's creation, holding things to an invisible standard is bad. Mapping errors can be fixed easily, and adjusting things to style is not impossible.

There isn't one and there really isn't anyone who has the authority to make one but my issue is with the general style- the _look_ of this map edit isn't good. Compare the old version of perma to the new one:

pr1

The old version is just more aesthetically pleasing to the eye and has a more logical design, while the new one is an assortment of square-shaped rooms with some areas being copy-pasted from Box.

This room is a prime example of what I am talking about, it's straight from Box:
image

There's even a leftover red power cable from when it was copy-pasted 
image

I honestly just don't like this PR and there's still a lot more wrong with it, here's a collage:

image

image

image

PR3

image

PR2

PR4

PR5

No lattice under this new grille spawner

image

There isn't even a point for there to be lattice up here in the first place, the only reason it was there in the original was to protect the northern windows which no longer exist

image

Can't use the tray/biogen, it's being blocked in.

PR6


Even with all that fixed I still think the old version is aesthetically better. May I suggest using the old version as a guide and instead reworking the internal layout of it instead?

**Comment by DogeDogIs** [comment]
> 

Look, I'm glad to see you learned that we need to make a suggestion instead of criticizing for changes to happen, people don't get it right the first time, right?

Well, let's start, first I know that everyone has their opinion, you didn't like the remap, it's ok, but to say that the before was better to look at, it's certainly a mistake to say that, first the old one was very closed and clautrophobic, while the botany was smaller and was housed in a place that was simply horrible to enter the door, comparing with the new one we can see the real difference. About the "copypastes" I made, it was just the racks, so I can save my time and don't forget to add some stuff to it, and about the area of ​​opening the airlocks to get into the perma, yes, I took the reference of the Box, because for some reasons, first, this style works, it's not for nothing that I got the reference directly from the boxStation, it works and does its role well, second, it's beautiful, it's not ugly to look at, it's the size good and sure everyone should like it. The map doesn't have the famous "circles" that the meta has, I, in my opinion, don't like to make curved rooms that don't have a significant importance, for example, the perma, but of course, everywhere in the map needs a touch of decoration and be made with love.

So, thanks for the suggestions and I'll fix everything you said. You saw how just criticizing wouldn't make a difference, and I know I may have been wrong in some places, but even you've been wrong in some PR, haven't you? Thanks!

**Review by S34NW — CHANGES_REQUESTED** [review]
Opinion:

I'm not overly sure we should move all stations to be more like box in these ways, each station having a unique setup is advantageous and a positive. Delta perma could do with a facelift though. Meta was similar enough to box (it being the inspiration for box remap) but still distinctly different in the systems available, these changes seem a bit needlessly unoriginal to be perfectly honest. You could make the QoL argument, and I agree for the kitchen to have a similar equipment set to box is fine. The changes to the perma entry area however were not needed as Meta already had a distinctly different two-layer entry system.

I'm personally not a fan of these changes overall, but agree that some of the changes are a positive. 

Objective Review Time:

image
Please do not run wires and pipes over grass.

image
Keep this pipe simple and connect it north to cut down on pipe runs.

image
Both these doors are labelled Solitary 1

image
You have both lockdown shutters and lockdown blast doors with similar name schemes. This is guaranteed to cause confusion to sec players, keep it to one system and lose the shutters over the window overlooking the airlock system.

image
This camera does not follow the naming scheme used by the rest of the room's cameras.

image
Your prison intercoms do not follow the standardised intercom bump offsets

image
Your wire setups here are confusing and not standard practice. Also the scrubber and vent pipe setup can be simplified.

**Comment by S34NW** [comment]
> So, thanks for the suggestions and I'll fix everything you said. You saw how just criticizing wouldn't make a difference, and I know I may have been wrong in some places, but even you've been wrong in some PR, haven't you? Thanks!

Also It's not my responsibility to comment on github interactions. But this sorta attitude is a bit grim, bmon may be direct in the way they give feedback but they are voicing an opinion born from experience. It would pay to not be smarmy with fellow mapping contributors.

**Comment by DogeDogIs** [comment]
maybe someday?

**Pull request closed without merging**
