### PR TITLE
Chem Boom Nerf

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Nerfs Chemical Explosions

-Forces chemical grenades to obey the bomb cap (meaning no more nitroglycerin+bluespace beakers wiping an entire department off the map); the max size explosion you'll be able to attain will be 3,7,14 (just like with plasma bombs).
-Removes the snowflake code for explosive reactions taking place inside mobs; this means that 40 units potassium pill+40 units water pill won't gib the mob anymore, instead it'll create an explosion just as if it had taken place inside a beaker or any other reagent container. Now, two 50 unit pills (one of potassium and one of water) will result in a size -1,0,2 explosion and deal around ~30 brute damage to the mob the reaction took place in. It'll still be incredibly useful if you can pull it off,, it just won't be cheap-win ridiculous anymore.

Update
-Updates the flash powder code so it's not so ridiculously snowflake; also brings its stun/weaken durations to more realistic values similar to flashbangs instead of a crazy weaken duration of 15; it now stuns you if you're 5 tiles away for 5 ticks; 4 tiles or closer and it weakens you for 5 ticks.

### CODE REVIEW

**Comment by Regen1** [comment]
I am in favor of removing the snowflake code, but I believe an explosion that happens INSIDE you would very much kill you.
Gibbing? No, organs smashed into soup, ribcage blown open and guts everywhere? Yes

**Comment by ZomgPonies** [comment]
~30 brute damage is way too weak for the power of the explosion. Crit but not deadly damage would be more appropriate, maybe increate the explosion size by 25% also. Something like 0,1,3.

**Comment by Fox-McCloud** [comment]
The explosion damage is the same exact amount as would be generate by throwing a 50+50 water and potassium grenade at the person and it took place on the same tile as them.

The snowflake code just to determine which ex_act level would occur for the holder mob, which effectively meant that the actual explosion would never happen, but they suffer an ex_act level (which is just damage); with this change you can still gib a mob with the nitro recipe (50 unit pills of each would result in a max size explosion occurring at the mob); it's really just potassium+water that's been nerfed in terms of gibbing.

**Comment by ZomgPonies** [comment]
Sounds good then. Thumbs up or whatever that emoji is.

**Pull request merged**
