### PR TITLE
Fix voxes n2 tank overriding items in hands

### LINKED ISSUE #8615: Vox Chaplains don't spawn with a bible
**Problem Description**:
What is the problem?
If you are a vox chaplain, your spawning bible doesn't appear in your hand. This is presumably because Vox spawn with the voxygen tank in the same hand as where the bible spawns. 

**What did you expect to happen**: 
Why do you think this is a bug?
Normally when you spawn as a chaplain, you have a bible in your hand.

**What happened instead**:
How is what happened different from what you expected?
As a vox, you do not spawn with a bible in your hand.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
This means that vox chaplains don't have their custom bible on their person at roundstart. The custom bible is incredibly useful. They can still print a bible at the library, but this is very annoying.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1) Be a vox.
2) Spawn as a roundstart chaplain.
3) Notice your lack of bible.
4) Cri

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### LINKED ISSUE #9120: Voxxy spawns with no first aids kits!
**Problem Description**:
When you latejoin (probably same when you join from beginning of game.) as vox medical doctor, you have your vox tank in your hand which replaces red first aid kit which medical doctors should get, pretty much deleting the kit.

**What did you expect to happen**: 
To spawn both with first aid kit and specialized n2 tank.

**What happened instead**:
Only specialized n2 tank spawned, and no first aid kit.

**Why is this bad/What are the consequences:**
Deletes first aid kit item on spawn.

**Steps to reproduce the problem**:
1. Be voxxie.
2. Join games, pick medical doctorings as job.
3. Is has voxxygenes in hands, but no first aids kits nowhere to be seens!!
4. **SCREEE**

### PR DESCRIPTION
**Pull request by alexkar598**
Fixes #8615 
Fixes #9120 

:cl:alexkar598
bugfix:Vox's nitrogen tank will no longer override items in hands.
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
This doesn't fix it as much as it just gets around the issue by not making any uniforms that are commonly used put anything in the hand slots

**Comment by alexkar598** [comment]
This is the best option performance wise,doing checks to see if we can put items in hands and in which hand to place it is a task that requires quite alot of if statements,putting it in the backpack/belt slot,while not the fanciest option is a better way for lag removal and further developpement of features that may occur at round start

**Comment by tigercat2000** [comment]
`best option performance wise` this is literally not true

**Comment by alexkar598** [comment]
Verifying if items can be equipped to slots take about 7 checks,if there is a better way then tell.

**Comment by Crazylemon64** [comment]
Citing "Performance" for a handful of conditional checks is laughable. Find a better excuse.

**Comment by taukausanake** [comment]
Ca't we just have job items spawn in one hand, the rest in the backpack, and then a specie specific item, if any, in the other? It almost looked like there was a _decent_ system for spawning in items for each job, maybe just make it more explicit for both jobs and species

**Comment by alexkar598** [comment]
This isin't stale,no one told me about why and/or how this should be changed.

**Pull request closed without merging**
