### PR TITLE
Adds decorative telecomms machinery for map making

### PR DESCRIPTION
**Pull request by Crazylemon64**
I didn't realize this map (The VR lobby) had actually functioning telecomms machinery! This fixes that.

### CODE REVIEW

**Comment by taukausanake** [comment]
That map still doesn't actually do anything yet, correct? Just asking because curious

**Comment by Crazylemon64** [comment]
Yeah right now it's something accessible only with an admin-only item

**Comment by SamHPurp** [comment]
@taukausanake it does work, just admin only... and afaik only the Roman arena exists.

The man developing it has disappeared though, maybe school/studies?

**Comment by alexkar598** [comment]
I wanted to continue the vr project but I stopped working on it and I will maybe try again at make it work

**Pull request merged**
