### PR TITLE
Makes surgery great again, part 2. (nerfs spaceacillin)

### PR DESCRIPTION
**Pull request by Vivalas**
Alright, so a long time ago in that nice big vaunted organ PR (#2885), spaceacillin was given a hardcore buff for infections. Now, I dunno if this was a stealth thing or not since from my limited skim of the 300 comments, none of them pointed this out, but as it stands now as a result of this PR, believe it or not, you can fix *every single infection in the body, internal, external, septic, WHATEVER, **with only 25u of spaceacillin***. 25u of spaceacillin is roughly 2 syringes worth. Every infection. No washing the organ under the sink, transplanting septic hearts etc., cloning patients, or using ethanol, just 25u of spaceacillin will do the trick.

Now, since this wasn't mentioned in the PR (I think), is not mentioned in surgery guides (which still alludes to having to use "every syringe of spaceacillin in medbay" to treat an internal organ), and is probably not well known by most medics, I'm "nerfing" spaceacillin.

Basically I've cut its effectiveness in half (the PR quadrupled it's effectiveness), and caused healing infections to consume more spaceacillin per tick per organ being healed (0.1u).

Just some numbers for infection healing - post nerf (pre nerf):

Healing one acute external infection will require about 12.5u of spaceacillin (4u).

Healing one septic external infection will require about 70u (25u).

Note surgery for external infection cleansing is pretty simple, just scalpel and cautery, otherwise you'll need a lot of spaceacillin.

Healing one acute organ infection will require 25u of spaceacillin (4u). 

Healing one septic organ infection will require 135u of spaceacillin (25u). Internal disinfection or transplantation might be easier than collecting 135u from the vendors.

These are the numbers for two infections:

Acute external: 16u (4u)
Septic external: 90u (25u)

Acute internal: 33u (4u)
Septic internal: 180u (25u).

Healing all acute external infections (each part of the body) will consume about 55u of spaceacillin.
Healing all septic external infections will consume about 300u of spaceacillin.

Healing all acute internal infections will consume about 66u of spaceacillin.
Healing all septic internal infections will consume about 360u of spaceacillin.

Comments, balance concerns, rage, and suggestions are welcome for these numbers but the current values (25u for cure-all) is a bit unacceptable IMO.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
It is my firm belief that while medicine may enhance the general experience of our players, too much of it will make it numb and boring for both the doctors and the victims.

It's not challenging to rinse someone's appendix before sticking it in his skull, it's just complication for the sake of complication.

Yes, as it stands all the things you could possibly do to avoid an infection are basically useless, but I feel this is not the fix the whole situation needs.

**Comment by Vivalas** [comment]
The idea is not to make dealing with infections super difficult, but to make it actually somewhat challenging. Injecting someone with two syringes of a drug to completely any and all infections in their body feels way too hugbox for me.

I don't believe surgery is needless complication, surgery is having to spend extra time in medical if you really get fucked up. It (supposedly) takes 15 minutes to go from mild to acute infections, and it takes longer to go from acute to septic. It takes a while for infections to get to the "shit we fucked up part" provided they are treated early enough.

Avoiding infection is actually pretty easy if you just follow all the procedures and dress your wounds before they get infected, but external infections are still basically super-easy to cleanse.

**Comment by EvadableMoxie** [comment]
I think the degree to which this is nerfed is a bit much.  I mean, if they realized they had an infection and got 25u of spaceacillin into them, they probably already are receiving medical care, so that point they should recover. There's no need to drag it out.  Maybe 25u is too little, but 585u is just ridiculous. 

Personally, what I'd do instead is make the surgical option easier instead of making the medical option harder.  Then make the medical option inefficient while making the surgical option very efficient, and pressure Spaceacillin supplies so that this actually matters.

To make surgery easier, what if you could use Spaceacillin during organ manipulation like you can Ethanol, except 5u of Spaceacillin applied surgically clears any infection in the organ instantly due to being a targeted application? 

To pressure the Spaceacillin supply, have less of it, or none of it at all at round start. Currently there is a total of 360u combined in the 4 MedVends at round start, which is usually more than Medbay ever needs, and that's not counting medical borgs that have infinite amounts of it.

If both were done, Doctors would have the option or just injecting Spaceacillin with a syringe which would eventually clear the infection, or doing it surgically to clear it instantly and with less Spaceacillin.

As an aside: I'm glad you are putting RPs like this up to deal with some of the more glaring inconsistencies in the medical system.  While we're talking about making surgery great again, I want to point out that currently organs being 'DEAD' means nothing, since you mentioned Mito splashing.  The only thing that matters is the raw level of damage, the DEAD flag isn't checked, or if it is that code is broken so the check does nothing.   So, there's no reason to ever transplant someone's organ with a new one, or splash it with mito. This is a pet peeve of mine, along with heart damage doing nothing.

**Comment by Crazylemon64** [comment]
@Vivalas #2885 was the Spaceacillin 4x buff, which proclaimed it did such in the OP. The PR was my doing.

Prior to that PR, the general strategy for "treating" someone with an infection was to let them die and go through the cloner, since it was prohibitively expensive to treat an infection. In addition, Medical had only 180u of spaceacillin before that PR (it doubled the supply in the vendors)

Keep in mind that reducing the 360u supply of spaceacillin will require chemists to hunt down space fungus to make it, and each patch of fungus supplies only 10u of fungus (or 20u of spaceacillin). (You could also get botany to produce fungus, though such a relationship might be difficult to arrange)

**Comment by Crazylemon64** [comment]
@EvadableMoxie I thought that heart damage reduces the effective amount of blood when checked in the blood updating systems? Meaning earlier oxygen loss, wooziness, and unconsciousness, as well as earlier death if things got too bad blood-wise?

**Comment by EvadableMoxie** [comment]
If it does, the effect is mild enough that I've never noticed it.  I got a monkey to a 60 damage dead septic heart by letting an infection progress and it was fine.  It had 100% blood so maybe that's why?

**Comment by Crazylemon64** [comment]
@EvadableMoxie If the heart dies, they *should* have a heart attack. Do they not?

**Comment by EvadableMoxie** [comment]
I broke a test subject's ribs and dragged them around to see.  They died when the lungs died, but they were fine when the heart died.

**Comment by Crazylemon64** [comment]
@EvadableMoxie "Fine" as in they didn't immediately die, or they showed up as 100% even 20 seconds after their heart had died?

**Comment by EvadableMoxie** [comment]
Fine as in 0/0/0/0 damage across the board for a good 2-3 minutes.

**Comment by Vivalas** [comment]
@EvadableMoxie The 585u thing was a calculation mistake I made because I was using the same 12 organ formula for internal organs, when there are only 7. It takes 360u to heal all internal infections if they're all septic, which is an unrealistic scenario that would likely never happen.

**Comment by Vivalas** [comment]
@Crazylemon64 I checked the Blame and for some reason it was Fethas's organ thing, hrm. I don't know if you changed the behavior of antibiotics other than 4x more effective thing, but internal infections shouldn't have been any harder to treat than external infections, unless that difference was removed somewhere.

**Comment by Crazylemon64** [comment]
@Vivalas They were always as easy to treat as the other

**Comment by Vivalas** [comment]
Then Fox's comments in that PR were completely false, since mild internal infections should have been as easy to treat as external infections.

**Comment by Crazylemon64** [comment]
I think what Fox meant was referring to external infections severe enough to hit internal organs - if that happens, then it's to the point where fixing the patient is prohibitively expensive.

**Comment by Vivalas** [comment]
Infections become severe enough to spread at INFECTION_LEVEL_TWO, which are "acute" infections, which is at germ_level 500. At germ_level 500 they could have been treated with 16u of spaceacillin, which would have also treated any internal infections. On a side note I think I messed up the comparison two old values, since they don't exactly align, but either way this system is still twice as effective as the old system, just that it gets costlier with more infections being treated at once.

**Comment by karmapay2win** [comment]
Well ss13 is technically an MMO, I was wondering at what level the numbers get multiplied by ten.

**Comment by Vivalas** [comment]
I don't think that's a valid argument, SS13 is not really a MMO but more of a multiplayer online sandbox, which includes a complicated and in-depth medical system. Like broken bones pre-splint nerf, severe infections shouldn't just be a slap on your hand and a quick injection before your health bar regenerates to 100% and you're golden.

**Comment by Tayyyyyyy** [comment]
I think @EvadableMoxie's idea for injecting spaceacillin directly into the infected organs makes the most sense. I remember when I first had to deal with infections that was what I thought you had to do too. It's intuitive and requires more skill to use rather than straight up nerfing it.

**Comment by Vivalas** [comment]
I think that would work nicely with this nerf, external infections aren't that heavily affected until they get to the septic level, and one acute internal organ infection can be cured with 3 syringes worth. Making it only take 5u if injected in would make it a good tradeoff for having to cut them open, and then you can inject them spaceacillin to clear the rest of the infection from their body.

**Comment by alexkar598** [comment]
The internal organ is okay as is apply ethanol to an organ takes a lot of time but for the external I don't care

**Comment by MischievousGremlin** [comment]
Higher dosages needed does not make it challenging. Adding more clicks just adds more clicks.

**Comment by Vivalas** [comment]
Closing this since I'm taking a different approach to it that revolves around @EvadableMoxie's comments.

**Pull request closed without merging**
