### PR TITLE
Add new visually appealing sprites to replace the existing trenchcoat and fedora sprites

### PR DESCRIPTION
**Pull request by Stokes52**
## What Does This PR Do
Adds all new sprites made by me to replace the old trenchcoat and fedora sprites.  Changes the following sprites:
* Black Fedora
* Black Trenchcoat
* Detective Fedora
* Brown Fedora
* Brown Trenchcoat

## Why It's Good For The Game
It looks much better.

## Images of changes
Trench_Fedora

## Changelog
:cl:
tweak: Edited the sprites for the trenchcoat and fedora
/:cl:

This is my first contribution to Paradise. Please let me know if I need to format or change anything. 

The hat is supposed to cover the eyes in the "down" position for that extra "Noir detective" look. It's modelled similarly to the cowboy hat.

Suggestions and opinions welcome. Thanks.

### CODE REVIEW

**Comment by S-CR** [comment]
Much improved, I like the changes to the coat especially.

**Comment by KasparoVy** [comment]
Godspeed, looks great

You able to apply the same changes to the Vox & Grey species-specific versions too?

**Comment by Stokes52** [comment]
vox

@KasparoVy Added another commit with a coat for the vox.  I couldn't find a special version of the hat for vox, or any special hat/coats for greys.

**Comment by AffectedArc07** [comment]
There are rogue pixels in your edits. Please fix.
image

**Review by variableundefined — CHANGES_REQUESTED** [review]
See above

**Comment by Stokes52** [comment]
@AffectedArc07 @variableundefined 

Fixed rogue pixel on the vox jacket.

Slightly modified button location to look more realistic. Example:

trench2

**Comment by Stokes52** [comment]
Edit: Missed one, one sec

**Comment by Stokes52** [comment]
Okay, there we go.

**Review by variableundefined — APPROVED** [review]

**Comment by Kiyahitayika** [comment]
>I couldn't find a special version of the hat for vox, or any special hat/coats for greys.

@Stokes52 The reason you didn't find them is because they don't exist. They don't exist _yet_. If you're willing to add them into the .dmi files for Grey and Vox and adjust them as necessary, it would be **massively** appreciated. That said, this is your first PR and it's okay if you don't include that. You can always fix them another time or someone else can help with it later. These sprites already look so awesome!

**Comment by Stokes52** [comment]
@Kiyahitayika I should be able to add hats for vox pretty easily.  I can take a look at greys later too. If I don't get to it for this PR I can circle back later and do a species pass.

**Comment by Stokes52** [comment]
vox_fedora
Some clipping is unavoidable with vox hair, but at least it sits on his head.

I also added a sprite for the white fedora, and I updated the inventory sprites to match the nice detective sprite.

**Comment by Stokes52** [comment]
Force pushed to fix merge conflicts.

**Comment by Stokes52** [comment]
Okay, I think everything is ready to go, unless any other changes are required.

**Comment by variableundefined** [comment]
Will merge when a head approve

**Comment by Spacemanspark** [comment]
This is awesome

**Pull request merged**
