### PR TITLE
Adds a patreon fluff item to the game.

### PR DESCRIPTION
**Pull request by HugoLuman**
As the title says. It's the children's beadspread of _the future_
backcape backcape2

Signed-off-by: HugoLuman <qaggeler@uci.edu>

### CODE REVIEW

**Comment by DesolateG** [comment]
picture?

**Comment by HugoLuman** [comment]
@DesolateG I kinda don't want to announce to everyone who plays the character that will use it. I've sent the pics to the heads though.

**Comment by Spacemanspark** [comment]
We can see all of that via glancing into the code, you might as well put a picture in.

**Comment by taukausanake** [comment]
That is a very pretty bedsheet though. I could think it could use some super dark purple in there but it looks well detailed as it is

**Comment by Spartan6** [comment]
Nice looking bedsheet.

And you're just making it slightly harder to see by not putting a picture in the OP. Public code man.

**Comment by HugoLuman** [comment]
Eh, fine

**Comment by ktoma36** [comment]
This is magnificent

**Comment by SamHPurp** [comment]
Jesus, that looks startling, over the top and out of place.

**Comment by FlattestGuitar** [comment]
this is pretty :o

**Comment by KasparoVy** [comment]
It's nanofabric, my dudes.

**Comment by taukausanake** [comment]
Seeing the actual animations now rather than the static icons, I want one now. Hell, I want a real one now

**Comment by ktoma36** [comment]
Omg it needs a matching suit and top hat, possibly a cane :D

**Comment by tigercat2000** [comment]
Absolutely amazing. I want one. :+1:

**Pull request merged**
