### PR TITLE
Rad collector - No streaks of light

### PR DESCRIPTION
**Pull request by DogsParadise**
This is 1 of the two versions, I will PR for the rad collector, opinions seem to differ too much.
This is the PR without streaks of reflection in the glass.

Link to other PR: https://github.com/ParadiseSS13/Paradise/pull/15820

**Alternative PR to #15665**

## What Does This PR Do
It changes the rad collector to the new perspective and updates the look to fit the new TG style more.

## Why It's Good For The Game
Current sprite isn't in the correct perspective and just generally outdated.
Sprite that might get merged from TG, looks weird and off.
TG themselves don't think it's a great sprite either, from what I have heard on their discord.

## Images of changes

New:
image

image

Animated + lights added:
https://gyazo.com/09f0c02571fb6bfefc90e84558737a07

Old:
image

TG:
image

## Changelog
:cl:
tweak: Changes radiation collector sprite
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
I prefer this one to #15820 personally

**Review by dearmochi — APPROVED** [review]

**Review by Dumbdumn5 — APPROVED** [review]
This sort of edit is exactly what I approached fox with in the old PR. I like this alternative because it's cleaner while still being updated and it fits with the aesthetic of the rest of the sprites far better. 👍

**Comment by SteelSlayer** [comment]
One thing that needs to be addressed is the plasma tank overlay. Currently it looks like this: 

image

It doesn't match up to slot properly and is overlapping the metal bit. I suggest modifying that sprite to fit yours.

**Comment by DogsParadise** [comment]
> One thing that needs to be addressed is the plasma tank overlay. Currently it looks like this:
> 
> image
> 
> It doesn't match up to slot properly and is overlapping the metal bit. I suggest modifying that sprite to fit yours. Or not I guess, if you're happy with how it looks.

The current one is exactly like this?
Tried sticking to that one :eyes: but i can change it if it's preffered

**Comment by SteelSlayer** [comment]
> The current one is exactly like this?

Yep this is what the current tank overlay looks like using your collector sprite. I suppose it doesn't actually look that bad. Up to you if you want to change it or not.

**Comment by DogsParadise** [comment]
> > The current one is exactly like this?
> 
> Yep this is what the current tank overlay looks like using your collector sprite. I suppose it doesn't actually look that bad. Up to you if you want to change it or not.

I am being an idiot, sleep deprived. was reading the general sprite not the tank. Gonna adjust it

**Comment by DogsParadise** [comment]
> One thing that needs to be addressed is the plasma tank overlay. Currently it looks like this:
> 
> image
> 
> It doesn't match up to slot properly and is overlapping the metal bit. I suggest modifying that sprite to fit yours. Or not I guess, if you're happy with how it looks.

updated, looks like the one from TG now.

**Comment by variableundefined** [comment]
TG sprites were merged in. Closing.

**Comment by SabreML** [comment]
@variableundefined The TG sprite PR is still open: #15665

**Comment by DogsParadise** [comment]
> TG sprites were merged in. Closing.

Tg sprite hasnt been merged in??

**Pull request closed without merging**
