### PR TITLE
R&D Rework Redux

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Implements #17756

Or atleast it will. This is a holding PR to make 20,000 something special, plus now that I have this its motivation to get it done.

ROUGH ORDER OF WHAT NEEDS DOING:
- [x] Implement better management of R&D networks (have the computers store data, leave servers idle for now)
  - [ ] Give free golems and thetasation their own R&D networks - and do all the mapping stuff
  - [x] Give the station an R&D network
  - [x] Make the server control console more advanced with R&D network manipulation and device linkage a-la tcomms and multitool soft refs
  - [ ] All the TGUI stuff
  - [x] Make the console harder to destroy (maybe put it somewhere safer to avoid griefing, or have it be on a distributed backup across the station, store in blackbox maybe??)
- [x] Implement a way to increase R&D levels by a points system (amount of points per level determined by an equation, ask a mathlete like charlie or corn to do that one)
- [ ] Convert the DA into something that can generate points from strange objects as well as unlock illegal research if given a sufficiently strong item
  - [x] Illegal tech will have a **much** stronger point scaling
- [ ] Add other point gain mechanisms (xeno core thing, botany plant thing maybe, chem machine, all of these need diminishing returns)
- [ ] A lot of testing to make sure nothing goes wrong as well as point scaling

## Why It's Good For The Game
R&D is in dire need of a rework, this will be it.

## Images of changes
TBD

## Testing
TBD

## Changelog
:cl:
add: Massively overhauled R&D - please click the PR in the changelog and give it a read
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
This PR currently will not compile. That is fine. It also wont be tagged as part of the mapping queue. That is also fine. I plan to open a disposable PR in the future when this one is done for the purposes of map queue tracking, since this thing jumping it despite being old isn't fair. 

---

The first commit is in, and a lot of stuff is still to be done, but I have made a base of an R&D network controller which the machines need to tie into a-la tcomms to make this code more bearable.

After that, I can start integrating machines into it, and use that as a means of generating research points.

**Comment by AffectedArc07** [comment]
Progress report:
- Devices now have full linkage functionality
- Consoles & Mechfabs have the TGUI in place to link to R&D controllers
- Servers have the code in place for pointgen, they still need their TGUIs
- We have fancy TGUIs and a working network system, thats major progress

---

Next steps are, in order:
1. Make the console backup system
2. Do an equation for R&D level scaling based off of points
3. Rework the destructive analyser into the object analyser as outlined in the document
4. Add the other misc pointgain machines
5. Push PR for TM

My goals are in sigh

**Comment by AffectedArc07** [comment]
R&D servers now have a TGUI, and they can now be linked and unlinked to network controllers. 

There's lots to do still, mainly:
- Making sure network names cant be duplicated
- Console backup
- Proper point generation scaling
- Chem decomposer
- Slime core consumer
- The destructive analyser becoming the scientific analyser
- Making strange objects have the following opens in the SA:
    - Discover (consumes research points, grants object power)
    - Investigate (consumers research points, explains what the object will do)
    - Consume (generates research points, destroying the object)
- Making specific uplink items unlock illegal tech on the R&D network
    - This will need fine tuning to allow illegal research to be levellable at all, maybe have much bigger exponential point scaling
    - Same applies for alien tech
- An ungodly amount of testing

This is what I am doing in order. This project will be complete, I just need the time.

**Comment by S34NW** [comment]
No commits in over a month and a half, marking as stale.

**Comment by AffectedArc07** [comment]
Backup console is done
image

The biggest hurdle has passed

**Comment by AffectedArc07** [comment]
image

Point spending framework is done. It needs work and the maths needs sorting, but that can wait or be done by someone else while I work the rest of this out.

**Comment by AffectedArc07** [comment]
This will come back.

I just dont know when.

**Pull request closed without merging**
