### PR TITLE
forceMove refactor

### PR DESCRIPTION
**Pull request by monster860**
Replaces instances of `loc = blah` to `forceMove(blah)`

### CODE REVIEW

**Comment by tigercat2000** [comment]
not all `loc = ` needs to be `forceMove()`, and not all should be, forceMove() is very intensive comparitively

**Comment by monster860** [comment]
Such as?

**Comment by Fox-McCloud** [comment]
Yeah, what Tiger said.

It's better to address individual `forceMove` problems as they come up/are noticed, rather than just replacing all loc setting, directly.

**Comment by VampyrBytes** [comment]
@monster860 
As an example, I used ```loc = ``` in my emote refactor yesterday. It was moving a newly created object from null space into a mob's contents. My first instinctr was ```forcemove``` but then I realised there was no point... there was no ```entered()``` or ```exited()``` to be called, and there was no lighting to deal with (unless the mob had been eating flashlights :wink:)

**Pull request closed without merging**
