### PR TITLE
adds the judge armor and helmet

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
Adds the judge armor and helmet
Judge armor and judge helmet are in the secdrobe, for 100 and 75 credits respectively 
Sprites made by ATP Engineer
## Why It's Good For The Game
Judge Dredd is cool and more clothing options are good

## Images of changes

Screenshot 2023-03-11 144013
Screenshot 2023-03-11 143954
Screenshot 2023-03-11 144110
Screenshot 2023-03-11 144045

## Testing
it works

## Changelog
:cl: ATP-Engineer
add: the Judge armor and helmet, available in a secdrobe 
/:cl:

### CODE REVIEW

**Comment by Denthamos** [comment]
Looks neat but seems a bit too fancy and away from the normal security look to be commonly accessible for sec.  Not sure how to feel on that aspect.

**Comment by Peakwastaken** [comment]
> Looks neat but seems a bit too fancy and away from the normal security look to be commonly accessible for sec. Not sure how to feel on that aspect.

Maybe making it part of the contraband section of the vendor would make sense

**Comment by Sirryan2002** [comment]
Not in favor of this being a normal option in the secdrobe. Would rather see it added to the contraband section or put into the costume vendor.

**Comment by GDNgit** [comment]
Moved to the contraband section, only got 1 of each in stock per vendor

**Review by Sirryan2002 — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Comment by QuacksQ** [comment]
One of the sprites of all time

**Pull request merged**
