### PR TITLE
Quick fix for invisible peacekeepers

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Keep the peace while keeping visibility.

Custom borgs will now have a default peacekeeper sprite.
- You may submit a custom one at any time to add to your existing custom sprite set.
- Desolateg has submitted a few new sprite updates along with his peacekeeper sprite, picture below.

This PR is only an update to the custom_synthetics sprite file.

image

:cl:
bugfix: Custom sprite borgs will no longer turn invisible when becoming peacekeepers.
sprites: Adds/updates custom borg sprites for desolateg to better cover the modules he was missing.
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
How many copies did you have to add? Lol

**Comment by taukausanake** [comment]
I counted eight. Why is this being done? Shouldn't there be a more code-based solution?

**Comment by FalseIncarnate** [comment]
The "code-based solution" is to essentially make an exception for a single module to not follow the normal custom sprite code, which honestly felt hackier than simply adding new states for each.

Additionally, I'm fairly sure that only like 2 or 3 of those people actually still play, so while I could have simply left off states for some people, I felt it was just better all the way around to add the additional couple and not need to worry should they suddenly reappear.

**Comment by taukausanake** [comment]
I am kind of confused. These are placeholders for custom borg sprites for users? Custom sprites that were not there before? I hate asking dumb questions but this is going to eat me up until I learn

**Comment by DesolateG** [comment]
@taukausanake the code looks for these sprites in the .Dmi. with the addition of peacekeeper borgs new sprites needed to be added to the Dmi for peacekeeper.

**Comment by taukausanake** [comment]
Okay I see now. Job variations for custom sprites. That's weird

**Comment by DesolateG** [comment]
@TullyBurnalot

**Comment by Crazylemon64** [comment]
Obsoleted by #8170

**Pull request closed without merging**
