### PR TITLE
Map: [DELTA] General Fixes

### LINKED ISSUE #23014: Mapping Issues Deltastation
**Issue Description**:

Missing cable in virology: X191, Y058
image
Missing cable to vacant office: X140, Y195 to X145 to Y195
image
Extra cable outside of SM atmospherics:  X105, Y175
image
Extra cable into gravity generator: X85, Y142 to X87, Y142
image
Missing cable in QM officer: X178, Y166
image
Extra Cable under door in Escape Shuttle Hallway: X149, Y65
image
Missing Cable under door to Security part of escape: X155, Y61
image
Missing Lightswitch in Botany
image
Missing Lightswitch in Kitchen
image
Missing Lightswitch in Mining Dock - Visible switch belongs to Cargo Bay
image
Missing Lightswitch in Vault
image
Missing Lightswitch in Eva Storage
image
Missing Lightswitch in Research
image
Missing Lightswitch in Cloning and Genetics Lab
image
Missing Lightswitch in Exam Room and Medical Storage
image
Missing Lightswitch in Fitness Room
image
Missing Lightswitch in Wardens Office
image
Missing Lightswitch in Courtroom
image
Missing Lightswitch in Medical Reception
image
Missing Lightswitch in Medbay
image
Missing Lightswitch Atmospherics
image
Missing Lightswitch Engineering Control Room
image
Missing Lightswitch Fore Primary Hallway
image
Missing Lightswitch Central Primary Hallway and Central Primary Hallway (south)
image
Missing Lightswitch Port Primary Hallway
image
Missing Lightswitch in Starboard Primary Hallway
image
Missing Lightswitch Aft Primary Hallway
image

**What did you expect to happen**: 

For things to not be missing, or exist additional off where mapping standards are

**What happened instead**:

Things are missing or missplaced

**Why is this bad/What are the consequences**:

They should be there

**Steps to reproduce the problem**:

Go to location, and see if things missing are missing, or things that should not be there, are there.

**When did the problem start happening**:

Unknown

**Extra information**:

### PR DESCRIPTION
**Pull request by Oyu07**
## What Does This PR Do
Will update overtime as the Kitchen and Atmos remap comes in, alongside other updates

1. fixes #23014 - Exception, No lights on hallways and Atmos area, leaving that for atmos area rework
2. Moves wires to follow atmos pipes
3. Wires no longer pass over scrubbers and vents (Please tell me if there is an actual design decision for this, cause its the same for cyberiad and it just looks really weird)
4. Fixes some missing atmos pipes (turns out mime supply is not connected at all)

## Why It's Good For The Game
1. Fixing requested
2. Consistency of wires and pipes
3. General fixes

## Images of changes
**LIGHT SWITCHES**
Please check mapdiff bot for that

**OLD**

**NEW**

**WITH ATMOS**

**CABLES ALONE**

**WITH DOORS**

## Testing
**NOT YET**
1. Load ss13
2. Open delta
3. Check all new light buttons
6. Lots of map scrolling

## Changelog
:cl:
fix: [DELTA]Light Buttons on Medbay - Science - Bar - Botany - Kitchen
fix: [DELTA] Mime vent not connected to supply pipe
tweak: [DELTA] Moved wires to match the pipe layout and vice versa
/:cl:

### CODE REVIEW

**Comment by Oyu-De** [comment]
It is a draft for now, still doing work, just wanted it to put it on for early comments.
I am very much new to mapping, so please be patient with any "obvious" mistakes, 
I started doing this from the issue report, but the pipe/wire mismatch draw me mad so here we are

**Comment by Henri215** [comment]
image
That "add:" is probably a "fix:" and its a good idea to specify waht station those changes are from.

**Comment by Oyu07** [comment]
Need to check all calbes / atmos pipes to make sure they did not get screwed over the multiple pr's

**Comment by Oyu07** [comment]
oh god the commits got fucked
need a second

**Review by Henri215 — CHANGES_REQUESTED** [review]
image

There is already a vent here.

**Review by S34NW — APPROVED** [review]
Map looks fine to me, no doubt any issues missed will be promptly reported :kek:

**Pull request merged**
