### PR TITLE
Attempts to fix CI by removing filters from mutable_appearance

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

This may fix CI as well keep the fix that might be reverted in #23499 if this does not work.

## Why It's Good For The Game

Return of UI bugs is horrible

## Testing

Compiled

### CODE REVIEW

**Review by Contrabang — COMMENTED** [review]
The reason this was added was because I requested that when they made the PR that changed this, that it include overlays. I think using filters was their version of making that work. Perhaps we need to add the overlays manually.

**Comment by ppi13** [comment]
Ran CI 10 times since i woke up, and it passed 10 times. 

Filter implementation appears to be the issue, and most likely have to use `add_fillter` and `remove_filter` instead.

**Comment by S34NW** [comment]
> Ran CI 10 times since i woke up, and it passed 10 times.
> 
> Filter implementation appears to be the issue, and most likely have to use `add_fillter` and `remove_filter` instead.

Please do this and we can see if it works :)

**Review by S34NW — APPROVED** [review]
Bugger it, we can add filters back later if we really care

**Pull request merged**
