### PR TITLE
Corrected some spelling errors in the examine descriptions

### PR DESCRIPTION
**Pull request by RudiPardieck**
Corrected some spelling errors in the examine descriptions

### CODE REVIEW

**Comment by Plotron** [comment]
Cool changes.
Question:
I have never seen these long descriptions before. When are they displayed? Do antags see things differently?

**Comment by tigercat2000** [comment]
@Plotron Examine something, then switch to the 'examine' tab in the stat bar (next to the "Status", "Admin", etc buttons)

**Comment by Plotron** [comment]
Right, now I think I remember something like that, thanks.

**Comment by Ultimate-Chimera** [comment]
Vacuum is correct. Vaccum is wrong.

**Pull request merged**
