### PR TITLE
Makes it so spacepods can push

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
tweak: Spacepods can push now.
/:cl:

Also fixes a minor coding error

### CODE REVIEW

**Comment by Aurorablade** [comment]
Why would they need to?

**Comment by Kyep** [comment]
This is a really bad idea. Spacepods are already extremely robust in space. About your only hope of winning combat with one is to get back inside the station. Giving them the ability to push you away will largely stop you being able to do even that.

**Comment by monster860** [comment]
travis failed on tgui step....

**Comment by KasparoVy** [comment]
Jetpack lets you juke them no problem

**Comment by Kyep** [comment]
That last Travis step sometimes times out for no reason I can identify. Closing/reopening the PR to force a Travis recheck usually fixes that issue.

**Comment by Denthamos** [comment]
Honestly in terms of space combat, 9/10 times someone with a jetpack and guns will win due to better mobility and being able to shoot in any direction you are aiming while flying.

Pushing would not really affect combat that much if it works like mech pushing as the most it will impact is space pods pushing crates through space.  If it is that much of a worry, add a penalty on pushing an object that causes slight damage to the space pod?

**Comment by Fox-McCloud** [comment]
Not really a big fan of this. I've never liked spacepods in any capacity, as they tend to just be used to ruin antags or get loot far easier (and with more protection).

I'm extremely cautious about doing anything that would buff them.

**Comment by FlattestGuitar** [comment]
Spacepods should be removed. Their movement is horribly inconsistent and they are incredibly unwieldy to use or fight. They do not fit a game where movement is restricted to tiles and generally cause massive amounts of issues with inconsistencies.

If not, spacepods should be able to push people if *people* can push people, that's a no brainer.

**Comment by Spartan6** [comment]
If we remove Space Pods that’s probsblg requiring an overhaul of

**Comment by tigercat2000** [comment]
@FlattestGuitar Please keep comments relevant to the discussion at hand, don't drag the thread off topic into "remove dis" territory.

**Pull request closed without merging**
