### PR TITLE
Adds radial menus to cult structures and constructs

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds Radial menus to cult structures (Altar, Archives, Forge) and the construct selection menu.

I was going to add one for the 'Blood Rites' menu too, but then if anyone wanted to add a new spell they would also need a sprite for the selection menu.

## Why It's Good For The Game

1. It looks better.

2. It's a lot easier to tell what the item/construct is going to be.

### Structures: (Before/After)
**Altar**
Altar BA

**Archives**
Archives BA

**Forge**
Forge BA

### Construct Selection: (Before/After)
Construct BA

## Changelog
:cl:
add: Added fancy radial menus to cult structures (Altar, Archives, Forge) and constructs
tweak: Making an item at a cult structure now puts it directly into your hand when applicable
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
How do these look in dark areas, can you still see the icons clearly? I'm worried about certain ones like the blindfold, or unholy water, because they're just all black.

**Comment by SabreML** [comment]
> How do these look in dark areas, can you still see the icons clearly? I'm worried about certain ones like the blindfold, or unholy water, because they're just all black.

Both still look visible to me, or at least not *in*visible
NSS Cyberiad 2020-11-09 010504
NSS Cyberiad 2020-11-09 010509

**Comment by Kyep** [comment]
Personally I prefer the text.
The sprites may look nicer, but the text is clearer about what you actually get.
You can CTRL-F the text on the wiki to find out what the item is and what its good for.

**Comment by Spacemanspark** [comment]
Maybe a combination of the two, have it bring up a small text blurb when you highlight an item, telling its name and maybe even giving a short description of its purpose.

Otherwise this won't really be friendly to someone unfamiliar to cult. I'm fine with a learning curve but new players should at least be able to look stuff up on the wiki properly.

**Comment by SabreML** [comment]
@Kyep @Spacemanspark 
Ah right, I didn't think to get a screenshot of this;
It does still show the item name when you hover over the icon, and I *think* it can be edited to show a description too. Although I'm not sure how that's done.
Untitled

**Review by Dumbdumn5 — APPROVED** [review]
I didn't even know we had radial menus, but considering I'm a civilian main and these are seldom used, more places for em would be great!

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
