### PR TITLE
Makes Hardsuits Auto-Adjust for Species

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Makes hard-suits auto-adjust for species.

Basically, instead of having to apply a modkit to a hardsuit to get it to fit to your species, you just have to put the hardsuit on.

This DOES technically mean that the hardsuit *object* (what you pick up) always looks the same, but the hardsuit's appearance, on the mob wearing the suit, WILL look different. I don't consider that a problem, to be honest, because of the greater convenience of being able to pick up any suit and just put it on, not to mention it's the mob sprite that's far more important to look correct.

ICly, this can all be explained by the hardsuits being advanced enough to shift their shape to adjust for the user, or something-or-other.

- Removes hardsuit mod kits from the map (These are no longer needed)

Helps make hardsuits easier to use for everyone that can wear them and players don't have to waste time looking for those rare EVA vendors to change suit types if they're incompatible.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Ehhhhhhhh.
Ehhhhhhhhhhhh.
I'll wait for other responses before making a thought out reply.

**Comment by Fox-McCloud** [comment]
I'd like to point out that this is already how Bay's backpack Rigs handle things; most of them aren't species restricted; they just deploy and auto-adjust their appearance.

**Comment by PsiOmegaDelta** [comment]
While our rigs indeed work that way, hardsuits (on Bay now called voidsuits) are still species restricted. However, our hardsuit mod kits have been replaced in favor of suit cycler machines that allows one to change the suit as many times you'd like.

**Comment by Fox-McCloud** [comment]
Yeah--we don't use those here, so I opted for this methodology since it seemed like pointless busywork for the player.

**Comment by veganzombeh** [comment]
Definitely :+1:, there's no need for modkits. 

It's also worth noting this would "fix" #2354 and presumably some other issues.

**Comment by theColdflame** [comment]
can't say I support homogenizing all the aliens but kits are already everywhere you can get a hardsuit anyway so there's not much reason for the system to begin with

**Comment by KasparoVy** [comment]
I'm going to miss those modkits. I felt it made more sense to have them-- I'm just having a really hard time understanding how a hardsuit could possibly adjust from fitting a plantigrade human user to a plantigrade unathi user to a digitigrade tajaran user to a digitigrade tajaran user. Maybe some very finely tuned manipulators and a variety of armour plate arrays that move when the software scans the user

IDEK, hard to rationalize it. Every time I have to go out and get a modkit it reminds me that I'm playing a species considered second-class to humans in most of the galaxy working on a human-managed (in lore at least) station. Additionally, it wards some nonhumans away from stealing hardsuits off incapacitated/AFK people or just picking one up should they find it as now they will no longer have to go through the trouble of hunting down a modkit.

**Comment by tigercat2000** [comment]
Modkits are a pain in the ass for only a minor bit of "oh well they need to be adjusted since they are for humans!"

**Comment by KasparoVy** [comment]
It's much easier to imagine a cheaper hardsuit that was built with modularity and moddability in mind (utilizing potentially aftermarket modkits) rather than a hardsuit built with an extremely expensive micro-manipulation and scanning unit to fit the thing to the body of whoever wears it

**Comment by KasparoVy** [comment]
k

**Pull request merged**
