### PR TITLE
cere: fix improper and duplicate cabling

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
This PR fixes cabling issues found as a result of #24262.

Added terminal nodes to unwired aft-port solars (117,51; 121,51; 125,51; 126,52)
Added terminal nodes to unwired aft-starboard solars or removed cabling (144,79; 144,80; 144,82; 146,82; 144,83)
Removed stray cable underneath airlock between eastern disposals and starboard maintenance (227,116)
Added terminal nodes to unwired starboard solars or removed cabling (204,152; 208,152; 212,152; 214,152; 203,153; 204,154; 208,154; 212,154;)
Added terminal nodes to unwired fore-starboard solars or removed cabling (218,173; 222,173; 226,173; 230,173; 216,174; 218,175; 222,175; 226,175; 230,175; 221,176; 218,177; 222,177; 226,177; 230,177)
Removed stray cable leading into Cell Block A (85,180)
Added terminal nodes to unwired fore-port solars or removed cabling (22,207; 26,207; 30,207; 34,207; 36,208; 22,209; 26,209; 30,209; 34,209)
Removed duplicate cable underneath rack in engineering (137,115)
Removed duplicate cable underneath airlock leading to Surgery 2 (201, 134)
Removed duplicate cable in fore-port maintenance near SMES airlock (52, 172)

## Why It's Good For The Game
Mapping errors bad.

## Testing
Ran CI.

## Changelog
:cl:
fix: Farragus: several missing or erroneous cables have been fixed.
/:cl:

### CODE REVIEW

**Comment by Fluffyzack21** [comment]
> Removed cable leading into rock in arrival shuttle hallway (151,67)

That got fixed with [https://github.com/ParadiseSS13/Paradise/pull/24268]()
Screenshot 2024-02-22 193751

**Comment by warriorstar-orion** [comment]
> > Removed cable leading into rock in arrival shuttle hallway (151,67)
> 
> That got fixed with [https://github.com/[/pull/24268](https://github.com/ParadiseSS13/Paradise/pull/24268)](fixes cerestation cables) Screenshot 2024-02-22 193751

removed

**Review by Henri215 — CHANGES_REQUESTED** [review]
1. This duplicated cable is still here

image


Everything else is looking good.

**Review by Henri215 — APPROVED** [review]
Lewcs good to me now

**Review by S34NW — APPROVED** [review]

**Pull request merged**
