### PR TITLE
New Medal Sprites, new Cargo Medal, and a minor locker sprite fix

### PR DESCRIPTION
**Pull request by ZomgPonies**
## What Does This PR Do
Based on https://github.com/ParadiseSS13/Paradise/pull/13126
Fixes the merge conflict

This makes the different medals each department head gets have a unique sprite, along with giving the HoP a new cargo medal to give away.

This also fixes a minor sprite error on the broken magistrate locker sprite.

## Why It's Good For The Game
Makes medals look more unique looking, makes it so the HoP is able to reward cargo with a medal, and fixes a sprite oversight.

## Changelog
:cl:
add: Adds new Cargo Medal to the HoP locker.
fix: Fixes a minor spriting error on the broken Magistrate locker.
imageadd: Gives each departmental medal new sprites.
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
I would like to see a little update to sprites, right now medals dont look good enough, especially color palette

**Comment by ZomgPonies** [comment]
This is probably ready for merge as the original PR was already approved by maints (and now heads), all I did was fix a merge conflict and re-open.

**Comment by rapaskoti** [comment]
i have to agree with Ramon on this one but those sprites look a bit off _like the service one..i can only presume_ but apart from that it's a good idea

**Comment by Pixelzilla** [comment]
I like the idea of having new/unique sprites for each departmental medal but I don't really like the new sprites. Some of them are quite difficult to tell what they are supposed to represent and I have to agree the color choices are a bit strange and don't really scream "medal" to me. I think what really throws these off for me is the fact that there is so much color used on the medal itself and with how tiny they are that excess of color doesn't really convey what they're supposed to be very well. 

Maybe it would look nicer if the designs on the medals were recolored to appear more like engravings like the current medals have. The ribbon colors could be altered to be more accurate the departmental colors that the medal represents? Some of the medals could have their shapes altered a bit to make them stand out.

As is though? Not really a fan.

**Comment by ZomgPonies** [comment]
Closing as nobody cares enough, and I was just being helpful in re-opening a stale PR. Not my battle to fight.

**Pull request closed without merging**
