### PR TITLE
Captain office remap! (office got a makeover).

### PR DESCRIPTION
**Pull request by M11gamer**
This change is more for aesthetics new carpet and some everyday items such as the PAI, laptop,clothes, zippo lighter, flags, bookshelves, lipsticks in the bathroom, one gold necklace in the new closet some ties, a blue beret and new window to get a view into space, also is a bit more easy to get into the captain office by the bedroom.

cap office 3

:cl: M11
tweak: Captain Office remap
fix: Cable under the console for the bridge windows
/:cl:

Update: Fixed some strange light placement.
Update: Removed the multitool and the toolbox.

### CODE REVIEW

**Comment by taukausanake** [comment]
Sure is closer to that grav generator. Otherwise I think it looks nice, I kind of like it. Don't really care for the black carpet tables on black carpet. I might keep those just reinforced so they aren't just wrenched away. The table in the bedroom would be better wooded and I might give it red carpet. Same with the table on the east of the office. Black on black isn't that good

**Comment by M11gamer** [comment]
Yeah, i could try and change for a red carpet.

**Comment by taukausanake** [comment]
Oh hold up. Why does the captain have all that stuff on that one table?
image
There is no reason any of that should be there. He does not need a multitool, no emergency tools, a station bound radio isn't bad but again, shouldn't really be there.

So we DO have action figures in the code! I thought we didn't get that from /tg/ yet
image

I should make a PR to put those in every department section like /tg/ has it, unless they're prize items only. If that's the case it might have to go too

**Comment by M11gamer** [comment]
@taukausanake Hum a set of tools is not that bad, the captain has all access so if he wants he will get it the same way is just more easy to put it there, the radio is everywhere is not hard to find and the toolset too almost all emergency locker have it, the only "rare" thing is the multitool and again if he wants he can get it, is just more easy to put it there.
I need to see if I can put the action figures.......

**Comment by taukausanake** [comment]
The problem is not if he _wants_ them, it's if he _should_ have them at round start, if at all. Yes he can get them if he wants to but that's a different issue that just giving it to him right off the bat.

We already have powergaming Science. We don't need the captain to be one, all-access or not

**Comment by M11gamer** [comment]
Hum ok I will remove the multitool and the emergency toolbox, I will let the radio.

**Comment by FalseIncarnate** [comment]
If you are going to update the contents of your change, its usually best to just outright replace the old screenshots with new ones, to avoid confusion

**Comment by SamHPurp** [comment]
Hi mate, as I was saying on Discord, you've still got wiring problems in your south window.

**Comment by Shadeykins** [comment]
Not a fan. It effectively removes one of the few sneaky "void spaces" on the map for traitors to do neat things with by adding a window looking into it with AI vision.

When not used to hide bodies, plant bombs, or as a mini-base, this is also the spot the DNA vault goes a lot of the time, which will now be a room with *direct* access to the Captain's office.

Captain also doesn't need a toolbox. If he really needs them he's got access to everywhere on station to get them.

Also, black on black is tacky. 🤢

**Comment by taukausanake** [comment]
I was thinking the same on the space closed up next to grav gen but didn't think it was too much an issue. If anything another way inside the captain's quarters might be nice. Beats brute forcing with thermite.

@Shadeykins I have never seen that area used for anything except maybe once for DNA vault

**Comment by ktoma36** [comment]
Perhaps have the windows be plasma ones? Just as easy to disassemble but harder to break open than the wimpy glass ones. Also the APC being right over the captains bed looks kinda funny, could be moved to the southern wall above the table. Other than that I like the added space, looks a lot less cluttered

**Comment by M11gamer** [comment]
@FalseIncarnate Yep, thanks i will change it

**Comment by M11gamer** [comment]
@SamHPurp if you are talking about the captain bedroom windows they have the exact same wiring as the bridge windows so if I am wrong all the bridge windows are, I will see but I think is ok like that, but thanks
wire
wire2
.

**Comment by M11gamer** [comment]
@Shadeykins 1- They still have the hop space to do that and so many others, I hardly see any antag do that, of course, they will have one less space but is so not used and if they want to use it there is still so many others places to do it.  
2- There is enough space for the DNA vault and a wall to protect the captain office if they want to build it there.
3- I already did take it out.
4- Yeah maybe is tacky, I will see if the others don't like it too.

**Comment by M11gamer** [comment]
Plasma windows are a bit strange to place there :/, but thanks maybe I will just put a wall there, also thanks for the advice on the APC I will change the place.

**Comment by SamHPurp** [comment]
Let me be explicit then:

image

Your top power cable in that list goes from middle to right. There is nothing to the right for it to connect to. It isn't needed. It is entirely superfluous.

**Comment by M11gamer** [comment]
@SamHPurp Ok......

**Comment by M11gamer** [comment]
@SamHPurp Better?
cap office 3

**Comment by ktoma36** [comment]
Looks good to me 👍

**Comment by M11gamer** [comment]
@ktoma36 The pipes are in the same place as the default map, I can try to change them.

**Comment by taukausanake** [comment]
@M11gamer I'd leave the pipes for another PR, keep yours atomic, Even though it would be nice to fix the pipes while at it might be more organized with a pipe rework with other areas

**Comment by M11gamer** [comment]
If you don't like black on black I can also try.
1----------------
red and black
2----------------
red on bacl
3----------------
red on red

**Comment by Ty-Omaha** [comment]
I like the black carpet with red tables

**Comment by FreeStylaLT** [comment]
I suggest making in-game screenshots rather than DM ones for aesthetics, since DM doesn't blend the tables, walls, carpets and so on.

**Comment by M11gamer** [comment]
@FreeStylaLT Thanks, i will do it, just give me some time my net is a bit bad today....

**Comment by M11gamer** [comment]
A one conflict........... dam

**Comment by FalseIncarnate** [comment]
I'm seeing a lot of unrelated changes in here, looks like your merge didn't quite go as planned.

Additionally, you'll probably conflict again if you had to fix conflicts with the medbay remap being merged, as that is being reverted currently pending further discussion. You might want to just nuke this PR, reset your master, and begin again (perhaps not on your master branch) at that point.

**Comment by M11gamer** [comment]
@FalseIncarnate the change to  medbay is reverted?

**Comment by M11gamer** [comment]
hum... Easy to fix i will just replace the map with my backup from before the conflict.

**Comment by M11gamer** [comment]
yeah..... better start again

**Pull request closed without merging**
