### PR TITLE
Chemmaster and pills NOREACT, separates Eject Beaker and Clear Buffer

### PR DESCRIPTION
**Pull request by fludd12**
I am a madman and decided to try what we talked about in design chat oh god

### CODE REVIEW

**Comment by fludd12** [comment]
FRICK KILL ME NOW

**Comment by Crazylemon64** [comment]
> Separates eject beaker and clear buffer

:eyes:

**Comment by Deanthelis** [comment]
Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. Yes. 
👌

**Comment by fludd12** [comment]
hold on just a moment I dicked everything again

**Comment by Crazylemon64** [comment]
Also, the myriad minor styling fixes makes me suspect you accidentally collided two branches.

**Comment by fludd12** [comment]
shushhhh

**Comment by fludd12** [comment]
Okay, okay, now time to rebase correctly this time.

**Comment by fludd12** [comment]
oooookay nevermind, I'm dumb.

**Comment by taukausanake** [comment]
> I dicked everything again

Stop ERPing with GitHub

**Comment by fludd12** [comment]
Fludd12: a story of a person and their failures using the most basic of repository management software

**Comment by fludd12** [comment]
what happened what

**Comment by fludd12** [comment]
okay one sec unscrewing up everything and then opening new branch because apparently git closed this on its own.

**Pull request closed without merging**
