### PR TITLE
Chemmaster and pills NOREACT

### PR DESCRIPTION
**Pull request by fludd12**
I am sorry for making all these pull requests twice, someday I will be not terrible at github.

:cl:Fludd12
tweak: Pills and Chem Masters do not cause reagents to react inside of them.
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Now with %11666.666 less jank

**Comment by fludd12** [comment]
@Crazylemon64 I am going to try to rebase again to make sure there's no remote tracking merges. For some reason, this constantly makes the diff like 56 files and undoes a lot of previous PRs every time I tried it last PR, so if it does it again, I'm gonna need some help.

**Comment by Crazylemon64** [comment]
`git checkout master`
`git pull upstream master`
`git checkout mybranch`
`git reset --soft master`
`git add .`
`git commit -m "no more leading merge commits"`
`git push origin mybranch -f`

**Comment by fludd12** [comment]
do I replace `upstream` with `ParadiseSS13/master`?

**Comment by Crazylemon64** [comment]
Travis where art thou

**Comment by Fox-McCloud** [comment]
👎 

Pills and patches don't need to be buffed. This is stupidly overpowered; R&D has to research `NOREACT` beakers, and most other NOREACT containers (cigs and darts) are difficult to use or the equipment is difficult to acquire.

Chemistry doesn't really need buffs right now.

**Comment by Crazylemon64** [comment]
If the beaker removal and buffer clearing were linked again, making NOREACT pills would require the cryo beaker. However, as the PR stands, one is able to do so immediately.

**Comment by fludd12** [comment]
I'll re-tie-together bufferclearing and beaker removal, since that keeps mass production down and ties production to R&D.

**Comment by fludd12** [comment]
@Fox-McCloud With these changes, is it less nonsensically buffing chem?

**Comment by Fox-McCloud** [comment]
I'm really not too keen on NOREACT pills existing, to be honest--the amount of ridiculous things you can do with them is very high---and all you need is a single NOREACT beaker to utilize them.

**Comment by fludd12** [comment]
Honestly, the only things that come to mind are azide / nitro pills, which are not as scary as some of the toxins already in our code. What do you have in mind for ridiculousness?

**Comment by Fox-McCloud** [comment]
An of the explosive mixes, self heating pills that only activate when your swallow them, smoke pills, foam pills, pills that mix "toxic mix" reactions (like sarin or cyanide), thus multiplying the reaction; there's a lot of really obnoxious things you could do.

**Comment by Deanthelis** [comment]
I'm pretty okay with NOREACT pills. Consider making NOREACT pills something you have to make a Chem-Master 2999 with Diamond-tier parts to create, thus gating superpills to (usually) 12:30 when miners deliver.

**Comment by Fox-McCloud** [comment]
Stale---still no updates, and I'm still in disagreement with buffing chemistry in this regard.

**Comment by fludd12** [comment]
At the moment, NOREACT pills would require the rather underused cryostasis beakers. I feel like it'd make sense for this, but if you feel it's buffing an already powerful mechanic, I can close.

**Comment by Crazylemon64** [comment]
This is stale? Do we mark things stale if there aren't any changes requested on it?

**Comment by Fox-McCloud** [comment]
I'm still not in approval of this; it's a fairly significant and large increase in power to science and chemistry both for getting your hands on a 2-3 minute in device.

**Comment by Crazylemon64** [comment]
Would the solution to this be making a cryostasis beaker require exotic materials?

**Comment by Fox-McCloud** [comment]
I'd much rather this be tied to the chem_master itself; an ultra high tier upgrade.

**Comment by Fox-McCloud** [comment]
@fludd12 would you be willing to make this an upgrade an upgrade to the chem-master or?

**Comment by fludd12** [comment]
@Fox-McCloud Sorry about the long delay, was pretty sick this past week. Would you prefer bluespace-tier, upgrade, or just high?

**Comment by Necaladun** [comment]
Against - this buffs scichem, which needs the opposite, and has no use for medchem.

Maybe something super special to upgrade or the like, but as is I don't like the potential.

**Comment by fludd12** [comment]
Been thinking about it - as cool as noreact pills are, there, uh, isn't really much USE to them. That, and the above concerns, just gonna close this.

**Pull request closed without merging**
