### PR TITLE
Remove slime extract and plasma tank steal objs

### PR DESCRIPTION
**Pull request by datlo**
This PR removes the plasma tank and slime extract steal objectives. Although they may make sense roleplay wise, they're simply boring to do and rarely cause any actual conflicts between the antagonist and the station.

This PR also adds hints to the blueprints (photo taking as an option) and the ablative armor (cargo crate as an option) objectives.

🆑
del: Slime extract and full plasma tank can no longer be steal objectives.
add: Added hint to the steal blueprints and ablative armor objectives.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
Removing the riot shotgun obj and maybe making another PR later to keep the two issues separate

I mostly want the shitty steal objs gone

**Comment by Superhats** [comment]
That's a :-1: for me.
The theft objective doesn't make sense.
There's no conceivable reason the Syndicate would want to send an undercover operative  to steal a simple shotgun.
Most, if not all theft objectives are either
- classified information
- rare materials
- high-tech, or otherwise experimental equipment.
Meanwhile, a riot shotgun is as basic as it gets. It's a standard, pump-action shotgun. 
Additionally, from a gameplay perspective, it's a bulky item, unlike all other theft objectives, which forces you to
- saw it off
- steal a security armor and wear it in the suit storage, which is very visible and obvious
- carry it in your hand, which is extremely obvious and a terrible idea all things considered.

I feel like the riot shotgun was just picked to replace the theft objectives being removed, for the sake of it being hard to acquire. No thought was given to why this item would want to be stolen in the first place.

**Comment by datlo** [comment]
bad timing I just removed the objective *honks

but yeah you're probably correct

**Comment by Ralta** [comment]
Removing Slime Extract and Plasma Tank is :+1: but I'm not so sure Riot Shotgun is a good alternative. It makes little sense for the Syndicate to want them when they have clearly superior weapons available.

An alternate suggestion would be the Ion Rifle/Ion Carbine (either as an option for the objective). The rifle is available every round from the start, but is bulky like the shotgun, so can't be hidden and is obviously in a secure area. They could then get the carbine instead if Science is capable, but still have to be able to open the box (either by emag or access).

**Comment by taukausanake** [comment]
I thought this was done a year ago?

Oh wait it was _almost_ done a year ago back in #7523. It was [decided to keep them in for the time being](https://github.com/ParadiseSS13/Paradise/pull/7523#issuecomment-317788019). I wonder if that will chance now

**Comment by Jazz23** [comment]
Yeah slime extracts and plasma tanks are stupid easy to get. One time somebody just left the doors open and I waltzed in in front of everybody uncontested and grabbed an extract. I actually mentor helped to make sure it was that easy and it could be just any old extract from xeno. Pretty sure I greentexted that round too.

**Comment by davidchan13** [comment]
Pretty much beyond the scope of the PR, but I think a rework in general needs to be considered. Drop off points or means oh-so-discreetly exporting theft objectives to get resupplies and rolling an additional objective. 

As far as slime cores go, could probably add for it to be a specific color or variety, or a slight tweak to how xeno bio works and make it so cores degrade over time if not kept in a fridge, so a thief would need a specialized (and very obvious) refrigerated case to carry around to keep their core(s) viable. (Think the Aerosal Can from Jurassic Park used to smuggle embryos off the island.)

**Comment by FalseIncarnate** [comment]
While the plasma theft objective is thematically correct and lore-friendly, it definitely is a less interesting objective than it should be. Honestly I feel like security most of the time wouldn't care if someone happened to have a tank of plasma in their pack unless they also were toting transfer valves or a flamethrower along with it.

The slime core objective might be a bit more interesting if it had some sort of additional criteria (must be a specific color, or has some sort of degradation factor you must avoid as suggested by davidchan13), but even then you get into issues with ensuring the objective is actually feasible (oh, you need rainbow extracts but the xenobiologist is focusing on making golems? too bad!).

I'm not particularly in support of removing these objectives, but I also can't really come up with any ways to make them more interesting yet still remain feasible for the majority of rounds. Could possibly replace the plasma gas theft with stealing a full stack (50) of plasma sheets? Those definitely are a bit more suspicious and still fits the theme and lore of undermining NT's business interests.

**Comment by taukausanake** [comment]
I like the idea of dropoff points. Maybe something along the line of a bluespace teleporter that sends the requested items off-station but also alerts the station of a bluespace transmission in that general area to which the traitor has to get away before caught. Rinse and repeat as/if needed and I think that would be cool

**Comment by Jazz23** [comment]
> As far as slime cores go, could probably add for it to be a specific color or variety, or a slight tweak to how xeno bio works and make it so cores degrade over time if not kept in a fridge, so a thief would need a specialized (and very obvious) refrigerated case to carry around to keep their core(s) viable. (Think the Aerosal Can from Jurassic Park used to smuggle embryos off the island.)

That sounds sick, if you give me specifics I can probably code it. Maybe open a forum post on the topic?

**Comment by Citinited** [comment]
As an alternative to dropoff points, how about a rendezvous objective? Imagine if you were given a task to steal something and a deadline to get it, at which point a ghost takes the role of a syndicate trafficker and meets up with you to take the item. They then get off station (maybe with a special teleporter button or implant) and you either pass or fail your objective there and then.

Just a thought really 😄

**Comment by taukausanake** [comment]
Can you have a getaway in a spacepod maybe? Too bad there most likely won't be a chase but who knows

**Comment by variableundefined** [comment]
We believe some of the easier objectives should be left in for players who are new at traitoring - If they don't like the objective, they can always ahelp and ask for a reroll.

**Pull request closed without merging**
