### PR TITLE
Adds a bit more punishment to traitors raiding the syndidepot.

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

When a traitor is spotted raiding the depot, a new thing happens.
1. They are warned the first time, "Syndicate facility attack reported, continuation will result in contract termination."
2. If they are spotted by agrro'd by 2nd syndi officer, the alert will be raised and 1 of 2 things will happen.
        Condition a) If they have an uplink with crystals in it, it will be slowly drained of all its crystals within 2 minutes, and they will be notified that their contract has been terminated.
        Condition b) Otherwise, if they have no uplink, or they get aggro'd by a 3rd officer, then 0-3 random assassinate/maroon/debrain objectives that have not been completed by traitors, will be rerolled onto them if possible.

Input on this is appreciated, I just think something like this should be officially added to the game, and not something admins have to do every time some tot attacks the depot.

Im also waiting on the pending merge of #23350 to easily change the target

## Why It's Good For The Game
Its a more interesting way to disincentivize traitors from attacking their own faction, but if they do choose to go that route, they will get some interesting consequences.

## Testing

Need to do some testing, thats why this is drafted, and pending merge of #23350

## Changelog
:cl:
tweak: The syndicate has imposed more restrictions on traitors raiding the syndicate depot.
/:cl:

### CODE REVIEW

**Comment by Probablyjay19** [comment]
While this could work, a few more objectives for a loud tot that happens to be robust can result in not being that difficult of a task. I've discussed a few times with people on how it might be time to flat out remove the depot. As much as I love it, I am in stern support that it adds nothing to both the explorers who can't use its contents and the antagonists the admins don't want using its contents. I would much rather have the nuclear option.

**Comment by Contrabang** [comment]
> While this could work, a few more objectives for a loud tot that happens to be robust can result in not being that difficult of a task. I've discussed a few times with people on how it might be time to flat out remove the depot. As much as I love it, I am in stern support that it adds nothing to both the explorers who can't use its contents and the antagonists the admins don't want using its contents. I would much rather have the nuclear option.

This doesnt make it any easier for a tot imo. As for removing depot, thats way out of scope for this PR.

**Comment by TORE01** [comment]
> While this could work, a few more objectives for a loud tot that happens to be robust can result in not being that difficult of a task. I've discussed a few times with people on how it might be time to flat out remove the depot. As much as I love it, I am in stern support that it adds nothing to both the explorers who can't use its contents and the antagonists the admins don't want using its contents. I would much rather have the nuclear option.

Personally, I think removing the GPS beacon is a better solution. It's supposed to be for explorers, not for gear hunting traitors. If traitors want free gear, let them work harder for it. It's a secret syndie depot, not a 7/11 in space.

**Comment by Denthamos** [comment]
Whenever I spotted a syndicate contracted based antag raiding the depot I personally always did the second choice there, giving every single alive antag the kill/debrain objective in place of their current kill objective if they have one or adding it to them if they did not, for the raider.  Good stuff.

**Comment by Contrabang** [comment]
This has been drafted for so long, and I'm not currently planning on working on it at all.
I want to continue this some day, but I don't currently have the motivation to properly test a PR like this.

**Pull request closed without merging**
