### PR TITLE
More Lavaland Updates: Primal and Bayonets

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Yet more lavaland updates; this one primarily focused on bringing the primal category up to date in addition to bayonets on guns.

Primal

Finishes out the primal crafting category and re-arranges the listing. Just some minor  changes, most of which benefit Ash Walkers than anything else. Current added recipes include:

- Wooden Bucket (same as metal bucket, only flammable)
- Rake (cultivator)
- Firebrand (long lasting match)
- bone Bracers (gloves that actually have armor that protects your arms)

Bayonets

You can now attach combat knives, survival knives, and bone knives as bayonets to certain guns. Putting a baynoet on the gun allows you to attack with the bayonet, if on harm intent, rather than whipping the person with the gun itself.
 
- Kinetic Accelerators, c20r's, bolt action rifles, and the security auto-rifle now all accept a bayonet

Other
- Can craft ore boxes, buckets, rakes, or firebrands from a stack of wood.
- Skull helmets are now properly a helmet

:cl: Fox McCloud
add: Adds a number of primal recipes: rake (cultivator), wooden bucket, firebrand (long burning match), and bone bracers (armored arm protection that goes on your glove slot)
add: Can attach bayonets to C20rs, bolt action rifles, security auto-rifles, and kinetic accelerator; harm intent to stab with them
add: can craft ore boxes out of wood
fix: Skull helmets are now proper helmets
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
Could you... attach an edagger to a c20?

**Comment by Deelite34** [comment]
It'd be nice, if we could hide knife in miner boot too

**Comment by JKnutson101** [comment]
> Could you... attach an edagger to a c20?

An E-Bayonet of any kind sounds amazing.

**Comment by Fox-McCloud** [comment]
>Could you... attach an edagger to a c20?

No, and I don't intend to either; this works, specifically, with combat knives and their subtypes.

>It'd be nice, if we could hide survival mining knife in miner boot too

Not going to be doing this; while we could implement the hacky version with alt-clicking and specifically only holding knives, the better solution would be to utilize the actual storage system---but this would require more of an overhaul than I deem worthy to include in this PR.

The vast bulk of shafter miners that have need of the survival knife are going to be utilizing the kinetic accelerator, so this PR easily covers their knife storage problem; people who utilize the crusher already have a sharp object; the knife in boot thing really just means an extremely tiny minority of players (resonator and plasma cutters only miners) are "left in the dark" for an adequate storage solution.

**Comment by MrMagolor** [comment]
>No, and I don't intend to either; this works, specifically, with combat knives and their subtypes.

Do nukies even have any way of getting combat knives or a subtype?

**Pull request merged**
