### PR TITLE
Actual TCC (reinforced) walls port

### PR DESCRIPTION
**Pull request by ElorgRHG**
## What Does This PR Do

Resprites reinforced walls, that's that.

## Why It's Good For The Game

So https://github.com/ParadiseSS13/Paradise/pull/17887 has granted us new wall sprites and new floor sprites, now while the floor sprites are perfectly fine and don't think most people object to how they look, the reinforced walls are... well, not great. The PR said it was porting TCC walls, but not the reinforced ones, which are proprietary.

I mean no offense to whoever made the reinforced wall sprites for that PR of course, be it AA himself or someone he might've gotten them from.

And yes, I'm aware that this is a temporary solution as we're all awaiting the glorious 3/4 walls from McRamon, I'm doing this just so walls will look good till then.

## Images of changes

Some bit of images (starring New Test Character I as the ghost):

<details>

image

image

image

image

</details>

## Testing

Observed, went around the station to screenshot things for `Images of changes`

## Changelog
:cl:
imageadd: Replaced reinforced wall sprites.
/:cl:

_No shame in trying_

### CODE REVIEW

**Comment by ElorgRHG** [comment]
Will add a comment almost instantaneously
I've heard that _reinforced_ part of these have "dice"
image

and I myself dont see it, but for those that do, how would this work instead

unknown (1)

**Comment by AffectedArc07** [comment]
> Will add a comment almost instantaneously I've heard that _reinforced_ part of these have "dice" image
> 
> and I myself dont see it, but for those that do, how would this work instead
> 
> unknown (1)
> 
> problem with these is that deconstruction step sprites would look... bad.

I had this exact sprite in during an earlier commit of #17887(See https://github.com/ParadiseSS13/Paradise/commit/9d6fd13732861f2b12fd2ba00d115d2eef9b9548 and https://github.com/ParadiseSS13/Paradise/runs/6919656141) 

They were met with the argument of "you cant instantly tell its reinforced or not", which while I dont agree with, I shall bring it up either way for context.

**Comment by ElorgRHG** [comment]
>I had this exact sprite in during an earlier commit of https://github.com/ParadiseSS13/Paradise/pull/17887(See https://github.com/ParadiseSS13/Paradise/commit/9d6fd13732861f2b12fd2ba00d115d2eef9b9548 and https://github.com/ParadiseSS13/Paradise/runs/6919656141)

> They were met with the argument of "you cant instantly tell its reinforced or not", which while I dont agree with, I shall bring it up either way for context.

While admittedly I was not around for that TM due to having... certain events happening in my nearest proximity, I want to say that I really want to understand where that issue comes from, but I really don't, these look plenty reinforced, I feel even the newest of players would be able to tell them apart.

This seems like a "you can't tell a syndie from an officer apart" kind of argument. The ones without the "dice" I could understand not being to tell apart, the one with... yeah no.

image

**Comment by OctusGit** [comment]
Yeah current reinforced walls are not really good visually wise. I'm pretty sure any player with eyeballs can notice a difference between regular and reinforced (even without the dice)

**Comment by AffectedArc07** [comment]
> Yeah current reinforced walls are not really good visually wise. I'm pretty sure any player with eyeballs can notice a difference between regular and reinforced (even without the dice)

Oh I fully agree. I only did the walls like that because heads refused to approve it otherwise.

**Comment by S34NW** [comment]
Just wait for Ramon walls

**Comment by AffectedArc07** [comment]
> Just wait for Ramon walls

3/4 walls require a lot more than just wall sprites, since things will need remapping to not be on the south side and similar. On top of that, it's not even a fully decided project, and it's still all up in the air on whether it fits or not.

**Comment by S34NW** [comment]
> Will add a comment almost instantaneously I've heard that _reinforced_ part of these have "dice" image
> 
> and I myself dont see it, but for those that do, how would this work instead
> 
> unknown (1)
> 
> problem with these is that deconstruction step sprites would look... bad. That's why I'm not in favor myself.

I know I mentioned ramon walls earlier, but as for this PR the "no-dice" version of these definitely look better when repeating. If you can't tell it isn't reinforced by the ribbing then you need new eyes.

**Comment by ElorgRHG** [comment]
RIP
_I dont really care all things considered, long live the alternative_

**Pull request closed without merging**
