### PR TITLE
Changes Which Fax Machines Can Send To CC

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Only the IAA/Magistrate/NT Rep/Captain's fax machine can send messages to CentComm now.

If you have a complaint to lodge you think is worthy of CentComm's time go through a bureaucrat who can properly forward it to the proper channels. In theory.

:cl: DaveTheHeadcrab
tweak: Due to budget cuts expensive fax machines have been replaced with cheaper versions in some departments. Only essential personnel can fax Central Command. See your local IAA for details.
/:cl:

### CODE REVIEW

**Comment by Wheatley29** [comment]
Ew

**Comment by Necaladun** [comment]
+1 as long as emagging them still lets people contact the syndies.

**Comment by FalseIncarnate** [comment]
Emagging still appears to be functional even on the not long-range faxes, so that should remain fine.

This mostly means the fax machines in the head of staff offices are now more for internal communication, while IAA, captain, and NT Rep retain their links to CC.

**Comment by TullyBurnalot** [comment]
@FalseIncarnate Regardless, it is nice to have that option available, even if few players know how to use it properly.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by FreeStylaLT** [comment]
:ok_hand:

**Comment by Lady-Luck** [comment]
:-1: @FalseIncarnate brings up a good point and I'd like to see that addressed.

**Comment by Lady-Luck** [comment]
:+1:

**Comment by DaveTheHeadcrab** [comment]
@FalseIncarnate 
@Lady-Luck 
@Necaladun 
@TullyBurnalot 

I HAVE LISTENED TO THE COMMUNITY PLEASE PROMISE TO BE GENTLE WHEN YOU QUARTER ME IN EXCHANGE

**Comment by Kyep** [comment]
👎 

If the CMO/RD/HoS/HoP are faxing CC, either:
1) It is a true emergency, and Captain/etc are dead/unavailable/whatnot.
Or:
2) The Captain themselves is the problem.

Typically, it is problem (2) that causes other heads to fax CC.

Most shifts, there won't be an IAA/Magistrate/NT Rep.
Other heads being able to fax CC is one of the few reliable checks on the power of a bad Captain.
By removing the other heads' ability to fax CC, and ensuring the only people who keep that ability are the Captain and some optional roles not present in most shifts, you are severely reducing the Captain's accountability, and thus their incentive to do things properly.

This change is also unnecessary. CC already has a slew of options to respond to heads wasting their time with bad faxes (announcement, template reply, BSA, evilfax, etc etc etc). 

The Syndicate has even more options, because, presumably, it is a brutal, murder-prone organization that cares even less about its employees than CC does. Someone repeatedly faxes for a SST? Do an enemy communication intercept from the Syndicate saying "No, Joe Blogs, we aren't going to send a SST to kill your co-workers for you. Stop asking.". Watch as they freak out and get chased by crew. 

Nerfing fax machines seems both unnecessary and harmful.

**Comment by Lady-Luck** [comment]
Actually, thinking about this, would it make more sense to make it so all fax machines are capable of faxing CC but just limiting what jobs can do it?

**Comment by GeneralChaos81** [comment]
I think that's already true, I think. I tried to log into a fax as a Station Engineer last night, but it wouldn't let me. Into an emagged fax machine, no less.

**Comment by DaveTheHeadcrab** [comment]
Potentially. But then I'd have to add a new access for "The ability to fax", as the jobs that can fax CC aren't constrained to one single job that has one single access type.

Then I'd have to rewrite a pretty large chunk of fax code to account for access logged in with to do the exact same thing I'm doing right now.

**Comment by theColdflame** [comment]
The department heads, especially the HoP and HoS all have semi-regular scenarios they'll need to contact CC. This needlessly bottlenecks the already slow process of dealing with internal problems, seemingly for the sole purpose of giving certain, nonvital, jobs more relevance?

**Comment by DaveTheHeadcrab** [comment]
The HoP/HoS don't need to refer to CC for internal problems. At all.

**Comment by theColdflame** [comment]
Abusing the fax machine will already either land you a jobban or a BSA depending on severity. The HoP specifically requires a fax machine for handling transfers into karma roles, as well as getting rulings on questionable demotions or raising issues with higher-ups on the station.

Command are expected to be competent, they should probably be trusted with what's essentially the pray verb on steroids.

**Comment by DaveTheHeadcrab** [comment]
Never once did I say -- or imply -- that the reason this change was being made is command can't be trusted with it.

**Comment by Plotron** [comment]
Isn't it the case that most heads value their time and ask the relevant people to do the fax-and-paper thing instead of trying to accomplish that on their own?

I believe the impact here [on the con side] is also exaggerated, considering that all you really have to do is break into IAA/Rep/Magistrate/Captain rooms to send a fax to CC provided you've got command access. It won't be a big deal in most of emergencies.

**Comment by Dinarzad** [comment]
What Plotron said, for the most part.

If there's no IAA or Rep, getting into his office should be easy enough. If there is an IAA or Rep, send your fax to their office and ask them to forward it to CC, or ask them to draft one up.
The only difference is now you have another player reading it over first (I hope) before just sending it on to CC, and deciding if it is or is not worth their time. But that's also the entire job description of the IAA and NT REp. To appraise a situation and get in contact with the highest authority that NEEDS to be contacted, whether it be a head of staff, the Captain or Central Command.
(And in the case of the NT Rep, to send progress reports and inform them of developing situations.)

**Comment by Lady-Luck** [comment]
>I believe the impact here [on the con side] is also exaggerated, considering that all you really have to do is break into IAA/Rep/Magistrate/Captain rooms to send a fax to CC provided you've got command access. It won't be a big deal in most emergencies.

If that's the case, then what is the point of this change?

I've been thinking about this, and honestly I've decided I'm against it, because I very much dislike inconsistencies that aren't immediately apparent. It's unintuitive to have fax machines in two different locations work differently.

**Comment by Plotron** [comment]
Yeah, it's such a minor tweak - it's subtle but there's a point to it. I'd call that *refinement*.

**Comment by Lady-Luck** [comment]
>Modified sprites could help differentiate between the types.

I'd be fine with that. Without a more obvious way to differentiate between the two, however, I'm against this change.

**Comment by DaveTheHeadcrab** [comment]
If you'd like to make sprites, then by all means  do so.
But both the names of the fax machines that are able to transmit and the networks it says they are connected to are very obviously different.

**Comment by DaveTheHeadcrab** [comment]
OH NO
THAT WAS AN ACCIDENT

**Comment by TullyBurnalot** [comment]
> One of the many issues here is people feeling like they need a CC-approved paper before they can do anything.

I disagree with this notion. I rarely see more than three faxes a round, and that is in rounds that **have** faxes. Even then, more often than not, we see one or two faxes, as opposed to any significant number, and even then, those are, statistically speaking, more likely to be an NT Rep report than anything asking for the opinion of CC.

I feel you are exaggerating things a bit, considering more often than not, things **do** actually get solved on-site.

_THAT SAID_, I am still giving this a thumbs-up because it gives some more love to the NT Rep and the IAA. As for what @Plotron said, well, we can still arrest Heads of Staff for breaking into places to use fax machines, and if a Head of Staff actually takes the time to ask permission to walk into the IAA Office to use a fax themselves, it is probably something legitimately relevant.

**Comment by DaveTheHeadcrab** [comment]
>I disagree with this notion. I rarely see more than three faxes a round, and that is in rounds that have faxes. Even then, more often than not, we see one or two faxes, as opposed to any significant number, and even then, those are, statistically speaking, more likely to be an NT Rep report than anything asking for the opinion of CC.

In either case, the need for heads of staff to have instant access to CC communications is being _severely overstated_ in this conversation.

Which is kind of what I was getting at anyhow.

**Comment by ppi13** [comment]
Magistrate is the least played role on the station, IAA are more common, but they are for more internal matters, NT rep is for command matters.
Honestly there is no reason to remove the CC access, there are times when the others are inaccessible, be it due to xenos, or whatever, and faxes have been used to notify CC of what it happening as to warrant a higher level of ERT before calling them.
If you got complaints, you go to either the IAA or the rep, but complaints is not every fax.

**Comment by tristan1333** [comment]
Delet headcrab  man. But yeah this is a errr... Not very important thing but makes sense. More power to the paper monkeys I guess.

**Comment by Fox-McCloud** [comment]
@TheDZD supports this, now that emagging it works for *all* fax machines.

Merging this in.

**Pull request merged**
