### PR TITLE
Makes the medical HUD overlay smoother

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattestGuitar
tweak: The medical HUD will now be a bit smoother. Neat.
/:cl:

Added as many frames in there as humanly possible. Now you can murder someone and know *exactly* how many more hits to the face they need.

The numbers are ugly, because 100 isn't divisible by anything close to 14, but who cares anyway.

Also, per public request, ports the flashy thingies from /tg/'s [#17279](https://github.com/tgstation/tgstation/pull/17279)

### CODE REVIEW

**Comment by monster860** [comment]
:+1:

**Comment by taukausanake** [comment]
Cool, I don't have to feel so bad for making a ton of icons for my Hydroponics HUD overlay.
...
Fuck I need to get that pushed before you get this pushed

**Comment by FlattestGuitar** [comment]
:^] 

Fite me.

**Comment by Fox-McCloud** [comment]
Would you mind implementing this, as well? https://github.com/tgstation/tgstation/pull/17279

**Comment by LittleBigKid2000** [comment]
Related idea: Medhuds showing how much time a dead person has before they can't be defibbed, and if they're in their body, ghosted, or have left the server like a morgue slab.

**Comment by KasparoVy** [comment]
Fox' suggestion would be amazing to have.

**Comment by FlattestGuitar** [comment]
There. Added the nice thingy thingies. It will flash a bit at 0 health, flash way more at -50 and flash SUPER HARD at -85. o7

**Comment by Spacemanspark** [comment]
But does it spray confetti when they die?

**Comment by FlattestGuitar** [comment]
**Yes, it does.**

*(no, it doesn't.)*

**Comment by Spacemanspark** [comment]
But how will I play my Halo character now.
My immersions.

**Comment by taukausanake** [comment]
I thought that was only when you shot them in the head

**Comment by Norgad** [comment]
Could you move the medical HUD upward by a few pixels, so it doesn't overlap with the tops of people heads?

**Comment by Spacemanspark** [comment]
@taukausanake I was more referring to this https://www.youtube.com/watch?v=X1O8gp3yPwk and not the grunts :^)

**Comment by taukausanake** [comment]
@Norgad Those sprites are already at the very top so unless you can offset overlays that's where they are staying. They're also the exact same sprites we already have, size and all, but with a bit more value checks

**Pull request merged**
