### PR TITLE
WIP: Adjusts nurse dress sprite, fixes nurse's hat missing pixel

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do
This PR does three things (apologies, I could not split this up):

1) After #17670 the nurse cap had a red item sprite, but a blue onmob sprite. This PR fixes it.

image

2) The side-view of the nurse cap had a missing pixel pointed out by CinnamonBall on #17670:

image

3) The dress still had a red cross that we should get removed, so I removed that, and recoloured it. The blue line has the same colour palette as the hat to match the dress.

image

## Why It's Good For The Game
Colour consistency, plus we do not misuse the red cross emblem.

## Images of changes
Final image:

image

## Changelog
:cl:
tweak: The nurse dress and nurse hat sprites were slightly adjusted.
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
I feel like the nurse dress should retain the cross but in blue if need be, otherwise it just kind of looks like a tube top with nothing really to link it to medbay

**Comment by Miraviel** [comment]
> I feel like the nurse dress should retain the cross but in blue if need be, otherwise it just kind of looks like a tube top with nothing really to link it to medbay

I tried keeping the cross on it, but a cross on the hat and a cross on the dress felt like a fashion crime similar to wearing a plaid skirt with a plaid shirt...

I agree it has no visible symbol on it that connects it to medbay, but nurses IRL don't wear crosses either everywhere. (They don't even have a cross on their headwear, but we gotta stay game-y at least a bit). :>

**Comment by atteria** [comment]
You should probably make the item cross shape reflect the changes to the mob cross shape.

**Comment by Carthusia** [comment]
> > I feel like the nurse dress should retain the cross but in blue if need be, otherwise it just kind of looks like a tube top with nothing really to link it to medbay
> 
> I tried keeping the cross on it, but a cross on the hat and a cross on the dress felt like a fashion crime similar to wearing a plaid skirt with a plaid shirt...
> 
> I agree it has no visible symbol on it that connects it to medbay, but nurses IRL don't wear crosses everywhere either. (They don't even have a cross on their headwear, but we gotta stay game-y at least a bit). :>

The nurse hat/dress combo is based on old timey nurse uniforms, where many uniforms did have a red cross on the dress https://i.gyazo.com/237d63498eef37c07fff740c68f3ec52.png

Perhaps a redesign of the dress itself to be more accurate to their old style? 

https://i.gyazo.com/b158ab7ceef4bd734cbece3f483693c1.png

Blue cross obviously for "Legal' reasons

**Comment by Miraviel** [comment]
> > > I feel like the nurse dress should retain the cross but in blue if need be, otherwise it just kind of looks like a tube top with nothing really to link it to medbay
> > 
> > 
> > I tried keeping the cross on it, but a cross on the hat and a cross on the dress felt like a fashion crime similar to wearing a plaid skirt with a plaid shirt...
> > I agree it has no visible symbol on it that connects it to medbay, but nurses IRL don't wear crosses everywhere either. (They don't even have a cross on their headwear, but we gotta stay game-y at least a bit). :>
> 
> The nurse hat/dress combo set of items is based on old timey nurse uniforms, where many uniforms did have a red cross on the dress https://i.gyazo.com/237d63498eef37c07fff740c68f3ec52.png https://i.gyazo.com/092f30b41ff092489fe735253703aa34.png
> 
> Perhaps a redesign of the dress itself to be more accurate to their old style? Always did find it weird how the ingame dress has lopped off the shoulders and looks like a tube top dress than an actual nurses outfit. Who wants to have exposed arms when dealing with bloodied patients?
> 
> https://i.gyazo.com/b158ab7ceef4bd734cbece3f483693c1.png
> 
> Blue cross obviously for "Legal' reasons

I didn't know this, thanks!

I will take a crack at it and see how it looks.

**Review by AffectedArc07 — APPROVED** [review]

**Comment by AffectedArc07** [comment]
image
image
image

I may be dumb

**Pull request merged**
