### PR TITLE
Removes LINDA, Ports FEA from Goonstation

### PR DESCRIPTION
**Pull request by TheDZD**
Done at the request of Tiger, because of nerds complaining about LINDA. Instead, enjoy true hell.

### CODE REVIEW

**Comment by ScratKnapp** [comment]
...What are the differences between this and LINDA?

**Comment by KasparoVy** [comment]
Well, this is a changelog, and LINDA is an atmos system

**Comment by Spacemanspark** [comment]
It's a changelog update, @ScratKnapp

**Comment by Magikarpet** [comment]
:laughing: @ScratKnapp

**Comment by fludd12** [comment]
T~T

**Comment by ScratKnapp** [comment]
I recognized it's a joke, but what is FEA and why would it be 'true hell'?

**Comment by NTSAM** [comment]
Fea is goon atmos IIRC, it's dumb.

**Comment by NTSAM** [comment]
And even less fun than linda

**Comment by Spacemanspark** [comment]
Ayyy lmao.

**Comment by TheDZD** [comment]
I have been informed that OOC blew up about this. Mission accomplished.

**Comment by KasparoVy** [comment]
It was bloody hilarious, the salt is ongoing

**Comment by TheDZD** [comment]
Embrace the NaCl.
delicious

**Comment by Fox-McCloud** [comment]
We Goon now.

**Comment by NTSAM** [comment]
this was a clever ruse dzd

**Pull request merged**
