### PR TITLE
Paramedic EVA Re-Sprite

### PR DESCRIPTION
**Pull request by Agameofscones**
This PR is quite simple, in reviewing the various styles of space and or hard suits available in game,  the current Paramedic EVA gear noticeably does not match the style of all other NT EVAs (Excluding the voidsuits), and instead more closely resembles a recolored Syndicate Space Suit. I have gone and re-sprited the entire space suit using the original colors of the Paramedic's Vest, with the suit design being based heavily on the Medical hardsuit, with the helmet more closely resembling the original.

I have made sure to test the suit in game, and I have yet to notice any consistency or visual errors, however if there are any, do notify me so I might change the sprites.

image
image
image
image
image
image
image
image
image

All the dimensions for the species specific sprites were taken from other species specific hardsuits (Usually mining or the CE suit, since those were high contrast and easy to reference)

:cl: Triiodine (Agameofscones)
del: Removed original paramedic EVA sprites
add: Replaced paramedic EVA sprites with medical hardsuit inspired set.
add: Added species variants _(Which did not exist before hand)_ to Unathi, Tajaran, Drask, Skrells, & Vulpkanins.
add: Added the same armor values the basic EVA suit gets (bio 100, rad 20), this puts the paramedic suit in standard with other NT soft suits.
edit: Fixed a typo in the santasuit comment, because why not.
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
Have you also resprited species variants to fit this new style?

**Comment by Agameofscones** [comment]
There presently are no racial variants for the current paramedic EVA suit as well as the one I've re-sprited. However I am quite capable of making racial variants, but I am unsure of how to implement them, as that would be introduce new sprites into the racial suit.dmi's, and I'm not sure how to make those display correctly in game.

**Comment by Agameofscones** [comment]
Datlo, I have just checked the suit.dmi for Grey's, while they do have a variant of the paramedic vest and EMT-Labcoat, they do not have a specific variant for the EVA suit itself.

**Comment by Agameofscones** [comment]
I've started spriting the racial variants for those species that don't have em, I'll need help implementing them though!

**Comment by KorpoPapiez** [comment]
Greys DO have a variant of EVA paramedic HELMET.

**Comment by Superhats** [comment]
Don't forget pictures of the racial variants, bud

**Comment by KasparoVy** [comment]
Might be worth a re-up in a week or however long

**Comment by Agameofscones** [comment]
Yeah while fixing the conflicts with the new dracula coat I sorted _totally closed the PR permanently,_ so my only option really is to reopen the PR in a new one with the fixed conflicts. _oops_

**Pull request closed without merging**
