### PR TITLE
Optimizes Job Objectives

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Makes job objective end-round screen only show personal objectives if any. Optimizes some shitty recursive looping.

### CODE REVIEW

**Comment by tigercat2000** [comment]
So... it basically makes the job objectives even more pointless, as it even looses the ability to show off to other people?

**Comment by ZomgPonies** [comment]
I intend to make the objective stats database driven so you can compare your productivity to the server average. This is just a minor cleanup before getting into that.

**Comment by FalseIncarnate** [comment]
I still believe the objective should be displayed to everyone (perhaps on the pop-up end report), though condensed into the completion for the given job type / department

So rather than it being listed for EVERY scientist that they maximized research, it might just show something like "SCIENCE: Maximize all levels of legal research. (COMPLETE!)"

**Comment by ZomgPonies** [comment]
Considering how shitty the current system is and that noone has been willing to improve it for over a year and a half, it's either that or I'll probably end up ripping out the whole thing altogether.

**Comment by Aurorablade** [comment]
...should i add, 'add to objectives system' to my todo list?

**Comment by ZomgPonies** [comment]
If you want to take on the project, sure. This is based on an old vg system and really only covers RnD + Roboticist right now, and even with that is pretty spammy in the end-game result screen hence my attempt at cleaning it up a bit and making it more personalized.

**Pull request closed without merging**
