### PR TITLE
Claw Games! (HTML5 Arcade)

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds claw games, the absolute most-infuriating arcade game known to
mankind.
- Uses new fancy HTML5 / Javascript code stuff
image
- Is buildable!
 - Science can produce the board with programming 2
 - Requires a matter bin, manipulator, some cables, and a sheet of glass
- Costs money!
 - Accepts cash or ID swipes, 15 credits per play token
- Dispenses prizeballs!
 - Open them for a random plushie, carp plushie, or action figure!
- Two sets of sprites, thanks to FoS and Stephanov

image

Notes for the coders / future:
This provides a basic example for introducing new HTML5 / Javascript arcade games, as well as a base type machine to use for such games. While this may seem silly, this proves that we are not doom to have to tolerate only the battle game and Orion Trail forever, and can even make our own games for the arcade.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Pictures!

**Comment by FalseIncarnate** [comment]
I'll do you one better. A GIF!

image

**Comment by Crazylemon64** [comment]
'o'

**Comment by NTSAM** [comment]
OOOOOOOOOOOOOOOOOOH

OOOOH OOOH OOOOOOH

:+1: :+1: :+1: :+1: :+1: 

:+1: :+1: :+1: :+1: :+1:

**Comment by Spacemanspark** [comment]
:+1: x :100:
Fuck yes.

**Comment by kylejen** [comment]
Is it going to be added with the two random games that arcade machines can start with on round start, or is it only able to be built?

**Comment by Spacemanspark** [comment]
I just had a thought.
Make a timer pop up after you press play.

**Comment by FalseIncarnate** [comment]
@kylejen For now, buildable only. They use a different base path than the claw game, so I'd have to kinda snowflake the claw game into that spawning. I do, however, plan to dd claw games to the map after the current map-freeze is done. Ideally, I'd like to create a dedicated arcade area that will contain all the different arcade games, and also a prize vendor that operates off of tickets you earn from games.

@Spacemanspark I had considered including a timer, but decided against it as the game was already challenging enough (the controls are super touchy) without imposing a time constraint as well.

**Comment by kylejen** [comment]
@FalseIncarnate Aw, but that arcade idea sounds pretty COOL.

**Comment by Spacemanspark** [comment]
@FalseIncarnate Heh, fair enough.

**Pull request merged**
