### PR TITLE
Fixes some area problems.

### PR DESCRIPTION
**Pull request by monster860**
Fixes area problem in Bridge Maintenance
Fixes area problem in Engineering
Fixes area problem in AI upload

(Basically, instances of wrong area being used).

This PR was made with https://github.com/monster860/FastDMM

No mapmerge was used.

### CODE REVIEW

**Comment by Regen1** [comment]
Nono

What was the actual problem, what did you fix

Also changelog

**Comment by Krausus** [comment]
> doesn't re-use modified IDs, meaning no direct diffs
>
> three copies of `(/turf/simulated/floor/plasteel{icon_state = "dark"},/area/turret_protected/ai_upload)`
>
> five copies of `(/turf/simulated/floor/bluegrid,/area/turret_protected/ai_upload)`

Uhhhh...

**Comment by monster860** [comment]
Ah... Shit. I thought this thing was supposed to *not* do that.

**Comment by monster860** [comment]
There, fixed. Turns out I forgot to define an equals() and hashCode() on my tile instances, causing the map editor to think that the new tile instances were unique.

**Comment by Krausus** [comment]
That looks better... but the current map merger tries to re-use keys whenever possible, so the diff will (usually/sometimes) show what changed on a line. [This diff](https://github.com/ParadiseSS13/Paradise/pull/5265/files) is a good example of the map merger working well.

**Comment by TheDZD** [comment]
Have you checked to see what the Dream Maker map editor does after editing a map that has been edited by your tool? Specifically, what it does with tile IDs.

**Comment by monster860** [comment]
DM would shuffle the keys around and require mapmerge.

**Comment by Regen1** [comment]
@monster860 We need to know that DM plays nice with this

You used a different mapping tool, we need to know that our mapping tools doesn't break from this.

**Comment by monster860** [comment]
image
Dm looks fine to me.

**Comment by tigercat2000** [comment]
@monster860 does saving then using the normal mapmerge function correctly?

**Comment by monster860** [comment]
@tigercat2000 Yes, besides the fact that mapmerge + dm will move modified keys that were originally in the higher values to lower values, but it saves fine.

**Comment by Fox-McCloud** [comment]
Please just fix this via traditional means until your map editing tool is fully completed, tested, and bufixed--just to be on the safe side.

**Comment by monster860** [comment]
@Fox-McCloud The map compiles correctly, DM can load/save it, and the diff looks fine to me, and I've made more complex map changes than this and had it work correctly. I fail to see the problem.

**Comment by TheDZD** [comment]
Conflicts.

**Comment by monster860** [comment]
Conflicts fixed @TheDZD

**Pull request merged**
