### PR TITLE
Allows Vulpkanin, Tajara and Unathi to use certain human hairstyles

### PR DESCRIPTION
**Pull request by BunnyGirlJen**
## What Does This PR Do
Simply adds human hair to the Vulpkanin, Tajara and Unathi hairstyle lists, as well as removing the entirely useless gender variable on some hairstyles and also removing one redundant hairstyle.

There was probably a way better way to implement this, but hey-ho, it works. I don't have the skill to fix any hairs that don't work with the races, so no sprite changes here, I just removed whatever hairstyles didn't work from the three race's lists.

## Why It's Good For The Game
COMPLETELY subjective here, but I think it makes sense for these races to have more hair options, especially considering Unathi had _some_ of the hair options but not all of them.

## Images of changes
Here's Arah with an 80's ponytail.
image

## Testing
Ran the debug server, went into character customisation, gave each race every hair cut and removed any that were jank/didn't fit with the head sprites.

## Changelog
:cl:
add: Added certain human hairstyles to Vulpkanin, Tajara and Unathi
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
image
No need to included this into the changelog, it should only contain stuff that matters to the player.

**Comment by BunnyGirlJen** [comment]
>No need to included this into the changelog, it should only contain stuff that matters to the player.
Noted, thank you!

**Review by DGamerL — COMMENTED** [review]
This review is literally all of the mentions of one single question I had

**Comment by BunnyGirlJen** [comment]
To answer: All of those sprites had discrepancies that meant they wouldn't work on the Taj/Vulp/Unathi sprites without modification (i.e clipping through the snouts or having human ears), and I don't really have the skill in spriting to deal with that, so for the time being I just kept them as slime/human only.

As for why there's a pompadour and a dandy pompadour.. I have no idea. They do look different, though.

**Comment by BunnyGirlJen** [comment]
I just noticed there was a merge conflict, no idea how that happened but it's fixed now.

**Comment by DGamerL** [comment]
> To answer: All of those sprites had discrepancies that meant they wouldn't work on the Taj/Vulp/Unathi sprites without modification (i.e clipping through the snouts or having human ears), and I don't really have the skill in spriting to deal with that, so for the time being I just kept them as slime/human only. (I mentioned this in the pull request a little)
> 
> As for why there's a pompadour and a dandy pompadour.. I have no idea. They do look different, though.

👍 
Feel free to resolve my conversations then!

**Comment by Probablyjay19** [comment]
image

No way

**Comment by BunnyGirlJen** [comment]
I hope my small change here will turn the tides and get more people interested in improving hair so that we can be even drippier

**Review by DGamerL — APPROVED** [review]
LGTM

**Comment by Screampuff** [comment]
speedmerge pls

**Review by S34NW — APPROVED** [review]

**Pull request merged**
