### PR TITLE
Adds random drug pill bottles to mainloot

### PR DESCRIPTION
**Pull request by jughu**
This adds random drug pill bottles (one from old bar) as lootdrop

### CODE REVIEW

**Comment by Plotron** [comment]
Okay.

**Comment by Fox-McCloud** [comment]
Please read the documentation on maint loot tables; this isn't how you properly add something to it.

Also not keen on these being more common than they already are, given they can contain some really good chems (and cargo can order them).

**Comment by jughu** [comment]
@Fox-McCloud  i though cargo could only order the zoom pills and not the random ones

**Comment by Da-Dman234** [comment]
Floorpills are strong. They can contain both Vampire Dust and Prions, which both a very deadly, and aren't really able to be very well utilized by anyone without access to a chem machine. Only thing stopping them from being so strong now is that it takes multiple pills to get usable amounts of either. If you exclude those two reagents, there's still the issue of greyshirts running around with roundstart meth and bathsalts, though I don't really have a problem with that I'm sure someone does.

**Comment by Necaladun** [comment]
Maybe a seperate class of drugs without the super stuff in them?

**Comment by jughu** [comment]
I guess i get on that later and make a new PR since im gonna be busy for a whike

**Pull request closed without merging**
