### PR TITLE
Nano Updates

### PR DESCRIPTION
**Pull request by tigercat2000**
Just some small updates to Nano, a proper README, moving into Gulp-based compilation.

I was gonna go further and make the styles into LESS and minified automatically and all that jazz...
# BUT AFTER 7 HOURS OF FUCKING GETTING NOWHERE, I DON'T FUCKING CARE

so you get just some basic build tools

### CODE REVIEW

**Comment by TheDZD** [comment]
It seems that NanoUI refactors are truly an exercise in masochism.

**Comment by tigercat2000** [comment]
.. this might not actually work.

**Comment by tigercat2000** [comment]
GOD FUCKING DAMNIT THIS WORKED WHEN I TRIED IT BEFORE
AAAAAAAAAAAAAAAAAAA

**Comment by Fox-McCloud** [comment]
`binsult.ogg`

**Comment by Spacemanspark** [comment]
What's not working, Travis didn't beat you with a stick.

**Comment by tigercat2000** [comment]
the fucking javascript isn't working

**Comment by Spacemanspark** [comment]
Oh.

**Comment by tigercat2000** [comment]
AAHHFSDGDGIYSDIUH

FUCK NANO GOD DAMNIT

i thought htis FUCKING WORKED BUT APPARENTLY GODDAMN NOT AAHH

**Comment by Spacemanspark** [comment]
And that, kids, is the story of how the NanoUI system pulled @tigercat2000 to a deep abyss of insanity and all things Nano.

**Comment by tigercat2000** [comment]
goddamn git overwrite the branch already

**Comment by tigercat2000** [comment]
whatever fuck

**Comment by Tastyfish** [comment]
working nano's guts in a nutshell

**Pull request closed without merging**
