### PR TITLE
Readds collabs as a config option

### PR DESCRIPTION
**Pull request by Aurorablade**
Reverts https://github.com/ParadiseSS13/Paradise/pull/10558/
Readds collabs as a config option.
Why?
Downstreams may want it.
An admins on our code may one day feel 'okay lets do this' for a few rounds.

Why WIP?
I want to be sure i add everything in correctly as a config option and to the right damn file.
Knowing me if i don't have someone make sure i did i am gonna cause everyone to explode into parrots.

:cl:
add: Player Collabs return as a server based config option.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Should totally be a feature

**Comment by Aurorablade** [comment]
WIP off, Config works

**Comment by Allfd** [comment]
I am fine with this, being able to turn it on would be fine.

**Comment by ScratKnapp** [comment]
And collabs are..

**Comment by FalseIncarnate** [comment]
Collabs is short for Collaborators, removed in #10558 despite obvious support of changing it to a config option rather than removing it for reasons that were never shared even internally.

They are crew that a traitor is told may be willing to assist them in small ways to accomplish their objectives, but are not inherently antagonists themselves. Syndicate sympathizers, rather than actual Syndicate agents, if you will.

**Comment by Allfd** [comment]
@v0idp

Currently we allow any player to be a collaborator providing they have a valid IC/RP reason.

The collaborator system could potentially work a bit better, if players opted into it.  Then you would not get as many "No" responses.

**Comment by FalseIncarnate** [comment]
@Allfd technically the collaborator system is opt-in. You have to set your Nanotrasen relation in character creation to skeptical or opposed, and it is set to neutral by default. Don't want to be a collaborator, don't set that relation level.

**Comment by Allfd** [comment]
@falseincarnate

Yes but that's not documented anywhere a player could find it.

**Comment by FalseIncarnate** [comment]
@Allfd 
image Not exactly the best spot for visibility, I'll admit, but it technically is documented in a place players could see that the relation affects your eligibility. The wiki not being updated is more a failure on myself to actually make sure it got around to being documented more.

**Comment by Aurorablade** [comment]
Shhhh don't mention wiki updates we will wake up shady... *also i can add something here if someone tells me what/where*

**Comment by Birdtalon** [comment]
>Yes but that's not documented anywhere a player could find it.

Alffd is right. Ideally it should be baked into the game itself if not self explanatory.

**Comment by FalseIncarnate** [comment]
Not disagreeing that it should be more visible, though finding a way to communicate that in-game is going to be tricky to avoid excess clutter on the character screen and also should ideally also include reasons to select loyal/supportive which we don’t have (though I have been thinking of ideas on that, just nothing concrete yet)

**Comment by Birdtalon** [comment]
I would suggest a little box such as [?] with a popup maybe to reduce overall clutter on the screen but still remaining informative.

**Comment by FalseIncarnate** [comment]
That would probably work best, and if it could have visibility tied to the config option that’d be even better (so it doesn’t explain collab stuff if they are disabled).

Root issue of collabs turning down their traitors won’t be solved by that, of course, but at least clarifies it for new people. The collabs refusing to aid is more RP and personal reasoning that we really shouldn’t try to force with code anyways. Some days you just want to get shit done and go home, not help overthrow the corporation.

**Comment by Aurorablade** [comment]
Will need to figure out the ? visability thing then.

**Comment by Shadeykins** [comment]
> 
> 
> Shhhh don't mention wiki updates we will wake up shady... _also i can add something here if someone tells me what/where_

_ree_

**Comment by Aurorablade** [comment]
Not to self: Fethas, Work on the prefrence thing on your day off please.

**Comment by Aurorablade** [comment]
Okay i can't figure out clean way to for tooltips (someone slap me in the right direction please) but i am gonna add something to the pref window. commit after i test.
Wording not set in stone please suggest alternates if needed.

**Comment by Aurorablade** [comment]
okay really do not like how it looks but gonna commit for wording feedback or if anyone has a idea for better placment (or how tooltips work) maybe i can put in the actual Selection dialouge popup?

**Comment by Aurorablade** [comment]
Sorry for delay. What it looks like on the rep selection popup. Again best place i can think to put it and look clean. Open for suggestion of location and wording (only gonna show up if collabs are on in the config) https://puu.sh/CEgIX/a7d661d61b.png
This is probaly done if no one has any suggestions for location or wording but will wait to see if anyone has anything.

**Comment by variableundefined** [comment]
Collaborator should stay away from the codebase until we think up of rule and mechanics changes that make them viable instead of a noob trap and a headache for admin.

It should not become a config option until that is solved.

**Pull request closed without merging**
