### PR TITLE
Adds some Vox Helmet Sprites, Small Sprite Tweaks, Gladiator Helmet Toggling & Moves Species-specific Icons into Appropriate Files

### PR DESCRIPTION
**Pull request by KasparoVy**
Just another one of my Vox sprite-dumps.

:cl:
rscadd: You can now toggle on/off the gladiator helmet's face-shield with an action button. This is totally cosmetic.
imgadd: Adds a bunch of new helmet sprites for Vox.
tweak: Slightly adjusts the Vox knight armour sprites (not the Templar armour) to look nicer with the new helmets.
fix: The Admin 'Select Equipment' debug verb now appropriately equips Armalis when the 'Vox' option is selected.
/:cl:

**This PR also moves all species-specific clothing (gloves, shoes, suits, uniforms, headwear, both worn and obj states) into appropriate files to dramatically reduce clutter in the Human ones. Should resolve the issue we've been having with certain icon files being full.**

This PR also fixes a bug where the Admin 'Select Equipment' debug verb wouldn't properly equip Armalis if you selected the 'Vox' option, and where it'd try to give them two uniforms. I also went ahead and gave the Armalis a blank uniform sprite so they could at least wear something underneath that armour (so they can use IDs and such).

Slightly tweaks Vox knight armour sprites (templar untouched).

Adds toggling of face-shield on gladiator helmet.
Adds the following helmet sprites for Vox:
- Justice 1 & 2
- NVG Helmet
- Sci-goggle Helmet
- Materials-goggle Helmet
- Meson-goggle Helmet
- Syndicate Helmet
- Thermal-goggle Helmet
- Riot Helmet
- Thunderdome Helmet
- Roman Helmets (regular & legionnaire)
- Gladiator Helmet
- Red/Blue Lasertag Helmets
- Blob Hat
- Knight Helmets (Templar, Grey & RGBY)

voxhelms

--------
I've had most of these sprites laying around for ages because I'd totally forgotten they'd been done some time last year. A few small tweaks and a quick rebasing was all it took to get this sorted out. I took care to avoid any conflicts in the .dmi files by using versions current as of 3 hours ago to add my sprites to.

### CODE REVIEW

**Comment by uraniummeltdown** [comment]
lit

**Comment by Fox-McCloud** [comment]
While you're at it, could you move all the vox suit and helmet sprites from `icons/mob/head.dmi`, `icons/mob/suit.dmi`, `icons/mob/clothing/hats.dmi`, and `icons/mob/clothing/suits.dmi`?

We're running out of space, and there's no sense in having species only sprites here.

**Comment by KasparoVy** [comment]
Sure thing, I'll sift through it all and get them moved.

BTW the addition I made to hats.dmi was the for the item state (hud) icon for the hat, that doesn't care for species

**Comment by KasparoVy** [comment]
Done, I went ahead and did it for the Plasmaman suits/helmets and Unathi stuff as well because their presence was more significant. Tested them all and everything still seems to work just fine (no missing icons in-game), even the Unathi rigs (the space suit versions worked too).

**Comment by KasparoVy** [comment]
Alright, every single species-specific clothing/suit/glove/shoe/head whatever icon (worn and obj) is now in its appropriate file instead of maxing out the icon_state limit on the Human ones.

This even worked for the Unathi breacher rigsuits

I also went ahead and fixed a bug that got turned up with the Admin 'select equipment' debug verb where it wouldn't properly equip Armalis if you selected the 'Vox' option, and where it'd try to give them two uniforms. I also went ahead and gave the Armalis a blank uniform sprite so they could at least wear something underneath that armour (so they can use IDs and such).

Plasmaman suits work too, as does the Vox clothes

**Comment by KasparoVy** [comment]
One last round of testing is due to make sure (especially) that the item state icons are what they should be

**Comment by KasparoVy** [comment]
Amended a small issue where I'd defined the usage of an icon where I shouldn't have in Rigsuits, seems like everything's mint but I'll take another look when I'm back at the end of the day.

**Comment by Fox-McCloud** [comment]
Thanks for moving all the species clothing sprites; it was really making things a nightmare for further additions.

**Pull request merged**
