### PR TITLE
Brig Doctor Jumpsuit.

### PR DESCRIPTION
**Pull request by TheBeoni**
Added brig physician jumpsuit. Brig Physician spawns with one, i also put one spare into locker.
j247zmq

### CODE REVIEW

**Comment by TheBeoni** [comment]
also i finally learned how to work properly with git

**Comment by FalseIncarnate** [comment]
:+1:

Kinda want to say possibly drop the melee armor of the jumpsuit to 5 (from 10), but that's probably not too noticeable anyways.

**Comment by ZomgPonies** [comment]
Do any other -jumpsuits- have armor?

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

All sec jumpsuits have melee armor--all science jumpsuits have bomb armor--all medical have bio armor--and all engineering jumpsuits have radiation armor.

**Comment by TheBeoni** [comment]
I dont really think its any great avantage...its just there.

**Comment by veganzombeh** [comment]
Personally think it should be kept at 10 to be consistent with other security jumpsuits.

**Comment by Robertha89** [comment]
I would say 10 melee 10 bio, with geneticist having 10 bio and 10 bomb, since there are not that many cross department jobs.

**Comment by NTSAM** [comment]
Eh, there's some floating dot things on the suit...

**Comment by TheBeoni** [comment]
ill look into it

**Pull request merged**
