### PR TITLE
Mineral Solidification Reactions & Additional Mineral-Based Reagents

### PR DESCRIPTION
**Pull request by Deanthelis**
-Changes the Plasma Solidification reaction to use Carbon, not Iron
-Adds in solidification of Uranium, Gold, Iron, and Silver
-Adds Osmium, Tritium, Diamond and Metallic Hydrogen as reagents (currently they do nothing) and solidification reactions for each
-All solidification reactions require 5 parts carbon, 5 parts frost oil and 20 parts of the mineral to be solidified
-Iron changed to Carbon in solidification to allow solidification of Iron

This is mostly setup for future reactions, and quality of life to make ground minerals a two-way street, instead of plasma being special.
And yes, I am aware that diamonds are made of carbon, but in this case the grinder is making them into a powder rather than the carbon reagent (and because solidifying carbon into diamonds would be OP).

### CODE REVIEW

**Comment by SamCroswell** [comment]
Wasn't the PR for 16fd717 denied?

**Comment by Fox-McCloud** [comment]
No point to Tritium, Osmium, Metallic Hydrogen, and iron solidification/reagents; all of these are going to get axed once TG mining arrives; heck, even with our current mining tritium is unobtainable and osmium is worthless.

**Comment by Deanthelis** [comment]
Tritium is obtained by smelting hydrogen instead of compressing it.
The robust harvest was a goof, but has also been removed anyway - I don't know why git added it to this PR, mostly because I'm bad at git.
Osmium is for the SUPERPACMAN as I recall. Or MSPACMAN, one of the two.

Regardless, still valid points.
Glad I did them correctly, though. When /tg/ mining rolls around I intend to do this with its minerals, since any material that can be liquified should have a solidification reaction in case of accidental grinding.

**Comment by Fox-McCloud** [comment]
The only materials you can obtain with TG mining are: plasma, silver, gold, iron (which makes metal sheets not iron sheets), uranium, and diamond.

That's it; nothing exotic--no smelting vs compressing BS and the only alloy is plasteel.

**Comment by Deanthelis** [comment]
I feel that having other alloys for other purposes would be rather useful, but I'll look into that once the port is done. 
Until everything is all set in stone, I'll put a hold on any of the solidification reactions or any of the other ideas related to mineral reagents I've had bubbling up in my head.

**Pull request closed without merging**
