### PR TITLE
Added an airlock near Atmospherics.

### PR DESCRIPTION
**Pull request by monster860**
That way, when atmos guys want to do stuff just outside the atmos room, they don't have to hunt down an airlock on the other side of engineering, or mess with the windows.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Map files contains `step_[x/y]`, you need to open the file in a text editor and replace all `step_x` and `step_y` with `pixel_x` and `pixel_y` respectively. The byond "nudge" buttons don't work correctly.

**Comment by monster860** [comment]
Didn't realise that you couldn't just set them to 0 for the check to pass. I was using the nudge function, and transferring the value to pixel_'s.

**Comment by monster860** [comment]
FUCK. Is there any way to fix this without recreating the pull request?

**Comment by monster860** [comment]
Anyways, this can be deleted.

**Comment by tigercat2000** [comment]
@monster860 You can close it yourself, by hitting the "Close pull request" button right under the comment box.

**Comment by Fox-McCloud** [comment]
pics, too.

**Pull request closed without merging**
