### PR TITLE
[AFD] Increases game engagement

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
As we are all aware, the game can become more un-engaging as time goes by, you grow older, you get burnt out, all sorts of issues surrounding it. You start to lose interest and the game can become boring to play for long periods of time.

Thankfully, I have a solution to rectify this.

dreamseeker_On7ZgkUOO9

**It was this or adding more title music https://youtu.be/sWTA8xUo8uU?si=oZmxTV-FMHYUbfPa**

## Why It's Good For The Game
Engagement good

## Images of changes
See above

## Testing
See above

## Changelog
:cl: AffectedArc07
add: Made the game more engaging
/:cl:

### CODE REVIEW

**Comment by LouiseIsntHome** [comment]
10/10 i hate it and you

**Comment by StrangeWeirdKitten** [comment]
An actual improvement in the game

**Comment by PowerfulBacon** [comment]
holy shit this is amazing, I want this so bad

**Comment by ike709** [comment]
image

**Comment by AffectedArc07** [comment]
> image

24th month screenshot invalid

**Comment by ReturnToZender** [comment]
Best PR ever

**Pull request merged**
