### PR TITLE
Adds assistant alt-titles.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## What Does This PR Do
Adds three alt-titles for assistant:
- Off-Duty
- Retired
- Intern

## Why It's Good For The Game
I've suggested it on [forums](https://www.paradisestation.org/forum/topic/24408-state-of-assistants-on-paradise/) and people seemed to like it!

These three titles will open a lot of RP possibilities! Help with defining who your character is, and why are they on a low-tier position!
- **Assistant**s, as before, may choose to assist.
- **Off-Duty** personel will need some more context. Imagine you have a character you enforce knowledge locks on, you want them to specialize in one specific field. But then you just want to hang around with friends without being called unemployed, or without people suspecting you've been demoted or something similar! I certainly do not like either of those, I usually explain it by a "paid break" NT issued to my characters. I know some other people are using a similar concept, I believe it being more apparent is a good thing.
- **Retired**. Let's say your character has been working for NT for quite a while now! They have been a great worker, but old age isn't a choice! For their efforts, NT has decided to extend their contract on minimal pay, and allow them to visit stations where they once worked! In addition, even currently, heads can "retire" their employees. It makes them into an assistant, but it's the thought that counts!
- **Intern** is pretty simple - you are hired on minimal pay to prove your worth to the company! While it's just a title, it may make it more clear that you/your character are willing to learn!

I **don't** think these are as out there as "trader" or "tourist" or "civilian". The three titles I am adding would make sense to show up on the crew manifest AND be paid for doing so!

For obvious reasons, I'm also **not** including any really gimmicky titles - you still need to talk with HoP for those!

## Testing
Spawned in as every job, IDs looked fine. Tested how tcomms behave - worked well!

## Changelog
:cl:
add: Assistants now have three new alt-titles to choose from! "Off-Duty", "Retired" and "Intern"!
/:cl:

### CODE REVIEW

**Comment by Danchi299** [comment]
Finally a good In Character reasons for why "Assistants" are not even trying to Assist

**Comment by Sadhorizon** [comment]
Not my intent, I'm rather ignoring that kind of people for this PR.
They can use them, yeah, but I still believe it will open more ways to RP for people that do actually care.

**Comment by Landerlow** [comment]
Retired people -> You could roleplay that you get paid a pension by NT.
Off-duty -> You take *paid* leave. 


I think this is a good PR and I would like to see this added. It's a nice touch. I even have a retired character already for it *flip.

**Comment by Carthusia** [comment]
> Retired people dont hang out at workplace and dont get paid Off-duty people dont hang out at workplace and dont get paid Intern i guess works but i dont see any reason.in it. Intern assistant is weird

To be fair, retired can have a pension, and offduty an interns can both be paid if their salary.

Overall i like the idea of more titles

**Comment by 1080pCat** [comment]
0/10 no "bridge hobo" or "slacker" title. 
Kidding, this is pretty neat.

**Comment by Landerlow** [comment]
Also if you want to get into RP/semantics: You could always RP that, even though you are off-duty/retired, you can hang around because you are allowed by NT and because you're deep in space and perhaps your home is far, far away. Or your relatives are all dead and you don't want to return, etc. In the end, this is a game.

**Review by Burzah — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Comment by hal9000PR** [comment]
job titles are normally just different words/specialties of the same job. a retired dude has nothing to do with assistant except from the fact that people play assistants as hobos

**Comment by Landerlow** [comment]
It brings some more options for roleplay/creativity. Just small touches. I think it's a good thing.

**Comment by Sadhorizon** [comment]
> I must say, it does have the least gameplay support from three titles I want to see, but it still has more depth to it than "assistant" while making SOME sense.

what was I on about that day, you ALREADY can retire in game, which does in fact make you an assistant

**Pull request merged**
