### PR TITLE
Icon change/fix for the toy tommy gun

### PR DESCRIPTION
**Pull request by shazbot194**
Adds a blue muzzle toomygun icon for the toy tommy gun to use.
This is so the toy tommygun no longer has to use the real tommygun's icon or what is has been using, nothing.

### CODE REVIEW

**Comment by shazbot194** [comment]
oops, it pulled everthing

**Comment by lordpidey** [comment]
You need to make a new branch on your local repository, and then push it to your remote, and then open a PR.

**Comment by shazbot194** [comment]
ok, thank you.

**Comment by LittleBigKid2000** [comment]
Tip: Open the repository in the command line thing. Type `git reset ParadiseSS13/master`, then `git push -f` to reset it back to this repository, if you want to get rid of all commits you've made to that repository.

**Comment by shazbot194** [comment]
Ok, I used a slightly different way. I already made the new pull if you want to have a look, but I will rember this after this pull either goes through or is closed.

**Pull request closed without merging**
