### PR TITLE
Adds Further Disabilities Checks for Communication-Heavy Roles

### PR DESCRIPTION
**Pull request by matttheficus**
## What Does This PR Do
Prevents `Nervousness` (Stuttering) and `Lisp` from roles that require large amounts of communication to be effective.

This includes:
- Head of Security
- Warden
- Captain
- Head of Personnel
- Nanotrasen Rep
- Blueshield
- Magistrate
- Internal Affairs Agent
- Chief Engineer

## Why It's Good For The Game
Not being able to understand someone, especially roles that require large amounts of communication, is absolutely abysmal.

NT would not hire someone who cant communicate properly to a job that requires speaking skills.

## Changelog
:cl:
tweak: extends disabilities checks to include nervous/lisp for communication heavy roles.
/:cl:

### CODE REVIEW

**Comment by ArcticValor** [comment]
did a stuttering blue once that got off the rails REAL quick (I mean I tried to ROLEPLAY, CAN YOU BELIEVE THAT?)

**Comment by DGamerL** [comment]
> We might also just have to revisit how we treat stuttering and slurring, imo they are insufferable for an MRP server.

Stuttering seems like the easiest one to reduce how much it should be applied, but I don't know we would make lisp more tolerable

**Comment by Screampuff** [comment]
The problem I think is that lisps as implemented just.. don't really happen, the "disability" is Looney Tunes Daffy Duck grade.  I don't think you can actually make it tolerable from an MRP perspective because it in of itself is a shitpost.

> > We might also just have to revisit how we treat stuttering and slurring, imo they are insufferable for an MRP server.
> 
> Stuttering seems like the easiest one to reduce how much it should be applied, but I don't know we would make lisp more tolerable

**Review by DGamerL — COMMENTED** [review]
This is missing the QM, as they recently became a head of staff.

Also, it might be useful for all heads of staff (RD and CMO) to also get the blacklist as stutter is *very* debilitating

**Review by lewcc — APPROVED** [review]
Code looks good

**Comment by matttheficus** [comment]
> This is missing the QM, as they recently became a head of staff.
> 
> Also, it might be useful for all heads of staff (RD and CMO) to also get the blacklist as stutter is _very_ debilitating

With the recent reduction in stammer's "power", I'm leaving CMO, RD, and QM to be the weird little eccentric roles if they so desire.

**Pull request merged**
