### PR TITLE
Makes the code better

### PR DESCRIPTION
**Pull request by Ludox235**
Just like God intended

:cl:
:rscdel: makes the code better by deleting trash 
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Again, meme PRs arent funny when you dont do them properly

**Comment by Ty-Omaha** [comment]
Maps need deconflicting

**Comment by Citinited** [comment]
interesting and original

**Comment by Ludox235** [comment]
> 
> 
> interesting and original

Thanks friend. Paradise station is my favourite station so far, and I am trying my best to make it better, I may not be the most experienced in coding, I am still learning and trying my best to make the server a better place for players.

**Comment by Fox-McCloud** [comment]
Cut this out.

As you were told the first time, meme PRs that have effort and thought behind them are humorous and a joy for us maintainers to read.

This is zero effort and absolutely stupid. It's not funny and you're wasting our time.

Cut the meming out or you will be removed from the git.

**Comment by Ludox235** [comment]
> 
> 
> Cut this out.
> 
> As you were told the first time, meme PRs that have effort and thought behind them are humorous and a joy for us maintainers to read.
> 
> This is zero effort and absolutely stupid. It's not funny and you're wasting our time.
> 
> Cut the meming out or you will be removed from the git.

I got called unfunny by a paradise maintainer. How will I ever recover?

**Pull request closed without merging**
