### PR TITLE
Removes the joy mask

### PR DESCRIPTION
**Pull request by DarkPyrolord**
As is says in the title, removes the joy emoji mask as this is a bit too silly and memey for anything medium RP related.

🆑 DarkPyrolord
rscdel: Removes the joy mask
/🆑

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by RomanaTColgate** [comment]
delet
this

Really though it's silly yeah, no great reason for it to exist as something in the vendor, maybe as an admin spawnable item but a vendor item is too much.

**Comment by uraniummeltdown** [comment]
no wayyyy 😂😂😂😂😂😂

**Comment by improvedname** [comment]
>meme item
>we have litteraly za warudo :^)

**Comment by DesolateG** [comment]
Right.. because the current state of Paradise is MediumRP....

**Comment by Fox-McCloud** [comment]
Only if you add in emoji pillows.

**Comment by FlattestGuitar** [comment]
Another aspect of the emoji mask is that the picture is actually distributed on an attirbution license, which we do not respect right now. Remov pls.

**Comment by Regen1** [comment]
tyrani

**Pull request merged**
