### PR TITLE
-tg- Mob Size & Refactors

### PR DESCRIPTION
**Pull request by tigercat2000**
tgstation/-tg-station#9290
tgstation/-tg-station#2387
in one.

This commit does two things:
 - Fairly major refactor of how mobs lying down actually works
 - Allows admins to easily modify a mob's visual size, for horrific events.

Screenshots:
attack

### CODE REVIEW

**Comment by Robertha89** [comment]
*tear, this is beautifull, now we can make pishsalver and upelkuchen, if you drink enough pishsalver you can vent crawl, or even vent walk, and with upelkuchen, you can open several doors at once, and block of the hallway!

**Comment by tigercat2000** [comment]
@Robertha89 That... is one use that we could do at some point, probably.

**Comment by MactoPerFuror** [comment]
The laying rotation thing actually seems fairly clever. 

And have been dying for some resizable sprites for a long time now.

**Comment by tigercat2000** [comment]
Oh, important sidenote: This is -tg- laying, so any time you get knocked down/rest/etc., you actually transition and rotate there, instead of instantly teleporting.

**Pull request merged**
