### PR TITLE
Adds an IPC screen

### PR DESCRIPTION
**Pull request by NTSAM**
Adds a rainbow IPC screen. Simple.

### CODE REVIEW

**Comment by NTSAM** [comment]
oh god i hope i did this right

**Comment by Gummin** [comment]
+1

**Comment by KasparoVy** [comment]
EPILEPSY WARNING

**Comment by tigercat2000** [comment]
that actually looks really damn good
:clap:

**Comment by NTSAM** [comment]
:smiley:

**Comment by KasparoVy** [comment]
At first I thought there was a rogue pixel in the sprite at the bottom right of the gif, but then I realized
It was just your mouse, gg

**Comment by Fox-McCloud** [comment]
@NTSAM 

changelog

**Comment by taukausanake** [comment]
@Fox-McCloud I don't think we have instructions on how to Changelog, at least none that I've seen. Could you explain to us or is there a topic about it?

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/3117

**Comment by NTSAM** [comment]
oh ok

**Comment by NTSAM** [comment]
Am I still doin' it right

**Comment by Spacemanspark** [comment]
:+1:

**Comment by taukausanake** [comment]
I think you did it right. I wonder if all those # are needed though. Don't they just comment out things?

**Comment by Tastyfish** [comment]
Yes, you did it right.

**Comment by NTSAM** [comment]
yay

**Comment by TheDZD** [comment]
This looks amazing.
:+1:

**Comment by Tastyfish** [comment]
Although it's generally good to make a new branch instead of working directly on your master branch, eg. so you can easily checkout back to master if the branch becomes a hopeless mess. Doesn't really matter though.

**Comment by Crazylemon64** [comment]
:tada: woooo :tada:

**Comment by NTSAM** [comment]
yeeeee

**Comment by Spacemanspark** [comment]
:+1:

**Pull request merged**
