### PR TITLE
Updates our webhook processor

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
Updates the webhook processing system to TGs latest, as then we have native PR balancing, instead of it running on another persons server like tiger had it before. This also moves credentials over to a separate file. I have attempted to modify this to suit para needs, but I am not 100% sure. I would appreciate thorough review. Thanks!

**Changelog:**
*Was told its required despite it being backend and not even modifying any game code*
:cl: AffectedArc07
tweak: Updates the git webhook processor 
/ :cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
MSO the legend at it again

**Comment by AffectedArc07** [comment]
image
You commented in the future

**Comment by Aurorablade** [comment]
It wasn't running on tigers server..hell i don;t think tiger had an actual server. As it stands i think this is including alot of stuff we don't/can't currently support.

**Comment by AffectedArc07** [comment]
@Aurorablade
Speaking with Alffd on discord, tiger had his own VM which he then closed when he went, I assume this ran stuff like Cyb and the other web things. 

As for stuff we don't care/support, this is the script that powered the contributions leaderboard. I might try to reverse engineer it to just crawl the git for the points, but even then the script is still being updated incase Alffd wants to use a new one, or further downstreams do.

**Comment by Aurorablade** [comment]
@AffectedArc07 I know for a fact it never ran on his servers. Contrib however was a javascript thing that got data straight from github.

**Comment by Aurorablade** [comment]
Only if it has some updated functionality or code efficeny then what we have currently.

**Comment by AffectedArc07** [comment]
Generating the PR balances.

Speaking of which, python and git libraries to the rescue

**Comment by Aurorablade** [comment]
We don't need the PR Balance generating as we STILL have what we did for it. That didn't leave with tiger.

**Comment by AffectedArc07** [comment]
[Are you sure about that](https://contrib.nsscyberiad.net)

**Comment by Allfd** [comment]
I was told not to do this when I ported it,  I am not 100% on why it broke things, but were you able to test it for compatibility?

**Comment by AffectedArc07** [comment]
A **LOT** of testing later, cant seem to make this work well

**Pull request closed without merging**
