### PR TITLE
Improves Drinking Glass Colorization

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Drinking glasses will not mix their color from the reagents contained within them if the primary reagent doesn't have a unique glass icon. In other words, no more brown glasses (unless the reagents mixed are explicitly brown).

This does ***NOT*** remove the unique drink icon sprites; this just makes it so that drinks that do *not* have a special/unique icon will be colored, instead.

img

:cl: Fox McCloud
add: Non-designated drinks now mix their colors from the reagents within them
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Certainly looks loads nicer.

**Comment by taukausanake** [comment]
I'd like to see something similar with bar drinks in shot glasses. Speaking of, does this affect shot glasses too? Might be nice unless those use a different system for colors/icons

**Comment by Fox-McCloud** [comment]
@taukausanake shotglasses already do color themselves based on the reagents inside of them.

Until someone cares enough to sprite specific shotglass sprites for reagents though, there's no point to there being a shotglass "drink specific sprites" system.

**Comment by FalseIncarnate** [comment]
There are some unique sprite drinks that would make more sense on a shot glass than a full (pint?) glass (toxins special and the real-life shot B-52 come to mind), though I think it is fine for most drinks to stay as normal coloring based on their reagents. Rather hard to tell the difference between a shot-worth of a martini from a shot-worth of a silver tequila unless you are REALLY familiar with both in such small amounts (in which case why are you doing shots of a martini you silly drunkard).

**Pull request merged**
