### PR TITLE
Secure Armory

### PR DESCRIPTION
**Pull request by orelbon**
Adds Blast doors, making for easy access, also gives the racks windoors so the armory dosent all vent when there's a breach.(hopefully i didn't screw everything up, as this is my first large map edit)

amory edit

### CODE REVIEW

**Comment by orelbon** [comment]
FUUUU, ugh someone people halp

**Comment by tigercat2000** [comment]
@orelbon It failed the step check, you can't use the 'nudge' commands or shift+arrow keys in dream maker or you break movement. 

Open the map file in a text editor, replace all 'step_x' and 'step_y' with 'pixel_x' and 'pixel_y'.

**Comment by SamCroswell** [comment]
Oh lord, the last thing we need is for security to be even more needlessly obtuse. If you want to do this (And I don't think it's a horrible idea) I recommend moving the secure armory down into the HoS office hallway with the blast doors where the double door is now, as well as one on the HoS's side and Warden's side.

**Comment by orelbon** [comment]
@SamCroswell id love too but im too lazy for that, it was hard enough making this change lol

**Comment by orelbon** [comment]
@tigercat2000 YAY

**Comment by orelbon** [comment]
@SamCroswell I might start working on your suggestion, but itl take a lot of tim, and i have school and shit so idk.

**Comment by Fox-McCloud** [comment]
That's pretty damn ugly, not to mention it makes armory sneaking next to impossible.

**Comment by orelbon** [comment]
I'll admit it isn't the nicest thing to look at, I'm gonna work on it tommorow, but it's 12am here so I'm going to bed

**Comment by Earthdivine** [comment]
I don't see the point of this? If it's to allow security officers to run in and arm themselves, the win doors will stop that anywas unless they are regular sec access. Security running in to arm themselves is also very very bad, as they will NOT distribute weaponry, they will load up on what thy can fit and run out, you can see this with zip ties and handcuffs, so any officer not in security when it's opened will be sod out of luck. The placement looks real bad, this kind of thing will require a much bigger overhaul of the map then adding a hallway, and as fox says, you no longer can easily break into it. As there's only one point of entry now.

On the plus side, nuke ops can totally fuck up security with this as it will always breach into security.

**Comment by Plotron** [comment]
I do not like.
The idea of having an emergency "ARMOR OUT!" button may sound good, but I think that handling weapons is the most responsible job of the warden and HoS, and it's better to keep it harder/more time-consuming, more complicated and better controlled, just the way it is now.
It's not a military vessel.
Also what Fox said - it is ugly.
If you feel like you have to expand Brig, here's an idea: dedicated monitoring room.

**Comment by orelbon** [comment]
ok here's my reasons why this is a good idea; 1. the warden is not forced to open the shutters, if he wants to distribute weapons by hands it's his prerogative, this also makes it easier for the warden if he doesn't want to distribute everything by hand, and so he won't have to get a locker and pack it with things because he can't carry all the thing needed in the armory 2. it gives the security officers easy access in case the warden, HoS, etc.. are not available, so the Ai just needs to press a button 3. security officers have no reason to take more than they need, i dont see security officers taking more than they need when i put all the riots suits, masks, and guns on the tiny table in the warden's office, also the warden or HoS can monitor them if they feel it necessary

and yes i know it looks like shit, but i will edit it using @SamCroswell sugestion.

**Comment by orelbon** [comment]
@tigercat2000  any idea why the new merge conflicts, is it that fox's barber update got merged?

**Comment by tigercat2000** [comment]
i don't have any idea

**Comment by orelbon** [comment]
welp im just gonna close this and make a new branch

**Pull request closed without merging**
