### PR TITLE
Maint Loot

### PR DESCRIPTION
**Pull request by Keilden**
Adds more stuff to the random maint loot generator.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Um. What. this isn't...correct...at all...this isn't even from...a fork of the codebase?

**Comment by Keilden** [comment]
Well I had no idea what I was doing since I am new to git.

**Comment by Robertha89** [comment]
https://github.com/ParadiseSS13/Paradise/blob/e7ea5ee4cf4856ea4d83c6baebfcb6edd371b1d7/code/game/objects/effects/spawners/lootdrop.dm

this is the file you wanna modify

**Comment by Keilden** [comment]
so I modify them directly at github?

**Comment by Robertha89** [comment]
you can do that, or you clone a copy of your fork, make the change local, use the github client to choose what files to upload, make a commit, synch it, go into your fork, and add a commit from there to here. and there we go.

**Pull request closed without merging**
