### PR TITLE
Clean Up In Sprites: Effects Edition

### PR DESCRIPTION
**Pull request by TrashDoxx**
## What Does This PR Do
* I just deleted duplicates and files I couldn't find in the code, I also renamed a few things.

## Why It's Good For The Game
* I think this junk is of no value and will never be used.

## Changelog
* No player-facing changes.

### CODE REVIEW

**Comment by TrashDoxx** [comment]
Tomorrow. I'm busy now.

**Comment by TrashDoxx** [comment]
Oh shit, few moments.

**Comment by TrashDoxx** [comment]
@AffectedArc07 Okay, the force-pushes were not the best idea, but I got through it.

**Comment by TrashDoxx** [comment]
@AffectedArc07 Okay, the force-pushes were not the best idea, but I got through it.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
