### PR TITLE
Converts inline CSS class spans to #defines

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do

# YES THIS IS A HUGE PR BE CAREFUL OPENING UP THE FILES TAB

Updates almost every instance of `"<span class='something'>text</span>` to `span_something("text")`. Directly inspired by how they've done it on /tg/.

Spans are now found at `code/__DEFINES/span.dm`, which are almost entirely inclusive of the text spans we have in our .css files.

I did a basic regex find-and-replace before going through and verifying (`"<span class='(\w+)'>([^<]*)<\/span>"`). It wasn't too too much work to make this happen, so if this needs to wait before being pulled in, it'll be pretty easy to merge and update.

## Why It's Good For The Game
With these functions in place, it's so much easier to add a warning span to some text, for instance. This should generally make writing code involving chat messages a lot smoother, and should hopefully make it a lot harder to forget a trailing `</span>`.

### CODE REVIEW

**Comment by lewcc** [comment]
drafting for a little bit, turns out I missed a bit more than I thought lol

**Comment by lewcc** [comment]
> why

Fair question haha

It's something I've been contemplating for a while, and I do think it makes writing code that involves css classes a lot harder to screw up. It's syntactic sugar, sure, but it is nice to work with, at least from my experience working with /tg/code.
If it's more amenable, I can look at revisiting this for just the most common (notice, danger, userdanger, warning)

That being said, I'm not too attached to it if this is generally regarded as a Bad Idea. There is still a good bit of work that would need to go into making sure this is done cleanly

**Comment by AffectedArc07** [comment]
Yeah given how much of a conflict bomb this is and how we don't really *gain* anything from it, I am gonna side against this.

**Comment by lewcc** [comment]
Yeah, I don't really think this is gonna end up being worthwhile lol
Screenshot_20220709-132013

**Pull request closed without merging**
