### PR TITLE
Buffs Magistrate 👌

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlaaaaaattestGuitar
tweak: Magistrate now starts their shift with a pair of white gloves as well as Bridge and Meeting Room access.  
/:cl:

As per [this](https://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=9999) thread.

Discuss below, I will adjust the PR.

### CODE REVIEW

**Comment by tylerh95** [comment]
Yes, I love you. ❤️

**Comment by DesolateG** [comment]
Gloves are OP..

**Comment by Necaladun** [comment]
Sounds great except - why vault?

**Comment by SamHPurp** [comment]
Why Vault?

**Comment by Birdtalon** [comment]
Yeah no need for Vault access. Meeting room fine.

**Comment by tylerh95** [comment]
@DesolateG We don't want the magistrate getting paper cuts.

**Comment by DesolateG** [comment]
@tylerh95 he needs one of those little rubber finger things to make it easy to flip through the pages.

**Comment by tylerh95** [comment]
@DesolateG I would die.

@FreeStylaLT What was the reasoning for the vault access?

**Comment by FlattestGuitar** [comment]
The vault access seemed adequate, as they are meant to be a power-wielding command member. Vault access is almost completely meaningless as is - NT rep has vault access, among other people.

**Comment by tylerh95** [comment]
@FreeStylaLT Then I suppose it makes sense.

**Comment by SamHPurp** [comment]
I still don't think they need vault access at all. Their remit is space law... thats it.

I'm even kinda against them having bridge access.... they should be in the brig, their office, or the court room.

**Comment by tylerh95** [comment]
@SamHPurp The vault access I understand, but as a NT assigned VIP, similar to the Rep, they do a lot of interfacing and interacting with heads.

**Comment by davidchan13** [comment]
@FlattestGuitar Gonna need to explain the Vault access here.

**Comment by SamHPurp** [comment]
https://nanotrasen.se/wiki/index.php/Magistrate

I can see literally zero reason they need bridge access, let alone vault.

**Comment by davidchan13** [comment]
@SamHPurp I can actually get behind Bridge access, as they have the ability to overrule the Captain on executions or punishments, bringing their legalise document or just throwing Space Law at the Cap in their office fits the profile.

**Comment by tylerh95** [comment]
@SamHPurp They have command radio access. Space law is enforced upon crew members of all divisions. They do hold the authority to overrule the Captain on Space Law matters. I don't see why bridge access is unreasonable.

**Comment by SamHPurp** [comment]
@davidchan13 As Magistrate, I'd call the Captain into my office, rather than go to his.

Wield power!

**Comment by davidchan13** [comment]
@SamHPurp That would require them to respect your authorita to begin with. If the Cap knows they can hide on the bridge and you got no power to come in and rip em apart, makes no sense. Being able to storm the bridge/HoS/Cap office and law down the law makes it so you can impose your own authority and power legally.

**Comment by tylerh95** [comment]
@SamHPurp the same could be said for the NT Rep. They have a fax machine in their office, and don't "require" bridge access to do their job. The magistrate is almost the space law equivalent to the Rep and deserves access to the bridge to be able to properly work with command.

**Comment by tylerh95** [comment]
Just adding on, the Magistrate wiki page says this: 

> Try to be an active voice in Command Comms, helping to deal with issues in other Departments. While not exactly your field of operations, helping to enforce Standard Operating Procedure may also be a worthy use of your time.

**Comment by SamHPurp** [comment]
Except the NT Rep is an advisor for command.

The Magistrate is an advisor for sec.

**Comment by tylerh95** [comment]
@SamHPurp Not according to what I posted above.

**Comment by FlattestGuitar** [comment]
Let's not bring wiki pages into this, they're definitely not something we should base game design on. 

Magistrates spend most of their time in security, but if something along the lines of Vox Raiders was taking place, they should probably get a say in how to treat them, as well as be able to take part in any meetings command may have. 

If Magistrates start faffing around on the bridge instead of doing their job, we can easily revert this change. It's a very small one.

**Comment by SamHPurp** [comment]
@FlattestGuitar But for such rare occurances (such as the referenced game mode that doesn't even exist anymore) - they can just be invited onto the bridge.

**Comment by sothangel** [comment]
Bridge access is a nice addition, meeting room too. The vault is a bit strange, but I don't think Captain Office access would be appropriate; wouldn't it mean the Magistrate could use communications consoles like the Captain could?

**Comment by jughu** [comment]
The magistrate announces
IM THE LAW YAYA SHRIEK!!!

**Comment by SamHPurp** [comment]
@jughu then gets job banned.

They supposed to be the one sane person on the station. The one that can always been relied upon.

**Comment by Birdtalon** [comment]
Magistrates aren't supposed to be a member of command though?

**Comment by Aurorablade** [comment]
"Bridge, Meeting Room and Vault access."

As a magistrate player, NO. They do not need that. I cannot support this PR with that there.

**Comment by theColdflame** [comment]
45_karma

**Comment by SamHPurp** [comment]
@Birdtalon Nope. Even confirmed by Neca on the forum thread on this very topic. They aren't command.

**Comment by tylerh95** [comment]
@SamHPurp They are not command, that is correct, but the authority they wield and their responsibilities have them often working with and interacting with command. I completely agree that vault access isn't needed, even though it is pretty pointless- but bridge and meeting room access would help them by allowing them access to the command area to properly work with the heads of staff when needed.

**Comment by Aurorablade** [comment]
@tylerh95 they don't need it. At all. They are not command. They had access to the command channel and a fax. thats all they need.

**Comment by tylerh95** [comment]
@Aurorablade They don't "need" it, but it would be nice for magistrates to be able to have access to the bridge and the meeting room in order to partake in things that involve Space Law or other related items. I don't understand what is so crazy about that, especially considering that they are implanted, cost 45 karma, and already heavily scrutinized by staff.

**Comment by davidchan13** [comment]
The NT Rep and Blueshield aren't command either but they have very good reasons to be on the bridge to do their jobs. Speaking with the heads as Magistrate not only helps give them presence on the station but helps advise on matters of Space Law.

More than once in the last month or so while playing HoP, CMO or RD I've been part of a Command discussion on how to deal with another member of Command who was either a traitor or incompetent to the point multiple members of the crew were seeking not only their demotion but brigging.

I've also noticed that while Blueshielding, Captain, HoS and HoP alway seem to come to me for advise just because I am on the bridge monitoring the heads, particularly on issues the Magistrate or NT Rep would be better qualified to deal with.

**Comment by tylerh95** [comment]
@davidchan13 Completely agreed. Out of sight, out of mind. With the magistrate tucked back in the brig, or in his office, I feel like they are often forgotten about or ignored.

**Comment by SamHPurp** [comment]
But the NT Rep and Blueshield ARE advisers for command....

Magistrates deal with Space Law.

Where is space law dealt with? The brig.

**Comment by SamHPurp** [comment]
In instances where it'd be good to chat to the magistrate, perhaps go to their office? Or invite them onto the bridge.

Magistrates with bridge access are going to hang out there. When they should be hanging out in the brig.

**Comment by tylerh95** [comment]
The **_entire_** argument against this seems to be "oh no they'll hang in the bridge what will we do". Bad magistrates get weeded out rather quickly. If a magistrate is found to be simply hanging around the bridge, they'll probably get bwoinked. Don't punish the majority just because there are a few who do stupid shit.

**Comment by Aurorablade** [comment]
again. thats why they have a fax and a command headset. They do not need bridge access..AT ALLL. EVER.

**Comment by tylerh95** [comment]
@Aurorablade So besides "hanging out in the bridge" what is the downside of giving them bridge access?

**Comment by Aurorablade** [comment]
hanging out on the bridge is not my arguement. They just do not need it. They are not command but they carry thier own amount of authority in regards to law. and unless its a law based thing they need to be in on, they do not need anything to do WITH command.

NT rep and Blueshield are not command BUT they need to be related TO COMMAND. BS for protecting heads and NT Rep for protecting NTs interests. That makes sense.

I do not find much use for a magistrate having command/bridge access besides a headset to communicate with them.

**Comment by davidchan13** [comment]
@Aurorablade The headset isn't a very good point. At all even. They are one of 2 jobs in the entire game that doesn't have access associated with their granted radio channels. Everyone else with Command access has bridge access. 

The only other job treated this way is the Mechanic, who many have been arguing should have engineering access for a while now.

**Comment by Aurorablade** [comment]
@davidchan13 just cuase they have the headset dosen't mean they need the access. same goes for mechanic. and I love that role right there.

**Comment by SamHPurp** [comment]
I literally can't see why this is being argued.

They belong in the brig. The cases where they should legitimately be on the bridge is what, every 10 rounds?

No extra access. Do your jobs.

**Comment by Aurorablade** [comment]
Don't be rude sounding about it.

**Comment by FalseIncarnate** [comment]
I can understand meeting room access, which given the current layout of Boxstation does require Bridge access (or HoP's access) to simply reach. The vault, however, holds nothing of importance to a judge.

If there was an entrance to the meeting room from the hall, rather than only through the bridge and HoP's office (ignoring the plastic flaps in that maint closet), I'd wholeheartedly agree with only adding meeting room access. As pointed out, bridge access would give them access to the comms console, which would inevitably lead to magistrates sending out worthless announcements from it because they have nothing better to do.

**Comment by tristan1333** [comment]
The Judge can't be bribed, if he has access to the stations most valuable assets

**Comment by ktoma36** [comment]
Aren't we forgetting that there are internal affairs agents that are tasked to deal with most issues. The magistrate is meant to deal with major cases and advise the internal affairs agents below him when needed. Most of the legwork of collecting evidence and arguments should be done by the IAA. Of course if proven incompetent a magistrate can do the legwork themselves but in most cases a magistrate should not be tethered to the brig. While it is helpful for them to remain in sec to make sure space law is being followed the magistrate should not be expected to stay in sec the entire shift. They should be expected to be on call at all times though.

Also I think having vault access opens up some interesting role play value. Where else would you store the transcripts of important trials?

**Comment by Aurorablade** [comment]
file cabients or the secure briefcase?

**Comment by tylerh95** [comment]
@ktoma36 While I don't know if the vault makes sense for that, I agree. Could be an interesting twist.

**Comment by Dinarzad** [comment]
I don't think Vault access is entirely sensible for the Magistrate to have, but the Bridge is more then reasonable.

He's not an official member of command, but he does overrule even the Captain in matters of Space Law, and while he can confer with him over the Headset, there's times when you really don't wanna clog the entire Command channel with two people bitching at each other, which is where the Magistrate coming to the bridge to hash it out personally would be ideal.
And meeting room access would make sense, as he is the end-all authority on the Law, so if the heads of staff need to have a meeting, he is the legal side of the NT Rep.  NT Rep looks after SoP being followed and NT's best interests, the Magistrate makes sure that command are doing all that legally.

**Comment by owenowen212** [comment]
I can appreciate that some people see see the magistrate as being on par with command, considering their important position on the station, but since they are not command I don't think they should have command-like access. Especially the vault access.

**Comment by davidchan13** [comment]
How can people honestly say the Magistrate is not Command there for shouldn't get Bridge access when the NT Rep is literally the counterpart to this role and spends 99% of their time on the bridge when they are supposed to be ensuring SOP and NT interests are being upheld?

**Comment by Kyep** [comment]
Give them bridge and meeting room access, but not vault access.

**Comment by Birdtalon** [comment]
Magistrate can easily ask if he needs to come onto the Bridge. Otherwise why would be have access?

Think about it this way. Members of Command have access to the bridge to control the smooth running of the ship. 
The NT rep's purpose is to ensure the objectives of NT are being carried out whilst remaining outside the chain of command. That being said they are a high ranking member of NT in a corporate sense and therefore should have Bridge access as a representative of the company that owns and runs the station.

The magistrate is there to judge people. His only interference with command should be if the Captain has passed an illegal sentence due to a Capital crime. Otherwise his place is on the Brig. Why would he need Bridge access when really a judge isn't all that important? I think some of you are misjudging the importance of the job in relation to commanding a station. And the Karma cost of the role should not be taken into account so it's a pointless argument to lobby for additional privilege because it costs a certain amount of KP.

**Comment by emmanuelbassil** [comment]
I don't see why the Magistrate needs bridge access. He only interacts with
one head, which is the HoS. Any interactions with the Captain is when the
HoS fails to help or opposes the magistrate.
The NT Rep, on the other hand, interacts with all heads according to his
needs.

**Comment by KasparoVy** [comment]
Give them admin-level access and a pulse annihilator and call it a day. [/s]

**Comment by Anoonki** [comment]
> Give them admin-level access and a pulse annihilator and call it a day. [/s]

Finally.
Someone who's not shitposting on this PR.

**Comment by Fox-McCloud** [comment]
He has no reason to have vault access, especially when nothing in the vault even inherently relates to space law and more relates to top secret documents and information.

**Comment by tylerh95** [comment]
@FlattestGuitar I feel like the general consensus between both sides is at least no vault access. Perhaps remove that and then we might be good?

**Comment by Aurorablade** [comment]
i won't be happy with them having bridge access at all. but yes i am repeating myself.

**Comment by tylerh95** [comment]
Another thing I wanted to point out is that the Magistrate is in charge of the IA Agents. Bridge access would be very helpful to coordinate with other heads of staff relating to any IA Reports that need to be reviewed.

**Comment by SamHPurp** [comment]
It doesn't happen often, but I agree with @Aurorablade

**Comment by Regen1** [comment]
No to vault access

**Comment by FlattestGuitar** [comment]
The vault access has been removed.

Personally, I find it to be something hard to abuse and that could provide interesting gameplay opportunities, but we can leave it for later, seeing as it's easily the most controversial aspect of this PR so far.

Right now it's gloves and Bridge access.

**Comment by Aurorablade** [comment]
They. Do. Not. Need. Bridge. Access.

**Comment by Spacemanspark** [comment]
I don't see a particular problem with them having it; I see them in there anyhow with little to no ill effect most of the time anyways.

**Comment by Dinarzad** [comment]
> They. Do. Not. Need. Bridge. Access.
Why. Don't. They. Need. It?

**Comment by Lady-Luck** [comment]
I've always found it very strange how the Magistrate can't get to the meeting room. The gloves are nice too. Good change.

**Comment by FlimFlamm** [comment]
You need bridge access to get to the meeting room as it stands (right?)

That said, there **IS** a time and a place for the magistrate to be on the bridge. Informal meetings of heads on the bridge are important, and while the magistrate is not an actual head, they still represent nano-trasen and space law (and are usually filled with useful input). During extra-ordinary emergencies, the importance of the magistrate to Nano Trasen should make them a priority for protection, including when all the other heads flee into a locked-down bridge.

Furthermore, If a Captain is about to execute someone on the bridge, and a screaming magistrate is stuck beeping the door like some raving vagabond, it just seems like would get laughed at.  I'm all for a magistrate faxing CC directly in order to call a DS on the craptain, but the magistrate should at least be able to yell at the captains face before doing so.

Captains office access? No. I would be for adding an additional layer of blast doors in the captains office so that if and when the magistrate or NT rep need to call the law, they can hilariously barricade themselves into their office to make people do it _the hard way_

**Comment by Fox-McCloud** [comment]
conflicts.

**Comment by LightFire53** [comment]
The access that isn't added here that concerns me is that of the lethal injections and exile implants. For some reason, the person who can over rule the captain over space law needs the captain to open those lockers still.

**Comment by tylerh95** [comment]
@LightFire53 I was playing magistrate a few rounds ago and was able to open the lethal injection locker. Need to test exile implant locker. Also, while we're on the note of access changes, perhaps they should have Gateway access for the purpose of exiling.

**Comment by Necaladun** [comment]
I honestly see this as having less effect than the conversation on this github, don't see any harm tbh. Magistrates are rare enough and comdom ones get a lot of admin attention.

:+1:

**Pull request merged**
