### PR TITLE
Adds in the pilot suit and security jetpack [WIP]

### PR DESCRIPTION
**Pull request by shazbot194**
This PR replaces the pod pilot suit with the one Dumbdumn5 made. I also replaces the pod pilot's jetpack with a red colored one. It also fixes a small issue with the mining jetpack where both the left and right hand icons were in the left hand's folder.

kza85fpkrly2d8v-whtmbw
jrho_j5-ty_cb9msng6dnw
zxfzl94gs4srevreyrq6la

This is a [WIP] as more sprites are being added.

🆑 Shazbot-code and Dumnbdumn5-sprites
Add: We finally found the shipment of special pilot hardsuits, and red painted jetpacks. No they weren't being held by mercenaries for random, why would you ever say that, Hahaha...
Fix: Removes bluespace cloaking device from mining jetpacks that only activates when you held it in your right hand.
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
- needs pics
- needs to be mapmerged

**Comment by shazbot194** [comment]
I am adding them, this is about 30 seconds old.

**Comment by shazbot194** [comment]
So, I haven't done a map merge before, is there more to it then just adding in and taking out items?

**Comment by Necaladun** [comment]
In the pipe, 5 by 5.

**Comment by scrubmcnoob** [comment]
They look nice and would be refreshing to see.

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/blob/master/tools/mapmerge/instructions.txt

**Comment by shazbot194** [comment]
Thank you Fox, I will get to work on fixing the map commit.

**Comment by granodd** [comment]
These are effectively the same as sec hardsuits, yea? Just the different look and all?

**Comment by shazbot194** [comment]
Yup, so much so they are just a sub of the security hardsuit, and changes to them balance wise would also cover this suit.

**Comment by Fruerlund** [comment]
Look frickin awesome.

**Comment by FlattestGuitar** [comment]
Can we see how these look on different species, if at all? Would be really nice to have that functionality.

**Comment by KasparoVy** [comment]
Please try to keep up species sprite parity.

**Comment by Dumbdumn5** [comment]
Sending species sprites so far to people who DM me over discord, lemme know if you need them, not here right now because all the helmets/suits aren't finished yet!

**Comment by shazbot194** [comment]
Very much like Dumbdumn5 said, as soon as all the sprites are done and are put in I will post more pictures with all the races.

**Comment by Anticept** [comment]
http://img.amiami.jp/images/product/main/132/FIG-KAI-5466.jpg

**Comment by shazbot194** [comment]
So my github master has quite literally exploded, and I cannot make anymore update, I will be closing this pull and remaking it when I have all the sprites needed.

**Pull request closed without merging**
