### PR TITLE
Arcade Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the arcade machines to TG's latest improvements.

- Sounds for the battle arcade
- Prevents unlimited EMP farming of toys
- Rework of Orion Trail

The Rework of Orion trail is the most noticeable; you can now kill off your own crewmembers to save on resources. Additionally, there's new events, such as the space port (buy/sell/trade crewmembers, attempt to raid it, or buy/sell/trade other goods), and changelings (eat more food, and can kill crewmembers, but they, themselves can be eaten for food by the crew). Lastly, the arcade has a whole slew of unique effects if emagged----but if you can survive an emagged game, you will receive a toy ship that is basically a syndicate minibomb.
 - This game was already great, IMO, now it's even better; the emagged effects are downright hilarious.

Other
- Adds in a proc that allows all atoms to "speak". This is similar to the proc that a number of existing machines and bots use, but this can be used universally---you can also specify what speech verb particular atoms have, as well.
 - This is by no means perfect or ideal, but it's a quick and dirty way to give the appearance that an atom is, in fact "speaking".

### CODE REVIEW

**Comment by Robertha89** [comment]
##Prevents EMP farming of toys
:-1: x ∞
That is just cruel.

**Comment by Fox-McCloud** [comment]
Let me clarify--you can still emp farm toys, but the machine is going to blow up after you EMP, so you can't just singulo farm for all the toys in the world with literally zero effort.

You'll need R&D's help to repeatedly toy farm.

**Comment by Robertha89** [comment]
Currently there is a small chance of the arcade breaking, which can be fixed via new sheet of glass, rather then instantly destroy it, have it an even smaller chance of destroying, do circuit boards even had a 'destroyed' version, so if you say shoot a computer, there is a also a small chance of destroying the circuit? Might be outside of the scope of this PR, but would make something much greater, plus consistancy so all computers can go booom from EMP's.

**Comment by taukausanake** [comment]
Orion Trail sounds a little bit more like FTL I want to say. Kind of interesting

**Pull request merged**
