### PR TITLE
Clean out unused fluff items

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit cleans out any unused fluff item from the fluff item defines
file.

Mecha paintkits have been moved to mecha/paintkits.dm, and the fluff path
in them has been removed.

Helpful list of what has been removed:
 - /obj/item/weapon/paper/fluff/sue_donem
 - /obj/item/fluff/wes_solari_1
 - /obj/item/fluff/sarah_calvera_1
 - /obj/item/fluff/angelo_wilkerson_1
 - /obj/item/fluff/sarah_carbrokes_1
 - /obj/item/fluff/ethan_way_1
 - /obj/item/fluff/val_mcneil_1
 - /obj/item/fluff/steve_johnson_1
 - /obj/item/fluff/david_fanning_1
 - /obj/item/fluff/john_mckeever_1
 - /obj/item/fluff/maurice_bedford_1
 - /obj/item/weapon/book/fluff/johnathan_falcian_1
 - /obj/item/weapon/folder/blue/fluff/matthew_riebhardt
 - /obj/item/fluff/victor_kaminsky_1
 - /obj/item/fluff/ana_issek_2
 - /obj/item/weapon/soap/fluff/azare_siraj_1
 - /obj/item/weapon/clipboard/fluff/smallnote
 - /obj/item/weapon/storage/fluff/maye_daye_1
 - /obj/item/weapon/storage/firstaid/fluff/asus_rose
 - /obj/item/weapon/fluff/cado_keppel_1
 - /obj/item/device/camera/fluff/orange
 - /obj/item/device/camera/fluff/oldcamera
 - /obj/item/weapon/id_wallet/fluff/reese_mackenzie
 - /obj/item/weapon/reagent_containers/glass/beaker/large/fluff/nashida_bishara_1
 - /obj/item/weapon/reagent_containers/glass/beaker/fluff/eleanor_stone
 - /obj/item/weapon/storage/pill_bottle/fluff/listermedbottle
 - /obj/item/weapon/reagent_containers/pill/fluff/listermed
 - /obj/item/clothing/mask/fluff/electriccig
 - /obj/item/weapon/reagent_containers/hypospray/fluff/asher_spock_1
 - /obj/item/weapon/card/id/fluff/asher_spock_2
 - /obj/item/weapon/clipboard/fluff/mcreary_journal
 - /obj/item/device/flashlight/fluff/thejesster14_1
 - /obj/item/clothing/gloves/fluff/murad_hassim_1
 - /obj/item/clothing/gloves/fluff/walter_brooks_1
 - /obj/item/clothing/gloves/fluff/chal_appara_1
 - /obj/item/clothing/gloves/fluff/ashley_rifler_1
 - /obj/item/clothing/glasses/fluff/uzenwa_sissra_1
 - /obj/item/clothing/glasses/eyepatch/fluff/thysse_1
 - /obj/item/clothing/glasses/fluff/arjun_chopra_1
 - /obj/item/clothing/head/secsoft/fluff/swatcap
 - /obj/item/clothing/head/helmet/greenbandana/fluff/taryn_kifer_1
 - /obj/item/clothing/head/fluff/edvin_telephosphor_1
 - /obj/item/clothing/head/fluff/krinnhat
 - /obj/item/clothing/head/fluff/bruce_hachert
 - /obj/item/clothing/suit/storage/labcoat/fluff/pink
 - /obj/item/clothing/suit/storage/det_suit/fluff/graycoat
 - /obj/item/clothing/suit/storage/det_suit/fluff/leatherjack
 - /obj/item/clothing/suit/fluff/oldscarf
 - /obj/item/clothing/under/fluff/milo_hachert
 - /obj/item/clothing/under/fluff/jumpsuitdown
 - /obj/item/clothing/under/fluff/lilith_vinous_1
 - /obj/item/clothing/under/fluff/ana_issek_1
 - /obj/item/clothing/under/fluff/olddressuniform
 - /obj/item/clothing/under/rank/security/fluff/jeremy_wolf_1
 - /obj/item/clothing/under/fluff/tian_dress
 - /obj/item/clothing/under/rank/bartender/fluff/classy
 - /obj/item/clothing/under/fluff/callum_suit
 - /obj/item/clothing/under/fluff/solara_light_1
 - /obj/item/clothing/under/fluff/wyatt_1
 - /obj/item/clothing/mask/mara_kilpatrick_1
 - /obj/item/clothing/accessory/fluff/altair_locket
 - /obj/item/clothing/accessory/fluff/konaa_hirano
 - /obj/item/clothing/accessory/fluff/nasir_khayyam_1
 - /obj/item/clothing/accessory/fluff/lin_chang_1
 - /obj/item/clothing/mask/mara_kilpatrick_1
 - /obj/item/clothing/shoes/magboots/fluff/susan_harris_1
 - /obj/item/clothing/suit/storage/det_suit/fluff/retpolcoat
 - /obj/item/clothing/head/det_hat/fluff/retpolcap
 - /obj/item/clothing/under/det/fluff/retpoluniform
 - /obj/item/weapon/melee/baton/fluff/oeng_baton

As an aside, it also splits cigs_lighters.dm into lighters.dm and cigs.dm, as the lighter/match definitions were getting a bit long.

### CODE REVIEW

**Comment by Zuhayr** [comment]
You may also enjoy https://github.com/Zuhayr/Baystation12/commit/a9f936fe42e4046a305b70975990ac24ebf39357

**Comment by ZomgPonies** [comment]
Calling it a 'controversial refactor' as per TC's request. There isn't really a good tag for this.

**Comment by tigercat2000** [comment]
@Zuhayr Oh, nice, I'll grab  that soon.

**Comment by Iamgoofball** [comment]
I recomend keeping some of the items, retooling them to not be snowflakes, and adding them in, like that rainbow belt

Rainbow belt is hella cool spritewise and should go with the rainbow outfit

**Comment by Necaladun** [comment]
Why, btw? Does having them create problems at all?

**Comment by tigercat2000** [comment]
@Necaladun To keep object define levels down as much as possible, and it leaves a mess in the file of unused things.

**Comment by FalseIncarnate** [comment]
unless the associated players come back and start complaining they are missing their fluff items, it shouldn't affect much.

more than anything, this is just a clean-up of otherwise un-used code and thus reduces file size slightly.

some of those items are interesting and we may want to consider reviving them as standard items. The electronic cigarette would be a good choice for doing so, I know there was requests for one on the forum a month or two back

**Comment by tigercat2000** [comment]
@FalseIncarnate About 90% of these are just old bay fluff items that have never been assigned to players on our server. I think the only key I recognized was roland.

**Comment by Fox-McCloud** [comment]
Yeah, these are Bay fluff items, no Para.

I'll look through them and let you know which ones should probably stay though.

**Comment by fj45** [comment]
Agree with Fox, keep the nicely sprited items that are good for fluff items.

To add onto it...any pens/flasks, the peacemaker, that medkit and the NT badge.

Remember, some people might want to use the current sprites for their fluff item.

Don't agree with the atmos mags though, we don't need more magboot sprites and those are damned ugly.

**Comment by ZomgPonies** [comment]
Gonna DNM this until we settle on what to keep and what to remove. This doesn't remove the SPRITES themselves though, players are still free to choose any of those. This simply cleans out the item paths.

**Comment by Zuhayr** [comment]
Depending on how you guys handle custom items, you might want to look at grabbing the system that's up for merge at Bay. PR is https://github.com/Baystation12/Baystation12/pull/9202 and a readme on how to add items to the system is at https://github.com/Baystation12/custom-items.

This is entirely selfless and not at all motivated by me wanting you to do my bugtesting for me. No sir.

**Comment by ZomgPonies** [comment]
Speaking of bugfixing Zuhayr, we're reverting Mloc's lighting. It causes regular hard BYOND crashes for a lot of players, and is pretty laggy in general. It'll require a lot more testing and optimization before it's ready for a production server.

**Comment by fj45** [comment]
Ohhhh....silly me, yeah just as long as the sprites aren't touched, I'll leave the code to the coders.

**Comment by tigercat2000** [comment]
@fj45 what do you mean by NT badge? there are like 5

**Comment by fj45** [comment]
Ignore me, thought you were also removing the sprites, remove whatever you think you need to remove.

**Comment by tigercat2000** [comment]
@ZomgPonies I think this is merge ready now

**Pull request merged**
