### PR TITLE
Improved Sheet Handling; Better Sci machine resource Formatting

### PR DESCRIPTION
**Pull request by Crazylemon64**
* Research machinery and the fabricators now allow you to eject a custom
  amount of sheets, so you don't have to spam-click

* Research machinery and the fabricators now also count how many sheets you have 
  in units of 0.1 at a time, so you have some relatable idea of how much you have besides 
  some exorbitant amount

* Grabbing a single item from a stack is as before, but click again and you 
  will have a prompt on how much to move over from one stack to the other.

### CODE REVIEW

**Comment by Plotron** [comment]
Yay, wannabe mechanics no more!

**Comment by Crazylemon64** [comment]
It seemed to be some vestigial code that had failed to work at some point; I decided to repair it and bring it up to function as a parallel to the access restriction on the R&D systems.

If push really comes to shove, they could load the materials while the AI/cyborg (latter unlikely due to lack of roboticist) queues up the limbs needed. Though if everyone thinks that actually enforcing the access restrictions on the fabricators is a bad idea, I can tear that bit out.

**Comment by Fox-McCloud** [comment]
:-1: 

For the access restrictions on the mech fabs. The access was intentionally removed a while back to make things a bit more fluid for science---and as @Plotron pointed out, there's legitimate reason to keep them that way.

**Comment by Robertha89** [comment]
Access restriction is bad m'kay.  
Also the prompt for splitting sheets. No Plz.  Males it harder to take one sheet, and throw it.

**Comment by Crazylemon64** [comment]
Would it work if I made it prompt only if you were transferring sheets from one stack to another?

**Pull request merged**
