### PR TITLE
Belt Overlay System

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Ports tgstation's simple belt overlay system with changes to which items show icons for our sec force.

Currently this ONLY works for secbelts, as I'm terrible at making new icons from scratch.

In-Game Examples
ingamefull
ingameempty

Full Belt:
itemfull
Empty Belt:
itemempty

Note that this doesn't show up on your character, only on the belt's icon.

:cl: DaveTheHeadcrab
rscadd: Added overlays for sec belts that reflect the items stored therein.
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
Noice. Now does this work with all kinds of belts or only sec?

**Comment by DaveTheHeadcrab** [comment]
Only sec right now. It's super easy to add more if anyone who can icon worth a damn makes icons for it.

But I make icons about as well as K.E.V.I.N. swims.
(Toasters can't swim, it's a fact!)

**Comment by CrAzYPiLoT-SS13** [comment]
Oh God, yes! Thank you!

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by taukausanake** [comment]
I like playing with icons. Let me have a go at it later, I'd love to make some for Hydro at minimum

**Comment by Spacemanspark** [comment]
"This unit can swim!"
*Proceeds to jump into pool and short circuit.*

**Comment by taukausanake** [comment]
IPCs don't really short circuit when in the pool, do they? They really should I think, along with borgs but that would make such a meta...
Europa station when? I want to throw beings outside and watch them drown rather than freeze

**Comment by Spacemanspark** [comment]
They don't short circuit, no.

**Pull request merged**
