### PR TITLE
Stickier beakers ii

### PR DESCRIPTION
**Pull request by Crazylemon64**
After a search through the code, I think I've expunged every obvious way to get a borg to drop a NODROP beaker. With any luck, we shouldn't have any shifts with beakers glued to our hands anymore.

### CODE REVIEW

**Comment by Markolie** [comment]
Very nice, thank you!

Also, yay for span's!

**Comment by FalseIncarnate** [comment]
Compile errors, TRAVIS failed

**Comment by Crazylemon64** [comment]
Indeed. And I forgot to check the entire /game directory, too. So, I've fixed that, and am now compiling on my own end to get things working. A final commit will come in about half an hour.

**Comment by Crazylemon64** [comment]
Alright, this should be it. I'll check to make sure I didn't forget a return after each message that the item is stuck, as I found that to be a common self-made mistake when I was writing this.

**Comment by Crazylemon64** [comment]
Looks good on my end.

**Pull request merged**
