### PR TITLE
Nerfs beanbags & rubber pellet shots

### PR DESCRIPTION
**Pull request by Edan52**
## What Does This PR Do
Makes it so beanbags now take 3 hits to down you.
Rubber shots will knock you down in one hit at close range, allowing the user to crawl but two hits will stam crit them, and the negative armour penetration has been changed from -30 to -10.

## Why It's Good For The Game
We don't want people going down instantly from these.

## Changelog
:cl: CornMyCob
tweak: Beanbag shots & rubber shotgun rounds have been nerfed to require multiple/more hits to down.
/:cl:

### CODE REVIEW

**Comment by Inadvizable** [comment]
One thing to consider here is that the bartender can't stamcrit you anymore without reloading.

**Comment by roarbark** [comment]
i think rubber shot needs a nerf. i dont think beanbags need a nerf. they currently existed as a sidegrade to disablers, basically half the firerate, two handed, less ammo, worse storage economy but effectively double stamina damage.

also, i dont think a simple value change is a good way to deal with this. with the new values the use cases for RS and BB are very, VERY slim and you'd be better off with a second disabler in nine out of ten rounds.

if you're halving the damage for both, i would suggest some additional effects, like a short knockdown (maybe even with a tile or two of knockback for BB?) or slowdown or confuse, maybe even extra brute damage, anything to give people a reason to pick up a bulky weapon that has to manually reload and cant be paired with a shield, with worse or close to the same performance as the disabler who doesn't have all the other drawbacks in most situations.

**Comment by Leanfrog** [comment]
I feel it's worth noting that rubbershot is practically the only ammo/weapon (that isn't explosives) that is effective against a desword/shielded hardsuit user _especially so if both are combined_, I'm not saying this is a bad idea but it's worth noting for the already strong "block chance" meta that I've noticed emerging.

**Comment by Dafrek** [comment]
Rubber shot stam-critting at close range in 1 shot does seem a bit too strong, however, its limited range and weakness against armor are downsides that might justify it. Beanbags are of course much better at range and are less effected by armor, so I can see why you might want to tone its stamina damage down a bit.

Honestly though I think the main problem with riot shotguns is that you can fire the first two shots nearly as fast as the double-barrel shotgun by pumping it immediately after the first shot and then firing again. This means that if you do it right you can stam-crit someone with two shots much faster than you would be able to with a disabler.

**Comment by hal9000PR** [comment]
requesting a TM as people seem polarised on this.

**Comment by matttheficus** [comment]
image

You are now better off using disablers against anyone wearing even the slightest bit of armor instead of beanbags. 

Note: the base amount of shots for unarmored targets is two shots with all pellets hitting for rubbershot and THREE for beanbags.

If this goes through barkeeps are going to need a new way to beat people down who are being a pain because three shots to down someone is a bit much, especially unarmored.

**Comment by Edan52** [comment]
Update: Rubber pellets have been buffed again to make them more viable. Read PR description for details.

Regarding mentioned concerns,
>One thing to consider here is that the bartender can't stamcrit you anymore without reloading.

The bartender having the ability to down people in less than a second at the start of the round is a bit ridiculous considering the fact that security doesn't have the same luxury. Stam crit keeps you down for a LONG time, I don't see a reason for the bartender to have this of all people.

> i dont think beanbags need a nerf. they currently existed as a sidegrade to disablers, basically half the firerate, two handed, less ammo, worse storage economy and easier to fumble (not semiautomatic), but effectively double stamina damage.

The half the fire rate point is partly true, besides the first two shots from a riot shotgun which can be fired out at about the same rate, which becomes problematic when it only takes two shots from any range with beanbags to stam crit you. Shells being tiny items makes carrying around ludicrous amounts of ammo trivial, no need to go somewhere to recharge either, reload on the go (though you rarely have to worry about recharging with a disabler, especially when you may be carrying an energy gun as well, that's 40 shots!). The main downside is not being able to carry a shield at the same time. Beanbags currently deal 80 stamina damage, which is 2.67x the amount of a disabler beam, slowing people to a crawl in one hit from any range. As I stated before, you're able to down people in less than a second with beanbags, which is the sort of gameplay we're trying to get away from here.

Regarding your other points, the beanbag still has the ability to slow people in one hit from any range which is something the alternatives don't all have, as well as still being slightly more effective against armour than rubber shots.

>I feel it's worth noting that rubbershot is practically the only ammo/weapon (that isn't explosives) that is effective against a desword/shielded hardsuit user especially so if both are combined, I'm not saying this is a bad idea but it's worth noting for the already strong "block chance" meta that I've noticed emerging.

Latest changes should address this, though it shouldn't have impacted its shielded hardsuit breaking ability in the first place.

>You are now better off using disablers against anyone wearing even the slightest bit of armor instead of beanbags.

I still stand by the fact that you shouldn't be able to down people almost instantly in two shots from any range. Regarding the vests, simply target another area of the body. Being able to slow people in one hit as opposed to two is pretty huge when movement speed is often regarded as the most important stat. In these cases, use of the disabler or shotgun can be justified. In the case of the riot armour maybe disablers would still be better, rubber shots seem like a good option too now, and in the case of the nukie I'm not really concerned as I believe that gamemode should be more about lethals than non-lethals, I think it's actually five hits with the beanbags when the suit is in combat mode, which yeah I don't see why beanbag shells should be able to do much against a hardsuit, I will happily encourage use of lethals on a nukie round.

**Comment by AffectedArc07** [comment]
Yeah I tested this.

Current knockdown is busted, the bartender should not have a more reliable way of stunning people than the entire security force. No.

**Comment by Dafrek** [comment]
> Update: Rubber pellets have been buffed again to make them more viable. Read PR description for details.

I think the changes to rubber pellets are good, it should undoubtedly be better against an unarmored target at close range when compared to a disabler, however, any decent armor should counter most of the effects of the rubber shot. Beanbags are a bit tougher to balance though since they should be better than disablers due to the ammo and fire rate of disablers and the ability to shoot them through windows, but it would be hard to balance them between nearly instantly taking someone down or just being worse than disablers.

**Comment by BakKeener** [comment]
After reading through this as well as the comments, I do agree bartender shouldn't be able to just 2 tap anyone from any range and I happen to have been there for the conversation about this being a potential meta when people figured it out so I more or less know how strong rubber shot and beanbags are. What I don't agree on is the bartender one means of defense being stuffed and would like to suggest an alternative such as damage range drop off which would allow the bartender to still be able to defend the bar but not be able to snipe across the hall in addition to preventing security from raining these shots for easy slow down and stam crit. 

The reason I suggest for damage range drop off for these here is mostly due to the fact these are kinetic rounds which would make sense that they lose effectiveness as they further. I think we have something that already has damage drop off but I can't remember what weapon it is specifically but I believe it's something very feasible to do instead of going for a straight value change just to stomp out a meta that isn't even abused yet from what I've seen anyway in my time of playing.

This would give us the balance between not being able to peg people from across the hall for instant downs while maintaining the close quarters effectiveness these rounds are supposed to have for being fired from a shotgun.

**Pull request merged**
