### PR TITLE
Adds "Cobra Hood" hair type to unathi.

### PR DESCRIPTION
**Pull request by GunDOSMk1**
What it says on the tin.
This PR was made at the request of Alyx on the discord, all sprites are theirs. I only wrote the code.

snekky
^
What it looks like.

EDIT: More Pictures
screenshot 2017-05-06 00 20 47
screenshot 2017-05-06 00 20 48
screenshot 2017-05-06 00 20 50

🆑 
rscadd: Adds Unathi cobra hood
/🆑

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Can you include a colored version so we can see the way the shading affects colors / if it supports multiple colors? The white/grey is kinda hard to see on github's white background, and not much better on the transparent background of dreammaker.

You'll also need a changelog.

**Comment by GunDOSMk1** [comment]
screenshot 2017-05-06 00 18 37
^
Quick and hasty mock up on it on another character. (that's not albino)

**Comment by taukausanake** [comment]
This is kind of killing chances for porting the snek people from Europa Station, isn't it? I mean, more so than it already was. Overkill.

Looks a little weird. Then again I don't play Unathi. Maybe it's just the color choices used in the OP

**Comment by KasparoVy** [comment]
Europa snakepeople port is a bit less realistic a fantasy unfortunately. This is much easier fulfilled-- furthermore, I figure it's a good demonstration of the shading/colouring of the sprites. Pretty sure it was just added/coloured after spawning in as a random-genned unathi from charselect, which shouldn't be an issue

**Comment by GunDOSMk1** [comment]
> Pretty sure it was just added & coloured after spawning in as a random-genned Unathi from character creation

To confirm, yes it's a random unathi. I felt that was mist fair.

**Comment by GunDOSMk1** [comment]
> Can you include a colored version so we can see the way the shading affects colors / if it supports multiple colors? The white/grey is kinda hard to see on github's white background, and not much better on the transparent background of dreammaker. you'll also need a changelog.

Done annnnd done!

**Pull request merged**
