### PR TITLE
Mechas breakthrough

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Ported from https://github.com/d3athrow/vgstation13/pull/4378
- Mechas sent from Mass Drivers now break through windows, grilles, tables, and hurt people
- OH YEAAAAAAAAAAAH

https://dl.dropboxusercontent.com/u/33846352/byond/dreamseeker%202015-05-10%2005-38-31-07.webm

OH YEAAAAAH

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Oh dear.
:+1:

**Comment by Flip-Sandwich** [comment]
This owns bones, absolutely

**Comment by johannhawk** [comment]
i miss my orange-aid man gimmick...

**Comment by Fox-McCloud** [comment]
This will literally never be used.

No opinion, really.

**Comment by veganzombeh** [comment]
Breakthrough PR of the year. :+1:

**Comment by M3hillus** [comment]
You do realize, that with this new revelation in mecha technology, building a mass driver should be a thing.

**Comment by tigercat2000** [comment]
:+1:

and @M3hillus I mean to get around to porting /vg/'s buildable mass drivers at some point.. just need to think of a clever way to get around the multitool stuff.

**Comment by PJB3005** [comment]
#12 

now if only.

**Comment by tigercat2000** [comment]
OH YEAH!
:P

**Pull request merged**
