### PR TITLE
Dice will now roll when thrown

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
All Dices, when thrown, will now roll for their number. Buffs Dungeons & Dragons roleplay on our server.

Ported from /tg/station13.

Tested locally without any issue.

**Changelog:**
:cl: Arkatos
tweak: Dice will now roll when thrown
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Now you can roll your ranged weapon attack with a ranged weapon attack.

Soon we'll have to add a traitor item that is a set of "weighted" dice, that deal damage equal to the number rolled when they get thrown.

**Comment by taukausanake** [comment]
Librarian specific traitor item. Weighted Dice. Deals 5 * the face it lands on. I almost want to vote for 10 * face but I don't know how much you really want a CRIT to deal. Might be fitting though as an almost insta-kill (not too sure how it works with new code in). Might need to make it most effective at a certain range to _try_ and prevent spamability

**Comment by Fox-McCloud** [comment]
This should apply to the e20.

**Comment by Arkatos1** [comment]
@Fox-McCloud Actually, it does! I have tested it and saw no problems with the interaction - once E20 rolls, it is locked until explosion on that number, be it a roll in hand or by a throw. Throwing the dice and rolling 1 still gibs you, as it should.

**Pull request merged**
