### PR TITLE
Remove the Red Cross from the last of the medical sprites

### PR DESCRIPTION
**Pull request by SkullyRoberts**
Replaced the red cross on the purple first aid kit, medical briefcase, and first rad first aid kit with the green cross used on the toxin kit, O2 kit, and ointment kit.
Replaced the red cross on the syndicate NanoMed (on the syndie shuttle) with a black cross on a red and crimson background. This includes the animated syndimed-deny.

This also includes a small edit that corrects the header in swords_axes_etc.dm
appeasearc

### CODE REVIEW

**Comment by Spartan6** [comment]
GENEVA IS FINALLY HAPPY.

DON'T NEED TO HIRE A LAWYER ANYMORE.

**Comment by Ty-Omaha** [comment]
Pictures?

**Comment by tigercat2000** [comment]
@SkullyRoberts Could you include pictures of the new sprites in the OP, please?

**Comment by SkullyRoberts** [comment]
Added new sprites to OP, plus banana for scale

**Comment by tigercat2000** [comment]
lgtm

**Pull request merged**
