### PR TITLE
R&D Stock Parts Print Time Fix

### PR DESCRIPTION
**Pull request by Birdtalon**
Adjusted `lathe_time_factor` for all stock parts tier 1 through 4 to fix them to the correct value of 0.2.

🆑 Birdtalon
Fix: Protolathe stock part printing no longer takes a lifetime.
/ 🆑

### CODE REVIEW

**Comment by bigfatbananacyclops** [comment]
The components for upgrading machines take a long time to be made, it takes about twenty minutes to make all the components to upgrade all the station machines, it's pretty unfun and the slowness bummed me down a bit. I support this

**Comment by FlattestGuitar** [comment]
Might as well. This does nothing to make the game more fun. :+1:

**Comment by Fox-McCloud** [comment]
Wait, these use positive integers? What the ever loving hell.

This isn't a rebalance, this is a fix. Had I known about this, I would have told you to include it in your other PR.

All stocks parts are supposed to have a `lathe_time_factor` of 0.2

**Comment by Birdtalon** [comment]
All parts T1 through to T4 updated to a `lathe_time_factor` of 0.2 @Fox-McCloud

**Comment by Fox-McCloud** [comment]
Finally, this is fully fixed...hopefully.

**Pull request merged**
