### PR TITLE
Feedback for the Feedback God

### PR DESCRIPTION
**Pull request by FlattestGuitar**
The feedback tracking system is there, but it's silly. This is my attempt at making it less silly and hopefully a stepping stone on the way to us having a solid way of reviewing game data to help us make more informed design choices. This whole PR mostly just replaces weird old code and doesn't do that many useful things.

I ripped out the blackbox thing and added a feedback controller that polls the population every ten minutes, holds all the feedback data and commits it to the DB at round end.

Also changed around the procs responsible for reporting feedback. There's now only one - `feedback_report()` - it automatically increments entries that are the same data instead of giving people four different procs for incrementing, decrementing, adding new ones and just doing all of that together. No idea why it wasn't like this to start with.

This doesn't really change the way things look in the feedback DB, so what we have right now is not made obsolete. What it *does* change is the `legacy_population` table. The entries turn from this:

| Players  | Admins |
| ------------- | ------------- |
| 15  | 0  |
| 0  | 2  |

to this:

| Players  | Admins |
| ------------- | ------------- |
| 15  | 2  |

again, this system was stupid.

Also added round end tracking for shadowlings, so we can check whether they're *really* OP or just a bit.

This is all backstage, so no CL. Hopefully after this we can get some backend magician to make us a system that polls the DB and displays stats on *EVERYTHING*, but that's not going to be me, or at least not here and now.

### CODE REVIEW

**Comment by KasparoVy** [comment]
The God must be pleased

**Comment by Allfd** [comment]
Blackbox is evil,  I wish we had a way to convert the old data to keep uniformity.

**Comment by KasparoVy** [comment]
Did blackbox store it SQL? Could probably rig up some nasty queries that'd convert it all, but that's pretty risky.

**Comment by SamHPurp** [comment]
this thing is purely awesome

**Comment by FlattestGuitar** [comment]
The output should remain unchanged as far as I can tell. I did change the whole thing with a series of reg exps, but I tried to pay attention to keeping this mostly uniform.

Shouldn't run into issues.

**Comment by Allfd** [comment]
My preference would be to setup a new table in the database, then port over the older data to the new format so we are not throwing out three and a half years of data.

**Comment by FlattestGuitar** [comment]
The output is still the same. The only difference would be certain entries being repeated instead of merged into a single entry in the old system, which shouldn't impact *any* sensible query on the system.

One more difference would be me changing one feedback entry for blobs being blown up by nukes to not be ambiguous with others.

Other than that the output of the system is *exactly the same as the current one*, bar the population poll mentioned in the OP.

**Comment by Allfd** [comment]
No concerns then, thanks for explaining.

**Comment by tigercat2000** [comment]
Was there any particular reason you decided to mass-change the name of a proc that makes it inconsistent with every other codebase?

**Comment by FlattestGuitar** [comment]
Yep. I ripped out almost all of the feedback procs we had and replaced them all with a universal one. For the sake of anyone who doesn't check the exact contents of the procs when comparing codebases, I think it's safer to name a proc that does different things differently.

**Comment by tigercat2000** [comment]
With the merge of #7755 you will need to update this branch to the latest version of the repo and follow the directions set out within it.

**Comment by FlattestGuitar** [comment]
Been too long.

Feel free to take the code and implement it yourself, dear reader of this comment.

**Pull request closed without merging**
