### PR TITLE
Adds big cardboard boxes.

### PR DESCRIPTION
**Pull request by Spacemanspark**
Adds cardboard boxes.
Here is a defining feature for this item:
"!"
They can be made with 4 cardboard sheets.
@iamgoofball tell me how bad I butchered it.
I had to change the "open" sprite, as well as some other code, a bit, because /tg/'s locker code is... something else.
Tested and working.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Fuck you Travis.

**Comment by Spacemanspark** [comment]
"code/game/objects/items/stacks/sheets/sheet_types.dm:199:error: /obj/structure/closet/cardboard: undefined type path"
Gee.
 What's this, then, Travis?

**Comment by Crazylemon64** [comment]
You need to change paradise.dme to include your new cardboard box, so that it will actually know about your closet.

**Comment by Spacemanspark** [comment]
Spacemanspark fails at coding: part 31324356123423143

**Comment by Spacemanspark** [comment]
There we go.

**Comment by TheDZD** [comment]
[!](https://www.youtube.com/watch?v=2P5qbcRAXVk)

**Comment by Aurorablade** [comment]
!

**Comment by Fox-McCloud** [comment]
Snake? Snake?! SNNNNAAAAAAKKKEEEE!

**Comment by tigercat2000** [comment]
mrowl

wait wrong snake

**Comment by orelbon** [comment]
piss colored snake for the win

**Comment by M3hillus** [comment]
A pr to surpass metal gear

**Comment by Spacemanspark** [comment]
This is ready to go whenever.

**Pull request merged**
