### PR TITLE
Adds mineral to old station asteroids

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
The asteroids in the old station space ruin now have a chance to contain minerals, to give the crew yet another thing to do once the station is repaired, and to allow them to get a bit more beyond the materials that they can find on the station.

Since there's very few mineral turfs, I set a few of them to high chance, but even so they shouldn't exactly get too many minerals.

**Picture**
As was requested, have an example picture of how one of those asteroids might look like, keep in mind the minerals are allocated randomly at roundstart (though in theory I could pre-determine it too, so there's always the same minerals):

untitled

**Changelog:**
:cl: 
add: Ancient Station asteroids now contain minerals and can be mined.
/:cl:

### CODE REVIEW

**Comment by variableundefined** [comment]
Sounds good to me

**Comment by Shadow-Quill** [comment]
How will oldstation crew refine the minerals?

**Comment by variableundefined** [comment]
Technically, fire_act refine with an efficiency of 50%..

**Comment by TDSSS** [comment]
I admit, I assumed they'd just make an ORM with their science setup, but that requires ORM access to get anything out of it. But Ansari came to the rescue! Also, can't you build the old refinement stuff, the smelting machine or whatever it's called? The one you find in away missions?

**Comment by Shadow-Quill** [comment]
If I'm not mistaken, welders have a 100% efficiency rate, at the cost of like 20 fuel

**Comment by Shadow-Quill** [comment]
It's also quite annoying when you want to get to the main station via teleporter, but the mineral storage only has three crystals, with no diamonds in sight.

**Pull request merged**
