### PR TITLE
Cables punish you for touching with hands

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR is alternative to https://github.com/ParadiseSS13/Paradise/pull/22126
Cables now shock you when you touch them without protection

## Why It's Good For The Game

Logic fixed, if cable shock you when you touch it with conduct object, you should be shocked when you touch it with bare hands

## Testing

compiled, touched cable

## Changelog
:cl:
tweak: Cables now shock you when you touch them with hands.
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
I don't think this is a good idea - a lot of fights happen in maints, and a single misclick on a cable in there could end an antag/secoff's round, for no other purpose than realism.

**Comment by HMBGERDO** [comment]
> I don't think this is a good idea - a lot of fights happen in maints, and a single misclick on a cable in there could end an antag/secoff's round, for no other purpose than realism.

then vote yay for other PR

**Comment by SteelSlayer** [comment]
We should at least check if the cable is powered before shocking.

**Comment by HMBGERDO** [comment]
> We should at least check if the cable is powered before shocking.

it checks for power in shock proc

**Comment by Exavere** [comment]
The PR has been open for a while and I haven't seen much going for it, so I may as well voice my opinion too.  I don't think there really is any need to change how wires currently work.  

Is there any other reason for this PR other than an alternative to #22126?

**Comment by HMBGERDO** [comment]
> Is there any other reason for this PR other than an alternative to #22126?

actually, no, it was just one of ways to tweak the thing. Gonna close it and promote the other one

**Pull request closed without merging**
