### PR TITLE
Medical tool resprite

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Partial port of https://github.com/tgstation/tgstation/pull/69109
Ports only medical tools.
Some custom tweaks for laser scalpels.
Their blood filter tool is now our fixovein.
Didn't port laser cautery since we don't have it.
Adds missing inhands for all medical tools.

## Why It's Good For The Game
Medical tools are an inconsistent mess and it's hard to visually pick them out on a grey background, this drastically improves the situation.

## Images of changes
image
Image from their PR:
image

## Testing
Touched all the tools

## Changelog
:cl:  Onule, PositiveEntropy, TetraZeta, S34N
imageadd: Completely resprites all medical tools!
imageadd: Adds missing inhands for medical tools
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
Pretty good looking tools, a dozen of times better than what we have.

**Comment by Miraviel** [comment]
Clean outlines definitely help, I think I only recognise our tools because I have learnt their names (which is not great).

Their blue colour seems too dark for Para (compared to other blues like the NanoMed vendors, the defibrillator, the cryotubes, the sleeper...), especially the retractor's handles, but it's nothing that'd keep me awake at night.

The surgical drapes are in isometric view though and we don't use them, not sure if you want to update it (we should probably just remove it altogether).

**Comment by Bm0n** [comment]
I am surprised we even have surgical drapes in the code lol, thought that was a TG surgery only thing

**Review by hal9000PR — APPROVED** [review]
please deconflict for merge

**Comment by S34NW** [comment]
Drafting for DNM until I can fix the failed icon conflict resolution

**Comment by Scribble-Sheep** [comment]
Finally, tools I can actually see when they're on the table!

**Pull request merged**
