### PR TITLE
Enables printing of Demotion console circuitboards

### PR DESCRIPTION
**Pull request by SamHPurp**
Continuing the trend of making everything (within reason) constructible, and that this was missed off of #6766, admitted by the author [here ](https://nanotrasen.se/forum/topic/10665-list-of-irreplaceble-itemsmachinery-on-station/#comment-88368)- I figured I'd rectify it.

:cl: Purpose2
add: Demotion console circuitboard designs now available from your local Research and Development laboratory!
/ :cl:

### CODE REVIEW

**Comment by Kyep** [comment]
May want to check that the computers built with these cards work as well as the normal computers.

**Comment by SamHPurp** [comment]
@Kyep I demoted an engineer with a CE card from a CE console, and demoted a doctor with a CMO card from a printed CMO circuit.

**Comment by uraniummeltdown** [comment]
Wouldn't it be better to allow screwdrivering an ID Console board instead of adding 4 new designs?

**Comment by Fox-McCloud** [comment]
What @uraniummeltdown said.

Also, this should have been made so that the ID console allows selective hiring/firing based on the ID inserted into it, and not distinctive var requirements on each console (yuck).

**Comment by SamHPurp** [comment]
Refactoring a recently merged feature - with how long it took for it to be reviewed seems crazy. This should have been caught in the initial review no?

I'm going to close this and fix in sometime in the future.

**Pull request closed without merging**
