### PR TITLE
Makes meteors not take damage from railings

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Makes it so meteors don't take damage from hitting railings.
Also makes it so empty asteroid turfs will not take away hits of the meteor.

## Why It's Good For The Game
Farragus starts out with a ghetto meteorshield, this PR will avoid that.

## Testing
Spawned in some railings and meteors, they didn't go boom from the railings.

## Changelog
:cl:
tweak: Meteors don't take damage from railings anymore
/:cl:

### CODE REVIEW

**Comment by Qwertytoforty** [comment]
could you look into https://github.com/tgstation/tgstation/pull/78152 as well?

Would make empty asteroid turfs not use up  meteor hits

**Comment by DGamerL** [comment]
> could you look into [tgstation/tgstation#78152](https://github.com/tgstation/tgstation/pull/78152) as well?
> 
> Would make empty asteroid turfs not use up meteor hits

Seems easy enough to implement, I'll add this

**Comment by DGamerL** [comment]
> could you look into [tgstation/tgstation#78152](https://github.com/tgstation/tgstation/pull/78152) as well?
> 
> Would make empty asteroid turfs not use up meteor hits

Done, the list is just asteroid turfs and space currently, feel free to give suggestions

**Review by Contrabang — APPROVED** [review]
Code is fine

**Review by lewcc — APPROVED** [review]

**Pull request merged**
