### PR TITLE
So Salty

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds 1 unit of salt to pistachios and potato chips.

Don't get salty about the salt or I'll get salty with you for being salty about those salty chemists engaging in ghettochem.

### CODE REVIEW

**Comment by TheDZD** [comment]
salt

**Comment by Dumbdumn5** [comment]
ERMAHGERD OP NEEEEEEERRRRRRFFFFF. :+1:

**Comment by Nomzosha** [comment]
http://smashboards.com/attachments/salty-duane-gif.34388/

**Comment by NTSAM** [comment]
Salt Antag when?

**Comment by Fox-McCloud** [comment]
Given how much people complain when they get killed by an antag, I'd say every antag is pretty salt based.

**Comment by Keilden** [comment]
Bananas should have potassium for ghettochem. Also salt is good :+1:

**Comment by Iamgoofball** [comment]
@Keilden they should

**Pull request merged**
