### PR TITLE
Bucket resprite

### PR DESCRIPTION
**Pull request by SeizedClod22**
## What Does This PR Do
Fixes https://github.com/ParadiseSS13/Paradise/issues/21875
Changes the bucket and bucket lid sprites (not any of the others like the hat or held sprites. I might do those later.)

## Why It's Good For The Game
The old one looks kinda sub-par ig

## Images of changes
image
image
image
image

## Testing
Booted up a private server with the change applied. Works.

## Changelog
:cl:
imageadd: Changed bucket and bucket lid sprite
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
this'll fix https://github.com/ParadiseSS13/Paradise/issues/21875

**Comment by SteelSlayer** [comment]
> this'll fix #21875

I don't think it will because this is a simple sprite replacement. The code for lid applying is probably busted.

**Comment by 1080pCat** [comment]
> > this'll fix #21875
> 
> I don't think it will because this is a simple sprite replacement. The code for lid applying is probably busted.

the sprite change looks to work in their images

**Comment by SteelSlayer** [comment]
Author has linked their account.

**Review by Burzah — APPROVED** [review]
Looks good.
Pending team vote before merge.

**Review by DGamerL — APPROVED** [review]
Send it

**Pull request merged**
