### PR TITLE
Lower the layer of computer overlays

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Reduces the layer of the computer screen and keyboard so papers (and players, and everything really) no longer appear below it.

While the keyboard appearing above the lighting layer was certainly a very neat effect when the station was entirely dark, it also caused everything that goes on top of the computer to appear below the screen. Such a buggy implementation just isn't worth it for a somewhat cool effect. Keep in mind that computers still give off a light on their own unless they're completely depowered (and if they're depowered the screen will go black as well), so they'll still light up in darkness.

### CODE REVIEW

**Comment by Alex6511** [comment]
:+1: tired of gentecist ahelping because their injectors are under the computer.

**Comment by tigercat2000** [comment]
If you are going to do this, I have to request that you turn the light range values back to where they were before.

**Comment by Markolie** [comment]
Sure, no problem. Do you happen to know what these values are?

**Comment by tigercat2000** [comment]
Light_range_on was previously 3, light_power_on was previously 2.

**Comment by Fox-McCloud** [comment]
Hate to :+1: this, but I'm going to have to. While the effect is awesome, everything hiding behind it is annoying.

If there was some way to get them to appear above the light layer (like currently), but still not overlap everything, then I'd say keep this system in place. Alas, I know of no way to do this.

**Comment by Alex6511** [comment]
@Fox-McCloud You could accomplish that by analyzing the light state of the tile the computer is on. If the light is below a certain threshold (which you could establish arbitrarly based on your ability to see objects on that tile) you move the monitor layer up. If the light is above said threshold, you move the monitor layer down. It would probably be pretty resource intensive.

**Comment by Keilden** [comment]
Can Poly get back his ability to sit on computers then? It was removed when this effect was added,

**Comment by Fox-McCloud** [comment]
Yeah, that definitely should be re-added

**Comment by PJB3005** [comment]
To necro this: with planes it may be possible to bring this back without it rendering above everything else.

by reworking lighting overlay drawing to use a plane (`ADD` onto a plane, then `MULTIPLY` the plane onto the rest of the screen, same effect), you could have an overlay on the computer, on the **lighting plane** in the shape of the computer monitor that forces the part above the monitor to be full bright always, looks the same but doesn't make the computer monitor overlay everything!

**Pull request merged**
