### PR TITLE
Massive spacepod construction overhaul by /VG/

### PR DESCRIPTION
**Pull request by tigercat2000**
This overhauls our pod construction code (sorta) to d3athrow/vgstation13#1738

I say 'sorta' because the entire "Pod Fabricator" system is different, as well as the recipes adapted to our RnD system. Instead of being a type of r_n_d, the Pod Fabricator is a modified Copypasta of the Exosuit Fabricator. This was really the simplest way to do it. Credit to /vg/ for the rest, though.

Note: The costs and construction times are simply coder values, they are prone to change.

### CODE REVIEW

**Comment by fj45** [comment]
Sounds great.

**Comment by tigercat2000** [comment]
@Markolie This also contains a map edit to the mechanic's office, to include the new machine systems and clean it up a bit.

**Comment by fj45** [comment]
http://i.imgur.com/pIpc9gA.png

If you feel like changing the workshop a little more, I made this a while back but it conflicted.

**Comment by Fox-McCloud** [comment]
If the PODFAB already has support for holding reagents, then I say just put the pod circuitboard in the PODFAB--it means that mechanics don't have access to a bunch of circuit boards they otherwise shouldn't; it also means a one-stop shop for them as opposed to needing the R&D console+circuit imprinter for literally a single circuit.

**Comment by tigercat2000** [comment]
@Fox-McCloud R&D Console is necessary to sync with the R&D servers. It simply won't sync without a console in the area. And it is based off the exosuit fabricator, so no clue how to get reagent support with it.

**Comment by Fox-McCloud** [comment]
I know, which is why I said to give it metal instead of sulfuric and only have it be a PODFAB design =p

syncing nets you the weapons, which I think is prrrrooobabbly best the mechanic can't access given he's not sec, 'specially when the only hindrance to getting lasers is metal.

**Comment by tigercat2000** [comment]
Pod lasers spawn inside a lockbox.

**Pull request merged**
