### PR TITLE
Atmos Grenade Balance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Atmos grenades are a bit strong for regular traitor, especially with how much damage fire does now and the fact it melts walls.

Cost increased to 8 and moved to nuclear only.

:cl: Fox McCloud
tweak: Atmos grenades cost increased from 6 to 11
/:cl:

### CODE REVIEW

**Comment by Wheatley29** [comment]
They seem fine as they are, I have noticed no issues with them, and if they are abused ahelp it. Simple.

**Comment by xBoBox3** [comment]
Eh, i agree with nerfing them for constant use, but i'm not so sure about making them nuclear-only. They prove mighty useful for shuttle hijacks.

**Comment by IcyV** [comment]
I haven't seen them enough to have a full opinion on their price balance, but it seems a higher price would even more-so justify them staying available to non-nuclear. I can't imagine it being used all that much if it was a nuke only sort of item.

**Comment by Wheatley29** [comment]
image
That was a full plasma grenade, doesn't seem too bad for traitors to have really

**Comment by Taaketa** [comment]
To be honest that's a big room. Somewhere smaller like robotics, RnD, Genetics can easily get ruptured and overflow into other areas. Seen most of medical disabled at one stage because of one put into cloning.

**Comment by Kyep** [comment]
I created these. Yes, they are strong.
Most of their strength was intentional. I wanted to make antags stronger / more dangerous, give atmos techs the possibility of a real problem to fix, and introduce something fun/awesome that could make super-slow LINDA actually dangerous.
Some of the grenades' strength, though, comes from the fact that plasma fires now melt walls. This was a feature added in a later PR by someone else that I did not anticipate when I created the grenades. You could argue it acts as an unplanned buff for them. Or, equally, as a nerf, given that it tends to result in hull breaches which drain away the pressure rapidly. Either way, it was not planned when they were created.

Given their strength, I could definitely see increasing their cost to 8. Maybe even 10.
Restricting them to nuke ops, though, seems like it will defeat much of the point of having them.
They will no longer make regular antags a bit stronger, they will no longer give atmos techs something to do (nobody cares about breaches during nukeops), they'll no longer be a meaningful way to shut down cloning or Escape, and in general, their fun/awesome value will be overshadowed by nuke ops in all cases.

We (various admins, including Neca) did have a discussion about tweaking them a few weeks ago, and I offered to put up a PR to do that, but it was decided we should wait for awhile and see how they play out before PRing anything.

I could see upping their cost to 8 or 10. Restricting them to nuke ops seems to invalidate much of what they were designed to do.

**Comment by tristan1333** [comment]
Nuclear only yuck

**Comment by Crazylemon64** [comment]
Yeah, I too take issue with the "nuclear only" bit, for reasons stated above

**Comment by Necaladun** [comment]
-1 Nuclear only. N2O ones especially are amazingly useful, especially for hijack. Plasma fires are something that just aren't done (intentionally) enough on the station.

+1 Increased cost. 6TCs is insanely cheap. Even 8 feels low tbh.

**Comment by Plotron** [comment]
Fox complains that the station isn't deadly enough: wants to restrict plasma nades to nukeops only.

I agree with the other guys - atmos nades are a lot of fun (and I'm talking at the receiving end), and yes - they're too cheap at 6 TC.
Just don't take away the excitement from regular traitors.

**Comment by Earthdivine** [comment]
If they are nuclear only they will see little to no use. They aren't that powerful, but they were on fact too cheap

**Comment by FreeStylaLT** [comment]
I am not a fan of the nades being nuclear-only, the price change by itself is fine as far as I am concerned.

**Comment by Fox-McCloud** [comment]
Can still be purchased by regular traitors. TC cost is now 11.

**Comment by Plotron** [comment]
Agreed!

**Comment by Necaladun** [comment]
I want to say make them cheaper because I love them so much.

But 11TC is fair.

**Pull request merged**
