### PR TITLE
Updated Crossbow/Pneumatic Cannon Melee Damage

### PR DESCRIPTION
**Pull request by Aligotess13**
## What Does This PR Do

Updates the Powered Crossbow and all Pneumatic Cannon variants to 10 damage. Adds a 10 dm throw force to Pneumatic cannon.
## Why It's Good For The Game

For consistency among normal-sized items with the materials they're made of. Slightly makes them better as well with their age.
## Testing

Hit humanoids on a test server.
## Changelog
:cl:
tweak: Crossbow and Pneumatic Cannon do more damage in melee. The cannon hurts when thrown.
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
This isn't explicitly stated, but this pr affects the melee force of the weapon, not ranged attacks

**Comment by Aligotess13** [comment]
> This isn't explicitly stated, but this pr affects the melee force of the weapon, not ranged attacks

**Comment by DGamerL** [comment]
> tweak: Tweaked a few things

Please make a proper changelog.

**Comment by DGamerL** [comment]
> Pneumonic Cannon

image

**Review by Sirryan2002 — APPROVED** [review]
approved for code

**Pull request closed without merging**
