### PR TITLE
Chem Dispenser Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors chem dispensers so the code is more unified and there's less copy-pasta; changes the functionality a bit, as well.

Refactor portion is largely from TG

The portable chem dispenser is now gone; there's only the regular chem dispenser that you can build. Having multiple of these around was just a headache to maintain, and, quite frankly, there shouldn't be subtypes of a type that essentially does the same thing. A number of things have changed:

- Roundstart chem dispensers are now deconstructable/constructable; they can also be wrenched/unwrenched to be moved.
- The tiered nature of reagents being available for upgrade is gone; there's only a single upgrade list now that you have to have high tier stock parts for.
- Chem Dispensers now utilize an internal cell for power, as opposed to just using energy, directly.
- The scaling for energy has been increased by x10. This ultimately means 1 unit = 1 energy. Instead of recharging at a rate of 1 energy per recharge, it'll now be 10 (if it wasn't obvious by now, this means the starting energy is now 1000 instead of 100)
- Requires admin interaction for ghost chemical viewing
- Added the ability to add a single unit, at a time
- Adds the ability to isolate a reagent entirely; this will delete all other reagents in the container but the one you choose to isolate (I don't think TG has this one)
- Soda and drink machines circuits are subtypes of the chem dispenser board, to reduce copy-pasta and make things handle better.
- Hacking dispensers now causes the UI to update instantly
- Upgrading a dispenser causes the UI to update instantly
- All 3 dispensers now have a maintenance panel open icon

And most importantly:

### **GETS RID OF CAEL SHITCODE RELATED TO BROKEN CHEM DISPENSERS**

A look at the UI with changes:

img

:cl: Fox McCloud
add: Roundstart chem dispensers are now construcable/deconstrucable and can be moved
tweak: Energy ratio for chem dispensers increased by x10 (how many reagents you can dispense before running out and how quickly it recharges is all the same, however)
add: Adds the ability to add a single unit of reagent in the chem dispenser
add: Adds the ability to isolate reagents in the chem dispenser
del: Portable chem dispenser removed (the circuit board for them now makes full dispensers)
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
To be clear on one question I have: Will starting dispensers have less or more energy to work with?

**Comment by Fox-McCloud** [comment]
>To be clear on one question I have: Will starting dispensers have less or more energy to work with?

I mean no offense, but did you actually read the PR? I covered this explicitly.

**Comment by MrMagolor** [comment]
You will be able to upgrade chem dispensers just like you were able to upgrade portable ones, right?

**Comment by Mitchs98** [comment]
> > To be clear on one question I have: Will starting dispensers have less or more energy to work with?
> 
> I mean no offense, but did you actually read the PR? I covered this explicitly.

I did read it. Though with you porting TG's I was a little confused. TG's(At-least, Bad Deathclaw's) also uses more energy/an internal cell, but each chemical unit is more than one power unit.

I was just asking for clarification.

**Comment by Fox-McCloud** [comment]
>You will be able to upgrade chem dispensers just like you were able to upgrade portable ones, right?

Yep.

**Comment by SkeletalElite** [comment]
TG chem dispenser's do not have a single chem removal thing, infact, you cant remove any chemicals from a mixture on TG in the chem dispenser.

**Comment by taukausanake** [comment]
So upgrading the cell will upgrade the amount of charge in the dispenser? What about the charge rate? And the machine will charge the internal battery from the APC then?

**Comment by KasparoVy** [comment]
Sweeeet. That's nice. The isolation feature is nifty but steals a bit of the Chem master patch/pill maker things thunder--but no biggie I guess. Convenient

**Comment by TDSSS** [comment]
>Requires admin interaction for ghost chemical viewing

Can I ask why this is a thing? Were ghosts looking at chem dispensers to find tators or something?

**Comment by MINIMAN10000** [comment]
Just thought I'd point out the thing I really like.
> Roundstart chem dispensers are now deconstructable/constructable; they can also be wrenched/unwrenched to be moved.
I love construction/destruction
>Chem Dispensers now utilize an internal cell for power, as opposed to just using energy, directly.
I love machines being tied in with the physical battery system
>Added the ability to add a single unit, at a time
There are times I've wanted this
>Adds the ability to isolate a reagent entirely; this will delete all other reagents in the container but the one you choose to isolate (I don't think TG has this one)
I've mostly just wanted this because I wanted a clean slate but I knew I had at least 1 ingredient right
>Refactoring code to make it nicer
We all sorta just throw code at the wall, it's always nice when someone can go by and fix it up while still keeping the core idea there.

**Pull request merged**
