### PR TITLE
Adds Nar-Sie Hologram and Backup Error Screen to AI

### PR DESCRIPTION
**Pull request by Twinmold93**
Allows the AI the ability to use the holographic Nar-Sie sprite from the
selection. Also adds in a backup error screen for the AI in the case the
icon text is incorrect when the variable is changed.

Video of the two sprites: https://youtu.be/3mpd7aQod38
Photo: https://imgur.com/UjL5ZT7

:cl: Twinmold
rscadd: Nar'Sie AI Hologram and Error Sprite
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I don't think we've had a N.A.R.S.I.E. AI yet, have we? Looks like we might now

**Comment by TheDZD** [comment]
That's a pretty good hologram there.

**Comment by Spacemanspark** [comment]
We had a NARSIE AI before, but this will make it ten times funnier.

**Comment by taukausanake** [comment]
Even more if they get telecomms to format their speaking. Lovely, RIP cult rounds :P

**Pull request merged**
