### PR TITLE
Kitchen Overhaul

### PR DESCRIPTION
**Pull request by FalseIncarnate**
MASSIVE overhaul to the kitchen, should make the chef job more
interesting.

Additions:
- Candy Maker!
 - This machine allows the chef to create a variety of sugary treats
for the crew to enjoy.
- Candy! Lots of candy and this is only the first wave!
image (some of these aren't included yet, like the colored suckers and the second jawbreaker)
 - More candy planned / dreamed for the future
- Candy Moulds
 - Craftable from plastic sheets, also available in the kitchen vendor.
Use these to make different candy types
 - These are returned if you successfully make the candy. Screw up and
the mould is destroyed!
- Cardboard Tubes are now craftable from cardboard

Changes:
- Oven and Grill have been updated to work more in line with the
Microwave and Candy Maker.
 - This means that they are also buildable and upgradeable!
 - Boards for the oven, grill, and candy maker are available from the
circuit printer.
- Many recipes moved from the microwave to the oven and grill.
 - For example, bread is made in the oven, and kabobs are made on the
grill.
- Adds "byproduct" var to recipes
 - Allows for the return of an item in addition to the result,
currently used for candy moulds

Fixes:
- Adds Grape Juice reagent.
 - This will fix a runtime and also allow people to actually drink from
the purple cans.

Sprite Credits:
- Many thanks to Nienhaus for their sprites for a lot of the candies which I
combined and recolored
- Also thanks to FoS for the new sprites which were included, but not all
used (yet!)
- I also edited and created some horrible sprites for a few candy items
and machine states.
 - Hopefully they will be such an eyesore that a real spriter steps up
and provides something nice.

This overhaul should hopefully add a little variety to the chef role,
while keeping it largely unchanged in terms of difficulty.

### CODE REVIEW

**Comment by fj45** [comment]
Can't wait to mess around with this mate, any pics of the sprites?

**Comment by FalseIncarnate** [comment]
Map edit required to replace the oven and grill with their new versions. Also to remove the cereal maker from the map and replace it with the Candy Maker.

The cereal maker currently only exists to be used for nutriment stacking and making random junk edible (the box of plastic bag cereal). If we can come up with a more suitable use for the cereal maker, I will gladly update it's code to be more in line with the rest of the kitchen machines and recipes.

**Comment by Spacemanspark** [comment]
Ooh hey, I remember this from NT code.
:+1:

**Comment by FalseIncarnate** [comment]
Sorry about the multiple merge commits (that's what I get for updating while Fox is merging things).

Map edit is map-merged. Away mission maps were not changed, so if any had the old grill, old oven, or cereal maker, they still exist there.

**Pull request merged**
