### PR TITLE
Adds Random Cigs

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in random cigarettes

These contains random reagents in them, much like the random pill bottles--some reagents can only be found in these cigs (such as lexorin). Two packs are in each cigarette vendor; they'll set you back 150 spessbucks. Reagents can range from horrendous to helpful.

Related
- Adds in synaptizine to spaghetti and meatballs and spesslaw (forgot to do this a longgg time ago)

Fixes
- Fixes cigarettes not having an in-hand

### CODE REVIEW

**Comment by NTSAM** [comment]
yas :+1:

**Comment by Dumbdumn5** [comment]
:+1:

**Comment by Keilden** [comment]
More random stuff is good! While not add a random soda or random snack while at it? :+1:

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Plotron** [comment]
Reminds me of the meth'd up robust-eeze in Donk Co. vendors.
I disagree. Since the cigs may contain restricted chems, make it so that the vendors dispend them only after hacking.

**Comment by NTSAM** [comment]
Or just blacklist those chems somehow.

**Comment by Fox-McCloud** [comment]
None of the chems are nearly as strong as Meth--the "best" you can get is probably Synaptizine (reduces stun durations)--that said, it's 1 out of 35 possibilties of chems and it's only 10 units.

You're going to have to invest quite a bit of time chem hunting for the right cig, to be honest; i ntaht amount of time, you could easy request some far more robust (and seemingly innocent chems) from the bartender, chemist, or chef.

**Comment by Plotron** [comment]
It's not about accessibility of restricted chems nor efficiency. Hacking vendors is easy.
It's the roleplay/lore implications - such chems shouldn't be officially available in standard (non-modified) vending machines.

**Pull request merged**
