### PR TITLE
Makes the c-20r take two bursts to stamina crit you

### PR DESCRIPTION
**Pull request by Inadvizable**
## What Does This PR Do

The stamina damage of midbullet, the projectile used by nukie c-20r SMG as well as syndicate turrets, has been reduced from 65 to 40. This means that two bursts are now needed to down a crew member without bulletproof armor. The brute damage has been increased by 5 to compensate, mostly for the turrets. 10 armor piercing has been added to ensure that officers wearing basic gear are still downed by two bursts - though it will take full four shots connecting.

## Why It's Good For The Game

Part of the project to remove instant stuns from the game, as outlined by @hal9000PR. The c-20r is currently a much disliked weapon due to how it effectively is a ranged instant stun - or stamcrit in this case. This makes it so that you do not get instantly downed, leading to some opportunity to fight or run, though your odds are still bad - as they should be, against a nukie.

## Changelog
:cl:
tweak: Changed the damage of c-20r SMG to stamina crit in two bursts. Adjusted damage and armor penetration slightly to compensate.
/:cl:

### CODE REVIEW

**Comment by Denthamos** [comment]
With the base damage increased on the Cr-20 how does it now compare to the M-90GL and the l6 saw with their damage output and price cost TC wise.  We do not want nukies only using the Cr-20 because it gives the best cost _and_ damage due to such.

**Comment by Inadvizable** [comment]
> With the base damage increased on the Cr-20 how does it now compare to the M-90GL and the l6 saw with their damage output and price cost TC wise. We do not want nukies only using the Cr-20 because it gives the best cost _and_ damage due to such.

The damage on one c-20r burst is now 50, instead of 40. The m-90gl sits at a firm 110 brute per burst, and the SAW at 135. This change is a nerf and the 5 damage does not offset it very much.

**Comment by Inadvizable** [comment]
> I'd say going from 40 to 50 damage per burst is in fact an important change. While newcrit and stamina makes this slighltly less true, "hits to crit" has alway been an important metric in any weapon (see how deswords deal specifically 34 damage over the 30 of regulars, 1 less hit to crit on unarmored targets). This change moves it from 3 hits to 2.
> 
> Not saying I agree or disagree with the changes here, in any case. Just wanted to point out that going to 50 damage is sort of relevant.

Certainly, this is a valid point, and it is something I have considered - I would not opt to increase the damage without a reason. The weapon felt a bit... weak without its only current draw of instant stamcrit, and additionally, the same projectile is used by syndicate turrets, which I did not want to nerf as a side effect of this PR.

With this change the amount of shots to crit decreased from 5 to 4 against most targets, or more usefully 2 bursts down from 3. Considering its most direct competitor, the m90gl, takes 3 shots to crit most people, which on that gun is 1 burst, I don't think it unbalances c20r. It is still very subpar in the lethal damage category, by nukie standards. Especially since m90 also comes with a really quite bonkers 40mm grenade launcher. C20r will still stamcrit you before you are in actual crit, as well.

With the PR being testmerged, we should be able to find out whether this was a good call.

**Comment by AffectedArc07** [comment]
Yeah this has 4 balance objections, out of a team of 5 people.


Something needs doing with the gun, but this aint it chief.

**Pull request closed without merging**
