### PR TITLE
Nations 2.1.3 bugfix + other bugfixes

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Fixes combat borg shield overlay
- Fixes Meteor gamemode never kicking off
- Fixes Enemy Communications bugging out
- Fixes all nation HUDs including AI
- Fixes AI sec/medhuds
- Fixes a small borg runtime

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Ready for merge.

**Comment by ZomgPonies** [comment]
The thing is, I -know- this works. Everything else that was recommended to me broke huds.

**Comment by TheDZD** [comment]
FFFFFFFFFFFFF, I commented on the commits instead of the PR, I am a horrible person.

**Comment by ZomgPonies** [comment]
And yes that return shouldn't be in life it's what broke AI sec/medhuds

**Pull request merged**
