### PR TITLE
Applies repairing time to mining bots

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Does the same thing that was done to mechs a bit back. Give them a repair time but up the healing,

fix points if needed: #9676

**Changelog:**
:cl: Farie82
balance: Healing a mining bot now takes time but heals more
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
What problem is this trying to solve?

**Comment by KasparoVy** [comment]
A repair action without cooldown afaict

**Comment by farie82** [comment]
Trying to make sure that all repairs are handled the same. Aka one repair per time and that the repair takes time.

**Comment by variableundefined** [comment]
Approved.

**Pull request merged**
