### PR TITLE
Keeping updates

### PR DESCRIPTION
**Pull request by taukausanake**
Updating code

### CODE REVIEW

**Comment by taukausanake** [comment]
fuck, did this wrong

**Comment by taukausanake** [comment]
Please someone kill this with fire

**Comment by Fox-McCloud** [comment]
Shameful stealing of the 2000th PR

:angry:

**Comment by Markolie** [comment]
OH GOD WHY

**Comment by Spacemanspark** [comment]
I'm going to steal 2015 and do something incredibly bad with it.
I just don't know what.

**Pull request closed without merging**
