### PR TITLE
Thefuckam ievendoing

### PR DESCRIPTION
**Pull request by Draconic-saint**

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
:+1: , the change paradise needs.

**Comment by Draconic-saint** [comment]
Goddamnit

**Comment by monster860** [comment]
What is this?

**Comment by FlattestGuitar** [comment]
1561 files changed. Waht.

**Comment by Keilden** [comment]
Seems to be some kind of book decryption minigame?

**Comment by FlattestGuitar** [comment]
It is glorious XenoJedrArch which well have to wait four months for, but it will be worth it.

**Pull request closed without merging**
