### PR TITLE
Deputizing the Detective

### PR DESCRIPTION
**Pull request by matttheficus**
## What Does This PR Do
The Detective is now a full-blown Officer of the Law. They have now been given:

- A SecBelt (god bless this QoL addition)
- SecHUDs
- Brig Access
- Noir Glasses added to the DetDrobe

## Why It's Good For The Game
There is currently SoP changes in the pipe for Detective pending full approval (1 Head has approved, another has given verbal approval). They shall be listed below:

**GREEN**
1. The Detective is permitted to assist Security Officers with all Patrol Duties. This includes stops, searches, and arrests as per the current Alert Code. They should, however, prioritize investigations and the collection of forensic evidence;

2. The Detective is to follow all Standard Operating Procedures as outlined by the Security Officer SoP in regards to stops, searches and arrests as per the current Alert Code;

3. The Detective may carry their DL-88 Energy Revolver, spare charge packs, and crew pinpointer;

4. The Detective may carry their telescopic baton;

5. The Detective is permitted to unholster and use their energy revolver on tracker mode for the sole purpose of marking criminals to search;

6. The Detective is not permitted to overcharge their energy revolver without permission from the Head of Security;

**BLUE**
1. All Guidelines carry over from Code Green;

2. The Detective may pull aside any suspect for an interrogation during the course of their time in Processing. No detainee is to be held for longer than ten (10) minutes in Processing if no evidence against them is readily available.

3. The Detective may use their energy revolver on standard mode during arrests.

**RED**
1. Guidelines 1, 2, 3, 4 and 5 carry over from Code Green;

2. Guidelines 2 and 3 carry over from Code Blue;

3. The Detective is permitted to overcharge their energy revolver and freely discharge it when handling deadly threats in accordance with Space Law's ruling on Use of Deadly Force;

4. The Detective is permitted to carry around any weapons or equipment available in the Armory, at the Warden's discretion, but never more than one at a time. Exception is made for severe emergencies, such as Blob Organisms or Nuclear Operatives; 

Given these changes, this should make it so that the Detective is now the defacto "Field Officer" that leads the spearhead charge during investigations, much like IRL Detectives. While they dont have the authority to give orders like an actual ranked Detective, they are now able to do their job fully in the field and assist Officers in their duties.

## Testing

Spawned in, checked my gear and access, ~~got shitfaced at the bar like a true Detective.~~

## Changelog
:cl:
tweak: tweaked the Detective's starting gear, DetDrobe, access, and locker contents.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
Det's minor burn damage re-added as per Hal's request.

**Comment by Contrabang** [comment]
I like this, but it removes their noir sunglasses completely. Maybe you could add it to their clothing vendor?

**Comment by matttheficus** [comment]
> I like this, but it removes their noir sunglasses completely. Maybe you could add it to their clothing vendor?

I can double check, but I'm fairly sure that the maps have noir sunglasses mapped into the office. I might see about making the noirs a SecHUD as well, so that they can just use those instead of spawning with HUDs, but I'd need to check if theyre Maints Loot first.

**Comment by matttheficus** [comment]
Also, @Commit Access people, please do not merge without the implementation of the new Detective SoP. Without it things get a bit messy ICly.

**Review by hal9000PR — APPROVED** [review]
I wish we could have kept the noir glasses in some way. But lgtm

**Pull request merged**
