### PR TITLE
Preventing creating two-brain bodies.

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR prevents players from making two-brain bodies. It will block surgery if target is changeling(they dont need brain to revive) or if target already has brain.

## Why It's Good For The Game

Two-brain bodies is bad. It causes bugs including one player being permanently dead with no chance to be revived. We dont need two-brain bodies.

## Testing

Compiled, tried various surgery.

## Changelog
:cl:
fix: You can no longer put brain or MMI into a body that already has a brain or a player.
/:cl:

### CODE REVIEW

**Comment by tipoima** [comment]
> Friendship ended with LR checking, "trying to put a monkey brain into every patient" is my new friend.

IMO if you end up putting someone's brain into a changeling, at this point they _should_ just die. 
It's not like putting brains in other crew's bodies is a common occurrence anyway. 
I've only seen this be attempted once and it was to fix mindswap shenanigans (so they knew they were operating on a changeling in the first place).

**Comment by tipoima** [comment]
Actually, what happens if the changeling is reimplanted with their own brain? (Such as if they got debrained by another antagonist and did not choose to revive due to witnesses, or in case of a severe malpractice)

**Comment by HMBGERDO** [comment]
> Actually, what happens if the changeling is reimplanted with their own brain? (Such as if they got debrained by another antagonist and did not choose to revive due to witnesses, or in case of a severe malpractice)

That would fail currently, but i like your idea with player getting permakilled if their brain connected to the changeling. Wait for updates

**Review by lewcc — COMMENTED** [review]
Is it possible that this might become a changeling check?

**Comment by HMBGERDO** [comment]
> Is it possible that this might become a changeling check?

it is possible that people will abuse it but like, trying to put a brain into a dead body is... weird action for security or medical personnel, that would be OOC check. If they try to reconnect head that ling lost in the fight, they would fail, yeah. 
But i think its better than causing all the issues with two brain bodies.
I may change behaviour with changelings in future in new PR since that one was already approved and i dont want it to pass the checks again

**Comment by FunnyMan3595** [comment]
> I may change behaviour with changelings in future in new PR since that one was already approved and i dont want it to pass the checks again

No, this needs to be resolved in some way before this PR goes in. The concept of the PR is good, but we don't want to be adding changeling tests to the game.

My proposal is to allow another brain to be implanted into the changeling body, but drop it out of the body when the changeling revives. Nobody immediately objected to that in dev chat, but it still might be wise to chat with balance about it before implementing--they know the realities of changelings better than I do.

**Review by Burzah — CHANGES_REQUESTED** [review]
Putting a Change Request on this PR until the concerns by @lewcc  and @FunnyMan3595 are addressed.

**Comment by HMBGERDO** [comment]
i am not going to do anything further in here
since https://github.com/ParadiseSS13/Paradise/pull/26020 was merged, it already fixes the most issue which is syndie MMI creating two-brain bodies.
Cases when someone put head on headless dead changeling are rare and i am not going to fix it in the way i've been told to

**Pull request closed without merging**
