### PR TITLE
Remaps Medbay Lobby, makes some QoL changes to Medbay

### PR DESCRIPTION
**Pull request by FreeStylaLT**
The pathing was always awkward, walking all the way through Paramedic's dacha to get to your _reception_ didn't make sense nor did it flow well. On top of that, the lounge area was awkward, as if there was no dedicated space for it and so instead it was made to take up a single tile space in Medbay. (that was precisely the case). 

This attempts to fix these issues:

**BEFORE:**
img

**AFTER:**
img

**IN-GAME:**
img

As you can see, this fleshes out the lounge area and makes the reception actually be attached to Medbay proper with direct access, reducing unnecessary walking to get there. This also separates Paramedic from the Reception, so **he gets his individual access back.**

Beyond that, there are a few other minor tweaks:

- The cell charger was moved to the break room, with a cell added on top of it, along with the medical warddrobe closet (which now has surgery caps):
img

🆑 FreeStylaLT
tweak: Remapped Medbay Lobby.
tweak: Moved the cell charger from Cryo to the break room.
add: Added a cell to Medbay's break room.
/🆑

### CODE REVIEW

**Comment by ID404-NotFound** [comment]
This is cool

**Comment by davidchan13** [comment]
From my understanding the tables and chairs directly inside medbay were so Doctors/Medstaff could take a break in view of the lobby incase a patient rolled in.

With this layout you might as well put doors on the west end or just remove all the walls save for a few support pillars and fire shutters around the lobby.

**Comment by FreeStylaLT** [comment]
conflicterinos fixed

**Comment by TravellingMerchant** [comment]
Looks fantastic! Great work.

**Comment by TDSSS** [comment]
Can you add (back?) in a microwave in the breakroom? Very useful for warming donk pockets.

**Pull request merged**
