### PR TITLE
Update sprites for drone fab and experimentor

### PR DESCRIPTION
**Pull request by dj-34**
## What Does This PR Do
Replaces drone fab and experimentor (heavy lathe by sprite name) sprites with 3/4 variants
Sprites by **FanTik**

## Why It's Good For The Game
We use 3/4 sprites

## Images of changes
image

## Testing
Tested in game

## Changelog
:cl: FanTik, dj-34
imageadd: 3/4 sprites for drone fab and experimentor
/:cl:

### CODE REVIEW

**Review by Contrabang — CHANGES_REQUESTED** [review]
please include `FanTik` in the changelog authors, along with yourself

**Comment by dj-34** [comment]
> please include `FanTik` in the changelog authors, along with yourself

👌

**Review by Contrabang — COMMENTED** [review]
Changes look good to me, but needs sprite team approval

**Review by Henri215 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]
Has been approved for sprites

**Pull request merged**
