### PR TITLE
Fixes *halt spam.

### PR DESCRIPTION
**Pull request by Spacemanspark**
I'm sorry.
@Markolie 
Fixes https://github.com/ParadiseSS13/Paradise/issues/1933
EDIT: Actually, this is a feature, since SOMEONE thought it was a good idea to make that intentional to spam.
(Am I even allowed to downvote my own PR's? :-1:)

### CODE REVIEW

**Comment by Alex6511** [comment]
This needs to be tested, possible spaghetti code reason why it was setup this way.


Or you know: derp.

**Comment by Spacemanspark** [comment]
I was firing DD up to test it.

**Comment by Spacemanspark** [comment]
Yep, it works.

**Comment by Fox-McCloud** [comment]
HALT, SECURITY.

**Comment by FalseIncarnate** [comment]
I made it intentionally since security can effectively do the same thing with their hailers and gasmasks.

**Comment by Spacemanspark** [comment]
Ah.
Gasmasks aren't spammable, if the sechailers are, they shouldn't be, that shit's ANNOYING.

**Comment by Fox-McCloud** [comment]
There's a CD on it---they can't overlap the sounds like security borgs can, but they can spam it so it's constantly making noise.

**Pull request merged**
