### PR TITLE
Adds Sprites for Some Armalis+Vox Gear & Species-fitting Inhand Icons, etc.

### LINKED ISSUE #11975: Mega vox only can wear regular mask instead of vox mask
**Problem Description**:
What is the problem?
Mega Vox can't use the vox mask only the regular mask to get N2.

**What did you expect to happen**: 
Why do you think this is an issue?
Only the height change not the shape of face.... There is still a beak.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Breaking the merge of the game.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I was a friendly IPC with some voxxies. One of them was an admeme, I was changed to vox later on to a mega vox.

### PR DESCRIPTION
**Pull request by KasparoVy**
**What does this PR do:**
I wanted to do some work on Armalis some years ago but forgot. #11975 reminded me so I fixed that and added some basic gear sprites for Armalis, species-fit earwear for Vox Primalis and fixed a couple minor issues in humanoid icon generation.

Resolves #11975

**Images of sprite/map changes (IF APPLICABLE):**
https://imgur.com/a/6UdGpuq

**Changelog:**
:cl:
imageadd: Adds sprites for all Vox & Armalis earwear.
imageadd: Adds sprites for Armalis default backpack, nitrogen tank (old-style back & new-style belt) & all breath mask variations.
add: You can now species-fit in-hand icons: Use a single .dmi file and suffix the icon states with _l or _r.
fix: Fixes an issue preventing Vox Armalis from being rendered with the proper in-hand icons for their massive noise cannons.
fix: Fixes an issue preventing the species-fitting of earwear.
fix: Fixes an issue preventing Vox Armalis from wearing the 'Vox' breath mask.
/:cl:

I've always wondered wtf was wrong with the noise-cannons all this time. Thankfully since the massive icon generation refactor it was a more straightforward fix.

### CODE REVIEW

**Comment by KasparoVy** [comment]
IDK what the deal is with appveyor but people seem to be fixing it by...

**Comment by KasparoVy** [comment]
_AppVeyor, 2019_
> Maximum allowed artifact storage size of 110000 Mb will be exceeded.

**Comment by SteelSlayer** [comment]
Those are some nice Mega Vox sprites.

**Comment by FreeStylaLT** [comment]
MEGA VOX

**Comment by Ionward** [comment]
oooh, great stuff! super skrees roll out

**Comment by taukausanake** [comment]
Really missed out on the title saying the fixes were for Mega Vox

**Comment by KasparoVy** [comment]
I didn't wanna go too deep on it

**Comment by Necaladun** [comment]
dear god this is so sexy its near breaking our erp rules

**Comment by variableundefined** [comment]
@KasparoVy Conflict

**Comment by KasparoVy** [comment]
Thanks for the heads up, I'll resolve the conflict once I'm home at 10EST

**Comment by KasparoVy** [comment]
Deconflicted @variableundefined, cheers

**Comment by KasparoVy** [comment]
Corrected a rogue pixel in the Armalis-fitted medical mask south facing sprite

**Pull request merged**
