### PR TITLE
Made flares brighter

### PR DESCRIPTION
**Pull request by MrBauer24**
updates flares, made them brighter as per the request.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
You need to go under Build -> preferences for Paradise -> uncheck "Automatically set FILE_DIR for sub-directories"

**Comment by MrBauer24** [comment]
done :)

**Comment by fj45** [comment]
A picture of the new flare would be good.

**Comment by MrBauer24** [comment]
If you find one I can implement it :)

**Comment by ZomgPonies** [comment]
@MrBauer24 Umm you need to commit the new changes.

**Comment by MrBauer24** [comment]
Done :)

**Comment by MrBauer24** [comment]
Just so everyone knows, this is a fix for #1045

**Comment by TheDZD** [comment]
Just so git automatically closes the issue, fixes #1045.

**Pull request merged**
