### PR TITLE
Biosuit resprite

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Ports the biosuit sprites from tg https://github.com/tgstation/tgstation/pull/69047
Specifically:
- The virology and security biosuits are ported unchanged.*
- The body sections of the science and medical suits are unchanged.*
- The head of the CMO one from tg is now the head of the medical one.
- The head of the science one from tg is now the head of the basic one.
- The janitor one is recoloured to match the scheme used for my previous janitorial resprite, otherwise unchanged.*
- The CMO one has been completely recoloured, a more unique outfit for the department head.
- I made a new sprite for the basic biosuit based on the tg ones as I wasn't sure if it is used anywhere in the code, though this could be used for a general crew one now and the "general" one be locked to medbay specifically.

*All biosuit bodies have been tweaked to add the shoulder bits to the east/west sprites, as well as adding boots to all directions.

This PR also splits biosuits from the dreaded suit.dmi and hat.dmi, beginning my quest to chip away at it slowly and reduce the size of those awful files.
Some code was changed to accomplish this, such as the code for the biosuit base item and a little in icon overlay code (two lines in both the hat and suit sections needed to be flipped. Not sure how or why this works, but it works.)

Vox, drask, grey and kidan are currently using plague doctor sprites for humans - This is consistent with how they currently work, just needed to add the human sprites directly to each file so there wouldn't be issues with the sprite file locations being set on the base item.

Fixes https://github.com/ParadiseSS13/Paradise/issues/25221

## Why It's Good For The Game
Better sprites

## Images of changes
From left, in columns: Basic, CMO, medical (general), janitor. Scientist, security, virology.
Before:
image

After:
image

Updated image to show with the boots
image

## Testing
Above images + magic mirror test with all species to make sure there were no errors
Tested modsuits for errors due to the changes to overlay code.

## Changelog
:cl:
imageadd: Ports sci, sec, viro, jani and medical biosuits from tg.
imageadd: Resprites CMO and basic biosuit based on tg sprites.
/:cl:

### CODE REVIEW

**Comment by ATP-Engineer** [comment]
radsuits next please
image

**Review by Burzah — APPROVED** [review]

**Comment by Christasmurf** [comment]
Converted to draft as I need to add boots to the sprites

**Comment by Henri215** [comment]
> Converted to draft as I need to add boots to the sprites

https://github.com/ParadiseSS13/Paradise/issues/25221
Link this issue once its done

**Review by Henri215 — CHANGES_REQUESTED** [review]
image

image

image

The selected code is supposed to be over the "if(head.sprite_sheets...)" and not the "else if(head.icon_override)"

**Comment by Christasmurf** [comment]
> The selected code is supposed to be over the "if(head.sprite_sheets...)" and not the "else if(head.icon_override)"

Done this, tested biosuit + modsuit + plasmaman helmet for errors, no problems, committed

**Review by Henri215 — APPROVED** [review]
Looks Honkable to me

**Review by Burzah — APPROVED** [review]
Re-approving changes after Henri's review. Looks good!

**Pull request merged**
