### PR TITLE
PAI Borgi Sprite Replacements

### PR DESCRIPTION
**Pull request by K3Licia**
## What Does This PR Do
Replaces the death and rest sprite for the pAI's borgi form while also making said rest sprite directional.

## Why It's Good For The Game
About every other pAI has a noticeably different rest emote, meanwhile the borgi form is just... standing there with its animation turned off. I believe that difference is jarring (and frankly plain-looking) when pointed out and this would help to give it the same flair as the other forms. I also felt as though the death sprite could look better and therefore enhance the form once more.

## Images of changes
Old Death Sprite
image
New Death Sprite
image

Old Rest Sprite
image
New Rest Sprite
borgi slow turn

## Changelog
:cl:
imageadd: Added new sprites for the borgi pAI
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
Account is linked, PR is technically sound but requires approval from @McRamon

**Comment by McRamon** [comment]
jesus the sprites are bad! someone needs to resprite damn pAIs. though that is not for this pr
the sprites are fine for now

**Comment by K3Licia** [comment]
> jesus the sprites are bad! someone needs to resprite damn pAIs. though that is not for this pr the sprites are fine for now

honestly agree, full overhaul did cross my mind but also i am not too keen on it atm

**Review by Sirryan2002 — APPROVED** [review]

**Comment by S34NW** [comment]
Please update this branch from master to resolve CI issues that were fixed in https://github.com/ParadiseSS13/Paradise/pull/21301

**Pull request merged**
