### PR TITLE
Adds the ATMOS-holofan to the Protolathe

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## What Does This PR Do
Adds the ATMOS Holofan to the Protolathe
Needs
 - 5000 Metal (2.5 sheets)
 - 1500 Diamond (0.75 sheets)

 Requiring research levels 
 - Materials 4
 - Engineering 6
 - Magnets 7

## Why It's Good For The Game
Currently its impossible to get more than the 4 round start holofans, so any that are cryoed with (not sure if thats fixed yet), melted, recycled, lost, etc, are permanantly gone. This adds them to the Equipment section of the auto lathe for 2.5 metal sheets and .75 diamonds each, needing later game research to unlock. I may increase the price much more so that its what it is currently but with an upgraded Protolathe, but I'm not sure what thoughts on this are currently as its a item thats normally very rare becoming technically unlimited.

## Images of changes
atmosfanchanges

## Changelog
:cl:
add: Adds ATMOS Holofan to the RND Protolathe.
/:cl:

### CODE REVIEW

**Comment by Wojz** [comment]
This enables ungodly amounts of cheese unfortunately. It's silly enough what atmos can build with their roundstart holofans already...

**Comment by matttheficus** [comment]
Atmos is already gimped enough by not having anything to do at all. Removing one of their SINGLE uses by making their most robust tool wide-spread seems like another kick in the face.

**Comment by AffectedArc07** [comment]
Yeah.

No.

**Comment by DeveloperLoser** [comment]
Good points that I didn't consider about gimping atmos techs further.

**Pull request closed without merging**
