### PR TITLE
Moonshine Bottle - Nethiafins donator item

### PR DESCRIPTION
**Pull request by AndriiYukhymchak**
This item is for nethiafins character "Serhij Zozulia" containing boxed moonshine bottle with two shotglasses. Bottle has 100u in it.

Still awaiting for clearance from admins.

No CL, as it is unnecessary.

### CODE REVIEW

**Comment by warior4356** [comment]
All PR must have changelog. IT IS LAW!

**Comment by taukausanake** [comment]
If anyone actually reads the changelogs it might be nice to see in it all the cool stuff people get by donating to the server. But therein lies the problem, _actually reading the changelog_

**Comment by king5327** [comment]
I legitimately read the changelogs but have no idea how to start the [cl] thing.

**Comment by andrii-yukhymchak** [comment]
@taukausanake I read the changelog EVERY time. It is important for mentors

**Comment by FalseIncarnate** [comment]
@king5327 and maybe @AndriiYukhymchak https://tgstation13.org/wiki/Guide_to_Changelogs explains how to do changelogs. Even though fluff items don't necessarily NEED a changelog, I recommend including them anyways.

It makes it easier to know when the item is patched in and also can help avoid other players mistaking it as a non-fluff item and wondering how to get it.

**Pull request merged**
