### PR TITLE
Adds Beesplosion Chemical Reaction

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/tgstation/pull/39110

A chemical reaction largely for botanists.

Bee explosion creates bees, on reaction, and picks a random reagent that's in the container for each of the bees that it creates.

:cl: Fox McCloud
add: Adds beesplosion chemical reaction
/:cl:

### CODE REVIEW

**Comment by Pennwick** [comment]
Correct me if I'm wrong but does this check at all to see if they're sketchy reagent bees? Since you're bypassing the queen bees I think they can have any Reagent. Botany alone probably couldn't get into too much trouble but a Traitor Botanist with a good poison bottle or if Xenobiology got their hands on some honey they could cook up some terrifying swarms.

**Comment by taukausanake** [comment]
@Pennwick that almost sounds like how it should work. If you're making beenades then you're most likely trying to cause some trouble anyways. Or Science but since when isn't R&D trying to blow/kill themselves to oblivion?

**Comment by Pennwick** [comment]
@taukausanake The issue is a lot of these chems are non-synthable for a reason. Queen Bees check for the Can Synth tag which checks if an Oddysius can synth it. Bees can inject a random amount of 1-5 per sting. Here are some examples of what these bees could contain, all of which can be found in the poison bottle:

Concentrated Initropidril: Heart attack at 5u (2-3 stings likely)
Heartworms: Heart removal at >4.5 (2-3)
gibbis: infects with curable gbs at 2.5 (1-2)
Xenomicrobes and Nanomachines: infects at 1.5 (1) Also available from Xenobio
Prions: Infects with uncurable Kuru at >4.5 (2-3) available through brainburgers
There are probably more that I'm missing but these are some of the most deadly at bee sting levels. Theres a reason they're not synthable.

**Comment by taukausanake** [comment]
I get what you're saying, and you're wrong, because you're not synthifying any of these reagents. You're using them in something and they're getting used. The reason those reagents were removed from queen bees and the Oddysius was because they could multiply them. Bees by themselves can't and I don't think you can extract the reagent from them anyhow

**Pull request merged**
