### PR TITLE
Adds "hydrogen hydroxide"

### PR DESCRIPTION
**Pull request by monster860**
Hydrogen hydroxide is a new chemical used for cleaning shit. However, when mixed with certain chemicals, it can cause explosions. It can also slip people, and is used to put out fires.

:cl: monster860
rcsadd: Adds hydrogen hydroxide.
/:cl:

### CODE REVIEW

**Comment by Regen1** [comment]
Fuck no, this is way too deadly

It can literally kill the entire population if you have enough of it

**Comment by monster860** [comment]
How? By putting it in a pill? How do you expect to feed everyone a pill?

**Comment by TheDZD** [comment]
This is as dangerous as oxidane, and hydroxic acid. Too OP.

**Comment by monster860** [comment]
So? It's not any easier to make!

**Comment by Vivalas** [comment]
Is this a serious PR?

**Comment by Chakirski** [comment]
Needs to be renamed to dihydrogen monoxide.

**Comment by FreeStylaLT** [comment]
pretty sure the correct term would be hydrogen dioxide, you PR'd a HOH, not H2O

**Comment by monster860** [comment]
What you just said is actually HO2, not H2O.

**Comment by FreeStylaLT** [comment]
if you can read chemistry why did you choose a specifically incorrect name for water

**Comment by monster860** [comment]
Because too many people will recognise dhmo.

**Comment by Chakirski** [comment]
It's not "incorrect", it's just a way to name water in a systematic alkali way

**Comment by Fox-McCloud** [comment]
HUE

**Comment by IcyV** [comment]
Aren't you perma'd, Monster?

Also, this is hilarious.

**Comment by monster860** [comment]
@IcyV Yes, but that doesn't stop me from making MEME PR's (Or NONMEME PRs!)

**Comment by Ar3nn** [comment]
Wait monster's banned from the server?

**Comment by KasparoVy** [comment]
lmfao this joke

bahaha :droplet:

**Comment by PJB3005** [comment]
Did you know hydrogen peroxide can kill people?

**Comment by Regen1** [comment]
mfw nobody got the drowning joke

**Comment by Fox-McCloud** [comment]
Memes.

**Pull request closed without merging**
