### PR TITLE
Temperature fixes

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Firesuits will now make you completely immune to fires, granted that the fire isn't too hot, of course.
2) You will now actually be affected by cold and hot air - not just when you're on fire.
3) You will now take less damage from stage 3 hot environments when not on fire.
4) Fixes players taking no oxyloss when in critical.
5) Reduces the Malf AI starting timer, as it was way too high.
6) Fixes a possible runtime with the captain's display case.

Fixes https://github.com/ParadiseSS13/Paradise/issues/434.
Fixes https://github.com/ParadiseSS13/Paradise/issues/456.

### CODE REVIEW

**Comment by Markolie** [comment]
@Fox-McCloud Not sure if this requires any other changes (i.e. the oxyloss in space being reduced), as this might unbalance things.

**Comment by ZomgPonies** [comment]
Fixing the bug is priority one, we can always rebalance after.

**Comment by Markolie** [comment]
Well, I fear that space may be extremely deadly now due to the 3 oxyloss as well as very high cold damage, which is a considerable balance issue.

**Comment by Fox-McCloud** [comment]
@Markolie 

Space isn't cold on our codebase as there's specific checks elsewhere that prevent it from happening--plus the temperature of space itself is 273k as opposed to 2.6K

If/when LINDA is ported, I would suggest making space cold, but currently, with how ZAS functions, an entire zone instantly become cold if it's depressurized is pretty damn devastating, so the way it is now is probably fine.

There's a few more things I'll need to test out, once this gets merged in, as there's a few other weird oddities about temperature, but this looks like a great start.

**Comment by Markolie** [comment]
Good to go then.

**Comment by Fox-McCloud** [comment]
@Markolie 

Yeah, that's my mistake.

I'd suggest incorporating this, as well: https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/carbon/human/species.dm#L1316

Where only heat damage level 3 is applied if your body temperature is above that thresh-hold AND on fire; it helps cut down on fires being near insta-murder unless you're actively IN them.

**Pull request merged**
