### PR TITLE
Stops vampires spawning in the church :fire: :scream: :fire:

### PR DESCRIPTION
**Pull request by SamHPurp**
As per request of Dragnoir on Discord. Press F to pay respects.

Moves the spawn points for civvies out, one spot is in the chair next to library, and the other is in front of the arcade machine in escape.

:cl: Purpose2
fix: Stops vampires spawning in the church.
/ :cl:

### CODE REVIEW

**Comment by TravellingMerchant** [comment]
Great idea. You work fast.

**Comment by Crazylemon64** [comment]
hawt

**Comment by Fox-McCloud** [comment]
Conflictssss

**Comment by SamHPurp** [comment]
@Fox-McCloud done - though Travis appears to be on vacation.

**Comment by SamHPurp** [comment]
There you are Travis. Good boy.

**Pull request merged**
