### PR TITLE
Removes "Ass"-related words from AI vocabulary

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
fix: Kills AI voice announcement memes.
/:cl:

### CODE REVIEW

**Comment by Anasari** [comment]
Purge the ass. Plus one from me.

**Comment by SigholtStarsong** [comment]
Save the ass. Minus one for memes.

**Comment by Necaladun** [comment]
+1 for removing LRP sillyness.

**Comment by Kyep** [comment]
Consider also removing:
- Johnson
- USA
- Abortions
- Cancer
- Catbeast
- Cunt
- Fuck / Fucking
- Helicopter
- Shit

Consider adding:
- A tracking system which saves any word an AI player TRIES to use, but cannot (because it isn't in the list) to the database. After a month, we look at what words people are trying to use, but can't, and consider adding them.

**Comment by Anasari** [comment]
I agree with what Kyet say.

**Comment by Crazylemon64** [comment]
I'm not sure how these vocabulary words are generated, so adding new words seems difficult. Does anyone know how these words were created?

**Comment by DesolateG** [comment]
Ass blast usa helicopter Johnson JOHN MADDEN

**Comment by Kyep** [comment]
If memory serves, there's a voice synth program that does it, but it only runs on mac.

**Comment by Necaladun** [comment]
Yeah we're looking at a bunch of others.

...I kinda want cunt to remain because of my australian culture, but it also makes sense that NT wouldn't put those into the AI.

**Comment by Crazylemon64** [comment]
This is more for the sake of meme-killing than it is about killing foul-mouthedness

"Ass" is just the most egregiously abused

**Comment by Necaladun** [comment]
Death to memes.

**Comment by davidchan13** [comment]
Hugbox

**Comment by SamHPurp** [comment]
@Crazylemon64 I had basically this exact PR in the works, but with Kyet's additions as well.

Thumbs waaaaaay up.

**Comment by Twinmold93** [comment]
not mac, created on linux

**Comment by tigercat2000** [comment]
this is silly and excessive

**Comment by Fox-McCloud** [comment]
People are just going to spell this out or come up with another euphamism for it. The nature of being able to broadcast any message you like, over a global voice channel, is inherently going to lead to memey stuff like this, regardless of the vocabulary set (unless it's INCREDIBLY restrictive).

As for ass explicitly---I'm really not sure how this is a meme (aside from ass blast, USA, which absolutely is and "ass day", which is more of a Goon meme); "the crew are assholes", "captain is an asshole", "X is an ass" is where it's usually utilized---which isn't really a meme so much as petty insult/profanity.

**Comment by Lady-Luck** [comment]
at LEAST make it possible for the AI to use the bad words on Code Delta

**Comment by SamHPurp** [comment]
Remove "Woody" and "wood" too.

**Comment by Anticept** [comment]
@Fox-McCloud i rarely ever hear it used outside of ASS BLAST USA and ASS INSPECTIONS. And, in my experience, it isn't just once or twice, if someone does it once, they are doing it constantly. It's distracting.

**Comment by davidchan13** [comment]
Improve, don't remove. Most AIs barely seem to know they have an announcement feature, and the ones that do rarely use the 'meme' buttons enough to warrant their remove. They are used as a joke or to help get the point across by insulting thick skulled crew or antags.

**Comment by LittleBigKid2000** [comment]
>Remove ass-related words from the AI announcements to improve arr pee

>Still allow 'Fox McCloud'

Yeah no

**Comment by Anticept** [comment]
There is nothing you can do to improve "ASS" that compensates for its misuse.

And this isn't "fun", its immature humor.

**Comment by Necaladun** [comment]
Please keep things on topic and related to it, not use it to attack others. There's currently a big discussion on the forum for naming rules. 

The AI is the only one to be able to make vocal announcements. They attract a lot of attention because of this, and have a much stronger effect on immershoms than regular radio chatter. These shouldn't be used for memes or even to call people an ass. The intent is for them to be able to make a clear warning about plasma fires in medbay, etc. Not to call the Captain an ass. Having such words encourages people to make stupid announcements like that. This doesn't stop the AI from calling the Captain an ass, they just have to use the radio to do so like everyone else.

**Comment by Da-Dman234** [comment]
I'm going to point out the obvious fact that back when we were actually still considered MRP AI had even MORE abusable verbs. While I personally am not a fan of memes, they certainly give this game a unique charm I don't want to see go (but increasing the cooldown on AI voice announcements would be cool). 

The RP level isn't a problem caused by rules or other small things like this, but rather the playerbase.

**Comment by Necaladun** [comment]
I agree, however fostering a higher RP environment is something that is done with a large amount of small changes that encourage it, and discouraging lower RP and low hanging fruit. 

No one change is going to be a magic bullet to fix it. Banning for "poor RP" is something that I've never felt comfortable with.

There are still plenty of memes available, this just removes some of the overused and frankly annoying ones.

**Comment by Da-Dman234** [comment]
I was under the impression memes were supposed to be overused and annoying 💯 😄 

I can certainly understand what you're trying to do, but realistically I personally believe that we'll never regain our MRP status with the current playerbase. You obviously are probably privy to more detailed information regarding the subject than I am, but a lot of this game's charm (and Paradise's) come from stupid stuff like this. While I can understand forsaking it for a HighRP server, I don't think the tradeoff is worth it if were trying to strive for MRP, especially with how difficult I see it taking to get there.

That being said, this is just a stupid announcement. It's just that I feel like if we start approving stuff like this it'll set us down a path where a lot of this games uniqueness is lost, and I would be incredibly sad to see that.

**Comment by uraniummeltdown** [comment]
unnecessary fun removal

**Comment by Birdtalon** [comment]
Again something else attempting to be removed which can be fun because a certain number of players abuse it and spam stupid stuff. I dislike the immature nonsense when it's overused however I'd rather that we target those players rather than remove something from all of us. Big thumbs down.

**Comment by Draconic-saint** [comment]
R D BACK UP THAT A S S.

Don't fix attittude with removing shit. If someone spams ai vox, ahelp that shit, and if the admins don't deal with it, complain about that shit. And if you're annoying by a single ass, that speaks more about you than the ass.

On a semi-related note, I feel like we need a "man up and deal with it" button on the github too.

**Comment by Crazylemon64** [comment]
Time to do a blind trust-fall on the admin team!

**Pull request closed without merging**
