### PR TITLE
More holopads for medbay, by request of Plotron.

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit adds around 7 new holopads to medbay, so the AI can have a
presence there.

@Plotron

Before
After

### CODE REVIEW

**Comment by veganzombeh** [comment]
I'd support holopads getting more coverage, but I think don't think cluttering the medbay with holopads while other departments are just as lacking is the best solution. Personally, I'd prefer to see holopads' range increased instead, or scrapping holopads and having cameras project holograms.

**Comment by tigercat2000** [comment]
@veganzombeh As far as I know, the holopad only transmits and recieves speech in line of sight, so increasing the range wouldn't do much. And since medbay has walls around, requires quite a few holopads to have line of sight to cover most of it.

**Comment by ZomgPonies** [comment]
I don't think any one department should have full coverage. Holopads are an aid to the AI, they are not mandatory to allow him to do his job.

**Comment by Fox-McCloud** [comment]
Yeah---AI is meant to have some blind spots so it has to do some guesswork.

**Comment by tigercat2000** [comment]
@Fox-McCloud 
Unless I am misunderstanding you, I think you might be confusing holopads with cameras.

**Comment by Fox-McCloud** [comment]
I mean blindspots with the holodpads, not the cameras--sorry for lack of clarity.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by ZomgPonies** [comment]
Two maintainers voted this down in it's current state. Cut down on the amount of holopads by a LOT: I mean 1 in each surgery, 1 at reception, 1 in cry/cloning and 1 in CMO office, that's it. Random corridors don't need holopads, etc.

**Comment by Earthdivine** [comment]
The Ai really doesn't need that much of a spread of Holopad's, they are all barely in range of one another, even if they don't overlap. The Ai Hologram has the hearing range of a person, just standing a ways off can still get you in the conversation.

**Comment by Plotron** [comment]
Yes, there are some redundant holopads in the corridors. The chemistry/medkit storage area looks a bit like an overkill, the same can be said about the medical fridge and CMO's left door (I know it's to cover the sleeper area; it's a compromise). The exam room serves little purpose and there's little incentive to keep a holopad there. I'd keep the holopad in the break room for roleplay purposes, though.

Would the maintainers be fine with the other holopads if we addressed the issues outlined above?
Would you oppose the chemistry holopad where AI could contact/question chemists in a more face-to-face roleplay fashion?

Keep in mind that Medbay is cramped (no big open rooms) and that it is one of the places where you may want to contact the AI (malpractice, patients, naked clones, medbay emergencies, AI medical guidance).

To sum it all up, I propose changes to the original PR:
a) remove following holopads (4): medkit storage, medical fridge, sleeper corridor, exam room;
b) move the cryo sleeper into the room, so it won't stick out in the corridor.

This way the most important places of Medbay will be covered (where it makes sense to have a holopad), while the corridors won't.

We could also compensate for the additional coverage by removing the holopad located behind reception - in the locker/syringe gun/utilities area.

**Comment by ZomgPonies** [comment]
That would already be better yes.

**Comment by Plotron** [comment]
I'll message @tigercat2000 to adjust the PR then, thanks. Hold on tight.

**Comment by tigercat2000** [comment]
@Plotron I've taken notice, haven't found time to finish it.

**Comment by tigercat2000** [comment]
Removed the holopads and moved stuff around.
321tj3ged9cbf

**Comment by Plotron** [comment]
Looks balanced to me! And they no longer stand like a sore thumb.

**Comment by ZomgPonies** [comment]
I still think there's way too many, but that's just me I guess.

**Pull request merged**
