### PR TITLE
The World Can Burn For All I Care

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Friggin' darn crappy stack code. DIE.

fixes: https://github.com/ParadiseSS13/Paradise/issues/10979
fixes: https://github.com/ParadiseSS13/Paradise/issues/10984

:cl: Fox McCloud
fix: Hopefully fixes weird stack issues. Maybe. Who knows. The World can burn.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
F

**Comment by KasparoVy** [comment]
Stacks of wack

**Comment by Fox-McCloud** [comment]
#selfmergealldayeveryday

**Comment by AffectedArc07** [comment]
image

**Comment by Spacemanspark** [comment]
My guess is that he got permission to do it because the other maintainers were busy :P

**Comment by Fox-McCloud** [comment]
This was a very high priority problem; players being nearly perma-frozen after dragging around tiles, having 0 stack items that are runtime-city-USA, and causing goodness knows what other kinds of issues for stacks are all pretty game-breaking.

There was an internal vote to bypass the typical "merge another maintainer's PR" rule because all the other maintainers were unavailable and the issue needed to be fixed ASAP.

I would have thought that would have been obvious, especially as a "Fix" PR marked "high priority" and the fact that this hasn't happened in recent memory since....at least 2 years ago.

**Comment by KasparoVy** [comment]
Haven't had any issues since but the one I mostly ran into was the character freezing (only fixable by closing and re-opening client), happy to see it fixed either way

**Pull request merged**
