### PR TITLE
Replace the sounds for the Resonant Shriek and Dissonant Shriek Cling powers.

### PR DESCRIPTION
**Pull request by Scribble-Sheep**
## What Does This PR Do
Adds two new sound effects composed of various ingame screams, and replaces the Resonant and Dissonant shriek sounds for Changelings.

## Why It's Good For The Game
As of right now, the sounds that play for these abilities is the generic emp "woosh" sound, and an ear-bleeding shriek noise. I think having these sounds not only adds a bit more character to the abilities, but in the case of Resonant Shriek, also makes it a bit less...painful to use.

## Images of changes

https://user-images.githubusercontent.com/46016730/190839455-c2a2a1da-84bb-46e5-b961-c5f1934954d1.mp4

https://user-images.githubusercontent.com/46016730/190839461-ded90ae0-d922-4ba3-a4ca-072e47b75ea2.mp4

## Testing
I loaded up a test server, turned myself into a changeling, bought the abilities, and used them to ensure the sounds played.

## Changelog
:cl: Sciuridian
soundadd: Added Ling_Resonant.ogg and Ling_Dissonant.ogg
tweak: Changed the Cling shrieks to use the new sfx
/:cl:

### CODE REVIEW

**Comment by Scribble-Sheep** [comment]
Forum account has been linked. acbff17 is from syncing my fork with the upstream master, idk how to remove that from the commit.

**Comment by AffectedArc07** [comment]
> [Scribble-Sheep](/Scribble-Sheep)

PR author has now linked account

---



> Forum account has been linked. [acbff17](https://github.com/ParadiseSS13/Paradise/commit/acbff171dca22bc72715dca38544992d5efad485) is from syncing my fork with the upstream master, idk how to remove that from the commit.

Dont worry about it.

---

What is the source on these sounds? And more importantly, are they license permitting.

**Comment by Scribble-Sheep** [comment]
> What is the source on these sounds? And more importantly, are they license permitting.

I created them myself using the male/female human screams, and the vox shriek1 in Ableton 10.
Used Serum FX and some Valhalla vsts (Specifically supermassive and SpaceModulator) to get the effects, which afaik, should be fine, license wise?

**Comment by Scribble-Sheep** [comment]
Closing to re-pr it uh...not on my main branch.

**Pull request closed without merging**
