### PR TITLE
Department head jobs now require playtime in that department

### PR DESCRIPTION
**Pull request by Kyep**
:cl: Kyep
tweak: Changed playtime requirements for command jobs. HoS/RD/CE/CMO/AI now require 5h played in their department to be playable. HoP/Captain now require 5h played as a member of the command staff.
/:cl:

More detailed overview:
- HoS/RD/CE/CMO now require 5h played in their department. So for example HoS requires at least 5h played as security.
- AI is treated as a head for this, meaning playing AI now requires playing 5h in the "silicon" department (ie: as a cyborg)
- Captain/HoP require 5h played as a member of the command staff (ie: HoS/CE/RD/CMO/NTRep)
- Overall, this means that playing a head of a department now requires you to have spent a little time in that department, and commanding the station (as Captain or Acting Captain) now requires you to have spent a little time playing a head of a department.

Combined Breakdown:
- HoS/RD/CE/CMO/AI: previously required 20h as crew. Now requires 5h in their department. Their department requires 3-10h to get into (3h for med, 5h for eng/sci/silicon, 10h for sec). So, 8-15h combined, which is close to the previous 20h as crew requirement, except that it now focuses on time in their department, rather than time overall.
- Captain/HoP: previously required 40h as crew. Now requires 5h as command. Since playing command now requires 8-15h combined (depending on department), an additional 5h as command brings the total here to 13-20h. This is significantly less than the previous 40h as crew requirement... but in exchange it requires most of that time to be not civilian, and more than a third to be in a command job. Since some people rarely play command jobs, I think this is a fair trade.

### CODE REVIEW

**Comment by Couls** [comment]
Speedmerge for the love of god speedmerge!!!

**Comment by Ralta** [comment]
I'm sure I know the answer but just to be certain, this will prevent people from being put into those positions if their game preferences are set to choose a random job, right? Assuming they don't have the requisite playtime, of course.

**Comment by Kyep** [comment]
@Ralta Yes, it will prevent that.

**Comment by Bookdrizzt** [comment]
How will this affect players who had the requisite playtime prior to this being merged?

**Comment by Kyep** [comment]
@Bookdrizzt Most likely, they already have the roles they play regularly unlocked, because we've been tracking department playtime for a little while now and their prior department playtime will count towards the new requirements. In the event that they don't, then its still only 5 hours in a department to unlock playing the head of that department, which is not a difficult requirement to meet.

**Comment by Jazz23** [comment]
Yea I hate it when the CMO thinks that "heart tissue damage beyond the point of defibrillation" means repair the heart via spamming trauma kits without even doing surgery then continuously defibbing 10 15 times before trying to clone only to realize they're a slime then they leave them on the ground for some random civilian to notice and actually do something. There have been endless situations where heads are clearly more of a rookie then those who they command, ples merge this.

**Pull request merged**
