### PR TITLE
EngiVend has camera assemblies & be used by borgs

### PR DESCRIPTION
**Pull request by Tastyfish**
Implementing this topic http://nanotrasen.se/forum/viewtopic.php?f=12&t=7144
:cl:
rscadd: EngiVend now has 10 camera assemblies.
tweak: Borgs can now use vending machines.
/:cl:

### CODE REVIEW

**Comment by Gummin** [comment]
I was a scientist once, this borg came about every ten minutes for almost the entire shift into RnD to get a camera from the autolathe.
I felt bad for him. :+1:

**Comment by FalseIncarnate** [comment]
Since this likely applies to all vendors, you might want to make sure it handles properly with the ones that actually take funds to dispense stuff. Not sure if borgs get bank accounts, so might want to see what happens there.

Also, if that becomes an issue, perhaps just place a new var on vendors (something like var/borg_friendly = 0) and then set it for any vendor borgs should be able to use. You can then simply check if the machine is even usable by them with that var rather than try and scatter about more checks. In all honesty, things like a clothes and snacks vendor aren't really useful for borgs anyways, so stopping them from using those is fine in my book.

**Comment by Tastyfish** [comment]
@FalseIncarnate For the ones that require money, they just can't pay, like a person without an ID, since that was always the functionality. I could go further and allow borgs to pay with the station account, like they can with slot machines, etc, for the sake of serving.

**Comment by FalseIncarnate** [comment]
Might be an interesting idea, but just wanted to make sure they weren't magically bypassing the payment step of things and just vending directly.

Could possibly tie the ability to purchase from the station account to the service borg module (they apparently used to be the only borgs capable of using vendors before this) so they still can do their intended job: serve the crew. Might be a bit snowflakey though...

**Comment by Tastyfish** [comment]
The debit code in the vending machine was some things overly manually / wrong by the current way things were done too.

**Pull request merged**
