### PR TITLE
Wall lockers now require a click-drag to put a mob into them

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Makes wall lockers, when closed, only pick up items on their tile instead of mobs. 
You can still fit a mob into the locker if you click-drag, but you'll only be able to fit one inside.

## Why It's Good For The Game
Wall lockers are pretty much little cabinets, you shouldn't really be able to instantly stow yourself away in them, at least not without a little bit of difficulty.
Letting you click-drag yourself (or another mob) still lets these be used as little stashes, but now it requires at least a bit of work, and they'll still only hold one.

## Images of changes
txDOLUvP

## Testing
See images

## Changelog
:cl:
tweak: Mobs can now only be put in wall lockers after a short delay by click-dragging.
/:cl:

### CODE REVIEW

**Review by DGamerL — APPROVED** [review]
Code looks good 

Ideaguying: Contortionist suit maybe working on this?

**Comment by TravisAngeI** [comment]
> Code looks good
> 
> Ideaguying: Contortionist suit maybe working on this?

my first idea when i saw this PR was making it a clickdrag and taking like 5 seconds and giving you a movement penalty when you got out?
this idea kind of originates from attempting to turn it into an ambush plan instead of just outright removing it

**Comment by lewcc** [comment]
> > Code looks good
> > Ideaguying: Contortionist suit maybe working on this?
> 
> my first idea when i saw this PR was making it a clickdrag and taking like 5 seconds and giving you a movement penalty when you got out? this idea kind of originates from attempting to turn it into an ambush plan instead of just outright removing it

Yeah, that's a fair point! I was thinking about that. I'd be happy to implement something like that myself.

**Comment by Dafrek** [comment]
Why is hiding in wall lockers pretty much peak cheese? Just like regular lockers they make a distinct noise when you open and close them and it only takes a single click to check inside of one. With this change you will be able to store 30 toolboxes in a single wall locker, but not a person, which does not make much sense. The only actual issues I've noticed with these are the lack of a "welded-closed" sprite and the poor positioning of them in Cyberiad medbay.

**Review by DGamerL — COMMENTED** [review]
New changes are mostly LGTM, but it should maybe do a check how many mobs are in it's contents and increment `itemcount`, otherwise you might end up with 1 more item/mob in a wall locker than possible

**Comment by Dafrek** [comment]
> this is because they're on a wall and people aren't typically looking for lockers on walls making it a really good way to hide from people after turning a corner because nobody opens them, theres probably better ways to phrase this but its the best i could come up with

I agree that they are better hiding spots than normal lockers, but compared to something like plants, they are mostly an inferior hiding spot, especially when used while being actively chased. In that situation grabbing a plant and standing where it was placed makes no noise meanwhile hiding in a wall locker would make a noise that would inform sec that you just entered a locker.

**Pull request closed without merging**
