### PR TITLE
Refactors Barsigns

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors the bar sign (from TG)

The previous bar sign ran off text to icons and a poor "name to to text to icon"....It was...overall very ugly and not very modular, at all.

In any event this refactors the bar sign to utilize datums; this not only makes it a bit easier to add new signs in the future, but allows for customized names and descriptions to be set for the signs.

Pics of all the signs that will be available:

sign sign everywhere a sign
Please click on this to make it larger if you want to see it better (please note, The Orchard will NOT be included).

Other features
- can emag the barsign for a special sign 
- can emp the barsign to make it go haywire
- can repair the barsign
- Sign automatically reads your access on your card instead of having to be clicked on WITH a valid ID card.

Changed/Removed Stuff
- Added in all of TG's signs
- Removed all but one of the Dorf fortress signs (I hardly ever see these used or cared about and there really wasn't a need for literally 6-8 dwarf fortress signs that looked the same, but had a different bar name)
- Retained all our previous signs (had to write up the descriptions myself).

### CODE REVIEW

**Comment by tigercat2000** [comment]
Oh, nice. I had a branch for this, but odd compile errors and stuff and getting busy meant I never got around to finishing it.

As a note, I don't think you should remove the dwarf fortress signs that have a different name, and being able to set the bar sign to the off or on state is intentional, so, I would make the off state non-hidden and add an on state.

**Comment by Fox-McCloud** [comment]
Really don't think having duplicate signs is necessary. Literally every Dwarf Fortress sign is this:

ugly with a different name (it's not even properly illuminated).

The sign by itself is fairly ugly and lacks detail (like all the others), and our community isn't exactly into dwarf fortress, like Bay is.

**Comment by tigercat2000** [comment]
@Fox-McCloud Eh. Fair enough. I didn't really like them either, to be honesty, so. Point still stands about being able to turn it off and/or to a blank on state, though.

**Comment by ZomgPonies** [comment]
Yeah I had purposefully not added all of the un-animated, ugly, cookie cutter barsigns, OR the ones that were memes about specific players/servers. Fox, could you make a list of the signs you actually added back in?

**Comment by Fox-McCloud** [comment]
Sure.

**Comment by Fox-McCloud** [comment]
Snipped out the Orchard.

**Pull request merged**
