### PR TITLE
Changes mod say into mentor say

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Since moderators aren't a thing any more, as far as I can tell, and mentorhelping as a mentor or admin can basically be used as msay...

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Nooooope.

We removed this for a reason.

**Comment by tigercat2000** [comment]
nope

**Comment by LittleBigKid2000** [comment]
What was the reason?

**Comment by Spacemanspark** [comment]
So mentors cannot communicate with each other in game.
...Which makes no sense really but still.

**Comment by Krausus** [comment]
Yeah, that *doesn't* make sense. Why wouldn't we want mentors communicating?

**Comment by LittleBigKid2000** [comment]
I'm going to reopen this until someone can give me a good reason as to why this shouldn't be merged here.

**Comment by Regen1** [comment]
Ok here's a good reason

Both head admins and most seniors said no.

The rest of the seniors hasn't said anything on it

**Comment by LittleBigKid2000** [comment]
I'd like to know _why_ they said no, though.

**Comment by MindLeaker** [comment]
Honestly? No.
The purpose of mentors are to answer questions, we aren't staff, there isn't really a reason for there to be a chat aside from "Why not?", which isn't a good argument regardless.

Not to mention, there's the possibility of it being abused, be it intentional or accidental.

**Comment by FreeStylaLT** [comment]
Mentors already have a dedicated Discord chat, which is A) Not used for anything mentor-related B) is not even active. 

Regardless of that, why do you need it? How is this chat going to help any of the Mentors fulfill their responsibilities rather than turning into a poo-colored memesay?

**Comment by Krausus** [comment]
> Mentors already have a dedicated Discord chat

Completely worthless when they're in-game helping players.

> there isn't really a reason for there to be a chat

> How is this chat going to help any of the Mentors fulfill their responsibilities

Mentors aren't flawless question-answering savants. If they're not sure about the answer to a question a player is asking, it would be better to ask other mentors than to simply sit around hoping another mentor answers, or blurting out a potentially wrong answer.

And, in some cases, it would be helpful for mentors to be able to communicate with admins, or vice versa. For example, if an admin wants to tell all mentors to avoid answering questions about an event, too bad, there's no easy way to communicate with them.

> turning into a poo-colored memesay

This "durr, they'll probably just abuse it!" attitude is absurd. Potential for abuse isn't a reason to completely ignore the benefits of something. The worst excuse I've heard is that mentors - people who are already **trusted** to answer questions that could reveal information about the current round - will use the chat to *metagame.* Do you guys trust them, or not?

**Comment by Spacemanspark** [comment]
>This "durr, they'll probably just abuse it!" attitude is absurd. Potential for abuse isn't a reason to completely ignore the benefits of something. The worst excuse I've heard is that mentors - people who are already trusted to answer questions that could reveal information about the current round - will use the chat to metagame. Do you guys trust them, or not?

This, very much. We often times know the antag type, the name of at least one, if not more, and even the location and health of said antag(s) in less than ten minutes into every round.
That said, I'm not going to parade against the headmins' wishes, there might be more than one reason that they don't permit it. And I trust their judgement.

**Comment by Krausus** [comment]
> there might be more than one reason that they don't permit it

Maybe. Let's find out. @Necaladun, please weigh in on this topic.

**Comment by EpicCharger** [comment]
I'm indifferent. I use the discord channel to ask questions if I don't have answers to them to mentors that are not in game. -If- the mentor is ingame, they probably would have also seen the mhelp, and can just answer it them self. I'd likely only use it for chit-chatting, which is nice, but, not needed, and just takes up more room. So again, either way works for me.

**Pull request closed without merging**
