### PR TITLE
Instruction for how to right a vending machine

### PR DESCRIPTION
**Pull request by togglejoy**
## What Does This PR Do

Adds instruction to the description of a tipped over vending machine about the need to alt+click to right it

## Why It's Good For The Game

New players will get less frustrated trying to figure out how to fix the vending machines

## Changelog
:cl:
tweak: Description of tipped vending machine now tells you how to put it up again (alt+click)
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
please add a changelog for this PR

**Comment by togglejoy** [comment]
added!

**Review by lewcc — COMMENTED** [review]
I think this looks good. There are a few other interactions that lead to an alert like "You'll need to right it first!", and examining the machine tells you to alt-click it, but trying to use the vending machine with an open hand is the most likely interaction, so I like this change.

I think in the same spirit of improving this messaging, you could remove the `if(Adjacent)` check on the `Examine()` proc as well?
```dm
/obj/machinery/economy/vending/examine(mob/user)
	. = ..()
	if(tilted)
		. += "<span class='warning'>It's been tipped over and won't be usable unless it's righted.</span>"
		if(Adjacent(user))   // this line
			. += "<span class='notice'>You can <b>Alt-Click</b> it to right it.</span>"
```

**Review by Sirryan2002 — APPROVED** [review]

**Comment by togglejoy** [comment]
Oh I didn't see there was already an instruction there too! Removed the `isAdjacent` check on it, yep.

**Pull request merged**
