### PR TITLE
Vulp/Taj Chocolate and Darksight

### PR DESCRIPTION
**Pull request by Coolrune206**
## What Does This PR Do

Gives both Vulpkanins and Tajarans a chocolate weakness in exchange for increasing their darksight by one (from 3 to 4).
## Why It's Good For The Game

It was mentioned on the PR that initially brought their darksight down from the very high value it had that adding a chocolate weakness might be a good reason to slightly raise the darksight again. I don't play either Vulp or Taj but some of the players who do would like this from what I've heard so hey, why not - it's an easy change.
Might be worth increasing the damage this does or making it do heart damage, as it's not very much at the moment. Will have to have one of the balance nerds let me know.
## Images of changes

image
image
image
## Testing

Oh I had fun with this one, as you can see.
## Changelog
:cl:
tweak: Vulpkanins and Tajarans can see a little further in the dark
tweak: Vulpkanins and Tajarans now suffer toxin damage from eating chocolate
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
Do note, that they will also gain more eye damage from flashes due to the +1 to Darksight.

**Comment by Pennwick** [comment]
For consistency this should include raw cocoa and hot chocolate.

**Comment by SpringSkipper** [comment]
I think it'd be funny if it also changed the flavor messages for them to say that chocolate is the best thing they've ever tasted.

As far as more detailed symptoms that would be easy to replicate in ss13, symptoms of chocolate consumption in dogs are vomiting, increased heart rate, tremors, seizures, and heart failure. Maybe have it be based off of amount consumed, with heavy overconsumption leading to heart attack?

Just quietly taking some toxin damage sounds kinda... boring.

**Comment by CinnamonSnowball** [comment]
The "heavy" overconsumption would have to be *really* heavy to justify an entire heart attack, imo
Other than that, I second that if this is to be added, adding some fun jittering and/or seizure-like attacks (the latter perhaps gated behind a longer time of exposure, see the `current_cycle` var) would indeed be a neat way to spice up the otherwise boring toxin damage

**Comment by Tortoise-Dakota** [comment]
Not sure if you want to add it in this PR or another, but it seems that vulps (and probably taj) have lost their glow-in-the-dark eyes (not the NV) so now they just have regular, non-glowing, eyes.

**Comment by CinnamonSnowball** [comment]
The eye glow/shine is dependent on the level of darkness vision the eyes grant, 6, to be precise
Raising the darkness vision that high is probably a nono, and lowering the threshold enough to catch Vulp/Taj with darkvision of 4 would also give the glowy eyes effect to Nian, Greys, and Drask

**Comment by Bm0n** [comment]
I would include organ damage, 2 tox per tick or whatever is very little

**Review by S34NW — APPROVED** [review]
good to go once merge conflict addressed

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
