### PR TITLE
Kidan Antennae + Greyscaled & Darkened Skrell

### PR DESCRIPTION
**Pull request by KasparoVy**
Kidan sprites courtesy of @TravellingMerchant 
Blue Skrell flesh courtesy of @Puckaboo2 

:cl:
rscadd: Skrell have been greyscaled and darkened. You can now colour your Skrell characters as you please.
rscadd: Kidan can now select from multiple different antennae head-accessory styles.
tweak: Kidan male/female bodies now have differences, namely mandible/torso structure.
tweak: Skrell flesh is now blue (like their blood), though you'll only ever see this under certain circumstances if they're dismembered.
/:cl:

Aside from the above, admin-spawned Unathi mobs now have their horns as head accessories instead of hairstyles (can't be shaved off) and they now have a charcoal grey colour instead of pitch black.

_Skrell. As dark as you can get, and with the default colour (for adminspawned mobs, don't worry the rgb values are in a code comment. No sprite changes were made aside from the flesh colour and the darkening_
skrellcolouring

_Kidan._
kidanmenu
kidancompare
kidanantennae

_Unathi (this'll only ever be noticed by admins who spawn in Unathi mobs)._
lizzergreyhorns

### CODE REVIEW

**Comment by Aurorablade** [comment]
Taj claws plz

**Comment by Aurorablade** [comment]
And unathi claws

**Comment by TravellingMerchant** [comment]
Huh what's with the weird bridge across the kidans face? I didn't do that?

**Comment by KasparoVy** [comment]
Forgot to turn off glasses, woops. I turned one of the characters from an existing slot into Kidan and forgot to make that change. Updated the picture.

**Comment by Puckaboo2** [comment]
One side of the butt isn't even colored in. How is this considered quality spriting?

**Comment by taukausanake** [comment]
@Puckaboo2 It's like two pixels missing from the right ass cheek. And it actually makes a difference. Wow

**Comment by Puckaboo2** [comment]
Did you know Unathi tails clip into clothing, too? And the female Tajaran muzzle is missing an outline the male clearly has? A lot of these sprites have problems which have been addressed in the previous PR, yet, some bogus sprite expert said these sprites don't need anything done to them.

I call bullshit.

**Comment by Aurorablade** [comment]
Kasp I don't think adding a claws option would get the pr denied if anything make it a separate or.. Please please?😖

**Comment by Aurorablade** [comment]
Separate or rather

**Comment by Fox-McCloud** [comment]
@KasparoVy have a full body picture of a Kidan before this resprite?

**Comment by TravellingMerchant** [comment]
@Fox-McCloud He doesn't, but I do. https://puu.sh/nIgAK.png

I only changed the head markings to have a very slightly difference in markings between male and female. Main difference is the slightly larger mandibles on the male. The males chest is of course modified to accommodate that.

**Comment by KasparoVy** [comment]
Sorry, didn't notice the comment. Thanks for posting the picture

**Pull request merged**
