### PR TITLE
Enable emojis for asay and msay 🎉

### PR DESCRIPTION
**Pull request by Tayyyyyyy**

### CODE REVIEW

**Comment by Regen1** [comment]
This is it

I can't wait to 👌 😂 👍 💯 in asay while we :dab: on them :griefers: 😬 😂 😂 👀 🍆

**Comment by Tayyyyyyy** [comment]
Cue "👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit"

**Comment by Spartan6** [comment]
Enable Emoji’s in IC 😂👌

**Comment by Spacemanspark** [comment]
Stop no

**Comment by KasparoVy** [comment]
Do it, it is the final step in our evolution.

**Comment by Birdtalon** [comment]
This PR gave me cancer.

**Comment by FreeStylaLT** [comment]
🎩__

( 👁 👃 👁) DO I LOOK

(__👄_)     S  E  X  Y  ?

💪|👁 👁) 👍

|  . )

( 👄

|| ||

👠 👠

**Comment by FreeStylaLT** [comment]
Boss 🕴️ makes 🔨 a 💰 dollar 🤑, I ☝️make a 🤷 dime. That's ⬅️ why 🤷‍♂️ I 🚽 poop 💩 on company 👨‍💼 time 🕗

**Comment by Dumbdumn5** [comment]
:+1: s for the :+1: God!

**Comment by tigercat2000** [comment]
😂 😂 😂 😂 😂 😂 😂 😂

**Pull request merged**
