### PR TITLE
Rad collectors sprite update - streaks of light

### PR DESCRIPTION
**Pull request by DogsParadise**
This is 1 of the two versions, I will PR for the rad collector, opinions seem to differ too much.
This is the PR with streaks of reflection on the glass

Link to other PR: #15822 

**Alternative PR to #15665**

## What Does This PR Do
It changes the rad collector to the new perspective and updates the look to fit the new TG style more.

## Why It's Good For The Game
Current sprite isn't in the correct perspective and just generally outdated.
Sprite that might get merged from TG, looks weird and off.
TG themselves don't think it's a great sprite either, from what I have heard on their discord.

## Images of changes

New:
image

New animated + lights added:
https://gyazo.com/4cfe11acc606d6f0a7201e1a8d54b5ad

Old:
image

TG:
image

## Changelog
:cl:
tweak: Changes radiation collector sprite
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
I like these MUCH better than the TG ones

**Comment by BakKeener** [comment]
I noticed in the new sprites the red light isn't on like the TG ones, I think they should get updated to be on when they're not in use or get rid of them entirely in favor of only having a green light that is either on or off.

**Comment by AffectedArc07** [comment]
These fit the look of plasma much better since plasma is a purple-not-pink palette when in windows, and in gaseous form.

**Comment by DogsParadise** [comment]
> I noticed in the new sprites the red light isn't on like the TG ones, I think they should get updated to be on when they're not in use or get rid of them entirely in favor of only having a green light that is either on or off.
> I also like the new sprites much better than the TG ones.

Adjusting the sprite to add the red light when it's off.
Will be applied in the other PR first, then coming back to this PR.

**Comment by DogsParadise** [comment]
Animation + lights added
https://gyazo.com/4cfe11acc606d6f0a7201e1a8d54b5ad

**Review by dearmochi — APPROVED** [review]

**Comment by DogsParadise** [comment]
General opinion seems to favor the non-streaks of light version of the sprite.
For the sake of simplicity I am closing this one.

If this is the prefered merge which I deem unlikely by the heads, they can just re-open if need be.

CLOSED!

**Pull request closed without merging**
