### PR TITLE
Small Cash Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
We currently have VG's cash system...and while, IMO, it's not the best, overhauling everything at this stage is a bit more work than I'd like to take on, so, for now, I'm just updating a couple of things:

- Adds in the ability to stack cash
 - If you click on a turf, table, or stack of space cash that is the same type as yours, it'll stack the bills together--again, only like with like (10's stack with 10's, but not 100's).
 - Makes tracking a bunch of cash at once much easier.

Para Changes
- Ensures all base chip types are in the money types list
- Removes the VG cash sprites and overlays for stacked cash
 - These sprites are horrendous, in my opinion, and the overlay for stacks really isn't necessary, IMO; besides you need over 25 chips in the same stack before they even show up.

I just utilized the old, far more readable cash sprites (and about 10x easier to click on):

money

### CODE REVIEW

**Comment by Spacemanspark** [comment]
I dunno, I prefer the current sprites.
Other than that, :+1:

**Comment by FalseIncarnate** [comment]
Don't care about the sprites as much, but fixing up the code to be more mechanically usable is nice!

Now if only we could make the credit chips ACTUALLY useful...

**Comment by Fox-McCloud** [comment]
ideally, we should probably port over Bay's cash system; it's pretty close to Goon's system, only more usable for vending machines and such---it has fully stackable cash that's completely liquid.

**Comment by Plotron** [comment]
I'm in the same boat as FalseIncarnate. The old sprites aren't exciting, neither are the sprites proposed in this PR. I couldn't care less if the sprites were changed.

**Pull request merged**
