### PR TITLE
Ticket take now asks for a confirmation if it's already assigned + ticket/PM code refactor

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
The take for tickets now asks for confirmation if you want to take it when somebody else already has it assigned to his name.
Default here is No so a simple enter will make the window go away and nothing bad will happen.
Refactored some code and added the 'pmsend' css class.

**Changelog:**
:cl:
tweak: Ticket takes now ask for confirmation if you want to take an already assigned ticket.
/:cl:

### CODE REVIEW

**Comment by TheSardele** [comment]
So we will no longer need to duke it out in the thunderdome every time more than 1 mentor takes a ticket?
I guess we can still do that if somebody answers without taking the ticket in the first place.

**Comment by farie82** [comment]
Yeah now it's just for that. Saves some time for actual playing the game.

**Comment by CornMyCob** [comment]
Thank you

**Comment by SteelSlayer** [comment]
Thank you farie, very cool :+1:

**Comment by dovydas12345** [comment]
Ah, yes beautiful.

**Comment by farie82** [comment]
If somebody else wants to take on the PR feel free.

**Pull request merged**
