### PR TITLE
Cryo will now show occupant inside on sprite. (Bayport)

### PR DESCRIPTION
**Pull request by tigercat2000**
Ports Baystation12/Baystation12#8459.

outdated image:
shamelessly copied image

~~Better sprites to be ported/created later, if ever made/bothered with..~~
Covered in second commit, new sprites and animations (kinda)
outdated image:
fancy!
basically just makes the pods full, not half-filled (because that was weird and silly), also adds a little bobbing animation for mobs in the pod, so they look like they are floating in cryo liquid. 
third commit update; even betterer sprites edition
probablyfancy!

### CODE REVIEW

**Comment by Nomzosha** [comment]
ewwww icky greeen

**Comment by SamCroswell** [comment]
@tigercat2000 
Heads up -- Looks like your travis build failed.

**Comment by fj45** [comment]
Yeah, wouldn't mind proper medical green or light blue liquid.

**Comment by Fox-McCloud** [comment]
How well does this play with opening/closing the panel on the cryo-tube? It fits *perfectly* with the current sprite.

And yeah...I'll echo what everyone else is saying; the green liquid looks really gross.

**Comment by tigercat2000** [comment]
Travis failed due to an error, closing and reopening to trigger it manually

**Comment by fj45** [comment]
Uh, I think TG was having the same issue, for whatever reason Travis is just borked.

**Comment by tigercat2000** [comment]
Alright, now that I am awake, did some work on the sprites to try and get rid of weird green liquid 
As well as, actually adding an icon-state for screwdriver, because baaaaaayyyy 
animated thing
maint opened

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Kinda hard to ugprade a piece of machinery through a tiny hole like that =p

(yes, I'm being nitpicky).

**Comment by ZomgPonies** [comment]
Once, in band camp, I upgraded machinery something something tiny hole.

**Comment by ZomgPonies** [comment]
Very very nice. Did you also port the code so it supports multiple pods? Did you manage to port it to work through NanoUI?

**Comment by tigercat2000** [comment]
This is just a port of their cryo sprites- I have some plans for porting the closed cloning PR, but later

**Comment by fj45** [comment]
Looks great.

**Pull request merged**
