### PR TITLE
Sounds

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates a few sounds

-Adds in entirely custom sounds for the defib unit when its various states are ready, when it's charging, it shocks someone, revives someone, etc.
-Updates the taser firing sound to sound more beefy and sound like an electrical blast
-Various mining drills/pickaxes now have custom dig and hitsounds

-Removes the highlander, dodgeball, and space asshole music, as there's copyright concerns for them
-Removes 1.ogg music; pretty sure this comes from something else, as well--either case, it's not used anymore.
-Removes jukeboxes and boomboxes from the map.

Perhaps, in the future, if we can locate some copyright-free music, we can re-utilize the juke/boombooxes, but for now, this is the best/safest option.

Sounds from TG.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Okay what the hell is wrong with you guys and copyright suddenly? Because one butthurt player made an off-hand comment about getting us in trouble over a couple of MP3s because he didn't get his way, suddenly we're just caving in and changing all of our policies without discussion? 

I am totally against removing ANY MP3s without a full-on admin discussion over this.

**Comment by ZomgPonies** [comment]
Added a few tags until we get clearer feedback via http://nanotrasen.se/phpBB3/viewtopic.php?f=20&t=3797

**Comment by Fox-McCloud** [comment]
I hardly see  what's controversial about protecting Paradise's long-terms interest; especially when 2 of the 3 maintainers are in agreement over removing the music. It's hardly a change of policy; it's not inherently bad we have music; it's that we have music that has a copyright on it; as the PR says, if we can get our hands on some copyright free music, the juke and boomboxes can be re-added.

It's also not that hard to replace the highlander and dodgeball events with similar music.

**Comment by ZomgPonies** [comment]
What's controversial is that it IS a policy change: You're not removing the music for design reasons, you're removing it for POLICY reasons. Policy reasons aren't yours to unilaterally decide upon, this clearly falls under 'big picture stuff'. Hence the controversial tag and the 24h minimum wait period while it's being discussed on the forums. This is the checks and balances part of the maintainer system in action.

At the end of the day, it's just music and people can listen to the same songs on Youtube if they wish. I'm more concerned that you're oblivious to the fact that this is the kind of change that requires discussion before implementation.

**Comment by ZomgPonies** [comment]
If you want to modify this PR and leave jukeboxes in until a clear decision is reached regarding them, I'll merge in the removal of the Highlander and Dodgeball music.

**Comment by Fox-McCloud** [comment]
@ZomgPonies and @Markolie 

Map change reverted for now; music files remain removed.

**Pull request merged**
