### PR TITLE
Tweaked the area for the court room separating it out on delta and meta station

### PR DESCRIPTION
**Pull request by Fluffyzack21**
## What Does This PR Do
spreads apart the court room from the gallery and added apc's, fire alarms, and air alarms

## Why It's Good For The Game
Makes more sense to have it separated apart then together and people fighting over what is a gallery and what is not on meta and delta station and since the new area added it would make sense there is now fire alarms, air alarms and APCS

## Images of changes

Screenshot 2024-06-28 130019
Screenshot 2024-06-28 125017

## Testing
I spawned in as a ghost and made sure the new area had power, fire alarms, air alarms and cameras were named right

## Changelog
:cl:
tweak: I changed the court room the area making it separate having one-part gallery and another just court room and I fixed couple of the camera names, added fire alarms, APCs and air alarm on meta and delta station
/:cl:

### CODE REVIEW

**Comment by Fordoxia** [comment]
The PR description doesn't match up with what I'm seeing on map diff - the actual physical area is the same size.

Please rewrite the description to mention the rearranging of wall-mounted objects, the door helpers, and the new area + APC.

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
Can you add autonamers to these doors?

Untitled

**Review by warriorstar-orion — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]
image

Nevermind I think you accidentally removed this access helper on the prisoner holding windoor

**Review by DGamerL — CHANGES_REQUESTED** [review]
Wrong button

**Comment by Fluffyzack21** [comment]
> image
> 
> Nevermind I think you accidentally removed this access helper on the prisoner holding windoor

fixed

**Review by warriorstar-orion — APPROVED** [review]
Thanks for fixing up those stacked wallbumps as well

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
