### PR TITLE
Split Ahelp into Ahelp and Mhelp

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Ahelp now is only ahelp instead of a choice between mhelp and ahelp.
Mhelp is now a verb in the admin tab.
Also did some refactoring because it was needed.
F1 still opens Ahelp which is now only Ahelp.

**Changelog:**
:cl:
add: Mhelp is now a verb on it's own
tweak: Ahelp is no longer a choice between Ahelp and Mhelp, now it's just Ahelp
/:cl:

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
So pressing F1 still gives you the choice between mhelp and ahelp?

**Comment by farie82** [comment]
It still opens Ahelp which is now only Ahelp. Changed the description

**Comment by AffectedArc07** [comment]
@farie82 Does this split them into seperate procs so that they can be sent to different channels over IRC/Discord?

**Comment by farie82** [comment]
@AffectedArc07 the Ahelp verb is now split into two verbs. Meaning two procs. It should be easier to do that now yeah.

**Comment by Ralta** [comment]
Can I was what the point of this is? Adding a verb for mhelp is fair enough, but I don't understand the need to remove the option from F1. It's far easier to use that than a verb, and it's a very well-known method of mhelping, I believe.

**Comment by farie82** [comment]
The removal from the F1 is due to the removal from the ahelp verb. F1 is linked to the ahelp verb. It can be changed though

**Comment by Shadeykins** [comment]
A lot of people F1 ahelp when they don't need to already. Having F1 being a straight ahelp will probably exacerbate the issue.

**Comment by variableundefined** [comment]
I echo Shadey's concern.

**Comment by Agameofscones** [comment]
If concerned about being Ahelping, just pull a CM auto-response system. If someone ahelps with an mhelp question just direct them to the proper verb. People will get the message pretty quickly and adapt. I don't see the issue here.

**Comment by Shadow-Quill** [comment]
I believe the point here is that the ahelp verb pulls up a choice between ahelp and mhelp, instead of having a separate verb just for mhelp. This PR is adding that mhelp verb while removing the choice from ahelp

**Comment by Aurorablade** [comment]
yeah really not a point on this.

**Comment by MrMagolor** [comment]
It would be nice if mhelp had its own hotkey then, like the F3 that it has on goon.

**Comment by Allfd** [comment]
This will make things worse.  People already overuse ahelp when they should be using mhelp.

**Comment by taukausanake** [comment]
Can you make F1 bring up the old selection for ahelp and mhelp and then call the correct proc depending on the choice? That might be better. That or just remove the F1 key completely

**Pull request closed without merging**
