### PR TITLE
Robotics Sterile Surgery

### PR DESCRIPTION
**Pull request by Fox-McCloud**
A redo of a PR originally created by @Crazylemon64 

Now that robotics has augments, this makes way more sense. I'm also seeing, in game, that the vast vast bulk of augmentations requested are done so by the roboticists and not medical (unless the roboticist doesn't know surgery or it's the roboticist himself that wants it done). This also helps better fulfill the title of "Biomechanical Engineer"

- Robotics now has a 'sterile' surgery area, complete with gloves, cleaner, sink, and a few of the tools they were missing---in addition to anesthetic, for those who are more RP inclined when getting augments. 
 - Not really worried about "balance" implications of this as they had access to all of these tools, as is, and all the roboticists I'm seeing, in game, are utilizing screwdrivers in place of bone gel.
- Adds the bone gel and fixovein to the autolathe. 
- Ensures all surgical tools have origin tech on them--lowers origin tech on FixOVein

Pics:

img

:cl: Fox McCloud
add: Robotics now has a "sterile" surgical area for performing augmentations
add: Adds the FixOVein and Bone Gel to the autolathe
tweak: ensures all surgical tools have origin tech on them; lowers origin tech on FixoVein
/:cl:

### CODE REVIEW

**Comment by ProperPants** [comment]
@Fox-McCloud What exactly is the purpose of giving the surgical tools tech origin?

Additionally, I have a minor request to give the Robotics lab a little more walking space. Remove the wall to the right of the surgery computer. In its place, put the table with the MMIs and posibrain, including the single window to its right. Leave the sink where it is. This way, the two windows are effectively lowered by one tile, giving the room one tile row of walking space. The light switch could be moved to a wall along the right side of the room - I'm not sure where because I can't see it in the image.

The one tile this would free up really goes a long way, and the Roboticist performing surgery would still have to walk one tile right to access the table, so distance is unchanged.

**Comment by Fox-McCloud** [comment]
>What exactly is the purpose of giving the surgical tools tech origin? It doesn't really seem to matter either way.

Because, generally speaking, most of the surgical tools have an origin tech on them. The reason the bone gel was lowered was so that R&D can't just print off 3 of them at round start and instantly hint biotech 4, straight away.

**Comment by TullyBurnalot** [comment]
As much as it may surprise some people, I'll :+1: this. I'll even change my Implant SOP to match it.

My only concern with initially setting SOP so that "Surgeons > Roboticists" in Implantation Surgery was purely what this PR is fixing: sterilization (because no one likes infected brains). With that problem gone, I have absolutely no issue with Robotics performing the Implantations themselves. In a practical sense, this'll allow ease of access, as it's far easier to just walk up to Robotics and ask for an Implant, then get it there.

Also, Bone Gel and Fix-O-Vein in Autolathes? Fucking yes, please. Makes it far easier to get surgical tools replaced if they get stolen/destroyed.

**Comment by monster860** [comment]
Yeah, :+1: I've personally mixed my own anasthetics for Robotics to use before.

**Comment by pipextiny1** [comment]
A SINK! 
WE HAVE A WINNER!   :+1:

**Pull request merged**
