### PR TITLE
Grey Engineer hardsuit

### PR DESCRIPTION
**Pull request by Jovaniph**
This PR finally gives Greys an Engineer hard suit.

southnorthwesteast

south1west1east1

:cl: Jovaniph
rscadd: Adds Grey Engineering Hardsuit
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
The visor would use a bit more shading, but the rest seems alright.

**Comment by SamHPurp** [comment]
Look good to me. Agree on the shading comment from @FlattestGuitar

**Comment by Jovaniph** [comment]
I can definitely improve on it later or someone else can. Its what I got for now =D

**Comment by Fox-McCloud** [comment]
Going to need a bit of work; it's flat and stands out like a sore thumb, because of it, compared to the other hardsuits.

**Comment by Spartan6** [comment]
The chest and back are fine, the helmet just needs some more colour fluff.

**Comment by Jovaniph** [comment]
Thank you guys for the feedback...making the changes now.

**Comment by Jovaniph** [comment]
No additional feedback (from admins or maintainers) and PR been open far too long than it should have. Closing it since I got other projects I could be working on.

**Pull request closed without merging**
