### PR TITLE
Adds the Security Laser Rifle

### PR DESCRIPTION
**Pull request by Coolrune206**
## What Does This PR Do

Adds a new firearm designed to be a spot inbetween laser guns and the WT-550 in terms of function and escalation, the Security Laser Rifle. The SLR functions similarly to the ERT Ik-60 Laser Carbine in that it is a laser weapon with a magazine, but it is significantly weaker to match existing crew weapon options. It has the same ammo capacity (putting it in-line with the WT-550), but fires a single shot as opposed to the Carbine's two-burst.
The SLR is ordered from cargo in crates that are priced similarly to the current laser gun crates, but with 2 SLRs per crate instead of 3 laser guns. The ammo is able to be ordered from cargo in boxes of 4 ammo mags that cost 300 credits, or printed at RnD for 4000 metal and 600 plasma at Combat and Powerstorage 4.
Also the item is bulky to make it similar to the SAR. Fits in your armor slot and in belts.
Oh, one last thing, for real this time. The sprites are heavily based off the IK-60 laser carbine, with the in-hands being directly taken from it. I'm not a proper spriter, but I did my best. I can just claim this is the IK-60's ancestor, and have thus called it the IK-30.
## Why It's Good For The Game

The WT-550 is a common escalation used by security in regards to threats that a single clip cannot solve, or that use EMPs regularly (changelings my beloathed), yet this is quite the sharp jump in actual escalation because the WT also applies brute damage which is very strong. This Laser Rifle should act as a middle ground between conventional rechargable security weapons and the WT-550, and shouldn't just replace laser guns or energy guns because of the fact that it needs ammunition instead of an easy recharger.
Plus, it's a cool gun, I like it :)
## Images of changes

https://user-images.githubusercontent.com/71326864/223931966-18cdee09-8994-4b10-89e2-94692a9c8918.mp4

<br>

image

image

## Testing

See above.
## Changelog
:cl:
add: Added the Security Laser Rifle and its ammo, orderable from Cargo
tweak: Encased Laser Rounds are now caseless, you're welcome Janitors
/:cl:

### CODE REVIEW

**Comment by meow20** [comment]
Really cool idea, antags won't salt about those so much (they always do) unlike Wt's cuz no broken bones and ib's.

**Comment by Rurik123** [comment]
fuck yeah

**Comment by Samman166** [comment]
Hey that's my idea!

Lol I'm sure I'm not the only one to of had the idea. Few things though.

There isn't much of a reason to use this gun as a WT has better mag size, better damage type, and cheaper ammo. I don't think this is an issue with your PR but rather an indicator the WT is too strong.

I'd suggest making the magazines normal sized items so you can't cram a load of them into a single box, but make sure the magazines can be crammed into an assault belt, giving people a reason to actually want to use the assault belt.

If you wanna, you could make it so it does fire 2 shots but make the projectiles deal 10 damage(would want to double the mag capacity) it'd make it a bit harder to dodge both projectiles so you have a higher chance of one of the shots landing. Not a balance concern, I just think this could make the gun a bit more unique.

Still super glad someone else is getting on the buff lasers train with me.

**Comment by Coolrune206** [comment]
> I'd suggest making the magazines normal sized items so you can't cram a load of them into a single box, but make sure the magazines can be crammed into an assault belt, giving people a reason to actually want to use the assault belt.

The magazines are specifically designed with the intent of being small, hence the small sprite and small clip. I understand the reasoning behind making them larger but as is, if I did so it'd just be another reason the WT is better.

> If you wanna, you could make it so it does fire 2 shots but make the projectiles deal 10 damage(would want to double the mag capacity) it'd make it a bit harder to dodge both projectiles so you have a higher chance of one of the shots landing. Not a balance concern, I just think this could make the gun a bit more unique.

I had this concept initially and mentioned it to Matt when hashing out the details with him, he seemed to think multi-projectiles would be a bit much.

**Comment by Probablyjay19** [comment]
Looks good! My only complaint (and this is just me, feel free to ignore) is that the sprite kinda looks a bit wonky with the unsupported reversed magazine. Maybe add a magwell connected to the grip similar to something to the Kriss Vector?

image

**Comment by procdrone** [comment]
Maybe the mags could be compatible with ERT laser rifles too?  sec ERT always have to change weapons after their initial ammunition is spent so this would be a nice way for them to keep using the same rifle, albeit with slightly worse ammo.

**Comment by Coolrune206** [comment]
> Maybe the mags could be compatible with ERT laser rifles too? sec ERT always have to change weapons after their initial ammunition is spent so this would be a nice way for them to keep using the same rifle, albeit with slightly worse ammo.

As mentioned in coding chat, this would be a bit difficult to do because of the way guncode works unfortunately. If I ever bump the ammo count of this gun up to twenty, I'd definitely just use the ERT magazine, so it'd be compatible then.

**Comment by Coolrune206** [comment]
After a chat with Hal, and some feedback from folks, I'm upping the mag-size to 20 to put it in-line with the WT (the brute equivalent) so this has a purpose, and removing the glass from the RnD cost. This does mean the ammo type has been flattened into the same type as the ERT carbine, so they'll be interchangeable. RIP the small mag sprites :pensive:

**Comment by Peakwastaken** [comment]
Minor nitpick about the sprite : would like the light running on its side to be red rather than blue as the latter is usually associated with pulse weaponry.

I really like that it gives ERT the opportunity to get reloads on station too

**Comment by matttheficus** [comment]
Reloadable ERT Carbines are now horrifying.

**Comment by Coolrune206** [comment]
> Reloadable ERT Carbines are now horrifying. Would unironically like the small mags/just a different mag for the Carbine vs Rifle.

Gotten some differing opinions from the balance team/general playerbase on this one, but the reaction seems to be generally approval for ERT reloading so I think I'm going to keep it as-is for now.

Unrelated, I've gone ahead and made these caseless in the next commit, a change which is echoed onto the ERT Carbine. Because, to be honest, these things were making too many casings.

**Review by hal9000PR — APPROVED** [review]

**Comment by Coolrune206** [comment]
image

**Pull request merged**
