### PR TITLE
Tesla Gun Implementation and Small R&D Change

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Re-upload of : https://github.com/ParadiseSS13/Paradise/pull/4323

24 hours already passed on it.

Partial port of: https://github.com/tgstation/-tg-station/pull/16974 by @KorPhaeron 

Implements the Tesla Revolver, a replacement to the shock revolver.

This is a high-risk lethal weapon that deal damage and stuns---only it has a very high chance of recoiling back to the user and shocking them, as well.

Other
- Removes SMG and ammo from R&D

Overall goals: 
- Add diversity in R&D for the weapons they produce instead of having weapons that are nearly copy-pastes of existing weapons or that don't do anything interesting.
- Give cargo the niche of ballistic weapons and R&D the niche of experimental/odd weapons.

:cl: Fox McCloud
add: Adds in the Shock Revolver, a replacement for the stun revolver
remove: removes the stun revolver
remove: removes the prototype SMG+ammo from the protolathe
/:cl:

### CODE REVIEW

**Comment by Kevak** [comment]
I'd say keep the SMG/Stun Revolver in the proto. SMG is very niche and isn't really possible to get elsewhere. Revolver is in regular high demand by security.

**Comment by Regen1** [comment]
Science should keep the toxin and incendiary magazines, they're "experimental" in my eyes

**Comment by Fox-McCloud** [comment]
>Science should keep the toxin and incendiary magazines, they're "experimental" in my eyes

The experimental WT mags are still in, but the guns themselves (like all other ballistics) are in cargo.

**Comment by Regen1** [comment]
No they're not

https://github.com/ParadiseSS13/Paradise/pull/4352/files#diff-3308b30e46e7904c15a9cd7911bd81baL156

**Comment by TheDZD** [comment]
@Regen1 Leaving the SMG ammo in seems a bit pointless, since there'll be no way to get said SMGs. Experimental ammo for the WT (a cargo-orderable ballistic weapon) are still available in the protolathe.

**Comment by Regen1** [comment]
Wait, I figured he added the SMG to cargo as well, my bad

**Pull request merged**
