### PR TITLE
Removes the 20 second stun from tourettes

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do

Removes the 20 second stun from the tourettes disability. Yeah, you heard that right. Tourettes has a **20 second HARD STUN** that freezes you in place without warning, and with little to no indication to yourself or others that it's happening. I saw a pr from goof on /tg/ a while ago that did this (https://github.com/tgstation/tgstation/pull/64416), and I've been thinking about it ever since. I think he put it more eloquently than I can:

> Removes the fucking 20 second stunlock rng from tourettes because it's fucking stupid and I just had the most agonizing thirty fucking minutes of my goddamn life, holy shit, I hate this fucking mutation so goddamn much, who the fuck thought 20 second hard stun was a genius idea for a random mutation, especially the fact it gives absolutely zero indication that it's from the tourettes because the stun has no message attached

## Why It's Good For The Game

This isn't even related to the stun project, it's just a terrible symptom from a genetic mutation that's been around for ages. The fact that it makes you swear loudly is enough, I don't understand why a 20 second stun with no indication to its source would ever have been justified. 

Again, to quote goof:
> Oh my fucking god I hate this
> Twenty fucking seconds of stunlocking
> 20 fucking whole seconds
> This can end up being a solid fucking minute in laggy situations
> This is fucking stupid
> Fuck this symptom holy shit

## Changelog
:cl:
tweak: Tourettes no longer stuns you for a full 20 seconds at random
/:cl:

### CODE REVIEW

**Comment by Inadvizable** [comment]
Torn on this. Great PR but I also like when geneticists suffer.

**Comment by Carthusia** [comment]
This...explains why a buddy of mine could never get nommed by a vampire ages ago, the vampire would grab him at my maint bar, try to bite him and he would torrettes spazm out and he'd get ungrabbed, it happened so many times the vampire just said he wasnt worth the trouble and let him go

**Comment by Contrabang** [comment]
I like this but how will this affect cluwnes? Is this a cluwne buff? /s

**Comment by GDNgit** [comment]
Reminder to remove `instability = -GENE_INSTABILITY_MODERATE` from Tourettes as its cosmetic now

**Pull request merged**
