### PR TITLE
Station Utility Rerouting [Ready for Review/Merge]

### PR DESCRIPTION
**Pull request by IK3I**
The on board utilities of the station seem to be routed fairly randomly much to the dismay of engineers and would be ventcrawlers, crew and otherwise. 

This PR aims to fix that by remapping each utility to fit a recognizable pattern using the following steps:
### Atmos
1. Pipe a loop around maint
2. Pipe a loop around the primary station hallway
3. Enter each department from two opposite sides
4. Run one pipe through the main hallway of the department
5. Branch pipes off main line into nearby rooms
6. Branch into equipment in rooms
7. Establish Bypass opportunities where available

### Disposals
1. Make a small central Loop
2. Branch off main loop to each subsection
3. Branch further to final mail destinations
4. Insert passive junctions for pure trash chutes

### Power
1. Follow pipes where possible
2. Branch off maint lines into departments
3. Run down main halls of departments
4. Branch to APCs
5. Branch to powered devices and grilles
6. Ensure all subnets are colored yellow

## **To Do**
* ~~Scrubbers~~
* ~~Supply~~
* ~~Disposals~~
* ~~Power~~
* ~~Cleaning~~

The end result is that it's almost navigable!

### Atmos
Atmos Preview
### Disposals
Disposals Preview
### Power
Power Preview
  
:cl:
tweak: Cyberiad utilities rerouted
tweak: Cyberiad power subnets recolored yellow
tweak: Disposals sorting pipes can route to multiple addresses
fix: Metastation disposals actually ship to all addresses now
/:cl:

### CODE REVIEW

**Comment by Allfd** [comment]
If you can, at some point I would like to build something like Bay's electric substations.

**Comment by SamHPurp** [comment]
@Allfd thats the sort of thing that requires its own massive project, entirely separate to this really.

**Comment by Allfd** [comment]
I am aware, but as long as things are being rerouted, having the space on the map helps.

**Comment by taukausanake** [comment]
Please don't substations. I understand the reason for them, but that's the whole purpose of APCs. Also, won't that kind of block out powersinks?

**Comment by Fox-McCloud** [comment]
>Please don't substations. I understand the reason for them, but that's the whole purpose of APCs. Also, won't that kind of block out powersinks?

I believe they do, yes, because the departments are actually on different networks; powersink functionality doens't extend beyond a network.

**Comment by Kyep** [comment]
<3

Many of the layouts for pipes/etc make no sense.

Making them more logical, as this PR does, is great. 👍

**Comment by Allfd** [comment]
On Bay the substations are offline initially and have to be configured.  The subnets would be vulnerable, and Syndicate software could be used to infect the computers controlling the network to give traitors access.

**Comment by taukausanake** [comment]
So half of the posted image still doesn't make a ton of sense. Is there a reason that most of the main lines aren't going through the hallways? I guess first answer would be maintenance halls but then you realize our maint halls are _really ugly_. They barely go anywhere except to hidey holes and possible loot you most likely shouldn't have. It just looks like some of the lines go way out of the way in some cases. I understand the implications of traffic if pipe upkeep was a thing; don't want to work in the middle of a hall, but it would make knowing where each pipe went a lot better.

RIP that one pipe line in the Southeast corner of Science. Now that small windowed hallway is empty.

Was there always that yellow pipe from the turbine to the AI satellite?

**Comment by Vivalas** [comment]
Darn, that means I need to make another pipe map then.

**Comment by IK3I** [comment]
@taukausanake Could you be more specific as to the pipes you see problems with. I routed the pipes with an inner an outer loop explicitly so that bypassing could be done in the event of say Cargo exploding.

Also, maint halls are supposed to be cramped an ugly, they're for utilities and emergency travel but this PR really has nothing to do with them.

Oh, and yes, the AI has always had mixed air feeding it's sat's atmos. Why it does this is a bit confusing however as it is literally the same pipe that powers the turbine.

**Comment by taukausanake** [comment]
@IK3I I followed the lines a bit more and I noticed that they kind of go in a spiral around the station. You got Medbay and Science in a closed loop together and security has a loop about it too but then after that it's almost a straight path to anywhere else on the station. After Science it goes into NE maint through Espace and touches on all the department rooms there, through the Dorm and then goes through the gameroom before splitting off into Security and then a few more lines into the Dorm. After Security it continues towards Arrivals, goes through Cargonia, then splits into Engineering and the center of the station. The center line hits all of Command and then branches off left to hit the rooms the line from before skipped. If I had to guess, the farthest point from Atmos is the Arrivals bathroom.

There are only three loops here and they are internal to three departments. You could have run pipes other ways that still have maintenance halls. Most notable is right next to Atmos Control Room. How dare Engineering be one of the last to get the air they control.

You just need more lines connecting together. Personally I might have stuck to the main halls, keep a branching pipeline to everywhere, but that just might be me being biased to pipe crawling.

Off the subject of me berating your piping skills, no love for the Incinerator? You gave the Turbine a line. And maybe give the rooms in Science between the main hall and Testlab/Xenobio and Toxins some vents? Also no vents for Perma cells? Those might not be important though

**Comment by IK3I** [comment]
So it is probably worth mentioning that you can reverse the direction of the atmos loop while in atmos. as the loop is closed around a t-valve in atmos that controls direction. As for the scrubbers themselves, I'm only hitting existing ones right now, but feel free to request new locations. If you have a good reason for it, I'll add it in.

As for using more lines, the short answer is no.
The long answer is the system is already departmentalized and you can easily link together new or existing bypass pipes should something break. Adding additional lines increases complexity and makes navigation and repairs more difficult. 
* Medbay and Research have so many pipes simply because they are bordering eachother.
* Cargo has no space around it to construct bypasses since it is on the exterior wall. Therefore, bypass opportunities exist through the central lines and arrivals/engineering maints.
* Engineering itself is directly connected to atmos so you can just flip the valve if air is in critical need there. 
* Sec has pipes entering near the atmos isolation closet and additional pipes in maints bypassing it
* The bridge and central halls are on their own loop so they can act as a central bypass for any trouble spots on station
* As it stands, there are not in fact any closed loops on the station, all bypass loops are terminated with endcaps to prevent byond doing its thing.

**Comment by taukausanake** [comment]
Well that explains all the weird breaks I saw in the pipes. Thought that was just me or the map being weird. Still can't stand how it looks but that's just me I guess

**Comment by Shadeykins** [comment]
Digital T-Valve connection in atmospherics ideally should be a 3-way manifold. As it stands it serves no purpose other than to arbitrarily gate scrubbed gas if you happen to have a line rupture on either end.

@taukausanake The incinerator has never had any vents or scrubbers, likely to prevent it from becoming another part of the "meta" from vent crawlers. But yeah, it has never had distro/scrubbers connections.

**Comment by IK3I** [comment]
There's a couple fixes I noticed after Pushing that are already fixed on my local version and the preview. I also need to run over atmos proper and make sure everything is still connected to the control computers.

This is probably the final version of atmos unless something serious has to be changed. In the meantime, disposals will probably be faster than atmos depending on how complex the mail routers are to manage.

**Comment by IK3I** [comment]
Disposals are improved and mapped out with the new capabilities in full use.

Noticed some scrubbers start in the off position so I'll have to make a pass on those later.

**Comment by SamHPurp** [comment]
Whatever you're doing with disposals code, make sure you aren't hardcoding something that isn't going to work for Metastation ~~or Delta station~~

**Comment by IK3I** [comment]
There's nothing hardcoded outside of the define list in _globalvars. All the modifications are allowing two way traffic through junctions to create trees instead of loops. Additionally, bit masks are used instead of single tag sorting. All the junctions in the primary loop make use of this so only a few branches are needed. And yes, I have mailed to every destination on the list to verify it works.

I also noticed I forgot to pipe to the blueshield and Rep office, but those are just simple junctions so I'll add those when cleaning.

**Comment by IK3I** [comment]
I've got powernets done, but I need to run the mapping tools over them to verify everything is connected correctly. From there, it's just correcting some issues that were missed, then going over the cl and git issues list.

**Comment by Calecute** [comment]
You're removing mix to AI Sat? Shame, always wanted to use that. But to be fair I never really understood it's functions. It could be something like a kill switch for the AI, but you need to turn on a pump in AI Sat atmospherics, with a turret shooting you, for it to work. The AI can just turn it off, and if you're breaking into AI Sat you could just use a more direct method. Never seem it used also.

About the changes, I think there was probably a reason xeno and sci chem where not conected to the waste network, and instead were conected to the air injector outside xeno. If you're sure you want to change that remove the air injector.

Also I never understood why biohazard waste is conected to the network, shouldn't it be conected just to places that need to vent dangerous gas? Like virology?Also why virology has it's own air supply, but shares the waste with everyone else? Can't virus get into waste, go to filter, and into the supply loop that way?

**Comment by IK3I** [comment]
I noticed several of these things during my fixing stages. Routing viro to biohazard would be rather difficult due to the nature of running pipes like that. This was solved by just giving it it's own mini atmos that shouldn't need to be touched in a normal round.

As for the biohazard disposals conection. It exists so atmos has a method of venting waste gasses (plasma during a fire for instance) rather than trying to deal with an overloaded wasteloop.

As for the mix to AI sat, it's not really a feasible tool to deal with an AI for the reasons you mentioned. Diverting it off the main distro line is just a more sensible solution than trying to balance it with a pipe that's supposed to be carrying plasma based fuel. Plus the AI can still do some shenanigans with it if it has a borg on hand since it would just require moving the line back to mix and say, throwing N20 into it.

I'm just prepping the final additions to the powernet now and a few fixes, those included. I still need to fix some inactive scrubbers lying around but things just need test and review at this point

**Comment by Taaketa** [comment]
@IK3I  I'd watch out for #8513 as your PR will be affected by it.

Also you have cut of the ability for security to be isolated from the atmos supply as you've added a second link with no isolation room by the courtroom.

Also I'm pretty sure vents were removed from the permabrig and given air injectors instead? To avoid ventcrawling and scrubbers were isolated. I might be wrong

**Comment by IK3I** [comment]
In regards to isolating brig atmos. those pipes in the courtroom are actually not connected. If you zoom in, they are broken in the hallway with caps in place
As for perma, vents and scrubbers are in there in the live version and are connected to standard loops. Injectors are for gassing the people inside perma.

**Comment by TullyBurnalot** [comment]
@IK3I Just for clarification, and I understand that this is incredibly tedious to ask, but @tigercat2000  raised a concern regarding if the disposals loop was working properly; did you happen to test every disposal outlet to see if it flushed things properly, and if packages are delivered properly as well?

**Comment by IK3I** [comment]
@TullyBurnalot I did, but since I'm doing git stuff already, I can run another test to verify again since that was now several commits ago.

**Comment by SamHPurp** [comment]
@IK3I you can use the request console to print labelled boxes

**Comment by IK3I** [comment]
@SamHPurp Request consoles have delays between prints so grabbing the paper bin, laying out 24 sheets, wrapping and tagging is the fastest way to send shipments to every destination.

Anyway, every single disposal has been tested going both directions where applicable including human occupancy. There were a couple of errors that the most recent commit patched.

**Comment by RyanSmake** [comment]
There is some misconception here, for some reason people think that modular consoles need dotting, but that's in fact not true (Bridge, right cable, which seemingly goes nowhere.).

**Comment by IK3I** [comment]
that console has a power monitor on it which does require a dot. Why it has that installed when there is already one on the bridge is a question for another day.

**Comment by Calecute** [comment]
There's a power monitor on Engineering Control Room (the room with the computers fore of the eng lobby) that needs conecting to the power grid.  Also thanks for all the work.

**Comment by IK3I** [comment]
It sat to long and got new conflicts.... *scream

**Comment by Taaketa** [comment]
@IK3I The only other thing I'd point out is that you have the station split in 2 in terms of piping layout.

In atmos. What used to be the lines dedicated for filling the Air Pumps and emptying scrubbers are now just connected to the network. But that network covers, Cargo, Engineering, Arrivals access and surrounding rooms and part of the Starboard primary hallway. Not sure of the design reasons for that. But it does change the nature of how atmos works around the station. Especially for things like sabotage.

**Comment by tigercat2000** [comment]
>In atmos. What used to be the lines dedicated for filling the Air Pumps and emptying scrubbers are now just connected to the network. But that network covers, Cargo, Engineering, Arrivals access and surrounding rooms and part of the Starboard primary hallway. Not sure of the design reasons for that. But it does change the nature of how atmos works around the station. Especially for things like sabotage.

I noticed this as well, but it actually is worse than that- the two lines are connected, going through cargo, into maint, through arrivals, and back into security, they connect up in there.

**Comment by IK3I** [comment]
If you look at the current layout, https://joseph-case.github.io/SS13WebMap/Paradise/Cyberiad/index.html#l=144,108,1;z=2

They are actually connected exactly like this, including the mismatched scrubbers in atmos. Distro is fed by a volume pump, so as long as 200l/s isn't being used elsewhere, it will fill your pumps. The only change to those systems is that the connection is now obvious and upfront. 

The mismatched scrubbers, including locations actually make a lot of sense for atmos, since it needs to have the most robust defense in regards to leaks. Especially with canisters.

If you prefer changes are made, let me know, but as it stands, new and old atmos have the same interfaces with the station. Vents and Scrubbers may have been shifted or rotated, but the counts per room were all preserved.

**Comment by tigercat2000** [comment]
@IK3I Are you sure distro is connected? This is the only place I could find what appears to be a connection, but I think it's actually just a pipe-crossing, not a 4 way

**Comment by IK3I** [comment]
welp, back to the drawing board again. I just checked and they do indeed just cross over pipes. I'll figure out a relatively clean way to take care of this and throw up a new commit shortly.

**Comment by IK3I** [comment]
And yes, those pipes are hidden under the floor.

**Comment by FreeStylaLT** [comment]
ey you melted the snow

**Comment by IK3I** [comment]
It was in an already conflicting tile, so I just cleaned it up along with the other messy shenanigans from a both merge.

**Comment by EldritchSigma** [comment]
Fine work, skeleton. This looks amazing

**Comment by IK3I** [comment]
@tigercat2000 AHHHHH! PAGE THREE!

**Comment by IK3I** [comment]
@tigercat2000 

Power is easy enough, I'll get that patched up asap.

As for the atmos issues:
The two pumps are best thought of as a built in redundancy as they are both connected to their respective loops and flowing the same direction as their partners. It's functionally the same as parallel pumps. While I can remove them, they also shouldn't have large balance implications

The pipe caps are a layout of bypasses. They can be removed without affecting the primary loop so I'll take care of that as well.

As for the cargo maints pipes, that's actually the route we currently have, I'd be happy to move them but the APC is also in the tile that would be used so that should be taken into consideration as well.

**Comment by SamHPurp** [comment]
Power:

There is cable issues in the electronics tech storage

Some superfluous wiring by the back door of engineering

Why've you got yellow wires under the sec treadmills? These elsewhere are used to denote hotwired cables.

Atmos:

You've got an unattached vent in medbay surgery waiting room

Dunno why you've got a vent going into the chapel's mass driver. Have a small fan, not a vent.

**Comment by SamHPurp** [comment]
Also I remember flagging this with you before.... the ingame mapping tools are really useful for catching these errors, do ensure you're using these tools to catch these sorts of errors!

**Comment by IK3I** [comment]
Unfortunately, the in game tools only point out pipe to pipe connections in atmos, machine connections aren't noted. Also, I think the power picture might be out of date, but I'll double check those areas, they should be fixed already.

**Comment by Fox-McCloud** [comment]
A few concerns:

- The pipe layout, while more "efficient", has less interconnecting pipes. I have concerns how this is going to impact atmos and pipe crawling, in the long term; for example, if you're in central primary and want to go to science....I have to go into the central primary loop, down into engineering, up through cargo, over into sec, over through service sector, all the way over to escape, all the way back down into science.

With this layout and Xenos, the more intelligent of players are going to remove just a couple of pipes and pretty much seal off the rest of the station from the infested area.

- Getting rid of turbine mix to the AI sat means the AI can no longer use "poison satellite" at its satellite without raising extreme suspicion.

img

Keeping this functionality, if possible, would be desirable; it allows for some really clever traitor-y things.

-Powernets seem ok, on the surface; they'll still have to be re-done, *eventually*, when APCs get moved from in room to in maintenance.

**Comment by IK3I** [comment]
@Fox-McCloud 
* In regards to the first point. More intelligent players already do that, there's nowhere on the station that can't be cut off from cutting the right pair of pipes. Additionally, one can pass through the pumps in atmos allowing them to traverse the outer ring of atmos without issue. If you like, I can interconnect the central primary pipes so the scrubbers and vent feeds are on opposite sides of the loop. All that being said, it seems to me that adding complexity to a system is just a bandaid if the solution to the puzzle is harder to work out but fundamentally the same.

* If you think it really needed, I can reconnect the mix to AI, but it would rarely be usable due to the sheer amount of pumps that would need monitoring to keep it working.

* Anything short of a large fire can be handled by the scrubbers already inside with the holding tank attached, but I could route the scrubber line to space if you prefer.

* Going to need an explanation of which functionality you're referring to in that picture

**Comment by IK3I** [comment]
@Fox-McCloud still need a response to this so I can make whatever changes. I'll fix merge conflicts once I have that answer.

**Comment by Fox-McCloud** [comment]
- Care to provide pics of what you mean?
- AI Sat being kept the way it would be, will be good. It's already a bit of a "pain" to use, but I'd rather keep the option available to clever AI's who actually bother.
- Scrubber line to space would be good
- What I mean by keeping the functionality, is that all of disposals pass through that area, as does a potential backfeed to the HoP's office; it does mean that you won't have a *perfect* straightforward design anymore, but it'll be darn close if the disposal pipes are kept like above in terms of placement (and functionality).  I just feel it adds too much for potential use for it to be removed.

**Comment by Taaketa** [comment]
@IK3I Is this stale?

**Comment by Crazylemon64** [comment]
uhh. this, got neglected. oh no. it's not quite applicable anymore, is it? You don't plan on continuing this, do you, @IK3I ?

**Comment by variableundefined** [comment]
Unfortunately we'll be closing this PR as it has been stale for months. You are free to re-open this when it is ready. If this is re-opened during a feature freeze, no token will be charged.

**Pull request closed without merging**
