### PR TITLE
Resprites Stools, Office Chairs, and Barber Chairs - I fucking hate your soul and I DO want to kill it

### PR DESCRIPTION
**Pull request by Alecksohs**
## What Does This PR Do

Reshades Stools, Resprites Office Chairs, and Resprites Barber Chairs.

## Why It's Good For The Game

Better sprites. In regard to the Barber Chair, Christa and I agreed that updating the sprite is enough, and the bugginess of the sprite is from the original and is not worth the time fixing at this moment.

## Images of changes

image
image
image
image
image
image
image

## Testing

Ingame testing
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>
 (is this controversial?)
## Changelog

:cl:
tweak: Resprites many chairs
/:cl:

### CODE REVIEW

**Comment by TravisAngeI** [comment]
my voice doesnt really matter in the big bubble of paradise players but i kind of prefer the old office chair sprite? i think the rounded-shape the cushions of the chair it had were really good

i dont hate the new design though, these are all pretty objectively good

**Comment by Alecksohs** [comment]
> my voice doesnt really matter in the big bubble of paradise players but i kind of prefer the old office chair sprite (not sure if youll get what i mean), i think the rounded-shape the cushions of the chair it had were really good
> 
> i dont hate the new design though, these are all pretty objectively good

While I do get what you mean, I also knew that people would prefer the original shape. The issue is that it is hard to shade the original shape due to the original sprite that people liked the shape of using soft-shading, something we don't do anymore. I struggled to find a way to get it to work for the shape, and ended up with that.

**Review by PopeDaveThe3th — APPROVED** [review]
doing the lord's work

**Comment by Christer2222** [comment]
I feel like the back cushion on the sideways office chairs is a few pixels too thick, especially when you compare it to the other angles you could view the chair from

**Comment by Alecksohs** [comment]
> I feel like the back cushion on the left/right facing office chair is a few pixels too thick, especially when you compare it to the up and down orientations

I agree! I have fixed it.
image

**Comment by Alecksohs** [comment]
image
image

Changed the legs

**Review by Burzah — APPROVED** [review]

**Pull request merged**
