### PR TITLE
Replaces the Singularity with the Tesla on ThetaStation

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
It was mentioned that currently, Theta Station can't really be powered as they have the materials for a singularity generator only which has massive radiation issues (see #16349 for more details, as it's related to those PRs). As a result, changing (for now at least) ThetaStation to have energy ball capabilities.

## Why It's Good For The Game
 Bugs be buggy, we removed the singularity generator from DeltaStation for the same issues.

## Images of changes

Old:

image

New:

image

## Changelog
:cl:
tweak: ThetaStation ruin now has Lady Tesla instead of Lord Singulo
/:cl:

### CODE REVIEW

**Comment by atteria** [comment]
I think you missed adding the dirt decals to the moved charging room.

**Comment by lewcc** [comment]
Why keep the radiation collectors? They won't do anything for the tesla.

Also, you might want to update the flavor text on the paper next to the (now) tesla generator.

**Comment by LightFire53** [comment]
> I think you missed adding the dirt decals to the moved charging room.

Good eye, will add



> Why keep the radiation collectors? They won't do anything for the tesla.
> 
> Also, you might want to update the flavor text on the paper next to the (now) tesla generator.

Also a valid point on rad collectors. As for the paper, I had just full on removed it.

**Comment by datlo** [comment]
The singularity engine fits much better theme-wise in my opinion. I feel like maybe we should fix the radiation issue instead of working around it, especially for this scenario where building a singularity is really just a for fun project for the theta station players? They already have solars that they have to set that provides enough power for the facility.

**Comment by S34NW** [comment]
I see no problems with this PR technically. However I'm not overly sold on us working around the broken singulo instead of fixing it.
Having said that, I'd imagine radiation is on the way out at some point, mirroring the changes on TG.
Overall mixed, but the mapping is fine now at least.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
