### PR TITLE
NSS Cerebon (MetaStation) Security Fixes

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
Fixes a bunch of map bugs/oversights in the NSS Cerberon Security Department

- Adds an air alarm to the Warden's office
- Adds a shutter control button for the armoury
- Moves the Pod Pilot office's air alarm to not be encased in glass
- Adds a security camera to the Prisoner Education Chamber
- Fixes security camera consoles so they work now
- Adds fancy paper bins that give the letterhead option to Command areas and offices, as well as Internal Affairs
- Reduces the amount of Captain's stamps in the Captain's office to 1
- Closes crates that were open throughout the station at round start
- Replaced the Permanent Detention hot drinks vendor to a free variant, as prisoners don't ~~have rights~~ have money
- Replaces an all access air alarm in the Prisoner Education Chamber to require access again
- Fixes the labour camp shuttle doors so they now unbolt when the shuttle docks
- Adds a box of donuts to the security office at the cost of a pack of cigarettes and a red folder

Additional fixes:

- Moves a light a tile over to not be attached to an airlock
- Changes the flash control in the PEC to actually be a flash control
- Removes an invisible, useless item from the armoury
- White ship no longer docks in Permanent Detention, that docking port was moved to the south side of the station; added another docking port that is still north of the station - _note: for some reason there is another northern button in the white ship console, however it does nothing when pressed_
- Fixes random coloured tiles underneath windows in the PEC
- Adjusted Pod Pilot Office and Maintenance Tunnel below the Gamma Armoury to support the Gamma Armoury shuttle docking; loot spawn that was in the way was moved further south
- Removes a extra pipe causing runtimes in permanent detention - _note: There are still more random pipes listed in runtimes when loading the map, this only fixes one in permanent detention._
- Adds another Secvend, this time in the Warden's Office at the cost of moving their photocopier to the secure evidence
- Makes the HoS Office wiring look nicer
- Adds additional wiring to windows that didn't have any shock points to them
- Added warden access to the Armory Shutters button in the warden's office
- Connects a Permanent Detention vent to the rest of the system
- Head of Security now also spawns in their chair

## Why It's Good For The Game
Map parity, baby!

## Changelog
:cl:LightFire53
fix:MetaStation Security mapping bugs/oversights
/:cl:

Oh boy, my first map PR.

### CODE REVIEW

**Review by SabreML — COMMENTED** [review]
Second attempt reviewing this since I accidentally deleted the entirety of the first one instead of submitting it.
Lots of this stuff isn't related to anything you've changed in the PR, but since it's related to the sec department I figured I'd mention it anyway.

<details>
<summary>Collapsable since there's a lot of images:</summary>

Should probably also add the area to this new wall tile too:
image
<hr>

The armoury shutter button doesn't have any accesses set on it, so anyone can open/close it if they get inside.
image
Cyberiad button for reference:
image
<hr>

Since you're editing the area already, would you mind also removing/replacing this?
I'm not sure what's actually meant to go there, but currently it's just spawning an invisible item.
image
<hr>

The 'Flash Control' button here is the wrong subtype, so it doesn't actually trigger the flash at all.
If you change it from `/obj/machinery/ignition_switch` to `/obj/machinery/flasher_button` with the same variables then it'll work properly.
StrongDMM_Uq3xQCdBwc
<hr>

This light tube is probably intended to go on the window in the middle instead:
image

</details>

**Comment by LightFire53** [comment]
> Second attempt reviewing this since I accidentally deleted the entirety of the first one instead of submitting it.
> Lots of this stuff isn't related to anything you've changed in the PR, but since it's related to the sec department I figured I'd mention it anyway.
> 
> Collapsable since there's lots of images:

No worries! If you see anything else (or if anyone else sees something), I'm more than happy to keep poking into it.

**Comment by S34NW** [comment]
Yes, another issue is the gamma shuttle docking area, its the wrong size (the shuttle clips through the walls) and the door is not aligned correctly.

**Comment by S34NW** [comment]
Also, I think the air alarm in the Prisoner Education Chamber should remain as an AA one. We usually don't have them but this is an AI-proof zone so controlling the vents/scrubbers after gassing a prisoner becomes a pain in the arse.

**Comment by LightFire53** [comment]
> ~Also, I think the air alarm in the Prisoner Education Chamber should remain as an AA one. We usually don't have them but this is an AI-proof zone so controlling the vents/scrubbers after gassing a prisoner becomes a pain in the arse.~
> I see you've added a camera in that room, in that case it might be fine. I think the idea behind it being an AI free zone comes from the use of asimov lawsets instead of crewsimov. As the AI would try to prevent executions.

If this turns out to be a tweak rather than fix by a head or maint, I'll pull it

**Comment by S34NW** [comment]
Another thing I'd fix: Move the white ship docking port so it doesn't end up inside perma

**Comment by S34NW** [comment]
More fixes: double scrubber pipe here at 88, 198, no connection to the nearby air vent at all
image 

(this is causing the thousands of runtimes, a very important fix)

two red floorings instead of plating under these windows in execution
image

**Review by S34NW — CHANGES_REQUESTED** [review]
I'd also leave out the captains stamp change, that can be tackled in a bridge section map edit

**Comment by LightFire53** [comment]
> I'd also leave out the captains stamp change, that can be tackled in a bridge section map edit

I'll tackle more of what you listed when I get home today, but to touch on 2 points:

I tried to look to see if there was a nav beacon for the ship docking in perma, didn't see anything initially.
I did the captain's stamp because I was already there, and there's not a lot of stuff to fix regarding the bridge, IIRC.

**Comment by S34NW** [comment]
> 
> 
> > I'd also leave out the captains stamp change, that can be tackled in a bridge section map edit
> 
> I'll tackle more of what you listed when I get home today, but to touch on 2 points:
> 
> I tried to look to see if there was a nav beacon for the ship docking in perma, didn't see anything initially.
> I did the captain's stamp because I was already there, and there's not a lot of stuff to fix regarding the bridge, IIRC.

For the white ship, look at 125, 202.

The bridge is mostly okay in terms of issues, yes. It could do with some attention in regards to its looks however, its a bit bland currently.

**Review by S34NW — CHANGES_REQUESTED** [review]
image
This vent is still not connected to the pipenet.

--

The warden could really do with a second secvend

--

image

It would be preferable if these were wired using curves, not point to point nodes.

**Comment by AffectedArc07** [comment]
Giving CI a beating

**Comment by LightFire53** [comment]
Son of a

**Comment by LightFire53** [comment]
Shocking. My mess up made it pass the check it was failing?

**Comment by LightFire53** [comment]
Shout out to Sabre and SteelSlayer.

**Review by S34NW — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
