### PR TITLE
Revert "Revert "Good heavens, judging by the clock, we should be seeing a [Medbay Remap] dock.""

### PR DESCRIPTION
**Pull request by tigercat2000**
Reverts ParadiseSS13/Paradise#8335

Original PR by FreeStylaLT

# OP

Yes, it is that time again... again. This time an entirely new department. The one right in the center of the station. I think I might hate myself.

As the last time, here are the brass tacks for the impatient folk: (Click for increased size)
BEFORE:

img

AFTER:

img

MAIN GOALS:

- Make treatment easily accessible and convenient
- Eliminate unused / unnecessary areas (Isolation + EV room thing (?))
- Move or otherwise change the layout so the non-essential (CMO, shrink, break room, etc) rooms are NOT in the goddamn center and / or way of everything.
- Improve the overall flow of the department.
- (Not actually a goal, but this happened as a consequence of shrinking the size of Medbay) add more maint
- Improve piping ( ***FUCK*** )

Let's get down to the DETAILS:

**New Lobby and Chemistry:**

img
I am convinced it looks a bit _worse_. I wasn't able to fix the aesthetic issue, unfortunately.
Anyway, it's been condensed into a single entrance, I know, three airlocks in a row, ew, but it doesn't seem to be that bad in reality AND it fixes the major issues with flow the department use to have.

The equipment of that cramped-as-fuck storage / locker room from current Medbay has been split into the reception, and other rooms, as you'll see.

As for Chemistry, it's been made larger.. greatly needed, from what I could tell.
They also received privacy shutters, while consequently getting more windows facing the lobby, to increase visibility, while protecting against the greytide, sort of, as it only blocks the lobby-side:
img

**Treatment / Main hall:**
img

As mentioned, main point was to make treatment easily reachable and convenient, therefore pretty much everything related to healing has been stuck together into one giant complex.

Treatment's just _one_ room now with everything you might need, Cryo is right next to _treatment_ instead of Cloning - that's what it's meant to be used for.

Surgery also got attached and shrunken - having a ginormous 6x6 square for Surgery, and having _two_ of them seemed unnecessarily too much.

Each surgery also has its own storage room with no windows - both to reduce transparency and compensate for the loss of direct maint access (both surgeries still border maint with walls)

**Medical Storage, Morgue and Coroner:**
img

Slightly expanded medical storage, added one more type of medkit into it (the useless, """advanced""" one, and also moved Syringe guns and Belts there - as part of the previously mentioned re-distribution. Having those rather high-demand items in the actual Medbay storage makes the most sense.

As for the morgue - heavily expanded morgue trays and a slightly more convenient access for the Coroner. Also, added direct access for Robotics. Convenience, mostly, but partly to keep disposal pipes from going through walls. Priorities, right.

**Cloning and Genetics:**
img
Not much has changed, really, just slightly altered sizes and Cloning simply gets a cryo cell, instead of being attached to cryogenics, which both convenient AND cramped.
Cloning also gets a neat-o way of exiting:
img

**CMO and Break room:**
img
As said, moved CMO away from dead-center of Medbay back to the sidelines, bordering Maint, while also giving the ability to overlook Genetics, Cloning and the Break Room, thus still giving some degree of importance to the room.
Still has the shutters:
img

**Shrink, Virology, Maint, Secure Storage:**
In-Game:
img
In-Map, plus Maint:
img
Some new things, such as the addition of a sort of "Virology Lobby", which allows Virologists to be seen and talked to through the glass windows, however, the windows do have shutters. 

I believe this is a better integration of Virology into the core of Medbay, as it now appears to be an actual part of the complex, rather than an odd attachment, despite requiring quite the real estate.

img

This is a bit of an experiment, with the goal being making Maint, or in this case, a part of it, easier to traverse for those who actually have legitimate reasons to be in it.

**Maint changes:**

Southwest Maint:
img
A rather large change, incorporating some larger rooms and inter-connected smaller ones, another rather significant addition is the Engineering checkpoint:
img
Its purpose is meant to serve as both a location for re-supplies and a shortcut in Maint, as an Engineer is able to skip going around the Bar entirely, while anyone without access (or tools) is forced to loop all the way around. 

img
Virology maint. Some of the new space has been re-purposed into an abandoned diner, coupled with a grill and a fryer, and some meat in the _personal locker_ in the corner.
As noticed by the odd-ass regular-floor tile in the south side and a welded locker up north, this utilizes the randomized assets for entries.

img
Attached secret maint rooms to xenobiology, both for the traitor potential and for the hidden room.. potential, which have been reported as somewhat lacking for our maint.

img
"reference" maint with some minor medbay loot (though a box of latex gloves isn't all -that- minor) which borders CMO and Genetics. However, the airlock leading to it is Medbay+ access.

Otherwise, I re-piped quite a bit around Medbay, though not enough to be really listed as a large change.

Oh, and, Medbay lost some misc crap like two (?!!) photocopiers and possibly a few roller beds.

That about wraps it up. 

🆑 FreeStylaLT
tweak: Medbay has been remapped
add: New Maint areas have been added south of Medbay.
/🆑

### CODE REVIEW

**Comment by SamHPurp** [comment]
Yo dawg, so I heard you like reversions, so I've ----

**Comment by FreeStylaLT** [comment]
we hot potato now

**Comment by Belsima** [comment]
revert this

**Comment by ktoma36** [comment]
I dont... what is going on? I dont check in for like three days and things are getting revert reverted... what is the world coming to?

**Comment by Crazylemon64** [comment]
We can fix it as needed, so here we go

**Pull request merged**
