### PR TITLE
[TGUI] Mech recharge consoles

### PR DESCRIPTION
**Pull request by TDSSS**
## What Does This PR Do
This PR converts our existing recharger UI to TGUI. This is mostly a port from TG, since their UI was IMO a lot better than our existing, old one. On top of information about mech name and its cell charge, the UI now displays the mech's integrity. 

## Why It's Good For The Game
TGUI good
I also figured the UI is so empty and useless, adding a tiny bit of info (the mech's integrity) can hardly hurt.

## Images of changes
For comparison, this is the **old** UI: 
Untitled
And this is the **new** one:
newd

## Changelog
:cl:
tweak: mech recharger consoles now use TGUI
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
```
Built at: 08/13/2020 1:23:21 PM
          Asset      Size  Chunks             Chunk Names
tgui.bundle.css  88.7 KiB       0  [emitted]  tgui
 tgui.bundle.js   232 KiB       0  [emitted]  tgui
Entrypoint tgui [big] = tgui.bundle.css tgui.bundle.js
Error: our build differs from the build committed into git.
Please rebuild tgui.
The command "tools/travis/build_tgui.sh" exited with 1.
```

**Comment by SteelSlayer** [comment]
In my opinion, you should left align the "Mech Status" line, then shrink the UI horizontally a bit. And also shrink it vertically so that the `<Section>` fills almost the entire window because there is a lot of "empty" space down there.

**Comment by TDSSS** [comment]
IMO, the mech status is a title, which should be center aligned. I'll look into shrinking the UI, though.

**Comment by TDSSS** [comment]
newsize
How's this?

**Comment by SteelSlayer** [comment]
Oh, didn't realize the "No mech detetcted" bars were so big, which makes stretches out the Section. I guess you might need to add 5 or so more pixels back to the UI's height, so it matches the top border. Horizontal space is good now though.

**Pull request merged**
