### PR TITLE
The ultimate poster revolution

### PR DESCRIPTION
**Pull request by RyanSmake**
kep

:cl: Bxil
rscadd: Added a new poster.
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
This is both the best and worst thing.

**Comment by taukausanake** [comment]
I don't get it

**Comment by Ty-Omaha** [comment]
I don't get it [2]

**Comment by Keilden** [comment]
I don't get it [3]

**Comment by Birdtalon** [comment]
I don't get it [4]

**Comment by Vivalas** [comment]
I don't get it [5]

**Comment by RyanSmake** [comment]
_Anyone else?_

**Comment by Ratvar** [comment]
I don't get it [6] too thank

**Comment by Anasari** [comment]
[citation needed]

**Comment by Shadeykins** [comment]
It's George Soros, you dweebs.

**Comment by tigercat2000** [comment]
memes

**Comment by Ty-Omaha** [comment]
that crossed my mind but it looks like he has a mustache in that

**Pull request closed without merging**
