### PR TITLE
Lets you put accessories on other people by attacking them with it

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
rscadd: Attacking someone with an accessory will now let you put things on them without having to strip them.
/:cl:

### CODE REVIEW

**Comment by ScratKnapp** [comment]
:+1:  x :100: 

Now we dont need to awkwardly strip people to give them medals.

**Comment by Yukiona** [comment]
Yes! :+1: X :100: X :8ball:

**Comment by Gummin** [comment]
Awkwardly stripping people to give them medals was always the best part though!
But really, a great feature to have added. :+1:

**Comment by Fox-McCloud** [comment]
Personally, I like TG's implementation better: https://github.com/tgstation/-tg-station/blob/2a9444a891c3684042c5bf2e1b4f77898b10b88b/code/modules/clothing/under/ties.dm#L93

I don't personally think the do_after() is necessary since there's not really anything harmful you can do with this other than commits crimes against fashion.

**Pull request merged**
