### PR TITLE
Blob vs virus

### PR DESCRIPTION
**Pull request by Kyep**
So tired of people confusing blobs, spacevines, and virus outbreaks. Every time, at least one person gets confused as to what the outbreak actually is.

This should help. It isn't a total fix, but at least it is better than just a cryptic "level X" notice.

### CODE REVIEW

**Comment by Plotron** [comment]
But isn't the point of hazard levels to confuse people?
I find it funny when people correct each other in this situation.

**Comment by CrAzYPiLoT-SS13** [comment]
Yeah, I think we should leave it as is, those who make mistake in
distinguishing between these biohazards, will learn from their mistakes. No
point in adding clarifications, especially not in the manner it's done in
this PR. At least, that's my opinion.

**Comment by Fox-McCloud** [comment]
Will need a changelog for this one.

**Comment by Plotron** [comment]
I just feel like it's become a part of our server community now. It's a classic.

**Comment by Kyep** [comment]
@Plotron I always thought the point of the hazard levels was to give people some idea of how threatening the situation was, while remaining a little vague. IE: a level 5 is worse than a 7, which is worse than a 9, etc. Basically lower=more deadly. That was just my impression as a player, though, not as a designer, and not considering the whole system could just be based on arbitrary numbers. Really, I'd love it if numbered levels were removed entirely, and used color-codes like the alert system. IE: blobs were called "RED-level" dangers, viruses and space-vines "BLUE-level".

@CrAzYPiLoT-SS13 Yes, people learn over time. Still, IMHO having 'the station is in danger!' alerts be deliberately confusing isn't the best from a newbie-friendliness perspective, especially when the most serious alert (blob) is also the most generic / least distinctive. Regular players have memorized how to tell the difference, but newer players haven't. Newer players already have a lot to learn, IMHO, and having round-altering events be memorized by regulars but confusing to newer players isn't the best.

**Comment by CrAzYPiLoT-SS13** [comment]
It's just the way it was solved. I don't think we should just add a capitalized BLOB or VIRAL in there. I think a more subtle approach would be better.

**Comment by Kyep** [comment]
@Crazylemon64 What would you suggest?

**Comment by CrAzYPiLoT-SS13** [comment]
That's the problem. I have no idea.

**Comment by Kyep** [comment]
Well, how about just saying "red level biohazard" for blob, "blue level biohazard" for space vines, and "unknown biohazard" for viruses? That would make it clear that blob is serious business, space vines aren't a crisis but could be a problem later, and the virus can be harmless one round or deadly in another. It also does away with the caps, and the silly arbitrary numbered levels.

**Comment by CrAzYPiLoT-SS13** [comment]
I like that, only change viral to "green level biohazard" and vines to "unknown biohazard". It makes more sense.

**Comment by Regen1** [comment]
>newbie-friendliness perspective

This isn't a newbie-friendly game
You learn by observing, so what that you didn't understand that the biohazard code meant blob and not space vines? Now you know a little more about the game and can apply that information to the next time you play.

:-1: from me, keep it a bit cryptic, force people to learn from playing

**Comment by TheDZD** [comment]
Not much of an opinion on this either way, but it's odd how there are two level 5 biohazards, but they are differentiated by the fact that one is the numeral, the other is spelled out.

**Comment by tigercat2000** [comment]
all of the different biohazards should probably have an actual number for them instead of the same number but

**Comment by Plotron** [comment]
I agree with @tigercat2000. Immersion.

**Comment by Kyep** [comment]
Update: Blob is now "level 5 biohazard", spacevine is now "level 7 biohazard", viral infection is now "level 7 viral biohazard" and viral outbreak is now "level 7 major viral biohazard". 

This is very close to how it was originally, the only changes being:
(A) viral infection moving from 5 to 7, which the other viral event was already at anyway
(B) viral outbreak being called 'major viral' instead of just 'viral' so outbreaks and infections are subtly different. 

With these, it is slightly easier to distinguish blob (now the only 5) from the others, but the numbered levels are preserved, virus events are a bit more consistent, and no new sound/AI/outbreak*.ogg sound files are required.

**Comment by Plotron** [comment]
@Kyep, very good changes and ideas. I'm fully in support of this PR. :+1:

**Comment by Belario** [comment]
Better consistency with the alert levels is be nice, but outright telling everyone what the hazard kinda ruins the mystery :-1:

**Comment by CrAzYPiLoT-SS13** [comment]
Robert, it was changed, it's not telling them that directly anymore.

**Comment by Belario** [comment]
Herp derp, serves me right for skim reading.

**Pull request merged**
