### PR TITLE
IPC Takeover gamemode (Not ready for merge)

### PR DESCRIPTION
**Pull request by monster860**
This PR is not ready for merge, I am posting it to obtain feedback about my code and shit.

Here's what I have so far:

- Some IPC's start off with a revolting status
- They have a retractible RJ45 connector
- The RJ45 connector can be plugged into other IPC's to make them join your cause. [Pic](http://i.imgur.com/Y7WB5uW.png)
- The RJ45 connector can be plugged into an exosuit fabricator to add the design for an IPC frame.
- Add wires, microbattery, posibrain, and plasteel to the IPC frame, then use surgery to attach the rest of the components.
- FlattestGuitar is gonna do the sprites, for now I have shitty coder art.
- I need some ideas for the whole endgame conditions. I really don't want a species-specific rev.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
How many IPCs are required at round start for the game mode to be available?

**Comment by Finalsong** [comment]
Do this, but for every species except Human.

**Comment by Spacemanspark** [comment]
I don't know what they would use instead of a connector port, @Finalsong.

**Comment by theColdflame** [comment]
What makes this different from rev aside from gating it behind species?

**Comment by DavidRossii** [comment]
Species specific antag gamemodes are a terrible idea.

**Comment by Spacemanspark** [comment]
Also, instead of "humans", I'd put "Organics". It's a bit more of a broad term that is more explanatory, unless you want them to specifically target humans.

**Comment by monster860** [comment]
Keep in mind, non-IPC's can become IPC's by having their MMI put in a posibrain if you RJ45 a mech fab

**Comment by theColdflame** [comment]
nobody will do that

**Comment by Spacemanspark** [comment]
If you want recruits you would.

**Comment by DavidRossii** [comment]
So I guess IPCs kidnapping Humans to force them into IPC chasis?

**Comment by Spacemanspark** [comment]
Another question:
What is the ultimate goal?
Killing literally EVERY organic being on station?
If so, that might be a bit difficult for IPCs to accomplish.

**Comment by monster860** [comment]
I'm also thinking of, if you managed to get to an ai core/build one, plug the RJ45 into the networking port that NT forgot to get rid of on that AI.

**Comment by NTSAM** [comment]
Species specific antags are butt like David said.
Also murderboning is butt too.

**Comment by Regen1** [comment]
No
Absolutely not 
I like the idea, but we're nog adding a gamemode that revolves solely around a karma locked race.

**Comment by monster860** [comment]
Why is revolving around a karma-race a bad thing? Think of it as having slightly less shitty antags!

**Comment by NTSAM** [comment]
It makes a special funclub for people that actually own something.
That's bad.

**Comment by Spacemanspark** [comment]
Could do a general gamemode that picks from a list of all player playable species (ones with more than one player that has selected said race, probably around 5 players?), and have a neat little unique conversion mechanic for all of them.

**Comment by monster860** [comment]
I could make it so that if they are rolled for their antag, an IPC character is picked from the prefs, and if not availible, then an IPC character is generated for them.

**Comment by NTSAM** [comment]
ew

**Comment by Regen1** [comment]
No 
Leave the idea of it being IPC's only
It's not going to happen, and goes against our ideal of what karma unlocks are for

**Comment by monster860** [comment]
So... Do you have any better ideas?

**Comment by Spacemanspark** [comment]
Could try out my idea.

**Comment by ScratKnapp** [comment]
Even though I am an almost diehard IPC player, I'll have to say no. Besides the fact any IPC revolt would be shut down by one guy with an Ion Rifle, worsening the species circlejerk in this manner is just.. :-1: 

While the gamemode itself might not be a well received idea, would it be possible to make the IPC chassis available for creation in the Fabricator in all rounds?

**Comment by NTSAM** [comment]
I don't really support IPC chassises being constructable.

**Comment by monster860** [comment]
So what conversion mechanics for other races then?

**Comment by theColdflame** [comment]
how about a flash you can use on people without loyalty implants to convert them to the group of people who have to team up to try take out important people on the station?

**Comment by Spacemanspark** [comment]
@theColdflame Don't be sarcastic. Someone has an idea, and they're willing to expand a bit, let them try.

**Comment by Fox-McCloud** [comment]
Having a gamemode revolving around a karma race? No. Not going to happen. It's essentially saying "hey, if you paid karma for this race, you get this special snowflake game mode to go with it that people who don't have this race don't get."

This is just Revolution, only instead of some random crew members selected, it's random crewmembers of a particular race.

A game mode should strive to be as inclusive of as many races as possible, especially for the non-karma races.

**Comment by Keilden** [comment]
While I like the idea that IPCs gets somthing instead of ling/vampire, I don't like the idea of an entire game mode. Instead they should just get a reskinned ling that uses nanomachines to absorb DNA or somthing.

**Comment by NTSAM** [comment]
down with thine murderbone

**Comment by Dumbdumn5** [comment]
Not really into this for reasons stated above, through the entire PR.

**Comment by monster860** [comment]
So, can I hear from an admin about what I should do then?

**Comment by Fox-McCloud** [comment]
A gamemode that pits one species against the rest of the station is likely not going to fly---we already have a "takeover" mode and it's, by far, the most unpopular mode that we have---making it species specific isn't going to change that.

**Comment by monster860** [comment]
But what can I convert it to then?

**Comment by Fox-McCloud** [comment]
This wasn't my idea to begin with so I don't know--I'm just informing you criterion that will would/would not be acceptable.

**Comment by Vivalas** [comment]
>I don't know what they would use instead of a connector port,


( ͡° ͜ʖ ͡° )

**Pull request closed without merging**
