### PR TITLE
Nuclear Challenge Mode

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over: https://github.com/tgstation/-tg-station/pull/13640

Basically, the syndicate leader starts off with a "challenge" beacon that, when activated, gives him the option of getting extra TC for his team.

There's a few conditions:
- Crew population must be 50 or greater
- The decision must be made before the 3 minute mark
- If activated, it gives a HUGE warning to the station that the ops are coming and prevents their shuttle from launching for 20 minutes.

Related
- Ports over TG's configurable delay for when a shuttle can be called; defaults to 20 minutes
- If the challenge mode is activated, the shuttle cannot be called until the 25 minute mark
 - No cheesing victory.

### CODE REVIEW

**Comment by Deanthelis** [comment]
The "Are you sure?" prompt is handy. 

I still foresee people hitting the button despite none of the other team members wanting them to - perhaps consider this only working if all of the uplink computers have uplinks in them, maybe? I guess we'll see if that's needed or not.

**Comment by Fox-McCloud** [comment]
It's the leader who gets it--it's his decision whether to do it or not, really.

Yeah, it may lead to conflict at times, but it's still, utlimately, his decision.

**Comment by Plotron** [comment]
Am I reading this right? 280 extra TC for the leader? How much is that?

**Comment by Regen1** [comment]
Does this prevent the crew from calling the shuttle as well? Would be kinda silly if the crew gets the declaration, and just calls the shuttle and wins.

**Comment by Taaketa** [comment]
Whilst that would be hilarious regens is right. Perhaps a centcomm message stating 'We've received reliable intelligence that A Syndicate Operations team is it's way to the station. Defend your boarders. We will not send an evacuation shuttle.'

**Comment by Plotron** [comment]
Haha, Taaketa, more like "Syndicate Affiliates have set up a blockade. The emergency shuttle will take longer to arrive."
<insert 40 min ETA here>

**Comment by tigercat2000** [comment]
Might be a good idea to port tgstation/-tg-station#13758 and tgstation/-tg-station#13819 at the same time

**Comment by Fox-McCloud** [comment]
Alright, implemented TG's system for preventing shuttle calls; we already had this in communications console, but this works out better for the challenge mode.

**Pull request merged**
