### PR TITLE
Mechanics workshop, take two!

### PR DESCRIPTION
**Pull request by fj45**
https://camo.githubusercontent.com/76a73c737609cbbf9c6514ead6a1330336ef5cc8/687474703a2f2f7075752e73682f674e3277392f343561373165636235352e706e67

Note that the mechanics workshop still isn't how I would like it, if
someone with more skill then me could have a crack at properly
overhauling that entire area it would be great.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Uptodate Image
This is the correct image as of 145fbe1.

**Comment by Artorp** [comment]
:+1: I like it.

Could you add a welding helmet? I assume he still does not start with one.

**Comment by fj45** [comment]
Thanks for that Tiger.

I could add a welding helmet easily enough, just wish there was a bit more space in there.

**Comment by Fishocalypse** [comment]
Strange suggestion- go for welding goggles instead of welding masks. The current mechanic should have welding goggles, and grabbing some from engineering is not that hard.

**Comment by Artorp** [comment]
I like the idea of welding goggles, the mechanic doesn't need mesons and has his eye slots free, makes sense.

As mentioned here https://github.com/ParadiseSS13/Paradise/issues/643, could you replace the stack of plasteel with a stack of plasma?

**Comment by fj45** [comment]
Uh, might have to leave out the welding gear for now due it to complicating things a tiny bit, I'll have to work out those fab issues.

**Comment by ZomgPonies** [comment]
Make a new PR for the rest of the changes, since other bugfix PRs are depending on this getting merged first.

**Pull request merged**
