### PR TITLE
[FIX] return some classes and standardize some class=\"

### PR DESCRIPTION
**Pull request by ROdenFL**
## What Does This PR Do

Returns admin, narsiesmall, cultspeech and attack classes.
Standartize class=\\" in chat messages to class='
fixes https://github.com/ParadiseSS13/Paradise/pull/26852

## Why It's Good For The Game

Fixes aylnog's donkeys

## Images of changes

image
image
image

## Testing

Checked all returned classes

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
fix: Styleless chat messages are gone
/:cl:

### CODE REVIEW

**Comment by AyIong** [comment]
Thanks

**Comment by ROdenFL** [comment]
> Please test in both dark and light mode. Light mode may still be missing its admin span

That's not how it works. Aylong renamed the dark theme to the default one, because if the theme does not contain a style overwrite, it uses the value from there. My screenshots are generally made on the syndicate theme

**Comment by ROdenFL** [comment]
> Please test in both dark and light mode. Light mode may still be missing its admin span

image
anyway, here for you

**Review by Contrabang — APPROVED** [review]

**Review by Contrabang — CHANGES_REQUESTED** [review]
Cult chat is still fucked on lightmode and darkmode

**Comment by ROdenFL** [comment]
image
image

**Review by Contrabang — APPROVED** [review]
tentative approval

**Review by S34NW — APPROVED** [review]
What you have fixed should be fine, not sure about any other potentially missing stuff

**Comment by ROdenFL** [comment]
i've done as much, as i was asked for 🐱

**Pull request merged**
