### PR TITLE
Loosens restrictions on CC ID computer

### PR DESCRIPTION
**Pull request by Kyep**
CC ID computer:
- No longer has a cooldown when modifying open job slots.
- Can now modify open job slots for some jobs that normal ID computer cannot: Cyborg, NT Rep, Chaplain and Blueshield

Reasoning:
- Sometimes, admins want to modify open job slots for event purposes, without having to either wait 60 seconds between each  job slot change, or have to use 'free job slot' on each job, one by one, picking each one from a list.
- There are also situations where we might want more cyborgs, blueshields, or NT reps on the station, such as AI-themed events, revolution rounds, inspections, etc.

No changelog as not visible to players.

The normal ID computer is unaffected. This PR only changes the Centcom version of the ID computer.

### CODE REVIEW

**Comment by taukausanake** [comment]
inb4 100 clown jobs. Calling it now

**Comment by Kyep** [comment]
Only admins have the ability to use CC ID computers.

Even then, we can already modify job slots quite freely. This just makes doing so less tedious.

**Comment by DesolateG** [comment]
100 chappys

**Comment by DesolateG** [comment]
Oh god 100 cyborgs

**Comment by Crazylemon64** [comment]
Resistance is futile

**Comment by taukausanake** [comment]
Can we have 100 AI units please?
"AI, state laws"
"Law 1 ..."
"Law 1 ..."
"Law 1 ..."
"Law 1 ..."
"Law 1 ..."
"Law 1 ..."
...

**Comment by Krausus** [comment]
Why have *anything* in the admin-only blacklist?

**Comment by Fox-McCloud** [comment]
>Why have anything in the admin-only blacklist?

This.

**Comment by Kyep** [comment]
@Krausus @Fox-McCloud cleared blacklist for admins.

**Comment by DesolateG** [comment]
@kyep too many cooks

**Pull request merged**
