### PR TITLE
adds condiment crate HOPEFULLY

### PR DESCRIPTION
**Pull request by jughu**
for all your cheffing needs!

:cl:
add: Adds condiment crate to cargo
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
KILL ME

**Comment by Crazylemon64** [comment]
`git checkout master`
`git fetch upstream`
`git reset --hard upstream/master`
`git checkout -b *my_new_branch_name*`
*make changes*
`git add *changed files*`
`git commit -m "my commit message"`
`git push origin master`

You will need to have configured `upstream` to point to this repo, and `origin` to point to your fork.

**Comment by jughu** [comment]
THANK YOU HERO

**Comment by Crazylemon64** [comment]
Wait the last bit shouldn't be `git push origin master`, it should be `git push origin *my_new_branch_name*`. But it's otherwise correct

**Pull request closed without merging**
