### PR TITLE
Splits Farragus's bridge blast doors in two.

### PR DESCRIPTION
**Pull request by bruhlookatthisdood**
## What Does This PR Do

This PR splits the bridge blastdoors on Faragus into upper and lower, each with their own button.

## Why It's Good For The Game

I just feel like its nice to have extra control over the doors. Sometimes I want to be able to access that meeting room, but I can't because I need the blastdoors and i'd trap myself inside or can't get in at all.

## Images of changes

image

## Testing

Tested, the buttons indeed work. Top button closes top blast doors. Bottom button closes bottom blastdoors.

## Changelog
:cl:
add: Farragus's bridge blast doors have been split into two buttons. Upper, and lower.
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
fetur frez ):

**Comment by bruhlookatthisdood** [comment]
fetur frez over (:

**Comment by S34NW** [comment]
User has linked their account

**Comment by S34NW** [comment]
!merge_upstream

**Review by S34NW — APPROVED** [review]

**Pull request merged**
