### PR TITLE
Disarms have a lower chance to succeed and can have downsides if they fail

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
This PR does a few things to make disarming less powerful and more of a risk to the ones rushing in.
1. Lowers the chance of getting pushed down by 10% from 25% to 15%
2. Lower the chance of succeeding a disarm to drop the weapon by 10%. From 35% to 25%
3. A failed disarm now can get you stunned (Not drop down. Just stunned in place and drop your held items) for a short time if the target is on any intent other than HELP. 5% chance
4. A failed disarm has a chance to let you fall down on your ass. 5% chance.

**Changelog:**
:cl:
balance: Disarm pushing happens now 15% of the time instead of 25%
balance: Disarm disarming now happens 25% of the time instead of 35%
balance: Disarm failing now has a chance to drop you to the floor for 5%
balance: Disarm failing now has a 5% chance to get stunned if the target is on an intent other than HELP
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
I’d prefer removing the RNG aspect entirely but this is probably the best compromise we can get with this community

**Comment by KasparoVy** [comment]
Disarms less powerful? Hell yeah, looks good
...Until you realize it works both ways, as a disarmer you may as well be slippy-slapping with the force of a butterfly for all the good it'll do you now

I love that hopeless feeling!

**Comment by farie82** [comment]
> Disarms less powerful? Hell yeah, looks good
> ...Until you realize it works both ways, as a disarmer you may as well be slippy-slapping with the force of a butterfly for all the good it'll do you now
> 
> I love that hopeless feeling! /s
> I'm conflicted on this one

every disarm still has a 40% chance to "disarm" with this PR. and just a 15% chance to fail badly in total. I myself mostly want this to avoid valid hunters rushing somebody with a d-sword trying to disarm spam him.

**Comment by KasparoVy** [comment]
From personal experience I've only ever gotten major damage from the blocks when disarming someone with an energy-bladed weapon but I'm sure this'll work toward that end

**Comment by Mitchs98** [comment]
Bit iffy on this, but I mean, it'll help the people who've been upset about disarm spam lately. I guess.

**Comment by MrMagolor** [comment]
I like the change goon did to disarms, where a successful disarm knocks the item 1-2 tiles away from the "disarm-ee" in a random direction.

**Comment by KasparoVy** [comment]
That sounds like a sick idea.

**Comment by Mitchs98** [comment]
> I like the change goon did to disarms, where a successful disarm knocks the item 1-2 tiles away from the "disarm-ee" in a random direction.

Even less in favor of this than this PR itself.

**Comment by taukausanake** [comment]
I wonder about different types of disarm someone can perform on another. Like maybe I don't want to knock them down but make them drop their held item. Maybe I want disarm to push them away from me with a short stun so I can make a run for it. Maybe I can panic and I don't care what I do to the other person but I might fall over too because panicking. Little offtopic though.

> disarm spam

If spamming disarm is an issue then why not give disarming a cooldown like everything else? Or better yet, use this PR as a negative to trying to spam too much? Someone who is standing upright is less likely to trip up if they are only pushing someone over. The more they try to though the less coordinated they might be, more flail-y they get. That sounds like a better compromise and hides the RNG aspect of it. Doubt it would/could be implemented though

**Comment by Dinarzad** [comment]
> balance: Disarm failing now has a chance to let you get hit by the targets weapon if they are on an intent other than HELP

I *Strongly* oppose this change. The other nerfs I can MAYBE accept, but being hit by the weapon you're trying to disarm is a bridge waaaaaaaaaaaaaaaaay too far.
I know we're trying to make it less enticing for people to disarm rush an antag, but if you're the one being attacked, you're also impacting the effective of everyone's ability to do anything about it. This has wider and more far-reaching impacts then just valid hunters.

And this honestly feels like "Baby-proofing" to me. Valid hunters are a problem, but we can't just tape styrofoam to every system in the game that a valid hunter COULD abuse, because that road never ends.
Some people are going to be assholes. You can't force people to stop being an asshole, they'll find a way to keep being an asshole, and doing it via disarm spamming is honestly one of the most dangerous ways to do it, given the RNG-centric nature of it. Any valid hunter worth their salt would just use a stunprod or soap, or water or space lube or anything more then just disarm spamming, unless you've caught them by surprise.  and then it ISN'T valid hunting that's someone fighting back, and if an antag can't take that, then that's tough cookies, frankly. They're not owed a victory.

**Comment by Fox-McCloud** [comment]
Not really a fan of this PR. Disarm is the great equalizer in SS13. This ironically further entrenches instant-stun in our combat system, as it effectively makes stun batons, telebatons, and well...pretty much anything all that more likely to actually stun. 

It'll make strike first strategies even *more* powerful because there's even less of a chance that they can be countered.

I don't think this is a good direction with our current combat system, nor do I think it'd be moving in a good direction if we were to change the current combat system.

**Comment by farie82** [comment]
> > balance: Disarm failing now has a chance to let you get hit by the targets weapon if they are on an intent other than HELP
> 
> I _Strongly_ oppose this change. The other nerfs I can MAYBE accept, but being hit by the weapon you're trying to disarm is a bridge waaaaaaaaaaaaaaaaay too far.
> I know we're trying to make it less enticing for people to disarm rush an antag, but if you're the one being attacked, you're also impacting the effective of everyone's ability to do anything about it. This has wider and more far-reaching impacts then just valid hunters.
> 
> And this honestly feels like "Baby-proofing" to me. Valid hunters are a problem, but we can't just tape styrofoam to every system in the game that a valid hunter COULD abuse, because that road never ends.
> Some people are going to be assholes. You can't force people to stop being an asshole, they'll find a way to keep being an asshole, and doing it via disarm spamming is honestly one of the most dangerous ways to do it, given the RNG-centric nature of it. Any valid hunter worth their salt would just use a stunprod or soap, or water or space lube or anything more then just disarm spamming, unless you've caught them by surprise. and then it ISN'T valid hunting that's someone fighting back, and if an antag can't take that, then that's tough cookies, frankly. They're not owed a victory.

My issue mostly is that a disarm has a 60% of success currently. And no repercussions except being close to the target.
Being attacked by the weapon the person is holding is a big thing. Especially if somebody has a baton for instance. I am fully willing to drop the % on that one to 5% as well. So in total that there will be a 40% of success 50% chance of failure and 10% of crit failure.

And for the disarm being an equalizer to ss13. Why are we relying once more on RNG to balance things? A normal civilian shouldn't be able to reliably drop somebodies gun. Disarm currently makes it so that antags need to use stun based weapons. Or meme chems due to the disarm spam they get otherwise when they try to kill somebody with a "normal" weapon.

**Comment by farie82** [comment]
> I wonder about different types of disarm someone can perform on another. Like maybe I don't want to knock them down but make them drop their held item. Maybe I want disarm to push them away from me with a short stun so I can make a run for it. Maybe I can panic and I don't care what I do to the other person but I might fall over too because panicking. Little offtopic though.
> 
> > disarm spam
> 
> If spamming disarm is an issue then why not give disarming a cooldown like everything else? Or better yet, use this PR as a negative to trying to spam too much? Someone who is standing upright is less likely to trip up if they are only pushing someone over. The more they try to though the less coordinated they might be, more flail-y they get. That sounds like a better compromise and hides the RNG aspect of it. Doubt it would/could be implemented though

The ideas you are suggestion can be implemented but are way more work to make them work. 
Disarm already has a cooldown btw. And this PR will make it negative for somebody to spam disarms but by using RNG. It can be implemented that disarm spamming will increase the chance of falling down for instance.

**Comment by Dinarzad** [comment]
> For the disarm being an equalizer to ss13. Why are we relying once more on RNG to balance things? A normal civilian shouldn't be able to reliably drop somebodies gun.

Why shouldn't they? Like. I mean genuinely serious, why shouldn't they be able to knock something out of someone's hand? Just because you're not a trained military bodyguard like the Blueshield you're somehow so utterly inept you can't grasp the simple concept of "Bad man hold bad thing, get bad thing from bad man" ?  If the problem is how frequently it works then why not just touch THAT aspect instead of applying a carpet bomb of nerfs all over the mechanic in several ways that aren't even related to the original complaint/problem? There's no need for a shotgun when you can use a scalpel.

And, just because this targets valid hunters doesn't mean this doesn't have much much wider balance implications. Disarm is also the method of last resort when being attacked, and this significantly nerfs it in those use cases as well. And being close to the target is a MASSIVE downside as it is, depending on what you are disarming that's likely to be a stun and in that case gg no re. If it's a ranged weapon well, that involves even getting close to begin with.  This won't just hit valid hunters and we can't keep up with this "But valid hunters can do X" because that never stops.  Assuming we nerf disarms, okay, there's always lube. And Stunprods. And soap. And water. And bolas. And spears. And on and on and on it goes, valid-hunters will FIND ways to valid hunt. That's why it is against server rules and not mechanically enforced, because it CAN'T be, it HAS to be handled via administration because there's no alternative.

RNG can and frequently IS used as a common form of balance in several forms of game design. Rolling dice, literally or figuratively is a cornerstone in a lot of game systems. You take a chance and see what luck gives you. If you fail that roll, well the antag just got a free shot to murder you to death and given you resorted to disarm spamming, you apparently had nothing else up your sleeve so you probably just died, depending on the antag in question.  RNG existing is not bad design, it's abuse of RNG that can be problematic.
I'm not sure where this is coming from, I've really never seen Disarms be considered that much of a cancerous mechanic or a valid hunters go to tool compared to more sure-fire items like stun prods.

**Comment by farie82** [comment]
> > For the disarm being an equalizer to ss13. Why are we relying once more on RNG to balance things? A normal civilian shouldn't be able to reliably drop somebodies gun.
> 
> Why shouldn't they? Like. I mean genuinely serious, why shouldn't they be able to knock something out of someone's hand? Just because you're not a trained military bodyguard like the Blueshield you're somehow so utterly inept you can't grasp the simple concept of "Bad man hold bad thing, get bad thing from bad man" ? If the problem is how frequently it works then why not just touch THAT aspect instead of applying a carpet bomb of nerfs all over the mechanic in several ways that aren't even related to the original complaint/problem? There's no need for a shotgun when you can use a scalpel.
> 
> And, just because this targets valid hunters doesn't mean this doesn't have much much wider balance implications. Disarm is also the method of last resort when being attacked, and this significantly nerfs it in those use cases as well. And being close to the target is a MASSIVE downside as it is, depending on what you are disarming that's likely to be a stun and in that case gg no re. If it's a ranged weapon well, that involves even getting close to begin with. This won't just hit valid hunters and we can't keep up with this "But valid hunters can do X" because that never stops. Assuming we nerf disarms, okay, there's always lube. And Stunprods. And soap. And water. And bolas. And spears. And on and on and on it goes, valid-hunters will FIND ways to valid hunt. That's why it is against server rules and not mechanically enforced, because it CAN'T be, it HAS to be handled via administration because there's no alternative.
> 
> RNG can and frequently IS used as a common form of balance in several forms of game design. Rolling dice, literally or figuratively is a cornerstone in a lot of game systems. You take a chance and see what luck gives you. If you fail that roll, well the antag just got a free shot to murder you to death and given you resorted to disarm spamming, you apparently had nothing else up your sleeve so you probably just died, depending on the antag in question. RNG existing is not bad design, it's abuse of RNG that can be problematic.
> I'm not sure where this is coming from, I've really never seen Disarms be considered that much of a cancerous mechanic or a valid hunters go to tool compared to more sure-fire items like stun prods.

You still have a 40% chance to succeed with this PR so civs can still do it.

For clarification. By valid hunters I meant more the following:
Bystanders that rush into battle the moment they see a valid. Be it that they rush into a breach or rush into the line of fire. With the point to disarm the antag to get a kill.

Real prepared valid hunters like you are describing won't even use disarm. As you said they will use lube and stunprods.

This PR's aim is mostly to make the rushing into danger thing less effective. You are unarmed and go fight somebody with a weapon. Ofcourse you should have a big disadvantage while trying to fight this person.

If you have suggestions how to fix this problem I'd gladly hear them. But my opinion is that disarming is to strong at the moment and can end somebodies round due to it. Getting rushed by a civ or two and getting RNG pushed down to get killed isn't the most entertaining thing.

Once again. You still have a 40% chance to succeed and only a 10% chance to fail horribly. From which 5% is real bad.

**Comment by Dinarzad** [comment]
> Bystanders that rush into battle the moment they see a valid. Be it that they rush into a breach or rush into the line of fire. With the point to disarm the antag to get a kill.

*Is* that valid hunting? I mean. If you're doing antag things in clear view of bystanders is that really HUNTING an antag? Seems more like the antag came to them and, in all likelihood, is trying to kill somebody they know. "Valid hunting" is not doing anything but running in fear from said antag, it's going out of your way to hunt the valid, trying to save a buddy when you are right there, isn't valid hunting.
  And from the description here, sounds like darwinism would take care of it, they're in the line of fire, they're gonna cause as much problems for any inbound sec officers as the big bad in question.

> If you have suggestions how to fix this problem I'd gladly hear them.

I don't have suggestions because I don't think it's a problem, or is one that is being blown out of proportion.  Though my suggestion would be, absolutely remove crit failure out right. You don't need to screw over someone to 'punish' them, a simple "You do not succeed" is quite enough especially in these high stakes moments.  Lower the success rate to 40% and nothing else, and you have something I *might* questionably be okay with. Because as long as those other percentages's exist I am absolutely never gonna be on board with this, this is way to much for something that only needs small tweaks.

**Comment by Mitchs98** [comment]
Whole-heartedly agree with Dinar and Fox, in all honesty. They said everything way better than I ever possibly could, always like when someone does that for me...I usually mess up wording quite a bit. At any rate. Echoing the above, disarming is already for most people a last line of defense as it is. And given how BYOND handles RNG, we both know 5% is not at all a true 5%. Antags shouldn't get free auto-attacks because someone is disarming them.

Disarming, to me, is entirely fine as it is. If you're hellbent on nerfing it, bring it to a true 50/50. Though overall I really don't think it needs to be changed or nerfed in any manner, especially not to fight 'validhunting'. 

Disarming is as said, most of the time, used in defense of yourself or those in an immediate area/friends in the immediate area. If you're an actual valid hunter you're going to be used much, much worse items than just disarming.

**Comment by farie82** [comment]
Removed the counter attack and replaced it with a short stun. Meaning you can't move nor can't attack if you get parried by the 5%.

**Comment by Mitchs98** [comment]
That's arguably _worse_ than merely getting attacked by the weapon. Actually quite a bit worse. That doesn't really change anything, nor does it change my viewpoint on the matter. If anything I'm even more against the PR now, as as I said, everyone knows 5% isn't a true 5%. And with how BYOND handles things that'll likely be free stuns for antags for people trying to defend themselves, which I don't agree should be a thing.

Disarming is fine as it is.

**Comment by TDSSS** [comment]
Can we just remove the RNG component of disarming please?

**Comment by SkeletalElite** [comment]
Not a fan of this, would rather do something along the lines of how TG reworked disarm intent, where you cant push someone not on help intent anymore by walking into them and disarm intent pushes them, if pushing onto a table or into a wall you stun them.

**Comment by Couls** [comment]
I agree with removing the RNG component of disarm staking everything on a low chance isn’t fun to the person who spent a bunch of time planning an assassination or operation and isn’t that rewarding to the person who got some lucky numbers imo

**Comment by variableundefined** [comment]
I echo Fox's points.

**Comment by farie82** [comment]
I myself think that it'll decrease the reliance on stun weapons due to the fact that you will get less RNG fucked by disarms. Meaning you can actually use weapons instead of stuns to kill targets.
Currently any weapon without an insta stun or antidrop or block are rather useless due to the fact that disarm is so strong. Guy with an axe? disarm him and he's dead. Guy with a .357? Same deal.

If possible I'd like to have a testmerge of this and see how the crew responds to it.

**Comment by Dinarzad** [comment]
It'll have the opposite effect.
You'll just see a much bigger spike in stun prods an the like, things that are a sure-fire stun.
We seem to be viewing this from only one angle and that's not accurate. It works for antags too, and this is ripping that option off them just as much as it's ripping it from civilians.  Sec with a baton? You're now fucked.  Sec with a taser? Good luck taking it from him just to faceplant yourself. This is a blade that cuts both ways, everyone has disarm intent, it;s the 'equalizer' as has been said before.

All this does is encourage stuns even more, but now the chance that they knock that prod or baton out of your hands is chance they knock themselves over just trying, on top of you just needing to click them once make them helpless an then execute them. It's effectively removing an ability to fight back so you end up encouraging people to just carry prods in their bag at all times. Because now they can't just disarm someone an run away without running a high chance of screwing themselves over for 'daring' to not let an antag have a win.

Robustness is not clicking good. It's never needing to risk a click fight to begin with. This will fix nothing, break a lot of things, both balance wise and encouraging more power-gamey behaviour (Which is the opposite of what we're even doing this for) and ultimately is unecessary.

**Comment by Fox-McCloud** [comment]
>There's always another round to be played, it needs to be something we start telling people to just deal with.

More people need to take this to heart.

**Comment by variableundefined** [comment]
Removing disarms would only make insta-stun combat even more prevalent. While RNG might be bad, I'd rather not trade them away to make one of the most complained about aspect of SS13 combat stronger.

Closing the PR.

**Pull request closed without merging**
