### PR TITLE
-tg- underware overhaul

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit overhauls the underwear/undershirt system to -tg-'s text-based
version. No more magic numbers, just text states.

Note, this modifies the SQL Schema, and existing databases must be
modified by the following SQL:

ALTER TABLE server_db.characters
	    CHANGE underwear underwear MEDIUMTEXT NOT NULL,
	    CHANGE undershirt undershirt MEDIUMTEXT NOT NULL;

### CODE REVIEW

**Comment by TheDZD** [comment]
Greatly appreciated, hope this wasn't too much a burden on your sanity with BYOND flipping out because of a lack of blank icon states.

**Comment by tigercat2000** [comment]
@TheDZD Just BYOND being BYOND *twitches*

**Comment by FreeStylaLT** [comment]
socksocksocksockcocksocksocksocks

**Comment by Markolie** [comment]
I want to merge this, but we need to make sure we make the SQL changes first.

@Earthdivine Do you have MySQL access?

**Comment by Markolie** [comment]
Oh, @tigercat2000, you also need to update https://github.com/ParadiseSS13/Paradise/blob/master/SQL/paradise_schema.sql to include the new column.

**Comment by tigercat2000** [comment]
@Markolie [Already done.](https://github.com/ParadiseSS13/Paradise/pull/1740/files#diff-fb28c005899a0e15abbc76db235fc83eR53)

**Comment by Markolie** [comment]
:+1:

**Comment by Earthdivine** [comment]
>Do you have MySQL access?

I have been trying to find it but I haven't been told where it is yet.

**Comment by Robertha89** [comment]
Mel does not have anything simple like phpmyadmin, so you need a mysql client to log in.

Also, if you do not know this should work as normal if you merge it, unless you need to page a new schema, since in this case it's just a new column, there should not be an issue. I might be wrong, so *shrug*

**Comment by tigercat2000** [comment]
@Robertha89 It won't.
It's not as simple as just 'a new column' - the server database needs to be updated, and if it's not, people won't be able to save characters correctly.

**Comment by Markolie** [comment]
We'll hopefully be able to make the SQL changes tomorrow.

**Pull request merged**
