### PR TITLE
Give mechanic and pod pilot GPS devices

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
GPS devices are pretty important to jobs that involve exploring space, so this PR gives pod pilot and mechanic a starting GPS. Playtested and it seems to work with no issues.

:cl:
rscadd: Added GPS devices to pod pilot and mechanic's offices
/:cl:

### CODE REVIEW

**Comment by TYoung86** [comment]
Sure, make them telebomb targets.

**Comment by DesolateG** [comment]
Yes please

**Comment by uraniummeltdown** [comment]
Mechanic yes Pod Pilot no

**Comment by Lady-Luck** [comment]
Yeah, let's not encourage pod pilot to go explore space, please.

I play pod pilot plenty, mind.

**Comment by Tayyyyyyy** [comment]
I explore space as pod pilot only to map out space; I think it's pretty important to be able to fly to telecomms/asteroid/etc. I've recovered plenty of spaced bodies/discovered cults several times.

**Comment by Lady-Luck** [comment]
Given it is against SOP to do that without receiving special permission, giving them a GPS would not be consistent.

The Mechanic definitely deserves a GPS, they're really shafted in terms of access and have enough on their plate already if they want to get out and explore.

**Comment by Tayyyyyyy** [comment]
SoP explicitly permits the pod pilot to patrol telecomms and asteroid, actually. "The Security Pod Pilot is not permitted to explore the area surrounding the station, and must therefore be confined to the immediate orbital area of the NSS Cyberiad, the NXS Klapaucius (the Telecomms Satellite) and the Mining/Research Asteroid. Exception is made if the Head of Security permits otherwise."

**Comment by Lady-Luck** [comment]
I guess that makes sense. The asteroid and telecomms satellite can be hard to find.

**Comment by Fox-McCloud** [comment]
These should probably be on the map and not in someone's inventory.

**Comment by Anoonki** [comment]
>These should probably be on the map and not in someone's inventory.

Yis. Just put the items with the keys on the pod pilot's desk, and the starting pod kit in the workshop

**Comment by Tayyyyyyy** [comment]
@Fox-McCloud @Anoonki I removed the GPS devices from the backpacks and placed them on the map as suggested. I did use the map merge tool but I guess there's still a merge conflict with the map. Tested and can confirm both GPSes are there.

**Comment by Fox-McCloud** [comment]
You're going to have to resolve your conflicts; they are still present. It may be wise just to hard reset your branch to master and start over.

**Pull request closed without merging**
