### PR TITLE
Adds stuff to autopsy

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
fix:Electrocution is now tracked in autopsy
/:cl:

Tell me what else needs autopsy tracking

### CODE REVIEW

**Comment by DesolateG** [comment]
Vampire bites

**Comment by Kyep** [comment]
@Twinmold93 Your feedback is needed.

**Comment by VampyrBytes** [comment]
> Vampire bites

Yes? 😉

**Comment by DesolateG** [comment]
Oh geez

**Comment by Fox-McCloud** [comment]
>Tell me what else needs autopsy tracking

The entire system removed, 'cause it's snowflake and requires a damage proc that isn't as reliable as `take_damage` or `AdjustBrute/Fireloss` =p

**Comment by Crazylemon64** [comment]
It supports those now, are you happy now?

**Comment by Fox-McCloud** [comment]
There's a specific damage proc (and I admit, I may be recalling the wrong one) that is very unreliable in terms of applying/healing damage. At times it will specifically not heal/deal the full amount of damage you specify when its used.

**Comment by Crazylemon64** [comment]
Is it `take_organ_damage`?

**Comment by Fox-McCloud** [comment]
I'm not sure. Whichever proc cryox used to use for healing (prior to adjusting brute/fireloss) would trigger it.

**Pull request merged**
