### PR TITLE
Gives abductors an objective to stay hidden/limit crew disruption

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
This gives all abductors a secondary objective, to keep disruption to the crew to a minimum. Abductors are supposed to mostly stay hidden and just kidnap people, but sometimes they steal the AI, space armory, get into shootouts with sec and dab on the captain. From talking with admins I know that's not really intended so I figured a second objective should make it clear what kind of playstyle is expected of abductor players.
The objective's exact text is:
"Disrupt the primitives as little as possible."
The objective defaults to true and can only be failed if an admin manually toggles it, perhaps because someone did something very disruptive. It is on a per abductor basis instead of per team so you can selectively have people fail, but I expect that won't be done much, if at all.

**Images of sprite/map changes (IF APPLICABLE):**

**Changelog:**
:cl:
add: Objective to abductors to not disrupt crew too much.
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
On the flipside, if an abductor gets hurt, they NEED to use crew supplies. Recharging the pistol isn't that big a deal since you shouldn't NEED to use it anyways.

My idea is adding a special sort of stabilized hivelord core that you can buy for an equipment point or two.

**Comment by TDSSS** [comment]
I mean, if you're hurt and need to heal, that's a necessary disruption and allowed. You just shouldn't troll crew unnecessarily, or steal every set of surgery tools on station "just in case"

**Comment by taukausanake** [comment]
[Hmmmmmmmm...](https://github.com/ParadiseSS13/Paradise/pull/9201#issuecomment-404640852) Yeah I kind of think ayyliums get a free pass to do all sorts of weird shit. Objectives are good and all but they're not as fun as fucking with the crew

**Comment by Fox-McCloud** [comment]
I feel like keeping them *mostly* non-lethal is a good thing, but having them not interfere with the crew at all beyond what they need to do? Ehhh,kinda iffy on this one.

Abductors are kinda designed around the concept of "messing with the crew"; over the years, the vast bulk of their lethal things have been stripped from them and they've been turned into more of a "cause chaos and insanity". 

Taken more literally, this would even actively forbid messing with your abductees after you put them back on station---which, again, kinda negates the whole point of the device that lets you speak with them and implant objectives into their mind.

**Comment by TDSSS** [comment]
Hmm, maybe the objective's not worded ideally.

Maybe it should forbid 'overt' interference or something like that? Open for suggestions.

**Comment by polartron** [comment]
Secondary Objective: _"Complete your primary objective without the station going to Code Red"_
Mid-round antags will most likely trigger it, but it will give you an optional time limit.

The fact that you **have** to give them glands and that you have a limited supply of them makes it challenging in the sense that you quickly run out of glands that makes it less obvious that they have been abducted. Choose wisely.

**Comment by Quantum-M** [comment]
I strongly agree with this PR. Abductors are considerably advanced species, most likely way, way far ahead than any species on the station, all the acts mentioned (e.g. kidnapping the AI, spacing/stealing the armory, stealing IDs from crew, especially all access) makes them see more like a crappy form of greytide that can teleport. They are also supposed to be a "science team" meant to experiment on the crew, and as with a lot of experiments, the less impact the science team has, the better the "outcome".

It doesn't necesarily mean that the abductors shouldn't take the occasional item (taking a few medkits is fine when it's needed, but stealing all medbay items seems far too much of a thing), or "control" their test subjects (e.g. telling them to distract security to a minimal intent would be reasonable, telling them to kill people/themselves is not reasonable).

**_In short_**, the less abductors act out like greytide, the less dumb/unreasonable like antag they would seem (especially since they are the few non-highly dangers midround antags).

The objective could probably be worded better though, something like: "Avoid causing significant impact to the station crew as possible, with exception of your experiments."

**Comment by variableundefined** [comment]
I'm not good at making suggestions but preventing code red don't walk given that stations tends to be in permanent code red.

Lack of perfect information means that even if the threat is completely dealt with (Usually, they are not), security / command wouldn't know it and won't code blue.

Of course, there's also the fact that Code Red grant more authority.

**Comment by MrMagolor** [comment]
The only real reason currently for station to leave code red is the off chance that there are traders; the event will fire but not truly activate, with an announcement saying that they were denied docking due to heightened security level.

**Comment by TDSSS** [comment]
Best suggestion I've seen so far was "Limit contact with your targets outside of conducting your experiments and abduction." I think limiting contact is still rather permissive, you can have _some_ contact, etc.

**Comment by variableundefined** [comment]
That should be good. Let's try that out.

**Comment by TDSSS** [comment]
I tried to do it with the web editor, fled in terror at how bad it is and then promptly forgot. oops. Wording has been changed now.

**Pull request merged**
