### PR TITLE
Changes the genetics XRAY to night vision

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
This is the exact same PR as the one I did before. But seeing things have changed on paradise and a lot of people have PMed me to make another PR for this I'll reopen it.

Removes the XRAY block from the game and replaces it with night vision.
Xray is still achievable with the implant and other ways. DNA vault and the wish granter.
Vampires and wizards still have their Xray. I just removed the block so genetics can't get it and replaced it with a night vision block.

Currently antags have 1 play style if xray is found. Loud. Can't go be stealthy if security and maybe more crewmembers can see you. So what do you do? You perma kill the ones having xray since that way you survive. This is just plain boring.

Why not remove the science xray vision? That one is hard to make and you need atleast 1 other person to implant you. Thus making it more balanced.

previous one: #10102

**Changelog:**
:cl:
add: Night vision genetics block
del: Xray vision genetics block
balance: Genetics now can't get xray vision anymore. This is replaced by night vision.
/:cl:

### CODE REVIEW

**Comment by Allfd** [comment]
Salt inbound!

:+1:

**Comment by farie82** [comment]
@Allfd yeah for sure. Last one got that so I'm prepared :P

**Comment by Ralta** [comment]
I'm okay with this. Night vision is still super useful, and x-ray is accessible via implants n such anyway. Much better than half the crew running around with x-ray, seeing crimes occur through walls and whatnot.

:+1:

**Comment by Allfd** [comment]
It was (last year and a half) and is a very significant problem.

If you think of each crew member as an xray camera.  When we had say 30-40 players, it was manageable.

We have 120 now packed in the same space, when Genetics starts handing these out like candy, you are talking about essentially full coverage of all non-maint areas almost all the time.

**Comment by Necaladun** [comment]
My comments remain the same as the last time.

Rather than removing it from genetics outright, I'd much prefer to see it be nerfed - suggestions so far have been reduced view range, making people appear as skeletons (so knowing who they are is impossible), a hazy overlay to make it harder to see, etc.

I'll add:
Making it a toggle so that it can only be used in brief bursts (15 seconds on, 2 minutes off?), and possibly causing some form of damage to the person using it.

**Comment by MrMagolor** [comment]
Making it the goon xray (like ghost vision, but with darkness still enabled) would be a good idea. Also, possibly making it cost more genetic stability.

**Comment by taukausanake** [comment]
While Necaladun's suggestions sound neat I think I like what @MrMagolor said and do what Goon has. It makes sense that x-ray let's you see through things but not through darkness. I think that's the best outcome for this. And if you can make x-ray and nightvision work together in genetics then you can get the original functionality with even more genetic instability

**Comment by Diegoflores31** [comment]
yeah why not just delete genetics because nerfs everywhere man

**Comment by lass9030** [comment]
I for one is for this. Genetics can easily obtain all kinds of abilities if the RNG is right, including xray, at seemingly no cost, other than time, and some health. Meanwhile, science needs resources, time, and someone responsible for RnD.

**Comment by Dinarzad** [comment]
This is pretty needed.
X-ray still remains available with resources and cooperative work, and a moment of vulnerability (Needing surgery to have it installed).
Night vision is still extremely beneficial, and if Genetics never finds it, Science can provide that too, via night vision huds.

X-ray should be rare and highly sought after given how insanely strong it is, an this is a solid first step. (I feel vamps should lose theirs in favor of thermal vision.)

**Comment by davidchan13** [comment]
Genetics X-Ray should have been phased out a long time ago (probably around the time we took away hulk stun punches), so this is long over due in my opinion. I've yet to see anyone present an argument for why it should still remain, let alone be superior to the more difficult to acquire implant version.

**Comment by variableundefined** [comment]
Closing this in favour of 10864

**Pull request closed without merging**
