### PR TITLE
Fixes hilariously broken Grey Heads 

### PR DESCRIPTION
**Pull request by TravellingMerchant**
Ding Ding Ding, better PR.

Changes Greys heads to be less stupid. Also changes their cig usage back to the same as humans. The eyes have been fixed as well, allowing them to still be edited with the head changes.

People have been begging for it for ages and no one else was going to, so I have. Fits in all suits and with any mask now.

Image of the changes:
Before: 

After:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Not really a fan of the new look...

**Comment by Aurorablade** [comment]
The heads were meant to be like that it's the sprites that need to be made to fit

**Comment by TravellingMerchant** [comment]
Fixing every single mask, glasses and suit in the game is a lot of work. This is simpler and means there does not have to be more duplicate files just so grey's don't look idiotic.

**Comment by Aurorablade** [comment]
We have to do it for vox and drask and this breaks a look some people find iconic also if you look at vgs repo they do have some grey sprites such as https://github.com/vgstation-coders/vgstation13/pull/11886 and https://github.com/vgstation-coders/vgstation13/pull/11071

**Comment by ZomgPonies** [comment]
Yeah porting some of the vg sprites might be a better idea.

**Comment by TravellingMerchant** [comment]
Someone over on vgs likes greys a lot then. 

Someone can port those. Whatever stops people begging me every time I make any other kind of sprite change.

**Comment by SamHPurp** [comment]
Moving the heads back is just making them 'human'... calling them 'hilariously broken'.......

I'm not a fan of this at all.

**Comment by TravellingMerchant** [comment]
@SamHPurp Greys heads are stupidly broken though.

They really are.

**Comment by MrFroztee** [comment]
Even if it means spriting an entire folder of seperate lines of clothing, I'd take that over a more generic design and posture for Greys. They're already basically Human+, and reducing their design to a reskin for the sake of doing less works seems like a cop out.

Make aliens more alien.

**Comment by TravellingMerchant** [comment]
If you don't like the changes, then go see if you can port the things mentioned above.

I'm doing this so I don't get pestered every single time I make a PR to "fix greys masks!"

**Comment by imsxz** [comment]
Hey look it's me, the guy who literally only plays grey.

Currently, my main issue with greys is that I am unable to properly hide my identity when doing shady shit. Allow me to explain. Say I'm wearing a hardsuit or a spacesuit, breaking into the armory for whatever reason. AI will probably notice, and INSTANTLY be able to ID me due to my giant fucking pink eyes sticking through the helmet, rather than saying 'some random dude/random Grey's. am fine with glasses sprites looking silly, but this breaks game mechanics and allows for some juicy meta.

This PR lets me wear masks without fear of being "meta-ID'd" by people, and overall fixing an unrealistic visual. IRL their head wouldn't literally stick through the fucking space helmet mask.

Additionally, it doesn't make them look "human". They still have their iconic goofy ass eyes, which again I'm fine with because it's intended to look like that. The backs of their heads are still thicc too, preserving their weird grapefruit headshape.

And to the drask/vox/other race argument, the issue with greys is that they can be PERFECTLY identified, knowing who the exact grey is rather than just his species. If a vox is wearing a mask, they'll only know it's an unknown vox. Same with other races. Greys only unique identifier besides gender is their eyes, which sticks through the helmets/masks.

The suggestion to make new sprites entirely is silly, you'd have to make hundreds due to nearly all masks and most helmets not fitting. Porting VG sprites could work if you /really/ don't like this PR though.

That's my thoughts on this PR as a literal grey only player, I'd hope it meant more than some of the other people commenting on this post.

**Comment by SamHPurp** [comment]
@TravellingMerchant but this doesn't fix grey masks, this fundamentally alters the entire race's structure, humanising them and making them less alien.

If people are pestering you, tell them to fuck off... but I cannot agree with this change.

**Comment by TravellingMerchant** [comment]
@SamHPurp This doesn't change greys at all. They still work exactly the same. And it _does_ fix greys masks. Literally. You can go wear any mask with this.

**Comment by MrFroztee** [comment]
@imsxz Honestly, that's the tradeoff of picking a different race. If your issue is that people can identify your race as a grey and you're unable to hide, the solution isn't making it so Greys can blend in with the ocean of generic looking humans on the station.

I'm sure Vox, Kidan, and Dionae all have to face that problem, too, but I don't see anyone humanizing _their_ sprites.

I finished reading that wall of text that Travelling just thumbed up for agreeing with him, and they totally and utterly look more human. They're just grey and have weird eye snow, eyes which, mind you, can now conveniently be concealed behind a gas mask. 

There's an easy way to fix these sprites and there's a right way, and right now it looks like we're trying to get this shit done quickly.

**Comment by imsxz** [comment]
@SamHPurp they aren't even that much more human though, they still got the big eyes and the back of their head is still fat.
This PR fixes the main issue of masks/helmets looking unrealistic on them, with their face literally clipping through..
If you think that the new grey looks human, I wanna know the kinds of humans you're looking at.

**Comment by imsxz** [comment]
@MrFroztee the issue isn't the species being identifiable, it's that they can identify the EXACT grey is is, even if it says "unknown". If me and a vox are both wearing a hardsuit without our ID, you'd still know that it was Ares but the vox would just be an unknown vox.
And they still keep the giant back part of their head, and their giant eyes.

**Comment by MrFroztee** [comment]
Half the flavor in their sprite was their short posture. It sounds more like a code issue than a sprite issue, if what you're implying is that the mask doesn't hide your character's name.

**Comment by imsxz** [comment]
It may as well not hide my name unless the person who sees me doesn't know my name, even then they'll still call out "a grey with pink eyes"

**Comment by MrFroztee** [comment]
I'd rather just launch a counter PR doing this modification the right way, and the only thing stopping me is that I didn't see this change as necessary at all, but if it means keeping Greys looking alien, I'd undergo it eventually.

**Comment by SamHPurp** [comment]
The arguement is flawed, if I'm wearing a gas mask as Quixotia, and someone who knows Quixotia sees my red off-to-the-side pony-tail... they'll just say it was me.

**Comment by TravellingMerchant** [comment]
@MrFroztee Then do it. Its definitely wanted. At least I'm actually trying to _do_ something about it.

**Comment by MrFroztee** [comment]
Why didn't you just port /vg/'s if that is the better solution

**Comment by imsxz** [comment]
@samhpurp Your ponytail doesn't go through hardsuits....

**Comment by Aurorablade** [comment]
I can't port the vg sprites ATM due to lack of interwebs at my new place but that is the way to go

**Comment by granodd** [comment]
Moving their head back and shrinking it like that makes it look like they're puffing their chest out and tilting their chin down to touch their neck. Giving the back of their head more mass and also making it appear as though they had a neck might fix this, but I'm also in line with the whole "port /vg/ sprites" thing.

Let's just steal everything that's good.

**Comment by Birdtalon** [comment]
I like the old sprites. Greys are supposed to look silly IMO.

**Comment by KorpoPapiez** [comment]
Don't break muh greys.

**Comment by Fox-McCloud** [comment]
If that was the sprites were like that, when submitted, I'd probably say to go with that one...that said, now people are attached to the current one...this isn't going to fly.

**Pull request closed without merging**
