### PR TITLE
Fixes the arrivals checkpoint's camera monitor

### LINKED ISSUE #5180: Security Checkpoint's camera terminal don't work.
**Problem Description**:
Checked security camera monitor at security checkpoint as officer. It detect no cameras.

**What did you expect to happen**: 
That terminal supposed to work just like ones in brig to allow camera usage outside of brig.

**What happened instead**:
If I got it right terminal at security outpost have different name as well as board from deconstructed terminal - it might be broken outdated version of camera terminal, different from current ones at brig.

**Why is this bad/What are the consequences:**
Security checkpoint is already rarely used. Fixing cameras here would make it more useful for security - officers could enter the booth from time to time to check cameras outside of brig, someone even could help warden from here as dispatcher while keeping an eye on arrivals.

**Steps to reproduce the problem**:
I completely deconstructed and reassembled the terminal to make sure it is not some kind of bug. The board in terminal seems to be different from the one in tech storage by name as well.

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Previously, the camera monitor in the arrivals checkpoint wasn't connected to any networks by default. Now it's the same as the camera monitors in the security lobby, warden's office, sec pod bay, and hos' office.
Also changes the the camera monitor on the emergency shuttle bridge to be identical to the one on the bridge, since it was already the same but with the networks listed in a different order. This has no effect on gameplay, the only effect is that there's one fewer instance of camera monitor.
Fixes #5180
:cl:
fix: The arrivals checkpoint camera monitor is now connected to some camera networks by default.
/:cl:

### CODE REVIEW

**Comment by Krausus** [comment]
That camera monitor lacking default networks is probably intentional, considering it's the only one in an area that's barely secured and not really monitored. Anyone who breaks in would have access to the entire camera network.

**Comment by Earthdivine** [comment]
I mean, it probably isn't intentional since there's also that ID computer there too, so it's meant to be used.

Don't security camera consoles check for ID?

**Comment by Krausus** [comment]
Your access determines what camera networks you can set a camera monitor to use. Once it's set to use a network - which includes any default networks - anyone who interacts with it, regardless of access, can view any camera on that network.

Pretty much anything that can be used to view cameras is, technically, a camera monitor, but with a different icon, name, and default networks.

**Comment by Alexshreds** [comment]
Please do link the issue reports associated with your PRs, just so it's easier to identify which are fixed and need to be closed.
#5180

**Comment by Plotron** [comment]
Buff the antags, yes.

**Pull request merged**
