### PR TITLE
Maintenance Overhaul

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ok, so, in-game, the area of the map people are most unhappy with is maintenance; it's static, boring, and not a very good hiding spot. A number of people have expressed interest in Metastation's labyrinth style maintenance, so I started work on Boxstation's style maintenance for the Cyberiad.

This is ONLY arrivals area maintenance, as it's was the easiest; eventually I'd like to see us touch up the other areas, as well.

In any event, can't really describe this, so, here, have a picture:

mapchange

Not pictured: there's seeds in the public garden (just don't show up on the map) and a medkit in primary tool now.

### CODE REVIEW

**Comment by fj45** [comment]
Eh, while maint sure needs improvement, I don't think this is how it should be done.

Botany bit just seems useless and takes up more space in arrivals. (All of arrivals and cargo needs an overhaul)

The atmos machinery seems...well pretty pointless. If the connector and air tanks are for refilling air canisters, then why not have it more compact and more accessible? 

Surgery room is kind of interesting but doesn't make a whole lot of sense.

Breached room with the locker is uninteresting and the space could be used for something else. Having a damaged room on the outside of the hull could be good though.


An extra janitors closest would be good, atmos always needs more hidy holes.

**Comment by SirBloodBuske** [comment]
Could always make your own station map :p

**Comment by Nienhaus** [comment]
Everyone knows popular servers can't change the map without a drop in players.

**Comment by Fox-McCloud** [comment]
- A public garden actually gives something for people to play around with as a civilian without having to commit to making things for the chef; it also opens up the ability for day to day players to actually craft a few things with wood, as well. I dare say giving civvies more to do besides greytide isn't a bad thing. 

As for the overall design, this is largely taken from TG. Once Meta-Station gets merged in, a lot of random lootdrops will be added. The larger point to this is that it's *abandoned maintenance*; it's not meant to be neat and tidy or even 100% logical; it's a labyrinth for hiding bodies, meeting up with people, or ducking in to hide from security--while giving off the general feel of something that was previously utilized or a poorly planned out project that was abandoned.

It's bringing a hair bit of meta-station to Cyberiad/Box.

**Comment by fj45** [comment]
Is it that people like maintenance with content, or that style of maintenance? I much prefer thing being mostly clean to start with...and THEN going to hell.

At the very least cutdown on the size of the botany room and ditch some of the machines. The biogen infringes on botany.  
You could have four or so garden beds and a small backroom for the equipment.

I also want maintenance to be like that, but I think it can be given some utility while also allowing for that, instead of just being a dodgy place where bodies are found.

**Comment by Fox-McCloud** [comment]
Doesn't really infringe that much when they only start with like...5-6 seeds and lack any ways to genetically alter the plants or extract traits; at best they'll be able to grow some food, wood, or make a few low end products on the biogenerator.

And it does have utility beyond just acting as...a place to hide bodies; its' another construction area, a potential spot to get surgery in an absolutely insane dire pinch, refill area or attempt to repressurize a portion of the station. Think of it like the space bar kinda is (and I dare say our community loves that); it's not meant to be clean and tidy or perfect; it's meant to be flawed and have mechanical, roleplay, and gameplay values to it.

(if it looks a little bare though, I apologize; Tigercat's Meta PR has the lootdrop system in it; taht will be utilized here once that PR gets merged in).

**Comment by FalseIncarnate** [comment]
:+1: From me on this.

Just like when the abandoned maint bar was added, these new areas should hopefully make maint feel less... utilitarian. They'll offer some new stuff for people to scavenge, areas to repurpose, and dark corners to stash bodies in.

That ghetto surgery theater does however lack room to attach a sleeper console to the sleeper bed, might want to move that away from the wall.

**Comment by Fox-McCloud** [comment]
I had the same thoughts on the sleeper initially, but then, but I kind felt it should remain non-functional to add to the the whole "rundown" feel of it.

That said if others feel that it should be functional, I can definitely shuffle a few things in there so it is.

**Comment by fj45** [comment]
I just feel the space could be more useful really.

**Comment by veganzombeh** [comment]
Definitely :+1:. Honestly though I think this still makes it too easy to get from A to B via maintenance. IMO, I'd like there to be some obstructions in the maintenance corridors too.

**Comment by Earthdivine** [comment]
:+1: to making maintenance fun to be in....but it feels very cluttered. It's all one corridor. Just the packed feeling of it is a turn off too.

**Comment by Plotron** [comment]
I appreciate the idea of public gardens, however I'd rather have one in quiet and peaceful dorms (replacement for the swimming pool?) than Arrivals. Just subjective preference.

Regarding the maintenance - I never complained, but I can see why others have.
I just think it's slightly too random. I think we should imagine such maintenance as scattered emergency rooms, unfinished checkpoints and storage areas or vacant offices, not corridors with random walls here and there and secret rooms with no points of entry.

**Comment by ZomgPonies** [comment]
:+1:

**Comment by monkeysfist101** [comment]
I ended up making an account to comment on this. The design is shoddy at best. It's thrown together with little thought to functionality or sanity. Nanotrasen is an evil, miserly company that wouldn't just throw hundreds of thousands of credits of medical equipment into a room and then seal it up to rot. It's confusing and unessecary. On top of that, it removes an access point from arrivals.

**Comment by JaxSiran** [comment]
i also made an account here to comment on this atrocity that can best be described as trash map making. maint does have little to do at the start of a round, set up singu, set up solars, twittle thumbs untill something breaks. but here is the thing when sh*t hits the fan maint has a ton to do. if you want to add more stuff for civi's to do, take a botany lab and make it an addition to the main botany lab and allow civi's to work on it. also you could do a medical clinic that civi's staff to take care of the minor injuries that station staff incur and take a load of work off the main medical staff who are at any given time dealing with deaths viral out breaks, bio outbreaks and the such. you could also potentially create a training facility that is staffed by senior players that have great success in each job type to train new players how to play each job. all of this can be done with out screwing up arrivals and maint.

**Comment by fj45** [comment]
https://cloud.githubusercontent.com/assets/5573038/7948320/b0d390a8-0948-11e5-8125-d017061445e4.png

Our maint should be like this. Full of content and rooms but not completely wonky and decaying.

**Pull request merged**
