### PR TITLE
Delta Disposal - Aft +Starboard Section

### PR DESCRIPTION
**Pull request by Vi3trice**
## What Does This PR Do
Last part on fixing the disposals on Delta. A plant was replaced with a bin in departures, and a bin was added to the brig physician. Space was limited, so it could use some tweaking.

Two sort junctions were also added as the Captain and the Brig Physician didn't have any.

## Why It's Good For The Game
Makes things go where they should, and if something breaks, you won't have to rebuild a wall in the process (usually).

## Changelog
:cl:
add: delta.dmm - Added a disposal bin in departures
add: delta.dmm - Added a disposal bin in brig physician
add: delta.dmm - Added sorting junctions for the Captain and Brig Physician
del: delta.dmm - Removed a potted plan
tweak: delta.dmm - Touched up the layout of the pipes
fix: delta.dmm - Fixed the sort IDs for Medsci and Sec junctions
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
May I suggest, very kindly, that you do the whole lot at once? It makes it easier on everyone with deconflicting their mapping PRs?
Having said that, ill look over this in a moment :)

**Review by variableundefined — APPROVED** [review]

**Comment by AffectedArc07** [comment]
```
🆑
add: Added a disposal bin in departures
add: Added a disposal bin in brig physician
add: Added sorting junctions for the Captain and Brig Physician
del: Removed a potted plan
tweak: Touched up the layout of the pipes
fix: Fixed the sort IDs for Medsci and Sec junctions
/🆑
```

Please specify what map you did this for in your changelog

**Review by S34NW — CHANGES_REQUESTED** [review]
There is a random disposals pipe outside chemistry.
Apart from that, this LGTM

**Comment by S34NW** [comment]
Side note:

WTF was this pipe doing (Vi3 removes it in this PR)
image

**Review by S34NW — APPROVED** [review]
Good to go

**Comment by variableundefined** [comment]
@Vi3trice This PR got the go-ahead. Can you deconflict at your earliest convenience and DM me to merge on Discord after 5 PM EST.

**Review by variableundefined — APPROVED** [review]

**Review by variableundefined — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Review by S34NW — CHANGES_REQUESTED** [review]
Apologies, I intended to request changes but fat-fingered the approve button.

image
What is going on here

image
This above magistrate office is funky


Fix these two and it will be good to go.

**Review by S34NW — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Pull request merged**
