### PR TITLE
Deletes the space worm

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Removes any mention of space worms from the code.

## Why It's Good For The Game
Nobody is going to update this, otherwise it would've been done so a loooong time ago. 
Currently, if an admin spawns this thing in, there's an almost guaranteed chance that it will crash the server, so it seems better to not have this. If anyone wants to revive the spaceworm, I suggest either looking at the TG heretic worm, or looking into an older repo that has the code.

## Testing
It compiled, couldn't spawn any spaceworm

## Changelog
NPFC

### CODE REVIEW

**Review by Burzah — APPROVED** [review]

**Comment by spacegeese** [comment]
not the space worm, that no one ever uses ever! nooo!!!!

**Comment by AffectedArc07** [comment]
Get it gone

**Comment by DGamerL** [comment]
> not the space worm, that no one ever uses ever! nooo!!!!

The absolute funniest thing about the spaceworm is it's capabilities of crashing the server if it's spawned in

**Review by Henri215 — APPROVED** [review]
LGTM (Lets NOT Get This Merged)

**Review by S34NW — APPROVED** [review]

**Pull request merged**
