### PR TITLE
Beret + softcap .dmi split

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
This PR splits berets and softcaps out of the head.dmi files and into their own separate file.
This also changes the typepath/icon paths of a couple berets, and puts all the berets (not including fluff items) into their own code file.
This also swaps the grey softcap to be the default softcap and makes the cargo cap a subtype, hence the map changes.

Due to the typepath changes, some berets and softcaps in the loadout will require re-equipping.

## Why It's Good For The Game
Makes future PRs easier due to less conflicts

## Testing
Tested beret and softcaps on every species and corgis to make sure there were no errors

## Changelog
:cl:
tweak: Code changes to beret/softcap loadout items, some options may need re-equipping.
/:cl:

### CODE REVIEW

**Comment by SynthTwo** [comment]
THANK YOU

**Review by Henri215 — COMMENTED** [review]
image

These three had no mob sprites, see if you caused this.

image


Invisible on vox.

**Comment by Christasmurf** [comment]
> image
> 
> These three had no mob sprites, see if you caused this.
> 
> image
> 
> Invisible on vox.

the berets are fluff items, they have had no changes to icon files/code files so any issues with those specifically are unrelated to what i've done
the caps being missing are my bad woopsie i will fix those

**Comment by Christasmurf** [comment]
> > image
> > These three had no mob sprites, see if you caused this.
> > image
> > Invisible on vox.
> 
> the berets are fluff items, they have had no changes to icon files/code files so any issues with those specifically are unrelated to what i've done the caps being missing are my bad woopsie i will fix those

as it turns out, the berets were fucked with by this PR due to them being a subtype of beret, meaning the icon_override uses the same file as the rest of the berets instead of the correct fluff item file

will fix shortly

**Review by Burzah — APPROVED** [review]

**Pull request merged**
