### PR TITLE
Slimebrains are now properly an internal organ.

### PR DESCRIPTION
**Pull request by lordpidey**
Just a small fix for something I saw when porting devil.

Slime brains now take damage properly.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Classy.

Uh, enjoy your time on Paradise?

**Comment by Crazylemon64** [comment]
Oh, yeah, this got overlooked in the organs overhaul. Remember to update the slime people entry in `human/species/station.dm`!

**Comment by lordpidey** [comment]
It was already changed in station.dm

**Comment by Crazylemon64** [comment]
Oh, that just meant that damage handler was never used, silly me. Well, it looks like spacehotel has a bad organ in there... It seems to be a simple find/replace, though.

**Comment by lordpidey** [comment]
Aright, I'll look into it and fix it later today.

I just did a grep to check for the old filepath, and didn't see any, so I assumed it would just compile cleanly.  My mistake, thanks travis.

**Pull request merged**
