### PR TITLE
Properly Removes Stripper Uniform Sprites

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Properly removes the stripper uniform sprites

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
N-not the mankini.. right? :cry:

**Comment by Fox-McCloud** [comment]
@FreeStylaLT 

Of course not.

**Comment by mrturkeytoe** [comment]
NOOOOO :'(

**Comment by Fox-McCloud** [comment]
I guessed you could say these were....

Stripped out.

:sunglasses:

**Comment by mrturkeytoe** [comment]
WHY HAVE YOU FORSAKEN ME :VVV

**Comment by Aurorablade** [comment]
DAMMIT FOX

**Pull request merged**
