### PR TITLE
Progress bars

### PR DESCRIPTION
**Pull request by tigercat2000**
tgstation/-tg-station#9921
@Iamgoofball 

Progress bars! 
thanks goof
This commit does the following:
 - Ports progress bars from -tg- 
  - Clientside progress indicators for do_after
  - Fancy
 - Refactors wall attackby code to make it 100% less insane; Instead of
   manually checking every little thing, it uses do_after,
   consequentially, making the new progress bars affect dealing with walls
   as well.

For coders: Do_mob and Do_after have been entirely replaced by -tg-'s versions, which are slightly different. Also, whoever ported revenants, __passing too many arguments to a proc should really runtime.__

Most notably, do_after now requires a named variable to be specified, `target`, which determines where the progress bar will show up. It also requires that the target does not change it's location at any point during the do_after.

### CODE REVIEW

**Comment by TheDZD** [comment]
Someone remind me to add the progress bar to the lightning bolt spell as per tgstation/-tg-station#10578/ once this goes through.

**Comment by Fox-McCloud** [comment]
Yay. :+1: 

Glad to finally see this show up.

**Comment by Markolie** [comment]
:+1:

**Comment by Alex6511** [comment]
:+1:

**Comment by KasparoVy** [comment]
Hell yeah :+1:

**Comment by Dumbdumn5** [comment]
:+1:

**Comment by Ultimate-Chimera** [comment]
:+1:

**Pull request merged**
