### PR TITLE
Adds a toxins and burn medkit to the mining outpost and adds in a xenomorph toy! (Take 2)

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
I decided to add a toxins and burn kit to the medbay in the outpost because it lacked one... Why?

I also added in a xenomorph toy from /tg/ https://github.com/tgstation/-tg-station/pull/11411

ss 2015-09-15 at 05 12 52

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Fox, why is github so confusing and mean? :(

**Comment by Fox-McCloud** [comment]
Because something powerful and diverse is usually convoluted and tricky to learn, at first.

**Comment by Ultimate-Chimera** [comment]
Oh yeah, old screenshot because I was too lazy to make another one but all I did was copy the burn kit from the science outpost, put it over the oxy one and then copied the toxins one and pasted that over the burns one, there's no piping beside the bathroom door/wall.

**Comment by Ultimate-Chimera** [comment]
How long do PRs usually take to be merged in? Do they need to be discussed with by other staff or something before being merged?

**Comment by Fox-McCloud** [comment]
24 hours, typically.

There's some exception; refactors, fixes, performance, and custom-item related PRs don't have to wait.

**Comment by Ultimate-Chimera** [comment]
Oh, what do you think about this PR, Fox? Would you support it? Oh, do I need to wait another 24 hours even though my last PR had issues? Would that one have been merged in if there was no conflict or whatever that was..?

**Comment by Keilden** [comment]
I am starting to suspect that you might have a xenomorph fetish. But that can't be true.

**Comment by Ultimate-Chimera** [comment]
Obsession. :P

**Comment by Markolie** [comment]
:+1:

Not mapmerged, but whatever, it's Z5.

**Comment by Ultimate-Chimera** [comment]
How to mapmerge?

**Comment by Fox-McCloud** [comment]
Removing the Xenosuit in this PR and and not informing us was a bad move. You don't have a monopoly on that item.

**Pull request merged**
