### PR TITLE
Traitor Item Additions and Surplus Crates

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Additional Traitor Items

- Adds in Goon style surplus crates (coding from TG) (https://github.com/tgstation/-tg-station/pull/4919)
  - These are crates that cost 20 TC, but contain roughly 50 TC worth of items
 -  Items are randomly selected, up to and including job specific items; you could get some really good stuff, or a whole bunch of useless duplicate stuff.

- Adds in a few TG Traitor items
 - Dehydrated Space carp--rinse it with water to make a space carp. Carp are allied with their creator if the person "imprints" on it while it's still small (done by clicking on it) (https://github.com/tgstation/-tg-station/pull/8777)
 - Pizza Bomb--basically a disguised minibomb; can set the timer between 1 and 10; the next person that opens the box gets a not so delicious surprise (https://github.com/tgstation/-tg-station/pull/8582)
 - Secure Briefcase---pretty much fluff; it contains $5000 and has a base 15 melee damage, but it's pretty cheap for a robust melee weapon.
 - Boxed Blood Red Hardsuit---Fake people out and get them to shout "REDSUITS" over radio; incur panic and take advantage of the chaos you just created PURELY by wearing this (also screw meta).

Other
- Removes detective's conversion kit traitor item
 - He can't even roll for traitor and this item does the same thing as a screwdriver...with the same failure rate (not even joking!)
- Updates carp sprite to be in line with TG's darker purple carp.

Fixes
- Fixes mobs not starting off with a faction of themselves.

### CODE REVIEW

**Comment by fj45** [comment]
Dunno about changing the carp sprites, as much as bright purple is ugly, its SS13.

Rest seem fine though.

**Comment by Earthdivine** [comment]
Thumbs down if I can't get a surplus crate in a surplus crate with this.

On a serious note, will the hardsuit be replacing the boxed soft suit?

**Comment by Spacemanspark** [comment]
No, Earthdivine.

**Comment by Finalsong** [comment]
I support this. Sounds great.

**Comment by Spacemanspark** [comment]
:+1: to everything except changing carp color.

**Comment by Spacemanspark** [comment]
Also, on the blood red hardsuits; are they convertable to different races?

**Comment by Artorp** [comment]
:+1:

The detective revolver when modded by the conversion kit didn't have a chance of failure, instead it bypassed the probability calculation entirely: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/projectiles/guns/projectile/revolver.dm#L76

But then again, the detective can't be a traitor so I guess it's redundant anyway.

**Comment by CrAzYPiLoT-SS13** [comment]
:+1: x :100:

**Comment by Fox-McCloud** [comment]
@Artorp 

Hm, I was under the impression it still had that...hm. My mistake.

**Pull request merged**
