### PR TITLE
Turn diona nymphs into simple animals

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Turns diona nymphs into simple animals, until we have a better solution. They should function similarly to how they did in the past, without being all buggy. Added custom support for simple_mobs to speak languages.
2) Adds resting animations to syndifoxes, syndicats, cats and dionas. Dionas now also have a moment animation (from Bay). Fixes https://github.com/ParadiseSS13/Paradise/issues/1318.

Fixes https://github.com/ParadiseSS13/Paradise/issues/1722.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
they could become monkies, again...but this is likely to lead to Nymphs carrying+stealing everything not bolted down....again.

**Comment by Spacemanspark** [comment]
But that's fun.
Not to mention that a nymph dragging around two eguns through the hall looks fucking amazing.
(I swear I'm only half serious.)

**Comment by Earthdivine** [comment]
I really am not looking forward to Nymphs having hands again. There's a reason it was removed.

What else would this change?

**Comment by Markolie** [comment]
Nothing. This doesn't give them hands - they're similar to how they were before except that they're no longer permastunned, can be attacked, etc.

**Comment by KasparoVy** [comment]
tfw a diona nymph teefs the nuke disk

**Pull request merged**
