### PR TITLE
Gives the handheld defib a new sprite

### PR DESCRIPTION
**Pull request by Darkmight9**
Sprite credit goes to Ionward

## What Does This PR Do
Gives a new original sprite for the handheld defib

## Why It's Good For The Game
The old sprite was a temp sprite in the first place now we have an original one.

## Images of changes
image

## Changelog
:cl:
imageadd: Gives the handheld defib a new sprite
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
CLEAR

**Comment by Ty-Omaha** [comment]
stand clear of patient

**Comment by Fox-McCloud** [comment]
The old sprites should be deleted and these should be put in a different file. 

The goonstation files are ONLY for goon sprites as they have a unique license.

As you're not a goon contributor, nor are these goon sprites, I don't think you want them submitted under that license.

Please change it, or this PR can't be merged.

**Comment by Darkmight9** [comment]
The requested changes have been made PR is ready to roll!

**Pull request merged**
