### PR TITLE
Cyborg Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just a couple of Cyborg Tweaks

Service Borg
- Gives this module a guitar

SyndiBorg
- Replaces the crossbow with a 3D printer gun and grenade launcher
 - When we went from super tank borgs to their currently much weaker state (with module failure and the likes), this was meant to be re-added, but I never got around to it.

### CODE REVIEW

**Comment by fj45** [comment]
3D printer gun?

**Comment by Regen1** [comment]
It's just a gun that has ammo as long as the borg has power, it is called 3D printer because in "logic" in prints the bullets real time as it fires

**Comment by Earthdivine** [comment]
"Replaces the crossbow with .... grenade launcher"

Can we please NOT? I went over this in the Syndiborg threat, if the syndiborg has something that lets him BEAT AN ION RIFLE, he's too strong. Not to mention it does very little damage to the borg.

**Comment by Robertha89** [comment]
the ion gun is more for the stun then the kill, cause it's like a half minute stun, syndiborg is supposed to be strong, ion it, and beat it to death, also I rather see a rocket launcher with 3-5 uses then the grenade launcher. apply flash + baton.

**Comment by Spacemanspark** [comment]
Give it C4.

**Comment by SamCroswell** [comment]
The crossbow beats the ion rifle better than the grenade launcher does, or they are at the very least on par. The Ion Rifle is an instant stun for borgs, the crossbow is an instant stun for humans.

**Comment by Earthdivine** [comment]
Except the crossbow can be dodged by going one tile to the side, needs to be reloaded, and doesn't do damage. Not only can the Grenade Launcher hit in an AoE, it has damage in spades, doesn't need to be reloaded or atleast the cyborg version doesn't, and can stunlock multiple people. While I do admit the crossbow does beat the Ion Rifle, you atleast had to worry about OTHER PEOPLE TOO.

The Syndiborg is strong enough as it is with the crossbow+Esword, it will be stronger with gun+esword, it doesn't need a gun, Esword AND a grenade launcher, particullarly now that the borg subversion works with the Syndiborg.

@Robertha89  Last time I tried to Flash a Syndiborg when they had the launcher he just let me walk up to him then unloaded 3 grenades into my chest, stunning and killing me before I could even click him.

**Comment by Fox-McCloud** [comment]
He has a limited 6 shots that can never be refilled--ever. While the damage is higher, that's the trade-off of AoE vs single target.

Syndiborgs were HEAVILY nerfed when Cyborg health was refactored; they lost over 100 health and would actively lose their modules as they took damage--the crossbow change was made when they were still uber tanks that could take everything.

Something for 50 TC should be well worth the investment

**Comment by Earthdivine** [comment]
This is still a change in the direction the borg doesn't need, IMO. Right now on live it feels very much as an anti synthetic and utility purchase, being able to open doors, subvert borgs, take out the AI, and pin down and take out isolated and important targets. It does its role EXTREMELY well as it is, and adding the gun, and particullary the Launcher, will push it towards being able to do all this, AND kill multiple members of security extremely easily. The borg was hit with a big nerf yes but adding a big powerful gun like the Launcher is not a good trade off.

As it is I would say to fix what the borg does VERY will, which is kill the Ai with literally zero opposition, and then see if it needs the launcher to compensate.

**Pull request merged**
