### PR TITLE
Adds in Cafe Mocha

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in the Cafe Mocha drink

Chocolate+Cafe Latte

:cl: Fox McCloud
Add: Adds in a mocha drink
/:cl:

### CODE REVIEW

**Comment by Regen1** [comment]
Needs all the coffee specifics
 :+1:

**Comment by Spacemanspark** [comment]
Barista alt title job when?

**Comment by Tastyfish** [comment]
Espresso machine / milk steamer when

**Comment by FreeStylaLT** [comment]
espresso when

**Pull request merged**
