### PR TITLE
Adds classic baton and a cargo cap to Sol Traders

### PR DESCRIPTION
**Pull request by Spartan6**
Title. Gives them a basic self defence item and a fancy cap to put on their heads.

:cl:Spartan
tweak: Gives Sol Traders a baton and a cargo cap.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Find some sprite slave and make some neat new clothing sprites that they could wear and sell. 

Or at least rename the hat.

I think giving them a hat outright called a cargo cap seems a bit too low-effort.

**Comment by Spartan6** [comment]
@FlattestGuitar They already have a jumpsuit that says 'cargo technician jumpsuit'.

I'm just trying to get them to look a little less bald.

**Comment by FlattestGuitar** [comment]
Oh lord. Fair.

Still, would be neat to get them some bling.

**Comment by variableundefined** [comment]
I don't see why not

**Comment by Kyep** [comment]
I'm fine with this.

They have bathroom mirrors to adjust their hair, but not all traders will use them. A cap as part of the uniform seems fine.

They have means to defend themselves on the ship, but they're lethal means, and traders might sell them. So a non-lethal option for personal defense seems fine too.

**Pull request merged**
