### PR TITLE
Engineering renovation

### PR DESCRIPTION
**Pull request by GeneralChaos81**
Allows atmospherics staff to reach the Chief Engineer's office, to knock on the window, etc.
Tool storage is no longer a thoroughfare.
Moves Engineering 'front desk' somewhere where engineers are more likely to be.
Moves less used parts of engineering control room out of the way. (The drone machine room)
Both control rooms look like they're designed for more than one person at a time now.
Moved atmos office maint door to avoid people bumping it from both sides every time.
New door to maint (north end). Replaces the double-windoors.
Construction room changed to locker room, and all clothing lockers moved there. Camera cannot see into the showers, but passers by easily can.

Current NEW setup
engiupdate9d

Current EXISTING setup
engioriginal

Current areas
engiupdate9d-a

### CODE REVIEW

**Comment by TheBeoni** [comment]
> Allows atmospherics staff access to the Chief Engineer's office.

No

**Comment by mrturkeytoe** [comment]
I think they mean they don't have engineer/CE doors leading to the locker room between them and the CE office.

**Comment by Aurorablade** [comment]
> Allows atmospherics staff access to the Chief Engineer's office.
...wot?

> I think they mean they don't have engineer/CE doors leading to the locker room between them and the CE office
All the gear atmos needs is in thier area though, Atmos has thier own equipment lockers.

**Comment by Lady-Luck** [comment]
I like this in theory, but to be frank, it just doesn't look good.

**Comment by Fox-McCloud** [comment]
This...doesn't look good, at all, in my opinion. It's a big square open room. I've said before that that kind of design generally isn't a good thing. Inherently, a lot of room *are* square, but now they're filled, decorated, and laid out goes a long way to ensuring how they feel to the player.

This will, IMO, make it feel more cramped and square while bringing no real inherent advantage over the current map.

**Comment by DaveTheHeadcrab** [comment]
More bland, long hallways.
Our map is overcrowded again anyhow.

**Comment by taukausanake** [comment]
I like how Atmos techs can see the CE's office now, better to get their attention, but the whole of it looks more cluttered now than anything. I don't think there is anything wrong with how Engineering is already. I have to go with no to this

**Comment by GeneralChaos81** [comment]
Well that's disappointing, responses were positive on the forums.

I don't want to argue too hard for this (it's my first real try at map edits, of course it's going to be poor), but I would like to improve in this idea, or do better in the future, so can I get clarifications?

Atmos access to CE's office = can walk up to the window and wave, not walk into his office.
Is it really that boxy? Only the tool storage room is an actual rectangle. The existing tool storage is a big box with H formed from the table.

Long bland hallways: Is that about the aft main corridor? Or the 8-tile long one by the Chief's office? (Or both)

Is any of this idea salvageable?
Bypass hall down to CE's office.
Extra maint door at the top of the control room.
Positioning of the atmos maint door.
Extra space in the atmos office.

Thanks for reviewing this PR.

**Comment by Davdichan** [comment]
It's much better than what we have.

Change OP from "Allows Atmos Techs to access CE's office." to "Allows Atmos Techs to approach CE's office" there is some general confusion going on in above posts.

As for the square room complaint, the rooms in question were already square, bland and cluttered with constricted pathways to begin with. Side-by-side this with the current layout of engineering and this is a much better.

Criticism is fine but not offering constructive criticism or improvements is just lazy and does nothing but suggest your nostalgia for the current map is blinding you to beneficial changes.

**Comment by FalseIncarnate** [comment]
I like the concept, but as many people have agreed, the implementation needs work.

One of the biggest things I like is the change to the atmos control room and the engineering monitoring rooms (the two north of the lobby), as they now can actually support more than one person in them at a time. I'd probably put the drop-off point for the MULEs back in that top-most room though, to avoid MULEs getting stuck in the room.

Not sure how I feel about the atmos tech being able to walk up and bang on the windows of the CE's office, but still being unable to access tool storage. Usually, the CE can be reached via radio or PDA, not by lurking around his office (he tends to not be in there much in my experience), so there's not much reason atmos techs need to be able to get at the office unaided.

**Comment by Ty-Omaha** [comment]
It looks too crammed imo

**Comment by Davdichan** [comment]
@FalseIncarnate Every other department subordinates can approach their Head of Staff for paperwork or private requests that don't need to be put onto department radio or shouldn't be. Atmos techs are the only job that's never been able to do this because the engineering storage throughway is cancer.

I do agree though, none of the storage area equipment should be off limit to atmos techs, its mostly gear they already have access to anyways.

**Comment by GeneralChaos81** [comment]
Mechanics too, can't visit their head. I'd really like to add mechanic access to the engineering foyer door, but I don't know how.

**Comment by Davdichan** [comment]
I think it'd be easier to just give Mechanics basic engineering.

**Comment by GeneralChaos81** [comment]
Probably. But that's not for this PR.

**Comment by GeneralChaos81** [comment]
A couple of new draft ideas for the control room.
engiupdatedraft2
engiupdatedraft3

**Comment by taukausanake** [comment]
Those consoles look WAY WORSE and that's not just because they are turned which they shouldn't. I was actually okay with how they were set even if one person couldn't use them all at the same time

**Comment by GeneralChaos81** [comment]
Haha. Ok. Just trying stuff. I was so uncommited to the idea I just photoshopped it.

**Comment by Vivalas** [comment]
I like this engineering so much more than the current one. It makes a lot more sense, and I especially like the monitoring room, it has a mission control vibe going. :+1: to this it looks great. Pretty much all the negative criticism in this PR is also a problem with our current engineering, and this is so much more pleasing than the boxy and ugliness of engineering right now. It might have some problems but is better than what is on hand.

**Comment by Da-Dman234** [comment]
Looks like your storage room is missing a fire-alarm and a scrubber. Also, you shouldn't have an APC terminal located on the same tile as a vent.

Also, I really do think you need to move the storage room. The general access part of engineering is now just a three tile long hallway with crap thrown on the side, which is a big no-go. 

If I had to suggest anything, I'd say get rid of the currently never-used construction area and do something with it there. If you want to redesign the core of engineering to atmosians have access to it, sticking a storage room in the middle is not the way to do so. Also, use less windows for the storage room.

**Comment by Belario** [comment]
Well it's better than what we have.
Could do with being prettier but like I said, better than what we have :+1:

**Comment by GeneralChaos81** [comment]
Added scrubber and fire alarm to tool storage. Moved APC. Also fixed it in the hall outside.
Here comes the madness... Goodbye construction area. Hello locker room and showers.
That allowed me to move the crap out of the 3-wide hallway, which I will put decorated tiles down for, assuming this design is alright.

engiupdatedraft4

**Comment by Davdichan** [comment]
Minor (as in barely worth mentioning) complaints I have to the new suggested layout:

AI holopads don't have much coverage. Recommend putting one in the foyer at the end of the table to give it a semi-central location and coverage of the room. If there is a pad in the room, make sure its not covered by a table or anything, as an AI player its incredibly frustrating to find a holopad in a room if its not visible by default (RD office used to be like that.)

Atmos Control Room and Storage Room holopads aren't centrally located, and my OCD does not like that (in short it bothers me but it's not a big deal)

The bigger stickers here are cameras

The camera in the locker room is inside wall, in the shower. Should probably move it down to the benches and have it face north (giving the showers some privacy)

The camera in the atmos control room is mounted on a door. Looks bad and is probably against one of Fox's mapping rules.

As a suggestion, I'd make the shower doors windoors. Tinted or frosted glass instead of a wall would also be kinda a nice touch if we have them  (glass that isn't transparent)

Aside from that looks great and actually makes engineering seem like a better place to hang out.

**Comment by Vivalas** [comment]
You should probably make the showers use the bathroom tile the other bathrooms use, the slightly greenish one. I like it though. Could you also add a sink and mirror to both showers?

**Comment by GeneralChaos81** [comment]
Fixed AI holopad locations.
Fixed cameras for atmos office (was on the door) and changing room (in the wall).
Changed shower walls to tinted windows.
Added some tiling, and some more floor flair around the place.

engiupdatedraft4

**Comment by Davdichan** [comment]
Was the double holopad in atmos control intentional?

**Comment by GeneralChaos81** [comment]
Ha. Oh dang. No.

**Comment by Davdichan** [comment]
I swear I only try to help.

**Comment by Da-Dman234** [comment]
Do all the cameras have proper ID/Network tags?

**Comment by Belario** [comment]
Only thing I don't like is the squareness the lower half has, if you could magic it up to look as good as the upper part it'd be great.

**Comment by GeneralChaos81** [comment]
The cameras were not tagged, and one had research outpost ID. Weird. Fixed.
There was a fire extinguisher cabinet in a wall.
Changed Tool storage shape. Moved the two vendors out of it, as they have their own independent access requirements, plus some radios, again for poor forgotten atmosians.

The construction room has not been renamed. Do I just change Name from \improper Construction Area to \improper Engineering Changing Room, or does something else need to be done?

engiupdatedraft7

**Comment by Fox-McCloud** [comment]
This still looks cramped, croweded, and cluttered. It's a hair bit better than before, but I still don't think it's good, personally.

**Comment by tigercat2000** [comment]
I don't see the point. I like engineering as it is.

**Comment by GeneralChaos81** [comment]
Well I've got a side-by-side of current and renovated engineering and I see what you mean Fox. Let me see what I can do...

Testing and so many issues (again). Hello, reinforced wall under a door. How are you today?
Also, I don't know if it's my build or what, but atmos tech has access to the whole of engineering (minus the CE's office). Is that right? Is that how it is now?

**Comment by Spacemanspark** [comment]
It's not how it is currently, no.

**Comment by GeneralChaos81** [comment]
Oh good. Weird that I'm getting atmos on engineers and vise versa when running it locally.

**Comment by GeneralChaos81** [comment]
What about this for the foyer?
Turned the table back around. Had a run around in that and it feels cleaner.
engiupdatedraft7b

**Comment by Da-Dman234** [comment]
Mind throwing up a quick picture of the area zoning?

**Comment by GeneralChaos81** [comment]
Of course. I had one, but it was outdated and removed. It's in the first post. @Da-Dman234

**Comment by GeneralChaos81** [comment]
OK, I'm a GIT amateur and committed wrong stuff. How do I undo that last commit?

**Comment by GeneralChaos81** [comment]
I'm going to have to kill this branch and start it again, aren't I?

**Comment by FreeStylaLT** [comment]
What were your main goals with this map edit PR? What did you dislike about Engineering lobby layout that made you want to change it to that?

Also, Atmos techs don't actually get access to the engi-vend, so they wouldn't be able to use it anyway.

**Comment by GeneralChaos81** [comment]
I play a lot as CE, so acutely aware that a storage area was also a primary passageway, which... is weird. If anyone tried to pull that at my RL workplace it'd get shot down so hard. And also that atmos staff couldn't come tap on my window. I'm one of those CE's who hangs out more in his own office than the bridge, which I guess is not normal.
From an antag perspective, it puts atmos techs as close as engineerings to blueprints too.

After I posted pics of that, people on the forum also suggested expanding the atmos office, because 2 atmos techs... one chair, and it's super cramped. To get that to work I needed to shrink the engineering control room slightly, and I was bothered that the drone room was putting more distance to the 'front desk' of engineering... so shuffled that around. At that point I realised drones and borgs would probably want a better way out, than the long way, and that also med and sci had multiple maint escapes, where engineering only had one, and atmos one. So added shared one.

The consensus is that the construction area was never used too - I've seen it used and used it myself less than a dozen times. After all the 'too cluttered' comments, and a long think, and then copying the new sec layout a bit, went for moving all the clothing locked into a change/locker room. Also got to add in an engineering clothes locker, which seemed to be otherwise totally missing from the station.


So... it snowballed. I just wanted it so engineering equipment storage wasn't a primary passageway, but couldn't think of where else to move it that was still convenient, didn't block off atmos, and still hopefully in CE's line of sight.

And yeah, atmos techs can't access the engi-vend, but engineers leave the secure wardrobes unlocked, so that was a bigger security change. Plus atmos tech with a coin can get insulated gloves, if no other valid method exists (like no engineers and CE). There's a lot of love for atmosians in this PR, and I don't play as them anymore, but I remember the hardships, and I know what I get requests for almost every shift.

All said, if the consensus is that any part(s) of the changes just don't work, I like each part, so not everything has to change. I'm just not sure, overall which parts people don't like.

**Comment by FreeStylaLT** [comment]
I am not really in favor of it, mostly because the walls, windows.. _things_ seem to be all over the place.

- img
Odd wall bit under the computer hut. It seems to not have any real purpose to be there other than to create an artificial hole to stick the firefighting lockers into.

- img
Not maint tiles under the windows. Why is the only window in the computer hut next to a computer? Or rather why can no one see anyone sitting in the computer hut from the lobby without going all the way around?

- img
Why are these walls reinforced? Should there be windows there? The current computer hut is actually clearly visible from the hallway. Functionally this extension is similar, yet you walled it off.
img
This bit does not have reinforced walls, but the upper pic one does. Why?

- img
Why is there a recharger here? Along with that disposal bin. Why is it there? There is not even anything in the room to dispose of and it is in an awkward spot.

- img 
Missed maint tile again

- img
Where does the second disposal chute directional bit trail off to?
img
This one to be precise.

- img
Why is there a radio _and_ a cell charger on the same table?

- img
Why do you avoid making cornered windows, yet
img 
Allow it to happen here?

- img
Why is the atmos entrance popped out compared to the walls of the rest of the room?
You do not do this with the locker room, lobby entrance or the storage room.

- img
Why is this entrance DEEPER inside than the actual room?
To be quite honest it seems like this T shaped bit you have here is doing nothing but hindering the aesthetic appeal of the location. It's like you tried to be artistic with the shapes of walls rather than practical.

- img
If atmos techs have no access to the tool storage, why do they have access to this hallway? Is it for cohesion regarding all from a department having some access?

- img
img
Floor patterns. These bits have them. The rest of the floor does not.

- img
Why is there no vision of the locker room besides the airlocks?

- img
Why is there a window here and _only_ here in this entire computerhut section?

- img
Why is the mail reception thing here? Seems to be a bit more of a robot-only zone rather than anything human-related.
Also, why is the APC casing there?

- img
Why is the path to the locker room for Engineers twice as long as for Atmos techs?

- img
Why is there so much shit on this one table?
You have these two tiles
img
You can put racks here and move some of the massive clutter on those few tables there.

- img
the hell is this floor pattern

- img
I can't... tell for sure but I think it is missing a shower head.

- img
Why only one sink and mirror? Why tinted windows? Why are the clothing lockers _there_? I think most toilets would have the sinks and mirrors be where the lockers are and the lockers be either in the lobby or in the locker room, like in brig.

Not sure if I'm done here, but I'm done _for now_.

The more I looked at it the less I liked it. Lots of questions.

**Comment by Bram961** [comment]
Holyshit

Some of this is nitpicking, some of this is actually important.
I'm trying to be critical here and there are good things but writing them all down would fill up the image to much so this is stuff that needs to be worked on in my opinion.

(I am not quite sure if the two air alarms for one area was bad or not)

**Comment by Fox-McCloud** [comment]
I'm kinda with @tigercat2000 

I really don't think Engineering really has any problems as it currently stands, and I largely like its current design.

**Comment by GeneralChaos81** [comment]
@Fox-McCloud I agree that the current engineering IS nice. I play engineer or CE about 90% of the time

For the other comments, thank you. I can work with this, and I'll try to address everything raised.

Without specific examples of the crazy reasoning in some of the items listed: Some of the stuff was already like that(!), I have been trying not to move the rooms around too much (despite what it may look like), and tried not to increase or decrease the number of items available.

Just one thing, when Cargo ships items to Engineering via disposals they arrive near the engine. If they ship by mule they arrive in the very opposite end of engineering. Neither location are checked very often.

**Comment by GeneralChaos81** [comment]
Not quite done yet, but I think this is all I'm going to be able to do today:

engiupdate9

Everywhere
- Plates under reinforced windows

Control room (and main hall)
- Moved O2 closets, pumps and scrubbers up one square to match up with new windows.
- Added windows into control room, because yeah, you should be able to see into it from the main hall.
- Moved charger back into drone room. The charger wasn't moved when I switched the rooms.
- Moved disposals into the drone room, because I don't want to reduce the number of chutes.
- Extra window on the south side. I've moved more wall things to the north side, so did not add another there.
- Moved the entry into the centre of the bottom side, to reduce trip distance to the locker room.

Drone Maintenance
- Moved cyborg charger back to the foyer.
- This room's APC powers both it and the control room. They're technically the same room (and always have been) - should I fix that?
- More access points: It is not an additional door. I removed the double windoor entry, and added a maint door to replace it.

Foyer
- CE's disposal pipe was unchanged from original plans. I've reduced the spidering pipe a little. I could redo the pipes properly if that's the right thing to do.
- Billboard wall jut reduced. That was an artifact of trying to make the room less 'boxy'.
- Put the disposals back where that wall was.
- Removed the boombox. They don't even work, do they?
- Moved the cig machine to make way for atmos front window/wall
- Changed how indented the control room door looked. Newscaster to other side of the room. Yes, I was trying to be artistic with the walls. There appears to be a very fine line.
- Updated tiling. Should be a little more consistent now? I dunno. Not great at floors. :|
- Borg charger back in here, by Equipment Storage
- Waste piping was always like that, but I've moved it out to be in line with adjacent supply pipe.
- "This area is way too big." I can see where you're coming from. It appears to be one of the largest not hallway areas in any division. 
- Regarding the new hall: Atmos can now reach the bounced radios and tool vendor. Can pop by the chief's office.
- "Close enough to bombgrief the engine." There are two doors between the front of engineering and the engine. There's two between maint and the engine room. There's not really a loss of security, in my opinion.

Equipment Storage
- Extra screen removed
- Moved tables around. They're... kind of in categories. But the tables were always mixed, so not THAT sorted. There's a little less stuff on the tables overall now.
- Unblocked the Fuel tank.
- Charger table is just for the charger.
- Chaged one of the walls into reinforced window. When the entire thing was windows I was told 'too many windows'.

Locker Room
- Changed camera name to match the room name: Engineering Locker Room
- Moved the sink off to the side
- Confirmed there is in fact a shower in the right shower, it's concealed by the curtains. Copied a proper one and fixed it up.
- Changed tiling. There's a few engineering tile orientats that aren't in the list. Should I try to add those in, or just deal with what I've got?
- More windows for people to see into the locker room.
- Changed scrubber pipe to not run under walls in this room.
- Why only one sink? This was based on Security's locker room, which only had one.
- Why tinted windows? It was suggested. Seemed liked a reasonable request.
- Why showers at all? I had just enough room to put them in, and it filled in space I couldn't think to put anything else into. Yep. Because I could.
- Why are the clothing lockers by the showers? Because the fit there without blocking anything else.
- "Muh testings" That was my first through fifth thoughts on the subject of getting rid of the construction area. But we now have TWO of them, over in incinerator maint, so I went for it.

Atmos Control Room
- Moved the front window/wall combo
- Checked Air alarms. One of these was for Atmos main room.
- Door into atmos moved over by one
- Connectors moved from their original locations (that's where they've always been - dogma). I didn't have the right options available under pipe-simple-hidden-cyan, so now they're gray.

Maint
- Waste pipe up to medbay now goes through a different area.

**Comment by GeneralChaos81** [comment]
OK, I don't know why these checks are failing suddenly. D:

**Comment by FreeStylaLT** [comment]
update the OP with a proper pic and in general next time you make a map PR only have the OP contain the relevant pics.. I'm getting a bit confused now

**Comment by GeneralChaos81** [comment]
@FreeStylaLT the OP has the same picture as my last post. I agree, and have been meaning to clean them all up. OP is the only one with pictures now.

**Comment by Plotron** [comment]
Looking better and better! Keep it up!

**Comment by GeneralChaos81** [comment]
Ran it up and... the foyer doesn't feel right.

- Fixed corner by the arcade machine (added table back into main hall).
- Moved a fire extinguisher cabinet out of a wall in control room (to drone room).
- Moved rack with gas masks, vests and o2 tanks closer to the main door.
- Turned the table again (like the 6th time now?).
- Moved the atmos door up to accommodate the table.
- Moved the atmos control room disposals out of the way of the door.
- Put the Supermatter book back on the engineering table (when did that disappear?)

Thinking I might change the shape of equipment storage, to have room to put vending machines back into it... Maybe?

**Comment by GeneralChaos81** [comment]
I think I fixed the merge. Does the warning have to be removed manually? Or did I screw up in GIT?

**Comment by Davdichan** [comment]
I'm not sure if that is enough engineering locks. Atmos usually has 2 slots and a spare for late joins/job transfers. Engineering has 5 slots if I'm not mistaken, though if you haven't removed lockers from engineering it might not be an issue.

**Comment by GeneralChaos81** [comment]
Three of each is the default amount of each atmos and engineering. There's enough spare engineering gear to outfit a fourth Engineer transfer into the department.

*added link to image of original engineering setup

**Comment by GeneralChaos81** [comment]
Piping
 - Moved scrubber branches from the portable scrubber loop, to the main scrubber loop (like it used to be).
 - Added scrubber main pipe redundancy (like it used to be).

CE Office
 - Moved disposals pipe to not be under walls.
 - Wires under south window changed to match the other two windows.

PA Room
 - Plates under door instead of tiles. Fixed.

Engine Room (west)
 - It looks like the west SMES is hotwired. I haven't seen this cause a problem... should I just leave it alone? Looks like this would affect Engine Room APC, Secure Storage ACP, Hardsuit storage and CE's office.

**Comment by FreeStylaLT** [comment]
Still has issues regarding.. just.. general layout, really.
img
The Locker room either needs a revamped entrance for Engineers or you need to find a new spot for it. It just seems awkward for Engineers to trek twice the distance of Atmos techs.
Along with that, why does the Locker room has a direct connection with the computer hut and Atmos lobby, rather than Engineering's lobby as a whole? Even on paper that sounds.. odd, doesn't it? It looks odd, too, imo. Why even have a locker room? The spare space from the construction room could be used to be more maint, or an extension of the computer hut. 

On top of that there is this issue:
img
That is the "official" path for a person to get into that room, without taking the maintenance shortcut.
This is not the case in the original map, why did you remove the windoors and add the additional maintenance entrance?

Otherwise:
img
I am NOT SURE if these are examinable, since I can't load up the map to check.

img
Not maint tile

img
Start your job as AI, check if these two are enough to cover the lobby. I doubt it.

Navigating the hallway:
img
Not very practical to be forced to move around all the time. That rack is in the way. Awkwardly placed.
On top of that, it seems regardless of that rack, you the hallway is hardly a hallway if there's only one tile to follow to get through it without changing directions. No hallway does this. (Not brig, not Medbay, not any primary hallway)

img
If everything is glass here, why is the primary entrance still a solid airlock?

img
What purpose does this bit even.. have, now? The flaps are meant to be used by mules, but you moved the mulepoint. So this has no purpose to exist anymore. Could be windoors, as said earlier.

img
This may be more of a personal than objective point, but chairs being next to entrances like that just kind of _feels_ awkward. This happens very rarely in the actual map as it is, except for a few cramped receptions and _never_ happens for Conference/meeting type of tables. (See Conf. room, Captain's office, brig conference room, holodeck's conference room, heck even bar avoids this except for the holotable)

img
I hope these windows have lockdown shutters.

img
I see you moved the lockers around, but forgot to include a disposal bin in the lobby, which would have fixed a sore lack of it there.

Honestly, I am not sure you are solving the right problems here.. if any to begin with.. I am not saying the Engineering's layout is without its flaws, I am saying you may not be presenting the _right_ solution to them.

**Comment by GeneralChaos81** [comment]
Damned floor tiles! Always sneaking in under windows.
 Cameras cover all of engineering... but they miss a few squares in the hall. I'll fix that.
 Darned things in the hall.
 Airlock without windows because... that's how it was. Easy enough to change.
 Windows have shutters, yes.
Yeah. That's the feeling I'm getting. I might let it sit for a few days, look at it with fresh eyes later.

**Comment by Davdichan** [comment]
@FreeStylaLT Are you intentionally nitpicking or just trying to kill the PR because it's changing things?

>The locker room pathing

Aside from you hilariously misrepresenting things by picking the closest chair to a door and the farthest, from the upper left corner of the table it's 11 steps for an atmos tech to get to the locker room and 11 steps for an engineer. Twice the distance = the same distance?

>Drone Fabricator

Shouldn't this be a maint room anyways? Drones are no more attached to Engineering than Cyborgs are to Science. The only reason to go into the room is to A) Hack a drone that recently spawned or B) Send orders via their terminal, which the AI will do anyways.

>hallway pathing

clutter

Not that different than what we have now, which is said to 'increase the feel of clutter in the room' that engineering should have.

>Drone Fabricator Flaps

drone

Drones can use flaps. It ads to their character as bots and mindless worker slaves keeping the station intact, they go where people can't to fix things nobody cares about.

>I hope these windows have lockdown shutters.

Engineering control room and foyer have never had lockdown shutters or blast doors. Why add them now?

**Comment by GeneralChaos81** [comment]
The lockdown doors were at the edge of equipment storage. Since that doesn't actually block off access in this edit, I had to move them. Closer to the engine would leave the engine vulnerable. So... front windows it had to be.

**Comment by FreeStylaLT** [comment]
@Davdichan 
>Locker room

My point regarding locker room pathing issue is with the length, which Atmos still get an odd advantage over, along with its overall location. Like I said in my point regarding it, it just.. doesn't look like it belongs there at all.

>Drone fab

My point again, was mostly the fact that the legitimate windoor access was removed, but a maint access was added. I simply asked why, as it seemed oddly inconsistent.

>Hallway pathing

That is fine in the current Engineering, as it does not have hallways, but rather rooms connecting with each other. No hallway on the station obstructs movement to the extent this edit does. Consistency was the main concern, again.

>Flaps

No other location on the station has flaps without purpose. They are either for mulebots, or in cargo. This one has.. no purpose to be there.

>Window shutters

Currently, this is where the shutters reside:
img

Blocking access to Engineering completely unless approached from Maint, that is not possible now, given the fact that there is a hallway. So, unless new shutters get added somewhere in the hallway, the entrance itself to Engineering should be blocked off, though I guess it could be done a bit differently, actually.

**Comment by GeneralChaos81** [comment]
I'm putting this on hold for a little while. Should I close the PR, and reopen it when (if) I'm ready to resubmit again?

**Comment by Fox-McCloud** [comment]
>I'm putting this on hold for a little while. Should I close the PR, and reopen it when (if) I'm ready to resubmit again?

If you plan on not returning to it for quite a while, yeah, it would be best to just close it and re-open it in a new PR at a later time.

**Comment by Fox-McCloud** [comment]
Closing this due to submitter's statement for keeping it on hold and re-submitting later.

**Pull request closed without merging**
