### PR TITLE
Manually revert Purpose's smoothing PR

### PR DESCRIPTION
**Pull request by variableundefined**
**What does this PR do:**
This reverts the code changes made by the smoothing PR and the subsequent fix (But not the refactoring and the separation of .dmi files). We suspect it might be a cause of the crashes on the server.

It also change the plating icon back to the old one.
**Changelog:**
🆑:
remove: Plating smoothing changes
tweak: Plating's icon is back to the old one once again.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Uh. If you're sure? We ran this code 24/7 on Oracle where it was developed, and we -never- got crashes.

**Comment by variableundefined** [comment]
We have reports that a possible cause of the crashes is turf accessing something from another turf that isn't necessarily valid at the time of its creation, specifically in New().

The server crashes started on the 9th which was the day this PR was merged, or close to it, so we are going to test merge this revert and see if the crashing issues persist.

**Comment by SamHPurp** [comment]
Okay. Lets make sure this is test merged long enough to see if it still crashes.

**Comment by alex-gh** [comment]
Here is the byond bug report thread: http://www.byond.com/forum/?post=2405066

**Comment by KasparoVy** [comment]
Lummox the GOD

**Comment by SamHPurp** [comment]
Sounds like there is a bug somewhere, but Lummox claims to have patched the problem of it dying that hard.

So the impact is now minimal, but we still have the underlying cause to hunt

**Comment by Fox-McCloud** [comment]
This has been tested on both 511 *and* 512, and it has caused the complete cessation of crashes on the server, ergo, it strongly appears this is the culprit to it.

**Comment by SamHPurp** [comment]
I mean, if you read Lummox's post @Fox-McCloud , he confirms as much, but states that the new version (not yet released) fixes this.

**Pull request merged**
