### PR TITLE
Removes immersion breaking text to speech sound effect from APC events

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
This PR removes the immersion destroying text-to-speech voicelines from the APC overload events. They have been replaced by the "standard" AI voice just saying `Attention`. 

## Why It's Good For The Game
This sound effect just doesnt fit right in the game. A lot of the staff I have spoke to say it feels out of place, to the point where its more akin to asking someone to go to a checkout in a supermarket. Its just a generic text to speech voice which feels super out of place.

## Changelog
:cl:
sounddel: Removed out-of-place text to speech voice from APC events. It now just says "Attention" in the standard voice.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
A shame tbh, I like it myself.

Sadly tho with our other sound effects it really doesn't quite fit in.

**Comment by Qwertytoforty** [comment]
I'm fine with it as is to be honest, I find it funny, but I get if people want it gone

**Comment by Carthusia** [comment]
I do like it to, would be cool to have two AI vox voices instead of just the one

**Comment by Mitchs98** [comment]
Echoing the above, I personally like it. It sounds nice to me and actually fits the sci-fi theme quite well.

**Comment by TDSSS** [comment]
Personally, I hated it and am glad it's gone. Btw, what would be needed to get more sounds like the original AI vox ones? Like, is whatever was used to make them no longer available?

**Comment by AffectedArc07** [comment]
@TDSSS I got sent some DAW patches which can make stuff similar to it, will have a look later.

**Review by SteelSlayer — APPROVED** [review]
Code is fine.

**Review by Kyep — APPROVED** [review]

**Pull request merged**
