### PR TITLE
fixes #15967 Removes rogue pixel of doppley array

### LINKED ISSUE #15967: Rogue pixel on doppler array
**Issue Description**:
EghWSDwczt

**What did you expect to happen**: 
That pixel in the bottom right to not be there

**What happened instead**:
See image

**Why is this bad/What are the consequences**:
Looks bad

**Steps to reproduce the problem**:
Open eyes

**When did the problem start happening**:
Since the sprite change

**Extra information**:
I have been coffee free for over 7 days

### PR DESCRIPTION
**Pull request by DogsParadise**
fixes #15967 Removes rogue pixel of doppley array

## What Does This PR Do
fixes #15967 

## Why It's Good For The Game
No rogue pixel

## Changelog
:cl:
fix: Rogue pixel fix for doppler array
/:cl:

### CODE REVIEW

**Comment by DogsParadise** [comment]
Let me check the bot before.. i make mistakes again

**Comment by DogsParadise** [comment]
Should be good now

**Review by hal9000PR — APPROVED** [review]

**Comment by hal9000PR** [comment]
oh actually, just one thing. change the CL to be something like `fix: rogue pixel on the doppler array`

**Comment by DogsParadise** [comment]
> oh actually, just one thing. change the CL to be something like `fix: rogue pixel on the doppler array`

fixed

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
