### PR TITLE
Reinforced wall-pocalypse for internal walls (Non-Space)

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Basically takes only _internal_ wall changes from #5395, which were mostly just removing unnecessary (according to same criteria) walls. Criteria being, if it is a secure area, it should be (at least from the outside) covered in rwalls. Otherwise, it should be regular walls. There are a lot of inconsistencies with rwalls on the station.

Pics:

## Engineering:

Before:
img

After:
img
None of the lobby is meant to be secure enough to require rwalls, _especially_ not the building area.

**Virology hallway:**

Before:
img

After:
img
It is a hallway, I see no reason why have the additional security for it. Virology itself remains coated in rwalls.

**Xenobio entrance:**

Before:
img

After:
img
Not sure why they were inconsistent like that, especially the odd regular wall on the corner there.

## Experimentor:

Before:
img

After:
img
No need to have access to the actual hallway be reinforced, likewise I do not think experimentor warrants the same kind of protection from outside as R&D/Robotics, though I can add that back, no biggie. 

Also pruned needless rwalls near Genetics, covered Toxin Storage in rwalls - I believe that should be a secure enough area to be protected properly.

## Mechanic's garage/maint:

Before:
img

After:
img
I do not think his garage was meant to be this secure, only areas bordering space now have rwalls around his office.

**Chapel maint bits:**

Before:
img

After:
img
Basically just pruned the rwalls, perhaps they were there for some.. aesthetic reason? But I am not sure why it's there.

**Permabrig:**
Before:
img
Blatantly ripped from the other PR :^)

After:
img
Externally, I am sure it is meant to be reinforced, however, I don't know why they would be internally.

## Firing range

Before:
img

After:
img
No reason to have firing range reinforced from brig medbay, or that bit near the computers. Not sure about the middle section of firing range, but I removed it for sake of consistency.

## HOP/Conference/Bridge West Entrance:

Before:
img

After:
img
Conference room is not a secure area, HoP's office and Bridge are, I made rwalls reflect that properly.

## Surgery:

Before:
img

After:
img
The rwalls at the bottom were not even consistent with those on the left side of surgery. If it was meant to be a secure area - which is not, then it should have been covered completely, rather than only arbitrarily at the bottom. Trimmed unnecessary rwalls at the top right as well.

## Morgue:

Before:
img

After:
img
Not sure why Morgue had to be protected at all, along with Genetics to that extent.

Leave your opinions here.

**No space-bordering tiles were changed. That is for another PR.**

### CODE REVIEW

**Comment by TheBeoni** [comment]
I am against this. Since it would allow literally any antag easy access to these areas with just welder and wrench. :-1:

**Comment by FreeStylaLT** [comment]
Which is the point, since they are not meant to be secure. On top of that, most rwalls I removed were not the kind that fully enveloped a room anyway, so an antag was able to get into most of those with the exact same tools, anyway.

**Comment by Alexshreds** [comment]
> I am against this. Since it would allow literally any antag easy access to these areas with just welder and wrench.

First PR: Dis be makin antags weak mon
Second PR: Dis be makin antags too stronk mon nerf nerf nerf

**Comment by Norgad** [comment]
The r walls scattered around maintenance were cosmetic.

**Comment by Doukhan** [comment]
Muh consistency :+1: 
Be nice to see more hidden walls lying around inside departments too.

**Comment by pazneria12** [comment]
Im all for this, hidden walls are always fun for me.

**Comment by taukausanake** [comment]
I need to try tearing down that HOP/Conference maint wall, the one right next to the accounts computer, and see if I can steal everyone's money. That would be cool, and why I wonder it doesn't have r-walls.

Still thought maint walls exterior to only maint themselves were supposed to be reinforced because of radiation fluff. Yeah [in here](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/events/radiation_storm.dm#L24) it says "shielded maintenance tunnels". That's all I want to point out with replacing maint walls

**Comment by FreeStylaLT** [comment]
That wouldn't explain why any other rwall coated area gets irradiated though - not sure if rwals were meant to he the explanation for that

**Comment by tristan1333** [comment]
But
A E S T H E T I C maint R-Walls
But yeah really nice changes, I prefer r walls in maint though.

**Comment by mrturkeytoe** [comment]
My only negative feelings about it are the liberty of r-walls around the account terminal computer and conference room, if you kept the changes to xenobio from the other PR I personally think the holding cell walls should be all r-walls incase you are trying to contain something more dangerous than slimes and the walls leading to the main room of science being not r-walls.

**Comment by FreeStylaLT** [comment]
Xenobiology's rwalls remained rwalls. If there wasn't a pic of it - it wasn't changed. @mrturkeytoe

**Pull request merged**
