### PR TITLE
Fixes numerous Metastation bugs

### LINKED ISSUE #6921: [Metastation] Mining System on the Mining Outpost Doesn't Work
**Problem Description**:
The mining outpost has the old style of refinery, which doesn't work for some odd reason.

**What did you expect to happen**: 
People to be able to refine the ores that they mined.

**What happened instead**:
They have a note saying to drag it all the way to science.

**Why is this bad/What are the consequences:**
Out of Date

**Steps to reproduce the problem**:
Play on Metastation

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

### LINKED ISSUE #7427: MetaStation: Pipes outside Turbines
**Problem Description**:
Unable to unwrench the pipes from engineering airlock to turbine airlock.

**What did you expect to happen**: 
It's a pipe. You should be able to unwrench it.

**What happened instead**:
It stays wrenched in place

**Why is this bad/What are the consequences:**
You cannot redirect the pipes

**Steps to reproduce the problem**:
Select wrench. Select corner pipe or straight pipe.

### LINKED ISSUE #7428: Outpost cameras don't show.
**Problem Description**:
What is the problem?
The mining outpost cameras do not show on any of the monitors on the bridge or HoP's office even though it is listed at the top as able to be added.

**What did you expect to happen**: 
Why do you think this is a bug?
Because there is a monitor dedicated to these cameras but they are not viewable.

**What happened instead**:
How is what happened different from what you expected?
see above.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Broken feature, and makes the outpost unable to be monitored should the need arise.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Open the console like normal and try to view.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### LINKED ISSUE #7938: META STATION: Windows on the Escape shuttle are indestructible to blunt force
**Problem Description**:
The windows seem to be unbreakable by any mortal means

**What did you expect to happen**: 
To be able to break into the shuttle to get my friends away from a raging plasma fire

**What happened instead**:
Smacked the window with a duel esword for two minutes before having to abandon my friends to a fiery death

**Why is this bad/What are the consequences:**
If escape is compromised people will need to break on board. It also makes hijacking harder when they can only board through the airlocks.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was a nuke ops round and I had the disk. I was trying to get the surviving crew on board the shuttle. The syndi suit I had was fire proof, but my friends werent. I smacked the window with a duel esword for a full two minutes before everyone around me died.

### LINKED ISSUE #8311: Metastation: admin move to cryo button does not work
**Problem Description**:
On metastation, you cannot force-move ssd people to cryo using the admin List SSDs verb.

**What did you expect to happen**: 
They should end up in Cryo.

**What happened instead**:
They don't move.

**Why is this bad/What are the consequences:**
Tediousness.

**Steps to reproduce the problem**:
Load metastation.
Have an SSD person.
Use "list SSDs" to find them.
Hit 'cryo'.
Observe nothing happens.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
https://github.com/ParadiseSS13/Paradise/blob/855de4a7caafb749d7707f824910eb42e7f6003d/code/game/machinery/cryopod.dm#L760
Metastation has cryopods in /area/crew_quarters/fitness. On Box, they are in /area/crew_quarters/sleep.
Either the check for area should be removed, or Meta/Delta/etc should be updated to place the cryopods within a /area/crew_quarters/sleep area.

### LINKED ISSUE #8317: Roboticist missing stuff that makes life hell.
**Problem Description**:
Missing a few things, notably, a starting posibrain, component analyzer. May be more, but those were the most immediate and painful realizations.

**What did you expect to happen**: 
If an IPC gets vandalized early, best I can do is blind repairs, and hope he can come online and tell me what's hurt.

**What happened instead**:
I expected to be able to build a body, pop in a robobrain, send the new borg on it's way. As well as I expected to be prepared for damaged IPCs

**Why is this bad/What are the consequences:**
As previously stated, if early on, a wizard fireballs an IPC, he's getting blind guesswork surgery.

**Steps to reproduce the problem**:
Play roboticist

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope. Not really. I may be aware it is a cult round but that is because my friend asked questions and I am nice and won't go REEE and stab her repeatedly with a screwdriver.

### LINKED ISSUE #8516: Metastation: Atmospherics are lacking
**Problem Description**:
Atmospherics do not have access to any **inflatable doors/walls**, **pipe painters**, multitools, flashlights, or welding goggles. (Only flashlights are missing on the main station.) Having a third locker would be lovely as well. And the wall in the middle of atmospherics is a huge bother, at least replace it with reinforced windows if not remove altogether.

**What did you expect to happen**: 
To have access to some, if not all, of the above, and for the room to be less of a bother.

**What happened instead**:
There was no access and the huge wall was always in the way. It got way too cramped for two people trying to gear up.

**Why is this bad/What are the consequences:**
This made atmosians sad and unable to do their work properly. It also prevents any larger projects from not being a complete pain to do, such as setting up the Thermo-Electric Generator or a proper waste cooling.

**Steps to reproduce the problem**:
Include two or three of the mentioned items on atmospherics' desks. Change the large wall into a thin glass wall (two reinfoced windows next to each other one separate tiles), or remove it altogether. Add a third locker if the map allows three atmos techs.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I absolutely loved having instant access to the atmospherics reception desk. That was an incredibly simple but useful update.

### LINKED ISSUE #8518: METASTATION: Camera not mounted on wall.
**Problem Description**: 
The camera located in Medical's Cryo-cell room, left of the cloning room, appears to be mounted onto thin air, instead of on a wall. 

**What did you expect to happen**: 
Because the camera is clearly mounted into thin air and looking into a corner, instead of looking into the room.

**What happened instead**: 
Explained above.

**Why is this bad/What are the consequences:**
This isn't bad per se, I believe it just requires a small direction-readjustment. 

**Steps to reproduce the problem**:
No steps needed. I just flew by in observer mode and found it like this.

In the image blow, the camera I'm speaking of is two tiles in front of my Ghost, on the lower left corner of the small table.
scrnshot1

### LINKED ISSUE #8553: [META] Medbay Wireing Issues
**Problem Description**:
What is the problem?
CMO, Viro, Medbay Storage, Surgery Obv. APCs not wired to gird
**What did you expect to happen**: 
Why do you think this is a bug? 
They should be wired else they will lose power.

**What happened instead**:
How is what happened different from what you expected?
Expected all station APCs to be wired if they are not a construction area. 
**Why is this bad/What are the consequences:** These areas will lose power. CMO will get angry and viro wont be able to do their work. 
Why do you think this is an important issue?
These areas are important to medbay to function smoothly.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Was a drone went to inspect area with power alarm found their APCs not connected to the main power was sad and disappointed in builders what are we paying them for mistakes like these. Anyways not sure how these were missed unless  you rearrange medbay and forgot too adjust the wiring.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. it was Metastation

### LINKED ISSUE #8560: [META] Detective Doesn't Have Evidence Access
**Problem Description**:
What is the problem?
On the Metastation map the detective doesn't have access to evidence storage.

**What did you expect to happen**: 
Why do you think this is a bug?
This is a bug because evidence storage is one of the most important areas for the detective's job.

**What happened instead**:
How is what happened different from what you expected?
As a detective, I went to open evidence storage to place some evidence in. I discovered that I didn't have access to evidence storage as the detective.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
This is bad because it makes it extremely difficult for the detective to scan and store evidence from crime scenes, which is the biggest part of their job.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1) Load up Metastation (this bug doesn't exist on the main map)
2) Be a detective.
3) Try to open evidence storage.
4) Cry because you can't do the one part of your job anyone actually cares about.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### LINKED ISSUE #8610: METASTATION - Fire alarm floating off of wall.
**Problem Description**:
There's a fire-alarm floating off of the wall, as shown in the imagine attached.

**What did you expect to happen**: 
Not really applicable.

**What happened instead**:
Also not applicable.

**Why is this bad/What are the consequences:**
No real consequences, it just looks weird.

**Steps to reproduce the problem**:
No idea, I found it as is. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Happened on the Meta-station. It's in the Brig's Gear room, one up and one right from my Vox.
scrnshot1

### LINKED ISSUE #8611: METASTATION - camera monitor without any cameras linked
**Problem Description**:
to add to Wolfsyndrome's issue, there are some more floating fire alarms in perma. Also the camera monitor in brig reception isn't linked to any cameras.

**What did you expect to happen**: 
expected camera to be linked to it.

**What happened instead**:
no camera linked to it.

**Why is this bad/What are the consequences:**
floating things just look out of place; but the monitor having no cameras linked makes monitoring camera ... well impossible at least from there.

**Steps to reproduce the problem**:
just click on the camera monitor.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
just on Metastation, tried to monitor cameras as I usually do
metastation camera issue

### LINKED ISSUE #8647: [Meta] Arrivals pod bay outside freeze over
The tiles for the civi pod bay tend to feeze over. 

https://puu.sh/zgObV/45ab1a732b.png

### LINKED ISSUE #8649: [META] Law Office Privacy Shutters Grant no Privacy
**Problem Description**:
_The privacy shutters in the law office windows on Metastation do not obscure vision or whatever when closed._

**What did you expect to happen**: 
_The privacy shutters for the law office on Boxstation work._

**What happened instead**:
_See above._

**Why is this bad/What are the consequences:**
_Low priority, but this means that there is no confidentiality to the affairs conducted in the law office._

**Steps to reproduce the problem**:
_Close the privacy shutters and stare straight through them into the hall (or vise versa)_

**Possibly related stuff**:
_Staring through the shutters both directions. The law confirmed that he was able to see me, as well._
metalawofficeprivacyshutters

### LINKED ISSUE #8688: Metastation Virology Wiring Issue
**Problem Description**:
In the narrow hallway leading to virology, the cabling under the tiling is incomplete, leaving virology to quickly lose power at the beginning of a round.

**What did you expect to happen**: 
Virology, as the rest of the station, to remain powered as long as power was nominal.

**What happened instead**:
Virology, being cut off from the power network, lost power within the first half hour of the round.

**Why is this bad/What are the consequences:**
Virologist is unable to participate in the round without power.

**Steps to reproduce the problem**:
Issue submitter was playing as engineer. Was alerted to power problem in virology around half-hour mark of round. Made way there shortly thereafter. Found no issues inside of virology, tested wiring with multitool, and found no voltage in wiring. Lost power and lighting in room. Followed wiring out into corridor leading into Virology, and found missing length of cabling. Connected missing length of cabling, and Virology received power as per normal.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Picture of affected area: https://i.imgur.com/r2CuDcY.png

### LINKED ISSUE #8961: metastation map curruption issue
image

### LINKED ISSUE #9645: NSS Cererbron Telecomms APC Runs out of power too quick.
**Problem Description**:
The APC located in the Telecomms room in the AI sat on the Cerebron station runs out of power too quickly, to where it auto-shutsdown the entire room's machines when it gets too low.

**What did you expect to happen**: 
I guess I expected the APC to be able to handle the machines well until after the end of a 2-hour shift? 

**What happened instead**:
The power ran so low the auto-setting shut down all the machines, so I no longer received alarm messages as the AI. 

**Why is this bad/What are the consequences:**
It's very easy for the AI to miss important alarms when all the machines are shut down, and we don't get a warning message the APC's run low, either. 

**Steps to reproduce the problem**:
Run the station for 2+ hours and see for yourself? 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
No real additional stuff of note. Maybe as a possible solution, attach like 10 solar panels to the AI sat so it has its independent power and can charge the SMES already in the sat to keep the APC charging? 
untitled

### LINKED ISSUE #9652: Broken metastation bot pathing
**Problem Description**:
What is the problem?
Bots move only on small L shaped path in escape, not patrolling rest of station.
On attached screenshot I marked their path with red line.

**What did you expect to happen**: 
Why do you think this is a bug?
Bots should patrol whole meta station, not just escape

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I found them there, I assume It was since round start

### LINKED ISSUE #9654: unconnected pipe brig emergency storage maint
connector is not connected to the pipe

### PR DESCRIPTION
**Pull request by SamHPurp**
Fixes #7938
Fixes #8518
Fixes #8317
Fixes #8553
Fixes #8311
Fixes #8961
Fixes #8688
Fixes #8649
Fixes #8647
Fixes #8611
Fixes #8610
Fixes #8560
Fixes #8516
Fixes #9654
Fixes #9652
Closes #7427
Closes #7428
Closes #6921
Closes #9645

:cl: Purpose
fix: Metastation - Escape Shuttle windows are now breakable again.
fix: Metastation - Medbay camera no longer floating in mid-air.
fix: Metastation - Adds the missing component analyzer to Robotics.
fix: Metastation - Fixes the wiring issues in Medbay.
fix: Metastation - Fixes the wiring issues in Virology.
fix: Metastation - Fixes the lack of fungus on the map, placing it near water sources in maintenance.
fix: Metastation - Fixes area definition, so that admins can now send people to cryo.
fix: Metastation - Fixes bizarre map corruption from the Arcade PR which turned Coroners into a bit of an arcade....
fix: Metastation - Law office's shutters now grant privacy properly.
fix: Metastation - Fixes the lack of inflatables & pipe painter in Atmospherics
fix: Metastation - Adds a second atmos locker, as one is lower than number of atmos slots available....
fix: Metastation - Properly marks airless tiles by the hanger as airless.
fix: Metastation - Hooks up Security's Camera Computer to the station's cameras...
fix: Metastation - Fixes the floating fire alarm in Security.
fix: Metastation - Fixes the detective's lack of Evidence Storage access...
fix: Metastation - Captain, IAA and NT Rep's fax machines are hooked up properly. Bloody IT department...
fix: Metastation - Security cannister attachment is now attached to the pipe grid.
fix: Metastation - Bots now correctly patrol the station again.
tweak: Metastation - Updates the turfs & decals to use the correct decals.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Awesome, great job re-upping this 👌

**Comment by Crazylemon64** [comment]
Thank you so much!

**Comment by SamHPurp** [comment]
@Crazylemon64 of course.

Not that I care about the point system, but it may want to be revisited for those that do care, down the line. As this PR would net me "0 points", as neither of the tags are used.

Unrelatedly, @Crazylemon64 I'd like to get Delta up to date with the modern codebase, as many pathing refactors have happened since it was last updated. What is the likelihood of this getting a testmerge to test once completed? Ultimately, there is no point me putting in the work if its going to still be sitting there in September 2019....

**Comment by Crazylemon64** [comment]
It's not automated - you can cite this PR, and as a human with a thinking brain instead of an automated system, I would be able to make a decision on it.

as for the delta PR, I'll bring up a testmerge with the heads.

**Comment by SamHPurp** [comment]
Also after sleeping, I've realised the mis-understanding.

I wasn't referring to the Feature Freeze @Crazylemon64 , I was referring to this: https://contrib.nsscyberiad.net/

**Comment by Crazylemon64** [comment]
Ah, yes, my apologies. Things are more clear in that context.

**Comment by Ty-Omaha** [comment]
@SamHPurp faxe locations dont show the captains office, IAA or NTR in the fax panel
https://i.imgur.com/bszEK0T.png

**Comment by SamHPurp** [comment]
@Ty-Omaha Fixed.

Please test merge (or just merge) :)

**Comment by SamHPurp** [comment]
Bizarre. Apparently changelogs can be too long. This isn't showing in game @variableundefined @Fox-McCloud etc

**Pull request merged**
