### PR TITLE
Duct Tape

### PR DESCRIPTION
**Pull request by tigercat2000**
Baystation12/Baystation12#7212
This commit ports Duct Tape from bay, alongside a few other changes for
our own code.

Bay12 Features:
 - You can tape paper to.. anything basically, like a sticky note.

Changes from Bay12:
 - Tape is a stack now, and has 10 uses per roll.
 - The guitar recipe now calls for 5 pieces of tape.

It can be found in the following places:
 - Spread randomly around the map, mostly public-accessable places.
 - Cargo, paperwork crate

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Can we use it as a ghetto muzzle?
I would be very happy if we could.

**Comment by tigercat2000** [comment]
@Spacemanspark no :p

but you are actually the third person to ask, and that worries me

**Comment by Spacemanspark** [comment]
Hippie station has that feature.
It would be VERY nice to have.
I :+1: this anyways.

**Comment by Robertha89** [comment]
Can you tape a KICK ME not to the captain now?

**Pull request merged**
