### PR TITLE
Make the L6 shoot .308 win rather than 5.56x45mm

### PR DESCRIPTION
**Pull request by shazbot194**
This is a remake of my PR that makes the L6 shoot 308 rounds. This has no mechanical change, but makes it so you can't have a situation where you can have 5.56 ammo that can't load into a 5.56 gun. The reason why its not 7.62 like it originaly was is because we already have 2 different 7.62s, 7.62x54rr and 7.62x38mmR, and adding in 7.62x51mm could be rather confusing to someone who isn't gun/ammo savvy.

:cl: Shazbot
Change: The L6 ammo is now labeled correctly, as it has always been shooting .308 rounds. In other news, Steve, who was a part of the arms dealing wing of the Gorlex Marauders, has been fired for incompetence with a labeling machine.
/:cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Fucking  Steve. Messing up everything.

**Comment by shazbot194** [comment]
So I have to ask, do I need to say a PR is ready for review when it's ready to be merged? or is it assumed when I don't have any reference to it being a [WIP].

**Comment by taukausanake** [comment]
@shazbot194 Say it's ready to review. And just mass spam @Fox-McCloud @tigercat2000 and @Crazylemon64 because they got nothing better to do :)

**Comment by shazbot194** [comment]
Well @Fox-McCloud , @tigercat2000 , and @Crazylemon64 , This pull is ready to review.

**Comment by shazbot194** [comment]
So, any news or updates @Fox-McCloud , @tigercat2000 , or @Crazylemon64 ?

**Comment by Ralta** [comment]
Some day, there will be a response to this PR. It may not be today, it may not be tomorrow. It may not be 2017, but someday...

**Comment by shazbot194** [comment]
So @Fox-McCloud , @tigercat2000 , and @Crazylemon64 , another week another ping, any news on this PR?

**Comment by taukausanake** [comment]
@shazbot194 I know I said to spam, but it also might be good to just wait now. At most, maybe once or twice a week. Apparently there are things going on keeping everyone busy.

Welcome the to contributor waiting game :)

**Comment by Fox-McCloud** [comment]
This has no mechanical advantages and really doesn't have a code advantage either--furthermore, from a "realism" standpoint, these bullets are not exactly interchangeable. Hypothetically? Theoretically? Yes, but they're different bullets, as their core, with different pressures when fired---and aren't really *meant* to be fired out of a gun that's not designed for them.

For this reason, we're closing this.

**Pull request closed without merging**
