### PR TITLE
Reworks the Snow Biodome Ruin

### PR DESCRIPTION
**Pull request by Sirryan2002**
## What Does This PR Do
Adds some more stuff into the lavaland snow biodome ruin. Additionally adds a few journal entries for players to read and enjoy. 
Most notably the right area was turned into an altar thing and some blood/gore was added.

Secondly, I've renamed the "Eskimo" skeletons into just Undead Artic Explorers and changed the way the subtype is named.

This is my first mapping PR

## Why It's Good For The Game
The Snow biodome could be a bit more interesting story wise so I've decided to give it some flavor. If you read into the journal entries I think you'll find it rather interesting as it revolves around the story of a couple.

As for the name changes for the skeleton simple mob... "Eskimo" is viewed as a pretty racist term by the Inuit people and it's high time that we phase its use out of our code base. Since I was removing a _"thematic"_  (barely) part of one of our ruins I compensated by adding some story into it.

## Images of changes
Biodome

I've tested this and there were no runtimes
## Changelog
:cl:
tweak: Snow skeletons are now referred to in game as "Undead Arctic Explorer"s
tweak: reconfigured snow biodome ruin and added some story elements to it
/:cl:

### CODE REVIEW

**Comment by Wojz** [comment]
Could put railings for that "bridge" since we got those now. Make it look like an actual bridge.

**Review by variableundefined — APPROVED** [review]

**Comment by Denthamos** [comment]
Hrm, a source of food and chainsaw are removed from this however?  That would effect both ash walkers and stranded hermit more with that and do not see the point of removing some loot and items from the ruin entirely like that.

**Comment by Sirryan2002** [comment]
> Hrm, a source of food and chainsaw are removed from this however? That would effect both ash walkers and stranded hermit more with that and do not see the point of removing some loot and items from the ruin entirely like that.

Did not realize I removed those by accident 💀. I'll get them readded tonight.

**Review by S34NW — APPROVED** [review]
Mapping is fine

**Comment by Samman166** [comment]
Nice to see the change from Eskimo in time for truth and reconciliation day

**Comment by variableundefined** [comment]
Slapping a DNM Tag until the chainsaw and freezer is readded as per Denth's request

**Comment by Sirryan2002** [comment]
Requested changes added, it is ready to merge.

**Pull request merged**
