### PR TITLE
Adds Nanotrasen Hospital ship, Updates admin shuttle, adds admin shuttle templates system.

### PR DESCRIPTION
**Pull request by EvadableMoxie**
Recreation of #11162

Adds the Nanotrasen Hospital Vessel Asclepius.  This ship can be spawned via the shuttle manipulator to replace the Admin shuttle.

The admin shuttle has also gotten a bit of love. It now has a name in game, uses a navigation computer to jump to specific locations, and access requirements have been changed from admin to ert. Tiny fans have been added to the airlock to support the custom location functionality.

The new 'admin' category on the shuttle manipulator:

shuttlemanip2

Often, the destruction of Medbay functionally ends a round, or worse, when the round is not ended dead players no longer have a way to reenter the round.  The Asclepius gives admins a tool to essentially restore the station's ability to tend to crew and get them back into the round.  This is useful for when they want to keep a round going, or for situations where evaccing isn't viable, such as terror spiders or blobs. As this is an administrative tool that can only be deployed by the admins, normal balance issues are less of a problem.  Even so, I have tried to make the ship fairly balanced by making it slightly inferior to the actual medbay in terms of resources.

The Asclepius can transit to the station and dock at the southern arrivals port.  Additionally, it is outfitted with a navigation computer which allows it to jump to custom locations on z1, z3, z4 and z5 (The Cyberiad, Telecomms,  Construction Site and Mining Asteroid).  ERT access is required to jump the ship.

The Asclepius also has a keycard authentication device and comms console, allowing it to function somewhat as a mobile command center, though lacking most of the terminals the bridge does.  It lacks weaponry, though it does have two wall chargers in the command center for recharging the weapons of the ERT medics that crew it.

The ship itself is a functional medbay, featuring a cloning room with a cyrotube, two operating rooms, a chemistry room with 2 chem setups and a general area with 2 cryotubes and 2 sleepers.  There is a Pan.D.E.M.I.C 2200 in the command center for producing vaccines from anti-bodies, but it has none of the equipment for developing viruses that the Cyberiad does.  It also completely lacks a genetics department. There is no wine for producing SR (ERT medics have omni), so the crew will need to scavenge for it. All of the equipment uses stock parts.  If the crew want upgrades they'll need to get them from science.

In terms of equipment, the ship has 2 Nanomed vendors, IVs, Blood, Medkits, Radiation suits, bio suits, two medical hardsuit storage units (CMO access required), and some general equipment such as medical belts and basic health huds.  There is one wall mounted defib unit in the main area, and 1 normal defib in each of the ORs.  The main area has a cell charger for recharging the defib units. The external windows have shutters, and the airlocks have blast doors. These can be toggled in the command center using ERT access.  Overall, this is a bit less than what the actual medbay gets.

The chemistry room and operating rooms require Chemistry and Medical Doctor access respectively. The command center requires Bridge access. The ship itself, cloning, and the main treatment area do not require access. It's expected that the Cyberiad crew will help man the ship, with a few ERT medics to assist, hence the access requirements.

The southern airlock at arrivals has been extended 1 tile west so the ship can dock without blocking disposals.  The dock at CentCom has been extended 1 tile east and 2 tiles south.  This does not interfere with the emergency shuttle docking.

The shuttle has cameras installed on a separate network. The AI can access this network at all times, but as the shuttle is surrounded by walls while at CC it cannot see into any other area of CC while the shuttle is docked in the default location.

**Images of sprite/map changes (IF APPLICABLE):**

The NHV Asclepius:

NHVAscl

Arrivals southern docking port, after map changes:

AsclDockingAfter

Centcom docking port, after map chances:

Asclcentcomdockingafter

The updated admin shuttle:

argos

Note: This is my first PR so please let me know what I am doing wrong.

**Changelog:**
:cl:
add: Added the Nanotrasen Hospital Vessel Asclepius, able to be deployed by admins.
tweak: Admin shuttle now requires ERT clearance instead of admin clearance.
tweak: Admin shuttle now has a navigation computer and tiny fans at the airlock. 
/:cl:

### CODE REVIEW

**Comment by Quantum-M** [comment]
I don't think the shuttle should have cameras, since, if there's no one with the relevant access, they can break through the windows.

Also, if the cameras are the same as the ones in the station, a traitor AI could use the camera upgrade ability, which gives x-rays to cameras, and look into areas they are not supposed to look at (e.g other admin rooms).

**Comment by EvadableMoxie** [comment]
Since the admin shuttle is the default, the AI cannot access the camera unless the admins spawn the ship.  If they do, it's probably going to be used.  If the admins spawn it and decide not to use it, they can always despawn it again by swapping it out for the default shuttle.

In the worst case, the most the AI could see is the cargo shuttle come and go and the little medbay south of where the emergency shuttle docks.  It's far enough away from the Special Operations area that it wouldn't be able to get any intelligence on ERTs/DSes which is really the important thing.

**Comment by taukausanake** [comment]
Don't give shuttles cameras. They have no place on shuttles, not even if they are meant to dock to the station. And it doesn't matter if the ship isn't spawned in or not

**Comment by EvadableMoxie** [comment]
> Don't give shuttles cameras. They have no place on shuttles, not even if they are meant to dock to the station. And it doesn't matter if the ship isn't spawned in or not

Why is that?

**Pull request merged**
