### PR TITLE
Purging the wishgranter

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Removes the wishgranter from the code. It was already unused because of it being able to be cheesed easily and just being unbalanced, but this removes it from being used.
image
This is the ruin which is disabled currently. You can easily get in via using some bluespace crystals and trusting RNG.

## Why It's Good For The Game
Nobody uses it, might as well save some space on the repo.

## Testing
It compiled, tried to spawn stuff in, couldn't spawn in the wishgranter.

## Changelog
NPFC

### CODE REVIEW

**Comment by DGamerL** [comment]
I saw the unit tests fail, will fix tomorrow

**Comment by spacegeese** [comment]
what even WAS the wishgranter, sounds epic

**Comment by Carthusia** [comment]
> what even WAS the wishgranter, sounds epic

Basicly if you managed to reach it, it turned you into an antag with hulk, laser eyes and the objective to kill literally everyone.

it was super easy to cheese with bluespace crystals

**Comment by ItsMarmite** [comment]
But what about.... superheroes?

**Comment by DGamerL** [comment]
> But what about.... superheroes?

Adminbuse those as you wish

**Review by AffectedArc07 — APPROVED** [review]

**Review by Henri215 — APPROVED** [review]
Lewcs good to me, someone pls spawn this for me before this is merged :(

**Review by Burzah — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
