### PR TITLE
Puts drinks in one file, removes arbitrary temperature adjustments

### PR DESCRIPTION
**Pull request by Inadvizable**
## What Does This PR Do

`drink_cold.dm` is gone, non-alcoholic drinks are now in one file.
Drinks no longer arbitrarily adjust your temperature regardless of the drink's actual temperature.

## Why It's Good For The Game

- Not having to guess which file a drink is in is good, especially since it did not really strictly follow any logic before (iced cocoa wasn't in `drink_cold.dm` for example).
- Drinks obeying laws of physics instead of -50 degree coffee warming you (after it cools you at the same time...) is good.
- Using coffee for EVA purposes makes no sense in character.
- Slime people skipping their one real weakness with a vendor drink is silly.

## Testing

1. Spawn in a bunch of drinks, check that they all contain their right reagents.
2. Check bar dispensers and notice they all contain their correct reagents and work.
3. Drink them, notice that nothing weird happens.
4. Drink a bunch of coffee, jump into space with internals on, freeze to death.

## Changelog
:cl:
tweak: Drinks such as coffee no longer change your temperature arbitrarily.
/:cl:

I'm sorry Rurik.

### CODE REVIEW

**Comment by RagingLemons1** [comment]
-1 if this ends up nerfing the classic firesuit n coffee ghetto spacesuit. Just make it so that drink temp affects the temp the drink modifies your temp by.

**Comment by Inadvizable** [comment]
> -1 if this ends up nerfing the classic firesuit n coffee ghetto spacesuit. Just make it so that drink temp affects the temp the drink modifies your temp by.

This already is the case. 
And yes it will nerf the classic firesuit n coffee ghetto spacesuit. Don't see why that should be possible.

**Comment by Leanfrog** [comment]
> -1 if this ends up nerfing the classic firesuit n coffee ghetto spacesuit. Just make it so that drink temp affects the temp the drink modifies your temp by.

Space should be dangerous, a drink you can get anywhere on the station for basically nothing shouldn't nullify 1/3rd of the danger that space presents as well as make any attempts to use cold as a weapon pointless.

**Review by hal9000PR — APPROVED** [review]

**Comment by hal9000PR** [comment]
I am not sorry rurik

**Comment by Rurik123** [comment]
Im still upset

**Pull request merged**
