### PR TITLE
[Chemistry] Adds in Ether

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Got this from a closed PR on TG.

- Adds in Ether
 - Ether is pretty much like morphine only it's (1)not addictive (2) doesn't give you a speedboost (3)has a recipe.

Related
- Replaces *most* instances of morphine with ether (exceptions morphine bottles in nanomeds and supply packs).

This gives medical a way to knock people out without getting the the patient high as a kite or repeatedly taking damage from addiction; it also means that various things that use morphine for knockout purposes don't have the side effect of inducing crippling OD/addictions (ie: spiders, vox dart guns, etc). It can also be produced, so there's no fear of it running out in the middle of the shift.

### CODE REVIEW

**Comment by Mijhead** [comment]
I'd personally keep the morphine in the liberty caps; They're meant to get you high as a kite, alongside the space drugs in them. It also gives medical more reason to work with botany if they need more morphine.

**Comment by FalseIncarnate** [comment]
I'm with mij on this one. Leave morphine in the caps, otherwise :+1: on having an actual sedative that doesn't hurt patients

**Comment by Fox-McCloud** [comment]
Like...man, I don't like think that's even a thing to just eat all the caps of stuff mannn like whoahhhhh....


(re-added morphine to the hallucinagenic liberty caps).

**Comment by KasparoVy** [comment]
Don't kill morphine liberty caps :(. Botany is 4 durgz

Yay ether.

**Comment by Fox-McCloud** [comment]
Morphine was re-added to liberty caps, @KasparoVy

**Pull request merged**
