### PR TITLE
Admin verb mega update

### PR DESCRIPTION
**Pull request by SteelSlayer**
**What does this PR do:**
As per @Kyep's changes wanted page on discord, and from what he personally told me to update, I've tweaked/removed/updated quite a few admin verbs. Now obviously I took some liberty in how I changed *some* of these verbs. So if any of the staff want me to do something I did here differently, just tell me.

Preview of the new combined "List SSDs and AFKs" verb. Two seperate lists, one window
ssdafk

Preview of where the "resolve all ticket" buttons are now located:
tickets
This button will be visible to mentors in their mentor ticket window but since it calls the admin verb, they won't have the permissions to actually use it and will get a message stating so. The "resolve all" button is also present in the admin ticket window.

**Changelog:**
:cl:
tweak: The "Show Player Panel" verb is now right click only
tweak: The "C.M.A. - Admin" verb is now right click only
tweak: The "C.M.A. - Self" verb is now right click only
tweak: The "Check Contents" verb is now right click only
tweak: The "Freeze" verb is now right click only
tweak: The "Freeze Mech" verb is now right click only
tweak: The "Jump to Turf" verb is now right click only
tweak: The "Update Mob Sprite" verb is now right click only
tweak: The "List SSDs" and "List AFKs" verbs have been combined into one verb named "List SSDs and AFKs"
tweak: The "Resolve All Open Mentor Tickets" verb has been moved inside the mentor ticket interface window
tweak: The "Resolve All Open Admin Tickets" verb has been moved inside the admin ticket interface window
tweak: Increases the width of the new "List SSDs and AFKs" window a bit
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Why remove player_panel exactly? Thats useful for bringing up someones panel if you arent near them. The new one is horrible to use, hence why the old one was kept

**Comment by SteelSlayer** [comment]
I was under the impression "player panel new" was better. What's wrong with it?

**Comment by dovydas12345** [comment]
There's a new version which is much better and that old player panel is not used.

**Comment by Fox-McCloud** [comment]
TG is still actively working on stickybans and ways to fix it/get around its issue.

As long as a competent codebase is working on 'em, I don't want them gone.

**Comment by Markolie** [comment]
While you're at it, could you double the width of the SSD/AFK menu? Right now it always requires scrolling to the right, I believe.

**Comment by SteelSlayer** [comment]
Ok, re-added sticky bans and the player panel code and verbs. Also increased the width of the List SSD/AFK window a bit

**Comment by MrMagolor** [comment]
Somewhat unrelated; but I feel like the Jump-To-Ruin verb should be given to ghosts, since ruins aren't usually in the teleport menu.

**Comment by Spacemanspark** [comment]
Don't really see a need for ghosts to have such a button

**Comment by MrMagolor** [comment]
>Don't really see a need for ghosts to have such a button

Mostly convenience. On the flip side, why does that button have to be admin-only?

**Comment by Sihsse** [comment]
> Mostly convenience. On the flip side, why does that button have to be admin-only?
Probably for the opposite reason why this would be an incredibly bad idea to give to ghosts. Not very keen on wondering how a lavaland spawned role managed to get to some ruins immediately either by luck or abusing a tool to metagame.

**Comment by MrMagolor** [comment]
>Not very keen on wondering how a lavaland spawned role managed to get to some ruins immediately either by luck or abusing a tool to metagame 

You can already do that just by being a ghost. Not condoning metagaming, just saying that this would not add in any new behavior.

**Comment by Sihsse** [comment]
> You can already do that just by being a ghost. Not condoning metagaming, just saying that this would not add in any new behavior.

No new behavior, just exacerbates an existing one with no actual net positive aside from mild convenience for the few players who want to hang out at a ruins location. Cons outweigh the pros in this situation.

**Comment by Ty-Omaha** [comment]
Oh that's funny, the way you worded the CL makes it sound like you have to right click the verb in the admin tab.

**Pull request merged**
