### PR TITLE
Removes Unused Script

### PR DESCRIPTION
**Pull request by Fox-McCloud**
I missed this when I purged the text to speech system (or rather what remained of it) years ago.

Completely unused and all the other necessary files for it are gone.

### CODE REVIEW

**Comment by Aurorablade** [comment]
AIEOUAIEOUAIEOUR
BRBRBRBRBRBRRRBRBRBRBRBRBRBRBBRBRBRBRBR

**Comment by Allfd** [comment]
I remember when this was a thing.

**Comment by alexkar598** [comment]
Why was it removed?

**Comment by Spacemanspark** [comment]
Swoi swoi swoi John madden John madden

**Comment by tigercat2000** [comment]
RIP 😢 🖖

**Comment by taukausanake** [comment]
Wait, so what was this?

**Comment by tigercat2000** [comment]
@taukausanake A few years ago we had like two days to a week where mobs speaking would generate TTS noise and blast it into the ears of everyone who can hear them. It performed hilariously badly and the voices were headache inducing, so it quickly went from "everyone hears it" to "preference option" to "reverted". It wasn't reverted very well, though, it was just manually stripped out- this script is the only thing left.

**Comment by taukausanake** [comment]
I kind of thought how Mumble would work with SS13, distance based VoIP. Having people talk to each other is dangerous though, especially if you want to log what is said. Still interesting to think about though, real-time screaming of someone getting robusted

**Comment by alexkar598** [comment]
I would only see the hilarious image of looking at someone with headphones screaming"Why are you killing me" at their screen

On 2017-12-02, at 9:28 PM, "Ronald T. Mullins III" <notifications@github.com<mailto:notifications@github.com>> wrote:


I kind of thought how Mumble would work with SS13, distance based VoIP. Having people talk to each other is dangerous though, especially if you want to log what is said. Still interesting to think about though, real-time screaming of someone getting robusted

**Pull request merged**
