### PR TITLE
Remakes PR #17569, gives all special armours full body coverage

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Revives PR https://github.com/ParadiseSS13/Paradise/pull/17569 with new sprites and a few differences.

Changes bulletproof armour to have full body coverage like riot armour, its protection values have been tweaked and lowered to 50% protection.

Adds the ablative trenchcoat which replaces the ablative armor vest in the armoury, the trenchcoat has full coverage, a 50% deflection chance, a flash proof visor and 50% las/eng protection.

Traitors now need to steal the ablative trenchcoat instead of the ablative armour vest.

**there's a map edit in here for the trenchcoat**

## Why It's Good For The Game
Please read PR https://github.com/ParadiseSS13/Paradise/pull/17569. I did a good job explaining why this is a good idea there and it was well received.

As for the traitor objective changes it was essentially free greentext if you were in cargo or had access to cargo, making it so that you have to steal the limited trenchcoat in the armoury is a good thing and brings it more in line with other steal objectives.

## Images of changes

Original sprites from BS12/TG, species edits by me

PR1

image

## Testing

i shot stuff with muh guns

## Changelog
:cl: Bmon
add: Adds the ablative trenchcoat to the armoury replacing the ablative vest. It has a 50% reflection chance and 50% laser protection along with full limb coverage and a flash proof hood. Sprite from TG!
tweak: Traitors now need to steal the ablative trenchcoat instead of the ablative vest.
tweak: Bulletproof armour now has full limb coverage. Its ballistic protection values have been lowered to 50%. New sprite from Baystation!
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
Drask are banned from using the Ablative Drip, based as hell.

**Comment by Bm0n** [comment]
edited the vox sprite to match the human one more closer by the arms

image

**Comment by Bm0n** [comment]
I based the misc armour stats for bulletproof armour off my old PR which were a bit outdated and didn't account for the armour refactor. This should be fixed now.

**Comment by matttheficus** [comment]
Tarkov Leg Meta begone 🦀

**Review by hal9000PR — APPROVED** [review]

**Comment by Bm0n** [comment]
the trenchcoat accounts for the garment bag existing now

**Pull request merged**
