### PR TITLE
Another buff to radio jammers

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Gives another spin to #19241
Headsets with syndicate encryption key are protected from jammer effects.
Jammer replace_rate has been increased (50 --> 70)
## Why It's Good For The Game

jammer
The current scramble rate isnt enough to prevent the location or traitor name from being exposed to the public (even worse if the target is wounded), this buff should be enough to make most messages not that readable anymore.
## Images of changes

jammer_buff

## Testing

- tested while using syndie keys, was not affected.
- tested jammer with common keys, see images of changes.
## Changelog
:cl:
tweak: Headsets with syndiekeys are protected from jammers
tweak: Buffed jammer scramble rate
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
Oh wow that is a lot... might be good to tone that down a tad

**Comment by S34NW** [comment]
I think this is better, you shouldn't be at the mercy of a 50/50 RNG as to whether they get a specific message out or not

**Comment by OctusGit** [comment]
> Oh wow that is a lot... might be good to tone that down a tad

That's kinda the point of the jammer

**Comment by GDNgit** [comment]
> > Oh wow that is a lot... might be good to tone that down a tad
> 
> That's kinda the point of the jammer

The point of the jammer is to reduce response time, not outright remove the threat of it. Something like 65ish might be better.
The provided screenshots show this being an issue, with the text being nigh indecipherable

**Comment by Henri215** [comment]
> > > Oh wow that is a lot... might be good to tone that down a tad
> > 
> > 
> > That's kinda the point of the jammer
> 
> The point of the jammer is to reduce response time, not outright remove the threat of it. Something like 65ish might be better. The provided screenshots show this being an issue, with the text being nigh indecipherable

I tested different values and i think that <=70 keeps the problem of making it too readable.

**Comment by GDNgit** [comment]
> > > > > > Oh wow that is a lot... might be good to tone that down a tad
> > > > > 
> > > > > 
> > > > > That's kinda the point of the jammer
> > > > 
> > > > 
> > > > The point of the jammer is to reduce response time, not outright remove the threat of it. Something like 65ish might be better. The provided screenshots show this being an issue, with the text being nigh indecipherable
> > > 
> > > 
> > > I tested different values and i think that <=70 keeps the problem of making it too readable.
> > 
> > 
> > Could you get us a screenie of it on 70?
> 
> test70
> 
> I tested with 70 before and repeated it again, i would say that with 70 its possible (but rare) to decipher one word sometimes, with 75 its mostly impossible.

70 looks pretty good, it takes some significant effort to get a message across

**Comment by Henri215** [comment]
> > > > > > > Oh wow that is a lot... might be good to tone that down a tad
> > > > > > 
> > > > > > 
> > > > > > That's kinda the point of the jammer
> > > > > 
> > > > > 
> > > > > The point of the jammer is to reduce response time, not outright remove the threat of it. Something like 65ish might be better. The provided screenshots show this being an issue, with the text being nigh indecipherable
> > > > 
> > > > 
> > > > I tested different values and i think that <=70 keeps the problem of making it too readable.
> > > 
> > > 
> > > Could you get us a screenie of it on 70?
> > 
> > 
> > test70
> > I tested with 70 before and repeated it again, i would say that with 70 its possible (but rare) to decipher one word sometimes, with 75 its mostly impossible.
> 
> 70 looks pretty good, it takes some significant effort to get a message across

Will set it to 70 then, if necessary it can be tweaked at a later date.

**Review by S34NW — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
