### PR TITLE
Make ion laws more specie inclusive

### LINKED ISSUE #9125: Add: change ion law from human to crew
**Problem Description**:
Random ion law which says "only assistants and mime are **human**" should be replaced with "only assistants and mime are **crew**" because of species diversity on this server, asimov AI lawset is not utilized, and in turn, this ion law is useless.

**What did you expect to happen**: 
I expected for ai to lynch all non assistant and mime crew.

**What happened instead**:
No lynch ;c

**Why is this bad/What are the consequences:**
An oversight.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Greytide stationwide.

### PR DESCRIPTION
**Pull request by datlo**
Fixes #9125

Replaced instances of "Human" in ion laws by "Crew" to be more compatible with the default Crewsimov and Corporate lawsets.

:cl:
fix: Replaced instances of "Human" in ion laws by "Crew".
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
Nonsense! Ion laws aren't meant to be sensible. Let the long-festered inner specism that every jaded AI gets overtime as it sees the same screeching vox gangs flourish into beautifully interpreted murder!

**Comment by datlo** [comment]
You seem to be mistaken. These laws make the ion laws less sensible by allowing them to actually impact the AI's decision making. Right now if the law is that only clowns are human, the AI won't care, because "human" doesn't mean anything regarding its law. Making most of the ion laws completely pointless. This changes that so that if only clowns are crew, then the AI has to neutralize every single threat to the clown on station. Honk honk.

**Comment by alexkar598** [comment]
Hey,seems to be your first bug fix PR.Always good to have new coders to squash those bugs.However,when fixing an issue,you must put in the description the following
> Fixes #9125 
This is so the issue gets automaticly closed by github once this PR is merged.

**Comment by datlo** [comment]
Thanks, I have added it in the description. Does it work like this or do you need syntax of some sort?

**Pull request merged**
