### PR TITLE
[READY] Delta code alarm sound added

### PR DESCRIPTION
**Pull request by florkeger**
**What does this PR do:**
Adds a nice metalic alarm sound for when self-destruct is being activated

**Reference**
https://streamable.com/qh1xo

**Changelog:**
:cl: kazboo
add: added a nice metalic alarm sound for when the nuclear self-destruct is activated on the station.
/:cl:

### CODE REVIEW

**Comment by MRgaty** [comment]
Does it last that long? Or are you gonna use a shorter version?.

**Comment by taukausanake** [comment]
15 seconds, not _too_ long but maybe 10 seconds would be better. I think you can tell when something runs its course and five rings to me seems to be it

**Comment by florkeger** [comment]
> Does it last that long? Or are you gonna use a shorter version?.



> 15 seconds, not _too_ long but maybe 10 seconds would be better. I think you can tell when something runs its course and five rings to me seems to be it

Hi, thanks for your replies.

The original file was 31 seconds long, the same as the current biohazard 3 sound file. For the purpose of making it not too obnoxious, I just trimmed the file in Audacity to be 15 seconds. It's really not that long and I guess it's pretty good in that way. If need be it can still be shortened by 5 seconds but I guess 15 is just fine. Least better than the biohazard 3 which goes on forever.

**Comment by AffectedArc07** [comment]
It seems too calm for a "the station is about to explode into an atomic burning fireball"

Maybe something like [this](https://affectedarc07.co.uk/CDN/deltakalaxon.ogg) (This is used by Kepler and Citadel, and seems like the kind of shit for an impending explosion)

**Comment by florkeger** [comment]
> It seems too calm for a "the station is about to explode into an atomic burning fireball"
> 
> Maybe something like [this](https://affectedarc07.co.uk/CDN/deltakalaxon.ogg) (This is used by Kepler and Citadel, and seems like the kind of shit for an impending explosion, though you may need to knock 6dB off it)
Hm..

While I like the initial alarm, it seems a little bit too short for my personal likeness. When I think of self-destruct alarms, I instantly remind myself of scenes like from the Alien movies where the echoing melody of the alert just blares through the ship over and over again. While this can only be partially realized in the game without being too annoying (reference to CM13) I guess it's fine where it stands.

I'd probably take it though if it was edited and made a little bit longer.

**Comment by AffectedArc07** [comment]
@florkeger Easy to do in Audacity, just loop the end of the sample, and drop the gain a little

**Comment by variableundefined** [comment]
The alarm here seems to not really fit in with the other sound. I think the version Affected gave is better.

**Comment by variableundefined** [comment]
@florkeger See above

**Comment by AffectedArc07** [comment]
@florkeger Do you need a version thats looped on, that seemed to be your objection

**Comment by florkeger** [comment]
> @florkeger Do you need a version thats looped on, that seemed to be your objection

Since my Audacity skills suck, yes, a looped version with the beeping at the end a little longer.

**Pull request merged**
