### PR TITLE
Ports Citadel's Airlock Sounds. Take 2

### PR DESCRIPTION
**Pull request by razekpraxis**
What it says on the tin. Only for real this time.

Signed-off-by: Razek <megamattman2234@hotmail.co.uk>

### CODE REVIEW

**Comment by razekpraxis** [comment]
ok good it didnt include my other pr. note to self. only make branches from master

**Comment by tigercat2000** [comment]
literally just don't like the sounds here
they sound way out of place compared to the other airlock sounds

**Comment by razekpraxis** [comment]
i think they sound a lot nicer, imo. more crisp, they have more weight.

**Comment by tigercat2000** [comment]
that's exactly why there is a comment section and reactions :tiger:

**Comment by razekpraxis** [comment]
Kinda douchey to +1 your own pr

**Comment by Spacemanspark** [comment]
I'm kinda on the fence about the sounds.
They sound interesting, but at the same time a bit too... bold? I suppose is the word I want to say.

**Comment by razekpraxis** [comment]
I think they're more fitting for airtight, pneumatic doors

**Comment by Iamgoofball** [comment]
why dont you try the /tg/ airlock sounds?

**Comment by Kerroman** [comment]
Original DOOM airlock sounds when!?

**Comment by Fox-McCloud** [comment]
>why dont you try the /tg/ airlock sounds?

I did that, but the airlock closing sound got shouted down.

**Comment by QQCucumber** [comment]
I don't really like the sounds either.

**Comment by Dumbdumn5** [comment]
> Original DOOM airlock sounds when!?

**Comment by razekpraxis** [comment]
Yes, because they are DIFFERENT to the previous ones. Which means they're supposed to sound different. I honestly, genuinely think these both sound nicer and suit the doors way more.

**Comment by Dumbdumn5** [comment]
> Yes, because they are DIFFERENT to the previous ones. Which means they're supposed to sound different. I honestly, genuinely think these both sound nicer and suit the doors way more.

Well aware of that, my comment was simply to say that I dislike them compared to the ones we have currently.

**Comment by QQCucumber** [comment]
I feel like our current sounds are almost perfect, just need the quiet hallway door sound a little louder.

**Comment by Fox-McCloud** [comment]
not going to fly.

**Pull request closed without merging**
