### PR TITLE
Changes the fluffy cuffs description to not mention keeping your SO in line..

### PR DESCRIPTION
**Pull request by 1080pCat**
## What Does This PR Do

Changes the description of fluffy cuffs to not talk about 'keeping significant others inline', and replaces it with mentioning them being itchy. 
## Why It's Good For The Game

We aren't that kind of server.. 
## Testing

Just a description change, but still made sure it did indeed change the description. (it did)
## Changelog
:cl:
tweak: Removed fluffy cuffs mentioning of SO's being kept in line
/:cl:

### CODE REVIEW

**Comment by Gatchapod** [comment]
How am I supposed to keep my SO in line then?

**Comment by Contrabang** [comment]
On valentine's day of all days?

**Comment by OctusGit** [comment]
SOUL REMOVAL DETECTED🚨
SOUL REMOVAL DETECTED🚨

**Review by Sirryan2002 — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]
what on earth were you doing on valentines day

**Pull request merged**
