### PR TITLE
Improves shading on Tajara, adds new markings

### PR DESCRIPTION
**Pull request by Puckaboo2**
:cl: Puckaboo2
bugfix: Fixed a tail gap between the Tajara female's legs. Also removed a stray arm on torsos from east and west states.
tweak: Polished Tajara's shading. Muzzles are more detailed, connect to the body patch, and tails now match body color. Females no longer have white mouths and their muzzles are the same color as their bellies.
rscadd: Five new Tajara markings and ability to customize Tajara to be mono-color with new muzzle marking.
/:cl:

image

Oh, boy, where do I begin with all the problems I see, here? There is a GAP between the female's legs where the tail should be! ((Don't worry, I didn't change the shape of the tail or the animation, this time.) Feet shouldn't be shaded when they are only one pixel wide. The ears are darker than the head. The tail is darker than the rest of the body. I have so much to cover for these little guys, and it's saddening.

Let's start with the colors. I do not even need to explain how unprofessional the amount of near-duplicate colors I see on the original sprites. This is screenshotted from the actual sprite palette from Dream Maker.  There are exactly five duplicate colors, four 3-of-a-kind colors, and one 4-of-a-kind colors. The top palette represents the colors of the current Tajara and the bottom represents the current updated ones I have.
image
Zoom in on the tail. For some reason, 9 acts as the shading for the tail from the north direction, while 11 and 12 act as shading for the tail in the east and west position. I've decided to match the tails' colors to whatever part they connect to and color the border as the same color as the body. 

Now that I have addressed the color issues,, pull all images I show you in in Microsoft Paint and zoom in as I explain what I have fixed. The reason why I asked you this is because some of the changes are very subtle.

Let's start with the heads. I'll target problem areas in bold and explain them.

This is the male's head.
image
The border shading of the ears do not match the rest of the border shading of the body, so I fixed that (which is why human_face.dmi is also present in this PR.) Also, the ears, from the north position, are more dark than the rest of the fur, which does not make any sense as they were not like that in the original Tajara design. I re-shaded the ears and the back of the head to match the rest of the body.

Now, the muzzle. On the front, facing south, it has lost its shading and a little chin that rounds out the muzzle. To fix this, I went to the original sprites for a reference and I matched the shading to it. The muzzle clipped past three masks, which I have added to the Tajara's mask file.
On the sides, there is a dark pixel on the cheek that has no purpose. In fact, it looks like a side mouth. I've removed it, and also an outline pixel to the left of the dark pixel (the mouth on the muzzle)
 

Now, let's look at the female's head.

image

I'm not going to say anything about the ears because they are the same as the male's.

First, the shading on the side of the face from the south position is inverted. Second, The female's mouth has a pink dot and this is an issue because when people make female Tajara with lighter colors, that pink dot ends up looking like a tooth and the end result is a buck-tooth hamster Tajaran. Credit to Sidecat for my daily dose of lols for the hamster comment.
Third, and most obviously, female muzzle, from the side, not only has unsightly speckles of dark fur, but the color of the muzzle marking flare does not match the color of the belly patch (Don't believe me? Look at the full body on the first image,) nor does it have the shading the male has. I shaded the muzzle flare with an outline so it is still obvious the marking is different than the male's, but it does not reduce the surface area of the muzzle.

Let's look at the bodies, now.

tajara torsos

The reason why the flesh is darker than the original is because the flesh color does not stay the same when people have lighter Tajara. For example, my pure-white speshul snowflek has pure-white fur and her resulting flesh is a light pink.

Now, someone please tell me why the female looks exactly the same as the male? I'm not joking; there is no pattern difference or body shape difference from male to female. To fix this, I've used the human models as references and gave the females some hips from the north and south state. I have honestly attempted to give females a different body patch than the males, but they ended up looking they had a giant dick plastered on their chests no mat
tajara torsos
ter what I did. I can try again, if you want, though.

What I COULD do, however, was give the upper chest, below the neck, a little bit more shading so the muzzle would connect with the patching on the chest, but not too much. I also gave the kitties some shoulder blades and armpits like humans have. But, the sides... 

image

Ahh, the infamous dangling arm when the thing should have been amputated. I removed it, as you can see.

I think I am pretty much done explaining the flaws of Tajara. In other news, I have added some markings to Tajara.

markings

No, we had none of those markings before. And YES, YOU CAN HAVE A MONO-COLOR TAJARA. Angora kitties unite!

In game kitties
examples

New tail animation
ezgif-1-0df9ece5a9

Well, that's it! Also, maintainers, I would appreciate you including me in your conversation while deliberating on merging the sprites, please. I can make changes as you wish.

### CODE REVIEW

**Comment by Necaladun** [comment]
The defined breasts on the tajara female rule this right out for me.

**Comment by LightFire53** [comment]
Female taj no longer have a thigh gap. WTF, are all Tajaran supposed to conform to your definition of beauty? #triggered /s

**Comment by Puckaboo2** [comment]
@necaladun They don't have breasts. At all. I didn't modify anything in the chest. All I did was give them the same kind of waist humans do. If I must, I can change it back to what it was before.

@LightFire53 I hope you're joking... That isn't a thigh gap... That's a tail gap. That's where the tail should be.

**Comment by MarcellusPye** [comment]
I will admit, having anatomy that obeys the laws of physics is part of my artificial beauty standards...

**Comment by LightFire53** [comment]
@puckaboo2 I am joking, yes :P

I think they look awesome.

**Comment by Puckaboo2** [comment]
@LightFire53 Ah, I was hoping you were joking. Thank you so much. It means a lot, really.

**Comment by taukausanake** [comment]
Need boobies. Otherwise this looks nice.

Any chance of a six-pack for catbeasts too? :stuck_out_tongue:

**Comment by Birdtalon** [comment]
A nice improvement for Tajaran.

**Comment by Aurorablade** [comment]
I have to agree with neca here. otherwise i am unsure on it and i play a taj.

**Comment by Puckaboo2** [comment]
@Aurorablade I have no problem with making the female's body shape the same as the male's, again, of that's what people really want.

**Comment by Birdtalon** [comment]
I don't see any defined boobs? The chest looks the same as before.

**Comment by Puckaboo2** [comment]
@Birdtalon I agree, but, unfortunately, Necaladun, I believe, (I dunno for sure,) outranks even the maintainers for these decisions as he is a head admin. If I must, I will make female Tajara look like this from the front and back:

image

Same body structure as the male.

**Comment by ktoma36** [comment]
Its... one pixel on either side of the waist for the female body that has been pushed in. Its not giving the female defined breast its giving them more of a slender body shape. I like the slight difference, it adds a little bit more variety between the female and male options.

**Comment by Puckaboo2** [comment]
I have an image of the kitties in game.
image

If you want 64x64 view, open the image up in Microsoft Paint and size 200% (not resize, just the scroller.) Males on left, females on right.

**Comment by IcyV** [comment]
Especially given these are anthropomorphic creatures and not just humans I think it makes much more sense for them to not have defined bodies and for the male and female to have similar shapes. Breasts, difference in torso sizes, and so on feels odd at its core. I'd be a fan of just removing the breasts from both. There's really no good reason for there to be obvious breasts on a furry creature. 

I'm also not too big on the leg shading being different. It makes the legs look...off for some reason. I feel like it implies they're plantigrade rather than digitigrade.

Regarding the head and the ears being lightened, I definitely don't mind that. I do see an issue with the circle of shading that lines the base of the ears and so on though. I think it needs just a little bit more shading extending out rather than being a circle around the head. Not too sure there, just needs something extra.

Overall I like how they were fixed up save for my little nitpicks there.

**Comment by Puckaboo2** [comment]
@IcyV I understand what you are trying to say, and as much as I hate the original chest's design's resemblance to breasts, the males and females don't have breasts; they have pectoral muscles. I don't understand why people are just now pointing out the chests look like breasts and claimed I changed them to look like breasts, when I did not. It's almost insulting. If I really wanted to give Tajara breasts, I would have added nipples. Besides, the chest area has existed like that since before we could make Tajara any color you wanted, and without the indentation of the pecs, the chests look flat and without detail.

On the topic of the size of the waist, female cats are naturally more slender in build and generally a bit smaller overall, while males are more stocky and robust in the upper body, so it makes sense if females are a bit more lithe than the males are.

About the Tajara looking as if they are plantigrade, I'm afraid to burst your bubble, but Paradise said "fuck you" to anatomical logic and Bay lore: Tajara are plantigrade to allow their feet to fit into shoes, where, otherwise, on other servers, Tajara are digitigrade and are only able to wear sandals, slippers, galoshes, clown shoes, and cloth wraps. No offense, if this was laziness on the coders' and iconers' part or an effort to save time, I do not know, but we are set in our ways, afaik. Honestly, I did have a digitigrade design, long ago, but maintainers rejected it.

Finally, the circle on the head is unintentional, but unavoidable; it is the result of shading the sides of the head and adding an indentation to establish a border or shadow between the ears and where they connect to the head.

All in all, I'm sorry if you find any faults in the sprite, but I have done my best to make the sprites as anatomically correct as possible, the shading correspond to modern Para standards and Para lore, and just polish to the best of my ability. You are free to download the sprites, do some edits, and then show me a preview of what you think would look better, but I am warning you ahead of time, in the past, I may have tried to apply some pixel positioning you already had in mind and found the current models I have on display in favor.

**Comment by Puckaboo2** [comment]
Crap. I realized the fix for the tail gap between the female's legs causes the tail to clip into the groin of clothing.

image

Either I add a dot where the female's groin is to compensate for the tail gap, or I just leave the tail gap there. I don't really have any other option than to go for the first.

**Comment by Puckaboo2** [comment]
image
New tail animation, for the win.

**Comment by taukausanake** [comment]
> tail animation

> Not a gif

@Puckaboo2?

**Comment by Rumiluntti** [comment]
Can you post a picture of anything else than grey cats? I smell trouble with the seemingly random shade gutting if you use something else.

**Comment by taukausanake** [comment]
Give us some neons!

**Comment by scrubmcnoob** [comment]
i'm really bad at identifying changes to sprites as i'm not a great spriter, but the i've noticed that you managed to shade a hole where it should be pure white but it's dirtied.
May want to fix that my dude.

**Comment by Puckaboo2** [comment]
@scrubmcnoob I don't understand what you are telling me. Can you drop one of my images and draw an arrow on MS Paint or something? 

@Rumiluntti Most of the images you have seen do not have any markings on them. Changing the color of the Tajara would not change very much.

The PR pics are outdated. I will fix them, tomorrow, and show off a lovely new tail gif on a neon Tajara for you all. I've done some modifications at the maintainer's request and I hope they are satisfactory to your liking.

**Comment by tigercat2000** [comment]
Following a long discussion between the Heads of Staff and Maintainers, it was decided collectively to close this PR. While we appreciate the work put into the creation of the sprites, this is not a change that we believe is necessary for the codebase; not only are the changes themselves minor, they will, in practice, be inconsequential, taking into consideration the average size of the sprites during regular play. In essense, the new sprites would be a net neutral addition, not taking away anything, but not exactly adding anything either.

In addition to this, multiple issues have been pointed out over time in regards to the shading technique and shading quality, which have alternatively led to lashing out against the individuals providing criticism, said criticism being ignored and/or more additions being made contrary to what was requested. Due to the aforementioned reasons, and the overall difficulty in molding the creative process, this PR will be closed

**Pull request closed without merging**
