### PR TITLE
Beginnings of Combat Changes: Ranged Weaponry

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Re-upload of: https://github.com/ParadiseSS13/Paradise/pull/15708 to prevent cross-contamination due to age.

This is the beginnings of the combat work that has been posted in the design doc.

Again, it's impossible to do all this at once, so this starts slow and hits the obvious problem spots first.

This removes all advance tasers from the game and any day-to-day weapons that use electrodes; the only weapons that will have stuns, that will remain, will be pulse weapons, as that's kinda their niche.

This also removes the mind batterer and reworks the energy crossbow. 

Disabler changes:
- New sprite
- Can equip a flashlight to it now

Electrodes:
- No longer have an awkward 1.5 second delay between shots---again, they're really only available on pulse weapons anyhow.
- Re-stating: these only exist on pulse weaponry, turrets, and the turret guns now.

HoS Energy Gun Changes
- Can fire laser, disabler, or ion shots
  - You get 20 disabler, 10 laser, for 4 ion shots; the ion shots are very weak, having an AoE of 0
 
ED-209's
- Use disablers to construct them; they shoot disabler shots now

Mech Disabler
- Nerfed to fire a single projectile

Blueshield Revolver
- Only fires laser and disabler now

Advanced Energy Gun
- Only fires laser and disabler now

Mind Batterer
- Removed from the game

Detective Revolver
- It can no longer stun at all; it just deals damage
  - Go away det-curity. 

LWAP:
- Removed
  - The crew reallyyyy don't need to be given something like this, in my opinion, and it doesn't really fit a solid niche in the space it occupies without kinda sneaking into "like the syndicate rifle only different"
  - The crew will get ion rifles wherever they previously got this
  
Meteorslugs and Frag12 slugs
- Nerfed; won't stun for as long
  - Once crawling is introduced, these will get nerfed even more

Stunslugs
- Nukies can no longer purchase them; still producable from a protolathe though   

Disabler and empty disabler sprites:

img

:cl: Fox McCloud
del: most tasers and electrode shots have been removed from the game; the exception being turrets
tweak: HoS energy gun fires disabler, laser, and ion shots
tweak: nuclear energy gun and blueshield revolver only fire disabler and laser shots
tweak: Mech disabler fires a single disabler shot
tweak: ED-209 now fires disablers
tweak: ED-209 now uses disablers in its construction
tweak: Crossbow deals stamina damage, very briefly knocks down, and causes slurring and blurry eyes
tweak: Detective revolver no longer can stun; it just deals damage
del: Removes LWAP from the game
tweak: Gives the crew ion rifles wherever there was previously LWAPs
tweak: Mime fingerguns now just deals 40 damage; you only get 3 shots, but it recharges twice as fast now
tweak: Nukies can no longer purchase stun slugs
add:  Nukies can purchase meteorshot slugs
tweak: Meteorshot and frag 12 nerfed in stun duration
del: Removes the mind batterer from the game
/:cl:

### CODE REVIEW

**Comment by LordShekelstein** [comment]
Big ups, Fox. LGTM.

**Comment by dearmochi** [comment]
It was approved prior, simply re-uploaded to sort the merge artifacts out. We're

**Review by dearmochi — APPROVED** [review]

**Comment by Jordanstolethepreciousslam** [comment]
Was aranesp changed in previous commits though? 40 stamina heal per tick btw.

**Comment by Dafrek** [comment]
I don't know if replacing detective revolver's stamina rounds with lethal rounds not far from syndie revolver because, "Go away det-curity" is the best tbh, outside of that quality PR imo.

**Pull request merged**
