### PR TITLE
Makes the crew more salty

### PR DESCRIPTION
**Pull request by Aurorablade**
https://github.com/tgstation/tgstation/pull/18150/fileshttps://github.com/tgstation/tgstation/pull/18150/files port as a suicide act

...Act now with suggestion and i might add more suicide acts based on them for other items

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Ahahahaha

:+1:

**Comment by Tastyfish** [comment]
a salt with a deadly weapon

**Comment by Spacemanspark** [comment]
Then John was salt

**Comment by Qinexio** [comment]
Neat, Pet Rocks rip peoples throats open, cable restraints to be used as a noose and make people jam crayons up their noses when they try to suicide with them.

**Comment by Draconic-saint** [comment]
Warning cone: [x] is ignoring the cone's warning! Surely calamity is due!

hatchet/fire Axe: [x] axes themselves the question: "is life worth living?"

**Pull request merged**
