### PR TITLE
Removes Vampire HUD

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes the Vampire HUD.

Been getting complaints about this for a very long time, ranging from:

- It's ugly
- It's difficult to look at
- Hard to know/understand what anything means
- Obscures the view too much

And other similar things. In any event, this removes vampire HUD entirely, the only thing that will be kept is the blood counter display, which has been moved to a new location so it doesn't interfere with other icons:

img

:cl: Fox McCloud
rscdel: Removes Vampire HUD
tweak: moves the Vampire blood counter to a more easy to see location
/:cl:

### CODE REVIEW

**Comment by johannhawk** [comment]
sweet

**Comment by Tastyfish** [comment]
Why isn't the counter just in the status panel?

**Comment by Fox-McCloud** [comment]
>Why isn't the counter just in the status panel?

It is; there's always been a UI element though, though I suspect it was overlooked/hidden by the awful Vamp display, itself.

**Comment by Aurorablade** [comment]
it needs a pretty graphic for it..but thats just meeeeee

**Comment by Spacemanspark** [comment]
We should have that HUD as an actual setting in character preferences, I actually liked that HUD.

**Comment by Kyep** [comment]
Woohoo! I still remember how annoying this thing was when I started playing vamp.

**Comment by Earthdivine** [comment]
Don't suppose we could keep the blood counter HUD element atleast? It looks very Blegh and plain. But yea, :+1: because that stupid HUD kept breaking.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

I'm actually going to switch it over to what the ling chem count uses, once that gets merged; it's a lot clearer.

**Comment by Finalsong** [comment]
I think it was pretty nice personally

**Comment by TheDZD** [comment]
RIP in pieces poorly implemented UI.

**Pull request merged**
