### PR TITLE
Removes the slime friendship & speech buffer system

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Removes the slime friendship & speech buffer system.
Remake of #17562

## Why It's Good For The Game
Have you ever had a round where you come into xenobio after an hour, and the scientist wants to show you a cool trick? The trick of course is to magically freeze your entire game by saying `hi`. Slime talking and the friendship mechanic is a very very costly process
```
/mob/living/simple_animal/slime/proc/handle_speech    9.27
- Data from GDN
```
It's handled poorly, and isn't quite used. 
Also bonus:
> Commanding slimes and what to do/who to attack is a pretty interesting feature, to say the least--I'd hate to lose it when we haven't even tried to optimize it yet.
This was March 2022 - Fox McCloud
I don't think someone is gonna swoop in and optimize this too

## Testing
Spawned in a random slime, saw it walk around and it even emoted a bit. I then hit it and it chased me around, de-aggroing after a while as it should.

## Changelog
:cl:
del: Removes the slime friendship & speech buffer system
/:cl:

### CODE REVIEW

**Comment by Gatchapod** [comment]
Removing speech buffer is absolutely reasonable, but I question the consequences of removing friendship.
This will likely lead to slimes escaping their pens due to xenobiologists who completely ignore the changelog or plainly don't realize they rely on friendship. That is acceptable, I think. They'll have to learn to play xenobiology more carefully.
What I am worried about is the abductors' slime gland, though. The slimes a victim spawns will now be aggressive towards them. To maintain a similar behaviour, perhaps adding the victim to `slime` faction would be reasonable? This might be an idea for a different PR, however.

**Comment by GDNgit** [comment]
> Removing speech buffer is absolutely reasonable, but I question the consequences of removing friendship. This will likely lead to slimes escaping their pens due to xenobiologists who completely ignore the changelog or plainly don't realize they rely on friendship. That is acceptable, I think. They'll have to learn to play xenobiology more carefully. What I am worried about is the abductors' slime gland, though. The slimes a victim spawns will now be aggressive towards them. To maintain a similar behaviour, perhaps adding the victim to `slime` faction would be reasonable? This might be an idea for a different PR, however.

Slimes can still be satiated through hunger

**Comment by Gatchapod** [comment]
> 
> Slimes can still be satiated through hunger

All I'm saying is that a lot of xenobiologists are bad at actually keeping their pets well-fed. They'll have to learn that the hard way, I imagine.

**Comment by Furrior** [comment]
Slime... friends :(

**Review by S34NW — APPROVED** [review]

**Comment by Venuska1117** [comment]
solution? just never leave adult slimes in cages, because only adults can break out, if you are this incompenent, you can always put railings inside cage to prevent them attacking glass.

**Pull request merged**
