### PR TITLE
Adds Jani-ERT, Paranormal ERT, and Gimmick Teams in general

### PR DESCRIPTION
**Pull request by Kyep**
Adds the ability to group-spawn Paranormal and Janitorial ERTs.
As well, as, of course, a group of players with *any other admin outfit*.

To do it, Game Admins and up can use the "Gimmick Team" admin secret.
Then, specify how many players you want, and whether you want to pick manually, or just draw from ghosts. Finally, specify a mission, and the outfit (jani-ert, paranormal-ert, or any other admin outfit).
The selected players will spawn at your location in that outfit, with the mission briefing you entered.

This can be used to:
- Create custom NT teams (jani-ert, paranormal-ert, inspectors, whatever)
- Create custom syndicate teams (agents, infiltrators, strike-squads, whatever)
- Create custom wizard teams (marissa wizard cult, etc)
- And so on.
- This automatically supports any admin outfit added in future.

🆑 Kyep
add: Admins may now spawn 'Gimmick' teams, including Janitorial ERT, Paranormal ERT, and more. Any admin outfit, any mission, spawned anywhere.
add: Paranormal ERT outfit now exists. It acts like a red security ERT, except with focus on fighting paranormal threats.
fix: Janitorial ERT now gets ERT headset, not centcom headset. Also, they now get a survival box, and a flashlight.
/ 🆑

### CODE REVIEW

**Comment by SamHPurp** [comment]
Greater GM freedom 👍

**Comment by Anasari** [comment]
Finally I can recklessly spawn in 50 soviet guys at once

**Comment by KasparoVy** [comment]
BLYAT

**Comment by Spacemanspark** [comment]
Instant solgov teams. Yes.

**Comment by Necaladun** [comment]
Spawning all this shit in is annoying. This makes it less annoying. Less annoying is good.

**Pull request merged**
