### PR TITLE
Adds some new vox_fem words

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
rscadd: Adds the following words to the AI announcer: active, airlock, alcohol, arrival, arrivals, becoming, between, blob, briefing, camp, chair, chapel, closet, cyberiad, declared, detective, diona, dock, docked, docking, docks, drask, drunk, emag, equipment, evacuation, experimentor, gateway, hail, hallway, holoparasite, honk, hull, ian, imminent, interested, intruders, kida, kidan, labor, library, mime, mimes, miner, miners, mining, n2o, nuke, office, op, operational, ops, pod, pods, poly, pun, renault, representative, runtime, scrubbers, sequencer, skree, skrek, skrell, space, spider, spiders, still, stupid, swarmer, swarmers, sword, technology, teleport, teleported, teleporter, teleporting, tesla, tool, unathi, vacant, vault, vents, vulpkanin, weld, window, windows, yet
/:cl:

If you have any word requests, PM me them on discord, or post it here. Don't ping me on discord though, because I don't want to scroll up through a light-year of text.

### CODE REVIEW

**Comment by LittleBigKid2000** [comment]
Where do you get these voice clips from?

**Comment by monster860** [comment]
https://github.com/N3X15/ss13-vox

**Comment by FlattestGuitar** [comment]
I do believe we're lacking words describing Paradise-specific species. Possibly add those as well?

**Comment by Spacemanspark** [comment]
Synthetica. :^)

**Comment by TheDZD** [comment]
"Space Station 13" was available but "space" was not? Wow.

**Comment by LittleBigKid2000** [comment]
This is only tangentially related, but when I try to run the setup script, it says "ImportError: No module named apt". Know how to fix that?

**Comment by QuinnAggeler** [comment]
We could also use:
``blob`` ``swarmer(s)`` ``spider(s)``

**Comment by LittleBigKid2000** [comment]
Fluffy, scaley, squishy, smooth, polymer, metal, butt
Because why not?
Also, nuclear

**Comment by CrAzYPiLoT-SS13** [comment]
Also, delamination, abandon, murder and its variations

**Comment by LittleBigKid2000** [comment]
Why did I spend like nine hours setting up a VM with ubuntu and trying to get the vox thing to work

**Comment by LittleBigKid2000** [comment]
https://www.dropbox.com/s/ju6hu3gxhxe0yq5/vox_fem.zip?dl=0
Here's a zip of the ones I wanted, because adderall is a hell of a drug.

**Comment by QuinnAggeler** [comment]
Could use some basic grammar, too.
The, there, has, had, was, where, when

**Comment by Fox-McCloud** [comment]
@monster860 

Had to give it a listen. The proper pronunciation of Vulpkanin is: Vulp-CAN-inn

You may want to double check some of the words to make sure they sound like they're supposed to; may need to do some fiddling with some to get them to sound right (I know N3X15 had to).

**Comment by LittleBigKid2000** [comment]
I don't see 'fluffy' in there. I'm going to riot.

**Comment by Spacemanspark** [comment]
Can we remove the word "woody" while we're at it.
I'm not kidding, that word is actually in the vox list.

**Comment by taukausanake** [comment]
Afraid AI is going to say, "Woody got wood"? :package: 
I can't think of anything to add, but I'll look at the program all the same

**Comment by LittleBigKid2000** [comment]
>it was merged without my words
[RIOTING]

**Comment by Spacemanspark** [comment]
>It was merged without my words too.

[RIOTING INTENSIFIES]

**Pull request merged**
