### PR TITLE
Botany / Xenobotany Update [Feature][Sprites]

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Largely a port of https://github.com/Baystation12/Baystation12/pull/8038
(Credit to Zuhayr for his hard work on botany)

Breakdown of the port:
- Plant traits have been expanded drastically
 - You want a bio-luminescent tomato that explodes into a cloud of acid
when thrown or stepped on? Or maybe a corn vine that entangles people
and injects them with mannitol and it's harvests can be used as a
battery? Totally possible.
- Adds new random seeds! Replaces the egg-plant seed in the exotic seeds
crate from cargo with 2 of these.
 - Literally random, they have randomly generated stats, chemicals, and
traits. Great for researching, and/or wasting cargo's supply points.
- Plant analyzers can now print off the last scan they recorded, meaning
you can distribute copies of the report to validate your claims of
having the dankest weed on station.
- Potatoes, carrots, watermelons, soybeans, and pumpkins can all be
sliced/diced/carved with ANY sharp object, such as knives, hatchets,
glass shards, and e-swords.
 - This should give the chef a bit more room to make it look like he
actually is doing the work by slicing up fries by hand. The processor
still also works.
- New reagent: Wood Pulp
 - Currently has no use in recipes, but any plant with this reagent in it
can be chopped into planks with a hatchet. Did someone order some
Ambrosia Deus planks?
  - Also, vines with woodpulp are dense. You have been warned.
- Vines now have a tiny little spreading animation. Don't admire it too much though, or you will get floored and buckled by the vines.

image

Now onto the stuff I did in addition to the stuff from Bay.
- Fixed typos where plasma was mistakenly called "phoron" in the port.
(Sorry bay)
- Replaced bay's botany mutation chances with our tiered mutation
system.
- Re-re-added tobacco, space tobacco, tea aspera, tea astra, coffee
arabica, and coffee robusta.
- Updated the juicer and grinder code to accept the new plant system for juicing things.
- Re-enabled the rolling of joints
- Made it possible to hand-roll cigarettes from tobacco / space tobacco.
(A requested / promised addition)
 - Just like with joints, it will inherit any chems in the tobacco, has
the same reagent capacity as a joint, but looks and smokes like a cig
(lasts as long as the cigarettes) with a different name/description to
differentiate it from pre-made cigs.
- Corn can now be juiced in the grinder, in addition to grinding it.
Grinding corn will result in it's contained reagents (like corn starch),
while juicing corn will result in corn oil.
- Re-added the additional plant analyzer information when scanning trays
(displays age, weed level, etc)

Also cleaned up the recipes_microwave.dm file, removing the commented
out recipes that were distributed to the other machines during the
Kitchen Overhaul. Shortens the file a bit and makes it more readable.

image

I probably forgot stuff, so I will add things as I remember them / they
get pointed out.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Iamgoofball** [comment]
Beat me to it :+1:

**Comment by Fox-McCloud** [comment]
Once merged, this should definitely be policy that planting vines as a non-antag in the halls is griefing. It's recently become problematic/annoying for crew to deal with--and this will make it way worse and higher impact for those who have the skill to do it.

**Comment by FalseIncarnate** [comment]
@Fox-McCloud I am tempted to agree with you, though I am also able to easily tweak the spread-rate of vines if needed.

I also want to add scythes to the Janitorial ERT's equipment in place of their plant-b-gone bottles. If the ERT gets called in for the vines, those bottles are gonna empty out really fast, plus the scythe affects a larger area. This will be another PR though, since it needs discussion and will likely also include a buff/fix to plant-b-gone bottles only spraying adjacent tiles and not at range like the space cleaner bottles can.

**Comment by fj45** [comment]
Great job there!

**Comment by Iamgoofball** [comment]
@Fox-McCloud but what if it's friendly omnizine vines

**Comment by Spacemanspark** [comment]
Well, either way, the botanists will end up lynched because everyone will see vines and flip shit.

**Comment by Iamgoofball** [comment]
BUT MY FRIENDLY CLF3 PHLOG VINES

**Pull request merged**
