### PR TITLE
Adds runechat to various things that were missing it (MMIs, soulstones, and more)

### LINKED ISSUE #14994: Brains in MMIs do not speak through runechat
**Issue Description**:
Brains in MMIs do not speak through runechat.

**What did you expect to happen**: 
Brains in MMIs should be able to speak through runechat.

**What happened instead**:
Brains in MMIs do not speak through runechat.

**Why is this bad/What are the consequences**:
People will miss out on what MMIs are saying if they aren't checking the right side chat box.

This is specially bad for brains in MMIs considering they aren't able to do anything else other than talk.

**Steps to reproduce the problem**:
1. Be a brain in MMI.
2. Speak

**When did the problem start happening**:
Runechat probably never added to brains in MMIs.

### PR DESCRIPTION
**Pull request by SteelSlayer**
## What Does This PR Do
Added runechat to:

- MMIs, robotic brains and positronic brains.
- AIs inside of intellicards
- pAIs while they're in "card form"
- Mechs with *any* type of pilot (humanoid, AI, MMI, etc)
- Shades while they're inside of soulstones

**You cannot see the runechat of these things if they're inside of something such as a backpack.**

Fixes  #14994

## Why It's Good For The Game
It easy to miss MMI/robobrain speech because they have no visual indicator of them speaking, not even a chat bubble. People need to have their eyes glued to the chat window or they'll miss what the brains are saying. Sometimes this means they can sit there for quite a while, being ignored. The same can apply for the other items.

## Images of changes
image

## Changelog
:cl:
tweak: Adds runechat to various mobs who didn't have it before, such as all types of MMIs, and shades inside of soulstones
/:cl:

### CODE REVIEW

**Comment by Pyrodes** [comment]
does this affect posibrains too?

**Comment by SteelSlayer** [comment]
Yes it does.

**Comment by Carthusia** [comment]
Does this also apply to soul stones?

The other day when i got sharded, i had no runechat

**Comment by SteelSlayer** [comment]
@Carthusia It does not currently. Might see about included them too.

**Comment by SteelSlayer** [comment]
Updated to include shades in soulstones.

**Comment by Cocacolagua** [comment]
1. does this apply to AI intellicards
2. does this apply if the item is inside a container like a backpack or whatever

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Comment by SteelSlayer** [comment]
@Cocacolagua 
1) No
2) No

**Comment by Carthusia** [comment]
Just remembered a few other things that dont have runechat, Spacepods and Mechs

**Comment by SteelSlayer** [comment]
Further updated to include pAI's in card form, AIs in intellicards, and mech pilots of all kind.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
