### PR TITLE
-tg- style inventory update, stripping update

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit does the following:
 - Updates a few of our inventory procs to -tg-'s latest
 - Nukes the equip_e system from orbit
 - Fancy UI for stripping people now
  - It's fancy.
  - You cannot strip people if they are wearing something hiding that item;
    - ex; Hardsuits prevent you from taking jumpsuits, belts, everything attached to the jumpsuit, etc
 - Nuked fucking kitten ears from their snowflakey bullshit update_icons
   shitty fuck fuck FUCK
  - Kitty ears are not gone, just made 99999999999999999999999% less SHITTTTTTTTTT
 - NUKED FUCKING METAL DETECTORS AHHHHHHHHHHHHHHHHHHHHHHHHHH
 - Snapped @tigercat2000's mind.

pretty

### CODE REVIEW

**Comment by Markolie** [comment]
:+1: x :100:

Also: Nuked fucking kitten ears from their snowflakey bullshit update_icons shitty fuck fuck FUCK. Good riddance.

**Comment by tigercat2000** [comment]
@Markolie the miracle is that my hacky-as-shit use of equipped() and icon_override actually means they maintain full functionality

**Comment by Markolie** [comment]
Please don't bother fixing that, or PR'ing that. Screw those ears.

**Comment by tigercat2000** [comment]
@Markolie fix is already included in the main commit, and I can't be bothered to remove them from the code completely so cest la' vie

**Comment by Spacemanspark** [comment]
Remove cat ears remove cat ears remove cat ears.
Other than that :+1:

**Comment by Nomzosha** [comment]
:+1:

**Comment by Dumbdumn5** [comment]
Cat ears removed from being heavily integrated into code it didn't need to be in and instead just being a cosmetic item? 10/10

**Comment by Fox-McCloud** [comment]
As an addendum, I requested that @tigercat2000 add in custom stripe delay for specific items---after this gets merged, I'll be changing the strip delay on everything to be in line with TG--generally, armor and things like spacesuits will take longer to strip than, say, a regular old grey jumpsuit.

**Comment by tigercat2000** [comment]
yeah, as is, though, it just has two defines as the default- 
[defines](https://github.com/ParadiseSS13/Paradise/pull/2292/files#diff-4fef6bc8c3a87b3b9c5ee4ac6d6d2aa2R107)
[vars](https://github.com/ParadiseSS13/Paradise/pull/2292/files#diff-ac3b89e91ad083b3cb3fdb669006158cR52)

**Comment by Crazylemon64** [comment]
Oh, nice! This is much better than the band-aids I was writing to prevent those nasty NODROP shenanigans! :+1:

**Comment by KasparoVy** [comment]
screw cat ears, rip tiger's mind

Thanks so much for this pr

**Comment by Markolie** [comment]
Please make sure Plasmamen can still be strippped through their suit. Otherwise security won't be able to search them without them burning to death.

**Comment by Robertha89** [comment]
if thickmaterial disallow strip check would fix it, and allow evasuit to be ignored and whatnot.

**Comment by tigercat2000** [comment]
@Robertha89 That's not ideal.

**Comment by Fox-McCloud** [comment]
Just make it so that all plasmamen stuff doesn't hide jumpsuits--same with helmets

Yeah, it's inconsistent with other spacesuits, but it would be better than adding a snowflake check in inventory code, itself.

**Comment by tigercat2000** [comment]
I'm fairly sure that will cause layering issues.

**Comment by Markolie** [comment]
Just as a reminder:
Please make sure Plasmamen can still be strippped through their suit. Otherwise security won't be able to search them without them burning to death.

**Comment by Markolie** [comment]
We'll need to figure something out though: having plasmamen be unstrippable really won't work.

**Comment by Earthdivine** [comment]
>Plasman can't be stripped

Finnaly power to back my 100 karma purchase!

**Comment by tigercat2000** [comment]
Alright after looking at what HIDEJUMPSUIT actually does, it'll probably be fine to just remove
As far as I can tell, it's only uses are:
 - Hiding jumpsuits in examine text
 - Preventing people from stripping the jumpsuit or things on it (obvs)
 - Calling an update_inv_w_uniform on wear_suit being equipped

**Comment by Fox-McCloud** [comment]
@tigercat2000 

I figured that would be alright as the suit later is above the jumpsuit layer.

Yay.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

This ready?

**Comment by tigercat2000** [comment]
@Fox-McCloud yep

**Pull request merged**
