### PR TITLE
Fixes Cerestation Medical Storage disposals bin, also simplifies disposals in Medbay Break Room

### PR DESCRIPTION
**Pull request by SchrodingersWolf**
## What Does This PR Do

Fixes Cerestation's Medical Storage disposals bin - Previously if you tried to throw anything in it it would spit it back out into the room. As a happy side effect this also simplifies the disposals sorter in Medbay Break Room.

## Why It's Good For The Game

There wasn't an issue report for this and it is getting on my nerves, so I thought I would fix it.
Bins not shooting garbage you just thrown inside the bin back at you is good.
Simplified disposals also means an Engineer that has to conduct repairs after the fifth Medbay explosion in a round won't be scratching their head in abject confusion.

## Images of changes

We went from this jumble of disposal pipes that only somewhat works...

Screenshot (758)

To this simple and elegant sorter that works perfectly.

Screenshot (757)

## Testing
Wrapped and tagged crates, then shoved them down Cargo delivery chute and aghosted to follow it.
Repeated for all Medbay locations (Medbay/Medical Storage, Chemistry, CMO Office, Genetics) and CE Office as a control test, ~~got bored out of my mind as Farragus disposals takes forever,~~ confirmed that the crates arrived at their intended location.

Then inhabited a vox and jumped into the Medical Storage and Medbay Break Room disposals bin, confirmed that I arrived at where all vox deserves to be (Disposals).

## Changelog
:cl:
fix: Fixed Cerestation Medical Storage Disposals Bin
/:cl:

### CODE REVIEW

**Review by Henri215 — APPROVED** [review]
Lewcs good to me

**Comment by warriorstar-orion** [comment]
Your merge to master is faulty; Cerestation's map definition includes a key that is not defined, and merge conflict markers remain in the map file.
```
[2024-03-26T21:30:57] Runtime in code/modules/awaymissions/maploader/reader.dm,139: Undefined model key in DMM: gqG. Map file: _maps/map_files/cerestation/cerestation.dmm.
[Mapping] Loaded NSS Farragus in 3.7s
[Mapping] Loading Lavaland...
[Mapping] Loaded Lavaland in 5.5s
[Mapping] Skipping space ruins...
[Mapping] Populating lavaland...
Ruin loader finished with 60 left to spend.
[Mapping] Successfully populated lavaland in 0.3s.
[Mapping] Initialized within 10 seconds!
[Atoms] Initializing...
[Atoms] Initializing atoms...
## WARNING: HEY, LISTEN!!! Merge Conflict Marker detected at Medbay Break Room (196,115,2)! Please manually address all potential merge conflicts!!!
## WARNING: HEY, LISTEN!!! Merge Conflict Marker detected at Medbay Break Room (196,115,2)! Please manually address all potential merge conflicts!!!
## WARNING: HEY, LISTEN!!! Merge Conflict Marker detected at Medbay Break Room (196,115,2)! Please manually address all potential merge conflicts!!!
## WARNING: HEY, LISTEN!!! Merge Conflict Marker detected at Medbay Break Room (196,114,2)! Please manually address all potential merge conflicts!!!
## WARNING: HEY, LISTEN!!! Merge Conflict Marker detected at Medbay Break Room (196,114,2)! Please manually address all potential merge conflicts!!!
## WARNING: HEY, LISTEN!!! Merge Conflict Marker detected at Medbay Break Room (196,114,2)! Please manually address all potential merge conflicts!!!
```

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
There's a stray disposals pipe
2024_04_03__11_07_14__paradise dme  cerestation dmm  - StrongDMM

**Comment by S34NW** [comment]
!merge_upstream

**Review by warriorstar-orion — APPROVED** [review]
LGTM (Less Garbage Trashing Medbay)

**Review by Burzah — APPROVED** [review]

**Pull request merged**
