### PR TITLE
Gender neutrality

### PR DESCRIPTION
**Pull request by Superhats**
[No testing was done, as I am unable to access a computer with DM]

This theoretically gives Vox, Drask, Diona and Grey access to the _Neutral_ gender option, as all of them are sexually amorphic species, without a biological gender.

:cl: Superhats
tweak: Vox, Drask, Diona and Grey can now choose the Neutral gender option.
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Really don’t want to encourage use of the web-editor because you really should be compiling and testing your code prior to submission. That said, this is a small change based on existing code that IPCs use, so this should work the same.

**Comment by variableundefined** [comment]
Echo.

What could I say about this PR?

I feel perfectly *neutral* on this.

**Comment by Superhats** [comment]
I know the web editor is discouraged, but I did it specifically because it is a very minor change.

**Comment by lass9030** [comment]
According to the wiki. Vox cannot be gender-neutral, biologically. Their larvae are genderless until they get a stack, however.

**Comment by AffectedArc07** [comment]
What about slimes, I swear those are genderneutral

**Comment by Superhats** [comment]
The matter is less lacking sexual organs, and more there being no physical difference whatsoever between male and female individuals.

**Comment by Superhats** [comment]
That is a fair point, I will add slimes

**Comment by Superhats** [comment]
Though, physically, slime people appear very clearly male or female

**Comment by KasparoVy** [comment]
Skree

**Comment by KasparoVy** [comment]
bUt ItS 2019

**Comment by Mithrandalf** [comment]
> I know what the lore says. But we don't need to be putting it in code. Rp however you want. Just leave it out of the code. I COULD forgive diona being coded becuase that has actually always been a thing in the code for Diona, just not a prefrence option just something that was set on a new/init for them i belive.

okay but why

**Comment by Superhats** [comment]
I don't see why the lore and code should be strictly separated, especially on things that have no impact on mechanics whatsoever. If lore and code had to be separated, we wouldn't have things like the code green flight control messages, or the random newscaster news, who serve no purpose other than fluff.

**Comment by Superhats** [comment]
It's not a new feature either, IPC have always had this option.

**Pull request merged**
