### PR TITLE
Fixes steal station blueprints objective

### PR DESCRIPTION
**Pull request by Aquilar**
## What Does This PR Do
Now the objective requires the CE's copy of the station blueprints exclusively to complete either by photo or theft. stealing normal, slime or somehow cyborg blueprints do not count.
also fixes this issue by consequence https://github.com/ParadiseSS13/Paradise/issues/12942

## Changelog
:cl:
fix: Steal station blueprints objective now requires either the CE's actual blueprints, or a photograph of them
fix: Stops the advanced pinpointer from pointing at slime and cyborg blueprints.

/:cl:

### CODE REVIEW

**Comment by farie82** [comment]
Forgot one part of the code:
image
Else photos of regular blueprints still count

**Comment by Aquilar** [comment]
Fixed that, sorry, never thought to look in photography.

**Comment by Aquilar** [comment]
it's already a subtype, the sprite was so if an admin spawned in base or cyborg blueprints by accident and they somehow got into the wild, a traitor wouldn't be confused into thinking they are CEs prints.

**Comment by Fox-McCloud** [comment]
Thinking about it more, this might just be better as a variable that's checked for.

Something like `objective_compatible` or something. Defaults to `TRUE`. Set to `FALSE` for the borg and slime one.

Wouldn't really worry about the tablet thing. If ERT have blueprints, it should be a valid steal target.

**Comment by Aquilar** [comment]
this is now a pure fix.

**Pull request merged**
