### PR TITLE
Donator - Personal Cyborg Sprite

### PR DESCRIPTION
**Pull request by The-Driker**
the burger

My PR for my personal cyborg sprite. The following is all fluff I came up with when designing the different models. Basically like a sales show to Nanotrasen 

**Ladies, Gentlemen, and those of unspecified gender!** 
Are you tired of showing up to work and seeing _THEM_? Yes _THEM_, those terrifying cyborgs, androids, and robots that are there to make your job easier and make you feel safer? Well we here at **Chef Excellence** understand your plight! 
After extensive research and trial by fire[often literally], we have created a series of machine models based on our other product lines, that are inoffensive to even the most backwater stations in the universe. We present to you, THE BURGER BORG!
standard
Specifically designed to appear non-threatening, and to remind crew to take those much needed lunch breaks to enjoy a delicious Chef Excellence brand burger™️.
The product line doesn't end there however. Your crew can enjoy such wonderful models such as! 
engineer
**The Easy-going Engineer**
Fully equipped with the proper PPE and face you can trust. You'll never find yourself worrying about it eating the engine, _unlike the organic crew._ 
medic
**The Bed·side Bear**
In the early 21st century, the weebanese created a robotic bear that assisted the sick and depressed with improving their health. We aren't completely sure how such technology existed back then, but Chad in accounting told us about it, and we have no reason to doubt him! Now you too, can have a big cuddly looking bear treating your crew's injuries and mental sickness! 
janitor
**The Jolly Janitor**
Sterile and delicious! Clean your station in style and remind your crew to enjoy our delicious Chef Excellence brand burgers™️!
service
**The Senõrgi**
It is our never ending goal to cater to clients with products that we know they will love. To this end we bring you a service model based off your favorite canine companion, but with an exciting, and culturally appropriate twist _[And a way to avoid copyright infringement]_
miner
**The Modest Miner**
Fully equipped with up to date mining equipment, and designed off an ancient 21st century video game that our very own Shaun in security suggested. You'll never have to worry about this little guy taking away the pay or credit from your mining team, and he'll always have their back out there in that less than dead space. 
security
**The Solem Securitron** 
We at Chef Excellence believe in transparency in how the law is handled at our company, and that's how we believe it should be everywhere! Which is why this adorable, but serious model in the Burger Series™️, comes equipped with it's disabler sticking directly out of it's burger. Formal and dignified, you wont find this wonderful model just tossing bloodied bodies into your personal brig without a word! _[Chef Excellence takes no liability, and is not responsible for machines tossing corpses into various brigs]_

**These are just some of the amazing models for synthetic crew assistants that we at Chef Excellence have to offer. Other amazing and exciting models will be available for viewing at the VIP showing. We hope you've enjoyed this look at our exciting offer and look forward to doing business with you in the future.** 

_[Chef Excellence and affiliates takes no responsibility for property damage or death due to malfunctioning synthetic handymen. Any and all supposed affiliation with crime syndication’s is completely non-existent, and such claims will be dealt with to the full extent of space law.]_

**Byond Name is Driker
Wasn't sure if I needed that here or not.**

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
***American Stamp of Approval***

**Comment by tigercat2000** [comment]
:us:

**Comment by Necaladun** [comment]
Huh, these are a bit silly and I thought I'd say no to everything but the service one, but the sales pitch actually did a lot to sway me with the whole corporate idea of making stuff look safe and inoffensive even if it can murder you.

The gif of the engi borg there looks clearly like an engi borg to me, and the rest look like the would except:

Mediborg might not be clear, can I see a gif?
Secborg looks good, but might need to be in red - gif too pls?

**Comment by The-Boogie** [comment]
ezgif com-resize 1

ezgif com-resize

There you are sir.

**Comment by Xantholne** [comment]
Cheese burger can finally be a cheese burger, plz speedy merge top priority

**Comment by The-Boogie** [comment]
As far as the special VIP viewing models goes. 

ezgif com-resize
The NT Combat Burger

ezgif com-resize 1
The Syndicate Burger Hound

**Comment by IcyV** [comment]
Those are silly but awesome sprites. Neca voiced the only real concern I had about them too. Something that distinguishes the medical borg a bit better, like perhaps a nurse hat, and some more red on the security borg. Those two were the only ones I had a moment of confusion about.

Also the Senõrgi might just be my favorite borg ever.

**Comment by The-Boogie** [comment]
I did try to add a nurse hat on the medical borg, but the pixel height was above the limit. As for the security borg, I based it close to the basic model of the security borg, which is completely black and grey.

**Comment by Spacemanspark** [comment]
This just made my day.
Full approval.

**Comment by taukausanake** [comment]
This reminds me of that one burger borg fluff we had a while back but got closed because too silly. At least I think it was, I can't find it anymore. Amazing idea still

**Comment by Necaladun** [comment]
Oh god the disabler on the sec borg is fantastic, I was wondering what that was.

The mediborg, cute as it is, I don't think is particularly identifiable as a mediborg sadly. If the nurse hat is too big, any way a red + can be added or something especially...doctory?

**Comment by taukausanake** [comment]
> red +

Can't, copyright infringement. Unless we finally don't care about that kind of thing? Really retarded, Red Cross, as if anyone knows you exist

**Comment by Spacemanspark** [comment]
We have a lot of other sprites with a red cross on it.

**Comment by The-Boogie** [comment]
mediborgwork

Could I perhaps interest you in a loverly designer stethoscope?

**Comment by taukausanake** [comment]
The hat really can't work? A medical bib would be great though.

@Spacemanspark I argue [this](https://github.com/ParadiseSS13/Paradise/pull/7093#issuecomment-294287252). So can we or can we not use red crosses in our icons?

**Comment by The-Boogie** [comment]
mik1oyv

@taukausanake This is just one of many attempts at doing a hat, and they all look equally terrible. The conflict with the bear's head and ears makes them look ugly.

**Comment by taukausanake** [comment]
@The-Boogie yeah okay. The bib is better but maybe make it a bit smaller. Like just around the neck, more bib than apron. I think that would be cute

**Comment by taukausanake** [comment]
Also I just noticed in your gif images that the treads are animated. Is that a movement sprite or always moving even if the borg is not?

**Comment by The-Boogie** [comment]
It's a movement sprite.

**Comment by The-Boogie** [comment]
@taukausanake 

So something like this?
untitled

**Comment by taukausanake** [comment]
Yes, and the pink is even better than red. I don't like how the straps have to go around like they do but it look unavoidable. Besides, it's your fluff, you should be happy with it first and foremost

**Comment by The-Boogie** [comment]
ezgif com-resize

There we are! Not really a fan of covering the burger, but it's a sacrifice I'm willing to make for the sake of crew recognizing what I am.

**Comment by d3athrow** [comment]
Nice sprites dude I'm totally ''''porting'''' these to veggie so all my cool donators can use them for only a few pomf coins each.

**Comment by SamHPurp** [comment]
@The-Driker can I recommend against including red crosses in any of your work.

**Comment by taukausanake** [comment]
@SamHPurp It's a pink cross so it's fine. Also:

**Spacemanspark**
> We have a lot of other sprites with a red cross on it.

Someone better make up their mind on whenever or not we care about this issue, or whenever it really is one either way because I for one don't think so

**Comment by SamHPurp** [comment]
@taukausanake ah the original image, it was red.

It is something we should look to change in the future, but it isn't a priority.

**Comment by The-Driker** [comment]
@d3athrow 
I appreciate the thought, but if possible, I'd like to avoid this specific set of sprites being used as an incentive for profit beyond my personal use on paradise.

**Comment by Necaladun** [comment]
Thats medbay'y enough for me. 

LGTM, :+1:

**Comment by tigercat2000** [comment]
@The-Driker This can be merged when the icon conflicts are resolved.

**Comment by tigercat2000** [comment]
You somehow managed to create an empty file called `git`.

**Comment by The-Driker** [comment]
I don't know anything about coding. 
Flat walked me through fixing the conflict, I can keep trying, but I can't promise not to break anything.

**Comment by The-Driker** [comment]
blank git file deleted. Hopefully it's good to go now.

**Comment by taukausanake** [comment]
@The-Driker Well, there seems to be a dmi file conflict

**Comment by The-Driker** [comment]
@taukausanake It appears to be because another custom sprite got added while mine was sitting here. I'm fixing it again.

**Comment by Fox-McCloud** [comment]
Why were the burger models put into here? This should only include the driker models.

**Comment by The-Driker** [comment]
@Fox-McCloud Those are the driker models.

**Comment by tigercat2000** [comment]
@The-Driker I believe Fox is refering to the `Burger-x` icons in the custom-synthetic file- The icon_states must match `your_ckey-module` to be usable.

**Comment by The-Driker** [comment]
Took a look at the files I used to fix the conflicts from other sprites being merged and found out what happened. It's fixed now.

**Pull request merged**
