### PR TITLE
Humans with matter eater can now grab eat

### PR DESCRIPTION
**Pull request by Crazylemon64**
Eating mobs with minds will also generate attack logs

### CODE REVIEW

**Comment by Plotron** [comment]
Buffing one of the most OP genetics abilities? Well...

**Comment by tigercat2000** [comment]
i'll just point out here that the matter eater power used to be able to do this normally but was changed so that you can't eat people so easily

**Comment by Plotron** [comment]
Yeah, I remember limb-eating with it...

**Comment by TheDZD** [comment]
@Plotron You can still do that. This just lets them directly eat entire people, in the same way that xenos and fat people can.

**Comment by Crazylemon64** [comment]
@tigercat2000 <a href=https://github.com/ParadiseSS13/Paradise/commit/ebb188dbfd4b315b22fd0b451f3b8ce74627a38a>It looks like matter eater used to be able to qdel people after a delay</a> - this works like xeno eating, in that the victim is able to shout for help while inside, attack the person from inside, and reverse-chestburst if they have anything in their inventory.

**Comment by Plotron** [comment]
What now, then?

**Comment by KasparoVy** [comment]
Is consuming mobs via grab+eat not giving nutrient still a thing or nah?

**Comment by Crazylemon64** [comment]
It DOES still give nutrients - 10 per tick of a mob being digested. However, it doesn't give the digester the nutriment, protein, or plantmatter reagents.

**Comment by KasparoVy** [comment]
Thanks for clearing that up @Crazylemon64, I was unsure of how exactly that worked

**Pull request merged**
