### PR TITLE
Pronouns!

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
This is a port of tg's pronoun library. Humans' pronouns are determined by `get_visible_gender`.
I avoided changing pronouns for logs for easier splunking, but other than that, tried to get everything that I could find, including:

- \he, \his, \him
- they, their, they're
- he, him, his
- minor grammar fixes
- a few style fixes here and there for code that I touched

## Why:
- \his and other similar macros can only be used in certain spots, and cannot conjugate more advanced things, and also don't respect whether your gender is currently hidden
- This allows messages to be more immersive by using the pronoun of the mob. For example:

Before: `Mob is stabbing themself in the eye with a screwdriver! It looks like they're trying to commit suicide!`
After: `Mob is stabbing herself in the eye with a screwdriver! It looks like she's trying to commit suicide!`

## More technical details:
Let's say you wanna tell this to the player:
`to_chat(user, "They appear to be catatonic. Not even magic can affect their vacant mind.")`

With the pronoun library, all you gotta do is this, which will correctly handle the female, male, and plural case (if their gender is hidden or neutral, as in some IPCs):
`to_chat(user, "[target.p_they(TRUE)] appear[target.p_s()] to be catatonic. Not even magic can affect [target.p_their()] vacant mind.")`

If the user is female, you'll get `She appears to be catatonic. Not even magic can affect her vacant mind.`
If the user is male, you'll get `He appears to be catatonic. Not even magic can affect his vacant mind.`
If the user's gender is hidden or gender neutral, you'll get `They appear to be catatonic. Not even magic can affect their vacant mind.`

:cl: Tayyyyyyy
add: Most things will now use the correct pronouns.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
OK... how does having this help us?
Does it add new pronouns? Does it clean up code that is currently bad? 
What's the justification? How does it help us to have this?

Simply saying 'this ports X from TG' isn't enough to justify why *we* should have it. It isn't even enough to clarify what the PR actually involves. Many of us (myself included) do not play on TG and have never seen this system in action.

You need to actually explain:
1) How this is different to our current system
2) Why you think this system is better than what we have now (ie: what extra stuff it gives us, what problems it fixes, etc)

**Comment by Tayyyyyyy** [comment]
@Kyep sorry about that, I've updated the PR description with what this PR actually does.

**Comment by tigercat2000** [comment]
Marking this as balance because it makes a lot of things respect face hidden status instead of reporting the user's real gender.

**Comment by tigercat2000** [comment]
@Tayyyyyyy Literally everywhere that was changed from any bare macro like `\his` or `\he` would not have previously hidden the user's true gender, whereas the replacements do it by default.

**Comment by Tayyyyyyy** [comment]
@tigercat2000 merge conflicts fixed. Updating the PR desc to be more clear on everything it touches.

**Pull request merged**
