### PR TITLE
Cyberiad Wall Consistency Overhaul

### PR DESCRIPTION
**Pull request by FreeStylaLT**
This will be a doozey! :hammer: Prepare for pics. 

## What I did:
I tweaked all of the rwalls/regular walls on Cyberiad that I could find according to these criteria:
1) If area is secure, surround it with rwalls
2) If wall is bordering space, it must be an rwall

These criteria were there (from what I know) from the start of Cyberiad, it is just that they were not kept consistently well.

Some oddities came up (Science, mostly, which is surrounded externally by rwalls, but regular walls from the inside.)

## Permabrig:

Before:
img
Sorry for potater quality took that in-game

After:
img

**Disposals:**

Before:
img

After:
img

## Arrivals maint:

Before:
img

After:
img

## Arrivals docks:

Before:
img

After:
img

## EVA maint:

Before:
img

After:
img

## Firing range:

Before:
img

After:
img

## EVA:

Before:
img

After:
img

## HOP/Conference/Bridge West Entrance:

Before:
img

After:
img
Conference room - not a secure area, Bridge - is, HOP's office - is.

**Grav gen entrance:**

Before:
img

After:
img

## Incinerator Maintenance:

Before:
img

After:
img

## Engineering Maintenance:

Before:
img

After:
img

## Engineering:

Before:
img

After:
img
None of those areas are of such importance to require rwalls all around them.

## Surgery:

Before:
img

After:
img

**Medbay bits:**

Before:
img

After:
img

## Morgue:

Before:
img

After:
img

## Dorms maintenance:

Before:
img

After:
img

## Holodeck:

Before:
img

After:
img

## Chapel maint:

Before:
img

After:
img

## Chapel maint further:

Before:
img

After:
img

**Science:**

Before:
img

After:
img
Covered Toxins, left the layout as it was otherwise

## EXPERIMENTOR:

Before:
img

After:
img
Access to lobby changed to regular walls, otherwise - following rest of Science's consistency.

**This fucking bit right here**

Before:
img

After:
img

**Xenobio entrance:**

Before:
img

After:
img

## Arrivals pod dock:

Before:
img

After:
img

**Science maint:**

Before:
img

After:
img

That wraps it up. Oh boy.

:cl: FreeStylaLT
tweak: Changed quite a lot of rwalls/walls around the station to be consistent with station design.
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
TOO MUCH PICS.

**Comment by FreeStylaLT** [comment]
###DOCUMENTATION

**Comment by Danuis** [comment]
Is fine.

**Comment by Spacemanspark** [comment]
Oh my

**Comment by Norgad** [comment]
Eh, I kind of liked the inconsistency. It added vulnerabilities and made the station look more (lorewise) shitily built/dangerous

**Comment by Fox-McCloud** [comment]
>Eh, I kind of liked the inconsistency. It added vulnerabilities and made the station look more (lorewise) shitily built/dangerous

This is the general sentiment I agree with---points of entry on the station, externally, is a *good* thing, in my opinion. It's one thing that I never liked about our map design.

R-walls should be largely to lock down secure areas and not necessarily as a "keep everything out forever" mechanism.

**Comment by monster860** [comment]
Yes, I kind of liked the normal-wall in the HoP office

By the way, I thought RCD's could take down r-walls..?

**Comment by Fox-McCloud** [comment]
@monster860 

No, only cyborg RCDs can do taht.

**Comment by FreeStylaLT** [comment]
There are windows in most of the areas I changed to rwall which bordered space, those are.. easier to break through than walls.

Otherwise, I am absolutely not against having certain areas bordering space being normal walls - as long as it is an intentional design decision, not a leftover oversight from porting maint from other stations, which, judging from lack of consistency even in that aspect, was probably the case.

Perhaps any maintenance area which is not a hallway bordering space could have regular walls, perhaps only select few. Either way, it has to be intentional. Right now we are just kind of working with what we have, which is not consistent, as you noticed in my many pictures.

**Comment by taukausanake** [comment]
I thought maintenance halls were r-walls to keep out radiation storms (not that it's the feature just what is said) but I agree space-touching walls should be r-walls because on the other side is death. And a lot of these wall replacements do seem a little unneeded. I think I might like the idea that NT is making some of their walls cheaper to cut back on the station nuking itself most of the time.
If you're trying to break into the station, maybe nuke ops, you still have ways to get through r-walls so it's not that bad, is it?

**Comment by KingPhilipIII** [comment]
Sad face. Those R-walls in the engineering shuttle dock means I have to work hard to build an airlock to space out of inflatable walls.

**Comment by Lady-Luck** [comment]
Jesus christ no. We need less r-walls, not more.

**Comment by Doukhan** [comment]
The random r-walls 4noraison in maint were always odd, as well as the rear end of surgery.
The consistency is nice but maint should probably not be so fully covered ,it is maint afterall.

**Comment by GeneralChaos81** [comment]
Goodbye engineering forts and expanded maint bar. :<

**Comment by FreeStylaLT** [comment]
This is how it was meant to be from the beginning, from what I can tell. Again, if maint feels too reinforced, I am all for removing sections or a set of it following a criteria, but this time it being done with actual intention.

**Comment by Doukhan** [comment]
For maint IMO if it's right next to a secure/main area like the brig/a public hallway it should probably have r-walls.
Places like the abandoned bar and those great big empty spaces and the bit above botany though? Probably shouldn't be so secure, takes away a lot of accessibility.

**Comment by Lady-Luck** [comment]
I'm not sure I've ever disliked a PR more than this one, to be quite honest.

**Comment by Kerroman** [comment]
I've never really seen anyone breach a wall to get into/out of the station unless it was unintentional (i.e. something happened to explode and there was a convenient hole) or they were busting into the armory (already r-walls and thus unaffected by this PR).  The one or two times I can think of that a wall _was_ breached, well, thermite was used.

R-walls can be easily deconstructed with just a little practice and patience, and if you don't have patience then just disassemble one of the many - **many** - windows in maintenance.

To me it very much makes sense that all exterior walls would be reinforced, along with any secure area (which are pretty much all built with r-walls anyways.)

**Comment by Norgad** [comment]
Can we stop having 'convenience' map edits. If the station was perfectly designed it would be boring as hell. Go look at cogmap or cogmap2. Those maps are fun because things are intentionally designed for things to go wrong. This PR just bubble wraps the station even more.

**Comment by tigercat2000** [comment]
@Norgad it's literally just standardization, but okay

**Comment by Norgad** [comment]
@tigercat2000 Well then the standard itself is dumb

**Comment by SigholtStarsong** [comment]
I'm not a fan of the EVA change at all - Those walls are supposed to be R-Wall for a reason.

**Comment by FlattestGuitar** [comment]
As others have pointed out, the station isn't meant to be perfectly secure. R-walls deny entrance to all non-chem evildoers and adding more seems a bad idea to me.

**Comment by FreeStylaLT** [comment]
Looks like everyone forgot I removed about as many rwalls as I actually added to areas bordering space. I will be splitting the internal and external wall overhauls into two separate PRs.

**Pull request closed without merging**
