### PR TITLE
Adds new space ruin, crashed wizard shuttle

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
As I was reading through the wanted features list on the forums, I saw more space ruins are wanted. Since I've been interested in mapping, I decided to start adding some. Which brings us to this PR, which adds a new space ruin, a crashed wizard shuttle. The wizard was sent out on a mission by the wizard federation to terrorize some poor people, but a spellcasting accident spelled his doom.

**If you want to discover the ruin without spoilers, stop reading now.**

The shuttle's pilot was an IPC wizard, the Magnificent Z.A.P. Sadly, he bought the emp spell without thinking and thus fried himself. His shuttle, inspired by the wizard's den, offers some potential rewards for daring explorers, though.

It is guarded by a creature and a crate mimic. It also contains some wizard gateway singularities (They do not grow and they do **not** move. There is no risk of them ending up at the station, unless serious shenanigans are involved)

The shuttle also contains some valuable loot (or the chance of it). I expect this to be the a tad controversial, so let me list out the main loot. There is a loot spawner behind the two monsters guarding it that spawns a random, wizard-themed item. It spawns one item, chosen at random:

Wizard Tarot Deck (Guardian Creator) 1 in 68 chance
Spellbook of Knock 1 in 68
Wand of healing 1 in 68 
Spellbook of Charge 20 in 68
Spellbook of Summon Item 20 in 68
Spellbook of Force Wall 10 in 68
Soulshard 15 in 68

Miners can get guardians just form mining so I figured a very small chance to get a wizard guardian is an appropriate, rare reward. Knock is a non-destructive spell that is nonetheless very desirable. But abusing it will get you arrested. And the wand of healing has 3 charges total. It offers resurrection (which SR can also grant) and full heals (which hivelord remains can grant). ~~something something make death more meaningful~~

Keep in mind that there is just a chance to spawn a space ruin, then a chance to actually find it in space, and **then** a 1 in 68 chance for the great loot, after a fight that will be very challenging for unprepared explorers.

Sidenote, other (somewhat) notable loot includes:
sacrificial dagger, insulated gloves, fancy zippo, some plasma, real wizard outfit (they have pretty decent armor)

**Images of sprite/map changes (IF APPLICABLE):**

capture2
capture1

**Changelog:**
:cl:
add: New space ruin, the crashed wizard shuttle. Rumored to contain fabulous magical treasures.
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Just noticed that wizard flag got moved by space wind in my picture, will fix that in a moment.

**Comment by Shadeykins** [comment]
@Kyep You can fix the corners of the shuttle having space underneath them by manually placing a non-random generated mineral tile there.

**Comment by Citinited** [comment]
I question why wizards need a shuttle in the first place

**Comment by TDSSS** [comment]
Teleport scrolls can't be that easy to make or they'd give the wizard one with unlimited charges. Also, other servers have the wizard starting base be a shuttle.

Also, I've verified that the mini singulos do not move when affected by a singulo beacon. I've also made a PR to fix a bug where statues could push singulos. With that all ways the singulos could get free/be an issue should be solved.

**Comment by Citinited** [comment]
Maybe the SWF has a limited budget? 🤔 

Regardless, makes sense I suppose. 😄

**Pull request merged**
