### PR TITLE
refactor: rename action button appearance related variables and procs to be clearer

### PR DESCRIPTION
**Pull request by Gaxeer**
## What Does This PR Do
Rename action button image creation related variables to be easier to understand

## Why It's Good For The Game
Nothing player facing 

## Testing
Tested all spells, tested most of actions. Seems fine (but we all know...)

### CODE REVIEW

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Gaxeer** [comment]
!merge_upstream

**Comment by Gaxeer** [comment]
!upstream_merge

**Review by Sirryan2002 — CHANGES_REQUESTED** [review]
need this to pass tests

**Comment by Gaxeer** [comment]
> need this to pass tests

will do

**Comment by Gaxeer** [comment]
@Sirryan2002 Done

**Review by Sirryan2002 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]
Thank you so much for this

**Pull request merged**
