### PR TITLE
Vulpkanin Hardsuit sprites

### PR DESCRIPTION
**Pull request by DarkPyrolord**
As stated in the title, this adds in hardsuit sprites for Vulpkanin.

Hardsuit Foward
Hardsuit Right
Hardsuit Rear
Hardsuit Left

Also it comes with sprites for the hardsuit lights.
Suit Lights

Thanks to @FlattestGuitar for the sprites, and for making sure I actually finished this.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
All the yes.

Obviously this doesn't "fit" for those who have husky tails or the likes, but it's 100% better than current.

:+1:  x :100:

**Comment by johannhawk** [comment]
better than nothing, we can always find a different solution later...

**Comment by Plotron** [comment]
ok

**Comment by FlattestGuitar** [comment]
I r8 8/8. One idea someone had was to just sprite the suits without tails and then add the character's tail overlayed with a color depending on the suit. Not sure how hard it would be to code, but probably a better solution that what this is. 

Also, I spent way more time than I should have on these sprites, so wear them wherever you can.

**Comment by KasparoVy** [comment]
Looks wicked. I still think the different looking eye-slits would've been a better bet, though. I'll post pic related when I get back home later

**Comment by johannhawk** [comment]
i suggested the same thing as Kasprov did in the first page of this thread.
http://nanotrasen.se/phpBB3/viewtopic.php?f=17&t=6830

**Comment by Fox-McCloud** [comment]
Going to merge this in as it's a 1000% improvement over what we currently have; if anyone would like to make little tweaks to the hardsuit sprite visors after merge, then those will be gladly accepted.

**Pull request merged**
