### PR TITLE
Updates old gift sprites in items.dmi

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Changes 5 old icons to new ones.

## Why It's Good For The Game

CHRISTMAS

## Images of changes

Will also fix the problem of gift ITEMS being out of date compared to WRAPPED gifts.

image
image

## Testing

Works

## Changelog
:cl:
imageadd: Resprites outdated gift sprites
/:cl:

### CODE REVIEW

**Review by Sirryan2002 — APPROVED** [review]
the fact that we have duplicate sprites like this makes me want to vomit

**Comment by ATP-Engineer** [comment]
I hate it, I really hate it.

**Review by Henri215 — APPROVED** [review]

**Comment by McRamon** [comment]
fix the shape of the box, add some more depth to it

**Review by DGamerL — CHANGES_REQUESTED** [review]
Instead of copypasting this from the wrapped gifts file, could you instead just tell the code to use that spritesheet?

**Comment by McRamon** [comment]
I looked into PR more, didnt realise at first that we have like 3 different DMIs with gift related sprites for different thing.
What needs to be done:
Move them all together (icons in items.dmi, storage.dmi and christmas.dmi, as they all use same palette (or should) and thematically same)
Update icon path for icons that were merged
Update the flatness of the existing icons. 
Icon path updatign is pretty straightforward and easy to do, there are plenty of people on discord that can help with that. If you find a problem like those duplicated icons in future, please put some minimal effort in to fix it instead of just copy pasting icons from one dmi file to another. Last thing we, sprite contributor? want, is this mess in dmi files. 
If you are unable to make any code changes whatsoever, which is totally understandable, prepare all the icons and find someone who can do the code part, which won't really be a problem.

**Pull request closed without merging**
