### PR TITLE
Adds Disposals Chute to Mechanic's Workshop

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
rscadd: Adds a disposals chute to the Mechanic's Workshop
/:cl:

Be gentle, this is my first PR

I might figure out how to add screenshots
2016-04-25 15_47_05-greenshot

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
pics or it didn't happen.

**Comment by Norgad** [comment]
Im trying fam

**Comment by Norgad** [comment]
Okay what else is wrong?

**Comment by Fox-McCloud** [comment]
>Okay what else is wrong?

Make sure that the disposals actually does lead to the cargo office and that anything that passes through the disposals near the junction does, as well.

**Comment by Norgad** [comment]
Yep already tested that

**Comment by Fox-McCloud** [comment]
Then this is fine, as is. Thanks. And you did better than most for your first PR!

**Comment by Norgad** [comment]
<3

**Comment by monster860** [comment]
Yep. My first PR, I forgot to mapmerge.

**Comment by Norgad** [comment]
whoops I hope whatever button I just pushed didn't break anything

**Pull request merged**
