### PR TITLE
Virology air tank now holds contaminated air.

### PR DESCRIPTION
**Pull request by moxian**
## What Does This PR Do
Connects viro air supply to main distro.
Cuts Viro scrubber network away from the main distro, and reroutes it to the two small holding tanks south of it.

## Why It's Good For The Game
On Cyberiad, south of virology, there are two air tanks connected to virology. 
Logically speaking, the separate air network there is required to contain the spread of viral agents. (Gameplay-wise it doesn't matter, but let's pretend). However, the holding air tanks are connected to *vents* rather than *scrubbers*, which makes this whole setup dubious. Infected people in quarantine do not really need extra special air to breathe - they can use the main distro one just fine.

I've seen this brought up several times in dchat, and there has never been a sensible explaination for the current setup. But it's super minor and does not affect gameplay which is why i assume nobody bothered fixing it.

## Images of changes
Old:
20220501-184432-StrongDMM
New:
20220612-113629-StrongDMM

## Changelog
:cl:
tweak: Cyberiad virology air tank now holds contaminated air, instead of supplying breathable one.
/:cl:

### CODE REVIEW

**Comment by Dafrek** [comment]
Yeah, its strange, on Metastation the virology atmos situation is pretty much the same with the scrubber system connected to the station's scrubber system while it has its own isolated distro system. Meanwhile, on Delta the entire virology atmos is isolated, with waste pumping into space instead of into the station's waste system. 

I think it would make sense for them both to be disconnected IC-wise, but this would obviously hurt biohazard vent crawling antags that would want to get to the monkeys in virology.

**Comment by moxian** [comment]
Updated meta.

**Comment by Xsingular** [comment]
Just for the sake of argument:

What if the AI, borg, or an atmos tech remotely decided to do a Panic Syphon, or even manually change the direction of the vents from Blowing to Siphoning?

The contaminants would enter the distro loop, no? (lorewise, not gameplay-wise since we don't actually model that)

**Comment by Miraviel** [comment]
I am all in for logical changes, but it does impact gameplay: vent-crawling entities, especially xenomorphs, borers, and terror spiders will have a much easier time with this.

Currently, these three have to take a risk to get into virology and get the free monkeys (provided they weren't killed off by a virus or starving) by popping up in the cycler area and be seen/shot at. With this change, they can just crawl in without an issue.

By the time they spawn, virology is usually empty, because the virologist can do his job in 5 minutes and never go into that place again. This means that if terror spiders start with greens or whites, they will have an incredibly easy time to reproduce.

I cannot remember exactly, but from what I remember, Meta and Delta have extremely isolated virologies, and with this change these ventcrawlers can make an entire nest here without being in any meaningful danger for a long time.

I am not against the change, but please keep in mind that this will tip the balance in favour of these biohazard entities (in my opinion)!

**Comment by AffectedArc07** [comment]
Its designed for both pieces of the loop to be separate, mainly distro since that would be where theres a high volume of airflow (think of how viruses can travel between office rooms via AC shafts IRL), whereas the scrubbers network is normally a vacuum, which would be very difficult for particles to escape out of. 

Not in favour of hooking supply up to main, but if you want to expand the atmos room to add a holding tank for the scrubber output too, thats just fine by me.

**Comment by moxian** [comment]
> What if the AI, borg, or an atmos tech remotely decided to do a Panic Syphon, or even manually change the direction of the vents from Blowing to Siphoning?
> The contaminants would enter the distro loop, no? (lorewise, not gameplay-wise since we don't actually model that)

With manually changing direction yes. With panic siphon no (it only utilizes scrubbers, not vents).

> Currently, these three have to take a risk to get into virology and get the free monkeys (provided they weren't killed off by a virus or starving) by popping up in the cycler area and be seen/shot at. With this change, they can just crawl in without an issue.

Currently they don't need to take any risk if they use the scrubber network (red) as opposed to supply network (blue). This change only swaps the two around, with no meaningful shift to balance.

live:
20220502-163523-dreamseeker

pr: 
20220502-162749-dreamseeker

> Its designed for both pieces of the loop to be separate, mainly distro since that would be where theres a high volume of airflow (think of how viruses can travel between office rooms via AC shafts IRL, whereas the scrubbers network is normally a vacuum, which would be very difficult for particles to escape out of.

Normally, particles wouldn't be able to enter vents for the same reason they can't exit scrubbers - the pressure difference between the pipe network, and the ambient air. (Also, while it's very easy IC-wise to overpressurize distro, yet find scrubbers being near-vacuum to be improbable)

**Comment by AffectedArc07** [comment]
> Not in favour of hooking supply up to main, but if you want to expand the atmos room to add a holding tank for the scrubber output too, thats just fine by me.

I stand by this. Please make both of them go to isolated containers.

**Comment by hal9000PR** [comment]
I have a request, instead of using those static tanks, would you use a tank ontop of a connector?

**Comment by S34NW** [comment]
> I have a request, instead of using those static tanks, would you use a tank ontop of a connector?

They have both static and portable tanks in the viro rooms
image

**Review by S34NW — APPROVED** [review]
Mapping is fine.
Design wise, I do agree that it makes more sense for waste to be isolated, not distro. The actual harm done to a vent crawler using waste is currently minimal anyway as you aren't in the pipe for long if you have a brain.

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
> Not in favour of hooking supply up to main, but if you want to expand the atmos room to add a holding tank for the scrubber output too, thats just fine by me.

I stand by this. Please make both of them go to isolated containers.

**Comment by S34NW** [comment]
> > Not in favour of hooking supply up to main, but if you want to expand the atmos room to add a holding tank for the scrubber output too, thats just fine by me.
> 
> I stand by this. Please make both of them go to isolated containers.

Would you be open to a (initially closed) bypass valve in the maint room that could be opened to top up the supply tank from distro?

**Comment by moxian** [comment]
Disconnected viro from distro:
20220506-201112-StrongDMM

Two issues here though:
1) The total amount of air in the room is roughly twice that of an air canister. So if someone were to cycle the air out (or, less, likely, if the viro was completely hull breached), it won't be able to refill without atmos intervention. But that's probably fine
2) I deem this to be a HUGE NERF to terror spiders and other ventcrawlers, and nerfing those is NOT my intent here. I see that this has gotten a head approval *in its previous state that had no balance implications*, but I strongly believe this new iteration needs it be re-approved anew.

**Comment by S34NW** [comment]
You also need an online pump hooked to the scrubber tank @moxian or it will just share pressure with the pipenet

**Comment by moxian** [comment]
Thanks @S34NW !
I managed to miss (or misinterpet?) your "distro overflow" idea, but it's really cool. So i went ahead and added that.
Now we have the IC'ly permanently closed distro->viro valve, which despite being closed still allows ventcrawlers infiltrate viro gameplay-wise.
Also added the pump, thanks again!

And applied the same changes to the Meta.
<details><summary>Pictures</summary>
Box:

20220506-222726-StrongDMM


Meta:
20220506-222511-StrongDMM
</details>

**Comment by Dafrek** [comment]
I feel it would make more sense if the closed manual valve was replaced by a pump to drastically reduce the chance that distro mixes with virology's distro.

**Comment by moxian** [comment]
If we're concerned with pathogens getting into vents and spreading that way, then I would not expect the pupm alone to be a sufficient means of protection from those. It needs to be placed in addition to the valve, but there's not enough space to have both.

**Comment by AffectedArc07** [comment]
The box edits are fine, your existing images just need updating

image

Meta will need redoing entirely since the TG meta port took priority.


Please deconflict within 7 days.

**Comment by moxian** [comment]
Deconflicted box.
Meta at current master has scrubbers leading directly to space, which is fine by me. So i discarded my changes to it.

Updated OP with up-to-date picture.

**Pull request merged**
