### PR TITLE
try to fix mindslave implant hud

### PR DESCRIPTION
**Pull request by Aurorablade**
fixes https://github.com/ParadiseSS13/Paradise/issues/3165

Already have compile errors adding old code back, and still got ot make it so the hud will only display for mindslave to master....

Have to get up early...am confused...

### CODE REVIEW

**Comment by Aurorablade** [comment]
okay new commit, feel i am close, current issues, the icon will show oddly... the slave/master will get THIER icons but won't see the others. and when you aghost out and back in you loose the icon totally.

Using the method on suggestion of TG IRC. its like thier gang huds.

**Comment by Aurorablade** [comment]
current issue stopping everything: icons not showing on observer antag hud. minor: if you aghost and hop back in you loose the icon for yourself.

**Comment by Aurorablade** [comment]
I FIXED IT THERES THE AGHOSTING ISSUE BUT DO WE REALLY CARE ABOUT THAT IF IT ONLY AFFECTS THE ADMIN
READY FOR REVIEW

**Comment by Fox-McCloud** [comment]
This is better than the current status of thing, by far--going to go ahead and merge this, but the aghosting issue does need to be worked on.

**Pull request merged**
