### PR TITLE
icon/obj folder cleanup

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do

Purges many of the crummy unused crusty old sprites we still have lying about for literally no reason.

I left the old baguette, that's special.
image

## Why It's Good For The Game
We have so much soul bloating up our files, its time we deleted some of it

## Changelog
No player-facing changes, these sprites did not get used.

### CODE REVIEW

**Comment by S34NW** [comment]
Kind note to future spriters: If you replace a set of sprites, DON'T name it sprite_old and just leave it in the files. Thanks!

**Comment by AffectedArc07** [comment]
image

@dearmochi

**Comment by AffectedArc07** [comment]
Please resolve conflicts

**Review by AffectedArc07 — APPROVED** [review]
If this breaks we blame you

**Pull request merged**
