### PR TITLE
Resprites arcade tickets/stacks

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Replaces arcade ticket stack sprites

## Why It's Good For The Game

New sprite good

## Images of changes

Old tickets
image

New tickets
image

## Testing

New high score! 50 tickets rewarded

## Changelog
:cl:
imageadd: Replaced arcade ticket sprites
/:cl:

### CODE REVIEW

**Comment by TravisAngeI** [comment]
honestly kinda like the old sprites more just because the outlines make them look more defined

**Comment by Contrabang** [comment]
Yeah, I agree, the black outline looks better

**Comment by PopGamer45** [comment]
I must agree with it looking better with the black outlines, looks kinda gooey without them

**Comment by ATP-Engineer** [comment]
OK, darker outlines, got it.

**Comment by McRamon** [comment]
Sure i guess. Though id prefer an actual resprite than just a color adjustment

**Review by Sirryan2002 — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
