### PR TITLE
Replaces Ashwalker egg sprite, nest sprite

### PR DESCRIPTION
**Pull request by iantine**
## What Does This PR Do
Replaces the Ashwalker nest egg to something more thematically appropriate. Tweaks the nest sprite to include the new eggs.

## Why It's Good For The Game
The original egg sprite is very blurry, rather like an enlarged bird egg. This may be more Lavaland-ish.

## Images of changes
Old:
eggold
nestold

New:
egg
nest

## Changelog
:cl:
imageadd: New egg sprite, new nest sprite
imagedel: Old egg sprite, old nest sprite
/:cl:

### CODE REVIEW

**Comment by atteria** [comment]
Bit of weird jaggies on the egg's silhouette, probably inherited from the old sprite?
Otherwise a massive improvement.

**Comment by S34NW** [comment]
E G G

**Comment by meow20** [comment]
image

**Review by hal9000PR — APPROVED** [review]

**Comment by LightFire53** [comment]
Damn, that's really good!

**Comment by atteria** [comment]
Just checked the palette, I wasn't able to count them all but it's over **one hundred and eighty** unique colors. That's off the charts.

Most pixel art, including ss13 artstyles, tries to keep the palette limited. Please don't make sprites with each pixel having a unique color.

**Review by AffectedArc07 — APPROVED** [review]
The sprites are detailed, but I think that fits for lavaland. Everything on here has extra detail, like another world should.

**Pull request merged**
