### PR TITLE
Readds otherthing-dead

### PR DESCRIPTION
**Pull request by Emanthealmighty**
## What Does This PR Do
The death sprite for "creature" was removed somehow in my last commit to animal.dmi. This readds it

## Why It's Good For The Game
No one likes something going invisible when it dies. It was an unintentional change.

## Changelog
:cl:
fix: Fixed "creature" not having a death sprite.
/:cl:

### CODE REVIEW

**Comment by MRgaty** [comment]
There is an easier way to fix this... Make the creature invisible 😏

**Comment by TDSSS** [comment]
Just make the creature unkillable

**Comment by Emanthealmighty** [comment]
"Creature" is a gold slime extract spawnable mob. It's not becoming invincible.
The dead sprite wasn't removed because someone actually wanted it not to die, it was an error.

**Comment by Spacemanspark** [comment]
They were joking

**Comment by Emanthealmighty** [comment]
When you get two people in a row saying something like that with close to no indication that it's a joke... it's hard to not reply.

They made me look at the code like "is it actually supposed to be invincible?"

**Comment by TDSSS** [comment]
Sorry, I should have added a smiley or something. I figured a creature being unkillable was obviously too absurd to consider.

**Comment by Crazylemon64** [comment]
all hail the dummy

**Pull request merged**
