### PR TITLE
Backpack Fixes and Port

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just some backpack fixes and tweaks:

- Fixes https://github.com/ParadiseSS13/Paradise/issues/2748 (this applied to all duffle bags)
 - Please note, that a number of duffle bags, which aren't mapped, don't have a back sprite (as I don't have them, and neither does anyone else).
- Ports over TG's job specific backpacks and makes them equipped to those jobs by default
 - Chemistry, science, viro, genetics, and hydroponics.
 - Alter's hydro satchel sprites a bit to be consistent with the hydro backpack.
- In the course of fixing and porting these things, I noticed that a number of the satchels use backpack on-mob sprites for some reason, despite the fact that unique back sprites for the satchels exist--that's been corrected.

Pics of the job backpack+adjusted hydro satchel:

job1
job2

Reminder to self:
- Make a new PR to add in botanist ward-drobe along with backpacks, once the shuttels PR has been merged.

### CODE REVIEW

**Comment by taukausanake** [comment]
I can't say I like that Hydro satchel but I don't know how many others will agree with me so whatever. Same with the Hydro backpack but the others look nice

**Comment by Fox-McCloud** [comment]
I'm pretty sure the intended reason is for distinction and clarity; Botany's primary colors are green and blue, distinctively.

Green, however, is kinda the clown's color, especially for backpack. That kinda helps set it apart and match the botanist's default clothing.

**Comment by tigercat2000** [comment]
I think it would look much better the other way around
IE. the flaps and shit being green, with the base being blue

**Comment by TheDZD** [comment]
I don't have any particular issue with it, but it does seem a bit like the botany satchel/backpack's colors are too bright, almost on the level of clown items. Toning down the saturation a bit and/or lowering the brightness might make it fit a bit better. Darker greens, earthy browns, and darker blues tend to fit botany a bit better than brighter colors, given that they work with plants and dirt (well, I'd assume there's some dirt analogue in the hydro trays).

**Comment by Fox-McCloud** [comment]
hydro1
hydro2
hydro3
hydro4

Comparison.

**Comment by orelbon** [comment]
Could you make an atmos tech satchel?

**Comment by Fox-McCloud** [comment]
@orelbon 

Not in this PR.

**Comment by taukausanake** [comment]
Oh, I still like the original Hydro backpack. I really don't want it to change.

If you're going to do it though, make sure the Hydro duffle bag also gets the color change.
Or don't. I REALLY like the colors Hydro packs have

**Comment by Plotron** [comment]
Agreed with Tigercat.
Probably also agreed with Tauka.

**Comment by TheDZD** [comment]
Huh, apparently it's just the shading, and the colors are pretty much the same.

**Pull request merged**
