### PR TITLE
Ports security webbing from /tg/

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

Ports the security webbing from /tg/station (tgstation/tgstation#41394). 

It's a security belt **with an additional slot** and **can only be obtained through Cargo by ordering a Webbing Crate (15 points for 3).**

## Why It's Good For The Game

Security belts have 5 slots and that often forces an officer to carry additional equipment (handcuffs, bolas, holosign, ammo boxes...) in their backpack, which can be inconvenient since said equipment would be located in two different places.

Restricting the webbing behind Cargo orders ensures the belt isn't made obsolete. It's a minor upgrade at a cost. Also webbings look cool and tactical.

## Images of changes

dreamseeker_D56Ai9zPGy

## Changelog
:cl:
add: Add the security webbing, boasting an additional storage slot over its belt counterpart, but can only be acquired through Cargo since it's not standard issue
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
5 per vendor seems too much to me. Coins can be minted (iirc) and aren't really a huge cost for the station at large.

**Comment by dearmochi** [comment]
Yeah, the original PR this is from had 5 in the vendors but I don't really know the population counts over on /tg/station. I didn't want to make the belts restricted to a too small a pool of officers so I left the number as is.

**Comment by TDSSS** [comment]
Could always make them orderable from cargo

**Review by Kyep — APPROVED** [review]

**Comment by dearmochi** [comment]
I went and made it obtainable exclusively through Cargo. A crate of three webbings costs 15 points. That way officers can't get a webbing from round start and actually have to wait some time before getting one.

**Comment by Spacemanspark** [comment]
We already have webbing in the code, hilariously enough. It was from baycode and each officer started with one.

Fox removed it years back.

**Comment by procdrone** [comment]
looks interesting

**Pull request merged**
