### PR TITLE
Counter for #5379

### PR DESCRIPTION
**Pull request by taukausanake**
PR #5379 wanted to remove the stripper uniforms and suits because missing icons there were. In reality most of the icons were there but naming conventions probably messed up. The only sprites that were missing were the stripper suit icon_states but those were copied from its on_mob icons like every other suit it seems.

Also adds in fat versions of the clothings because who doesn't want a chubby stripper? However, untill #5402 is resolved this won't look as good

PICS. PICS ALL YOU PERVERTS:
capture

### CODE REVIEW

**Comment by Spacemanspark** [comment]
We don't need stripper clothing.

**Comment by FlattestGuitar** [comment]
That's the spirit, @Spacemanspark!

**Comment by Ty-Omaha** [comment]
Maybe _you_ don't need stripper clothing b-but.....nevermind....

**Comment by SigholtStarsong** [comment]
Why not? Now I can dress Nova up in fuzzy cuffs, a blindfold, a ball gag _and_ a stripper outfit!

**Comment by taukausanake** [comment]
Those stripper outfits are pretty cute. :3

I'd like someone to review this for me just in case it needs better names. I still have only half an idea on the naming conventions for clothing and I'd like a coder's take on what they should be

**Comment by Spacemanspark** [comment]
>Now I can dress Nova up in fuzzy cuffs, a blindfold, a ball gag and a stripper outfit!

My point has been proven.

**Comment by Ty-Omaha** [comment]
StripperStation13

**Comment by Aurorablade** [comment]
*puts spark in the vox box..*

**Comment by KasparoVy** [comment]
The icon_states/item colours appear to be changed but in the .dmi files all the stripper outfits still don't have _under or _over anywhere in the sprite names. Got pictures of this working?

**Comment by KasparoVy** [comment]
@taukausanake
The icon_states/item colours appear to be changed but in the .dmi files all the stripper outfits still don't have _under or _over anywhere in the sprite names. Got pictures of this working?

**Comment by IcyV** [comment]
>no pictures

**Comment by Wheatley29** [comment]
Burn it.
Burn it all.

**Comment by taukausanake** [comment]
@KasparoVy thanks for pointing that out to me, I just noticed it myself and I guess I forgot to fix them. I was too busy var editing everything in-game first.
I will fix vox names next as well.

I wasn't sure anyone would want pics of 2D spesswomen in stripper clothings, I mean with this being a non-ERP server and SO MANY people against it :P. I'll post _pics_ once I finish all the sprites

**Comment by Spacemanspark** [comment]
If you think you shouldn't post the pictures because we're a non ERP server that should be a pretty clear indication that we don't need the feature in the first place.

**Comment by Vivalas** [comment]
Inb4 furry stripper station 13.

**Comment by taukausanake** [comment]
Fuck, hold on, forgot to reapply my edits after merge conflict

**Comment by Necaladun** [comment]
Gonna have to go with a big no for stripper uniforms.

**Comment by Spacemanspark** [comment]
Seeing those pictures...
No. Just no.

**Comment by Lady-Luck** [comment]
Jesus fucking christ no

**Comment by MindLeaker** [comment]
First maid outfits, now stripper clothing.
We might as well rescind the ERP rule because apparently the word "borderline" doesn't exist in Paradise's dictionary
Because this is borderline ERP material, like it or not

**Comment by tigercat2000** [comment]
merge this then merge #5379 on top :sunglasses:

**Comment by taukausanake** [comment]
@tigercat2000 you're horrible. :(

@Fox-McCloud @TheDZD Ready for ~~judgement~~ review

**Comment by Fox-McCloud** [comment]
It's been decided that these will be removed.

**Comment by taukausanake** [comment]
Can I ask by who?

**Comment by Fox-McCloud** [comment]
DZD, myself, and Neca.

**Comment by taukausanake** [comment]
Fine

**Pull request closed without merging**
