### PR TITLE
Removes Unused Object

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes a useless tool with no function and its useless accompanying proc that's tied into literally nothing.

Also removes its usesless horrendous icky sprite which was an MSpaint recolor of a multitool.

Was this a precusor to the multitool? Some old thing from bayland? I have no idea. It's literally worthless now.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Being able to check if something was emagged does sound like a nice function this tool apparently was coded to fill, though frankly most emagged things are rather obvious to identify.

**Comment by Crazylemon64** [comment]
travis what you do

**Comment by Dinarzad** [comment]
Code archeology is the most fascinating sort of archeology.

**Comment by FlattestGuitar** [comment]
🐜 🔫 👌 💯

**Comment by Signmark** [comment]
@CIB what have you done
image

**Comment by Vivalas** [comment]
:-1: insert tangential at best reason why it sucks

**Comment by jughu** [comment]
Could you atleast add the special functionality from the debugger to the multitool since that really would be handy

**Comment by Fox-McCloud** [comment]
>Could you atleast add the special functionality from the debugger to the multitool since that really would be handy

No.

**Comment by Crazylemon64** [comment]
RIP in pasta oldcode

**Pull request merged**
