### PR TITLE
Refactors any remaining Loyalty references to Mindshield

### PR DESCRIPTION
**Pull request by SamHPurp**
Last year Loyalty implants became Mindshields... there were still some leftover loyalty bits when this was done, so I've cleansed this a bit.

No changelog as its back room stuff.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Incredibly pedantic, when none of this is even player accessible, but whatever.

**Comment by SamHPurp** [comment]
@Fox-McCloud It makes the code more understandable to others reading it, cleans up old stuff that isn't relevant.... calling it pedantic is great behavior of someone 'maintaining' the code. Definitely makes me feel like continuing to contribute!

**Comment by FreeStylaLT** [comment]
THIS SHIT CONFLICTED MY FUCKING BRIG
:dagger:

**Comment by SamHPurp** [comment]
:heart: @FreeStylaLT

**Pull request merged**
