### PR TITLE
TG Spider Port

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of TG's spiders.

TG's spiders are more or less the same as we have now, only the spiderlings are more difficult to kill (by virtue how how they move); the way the procs are handled in the spiders themselves are a organized a bit better (plus spans and non-relative pathing!), and spiders are actually something to contend with in a fight.

Additionally spiders now have full support for player control if an admin so deems it; this is different than the way it used to be in the past--this makes spiders function more like Xenos. If a player controlled spider lays eggs, those eggs will have the potential to pull from players with the BE_ALIEN flag enabled. 

This does buff spiders, in particular regular spiders and hunters--both of these classes will have more health and the hunter will move faster. That said, for the spider infestation event, there shouldn't be much of a difference in terms of balance to players. Why? Infestation only spawns spiderlings that will grow into Nurses (and their health is unchanged). End result; the infestation event, on start, will be about the same, but if the spiders are given a chance to get going, then the trouble WILL start.

Related to this:
- Nerfed changeling's spider ability from 4 spiderlings to 2--the reason it was 4 is because of our weak spiderlings+spiders.

Para unique changes: 

Spiders now inject the reagent "venom" when they bite someone as opposed to "toxin"---suggestion by @TheDZD. Will make damage scale; at first damage will start out smaller than on live, but as the spider bites you more and more, it could end up doing more damage. The window to fight against the spider should be much greater, but once he has you down, you're down (which isn't that much different from live) 

Other
- Carp should move a bit faster and be a bit more resistant to high temps (but provide more meat when killed).

### CODE REVIEW

**Comment by tigercat2000** [comment]
I'm not sure NPC spiders need a buff. Last time I encountered an NPC one, it still managed to kill me, alone, by benefit of the massive amount of toxin injected.

**Comment by ZomgPonies** [comment]
Yeah I wouldn't touch their HP, but rather make them grow from spiderlings -> full spiders a bit quicker, so the crew has less time to kill all the spiderlings. Also it'll boost nurse spiders who lay eggs.

**Comment by tigercat2000** [comment]
I will agree with ponies- I can't say I support this while they have 200 health. Other than the HP, :+1: to the refactor.

**Comment by Fox-McCloud** [comment]
Updated some things and explained some things better to alleviate some concerns. Give a tired fox a break, mannnn.

In any event, short of it is your average spider encounter from the infestation event shouldn't be much different, as they grow up into nurses---and their health remains unchanged. If players refuse to take care of the nurses and/or get themselves killed by a nurse, then the trouble begins.

Venom also allows for more up-front counterplay as it does less damage than toxin until you've gotten bit a lot.

**Comment by Spacemanspark** [comment]
Yaaaaaaa the spiders we currently have don't need a buff.

**Comment by TheDZD** [comment]
It may be worth reducing their on-hit damage in order to make them rely more on their poison. This would give players a better chance at being able to take down spiders in the short-term, and would offset the increased health.

**Comment by Finalsong** [comment]
I like it. All of it.

**Comment by Fox-McCloud** [comment]
@Finalsong 

Nah, they wouldn't be able to do that--it adds *support* for players controlling spiders and the future spiders continuing to be controlled by players *if* an admin allows it---day to day, spiders will still be an NPC entity. They'd ultimately still be weaker than Xenos--one way or another.

**Comment by fj45** [comment]
Hrm, don't know about buffing carp, in the wrong spot you can get completely swarmed by them, I have seen three people in hardsuits die as a group,

**Comment by ZomgPonies** [comment]
3 people in hardsuits...that's just people being unrobust. I don't see that as being representative.

**Comment by Spacemanspark** [comment]
Depends on how many carp were there.

**Comment by ZomgPonies** [comment]
Let's try this and adjust from there.

**Pull request merged**
