### PR TITLE
Added bridge blast doors

### PR DESCRIPTION
**Pull request by chopchop1614**
I basically added two blast doors leading to the captains office and the conference room. 

The reason is whenever you get nuke ops rounds and someone screams "NUKE OPS!" and you lockdown the bridge, they can come through teleporter into your office and into bridge or go through the HOP office and up. This seems pretty unfair as the lockdown basically becomes useless do to these exposed areas.

### CODE REVIEW

**Comment by chopchop1614** [comment]
Also, I apologise for the two commits. I did the same thing twice but one of them has the smaller file thingy. I am still learning git and can't figure out how to remove one of the commits.

**Comment by Fox-McCloud** [comment]
Lockdowns are not supposed to be absolute, as a generalization--of the ones that do exist, there's still multiple ways out, in a lot of cases.

Likewise, this doesn't stop nukies in that scenario; they can just emag the blast doors open.

**Comment by chopchop1614** [comment]
It just feels more secure having those doors. Whenever I am the captain and activate the lockdown I always get the door remote and lockdown the doors to the captains office and conference room.

**Comment by mrturkeytoe** [comment]
I don't understand why we even have the lockdowns if there are usually multiple ways around them

**Comment by chopchop1614** [comment]
Roleplay I guess.

**Comment by Taaketa** [comment]
Thumbs down. Every lockdown has a bypass on the station with exception to Science.

**Comment by chopchop1614** [comment]
Where is the bypass on medbay lockdown?

**Comment by Lady-Luck** [comment]
>Where is the bypass on medbay lockdown?

Apples and oranges... having medbay locked down is a gigantic handicap to the station.

**Comment by FlattestGuitar** [comment]
Medbay lockdown bypass is in the exam room, science the EXPERIMENTOR room.

I really tried stopping myself from doing this, but I can no longer.
https://en.wikipedia.org/wiki/Sodium_chloride

**Comment by tigercat2000** [comment]
No. They are intended to have vulnerabilities, as well as an actual escape route.

**Comment by monster860** [comment]
@chopchop1614 

It seems that you ran mapmerge off of an old backup.

```
git fetch ParadiseSS13
git checkout ParadiseSS13/master
```
Then run "Prepare Maps.bat"
```
git checkout mapedits
git reset --soft HEAD~2
```
Then run "Run Map Merge.bat"
```
git commit -m "Adds bridge blast doors"
git push --force origin mapedits
```

**Comment by chopchop1614** [comment]
@monster I will do that if I do another map pr. However I think I am having some issues with my git bash because it keeps babbling on about some missing repository thing. I will talk to you about it on the coder chat.

**Comment by Norgad** [comment]
@chopchop1614 The map is supposed to have intentional vulnerabilities.

**Comment by LightningLynx** [comment]
Medbay also has a lockdown in the paramedic room. Thats two lockdown bypasses on virtually opposite ends of the station -- so the bridge is still more easily defensible even if the lockdown is bypassed through HoP or teleporter. Additionally, lockdown isnt going to mean much to nukeops anyway -- nuke ops are still going to C4/emag through the shutters regardless, the only reason HoP/teleporter would be preferred now is its more easily defensible than being in the middle of the hall.

All this would do is fuck up non-nukeops traitors who would have more issues getting into the bridge if it were completely locked down -- and completely fuck up people trying to fight back against a malf AI who initiates lockdown and turns off the power.

**Comment by Fox-McCloud** [comment]
Lacks support, not map-merged, and it now has rogue commits. Going to go ahead and close this.

**Pull request closed without merging**
