### PR TITLE
Better looking toxins alert sprite

### PR DESCRIPTION
**Pull request by ZomgPonies**
- See https://github.com/d3athrow/vgstation13/pull/3556 for an image.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Might want to look at ours; I think ours looks even better than that; we definitely don't use the codersprite for tox anymore that VG mentions in their PR.

**Comment by ZomgPonies** [comment]
I did, this one definitaly looks better. It's higher res and much clearer. Also green, green like the warning lights during rad storms.

**Comment by fj45** [comment]
Our current one seems clearer and green=good. The VG one also has some weird detailing. 


(Rad storm lights are very different, you also get a huge warning.)

**Comment by ZomgPonies** [comment]
Open them side by side and you will see the purple one is much more pixelated.

**Comment by Spacemanspark** [comment]
I like it.

**Comment by fj45** [comment]
Sure, our current one isn't a nice sprite but it does its job very well, it is extremely clear.

**Comment by Fox-McCloud** [comment]
I kinda like our current one for the reason FJ mentioned---anyone else have any thoughts?

**Comment by Artorp** [comment]
For reference, side by side comparison (at 200 %):
tox

I kind of prefer the current one, the colors complement each other nicely, it has an unambiguous TOX warning, and I like the harder edges. Sure it's more aliased, but it's a 32 by 32 px sprite after all and the vg one feels a bit blurry by comparison.

**Comment by ZomgPonies** [comment]
Yeah now that you put them next to each other like that...

**Pull request closed without merging**
