### PR TITLE
Remove instant ranged stuns

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
HERE WE GO!

Remove ranged instant stuns! This removes the round-start tasers and removes the taze mode from the AEG, the HoS gun keeps his taser.

**Why?**
This is to encourage RP and to reduce the amount of situations where players are entirely helpless(things like taze and cuff). This is just another step in the direction I want to move combat where it's all more action and reaction and less action and.. over. This discourages security from disablering on sight and attempt to get closer to stun baton which are still instant stuns, and before people consider this an "security nerf" keep in mind that most antags use security gear for the majority of the shift and will usually end up with ranged instant stuns as well. This nerfs the instant win situations and helps encourage antags and security to be more comfortable with roleplaying with each other because it's slightly harder to instantly kill the other from a distance with a stun.

I understand there will be people who disagree with this and don't like this and I encourage discussion. This isn't final and will likely need rebalancing and there's likely ranged stuns I may have missed. Please share your thoughts and tell me why you support or don't support this and i'll be actively responding to the discussion here.

I truly think in a medium RP environment combat should be slightly more drawn out to encourage more interesting situations and more RP and less time in perma, or observing the round. I would love for this to become a game of wits and strategy and less of who can click who quicker, though that has its place as well.

There is a poll here on the topic at the forums: https://nanotrasen.se/forum/topic/16427-community-opinion-on-ranged-instant-stuns-and-how-removing-them-can-have-a-positive-or-negative-impact/

**Changelog:**
:cl: Coul
balance: Replaced advanced tasers with disablers
balance: ED-209 now uses disablers instead of a tazer
balance: Remove stun shells from the bulldog shotgun
balance: Remove tazer mode from the AEG, it's still a strong weapon due to its self-recharging and large amount of disabler shots.
balance: energy crossbow now takes two shots to stun
balance: detective revolver no longer instant stuns
balance: Mech taser cannot be crafted from mechfab anymore
balance: blueshields revolver has disabler mode now
balance: ERT now get blueshields revolver instead of taser pistol
balance: donksoft sniper rifle now does 80 stamina damage per riot shot instead of 100
/:cl:

### CODE REVIEW

**Comment by Christasmurf** [comment]
Leaving turrets with tasers? Or changing them to disablers too? Since the AI satellite, upload and telecommunications satellite have those.

**Comment by Couls** [comment]
Those are a different case so they've been left the same way they are.

**Comment by Quantum-M** [comment]
Not really sure on what side to lean on.

On one hand, this makes it so it isn't a near game over when security/a antag gets tazed by a antag/security, making it less infuriating, but on the other, this probably has a bigger impact for security when having to deal with greytiding idiots or antags that are just going loud (e.g. murdering security to not get captured) and being successful on it, and with the low level of competency security tends to have nowadays.

I also feel that antags would want to even _more_ get their hands on the HoS' gun (see the RD's armor and their usage when involving vampires) since it would be the near round start ranged stun device to get (if you have the access/a emag that is) along with stun chemicals (which is a discussion in itself for another day).

**Comment by Couls** [comment]
Stun chemicals are limited, you can't use it multiple times and if you use it in a syringe gun you run the risk of missing, running out of chemicals or not piercing an hardsuit if security decides to show up with those, also the syringe gun is limited to 6 shots before it has to be reloaded which will take time you still can't waste in combat. ontop of these things disablers are still very robust as they inflict slowdown on the first hit meaning you will have no trouble slowing down and inevitably capturing any tiders that decide to screw with security, there are also some interesting tactics you can pair, like slowing them down with the disabler so you can get in close enough to baton. also the HoS being a high value target will always be a thing, let antags target him after all he or she is going to be the only one with ranged stuns capable of taking down anyone who wants to get their hands on them round start.

**Comment by taukausanake** [comment]
This is really weird. Right away I think, "Ha, this is dumb and it'll never get merged," but then I start wondering about it and I think, "Maybe this could work a little but it's still not getting merged," so I don't know. I don't like the taser stuns to be removed completely but maybe Security shouldn't have them right away.
Personally I think I'd keep tasers on ED-209. They're just dumb robots so I feel they should have that advantage of the taser stun

**Comment by Couls** [comment]
they're dumb robots with machinegun tasers, beepsky is already annoying enough in the way that he literally hands up people to security on a silver platter by keeping them permastunned until security responds trust me, disabler ED-209 is still robust. and I don't think making it take time to get tasers would solve the issue of instant ranged stuns, the issue isn't tasers. it's the concept of essentially getting a game over from a single shot.

**Comment by Necaladun** [comment]
Controversial at the very least!

I'd like to see nerfs/changes to stun overall rather than eliminating the sources of it, of which there are...many, from bananapeels to tables to tazers.

If people are interested though, I'd be ok with this as a test merge to see how it plays out, but only for a short term (few rounds).

**Comment by TDSSS** [comment]
Personally, I agree with the taser/AEG changes, but I'd leave in taser projectiles for shotguns (shotguns are clunky to use, IMO). I also don't think the e-crossbow needs a nerf, personally. It isn't used very much and personally, I want antags to use more non-lethal weapons over stuff like e-swords.

**Comment by Couls** [comment]
It's an indirect antag buff if I were to leave instant ranged stuns in for antags but not security, this needs to be universal otherwise i'm going against what i'm trying to argue for

**Comment by Emanthealmighty** [comment]
I think tasers and disablers could just use more energy to fire so that they can only be shot twice or thrice before the whole weapon becomes useless. This would reward those with good aim and not give too many second chances to those with bad aim, while also making people think twice before shooting, giving a runaway traitor more time to run.

**Comment by AzuleUtama** [comment]
We'd need to have a look at some of the other stun methods in the game as well if this got merged, particularly the use of space lube and anything that can slip people. I do agree with reducing the amount of instant stuns in general though so I'd agree with giving this a test merge to see how things go.

Some observations from what has been changed so far though:
- Will sniper rifle rounds need to be changed as well? The regular and compact rounds have a short stun tied to them and soporific rounds will knock people out for a while on hit.
- If we're removing the energy crossbow's stun I'd have another look at the price for it since you're going to nerf if quite a lot in the process given it can't fire as rapidly as other stamina damaging weapons. That or change the e-bow entirely but that's another PR altogether.
- Did the HOS's gun also have its energy consumption changed? When TG nerfed ranged stuns they made it so the gun only had enough charge for 3 tasers shots and the same would probably be a good idea here otherwise we'd end up seeing the HOS charging into maintenance to hunt antags by himself.
- Does this also change the Blueshield's advanced revolver to no longer fire taser shots?

**Comment by Couls** [comment]
Good catch on the blueshields advanced revolver that’s something I missed, I don’t really know if we need to restrict the amount of stuns on the HoS laser just yet and I’ll take a look at sniper rifles the next time I work on this which will be in a couple of hours

Space lube and other stuns and slips will be dealt with in another PR to avoid going off-topic I’ll just say that I’ll be working on implementing crawling soon after diagonal movement is merged

**Comment by Couls** [comment]
It’s not about the amount of shots eman, it’s the fact that even if they had one shot and had to make it count they’re one click away from ending your round and the fact is that it wouldn’t be hard to use your one or two taze shots before you need recharging on catching someone off guard, like I said earlier it’s not about nerfing security or antags it’s a universal thing and the concept of instant ranged stuns needs to be looked at, lowering the amount of instant ranged stuns just won’t do the trick in this case

**Comment by Ty-Omaha** [comment]
security isn't the only one with instant stuns

e-bows are also instant stuns

**Comment by Ratvar** [comment]
"balance: energy crossbow now takes two shots to stun"

**Comment by Mitchs98** [comment]
Been against this ever since it was originally brought up. I'm of the standpoint combat is fine as it is. Sure, instant stuns can suck for both sides of the spectrum, but that's just the way it is. I see very little reason to change things trying to become like other servers much in the same way I saw very little reason for newcrit to be added in. 

Though, I'm hoping this won't actually get merged or even considered in the current state its in. Even more the idea of giving disablers only two or three shots before it runs out of juice someone suggested..that's an even worse idea. As a whole, if it ain't broke don't fix it. I'm aware you and some others prefer the combat system of other servers...but personally I don't see that a reason to fullstop change it for everyone and those that don't.

**Comment by taukausanake** [comment]
I agree with Mitch but I also think tasers should have less shots, just as a middle ground if nothing more. Normal tasers aren't supposed to have a lot of power stored and are used up in two shots, but that's more a limitation on the build not the power. I'd say three shots before it needs to be recharged

**Comment by Mitchs98** [comment]
I'd accept tazer shots being brought down to three, though disabler shots should be left alone.

**Comment by Couls** [comment]
I guess we just see things different then, I really do thing combat can be improved and removing situations with instant losses will help this more than limiting the amount of times you can instantly win. Like I said originally I’d be happy to come to an agreement or compromise but what you’re suggesting is to abandon this idea entirely. I think change is important and a lot of things can be modified and added to help make paradise unique(you seem to think I’m doing this to make it more like other servers) while I’m still taking inspiration from other servers I’m trying to add features I think will help paradise and fit the RP environment if not improve it

**Comment by Mitchs98** [comment]
Changing stuns and combat won't improve RP. If anything people will go for lethal options sooner if a means to incapacitate their target easier/with less risk is removed. Your want to improve RP by this will go the way of people supporting newcrit for the same reasons; it won't impact it. RP will stay the same. People said that Newcrit would improve RP but thus far I've seen no proof of that happening. If anything this'd be more detrimental a change than newcrit was.

Change can be important and a good thing, but not always needed or wanted. You can't just say 'Change is a good thing' as a blanket reason to change everything, when it is infact not always a good thing nor needed. That's just foolish. 

You also say there's lots of things to change or make Paradise unique, when you're clearly trying to port other servers' changes in an edited way more or less making it like them. Paradise already is unique, yes its also built from a lot of TG and other server ports, but at the same time they're usually cherrypicked for the server and kept in mind for our server while being heavily modified. Not just "TG basically has combat like this, so lets slowly change it to be like it.". Your 'compromises' are nothing short of basically mimicking TG's stamina based combat, at-least part of it.

It's not a compromise, it is however actually changing it partially to be like it by removing taser stuns. And as you said, it's only step one. I could probably guess that your next step is impacting stuns further. Would I want part of them changed? Possibly, but not like this.

You're also saying you want to change combat and make it more fair and action orientated, yet you're ignoring a (in my opinion) much more abused portion of combat, and that's lethal memechem deathmixes. Harder to balance? Sure. More of a problem than taser shots that are, usually, not overly hard to dodge? Definitely. Out of scope of this PR sure, but not out of scope of your goal.

What are your plans for them? Combat as a whole? Changes to combat like this need to be discussed with the community on a whole, planned out entirely, and actually have something planned out rather than tossing up a few odd PR's. PR's that will likely not be merged and will cause needless drama and wasted time discussing it.

TL;DR;

Combat as is is fine. We don't need to mimic other servers for everything, and small changes like this that would inevitably set a slippery slope to doing so isn't a good idea. IF we are to change combat to be truly unique to Paradise, a thread should be made that outlines changes everyone wants to properly consider them and lay out the pros and cons of them. Like what was done with newcrit...but better. Instead of tossing up PR's here and there to change certain aspects.

Just know, changing combat most likely still won't impact RP either way, just as newcrit didn't.

**Comment by Dinarzad** [comment]
I'm tentatively for this if it gets rid of the "Stun an Done" nature of the game. It also takes some more niche tools in Security's toolkit and gives them a more desirable use. Stun batons are a risk-reward thing now, and Flashbangs remain as high a value tool then ever, possibly more so with these changes.

I noticed you said round-start tasers were gone, but does that mean Science can still produce them?  If Science can still produce them, I'm not sure if that's a good or bad thing, on the one hand I feel it makes removing them from roundstart at all rather moot as every officer will just come to RnD for a Taser, on the other hand, encouraging Security to come to RnD for upgrades might be a good thing, it pushes them to interact with crew, which might help alleviate the feeling that Security is just around to be shitters, since now you're actually dealing with each other on the regular.  Definitely gives Security a damn good incentive to respond to/be prompt with calls in Science if it's the source of their tasers an shit.

Also a reminder to look at non-weapon based sources of ranged stuns from antags like Changeling or Vampire, etc.  Security would be losing some serious bite with this change, and those other antags would need to be looked at very seriously (Perhaps reducing the radius of Chiropteran Screech, etc. but then it's rather analogous to a Flashbang I suppose, so it might not be necessary, I don't know.)

TL;DR:  I'm not fond of the stun centric gameplay loop we have now, and seeing it removed would be a boon in my eyes. But this is gonna be a real bumpy ride to doing so, balance is going to break, it might be a good idea to get a poll or something up on the forums for community input sooner rather then later.  Not just as feedback for this very PR and further changes, but given how much this is probably gonna break things for a bit and take, likely, multiple PRs to fully implement properly, it'd be good to make sure that's what the community even wants.  If they want it at all, they'll grit their teeth an tough it out, if not, it's gonna piss people off.

**Comment by Spacemanspark** [comment]
you fucking madman

**Comment by Couls** [comment]
Science can no longer produce tasers themselves, I've made sure to get rid of all types of it, i'll soon be pushing a commit that even gets rid of them from mech fabs. I'm trying to be universal as possible with this(excluding AI sat turrets for obvious reasons). They're going to be completely gone and if they're not then I definitely missed something.

**Comment by Couls** [comment]
codersprites for the disabler charge bar, shouldn't be that big of a deal but if someone else wants to redo them that would be neat, can't really take a screenshot because they're just blue bars basically

**Comment by Tayyyyyyy** [comment]
Doesn't the ebow count as an instant ranged stun?

**Comment by Denthamos** [comment]
Mmn, like some others have mentioned while I like the idea on it keep in mind this is hardcore buffing melee stuns.  Especially antags which rely upon such.

Also shadowling glare is a ranged stun which would need to get hit by this as well.

**Comment by Couls** [comment]
Not sure how I want to handle shadowling glare as changing their main ability too much can make or break shadowlings going on in the future, I kind of feel like it's already been nerfed in the way that it's much weaker the further you are away so i'm not sure if I need to wipe it out completely just yet, the way of fighting shadowlings is much different from a lot of the other combat we have so i'll likely be giving that a pass(they can't really instantly win in a one on one engagement as light sources like torches will still prevent them from getting close even if you're stunned)

**Comment by Breenland** [comment]
I’d not mind seeing it tested! Though I am a bit iffy on the complete removal, mechs and all. Mechs should be able to keep theirs for riot suppression, as well as the fact that if someone is stomping around mech tasing people that’s something they can be handled better than officer doing it on foot.

**Comment by davidchan13** [comment]
Why remove tasers but leave flash bangs? This also leaves vampire and shadowling stuns untouched. And it doesn't address how stupidly powerful antistuns like adrenals will become. I get what your trying to do but if you half measure this it's only going to get worse.

**Comment by Couls** [comment]
if I remove stuns from synthetics they effectively become invincible, they already can't be slipped and I think there should still be a way to disable them without destroying them. flashbangs can be seen heard and predicted and is still an important tool for crowd control, without it this would actually be a security nerf. and how do you think adrenals will become more powerful from this? adrenals won't completely heal stamina damage, they actually only heal 75 so you would still have slowdown coming out of stamina crit as you'd still be missing 25 stamina. Disablers are arguably stronger at dealing with adrenals than tasers would be so I don't really understand the adrenal argument. I already explained why shadowling stuns don't lead to instant win/loss situations and why I held off on modifying them, vampire glare requires you to be in one tile range but the screech is a valid concern and i'd like to have discussion on how we can change it to be less of an instant flashbang.

**Comment by Allfd** [comment]
When the person who fires first wins, there is every incentive to fire first and ask questions later.

Instastun, is the reason security does not talk to you before the taser and cuffs come out.

**Comment by Mitchs98** [comment]
I entirely doubt that's the main problem. A minor part as mentioned in my post perhaps. But not the full reason by far.

**Comment by Couls** [comment]
I think it's a major part actually, fact is that people will usually do whats easier. and when ensuring someone can't fight back is easier than talking to them its quite obvious what would be the optimal course of action.

**Comment by Mitchs98** [comment]
The only difference will be antags will use lethals instead of stuns. Same for security. I don't really see anything changing, personally.

**Comment by Dinarzad** [comment]
I'm not sure I agree Antags will jump straight to lethals all the time, because of Paradise's rules on going full murderboner.
 It's usually rather frowned on for an antag to rack up an unnecessary body count, but beyond that, as long as antags are not PERMA-KILLING anyone, I don't think it's a huge deal, maybe it'll help discourage tiders to not validhunt things so hard when they can't instantly lol on a vampire and it can much more easily kill them/non-security personnel.
That could arguably nerf races that can't be cloned, but that's something we can tackle if that change of server mentality comes to pass at all.

**Comment by Couls** [comment]
With new crit in place killing someone will be a lot harder than talking to them still, people will realize they will have to be smarter with how they deal with things and talking is much more viable than doing 300 points worth of damage or shooting them with a disabler and risk them trying to run or attack back, they could also use their stunbatons more but that poses a risk for the officer doing so. either way both antags and security will need to think a lot more before acting

**Comment by AdamElTablawy** [comment]
It’s a positive change for combat, but it won’t impact RP at all.

People shoot at you because they want to shoot at you. They choose stuns because those are the most effective, least damaging weapon in most cases. If you change that, people won’t be less likely to shoot. They’ll still shoot at you first ask questions later regardless of the risk to them unless they get banned for it (IE, they won’t shoot you with a shotgun on sight because they’ll get in trouble for it if you aren’t doing something worthy of death, but will use a disabler since they can just shake you up.)

Still, being instantly hit by a tazer and being out of the round unless you’re on antistuns is annoying, so that’s a fair change. Consider though that you’ll also have to adjust chems and stamina damage regeneration to compensate on needing stamina damage to down someone, as right now stam damage is really annoying to heal off.

**Comment by ktoma36** [comment]
Antagonist roles are meant to spice up the round, bring danger and intrigue as security skirmishes with the threat. On both ends of the spectrum having the ability to instantly put the other combatants out of commission with just one shot is both wholly unfun and dissuades people from taking risk. The best stories that I've heard come from paradise are ones that involve people taking risk and ending up having their efforts rewarded tenfold either in magnificent greentext or hilarious failure. Having methods to circumvent putting oneself at risk not only puts those who want to take on major risk (such as taking a hostage to levy for the HOS's gun, bribing a head of staff for their secret documents, or even pretending to be a demon via chameleon projector and some cardboard cutouts to demand tributes of bananas) at risk of losing their entire round in just a single shot but also encourages antagonist to retaliate in kind. Stunning then killing security knowing that if they do not completely finish off the officer they may get up and get off one lucky shot. 

In my opinion instant stun combat is one of the worse things to have to deal with on Paradise, it leaves you completely vulnerable to, as mentioned above, have your entire round ruined in just one shot. Yes, if this PR is merged then people will complain about the loss of the most risk free way of dealing with each other in the short run. In the long run though I believe this change will bring about much more interesting and engaging interactions with security and antagonist.

**Comment by ktoma36** [comment]
Oh and another taser system that I just remembered about are the space pod ones, one spawns in the sec pod pilots pod bay and could probably be replaced with its disabler alternative.

**Comment by Couls** [comment]
> Oh and another taser system that I just remembered about are the space pod ones, one spawns in the sec pod pilots pod bay and could probably be replaced with its disabler alternative.

Those tasers already fire disablers which makes you wonder why they were named tasers in the first place

**Comment by Mitchs98** [comment]
This definitely needs the controversial tag too. Tbh.

**Comment by C-Kuha** [comment]
I think the Blueshield should still have a taser function, at least. They're a man sent and picked from NT just like the HoS, right? It's a karma job too, and people who have accumulated that karma, 8 times out of 10, will have good role playing skills, and wouldn't jump to the taser immediately. 

The ERT having the Blueshield pistol seems like sort of an issue, too. The advanced stun revolver has always been a weapon unique to the Blueshield job, and it should stay that way.
As an alternative, can you not just modify the taser-pistol the ERT are equipped with now?

**Comment by Couls** [comment]
I personally want to axe as many ranged stuns as possible, and I feel like if the response team sent by NT isn't given tasers than the blueshield likely won't have them either.

**Comment by Couls** [comment]
My current issue is that ERT is kinda just loot piñatas, giving them tasers just allows them to be thrown back into the station and now they’ll be circulating(antags can get them off ERT, others can get them off dead ERT) and with that in mind I already think the gear they get is strong without having tazers(that IK carbine is no joke) from an RP standpoint ERT already has decent gear for what they’re needed for I don’t think not having a taser would be a concern and the only reason it’s even considered as something strange not to have is because it’s been part of their loadout for some time now

**Comment by C-Kuha** [comment]
Well, still from an RP standpoint, the purpose of the ERT is to CONTAIN the situation, and to get the station back under control. Not to absolutely obliterate all the threats. They're for when security cannot do the job. I assume security will have a harder job without ranged stuns (and they CAN function without ranged stuns.) But when the situation is dire, the ERT would come in with their tasers, advanced equipment, and, yes, the laser carbine. 

(Near) Complete removal of ranged stuns would also severely change the meta for combat. It'd take some serious adjusting. I don't think the solution to this all is removing stuns altogether, but limiting them. Say, all of security shouldn't be able to obtain ranged stuns, but certain special jobs, like the HoS and his Multiphase energy gun, the ERT and their taser-pistols, the Blueshield and his revolver, should have access to them. The HoS requires time on security, and gives people an opportunity to learn the game as regular security officer before being something like the HoS. The Blueshield is a karma job, so only people which would have accumulated that positive karma (likely from RP or excellence in their gameplay) would be able to play it.

You have an excellent idea, don't get me wrong. Ranged stuns deserve a change, but they do **not** deserve to be removed so severely.

I really don't think the solution is to completely remove ranged stuns. It'd serve the community much better to limit the distribution of ranged stun weapons.

**Comment by Couls** [comment]
They can still effectively contain a threat non lethally by using their disablers, and are still capable of getting the station back in control. They don't lose a non-lethal option here. they still get a disabler they just don't get a taser. I really wanna give as little ranged stuns as possible a shot before deciding who may or may not need to be given back some ranged stuns because the optimal situation is for nobody to have an instant win from a distance excluding some extreme situations(wizards will obviously need this as they're pitched against usually more than 50 people)

**Comment by C-Kuha** [comment]
Well then maybe the solution is making instant ranged stuns not as worth it for the people who have it. I.E, making it have less range, making stun shots use up more power, etc etc.

Another idea would be to make the ranged stuns... not instant? This is a PR for the removal of INSTANT ranged stuns. Perhaps things like range, physical health, or any mix of other things would allow a taser shot to NOT instantly put someone on the floor.

**Comment by Couls** [comment]
Wouldn’t be a taser anymore if it didn’t take down immediately, instead of completely reworking tasers which would take lots of time effort discussion and balancing it’s much easier to use disablers that were already made to stun in multiple shots as opposed to one

**Comment by C-Kuha** [comment]
Hm, I suppose you'd be right about it not being exactly a taser anymore. But even then, the best solution for more engaging combat is definitely not to remove tasers near-completely. I stick to my statement that the solution is severely cut distribution to roles like the Blueshield or the HoS.

Relating to the Blueshield, why give the ERT the Blueshield's revolver instead of modifying the ERT's taser pistol?

**Comment by Couls** [comment]
Need to remember to change mime's finger guns to not be an instant stun as well

**Comment by Drakeven** [comment]
I like this idea. Combat can end so quickly with tasers...

**Comment by JKnutson101** [comment]
I think I'd honestly be for this at the end of the day. Obviously balance going forward would need to be adjusted, (stuff like vampires) but excluding hyper lethal methods like a sniper to the head, combat shouldn't be over in one hit.

While I think the straight removal is fine, if they're not removed, perhaps more ways to resist insta-stuns would make more sense. Considering tazers are supposed to be electricity, and stuff like insulated gloves + engi-suit make you immune to Tesla tier electricity, it's really silly that a dinky tazer can stun through that.

**Pull request closed without merging**
