### PR TITLE
Grey mask update

### PR DESCRIPTION
**Pull request by Jovaniph**
Breath Mask
frontsidefrontupsideup

Gas Mask
553a52530ad555a7d2a6c62e1c986841

Cyborg Visor
4a96b4f2349df72946386dc63b5474d3

🆑 Jovaniph and Dumbdumn5
rscadd: Greys have new mask: Breath, Gas, and Cyborg
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Good to have 'before' images for comparison, but these look good

**Comment by Jovaniph** [comment]
you want a before image? They technically exist...they....hold on.

**Comment by Jovaniph** [comment]
gasmask1gasmask2
breath1breath2
cyborg1cyborg2

**Comment by SamHPurp** [comment]
Good to see the comparison - yours are miles better! 👍

**Comment by Ionward** [comment]
my only change would be to make the gas mask's eyes more saturated/brighter, like these 
gasmasks

**Comment by Jovaniph** [comment]
@Ionward You'll have to talk to Dumdumn5 for that. He made the Cyborg and Gas Mask.

**Comment by Fox-McCloud** [comment]
The gas mask doesn't match at all; it should be identically shaded+colored, only fits to the Grey better.

The cyborg visor is virtually flat--it doesn't even look like a mask so much as a sheet over the face.

The breath mask is good though.

**Comment by Dinarzad** [comment]
This new era of Grey related PRs has me excite.

That said, the gask mask could use a bit of a tweak around the eyes, like Ion said, to make them match up better to other gask mask sprites when worn.

**Comment by Jovaniph** [comment]
Gas mask has been update to meet the same color scheme as the other...please note that the one in the picture may appear to be darker because the gas mask are transparent.

**Comment by Dinarzad** [comment]
Looks to good to me, I like it.

**Comment by Jovaniph** [comment]
Cyborg and Gas Mask updated thanks to Dumbdumn5.

**Comment by Jovaniph** [comment]
ownage

**Comment by Jovaniph** [comment]
No additional feedback (from admins or maintainers) and PR been open far too long than it should have. Closing it since I got other projects I could be working on.

**Pull request closed without merging**
