### PR TITLE
CLOROX BLEACH: DRINK 2DAY!!!

### PR DESCRIPTION
**Pull request by MoreRobustThanYou**
clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox clorox 

monkeys
maxresdefault

:cl:
fix: fixes every bug in existence!
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
I support this.

**Comment by taukausanake** [comment]
Man, I didn't even get to see what this was. Guess I got to peek into the .dmi

**Comment by MoreRobustThanYou** [comment]
@taukausanake have fun 
clorox

**Comment by MoreRobustThanYou** [comment]
tbh it's just a Clorox bleach sprite i found online downscaled to 32x32

**Comment by taukausanake** [comment]
You downscaled it good! Lines stayed straight. Not always easy

**Pull request closed without merging**
