### PR TITLE
Increasing beaker size to current Bay size

### PR DESCRIPTION
**Pull request by IDTia**
BayStation beakers are 60 units and large beakers 120 units. This makes complex chemistry less messy for me at least. Only 6 lines are changed, but the entire thing is marked as changed for some reason, not sure.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
What's the max size for pills right now? 50?

**Comment by IDTia** [comment]
Current pill size is 50, but I am pretty sure that it is still 50 on bay, checking now.

**Comment by PJB3005** [comment]
add pls, it makes a lot of sense since a lot of recipies come in factors of 3

**Comment by IDTia** [comment]
Should pill size be increased as well? Would be useful for those who actually make complex combinations that treat all damage types.

**Comment by ZomgPonies** [comment]
I think max pill size should probably be increased to 60 to fit with the chemistry multipliers.

**Comment by IDTia** [comment]
Looking into adjusting all the values right now.

**Comment by IDTia** [comment]
Alright everything should be adjusted properly. ChemMaster pill creation, pill size itself, and beaker size

**Comment by Fox-McCloud** [comment]
:-1:

Thumbs down from me. Beaker bombs are already strong enough, as is, with current beaker sizes; if a chemist wants the extra 20 units for chem mixing, he can ask botany, cargo, or the janitor for a bucket.

**Comment by ZomgPonies** [comment]
What are the current sizes? 50 and 100? How about making them 60 and 90 to fit with the '15' syring multiplier?

**Comment by Fox-McCloud** [comment]
Current sizes are: 50 (small), 100 (large) , 120 (bucket), and 300 (bluespace).

While 90 matches up nicely with syringes, it doesn't play as nicely with chem mix straight from the dispenser; there's still quite a few recipes that have even numbers of chems that result in even amounts of output, so--either case, 90 or 100 you're not going to come out with perfect nice little numbered results.

**Comment by ZomgPonies** [comment]
Unless this PR can provide perfect numbered results, I'll need to :-1: also

**Comment by Fox-McCloud** [comment]
Just did some testing:

100+100 beakers of potassium+water:
explosion size: 0,2,5

120+120 beakers of potassium+water:
1,3,7

That quite easily takes it from wall popper to floor puncher.

**Comment by TheDZD** [comment]
Going to have to say :-1: as well. I don't believe we should look at Baystation much as far as balance is concerned, as many of their gameplay features are balanced to a heavy RP environment, while Paradise is anything but. We have quite a few players that are incredibly good at min-maxing when it comes to game mechanics, and that should be kept in mind when making balance changes, especially to something that's already as powerful as chemistry.

**Comment by ZomgPonies** [comment]
Legitimate balance issues were brought up. The PR couldn't give enough benefit to overcome them. Two maintainer thumbed it down. Closing.

**Pull request closed without merging**
