### PR TITLE
Xeno-Botany Quality of Life Changes

### LINKED ISSUE #1409: no machine boards for lysis/ballistic and broken apples
Both these issues exist on bay as well as far as I know.

You can't reconstruct or construct the lysis centrifuge or the ballistic thingymabab because there's no board for them or definitions for machine components. If these could be added to the circuit imprinter/machine definitions that'd be pretty neat. 
No need for upgrade code or anything, but if you do you could make better parts destroy the genome slower in the lysis machine/allow for more mutations in the bioballistic before they become unviable.

 As for apples, their icon or something is broken. They come out of the vendor as question marks, and attempting to use them in the lysis/bioballistic will freeze those machines up permanently, which is a problem because they can't just be torn apart and put back together RE: previous issue.

Also side thing that I'm not sure is actually an issue, as it might be intentional? Poppys don't have any reagents at all.

### PR DESCRIPTION
**Pull request by FalseIncarnate**
De-obfuscates the gene masking for the xeno-botany machines and discs.
image
- Rather than seeing a bunch of random numbers and letters, each gene set now displays a plain-text name.
 - No change to functionality, just removes Bay's famous "complexity for the sake of complexity" from it.

Adds a connector and some pipes to hydroponics to help with gas consuming/producing plants.
image
- Connector added to the back room for canister hookup, and to the "isolation tray" for plant-use.
 - More can be installed with assistance from a bored engineer/atmos tech
- Pump added to new pipes below the left-most locker in the back room to allow you to dump the "harvested" gas into the scrubbers network for atmospherics to filter out safely (or to empty out that canister you stole from maintenance)
- Map changes are map-merged

A long-requested feature, you can now (re)build the two xeno-botany machines
- Lysis-Isolation Centrifuge
 - Requires 1 matter bin, 1 scanning module, and 1 console screen
 - Upgrading the scanning module causes less degradation when extracting genes, meaning seeds last longer (probably not a big deal now, but whatever)
- Bioballistic Delivery System
 - Requires 1 matter bin, 1 manipulator, and 1 console screen
 - Upgrading the manipulator decreases the degradation caused by splicing genes, meaning you can (theoretically) splice more onto a pack before it fails
Map changes are map-merged.
- Boards for both machines now are able to be made in science with biotech and programming 3, and thus also have these set as origin techs.
- Fixes #1409
 - Well, the part that wasn't technically fixed with the last time I "fixed" it.

:cl:
tweak: Xeno-botany is now more user-friendly, and less random letters/numbers.
rscadd: Hydroponics now has a connector hooked up to the isolation tray and a new connector in their back room for those strange plants that like spewing plasma or eating nitrogen.
rscadd: You can now (finally) build the xeno-botany machines, and science can print off their respective boards.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
That is wonderful but I still wish we had means for pressure and temperature

**Comment by Fox-McCloud** [comment]
Merge commits >=(

**Comment by FalseIncarnate** [comment]
The merge commit is from updating to include your map edit from your science PR. Was hoping it wouldn't have shown up, but since I had already committed the first bit, it was too late to turn back on that branch.

**Comment by TullyBurnalot** [comment]
No more "random RNG research for wasting time" each round?

:100:

**Comment by taukausanake** [comment]
@FalseIncarnate I know how the plant pressure and temperatures work, my disappointment is that we don't have any means to do that yet without atmos helping.

I wonder now, if a plant needs a certain pressure and/or temp and also creates a gas but you have to use the tank, what happens?

**Comment by Fox-McCloud** [comment]
botanical research no with -1 retardness

**Comment by taukausanake** [comment]
I just noticed the top bit of the OP. I don't know if I like knowing what I'm _researching_. I originally thought but never made notice of if the machines were constructable then you could upgrade them then you could unlock the machine's ability to know what the gene is. Also maybe extract separate bits of a gene, like appearance and reharvestability that share the same block

**Comment by FalseIncarnate** [comment]
Xenobotany has never been researching the genes, but rather researching new ways to combine them via hybridization. The only real unknowns are the traits of the randomly generated strange seeds. 

Obviously the contents of the genes are something you can learn via experimentation and/or the code, and previously you had to spend time figuring out which button the genes were on. There was no research to be had in that, only a horribly watered-down game of Simon.

I'd rather not go back to re-obfuscate these genes only to re-de-obfuscate them with upgrades (something that would require a fair amount of tweaking to both the gene list and the nanoUI templates of the machines). Breaking up the gene sets into their base traits would be a major balance change, and not something I'd be comfortable doing with this PR.

**Comment by taukausanake** [comment]
Maybe in the future then. I consider it research though, kind of like how Genetics has to find mutations

**Comment by Mijhead** [comment]
:+1:

**Pull request merged**
