### PR TITLE
Virus Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Virus code is horrible and terrible (COLONS) and no I'm not going to fix it myself except for leaving this here: *scream

Adds a number of new virus symptoms
- Projectile vomit: vomiting
- Borgification Disorder: turns you into a borg

Additions
- Utilized Virus2 to best recreate the old borgification diseas tied to the disease-reagent "Nanomachines"

Changes
- Poop symptom is now handled by a proc. Pooping no longer lowers nutrition and it doesn't contain viruses held by the host anymore. Given this change, it's purely an aesthetic symptom now (and thus has been move down to a stage 1 symptom).
- Longevity no longer deals a ton of damage when it deactivates.
- Removed fizzle effect (kinda already covered with the invisible symptom stage 4)
- Removed some unused virus symptoms

Other semi-related
- Added nanomachines as a potentially selected reagent for traitor poison bottles.

Fixes
- Made some adjustments to various effects/symptoms so they're not so lethal (by accident) or are actually effective (or in one case, adds a reagent that doesn't exist).

### CODE REVIEW

**Comment by tigercat2000** [comment]
> Goon Symptom: farting

please
please no fox
please no

> poop being moved to first stage

please fox
please no
this is a horrible idea
please don't make it any more common
regardless of "gameplay effect" it's horrible enough

> everything else

eh.

**Comment by Fox-McCloud** [comment]
Stage 1 isn't any more common than stage 2; the stages are purely indicative of the symptom's strength, not how common they are (or not); in its current state it has a gameplay effect, which warrants it being stage 2 over stage 1---now that it's purely aesthetic...well, yeah, makes no sense for it to be 2 anymore (other than coder irony =p).

Excessive flatulence is a genuine medical condition indicative of a number of viral infections!

**Comment by Earthdivine** [comment]
I don't mean to be rude with this but farting was already shot down as an emote, adding it in as a virus symptom, while it being a true medical condition, will look like it's being loopholed or added in in a different variation. I would make a post about adding it in on the Code Discussion to avoid bad backlash over it.

Also making poop...while I don't like it either it feels more like it was meant to be a type 1 symptom anywas

**Comment by Krausus** [comment]
One roburger contains enough nanomachines for 50 doses. A single dose will infect someone with a virus that converts them into a robot minutes after they've been infected, with no warnings whatsoever unless you get lucky with the 50% chance to not turn into a cyborg **immediately after the first and only message you get.** By then, it's probably already too late.

Their old body is gibbed, and their ghost is forced into a newly-generated cyborg. The victim will, of course, not be able to return to their old body.

This is, by a huge margin, the single most ridiculously abusable player-obtainable reagent in the game. People can be silently infected without realizing it, without any warning, and won't know about it until easily 15+ minutes later, when they suddenly explode and are a cyborg. A griefer who knows what they're doing can infect people without leaving logs that make it feasible for admins to discover the culprit. For someone who has a legitimate reason to kill someone else, there is nothing nearly as effective and discreet.

Why would you do this? Why would any sane person do this?

**Comment by Fox-McCloud** [comment]
'cause we kinda had it before--and all codebases kinda have it with...hardly any controversy or complaints generated by it. 

I mean, I can hypothetically modify it so there's a 2 stages to and make it start at stage 1 instead of 2, to make it a bit closer to the original disease, but all in all--yeah, still fairly close to what we had before.

**Comment by Krausus** [comment]
> 'cause we kinda had it before--and all codebases kinda have it with...hardly any controversy or complaints generated by it.

What the other codebases have is a disease with 5 stages, where each stage past the first has a mixture of personal warnings *and* externally-visible symptoms, and this disease is cured by simply injecting copper. You get tons of warning, and curing it is trivial.

What you've made is a virus that gives no indication you've been infected until it's hitting the 50% chance to convert. You have a 50/50 chance to get no warning whatsoever before, bam, you're a cyborg. And it has to be cured the same way any other virus is - slowly, using radium or virology. Which doesn't actually make any sense for *nanomachines.*

**Comment by Fox-McCloud** [comment]
@Earthdivine 

Removed the Goon Syndome; not worth the fight.

**Comment by Earthdivine** [comment]
nofun

The robo one was too big...

**Comment by ZomgPonies** [comment]
The original use for the pooping syndrome was as a vector and symptom for diseases. You just removed it's utility as a vector, for no apparent reason? :-1: Because of that.

**Comment by Robertha89** [comment]
Blank symptomes are great for making specific viruses, or even super lethal ones, 3 blank symptoms and one lethal, and the pooping is the best way to spread the disease, as you can't customise how it is spread. I do love the concept behind nanomachines, but ya havent been able to make it since the new cooking update about a year ago. While I agree that the virus symptoms need somewhat of an overhaul, this is not a good way to go about. The reason longevity damages you is cause when cured, you are supposed to age like 15-20 years, and gain damage due to that. Regarding the Rapid Synapse effect, 15 units is still too high due to addictions

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

It's actually not a vector; stepping in feces doesn't infect you, on live.

**Comment by Fox-McCloud** [comment]
fixed up meth causing addiction and renamed the haloperidol virus

**Comment by Iamgoofball** [comment]
what

we have poop and poop is a thing

but fart is too far

?????????

**Comment by ZomgPonies** [comment]
Shouldn't have merged this before the roburger stuff was addressed. That was my mistake.

**Pull request merged**
