### PR TITLE
Minigibber toy

### PR DESCRIPTION
**Pull request by tigercat2000**
This commit adds a minature gibber toy (/obj/item/toy/minigibber), which
uses a downscaled sprite of the gibber.

Features:
 - Plays a gibbing noise when you click on it with itself, cooldown of 8
   ticks applies.
 - It's a minature gibber.
 - Custom attack verbs (grinded, gibbed)

picture of minigibber in comparison to regular gibber
attack text

## UPDATED!
You can now use any of the DnD minifigure characters as victims!

Simply click on the minigibber while holding a minifigure to put it in, then use the gibber to grind it to bits, for ``Realistic Gibbing Action™.``
burrnn
_before you ask, no, there isn't a way to get it out. Shouldn't have put something in the minigibber if you wanted it back!_

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
*sigh*

**Comment by Krausus** [comment]
No way.

Not until you can feed miniatures into it.

It *needs* Realistic Gibbing Action™.

By the way, you spelled "miniature" wrong. Twice.

**Comment by tigercat2000** [comment]
@Krausus Minature is spelled how I want it spelled! :angry:
(will fix)

**Comment by Nienhaus** [comment]
It's so cute!

**Comment by ZomgPonies** [comment]
Needs to allow Minis and D&D figurines to be gibbed :D

**Comment by tigercat2000** [comment]
@ZomgPonies Already done, it can eat the D&D figurines. Not sure what you mean specifically by Minis

**Comment by Earthdivine** [comment]
It's official, tigers lost it all.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

You and I both know he's never had it =V

**Comment by tigercat2000** [comment]
<3

**Pull request merged**
