### PR TITLE
Removes Telecomms

### PR DESCRIPTION
**Pull request by TheDZD**

### CODE REVIEW

**Comment by tigercat2000** [comment]
:eyes:

**Comment by Plotron** [comment]
Remove TComms pliz.

**Comment by Spacemanspark** [comment]
Dammit, you got me this time.

**Comment by LittleBigKid2000** [comment]
For some reason, the server was patched, but I'm not seeing any changes in the changelog

**Comment by CrAzYPiLoT-SS13** [comment]
I hope it isn't my changelog notification tweak D:

**Comment by TheDZD** [comment]
The repo on the server synced before this got merged, which is why it isn't showing up.

**Pull request merged**
