### PR TITLE
Adds sprites for Coated Reinforced-Walls

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
add: Coated Reinforced Walls now have unique sprites
/:cl:
coated_reinforced_wall - copy

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
Yaay 🎺

Did you test if they all properly work?

**Comment by Norgad** [comment]
@FreeStylaLT Yep, they work fine. Not surprising, as they are just an rwall subtype. I'll do some screenshots of them in use.

**Comment by Norgad** [comment]
Wow, So nice!
2016-08-12 21_42_21-greenshot



Somebody forgot to coat this. Naughty!
2016-08-12 21_54_36-greenshot

**Comment by FreeStylaLT** [comment]
Oh crap the bottom rwalls are not coated, shiii-

**Comment by FreeStylaLT** [comment]
Also, I meant the disassembly sprites. Are you sure they work?

**Comment by Norgad** [comment]
I'm pretty sure they worked too. I'll double check later

**Comment by Norgad** [comment]
Yep! All the sprites work fine!

**Pull request merged**
