### PR TITLE
Wordlist Tweak

### PR DESCRIPTION
**Pull request by Kyep**
Removes the word 'faggot' from certain messages on the server.
Reasoning should be obvious: if using that word as a player will get you banned, the server shouldn't be sending it to you in any automated message.
Based on https://github.com/ParadiseSS13/Paradise/pull/6996 - but with less controversial changes.
🆑 Kyep
tweak: Slight adjustment to word lists based on our rules.
/🆑

### CODE REVIEW

**Comment by Fruerlund** [comment]
Agreeable on this one, we cannot ban people and then throw the word around.

**Comment by FreeStylaLT** [comment]
Glad to see this get removed. It directly violates our rules, despite being restricted entirely to code.

**Comment by tristan1333** [comment]
We should replace faggot with cunt. It's got the same strength but isn't rule breaking. Asshole is just... Weak.

**Comment by KasparoVy** [comment]
gdoruge mwrlins

**Comment by Allfd** [comment]
You may wish to check AI names also, we ran into this issue like two nights ago

**Comment by SamHPurp** [comment]
@Allfd The only one is "Fagor" - unknown if that is a supposed allusion to it or not, but I don't expect anyone would miss it if it went, either way.

**Comment by Anoonki** [comment]
Man, I remember playing in the round that this PR went up in, and seeing that Kyet was online, and that there was a gateway automaton shouting "...faggot!" on 5 minute intervals and just expecting to see the PR.
Then to actually get it pop up in the same round was just too good.

**Pull request merged**
