### PR TITLE
MAKING PARADISE GREAT AGAIN.

### PR DESCRIPTION
**Pull request by PJB3005**
WE'RE GONNA BUILD A WALL AND THE FURRIES ARE GONNA PAY FOR IT.

On behalf of @Spacemanspark 

<sup><sup><sup>Okay this is REALLY a meme PR</sup></sup></sup>

### CODE REVIEW

**Comment by TheDZD** [comment]
Still doesn't properly fucking remove anything.

**Comment by KasparoVy** [comment]
Desperate and cringey

**Comment by Earthdivine** [comment]
Still doesnt do it properly. Plus only goes after Tarjan and Vulp. 

Do not do this again please.

**Comment by KasparoVy** [comment]
Desperate and cringey

**Comment by Rapidvalj** [comment]
Please stop

**Comment by Jaywings** [comment]
Disgusting.

**Comment by EpicCharger** [comment]
Yay furry hate. Ain't it grand.

**Comment by Iamgoofball** [comment]
:+1: removes sexual fetishes from the game

**Comment by LightningLynx** [comment]
@EpicCharger 

If furries on this server could stop hijacking it and trying to make it their own personal little playground for them and their friends, sitting around chatrooming instead of playing the game, and make some attempt to actually integrate then it wouldnt be such an issue. Unfortunately there are so many people on the staff who perpetuate this that it's never going to change.

**Comment by Vivalas** [comment]
10/10 always get a chuckle when meme PRs have contention. I kinda wish this was real though.

**Pull request closed without merging**
