### PR TITLE
Makes it painfully obvious not to use plain old /turf/simulated/floor

### PR DESCRIPTION
**Pull request by Crazylemon64**
Probably will make some mapping look weird, but that floor doesn't behave properly - will react to crowbar, but won't actually yield tiles, for example.
bad_tile
Here's how the flooring you shouldn't use will now look.

### CODE REVIEW

**Comment by Gummin** [comment]
Why keep it in the game at all if It's not meant to be used?
_Sorry for my ignorance._

**Comment by Crazylemon64** [comment]
@Gummin It's a base path of the other floors we have - similar to the situation for the invisible "animal" that rarely summons from xenobio - it's a result of a base class that doesn't actually have any meaningful definition, that thus malfunctions when used.

**Comment by Gummin** [comment]
@Crazylemon64 Ah, thanks.

**Comment by Tastyfish** [comment]
Based on my regex check, it looks like only `_maps/map_files/debug/smoothing.dmm` still has it, but my regex could be wrong and it's always good to prevent people from dropping down the wrong turf type.

**Comment by Crazylemon64** [comment]
It was also present in admin buildmode, but I fixed that now so they won't be painting with PAIN after this change.

**Comment by Tastyfish** [comment]
Ah good.

**Pull request merged**
