### PR TITLE
Fixes exotic blood not working.

### LINKED ISSUE #10020: IPC leaking
**Problem Description**:
IPC's don't leave visible evidence of leakage.

**What did you expect to happen**: 
For leaking IPC's to actually leave visible oil trails or spots.

**What happened instead**:
No oil. At all.

**Why is this bad/What are the consequences:**
A merge was made that gave the IPC the ability to "bleed", but no such effect has been observed after merging.

**Steps to reproduce the problem**:
1. Spawn or be an IPC
2. Bash the IPC, or be hurt as IPC
3. You should now start leaking without visible effects.

**When did the problem start happening**:
since #8894 was merged.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing else.

### PR DESCRIPTION
**Pull request by alex-gh**
**What does this PR do:**
fixes #10020

**Changelog:**
:cl: uc_guy
fix: IPCs and slimes now have an effect on the floor when bleeding.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
why 4?

**Comment by alex-gh** [comment]
We need a certain amount of reagent to make the turf react. 

As for why exactly 4: I played around with it until I believed that the bleeding started early enough.

**Comment by KasparoVy** [comment]
Able to define that value in a relevant location so it isn't as magical?

**Comment by alex-gh** [comment]
Sure. Would a variable definition with a short comment right before use be sufficient?

**Comment by variableundefined** [comment]
Maybe a define then like EXOTIC_BLOOD_MULTIPLIER with a comment explaining why

**Comment by Mitchs98** [comment]
Wait. Will this make slime blood slip everyone again..?

**Comment by variableundefined** [comment]
Yes

**Comment by Citinited** [comment]
I have no idea how blood code works, but wouldn't a better solution be to figure out why this occurs in the first place instead of just multiplying by an arbitrary value to get blood to appear?

Like, move the `..()` round and see what happens... etc.

**Comment by Mitchs98** [comment]
I don't entirely look forward to slime people becoming walking slip machines, but eh...

**Comment by Citinited** [comment]
fair enough

**Comment by KasparoVy** [comment]
If you ain't slipping you ain't really living

**Pull request merged**
