### PR TITLE
Adds a lot of AI holoapds to the NSS Cerebron

### PR DESCRIPTION
**Pull request by Daylight2**
## What Does This PR Do

Adds a lot of holopads to the NSS Cerebron.

## Why It's Good For The Game

The NSS Cerebron (metastation) has a lot less holopads than other maps do, and it can be annoying when you want to talk to somebody as an AI, only to realize that there are no holopads within range. This should bring the map roughly to parity with the Cyberiad.

## Images of changes

See mapdiff.

## Testing

Hopped on as AI, appeared on a few holopads.

## Changelog
:cl:
add: Added more AI holopads to the NSS Cerebron.
/:cl:

### CODE REVIEW

**Comment by Daylight2** [comment]
I'm sure this will have no merge conflicts

**Comment by Henri215** [comment]
image

**Review by Henri215 — COMMENTED** [review]
image

Eh.. one inside here??

**Comment by Daylight2** [comment]
> image

Note that some of the red holopads are holopads that were removed so they could be shifted somewhere else.

**Comment by Daylight2** [comment]
> image
> 
> Eh.. one inside here??

Yeah, I'll take that one out, and do another pass soon-ish. Forgot to put any inside the armory too.

**Review by Henri215 — COMMENTED** [review]
image

Places like these do need a holopad?

Its looking good, i just have a feeling that one or two rooms are too much populated with it.

**Comment by Daylight2** [comment]
> image
> 
> Places like these do need a holopad?
> 
> Its looking good, i just have a feeling that one or two rooms are too much populated with it.

While it's true that the equivilant area on the Cyberiad doesn't have a holopad there, it's not u common for that area to end up breached from karp and/or for crew and some antags to bunch up in that area.

It's worth remembering that holopads are a role-playing device - the AI still needs cameras to actually see and mess with stuff. They allow for more personal and interesting role play oppurtunities than simply announcing ";Grey Mcshirt, stop hacking into xenobio", and I can't think of many ways for the AI having access to a holopad to be a 'bad' thing.

**Review by Henri215 — COMMENTED** [review]
image

image


image

Two of them were hidden by spawners, causing you to not see it when placing another one.

**Review by Henri215 — APPROVED** [review]
holoapds are looking good to me

**Review by S34NW — APPROVED** [review]

**Comment by S34NW** [comment]
Please manually deconflict and then ping me

**Review by S34NW — APPROVED** [review]

**Pull request merged**
