### PR TITLE
[FIX] Better Magboots icons

### PR DESCRIPTION
**Pull request by larentoun**
## What Does This PR Do

- Wizard magboots 1 pixel to hide feet
- Vox magboots are better

## Why It's Good For The Game

Magboots now hide feet when it didn't

## Images of changes

We'll see in the icondiff

## Changelog
:cl:
fix: Better Magboots icons
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
You have a LOT of unrelated boot sprites being added here.

**Comment by larentoun** [comment]
> You have a LOT of unrelated boot sprites being added here.

I see, that's why I wanted to see icondiff

**Comment by larentoun** [comment]
Now it should be good

**Review by Sirryan2002 — APPROVED** [review]

**Review by Henri215 — APPROVED** [review]

**Comment by DGamerL** [comment]
For the next time, could you please put images in the appropriate section? Icondiff doesn't play nice with mobile viewing!

**Review by S34NW — APPROVED** [review]
Please deconflict for merge

**Review by S34NW — CHANGES_REQUESTED** [review]
PR ready for merge but stale, please deconflict for merge

**Review by Sirryan2002 — APPROVED** [review]

**Comment by larentoun** [comment]
I've done an oopsie, well... RIP that PR then

**Pull request closed without merging**
