### PR TITLE
RnD Fixes and Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
R&D Tweaks

- Adds in unique sprites for all stocks parts (impacts scanning modules and capacitors only, really)
- Removes the cartridges and PDAs from the protolathe (not all bad news, more on this below!)
- Removes the binary encryption key & freedom implant from the protolathe (these were just too easy to acquire and too high of impact; you're meant to spend TC on these things)
- Removes the loyalty, chem, and implanter from the protolathe (we've wanted to reduce access to loyalties and the other two are now easily available from cargo)
- Bluespace toolbelts no longer have a 5% chance of being owlman's belt (sorry, superheroes aren't made via protolathe)
- Tweaks numbers on some borg modules to prevent round-starting powergaming from borgs with the movement speed module+gold from the vault
 - Effectively, the only locked items in R&D now are firearms/guns.

Fixes (R&D)
- Fixes a bug where you could keep making items from the protolathe/circuit imprinter as long as you had even a fraction of the material to make said item

Additions
- Reworks the cartridge vending machine so it has PDAs and all non-locked carts that were previously in the protolathe; can purchase PDAs or cartridges here now (even has 1 each of the mime and clown carts as contraband)
- Replaces the laptop vending machine in cargo with a PDA/cartridge vendor (there's still another laptop vendor around; the other in tool storage)

### CODE REVIEW

**Comment by tigercat2000** [comment]
As far as I can see, This PR does not leave any way to produce the command staff PDA cartridges. I don't think they should be completely unobtainable from anywhere other than the command staff themselves and the one spare in their locker. Especially when, as an example, the CMO cartridge is very useful to chemists if RnD currently ever gets around to producing it.

**Comment by Markolie** [comment]
"Removes the loyalty, chem, and implanter from the protolathe (we've wanted to reduce access to loyalties and the other two are now easily available from cargo)"
Ehh, not sure if it's needed. Especially the chem implant.

**Comment by Earthdivine** [comment]
Making the implanters order from cargo makes a bit more sense then printing them off in RnD, since it follows how Loyalties works before.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

I considered that, but in all my time of playing R&D and watching it be played, the amount of times someone has requested a cartridge? I can count on one hand. The times where someone requested a head cartridge? Zero. Had a few requests for PDAs, but that's about it (which are just purchased at a vendor now)

@Markolie 
Few reasons why I did it:
- They're locked, and therefore not useful to science
- Sec hardly ever uses the chem or tracking implants they have
- Preparation for the *potential* implementation of firing pins, which doesn't have locked boxes.

**Pull request merged**
