### PR TITLE
Replaces humans with corgis

### PR DESCRIPTION
**Pull request by Crazylemon64**
Fixes a whole bunch of things
* Unable to vandalize station, reducing grief potential
* Cannot validhunt directly
* No hands to get burned on lightbulbs
* Much simpler medical system, and thus more extensible in the future
* Much more adorable sprite than humans
* Will not be a major change for vulpkanin(and taj, to a lesser extent) players
* Don't show actual gore or dismemberment when hurt, meaning the game is suitable for more people
* Lack of accesses means that people can no longer sneak into atmos and plasmaflood
* Eliminates species cliquing

For these reasons, and more, all players are replaced with dogs.
:dog: :poodle: :dog2: :wolf:
We shall become dogs of a new age, and you canine't believe how this will revolutionize gameplay.

:cl:Crazylemon
tweak: Humans are now dogs
/:cl:

### CODE REVIEW

**Comment by LittleBigKid2000** [comment]
:+1: :x: :100:

**Comment by Yukiona** [comment]
:dog2: Speed merge! :poodle:

**Comment by LittleBigKid2000** [comment]
https://youtu.be/Tao67Idz3Uc

**Comment by FlattestGuitar** [comment]
"Oh wow, Crazy is doing changelogs now" 
*looks at code*
"Oh, wait"

Living up to your name, Madlemon.

**Comment by Dumbdumn5** [comment]
Fuck yeah, why not, just put this into a button and the bus will occur... :+1:

**Comment by Keilden** [comment]
Add pugs and borgi as karma races

**Comment by Fox-McCloud** [comment]
I'm deeply offended by this.

I personally identify as a German Shepherd.

Maybe if you made a subtype of corgi that looked like a German shepherd, but that would just come off as too close to re-enforcing breed stereotypes.

**Comment by Necaladun** [comment]
Can we call them alsatians to not have Nazi Stereotypes please?

**Comment by Fox-McCloud** [comment]
>Can we call them alsatians to not have Nazi Stereotypes please?

That doesn't sound very breed-neutral.

**Comment by Necaladun** [comment]
For the sake of inclusiveness we need to have every single breed of dog ever then. I don't like this "breed-neutral" bullshit.

:-1:. Do not merge. Tag with controversial please.

**Comment by theColdflame** [comment]
:-1: quite frankly this is just racist to pitbull players

you should feel ashamed of yourself

**Comment by NTSAM** [comment]
i just woke up
i don't know whats going on
help 😱

**Comment by Spacemanspark** [comment]
I didn't order these memes.

**Comment by ProperPants** [comment]
But I'll gladly take them.

**Comment by kylejen** [comment]
I feel triggered by you forcing these society norms onto me! :Dog: :poodle:

**Comment by Tastyfish** [comment]
Preview of new rigsuit sprite [Rigsuit](http://corgisdressedasthings.tumblr.com/image/12657697592)

**Comment by TheDZD** [comment]
You've gone and done it now.

**Comment by monster860** [comment]
The `Dafuq?` label was created just for this PR. I like it.

**Comment by TheDZD** [comment]
Oddly enough, we've had the label for a while now, just never used it.

**Comment by Tastyfish** [comment]
All of the refactors of the past year have led up to this.

**Comment by ProperPants** [comment]
my fucking eyes when I viewed the hub

:skull: :eyes: :skull:

**Comment by Cameron653** [comment]
:+1:

**Comment by KasparoVy** [comment]
TOP KEK

**Comment by sasanek12** [comment]
:+1: :+1: :+1:

**Comment by fludd12** [comment]
This is completely insane, it would never get merged as is.

Everyone knows that cats are clearly the more played race. Runtime for Captain 2016.

**Comment by PJB3005** [comment]
Wow way to ruin the party fox.

**Comment by fludd12** [comment]
I told you it was the cats.

**Comment by pipextiny1** [comment]
nofun_robot

**Pull request closed without merging**
