### PR TITLE
More Lavaland fixes

### PR DESCRIPTION
**Pull request by Markolie**
**What does this PR do:**
See the changelog.

Fixes https://github.com/ParadiseSS13/Paradise/issues/11632.
Fixes https://github.com/ParadiseSS13/Paradise/issues/11624.

A big thank you to Ionward for providing species specific explorer sprites!

**Changelog:**
:cl: Markolie and Ionward
add: Added Tajaran, Vulpkanin, Unathi and Vox sprites for the explorer gas mask (thanks to Ionward!)
add: Added custom species sprites for the explorer suits and hoods (thanks to Ionward!)
add: Added missing surgical tools and a pet vendor to the animal hospital.
add: Added a custom cigarette vendor to the beach biodome ruin.
add: Added an autolathe and RPD to the Lavaland Syndicate base. Also added a custom cigarette vendor and made the vendors not charge money.
add: Added tiny fans to the mining base and labor camp exist.
add: A separate jobban for ghost roles has been added.
fix: The alternative sink now has directional sprites. This resolves an issue with shelters having sinks facing the wrong way.
fix: Fixed the Syndicate sleepers on the Lavaland Syndicate base pointing the wrong way when a ghost role spawns in.
fix: Fixed Lava being removed by the staff of lava not working. Also added a missing warning effect when the staff is turning regular turf into lava.
fix: Fixed random bookcases not spawning books (hopefully).
fix: Fixed surgical drapes not having a sprite.
fix: Fixed being unable to modify the GPS tag of shelters.
fix: Fixed the Lavaland swarmers not eating anything.
fix: The ash drake swoop attack is no longer incredibly loud.
tweak: The Syndicate base self-destruct is now much more powerful and capable of destroying the entire base.
tweak: The flavor text of Ash Walkers and Syndicate operatives now clarifies what they can('t) do.
tweak: Ash walkers can no longer use machinery.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Is the ability of lavaland mobs to smack you from an extra tile away an intended part of their behaviour? Just curious

**Comment by Markolie** [comment]
That's not intentional no, but probably an issue with the underlying mob code.

**Comment by AffectedArc07** [comment]
Reason for appveyor failing is because were out of artefact storage
```
Uploading artifacts...
Maximum allowed artifact storage size of 50000 Mb will be exceeded.
```

Ask a maintainer to clear the appveyor artefact cache to stop it from failing. Really it should still pass if it cant upload but oh well

*This is not an automated message*

**Comment by SteelSlayer** [comment]
'Added an autolathe and RPD to the Lavaland Syndicate base.'
Oh yes, I like very much :ok_hand:

**Comment by Crazylemon64** [comment]
There's no button for simply clearing the artifact cache, as far as I can see - I'd have to delete each of the ~500 builds manually
Why are we using appveyor if we're not using the artifacts, anyways?

**Comment by KasparoVy** [comment]
Maybe cron job to clear oldies

**Pull request merged**
