### PR TITLE
Allow for the construction of wheel chairs

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) You can now build wheelchairs with fifteen metal sheets. Fixes https://github.com/ParadiseSS13/Paradise/issues/1897.
2) Fixes https://github.com/ParadiseSS13/Paradise/issues/1904.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
can science get rocket powered wheelchairs as an R&D researchable

**Comment by Markolie** [comment]
We need that.

**Comment by dagilbert** [comment]
Yay! Wheelchairs! Now people with no legs can play!

**Comment by Earthdivine** [comment]
>Yay! Wheelchairs! Now people with no legs can play!

You already could start with them, you just couldn't replace them

**Comment by Fox-McCloud** [comment]
Prolly for the best.

:+1:

**Pull request merged**
