### PR TITLE
Fixes Judge armor for Grey by adding sprites

### LINKED ISSUE #21735: Judge armor is invisible on greys
**Issue Description**:

Judge armor on greys doesnt have a sprite so shows as invisible.

**What did you expect to happen**: 

DRIP

**What happened instead**:

SAD

**Why is this bad/What are the consequences**:

I AM NOT THE LAW

**Steps to reproduce the problem**:

1. Equip judge armor as grey

**When did the problem start happening**:

Presumably since it was added

### PR DESCRIPTION
**Pull request by SynthTwo**
## What Does This PR Do
Fixes #21735

## Why It's Good For The Game
Now Greys can be the LAW. A species not being able to see an item they can wear is no bueno. 

## Images of changes
image-1

## Testing
Loaded a grey in game, loaded the item. Badda boom, bada bing, it works. 

## Changelog
:cl: ATP-Engineer
fix: adds sprites for the grey variant of judge armor
/:cl:

### CODE REVIEW

**Review by Contrabang — CHANGES_REQUESTED** [review]
image
These sprites go WAY off the grey's body, and are even clipped by the helmet a little (which is mostly the helmet's fault).
For comparison, heres how they look with normal sec armor, no overhang.
image
Heres what they look like if they use the human-body armor sprites, it should preferably look more like this imo, with just the arm-holes fixed.
image

**Comment by SynthTwo** [comment]
> image These sprites go WAY off the grey's body, and are even clipped by the helmet a little (which is mostly the helmet's fault). For comparison, heres how they look with normal sec armor, no overhang. image Heres what they look like if they use the human-body armor sprites, it should preferably look more like this imo, with just the arm-holes fixed. image

Got it boss, will change it.

**Comment by SynthTwo** [comment]
Changed it now, gave it reduction surgery 🫡

**Review by Henri215 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]
Awaiting sprite team approval

**Pull request merged**
