### PR TITLE
Encourages crew to foster highly dangerous biothreats

### PR DESCRIPTION
**Pull request by Crazylemon64**
Also refactors space vines slightly to allow admins to delete spacevine events cleanly without blowing up half the station, if one of them mutates to "explosive"

:cl:Crazylemon
rscadd: Kudzu vines now can yield materials if carefully tended to
/:cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Should add a proper xenomorph containment chamber to xenobiology.
The ones on TG have injectors, wall igniters and forcefields to contain them much more securely.

**Comment by Crazylemon64** [comment]
This has nothing to do with xenomorphs.

**Comment by KingPhilipIII** [comment]
I was focused on the 'dangerous biothreats'.

I understand it was unrelated to xenomorphs.

**Comment by taukausanake** [comment]
So how does one obtain a space vine sample and start breeding it? I haven't seen them in total action yet and wonder if this is even worth the trouble

**Comment by Crazylemon64** [comment]
You get them by attack-selfing a kudzu fruit - preferably in an area you can control safely. Faster production time and potency increase spread rate and mutation rate respectively.

**Pull request merged**
