### PR TITLE
NanoUI Bodyscanner

### PR DESCRIPTION
**Pull request by tigercat2000**
Adds NanoUI to the bodyscanner (god help me)

Also:
 - Fixes misdetecting blindness as nearsightedness; one is an sdisibilities flag, one is a disibilities flag, it was checking both as sdisiibilities
 - Cleans up (some) of the code
  - Mostly got rid of colon abuse and cleaned up the normal UI code
    - Yes, I did have to keep the normal UI code, for printing paper
 
lotsapicks
lotsapicks
lotsapicks
lotsapicks
lotsapicks

### CODE REVIEW

**Comment by tigercat2000** [comment]
Sidenote, yes, I noticed the screenshots have the blindness and nearsighted on the same line, already fixed, can't be bothered to make a new screenshot.

**Comment by FalseIncarnate** [comment]
I see you kept the ability to print after all, assuming that is identical to current print-outs?

:+1:

**Comment by tigercat2000** [comment]
@FalseIncarnate more or less, I tried my best to clean it up

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Finalsong** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Body temperature should not be in Kelvin.

It should be in Fahrenheit with Celsius in parenthesis, or something like that.

**Comment by tigercat2000** [comment]
oh right

**Comment by tigercat2000** [comment]
Um, also, am I the only one... or does body temperature drop while people are inside of things?

**Comment by tigercat2000** [comment]
oh right screenshot
SKREEEEEEEEEEEEEEEEEEEEE

**Comment by Crazylemon64** [comment]
Maybe this might be more of a feature request, but could you make it so organs that are bruised, broken, and ruined have different text colors of damage?

**Comment by tigercat2000** [comment]
@Crazylemon64 Well, it's... certainly possible, but I would rather not play with this any more, it's messy enough as is, really.

**Comment by Crazylemon64** [comment]
Fair enough. Might take a peek at this myself after I finish doing something similar to sleepers, as sleepers the way they are now are difficult to use for the chemicals further down the list, given that it refreshes and snaps to the top whenever a chemical update happens.

**Comment by Plotron** [comment]
I am skeptical. Is it as intuitive or easy to read as the old UI? There's a lot of wasted space.

**Comment by Markolie** [comment]
Please do not use Fahrenheit. Stick with Celsius alone. Nothing in SS13 should use the terrible backward Fahrenheit system (and currently nothing does, so yay!)

**Comment by tigercat2000** [comment]
@Markolie That's not true, sleepers and current body scanners show Fahrenheit next to Celsius for body temperature. Not to mention that PURE MURICAN means I would rather remove Celsius from the readout.

**Comment by tigercat2000** [comment]
@Plotron It is a lot of wasted space, that's true... however, I would say it is definitely easier to read, given that current bodyscanners just throw all statuses together;
 `Head | bleeding:fractured:infection:loyaltyimplantunknownobjectdetected:`

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Health analyzers, too.

**Comment by TheDZD** [comment]
:us:
Definitely necessary to keep Fahrenheit.

**Pull request merged**
