### PR TITLE
Delta sec remap 2

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR is a remap of delta sec to include a way for auto-released prisoners to leave without warden involvement.
By consequence, other parts of sec have been shuffled.

Edit 2022/05/31:
Maints added to connect cargo, disposals, sec, and that bit north of vault.
Magi bedroom deleted.
Evidence delivery disposals from processing to evidence room. For the lazy as hell sec officers, or escaped processing prisoners who feel lucky.
Solitary and execution swapped to make solitary more secure and let maints hobos watch executions

## Why It's Good For The Game
Prisoners being able to just leave when their timer expires is very useful, and cuts down on frustration.
This PR doesn't really increase the difficulty of breaking into sec either, just moves some doors around. You are never more than 2 doors away from any part of the brig.

Edit 2022/05/31:
Maints added to give antags more chances to move around delta, connection to sec to weaken the brig as currently, it is very fortified.
Magistrate did not need a bedroom.

## Images of changes (updated 2022/06/12)
image

## Changelog
:cl:
tweak: Tweaked delta security to allow prisoners to leave
tweak: Added new fore-starboard maints to delta that connect cargo, disposals, security, and that bit north of the vault.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
This is my singular complaint with Delta nearly every shift as Sec. God bless.

**Comment by LightFire53** [comment]
image

Stray power cable, and unpowered windows by the equipment room

image

Head of Security office has a power cable running down into nothing from underneath the tables. No intercomm on the walls.

image

HoS Quarter's are also missing an air alarm, as well as a firelock under the airlock

image

I also think we typically try to avoid double walling like this?

image

Interrogation is missing a light switch, as well as firelocks

image

Not you on this one, but since we are already talking firelocks, we are missing one on the connection to the suits

image

image

This room share the same area as the majority of the brig, which feels a bit off since it is noticeably detached. Pre-existing, but maybe it could be adjusted? No worries if not.

Some weird area-ing, plus this room lacks the basics of area requirements: light switch, air alarm, fire alarm, intercomm 

image

A single jelly donut will not sustain this security force

There is no light switch for the `brig` area, as well as no intercomms it appears.

I was going to load up the map on a local server and check lighting, but I appear to be having issues with that for the moment.

**Comment by Bm0n** [comment]
These walls should probably be rwalled since they connect to the inner brig else it is 2 normal walls or 1 normal wall and 1 unpowered rwindow to get inside.
image
The only other gripe I have is that the sec equipment room is a little big and open and that the whole brig seems a little over-reliant on dark tiles but besides that, this layout is vastly superior to the current delta brig.

**Comment by LightFire53** [comment]
image

image

These areas seem really dark in night shift lighting compared to this which was also in night shift lighting

image

image

Batman hides in this corner, it's so dark.

**Comment by LightFire53** [comment]
Few more:

image

Top cell window isn't shocked

image

Cell 3 has a spare power cable going towards a wall in the entry way

image

This wall is in space

image

Missing firelock on the airlock to the firing range

image

Should probably shift this over a tile to run under the window

image

This airlock doesn't have a security blast door

image

Double security blast door on the lower airlock

image

Another missing under the window in between the two airlocks on the right

image

Blast doors on the cell timers on these two cells, but not the others

image

And then on the middle windows here, but not in the other set

The HoS office also completely lacks the security blast doors on the outer windows.

**Comment by S34NW** [comment]
Thanks, I've addressed these.

However, 

> Missing firelock on the airlock to the firing range

This is on purpose, we do not add firelocks to maintenance access doors (of which this sorta is in my mind)

> This airlock doesn't have a security blast door

The others being blast doored on this checkpoint was a mistake. I've now removed all blast doors on the checkpoint.


I've also only put blast doors in a perimeter on the brig, similar to the electrified windows.

**Comment by S34NW** [comment]
## Blast Doors:
blast_doors

## Firelocks:
firelocks

## Wires:
wires

**Comment by Christasmurf** [comment]
Magistrate and HoS windows should be electrochromic if they aren't, rather than shutters, and the doors non-glass variants to keep them in line with other command offices, as I think we've got electrochromic on all head offices now (at least on boxstation), same with the detective's office and processing if these aren't already like that. Blast doors on one of the magistrate's windows, probably the inner one to allow them to still leave their office to the rest of the station in the event of a lockdown in brig.

Other than that, looks good!

**Comment by S34NW** [comment]
> 



> Magistrate and HoS windows should be electrochromic if they aren't, rather than shutters, and the doors non-glass variants to keep them in line with other command offices, as I think we've got electrochromic on all head offices now (at least on boxstation), same with the detective's office and processing if these aren't already like that. Blast doors on one of the magistrate's windows, probably the inner one to allow them to still leave their office to the rest of the station in the event of a lockdown in brig.

HoS already had electrochromic, but I swapped the Magi's shutters out for them and added it to det office and processing.
Doors are mostly fine bar det's office so that was swapped to non-glass.
Blast doors were added to magi's interior access.

**Comment by LightFire53** [comment]
The final review:

Prisoner Processing has glass airlocks with it's electrochromatic windows, not sure if they were intended to be or if they should be moved to solid airlocks.

Also Cell 5's TV is set to +31 for Pix Y, instead of +32 (and -32) for the other ones.

Other than that, LGTM 👍🏻

**Comment by S34NW** [comment]
> Cell 5's TV is set to +31 for Pix Y, instead of +32

image

**Comment by LightFire53** [comment]
image

May want to add some vents and scrubbers for this section, considering the amount of glass involved here. Also a firelock under the airlock.

image

Need a firelock here

image

Not sure what the vibe of this room is supposed to give: Is it a break/resting area, or is it their main office/briefing room? If it's a briefing room, may want to give it a big conference table like Meta has to fill some space.

image

Still think this doesn't need to run under a window, tbh.

But otherwise, seems to be in the same shape I last reviewed.

**Comment by Komrad822** [comment]
image

The hos office should be like this, otherwise the donut case blocks the hardsuit storage.

**Comment by S34NW** [comment]
> image
> 
> The hos office should be like this, otherwise the donut case blocks the hardsuit storage.

good point, thank you

**Comment by Hostail** [comment]
Those airlocks near perma, does security have access to them? Cause I remember in the past they didn't have access and I always found it weird that theres this useless airlock inside security that they can't use. Just wondering if thats gonna continue being the case or if that was a mistake from the beginning.

**Comment by S34NW** [comment]
> Yet another review

Issues addressed, as for the shuttles starting off-station. That's how it's always been :)

**Review by Bm0n — COMMENTED** [review]
I have arrived to review your map

<details><summary>Review</summary>

A layout like this is best to keep stuff off windows. Just follow the arrows... plus intercoms on windows just look funky. Also, I have no idea why cells have firelocks, I know Box does this, but it's genuinely pointless when the cells are made out of glass walls.

review

Can I convince you to remove the one stool marked in red? It'll overall improve the roundedness of the room

review2

Invert the stacking of the weapons here else you'll end up with this mess in game

image

image


This area here should be security office, not security equipment storage. Security equipment is only for the room with the lockers.

image

The L3 and L4 lockers in the firing range is kind of weird to me. Try putting them outside the armoury where the security office should be

image

A public-facing gulag shuttle isn't necessary for Paradise, we don't temp gulag. Also, if the gulag shuttle is left at the outpost by accident or a prisoner in the gulag is fast enough to trick secoff coming down to the outpost they can get on the shuttle, use the points claimer console to move the shuttle and then escape because you put a one-way helper on the prisoner side of things that leads right to the public hallway.

image

This area is F-S maints when it should be space

image

This door has no access points, it should have maintenance access

image

To me personally, this theme makes no sense. A jungle in a dark maintenance tunnel on a space station next to the brig of all place?

image

Try not to block off maints with grille spawners. It was one of the things that made old Meta so trash. Just leave at least a 1x1 always clear passage

image

This cobweb here looks like it floating when the door is opened. Try only to place cobwebs on wall angles

image

I cannot tell you how much this triggers my ocd. I would move the south wall up by one and make it flush with the shuttle.

image

I am sorry to complain about the theming again but all of this just makes no sense. You've got church pews, some sort of beach sand area and glass floors. I suggest taking a look at the rest of Delta maints, it tends to have a lot of floor tiles and is usually broken up by girders for cover

image

Catwalks are usually connected with each other and lead somewhere. I would use lattice here instead and only keep the catwalks around the mass driver.

image


</details>

I'll take another look at this later. Good luck with your PR!

**Review by AffectedArc07 — APPROVED** [review]
Seems much better in practice

**Pull request merged**
