### PR TITLE
Nukes karma

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Completely removes karma, makes all species unlocks defaults. The system was added during a different era of SS13, and especially a different era of para, when decisions were made by 1 man who (in his own words) was stoned 99% of the time. 

Lemme give you some stats. In the past 30 days, 372 round have been played. 2909 karma has been awarded, by 591 unique people. For context, 3381 unique people have played in the past 30 days. Only 17% of people use this system, and of that 17%, most of it is awarded to excessive antag or powergaming plays, with both metrics and anecdotes to back this up. To quote, "my successful hijack got me 20 karma"

The system has outstayed its welcome, serves no real benefit other than exclusivity cliques and copious amounts of metafriends, and is generally just the epitome of "ok this is good in theory but awful in execution"

---

Oh and to the people who cry "Improve dont remove!", this system has existed since Paradise's inception in 2013.
image

We have had almost a full **decade** to improve it. Its not getting improved. It needs to go. Theres a reason that Nians werent made a karma species. 

## Why It's Good For The Game
See above ramble.

## Images of changes
Top right
image

## Testing
- Started the server
- Checked the species menu as a non admin - All species except armalis and nucleation
- Checked the species menu as an admin - All species including armalis and nucleation

## Changelog
:cl: AffectedArc07
del: Removed the karma system
tweak: All karma species are free now
/:cl:

### CODE REVIEW

**Comment by ppi13** [comment]
Karma species leaving, is a good change, since one of the common cries regarding any species changes is "but muh karma cost".
So seeing that leave is just a good change.
Karma could have staid as either a goodboy points system, or even loadout unlocks, but again, few uses it, since there is no real reason to, you do not get notified of getting karma, so you need to check, so even as a goodboy point system, its pointless.
Sad to see it leave, its been here since the start, but jobs unlocks are gone, species unlock going is just the next logical step.

Good change, but bittersweet.

**Comment by hal9000PR** [comment]
> Karma could have staid as either a goodboy points system,

We dont need ss13 reddit karma

**Comment by Miraviel** [comment]
This will also need the removal of Rule 9 (karma trading) and its relevant section in the Advanced Rules (just so we don't forget it)

**Comment by Rurik123** [comment]
I've been told the main reason species karma exists is to enforce species rarity, so there aren't 15 plasmamen running around in one shift.

Is this no longer a desired goal, or is it that having this karma system isn't worth what it achieves?

**Comment by AffectedArc07** [comment]
> I've been told the main reason species karma exists is to enforce species rarity, so there aren't 15 plasmamen running around in one shift.
> 
> Is this no longer a desired goal, or is it that having this karma system isn't worth what it achieves?

I have never heard this

**Comment by Accinator50** [comment]
I agree with the points made.

However, I personally also thought that karma was used to make certain species rarer, so that, for example, there are not 20 vox running around during a round. 

Likewise, the karma system had a bit of a function of making it possible to work towards something that persists across rounds (rather than just having small personal goals within the round, such as building a Tesla).

Nevertheless, the karma system creates more problems than it "solves". 

Would it be desirable/possible to turn the karma system into a game hour system instead, similar to the karma jobs, so that for a species that previously cost 30 karma you now have to "pay" with 50 game hours (the game hours are just an example for now). 

This would leave the species a bit more unique and give you a multi-round goal, while eliminating the problem of the karma system (namely the problem of meta-cliques or gamers having an advantage and also the problem that there's always luck involved in getting karma).

**Comment by Screampuff** [comment]
I don't think unlocking tons of races to the general public will increase races Vox dramatically when they have so many downsides to playing them.  If anything, it'll cause a flood of new IPC players and that's about it.  Opening up tons of more races to play should increase variety tenfold instead of seeing 90% of the population being vulp (myself included)

**Comment by Christasmurf** [comment]
> Karma could have staid as either a goodboy points system, or even loadout unlocks,
I love how since jobs got removed from karma system everyone has been saying "we can add cosmetics to karma!" and nobody has even THOUGHT of a new outfit that could be karma purchase

Good riddance, goodbye karma

**Comment by jabrongo** [comment]
> hello comment section readers, I am here to SHAMELESSLY encourage you to create a grey, kidan or drask character as they are the LEAST played species on the server and they have really cool mechanics that you can check out below here https://paradisestation.org/wiki/index.php?title=Kidan https://paradisestation.org/wiki/index.php?title=Grey https://paradisestation.org/wiki/index.php?title=Drask
> 
> bless this PR, I hope to see more variety should this be merged (fingers crossed).

ironic because i consider those three races to be the coolest LOL

**Comment by OctusGit** [comment]
The death of karma, finnaly.
The new era of Paradise begins...

**Comment by Retrograde115** [comment]
Can I get some financial reimbursement for the 48 karma I've painstakingly acquired over 600 hours of playtime?

For real though, I support this 1000%

**Comment by AffectedArc07** [comment]
> Can I get some financial reimbursement for the 48 karma I've painstakingly acquired over 600 hours of playtime?
> 
> For real though, I support this 1000%

I was getting ready to lynch you when I saw this in my outlook
image

**Comment by SynthTwo** [comment]
very based PR

**Comment by GDNgit** [comment]
Very based pr, and to those who say "Well we shouldn't have a bunch of [X] species on the station"
I ask you, why? ~If it's vox that's just more KFV anyways~
Very happy to say this will release hal of this vox ban, and will therefore be forced to play vox by meow

**Comment by procdrone** [comment]
AA just needs to convert current karma to antag tokens, it will be fine, trust me bro

**Comment by ppi13** [comment]
I would actually like to see the list of who memes the hardest and earned the most karma by the time this gets merged.
And while the antag token is just a quip, i know there are people who could play antag, 8 hour a day for a year straight, and still not run out.

**Comment by Regen1** [comment]
Goodbye karma, you were a good addition when we made you back in 2013, but you did not stand the test of time

**Comment by Denthamos** [comment]
I can agree with this.  It is not a system that works well anymore in this day and age of paradise.

What I _will_ say though is that in the future I would personally love to see a system not unlike goons spacebux store.  A karma style currency system that allows players to purchase for the round only, specific fluff, flavor, and clothing items that are not obtainable otherwise.  With such maybe even remove the roundstart loadout options in favor for such a thing?  Stuff for the future.

**Comment by Komrad822** [comment]
YES.

Let there be suffocated voxes, burning plasmamen, and frozen slimes EVERYWHERE!

**Comment by matttheficus** [comment]
I can kill more Vox.

This is an unfathomably based PR.

**Review by Fox-McCloud — APPROVED** [review]

**Comment by gamingvirtue** [comment]
> I can agree with this. It is not a system that works well anymore in this day and age of paradise.
> 
> What I _will_ say though is that in the future I would personally love to see a system not unlike goons spacebux store. A karma style currency system that allows players to purchase for the round only, specific fluff, flavor, and clothing items that are not obtainable otherwise. With such maybe even remove the roundstart loadout options in favor for such a thing? Stuff for the future.

Eh, I like this idea, but preferably not at the expense of the loadout as-is. It provides a nice bit of consistent personal flavour right now to each character that would be lost with its removal.

Otherwise-unobtainable extras on top of that, though? Absolutely.

**Comment by Accinator50** [comment]
>  and to those who say "Well we shouldn't have a bunch of [X] species on the station" I ask you, why?

It's just my head lore that humans are the dominant species and that species like Plasmamen or Vox rarely work for NT because of their culture. But I don't want to divert the conversation because I am also in favour of abolishing karma. This point can be discussed when karma is gone and it is apparent how the number of species has changed.

**Comment by Samman166** [comment]
The only downside to this PR is that I will never be able to get 420 karma

**Comment by ReedOni** [comment]
More Vox means more chances of departed soul voxes which means more KFV, which is good for corporate interest.

**Review by hal9000PR — APPROVED** [review]

**Comment by hal9000PR** [comment]
fuck it ship it

**Comment by Screampuff** [comment]
SEND IT

**Comment by Contrabang** [comment]
SHIPPPPED!!!

**Comment by GDNgit** [comment]
https://discord.com/channels/145533722026967040/145700319819464704/1085280414568038522

**Comment by Probablyjay19** [comment]
> hello comment section readers, I am here to SHAMELESSLY encourage you to create a grey, kidan or drask character as they are the LEAST played species on the server and they have really cool mechanics that you can check out below here
> 
> https://paradisestation.org/wiki/index.php?title=Kidan
> 
> https://paradisestation.org/wiki/index.php?title=Grey
> 
> https://paradisestation.org/wiki/index.php?title=Drask
> 
> 
> 
> bless this PR, I hope to see more variety should this be merged (fingers crossed).

Oh the misery 
image

**Pull request merged**
