### PR TITLE
Allows for some hard suits to carry suit storage jet packs.

### PR DESCRIPTION
**Pull request by sdtwbaj**
Yeah that.

I've never modified SS13 code and have no idea if that would work, lets hope, right?

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:-1: 

No. If you're going to use a jetkpack, you should have to sacrifice for it.

**Comment by Tastyfish** [comment]
```
code/modules/clothing/spacesuits/rig/suits/station.dm:62:error: obj/item/weapon/tank/jetpack: undefined var

code/modules/clothing/spacesuits/rig/suits/station.dm:90:error: obj/item/weapon/tank/jetpack: undefined var

code/modules/clothing/spacesuits/rig/suits/station.dm:117:error: obj/item/weapon/tank/jetpack: undefined var

paradise.mdme.dmb - 3 errors, 0 warnings (3/4/16 4:55 am)
```

**Comment by sdtwbaj** [comment]
I mean, the fact that it can hamper space exploration sometimes because of that fact that jet packs only fit on the backpack slot throws it off. In a recent suggestion, it seemed like people were supporting this sort of thing. It's something people would like to see.

**Comment by tigercat2000** [comment]
Two things:
 - Paths are incorrect, which is making travis fail
 - These are the files for the newrig admin-only suits. It won't affect the obtainable suits. You are looking for https://github.com/sdtwbaj/Paradise/blob/patch-1/code/modules/clothing/spacesuits/rig.dm

**Comment by sdtwbaj** [comment]
Ah, okay. Modifying.

**Comment by DaveTheHeadcrab** [comment]
Jetpacks can already be placed in those slots, what you're doing will not have the intended effect (Or any effect at all, actually)

Also even if this did work I would disagree with it.

**Comment by sdtwbaj** [comment]
Le sigh. More on the topic of the code, where would I need to modify to have the desired effect?

**Comment by Fox-McCloud** [comment]
well, you'd have to check for the slot directly--thing is, though, jetpacks are child of tanks, so everyone would get this benefit--likewise, there's no feature in place to prevent a subtype from being equipped to a particualr slot (with regards to suit storage) as far as I know.

This means you'd have to ultimately refactor and re-path jetpacks or implement some feature to block certain things from being in that slot---AND code in the functionality for jetpacks functioning in that slot.


Frankly, it'd be better to just implement TG's hardsuit system, as that resolves a number of problems and has support for built-in jetpacks for a number of hardsuits.

**Comment by VampyrBytes** [comment]
From a code point of view
The reason it's failing is you've missed the / off the start of the jetpack paths.
However, assuming Fox is right about there being no feature to prevent a subtype, what you're doing has no effect whatsoever... because jetpacks are a subtype of tank which is already in those allowed lists. So technically there's nothing to stop you putting a jetpack into a rig at the moment. So why can't you use one when it's there? Because neither the rig nor the jetpack know to use the jetpack  when it's there. That's what you would need to address.

From the fact that you say it's your first venture into the code, and the fact that you didn't try compiling and testing this before submitting, I would strongly suggest you start smaller... rather than starting with features, start with bugfixes. Bugfixes involve a lot of reading of code, which will help you learn how things work and where things happen, and usually only small changes to the code. It will also get you into the habit of compiling and testing everything, as you'll have to to be sure what you've done fixes the bug (and doesn't break anything else in the process)

**Comment by Fox-McCloud** [comment]
Going to go ahead and close this for the above reasons.

**Pull request closed without merging**
