### PR TITLE
Hardsuit Jetpack Upgrade[WIP]

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
Adds a new item into the game, the embedded jetpack upgrade for hardsuits. Ported from TG

**Changelog:**
:cl:
add: hardsuit jetpack upgrade
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
If we're going to do this, we should definitely can being able to use a jetpack in your suit storage slot.

**Comment by BakKeener** [comment]
Aren't we already able to use a jetpack from the suit storage slot? If not then I must of missed a very recent change then because I was able to use a jetpack from it last week.

**Comment by Fox-McCloud** [comment]
"can" as in get rid of. Axe. Remove. Decimate. Eviscerate. REMOVE FROM THIS MORTAL PLANE.

**Comment by Couls** [comment]
Fox wanted this one too THE MADMAN

**Pull request closed without merging**
