### PR TITLE
New tribal craft items(pickaxe and scythe)

### PR DESCRIPTION
**Pull request by botka4aet**
## What Does This PR Do
Bone pickaxe and scythe. Icons from ElGood.

## Why It's Good For The Game
New tribal items

## Images of changes
image

## Changelog
:cl:
add: Added a craftable bone pickaxe and scythe.
imageadd: Added new sprites for the bone pickaxe and scythe.
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
Very cool idea, good for the ash walkers!

Not sure that the bone pick axe should be better at mining than the standard metal one though...

**Comment by S34NW** [comment]
> 
> 
> Very cool idea, good for the ash walkers!
> 
> Not sure that the bone pick axe should be better at mining than the standard metal one though...

Bone items _do_ currently outclass their metal ones in-game. For example, the bone spear does more damage and can be thrown against megafauna, unlike the regular spear.

**Review by SabreML — COMMENTED** [review]
Great idea for a first PR. The more thematic tribal items that Ash Walkers have access to the better IMO.
Just a couple of nitpicks and styling things:
<hr>

You'll want to put some more detail into the changelog in the PR's description, since that's the part that actually shows up ingame.
For example, this changelog from #16603:
> 🆑
add: Added a closet in the Cerebron Custodial closet
tweak: Moved things around in the room to make up for the addition of the closet
del: Removed extra docking port for the whiteship
fix: Fixed access for the engineering lobby door and the maintenance airlock to allow the mechanic in
/🆑

Gets shown as this on the ingame changelog:
image
<hr>

Something like this would work for the changelog here:
> 🆑
add: Added a craftable bone pickaxe and scythe.
imageadd: Added new sprites for the bone pickaxe and scythe.
/🆑

**Comment by Spacemanspark** [comment]
>Bone items do currently outclass their metal ones in-game. For example, the bone spear does more damage and can be thrown against megafauna, unlike the regular spear.

I'd imagine the bones of the megafauna would be more powerful than the flimsy piece from a glass shard attached to a metal stick :p

**Comment by botka4aet** [comment]
> You'll want to put some more detail into the changelog in the PR's description, since that's the part that actually shows up ingame.

Thx for guide

**Comment by PacifistDalek** [comment]
> > Very cool idea, good for the ash walkers!
> > Not sure that the bone pick axe should be better at mining than the standard metal one though...
> 
> Bone items _do_ currently outclass their metal ones in-game. For example, the bone spear does more damage and can be thrown against megafauna, unlike the regular spear.

Huh, I had no idea!

**Comment by variableundefined** [comment]
Please make more informative PR title about what you are doing with bone items

**Comment by Denthamos** [comment]
Holding off on approval of this PR until the title is properly informative on what it is doing for sanity purposes.

**Comment by botka4aet** [comment]
Changed title.

**Review by variableundefined — CHANGES_REQUESTED** [review]
PR will be good to go when styling issues pointed out by Sabre is fixed.

**Comment by botka4aet** [comment]
Fixed reviewed issues

**Review by SabreML — APPROVED** [review]

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
