### PR TITLE
Updates stamps and adds contract sprites.

### PR DESCRIPTION
**Pull request by Quantum-M**
**What does this PR do:**
Updates the stamp sprites, along with adding sprites for the employment contract and infernal contracts.

**Images of sprite/map changes (IF APPLICABLE):**
image

image
Employment contract to the left, infernal contract to the right.

**Changelog:**

:cl: Quantum-M
tweak: Changes the stamp sprites.
imageadd: Add new sprites for the infernal and employment contracts.
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
Please... PLEASE...
Warden stamp...

**Comment by Quantum-M** [comment]
Maybe in another PR, @Spartan6

**Comment by granodd** [comment]
Does this finally mean that we can make the QM's stamp not the same color as the DENIED stamp?

**Comment by Quantum-M** [comment]
@granodd , QM stamp is Brown and, I believe it's the bottom left one in the image above.

**Comment by Fox-McCloud** [comment]
a before and after would be preferable.

**Comment by Quantum-M** [comment]
@Fox-McCloud 
When you say flat, do you mean the contracts, the stamps, or both?

I disagree on the fire being a nice touch, as it looks a bit crappy, with just a fire coming from a bottom of a plain paper sprite, and when one pictures some contract from a demon/devil, one usually thinks of some sort of sinister looking scroll or similar.

TGs: 
infernal_contract

Current one:
infernal_contract2

**Comment by Fox-McCloud** [comment]
The Stamps.

The contract sprites are ok, though I still contend the infernal one should be on fire.

**Comment by variableundefined** [comment]
Any updates on the stamps and contract sprites?

**Comment by Quantum-M** [comment]
Sorry for the lack of response, @variableundefined , updated the handle(?) part of the stamps, meaning that it's slightly darker now: 
image

**Pull request merged**
