### PR TITLE
Yeah. No. This is going away now.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Merge ASAP.

### CODE REVIEW

**Comment by Fishocalypse** [comment]
You're fucking with a beast you PROBABLY can't handle, goofball.

**Comment by tigercat2000** [comment]
Removing Ponies's Ponies is asking for the same fate as Uc_guy.

**Comment by Iamgoofball** [comment]
i survived chemistry
this can't be that bad, right?

**Comment by Spacemanspark** [comment]
This won't end well.

**Comment by Iamgoofball** [comment]
plus it uses relative pathing AAAAAAAAAAAAAAAAA

**Comment by tigercat2000** [comment]
#fixitdon'tdeleteit

**Comment by Iamgoofball** [comment]
#whywouldweeverkeepponyshitinthegame

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by Iamgoofball** [comment]
>travis doesn't compile

bah, travis is not needed, we only need pony removal

**Comment by tigercat2000** [comment]
This can only end extremely well I feel (and travis failed gg)

**Comment by Iamgoofball** [comment]
actually doing a git blame shows that Markolie was the guy who did it

huh

**Comment by tigercat2000** [comment]
markolie wasn't even around when these were made

**Comment by Iamgoofball** [comment]
huh

**Comment by Fox-McCloud** [comment]
There's other references to the ponies here---I think under the play as NPC thing.

**Comment by Spacemanspark** [comment]
...Please don't tell me those were actually selectable under that menu.

**Comment by tigercat2000** [comment]
oh
markolie cleaned out the WIP folder that's why, these used to be in there under ponies name

**Comment by tigercat2000** [comment]
@Spacemanspark of course they were, pretty much every simple_animal is selectable there

**Comment by Spacemanspark** [comment]
God dammit.

**Comment by CrAzYPiLoT-SS13** [comment]
If you wanted to do it, do it as it should be done. Remove all the references to them although i highly unsupport it. :-1:

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/blob/77534a6fa32a923e3d19e7b885f019ff20905892/code/modules/mob/transform_procs.dm#L424
https://github.com/ParadiseSS13/Paradise/blob/77534a6fa32a923e3d19e7b885f019ff20905892/code/modules/mob/transform_procs.dm#L455
https://github.com/ParadiseSS13/Paradise/blob/10ee512d222f3003518e8a6a4fed64662b737223/code/game/objects/items/flag.dm#L96

**Comment by FreeStylaLT** [comment]
:-1: I really don't see the point in removing this when it has no impact on anything, it'd be like removing the gyrojet pistol or the desert eagle - neither of those have any real impact on the game whatsoever and are admin-only, just like the ponies, neither are they broken like the SM, so why remove it?

**Comment by MactoPerFuror** [comment]
This is admin behind the scenes flavor. I have used it for things as punishments to adminbus events. Both of which have been greeted to much enjoyment from the community. There is always just one person who goes "ew gross, ponies!" and I feel that this is filled with that same vibe. Removing something that many enjoy just because a few think that. This for me, is my favorite tool as an admin. The crabs hardly have the same effect as a pony. I am very against the idea of removing them since they feel like they are at this point a major core to the server.

**Comment by TheDZD** [comment]
DNM because it doesn't compile. Controversial because, well, see everything above.

**Comment by Iamgoofball** [comment]
>ponies are a major core to the server

sorry, what

**Comment by TheDZD** [comment]
I don't particularly care either way, but removing something just because you don't like it doesn't seem like a fair enough reason to do so. Although if you are going to remove something, remove references to it as well.

**Comment by MactoPerFuror** [comment]
Removing ponies is not unlike removing clowns. Some people straight up hate them. Removing them just removes an entire element and feel to the server.

**Comment by tigercat2000** [comment]
okay while I strongly disagree with removing these just because, @MactoPerFuror, i don't think it is entirely fair to call ponies the equivelent of clowns, clowns are part of the core server, ponies are a rarely-seen admin thing

**Comment by ZomgPonies** [comment]
- No description
- No reason given for the removal
- No discussion on the forums beforehand
- This is clearly some sort of bullshit metagrudging joke PR
- Stop fucking with our Github or you will be removed from it.

**Pull request closed without merging**
