### PR TITLE
Jaunt abilities are no longer blocked by blessed tiles

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
Jaunt abilities are no longer blocked by blessed tiles
Renames the bitflag to be more descriptive 
## Why It's Good For The Game
If this ever actually becomes practical in game we have a problem. Poor feedback combined with the fact this ganks wizard (who absolutely needs their exit options to work) makes this pretty silly. 
If you're wondering this didn't affect any of the other jaunt types, they overrode parent

## Testing
Rev'd all over the place and jaunted into blessed tiles

## Changelog
:cl:
tweak: Jaunt abilities are no longer blocked by blessed tiles. This affects wizards exclusively 
tweak: The Cult Wraith jaunt is still blocked by blessed tiles
/:cl:

### CODE REVIEW

**Comment by spacegeese** [comment]
what does blessing tiles do now then?

**Comment by GDNgit** [comment]
> what does blessing tiles do now then?

blocks the movement of revenants

**Comment by spacegeese** [comment]
> > what does blessing tiles do now then?
> 
> blocks the movement of revenants

i mean after this PR goes in

**Comment by GDNgit** [comment]
> > > what does blessing tiles do now then?
> > 
> > 
> > blocks the movement of revenants
> 
> i mean after this PR goes in

blocks the movement of revenants

**Comment by spacegeese** [comment]
> blocks the movement of revenants

oh, so what's a wraith? i have never heard of it

**Comment by GDNgit** [comment]
> > blocks the movement of revenants
> 
> oh, so what's a wraith? i have never heard of it

wraiths are one of the three cult construct monsters. they get jaunt, deal good damage, but have very low health

**Comment by spacegeese** [comment]
> wraiths are one of the three cult construct monsters. they get jaunt, deal good damage, but have very low health

that usage seems cool but i understand

**Review by DGamerL — APPROVED** [review]

**Comment by DGamerL** [comment]
> This pull request seems to be stale as there have been no changes in 14 days, please make changes within 7 days or the PR will be closed. If you believe this is a mistake, please inform a development team member on Discord.

It is not

**Review by Burzah — APPROVED** [review]

**Pull request merged**
