### PR TITLE
Increases gas toxicity across the board.

### PR DESCRIPTION
**Pull request by alex-gh**
**What does this PR do:**
While working on upping the oxygen damage to Vox I have discovered that toxic gases do a laughable amount of damage. For example you could stay in 25% plasma atmosphere indefinitely and survive by vomiting alone.

This PR increases the toxicity of the gases by a factor of 10.
It also ups the damage Vox take from oxygen, bringing the oxygen toxicity in line with the toxicity of plasma.

A vox will fall into hard crit in about 2 minutes and 20 seconds in the normal atmosphere.

**Changelog:**
:cl: uc_guy
balance: Toxic gases now do more damage.
balance: Vox take higher damage from oxygen.
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
Thank fuck.

**Comment by KasparoVy** [comment]
Thank you very very much.

**Comment by Ralta** [comment]
Finally. I don't play Vox as much as I used to, but they should really be taking far more damage for breathing oxygen than they are now; this'll be a good change for that.

As far as general toxicity, how quickly would you pass out from being exposed to, say, plasma with this change?

**Comment by alex-gh** [comment]
@Ralta Depends on plasma concentration but there is an upper damage cap of 10 damage/breath. For 20% plasma : same as Vox 2:20.

**Comment by Ralta** [comment]
Perfect,  thanks for the response @alex-gh - looking forward to this getting merged 😁

**Comment by Birdtalon** [comment]
Does nobody else think a factor of 10 is a bit crazy?

**Comment by alex-gh** [comment]
@Birdtalon Like I said, the current damage values are laughable.

Spin up a test server, open a canister of plasma on arrival shuttle, see for yourself.

**Comment by Birdtalon** [comment]
Yeah just chatted to Spartan on discord about it. Seems fine then from his description.

**Comment by KasparoVy** [comment]
Glorious

**Pull request merged**
