### PR TITLE
Makes all security newscasters bumped, centers newscasters, and converts several newcasters to the security version, adds several newscasters to box

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
Makes all security newscasters bumped and centered. It also adds several security newscasters to security and changes normal ones in brig/bridge to be security ones.

## Why It's Good For The Game
 Improperly bumped and uncentered newscasters look bad and there a lack of security newscasters specifically on the Cyberiad. So if you ever want to use the wanted feature, you never can properly find one. Several normal newscasters are missing on the cyberiad, particularly in medbay and research and to an extent engineering and cargo. More normal newcasters have been added so they can be used and are consistent with other stations. Also, more newscasters are good because they give you something to read if you are bored and waiting on something, especially in a workplace.

## Changelog
:cl:
add: Adds security newscasters to Warden's office, Detective's office, and Processing on all maps
add: Security newscasters now have a custom description
add: Newscasters are now inside the HOP line, for easy access to see what jobs are available
add: Readds a security newscaster to Box brig where the perma remap removed it
tweak: All newscasters in the brig/main command area are now security newscasters
tweak: Magistrates office now has a security newscaster, IAA have not been given one
tweak: Newscasters are now consistently centered
fix: Newscasters while alerting will only show the alert and not the default icon behind it
add: More newscasters have been added to several workplaces on all 3 stations.
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
The icon_state "newscaster_wanted" is not used anywhere besides the changes in this PR. Even checking for "_wanted" yields nothing else related to the newscaster icon state. I skimmed through "wanted" too but there was over 100 results, I didn't see anything there. Testing this on master does not yield the "newscaster_wanted" sprite at all. It may have been removed when newscasters were TGUI'd.

Testing on master, creating a wanted notice yields this. It never turns into the wanted icon
image

**Review by S34NW — CHANGES_REQUESTED** [review]
Your delta is not up to date, please re-apply delta changes over master

**Comment by Contrabang** [comment]
Delta and update_icon() updated

**Review by S34NW — CHANGES_REQUESTED** [review]
You revert a number of changes on delta still.

Please reapply your changes over the master file.

**Comment by Contrabang** [comment]
Aaaa I must have not saved it, I'll make the changes again

**Comment by Sirryan2002** [comment]
> The icon_state "newscaster_wanted" is not used anywhere besides the changes in this PR. Even checking for "_wanted" yields nothing else related to the newscaster icon state. I skimmed through "wanted" too but there was over 100 results, I didn't see anything there.
> 
> Testing on master, creating a wanted notice yields this. It never turns into the wanted icon image
```dm
/obj/machinery/newscaster/update_icon_state()
	if(inoperable())
		icon_state = "newscaster_off"
		return
	if(GLOB.news_network.wanted_issue)
		icon_state = "newscaster_wanted"
	else
		icon_state = "newscaster_normal"
```
it's used here, I wonder if it is just broken instead of unused?

**Comment by Contrabang** [comment]
> > The icon_state "newscaster_wanted" is not used anywhere besides the changes in this PR. Even checking for "_wanted" yields nothing else related to the newscaster icon state. I skimmed through "wanted" too but there was over 100 results, I didn't see anything there.
> > Testing on master, creating a wanted notice yields this. It never turns into the wanted icon image
> 
> ```dm
> /obj/machinery/newscaster/update_icon_state()
> 	if(inoperable())
> 		icon_state = "newscaster_off"
> 		return
> 	if(GLOB.news_network.wanted_issue)
> 		icon_state = "newscaster_wanted"
> 	else
> 		icon_state = "newscaster_normal"
> ```
> 
> it's used here, I wonder if it is just broken instead of unused?

This is normal on master now, it got merged with porting TG appearances, its no longer part of this PR

**Comment by LightFire53** [comment]
<details><summary>A review</summary>

### DeltaStation

image

Lots of newscasters in this area. The two in the private areas should stay, but could downsize on the other 3 in the library

image

Librarian is dual-wielding newscasters

image

Double caster in the conference room, and one is normal while the other is security.

image

Double caster in the cargo office

image

Sci-breakroom could use a newscaster (the pictured one is in Xenoslimeology)

image

Chapel Morgue has 2 casters in it as well

image

Robotics is also double castered

### BoxStation

Arrivals area and it's hallway is noticeably barren of casters.

I would add a caster to the medical hallway between Viro and Surgery

Mime and Clown Offices could use casters too

Atmospherics is also barren

image

Engineering has 2 security casters

### MetaStation

image

Medical (also including virology here, just not seen above) has a total of 2 newscasters

image

Library also suffers the "too many casters!" issue here. <strike>Not enough mana.</strike>

image

Cargo has 1 newscaster

The only newscasters in dorms exist in the mime and clown offices as well as the toilet.

Engineering only has 2 casters: 1 in the CE office and 1 in the main lobby.

Science breakroom could get a caster, same with the hallway between toxins and robotics. Speaking of toxins, it has 0 casters
</details>

**Comment by Bm0n** [comment]
despite the git bot removing the merge conflict tag you didn't deconflict this right, meta and box are still messed up.

also please please please don't spam newscasters all over the place. Newscasters are not fire alarms, they're meant to be rarer and strategically placed. There's nothing in our mapping guidelines that requires them to be in every room like you've done here. A few more are okay but some of these are just poorly placed on top of it-

like so, this is clipping with a light switch and is noticeable in-game

image

I am not going to go through and list them all but right now but I saw more.

also, why was the newscaster in Metas AI sat moved? The old layout gave the AI sat a more clean look towards the core. Just because it's not beside them doesn't mean the AI can't use it.

pr1

**Comment by LightFire53** [comment]
> also, why was the newscaster in Metas AI sat moved? The old layout gave the AI sat a more clean look towards the core. Just because it's not beside them doesn't mean the AI can't use it.
> 
> pr1

Delta did (does? I can't remember currently) have it in that spot, and box has something similar. I personally don't thik it retracts from cleanliness, to be frank.

**Comment by Contrabang** [comment]
> despite the git bot removing the merge conflict tag you didn't deconflict this right, meta and box are still messed up.

Resolved in latest commit, previous merge master was for fixing files from the Emissive PR.
> also please please please don't spam newscasters all over the place. Newscasters are not fire alarms, they're meant to be rarer and strategically placed. There's nothing in our mapping guidelines that requires them to be in every room like you've done here. A few more are okay but some of these are just poorly placed on top of it-

They are not in every room, medical was basically missing any newscasters on box, even if I did place a few too many, which I have scaled back in the latest commit. I added them particularly where people sit and do nothing in their workplaces, where reading the news could be a good way to pass the time (break rooms, hallways, etc.)
> 
> like so, this is clipping with a light switch and is noticeable in-game

Fixed with removal, They were not on the same side of the wall but could be seen through because of the window. There is literally no other place in that room that is not blocked by a windoor, window, other walling objects, or vending machine. This same kinda issue also happens at the chapel on box.

> I am not going to go through and list them all but right now but I saw more.

Listing them would be appreciated, I've gone through what I've added and removed any problematic ones.
> also, why was the newscaster in Metas AI sat moved? The old layout gave the AI sat a more clean look towards the core. Just because it's not beside them doesn't mean the AI can't use it.
> 
I disagree, placing it next to the AI like on the other stations makes it make more sense because consistency. Same thing with the AI request console on meta, but changing that would be scope creep.

**Review by Bm0n — CHANGES_REQUESTED** [review]
>Listing them would be appreciated, I've gone through what I've added and removed any problematic ones.

sure

delta:

Near the HoP line. Move this AI display to the tile adjacent and nudge the X by 32. The newscaster just below it should be on the wall and not nudged.
image

meta:

you removed the angled lightswitched :(

image

image

seems like the other problematic ones that I found before were moved. nice

box: 

you switched the normal newscasters in brig out for sec ones. if you're going to do this do it for all maps, I think Meta is currently the only other map lacking them but check Delta just in case.

image

I don't really like the placement of this light but this is very nitpicky for me to bring up lul. maybe try setting the dir of the new light to 2 and see if you think it looks better

image

i don't think the dead like to read the news. if it was meant for the corner put it in his office

image

this is blocking a lightswitch when the door is open. You have a lot of room to play with in the locker room, find a better place for it

image

I don't think xenobio needs two newscasters for one room. remove one of them please

image

>I disagree, placing it next to the AI like on the other stations makes it make more sense because consistency. Same thing with the AI request console on meta, but changing that would be scope creep.

Ehhh, If you want to change it make a PR for it and do all of them at once, it just looks awkward now... besides, Meta is not Box.

**Comment by Contrabang** [comment]
Should all be resolved now!

**Review by S34NW — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Review by Bm0n — APPROVED** [review]
maps good now

**Pull request merged**
