### PR TITLE
Nanotrasen Rep Cane Tweak

### PR DESCRIPTION
**Pull request by Fox-McCloud**
NT Rep's cane is now a child of the classic baton---as such, it will now have a cooldown between uses and stun for less duration.

This keeps it as a viable self-defense/deterrent weapon, while not allowing it to be an out and out combat weapon.

:cl: Fox McCloud
tweak: NT Rep's cane stuns for less and invokes a cooldown between use, similar to telebatons
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Good change. I've always liked the way the classic baton works far more.

**Comment by Plotron** [comment]
No more shocking Representatives!

Well, I guess I had it coming!

**Comment by taukausanake** [comment]
Can we still have a stun cane? I really do like the sound of just poking someone with a walking stick and tasering them on to the floor with it. And then the repeated tasering as they have a seizure while you stand above them like the smug shitface you are :D

**Comment by Plotron** [comment]
A stun cane? Where do you want it?

**Comment by TheDZD** [comment]
I would like to add that classic_baton is hilarious when used by clowns/anyone with the clumsy mutation, who can stun themselves for 36 cycles (72 seconds).

**Pull request merged**
