### PR TITLE
Make blue carpet smooth.

### PR DESCRIPTION
**Pull request by Bill-Luxe**
So, i look at blueshield office and found ~~shitty~~ blue wierd carpet.
This pull make new blue carpet and blue carpet item tile, which have smooth effect!
Also, i edit map to replace tiles in blueshield office to blue carpet.
ALSO, needed tile item icon and broken state, this my request for this pull.
~~Say me what i dont broke map, please~~

### CODE REVIEW

**Comment by Bill-Luxe** [comment]
Oh, i forget.
Pictures:
1. [In office](https://cloud.githubusercontent.com/assets/17644501/22618398/288cd3e4-eaec-11e6-8d8f-41908819821e.png)
2. [Smooth effect test](https://cloud.githubusercontent.com/assets/17644501/22618400/2cebccce-eaec-11e6-9187-20719478e547.png)

**Comment by Fox-McCloud** [comment]
Needs pics. Also, if I"m understanding you correctly, you're still missing sprites? This can't be accepted until you have those.

**Comment by Bill-Luxe** [comment]
@Fox-McCloud Already upload pics. About missing sprites - hope today i add these spirtes , but later.

**Comment by Bill-Luxe** [comment]
Added item-tile icon and broken carpet sprite (don't use cuz if carpet var/broken in 1 and icon updating = carpet deleting)
default

@Fox-McCloud I think everything ready.

**Comment by RemieRichards** [comment]
god that's an eyesore.

**Comment by Bill-Luxe** [comment]
@RemieRichards Sorry, but item and "broken" icon done by my friend, and i am bad with that.
Better to replace with something better but what i say - i am not spriter.

**Comment by RemieRichards** [comment]
It's mainly the white on blue, both of the shades picked for those colours simply don't work.
The overall shape of it is similar to other carpets, and is fine, the colours just need tweaking is all :)

**Comment by Fox-McCloud** [comment]
Yeahhh, going to concur with @RemieRichards here, That just looks absolutely horrible.

**Comment by taukausanake** [comment]
I have blue carpet icons that are basically recolored normal carpet icons. I'm sure I have them somewhere but don't remember if they look any different than these. I'll bring them up if I can find them

**Comment by Fox-McCloud** [comment]
merge conflicts.

**Comment by Bill-Luxe** [comment]
Will fix then found new hecking icon :\
/me run away into darkness...

**Comment by Fox-McCloud** [comment]
Should I close this for now then and you just submit a fresh PR once you've found the icons?

**Comment by Bill-Luxe** [comment]
I don't think i'm gonna back with new PR, but hope someone who not lazy make pr with better sprite :Р
Welp, thanks you for critic, it was a nice try to make first PR on english language repo :D 
@RemieRichards And thanks you too.

**Pull request closed without merging**
