### PR TITLE
Engineering Drip Lite™

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Adds Engineering/Atmospherics Bomber jackets
Adds atmospherics backpack and satchel

Includes relevant species sprites, changes default atmospherics bags to their respective variants when spawning on players/in lockers, also adds all items to vending machines in engineering.

Only going with these items in this PR as the others from the previous one have had a grand total of 0 progress since that time and these were the least controversial items that I wasn't requested to work on
## Why It's Good For The Game
More outfit/bag variants

## Images of changes
Bomber jackets (with unzipped versions):
image

Atmospherics bags: (Satchel item sprite made by atteria#4221 in discord)
image

In hand sprites for bags:
image

## Changelog
:cl:
add: Added engi/atmos bomber jackets, backpack and satchel for atmospherics
/:cl:

### CODE REVIEW

**Comment by Christasmurf** [comment]
Should be deconflicted again

**Comment by SteelSlayer** [comment]
Needs a deconflict again, but then this can be merged.

**Comment by Christasmurf** [comment]
Gang shit should be deconflicted again

**Review by SteelSlayer — APPROVED** [review]

**Comment by SteelSlayer** [comment]
Actually looking over the sprites again, I feel like something is a little off with this view of the satchel: 

image

Like, there might need to be another dark yellow pixel to complete the bag. Maybe even need part of the strap to be shown connecting to the bag as well.

**Comment by Christasmurf** [comment]
I will sort that shortly

**Comment by Christasmurf** [comment]
image
image
Reshaped to fit the human and grey better

**Pull request merged**
