### PR TITLE
Minor visual update to MISC testing. 

### PR DESCRIPTION
**Pull request by fj45**
testinglab

Added two firefighting closets as well.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Under dream maker please go into build->preferences and uncheck "automatically set FILE_DIR for sub-directories"; PR will not be accepted with a messed up .dme =p

**Comment by fj45** [comment]
Bugger, should have map merged that. Is it still alright?

**Comment by Fox-McCloud** [comment]
Needs to be mapmerged =p

**Comment by fj45** [comment]
Alright, lets see if I can fix this...

**Comment by fj45** [comment]
¯\_(_)_/¯ 

Hope this works!

**Comment by Fox-McCloud** [comment]
yeah, you got it.

**Pull request merged**
