### PR TITLE
Touching up drink sprites

### PR DESCRIPTION
**Pull request by Ionward**
**What does this PR do:**
I noticed how flat some of the drinks look, and how some drinks don't match visually what they should be, and felt like doing some drink sprites!  
(rewriter, whiskeycola, milkshake)

**Images of sprite/map changes (IF APPLICABLE):**

[Here's a link with an album with the old and new versions of all the sprites, I hope it helps!](https://imgur.com/a/ywVKUC6)

Everything I've changed: Ale, Bloody Mary, Brownstar, Cognac, Gin Fizz, Grog, Ice Tea, Kahlua, Milkshake, Rewriter, Robot Tears, Rum, Servo, Synthignon, Synth n' Soda, Tequila, Uplink, Vermouth, Whisky Cola, Whiskey, and Whiskey Soda.

**Changelog:**
:cl:
imageadd: Updated some drink sprites!
/:cl:

### CODE REVIEW

**Comment by Pixelzilla** [comment]
Can we get some before and after comparisons for each sprite?

**Comment by Nicaragua1** [comment]
@Pixelzilla was going to ask the same:point_up:

**Comment by variableundefined** [comment]
Wow. I really love it.

**Comment by KasparoVy** [comment]
Let's get CRUNK IN SPACE

**Pull request merged**
