### PR TITLE
You can now cancel surgery after cutting someone's ribcage open again

### PR DESCRIPTION
**Pull request by Crazylemon64**
I forgot to document this in the IPC surgery update PR, and so, I am removing it at Fox's request.

:cl: Crazylemon
tweak: You can now mend incisions after having cut open someone's ribcage.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
This is extremely unintuitive, why should it be a thing?

**Comment by Lady-Luck** [comment]
Why was this part of a IPC surgery PR

**Comment by Crazylemon64** [comment]
Because I was overhauling surgery in general in the process, including reconciling `can_use` with the rest of the system.

**Comment by Kyep** [comment]
Does this fix the bug where sometimes people can get stuck in surgery, unable to finish the surgery?

**Comment by Fox-McCloud** [comment]
>Does this fix the bug where sometimes people can get stuck in surgery, unable to finish the surgery?

I believe it should; that was one important aspects of mend--if the surgery ever went completely askew you could just mend it and start over.

**Comment by Crazylemon64** [comment]
By the by, which particular surgery was it that could get stuck, without a means of finishing?

**Comment by Kyep** [comment]
@Crazylemon64 If memory serves... implanting a medical hud into someone.

**Pull request merged**
