### PR TITLE
[FEATURE][REFACTOR] Accessory changes, R&D search function

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds Bay's accessory update (https://github.com/Baystation12/Baystation12/pull/8081). Might require some changes later as the PR's still open at Bay. Also ports over Bay's internal storage system and applies it to labcoats and webbing vests (noticeable on the backend only). Gives the Blueshield a shoulder holster (general one, not detective one, as he does use energy guns) as he can now wear a tie and holster.
2) Adds a search function to R&D (https://github.com/tgstation/-tg-station/pull/7586).
3) Personal lockers will now have their owner removed when unlocked.
4) Fixes the JMP button in the incendiary mithochondria log.
5) Fixes vulnerabilities in the APC and air alarms.
6) Fixes a variety of simple runtimes by adding sanity checks.
7) Adds /tg/'s defib changes (https://github.com/tgstation/-tg-station/pull/7624). The CMO gets a compact defib (which is now the steal objective), the ERT gets a single combat defib.
8) Updates the list of jobs that won't get certain steal objectives.
9) Fixes the detective laptop access (https://github.com/ParadiseSS13/Paradise/issues/268).

### CODE REVIEW

**Comment by Markolie** [comment]
@Fox-McCloud Ready. Also, Travis!

**Comment by Fox-McCloud** [comment]
@Markolie 

You may want to port over TG's accessory suit sprite HUD thing as well; the one where you can tell if you have something equipped to your suit or not (and would prevent the "where's my Captain's medal" questions).

**Comment by Markolie** [comment]
Not sure what you mean with the suit sprite HUD. This PR does include an overlay for suits, so if you wear a shoulder holster, it'll show up on your character. Same for ties, webbing vests, etc. Only the scarves don't have an overlay.

I think having the webbing vests orderable is a good thing: they're not readily available at round start so the power gamers can't abuse them, but if the crew is in need of extra storage capacity they can order them from cargo.

**Comment by Fox-McCloud** [comment]
@Markolie 

I meant clothing HUD, where you put your clothes on to wear them; on TG, there's a little tiny icon that shows what's attached to the suit.

That sounds good, in theory, but they still have access to them quite readily; taking 5 minutes to order them is a rather trivial task for a 5 slot storage item that can easily be hidden (since it's attached to the jumpsuit, anyone who has something that hides a jumpsuit can easily use this without anyone knowing).

**Comment by Markolie** [comment]
Actually, the new webbing vests are extremely obvious on-sprite.

**Comment by Fox-McCloud** [comment]
wasn't referring to stuff like that; more things like hardsuits, HoS's jacket, space suits, etc. A lot of things that obscure jumpsuits will obscure this.

**Comment by ZomgPonies** [comment]
Did you keep the action_button stuff I had setup for ties/holsters? I know for one I really appreciate being able to holster/unholster my weapon through a UI button rather than digging through verblists.

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

The functionality of webbing vests was not touched, nor was the accessory/tie shoulder holster--merely players' access to them.

**Comment by Markolie** [comment]
@ZomgPonies Yep, I only modified it so it supports having multiple accessories. I'd hate to lose that function.

@Fox-McCloud You're right. I've removed the webbing vests from cargo. I'm not too sure about the accessory HUD, but I'll look into it. Not sure if it'll make it into this PR though.

**Comment by Markolie** [comment]
Going to re-open a clean PR

**Pull request closed without merging**
