### PR TITLE
Adds new Revenant sprites

### PR DESCRIPTION
**Pull request by Quantum-M**
**What does this PR do:**
Adds new revenant sprites, which tend to display a different "ghost". The sprites are chosen randomly at the moment.

The different sprites are: A evil ghost, a sad ghost, a happy ghost, and a angry ghost. The original revenant sprite has not been touched besides moving it into a new, separate file.

**Images of sprite/map changes (IF APPLICABLE):**

image

**Changelog:**

:cl: Quantum-M
add: Adds new Revenant sprites that are chosen randomly.
/:cl:

### CODE REVIEW

**Comment by variableundefined** [comment]
I like the sprites, but there's a really big problem.

**Comment by Quantum-M** [comment]
What would that be? The conflict?

**Comment by Ionward** [comment]
Gives me Luigi's Mansion sort of vibes? I like 'em!

**Comment by variableundefined** [comment]
Just the conflict

**Comment by Ty-Omaha** [comment]
spooky scary revenant sends shivers down my spine

**Comment by KasparoVy** [comment]
Shrieking ghosts will suck your souls, seal your doom tonight

**Comment by Aurorablade** [comment]
I honestly do not like the sprites. I mean i appreicate the effrot you had to put into them they just feel off.

**Comment by Pixelzilla** [comment]
I'm not really crazy about the sprites. I like the fact that the original revenant has no obvious facial features, makes it seems a bit more spooky and the colors used are also not very eye catching and that helps when you're trying to be a spooky ghost.

The new sprites all have vibrant red "faces" and i feel like the really bright colored ones would be more difficult to play as since they certainly draw your attention more than a darker color like the muted purple that the original is.

**Comment by TheSardele** [comment]
Not a big fan, the revenant's non-humanoid form and lack of a face gives off a really alien appearance, giving it horns and an "evil" face just detracts from that for me.

**Comment by Couls** [comment]
I like the effort and I think it's nice for paradise to have something unique but at the same time I really like TG's revs sprites that are both more detailed and have all four directions.

Look at these bad boys!
image
image

**Comment by Fox-McCloud** [comment]
I....really don't like these. They're goofy and whimsical---for a being that causes nothing but grief and heartache.

if TGs has proper alpha then it'd be way better.

**Comment by MrMagolor** [comment]
I like the goon wraith (basically their revenant) sprites- conveys the "dark eldritch being that just has fun tormenting you"

**Comment by variableundefined** [comment]
Goon sprites cannot be ported, but we can attempt to make our own version of their features.

**Comment by Fox-McCloud** [comment]
Their sprites can be ported if they're in the public release or we get explicit permission.

**Comment by variableundefined** [comment]
Closing for reasons stated above

**Pull request closed without merging**
