### PR TITLE
HTML5, IE11, CSS3

### PR DESCRIPTION
**Pull request by tigercat2000**
Oh dear god this took me over 6 hours of debugging for one single fucking issue. Nearly 12 hours of work in total.

Great start. But, anyhow, this PR enables HTML5 for both the datum browser and nanoUI. This is as simple as adding a <meta> tag to their headers.
The rest of this PR is fixing all the bullshit that's not compliant with HTML5 "Seriously, write better HTML bitch" standards.

Fucking things I had to completely overhaul:
 - jQuery has been updated to the latest 1.x version.
 - jQueryUI has been updated to the latest version.
 - jQueryTimers have been expanded into development mode in the libraries file, updated to the latest, and given attributions.

Now, onto the non-technical talk of "why would we ever want this"
 - Running HTML5 IE11 is so much more fucking responsive, so much more.
 - Happy side effect (if local tests mean anything)- The nanoUI lag on client connection (y'know, where you can't actually open any UI's for like 10-30 seconds) is gone.
 - CSS3 means fancy fucking gradients and more (when I get to it)
 - Potential for prettier UI's (when someone gets to it)

Shit that I can't/won't fix with this:
 - Mouse-wheel scrolling seems a bit iffy with this, I'm not sure if it's IE, the HTML, or my mouse, so. I am pretty sure it's IE, though, and that's not something I can fix.
 - The nanomap (crew monitor map) can now be dragged right off the screen. Leaving you stuck staring at a blank screen. Don't drag it off the screen and everything is good!
 - CodeMirror now runs properly, without the weird line bugs and strange selection mechanics.
  - I also took the opportunity to refactor how the buttons work, no more weird inconsistant buttons.
 - NanoUI now has a proper fucking debugging state- If topic call logging is enabled, nano will output all it's errors to the client. This is quite an improvement over literally no error logging at all.

### CODE REVIEW

**Comment by orelbon** [comment]
so...what does all this mean?  i don't speak code :x

**Comment by tigercat2000** [comment]
@orelbon read the "why would we ever want this" section

**Comment by orelbon** [comment]
ah yes very good :+1:

**Comment by Iamgoofball** [comment]
Does this work with Microsoft Edge? Or does it still use shitty IE from Windows 8?

**Comment by tigercat2000** [comment]
@Iamgoofball fuck if I know, I'm running windows 7. According to microsoft's documentation, the tag means it'll use the latest IE version.

**Comment by Tastyfish** [comment]
According to the user agent with a page formatted in this way in byond, it is `Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)` as in, IE 8, although for all I know the user agent is always wrong when using the iexplore activex control the way byond does. If it works smoother, it works smoother.

**Comment by tigercat2000** [comment]
@Tastyfish I did notice the user agent being fucky in a seperate project playing with this stuff- however, even if it is running IE8, the important part is the CSS3 and HTML5, which it definately is running.

**Comment by Tastyfish** [comment]
Agreed

**Comment by tigercat2000** [comment]
wee

**Pull request merged**
