### PR TITLE
Adds ghost-following and admin-jumping for AI eyes and ghosts' bodies

### PR DESCRIPTION
**Pull request by Krausus**
This took a lot more effort than anticipated.

* Ghosts can now follow AI eyes, rather than always uselessly following their core.
  * aieyefollowing_ghosts
  * AI eyes even show up in ghosts' Jump to Mob and Follow verbs!
* Admins can now jump to AI eyes, rather than always uselessly jumping to their core.
  * Exciting new Eye links will now show up all over the place when dealing with AIs!
  * aieye_1
aieye_2
aieye_3
aieye_4
* Ghosts and admins can now follow/jump to the body of a ghost, assuming the ghost actually has one.
  * This won't show up in the *fancy* player panel, because I'm too lazy to go through the trouble to add it there.
  * ghostbody1
ghostbody2
* Most places that used hard-coded ghost follow/admin jump links have been replaced by calls to new ghost_follow_link and admin_jump_link procs, respectively, since it would be an atrocity to add AI eye snowflake code all over the place.
  * I still had to do so in a couple places anyway, because browse windows.

### CODE REVIEW

**Comment by Robertha89** [comment]
Can this be done for bodies and ghosts to?

**Comment by Earthdivine** [comment]
Beautiful

**Comment by Krausus** [comment]
> Can this be done for bodies and ghosts to?

Being able to follow/jump to the body of a ghost? That would probably be feasible...

**Comment by Fox-McCloud** [comment]
Very nice!

:+1:

**Comment by Robertha89** [comment]
Great, this will fix so many admin issues, regarding people dying and then ghosting so you jump to the ghost instead of the body. :+1:

**Pull request merged**
