### PR TITLE
Purified/Holy construct tweaks

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Changes soulstone purification to only be possible by the Chaplain and any Paranormal ERT members. (`isholy` flag)
Also changed Holy Artificer constructs to make purified soulshards rather than regular ones.

## Why It's Good For The Game

It really doesn't make much sense that any idiot with a bible can exorcise a soulstone.

## Changelog
:cl:
tweak: Soulstones can now only be purified by Chaplains and other holy crew members (Paranormal ERT)
tweak: Holy Artificer constructs now spawn purified soulstones rather than regular ones
fix: Fixed cult constructs not showing as antagonists in admin logs
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
I can make purified construcs sprites if you want, blue shifting doesnt look too good

**Comment by SabreML** [comment]
> I can make purified construcs sprites if you want, blue shifting doesnt look too good

If you're up for it, sure!
There only needs to be one for each construct type, no need for three like the cult ones.

**Comment by Kyep** [comment]
Blue-tinting them doesn't look good. They need their own sprites.

**Comment by Carthusia** [comment]
I like this, the other day, some guy who had obtained a chaps soulstone sharded a patient of mine on the shuttle, at round end turned out the patient wasn't even a target.

As for the glow they let off, perhaps a holy golden or holy white aura?

**Comment by SabreML** [comment]
Drafting until I've got some sprites

**Comment by Kyep** [comment]
Holy constructs really need to be their own mob type with unique sprites.
Maybe something like a lightgeist. Weak but not useless.
They cannot be loyal to the Chaplain, and I'd really prefer the Chaplain not have any soulstone at round start.

**Comment by SabreML** [comment]
In the interest of getting the everything else through, I've removed the blue tint from purified constructs.
I still think it'd be good to have some way to distinguish cult constructs from holy ones, but that can be done later.

**Review by Kyep — APPROVED** [review]

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
