### PR TITLE
Removes racist safe

### PR DESCRIPTION
**Pull request by Mooballoono**
## What Does This PR Do
This PR changes one of the sound effects or cracking a safe from an asian slur to "crink".

## Why It's Good For The Game
While most people dont care since its just a sound effect, there are some people who have seen it and thought it was racist which isnt a very good look for the game.

## Testing
opened the game
went to a safe
image
closed the game

## Changelog
:cl:
tweak: Changed safe sound effect to "crink"
/:cl:

### CODE REVIEW

**Comment by Mooballoono** [comment]
if someone knows how to stop those 3 unrelated commits from showing up please tell me

**Comment by DGamerL** [comment]
I think you didn't switch to a new branch when making this new PR!

**Comment by DeckardCainRPC** [comment]
i've been asian all my life and i'm more insulted by the insinuation that my people are so fragile as to burst into flames upon seeing a string of characters out of context. the japanese internment camps kind of set my family's bar for "offensive" and we're not in a hurry to dilute the seriousness of that injury by turning around and exaggerating the impact of non-issues

**Comment by OctusGit** [comment]
Im confused how this is an issue when it clearly context wise has nothing to do with slurs.

**Comment by ArcZelf** [comment]
💀

**Comment by Mitchs98** [comment]
I have never in the long time I've played on the server ever hear someone complain about this being racist or even hinted at it being racist. It's a noise, nothing more, unless you obviously use the word in a derogatory manner or try to hard justifying it _as_ racist.

It's overall not a major change...but a very needless and pointless one.

**Comment by Carthusia** [comment]
Sorry what word is "racist" here?

**Comment by Sirryan2002** [comment]
I think what people needed to say has been said, please limit further discussion on this PR to technical review/comment.

**Review by S34NW — APPROVED** [review]
Code is techinically sound, as it is a simple change

**Comment by Mooballoono** [comment]
bad idea i guess

**Pull request closed without merging**
