### PR TITLE
Updates botany and makes owning a chem dispenser possibly illegal

### PR DESCRIPTION
**Pull request by Miraviel**
### **This will look like a botany buff at first glance. Please read it through properly before making any assumptions.**

(It is ready to merge, but should it pass the balance/design checks, I wish to see it testmerged first, thus the WIP state.)

I'll sum it up: botany is one of the powergaming departments (next to science and mining), we all know this. It was designed to be somewhat reliant on other departments (cargo and medchem). As it was mentioned by a fellow staff member, "Having to walk over and hope other departments can be bothered to help you is just annoying, really, and I don't blame people for trying to skip that. After the 100th time, "Can I please have chemicals X Y Z" is not engaging RP, it's just irritating."

This led to players getting the chem dispenser every round now because 1) science wants things instantly 2) botanists want things instantly, making botany even more powerful, as now they have access to pretty much _every chemical,_ save for uplink/admin-spawned ones.

I see people cryoing/suiciding because they don't have the chem dispenser as botany. I will be blunt, it fucking sucks and I tried to fight it for months, both IC and OOC, but people simply don't budge - the past ten rounds I've been a botanist, I could only find one guy who begrudgingly accepted not having a dispenser and I had to spend 10+ minutes to explain it why we don't need one.

As this has been ongoing for 6+ months at least, I just concluded that our botany culture simply changed and people don't want to go back to the old ways.

I think we should stop fighting it and that we should just accept that people don't want to **_rely_** on other departments to start working. No other departments do it. Medical is able to do surgery from the get-go without going to cargo to beg for surgery tools.

Let's make botany the same. The idea is this.

### 1. Left 4 zed jugs are replaced with unstable mutagen jugs ("jug of Mutation Solution"). 

Left 4 zed works on servers where the pacing is slow, not here. People want stuff and they want it instantly. This will allow them to mutate blumpkins and whatever RND needs instantly (good for nukie rounds). Currently, the NutriMax vendor starts with 800 units, we can tweak this.

image 

image

This cannot be made by the biogenerator (as opposed to left 4 zed jugs) to avoid perma biogen being too powerful. As before, you can cross blumpkins with glowshrooms and grow your own mutagen, infinitely.

Edit: Left 4 zed is still in the biogenerator, to allow perma/public gardens to freely, but slowly, mutate.

### 2. Replaces ammonia bottles with saltpetre bottles. Accessible without hacking the vendor.

This will allow botanists to either maximise a plant with potency and then transfer its potency to disks later in the round (should RND upgrade them) and/or inject it into bees and grind honey at roundstart.

Currently starting with 5 bottles (150 units).

image

### 3. Diethylamine (and saltpetre) bottles are moved out of contraband.

Contraband should be meaningful. Currently, it is not, it is just yet another chore for which botanists **must** get a multitool - thus, we encourage an already strong department to have even more tools. (They start with a screwdriver, so now they are always able to hack doors due to their "necessary" equipment.)

Diethylamine is excellent for restoring plant health when you use too much unstable mutagen on it. No reason to be hidden in contraband.

image

### 4. Adds bee costume to NutriMax' contraband section (making it its only contraband).

Drip is an essential tool but should be hidden away. This will also make hacking NutriMaxes worthwile, but not necessary.

It would make more sense to put this into their clothing vendor but the NutriMax is kind of an equipment vendor already and it needs some fun contraband.

image

### 5. Adds a beekeeper starter kit to botany.

As bees are as essential to botany now as an operating table for surgeries for medical, they now start with bees. It is a custom crate without the extra bee suits.

This will make cargo not essential for botany, but a backup option should the bees get stolen/destroyed in an accident - as cargo is for every other department. A backup/bonus option.

image 
image

### 6. Adds beekeeper hat and suit to botany lockers.

Nothing is more annoying than to have bees but you cannot enter your own workplace, because nobody ordered any extra suits.

Only botany has these (access-locked!) lockers on the station, checked on all three maps.

image

### 7. MegaSeed Servitor contraband changes: glowshroom, nettle, and plump helmets are no longer contraband.

Glowshrooms and nettles are "the RND plants", it makes no sense they are hidden behind contraband.

Plump helmet is an edible mushroom and one that has its own custom food, again, makes no sense to be hidden away as liberty caps.

Cannabis is still contraband, so it will not completely remove the "rush multitool as botanist" meta, but not every round is a cannabis round. If you want to get thc or omnizine, get the funny yellow tool.

image

### 8. It is now illegal by Space Law to have a chem dispenser, unless your job is assigned one.

This needs an obvious change to Space Law @Necaladun, so I leave the specifics to you. I suggest listing having a chem dispenser under "Possession of a Restricted Weapon" (unless your job assigns you one), as you can make pretty much every pyrotechnic with it + an igniter, not to mention narcotics.

This will not only hurt botanists, but also random assistants (or bartenders) running up to RND and saying they need a chem dispenser for their whatever wacky ideas. It is insane that you can hand out an entire chem board and get away with it, but you hand out the tiniest grenade and you are brigged for distributing weapons.

## Why It's Good For The Game

- It kills the chem dispenser meta, ensuring scichem always has 2 chem dispensers and that botanists don't have access to every possible chemical (save for admin/uplink ones) just because they need 2 specific ones from the machine.
- It makes botany less of a chore, you don't need to run to people and beg for stuff to start playing and you don't need to get a multitool for accessing stuff you want to have every single round.
- **_This department is way behind mechanically than what our players wish for and do every single round._**

## Testing

Spawned in and clicked on things, see the screenshots above.

## Changelog
:cl:
add: It is now illegal to own a chem dispenser unless your job provides you with one.
tweak: Botany was updated, here are the changes. To sum it up: you can no longer have a chem dispenser, but you are given tools to get everything you had before with relative ease.
add: Botany now starts with a beekeeper starter set and protective gear in their lockers.
add: Added "jug of Mutation Solution" to the NutriMax. It contains 80u unstable mutagen per jug.
add: Added "saltpetre bottle" to the NutriMax. It contains 30u saltpetre per bottle.
add: Added bee mask and bee suit to the NutriMax' contraband section.
add: Added three "jugs of Mutation Solution" to perma, public, and maintenance gardens.
tweak: Diethylamine bottle is no longer in the contraband section in the NutriMax, it is available without hacking the vendor.
tweak: Glowshroom, nettle, and plump helmet seeds are no longer in the contraband section in the MegaSeed Servitor, they are available without hacking the vendor.
del: Removed left 4 zed jugs from the NutriMax vendor. Still printable by biogenerators.
del: Ammonia bottle was removed from the NutriMax.
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
Belatedly, I realised, that perma no longer be able to slowly mutate their plants with the lack of Left 4 Zed. This is an unintended side-effect of this PR. If we want perma to have some way of mutating plants, please let me know and I could map in a few mutagen bottles for the RNG game. (I don't want to make the biogenerator able to print mutagen as of now, as it would defeat the purpose of plant crossing.)

**Comment by datlo** [comment]
Alternative option for perma mutations : Add a couple of every botany jug (including mutagen) to the perma maintenance room. This is only accessable during radstorms or when maint doors are unlocked stationwide, so this leaves the opportunity for perma mutation plays without making it a guarantee every round.

**Comment by Denthamos** [comment]
Not a fan of perma, free garden, or anywhere else that is not botany with access to the vendor being locked out of slowly mutating things and cannot sign off on this while it is like that.

**Comment by PacifistDalek** [comment]
I like this overall. A thought, though:

*Ahem*

**The Bee costume should function as a beekeeper suit if it doesn’t already**

**Comment by Miraviel** [comment]
> Not a fan of perma, free garden, or anywhere else that is not botany with access to the vendor being locked out of slowly mutating things and cannot sign off on this while it is like that.

Added 3 jugs of mutation solution to every biogenerator areas that is not hydroponics (public garden, perma, maint botany). That's 240 units of mutagen, 48 mutations, after which you need to go ask chemistry for more or - if you are in perma - tough luck, you cannot grow death nettles with a bad luck.

> **The Bee costume should function as a beekeeper suit if it doesn’t already**

Fret not, it already does

**Comment by Sirryan2002** [comment]
My thoughts on this PR
* Moving stuff out of the contraband sections of the vendors is a great change, I don't know who thought it was a good idea to lock department mechanics behind hacking, it's stupid.
* Botany's reliance on strange mutagen is bad, if the only way to progress in botany is to rely on RNG mutation by dumping copious amounts of stuff on the plants there's an issue with progression. Furthermore, if there's limited amount of the magical juice, botanists are going to find ways to get more either by begging or stealing. (See my 4th point as well)
* I'm conflicted on making beekeeping so readily available, I think it should be better integrated into botany mechanics instead of slapping a crate of it in botany at roundstart. Beekeeping is so separated from the actual mechanics of botany that beekeeping really doesn't have much to do with plant mechanics. I'd like for it to stay as a crate until it's better tied into botany, service members can buy it if they really feel they want to do beekeeping.
* Instead of making chem dispensers illegal find a way to give botany better ways to make more strange mutagen, they can export plants for space cash $$$, perhaps give them an opportunity to buy in bulk more mutagen or to buy a machine that allows them to use plants they grew to make more mutagen.

**Comment by Miraviel** [comment]
> * Moving stuff out of the contraband sections of the vendors is a great change, I don't know who thought it was a good idea to lock department mechanics behind hacking, it's stupid.

Yeah, if this PR gets denied, this part will be something I re-PR. At least the dieth/seeds movement because they are truly every round stuff...

> * Botany's reliance on strange mutagen is bad, if the only way to progress in botany is to rely on RNG mutation by dumping copious amounts of stuff on the plants there's an issue with progression. Furthermore, if there's limited amount of the magical juice, botanists are going to find ways to get more either by begging or stealing. (See my 4th point as well)

I don't think RNG is that bad. It's fun to see if my plant mutates into glowcap or shadowshroom and if I needed 2 pours for it or 20. It's always a nice surprise to get things for the first few tries.

If we wanted to have it the infinite way without chems, there is always the floray somatoray, that is currently locked behind RND, not very responsive for players (I barely know what it does whenever I shoot it), and does not really do the trick. It could be improved upon so it can hardmutate plants, but then we go back to Denth's issue, that perma/public gardens need it to, and boom we gave perma prisoners infinite attempts at mutating possibly lethal plants...

> * I'm conflicted on making beekeeping so readily available, I think it should be better integrated into botany mechanics instead of slapping a crate of it in botany at roundstart. Beekeeping is so separated from the actual mechanics of botany that beekeeping really doesn't have much to do with plant mechanics. I'd like for it to stay as a crate until it's better tied into botany, service members can buy it if they really feel they want to do beekeeping.

It works on most other servers I've seen, where bees are ready from the get-go. They are also essential with the current meta - botanists need two things from the chem dispenser, unstable mutagen and saltpetre. Bees are the way to generate their own saltpetre. If I don't add bees, we keep the "run to another department for you to start gaming". Botanists want to game and if we deprive them their tool, they'll cryo/suicide/break into science and steal a dispenser.

It is ugly, but this is how it is now. We did not do anything about it for about a year and it became player culture.

> * Instead of making chem dispensers illegal find a way to give botany better ways to make more strange mutagen, they can export plants for space cash $$$, perhaps give them an opportunity to buy in bulk more mutagen or to buy a machine that allows them to use plants they grew to make more mutagen.

They have a very simple way to make unstable mutagen. Mutate pumpkin once. Harvest glowshroom. Take 3 traits from these plants. Put it into wheat/peanuts. Get 50+ plants easily (especially if you have bees). Put them into the all-in-one grinder. You constantly have 120 units of mutagen buckets.

**Comment by Sirryan2002** [comment]
In that case, the bees would make more sense. While I don't have too many more concerns left, I would like to see Denth's requests addressed.

**Comment by Coolrune206** [comment]
There are some good steps here like the movement of plants out of contraband but the rest of this I'm not so sure about. Bees are to botany like RnD prototypes are to Science, if you want them you should have to go through cargo. They should not be available roundstart to botany.

Additionally, I'm dubious about the unstable mutagen changes. Botany is capable of manufacturing this through the aforementioned Blumpkin method. The slower start of botany while youre waiting for your pumpkins to mutate is a great time to get some plants going for the chef, I've noticed the moment botany has access to their infinite mutagen theyre a lot more likely to be busy fucking around with mutating plants than they are to be with actually growing food crops.
Instead of dealing with botany typical powergamey behaviour this feels more like it will enable it, just without a chem dispenser.

**Comment by Miraviel** [comment]
> There are some good steps here like the movement of plants out of contraband but the rest of this I'm not so sure about. Bees are to botany like RnD prototypes are to Science, if you want them you should have to go through cargo. They should not be available roundstart to botany.

I agree, I would normally not make them available, but people want saltpetre from the chem dispenser and they want it fast. I am afraid if we deny them, they'll constantly go to beg RND for a dispenser and despite it being illegal, we go back to the current meta.

I am more than willing to remove the bee starter kit + suits if we can figure out how to prevent this because I like interacting with cargo, especially since I need to talk with the HOP/captain too now to access the service account. I just need ideas how to cut down on this addiction to the chem dispenser gameplay.

If we don't have an idea, then we have to facilitate these minmaxers somewhat to stop them being insufferable.

> Additionally, I'm dubious about the unstable mutagen changes. Botany is capable of manufacturing this through the aforementioned Blumpkin method. The slower start of botany while youre waiting for your pumpkins to mutate is a great time to get some plants going for the chef, I've noticed the moment botany has access to their infinite mutagen theyre a lot more likely to be busy fucking around with mutating plants than they are to be with actually growing food crops. Instead of dealing with botany typical powergamey behaviour this feels more like it will enable it, just without a chem dispenser.

I 100% agree with this. The issue is, it is completely different in practice. I spawn in as a botanist, get blumpkins+glowshrooms growing. My colleague is already at RND, begging for a chem machine.

Just today, I had an unstable mutagen plant pretty much ready by the time my colleague arrived. He asked me where the machine was, I told him we do not need it, we have the plants. Had to spend 5-10 minutes to explain it to him why we don't need a machine when we infinite-grow our own stuff.

I went SSD. Later a player DM'd me that the guy, after I disappeared, went to RND to get the machine.

This is not a one-time occurrence. As I mentioned it on the admin forums, this is something observed over the months, when me, Marm, and other botany mains actively spammed botanist rounds to teach people how to grow their own mutagen. They don't want to. They want the magical solution.

**Comment by Miraviel** [comment]
As per request of Denthamos, left 4 zed was re-added to the biogenerators to allow for slow mutation in perma/public gardens. Removed the public mutagen bottles.

Botany still does not start with any, they can print it or just use the already superior version in their vendors, the mutagen.

**Comment by Komrad822** [comment]
> I am more than willing to remove the bee starter kit + suits if we can figure out how to prevent this because I like interacting with cargo, especially since I need to talk with the HOP/captain too now to access the service account

I like the idea with the current eco changes that botany sells seeds to botany and they money they receive can be put towards bees. But as you said we want that juicy juicy potency 100%, so we put it in bees to:
A. proliferate potency across all plants
B. grind saltpetre combs to make a mix of honey and saltpetre

Cant do that if we dont have the bees, and waiting on cargo with the new eco can be a pain but there could be a solution to this. We COULD just make the machine able to extract 95% potency from the very beginning. Bees not only distribute potency and make the chem you put in them but they ALSO boost yield by a wooping fucking 10, making max yield plants output 20. So if we make the machine able to extract 95% from the very beginning we dont NEED to have bees for saltpetre, instead we can have botany use the saltpetre they have in the vendor to boost a plant and then extract the stat. 
The pathing would be:
1. Extract 50% potency from towercaps
2. Place it in fast growing plant
3. Boost said plants potency
4. Wait for growth and then harvest
5. Extract the seeds and then extract the potency
6. You now have 95% potency without the need to rush for bees but you are still stuck with shit yield, shit grow times, which is fine honestly.

With this, botanist can have plants with a good amount of chems AND the chef/crew have GOOD food that is quite filling tbh and or strong effects (I.E the glow from different plants).

**Comment by Miraviel** [comment]
I did not get a ruling on this for a long time, I consider it rejected.

**Pull request closed without merging**
