### PR TITLE
Adds the Praetorian Modsuit for Blueshield

### PR DESCRIPTION
**Pull request by PollardTheDragon**
## What Does This PR Do
This PR adds the Praetorian modsuit, for use by blueshields. Functionally, the modsuit comes with standard storage, a basic ion jetpack, and a crew monitor module. This modsuit has armor comparable to the Security modsuit. The modsuit starts inside a modsuit storage unit in the blueshield's office. The intent is to provide the blueshield with a way to recover and protect heads of staff in hot/cold/spaced areas without needing to break into EVA or steal a modsuit from engineering or security.

This also adds the Crew Monitor MOD module, and gives it to the Praetorian and Rescue modsuits.

## Why It's Good For The Game
The blueshield not needing to commit crime to do their job is a good thing. The blueshield being able to better protect and/or recover spaced command staff is also good.

Paramedics having tools for finding crew in their mod is good when their job is to find and recover crew.

## Images of changes
image
image
image
image
image

## Testing
Spawned in as blueshield, put on modsuit. Deployed crew monitor and checked it.

## Changelog
:cl:
add: Added praetorian modsuit for blueshields
add: Added crew monitor module
tweak: Gave rescue modsuits the crew monitor module
tweak: Added modsuit storage to blueshields' offices
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I thought this was based on the doom praetor suit at first, glad it ain't lmao, complety wrong aesthetic.

**Comment by spacegeese** [comment]
> I thought this was based on the doom praetor suit at first, glad it ain't lmao, complety wrong aesthetic.

blueshield on revolution rounds be like
th-3925760240

**Comment by Stoniest** [comment]
I like this addition, however a few concerns, the modsuit is akin to an atmos suit along with the added benefit of being a safeguard modsuit, maybe look into is `FIRE_PROOF` and `ACID_PROOF` resistance flags.

`complexity_max = DEFAULT_MAX_COMPLEXITY - 5` is quite a drop compared to other modsuits that are about the same, - 3 I think would be enough (It is actually shock proof unlike the HoS's/security modsuit(s), which is a good thing).

It can only hold a seclite? I don't see why it should specifically be the Seclite and not allow normal flashlights or penlights, should maybe just have it as `/obj/item/flashlight,`. Unless others think otherwise and it should be select lightsources, but I do not see a problem with it just being all forms of flashlights.

**Comment by PollardTheDragon** [comment]
> I like this addition, however a few concerns, the modsuit is akin to an atmos suit along with the added benefit of being a safeguard modsuit, maybe look into is `FIRE_PROOF` and `ACID_PROOF` resistance flags.

While the modsuit isn't destroyed by fire/acid on the ground, it does not grant one immunity to fire or acid. It actually has fire/acid armor in line with the security modsuit - in fact, all of its armor values are. You can and will still die if you're lit ablaze. The difference is that the praetorian grants immunity to atmos-based heat, so you can go into superheated environments, provided you aren't ignited - this is intended, as part of your job as blueshield is recovery of dead command, and thus it has some of the perks of the Rescue modsuit.

> `complexity_max = DEFAULT_MAX_COMPLEXITY - 5` is quite a drop compared to other modsuits that are about the same, - 3 I think would be enough (It is actually shock proof unlike the HoS's/security modsuit(s), which is a good thing).

Yeah, this is pretty low. I can probably increase it to -3 or even just flat default capacity.

> It can only hold a seclite? I don't see why it should specifically be the Seclite and not allow normal flashlights or penlights, should maybe just have it as `/obj/item/flashlight`,. Unless others think otherwise and it should be select lightsources, but I do not see a problem with it just being all forms of flashlights.

Agreed, it should probably be allowed to carry other flashlight-types. I'll adjust.

**Comment by Stoniest** [comment]
> > I like this addition, however a few concerns, the modsuit is akin to an atmos suit along with the added benefit of being a safeguard modsuit, maybe look into is `FIRE_PROOF` and `ACID_PROOF` resistance flags.
> 
> While the modsuit isn't destroyed by fire/acid on the ground, it does not grant one immunity to fire or acid. It actually has fire/acid armor in line with the security modsuit - in fact, all of its armor values are. You can and will still die if you're lit ablaze. The difference is that the praetorian grants immunity to atmos-based heat, so you can go into superheated environments, provided you aren't ignited - this is intended, as part of your job as blueshield is recovery of dead command, and thus it has some of the perks of the Rescue modsuit.
> 

Sorry, I was on about `max_heat_protection_temperature = FIRE_IMMUNITY_MAX_TEMP_PROTECT`. I get what the purpose of having it was, but I'm just a little iffy on it, the blueshield modsuit will be an all-round with what stats it has, it will literally be on of the best crew modsuits, out-performing the others but a good margin. I'll wait to see/hear what the other members of the balance team think about it.

**Review by Sirryan2002 — APPROVED** [review]
Not seeing any immediate issues, this is approved on condition it's tested

**Review by Burzah — APPROVED** [review]

**Pull request merged**
