### PR TITLE
Icon cleanup and more

### PR DESCRIPTION
**Pull request by Adrer**
## What Does This PR Do
This PR is a hopeless attempt to clean up the hellhole that are our DMI files. This includes the following 

- It removes _most_ states with duplicate names
- It removes a few states that are significantly outdated, have been replaced or are permanently out of use
- It adds a few missing states for items held in-hand that did exist for the other hand.

Or at least tries to do these things.

fix: #17153

## Why It's Good For The Game
Removing sprites that are unnecessary reduces bloat.

## Images of changes
Please consult the icondiffbot, god bless his soul.

## Changelog
:cl:
imageadd: Spellbooks now actually animated
imageadd: Items previously only visible in one hand now visible in both
imageadd: 9mm/10mm/.45 ammoboxes sprites changed
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
I think your branch is a bit outdated. If you take a look at `icons/obj/items.dmi`, it looks like the new fire extinguisher sprites that were recently merged (#16739) are being reverted to how they were before the PR was merged. Same with the fire extinguisher in-hands in the left and right hand .dmi file.

**Comment by S34NW** [comment]
image
These are not 3/4ths perspective 😠 

Apart from that, thank god someone is cleaning these up. You can also delete all the carpets from floors.dmi because they should now all be using the new types. (watch as some random away mission hard-bakes carpets though)

**Comment by Kurgis** [comment]
This object should be deleted along with its icon: `/obj/structure/chair/old`.

**Comment by dearmochi** [comment]
Closing as the last recent activity was nearly a month ago. You are free to re-open this later.

**Pull request closed without merging**
