### PR TITLE
Ripping off the bandaid - New floors & walls

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Ports over the floor sprites from our Russian downstream, SS220, and the wall sprites from TCC

All of the floors have a darker tone by default as well as a different aesthetic, which I feel is more inline with the TG look we are going for.

I did not port TG floors because they are just too bland for my taste.
image

## Why It's Good For The Game
Floors are the most dated thing we have and the best way to give the server a new coat of paint

## Images of changes
Here (https://paradisestation.org/aastuff/floordiff/) is a webmap with all 3 maps showing before/after diffs **of both the walls and floors**

## Changelog
:cl: AffectedArc07
imageadd: Replaced floor and wall sprites
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Fixing this
image

**Comment by S34NW** [comment]
Looks good, the only gripe I'd have is the "white" tileset is a bit more grey than I'd expect. But overall I like the style.

**Review by S34NW — COMMENTED** [review]
Could you also port the tau ceti stairs? (These sprites are originally from there, and their stairs are better)
image

**Comment by Carthusia** [comment]
They look nice, but somthing seems off about the top picture, is it just because of lacks the usual lighting and shadeing from standard play?

If so that explains why it looks very...flat?

**Comment by atteria** [comment]
One inconsistency about floor tiles from other servers that's always bugged me is that the beveled edge's reflections are facing the opposite direction than they would be on any object. 
If you look at the toolbox and back at the tiles, they look like they're receiving light from opposite directions.

**Comment by S34NW** [comment]
> They look nice, but somthing seems off about the top picture, is it just because of lacks the usual lighting and shadeing from standard play?
> 
> If so that explains why it looks very...flat?

that top picture is TG floors you donkey

**Review by S34NW — APPROVED** [review]
looks fine now that you added stairs too

**Comment by matttheficus** [comment]
Looks VERY jank with our walls but I suppose those are going to be another bandaid to rip off one day. I like em overall though.

**Comment by Sikroth** [comment]
Opinion: the sprites themselves look great but I'd personally rather have the brightness closer to what we currently have. These are a bit too dark.

**Comment by CinnamonSnowball** [comment]
These new floors are _significantly_ darker than our current floors, and they also mess with the floor-wall contrast quite a lot; definitely agree that the brightness should be scaled up at least a bit

**Comment by AffectedArc07** [comment]
# Please put all feedback from the testmerge on the thread

https://www.paradisestation.org/forum/topic/22599-floor-tiles-pr-feedback-thread/

**Comment by AffectedArc07** [comment]
Todo - Item sprites

**Comment by AffectedArc07** [comment]
Latest commit splits the tiles back into quadrants instead of triplets


Before:
image

After:
image

**Comment by AffectedArc07** [comment]
We using TCC walls as well now

**Comment by S34NW** [comment]
yes

**Comment by KittyNoodle** [comment]
new walls looking great

**Comment by KittyNoodle** [comment]
circuit floors have lost their animation and don't turn red when ai deltas

**Comment by AffectedArc07** [comment]
> circuit floors have lost their animation and don't turn red when ai deltas

@KittyNoodle they never did that on this codebase.

**Comment by S34NW** [comment]
While you are doing this, could you also port the superior reinforced floor tiles from TG and various other servers? @AffectedArc07

**Comment by AffectedArc07** [comment]
> While you are doing this, could you also port the superior reinforced floor tiles from TG and various other servers? @AffectedArc07

TODO - That

**Comment by AffectedArc07** [comment]
After 9 hours of work, the tiles now have a single dot ring outline, and reinforced walls have been given more distinction.

**Review by hal9000PR — APPROVED** [review]
LGTM

**Comment by hal9000PR** [comment]
PR has sufficient approval.

**Pull request merged**
