### PR TITLE
Adds Xantholne's custom borg sprites

### PR DESCRIPTION
**Pull request by Crazylemon64**
custom-synthetic
This is how Xantholne's custom sprites look.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@FreeStylaLT

**Comment by FreeStylaLT** [comment]
What about the opened-panel / battery / no-battery / shut-off sprites?

**Comment by Xantholne** [comment]
They're in. Forgot all about them when finishing and default panel didn't line up so had to make a custom panel.

**Comment by taukausanake** [comment]
Are these like the plain borg but with colors added to them? It's going to be weird seeing R2-D2 moving about the station...

**Comment by Spacemanspark** [comment]
I think it's neat.

**Comment by taukausanake** [comment]
So we can have R2-D2 and Disney won't bat an eye but we can't have metroids without fearing a Nintendo sue? :P That's MY only salt against this

**Comment by Spacemanspark** [comment]
SS13 is so full of direct references.
Honestly I'd prefer metroids too but they were removed long ago.

**Comment by Xantholne** [comment]
I mean, this game lives and breathes off of direct references. Hell we already have had lightsabers and droidekas even.

**Comment by Earthdivine** [comment]
@taukausanake Nintendo goes after anyone using their stuff, no matter how small their use is.

**Comment by Nienhaus** [comment]
R2 units don't tilt back at 45 degrees though. More like 30.

**Comment by Fox-McCloud** [comment]
mergeeee conflicts.

**Comment by Fox-McCloud** [comment]
After talking it over with @Crazylemon64 and @FreeStylaLT we felt this was too close to source content (specifically from Disney), so we're deciding to close this. Apologies.

**Pull request closed without merging**
