### PR TITLE
Adds Species Levers

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just adds a few species levers, should we wish to use them:

- Oxygen resistance/weakness
- Toxin resistance/weakness
- Brain resistance/weakness
- Clone resistance/weakness
- Stun resistance/weakness (this includes sleeping, stun, weaknen, and paralysis)
  - No, I'm not breaking each of these into a separate category; they're always treated as one when it comes to stun resistance
- Hunger rate (how quickly you get hungry
- Digestion rate (how quickly you absorb reagents)

There are not any balance changes made at this time; everything is the same, functionally; this is purely adding in additional levers, should we want to use them.

Code wise
- Hunger rate and digestion ratio are not at the human level due to how reagents and nutrition are handled (at different levels that aren't purely in `human`)
- Removed the `NO_POISON` flag; the damage is now handled by toxin resistance being set to 0 on a species that's meant to be poison immune
- `NO_BREATHE` unlinked from O2 damage
  - all current `NO_BREATHE` species are immune to O2 damage, but in the future, if we wanted a species that doesn't breathe, but still takes O2 damage, we can.
- `NO_DNA` no longer governs clone damage immunity (handled by the clone species ratio)
- Slime's brain damage is now handled by the species rather than the brain itself.

No changelog as this is mostly backend changes for designers/coders and no functionality is altered from a player perspective.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
A while ago someone mentioned creating an organ system tied to metabolism, damage values and so on. Perhaps all these values should be just tied to organs instead of one's species?

Swapping your hand for that of a different species should have some sort of an effect if the values added by this PR are ever changed.

**Comment by Fox-McCloud** [comment]
There is no organ at this time, nor am I really interested in creating one (or its complexities) at this time---the idea is interesting, but it's far far more involved than I want to be---I just want people to have the option, when balancing or designing a race to have access to levers *now*.

There's nothing saying that couldn't be done later.

**Comment by KasparoVy** [comment]
Really nice set of features

**Comment by taukausanake** [comment]
> when balancing or designing a race

Yeah because either of those are going to happen any time soon. But I get it, these do seem a lot more convenient for later use. Maybe we'll get lucky and the existing species will get modified with these

**Pull request merged**
