### PR TITLE
RAN RAN RUUUUU

### PR DESCRIPTION
**Pull request by taukausanake**
I REALLY hope I'm doing this correctly this time.

Adds in Ronald McDonald clothing in the forms of a mask, uniform, and shoes. ~~So far only a majority of the icons have been done. Making this PR now because I'm still new to doing GitHub stuff and want to go to bed.~~ Everything has been sprited and coded in properly to my knowledge, Vox clothing also.
He looks so cute!
And descriptions

[Blame NTSAM](http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=6952)

### CODE REVIEW

**Comment by NTSAM** [comment]
https://www.youtube.com/watch?v=6P_BvrtuxAI

**Comment by KasparoVy** [comment]
Changelog?

**Comment by FalseIncarnate** [comment]
Looks like some merge conflicts (guessing something in uniforms, probably from the vox robe PR).

Additionally, you only added sprites, but they aren't used anywhere. You'd need to define new clothing items to use these sprites, unless the intent was to simply include the sprites in this PR for admin-use or something.

**Comment by Iamgoofball** [comment]
Okay so

I'd argue mcdonalds is one of the most likely companies to sue us all

You don't rumble with mcdonalda when it comes to this shit

**Comment by Fox-McCloud** [comment]
>I'd argue mcdonalds is one of the most likely companies to sue us all

This. I can't agree with this, at all.

**Comment by KasparoVy** [comment]
Also please don't break the stuff from my PRs kek

General rule of thumb is to avoid putting copypasta from real life companies' licensed property in the game without permission from them

**Comment by NTSAM** [comment]
xenos are licensed right?

**Comment by tigercat2000** [comment]
jesus christ mcdonalds isn't going to sue us calm your titties

**Comment by NTSAM** [comment]
I doubt McDonalds will sue us over a few sprites when we have a gamemode based on an entire damn movie.

also dead space hardsuits plasma cutters and batman stuff and MGS boxes and 2001 space suits/pods and asimov laws and i could just go on with stuff we use.

**Comment by HereticChurch** [comment]
But mcdonalds lawyers are probably assholish enough to do something about it.

**Comment by tigercat2000** [comment]
Fuck no they won't. It isn't even worth an hour of the corporation's time to go after an obscure completely free indie game presuming they even ever receive a fucking notification. **Calm your tits.**

**Comment by FalseIncarnate** [comment]
* We no longer have a supported xenos gamemode.
* Owlman is more likely to infringe on Watchmen than Batman.
* Pretty sure Asimov's laws no longer fall under any sort of copyright, plus we modified them so it's not even pure Asimov lawsets anyways.

Point is, there's a difference between fan-works and blatant copyright / trademark infringement. If you went with [Evil Ronald](http://mugen.wikia.com/wiki/Ronald_McDonald/Kishio's_version/Edits#Evil_Donald) there might be less controversy over this, but that's not my call.

**Comment by tigercat2000** [comment]
@FalseIncarnate You're right, there's a difference between fan-work and blatant copyright and 
trademark infringement.

A drawn 32x32 pixel sprite made in the general likeness of Ronald McDonald being used in a free indie game isn't even fucking close to that line.

Having a full McDonalds store within the station, complete with golden arches logo, trademark logos everywhere, an actual menu completely copied verbatim from McDonalds, that _might_ fall on the infringement side of things, if it could be reasonably believed by a player that our server is sponsored by McDonalds.

**Comment by NTSAM** [comment]
I'mma leave this here

MUGEN McDonald was a fully functional character that shot fries out of his hands and made burgers rain from the sky to destroy his enemies, and he used sound clips from an actual commercial

This is a sprite.

**Comment by taukausanake** [comment]
I think I need to wake up earlier for this shit.
@FalseIncarnate I know I didn't finish this PR just yet. I thought I made mention to it in OP. This is literally my first pull request in the history of my life. Instructions on how to do this like the pros (read: all of you guys) is limited if anything. I want to take my time in trying to learn this process.
@KasparoVy I'll do it when I finish everything else first.
Everyone else: It sounds like this is split halfway with most of the few on here saying **no**. Well whenever or not this gets pushed I'm still going to make it for myself. I'll let you guys argue it off for now

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Earthdivine** [comment]
Considering the server is in Sweden, shouldn't this be Melandors call on the copyright thing?

**Comment by Tastyfish** [comment]
Why does paradise.dme have almost 2000 line changes for a PR that doesn't add or remove any files?

**Comment by Spacemanspark** [comment]
We have Star Wars, Star Trek, hamsteak, metal gear solid, zelda, mario, portal, half-life, aliens, and fifty billion other references in the game, some more prominent/ obvious than others. I'm pretty sure another isn't going to blow us to high hell.
The decision should be up to @melandor0, of course, as they are the host.

**Comment by taukausanake** [comment]
You forgot Pokemon as of recently. Best sprites ever.
@Tastyfish I don't know, this is my first time doing this. I have to go in raw if I'm going to find out how to PR correctly.
@Fox-McCloud Thanks for the tag.

Updated OP

**Comment by Fox-McCloud** [comment]
We didn't add Poke'mon; that's Admins adminbusing.

**Comment by taukausanake** [comment]
Oh. Okay. And I know I have conflicts. One step at a time...

**Comment by Spacemanspark** [comment]
When I get my shit sorted for this semester, I can totally add Pokemon. :^)

**Comment by TheDZD** [comment]
Might want to figure out what is wrong with the .dme file, also this has merge conflicts. 

As far as the people saying that it should be up to the host, you're missing the part where a DMCA request would be sent to *Github* over *the repository* (if some giant company for whatever reason decided to DMCA a codebase for an obscure 2D spaceman game on the internet). If Mel wants to keep copyrighted files solely on his machine for things like the jukebox, that's his decision. But the Github repo itself is a different issue.

As to whether or not a giant company would have nothing better to do than to send a DMCA notice to a small codebase for an obscure 2D spaceman games? It's unlikely, but corporate lawyers are all a part of some sort of Satanic cult that feasts on fun (in other words, they've got nothing better to do). That said, if anyone bothered to read [the Github DMCA policy](https://help.github.com/articles/dmca-takedown-policy/), you'd see the bit about Github notifying the repository owner asking them to take down any copyrighted content should a DMCA request be filed. Additionally, you can see the full list of the DMCA requests submitted to Github [here](https://github.com/github/dmca).

I've no problem with this as long as there's no use of copyrighted phrases or logos (or sounds), as those are really the major concerns with cases like these. That said, the sprites creep me the fuck out.

**Comment by Plotron** [comment]
Tbh this sprite looks like a penguin gone acid.

**Comment by taukausanake** [comment]
The .dme file might have some leaked lines from my other branches. It shouldn't though as I branched off my clean copy of the code and pulled from here, basically the same source but I'm sure I did something wrong. Maybe I'll end up closing this anyways but for now I'll see what to do about the merge conflicts. Someone said about the vox robe?

This wouldn't be the first costume to have its likeness impressed in SS13. We have a Spiderman suit and mask last I recall. Still, I don't think I care where this goes now. I'm just happy to be making it and getting to learn GitHub a bit more

**Comment by Vivalas** [comment]
Don't forget MLP, oh god the bronies.

**Comment by KasparoVy** [comment]
Yeah, the Vox robes and such were fixed in #3366 
Also, another conflict might be because of #3384 and #3392 because all three of those PRs are dealing with the same files as this PR does

**Comment by taukausanake** [comment]
Bah. I'm not going to get this done in any reasonable time. I'll just close this and go back to it when I have more time and hopefully less conflicts

**Comment by Spacemanspark** [comment]
Darn.

**Comment by melandor0** [comment]
SS13 doesn't need more references or memes.

**Pull request closed without merging**
