### PR TITLE
Makes everything terrible

### LINKED ISSUE #2429: You keep your Change Monitor verb as a Vox Raider
As it says in the title, pretty much.
Here's what went down.

- Have an IPC character with Be Vox enabled.
- Get lucky enough to be chosen for Raider.
- Check your verb tabs.
- You'll still have your Change Monitor verb.

Probably worth noting that instead of screens being listed it lists Voxen haircuts.

### PR DESCRIPTION
**Pull request by Crazylemon64**
Fixes #2429 

This needs the "Fun Removal" tag

### CODE REVIEW

**Comment by NTSAM** [comment]
Vox now cannot shoot out quills like a hedgehog and regrow them instafast.

rip

**Comment by Spacemanspark** [comment]
Dammit, I never got a chance to do my vox guitarist.

**Comment by NTSAM** [comment]
There's always the next hilarious bug, @Spacemanspark

**Comment by Crazylemon64** [comment]
</3

**Pull request merged**
