### PR TITLE
Me Button

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Functions exactly like the Chat button
cbar
Disregard the OOC button in the pic

:cl:
add: Me button added to chatbar
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I dont see this being useful. OOC is disabled, me can be used by pressing M, and it looks like there are too many buttons there.

**Comment by uraniummeltdown** [comment]
It's mainly for people who don't use hotkey mode. I know OOC is disabled during rounds but it still might be useful when a round ends and the server restarts

**Comment by Citinited** [comment]
> me can be used by pressing M

If you don't use hotkeys then this won't help. IMO the functionality is worth the tiny amount of screenspace it uses up

**Comment by datlo** [comment]
I'd remove the OOC button. You can OOC by using the verb in the OOC tab, and OOC is disabled during round.

**Comment by Tails2091** [comment]
Is there a way to disable/grey out the OOC button while it's not usable?

**Comment by KasparoVy** [comment]
LOOC 👽👌

**Comment by variableundefined** [comment]
@uraniummeltdown Since OOC is barely used, may I request that the OOC button be removed but the me button retained? 

Otherwise this looks good to me.

**Comment by KasparoVy** [comment]
Lmfao, yeah. Back when we had public OOC I'd always hit 'en with the classic

`OOC OOC wa guan spessmen`

**Comment by Birdtalon** [comment]
Yeah replace the OOC button is a good idea. 👍

**Comment by Kyep** [comment]
Maybe "Emote" instead of "Me". New players probably know what "emote" means, but probably not what "me" means.

**Comment by KasparoVy** [comment]
Good call

**Pull request merged**
