### PR TITLE
Adds the Elusive Black crayon

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

This adds the elusive black crayon to the game, allowing everyone and their dog to color anything they want black.
It also adds the white and black crayon to the box of crayons and increases the space of said box.
Oh, and it changed the color of black gloves from brown to black.

## Why It's Good For The Game

The only known method AFIK to color things black is using the HoS stamp as a consumable, or a chameleon stamp turned into a HoS stamp as a consumable

## Images of changes

image

## Changelog
:cl: ppi
add: Add black crayons
tweak: Add white and black crayons to the crayon box
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
Oh god, YES

**Comment by DeveloperLoser** [comment]
yes! no more rushing bar maint for my various costumes

**Comment by Wojz** [comment]
astounding developments in drip theory

**Review by Necaladun — APPROVED** [review]
approve assuming a maint has checked people can't make things basically invisible with it as has rarely happened

**Comment by Djvoid225** [comment]
FINALLY, I DON'T HAVE TO BREAK INTO THE HOS' OFFICE ANY MORE

**Pull request merged**
