### PR TITLE
New Job: Bouncer

### PR DESCRIPTION
**Pull request by Kyep**
- Tosses unruly patrons out of the bar. So the bartender can focus on drinks-making. Can also function as a bouncer for another department that wants him, such as Medical. Member of the service department.
- Starts with: black jumpsuit, armored vest, sunglasses, flash, one pair of zipties.  Does NOT get sec radio access, or a mindshield implant. Does NOT get any kind of gun.
- Access: maint, weapons permit (so beepsky won't bust him for picking up any weapon an assailant drops).
- This job kept coming up as a good potential job, because it is arguably a needed role during highpop, interacts a lot with the rest of the crew, and generally performs a useful service.

🆑 Kyep
rscadd: Adds 'bouncer' job, that Bartender and Medbay can use to keep out ruffians.
/🆑

### CODE REVIEW

**Comment by taukausanake** [comment]
Sounds like an assistant job, but with the requirements to not suck. Some moc SoP rules might help though

**Comment by SheepFighter** [comment]
This sounds like an excuse for valid-hunting, not to mention unnecessary. Barfights aren't much of an issue in my experience. Probably because the folks who would start them are off roaming the hallways in gasmasks.

At the very least, remove the telebaton. The armored vest should suffice for giving him the edge he needs.

**Comment by taukausanake** [comment]
No, no. This isn't a needed job. It IS the bartender's job to make sure the bar is at peace. It's why he has the armored vest and shotgun with nonlethal shots. If you must have a bouncer then it should be an assistant job, not something available at round start

**Comment by Kyep** [comment]
@SheepFighter Removed baton.

**Comment by Necaladun** [comment]
Might be good to have as a karma thing for quality control and 'cause we haven't had a new karma job in awhile

**Comment by taukausanake** [comment]
We really do need more karma jobs I know of one I would like to see but would require a rework of things.

As for Medical bouncer, if we are going to go into department protectors then just make security checkpoints and have a special sec officer positioned there or a rotation thing with normal sec. It makes sure that there is always a security presence somewhere. As it stands the bartender should not depend on someone else to defend his turf, not while he has an armored vest, shotgun, and reason to fire it at rude customers

**Comment by SheepFighter** [comment]
Yeah, Metastation has checkpoints everywhere.

**Comment by Kyep** [comment]
@Crazylemon64 Metastation spawnpoint added.

**Comment by DesolateG** [comment]
I completely disagree with security posted at every department @taukausanake. They shouldn't be EVERYWHERE, otherwise what's the point of attempting to be an antag?

**Comment by SamHPurp** [comment]
I support this, even more so if it was karma-locked, albeit cheaply.

**Comment by tylerh95** [comment]
Everything that makes us more unique helps create a more defined niche for us. +1

**Comment by Iamgoofball** [comment]
Is this guy persuadable?

**Comment by Fox-McCloud** [comment]
Conflicts.

Also you have no pics.

This just comes off as a faff about job that's going to lead to people being a jerk with it. IAA already trends towards this way too often; I don't really think this is going to be any different, especially given that it has less responsibilities and the bartender is far better equipped at dealing with unruly customers than the bouncer is.

You're also going to have people utilize it in the "I'm a super chef/bartender" as well, since he has access to both areas (why does he even need access to the bartender's area or the kitchen, when both jobs have defense mechanisms to keep people out).

Also, this is really security's job to deal with something like this--it's the whole reason the job exists; it's not meant to be fulfilled by a civilian.

**Comment by KingPhilipIII** [comment]
I support the addition of sec checkpoints with holding cells to each department. Decentralize the brig a bit.

They get armbands and basic departmental access. Like TG does.

**Comment by taukausanake** [comment]
No, no holding cells, just a place for a sec officer to make sure no illegal access is gained, basically a doorman, and who can respond to department emergencies quickly. I wouldn't give them department access but then realize that they would be useless without it

**Comment by Kyep** [comment]
@Fox-McCloud 
- Fixed merge conflict
- Added pics, including sechud icon
- Removed bar/kitchen access

With regards to the idea of using security for this... this just never happens. Security doesn't look after the bar, or guard the entry to medbay. They just don't. They always have better things to be doing. The bartender and CMO can guard their areas somewhat, but they shouldn't really have to... and there are plenty of other places a bouncer could be useful, such as the entry to the brig, the HoP line, etc.

**Comment by DesolateG** [comment]
@kyep can the bouncer have the ability (with a cool down) to roundhouse face kick people?

**Comment by Anoonki** [comment]
> roundhouse face kick people

Ghetto krav
bar warden
aaaa

**Comment by DesolateG** [comment]
Roadhouse 8')

**Comment by Kyep** [comment]
@DesolateG He already has a flash. That should be enough to stun most people. I would prefer not to give him martial arts - I want this to play different from warden/sec.

**Comment by DesolateG** [comment]
@kyep roadhouse!

**Comment by DesolateG** [comment]
Be nice, until it's time to stop being nice.

**Comment by scrubmcnoob** [comment]
150 people and like 10 sec personnel.
Yes security should deal with greytide but more of hacking into secure storage. Stupid drunk bar fights doesn't really need an officer when said officer can be doing something else much more important.
Having a dedicated bouncer would be helpful to just deal with average hotheads in the bar.

**Comment by taukausanake** [comment]
I think I see something missing from this bouncer now that I've seen the pictures posted. The bouncer needs to be fat. Bouncers are normally big BIG people. With either muscle or just a large demeanor that is how they keep people out. I'm not saying this is just for appearance though. Fat people can't be pushed and might be a necessity against idiots looking for a fight.
Still don't see this job as needed though

**Comment by DesolateG** [comment]
That's a stereotype. Bouncers come in all sizes. I was a bouncer, 6'3" big guy, but my 5'4" boss guaranteed could take me down in a heartbeat.

**Comment by Necaladun** [comment]
This job, by itself, isn't needed for sure. But I think it can be a fun and useful addition. It gives a guaranteed person for the barman to talk to when things are slow, as well.

The karma locking (10?) I think could make sure it's not just newbies and idiots using it badly or to get powers over other.

SoP and space law stuff will need to be added for it. I selflessly volunteer Tully for that ofc.

**Comment by DesolateG** [comment]
@Necaladun roadhouse?

**Comment by Anoonki** [comment]
How about just giving him krav pin and calling it a day?
Let him get a guy on the floor, pin him, then yell for security until they come over and collect the rowdy nerd.

**Comment by scrubmcnoob** [comment]
Nah it should be tabling and shoving them down disposals. Essentially just able to get rid of rowdy people without needing security.

**Comment by Necaladun** [comment]
Tabling really seems like it should be his signature move.

**Comment by taukausanake** [comment]
That and literally tossing them out through the door

**Comment by jughu** [comment]
Barmaid job when

**Comment by Doukhan** [comment]
@DesolateG au contraire having sec split up across the station can make things a lot easier.
As things are sec tends to move in one contiguous mass from one disturbance to another, when they're posted in in their own little areas sure they respond faster individually but they're also a lot easier to pick off.

**Comment by FlattestGuitar** [comment]
Security is there to stop fights like these. The bartender is already equipped to do that himself if need be.

This job will only promote validhunting or beating people up for no reason.

I really can't see how this will improve the game.

**Comment by jughu** [comment]
I WANT A BARMAID JOB REEE

**Comment by Aurorablade** [comment]
This job like gateway explorer is not needed. i a gree with flat here.

**Comment by Lady-Luck** [comment]
In the days of auto-patching, I don't see why we're so afraid to try things.

**Comment by Draconic-saint** [comment]
Auto patching doesn't mean we should just throw shit at the wall and see what sticks.
Undermines security's authority in my eyes, encouraging people to take matters into their own hands. Not sold on it.

**Comment by Lady-Luck** [comment]
>Auto patching doesn't mean we should just throw shit at the wall and see what sticks.

It's not like this is  unanimously disliked, it's pretty split, so we should give it a shot.

**Comment by Aurorablade** [comment]
that only applys to mechnical code changes, you introduce a job decide it dosen't work and take it away people may or may not be miffed. espicalluy if you have to spend karma.

**Comment by Lady-Luck** [comment]
uh, we have a karma refund system.

**Comment by taukausanake** [comment]
Yeah but that will require a revert and push of some sorts, maybe code, maybe SQL, maybe both. In other words more work to correct a mistake. It would be better to have it not as a karma job first for a while and then switch it up but that brings in a different set of problems for characters that still have bouncer set after it becomes karma locked

**Comment by Lady-Luck** [comment]
We have a metric ton of civilians lacking things to do. We need to be making new jobs, period. Bouncer is one of the best ideas on the table.

**Comment by Kyep** [comment]
I have no intention of karma-locking any job I add. That includes Bouncer.

The way I see it, the primary purpose of these new jobs is to give us more job slots. Karma-locking the jobs so that they're taken much less frequently largely defeats the point of adding them at all.

In addition, should we merge this for a trial run, it will be a lot easier to observe how the job plays, gather feedback about it, and even revert it if needed, if the job isn't a karma job. 

For all of these reasons, I am not making this a karma job, and I'm unlikely to make *any* job I add a karma job.

**Comment by Allfd** [comment]
I don't know that I like where this is heading, not so much the job, but the need for the job.

I don't know if I would like work so much if we needed bouncers to throw random bald people out of places they wandered into off the street.

**Comment by Draconic-saint** [comment]
If you want civilians to have things to do, put more side-activities on station, combined with more actual jobs that need doing.

-Expand on the painting/crayon'ing system. I've played several rounds of Honk Ross, the afro-rocking painting clown. (Which I just realised makes me a bit of a hypocrite on the naming rule, shame on me...) painting supplies are not hard to come by, but not a lot of people use them, and it's not a very intuitive system to use.

- Promote renovation of the tunnels. There's a lot of fun building spots that can serve as neat little hideouts.

There's a few more options but when it comes to bouncer, I don't think getting into fights is a "side-activity" we should be promoting with the greyshirts.

**Comment by Lady-Luck** [comment]
You know, it would be nice if there were a way to make certain jobs only unlock at at a threshold of crew population.

Bouncers sound completely worthless off-peak, but invaluable at high pop.

**Comment by theColdflame** [comment]
an unmonitored assistant with some extra access, a weapon permit, and sec gear?

**Comment by Necaladun** [comment]
Can we put this on a hold until SoP/Space Law etc is written up for it? That'll really determine the problems of valids etc with it.

**Comment by Kyep** [comment]
I'm fine with that - I assumed we'd want some SOP for it anyway.

**Comment by Necaladun** [comment]
Oh also - maybe spawn with a bruise pack ;)

**Comment by Kyep** [comment]
@Necaladun Some people objected to GEs getting a brute pack, despite the fact miners have one, GEs face more dangerous mobs further from medbay, etc. I reasoned that if some objected to GEs having brute packs, they'd definitely object to a bouncer having a brute pack. They can always ask for one from medbay, though. It isn't like medbay is short on brute packs.

**Comment by Allfd** [comment]
Its not a far walk from the bouncers posting to medbay it would seem.

**Comment by jughu** [comment]
Remove the weapon permit if he really gets a weapon he can put in his backpack instead of holding it out in beepskys visibility besides beepsky doesnt even start on checking for weapon authorization

**Comment by Lady-Luck** [comment]
>Remove the weapon permit if he really gets a weapon he can put in his backpack instead of holding it out in beepskys visibility besides beepsky doesnt even start on checking for weapon authorization

Doesn't matter, if you hold it even for a second beepsky will get pissed.

**Comment by taukausanake** [comment]
Just have the bartender pick it up then. He has the permit so should be okay. Just make sure to call Security to get rid of it

**Comment by Vivalas** [comment]
I agree with Lady-Luck, Paradise and SS13 communities in general seem especially wary of trying to change the general equation of things. This seems pretty cool.

**Comment by Fox-McCloud** [comment]
Generally feel this will just create more incentive to validhunt, while not really adding much more in terms of crew interaction or gameplay, especially when the bartender is better equipped to handle unruly patrons.

**Comment by jughu** [comment]
@fox-mccloud now what would you say instead of a bouncer a WAITER to serve the barman/chef pimp up dat bar

**Comment by Kyep** [comment]
@Necaladun @FreeStylaLT @TullyBurnalot I was under the impression this would probably be merged, once SOP/Space Law was written for it?

**Comment by taukausanake** [comment]
@jughu You mean an Assistant? I've kind of wanted to play as a waiter/barmaid but figured no bartender or chef would care enough to manage one. You know, due to the fact it would require more information to be maintained than just "do X for Y" as well as anyone's goal being just "get X as soon as possible so I can go back to doing Y"

**Pull request closed without merging**
