### PR TITLE
Corgi Update

### PR DESCRIPTION
**Pull request by Pewtershmitz**
## What Does This PR Do

Our boy Ian has some new sprites (states) and two animations! 
**_He wasn't changed, only animations added!_**
Nothing else, so clothes need to be updated!

image

## Why It's Good For The Game

New sprites always good, especially for Ian!

## Changelog
:cl:
add: New **sitting, resting** and **death** states. Two animated states for **howling and sleeping.** 
imageadd: Image added

/:cl:

### CODE REVIEW

**Comment by MRgaty** [comment]
I dont like the sprite for the corgi death, is too grotesque, I find the current one better because it is sillier and more cartoony.

**Comment by taukausanake** [comment]
I kind of agree with @MRgaty but I like the work put into it. A+ for effort

**Comment by KasparoVy** [comment]
:( the dead Ian sprite, so sad

**Comment by Cazdon** [comment]
Agreeing with the above, these sprites look wonderful but the current death sprite of a corgi just being upside down version with X's over its eyes is just so appropriate, I wouldn't want that changed.

**Comment by Carthusia** [comment]
Devils advocate: As much as I dislike seeing Ian all dead like that, it DOES give more incentive to lynch the people who DO kill him intentionally, so theres a positive heh

**Comment by ppi13** [comment]
this pr might wanna include changes to Ian's wardrobe, since some of this will visually break em. hats, pet collars, radios, and so on.

**Comment by TDSSS** [comment]
What about puppy Ian, will he still use the old sprite?

**Comment by taukausanake** [comment]
_Please make a murdered puppy Ian, **I want to see it**_

**Comment by Pixelzilla** [comment]
As cute as it is to have additional animations for Ian it does cause some issues since the various clothing/hardsuit/hats/collars will no longer fit him properly when using the altered animations/poses.

Ian is such an iconic sprite for ss13 that changing him is really really not a great idea. We also have Lisa's sprite, Corgi Puppies and Exotic corgis that are left out of this.

As cute as the sprites might be I'm not really keen on adding something that will break longtime (and well liked) features of Ian. Not saying I dont understand the effort involved in making all of the clothing/hats fit and be properly animated in the new states (i absolutely do understand) but I dont like that it is essentially shoving that workload off onto someone else (or in reality, it probably wont get done).

**Comment by Pewtershmitz** [comment]
> I dont like the sprite for the corgi death, is too grotesque, I find the current one better because it is sillier and more cartoony.

> Agreeing with the above, these sprites look wonderful but the current death sprite of a corgi just being upside down version with X's over its eyes is just so appropriate, I wouldn't want that changed.

> :( the dead Ian sprite, so sad

You're right boys, I also prefer the old Ian death sprite. Cartoony is good enough!



>As cute as it is to have additional animations for Ian it does cause some issues since the various clothing/hardsuit/hats/collars will no longer fit him properly when using the altered animations/poses. 

> this pr might wanna include changes to Ian's wardrobe, since some of this will visually break em. hats, pet collars, radios, and so on.

I'm currently working on the corgi_back.dmi, adding sprites to all of his wardrobe. It's a really slow process, with over 180+ sprites just for corgi_back alone. I'm slowly making progress, and have, for example, the walkietalkie to show: https://i.imgur.com/oC64ACG.png




 
> What about puppy Ian, will he still use the old sprite?

> _Please make a murdered puppy Ian, **I want to see it**_

I'm not touching the puppy Ian, or Lisa sprites. Puppy Ian is way too small, and my main focus is on Ian right now.


Thank you all for your feedback! I'll let you know when I have the clothes ready!

**Comment by Fox-McCloud** [comment]
Not really a big fan of these sprites, at all.

👎

**Comment by variableundefined** [comment]
The sprites for the corgi death and sleeping seems to not match with current animals sprites style. 

The sleeping and death sprites feel like they have much more depth, shading and 3Dness to it, which is generally a good thing for sprite, but is jarring in comparison with how things are portrayed in sprites Para wise.

**Comment by Fox-McCloud** [comment]
Merge conflicts. 

I'm still not a fan of these--if you want to continue this, solve the conflicts--if there's no reply in a week, this will be closed.

**Comment by Fox-McCloud** [comment]
no response. Closing.

**Pull request closed without merging**
