### PR TITLE
Expands MetaStation Maintenance

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Expands the maintenance tunnels on MetaStation, done via reshuffling the existing rooms where possible, as well as the chapel/escape and engineering by 1-2 tiles. To fill some of the gaps made, added some maintenance rooms.

Please note that there will still be 1 tile wide maintenance tunnels on the map, however they are now the minority instead of the majority as lots of the tunnels don't actually connect and more or less weave between pre-established departments.

In addition, if there are any areas that need an obvious change or can be improved from what is provided, please comment it as this is really my first time redesigning a major station component.

## Why It's Good For The Game
One of the major gripes with MetaStation is that it's maintenance is significantly narrow. By doing this expansion, I'm hoping to bring it more in line as best as I can.

## Images of changes
 Go view MapDiffBot.

## Changelog
:cl:
tweak: Expands MetaStation maintenance tunnels
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
There are other things I need to do with Meta still, like adding in a magistrate's office somewhere somehow, same with science chemistry... but it's a start.

**Comment by procdrone** [comment]
By courtesy of aa07

before: https://mdb.affectedarc07.co.uk/Files/27286452/5714968101/0/before.png
after: https://mdb.affectedarc07.co.uk/Files/27286452/5714968101/0/after.png

**Comment by LightFire53** [comment]
> By courtesy of aa07
> 
> before: https://mdb.affectedarc07.co.uk/Files/27286452/5714968101/0/before.png after: https://mdb.affectedarc07.co.uk/Files/27286452/5714968101/0/after.png

Yes, those are the MapDiffBot images I referred to. You can find it under the checks section 🤪

**Comment by S34NW** [comment]
currently away on business trip. Will thoroughly review upon return ;)

**Comment by S34NW** [comment]
Right, be prepared for some image spam, I am going to include issues not of your doing, but should be fixed while you are there:

image
cobweb looks weird when not in a corner, scrubber over vent pipe, reinforced window spawner over a wall.

image
this feels a bit barren, maybe add a fire closet or some fluff?

image
this is all var edited to say port maintenance, when there is a port maintenance area already present, also the lines between them are not logical.

image
missing power cable

image
this bit of space is labelled chapel

image
these misaligned windows

image
these are classed as nearspace but nothing is there

image
this needs to be nearspace

image
this needs to be space

image
this is all labelled "port maint" by var edit, it should use the proper area object

image
scrubber over a pipe

image
this section feels a bit devoid of life/character. Consider adding dirt/posters, etc?

image
same here, feels like a loot room that sec/detective will immediately rush, not much character to it

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
