### PR TITLE
Make stunprods bulky

### PR DESCRIPTION
**Pull request by Couls**
## What Does This PR Do

This makes ghetto stunbatons, the stunprods into bulky objects.
## Why It's Good For The Game

I don't think the ghetto version of a stunbaton should be so easily concealable. The case with security is that you can easily assume they have a stunbaton but you can't assume any crew member has a stunprod. I don't think these instant stun items should be so easy to hide and remove on a whim and if you're planning to use a stunprod you'll need to accept the risk of being openly visible or attempt to get an upgrade to a stunbaton or use a bag of holding. Stunprods barely have a downside in comparison to stunbatons especially when you pair them with a yellow cell. The stun for stunprods only last 4 seconds less than a stunbaton and that's more than enough time to cuff or do whatever nefarious deeds. I think it would be better to make an item that is so easily available(0 TC, uses things that can be mass produced out of an autolathe excluding the high cap cell that you can get from science) have a downside

## Changelog
:cl:
balance: stunprods are now bulky and will not fit in bags
/:cl:

### CODE REVIEW

**Comment by Mocha-Not-Latte** [comment]
iTsAfeaTuRe REeeEeeeeeeerRreeeee

**Comment by Couls** [comment]
> iTsAfeaTuRe REeeEeeeeeeerRreeeee

Not a major feature or refactor REEEEE and I talked with ansari about it before they went to dinner

**Comment by FlattestGuitar** [comment]
image

**Comment by Arkatos1** [comment]
I would be personally in favor of this, but only if the stun rework gets merged first.

**Comment by Couls** [comment]
I feel like the issue is actually made worse by not actually having the stun rework. having an basically invisible stun weapon that only appears after you're hit by it? Kinda lame.

**Comment by AzuleUtama** [comment]
Stunprods right now are effectively just batons that use double power which you can make with 4 very easy to find items. You can conceal them easily and surprise attack anyone with no effort, so removing the ability the keep them so easily hidden like TG have done seems perfectly logical and doesn't nerf the actual power of it.
Antagonists have access to other weapons or powers for stunning (except maybe cling), so I don't see this harming their usability. The only people that are really going to be affected the worst are those without a real reason to be making them in the first place (non-antags / non-sec).

**Comment by KasparoVy** [comment]
You can still have them mostly assembled in-bag and complete the final steps in the event trouble comes anyway, jutsllike spears

**Comment by MRgaty** [comment]
I dislike this, as it also affects antags.
Even if you can use other resources, are you always gonna have tc for a stun?
Are you always gonna have paper for a talisman?
What do you use as cling instead.
What do you use as vampire instead.
This is going to heavily nerf one of the antags most basic ways to get a weapon.

**Comment by Couls** [comment]
> I dislike this, as it also affects antags.
> Even if you can use other resources, are you always gonna have tc for a stun?
> Are you always gonna have paper for a talisman?
> What do you use as cling instead.
> What do you use as vampire instead.
> This is going to heavily nerf one of the antags most basic ways to get a weapon.

Maybe it's time for antags to find better ways to get weapons? It's not like every antag is just crew and even then, crew is pretty powerful. I'd prefer antags to think outside of the box instead of making such an easily acquirable item. Plus like you said you're not always gonna have these things. but stunprods are a constant and they're so easy to make you can always have one on you, you can always have an item on you that basically means you win every one and one engagement you start. I really think it'd be better if antags got more creative with acquiring weapons instead of falling back to the one constant that's always there.

**Comment by Mitchs98** [comment]
Kind of against this. Just as I'm against the ranged stun rework. While it's not really removing the item it is making it a decently pointless thing to use or make without a bag of holding. Personally I feel its fine how it is. Same as how I feel ranged stuns are fine how they are, and disarms, and nearly every aspect of combat. "TG did it so it's a good change." Doesn't sit well with me.

Nor does making it so people have to go through extra hoops to 1. Get a decent method of non-lethally subduing people as an antag. 2. Make it even remotely feasible for thralls to be able to capture people for shadowlings without Shadowlings getting super lucky and getting an officer/scientist with BOH. Or 3. Crew to get a means of self defense. 

The whole "Non-antags/non-sec not having a valid reason to make them." isn't really always valid. There are many instances in where non-sec need to make them antag or no, it all depends on context. I see absolutely no reason to change it.

I get the gist of WHY you want it to be changed, and on one side of the 'idedplsnerf' spectrum understand why it's a good idea. No one likes getting randomly prodded and dragged off to who knows what. But at the same time, things happen.

**Comment by Fox-McCloud** [comment]
On one hand, it'll probably cut down a bit on validhunting and surprise batons...at least in some regards.

On the other, I do like high levels of paranoia in SS13.

**Comment by Fox-McCloud** [comment]
You need to make this a back item if you're going to do this, and put those sprites in.

**Comment by datlo** [comment]
Unless I am mistaken with this change the stunprod will still fit on sec armor and subtypes (the same way riot shotguns do). That is IMO good because it lets you store the item without hiding it, but its something you should be aware of balance-wise.

Please make it fit on back slot and add a back sprite for it, and I think I would be okay with this change.

**Comment by Krysonism** [comment]
/tg/ has a stun prod back sprite. One of the strongest weapons in the game should not be able to be obtained with no effort.

A bulky stun prod is still useful for surprising people in maint or sneaking up to people before they can see the stun prod strap on your sprite.

Being able to pull a prod from your bag and one hit win anyone with no counterplay is bad.

**Comment by Couls** [comment]
> You need to make this a back item if you're going to do this, and put those sprites in.

Already a back item and already has those sprites

**Comment by Rurik123** [comment]
Should be noted that shadowlings will be hit the hardest by this, since pretty much the only effectiveness of non-sec thralls is their ability to surprise stun & cuff you with a stunprod. 

It won't be that big of a deal for traitor, cling and vampire though. Hell, it could be considered a benefit for them since they won't have to deal with their victims pulling out a surprise stunprod either.

**Comment by Denthamos** [comment]
Antags should be relying more upon their abilities and the gear they get from their status.  The current stun prod is a universal win button that currently anyone antag of valider can use and hide at will.

Time to get more tactical with how you handle things instead of relying upon the prod.

**Comment by SteelSlayer** [comment]
It absolutely is a big deal for traitor and changeling. The only reliable instant stun item traitors can buy is the mini ebow and it costs **12 TC**. And as for changeling, they don't even get a stunning tool in their kit. Don't say armblade either because the knockdown is RNG. Tentacle doesn't stun, only puts people into a grab which they can resist out of by holding a movement key.

Yes, traitors is slightly less affected by this nerf because they can buy the ebow, but changelings and, as Rurik mentioned, shadowling thralls are still pretty screwed. We need some other melee stunning tool that these antags buy with TC/unlock with evolution points to compensate for the fact that stunprods are basically worthless now and will instantly broadcast that you're a bad guy

**Comment by Fox-McCloud** [comment]
Might I suggest, then, as a token piece of compensation, the ability to craft the teleprod?

**Comment by Rurik123** [comment]
@SteelSlayer If your looking at it purely from what instant/reliable stun options are available, this does affect them heavily, but you also have to take into account context. Traitors, since they only have one objective now, don't even really need a stun to accomplish anything outside of hijack. Targets are pretty easily killed through the variety of other lethal means, and if ya really need a stun before going in to lethal, soap works just as well assuming your not already known as a danger to them. 

For an officer as a target, slip and apply two stechkin mags to the face. If you're worried about him getting your name out, have your ID off and a gas mask on when you strike. If they don't have a helmet, you can just crack them over ahead with a bottle which also acts a stun, then lethal. Or emp the arrivals checkpoint locker for a free baton. And for stealth objectives, stuns were never necessary. Hell half the time you could do those without an emag unless the Captain was _that _guy__ and hordes his gun, hand tele and medal box. 

For changelings, what they lack in the instant stun department is made up in utility via eliminating stuns, using meth speed run to escape engagements, ability to go invisible and the infamous mute sting cheese of killing someone without them even being able to speak. It should be noted as well the tentacle arm, besides just disarming sec for their tazers, can instantly put you into an aggressive grab which you can immediately upgrade into a chokehold which makes them drop their held item and gives them a decent stun if they manage to resist out (5% chance iirc? or maybe that was just for using the garote?). Changelings, unlike traitors, can also just kill a sec member for their equipment. And if you feel bad about killing them, just take what stuns you need and drag them back to medbay.

I get where you're coming from though, It just won't be that game-changing for the golden three, imo. Slings on the other hand...

If this were to merged, I'd almost feel like thralls need their baby 3 sec glare back. Almost.

**Comment by Fox-McCloud** [comment]
#bringstunglovesback

**Comment by Couls** [comment]
sling thralls have numbers and the _ability_ to communicate silently, their strength is in numbers and they can all still use stunprods and prowl maints, or not prowl maints. the only downside is that it would just be more obvious who's a thrall or not but stealth is still a very viable option for them, sure it'll be a nerf but shadowlings almost always snowball anyway so this might make it a bit easier to turn it around for crew and it also helps fight the "let me get thralled so I can run around and stunprod people" mentality I see with people immediately running into maints when shadowlings are announced

**Comment by variableundefined** [comment]
Closing due to two heads objection as this did not work out well in Para's history.

**Pull request closed without merging**
