### PR TITLE
Get max 1 power from the DNA vaults

### PR DESCRIPTION
**Pull request by farie82**
## What Does This PR Do
Limits the amount of powers you get from multiple DNA vaults to 1.
Adds UI to notify the user that they have already selected a power

Fixes: #14955

## Why It's Good For The Game
The DNA vault powers are "balanced" in a way that a player can only really have one max in a round. Having more will break balance big time for antags and security alike. However fun it could be

## Images of changes
image

## Changelog
:cl:
tweak: A player can have up to 1 power from the DNA vaults now. Making more will not add powers to choose from
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
Does multiple dna vaults still give you more options to choose from? So you can only get one power, but putting in the effort to build another vault will give more to choose from for that single power?

**Comment by farie82** [comment]
> Does multiple dna vaults still give you more options to choose from? So you can only get one power, but putting in the effort to build another vault will give more to choose from for that single power?

It won't. You get one set of powers to pick from per round

**Comment by Butlerblock** [comment]
"The DNA vault powers are "balanced" in having one max" DNA vaults aren't balanced regardless so honestly, the powers themselves should be balanced before anything else because they're EXTREMELY overtuned.

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]
An end to this meme

**Pull request merged**
