### PR TITLE
Gives the Mime a baguette

### PR DESCRIPTION
**Pull request by Coolrune206**
## What Does This PR Do

I believe this may be my most controversial PR yet, but I believe the Mime requires a baguette, so I have given them one round-start.
## Why It's Good For The Game

Hon hon hon, je mange le pain.
## Images
image

## Testing

It's just bread, but it works 👍 
## Changelog
:cl:
tweak: Le mime a une baguette
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
hon hon baguette

**Comment by Gatchapod** [comment]
We have removed infinite crayons so mimes and clowns do not get roundstart infinite sustenance.
However clowns start with a banana and a banana pie, while mimes start with nothing.
I am not sure if baguette is a nutritional equivalent of these two foodstuffs, but it is a step in the right direction, balance-wise.
Perhaps we should consider adding a cheese wedge to the mime office?

**Comment by Henri215** [comment]
> We have removed infinite crayons so mimes and clowns do not get roundstart infinite sustenance. However clowns start with a banana and a banana pie, while mimes start with nothing. I am not sure if baguette is a nutritional equivalent of these two foodstuffs, but it is a step in the right direction, balance-wise. Perhaps we should consider adding a cheese wedge to the mime office?

Mimes got infinite food already, its just that most of them are too lazy to mime one.

**Comment by hal9000PR** [comment]
1 design team objection and nobody in favour after a month

**Comment by Coolrune206** [comment]
image

**Pull request closed without merging**
