### PR TITLE
Atmos Update 'Charles' DPV Deletion

### PR DESCRIPTION
**Pull request by RangerYote**
## What Does This PR Do

Removes Dual Port Vents

## Why It's Good For The Game

Dual Port vents currently serve no purpouse. They were previously designed to work with the AAC which is long since removed. Their purpouse to save space is made redundant by the fact that you can stack scrubbers and unary vents on top of one another. Bloat is bad.

## Testing

Checked on a local server to make sure they were removed. Tried to spawn in dual port vent using an RPD and it was not in the menu.

## Changelog
:cl:
del: Removes Dual Vent Pumps from RPDs
/:cl:

### CODE REVIEW

**Review by Henri215 — CHANGES_REQUESTED** [review]
Remmoved the ```dual-port vent``` sprite that is inside ```pipe-item.dmi``` and remove the following mention.
image

**Review by S34NW — APPROVED** [review]

**Review by S34NW — CHANGES_REQUESTED** [review]
Please see the above review that needs addressing

**Comment by RangerYote** [comment]
Deleted the pipe icon, found the reference to dual port vents in the RPD asset and removed it.

**Review by Henri215 — APPROVED** [review]
Lewcs good to men now

**Review by Burzah — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
