### PR TITLE
Adds blast door button next to secure storage

### PR DESCRIPTION
**Pull request by Citinited**
What it says on the tin - adds a blast door button next to secure storage in engineering. Change made because the AI / engineers / CE never seem seem to know where the specific button is, or usually press the wrong one.

The access on the button is Chief Engineer+

image

:cl:
tweak: There's a button next to secure storage's blast doors now.
/:cl:

### CODE REVIEW

**Comment by datlo** [comment]
Chief engineer access only, as it is (effectively) now please. If an engineer really absolutely needs in, he can turn off equipment on the APC and crowbar them open.

Other than that sure, i agree with adding the button

**Comment by Rurik123** [comment]
rip the days of breaking in the CE's office to press the button when CE is non-responsive.

**Comment by Citinited** [comment]
Actually on reflection I am gonna make it CE+ so engineers do have to break in to the CE's office if they want access to the secure storage, but allows for easy button access for AIs / authorised crewmembers

**Comment by Rurik123** [comment]
Ah good, I liked having an excuse to break into my boss's office

**Comment by FalseIncarnate** [comment]
Provides an obvious way to open the door but retains the secure nature of doing so? :+1:

**Comment by AffectedArc07** [comment]
Can we make the access regular engineer? I mean normal engineers already have access if they hack in, like they can press the button

**Comment by Citinited** [comment]
It was originally like that but I changed it on reflection so it retains its "secure" status. If you need to you can still break into your boss' office (and potentially face criminal charges for doing so)

**Pull request merged**
