### PR TITLE
Brooms, Stick-horses, and Flying Wizards!

### PR DESCRIPTION
**Pull request by FalseIncarnate**
A port of https://github.com/d3athrow/vgstation13/pull/4377

image

Allows brooms to be wielded with 2-hands. Doing so places the broom
between your legs so you look like you are riding it.

You can also put a horsehead mask onto the broom to create a stick-horse
to ride. This can also be wielded, but will ALWAYS appear between your
legs.

And for the more magically inclined, wielding a broom or stick-horse (2
hands!) will cause you to ride it like a witch, giving you the ability
to bypass hazards such as tables and banana peels.

### CODE REVIEW

**Comment by Keilden** [comment]
Nice! Now all we need is flying monkey minions for wizard and we can have the wicked witch.

**Comment by Spacemanspark** [comment]
We can play space Quiddich now.

**Comment by ZomgPonies** [comment]
Talk to me about horse head masks. Do we have a version that's not unremovable? Gotta put one somewhere on station so they can add to to the broom and pretend they're knights. Add some cardborg armor and call yourself Sir Bolts-A-Lot

**Comment by FalseIncarnate** [comment]
@Zomgponies

The horsemask is removable by default. The curse just adds a NODROP flag and a couple other tweaks to it, rather than a separate type (probably should use a new subtype like /magic), so they are harmless by default.

There are none on map/obtainable to my knowledge, but we could add them to a machine/map/cargo easily enough once we decide where/how to do so.

We can discuss that part later after I am done at work

**Comment by ZomgPonies** [comment]
Bah just add one to the costume vendor and call it a day.

**Comment by Keilden** [comment]
One? but then we cant have people joust!! We need two

**Comment by ZomgPonies** [comment]
Fine, two. Whatever! The point was that we didn't need to make it fancy.

Also, it can be added to the cargo costume hat crate or something.

**Comment by Spacemanspark** [comment]
Why not thirty, we need to be able to PROPERLY play space Quidditch.

**Comment by Robertha89** [comment]
make it unaffected by space and gravity, so you can actually drive about in space.

**Comment by FalseIncarnate** [comment]
@Zomgponies
I'll add them to the crates and vendors later tonight, DNM until that's in.

@Spacemanspark
You'd need to get more brooms for that anyways, so you'd be going through cargo for stuff already. I might add a new crate of brooms and horse heads and maybe a beach ball for some space polo action

@Robertha89
I need to check, but I believe wizards are immune to gravity and can move freely while flying on brooms. I'll report on that later, but the broom won't protect against the vacuum of space so they need to be properly equipped

**Comment by Spacemanspark** [comment]
I was mainly making a joke.
Though Space Quidditch would be pretty damn neat.

**Comment by ZomgPonies** [comment]
DNM until he gets the rest of his bits in.

**Comment by Robertha89** [comment]
@FalseIncarnate that is good, and i assumed you would need a suit to use it in space unless you are a diona or vox or plasma man.

**Comment by FalseIncarnate** [comment]
Adds 2 Horsemasks to the AutoDrobe's hacked items list.

Adds 2 new crates to cargo: Team Jerseys Crate and Polo Supply Crate.
- Team Jerseys Crate (15 supply points) contains 4 red jerseys, 4 blue
jerseys, and 1 beach ball
- Polo Supply Crate (20 supply points) contains 6 brooms, 6 horse masks
(to put on the brooms), and 1 beach ball

Adds new jerseys: an alternative to athletic shorts that come in red and
blue. Red team is the NT Phi-ghters, Blue is the NT Pi-rates. Show your
team spirit today!

image

**Pull request merged**
