### PR TITLE
Ports /TG/ shotgun inhand sprites, adds custom ones

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Ports in-hand sprites for: Shotgun, double barrel shotgun, improvised shotgun, sawn-off improvised shotgun, slung improvised shotgun, combat shotgun (with edits for shells and a new stock).
'Created' (scuffed) new sprites for: Riot shotgun, assault shotgun.

Fixed inconsistencies in gun icons, they all point right now (some shotguns, pistols and the tommy gun were randomly flipped)

## Why It's Good For The Game
All shotguns currently look like the same twig.
Twig guns bad.
This change lets people see at a glance what manner of slug delivery system is running straight for them.

## Images of changes
I assembled 24 naked men to showcase these at various angles for you. Not shown are sawn-off improvised shotgun and slung improvised shotgun. 

Untitled-2

## Changelog
:cl:
add: Added unique in-hand shotgun sprites for all shotguns
tweak: Gun icons now all point consistently to the right
/:cl:

### CODE REVIEW

**Comment by Pyrodes** [comment]
Gonna miss the downward-facing shotguns, but this is definitely an improvement.

**Comment by Stokes52** [comment]
Big fan of the new in-hand sprites, very nice!

**Comment by Cocacolagua** [comment]
There should probably be a different sprite when holding the shotgun two-handed

**Comment by S34NW** [comment]
> 
> 
> ~There should probably be a different sprite when holding the shotgun two-handed~
> 
> Nevermind, brain bad :trollface:

While I agree that shotguns should be wielded items, like some melee ones, that _is_ out of scope for this PR

**Review by dearmochi — APPROVED** [review]
I love you

**Comment by Fox-McCloud** [comment]
TG Spritefication will continue until pixels improve.

**Pull request merged**
