### PR TITLE
ORM points are now claimed by swiping IDs rather than inserting it

### PR DESCRIPTION
**Pull request by Arthri**
## What Does This PR Do
- Removed all ID insert-related code from `machine_redemption.dm`.
- Removed "ID card", "Current Mining Points", and "Total Mining Points" from the ORM UI.
- Moved claim points from `ui_act` to `attackby`. Points are now claimed by swiping an ID over the ORM.

## Why It's Good For The Game
This PR removes an unnecessarily complex workflow. The ORM uses an inserted ID for three purposes:
1. to display the current mining points associated with the inserted ID,
1. to display the total points accumulated by the inserted ID,
1. to check the access of the inserted ID before points can be claimed.

For points 1 and 2, the same can be achieved by flashing the ID(using it in hand), both statistics are also displayed when points are claimed. For point 3, the check has been moved to check the access on swipe. In conclusion, there is not much lost by simplifying this mechanic down to a swipe. It also helps to prevent miners from forgetting their IDs inside the ORM.

## Testing
- Opened the ORM and checked that the section where IDs would be at is gone(leaving only Unclaimed Points).
- Spawned some ore and swiped an ID card over the ORM, then checked that the ID has indeed gained points.

## Changelog
:cl: cdui
tweak: IDs can no longer be inserted into ORMs
tweak: ORM points are now claimed by swiping an ID on it
/:cl:

### CODE REVIEW

**Comment by warriorstar-orion** [comment]
@Arthri I'm not sure this is working properly. When I tested it locally, I put some ore in the ORM, tried tapping the ORM with my ID card, and got the message that the ORM wouldn't accept my card. I tapped it again and got "There are no points to claim". Then I tried touching the ORM with my other empty hand, and the points transferred to my ID.

Based on the code it looks like touching the ORM with the ID is what should transfer the points.

**Comment by warriorstar-orion** [comment]
@Arthri could you make it so that the UI updates once the points are claimed?



Also, on line 356, `add_fingerprint` gets called at the end of all the actions which are expected to be physical interactions with the ORM. Should it also add fingerprints in this case?

**Review by warriorstar-orion — APPROVED** [review]
LGTM

**Review by S34NW — APPROVED** [review]

**Comment by S34NW** [comment]
!merge_upstream

**Pull request merged**
