### PR TITLE
(TG Port) Recolors the circuit boards into department-based colors

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Port from https://github.com/tgstation/tgstation/pull/44738
Adds 8 new icons for circuit boards, based on department colors.

## Why It's Good For The Game

Department colored circuit boards are easier to identify and its pretty to the eyes.
## Images of changes

colored_board

## Testing

- Compiled and looked into some circuit boards
## Changelog
:cl: Henri237, blargety, Onule
imageadd: Adds 8 new icons for circuit boards, based on department colors
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
circuits visually distinguishable, looking good

**Comment by procdrone** [comment]
thats actually amazing

**Review by S34NW — APPROVED** [review]

**Comment by Sirryan2002** [comment]
I saw you added a base generic green sprite for circuit boards, is the old sprite still in use anywhere?

**Comment by Henri215** [comment]
> I saw you added a base generic green sprite for circuit boards, is the old sprite still in use anywhere?

Its being used by the smartfridge and vending machines circuit boards.

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
