### PR TITLE
Makes Circuit Imprinter Metal Compatible

### PR DESCRIPTION
**Pull request by granodd**
What it says on the tin. Allows the circuit imprinter to now be fed/spit back out metal for designs that require metal.

:cl:granodd
add: circuit imprinter is now compatible with metal
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
Is there any circuits that need metal?

**Comment by granodd** [comment]
There's three, which are the network cards for computers.

**Comment by Fox-McCloud** [comment]
Don't support the old methodology of doing this; you need to utilize the materials datum.

**Comment by granodd** [comment]
Could you elaborate on what you mean by this @Fox-McCloud ? I ask seeing as I just used what was there, unless what you're trying to imply is all this code needs a refactor to utilize the materials datum. What would be an example of the materials datum, also?

**Comment by Fox-McCloud** [comment]
Anything that holds materials of any kind utilizes a materials datum (ORM, Protolathe, autolathe, crusher, etc); this is an exception---continuing to support a legacy system isn't in the codebase's best interest; we need to utilize the materials datum for this, not add to a dead-end legacy system.

**Comment by granodd** [comment]
Attempted to fiddle around with material datums and the circuit imprinter, though sadly that's something that's personally out of my reach. I'll leave that for anyone else who's a bit more savvy than I am, while in the meantime attempting to remove the metal requirements for the network cards, seeing as they're the only three things in the imprinter that use metal.

**Pull request closed without merging**
