### PR TITLE
TG sprite project: Vendors and Consoles.

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR ports TG vendors and consoles, and resprites para-unique ones to fit the style (I.E. changs, petvend).
This also means consoles will be directional in future, upon a further mapping PR for such.
Also fixes botany machines, the PA iconset, and mining machinery (ORM, points console, etc.)

Yes, dogs was working on his own consoles, but that is a WIP with no updates in 3 months. He can replace these with his when he is done.

## Why It's Good For The Game
Our sprites are old, outdated, and crusty. This is another step towards modernising our look.

## Images of changes (these images are liable to be out of date due to small fix commits)
Vendor and select console previews:
2021-08-18 14_38_31-Paradise Station 13

Console previews:
image

Video to showcase animations:

https://user-images.githubusercontent.com/12197162/129908775-e5ce48d4-622e-475b-8af4-fe81eded8f7d.mp4

2021-08-21 18_29_01-Paradise Station 13
2021-08-21 18_28_45-Paradise Station 13

## Changelog
:cl:
add: Added directional sprites to consoles
tweak: Tweaked vendor and console sprites to be TG style and perspective
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
>Our sprites are old, outdated, and crusty. This is another step towards modernising our look.

This is a matter of perspective. Do we really need to look like a pop up book?

**Comment by S34NW** [comment]
> 
> 
> > Our sprites are old, outdated, and crusty. This is another step towards modernising our look.
> 
> This is a matter of perspective. Do we really need to look like a pop up book?

This decision was already made by maints, they said we are moving to 3/4ths perspective like it or not. See: RND machines.

**Comment by Spacemanspark** [comment]
So be it, then.

**Comment by Mitchs98** [comment]
> but it's something that looks better and everyone will be used to it in the span of maybe five rounds.

This is more of a matter of opinion, I personally don't think that 3/4th is fully better overall. It's not objectively better by any means either. It's not exactly something that'll make me quit the server but I really think overall 3/4th is worse than what we have, 'modernized' or not.

That said I actually kind of like these particular sprites better. I definitely didn't like the 3/4th walls and such that I saw in the past, but these are actually fairly nice.

**Comment by DeveloperLoser** [comment]
I know that our opinion has no weight or meaning but may as well state it.

Directional sprites are great, 3/4 is meh, no real advantage and I see it as change for the sake of change. Porting TG sprites is just... Why? Were our own damn server and I as well as others love that we have our own(ish) sprites that reflect that.

**Comment by Spacemanspark** [comment]
Oh lord, this means that the booze-o-mat isn't going to look nice when set directly into a wall anymore, I just realized.

**Review by Kyep — COMMENTED** [review]
Yeah... sorry, I just don't like how these consoles look.
There's something about them I just don't like.
Maybe the perspective.

**Comment by S34NW** [comment]
At the request of a head, the front-on sprites are now less "chunky".

image

image

**Comment by Necaladun** [comment]
Dechonkification complete, approved.

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
