### PR TITLE
DNM Mining outpost major mapchange

### PR DESCRIPTION
**Pull request by M3hillus**
Adds a Mechbay, Break room, Fixes some lighting issues, changes some of the disposals, removes most of the belts, removes smelter.

updated map

### CODE REVIEW

**Comment by tigercat2000** [comment]
Merge conflicts in less than ten minutes? Impressive.

**Comment by M3hillus** [comment]
Right? I'm totally bad at Github.

**Comment by Fox-McCloud** [comment]
Fire doors over the top of regular doors--a no no for mapping.

Also, where does that second pipe come in from? Most of the disposals are meant to route to the mining smelter and not..actually meant to disposal stuff.

**Comment by M3hillus** [comment]
I changed all the outlets to bins and rerouted it to dispose of the trash. As for the Fire doors, I was just following the status-quo on the outpost already, but, I'm likely going to have to redo all of this, so I'll keep that in mind.

**Comment by tigercat2000** [comment]
Um, wait, what? Fire doors over the top of regular doors.. that's.. uh.. kindof the standard..

**Comment by Markolie** [comment]
Fire doors go below regular doors, otherwise the door can disappear when it opens. I fixed it on Z5 during the intercom fixes which is probably why this is conflicting.

**Comment by tigercat2000** [comment]
Physical position on the map shouldn't matter, something more is wrong if it is having any effect on a bug. BYOND layers based on the layer var, not on position in the map stack.

**Comment by Markolie** [comment]
It does matter though, just like how having a metal sheet on top of a glass sheet on the map will hide the glass sheet in-game until you pick up the metal.

**Comment by TheDZD** [comment]
Merge conflicts.

**Comment by M3hillus** [comment]
Working on it, should be done within an hour or two.

**Comment by M3hillus** [comment]
@Fox-McCloud @TheDZD @Markolie In regards to the disposals situation, would it be better to make a trash compactor type room, or add a staging area for the minerals that someone might send down the tubes, instead of changing all the disposals on the asteroid?

**Comment by Taaketa** [comment]
Can the disposals not be used as rapid transit from section of the asteroid to another? From the main station to North station and West station for instance?

**Comment by M3hillus** [comment]
They could, would involve some wall cutting and/or window smashing. Updated map changes will be posted soon, as soon as I figure out how to manage my damn branches.

**Comment by M3hillus** [comment]
I accidentally a button.

**Comment by M3hillus** [comment]
The dream is not dead, this will get done.

**Pull request closed without merging**
