### PR TITLE
Updates Revolution

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the Revolution game mode, from TG.

Yes, yes, I know "revolution is bad'. Well, that doesn't mean we can't attempt to improve it (and there are some people who do legitimately enjoy the mode)--likewise, it doesn't necessarily mean it'll be back in rotation (after all, we do have downstreams, some of which are lighter RP that would enjoy this), but if it is ever re-added, it'll be a lot better, and it'll be an improved experience when it is (rarely) forced.

Changes

- Total rev heads scale with the population, instead of always being three
- Late joining Head of Staff are added to the kill list and are required to be killed if they latejoin (as opposed to who was in when the round started)
 - Removed the other "additional heads" thing, as this was meant to be a compensatory thing for high-pop rev when late-joining heads were not being added
- If there's only 1 rev head and a ton more people join, newcomers roll for the potential to be a rev head
- Rev heads now start with a flash, spraycan, and chameleon sec hud
 - Chameleon sec hud is basically a pair of sec sunglasses that can be disguised to look like a number of station glasses (or Gar glasses...if you want to be a doof)

Related
- Removes RP Revolution
 - This has been played a total number of, IIRC, 3 times in Paradise's history. 

:cl: Fox McCloud
tweak: Updates Revolution game mode so it better scales with total player population
tweak: Head revs start off with a flash, spraycan, and chameleon security HUD
add: Add chameleon security hud, which is basically sec shades with the ability to disguise as a number of regular glasses
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
> Removes RP Revolution
Muh goofy roundtype maymays

**Comment by CrAzYPiLoT-SS13** [comment]
What the fuck even is RP Revolution? :+1:

**Comment by Fox-McCloud** [comment]
>What the fuck even is RP Revolution? :+1:

Walk up to them, ask them to join with a dumb prompt, hope they accidentally click yes and get tricked by it--congrats, successful Rev on your side!

Or....walk up to someone, ask them to join, they say no, immediately yell over radio that there's revs that tried to get you to join and you said no---round ends 5 minutes later.

**Comment by CrAzYPiLoT-SS13** [comment]
That's..uh, I don't even know what that is. Glad to see it gone.

**Comment by FlattestGuitar** [comment]
How about making Rev about something else than indiscriminately murdering people you RP with on normal rounds? 

I dunno, just throwing *wild* ideas out.

**Comment by Fox-McCloud** [comment]
>How about making Rev about something else

That's like asking for nuke ops to be something other than indiscriminately killing everyone and blowing up the station.

**Comment by FlattestGuitar** [comment]
How about taking away a head's ID or handcuffing them counting as them being 'taken care of'? Will add a non-lethal option for people who don't want to murderbone. 

Also, I think Brig Phys should be added to the list of people impossible to convert. Only job with brig access that's not on there so far.

**Comment by Fox-McCloud** [comment]
>How about taking away a head's ID or handcuffing them counting as them being 'taken care of'? Will add a non-lethal option for people who don't want to murderbone. 

You've always been able to do this by forcing them off station.

>Also, I think Brig Phys should be added to the list of people impossible to convert. Only job with brig access that's not on there so far. 

He has a loyalty implant at round-start.

**Comment by theColdflame** [comment]
off z-level rev targets are already considered dead

exiling them to the asteroid/gateway is an option already

**Comment by FlattestGuitar** [comment]
Seems like a lot of hassle. Just cuffing a head will be faster and having the option will discourage the murderbone. I was under the impression that Paradise aims to be a more RPy and that would certainly help. Plus, it will discourage a Captain from running around as an Unknown in a plague doctor's mask. 

As for the Brig Phys, all of security and command are impossible to convert, why does the Phys not get the same treatment? Just seems weird to me.

**Comment by Spacemanspark** [comment]
Ya, rev is pretty eh. Murderboning is garbage.
That said, this PR is alright.
:+1:

**Comment by theColdflame** [comment]
if heads are valid people will kill them regardless, no need to add cuffing them as an option to end the game without actually taking over (for example, combat-cuffing the last head whilst they still have people fighting for them).

**Comment by KasparoVy** [comment]
Huge kudos to you for your work on this! I've mixed feelings on Rev, but I definitely see its merits and I'm sure that the effort put into improving it will pay off.

**Comment by Earthdivine** [comment]
You also forgot about RP Rev, Fox, is that if you say No they would stun, cuff you, and repeatedly press the convert box until you say yes.

And you can't tell who Rev Heads are since they got no flashes.

And used to also have Traitor Uplinks.

**Comment by theColdflame** [comment]
why the spraycan?

**Comment by Fox-McCloud** [comment]
Tested this out---should be ready to go.

**Pull request merged**
