### PR TITLE
Fix karma totals table name in schema

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

SQL schema creates `karmatotals` but DM code uses `karma_totals` - not good! This fixes that

## Changelog
N/A

### CODE REVIEW

**Comment by S34NW** [comment]
This bumps the schema version, you need to make an update file for existing databases

**Comment by AffectedArc07** [comment]
> This bumps the schema version, you need to make an update file for existing databases

No it doesnt. The updates have the right name.

**Comment by S34NW** [comment]
> > This bumps the schema version, you need to make an update file for existing databases
> 
> No it doesnt. The updates have the right name.

scuffed

**Comment by AffectedArc07** [comment]
> > > This bumps the schema version, you need to make an update file for existing databases
> > 
> > 
> > No it doesnt. The updates have the right name.
> 
> scuffed, so it was moved over everywhere apart from the actual schema for new setups?

yep

**Review by AffectedArc07 — APPROVED** [review]
I am a certified dumbass.

More SQL unit tests coming soon.

**Pull request merged**
