### PR TITLE
Kidan Sprite improvements plus additional cosmetics.

### PR DESCRIPTION
**Pull request by TravellingMerchant**
This PR adds improved shading to the Kidan sprites as well as additional cosmetic items, such as horns and a few new antennae. 

Before and after of the new shading. (Before above, after below)

Full display of the new cosmetics with the new shading.
In order from right to left: 
Mantie_Long
Mantie_Curled
wide_horns
hollow_horns
hawk_horn
curled_horns
bull_horns
broken_bull_horns
tall_horns
Very_Short

kidan cosmetics

The new horns can be worn at the same time as antennae.
dreamseeker_2018-08-09_16-22-45

### CODE REVIEW

**Comment by TravellingMerchant** [comment]
Also damn, missed my chance to make a joke about Kidan being horny. Oh well.

**Comment by Plotron** [comment]
Kidan love! Loving it.

**Comment by KasparoVy** [comment]
Good call, looks fantastic.

**Comment by TravellingMerchant** [comment]
Thanks!

**Comment by TravellingMerchant** [comment]
Is there anything else I need to do or is it good to go?

**Comment by TravellingMerchant** [comment]
Guess I'll wait a month for merging then.

**Comment by FishStix4Dayz** [comment]
so sad... I hate these long wait times

**Comment by TravellingMerchant** [comment]
Guess this PR is going nowhere.

If someone wants to fix the conflicts and make another PR, be my guest.

**Pull request closed without merging**
