### PR TITLE
Undoes the map explosion caused by AA's PR

### PR DESCRIPTION
**Pull request by Crazylemon64**
Reverts #9361 due to it not playing nice with map merge

```
git show HEAD~6 cyberiad.dmm > cyberiad.dmm.backup
*run map-merge tool*
git status
*no changes*
diff -u cyberiad.dmm cyberiad.dmm.backup
*every single line is changed*
```

:cl:Crazylemon
fix: makes AA's map fix not annihilate every map PR in existence
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
So how do I make this work

**Comment by Crazylemon64** [comment]
@AffectedArc07 I re-did your changes and this time they didn't map conflict. So that's good.
modified_map_aa

**Comment by AffectedArc07** [comment]
:cl: Crazylemon
fix: Makes affecteds scrubber fix not nuke every single map PR
/ 🆑

**Comment by Crazylemon64** [comment]
(Yes, I noticed those loose pipes I placed down to test after that screenshot, and removed them)

**Comment by miniusAreas** [comment]
@AffectedArc07 So your a atmosian AND a telecoms nerd? Yeesh. What more do I have yet to learn from you.

**Pull request merged**
