### PR TITLE
Adds "Muh Cliques" Graffiti

### PR DESCRIPTION
**Pull request by Ty-Omaha**
muh cliques

277e93c17a9a7a8c32b8983664039552

:cl:
add: Adds "Muh Cliques" Graffiti
/:cl:

### CODE REVIEW

**Comment by Wheatley29** [comment]
Image?

**Comment by FlattestGuitar** [comment]
I don't even know.

......:+1:?

**Comment by Aurorablade** [comment]
.....
....
..no..

**Comment by Lady-Luck** [comment]
sure why not

**Comment by Rumiluntti** [comment]
Why was this not an option earlier?

**Comment by KasparoVy** [comment]
Lmfao, easter egg Vulpkanin.. Those are some nice pastel colours.

**Comment by Ty-Omaha** [comment]
after sleeping in the middle of the day and finally stopped laughing, now that I think about it this will just be used as another form of harassment, so as funny as it is, I'm gonna close it

**Pull request closed without merging**
