### PR TITLE
New mutation, new clown feature

### PR DESCRIPTION
**Pull request by ZomgPonies**
- COMIC mutation. Talk in Comic Sans. Works over radio, and works with alien languages.
- Gives the clown COMIC for added HONK.
- Adds Mk2 and Mk3 drone icons Pics: http://baystation12.net/forums/viewtopic.php?f=44&p=259489#p259487
- Changes the clown intro pic to awesome FoSart https://www.dropbox.com/s/iqen0vmgj8hbwn7/fos1.png?raw=1
- Makes sure all staff have "Check new players"
- Adds a new secondary language anyone can learn: Clownish
- EMERGENCY: Removes WHISPER disability which causes infinite loops and crashes

### CODE REVIEW

**Comment by fj45** [comment]
Yes, YES.

**Comment by Fox-McCloud** [comment]
Pics for the drones would be great.

**Comment by ZomgPonies** [comment]
http://baystation12.net/forums/viewtopic.php?f=44&p=259489#p259487

**Comment by TheDZD** [comment]
Hmm, the comic mutation may pose a problem for changeling clowns, or traitor clowns that use the voice changer gas mask, may want to remove the block in the same way the clumsy gene is removed from traitor/ling clowns.

Other than that :+1: for the evil that is Comic Sans.

**Comment by Fox-McCloud** [comment]
If the block is removed from ling clowns, then everyone will just metaknowledge normal talking clowns as changelings; likewise, they'll metaknowledge the point DZD brought up, as well.

Ok for this to be a mutation, but having it on the clown is going to present problems.

**Comment by ZomgPonies** [comment]
Give the clown a 50% chance of him getting it, problem solved.

**Comment by ZomgPonies** [comment]
Also I think an interesting concept that could give a buff/balance to Lings would be that when they turn into another character, have them also have those character's SE. So if they absorb a bunch of characters with beneficial mutations, they would have a selection of different characters that would be 'buffed', but on the flipside they might absorb characters that have genetic debuffs. But that's probably an idea for a seperate PR.

**Comment by ZomgPonies** [comment]
Since lings absorb all DNA already (SE + UI), it's easier just to fix the voicechangers themselves.

**Pull request merged**
