### PR TITLE
pAI Manifest / Messager Default Software

### PR DESCRIPTION
**Pull request by K3Licia**
## What Does This PR Do
Makes the Crew Manifest and Digital Messenger software be installed onto pAI by default. 

## Why It's Good For The Game
I believe it makes sense for pAI to have these features by default as PDAs already do, and it feels questionable having to pay for what is the bare minimum, in my opinion, even if cheap. Crew Manifest is harmless to give for free, and every pAI takes Digital Messenger regardless of their specialization, so I figured it wouldn't be too much of a game changer.

## Testing
Unfortunately, I cannot test the PR. (likely due to spawned in pAI's being different somehow? or perhaps private servers) However, I'm confident a simple line change like this wouldn't need much testing!

## Changelog
:cl:
tweak: Makes pAI software "Crew Manifest" and "Digital Messenger" installed by default.
/:cl:

### CODE REVIEW

**Review by DGamerL — COMMENTED** [review]
You seem to have touched a lot of unrelated sprites?

**Comment by K3Licia** [comment]
> You seem to have touched a lot of unrelated sprites?

thaaaat is very weird, hold on a moment

**Review by DGamerL — COMMENTED** [review]
Taj sprites still touched...

**Comment by K3Licia** [comment]
> Taj sprites still touched...

cured...

**Review by DGamerL — APPROVED** [review]
No more sprite changes :D

**Review by PidgeyThePirate — APPROVED** [review]
Code looks fine.

**Review by Henri215 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]

**Pull request merged**
