### PR TITLE
Tweaks Beach Awaymission

### PR DESCRIPTION
**Pull request by Kyep**
Adds a pirate area to the beach away mission.

Area contains:
- dangerous mobs to fight: several pirates with e-cutlasses and laserguns. Bring friends!
- loot: pirate clothing, including collectible hats, retro laser guns, uranium, a small amount of diamond.

Note: getting to the pirate area is not easy. You have to find a hidden diving anchor in the undersea area. The pirates themselves are merciless. They will burst-fire lasers at you like no tomorrow. This is NOT aimed at solo explorers!

🆑 Kyep
tweak: Adjusted Beach awaymission so it now includes deadly (but rewarding) pirate area.
/🆑

### CODE REVIEW

**Comment by jughu** [comment]
You can auctally solo this pretty easy put unsecured girders infront of it they fire at it then you take a side step do 1-3 shots(or floortiles if you dont have weaponry the room with the 2 pirates is the only challenging thing bout it but the rest you can solo it easily

**Comment by jughu** [comment]
>pirates dont even have gold but fucking uranium I THOUGHT PIRATES WERE ALL ABOUT BOOTY

**Comment by Kyep** [comment]
@jughu That assumes the pirates don't flank you. Also it doesn't work against the esword-wielding pirates. If it turns out to be too easy, I can tweak it later. However, when playtesting it, I found myself rapidly dying to laser bursts multiple times. A triple-shot from a laser gun does 60 or so with one burst. Yeah, perhaps you can do it with girdirs if you are very, very careful - but if you mess up, you're going to bed dead.

**Comment by Xantholne** [comment]
unsecured girders can still be destroyed by any projectiles

**Comment by SamHPurp** [comment]
Like the trend of adding more to Away missions 👍

**Comment by jughu** [comment]
@xaltonon secured is fine to since pirates moves away from you as it shoots

@kyep doesnt stop my floortiles throwing skills

**Comment by KasparoVy** [comment]
Pretty sure they can one-burst a displaced girder to death, they're really not that strong anymore AFAIK

**Comment by Aurorablade** [comment]
i don't think all away missions need a combat edge to it, i would be fine with a simple exploratory edge to it.

**Comment by Fox-McCloud** [comment]
>i don't think all away missions need a combat edge to it, i would be fine with a simple exploratory edge to it.

This. Not everything is *meant* to be loot city or combat city USA with an inherent "Get all the stuff for personal gain" angle; some are just meant to be taken in, thematically; beach is more on this level than the others.

**Comment by Kyep** [comment]
If you have some suggestions for exploration stuff I could add, let me know.

The pirate base is in a secluded area that you have to pass through two zone transitions to get to. You have to dive, explore for awhile, the find a second, hidden, dive point. It is pretty well hidden. People who go there seeking a relaxing time, won't find it. You have to be pretty dedicated to find it.

**Pull request merged**
