### PR TITLE
Return gag to security

### PR DESCRIPTION
**Pull request by tigercat2000**
Muzzles are the best clothing item.

Re-adds the ballgag to security ballgag

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Yeah, no :-1:

**Comment by Spacemanspark** [comment]
I don't see a terrible issue with this.

**Comment by Alex6511** [comment]
Weren't they bugged?

**Comment by tigercat2000** [comment]
Not as far as I know, muzzles work just fine.

**Comment by Bad-Apple797** [comment]
kinky.

Muzzles work fine, last I checked blindfolds are bugged but that was a while ago.
Muzzles in maint doesn't make much sense, can't we port duct-tapping mouths?

**Comment by Regen1** [comment]
:+1: for what apple said

**Comment by TheDZD** [comment]
I don't see an issue with this (except telescience, but telescience is shit in and of itself).
:+1:

**Comment by NTSAM** [comment]
Yesh, gags again. Best addition 2k15

**Comment by Markolie** [comment]
Don't really care about this either way.

**Comment by Iamgoofball** [comment]
Ballgags are a fetish item. Never re-add.

**Comment by Earthdivine** [comment]
Don't really care for the ballgag, no ones gunna remember it's there.

Muzzles however I don't like, the idea of having an easy access item that stops all talking is a big no to me.

**Comment by Bad-Apple797** [comment]
I'm not against the idea of being able to muzzle people - takes the same amount of time as removing their headset, and anyone close enough to hear you normally should be able to see you're cuffed and gagged, if they can't figure out you're being kidnapped, they would likely do nothing even if you did speak,

But the idea of a muzzle being in maint is kinda weird, why does a science station have so many muzzles? Port duck-taping mouths, gives it a damn use, and being able to silence people might lead to antags being a bit more creative.

**Comment by tigercat2000** [comment]
general consensus seems to be against the muzzles in maint.

**Pull request merged**
