### PR TITLE
Resprites a few Species, updates others, Kidan Antennae, Skrell Colouration, etc.

### PR DESCRIPTION
**Pull request by KasparoVy**
This is a re-up of https://github.com/ParadiseSS13/Paradise/pull/6174, the finished product.

:cl: Puckaboo2, TravellingMerchant, KasparoVy
tweak: Unathi, Tajara, Grey, Skrell and Human sprites receive enhancements to overall quality.
tweak: Nucleation and Kidan sprites receive anatomy upgrades.
tweak: Skrell receive unique eye sprites.
rscadd: Adds a bunch of Kidan antennae head-accessories.
rscadd: Adds Kidan female sprites.
rscadd: Skrell can now be coloured as you please. The sprites have been greyscaled and darkened.
rscadd: Adds a few modified markings for Tajara and Unathi (shading tweaks, mainly).
rscadd: The horns of a spawned-in non-player Unathi now have a default colour.
rscadd: Tajara and Unathi can choose to have visible hand-claws at character creation. Purely cosmetic.
fix: Resolves an issue where the lower snout marking wasn't a choice for those who picked the Unathi alt. head.
/:cl:

Pretty much all sprite-work courtesy of Puckaboo2.
Kidan sprite-work courtesy of Puckaboo2 and the race creator, TravellingMerchant.

- Resprites Unathi, Tajara, Greys, updates Humans, Nucleations and Kidan.
--------> The adjustments made to Nucleations were just to keep their anatomical structure the same as Humans, which they once were. Their colours and crystals are all the exact same.
- Adds a bunch of antennae for Kidan as head accessories.
- Adds a few modified markings for Tajara and Unathi (mainly shading tweaks) although the originals have been kept for the sake of choice.
- Skrell now get proper eye sprites, and are FULLY COLOURABLE! Their tentacles and tentacle accessories got a bit of a touch-up, as well.
- Tajara hair received a touch-up shading enhancements.
- Changed the default hairstyle on Unathi mobs to the head-accessory version. No visual change, doesn't affect players unless they humanize a Stok from genetics. All they'll notice is that they can't shave off the lizard's horns. Furthermore, these horns now get a slightly greyish default colour instead of coal black.
- Skrell get something similar to the above point: They now have a 'default' body and head tentacle colour that closely resembles the colour they used to be by default. Remember, this doesn't apply to players, only spawned-in playerless mobs.
- Tajara/Unathi now get the option to have visible claws on their hands. These claws will not appear on robotic hands, and are purely cosmetic.

# Pictures (click links).
[**Body Sprite Comparisons**](http://imgur.com/a/xHIve)

[**Markings, Hair, Antennae and.. Everything else.**](http://imgur.com/a/u2n1S)

## Yet more pictures.
_The final iteration of the 'very humanoid sprites' (changed from initial). These do not clip with uniforms._
humanoidspritesupdatedyetagain

_The claws preference. This is purely cosmetic._
clawspref

_The claws in game. You've already seen this in the above pictures._
clawsfoursquare

_Claws showing up in ID cards photos._
idclaws

_The cosmetic claws persist if you swap the hand to another player. Conversely, cosmetic clawless hands swapped to you will not suddenly get claws if you have the preference on._
clawhandswapping

### CODE REVIEW

**Comment by taukausanake** [comment]
That Tajaran tail looks a bit weird...

**Comment by Puckaboo2** [comment]
Oh my goodnis, I am so stoked. This took so long and I am thankful for Merchant for allowing me to collab with him and Kasparov for saving my fluffy ass multiple times during the processdof getting these pics together 

UNATHI BELLIES

**Comment by HugoLuman** [comment]
Perhaps we might see an uptick in Skrell while people try this out?

**Comment by KasparoVy** [comment]
I know quite a few players who'll be ecstatic to be able to properly colour Skrell. This is something they've needed for ages

**Comment by Puckaboo2** [comment]
And something that has already been a thing for ages on other servers. Hell, even Eternal, which used olllld baycode, had colorable Skrell and eyes and their tentacles matched, too.

**Comment by Dinarzad** [comment]
dat skrell tho.
I'll probably actually bring mine out more with this.

**Comment by TravellingMerchant** [comment]
Looking forward to this! It was fun making the Antennae. 

The rest of the changes look fantastic too!

**Comment by Aurorablade** [comment]
NO FAT TANGERINES...RABBBLERABBBLERABBBLERABBBLERABBBLERABBBLERABBBLERABBBLERABBBLERABBBLERABBBLE

**Comment by taukausanake** [comment]
Still need fat foxys

**Comment by Puckaboo2** [comment]
Fox said no fat foxies. Sorry.

**Comment by Nienhaus** [comment]
Why not?

**Comment by TravellingMerchant** [comment]
Because fat foxes goes against them being the most perfect race in the entire universe where nothing bad could happen with them. /s

**Comment by TravellingMerchant** [comment]
Also forgot to mention, this PR should contain new separate male and female Kidan sprites. Males have bigger jaws and the markings are different. There's also shading improvements.

**Comment by Puckaboo2** [comment]
@TravellingMerchant I don't know how many times you told me 'You did the chest wrong' and I'd go 'no I fix' and 'you did it again' and I'd go 'nonono I fix'

We were really a team there xD and Kidan turned out looking really nice. You rocked those antennae, fam, I can tell you that much. Kidan peeps are going to love the new antennae.

**Comment by FlattestGuitar** [comment]
https://www.youtube.com/watch?v=w7AuQvuq2sY

**Comment by Puckaboo2** [comment]
Omg XD

**Comment by PhantasmicDream** [comment]
Skrells now being grey-scaled is all I wanted in life.

**Comment by taukausanake** [comment]
Does that mean they can be any color then? How is this different from all the rage that Vulpkanins and Tajarans got for being any color? I am too curious as I thought (Polaris at least) had a draft showing multiple colors Skrell could be

**Comment by Puckaboo2** [comment]
In bay lore, Skrell skin colors can range from reds, greens, blues, oranges and pinks, even black. So, it makes sense Skrell can be colored.

**Comment by KasparoVy** [comment]
@taukausanake Skrells could already be just about any colour they wanted except the darker ones, which means that if they wanted to have a non-standard colour, it was eye-blindingly bright.

**Comment by Spacemanspark** [comment]
While we don't follow Bay lore, I don't see an issue with skrell being any color they want. It doesn't look fucking terrible and makes sense.
Unlike a neon green/ pink/ yellow vulp/ taj thing that kills your eyes.

**Comment by taukausanake** [comment]
I don't see an issue either but I like lore. It helps keep things consistent, in some fashion even if limiting in some areas. Nothing wrong with it, just me being me

**Comment by Spacemanspark** [comment]
I wouldn't say it's against our lore.

**Comment by taukausanake** [comment]
I understand Paradise lore but I like following whatever can be noted as the original lore of something. Take Drask for instance. They originated here therefore any lore concerning them for me will be read from Paradise. Another instance, Resomi (or whatever the fuck they're called now), I will follow the lore from the [Official Avali Wiki](http://avali.wikia.com/wiki/The_Official_Avali_Wiki) because that's what they were based off even if not completely the same. That OR I go to BayStation that made it but it's not the same to me

**Comment by Aurorablade** [comment]
Code Precedes Lore...and don't mention resomi you will trigger some of the coders...

**Comment by taukausanake** [comment]
@Aurorablade Please, I'm already triggered we will never get them. Those feathery bastards are the cutest <3

**Comment by Spacemanspark** [comment]
gib resomi

**Comment by KasparoVy** [comment]
Not in this PR. :')

**Comment by Fullofskittles** [comment]
I'm not really keen on the tiny pixel claws on the Tajaran. If anything I feel that'd be better left to an optional body accessory/marking instead of something on the base-sprite itself. Also, the tail animation was changed in the east/west directions. Is this an alternate tail or did the original one get updated too?

The other thing I kinda wanna poke at is that with all of the the reshaded options it looks like you only see one leg in the east/west versions. The darker outline that previously was there seems to have been removed which makes it look inconsistent with the rest of the sprite. I think it'd be nice to see that shading on the legs altered to show that there are indeed two there.

**Comment by Puckaboo2** [comment]
Fine. I'll see what I can do.

**Comment by Fox-McCloud** [comment]
@Puckaboo2 

Did you resprite these according to what @Fullofskittles suggested?

**Comment by Puckaboo2** [comment]
@Fox-McCloud no, I did not. Doing that would require me lightening the darkest border of all the color-selectable species by 10 rgb and then modifying the markings as well. 

I might do something like that for the next PR I am planning to do, but even then, I do not know how that will turn our. I actually could do the foot and leg thing for humans and Grey, and if it bothers you all for those two species, I could possibly make some changes. For the rest of the species, I wish to leave those alone, for now.

**Comment by Fullofskittles** [comment]
xkj1
I haven't checked the other sprites to see if extra pixels have been added anywhere that might cause issues with clothing but adding extra pixels will _generally_ cause issues with clothing which means either adjusting every existing clothing (and all future clothing) _or_ just sticking with the existing silhouette to avoid compatibility issues.

I really do think this is something you need to address and if you're going to fix those extra pixels you might as well take the time to adjust the legs too. That's as simple as colorpicking since the outlines of most mobs is consistent. 

Truthfully the best way to have gone about this would've been to reshade and wait to chop each part into bodyparts _after_ they were approved. In the future it'll save you a ton of work on revisions in the event of changes being requested.

A few final questions;
- Have you tested the other sprites to see if they work with existing clothing yet? 
- Were there other spots were you added pixels that may extend past the 'standard' bodyshapes?
- Did you also reshade the original tajaran tail animations or did you change the east/west sprite entirely?
- Did you consider making the tajaran claws an optional accessory instead of a forced change?

**Comment by Puckaboo2** [comment]
Alright, I see what you're saying. I'll be sure to get to fixing that.

1. I have not tested any races with clothing, but after I apply these fixes, I will clothe the sprites and see how they look.

2. I have not seen any more clipping issues with any sprites I have seen with clothing.

3. It was a simple reshade for the still sprite, but the animation was changed so the tail had a more uniform appearance.

4. We have thought about making claws appear only on harm intent for Tajara and permanent for the Unathi. If you want me to make these accessories, for now, I am happy to oblige.

**Comment by KasparoVy** [comment]
Sprites updated, very humanoid body-types will no longer clip with uniforms as they did in the first iteration.
The claws on the hands of Tajara and Unathi are now by-preference only.
See main post for details.

**Comment by Fox-McCloud** [comment]
@Fullofskittles

**Comment by Puckaboo2** [comment]
@Fox-McCloud The edits you have suggested have been applied.

**Comment by KasparoVy** [comment]
Conflicts resolved.

**Comment by Fox-McCloud** [comment]
@KasparoVy 

As the OP been updated with the newest sprites?

**Comment by KasparoVy** [comment]
@Fox-McCloud The pictures that are visible at the bottom of the OP without having to click a link are up to date with the newest sprites, the ones you have to click a link to view are older but I left them in anyway as they still have some bearing.

**Comment by tigercat2000** [comment]
Honestly, the only sprite changes I like are the ones to fat humans. Everything else feels kinda unnecessary.

**Comment by KasparoVy** [comment]
I disagree.

**Comment by Puckaboo2** [comment]
@Kaspersky I could not agree more. These changes needed to be made. Some of these sprites are God-knows-how old and they truly needed some love.

**Comment by taukausanake** [comment]
Did the golem front always look so... bland? I thought it was more detailed than that, even if just a tad bit. Maybe it's just me...

**Comment by KasparoVy** [comment]
@Taukausanake Yes, golem sprites have not been touched by this PR.

**Comment by TravellingMerchant** [comment]
If the rest of this doesn't get through, can we at least get the Kidan changes through? Very minor customisability would be nice.

**Comment by KasparoVy** [comment]
I don't understand the opposition to what're straight upgrades to existing sprites.

**Comment by tigercat2000** [comment]
How can you possibly perceive any creative artwork as "straight upgrades"?
It's a change in aesthetics, some people will love it, some people will hate it, that's how aesthetics work
I don't consider this anything close to a "straight upgrade"; I dislike the way that skrell hair looks, it's lines are too bold, the tentacles should be the same color as the body. I don't care for the fact that it gives human sprites a noticable curve under their chest, especially on males. They shouldn't have tits. I don't like the very slight pink tint to the nipples on the sprite. The female human side states look like their bodies are deformed, it doesn't convey "breasts", it conveys "help my ribcage is collapsing", or perhaps "i'm a sloucher". I think the claw overlay on tajara look pretty bad, and don't really get across "claws" at all.

**Comment by taukausanake** [comment]
Yeah, I got to agree with Tiger on all accounts, as well as say I don't personally like any of the other sprites either. Tajaran look like some kind of mouse now. I think those gray on the center right are abductors? They have anime eyes and I think they were faceless before? It's all I've seen from the wiki page at least. I can't add anything else that hasn't been said already

**Comment by KasparoVy** [comment]
@tigercat2000 Skrell hair, by default, is the exact same colour as the body. I manually picked the body and hair colour in one of the preview images so they wouldn't be black, and I arbitrarily decided on a darker shade for the tentacles. The Tajara/Unathi claws are an aesthetic preference, and in-tune with your aesthetic point I'm going to again disagree. I've no comment on the Human sprites as I don't see a glaring issue with either point, though I couldn't care less if it was changed. I'm going to leave the decision of what changes to make up to @Puckaboo2 on this one.

@taukausanake Could you please look at the changelog and changed files tab? Abductors were not touched in this PR, either. Updated the picture caption to make it more obvious

**Comment by TravellingMerchant** [comment]
Hearing no criticism about the Kidan changes though?

**Comment by Puckaboo2** [comment]
@tigercat2000 I fixed the backs for you. The female human looks exactly how she did before but with very minor changes to the front.

I can't really do anything else. I've worked very hard on these changes.

**Comment by KasparoVy** [comment]
Going to resolve the conflicts shortly

**Comment by KasparoVy** [comment]
Conflicts resolved, going to post updated pictures soon(tm).

**Comment by KasparoVy** [comment]
Been very ill for the past four days, might not get to making the photos until mid-week or friday with the work backlog I have now.

**Comment by KasparoVy** [comment]
humanoidspritesupdatedagain

**Comment by taukausanake** [comment]
Black Skrell. That is all I have to say here

**Comment by KasparoVy** [comment]
(Hopefully) final tweaks committed.

humanoidspritesupdatedyetagain

**Comment by orelbon** [comment]
Sooo merge plz?

**Comment by Fox-McCloud** [comment]
After discussing this internally and consulting with a few other individuals, we've come to a conclusion on this: we do not want the re-shading portion of this PR---other aspects of this PR (accessories, Skrell being colorable, etc) are welcome, but the re-shading is not; if that is completely stripped out, then things should be ok.

Also, apparently, this changes the Tajaran tail wagging animation, but doesn't really document it; that's a no-go as well.

**Comment by Puckaboo2** [comment]
What is wrong with the shading?

**Comment by Puckaboo2** [comment]
Does anyone realize how much work Kasparov, Travelling Merchant, and I put into this? Over the past few months?

**Comment by KasparoVy** [comment]
We're both interested in hearing what particular was disliked about the sprites, specific criticisms, etc. I know Puckaboo's been working, tweaking/retweaking/responding based on criticisms again and again for the past age and this came as a bit of a surprise.

**Comment by TravellingMerchant** [comment]
I mean hey, my only changes were the Kidan, which should be in the acceptable part of what fox said.

**Comment by KasparoVy** [comment]
Opening another PR with the passable features

**Comment by Lady-Luck** [comment]
Ridiculous.

**Comment by Aurorablade** [comment]
Uhhh I am gonna have to agree I was looking forward to some of the taj stuff maybe not the tail bit

**Comment by Lady-Luck** [comment]
"In regards to the sprites, a party not wishing to be named and who does spriting for a living, contacted the maintainers about the shading, and how it actually affected the quality of the models. Naturally,  this affected the animations of said sprites and, all in all, would be a downgrade in the long run."

ahahahahaa

**Comment by Aurorablade** [comment]
Light fire is correct there and I can understand this after hearing the explantion from various partys.

**Pull request closed without merging**
