### PR TITLE
Adds a matter decompiler to janitorial and service borgs

### PR DESCRIPTION
**Pull request by Landerlow**
This way, borgs can clean more stuff up. Especially since the service borg also causes a mess by producing glasses, etc.

>Some items like glasses and noodle cups need to be made working with the trash bag AND matter decompiler. Talked to Crazylemon about that in discord recently. But that's not for this PR.

🆑 
Adds a matter decompiler to the janitorial and service borg modules.
/ 🆑

### CODE REVIEW

**Comment by Bigtimetripod** [comment]
Add a changelog note also.

**Comment by LittleBigKid2000** [comment]
You're probably going to get yelled at for the merge commit things. You should probably rebase then redo the changes.

**Comment by Landerlow** [comment]
Oh. I see. Yeah. I'm not sure what went wrong there. Hold on

**Comment by Landerlow** [comment]
I'm an idiot. I'm not sure what happened here, what with the merge commit things. All I wanted is to change those two lines of code.


:upside_down_face: 🔥  🔨

**Comment by Landerlow** [comment]
Okay, even with crazylemon's awesome help it just did not want to fix properly.

**Pull request closed without merging**
