### PR TITLE
New bag sprites by Alexios!

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Resprites all the bags, done by Alexios
The treasure satchel (only normal, not bluespace) got a new sprite

## Why It's Good For The Game
These are all very crusty sprites, long overdue for some new ones!

## Images of changes
image

image

image

image

image

## Changelog
:cl: Alexios
imageadd: The Plant bag / Chemical bag / Bio bag / Treasure satchel / Mail bag have all been resprited!
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Pending sprite team approval

**Comment by Alecksohs** [comment]
> Pending sprite team approval

image

**Review by Sirryan2002 — APPROVED** [review]
approved for code

**Review by Spaghetti-bit — APPROVED** [review]
Took a look at the sprites and loaded this onto a local server. Looks good, code is minimal as it is just a resprite. Good work.

**Review by Burzah — APPROVED** [review]

**Pull request merged**
