### PR TITLE
Icon and Sound Cleanup

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just a cleanup patch; it's no secret that our codebase is uh....a bit large in size. Should help players load in faster and just generally cleans up a bunch of unused stuff we don't use anymore or never did.

There's really only two sound changes here (and NO icon changes) that players will notice (they're at the bottom in their own section).

Overall amount shaved out of the codebase: ~20 MB.

How it impacts players: instead of downloading ~72 MB of resources, they'll now download ~57 MB

KIlls off some Hefty Sized Unused Icons
- Removes some unused singularity icons  (these files were huge for what they were)
- Removes the unused EM field icon (RIP R-UST generator)
- Removes all of the unused Title Screens

Kills off a bunch of unused sounds
- Removes an unused Bay music clip
- Removes 99% of the old AI voice sounds (mai nostalgias!); a few remain that are still used/accessible to players
- Removes some unused wind wounds
- removes some unused snowflake Bay player announcements
- removes a duplicate sound in the wrong folder

Replaced Sounds

- replaces taser sound with TG's taser sound
 - this is actually our taser sound, just shortened so the sound doesn't last forever and the file doesn't take up so much space
- Removes our current sear sound (0.3 MB and the sound lasts 10 seconds when you get hit by a laser shot...what)
 - Laser shots will now play the "sear" sound laser scalpels make

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:-1: To arbitratry removal of icons/sounds from the codebase. 20MB barely makes a difference overall, this has absolutely no benefit to the players, and is a slippery slope as to one maintainer considers deprecated. For example, what makes you think the RUST generator is deprecated and won't get fixed up? Other codebases have completed it.

**Comment by Iamgoofball** [comment]
@ZomgPonies As someone on the west coast, I dread having to update my resources for paradise because it takes so goddamn long.

This would give me a noticeable increase in download speed.

**Comment by Fox-McCloud** [comment]
R-UST is dead; you killed it off, yourself: https://github.com/ParadiseSS13/Paradise/commit/b33df4745cd6ca06903bd97a63a883fa260b4143 and it was excised from the code, at a later date (I believe during Mark's restructuring). 

The singulo sprites (16 of the 20 MB) take up the majority of this space; they're redundant with the current sprites, so they're not needed anymore--no sense in having players download 16 MB worth of resources they don't use.

The rest of what was removed is literally not in use in *any*  part of the codebase--the majority of which is VOX (the old old AI voice announcement)--again, redundant because of Vox_Female.

**Comment by ZomgPonies** [comment]
Except players DONT download those ressources as they are not compiled into the rsc. ONLY coders download them from Github.

**Comment by Fox-McCloud** [comment]
Fair enough; either case, the vast vast bulk of this PR is removing redundant resources that are unused or replaced by something else. (or have no place in the codebase: a baystation player's own vocal recordings).

**Comment by ZomgPonies** [comment]
I'm alright with the sound stuff since it's already replicated elsewhere, but I'd like to keep the sprites as those can be reused for other projects. They literally need to be downloaded once, and only be people downloading the codebase. The benefit from removing them is pretty trivial.

**Comment by tigercat2000** [comment]
Removing icons and sounds that aren't used does precisely nothing for player-end downloads. BYOND doesn't care about sounds or icons that aren't in a ' operator somewhere in the code, it just doesn't send them. This isn't necessary at all, and is also exactly how sprites and sounds end up lost to time, like thunderdome.ogg. Not going to support this.

**Comment by ZomgPonies** [comment]
So after lots of discussion in staff chat, it's requested that instead of removing the icons from the codebase, they are instead split off into a seperate dmi file so as not to get sent to players in the rsc.

**Pull request closed without merging**
