### PR TITLE
Footsteps fix

### PR DESCRIPTION
**Pull request by CrAzYPiLoT-SS13**
Fixes half of #2786, other half has already been fixed.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
...no.

The footwear sound should override the floor, not the other way around.

**Comment by Fox-McCloud** [comment]
@tigercat2000

**Comment by tigercat2000** [comment]
it's not really very good but whatever i guess

**Comment by Fox-McCloud** [comment]
Next time, you need to update BEFORE you push changes.

**Comment by CrAzYPiLoT-SS13** [comment]
I actually did, it's just Git Desktop fucking me over.

**Pull request merged**
