### PR TITLE
[PORT] Eris slimes sprites (Second try)

### PR DESCRIPTION
**Pull request by AyIong**
## What Does This PR Do
Reopens - https://github.com/ParadiseSS13/Paradise/pull/16882
Port - ~~https://github.com/TauCetiStation/TauCetiClassic/pull/9700~~ https://github.com/discordia-space/CEV-Eris/pull/6205

## Why It's Good For The Game
**Really** cool slime sprites

## Images of changes
image

https://github.com/ParadiseSS13/Paradise/assets/69762909/8c1a9680-f8d7-4009-a7b9-8170740420f0

## Testing
Locally

## Changelog
:cl: WalterJe
imageadd: Slimes have new sweet sprites
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Please give appropriate credit in the changelog, these are Eris sprites (previous PR here https://github.com/ParadiseSS13/Paradise/pull/16882) by spriter `WalterJe`, see https://github.com/discordia-space/CEV-Eris/pull/6205

**Comment by AyIong** [comment]
> Please give appropriate credit in the changelog, these are Eris sprites (previous PR here #16882) by spriter `WalterJe`, see [discordia-space/CEV-Eris#6205](https://github.com/discordia-space/CEV-Eris/pull/6205)

Thanks, i was thinking that's tau sprites

**Review by SynthTwo — APPROVED** [review]
Looks Gooey To Me.

(I just really wanted to say this first. The PR is one file. It works. I checked in game. Ramon likes the sprites.)

**Review by Contrabang — APPROVED** [review]

**Review by PopeDaveThe3th — APPROVED** [review]
yeah it's probably fine

**Review by Henri215 — APPROVED** [review]

**Pull request merged**
