### PR TITLE
Touching a lightbulb with bare hands will now set you on fire

### PR DESCRIPTION
**Pull request by tigercat2000**
Alternative to #4246

### CODE REVIEW

**Comment by fludd12** [comment]
Not drastic enough, make touching it twice ash you.

**Comment by KasparoVy** [comment]
You got it boss

**Comment by Dumbdumn5** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Speedmerging. Too hilarious to not be in.

**Comment by Dumbdumn5** [comment]
Thank you, does this mean I stop commenting on the other one?

**Comment by Dumbdumn5** [comment]
Oooh, can we have a chatroom basically, wait... we have those... but we don't use them.

**Comment by Fox-McCloud** [comment]
@Dumbdumn5 

Definitely.

**Comment by Dumbdumn5** [comment]
I mean, everybody is here...

**Comment by Dumbdumn5** [comment]
@tigercat2000 Did you order the beer volcano and hookers?

**Comment by Dumbdumn5** [comment]
Welp, off to the staff chat to continue being horrible.

**Pull request merged**
