### PR TITLE
Metastation R&D remap

### PR DESCRIPTION
**Pull request by Johannes2262**
## What Does This PR Do
The R&D machines got moved closer to the R&D desk, some things which were at this place got moved to the old place of the machines.

## Why It's Good For The Game
The change allows scientists printing or deconstructing items to see people waiting at the front desk.

## Images of changes
grafik

## Testing
Compiled and tested on a local server, everything worked as intended

## Changelog
:cl:
add: Moves R&D machinery closer to the R&D desk
/:cl:

### CODE REVIEW

**Review by Miraviel — CHANGES_REQUESTED** [review]
- This scrubber pipe has no scrubber outlet (under the protolathe) and the vent is not connected to a pipe here. In general, I suggest _not_ putting scrubbers/vents under objects, it makes them difficult to weld/see at a glance if the air alarm is acting up.

image

- The APC is not connected to the power grid:

image

- The room has two fire alarms:

image

- The room has seemingly no air alarm or I'm blind (one of the two)

- Consider adding a camera near the protolathe, the AI cannot see that entire section if the shutters are down

- This is more of a request, but I suggest putting the Protolathe near the console, as it is the most frequently used machine out of the three (circuit imprinter, protolathe, destructive analyzer) - it'll cut down on the walking time. Something like this could work, the analyzer should be accessible through the table:

image

**Comment by Johannes2262** [comment]
I will change the object placement soon, the issues with power and scrubbers probaly happened when I moved the tile there, will get fixed soon.

**Comment by Johannes2262** [comment]
The protolathe got moved near the console now, it is possible to access the analyzer diagonal over the table. Both APC and atmospherics should be working now too, the second fire alarm was removed. I also added another camera near the desk.

**Review by Miraviel — CHANGES_REQUESTED** [review]
Looks good, one last nitpick, the room has 2 vents but only 1 scrubber, please add one more scrubber (almost every area has the same amount of vents/scrubbers, this is just to make this room in line with the others).

image

**Comment by Johannes2262** [comment]
Should be done now, I will update the picture too.

**Comment by Johannes2262** [comment]
I also fixed the name of the Northern camera, it was labelled "Chapel" before.

**Review by Sirryan2002 — APPROVED** [review]

**Comment by farie82** [comment]
Gonna close and reopen for the CI to hopefully work again

**Review by farie82 — CHANGES_REQUESTED** [review]
```
_maps/map_files/MetaStation/MetaStation.dmm:	step_x = -0.5;
_maps/map_files/MetaStation/MetaStation.dmm:	step_y = 6
ERROR: step_x/step_y variables detected in maps, please remove them.
```
Once those are removed, then the PR can be merged

**Comment by Bm0n** [comment]
Still missing the science request console. Also the donuts were not there in the old version, there's already a box of donks in the break room

**Comment by Johannes2262** [comment]
The console and the donuts should be added or respectively removed now, the step_xs and ys are also gone now.

**Comment by SteelSlayer** [comment]
@Johannes2262 could I have you update your branch with the latest upstream master? MDB is showing a lot of unrelated station-wide changes. Should hopefully make them go away.

**Comment by Johannes2262** [comment]
Should be fixed now, hopefully.

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
