### PR TITLE
OneHuman Module fix

### PR DESCRIPTION
**Pull request by CrAzYPiLoT-SS13**
Fixes: https://github.com/ParadiseSS13/Paradise/issues/654 Someone made
a really stupid error.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Did....did you even test this?

**Comment by CrAzYPiLoT-SS13** [comment]
Of course I tested it. Why?

**Comment by CrAzYPiLoT-SS13** [comment]
Status?

**Comment by Fox-McCloud** [comment]
This effectively prevents the card from being able to remove other zeroth laws...

**Comment by CrAzYPiLoT-SS13** [comment]
Uhm, it doesn't need to remove them, take a look at other zeroth law
modules. None of them have the statement I deleted, afaik. It doesn't need
to remove them, because it can just overwrite them. This actually removed
it's own zeroth law, the moment it was added.

2015-07-21 23:06 GMT+02:00 Fox-McCloud <notifications@github.com>:

**Comment by Fox-McCloud** [comment]
It's meant to remove zeroth laws though---andddd the others will not do that, I'm pretty sure (it even prints a special message to the AI when its zeroth law is attempted to be overwritten).

**Comment by CrAzYPiLoT-SS13** [comment]
Well, if that's the case, I don't know any other way that would fix this.

2015-07-22 14:40 GMT+02:00 Fox-McCloud <notifications@github.com>:

**Pull request closed without merging**
