### PR TITLE
Adds a sound when becoming a traitor to AIs, humans and IPCs

### PR DESCRIPTION
**Pull request by FreeStylaLT**
we had these lying around for a while, why not use them? they're pretty cool

Sound non-IPC traitors: https://my.mixtape.moe/mismpy.ogg
Sound for IPCs/traitor AIs: https://my.mixtape.moe/suzajg.ogg

### CODE REVIEW

**Comment by Twinmold93** [comment]
Cool sound is cool. And might as well use it, honestly.

**Comment by monster860** [comment]
Oh god those sounds are horrible.

**Comment by FlattestGuitar** [comment]
This is specieist.

Also, the sounds are hilariously horrible. Please don't use them.

**Comment by Twinmold93** [comment]
What, exactly, makes them horrible?

**Comment by FlattestGuitar** [comment]
They completely don't fit the style of ss13 and they sound super cheesy.

**Comment by NTSAM** [comment]
>ss13's style is super cheesy

**Comment by Twinmold93** [comment]
The style of SS13. It's a voice played (more likely than not through the headset for regular traitors) and internally (for IPCs). It's not utterly robotic, which is what I think is getting you.

**Comment by FlattestGuitar** [comment]
Meh, I guess you're right. This is something to get used to, so I won't mind after the first few times I hear it in-game. 

Still, super cheesy.

**Comment by Twinmold93** [comment]
I do note that it doesn't play this when you get auto-traitor or an admin makes you a traitor. Seems to be specifically for the traitor round-type.

**Comment by Fox-McCloud** [comment]
These are so bad.

**Comment by taukausanake** [comment]
It's sitting around there. Yeah I say use it. I think I like how horrible it sounds

**Comment by FreeStylaLT** [comment]
these are so bad they're great guys trust me :eyes: :wink:

**Comment by KasparoVy** [comment]
I thought the sounds were pretty dope, haha. Decently made with classic cheese. Cool to see them getting use.

**Comment by Krausus** [comment]
Wouldn't these end up overlapping the "Welcome to the station" VO? It looks like there's a random 1-10 second delay before round-start traitors get greeted, but that 1-second minimum would need to be bumped up a bit.

**Comment by taukausanake** [comment]
Maybe replace the sound that gets played for traitors? Might be a better choice I think

**Comment by ScratKnapp** [comment]
Could someone upload the sound files themselves? I don't know how to get access to them.

**Comment by FreeStylaLT** [comment]
@ScratKnapp done

**Comment by Vivalas** [comment]
These sound pretty cool, hope this gets merged without a shitfest of salt and drama over nothing,

**Comment by TheDZD** [comment]
Oh god those sounds are so cheesy.

**Comment by Kyep** [comment]
Too cheesy.

A simple beeping or other alert sound would do fine.

**Comment by FreeStylaLT** [comment]
you guys are totally lactose intolerant

**Comment by Spacemanspark** [comment]
Dammit

**Pull request closed without merging**
