### PR TITLE
Clown Piano

### PR DESCRIPTION
**Pull request by Deanthelis**
I'm flying mostly by the seat of my pants here, but everything compiled fine and it worked fine in local testing, so here's to hoping nothing strange happens.

This PR adds the Clown Piano to the game as part of the normal piano that appears in the Bar. There is a 25% chance each round at roundstart that the piano will be a Clown Piano instead of a Space Piano or Space Minimoog, because while people might want the Clown Piano some of the time, they probably won't want it all of the time.

The Clown Piano works exactly like the normal piano does for songs, etc. I didn't change any of that at all. The only differences are the sprites (one normal, one broken), which are both horrible abominations I drew and should probably be replaced eventually by someone who can make them look less horrid, at least as far as clown things go, and of course the sounds it makes, which are all bike horns.

Yes, that is correct, this PR adds a piano that produces songs composed entirely of bike horns. I had this idea ages ago, and decided to finally do it.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
*scream

in DD->build->references->uncheck automatically setting the FILE_DIR. Anyone who does has a PR that has the FILE_DR set will have a PR that will not get merged.

**Comment by Deanthelis** [comment]
Yeah, I figured I'd do something wrong somehow. Fill fix shortly.

**Comment by tigercat2000** [comment]
@Fox-McCloud we should probably add a grep or other such thing to the travis scripts to fail if file_dir is defined for anything but .

**Comment by Deanthelis** [comment]
Right, so, couldn't figure out how to revert properly because I'm terrible at git, closing and trying again. Whee.

**Pull request closed without merging**
