### PR TITLE
RnD autolathe removal + tech level overhaul

### PR DESCRIPTION
**Pull request by tigercat2000**
Remake of #7101 

Removes the roundstart autolathe from Science, the research division should be able to research the board and build it themselves (or just raid tech storage) rather than having it handed to them on a plate

Ports the tg RnD tech level rebalance, with many origin_tech of items changes, req_tech of designs changed to make RnD more interdepartmental, cooperative and less something that you can do just inside of science

The Experimentor can no longer raise tech levels of items, but discovering strange objects will now give them random tech levels which may be useful

The Exosuit Fab and Protolathe get their efficiency upgrades back, with the right upgrades making the costs of items lower again

RnD tech level skipping jumps 1 level further than before

Removes a few references to reliability, which was scrapped from RnD long ago

Adds an item to Cargo for Engineering research

The Destructive Analyzer will only prompt the user if deconning the item won't raise tech levels

Max tech levels for job objectives increased to 7 for all techs

Removed the forensic scanner from RnD and put it in a cargo crate

:cl:
tweak: Upgrading the Exosuit Fabricator and Protolathe with the right parts will lower item costs
add: Added an item to Cargo that RnD can use
tweak: Tweaks the tech levels for many items and the required tech levels for their designs. This is to make RnD more of a station-wide effort.
tweak: RnD tech level skipping skips 1 level further
tweak: The Destructive Analyzer will only prompt the user if tech levels will not be increased.
del: The Experimentor can no longer raise tech levels of items. It can however discover the tech levels of strange objects.
del: Removes the Autolathe from the RnD Room.
del: Removed the Forensic Scanner from RnD. Cargo can order a Forensics crate now.
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
An idea that I have had was to remove tech levels in the current sense, and instead make the system score based (research points?). Use those scores to unlock the tech you want. Higher tech items need more research points spent on them to unlock. You still keep the separate categories (can't apply plasma research points to biotech, for example).

In such a system, it makes it possible to use data from the tachyon doppler array in toxins for points, xenobiology slime cores, anomaly core research, various chemistry blends... all of this contributes to research. Same with experimentor data on strange objects, they too would contribute research points.

In general, the idea is that the science department as a whole contributes to research, not just "R&D".

I acknowledge this is a pretty major overhaul of the system, but just putting that out there...

**Comment by Birdtalon** [comment]
I like the idea but what is the intention for the experimentor to become if it can only discover strange objects and the other options become redundant?

**Comment by taukausanake** [comment]
Well seeing that no one really likes the experimentor, dead probably. Go the way of telescience maybe.

I like the research points idea but for another PR. Otherwise this PR seems like a needed change

**Comment by Spacemanspark** [comment]
We had telescience at roundstart a few years back... please, I beg you, don't put it back. Even then, it was used for validhunting to an extreme.

**Comment by taukausanake** [comment]
@Spacemanspark I meant kill the experimentor like how telescience ended out. As much as I'd like a feature in the game to be more available I more than understand no one wanting it around

**Comment by Spacemanspark** [comment]
Ah, alright.

**Comment by mrturkeytoe** [comment]
Don't like the experimentor gutting, makes science getting combat above 5 and max bio basically impossible assuming that combat is still reliant on the combat shotgun because security are paranoid comdom assholes and cargo are greedy bureaucratic assholes. And depending on how you've changed the bio levels I think it's impossible to max it unless you roll xenos?

**Comment by MasterrExploder** [comment]
After playing with this i have some minor complaints. Why remove the autolathe? it's just an inconvenience. Removing it really does nothing, beyond being lightly annoying. Using Structural Enzymes from Genetics also doesn't work, and kinda makes the engineering tech level totally reliant on cargo, for the machine prototype, and to make matters worse, anomalies are still broken. I actually like most of the changes, and how it encourages R&D to be less "have this done by 12:30 so i can implant myself with memes" and more of a station-wide, or at least multi-person job, but in it's current form it's just kinda harsh.

**Comment by mrturkeytoe** [comment]
Also not to rain on their 'fuck science' parade but if you can't get it done by thirty minutes it's probably not worth it beyond that point.

**Pull request merged**
