### PR TITLE
Unreverts Updates the technical names of BoxStation and DeltaStation

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do

Unreverts #27429. Should only be merged after an SQL script is run on the DB.

```
UPDATE round 
SET map_name = 'DeltaStation' 
WHERE map_name = 'Delta';

UPDATE round 
SET map_name = 'BoxStation' 
WHERE map_name = 'Cyberiad';
```
## Why It's Good For The Game

This shouldn't break things so long as the script is run.

## Testing

As before.
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

image

image

### CODE REVIEW

**Review by Burzah — APPROVED** [review]
Approved from original PR that was reverted.
Update statements within the PR description are good.

**Review by AffectedArc07 — COMMENTED** [review]
You able to dump the script in `tools/pr_sql/27431/script.sql` as well?

**Comment by AffectedArc07** [comment]
This can be merged once that script is put into `tools`. 

I can retroactively run it.

**Comment by Bm0n** [comment]
> You able to dump the script in `tools/pr_sql/27431/script.sql` as well?
This should be done now.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
