### PR TITLE
[META] [DNM] Adds lighting on Wizard's Den, Fixes disposal blast door not opening

### LINKED ISSUE #7573: [META] disposals mass driver
The disposals mass driver on meta station has a messed up tag for the blast door, the driver itself fires but since the doors never open nothing gets fired out.

### LINKED ISSUE #8517: Metastation Wizard Spawn has no lights
**Problem Description**:
No lights in Wizard Spawn. At all.

**What did you expect to happen**: 
To have lights..

**What happened instead**:
See title

**Why is this bad/What are the consequences:**
THE BLINDNESS. And the murder monster that would be nice to be able to see.

**Steps to reproduce the problem**:
Load Metastation map. Spawn as Wizard.

### PR DESCRIPTION
**Pull request by Shadow-Quill**
**What does this PR do:**
Closes #8517
Closes #7573

**Images of sprite/map changes (IF APPLICABLE):**

image

**Changelog:**
:cl:
add: Added lights to Wizard's den on Meta.
fix: Fixed the disposals mass driver door not opening on Meta.
/:cl:

### CODE REVIEW

**Comment by BakKeener** [comment]
reminds me of all the abandoned areas in meta station, but as for why the wizard den has no lighting... beats me but it'll be nice to have when we play meta station that one time and wizard happens to roll

**Comment by Fox-McCloud** [comment]
This should probably use some form of light that isn't actually light bars---it's a spoopy area; having machine lights kinda breaks that a bit.

I believe we have lights that you can't see.

**Comment by Shadow-Quill** [comment]
I'll check tomorrow then move these changes over to #12029

**Comment by Shadow-Quill** [comment]
done and moved

**Pull request closed without merging**
