### PR TITLE
Bag of Holding Tweak

### PR DESCRIPTION
**Pull request by Fox-McCloud**
From TG

- Buffs the Bag of Holding's max weight class from 4 to 5
- Buffs the max combined weight class from 28 to 35 (default backpack is 21)

:cl: Fox McCloud
tweak: Increases bag of holding's storage capacity
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
What even uses w_class 5?

**Comment by Fox-McCloud** [comment]
>What even uses w_class 5?

A few guns (LMG, turrets, etc), bo staff, magic wands, and a couple of other things.

**Comment by ScratKnapp** [comment]
I assume you mean magic STAFF, as wands can be pocketed and have a few uses. Staves are infinite use but are too large for backpacks and likely class 5.

Otherwise, :+1:  It's meant to be able to hold just about everything, after all.

**Comment by TullyBurnalot** [comment]
Does this mean we can carry Defibs in BoH now?

**Comment by ProperPants** [comment]
Does this mean we can carry literally anything in BoH now? Is there any holdable item beyond weight class five?

**Pull request merged**
