### PR TITLE
Remove random pod door near white ship start point

### PR DESCRIPTION
**Pull request by Crazylemon64**
That always annoyed me.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
not mapmerged =V

**Comment by tigercat2000** [comment]
are you sure it's random and not accidentally fallen off of the white ship

**Comment by Crazylemon64** [comment]
random_door

Doesn't have a corresponding blast lock or endpoint walls, and maintains animation. Is it intended to be detritus?

**Comment by tigercat2000** [comment]
No, it's probably just me being bad at mapping. Also, you know, something to make mapping 90% less laggy and 200% easier; Go to the layers menu, click 'only show selectable layers' or something along those lines, then click on the checked 'area' thing to hide areas.

**Comment by TheDZD** [comment]
You need to mapmerge the changes before we merge the PR.

**Comment by Crazylemon64** [comment]
Ah, how would I mapmerge? The <a href=http://nanotrasen.se/wiki/index.php/Guide_to_Mapping>Guide to Mapping</a> doesn't carry any information on that topic

**Comment by TheDZD** [comment]
You would have to undo the map changes that you've made completely (so that no git diffs show up between your map and the one on live), run the prepare_map.bat file in tools/mapmerge, redo the changes, save them and close Dream Maker, and then run the clean_map.bat file in the same folder.

**Comment by Crazylemon64** [comment]
I think this might have made the problem WORSE. Hmm, I might need to try this on the windows end.

**Comment by Fox-McCloud** [comment]
When it comes to map stuff, sometimes it's easier to just re-make the PR entirely.

Considering this would be a remake, it could be merged as soon as Travis passes (especially since it's a fix).

**Comment by Crazylemon64** [comment]
Ah, looks like it's better now. I managed to get it much more condensed, there was something nasty going on with unix and DOS line endings

**Pull request merged**
