### PR TITLE
Runtime error fix

### PR DESCRIPTION
**Pull request by Bram961**
Hopefully this fixes the error:
runtime error: Cannot read null.ambience_playing
proc name: Entered (/area/Entered)
source file: areas.dm,388

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Might want to test this locally to see if that really does fix it.

**Comment by Krausus** [comment]
I took a peek at the line that's runtiming:

`if(!L.client.ambience_playing && L && L.client && (L.client.prefs.sound & SOUND_BUZZ))`

`L && L.client` should be *before* `!L.client.ambience_playing`, to make sure `L.client` actually exists. The runtime occurs when it doesn't.

To be more specific, the runtime occurs when a mob owned by a disconnected player enters a new area. Such a mob will have a `ckey` (passing line 383), but not a `client`, which is why it's important to make sure `client` isn't null before trying to use it.

**Comment by Fox-McCloud** [comment]
@Krausus 

That makes a lot more sense. Thanks.

**Comment by Bram961** [comment]
Ah right, I completely missed those things having a specific order. Ill change it.

**Comment by Bram961** [comment]
thanks @Krausus

**Pull request merged**
