### PR TITLE
Buffs rapier throwforce

### PR DESCRIPTION
**Pull request by jughu**
from 10 to 20 incase your CRAZY enough to throw a rapier at the enemy

### CODE REVIEW

**Comment by jughu** [comment]
this is a valid combat technique if you just throw juuuuust right :)

**Comment by jughu** [comment]
auctally 17 is better

**Comment by jughu** [comment]
your supplementary video
https://www.youtube.com/watch?v=wTC_1HRgbuo

**Comment by Fox-McCloud** [comment]
But..why.

**Comment by jughu** [comment]
Because my immersion is hurt
Throwing swords can be strong if used right

**Comment by IcyV** [comment]
It's already a pretty strong weapon in the first place. Not really sure it needs more.

**Comment by jughu** [comment]
Its strong melee and it has a big risk to be used against you when thrown
So big risk big reward

**Comment by TheDZD** [comment]
> It's already a pretty strong weapon in the first place. Not really sure it needs more.

Pretty much this.

**Comment by TullyBurnalot** [comment]
Its a bloody rapier that works... like a rapier. No point turning it into a viable spear.

**Comment by jughu** [comment]
You would really think throwing swords would do more damage when thrown since embederini this was a legit mediaval tactic

**Comment by FlattestGuitar** [comment]
If someone uses this strategy they deserve props for not getting themselves killed soon after.

This PR is :+1:

**Comment by jughu** [comment]
@IcyV  if you mean by stronger having 2 extra brute by throwing it and having a embed chance or the weapon being used against you then yes dont forget in mediaval times poeple did this wgen the opponoment doesnt expect it because it could be catched

**Comment by Fox-McCloud** [comment]
>

    It's already a pretty strong weapon in the first place. Not really sure it needs more.

Pretty much this.

**Comment by jughu** [comment]
@Fox-McCloud 

Then can the throwforce atleast be 15 eqauling to the melee and i dont really see how it can be strong when thrown for 2 extra brute since it can be used against you

**Comment by Plotron** [comment]
https://youtu.be/wTC_1HRgbuo

I don't think this rapier would be a good throwing sword.

**Comment by Fox-McCloud** [comment]
Don't really think this weapon needs buffed, at all.

**Comment by jughu** [comment]
Im a big meme

**Pull request closed without merging**
