### PR TITLE
Adds 19 new nanomeds(the wall ones) to delta

### PR DESCRIPTION
**Pull request by 1080pCat**
## What Does This PR Do

Pretty much the title, adds 19 nano meds semi randomly around the station, mostly wherever made sense/looked good.
## Why It's Good For The Game

Did you know delta has 5 nano meds? 4 being inside medical, one in med maints? yeah. this changes that. 
~~I've added roughly 2-3 nanomeds per department/department sector, give or take, i wasn't really following any order while doing it.~~
Since lowered to 1 per department, unless its in a particularly hazardous area, mainly in atmos, toxins, and theres still two in departures since the little sec room makes sense to have another. 
## Images of changes

<details>
<summary>19 images, be warned.</summary>
<br>
Departures

image

Toxins

image

Engineering, tesla room

image

Bridge

image

Far left arrivals hallway 

image

Departures security room

image

Maints bar/rage cage

image

Science, right outside the experimenter room

image

Port primary hallway, sandwiched between primary tool storage, and technical storage

image

Possessing

image

North atmospherics

image

Inside that strange small surgery room, in fore secondary maints

image

Dorms/locker rooms

image

Engineering foyer

image

Mining dock

image

Fore primary hall, outside bar

image

Perma

image

And finally, expedition room

image

</details>

## Testing

compiled, looked around at the new nanomeds.
## Changelog
:cl:
tweak: Added 19 new nanomeds across delta station.
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
I think "tweak:" fits more than "add:" over your changelog.

**Comment by Henri215** [comment]
**ISSUES**
image
One inside the CMO office? Its a mistake?

image
You didnt remove the ones it had in medbay?

**BELOW IS IN MY OPINION**
I personally dont think adding it to maints is necessary, unless it has a certain theme (it feels a bit out of place) the hallway ones are public enough for anyone to access.

I think you added too many to departments, one should be enough for most cases in my opinion.

**Comment by 1080pCat** [comment]
> **ISSUES** image One inside the CMO office? Its a mistake?
> 
> image You didnt remove the ones it had in medbay?

i didn't touch medicals nano meds, no. Though i can remove them if need be.
Also i'll lower them to one per department when i have time, unless its in a particularly hazards area, like atmos.

**Comment by 1080pCat** [comment]
Sadly going to close this, as the window de-grilling PR stealth conflicted, and i do not have the current desire to pretty much redo this.
I might re-open it at a later date

**Pull request closed without merging**
