### PR TITLE
Updates nanoui map to latest station version

### PR DESCRIPTION
**Pull request by Citinited**
Because this hasn't been done since before the incinerator maintenance was redone.

:cl:
imageadd: NanoUI will now display the latest version of the NSS Cyberiad.
/:cl:

Please don't shoot me for the duplicate PR, I screwed something up ;_;

### CODE REVIEW

**Comment by Citinited** [comment]
Wonder why this is Do Not Merge...

**Comment by taukausanake** [comment]
Maybe because the map might change or something? Possible

**Comment by Citinited** [comment]
Speaking of map changes, Brig remap 2.0. I'm guessing that's why it's Do Not Merge?

**Comment by taukausanake** [comment]
Should have Waiting For Clean Shot At Map tag instead then

**Comment by Citinited** [comment]
Heh. I asked Fox about it and apparently they're trying to reach a concensus on some things for maps, so anything map-related is on hold.

**Comment by taukausanake** [comment]
Looking at the commit, this looks like the map that Norgad made in #6076 and reverted in #7139. This might be closed either way. A new PR would be made instead when the map is updated.
It might be a good idea that when map edits like this are made we have a means to make the nano map for it

**Comment by Crazylemon64** [comment]
@Citinited go go go!!!!

**Comment by Citinited** [comment]
Closed as Mars ended up adding the brig bit for me 👍

**Pull request closed without merging**
