### PR TITLE
Adds full cycling functionality to the Arrivals Trader Airlock & AI Sat

### PR DESCRIPTION
**Pull request by SamHPurp**
This brings this airlock into the same standard as all other external airlocks with fully functional cycling. This has been left all access, as it has been, so balance isn't affected.

image

image

This also makes a few more small tweaks necessary for #7213 @Allfd 's  atmospherics improvements PR, such as anchoring the Canisters in Atmos. No image because nothing visually changes, nor will it ever come into effect without the atmos changes....

:cl: Purpose2
tweak: The Arrival's Trader Dock now cycles properly.
/ :cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Why are the canisters anchored? Isn't that inconsistent behavior? All other canisters can be moved, as far as I know.

Can you unwrench these somehow?

**Comment by SamHPurp** [comment]
@FlattestGuitar yep a simple wrench will do it.

Its to stop the atmos cannisters from being chucked around the atmos holding tanks.

**Comment by deep-fried-faceplant** [comment]
I always thought that airlock having all access was an oversight. Doesn't make sense for the station to have a public airlock, when there's no reason for the average crewmember to go EVA without gear. Even spaceworthy races shouldn't be jumping through the airlock without reason. A public airlock with no publicly available EVA gear just doesn't make sense.

If the airlock is all access for traders, that's like keeping the front door unlocked at all times because you're expecting a package sometime this week. If the airlock is all access for antagonists, there's no reason to make their job easier with an inconsistency. There's plenty of airlocks and windows that can be broken or hacked anyways, better for antagonists to leave a mark when they're trying to go EVA.

Aside from that, +1 for bringing this airlock up to speed with cycling.

**Comment by SamHPurp** [comment]
@deep-fried-faceplant its been all access to that the Sol Traders that dock, can access the station.

I'm not touching this, purely because that'd be out of scope of my intention - however I do understand where you are coming from, and entirely agree.

**Comment by pinatacolada** [comment]
can you hide the canister in the maintenance to the right of the pods? iirc these airlock canisters have been tucked away into maintenance

**Comment by SamHPurp** [comment]
I can hide it in the escape pod bit above, not a problem. Just think its a little bit messier that way. Will leave it for a Headmins decision on there or in the maintenance bit above.

**Comment by Kyep** [comment]
I don't think we should have cycling airlocks, anywhere.

They're slower, and more cumbersome, than normal airlocks.

They offer no benefits over normal airlocks.

They have no reason to exist.

**Comment by Anticept** [comment]
They will matter in the atmospheric update. Otherwise people will get thrown out or unable to get inside. Not just on station, but places like mining.

If they are slow (they are), then they should be fixed. For one, it would be nice if they didn't rely on the atmospheric simulation to move air. The vents used should be able to fill and drain all tiles neighboring as well as their own at once, and you would SIGNIFICANTLY SPEED THEM UP.

**Comment by SamHPurp** [comment]
> They're slower, and more cumbersome, than normal airlocks.
Single tile airlocks like the one built approx 3 seconds of cycle time? If pressure is already at safe levels, it'll insta open for you... and if you are in it already, you can force the doors open anyway with the controller.

> They offer no benefits over normal airlocks.
They stop depressurization of the tiles nearby on the station. And if/when the upgraded LINDA comes in, this'll make it possible to actually get back into the station without magboots... and also stop you from being instantly chucked into space when you intentionally leave it.

> They have no reason to exist.
See above, this is wholly false.

**Comment by Twinmold93** [comment]
Kyet, with upgraded Linda it has every reason to exist. However, in order for this airlock to work you had to change a few things, unless you left the doors alone, in which case it won't work as intended anyway. If you changed the tags on the doors, it won't work when the traders arrive. Personally, I feel while the doors should remain all access accessible, the control Burton's should still be exterior access licked.

**Comment by Kyep** [comment]
Why not simply reduce timing on the two doors? That would stop atmos issues without requiring use of an airlock controller/button.

**Comment by SamHPurp** [comment]
@Kyep that is entirely false. You will still get utterly ejected from the station, or blocked from entering it.

I do not mean this in an offensive way, but have you had a chance to try out the new LINDA yet?

**Comment by Anticept** [comment]
Again... for all the airlocks that cycle slow as hell... we just need to add more vents. I believe dual port vents are working again, so why not use those? You can easily stuff a room full of vents without a a crazy elaborate piping network.

**Comment by Fox-McCloud** [comment]
Conflictsss

**Comment by SamHPurp** [comment]
Having some real issues with map merge... will try again this evening....

**Comment by SamHPurp** [comment]
@Fox-McCloud @Allfd Fixed the map conflict. Forgot to push with `-f` after updating it with the current map.

**Comment by SamHPurp** [comment]
Fixed conflicts again...

**Comment by SamHPurp** [comment]
@Fox-McCloud as you were asking about conflicts 12 days ago, does this mean this is ready to go?

**Comment by Kyep** [comment]
I never thought I'd see the day when we add a cycling airlock, and it is an improvement.

**Comment by SamHPurp** [comment]
reeeeeeeeeeeeeee

**Comment by SamHPurp** [comment]
Do I seriously have to fix conflicts a 6th time.

**Comment by tigercat2000** [comment]
If you want to be technical about it, the AI satellite has a non-cycling airlock too...

**Comment by SamHPurp** [comment]
@tigercat2000 ... if I fix the conflicts for a 6th time, and include that, can I not have to fix the goddamned conflicts a 7th time? :(

**Comment by SamHPurp** [comment]
C'mon dudes.

**Comment by Fox-McCloud** [comment]
Going to go ahead and merge; eventually, though, cycling airlocks will *probably* be killed off in favor of an auto-open/auto-close system that emulates cycling airlock behavior.

ie: open external door, it auto-closes the internal one. Open internal door, it auto-closes the external one.

**Comment by taukausanake** [comment]
@Fox-McCloud With whatever atmos system we end up having I'm pretty sure we'll need doors that operate exactly how we have them as is, if not a lot kinder to mappers and such. You'll need to have both doors closed in order to get through, not closing/opening at the same time. Surely there must be a better way to make the airlocks work? Maybe have them share IDs while in the same area?

**Pull request merged**
