### PR TITLE
File standardisation

### PR DESCRIPTION
**Pull request by AffectedArc07**
# NOTE FOR WHOEVER REVIEWS THIS
Please enable whitespace hiding as that will make all the files show as whitespace only changes, which are what all these changes are. It will still show files with actual code changes, hence the change in travis and the python script. 
image

I also recommend closing anything that isnt chrome if you are short on RAM
image

## What Does This PR Do
This PR does the following things
- Sets all files to use LF line endings
- Sets all files to have a trailing line at EOF
- Adds an `.editorconfig` file to auto-enforce these rules
- Adds `EditorConfig` to the list of recommended vscode extensions

## Why It's Good For The Game
Having standardised code is a benefit for many reasons, but the main one I am pushing to fix with this PR is file merge conflicts. Whenever a PR goes through which has changed line endings, it needlessly conflicts other PRs. The same also goes for newline changes at the end of files. This PR will make those conflicts a thing of the past.

## Changelog
:cl: AffectedArc07
tweak: All files in the codebase are now LF, with trailing newlines
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
whats a `LF line ending`?

**Comment by Gatchapod** [comment]
> 
> 
> whats a `LF line ending`?

Standard newline method for Unix and Unix-like systems.
Windows and some other systems use CRFL for their newline.

What this PR does is basically properly ensuring every single file ends with the same kind of EOF, first by setting the standard for newline and then ensuring all files end with a newline.

It's mostly inconsequential for actual coding, but invaluable for running many kinds of scripts that care about what type of newline is deployed and where EOF is.

**Comment by Citinited** [comment]
An Excellent PR

**Comment by AffectedArc07** [comment]
Conflicts will remain unresolved until maints decide they want this in, because I wish to avoid many excess merge commits.

**Comment by AffectedArc07** [comment]
DM works as an editor still, and the reason for using LF is that I have tried to write scripts for CI runs which used CRLF files, and I kept running into issues when reading the files in and having extra `\r` characters, and when making external tools for the game. LF seems to work better __in my past experience__.

**Comment by taukausanake** [comment]
For those of us who tend to keep an up-to-date branch with edits on it, and I'd imagine any downstreams that pull fixes and such from Paradise, is there any easy way  to fixing the MASSIVE AMOUNTS OF CONFLICTS WE HAVE NOW? I have entire files that are diff-ed and have to go through each one to find out what is mine and what should be actually pulled. It's really depressing

**Comment by Kyep** [comment]
@taukausanake Yes. Check the top pinned message in coding-chat on our discord server. It has a detailed, page-long step-by-step guide as to how to update your stuff with minimal (not zero, but minimal) effort.

**Comment by taukausanake** [comment]
Funny thing about that. I was kicked like a year ago and never bothered to rejoin. Could someone send me a PM with the instructions please? Or maybe post it somewhere else?

**Comment by Kyep** [comment]
@taukausanake Login to the actual game and hit the "Discord" button. The link differs based on your account.
You should probably also hit the 'Forum' button and activate the forum account you have.

**Pull request merged**
