### PR TITLE
New sprites for mugs (there is sprite in my mug)

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Resprites mugs

## Why It's Good For The Game
Guess yourself

## Images of changes
image

## Testing
I got mugged while testing this

## Changelog
:cl:
imageadd: New sprites for mugs
/:cl:

### CODE REVIEW

**Review by Henri215 — CHANGES_REQUESTED** [review]
image
Rainbow mug animation is not finished.

**Comment by DGamerL** [comment]
> image Rainbow mug animation is not finished.

Dw it 
image

**Comment by McRamon** [comment]
ffs

**Comment by McRamon** [comment]
> image Rainbow mug animation is not finished.



> > image Rainbow mug animation is not finished.
> 
> Dw it image

fixed

**Review by Henri215 — APPROVED** [review]
Lewcs Good To Me now, nice rainbow animation.

**Review by DGamerL — APPROVED** [review]
I'll see if I can make them have the reagent overlays in a later PR!

**Review by S34NW — APPROVED** [review]

**Pull request merged**
