### PR TITLE
Updates darkmodes theming to more closely match Bay

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Updates darkmodes theming to match Bays which is overall a better version of darkmode

Darker bits are a little darker especially up in the status panel, themes better with the chatbox now.

All chat colours have remained unchanged except for the default chat colour which includes say and the announcement colour. Basically, if it was bright ass #FFFFFF white before it's gone and now replaced with a white blue, kind of like the same colour you have here on Github darkmode but a little bluer to compensate for it being on a darker background.

These changes are from Baystation.

## Why It's Good For The Game

Please for the love of all that is good in this codebase my eyes bleed every time I switch on darkmode and am flashbanged by a half white half dark chatbox. I want a darkmode, not an inverted colours mode.
## Images of changes

parabay

image

## Changelog
:cl: Bmon, BS12
tweak: Goonchat has been tweaked to match BS12's darkmode. No more bright white!
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
When do we get support for custom fonts, icon increases, etc?

**Comment by Bm0n** [comment]
> When do we get support for custom fonts, icon increases, etc?

literally already a thing.

also, this isn't a suggestion thread, this is a PR

**Comment by Calyxman** [comment]
> > When do we get support for custom fonts, icon increases, etc?
> 
> literally already a thing.
> 
> also, this isn't a suggestion thread, this is a PR

Keyword being custom, I was wondering if you or someone else was making it actively though

**Comment by Bm0n** [comment]
> Keyword being custom, I was wondering if you or someone else was making it actively though

Can you make a suggestion thread on the forums please?

**Review by Sirryan2002 — APPROVED** [review]
css/style on this is much better than what we have IMO. This is more "darkmode."

Also all the code looks good, just value changes

**Review by SteelSlayer — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
