### PR TITLE
Gives the mime his very own door and ports /tg/ mime backpack

### PR DESCRIPTION
**Pull request by Artorp**
- Adds a new mime door
 - Door uses the freezer icon
 - Door has no open/close sound
- Ports over /tg/station mime backpack (https://github.com/tgstation/-tg-station/pull/3247)

### CODE REVIEW

**Comment by SamCroswell** [comment]
Could we get pictures of it?

**Comment by Markolie** [comment]
:thumbsup:

**Comment by Artorp** [comment]
Sure, here:
untitled

Uses the same sprite as the kitchen freezer, functionality wise only difference is the sounds (and access etc).

Maybe I should, the clown has a clown backpack, it would only be fair for the mime to get some unique stuff!

**Comment by Fox-McCloud** [comment]
I second the idea of porting over the Mime's backpack from TG.

**Comment by Artorp** [comment]
Looks solid on the local server, ready to merge if Travis gives green light.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by Artorp** [comment]
Question, should the mime backpack be mandatory? The Clown's currently is. If it is, people who prefer satchels don't have to change their option to backpack in case they happen to spawn in as the mime.

**Comment by Fox-McCloud** [comment]
If it's mandatory for the clown, then it should be for the mime, as well.

Also, the costume crate (the one that has the clown backpack in it) will also need the mime backpack.

**Comment by Markolie** [comment]
Going to merge this now as to avoid conflicts with the next two big PR's.

**Pull request merged**
