### PR TITLE
Not tranqualiser

### PR DESCRIPTION
**Pull request by shazbot194**
This PR renames tranqualiser darts to anti-stimulant darts, as the darts do not contain tranqualisers, but rather anti-stimulant. They are meant for meth heads, not for traitor Joe who just has a .357. 

🆑 Shazbot
Changes: Changes tranqualiser darts's name to anti-stimulant darts.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
I perfer tranquilizer as the intent is the same, calm someone the fuck down.

**Comment by shazbot194** [comment]
Even then, this gives a much better idea on what these are meant to be used for, as they can cause brain damage when used on someone, which isn't something that should be taken as lightly as tazing someone, not to mention they suck as tranquilizers, only working some of the time, and never long enough to put cuffs on someone.

**Comment by Aurorablade** [comment]
https://en.wikipedia.org/wiki/Haloperidol
for all intents and purposes its used for emergency sedation. IN REALITY there are better drugs for it..in ss13..its a sedative and anti-psychotic in use. The therapist has it in the locker.

Its a tranq, with side effects if abused. Thus why we try to keep people from abusing it.

**Comment by shazbot194** [comment]
From our in game description of the pills

> desc = "Haloperidol is an anti-psychotic use to treat psychiatric problems."

From our in game mechanics

> <removes all the fun drugs>
> if(prob(50))
> 		M.Drowsy(3)
> 	if(prob(10))
> 		M.emote("drool")
> 	if(prob(20))
> 		M.adjustBrainLoss(1)
> 	..() 

So while yes, it is a very weak tranquilizer, only causing drowsiness half of the time, it is a much much much stronger anti-stimulant, hence why it should carry that name instead.

**Comment by Aurorablade** [comment]
the proper solution may just be to make a new reagent or change what the chem does instead of renaming the entire thing.
Tranqs are supposed to make you drowsy and it may trigger more often then people think, as its a 50 percent chance, thats a pretty high chance to be honest. Its enough to stop someone dead when it counts while providing some room for the person to get away.

**Comment by shazbot194** [comment]
I do agree, but it is much more useful as a anti-stimulant when there are better tranqs out there, ranging from unobtainable like sodium_thiopental or ketamine, to obtainable ones like sulfonal (slightly toxic) or capulettium, all of which do a better job at letting the person get away while being a more effective tranquilizer.

**Comment by Aurorablade** [comment]
Those are stronger does and more needing of a chem mix. This is something to provide on a round start basis.
Plus anti-stimulate dart is a mouthful and too technical then just saying tranquilizer dart.

**Comment by shazbot194** [comment]
I personally don't think anti-stim dart is too hard to say, not anymore then tranq dart. I would like to say both sulfonal and capulettium are extremely easy to make, I'd say on par with Haloperidol, if not even easier to make, with a window without it being RNG, allowing for a predetermination amount of time before the drowsiness takes hold. With capulettium taking 6 ticks, and sulfonal taking 11 ticks,

**Comment by shazbot194** [comment]
I would like to note, I am more then open to shifting this PR from renaming the tranquilizer to putting a different chem, I just do think that security might have more use for a anti-stimulant that is easy to tell apart rather then a tranquilizer, as I have met a lot of veteran officers who thought they had proper tranquilizers, in that they put people to sleep.

**Comment by Birdtalon** [comment]
>Plus anti-stimulate dart is a mouthful and too technical then just saying tranquilizer dart.

All I would really point out is this. "Anti-stimulant darts" sounds a bit silly.

**Comment by Kyep** [comment]
Better to sound silly but be accurate, than to sound normal but be misleading?

**Comment by taukausanake** [comment]
It's not too misleading. Not completely. For me it's tough to pick one argument over the other as they are both fair. Maybe tranq dart is a better choice though but another chemical might not be a bad idea either

**Comment by Ty-Omaha** [comment]
Why not just replace it with ether

**Comment by shazbot194** [comment]
That could work, but it takes 16 ticks before it makes someone drowsy.

**Comment by uraniummeltdown** [comment]
Anti-stimulant just sounds stupid, if you must change it make it antipsychotic

**Comment by Dinarzad** [comment]
The opposite of a stimulant is a Depressant.
That's probably going to sound just as funny shooting people with Depressants, but still maybe there is something there to work with, as it is literally the antonym of "Stimulant"

**Comment by Squirgenheimer** [comment]
the desc of the dart clarifies this enough I think

**Comment by shazbot194** [comment]
I don't really feel like waiting anymore to hear about this, nor do I feel like fixing the conflicts, so I will be closing this PR down, if you wish to remake it, go right on ahead.

**Pull request closed without merging**
