### PR TITLE
New Biochip Activation Icons

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
Ports ~~implant~~ biochip activation icons [from TG](https://github.com/tgstation/tgstation/pull/66213).

## Why It's Good For The Game
Some of our biochip icons are quite rough, this improves most of them.

## Images of changes
**OLD**
image
**NEW**
image
image
image
image
image
image
image

## Testing
Loaded in and injected myself with the implants.

## Changelog 
:cl: Comxy, PacifistDalek
imageadd: New implant activation icons
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Are the animations from freedoms and explosive implants always playing? That seems like it could be a little distracting.

Also rip stickman o7

**Comment by Dafrek** [comment]
I kind of prefer some of the ones we have now, especially the freedom and explosive ones, but the regeants, adrenal and storage ones look like an improvement.

**Comment by AffectedArc07** [comment]
The adrenals one is great, however, I dont like icons this flashily-animated as action buttons, as it could get somewhat distracting from ingame.

**Comment by S34NW** [comment]
> The adrenals one is great, however, I dont like icons this flashily-animated as action buttons, as it could get somewhat distracting from ingame.

Can it be a "play-on-hover" system? I bet it can, that would make it much less problematic.

**Comment by PacifistDalek** [comment]
Turns out @McRamon has another set of new ones almost ready to go that avoid some of the issues here, so i’m gonna close this for now!

**Pull request closed without merging**
