### PR TITLE
Add in banangarang's fluff cyborg sprite

### PR DESCRIPTION
**Pull request by variableundefined**
This PR adds in banangarang's maid bot sprites. Here's the gif:

EDIT: Updated

🆑:
add: banangarang's maid bot fluff sprites
/🆑

### CODE REVIEW

**Comment by giblinator1337** [comment]
uh

**Comment by taukausanake** [comment]
You messed up on the blue one. Also the gif doesn't show the blue either.
image

I like it. It looks so cute :heart:

**Comment by BanangArang** [comment]
Whoops, didn't notice that one of the sprites was wrong for Medic.  I'll talk to the artist I got it from and see about it getting replaced real quick.  

And the GIF is wrong, yeah.  But you get the general idea it's supposed to be like!

**Comment by variableundefined** [comment]
The DMI has been replaced

**Comment by TravellingMerchant** [comment]
It was fun working on these! I hope everything goes well!

**Comment by BanangArang** [comment]
The medical borg's back and side sprites are a little off, if someone could update it at some point that'd be great.  
https://cdn.discordapp.com/attachments/476038679547215872/477168543151161346/Robo-Maid.dmi

**Comment by taukausanake** [comment]
I don't see anything wrong with it. What's off on the blue back?

**Pull request merged**
