### PR TITLE
Increase ambulance speed

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Increase ambulance base speed, and makes it even faster when the siren is on. You've got patients to treat, after all!

## Why It's Good For The Game
At least from what I've seen, the ambulance is miserably slow. There's no real reason to use it beyond RP, and it's honestly just as fast to walk on foot with the roller bed behind you. The purpose of the paramedic is to get somewhere as fast as possible, and a speedy ambulance gives them more of a reason to be the one who goes out and saves the day.

## Images of changes
https://user-images.githubusercontent.com/89928798/139689636-d77d47be-ee2d-4833-92c5-287bc4e4224a.mp4

## Changelog
:cl:
tweak: Ambulance base speed is now faster.
tweak: Ambulance now moves even faster when the siren is on.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
speed is absolutely busted in terms of combat viability. add in that a vehicle removes damage slowdown and this could be VERY scary if you have a gun (say a .357 or stechkin + a shield). I do wish the ambulance was better, but making it THAT large of a speed bonus might be a bit meh balance wise.

perhaps keep it at normal playerspeed for lights-off and slightly higher for lights-on?

**Comment by Gatchapod** [comment]
I don't think it will pass.
A vehicle that can block shots for you and allows you to outrun all officers?
_Maybe_ if you added something like EMPs breaking it, so security can actually fight paramedic antags.

**Comment by lewcc** [comment]
Drafting for now, I think the ambulance really needs a speedbuff so I'd like to make sure it happens, but I definitely want to make sure it's done *right*

**Comment by lewcc** [comment]
https://user-images.githubusercontent.com/89928798/139695115-de6884ca-26bd-4668-a04e-019a6477344e.mp4

Reducing the speed so it's a little less obnoxious. Wasn't aware vehicles were nerfed deliberately, that's kind of a shame.

**Comment by Leanfrog** [comment]
I'm going to note that the ambulance used to be equal to or faster than crew in the past, I can't recall exactly which, but it was nerfed because vehicles were actually very strong for combat purposes, they shift your melee hitbox and as mentioned here previously make you ignore damage slowdown a very large factor of combat.

**Comment by lewcc** [comment]
Ambulances now drop below walking speed if they're hit by an EMP, which should hopefully provide a method of dealing with them.

That being said, I'm seeing that I wasn't really aware of the sheer power of fast vehicles. As much as I'd love to see the paramedic not be stuck with an awful ambulance, I'd be happy to shelve this idea for now until some sort of vehicle rework happens.

**Comment by Sirryan2002** [comment]
Ambulance should probably only be a tad bit higher than normal player speed. It already provides slip immunity and prevents people from bleeding out from being dragged. I don't mind it getting a little speed boost but anything over a small buff is going to make this a major target for antags who want some speed and will take away from the intended purpose of this PR.

**Comment by Fox-McCloud** [comment]
So, this used to be the case, but it was deliberately lowered, because, as others have already elaborated.

People would take this or sec would commandeer it to hunt antags because it removes all slowdown.

Anti-slowdown is generally find for things that have effort or that are slower than normal speed, but something that's round-start available gets pretty iffy.

**Comment by Hematoma** [comment]
Couldn't you just make driving the ambulance fill your hands I.e with the handle bars. I am not sure how your supposed to be driving as it is with no hands. The paramedic should get off to treat patients anyway. The ambulance dose take damage/can be destroyed, and I'm not sure there is a way to repair it so the damage will accumulate. Another thing you can do would be to make the ambulance a trackable item like the Janitors items are with the Custodial Locator. As is the ambulance is practically a useless item, and dragging just the ambulance cart now looks weird because you face backwards when pulling.

**Pull request closed without merging**
