### PR TITLE
The Great Del() Cull of 2015

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Replaces most del()'s with qdel()'s

there's still quite a few del()'s left; I generally tried to avoid things that seemed iffy (client related), I knew didn't work well (stacks), or a few other related stuff (map suite). I tried to error on the side of being conservative, but eh. I also avoided files I knew others were working on (update icons, mining, etc).

Requesting review by @Krausus @TheDZD  @tigercat2000  and @ZomgPonies if possible.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
did a second pass to catch all the `del <thing>`'s that exist

**Comment by Krausus** [comment]
Well... it doesn't seem practical to try and look through 830 individual changes, so I'm going to assume this doesn't cause any glaring problems in testing, and that we'll probably be able to fix any others that crop up.

A couple things worth checking, though:
* Make sure cyborg stacks still properly delete when they're used up.
* Make sure you can unwrench pipes without the pipenet doing anything weird, like not realizing the pipe is missing.

**Comment by Fox-McCloud** [comment]
I generally attempt to leave stacks a lone; I'm sure there's some, but I avoided *most* things in stack.dm and the children files. There's still a few here and there floating around, but I'll test it.

Any thing in particular to look for *specifically* with pipes--what kind of odd behavior, exactly?

**Comment by Fox-McCloud** [comment]
Oki doke, think this is ready to merge now.

**Pull request merged**
