### PR TITLE
Skrell & Taj Hardsuit Recolor

### PR DESCRIPTION
**Pull request by Agameofscones**
Moves the last _few_ racialized hardsuits away from the old Bay12 palette and onto the updated Paracode palette. No more security Skrells & Tajara looking _almost_ like nuke-ops.
**Old**
image
**New**
image
**Old**
image
**New**
image

Has helmet lights (with alpha layering). Tested in game, etc.
Will edit on request.

It appears Taj suits are also on the wrong palette as well. Will update shortly.

:cl: Triiodine
tweak: Skrell & Tajaran sechardsuit to paracode palette, from Bay12 palette.
del: TG & BS12 sec-hardsuits in all dmis
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Squid squad lets go :squid:

**Comment by Spartan6** [comment]
Visor should be red to be consistent with the rest of security visors on the hardsuit.

**Comment by Agameofscones** [comment]
> Visor should be red to be consistent with the rest of security visors on the hardsuit.

Will update visor colors, didn't catch that

**Comment by Agameofscones** [comment]
image
Visors updated 👌

**Pull request merged**
