### PR TITLE
Makes plasmaman engineering/atmos helmets weld/flash proof

### PR DESCRIPTION
**Pull request by GuppyLaxx**

### CODE REVIEW

**Comment by SamHPurp** [comment]
I mean... if you're gonna do this, you should probably only do it for Engineering and CE suits.

**Comment by GuppyLaxx** [comment]
Compared to literally any other server, helmets come already weld proof, besides, plasmaman are already lacking here

**Comment by scrubmcnoob** [comment]
just wear the goggles or something

**Comment by jughu** [comment]
>inb4 admins do a rev event just kill dat plasmaman xd

**Comment by GuppyLaxx** [comment]
>Goggles
like they ever give them out, lel

**Comment by scrubmcnoob** [comment]
That's not the type of response you make if you want your PR to get merged. But what ever, good luck. I personally think they've been fine without it.

**Comment by SamHPurp** [comment]
Legitimately, the Atmos burn one got merged recently. If you want a chance of having this merged, you probably want to limit it to Engineering and CE. But, I'm not your mum.

**Comment by Aurorablade** [comment]
And even if it was on ce and engi. I don't agree with it. Use the goggles.

**Comment by FlattestGuitar** [comment]
This actually makes it impossible to use Sec HUD glasses along with plasmamen helmets because the flash protection stacks too hard.

Some things are not meant to protect from flashes and welding, yo.

**Comment by granodd** [comment]
I'd say to only make this true for the CE/Engineering/Atmos Tech helmets while keeping the rest flash vulnerable. Though even then they have access to goggles, which can be safely removed by security so that the plasma man in question can be flashed should he be placed into a cell.

A better solution would be to make it so that welding goggles can be printed from the autolathe if they can't be already.

**Comment by ProperPants** [comment]
Uh, how are you supposed to get welding goggles? I just checked, and couldn't find it as something able to be made in the autolathe or protolathe.

**Comment by SamHPurp** [comment]
@ProperPants there are (five?) on station at round start.... and you can't really get any more.

1 in Assembly line, one in R&D, and 3 hidden away in Engineering by the backdoor to engineering shuttle.

**Comment by GuppyLaxx** [comment]
Those tend to be taken, put somewhere else where you can't find them, or for RnD/Robotics refuse to give them

**Comment by Anticept** [comment]
Add the goggles to autolathes. Seems silly we can make helmets but not goggles.

**Comment by HereticChurch** [comment]
I think it would be better if instead of a constant protection, they could be given a function in the objects tab that darkens the tint of the helmet viewport to have the welding mask level of vision and welding/flash protection. Not too overpowered but still useful to engies and such.

**Comment by Allfd** [comment]
That would be cool, it would also restrict vision so it wouldn't be such a buff if that is the concern.

**Comment by ProperPants** [comment]
Engineering hardsuits have welding protection with no vision restriction built into them. Just as #7372 made plasma atmos suits like atmos hardsuits, this PR would be more balanaced if  it only focused on the CE and engineering plasma suits being like the equivalent hardsuits.

**Comment by Anticept** [comment]
The hardsuits do have slowdown, however.

**Comment by ProperPants** [comment]
If plasma suits had slowdown, plasmapeople would become shitty diona. Hardsuits having slowdown is compensated by the fact that you can take them off.

**Comment by Anticept** [comment]
I'm just pointing out that there IS a drawback to hard suits.

The fact you can run full speed with them off confuses me as well... these are big damn suits and while I'm sure moving inside one takes effort, I'd still love to know how you can Usain Bolt down the hall with this thing fitting in one hand.

**Comment by FalseIncarnate** [comment]
No description provided.
No changelog.
Blanket change to an entire species-worth of items they get at roundstart.

Yes, this seems beyond the realm of "balance" and "tweak" and into the realm of "powergamer's wet dream".

Limit this to Engineers, CE and Atmos like everyone else is suggesting, and you'll have a solid PR.
Don't limit it and you'll have a closed PR once the maintainers decide you aren't gonna listen.

**Comment by Fox-McCloud** [comment]
This would be acceptable for engineers, atmostechs, and the CE, but no one else; if it's changed to that, then this would be acceptable.

**Pull request merged**
