### PR TITLE
Adds a custom antag hud icon to traitor hijackers

### PR DESCRIPTION
**Pull request by trololiver112**
## What Does This PR Do
Sprite by @McRamon 
Gives traitors with Hijack a custom antag hud icon. 

## Why It's Good For The Game
Makes it easier for ghosts spectating to know if someone has hijack, and prevents 100 ahelps saying something like "he killed me, was it legit?" 
Was also on Kyet's changes wanted list.

## Images of changes

5JOQLUpk9l

## Changelog
:cl: Trololiver112, McRamon
add: Added a new antag hud icon for traitors with hijack
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
`prevents 100 ahelps saying something like "he killed me, was it legit?"`

Wrong, because aHUD is not enabled by default and enabling it prevents you from playing in the round again, so nobody will notice, well, except maybe from banter of other observing ghosts, but thats not a very valid source.

**Comment by trololiver112** [comment]
Well all you need is one person confirming hijack, It might not be a solution to all problems but i certainly think it helps.

**Comment by Spacemanspark** [comment]
It'll help admins for sure.

**Comment by Fox-McCloud** [comment]
Merge conflict.

**Comment by trololiver112** [comment]
Yeah, will fix it when i get time

**Pull request merged**
