### PR TITLE
Adds a syndicate emergency box

### PR DESCRIPTION
**Pull request by improvedname**
Adds a emergency box to syndicate, adds a red military glowstick to it.
moves the pill from their backpack into said box as its meant for a suicide pill
adds a new box sprite.

**Images of sprite/map changes (IF APPLICABLE):**
image

:cl:
add: Syndi emergency box to nuclear opratives.
tweak: Moves the suicide pill to the emergency box
/:cl:

### CODE REVIEW

**Comment by Agameofscones** [comment]
Not sure about the addition of the medical hypospray, but other than that seems pretty neato.

**Comment by improvedname** [comment]
thats the EPI pen they get by standard anyways.

**Comment by Agameofscones** [comment]
Oh, haha my bad!

**Comment by improvedname** [comment]
Why do i need to remove the initro pill. If a syndicate agent wishes to suicide if hes about to be captured he should get the option

**Comment by improvedname** [comment]
I get that on the next pr

**Pull request merged**
