### PR TITLE
Resprites Cigars, Holocigars, Premium Cigars, Rollies, and Cigarettes

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

image

## Why It's Good For The Game

New sprites look good. Changed cigarettes to go with the PR, size upscale may seem initially out of place but compared to other wider items it's not that bad, if they were downscaled further they'd look worse. Premium cigars having a separate cigarbutt than regular also probably being something for later. ( already have a sprite for it )

## Images of changes

image
image
image
image
image
image
image

Cigarette commit changes
image
image
image

## Testing

image

## Changelog
:cl: Mcramon, ATP Engineer.
imageadd: Resprite for Cigars, Premium cigars, Holocigars, and Rollie blunts.
imagedel: Removed unused hand rolled cigarette icons
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
Great sprites, I particularly love the holo cigar and the first cigar sprite (the darker brown one). The golden one which I assume is the havanian cigar has a lot of sheen to it which seems a bit out of place since its supposed to be rolling paper, would it be possible to reduce the brightness on the more whiter parts of it?

**Comment by ATP-Engineer** [comment]
White area is intentionally bright because its part of the gold color combination taken from the gold revolver. Also tried to add the gold using the original segment design but it ended up just making it look ugly. So I compromised and just made the premium cigars even more premium looking for the people walking around with expensive taste.

image

**Comment by Sirryan2002** [comment]
that's fair

**Comment by ATP-Engineer** [comment]
Updated to actually include cigarettes after finding a good method to make them not look bad in comparison to the others

**Review by Henri215 — COMMENTED** [review]
image

Sprites are looking good.
Can you remove these two sprites? I investigated and they are not being used anymore (It was used by a hand-rolled cig which we dont have anymore).

**Comment by ATP-Engineer** [comment]
Deleted both icons

**Review by Henri215 — APPROVED** [review]
Lewcs good to me

**Review by Burzah — APPROVED** [review]

**Review by Sirryan2002 — APPROVED** [review]

**Review by Sirryan2002 — CHANGES_REQUESTED** [review]
Hold up, please double check the icons for `spliffon` and `cigon`, it appears that they've been turned into gifs or something.

**Comment by ATP-Engineer** [comment]
I looked at both repeatedly in the repo and they appear fine.

**Review by Sirryan2002 — APPROVED** [review]
alright, finally got around to double checking locally. DMI's look good, icondiff just is fucky wucky.

**Review by S34NW — APPROVED** [review]

**Pull request merged**
