### PR TITLE
Bluespace tile update

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
This PR updates the sprite of bluespace floor tiles to still keep the bluespace-slime aesthetic (flashing green and sparks for whatever reason), but now the tiles dont look like they will electrocute you instantly. The tile sprite has also been updated

Before:
uuqMBZOaZq

After:
LZ3CJeLAHA

## Why It's Good For The Game
Currently, these tiles look like they are going to seriously harm you if walked on, which is discouraging to new players to say the least. The tiles should look legitimately helpful, not like deathtraps.

## Changelog
:cl: AffectedArc07
tweak: Bluespace floor tiles no longer look like they will shock you to death
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
In a perfect world this would just be an overlay put onto existing tiles with a bluespace applicator which then gets a speedup component, which can then keep the look of the last tile but just have a small overlay, but I think thats out the scope of a sprite change, and afaik we dont currently have a speedup component.

**Comment by Carthusia** [comment]
Is it possible to make these new tiles compatible with a floor painter?

**Comment by AffectedArc07** [comment]
@Carthusia what I said above would work with that

**Comment by McRamon** [comment]
Question, can animation be played only when people step on tile? I wish it was like that

Anyway, i have to say this sprite not great too

**Comment by MRgaty** [comment]
I agree that the sprite is kinda ugly

**Comment by AffectedArc07** [comment]
Making this into an item that can be applied to any floor tile on the station so the original aesthetic can be preserved

**Comment by AffectedArc07** [comment]
Nevermind, I am already juggling enough projects to rewrite stack code to allow it to use an item when you click a turf

**Comment by AffectedArc07** [comment]
Will deconflict when we reach a consensus of "do we want this or not"

**Comment by AffectedArc07** [comment]
Disliked by majority, plus I have better plans for this.

**Pull request closed without merging**
