### PR TITLE
Key Based Pod Locks

### PR DESCRIPTION
**Pull request by IK3I**
Adds Key Based Podlocks and keys

### CODE REVIEW

**Comment by pinatacolada** [comment]
you should squash the commits

**Comment by IK3I** [comment]
fairly new to git, how do I go about squashing them?

**Comment by pinatacolada** [comment]
don't think you can now, but it's a thing for when you create a new PR that you should do, if you use the hub it will ask you if you want to

**Comment by IK3I** [comment]
ah, I used the desktop client and that wasn't an option I saw. I'll do PRs from the web client from now on.

**Comment by pinatacolada** [comment]
I meant the desktop hub, I can't even figure out how to make a proper pr on the web version. Don't worry about it though

:+1: for the keys, might want to consider discussing if the sec pod should spawn with one or not. Also maybe add the key to the items you can retrieve from cryo, it'd suck for a latejoin pilot to find the original pilot locked and cryoed away with the key

**Comment by IK3I** [comment]
I thought about the first one, but completely forgot about the cryo issue. I'll add in pod pilot lock with an id out of the standard lock range and drop a key with the same ID in the pod pilot and hos offices so it's not lost. as for the cryo issue, that's something I've never touched before so can you link the file I need to add it to?

**Comment by Spacemanspark** [comment]
Now we just need a wireless car lock that goes 'beep beep' when clicked.

**Comment by KasparoVy** [comment]
I think you'd have to do git rebase -i HEAD~13
leave the top entry as pick, and put 'squash' for everything below it

**Comment by IK3I** [comment]
is it possible to do that with the PR already created Kasparovy?

**Comment by KasparoVy** [comment]
Yeah, afterward you have to do git push -f, that'll force a push and overwrite the old stuff

**Comment by IK3I** [comment]
looks like squashing needs to be done prior to making the PR. Also, git seems to break on one file and write all over it if let it squash past this point. Not really sure what to do about that. 

Should I just leave it as is, or make a new fork, transfer the changes over and make a new PR?

**Comment by IK3I** [comment]
yeah, I pretty sure that squash issue broke something on the map, adding 2 items does not make 9000 changes... I'm gonna have to grab a clean copy to make the changes on.

**Comment by pinatacolada** [comment]
For map edits you need to use the mapmerge tool, this details how to http://www.ss13.eu/wiki/index.php/Map_Merger

**Pull request closed without merging**
