### PR TITLE
Metastation fixes - round two!

### LINKED ISSUE #6510: [META] The whole station is hotwired
**Problem Description**:
The whole station is hotwired by default.

**Why is this bad/What are the consequences:**
ITS NOT A GOOD THING. Death potential goes through the roof, as even benign experimentation can cause widespread death. Plus, power sinks have extremely high potential to RELEASE THE ENGINE.

**Steps to reproduce the problem**:
Just fire the engine up and check the bridge power computer. ABSURD POWER.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Engineering should have its own SMES just like the west one on boxstation, which acts like a backup battery just for the core of engineering and the emitters. The power monitoring SMES should just power the rest of the station.

### LINKED ISSUE #6872: [Meta-Station] Toxins burn chamber airlock controller doesn't work
**Problem Description**: Cannot access the Embedded Controller in Toxins for the burn chamber airlocks

**What did you expect to happen**: I could use it to open the doors for the burn chamber

**What happened instead**: Nothing. Not even an Access Denied

**Why is this bad/What are the consequences**: Cannot access the gas pumps to start pumping your burn mix into the chamber or suck any of it out

**Steps to reproduce the problem**: Go into Toxins. Try and use controller. Cry when you can't use it

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: METASTATIOOOOOOOON! *shakes fists into the air angrily*

### LINKED ISSUE #7143: Turbine in meta station
The turbine controls dont work at all.

Thats it.

### LINKED ISSUE #7147: [Meta] No garage for Paramedic
**Problem Description**:
What is the problem?

Paramedic has no garage and therefore none of their equipment.

**What did you expect to happen**: 
Why do you think this is a bug?

Paramedic needs their equipment especially their ambulance.

**What happened instead**:
How is what happened different from what you expected?

Expected to spawn in my garage as a paramedic but just spawned in medbay lobby instead.

**Why is this bad/What are the consequences:** 
Why do you think this is an important issue?

Slows down paramedic without their trusty ambulance and space suit.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Be a paramedic try to find garage but fail to find it cause it don't exist.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.  

Meteor + evil pyro.

### PR DESCRIPTION
**Pull request by SamHPurp**
Second round of fixes, #7126 was the last big one I did. This time /mostly/ focused on Engineering/Atmos work.

~~Engine containment grid added.~~ To come in a future PR.

There wasn't really room for a whole Paramedic's office - but the cart, locker and spawn point have been added to a logical location, and a backup set of keys given to the CMO.

Fixes #7147
Fixes #6510

Now also: (19/05/2017)
Fixes #7143 
Fixes #6872 

:cl: Purpose2
add: Metastation - Adds the Paramedic's cart and locker.
add: Metastation - Adds a backup set of paramedic keys in the CMO's office.
fix: Metastation - Engine no longer hotwired.
fix: Metastation - Turbine doors now function properly.
fix: Metastation - Toxin Mixing's Controller is now accessible.
tweak:  Metastation - Moved Containment out a single tile, to fix irregularities with Singularity setups.
del: Metastation - Reduced redundant redundancies in the Atmos/Wiring.
del: Metastation - removed blob spawn that was only a few tiles from Cryostorage....
/ :cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
`add: Metastation - Now has a functioning containment grid.`

What do you mean by this?

**Comment by SamHPurp** [comment]
image

Sorry if this seems like a basic Engineering 101. 

So, previously there was no containment SMES, and the containment emitters and collectors ran on the main power grid, it was all a single grid.

What does this mean?

1. Further away emitters don't get consistently powered, so before engine gets up, engine containment can fail due to more distance emitters getting de-prioritised.

2. A single power sync releases the engine.

3. Grid check events, either do absolutely nothing, or they release the engine - depending on IC wiring.

4. Antagonists can no longer deconstruct the power grid SMES to disrupt power on the station, without fear of releasing the engine.

This brings the Engine containment wiring setup in line with Boxstation, which is by all reasonable measures, the standard - by adding an SMES for the emitter grid, and insulating it from the main grid (as it was always hotwired before too!)

**Comment by Anticept** [comment]
What purpose said was correct, and is quite important this change be made.

**Comment by SamHPurp** [comment]
Anything further I can clarify on this, @Fox-McCloud @Crazylemon64 ?

**Comment by Fox-McCloud** [comment]
@tigercat2000 

You're the Metastation person.

**Comment by tigercat2000** [comment]
I'm not entirely sure the power stuff isn't intentional- especially with the "a single power sink releases the engine" mention, I recall Cyberiad having the same "issue" in the past before we redid engineering.

**Comment by Anticept** [comment]
Whichever way we go, it should be consistent.

There's also one other thing: separating the grids effectively buffs antags. 3 million power will severely mess one up. 600,000 power does some decent damage but patchable.

**Comment by SamHPurp** [comment]
@tigercat2000 @Fox-McCloud This would make a power sink a hijack only item, only when on Metastation... which is madness. You'd also then want to remove power sink from the Syndie Surplus Bundle, when on Metatstation... Also, you'd want to just straight up remove the grid check event....

Paradise engines have a separate containment grid. Doesn't matter what map we're on, the effects are too far reaching to have them be handled separately map to map.

**Comment by SamHPurp** [comment]
Any update on why this hasn't been merged yet? @TullyBurnalot @Fox-McCloud 

Also as an aside these can be closed:
#6008
#7145
#6000
#6004
#6002
#5998
#5999

**Comment by Aurorablade** [comment]
@SamHPurp its probaly with the issue on the powergrid. or lake of time. and i agree with tiger. All maps do not need to have the same grid layout. So not having a containment grid is intentional and is not a bug fix but a feature and does not need to be included.

**Comment by Anticept** [comment]
A vastly superior feature, however, @Aurorablade . Without it, you're exposing both crew and antags to the unfettered power of the engine... enough to instantly kill them as soon as they hit the wrong wire on a door.

**Comment by Aurorablade** [comment]
@Anticept thats only if you hotwire the grid. the only thing a containment grid does is put the containment field power on its own SMES so you have more time to set the field up. this map INTENTIONALLY does not have this.

**Comment by Anticept** [comment]
What fucking planet are you on? I was the one that discovered that IT IS HOTWIRED.

**Comment by tigercat2000** [comment]
There's a difference from the emitters being wired to the grid instead of a separate SMES unit and the engine being wired directly to the grid; The former is intentional, the latter is not.

**Comment by Aurorablade** [comment]
@Anticept and thats not the issue we are talking about. WE ARE OKAY WITH THE HOTWIRE FIX.

We are talking about the CONTAINMENT GRID. on THAT NOTE. AS engineers if you wanted to put safety on the grid, you can build a seperate SMES after the containment field is up and put power on that so it doent fail.

**Comment by Anticept** [comment]
@tigercat2000 @Aurorablade if you don't have the separate SMES on the inside of the grid, and you separate the two grids, then you have no way to power up containment unless you have people anchor the PACMAN

**Comment by Aurorablade** [comment]
@Anticept thats the way we did it before we baby proofed cyb engineering and its fine for meta. As i said they could put in a safety SMES after they got things set up.

**Comment by TullyBurnalot** [comment]
@SamHPurp Abridged version:

Everything else is fine, but the engine containment in Meta is _designed_ to have less failsafes and to be more dangerous to the crew, not to have the same level of backup protection as the engine on Box.

**Comment by Anticept** [comment]
@Aurorablade @TullyBurnalot the SMES isn't for safety, it's for consistency. Once the engine is running, the SMES isn't needed. Someone would have to really derp and either remove the tesla coils, cut the wrong wires, or turn off all 6 rad collectors at once.

If you intend to remove the engine grid SMES, then the wiki will need updating stating the use the pacman. The only real reason for having that SMES is to **make it faster to start up the engine**, and power engineering for a little while longer while they get things set up.

**Comment by tigercat2000** [comment]
The power grid SMESs are intended to start with 1/3rd power, I believe, specifically so that you don't have to cold-start the engine with a PACMAN. If they aren't doing such, that's probably a separate issue that could be fixed.

**Comment by Anticept** [comment]
@tigercat2000 this goes back to the issue of the station and engine grid being connected together then in a hotwire.

There is one other possibility: that is just connecting emitters to station grid side, but you WILL GUARANTEE an engine release then when a power sink gets dropped. At most, those three smes will only be able to provide 600k power, while the power sink draws 2.4 million.

**Comment by TullyBurnalot** [comment]
@Anticept and I have just come to an agreement with this kerfuffle if the following is added to the description of the Power Sink:

"WARNING: THIS MIGHT RELEASE THE ENGINE!"

**Comment by Anticept** [comment]
I had a chat with @TullyBurnalot and he suggested this for the power sink:

```
Add this to the item description:
"WARNING: THIS MAY RELEASE THE ENGINE!"
```

I would be very happy with this extra warning being added to a power sink description if we are going to have emitters powered by the station grid, as it will help bridge the gap between what has been learned over the past couple of years, and what is to come.

It still means gamemodes such as shadowlings can still result in engine release, due to the incentive to destroy the SMES (and subsequent engine release that will result due to emitter power being cut), but that requires much more determined action, so I find that less worrying.

**Comment by SamHPurp** [comment]
This discussion is still on-going. Hang on.

**Comment by Anticept** [comment]
Hey uhhh.... did TG ever use releasable engines on metastation? I know they use SMs...

**Comment by SamHPurp** [comment]
This is TG's Metastation:
image

This is TG's Tgstation:
image

This is TG's Omega station:
image

This is TG's Cere station:
image

This is TG's Delta station:
image

----------

Whats my point in showing all of these? TG don't use active engine containment, because they use different engines.

Using a very outdated comment of 'Oh TG don't use containment' is disingenuous at best.

They don't even need to use containment. They don't have releasable engines.

We do.

Square pegs and round holes.

This is a simple cut and dry: You use containment field for a containable engine, you use a containment grid.

**Comment by Aurorablade** [comment]
We did not always use a containment grid not did tg always use a sm on all maps. Our meta varient is before that change over.

**Comment by Aurorablade** [comment]
Also nothing about any of this has to do with tg at all.

**Comment by SamHPurp** [comment]
> @SamHPurp [...] not a bug fix but a feature and does not need to be included. - @Aurorablade 

See now that is an argument I can understand.

If I re-titled this as more 'Bringing it up to Paradise's Standard Phase 2' than straight 'fixes' - would that cheer everyone up?

As honestly there are a number of things that should happen to make Metastation viable for active rotation, and this is a key part of them.

It'd be rather obnoxious and **slow** to have to do every one of them in their own PR.

@TullyBurnalot Not being able to do a bunch of sweeping Metastation 2.0 changes to Paradise-itise the map to make it usable, and having to do everything in slow moving individual things to be picked over seems the opposite of the idea of being able to be swift and agile.

Through no ones fault, Metastation is poorly maintained, and I seem to at present be the only one vaguely interested in working on it.

**Comment by Aurorablade** [comment]
@SamHPurp "If I re-titled this as more 'Bringing it up to Paradise's Standard Phase 2' than straight 'fixes' - would that cheer everyone up?" not really..as i feel it should be left as is. and i am not really sure if having the containment on its own grid is really a standard moreso then it was a Newbie QoL change we did.  I also liked improveing the meta map but i had a period of internetless and something i wasn't sure how to do with. I do like leaving parts around in meta engie to build a containment SMES so engies could build thier own containment grid. But thats jue meeee...

**Comment by Anticept** [comment]
**I personally would LOVE to have containment "incomplete" on BOTH stations.** Most of the wires are laid, but not hooked in. It is on the engineers to know where to hook up the final run and do the final anchoring on the emitters. The tesla coils and containment emitters will already be in place. They would need to drag the engine device of choice out and anchor it down... but we run into a problem of dealing with secure storage permissions...

**Comment by SamHPurp** [comment]
@Aurorablade I do understand your point of view on this, but I'm afraid I don't agree. The fact that a single power sink, anywhere on the station, hidden anywhere, with zero chance of counterplay - will release the engine.

**Comment by Anticept** [comment]
To be fair, engineering could wire containment at start so there IS counterplay, but I do not look forward to making such a mundane task a regular occurrence.

**Comment by SamHPurp** [comment]
A'ight jerks. I've reverted the Engine Containment Grid addition... I'll raise a future PR for this, and we can debate the pros and cons till the cows come home there.

I also fixed a couple more bug reports:
Fixes #7143
Fixes #6872

@Fox-McCloud @Crazylemon64 @TullyBurnalot The offensive bit has been removed from this PR.

**Comment by jughu** [comment]
It ALWAYS was like that SM was just a addition this year because people got sidk of released engines

**Comment by Anticept** [comment]
Note: power grid checks **_WILL RELEASE THE ENGINE_** as long as emitters are powered by the station grid.

However, I think we could come up with something interesting if we step back and rethink what engineering could be doing. I was exploring an idea while developing my draft for a power grid refactor, but I guess I'll bring this out now.

It would be neat for machines and things to have a "low power mode" and "high power mode". The station is initially powered by solars, which provide enough power for "low" mode. When the engine is constructed and brought online, everything can switch over to a high power mode, greatly increasing speed and efficiency. However, I had not begun to think about what those specifics are... as it's complex and requires a lot of considerations.

I bring out that idea now as this seemed a good a time as any to get some feedback on what such a system could mean.

**Comment by SamHPurp** [comment]
Hey dudes, since I removed the `feature` from this, and kept it to fixes, could this get merged please?

**Comment by TullyBurnalot** [comment]
@SamHPurp Just waiting on a final review by @Crazylemon64 , then should be ready to go.

**Comment by Crazylemon64** [comment]
deburred_containment_grid
Looking here, it seems like the emitters have been moved to the power generation side of the grid.

What is the thrust of this PR? Is it to deburr sharp edges of Metastation that could lead to disaster? Or is it to reconcile systems that are incompatible with this map not having been updated?

I'd like to keep balance and fixes quite distinct. If you're going to keep this as a "Fixes" PR, could you please move the blobspawn and the engine containment change to a separate PR, specifically dedicated to Metastation balance?

**Comment by TullyBurnalot** [comment]
@SamHPurp

**Comment by SamHPurp** [comment]
@TullyBurnalot as @Crazylemon64 and I just spoke, he is now in agreement with myself that those two items do constitute fixes.

**Pull request merged**
