### PR TITLE
Removes cortical borers. No, I am not sorry.

### LINKED ISSUE #3969: Borers UI is prone to breaking
Dagnabbit sometimes the buttons don't show up for some reason

Maybe I made one of the command names too long and BYOND hates that?

### LINKED ISSUE #7107: Possessable borer ghosts
**Problem Description**:
When I joined as a borer using the join as NPC command, I was placed into the nonexistant body of a borer ghost.

**What did you expect to happen**: 
To be placed into one of the many borers left lying around.

**What happened instead***
I was placed into a ghost, unable to move or do stuff.

**Why is this bad/What are the consequences:**
Spooky brain slug ghost possessions.

**Steps to reproduce the problem**:
Join as a borer using the join NPC tab. All I did, I have no idea what else might have happened to cause this.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Meh. Not really. I only know I became a spooky ghost borer because when I said fuck it and ghosted, there was a borer ghost on my tile with the same name as me.

### LINKED ISSUE #11749: Player Panel New Doesn't show Host Brains
**Problem Description**:
Can't search up people that are being controlled by a coritcal borer in Player Panel New. Have to use the old player panel.

**What did you expect to happen**: 
For them to appear in the list

**What happened instead**:
They didn't

**Why is this bad/What are the consequences:**
Inability to apply timely admin action when needed

**Steps to reproduce the problem**:
Have someone be controlled by a borer
Search for the non-borer ckey in **Player Panel New** (not Player Panel) 
It doesn't show up

### LINKED ISSUE #12533: Borers inside a hosts head get hurt by ash storms
**Issue Description**:

Borers inside a hosts head get affected by an ash storm, and killed from it

**What did you expect to happen**: 

Expected my host to take damage from the storm, and for me to be safe unless I crawled out.

**What happened instead**:

Died inside my host silently, without even my host noticing

**Why is this bad/What are the consequences**:

If someone is in a pod, they are safe from a storm, following the same rules, a borer in someones skull should to.

**Steps to reproduce the problem**:

Infest a miner. 
Watch as they are in an ash storm for more then 6 seconds.
Die

**When did the problem start happening**:

Probably since lavaland was added.

**Extra information**:

### LINKED ISSUE #16623: A miner, borer, and anomalous crystal can do weird things.
**Issue Description**:

A miner who has an anomalous crystal with the animal possession ability can take over NPC cortical borers.
A miner with a cortical borer inside them, who uses the crystal, and exits the animal while the borer is controlling their body, will have their mind forced out of their body and into the borer, removing the borer's previous player from the borer.

**What did you expect to happen**: 

Truthfully, I did expect this to happen. Me and the borer both purposely did this to experiment with "black magic".

**What happened instead**:

If the miner is possessed by the borer, as they are in animal form, they will still control the animal.
The borer, controlling their body, can actually still do things with the body, like move objects in the inventory (this actually deletes the items), toggle flashlights, and use other abilities, like vomitting headslugs. (a mouse vomitting headslugs on the bridge scared the captain.)
If the miner tries to exit the mouse or other animal, while the borer is still in control of their body, this will crash the miner, who upon rejoining, will now be controlling the borer, possessing their own body. 
They've essentially ghosted out of their own body and entered the borer, still controlling their body. Oh, and the ORIGINAL borer is apparently kicked back the the main menu screen after they crash.

Also, borer-ception is possible. You can make another borer, enter it with the crystal, then enter another body, take it over, and repeat with more borers. Black magic.

**Why is this bad/What are the consequences**:

It abuses game mechanics and does weird shit. I feel like the problem explains itself, with the weird things that happen.

A player can be booted from their own body under certain circumstances, and a previously dead/observing player can later join the round as crew (possibly, based on what the borer said, i might have misunderstood)
This might allow for some metagaming to happen.

It isn't too bad though. It can't really be used to negatively effect anyone other than yourself. You have to intentionally do this.

**Steps to reproduce the problem**:

I previously explained exactly what happened, so I wont repeat myself.
Just do exactly what I did with a player controlled borer, after getting an anomalous crystal with animal possession. 

**When did the problem start happening**:

This happened earlier today. I don't have the round's ID, but it was the extended round that ended about 6-ish hours before I made this post.

I mean, this is only possible when:

A. Miner kills colossus and finds the correct crystal
B. Miner gets a borer
C. Miner and borer intentionally attempt to do this

This could have happened years ago if people tried, and I don't think it's any fault of the code or a new bug.

**Extra information**:

The situation was resolved after we broke shit by PM'ing an admin, explaining the situation, where they put me back into my body. 
That being said, after doing further experimentation a second time, I was to embarrassed to ask for help again, so played the rest of the round as a borer controlling my own body. Had to explain to the CMO in LOOC to not get killed.

I personally cannot offer any easy solution to this problem. I don't know how borer code works, I don't think this issue is worth removing the crystal or the animal possession ability, or removing any other current game mechanics.

The only solutions I can think of are complicated. Somehow checking if a borer is in a person when the animal possession is used, maybe. 

Also, maybe not letting borers be controlled with animal possession. Miners being able to get inside of other people as a borer isn't good.

Otherwise, this is such a situational thing that has to be done intentionally, where the only victim is the people who do it, and maybe the admin who fixes it. Thank you Frailty.
frailty

### LINKED ISSUE #18083: Borer can permakill host and take over his body entirely
**Issue Description**:

Borer can permakill host and take his body

**What did you expect to happen**: 

Exactly that

**What happened instead**:

Exactly that

**Why is this bad/What are the consequences**:

Well, borer permakilling host is kind of bad

**Steps to reproduce the problem**:

1.Be borer
2.Find a host
3.Take over
4.Eat roburger(best results, will focus on it in next points)/xeno microbes/anything that transforms into mob that cannot have borer
5.Host will be permakilled and borer will be in control of borg
6.Borer can now ask to be turned into IRC, thereby replacing host entirely

**When did the problem start happening**:

Sadly, i cannot answer that

**Extra information**:

It was found and tested on testserver. Thankfully never seen it happen in game.

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Removes cortical borers. Not much more to say.

We actually decided on this way back in october 2021 after a community meeting (link: https://youtu.be/Qwe1ruXNzA8?t=6264). I kinda let this slide because I had bigger fish to fry but the topic was raised again, especially after administration had to deal with one too many god awful borer rounds.

Borers are flawed, no real objectives, a pain to administer, riddled with bugs and outdated code, and its about time we give them the axe,

Closes #3969
Closes #7107
Closes #11749 
Closes #12533 
Closes #16623 (Probably)
Closes #18083 

## Why It's Good For The Game
See above.

## Changelog
:cl: AffectedArc07
del: Removes cortical borers. No, I am not sorry.
/:cl:

### CODE REVIEW

**Comment by roarbark** [comment]
probably for the best. i feel the idea itself wasnt the problem, but the implementation- maybe they can return someday, done right though.

**Comment by AffectedArc07** [comment]
Fixing CI

**Comment by dikers93** [comment]
why do you cut them completely if you can just as a mode? So that it would be easier to modify / correct them later

**Comment by Sirryan2002** [comment]
> why do you cut them completely if you can just as a mode? So that it would be easier to modify / correct them later just like they did with xenomorphs

Cortical borers have gone years without a rework. Moving a bad antag off rotation with the expectation that it will one day be fixed is how you get stagnated gamemodes like devil, revolution, vox raiders, etc etc. Xenomorphs aren't fixed either, they're still a balance nightmare atm and no successful rework has gone through from them either since they were pulled from rotation.

**Comment by dikers93** [comment]
> > зачем вы их полностью вырезаете если можно просто как мод? Что бы их потом было легче дорабатывать/исправлять так же как это было с ксеноморфами
> 
> Кортикальные сверла годами не ремонтировались. Удаление плохого антага из ротации с ожиданием того, что однажды он будет исправлен, — это то, как вы получаете застойные игровые режимы, такие как дьявол, революция, вокс-рейдеры и т. д. Ксеноморфы также не исправлены, они по-прежнему представляют собой кошмар баланса, с тех пор как их сняли с ротации, прошла успешная переделка.
> 
> Для игр важно вырезать функции, которые никто не собирается исправлять, потому что они в целом негативно влияют на игровую среду и баланс. Вероятно, кому-то будет проще переписать сверлильщиков с нуля, чем пытаться реорганизовать то, что уже существует.

you are partially right, but still, just like the xenomorphs, there is no need to permanently cut them out, they are difficult to complete, but it is better to have at least a basis for them. This will make things easier in the future.

**Comment by Fox-McCloud** [comment]
I can't approve this fast or hard enough.

**Comment by AffectedArc07** [comment]
> remember to remove borers from #14968

Will do once this is in

**Comment by smokincheez** [comment]
I feel honored being the (Probably) in the close list, but it also makes me realize this is 200% a good choice.

**Pull request merged**
