### PR TITLE
Added an airlock near Atmospherics.

### PR DESCRIPTION
**Pull request by monster860**
That way, when atmos guys want to do stuff just outside the atmos room, they don't have to hunt down an airlock on the other side of engineering, or mess with the windows.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
pics, please.

**Comment by KasparoVy** [comment]
Snipping tool bro!

**Comment by monster860** [comment]
http://imgur.com/nmrUwwa

**Comment by Plotron** [comment]
Looks handy.

**Comment by Tastyfish** [comment]
I like this. The only current way to get out there in practicality is to dismantle the windows and rotate them for airlocking.

**Comment by Fox-McCloud** [comment]
Waitttt.

You changed some transit tube pieces, it seems. You won't be able to cross through, anymore. Anything else you changed?

**Comment by monster860** [comment]
I tested the transit tube, it works fine.

**Comment by monster860** [comment]
What exactly do you mean by being able to cross through?

**Comment by Tastyfish** [comment]
You removed the pass tube pieces, so the tube is now an impenetrable wall in space that people can't cross through.

**Comment by monster860** [comment]
There, fixed it

**Comment by Fox-McCloud** [comment]
Pics of the entire area again, please?

**Comment by monster860** [comment]
http://imgur.com/JHFj6Qw

**Comment by monster860** [comment]
Note the air tank, grille, and cat walk. The reason the transit tube got messed up is I needed to move it down to make space for the airlock.

**Comment by Fox-McCloud** [comment]
This is going to sound nitpicky, but the pass through tubes should be in the center.

**Comment by monster860** [comment]
Done. Centered the passthru tubes (In between the lattice tiles)

**Pull request merged**
