### PR TITLE
Icon and Sound Cleanup

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Cleans up Icons and Sounds

- Reduces the codebase size by ~4-5 MB
- Reduces RSC file size from ~72 MB to around ~57 MB
 - THIS REQUIRES A CLEAN COMPILE TO TAKE ADVANTAGE OF!

Sound

- Removes all but 8 files of Vox (that are no longer in use)
- Removes duplicate test loop sound
- replaces the 5-6 second long sear sound with the same sear on scalpels
- replaces the current taze with one that sounds the same, but is slightly shorter 

Icons

- splits the high-rest singularity and EM field sprites off into their own unused folder
- removes duplicate cable conduit files
- Updates the Vox sound-gun projectile sprite to use the updated version.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:+1:

**Comment by TheDZD** [comment]
:+1:

**Comment by Robertha89** [comment]
:+1:

**Comment by Spacemanspark** [comment]
Thank fuck.
:+1:

**Comment by Fox-McCloud** [comment]
Made a small addendum; upates the Vox's sound cannon to use the updated particle sprite (also saves a bit more on space for players).

**Comment by Plotron** [comment]
Yay, less BYOND fuckery with redownloading all the shit.
As in, it will be faster at least.

**Pull request merged**
