### PR TITLE
Mhelp Fix

### PR DESCRIPTION
**Pull request by Alexshreds**
Fix - #7485

🆑 Alexshreds
tweak: Taking mhelps no longer gives mhelping players your IC name
/ 🆑

### CODE REVIEW

**Comment by SamHPurp** [comment]
"Your question is being attended to by Syndiedonk Operative #1 (Purpose2). Thanks for your patience!"

**Comment by Alexshreds** [comment]
"Your question is being attended to by Purpose2(Syndiedonk Operative #1). Thanks for your patience!"

😉

**Comment by SamHPurp** [comment]
(psst you have a leading merge commit)

**Comment by Alexshreds** [comment]
i cn't rebaze hlp plz i dnt kno hw 2 uz torgit

**Comment by Alexshreds** [comment]
I believe I've fixed it for many futures to come

**Comment by Xantholne** [comment]
>Implying it ever gets used in the first place
but yeah seriously it can sometimes give out metay information that aren't under staff rules

**Comment by LightFire53** [comment]
I assume this applies to ahelp as well?

**Comment by Alexshreds** [comment]
Hmm?

**Comment by Anticept** [comment]
Ahelps do this too.

**Comment by Alexshreds** [comment]
If it is specifically admins taking mentor helps, this will fix that. I'm not sure about normal ahelps though, I can take a look.

**Comment by Alexshreds** [comment]
I believe it fixes that as well, although, all admins and mentors will get a message saying "x is attending to y's question" and that does reveal IC names but that is just only to admins and mentors.

**Comment by Anticept** [comment]
I saw that was separate, and that's not really a big deal.

**Pull request merged**
