### PR TITLE
Mimic Gun and Gun Fixes

### PR DESCRIPTION
**Pull request by TheDZD**
:cl:
add: Adds an adminbuse gun that fires gun mimics, you can varedit the gun's `mimic_type` var to any gun path, and it'll fire that gun as mimics. By default it fires stetchkin pistol mimics.
fix: Fixes minor issues caused by some guns having text paths for power cells.
fix: Fixes some runtimes and inconsistencies with the telegun and temperature gun.
/:cl:

### CODE REVIEW

**Comment by Earthdivine** [comment]
Gun that shoots more guns. Finnaly.

**Comment by TheDZD** [comment]
Can't get a recording of it at the moment, but the projectiles do look like whatever gun the mimicgun is making mimics of. I do need to make it copy over overlays though.

**Comment by taukausanake** [comment]
Will these mimics also shoot things? Can they shoot the mimic gun which will in turn shoot more mimic guns? (unless they take the default pistol) Do the mimics fired act like projectiles or being thrown? These are important things

**Comment by TheDZD** [comment]
The answers to those questions are: yes, yes, and no.

**Comment by taukausanake** [comment]
Aww, so much for shooting people with guns I guess. +1 for the gun spam however

**Comment by Keilden** [comment]
Can it fire itself? So you get a gun that fires guns that fire guns?

**Comment by TheDZD** [comment]
Just as a sidenote, this probably needs actual sprites, instead of just using disabler sprites.

**Pull request merged**
