### PR TITLE
Change order of HOS gun modes

### PR DESCRIPTION
**Pull request by Jovaniph**
As requested: https://nanotrasen.se/forum/topic/11158-hos-shot-type-order/

Previous order was: Stun, Kill, Disable
Now: Stun, Disable, Kill

🆑 Jovaniph
tweak: Change order of HOS's gun to Stun > Disable > Kill.
/ 🆑

### CODE REVIEW

**Comment by Anasari** [comment]
I think that's the wrong thread you are linking to. https://nanotrasen.se/forum/topic/11158-hos-shot-type-order/ is the correct one

**Comment by Fox-McCloud** [comment]
I'd be inclined to say leave it the way it is; it's been this way for 2 years now with literally a *single* player complaint.

Everyone and their brother is used to it being the way it currently is.

**Comment by Twinmold93** [comment]
Leave it as it is. I echo what Fox says, the current order is order of power already: disable; stun; kill.

**Comment by Spartan6** [comment]
Uhm, that isn't the current order.

The current order is Stun, kill, disable, that's what he is changing to the new order of stun, disable, kill.

But I do agree disable, stun and kill is a better order.

**Comment by Twinmold93** [comment]
However, if you look at it, it is disable, stun,kill. The order doesn't just stop, it merely means it starts on stun instead of disable. Stun, kill, disable, stun, kill, disable... The order is already correct and therefore doesn't need a change.

**Comment by DesolateG** [comment]
As someone who plays HoS more often than every blue moon I can tell you that it starts out Yellow (stun) at the start of the shift. Stun, kill, disable.

**Comment by Jovaniph** [comment]
Shame...All of you.

**Comment by Spacemanspark** [comment]
This is something that's bothered me for a bit now, and I have seen new Heads get confused.

**Comment by Ralta** [comment]
Easy solution; don't change the order, just change the starting mode to be disable, then have it cycle to stun and kill as normal.

**Comment by taukausanake** [comment]
@Ralta I mean you're going to edit the exact same thing, this is a one-line edit

**Comment by KingPhilipIII** [comment]
This is giving me a headache now.

**Comment by Twinmold93** [comment]
Desolate, I may not play HoS too often, but I'm aware it starts on stun like I stated. So do all hybrid tasers. The point is the cycle, which changing only changes what it starts on, and should be kept in line with other tasers.

**Comment by Vivalas** [comment]
I've accidentally lethaled crew a few times because of this, definitely think stun should come before disable, since that keeps it consistent with tazers and typically stun is your "normal" mode, with disable being used in a few special cases.

**Comment by SirBloodBuske** [comment]
Stun Disable kill!

**Comment by tigercat2000** [comment]
After discussion between the Heads of Staff and Maintainers, it was decided to close this PR. The HoS' Gun already starts every round on the "Stun" setting, which makes the progression Stun--->Kill--->Disable--->Stun and repeat. As such, we do not see it as necessary to alter the order.

**Comment by Jovaniph** [comment]
You think this PR doesn't altar the order but in fact it does
The Current order is Stun Kill Disable Stun Kill Disable Stun Kill Disable
This PR changes it to Stun Disable Kill Stun Disable Kill Stun Disable Kill Stun Disable Kill

If you alter the cycle, you'll notice the difference.

**Comment by tigercat2000** [comment]
@Jovaniph I'm aware it changes the order. It changes the order to be completely inconsistent with both power and the standards of other guns- It always goes disabler, stun, kill. Disabler is the least impactful of the three.

**Pull request closed without merging**
