### PR TITLE
Hide PM mob name from non-admins

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
:cl: Tayyyyyyy
fix: You can't see admin character names in PMs
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
REVENGE!!1

**Comment by DesolateG** [comment]
This include +MENTOR?

**Comment by Tayyyyyyy** [comment]
@DesolateG This is just restoring to whatever it was before #8896, so it'll be the exact same as before.

**Comment by DesolateG** [comment]
Ah gotcha

**Pull request merged**
