### PR TITLE
Implement Tackle

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
This adds in a new tackle ability available to everyone which can be activated by using throw and grab intent with an empty hand and clicking on your target, it is a very short stun and it only works within a three tile range. It can be used to dive over tables and other obstacles but has a long cooldown to compensate. This was more something I thought would be a nice addition to the game and a nice challenge for me to try as a first real PR
ezgif-4-32243ef7e843

**Changelog:**
:cl:
add: Added new tackle attack
/:cl:

### CODE REVIEW

**Comment by Superhats** [comment]
This just seems like a shorter (?) Version of the vox leap, which was removed. I'd be fine with this if it was in some martial art, like CQC giving you a chance to block, but I'm strongly opposed to everyone getting it. SS13 is already a game whose combat is strongly centered around stuns, we don't need another stun, especially one people can do empty handed

**Comment by farie82** [comment]
Will be fine if added to a syndicate item. Or maybe the wardens gloves but giving people a reliable stun attack is bad for balance.

**Comment by Shadeykins** [comment]
I will give this a thumbs up if you make it read as "glomps" if an admin uses the japanese anime mode.

**Comment by Breenland** [comment]
GLOMPING ASIDE, I think it would be good if it knocked both parties down. Is there a cool down on its use? Otherwise I like it!

**Comment by Ty-Omaha** [comment]
This is pretty cool but is an instant "I win you're stunned" 😕

**Comment by davidchan13** [comment]
The fact that it stuns and knocks back the monkey before he even clears the table is particularly bad. Doesn't even need to connect, just auto win. :-1:

**Comment by Couls** [comment]
It’s a very short stun which wasn’t shown at the end of the gif and the range is very short and again it has a long cool down so it can’t be spammed it’s only useful for stopping someone that’s running away from you and not just an insta-win button the knockdown isn’t long enough to cuff someone and you still have to aim at your target and be in range to tackle them down I’ll show add a gif of the stun time

**Comment by Breenland** [comment]
I can get behind that now, have always wanted to see Security tackle someone who they've been shooting with a disabler.

**Comment by Couls** [comment]
So this now both knocks down both users meaning it can't be used with a weapon on your off-hand or else it will be dropped, the tackler has lightly less of a knockdown time compared to the victim(they get up three seconds earlier) this can also be changed to make the stun time the exact same and have tackles become more like something used to help someone(tackle someone out of the way or tackle someone when taking fire to dodge some of the lasers)
image

**Comment by Spacemanspark** [comment]
This is basically a nerfed vox leap.
:-1:

**Comment by Shadeykins** [comment]
Ahahahaha. :D Glomp

**Comment by Couls** [comment]
Pretty unlikely this will be getting merged but it was fun to code and i'm pretty happy with this, maints feel free to close it or review it and help me out with how you want formatting for future PRs and stuff

**Comment by TheMadTrickster** [comment]
So before I start my comment, I feel I should say that I support this, and after a bunch of balancing I feel it could really be a nice addition to paradise. 👍
But as I said before, Balancing is really needed here. 

> It can be used to dive over tables and other obstacles but has a long cooldown to compensate.

This concerns me, considering how it'd indirectly make table climbing less viable. It's almost guaranteed that a lot of players would use this to get over tables, instead of actually climbing over them, if this were the case, considering the time taken to get over the table is much shorter, and it's overall a quicker more effective way to get over them. I understand it has a long cooldown to compensate for it, but I still believe that there should be more stopping a player from simply tackling over a table instead of climbing over it the usual way. One way to counter this without changing the core idea behind the feature, would be to make a player stay stunned for the same amount of time as it'd take to climb over a table (or a second longer if that helps) if the tackle doesn't hit anything. This way, it'd make table climbing more ideal for getting over tables than just tackling, and keeping tackling as what it was meant to be.

> the tackler has lightly less of a knockdown time compared to the victim(they get up three seconds earlier) this can also be changed to make the stun time the exact same and have tackles become more like something used to help someone

I believe this is a step in the right direction from the original PR, I think it should be the exact same time, or else it'd end up being much too effective. If a security officer has a stun baton in his hand, and you're a greytide about to be arrested for breaking into the clowns office, you shouldn't be able to tackle the security and get up fast enough to pick up his baton before he even gets the chance to. If there are syndies in the hallway with dual eswords, you shouldn't be able to tackle them and pick up their dual eswords and robust them before they even have the chance to pick it back up, or hit you at all with it. In my opinion, and I'm sure many other peoples opinions, tackling should **not** be an almighty way to instantly win a melee fight with an opponent no matter what weapon they wield.

I'm sure there are many more balancing issues with this PR, but after all of them have been resolved, this could be a really great addition to the game, and take a big part in the paradise combat system, and give players more options to strategize their approach when faced with a dangerous foe. I 100% support this PR, and I hope to someday see it in the game!

**Comment by variableundefined** [comment]
The tackle is way too strong even if it knocks down the user, I fear it'll encourage even more validhunting as a mob have even more weapons to deal with someone armed.

**Pull request closed without merging**
