### PR TITLE
New Lobby Music!

### PR DESCRIPTION
**Pull request by Ultimate-Chimera**
Adds in Sans theme (megalovania) from Undertale for a lobby song.

https://dl.dropboxusercontent.com/u/211463060/megalovania.mp3

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Forgot to add .ogg, making a quick fix.

**Comment by Fox-McCloud** [comment]
Get permission (and proof of such, given his status) from Tobi Fox.

**Comment by Ultimate-Chimera** [comment]
Alright.

**Comment by Ultimate-Chimera** [comment]
Wait, where can I find his soundcloud/youtube or whatever?

**Comment by Ultimate-Chimera** [comment]
Found his twitter, one second.

**Comment by Earthdivine** [comment]
With or without permission, this is a :-1: from me. Why? Megalomania is not a song that is for casual listening, it's an up beat tune meant to be used to hype and pump you up for a fight. Bonetrouse's light and chippy tune would be a better pick for this then Megalomania ever would.

**Comment by Fox-McCloud** [comment]
There's that, as well, and I completely agree with @Earthdivine on her points.

**Comment by Ultimate-Chimera** [comment]
Well, if you want I can change it to that, people requested that song in OOC so isn't that like Papyrus's fight theme?

**Comment by Ultimate-Chimera** [comment]
I'll just close this till I get permission from Toby.

**Pull request closed without merging**
