### PR TITLE
Blob can attack living things

### PR DESCRIPTION
**Pull request by Robertha89**
Fully equipped Kidan take 4,4 brute.
Fully equipped Human take 7 brute
Fully equipped IPC take 9.75 brute
This is security jumpsuit + riot suit and helmet
Anyone else takes 40-50 damage armor depending, currently there appears
to be an issue with the damage as instead of dealing 20-30, so that is a
bug that needs to be fixed.

### CODE REVIEW

**Comment by tigercat2000** [comment]
uh, what? This was purposely removed because 40-50 damage is absolutely ridiculous for a blob to just deal at any point

**Comment by Robertha89** [comment]
exactly, thus the damage values can be fixed.

**Comment by tigercat2000** [comment]
I don't see any reason to enable this at all, blobs have plenty of other methods at their disposal to deal with people without giving them the ability to do a ridiculous amount of damage with a cheap expand

**Comment by Robertha89** [comment]
Here is the thing, you you are armored, then blob is gonna have a hard time, if you attack an powerfull expanding alien organism then you can expect getting punched by it hurts, that is the deal. They have currently, 2 ways of damaging. Blob Spores, and random block_act on living beings. so i don't see what other ways unless you are talking about welder tanks, thanks to linda atmos is not really a good way to protect a blob anymore.

**Comment by Spacemanspark** [comment]
Ehhhhhhhhhhhh.........
Blobs don't need to do a ridiculous amount of damage, then have blob zombies for that.
:-1:

**Comment by Robertha89** [comment]
If a blob spore attacks you 458 times in riot armor, you will take a total of 138 brute damage. but i am also working on fixing the damage a blob does. cause its  wee bugged.

**Comment by Iamgoofball** [comment]
Christ, reduce the damage to 10-20

**Comment by FreeStylaLT** [comment]
dude now the blob's spread and node's spread already deal a shitton of damage you want that to be -on demand-? That's pretty insane, seeing how blobs have no trouble winning without it right now

**Comment by Spacemanspark** [comment]
If you have goofball, the guy who made extremely deadly chemblob for /tg/, telling you the damage is too high... it's too high.
...At least, I think goofball wrote chemblob.

**Comment by Iamgoofball** [comment]
@Spacemanspark 

10-20 is the damage range we have blobs doing on TG code.

It's worked pretty well.

I'll probably port tg blob over here because it's a much more balanced experience then bay blob, and more fun.

**Comment by Spacemanspark** [comment]
So I hear.
Please do.

**Comment by Fox-McCloud** [comment]
I don't think this is a good idea *right now*. Our blob code is the very very first iteration of TG's blob code---it's not been updated much, except for little buff here and there without compensating for other changes TG made elsewhere.

I'm fine with this ability returning when the game mode is brought up to modern standard, but for now, I cannot support this.

**Comment by Earthdivine** [comment]
I will have to :-1: this one extremely hard. The blob doesn't do this because it EVAPORATES anyone it can get to. The ability itself has no cooldown, so a blob with a good sizeable points will instantly kill anyone and anything that gets near it. The amount of damage can be negilable and still the blob will evaporate people.

**Comment by Robertha89** [comment]
Very well, i will work on a port, always wanted a chance to try a bigger project

**Comment by Iamgoofball** [comment]
@Robertha89 Don't, I'll probably end up porting it as it's kinda tied in with reagents code.

**Comment by Fox-McCloud** [comment]
@Robertha89 

Yeah, let Goofball handle it, as he's far more familiar with reagents.

**Pull request closed without merging**
