### PR TITLE
Tweaks some playtime requirements

### PR DESCRIPTION
**Pull request by Kyep**
Changes:
- IAA now requires 5 hours
- Captain and AI now require 20 hours

🆑
tweak: Playtime requirements for IAAs have been set at 5 hours (similar to Sec Officer). Playtime requirements for Captains and AI have been increased from 10 hours to 20 hours.
/🆑

### CODE REVIEW

**Comment by LightFire53** [comment]
👌

**Comment by Allfd** [comment]
What will we do without 15 minute playtime IAA's butt faxing CentCom?

**Comment by Kyep** [comment]
@Allfd rejoice?

**Comment by Spacemanspark** [comment]
Don't worry, I'll just get the HoS to do it

**Comment by FlattestGuitar** [comment]
Ten hours is barely enough experience to play as a security officer, but far too little for Head of Security. 

These numbers should be much, much higher.

**Comment by Twinmold93** [comment]
Deciding the ultimate playtime for Head of Security vs other roles is not in the point of this PR. This is merely to, one, make the high-end roles of Captain and AI, mirroring the original intention, have a higher time requirement than normal head roles, and requires some actual experience on the station prior to jumping into Internal Affairs, which is already expected to know a lot in terms of Space Law and Standard Operating Procedure.

**Pull request merged**
