### PR TITLE
Atmosia/Medistan/Brigistan/Commandtozka/Scientopia blast door fixes.

### LINKED ISSUE #10264: Medbay Quarantine Doors
**Problem Description**:
What is the problem?

The quarantine button in the CMO's office on the NSS Cyberiad does not close/open the blast doors.

**What did you expect to happen**: 
Why do you think this is an issue?

Blast doors to close.

**What happened instead**:
How is what happened different from what you expected?

They remained open.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

In event of an outbreak, infected people could leave the medbay and spread the infection to other crewmembers.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Press CMO's Quarantine button in their office.
Observe how the quarantine doors do not close.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

Today I noticed this.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

Lowpop.

### PR DESCRIPTION
**Pull request by Shadow-Quill**
**What does this PR do:**

Makes every blast door controller STRONK by BUFF range.
Also fixes #10264 

**Images of sprite/map changes (IF APPLICABLE):**
Didn't add/remove stuff, just changed vars.

**Changelog:**
:cl:
fix: Made Brig/Perma-Brig/Medbay/Research/Engineering/Atmos blast doors open/close correctly.
tweak: Renamed the "Prison Wing" door control button to "Perma Brig" for clarity.
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
Gonna be honest i am not alway keen on editing the objects directly on the mapfiles as it may sometimes cuase issues for mappers later.

**Comment by variableundefined** [comment]
The Re-Northening will have higher priority than this PR.

And yes, it might be better to create a new subtype and then edit the subtype directly instead of this.

**Comment by variableundefined** [comment]
@Shadow-Quill Please make a new subtype of blastdoor with better range and edit the subtype of the blast door instead of directly mapediting them.

Also I see an extreme amount of seemingly unrelated changes in z2 - Did you start from a clean commit? Can you fix that too?

**Comment by Shadow-Quill** [comment]
Dunno what happened, but I'll make a subtype. Closing this PR for now.

**Pull request closed without merging**
