### PR TITLE
White ship Pod-bay

### PR DESCRIPTION
**Pull request by tigercat2000**
### RELIES ON #1084, DNM BEFORE THAT.
The white ship "Pod-bay" is now an actual Pod-bay, instead of a mass-driver.

The white ship pod bay

Travis will probably fail this compile, because I ripped this off another branch, just to make the PR's seperate. WHOOPSIES.

### CODE REVIEW

**Comment by Mijhead** [comment]
:+1:

**Comment by Finalsong** [comment]
noice

**Comment by Spacemanspark** [comment]
:+1:

**Comment by fj45** [comment]
Great, thanks for that.

**Pull request merged**
