### PR TITLE
Heartbeat sound port from Baystation12/Baystation12#8386

### PR DESCRIPTION
**Pull request by tigercat2000**
This ports and adapts Baystation12/Baystation12#8386 to paracode.

Basics of what it does:
* Adds a heartbeat sound to mobs that have hearts.
* Sound only plays when one of the following is met:
  * Mob is in shock (shock_stage > 10)
  * Mob is in space (get_turf /turf/space)
  * Mob's pulse is over 120 (pulse >= PULSE_2FAST)
* Does not play if mob has a robotic heart.

Edit:
* New thing: SOUND_HEARTBEAT
  * Preference option that allows you to toggle heartbeat sounds on and off.

* Another new thing: Different sounds for assisted and mechanical hearts.
  * Mechanical hearts (and machine people) get a dubstep-like sound.
  * Assisted hearts get the first part of the mechanical heart sound, followed by a normal heart beat.

EditEdit: Made a small demonstration video for listening to the sounds.
https://youtu.be/rCR60fjyyiQ

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Big thumbs down to this one unless it's a player config option---sorry, but I don't want to be hearing my own heartbeat 24/7 just because I'm in space or happen to be using several drugs; miners and engineers already have enough going against them; having a repetitive heartbeat sound play 24/7 is just going to get distracting (nukies as well).

**Comment by tigercat2000** [comment]
It plays once every 6-7 seconds in my experience, and it isn't very loud. It really isn't as distracting as it seems like it would be. It's more of a subtle-indicator type deal, that your pulse is either too fast, you are in shock, or you are in space.

**Comment by Spacemanspark** [comment]
I like it.

**Comment by Fox-McCloud** [comment]
Let me clarify; I have no problem with this IF it's a config option (like environmental sounds, music, etc), otherwise :-1: for me.

**Comment by tigercat2000** [comment]
Can do, working on it now.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by fj45** [comment]
Not sure about it playing in space, wouldn't mind having sounds in space return completely. As "unrealistic" it is, it just doesn't work to have everything quiet.

**Comment by tigercat2000** [comment]
@Fj45 if that decision is made, I'm sure it wouldn't be too much of an issue to revert this PR. 
As for now, however, space is pretty quiet with only the ambient space sounds, so this gives it a bit more of a creepy atmosphere walking around outside the s tation.

**Comment by Fox-McCloud** [comment]
@fj45 

With the way this is set up you can turn it off if you don't like it.

**Comment by fj45** [comment]
Yes, just saying that I would much prefer sounds to still exist in space. Not really for this PR though.

**Pull request merged**
