### PR TITLE
Replace if (/while (/ for( with if(/while(/for(, add to contributing guidelines.

### PR DESCRIPTION
**Pull request by tigercat2000**
:eyes:

Regex:
Find: `(if|for|while|switch)\s+(\(.*?\))`
Replace: `$1$2`

### CODE REVIEW

**Comment by monster860** [comment]
Can you also do `for (` and `while (` ?

**Comment by KasparoVy** [comment]
All praise :+1:

**Comment by monster860** [comment]
You are going to cause so many merge conflicts.

**Comment by tigercat2000** [comment]
@monster860 naahh
@TheDZD @Fox-McCloud speedmerge :eyes:

**Comment by PJB3005** [comment]
\> ruining the coding standard.

People separate the if and the parentheses because it makes it easier to see it's a keyword and not a function.

http://stackoverflow.com/a/7457346

**Comment by tigercat2000** [comment]
@PJB3005 
```
$ grep -rn 'if (' code/ | wc -l
   7006
$ grep -rn 'if(' code/ | wc -l
  49289
$ grep -rn 'for (' code/ | wc -l
    592
$ grep -rn 'for(' code/ | wc -l
   5694
$ grep -rn 'while (' code/ | wc -l
     49
$ grep -rn 'while(' code/ | wc -l
    406
```

**Comment by PJB3005** [comment]
That's like saying we should've continued to use relative pathing because it was used more a few years ago.

"this is how it is already" is the worst argument ever.

**Comment by tigercat2000** [comment]
it's literally entirely a styling thing
it should be consistent one way or the other

**Comment by TheDZD** [comment]
This is going to conflict with just about anything and everything.

**Comment by tigercat2000** [comment]
only minor conflicts~

**Comment by monster860** [comment]
@tigercat2000 Also, you should probably do `switch (` as well

**Comment by FreeStylaLT** [comment]
I click files changed.
Browser is kill.

**Comment by taukausanake** [comment]
I think I'm one of those guys who likes actually putting spaces in. Treat it like a word, as its own bit. I guess for SS13 the space could/should be omitted because procs don't use spaces between their name and arguments.
Eh, probably not going to stop me or others from doing it still. Habit and all

**Comment by tigercat2000** [comment]
@taukausanake then i'll be there to comment on the PR and point out that it violates contributing standards

**Comment by TheDZD** [comment]
Merge conflicts go!

**Comment by tigercat2000** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by PJB3005** [comment]
👎✖💯➕1

**Pull request merged**
