### PR TITLE
Ports TG medibeam

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do

Ports TGs updated medibeam sprite.

Sprite taken from https://github.com/tgstation/tgstation/pull/14861
## Why It's Good For The Game

It's a way better sprite compared to the blue squiggly line we were using before

## Images of changes

yes its animated I am just lazy and don't want to make a gif. go look at icon diff please.

image

## Testing

In game.

## Changelog
:cl: Bmon, Gun Hog, WJohn
imageadd: Ported new medibeam sprite from TG.
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
Pretty cool beam (try not to cross it)

**Comment by procdrone** [comment]
how does it look on angles?

**Comment by Bm0n** [comment]
> how does it look on angles?

image

**Review by Sirryan2002 — APPROVED** [review]
sprite diffs look good, no code changes

**Pull request merged**
