### PR TITLE
The Nations Update Everyone Deserves!

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Already discussed this, and this needs to go.

It's a terrible "game mode" that is never run, snowflaked into `Life`, requires some server rules to be suspended, has no underlying goals or good design direction behind it, and it's not going to be updated or maintained. It's really only used for adminbus. If people want to do that, they're welcome to use extended.

If you want chaos and slaughter, we have a *perfect* game mode for that, already. It's called "Revolution" and actually has design principles behind it.

img

And yes, if you couldn't tell, I have nothing but disdain for this **"game"**  **"mode"**

:cl: Fox McCloud
del: Updates nations. Updates nations so hard right into the void
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
https://www.youtube.com/watch?v=KolfEhV-KiA

**Comment by Kyep** [comment]
For the record, I support this removal.
Nations is a terrible game mode, and even worse from an admin POV.

**Comment by Ty-Omaha** [comment]
Improve, don't remove

**Comment by Bookdrizzt** [comment]
I like nations as a concept, and I’ve had some great nations experiences. As Ty said, I’d rather you improve it then just say ‘fuck it’. It’s more innovative and fun then rev, to say the least.

**Comment by Ty-Omaha** [comment]
Nations is a special gamemode because, while you may dislike it, it has an appeal.

The beauty about it is that the "direction" is not forged objectives that are the same 24/7, the players, nation leaders and admin events decide the direction of that round. I would say this is a much more interesting story and game design than the same "Steal this, kill that, dont get caught by sec, escape" repetitiveness. 

Nations is rarely ran, to keep the novelty of it. "It isn't going to be maintained or updated" - I could say that about revolution, devil, or a lot of other gamemodes. Nothing is being "maintained or updated" unless there is an active project doing it.

Comparing nations to extended adminbus is really far out there. Extended adminbus doesn't result in each department becoming it's own nation, with it's own nation leader / heir and nation HUD icons etc.
Can it be used to do that? Sure, however; that's equivalent to removing the trader ship system and manually doing it.

The Nations mode builds tension and has political aspects to it. Revolution is running around flashing anyone you see. Nations has a story. These two modes are extremely different.

There is currently 1 open issue about something regarding nations. While it has been open since 2016, there are many other issues that are similar as well so it is not isolated to a "nations" problem. If attention was brought to that issue it is far more likely that someone will fix it. Coders typically not going back to issues from 2016 to solve.

Saying "it's snowflaked" is not a strong argument for removal. Things can be refactored to proper code standards, but if nobody brings it up then nobody is going to know. This is a good use for the #changes-wanted channel in discord where maintainers and head admins can put changes they want.

All in all, nations has much more than "chaos and slaughter". The nations round that happened a week or go did not have any slaughter until well into it, roughly 1:30 into the round.

**Comment by Ty-Omaha** [comment]
Also:

>Already discussed this, and this needs to go.

Where was this discussed?

**Comment by craftxbox** [comment]
again think that there still really shouldnt be a reason to remove features after theyve been added, unless theyre a problem, which i havent seen nations being a problem at all.

**Comment by Dinarzad** [comment]
Do it.
Doooooo iiiiiiiit.

Nations, most of the time devolved into a giant station-wide Team Deathmatch, tothe point that if I honestly think that Nations is a real possibility in a round, I *stop playing.*
I will spectate just to try and avoid dodging nations rounds.  Yeah when Nations DOESN'T devolve into "those people aren't us, kill them." mentality, it can be kinda interesting.
But not enough to be worth the other 8 out of 10 times it turns into a miserable slog. It's also the same kind of interesting you can get out of other round types or making use of Extended an custom events.

**Comment by Fox-McCloud** [comment]
>Where was this discussed?

Headmins and maintainers had a discussion about it, how toxic it was, and how poorly designed it is. We came to the conclusion it's not worth saving, especially since it's snowflaked into everywhere.

**Comment by craftxbox** [comment]
you may have more experience than me, but out of the three nations rounds ive played in the past six or so months, i havent ever seen nations devolve into a TDM. And again, because something isnt liked but is optional and doesnt *really* cause much problem (that i can see yet)

**Comment by Quantum-M** [comment]
While Nations was/is dreadful in it's own ways, it's less worse than Revolution, which usually just devolves to murderous greytide or a round long stand off as command was fast enough to hide behind security and security is being competent.

**Comment by EvadableMoxie** [comment]
It's already out of the rotation, why remove it? Admins do sometimes run it and people enjoy it.

**Comment by Spacemanspark** [comment]
While it's often a trash fire...

It's not in the rotation, as previously mentioned, and if we're going this route we should also remove Meteors, Revolution, Heist, et cetera.

I've seen nations rounds that make me want to bash my head through a wall... and the Nations rounds that pleasantly surprised me. I don't support it being re-added to rotation, and I can't really think of any way to improve it immediately off the top of my head, but I don't really see the need to outright remove it.

**Comment by granodd** [comment]
You kind of had me up until you said "Revolution".

**Comment by Kyep** [comment]
I have pinged all heads/maints on this topic, and to the best of my knowledge:

- Several heads/maints (including me) favor the outright removal of nations
- NOBODY (to the best of my knowledge) is willing to defend it as a game mode

Why?

Several reasons:

- It hasn't been updated in a long time, and nobody is willing to update it. People have promised to update it in the past, but then failed to do so.
- It is so unpopular among admins that some will occasionally joke "hey, at least this round isn't NATIONS".
- The root cause of that unpopularity is that it is incredibly difficult to admin a nations round. It requires constant babysitting, often by multiple admins, and a game mode that requires that just isn't practical.
- While many players may ask for nations in OOC before roundstart, many of these players have never actually PLAYED nations, much less been charged with keeping the round fun during it.
- Fundamentally, most of the game is designed with the assumption that the crew is largely on the same side, when you break that fundamental assumption, you break the game. Suddenly, everything, even basic stuff like the supply of power and air, become a battle.

**Comment by farie82** [comment]
The rare times I played nations it usually made some interesting stories. It's something the player base knows yet rarely plays and that is what makes it so interesting. Removing it will once again remove something the player base knows and likes without once again a valid reason.

Instead of removing things why not make them better if they need improvement? Yes it costs time and work. But removing something that is still used sometimes is not a good practice.

**Comment by AffectedArc07** [comment]
I agree on this

Of all the times I have played nations, I have __never__ enjoyed it. Its always a fuckfest that I only see enjoyed by the people with murderboners breaking out of their jeans. A removal of this would make the server better, and would stop all the constant roundstart nagging for nations.

Nations is a pain for people that just want to play a normal round, a pain for the admins that have to manage the shitfuck, and it adds a lot of confusion for new people who may think its normal


Why wasnt this done sooner?

**Comment by KasparoVy** [comment]
I've always wondered just how it felt to administrate those rounds. Glad I didn't have to ask!

**Comment by davidchan13** [comment]
I'd rather see the 'Improve don't remove' mindset get enforced here. While there certainly are problems with the gamemode, it does see semi-regular use. It's not a conversion mode like Revolution or Cult, it is a sovereignty mode where each department is it's own separate entity. 

Yes, it needs to be reworked, goals given to each department and better distinction of who belongs wear. The AI/Borgs need a rework as it's impossible for borgs to follow and enforce their laws without the AI constantly checking what cameras actually work since Borgs can't remotely view a camera and see if it's actually functional or the focus lens was cut, let alone which cams have xray.

It is an adminbus round type in the same vein as highlander, and while a headache for some it is none the less amusing and a good change of pace from the repetitive traitor/ling/vamp mix and match rounds. Why is nations on the block when it can only be triggered by an admin, when things like [ponies ](https://github.com/ParadiseSS13/Paradise/blob/6fe83a698757f023d26171355fff906d95ee764b/code/modules/mob/living/simple_animal/pony.dm)are still in the code?

**Comment by Fox-McCloud** [comment]
So the primary reason this is being gotten rid of is that there's no good design flow or purpose for nations. It's something that can just as easily be done on extended without any fancy mode to back it up. There's no goals, there's no direction, and there's no unique mechanics to it.

This isn't to say we can't have open ended game modes that leave some things up to the players, but this isn't it.

The reason Rev and a number of the others are still around is that they're effectively finished out game modes. Rev is not likely to change much; it has a very solid and very basic underlying design behind it and a clear, precise goal.

Heist I do not defend; it does need to be reworked. @FlattestGuitar had plans, a couple years back, to do so, but got side-tracked and realized it was going to be harder than he thought. He wanted to make it more general space pirates with goals that were more mischievous and not so aimed at interacting with only command.

Abductors? Really? Abductors can come up any shift as a mid-round antag; the event utilizes the game mode to run properly (it runs a temporary instance of it).

The mode has never been updated since it was put in a few years ago--the only times anyone has touched the code was when Fethas refactored HUDs. Yes, I know Rev hasn't been touched in a long time, but that's essentially because it's in a finished state (like traitor or changeling); the goals and design direction for it have already been established.

Nations? There's no design direction. There's no goal. It doesn't even know what it wants to be; it's just extended with a few HUD icons and admins willingly suspending the rules whenever nations pops up.

Mutiny was a bad game mode, but at least it had goals in mind and a design direction...and nations has FAR less meat to it than mutiny ever did.

**Comment by Ralta** [comment]
I actually really like Nations _occasionally._ It's not in rotation but as an occasional event to change things up, it can be a lot of fun. I'd really rather it didn't get removed, as it's not super-common as it is.

**Comment by Ty-Omaha** [comment]
>There's no design direction. There's no goal. 

Why exactly does something need a set in stone design direction? SS13 is a roleplaying game after all.

**Comment by Ty-Omaha** [comment]
>"It's not updated and nobody is willing to update it"

I just made a PR to update it (which spawned this removal PR). Sure it was a minor update, but it was still an update.

> "Nobody is updating it" 

Re-iterating what I said earlier - there hasn't been any effort to actually _get_ someone to update this.

**Comment by Ty-Omaha** [comment]
> there's no unique mechanics to it.

Nation leaders can set nation heirs, AI and synthetics get a space geneva convention lawset and nation borgs, people get HUDs indicating their faction, people's IDs are renamed to their nation such as "Medistan" etc

**Comment by Ty-Omaha** [comment]
>I only see enjoyed by the people with murderboners breaking out of their jeans.

I have seen otherwise

>Nations is a pain for people that just want to play a normal round

Normal rounds happen 99% of other times, we should remove all non-normal rounds then.

>a pain for the admins that have to manage the shitfuck

Was not that much of a pain last week

>and it adds a lot of confusion for new people

Every event will do this to new players, the other non-rotation modes will also do that.

**Comment by Rurik123** [comment]
Would this mean that maybe Revolution, the superior and ultimate gamemode, will be played more in its place? :thinking:

**Comment by Dave-TH** [comment]
The commit history exists for a reason, if any one of the people saying that Nations should be improved instead of trashed it's no big deal to reverse history locally and make the changes that turn this into something playable. As of right now, however, this is major bloat that exists for admins to force it 1-2 times a month as a joke to remind people of how awful it is.

**Comment by daylight2** [comment]
The main objection aganist this seems to be that it's a pain for the admins to manage and requires a lot of babysitting, which should defenatly be a big red flag for any normal game modes. Howerever, with nations being a admin-only game mode, I'd think that admins would be ready to put up with all the difficulties of the gamemode when they choose it. If absolutely none of the administrators are willing to deal with nations, how come it gets selected a few times every month? Nations is a semi-meme gamemode that's only triggered when the admins feel like running it, and just because a portion of staff doesn't want to administrate for it, doesn't mean that the reast should be banned from doing it whilst said portion is away.

**Comment by shazbot194** [comment]
Not saying that I support or approve of it being removed, but wasn’t there a PR to just remove xenomorphs from rotation that was shot down because it should be improved rather then removed (from rotation).

**Comment by Dinarzad** [comment]
> If absolutely none of the administrators are willing to deal with nations, how come it gets selected a few times every month?

Because people usually spam round start OOC begging for it and eventually people cave.  You have to understand it's just as likely to be "Sure we can do nations!" as it is to be "Uggggggh.... I mean.... Yeah I guess..."  when they choose to run it.  It's not always being run because they enjoy it or wanna run it, but because they're trying to be nice an give the thing some people are asking for even though it's a miserable experience on themselves and the players who don't want it.

Because that's what it is. It's some players forcing everyone else to shuffle through something they hate so that THEY can have a good time. There's lots of game modes people may not like, but those are very rarely forced to occur and are just unfortunate RNG. nobody AMDE blob happen, that's just how the dice fell. Nations is not in rotation so whenever it happens it really is some people forcing everyone else to experience a game mode they, in my case, vehemently hate so that they can have fun at everyone else's expense. Like I said I *literally stop playing* when I see it's Nations. 
 Just because Nations will be gone as a game mode, doesn't mean Nations-esque events can't be held via extended.

**Comment by craftxbox** [comment]
You're forgetting that people screaming 'nations' in pre/post round ooc most of the times arent legitemate requests. And that other people exist too.

**Comment by Ty-Omaha** [comment]
> It's not always being run because they enjoy it or wanna run it, but because they're trying to be nice an give the thing some people are asking for even though it's a miserable experience on themselves and the players who don't want it.

Nations is ran sparsely when we think it would be a good mixup and want to. We don't just force nations because of people saying "NAYSHUNS" in chat.

>Because that's what it is. It's some players forcing everyone else to shuffle through something they hate so that THEY can have a good time.

Every single gamemode shares this logic of putting up with things that people don't like. The thumbs-up and thumbs-down on this github are pretty close so the gamemode itself is not as polarized as you make it out to be. 

>"You aren't allowed to run this mode because we (group B) dislikes it!"

Demanding that group A submits because group B dislikes something is the same logic.

Your arguments can easily be flipped around, as demonstrated above. Since the beginning of 2016, there have been 59 nation rounds according to the bots. There has been a total of 9945 rounds since then, with some room for error. Let's subtract 100 to be safe.

**59 / 9845 x 100 = 0.59%** 

This is less than 1% of rounds, and demanding that group A submits because group B dislikes something that happens 0.59% of the time is pretty selfish in my opinion.

>Just because Nations will be gone as a game mode, doesn't mean Nations-esque events can't be held via extended.

If an admin runs an event where NT has severed all ties with Cyberiad, makes every department it's own nation, without all the mechanics; that is the same. It's like eating chocolate icecream with sprinkles and eating chocolate icecream without sprinkles. The custom mechanics of nations being the sprinkles.
This would result in the same people who dislike nations be upset with the extended adminbus. The only difference is that there are not mechanics backing it.

**Comment by Ty-Omaha** [comment]
I do think nations can be improved, however if nations is removed I do not think any PR improvement to it would get merged after the fact.

**Comment by Dinarzad** [comment]
> And that other people exist too.

I don't see how that logic doesn't work both ways Craftxbox.
You're basically saying "Well other people like it."
and the counter to that is "Well, other people DON'T like it." 
The fact some people actively hate the round and other people ask for it to be forced regardless is asking for group B to be subjected to things Group A wants, in spite of them not liking it.  Group B is not selfish for not wanting to do it.  Group A IS being selfish by forcing other people to 'deal with it'.



> Every single gamemode shares this logic of putting up with things that people don't like.

Ty, you either missed or glossed over the entire point of that section.  Other game modes **aren't forced.**.  If someone hates blob and gets a blob round, nobody forced that to happen, RNG just dictated it would happen, it was bad luck for that person.  Nations not being in rotations means that an active choice was being made to choose Nations. That's completely different circumstances.  One is tough luck on a coin flip or dice roll, the other is going "Screw you guys, we're doing what I want."

> Demanding that group A submits because group B dislikes something is the same logic.

It absolutely is not.  Group A isn't being told to be subjected to something they dislike, it's not like Group B is out here going "VOX TRADERS OR RIOT."  Group A is being told that them forcing the game mode is actively ruining the experience for Group B, and that they can still get a Nation's-esque experience via an event which is a lot more hands on, and given the round landed on Extended, isn't something that was forced into happening, the rotation landed on extended and an admin is making use of it to do a Nations event.

Telling someone they don't want to do something isn't selfish in the faintest. I don't want to do the thing, I am not GOING to do the thing, and every time someone asks if I want to, I am going to vocally say "Guys, I don't want the thing."  If someone tells that person "Too bad we're doing the thing." Yes. That is Selfish. That is the actual definition of it, which is as follows:
"(of a person, action, or motive) lacking consideration for others; concerned chiefly with one's own personal profit or pleasure."

If someone tells you they don't want to do something and you force it on them anyway, I don't know what to tell you. It is forcing a thing someone doesn't want onto them regardless of protest. Removing it isn't forcing anything on anyone.

> This would result in the same people who dislike nations be upset with the extended adminbus.

And that should tell you exactly how problematic that game mode is to a lot of players.

**Comment by Ty-Omaha** [comment]
>Ty, you either missed or glossed over the entire point of that section. Other game modes aren't forced.. If someone hates blob and gets a blob round, nobody forced that to happen, RNG just dictated it would happen, it was bad luck for that person. Nations not being in rotations means that an active choice was being made to choose Nations. That's completely different circumstances. One is tough luck on a coin flip or dice roll, the other is going "Screw you guys, we're doing what I want."

>It absolutely is not. Group A isn't being told to be subjected to something they dislike

"We dislike **not** having nations", therefore they are being subjected to something they dislike. 

>Telling someone they don't want to do something isn't selfish in the faintest.

I have no problem with people saying they don't want to do something, your argument is "nations should NEVER be played because we  dislike it!"


>If someone tells you they don't want to do something and you force it on them anyway, I don't know what to tell you. It is forcing a thing someone doesn't want onto them regardless of protest. Removing it isn't forcing anything on anyone.

>aren't forced

Someone doesn't want wizard but RNG forced it. I fail to see why this is an issue because it's a human making the decision instead of a robot. It is virtually impossible to have 100% of people collectively like something. If it was coded to play once a month it would be no different, except that a human isn't forcing it, a robot is. Just because people demand X does not mean they will get X.

If I did a dice roll and said 1 = nations 2 = not nations would that be forced? Yes, because I forced a dice roll and gave it legitimacy. 

The main issue I seem to be getting from your argument is that a human is making a decision instead of a robot. People's opinions are taken into account when nations is forced, however if group A wants it and group B doesn't want it, we're again left at a situation where 100% of people do not get what they want.

**Comment by Ty-Omaha** [comment]
>"(of a person, action, or motive) lacking consideration for others; concerned chiefly with one's own personal profit or pleasure."


**"No, we aren't doing it because group A said no."**
-Not selfish
**"Yes, we are doing it because group B said yes. (paired with additional factors such as when the last time it was ran)"**
-Selfish

This logic is not exclusive to your side, please understand this.

**Comment by Dinarzad** [comment]
> "We dislike not having nations", therefore they are being subjected to something they dislike.

That isn't how that works and you know it. 

> I have no problem with people saying they don't want to do something, your argument is "nations should NEVER be played because we dislike it!"

That is also not my point at all and you've entirely misrepresented everything about it to make arguing against it easier. I and others have said Nation-style events can still be had via Extended style admin custom events. Extended exists to be the realm of admin shenanigans of whatever variety they so choose.  *THAT* is the point. Group A is not losing ANYTHING.

> Someone doesn't want wizard but RNG forced it. I fail to see why this is an issue because it's a human making the decision instead of a robot.

If you can't see the issue between a random dice roll and someone knowingly choosing to go against your wishes then I can't argue anything with you.  Here's an example.
You an some friends want to go out for dinner. Most the options are fine but one is REALLY not to your taste, like you can't bear the stuff.  So you all roll a dice.  It lands on that thing. Shucks and gosh oh well, luck wasn't on your side you'll grab something to eat elsewhere.  OR.  You tell your friends you REALLY don;t wanan go there cuz you can't stand it and half your friends agree. But the other half go "That's too damn bad cuz we're going there now."

One of those was random chance, it was fair for everyone.  The other was someone shutting down anything the other half wanted to enforce what they wanted at their expense. 

> "No, we aren't doing it because group A said no. (paired with additional factors such as the dislike for it)"
-"Not selfish"
"Yes, we are doing it because group B said yes. (paired with additional factors such as when the last time it was ran)"
-"Selfish"

Ty that's... that's not how that works. Especially when half the bloody staff is in agreement that they don't want it. At this point it's being actively argued that people should just deal with not liking it because they want something that they like and damn the consequences. At this point you're about the only admin I am seeing so vehemently arguing for it, and the roundtype is absolutely predicated on administration being willing and available to make sure everything runs smoothly. So if even the majority of people running the thing can't stand it's presence, why SHOULD it stay?

People keep saying to "improve not remove" and yet not once until this very moment has anyone shown even the vaguest interest in doing so.

**Comment by craftxbox** [comment]
```People keep saying to "improve not remove" and yet not once until this very moment has anyone shown even the vaguest interest in doing so.```  
Thats because nobody has been asking for it. And everybody has been saying stuff like 'dont bother updating nations its shit anyways'.

**Comment by davidchan13** [comment]
And much like the eggborgs, if a vocal minority of the community doesn't like something, nobody else is allowed to.

**Comment by Dinarzad** [comment]
> And much like the eggborgs, if a vocal minority of the community doesn't like something, nobody else is allowed to.

If what you like is actively impairing other people's good time, and you still have plenty of other things you enjoy just fine about the server, then it needs to be discussed. That's a massive exaggeration of the argument. People ARE being told "This game mode actively ruins my experience playing the game" however. You can like it all you want, what we're talking about is removing it for a multiple amount of design flaws that anyone, at any time, can go fix.
And if we go by the up/downvotes on this PR as an example, it seems like a nearly 50/50 split. I wouldn't exactly call **half** the people involved in this debate a "Vocal minority" would you?

> Thats because nobody has been asking for it. And everybody has been saying stuff like 'dont bother updating nations its shit anyways'.

Of course nobody's been asking for it, that's the POINT. Nobody was slightly interested in this game mode, and if it had been removed and nobody had said a word about it, nobody WOULD have cared, that's how meaningless this entire "IMPROVE DON'T REMOVE" argument is in this debate. Nobody would have even noticed, nobody would have gotten upset, and you'd never even realize it was gone.  So why fight tooth, nail and claw over something you objectively would never have even noticed was missing if nobody had told you?

And again. I put forth, what is stopping any of you from going, right now and making improvements yourselves? Because NOBODY has said 'Don't bother updating it' even a single time. You are making that up entirely in your head.  What HAS been said are the multitude of design flaws the roundtype has on a fundamental level.  It's been called shitty and flawed, but nobody has ever said they should not or are not allowed to go try and work on it if they want to.  But that isn't what THIS PR is about. If one of you wants to improve nations and change it up, by all means go do so and make a PR re-introducing it with improvements. In terms of THIS PR we're talking about removing it.

**Comment by craftxbox** [comment]
I should clarify, nobody asks for it because alot of people dont know how nations plays in thew first place

**Comment by craftxbox** [comment]
today is a sad day.

**Comment by Diegoflores31** [comment]
i would call nations a Team death match , and no its not the same , revolution is something you are like forced to do but , in nations everything can happen , its like the purgue but in ss13 is fun , and not so dont remove  lel

**Comment by Diegoflores31** [comment]
welp neverming , why you even make a pull if its going to get instantly merged ,_,

**Pull request merged**
