### PR TITLE
Delta firing range moving target fix attempt 2

### LINKED ISSUE #19682: firing range console on the NSS Kerberos does not work
**Issue Description**:

firing range console does not work

**What did you expect to happen**: 

it to move the target

**What happened instead**:

it did not

**Why is this bad/What are the consequences**:

security will continue to be unable to shoot if their life depended on it

**Steps to reproduce the problem**:

try any command in it and it still will not work

**When did the problem start happening**:

honestly this is the first time i tried improving my aim in a nonviolent manner so i can't say

**Extra information**:

### PR DESCRIPTION
**Pull request by DevanStrife**
## What Does This PR Do

Fixes #19682

Accidentally closed the previous PR trying to fix a merge conflict so ye. See #19750 for old PR

Puts the required gravity node below the target that allows it to be manipulated by the target console.

## Why It's Good For The Game

Things working as intended are good!

## Images of changes

Screenshot (83)

Screenshot (84)

Screenshot (85)

## Testing

Spawned in and put the target on the moving target stand.
Used the target console to make it move.
It moves!

## Changelog
:cl:
fix: Fixed the delta firing range target not moving
/:cl:

### CODE REVIEW

**Review by Sirryan2002 — APPROVED** [review]

**Comment by hal9000PR** [comment]
I am no expert with maps but I am pretty sure they shouldnt have this big of a diff for such a tiny change.

**Comment by DevanStrife** [comment]
Yeah, i had to merge all the new changes into it to make it not have a merge conflict. I dobt know if there is any other way to do it.

**Comment by S34NW** [comment]
Please run mapmerge, found in `Paradise\tools\mapmerge2`

**Review by S34NW — CHANGES_REQUESTED** [review]
Please run mapmerge, found in `Paradise\tools\mapmerge2`

**Review by S34NW — APPROVED** [review]

**Comment by SteelSlayer** [comment]
This PR now leads the Delta queue. Once this is deconflicted, this can be merged.

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
