### PR TITLE
people who don't breathe don't get affected by smoke

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
I have multiple reasons for proposing this change, first and foremost, internals completely stop smoke and everyone starts with them. That makes sense, but then why do races who don't breathe or need internals at all need to put them on just to deal with smoke? it's inconsistent. N2O Plasma and CO2 don't affect those who don't breathe either.

Second of all, I feel like racial bonuses should be just that, a bonus. If we're going to boast not breathing as a bonus then we really shouldn't be punishing races who don't breathe for not wearing internals when getting hit by smoke.

If the counter to smoke is so easily obtainable(everyone starts with it) I don't understand why races who don't breathe shouldn't be able to innately be immune to it.

**Changelog:**
:cl:
balance: People who don't breathe don't inhale smoke anymore
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Being immune to stuff like pepperspray, stun chems, breathable poisons, and the likes is insanely powerful--it's one of the reasons why, over the years, smoke has *deliberately* applied to species that can breathe. 

Yes, I know, touch based reactions still apply, but most of your chem shenanigans don't use touch based reactions.

If you want to counter smoke, then you're going to have to do so like everyone else; wear a gas mask.

It's similar to Xenomorphs---"but species that breathe wouldn't get knocked out by them or suffer any ill consequences from it". Yeah, true, but there's bigger factors at play here---it too negatively impacts the balance of a lot of things, while having virtually no downsides to go along with it.

For that reason 👎

**Comment by Couls** [comment]
That's the thing, the downsides and upsides aren't self-contained. The races are balanced around their bonuses and downsides all together. On it's own having the ability to not breathe could SEEM overpowered but you have to consider that every race that doesn't have to breathe already has downsides(IPCs instadie from EMPs, diona move stupidly slow and are immediately killed by weed killer, slimes are weak to cold and require SR to revive and also take increased brain damage). I think its so silly to stack all these downsides on these races for the upsides if the upsides are just gonna be neutered anyway for the sake of unity and general balance. Weaknesses need to be balanced by strengths and I don't think not breathing is strong enough to make all the downsides worth it

**Comment by Denthamos** [comment]
Hrm, on one side I like keeping things lore straight for mechanics but at the same time you have to draw a line for balance reasons.

Becoming immune to any smoke and breathing based chem is a very powerful thing by default simply by the fact you are always immune to such in a period of no warning which is when they are strongest.

Honestly I am on the fence about such a thing due to potential meme chem shenanigans that could follow with it.

**Comment by Sikroth** [comment]
A problem I see with the current implementation (nonbreathing species being vulnerable to smoke) is that, in a way, they are even more vulnerable than regular species, if you think about it. Let me explain.

You don't need to breathe, so therefore why would you keep internals with you? It's literally a waste of space. Except mechanically, because balance, if you happen to run into someone using memechem smokes, now your lack of internals means you're screwed. Your non-breathing ironically makes you weaker to a breathable smoke.

Another point is, while the counter to smoke is simple and readily available, by design nonbreathers shouldn't need to have it around. And at this point, keeping an otherwise useless item with you "in case someone attacks me with smoke" feels a bit powergamey, even.

I entirely acknowledge the balance issues this raises, even if the species already have weaknesses to compensate for it, but currently I think this is a very counterintuitive design choice in several ways.

I know this would make for a much bigger PR, but maybe we should considering expanding the touch effect of a lot of chemicals, especially dangerous ones (this'll also make for more interesting play/counterplay imo, but again, big scope). That way protecting yourself with just a gas mask (or by not breathing, assuming this is merged) would be less "overpowered" and nullify smoke completely.

**Comment by Necaladun** [comment]
The real solution here is using a gas mask for a lot of them. Sure it doesn't make some sense from a lore point of view, but balance wise this is how it kinda needs to be.

**Comment by variableundefined** [comment]
Closing for reason Fox stated. While this might be flavourful it would affect balance badly.

**Pull request closed without merging**
