### PR TITLE
Plain and Fancy Gold and Silver Tiles

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Added the old gold tile sprites, now gold and silver tiles can be used in hand to change them into fancy/non-fancy versions via recipes.
Sprites from tgstation
gold
silver

:cl:
add: You can change gold and silver tiles into fancy versions by using them in hand.
/:cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Fancy.

**Comment by Draconic-saint** [comment]
These give me a headache...

Less than the gold tiles, but still a headache...

**Comment by taukausanake** [comment]
Can't we get something that looks a little more silver-y?

**Comment by LightFire53** [comment]
I personally prefer the current/top silver tiles. The gold/new silver tiles look outlandishly gaudy

**Comment by KasparoVy** [comment]
If we're making silver floors, we might as well make them totally pimped out

**Comment by Fox-McCloud** [comment]
If I'm honest, I kinda wish the gold floors looked more like the *current* silver floors, above.

I'm with @LightFire53 on this one; they look reallyyyy gaudy.

**Comment by uraniummeltdown** [comment]
They're a bit gaudy I agree but they can look very cool, just got to see a hallway or nicely designed room full of them.

**Comment by Necaladun** [comment]
Yeah I prefer the plain silver too. Where does the blue even come from!?!? Oh, bluespace I guess.

But yeah, plainer silvery is better. Maybe an option for different floor tiles if combined with...something?

**Comment by Anticept** [comment]
Silver tarnish can hold a blue hue due to interference color. That said, it would be damn impressive for anyone to be able to use this to the effect of creating patterns... so yes probably bluespace.

**Comment by FreeStylaLT** [comment]
Personally, these type of patterns give me nausea. It is a subjective thing, though.

**Comment by uraniummeltdown** [comment]
The different patterns of floor tiles if combined with something seems like a good compromise. There's an old non-fancy gold tile sprite too. I'll come up with something soon

**Comment by Fox-McCloud** [comment]
@uraniummeltdown 

Sure, that'd be good.

**Comment by Anticept** [comment]
> Maybe using a knife to carve/uncarve a pattern in them?

Dwarf. Mothafukken. Fortress.

**Comment by uraniummeltdown** [comment]
Attackby with stacks was giving me a headache so I just made the tiles use recipes instead. Use a gold/silver (fancy) floor tile in hand to change its fanciness

**Comment by taukausanake** [comment]
Follow the yellow brick road. However doesn't look bricky enough for that. I like still

**Comment by Lady-Luck** [comment]
I saw cargo lined with gold tiles similar this the other day, thought this must've gotten merged.

I really do dislike these. They are painful to my eyes.

**Pull request merged**
