### PR TITLE
Removes slaughter demon events.

### PR DESCRIPTION
**Pull request by Corocan**
**What does this PR do:**
This PR removes slaughter demons as a major random event. I don't believe that slaughter demons are finely tuned to the game and generally aren't fun for the crew to fight against. Their kit enables them to too easily move around the map with impunity and when implemented they often take players out of the round indefinitely. It's not uncommon for shuttle calls to be issued either because of, or with significant cause, a single slaughter demon. In all honestly they should be balanced so that it's more reasonable for them to be dealt with, but I think the effort necessary to do that would be wasted and they should just be scrapped as a random event and secluded to wizard summons or adminbuses.

**Changelog:**
:cl:
del: Removed slaughter demons as a major random event.
/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
Major events are supposed to be able to take people out the round and call shuttle calls. Slaughter Demons are strong yes, but they aren't unbeatable. They don't actually have a lot of health so if you can stop them from getting bodies, which is doable if you clean the blood (janiborgs op) Space Cleaner is really easy to make too.

**Comment by lass9030** [comment]
I would suggest actually trying to compile this locally, before making a PR. It's not enough to just delete the file itself.

**Comment by Corocan** [comment]
> 
> 
> Major events are supposed to be able to take people out the round and result in shuttle calls. Slaughter Demons are strong yes, but they aren't unbeatable. They don't actually have a lot of health so if you can stop them from getting bodies, which is doable if you clean the blood (janiborgs op). Space Cleaner is really easy to make too.

Slaughter demons are capable of taking 100 points of damage (Brute or burn). A single laser shot deals 10 damage of burn. A **pointblank** shotgun will typically deal about 6 per pellet, with 6 pellets, ends up with roughly 36 damage of brute. A single consumption of one body from a slaughter demon will return it to full health, which is 100. This, assuming that the slaughter demon gets at least one body per resurface, means that you must shoot this slaughter demon 10 times with a laser rifle or at least 4 times, **pointblank**, with a shotgun to kill it.

I never said they weren't _unbeatable_, I just don't understand how this is reasonable when they **permanently** kill anyone they eat, fully regain their health upon doing so, and can exit a fight as easily as they enter one.

**Comment by TDSSS** [comment]
I see pls nerf 2 electric boogalo

A major event is supposed to shake things up, and slaughter demons are rare and beatable enough. Even if you can't kill it, just keeping the station Clean renders it impotent.

**Comment by Spacemanspark** [comment]
They don't permakill anyone they eat; all bodies fall to the ground when the slaughter demon dies.

The demon itself is slow. Grab a stack of metal rods and stick to the larger hallways, running away and tossing rods at it when it appears.

Stick to large crowds to make yourself less of a target.

Clean the blood with soap or clean spray.

**Comment by Corocan** [comment]
>A major event is supposed to shake things up
>
Shake things up how? Make medbay wanna cryo because the janitor already cryo'd by the time major events start proc'ing?

>Even if you can't kill it, just keeping the station Clean renders it impotent.
>
>Clean the blood with soap or clean spray.
>
Have you ever actually seen the station stay clean long enough for that to be relevant?

>They don't permakill anyone they eat; all bodies fall to the ground when the slaughter demon dies.
>
I use permakill in the sense that these demons generally aren't killed in the rounds they spawn, so it works as a de facto permadeath.

>The demon itself is slow. Grab a stack of metal rods and stick to the larger hallways, running away and tossing rods at it when it appears.
>
Average intelligence demons won't fall for this. Additionally, rods only do 5 brute per throw so I doubt you're going to manage to chuck 20 rods before it realizes it's at a disadvantage and just submerges to find a more isolated victim.

>Stick to large crowds to make yourself less of a target.
>
This isn't really a valid strategy to kill slaughter demons unless you can somehow convince the entire station to stand in one really big circle. Even if you do, most times the only armed crew members are security and ERT, which can easily be killed since they're generally not in large enough force to kill a slaughter demon in one go.

The majority of your strategies completely rely on the slaughter demon making massive mistakes or are purely defensive and don't actually work to actively remove the threat.

**Comment by Citinited** [comment]
> Have you ever actually seen the station stay clean long enough for that to be relevant?

You don't need to clean the entire station, only the bits that are bloody (blood sticks out as it's red). You don't even need to clean all the bloody bits, if you get every bit of blood near you then you're good to go. One exception is medbay of course, but that's likely to be full of people and therefore is going to be quite hard to take on.

Hire a janitorial ERT if you're really struggling

> Average intelligence demons won't fall for this. Additionally, rods only do 5 brute per throw so I doubt you're going to manage to chuck 20 rods before it realizes it's at a disadvantage and just submerges to find a more isolated victim.

Don't fight the demon 1v1, you'll just lose. Team up with a group and don't run off on your own (this advice is also valid for many other antagonists which you insta-lose to, 1v1)

> This isn't really a valid strategy to kill slaughter demons unless you can somehow convince the entire station to stand in one really big circle. Even if you do, most times the only armed crew members are security and ERT, which can easily be killed since they're generally not in large enough force to kill a slaughter demon in one go.

You don't need to "stand in one really big circle", groups of five or six should be okay if a few of you are armed. Cargo can buy guns. Science can print guns. The multitude of greytide can attack the demon with floor tiles. There are many ways to combat the demon.

**Comment by Dinarzad** [comment]
> It's not uncommon for shuttle calls to be issued either because of, or with significant cause, a single slaughter demon.

In fairness, that is sort of the point. Almost all the major events in the round are major, round-shaking events that can make or break a round. Blob spawns, Xenos, Terror Spiders, Slaughter Demons, Abductors, Meteor waves, and on the beneficial side, the Sol Traders.

They're sort of intended to be rounds that break the stalemate, or in the event the antag has been taken care of real early, give a suitable repalcement primary threat to manage.

Major events should be rather major, since they don;t really happen until well into a round. It's not like these can happen at round start. If you die at the hour or longer mark then... I mean that's just SS13, this happens all the time.

**Comment by Corocan** [comment]
>You don't need to clean the entire station, only the bits that are bloody (blood sticks out as it's red). You don't even need to clean all the bloody bits, if you get every bit of blood near you then you're good to go. One exception is medbay of course, but that's likely to be full of people and therefore is going to be quite hard to take on.
>
Medbay tends to be the location where the demon slinks around the most and perpetuates its own filth due to the nature of itself. It tends to be extremely difficult to keep it completely clean. If anyone bleeds, it's generally used as a window for the demon to get in and once it's in, you can guarantee there will be blood used to get out.

>Don't fight the demon 1v1, you'll just lose. Team up with a group and don't run off on your own (this advice is also valid for many other antagonists which you insta-lose to, 1v1)
>
 Although that is very wise, demons can pick their fights, crew generally can't.

>You don't need to "stand in one really big circle", groups of five or six should be okay if a few of you are armed. Cargo can buy guns. Science can print guns. The multitude of greytide can attack the demon with floor tiles. There are many ways to combat the demon.
>
Same problem, and arming the crew generally depends on where the captain falls in terms of how bad is the threat of the demon.

>Why did you paste the code into itself, more importantly why did you stage it?
>
im _really_ new to github

>In fairness, that is sort of the point. Almost all the major events in the round are major, round-shaking events that can make or break a round. Blob spawns, Xenos, Terror Spiders, Slaughter Demons, Abductors, Meteor waves, and on the beneficial side, the Sol Traders.
>
>They're sort of intended to be events that break the stalemate, or in the event the antag has been taken care of real early, give a suitable repalcement primary threat to manage.
>
>Major events should be rather major, since they don;t really happen until well into a round. It's not like these can happen at round start. If you die at the hour or longer mark then... I mean that's just SS13, this happens all the time.
>
I'll concede to those facts. I don't complain if I get hived by xenos or if I get killed by a blob or if a cow collides with my body at mach 1. I'm not arguing about the fact that slaughters are lethal, I'm more so concerned about how there's not really a decent counter beyond making sure you're not standing near blood or making sure the floors are clean. It's just that we don't really think about any other major antag like that and I feel like that's what's frustrating about slaughters. You're not trying to _kill_ a slaughter you're just trying to _survive_ a slaughter.

We don't run to the mining outpost as soon as a blob is announced. We don't bolt and weld maintenance shut when xenos or terrors are discovered. Why is it different with slaughters? That's what I'm frustrated about.

**Comment by Corocan** [comment]
> 
> 
> > You don't need to clean the entire station, only the bits that are bloody (blood sticks out as it's red). You don't even need to clean all the bloody bits, if you get every bit of blood near you then you're good to go. One exception is medbay of course, but that's likely to be full of people and therefore is going to be quite hard to take on.
> 
> Medbay tends to be the location where the demon slinks around the most and perpetuates its own filth due to the nature of itself. It tends to be extremely difficult to keep it completely clean. If anyone bleeds, it's generally used as a window for the demon to get in and once it's in, you can guarantee there will be blood used to get out.
> 
> > Don't fight the demon 1v1, you'll just lose. Team up with a group and don't run off on your own (this advice is also valid for many other antagonists which you insta-lose to, 1v1)
> 
> Although that is very wise, demons can pick their fights, crew generally can't.
> 
> > You don't need to "stand in one really big circle", groups of five or six should be okay if a few of you are armed. Cargo can buy guns. Science can print guns. The multitude of greytide can attack the demon with floor tiles. There are many ways to combat the demon.
> 
> Same problem, and arming the crew generally depends on where the captain falls in terms of how bad is the threat of the demon.
> 
> > Why did you paste the code into itself, more importantly why did you stage it?
> 
> im _really_ new to github, sorry
> 
> > In fairness, that is sort of the point. Almost all the major events in the round are major, round-shaking events that can make or break a round. Blob spawns, Xenos, Terror Spiders, Slaughter Demons, Abductors, Meteor waves, and on the beneficial side, the Sol Traders.
> > They're sort of intended to be events that break the stalemate, or in the event the antag has been taken care of real early, give a suitable repalcement primary threat to manage.
> > Major events should be rather major, since they don;t really happen until well into a round. It's not like these can happen at round start. If you die at the hour or longer mark then... I mean that's just SS13, this happens all the time.
> 
> I'll concede to those facts. I don't complain if I get hived by xenos or if I get killed by a blob or if a cow collides with my body at mach 1. I'm not arguing about the fact that slaughters are lethal, I'm more so concerned about how there's not really a decent counter beyond making sure you're not standing near blood or making sure the floors are clean. It's just that we don't really think about any other major antag like that and I feel like that's what's frustrating about slaughters. You're not trying to _kill_ a slaughter you're just trying to _survive_ a slaughter.
> 
> We don't run to the mining outpost as soon as a blob is announced. We don't bolt and weld maintenance shut when xenos or terrors are discovered. Why is it different with slaughters? That's what I'm frustrated about.

**Comment by Aurorablade** [comment]
Greetings let me clear up a few misconceptions on slaughter demons,
yet it is a major event but with a 1% chance of happening..
1%
One percent 
One%
1percent.

This is a really, really, really, really, really, really, low low low low low low chance of happening. just really low.

Conditions for a slaughter demon to spawn: Major event(1% chance be happy it wasn't a floorcluwne that has the same chance to spawn), WIZARDS, the cults final objective, the gods REALLY want you dead.

While i am sorry you got killed by a slaughter demon with such a low spawn chance there is really no reason to remove it.

**Comment by CornMyCob** [comment]
> Slaughter demons are capable of taking 100 points of damage

They have 200 health, and buckshot shells deal 75 damage per hit point blank (the slaughter demon has to fight you in melee range). You can even miss a couple pellets and still kill the demon in 3 hits, as they do 12.5 damage each! You seem to overestimate the amount of time it takes to actually kill the demon, a combat shotgun will take less than 2 seconds to do so. A security gear with riot/swat equipment and a gun can more often than not 1v1 a slaughter demon as they will heavily outdamage it. Your regular crewmember simply has to avoid blood if they're that worried, and should really be helping to clear blood, maybe even get weapons and armour of their own if it gets that bad, as we see with terror spiders and xenos.

Demons rely heavily on blood for their combat and they're easily kited, the argument that there aren't many counters besides this are kind of invalid as these are huge counters. The amount of death that often occurs with demons is more down to crew error rather than slaughter demons being overpowered, as they ignore the "blood begins to bubble" message, as well as don't clean blood. If crew focused more on keeping the station clean, and didn't drag dead bodies across the floor leaving a blood trail everywhere (use body bags or lockers!) we'd see a lot less death. As for medbay, just keep a couple people with guns there while making an attempt to keep it as clean as possible, and keep dead bodies well outside of the range of blood and there's not much it can do.

**Comment by Corocan** [comment]
> They have 200 health, and buckshot shells deal 75 damage per hit point blank (the slaughter demon has to fight you in melee range). You can even miss a couple pellets and still kill the demon in 3 hits, as they do 12.5 damage each! You seem to overestimate the amount of time it takes to actually kill the demon, a combat shotgun will take less than 2 seconds to do so. A security gear with riot/swat equipment and a gun can more often than not 1v1 a slaughter demon as they will heavily outdamage it. Your regular crewmember simply has to avoid blood if they're that worried, and should really be helping to clear blood, maybe even get weapons and armour of their own if it gets that bad, as we see with terror spiders and xenos.
> 

That's actually a good point, you're right.

**Comment by Couls** [comment]
Improve don't remove! I'd take slaughter demons over terrors or xenos anyday considering they're the other things you can get from a major event. Slaughter demons are stupid strong yeah but they're a lone antagonist and if they're not careful they'll die pretty fast to a shotgun

**Comment by TDSSS** [comment]
>Have you ever actually seen the station stay clean long enough for that to be relevant?

I have, yes. A janiborg with the cleaning upgrade, the janitor with the floor buffet upgrade for his cart, a bored roboticist making 500 cleanbots, a cleaning foam producing strange object...there are many, many ways to keep the station clean if people make an effort. Making an effort is the least we shoudl expect to deal with an event on par with a Prince of Terror spawning and murdering the fuck out of everyone.

**Comment by SkeletalElite** [comment]
> I'll concede to those facts. I don't complain if I get hived by xenos or if I get killed by a blob or if a cow collides with my body at mach 1. I'm not arguing about the fact that slaughters are lethal, I'm more so concerned about how there's not really a decent counter beyond making sure you're not standing near blood or making sure the floors are clean. It's just that we don't really think about any other major antag like that and I feel like that's what's frustrating about slaughters. You're not trying to _kill_ a slaughter you're just trying to _survive_ a slaughter.

So basically I ded pls nerf? It's way easier to survive against slaughters than it is against xenos. Slaughters are slow and give a message and a delay when they start to come out the blood, if you keep moving and prevent bleeding with some bandages or a trauma kit. You'll outrun the demon 90% of the time. 

Yes a single slaughter is a lot harder to kill than a single xeno, but slaughters are one guy, xenos start with two and grow rapidly from there. You really shouldn't expect to be able to 1v1 it just like you shouldn't expect to be able to single handedly kill an entire xeno hive. Complaing about slaughter demons being too powerful and easy to kill is similar to complaing about a wizard being too powerful because you can't win in a toolbox fight vs. their ei'nath. They're not supposed to go down easy.

**Comment by Neo-0** [comment]
I ded pls nerf

**Comment by The-Driker** [comment]
I love the fact that someone with a Doom Guy icon is trying to remove demons.

**Comment by Spacemanspark** [comment]
...Either I'm missing something or he totally doesn't have a doom guy icon

**Comment by The-Driker** [comment]
> ...Either I'm missing something or he totally doesn't have a doom guy icon

 This is his Icon for me.

**Comment by Spacemanspark** [comment]
Mmm, I'm on a github app on my phone, might be related.

**Pull request closed without merging**
