### PR TITLE
Deathgasp and Gasping Sounds

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Implements deathgasp and gasping sounds; credit to Goon for the sounds--they've been placed in the appropriate folder with the appropriate license.

Fairly simple; when you die, it actually plays a deathgasp sound.

Likewise, when you gasp, it also plays a sound. This sound is conditional based on your health; if you're just low on air, it's just a small, quiet gasp. That said, if you're in poor condition (critical), then your gasp will be far more dramatic and labored. Also gives doctors and audible cue when someone is just having issues, versus potentially dying.

To note, the deathgasp sound can't really be cheesed out of either. Thanks to an earlier refactor: https://github.com/ParadiseSS13/Paradise/pull/11283 the deathgasp emote bypasses cooldowns when you actually die--which means you can't do silly things like forcing someone to flip or what have you, then immediately insta-killing them to avoid the sound playing.

Gives a little bit for auditory cues for when people die while enhancing overall immersion of the scenario and situation.

:cl: Fox McCloud
add: deathgasping now has a sound
add: gasping now has a sound; more labored if you're low on health
/:cl:

### CODE REVIEW

**Comment by Cazdon** [comment]
The sounds of Goonstation have been my most wanted feature from it, and these are just excellent. I can't wait for even more, like the clicking of keyboards for in game computers.

**Comment by SteelSlayer** [comment]
Most of these are pretty neat, the deathgasp_1 sounds awful to me though.

**Comment by Spacemanspark** [comment]
How does this impact IPCs?

**Comment by Cazdon** [comment]
It probably doesn't at all, or just gives them deathgasp that every human has. Could just give them the deathgasp flatline sound borgos have in a later PR.

**Comment by lolzyking** [comment]
xenobio is hell now.

**Pull request merged**
