### PR TITLE
Makes the "thanks" autoresponse from admins sound less sarcastic.

### PR DESCRIPTION
**Pull request by hal9000PR**
## What Does This PR Do
"Thanks, have a paradise day" to "Thanks for the ahelp"

## Why It's Good For The Game
The old one sounded sarcastic and corny as hell.

> yo this dude just killed me 
> admin handles it and autoresponds with "thanks"
> It sends the player "THANKS HAVE A PARADISE DAY"

## Changelog
:cl:
tweak: changed the admin "thanks" auto response to be less sarcastic sounding
/:cl:

### CODE REVIEW

**Comment by Adrer** [comment]
Thanks for this PR, have a Paradise day!

**Comment by S34NW** [comment]
Thanks for this PR, have a Paradise day!

**Comment by Sirryan2002** [comment]
I have mixed feelings about the auto respond feature in general. The auto response that you are changing is intended to be sarcastic and snarky.

That being said. It's not a terribly professional way to respond to an ahelp and I do my best to never come across as pissy unless a player is being a unabashed asswipe so I would be happy to see this feature just go in general. Just having it as "thanks" still doesn't get rid of the negative undertone I feel and would be more appropriately said through a PM where it's clearly coming from an admin personally.

**Comment by Norwes1** [comment]
Ye gods please, yes. Sometimes you need to auto-resolve an ahelp (like using the 'Handling It' auto-response when some idiot gets three or four ahelps on him at the same time), but TBH I didn't realize our auto text was this bad. Seriously, "have a Paradise day?" That's, uh, yikes.

**Review by AffectedArc07 — APPROVED** [review]
get out

**Comment by AffectedArc07** [comment]
Also this has an approval from a head, I need to figure out why the label is still there

**Pull request merged**
