### PR TITLE
Ports Baystation's suit sensors

### PR DESCRIPTION
**Pull request by Spacemanspark**
Almost every codebase has this.
Pretty much, now, when you click 'toggle suit sensors', a window will pop up with suit sensors options.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This needs a check for if the sensor mode is greater than 2 so people can't toggle prison suit sensors--likewise, you still shouldn't be able to toggle suit sensors on a suit that lacks them.

**Comment by tigercat2000** [comment]
@Fox-McCloud This uses `set_sensor()`, which is what the stripping menu uses. If that's flawed, it's a problem for another PR.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

It actually wouldn't be, in this case, as you're changing how it functions.

I looked into the proc set_sensors() though, and it does have those checks, so this PR is ok.

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by Spacemanspark** [comment]
Ready to merge whenever you guys are.

**Pull request merged**
