### PR TITLE
Replaces medbay fridge "Anti theft shield windoor" with a secure fridge

### PR DESCRIPTION
**Pull request by Ty-Omaha**
As it is currently, the "anti theft shield" windoor gets left open all the time because it's inconvenient to have to wait for it to open, or then it will close on you while you are busy looking at the UI.

This achieves what the "anti theft shield" _should_ achieve but doesn't. Preventing everyone from ignoring doctors and just rushing to the machine.

You need to have medbay access to vend items from it. 

The public fridge is still there. Critically ill patients can still be put into cryotubes or a sleeper in an emergency.

</img>

🆑 
tweak: Replaces "anti theft shield windoor" with a secure medical fridge.
/🆑

### CODE REVIEW

**Comment by DesolateG** [comment]
Cool

**Comment by Kyep** [comment]
Personally, I would prefer medicines be kept easy to access.

**Comment by davidchan13** [comment]
@Kyep thats what the public fridge is for, this is medbay side fridge above cryo for difficult to produce or easy to OD chemicals that assistants and security officers shouldn't just be allowed to pocket.

Plus when 90% of a role's job is to apply patches, some effort has to be made ensuring they have first dibs to said patches.

**Comment by KasparoVy** [comment]
Yeeeees.

**Comment by Denthamos** [comment]
@davidchan13 Perhaps if chemists actually loaded said items into the public fridge people would not be constantly raiding the medical fridge for such.  As it is most times people just need a mannitol pill, a brute patch, a burn patch, or other such minor healing but it is all only contained in the medbay fridge.

**Comment by Tayyyyyyy** [comment]
This may be true now, but I think it's partially because there's functionally no difference between the two fridges. With this change, it'll give some of our chemists more to do, since they'll be able to populate the public fridge as well.

**Comment by davidchan13** [comment]
@Denthamos From a lore perspective, anything other than saline glucose tablets, approved virus samples and very small patches/pills for basic bruise/burn/toxins is against the point.

If chemists replicate most of the stronger healing medicines from the secure to public fridge, there is a very real chance that many crew with broken bones, infections, damaged organs or contagious viruses WON'T stick around for a doctor and just run off needing to come back or be dragged back later, wasting what ever effort went into what medicine they took and thus the time of the chemist.

If medbay is staffed there is very little reason people need to be self medicating for minor wounds when healing items spawn all over the station and eating a bag of beef jerky can heal minor burns and bruises like those you get from touching a lightbulb or having an item thrown at you.

**Comment by DesolateG** [comment]
Please don't use a "lore" argument for a game mechanic that has little to do with it.

**Comment by davidchan13** [comment]
>ignore all semblance of RP on a Med RP server.

**Comment by Denthamos** [comment]
Mmn,  but essentially you are regulating EVERY SINGLE damage for doctors to handle personally despite how major/minor it might be.  The front fridge relies upon chemists to actually use such.

Lore wise, what you said does not make sense because anyone can go to any public RX store and pick up splints, heavy painkillers, virus treatment, ect in large amounts if they so wish to.  Now things that CAN be harmful makes sense to keep locked in a locked fridge I do agree, like SR, penetic acid, ect.

Something I can see happening because of this is science for example making their own public use fridge loaded with healing chems for science to use as needed.  Hell, I may consider doing such as cargo in the future using a chem lab, dispenser, and public fridge for miners since it would make the process for them faster than having to wait 5-10 minutes just to get some mannitol pills/burn patches, or such.

**Comment by davidchan13** [comment]
@Denthamos 

>Mmn, but essentially you are regulating EVERY SINGLE damage for doctors to handle personally despite how major/minor it might be. The front fridge relies upon chemists to actually use such.

Well, for one medchem does not handle 100% of damage in medbay, let alone the station. Cryotubes are a catch all for external damage and surgery for internal. Minor damage can be healed with first aid items that spawn around the station, as well as eating just about anything nutritious to you species (unless your IPC, in which case if you want good healing get bent)

For another, **It's literally medical's job and purpose.** If you hadn't already notice, SS13 as a whole and Paradise in particular prefers to focus on the interdependence of the crew to discourage and prevent power gaming, valid hunting and general hoarding of items your character does not need. If medical doctors aren't doing their job, ahelp it. If you're getting upset that barriers are being placed between you and backpack full of medpatches that you MIGHT need, perhaps you should consider playing on another server that embraces this behavior.

>Lore wise, what you said does not make sense because anyone can go to any public RX store and pick up splints, heavy painkillers, virus treatment, ect in large amounts if they so wish to. Now things that CAN be harmful makes sense to keep locked in a locked fridge I do agree, like SR, penetic acid, ect.

I'm not sure what you're trying to get at this statement. You can't just walk into a hospital, raid the pharmacy for tylenol or pain killers because you think they need them. You can't just walk into a drug store and take a speciality medicine and walk out no questions asked, you need a **prescription from a doctor** before hand to get most anything that isn't basically a placebo or motrin. You definitely can not get large amounts of any of these medical strength items without a very good reason without the authorities getting involved wanting to know why.

I'm even more confused why you are thinking everyone should have access to medical's store of goods and custom supplies. The RnD Terminals, Supply Terminals and departmental vending machines, including the bartender's BoozeMat, flatly reject random users without proper access even if you managed to get past the door without such access. What possible reason, IC or OOC, can you have for insisting that medical supplies be free for all to take when an entire department revolves around their proper application?

>Something I can see happening because of this is science for example making their own public use fridge loaded with healing chems for science to use as needed. Hell, I may consider doing such as cargo in the future using a chem lab, dispenser, and public fridge for miners since it would make the process for them faster than having to wait 5-10 minutes just to get some mannitol pills/burn patches, or such.

If someone wants to set up their own public fridge, it's on them. They can get them from science the same way they'd get medicine from medical, **ask the appropriate staff for the supplies and give a valid reason for their use.** I strongly suspect you'll find few scientists willing to prep several dozen patches and pills of varying applications for Cargo's personal use but feel free to ask. For all the hoops you'd jump through to get that stockpile, I don't know why you wouldn't just ask Medical/Chemistry, if you ever bothered to ask for the supplies they might even put them in first aid kits and pill bottles for miners to take with them to the asteroid.

**Comment by Denthamos** [comment]
@davidchan13 Do not misunderstand me, I am not arguing against medical having mode secure storage for medicine that can cause harm when used in large amounts, or for really hard to make medicine that should be used sparingly.

What I want is a reason for chemists to actually load easy to make no harm healing chems into their public fridge which does not get used at all as it is now besides from the viro.  Stuff like brute/burn patches or synthflesh patches, charcoal pills, mannitol pills, oculine pills, or even saline glucose.  Its all stuff that is easy to make in large batches but as it is now it all gets shoved into the main fridge.

Just that alone would stop a lot of people rummaging around through the medbay fridge.

**Comment by variableundefined** [comment]
My main objection to this PR is that this mess over anyone who legitimately breaks in and try to steal the medical fridge's content. Wizards' screwed, and so are nukies unless they grab a doctors' ID. I am certain this is one of the reason why Access checks are better than ID check on machines.

You can bypass access check in multiple way, but there's only one way to go through ID check.

**Comment by Crazylemon64** [comment]
Due to a majority of objections among the heads and maintainers, it has been decided that this PR shall be closed.

**Comment by Necaladun** [comment]
Although the general idea of making it more secure would be nice - the anti theft shield does that if PEOPLE WOULD JUST REMEMBER TO CLOSE IT.

I'd like to see a nicer solution to this that doesn't mean it'll get escalated by people taking the whole thing apart and dumping every damn pill on the ground.

**Comment by tigercat2000** [comment]
This is basically taking away options from doctors. It makes it both too secure and makes it so that the doctors can't choose whether it's open or not.

**Pull request closed without merging**
