### PR TITLE
Cameras Now Handle Disguises

### LINKED ISSUE #6015: Camera Bug
**Problem Description**:
What is the problem?
If you take a photo of someone carrying a plant, the photo shows the person, not the plant
**What did you expect to happen**: 
Why do you think this is a bug?
Because it is not showing the plant, the person is holding
**What happened instead**:
How is what happened different from what you expected?
You see the person instead
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
If someone tries stealth using a plant, a camera could spot him.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Pick up a camera, shoot a photo of a person holding a plant.

bug

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### PR DESCRIPTION
**Pull request by KasparoVy**
Fixes a bug where you could take a picture of stuff behind walls (ghetto X-Ray).
Pictures will now render people with disguises as you see them (borgs see people with cardborg suits as borgs, people with cardborg suits see themselves as borgs, everyone sees people carrying plants as plants)
although they will also state the person's name, regardless of disguise (**same as if you hovered over them with your cursor**).

Fixes #6015 

:cl:
fix: Cameras will no longer be able to take photos of stuff outside your line of sight.
tweak: Cameras will now render disguises as you see them.
/:cl:

_Cameras no longer use x-ray tech._
noxraycamera

_Taking a picture of someone holding a bush._
bushdisguise

_Taking a picture of someone else wearing a cardborg outfit as a human._
cardborgphotoother

_Taking a picture of yourself when you're wearing a cardborg outfit._
cardborgphotoself

_Testing to see if Cyborg onboard cameras inherited the same fix. They did._
cyborgcameraworking-noxray

_Taking a picture of a person wearing a cardborg outfit (left), holding a plant (top) and holding/wearing nothing (right) as a cyborg (bottom)._
alltogether

### CODE REVIEW

**Comment by Plotron** [comment]
I did not realize the cardborg suit was so special!

**Comment by pinatacolada** [comment]
Does this do anything to pictures taken by the AI? They should ideally respect the AI static thing

**Comment by KasparoVy** [comment]
I'll check, but AFAIK in places where the AI would have static, it should just be black in these photos. I'll check while I'm making the revision. It'll only render whatever's in the AI's view(), and I'll find out just what that is in a few moments.

**Comment by KasparoVy** [comment]
Yep, works as I expected. Here's some pictures of AI pictures.

Left: _AI taking a picture of a guy wearing full cardborg, a guy holding a plant, and another guy._
Center (top): _AI taking a picture of an a spot between areas where they have and do not have vision._
Center (bottom): _What the above looked like to the actual AI (static instead of blackness)._
Right: _AI taking a picture of a spot between two areas with camera coverage._
aiphotos

Working as intended, no satire

**Comment by Fox-McCloud** [comment]
@Crazylemon64

**Pull request merged**
