### PR TITLE
Updates librarian's PDA description

### PR DESCRIPTION
**Pull request by iantine**
## What Does This PR Do

Removes the WGW references from the Librarian's PDA description, changing two instances of 'WGW-11 series e-reader' to 'NTOS series e-reader'.

## Why It's Good For The Game

Since we've had (thankfully infrequent) issues with librarians blasting unpleasant copypastas, it may be prudent to remove any reference, no matter how obscure, that may encourage them to think it's okay to do so.
If it happens a reference to something else, or considered too harmless to change, feel free to comment/close.

## Changelog
:cl:
tweak: Changed librarian's PDA description
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This is a joke and kinda part of SS13 lore and culture---as terrible and bad as it is, and as infrequently as it happens--it *does* still happen--much like bald assistants and the inevitable person who joins named "Hitler" and gets promptly *lynched*.

👎

**Comment by Mitchs98** [comment]
Pretty much echoing Foxes' sentiment. It's not really hurting anyone, and as said IS a part of SS13 on a whole whether people like it or not.

**Comment by FreeStylaLT** [comment]
We have rules to cull the stupid and the ignorant from the server. We will never have a self-enforced server populated by people who are all acting reasonably. If someone googles WGW and decides it's okay to paste it because a PDA's description had the acronym, then they're already the type of player we would rather not have here.

**Comment by iantine** [comment]
Seems largely a non-issue due to comments. Closing.

**Pull request closed without merging**
