### PR TITLE
Hallucinations 2.0

### PR DESCRIPTION
**Pull request by davipatury**
Ports tgstation/tgstation#24478, tgstation/tgstation#24641, tgstation/tgstation#24680 and tgstation/tgstation#24806.

:cl: Developed by XDTM, ported by davipatury
tweak: Hallucinations have been modified to increase the creepiness factor and reduce the boring factor.
add: Added some new hallucinations.
fix: Fixed a bug where the singularity hallucination was stunning for longer than intended and leaving the fake HUD crit icon permanently.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
What a God. These things rock.

**Comment by SamHPurp** [comment]
Looks cool

**Comment by Crazylemon64** [comment]
⭐️o⭐️

**Comment by Kyep** [comment]
Yes please. Old hallucinations were boring.

**Pull request merged**
