### PR TITLE
Ports penguins

### PR DESCRIPTION
**Pull request by Aurorablade**
And one additon i did that i could not pass up.

https://github.com/tgstation/tgstation/pull/28454

and 

https://github.com/tgstation/tgstation/pull/30487/files

as origin. TG has it on the holodeck but i am unsure how to rig that up on our holodeck code so i am open to suggestions or someone can find a nice home for them later.

:cl: Fethas
rscadd: Penguins, Penguins in shambreos and Albino penguins are a thing.
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
These are amazing
Yes please

**Comment by taukausanake** [comment]
~~IT'S NOT FUCKING CHRISTMAS YET WHAT IS WRONG WITH ALL YOU FUCKS?~~

This is nice I like it. [Can't wait for this to happen though](https://www.reddit.com/r/SS13/comments/720pg1/penguin_cult_activity/).
I wonder how long until one of them is named Pingu...

**Comment by HugoLuman** [comment]
Hugo's do-list += add Penguin borg sprites in another PR

**Comment by adamkad1** [comment]
porting tg stuff eh? plz port new tg R&D den

**Comment by taukausanake** [comment]
@adamkad1 
> porting lots of tg stuff

Apparently you haven't heard the "we're turning into /tg/" joke yet, have you?

@Aurorablade Wouldn't it be as simple as just making a new holodeck area with holo-penguins on it? I would think it not that hard if that was the case but I could be wrong

**Comment by Aurorablade** [comment]
@taukausanake issue i could add it to the current holodeck thats not the issue. the issue is making sure they disappear if they leave the holodeck. our current code does not supports safe holodeck critters. Just murderous emagged space carp.

**Comment by tigercat2000** [comment]
Adorable. 👍

**Comment by adamkad1** [comment]
@taukausanake i know that joke, im probally one of people who started it, still, the new tg science is vastly superior to current one we copied some time ago

**Pull request merged**
