### PR TITLE
(hatched)Shadowling icon update

### PR DESCRIPTION
**Pull request by Aurorablade**
Please note..the fact it looks like its walking around with its hand on its hip..is cuase i accidently left in the file for the old r_arm and it overlapped..BUT IT LOOKS FUCKING HILARIOUS.
:cl:
add: new hatched shadowling icons by phantasmic dream.
/:cl:

### CODE REVIEW

**Comment by PhantasmicDream** [comment]
Just to help show a comparison 
shadowlings

**Comment by KasparoVy** [comment]
I'm conflicted on this one, but the sassy shadowling gave me a bit of a laugh.

**Comment by Agameofscones** [comment]
You've lost the original rough wrinkly variance, and instead have replaced it with a more uniform visual approach. I'm not really a fan, while the shading is nice and the emphasized form is clear, it moves the aesthetic away from the original intent into a different direction that doesn't feel as, horrifying,

Perhaps reshading the original with varied marks over the body instead of uniform would be better. This could easily be accomplished with a set of overlays that get picked once hatched. Randomizing the red line placement could add to the unique identification of shadowlings as well, which would reward the keen eye of clever players.

It looks more like a broski in a black morph suit in the new version. Another change you might want to try, is to keep the wrinkles, but then add the uniform red lines.

Animating said redlines, while a chore thanks to Byond, would also be an excellent addition.

**Comment by taukausanake** [comment]
I kind of agree with @KasparoVy but that new sprite also looks soo cute! Maybe because it looks a tad smaller than normal mobs. It's like seeing an edgy emo kid. That's hilarious to me

**Comment by Aurorablade** [comment]
its not smaller at all.

**Comment by Aurorablade** [comment]
The diffrence is its kinda curvy on the shilioute. And yes there is not sassy hand on hip in this one.

**Comment by taukausanake** [comment]
It looks a tad smaller body width. Slimmer I think. Also legs don't take as much space because they're so close together. It's just a little more compressed than normal mob sprites and that's why it looks a tiny bit smaller and cute to me.

You still use the other sprite for shadow people, yes? Feel like that should stay the same

**Comment by PhantasmicDream** [comment]
My goal was to add elements from the ascendent sprites to the regular shadowlings sprites, because to me they didn't feel like they messed well together before. And to make them stand out from other all dark shadowy beings. 


I know the "aesthetic" of the original one had a nice rough and rocky feel going for it, but personally had a hard time adding those elements and the markings together without making it look like a sloppy mess. But you're always free to come up with your own design.

**Comment by Aurorablade** [comment]
@taukausanake yeah shadow people and shadowlings are diffrent ducks.

**Comment by Aurorablade** [comment]
both from a lore perspective and a code one.

**Comment by taukausanake** [comment]
I might avoid the markings, or make them darker like they are not glowing. I can't remember if acceded shadowlings have their red markings glow in the dark like eyes do. Lesser slings shouldn't glow because they need to be sneaky. I'd make them darker or replace them with something else. Otherwise the body shape is great

**Comment by Spacemanspark** [comment]
Am I wrong for wanting an option to place our hands on our hips now

Just so I can run into places and shout "OH NO YOU DIDN'T"

**Comment by PhantasmicDream** [comment]
Have the chance to be a sassdowling(?) to go along with the assendent

**Comment by PhantasmicDream** [comment]
Also, just going to bring up that shadowlings were basically a recolour of shadow people
3crtncduqa6zz0vix7lfcq

**Comment by KasparoVy** [comment]
Or was it vise versa? 🤔

**Comment by Aurorablade** [comment]
I like these..and the option is there to make glowy stuff but you know..it will kill some of the stealth aspect. I can't remeber if i put glowy on ascedends or not...i had the idea for it way back...

**Comment by Aurorablade** [comment]
"Have the chance to be a sassdowling(?) to go along with the assendent" As another note..this just makes the 'you got that' meme go in my head..only with sassy ss13 antags..

**Comment by variableundefined** [comment]
We prefer the old sprite.

**Comment by Aurorablade** [comment]
I would like a better explination there and maybe did you contact the maker of the sprite to see if they were willing to tweak it.

**Pull request closed without merging**
