### PR TITLE
More belt overlays

### PR DESCRIPTION
**Pull request by taukausanake**
:cl: Tauka Usanake
rscadd: Adds more belt icon overlays
/:cl:
I posted in PR #4548 that I'd like to try and make the other belt overlays. Here is my contribution!

Progress:
- [x] Bandolier
output_gzxuoc

- [x] Botany belt
botany belt

- [x] Utility belt
utility belt

- [x] Medical belt
medical belt

- [x] Janitor belt
janitor belt

- [x] Wand belt
wand belt

- [x] Soul Stone belt

* Bandolier works the same as the lazarus "trainer's belt". I had to remove the bottom shell pixels so that it actually held eight instead of nine shells.
* Botany belt shows icons for plant analyzer, mini hoe, spade, hatchet, and wirecutters. Wirecutters will be shared with botany belt and utility belt.

I'm going to take my time with this, also to have judgement passed on my sprites. I'm sure they're shitty compared to what others might make but I wanted to give it a shot.

I'd also like to ask about the usage of the assaultbelt and securitybelt icons. I'd imagine them to be used for each other, not the way they are. I know @DaveTheHeadcrab made the sprites for the assault used for sec but the belt itself seems out of place with all the others. Just a thought

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Needs pics

**Comment by CrAzYPiLoT-SS13** [comment]
GG, you made Fox create a custom label

**Comment by DaveTheHeadcrab** [comment]
full botanybelt

Here's what a full botany belt looks like.
:+1:

**Comment by taukausanake** [comment]
HURG I don't want a custom label made for me. D: I was going to make a image later anyways but Dave beat me to it.

Okay, removed the holster from OP. Didn't start on it anyways. I thought as an accessory it might still work but I guess not.

@DaveTheHeadcrab I mean the old secbelt icon matches all the other belts we use while the new /tg/ one looks more assault-y. They really should be the other way around. I'd like to switch them back but I don't know who did it before and want others take on it before I touch it

**Comment by Spacemanspark** [comment]
You stole that label from /tg/, you sneak.
@Fox-McCloud

**Comment by taukausanake** [comment]
Did the icons for the utility belt. Uses wiercutters, cable coil, wrench, multitool, welding tool, pocket crowbar, and screwdriver. It looks properly cluttered.
utility belt

**Comment by Spacemanspark** [comment]
Hrm...
Personally I think those sprites look a bit too big.
Not a large problem, looks fine otherwise.

**Comment by taukausanake** [comment]
Maybe they are a bit too big but I didn't want to make them too small. I want the visual to show after all.

@Fox-McCloud I added the pics, now remove the label and thereby my shame

**Comment by DaveTheHeadcrab** [comment]
I tend to agree with @Spacemanspark 
Less is more here

**Comment by taukausanake** [comment]
I kind of also wanted the utility belt to be cluttered due to it's engineering/tide nature. Those are the items normally used in it so I don't see why they shouldn't be shown. And I know about not needing every object that can go into a belt. I'm picking whichever ones seem reasonable and would actually be visible

**Comment by taukausanake** [comment]
Got the medical belt done. Has icons for a beaker, pill bottle, vial (might remove, it doesn't seem like it's used anywhere), Health Analyzer, Syringe, and emergency autoinjector just because.

These icons require specific names of the objects it holds. Took me a while to get them to work and find out which ones would work on the get-go. Any complaints besides the icon sizes?

**Comment by taukausanake** [comment]
Janitor belt icons done. Will show icons for soap, space cleaner, holograohic sign projector, light replacer, and cleaner grenade.

**Comment by taukausanake** [comment]
I've decided against doing anything for the soulstone belt. That being said I feel I'm done with what I set out to do and await review. Might need to make one last push to clean up anything I left around but otherwise additions are finished

**Comment by taukausanake** [comment]
I found problems. Where I thought I was smart and let the utility belt and botany belt share the same sprite for wirecutters, I missed that botany belt and medical belt also carry similar items, mainly beakers and syringes. Seeing as these aren't really used in Hydroponics much anymore can they be removed from the can_hold list in botany belts?

**Comment by TheDZD** [comment]
Might want to do this for the wizard's wand belt.

**Comment by taukausanake** [comment]
I'll take a crack at it

**Comment by DaveTheHeadcrab** [comment]
I'd still like to see the utility belt de-cluttered a little bit.
Otherwise looks really nice.

**Comment by taukausanake** [comment]
I actually really like how cluttered the utility belt is. I mean you must have seen real belts used out there. They're so messy with everything everywhere. Add to that the other belts look fairly tame, at least I would hope

**Comment by taukausanake** [comment]
This should be everything finished now. Made sprites for the wand belt and animated them too! Sprites for wand of fireball, polymorph, death, resurrection, teleportation, door creation, and nothing because it's also a wand. Also made a sprite for a single soul stone for the soul stone belt. Didn't feel it needed the same treatment as the bandolier.
The only thing that might not be accepted in this commit is that I commented out the syringe and beaker for the botany belt. They clash with the belt as it is but my argument is that they aren't even used in Hydroponics anymore anyways. At the very most you'll use them for the reagents you grow but chances are you won't put them in your belt anyways.

Ready for review.

**Comment by Fox-McCloud** [comment]
May want to make the wrench and welding tool just a bit smaller to cut down on the cluttered look. 

They don't have to be tiny tiny, of course.

**Comment by taukausanake** [comment]
I honestly think they're a good size but alright, I'll see how it goes

**Comment by Davdichan** [comment]
@taukausanake Atmos techs start out with a pocket fire extinguisher and analyzer on their belts. Would it be possible to align the fire extinguisher on the right side of the belt? If not thats fine, but if the point of the system is to see whats in the belt belt at a glance it'd be nice to have that.

**Comment by taukausanake** [comment]
@Davdichan The problem with that is there is limited space on the belt and you don't want overlapping of the sprites. I considered the items that atmos belts start with but by that time I had already finished the sprites for utility. There isn't anymore room without shrinking the sprites so small that they don't look like anything anymore.

As for the sprites already on the belt, I tried making them smaller but I just couldn't get anything that I thought looked better. I really do like how it came out though. I can't see myself getting any more out of this than it already is

**Comment by Fox-McCloud** [comment]
the "standard" utility belt set up is a wrench+wirecutters+crowbar+welding tool+multitool+screwdriver+cable coil.

While, yes, analyzer and a few other things fit, those definitely aren't used nearly as much, day to day---so, as with the sec belt, it's generally better for it to include the most common items that are normally equipped to the belt.

**Comment by Fox-McCloud** [comment]
@taukausanake 

ETA on this?

**Comment by taukausanake** [comment]
It's done. I said I couldn't make the sprites smaller and look good. If someone else wants to try they can but I've done all I am able to

**Comment by taukausanake** [comment]
My second contribution. I am happy

**Pull request merged**
