### PR TITLE
Change Epsilon voice announcement and message

### PR DESCRIPTION
**Pull request by Code-Lyoko0**
## What Does This PR Do

Changes the audio announcement for going to Epsilon Alert to something a bit more thematic, and also changes the message to match the new voice announcement. The added part about the NTR does not mean a Deathsquad has to save the NTR if it is not requested by SOO, but makes it scarier to the crew that NT no longer cares about anyone but the NTR, and should not change anything if an admin wants to go fully "no survivors"

Voice generated by me and edited by me and @Qwertytoforty 

Radio Static comes from the following CC0 sources:
https://freesound.org/people/9voltplasma/sounds/724710/
https://freesound.org/people/9voltplasma/sounds/724704/

## Why It's Good For The Game

Epsilon Alert is meant to be scary and adding these extra effects adds to this. The part about the NTR is mostly just fluff, if the DSquad goes full murder and kills them, nothing would happen, it is just to add to the chilling effect of the message

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/13879982/10caca86-9300-4cd9-b764-cd8d4ddb0398

## Testing

Loaded server, set security level to Epsilon, heard sound

## Changelog
:cl: Code-Lyoko0
tweak: Changed the Epsilon Alert announcement to match the new voice announcement 
soundadd: changed Epsilon voice announcement to be more thematic. 
/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
Can you add the "Consider all contracts terminated" to the voice as well?

**Comment by Code-Lyoko0** [comment]
> Can you add the "Consider all contracts terminated" to the voice as well?

it was discussed when I was creating the lines, but generally I dont think it was something that was needed and would make the voice line go on longer then  it already is with the new added effects

**Comment by Onyxarias** [comment]
Gives me chills. Very happy to see you got the effects going!

**Review by Henri215 — APPROVED** [review]
Hearing good to me

**Review by S34NW — APPROVED** [review]

**Pull request merged**
