### PR TITLE
Rb303 fluff item 2: electric boogaloo

### PR DESCRIPTION
**Pull request by rb303**
**What does this PR do:**
Adds fluff item, approved of by Purplegenie.
Ckey: Rb303
Character: Isthel Eisenwald

**Images of sprite/map changes (IF APPLICABLE):**
image

_Yeah I know I'm dumb but at least it won't happen again. Probably._

**Changelog:**
🆑
add: Fluff scarf for Rb303
/ 🆑

### CODE REVIEW

**Comment by AffectedArc07** [comment]
>Provided help

>Makes a new PR anyway

>Insert shocked pikachu here

**Comment by Ty-Omaha** [comment]
>add: Fluff scarf

thats so generic

🆑
add: Fluff scarf for Rb303
/ 🆑

**Comment by Fox-McCloud** [comment]
I'm very wary of making a simple re-color a fluff item.

And yes, I realize it's more than that, but when something is a recolor+a bit extra, it makes adding a different version of it difficult to impossible because "that's someone's fluff item!"

**Comment by Shadeykins** [comment]
> 
> 
> I'm very wary of making a simple re-color a fluff item.
> 
> And yes, I realize it's more than that, but when something is a recolor+a bit extra, it makes adding a different version of it difficult to impossible because "that's someone's fluff item!"

We could always use another shade of purple, or the same shades in opposite patterns. ;)

**Comment by AffectedArc07** [comment]
image
🤔 

Not `Custom Item`?

**Comment by rb303** [comment]
I can see your concern Fox, but from what I've seen many fluff items are simple recolors of things like berets and jackets, yet those generally work out just fine anyway. Besides, like with what Shadey said, it wouldn't be difficult at all to just use different shades of coloring like it is usually done with berets, which IMO just share the same amount of colour options as scarves. Comparing my scarf with a normal striped purple scarf side-by-side would show pretty obviously which one the fluff item is, so this item's design doesn't seem too controversial to me.

**Comment by variableundefined** [comment]
Brainfarted

**Pull request merged**
