### PR TITLE
Belt Update

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
This PR consists of 2 changes regarding belts:
1) Full toolbelts now spawn with a randomly colored cable coil instead of being restricted
2) Added inhand sprites for belts, example image below. While I think they could be further improved, this is much better than not to have any inhand sprites for belts at all.

**Images of sprite/map changes (IF APPLICABLE):**
belts

Ported from /tg/station13, credits for sprites to them.

Tested locally without any issue.

**Changelog:**
:cl: Arkatos
tweak: Full toolbelts now spawn with randomly a colored cable coil
imageadd: Added inhand sprites for belts
/:cl:

### CODE REVIEW

**Comment by variableundefined** [comment]
I like it

**Comment by Ralta** [comment]
Can I ask why the random coloured cable coil? I like the in-hand sprite change, but I actually prefer to have one standardised colour for cables (i.e. red) as an engineer. If I'm the only one who feels that way, fair enough :eyes:

**Comment by KasparoVy** [comment]
4 strength 4 stam?

Level 18?

**Comment by Necaladun** [comment]
...i like the standard red too. Idk even why, but good to know im not alone there!

**Comment by Markolie** [comment]
Now I can even give those unruly assistants the belt in-game.

**Comment by Couls** [comment]
Can this be accompanied with a lashing sound when you use the belt on people... asking for a friend

**Pull request merged**
