### PR TITLE
Remove embedded objects with a hemostat.

### PR DESCRIPTION
**Pull request by Birdtalon**
It's just more professional...

🆑 Birdtalon
tweak: You can now remove embedded objects with a hemostat or it's ghetto variants.
/🆑

### CODE REVIEW

**Comment by SamHPurp** [comment]
>More Professional

>Enables mice traps to work too

**Comment by KasparoVy** [comment]
I can't help but wonder how the cable coil would work for getting stuff out (not a criticism, just curiosity). Do you tie it around the item and pull? :grin:

**Comment by Birdtalon** [comment]
@KasparoVy I've also thought about that in the past. I'm sure there's better hemostat substitutes in the game but someone decided that cable coil would be it!

**Comment by taukausanake** [comment]
How to remove a brain:
1. Get head
2. Break open head
3. Tie cable around brain
4. PULL
5. ???
6. PROFIT

**Comment by SamHPurp** [comment]
> @KasparoVy I've also thought about that in the past. I'm sure there's better hemostat substitutes in the game but someone decided that cable coil would be it, I wouldn't want to find out first hand how it works.

Its like... how you remove a tooth by looping string around it, then tying it to a car door and slamming that car door. (or a brick and dropping the brick)

**Comment by Crazylemon64** [comment]
```
Following discussion between the Heads of Staff and Maintainers, it was decided to close this PR; there is already a perfectly valid option in the form of hands, and adding more (inferior) options would merely add confusion to the process.
```

**Pull request closed without merging**
