### PR TITLE
Improves the stairs sprites

### PR DESCRIPTION
**Pull request by SamHPurp**
image

:cl: Purpose
add: Adds new stair sprites.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Much improved!

**Comment by tigercat2000** [comment]
We are not out of our feature freeze #9426.
Please cite your three fixes for this PR or it will be closed.

**Comment by variableundefined** [comment]
Now one fix

**Comment by SamHPurp** [comment]
https://github.com/ParadiseSS13/Paradise/pull/9713 ?

Minor, but took ages, and two admins specifically asked that I fix it for them ASAP.

**Comment by variableundefined** [comment]
That one will count.

Awaiting approval.

**Pull request merged**
