### PR TITLE
Removes superior welding goggles

### PR DESCRIPTION
**Pull request by TheDiode**
## What Does This PR Do
Removes the superior welding goggles from the game. It is no longer in the RD's locker or the CE's locker.

## Why It's Good For The Game
This item is...bad. It was never meant for players, it was added as a custom item for a Baystation12 player (according to git history).
This item is the welding goggles, but without the downside of obscuring your vision. If you don't want to wear a helmet or goggles you should go to Robotics and get welding shielded eyes. When you use a welding helmet or goggles, you're a bit vulnerable when welding due to decreased vision. These roundstart goggles are superior in every way...why do they need to exist?
Not to mention the terrible sprite, it's just 2 green circles and a curved line.

## Changelog
:cl:
del: Removed the superior welding goggles from the RD and CE's locker.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
But . . . why though? Its not OP, its a QoL item for both the CE and RD to use, and isnt really an issue?

**Comment by ItsMarmite** [comment]
The superior welding goggles exist as upgraded equipment for both the Research Director and Chief Engineer.

The Chief Engineer, of course, using these for the purpose of welding through metal- among other uses.

The Research Director using these for eye protection against chemical reactions, cyborg flashes and in the construction of mechs.

The goggles exist much like other such equipment exists for heads of staff, direct upgrades of equipment their staff in their respective departments get. (Welding helmets/goggles).

Also the sprite is kinda drippy ngl.

Highly against this.

**Comment by LiberatedWaveMan** [comment]
not only is the sprite just fine, but like matt said, this is a simple QoL item.

**Comment by AffectedArc07** [comment]
Yeah no

**Comment by Bokkiewokkie** [comment]
> If you don't want to wear a helmet or goggles you should go to Robotics and get welding shielded eyes.

Or flip up your hardsuit helmet with in built welding protection lol, no point in removing the drip.

**Comment by Inadvizable** [comment]
> Welding things should leave you vulnerable.

What even
It's just welding, a hardsuit you can take off for speed in 0.5 seconds by clicking on it will protect you, hell experimental welder + sunglasses does the trick. Something the CE starts with.

**Comment by Sirryan2002** [comment]
What balance concerns does this object actually present? Yes it has flash protection, but so does the bartender round-start sunglasses. The CE doesn't have access to ear protection outside of ear muffs which already present a major tradeoff so they're quite vulnerable to flashbangs (and batons, and disablers). 

Please stop exaggerating how good these goggles are, the only difference they have from a welding helmet is that they are eye slot instead of helmet and don't have a view range debuff. Also, using the justification of it being a baycode import (from 9 years ago) pays no attention to the fact that our codebase has changed dramatically during that time period and that these goggles are no longer just a specific "user's item."

I'd like to see a justification to this PR that actually addresses why removing these goggles will balance our game more and improve it.

**Comment by Bokkiewokkie** [comment]
> @Bokkiewokkie Hardsuits make you slow

That's why you hold it in your hand when walking to prevent the slowdown, I feel like most engineers that are constantly welding won't be minding the slowdown that much (as welding is slower)

**Comment by Bokkiewokkie** [comment]
> @Bokkiewokkie If you hold it in your hand, you can be disarmed. And if you're holding it in hand you're now vulnerable to being flashed.

I thought the point was not being vulnerable while welding, something which people are generally stationary for so the suit would already be on. Anyone looking for a fight would have taken a pair of sunglasses from sec or maint if they really wanted free flash protection anyways.

**Comment by Inadvizable** [comment]
> @Bokkiewokkie If you hold it in your hand, you can be disarmed.

not really... RNG disarm is gone

**Comment by LiberatedWaveMan** [comment]
> If you really like the sprite, I can keep it in, but the roundstart welding and flash protection needs to go. It's not healthy for the game.

With all due respect, you joined github just this month, and only began contributing today when, in the span of 4 hours, you haphazardly rolled out 5 separate PRs, 3 of which were almost universally disliked by coders and the community. At the current rate you're going, it makes it very clear that you either don't know what's healthy for the game, or you just don't care what other people think. It's welding/flash protection for the two people on-station that need it most, and as far as realism goes, it makes complete sense that they would have it. The benefits it provides aren't even that powerful, considering there's multiple other ways to accomplish it.

**Comment by LightFire53** [comment]
> > If you really like the sprite, I can keep it in, but the roundstart welding and flash protection needs to go. It's not healthy for the game.
> 
> With all due respect, you joined github just this month, and only began contributing today when, in the span of 4 hours, you haphazardly rolled out 5 separate PRs, 3 of which were almost universally disliked by coders and the community. At the current rate you're going, it makes it very clear that you either don't know what's healthy for the game, or you just don't care what other people think. It's welding/flash protection for the two people on-station that need it most, and as far as realism goes, it makes complete sense that they would have it. The benefits it provides aren't even that powerful, considering there's multiple other ways to accomplish it.

Please keep commentary regarding the PR itself. It is up to staff coding team to determine validity of PRs/Authors.

**Comment by Inadvizable** [comment]
> @Inadvizable Can't you be shoved or whatever? I know disarms are gone but I still call it that out of habit.

Not easily... You'd need to be clicked twice, or shoved against an obstacle. Both highly preventable situations by pressing E as someone approaches to equip the suit

**Comment by PacifistDalek** [comment]
> It was never meant for players, it was added as a custom item for a Baystation12 player

As a hopefully helpful tip, there's a lot of stuff on our codebase that isn't for players on other codebases, and vice versa. We're running a different kinda ship than Baystation12, and so are they from us. Balance and other concerns are worth bringing up and discussing of course, but I think the "it was a custom item only on bay" and similar arguments don't really work when it comes to different ss13 servers.

**Comment by AffectedArc07** [comment]
This PR has every single member of the balance team against it and is basically universally disliked.

Its being closed.

**Pull request closed without merging**
