### PR TITLE
Connects the scrubber loop to waste

### PR DESCRIPTION
**Pull request by Ty-Omaha**
Pipes near cargo

All the scrubbers except the ones in medbay, science, and engineering are not connected to the waste loop. I didn't believe it and kept searching for a connection, but couldn't find one. Nor could several other people.

This connects it.

:cl:
fix: Connects the station's scrubber loop to the waste loop
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
Whenever I boot up DM recently, I get messages like this:
## ERROR: /obj/machinery/atmospherics/pipe/simple/hidden/scrubbers added to a pipenet while still having one (pipes leading to the same spot stacking in one turf). Nearby: 97, 178, 1.

Maybe they're related?

**Comment by Ralta** [comment]
Wait...that issue report was legit? There really wasn't a connection outside medbay/engineering/science _at all!?_ 🤣

**Comment by SamHPurp** [comment]
@Kyep that is likely a separate issue with multiple of the same pipe on the same tile... whoever has been mapping lately screwed some stuff up ;)

**Comment by Vivalas** [comment]
That means there is a duplicate somewhere in the area of those coordinates.

**Comment by Kyep** [comment]
It may be a separate issue, but no reason not to fix it in the same PR. Less PRs that edit cyberiad.dmm = less map merge conflicts.

**Comment by Taaketa** [comment]
Isn't this PR redundant because of #8469 ?

**Comment by Ty-Omaha** [comment]
That's been open for almost a month now, this was supposed to be a quick fix.  Seeing as how that PR is no longer a WIP, paired with the map conflicts I'll close this.

**Pull request closed without merging**
