### PR TITLE
New sounds for Firelock, Airlock Closing, and Airlock External

### PR DESCRIPTION
**Pull request by Jovaniph**
This PR adds new sounds to the doors for a bit more...immersion? The regular airlock closing sound was taken from the yogstation sound files. The other two sounds were free and had no license (i made sure) to them so its all good.

https://www.youtube.com/watch?v=7Qp23Umzqds

:cl: Jovaniph
rscadd: New sounds to Firelocks and Airlock External
rscadd: Door closing sound to Airlocks - from yogstation
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I don't know about the Airlock closing. I kind of like the one we have already more. The other sounds are great though! Just keep the old airlock closing one

**Comment by Spartan6** [comment]
The external firelocks sound less meaty than the normal airlocks. If anything, switch them around. You'd think External airlocks tougher than bog standard ones.

**Comment by taukausanake** [comment]
If anything I think external sound more air tight. More squeezed together and suctioned. The normal airlocks are more casual, more smooth

**Comment by MrFroztee** [comment]
I honestly think these sounds are too quiet for the sound of metal clashing on metal. Needs to be a more solid sound for a heavy door.

**Comment by Anticept** [comment]
I don't like them... They sound really weird and out of place.

**Pull request merged**
