### PR TITLE
Makes the UI a darker theme (And other styling tweaks)

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This PR tweaks the UI to make it more like other UIs in the game, and make it easier on the eyes (Dark themes are better, change my mind).

**Images of sprite/map changes (IF APPLICABLE):**
Full UI:
image
*A lot of tweaks*

Buttons:
image
*These have been themed to look like other UI buttons, and pushed down from the top slightly*

Tab area::
image
*This has been darkened, and the highlight color has been updated to show better on this color*

Chat window:
image
*The background of this has been set to #C0C0C0 as it is darker than pure white, but doesnt require a full style-sheet rewrite, as most other colors still match on it. The most grey thing I could think of was trinary, and this is how that looks*
image

Hotkey mode enabled:
image
*Now a green highlight instead of nothing, text is white*

Hotkey mode disabled:
image
*Highlight color darkened to make it look better with the UI*

Taskbar:
image
*This is how the tree looks on red, I am not changing my UI style for the sake of a PR*

Window title
image
*Again, not changing*

**Changelog:**
:cl: AffectedArc07
add: Paradise tree icon now shows on your taskbar and window title when you play
tweak: The main UI is now a darker theme to match the other UIs
tweak: Chat is now a grey instead of a white to make it easier on the eyes
/:cl:

***NOTICE:*** A cache clear may be required to make this work

### CODE REVIEW

**Comment by Deelite34** [comment]
Tab area looks sexy, gray chat window looks bit weird, but it's probably about getting used to it. I'm all for dark theme instead of white theme

**Comment by Citinited** [comment]
Personally I dislike light grey reading panes - but hey the rest of it looks pretty cool. 

Why'd you change the colour of the hotbar from white to green though? Should really try to keep that as readable as possible

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
bright red text in the chat window is hard to read, perhaps a darker shade would be better

**Comment by DrawitRalph** [comment]
Would it be too much to ask to make it toggleable?

**Comment by AffectedArc07** [comment]
Yes @DrawitRalph

**Comment by Ty-Omaha** [comment]
https://github.com/ParadiseSS13/Paradise/pull/10550/files#diff-295c1addd725262111a2924f585f525aR371

@AffectedArc07 That changes the changelog color, you could do something similar with the other things no?

**Comment by AffectedArc07** [comment]
@Ty-Omaha 
1) We have comments for this kind of thing
2) This is to handle changelog glowing orange when its unread, and white when its read. Now instead of being white unread, its the UI blue

**Comment by Ty-Omaha** [comment]
I know.

You asked me to find you a way to make the skin toggleable and I proposed a way

**Comment by AffectedArc07** [comment]
@Ty-Omaha that only applies to the button. This would have to apply to the user loading a different `skin.dmf`, which is pushed into the code on compile. So unless you make some abomination skin which has light and dark in different panes, basically 2 skins in 1 file, which sounds like a fucking horrible idea, there is no real way to do this.

**Comment by Ty-Omaha** [comment]
Push preference button, or check if user has saved preference for dark on startup
if so, proc loops through all desired elements like "browserwindow", "browser", "mapwindow" and sets the background-color and text-color to the dark theme, using the method that the changelog button uses

I am not following your logic of the changelog button being an entirely different thing, [it is just another skin element](https://github.com/ParadiseSS13/Paradise/pull/10550/files#diff-e9b841fdf3357c5888ab207ac587e749R1730) so the method that changes the changelog button can be used on everything else unless I am missing something

**Comment by AffectedArc07** [comment]
What about chat CSS, or can we just leave chat white (Actually come to think of it that would solve the issues of the colors looking off)

**Comment by AffectedArc07** [comment]
Unable to make a preference version

**Comment by KasparoVy** [comment]
Thansk for tryin

**Comment by Shadeykins** [comment]
As the server's only Discord white-theme user, I am not a fan.

**Comment by KasparoVy** [comment]
Why can't byond just use base16 :(

**Comment by FreeStylaLT** [comment]
Unfortunately forcing such a radical change from what we used to have for months when it is largely a subjective is something I'm against. I can't be certain that this is an improvement across the board, not sure if anyone can.

**Comment by AffectedArc07** [comment]
Closing because of #10758

**Pull request closed without merging**
