### PR TITLE
TG Traitor Objectives Assignment

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over TG's traitor assignment.

Without going into tons of details, basically this allows for the amount of traitor objectives to be customized, server side---it defaults to 2+hijack/escape/die a glorious death.

It also ensures that you can't get impossible combinations, like stealing an item then "die a glorious death" (as that doesn't make sense ICly and generates problems from a mechanics perspective).

This will introduce players to the "maroon" objective, which allows you to either kill *or* prevent them from getting off on the shuttle.

Objectives Removed from traitor
- Minimize casualties
 - Implied in server rules (even if it wasn't, this is pretty dull)
- Harm
 - This is just a conditional assassination, in practice; if the person gets their face fixed or their bones fixed, then this objective fails, so, in practice, you have to kill them.

Objectives out and out removed from the code:
- "harm". That is to say, the break someone's bones/disfigure their face
- Some old "anti revolution" objectives; no idea where these were even used at

:cl: Fox MCCloud
tweak: Removes "harm" traitor objective
tweak: Increases non-escape/hijack/die objectives from 1 to 2
tweak: Tweaks available objectives to traitors a bit
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
don't like removing the harm objective
other than that, :+1:

**Comment by taukausanake** [comment]
Would removing any of their limbs count as harming them? I wouldn't mind turning someone into a stump. Then that brings the question whenever robotic limbs count as repairing the damage.

Are logs kept of who attacks who? Couldn't you use those to track the objective and mark it as complete if you beat the guy? And I wouldn't make the objective fail if they got themselves repaired, I'd see it as making an example to them

**Comment by Necaladun** [comment]
Harm I -love- in theory, but is buggy and generally just means "Kill". If it's possible to keep it and trigger as intended - if they're ever harmed - and also spawn with a protect objective, so they have to be sent a message but NOT killed, that'd be a great one.

Debrain I never really liked for traitors, so good.

Steal+Die was always stupid and I thought we fixe dit but it came back :(

+1 objective for traitors is good. If possible it'd be great for it to be 1 "Major" and 1 "minor" objective, like kill and a steal.

Minimize casualties was just bad because it was mostly out of your control.

Maroon is a sure why not.

Overall it's a :+1: but it at least a :+1: :+1: with those changes I suggested.

**Comment by Dumbdumn5** [comment]
Don't like removing debrain and harm, otherwise :+1:. 
Debrain was fairly interesting in terms of how people actually got around the surgery and if they chose to place the brain in an MMI or not, still giving the victim a chance to be in the round if the traitor was willing to listen to them screaming. Harm, while buggy, seemed to give people something interesting to do aside from outright deathspraying the crap out of people.

**Pull request merged**
