### PR TITLE
Common guns sprite update

### PR DESCRIPTION
**Pull request by Stokes52**
## What Does This PR Do
  * Adds completely new in hand sprites for some lasers that lacked them
     * Retro laser
     * Laser tag lasers
     * Immolator (two variants)
     * Laser cannon

  * Updates the most commonly used gun sprites so that they:
     * Use a consistent color palette
     * Have proper shading and contrast
     * Evoke the classic SS13 guns we're familiar with, just updated with a newer look

Most sprites are meant to feel familiar to the originals, however a few sprites are completely redone (Combat shotgun, ERT carbine). I hope you like the result.

## Why It's Good For The Game
The current weapons have very different styles, color palettes, inconsistent shading, and in some cases odd shapes.  The goal of this PR is to make everything look like it belongs in the same world.

### New Inhand sprites:
inhands

### Ingame:
*Before*
ingame_old

*After*
ingame_new

*Side by side comparison:*
comparison

### Bonus!!
*The bartender gun has all new alternate shotgun skins they can use with alt click*
From top to bottom:
* Black Polymer
* Ashwood and Iron
* Cherry and Nickel
* Ivory and Nickel
* Gold Plated

bartender_variants

## Changelog
:cl:
add: New in hand sprites for lasers that were missing them
tweak: Updated many common weapon sprites to have a consistent style
/:cl:

### CODE REVIEW

**Comment by hal9000PR** [comment]
Please post pictures of the modified shotgun in hands.

**Comment by Stokes52** [comment]
inhand_shotties

**Comment by McRamon** [comment]
This is decent quality update, i approve.
I dislike usage of modern guns but that can be changed in future with proper art direction (if it happens).
I just hope noone will scream "guns were just changed no need to change them again reeeee

**Comment by MRgaty** [comment]
The combat shotgun one hurts deep inside me. They are cool tho.

**Comment by S34NW** [comment]
These look great, the shading is vastly improved and shotgun variety is nice to see (as opposed to reskins with slight tweaks like it is currently)

**Comment by maxymax13** [comment]
that db shotgun 👁️👁️

**Comment by LiberatedWaveMan** [comment]
Absolutely loving the spritework, nice one

**Review by dearmochi — APPROVED** [review]

**Comment by DogsParadise** [comment]
Combat shotgun could still use some work

**Comment by SteelSlayer** [comment]
I like most of these sprites. However, I'm not sold on are riot shotgun and sawed-off riot shotgun, particularly the sawed-off. The colors/shading on these two just look odd to me. And I'm not saying I like the original one better or anything.

**Comment by Carthusia** [comment]
> I like most of these sprites. However, I'm not sold on the riot shotgun and sawed-off riot shotgun, particularly the sawed-off. The colors/shading on these two just look odd to me. And I'm not saying I like the original ones better or anything.

I feel its the lack of a stock, i like it, but that lack of a stock on the sawn of riot just looks odd due to it also having the forward handle for easy racking.

I mean i own somthing like that, more or less the exact same thing, but sprite wise it does look a tad odd when you see them side by side.

The auto rifles green ammo indicator also seems really dark compared to the old one and a bit harder to notice compared to the other weapons ammo indicators

**Comment by Stokes52** [comment]
> The auto rifles green ammo indicator also seems really dark compared to the old one and a bit harder to notice compared to the other weapons ammo indicators

This is fixed in the latest commit.

**Comment by hal9000PR** [comment]
I'm not sure about the assault shotty or the combat shotty but otherwise these look good.

**Comment by DogsParadise** [comment]
Sawed off stock looks off, your not cutting off half the stock.. i imagine.

Shading is off on a few of these sprites.

I guess it would be a slight improvement over all, but sawed off and that combat shotgun need some love

**Review by Kyep — APPROVED** [review]

**Comment by Stokes52** [comment]
@DogsParadise for these, yes, half the stock is being cut off. A sawn-off can be done many ways, but most commonly the entire stock is cut when the goal is concealment.  This can be done cleanly by sanding it down or with a ugly cut, but both ways work.

Examples:
example


See also [this example](https://static.wikia.nocookie.net/hunthorrorsofthegildedage_gamepedia/images/5/54/Specter_1882_Compact.png/revision/latest?cb=20190109032022) with a modified slide.

I can improve shading but you'll need to be more specific on exactly how/where, you can DM me on discord if that's easier.

**Comment by Stokes52** [comment]
Some minor shading updates:
shading_v2

**Comment by ZanderDoggo** [comment]
Absolutely love the work! The new designs are so good and will add a bit more freshness to the server. I especially love the ERT specific weapons, my question for the ERT security rifle, did you change the magazine sprite to match as well? Either way, love the work and thank you for spending your time creating these beautiful pieces of art!

**Comment by S34NW** [comment]
> 
> 
> Some minor shading updates:
> shading_v2

Is there a version of the riot where the stock doesn't look split? I don't know if it's trying to convey a "folding stock" idea but it just looks a bit... off?

**Comment by Stokes52** [comment]
> Is there a version of the riot where the stock doesn't look split? I don't know if it's trying to convey a "folding stock" idea but it just looks a bit... off?

@S34NW 
The riot shotgun stock and grip is meant to look [something like this](https://images.proxibid.com/AuctionImages/3777/137626/FullSize/210.jpg) where the grip is integrated into the stock.

**Comment by S34NW** [comment]
> 
> 
> > Is there a version of the riot where the stock doesn't look split? I don't know if it's trying to convey a "folding stock" idea but it just looks a bit... off?
> 
> @S34NW
> The riot shotgun stock and grip is meant to look [something like this](https://images.proxibid.com/AuctionImages/3777/137626/FullSize/210.jpg) where the grip is integrated into the stock.

Ah, fair. As a non-gun person, I wasn't aware this was a thing, so it just looked weird to me.

**Comment by Stokes52** [comment]
Hello maintainers, @Fox-McCloud @AffectedArc07 @Crazylemon64.

I hope it's okay to ping you.  Since this has been open a while, please let me know if you would like me to fix the merge conflicts, close this PR, or continue to wait.  Thank you for your time. :)

**Comment by Spacemanspark** [comment]
I'm only just seeing this.

Not really a fan of the egun or epistol changes. The gun looks a bit too simple now, while the pistol looks a bit too much like a normal handgun. The handle 'guard' as I'd guess you'd call it was a nice touch.

**Review by variableundefined — CHANGES_REQUESTED** [review]
So here's what I think. 

I am pretty neutral on most of the energy guns changes, I don't really have an opinion one way or another. 

I love the in hand sprites and I think adding inhand sprites for missing items should be encouraged. 

The shotguns - I like the variety, but something strike me as very odd about those sprites - they look out of place, very different. While the previous sprites seems to fit in with the art style of rest of SS13, those guns sprites look like they came straight out of another game. In the side-by-side comparison it is made even more obvious.

So personally, I prefer to just add in the inhand sprites.

**Comment by variableundefined** [comment]
Closing this PR now for two objections. 

We're not really keen on changing sprites for the sake of changing them - Especially gun sprites in general. Also, both of us don't believe these are an objective improvement over the existing sprites. 

As I've mentioned before the shotgun sprites in particular look very jarring.

**Comment by Darkmight9** [comment]
@Stokes52 A possible idea is splitting the PR into parts such as adding in the new inhand sprites in one PR, resprited energy guns in another, regular firearms in a third and the shotguns in a forth if you want to give them another shot

**Pull request closed without merging**
