### PR TITLE
Adds in Chainsaws

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Simply put, adds in chainsaws

chainsaw

Chainsaw stats:
Weight class: 4 (no backpacks, no belt, no back, nothing--only can be carried in your hands).
Weapon type: dual-handed melee weapon
Damage when unwielded: 15
Damage when wielded: 50
Special features: Stuns when wielded. Can turn corpses into meat. 
Downsides: INCREDIBLY noisy. Has unique sound when initially wielded and also plays a unique sound when you're attacking someone with it--it's *very* loud, *very* distinctive, and *very* obvious. You get this thing, and everyone KNOWS you have it.

You'll be able to purchase it on the uplink for a whopping 13 TC--it's an even more blatant and obvious weapon than the e-sword is--no way to conceal it, the sprite is noticeable from a mile away, and the sound is very loud+travels for a significant distance. In exchange for this, you get an incredibly robust weapon that can compete against sec's stun batons and potentially allow you to go toe to toe with them. It also has the same feature as the traitor chef's meatcleaver---being able to 'cut people to pieces' (turn them into meat with their name on it).

Credit to TKDRG of TG for the sprites (from a now defunct PR of his) and Lonemonk of Freesound for the sounds. Big thanks to @tigercat2000 for helping with the sounds.

### CODE REVIEW

**Comment by adrkiller59** [comment]
*whistles
http://www.mediafire.com/view/8sp86eo9fvt89k3/Chainsword.dmi
Just leavin' this here.

**Comment by Spacemanspark** [comment]
Doesn't this encourage the issues we're currently having with murderboning and whatnot?
I like the idea, but I do have my concerns.

**Comment by tigercat2000** [comment]
:+1:, I think.

**Comment by fj45** [comment]
Yes, I do have to agree with Kei here, it could be problematic,

**Comment by Nienhaus** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=11&t=1659
Pretty sure this is there the chainsaw sprite is from.

**Comment by SamCroswell** [comment]
I fail to see how this is problematic. The energy sword is cheaper, easier to conceal, and is more discrete, as well as also acting as a riot shield when activated.

The only upside to the chainsaw is it deals more damage and can gib corpses.

On top of that, if someone's goal really is to go on a murder rampage they can purchase the large syndicate bomb for cheaper than this chainsaw. If anything it's under-powered.

**Comment by Spacemanspark** [comment]
It's the fact that since it out and put gibs dead bodies, can't be stored anywhere (Therefore encouraging open and often combat, and to an extent murderboning.) and still deals a hefty amount of damage when wielded that gives off a bad vibe to me.

**Comment by Spacemanspark** [comment]
To elaborate, my issue is that the item encourages murderboning, not that it's OP.

**Comment by Fox-McCloud** [comment]
You could make that argument for any number of items though.

Revolver+auto-lathe = near unlimited killing potential.

Double esword = nigh unstunnable, high damage weapon that ALSO reflects the damage/stuns back at the attacker

Power gloves--Insta-kill potential with no resource cost--at range.

Chef's Meatcleaver---high damage weapon that also gibs corpses

Chef's Special Sauce--blatantly meant to be used no-holds bar and just out and out put in just about any/all food.

esword+ebow---the classic; entire sec teams have fallen to this combination.

So we already have weapons that "encourage murderboning".


And all of this is not to mention Para's more recent trend to more open-ended antags behaviors.

**Comment by Spacemanspark** [comment]
A trend which is very awful.

**Comment by Iamgoofball** [comment]
Just because you want the game to be a hugbox doesn't mean it will be.

:+1: from me.

**Comment by fj45** [comment]
Goof, last thing I want is a hugbox too but murderboning is often crap.

**Comment by Regen1** [comment]
I don't think you're understanding the issue that @Spacemanspark is trying to point out here @Fox-McCloud 
The reason it encourages more murderboning us because you literally can't hide it.
WIth an esword, revolver, meat cleaver you name it you can actually hide it on your person, while the chainsaw is loud, obvious and impossible to hide if not in a closet it encourages the player to just use it as much as they can for as long as they can.

**Comment by Fox-McCloud** [comment]
@ZomgPonies  @Markolie 

Merge when? D=

**Pull request merged**
