### PR TITLE
Sushi Update

### PR DESCRIPTION
**Pull request by FalseIncarnate**
<h3> The Somewhat Awaited Sushi Update!</h3>
<hr>
image
image
<hr>
Adds multiple types of sushi, made from various ingredients including rice, egg, fish, and fish eggs.
- Most sushi recipes are made via table-crafting, though Tamago Sushi requires a grill to prepare.

Adds multiple new types of fish for the fish tanks! Their eggs can be purchased in the CritterCar vendor.
- Catfish
 - Will periodically reduce the filth level of the tank, helping keep it clean while you are busy.
- Feederfish
 - Will sometimes sacrifice itself to add food to the tank for other fish. Will not sacrifice if it is the last fish, or if the food level is sufficiently high
- Shrimp
- Salmon
- Electric Eel
- Glofish
 - Will produce light if the the tank light is off.

Adds fish items for each fish you can raise!
- Most fish are simply weak weapons you can slap people with.
- Sharks and baby carp do slightly higher damage, and make a bite sound on hit
 - Sharks can have their teeth removed by using a wirecutter on them.
 - Toothless sharks lose their extra damage, nor do they make the bite sound
 - Shark teeth will be used in various future recipes for things like necklaces and weapons
- Salmon and catfish can be cut into filets with a knife
- Shrimp and feederfish can be eaten raw, though they aren't very filling (pure protein though!)
- Glofish, you guessed it, glow! They give off a weak green-colored light.
- Clownfish are slippery like banana peels! HONK!
- Electric eels do not zap people, but will be used in a future crafting recipe or two for an improvised stun weapon.

Tweaked the rate at which filth will accumulate in a tank, so hopefully it won't be a full time job to maintain a single goldfish.
- Tanks with no fish will get dirty at a lower rate than before, and will not continue to get dirty if the filth_level is 7.5 or higher
 - Previously: 25% chance to increase by 0.1
 - Now: 15% chance to increase by 0.05
- Tanks with at least one fish now will get dirty slightly less often
 - Previously: 25% chance to increase by 0.1 with a 30% chance to increase by 0.1 per fish if they ate that cycle
 - Now: 10% chance to increase by 0.1 with a 25% chance to increase by 0.1 per fish if they ate that cycle

Using a fish net on a fish tank will now let you select a fish to
remove, instead of selecting one at random.
- Catching a fish with the fish net will now remove it from the tank and
drop the appropriate fish item at your feet.

Added support for special cooking via cooker machines (deepfryer, cereal
maker, old candy maker, old oven)
- Only the deepfryer currently utilizes it (as the other machines aren't
used currently)
 - Inserting specific items will cook them into a new item instead of
simply frying them!

New deepfryer recipes:
- Tofu can be deepfried into Fried Tofu!
- Raw sticks (from slicing potatoes) can be deepfried into a bag of chips!
- Bananas can be deepfried into Fried Bananas! (old recipe still possible)
- Corn can be deepfried into a bag of Corn Chips!
 - This is the same as a bag of chips, except Space Mexican
- Shrimp can be deepfried into Fried Shrimp!

Began phase 1 of re-organizing/dividing food icons and code into multiple files
- The existing icon file was nearing capacity, and the code file was incredibly long
 - This re-organization will make it easier for coders to find, edit, and group similar/related foods together, without worrying about overfilling the food icon file
 - This means we can add way more foods in the future without worrying about the icon being full!

Sprites courtesy of FullOfSkittles, with a few of my own horrendous recolors/edits.
- Not all of the new sprites are currently used, but are planned for use in a near-future PR to further expand the food options available.

### CODE REVIEW

**Comment by M3hillus** [comment]
:+1:

**Comment by Keilden** [comment]
:+1:

**Comment by Zuhayr** [comment]
Would it be alright for me to steal these sprites for Europa?

**Comment by FalseIncarnate** [comment]
@Zuhayr I would assume so, but you'd want to double check with FullOfSkittles. She did most of the work on them, but she likely will say yes

**Comment by TheDZD** [comment]
> Most fish are simply weak weapons you can slap people with.
Cannot :+1: this enough.

**Pull request merged**
