### PR TITLE
Adds Salmon Suit

### PR DESCRIPTION
**Pull request by kugamo**
## What Does This PR Do
This PR adds the **Salmon Suit** which can be made with 20 salmon, 5 duct tape, a knife, and a pair of wirecutters.

## Why It's Good For The Game
Become your friendly neighborhood salmon man! Fishy fun for all ages.

## Images of changes

Aseprite_App4HWhsDW

Aseprite_tW00EbVOhK

dreamseeker_mA6O7J8No5

## Changelog
:cl:
add: Adds Salmon Suit, and a crafting recipe for it.
imageadd: Adds sprites for salmon suit.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
This PR got me hook, line, and sinker.

**Comment by Mitchs98** [comment]
Beautiful.

**Review by SteelSlayer — APPROVED** [review]
Yes

**Review by variableundefined — APPROVED** [review]

**Review by farie82 — APPROVED** [review]
Yes

**Comment by Pyrodes** [comment]
Yes

**Review by Kyep — APPROVED** [review]

**Pull request merged**
