### PR TITLE
Adds tech levels to RnD main menu display

### PR DESCRIPTION
**Pull request by Ar3nn**
A recreation of the failure that was #4840 

Maybe it won't break this time.

main menu change

:cl: Ar3nn
tweak: Adds tech levels to RnD console main menu
/:cl:

### CODE REVIEW

**Comment by Ar3nn** [comment]
Being as I ripped the files straight out before nuking the old branch and pasted them back in after, it should all be exactly the same as before, just without 114 additional file changes.

**Comment by monster860** [comment]
Keep the "current research levels" button because MUH FLUFFTEXT.

**Comment by Ar3nn** [comment]
@Fox-McCloud which would you prefer? People are requesting both button and no button.

**Comment by monster860** [comment]
I'm not too big a fan of this anyways. It kinda doesn't look like it fits there.

**Comment by Ar3nn** [comment]
It fits just fine. I'll update the OP with the screenshot.

**Comment by monster860** [comment]
Yeah, that looks really out of place to me.

**Comment by Ar3nn** [comment]
Well if you have a suggestion to make it look better to you, I'd make an attempt.

**Comment by Twinmold93** [comment]
To me, all that information on a main menu is... Too much. A main menu shouldn't overwhelm someone with information.

**Comment by Ar3nn** [comment]
I just feel like this: 
1) The way the current research level menu is laid out, while it looks fine, is way too much. You only really need a simple list like this anyway for it.
2) The extra click to get in there, and scrolling up and down to read all the values, takes a lot of time. 

Putting it up-front and making the list smaller helps with both of these things. You could argue that it could at least be mollified by just making the list smaller (removing the boxes on the inner list) but this is the solution I thought was better. Explain how its overwhelming anyway? It's core information that anyone looking at this menu needs to know so they know what's available in the protolathe/circuit imprinter.

**Comment by monster860** [comment]
Come on, we all know the *real* this PR was made. It's to easily load values into the rndTool!

**Comment by Davdichan** [comment]
Until someone figures out how to port the Supply Order / Cargo computer to RnD, this is about the best we can hope for here.

**Comment by Ar3nn** [comment]
If someone wants to tackle making a similar modular function for these computers, I'll be glad to close my PR when theirs goes up. Until then, I think this is fine, personally.

**Pull request merged**
