### PR TITLE
Clean up skin.dmf, fix input darkmode, add statusbar toggle option

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

Edits the `skin.dmf` file to clean up the bloat and moves some elements around to improve colour/spacing consistency.

## Why It's Good For The Game

More visual consistency and the ability to disable the bottom-left status bar since we have screentips now.

## Images of changes

dreamseeker_hS2ecLPiBY

dreamseeker_HGXxTY8cR7

dreamseeker_PsKH3FDTox

## Changelog
:cl:
add: Add option to disable the status bar in the bottom left of the viewport in the menu at the top. Options > Show status bar
tweak: Clean up the game window a bit so things look and are positioned more consistently
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Amazing, thanks for making this. Especially `Add option to disable the status bar in the bottom left of the viewport in the menu at the top. Options > Show status bar`

**Comment by AffectedArc07** [comment]
Tempted to break retirement rules just to get this in

**Comment by S34NW** [comment]
While you are at it, can you add `flags = NO_SCREENTIPS` to `/obj/effect/statclick`?
Prevents this from happening:
image

**Review by AffectedArc07 — APPROVED** [review]
Im merging this because the UI hurts me at the moment, and darkmode is bugged

**Pull request merged**
