### PR TITLE
NT medical screening for key jobs

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
add: Captain and HoS can no longer have most disabilities at roundstart.
🆑

With this PR, the Captain/HoS may no longer have any of the following disabilities:

1. Deaf
2. Blind
3. Mute
4. Scrambled Speech
5. Epilepsy/Seizures
6. Tourettes Syndrome
7. Nearsightedness
8. Dizziness

Characters with any of these disabilities will not be eligible for Captain/HoS positions.

Any disability NOT listed above (e.g: obesity, color blindness, wheelchair-bound, etc) is NOT prohibited.

### CODE REVIEW

**Comment by Hylocereus** [comment]
It's about time. Who the fuck hires a blind, deaf, mute retard into a role of authority? You CANNOT be mute as a command member without jeopardizing the ability of your department. Yes, it disrupts your IC stuff if you have a mute snowflake, but let's be real even assuming the NSS Cyberiad is where they send the rejects of their employees, NT is not going to hire on someone who can't perform their job to a base minimum.

When my snowflake is blind and mute, I don't play command with her either, because I don't like handicapping other people for the sake of my RP. If I went mute in a job that required a lot of communication I wouldn't expect my employers to just go "well he's good at it aside from the not talking thing, let's keep them even though it's detrimental to their co-workers!"

**Comment by Spartan6** [comment]
Does this still allow wheelchaired people?

**Comment by DrunkDwarf** [comment]
This is very ableist.  Whether command personnel are able to perform their job should only be a factor of their leadership ability and knowledge of their job. 

Disabilities don't inherently affect leadership ability. A blind person can still communicate with others, the issue is staff not communicating with their head to provide vital information, a head shouldn't have to be running about doing everything them self if they have competent staff who communicate. A deaf or mute person can still communicate pretty effectively using the PDA and emotes, Jovan Taru is a great example of this. Same goes for tourettes, or have scrambled speech, they can still communicate.

**Comment by Jovaniph** [comment]
You gotta be kidding me. I hope this is a meme PR.

**Comment by Citinited** [comment]
`This is very ableist. Whether command personnel are able to perform their job should only be a factor of their leadership ability and knowledge of their job.`

Play a Chief Engineer without arms and tell me how that goes.

**Comment by Jovaniph** [comment]
@Citinited that's creating a strawman argument. I play CE mute very well actually.

**Comment by Spacemanspark** [comment]
why would NT hire a person that is incapable of proper communication, into a role where it is critical?

**Comment by Citinited** [comment]
@Jovaniph Not a strawman. That person's point is that disabilities do not factor into playing command roles. Having no arms is a disability and prevents you from doing anything related to engineering (which is something that Chief Engineers need to be able to do). Therefore having no arms directly impacts your ability to play a command role.

**Comment by Jovaniph** [comment]
This feels like an attack for player who play IC mute. It's not fair at all. I've made my argument in the forums about this. If you want to discriminate how I play then goodbye Paradise... It's been fun while it lasted.

**Comment by DrunkDwarf** [comment]
@Spacemanspark That really depends on what you personally define as "proper communication", even a mute is perfectly capable of communicating through mechanics already available in the game, typing a response to someone via a PDA message is not any less clear a form of communication than saying it directly. I would agree that communicating is a very important part of command and security roles, I just don't agree that there is a need to restrict what type of communication is considered the only acceptable method.

**Comment by Kyep** [comment]
@DrunkDwarf
Leadership requires the ability to communicate quickly and effectively. It also requires situational awareness.

For example:
- Deaf characters are never going to be as situationaly aware as normal characters, because they won't hear anything said on radio, which is where most of the important communication in SS13 happens. In SS13, there really is no substitute for radio.
- Mute characters are never going to be as effective at communication as normal characters, because they won't be able to speak effectively to groups of people from wherever they are. The most they can do is use a station announcement, but that relies on them being near a working console, one they have access to, is powered, is not on cooldown, etc. It also requires that the information be suitable for crew-wide broadcast.

I cannot be a professional weightlifter, because I am not able to lift the super-heavy weights they use in weightlifting competitions.
Is the weightlifting profession discriminating against me because of my lack of lifting ability?
No. They simply have a requirement that in order to be a professional weightlifter, you have to actually be able to lift weights, and I can't.
They're not judging me as a person, they're just saying that weightlifters have to be able to lift weights.
The reason I cannot lift the weights is irrelevant. It could be because I have a disability. It could be because I am simply not strong enough to lift weights professionally.
The reason doesn't matter. If I can't do the job, I can't do the job. The reason why I can't is irrelevant.
To give another example, if I had haemophilia, I would not expect to be allowed to be a soldier, wrestler, policeman, etc. Because I would not be able to handle the fighting that comes with the job. I might get seriously injured, and bleed out.
In short: the requirements of the job come first - and if I cannot meet them, for whatever reason, it is unreasonable to expect that I would be allowed to take that job. SS13 is no different in this regard.

In SS13, the requirements of Sec/Command positions include the ability to communicate well, be perceptive of your surroundings and the station environment, etc.
Being deaf, mute, blind, etc means the character isn't capable of doing that to normal standards.
So, they shouldn't be allowed to take jobs where doing those things is a requirement.
This doesn't apply to most jobs, but it does apply to Command/sec jobs where everyone is *counting* on them to be aware, and react, quickly and effectively.

I understand your argument that we could simply add features to the game that would enable disabled characters to still perform adequately at these jobs.
However, that argument ignores several relevant facts:
- This may simply not be possible. How, exactly, would a blind member of Security be able to effectively chase and arrest criminals? They couldn't.
- Even if it were possible, it might be prohibitively costly to do. I suspect you underestimate the amount of code it would take to allow any character with any disability to do anything. Allowing blind characters, for example, to 'see' would require effectively a second vision system. Allowing deaf characters to 'hear' radio without hearing would require some kind of translation system. Etc. And so on for every requirement, and every problematic disability.
- Even if it were possible, and not prohibitively costly to do, it would negate the point of having the disability in the first place. What's the point of supporting disabilities in-game if they have no actual consequence for taking them - if, despite taking them, they don't actually limit you at all? That just means we've done a lot of work to nerf disabilities into the point of being meaningless.

On the contrary:
- Stopping characters who we have good reason to think wouldn't be able to perform a job (due to disability) from taking that job is very possible. This PR actually does it.
- It isn't prohibitively costly, either. This PR is small.
- It doesn't negate the point of playing a character with disabilities, either. In fact, its more immersive, as it recognizes the fact that characters with certain disabilities simply can't do certain things.

This PR is not saying that a character with any disability is assumed to be unable to play command roles. There are actually a fair few disabilities that this PR completely ignores.

What this PR is saying is: characters who cannot communicate effectively, properly perceive their surroundings, etc, are unsuitable for leadership roles, because these roles require the ability to do these things.

**Comment by Kyep** [comment]
@Spartan6 
No, it doesn't. The criteria for spawning with a wheelchair is that you must be missing both feet.
This is not recognized as one of the disabilities in the list at the top of the PR, thus it does not count.

Additionally, I see no reason to include it. Wheelchair use doesn't impair someone's ability to communicate. It doesn't impair their ability to be aware of their surroundings. You could argue that it makes them vulnerable to being unseated, which is true, but that can only be done from melee range, and if you have hostiles in melee range you're going to suffer, wheelchair or no.

So, no, it isn't included, and right now I see no reason why it should be.

**Comment by DrunkDwarf** [comment]
@Kyep The point of pretty much every disability in the game, is Role-play. A department head role-playing one of these disabilities and facing those challenges, has the potential for some great role-play. And there have been some good examples of individuals able to perform some of those roles with disabilities without it having a negative impact on the round, Jovan for example.

I agree some of the more extreme disabilities will make it impossible to do specific roles, primarily Security. But the disabilities this PR has restricted are not all equally prohibitive to ALL command roles. The inclusion of mute for example, is without the doubt the most contentious, and does not pose the same level of handicap as being blind for example.

**Comment by Kyep** [comment]
@DrunkDwarf 
We shouldn't judge things by their potential best outcome. We should judge them by their average outcome. The average outcome of a deaf or mute head, for example, is a dysfunctional department, due to the lack of communication. The average outcome of a head with blindness is that they become a loot pinata. Etc. Most people wouldn't call having to go to twice the effort to accommodate their head's disability 'roleplay'. They would call it 'annoying' and/or 'tedious'. Or, knowing you chose to have that disability on your character, they simply wouldn't bother making any accommodations at all. They'd assume that if you are, for example, deaf, you don't *want* to hear, or be informed - and they wouldn't inform you. Hence, very dysfunctional department.

The basic problem here is that by choosing to play a character that cannot perform the basic functions of their job, like listening to radio, you are asking everyone around you to do extra to work around your voluntarily chosen character disability. This is generally not fun or engaging for everyone else, and since you're a head of staff, they need you to be competent, and don't have the option of simply not dealing with you. 

In short: if you want to play a character with a disability, that's fine. But if you want to play a character with a disability that prevents them from doing their job, and then expect everyone else to cover for you and help you so that you can try to perform adequately.... that's inconsiderate, and a problem.

**Comment by Regen1** [comment]
I'd also like to add, screaming "BUT THE RP!!!"

In ss13 you have genetic manipulation and robotic limbs, if a security officer does his job well, but looses an arm in a fight, NT would offer to replace the arm, through surgery or through a robotic limb. 

Wanting to RP something is all fine and dandy, but don't try to make this into an IC issue, because IC you would've been asked to fix your disability (Which can be easily done), or NT will find a job for you which doesn't require those essentials.

One person RPing it well doesn't set the bar for how everyone play, it's a shame that this is seen as a personal attack, but it really isn't.

**Comment by Regen1** [comment]
Also please, this isn't a social justice corner

>This is very ableist.

@DrunkDwarf In a world where admins are literally the gods, and genetic defects can be fixed with a machine and a few presses it's not ableist. Those kind of accusations do not belong here.

**Comment by Landerlow** [comment]
Well, I will give my two cents.

I have a disability (physically, and it's just my legs, no mental issues or blindness or whatever) in real life. It makes no difference whether or not a person is disabled when it comes to doing a job. The issue is how one handles with the disability. If you handle a disability well, you can handle the job well. I see far more moments where "healthy" command members are absolute abominations when it comes to doing their jobs. 


Furthermore this PR feels a bit too much of a personal attack on Jovaniph, but that might just be me. There has been no issue with things like this, until Jovaniph got .. told not to play a disabled command member. 

I myself have played captain with tourettes once. While it is hard and was a pain, it could be fixed. Even if I did not get it fixed, I could actually cope fairly well. Lots of people who play a disability - command role with it or not  - are perfectly capable of doing their chosen job, with their disability.


I *seriously* hope this PR does NOT get merged. Instead, encourage better  communication, roleplay, and take on the actual issue which is that a lot of players who play command simply refuse to communicate or do their jobs properly because they can't be arsed instead of being disabled.

**Comment by Spacemanspark** [comment]
@Landerlow if you read the PR description in full, you'd see that it's just the blind/ mute/ et cetera disabilities. Not amputees, neccessarily, that are being blocked.

**Comment by Shadeykins** [comment]
I'd like to point out that this PR is **not** about Jovaniph. I've been playing on the server for several years, and I've seen veritable hordes of mute HoP's, CMO's, and Captains get demoted by CC over this period of time.

It's never been okay to hinder an entire department and make everyone work around you by playing a mute in Command, irrespective of how robust or competent you are. This is the exact same reason why nuclear operatives and ERT's are no longer allowed to spawn with disabilities.

This is just mechanical enforcement of something that's already been enforced by policy.

**Comment by taukausanake** [comment]
@Spacemanspark He was using his own disability as an example. Missing a limb is a lot more limiting than half the genetic disabilities (blindness being the only one worse).

I agree with @Landerlow. I first thought this was something that might need to be merged but I feel it is better for people to try and play with the challenges they put up to themselves. If they can't handle it then by IC they should be replaced with someone more capable

**Comment by KasparoVy** [comment]
Full support, no memes.

**Comment by Tayyyyyyy** [comment]
SS13 takes place in a hypercapitalist dystopia where a corporation has the authority to execute you...while I am 100% against ableist hiring in real life, I don't think it's unreasonable that NT would impose these regulations.

I don't know if this PR is 100% necessary, though. I feel like if a head is failing to communicate properly, then IC means can always be used to remove them.

**Comment by Regen1** [comment]
>I have a disability (physically, and it's just my legs, no mental issues or blindness or whatever) in real life. It makes no difference whether or not a person is disabled when it comes to doing a job. The issue is how one handles with the disability.

I mean absolutely no offence in this, but if your legs are disabled you wouldn't be hired as a security guard who might have to rely on running to catch someone. That's the flat out truth to it.

An officer who needs to be verbal and communicate well wouldn't be hired for that job if they were physically unable to communicate over comms, when comms is by far the most used method of communication. They'd be a huge liability to the security of the station, and if it's a fixable problem then the ultimatum would be to fix the problem or find a better suited job.

This PR goes to solve the problem of that discrepancy, Jovan might be doing it well, but he is also most likely among the very few who does it well.

**Comment by DesolateG** [comment]
NanoTrasen is an EOE, this is discrimination.

**Comment by The-Driker** [comment]
I'm just going to put in my two cents as a regular engineering player, because having perspectives from all sides is handy in these type of situations.

I have been on the receiving end of having a mute chief engineer as of late, and I'm not going to list any names, but I will say that it absolutely sucks. Sure the person did their job as far as the engineering side goes, but the lack of communication was painful. Listening to radio silence until somebody relayed something that was sent to them through PDA, lost valuable time, and crew died because of it. 

Yes if there had been an AI it could have announced the plasma fire, but there wasn't one and the chief engineer who learned of the situation first had to get someone else to relay the message. By the time they had gotten the message relayed, I as a cyborg was already aware of the situation and traveling there because of my sensors.

So don't get me wrong, I honestly don't feel like this needs to be merged, but from some of the things I've experienced I can definitely see why people would want it to be.

**Comment by MrFroztee** [comment]
As somebody who plays Command with no legs, I'm sure it's biased of me to disapprove of such a PR. I really don't like the concept that we're setting the bar that only mary sues and john does will be able to play Command roles now, as I have proven capable of performing just as well as somebody with legs.

If this is an issue of shitlers ruining the round with disabilities that hinder them and the station, they should be command banned. I like to think I earned the right to play a character with no legs, having shown competence and effectiveness as a Captain.

**Comment by Very-Soft** [comment]
While I am in support of this in large part, I do think it's too heavy handed and broadly sweeping for the most part, and also doesn't cover enough at the same time.

I would argue that SOME members of command can operate perfectly fine with missing certain functions. 

A captain that can't see is not -that- big a deal, being as they usually have help very close by to begin with, and would not be impaired in doing their job all that much in terms of commanding and informing the crew. They ought to know the rules and the general threats that can affect the station, and be well versed in space law, because reading it's gonna be an issue on the spot, but it ought to be expected that they SHOULD be familiar with these things. So them being blind wouldn't generally be that big a deal I would think.

The RD in large part only really needs to approve or deny projects. There aren't a whole lot of situations where they really need to communicate widely, and it's the sort of role where I think a company would allow some freak mute supernerd to be in, as they'd want the smartest guy, despite disabilities. 

And finally, again, the CE would be chosen for their skill and knowhow I feel like, as long as they have the tools in place to actually communicate with their department reliably. LUCKILY, NT has that neato chatroom feature available via PDAs. Which I would think would not be an unreasonable place for a mute CE to collect their team into, so that they can communicate to them all at once. And if PDAs are down, then they are probably going to resort to silence or station announcements anyway while they work on fixxing the issue, mute or not.

PASSED all that, while I agree that security for the most part does need to be able to speak, I think you left out an important department in that: Medical. Medical needs to be able to tell people what's up and why. Realistically IC it would be a giant stupid lawsuit waiting to happen if someone was running around wordlessly sticking people with needles and performing surgery without the ability to effectively communicate with, say, a blind person.

Just my thoughts, TL;DR,

It should be plain to see by short observation who's performing poorly at a role, and who's not. Make individual decisions over this, rather than completely restricting certain ways of playing by arbitrary mechanics.

**Comment by Kyep** [comment]
Would you entrust the safeguarding of the Nuclear Disk to a blind Captain? How exactly would they even know they're about to be shot? They'd be dead before they even knew who was shooting at them.

RDs regularly face situations where they have to advise command and/or the crew at large about risks. Just today we had a round where someone bred sentient spiders in Xeno. There were spiders in literally every room on the station. That sort of situation requires a RD who can communicate. Not least because many crew had to be armed to deal with the spider menace.

Chatrooms are not adequate. Aside from the fact they're opt-in, they are prone to creating lag / server issues.

Medical is arguable. You can treat people silently as a medic, and many do. You cannot be a silent member of Command or Security without completely compromising your department's ability to function.

While we do job-ban people who deliberately do a terrible job in sec/command roles, that's still no reason to allow people to sign up for said roles with conditions that make their doing well extremely difficult to impossible.

**Comment by Very-Soft** [comment]
Well to your first point, the captain would know they need to protect the disk, just like any other captain. Blind people can feel when things enter or leave their pockets, just like anyone else. And if I'm honest, Captains get killed quite effectively who can see just fine, and then it's usually the blueshield, who is almost always standing behind them, gets them out of that trouble again. The Captain's job is to be on the bridge commanding the crew, and keeping track of the disk. That is a job that I personally think could be handled by a blind person in this example. Experienced leaders can be blind. It's not ideal, and I wouldn't want them to be like, piloting anything? But commanding? Sure.

The situation you describe with the RD and the spiders sounds like one that could quite effectively be communicated with a PDA, or the announcement computer. It's not as convenient, but that's not what the game's about, generally.

Further, I was under the impression that the chatroom's work just fine so long as you aren't inviting the whole server to them. I've had the whole engineering department in them a number of times with no apparent negative effects. That was admittedly a while ago though, so perhaps things have changed since then.

I think people who do deliberately terrible ought to be disallowed to participate in critical roles. I agree with you there. However, I think that it should be up to that individual situation to be decided upon, rather than outright denying certain kinds of characters because they _might_ [probably will be] bad.

I speak out about it, because I know that these things CAN be done well by those that will put in the effort. And I think that those ones should be allowed to try. This change denies them that.

**Comment by Kyep** [comment]
In my opinion, it is illogical to require every case to be considered individually. There simply isn't time. Admin time/attention is a limited resource. We cannot operate under a paradigm that absolutely everything must be permitted and only by an admin judging that individual person in their individual situation to have been bad, can it be ruled impermissible. That sort of paradigm is just totally, absurdly, impractical. Not to mention unfair to players - it makes EVERYTHING subject to the subjective opinions of the admin reviewing the case. No rules, no policies, no code-based sanity checks, even. Impossibly impractical.

We have code that prevents certain things from happening. We have rules that say certain things are not allowed. We have IC conventions that say certain things are bad ideas and you risk consequences for doing so. All of these things are codes, either software or policy, that state that the risk/reward of allowing certain types of behavior/interaction is too poor, and as a result, those things are prohibited, because, on balance of probability, we are better off without them.

Could a blind Captain defend the disk competently? It is *possible*. It just isn't *probable*. The most likely outcome is they get shot by someone they can't even see. Since the expected outcome is bad, the situation (bad captains) ought not to be allowed to occur. Hence this PR.

Again, we cannot ask for every possible case to be evaluated individually.

We have to have policies, both code-enforced and admin-enforced, which recognize that some things have, on balance of probability, average outcomes that are bad. And so, we shouldn't allow them.

To say that we should allow mute, blind, etc Captains is like saying we should allow non-antags to blow holes in the station. Yeah, in theory, it could work out, but in practice, most of the time, it doesn't work out at all. And we have to judge things on their average outcome, NOT require every case to be considered individually without any attempt to review the behavior overall.

**Comment by Tayyyyyyy** [comment]
I don't know if basing things on the average expected outcome is a good idea. That limits situations to a narrower band of experiences. I feel like IC means are more than enough to handle dysfunctional command members, which happens all the time with people without disabilities.

However, I do buy the argument that Nanotrasen would want to screen out certain disabilities. Sure, you could choose to live with a disability because of personal reasons but to a corporation that is basically an intergalactic empire, that would be a liability. Incredibly unfair, but that's what happens when you let corporations run loose.

**Comment by Kyep** [comment]
CHANGES:

Disabilities are now divided into two categories:
- Major disabilities are: deaf, blind.
- Minor disabilities are: mute, epileptic, tourettes, scrambled speech.

Jobs ability requirements are now:
- The Captain, and members of security, may not have either major or minor disabilities.
- The rest of the heads of staff may not have major disabilities, but they can have minor ones.
- Everyone (the above included) may have disabilities not listed in either category, such as obesity, shortsightedness, being wheelchair-bound, etc.

**Comment by DrunkDwarf** [comment]
This is a much more reasonable compromise :)

**Comment by Very-Soft** [comment]
Yes this is much more reasonable, I much prefer it.

**Comment by Jovaniph** [comment]
I can get behind this... Thumbs up for me.

**Comment by HugoLuman** [comment]
Though I do have to ask, seeing as most of the problematic ones are genetic: why not mutadone them?

Also, thank you for still allowing sec officers to challenge themselves with certain things. Particularly wheelchairs: while they do have major disadvantages, they also have some advantages that can make for a very robust playstyle when mastered.

**Comment by DesolateG** [comment]
@Kyep I would put Tourettes as major due to the seizures

**Comment by Kyep** [comment]
@DesolateG Personally, I would prefer it if all the minor disabilities were treated as major ones. Mute inhibits communication a lot. Tourettes / epilepsy stun you / interfere with movement, etc. I see no reason to allow these in ANY command or sec role.

That said, this PR isn't about what I personally want. This PR is about what most staff agree on. I did a poll of the staff team, and then modified the PR to match what the majority of the staff agreed on. There are only one or two cases where this PR does not follow staff consensus, and in those cases, I'm typically less restrictive than the staff vote would allow. E.g. the staff voted to prohibit HoS/officers/etc using wheelchairs, but my PR does not prohibit this.

**Comment by imsxz** [comment]
Mute is definitely a major disabity to command..

And if you guys wanna pull the "OH BUT IN REAL LIFE--" card, NT would just mutadone EVERY (including the ones who sit at the bar all day) employee with any disabilities upon confirmed diagnosis. Or just not hire them.

Sure a mute command member can still be good at their job, but they'll always lack practical communication OR just break immersion entirely, such as abusing megaphones (I think megaphones were fixed though) or the announcement system. ":C !taps on microphone to indicate there's nukies in aft starboard solars"

**Comment by imsxz** [comment]
Also using "mute people have PDA" as a reason against this PR isnt a very strong argument. PDA can be and usually is disabled for a good amount of time, for one reason or another. There could be the power outage event, an explosion near the HOP line, a mass PDA group invite, telecoms outage, etc. 

There isn't a backup if PDA servers go down *or* if you lose your PDA and or ability to use your hands. Normal comms has things such as station bounced radio, intercom, etc.

**Comment by DesolateG** [comment]
Pen and paper.

**Comment by Very-Soft** [comment]
#8299

Is also adding sign language, which I would think ought to still work with. Would be a cool alternative.

**Comment by davidchan13** [comment]
It's been almost 5 weeks and this hasn't been merged or closed?

Strongly in favor of key jobs having higher standards of physical capability. There is no argument in this thread I've seen that compels me as to why a person who can not see or hear be put in a command position. Definitely think Muteness should go back on that list of major disabilities, because a Command position requires them to act in emergency situations to inform their counterparts quickly and aptly of the situation and direct their personnel to safety. 

Given how NT is lore wise, they would force anyone in such a position to undergo operations to amend any such disabilities from genetic therapy to cybernetic augmentation such voice box synthesizers or vocal cord implants.

Also definitely feel wheelchair bound characters should be barred from security roles (with possible exceptions made for Brig Phys and Magistrate/IAAs, and perhaps the Detective.) They can't physically perform their job then why would they be given the job. The characters are thankfully few and far between but it should certainly be enforced in character creation that these roles are reserved for individuals who can perform all the tasks required of the position.

**Comment by Kyep** [comment]
@TullyBurnalot (+EVERYONE)

Based on headmin request, this PR has been altered.
It now ONLY affects HoS/Captain, BUT it blocks more disabilities for those roles, including things like scrambled speech, nearsightedness, etc.
Details in the PR description.

**Comment by Crazylemon64** [comment]
time to make a mistake

**Comment by HugoLuman** [comment]
I have only 2 comments:

1) Isn't nearsightedness not that big a deal with glasses?

2) It would be better for these roles to remove these disabilities from people, rather than being banned until they turn them off in their character prefs. That way they can still play with their disabilities if they wind up in another job at roundstart. And don't have to keep toggling them manually.

**Comment by SkullyRoberts** [comment]
AAAAAHHHHHH ABLEISM! *flees the thread*
Jk. but seriously, I don't like this. Even with current game mechanics it's pretty easy to get around most of the disabilities. Missing both arms is one thing, but being deaf or mute can be gotten around using a sign language language or PDA chatrooms. And nearsightedness isn't actually an issue, like, at all. you can combine glasses with any sort of glasses to make a prescription version. And nearsighted characters spawn with perscription versions of their spawn glasses anyway.

**Pull request merged**
