### PR TITLE
Add kitty ears to load out

### PR DESCRIPTION
**Pull request by Anasari**
As per title.

🆑 
add: Kitty ears to loadout option under hat for 1 point
/🆑

### CODE REVIEW

**Comment by taukausanake** [comment]
I'm going to upvote this because furries, but I KNOW it's going to be shot down almost right away

**Comment by Allfd** [comment]
> I'm going to upvote this because furries, but I KNOW it's going to be shot down almost right away

@taukausanake No.  This is literally how it starts.  Animu catgirls is the gateway drug.

**Comment by tigercat2000** [comment]
I suggested doing this myself.

I don't see any reason that these should be
A) Limited supply
B) Intentionally rare
C) Not available at roundstart

 Which are the only reasons we've denied loadout PRs in the past.

**Comment by Shadeykins** [comment]
We're one step closer to ascension.

And by ascension I mean Hell.

And by Hell I mean I'm OK with this.

**Comment by KasparoVy** [comment]
Makes no difference afaict aside from convenience since you can decon the vendors and get infinite ears. Should probably make it in.

**Comment by Ty-Omaha** [comment]
spacestation 13

**space** **station**

_not kitty station_ 

👀

**Comment by Citinited** [comment]
space station more like spay station

**Comment by Anasari** [comment]
Catgirl is not a gateway drug into furries.

No, catgirl is a gateway drug into human for furries.

You all have it wrong.

**Comment by KasparoVy** [comment]
Dare someone to put that controversial label on here

**Pull request merged**
