### PR TITLE
Removes some old unused code

### PR DESCRIPTION
**Pull request by alexkar598**
This code was commented out in pr #1438

Its been 2 years and it havent been touched.

### CODE REVIEW

**Comment by uraniummeltdown** [comment]
>not re-enabling it instead

**Comment by alexkar598** [comment]
seems pretty unbalanced,make a grenade with blackpowder smoke and small water potassium explosion and you have a maxcap

**Comment by taukausanake** [comment]
Exactly how maxcappy is it though? Would lowering the explosive potential of black powder solve anything?

**Comment by alexkar598** [comment]
Not really as its as explody as you can spread smoke/foam since if you spread black powder over the whole station and explode 1 tile,all the other tiles will explode too. Its making multiple small explosion so it essentially bypass the maxcap

**Comment by alexkar598** [comment]
Never mind,its actually only a 0,0,2,5 explosion,meaning its nowhere near the max cap. Its only laggy not unbalanced

**Comment by tigercat2000** [comment]
Commented code must *die* 🔪

**Pull request merged**
