### PR TITLE
New sprite IPC plushie

### PR DESCRIPTION
**Pull request by DogsParadise**
Ipc plushie

## What Does This PR Do
Changes the current sprite of the IPC plushie to a new one.

## Why It's Good For The Game
-Adds animation to sprite
-Previous sprite was a good shot but it had little depth in it was a little bland.

By this new sprite I try to stick to the old sprite's base format but change color schemes and
at a animation.

## Images of changes
Old sprite:

New Sprite:
Ipc plushie

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
not all heroes wear capes

**Comment by Fox-McCloud** [comment]
It wasn't the wrong sprite; Kyet objected to the sprite, but others approved of it.

Please don't pass this off as a "mistake" or that the other PR was "wrong".

This is a sprite change, plain and simple.

**Comment by DogsParadise** [comment]
> It wasn't the wrong sprite; Kyet objected to the sprite, but others approved of it.
> Please don't pass this off as a "mistake" or that the other PR was "wrong".
> This is a sprite change, plain and simple.

The sprite would have been updated, but Drakeven forgot about it.
Thus it was a mistake, maybe not by you nor the other headadmins.

**Comment by AffectedArc07** [comment]
image
Please include an old sprite, and please either add a changelog entry, or remove the :cl: blocks since it will likely bug the webhook

**Comment by DogsParadise** [comment]
I am gonna close this sprite request, even if the sprite might be of a better quality/ or might not be than the current one. 

Drakeven put a lot of effort into the current sprite and I do not wish to force my sprite into a pr they put so much effort in to. It wouldn't be right. If at some point It is requested to change the current sprite or something new would involve, I can open this pr again.

Till then, PR Closed.
Thanks for the info @Fox-McCloud

**Pull request closed without merging**
