### PR TITLE
Adds a Medkit for IPCs

### PR DESCRIPTION
**Pull request by AlAtEX**
NEW:
What does this PR do:
Adds a new type of medkit that has 90 cables, a welding tool , 100u of oil and a cyborg analyzer in it.
Two of them spawn on the robotics operating table at roundstart.
They can be ordered for 10 supply points for four, the same as basic and advanced medkits.

Images of sprite/map changes (IF APPLICABLE):
newmedkit

Changelog:
🆑 AlAtEx
add: Added a new medkit for IPCs
imageadd: added a purple medkit
/🆑

OLD

What does this PR do:
Adds 3 new types of boxes, with a emergency welder, 10 pieces of cable, and 100u of oil in an oil can and art for each, based off of shazbot194's box art added in #10177
A civilian box, engineering box (same but with different colour strips), and a mining box (same but with a red crowbar inside and different colour strips)

I have also re-enabled the survival_mining box which has a larger airtank than the default one and a red crowbar in it (if you get stuck outside) that change is located in the jobs/support.dm (if unwanted)

Images of sprite/map changes (IF APPLICABLE):

storage
modification

Changelog:
🆑 AlAtEx
add: Added a repair kit box to start with for IPC's
add: Re-added the crowbar and extended tank to miner's boxes
imageadd: added three new box images
/🆑

### CODE REVIEW

**Comment by Necaladun** [comment]
Absolutely against this. MAYBE as a special first-aid kit for IPCs that robotics has or cargo can order, but no one should be starting with a med kit.

**Comment by Necaladun** [comment]
Discussed this with a few admins, and the idea of adding "IPC medkits" to both cargo and robotics seems well supported. The general idea of robotics medkits I quite like! I'd go with a full stack of cables in that and a proper welding torch. Things like nanopaste I'd avoid, as they have uses in science, etc.

**Comment by variableundefined** [comment]
@AlAtEX 

We prefer box to be generic and in general, it is not good practice to add in special check for this. In the future if we have species-special item it should be added to their species file not to the one that assign them item.

If possible, you could change this PR to use the sprite instead for a single robotic first-aid kit that contains:
1 x welding tool
3 x full stack of cable coil
1 x oil can
Then add two to robotics, and add it as an option to order from cargo with the same cost as other first aid kit.

Also, please crop out your images of change to only include the sprite you are actually adding, not the entire file.

**Comment by granodd** [comment]
Starting with a robotic repair kit is "eh", and also a bit pointless. Most savvy IPCs will typically ditch their internals for box space and fill it with a welder and some cable (I personally keep the emergency injector on hand because I like to save people).

Adding special kits that you can order from cargo pre-filled sounds pretty neat though, and would help remove some of the tedium in filling up boxes like that.

**Comment by Necaladun** [comment]
Ansari does word things better than me right now, what he said

**Comment by shazbot194** [comment]
If you want, I already made a fully purple box meant for IPCs, in the same vain as O2 boxes, N2 boxes, and plasma boxes, the latter two potentially being added by spartan at a later time.

**Comment by Dinarzad** [comment]
@Necaladun   Question: What if the welder/cables were removed from the contents, but the oil kept?  Presently Oil is a bit of a scarcity on station, and where organics can do blood drives from the dozens of crew (Y'know... if they ever fuckin bother...)
IPCs tend to be somewhat more boned if robotics goes up, having only Cargo left to draw from.  What would be staff thoughts on less of a 'repair kit' and more just an emergency 25 units of oil?

**Comment by AlAtEX** [comment]
What does this PR do:
Adds a new type of medkit that has 90 cables, a welding tool , 100u of oil and a cyborg analyzer in it.
Two of them spawn on the robotics operating table at roundstart.
They can be ordered for 10 supply points for four, the same as basic and advanced medkits.

Images of sprite/map changes (IF APPLICABLE):
newmedkit

Changelog:
🆑 AlAtEx
add: Added a new medkit for IPCs
imageadd: added a purple medkit
/🆑

**Comment by Mitchs98** [comment]
@AlAtEX You'll want to edit the initial post of the PR with your changes to the PR instead of making a new post with it. If I'm not mistaken anyways.

**Comment by pinatacolada** [comment]
What happens if you make a medibot with the purple box?

**Comment by variableundefined** [comment]
I suppose you get the purple medibot then.

**Comment by shazbot194** [comment]
I think that should be double checked

**Comment by AlAtEX** [comment]
Has been tested, I did make sure to construct a medibot on my personal test server.

**Pull request merged**
