### PR TITLE
Removed #msay (+#asay?) gibberish

### PR DESCRIPTION
**Pull request by FunnyMan3595**
## What Does This PR Do
Corrected over-escaping that lead to HTML gibberish in #msay and, presumably, its admin equivalent..

## Why It's Good For The Game
`People shouldn&#39;t have to interpret &#34;useful&#34; HTML codes.`

## Testing
It compiled, but I don't have a setup that lets me test it.

## Changelog
NPFC

### CODE REVIEW

**Review by AffectedArc07 — APPROVED** [review]

**Comment by Danchi299** [comment]
does that means that saying `<hello>` in msay will return `hello` or `<hello>` in discord?

**Comment by FunnyMan3595** [comment]
Right now, if you say `<hello>` in msay, it'll show up as `<hello>` to others on the server, and `&lt;hello&gt;` to folks in Discord. This corrects that to also say `<hello>` in Discord.

**Comment by Danchi299** [comment]
which means I can finally ping people in discord from MSay using `<@ID>`, time to ~~ab~~use this fix

**Comment by Coolrune206** [comment]
I've noticed this gibberish also pops up in the forced whisper that comes along with oxygen loss - will this fix that too?

**Comment by FunnyMan3595** [comment]
> I've noticed this gibberish also pops up in the forced whisper that comes along with oxygen loss - will this fix that too?

No, but #24876 might. I didn't specifically handle that, but it could easily have gotten caught in some of the cleanup I did.

**Review by Burzah — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]
Should be fine, cant HTML inject in discord (or atleast I hope not given its webshit)

**Review by Contrabang — APPROVED** [review]
LGMT

**Pull request merged**
