### PR TITLE
Remasters the Clown-Mime Battle Ruin

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
The old clown-mime ruin has been completely remapped. Instead of two ships that randomly are crashed into an asteroid, they it is now the site of two simultaneous raids from militant mimes and clowns upon an unfortunate cargo vessel carrying a shipment of tranquilite and bananium among its wares.

The core reward of 30 tranquilite and bananium, and one honk grenade remains unchanged.  There are no longer any mineral deposits to mine, however the contents of the stricken vessel make up for this:

1 loot spawner. 2 toolboxes.
An electrical and mechanical toolbox.
A crate stocked with basic mining supplies.
A crate stocked with various toys.
A crate stocked with electrical supplies.
A crate stocked with flares and glowsticks.
A crate stocked with 2 bottles of nothing.
A crate stocked with banana juice.
A crate stocked with a full set of baseball gear.
The HONK rifle of the clown commander.
Clown and mime flags.
Clown and mime helmets.

The paper containing a reference to Clown Planet has been deleted, by order of the Lore Team.

## Why It's Good For The Game
This ruin has has non-diverse loot, and is silly and random.

It is now silly and whimsical, and has more varied and unique loot. The scale of the epic struggle between the opposing forces is better communicated with all the damage to the vessel.

## Images of changes
SDMM
image

## Testing
Visited the ruin. Made sure no weird titanium wall angles happened. Checked that everything was in the right place.

<hr>

### Declaration
- [x] I confirm that I either do not require [pre-approval](/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

## Changelog
:cl:
tweak: Remapped the clown-mime battle ruin. It is now set on a besieged cargo vessel rather than an asteroid crash site.
add: There is now a HONK rifle to be found at the ruin.
add: Various other minor loot items have been added to the ruin.
del: Removed a paper that mentions Clown Planet.
/:cl:

### CODE REVIEW

**Comment by Screampuff** [comment]
Way better environmental storytelling.

**Review by 1080pCat — APPROVED** [review]
Looks honk to me.

**Comment by Fordoxia** [comment]
> What does the HONK rifle do exactly? Never heard or seen it before.

It's a weapon currently only spawned along with clown ERTs. It fires snap pops.

**Comment by 1080pCat** [comment]
> > What does the HONK rifle do exactly? Never heard or seen it before.
> 
> It's a weapon currently only spawned along with clown ERTs (where it is randomly chosen as an alternative to the pie cannon). It fires snap pops.

i believe it can be obtained by letters too.

**Comment by Fordoxia** [comment]
> > > What does the HONK rifle do exactly? Never heard or seen it before.
> > 
> > 
> > It's a weapon currently only spawned along with clown ERTs (where it is randomly chosen as an alternative to the pie cannon). It fires snap pops.
> 
> i believe it can be obtained by letters too.

Alas it cannot. `/obj/item/gun/energy/clown` only appears in the clown ERT outfit.

**Review by warriorstar-orion — APPROVED** [review]
Please merge master and replace the maint loot spawner, as CI won't catch the change.

**Comment by Fordoxia** [comment]
> Please merge master and replace the maint loot spawner, as CI won't catch the change.

Updated and replaced.

**Review by Burzah — APPROVED** [review]

**Pull request merged**
