### PR TITLE
Updates the ERT carbine and sidearm (version 2)

### PR DESCRIPTION
**Pull request by Stokes52**
This is an update/improvement over my first attempt (https://github.com/ParadiseSS13/Paradise/pull/15890)
See previous work with security lasers here (https://github.com/ParadiseSS13/Paradise/pull/15871)

## What Does This PR Do
Updates the ERT carbine and sidearm to have a clean sprite and matching visual style.
New ammo, weapon, magazine, and in-hand sprites and animations
New description on the carbine

## Why It's Good For The Game
The ERT carbine sprite badly needed a rework, with the creator themselves admitting so.  The PDW update is mild, only so that the style is maintained across both weapons.

The ERT carbine is a unique weapon since it is classed as a projectile weapon and uses cartridges yet it fires lasers. I hope this new design captures the spirit of a conventional weapon with a laser twist.

## Images of changes
**< < < CURRENT VERSION > > >**
V3
animation_v3
magazine_v3

**< < < OLD IMAGES BELOW HERE. OUT OF DATE > > >**
Comparison:
ERT_comparison_v2

Animations, new ammo, magazine, etc.  Includes empty, full, and multiple partial full states.
ERT_guns_v2

Descriptions
ERT_descriptions_v2 copy

In hands sprites
ERT_hands_v2

In action
ERT_shooting_v2

## Changelog
:cl:
add: New ERT carbine sprites
add: New description and code to make the ammo animation updates work
tweak: slightly changed the PDW sprite to match
/:cl:

### CODE REVIEW

**Comment by SteelSlayer** [comment]
While I'm a fan of the guns, I think the animation on the cartridges and magazines are a little too... busy, I suppose.

**Comment by LightFire53** [comment]
> While I'm a fan of the guns, I think the animation on the cartridges and magazines are a little too... busy, I suppose.

They seem to be really slow to spin, and there's the red muzzle flash that doesn't match the pace of the projectile so it looks rather off and stick out like a sore thumb.

**Comment by Stokes52** [comment]
> > While I'm a fan of the guns, I think the animation on the cartridges and magazines are a little too... busy, I suppose.
> 
> They seem to be really slow to spin, and there's the red muzzle flash that doesn't match the pace of the projectile so it looks rather off and stick out like a sore thumb.

Yeah the muzzle flash is out of scope for this PR. I didn't make it, just using what's there.

Regarding the animation, part of it is due to the gif loop and low fps, it looks better in game,

**Comment by E-MonaRhg** [comment]
Okay in my opinion this one looks better than the previous attempt BUT once again I guess I got some points :
1. The carbine _might_ be a bit too thin now, might look better with a sight or something on it to make it a big bigger.
2. It would be neat if the green light on the loaded carbine would change color depending if it is set to semi-auto or burst.
3. And this point is more of a request, could you make in-hand sprites for the PDW9? It uses the normal pistol one now.

But otherwise, looks great.

**Comment by Rurik123** [comment]
Looks amazing, sprite wise. Definitely prefer this one. 

> The carbine might be a bit too thin now, might look better with a sight or something on it to make it a bit bigger.

Personally I prefer the thinner/more sleek look. Looks like an actual rifle a future corp would use. That might just be me though

**Comment by FlattestGuitar** [comment]
They look very cool, but I have a complaint here. The guns clearly look like they're part of the same series or some such - they share a lot of visual characteristics, but they are clearly two completely different guns with different features. 

It makes no sense that we'd have two guns that share a ton visually, but behave completely differently. This seems to me like a big issue.

**Comment by Stokes52** [comment]
> They look very cool, but I have a complaint here. The guns clearly look like they're part of the same series or some such - they share a lot of visual characteristics, but they are clearly two completely different guns with different features.
> 
> It makes no sense that we'd have two guns that share a ton visually, but behave completely differently. This seems to me like a big issue.
@FlattestGuitar 

This is an intentional decision to make them part of the same series even though they function differently.  In the real world it's not uncommon for gun manufacturers to take a single design and wildly modify it for different configurations and calibers.  For example, Sig Sauer produces the MPX submachine gun, but they also use the basic design features of the MPX to make the MCX, which looks very similar and reuses certain parts but comes in a completely different caliber (9mm vs 7.62×35mm) and comes in rifle, carbine, and even pistol configurations.  Another Sig Sauer weapon, the Sig P229 can easily be converted to fire multiple calibers with just the switching out of a few parts. Not every gun can do this, but some guns are designed specifically to be modular enough to take on different roles, calibers, length's, etc.

In our world, we don't have laser weapons, so its hard to compare how easily interchangeable a laser vs cartridge weapon would be, but the exterior is the easiest part to make the same.  It's the guts/internals that matter and those are not visible.

Once again, in the real world, we don't have lasers, but we have weapons with different calibers and different roles yet we do see this pattern of repeating design elements and parts to make similar weapons in different classes or even modular multi-role weapons that can be drastically changed by swapping out a few parts.  This is especially common on more modern firearms and I don't see why a company in the advanced future wouldn't use the same philosophy.

That's essentially what I want this weapon to be, a weapon made by a company that values design efficiency and has created multiple models of weapon using similar parts and design elements even when the resulting models fire different ammunition or serve different functions.

Back to SS13:
To reflect this in the lore, I have some head canon about why the weapons are named they way they are.

The manufacturer of these weapons specializes in military grade weapons.  Like most real world gun manufacturers today, they reuse proven design.  In order to organize their weapons effectively they use a simple naming convention to organize their elements based on role and other characteristics

Naming scheme = **AAA-123**
AAA =Role/Specialty
1= Series
1 number = pistol configuration
2 numbers = carbine configuration
3 numbers = rifle configuration

PDW-9 - Personal defense weapon, series 9, pistol configuration

CL-90 - Cartridge Laser, series 9, carbine configuration

This doesn't have to be written into the lore, but it was being considered as I designed it. How can I make two weapons with similar design elements, but that fulfil different roles? Well, there's a lot of real world inspiration to draw from where companies do exactly that.

**Comment by FlattestGuitar** [comment]
You're going out of your way to make two clearly different guns look very similar. And that's for the sake of realism? "Gun lore"? Come on.

This will not be intuitive to people who haven't played as an ERT member before.

Just make a few small color and body changes to one of the guns and you're good, no need to compromise your vision.

**Comment by Stokes52** [comment]
> You're going out of your way to make two clearly different guns look very similar. And that's for the sake of realism? "Gun lore"? Come on.

Yes, that's what I'm trying to do. In addition to making a better sprite, I want to make something that fits aesthetically with the existing equipment and is believable.  I disagree that this adds confusion, the description of the weapons makes it clear what they do. Laser carbine for killing. "Taser" for tasing.

However I appreciate the feedback and am very open to hearing other opinions as well, feel free to comment or use those thumb up/downs to share your opinions, dear readers.  It's not possible to make a sprite that pleases everyone but we can try to make something that many like.

**Comment by DogsParadise** [comment]
Here is my notes, quick and easy:

**Animations:**
-The animations feel too much out there, animations imo are something that just add that little bit of extra. But it shouldn't be distracting, which it currently is.
-I really dislike the red flash when shooting especially.

**Looks:**
They are a bit too similar, I am gonna side with what Flattest said here.
I think you should make a few adjustments, to make one stand out from the other.
I can see myself accidentally grabbing one, meaning to grab the other when in tense moments.


**Shading**
The color you use for shading is inconsistent, highlights on 1 gun are way brighter than the others.

If you wish me to go more in depth, shoot me a dm.

**Comment by Stokes52** [comment]
An attempt to make them less similar.  Upvote if like, downvote if no.

V3

**Comment by DogsParadise** [comment]
I like the modified version

**Comment by Stokes52** [comment]
Updated PR with:
- Less busy weapon animations:
animation_v3
magazine_v3

- Easier to tell the ERT carbine and pistol apart
V3

**Review by S34NW — APPROVED** [review]

**Comment by Stokes52** [comment]
Fixed merge conflicts. Should be ready to go.

**Comment by lectronyx** [comment]
> They look very cool, but I have a complaint here. The guns clearly look like they're part of the same series or some such - they share a lot of visual characteristics, but they are clearly two completely different guns with different features.
> 
> It makes no sense that we'd have two guns that share a ton visually, but behave completely differently. This seems to me like a big issue.
> 
> I'd at least recolor the blue embellishment and drop the connected grip-stock on one of these, so they are more different from each other.

To be fair, there's a L O T of weapons that resemble the AK-47, despite having incredibly different purposes. Compare, for instance, the AK-47 assault rifle to the RKP light machine gun, PP-19 Bizon SMG, Saiga-12 Shotgun, AKS-74U compact carbine (That thing's less than 2ft long with the stock folded, which I find super weird and worth noting), APS underwater rifle, etc.

I, for one, would say the AK-47 is probably not used like a shotgun, underwater rifle, or sniper rifle at all... But they still look similar and use similar parts. And that's just with real-world equipment. Who knows what the limits could even be in a setting 500 years into the future, using laser weaponry! Besides, the WT-550 Security Autorifle and the Laser Gun aren't really similar weapons... but we made them look alike.

**Comment by Stokes52** [comment]
Closing in favor of new version (less merge conflict issues!): https://github.com/ParadiseSS13/Paradise/pull/16105

**Pull request closed without merging**
