### PR TITLE
Bug Fixes

### LINKED ISSUE #9607: Duct Tape, Package Wrapper, Wrapping Paper missing proper stack description
**Problem Description**:
Certain items have odd descriptions when in a stack, such as duct tape, package wrapper, and wrapping paper.

**What did you expect to happen**: 
When inspected, the item to say, "There are XX [objects] in the stack," such as "There are 25 sheets in the stack." 

**What happened instead**:
When inspected, the items say, "There are XX s in the stack," such as "There are 25 s in the stack."

**Why is this bad/What are the consequences:**
It's not particularly important, just annoying and inconsistent.

**Steps to reproduce the problem**:
1. Find a roll of duct tape, package wrapper, or wrapping paper.
2. Examine.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Those three I know for certain have this issue, but I'm not sure if there are more.
2018_09_24_11_55_32_paradise_station_13

### PR DESCRIPTION
**Pull request by dapocalypse**
Fixes #9607, makes the s display the singular name.

### CODE REVIEW

**Comment by dapocalypse** [comment]
Also will this count towards the three bug fixes needed to contribute a feature for the feature freeze.

**Comment by Crazylemon64** [comment]
I am afraid this will not, due to this being a trivial grammar fix in 3 locations. If you could verify this was all the stack grammar problems in the codebase, then I would count this towards the freeze.

**Comment by dapocalypse** [comment]
Alright so I scour through all the things and look for things without singular_name?

**Comment by dapocalypse** [comment]
Alien Claws, enruranium, and Weed Extract, is there a special reason they don't have singular_name or should I fix them.

**Comment by Crazylemon64** [comment]
Wonderful! Thank you for ripping out the root of the problem.

**Pull request merged**
