### PR TITLE
Metastation: Pod Bays

### PR DESCRIPTION
**Pull request by Aurorablade**
Please note, First map edit, some shots were taken before i fixed some stupid stuff i missed. I swear i map merged this. I more then likely fucked up something.
Don't kill me.
mecba
scrnshot1
scrnshot2

:cl: Fethas
- rscadd: Security podbay. moved fireing range one tile down
- rscadd: Public use bay, sourthern part of Arrivals
- tweak: expanded Mechnic pod bays
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
it's beautiful, i love it <3

might want to make the public bay have a 4x door though

**Comment by Aurorablade** [comment]
the tiles aren;t even and it would look off..i was trying to be fancy....>.>

**Comment by tigercat2000** [comment]
@Aurorablade couldn't you add it right in the center? like

wall wall poddoor4poddoor4poddoor4poddoor4 wall wall

**Comment by Aurorablade** [comment]
will try to check in a bit

**Comment by FalseIncarnate** [comment]
I think my biggest complaint is that the mechanic is stuck off a maint tunnel and thus feels like it has no solid connection to the station. People will have to go down a sketchy hall or send a message via PDA / radio asking for a pod to be built, rather than the nice well-lit hall we have for him on Cyberiad.

:+1: despite that though

**Comment by KasparoVy** [comment]
Mechanic traitor heaven

**Comment by TullyBurnalot** [comment]
:+1: 

Though moving the Mechanic Pod Bay to Nowheresville, Maintenance, maybe be a bit harder on the Mechanic. Perhaps try to have it a bit closer to Engineering?

**Comment by tigercat2000** [comment]
@TullyBurnalot it was already in bumfuck nowhere, aurora just expanded it; Engineering has literally no empty points that are near space.

**Comment by Aurorablade** [comment]
it does buts it near atmos and i am not sure if its a much better spot. somone needs to look at the meta map and see if theres any suggestions.

**Comment by TullyBurnalot** [comment]
@tigercat2000 Well... not exactly. The Pod Bay was out of the way, but that maintenance corridor and hallway were still regularly used. It wasn't really out in the boonies, just kinda scooched over, but I get yer point.

**Comment by Tastyfish** [comment]
Loading up the PR's map, I would the main issue with the current mechanic location is that it's _too_ far into engineering. You literally have to go through the engine room and gravity generator foyer to get to it.

**Comment by Tastyfish** [comment]
Also, a lot of the switches/fire alarms/etc are on the wall turf or an adjacent wall turf. They need to be on the floor directly in front of them or you'll be able to see them on both side of the wall and/or players will have difficulty interacting with them as expected.

**Comment by Aurorablade** [comment]
I need a list of them and someone to hel find a new mech bay spot for when I get off work

**Comment by Aurorablade** [comment]
I need a list of them and someone to hel find a new mech bay spot for when I get off work

**Comment by Tastyfish** [comment]
Maybe the engineering escape pod and AI tube could be rearranged to put it south of the singularity. That would put it at near the foyer. It's literally the only other location I can reasonably see.

**Comment by Aurorablade** [comment]
i got i got the mechnic bay and an escape pod swapped. But i am having issues with the pod door controls not controling the door in the mechnic bay and the public use one. Also an odd atmos issue in the sec pod bay...maybe public use bay. Anyone help me figure it out?

**Comment by Tastyfish** [comment]
The `id_tag` of the podbay doors aren't set, so the buttons aren't linked to them. Also, the public use door button is still misplaced. Will return when I look at the atmos.

**Comment by Tastyfish** [comment]
Actually, can you describe the problem you were experiencing with the atmos?

**Comment by Aurorablade** [comment]
@Tastyfish also the floor is icy like with a hull breach

**Comment by Tastyfish** [comment]
After looking at it again, all of the security pod bay's walls are false walls for some reason.

**Comment by Fox-McCloud** [comment]
Any further thoughts or input on this? @TheDZD @Tastyfish

**Comment by TheDZD** [comment]
Makes Metastation ~~great again~~ more usable. :+1:

**Pull request merged**
