### PR TITLE
Dispose chems directly from chemdispenser

### PR DESCRIPTION
**Pull request by Artorp**
As requested: https://github.com/ParadiseSS13/Paradise/issues/758

Makes it possible to dispose chemicals directly from the chem dispenser

untitled

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Can you do this with the bartender's machines too?

**Comment by Artorp** [comment]
Sure can, they all use the same code.

**Comment by Spacemanspark** [comment]
Perfect!
:+1: x :100:

**Comment by tigercat2000** [comment]
:+1:

**Comment by Iamgoofball** [comment]
:+1:

**Comment by CrAzYPiLoT-SS13** [comment]
Why don't you make it so that the chems go back to the machines 'Energy'. Just remember that 10u is 1u energy.

**Comment by Fox-McCloud** [comment]
big :+1: 

Thanks so much for this; this wasn't as necessary when most medical chems were composed of 3 reagents---but with our current system, it's a huge pain to switch around all the time---plus, this give bartender a way to fix any "oops" scenarios.

**Comment by Artorp** [comment]
@CrAzYPiLoT-SS13
Thought about it, while it's a neat idea I think it'd sort of encourage disposing using the dispenser instead of the chem master. It'd also make it possible to move energy between multiple dispensers which I just don't think is needed and is outside the scope of this PR. Wouldn't mind seeing it added, but it is not something I bothered to add at the time.

**Pull request merged**
