### PR TITLE
Ports Changelog System from /tg/station

### PR DESCRIPTION
**Pull request by TheDZD**
Also includes tgstation/-tg-station#14348, as I plan to add automatic changelogging via the use of :cl: inside of PRs. Big thanks to @MrStonedOne for the PR announcer/changelog generator webhook script, and for answering my questions. Credit to @N3X15 for creating this changelog system in the first place.

DNM as I still need to make sure a few other things work first.
Now also ports Baystation12/Baystation12#10096, which should make Travis CI builds faster as well.

Sample image:
changelog

### CODE REVIEW

**Comment by TheDZD** [comment]
Goddamit Travis.

**Comment by tigercat2000** [comment]
@TheDZD You need to generate a new md5sum for our changelog

**Comment by TheDZD** [comment]
@tigercat2000 Oddly enough, I did.

**Comment by TheDZD** [comment]
Turns out it was a minor issue with EOL operator conversion, thanks for pointing this out @MrStonedOne.

**Comment by TheDZD** [comment]
Updated and squashed.

**Comment by Crazylemon64** [comment]
:cl: 
* Earthdivine gets a break
/:cl:

**Pull request merged**
