### PR TITLE
Lets Borgs and Drones Flip

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Allows borgs (and drones) to flip.

Obeys the standard cooldown.

Obviously the most utmost priority PR ever.

other:
- removes unused color var for toolboxes.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Too many labels.
:+1:

**Comment by M3hillus** [comment]
Missing the WTF label, IMO

**Comment by FreeStylaLT** [comment]
no controversial label?

**Comment by TheDZD** [comment]
Needed more labels.
:+1:

**Comment by KasparoVy** [comment]
NEEDMORELABELS.lbl

YEESSSS ahahaha, going to be hilarious.

**Comment by Spacemanspark** [comment]
Oh shit wait add this function to pAI's too.

**Comment by Iamgoofball** [comment]
*flip

**Comment by Robertha89** [comment]
Mice used to be able to flip tables for a while when it was implemented.

**Comment by Markolie** [comment]
Missed some there.

**Comment by Fox-McCloud** [comment]
What the flipping hell guys?

**Comment by Aurorablade** [comment]
@Fox-McCloud should i add this to my pai Stuff while i wait for sprites?

**Comment by TheDZD** [comment]
Changing the robot emotes to work for AIs and pAIs would be [incredibly simple](tgstation/-tg-station/pull/5697), although that might be outside of the scope of both this PR, and the pAI update PR.

**Comment by tigercat2000** [comment]
@TheDZD *flip'ing AI's. THE HORROR.

**Pull request merged**
