### PR TITLE
Fixes a couple sprite issues from my previous work

### PR DESCRIPTION
**Pull request by Ar3nn**
I was still working on the sprites and it got merged anyway, so here's the new stuff. Should be okay now.

robos

### CODE REVIEW

**Comment by Ar3nn** [comment]
thats a lot of garbage

**Comment by monster860** [comment]
Where did that garrbbbaaaggge come frome?

**Comment by KasparoVy** [comment]
git rebase -i HEAD~whatever and try to squash all that

**Comment by Fox-McCloud** [comment]
Those do look a lot better; sorry about merging your other PR early.

**Comment by Ar3nn** [comment]
Its k I should've been updating it all along but it just seemed like a lot of work just to do it again and again, and then it took me a while to get everything straight and by that time, you'd merged it :P

**Pull request merged**
