### PR TITLE
Paradise's soul removal part two of many: security jumpsuits

### PR DESCRIPTION
**Pull request by ElorgRHG**
## What Does This PR Do

Ports quite a lof of (older) security resprites from TG, standardises the palette, refreshes the look a bit.

This is part one of lets say 3 to maybe 4 for security resprites, jumpsuits, suits and vests, headgear.

Waiting for https://github.com/ParadiseSS13/Paradise/pull/19058 to get merged first, that's why its open in draft.

**And also to gauge the opinions of the community a bit before making species variants and then this PR getting closed, wasting everyone's time.**

## Why It's Good For The Game

With the captain resprite being merged, my crusade has been called a righteous one, and well, time to further it.

I can't really say much more about why this is good for the game, its new sprites, that's always good... usually.

## Images of changes

Just a small comparison to let you gauge the quality of our current security jumpsuits just from the default security red.
They're showing their age for sure, the old ones that is, and well, let's kill that bit of history off, eh?

<details>

image

</details>

image

## Testing

Went to the secdrobe, HoS's garment bag and warden's locker
Put on all the clothes
No missing sprites.

## Changelog
:cl:ElorgRHG, Christasmurf
imageadd: Resprited security jumpsuits.
/:cl:

### CODE REVIEW

**Comment by Bm0n** [comment]
not sure about the corporate skirts, kinda looks like shorts tbh. should keep the same style as the normal secoff skirt.

**Comment by ElorgRHG** [comment]
> not sure about the corporate skirts, kinda looks like shorts tbh. should keep the same style as the normal secoff skirt.

Yeah the more I looked at them the worse they looked, so this is how they look now :)
 (I'm not updating the preview in the actual PR desc, these mockups are painful to arrange 💀 )

image

Adding the chest badge was a pain to get to look good on the skirts, due to certian... protrusions, so I'm hoping these will do fine.

**Comment by ElorgRHG** [comment]
Grey and drask variants finished, security dress skirt adjusted courtesy of @Christasmurf, prerequisite PR merged, this PR is ready.

**Review by S34NW — COMMENTED** [review]
seems mostly okay, a bit annoying that we have two naming schemes, `sec_thing` and `security_thing`, but that's slight scope creep

**Review by S34NW — APPROVED** [review]

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
