### PR TITLE
EMERGENCY PASTE REMOVAL

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Copy-paste struck again!

### CODE REVIEW

**Comment by TheDZD** [comment]
Whoops, wrong button.

**Comment by KasparoVy** [comment]
fucking christ

rest in copypasta
kill me rn

**Comment by TheDZD** [comment]
[1 minute merge](http://youtu.be/X7DnyP4dqsw)

**Comment by ZomgPonies** [comment]
@KasparoVy TRIPLE CHECK AND TEST ALL SQL CHANGES. If this had corrupted our most precious SQL data, I would've been more than a little pissed. Keep that in mind for next time.

**Comment by tigercat2000** [comment]
@ZomgPonies I'd be pissed if you don't back up the SQL database before major changes :cat:

**Comment by Crazylemon64** [comment]
SELECT isn't a mutative operation, is it? It, however, WOULD have caused character variables to be messed up on load, everything from eye color onwards... And of course, this would have caused problems when you attempted to SAVE this data immediately afterwards...

**Comment by Tastyfish** [comment]
Yes, in fact it just crashed the character screen thankfully so nobody *could* save.

**Comment by tigercat2000** [comment]
@Crazylemon64 I'm not sure what you mean by mutative operation
but as far as I know, the query data will return in whatever order the columns are listed in the SELECT statement
so
`SELECT jango, jumbo FROM table`
would return
`query[1] = data from jango; query[2] = data from jumbo`
and
`SELECT jumbo, jango FROM table`
would return
`query[1] = data from jumbo; query[2] = data from jango`

**Comment by Crazylemon64** [comment]
@tigercat2000 I think I picked that up from the dogma of Functional Programming I think or something like that, which labels certain operations as "mutative" if they change the state of the object, or cause some persistent effect after being called, if I'm remembering right

**Comment by Tastyfish** [comment]
Yes, @Crazylemon64 is referring to operations that cause side effects in the database.

**Pull request merged**
