### PR TITLE
Mini ballistic rebalance

### PR DESCRIPTION
**Pull request by Anasari**
Currently, the optimal ammo ballistic ammo to use for almost all situation is always buckshot. This lead to buckshot being almost always optimal as WT-550 and slug are by comparison, relatively weak.

This PR sought to remedy some of that problem by adjusting their relative power to eachother.

Feedbacks are highly welcome.

List of changes:
Toxin bullet: 15 -> 20 damage
Buckshot & Weak pellet: Armor penetration of -10 (Results in -25% damage against syndicate elite hardsuit)
Buckshot: Spread changed to 40 degree instead of 25. Result in a 1 - 2 bullet hitting a single tile at maximum screen length.
Slug: New type of projectile created. +10 penetration. Against syndie hardsuit, this result in 24 -> 30 damage from before. 

🆑
tweak: Buckshot & Improvised shell AP ability reduced. Slug AP increased. Toxin bullet damage increased to 20. 
/🆑

### CODE REVIEW

**Comment by alexkar598** [comment]
And an other nerf

**Comment by Shadeykins** [comment]
@alexkar598 Except for the fact that it buffs the WT-550 which is cheaper to manufacture/obtain, buffs toxin rounds (which are painful to be hit by), and buffs shotgun slugs (which are a default ammo type).

**Comment by imsxz** [comment]
Make sure to add a toggle between single and burst fire to the auto rifle.

Other than that, I agree with this PR because it's not making buckshot useless, while it makes slugs and the WT much more viable.

Glad buckshot will no longer be the go-to free win against all antags :ok_hand: .

As for toxin ammo, glad it's finally getting some love but it may just be too difficult to balance properly. Some species, simple mobs, and cyborgs all ignore the effects of the toxin damage, and while most won't have anti toxins on hand, it won't leave any real lasting damage if they don't die. I can see where it would be useful, as toxin damage completely ignores armor, but there may be a bit too many targets that flat out ignore toxin damage to make it useful, regardless of buffs (unless it's buffed to the point of godhood or something).

:b:retty good :b:R, :b:uckshot being nerfed but still useful is great to see.

**Comment by Anasari** [comment]
From my test, toxin damage don't bypass armour completely at all. Testing against a HoS in the arena results in 11.5 damage, while a syndie nuke suit cut it down to 7.5. This is with 15 base damage value.

I'll add in a toggle tommorow.

**Comment by imsxz** [comment]
Oh that's kinda silly. Perhaps make it do 5 brute instead of toxin, then just make it adjust tox loss by 20 or so on impact. That way it won't be negated by armor

**Comment by FalseIncarnate** [comment]
@Anasari that's due to the toxin bullet being resisted by bullet armor. You could handle this a few ways such as making it a nodamage bullet and then applying the toxin damage directly on hit, giving it armor penetration, or leaving it as-is until someone codes a way to make projectiles not be affected by any armor type (seriously, why is this not a thing already?) and then change it to be whatever is needed to be unaffected.

**Comment by Squirgenheimer** [comment]
In case anyone is wondering, this would be the new damage of buckshot _given all 6 pellets hit the chest_.

| Armor  | Old Damage | New Damage |
| ------------- | ------------- | ------------- |
| None | 75  | 67.5  |
| Elite  | 30  | 22.5 |
| Blood red | 37.5 | 30 |
| Sec hardsuit | 63.75 | 56.25 |
| Sec armor | 63.75 | 56.25 |
| Armored coat | 52.5 | 45 |
| Caps carapace | 45 | 37.5 |
| Bulletproof vest | 15 | 7.5 |

In this hypothetical will take one more shot to put someone into crit for the blood red hardsuit, elite hardsuit, and armored coat.  

If I were doing this myself I'd probably take an additional flat 1.5 off of the pellet damage, but then again, this makes the wearing the bulletproof vest&helmet stronger.

**Comment by Ssirius** [comment]
👍 Any buckshot nerf is a good thing, ammo that requires no aiming skill to use should not also be the best ammo available for the gun.

**Comment by Twinmold93** [comment]
This still makes very close buckshot fires very deadly, while lowering distance firing to weak, for being a nerd, it's a very good and realistic need, since now single fire ranged should begin out performing buckshot at distance. Good work.

**Comment by Twinmold93** [comment]
A nerf, rather.

**Comment by alexkar598** [comment]
Auto correct striked you as well?

On 2017-10-13, at 5:15 PM, "Twinmold93" <notifications@github.com<mailto:notifications@github.com>> wrote:


A nerf, rather.

**Comment by Fox-McCloud** [comment]
Buffing the sec rifle? Hell no.

**Comment by taukausanake** [comment]
@Fox-McCloud could you explain why that would be a bad thing? I didn't even know sec HAD a bullet rifle, unless you meant some laser weapon

**Comment by Anasari** [comment]
On a second thought, I do agree with Fox's notion. The sec rifle carry 20 shots of 20 brute, compared to the energy gun's 10 / 12 lethal shot of 20 burn. And in addition, its ammo are very easy to carry, at only tiny size and 20 ammo in size. Buffing its burst size would probably lead to it becoming the new buckshot.

**Comment by Varghh** [comment]
Even when I agree the auto rifle is in a good state, I think the toxic ammo should receive is buff to stop being trash tier ammo. Not sure I would make it 20 to damage but 15 tox - 5 brute damage sounds a bit more real, plus adding a bit of armor pen (+5) so it's good for low armored criminal scum or heavy brute burn regen targets

**Comment by Anasari** [comment]
Bullet armour still applies to toxin damage from what I know. It has its use, as toxin damage are way harder to instantly heal compared to brute / burn (Which has instant touch patch available for them). I think it is better to not buff it too hard and just wait and see.

**Comment by taukausanake** [comment]
What happened?

**Comment by Squirgenheimer** [comment]
I'm also curious.

**Pull request closed without merging**
