### PR TITLE
Removes the Chaplain's soul stone 🗿

### PR DESCRIPTION
**Pull request by FlattestGuitar**
The thing is crazy powerful, most newcomers have no idea how to use it, it generates needless salt and has a ton of potential for abuse.

I thought about making it some sort of an opt-in for ghosts, but I doubt many people would willingly subject themselves to the procedure instead of, you know, being revived.

:cl: FlattestGuitar
rscdel: Removes the soulstone from Chap's office
/:cl:

Discuss.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Fuck yes please.

**Comment by jughu** [comment]
Add it as a chaplain only traitor item i guess for 5 tc comsidering you dont have a shell

**Comment by tigercat2000** [comment]
> The thing is crazy powerful

Could you please describe how a soulstone that only works once is "crazy powerful"?

**Comment by KasparoVy** [comment]
One person ded please nerf?

**Comment by jughu** [comment]
@tigercat2000 it isnt powerfull at all but said soulstone can absorb ANY shade including the cultist ones and releasing them make them their aves which against isnt really a issue since if cult uses normal shades they are on a bad path anyways

**Comment by jughu** [comment]
I guess this is more the case of i got permanently removed from the round because the fucking chaplain

**Comment by FlattestGuitar** [comment]
@tigercat2000 
>kill target as tator
>click target
>ghost spawns
>click ghost ten times
>no evidence murder gg

**Comment by jughu** [comment]
@FlattestGuitar 
>buy 375. Revolver shoot person
>put body in cremator
>grab the mob clean it up
>no murder gg

**Comment by jughu** [comment]
Besides doesnt soul shards leave skulls remains behind that cant be cleaned

**Comment by FlattestGuitar** [comment]
That still requires you to actually drag the corpse to your office.

**Comment by Aracino** [comment]
Miners can get a shell from the asteroid. It happened one wiz round, an artificer makes more soul stones and shells. There can be an infininte army of cult constructs via the chaplain's soul stone.

**Comment by Kyep** [comment]
Soulstones are a cult/wizard object, not something a Chaplain should have.
They give you a permanent shade helper. which is too strong.
Finally, they're abusable, they encourage validhunting, and they cause ahelps.
We're better off if Chaplains don't have them.

**Comment by Fox-McCloud** [comment]
Leave it in.

Hardly that strong, in the global context of things. Saying this allows for unpinnable murders is really a moot point when the chaplain has access to the crematorium.

If anything, this leaves behind [i]more[/i] evidence than that, as the soul stone leaves behind an unremovable skeleton decal.

He gets to use this once and he gets a follower that can't even warn him of danger.

Miners can also get soulstones (or are supposed to be able to) to do something similar.

This is an interesting mechanic that lends itself towards the Chaplain's magical/supernatural nature, without *explicitly* encouraging him to run around with his swords shanking things.


This would be like removing gold cores+sentience potions from Xenobio---that is to say, you're removing an interesting mechanic that has uses for both antags and non-antags, alike, all because someone is breaking server rules.

Last I checked, we don't remove things or mechanics because someone used them to break server rules--we address the problem, administratively.

**Comment by Aracino** [comment]
So the chaplain should be allowed to make armies of nar'sie because a miner got lucky?

**Comment by KasparoVy** [comment]
Yeah. When else would they be able to? I'm pretty sure this happened to fight a blob one time or something, and it wasn't Nar'sie. It was Pyr'kaeus.

**Comment by Fox-McCloud** [comment]
>So the chaplain should be allowed to make armies of nar'sie because a miner got lucky?

Xenobio can already do this with golems and sentience potions.

And given how little this will happen, it can/will be interesting---not every single round is supposed to be static or the same; there's supposed to be dynamism and interesting happenings that occur on station---IMO, seeing this happen every once in a while would be interesting--even more so if an antag did it.

**Comment by granodd** [comment]
I'm sort of in line to agree with removing it. Why does the chaplain need it? What purpose does it serve in practicality? Why were they given it in the first place outside of "Meta station had it".

In terms of abuse, there is the previously mentioned "traitor" method of killing someone and then getting rid of the body, making it so they can't respawn. Sure it leaves bones, but you can't identify whose they are, as with any remains. Another thing that was sort of mentioned before is newbies using the thing to completely remove someone's ability to respawn. Sure you can "deal with it administratively", but just removing something that didn't make much sense to be there to begin with sounds like a much better alternative.

Yea, miners can get them, too, but they're not guaranteed. Nothing from the asteroid is (outside the space suit and toolbox + pod). It's also found on the asteroid where you can find all kinds of other culty shit like robes and I think even the cult blade(?).

**Comment by Lady-Luck** [comment]
I completely agree with Fox here. The crematorium is already a thing and isn't going away, so why is the soulstone such a problem in that context? This is silly.

**Comment by sothangel** [comment]
Doesn't really make 100% sense that the Chaplain would have something so heavily linked to the cult, as stated before. I was never really convinced that this was something the Chaplain needed to have added and if it was only to maintain parity with the Metastation map, I'm not so sure that was a sensible thing to make the decision based on.

**Comment by tigercat2000** [comment]
I mean, out of everything you could possibly nerf out of the chaplain, this seems like honestly the least silly thing.

**Comment by Lady-Luck** [comment]
Why exactly are we so obsessed with nerfing the chaplain lately?

**Comment by Aracino** [comment]
Because they have so much power for a service job. Do you see botany spawn with spwce vines? Or the chef with a meat cleaver? Its to lessen the valids and make chaps lean more towardsnspirtual shit than trying to kill people

**Comment by Fox-McCloud** [comment]
>Or the chef with a meat cleaver

Given that the chef starts off with a whetstone and it takes him a few seconds to get a butcher cleaver, well, this point isn't really allll that valid, to be honest.

Most of botany's most powerful things an be accessed in a < 10 minute time frame, and it's certainly higher impact than a single use soul stone shard.

**Comment by granodd** [comment]
@Lady-Luck This isn't really a nerf though, it's reverting the chaplain to what they used to be before we put in Meta station. They only got the stone because it was on the Meta station map, and rather than not remove it from there, they decided to add it to the main Box station map (for whatever reason).

One of the most common complaints about chaplains is that they're super valid-hunty, and I don't think that leaving something like a soul stone on their desk exactly discourages that in the least bit.

As for botany and the chef in terms of having access to their tools that they can valid with, every job has access to something that they can valid with. No one is actually _supposed_ to go valid hunting, though (except in rare circumstances such as nukies or wizard). The difference between botany/the chef and the chaplain is that botany and the chef have a job that's far more tangible. That is, their work has actual in-game mechanics and products to show the fruits of their labor in the form of actual fruits (for botany) and food (for the chef). Neither the chef or botanist is encouraged or even really allowed to go valid hunting, and I'm almost certain that we have rules against things like that.

The chaplain, on the other hand, is either completely a role-play job, or is a job that actually serves a critical role (in rounds such as vampire, cult, and soon-to-be, devil). You're needed, or you're not, there is no in-between. Though in the cases when the chaplain is needed, I can't imagine why he needs a soul shard. It does the same thing as the cremator, though is one use and mobile. However, even as that may be, I don't think its flavor fits in with the "holy" and "pious" nature of what the chaplain is supposed to be, and he should instead just have the cremator. 

Keeping the soul shard conveys all the wrong ideas if you want to keep the chaplain as a "non-valid-hunter" role, though if that is the case, I think that the chaplain could use some love or additional features to help discourage such.

**Comment by Twinmold93** [comment]
Why exactly was the chaplain even given such an occult item? Lore wise, it's an item heavily associated with cults and dark magic, something the chaplain should know about, but not necessarily be practicing himself. Due to association to cults, NanoTrasen would find the presence of such items to be in more support of cults, especially if used as it'd be understood the dark energies within could beckon forth worse foes. It's along the idea of all the darker or more twisted forms of the null rod. In any realistic sense, a holy man would never dare use them, and their use would be highly suspicious, even investigation worthy with mental re-evaluation just because the chaplain used it. They do not for in lore-wise, and mechanically can even give the air of hunter nature, with many taking the opportunity to go after antags because they can and screw actual lore. Having a useful shade can become with ease an extra pair of eyes, ones that can see beyond walls with genetics for self-adaptation. As from any lore, however, which seems to have passed many by, it just doesn't make sense.

**Comment by Doukhan** [comment]
@Twinmold93 I believe it's presence is an old holdover from the times when most SS13 servers had things such as public autolathes.
Take a look at some old station maps from before 2013 and a lot of them have things like soul stones laying around, mostly long gone now because balance.

**Comment by SamHPurp** [comment]
We literally added it because 'Meta station had it'.... which is crazy because while we're updating MEtastation to not be buggy, we're told to keep things the TG way and not 'paradise/boxstation-itise' the map.....

**Comment by KingPhilipIII** [comment]
If the complaint is lore, just resprite the chaplain's soulstone to something less occult, because not everything that calls a lost soul from the beyond has to neccesarily be evil. As far as mechanics. Meh. Idc. I don't think it's enough of a problem to warrent removal

**Comment by granodd** [comment]
@KingPhilipIII It's not the main argument, but it is one of the major ones. The main argument against it (at least in my mind) is that it encourages valid-hunting even further when chaplains have already had an issue with being very valid-hunty when they're not supposed to be.

**Comment by KingPhilipIII** [comment]
>Complains about soulstone for valid hunting.

>Does nothing about their null rod or armor.

**Comment by jughu** [comment]
Null rod already had its turn

**Comment by SamHPurp** [comment]
@KingPhilipIII literally rod and armour just got nerfed within the last week.

**Comment by KingPhilipIII** [comment]
Did it? I missed that PR then. I should check the changelog.

**Comment by granodd** [comment]
@KingPhilipIII #6647

**Comment by Fox-McCloud** [comment]
I really don't see the conjecture that this encourages validhunting, especially when pAIs exist. It's a minor supernatural element that the Chaplain has that fits in with his theme, without encouraging much of any behavior at all.

Yes, you have to use it on a dead person; that's not necessarily encouraging, explicitly, for the Chaplain to validhunt, so much as find someone who's dead. 

In the long scheme of things this is really *really* minor; I can do far more damage to antags, as a Chaplain, by carrying around a pAI, than a soulstone shard; and I"m generally more secured against staying dead, as well.

**Comment by ZomgPonies** [comment]
I'm against removing it because the arguments in favor of nerfing it are way way way out of proportion to it's actual effectiveness.

**Comment by FlattestGuitar** [comment]
That was actually an accident on my side, I deleted the branch too soon. :|

I guess I'll reopen this with the idea I had in mind some other time, considering the lack of opinions from the people in charge.

**Comment by SamHPurp** [comment]
Please re-add @FlattestGuitar, since it was an accident.

I'm wholly in support of this.

**Pull request closed without merging**
