### PR TITLE
revamps the fire cult floor tile

### PR DESCRIPTION
**Pull request by Aurorablade**
By Request, not sure this needs a changelog but it does need a picture!
Before:

After:

### CODE REVIEW

**Comment by KasparoVy** [comment]
burnination

**Comment by KingPhilipIII** [comment]
It should produce soft red lighting yea. Really nice effect that way. When will we see more unique cult structure sprites?

**Comment by Aurorablade** [comment]
i know i have some for death cult just not fire. but when i can sort some ideas i have out with datum...later...

**Comment by Aurorablade** [comment]
also the shuttle wall has to be in the do not eat blacklist...its got to be wit how its typed.

**Comment by Necaladun** [comment]
LGTM :+1:

**Pull request merged**
