### PR TITLE
Greatly reduces Slot machine money abuse

### PR DESCRIPTION
**Pull request by Darkmight9**
## What Does This PR Do
Greatly reduces the amount of money you can win on the slot machines and raises the buy in price to 50 credits

## Why It's Good For The Game
The slot machines have been a long standing issue with getting an economy going on paradise since it's basically free money with enough patience and clicking. Now the most you'll be able to win on the slots is 10,000 which is no small amount but won't completely bust the economy

## Changelog
:cl:
tweak: Reduced how much you can win on the slot machines and raise the buy in price to 50
/:cl:

### CODE REVIEW

**Comment by pmitchell** [comment]
Did the math really quick, and each spin has an expected payout of 34.8 credits, for a net loss of 15 credits a spin (versus a previous gain of like... hundreds per spin, on average).

**Comment by moxian** [comment]
> The slot machines have been a long standing issue with getting an economy going on paradise since it's basically free money 

The slot machine is currently *the only* way to make money on paradise.
Calling it "free money" is somewhat disingenuous - it's as much "free money" as being paid for services is  "free money" - you exchange your time for, well, money. If anything having a payroll (as it is on some other codebases), where you periodically receive cash just for existing is free*er* money than slots (where you need to actually spend time clicking things).

Yes, it's "unrealistic", but removing it while not providing alternative means to make profit is a bad thing. It effectively locks people out of buying musical instruments, and plushies from the claw game.
Since the only thing you can *spend* the money on are food vendors and fluff items (again, instruments and plushies), I doubt you even *need* to nerf the slots. No harm comes from having too much money "for free" (and do note that you still need to invest time spinning the slots to actually achieve the financial success).

If you have a convincing idea of overhauling the entire economy - then nerfing slot machines should definitely be part of that, but on its own this PR is not "good for the game", in my eyes.

And if you *really* want to nerf them "in preparation" of the economy overhaul or something - *at least* make sure that people's starting balance is always enough to afford a synth, several snacks, and a claw game plushie.

**Comment by Darkmight9** [comment]
> > The slot machines have been a long standing issue with getting an economy going on paradise since it's basically free money
> 
> The slot machine is currently _the only_ way to make money on paradise.
> Calling it "free money" is somewhat disingenuous - it's as much "free money" as being paid for services is "free money" - you exchange your time for, well, money. If anything having a payroll (as it is on some other codebases), where you periodically receive cash just for existing is free_er_ money than slots (where you need to actually spend time clicking things).
> 
> Yes, it's "unrealistic", but removing it while not providing alternative means to make profit is a bad thing. It effectively locks people out of buying musical instruments, and plushies from the claw game.
> Since the only thing you can _spend_ the money on are food vendors and fluff items (again, instruments and plushies), I doubt you even _need_ to nerf the slots. No harm comes from having too much money "for free" (and do note that you still need to invest time spinning the slots to actually achieve the financial success).
> 
> If you have a convincing idea of overhauling the entire economy - then nerfing slot machines should definitely be part of that, but on its own this PR is not "good for the game", in my eyes.
> 
> And if you _really_ want to nerf them "in preparation" of the economy overhaul or something - _at least_ make sure that people's starting balance is always enough to afford a synth, several snacks, and a claw game plushie.

At the risk of sounding rude (and I'm sorry if I do) but... is it really that hard to ask others for some spare cash? If you don't have enough money to buy a synth or play the claw game for a plushie then money has value for you now because you want to get those items. Now you need to ask around and RP to others for some spare cash so you can buy the things you want.

Other ways of getting some cash are becoming a miner and mining for a bit and redeem your points for some cash. Ask the HoP for a loan maybe since they run the account computer. Do some odd jobs for other people in exchange for payment. Ask for tips as one of the service crew. Take bribes as one of sec or command or take bribes in general, the syndi suitcase is for that purpose. Start up a business and ask for payment for your services. Donate some blood to medical in exchange for cash. There are other ways of getting money, it's not guarantied no, but there's other ways.

**Comment by Darkmight9** [comment]
> Did the math really quick, and each spin has an expected payout of 34.8 credits, for a net loss of 15 credits a spin (versus a previous gain of like... hundreds per spin, on average).

Yep, when you gamble you're not supposed to win. This is from someone who's been selling lottery and scratch off tickets for 4 years.

**Comment by moxian** [comment]
> At the risk of sounding rude (and I'm sorry if I do) but... is it really that hard to ask others for some spare cash? 
At the risk of being too political, yes, it is. I don't condone begging for money, both irl and in game.
I assume other people need the money just as much as I do, and it's not fair to them if they have to give their hard-earned money to me on a personal basis.
And this would even be okay if it was a "loan", but since I cannot repay it (because there is no way to make money!), it's just feels very bad.

> There are other ways of getting money, it's not guarantied no, but there's other ways.
In all the methods you've listed you are getting money from other people. There is no influx of money into the system, but there are only money sinks. This is not sustainable.
Other than mining... although i'll be honest i'm not 100% sure you can exchange mining points for cash. But I don't think it's a good thing when the only realistic way to get money is to be a miner".
The only reason mining does have this money bit (again, in case it does), is because mining was ported from /tg/ that already has reasonable economy, so mining earning money made sense there.

Again, i don't mind this nerf at all ***if*** we have a real economy to accompany it. On its own it degrades the paradise experience, not enhances it.

**Comment by Spacemanspark** [comment]
Tbh I like this change. People should not be able to spend five minutes at a gambling machine and gain a trillion credits easily. 

Hilariously, this makes the service borg a bit more useful. Perhaps that should be looked into as well in another PR.

**Comment by DevL-Whats-a-jpg** [comment]
I like this change aswell, also, science gets fuck tons of cash from reaserch.

**Comment by ppi13** [comment]
Currently you need to play 11512 to win a million, 3288 times to win 100k, 212 times to win 10k, 189 times to win 1k, 93 times to win 100, 93 times to win 50, 12 times to win 10, and considering each slot machine takes 26 seconds per roll, at average you get 1 winner of a million credit every 13-14 rounds.
While this needs a re-work for better economy, it needs to come along with the better economy, since this is the ONLY economy.

**Comment by Darkmight9** [comment]
If people have ideas for income sources or examples of how tg does their economy feel free to leave them here

**Comment by Darkmight9** [comment]
I got this discussion going might as well fish for ideas

**Comment by ppi13** [comment]
having a payment every 15 minutes, more job objectives, random economic events, re-work all vendors into costing currency to buy, alternative ways to earn money.

**Comment by Mitchs98** [comment]
I'm not actually sure on the numbers here, but in Discord it was supposed to be that you can't lose money playing the slots but you didn't easily gain it either. Unless I'm misreading the code here that's what this PR does, rather than make slots a money sink?

**Comment by procdrone** [comment]
An important question.

...what economy? What economy is being busted by the slot machines?

Money has no value or use, its flavor. You only can spend it at vendors and thats it. And since everyone starts with more than enough there is no incentive to earn more. And even if, kitchen removes any need to use vendors. 

I dont feel like this is required at all.

**Comment by procdrone** [comment]
@Spacemanspark Service borg money printing abilities are severly hampered by the energy requirements. You can't really print a fortune using them. and its very tedious given the fact it makes only 10 creds per print.

**Comment by Spacemanspark** [comment]
Cyborg rechargers are a thing. 

Also @PPI in theory, yes. In practice, people play for about ten minutes and get a million. I've seen it time and again.

**Comment by Mitchs98** [comment]
After thinking it over I'm no longer in favor, nor am I against this PR. I don't particularly feel it needs to be done at this point in time until an actual economy is made, but on the other hand as long as it's not nerfed to the point that you can't get more money for traders and vendors then I'm fine with it. It can always be reverted if earnings are too low for people to reasonably afford basic/essential fluff items.

**Comment by lolzyking** [comment]
> After thinking it over I'm no longer in favor, nor am I against this PR. I don't particularly feel it needs to be done at this point in time until an actual economy is made, but on the other hand as long as it's not nerfed to the point that you can't get more money for traders and vendors then I'm fine with it. It can always be reverted if earnings are too low for people to reasonably afford basic/essential fluff items.

If this pr is merged it will never be reverted, that's not how things work.

**Comment by Mitchs98** [comment]
> > After thinking it over I'm no longer in favor, nor am I against this PR. I don't particularly feel it needs to be done at this point in time until an actual economy is made, but on the other hand as long as it's not nerfed to the point that you can't get more money for traders and vendors then I'm fine with it. It can always be reverted if earnings are too low for people to reasonably afford basic/essential fluff items.
> 
> If this pr is merged it will never be reverted, that's not how things work.

That....is though? If a bad PR is merged, revert is always an option. That most certainly is how things work and has been done MANY times before. If anything a new PR can be made adjusting the changes.

PR's are not simply merged with no chance of ever being changed again. **_THAT_** is not how things work.

**Comment by AffectedArc07** [comment]
> If this pr is merged it will never be reverted, that's not how things work.

You're aware that this *is* the case? If we merge a PR which tends to horribly screw things up, we do revert those. 
image
Examples of 2 here.

**Comment by Kyep** [comment]
This is a first step towards us eventually having an actual economy. So yes, please.

**Comment by Mitchs98** [comment]
> This is a first step towards us eventually having an actual economy. So yes, please.

I'm iffy on this being a valid reason to merge this right now.
This is something that should be merged later, when the economy system itself is/right before it. Not something merged well in advance that kills the players' ability to get more money with the promise of a system _eventually_ being put into place.

**Comment by Spacemanspark** [comment]
Can we re-add ponies old economy system

**Comment by Mitchs98** [comment]
> Can we re-add ponies old economy system

Explain for those of us that have no idea what this is :eyes:

**Review by Kyep — APPROVED** [review]

**Comment by AffectedArc07** [comment]
Please resolve the TGUI conflict

**Comment by AffectedArc07** [comment]
```
Error: our build differs from the build committed into git.
Please rebuild tgui.
```

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
