### PR TITLE
Prevent syndi key from being metad

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
:cl: Tayyyyyyy
tweak: Headsets with syndicate encryption keys stop working when someone else tries to listen to them
tweak: Syndicate encryption keys cannot be removed from a headset with a screwdriver.
/:cl:

Reasoning behind this:
- It's kind of silly that security can't listen in on syndicate channels because "contraband abuse". /tg/ has a syndicate language to circumvent this, but I figured this might be a better solution so that you can't figure out the names of the traitors, even if the traitors are using another language
- All traitors using the syndicate channel shouldn't be screwed over just because someone else found a headset
- I made the encryption key unremovable, because even though it's intended not to be meta-able, being labeled as a "standard encryption key", most security knows that's BS and will call you out. It also simplifies the code for wiping the syndie key when someone else gets their hands on it.

IC justification:
An organization within the Syndicate has developed Bluespace Mindprint(tm) technology and installed it to syndicate encryption keys. Now, if a headset with a syndicate key falls into the hands of someone else, the syndicate key will automatically destroy itself, leaving no trace behind.

This applies to nukies as well

### CODE REVIEW

**Comment by StreakyHaddock** [comment]
So... Detectives won't be able to scan the key?

**Comment by Tayyyyyyy** [comment]
They can scan it if it's been put into a headset. If it's already inside the headset there's no way to take it out. If there's another normal encryption key, the normal one will pop out. If it's a civy headset that doesn't have a normal encryption key, it'll say "no encryption keys"

**Comment by Ty-Omaha** [comment]
What if they want to give it to a collab/mindslave/other syndicate?

**Comment by Tayyyyyyy** [comment]
They'd have to give them the encryption key before putting it into the headset. The owner is determined by whoever picks it up/wears it and hears something first.

**Comment by alexkar598** [comment]
I like to remove my key a lot when im traitor with syndi comms,maybe make it so when traitors screwdrivers it it shows a menu to choose to take out traitor key or normal key

**Comment by alexkar598** [comment]
Also you can still meta it by bein on the same tile as traitor and hearing the sweet intercepted chat

**Comment by Tayyyyyyy** [comment]
Shhh don't give them any ideas. I dont want power gaming sec officers to be batoning people and intentionally getting on top of them. I guess I could also add a manually activated self destruct ability if that becomes an issue. But hopefully this will reduce the vast majority of "boink, why we're you listening to a syndicate headset?"

I'm open to ideas for fixing issues involving that though. I think I might have it deactivate when on the ground too.

**Comment by Allfd** [comment]
I was thinking you could instead have a phrase that wiped the key or destroyed it.   It could be set by the user initially.

But that could just be more work.

**Comment by Ziiro** [comment]
Alternatively: Have it something that is implanted in them that gives them access with **_any_** headset they put on.

🤔

**Comment by Jountax** [comment]
An implant that works like an undetectable headset would be amazing and make a lot of sense, actually.

**Comment by uraniummeltdown** [comment]
If a traitor gets caught by Sec and they catch hold of the channel, so be it. It's part of the game, there has to be some danger to buying the encryption key. It's not a mandatory purchase at all.
Making it unremovable is stupid. If you really want to make it meta-proof, make the key take on the sprite, desc, name of another station key.
IIRC Standard Encryption Keys used to be actual keys that gave Common channel access

**Comment by Tayyyyyyy** [comment]
> If a traitor gets caught by Sec and they catch hold of the channel, so be it. It's part of the game, there has to be some danger to buying the encryption key. It's not a mandatory purchase at all.
Making it unremovable is stupid. If you really want to make it meta-proof, make the key take on the sprite, desc, name of another station key.
IIRC Standard Encryption Keys used to be actual keys that gave Common channel access

I would agree with you but people have been job banned for "abusing contraband". I would rather the problem of this channel being solved through code rather than through admin enforcement, which is spotty and someone could easily get away with eavesdropping as long as they don't say that they're using it out loud.

Also it just isn't very fair that if one traitor gets caught, everyone else on the channel is screwed. This is why it's forbidden to use captured headsets, even though it makes no sense not to gather that intelligence.

I can increase the TC price to 3 TC if it's really that much of a buff, but I honestly don't think this changes the headset at all, because right now server policy is that you're not supposed to abuse contraband. This is preventing something that wasn't supposed to happen in the first place.

On Implants. While an implant is a good idea, it would have to be a separate item, probably with a higher TC price. It's easier to sneak into perma and stufff like that.

**Comment by Vivalas** [comment]
Eh, I'm pretty sure all headsets come with a standard encryption key, I'm not exactly sure how that is meta-able.

Either way syndicate encryption key is very powerful to traitors and this is a good downside to using it, as well as contributing to the paranoia theme of the game, which I think is very important.

**Comment by Tayyyyyyy** [comment]
No, I tested that or I wouldn't have made that change. Civilian headsets don't have keys.

It's not a downside because once again, admins don't want you to be doing it. There are IC and ooc consequences to using this as security. No need to repeatedly bring this up as a downside, it's not one.

**Comment by Spartan6** [comment]
This is a bit silly, really. Syndicate comms should be able to get compromised as much as security comms do.

**Comment by Shadeykins** [comment]
As per space law, evidence is to be used as **evidence** and nothing else.

If you're abusing confiscated equipment (IE: evidence), whether that is by stealing people's utility belts, their medical supplies, or their contraband, you're breaking the law as a Security Officer. You are doing the exact opposite of your job, and security officers abusing traitor equipment to get an edge is not something anyone wants to promote.

This is an all or nothing - either we let security abuse this equipment and we have officers running around with .357's and chainsaws, or we don't let them abuse it and we end up bwoinking over abuse. Arguing otherwise and creating a list of "it's acceptable to abuse this kind of evidence, but not this kind" would set a ludicrous double standard.

"Abuse of Confiscated Equipment" exists for a reason - poking holes in that with exceptions just makes Space Law even more unwieldy and defeats the entire purpose of the clause. This nonsense with the headsets is no different than when we had proper loyalty implants - security would capture changelings, loyalty implant them, and vicariously "listen in" on the changeling hivemind.

**Comment by Fox-McCloud** [comment]
The changelog is not a place to roleplay, please stop.

Things are to be cleanly documented and clearly laid for there what you're changing, precisely; it's a technical and basic tool, not social interaction.

**Comment by Tayyyyyyy** [comment]
Sorry Fox. I was just trying to provide some IC reasoning behind it since changelogs are player facing.

Changelog fixed.

I like the implant idea but it would require a TC increase. This is more of a thing to have the policy against listening in on syndicate comms make more sense. I think I'll add a 30 second timer or something for the headset being on the ground to deactivate so people can't strip it and then stand on top of it to eavesdrop.

**Comment by LightFire53** [comment]
Well, this would prevent them from removing the key and inserting it into their own headset, but anyone who still wants to get dat sweet power game would just wear it on the other ear, and maintain the benefits of hearing both syndicomms and flash protection.

**Comment by Tayyyyyyy** [comment]
Well, the PR as is actually wipes the key if someone else other than the original owner puts it on. But I really like @Allfd's of a voice activated wipe better, cause that gives the user a bit more control over it. Closing this PR in favor of that idea.

**Pull request closed without merging**
