### PR TITLE
Allow admins to drag-drop ghosts into mobs 

### PR DESCRIPTION
**Pull request by tigercat2000**
Port of tgstation/-tg-station#8957

This allows administrators to drag their mouse from a ghost to a type of
/mob/living, which will then prompt them if they wish to put that ghost in
control of the mob, and obviously, that is exactly what happens if you
select yes.

Tiger's notes- Original commit by MSO had access requirements similar
to editting a ckey in vv, but, after discussing it with a headmin, and
the fact that our trialmins can assume-direct-control, this only
requires R_ADMIN & R_DEBUG, or R_VAREDIT

Player Notes; Only affects admins.

Admin Notes: Click and drag any ghost (yes that includes yourself) onto a mob, hit yes in response to the warning, ???, win. But seriously, it will warn you if the mob has a client, pay attention and try not to displace anyone :P

### CODE REVIEW

**Comment by SamCroswell** [comment]
:+1:
Useful indeed!

**Comment by MrStonedOne** [comment]
As an added bonus, it will properly kick any existing person out of the mob, where as editing a ckey by hand when it already has somebody in it will cause that somebody's connection to crash, and when they come back, they will find themselves in the lobby.

**Comment by Fox-McCloud** [comment]
@MrStonedOne 

We actually deliberately used that, for a while, to kick people to lobby before you guys released "return to lobby"--it had the side effect of runtimming the key list though =p

**Comment by JJRcop** [comment]
Before this is merged, I would take a look at tgstation/-tg-station@2227b7adb31a113488e1305246478eb8878a0cab

**Pull request merged**
