### PR TITLE
Replaces chocolate in weightloss shakes with berry juice

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Replaces the chocolate in weightloss shakes with berry juice so vulps can drink them without being poisoned.

## Why It's Good For The Game
As of the recent vulp vision and diet changes, vulps are now poisoned by chocolate. Weight-loss shakes are quite useful for losing weight, and the fact vulps would need to break weight-loss shakes down in chemistry feels like a bit of an oversight.

## Testing
Drank a weight-loss shake, didn't get poisoned.

## Changelog
:cl:
tweak: Weight-loss shakes now contain berry juice instead of chocolate.
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
Oversight? 😏

**Comment by SpringSkipper** [comment]
I feel like this is the sort of small impediment that vulps should need to deal with in exchange for their better nightvision (and, as someone who obstinately still wanders maints with no lightsource, the increase from 3 to 4 is a big difference!)

You can still get a chemist, chef, or botanist to separate out the chocolate for you. The only real issue I have with this is the same issue I had with the original PR; vulp chocolate poisoning is boring. It silently does toxin damage instead of at all resembling real life symptoms or being fun or comedic like, say, a grey's fire extinguisher weakness or a nian's flyswatter weakness.

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Carthusia** [comment]
I like it as is, its just a quirk you have to deal with when playing as a different species and it adds flavor

**Review by hal9000PR — APPROVED** [review]
I dont agree with this but 95 is TOO many PRs

**Pull request merged**
