### PR TITLE
Readds Glove snipping

### PR DESCRIPTION
**Pull request by Aurorablade**
# **ALERT ALERT: THIS IS OPTIONAL COMESTIC ONLY I AM NOT TRYING TO ADD BACK IN THE RACIAL RESTRICTIONS BUT ALOT OF PEOPLE WERE MISSING DOING THIS FOR OUR CHARACTERS SO ITS OPTION COSMETIC ONLY! WEEWOOOOOWWEEEEWOOOOOOOOOOOO ALERT ALERT**

:cl: Fethas
rscadd:Due to various complaints from tajarans having hand cramps, glove makers have changed the fabric to not include plasteel in the thread...
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
For what purpose

**Comment by FreeStylaLT** [comment]
wait how does this work with black gloves which turn into fingerless gloves now

**Comment by Aurorablade** [comment]
.....someones gonna have to tell me what to check for that...

**Comment by LightningLynx** [comment]
...why? for what possible purpose?

do i really need to hunt down wirecutters any time i want to put on a pair of gloves, just because some people think that this somehow magically contributes to the roleplay atmosphere of this server? out of all the issues with roleplay here, we're getting hung up on gloves snipping?

**Comment by Earthdivine** [comment]
This being a forced thing I do not like.

Having it be an optional choice I am fine with.

Being told you cant have gloves and have to hunt down wirecutters, which are often completely taken by greyshirts to have a toolbox in their box, and then having to probably bug cargo for a pair...doesn't seem like it'll add to the roleplay aspect at all. It sounds more like menial work to use something every single other race is allowed to have.

**Comment by FalseIncarnate** [comment]
This does not REQUIRE snipping. It just lets you create "mangled insulated gloves" and such again.

Aside from a name and description change, it has no mechanical impact.

**Comment by Earthdivine** [comment]
OP really should update with that, cosmetically that feels fine.

**Comment by Fox-McCloud** [comment]
This is going to cause issues with black gloves.

**Comment by Aurorablade** [comment]
I didn't feel i needed to state this does not add back the racial restrictions...

@Fox-McCloud i was going to fix that i just had to sleep last night and needed to find the point in the code that affected that...

**Comment by Lady-Luck** [comment]
Snipping gloves was always stupid. Exposing your nails in latex/nitrile gloves is obviously the worst thing ever for surgery, there would be infections for obvious reasons.

And theoretically, even though nails are insulated to some extent, insulated gloves are far more insulated than nails, so you could get electrocuted by having exposed claws if the current is strong enough.

It was always a dumb thing and bringing it back is just reintroducing the dumb.

**Comment by Spacemanspark** [comment]
That's great, but it doesn't have any effect on gameplay so who cares?

**Pull request merged**
