### PR TITLE
Fixes blob spawn locations, broken wires, duplicated items in a maint room

### LINKED ISSUE #6918: Hidden Surgery Room IN Chapel Maint has duplicates
**Problem Description**:
What is the problem?

The surgery table, computer frame, IV drip, sleeper are all Duplicated on the same spot.

**What did you expect to happen**: 
Why do you think this is a bug?

Pretty sure there shouldn't be two of everything there

**What happened instead**:
How is what happened different from what you expected?

Should be only thing there.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

People can get 10 plasteel very easily from the Duplicate surgery table.

### PR DESCRIPTION
**Pull request by SamHPurp**
Fixes blob spawns including - http://imgur.com/GcffX6O - Blob spawns right next to a welder. Boom.

Fixes #6918 - Duplicate surgery room fixed (looks like @Norgad's PR copy pasted twice over itself)

Fixes broken wires stopping the grilles in front of the bridge from being electrified.

:cl: Purpose2
fix: Stops an instance of blobs welder bombing itself on spawn.
tweak: Moves a few event blob spawn locations around.
fix: Fixes the broken wires, re-electrifying the grille in front of the bridge
fix: Fixes duplicate maintenance surgery room items
/ :cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
>What was that?!
Blob!

**Comment by SamHPurp** [comment]
Updated with a few more blob spawn spot fixes (thanks to those of you that suggested fixes on these). Also fixed some long standing wiring problems with the grille in front of the bridge, and a new bug introduced in the latest version of maintenance with duplicate items in the surgery room.

**Comment by FreeStylaLT** [comment]
#6900 Fixes #6918 As well. The Issue was posted after the PR, though, so I didn't get to point it out at the time.

**Comment by SamHPurp** [comment]
@FreeStylaLT Alright. It'd be great to get a view as to when things'll get merged and the order.

I'm assuming yours will go in before mine, then end up re-doing my blob fixes & grille fixes.

**Comment by SamHPurp** [comment]
This is still an issue.

**Comment by SamHPurp** [comment]
Since @FreeStylaLT closed his PR, mine remains the only one that fixes the duplicated Surgery and other issues.

cc: @Fox-McCloud @Crazylemon64

**Comment by SamHPurp** [comment]
Any communication on this one guys?

**Comment by SamHPurp** [comment]
https://www.youtube.com/watch?v=f4zyjLyBp64

**Comment by taukausanake** [comment]
Is this based on new maint? It got reverted so might want to close

**Comment by SamHPurp** [comment]
@taukausanake yeah, I'm going to re-open fixing the wiring bug soon-ish.

**Comment by Fox-McCloud** [comment]
Closing this due to the revert.

**Comment by SamHPurp** [comment]
I'd just like to highlight the vast period of time repeatedly asking for feedback and receiving none, is exactly what people have been complaining about, @Necaladun .

Obviously now, the plan was to revert, but these were bug fixes that sat and sat and sat for ages.

**Pull request closed without merging**
