### PR TITLE
Expanded cyberiad permabrig

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR expands the permabrig on cyberiad to include a library room, a mostly furnished kitchen, a large "green" area for growing and relaxing, and various gym equipment.
Solitary cells are inside perma, so they are isolated but still not totally cut off from everyone.

The prison entry doors by default operate in an "airlock" system like xenobio. It will be most efficient with an officer manning the controller, but works using the provided buttons too. This system can be overriden by having the AI unbolt them.

The execution room has been adjusted to allow for asphyxiation and gas-based executions.

Nearby maints has been shifted to allow for room between the SIT shuttle dock and perma.

I've also included a mapping QoL change that puts wires _above_ atmos pipes during mapping, and makes them semi-transparent. This is all put back to normal on initialise.

## Why It's Good For The Game
Currently, perma on cyberiad is so cramped it is oppressive. While this does fit the prison theme, it is not very good for the players. While this doesn't promise to make perma super engaging and fun to be in, but it will be an improvement over the current one.

Metastation has a better perma, and this takes inspiration from it.

## Changelog
:cl:
tweak: Remapped cyberiad permabrig and surrounding brig rooms.
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
An initial thought is that now there are multiple windows prisoners can escape out of (including solitary now), having exterior camera for those areas is not a bad idea.

Haven't had a chance to boot it locally either, but how does the airlock system react when the prison break event occurs?

**Comment by S34NW** [comment]
> An initial thought is that now there are multiple windows prisoners can escape out of (including solitary now), having exterior camera for those areas is not a bad idea.
> 
> Haven't had a chance to boot it locally either, but how does the airlock system react when the prison break event occurs?


Good points, I will add exterior cams and I am unsure on the second point

**Comment by lewcc** [comment]
Really good to see more space in perma. It feels a lot more like meta's brig now, with a lot less observability and a lot more (internal) freedom for prisoners, which seems like a good thing given that prisoners have like two or three places they can actually hide in permabrig. I also think the airlock system is pretty neat, making perma access/booking different across all three stations provides some interesting diversity.

Just some quick notes:

image
This maintenance room should probably be rwalled out to space? Otherwise, it's a very weak link that current box brig maints doesn't have.

- Three tanks of n2o feels like overkill. There's definitely a lot more space to cover, but that's a *lot* of gas, and I can't imagine it'd be any fun for atmos techs to clean it up. If it gets released in brig as well, it's probably not getting cleaned.

**Comment by S34NW** [comment]
> Really good to see more space in perma. It feels a lot more like meta's brig now, with a lot less observability and a lot more (internal) freedom for prisoners, which seems like a good thing given that prisoners have like two or three places they can actually hide in permabrig. I also think the airlock system is pretty neat, making perma access/booking different across all three stations provides some interesting diversity.
> 
> Just some quick notes:
> 
> image This maintenance room should probably be rwalled out to space? Otherwise, it's a very weak link that current box brig maints doesn't have.
> 
> Also, three tanks of n2o feels like overkill. There's definitely a lot more space to cover, but that's a _lot_ of gas, and I can't imagine it'd be any fun for atmos techs to clean it up. If it gets released in brig as well, it's probably not getting cleaned.

Good points, thanks for pointing out the rwall especially. I'll fix these now :)

**Comment by LightFire53** [comment]
> Also, three tanks of n2o feels like overkill. There's definitely a lot more space to cover, but that's a _lot_ of gas, and I can't imagine it'd be any fun for atmos techs to clean it up. If it gets released in brig as well, it's probably not getting cleaned.

Noting that you don't have large scrubbers in the screen shot, would recommend that you add some of those and their control computer

**Comment by Inadvizable** [comment]
Very pretty, nice work. I think making perma a nice place really facilitates a better mentality about being put there. Box's current perma is... you might aswell go afk, unfortunately.

**Comment by S34NW** [comment]
> Noting that you don't have large scrubbers in the screen shot, would recommend that you add some of those and their control computer

Added, thanks

**Review by LightFire53 — APPROVED** [review]
Looks good, only comment is that you have the mouse as Tom in the maintenance room rather than generic mouse. Either we need a different prisoner mouse or Tom needs to be removed from the vault for his crimes and permabrigged.

**Comment by S34NW** [comment]
> Looks good, only comment is that you have the mouse as Tom in the maintenance room rather than generic mouse. Either we need a different prisoner mouse or Tom needs to be removed from the vault for his crimes and permabrigged.

Tom will finally pay for major tresspass... (I'll change the path, good spot)

**Review by Bm0n — CHANGES_REQUESTED** [review]
Got a review for you.

<details><summary>review</summary>
Normal table should be an rtable

image

These two cameras look awkward when viewed with x-ray or by ghosts. You might want to change the bottom left ones dir to either 8 or 9

image

Shocked wire is unconnected and not following the pipes

image

Perma mains door helper should be brig not armoury

image

Perma space camera is not areaed like the rest of our space cameras

image

Ditto

image

Again

image

I would remove the grillies that for some reason go on top of the blastdoors. They look really ugly.

image

Buttons on windows... try to avoid this

image

Solitary has no APC or air alarm.

image

Execution is lacking a firelock

image

This air alarm is in a wall

image

Prison oversight is lacking a firelock

image

Denth didn't like it when I had windows exposed to space with nothing blocking them for Meta. I am sure he'd think the same for your PR.

image

I would put some catwalk under these docking beacons like I did on Meta

image

Example from Meta:
image

Needs rwalling

pr1

Why is this here? It looks out of place

image

Space is lacking a lot of detailing such as lattice and it really shows

image

This is purely a suggestion so feel free to ignore it but perhaps this is a better layout

layout

</details>

I'll review this again later once changes have been made.

**Comment by S34NW** [comment]
> Perma mains door helper should be brig not armoury

This was not done in error, but on purpose. It's aim is to somewhat mitigate gamer security officers rushing the room and stealing everything (There are some basic tools in there.) The warden is less likely to do this as they start with tools, and tend to be less "gamer" than officers.



> Perma space camera is not areaed like the rest of our space cameras

As discussed in discord it seems this is no longer required for it to function, we can likely remove the "requirement" (quotes because it was never a hard requirement anywhere, just a consistency thing) for these to get an area.



> I would remove the grillies that for some reason go on top of the blastdoors. They look really ugly.

I've managed to put them under the blast doors, they are important to have to stop anything in the room exiting on being spaced.



> Buttons on windows... try to avoid this

Seems fine to me in this instance, but I've put them on the walls for you ❤️ 



> Solitary has no APC or air alarm.

This area was removed and made part of the brig like currently on box, turns out that area has power shenanigans.



> Denth didn't like it when I had windows exposed to space with nothing blocking them for Meta. I am sure he'd think the same for your PR.

I'd respectfully leave other's opinions for them to express if true.



> Why is this here? It looks out of place

To give prisoners somewhere to keep their trash (and to hire the wirecutters)



Anything else not directly discussed has been addressed.

**Comment by Bm0n** [comment]
> This was not done in error, but on purpose. It's aim is to somewhat mitigate gamer security officers rushing the room and stealing everything (There are some basic tools in there.) The warden is less likely to do this as they start with tools, and tend to be less "gamer" than officers.

If secoffs are doing this I would suggest warning them for powergaming. An officer already got trapped in there during the TM, it's probably best to keep it brig access.


> Seems fine to me in this instance, but I've put them on the walls for you ❤️

the reason you want to avoid putting buttons on windows is because(especially the ones facing the inside of perma) they're probably the first thing to break and that leaves floating buttons. Walls are much more solid and more unlikely to be outright destroyed.

> I'd respectfully leave other's opinions for them to express if true.

Normally I would but that was denths main objection to Meta as a whole and perma had to be changed quite a bit to get it approved.

Considering that this version of Box perma is very obviously based on Meta's and that new Meta is only about a month old I thought it'd be reasonable to bring it up.

> To give prisoners somewhere to keep their trash (and to hire the wirecutters)

perhaps use a trashcan like the one outside the kitchen instead? 

I'll review this again probably sometime tomorrow to see if I can find anything else awry

**Comment by S34NW** [comment]
> An officer already got trapped in there during the TM

Good, they can stay in there. How did they even get in? I'm not making this an administrative issue when it can be easily solved by mechanics. What actual reason do officers have to go in there?



> Walls are much more solid and more unlikely to be outright destroyed.

I would agree for rglass, but rplasma is substantially stronger than a regular wall. Your point still stands though and I will leave the buttons on the walls.



> Normally I would but that was denths main objection to Meta as a whole and perma had to be changed quite a bit to get it approved.
> 
> Considering that this version of Box perma is very obviously based on Meta's and that new Meta is only about a month old I thought it'd be reasonable to bring it up.

Somewhat fair, but if denth has an issue denth will say. I'm not changing things because someone might say something maybe. Meta and Cyberiad are different maps that can have different approaches.


> perhaps use a trashcan like the one outside the kitchen instead?

Sure

**Comment by EmilyFontaine** [comment]
Super happy to see an expanded permabrig like this. Everything is a vast improvement, save for one thing.

Old cyberiad permabrig had (and every other station, as far as I'm aware, have) the two cells that you could lock down in order to process new prisoners into perma, which this new layout lacks. I'm not sure if this was done intentionally or due to a lack of space, but the absence of it is definitely a detriment.

Also, it seems that if a light switch is pressed in an isolated room, like the showers, the lights in the entire permabrig are turned off.

**Comment by Dafrek** [comment]
I believe that when you moved the access buttons from the windows to the walls they were placed in spots that you cannot reach from inside the airlock system. I noticed this while it was test-merged, resulting in either having to use a door-remote to get in and out or by having an officer in the oversight room let you in with the door controller in there.

**Comment by S34NW** [comment]
> I believe that when you moved the access buttons from the windows to the walls they were placed in spots that you cannot reach from inside the airlock system. I noticed this while it was test-merged, resulting in either having to use a door-remote to get in and out or by having an officer in the oversight room let you in with the door controller in there.

oh crap hahah you are right

**Comment by Bm0n** [comment]
image

image

>>Buttons on windows... try to avoid this

>Seems fine to me in this instance, but I've put them on the walls for you ❤️

https://www.youtube.com/watch?v=YcAHHKY3Y0I

but that's just me being picky

image


>>perhaps use a trashcan like the one outside the kitchen instead?

>Sure

https://www.youtube.com/watch?v=YcAHHKY3Y0I

this

image

image

besides that the east and west warning stripes in solitary should be removed as they're being covered up by the full one

image

remove the corner warning stripe here. it's breaking the 3d illusion/shading of the stairs

**Review by Bm0n — APPROVED** [review]
the only thing I can find is two dirt decals stacked on top of each other but that's very minor so lgtm

image

**Review by hal9000PR — APPROVED** [review]
LGTM

**Pull request merged**
