### PR TITLE
Removes Last Traces of Xenoarch

### PR DESCRIPTION
**Pull request by Fox-McCloud**
removes the last tidbits of xenoarch

- Removes Xenoarch access constant
- Removes "Xenoarcheologist" alt scientist title
- Removes "Anomalist" alt scientist title

:cl: Fox McCloud
del: Can no longer select "Xenoarcheologist" or "Anomalist" as scientist alt titles
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
SQL change?

**Comment by alexkar598** [comment]
Rip xeno arch

**Comment by Keilden** [comment]
Rip xeno arch, you will be missed by me atleast.

**Comment by Ataman** [comment]
Always thought the Anomalist is just a general scientist specialised on anomalies (the random ones occuring on the station) what's his connection to xenoarcheology?

**Comment by Fox-McCloud** [comment]
@Kyep 

The SQL table is going to have to be altered a bit so that everyone who has the title "Xenoarcheologist" or "Anomalist" is removed.

@Ataman 

Anomallies were a thing you'd harvest as a xenoarcheologist. They had unique/weird properties/effects. They could be harvested out of the anomaly and into an anomaly-battery and utilized somewhere else....at least in theory. In practice, storing of the anomaly didn't work, really; just the anomaly itself.

They're gone now and have been for 2 years (from a player perspective).

**Comment by Ataman** [comment]
@Fox-McCloud alright, didn't know that, 2 years ago I never heard of ss13 tbh.

**Comment by Kyep** [comment]
@Fox-McCloud Oh. I was confused for a moment as I did not see any file change that referenced SQL. Nevermind.

**Comment by Jountax** [comment]
@Fox-McCloud 
"The SQL table is going to have to be altered a bit so that everyone who has the title "Xenoarcheologist" or "Anomalist" is removed."

My Removed do you mean just setting their job title back to scientist?

**Comment by SamHPurp** [comment]
If it helps, here is the SQL we executed to strip Coroner as an alt title:

`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, 'Medical+Doctor=Coroner&', '') WHERE INSTR(player_alt_titles, 'Medical+Doctor=Coroner&');`
`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, '&Medical+Doctor=Coroner', '') WHERE INSTR(player_alt_titles, '&Medical+Doctor=Coroner');`
`UPDATE characters SET player_alt_titles = REPLACE(player_alt_titles, 'Medical+Doctor=Coroner', '') WHERE INSTR(player_alt_titles, 'Medical+Doctor=Coroner');`

**Comment by StreakyHaddock** [comment]
Can we keep Anomolist? It sounds like a more tele-sciency title than xenoarch.

**Comment by tigercat2000** [comment]
I think we should keep the anomalist title. Additionally, please do what Crazy said and add an SQL update directory (no need to bump the sql version, though)

**Comment by Fox-McCloud** [comment]
Will look into some other time; for now, not going to bother.

**Pull request closed without merging**
