### PR TITLE
Atmos Fix

### PR DESCRIPTION
**Pull request by Allfd**
Fixes ambulance once and for all.

🆑  Alffd
fix: Makes throwing the ambulance with atmospherics almost impossible.
/🆑

### CODE REVIEW

**Comment by MarcellusPye** [comment]
Time to start making float overflows in atmos!

**Comment by taukausanake** [comment]
Should this maybe be applied to other vehicles like the janicart and security thing?

**Comment by Allfd** [comment]
Its not the cart so much as the trolley.

**Comment by taukausanake** [comment]
Ah okay

**Comment by tigercat2000** [comment]
I really wish we could fix whatever fucked up underlying issue there was with the ambulance, instead of hacky patch jobs like this.

**Pull request merged**
