### PR TITLE
Makes the swedish gene more swedish

### PR DESCRIPTION
**Pull request by pinatacolada**
957288bc2b

Also because I'm not sure if git will fuck up the encoding or not:
d4e5bd814e

:cl: Pinatacolada
add: Makes the swedish gene spit out weird swedish chars and sounds
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
could you like please organize these replacements
have all the lowercase replacements at the top, uppercase at the bottom
or the opposite
or literally any method of consistent sorting

**Comment by pinatacolada** [comment]
oops, i swear they were at one point

**Comment by Davdichan** [comment]
Bork Bork!

**Comment by pinatacolada** [comment]
oh what the fuck

**Comment by Chakirski** [comment]
Atom likes to override your indentations and forces them under the previous function. I have yet to find a way to slap it and put atom in time out.

**Comment by FalseIncarnate** [comment]
Wi nøt trei a høliday in Sweden this yër?

:+1:

**Pull request merged**
