### PR TITLE
rework disease outbreak event

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
The level-7 Biohazard event now has a 75% chance of creating a randomly named virus with 6 random symptoms and randomized properties. This spices up the biohazard event and also breaks the meta of all advanced diseases coming from the virologist. The disease has a randomized name

**Changelog:**
:cl:
tweak: Reworks the biohazard event to have a chance of giving a randomized advanced disease with 6 varying symptoms instead of a preset disease.
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
>tweak: Rework biohazard.

isn't very descriptive, people should know how it was "reworked"

**Comment by Couls** [comment]
add: Blushing Village virus

**Comment by Pckables** [comment]
Will the disease have randomly generated names?

**Comment by Couls** [comment]
> Will the disease have randomly generated names?

Yeah, forgot to include that in the PR description but yes it uses a random adjective and noun from a list

**Comment by Ralta** [comment]
Can't wait to have the `Mushy Sex` disease :eyes:

**Pull request merged**
