### PR TITLE
Thunderdome and Admin Room Changes

### PR DESCRIPTION
**Pull request by SamCroswell**
- Adds a new martial art and weapon, detailed here: tgstation/-tg-station#10191. Currently unused outside the Thunderdome and Admin room.

 - Fixes a minor area tagging issue in the admin room.

 - Changes the thunderdome to not use dynamic lighting.

 - Changes the axe supply (Now the 'specialist' supply) to contain a sleeping carp scroll and staff as opposed to the fire axe it had previously.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by tigercat2000** [comment]
> Changes the thunderdome to not use dynamic lighting.

I'm not sure that's a good idea, I was trying to phase out non-dynamic-lit areas with the original lighting PR, although not really sure if that's still my intent.

**Comment by SamCroswell** [comment]
Why would we need dynamic lighting in the thunderdome?

**Comment by tigercat2000** [comment]
@SamCroswell Because it looks fancy. I should work on indestructable lights.

**Comment by Fox-McCloud** [comment]
Very Yesss :+1:

**Pull request merged**
