### PR TITLE
Revert "Goonchem: Addiction Rework"

### PR DESCRIPTION
**Pull request by Spacemanspark**
Reverts ParadiseSS13/Paradise#13034

But Spaaaark, wh-
This is largely here because I've seen nothing good come from the system mechanics or roleplay-wise. While this might fit on Goonstation, it doesn't mesh well here. I haven't seen a single good comment on the new system. 

This all said, I understand there are PRs out there to change and rebalance the system. Should those be accepted and make all sides happy, I'll happily close this after a period of time if I see no further complaints on the system. Improve over removal, yes. 
However, If the majority of players still hold issues, I'm leaving this up. 

Hi yes CL stuff ahoy
:cl:
del: Reverts the addiction system back to the way it was prior to the goon port.
/ :cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
Posted before Spark added the PR Description:

I assume this will revert the whole "You are addicted to (Black Russian, Vodka, Absinthe) kind of addictions that keep happening when people just have a few drinks at the bar or eat some icecream with liquor in the mix?

**Comment by Spacemanspark** [comment]
Yes

**Comment by Mitchs98** [comment]
Please do. I haven't been able to actually drink or smoke as any of my characters due to this. Either this, or a decent bump in the thresholds need to happen.

**Comment by Denthamos** [comment]
While I do like the idea of addictions taking place with the addiction system on paper, in practice it makes people just avoid anything that may get them addicted.

**Comment by MRgaty** [comment]
Till it can get tweaked I think we are better without it.

**Comment by Spacemanspark** [comment]
I might close this since alcohol addiction was removed. Cigarette addiction is still an issue in my eyes, however.

**Comment by Carthusia** [comment]
The cig addiction is a bit of an issue, i smoked a pipe for 30 seconds and became addicted, and not long after began to have withdrawls, even though the pipe was still burning.

I think the pipe got overlooked when it came to the rebalance.

**Comment by Mitchs98** [comment]
Cig addiction is still very much an issue. Smoked last night for roughly 20-30 seconds and was addicted. Put it out and not long after symptoms kicked in. I really don't feel nicotine is that abusable to have such heavy handed addiction symptoms or chances.

**Comment by Fox-McCloud** [comment]
Going to close this. Ethanol is no longer addictive and the addiction fix means if you chainsmoke you won't get a nicotine addiction.

**Pull request closed without merging**
