### PR TITLE
Gives wizard the ability to buy more SM goodies

### PR DESCRIPTION
**Pull request by KingSuperBOB**
Adds Oblivion Halberd and Oblivion Gloves to wizard spellbook

## What Does This PR Do

Gives the wizard SM gear without Oblivion loadout
## Why It's Good For The Game

Allows for further customization of wizard loadout, for actual full SM immunity while running the Halberd youd need a total of 6 points spent
## Testing

Pressed compile and run, spawned the Halberd and gloves then bonked SM
## Changelog
:cl:
add: Added Oblivion loadout Halberd and gloves to Wizards spellbook
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
Really not a fan of giving the Wizard this outside their kit. The kit as a whole is the gimmick that allows for the powerful equipment, seeing it able to be brought in outside of it feels like it'll be a balance nightmare (and yes, I know I'm saying balance about wizards).

**Comment by KingSuperBOB** [comment]
In all fairness I never expected this to be merged, just made it in like 5 minutes after someone told me WYCI.

**Comment by matttheficus** [comment]
The Halberd should never be obtainable outside of the kit. Period.

**Comment by farie82** [comment]
The balance team voted against this PR for the following main reason:
- you want the SM gimmick you commit to the gimmick hard.

This PR makes it too easy to perform the gimmick, taking away the interestingness of it. You can perhaps try again once you've spoken to both the design team and balance team on how to get this idea changed so it can be approved. For now I'll close it

**Pull request closed without merging**
