### PR TITLE
[READY] Gamma armory redecoration

### PR DESCRIPTION
**Pull request by lass9030**
**What does this PR do:**
Changes the equipment in the Gamma Armory shuttle.

- 3 Pistols and their mags have been replaced with 3 Enforcers and 3 mags.
- Rocket launcher and rockets replaced with 3 LWAP Snipers.
- LWAP Snipers replaced with 3 NT Sabers and 3 additional mags.
- Durand and charging station replaced with a loaded gygax and 2 sets of Swat suit, helmet, boots, hailer, and telescopic shield.

Loaded Gygax now comes with taser and LMG, instead of taser and flashbang.

**Images of sprite/map changes:**
gamma3

**Changelog:**
:cl: Alonefromhell & Spartan
balance: Gamma armory equipment changed.
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
Not sure how I feel about the removal of the LWAPs and the Durand. The Gamma Armoury is the only way to actually get to play with the LWAP.

**Comment by Ty-Omaha** [comment]
The gamma armory shouldn't have the majority of it's things be what the station can easily obtain on its own

**Comment by Citinited** [comment]
Why have you changed this? Was the equipment out of date or something?

**Comment by Denthamos** [comment]
Gotta agree with Shadey and Ty.  The armory should not contain what is already easily available by the crew.

Replace the auto rifles with the NT Saber SMG's and mags, and the immolator lasers with the LAWP snipers I would say.

**Comment by lass9030** [comment]
I'll take the suggestions up with spartan. Expect updates around friday. Until then DNM.

**Comment by Decemviri1** [comment]
This is a major nerf of the gamma armory. Missile launcher, mech and LWAPs should be returned. AEGs should be replaced with the NT laser carbines and ammo.

The gamma armory represents the last resort (before code Delta) for a crew against an existential threat to the station. We should not be nerfing it.

**Comment by lass9030** [comment]
Updated.

**Comment by Citinited** [comment]
You still haven't answered my earlier question as to why you're changing these @lass9030

**Comment by lass9030** [comment]
@Citinited This is originally Spartans idea, im simply helping him implement it.

**Comment by Citinited** [comment]
@lass9030 Fair enough!

**Comment by Shadeykins** [comment]
Definitely like the changes, but e-shields are still weird given that they're technically a syndicate item.

**Comment by Decemviri1** [comment]
E shield is syndicate tech and would stick out like a sore thumb. 

Still think the AEGs (station tech) should be replaced with the new Laser Carbines (NT unqiue weapons).

Additionally the use of a Gygax over a Durand still makes no sense. Gygax are general issue security mechs. Multirole platforms for average threats. Not Code Gamma emergencies. It should remain a lethal Durand with the charger in place (because science may well be lost by the time Gamma is called)

I get that the idea is to let admins feel comfortable calling Gamma more often but that's no good if it's stripping the use and utility out of it. The Gamma armory definetly needed an update and I think some of the changes are good (Sabre/Enforcer) but that Durand combat mech is a tide turner. A Gygax is not.

**Comment by Denthamos** [comment]
At this point it may be best to close the PR, do some discussion regarding the changes and what items should be removed/added, and then put the PR up again the idea is finalized.  And like Shadey/Dece said, syndicate tech has no place in gamma considering its coming from NT and central command.  It makes sense for deathsquads because _no one survives the deathsquad to report syndicate tech usage_ but not so much for the gamma armory the crew would use.

**Comment by Spartan6** [comment]
A gygax will happily turn the tide of a conflict and is a lot more mobile and able to respond to emergencies.

It is not a case of one security mech is better than the other, both have strengths and weaknesses.

The shield stuff makes sense, teleshields it is.

**Pull request closed without merging**
