### PR TITLE
Adds office door button to magistrate's office

### PR DESCRIPTION
**Pull request by dovydas12345**
**What does this PR do:**
I missed the magistrate's office when adding the buttons to command member's offices. So here it is!

**Images of sprite/map changes (IF APPLICABLE):**
MagiButton

**Changelog:**
:cl:
add: Adds office door button to magistrate's office
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
image

**Comment by variableundefined** [comment]
@dovydas12345 Conflicts, can you fix?

**Comment by dovydas12345** [comment]
I'll do it later.

**Comment by dovydas12345** [comment]
I just realized I did it incorrectly and messed everything up... Yay!

**Comment by dovydas12345** [comment]
I think I'll just close this since I didn't change 428 files and well... I messed everything up.

**Comment by variableundefined** [comment]
Approval still stands. So just ping me when you make a new PR to replace this one.

@dovydas12345

**Pull request closed without merging**
