### PR TITLE
Fixes missing ironsand sprites

### PR DESCRIPTION
**Pull request by Birdtalon**
Iron sand sprites were not considered within https://github.com/ParadiseSS13/Paradise/pull/9716 when creating a new plating.dmi file.

This PR moves the ironsand variants into their own .dmi and points the class towards it.

Fixes https://github.com/ParadiseSS13/Paradise/issues/9802

🆑 Birdtalon
fix: Iron sand icons now render correctly.
/🆑

### CODE REVIEW

**Comment by Birdtalon** [comment]
Just need to check out why some icons have been touched here which I haven't intended to.

**Comment by variableundefined** [comment]
Factors byond your control.

**Comment by Birdtalon** [comment]
I am byond words... Sorted now. Icondiffbot seems to not show the icons properly but you can pull the new ironsand.dmi and check.

**Comment by SamHPurp** [comment]
Welp, home soon anyway and can help then

**Pull request merged**
