### PR TITLE
Fix Windoor at NSS Cerebron Arrivals Security Checkpoint public access

### LINKED ISSUE #22434: Windoor at NSS Cerebron Arrivals Security Checkpoint is public access
**Issue Description**:
The windoor at NSS Cerebron Arrivals Security Checkpoint is public access

**What did you expect to happen**: 
I believed that I, as the lowly assistant I was, would simply cause a red light to flicker when I tried to open the windoor

**What happened instead**:
The windoor opened, I could freely enter the security checkpoint

**Why is this bad/What are the consequences**:
It allows anyone to easily enter and rob Arrivals Security Checkpoint on NSS Cerebron, and I do not think it is intended by the coders or by Nanotrasen

**Steps to reproduce the problem**:
Go up to the windoor at NSS Cerebron Arrivals Security Checkpoint as anyone not supposed to have access, then open it

**When did the problem start happening**:
N/A

**Extra information**:
N/A

### PR DESCRIPTION
**Pull request by Fluffyzack21**
## What Does This PR Do
 Fixes the access to the windoor so no Assistants don't got access to the checkpoint, 

 fixes #22434

## Why It's Good For The Game
 People shouldn't be able to easily break into sec like this

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/98861947/94d5198c-9155-44c6-9fe4-bf93550663f9

## Testing
 I spawned myself as a Assistant and checked if you they access and they don't, But security officers do

## Changelog
:cl:
fix: Fixed the door access in arrivals sec checkpoint on NSS Cerebron
/:cl:

### CODE REVIEW

**Comment by Jaredw224** [comment]
Yeah I did

**Comment by Jaredw224** [comment]
Updated again, Since I missed placed a few things

**Comment by Henri215** [comment]
Are you fixing it in another place too? If yes update the description

**Comment by Fluffyzack21** [comment]
> Are you fixing it in another place too? If yes update the description

No I just fixing just the one

**Review by warriorstar-orion — APPROVED** [review]
I get what happened here. If you look at the departures checkpoint, there's a public access windoor and a security access windoor. The windoor you removed, that was on the same tile as the table, had a pixel offset, so it was supposed to "be" on the lower tile. I bet if you were to check on master you'd have assistant access to the lower windoor, but wouldn't be able to climb over the table. This is horrible.

If you want to be consistent with the Warden's office and Departures Checkpoint, you could add an additional public access windoor facing south to the Arrivals Checkpoint. I... don't think it matters all that much, considering no one even mans them.

Otherwise the actual code changes LGTM.

**Review by Aylong220 — APPROVED** [review]
How the hell do you do that?

**Review by DGamerL — APPROVED** [review]
LGTM, might wanna thinkg about warrior's proposal

**Review by lewcc — APPROVED** [review]
Should probably be fine at this point.

**Pull request merged**
