### PR TITLE
Makes NT-Rep and Blueshield offices smaller, adds a maint tunnel above tech storage

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
add: The Blueshield and NT-Rep have been resized.
add: There is now a maint tunnel above tech storage.
/:cl:

2016-07-05 20_45_05-greenshot

### CODE REVIEW

**Comment by Keilden** [comment]
Now the NTrep and Blueshield can make a false wall to the tunnel and ERP!

**Comment by Da-Dman234** [comment]
I was kinda always under the impression that you weren't supposed to be able to be in maint 100% of the time, and this seems to really take away from that. I'm tired so I won't go into balancing details cause it'll probably end up being incoherent, but what exactly is the point of adding this other than to immediately jump back into maint? Not only that but it's a single tile wide line.

**Comment by IcyV** [comment]
@Da-Dman234 There's been a big switch into having ~20% of the station be maint tunnels with access to them from virtually everywhere. Similar to Metastation.

**Comment by FreeStylaLT** [comment]
Erhh, I've never been a fan of single-tile maint hallways with nothing really in them. Though, the newly shaped offices are more compact, neat.

**Comment by Norgad** [comment]
@Da-Dman234 
@FreeStylaLT 
There is really no way you make that make the maint hall any wider, without making the offices cramped rather than cozy. I _can_ however, make it look a bit nicer with some decoration. Also, what @IcyV said.

**Comment by Norgad** [comment]
Screenshot updated. Now it doesn't look as boring as it did, and it isn't a good shortcut unless it's been cleared up beforehand.

**Comment by Davdichan** [comment]
@Da-Dman234 they are supposed to be literal tunnels, like the Jefferies tube in Star Trek that are cramped and avoided by the regular crew when ever possible but still used to make repairs or alternate routes when main passages are in danger. Making them wider, functional hallways is pretty much defeating the purpose.

**Comment by FreeStylaLT** [comment]
Yes, I know that, I was more referring to the fact it has.. like nothing in it. Not even that many pipes. Maint, imo, should either be tiny hallways connecting more open, seemingly long-abandoned areas with looties or hallways that serve an actual function (pipes, cables), I guess this one fits that now better than before with that extra fluff

**Comment by Earthdivine** [comment]
I kinda don't like it. There's no much reason to have this there and makes it real easy to jump between tunnels for this part of the station. If you take a look at the tunnel set up, you still CAN, but you also pass through area's people are often at work at or populate.

**Comment by Lady-Luck** [comment]
A good antag buff that doesn't buff science antags. :+1:

**Comment by Fox-McCloud** [comment]
Don't much care for this, TBH.

**Comment by Belario** [comment]
:+1: Those two offices have been freakish oblong for way too long.

**Comment by Lady-Luck** [comment]
@Belario brings up a good point. As someone who plays NT Rep, a smaller office would actually be fantastic because as it stands, people can't see me through the windows when I'm at my desk.

**Comment by Ar3nn** [comment]
So your main point to having this is to have a maintenance run by these offices. Yet, they have no access through their office into it. I'd say add doors, but locked to the same access as the front. As a NT guest on the station, it'd make sense for at least the Rep office to have a second entrance.

**Comment by Norgad** [comment]
@Ar3nn Good idea! I'll add that soon

**Comment by Plotron** [comment]
Blueshield's office is just the right size, it feels!

I have mixed feelings on NT Rep's office, though... This one here doesn't leave much room for DIY improvements.

They definitely feel cozy, though.

**Comment by Taaketa** [comment]
I don't like it. This give that particular area of maint 3 entrances within close range of each other and with the recent Incinerator maintenance change. There is already a maitenance connecting Engineering to the bottom side of cargo maint.

This one now makes it relatively easy to move one from large section of maint to another section of maint on the station. I'm not sure that is replicated anywhere else on station. Pretty nearly all the large areas of maint require you go through a camera visible space for a reasonable amount of tiles before you can re-enter maint.

This change means someone can move from science / medical maint (Which is stupidly huge already) to Engineering/South cargo maint with relative ease. The wooden barricades aren't really a good explanation to say this would discourage people. If I'm a sec officer, am I gonna arrest someone for taking down two barricades in an area that is suppose to have access for someone to walk through? Nope. Just seems like a very direct buff to all those antags that like to hide in maint.

**Comment by Belario** [comment]
Just one teeny little nitpick, everything is in perfect symmetry except the disposal outlets.
It'd look ever so slightly better if one were flipped below the other window.

**Comment by Ar3nn** [comment]
@Norgad don't forget to update the OP screenshot or just make a new one (updating the OP is more generally smiled upon)

**Comment by Norgad** [comment]
@Ar3nn I already do.

**Comment by Fox-McCloud** [comment]
going to go ahead and close this due to the overwhelmingly large negative feedback.

I'll also add this:

- You can have too many maintenance paths
- This makes the offices really tiny 
- functionally this is pointless with the wooden barricades

**Comment by AceMcLazer** [comment]
Damn. I was really hoping for this to merge.

**Comment by Ar3nn** [comment]
@Fox-McCloud people actually wanted the NT Rep's office a bit smaller, and the Blueshield should almost never be in their office, anyway, they should be doing their job. The barricades were in response to feedback and could've been asked to be removed, probably. Just some thoughts.

**Comment by Lady-Luck** [comment]
@Fox-McCloud Yes, as someone who plays a lot of NT Rep, I legit want my office to be smaller. IAAs have a nice, huge window that people can see into, and they get a lot of business. You can only barely see the NT Rep at the far end of your screen if you are right up against the window. NT Reps have privacy shutters already if they don't want to be seen.

Functionality over size any day.

**Comment by Norgad** [comment]
Okay, so my internet is back. I'm working on a new Pr which shrinks the offices but makes the area south of the offices much more suspicious to be in.

**Comment by Lady-Luck** [comment]
@Norgad Can you also give the NT Rep office 4 windows instead of 2

**Comment by Norgad** [comment]
@Lady-Luck Sure fam

**Pull request closed without merging**
