### PR TITLE
Removes duplicate (PP) from ahelps/mhelps

### PR DESCRIPTION
**Pull request by Kyep**
Fixes a bug causing (PP) to show up twice in ahelps/mhelps. No CL as not player-visible.

### CODE REVIEW

**Comment by LightFire53** [comment]
Unacceptable. How is this supposed to help me power game? :-1:

**Comment by Kyep** [comment]
@LightFire53 Well, nobody's saying you can't click the one (PP) link twice.

**Comment by Necaladun** [comment]
Seriously how long has this been here because i never noticed until now

**Comment by FlattestGuitar** [comment]
It's not like I look at ahelps anyway. Meh.

**Pull request merged**
