### PR TITLE
Fixes xray machines

### PR DESCRIPTION
**Pull request by MarsM0nd**
The Xray machine did only check if what passes through would be classified as dangerous, but not if the contents of it would be, which kinda is the job of an xray machine. Now goes through the contents, and the contents of the contents ..., until either a dangerous object is found, or everything was checked.
:cl:
tweak: Xray machines now have xray vision, and check contents of an item, instead of just the item.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
You can use `getAllContents()` for this.

**Comment by taukausanake** [comment]
Wait, what is this? Some airport security screening machine? I've never seen it before

**Comment by MarsM0nd** [comment]
Currently not placed anywhere, can be spawned in by admins, but only works as a weapon distinguisher. And yeah, it's supposed to be just like an airport security screening machine.

**Comment by taukausanake** [comment]
We should make it constructable and/or orderable for maximum security

**Pull request merged**
