### PR TITLE
Changed TComms Traffic Control to use POST for NTSL code

### LINKED ISSUE #2775: Telecomms compiler fails to upload for certain scripts
Uploading my script caused the local html to refuse to upload it.
Here
* Line 58 is the `window.location = ` that pushes the script to the (real game) server. From fiddling with deleting parts of the script, I think it flips out if the script is over a certain length.

Going to naturally assume related to #2433. Can upload the script somewhere if need be for testing.

### PR DESCRIPTION
**Pull request by monster860**
This allows NTSL scripts to be MUCH longer. Now we can have even more features in our telecomms scripts! Fixes #2775

### CODE REVIEW

**Comment by tigercat2000** [comment]
Hm. If you can use POST for byond:// requests, wouldn't a less hacky solution be to use [`jQuery.post()`](http://api.jquery.com/jquery.post/)?

**Comment by monster860** [comment]
Oh, this has jQuery? Fun shit. The HTML didn't show evidence of jQuery usage.

**Comment by monster860** [comment]
Personally, I'd call this a fix, because I doubt having the character limit because of GET be intended.

**Comment by tigercat2000** [comment]
@monster860 Acttually I don't think it has jQuery, and the datum browser doesn't currently let you use bare head references... this'll work, for now.

**Comment by Crazylemon64** [comment]
:D

**Comment by tigercat2000** [comment]
Oh, @monster860, could you please put "fixes #2775" in the OP, so the issue is closed when this is merged?

**Comment by monster860** [comment]
Done

**Comment by Tastyfish** [comment]
jQuery is in nano/js/libraries.min.js, nano itself actually uses it extensively, although $.post() just doesn't seem to work at all in byond for whatever reason.

**Comment by tigercat2000** [comment]
@Tastyfish Yes, but it's not included in the datum/browser system by default, and with the way it's scripts work, you can't easily add it

**Comment by Tastyfish** [comment]
@tigercat2000 Around line 167 (160 in master version), you'd add `popup.add_script("libraries", 'nano/js/libraries.min.js')`

**Comment by monster860** [comment]
Well, the code I made works.

**Comment by Crazylemon64** [comment]
I take it this means you are ready to merge?

**Comment by Tastyfish** [comment]
Yeah, I guess jQuery is just micromanaging the URL in ajax()/post() in some weird way that's incompatible with byond (or IE8). A shame. It does work with my comically long scripts though. :+1:

**Pull request merged**
