### PR TITLE
Swings the axe on modular consoles

### PR DESCRIPTION
**Pull request by AffectedArc07**
# Preamble 
This has been discussed internally and already has approval from all of the heads, as well as other maintainers. Please avoid salting and arguing in the PR description. If you say `Improve, dont remove`, then you will be told yourself to improve the feature. 

## What Does This PR Do
This PR swings the axe into modular computers. The TLDR is that they have not been maintained, are a pain to work with, and not user friendly to use ingame.

Modular consoles have not been maintained since they were added. They are missing half of the standard console apps, and are a nightmare to work with code side. For something called a `modular` console, they are the least modular thing from a code POV. If you want to edit one singular console in the world, you have to update 2 sets of nano templates, 2 interaction procs in DM, in 2 separate folders with structures which arent similar at all. It is exhausting to work on them, and there is a big reason why people flat out refuse to touch these.

The only benefits these bring are also drawbacks, for example, the HoP being able to make ID changes anywhere or the captain having a comms console anywhere. It all seems nice on the surface, until you have people running around maints rapidly calling the shuttle while security cant do anything about it, or a traitor flying round space opening ungodly amounts of clown slots.

## Why It's Good For The Game
Removes unmaintained features, also greatly simplifies the TGUI pipeline by knocking out about 20 templates that would need converting.

## Images of changes
Mapdiffbot will handle these. Its mostly just replacing consoles with appropriate ones (EG: Bridge one replaced with an ID console, engineering one replaced with a cam monitor on Meta & Delta, tcomms being re-arranged to move the relay around, etc)

## Changelog
:cl: AffectedArc07
del: Removed modular consoles
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
improve not remove

**Review by Kyep — APPROVED** [review]
Can confirm:
- From a contributor POV, modular computers (laptops/tablets) have a ridiculous amount of duplicated code/templates which is a massive time sink for any coder (myself included) who works on computer functionality
- From a balance POV, many of the things that you can do with modular computers (see examples in PR description) are highly annoying to deal with
- From a technical POV, modular computers make our codebase harder to maintain, and are a bunch of bloat we do not need
- From a head/maint POV, modular computers very much need to be axed, as they're unfixably bad given the above concerns.

For all these reasons, this removal is necessary.

**Comment by Balthusdire** [comment]
Toss em out. I have almost never seen them used and keeping a crappy system around just because is bad.

**Comment by Muhdi345** [comment]
The only reason I used modular consoles was for the supermatter console. Now I haven't checked the circuit lathe for a loooooooong time but are they able to be made in there now?

**Comment by AffectedArc07** [comment]
> The only reason I used modular consoles was for the supermatter console. Now I haven't checked the circuit lathe for a loooooooong time but are they able to be made in there now?

Yep. Was added in https://github.com/ParadiseSS13/Paradise/pull/13955

**Comment by kenken244** [comment]
also from a thematic point of view, portable computers didn't exist during the 80s and don't fit our retro futuristic theme. delete them. replace them with pda cartriges if needed

**Comment by shawnhind** [comment]
I am extremely disapointed that portable ID computer is no longer possible.  If someone were interested in refactoring this so that computers and modular computers could share their UI code, would that be something that would be considered?

**Comment by Kyep** [comment]
@shawnhind Since #14291 Captain/HOP can access most of the functions of an ID computer at any department management console. The ones that always require a full ID computer, require that for balance reasons. So portable ID computer laptops are no longer needed.

**Comment by taukausanake** [comment]
A console-less station would be an interesting take I feel. A smaller station that has a more open or less personalized layout. You use a tablet or other handheld computer for your console needs and portable machines for other tasks. Maybe something new can be made in the future. Am kind of disappointed to see the laptops go at those were interesting on their own

**Comment by procdrone** [comment]
This makes me sad. Gone are the days I could load up comms/id/alert apps into my laptop as a captain, and go out of the bridge to interact with crew, service and other departments while maintaining basic command capabilities.

Although im not going to defend it, as i agree the execution of laptops/modular consoles is kinda spagete

**Pull request merged**
