### PR TITLE
Caching

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds caching to crew monitors (https://github.com/Baystation12/Baystation12/pull/10481). Updates every five seconds. This should give antags more time to disable suit sensors if there's a Robocop watching the monitor around the clock. 
2) Adds caching to power monitors. Only affects AI's when they have to select a power monitor through their subsystem and the PDA power monitor cartridge. This cache only updates when a power monitor is deleted, created or loses power.
3) Adds caching to APC's. Only affects the power monitor computer. Updates every ten seconds.
4) Adds caching to air alarms. Only affects central atmospherics computer. Updates when an air alarm is created, destroyed or the alarm level is changed.
5) Cloning computers now update after scanning.

Overall, this should help cut down on lag. Whereas previously the list of apc's, air alarms, etc. was being updated every tick when someone had a monitor open (which could result in the list updating 10x every tick if ten different monitors are open), it'll now only update once every X amount of seconds as the data is saved in a central repository, if anyone even has the window open.

Part of the NanoUI improvements requested in https://github.com/ParadiseSS13/Paradise/issues/1623.

### CODE REVIEW

**Comment by Markolie** [comment]
Actualy, going to re-do the way air alarms are cached. Hang tight.

**Comment by TheDZD** [comment]
Ready to be merged then?

**Comment by Markolie** [comment]
Sorry - haven't had the chance to do a final review. Should be ready in like 30 min - will let you know.

**Comment by Markolie** [comment]
Ready. Better caching's definitely possible (instead of looping through the entire machine list and refreshing all air alarm data, only update the respective item in the list of the air alarm being updated) but this is already a major improvement.

**Comment by FalseIncarnate** [comment]
This might be outside the scope of the PR, but could you make the cloning consoles properly update when scanning people? The past few times I've gone to clone someone, I've needed to click the console a second time to update the NanoUI to see whether or not they were scanned at all.

**Comment by Markolie** [comment]
Done.

**Pull request merged**
