### PR TITLE
Removes swarmers

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Removes:
- Swarmers as a mob
  - The main point of this PR
- Swarmer cardboard cutout
  - Makes sense to
- Swarmer lavaland ruin thing
  - This also makes sense to, and I am also 99% sure this is riddled with GC problems, but citation is needed there

## Why It's Good For The Game
Swarmers suck. No one ever fixes the damage they create, and tend to just cause enormous amounts of suffering for the crew with them consuming vital assets such as R&D, and with the luck of the round, you'll then get terrors 30 minutes later. 

Aside from being legal grief machines, I see no real point in them other than "piss people off", which I don't feel is an appropriate atmosphere for the game.

## Changelog
:cl: AffectedArc07
del: Removed swarmers. Please file your complaints in /dev/null
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
Also you can't turn off prompts for them as a ghost. 😱

**Comment by procdrone** [comment]
yes please, swarmers are the worst

**Comment by Mitchs98** [comment]
Literally one of the best PRs of the year. Thank you, they won't be missed.

**Comment by ppi13** [comment]
Player controlled swarmers, is by far the least fun, most obnoxious, and annoying antags to fight against.

The lavaland ruin is also a pain in the ass that needs to be dealt with unless it will bite you in the ass later.

However, the swarmer beacon could be used to replace the swarmer event, as the beacon on station is the only time you will ever find it enjoyable to fight swarmers.

**Comment by TORE01** [comment]
YEEEEES
Please do it.

**Comment by ItsMarmite** [comment]
Not a fan of the Lavaland ruin being removed personally, Lavaland swarmers tend to mix Lavaland up a little.

But god, please remove them being a station thing.

Its AWFUL.

**Comment by Pckables** [comment]
Been a long time coming.
Player-controlled swarmers gameplay completely consists of "Grief important machinery before the vents are welded and then die to lasers."
Thing is, I do remember swarmers being more dangerous and fun back in 2018, when overall crew and security were fewer and not as robust, resulting in an actual back-and-forth fight; 
but after years of combat updates and better players, swarmer's don't hold up in any capacity. Their lifespan outside a vent is too short to do anything but hide or grief RnD/Cloning.

**Comment by hal9000PR** [comment]
Swarmers are great! I !!Love!! Swarmers. They are like allow me to take a break from the game periodically and randomly. 

My favourite combat moment with swarmers is when they start stunning you so you get eaten by terrors. Even though they aren't supposed to interact with living things. 

My favourite method for countering swarmers is "cryoing" it works every time. (Also works against shadowlings)

Blessed pr. o7

**Comment by matttheficus** [comment]
I personally wouldnt mind seeing them as a midround NPC threat. The Swarmer Beacon on Station was probably the only time I've ever enjoyed seeing them.

Otherwise, theyre just GriefBots on Station or literal cryo-bait on Lavaland.

**Comment by Samman166** [comment]
Amazing PR I don't think anyone will be sad to see swarmers go. One suggestion though that maybe should be done in a different PR is to compensate the removal of swarmers by making morph events more common, it's a shame they turn up so rarely after the rework of them.

**Comment by nukularpower** [comment]
sucks to see all the flavor getting PR'd out of the game one bit at a time with nothing being added to replace it.

**Comment by hal9000PR** [comment]
> sucks to see all the flavor getting PR'd out of the game one bit at a time with nothing being added to replace it.

Garbage has a "flavour" doesn't mean it's good

Also, I'm extremely sorry that the unpayed  coders have only reworked 2 major antags this year and they aren't doing more, because we all have an abundance of time to add 1000+ line features. And the maintainers have the time to review it. 

Your bitching shows how little appreciation you have for the contributors.

**Comment by warriorstar-orion** [comment]
In what respect are swarmers griefing that a more destructive midround, e.g. blob or terrors, isn't? Compared to blob or terrors, swarmers are mechanically prohibited from causing lethal damage or eating anything that could compromise the structural integrity of the station. Is it that they're less likely to be spotted before they cause that amount of damage? Could that be addressed by adding a biohazard alert for them?

I agree that swarmers being coordinated enough to take out R&D and the servers simultaneously causes a problem for the station, but that's vacuously true—any antagonist destroying R&D and the servers simultaneously causes the same problem. If it's too easy to destroy the R&D servers without anyone noticing, despite them being connected to multiple devices on the station, maybe we should make it easier to notice when the R&D servers have been taken offline?

**Comment by dearmochi** [comment]
There are now two maintainer objections to this pull request. In consequence, I will have no choice but to close it.

Complete removal seems extreme when TG swarmers exist and are much more reasonable in the gameplay sense, while remaining thematically similar. It would be good to start discussion or make a formal design document on how ideas could be drawn from their version so that ours can be improved to make it a better experience for both sides, be it crew or swarmer.

Additionally, I believe the leadership was not consulted (at least not the maintainers) about this pull request which only makes it look like a knee-jerk reaction rather than a reflected upon decision.

**Pull request closed without merging**
