### PR TITLE
Removes the mysterious door to space in the prisoner shuttle dock: Mapmerge edition

### LINKED ISSUE #4177: There's a door in the labor shuttle dock that leads directly to space
https://gyazo.com/4a959717a9332712e21068516910b818

How did this even happen? Why is it there? Who put it there?

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
Fixes #4177

Now with 100% more mapmerge

### CODE REVIEW

**Comment by LittleBigKid2000** [comment]
I shouldn't try to do this sort of thing at six in the morning on a monitor that I can't clearly see because I'm nearsighted and don't wear my glasses while on my computer.

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, mate, I think you added some merge commits there.

**Comment by LittleBigKid2000** [comment]
I saw them, but do they really affect anything?

**Comment by CrAzYPiLoT-SS13** [comment]
I don't think they affect anything, it's just not good practice to leave them in AFAIK. Don't take my word for it, though. Also, did you remember to add a wall in place of the door?

**Comment by LittleBigKid2000** [comment]
I guess I'll make ANOTHER pr and hopefully it'll be perfect this time. After that, I'm going to bed.

**Pull request closed without merging**
