### PR TITLE
Syndicate Uplink Icon Update

### PR DESCRIPTION
**Pull request by Dave-TH**
**What does this PR do:**
This PR replaces this really terrible syndicate uplink background with /tg/'s cool snake background image!

**Images of sprite changes:**
newS

**Changelog:**
:cl:
imageadd: The syndicate uplink is now complete with a new spooky background. Very neat!
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
hiss

**Comment by AzuleUtama** [comment]
I do love their Syndicate icon. Yes please!

**Comment by Dave-TH** [comment]
Note: Because using the .svg version in JS would require bringing in another dependency I've used a .png version of the image. If any JS masterminds have ideas about making the .svg work without importing anything extra I'd love to hear it! The consequences for using the .png is the scaling is a bit less pretty than it would otherwise be.

**Comment by AffectedArc07** [comment]
@Dave-TH Isnt the NT logo in the background an `svg`, so wouldnt you be able to re-use that bit of code to get the syndicate thing in?

**Comment by Dave-TH** [comment]
No, the NT logo is set in a .less file whereas the syndicate logo is set using JS. .less can handle a .svg cleanly, to do it in JS we'd need another library which I hesitate to bring into the project.

**Comment by AffectedArc07** [comment]
Understandable

**Comment by Dave-TH** [comment]
That is a .svg file. Which is set in the background of the default browser in .less
As I said above, .less has the tools to load the .svg without a problem.
The browser is modified to "syndicate mode" using JS, which does *not* have the tools to load a .svg without problem.
If we wanted to load it we'd need to add another dependency, which I hesitate to do.

**Comment by craftxbox** [comment]
Isnt it possible to do some visibility/display attribute fuckery to have the svg preloaded but invisible?

**Pull request merged**
