### PR TITLE
MAP: Cyberiad, Corp jumpsuits, Engi curtains

### PR DESCRIPTION
**Pull request by tigercat2000**
This PR does the following:
 - Adds a corporate wardrobe to security, equipped with 3
   corporate jumpsuits and 3 corporate caps.
 - Changes the shower curtain on the engineering outpost from a regular
   curtain to an engineering curtain, because we have those now

corporate jumpsuits
corporate jumpsuits on map

engi
engimap

### CODE REVIEW

**Comment by Spacemanspark** [comment]
YES.
YES.
:+1: x :100:!

**Comment by TheDZD** [comment]
For some reason I read that as "Corgi jumpsuits".

**Comment by Fox-McCloud** [comment]
going to :-1:  because of the corporate jumpsuits. Sec already has *TWO* full *matching* security getups that are complete (as in jumpsuit+matching suits+hat).

This isn't a complete, and there's really no reason for there to be three security jumpsuits sets---every other department has a single set of jumpsuits for each job...I don't see any reason why security needs *three*.

Not only this, these are available from cargo, if players absolutely want to order them---and I hardly see sec a myriad of sec players lining up just to get them, so I question just how many players *really* care about them.

Even Bay's maintainers+coders told their community no to more sec jumpsuits.

**Comment by Fox-McCloud** [comment]
Oops, wrong button!

**Comment by tigercat2000** [comment]
I'm going to just go ahead and stay out of this, I made this PR for the forum's benefit, I don't feel very strongly for or against corporate jumpsuits.

**Comment by Spacemanspark** [comment]
If so many players like them, then why does it matter?
Put one of the new sets in the cargo thing, not too many use it anyways, where as before the update to Cargo, a lot of people wore the corporate jumpsuits. We're not asking for any new jumpsuits, we're asking for what we had before. The new jumpsuits look just like the default ones, just with a grey bottom.

**Comment by Spacemanspark** [comment]
Ponies has earned his brownie points.

**Comment by Spacemanspark** [comment]
And TC, of course.

**Comment by ZomgPonies** [comment]
Forum people want it. Remove the other uniform that looked similar to this in another PR.

**Pull request merged**
