### PR TITLE
Fixes #3167, Gives NT rep their own stamp instead of stamping as CC

### LINKED ISSUE #3167: Nanotrasen Representative's stamp marks pages with Central Command Approval
This probably shouldn't happen for kind of obvious reasons.

### PR DESCRIPTION
**Pull request by Ty-Omaha**
Fixes: #3167

I tried to fit the whole word "Representative" on, but it made the text ridiculously skinny and looked ridiculous

jwfqtsuj

asdf

🆑 
fix: NT Rep stamp no longer stamps as Central Command, they have their own stamp now.
/ 🆑

### CODE REVIEW

**Comment by datlo** [comment]
I kinda like the stamp as it is now, the NT rep being a representative of Central on the station.

**Comment by taukausanake** [comment]
I think it looks nice. Yellow and black are their colors aren't they?

**Comment by Kyep** [comment]
There's an enormous difference between the NT rep saying something, and CentCom saying something.
So yeah, they should not use the same stamp.
I'd suggest a blue color for the stamp, but better a yellow one than them using CC's.

**Comment by FlattestGuitar** [comment]
You can forge something as a CC fax using the rep's stamp. 

This is most definitely not a fix, but a balance change and should be treated as such. 

Get out.

**Comment by Ty-Omaha** [comment]
If someone really wants to forge something as CC they can spend the 1 TC for a chameleon stamp. 

With that logic, if the smugglers satchel had infinite space then it would be balance and not a bug fix.

This is something that should have been done when the job was created, but wasn't.

**Pull request merged**
