### PR TITLE
Material datums, Recycler Refactor, and Additional Item Materials

### PR DESCRIPTION
**Pull request by Fox-McCloud**
A port of:
- https://github.com/tgstation/-tg-station/pull/10308
- https://github.com/tgstation/-tg-station/pull/11469
- https://github.com/tgstation/-tg-station/pull/11487

Datumizes Materials

Simply put, converts materials into datums as opposed to relying on the g_amt and m_amt vars for storing how much metal/glass is in an item. Datumizing materials also allows for different types of materials in an item. As an example: plasteel no longer is metal+glass, but metal+plasma. Some other items also have materials in them now (coins contain their base material types, AI circuitboards contain gold, and captain's flask contains silver, for a few examples). Datumizing materials also allows for expansion of features for R&D, Cargo, and construction in the future.

Would really appreciated someone looking over the autolathe section, in particular; it's the one I'm most worried about.

Recylcer Refactor

- Instead of the recycler being based on RNG production of resources, it actually destroys the item and extracts the materials inside the item itself; it's not 100% efficient, but the efficiency can be improved by upgrading the recycler with parts from R&D.

Other things done in this PR

- Removes unused `construction_time` and `construction_cost` vars from objects (everything is tied to design datums now)
- Fixes a few errant numbers for metal/glass amounts on a few design datums

Status
- This has been tested and fiddled with a few times; I can't get it to runtime or notice any odd behaviors with the autolathe or anything else; numbers are correct and update properly.

@Artorp

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Pass II completed.

Need to figure out if construction_time and construction_cost can be removed (ie: they're times/costs are extracted from datums, instead).

**Comment by Fox-McCloud** [comment]
Fixed some improper numbers on the autolathe design datums.

Tested this out; no runtimes or strange behaviors with the autolathe; everything seems to function properly.

**Comment by Fox-McCloud** [comment]
As I suspected, the construction_time and construction_cost vars are no longer used as everything is tied to design datums now; went ahead and axed those vars to avoid confusion, in the future.

**Comment by Markolie** [comment]
LGTM

**Pull request merged**
