### PR TITLE
Xray Gene removed from Genetics

### PR DESCRIPTION
**Pull request by Kepplerx**
## What Does This PR Do
Changes the chance for the Xray Gene to activate to 0.

## Why It's Good For The Game
Genetics Xray comes with too big an advantage, and can literally destroy rounds, especially if given to Sec, or even given out at all. This is something nukies need to pay a lot of TC for, and Genetics can get it for free, this further shows how broken this Gene is. This does not affect the Xray implant, merely the gene, which only really is used in Genetics.

## Changelog
:cl:
tweak: Changed the chance of Xray to activate to 0
/:cl:

### CODE REVIEW

**Comment by Kepplerx** [comment]
I have been notified this will likely collide with Fox's Mutation refactor, so it may not be mergable. That said I think its needed, and can likely change it after Fox's refactor goes through.

**Comment by Kepplerx** [comment]
Changed it, by a good suggestion, so instead of removing the Gene it now changes the activation chance to 0, effectively removing it from Genetics while still allowing Admins and items to use it.

**Comment by S34NW** [comment]
`activation_prob = 0` Is a great way to do it, a shame fox's PR will steamroll this change, but who knows when that will be merged.

**Comment by Kepplerx** [comment]
> `activation_prob = 0` Is a great way to do it, a shame fox's PR will steamroll this change, but who knows when that will be merged.

All credit to @hal9000PR Bubbledumb on that one, not gonna take credit for this, my solution was much longer and worse

**Comment by FreeStylaLT** [comment]
#15529

image

**Comment by Wojz** [comment]
> #15529
> 
> image

Few rounds ago security had their own brig geneticist set up there, mindshielded, shitting out xrays vs like 4 cultists. They also ordered like 4 crates of combat shotguns and slugs "in case it gets big" but that's besides the point and not what killed that cult.

**Comment by MRgaty** [comment]
Perhaps changing it for thermals or some sort of improved vision would be better.
Tbh genetics is kind of a joke right now, dont know if it needs further straight up nerfs.

**Comment by Wojz** [comment]
> Perhaps changing it for thermals or some sort of improved vision would be better.
> Tbh genetics is kind of a joke right now, dont know if it needs further straight up nerfs.

It does need nerfs, because the parts of it that aren't useless are almost all overpowered.

**Comment by MRgaty** [comment]
For sure they are op, but they are also the reason why anyone would sit down 2 hours doing genetics.
If we remove the only thing good bout genetics without giving any other options then why would anyone play genetics?

**Comment by PidgeyThePirate** [comment]
You're making another "nothing" gene which is absolutely the worst thing in genetics right now when combined with the tiny chance of activating that major powers have. I don't care about X-ray itself but this? This does not make me happy.

**Comment by Kepplerx** [comment]
> For sure they are op, but they are also the reason why anyone would sit down 2 hours doing genetics.
> If we remove the only thing good bout genetics without giving any other options then why would anyone play genetics?

Genetics as is is a joke indeed, with very few really useful genes. That said Xray is something that would cost even nukies a lot of TC, so why would crew get it for free? Whenever it actually appears in rounds, its usually considered OP, and most often it doesnt at all.

**Comment by Kepplerx** [comment]
> You're making another "nothing" gene which is absolutely the worst thing in genetics right now when combined with the tiny chance of activating that major powers have. I don't care about X-ray itself but this? This does not make me happy.

I agree genetics needs a rework, that is beside the point, at the moment the must "useful" thing Genetics does is make humanized monkies. That is beside the point however, and not at all a reason for them to have xray, something only very powerful antags have otherwise.

**Comment by S34NW** [comment]
> 
> 
> You're making another "nothing" gene which is absolutely the worst thing in genetics right now when combined with the tiny chance of activating that major powers have. I don't care about X-ray itself but this? This does not make me happy.
PR'ing a major genetics rework is not logical with the Fox PR coming up in the future

**Comment by procdrone** [comment]
Ive always been a person who advocated removal of xray from standard gameplay (make it admin only gene), as its a literal wall/map hack without any downsides, unfun and impossible to counter. It stands in denial of what SS13 should be.

So a good change in my books.

**Comment by Kepplerx** [comment]
> > You're making another "nothing" gene which is absolutely the worst thing in genetics right now when combined with the tiny chance of activating that major powers have. I don't care about X-ray itself but this? This does not make me happy.
> 
> PR'ing a major genetics rework is not logical with the Fox PR coming up in the future

This is first of all not a major genetics rework, it changes one single value. Second of all we are still gonna play this till Fox's PR comes in, so might as well have it as nice as possible till then.

**Comment by S34NW** [comment]
> This is first of all not a major genetics rework, it changes one single value. Second of all we are still gonna play this till Fox's PR comes in, so might as well have it as nice as possible till then.

Apologies, that message was in reply to PidgeyThePirate, who was implying a better solution would be to redo genetics, something not currently feasible considering it would have to be rewritten in the very near future.

**Review by dearmochi — APPROVED** [review]

**Comment by Spacemanspark** [comment]
I'm still traumatized by the days of people using tk + xray + hulk with zero consequences

Xray can die in a fire, honestly

**Comment by Kepplerx** [comment]
> I'm still traumatized by the days of people using tk + xray + hulk with zero consequences
> 
> Xray can die in a fire, honestly

This is a PR born in salt, but made with good reason still. This is a change that could be done to tk and/or hulk as well, but I am choosing not to touch those, as the nerf is already quite large. It is however easy to change the others too, but Fox's PR is coming soon impacting genetics and all.

**Comment by Spacemanspark** [comment]
TK and Hulk are mostly find on their own.

**Review by Kyep — APPROVED** [review]

**Comment by hal9000PR** [comment]
The issue with changing it to thermals is alot of admin/wizard things rely on the gene. Such as, scrying orb. However i would completely support replacing one of the currently empty genes with welding protection/nightvision. So from the genetics perspective xray is replaced with one of those while still maintaining admins ability's to give people xray. 

Also because this power is admin only now it might make sense to remove the genetic instability from it? Just a thought.

**Comment by AffectedArc07** [comment]
We have better PRs for this open, this has 2 maints against, and isnt even a proper remova, just a 0% chance to get it.

Closing.

**Pull request closed without merging**
