### PR TITLE
Removes mapping headache - names sort junctions

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Before:
img

After:
img

### CODE REVIEW

**Comment by SamHPurp** [comment]
Makes sense to do - I do suspect people will be idiots in future re-maps using the wrong thing simply because it has the right name - but I guess worry about that then.

Want to do this for Meta too?

**Comment by taukausanake** [comment]
So how do you deal with multiple instances when working with multiple maps? I hated doing this thing with APCs before they were renamed for their area. Do you do a clean build to clear out the list or something?

**Comment by SamHPurp** [comment]
@taukausanake this list will populate with instances on the opened maps. So if you're working on Meta and you don't want only the meta ones to show.... only open meta. If you open box by accident. Close it and reboot DM.

**Comment by tigercat2000** [comment]
👍

**Pull request merged**
