### PR TITLE
Adding status icons for gamma/delta/epsilon

### PR DESCRIPTION
**Pull request by Kyep**
Changes:
- Display icons for gamma/delta/epsilon alert levels on status displays, instead of just using the standard red alert icon.
- Upon change to blue/green alert, clear the display. This avoids an annoying situation where everyone thinks it is code red/etc because the status displays say it is - even though the actual level has been changed, the displays still show red.

Note:
- The icons in this PR are placeholders. I am hoping a better sprite-maker than I can replace them with better versions. The code should render whatever icons are slotted in correctly, though. Tested locally.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Hell yeah, codersprites bestsprites

**Comment by tigercat2000** [comment]
could you please put the icons in the OP

**Comment by Fox-McCloud** [comment]
@Kyep 

Will need a changelog for this one.

**Comment by Regen1** [comment]
Ready for merge?

**Comment by Fox-McCloud** [comment]
@Regen1 

waiting on sprites.

**Comment by Nienhaus** [comment]
I maded sprites.

**Comment by Kyep** [comment]
@nienhaus Thank you!

@Fox-McCloud Retested after including sprites. Works.

**Comment by Kyep** [comment]
Closing & recreating on new repro.

**Pull request closed without merging**
