### PR TITLE
Moves the oxygen closet in the AI sat airlock

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## What Does This PR Do

~~Title, that fucking oxygen closet keeps fucking moving in the airlock, and I cannot tell you how many times that's happened to me, so tada, it's anchored now.~~
Someone said "moving it is better" so now it's moved, and I agree, it's better.

## Why It's Good For The Game

It's just frustrating, that's all.

## Changelog
:cl:
tweak: the oxygen closet in the AI sat has been moved out of the airlock to facilitate better entrance into the satellite. 
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
> 
> Someone said "moving it is better" so now it's moved, and I agree, it's better.

Who said this out of interest? I think anchoring it would have been a better choice personally, maybe with a name var edit to reflect that.

**Comment by GuiltyNeko** [comment]
> Who said this out of interest?

Mochi.

**Comment by Dafrek** [comment]
> Who said this out of interest? I think anchoring it would have been a better choice personally, maybe with a name var edit to reflect that.

I feel that moving it would be better since if someone opens it, which is admittedly rare, the contents will be sucked out into space.

**Comment by GuiltyNeko** [comment]
> if someone opens it, which is admittedly rare,

I've had to open it OFTEN, as if you ever enter the sat from the airlock, it will ALWAYS move to be on top of the vent, and so the easiest way to deal with it is literally just to open it.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
