### PR TITLE
Mapmerge2

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This PR replaces our map file layout, and replaces mapmerge with mapmerge2. Regular mapmerge seems very intermittent, and hardly works for a lot of users. The maps themselves have no edits apart from a file layout change. 

Example of lesser diff:
image
*This was me covering multiple rooms in closets*

**Changelog:**
:cl: AffectedArc07
tweak: Mapmerge has been replaced with mapmerge2
tweak: Maps are now the TGM format. This means nothing for people who do not make map edits
/:cl:

### CODE REVIEW

**Comment by dovydas12345** [comment]
Nothing to worry about here... Just a small loan of a million lines! 👀

**Comment by AffectedArc07** [comment]
@dovydas12345 It has not been easy for me

**Comment by Ralta** [comment]
Dear God

:scream:

**Comment by AffectedArc07** [comment]
This has been running for 5 hours, I think it broke
image

**Comment by KasparoVy** [comment]
Render THIS

**Comment by Agameofscones** [comment]
Having working with MM2, it's a blessing. Seriously, full steam ahead broslice

**Comment by Ty-Omaha** [comment]
So does it merge automatically or do you still have to run the .bat files?

**Comment by AffectedArc07** [comment]
@Ty-Omaha you still have to run the files, but the new mapmerge actually works properly

**Comment by Aurorablade** [comment]
The old mapmerge actually works properly. I have not had any problems with it myself. Now the conflict fixer people sometimes have issue with.

**Comment by Kyep** [comment]
Is this a one-time change?

Or will map editors have to convert between DMM/TGM before checking in every map edit they make?

**Comment by AffectedArc07** [comment]
@kyep it should be a one time change

@Aurorablade I asked about and a fair few people had problems with mapmerge but not mapmerge2, possibly related to java versions being shit

**Comment by Mitchs98** [comment]
Dear. Fucking. Jesus. Nearly 2million lines of code.

You madman.

**Comment by AffectedArc07** [comment]
ITS NOT CONFLICTED YOU PIECE OF SHITAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by AffectedArc07** [comment]
REEEEEEEEEEEEEEEEEEEE

**Comment by AffectedArc07** [comment]
https://github.com/ParadiseSS13/Paradise/pull/10978

**Pull request closed without merging**
