### PR TITLE
ERT backpack update

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Replaces the backpacks ERT members spawn with, with dedicated ERT versions. Also adds an on-mob sprite to all ERT backpacks.

### CODE REVIEW

**Comment by Markolie** [comment]
@SamCroswell Not sure if this was intentional or not. Probably not.

**Comment by SamCroswell** [comment]
It was.
The ERT backpacks look pretty bad and have no on mob icon.

**Comment by Markolie** [comment]
Ah yes, them not showing on the back is an issue, will fix that. I do think they look better (much better than an ERT leader carrying around a *captain's* backpack: https://camo.githubusercontent.com/664201baf84af03ac7591df4d34fd4d60f8cc5d9/687474703a2f2f692e696d6775722e636f6d2f465066397961682e706e67.

**Comment by Spacemanspark** [comment]
I wish ERT got choices between satchels and backpacks.

**Comment by Earthdivine** [comment]
The backpack makes them look like turtles.

**Comment by Alex6511** [comment]
:+1: The slightly but not fully off-color backpacks have been annoying me so much.

**Comment by Fox-McCloud** [comment]
Yay. :+1:

**Pull request merged**
