### PR TITLE
Refactor pony code

### PR DESCRIPTION
**Pull request by tigercat2000**
This refactors the simple_animal/pony code to use absolute paths and be
less shitty in general

directly in response to #883 because refactoring bad code is better than unticking it from compile.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:-1:

**Comment by Spacemanspark** [comment]
I think the point was to remove ponies in general.

**Comment by tigercat2000** [comment]
"shit code" was the first defense of it

**Comment by ZomgPonies** [comment]
:+1: 

This is a proper PR dealing with an actual issue.

**Pull request merged**
