### PR TITLE
Standardizes Holodeck

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Standardizes the holodeck to be vertically oriented on the Cyberiad.

This shouldn't have been made horizontal to begin with.

The standard orientation for the holodeck has always been vertical.

Generally speaking, Spessmens is better parsed on a vertical (up/down) plane rather than horizontal (left/right); there's some exceptions, but take the bar, for example; it's a vertically parsed section that just "presents" better to players.

This also ensures 100% standarization across all maps in terms of how the holodeck is, which should help @AffectedArc07 quite considerably for mapping standardization.

Lastly, this makes porting holodeck updates from TG considerably easier, as some of those just don't parse/present well horizontally (Kobayahi maru one is awesome and wouldn't really work well horizontally).

Also holodeck "space" program now actually looks like space.

pic:

img

:cl: Fox McCloud
tweak: re-maps the holodeck to, once again, be oriented vertically
add: Holodeck "space" program now actually looks like space
fix: Fixes there being a useless engineering shuttle console on the bridge
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
fixed a couple of errors/omissions.

Also made holodeck space look like real space.

**Comment by AffectedArc07** [comment]
Could we get the pipes to run this way and maybe have a little maint door here?
image

The pipes going through the walls is a bit ehhhhhh

**Comment by AffectedArc07** [comment]
Could be worth also fixing https://github.com/ParadiseSS13/Paradise/issues/13707 in this PR?

**Comment by Carthusia** [comment]
Heh, it just kind of hit me, but anyone who tries to emag the console, now almost immediately gets killed by the holocarp.

Perhaps add a delay to the holocarp spawning so the syndicate agent can get out of the way?

Otherwise currently there is no safe way to do so besides busting in from space to do it.

**Comment by Fox-McCloud** [comment]
There is a delay; their AI doesn't kick in instantly either.

**Comment by Spacemanspark** [comment]
Those doors being misaligned hurts me a little inside, but otherwise I don't mind this.

@Carthusia
Make a false wall into the maintenance area next to the console room and dip out that way. If you're emagging the thing in the first place you likely want to minimize chances of being caught doing so anyways.

**Comment by Fox-McCloud** [comment]
@Spacemanspark that's a mapping error.

**Comment by Carthusia** [comment]
> Those doors being misaligned hurts me a little inside, but otherwise I don't mind this.
> 
> @Carthusia
> Make a false wall into the maintenance area next to the console room and dip out that way. If you're emagging the thing in the first place you likely want to minimize chances of being caught doing so anyways.

Fair enough, though youve now pointed out the doors...god, i cant unsee them, they burn into my brain, is it possible to...align them properly?

**Comment by AffectedArc07** [comment]
Travis failing is not your fault
```
[2020-06-27T16:56:41] Runtime in _logging.dm,46: Cannot read null.log_game
  proc name: log game (/proc/log_game)
  src: null
  call stack:
  log game("EMP with size (0, 0) in area A...")
  empulse(the floor (222,39,2) (/turf/unsimulated/floor), 0, 0, 1, null)
  EMP Pulse (/datum/chemical_reaction/emp_pulse): on reaction(/datum/reagents (/datum/reagents), 6)
  /datum/reagents (/datum/reagents): handle reactions()
  /datum/reagents (/datum/reagents): add reagent("iron", 3, null, 293.15, 0)
  the crazy giblets (/obj/item/reagent_containers/food/pill/random_drugs): New(the pill bottle (???) (/obj/item/storage/pill_bottle/random_drug_bottle))
  the pill bottle (???) (/obj/item/storage/pill_bottle/random_drug_bottle): New(the floor (222,39,2) (/turf/unsimulated/floor))
```

Just re-run it,

**Comment by taukausanake** [comment]
I never liked landscape holodecks. This is so much nicer. Although now that I think about it, square holodeck wouldn't be bad, just not landscape. May explore that in the future

**Comment by AffectedArc07** [comment]
Also extremely minor
image
This being upside down hurts me a bit

**Comment by Fox-McCloud** [comment]
@AffectedArc07 

I know, me too. It's *hard coded* to be that way.

**Comment by Spacemanspark** [comment]
Beat up falseincarnate

**Comment by AffectedArc07** [comment]
Any chance we can get a real ID console back on the bridge? Having an outpost camera monitor seems superfluous when the sec cam monitor can view all the outpost cams anyway (or atleast, I think it can)

*Basically I want to be prepared for when we switch ID consoles to TGUI, and if that happens before modular computers, the bridge wont have a decent ID console*

**Comment by Spacemanspark** [comment]
I can become a permanent makeshift ID console by joining as a civilian and standing in the bridge, taking anyone's ID cards :^)

**Pull request merged**
