### PR TITLE
Glass shards can now cut cables.

### PR DESCRIPTION
**Pull request by Emanthealmighty**
**What does this PR do:**
Allows glass shards to be used to cut wires. This is something to allow people with basically no items in their inventory to work towards getting a spear or cable cuffs by breaking windows and cutting wires. It should be possible. So here it is.

**Changelog:**
:cl: EmanTheAlmighty
add: Glass shards can now be used to cut wires, however, being an improvised tool, there's a chance the wire will be destroyed, becoming unusable.
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
Does doing this with a glass shard prevent shocks like using glass on an electrified grill does?

**Comment by Emanthealmighty** [comment]
> Does doing this with a glass shard prevent shocks like using glass on an electrified grill does?

It doesn't prevent shocks.

**Comment by Breenland** [comment]
I feel like this should have a chance of failing and instead of granting the cable piece, destroy it. Sort of how improvised surgical tools have a higher chance of failure, an improvised cutting implement like this shouldn't work as well as a purpose made one.

**Comment by taukausanake** [comment]
I feel like this needs more of a debuff compared to using wirecutters. Can you give a glass shard a cut-time for snipping it? Glass is sharp but not so sharp that it should be able to cut a wire. I'd imagine you'd have to really go at it to get through the coat and then the actual metal wire inside

**Comment by Necaladun** [comment]
Breen and Taukau's comments are both good ideas there, I'd like to see those - mostly because a lot of wire cutting is just random people being random shits and not actual sabotage.

**Comment by Emanthealmighty** [comment]
> Breen and Taukau's comments are both good ideas there, I'd like to see those - mostly because a lot of wire cutting is just random people being random shits and not actual sabotage.

Cutting wires with a glass shard has a chance of failing.
If you're not wearing gloves, you WILL cut yourself in the process.
If said gloves aren't insulated, there's a very high chance you'll get shocked.

I don't think it'll be necessary to add anything else to it. People can already be random shits and cut wires for the fun of it with wire cutters which are extremely easy to get.

**Comment by Fox-McCloud** [comment]
greytiding is already easy enough with wirecutters; this is going to make it worse.

It's also going to disincetivize security from permabrigging people even more--now, not only do they hhave to worry about someone breaking things; said person may wind up with a spear to boot (and this applies to regular cells too).

Not a big fan.

**Comment by Fox-McCloud** [comment]
For the reasons stated above, we don't think this would be a healthy addition to the game.

**Pull request closed without merging**
