### PR TITLE
Removes Advanced Release Grenade from science.

### PR DESCRIPTION
**Pull request by alex-gh**
**What does this PR do:**
Some reagents do not scale with their amount leading to balance issues when used with this grenade. 
By request from @Spartan6.
"Fixes"? #9912

**Changelog:**
:cl: uc_guy
del: Removed Advanced Release Grenade
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
https://github.com/ParadiseSS13/Paradise/pull/9018 attempted this same thing, was shut down in favor of re-balancing the reagents that do not scale properly (read: at all) without limiting access to these items in the interim.

Let's hope that doesn't occur again here, because absolutely none of the reagents seem to have been re-balanced for scaling since then.

**Comment by DesolateG** [comment]
this was tried once and denied already.

#9917 is the way they wanted it fixed.

**Comment by Crazylemon64** [comment]
Please cite 3 fix PRs as per the feature freeze.

**Comment by alex-gh** [comment]
Having read #9018 I think this PR is an worse idea that I originally thought.
Especially considering you could achieve the same effect with just beakers.

It does not seem like the sky is falling and that this is being abused really badly. So I'm closing this "band-aid" PR in favor of a proper fix somewhere down the line.

**Pull request closed without merging**
