### PR TITLE
Swarmer mini-rebalance and tweaks

### PR DESCRIPTION
**Pull request by ExusA**
**UPDATED**

## What Does This PR Do
1. Swarmers' projectiles are now effective against cyborgs, mechas, and simple bots like EDs and medibots.
2. Swarmers can now disassemble chem dispensers and station turrets. Station turrets that would harm swarmers still can't be disassembled, because the swarmer has to stand still next to it while it waits to disassemble. The turret either has to be off, or non-lethal. Chem dispensers couldn't be disassembled for some reason, despite doing so not causing harm to the crew. They now can be disassembled as usual.
3. Swarmers' resources are now capped at 60 instead of 100, to discourage resource hoarding and remind players to spend their resources.
4. Does NOT add turrets anymore, ignore this.

## Changelog
:cl:
tweak: Swarmers can now deconstruct station turrets and chem dispensers
tweak: Cyborgs and mechas are no longer entirely immune to all swarmer abilities
tweak: Swarmers can now only hold 60 resources at a time.
/:cl:

### CODE REVIEW

**Comment by Qwertytoforty** [comment]
Please no, swarmers are a pain already to deal with. It's neat, but please no.

**Comment by AffectedArc07** [comment]
> Adds a new device that swarmers can construct a simple AI turret
Thats already a no from me

**Comment by TDSSS** [comment]
That does not look like a turret to me. I like the idea of giving swarmers a way to deal with borgs, though.

**Comment by Spacemanspark** [comment]
Swarmers aren't meant to harm anyone tho

**Comment by Deelite34** [comment]
turrets are no no no. ability to deal with synthethics? YES YES YES

**Comment by ExusA** [comment]
Hmm, pretty surprised this is how people feel about swarmers. They're quite, quite broken ATM with tons and tons of hard counters unlike any other antag. Welding vents stops them entirely, ion rifles instakill them, heck, _normal security lasers_ instakill them. With almost every other antag, the crew needs _some_ equipment to deal with them, but all you need for swarmers is a _welder_. Which almost everybody on the station is probably going to have on your average round. They're annoying as crew, and annoying when you're playing as them, because as crew they silently steal useful stuff, and when you're playing as one, it feels like a slow road to eventually dying out. They have no way to, dare i say, """""win""""". It's not a matter of if the crew can overcome them, it's just _when_. Antags that have a set outcome might not as well be in the game, because uncertainty is why antags exist anyway. Which is what I was at least _aiming_ to add, some uncertainty outside of the usual "the RnD server is gone, toxins is gone, scichem is gone, elecmaints is gone, swarmers are dead" cycle which INVARIABLY happens on the rounds swarmers appear in.

**Comment by ExusA** [comment]
(all of that being said, just gonna cut the turrets and leave the projectiles, which seems to be the general feedback)

**Comment by ExusA** [comment]
@Spacemanspark Probably should have mentioned, the turrets would fire disabler beams.

**Comment by Cocacolagua** [comment]
To clarify on what was said above regarding swarmers durability, they actually don’t get one-shotted by ion rifles (even though they should)

**Comment by Qwertytoforty** [comment]
They really dont get as hard countered as people think. They replicate with ease, unlike terrors / xenos, all swarmers are the same, if one is alive, it can reproduce. It destroys whatever it finds in 15 seconds or less. They can eat _reinforced walls in seconds._ Even if you weld all the vents in science, they will go through the walls in medmaints to eat the servers. They are not fun to fight, and this PR will make it less fun

**Comment by Cocacolagua** [comment]
The reason people hate swarmers is that, unannounced, they can eat one-of-a-kind machinery, or it’s replacements quite fast, examples of these include: research and development machines, xenobiology consoles, cargo supply consoles, keycard authentication devices, communication consoles, airlocks and whatever there is on technological storage.

They can also replicate from nothing, as all swarmers are capable of continuing the swarm by getting fifty resources.

Their non-lethal teleport can teleport the target to dangerous places that contradict with the swarmers laws. Examples of these include: space, engine, xenobiology cages.

I love playing as swarmer, but the only buff they probably need is a way to deal with cyborgs, like meleeing them stuns them for half a second.

**Comment by ExusA** [comment]
Haven't played as crew against swarmers in quite a while, since they're one of the rarer threats to the station. If they're unfun to play against, I can see why. The only reason I thought this would be a good idea is that the swarmers event always pans out the same way, but making them stronger probably isn't the solution to that. Some way to stun cyborgs for just long enough to tele them would be good, and fixing teleporting people to dangerous areas would also probably be good. Even with that, swarmers would still be the same every time they appeared: they'd eat toxins, scichem, server room, elecmaints, possibly one or two other places the crew don't visit often, then die out once sec catches on and hunts them, and science starts checking the fringe areas occasionally. Other infestation antags tend to take out crew one by one, like terrors do, or become stronger if left unattended like the blob does, but no matter how many swarmers there are and no matter how long they've been left ignored or unnoticed by the crew, the worst they'll do is remove enough fun and useful items from the round to annoy the crew into calling the shuttle. That's not fun for crew, and feels cheap and dirty when you're a swarmer. Can see that all these changes don't really fix _any_ of that, but i'm not sure what, if anything, will.

**Comment by Qwertytoforty** [comment]
They actually can stun borgs with the shock trap, if they are clever

**Comment by ExusA** [comment]
True true, yeah. doesn't happen very often, though. (also, curious whether anybody has ideas to improve swarmers, being as they are)

**Pull request closed without merging**
