### PR TITLE
Fixes xeno borg

### PR DESCRIPTION
**Pull request by shazbot194**
This PR fixes the xeno borg so it both is able to be made, if you have a xeno brain, and so the icon works. 

This does not make xeno borgs useful though.

🆑 Shazbot
fix: Now you can actually make xeno borgs.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
I really, do not feel these should be made. Fixing MMIs for xeno brains fine. But i DO NOT feel we need the xenoborg in play.  Not even sure as an alt skin..its just...i dunno.

**Comment by taukausanake** [comment]
Personally I don't think anyone should be able to make xenoborgs (as in with the module) and leave it as an admeme thing. A xenoborg is interesting to see in a xeno round. The brain as a borg might be fine but then you're assuming an alien race which only means of interaction with other species is by knocking them up. Maybe a xeno brain shouldn't be borg-able?

**Comment by shazbot194** [comment]
Guys, you should double check the code. You NEED a xeno brain to make a xeno borg.

**Comment by Kyep** [comment]
Xenoborgs in general are kinda silly.
How often are there xenos?
Of that, how often do you get their brain?
Of that, how often do you get to put their brain in a borg?

Why would you even WANT a xenomorph's intelligence in a borg?

**Comment by Crazylemon64** [comment]
Looks alright

**Pull request merged**
