### PR TITLE
Airlock/Shuttle Compatibility Patch

### PR DESCRIPTION
**Pull request by Twinmold93**
This patch makes it so airlock code is now compatible with current /tg/ shuttle code. It changes how airlocks work slightly, by making airlocks reference var/id_tag_airlock instead of var/id_tag (which all shuttles reference, hence the current incompatibility). With this, all airlocks that have shuttles can now also have cycling airlocks, though the ones on the Cyberiad itself still require External Access.

Airlocks having the ability to be proper station airlocks adds in more locations that people have access to get into and out of the station, especially for engineers, without having to either find a completely different airlock, hack the airlock open, or make a window airlock (and/or possibly breach the station itself, (Grand) Sabotage).

This doesn't change the ability to force airlocks open/closed, if someone is in an emergency or hurry. This does not force the airlock to cycle when the shuttle arrives. As the shuttle does now, it only opens the airlock when the shuttle arrives. The adjustment is so that id_tag that both currently use is no longer the same value both reference.

As a countermeasure of airlocks being used when a shuttle is present, airlock doors also now have var/can_op_airlock, which when shuttles dock and leave manipulate (after closing or opening the airlock in shuttle.dm, adjusts the door's can_op_airlock value so that the airlock cannot be worked with while a shuttle is docked), to make the code have an easier reference point. This is the only change to shuttle code. That is: When a shuttle is docked to the airlock, the doors are unlocked and the controls cannot be used to prevent locking the airlock down, as it is currently.

I have also gone through all z-levels, including MetaStation (virology and xenobiology accesses only), and moved the var/id_tag of all airlocks to var/id_tag_airlock, as well as added frequencies to the airlocks that have an airlock controller so they can receive the signal to open/close.

The only shuttle's airlock not changed to be used as a cycling airlock when the shuttle isn't present is the brig shuttle, due to another PR currently being considered that changes how that area looks, to prevent any potential conflicts between the two.

Additionally, this PR also adds in one additional air vent to each of the two engine airlocks in engineering, to speed up cycling, and also secures the currently open airlock in arrivals for the trader shuttle that spawns unlocked until the shuttle arrives and leaves. When shuttles arrive, they automatically unlock their relevant door and shutdown the cycling airlock.

https://i.imgur.com/SdqeMxJ.png - Escape and Science Dock Airlocks
https://i.imgur.com/OHwRvdS.png - Engineering Additional Vents
https://i.imgur.com/kYbCXUo.png - South Arrival Docks
https://i.imgur.com/hZFaG1G.png - North Arrival Dock

This change will not only allow us to have working airlocks on shuttle airlocks when the shuttle isn't present, increasing the number of avenues players have to access the station without breaching the station (and systematically being valid for a Capital Offense when they really do have external access) but also saves time for engineers, security members, or spaced civilians who may need to get into space or back onto the station via an airlock so they don't have to find a completely different airlock when one so much closer, and already present, would suffice.

:cl: Twinmold
Tweak: Airlock/Shuttle Compatibility Patch - All airlocks can now be cycling airlocks, including shuttle airlocks!
Add: Adds cycling airlocks to most airlocks on the Cyberiad, with require External Access (13) for the controls themselves.
Add: Adds additional vent to each engine airlock, for faster cycling.
Tweak: Locks the unlocked arrivals airlock.
Tweak: Goes through multiple z-levels and patches the airlock systems.
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
cyberiad.dmm looks like it wasn't mapmerged.

**Comment by Twinmold93** [comment]
I recall running map merge. It's just there are a lot of changes (pipes, airlocks, the sort). I'm grabbing two more images of arrivals.

**Comment by TheDZD** [comment]
~9100 lines is about the total size of the map. There's no way it should have that many diffs unless it wasn't mapmerged. Keep in mind you have to mapmerge every time you make changes to the map, so if you ran it once without preparing maps before, and merging the map after, it would result in the giant amount of diffs.

**Comment by Twinmold93** [comment]
How would I fix that for you guys?

**Comment by Twinmold93** [comment]
Now map merged properly.

**Comment by DaveTheHeadcrab** [comment]
:-1: 
We really don't need these for shuttles. Again.
If we had explosive decompression (Which I'm not against) it'd be warranted, but we do not.

**Comment by Fox-McCloud** [comment]
No shitty cycling airlocks 

:-1: x :100: 

They're annoying an unnecessary; they only ever *sometimes* cause coldness/lack of pressure on the shuttle door itself or the outside airlock door.

Other than that, they just waste time; there's a reason miners and everyone else just blindly forces them.

**Comment by Spacemanspark** [comment]
I don't see people forcing them very often unless they're in danger.
:+1: It's not really that annoying and I love my cycling airlocks.

**Comment by tigercat2000** [comment]
I've already said my opinion in other places.
:-1:

Cycling airlocks should be phased out or at the *very* least 100% rewritten. There shouldn't be shoddy patches to make them work with -tg- shuttles.

In my opinion, we shouldn't have them at all. It's pointless and annoying with LINDA in play.

**Comment by Twinmold93** [comment]
The biggest matter of debate is 'practicality vs realism'. I would love explosive decompression to be a thing again, I really would. It'd give meaning back to the atmospherics job, fires being a proper threat, and people needing to be careful when it does come to the atmospheric systems.

People blindly force them because 'time', rather than actual RP/pretending to some form of realism. This doesn't change that part of airlocks. This makes them properly compatible with shuttles, and adds in the long-missed escape airlocks. Otherwise, unless you make a shoddy window airlock, there are very few locations to get out of the station (or back in if you need help) without sabotaging the station, and you may not even have the tools to do so without actually committing code 407: Grand Sabotage. With this, you go to literally any airlock and ask to be let in if you don't already have access, which gives the AI a much better chance of letting you in without going through a department, or venting some moderate amount of air into space.

The other choice would be add in more independent airlocks, but honestly, it'd be a waste of space that could be used for other possible projects or map changes, as well as just more size for no real gain. Unifying them to pre-existing airlocks makes much more sense, structurally and realism-wise.

**Comment by Twinmold93** [comment]
I'd like to note: This does not force airlocks to cycle when the shuttle arrives. Like it does now, it opens both airlock doors immediately: No cycling stage. The additional value is so it can tell those airlocks that they cannot be changed by the access buttons or airlock controller until the shuttle leaves, and opens up that access again.

Effectively, the compatibility patch is so airlock controllers and shuttles don't use the same value, and therefore you can have airlocks on the same airlocks that shuttles currently use. Their functionality is still independent to one another, other than the two lines in shuttle.dm that change a value in airlock doors that makes it so that you cannot work with the buttons for the airlock when the shuttle is docked.

Airlocks missing one or the other will still work perfectly fine. (An airlock with a shuttle but no controller works no different than one with an airlock controller, which works the same way as our current shuttles work, which have no code for airlock cycling [And no cycling is added to shuttle code]. An airlock without a shuttle but a controller works like the engineering engine airlock/mining outer airlocks/solar airlocks currently do.)

**Comment by Twinmold93** [comment]
That didn't fix the merge conflict... Hmmm... No idea where the merge conflict even came from, honestly.

**Comment by TheDZD** [comment]
And now there's another.

**Comment by Fox-McCloud** [comment]
After having discussed this, we'd like to move in the direction of removing the cycling airlocks that already exist rather than bringing them back and shoe-horning an outdated system in with more modern TG shuttles...not to mention the huge pain in the butt mapping in these airlocks and their controllers are.

**Comment by Spacemanspark** [comment]
Ugh.

**Comment by Twinmold93** [comment]
@Fox-McCloud And the reasoning to removing cycling airlocks in total? I believe a big misunderstanding of what this PR actually does, noted in the first three comments against it, is you guys believe this adds in shuttle cycling to airlocks. This PR does no such thing. It adds in airlock controls (and thus the ability to cycle the airlock in and out) to airlocks that once at a time had that ability. This does not re-add the ability for a shuttle to cycle an airlock. This is, above all else, a PR that makes flow of the station more numerous. Because, going to tell you this now: You remove all airlocks abilities to cycle, or rather the entire system altogether, you're going to run into a number of issue, which includes balance issues.

Remove the system altogether, and Xenobiology and Virology accesses become useless, and both doors must be unlocked (or unlock one, remove the other, not too much of an issue with virology access _**normally**_, yet for both cases anything inside, it's one less safety against xenomorphs, an already fast force if not taken down quickly. And any mob that can force doors open, no power in the room, forces the doors open and becomes an even bigger threat a lot faster).

Secondary, removing the system altogether and just leaving the airlocks open/unlocked, makes it even easier for antags, especially Nukies, to just emag in, emag out. This would give them, even just 10 to 15 seconds, a bigger lead time.

Just switching to access buttons is also very pointless, viewed from atmospheric/RP stand-point. Sure, LINDA doesn't have serious issues, but removing the need, or even the code, means you'd have to re-add the code, or even similar code, anyway, if you ever even thought of making a better atmospheric system, or speeding up Linda's calculations, so atmospherics is something to actually work with again (atmospheric job)/is a bigger threat to people/a valid concern and people having the fear of a fire.

The code was last updated a year ago, and yet has not broken. An old code thrown out just because it's old doesn't mean the code doesn't work, or is without value. The entire point of this PR is so we can actually have more airlocks, more access points, on the station so people can more easily get in and out of the station without causing a breach (and subsequently getting in trouble by security for Grand Sabotage and possibly admins, depending on how poorly it was done), while not giving a huge advantage to antags themselves. More airlocks, yeah, but if they really wanted to, they could just go through the window themselves, anyway.

**Pull request closed without merging**
