### PR TITLE
Combine atmospherics process to air controller

### PR DESCRIPTION
**Pull request by Allfd**
This PR merges the pipenet process into the air process.  It also removes atmospherics machinery from the machine process and moves them to the air process.  This allows for atmospheric related machinery to run at a different scheduler speed then normal machinery.

No CL as this is entirely invisible to clients.

### CODE REVIEW

**Comment by taukausanake** [comment]
ZAS murder gases when? Alternatively, can you explain what this means to stupid people like me?

**Comment by Allfd** [comment]
It ties the speed of things like pumps, pipes and other atmospheric equipment to the speed that the air simulation is running at as opposed to the speed of standard machinery which is slower.

**Comment by tigercat2000** [comment]
I've said it in the past, I really don't like the idea of merging all atmos machinery into LINDA's controller. If anything hangs it, it takes down _everything_ else.

**Comment by Anticept** [comment]
If linda hangs, it's hardly going to matter for the atmos machinery anyways.

**Comment by tigercat2000** [comment]
@Anticept On the reverse side, if atmos machinery hangs, it crashes LINDA completely.

**Comment by Anticept** [comment]
I've never seen atmos machinery hang ever, that'd be really damn weird with how simple they are.

**Comment by Allfd** [comment]
Currently if an atmos machine hung, _**all**_ machines would stop work.

**Comment by Anticept** [comment]
@tigercat2000 just realized... if the atmos machinery crashed linda... it still wouldn't be a problem unless you somehow vented most of the station (shuttle anyways).

**Comment by taukausanake** [comment]
Or you know, the mandatory server restart because no one can be assed. But that brings out interesting thoughts. Does that mean LINDA won't make any changes to anything and leave the air always the same or are you saying people will need internals? Either way that sounds nice

**Comment by ZomgPonies** [comment]
This PR makes logical sense and is a requirement for sped up atmos, and Tiger's argument against it is flawed.

**Comment by Allfd** [comment]
@Anticept 
@taukausanake 

To clarify what a hang would cause.  As it stands at the moment without this merge, if a piece of atmospheric machinery hung, every piece of machinery on the server across all Z-Levels would also hang, all 4,060 of them.

So yes if this is merged an atmospheric machine hang would take down linda, as opposed to taking down all machinery.

**Comment by Fox-McCloud** [comment]
>Tiger's argument against it is flawed.

Nottt really.

While I'm in support of merging the controllers, never the less, there are a few things that are, never the less true about this:

- Any halt anywhere in atmospheric machines, pipenets, or the air system will cause **all** of the air system to fail; as it stands now, having them in 3 separate systems means that while one can fail, the others will not halt.

- putting the atmos machines and pipenets on the same controller does mean that there's going to be a lot more things processed on the same tick. As it currently stands, air, machines, and pipenets are all spaced out, and therefore processed on different ticks. This spreading helps prevent "spikey" performance dips and also spread out the calculations over different ticks; with this, it's just BAM all at once, all on one tick.

so, while I do support this, never the less, ***it's not without drawbacks***.

**Comment by Taaketa** [comment]
Based on what people are saying, I'm pretty sure I can crash atmos with this change coming, reliably and easily. I bug reported the hang up issue I discovered with pipes, sometime ago.

**Comment by Allfd** [comment]
This code is obsolete.  Newer code will be put up as a PR in the near future.

**Pull request closed without merging**
