### PR TITLE
Autocomplete input

### LINKED ISSUE #11720: "Teleport" and "Orbit" verbs no longer allow autocompletion
**Problem Description**:
Before some recent updates (one adding ghost GUI and replacing Following with Orbiting, I believe) the Teleport and Follow verbs had an autocompletion feature. You could type "Teleport synd", press [Space] (IIRC?) and a floating pop-up showed up a list of possible locations that included "synd" in their name. This was very helpful as you could quickly find the desired area/entity instead of looking through a looong, potentially unsorted list of all possible ones. You could still see this behavior in some admin verbs such as "Jump-To-Area" and "Jump-To-Mob", but us ghosts without adminpowers no longer have access to this useful feature. I'm surprised this wasn't reported before!

**What did you expect to happen**: 
Autocompletion option working well, as before, allowing to quickly find the desired entity to follow or area to teleport to instead of painstakingly scrolling through a long, unsorted list.

**What happened instead**:
Teleport/Orbit verbs no longer have autocompletion in text mode.

**Why is this bad/What are the consequences:**
It takes much longer now to find someone/something as a ghost, and this is very sad. I am sad.

**Steps to reproduce the problem**:
1) Enter text mode with [Tab], if you were in hotkey mode before. The text prompt below the game area will turn red.
2) Type "Teleport synd" and press [Space]. Nothing happens! Same thing with the Orbit verb.
3) Now erase that, type instead "Jump-To-Area synd" and press [Space]. If you're an admin, you will be immediately prompted with a list of suggested areas - just like Teleport and Follow verbs used to work before.

**When did the problem start happening**:
Recent Paradise updates... When ghost GUI was added, I think?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Don't think there is anything more to tell!

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
**What does this PR do:**
Adds an autocomplete input. I've only added it to ghost buttons for now, but can expand it to karma awarding, admin things, and other stuff if this seems better.

Fixes #11720

**Images:**
ac

**Changelog:**
:cl: Tayyyyyyy
add: Autocomplete for ghost buttons
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
Dear Lord, what is this space magic? I'd burn you at the stake if I weren't so grateful for this addition.

+1, burn the heretics.

**Comment by Taaketa** [comment]
Might I recommend some kind of check to not spam the list with medbots, cleanbots?

Not a problem if the they are named but if someone doesn't bother it could spam the auto filter.

**Comment by Markolie** [comment]
Nice! Honestly, I’d just replace all of our inputs with this.

**Comment by Ralta** [comment]
> Nice! Honestly, I’d just replace all of our inputs with this.

Ditto. I'd like to see how it works in-game but if it's as clean as it looks in the gif, I reckon it'd be great for all lookup inputs.

**Comment by Ty-Omaha** [comment]
can we hit enter on it

**Comment by Tayyyyyyy** [comment]
> Might I recommend some kind of check to not spam the list with medbots, cleanbots?

I haven't changed the list of stuff that the commands pull from. The follow command already filters out mindless mobs. I think it's just the jump-to-mob command that lists everything.

> Nice! Honestly, I’d just replace all of our inputs with this.

The only reason I haven't replaced a lot of it is that some verbs can take arguments, which you can type into the bar on the bottom (and actually byond has its own autocomplete for those types of verbs, though it's a bit clunky). Some of those might be macrod, so I'm not sure whether breaking those is a good idea. One option is to have a tab for "Legacy Admin" that would have all the verbs that you can type with arguments, and then new verbs that use this input and call the old ones. I already have some admin commands implemented this way but not committed

> can we hit enter on it

Yes, enter submits it. Sadly byond for some reason doesn't let you use enter to select the option if you're using arrow keys to select, even though worked in IE 🙁

**Comment by Markolie** [comment]
I’d prefer not adding even more tabs/verbs. Probably best to just determine what verbs people macro and have those use the old system. There’s probably only one or two.

**Comment by Bookdrizzt** [comment]
I desperately beg you, add this to malf AI functions. Currently, for machine overload, you need to scroll through a list of EVERY MACHINE ON THE SERVER to find any machine, and it’s organized pretty randomly.

**Comment by Citinited** [comment]
We're finally stepping into the 21st Century with this 😄 

May I suggest that the VV panel and game panel (the one where you can spawn stuff) work with this?

**Comment by Tayyyyyyy** [comment]
> I desperately beg you, add this to malf AI functions. Currently, for machine overload, you need to scroll through a list of EVERY MACHINE ON THE SERVER to find any machine, and it’s organized pretty randomly.

AI stuff is definitely the next thing I'm planning on adding if it gets approved!

> May I suggest that the VV panel and game panel (the one where you can spawn stuff) work with this?

So I just tried implementing VV with this, since the sheer number of items VV goes over was a good performance test for the input. The good news is that the input handled the massive number of options just fine. The bad news is the DM for loops get all the turfs and objects on the server lagged the server by a lot. I'm guessing byond must internally keep track of a list of all objects and turfs somewhere, but I'm not sure where to access that.

Also, isn't VV usually accessed through right click?

As for game panel, this is just HTML's native autocomplete, so it only looks at the beginning of the string. I could add a button to select from game panel search results with this input. I'm not sure it would be that much faster though, since you'd have to type out the whole start of the path?

**Comment by Citinited** [comment]
Hmm yeah, you may be right on the game panel - it may be a non-starter if you always have to type out the starting bit. Ah well!

**Pull request merged**
