### PR TITLE
LINDA Performance Fixup

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Dramatically cuts down on the amount of turfs LINDA processes.

Simply put, LINDA is very selective of the turfs it processes; if there's something even slightly amiss with them, it adds them and all the turfs around it in a zone to an "excited group" and proceeeds to process them.

That said, on Paradise, LINDA is a bit...too active. This is primarily because of mapping errors; having floors out in space, in particular, is troublesome---so is having random tiles that have more pressure/temperature/gas content than all the turfs around it.

Another source is telecomms equipment, which generates heat, and therefore requires constant cooling---which results in the entire telecomms compartment processing 24/7/365 despite not being interacted with or touched.

Either case, this cuts down the amount of active turfs to processed from about 2000 down to 30--when the round starts, the amount of active turfs will temporarily balloon up to about 600, but quickly dissipate down to 30-40 by 4 minutes into the shift. 

The research Xeno outpost was a HUGEEE culprit of the number of active turfs--there were tons of turfs with air in them that would spill out into the main asteroid (where the monsters were) and end up ballooning the processing turfs up to 4000+ later on into the round, which can really add up.

In any event, 95% of this PR is map edits to fix various mapping errors with turfs, the other part:

- Removes telecomms equipment generating heat
 - It's pointless to process this by the machines controller and LINDA every tick, when telecomms isn't interacted with 99% of the time (and the 1% it is interacted with, it's blowing it up)
- Makes Telecomms equipment GC
- Removes the cooler to the telecomms compartment (no longer needed)
 - The telecomms compartment is still cold, by default.
- Removes the little weird mining substation between the research and science station
 - Yes, this area was causing active turf issues in addition to taking up valuable high-tier mining turfs.
 - The spare hardsuit here was moved to mining storage

Other Fix of Note:
- Re-adds Syndicate. Fixes https://github.com/ParadiseSS13/Paradise/issues/2360
- Re-adds the Xeno Suit that was removed, without notification or permission in this PR: https://github.com/ParadiseSS13/Paradise/pull/2059
 - No one has a monopoly on this damn thing.

Screw Dat Shit, I want numbers.

Ok

Before: http://hastebin.com/icojovewor.mel

After: http://hastebin.com/aquqakuhen.mel

45% cheaper, overall.

Sometimes the current situation is even worse---at times the active turfs on the asteroid will clear and LINDA will settle out to ~150-200 active turfs...that said, sometimes it'll never clear and balloon up to 4000+ turfs.

Coder musings

Incorrect turfs that were amusing:
- Most of the non-station solar turfs were fully aired turfs 
- The Goon plagues had custom air settings on them for no apparent reason 
-  Copy-pasta never dies: some north-facing warning stripe plates (labeled as normal) were airless, causing entire sections of maintenance to be permanently excited.
- The solars plating turfs that joined it to telecomms were curiously fully aired despite the other 99% not being so.
- There were 2 custom set turfs on the Vox skipjack...why?

Right so, there's still about ~700 round-start turfs that become active; 90% of those are due to disposals. Fixing that will be addressed in a future PR, once https://github.com/ParadiseSS13/Paradise/pull/2373 is merged. It's a relatively easy fix.

### CODE REVIEW

**Comment by Robertha89** [comment]
I am against removing the North mining outpost, it contains the fourth mining rig, and a box of donk pockets, if this is moved into the main mining outpost, then sure.

**Comment by Fox-McCloud** [comment]
There's a box of donk pockets in the mining outpost proper, and the suit is unused 99% of the time except to be stolen by certain science team members who don't really need such a thing--other than that, it's a pointless addtition that has some atmos problems with it and takes away additional high tier mining turfs.

**Comment by tigercat2000** [comment]
still don't think telecomms heat should be removed, if anything, it should be capitalized upon, made the CE's job, go turn on the cooler or no radio

**Comment by Robertha89** [comment]
the suit was used consistently for half an day, and the reason it's rarely used is because to get there you need to spacewalk, thus a 4th vox miner would grab it, it should be added back.

**Comment by Spacemanspark** [comment]
I'd rather we keep that norther mining outpost.

**Comment by Robertha89** [comment]
@Fox-McCloud in the 129, 146 ,5 area of mining just, after diffing i found tiles with air, there are also a few pockets of air below the east entrance, which might not be helping, so this should be checked out.

**Comment by Fox-McCloud** [comment]
I can re-add the mining hardsuit, but having an unused room dedicated to it (that's functionally pointless and unused) over additional tiles to mine is a nada.

**Comment by Fox-McCloud** [comment]
Re-added the hardsuit to mining storage.

@Robertha89 

There's not any turfs that have explicitly set Oxygen or Nitrogen that are outside of the Research Outpost Isolation, so if there's issue, then it originates from an improper turf.

This PR is meant to address the BIG issue with LINDA (processing 1000+ turfs for the entire round, even with hardly anything happening); as I said in the first part, there's still lots of work to be done, but it's going to require some debugging tools to pin down all the incorrectly set turfs, and that's for a different PR.

**Comment by Fox-McCloud** [comment]
There's apparently a few errant alarms, as well, which are set to be 18 degrees colder (F) than they should be---likely a copy-paste error as they all have the same pixel offset; it means they'd also try to start cooling turfs.

**Comment by Fox-McCloud** [comment]
It would appear that disposals may be interacting with turfs and causing a big portion of the round-start activated turfs.

@Aranclanos 

Would you know anything about this?

**Comment by Fox-McCloud** [comment]
Aghhhhh, so many floors in space.

**Comment by Fox-McCloud** [comment]
Re-adds the Xeno suit that was removed, without permission, and snuck in, in this PR: https://github.com/ParadiseSS13/Paradise/pull/2059

**Comment by Fox-McCloud** [comment]
Alright, did some testing, and I won't be able to include it in this PR, as it'll conflict with another one, but, yeah, those 500-600 active turfs that clear by 4 minutes in? It's disposals. Need to add an initialize for them so they start off with air.

Once that's done, the round-start turfs will only jump up to 70 before falling back to the baseline of ~30

**Comment by Plotron** [comment]
I'm hyped!

**Comment by KasparoVy** [comment]
Chimera trying to kill the xeno suit o_O

I'm supes interested to see how this pans out. I remember we did that one test where we amped the LINDA processing speed. I figure it'd work WAY better now after this PR, and it'd probably be a good idea to test it

**Comment by Aranclanos** [comment]
if you have an older version of disposals, they'll appear empty at roundstart and slowly charging themselves by taking air from the turf on top of them. Just make their initialize() COPY (not take) a chunk of the air of the turf to pressurize themselves.

remember that the idea is to have 0 active turfs at roundstart, but at the same time I wouldn't remove features (tcomms and RnD servers heating)

**Comment by Fox-McCloud** [comment]
@Aranclanos 

Yeah, that's what I've been doing; thus far, the only turfs active at round-start (and I dunno why), after this change, are artifact rooms on the mining asteroid. Not really sure why they are being listed as active--the split second the round starts, though, they instantly clear, and the only active/excited turfs are those generated because of disposals and because of a few atmospherics tanks on station.

**Comment by Fox-McCloud** [comment]
re-added Syndicat.

This PR is ready to.

**Comment by TheDZD** [comment]
Honestly, it doesn't feel to me that Telecomms creates enough active turfs to justify just nuking the heat generation portion of it entirely. It may not be feature that really contributes much, but if by that logic we could go around nuking around a lot of features that don't contribute much and cause slight performance problems.

**Comment by Fox-McCloud** [comment]
Before and after:

Before: http://hastebin.com/icojovewor.mel

After: http://hastebin.com/aquqakuhen.mel

**Comment by Fox-McCloud** [comment]
@Aranclanos 

Even after considerable work, I'm still getting all the mining asteroid artifact rooms being activated at round-start (only them, though and they clear the split second the round starts)---any idea how to correct this or why it's occurring to begin with? It's not a big issue, to be honest, as they instantly clear, but I'd still like to correct/address the issue.

**Comment by TheDZD** [comment]
Huh, given those kind of numbers I agree that it's probably worth nuking then.

**Comment by Fox-McCloud** [comment]
@Aranclanos 

The only thing I can think of is that when a turf is replaced on the asteroid by the artifact rooms, that ultimately it's calling the Turf/Destroy() which is telling LINDA "Hey, list this as excited and add it to active turfs".

**Comment by Fox-McCloud** [comment]
I do plan on doing further work on this, but this does solve the vast vast majority of active turf problems; I'll be making a new PR, once this is merged, to address disposals and maybe make a few more alterations (likely very little mapping ones) to kill off the remaining round-start turfs.

@Markolie  @TheDZD 

This is ready to merge once it passes the 24 hour mark and meets your approval.

**Comment by Aranclanos** [comment]
yeah just make the asteroid artifact rooms generate before linda intializes

**Comment by Fox-McCloud** [comment]
Aight. I can only do that, really, by moving away mission and artifact room generation into world/new().

On a related note, how come I was able to cut the round-start turfs (minus the artifact rooms) to 0, but it was required to add T.Excited = 0 and removing turfs from active turfs on TG? https://github.com/tgstation/-tg-station/blob/master/code/controllers/subsystem/air.dm#L176 here and the next line down.

**Comment by Aranclanos** [comment]
there was a reason but I can't say I remember right now

**Pull request merged**
