### PR TITLE
Kidan Resprite (CLOTHES NOT INCLUDED)

### PR DESCRIPTION
**Pull request by SeizedClod22**
## What Does This PR Do

This PR changes horn sprites, antennae sprites, mask sprites, and body sprites for the Kidan. Note that clothes sprites are not accounted for, and are being worked on by another person.
## Why It's Good For The Game
The Kidan sprite seemed outdated compared to the evolution of sprites on the server

## Images of changes
image
image
image
image
image

## Testing

Made several private servers, ensuring every body part was where it was meant to be
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval]
(https://github.com/ParadiseSS13/Paradise/blob/master/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
image
  
  
  <hr>

## Changelog

:cl:
imagereplace: Redid the Kidan species’ related sprites, including antennae, clothing masks, body parts, etc
/:cl:

### CODE REVIEW

**Comment by Git-GoR** [comment]
Reposting here so it does not get lost in Discord.

The previews of the new design make it seem so the new eyes are now a 2 by 3 pixels rectangle socketed with an outline that belongs to the "head", compared to the old egg-shaped eye that the current design has. However, ingame the egg shape returns as the color mask is applied to this different color outline as well. Which design is the intended one?

Compare the new socketed eye with a clear outline 
imagen

vs the current design, no outline.
imagen

This is not to say one is better than the other, necessarily. I personally think both have their pros and cons. But I just wanted to make sure which one is intended, because if the idea is to keep the non-socketed design, then why give them an outline at all?

**Comment by SeizedClod22** [comment]
> Reposting here so it does not get lost in Discord.
> 
> The previews of the new design make it seem so the new eyes are now a 2 by 3 pixels rectangle socketed with an outline that belongs to the "head", compared to the old egg-shaped eye that the current design has. However, ingame the egg shape returns as the color mask is applied to this different color outline as well. Which design is the intended one?
> 
> Compare the new socketed eye with a clear outline imagen
> 
> vs the current design, no outline. imagen
> 
> This is not to say one is better than the other, necessarily. I personally think both have their pros and cons. But I just wanted to make sure which one is intended, because if the idea is to keep the non-socketed design, then why give them an outline at all?

They’re supposed to be non-socketed. The outline’s skin colored to limit the color pallette. I added an outline to it so the eyes wouldn’t blend into the background. The yellow eyes aren’t actually seen ingame, since it’s being covered by the black eye color overlay

**Review by Burzah — COMMENTED** [review]
Changelog needs to be redone.
It should just be that you updated the species sprite itself. It also should not contain any images, as this is what appears on the in-game change log.

**Comment by SeizedClod22** [comment]
> Changelog needs to be redone.
> It should just be that you updated the species sprite itself. It also should not contain any images, as this is what appears on the in-game change log.

Is the new changelog better?

**Comment by Christasmurf** [comment]
I have contacted you on discord about some minor changes to the sprites, let me know when those are done and I can review this

**Comment by SeizedClod22** [comment]
> I have contacted you on discord about some minor changes to the sprites, let me know when those are done and I can review this

Done

**Review by Christasmurf — APPROVED** [review]
Sprites all check out in correct files, changes looking good.

**Review by DGamerL — APPROVED** [review]
Diffbot looks good, sprite team approval

**Pull request merged**
