### PR TITLE
DeltaStation: Science Remap

### PR DESCRIPTION
**Pull request by DogeDogIs**
This PR remaps the science in DeltaStation for a better gameplay experience.

## What Does This PR Do

This PR redoes Delta's science almost entirely, completely changing the places of the rooms and improving some, such as toxins, which in the old Delta was totally disorganized and contained a lot of pipe information and was not spacious, now we have a new room for the toxins, the Sci-Chem was modified with an appropriate test chamber, and the experimenter was positioned elsewhere as well. Now the break room also gives access to roboticists, who previously did not have this access.

## Why It's Good For The Game

Our current Delta has many errors, and if we start with the main points, we can gradually improve it. Science had a lot of mapping errors and it wasn't pleasant to look at either. With remap, the rooms contain a new position which I think is good, and Toxins is no longer the mess it used to be. With the changes we can certainly have a much better gameplay, since many didn't understand how to make the toxin in the old Delta. With the change, it looks a lot like the Cyberiad toxin, to help anyone using the Wiki.

## Images of changes

science

## Testing

created local game, entered as scientist and pressed buttons and walked arround to see if had any errors.
## Changelog
:cl:
tweak: Remapped Delta Science
/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
damn errors
😭

**Comment by Serxule** [comment]
not a fan of toxins storage being in the middle of science and a bit far away from toxins, but sci-chem and toxins look nice

**Comment by GDNgit** [comment]
Couple of things
1. This is cramped as all hell, this turns the entire area into a choke point for antagonists, consider adding some ways in and out 
2. Toxins seems to be overly well protected, would be for the best if it was given a couple more ways to get in
3. Long 2 tile hallways are bad, break those up
4. Not a fan of science couch/medical bench kind of things, just encourages people not to do their jobs or RP in a way that isn't super metafriend-y

**Review by Sirryan2002 — APPROVED** [review]
after looking at the mapping changes I don't see any issues and things look inline with the mapping standards. Although it probably wouldn't hurt to have another person look at it

**Comment by AffectedArc07** [comment]
Could the conflicts on this get resolved soonish please?

**Comment by DogeDogIs** [comment]
I can't use the SDMM to check the map for errors so this PR can be put on wait, thats pretty bad.

**Pull request merged**
