### PR TITLE
PDA + Pinpointers Resprite

### PR DESCRIPTION
**Pull request by kugamo**
## What Does This PR Do
Resprites the PDAs, fresh coat of paint. Enter 3/4ths. (not really a huge change)
also Pinpointers.
also also makes the clear PDA once again in game (it hasnt been around since mining asteroid)

## Why It's Good For The Game
Moving all our sprites to 3/4ths perspective, this is part of that effort.

## Images of changes
image
Aseprite_m8mE5x9Eyh
redid the screens a bit, so they dont blend with the body as much
firefox_NZgvhnnj3Q

## Testing
Loaded up the game **ONCE** because its a resprite and everything lined up .... 

## Changelog
:cl:
imageadd: Tweaks PDAs' & Pinpointers' sprites a tad.
add: The clear PDA can now be found as extremely rare maint loot.
/:cl:

### CODE REVIEW

**Comment by DGamerL** [comment]
What's with the cyan line on the top right sprite?

**Comment by kugamo** [comment]
> 

its a see through pda, so I suppose its the clear plastic. Idk i think its a patreon thing or something, i've never seen it b4 in game.

**Comment by DGamerL** [comment]
I have never seen that before haha

**Comment by ArcticValor** [comment]
oh, is everything just becoming progressively chunky now?

**Comment by kugamo** [comment]
> oh, is everything just becoming progressively chunky now?

Have some dimension with your pixels, ON THE HOUSE.

NEW CLEAR PDA SPRITE--->>>
image

**Comment by GreatGatherer** [comment]
I'm a big fan of the new pinpointers, but the new PDAs feel a bit odd. Perhaps a slightly darker outline around the screen could make them feel a bit nicer, especially so near the bottom.

**Pull request closed without merging**
