### PR TITLE
Remove genetics from medbay

### PR DESCRIPTION
**Pull request by dapocalypse**
After some disscussion with a few people on discord, we have concluded that genetics is useless to medbay therefore I would like to remove genetics from medbay. The three things that genetics provide for medbay are, to clone, monkey cubes, and cure genetic defects. Genetic defects can be cured via mutadone and monkey cubes can be obtained via virology. And what about cloning? Cloning is neglected by the geneticists and is often taked up by the coroner. A map change walling off the genetic research lab and cloning should be made. SOP should also be edited to make cloning an official duty of the coroner and cut ties with medbay.

### CODE REVIEW

**Comment by EvadableMoxie** [comment]
So you want to remove Genetics from Medical, because it only does 3 things for medical which are somewhat redundant.  And give it to, Science I assume, for whom it does... 0 things?

From a balance perspective, making by far the strongest department in the game even stronger seems like a bad idea.

**Comment by dapocalypse** [comment]
I mean to say, most peopl ignore its medical responsibilities while fulfilling its reasearch aspect.

**Comment by dapocalypse** [comment]
I brought up the three things to show. These are their responsibilities, they dont even do these. It contributes to science by discovering powers which it acually does uts job in.

**Comment by alexkar598** [comment]
Human experimentation is more a medbay field than science(they experiment on objects and non crew) and you already said in the OP,what does genetics have that science needs?

**Comment by alexkar598** [comment]
^^no delete on mobile,you already said in the OP meant to be you already said in the OP what they give medbay

**Comment by dapocalypse** [comment]
I explain how they don't provide or can be replaced. Medbay is for treating injured. Science is reasearch.

**Comment by dapocalypse** [comment]
Clean ses can be replaced with mutadond. Monkeys can be obtained from viro, geneticist ignore cloning

**Comment by alexkar598** [comment]
Where should they get humanized monkeys?

**Comment by dapocalypse** [comment]
Viro

**Comment by alexkar598** [comment]
Please note I said humanized monkeys

**Comment by dapocalypse** [comment]
And why would you need them

**Comment by alexkar598** [comment]
Have you played medbay for at least 6 shifts?

**Comment by dapocalypse** [comment]
Yes please explain

**Comment by Miraviel** [comment]
"The three things that genetics provide for medbay are, to clone, monkey cubes, and cure genetic defects."
 
Genetics also provide humanized stoks, nearas and wolpins for brain transplants which is sometimes the only way to bring someone back - for example when the cloner is blown up or otherwise unreachable, SR is either not made, a brain transplant + transferring the DNA would be less of a hassle than SR (body is too long dead, it'd take too much with surgery to revive everything) or their body is gibbed and only their brain is left.
 
In case mitocholide is not available, Genetics can provide organs for medical to replace dead ones. Sometimes medical starts with harvesting organs and store them in freezers, just like with blood packs, especially when they are low on staff and/or they know they won't have time for treating everything with mitocholide (early nuke ops announcement, etc.).
 
 "Genetic defects can be cured via mutadone and monkey cubes can be obtained via virology."
 
 Mutadone, yes, but if it's the clown, you cannot just cure them with mutadone or they lose their voice or in the case of a Grey, they lose their telepathy.

Monkey cubes in virology are meant to be used in virology, for testing viruses. Virology also lack of neara, wolpin and stok cubes that are otherwisee needed (see above).
 
"A map change walling off the genetic research lab and cloning should be made."

Please no. Just no. Science already has almost everything (in time, they literally have everything) and denying Medbay one very useful resource in favour of the most powergamey department just doesn't make sense.

Geneticists already rarely give a damn about giving out superpowers, decreasing their responsibility even further would lead to their SEs being more frequently used by antags.

**Comment by dapocalypse** [comment]
Ok I can place a clean se in medbay storage so they can make a gun cloning monkey

**Comment by Miraviel** [comment]
You clearly do not read what we write. I just hope this gets closed soon.

**Comment by dapocalypse** [comment]
Mobile delete ^

**Comment by dapocalypse** [comment]
Above yours

**Comment by alexkar598** [comment]
Stop listening to discord,what people wants is almost always the exact opposite of what discord people

**Comment by dapocalypse** [comment]
How do we get genetics to do cloning

**Comment by dapocalypse** [comment]
It's the one responsibility that links then to medbay. Theyvdont do it.

**Comment by Tayyyyyyy** [comment]
It makes so much more sense to remove genetics from science. Like literally who thinks of genetics as a science department? Like shadey said on discord, it's always the CMO that has to go after genetics when they start giving out hulk in the bar. If you make the opposite PR, I think people would be all for it.

And no, it's not the one responsibility. I'll just put shadey's discord comment here:

> Medical needs genetics for Clean SEs (mutadone does not fix everything), and far more essentially, humanized monkeys, stoks, nearas, farwas, ETC. Genetics plays a role that is required in medical, fullstop.
If a corpse is skeletonized there is no alternative other than a brain transplant.
If a corpse is gibbed, there is no alternative other than a brain transplant.
If someone's organs are dead (which happens), there is no alternative other than an organ transplant

**Comment by Denthamos** [comment]
I agree with Tay on this part.  It makes more sense to merge genetics fully into medical and move it away from science.  It will also reduce the overall strength of the most powerful department of the station which will be a good thing.

**Comment by Necaladun** [comment]
Genetics can be pretty damn necessary for medical, as proposed above. Especially due to the usage of cloning, which is part of genetics, I'm all for this being closed. It's not a change I'd like to see.

**Comment by Fox-McCloud** [comment]
Did you really do this in the web editor?

**Comment by Kyep** [comment]
Thoughts:
1. Removing the Geneticist job/access is a bad idea. It effectively gives all Scientists access to genetics. This makes them even stronger than they already are. It also makes it nigh-impossible to control the distribution of genetic powers if so many people have access to the equipment.
2. If you want to avoid having Genetics as a split department (which makes it annoying hard to manage) then there are better options. You should instead move the R&D part of Genetics into Science (e.g: Genetic Researcher), and maybe give responsibility for cloning to the Coroner (or MDs). Either way, have a window between the two (like kitchen/botany) so Genetics Research can hand out clean SEs, for example, or humanized monkeys for organ farming. Doing this would split Genetics into medbay bits and R&D bits, with each of them going to their respective department, instead of the whole thing being a weird workplace that is part of both departments.

**Comment by dapocalypse** [comment]
I am just needing to use my school ipad

**Comment by dapocalypse** [comment]
Also I agree with number two.

**Comment by dapocalypse** [comment]
However no code changes are needed for number two I think other than map and sop

**Comment by dapocalypse** [comment]
Other than ones proposed

**Comment by dapocalypse** [comment]
And can't chemistry make human monkeys

**Comment by davidchan13** [comment]
>How do we get genetics to do cloning

**Comment by davidchan13** [comment]
>How do we get genetics to do cloning

Change how Genetics/Cloning work. Make cloning require someone outside the pod to monitor and keep track of values on the console and change settings as the clone progresses to ensure a healthy clon and/or minimize defects. 

Have a successful cloning give out data relevant to genetics (Identify a SE or UI or something) or make it so Genetics can rig up the cloners to always apply certain SE combinations.

IMO Genetics should grow/prepare clones much like how Robotics prepares Borgs, making templates and spare bodies for use for when a brain comes along that needs a body, and the Geneticist doing the final modifications and transferring brainwaves to the new body.

**Comment by Birdtalon** [comment]
Good lord.

**Comment by dapocalypse** [comment]
Why not kyeps idea

**Comment by alexkar598** [comment]
Maybe because it will be finally coded at the same time as lava land ?

**Comment by Fox-McCloud** [comment]
Yeah, this isn't going to happen.

**Comment by Fox-McCloud** [comment]
Not a direction we want to be going in; would be better to encourage genetics to do their job.

Also this is hugely unpopular.

**Pull request closed without merging**
