### PR TITLE
5.56x45mm and 556 rename

### PR DESCRIPTION
**Pull request by shazbot194**
This PR renames 5.56x45mm to .308 Win. and 556 to 5.56x45mm. This PR does not effect balance, or anything like that. This PR is a remake of #7725, and even though that one was denied, I am making this as even the maintiners have shown interest in this kind of PR since we current have two ammos that share a name.

🆑 Shazbot
Change: Renames 5.56x45mm to .308 Win. and 556 to 5.56x45mm
/🆑

### CODE REVIEW

**Comment by shazbot194** [comment]
*Buzz*
Time to try and find a way to fix this

**Comment by shazbot194** [comment]
*Pings!*
Well, this is ready for review, as it's a rather small PR, that mostly just changes names.

**Comment by davidchan13** [comment]
.308 caliber is 7.62mm, and .308 Winchester is specifically 7.62x51mm NATO rounds...

**Comment by shazbot194** [comment]
That I said very true, but I know that a lot of people aren't quite as well versed in guns, and I don't want to confuse them with another 7.62 ammo.

**Comment by FalseIncarnate** [comment]
Why not just rename it to like “carbine shells” or something, since that’s what they are used in? Or change the other to “machine gun ammo belt”, as it is used in a belt-fed machine gun

**Comment by shazbot194** [comment]
Mostly because no other ammo is like that. They all use real world names, even if the effects don't quite match up.

**Comment by shazbot194** [comment]
Well, this is the third try on a PR I have waited months for, and I have waited months for this one too, I don't want to fix the merge conflicts anymore, just to wait for more to appear, so I am closing this PR.

**Pull request closed without merging**
