### PR TITLE
Spellbook overhaul

### PR DESCRIPTION
**Pull request by tigercat2000**
tgstation/-tg-station#9537
Contains Commits:
 - Spellbook Refactor <AnturK/-tg-station@6380f67>
 - Splits the Spells into Offensive/Utility <AnturK/-tg-station@25ba9fb>

More or less a complete overhaul of the spellbook to a datum based system.
Current image: blarhgehtr

### CODE REVIEW

**Comment by Robertha89** [comment]
Oh, i do like this, maybe use this time to add a few extra items for the wizard to buy, maybe even add more uses, as with the standard high server pop, you basically never have a sucesfull wizard.

Artifacts that could be added, veil render, statuette (itempath name vampire or vampiric, statuette is just the item name), Veil Render, summons a portal that when touched or after a while summons a narsie/wizard, bout the size of a stage 4 singularity, the statuette is, well if you gibbed a room full of people, it will eventually spawn monsters from the blood, the same type of monster as the wizard's pet.

Also, i believe the reset spell option might have gone away, and returning uses by applying the artifact summoned to the book might not work, not sure.

I dunno, maybe i wanna buff the wizard, or maybe i just wanna see a use of items most people do not even know about.

**Comment by tigercat2000** [comment]
@Robertha89 Reset spell is gone- but you can refund spells individually as long as you are in the wizard lair.

**Comment by TheDZD** [comment]
Considering Summon Guns and Summon Magic now give you an extra spell charge, I would recommend removing the fact that they turn 25% of the crew innto antags, /tg/ had removed that a while back.

**Comment by Robertha89** [comment]
Yes please, the turning crew into antag is dumb, not the idea it self, it's fairly great, but due to our player base, and probably the lax rp-rules. Hey, gotta survive, means i should kill EVERYONE. I mean really, it's technically bannable to go on a killing spree with that objective. 

But yes, removing the make people antag part would be great, because we can't have nice things.

**Comment by tigercat2000** [comment]
@Fox-McCloud @TheDZD @ZomgPonies This is merge ready now.

**Pull request merged**
