### PR TITLE
Zombie changes #3

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

- Buffs zombie healing from 1-6 to 3-8 for each damage type.
- Zombie healing now heals robotic parts
- Zombies now go after all living non-zombie players when in a mindless hunger, including borgs and simplemobs.
- Cremating a zombie will now do 1000 burn damage instead of destroying them
- Gibbers do the same, but with 1000 brute
- You can no longer cut off a zombie's head, even with surgery
- Zombies now break out of buckle-cuffs instantly, but still have their normal cuff time. This is because cuffing is way too strong.
- Cures now no longer need the virology symptoms, but having them makes making the cure much easier as it requires only 1/3 of the reagents

## Why It's Good For The Game
Zombie "balance", and less round removal.

## Testing

Not tested yet

## Changelog
:cl:
tweak: Buffs zombie healing from 1-6 to 3-8 for each damage type.
tweak: Zombie healing now heals robotic parts
tweak: Zombies now go after all living non-zombie players when in a mindless hunger, including borgs and simplemobs.
tweak: Cremating a zombie will now do 1000 burn damage instead of destroying them
tweak: Gibbers do the same, but with 1000 brute
tweak: You can no longer cut off a zombie's head, even with surgery
tweak: Zombies now break out of buckle-cuffs instantly, but still have their normal cuff time. This is because cuffing is way too strong.
tweak: Cures now no longer need the virology symptoms, but having them makes making the cure much easier as it requires only 1/3 of the reagents
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
Thank god. I get tired of telling people not to gib the first one or two zombies constantly.

**Comment by Rayforx** [comment]
It would probably be a good idea to give a bit of toxin/oxygen regeneration
Else we can give the zombies funny chemicals, while they can't fix it

**Comment by Migratingcocofruit** [comment]
The main problem all these sort of changes are trying to solve is that zombies are being removed from the round, whether by destruction or containment, rather than cured. I think this issue is merely a symptom of greater problem: fighting zombies, keeping them contained and RRing them isn't risky enough.  
The way I see things going currently is:
1) players figure out a way to contain or RR zombies
2) zombies are updated to become immune to that
3)repeat until zombies are immune to everything

In other words the way zombies are being currently treated leads to a situation where either the station has some cheesy way to completely disable them, or the zombies are immune to everything and the crew can do nothing to protect itself.   
Think of it this way, if a zombie was a lone antag without the means to infect anyone, in other words objectively nerfed, would all these proposed abilities be okay? I doubt it. 

Rant over, time for suggestions:
As said before I believe, Zombies should be far more risky to fight; specifically, there needs to be a far higher risk of infection. I see two main ways of addressing it:
1) The current way equipment currently protects against infections is too absolute. Having various armours and suits offer varying levels of protection with varying levels of coverage should make it so more specialized equipment is needed if you wish to actively fight zombies, and even the best of gear should still leave room for error that would allow one to get infected without even realizing it until it's too late.
2) Zombies should get more infection abilities. A few options include releasing infectious smoke, splashing bodily fluids on enemies, or having any item covered with their blood become infectious as well, especially sharp objects. If you aren't prepared to fight them you should run away and hide.

 If the crew wishes to gib a zombie they should be able to do so, although discouraged, both by it being murder of a fellow crew member that is otherwise saveable, and by the process of capture and gibbing being very likely to infect everyone involved. This of course may not be enough, so another thing that could be considered is the brain of the zombie becoming a mob itself once removed, being able to vent crawl and having other new abilities that allow it to infect and perhaps even take over monkeys to regain a body while also being able to survive cremation and the like so crew doesn't just destroy is as well. 

The situation I feel should be aimed for is one in which the crew is scared of fighting the zombies and tries to avoid them while also being forced to risk an encounter as a result of their needs, whether related to the cure, or otherwise.

**Comment by SynthTwo** [comment]
!wiki_label

**Comment by Contrabang** [comment]
I don't have the motivation or time to maintain any of my PRs

**Pull request closed without merging**
