### PR TITLE
Explosion Tweaks and Fixes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates and Tweaks Explosion Code

Explosions
- Updates Explosion code for floors to be more in line with Bay, TG, and Goon.
- Explosions slightly less effective against walls
- Cleaned up explosion code for a lot of mobs; also generally removes damage being dealt to mobs when they should just out and out gib
- Redid human explosion effects (will require its own section for explanation)*
 - Heads/skulls are no longer eligible candidates for dismemberment (meaning no more unlucky insta-deaths from small explosions)

Fuel Tanks
- Removes unused code for fuel leaking.
- Nerfs fuel tank explosions with regards to mobs (no more gibbing people with them).
- Fixes fuel tanks exploding from disabler beams and some other non-damaging projectile sources.
- adds admin logging for fuel tanks that have been exploded by projectiles

Other
- Makes atmos backpacks start out filled with water

*Human Explosion Damage Tweaks

On live, when someone is hit by an explosion, it willdeal damage based on severity: at severity 1 it will gib the person; at severity 2 it will deal 60 brute and 60 fire; at severity 3 it will deal 30 brute. In addition to this explosion damage, the mob will also get limbs dismembered based on the strength of the explosion.

There's two problems however; how the explosion damage is applied and how dismemberment is applied. When explosion damage is applied it will randomly pick *ONE* organ to take 90% of the damage and the other 10% will be distributed over the whole body; not only is this unrealistic, this causes problems when you factor in dismemberment. If the picked organ happens to be one that is dismembered, then the person will walk away with very very little damage from the explosion. The second problem is dismemberment itself; when a limb is dismembered, it creates a wound on the parent organ equal to the dismembered organ's max health. Normally this damage mechanic isn't a problem as you need to do more than the organ's max health to dismember it. That said, since explosions just call dismember directly it can result in explosions dealing loads more damaeg than they otherwise should. Sometimes explosions will out and out kill a mob (when damage should only be around 120) from the extra damage dismemberment causes.

Solution: explosion damage is now applied to the entire body, with 70% of the damage applying to the head, chest, and groin. Secondly, limbs that are dismembered by explosions (and only explosions) will not create wounds on the parent organ. This technically means that yes, getting a leg and foot blown off will reduce the amount of total damage you take from an explosion, but not by much. In general, you'll always take around 100-120 damage from a severity level 2 explosion; FAR more consistent than it currently is (which, on live, can range from as little a 40 to as much as 180+ from the same strength explosion).

### CODE REVIEW

**Comment by M3hillus** [comment]
:s I think removing welder tank rigging should be brought to the table for discussion.

**Comment by Fox-McCloud** [comment]
@M3hillus 

It's a relatively minor and very poorly documented feature that just allows any staff assistant to effectively have a high-powered on-demand explosion; I personally feel it's better if power like that is limited in access (science/chemistry) rather than broadly available to literally everyone; this isn't a window popper like the IEDs; it's a fully fledged explosion.

**Comment by M3hillus** [comment]
If by any staff assistant, you mean grieftider mc joe, I suppose, but It just feels you are limiting the actions of someone who would use it for a legitimate use.

**Comment by ZomgPonies** [comment]
- Removes fuel tank rigging and fuel leaking

Not a fan of this at all, seems like you're going overboard trying to bubblewrap the server. We have admins for that.

**Comment by M3hillus** [comment]
IIRC, Fuel leak was gone for quite some time, kinda miss using it when I was antag when you needed a little bit of the old ultra violence.

**Comment by Regen1** [comment]
Agree with ponies on this, I think we should keep fuel tank rigging

**Comment by tigercat2000** [comment]
I'll agree with Ponies and Regens, fuel tanks are supposed to be a bit dangerous, I think we should keep the rigging and fuel leaking.

**Comment by ZomgPonies** [comment]
I'm not sure about a lot of the logic in this PR. I think it shouldn't be merged until Fox explains his reasoning for the controversial bits, because I don't see the point in them.

**Comment by adrkiller59** [comment]
Well due to my inactivity i'm not sure how much rigging is abused. But since the floors were reinforced by ZomgPonies over a year ago so exploding weldertanks would not cause a breach anymore, welderbombing griefers practically dissapeared. I don't believe fueltanks are a real problem because i never heard any complains of any kind about it.
I'm mostly indiferent about fueltank leaking, but i'd appreciate if it had some proper trackable adminlogs in the investigate panel or something. I support the non-lethal projectiles not causing the tank to explode.

"NEW Feature: explosions (of any strength) will gib dead mobs."
I.... don't see the logic behind this... Why make this?

Also if this "floor change" will make welderbombs cause massive breaches in the middle of the station, then yeah no, I so much prefer our current floors. SO MUCH.

**Comment by Deanthelis** [comment]
This seems like a whole lot of work, for... What reason?
I genuinely don't understand the point of any of this, the only things I'd take from it are disablers not blowing up fueltanks, admins having logs of which projectile blows up a fuel tank, and the atmos backpacks starting out filled (which is completely irrelevant to the rest of the PR and really should be in its own).

I'm kind of leaning toward the refactor of how it deals damage; I'm kind of sick of having a leg fly off and suddenly being almost or completely dead. Spreading the damage out mostly evenly over the victim's body (70% to head, chest, and groin makes sense, since those make up... 70% or so of your body) seems much better than just randomly picking a limb to fly off and another body part to soak all the hurt. In fact, this means IPC will have middle ground, instead of being stuck between "there was an explosion and your head flew off, enjoy being dead until someone picks up all the pieces" and "there was an explosion and <one limb> flew off, the rest of you is fine".

However, explosions shouldn't just gib every single dead mob in their radius, because A. That makes no sense, and B. The number of ways players have to completely eliminate someone else from a round with no hope of return is rather limited and is limited on purpose, adding that in means an IED can dispose of any corpse ever.

Also, really? Taking away rigged welderbombs? Most players don't even know you can attach igniter assemblies to fueltanks at all. With Ponies' strengthened floors, they're hardly a grief threat. The worst you can do with one is kill someone that is -right next to the fuel tank-, which... I mean, it's mostly their fault if they're that close.

One thing I -would- recommend is some sort of delay or warning message, perhaps a second or two, between using a lit welder on a fueltank, because seriously, the number of people who accidentally welderbomb themselves is silly. Not to mention it isn't necessarily readily apparent what happened.

**Comment by Earthdivine** [comment]
Explosions slightly less effective against walls

This is, THE biggest reason to use any explosives, to get through a wall. Whats the point of getting C4 if it cant make the hole you need to get through? A one tile wide hole might help, but that nerfs the minibombs the Nuke Ops use too. Remember last time how when we redid explosions NO syndicate bombs could be used?

Updates Explosion code for floors to be more in line with Bay, TG, and Goon.

The floors were coded the way they are to prevent Welder bombs from breaching but other bombs still would still breach. If what the conversation in the skype chat we had was true, then ANY bomb breaches now. How is this better, now we got to be even more aware of what Civs are doing now.

NEW Feature: explosions (of any strength) will gib dead mobs.

Why. IED's are far more powerful now when they were meant to be fun little things to mess with. Now I never want to be near anyone with an IED, less they kill and gib me. Don't gib. Why gib. I thought we through realism out the door when it would keep people from playing the game.

Removes fuel tank rigging and fuel leaking

Fuel Leakings been gone, it was disabled in the code if I remember correctly, but this is a feature NO ONE EVER USED, and when they did it certainly wasn't for Greif. A greifer doesn't care if they get banned or not, why would they set up the bomb when they can welder it and blow it up.

I don't understand why most of this was nesscary.

**Comment by Fox-McCloud** [comment]
Sure.

Floor Changes

ex_act 1 already has (on live) a 87.5% chance of exposing *at least* one tile to space, so having roughly 14% more tiles being exposed to space, under ex_act 1, doesn't really accomplish much except more clearly delineating the boundary between devastation and heavy blasts; especially since ex_act 1 destroys everything, guaranteed, its blast radius (walls, mobs, structures, machinery, etc).

What it does buff is moderate explosions (ex_act 2; which really only impacts water+potassium grenades) sized explosions with a chance to defloor tiles hit--which combined with the rebalance/nerfs to human explosion damage, should work out nicely for the total damage the mobs should take.

Ex_act 1 still does what it's always done.

Dead Gibbing

I figured this would be controversial; primary reason to include it was just for a bit of fun--once you're dead your killer pretty much has total agency over you anyway, especially with dismemberment; just thought I'd give a semi-interesting alternative (keeping in mind gibbing leaves the head).

Rigging 

(fuel leaking was removed a long time ago from a mechanics standpoint; it's only the code for leaking that remains).

The reason for this change has absolutely zero to do with griefers and all to do with those who DO use it legitimately.

(Related note to floor changes: welder bombs, even with the the way floors are *on live* still far more often than the do not depressurize an area (87.5% of the time); ergo welder bomb griefing stopped for other reasons than the floor nerf.)

In general, I'm a firm believer that high powered weaponry of any sort should be relatively difficult to get your hands on as a non-antag (ie: plasma bombs take the knowledge to make and take a bit of time investment; IEDs create very tiny explosions, but are intended to be flame-based only in the future) or only put in the hands of individuals who have a high burden of responsibility (ie: security). Fuel rigging is a stand-out in this case; its explosive power is on par with a syndicate minibomb, but is accessible to literally everyone (and it strengthens traitors themselves by giving them a zero-cost way of dealing with a given situation)

@Earthdivine 

Regarding walls and C4: C4 has a specific proc to deconstruct walls--so it doesn't matter if the explosion is gigantic or non-existant; it still accomplishes its purpose (as a matter of fact when recursive explosions are enabled they don't  cause any size explosion). Furthermore; explosion code was updated by Bay a while back to do damage to walls directly instead of dismantling them; it had a 50% chance to destroy them outright and a 50% chance to dismantle them; that's really all it's doing is setting it back to this standard; 50/50 to destroy/dismantle instead of a 75% chance to destroy.

**Comment by Necaladun** [comment]
With welderbombs - Grief wise, I agree, no real problem with them.
Love disablers not setting them off, it's very hard to disable someone who has one.

The thing with welderbombs is how bloody obvious they are, even an engineer dragging a welding tank towards a breach is treated with heavy suspicion.

**Comment by fj45** [comment]
Think about rev/cult, they need some way (even if its highly obvious and bulky) to do some damage, double so when ERT turns up.

**Comment by SamCroswell** [comment]
The thing about the rigging of welding tanks to explode is that I _only_ see griefers do it. I have not seen antags use it to any capacity at all for the exact reason Neca highlighted above -- It's very obvious. If I wanted to rig set someone up to die via prox bomb the first place I would go is toxins, or if that is unavailable buy the big syndi bomb and rig it with a nearby prox + remote signaller assembly to get a much larger bang to ensure my target stays down.

A rigged welding tank gives a lot more power for the invested time than something like a tox bomb does, and is a quick and dirty way to piss security off when the grief fest starts.

As for Cult -- You have Jugernauts. If you need rigged welding tanks to inflict damage then you're doing something wrong. Regarding Rev: Yeah, It's probably the one gamemode where this is effective / relevant. You can still flash a scientist or make IEDs. (Note that I have no problem with IEDs -- They take a lot longer to make than a welder bomb and have a lower damage output.)

**Comment by ZomgPonies** [comment]
See that's the thing with welderbombs, I -don'-t see griefers use them because they get -1- shot at causing a shuttle call, and they will ALWAYS go the atmos or sciencebomb route. Until we see regular reports of grief regarding them, this -is- bubblewrapping. If it's not broken, don't fix it.

**Comment by Fox-McCloud** [comment]
Bubblewrapping would be removing toxins completely---or removing something like RCDs because they could be used for grief.

Again, that's not the active point I'm attempting to make; I'm removing it because it grants too much power to a particular class (regular station crew) for no investment, which also grants traitors additional power by lessening reliance on TC; it's the same reason we let traitors have Syndicate bombs, eswords, camera bugs and the like, but not regular crew---if antags already had access to them, they'd be even more powerful--not to mention the station's power level, itself would be brought up a notch.

Case in point: how often have you seen a traitor purchase a fully stocked toolbox (despite it being only 1 TC); why? Because they can obtain it legitimately with almost zero effort.

**Comment by adrkiller59** [comment]
Well... if rigged weldertanks are so powerful as you claim, why aren't they used more? I mean, if something is OP, then one could expect people to abuse it more, right?

Also, i personally bought the syndicate toolbox to escape from permabrig literally under the nose of the blueshield, so yes it has an use.

Speaking of camera bugs, that's an item i never saw used by any traitor, i'm not even sure how they work. 

And let's be honest, a robust traitor doesn't need the syndicate uplink alone, as he can accomplish all objectives flawlessly walking around with a syndicate balloon. You, Fox, are the living proof of it.

**Comment by ZomgPonies** [comment]
That's exactly the reason we SHOULD keep welderbombs. It levels out the playing field for all jobs as far as explosives go, rather than keeping it limited to science or chemistry. They can be used against xenos, blob, etc.

Also, what adr said. There IS no current balance issue with welderbombs, stop trying to fix what isn't broken.

Christ if you'd spend even a quarter of the time fixing the stuff that really DOES need balancing like acid smoke grenades, we'd all be so much better for it. Instead, we need to nitpick over stuff noone complains about in their current iteration.

**Comment by SamCroswell** [comment]
The same could be said about you and the damage changes you're intent on making.

**Comment by ZomgPonies** [comment]
The PR that I haven't put up yet? Yeah once it's up, I'll be open to any criticism and I'll be willing to change what needs to be changed in it. Also, that PR will address an actual problem, not some meta idea of global balance that hasn't been defined anywhere other than in Fox's head.

Please, stick to the topic at hand in these comments.

**Comment by adrkiller59** [comment]
There is no PR i can see about damage changes from Ponies yet. And even then, he did discuss it with the admins to get feedback and opinions on this before he got any work started, so it's not really comparable.

Also I want to point out that not everybody knows how to make a proper toxin bomb since it's a quite obscure thing and the wiki documentation tends to be outdated, not mentioning how restricted the access to toxins is. And again, rigged welderbombs were a thing since almost always, even if broken for some time. What makes it such a burning issue all of a sudden? The balance of the rigged weldertank is that they are an easy obtainable explosive that is EXTREMELY OBVIOUS to anybody.

**Comment by SamCroswell** [comment]
@adrkiller59 
Is that not what's going on right now? Discussion?

It was never a sudden and burning issue -- It was an addition to an already existent PR balancing explosion code. 

Welder bombs are far less documented than Tox bombs and far less used, and I'd argue you aren't in a position to assess the knowledge of the current player base as, unless I'm mistaken, you've been off the server for a few months now. Admittedly, yes. Wiki documentation for Toxins bombs is outdated. However there is *no* documentation to speak of for welderbombs.

@ZomgPonies 
The validity of the arguments being presented is entirely relevant.

In regards to 'Leveling the playing field'..
Why?
SS13 has always been un-level in terms of balance of job power. The argument is equivocal to saying we'll be giving all jobs the means to provide power to the station in case the engineering department is nonfunctional or incompetent.

**Comment by ZomgPonies** [comment]
What? Since when does powering the station = being able to set off a small-medium explosion? That's another strawman, it's apples and oranges between a specific role having a specific job and access to ways to do AoE damage.

**Comment by adrkiller59** [comment]
It's true that I have been inactive on the server itself for a longer period of time for reasons that are outside my reach. However, I do my best to keep regular contact with many active players, from inside and outside the staff, as well as read the forums at least twice a day, just to stay as tunned as possible to the code and community development of Paradise. The effectivity of my efforts might be arguable but I do what I can. Just wanted to clear that up.

And yes, I'm yet to hear what's so wrong with the rigged weldertanks. Is it being currently abused yes or not?

**Comment by Fox-McCloud** [comment]
@adrkiller59 

But...it's not extremely obvious until the assembly is placed on the tank itself; prior to that, it's just some random person pulling around a welding fuel tank. As for why they're not used? Poor documentation--the same reason hardly anyone makes any of the taclecrafting recipes (despite their power level)--this doesn't really impact balance so much as obscure it. 

As for doing traitorous deeds without TC? Yes, that should be a mark of extreme skill, not because you have more knowledge of game mechanics than someone else--traitoring should be *hard* without using TC---with stuff like welder bomb rigging, chem sprayers, etc--it's not.

@ZomgPonies 

Sometimes game balance isn't always about beating down an issue once it becomes a problem, but beating down problems before they become an issue or that are clear standouts. Sometimes this is obviously and issue even before it becomes one (roman jumpsuits giving +25 melee and bullet resist, for example leading to melee damage immunity with other armor); other times it's not quite as obvious.

I strongly disagree with the sentiment of leveling the playing field amongst jobs--particularly with non-traitor gear (unique traitor gear, however, is a different story); each job should have inherent strengths and weaknesses to it--no job should be a catch all in things it can do; choices (or lack there of) are important to gameplay to differentiate classes, jobs, and styles.

**Comment by ZomgPonies** [comment]
@Fox-McCloud - Maybe so, but this is the wrong way to go about it, and people have given their say as to why. You need to learn to bend, you are not the balance czar; this is a collaborative effort.

If it's not well documented, then document it, then wait and see, THEN make a PR about it if there's a problem at that point. Tons of things aren't well documented, it doesn't mean they should be arbitrarily removed.

**Comment by SamCroswell** [comment]
@ZomgPonies 
'a specific role having a specific job'

You mean like Tox and larger-scale bombings?

A better comparison would be allowing people to create makeshift magboots in case Engineering lapses on it's job and fails to keep gravity up or the generator is compromised due to aliens or blob, just like how these makeshift bombs would be used (*if* they were used) -- When science lapses on its job to create higher-yield explosives for emergencies.

**Comment by ZomgPonies** [comment]
We're talking about a huge difference of scale between a welderbomb and a toxins bomb. Scientists get to keep their quasi-monopoly on large scale explosions, like they always have even with welderbombs being in currently.

Seriously I don't know why we're still arguing this, this is a controversial change, the people have spoken, you're re-iterating the same flawed arguments over and over and just making this thread unreadable.

Fix the PR, maybe if you'd have discussed these changes before-hand with anyone, they could have told you some of the choices in it weren't such a hot idea. When you decide to take balance into your own hands with no prior discussion, you end up with controversy and unmergeable PRs.

**Comment by Fox-McCloud** [comment]
@ZomgPonies 

I'll wait to hear from Mark and Neca before I make any changes to this; ADR and your own opinion have been made abundantly clear here, while theirs have not.

@Markolie  @Necaladun

**Comment by ZomgPonies** [comment]
Neca already commented, but I guess that's not good enough for you?

**Comment by Fox-McCloud** [comment]
I'd like to know his opinion on it; is there anything wrong with that? His comment doesn't really address it as positive or negative; only that grief with welder bombs isn't really an issue--pardon me possibly misinterpreting here, but this doesn't exactly strike me as being for or against the change specifically.

**Comment by Nomzosha** [comment]
Gibbing of dead bodies isn't needed. If it's simplemobs, sure go ahead im coo with that. I would say leave actual player body-gibbing to C4 but that's been nerfed. While unlikely, I can imagine someone bombing medbay cloning 4thelulz and gibbing all the bodies if that's how it's gonna work.
Fuel tank leaking/bombings/riggings by griefers should be handled by the admins, unless you want to eventually nerf everything to hell and demote all the admins, then rename the server 'Teddy Bear Inc.'
Jokes aside.
Walls not being able to be boom'd as easily is just going to lead to even less engi work, think about the players. Since i'm not in a particular state where I want to reason well, I just want to leave off at that by discussing these projects/bugfixes/features beforehand, if this is denied, will lead to less wasted work.

that's my 2 cents.

**Comment by Spacemanspark** [comment]
Gibbing a dead body with any type of explosion? How is that 'Fun'?
No please.
As for the rigged fuel tank bombs, I say we leave it in, I rarely ever see it used, and when it is, it's pretty appropriate.
Same with everything else that people have said, remove the controversial bits.

**Comment by Fox-McCloud** [comment]
Spoke with Neca and made a few changes:

- Fuel tanks can still be rigged; overall station damage will be *roughly* the same as what it is on live; overall damage to mobs will be reduced (no gibbing people with them).

- Dead gibbing removed.

**Comment by tigercat2000** [comment]
I'm still not sure that floors should be changed to be able to be breached by only an ex_act 2, that seems like a major problem. Not to mention that ex_act 1 no longer has any RNG to it, it just has a flat 100% chance to breach to space, so any bomb that has a total devastation range is going to breach no matter what, without any chance to leave plating/lattice, even if those happen fairly rarely now, they still have a 25% (if I can read code correctly) to just not breach at all. As another point, when you use explosives, most of the time you want to break open a wall without breaching the floor, not the other way around.

**Comment by Fox-McCloud** [comment]
A bomb that has any devastation range already breaches 87.5% of the time, not to mention that the entirety of the code is consistent with "devastation" literally meaning destroying everything; mobs gibs, machines are deleted; everything is literally gone; even walls (which are mechanically, ICly, and logically more difficult to destroy than floors) are turned into space tiles when impacted by ex_act 1/devastation. Its fairly consistent for floors to follow this same mechanic.

**Comment by Regen1** [comment]
What I really hate about these new "balance changes" is that they are treating this as a game that you are supposed to /win/

I've never seen SS13 as a need to win the game, I play it for the fun of playing, not surviving the end of the round.
The fact that there are loads of different ways to get around things is what makes the charm of SS13 for me, can't access toxins to create a bomb? Use a welder tank as a weaker substitue for that.

I also agree with a lot of what @ZomgPonies is saying, don't try to fix something that isn't broken, I have had literally 0 problems with welder bombing, and I have very little of an idea as to where fox suddenly decided that "hey this feature needs to be removed"

**Comment by ZomgPonies** [comment]
Seems like all the reported issues have been corrected, merging.

**Pull request merged**
