### PR TITLE
Fixes two minor spelling/grammar issues.

### LINKED ISSUE #7530: Unknown Blob Grammar
**Problem Description**:

Unknown blob upon examination:

"Some blob creature thingy
It looks like it's of a unknown kind."

"a" should be "an"

Absolutely unplayable

IGN 0/10

(P.S. It was an admin bus round)

### LINKED ISSUE #7599: Safety typo
**Problem Description**:
Yet another typo in our midst! "Safety" is misspelled "Saftey" on both posters and on the pool temperature controller.

**What did you expect to happen**: 
For ALL the typos to be gone!

**What happened instead**:
I can still spot TYPOS!

**Why is this bad/What are the consequences:**
This typo appears in multiple spots, increasing severity

**Steps to reproduce the problem**:
It is a typo, nothing more.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: We must remove ALL of the TYPOS!

### PR DESCRIPTION
**Pull request by Birdtalon**
Fixes #7599 
Pool controller now reads "Safety" instead of "Saftey"

Fixes #7530 
Tweaked the description of the blob to no longer rely on "a" or "an".

🆑 Birdtalon
fix: Pool contractors have been back to school and can now spell "safety" on the controller correctly.
tweak: Minor change to blob description to address grammar issue.
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Github web editor, Reeeee

**Comment by Birdtalon** [comment]
I actually used Notepad++ for the Safety one. Do you want me to re-do it in Dream Maker @Fox-McCloud ?

**Comment by SamHPurp** [comment]
I'd have used Notepad++ for the safety one too, personally. Not sure the problem here, both bugs fixed in atomic commits. Seems good to me....

**Comment by Fox-McCloud** [comment]
yeah, notepad++ is fine for editing nano UI templates, but you should reallyyy not be using the web editor (if you can help it) for making changes to the code itself.

**Comment by Birdtalon** [comment]
I didn't use the web editor though. I used Dream Maker for the other commit. @Fox-McCloud

**Pull request merged**
