### PR TITLE
removes picture from all records

### PR DESCRIPTION
**Pull request by Ar3nn**
It's a nice touch, but for months this has caused a lot of crashing and as a result people don't use records as much anymore, and the fact that it doesn't happen every time makes people repeatedly report it because it seems fixed then strikes again. Removing this until it can be re-visited and the kinks worked out of it will help, in my opinion.

:cl: Ar3nn
rscdel: Removes pictures from security records to prevent crashes related to it
/:cl:

### CODE REVIEW

**Comment by Plotron** [comment]
k ;(

**Comment by TullyBurnalot** [comment]
To be quite honest, pictures offer nothing in comparison to what's on the rest of someone's records. Good riddance, I say.

However, if you really want to go through with this, make it affect Medical Records too, they still have pictures AND they still crash the game.

**Comment by Ar3nn** [comment]
Oh, right, I forgot the medical records were also affected. Whoops, I'll go do that.

**Comment by Kyep** [comment]
Pictures add little value. In theory you can ID someone by searching through the pictures of crew to find a match (red hair human, for example) but that's tedious and impractical on shifts with a substantial crew.

Yeah, you can probably just axe them.

Maybe, though, it would be better to hide the pictures under something that makes you click to see them. That way they don't load by default, won't crash you by default - but you can still look at them if you really want to.

**Comment by Ar3nn** [comment]
again though, just because they take it upon themselves to load the picture doesn't change the fact that they cause crashes.

**Comment by Kyep** [comment]
Correct.

But hiding them under something lets people see them if they really need/want to. Whilst still ensuring most people who browse the records (and don't click to see them) won't see them.

But, I would be fine with simply deleting them, too. They can always be re-added later when BYOND stops crashing as a result.

**Comment by Ar3nn** [comment]
Exactly. Anything that crashes a client simply by existing cannot be justified at all. Plain and simple.

**Comment by tigercat2000** [comment]
actually
i'm fairly sure the crash is from sending images, not displaying images
and this doesn't remove the sending images, just the displaying

**Comment by Ar3nn** [comment]
This honestly doesn't even do that. I'm still trying to track down where it actually displays, because (uncommitted) I have cleaned out all mention of photo from four separate .dm files and still they show up on local unabated.

**Comment by Ar3nn** [comment]
Well, that didn't work at all.

**Comment by Fruerlund** [comment]
No. Honestly its not that big an issue. When youve crashed once you dont seem to crash more anyway. 

Whats the point of records without pictures. Would make the wanted issue on the newscaster worthless again. If you have too add a button to go to the photo page or something similiar!

**Comment by Ar3nn** [comment]
I'd honestly prefer to get rid of the issue that causes crashes, but I can't even find where they're generated, so I can't do any of it at all. I've literally purged the words get_id_photo, var/icon/photo etc from the codebase and they still generate freely, so I can't fathom what to look for.

**Comment by Ar3nn** [comment]
yeap fuck it, its a tenacious fucker and I don't have the patience to do this. It reacted to me ripping out the get_id_photo(), but that just stopped it from generating the mob's icon in the photo. I found where it supposedly calls the clothes to go on the mob in the photo, but deleting those didn't seem to cause any harm to it. Thus, the PR shall be closed.

**Pull request closed without merging**
