### PR TITLE
Returns Customs to its former glory. Adds a few QoL improvements to Customs.

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Nanotrasen has decided to expand upon their efforts at stopping the Syndicate terrorist attacks. The best way was to, obviously, return Customs to the game. With some minor improvements.

BEFORE:
img

AFTER:
img

Escape Shuttle no longer has any windows:
img
Dirty smugglers and terrorist aren't getting in through those anymore!

In addition, all pods have been removed:

Arrivals:
Before:
img

After:
img

Security:
Before:
img

After:
img

Engineering:
Before:
img

After:
img

Gloriously, there is now no other way off the station except through Customs.
Due to this, our beloved corporation has decided to expand the capabilities of our hard-working Customs officer:

- Flash protection against filthy rioters
- Turrets placed in order to keep the peace
- Anti-Terrorism shutters
img

- Riot Control in the form of two automatic machine gun turrets and one grenade launcher:

img

- Customs Officers have been replaced with Peacekeeper Cyborg units

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
This is going to conflict with the arcade... also why no metastation customs?

Add that and I'll close my arcade map so you can get this in

**Comment by Ty-Omaha** [comment]
Only thing I don't like is how Customs Officers are replaced with borgs

**Comment by taukausanake** [comment]
Holy fuck what even is this? No one is going to like this not by a long shot. Even I don't know if I like it but I do think the escape pods being gone is a _kind of_ bonus? Really don't like them as an alternate means of escape. Maybe only activate during emergency alert but that's not this PR.

Sad that the space pod bay is gone. Not that anyone really uses space pods...

I'm okay with Peacekeeper borgs being Customs. If that's their only purpose people might be more okay with them. The problem comes when no one decides to play them because of that.
Wait, Peacekeepers aren't even ported yet. Trying to get the favor of maintainers? Not going to work. :^)

Fucking NO ONE is getting away on the shuttle now unless they emag and break in from outside.

We Military Station now. Would I be wrong to think this looks lime CM a bit? Never played it but I can imagine

**Comment by MrFroztee** [comment]
Looking forward to this being implemented, nobody should be getting on that shuttle without three background checks and a passport shoot. I'd advise also adding a ticket machine to the front of the line so people have to take a number and wait their turn, lest they face the wrath of Bureaucracy.

+1 from me, by all means

**Comment by ShibberinoShipperino** [comment]
Glory to Nanotrasenka!
As an Official Nanotrasen Health and Safety regulator we'd like to inform you that the Rocket Launcher in the execution room is deemed and I quote: "A wonderful addition to the execution room"

Our Space OSHA department holds slight concerns over the Turrets located, but we assume these are only loaded with blanks. Please remember to provide additonal helmets for not only the officers but any executed victim to comply with Health and Safety regulations.

**Comment by Jovaniph** [comment]
Speed Merge

**Comment by Ty-Omaha** [comment]
>No one is going to like this not by a long shot. 
i like this

**Comment by taukausanake** [comment]
I am speechless

**Comment by tigercat2000** [comment]
>not updating MetaStation

You swine.

**Comment by imsxz** [comment]
Forgot the window to the left of shuttle medbay, terrorists can still enter!

**Comment by scrubmcnoob** [comment]
this customs... looks amazing
just you're missing one thing
where's the ass probing machine 🤔 🤔 🤔 🤔 🤔 

and maybe a giant wall

**Comment by Doukhan** [comment]
No x-ray machines for the greyshirts to suicide with? ridiculous.

**Comment by KingPhilipIII** [comment]
Make sure they have their own SMES. Don't want to risk power failure and improper processing.

**Comment by granodd** [comment]
At first I thought this was serious, but then I saw you removed escape pods. 10/10 well meme'd.

**Comment by Birdtalon** [comment]
This is hilarious.

**Comment by Keilden** [comment]
Unbalanced, the south custom officer has a short walk to the rocket launcher.

**Comment by jughu** [comment]
HEY I NEED TO ESCAPE BLACKHOLE EATING STATION
I need to see you're papers first.

**Comment by Necaladun** [comment]
Why not just replace the shuttle with a singularity? Easier way to deny greentext.

**Comment by Ralta** [comment]
Secretly, @FreeStylaLT is saddened because his super-srs PR is being treated as a joke. He will play along, but will be dying on the inside.

**Comment by taukausanake** [comment]
If that's the case then at least I wasn't the only one who treated it seriously. Unfortunately I'm pretty sure I am the only one

**Comment by alexkar598** [comment]
We need inventory checking machines,ass scanner machine,x ray scanner .automatic mind reading terminating machine,instagib guns and some supper matter launching turrets. Without these changes this pr is UNACCEPTABLE!!!

**Comment by Dumbdumn5** [comment]
Much simpler fix, remove the station, customs is no longer required.

**Comment by TullyBurnalot** [comment]
Unfortunately, the new Customs Package was stopped at Customs for not carrying the proper stampage.

Entry denied, Glory to NanoTrasen.

**Comment by SamHPurp** [comment]
image
I come back later.

**Pull request closed without merging**
