### PR TITLE
Fixes, Genetics, and Balance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes and Genetics changes (some balance too)

Fixes:
- Fixes unstunnable mobs becoming permastunned when they get thrown into objects
- Fixes the NO SHOCK power; it prevented a tiny little proc that's almost never used; it's now the same as having insulated gloves
- Fixes Xeno leaping
- Fixes Xeno visible message when pounced
- Fixes stuns, weakens, paralysis, and sleeping not being instant (I'll explain this in a bit)*
- fixes slurring not being properly applied
- shifts jitteriness to its own proc so it behaves more consistently (doesn't have to wait on life proc)
- Fixes monkies being able to push fat people
- Fixes people not floating after doing an attack animation

Features:
- Adds in TG's shocking jittery animation. Basically, when shocked, instead of just falling down, you are frozen in spot for a short while, then you fall over (https://github.com/tgstation/-tg-station/pull/6347).

shock

Balance:
- self damage from power gloves removed (let's not punish people who can pull this off)

- A lot of the major genetics powers are now a lot harder to find; X-Ray no breathing, camo, and cloak of darkness now only have a 10% chance of becoming activated (instead of the regular 45% chance)
- TK acquisition chance lowered from 15 to 10
- Hulk acquisition chance lowered from 15 to 5

- Hulk is now a permanent mutation as it was before; overall goal is to make it more rewarding to punch things, but less rewarding to engage in weapons based combat--the mutation's unarmed ability is a bit stronger to factor in how much rarer and more difficult it is to find now, as well:
 - Specific snowflake boosts to item attack damage and throwing (and therefor stun chance) completely removed; you previously got a 2x modifier on weapons with hulk.
 - Hulk's punching now out and out stuns, in large part to compensate for their other damage/weaken boosts being axed (sorry, no more drills do 30 damage, spears doing 36, and eswords doing 60).
 - Hulks now operate off of CANSTUN/CANWEAKEN/CANPARALYZE/CANPUSH instead of a snowflake check specifically for hulk; this means that they won't be knocked over by airflow or slamming into walls, too.
 - Hulks scream when shot with tasers now

- Xenos no longer have the ability to move around freely in space
- Xenos have a chance to become paralyzed when attacked as opposed to weakened

*Explanation on making instant stuns more...instant. No, this isn't a buff to tasers, at all; basically what was happening is that when someone was stunned, paralyzed, or the likes, they wouldn't actually become impacted by that status effect until it ran on the next life proc. Currently weakening did update instantly--so you probably didn't notice any delay (since stunbatons, batons, tasers, and 99% of stuns you encounter have weaken AND stun on them); just making it so that it's consistent across the board in this behavior and to prevent some weird sitautions.

As an example of this messing things up; before this was fixed, you could shock yourself with this new door-shock animation then step 2-3 tiles away from a door before you finally got stunned by the shock---since it stuns first then weakens and it wouldn't actually stun you until the next life proc (roughly ~1.8 seconds).

### CODE REVIEW

**Comment by Earthdivine** [comment]
No breathing is not nearly as powerful as the other genetic powers, could we keep it higher then 10% at least?  With all the other powers being harder to find genetics would be getting nothing for most of their work, at least keeping no-breathe can help the other crew like Vox. If it's a problem with "geneticist sits for an hour and a half then walks out as a god", it'd be better to find a way to get them to work with crew for their powers rather then making them feel bored hoping for that 10%.

**Comment by Fox-McCloud** [comment]
I base my reasoning on two things:

(1) https://github.com/ParadiseSS13/Paradise/blob/9b60ee0f0bd794cc59884cbd3d3aa020033b7949/code/game/gamemodes/setupgame.dm#L52 it's already in with the hardest group to activate (meaning the block itself has to be set to a higher number)
(2)I'd argue it is as powerful; it means N2O, plasma, and  being in space do nothing to you in terms of O2 damage--that's pretty powerful in and of itself; additionally it means that you can remain in crit indefinitely since that makes you accumulate losebreath--and since NOBREATHING cuts off the "breathe" proc.

**Comment by Earthdivine** [comment]
....wait what seriously, it keeps you from recovering from crit? That's completely dumb.

If N20 or Plasma is in the air, you got bigger bigger problems then just not being able to breathe honestly. I would say the inability to catch airborne virii would be more of a problem then either of those.  As for space, that is a very powerful ability to have but to reduce it to 10% proc rate seems to be a bit much for something that comes up more sparsely.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

Nah, it keeps you from getting worse in crit. Meaning that other slowly die while you can be kept in that state indefinitely (until someone fixes you).

**Pull request merged**
