### PR TITLE
15 new hair styles from -VG-

### PR DESCRIPTION
**Pull request by tigercat2000**
Ports d3athrow/vgstation13#3729, titled: "Added 15 new hair options courtesy of Fury McFlurry"
**Original PR post:**
http://ss13.pomf.se/forum/viewtopic.php?f=9&t=1834
img
the icons in that image are white but they have since been changed to conform with the existing system
Fury did a really great job on these

Sidenote: requested by Zomg

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Osha and Nomzy will be pleased.

**Comment by fj45** [comment]
Four are just silly and oversized, but otherwise looks great.

**Comment by tigercat2000** [comment]
@fj45 i think that was the point

**Comment by SamCroswell** [comment]
Invasion of the floor-length braids.
:-1:

**Comment by Fox-McCloud** [comment]
Yeah---floor-length braid already kinda covers this; don't think we need hairstyles bigger than the mob sprites themselves.

A couple of these aren't too bad, but a lot of these are pretty bleh and gigantic.

**Comment by ZomgPonies** [comment]
so remove the two floor-length ones and keep the rest?

**Comment by Nomzosha** [comment]
If this is the only female hair, or just hair in general, expansion we're gonna get, I don't see why not. GIgantic hairstyles also removes the extreme blandness of our human females, who only choose emo/long fringe/floorlength braid because they're the only ones that look good. Floorlength braid, to me, personally does not look that good either..

**Comment by SamCroswell** [comment]
@ZomgPonies 

The three I dislike are the two floor-length braids and the one second from the bottom on the left (That kinda looks like a bird roosting on the person's head)

The rest are :+1:, so far as I'm concerned.

**Comment by ZomgPonies** [comment]
I'm personally okay with all of them. Gonna wait for more comments to see what we keep and what we axe, but more female hairstyles is always good.

**Comment by Iamgoofball** [comment]
@Fox-McCloud keep in mind this means more opportunities to splash super hairgrownium on stupid anime FLB/new FLB hairstyles stutterwhore doctors

**Comment by fj45** [comment]
For the females, axe 2 and 4.
For the males, axe 3 and 7

**Comment by M3hillus** [comment]
Keeping in mind, having the fuck-huge hairstyles on your person are a large negative. All the more to click on~

**Comment by Fox-McCloud** [comment]
my opinion:

hair

**Comment by Nienhaus** [comment]
tumblr_mdrdabv5fg1rzp1epo1_400
Must have.

**Comment by fj45** [comment]
That's it exactly fox.

**Comment by Iamgoofball** [comment]
>not wanting the incredibly long pompadour

i thought you were better then that @Fox-McCloud

**Comment by adrkiller59** [comment]
I'm fine with the female 2 and 4 and the male 3 and 7 as long as it prevents them from using any kind of helmets. And CANNOT be selected as an avaiable hairstyle when using a mirror.

Also captain caveman haistyle when.

Alt Text

**Comment by Fox-McCloud** [comment]
@adrkiller59 

Snowflake code for 4 hairstyles---badddd. lol.

**Comment by FuryMcFlurry** [comment]
Ahaaha, look at everyone vomiting because of my hairstyles, that is why I created them.

**Comment by Earthdivine** [comment]
You all are haters on the Pompadour and drill hairs.

**Comment by Iamgoofball** [comment]
@FuryMcFlurry b-b-but muh reals!1!!

**Comment by Spacemanspark** [comment]
I don't see issues with any of these.

**Comment by ZomgPonies** [comment]
So Dave, Fj and Fox for removing some, nobody else seems to care much one way or the other.

Tiger can you remove the ones Fox showed in his picture and we'll call it a day?

**Comment by tigercat2000** [comment]
Aahhh git please, stahp being insane- Removed the three in fox's image

**Pull request merged**
