### PR TITLE
Removes unused stripper uniforms

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
4 of these don't have sprites~~, the other is a mankini~~, none of them are mentioned anywhere else.

### CODE REVIEW

**Comment by tigercat2000** [comment]
why remove them
make sprites if they lack them :v

**Comment by LittleBigKid2000** [comment]
Do stripper uniforms really belong on a no-erp server?

**Comment by fludd12** [comment]
how else am I going to put tully in lingerie?

**Comment by Fox-McCloud** [comment]
>how else am I going to put tully in lingerie?

Very carefully.

**Comment by FreeStylaLT** [comment]
I have used the mankini. It has uses.

**Comment by LittleBigKid2000** [comment]
Re-added the mankini. Still removing the spriteless stripper uniforms.

**Comment by Ty-Omaha** [comment]
Their *uniform* is being naked!!!

**Comment by Aurorablade** [comment]
DO NOT TOUCH MY STRIPPER GEAR

**Comment by Fox-McCloud** [comment]
@Aurorablade 

It's ok, these all are unused and spriteless. Your stripper-Drask will live on.

**Comment by Aurorablade** [comment]
I USE THEM....JUST GIVE THEM SPRITES...

**Comment by Iamgoofball** [comment]
stop bullshitting, you don't use these

**Comment by GeneralGoose** [comment]
0/10 how am i supposed to yiff

**Comment by taukausanake** [comment]
Huh, I thought these did have icons. Maybe they looked more like sexy sleepwear that stripper things but I was sure they had icons.

Well I know what I'm doing now :)

**Comment by taukausanake** [comment]
And it did reference it twice. Darn

**Comment by TheDZD** [comment]
This has merge conflicts.

**Comment by LittleBigKid2000** [comment]
Fixes the merge conflict through magic. I don't recall actually making any changes (That I didn't undo) to uniform.dmi.

**Comment by taukausanake** [comment]
Well you might as well. If you're going to remove the stripper clothes you should remove the icons for them too

**Comment by LittleBigKid2000** [comment]
The stripper clothes that I'm removing don't have icons. I'm leaving the mankini, which does have an icon.

**Comment by taukausanake** [comment]
I didn't make any of those icons in my PR. They were all there already save for the icon icons for the suits. If you want to remove them then you should have removed their already existing and now unused sprites

**Comment by LittleBigKid2000** [comment]
What icons?

**Comment by taukausanake** [comment]
I don't know if you seriously didn't see the icons or if you're just pretending they don't exist because 2kinky4u. I really hate people like that and I have a friend exactly like that

**Comment by TheDZD** [comment]
These ones.
image

**Comment by LittleBigKid2000** [comment]
Yeah, I see it now.

**Pull request merged**
