### PR TITLE
Adds deathsound for Silicons

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
This PR adds a sound when a Silicon(such as cyborg or AI) dies. This will increase immersion and gives a clear cue that a Silicon has died, previously it was quite easy to miss a death message while fighting.

[Sound](https://raw.githubusercontent.com/Arkatos1/Paradise/918bee37d3d491d02350765d472349b4f2958e13/sound/voice/borg_deathsound.ogg)

Ported from /tg/station13.

Tested locally without any issue.

**Changelog:**
:cl: Arkatos
soundadd: Added deathsound for Silicons
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
That sounds dope.

**Comment by variableundefined** [comment]
All mob has a variable called deathsound that you should use.

**Comment by variableundefined** [comment]
@Arkatos1

**Comment by Arkatos1** [comment]
@variableundefined Fixed.

**Comment by variableundefined** [comment]
I'm so sorry, I messed up. I was looking in TG's code instead of ours. Ours don't have a death_sound defined at mob level for all mob. It is TG who has a deathsound, defined on the mob level. However that is quite a big refactor outside of the scope of this PR.

Can you go back to your original changes? I'm really sorry about this.
@Arkatos1

**Comment by Arkatos1** [comment]
@variableundefined Commit reverted. No harm done.

**Pull request merged**
