### PR TITLE
Customize Honk Sound for Clown Uniform

### PR DESCRIPTION
**Pull request by Fox-McCloud**
You can now var-edit the clown's uniform to give it a a custom sound to play when you abuse the clown.

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
can I turn it into the roblox oof sound

**Comment by Fox-McCloud** [comment]
Yep.

**Comment by Allfd** [comment]
🤡

**Comment by KasparoVy** [comment]
Lmao holy shite this'll be a fun one

**Pull request merged**
