### PR TITLE
Adds Picket Signs (Port from -tg-)

### PR DESCRIPTION
**Pull request by tigercat2000**
Do I really have to say "On the tin"? tgstation/-tg-station#8683
BorrowedImage

AnotherBorrowedImage

NotborrowedImage
[12:01:01 AM] Tigercat2000: Shadow Larkens waves around "NO PENIS SHAPED FOOD" sign.
This is a  NO PENIS SHAPED FOOD sign. It is a bulky item.
It reads: NO PENIS SHAPED FOOD#

### CODE REVIEW

**Comment by Spacemanspark** [comment]
That's lewd.

**Comment by tigercat2000** [comment]
Goat sim lel

**Comment by Finalsong** [comment]
I can have a picket sign that says "REMOVE CATBEAST?" yes please

**Comment by ClaytonKelly** [comment]
How do you make them?

**Pull request merged**
