### PR TITLE
Removes Away Missions

### PR DESCRIPTION
**Pull request by Fox-McCloud**
As requested by @Necaladun 

Disables away missions to encourage players to stay on the station more and cut down on powergaming.

Performance standpoint: 
- Cuts down on total instances by roughly 15%, which we were recently poked at by Volundr to address (less processing of atmos/object/etc).
- Game loads up significantly faster

My own two cents? Eh...slightly mixed feelings,but I'm really not sad to see these go.

Side note: 60 days streak for contributing to SS13; I've been doing this way too much.

### CODE REVIEW

**Comment by tigercat2000** [comment]
@Fox-McCloud

First off, I'll get out of the way; I don't support this in any way. 
I can write details later if I have the time.

Second off; If you are going to disable away missions, disable them properly.
Remove the gateway, for one thing.

Third; The game loading could be fixed in other ways, maploader isn't __that__ slow to load. It takes maybe 30 seconds, and it probably wouldn't be noticable if it didn't wait for the first client to login.

**Comment by TheDZD** [comment]
I have to agree with Tiger's second point, if away missions are being disabled, the gateway should be removed as well. That said, I don't have particularly strong feelings on away missions, I don't particularly like them and wouldn't be sad to see them go, but this shouldn't be done without actual discussion having taken place.

**Comment by FreeStylaLT** [comment]
But the station is booooriiiiing.


At least, like, make Metastation somehow usable or something in return. Away missions were exciting ventures at first and, unfortunately, have fallen into becoming static lootboxes. I mean, I get the optimization reasoning, but I rarely ever support content that gets removed with... nothing being added back in to compensate.

**Comment by Spacemanspark** [comment]
:-1: wait what why no.
I don't see a terrible amount of players jumping into the gateway, at least not so many that it really effects the station terribly much.

**Comment by Fox-McCloud** [comment]
@ Everyone here.

If you disagree with it that strong, then I strongly recommend bugging @Necaladun at it, as he far more strongly favors this than I do.

**Comment by tigercat2000** [comment]
@Fox-McCloud He should be watching this PR, no?

And at least, point 2 of my previous post was addressed specifically to you, about removing things like the gateway

**Comment by Fox-McCloud** [comment]
I'm aware--I'm not going to work on this any more than I have to though, due to its controversy and the fact that map edits tie things up; IF this gets to the point where it's going to be merged in, then I'll make the map edits then.

**Comment by Ultimate-Chimera** [comment]
:-1: :(

**Comment by Earthdivine** [comment]
I would say remove the emitter maze and keep the other two. The others can be used by other players for some fun times or some adminbuse events , but the Emitter maze is mostly just a big powergamer map with some syndicate stuff at the end, compared to the very tame items in the other maps.

**Comment by Necaladun** [comment]
Ideally, there'd be many more missions made adding variety and balancing the pre-existing ones. This was planned when the gateway was re-introduced, but has not happened. Plans have happened but nothing's come of it - if some really good gateway missions surfaced that'd be great.

Maps themselves either come under high or low-impact, the lowest-impact being the beach, highest being the danger room.

Removing/changing the high impact ones by itself is a good idea.

The low-impact ones aren't a great loss, having such low impact.

The problem here is as we make missions have lower impact, they become more irrelevant, and have less reason to stick around. I currently do not see the benefit of the gateway outweighing the costs.

**Comment by Robertha89** [comment]
In general, the gateway often works as a get outta hell free card, and alternativly, just make it default back to clown planet. I miss that place, was great for mining.

**Comment by Necaladun** [comment]
The gateway was never meant for mining, and with our new overhaul of mining is unnecessary. 

No one should be getting out of hell, especially for free.

**Comment by Robertha89** [comment]
There is also the fact that its great for events, like really great, but to make it great admins needs to be able to load away missions when needed, this would make a better use of it, and sending a fax to centcom could get them to open some of the away missions.
I rather see the use changed somewhat then removed completely, like for cultists away missions are great as they are allowed to research without getting discovered.

**Comment by KasparoVy** [comment]
The only reason why I like the gateway is the beach

otw it might as well not even exist

**Comment by Necaladun** [comment]
Cultists using the gateway for research was completely not intended, and another reason it should be removed IMO

**Comment by Markolie** [comment]
Don't really care either way - but people (and antagonists) using Moon Outpost 19 or Underground Outpost 45 as an "alternative" station very much was intended. People on Paradise don't really seem to interested in huge "building projects" where they fix large portions of something or build a new station, but MO19 and UO45 certainly allow for a lot of opportunities for these projects that I personally find very enjoyable. If security finds that antagonists are using the other stations for nefarious purposes, then lock them down. There's only a single entrance into the gateway, and it's surrounded by rwalls.

Also, I'm not sure why we've gotten to intent on fixing performance issues by removing stuff. Sure, it slows down the load of the server, but it adds plenty of content. Fix it, don't remove it. Or find something else to optimize, as I'm pretty sure away missions aren't a primary source of lag.

**Comment by Keilden** [comment]
If keept make it harder to activate the gate. Maybe have the need for some stuff from end level RnD and rare materials.

**Comment by Krausus** [comment]
> Performance standpoint:
> 
> - Cuts down on total instances by roughly 15%, which we were recently poked at by Volundr to address (less processing of atmos/object/etc).

Total instances mainly matter when something has to be directly deleted. We would save a lot more instances, with less impact on players, by removing several of the space Z-levels. They're less interesting, less accessible, and more predictable than most away missions as it is.

> - Game loads up significantly faster

This is completely irrelevant outside of local testing. What we need for _that_ is a config option to disable away missions without having to edit the mission list.

@Necaladun
> I currently do not see the benefit of the gateway outweighing the costs.

The technical costs of the gateway don't really matter. We waste more resources on less elsewhere.

> The low-impact ones aren't a great loss, having such low impact.
> 
> The problem here is as we make missions have lower impact, they become more irrelevant, and have less reason to stick around.

I've seen plenty of players have fun just exploring some of the more interesting (i.e. not the dumb emitter maze) away missions. There's more to the game than collecting phat lewts.

> The gateway was never meant for mining

> No one should be getting out of hell, especially for free.

> Cultists using the gateway for research was completely not intended

Gotta be honest, these make it sound like you just hate emergent gameplay.

**Comment by veganzombeh** [comment]
I support removing them, actually. They're stale and used almost exclusively to powergame or as an easy way to escape danger on the station.

If away missions are removed, the gateway itself should either be removed or functionality should be added for admins to use it for events.

**Comment by Alex6511** [comment]
Regarding having additional away mission, unnoticed there are several others in the code but they cannot be loaded in the map editor. Are these maps just waiting to be ported? Would porting them help resolve some of the problems with them? I think the issue here is partly because of the low variety of the missions, as well as the fact that they are not very dangerous (which could be argued is due to the low variety, people have had plenty of time to learn how to "beat" these missions). If we removed the current gaunlet (because its a lootfest) and created more high risk high reward scenarios, would that resolve your concerns Neca?

**Comment by Spacemanspark** [comment]
I still think my idea for a dungeon crawler gateway mission with holographic weapons (So they can't be taken out of the gateway.) and various checkpoints which one could use to get back to the station, is a good idea.

**Pull request closed without merging**
