### PR TITLE
Makes Bubblegum fightable

### PR DESCRIPTION
**Pull request by Edan52**
## What Does This PR Do
This PR makes Bubblegum's attacks a little bit slower to account for paradise movement speed so that the fight is possible without a load of cheese. This doesn't make it an easy fight by any means, but possible with regular miner gear. Here's a video showcasing the changes: https://streamable.com/f724j

This PR now also removes the bottle of mayhem and blood contract from the loot pool (for now at least).

## Why It's Good For The Game
Bubblegum should be very hard to kill, but not almost impossible.

## Changelog
:cl: CornMyCob
tweak: Bubblegum attacks a bit slower, making him possible to kill
/:cl:

### CODE REVIEW

**Comment by Carthusia** [comment]
I like the idea, though he seems...i dono, to slow now? I mean you 1v1d the guy with a KA and some med patches

**Comment by Gatchapod** [comment]
You have beaten Bubblegum with the most basic of gear almost any semi-experienced miner has 40 minutes into the round, if not earlier. The only exception is fireproofing, which is semi-rare, but can be countered by killing Bubblegum faster.

Bubblegum is not supposed to be "possible with regular miner gear". The whole idea of megafauna goes against that.
Even BDM and Hiero require certain preparations to ensure it's safe to engage them, though it's adequately easy to prepare for them. The Bubblegum you suggest requires just walking left and right with one range mod in your KA, maybe even without it.

I play a miner quite a bit and my opinion is that current Bubblegum suits Paradise just fine. If you are insane enough to prepare for the fight and pull it off, you deserve the fucking bottle and contract to give admins a headache. Otherwise, Bubblegum is just that thing you avoid, like an ascended shadowling. Don't fight. Run!
This PR, any any significant nerf to him, would lead to Bubblegum being dead every single round and we're back in the days of multiple lesser ash drakes roaming the station every round.

**Comment by datlo** [comment]
I agree that the fight is too difficult but this seems like too much in the other direction, as explained by Gatchapod.

**Comment by CornMyCob** [comment]
> Bubblegum is not supposed to be "possible with regular miner gear". The whole idea of megafauna goes against that.

All megafauna can be killed with pretty basic miner gear and I don't see the problem with it if you're experienced enough. The BDM preparation you speak of consists of putting 6 goliath plates on your explorer suit and tanking it and shooting it, and you can fight the rest of the megafauna with just a first aid kit and maybe a fire extinguisher for the ash drake. How can you currently prepare for the fight? The only ways I've heard involve insane amounts of cheese.

> The Bubblegum you suggest requires just walking left and right with one range mod in your KA, maybe even without it.

Isn't that the same for the rest of the megafauna? You can say the same for all fauna on lavaland, that's how all PvE combat is in this game if you simplify it down to that level.

I don't see where this idea of bubblegum being the hardest boss on lavaland has come from. I think that should be legion if anything. This is the first set of values that seemed to work quite well for him, any faster and he'd just hit you every time he charges. I could maybe make the lower health attacks happen a bit quicker. These nerfs still make it nowhere near as easy as the old ash drake in my opinion, one step in the wrong direction and you're punished with pretty much guaranteed death a lot of the time.

**Comment by Gatchapod** [comment]
Ash drakes require nearly perfect reaction time and kiting as complicated as the engine allows for. You pretty much have to bring unique items to deal with it safely, like fire extinguisher and Legion cores, because even the tiniest slowdown can kill you. Unless you have a guardian, then it's not a real fight.

Colossi are exclusively dodging and, if you play with a crusher, timing. Almost everyone's first colossus kill is with a meatshield, which is hardly "regular miner gear".

The Legion requires you to build specifically around that fight and, to a minor degree, tests your multitarget combat. It's not a hard one, but it's long and mistakes can be very unforgiving.

None of these involves moving back and forth in a straight line with no chances of getting hit.



> This is the first set of values that seemed to work quite well for him, any faster and he'd just hit you every time he charges.

Well, I hate to be the "git gud" guy, but using basically the same technique you are using, I managed to reach a decent amount of dodges on unmodified Bubblegum. The problem seems to mostly come from the third charge that requires you to "feel it", rather than respond to it.
If you don't have a few preserved cores on you to counter slowdowns, you shouldn't be doing top tier megafauna.
If you do have the cores, getting hit by the third charge (in practice the only actually dangerous charge) is not as disastrous as it might seem. Even if you get hit twice in a row, without slowdown you should be able to disengage.

I'm not saying Bubblegum is perfectly doable, let alone easy. However, what you suggest would make the kill so unrewarding I wouldn't even bother with trying.

**Comment by Gatchapod** [comment]
Well, time to be more fair instead of being a naysaying asshole.

After the author asked me to actually test the fight, I have come to conclusion it is far from trivial.
I used a similar setup, but picked only 1 ranged KA mod.
While the first phase (triple charges only) is absurdly easy, I suppose it never was that much of an issue, anyway.

The problem begins once hallucinations join in.
If RNG likes you, the speed is irrelevant. Walking straight will always work.
The difference comes into spotlight when RNG decides to hate you. If you misstep in such a case or predict his path incorrectly, you will take a nasty hit.

On live, this is the end of you, unless you have a Legion core buff on you. The slowdown from the damage will almost certainly result in another hit, likely putting you in a crit while your screen shakes so badly you can't apply that brute patch to yourself. Effectively, the fight revolves around pretty much the impossible: Never getting hit.

On this PR, you are actually capable of continuing to dodge even after getting hit. This is a massive change, as it makes mistakes much more forgiving. If you play it well, you can heal yourself.
Not only that, but mistakes genuinely feel like mistakes, not just RNG deciding it's the end of the round for you.

Overall, this PR doesn't make Bubblegum easy, as I unfairly implied. It merely makes him manageable, more in line with other endgame megafauna.
Regarding my fear the bottle and the contract might become commonplace, I now highly doubt it will be the case. In this PR, he requires discipline, skill and a fair chunk of practice (and low ping). People with those usually have enough common sense to not abuse those items.

I am still fine with the current state of Bubblegum, but I no longer think this PR is a bad idea.

**Comment by nok-ko** [comment]
On a related note, I think the playerbase would appreciate guides on fighting megafauna written by experienced miners like @Gatchapod on the wiki. (Or any Lavaland content there at all, it's very sparse right now.)

**Comment by KasparoVy** [comment]
i'M dOn'T aFrAiD oF aNyThInG

**Comment by trololiver112** [comment]
While seeing that video made it look a little too easy, i agree it should not be as hard as it is right now. And on that you should not be able to do it with only mining gear, you can already do that. The only thing you need from outside mining to kill bubblegum in its current state is drugs for speed. If i was to say what would make this fight the best in my opinion it would be possible with extreme practice, but never easy. People should fear this thing and probably run away yes. But miners who practice the fight should also be able to fight it without just being dumb lucky or having to do tons of drugs for speed.

**Comment by MRgaty** [comment]
> While seeing that video made it look a little too easy, i agree it should not be as hard as it is right now. And on that you should not be able to do it with only mining gear, you can already do that. The only thing you need from outside mining to kill bubblegum in its current state is drugs for speed. If i was to say what would make this fight the best in my opinion it would be possible with extreme practice, but never easy. People should fear this thing and probably run away yes. But miners who practice the fight should also be able to fight it without just being dumb lucky or having to do tons of drugs for speed.

Considering what kyet said I dont think miners should be able to fight him at all, with practice or without it

**Comment by CornMyCob** [comment]
> Objection: I don't think bubblegum, who is supposedly meant to be the king of slaughter demons, should be beatable with regular mining gear.

Well he basically is, as are all other megafauna, the difference being right now you need to use drugs to get insane movement speed to have any chance at killing him. If this is the strategy you want for killing him then I'll close the PR, I'm fine with that.

> He should be an enemy you have to avoid, rather than fight.

He was buffed to be more difficult, not impossible. What's the point of having him be unkillable? All this does is mean miners won't go near him and he'll be protecting a certain area all round which is quite honestly really boring, especially when the code for a fun fight is already there.

>  I don't like this mentality whereby players expect to be able to beat every monster that exists in the game, and never have to run from anything.

I find the idea of having an unkillable monster in the game extremely unfun, and these nerfs by no means make him easy to fight or kill. It took me many attempts to kill him and I'd probably still not fancy my chances if I saw him in game. In my opinion, this would still make him by far the hardest megafauna with one of the hardest learning curves, as any mistakes like misstepping are punished with death almost all the time, even more so now that patches have been nerfed.

**Comment by nok-ko** [comment]
> I find the idea of having an unkillable monster in the game extremely unfun
Seconded. "This is Bubblegum country, son, stay out" is not an engaging game mechanic. Where the Ash Drake, BDM, and Colossus are fightable if you're prepared and you know what you're doing, Bubblegum may as well be an aggressive, moving chasm to most miners. Worst of all is the fact that currently the megafauna AI doesn't stay far enough away from the mining outpost, leaving miners out of a job due to wildlife problems on some rounds. If you get Bubblegum right outside the station windows, sometimes your only bet to continue mining is to ask Sec to let you onto the Labour Camp. Woo-hoo.

**Comment by trololiver112** [comment]
Having actually tried this fight i can safely say that it’s not an easy fight. While it might seem easy since you are able to dodge most of his attacks that is because you have to dodge almost all his attacks to survive.
My first attempt at it with really good stuff ended up with me getting hit by his second triple attack move. This immediately put me in crit and ended the battle. I didn’t have time to heal.

This is what i think is good though, to do the megafauna now you need perfect movement and to almost not get hit at all. This pr still makes it remain as the toughest megafauna, just beatable if you do the fight perfectly.

And if the goal really is that he is not suppose to be beatable, all you’re doing is having a 7 by 7 area in lavaland you dont walk to. And it even has audio warning.

**Comment by Fox-McCloud** [comment]
Support this, though I need to do the math on the specific numbers.

**Comment by trololiver112** [comment]
People that are able to kill bubblegum, even after a nerf are probably not doing it for the loot itself. And definitely should have enough hours to know why they can’t use any of those two hijack items.
This can also probably be fixed by adding a small warning check. Non hijack players can still put a BOH in a BOH and spawn a singularity, and the only thing stopping that is a small warning box.

Overall i really disagree with the argument that bubblegums items means he can’t be made possible to kill. Sure the items cause lots of chaos, but shouldn’t that be something we could look at changing instead of making bubblegum unbeatable? 

As it stands currently it is really easy to avoid BB with his warning sounds and blood. All this makes him really is a big box you can’t get close to because he will insta kill and gib. There isn’t really any fun in that, and at that point you honestly might as well remove it.

It’s a damn shame too i must say, as the bubblegum fight I did was one of the most stressful, yet the most rewarding megafauna fight i have had. And it had absolutely nothing to do with the mayhem in a bottle i got and saved until the round had ended.

**Comment by Spacemanspark** [comment]
A singularity is easily deleted and its damages rectified if it's caught fast enough, even if done in a highly populated area.

The way bubblegum's chaos drop works impacts _everyone_ all at once, however. Anyone on station and off it gets a knife and orders to kill a specific individual, and the victim gets a chainsaw and orders to kill.

It's an immediate disruption to everyone's round.

Honestly? Just remove the item altogether and find something new, while merging this in. It really isn't suitable for Paradise.

**Comment by trololiver112** [comment]
Either way the main message of my comment means the same. 
If the issue lies in the items, isn’t that what we should look at removing? Not making bubblegum unbeatable, as that just feels like a half fix that could so easily be replaced with something like removing the items.

In conclusion, the argument that bubblegum shouldn’t be beatable because it can drop items that are problematic is a easy to fix point. Honestly, the spellblade and armor alone is probably enough when paired with the glorious feeling of victory

**Comment by Spacemanspark** [comment]
To clarify, I wasn't necessarily saying that bubblegum shouldn't be tweaked (although it should still be very, very hard to fight imo, as all megafauna are, but even harder) but moreso just making a point about the drops themselves.

A lot of the megafauna drops really don't fit with Paradise tbh, and it shows. We've removed hierophant after players managed to solo entire nukie teams with the staff from behind a wall, we've had endless discussion regarding ash drakes giving the ability to take on the lesser form of one, legion staff turning entire areas into ash storms indefinitely, lava staffs that can make floor tiles instant death traps, so on so forth.

Blood drunk miners are probably one of the more interesting megafauna. They pose a solid challenge and drop a useful item that's not ridiculously overpowered (and also makes a subtle but nice reference to Bloodborne, if I'm correct)

**Comment by Fox-McCloud** [comment]
>A singularity is easily deleted and its damages rectified if it's caught fast enough, even if done in a highly populated area.

The way bubblegum's chaos drop works impacts everyone all at once, however. Anyone on station and off it gets a knife and orders to kill a specific individual, and the victim gets a chainsaw and orders to kill.

Yeah, I don't buy this.

Viro lethal viruses, BoH detonation, and tank transfer bombs all fall into a similar category and yet all 3 are not really that problematic, on the whole--they tend to cause widespread damage and impact and none are particularly easy to clean up after if someone messes it up. 

Contrast this with something that's easily handled by an OOC "ignore the urge to kill; that person is griefing." followed by banning the offender in question if it's not legitimate--fairly easy to handle; the AoE blood rage is even less impactful.

Not everything has to have an explicit use case purpose that is useable by the crew 100% of the time--otherwise we'd have to start purging a lot of stuff like lethal viro, BoH bombing, tank transfers, slime enraging, chems like sarin and what have you.

**Comment by Spacemanspark** [comment]
Build mode is a thing and I've used it to clean out singulo grief many times, enabling rounds to continue.

Not to say it's _always_ going to work, but it's generally fixable if caught soon enough.

Bubblegum's item _might_ be rectified fast enough, if you, as an admin, can check the person to see if they're an antag fast enough, and if their not/don't have an objective relating to that person, say something in OOC before murder starts happening.

And yes, admin rejuv is a thing, the aftermath can still be cleaned up and such. But the fact still remains that this impacts EVERYONE at once. Its a sudden disruption to everyone's round and frankly I don't find that alright.
Thusly, I don't buy into your argument either.

**Comment by CornMyCob** [comment]
While I agree that the loot could potentially be used to grief and doesn't really suit the server well, I don't think it's going to happen anywhere near as often as it's being made out to be, or at all the be honest (I can't see this being killed very often at all), particularly considering there was a time where he was a LOT easier to kill than this, with the same loot, and I don't recall a single case of it being used to grief.

That being said, if you can suggest any ideas for replacement loot @Kyep @Spacemanspark I'd happily try and add them.

**Comment by Kyep** [comment]
@CornMyCob 
I'd say change the loot of /obj/structure/closet/crate/necropolis/bubblegum to this:
/obj/item/clothing/suit/space/hostile_environment
/obj/item/clothing/head/helmet/space/hostile_environment
/obj/item/gun/magic/staff/spellblade
IE: just remove the chance for it to drop either mayhem or blood contract.

If you did that, I'd probably support this PR. I'm okay with bubblegum being fightable, but I'm not okay with the mayhem or blood contract being obtainable.

**Comment by CornMyCob** [comment]
Removed the bottle of mayhem and blood contract from the loot pool, wasn't quite sure where to move the code for them so I've kept them where they are for now.

**Comment by variableundefined** [comment]
Stalled for too long. Merging.

**Pull request merged**
