### PR TITLE
The STUNMAGGEDON: Goodbye (most) ranged stuns and analyzing some melee stuns edition

### PR DESCRIPTION
**Pull request by Cocacolagua**
Draft because:
- [ ] Need a new sprite for the disabler since it's ugly, and also disabler+seclite attached sprite is broken
- [x] Allow flashlights to be connected to cisablers, the same way you can connect them to tasers
- [ ] Given that there's atleast four months until the PR is considered, might as well rebalance all antagonist and random objects that come with this change, or atleast give reasoning on if they're fine as is.
   - [ ] Vampires (glare, rejuvenate, shadow walk and mist form)
   - [ ] Blood Cultists (flagellant robes, mirror shield, runic bola and stun hand)
   - [ ] Traitors (e-bow, adrenal implant and the mime gun)
   - [ ] Nuclear Operatives (the mind batterer and the C20-r)
   - [ ] Changelings (their anti-stun, epi overdose and strained muscles)
   - [ ] Chemicals (specifically the anti-stuns, please contact me on the chemicals affected as i'm not an expert on chemistry)
   - [ ] Shadowlings (i don't even know what will happen to this gamemode without instantstuns)
   - [ ] CNS (probably fine as is)
   - [ ] Mining Meathook and Banana Staff(probably deserves a full rework/replacement)

## What Does This PR Do

Replaces the hybrid tasers to disablers to the following:
- The Armory.
- The warden's locker.
- The roundstart equipment from security officers, security pod pilots and the warden.

Removes some stun stuff:
- Taser crate from cargo.
- The option to print the mecha taser or taser ammo for the shotgun.

And also some other stuff:
- HOS's taser module consumes more charge, only letting him fire three golden bolts before running out of juice.
- Blueshield's revolver lost his taser module, replaced with a disabler module (sprites included).
- ED209s are now crafted with disablers instead of tasers, but still fire taser shots.
- Allows Seclites to be attached to the disabler.

## Why It's Good For The Game
This PR is far from perfect, as the stamina system is also not the best...
but god is there a lot of bitching about ranged stuns, which fair enough, now you can have this PR and be happy or something.
Main reasons why ranged insta-stun combat is bad are:
- It makes the combat very uninteresting, just click on the opposite gamer and be done with it, making some slower weapons a gimmick rather than a considerable side-grade.
- You can be game-ended quite easily with these, so roleplay is hard to come by. Why slow-down to talk with security when they will probably one-hit KO me? (or by antagonists as well)

Recommended testmerge.

## Changelog
:cl:
del: Taser crate from cargo.
del: Printable Mecha Taser.
del: Printable Stun ammo for the shotgun.
tweak: The armory now has disablers instead of hybrid tasers.
tweak: Security officers, the security pod pilot and the warden spawn with disablers instead of hybrid tasers.
tweak: The warden's locker now has a disabler instead of a hybrid taser.
tweak: The HOS's gun can now only fire three taser shots before running out of charge.
tweak: The Blueshield's revolver fires disabler shots instead of taser shots.
tweak: ED209s are now crafted with a disabler instead of a taser.
tweak: Seclites can now be attached to disablers.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Oh god not this again

Also this is a map edit which means its blocked for about 4 months

**Comment by Cocacolagua** [comment]
fair enough

**Comment by FlattestGuitar** [comment]
> Also this is a map edit which means its blocked for about 4 months

TG has great merge drivers that help with automatic conflict resolution. Adding that to your codebase's toolset is probably a better solution than whatever this comment is trying to accomplish, @AffectedArc07 


This is an undeniable hard nerf to security. It'd be good to see some thought put into how antags work with this as well. 

I think you could've put some more effort into the justification blurb for this PR. Two good arguments for this are:
* This lowers the tension during encounters with the "enemy", making RP in those moments less risky. More RP = more good. Nobody can disagree.
* The vast majority of fights are over as soon as a stun lands. This way they won't end with a single mistake, but rather to a short series of related mistakes.

I applaud the courage 👏

**Comment by AffectedArc07** [comment]
> TG has great merge drivers that help with automatic conflict resolution. Adding that to your codebase's toolset is probably a better solution than whatever this comment is trying to accomplish, @AffectedArc07

@FlattestGuitar we *have* those merge drivers, just we said no map changes till SM port is in.

**Comment by Cocacolagua** [comment]
@FlattestGuitar thanks for the imput, PR description was updated on the "why it's good on the game", and will tone down some of the extreme cases of antagonists stuns.

**Comment by procdrone** [comment]
consider also touching on all the stun related chems/implants, they will kinda loose their function with removal of the golden bolt

**Comment by Spacemanspark** [comment]
Good luck... and also about time someone had the balls to step forward and properly attempt this. 

I still hold some vague, six year old bitterness towards this topic, and as such I'm merely giving my approval and backing away. The stress of this topic alone is probably going to give me white hair strands at the age of thirty.

**Comment by Cocacolagua** [comment]
Changes made: Reverted ED209 nerf, it fires electrodes, but will be crafted with a disabler. Although you could say it doesn't make much sense for a disabler to fire electrodes, I believe it's necessary so this thing becomes a formidable threat for once, as it'll be one of the only ranged stuns in the game.

**Comment by Krysonism** [comment]
/tg/ has a nice looking disabler sprite you can use.

Does paradise have knockdowns(drop items + forced crawling)?

They are used as a more fair substitute for stuns on /tg/ in some instances. 

For example, the /tg/ antag that is closest in design to the paradise vampire; heretic, has a melee attack that deals like 80 stamina and knocks down.

**Comment by Cocacolagua** [comment]
@Krysonism I'll check out their disabler sprite and see if it fits, thanks.
Also no, we don't have the crawling mechanic here, albeit it would solve a lot of issues.

**Comment by shmabuu** [comment]
If the name of this PR is to remove **ranged** stuns, I don't see how cult stun hand and vampire glare fit into that, as they are not ranged stuns. I may be misunderstanding something, if I am, let me know. 
A stamina-based system with crawling as we all know would be great, but is out of the scope of what this PR is for. It is great to see someone PR this, no matter how small the change, our combat system needs to change at some point.

**Comment by Cocacolagua** [comment]
@shmabuu Title updated to be clearer, the vampire glare and cult stun hand won't be removed, but it's something to take in consideration in this PR to see if they may be too strong without instant-ranged stuns for security.

**Comment by procdrone** [comment]
> @shmabuu Title updated to be clearer, the vampire glare and cult stun hand won't be removed, but it's something to take in consideration in this PR to see if they may be too strong without instant-ranged stuns for security.

Disable lasering a vampire is actually more effective than tasing them - as stamina damage incurs penalties to movement speed, and if you're not a nutcase (fighting a vampire alone), after getting up from the stun (and glaring you) they wont have full speed to run from your backup.

**Comment by Varghh** [comment]
You have my absolute support for this, feel free to ask me for help or whatever

**Comment by Necaladun** [comment]
I appreciate someone trying to tackle such a long debated topic, but I have to object to this on several reasons - most of these are rehashes of the issues I've raised with similar PRs in the past. I'm also going to give a fairly hard rejection now so too much work isn't put in before this is all taken into account.

I don't object to people trying to fix the combat system - but to do so is an incredibly huge project that needs to be done properly, and take into account the balance between every single antag type, security, crew members, the clown, etc. This is something that should have a design document and all that, and would be one of the largest projects taken on from a balance perspective. 

Removal of some, but not all stuns, will only increase the power of the remaining stuns. Flashbangs will become the new meta, followed by batons, water, tasers, etc. Years and years worth of PRs have taken into account what stuns are available, to who, where, and when. You cannot "fix" the combat system by simply removing the most obvious of stun weapons. The cancer of stun has metastasized, if you will. A holistic approach is needed that tweaks or changes a spread of things across the game. 

Having seen the effects of removing tasers (and even having batons only do stamina damage), I don't believe that it leads to roleplaying being "hard to come by". That's a ridiculous over exaggeration. A vast majority of RP has nothing to do with stun based combat. The idea that we are losing out on all this RP because people can be stunned I simply don't accept. This is all based on some hypothetical situations where security and an antag choose to engage in combat rather than talk to each other, all because they can instant stun each other. 

People aren't going to stop and discuss their life stories because of this. If someone is wanted as an antag, sec are going to bring them in. Greytiders will yell insults at them. Communication and RP are still possible between them, both before and after they go loud or get caught. RP is still RP if it's happening in prison or over comms.

I have seen security and antags interact when they only had disablers, nerfed flashbangs, and stun batons that do stamina damage. Whoever shot first still won. This shouldn't be an absolute thing, but you should always be at an advantage when you're attacking an unarmed and unprepared target. I have also seen numerous combats where someone has been hit by a tazer but still gotten away. 

Security also really don't need nerfs there - it's a very unpopular job with a huge turnover rate. Antistuns have been added and tweaked over the years to give antags an advantage here, while still keeping security easily able to deal with greytiders. Tasers are great for the less robust sec to be able to get an edge over greytiders.

**Comment by Cocacolagua** [comment]
Talked with kyet about whether there were more objections/approvals for this PR, was instructed to close it for now, it probably isn’t coming back but it is what it is.

**Pull request closed without merging**
