### PR TITLE
Issue #12438 - Abductor Surgery Fix

### PR DESCRIPTION
**Pull request by PidgeyThePirate**
## What Does This PR Do
Addresses Issue #12438. Abductor surgery will now remove heart subtypes. Also capitalized the surgery names for consistency. 

EDIT: Removed the ability to take out IPC cells. The surgery doesn't compensate for its loss like it does the heart.

## Why It's Good For The Game
Abductor surgery can't remove subtype hearts currently. This is likely unintended behaviour introduced by species organ subtypes.

## Changelog
:cl:
fix: Abductor surgery will now remove heart subtypes.
tweak: Capitalized abductor surgery names for consistency with the surgery UI.
/:cl:

### CODE REVIEW

**Comment by MrMagolor** [comment]
You should maybe add the IPC microbattery bit to the changelog?

**Comment by PidgeyThePirate** [comment]
I wasn't clear enough. Abductor surgery didn't remove the cell before, I changed it so it did (because it looked like it was intended) and then found out the surgery didn't compensate for the loss of the cell and reverted it.

**Comment by variableundefined** [comment]
Uses fixes instead of addresses next time, github recognize that and auto close issue

**Comment by PidgeyThePirate** [comment]
That's useful to know, thanks.

**Pull request merged**
