### PR TITLE
Generic Action/Action Button System

### PR DESCRIPTION
**Pull request by tigercat2000**
Testing complete, I couldn't break it. 
tgstation/-tg-station#8728
This commit ports the GAABS from -tg-station13. The GAABS allows for
generic, movable, hud elements for spells, powers, and items.

## Differences from -tg-
 - We do not have the xeno abilities linked to icons
  - We don't have the same ability system as -tg-, our current verb system is incompatible.
 - No mime spells
  - Eventually I'll port them, but beyond this PR.

Todo list:
 - [x] Try to break it. - 35 buttons it handled just fine, see screenshots section. I was running out of things to actually test it with.

### Screenshots!
example
You can move the buttons too, by drag-dropping them.
movable!
And of course, when your horribly mauled UI gets on your nerves, just use the minimize button.
Minimize
(and yes I did test for merge conflicts, this will automerge just fine with the light overhaul)

### CODE REVIEW

**Comment by tigercat2000** [comment]
DNM can be taken off, testing revealed no major issues.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Thank goodness--no more defining action buttons by their name and icon state.

Also, for this PR, I strongly recommend lowering the view range back to what it's *meant* to be. It was upped purely to compensate for the increased amount of actions buttons---but it broke everything else (vision ranges, cinematics, some overlays, spriting sizes, etc). Given this system avoids that issue entirely and the fact that SS13 is balanced around the previous view range, I'd strongly strongly recommend going ahead and adjusting it back to this, especially since you're already fiddling with HUD elements and positions in this PR.

**Comment by tigercat2000** [comment]
@Fox-McCloud I strongly disagree. We have been running at 17x17 for months, and I foresee a lot of people yelling about it if it is changed. Not even mentioning that I personally like the extended range.

**Comment by Fox-McCloud** [comment]
They may yell, but the game is literally not designed for it in the slightest--as evidence by every single cinematic being broken, throw ranges not matching up, projectile ranges not matching up, overlays being messed up, vision being broken, and projectiles not matching up to screen range, either. It's hugely inconsistent with literally every code-base (and from what I can tell BYOND games, in general) and causes a lot problems.

Not to mention it'll have a decent performance impact (good one) for users as well as they won't have to render nearly as much, at once--and I dare say less lag (even if input delay based as opposed to server side) is a good thing.

We ran 17x17 for months, but we also ran 15x15 for months--it's one thing half outdoes the other, but literally SS13 is not meant, designed, nor balanced around 17x17.

**Comment by tigercat2000** [comment]
@Fox-McCloud Either way, it's beyond the scope of this PR, and I know ZomgPonies opposes changing it.

**Comment by Fox-McCloud** [comment]
It's pretty tied into this PR considering how much HUD elements have been changed.

View range being higher rather than lower will *always* be preferable to the players because it inevitably means more of an advantage for them--this is why game designers have to put hard limits on it that work for the game itself--as opposed to what individual players may particularly desire--because more vision range is *always* preferable to less (and why if you give players the opportunity to have a longer or wider vision range, they will always make it the widest and longest possible)---not shockingly, a good portion of hacks for game deliberately alter this range to give them a specific advantage---again 'cause increased vision is always preferable (to a player) than to less--but game health, balance, and design are more optimized to it being fixed (or very limited)---and in SS13's case, it's literally designed around 15x15.

**Comment by tigercat2000** [comment]
@Fox-McCloud what are you even going on about? I'm not going to change the view range when I know at least one other maintainer doesn't agree with your opinion of it, and we have been running 17x17 for months with no complaints from anyone but you as far as I have seen. We are a mod on a mod on a mod, we don't have to use 15x15 just because Bay and -tg- do.

**Comment by Spacemanspark** [comment]
I personally like the view range the way it is currently.

**Comment by ZomgPonies** [comment]
@Fox-McCloud - We just added the possibility of having a LOT more HUD icons. The extended viewrange was put in SPECIFICALLY to give us more border real estate to support such behavior. 

As for you arguments against, I don't understand them. They don't make any sense. The vision range is still fixed, it is simply 17x17 for all players. Nobody gets an advantage, all this does is give more space for hud icons.

**Comment by fj45** [comment]
17x17 is great, please keep it.

**Pull request merged**
