### PR TITLE
Pens no longer use comic sans

### LINKED ISSUE #6805: Comic Sans Writing
**Problem Description**:
Writing with a pen on paper uses the comic sans font.

**What did you expect to happen**: 
Writing in pen to use the regular font.

**What happened instead**:
Writing in pen used the comic sans font.

**Why is this bad/What are the consequences:**
Pretty sure only crayons are to produce comic sans.

**Steps to reproduce the problem**:
1. Grab Pen and Paper
2. Write Woody's Got Wood on paper
3. Read Woody's Got Wood in comic sans out loud.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### PR DESCRIPTION
**Pull request by Crazylemon64**
Fixes #6805

:cl:Crazylemon
fix: All pens are now certified crayon-wax free!
/:cl:

### CODE REVIEW

**Comment by tristan1333** [comment]
comic sans is irrefutably the greatest font. This is a shame upon the server, an absolute disgrace. The playerbase won't stand for this change.

**Comment by Lady-Luck** [comment]
Isn't it used because it's supposed to be handwriting and Comic Sans is a handwriting font?

**Comment by Lady-Luck** [comment]
Oh, nevermind, it's a bug apparently.

**Comment by Crazylemon64** [comment]
@Lady-Luck Ever since the new computers - there was a change to the way to pencode translation was done, that changed the way the function called so that the slot for the crayon font got shunted into the slot for the pen font.

**Pull request merged**
