### PR TITLE
Adds support for dank 360 no scopes

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Finally hoping to cash in a bit on my GBP with some fun sniper shenanigans.

In general, adds a hitmarker sound for sniper rifles. While shooting blindly down a hallway remains a quality tactic, you now get some feedback if your bullet hit anyone along the way. For penetrating shots, you learn about *every* hit.

Now, the fun stuff. By performing a spin or a flip while shooting a sniper rifle, you leave a little calling card with your victim telling them that they've been styled on. This is purely flavor.
If you aren't scoped in, though, it gets a little more interesting. Mom gets the camera and takes a picture of your victim right when your amazing shot hits them. Your victim, on the other hand, is left with an air horn denoting how owned they were. While this is still mostly for flavor, it might provide a bit of interesting intel based on where your shot ends up (especially for penetrators).

Also, on the backend, I added some missing SEND_SIGNAL calls throughout the gun system.

## Why It's Good For The Game
I feel like adding the hitmarker effect to the sniper rifles may be a bit of a buff, but at the same time should make for some more dynamic gameplay. If you get sniped down a hallway, you should probably move, because there's a non-zero chance the sniper will be able to fish for another lucky shot.

The camera of the sniper is a bit goofy, I'll admit, but who's to say that the Syndicate haven't been experimenting with some miniaturized cameras anyway? The camera range is only 3x3, so there shouldn't be too much mission-critical information given. I think that, when combined with a penetrator shot down the middle of the ship, it could yield an interesting way to gain intelligence, though the airhorn is a dead giveaway and will likely blow any cover you hoped on maintaining.

I feel like the charming flavor of pro sniper gaming fits in fairly well with the content of SS13. A good stale meme here and there + some more entertaining flavor for syndies will just make things more fun, I believe. Maybe you won't feel as bad when you get your head blown off by an antimatter shot because the shooter did a sick nasty trickshot. 

## Images of changes
https://user-images.githubusercontent.com/89928798/149850126-9c7496d8-7f59-4e30-9ebd-d08aff42d3da.mp4

the image

## Changelog
:cl:
add: Sniper rifles now create a hitmarker sound if they hit a target.
add: Performing a flip or spin before shooting a sniper tells the victim they were styled on.
add: Firing a sniper while spinning and not scoped in fires a 360 no scope that takes a picture of your sick trickshot.
/:cl:

### CODE REVIEW

**Comment by LiberatedWaveMan** [comment]
I can't speak for everyone, but I feel like this kind of thing is _exactly_ why there's a limit to how far audio travels. You're not going to know your sniper hit someone because of a funny sound, you either see it happen or you don't; and an airhorn? C'mon, that's a meme.

**Comment by lewcc** [comment]
I was under the impression that you could still implement features if you had enough gbp to balance it out

otherwise yeah. snipers are rare enough that I felt it'd make for some good jokey flavor when they do appear. If it's too far I can can it

**Comment by LiberatedWaveMan** [comment]
> I was under the impression that you could still implement features if you had enough gbp to balance it out
> 
> otherwise yeah. snipers are rare enough that I felt it'd make for some good jokey flavor when they do appear. If it's too far I can can it

I didn't realize this was a goodboy points exchange, that's on me; still, the hitmarker sound feels like a bit much

**Comment by TORE01** [comment]
Hey. Just wanted to say that its a great idea, especially for the regular traitor one with no scope since you cant always see where you shoot and if you hit. But the airhorn sound just makes this PR into a meme PR.

**Comment by hal9000PR** [comment]
>I was under the impression that you could still implement features if you had enough gbp to balance it out

From the feature freeze pr
```As for the features you do submit or refactors you engage in, contact maintainers first about the refactor and contact maintainers or headmins first about the feature. Without explicit approval (for refactor and feature PRs), your PR can and will be closed. When seeking feature PR approval, specifically, you will have to demonstrate which fixes are to count towards your feature submission.```

**Comment by dearmochi** [comment]
As per the ongoing [feature freeze](https://github.com/ParadiseSS13/Paradise/pull/17040):

> As for the features you do submit or refactors you engage in, contact maintainers first about the refactor and contact maintainers or headmins first about the feature. Without explicit approval (for refactor and feature PRs), your PR can and will be closed. When seeking feature PR approval, specifically, you will have to demonstrate which fixes are to count towards your feature submission.

This rule was not followed to my knowledge. Additionally, the LRP nature of this feature does not sit well with me, even when taking the meme aspect of SS13 into consideration. **This is really something you should have gotten an extensive approval on before getting around to making it.**

In accordance with the feature freeze conditions, I will be closing this pull request. If you wish to know how to proceed from here, do consult me in private.

**Pull request closed without merging**
