### PR TITLE
New Turbine Sprites

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
Replaces the ancient turbine sprites with new ones [from BeeStation](https://github.com/BeeStation/BeeStation-Hornet/pull/4130). Also, I fixed the overlays and one turbine dir sprite that were screwed up on the Bee PR. 

## Why It's Good For The Game
Do you really have to ask?

## Images of changes
image
image

## Testing
Loaded in, set up and started up the turbine, confirmed that the sprites and overlays worked as intended.

## Changelog
:cl: PacifistDalek, PestoVerde322
imageadd: New Turbine Sprites!
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
i have been informed that tg’s turbine has spinning fan blades so Dammit im gonna have to steal tg’s spinning fan blades and weld them onto this sprite before it can be merged.

**Comment by Christasmurf** [comment]
One the bottom right sprite, the control panel (red cross and weird yellow lights(?)) needs to be flipped to be consistent with the other three directions, otherwise looks good

**Comment by PacifistDalek** [comment]
> One the bottom right sprite, the control panel (red cross and weird yellow lights(?)) needs to be flipped to be consistent with the other three directions, otherwise looks good

good eye! that’s only the case in that pic that i stole from the bee PR, i already swapped that around in the PR :)

**Comment by PestoVerde322** [comment]
Oh uh, I was working on some Less noisy icons for this:

VTEC3

The new version, compared to the old one, is ~~Really desoulified~~ more streamlined, with less colors and a slightly better perspective than the old one.

**Comment by PacifistDalek** [comment]
I took PestoVerde322's updated sprites and updated the overlays for them. To be honest, I just like the design of their sprites more than TG's, and trying to mash their 3 tile sprites into 2 tiles didn't really come out that well. Sorry, spinning turbine, jet engine turbine is staying for now!

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
