### PR TITLE
Pod Pilot Jumpsuit.

### PR DESCRIPTION
**Pull request by TheBeoni**
Added Pod Pilot Jumpsuit which is equipped by default. Fixed the floating dots around brig physician jumpsuit.
c431utl

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Don't think your branch is up to date...

**Comment by TheBeoni** [comment]
...i noticed right after i posted it

**Comment by TheBeoni** [comment]
also i checked it and this does not change anything...

**Comment by TheBeoni** [comment]
Want me to re-upload from updated branch?

**Comment by Fox-McCloud** [comment]
preferably, yes.

**Pull request closed without merging**
