### PR TITLE
Changes the fox pAI chassis resting animation

### PR DESCRIPTION
**Pull request by JimKil3**
## What Does This PR Do

This PR slightly changes the fox pAI chassis' resting animation.
## Why It's Good For The Game

This is good for the game because the existing rest animation has a lot of movement, which doesn't make sense for a resting animation, and the way the lights on the sprite cycled was not consistent with the other fox chassis sprites. Also, two of the directions have mirrored sprites, to allow the pAI to choose a direction to face.
## Images of changes

Old Animation:
old_animation
New Animation:
new_animation

## Changelog
:cl:
tweak: edited the fox pAI sprite to be nicer to look at
/:cl:

### CODE REVIEW

**Comment by Kiyahitayika** [comment]
Maybe change the tick length between some of the animations? Although, that would mess up the light cycling, which I agree does look better on your work!

**Comment by JimKil3** [comment]
> Maybe change the tick length between some of the animations? Although, that would mess up the light cycling, which I agree does look better on your work!

Thanks for the feedback! The tick length is copied from the regular, standing sprites, so I'd rather not change it without changing those.

**Comment by JimKil3** [comment]
Edited the PR description to show that the sprite is mirrored to give directionality, like with Renault's sprite.

**Comment by Fox-McCloud** [comment]
Yeah, no.

This sprite was made Full Of Skittles, and I seriously doubt they'll appreciate it being changed.

Current sprite is fine.

**Comment by Spacemanspark** [comment]
While I'd say that anyone is free to try and edit whatever they'd like within the codebase... I agree with Fox that FoS' original sprite does look better. It has a bit of life to it that I kind of wish the other pAI sprites possessed, the only other one I can think of are the fairy and cat sprite (when it's resting). The one proposed in this PR is rather frozen in comparison.

**Comment by Kiyahitayika** [comment]
> It has a bit of life to it that I kind of wish the other pAI sprites possessed

I want to echo this. I do agree that the light cycle does a bit off in the original animation - although I never noticed it until your PR pointed it out.

I support people in opening PRs, especially their first ones. That said, I also want to echo what Fox said. The current sprite is wonderful and, as Spark says, it has life. Removing "content" from the game is always going to be controversial and this request seems very odd. Yet, you also added content by allowing the sprite to face another direction. I wonder - would you be able to mirror the animated sprite to face the other direction as well?

**Comment by JimKil3** [comment]
Okay! After reading all of this feedback (thanks for the feedback, by the way) I'll redo this - I'll keep most of the old animation, while adding the directionality and fixing the light cycle (if possible).

**Comment by Pixelzilla** [comment]
The light cycle isn't "off" it is intentionally different because during walking/standing mode it flickers to red because it is "consuming power" while in "rest" mode it only flickers to a darker green because it is "charging".

**Comment by JimKil3** [comment]
> Intentionally different because..

I did not get that at all, it just looked like an oversight or an inconsistiency, although now that you point it out it makes a bit of sense. Still, it's not my favorite.

**Comment by Necaladun** [comment]
I personally really like the head turn

**Comment by AffectedArc07** [comment]
2 maints and a head objecting. No one in favour. Closing.

**Pull request closed without merging**
