### PR TITLE
Fixes being able to sentience potion pirates & other sentient simple_animals

### PR DESCRIPTION
**Pull request by Kyep**
🆑Kyep
bugfix: it is no longer possible to use a sentience potion to convert space pirates in the beach away mission to your side. Nor is this possible with other sentient NPCs, such as syndies or russians.
/🆑

### CODE REVIEW

**Comment by Vivalas** [comment]
On one hand it's really neat and clever.. on the other hand it's a meme. This being opened right after the round though makes me wanna scream about fun police though...

**Comment by Kyep** [comment]
Really, any simple_mob that is meant to be intelligent should be immune to the sentience potion. I just started with these as I saw people actively using sentience potions to convert them into slaves of the crew.... which is bad as they have a triple-laser attack and are meant to be pirates.

**Comment by imsxz** [comment]
You'll have to fix this for the Russians and syndicate NPCs too

**Comment by Kyep** [comment]
@imsxz Meh, why not. Added them in as well. Angels, too, as they're sentient.

**Comment by Vivalas** [comment]
Huh, if this worked for angels, now that's a big issue.

**Comment by Fox-McCloud** [comment]
Uh, angels aren't sentient. They're simple mobs like any other.

Just because they exhibit certain behaviors doesn't inherently make them sentient.

Any human mobs? Yeah, that makes sense, because they're a stand-in, but I don't think angels should be included here.

**Comment by The-Driker** [comment]
@Fox-McCloud 
If the angels are in fact still based off the weeping angels from Doctor Who, they are very much sentient beings. 
http://tardis.wikia.com/wiki/Weeping_Angel
I'd say it's safe to include them.

**Comment by Spacemanspark** [comment]
Angels are already ridiculous, considering it's literally impossible to kill.
They don't need to be player controlled in my opinion.

**Comment by Vivalas** [comment]
Not really the scope of this PR. As angels are player controlled and are indeed sentient beings, they should not be able to be controlled by a sentience potion.

**Comment by Kyep** [comment]
@Fox-McCloud Weeping angels clearly are sentient. Look at their behavior on Dr. Who. There are scenes where the main characters have conversations with them. Long conversations. They're not just sentient, they're actually quite smart. They deceive, they manipulate, they prey on the fears of their targets. They are capable of understanding what scares a person, and using that against them. If the statues in SS13 are based on the Weeping Angels from Dr. Who, they are obviously sentient.

That said... I don't actually care if we get the angels right in this PR. The purpose of this PR is simply to fix the syndie mobs in the beach mission. Anything else being improved is a bonus. So, I've removed the changes to angels from the PR. For the record, though: weeping angels, and the SS13 mobs they're based on, are obviously sentient.
To quote https://en.wikipedia.org/wiki/Weeping_Angel
_On those occasions when they have chosen to communicate with their prey or foes (using the gruesome proxy method mentioned above) they have demonstrated a cold and impersonal intelligence, but exhibit no empathy and no emotions beyond hunger, determination, and occasional predatory sadism._

**Pull request merged**
