### PR TITLE
Adds to Maintenance-Areas Near Incinerator

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
rscadd: There is now a maintenance tunnel around each side of the mechanics workshop
rscadd: There is now a disposals tube that runs between disposals maint and incinerator maint
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
I'm having a very hard time picturing this.

**Comment by Fox-McCloud** [comment]
Pics or it didn't happen =p

**Comment by Norgad** [comment]
Are the screenshots broken?

**Comment by IK3I** [comment]
I don't see how this is even possible without cutting the mechanic's shop off. What sorcery have you done?

**Comment by Norgad** [comment]
Guys how do I pictures

**Comment by Fox-McCloud** [comment]
![ imagename goes here ] ( url goes here )


Only no spaces

**Comment by FlattestGuitar** [comment]
Add a "!" before the square brackets. Also that needs to be a direct link to the pic's url

**Comment by Norgad** [comment]
I gave up and added a link

**Comment by IK3I** [comment]
interesting, not sure if having the mechanic's podbay so readily accessible is a good idea though

**Comment by Norgad** [comment]
Well, It still has podlocks and R-Walls

**Comment by FlattestGuitar** [comment]
Literally the only practical use of the incinerator I ever saw was using it to house an sm engine and toss it out through the shutters, were it to delaminate. This kinda disables that option. 

Maybe move the incinerator to the left and make the maint a bit bigger?

**Comment by Fox-McCloud** [comment]
kinda weird..kinda like it, kinda don't. Always up for more maintenance stuffs though.

**Comment by Keilden** [comment]
You can't walk on open pod airlocks, only fly. Also more maint is :+1:   As long as the strange objects can spawn there.

**Comment by Norgad** [comment]
Be glad I haven't added my other idea...
ya
...yet

**Comment by Fox-McCloud** [comment]
@Norgad 

Oh gosh, why

**Comment by Norgad** [comment]
Because I have a dream of a station where I can run an entire lap while barely ever leaving maint. Also because environmental danger is fun. It's part of what makes cogmap2 so great.

**Comment by IK3I** [comment]
Should've been chutes to minimize loading times.

**Comment by Norgad** [comment]
It will be. That is just my mock-up design of it

**Comment by KasparoVy** [comment]
I was going to make a comment about how this just makes it easier to hijack parked pods from the mechanic's workshop, but then I realized that you extended the garage section behind the airlock and passed maint through there instead haha

Nice.

**Comment by pinatacolada** [comment]
:-1: cutting the podbay in half is weird by the very least

**Comment by Norgad** [comment]
> cutting the podbay in half
The original podbay is the same length as it was before, it just has an extension on the end. There shouldn't be any risk of it being blocked/ambushed as pod doors can be seen through

**Comment by pinatacolada** [comment]
that's not my problem, I just don't like it on an aesthetic standpoint, it feels wrong, but that's just me.

**Comment by Dumbdumn5** [comment]
MORE MAINT, MAINT STATION, MAKE IT SO ALL OF THE STATION IS A COMPLEX NETWORK OF TUNNELS WITH SPACE WINDOWS, DECREPIT AREAS, AND STATION COMPONENTS STRAPPED ON TO EACH END, AND LIT BY FLOOD LIGHTS, AHAHAHAHHA! (:+1:)

**Comment by Taaketa** [comment]
Only suggestion I'd make is to lose the mining dock windows that are exposed to maint. Makes it far too easy to break into the dock.

**Comment by Norgad** [comment]
Okay Ill work on the edits and then fix the merge conflict

**Comment by Norgad** [comment]
> Could there thematically be a bolting function when the podbay doors are open?

I'm adding some doors, though bolting them would be redundant as podlocks only let pods pass through anyway

**Comment by Norgad** [comment]
What am I doing wrong to fix the merge conflict?

**Comment by IK3I** [comment]
You need to use the map merge tools in the tools folder of the repo.
Also, the simplest way to fix a merge conflict is to backup your changes and merge up to the current commit on the master. Next, for each conflicting file, pull down the version from the master and copy it over to your local branch. Copy Pasta your changes over to the conflicting file correcting any conflicts as you go. Once you finish that, you're ready to commit the new changes which shouldn't conflict anymore because you've already brought your branch up to the current state of the master. The alternative is to use the amended history route by backing up changes, hard resetting your branch up to current, then doing as described above for any conflicting files.

**Comment by Norgad** [comment]
Thanks, fixed now!

**Comment by IK3I** [comment]
Also, it's good practice to link to the PR that caused  the conflict in your commit that resolves it so the history is more clear. It's not really required, but better documentation means easier fixing if something goes wrong.

**Comment by Norgad** [comment]
Will do for future PRs

**Comment by Norgad** [comment]
Can someone remove the merge conflict tag?

**Comment by Norgad** [comment]
Whoops wrong button

**Comment by IK3I** [comment]
Maintaners check on the PRs periodically, the tag will be removed the next time one looks at it and sees the conflict is resolved.

**Comment by lolzyking** [comment]
I like it

**Comment by monster860** [comment]
I don't really like the maintenance tunnel running through the mechanic's podbay.

What I think would be awesome is a system for overpasses.

**Comment by monster860** [comment]
@IK3I Actually, the easiest way to resolve a merge conflict is to use Bay's mapmerge driver.

**Comment by IK3I** [comment]
@monster860 I was referring to merge conflicts in general. That being said, I was unaware that that tool resolves conflicts in the process, so that will be useful in the future.

**Comment by monster860** [comment]
@IK3I The mapmerge tool Bay uses is not the one that Paradise uses. You'll have to copy it somewhere and change bat/sh file.

**Comment by taukausanake** [comment]
I don't think I like it. Cutting into Mechanic's bay, and you already have the maint halls so close to each other on the other side of Mechanic's. You really don't need this

**Comment by Norgad** [comment]
Hmm. Once I get home I'm going to edit this to make it more ~~fun~~ ~~dangerous~~ useful.

**Comment by Norgad** [comment]
I'll edit the changelog and add new screenshots

**Comment by Norgad** [comment]
The comment has been updated. 
@Fox-McCloud I did the thing

**Comment by Fox-McCloud** [comment]
The most recent change, with the chutes looks bad, no offense---and it has no logical purpose to exist or "to be", nor does it really fit with maintenance, to be honest. It's just a "let's put disposals here so I can get from point A to point B quickly".

I'm all for expanding maintenance, but just shoving maintenance into areas purely for the sake of "point A to point B" and only that isn't generally a good idea, nor does it look good.

**Comment by Norgad** [comment]
@Fox-McCloud You could argue that many features of maintenance have no real reason to be on the station. The abandoned surgery, random blast door area, the extension to sci-maint, heck even the old bar. They aren't there for everyday use, they are there to add flavour to the map and add points of interest to the station. None of them are as directly useful as the main rooms of the station but what they do do is supply options and alternatives for the crew.
The disposals transport is no different. While yes it supplies a shortcut across the station, it does so at the cost of health. It also fixes the issue of engineering and cargo maintenance being cut off from other maintenance areas.
I'll try to see how I can improve the look of the disposals pipe over the next day or so, but if I cannot find a solution that satisfies other users I'd be fine to just revert the changes and remove the pipe altogether.

**Comment by monster860** [comment]
I still think you should NOT have it cut through the mechanic podbay.

**Comment by Norgad** [comment]
@monster860 I'm away from my computer right now, but removing the pod bay bypass is mostly done, just not committed yet.

**Comment by TheDZD** [comment]
Really don't like the look of that disposal pipe in space.

**Comment by taukausanake** [comment]
Yeah, both these edits don't look good or add anything useful to the station. More bothersome I think

**Comment by Elysian-Prince** [comment]
I think it's a fun idea--the whole point of maintenance being used for anything is sketchiness, and the pipe brings a sort of 'rigged' sense to it. As to people complaining about the piping in space--we've already got a LOT of ugly stuff around the station otherwise that isn't exactly necessary. Random walls outwards, random metal lattices and catwalks.

If visual context is the issue here, the only ones likely seeing the pipes besides those using it would be mechanic/security pod pilot, and maybe an engineer if something goes boom. If the issue is with it goign through the mechanic's podbay, then i'd say just go around it then. Fix the mapping so that there isn't a doorpath through the bay and then you're golden.

**Comment by Norgad** [comment]
The description has been updated once again with screenshots of the changes

**Comment by Norgad** [comment]
Oh shit I noticed a broken wire

**Comment by Norgad** [comment]
Okay. **Now** it should be fixed.

**Comment by Fox-McCloud** [comment]
still a :-1: for me because of the space disposal bypass; it's fairly unsightly and...well, frankly, not needed.

**Comment by Norgad** [comment]
@Fox-McCloud What would improve the pipe visually for you? As Elysian said, it already fits the 'sketchy' fell of the rest of maintenance. Perhaps adding some more warning tape and deteriorated/un-maintained features, or maybe it needs to be of a more staggered shape with three corners instead of one? I don't know what about it makes it look so bad to you? (though I will admit that the lack of lighting in the screenshots does make it look a fair bit worse than ingame)

**Comment by Elysian-Prince** [comment]
As a suggestion, perhaps try running the disposals pipes along the side of the station so they don't jut outwards into a 90 degree angle, then run up? It may take longer, and may cause some more damage, but as far as I can see, it would clean up the issue a little more.

**Comment by pinatacolada** [comment]
Why not just make a normal glass bridge thing where the pipes are? Box station kinda has it boxxyyaya

**Comment by Norgad** [comment]
@Elysian-Prince I'll try that once I get back to my computer.

**Comment by Norgad** [comment]
@pinatacolada I considered it, but it just makes the mining and supply shuttles feel 'boxed in'.

**Comment by taukausanake** [comment]
You know, those maint halls aren't so bad, but the pipes are still an eyesore. I'd still remove the pipes and make those rooms like that one maint room below viro where everyone does their ERP. Little sitting areas, those would be nice

**Comment by Keilden** [comment]
Remember that the shuttles fly in space, they can go up and down.

**Comment by Norgad** [comment]
@Keilden  Yes, though because everything in the game only moves horizontally or vertically, it still 'feels' like the shuttle is trapped, even if it wouldn't be in the real world.

**Comment by Norgad** [comment]
Updated the pipe agian

**Comment by taukausanake** [comment]
So the new image has the pipes looking a little broken? I guess that's better but still can't say I like them much. On the plus side I can see this as being a possible new way to space things

**Comment by PJB3005** [comment]
I don't think the pipe is a good idea.

Disposals pipes aren't for human transport. NT wouldn't make pipes like this.

<sup>i don't play here but it's my 2 cents</sup>

**Comment by Norgad** [comment]
@PJB3005 You are correct. NT would not make disposals pipes for human transport. But that wouldn't stop workers from using them for that anyway.

**Comment by tigercat2000** [comment]
@pinatacolada that's metastation not boxstation you silly

**Comment by pinatacolada** [comment]
shhh no one noticed until now

**Comment by Spacemanspark** [comment]
I did but didn't want to point it out.

**Comment by Norgad** [comment]
>tfw a tiny change causes a merge conflict

**Comment by Norgad** [comment]
Oh no. I've messed this branch up so bad.  Should I just make a new branch and PR?

**Comment by tigercat2000** [comment]
@Norgad please don't
you may have to make a new branch and fix it there
but instead of opening a new PR, just reset the PR branch to the new branch and force-push it

in commands:
```
(assuming you are on the new branch, let's call it "new_branch_name")
git checkout cargo-engi-maint
git reset --hard new_branch_name
git push origin cargo-engi-maint -f
```

**Comment by Norgad** [comment]
@tigercat2000 Did it work?

**Comment by Norgad** [comment]
@tigercat2000 Did it work?

**Comment by tigercat2000** [comment]
@Norgad well you overwrote all the commits it seems which is what should have happened
still a merge conflict though

**Comment by Norgad** [comment]
@tigercat2000 How do I fix it now then?

**Comment by tigercat2000** [comment]
@Norgad try to update to upstream, fix any merge conflicts that it shows

**Comment by Norgad** [comment]
@TheDZD I fixed the merge conflict. Github was being a lad and not syncing anything.

**Comment by Norgad** [comment]
@tigercat2000 Thanks for the help with merge conflicts

**Comment by Norgad** [comment]
Goddammit I pushed the wrong button agian

**Comment by Fox-McCloud** [comment]
The whole space disposal ride is still a :-1: from me.

**Comment by QuinnAggeler** [comment]
Being able to go between those two areas without leaving maint is a rather large balance change, when you think about it.

**Comment by Norgad** [comment]
@QuinnAggeler Yes, though it does have its drawback of a bit of brute per ride which helps balance it out.

**Comment by taukausanake** [comment]
I don't think we get brute damage when going through disposals? I know that used to be a thing and was a HILARIOUS way to murder someone given a long enough trip. Kind of miss that actually

**Comment by Norgad** [comment]
@taukausanake For some reason the atmos information of the tile the pipe is on is applied to things inside the pipe too.

**Comment by TheDZD** [comment]
Yeah, still don't like the idea of the disposal pipe.

**Comment by Fox-McCloud** [comment]
Closing this--it's been 2 weeks with no updates.

**Pull request closed without merging**
