### PR TITLE
Electric Chair update

### PR DESCRIPTION
**Pull request by Artorp**
1) Buffed damage, victim will die much quicker
2) Removed stun
3) Added support for spawned/map-placed e-chairs (would runtime when disassembled)
4) Fixed activation animation, it will now show the snazzy zap animation as God intended
5) Changed toggle verb into activation verb
6) Fixed updating of icon when activated

Electric chair used to do 170 burn damage, which usually meant more than a minute of waiting for the victim to die of crit-induced suffocation. Requiring a "double-tap" so to speak. Changed it to 180-200 burn damage, weighted towards 200. This is an electric chair, not a torture device.

Removed the 10 minute duration stun, no need for it and it posed problems should the victim survive.

~~I'm also contemplating adding it directly to the map~~ instead of requiring security to assemble it before use. The electropack could be moved to the interrogation observation room, the armory, or somewhere else. Thoughts? 

Added to map, here's what the new death chamber looks like:

space station 13 2015-04-14 233242_crop

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
How about making the whole station's lights overload(and by that I mean turn on and off, not explode) as it uses most of the station's power at the moment. Also gets a bit of fear into the traitor's bones. HEIL NT.

**Comment by Fox-McCloud** [comment]
Add it directly to the map if you don't mind---that was always my intentions, but as there wasn't support for it, I just added the components instead. Chair is better than lethal injection as it makes everything speedier for everyone involved.

Just make sure the chair frequency is some highly unlikely used frequency and it has a matching remote signaler to go with it.

**Comment by Artorp** [comment]
Sure, will do.

**Comment by Fox-McCloud** [comment]
awesome! Thanks Artorp! :+1:

**Pull request merged**
