### PR TITLE
Fixes runtime with robotic cryopods (previously: mechbay cryopod fix)

### LINKED ISSUE #8185: Borg Crypod Runtime
[20:38:48] Runtime in cryopod.dm,750: Cannot execute null.remove subsystems and actions().
   proc name: despawn occupant (/obj/machinery/cryopod/robot/despawn_occupant)

### PR DESCRIPTION
**Pull request by Kyep**
~~Adds a robotic storage oversight console to mechbay, fixing the "crypod could not find a control computer" error when it is used. You can also click the console to find out which robot cryoed in the pod.~~ Change removed. That change was instead merged in https://github.com/ParadiseSS13/Paradise/pull/8480 - in order to reduce the number of PRs which change Cyberiad.dmm

Fixes a runtime in cyropod.dm which can be caused by a robot with no modules cryoing. Specifically, when the cryopod tries to call R.module.remove_subsystems_and_actions(R) on a R(obot) with no R.module. Fixes #8185

### CODE REVIEW

**Comment by SamHPurp** [comment]
Is it this issue it fixes? #8185

**Comment by Kyep** [comment]
Yes.

**Comment by Kyep** [comment]
Closing/reopening to force Travis to recheck.

**Comment by tigercat2000** [comment]
LGTM

**Comment by Kyep** [comment]
For the record: 
https://github.com/ParadiseSS13/Paradise/pull/8502 already included the mech cryopod fix. 
Deleting it from this to avoid unnecessary cyberiad.dmm map edits.
Only the runtime fix remains.

**Pull request merged**
