### PR TITLE
Tesla Update/Rebalance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates and rebalances the Tesla to TG's current standard.

This fairly dramatically reduces the power output of the Tesla, putting it on par with the singulo (still possible to hit higher power output levels, but it'll take a lot longer). It will also start to lose energy balls if you don't keep on pumping power into it. Another important feature is that the the singularity beacon (now renamed power beacon) will attract the Tesla AND the Sinuglo.

It's generally more flashy too, with each of the smaller energy balls capable of shooting out zaps:

img

Code Related
- Tesla Zap is better on performance than it previously was
- Fixes some turf/area oddities with `Beam`
- Tesla shocked now uses a timer as opposed to `Spawn`

Semi-Related
- Updated the explosion for fuel tanks; it's stronger than before and capable of bouncing Tesla shocks even further

:cl: Fox McCloud
tweak: Updates the Tesla; it will now have to be "fed" or it can run out of energy; the rate at which it gains additional energy balls and power has been greatly lowered.
tweak: energy ball will now be drawn towards the singularity beacon
tweak: fuel tank explosions a bit stronger and will arc tesla blasts further
/:cl:

### CODE REVIEW

**Comment by Keilden** [comment]
ooooo pretty

**Comment by FlattestGuitar** [comment]
Could we get a nice breakdown of how the tesla's power generation looks over the course of a shift?

The idea I tossed out some time ago was to make the tesla generate way less power than a singularity on startup, making the two actually proper alternatives, rather than making the tesla miles better.

**Comment by IK3I** [comment]
Sounds like Lady Tesla didn't like the power reduction, so she got more zappy. Also on the very plus side, a loose tesla with a single energy ball probably won't need admin intervention anymore.

**Comment by Aurorablade** [comment]
I disagree with this...

...That screenshot show you not trapped behind an emittier and unable to get out...This is WHOLLLY inaccurate and must be fixed.

**Comment by Fox-McCloud** [comment]
I didn't feel like running a test server for 2 hours, but I ran it for ~20 minutes, and the power only increased by 100,000-200,000ish during that time.

I suspect it would hit somewhere around 3-5,000,000 watts by the end of the shift, but that's a basic estimate.

It's certainly not going to be very good for powerglove rampages at 5 minutes in, anymore.

**Comment by IK3I** [comment]
I don't know who originally coded the tesla, but the code for it is certainly heavy on the memes. I'm glad to see your preserved that aspect.

**Comment by Fox-McCloud** [comment]
>I don't know who originally coded the tesla, but the code for it is certainly heavy on the memes. I'm glad to see your preserved that aspect.

That would be @Iamgoofball

**Comment by Bigtimetripod** [comment]
Now i have a reason to yell at AI if it locks me up for messing with wires and increasing PAs power output to 3... MOAR POWAR IZ NEIDED!

**Comment by Regen1** [comment]
Holy fuck no :-1: :100: filthy fucking nerfs!

on a serious note, yes thank you :+1: forever

**Comment by Necaladun** [comment]
Yayyy! A good start, I'll monitor it to see how much power it gives off etc

**Pull request merged**
