### PR TITLE
Fixes Vox Robes + Prefs Sec=High Beret Icon Gen. + Sigholt's Beret

### LINKED ISSUE #3364: Fluff item sprite MIA
My beret (Lieutenant Starsong's beret) is missing its' sprite and thus is not very much of an item. It is still deposited into my bag and is examinable until I put it on my head, at which point it can't be removed by myself.

### PR DESCRIPTION
**Pull request by KasparoVy**
Does what it says on the tin. Fixes #3364, fixes Vox robes (previously they showed up as greytide uniform), fixes an unreported bug where if sec prefs were set to high there was a slim chance it would show the wrong (or no) beret sprite on the head in the char setup screen, also fixes Sigholt's beret.

:cl:
bugfix: Fixes Vox robes not using the correct on-mob sprites.
bugfix: Fixes unreported bug where there was a slim chance during character preview icon generation that a character with Security Officer set to high would get rendered with either the wrong beret sprite or no beret sprite at all.
bugfix: Fixes an issue where Sigholt's fluff beret wasn't using the correct sprites.
/:cl:

*PR in Action*
voxuni sigholtberet

The row of 3 beret icons shows, from left to right, the icon in the head slot, in hand, and on the ground.
Then below that on some Vox raider who'd probably knicked and had it hidden away all this time. Dastardly pirate birds.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
don't put "fixes <number" in the changelog; it doesn't mean much to regular players; just say what it fixes in the chagelog itself anddddd save that for in the regular PR.

**Comment by tigercat2000** [comment]
@Fox-McCloud put in my big list of "Definately 100% do" list for changelogs

#### Definately 100% changelog does
 - never use inline changelogs, only yml files
 - don't ever use your actual username for the author, or the secret service will eat you
 - use github terminology and reference things only by issue number

**Comment by KasparoVy** [comment]
> ?
> One letter off from my actual username, KasparoVv was taken and it makes little difference
> The only thing I had to change was the removal of the PR number from one of the bugfix entries

**Comment by Fox-McCloud** [comment]
@KasparoVy 

Your changelog is fine now. Thanks for fixin' it.

Someone abusing the Git to make in-game announcement is begging for a git ban.

**Pull request merged**
