### PR TITLE
Extends Incinerator Maintenance - 'No gross commits everywhere' Edition

### PR DESCRIPTION
**Pull request by Norgad**
:cl: Norgad
add: Maintenance around the incinerator has been expanded. 
add: Engineering maintenance finally has an APC.
add: The incinerator has been moved eastward, there is now a construction area in it's previous location.
/:cl:

It's just #4636 , but without random file "changes"
Please merge this before more conflicts happen.
map

### CODE REVIEW

**Comment by Aurorablade** [comment]
could we have a current screenshot of how it looks after changes...

**Comment by Norgad** [comment]
@Aurorablade It's the same as the one in the previous PR, but sure. Ill get it ready now.

**Comment by Aurorablade** [comment]
if you mean https://cloud.githubusercontent.com/assets/9260111/16034130/1dedc6aa-3264-11e6-9667-b0b94acb4b88.png

then i should have payed attenion to this sooner...

i do not like that maintance door that cuts through the pod bay on both sides..unless its properly restricted to CE/Mechnic..the same for the other maint door. Also was that other podlock door already there cuase i thought it was a blast style door.

**Comment by Norgad** [comment]
@Aurorablade Pod doors can only be passed over by pods. There is no extra risk of break in.

**Comment by Aurorablade** [comment]
only if theres a podlock barriet thing on it (those green things when the pod bay door opens), I don't feel it should be on an INTERIOR pod door if its kept as it is cuase it just makes hassle for the mechnic to go around thier leg to get to thier elbow when getting out of a pod and docking...

**Comment by Aurorablade** [comment]
this is all my opinion however.

**Comment by Norgad** [comment]
@Aurorablade I've already got the podlock. Its is very easy to toggle the doors from inside the pod, as only the closest door gets toggled by the verb

**Comment by Norgad** [comment]
@Fox-McCloud I cleaned the commits. It's ready again.

**Comment by Aurorablade** [comment]
well i mean the interior door leading to the bay, this one http://puu.sh/pFes6/b312db4ad2.jpg
the one does not need a green pod lock on it, and it needs a button on this side  (restricted access) so the pilot can open the door and walk back into the workshop instead of having to loop through the south maintance tunnel.

**Comment by Norgad** [comment]
@Aurorablade Because of the incredibly short distance, its still faster to just walk around than to push the button, walk through, and push the close button. Also, every other pod door on the station has a podlock and I'm not going to break that convention

**Comment by Norgad** [comment]
@Aurorablade Adding onto that, why would the mechanic park their pod outside the inner door anyway?

**Comment by Aurorablade** [comment]
cuase thats what its for..thats always been what its for..the interior area in more like a workshop/construction area. and it makes sense to put it there. and while a short walk its a walk through a dark spooky maintenance tunnel...I do not like the pod bay design choice here and its sometimes okay to break from convention if it helps the area design.

**Comment by Norgad** [comment]
@Aurorablade I said interior door, not the exterior one. The interior door on this change is the old podbay's only door. Also, to comment about your thoughts on the maint trip, I'm sick and tired of this server's playerbase being so 'anti danger'. The core fun part of SS13 that all of the other fun stems from is things going wrong and then the crew having to react to these changes.

**Comment by SigholtStarsong** [comment]
I'm not a big fan of this proposal for Maintenence - It looks too "clean" and "lived in". Especially with the built-in sleeping areas, bathroom, space-view lounge, ect.

The construction area where Incinerator currently is, however I do like.

**Comment by Aurorablade** [comment]
I DIDN't mean the exterior door i meant the interior door..i provided a screenshot..i am not anti danger, i am pro convience in this desing aspect...

**Comment by Norgad** [comment]
@Aurorablade That IS the interior poddoor. The one to the right of it is the garage BLAST door and the one to the left is the EXTERIOR poddoor. It make zero sense why you would park your between the exterior ind interior poddoors, since two can fit in the garage and another one can fit in the office. The ammount of room in the workshop that is only accessible to the mechanic is exactly the same as before the PR. The section to the right of the interior poddoor is actually an extention.

**Comment by IcyV** [comment]
Not really sure I'm a fan of the +3 entrances to the pod bay or the little bedrooms at the top. Other than it looking maybe a little too constructed as opposed to being a messy maint tunnel, it doesn't look too bad.

**Comment by Norgad** [comment]
Okay, Im going to make a slight edit because it doennt seem obvious enough that the the inter-poddoor area is a 'maintenance tunnel'

@IcyV I'll make it look a bit more degraded.

**Comment by Aurorablade** [comment]
I still do not like it being a 'maitaince area'

**Comment by FalseIncarnate** [comment]
Is there a reason you even need to make the maint cut-through of the podbay? Why can't you just hop across the hall like 5 tiles like normal?

Further, why does the "publicly accessible" side of the podbay need to be big enough for a pod? Why not just make it a single tile wide (just enough to walk through) and have pod-doors and pod-locks on both sides of that instead? You'll feel like you're cutting across the deck of an aircraft carrier mid-takeoff procedure as you dodge the inbound mechanic trying to dock, which is arguably more bad-ass feeling.

**Comment by Norgad** [comment]
@FalseIncarnate Think of the extension to the podbay as a driveway. The reason it is so wide is that because of the way pods are coded, 4 tiles is the minimum distance the pod doors can be apart and still be toggled by someone inside a pod correctly. Only the closest pod doors get toggled and the 'origin' of the door toggling signal is on the bottom left tile of the pod.

**Comment by taukausanake** [comment]
This makes me think the pod bays be four tiles high instead of three, but I forget if pods are 2x2 or 3x3 tiles. You wouldn't be able to get into them either way if you could fit more than one pod inside but I'd like that addition now that I think of it. Useless addition, but nice still

**Comment by Norgad** [comment]
@Fox-McCloud @TheDZD This is ready to merge.

**Comment by Norgad** [comment]
Oh jeez. Realised I forgot a small edit to the doors. I'll commit that change once I get home. After that, it's actually ready

**Comment by Norgad** [comment]
@TheDZD @Fox-McCloud Sorry about that. It's actually properly ready now.

**Pull request merged**
