### PR TITLE
Fixes several midround antag/creature assignments not asking ghosts first

### LINKED ISSUE #2306: Some things pull ghosts with no prompts
List of things I know of:
 - Xenomorphs
 - Borers
 - Revenants
 - Wizard Apprentices
 - Blubs

>observing, in the middle of dealing with so-
>LOLXENONOW
>fucking kill me

### PR DESCRIPTION
**Pull request by Tastyfish**
- Fixes #2306
- For:
 - Xenomorphs
 - Borers
 - Revenants
 - Wizard Apprentices (Contract & Multiverse Sword)
 - Blobs
 - Slaughter Demons
 - Morphs
 - Sentient Slimes
- This also fixes facehugger egg organs, because they were completely broken, possibly due to an oversight we forgot in #2903.

:cl:
tweak: Mid-round selection for various creatures and antagonists now consistently asks permission.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Thank goodness.

Can't :+1: this enough. I finally feel like I can turn on a few antag prefs now.

**Comment by veganzombeh** [comment]
It might be a good idea to add a check if they've enabled antagHUD in `pollCandidates

**Comment by Tastyfish** [comment]
Yeah, that was a strange oversight on that proc.

**Comment by taukausanake** [comment]
Facehugger egg organs? Can we make more Lamarr's now? I know we can't but I'd like to imagine the possibility at least

**Pull request merged**
