### PR TITLE
Removes some 'null' variables from cyberiad.dmm

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Removes a bunch of `x = null;`'s from the `cyberiad.dmm` file.

## Why It's Good For The Game

They're only there because of a Dream Maker "quirk", so removing them doesn't actually have any downsides.
And it makes the 'Edit Instance' thing look cleaner.

## Changelog
:cl:
tweak: Removed a few 'null' variables from the map file
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
this is going to merge conflict all mapping prs, won't it?

**Comment by SabreML** [comment]
> this is going to merge conflict all mapping prs, won't it?

In theory it shouldn't, unless they're editing the same stuff I did.
AFAIK mapmerge stops conflicts like that from happening.

**Comment by variableundefined** [comment]
I don't think they do, might be best to hold off on this PR. Other PR are more important.

**Comment by variableundefined** [comment]
Closing. Due to pending mapping changes I don't think this is worth the conflicts at the moment.

**Pull request closed without merging**
