### PR TITLE
Republish - make 513 compile

### PR DESCRIPTION
**Pull request by Cazdon**
## What Does This PR Do
permission
"Minimum changes so that 513 will compile with paracode"

## Why It's Good For The Game
I... don't know. This is a request from @Kyep since I have Couls permission to republish these, but to copy straight out of Coul's PR.

"lets people get their hands on the new filter stuff and is less work when 513 goes from beta to stable release"

## Changelog
:cl:
tweak: people using 513 can now compile the code
/:cl:

### CODE REVIEW

**Comment by Cazdon** [comment]
now this itself doesn't compile 😄 

yeah let me try to fix this without breaking it completely.

**Comment by Cazdon** [comment]
Or you know, I could try not coding at 1AM. I had the test server open so of course it couldn't compile.

Am good coder guys, promise.

**Comment by farie82** [comment]
> I... don't know. This is a request from @Kyep since I have Couls permission to republish these, but to copy straight out of Coul's PR.

This will make the code 513 compatible. Meaning arctan and islist are no longer required since byond now has their own procs for this. Same for the border variable it's no longer used.

**Comment by AffectedArc07** [comment]
May be worth making a system similar to https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9637/files as this allows for better modularity of procs changed between versions

**Comment by Cazdon** [comment]
> 
> 
> May be worth making a system similar to https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9637/files as this allows for better modularity of procs changed between versions

Since you know what you're doing a lot better, if you'd like to go for it and port that please do. I just republished this on request after all.

**Pull request merged**
