### PR TITLE
Adds dept shuttle

### PR DESCRIPTION
**Pull request by Kyep**
Adds a new, department-based shuttle for the Cyberiad.
This is an optional shuttle template, and will only appear if an admin chooses to load it.

Features:
- Shuttle cockpit with colorized chairs for the heads.
- Minibar for crew (unlike other 'bar' shuttle, this uses chairs, so you won't go flying)
- Individual, department-specific seating sections, which only members of that department can get into (unless someone smashes the windows). There is also a general/service section in the middle, and next to the bar.
- Small cargo and medical compartments, as now. 

Why would admins want to use this? A few reasons:
- Keep department crew separate, to minimize chaos on the shuttle.
- Treat the heads to a comfy flight for a job well done.
- Let the crew get completely hammered with the open-access bar.

🆑 Kyep
add: New 'department' shuttle, which can be sent by CC instead of the regular evac shuttle.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
needs barstools at the bar not chairs. *stares* its more fun that way....

**Comment by Kyep** [comment]
I deliberately used chairs instead of barstools so everyone wouldn't fall over when it launched. 

If there's great demand for barstools, I can use them, but we already have a shuttle that uses a lot of barstools, and I wanted this to have its own theme.

**Comment by Ralta** [comment]
Nice, I like it! Any chance of adding a rollerbed or two to the medical area, even if they're folded up? Handy for crit patients you didn't have time to stabilise prior to boarding.

Otherwise, +1!

**Comment by swordsith** [comment]
looks neat if you could shove airlocks in instead of windors it'd be heccka neat, maybe making it more compact ish like a train with rooms on the right and left.

**Comment by taukausanake** [comment]
I guess you can't make a bigger shuttle than this size? A large shuttle would be cool for those really high-pop rounds

**Comment by Kyep** [comment]
@Ralta Roller bed added.

@swordsith Airlocks won't really fit. And they'll physically prevent, say, security from breaking in if they really need to.

@taukausanake issue is: if I make it bigger, not only might it not align with the dock, but also, everything that messes with shuttles now has to account for bigger/variable size.

**Pull request merged**
