### PR TITLE
Removes Ghost Chilli Juice and Dragon's Breath Reagents

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Before accusations are thrown around about this; no I haven't been a victim of this. I included these two reagents in the "additional reagents PR", but I've been keeping a very very close eye on them to see how they're used and how much.

Unfortunately it's as I've feared--neither of these are rarely used; they're the first go to things anyone with chemistry or sci-chem access to making to murder people with, with nearly a 100% success rate. Worst yet, when the player is killed, they have no way of getting back into the round. Why even bother with the RNG of uplink-only super chems when you can make this?

Thus:
- Removes Dragon's Breathe Recipe (the reagent remains in for adminbus)
- Removes Ghost Chilli Juice

:cl: Fox McCloud
tweak: Removes Dragon's Breath Recipe
tweak: Removes Ghost Chilli Juice
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Okay, for a moment there I thought you meant the shotgun shells. Never seen these in action though

**Comment by Fox-McCloud** [comment]
edited title for clarity

**Comment by Fox-McCloud** [comment]
>Never seen these in action though

Basically they can `dust` you, meaning you and everything on you are permanently gone---no chance to come back.

**Comment by IK3I** [comment]
they make you go away in a manner similar to the crematorium. Kinda broken when you can just powergame your way to instant cremation

**Comment by fludd12** [comment]
I suggest keeping the Dragon's Breath as player create-able, but make it require annoyingly difficult to obtain stuff, like advanced mutation toxin with capsacian. This way, you'd have to mass-breed black slimes or abuse an odysseus (which can be shut down hard, if discovered) in order to make the stuff.

**Comment by QuinnAggeler** [comment]
Wow, that is, like absurdly OP. Murderous chili juice sounds like something that should be locked away behind the highest tiers of botany, guarded by the caprice of the RNG, rather than something that could be whipped up without fail.

**Comment by IK3I** [comment]
It is locked behind the gate of mutation, but it will take at most one hour of work to get to the highest tier of anything in botany or xenobio if you know what you're doing. Having something that lets you get away with murder scot-free for one hour of your time is well worth it to any powergamer.

**Comment by Da-Dman234** [comment]
Can confirm, used this today (In a hallway full of people no less) to kill a target of mine. Literally walked up to him, forced him to drink one sip, he dusted and I walked away scott-free.

That is not something that should ever reasonably happen, no matter how hard you make it to get (Nevermind how easy it is to make now). I quite literally cannot think of anything stronger, and this is me saying so without even having put it in a syringe gun yet.

**Comment by DaveTheHeadcrab** [comment]
@Da-Dman234 
Imagine if you had the traitor dart pistol that doesn't make messages when you fire it.

**Comment by FlattestGuitar** [comment]
Yep, I've been toying with both of those lately and they're insanely powerful. 

I'd remove the dusting from the ghost chili juice, because the screaming and crying is hilarious.

**Comment by mrturkeytoe** [comment]
@Da-Dman234 That was me you melted! >:|
https://www.youtube.com/watch?v=GPO43kCh3_c

**Comment by Bigtimetripod** [comment]
Wasent the "dusting" heavy RNG like Initro heart attack? I thought thanks to the RNG element i was quite useless like initro. Not calling initro useless, but RNG jesus really needs to be on yer side cause sometimes ye kill a person with 5 units, sometimes ye need 30 units...

**Comment by taukausanake** [comment]
I got a question. Does this work at an injected/consumed reagent or can it be used with smoke reactions with the same effect?

**Comment by KasparoVy** [comment]
Even with the RNG you're guaranteed to dust the target in a few seconds

**Pull request merged**
