### PR TITLE
Updating Resource to /tg/ standars along with factory

### PR DESCRIPTION
**Pull request by Robertha89**
title, makes resource nodes far better. should pick up the drag that is costing resources to send blob to corpse.

### CODE REVIEW

**Comment by Regen1** [comment]
This is over double the speed, I am not sure if blob needs THIS much of a buff..

**Comment by Fox-McCloud** [comment]
:+1:  Considering how useless resource nodes are currently.

**Comment by ZomgPonies** [comment]
Between this and the blobs respawn rate increase, I'm afraid we'll be looking at some power creep.

**Comment by ZomgPonies** [comment]
Alright let's add this in also, and then stop and take a look at how blob plays out now, and decide what, if anything needs to be balanced from there.

**Pull request merged**
