### PR TITLE
Ports 3 New Chaplain Weapons

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports: https://github.com/tgstation/tgstation/pull/18086

Implements 3 new chaplain weapons:

- Pirate Saber
- Multiverse sword
 - Above two are just claymore reskins
- Possessed/Talking Sword

The possessed/talking sword can be activated, where upon it'll poll from the ghost population, then put them into a shade which will be placed into the blade itself. It can't do much other than, well, talk.

img1

Also fixes not being able to sheath the claymore in the Crusader armor.

:cl: Fox McCloud
Add: Adds three new chaplain weapons: pirate saber, multiverse sword, and possessed/talking sword
Fix: Fixes not being able to sheath the claymore in the Crusader Armor
/:cl:

### CODE REVIEW

**Comment by TechDragon610** [comment]
how are these reskins triggered?

**Comment by taukausanake** [comment]
I see that you can name yourself when you enter the blade. Sounds like a nice ghost role to play. Hope it happens enough

**Comment by Regen1** [comment]
While these sprites are fine and dandy, I feel like they are misplaced in the SS13 universe

If anything, all these chaplain items should at the very least have some form of religion tied to them, so the chaplain gets the weapon of his religion or whatever.

**Comment by Iamgoofball** [comment]
@Regen1 SS13 universe is clowns, mimes, and chaos dunks from b-ball wizards, this is nothing

**Comment by Regen1** [comment]
All of that is spread out, these are all collected under a single job

And TBH the only "odd one out" is the clown and mime

**Comment by fludd12** [comment]
I half agree that them being all under one job is a tad weird, but remember that you can only ever have one per round. I think it fits quite well when you realize that.

**Comment by taukausanake** [comment]
Yeah I think that fits the bill. I don't see a good use for the pirate saber unless you're going to be dressed like a pirate and preach piracy (in which case I might have a new character and job calling) but then that's trouble on other levels

**Comment by KorPhaeron** [comment]
I'm always torn between being happy my stuff is being ported and a bit sad someone elses name is on the changelog

@Regen1 

The idea was the chaplain would choose a gimmick weapon to match their religion, but yeah it's been kinda wonky with crusader chaplains running around with katanas.

We crossed that bridge a long time ago though.

**Comment by Spacemanspark** [comment]
I can do the same damage in most cases with a welding tool turned on, and it also fits into my pocket, and there's a lot of them.
Or a spear. Easily to craft as well.
Meanwhile, only one null rod unless the admins spawn in more.
Really, this isn't a large issue.

**Comment by Fox-McCloud** [comment]
@TheDZD merge conflicts fixed; this should be ready.

**Pull request merged**
