### PR TITLE
CC Map Updates

### PR DESCRIPTION
**Pull request by Kyep**
1) Gamma armory is now part of CC. It is no longer a weird room floating by itself in space. This also means that, admins permitting, ERTs can be issued items from it more easily. It is defended by pulse turrets that shoot everything. 
2) Adds a small prison area to the special ops portion of centcom.
3) Fixed a bug with the specops mech launchers, where the runway was slightly too long, sometimes causing mechs not to actually reach the teleporter at the end of the runway.
4) ~~Thunderdome is now connected to CC, via the Special Ops area. Ever wondered what CC does with the prisoners its ERTs bring back? Now you know. Note: this only allows access to the non-admin, guest, observer area for thunderdome. It does not allow access to the areas the players spawn in, nor areas the admins use. It only allows, at best, people to observe, and even that, requires an admin to turn off the turrets/open the doors to allow access to the observation area.~~ Removed cause Neca wanted it so.
5) Cryodorms have been added to CC. This provides an IC explanation of where ERTs, DS, etc come from (they're stored in cryo until needed). It also allows ERTs who are recalled to central and complete their mission to cryo themselves at CC.
6) Adds bushes/flowers to CC. Mainly because plain green grass looks ugly. This looks better.
7) Added medical outpost to CC docking area. Mostly for RP, so people who want to be sane (and not just murder each other) can patch themselves up quickly.
8) Added new map icons for CC areas. (CC, CC Ferry, CC Supply, CC Evac, CC Control, CC Specops, etc). These only show up in DM. 

🆑 Kyep:
tweak: Updated CC map.
/🆑

### CODE REVIEW

**Comment by Lady-Luck** [comment]
The gamma armory on the station is a waste of space, getting rid of it on the station gives a bit more room for the brig mapping.

**Comment by Kyep** [comment]
@Lady-Luck I want to convert the Gamma Armory (both on-station, and on CC) into a shuttle. That would make a lot more sense. However, I have too many Cyberiad map PRs open currently, and I don't want more map conflicts. If I do it this way, though, I can get some of the CC map edits done now, and then turn Gamma into a shuttle later on.

**Comment by Lady-Luck** [comment]
>I want to convert the Gamma Armory (both on-station, and on CC) into a shuttle.

We need less shuttles, not more.

**Comment by Fox-McCloud** [comment]
A lot of this is, to be blunt, unneeded fluff for something that takes place during the last 60 seconds of the round.

Mentioning "RP" with anything that takes place when people are out and out murdering each other just because they can is...a bit disingenuous,  at best. Even if we had the "no post-round violence" rule in place, making lots of "RP" changes for what is effectively ending credits is ...a bit silly.

The prison area in particular has no reason to be IC, as it's a purely OOC thing--it's for people who aren't paying attention and you want to isolate to talk with them; it was never meant to be an IC thing, at all.

Thunderdome is isolated because of all the whackiness that goes on, and so people can't somehow break out and screw with things in CC.

We've *been* down the path of a sprawling "immersion" based CC. It doesn't get used, it's unneeded fluff, and doesn't do much for the map or players; it was rejected outright.

`Added new map icons for CC areas. Only shows up in DM.`

This is about the only part of the PR that I support.

**Comment by Fruerlund** [comment]
Where am I going to place my operations department now? 

This is good, especially with the cells. 
☝️👍👍

**Comment by HereticChurch** [comment]
Other than the prison I think this is all perfectly fine. The  turrets and the blast doors would do a perfectly fine job keeping the thunderdome participants out of the main area if they somehow manage to get out through the indestructable windows and through the CC locked doors. I do really like the cryo addition as well, as a way for the ERTs to ghost out without leaving their bodies on CC.

I think a more interesting, immersive CC is perfectly fine as long as it doesn't somehow get abused by players, and even if it does the admins should handle it quickly, so that is almost a moot point. It might not get seen as often by players but there's no real harm in it. As long as we don't start throwing personal fluff into the rooms and shit I'm sure it'll be okay.

**Comment by Kyep** [comment]
@Fox-McCloud @HereticChurch 
FYI:
- IMHO, it is nice if CC looks nice (flowers, etc) and we don't have rooms just floating in space. It is also tidier.
- Prison is sealed such that each cell has a wall (door sprite) and fake glass (unbreakable glass) in front of it. There is no way out of it. 
- Thunderdome is still isolated. This just allows transit from main CC to thunderdome observation area. It doesn't allow transit into the actual loadout areas.

**Comment by Twinmold93** [comment]
Central (z2 in general) needs to be remapped. Having everything closer together means that there is more open space for OTHER things when its decided to add other things, if ever decided to do so. A few admins already make adjustments to CC as is to make it a bit more realistic (such as the added office and central Cyberiad monitoring area). Many times, I use z2 for events as is, and having additional space means I can do better events on occasion (for like dead chat or casino). Saying aesthetics make no difference only because we don't let people see it as is is counter-intuitive: We don't tend to do anything with it because it does look bad as is; you don't tend to want people to see poor maps until they are better. This is FREE work to the level to make it look better that has no actually significant effect on performance in practically any degree (presuming it's still unsimulated, which it most likely is). And just because people have done things a certain way for a long time (like end-round death match) doesn't mean they wouldn't appreciate something different from time to time. As for RP, if we start showing we SUPPORT role-playing, in more than just the station and rules, with things like this that make more sense, people might start viewing us as wanting to move towards a more RP friendly server: It's a mentality, and the only way to change it is start subtly supporting it. Will end-round still be bloody? Of course. But it gives the ERT an excuse to go back, too, rather than stay on the station, because there is something TO go back to. And if people think they can get opportunity to go back with GOOD role-play and want to go and see it and check it out, that can support them in a mentality state in trying to role-play more in general, because they want to check out the cool new area.

Just because you don't see us using it all the time doesn't mean it's unnecessary. Look at the Ninja area. We don't use it AT ALL for anything OTHER than a very rare event that is called once every other blue moon, why is it still there? The dead bar is the same way. Hell, even the prisons are unused by practically ALL admins. They are there, however, for the time we want to use it. A modified Central would be the same way, it'd be there for when we WANT to use it.

**Comment by Fruerlund** [comment]
Not a fan of cutting the prison off. Whats the point of it. Before this PR it served no purpose. Who magiclly teleports people to the prisons to punish/ban them anyway???? 

Now we had a proper RP use for them as the prisomers could be interacted with in a minor way. 

Either get rid of it, or add a 2nd prison area for roleplay purposes connected to the central CC

**Comment by Fruerlund** [comment]
Also Central Command is used during rounds anyway for events or atleast I do

**Comment by Markolie** [comment]
👍 I never liked CC being stripped down because of "never being used".

**Comment by MrFroztee** [comment]
It's stripped down because it's an admin area, and is only used functionally, unless of course, the admins are bored out of their minds. Considering it's really just the uh..indication that you've arrived at your destination, I really don't know what purpose the extra detail entails. Seemed fine to me as it is.

**Comment by Draconic-saint** [comment]
I think this will rarely be used, but then again, it doesn't hurt to have some of it in either.

I do like the flowers and medical outpost. They're legit additions that make CC better IMO, for both players and admins trying to plan post-round stuff.

Cryo is legit useless, admins spawning their chars on CC can easily just delete the mob. As for the "DS on ice" explenation. I'm gonna be frank and call that just stupid. They can just as easily be shuttled in as normal crew on the arrivals shuttle. And for allowing ERT to cryo, they can't in the current config, because of limited acces, IIRC. So you'd either have an admin baby-sit the ert even more, or just made a useless addition. Either way not good.

I don't like CC & thunderdome being connected. also holy fuck "ERT prisoners fight in thunderdome" is pants on head moronic. Thunderdome has been an event that has been completely seperate from main NT "canon" as long as I can remember. There is NO lore surrounding it, it's mindless violence broadcasted, that is it. Please don't try to fucking shoehorn it in with NT for your remaps.

My suggestion. Remove the cryodorms & thunderdome connection.

**Comment by Spacemanspark** [comment]
Well, you can see thunderdome matches via the entertainment consoles posted in a few various places on station. Surely that means that NT at the very least supports it.

**Comment by taukausanake** [comment]
> you can see thunderdome matches

Wait seriously? I've been wondering if that was possible for the longest time! I would set an event for ghosts to join Thunderdome on a quiet round and then the crew can watch them battle it out. I remember that having some opposition though...

One day I hope to have CC play a more active role in SS13, not just being admins but maybe highup players who wouldn't shit on everything right away. Another station. Otherwise most of CC really has no reason to exist. Just have boxes that are the rooms floating around

**Comment by Draconic-saint** [comment]
condoning & allowing acces to a certain network is not the same as hosting it. and even **if** they did, they would not be doing it in a slapped on module for an oficial adminstration station.

I honestly don't understand the need to connect everything on z2 that's close to eachother location wise. CC is unused for 95% of the time. It's fine to flesh the parts out that can be visited on round end, but otherwise, it's wasted effort imo.

When would the connections *ever* be used. It's just for aesthetic purposes for the **ghosts**. I'm sorry, but  the moment you're a ghost, immersion & RP become a non-factor.

**Comment by Necaladun** [comment]
I'm all for a more functional looking CC, great for events or when certain antags make it back there via ERT shuttles, etc.

CC not being updated because it's never used means CC won't be used as much. Unless it's actually got some negative effect on the main station, I see no reason not to update it.

**Comment by Draconic-saint** [comment]
It's not so much that i'm agaist CC being expanded, as that i'm against slapping the thunderdome on CC for no other good reason than to have a connection.

I wouldn't be opposed to move the thunderdome somewhere more remote and actually flesh it out to be a fully developed blood-sports stadium. But that seems outside of the scope of this pr.

**Comment by Necaladun** [comment]
Thunderdome being nice and seperate is good for giant mobs and oversized explosions.

**Comment by Kyep** [comment]
@Necaladun Thunderdome disconnected again. The only thing still on that side is the Gamma armory.

**Comment by Fruerlund** [comment]
Reading the comments I get that there are quite a few of us who would like to see more added to central Command. 

So why stop here? 

We should perhaps consider porting some of the other codebases central Command and make minor modifications to them. There are some very nice designs out there.

**Comment by Kyep** [comment]
@Fruerlund I actually based this concept on TG's version. The flowers and all. I don't want to outright replace our CC with one of theirs, as I feel I'd spend forever chasing down incompatible things that were not obvious. 

I have a stream of things I'd like to connect to the main CC: gamma armory, prison cells, thunderdome, etc. Unfortunately there were objections to the admin prison/thunderdome being connected. So, currently, just the gamma armory is connected.

Right now, the PR is: gamma connection, flowers, medical.

I am debating adding in a CC-prison (not an admin prison, an IC prison you can throw people into at CC, e.g: for terrible captains). 

I'm also debating adding in a more expansive docking area, e.g. for the cargo shuttle. Currently, it docks to a wall.

Other then that, if there is anything *specific* that you want me to add, tell me (in detail, preferably with screenshot) and I will certainly consider it. My goal here is to revamp/expand CC in ways that make sense. That means adding things which already exist (just need moving), and adding things you'd *expect* to see. Also, adding fun things that people can do post-round if they break into CC. I don't want to add lots of pointless fluff, though. It is a balancing act.

Again, suggestions welcome. Please be specific, not just "make it huge like <otherserver>".

**Comment by Markolie** [comment]
A prison (non-admin one for the ERT) would actually be pretty cool. We actually ran into a problem today where ERT had to lock up a criminal in the living quarters (with admin assistance).

**Comment by Kyep** [comment]
@Markolie Added one. Screenshot updated. Let me know if you have any suggestions.

**Comment by Fruerlund** [comment]
@Kyet 

I love the work you are doing and the prison was a good addition. Anyways heres a few thoughts. 

May i suggest moving/recreating more of the upper areas /bar/kitchen/ down below the checkpoint to increase the area size and make it more lively as crew is never going to make it up there and if you decide to have players there it would be an issue having them run between arrivals and the control room. 

Or

Move the control room to the area that connects to the gamma armory and move the checkpoint up and left so CC is split in half. Then some different areas in the big open area?

Throw in a firing range for the ERT when they are mission complete or perhaps an armory split into non lethal for minor operations / a more lethal one. (I know we have the ability to use select equipment/different alert levels) perhaps some riot guns, the dart guns.

**Comment by Kyep** [comment]
@Fruerlund 
- Re: CC bridge, right now there's nothing on CC bridge that we need to worry about crew having access to. Post-round, they can access it, but we don't care what they do post-round. During the round, its impossible to access without an ERT being called, you obtaining an ERT ID, plus either A) ripley with drill, or B) an emag. Even if someone has all of those, once we notice CC was broken into, we can spawn an officer and kill them. I have, however, considered adding some security to the CC ID, and/or the BSA cannon, such that you cannot access them prior to round end without an admin deliberately allowing it.
- Re: moving the bar/kitchen down below, I thought about it, but there's nothing up there that's amazing, and I'd rather keep that area reserved for returning ERTs and events, so people participating in those can see *something* they could not see normally.
- Re: firing range, I don't think the ERT would ever use it. 
- Re: armory split into lethal/nonlethal... ERT are meant to spawn with their gear. The bluespace gamma armory isn't meant to be accessible to ERTs, short of admin intervention - in which case they can already customize what's in the armory.

**Comment by Kyep** [comment]
@FreeStylaLT @Necaladun Should I keep working on this, or is it a waste of time?

**Comment by FreeStylaLT** [comment]
I do not think this is a bad idea, as long as most or all of the areas are bundled up into a single space, as opposed to being scattered all over.

I'd just replace the bathrooms here with the Gamma armory:
img
Make the door openable from the Operations office with CC access.
The whole turret idea seems to not have much merit, besides a tiny dash of realism and, if the airlock leading to it is accessible to ERT, just shot people.

**Comment by Kyep** [comment]
@FreeStylaLT 
The areas are already quite connected. Are you requesting a specific thing be moved? If so, what, and where?

I could put the Gamma armory there, but I assumed that people would want the bathrooms kept, as they have mirrors the ERT might use.

The door is already openable from the CC office with the button.  It has a blast door under it. The reasoning is that the blast door is access control, and the airlock limits turret fire when unlocked.

Aside from realism, the turrets also function as a CC defense system, and a challenge for post-round mischief-makers. They have several uses, and they aren't accessible to ERT by default. The mech room ones won't shoot ERT even if the door is opened. The gamma ones will shoot everyone, but it takes a CC officer to unlock that door, and admins can deactivate those turrets.

**Pull request merged**
