### PR TITLE
Removes unused adminverb

### PR DESCRIPTION
**Pull request by Regen1**
VV editing the AI/borg name works just fine

### CODE REVIEW

**Comment by Markolie** [comment]
Pretty sure it doesn't. It doesn't do any of this: https://github.com/ParadiseSS13/Paradise/blob/d829e7003ae03ab538b9333c1004a3a3ce43b127/code/modules/mob/living/silicon/robot/robot.dm#L319.

1) It doesn't properly rename the borgs camera name.
2) It doesn't properly rename the borgs PDA.

**Comment by tigercat2000** [comment]
Then it should, having an admin verb for that is insane.

**Comment by Regen1** [comment]
Our admin verbs are already insanely cluttered and messy.

**Comment by Markolie** [comment]
"Then it should, having an admin verb for that is insane."
Then it should probably added to the View Variables menu before this verb is removed.

**Comment by Alex6511** [comment]
Broken code gets fixed, shit code stays forever. If the VV before this.

**Comment by Fox-McCloud** [comment]
Do you plan on changing the PR or will you be opening a new one for this, @Regen1

**Comment by Regen1** [comment]
I'll try to add it to the PR, I might not be able to code it though

Lets hope I don't kill tiger with questions

**Pull request merged**
