### PR TITLE
Soul shard dull name fix

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

fix dull dull dull dull dull dull dull dull dull dull dull dull dull shard

## Why It's Good For The Game

dull

## Testing

compiled, used shard on construct shell

## Changelog
:cl:
fix: soul shard is not anymore dull dull dull dull dull
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
> cumpiled

image

**Comment by Henri215** [comment]
Nice one 😆 , now update the PR title so its not a pain to search in the future.

**Review by warriorstar-orion — APPROVED** [review]
LGTM

**Review by lewcc — APPROVED** [review]
looks good good good good good good good good good good good good good good good good to me

**Pull request merged**
