### PR TITLE
Sets IV Drip density to 0

### PR DESCRIPTION
**Pull request by uraniummeltdown**
It's inconsistent for players to be able to run over chairs, stools, beds, and potted plants, but not over thin metal IV drips. Also it's just generally frustrating having to shuffle around IVs because they're blocking your path.

I removed the var edits with a text editor only, do I need to do it with DM+mapmerge so that it reassigns keys or is that not necessary?

"Fixes" https://github.com/ParadiseSS13/Paradise/issues/6889

:cl:
tweak: IV Drips are no longer dense objects, you can walk over them.
/:cl:

### CODE REVIEW

**Comment by tylerh95** [comment]
Makes sense, IV drip poles are generally not huge, and it makes sense that you'd be able to slip past them.

**Comment by FlattestGuitar** [comment]
No real reason for their density to be at 1 to begin with. You can move them around freely and this doesn't really add anything to the game other than being annoying.

**Comment by Crazylemon64** [comment]
Please do this in-code, not via map edit. Otherwise, this won't apply to new IV drips. Fixing this would be as simple as inserting `density = 0` below the entry for `/obj/machinery/iv_drip`

**Comment by Crazylemon64** [comment]
Eh you know what screw it

We're over 50 PRs, if you're going to submit a PR, please make sure it's well-thought through.

**Comment by Crazylemon64** [comment]
nevermind, I am stupid and got things backwards

**Comment by Lady-Luck** [comment]
Wouldn't this affect both stations?

**Comment by Fox-McCloud** [comment]
If you use a map editor to make changes, you don't have to map merge.

**Comment by uraniummeltdown** [comment]
@Lady-Luck only the metastation map is edited, meta's IV Drips were var edited to have density = 0 and since normal IVs are non-dense I removed the var edits

**Comment by SamHPurp** [comment]
Practicing what I preach and giving the reasons I thumbed it down:

1. Vampires that are topping up their victims would now need less space to hide in, and suddenly more maintenance bolt holes are available to them

2. I kind of enjoy when medbay is in chaos and someone accidentally pushes an attached IV away, causing damage.

3. Nostalgia really.

I'm not going to be upset if it merged, but I figured I'd sensibly lay out my reasoning behind why I don't explicitly support it.

**Comment by taukausanake** [comment]
Yeah I kind of agree with Sam here, seeing those IV drips having some physics is nice. It's a good QoL having 0 density but it takes away a little bit of what makes it what it is

**Pull request merged**
