### PR TITLE
Wizard will now always recieve a hostile objective

### PR DESCRIPTION
**Pull request by Alex6511**
This is to push wizards away from being "Friendly." They are antagonist for a reason, if an admin wants a non-hostile wizard, they can obviously create custom objectives or modify the objectives at round start. It also gives wizards that do not have a hijack objective to also have a steal objective, to prevent stealth wizards from being passive until the very end of the round, or waiting until the end of until the end of the round, quickly killing your target, then jumping in a pod.

### CODE REVIEW

**Comment by Robertha89** [comment]
I am kinda against it, KINDA, but fuck friendly wizards, we all know they are assholes. :+1:

**Comment by Alex6511** [comment]
Don't merge this yet, going to modify the numbers some more.

**Comment by Aurorablade** [comment]
i disagree while they are antags..an antag that is able to rp and has the option to NOT murder should be encouraged to do so to make the round interesting. its a matter of the antag having the choice of 'do i want o kill everyone' (Don't get me wrong, that CAN Be fun!!) or 'do i want to mainpulate them into geting what i want' (Also FUN)...lets not forget 'do i want to mind swap everyone i see while blinking around naked' (QUEUE BENNY HILL MUSIC!)

**Comment by theColdflame** [comment]
I agree with this, Wizards aren't intended to have a friendly option.

(I also think friendly wizards make rounds boring for everyone except the wizard and one or two crew members, but that's outside the scope of this discussion)

**Comment by Earthdivine** [comment]
The problem with Friendly Wizards is the same problem with Vox Traders, it makes the round into Extended. There's nothing wrong with a wizard trying to be friends, but if he's avoiding doing any thing at all that feels like a gross misuse of his powers. The round ends when he dies because his arsenal is geared towards mass destruction. Your not adding anything to the round, your just another crew member at that point.

Trying to be friends with everyone and ei nath/ Lighting Boltings rude people who try to club your face in because you want the pretty things is a good example of a friendly wizard who still adds to the round.

Quite honesty I think the Wizard shouldn't have any objectives at all other then Survive or Hijack, but that's me.

**Comment by tigercat2000** [comment]
I don't think this will fix what you are trying to fix. People can just ignore their objectives.

**Pull request merged**
