### PR TITLE
Nations 2.1.1 bugfix

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Fixes Servicion HUD icon
- Fixes Peacekeeper borgs
- Fixes borg icons and the combat/peacekeeper subtypes
- Borgs created by robotics after kickoff become Peacekeeper borgs.
- Gave wrench back to Combat/Peacekeeper borg because tables

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Can you please start updating your branch before pushing commits?

**Comment by ZomgPonies** [comment]
Umm it is?

**Comment by TheDZD** [comment]
Doesn't seem to be the case, given the three merge commits.

**Comment by ZomgPonies** [comment]
Alright I'll try that next PR.

**Comment by Zuhayr** [comment]
You can also just git rebase -i upstream/master to get rid of the merge commits.

**Comment by tigercat2000** [comment]
Or use an alias reset script like I do
```
git checkout master
git fetch upstream
git reset --hard upstream/master
git push origin master
```

**Comment by ZomgPonies** [comment]
There we go, thanks Zuzu

**Comment by Zuhayr** [comment]
Any time.

**Pull request merged**
