### PR TITLE
Delta dorms remap

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR remaps delta dorms to be less of an empty void with a large number of doors in-between.

## Why It's Good For The Game
Currently, delta dorms feels devoid of character and is oversaturated with doors for no reason.
What is meant to be the primary hangout spot for crew is far inferior to areas such as library or bar. This attempts to bring it to the point where it can compete with them.

- The overall footprint was lowered
- Lounge area with electrochromic windows was added
- Changs comes to delta
- Boxing ring uses railings now
- Weird holodeck setup simplified
- Mini-arcade added (I have not touched the one in fore starboard maintenance)
- Bedrooms removed
- Maint room below court expanded with a crittercare setup and some other vendors
- Cryodorms consolidated into one room
- Abandoned sec storage area converted to use chainlink fences

### Old Dorms:
deltadormsold

### New Dorms:
deltadormsnew

## Changelog
:cl:
tweak: Deltastation dorms remapped to be simpler and more cozy.
/:cl:

### CODE REVIEW

**Comment by Wojz** [comment]
No gym. Absolute cowardice. I like it a lot though. Defo gonna actually hang out there now.

**Comment by S34NW** [comment]
will deconflict when required

**Review by variableundefined — APPROVED** [review]

**Comment by S34NW** [comment]
Please note https://github.com/ParadiseSS13/Paradise/pull/16837 should be before this in the queue, despite the actual PR order.

**Comment by variableundefined** [comment]
No agreement on what to do regarding this PR. Also, we'd rather keep Delta and Meta mostly unchanged for now and focus on fix. Closing.

**Pull request closed without merging**
