### PR TITLE
Tesla Grilles

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Grilles now have a 50% chance to spawn a tesla bolt and zap you if you throw an object at them and there's a powered cable underneath. The damage is not too serious, at roundstart it does 10 burn to zappees.

:cl:
add: Powered grilles now have a chance to zap you when you throw an object at them.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
End grille violence today.

**Comment by FreeStylaLT** [comment]
What about the non-conductive items like glass? You can cut active grilles with a shard, why would throwing it cause a zap?

**Comment by uraniummeltdown** [comment]
Well I guess I could make it respect CONDUCT flag, but glass shards are very common so it's not much of a deterrent if they can't zap you too.

**Comment by scrubmcnoob** [comment]
That doesn't seem consistent.

**Comment by Rumiluntti** [comment]
Heeey, this means I can make a paper-disposal engine!

**Comment by KasparoVy** [comment]
Really should respect CONDUCT flags.

**Comment by tylerh95** [comment]
The entire idea seems inconsistent to me, why would the force of something impacting an electrified grille cause a tesla bolt to shock you? Additionally, wouldn't it be more likely that the bolt would shock the item (if conductive) that was thrown rather than the person who threw it?

**Comment by KingPhilipIII** [comment]
Tesla grilles are a bitch. When the engine is running, and all the APCs outputting, that shock can be lethal.

**Comment by AffectedArc07** [comment]
YES WE CAN MAKE TESLA ENGINES

**Comment by KingPhilipIII** [comment]
I've actually seen a group of five armed revs get fried by the chief engineer with gloves and a hard suits using tesla grilles. He threw glass shards while they were smashing their way in to murder him with looted guns and spears. One blast stunned them all. Second killed most. Third burned them to a crispy

**Comment by uraniummeltdown** [comment]
We can always nerf the damage if it's too crazy

**Comment by KasparoVy** [comment]
Conductive flag check?

**Comment by davidchan13** [comment]
Tesla bolts from grills don't really make sense, least not jumping from the grill directly to someone who isn't even next to it.

**Comment by Anticept** [comment]
Or how about grilles are a lot stronger when you try to throw shit at them?

**Comment by uraniummeltdown** [comment]
No conductive flag check, yes it's not realistic but glass shards are the most common item used to break grilles. Anyway with a normal full powered SMES setup the bolts do 23 burn. It only gets really dangerous if you hotwire the engine where with a power 2 tesla the bolts do 127 burn, but door shocks do 86 burn so it's not too crazy.

**Comment by KasparoVy** [comment]
I can't see a way to rationalize supporting this then unfortunately. I feel it's confusingly nonsensical

**Comment by Regen1** [comment]
This seems more of a TG meme than anything
We don't need more of this on paradise.

**Comment by Fox-McCloud** [comment]
It's absolutely not a meme.

It was a design element to add additional danger to the station and discourage cheesing of grills without protection, while also remaining consistent with their object damaging system.

**Comment by SamHPurp** [comment]
Why don't you just copy all of TG over and delete Paracode @Fox-McCloud ?

Seems to be the way you want to go.

**Comment by Regen1** [comment]
>throw a crayon at a set of steel bars
>It's arc flashes and kills you

Yeah no that seems perfectly sensible

**Comment by Anticept** [comment]
Again. If cheesing grilles is a problem, then consider throwing vs meleeing them. Throwing items is hard to damage them, taking a lot of effort, while melee would still be simple. This is much more consistent.

**Comment by davidchan13** [comment]
>Vampire screams near the armory.
>Shatters all glass to exterior
>Glass shards, metal rods and loose objects pulled by space wind against the grills
>Sec can't use armory for the rest of the round cause the area is death trap with only one bolt needed to stun you and the rest kill you.

**Comment by uraniummeltdown** [comment]
@davidchan13 Shoot the grille with a laser to destroy it, then get Engineering to fix it and make it more secure

**Comment by jughu** [comment]
@davidchan13 it auctally have to be thrown into it spacewind wont doing anything

**Comment by Fox-McCloud** [comment]
>Glass shards, metal rods and loose objects pulled by space wind against the grills

This would never happen. Space wind doesn't throw things; it just pushes them around.

You have to actually throw things at the grill for this to be triggered; it just bumping into the grill will only ever call `Bump`.

**Comment by PJB3005** [comment]
This meme makes no sense why are you porting it.

If you need to make grilles more lethal, there are *much* better ways to do it than making paper engines holy shit.

**Comment by PJB3005** [comment]
Lol

Paper engine when

**Comment by uraniummeltdown** [comment]
now

**Comment by KasparoVy** [comment]
Lmao... Oh well.

**Pull request merged**
