### PR TITLE
Adds all Vox Skirts and CMO Uniform

### PR DESCRIPTION
**Pull request by KasparoVy**
Someone brought it up in game. Didn't realize I'd missed this until now.

:cl:
imageadd: Adds Vox compatible versions of all jumpskirts.
imageadd: Adds Vox compatible version of the CMO jumpsuit.
/:cl:

voxskirts

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
skree :+1:

**Comment by Plotron** [comment]
You'd never want to look up their skirt...

**Comment by Norgad** [comment]
@Plotron You wouldn't find anything anyway

**Comment by taukausanake** [comment]
These are what the skirts look like? Man I thought they were frilly skirts, this is kind of a let down :(

**Comment by KasparoVy** [comment]
Yeah, they're businessy and only slightly short. If you want frilly dresses, just about EVERY OTHER dress will suit your tastes.

The security and warden dresses do have low v-cut necks, though.

**Pull request merged**
