### PR TITLE
/tg/ Mecha - Part 2, Action Buttons!

### PR DESCRIPTION
**Pull request by tigercat2000**
It's been long overdue for Mecha to get finished off. Unfortunately, this leaves room for a third part, which would be primarily focusing on converting mecha to the object integrity system instead of the snowflakey bullshit they use now. 

This is a continuation of the PR #5429, updating our mechs to /tg/'s far superior code. The primary portion of this PR is converting all of the mecha verbs into action buttons and screen alerts. See the CL for all changes.

On top of that, I've taken it a step further and added something that /tg/ should probably backport, honestly; Rather than porting their "cycle weapons" action button, I've taken advantage of radial menus to make a radial equipment selection wheel.

:cl:
add: Mecha now use action buttons instead of ugly verbs.
add: Mecha weapons can now be selected through a radial menu brought up by Ctrl Clicking on the Mecha while you are piloting it.
add: Tooltips now appear on radial menu buttons when you hover over them. Seriously, why wasn't this a thing in the first place?
tweak: Action button icons are now located in their own file.
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
Not enough tags

**Comment by AffectedArc07** [comment]
Finally, I missed these ever since I stopped on oracle

**Comment by TDSSS** [comment]
Oh, neat. Very useful feature.

**Comment by Mitchs98** [comment]
This is literally amazing.

**Comment by Kyep** [comment]
What if the mech has more than 3 pieces of equipment? Does the radial menu handle that?

**Comment by Spacemanspark** [comment]
Radial menus remind me of playing a Metroid Prime game on the Wii.

**Comment by tigercat2000** [comment]
@Kyep Radial menus can handle any arbitrary amount of mech equipment, if it gets too long it'll automatically form a page button. But as far as I know, there's no way to actually attach that much shit to one mech.

**Comment by Xantholne** [comment]
Is the fixated /tg/ mech movement planned to be added to this? i.e. locking your mech to face West while still moving North/South/East/West freely.

**Comment by tigercat2000** [comment]
@Xantholne That's called strafing - not in this PR, but it's plug and play.

**Pull request merged**
