### PR TITLE
Species name now shows in a species theme color on examine

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
Species name now shows in their theme color on examine. I have added theme colors to a few races that lacked them. Example images below. This really depends on your personal preference, and if majority of people dislike this, I will close the PR.

**Images of sprite/map changes (IF APPLICABLE):**
Vox
Diona
Slime
Grey
Unathi

Partial port from Aurora Station. Baystation12 also has this.

Tested locally without any issue.

**Changelog:**
:cl: Arkatos
tweak: Species name now shows in a species theme color on examine
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
I find it hard to read and weird, what's the need for this?

**Comment by AffectedArc07** [comment]
@Arkatos1 I kinda stand with Ty here, and have you tried these in darkmode? You have to consider that too

**Comment by TDSSS** [comment]
Not a fan, tbh

**Comment by Arkatos1** [comment]
@AffectedArc07 I have tried and it works and looks fine in darkmode, atleast to me.

This kinda depends on each one personal preference, but if majority of people dislike it, I will close it. Keep in mind that each color can be changed to be something else, brighter or darker without problem.

**Comment by AffectedArc07** [comment]
@Arkatos1 can we get screenshots of both?

**Comment by Arkatos1** [comment]
@AffectedArc07 Sure.
Dark Mode examples:
DarkVox
KidanDark
MachineDark

**Comment by Tayyyyyyy** [comment]
I'm not sure that the human "color theme" is a good idea. I know that the "flesh color" is just the starting point for human skin tone already in the code, but if we're going to expose this to players, it should either match the skin color of the human being examined or pick a random skin tone. Otherwise, it probably doesn't send the right message that pale (and what most of us would probably call white) skin is the "theme" of humans.

**Comment by Bookdrizzt** [comment]
The Vox and Diona are pretty ugly-looking to me, being honest. Also, what’s the Skrell, IPC, Plasmaman, etc colors? Those seem important to show.

**Comment by Fox-McCloud** [comment]
>I'm not sure that the human "color theme" is a good idea. I  know that the "flesh color" is just the starting point for human skin  tone already in the code, but if we're going to expose this to players,  it should either match the skin color of the human being examined or  pick a random skin tone. Otherwise, it probably doesn't send the right  message that pale (and what most of us would probably call white) skin  is the "theme" of humans.

Or we could do an average of the skintone of all our human players and set it to that.

**Comment by Dinarzad** [comment]
Make it gold.
Because Humans are number one and are the Gold standard for Nanotrasen.
:D

**Comment by Tayyyyyyy** [comment]
> Make it gold.
> Because Humans are number one and are the Gold standard for Nanotrasen.

I like that. Emojis by default are gold. Nobody says theme colors have to be determined from skin color.

Another option is to just leave humans as normal text color, because they're the "boring" race anyways, and trying to determine the "color" of humans seems like a pointless endeavor.

Averaging could work, but we don't really track that data as far as I know and I'm not sure it'd be worth the effort, especially because tide baldies being the default flesh color can skew the result. It would probably be more neutral to just pick the color that's in the middle of the range if we were to go with some kind of average.

**Comment by KasparoVy** [comment]
I'd be down for gold. I never play as a Human and it seems like a reasonable and acceptable solution.

**Comment by variableundefined** [comment]
I also prefer gold.

**Comment by Arkatos1** [comment]
Gold color added as requested.
goldhuman

**Comment by KasparoVy** [comment]
Sweet!

**Pull request merged**
