### PR TITLE
Safety First!

### PR DESCRIPTION
**Pull request by swordsith**
This Commit add's Re-enforced walls in place of normal walls along the
hull. I'm almost positive anywhere it would make sense for there to be
Re-enforced wall there is now, Pictures:
Before
before
After
after

Before
image

After
image

Before
image

After
image

Before
image

After
image

I did this Commit because i saw that most maint's already had re-enforced walls along the hull Ex sci-maint 
image

There wasn't many but I figured i'd make it uni-formal.
There /is/ others than the ones just showed in the pictures but i could not be bothered.

### CODE REVIEW

**Comment by Norgad** [comment]
You'd really need screenshots for these changes, also some of the walls being non-reinforced are for balance reasons People had a massive shit-fest last time someone tried to change all the walls around.

**Comment by swordsith** [comment]
@Norgad hmm? Guess it make's since. what shouldn't be re-enforced?

**Comment by Norgad** [comment]
It's really all over the place. Personally I'd just leave all the walls alone for now, until some glaring issue pops up.
Plus, no map edits on box can go through until #6076 is merged

**Comment by swordsith** [comment]
@Norgad true figured i may as well start the PR and fix it when and if that's merged.

**Comment by swordsith** [comment]
Also how do I add a label lmao

**Comment by Norgad** [comment]
You cannot.
That's the maintainers' job.

**Comment by Kyep** [comment]
@swordsith There are three locations (north arrivals maint, sci maint, and eng shuttle maint) that I deliberately put non-reinforced walls for, so that SIT team members arriving in their shuttle could easily make a false wall and get in, without having to spend ages deconstructing an rwall. Please don't have reinforced walls in these areas. Rest of the walls are fine, but please not these three places. You can identify them because they have a shuttle dock beacon next to them. It looks like a red pinpointer in DM.

**Comment by swordsith** [comment]
@kyep oh makes sense I wasn't sure what those were there for, on it. Maybe in a hour I'll do I just woke lmao.

**Comment by swordsith** [comment]
engone
scifin
arivfin
Like this @Kyep i'll commit it if this is watcha ment

**Comment by Kyep** [comment]
Yes, @swordsith - that's what I meant.

**Comment by Iamgoofball** [comment]
# kickin rad place to be

**Comment by Fox-McCloud** [comment]
This is going down the same, exact, path the previous one is; closing it now.

**Pull request closed without merging**
