### PR TITLE
Adds config option to let players see their own notes.

### PR DESCRIPTION
**Pull request by monster860**
It's a fucking config option, and it's not enabled by default
===

The salt is real
===

I'm 99% sure it says somewhere on my notes that I wrote a translator script in NTSL. By the way, I NEVER FUCKING WROTE THAT SCRIPT
===

There's literally no way to know if there's inaccurate data in your notes.
===

Okay, fine, I'll stop spamming the H1 text.....
===

Ported from tgstation/tgstation#6490

When enabled in config.txt, this allows players to see their own notes.

>Eh, at this point we've been making notes without the intent of showing it to any non-admin for years.
Can't exactly transfer to a different, more public method just at the snap of a finger.

-FreeStylaLT

And.. now you can.

:cl: monster860
rscadd: Adds a config option to allow players to see their own notes.
/:cl:

### CODE REVIEW

**Comment by Wheatley29** [comment]
The point of notes is so admins know who does what and who to look out for, not so players know when the admins are onto them doing X, so they instantly stop.

**Comment by TullyBurnalot** [comment]
No.

No.

No.

Those are kept Admin-Only for a reason.

**Comment by Rumiluntti** [comment]
Lol no

**Comment by Fox-McCloud** [comment]
>The point of notes is so admins know who does what and who to look out for, not so players know when the admins are onto them doing X, so they instantly stop.

**Comment by Chakirski** [comment]
Admins everywhere are cringing.

**Comment by fludd12** [comment]
It's not enabled by default, guys. It's an option.

**Comment by monster860** [comment]
It's not enabled by default! It's an *option*

**Comment by fludd12** [comment]
I'd say, at the least, more tools for our config menu can't hurt. If, in the future, policy changes on notes, this would be good to have.

**Comment by sasanek12** [comment]
Nope. Nein. Niet.

**Comment by Wheatley29** [comment]
Okay, that still changes nothing as it will still allow every player to see what the administration team thinks of their actions, by that note it would basically mean that EVERYONE with a single word on their notes would have it blocked, making it redundant

**Comment by Rumiluntti** [comment]
Useless option, that's as useful as adding "YOU CAN ALSO SHIT YOUR PANTS!!" -posters in your toilet.

**Comment by Wheatley29** [comment]
Controversial tag?

**Comment by FlattestGuitar** [comment]
I think this PR will have a very unanimous reception.

**Comment by TullyBurnalot** [comment]
@Wheatley29 This is not "controversial" so much as it is "universally reviled".

**Comment by FreeStylaLT** [comment]
I do not really see any reason to have this as an option, even. Since, this will never happen, if only because we have simply been noting people without ever intending to show them to any player. We cannot reasonably edit those notes before showing them to everyone, nor can we change our note methodology to fit the new public view it would have, this is simply infeasible.

**Comment by Chakirski** [comment]
I dare someone to give it a thumbs up.
:skull:

**Comment by FreeStylaLT** [comment]
AND TRAVIS FAILS.

**Comment by Wheatley29** [comment]
This PR was a shitstorm from the start

**Comment by Chakirski** [comment]
code/game/verbs/ooc.dm:238:error: see_own_notes: undefined proc
code/modules/admin/sql_notes.dm:181:error: show_note: duplicate definition
code/modules/admin/sql_notes.dm:114:error: show_note: previous definition
code/modules/admin/sql_notes.dm:199:warning: id: variable defined but not used
code/modules/admin/sql_notes.dm:203:warning: last_editor: variable defined but not used

**Comment by LittleBigKid2000** [comment]
Even if Paradise admins don't plan on showing players their notes, a downstream server's admins might want to. Downstream servers are the reason revolution was updated despite it not being in rotation, if I recall correctly.

**Comment by Wheatley29** [comment]
And even if it is an option, it will be used maximum once and then never again, thus wasting space and collecting dust

**Comment by Fox-McCloud** [comment]
>upvoting your own PR.

Shameful.

**Comment by monster860** [comment]
> upvoting your own PR.

> Shameful

But... But... REDDIT.

**Comment by Wheatley29** [comment]
@monster860, what in your opinion, is the point of adding this to the server?

**Comment by monster860** [comment]
There's no way for players to know if there's incorrect data in their notes right now. Like I said, I wouldn't be surprised if it said in my notes that I wrote the translator script, but I never wrote that script.

**Comment by monster860** [comment]
The fact that so many admins are against this makes me *really* worried about the contents of my notes.

**Comment by FreeStylaLT** [comment]
>The fact that so many admins are against this makes me really worried about the contents of my notes.

Perhaps that is for the better.

**Comment by Draconic-saint** [comment]
@monster860 This is not about you. This is apparently about your lack off insight into how we like to run this server.

Notes are a thing we as admins use to keep track of what transpires during rounds. They're not meant to be public. While perhaps a public system parallel to the notes might be implemented one day, that isn't what this PR does. This option won't ever be enabled. I don't see why the maintainers would have to put effort into reviewing this.

Sorry to say, your effort here was for nothing.

**Comment by monster860** [comment]
@Draconic-saint I noticed.

**Pull request closed without merging**
