### PR TITLE
Fix atmos meter, emag refactor, vending machine update, UI reworks, admin fax overhaul, other fixes

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Fixes atmos meter (de)construction (https://github.com/ParadiseSS13/Paradise/issues/306).
2) Fixes area names in the teleporter.
3) Adds the event MC cost to the status tab.
4) Overhauls the vending machine UI, and lets you pay with cash (https://github.com/Baystation12/Baystation12/pull/8112).
5) Fax machines now use NanoUI (http://i.imgur.com/GLEBPky.png).
6) Refactors emags to use emag_act() rather than attackby.
7) Overhauls admin faxing. Adds a new fax interface for admins (http://i.imgur.com/AKCzaU7.png), which allows admins to see all faxes that have been sent, reply to them, and also create a new fax which they can send to a specific (or all) department(s). Emagged fax machines can now contact the Syndicate. 
8) Minor R&D search fix: it should now remember the window you were on after searching.
9) Stops AI's from detaching IV drips.
10) Refactors handcuffs/legcuffs so they're a child of weapon/restraints, and gives secbots/ED-209/security cyborgs zipties, which can be broken out of in 45 seconds.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Very swanky fax interface

**Comment by Markolie** [comment]
Why thank you.

**Comment by Markolie** [comment]
Derp, misclicked.

**Comment by Fox-McCloud** [comment]
Looks great; so glad to be able to finally keep tabs on faxes--was always a pain getting nudged by another admin or having to nudge an admin "hey, I replied and said something completely different".

**Comment by FalseIncarnate** [comment]
simply being able to pull up past faxes alone is a life-saver.

it's embarrassing to get the inevitable PM from a player "hey, did you get my fax a few min ago?" and not be able to find it because attack logs from security beating the clown pushed it off of the chat log.

Being able to send faxes without replying to an existing one will also be nice for Event stuff.

**Comment by Fox-McCloud** [comment]
Oh, hahaha, you did the handcuff refactor--was going to implement zipties myself, but it looks like you beat me to it.

:+1:

**Comment by fj45** [comment]
Looks great, really like the vending machine UI.

**Comment by Markolie** [comment]
Mhm? I'm not sure why security would need zipties in their dispensers and boxes. In my opinion, they should only serve as a replacement for the unlimited handcuffs bots/cyborgs could provide (and to slightly nerf them), not to have them replace security's gear. They've been hit hard enough by nerfs lately.

**Pull request merged**
