### PR TITLE
Improves Construction Site

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
tweak: The Construction Site (partially finished space station east of eng outpost) has been revamped. With basic power/atmos networks in place, it should now be much more viable to repair it during a round.
/🆑

Changes:
- CS now has a bare minimum powernet, with enough APCs, wires, solars, etc to be powered - with a little fiddling.
- CS now has lights, so once power is up, you'll be able to see.
- CS now has a very basic atmos distro loop, so that with power (and some setup) you can actually pressurize at least the core of the site. Outlying areas... you will have to make your own pipenet to pressurize.
- CS now starts with some useful construction materials, such as a pipe dispenser, welding tanks, etc.
- CS areas have been changed. They are now more logical, with empty science rooms in the north, and half-built storage rooms in the south.
- Engineering outpost now has an airlock directly to space, so its possible to enter/exit the eng outpost from space without having to risk venting the place to do it.

CSite Engineering (requires a crate to get engine online, though solars are available):
csite_eng

CSite Atmos/Medical (once powered, can supply air and enable use of sleepers):
csite_atmos_med_storage_hallways

CSite central area (east side is easy to power/pressurize, west side less so):
csite_core_ai_primary

CSite north area (all can be powered, but the maint areas will require some work to be able to pressurize):
csite_north_bridge_sci_maint

Engineering outpost (note the added red airlock to allow entry/exit from space):
engoutpost_secondairlock

### CODE REVIEW

**Comment by DesolateG** [comment]
@Kyep  did you get rid of the walls in the doors? an example: the doors going to the sleepers

**Comment by Kyep** [comment]
@DesolateG Yeah, I just checked every door. You were right. Some of the old ones had walls under them. That is fixed now, too.

**Comment by DesolateG** [comment]
Sweet

**Comment by Kyep** [comment]
Added airlock to Eng Outpost, enabling entry/exit from space (and easier access to csite, without having to break a wall/window in the outpost and risk depressurizing it).

**Comment by tigercat2000** [comment]
LGTM, maybe this will actually help the construction site see some usage

**Comment by DesolateG** [comment]
@Kyep  Just noticed the shield pylons for the engine are across from each other rather than offset.

**Comment by Kyep** [comment]
@DesolateG the current design assumes you probably won't be putting up an engine there at all, because the solars are enough for power, and way, way easier to set up. If someone wants to do an engine setup there, they will already have to acquire a full engine crate, and do all that setup. I don't think its much to ask to move the pylons, given the other setup they will have to do to get the engine online.

**Comment by DesolateG** [comment]
You're going to get dummies trapped heh..

**Comment by Kyep** [comment]
You can't get trapped unless you online the field from inside it?

**Comment by Denthamos** [comment]
On the engineer outpost can a airlock cycler be added to the room with an air tank setup in the room above it?  This needs to be done with most airlocks to space due to the fastmos changes put in a while ago.

**Pull request merged**
