### PR TITLE
Updates Syringe Icons

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Adds a higher-quality icon to be used by syringes and DNA injectors, as well as a higher-quality draw/inject UI element. 
Fully compatible with colored reagents.

UI Elements:
draw  inject

Syringe Examples:
syringedemo

Icons are 100% the work of Goonstation.

_Because, really, our current syringe icons are pretty much ass..._

### CODE REVIEW

**Comment by MrBarrelrolll** [comment]
A little dark, makes them hard to see in the hand by just a bit.

**Comment by DaveTheHeadcrab** [comment]
I believe they're actually brighter than our current syringe icons -- They just have a bit more transparency.

**Comment by taukausanake** [comment]
I don't know how to feel. I agree that these look great but I don't want to replace the ones we have already

**Comment by MrBarrelrolll** [comment]
Idk man the ones we currently have do look pretty bland

**Comment by fludd12** [comment]
They're pretty!

**Comment by Gummin** [comment]
In the UI the back bit of the syringe is missing?

**Comment by DaveTheHeadcrab** [comment]
@TheDZD / @Fox-McCloud

**Comment by TheDZD** [comment]
I like these new icons better, although you're going to want to move them to the [goonstation folder](https://github.com/ParadiseSS13/Paradise/tree/master/icons/goonstation).

**Pull request merged**
