### PR TITLE
Cyberiad Christmas!

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Cyberiad got itself some Christmas cheer, snow and lots of gifts. And snow. Also trees. Almost every department got a little bit of something.

Bar:
img

Dorms:
img

Escape:
img

Brig:
img
img

Engineering:
img

Arrivals:
img

Also adds the missing nitrogen / plasma emergency tanks:
img
🆑 Santa Claus
add: Christmas cheer!
del: Grinch
fix: missing emergency nitrogen / plasma tanks
/🆑

### CODE REVIEW

**Comment by Ralta** [comment]
I love this! Woop woop, feeling Christmasy! ❤️ 

Just to be grinchy for a sec, shouldn't that medbay fix be in a separate PR? Or does it not really matter considering the nature of the fix? 🤔

**Comment by FreeStylaLT** [comment]
This'll get reverted after Christmas is over, where the fix can be bundled again, though this IS a bit impractical.

**Comment by Spartan6** [comment]
Can you at least fix the damn arrivals airlock while you’re at it, because this might make it break for the fifth time if that fix goes through.

**Comment by Aurorablade** [comment]
Lynch Atmos

**Comment by Fox-McCloud** [comment]
too many christmas trees; just the bar and the area in escape is enough, IMO.

All the snow is kinda an eyesore.

**Comment by KasparoVy** [comment]
The whole station should be snow. I request enough trees to qualify this place as arctic tundra station 13.

**Comment by Joseph-Case** [comment]
Just change the floor sprite to snow, problem solved

**Comment by FreeStylaLT** [comment]
Trimmed down the excessive snow in most areas. Pics updated.

As for the trees - I kind of want to keep them, since the intention here was to have the ~Christmas spirit~ be present no matter where you worked, at least somewhat. I also tried replacing the trees with snowmen, but that looked.. off.

Though, if you guys insist, I'll remove them.

**Comment by taukausanake** [comment]
What we really should have is a chemical reaction that makes snow like what carpet grenades do. Imagine real snow, not that dumb nitrogen frost that only atmos can do. Bonus if it also lowers the temperature of the affected areas a bit

**Comment by Spartan6** [comment]
>trims snow
>all of fucking escape is snow

**Comment by Vivalas** [comment]
There is a lot of snow and... cowboy hats. Interesting choice but it did just snow all over Texas so whatever, I can dig it.

**Comment by Jountax** [comment]
@taukausanake Love the idea of a reaction that makes snow. If it's one that requires a cold temperature to happen, then cryo grenades would also finally have a purpose. (Seriously, what are those even good for?)

**Comment by taukausanake** [comment]
@Jountax Cryo grenades are more like keeping a reaction from happening I thought. Think like cryo beaker, things don't react inside it. I _THINK_ that's how it works though. We don't have containers that affect temperature

**Comment by Crazylemon64** [comment]
ho ho ho

**Comment by taukausanake** [comment]
And here I was thinking this wasn't going to get merged until AFTER Christmas. :smile:

On the subject of seasonal maps, would it not be feasible to have an easier way to switch them out rather than waiting half the season for a PR to get merged? First thought would be separate maps but then maintaining them all would be awful. Maybe get these ready a month in advance along with a map freeze?

**Pull request merged**
