### PR TITLE
Borg sub-modules (WIP)

### PR DESCRIPTION
**Pull request by shazbot194**
Hello, so I would like to preface this PR with none of the balance aspects of this PR are set in stone, and I will be happy to change any of them. 

For this PR, I would like to try and cash in PRs #9932, #9465, and #9454.

So this PR add in the ability for a borg to select a sub module, which is a side grade for the current modules. These are almost always more specialised, and are meant to do one or two tasks better at the expense of other tasks. Currently, to select a sub module, you select a module, then it will offer you the option to select a sub module. In order to keep people from selecting something they don't want, I have impliment a system much like how sprite selection works, where you get 5 chances and give you a short description when you pick on. On the 5th chance, you get whichever mod you picked. 

Currently, I have the base for this feature in. This includes changing the way speed is handled slightly so it can be more reliably calculated. Made the ion thruster cost more modular, and several other small improvements.

Some features that will be or have been worked on.
- Structure for new sub-modules: **Done**
- Code to allow speed to be controlled by sub-modules: **Done**
- Code to allow Ion thruster energy cost to be determined by sub-modules: **Done**
- Code to allow health and armor to be controlled by sub-modules: **Heath is done**
- New Sub-modules
- Displaying which module and sub-module are active on a borg when examined
- Balancing sub modules
- Cleaning up my own mess of code

🆑 shazbot194 
Adds: in sub-modules for borgs to specialize in their department.
/🆑

### CODE REVIEW

**Comment by Birdtalon** [comment]
Just to explain my downvote -> I'm giving this a thumbs down as on the surface it goes against my beliefs in how borgs should be approached. But as it's a work in progress I'm open to changing my mind dependant on the final product and a more comprehensive explanation of the benefits and restrictions.

**Comment by Taaketa** [comment]
I'll reserve any judgement myself. Until there is some more about these sub modules.

**Comment by shazbot194** [comment]
@Birdtalon and @SamHPurp, the current idea is to have each sub-module be a side grade, or a specialist in a couple tasks. This means that they would forgo the benifits of being good at everything in a department to become really good at just a couple tasks. I think my ideas for medical can best show this. Currently, I plan on adding 4 sub-modules for medical; General MD, Surgeon, Nurse, and Paramedic. _Do keep in mind, none of these are final, but instead the general idea for what I want to do._
- The General MD is the current borg module, unchanged in function of equipment. Good at all of medical, but not great, and can be outperformed at any one task.
- The Surgeon only about surgery, gaining some very shiny tools such as an incision management system and augmented saw, but looses things like splints, nanopaste, robot analyser, chemistry stuff, and even some chemicals from their hypospray like charcoal.
- The Nurse is all about small damage, loosing all their surgical tools in favors of things like more chemicals, potentially a way to fix robotic limbs besides nanopaste, and some other things. But as stated above, it physically cannot do surgery.
- The Paramedic is a borg with even less equipment, lacking a lot of the tools to heal people, it really only has some things to keep people who are in Crit alive. But in return it’s a little faster then normal borgs and has a decreased ion thruster move cost. As with the nurse, it lacks tools to surgery, but also doesn’t have the majority of the means to heal, but is instead meant to rescue people and bring them back for the rest of medbay to help.

**Comment by davidchan13** [comment]
Taking nanopaste from the surgery bot? Isn't it only there so borgs could repair mechanical organs?

**Comment by tigercat2000** [comment]
The maintainers believe that this is a strong step in the wrong direction for borgs and do not believe this PR's goal is suitable even if the submodules are "balanced" appropriately. On top of this, there is concern that this will lead to encouraging overpowered designs that are balanced by "well they only have x and y though".

Additionally, this makes it even more of a pain in the ass for players to decide what cyborg type they're going to play as, and get yelled at no matter what choice they make because they're "specialized" in something that ends up not mattering for that given round. 

As such, this is being closed.

**Pull request closed without merging**
