### PR TITLE
Bear resprites, sprite from SS14 by Alekshhh applied for all instances

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Resprites Bear pelts, Space bears, Brown bears, and Pelt hats

## Why It's Good For The Game

Looks incredible in comparison to soul

## Images of changes

image
image
image
image
image
image
image
image

## Testing

Refer to images
image

## Changelog
:cl: Alekshhh
imageadd: Resprites bears, bear pelts, and bear pelt hat icons for all instances with Alekshhh SS14 sprites.
/:cl:

### CODE REVIEW

**Comment by ATP-Engineer** [comment]
Made sure polar bear pelt icon wasnt left behind, only forgot it because it was nowhere to be found in mob/clothing/heads, and instead is located in customitems (WTF)
image

**Comment by Henri215** [comment]
Brownbear_gib is now the same as bear_gib?

**Review by Henri215 — CHANGES_REQUESTED** [review]
image

image

You will have to create a vox version for it too, it currently has the old bear pelt on vox specific hats.dmi file. 
The polar one also goes invisible on vox, which is expected considering its a fluff item, no need for you to do anything about that one.

**Comment by ATP-Engineer** [comment]
Weird, checked a few species specifics and they didnt seem to have the pelt, guess I missed vox.

**Comment by Henri215** [comment]
You didnt add it inside "vox/head.dmi", instead adding a "vox/voxpelt head" into the files thus causing the error

**Comment by ATP-Engineer** [comment]
Russians accounted for, and Vox version fixed so its not covering their face on the sides.
image

**Review by Henri215 — APPROVED** [review]
Lewcs Good To Me

**Comment by Fluffyzack21** [comment]
will this effect the other species like, IPC, vulps, greys, unaiths, tajaran, slime people and the other's besides a vox?

**Comment by Henri215** [comment]
> will this effect the other species like, IPC, vulps, greys, unaiths, tajaran, slime people and the other's besides a vox?

affect*
And no, it only had a custom version for vox, not the other species.

**Comment by ATP-Engineer** [comment]
Attempt at resolving merge conflict #2

**Review by S34NW — APPROVED** [review]

**Pull request merged**
