### PR TITLE
Replaces all Cyberiad's windows with full-tile windows

### PR DESCRIPTION
**Pull request by FreeStylaLT**
img
img
img
img

Replaces the windows with full-tile ones that have more functionality (damage overlays, repairability(?))
**Changelog:**
:cl:FreeStylaLT
tweak:Replaced Cyberiad's windows with full-tile windows.
/:cl:

### CODE REVIEW

**Comment by datlo** [comment]
You need to update RCD to create grille + fulltile windows instead of the old ones if this is going to be the new standard.

On the actual windows... I'm not sure. I'd have to see how it plays with mb a testmerge to see how this goes.

**Comment by Pixelzilla** [comment]
> 
> 
> You need to update RCD to create grille + fulltile windows instead of the old ones if this is going to be the new standard.
> 
> On the actual windows... I'm not sure. I'd have to see how it plays with mb a testmerge to see how this goes.

I'd suggest adding an additional RCD option with fullsize window instead of outright replacing the other ones. I personally think the other ones look nicer and would hate to lose the ability to make those style windows with the RCD.

**Comment by KasparoVy** [comment]
How's this stack up durability wise vs two separate directional pane rwindows with the grille in the mid
Are we only able to place full windows over grilles by creating the grille and the window on our tile without moving that whole time?

**Comment by Spartan6** [comment]
@KasparoVy 
1. The full tile window has the health of two one directional windows.
2. Yes.

**Comment by Superhats** [comment]
It looks super blocky, compared to our smooth dual windows. I don't like it, personally.

**Comment by TDSSS** [comment]
Does this kind of window still shock people trying to break through? That was a huge security factor in the 4 windows + grille setup. If that's removed, that makes break-ins a LOT easier.

**Comment by Spartan6** [comment]
@TDSSS After smashing the window, the grille is still underneath, so it would need need to be broken and would still shock you, yes.

**Comment by KasparoVy** [comment]
Thanks for the response @Spartan6
Pretty much addresses all my concerns. Still a bit of a nerf due to the nature of having one 'target' rather than two separate objects to sustain damage but *shrug*
I don't mind the appearance either way. The overlays is a good enough argument for me.

**Comment by AffectedArc07** [comment]
Me likey

**Comment by Spacemanspark** [comment]
Not really a fan of the look honestly.

**Comment by Mitchs98** [comment]
Not a fan of it either. Full windows in some places look good but overall nah. Sure the windows are stronger and it'd make places harder to bust into a bit, but still. Overall aesthetic looks better with directional windows. Now, they could do well for areas facing space perhaps? It'd make sense from an IC perspective to have the more 'durable' windows in such areas.

**Comment by Spartan6** [comment]
I think it’s just because it appears different initially. A good, prolonged test and people getting used to the look would sort that out.

**Comment by Spacemanspark** [comment]
I mean, I used to play solely on stations that had the single pane glass windows.

I can honestly say I prefer the look we currently have.

**Comment by Fox-McCloud** [comment]
I strongly support this, but only if you really go with TG's window sprites.

Our current full tile window sprites are pretty icky; these look eh (but would suffice in the interim).

Fulltiles windows resolve a number of design and balance problems, and when they're switched over to the new sprites, they'll look pretty great.

👍

**Comment by Citinited** [comment]
Will deltastation and metastation also be updated with these?

**Comment by Spartan6** [comment]
@Citinited I suppose testing them first on Cyberiad would be best.

**Comment by Allfd** [comment]
An issue, it is no longer possible with this design to make glass airlocks,  So prepare to be fastmossed!

I suppose I am fine with that.

**Pull request closed without merging**
