### PR TITLE
Adds engine containment grid to Metastation

### PR DESCRIPTION
**Pull request by SamHPurp**
This spurred some debate previously as I had classified it as a fix. This is now classified as a Feature add, and its own separate PR.

Without this separate grid, a single power sink on the station anywhere would release the Engine.

Without this separate grid, the Grid Check event would release the Engine.

Without this separate grid, you would need to make SMES alterations or cold start with a PACMAN to get containment up and running.

**This standardizes with Boxstation, nothing we aren't already entirely familiar and used to.**

Before:
image

After:
image

:cl: Purpose2
add: MetaStation: Standardizes the engine containment with Boxstation's engine containment.
/ :cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
I am not _super_ against this, but I think that a better solution would be wiring the emitters to the mains, but including a very convenient half-built SMES unit just waiting for parts, so that it isn't completely cheapened.

**Comment by SamHPurp** [comment]
@tigercat2000 added the photos.

With how frequent people messing up containment and releasing the engine in the first 10 minutes lately, I'm really against having the setups be different between the stations.

Engineers have quite a lot to do already at round-start, adding all this extra bits just to stop everyone dying is also kinda a big deal.

How about running a bunch of Metastation tests today/tomorrow. (would be great if someone would ping me on Discord when they happen so I can come observe)... so you can see exactly all the problems I'm outlining.

Alternatively, merge it, then run all the tests ;)

**Comment by Anticept** [comment]
There is one more problem that is not being mentioned that I did before:

Powernet priority.

Due to the way that paradise powernets work, the items that have highest power priority are those that are closest to origin, 0,0. Engineering is almost the last place in that list in metastation.

When you turn on the emitters, pay attention to them. The top set barely fires at all.

We've got a lot of problems with powernet and metastation compatibility. I still stand by the fact we're going to end up *needing* boxatation's containment grid.

**Comment by SamHPurp** [comment]
@Anticept Aye, this is what I was eluding to with:

> Without this separate grid, you would need to make SMES alterations or cold start with a PACMAN to get containment up and running.

This is due to exactly that power-grid origin problem.

**Comment by Anticept** [comment]
"Alluding", but I see that now. Still, you hinted at the horse, I continued beating it after it died.

**Comment by Aurorablade** [comment]
I still do not think it needs a containment grid.

**Comment by SamHPurp** [comment]
@Aurorablade 
image

Please expand. Why do you feel this way? I'm legitimately asking because I cannot for the life of me understand the reasons against this.

**Comment by taukausanake** [comment]
I think we should use the PACMAN to cold boot the engine. The SMES Tiger mentioned could be hooked up to main but fed to the emitters. However I'm not an engineer, at least not much of one, and experimentation in this area seems to be avoided due to the fact people don't like dying like you'd imagine spessmen in spess would.
I need to learn the magic that is powernets eventually

**Comment by Anticept** [comment]
@taukausanake basically, they want the emitters to be fed only by the station grid, which unupgraded SMES are limited to 200,000 watts each, the three of them collectively provide 600,000 watts.

Power sinks will consume up to 2.4 million watts, and purposely force itself to be fed first, which starves the emitters and the engine will release. However, if emitters are fed on the engine grid side, the SMES will prevent the power sink from starving the emitters, and containment will stay up.

In addition, engineering is located on the west side, while the origin point is in the lower left of the map. As a result of this, engineering is a lower priority for power. Unless you turn up the SMES, the emitters in at the top of containment aren't being fed hardly any power at all.

Finally, a grid check event will cause the SMES to go offline, automatically starving the emitters, and releasing the engine.

On box station, the emitters are hooked into the engine grid, with a backup smes hooked in a loop (east side of engineering). Even during a grid check, the engine still directly feeds the emitters, so it doesn't release the engine. And, since the emitters sit on the engine and not the station grid, a power sink doesn't cause containment failure either.

**Comment by taukausanake** [comment]
@Anticept Thank you for verifying the few things I thought I knew and explaining everything I didn't know. I properly understand and see the fixes/features that Sam is applying

**Comment by SamHPurp** [comment]
Doing MetaStation tests currently. Round 3 is going now, so can't say anything about Round 3... HOWEVER...

Round 1: the CE and three engineers failed repeatedly to get the Engine containment working, due to the Origin issue. By minute 45 and the station in the dark, he gave in his ID at the HoPs telling him he quit.

Round 2: More failure. Minute 15, I got bussed in as an emergency engine tech to get it off the ground. It went fine after then.

**Comment by Anticept** [comment]
I joined for round 2 as captain at the 25 minute mark, and round 3 as the CE.

I was told what happened in round 1 and the start of round 2.

On round 3, I went looking for an SMES board in tech storage, I wanted to have one set up as a backup and cut the engine grid from the rest of the station. There wasn't one in tech storage, so I had the solars directly wired near the grav gen into the main grid as a way to be sure to kickstart the engine containment, and deconstructed and took the components from the SMES.

Our powernet has more bugs that metastation has revealed. Wire crossings that aren't connected are still exchanging power. Curved wires on the same tile (west to south, and north to east) are also passing power, despite not touching. I had demonstrated the problem to observers.

The way it is wired in today's test, it shouldn't have even have been possible to fire the PA either (it's wired to power collectors, but not station output). As said, powernet bugs passed power across connections that didn't technically exist.

I very much advocate that we *need* a boxtation engine containment. Our powernet systems are designed around it.

I do, however, love the idea of cold starting, and I would be quite happy with a partially constructed SMES and parts nearby to finish it, as well as the node ready to receive the PACMAN. But... I'm not only an experienced and dedicated SS13 engineer, but I also have real life experience in power distribution systems, for however that much matters. Most aren't.

We're dealing with a lot of casual players. Such a critical system really should be consistent for startup. The more advanced techniques that require deeper understanding of the grid should be left where it wouldn't cause a round end from a simple mistake during dabbling.

**Comment by Twinmold93** [comment]
Fethus, without the grid, we'd have to once again disable the Grid Check event, which means disabling it for Cyberiad, too. On top of that is inclusion of having, not only a new map and layout to know, but also systems that look the same but are drastically different, and having people have to remember they are different and work accordingly is too much to ask because we cannot reasonable ask them to remember everything about Meta when they either don't know Cyberiad yet or only know Cyberiad. Especially as Cyberiad is our main station.

**Comment by SamHPurp** [comment]
@Fox-McCloud @tigercat2000 If this concept is approved - I'll include this change onto #7435, and close this one which is already overhauling Brig/Medical.

**Comment by tigercat2000** [comment]
This has been approved (finally); feel free to include the change onto MetaStation 2.0 (#7435).

**Comment by SamHPurp** [comment]
This has been added onto the other PR. Thanks dudes.

**Pull request closed without merging**
