### PR TITLE
Old Humanoid Cyborg skin resprites

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Updates a lot of the old cyborg sprites, removes all/most of their headwear items to allow anyone who uses them to use any custom hats without clipping.

## Why It's Good For The Game

Consistency (namely the hazard vests/suits)

## Images of changes

Before
image
After
image

## Testing

It just works.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
imageadd: Resprites most of the old cyborg skin clothing, removes their permanent headwear to allow better use of the hat update. Bro Bot is now literally me.
/:cl:

### CODE REVIEW

**Comment by Fordoxia** [comment]
A lot of these are great (and much-needed) drip upgrades.

Is there actually any difference between `Miner_old` and `Miner+j_old`? They look the same to me both before and after.

Engi, Jani, and Mining all sharing the same hazard vest makes them less visually distinct from each other than before, can this be helped?

**Comment by ATP-Engineer** [comment]
A lot of the distinctions between these three came from hats. Which of course, cyborgs can choose for themselves now. The Miner+j has a jetpack on its side/back sprites.

**Comment by Cress67** [comment]
The loss of the pink shirt on the Brobot will be wept over for generations.

**Comment by ATP-Engineer** [comment]
> The loss of the pink shirt on the Brobot will be wept over for generations.

WYCI, and WISI. We can have another.

**Review by Burzah — APPROVED** [review]

**Pull request merged**
