### PR TITLE
Robot Talk Looks Cooler

### PR DESCRIPTION
**Pull request by uraniummeltdown**
robottalk

from ti ji

:cl:
tweak: Speaking in Robot Talk is easier to see
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
Did you just 1up your own post? 🤔

**Comment by MarcellusPye** [comment]
Hurray for memes!

**Comment by taukausanake** [comment]
I don't know, I kind of like this. It feels out of place but I think so long as it stays only to silicons it might actually be okay. I'd combine it with #8425 personally because I like both of them

**Comment by Ty-Omaha** [comment]
This is **really** intrusive, not a fan.
Even asay doesn't get it's own highlighted line.

**Comment by uraniummeltdown** [comment]
That's because nobody bothered to change it, asay COULD get it's own background color if someone made a PR for it

**Comment by Crazylemon64** [comment]
yikes, changing the background class like this looks really out of place

**Comment by Ty-Omaha** [comment]
Having certain lines with background color whereas every other line does not have background color is still, really off putting and intrusive to everything else. 
I don't want asay to have it's own highlighted line. As Crazy said; it looks out of place. Which it is.

**Comment by Vivalas** [comment]
I like it. I say give it a chance, or else give it a pref.

**Comment by Birdtalon** [comment]
Being frank it looks gross.

**Comment by GunDOSMk1** [comment]
Really don't like this I'm afraid. SUPER out of place :/

**Comment by Crazylemon64** [comment]
After discussing with heads

**Comment by Crazylemon64** [comment]
While we appreciate the desire to make Robot Speech more noticeable, this makes the textbox look like an early Windows command console, and it entirely out of place with every other font/colour combination used in-game.

**Pull request closed without merging**
