### PR TITLE
Fixes Misaligned Areas on Cyberiad

### PR DESCRIPTION
**Pull request by Norgad**
2016-12-21 02_20_55-greenshot
2016-12-21 02_26_16-greenshot

Those are only the **major** issues, there's lots of one-tile mistakes

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I smell fastDMM, which we've rejected, in the past, unless it was map-merged.

**Comment by monster860** [comment]
Why do you have such a big problem with FastDMM?

**Comment by CrAzYPiLoT-SS13** [comment]
I too, don't understand why you reject a greatly superior? You haven't provided any real reason the numerous times you were asked about it. 

I smell some grudges from the past affecting your judgement.

**Comment by monster860** [comment]
In fact, I'm going to compare the compile times of this codebase on a map WITH randomized keys and WITHOUT randomized keys (as it is right now)

**Comment by monster860** [comment]
@Fox-McCloud I have done some testing. For compiles with Cyberiads map as it is now, it takes 318.0 s. If I apply FastDMM to it and randomize all the keys on all 7 z-levels, the resulting compile time is 324.1 s on average, which is only 6 seconds slower.

**Comment by tigercat2000** [comment]
@monster860 Your randomized-keys method is incompatible with our default map-merging tools, which some people do still use. If we allow people to use randomized keys on their map edits, eventually when someone uses the default map editor and map-merges it, it's going to make a huge diff because it'll clear all of your custom keys and rewrite them in order.

Thanks, but, we're not going to limit our codebase to requiring fastDMM for map edits.

**Comment by monster860** [comment]
@tigercat2000 That's not how mapmerge works. The point of mapmerge is to *not* rewrite the keys, so if a key isn't changed it doesn't change it's ID. I made a simple map change on a fast-dmm-ified version of Paradise and I ended up with 28 additions and 25 deletions when using DM and mapmerge.

**Comment by Norgad** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE, merge conflicts. I'll fix it later, once the other mapping PRs are through

**Pull request closed without merging**
