### PR TITLE
Kingston go

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

This PR nukes Kingston and Advanced Kingston diseases from the code

## Why It's Good For The Game

This is grief virus that turns you into Tajaran or other species, making returning to normal state impossible or VERY hard.
This virus can be rolled in disease outbreak event, making it possible to be in any round.
This virus doesnt kill, it just griefs and make people suicide/exit round because turning your character back is (nearly) impossible.
This virus was added 6 years back in the age of stable mutagen and other things that probably supposed to help you bringing back your character but now they are gone. This virus should follow their way.

This actually is not a big issue due to roll chance, you need to roll disease outbreak even and roll Kingstons over (mostly) all other diseases which is very low chance.

Why do i delete the code instead of blacklisting it? Well if the code is not used, it probably shouldnt be there. If thats necessary, i can change PR to just blacklist it from the event.

## Testing

Compiled, spawned disease outbrake event

## Changelog
:cl:
del: Kingstons Syndrome and Advanced Kingstons Syndrome diseases.
/:cl:

### CODE REVIEW

**Comment by CinnamonSnowball** [comment]
While I sympathize with the notion that not all players enjoy having their character permanently modified by a virus, I think adjusting how hard it is to cure or how fast it progresses would be a better solution to axing it entirely

**Comment by Danchi299** [comment]
I saw this notification while still playing the round with outbreak of this virus
what the hell?

**Comment by Mitchs98** [comment]
Not wholly relevant but I feel it worth mentioning that Stable Mutagen or other easy ways of returning to your character's previous appearance/not a vulp did not exist when Kingston's was originally added.

**Comment by Coolrune206** [comment]
I Taj pls nerf

**Comment by matttheficus** [comment]
Any competent CMO should be able to prevent Kingstons rather quickly.

Maximum I Ded Plz Nerf.

**Comment by AffectedArc07** [comment]
> I saw this notification while still playing the round with outbreak of this virus
> what the hell? 

That makes this an ided PR

**Comment by A-Medster** [comment]
Genuinely, i havent had much of an issue with Kingstons. Main qualm with it is the hard stun it puts you in while you cough up a hairball.
It breaks flow and feels a little out of the blue for a race thats (at least we want to be) more tham just a Cat but Humanoid
I do really like the concept of viruses that change a persons race, makes you think about what your character would do in that situation, and/or forces you into learning how a diffrent race plays
The virus is rare as is, and the only one of its kind (pretty sure the last time i saw something like this with Moth Cough, it was an admin event). Might be a good idea to look into adding a counter virus that can be made in Virology that can return people to the race that they started the round as.

**Comment by farie82** [comment]
The teams have voted against this PR being merged with the following reasons given:
- It can be interesting to roleplay the effects of your species being changed. Unlike stable mutagen / transformation sting it's not someone fucking with you on purpose, it is not turning you into a fat david flufferton, it *only* changes your species, and can be cured before transfomation. If you can't roll with your species being changed, and want to suicide, that is on you. And if it is rare and not a big issue as you said, why remove it?
- If the sole reason for making this PR is simply cause it causes people to suicide then that's not good enough, paradise is not a hugbox server as much as some people would call it such. it's curable before it changes someone's species and in a lot of cases your species can be changed back to something similar to what it was before the disease. There's plenty of time to get your disease cured if caught in time just like any other disease

Due to these reasons I don't think it'll be possible to change the PR to make it pass without completely redoing it another way.

**Pull request closed without merging**
