### PR TITLE
Fixes #8508, the Needless Shedding of Blood

### LINKED ISSUE #8508: Blood splatters stack way too much on a single tile
**Problem Description**:
Blood effects that are created when a person gets hit can stack onto a tile forever
Even trying to alt click to avoid game freezes can yield a huge huge list

**What did you expect to happen**: 
For blood to be limited, maybe to two or three times
I don't think this happened before pull request #7848 
**What happened instead**:
There was enough blood to fill a pool on a single tile

**Why is this bad/What are the consequences:**
Makes it difficult to locate items on tiles that are affected by this. 

**Steps to reproduce the problem**:
1. blob with a bunch of factories
2. get hit by multiple blobs at the same time

Or just hit yourself a bunch. More testing may be required.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I believe this mostly concerns melee attacks
I was getting hit by multiple blob attacks rapidly the first time I saw this happen
The second time a prisoner appeared to have been beaten either by themselves or by an officer
screenshot_548
screenshot_547

### PR DESCRIPTION
**Pull request by KasparoVy**
Fixes #8508 

:cl:
fix: Avoids wanton bloodshed by revising logic that checks for blood already in the splat zone.
rscadd: Adds a helper proc with which you can get a list of all atoms of a type at a given location.
/:cl:

_After MANY shots fired..._
bloodsplatta

### CODE REVIEW

**Comment by Aurorablade** [comment]
ohhhhhhhh...also get_atoms_of_type_here seems a bit long, may need to shorten it.

get_atoms_in_loc myabe

**Comment by KasparoVy** [comment]
I was drawing a total blank on a proper name. I wanted to indicate that it fetched all atoms of a given type.

Perhaps I can just leave '_here' off.

**Comment by SamHPurp** [comment]
Travis is totally choking on this, might be worth reopening

**Comment by KasparoVy** [comment]
Looks like Travis finally made it through. Wasn't expecting that!

**Comment by SamHPurp** [comment]
` Ran for 18 hrs 52 min 21 sec`

God damn

**Comment by KasparoVy** [comment]
Travis working overtime, my man

**Comment by Ralta** [comment]
Sweet, no more right-clicking to find an item in amongst 50 blood spatters and waiting 30 seconds for the game to stop freaking out :tada:

**Pull request merged**
