### PR TITLE
Makes all arrival shuttles indestructible.

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Replaces all walls, floors and windows of every arrivals shuttle with their indestructible variants.
Also adds some missing tiny fans to the Meta shuttle.

## Why It's Good For The Game
When meteors hit the shuttle, it can sometimes just absolutely wreck it, causing a lot of work for admins to rebuild it, and add atmos to it again. This will solve all those issues.

## Images of changes
I'm opening this PR so  I can use mapdiffbot to see  what I missed - Keeping this section here even though there shouldn't be any visual changes.

## Testing
Went into a testserver, blew up a lot of shuttles with meteors.

## Changelog
:cl:
tweak: The Meta arrivals shuttle now has tiny fans
tweak: All arrivals shuttles are now indestructible.
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
nice merge conflict

**Comment by DGamerL** [comment]
> nice merge conflict

:(

**Comment by githubuser4141** [comment]
Are the tiny fans indestructible? Otherwise explosions or focused melee attacks can probably break them, unless they are by default.

**Comment by DGamerL** [comment]
> Are the tiny fans indestructible? Otherwise explosions or focused melee attacks can probably break them, unless they are by default.

I made them the invisible variant, which are indestructible

**Comment by DGamerL** [comment]
I'm surprised that this only happened after these last two commits, I'll investigate it more tomorrow

**Comment by Denthamos** [comment]
Would honestly prefer if the arrivals shuttle would only arrive when there IS a new arrival and would leave after the person gets off said shuttle. While I am not a fan of porting everything from TG, it is a very nice feature and would prefer that instead of just making the arrival shuttle magically invulnerable.

**Comment by DGamerL** [comment]
Closing for 2 reasons:
1. The design team has said that they prefer to have the shuttle move out during meteor storms and such, which I do agree with
2. The turfs being active before init error is making me go insane because I'm not able to fix it well

**Pull request closed without merging**
