### PR TITLE
Updates On Fire Sprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the human on-fire sprites to what TG uses.

img

It's a LOT easier to see than our current sprite; maybe people wont' be halfway dead by the time they realize they're on fire, now.

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
:fire: :+1:

**Comment by Regen1** [comment]
:fire: :100:  tbh fam

**Comment by Aurorablade** [comment]
given what i know about some peopel IRL you are still gonna have people standing there on fire going...duuhhhh why hot...but otherwise good change...

**Comment by tigercat2000** [comment]
AHELP: Question: XXNoobSlayerxx: "why am am me flameses?"

**Comment by DaveTheHeadcrab** [comment]
Reminds me of my mixtape.

**Comment by Fox-McCloud** [comment]
>Reminds me of my mixtape.

The car literally melts.

**Comment by KasparoVy** [comment]
And it burns, burns, burns

The ring of fiiiireeee

**Comment by NTSAM** [comment]
Things are starting to *heat up* in this place.

This is most certainly a *hot* topic.

I can almost sense a *flame* war coming to light.

**Comment by Spacemanspark** [comment]
Dammit, now I'm all *fired* up.

**Comment by TheDZD** [comment]
Damn, and I thought the ice puns were bad.

**Comment by Spacemanspark** [comment]
We kinda burned up the ice puns.

**Pull request merged**
