### PR TITLE
More Gore from Gibbing

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Makes Gibbing way more gorey

- Gibbing will now throw out your organs *everywhere*
 - Brain, Lungs, Liver, Kidneys, Eyes, and Appendix all go flying
- Can pick up organs and eat them (be on harm intent then click on the organ itself)

gibbing

### CODE REVIEW

**Comment by tigercat2000** [comment]
This is somehow horrible and absolutely fucking great at the same time. :point_right:

**Comment by Midaychi** [comment]
Do you really want to make gibbing demonkied monkeys a viable source of quick organs though?

**Comment by Spacemanspark** [comment]
Can we also get Hippie's thingy where you hit someone and blood spurts out one tile away from the victim?
Outside the scope of this PR, I know, but it would be a neat idea...

**Comment by veganzombeh** [comment]
Do the limbs go flying too, or just the organs? It actually looks a bit odd that the legs *haven't* moved in that gif.

**Comment by Fox-McCloud** [comment]
@veganzombeh 

Runtimes, sadly =p

**Comment by veganzombeh** [comment]
Haha, that's organ code for you.

**Pull request merged**
