### PR TITLE
Remaps CC

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This Pr transforms CC into a new layout based on TGs CC.
It also tidies up the CC Z-level by:

- Consolidates both Thunderdomes into one
- Removes the escape ship that shuttles dock with at the end of the round
- Adds more space between abductor ships
- Rearranges things on Z1 to make more sense.

The PR also touches supply shuttle code slightly, making supply shuttles only sell their contents on ARRIVING at CC, this means supply shuttles can be loaded with stuff at CC that will then get sent back to the station without being deleted.

## Why It's Good For The Game
Currently, CC is a shell of a location. While its potential uses are limited, the current layout means it's hard to RP or do much of anything there. This new layout expands on the bar, and makes the station more realistic in terms of facilities.

The ERT section of the station now has some character and life to it.
Thunderdome is part of CC and can be accessed from it.
There is an expanded supply area connected to the supply shuttle.
The "admin prison" (who uses this even?) Is now a proper small prison facility.

Escape pods dock at Trurl now, there is no escape from the hell that is end round deathmatch.

Since atmos isn't a problem on the CC Z-level, the extra space added does not matter in terms of performance.

### See MDB for full z-level changes
ccsnew

## Changelog
:cl:
tweak: Remapped CC
/:cl:

### CODE REVIEW

**Comment by Pyrodes** [comment]
The fact that CC has autorifles in their armory makes me fear for their budget, maybe replace it with saber SMGs? but overall this is pretty cool!

**Comment by AffectedArc07** [comment]
```
loading map_files/generic/centcomm.dmm
_maps/map_files/generic/centcomm.dmm:1094:error: invalid variable name: syndie
_maps/map_files/generic/centcomm.dmm:1333:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:4798:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:4865:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:5819:error: invalid variable name: syndie
_maps/map_files/generic/centcomm.dmm:6165:error: invalid variable name: syndie
_maps/map_files/generic/centcomm.dmm:7847:error: invalid variable name: syndie
_maps/map_files/generic/centcomm.dmm:8137:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:10303:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:11262:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:12512:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:13390:error: invalid variable name: syndie
_maps/map_files/generic/centcomm.dmm:13554:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:13671:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:14197:error: invalid variable name: id
_maps/map_files/generic/centcomm.dmm:15011:error: invalid variable name: id
```

You tested this and made sure the shuttles and everything ingame works right?


Right?

**Comment by S34NW** [comment]
> 
> 
> ```
> loading map_files/generic/centcomm.dmm
> _maps/map_files/generic/centcomm.dmm:1094:error: invalid variable name: syndie
> _maps/map_files/generic/centcomm.dmm:1333:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:4798:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:4865:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:5819:error: invalid variable name: syndie
> _maps/map_files/generic/centcomm.dmm:6165:error: invalid variable name: syndie
> _maps/map_files/generic/centcomm.dmm:7847:error: invalid variable name: syndie
> _maps/map_files/generic/centcomm.dmm:8137:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:10303:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:11262:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:12512:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:13390:error: invalid variable name: syndie
> _maps/map_files/generic/centcomm.dmm:13554:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:13671:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:14197:error: invalid variable name: id
> _maps/map_files/generic/centcomm.dmm:15011:error: invalid variable name: id
> ```
> 
> You tested this and made sure the shuttles and everything ingame works right?
> 
> Right?

Yes, those vars were nulled but not fully removed so CI was no likely. Fixed.

This works fine upon testing, will need a bit of a thorough test though.

**Comment by SagaStars** [comment]
image
These are NPCs? :eyes:

**Comment by Carthusia** [comment]
Even though I probably wont ever see this new areas, the fact they exist at all is good to have for those who can/will just due to their potential.

I LOVE the fact that the NT supreme court has an actual room where you could put people on trial at and various other RP zones here.

Very nice

**Comment by S34NW** [comment]
> 
> 
> image
> These are NPCs? 👀

Cardboard cutouts :P

**Comment by LightFire53** [comment]
Moving the BSA away so no one can actually get to it in time: top skrek

Also, does this mean ERT spawn directly in the briefing room now?

**Comment by Denthamos** [comment]
Does this mean we at CC can finally put things onto the cargo shuttle while it is there and it will not delete said things before it arrives on station to replace itself with what the station has ordered?

**Comment by S34NW** [comment]
> 
> Also, does this mean ERT spawn directly in the briefing room now?

They do indeed

> 
> 
> Does this mean we at CC can finally put things onto the cargo shuttle while it is there and it will not delete said things before it arrives on station to replace itself with what the station has ordered?

You totally can now. No longer is it just in a walled-off box.

**Comment by Marginalorb** [comment]
[Yes, YES!](https://www.youtube.com/watch?v=P3ALwKeSEYs)

**Comment by Shadeykins** [comment]
I'm not sure about moving the escape pods. Usually the "escape shuttle" is nice and quiet and allows for a moments respite/some level of roleplay and interaction. I would sorely miss it, personally.

As one of the only admins who bothers w/ thunderdome, I'm not sure about putting it on CC.

Usually it's used for ridiculous deathmatches. Sometimes megafauna is spawned inside it. Sometimes there are explosions. It would be a lot safer to leave it isolated.

Admin prison, when used, is generally used as a 'safe spot' to equip/fix antagonist things. That said, the test area satisfies this function as well (assuming it's not blown up).

**Comment by S34NW** [comment]
> As one of the only admins who bothers w/ thunderdome, I'm not sure about putting it on CC.
> 
> Usually it's used for ridiculous deathmatches. Sometimes megafauna is spawned inside it. Sometimes there are explosions. It would be a lot safer to leave it isolated.

It is still made of totally indestructible walls and windows (the "windows" that surround it arent even windows, they are just transparent indestructible walls with a window texture slapped on them), so anything hosted within won't affect CC itself in any way. It's just a good way of consolidating the 2 different thunderdome areas on the map.

> 
> Admin prison, when used, is generally used as a 'safe spot' to equip/fix antagonist things. That said, the test area satisfies this function as well (assuming it's not blown up).

Admin prison should still be useable for that purpose, the cells are isolated and it is tucked away from the rest of the commonly used CC areas.

>
> Usually the "escape shuttle" is nice and quiet and allows for a moments respite/some level of roleplay and interaction.

That's what the bar is for... I do suppose you have to run the gauntlet of death to get to it though.

**Comment by Spacemanspark** [comment]
Indestructible flooring would be nice to have in the thunderdome.

**Comment by S34NW** [comment]
> 
> 
> Indestructible flooring would be nice to have in the thunderdome.

Good idea, ill get on it

**Comment by Exavere** [comment]
Home away from Home comes to Home, very nice.

**Comment by Denthamos** [comment]
> > Does this mean we at CC can finally put things onto the cargo shuttle while it is there and it will not delete said things before it arrives on station to replace itself with what the station has ordered?
> 
> You totally can now. No longer is it just in a walled-off box.

Not what I meant with that.  Items you put on the shuttle would **delete** themselves before they arrived at the station when I last attempted to manually put items on it for an event.  I mean, is that still going to happen?

**Comment by S34NW** [comment]
> 
> 
> > > Does this mean we at CC can finally put things onto the cargo shuttle while it is there and it will not delete said things before it arrives on station to replace itself with what the station has ordered?
> > 
> > 
> > You totally can now. No longer is it just in a walled-off box.
> 
> Not what I meant with that. Items you put on the shuttle would **delete** themselves before they arrived at the station when I last attempted to manually put items on it for an event. I mean, is that still going to happen?

It is not going to happen no, this was done because no checks were made for when the cargo shuttle should try and buy/sell.
Now it only sells when arriving back at CC, and only buys when landing at station.

**Comment by TheYeetster1** [comment]
Has the camera issue been fixed with the thunder dome? Some camera viewers only let you see the red side of the team storage area, and the middle while not letting you see green's side.

**Comment by S34NW** [comment]
> 
> 
> Has the camera issue been fixed with the thunder dome? Some camera viewers only let you see the red side of the team storage area, and the middle while not letting you see green's side.

I was not aware of the issue, I'll do my best to remember that I need to have a look.

**Review by Kyep — APPROVED** [review]

**Comment by S34NW** [comment]
After some feedback from Fox, I've removed most of the additional RP areas to discourage CC roleplay.
Round-end dock areas have remained the same, as has the ERT area. These are what most needed life.
Thunderdome is less bloated, but still connected to CC.
Security and supply areas majorly reduced, court removed.
3 med/sec/customs checkpoints removed.

**Comment by AffectedArc07** [comment]
Random AI core in space
image

Random other shit in space
image

**Comment by S34NW** [comment]
oh god i turned off mob view when moving things

**Comment by AffectedArc07** [comment]
I am in the camp of I dont really like this. Here are a few issues I have with it in no particular order:

No one is gonna do anything meaningful in this bar in 75 seconds, much less when they are being murdered
image

I dont like the pods being here as sometimes people use pods to escape EORG
image

The fallback shuttle is no longer at CC
image

(Unrelated) Random floorbot in the wall
image

This room having 4 blast doors is dumb
image

2 comms consoles a room apart
image

The BSA can slice shuttles mid transit if admins choose to use it
image

This being split down the middle just looks off
image

This gap behind the chair seems really pointless since you cant get there, its just a wasted gap
image

Point of this room?
image

**Comment by S34NW** [comment]
> No one is gonna do anything meaningful in this bar in 75 seconds, much less when they are being murdered
> image
This was for the odd occasion an admin does a ghost bar/lounge (happens every now and then) they can have a functional kitchen.


> I dont like the pods being here as sometimes people use pods to escape EORG
> image
This is fair, it's one of the design choices that most people dislike about this.


> The fallback shuttle is no longer at CC
> image
Does it dock back at the fallback location? I've never even been able to get it working to test it.

> (Unrelated) Random floorbot in the wall
> image
My fault for not moving mobs when stuff moved about

> This room having 4 blast doors is dumb
> image
Agreed, I'll change it.


> 2 comms consoles a room apart
> image
As above.

> The BSA can slice shuttles mid transit if admins choose to use it
> image
Again, agreed.

> This being split down the middle just looks off
> image
Was an attempt at making it somewhat symmetrical, the other option is a double-door entry.

> This gap behind the chair seems really pointless since you cant get there, its just a wasted gap
> image
ALICE sits there, but I forgot to move her.

> Point of this room?
> image
That's where steve works.

**Comment by variableundefined** [comment]
Two maintainer objection and no forthcoming approval. Closing.

**Pull request closed without merging**
