### PR TITLE
Allows slime people to change color in lobby.

### PR DESCRIPTION
**Pull request by tigercat2000**
This PR allows for slime people to select their color in the setup character menu.
The SQL schema has been updated to save this preference, which should be taken into account on downstream server databases.

### CODE REVIEW

**Comment by Markolie** [comment]
As all donators with the slime color changer fluff item have been contacted (and only one responded after more than a week), we're good to have this one in once the 24h period passes.

_This includes a MySQL change. Do not merge/patch this until this change has been applied to the database._

**Comment by ZomgPonies** [comment]
Also make sure the slime colors update properly in proc/update_preview_icon

**Comment by tigercat2000** [comment]
Slime people previews do not work at all.

**Comment by tigercat2000** [comment]
@ZomgPonies proc/update_preview_icon and datacore rendering of slime people color on PR #548 is working

**Comment by Spacemanspark** [comment]
Tajaran always appear black on their ID card, mind looking into that as well?

**Comment by tigercat2000** [comment]
That is beyond the scope of this PR, but, I'll look into it once this is merged/closed

**Comment by Spacemanspark** [comment]
Alrighty.

**Pull request merged**
