### PR TITLE
walking prevents sliplock

### PR DESCRIPTION
**Pull request by VampyrBytes**
Removes slipping whilst walking from banana peels and soap to give a way
out of slip lock (#3490)

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Mmm, it DOES also render them less effective than water at slipping people too, then - water's more transparent, and harder to see - the banana peels, less so.

**Comment by TheDZD** [comment]
Is the clown PDA still able to be used to sliplock?

**Comment by Iamgoofball** [comment]
literally an i ded pls nerf
:-1:

**Comment by Iamgoofball** [comment]
also this doesn't fix the issue, that's bullshit

a proper fix would be "don't cause slipping if you're lying down"

"you can't slip while walking unless its lube" is not a fix

**Comment by Fox-McCloud** [comment]
Yeahhh, this isn't a very good solution, IMO; it would be better to add a check that you can't slip someone who's lying.

**Comment by VampyrBytes** [comment]
The clown pda was already set to not slip if walking before I changed anything.

> a proper fix would be "don't cause slipping if you're lying down"

that leads to a situation of you having to be lucky enough get away from them in between standing up and them pulling you over it again.

**Comment by Fox-McCloud** [comment]
@VampyrBytes 

The primary complaint has always been dragging someone over a bar of soap/peel/etc while they're already stunned/weakened---or the grab+pull permaslip trick; not that bananas/soap/etc will always slip, even when walking.

**Comment by VampyrBytes** [comment]
@Fox-McCloud 

The point is you can change your stance while you're stunned/weakened, so they can't keep doing it to you. If I just do a check for lying then they'll have to get better at timing but they'll still be able to do it

**Comment by Iamgoofball** [comment]
Well, maybe you should get good and use more than one method to keep your opponent down.

**Comment by HereticChurch** [comment]
Making it so you can't slip while already on the ground makes tons of sense. Walking is a bit iffy. Always considered walking as being more careful about where you step, so it'd make sense, but eh...
Walking new anti-slip meta.

**Comment by KasparoVy** [comment]
tfw a miner comes back from the roid after a long shift
buys NOTHING BUT SOAP

**Comment by theColdflame** [comment]
considering pretty much everyone can get hold of a peel, being able to counter it is far from a bad thing.

**Comment by Fox-McCloud** [comment]
>considering pretty much everyone can get hold of a peel, being able to counter it is far from a bad thing. 

You can counter it.

Water is countered by walking; banana/PDA/etc. is countered by picking the item up and chucking it aside.

**Comment by theColdflame** [comment]
And throwing it at someone's next tile, dragging them onto it, or sacking a tile with upwards of ten peels?

**Comment by Fox-McCloud** [comment]
Then you pick up each peel and move it out of the way, just like if someone has sprayed the next 20 tiles; you walk over the next 20 tiles.

Dragging someone onto the tile is only going to work the second time; they're going to have to wait until the stun wears off (and you can move again) before they can attempt to slip again; if you're not spamming like resist like no tomorrow and attempting to move away from the peel--that's on you, at that stage.

**Comment by Robertha89** [comment]
Walking to prevent slipping on slip objects is kinda bad, since the pda is also a weapon for the clown, it's been said before, but you can resist outta it, and in general it's used to be a dick, but being able to counter everything slippable by walking is just... Bad balancing, even making it you don't slip when laying down would not fix it, since +10 bars of soap in closet, slip person, close closet, if they open it, they slip, letting you close it. While slip lock is annoying, the best way out if getting help, it's as legit a strategy as stunlocking with a stunbaton. Or a police baton for that matter.

**Comment by VampyrBytes** [comment]
@Robertha89 

> since the pda is also a weapon for the clown

2 things. firstly, I've already said it, but I have NOT changed the PDA... I didn't need to. It was always possible to walk over the pda without slipping. It was finding that in the code that gave me the idea for this solution. All this does is bring the soap and banana peel in line with the pda. Secondly, no, the pda is not meant to be a weapon... it's meant to be a prank item, just as the banana peel that he gets from the banana he starts with is. There's a long way between a prank and being able to totally incapacitate someone.

> even making it you don't slip when laying down would not fix it, since +10 bars of soap in closet, slip person, close closet, if they open it, they slip, letting you close it

So we shouldn't fix one problem because there's another? It would take me about 2 minutes to stop you slipping if you're in a closet.

> it's as legit a strategy as stunlocking with a stunbaton

The fact that you are comparing easily accessed items with highly restricted weapons demonstrates the problem. The major difference is that if you went around as security abusing the stun lock ability of the stun baton, you'd soon find yourself banned from security, whereas you're fine if you use a banana peel

**Comment by Robertha89** [comment]
Again you can cuff them, and drag them around, you can push them over put them in a killing grab and go, neither of this allows you to resist. Also, it's not that easy getting banned from security.

Bot honestly, letting you walk over banana peels and soap without slipping, thats really broken. This does not fix the issues of stuns being op, this just tries to balance it in a way that makes it essentially useless. This is an inherent issue regarding stuns as a whole, and that is something that is impossible to fix. 

While being stun locked is no fun, it's still one of the parts when just used to slip lots of people, you already got like 3 methods of avoiding such. Janitor Galoshes, Magboots and hulk, and that anyone can counter it by simply walking... It kinda takes the fun outta peels and soap.

**Comment by VampyrBytes** [comment]
Obviously not enough support in it's current form. I'll put up a change soon

**Comment by Gummin** [comment]
Interesting. While if you use your verbs properly and effectively, a stun-lock can usually be broken,
but I think this is a good thing to have. Just using another method.
So :+1: :-1:.

**Comment by VampyrBytes** [comment]
:cl: 
Reverts banana peel and soap to slip whilst walking
No longer slip whilst lying down
No longer slip whilst getting in and out of a closet containing a slippery item
:cl: 

Discuss :wink:

**Comment by Gummin** [comment]
Personally I think this is the best way to go about it. :+1:
_also thanks for fixing slipping when exiting containers._

**Comment by theColdflame** [comment]
With good timing you could still keep someone stunlocked that way.

**Comment by Robertha89** [comment]
odd, the code does not work for me, can stunlock with a banana, and a closet. on both entering and leaving...

**Comment by Gummin** [comment]
@theColdflame Well I guess we could add like a 50ms delay before they can be stunned again?

**Comment by VampyrBytes** [comment]
@Robertha89 Did you use the code from the changes link just above where I posted the :cl: bit? And is your copy up to date? I refactored slipping into a mob proc about a week ago, if you haven't got that it won't work.

It was fully tested and working on my local server

**Comment by tigercat2000** [comment]
have you tested spacelube to make sure it actually still sends mobs flying

**Comment by Robertha89** [comment]
eh, probably not, mine is outta date, should get around to fix that.

**Comment by VampyrBytes** [comment]
@tigercat2000 Ice and lube were tested in the refactor, but there's nothing that would interfere with it here. The movement is handled through spawned step calls rather than anything recursive and step doesn't care whether you're standing or lying.

**Comment by Fox-McCloud** [comment]
One thing I'll definitely miss, once this gets merged: creating slip-paths with water.

Also, @VampyrBytes what happens when you slip on 5 tiles of lube? How much damage do you end up taking? 2 or 10?

**Comment by VampyrBytes** [comment]
@Fox-McCloud Both good points. Luckily the fix is the same for both. I'll get it up soon

**Pull request merged**
