### PR TITLE
WIP: Remaps the Sol trader shuttle; adds a SolGov ID card

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do
- Remaps the trader shuttle to be more accommodating for more than 3 buyers at a time
- Adds a new trader selling console
- Adds a new SolGov ID card since we have a few SolGov presets

## Why It's Good For The Game
Trader ship:
- More people can come into the ship and stare at the goods
- More streamlined purchasing process

ID:
- More lore-representative items in game

## TODO
- [ ] Fix the ship not jumping properly
- [ ] Ensure that the ship can dock with all three stations
- [ ] Add a few random spawns to the ship's cockpit to make it more lively
- [ ] Add access-locked crates into the small rooms (special delivery for sec/command, etc.)
- [ ] Adjust the ID's colours, finalise its appearance
- [ ] Maybe add SolGov-coloured crates?
- [ ] Add the buyer-seller console to the code
- [ ] Replace the placeholder RD consoles on the ship with the buyer-seller consoles
- [ ] Experience with different flooring; grey is good on the eyes, but rather monotone

## Images of changes

Ship **(not finalised)** current look:

image

image

ID **(not finalised)** iterations, need to be less saturated and its design chosen:
image
## Changelog
:cl:
rscadd: The Sol Trader shuttle has been completely revamped.
rscadd: A new ID card type was added for SolGov-related jobs.
tweak: The arrivals shuttle on the Cyberiad is now one tile narrower.
/:cl:

### CODE REVIEW

**Comment by meow20** [comment]
What's the problem with a minor event having some effort be put into it and for it to look cooler? Para's sprites are so old the whole server feels like it should be put down due to sheer age, having sol traders get an addition that isn't in any way detrimental to the game is a pure positive imo

**Comment by atteria** [comment]
This feels more like an actual ship rather than a hole-in-the-wall that must have been towed all the way from Jupiter.

The sprites look good, I personally like #2.

This ship deals with a real population issue, sol traders even on mid-pop are crowded to hell, causing salt in the process even when there's an actual queue.

**Comment by lewcc** [comment]
I really like this compared to the weird little shuttle we currently have now.
- Big thumbs-up on supporting more people at once. It's misery on higher populations.
  - If you still want to keep people in-line, you might want to corral them with some fencing.
  - If you want people to just chill out and wait, though, I think the waiting room needs to be a bit bigger, possibly by taking away some of the personal living space or extending it in general. It is still first-and-foremost a trading shuttle, so letting more people stick around inside (with some personal space) would be nice.
  - On the same note with the waiting room, I think it'd be cool if you added the ticket system that the HoP has to the shuttle, deli or DMV style. Grab a number, wait for it to be called, then place your order while you hang out.
- Could you elaborate a bit more on what you plan on with the buyer/seller system? Traders should be an RP event as well as the loot, and it's fun to be able to haggle, so the closed windows without a desk and "sit at a console in the back" style of this has me a little confused.

**Comment by Denthamos** [comment]
While I like the idea of expanding it a bit, there are some issues I have.  One of the main benefits of the smaller shutter is that it is easier for the traders to keep an eye on their entire shuttle and keep it secure.  With a larger area it will be harder for them to respond to someone breaking in from space like with how far the cockpit area is with its windows.

Secondly the loot/item viewing area with its windows, ill it takes is a single person with an RCD and 1.5 seconds to decon the windows while the traders are not paying attention and bam.  There goes a good chunk of valuable stuff, as with the current version the loot is behind the traders which gives them an easier sightline on shennagains.

**Comment by Sirryan2002** [comment]
> What's the problem with a minor event having some effort be put into it and for it to look cooler? Para's sprites are so old the whole server feels like it should be put down due to sheer age, having sol traders get an addition that isn't in any way detrimental to the game is a pure positive imo

Please don't misinterpret what I'm saying, I do not disagree with an expansion of the shuttle, infact I'm happy to see the trading area be expanded and support our higher player base. However, Sol traders only spawns 2 traders, sometimes only 1 person signs up. The traders don't need an entire room just for food vendors and the cycler room serves purely a cosmetic purpose, there are more efficient ways to make the trader shuttle look cool and more like a shuttle. I wouldn't be as concerned about this also if the shuttle design DIDNT extend beyond the NSS Cyberiad Z-Level (which is probably why it can't dock). It's atleast a full 2 tiles longer than the Z-Level and even if cut down a few tiles, it would place the shuttle at the very edge of it. Even the AI satellite gives 7-8 tiles in-between the last construction and the Z-Level edge.

**Comment by matttheficus** [comment]
Do note that walking around areas that are close to the zlevel's edge can cause some wacky teleporting stuff that could be used to clip into the Trading Shuttle. A buffer really should be given to avoid issues.

**Comment by Miraviel** [comment]
I am shelving this project, I do not have the brain capacity to work on this.

**Pull request closed without merging**
