### PR TITLE
You are now able to opt out of all role requests for a single round

### PR DESCRIPTION
**Pull request by Crazylemon64**
"Do you want to be a pet of Nerdwad McXenobiologist?"
"Do you want to be a pet of Nerdwad McXenobiologist?"
"Do you want to be a pet of Nerdwad McXenobiologist?"
"Do you want to be a pet of Nerdwad McXenobiologist?"
DAAAAAAAAAAAAAAAAAAAAAAAAAAA

:cl:Crazylemon
tweak: You can now opt out of all requests on a role for a round
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Honestly, I think if we put all the pop ups into the chat (similar to pAI's and Posibrains), we'd be better off.

**Comment by Lady-Luck** [comment]
What Spacemanspark said, yes. I don't really like this solution.

**Comment by KingPhilipIII** [comment]
Regardless, this is still better then ten thousand popups to be xenobiology creatures right around the time the midround antag would spawn.

**Comment by KasparoVy** [comment]
No reason to say no to unobtrusive convenience.

**Comment by taukausanake** [comment]
How about implement this in the chat? Or make it a preference if possible? That will be more work but I like both the popup box and chat notifications. They just both serve the same purpose but at different angles, sometimes better for worse

**Comment by Crazylemon64** [comment]
travis, where art thou

**Comment by Crazylemon64** [comment]
Oh, it looks like travis is back

**Comment by Fox-McCloud** [comment]
These being in chat wouldn't be ideal, either.

Action buttons is where it's at.

**Comment by Spacemanspark** [comment]
I prefer them in the chat because it's more noticeable to me.
I've been on /tg/ with the action buttons and I don't really dig it.

**Comment by KingPhilipIII** [comment]
I like TG's action buttons actually. I can see how others might not enjoy it however.

**Pull request merged**
