### PR TITLE
Janitorial equipment tweaks and cleaners availability

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Reagent usage is now higher with longer spray ranges.
**Space Cleaner tweaks:** 1 tile (10u -> 5u), 3 tiles -> 2 tiles (5u -> 10u).
**Added Advanced Space Cleaner (500u capacity) for janitorial ERT:** 3 tiles (10u)
**Janitor Water Tank tweaks:** 2 tiles (5u), 4 tiles (10u). Had 3 tiles spray for 5u before.
**Mop:** Capacity 5 -> 6.

**Mapping changes:**
Medbays: space cleaner amount has been decreased to 4.
Removed 1 space cleaner from workplaces that had 2 of them (in example: chemistry having two cleaners).

This is another version of #19989.

## Why It's Good For The Game

Non janitors shouldnt have the same cleaning capacity as janitors.
The amount of cleaners that science and especially medbay has was enough to keep their departments clean for the entire round (that is, if it didnt get stolen or if the round has a biohazard that goes on for a long time).
Having a nerfed version that can only clean 2 tiles each spray should be enough to accomplish their main purpose in these departments, and in cases where it feels too weak for the situation then you should be calling the janitor or even ordering a janitorial crate.
There was no reason to use the janitor water tank, it had the same range as the space cleaner, is a backpack and has slowdown.

**Expected roles:**
**Soap:** Same role as before, used in emergencies, hard cleaning.
**Mop:** Slow, but resources can be found all over the station, no need to refill at the custodial closet. Advanced version would be the way to go if you wish for mop to be your main equipment.
**Space cleaners:** Fast, but you need to refill constantly and the range isnt that great for larger rooms anymore.
**Janitor Water Tank:** Very fast, can take care of large rooms and refill less often because of its capacity. Downside is the slowndown and backpack slot lost with it.
## Images of changes

cleaners

https://user-images.githubusercontent.com/77684085/209906170-5fa32529-15b8-42e4-8ba8-9454148bdf8b.mp4

## Testing

- Used all cleaners and janitorial water tanks to clean lots of mess.
- Did look around the map looking for any mistakes or duplicated cleaners.
## Changelog
:cl:
add: Added advanced space cleaners (spray range = 3 tiles). Available to janitorial ERT
tweak: Reagent usage is now higher with longer spray ranges 
tweak: Space cleaner: decreased the maximum spray range (3 -> 2 tiles)
tweak: Janitor Water Tank: increased the maximum spray range (3 -> 4 tiles)
tweak: Mop capacity has been slightly increased
tweak: Decreased the amount of space cleaners available to science and medical departments
/:cl:

### CODE REVIEW

**Comment by farie82** [comment]
Be sure to note that this also influences any other use of space cleaner bottles. Such as spraying water or other chems. Labeling it balance due to this

**Comment by Henri215** [comment]
> Be sure to note that this also influences any other use of space cleaner bottles. Such as spraying water or other chems. Labeling it balance due to this

And because of this and after some tests i had stick to 5/10u values. If its decided that the maximum range usage of 10u would be too big of a buff when used with other chemicals then i could revert to the way it was before and tweak the capacity values instead.

**Comment by Henri215** [comment]
Increased mop capacity (5 -> 6 tiles before refill), enough to clean 3 tiles from each side.

**Review by Sirryan2002 — APPROVED** [review]
code looks good, just needs to be deconflicted I believe

**Comment by Landerlow** [comment]
Make janitor great again yes.

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
