### PR TITLE
Removes broken clownPlanet away mission

### PR DESCRIPTION
**Pull request by Kyep**
Deletes clown planet away mission.
Originally I tried to fix it, but after spending some time trying to get it up to standard - I came to the conclusion that it is just such a mess we're better off removing it and possibly replacing it with a new mission later.

You won't notice any change from this PR, because this clown awaymission is already commented out in the config, and has been for a year or more.

🆑 Kyep
rscdel: Deleted clown planet away mission.
/🆑

### CODE REVIEW

**Comment by jughu** [comment]
RETURN OF THESE LITTLE FURRY THINGS?

**Comment by Fox-McCloud** [comment]
This is a veryyyyy poorly designed away mission.

I'd just delete it, to be honest. The single unique thing it has that's not completely cheesy/unbalance is the Tribble.

Other than that it's just honk mech wonderland.

**Comment by Necaladun** [comment]
Yeah, if theres a clown planet away mission again, i'd overhaul it from the ground up.

**Comment by Kyep** [comment]
Changed this PR to completely delete the clown awaymission, on these grounds:
1) The map is terrible, with a long fence that goes nowhere, huge empty/destroyed areas, cheesy jokes, and generally is neither well-designed nor looks good.
2) Has only one unique thing, the tribble, which, frankly, is more annoying than useful. 

I did think about doing a revised clown planet... but if I do, I think I want to start from scratch. Having looked into it further, I think the basic layout of this map is too bad to salvage.

**Comment by taukausanake** [comment]
I fear that if you delete the clown planet away mission it will be lost to time and never redone. Why not just remove it (if not already) from the list of away missions and start working on a new one to replace it?

**Comment by Kyep** [comment]
@taukausanake Its already removed from the list of active missions. I wanted to fix it up and make it viable again. I fixed it so it compiles, etc, but then I started taking a really hard look at it. The problem with it is.... it just isn't fun. And it never will be, without a huge amount of work. It has nothing unique/interesting in it except tribbles (which are annoying!). It is badly designed/mapped. It just looks bad. Sure, it is an interesting story about the clown/mime war, but a better way to tell that story would be to have, say, opposing clown/mime outposts on different rocks in space, assigned to spy on each other, and decommissioned after the war. That could be a much more interesting away mission, without huge empty areas. The clown planet map is just.... not that well designed/interesting.

**Comment by KasparoVy** [comment]
Rest in prank, honk in peace.

**Comment by Rumiluntti** [comment]
And nothing of value was lost.

**Pull request merged**
