### PR TITLE
Sixteen New Borg Skins!

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
Adds three new borg skins for each module, and one new security skin (only one since it's only used as part of adminbus/red ERT)
Some come from Citadel Station RP, some come from Yogstation, some come from TG, one that was in pieces across multiple codebases, and some I made myself. Basically all of the ones ported from other stations had modifications and shading changes to make them look better on our server. (Sorry to any original creators, I tried to track some of the designs down but struggled to do so as they have convoluted histories)

## Why It's Good For The Game
BORG DRIP PART 2

## Images of changes
Names and details are listed from left to right. None of my fanciful descriptions here have any mechanical effect, these are new visual skins purely.

### Nanotrasen welcomes you to this display of our newest cyborg chassis designs, coming very soon to a station near you!

image
**"Mark III"** - Created by the same roboticists that designed the Mark I maintenance drones common on many NT stations, the Mark III is a massive upgrade in size, ability, and sentience. Top scientists rave, "At least it's not a Mark II".
**"Heavy Service"** - A repurposed heavy construction chassis, fitted with high quality drink dispensing equipment and the finest social courtesy module a robotics budget can buy, the Heavy Service module is sure to be a welcome sight in canteens and fancy dinners across NT space"
**"Omoikane"** - Dust-covered, yet glittering spherical robot parts were found in storage rooms scattered across our oldest stations. An enterprising explorer gathered them, and put them together piece by piece. Once together, the machine unfolded from its spherical shape. "I am Omoikane", it said, before experiencing a power surge that destroyed its internal components and killed the explorer. So we tore the busted parts out and shoved standard borg internals in there! RIP nameless explorer.

image
**"Mark III"** - With millions of man-hours of drone work to study, our robotics team was able to create the perfect blending of drone ability and human ingenuity in this cyborg module design, with only one extremely tragic setback!
**"Heavy Engineer"** - Do you need to build an entire station from scratch? This powerful cyborg can do it all, with it's powerful cybernetic and hydraulic internals.
**"Treadwell"** - Numerous arms, numerous tools. The Treadwell model performed excellently in our engineering tests, with Kidan crewmembers specifically noting their appreciation for it's bugeyed visual sensors.

image
**"Qualified Doctor"** - Arriving mysteriously at our robotics hub looking for work, coming from parts unknown, this robot quickly demonstrated its medical skill saving the life of our hub director from an attack of venomous [REDACTED] larvae. The director desided it was better to not ask too many questions and approved the robot for work on all NT stations.
**"Heavy Medical"** - Sometimes you just need a really buff doctor to help you get back on your feet.
**"Coffin Medical"** - In order to cool its cutting edge electronics, this design has armatures that shift position regularly. Despite the intimidating name, the Coffin borg line is named solely for the shape it makes when it's armatures are retracted.

image
**"Mark III"** - Nanotrasen's legal department would like to note that there is an active injunction in all NT space against dicussing the Mark II robot design. Do not ask about the Mark II, the [REDACTED] incident, or the whereabouts of [REDACTED] asteroid mine.
**"Heavy Cleaner"** - Say goodbye to daily stains and dirty surfaces with new HEAVY CLEANER BORG. Goodbye dirt!!
~~**"Next-to-Godliness"**~~**"Custodiborg"** - Truly, the halo above this borg's head speaks to the real moral fiber and emotional fortitude it takes to be a station janitor.

image
**"Sleek Miner"** - A classic robot design, now upgraded with highly aerodynamic plating designed to give protection against the at least some of the terrors that our mining crews have to face.
**"Squat"** - A repurposed experimental Syndicate combat robot, this mining robot was given the nickname "Squat" by the engineers who repurposed it. We don't know why, as it's quite tall. Who knows why engineers do anything?
**"Coffin Drill"** - With it's armatures retracting and expanding to keep it's temperature at peak efficiency, this borg design says "I'm cool", while it's colossal drill says "Warning, please keep your hands and feet away from the colossal drill".

image
**"Heavy Security"** - Say goodbye to daily Space Law infractions and dirty dealing asistants with new HEAVY SECURITY BORG. Goodbye dirt!!

_See Icon Diff Bot for the animated sprites: the Mark IIIs wiggle their legs to move, Treadwell's tracks move, Omoikane rolls into a ball, Next-to-Godliness has pulsing lights, and the Coffin borgs shift armature position every ~30 seconds._

## Testing
Spawned like 50 cyborgs at once (and a hellish chorus of "I LIVE AGAIN" was heard) and tested every module and skin, including that they were able to have their panel opened by a roboticist.

## Changelog
:cl: PacifistDalek, a whole bunch of spriters whose identities are lost to time and github commits
imageadd: New Borg Skins!
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
All of these look awesome, 2 things though
1. "Next to godlyness" should be renamed to something else, it's funny but people will meme it a BIT too hard. Great sprite though and I'll 100% use it
2. The drone borgs a still a bit too short, which is an issue because melee will be more difficult on them

Great sprites though, and the heavy ones don't actually look like mechs!

**Comment by PacifistDalek** [comment]
I'm listening to feedback both here and on discord, and will happily tweak designs, by the way!

**Comment by matttheficus** [comment]
I like the "three medbots in a trenchcoat" WAY more than I should. That being said, I worry about hitboxes for some of them as theyre a tad small.

**Comment by Landerlow** [comment]
I love these skins! <3

**Comment by UmeBelle** [comment]
I love it, some of them look a bit short but I wouldn't complain as I don't find the hitbox being smaller a major issue. Yeah 1 single pixel can make a difference in some cases but I personally don't play just to win. I like to have fun.

Very nice work!

**Comment by S34NW** [comment]
image
This one looks a bit off, like it doesn't belong with the rest. I think it's because of the border? Makes it look a little more "blurry"

**Comment by S34NW** [comment]
Actually it might just be an issue with how you tok the screenshot, as this does it too 
image

**Comment by PacifistDalek** [comment]
Yeah, that’s a screenshot issue, they’re all crisp normally.

Also, gonna convert this to draft while i bulk up the small ones a bit!

**Comment by PacifistDalek** [comment]
Bulked up the first of the 4 that need bulking up.
image

**Comment by PacifistDalek** [comment]
image
Landmate to scale! Hopefully this size is a bit better :)

**Comment by PacifistDalek** [comment]
Omoikane bulked up too!
image

**Comment by PacifistDalek** [comment]
Updated images of all the new borg modules (minus the weird blurring before):
image
image

**Comment by ATP-Engineer** [comment]
Unsure if a bad take, but probably should tweak the security sprites eye to be a flash color set instead of yellow. Changing it to a more fitting green.
image

**Comment by Sirryan2002** [comment]
I'm voting no on this PR (I know it took a while to leave feedback)

**Here is my reasoning:**

- You are adding 16 more borg skins to the game, however, I don't feel like they have solid cohesion with each other, as in the art styles vary significantly. The heavy borg skin does not feel like it comes from the same design as the coffin drills or mark III's.
- I like the heavy service borg, squat, treadwell, and a couple other sprites but if they're packaged with all 16, it's difficult to accept the PR as a whole
- the Mark IIIs feel like they are scaled larger than what their sprite design would suggest and I think that reduced the overall quality of the sprite.

Overall there is a lot of good sprites (and ones I would be happy to add to the repo), however now that we're moving towards having a more cohesive art style & design we need to start more closely nitpicking sprites. I think you should find some time to sit down with @McRamon and go over what he has in mind for borg sprites and how we can take the sprites you currently have right now and move them in that direction.

**Comment by PacifistDalek** [comment]
> I don't feel like they have solid cohesion with each other, as in the art styles vary significantly.

That’s very fair, and quite accurate, as they’re all ports from other servers except at this point the Mark IIIs. I’m more than happy to pare down what you see above to a smaller collection that are more cohesive.

> * the Mark IIIs feel like they are scaled larger than what their sprite design would suggest and I think that reduced the overall quality of the sprite.

That’s unfortunate, as i scaled them up specifically because so many people were concerned about balance. I can scale them back down if head consensus is that it won’t affect balance and the aesthetics will be approved.

> Overall there is a lot of good sprites (and ones I would be happy to add to the repo), however now that we're moving towards having a more cohesive art style & design we need to start more closely nitpicking sprites.

I do wish this change had been publicized earlier, (i don’t mean this in regard to your feedback taking a while, i just mean in general terms, a shift to a cohesive spriting style would have been nice to know about a few months ago) as i would definitely have dropped some of the designs earlier before i put work into them!

That said, i know that’s life with a collaborative project like this, and i’m not frustrated or the like :)

In any case, like i said, im more than happy to pare this set down. I only truly want to fight for/put extra effort into the Mark IIIs and Qualified Doctor, tho i do think some of the others are excellent as well . I’d love to hear which ones both yourself and other heads feel worth including.

**Comment by hal9000PR** [comment]
author is unable to continue with this PR due to IRL situations. filing as closed. anyone is free to pick this PR back up with the requested changes.

**Pull request closed without merging**
