### PR TITLE
Remove collaborators

### PR DESCRIPTION
**Pull request by datlo**
~~REMOVE COLLAB remove collab you are the worst mechanic you are the self-antag smell to our server you may not go~~

Remove syndicate collaborators, as requested by PurpleGenie.

🆑
Delete: Removed syndicate collaborators.
/🆑

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Quite simply: no.

The entire "issue" from my understanding is players not being properly policed on this. The system isn't at fault, not like the players and administration

**Comment by datlo** [comment]
Just doing the PR as requested to have it discussed, I'm personally neutral on the issue and don't care either way.

**Comment by FalseIncarnate** [comment]
I'm aware you were requested. I can still oppose it, and am opposing it, without it being simply because you made the PR. The entire "reason" for the request is what i'm opposing.

**Comment by Aurorablade** [comment]
Echoing false. And if needs to be discussed then it needs to be done so outside a PR.

**Comment by Shadeykins** [comment]
The entire issue has never been about players being poorly policed. It's about a poorly implemented system that creates and encourages psuedo-antags who can't do anything a regular player can do anyways. Either it should be changed to remove the troubling gray area (by lowering the number of collabs and making those who are successfully sought out into full antags w/ no TC) or scrapped. The system as-is attempts to make antags who can't actually do anything sincerely meaningful and who get bwoinked/warned if they do.

All the system in its current state achieves is getting new players in trouble for no good reason (it doesn't help that's there not even an easy/straight-forward way for admins to see who's a real collab/chump).

This isn't even a new issue either, it's something that people have been talking about pretty much since the system's inception. Anyone who's bothered to log in more than once in a blue moon is well aware that the system is deeply flawed and either needs a serious amount of rethinking or an out-and-out removal.

**Comment by Allfd** [comment]
Its been forever, I don't know what to tell people.  Also its confusing, every time we talk about it, the things a collaborator can do, are things that we already let people doe if they have a compelling IC reason.

**Comment by Kyep** [comment]
Thank you for doing this PR.
I've been meaning to do it for awhile, but you beat me to it.

**Comment by Pixelzilla** [comment]
I dont personally understand the issue with being collab. It's helpful for newer traitors to have someone to contact safely that can help them out in minor ways. I've often explained to them that i am not an agent but will help them in small ways if I can. I make it pretty clear i wont murder people but I can help them out by getting them things to make their job a bit easier without drawing too much attention to them specifically getting the things they might need or saving them/cloning them if they die and potentially breaking them out of the brig. I think it adds a nice fun element even if it isn't often that people contact collaborators and use codewords.

I think being a collaborator _is_ your IC reason to do shady things to help antags and I dont think removing it is going to make the game better, it might just snuff out yet another interesting feature that needs a bit more polish.

As it is a lot of the crew is willing to snitch/validhunt so having at least a handful of people who are collaborators and are sympathetic to those who are being blackmailed/contracted into the syndicate can make life a little easier with how frequently people seem to go out of their way to remove antags quickly.

I remember when this feature was not around and honestly? I really like what collaborator has brought to the table. I was absolutely unaware the community had issues with it or thought it was something that brought so little to the round that it should outright be removed. I don't really like to antag but I like being able to help them out as a collaborator. It's a nice middle-ground for people who aren't interested in being an antag but still don't want to be a super loyal crewmember and want an IC justification to occasionally help agents screw over a company they oppose.

**Comment by FalseIncarnate** [comment]
For clarity, collaborators have been part of our codebase longer than I have, likely longer than most of not all of our players and active contributors and above commentors.

When Allfd says “it’s been forever”, he’s not really exaggerating. The only thing that changed was their own knowledge of BEING a collaborator.

https://github.com/ParadiseSS13/Paradise/pull/6829 Attempted to remove this same feature and was shut down because clarification provided by https://github.com/ParadiseSS13/Paradise/pull/6867 was deemed more favorable than outright removal.

Shadey’s argument that the system is poorly implemented is outright laughable as far as code is concerned. https://github.com/ParadiseSS13/Paradise/pull/7917 even goes as far as to straight up tell the collaborator they are not an antagonist, so the entire issue once again is players and admins failing to acknowledge basic responsibilities of their conduct and case management.

The only shortcoming of the code is not having an easy reference of current collaborators, which hardly warrants removal of the entire system.

Improve, educate, and clarify. Not remove.

**Comment by Birdtalon** [comment]
The code isn't flawed it's more a question of whether or not it fits into the current state of the server. Maybe a config toggle option would be better?

**Comment by FalseIncarnate** [comment]
A config option wouldn’t be a bad idea, even if we keep it. Honestly, probably should have included one a while back so potential downstreams could decide for themselves without having to alter code

**Comment by Denthamos** [comment]
Its about time.  While I love the concept on paper, in practice its hell to manage and just tends to confuse newer players and tends to be newbie bait for breaking the rules.  Its better to avoid such confusion.

The capability to be able to make collaborators via a config toggle would be nice, but it should not be default on in round.

**Pull request merged**
