### PR TITLE
Fixes a pipedicularly problematic issue in brig disposal pipes

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Thanks to some _disposable_ Clowns who found this bug.

Before:
img
The topmost disposal junction is backwards.
After:
img
Now it's fixed, though looks a bit off.

Also fixed some extremely minor issues with aesthetic tiling, some lights and missing floor tiles.

:cl: FreeStylaLT
tweak: Remapped brig
fix: Fixed broken pipes in brig
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Why did you move both junctions below the door? You could have just moved the problem one and kept the other pipe out from beneath those windows

**Comment by Rurik123** [comment]
Ran into this bug earlier while attempting to escape from sec, and ended up with a borg having to cut me out. A anti climatic ending.

**Comment by Anoonki** [comment]
Dang now I can't duck responsibility as HoS at round start and just sit in that junction

**Comment by FreeStylaLT** [comment]
Screwed up my branch, going to make another PR.

**Pull request closed without merging**
