### PR TITLE
Fixes & Improves MoonOutpost19 Away Mission

### PR DESCRIPTION
**Pull request by Kyep**
Changes:
- Adds atmos, powergrids, and new areas. Some areas, you may have to do some engineering work on to get powered.
- Fixes duplicate blast doors on the same tile. Mapping error.
- Makes it possible to complete the mission by opening the blast doors, rather than trying to break the rock around the doors.
- Makes it possible to repair MO19 it to functionality. This includes repowering it, filling it with air, and generally taking it over.
- Standardizes the access used in the mission to 271, aka: access_away01.

Notes:
- This PR relies on the away mission powergrid change introduced in https://github.com/ParadiseSS13/Paradise/pull/6531 for full functionality.
- All the combat parts of this mission (the aliens in the northwest) have been left as-is. This is only a tweak to make the exploration/construction parts of the mission more substantial.

🆑 Kyep
tweak: The moonoutpost19 away mission should now be finishable, and more enjoyable to attempt.
/🆑

### CODE REVIEW

**Comment by Taaketa** [comment]
Now I know where I will be as an Engineer.

**Comment by Fox-McCloud** [comment]
Pics.

**Comment by Kyep** [comment]
@Fox-McCloud

**Comment by taukausanake** [comment]
You know what I would like but don't know if the map actually has it? Mineral rocks in there. It has mining purpose and I always like the idea of having to live off another section than just the main station. Does it have mineral rock walls?

**Comment by Kyep** [comment]
@taukausanake It does not. I'm already facing a little bit of an uphill battle with getting my away mission improvements merged. I worry that if I put real minerals in these awaymissions, it would result in miners going here, rather than the mining asteroid. Or it might result in a bunch of pseudo-miner-explorers. Not necessarily a terrible thing, but.... I'd prefer to focus on fixing the more major stuff, and steer away from controversy.

**Comment by taukausanake** [comment]
That's understandable. I just wanted to ask is all

**Pull request merged**
