### PR TITLE
Updates the icon for the firecult god

### PR DESCRIPTION
**Pull request by Draconic-saint**
Gives the glorious Pyr'Kaus (Bug'sie for close friends) a new look!

photoshop_2017-01-31_00-07-27

While still not on par with Nar Sie on level of detail and shading, I do feel like this is a welcome improvement on the lackluster sprite for the Lord of the firecult.

### CODE REVIEW

**Comment by taukausanake** [comment]
I might have been the only one against the fire cult having a god figure. I wanted their end goal to set the station on fire with a flame that spread everywhere, eats everything, and turns mobs into fire spirits like Nar'sie has its little things. Cleansing the station if you will. I wouldn't want firecult to be a reskin of Nar'sie cult even if some mechanics are different

**Comment by KasparoVy** [comment]
The sprite looks absolutely dope, great work.

**Comment by HugoLuman** [comment]
I have to agree with @taukausanake
I'd really like the different cults to be that, different

**Comment by Draconic-saint** [comment]
Any feedback on the mechanical features of the cult rework should probably be directed at fethas, or the forums.

I just do sprites man, the old version I did sucked, this one is better.

**Comment by KingPhilipIII** [comment]
Make it like TG's Clockwork cult in that it focuses more on base building and steadily gaining power than a blitz(Which is now possible thanks to no research times.)

**Comment by Spacemanspark** [comment]
we really should just port over /tg/'s clockwork cult

**Comment by Aurorablade** [comment]
This Is a sprite PR not a game mrchnich PR  there is also a limit on what I can or am will ing to do. Themeimg the cult sprite wise lends enough to a feel

**Comment by KingPhilipIII** [comment]
I wonder frequently what it would be like to play as a Clockwork cultist on a station where Sec didn't call the shuttle the moment they discovered there was a cult about.

**Comment by Fox-McCloud** [comment]
>we really should just port over /tg/'s clockwork cult

Not as long as @changelingRain keeps making 10 PRs a week to it =p

**Pull request merged**
