### PR TITLE
Admin 'List SSDs' verb & cryo option

### PR DESCRIPTION
**Pull request by Kyep**
Adds two things:

- A 'List SSDs' admin verb, which does exactly as you'd expect
- A 'Cryo' option, which can be used from PP or the above list, to move a SSD person to cryo.

Other changes:
- Refactors cryopod.dm removing "loc =" calls, and turning the process of entering a cryopod into a proc.

Demo:

ssd_panel

🆑 Kyep
add: Admins now have a 'List SSDs' verb to list SSD players, and the ability to move them to cryo.
/🆑

### CODE REVIEW

**Comment by taukausanake** [comment]
Are SSDs really that big an issue on the station? Not that I'm in disbelief just curious

**Comment by Necaladun** [comment]
I don't see SSDs as a huge issue.

I'd prefer to see a "list SSDs" panel with a time of how long they've been SSD, and an auto-cryo button for each.

I can't think of any times I've needed to hit the button in this PR

**Comment by Kyep** [comment]
Putting each individual person in cryo manually seems like a lot of clicking. It doesn't really matter who they are. If they're SSD for ages on station, they should go to cryo.

**Comment by Kyep** [comment]
@Necaladun @FalseIncarnate @Aurorablade This PR has been changed so now, it simply provides a list of SSD players, and lets you cryo each one selectively. The list includes their Ckey, name, job (if any) and a PP / Cryo link. Cryo links also show up on PP in general, but only for SSD players.
I changed it like you asked. Now support it, nerds :P

**Comment by Necaladun** [comment]
A: Great and damn useful :+1:  - Could I be an ass and request you make heads of staff and antags stand out on it? (Red or green text or something).
B: Good and kinda useful 

C: Refactor part is above my paygrade so sure why not refactor all the src procs

**Comment by Kyep** [comment]
@Necaladun your requests are done.

**Comment by Fox-McCloud** [comment]
the special roles formatting table seems broken.

**Comment by Kyep** [comment]
@Fox-McCloud Do you mean how some cells are blank? That's intentional - those mobs just don't have a special role.

**Comment by Kyep** [comment]
@Fox-McCloud Updated.

**Comment by Fox-McCloud** [comment]
That looks way better.

Conflicts though.

**Comment by Kyep** [comment]
@Fox-McCloud Conflicts fixed.

**Comment by Kyep** [comment]
@Fox-McCloud Apparently the merge conflict fix introduced some weird characters at the top of admin.dm, which did not show up in Git diff, but still caused Travis to fail. That has also been fixed now. Should be good.

**Comment by Kyep** [comment]
@Fox-McCloud ready for merge.

**Pull request merged**
