### PR TITLE
Armor resprite (Sprites by Norstead)

### PR DESCRIPTION
**Pull request by AffectedArc07**
Making this PR on behalf of Norstead since they dont have a GitHub account and dont want to go through the hassle of setting up git locally.

## What Does This PR Do
Resprites the security armor because the current sprites are well, lacking to say the least. It resprites regular armor, security armor (holobadge attached), detective armor and blueshield armor. The resprite includes changes to onmob sprites and the item

## Why It's Good For The Game
Sprite improvements are good

## Images of changes
image
image

## Changelog
:cl: Norstead
imageadd: Resprites the security armor
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Any updated vox-fitted sprites?

**Comment by AffectedArc07** [comment]
@KasparoVy 
From Norstead:
`There could be if people want it`

**Comment by KasparoVy** [comment]
That's be awesome if we could keep maintaining sprite parity, Vox currently have fitted Armour sprites so it'd be correct to update those too

And greatly appreciated

**Comment by Carthusia** [comment]
Very nice, an update to the vox sprites to would be appreciated by the vox mains

**Comment by AffectedArc07** [comment]
image
Vox sprites have been done

**Comment by KasparoVy** [comment]
That's awesome, thanks a ton @AffectedArc07 and Norstead

Sprites look great and I appreciate the effort. Vox have species-fitting for just about everything at this point and if we maintain that by adding Vox sprites when adding/respriting stuff we won't need any more massive sprite PRs in the future haha.

**Comment by AffectedArc07** [comment]
I take no credit for this, I just made a PR with the sprites

**Comment by AffectedArc07** [comment]
Grey sprites have been made, but I need to implement them when I aint busy. DNM for now

**Comment by procdrone** [comment]
Are holobadge versions for security optional or all security armors now have in built holobadge?

I would personally prefer it being optional.

**Comment by AffectedArc07** [comment]
They are still optionally equipped, I just put them on to show the sprite properly

**Comment by McRamon** [comment]
I still recommend not making blueshield armor badge so bright and out of place

**Comment by AffectedArc07** [comment]
The grey sprites look off due to grey having almost no jumpsuit sprites of their own, and looks weird, so they wont be included.

**Comment by Pixelzilla** [comment]
Can we get before images for comparison?

**Pull request merged**
