### PR TITLE
Adds briefcase/card box as leather recipes and reorganizes other recipes

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds the briefcase and card box as leather recipes.
Includes some recipes lists  and reorganizes leather, plastic, cloth, minerals, cardboards and wood recipes.
## Why It's Good For The Game

The briefcase and card box are supposedly both made of leather, it would make sense  being able to make them with it.
Having organized recipes is good for locating your desired item.
## Images of changes

leather
wood

## Testing

- spawned all sheets, got the added items and verified all recipes, all look good.
## Changelog
:cl:
tweak: Briefcases and card boxes now can be made using leather
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
not sure how I feel about the utility belt being craftable

**Comment by Henri215** [comment]
> not sure how I feel about the utility belt being craftable (as opposed to using the biogen)

This PR only adds the briefcase and card box, the toolbox can be made using leather already.
I agree that it should be made either with the leather or with biogen.

**Comment by McRamon** [comment]
Bingen can't craft utility belts tho

**Comment by Sirryan2002** [comment]
will try and get a review out on this soon

**Review by farie82 — APPROVED** [review]
Be sure to next time avoid doing unrelated refactors in add/tweak PRs. It makes reviewing quite a bit rougher

**Pull request merged**
