### PR TITLE
Adds the Sparta tattoo for Greys

### PR DESCRIPTION
**Pull request by ArcZelf**
## What Does This PR Do

Adds a new tattoo for Greys to select called the "Sparta" tattoo.

## Why It's Good For The Game

Grey swag. More customization for Greys is good because it gives them more freedom and uniqueness. =)

first pr plz no hate

## Images of changes

image

image

image

image

## Testing

I spawned in my naked blue eyed grey character with the tattoo and took nude photos of myself and uploaded them to github.

## Changelog
:cl:
add: Added the Sparta tattoo for Greys.
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
LGTM from a technical standpoint

**Comment by McRamon** [comment]
Id reccomend adding a lil bit of shading to it so it follows the curves of the body and doesnt look like a weird spot of pixels

**Review by Sirryan2002 — APPROVED** [review]
code and sprite diffs look good

**Review by hal9000PR — APPROVED** [review]
cowabunga

**Pull request merged**
