### PR TITLE
Blood Cult 2: Electric Boogaloo

### LINKED ISSUE #2799: Cultist Construct lights showing behind NarSie
Cultist Construct lights will be visible behind Narsie. Completely harmless but a bug nonetheless.

### LINKED ISSUE #6089: The blood spilled tally doesn't work.
The "spill blood over X tiles" objective doesn't properly count the tiles. `bloody_floors` stays empty at all times, I had to manually trigger the next cult phase.

### LINKED ISSUE #8070: Crew leaving the station and cult summoning their god results in cult victory
**Problem Description**:
If the crew manage to successfully evacuate the station and those couple pesky cult left manage to band together and summon their god, it results in a cult major victory.

**What did you expect to happen**: 
The crew managed to successfully evacuate, the shuttle has left, the cult just cheesed it in the last two minutes. Either it should be a crew victory or a draw.

**What happened instead**:
Game results in cult major victory, which equals a lot of OOC salt from both sides, admins telling everyone's it's a bug and so forth.

**Why is this bad/What are the consequences:**
People are confused about who won and both sides feel butt hurt over it. Plus, it adds an easy victory solution to the cult; convert everyone, do objectives, then camp off station and wait for crew to leave before summoning, win everytime.

**Steps to reproduce the problem**:
Call the emergency shuttle, have it leave with the crew and while it is in transit back to CC, summon thy cult god.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I mean, it was the slaughter demon god, I dunno if that meant anything but probably not. Staff and players were saying it was a bug that they won while other players celebrated the cult cheese.

### LINKED ISSUE #8833: When non-cultist releases you from shard, message you receive is bugged. ((and 2 more minor issues))
**Problem Description**:
I was killed and sharded by cultist Otsuka Misaka. Security captured them.

First issue: I was able to pull cultist from officer grip when I was still shard and in cultist backpack.

Second issue: I was released from shard form by security officer that was NOT cultist.
I recieved message "You have been released from your prison, but you are still bound to Kaizen-5's will. Help them succeed in their goals at all costs." Kaizen-5 was security officer that released me.

Third issue: No idea if it's intended, but as Shade I was able to access others equipment and take off their equipment ((and cuffs))

**What did you expect to happen**: 
I really have no idea what should happen. I got so confused that I decided to a-help that. I literally had no idea if I have to serve security now. But from what admins said, that should not matter at all, and I should recieve message that I still serve the cult.

**What happened instead**:
I recieved message "You have been released from your prison, but you are still bound to Kaizen-5's will. Help them succeed in their goals at all costs."

**Why is this bad/What are the consequences:**
Well I recieved information that I am bound to security officer now. I a-helped that, but some players will help security. Also at the time admins responded, cultist that sharded me, was already deconverted.

**Steps to reproduce the problem**:
Step by step:
-I was killed and sharded.
-Security detained cultist
-Cultist ordered me to pull her out from officer grip, and as shard in her backpack I was able to do that.
-Officers brought cultist to processing, Kaizen-5 released me from the shard.
-I received information that I am bound to Kaizen-5
-I a-helped that. Cultist got deconverted.
-When I got information that I am still part of the cult, I escaped brig.
-Later I as shade, pulled another cuffed cultist from officer grip, took off the cuffs.
-I was killed by officer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Well It was cult gamemode, Beside the things I mentioned, everything was normal

### LINKED ISSUE #10402: Cultist: "Do Not Let Non-Cultists Escape" Objective isn't counting Non-Cultists
**Problem Description**:
The "Do not let Non-Cultists escape" objective isn't counting non-Cultists on the Escape Shuttle or Emergency Pods.

**What did you expect to happen**: 
It would count at least 1 non-Cultist (me) as escaping.

**What happened instead**:
It said 0 non-Cultists escaped on the Escape Shuttle and Escape Pods.

**Why is this bad/What are the consequences:**
It makes it impossible to fail the Objective, meaning the Cult can start summoning 15 seconds before the Escape Shuttle leaves with the crew and still greentext.

**Steps to reproduce the problem**:
1. Escape Shuttle called.
2. We get the summoning alert 15 seconds before the Shuttle leaves the station.
3. Eldritch abomination is summoned while the Escape Shuttle is en route back to CentComm.
4. Final non-cultist count is (0 non-cultists escaped on the shuttle, 0 escaped on pods).

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Summoning didn't succeed until the Escape Shuttle was already en route with us back to CentComm.

image

### LINKED ISSUE #10958: Cult Sacrifice Objective Requires Admin Intervention To Complete
It's an old and well-known bug, I know, but it might as well be put up on the Github as a reminder.

**Problem Description**:
The Cult's Objective to "_Sacrifice [Crew Member]_" can not be completed normally, and requires an admin to manually set the objective as complete.

**What did you expect to happen**: 
After placing the target on the Tribute rune with 3 total invokers, for the sacrifice to go through, and to get the message: "_Yes! This is the one I desire! You have done well._" from the cult god, before being given the next objective.

**What happened instead**:
Whether the target is alive or dead, the cult god gives the message: "_I accept this sacrifice._" as if it was a non-target that was sacrificed. No further objectives are given.

**Why is this bad/What are the consequences:**
Cult rounds can't progress without admins being on-duty. Gives admins more work.

**Steps to reproduce the problem**:
Be in a cult of 4+; if sacrifice is not the current objective, complete the objective until it is given.
Capture the indicated sacrifice target and place them over a Tribute rune with 3+ cultists adjacent, then use the rune. Target's state doesn't seem to make a difference.

**When did the problem start happening**:
Possibly for more than a year at this point.

**Other Notes**:
Did some diving in hopes of helping a bit. For ease, the problem likely lies in files are listed below:
[Cult_Objectives](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/cult_objectives.dm)
[Cult Runes](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/runes.dm) (Lines 383-459)
[Cult](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/gamemodes/cult/cult.dm) 
EDIT: Problem described by Aurorablade below.

### LINKED ISSUE #11275: Spawned in cult constructs cannot see cultists
**Problem Description**:
Manually spawning in cultist constructs despite having the cult faction, cannot see the cultist symbol on the HUD.  You cannot make spawned in constructs a cultist either via the traitor menu, but you can make them a traitor?  (Honestly what the shit?)

**What did you expect to happen**: 
To open the traitor panel on constructs and turn them to cultists

**What happened instead**:
Cannot make spawned in constructs via the create mob menu cultists

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
Spawn a construct, open its traitor panel.  No cult open.

**When did the problem start happening**:
Has been in for quite some time I assume.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Cult mode.

### LINKED ISSUE #11307: Cult Summon Locations Pulling from other Maps
**Problem Description**:
For the cultist summoning objective which lets them only summon in specific areas, noticed that some of the locations are often locations not even on the box map we run.  An example is the fitness room which is on meta/delta but not box.

**What did you expect to happen**: 
For only locations on the map being used to be used for summoning locations.  Kind of hard to summon in an location which does not exist.

**What happened instead**:
Cultists are getting summoning locations that do not exist in the game.

**Why is this bad/What are the consequences:**
Limits or straight out prevents the cult from summoning.

**Steps to reproduce the problem**:
Its RnG for the game mode when you get the summoning.  Sometimes you get all box locations, sometimes you get locations not on box.

**When did the problem start happening**:
Most likely when the cult location summoning was added.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Cult round.

### LINKED ISSUE #14132: Cult objectives seem to mess up when sacrifice targets are no longer a thing
**Issue Description**:

When cult's sacrifice target(s) no longer exist weird things seem to happen with the objectives as well newly converted cultist's notes.

Images of it happening in a round where I believe both sacrifice targets, who were in soul stones, got deleted by a admin on accident:
cult1
This is what the notes of the objectives looked of a newly converted cultist.

cult2
This is how the objectives looked when the round ended.

**What did you expect to happen**: 

I expected the cult's objective to be displayed consistently between all cultists as well as the end round info to display the objectives correctly.

**What happened instead**:

See the images for what it happened.

**Why is this bad/What are the consequences**:

This may cause confusion between the players and the admin team due to inconsistency and other things.

**Steps to reproduce the problem**:

Become cult with sacrifice objectives with valid targets. Somehow remove the targets and then convert a new cultist the sacrifice objective should be shown to the new cultist as a free objective and the end round screen will display a empty objective.

**When did the problem start happening**:

Possibly has been a thing for a long time, but only seen today. 2020-08-22

### LINKED ISSUE #14150: Couldnt convert a mindshieldless crew with two cultists.
**Issue Description**:
Two cultists stood next to a binding rune with a mindshieldless crew and when trying to activate the rune, it said it needed two invokers.

**What did you expect to happen**: 
I expected to convert the crew to be cult.

**What happened instead**:
The rune pulsed saying it failed and claimed that it needed a 2nd invoker, even though we were both within range of the rune to be invokers.

**Why is this bad/What are the consequences**:
If toko hadnt played along it could have gotten cult spotted.

**Steps to reproduce the problem**:
Races involved. Invokers Shawna Lupix. Vulpkanin. Meek, a Grey. 
Victim. Tokorizo, Vox.
We had placed Toko onto the binding rune, which was under a table. Me and Meek stood next to it, and when pressed the rune it complained of us not having enough invokers. 
If place matters the rune was under the monkey box in xenobio(same spot where it spawns.) and me and meek were on the chairs left of it.

**When did the problem start happening**:
The cult round that happened at 12:15AM EST 8/26/2020 was when I noticed it.

**Extra information**:
We later tried to combined souls summon toko and it gave similar results of. Grey and Vulpkin not being able to summon toko.

### PR DESCRIPTION
**Pull request by SabreML**
I'm sure I can't be the only one who was pretty sad when the Blood Cult PR was closed, so I've decided to re-open it!
This is all exactly as it was left except for some deconflicting and bugfixes on my part, so hopefully it'll still be testmerge ready.
`Now includes balance changes too!`

I will note that I haven't read *all* of the new code (image**!!!**), so I'm not exactly an expert on it.
However, if any bugs are found that will stop this from getting merged, I'll do my best to fix them.

-SabreML

<i>P.S:
I'll try not to add any new features or change existing ones too much in this PR, since I don't want to end up stuck in development hell like the original seemed to be. Bugfixes and balancing only for now.</i>

<hr>

# ORIGINAL PULL REQUEST #13018 

This is the first of multiple PRs updating Paradise's cult to TG, with some alterations for our codebase.

Info on this PR and Blood Cult can be found on this updated temporary wiki page : [Blood Cult](https://www.paradisestation.org/wiki/index.php/User:DatKoyote)

`Re-opened version testmerged twice so far, on 2020/10/12 and 2020/10/26, with a whole bunch of bugs and issues found. This'll take a bit longer than expected to fix, but that's life!`

<details>
<summary><i><b>Known issues :</b></i></summary>

- [ ] The blood halo looks off when you are lying down, as it doesnt rotate properly.

- [x] Relogging as a cultist seems to remove your cult halo.

- [x] The 'reset action button location' function is currently *very* buggy with blood magic due to their unusual screen placement.

- [ ] Some of the tooltips for the spell buttons are very off-center. (Probably a screen resolution thing)

- [ ] The position of the cult spells intersects with your inventory sometimes.

- [x] No in-hand sprite for 'Blood Bolt Barrage'.

- [x] Blood Bolt Barrage produces blue sparks, when they should probably be red instead.

- [x] The cult blade (the long one) sprite clips through some player sprites. (Not *entirely* fixed, but a lot less noticable.)

- [ ] The Nar'Sie cult 'Altar' sprite has no visual differences when anchored/unanchored.

- [x] Inconsistent span classes. (I've got most of them at this point, I think)

- [x] Sacrificing a brain doesn't give a soul shard.

- [x] Cultists can walk over activated shield runes. (Probably hopefull maybe fixed?) (Not fixed) (Actually fixed now!)

- [x] Converting an IPC doesn't heal them. (Possibly an oldcrit thing, and probably also broken for prosthetics)

- [x] Manifest runes can be placed during the Nar'Sie rune drawing timer. (Needs testing)

- [x] Mirror shield doesn't break when hit with lethal weapons, including ERT weapons. (Possibly make it break on drop?)
(Needs testing)

- [x] Mirror shield is far too OP in general. (Fixed!) [***citation needed***]

- [x] Stun spell duration is *far* too long at around 20 seconds! (Halved all time values since the procs are actually in lifecycles, I haven't changed the times other than that.)

- [x] Cult slurring after being converted is probably also too long. (See above)

- [x] Reviving a cultist might offer the body to ghosts without giving the original owner a chance to re-enter. (Unable to test locally, but the code looks fine.)

- [x] Flagellant Robe seems too powerful with not enough downsides.

- [x] The Blood Boil rune is too powerful in its current form. (Needs testing)

- [x] Converting someone doesn't always heal them. (May have something to do with proximity?) (Unable to reproduce)

- [x] Deconverted cultists seem to be able to wear cult items without issue. (Maybe make them unequip on deconversion?)
(I've decided that this isn't really an issue, since people who keep the armour on will just end up getting validhunted.)

- [x] The threshold for cult ascendance (Halos and KoS order) is currently too low, and there's no way of telling when it'll happen.

- [x] IPCs drawing runes seems to make them red, when they should probably be black instead. (Oil rather than blood)

- [ ] Blood halberds can't be sharpened. (Currently can't find a way to fix this without refactoring whetstones entirely or nerfing the halberd.)

- [x] Admin rejuvenate / legion cores give out cult sparks when used on cultists. (Unintended, but only happens if they have a halo so it won't exactly blow their cover.)

- [x] Sacrificing a body can give multiple soul shards in some situations.

- [x] A few issues with the 'Check Antagonists' admin panel.

- [x] Juggernaut nightvision is a bit bugged.

- [x] Crayon runes still use the old sprites.

- [x] CC announcement at ascension still says "Half".

- [x] Cult related 'Tips of the round' need to be updated.

- [x] Zealots blindfolds still work even when deconverted.

- [x] Clicking on yourself with a soulshard gives you the option to capture your own soul.

- [x] Various small text errors (Grammar, span class, etc.)

- [x] Erasing a telerune during the portal animation removes the location notice.

- [x] Space telerune portals don't always point towards the Z level.

- [x] Admins offering a cultist to ghosts breaks blood spells.

- [x] Cultist deconversion message is too small.

- [x] Cultists don't show on the antaghud orbit menu.

- [x] Cultists become temporarily invisible when teleporting other people through a rune.

- [x] Runes made by slime people don't leave any DNA.

</details>
<hr>

Many thanks to Darkmight for starting the work on this and passing it to me, to McRamon for his rune sprites, to Dogs for the cult hud idon, to Robustin from TG for making Blood magic, and all other TG contributors who updated cult on their codebase.

Main features :

* Cult objectives were refactored from scratch, to use proper objectives and be less... legacy in general. Added a new cultist action to check your cult objectives.
* Cult goals are now always 1. Sacrifice target 2. Sacrifice 2nd target 3. Summon god. This means the slaughter demon objective and rune are gone. To be possibly re-added in a later PR. The amount of sacrifices required can be changed by admins.
* The arcane tome was replaced by the Cult Dagger. This is mostly a thematic shift, most of the tome's functions are now present in the dagger. This is because...
* Talismans were completely removed and replaced with blood magic. Roundstart cultist now start with 10 runed metal instead of a supply talisman.
  See https://tgstation13.org/wiki/Blood_Cult#Blood_Spells for details on blood magic. All spells implemented, with the exception of Blood Rites' blood beam
* The station is now informed of the Summoning location when a Tear Reality rune starts being drawn. Make sure you're prepared to fend them off! Barrier and blood boil runes are good for that.
* Cult Ascendance: At 10-20 percent of the station population, the cult will Rise: All cultists will get a warning that their eyes are starting to glow. After a minute, all cultists eyes, present and future, turn red, and show as a warning on examine if your eyes aren't covered.

image

* At 20-30 percent, the cult will get a warning and after a minute, it will Ascend: All cultists, present and future, will get a red halo that you are unable to hide. Central will also inform security of the present threat and authorise lethal force.

image

image

* Added the Mirror Shield. Protects similarly to a riot shield while reflecting blocked energy shots and creating illusions when hit. Can be shattered using high damage projectiles such as .357 revolver rounds, shotgun slugs, solar laser cannon/pulse rifle shots.
* Zealot blindfold now gives a medhud on top of flashprotection and nightvision.

<details>
<summary> <i>Rune updates:</i> </summary>

- Runes were updated to TG. New sprites were made for them, see below.
See https://tgstation13.org/wiki/Blood_Cult#Runes for details on rune functions, some of which modified to fit the server better.
The apocalypse rune is not implemented in this PR.
Notable changes :

- Teleport rune now reveals the location of space/lavaland bases if teleported from them. See screenshot.

- Offer rune now heals most of the convertee damage, aswell as bone breaks, IB, and crit conditions. They are also uncuffed.

- Talisman rune changed to Empowering rune, which lets you carve blood spells at a much lesser cost and carry up to 4 of them from a single one without rune.

- Barrier rune can now be destroyed with brute force. Will be more clear if they are activated or not.

- Summoning rune now always require two cultists to rescue a cultist, but CAN ONLY BE USED ON THE MAIN STATION. **Is unable to rescue cultists being dragged in cuffs by security or bucklecuffed.**

- Spirit realm rune now handle both ghosting yourself and manifesting ghosts. Manifesting ghosts CAN ONLY BE DONE ON THE MAIN STATION. The amount of ghosts is limited to 4 maximum, minus one for each objective accomplished, with a minimum of 2 ghosts possible.

- Blood boil rune: No longer blows up the invoker using it. Now deals 30 burn damage to non-cultists in view over a short period of time and ignites them. Requires 2 invokers to be constantly channeling.

- Narsie rune: Will now reveal the cultist's location when you start scribing, but deal much less damage (shouldnt break bones/cause IB anymore). Be prepared when you start the ritual! Barrier runes are helpful for this.

- You can no longer draw runes on the tiles occupied by the narsie rune. Combined with the 2 ghost maximum restriction of spirit realm, this means you need at least 5 real cultists/constructs to summon narsie.
</details>
<hr>
<details>
<summary><i>Cult structure rebalance:</i></summary>

- Pylon no longer converts turfs when built on the station level, and has less noticeable lights. This is to encourage stealthy onstation cult bases, especially combined with the new Conceal Presence spell.

- Pylon now slowly restore blood on top of healing cultists. Still costs 4 runed metal.

- Forge, altar and archives now all cost 3 runed metal to make the following items :
Forge - Shielded robes, Flagellant robes, Mirror shield
Altar - Whetstone, Construct Shell, Unholy Water Flask
Archives - Zealot Blindfold, Veil Shifter, Shuttle Curse

- Cult girders and walls are now very quick to build. Still costs 1 runed metal each (so 2 for a full wall)

- Cult airlocks can now be built for free using the Twisted Construction spell on an existing airlock. They will be weaker than airlocks built with runed metal.

- *All* cult structures can be completely hidden with the Conceal Presence spell. Airlocks will look and act as normal airlocks, but will deny access to non-cultists.
</details>
<hr>
<details>
<summary> <i>Soulshard updates:</i></summary>

- Chaplain now starts with a blue soulshard, creating holy shades/constructs. This avoids confusion between an antag item and a crew item, since cult items are illegal now.

- Crewmembers can now purify soulshards using a bible, turning them into blue purified soulshards, and unculting any shades trapped within. These purified shards work similarly to the chaplain's, you cant force unwilling souls into them if they are empty, and they cant be used to trap cultist shades.

- Cultists can undo this with their ritual dagger, cleansing the shard back to normal.

- Fixed bugs causing shades to be invincible sometimes.

- Fixed various bugs/inconsistencies with soulstones in general

- Shades can no longer pull mobs, but can spacewalk

- Shades are now properly cultists if sharded by a cultist, or mindslaved if sharded by anybody else

- Shades now have universal speak, so they can speak and understand others

- Refactored the soulstone to remove the god awful menu and just make it release the shade on use

- Admins can now turn constructs and other simple animals into cultists via traitor panel, if they have a mind attached to the mob.
</details>
<hr>

- Many new sprites and animations, most from TG with some provided by Darkmight, and rune sprites provided by McRamon

- Various small tweaks to improve cult flow and gameplay.

- Bug fixes.

<details>
<summary><i> Screenshots (Cult hud icon has been updated, see above for new one): </i></summary>

- A cult base in arrival office.
image

- The same cult base after a cast of Conceal Presence. The structures are invisible and can be walked through but are not functional. They can be revealed with a chaplain's bible (by the chappy only)
image

- A teleport rune with a space tear. This reveals the location of the cult's space base for one minute after teleportation.
image
image

- An offstation cult base.
image

- New rune sprites. Color is based off mob blood, except slime people who have it based on their body color (they use internal fluids to draw the rune)
While this lets you narrow down who drew the rune, keep in mind you can already DNA scan a rune for an exact match, and this PR massively improves your ability to hide your cult runes/structures.
NSS Cyberiad 2020-10-13 215821

</details>
<hr>

Fixes: #11307
Fixes: #10958
Fixes: #10402
Fixes: #8070 (Working as intended)
Fixes: #6089
Fixes: #8833
Fixes: #11275
Fixes: #2799
Fixes: #14132
Fixes: #14150
Fixes: #14510 (Unable to reproduce)
Fixes: #14393 
Fixes: #13855

:cl: Three Point Fourteen & SabreML
add: Complete overhaul/update of the cult gamemode.
add: Added cult blood magic and the cult dagger, replacing the tome.
add: Cult ascendance. At ~10% of the crew population converted, cultists will have their eyes start glowing red. This can be hidden with glasses or face covering like a gas mask. At ~30%, cultists will gain a red halo that obviously marks them as cultists.
add: Added the Mirror Shield. Forged at a cult forge. Protects like a riot shield with a chance to reflect, and summons illusions of the cultist when you block.
add: Zealot blindfold now also provides a medhud on top of nightvision and flash protection.

del: Removed talismans and the cult arcane tome.
del: Removed cultist hardsuit and the old cultist dagger.

tweak: Cult objectives are now always sacrifice two crewmembers, then summon their god.
tweak: The station is now informed of the cult's summoning location once the tear reality rune starts being drawn. Make sure you're prepared for the final fight.
tweak: Cultists can now tell how many members they currently have by using the 'Study the Veil' action. This shows the number of Cultists and Constructs, and also how many conversions are required until Rise/Ascension.
tweak: Cult structures costs and items provided have been rebalanced.
tweak: Rune costs and strength have been rebalanced.
tweak: Offstation cult bases have been nerfed. You can no longer manifest ghosts off station. You can no longer summon cultist from offstation. Teleporting in and out of the station is still possible, but will now create a tear above the rune that reveals the location of your offstation base for one minute after arrival.
tweak: You can no longer summon cultist being dragged in cuffs, or bucklecuffed. Security no longer needs to lethal competent cult on sight because they just teleported away if you didnt.
tweak: Pylons no longer convert floors and walls when built on the station. This allows for stealthy cult bases onstation especially combined with the new concealed presence spell.
tweak: Chaplain now starts with a blue purified soul shard.
tweak: You can now purify soul shards using bibles. Any crewmember can do this. Purified shades/constructs work for the crew against the cult.
tweak: Cultists can reverse this with their ritual dagger, turning soul shards back to the cult side.
tweak: Disabled the alternate construct names for Fire and Death cults, since they were a bit confusing.

fix: Fixed many cult bugs, especially related to objectives.
fix: Slaughter demons can no longer blood crawl in oil tracks.

imageadd: Added new sprites and animations for cult spells, items, runes and features. Thanks to Darkmight, McRamon, Drakeven, Kugamo and tgstation contributors!
/:cl:

### CODE REVIEW

**Comment by Cocacolagua** [comment]
woo

**Comment by shmabuu** [comment]
yahoo

**Comment by McRamon** [comment]
oh alright.  if its getting reopened, i need to finish the cult swords/daggers and send them to you, as well as new hud icon

**Comment by SabreML** [comment]
> oh alright. if its getting reopened, i need to finish the cult swords/daggers and send them to you, as well as new hud icon

There's individual dagger sprites for all three cults already, if that's what you mean.
Only one for swords though

**Comment by Necaladun** [comment]
@Kyep  has done most of the tests of this so I'd like his opinion on how it goes

**Comment by Kyep** [comment]
@Necaladun 
I'm not sure my old opinion is still valid. While there were issues I observed (it makes cult game mode much faster) some of those are just my personal preferences, and I believe the PR was updated after I explained them, so they may not even apply anymore.

I'd really like at least one, if not 2 or 3, new TM rounds of this, so I (and anyone else interested) can form an opinion given the current state of the PR.

**Comment by PacifistDalek** [comment]
"Admins can now turn constructs and other simple animals into cultists via traitor panel, if they have a mind attached to the mob."

Cultist Ian!

**Review by Kyep — COMMENTED** [review]
Having TM'ed this for 3 rounds today:
- As it stands, I think its an improvement over old cult.
- That said, I do think mirror shields, and potentially conversion speed, are still very strong, and potentially overpowered compared to old cult.

**Comment by AzuleUtama** [comment]
Some thoughts from the TM:

- Gamemode looks much more fun and easier to get into than current cult.
- Much faster-paced and had people making bases on station rather than in the middle of space.
- Mirror shield is extremely strong to the point where every cultist had it and was immune to the majority of Sec's and ERT's armory.
- The Stun spell lasts quite a long time and was used for both capturing converts and attacking people in open combat. Could do with being brought down to the same level as vampire or ebow's stun length since it's much longer than that right now.

**Comment by SabreML** [comment]
Updated the 'Known Issues' section with most of the stuff I found.
I'll start work on it tomorrow since it's midnight right now, and sleep is good.

**Comment by EmilyFontaine** [comment]
Any chance of adding the Cult Master? Less so for the powers, more so to give cultists an actual leader with big, fat, bold text that will make even the baldest man think "I should listen to this person."

**Comment by SabreML** [comment]
> Any chance of adding the Cult Master? Less so for the powers, more so to give cultists an actual leader with big, fat, bold text that will make even the baldest man think "I should listen to this person."

@EmilyFontaine 
I'd definitely like to see that at some point, but I'm trying not to add any more features to *this* PR at the moment, if only to speed up the development/review process.
When/if this gets merged, then definitely. If not from me then from someone else.

**Review by Kyep — APPROVED** [review]

**Comment by Kiyahitayika** [comment]
I dislike cult rounds when I am converted into playing cult. I really dislike them. That said, during the test merge, I had an easier time figuring out what to do and how to do it. I clicked on some new icons and it was much more straight-forward for a newbie like me. I really appreciate what was done here. Thank you!

**Comment by Tailiik** [comment]
The halos appearing over your head based on converts when you have no mechanical way of knowing how many people are converted is annoying. I had only worked on a healing virus and a fake virus to bait security with when all of a sudden my SHOOT ME IN THE FACE icon appears over my head in front of a sec officer without warning.

Alsooooo, the "validate my parking" sticker disappeared when I closed the game and logged back in to fix the chat not loading glitch.

**Comment by SabreML** [comment]
I'm gonna go to sleep now because
image
I'll add everything I noticed to the known bugs section tomorrow, and start working on them.

**Comment by TheMaveran** [comment]
@Tailiik A common misconception is that the shield rune is new, it was in paper cult. However in that version the wall and rune were completely invisible, confusing foe newer cultists but technically more powerful.

**Comment by iantine** [comment]
I used Rune of the Spirit Realm to ascend as a Dark Spirit whilst the cult was in 20% - eye glow mode - and returned to my body when cult was in 40% - halo mode - and my action buttons for Blood Magic and rune-drawing had vanished; I needed to use my dagger in-hand to draw a rune. Not particularly gamebreaking, but figured it's worth reporting nonetheless.

**Comment by Kiyahitayika** [comment]
@SabreML The most underrated part of this PR is the fact that the library computer can now print a dagger xD 
I was looking something up, searching for the word "frozen" in the Paradise codebase. I was like, "Hey, wait a minute!" x3 
Love this x3 <3

**Pull request merged**
