### PR TITLE
Virology Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just some viro tweaks from TG

- resolves potential runtime with choking
- Sensory restoration nerfed; it no longer has anti-stun properties and no longer heals brain damage, but has a lower acquisition level
- Damage converter heals specific limbs instead of healing overall damage (actual impact difference? Not so much)

:cl: Fox McCloud
tweak: Sensory restoration virology symptom no longer has anti-stun properties nor heals brain damage, but has a lower acquisition level
tweak: Damage convert heals individual limbs instead of healing overall damage (actual impact is low)
/:cl:

### CODE REVIEW

**Comment by MarsM0nd** [comment]
A small oversight: Synaptizine heals brain dammage, synaphydramine does not, but it's not listed in the changelog that the brain healing property from sensory restoration gets removed.

**Comment by KingPhilipIII** [comment]
Personally I look forward to unstunnables due to their virus.

**Comment by Ssirius** [comment]
I have no problem with healing viruses, but stun resistance (with no drawbacks) + healing is just way too much especially due to the fact how they get handed out like pre nerf genetics did.

:+1:

**Comment by Crazylemon64** [comment]
Sensory restoration still heals brain damage - mannitol is one of the chems it applies

**Pull request merged**
