### PR TITLE
Adds a fluff item for ComputerlessCitizen

### PR DESCRIPTION
**Pull request by FlattestGuitar**
In-Game name of the item: Dusty Jacket
Description on the item in-game: A worn leather jacket. Some burn holes have been patched.
What the item does: It's a jacket, for the exosuit slot. It can be worn. Does nothing else.
Your byond key: ComputerlessCitizen
The name of the character you want to have the item: Screech
The specific jobs you want the character to have the item for: All, if possible? Otherwise, only Mechanic.
Donation made via patreon.

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
:ok_hand:

**Comment by Computerless** [comment]
Thank you very much.

**Comment by Fox-McCloud** [comment]
Conflicts. The worst kinda too....sprite conflicts...

**Comment by FlattestGuitar** [comment]
OH FOR THE LOVE OF ALL THAT IS HOLY

**Comment by FlattestGuitar** [comment]
I hope you're proud of yourselves, merge conflict leprechauns.

**Pull request merged**
