### PR TITLE
pAI advertisements!

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
Here's a thought I had about an immersion friendly(tm) way of advertising availability of pAIs now that OOC is gone.

This gives observers and ghosts who can't re-enter their corpse who have the pAI option enabled a spell that will cause newscasters to broadcast "Advertisement: New pAI personality available! Download yours today!"

It currently has a cooldown of 10 minutes, and is restricted to those who can't re-enter your corpse cause re-entering and exiting your corpse resets the cooldown on your spells.

This is just a rough idea. There may be other ways like having a thing with a shared cooldown among all ghosts or something to avoid spam.

:cl: .Tayyyyyyy
add: Observers who have pAI enabled have a spell to broadcast their availability on newscasters
/:cl:

### CODE REVIEW

**Comment by theColdflame** [comment]
i suspect giving dead people a prominent  button to mildly annoy the living won't pan out too well, making this a little more effort to.trigger would probably be wise

**Comment by Tayyyyyyy** [comment]
Before this it was OOC. I will add a confirmation button to it, however. I forgot to do that.

**Comment by theColdflame** [comment]
I'm moreso staying there's no reason *not* to click this whenever it's off cooldown, even if you have no intent on playing pAI. People doing mildly annoying stuff for no other reason than 'I can' is a time honoured ss13 tradition.

**Comment by Citinited** [comment]
How about a `toggle pAI availability` verb that makes a red light flash on unoccupied pAIs? So if a pAI is flashing you know at least one ghost is available

**Comment by Fox-McCloud** [comment]
>How about a toggle pAI availability verb that makes a red light flash on unoccupied pAIs? So if a pAI is flashing you know at least one ghost is available

This is a lot better idea. It's more in flow with how things function, and it only annoys the people who precisely won't be annoyed by it.

**Comment by ktoma36** [comment]
The problem with making it only indicate the availability of a PAI on the sprite is that there are only two PAI's that spawn roundstart, and one of those is in the RD's office. Most people will not go get a PAI unless they know someone wants to become one, and the only way to get one outside those two roundstart PAI is through science which while they are cheep to make it still means waiting around for a scientist to print one out. 

Maybe it would be better if it was an alert on a newscaster, like job openings. The newscaster could send out an alert that a PAI is available when someone opts into it. If the person opts out there can be a ten minute cooldown like the mouse role

**Comment by lazerbear7** [comment]
> Maybe it would be better if it was an alert on a newscaster, like job openings. The newscaster could send out an alert that a PAI is available when someone opts into it. If the person opts out there can be a ten minute cooldown like the mouse role <

sending one newscaster message for every pAI that signs up is going to be too easy to miss.  I think a better way to do it would be to have newscasters repeat the "pAI available" message or whatever every ten or fifteen minutes, so long as there are personalities for download.  Additionally I think the message should include something about where you can acquire a pAI.  This avoids people who might want a pAI simply missing the message, or not knowing where to get one.

**Comment by Citinited** [comment]
`The problem with making it only indicate the availability of a PAI on the sprite is that there are only two PAI's that spawn roundstart, and one of those is in the RD's office. Most people will not go get a PAI unless they know someone wants to become one...`

In that case you could either a) map in more pAIs; or b) have an opt-in function on PDAs that messages you if a notification becomes available. There are plenty of ways to do it without broadcasting to everyone on the station about a pAI

**Comment by Citinited** [comment]
`The problem with making it only indicate the availability of a PAI on the sprite is that there are only two PAI's that spawn roundstart, and one of those is in the RD's office. Most people will not go get a PAI unless they know someone wants to become one...`

In that case you could either a) map in more pAIs; or b) have an opt-in function on PDAs that messages you if a personality becomes available. There are plenty of ways to do it without broadcasting to everyone on the station about a pAI

**Comment by Vivalas** [comment]
I think it should have no cooldown and just be a one-off thing, combined with the red light idea.

**Comment by Kyep** [comment]
Just make it so that double-clicking a pAI card in-hand offers ghosts a choice/prompt to join as your pAI. Oh, and before prompting ghosts, it should ask YOU (the human using the pAI card) what sort of pAI you want, and give ghosts that information so they can make an informed choice about whether they want to sign up as your pAI or not.

E.g: Joe double-clicks pAI, gets asked what kind of pAI he wants (from a few presets, like 'companion', 'door hacker', etc) and ghosts are then offered 'You you wish to play as the (companion) pAI of (character)?". 

All the fuss about custom pAI descriptions don't really serve to add anything - all the existing process does is make it less likely that anyone will get a pAI.

**Comment by Spacemanspark** [comment]
As long as the prompt remains in the chat box instead of a damn popup

**Comment by Crazylemon64** [comment]
We've decided to close this PR - as it stands, it's another vector for ghosts to harass the crew. An acceptable alternative would be to have a "blinking light" on the pAI card itself.

**Pull request closed without merging**
