### PR TITLE
Makes the old Brig Physician space into a new Prisoner Lockers Room (Cyberiad)

### PR DESCRIPTION
**Pull request by Quantum-M**
## What Does This PR Do

Moves the Prisoner locker room, leaving a small break area behind, to the space that used to contain the Brig Physician's room, making more spacious and with extra lockers.

## Why It's Good For The Game

Deals with that very awkward looking space left when the Brig Physician was removed, along with giving extra prisoners locker and making it easier to move around for Security when permabrigging (or sending to the labor camp) prisoners.

## Images of changes

<b>Before:</b>
image
<b>After</b>
image
## Changelog
:cl: Quantum-M
tweak: Makes the old Brig Physician space into a new Prisoner Locker room.
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
I like this, it also gives antags a chance to steal their shit back if it gets put in the prison lockers.

**Comment by BakKeener** [comment]
also lets them do a sneaky and pull prisoners out of the left solitary cell from space if someone gets put in them and effectively the right one if they move quick enough.

**Comment by Miraviel** [comment]
I love this and tested it - found no particular issues at all!

I am not sure if it is intended, but this intercom has no access to the "Security" frequency, only "Security(I)".
image

If you are taking suggestions, I would place a vent-scrubber pairing here as the next one is rather far, but I understand it ruins the prettiness of this lil' corner. I think it is great with or without.

No issues here, just an in-game screenshot of the room on red alert (well-lit without ten light tubes, good stuff!!):
image

**Comment by atteria** [comment]
> it also gives antags a chance to steal their shit back if it gets put in the prison lockers.

This actually makes it harder to steal from prisoner lockers for most prison escapees, unless they have a space suit. This is because the room is much closer to the epicenter of brig activity and very visible. The old locker room is only visible if you are heading to perma, the labor camp, or looking over into IAA from the brig hall. All of which are uncommon activities.

A raid on this locker room is easily noticeable by anyone looking into the Warden's office, simply entering Sec from the left side, entering or exiting the receptionist's to set a record, etc.

**Comment by matttheficus** [comment]
To be fair, the only thing that should be in these lockers are clothing and non-contraband, so raiding it is kinda pointless when your scary tot gear should be in Evidence.

Definitely love the change, uses up a hole in the Brig's layout and gives some more room in the locker room.

**Comment by Quantum-M** [comment]
Added a additional vent and scrubber to the end of that hallway.

As for the intercom, the Brig is has that type of intercom around the place, and figured it wouldn't stand off if added to that small corner, @Miraviel

**Comment by Miraviel** [comment]
> Added a additional vent and scrubber to the end of that hallway.
> 
> As for the intercom, the Brig has that type of intercom around the place, and figured it wouldn't stand off if added to that small corner, @Miraviel

Lovely!

No-no, that intercom is at an absolutely great spot! I was just wondering if it was the right type, because I walked to the east side of the corridor, and the intercoms there have Common, Security, and Security(I) as their channels.

**Comment by Quantum-M** [comment]
Moved the scrubber, lights, and wired the windows, @dearmochi 

I recommend against moving the holopad, as it would end up on top of some scrubber pipes and the wire, making it harder for repairs/tracking them with a t-ray scanner.

**Comment by dearmochi** [comment]
image

That's hardly obscuring the pipes, and holopads can be wrenched away.

**Comment by AffectedArc07** [comment]
After a discussion within server leadership, we have decided to halt your PRs due to your use of multiple ckeys without informing server administration

```

Using multiple accounts for yourself during a round (Multikeying) is not allowed. Simply having multiple accounts, by itself, is permitted - but we require you to inform us so we can add a note that these accounts are both yours.
```

This block will be removed once the server administration have been informed of your alternative ckey.

**Comment by AffectedArc07** [comment]
Info has since been added. PR block removed.

**Comment by Quantum-M** [comment]
Holopad moved to the east as requested, @dearmochi

**Comment by dearmochi** [comment]
Vent needs nudging north for the sake of symmetry.

**Comment by Quantum-M** [comment]
Vent moved to be opposite of the scrubbers, @dearmochi

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
