### PR TITLE
Adds 'Gateway Explorer'

### PR DESCRIPTION
**Pull request by razekpraxis**
Adds 'Gateway Explorer' to Scientist titles and gives them EVA and Gateway access.

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
Did this not already exist? :+1:

**Comment by Spacemanspark** [comment]
Yes.

**Comment by FlattestGuitar** [comment]
Let's make science just this bit more powerful.

Generally assistants find something to get occupied with by becoming explorers, this takes it away from them, so a :-1: from me.

**Comment by theColdflame** [comment]
isn't this an objectively advantageous pick over scientist?

a separate job or forfeiting some other sci access in trade would work better here

**Comment by Rumiluntti** [comment]
Giving a scientist EVA access? How about no, we just got rid of the excavation suits

**Comment by TheDZD** [comment]
:-1: 
Science does not need yet more access, especially not EVA access.

**Comment by DaveTheHeadcrab** [comment]
God why. :-1:

**Comment by razekpraxis** [comment]
Alright jesus. I only made it science because it's a science job.

**Comment by Spacemanspark** [comment]
Really though, we should have some kind of job dedicated to gateway stuff.
Spelunker, perhaps?

**Comment by razekpraxis** [comment]
That's already a think. It's the same as shaft miner.

**Comment by Spacemanspark** [comment]
I know, I was suggesting adding the access to that.

**Comment by razekpraxis** [comment]
But then that defeats the entire purpose of having a Gateway Explorer job to begin with.

**Comment by Spacemanspark** [comment]
The spelunker would function as a gateway explorer type dude if they wanted to, or go mining.

**Comment by razekpraxis** [comment]
Hm. Okay I see where you're going with this. One second.

**Pull request closed without merging**
