### PR TITLE
Face the thing you are pulling

### PR DESCRIPTION
**Pull request by Ty-Omaha**
This makes you face the thing you are pulling / grabbing.
This also makes you slightly slower when pulling because running at full speed backwards makes no sense.

Pulling the roller bed, wheelchair, IV drips, janitorial cart, (things with wheels generally) or objects you can pickup will still allow you to move at 100% speed

Not pulling
https://streamable.com/h6c1c

Pulling
https://streamable.com/ky0vx

:cl:
add:You will now face the direction of a thing you are pulling / grabbing.
tweak: When pulling something you are slightly slower. Roller beds, janitorial carts, and things with wheels are not affected.
/ :cl:

### CODE REVIEW

**Comment by Aquilar** [comment]
could make it so if your pulling a roller bed your moving at full speed?

**Comment by Ty-Omaha** [comment]
Good idea, I will

**Comment by Carthusia** [comment]
I get the slower speed pull, though if its a 1 handed pull, the point can be made that their walking forward, while pulling them from behind.

Perhaps if you one hand pull, you get half speed, without orientation, if you two hand pull, you get a higher speed, and face the object your pulling.

Rollerbeds, wheelchairs and such items remain full speed pulling

Example Photo: https://gentlemint-media.s3.amazonaws.com/images/2013/05/18/0daaa2d9.png.563x405_q85_crop-smart_upscale.png

**Comment by datlo** [comment]
It's about time speed while pulling was nerfed.

**Comment by Darkmight9** [comment]
Pull trains are gonna look really weird if the facing thing remains in

**Comment by taukausanake** [comment]
I like this but don't make everything that isn't a roller bed do this. Things that would naturally be roller like office chairs or some of the closet/crate things (I recall a dumpster thing at one point) and the various carts that the janitor and chef can use. If they have wheels then then shouldn't be affected

**Comment by MRgaty** [comment]
I dont like this, pulling people out of places fast enough so they either dont wake up or die before reaching the place needed. 
I dont see why pulling stuff needs a nerf, grabbing is already a pain because people pressing any direction even when stunned AND cuffed prevents you from grabbing tbem and newcrit makes you unable to punch someone unconcious without literally killing them.
Even if this just applies to closets and such, I still see this unnecessary in my personal opinion.

**Comment by Mitchs98** [comment]
Agreeing with Gaty. This change seems entirely unwarranted and not needed. I wouldn't really consider anything to do with pulling needing to be nerfed or otherwise 'overpowered'. If this is just a change for 'realism' sake then I further don't see a reason for it. Sure, we have some realistic aspects and do need some realistic aspects here and there it's a roleplaying game. But as I often say and will stand by gameplay > realism.

I don't see how lowering the speed of pulling things/people will meaningfully make the game better in any possible way or affect things positively. The only thing this will do is make it harder for people to retrieve bodies, save people, drag criminals along, and etcetra. Overall a net negative rather than any kind of positive.

**Comment by datlo** [comment]
Yeah no pulling speed needs nerfing. Perhaps not exactly how this is implemented but it just does. Getting stunned, dragged and cut up by a sped up syndi with a dsword with people being utterly unable to rescue you is ridiculous. 

Suggestions : 
1. Cuffed people do not slow you down when dragged. This lets sec and antags keep dragging people fast but needs some time to apply cuffs, letting others rescue/interrupt the process.
2. If you have BOTH hands empty, you can still drag at the same speed as before. This lets paramedic/medical do rescues without having to carry a roller bed everywhere, but you will be slowed down if you apply healing in the mean time (For a very short time it wouldnt be a big issue.)

**Comment by Carthusia** [comment]
In hindsight, I gotta agree.

Why is this needed exactly?

I get that it makes sense in a way and is more realistic, but is it really required? Do we really need it? 

Ehhhh, feels like we don't? This also has the counter effect of making it take even longer for players who construct RP areas to move larger objects around that they have to pull and a multitude of other factors not accounted for in the original PR's writing.

Feels like a situation of "If its not broke, don't try to fix it"

**Comment by MRgaty** [comment]
Precisely WHY is this good for the game?

**Comment by Mitchs98** [comment]
> Yeah no pulling speed needs nerfing. Perhaps not exactly how this is implemented but it just does. Getting stunned, dragged and cut up by a sped up syndi with a dsword with people being utterly unable to rescue you is ridiculous.
> 
> Suggestion :
> If you have BOTH hands empty, you can still drag at the same speed as before.
> 
> This means that security and antags can still drag people in cuffs, but will be slowed if they harmbaton/esword them at the same time.
> 
> This also lets paramedic/medical do rescues without having to carry a roller bed everywhere, but you will be slowed down if you apply healing in the mean time (For a very short time it wouldnt be a big issue.)

Sounds more like a case of 'i ded pls nerf', genuinely. I'd accept that hands free thing as a compromise, maybe. But as Carthusia said it doesn't take into account people building areas or anything else that'll make it take a LOT longer to do so.

Even if that suggestion was accepted and used instead, I disagree with it making you face whatever you're dragging just on the grounds that it'd look weird. This portion sounds like a thing of 'TG did it so do we'.

**Comment by TDSSS** [comment]
I like this a lot. This is a good nerf to the stupid strategy of 'run up, stun baton once, pull and zoom away while constantly harmbatoning your victim' that leaves pursuers with no chance to catch up. Especially holopara users suffer from that a lot.

**Comment by Ty-Omaha** [comment]
I think many of you are comparing the slowdown to a grab slowdown. It's nowhere near as slow

**Comment by Carthusia** [comment]
Ty, is it possible to grab a gif to show the slowdown in action and one without so that we have a frame of reference to make further responses to?

Would help clear up some concerns we have.

**Comment by Ty-Omaha** [comment]
It's stutters because of the FPS limit on the gif

ezgif-1-f97ae42087f7
ezgif com-video-to-gif (2)

**Comment by Ty-Omaha** [comment]
Not pulling
https://streamable.com/h6c1c

Pulling
https://streamable.com/ky0vx

**Comment by Carthusia** [comment]
Oh, that's hardly noticeable for most people, slight reduction to account for in the event you want to commit a crime, but hardly an issue for anyone else.

Few things though:

Is it possible to separate the "Face towards object being pulled" aspect from large objects, and small.

So say, pulling a locker, you face towards it as shown, with speed reduction

Pulling along a person who is standing, you don't face them, and you don't reduce speed, as you are in essence just guiding them by holding their hand. Otherwise you'd have pull trains of people who are all floating backwards down the hall on their way to the departures lobby.

Pulling a body on the ground, speed reduction due to their KO'd nature, but the need for a face towards doesn't seem needed as pulling people by their collars "Or in the case of someone with body armor, the pull grip on the armor" with one hand to get them out danger is kind of standard in situations that require a pull.

**Comment by Fox-McCloud** [comment]
I don't like this much, at all---also means that pushing things is more viable than pulling things which just makes it finicky.

I especially don't like the "face the thing you're pulling". 

It just ends up making things look weird and awkward; I'm not going to drag a piece of paper or a pet while facing backwards.

TG has an entire system based upon this it was handled in a more nuanced manner---and they have the fireman carry to replace a lot of the changes--haven't seen that in action, it's kinda neat, but I'm not *exactly* a fan of it either.

**Comment by lolzyking** [comment]
Does this affect simple mobs pull speed?

**Comment by Birdtalon** [comment]
Really disagree with this. Pulling stuff and being able to move at normal speed is an integral part of gameplay especially when fighting/evading multiple people. Unnecessary, in my opinion.

**Comment by TDSSS** [comment]
I would say it's an integral part of gameplay that should be removed. Pulling things should come at a cost, a minor slowdown seems very appropriate.

**Comment by variableundefined** [comment]
Closing due to two maintainer objection

**Pull request closed without merging**
