### PR TITLE
Solars space sprite update. Adds new solar panels and catwalk

### PR DESCRIPTION
**Pull request by DogsParadise**
## What Does This PR Do
Changes solar panel sprites and catwalk sprite.
Lattice update is pr'd seperatly in: #15851

## Why It's Good For The Game
More consistent sprites.
Improved perspective at catwalk and such

## Images of changes
Before:
image

After:
image

## Changelog
:cl:
tweak: Solar and catwalk sprites
/:cl:

### CODE REVIEW

**Review by dearmochi — APPROVED** [review]

**Comment by procdrone** [comment]
sprites appear very good. 

are the new solar sprites supposed to be so bright? Or is that lighting thing

**Comment by DogsParadise** [comment]
> sprites appear very good.
> 
> are the new solar sprites supposed to be so bright? Or is that lighting thing

It's the lighting thing.

**Comment by DogsParadise** [comment]
I am closing this, i prefer my sprites not being merged in paradise atm.

**Comment by Spacemanspark** [comment]
Bye

**Pull request closed without merging**
