### PR TITLE
Пожалуйста добавьте очки Симона для капитона.

### PR DESCRIPTION
**Pull request by vanyvol**

### CODE REVIEW

**Comment by tigercat2000** [comment]
kek you did it the wrong way around

**Comment by LittleBigKid2000** [comment]
пить меньше водки

**Comment by Cotux34** [comment]
great stuff 10/10 would merge again

**Comment by vanyvol** [comment]
make merge great again

**Comment by TheDZD** [comment]
I think you might have pull requested this to the incorrect repo. Pull request should be targetted to [ITBlackwood/ATMTA-Paradise](https://github.com/ITBlackwood/ATMTA-Paradise), not ParadiseSS13/Paradise.

**Pull request closed without merging**
