### PR TITLE
Ports Citadel's Airlock Sounds.

### PR DESCRIPTION
**Pull request by razekpraxis**
What it says on the tin.

### CODE REVIEW

**Comment by razekpraxis** [comment]
i fucked up

**Comment by Fox-McCloud** [comment]
you included your previous PR into this one. Please don't do that :stuck_out_tongue:

**Comment by tigercat2000** [comment]
a. your other PR commits are in here too
b. these airlock sounds are awful :tiger:

**Comment by LiquidNightfury** [comment]
These sounds would making playing sec an unmitigated nightmare. If the sound was nice and we only had a few doors that used them it'd be fine, but the cacophony that Citadel doorsounds are makes me cri.

**Pull request closed without merging**
