### PR TITLE
(WIP) Isometric Spessmen

### PR DESCRIPTION
**Pull request by monster860**
Hello, it's me, the one the is *still* trying to make enormous visual changes to this server. (See: Spess Parallax, Animated Departures)

Still unfinished. Basically, 64x64 isometric sprites.

space station 13 2016-08-24 103429

space station 13 2016-08-24 093818

Sprites currently finished:
walls and r-walls
most floors
atmos pipes, cables
lattice, grilles, windows
most mobs and inhands

TODO:
- [ ] Yell at byond devs to fix rsc cache issues.
- [ ] Yell at byond devs to fix crashes.
- [ ] Make fullscreen shit not fuck up the view.
- [ ] Fix the layering problems
- [ ] Find a solution for walls blocking shit.

Sprites TODO:
- [ ] Doors.
- [ ] All the walls.
- [ ] Items.
- [ ] UI
- [ ] Wall-mounted objects (Will require map changes)
- [ ] Machines and structures (Most of them are using parallel projection, so a simple transform can make them isometric, but they will look really thin. Look at the safe in `structures.dmi` for an example)

### CODE REVIEW

**Comment by fludd12** [comment]
WHOA WHAT

**Comment by counterfeitguise** [comment]
can it be optional, isometric views make me nauseous

**Comment by fludd12** [comment]
Don't get me wrong, this is beautiful, but I can't imagine it's going to be accepted, just because it'll change quite a lot gameplay-wise.

It would be amazing for its own server, though, or an option like Counter said. I can't imagine the playerbase you'd get simply from this.

**Comment by Aurorablade** [comment]
No for here yes on your own server move along

**Comment by TheDZD** [comment]
Looks really cool, but not something that will likely be merged.

**Comment by Regen1** [comment]
Looks baller as fuck 

But i have no idea what we would use it for

**Comment by taukausanake** [comment]
I personally think this would go great on its own server and/or branch in the repository. This isn't something that can be ignored, but it can't be something merged into 2D spessman for that reason itself: 2D spessman.

If I have any issues with this is it the following: I feel I can get right up next to a wall, technically behind it sue to isometric view, and no one will see me. However you haven't made mob icons yet (good luck with that my friend) so maybe it's too soon to be an issue.

Again, love how this looks. It won't be something on the main server though

**Comment by monster860** [comment]
@taukausanake Actually, I have done all the mob icons, they are essentially paper-mario billboards though.

**Comment by taukausanake** [comment]
You leave me no choice but to set everything on fire then.

Speaking of such, how would that work out anyways? Gasses and fires and such

And no isometric spessmen, I'm disappointed. If you're going to go 3D go all the way, not some ripoff Paper Mario :P

**Comment by monster860** [comment]
I'm not an artist, I'm just someone that's fucking around with pieces of horribly-written java code.

**Comment by taukausanake** [comment]
Well granted this doesn't get merged keep it open on your repository. Maybe some others can update the icons for it until it's complete

**Comment by Fox-McCloud** [comment]
This is solidly in the realm of "never going to happen on Paradise", but it's still a neat concept.

**Comment by Taaketa** [comment]
This is neat. Keep working on it.

But yeah, not to paradise. It's just too much of a shift.

**Comment by PKPenguin321** [comment]
holy shit what the fuck
thats the coolest shit

**Comment by taukausanake** [comment]
Oh, and @monster860 you didn't comment about mobs hiding behind walls. They take up almost the whole icon directly above them. Won't that be an issue?

**Comment by monster860** [comment]
@taukausanake Human mobs might be able to hide while laying down, but I do plan to implement a solution to shit from hiding behind walls (possibly /image objects)

**Comment by HugoLuman** [comment]
By all means, though, continue developing this for any downstreams

**Pull request closed without merging**
