### PR TITLE
jacobs ladder removal from tendrils

### PR DESCRIPTION
**Pull request by hal9000PR**
## What Does This PR Do
removes jacob's ladder from tendrils

## Why It's Good For The Game
It is basically one use telescience. It can render an area useless such as perma. or you can raid the entire armoury with no counterplay. or instantly steal the AI.

Apparently it is also super hard for admins to remove, meaning it can be used for griefing fairly easily. such as placing it under perma and letting everyone out.

It also just breaks immersion. Its description is literarily `A celestial ladder that violates the laws of physics.` Its just silly and makes no sense.

## Changelog
:cl:
del: removes jacob's ladder from tendrils
/:cl:

### CODE REVIEW

**Comment by LordShekelstein** [comment]
Not sure why this doesn't have the controversial tag? 🤔

**Review by AffectedArc07 — APPROVED** [review]
Im ok with this

**Comment by Wojz** [comment]
No more cheesing syndie space base. Good riddance!

**Comment by Feasel** [comment]
No more shaft memes putting this in a public area and killing randoms who just started learning the game. 

10/10

**Comment by S34NW** [comment]
But with this gone how can I cheese the AI?

**Review by S34NW — APPROVED** [review]

**Comment by Spacemanspark** [comment]
About tome

**Review by Kyep — APPROVED** [review]
Its about damn time.
This item is incredibly stupid and should never have been added in the first place.

**Pull request merged**
