### PR TITLE
Adds sake to hacked booze dispenser

### PR DESCRIPTION
**Pull request by Landerlow**
🆑 
Add: Adds Sake to a hacked booze dispenser's menu.
/ 🆑

### CODE REVIEW

**Comment by Necaladun** [comment]
LGTM

**Comment by Anasari** [comment]
Onry the brest japanese rine

**Comment by KasparoVy** [comment]
*slams table. "SAKE!!"

Fantastic.

**Comment by Landerlow** [comment]
Merge please? :)

**Comment by tigercat2000** [comment]
👍 ❄️

**Pull request merged**
