### PR TITLE
Rework the fireaxe cabinet so it uses less sprites, and other tweaks

### PR DESCRIPTION
**Pull request by Vi3trice**
## What Does This PR Do
Due to how it's currently coded, the fireaxe cabinet uses 40 sprites, even though the vast majority of them are identical to each other, with probably the expectation that someone might come in and do new ones.

This cuts it down to just 16 sprites while making the naming scheme more sense. At the same time, an operating proc (Based on airlocks) is added to prevent spam or skipping animations.

If the cabinet is smashed, examining it will also state as such instead of still showing the multitool tip.

## Why It's Good For The Game
While the possibility of new sprites is still there, it's somewhat minor. The current sprites and naming scheme just added to confusion.

## Images of changes
FireaxeSprites
SmashedCabinet

## Changelog
:cl:
tweak: Smashed fireaxe cabinet no longer says to use the multitool to toggle it
fix: Fixed skipping/spamming animation on fireaxe cabinet
imagedel: Deleted 24 redundant sprites
/:cl:

### CODE REVIEW

**Comment by hal9000PR** [comment]
`tweak: Reworked the fireaxe cabinet to cut down on sprites` 
Not really a player focused changelog.

**Comment by S34NW** [comment]
Minor nitpick, could you arrange the sprites within the DMI so they are grouped logically? It helps when looking at the DMI file later

**Review by hal9000PR — COMMENTED** [review]
couldn't you make this use overlays to further reduce the amount of sprites?

**Comment by Vi3trice** [comment]
> couldn't you make this use overlays to further reduce the amount of sprites?

I'm not sure how I'd do that without making new sprites.

**Comment by S34NW** [comment]
> 
> 
> > couldn't you make this use overlays to further reduce the amount of sprites?
> 
> I'm not sure how I'd do that without making new sprites.

You can just cut out whats already there, basically.
Have the main sprite be the open empty cabinet, add an overlay for the axe if it is in there. Then an overlay for the door with different states for how damaged it is.

That way you don't need two sprites for each damage state (full and empty)

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
