### PR TITLE
[Feature][Refactor][Review Requested] Nutrient Changes and Dietary Concerns

### PR DESCRIPTION
**Pull request by FalseIncarnate**
<b>Nutrient Changes and Dietary Concerns</b>
Splits nutriment into 3 reagents: Protein, Nutriment, and Plant-matter. Every race now has a defined diet (except Diona and IPCs who don't get nutrition from food) which dictates what types of nutrient reagents that benefit them. Nutriment is considered a neutral type, and thus can be digested by carnivores, herbivores, and omnivores alike, while protein cannot be digested by herbivores and carnivores cannot digest plant-matter.

Regardless of diet, all three nutrients will metabolize out of the body safely, meaning you cannot become fat off of a steak if you are an herbivore. You only will gain the benefits of nutrition and slight healing from the nutrient types your species can digest.

Most of the kitchen-produced foods have been largely untouched, as have most vending machine foods. Vending machine jerky and the Admiral Yamato Carp have had their reagents adjusted to include protein, and 4noraisins have had their reagents switched to plant-matter to ensure that a dietary-friendly option will be available without botany or a chef. Since kitchen-produced foods inherit the reagents of their ingredients, few higher-level foods have been adjusted, while most ingredients such as botany produce and monkey meat have been updated to properly list plant-matter or protein as appropriate. Chef food will typically include at least 2 nutrient types.

<b>Breakdown of additions, changes, etc:</b>
- Adds Protein and Plant-matter reagents, nutritional values of 15
- Reduces nutritional value of Nutriment to 12, down from 15
- Adds new flag defines for racial diets, and new dietflags var to species
(must be set manually in the species definition, otherwise it will be
null)
- Assigns each species their respective diet's flag:
 - Carnivores: Unathi, Slime People
 - Omnivores: Human, Tajaran, Vox, Shadowpeople, Golems,
Plasmaman, Nucleation, Vox Armalis
 - Herbivores: Skrell, Kidan, Grey, Wryn
 - No Diet (null dietflag): Diona, IPC
- Adds checks to all nutrient on_mob_life procs to handle simple_animals
versus carbon/human mobs
 - Simple animals will heal from any nutrient source, but don't gain
nutritional value since they don't appear to deplete it
- Adds check to Nutriment on_mob_life proc to ensure that the diet for a
species has been set
 - Failure to set a diet flag will prevent the species from benefitting
from ANY nutrients, while metabolizing the reagents normally
 - This is largely for ensuring the species is properly defined
- Adds checks to Protein and Plant-matter on_mob_life procs to handle
incompatible diets
 - Ingesting Protein does not benefit Herbivores, but will metabolize out
of the body normally
 -Ingesting Plant-matter does not benefit Carnivores, but will metabolize
out of the body normally
- Initial update of food reagents to utilize new nutrient reagents
 - Food inherits the reagents of it's ingredients in almost every case, and then adds some additional nutriment to the product
- Fixes the blood tomato mutant list to actually allow mutation into
killer tomato.

<b>I would like to request at least one other person look through this and ensure I have not missed anything important and that it is largely bug-free before it is merged. I have done testing, but given the scope of the reagent changes, I would rather it be delayed slightly than merged feature-incomplete.</b>

### CODE REVIEW

**Comment by Keilden** [comment]
As cat people I would say that tajaran should be carnivores.

**Comment by ZomgPonies** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
I like this; if you integrate it with TG's overhauled nutritional system (which has satiety and fullness both), it'll be a pretty mechanically deep system that will really encourage players to utilize the chef over vending machines and to eat "good" food over junk.

**Comment by KasparoVy** [comment]
Awesome to see this lined up to be implemented

**Comment by TheDZD** [comment]
It'd probably be best to just have both DIET_HERB and DIET_CARN given to omnivorous races, rather than creating a specific flag for them.

**Comment by FalseIncarnate** [comment]
@TheDZD As I explained in the coder chat, the DIET_OMNI is so that we can potentially tweak things balance-wise for just carnivores or just herbivores without affecting omnivores.

Should we port TG's system like fox suggested, one potential use would to be making it so protein-heavy foods offer better satiety to only carnivores or plant-matter for herbivores, without affecting omnivores. Using both DIET_CARN and DIET_HERB for omnivores would over-complicate such adjustments.

**Pull request merged**
