### PR TITLE
Engine containment room atmospherics

### PR DESCRIPTION
**Pull request by Bram961**
Changes the airless and space turfs in the engine containment room to
normal plating so its pressurised.

This will cause the tesla engine to be completely hearable, right now
only half the sounds are hearable because the ball itself is in a
vacuum.

It also creates a much more open space to possibly build a supermatter
or something like that while running the station off off solars.

The singularity engine will ofcourse rip open the flooring and cause the
area to vent which causes a large patch of ice that fades after a few
minutes.
There are some concerns for lag here although a local server handled it
withouth an increase in lag.

### CODE REVIEW

**Comment by Bram961** [comment]
For completeness I forgot to mention that the warning stripes were relocated to surround the containment grid instead of the 3x3 area in the middle since it looked better that way.

**Comment by Earthdivine** [comment]
Pics!

**Comment by Bram961** [comment]
image

**Comment by Bram961** [comment]
https://www.youtube.com/watch?v=0B9duAPAcbg Video of what happens when you turn on the singularity. (extra pictures in the description about when the ice fades and whatnot)

**Comment by Fox-McCloud** [comment]
Not a big fan to be honest--it makes containment even more trivially piss easy to set up than it already is; also, it means the crew are going to be incessantly hearing "BANG BANG BANG BANG BANG BANG" every literally 2 seconds (and you can hear the bang from it from quite a ways).

The sound is nice, but it'll get old hearing it drone on and on for 2 hours shift after shift---not to mention it'll make crew lulled into a sense of artificial security from having to hear it all the time.

**Comment by Bram961** [comment]
@Fox-McCloud you're right I didn't take the range of the sound into account. Now that I tested it it is indeed hearable througouth engineering and the surgery ward as well, although it ends right there.
Pity the fact that the sounds aren't usually heared though.

Can't the range of the sound coming from it be decreased somehow?

**Comment by Fox-McCloud** [comment]
Yeah, range can be adjusted, but that also means people won't hear it well when it does legit escape too, so there's that.

**Comment by Bram961** [comment]
Than im closing this, the sounds can be heared when the thing gets loose anyway although that will probably never happen.

**Comment by Fox-McCloud** [comment]
Don't get me wrong; the sounds are *really* awesome---I love them--it really is great---just trying to weigh all factors here.

**Comment by Bram961** [comment]
Don't worry fox I get that completely. I'm a little sad that drool inducing spess noises don't get heared all that much but I do understand that standing in engineering or surgery with this is very irritating.
I feel sort of stupid for not weighing that in myself actually.

**Comment by Deanthelis** [comment]
Would it be possible for the containment field, when active, to dampen the noise it makes?

**Comment by Fox-McCloud** [comment]
@Deanthelis 

No, not without a dramatic overhaul to the sound system.

**Comment by CrAzYPiLoT-SS13** [comment]
What about some var that is true when the field is active and when it's true the sound_range and volume is decreased?

**Comment by Deanthelis** [comment]
@CrAzYPiLoT-SS13 Try it locally, if you think it'll work, and if so, maybe make a PR for it. That sort of code might come in handy for other devices, too.

**Pull request closed without merging**
