### PR TITLE
Paramedic EVA Resprite (Take 2)

### PR DESCRIPTION
**Pull request by Agameofscones**
**Since I managed to break my old PR while fixing the Transylvanian coat conflicts, I'm re-opening the branch at @Crazylemon64 suggestion after attempting to fix the original PR (to no avail)**

This PR is quite simple, in reviewing the various styles of space and or hard suits available in game,  the current Paramedic EVA gear noticeably does not match the style of all other NT EVAs (Excluding the voidsuits), and instead more closely resembles a recolored Syndicate Space Suit. I have gone and re-sprited the entire space suit using the original colors of the Paramedic's Vest, with the suit design being based heavily on the Medical hardsuit, with the helmet more closely resembling the original.

I have made sure to test the suit in game, and I have yet to notice any consistency or visual errors, however if there are any, do notify me so I might change the sprites.

image
image
image
image
image
image
image
image
image

All the dimensions for the species specific sprites were taken from other species specific hardsuits (Usually mining or the CE suit, since those were high contrast and easy to reference)

:cl: Triiodine (Agameofscones)
del: Removed original paramedic EVA sprites
add: Replaced paramedic EVA sprites with medical hardsuit inspired set.
add: Added species variants _(Which did not exist before hand)_ to Unathi, Tajaran, Drask, Skrells, & Vulpkanins.
add: Added the same armor values the basic EVA suit gets (bio 100, rad 20), this puts the paramedic suit in standard with other NT soft suits.
edit: Fixed a typo in the santasuit comment, because why not.
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
This engineer suit sprite has been modified and wasn't mentioned in your PR.

**Comment by FlattestGuitar** [comment]
Personally, I think the blue is far too deep for this. I'd make it more washed out than it is right now, it looks very off.

**Comment by Agameofscones** [comment]
@Birdtalon That's, actually weird, I didn't touch the ERT suits for drask, doesn't seem to have ACTUALLY changed, but, I'll just go and make it match master if it doesn't already.

**Comment by Birdtalon** [comment]
Yeah I figured it was just something weird.

**Pull request merged**
