### PR TITLE
The Great Engineering Rework

### PR DESCRIPTION
**Pull request by silverplatedelta**
## What Does This PR Do
1) Removes the atmospheric technician role
2) Adds the Maintenance technician role. Low hour requirement role that focuses on general maintenance issues around the station, including but not limited too: hacking vendors, unshocking things, assisting engineers with the power net, Configuring local SMES, and repairing station damage
3) Changes the station engineer role to also include the duties of atmospheric technicians (they aren't dead, just merged with engineers).  Station engineers/atmos techs will also work on the completion of station goals/department modules (to be added in future PRs).
4) Adds the Engine Technician role. At least one of these (or the CE) must be monitoring the engine at all times (see #21406 for why).
5) remaps all engineering departments to reflect the above role changes
6) Changes the primary method of generation from rad collectors to turbines, which after #21343 will produce just as much/more power than rad collectors, and require active monitoring/intervention by operators.

Posting this now to allow multi contributor drifting. Sorry for the third draft PR!

## Why It's Good For The Game
To address the elephant in the room, the merging of atmos techs and engineers is likely going to be quite a contentions change. Currently, the duties of atmospheric techs consist of: Change 2 pipes at roundstart, max four filters. Every single other duty can easily be completed by engineers with their provided access level. Outside of required duties, atmos techs are basically left alone in their area to experiment with the atmospherics system. While having no other duties and the freedom to experiment can be fun, its not a successful gameplay loop. 

The new roles address the void filled by the removal of each atmos techs as follows:
First, experienced engineers will be given the new Engine Tech role, to experiment and operate with engines and applied atmospherics. Second, newer engineers will be given access to atmospherics, allowing them to experiment on a whim, and not have to roll one in three spots to be allowed to play with the pipes for that round. Third, the new role Maintenance techs will fulfil the designated "antag/im going to go barRP" role with little expectations/duties. Finally, atmospheric technicians will be preserved as an alternate title for station engineers, with an atmosdrobe still in the department, allowing people to still play as atmos techs, simply without the exclusive access.

## Images of changes
TBD

## TO-DO
Finish cyberiad remap
Kerberos remap
cerberon remap
farragus remap
New sprites for roles

## Changelog
:cl:
add: Added new roles: Engine Tech, Maintenance Tech
del: Removed role: Atmos Tech (merged with standard engineer, now an alt title)
tweak: Remaps all four engineering departments
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
image

You're gonna have to do some serious convincing

**Comment by Probablyjay19** [comment]
⚠️ SOUL REMOVAL DETECTED ⚠️

**Comment by procdrone** [comment]
thats a big task you took upon yourself, did you even ask a single head of staff if the changes are desirable? If not, you probably wasted all of that time it took to code and map this, because, yeah, I just can't see this being wanted by anyone.

**Comment by DGamerL** [comment]
> thats a big task you took upon yourself, did you even ask a single head of staff if the changes are desirable? If not, you probably wasted all of that time it took to code and map this, because, yeah, I just can't see this being wanted by anyone.

If you don't see it, you're the outlier. It has been approved already.

**Comment by procdrone** [comment]
> If you don't see it, you're the outlier. It has been approved already.

if it was preapproved, that's all good. (simply seemed like a radical change to me, not that I feel one way or another). My apologies then.

**Comment by Denthamos** [comment]
Perhaps the atmospheric tech role can be kept as an alternate title role?  That way people can still show as such while being a single job.

**Comment by S34NW** [comment]
> > If you don't see it, you're the outlier. It has been approved already.
> 
> if it was preapproved, that's all good. (simply seemed like a radical change to me, not that I feel one way or another). My apologies then.

I think they meant regarding the approval labels. "Awaiting approval" means it does not have the team vote in it's favor yet, "Awaiting review" means it is currently passing the vote.

While I appreciate your eagerness to help, @procdrone, the development team is more than capable of handling large PRs that open without prior consultation.

**Comment by S34NW** [comment]
image
PR is waiting on https://github.com/ParadiseSS13/Paradise/pull/21250, MQL skip applied.

**Comment by DGamerL** [comment]
Okay, I'm gonna take a look this weekend and try to merge master in this + the .bat that contra made, to see how much is fucked from merge conflicts.

**Comment by silverplatedelta** [comment]
Due to an overwhelming amount of IRL things to do, this PR is going to be closed until either someone takes the reigns or I find myself with enough free time to continue. Thank you to everyone that helped get it this far, I do want to make this happen in the future, but now isn't the time.

**Pull request closed without merging**
