### PR TITLE
Makes a few more machines movable

### LINKED ISSUE #9983: Machines which cannot be moved.
Some machines are impossible to move/deconstruct.

- [x] Book binder
- [x] Library computer
- [x] Pandemic virus machine
- [ ] Washing machine
- [x] Chem master
- [x] Chem dispenser
- [ ] PDA Machine

Please comment any I have missed so I can address them all.

### PR DESCRIPTION
**Pull request by CornMyCob**
**What does this PR do:**
This PR makes more machines unwrenchable, so that they can be moved, please tell me if I've done something wrong. I have left it so the chem dispenser cannot be unwrenched since that is the purpose of the portable chem dispenser.
Fixes #9983

**Images of sprite/map changes (IF APPLICABLE):**
N/A

**Changelog:**
:cl: CornMyCob
add: You can now unwrench and move the library machines/computers, chem master, chem heater, washing machine, pandemic and PDA painter
/:cl:

### CODE REVIEW

**Comment by farie82** [comment]
That are a lot of adds and removals. Unsure what went wrong there.

**Comment by KasparoVy** [comment]
I like to move it move it.

**Comment by CornMyCob** [comment]
@farie82 yeah I realised that, I'm not good with github though. I assumed it was just being weird like the icon diff bot check apparently taking 2019 years to complete

**Comment by Birdtalon** [comment]
Nice.

**Comment by tigercat2000** [comment]
Counting this as free.

**Comment by variableundefined** [comment]
I have no idea what happened with everything getting whitespace changes.

Maybe a proper IDE will prevent it?

**Pull request merged**
