### PR TITLE
Health Assembly

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Health Assembly port from TG, which is and of itself a port from NT Station.

Health assemblies are a new ...well, assembly type that can trigger either when someone enters soft-crit (100 total damage) or when the holder of the assembly is nearly dead (-90 health).

Additionally, if you have a health assembly on your person, it will display your current health in the status tab (spiffy!).

You can produce these at an autolathe or find them as contraband in plasma research and assembly vendors.

Related
- Voice assemblies added as contraband to assembly vendors.

### CODE REVIEW

**Comment by Earthdivine** [comment]
Finally, suicide vests?

**Comment by Fox-McCloud** [comment]
Well, not vests, per se, but effectively what a suicide vest would do, yes.

**Comment by FalseIncarnate** [comment]
Now we need a way to combine these with syringes to make Auto-Stimpacks that inject Chems when the holder drops below threshold.

:+1: for the assembly, even if it doesn't get used much. Wish things like the prox and infrared sensors got more use, they are interesting devices.

**Comment by Fox-McCloud** [comment]
@FalseIncarnate 

Funny you should mention that; I was thinking about something along those exact lines.

**Comment by Spacemanspark** [comment]
More NTstation things hooray.

**Comment by Keilden** [comment]
Will these work from your backpack? Or do you need to put them in your hand/pocket like voice assembly?

**Comment by Fox-McCloud** [comment]
If they're anywhere on your person, they should work.

**Pull request merged**
