### PR TITLE
Allows xenos to use *flip.

### PR DESCRIPTION
**Pull request by Spacemanspark**
Why not.
(Tested and works.)

### CODE REVIEW

**Comment by Markolie** [comment]
:+1:

**Comment by Spacemanspark** [comment]
Holy shit Mark that was fast.

**Comment by Alex6511** [comment]
He tags things faster than he responds on teamspeak.

**Comment by TheDZD** [comment]
*flip
:+1:

**Comment by Fox-McCloud** [comment]
*flip

:+1:

**Comment by Flip-Sandwich** [comment]
Hi, my name is literally *flip_sandwich

:+1:

**Pull request merged**
