### PR TITLE
Adds me to CONTRIBUTING.md review team

### PR DESCRIPTION
**Pull request by BiancaWilkson**
## What Does This PR Do

Puts my name in the codebase

## Why It's Good For The Game

Gives me more power

## Testing

Whats that
<hr>

### Declaration

- [X] I confirm that I did not get [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, and I will not obtain such approval or add a screenshot showing said approval.
  
  
  <hr>

### CODE REVIEW

**Review by warriorstar-orion — APPROVED** [review]
Welcome to hell

**Review by 1080pCat — APPROVED** [review]
pilkson

**Review by Contrabang — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]
I'm sorry to hear that this has happened

**Comment by Adrer** [comment]
My condolences

**Review by lewcc — APPROVED** [review]
huzzah

**Review by DGamerL — APPROVED** [review]
I'll free you from your suffering

**Pull request merged**
