### PR TITLE
Stunts Growth Serum

### PR DESCRIPTION
**Pull request by Aurorablade**
1(normal) >1.1 > 1.2> 1.25 > 1.3 > 1.5 (new cap)

Numbers can be changed...espically the mob metabolize cycle numbers as thats alway been voodoo to me.

:cl: Fethas
tweak: Cap growth serum at 1.5
/:cl:

### CODE REVIEW

**Comment by Draconic-saint** [comment]
Please cap it at 1.5 max, 2 is still too large by taking up 3 tiles vertically, and the sprite looks too fuzzy(and not cause he's a furball)

**Comment by Aurorablade** [comment]
I can certainly do that if others agree it is a good medium.

**Comment by Fox-McCloud** [comment]
I'd leave the switch the same (for volume), but make the scaling something like this:

1.1->1.5->1.2->1.25->1.3

**Comment by uraniummeltdown** [comment]
1.5 max is a nice spot

**Comment by Aurorablade** [comment]
Cap updated and syncing, OP Updated with new comparison shot.

**Comment by SamHPurp** [comment]
I'd still prefer straight up removing it (Or leaving it for adminbus only). It doesn't look good, and adds nothing of worth in my opinion.

**Comment by uraniummeltdown** [comment]
fly amanitas having growth serum isn't just random it's a mario reference
also it looks absolutely fine now, max size is more than half as small as previous max

**Pull request merged**
