### PR TITLE
handles antagbanned players who get mindslaved

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
fix: mindslaving an antagbanned player now offers control of their mob to ghosts.
/🆑

### CODE REVIEW

**Comment by taukausanake** [comment]
That... is one way to do it. Maybe not the best way though

**Comment by Kyep** [comment]
If you have better ideas, state them.
I did debate having it simply not work on antagbanned players... but... that would allow those players to still notice (and rat out) antags. It would also be inconsistent with how cult, shadowling, etc, handle it. So, that option isn't good.
Do you have any other ideas?

**Comment by taukausanake** [comment]
None, and that's what makes this tough. Maintainers will need to vote on this if focusing on bans. I'm just stating the obvious

**Comment by DesolateG** [comment]
Only other option I'd wager is gibbing them.

**Comment by taukausanake** [comment]
@DesolateG That... was actually one of the first things on my mind. Then it could be used for meta-grudge hunting however. It's going to be tough to do anything that's not kicking the mindslavee out of the round

**Comment by scrubmcnoob** [comment]
Why not do it this way? Just boot the player out.

**Comment by Kyep** [comment]
@DesolateG "Yes, officer. This guy was standing next to me. And he just gibbed. For no reason. I had nothing to do with it. Why are you giving me that look? Uh, no, you can't search my bag."

**Comment by Ralta** [comment]
Should probably just ghost them, but maybe give a message to the mindslaver that the person's will was so weak that their body failed. Then make the corpse show the "This person is catatonic, couldn't handle the rigours of life in space etc etc" so that the mindslaver doesn't immediately become suspect.

**Comment by alexkar598** [comment]
But your still ruining his round of the one who's implanted

**Comment by imsxz** [comment]
If we're gonna do this, could we at least add a way for antag banned players to get their bodies back after dethralling or deconverting or unslaved? I don't wanna be out of the round forever because a chaplain WOLOLO's me 10 mins in. At least on shadowling shifts, it's possible to avoid them entirely...

**Comment by imsxz** [comment]
Of course I'm going to sound super biased but I would've had this same opinion had you asked me 6 months ago; I feel antag banned players (with only the role_syndicate) should be able to be converted or slaved with no issues, but if they start abusing that and intentionally getting converted, you either ban them from convert antags or just permaban them. I dunno that's my 2 cents, good forbid a banned player having fun, they don't deserve it.

**Comment by Spacemanspark** [comment]
They're antag banned for a reason. They do not get exceptions.
It's a matter of keeping unruly players from ruining other players' fun at that point.

**Comment by taukausanake** [comment]
By that point I guess it's a fair argument that you **can** ruin unruly players rounds. It's not their fun that's of matter, only those who do not cause trouble.

So gibbing and/or ghosting when implanted. I can get behind that now

**Comment by Spacemanspark** [comment]
When one player is ruining a giant chunk of the server population's fun, who's the one being punished more?
It's not like we don't care, but we do need to consider the wide majority.
As for this PR, I agree that it should be consistent.

**Comment by FalseIncarnate** [comment]
Needs of the many weighed against needs of the few.

While I don't think this will be as common of an occurance as other comments might lead one to believe, I think this is a good move. Failure would punish the antag, gibbing punished the antag AND victim, ghost control simply punishes the victim who is ALREADY being punished with the ban in the first place.

If the implantee is that upset about losing control of their character, they can always clean up their act and appeal it.

They were banned from all antags because their actions showed they weren't responsible enough to play those positions properly. Keeping them out of convert roles is just reinforcing the "you are not responsible enough for this role", which keeps them from getting worse. It's not so much "you can't have fun" as much as it is "you aren't fun".

**Comment by alexkar598** [comment]
Maybe we could kick them back in the lobby after being implanted?

On 2017-10-10, at 10:19 AM, "FalseIncarnate" <notifications@github.com<mailto:notifications@github.com>> wrote:


Needs of the many weighed against needs of the few.

While I don't think this will be as common of an occurance as other comments might lead one to believe, I think this is a good move. Failure would punish the antag, gibbing punished the antag AND victim, ghost control simply punishes the victim who is ALREADY being punished with the ban in the first place.

If the implantee is that upset about losing control of their character, they can always clean up their act and appeal it.

They were banned from all antags because their actions showed they weren't responsible enough to play those positions properly. Keeping them out of convert roles is just reinforcing the "you are not responsible enough for this role", which keeps them from getting worse. It's not so much "you can't have fun" as much as it is "you aren't fun".

**Comment by FalseIncarnate** [comment]
We generally avoid kicking players back to the lobby since that would imply they can rejoin (potentially as the same character) without addressing the fact that they know who the antag is. Ghosting them is generally safer since you don't have to worry about them coming back as a full crew member as quickly.

**Comment by alexkar598** [comment]
Right...

On 2017-10-10, at 6:17 PM, "FalseIncarnate" <notifications@github.com<mailto:notifications@github.com>> wrote:


We generally avoid kicking players back to the lobby since that would imply they can rejoin (potentially as the same character) without addressing the fact that they know who the antag is. Ghosting them is generally safer since you don't have to worry about them coming back as a full crew member as quickly.

**Comment by The-Driker** [comment]
> if we're gonna do this, could we at least add a way for antag banned players to get their bodies back after dethralling or deconverting or unslaved?

I'd like to see that actually. If after the person is turned back to normal, it ghosts the person who took control and gives the original player the body back.

**Pull request merged**
