### PR TITLE
New Tank Sprites

### PR DESCRIPTION
**Pull request by uraniummeltdown**
https://github.com/tgstation/tgstation/pull/23861
https://github.com/tgstation/tgstation/pull/23934

Also adds inhands that match.
I did the emergency nitrogen, vox and emergency plasma tanks
newtanks
newtanks2
newthanks3
Sprites by Ausops

:cl: Ausops
add: Internals and plasma tanks have been resprited.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
I'm personally not a fan.

**Comment by Fox-McCloud** [comment]
Ausops always did have a unique style.

I kinda like them. They're a lot easier to differentiate.

**Comment by scrubmcnoob** [comment]
These are really good looking. I hope we introduce these. Good work.

**Comment by Draconic-saint** [comment]
These look amazing, but the style kinda clashes with our style: hard black outlines and very binary & straight line shading. I think it'd make them stick out and be a bit of an eyesore

**Comment by fludd12** [comment]
Very pretty, but I agree that they do clash with the rest of our style.

**Comment by KasparoVy** [comment]
Lol wtf? The sprites look just fine and I don't feel they clash whatsoever. That argument is moot since we have such large variation in sprite style already.

The quality is superb and I support this PR

**Comment by taukausanake** [comment]
I agree with most here, they are very pretty but don't seem to fit in with the rest of the style we have. I rather not have the icons changed out

**Comment by Dinarzad** [comment]
They are fancy, and thus, I approve of them.

**Comment by DesolateG** [comment]
Does this change the look of jet packs too?

**Comment by uraniummeltdown** [comment]
Jetpacks are unchanged only the above tanks get new sprites. Also I will port the inhands once TG finishes them.

**Comment by Norgad** [comment]
Eww, no thanks. The colors are weirdly desaturated and the outlines are gross.

**Comment by tigercat2000** [comment]
Don't like these. Definitely love our current tank sprites. Please no.

**Comment by Fox-McCloud** [comment]
@uraniummeltdown you'll want to include the back sprites for the tanks as well, here:

The picture above doesn't really do these justice; it makes them look more pixelated than they really are.

**Comment by Draconic-saint** [comment]
I still find the hard black outlining too clash hard, especially on the character sprites, where outlines are done much more subtly.

**Comment by scrubmcnoob** [comment]
Looks great.

**Comment by taukausanake** [comment]
Yeah, it's those outlines, they just stick out too much. These will look horrible on the station

**Comment by optimumtact** [comment]
They only stick out until they're not new

**Comment by uraniummeltdown** [comment]
Added back and belt sprites now. Note that double emergency oxygen (double yellow) and vox specialized (double red) still use the old belt sprites

**Comment by Fox-McCloud** [comment]
@uraniummeltdown 

Have the belt sprites finished?

**Comment by uraniummeltdown** [comment]
@Fox-McCloud Going to take one last look at it later today to make sure everything's alright, almost ready

**Comment by uraniummeltdown** [comment]
Should be ready now. I removed the belt_mirror (suit storage) sprites for tanks as we never had them before and it looks awful when you wear spacesuits and use the small tanks in suit storage

**Comment by Aurorablade** [comment]
i did not know this was a thing..cuase..i am also not a fant..i need to keep up with PRs better...

**Pull request merged**
