### PR TITLE
CHAD WOLF IS LING GO KILL HIM

### PR DESCRIPTION
**Pull request by CHADWOLFCHANGELING**
FUCK THAT DUDE IS BEWING CHEAP

### CODE REVIEW

**Comment by SamHPurp** [comment]
speed merge

**Comment by alexkar598** [comment]
Salt!!! Chlorine + water + sodium

**Comment by alexkar598** [comment]
I guess there's a ban going fuck this dude up

**Comment by Crazylemon64** [comment]
Following a discussion between heads and maintainers it was decided - haha no I am the law

**Pull request closed without merging**
