### PR TITLE
Inhand snack sprites

### PR DESCRIPTION
**Pull request by kugamo**
## What Does This PR Do
This PR adds inhand sprites for a number of snack items.

## Why It's Good For The Game
Immersion. More inhand sprites are good.

## Images of changes

snack inhand spirtes

## Changelog
:cl:
imageadd: Adds inhand sprites to all items in the snack vendor as well as for syndie cakes, and popcorn.
/:cl:

### CODE REVIEW

**Comment by Kiyahitayika** [comment]
Much needed QOL here! ^__^

**Review by variableundefined — APPROVED** [review]
Keep up the good works, spriteperson

**Review by Kyep — APPROVED** [review]

**Comment by kenken244** [comment]
Where is kfv?

**Comment by kugamo** [comment]
> Where is kfv?

Already in game 🤩

**Comment by SteelSlayer** [comment]
Suggestion: Make the in hands for Mr Changs look like the mob is holding the little handle of the bucket, instead of sticking his hand inside it. Not sure if this is viable because it needs to look good with non-humans but yeah.

**Comment by kugamo** [comment]
> 
> 
> Suggestion: Make the in hands for Mr Changs look like the mob is holding the little handle of the bucket, instead of sticking his hand inside it. Not sure if this is viable because it needs to look good with non-humans but yeah.

Its a give and a take, just imagine they hold it from the back. I made some improvements to the side view sprites, hopefully an improvement.

**Comment by AffectedArc07** [comment]
image
Feel like these are far too big for Chinese food boxes
image
Its about the size of a hand, not a decent amount bigger.

**Comment by kugamo** [comment]
> 
> 
> Feel like these are far too big for Chinese food boxes
> Its about the size of a hand, not a decent amount bigger.

Yes, I somehow didnt think they were the take out boxes size. Space chinese food??? The items themselves are in need of a resprite. Anyways I resized them. @AffectedArc07

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
