### PR TITLE
GLORY TO THE SYNDICAT

### PR DESCRIPTION
**Pull request by Crazylemon64**
#2360

### CODE REVIEW

**Comment by veganzombeh** [comment]
Out of curiosity, was there any reason for mapping it right on top of syndifox?

**Comment by Crazylemon64** [comment]
I don't actually have a working map editor, so I directly edited the map file. I didn't want to have to fiddle with inserting a new tile ID.

**Comment by Markolie** [comment]
It should be on a different tile, yes.

**Comment by Fox-McCloud** [comment]
I'll add this ins the LINDA PR.

**Comment by Crazylemon64** [comment]
Alright, I'll shut this down, then.

**Pull request closed without merging**
