### PR TITLE
Fix hyposprays not spreading viruses

### PR DESCRIPTION
**Pull request by datlo**
This PR adds reaction to blood injection from hypospray, letting you spread viruses (and I believe vaccines) with them.

Things that transmit blood but not viruses and should : 

Hypospray : Fixed by this PR
Sleepy pen : Not functional
Syringe gun : Not functional
Blood smoke : Not functional

I'd like to fix all of these, but it seems fixing those is more difficult as they are not reagent containers subtypes like syringe/hypospray. If you know how to fix, let me know, please!

🆑:
fix: Fixed hypospray not spreading viruses.
/🆑

### CODE REVIEW

**Comment by tigercat2000** [comment]
Making this trigger an INGEST reaction when it's an INJECT based tool could have unintended side effects for a lot of chemicals.

**Comment by datlo** [comment]
This is the code used by the syringe, so I assumed that INGEST was the type used for injections aswell as eating. Should I change it on syringe and this to INJECT?

**Comment by KasparoVy** [comment]
I agree and think you should, good eye spotting it

**Comment by datlo** [comment]
Closed because henk made a PR fixing this and others.

**Pull request closed without merging**
