### PR TITLE
Removed Malfunction from Renevant.

### PR DESCRIPTION
**Pull request by Robertha89**
This literally makes Renevant a god, also emps are too powerfull to be used as safely as this, you basically need a mech to kill a renevant with this, Oh lol, renenvant stepped on table and walked away, you put your empty stun baton on the table. Is something that will happen a lot, not to mention the fact that they can hide inside windows and whatnot.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:-1: 

Revenants needs the latest round of balance and tweaks from TG, but this is dumb.

**Comment by Earthdivine** [comment]
What one thing we could do is make the Heavy EMP the Revenant tile only, so it cant Instant kill IPC's but not outright remove the use.

**Comment by Robertha89** [comment]
It also instantly kill IPC's and make them already hard to fight against, revenante is also a Moderate event, and yet is harder to kill then blob, alien infection, and a major carp migration. Swarmers are moderate, but you can actually fight against them, and stop them. There is also the fact that it also does emp act on people, and doors that are permanently shocked. I mean honestly, it can hide by cloning the entire round, absorb the dead people, emp the cloning pod to prevent them from being cloned.

**Comment by Fox-McCloud** [comment]
Yes, I know; revenants are very difficult to fight against--again, we've not updated to the most recent Revenant iteration TG has--we've all been very busy with projects of late, so a mini-antag has taken a bit of a backburner.

It's a lot easier to handle revenants in the most recent iteration as they're revealed for far longer.

**Comment by Aurorablade** [comment]
:-1:

**Comment by Spacemanspark** [comment]
My opinion on this?
The purpose of a Revenant is to be a mere annoyance, if I recall.
Not a death machine.
My stance on this for changelings, however, is that they are meant to kill, it's fine the way it is.

**Comment by Aurorablade** [comment]
is there anyway a override for IPCs to be added that simply overloads thier sensors and/or makes them act confused on a Revernent emp?

**Comment by Fox-McCloud** [comment]
I'd recommend implementing TG's latest round of balancing for revenants and we see how that plays out before we consider just removing this ability.

**Pull request closed without merging**
