### PR TITLE
Fifty shades of grey

### PR DESCRIPTION
**Pull request by Aurorablade**
...clothing..

Adds as much of https://github.com/vgstation-coders/vgstation13/pull/11886 and https://github.com/vgstation-coders/vgstation13/pull/11071 as i could. I may have done something wrong linking it up code wise. and theres probaly still sprites missing.

Screenshots in PR links. 

:cl: Fethas
rscadd: a ton of grey clothing sprites.
/ :cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
What a beast. Nice

**Comment by KorpoPapiez** [comment]
After all these years

**Comment by Aurorablade** [comment]
If anyone can double check I did not miss anything

**Comment by imsxz** [comment]
MERGE. NOW. THANKS.

**Pull request merged**
