### PR TITLE
Ghetto Hemostat - changes cable coil to wirecutters in most surgery steps

### PR DESCRIPTION
**Pull request by imsxz**
This PR tries to make some ghetto surgery tools a bit more consistent. Cable coil is supposed to act as a ghetto fixovein, and wirecutters are to act as a ghetto hemostat. Wirecutters already functioned as hemostat in some surgeries such as ghetto implant removal, where it wouldn't function in surgeries like removing organs. Anyways, it makes a bit more sense to be able to rip out organs with wirecutters, doesnt it?

🆑  imsxz
tweak: changes cable coil to wirecutters in lots of ghetto surgeries
add: adds wirecutters to list of tools that can extract organs
\🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
if you are gonn do this you are gonna need to make it so it always does damage cause its wirecutters inside a incision.

**Comment by granodd** [comment]
Makes more sense than cable coil. Can also agree that it should cause damage while using it.

**Comment by Ionward** [comment]
if the mouse trap in lieu of a hemostat or welding tool cauterizer doesn't cause direct damage i don't see why wirecutters should. ghetto surgery damage functions on success chance, wirecutters could have a 50% success rate and hemostat could have a 75%, and that leaves the mousetrap at its default 20%

**Comment by EvadableMoxie** [comment]
> if you are gonn do this you are gonna need to make it so it always does damage cause its wirecutters inside a incision.

I don't feel the goal of the ghetto surgery system should be realism. It should exist so people aren't totally screwed if Medbay gets blown up.  Besides, you can patch lungs with gauze or mend bones with a screwdriver, realism is pointless without consistency. 

>wirecutters could have a 50% success rate and hemostat could have a 75%, and that leaves the mousetrap at its default 20%

Actual surgical tools should never have a less than 100% chance.

**Comment by imsxz** [comment]
@aurorablade that isn't consistent with the other ghetto surgeries. Using a crowbar to pry someone's skin open doesn't cause damage in game.

**Comment by Vivalas** [comment]
I like using a fork to remove people's organs, I think wirecutters makes more sense for certain steps like stopping bleeding, but niche cases should stay the same. The intended effect here is that one tool can't do all the same things an actual surgical tool can.

**Comment by EvadableMoxie** [comment]
I don't like a fork being the method of organ extraction because a fork has absolutely no purpose beyond that.  There is literally zero reason for anyone to be carrying a fork around, unless they are prepping for having to do ghetto surgery, and if that's the case, just go down to cargo and print a hemostat.

I feel ghetto surgery should be something you do with tools people are already carrying in an emergency.  If you need to seek out specific tools no one has a reason to carry, there's no point, you might as week seek out the proper tool instead.

**Comment by Vivalas** [comment]
A fork is much easier to aquire than a hemostat, just because you're improvising doesn't mean it has to be easy...

And in the case of ghetto organ removal, well, it's not something you probably would be doing in an emergency, but as an antag or mad clown or something.

**Comment by Anticept** [comment]
> if you are gonn do this you are gonna need to make it so it always does damage cause its wirecutters inside a incision.

The wirecutters pictured in game are not side cutters. They are wire strippers. Makes sense, because using side cutters to mend a wire would be difficult and require a lot of skill. I've done it, but only because I had to. Usually I have my toolbox which have a pair of these and these:

image

image

**Comment by EvadableMoxie** [comment]
>That said, it's absolutely insane that anyone would be able to clamp an artery with either of these. It's not damage I would worry about... it's the fact there's no freaking way you could do it due to all the gaps.

A lot of the things in the game are absolutely insane and we don't even need to go outside of the ghetto surgery system to find them.  Mending lungs with gauze is insane, Fixing bones with a screwdriver is insane. How how about being able to do surgery with anesthetic in the first place?

Demanding realism from one specific mechanic within a system that itself is wildly unrealistic makes little sense, at least to me.  

>And in the case of ghetto organ removal, well, it's not something you probably would be doing in an emergency, but as an antag or mad clown or something.

Except that alien embryos and terror spider eggs is organ removal, and that's one of the few surgeries you should be doing in an emergency. As it currently stands, about the only thing it's viable to ever do is internal bleeding, since it's easy and IB is deadly enough to warrant it.

**Comment by imsxz** [comment]
I don't think it's fair to get THIS picky about realism in SS13. The point of this is to make ghetto surgery more friendly and viable. For Christs sake, bone gel is replaced by a screwdriver...

**Comment by Vivalas** [comment]
Mhm, I just think ripping people's organs out with a fork is a nice mechanic.

**Comment by taukausanake** [comment]
We need glue in SS13. Then we can properly replace bone gel.

OR you could go the _real_ ghetto way and use duct tape

**Comment by Fox-McCloud** [comment]
Conflicts.

Also, why not have wirecutters and cable coils both, like TG does? With wirecutters being the "better" choice, and cable-coils being the "bad" choice?

**Comment by Fox-McCloud** [comment]
Closing this, as this is stale; a suggestion was offered a long time ago as was notification of the merge conflict.

**Pull request closed without merging**
