### PR TITLE
Adds in Corgi Hardsuit

### PR DESCRIPTION
**Pull request by Fox-McCloud**
- Adds in the ability for corgis to wear engineering hardsuits
 - Credit to @NigglyWiggly of VG for the sprites

spesscorgi

Other
- Fixes the hardsuits on the map being regular hardsuits instead of engineering hardsuits
 - Functionally, no difference at all, nor even sprite differences

### CODE REVIEW

**Comment by Robertha89** [comment]
Oh, i did at a time work on icons for the rigs in EVA for Ian to wear, but then, i got busy... Are these actually functional, the hardsuits taht is, if so, im adding moar.

**Comment by Fox-McCloud** [comment]
No, corgi clothing is purely aesthetic.

**Comment by Robertha89** [comment]
Thats not right, wearing armor and helmet gives corgis 100% brute protection, so the mean captain can't kick ian to death. Also, at least two hats makes him a light source.

**Comment by TheDZD** [comment]
@Robertha89 The corgi armor works via a snowflakey istype check in the corgi attackby, which makes me want to cry.

**Comment by Dumbdumn5** [comment]
:+1: YES!

**Comment by Spacemanspark** [comment]
Oh hey, while you're at it can you port over /tg/'s deathsquad corgi? I was gonna try doing it at one point, but perhaps it could be added to this PR.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

That was already added in a longgg time ago.

**Comment by Spacemanspark** [comment]
Wait what.

**Comment by Spacemanspark** [comment]
Hahahaha it is.
I'm so fucking stupid.

**Comment by Fox-McCloud** [comment]
@Markolie and @TheDZD 

This should be ready, if there aren't any objections.

**Comment by tigercat2000** [comment]
I think it would be fun if it made corgi's space-resistant, but w/e

**Comment by Plotron** [comment]
Why can't we send the corgi on a spess-venture?
I second @tigercat2000

**Comment by TheDZD** [comment]
Just address it in another PR if you want corgis to be spaceproof with the hardsuit.

**Comment by NTSAM** [comment]
Corgi plasma cutter when?

**Pull request merged**
