### PR TITLE
Adds Fox Resting Sprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds a resting sprite for the Fox. Sprites by @FullofSkittles. Thank you!

foxie

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:+1:

**Comment by Plotron** [comment]
Looks, it's so cute and happy!

**Comment by Tastyfish** [comment]
adorable

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by KasparoVy** [comment]
[TAIL WAVING INTENSIFIES]

**Pull request merged**
