### PR TITLE
Updating some of our food sprites to better ones from other codebases

### PR DESCRIPTION
**Pull request by PacifistDalek**
## What Does This PR Do
Takes some of our worst food sprites and replaces them with better sprites from other stations. Plus I took TGstation's meatwheat clump sprite and made it look less like a skein of meat yarn, and more like a clump.

## Why It's Good For The Game
Ugly sprites bad, better sprites good!

## Images of changes
foodtheft2

## Changelog
:cl:
tweak: updated a handful of food sprites to better ones from other codebases
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
mmmyes.

**Comment by PacifistDalek** [comment]
> mmmyes.

delicious, no?

**Comment by farie82** [comment]
image
Duplicated I assume?

**Comment by SabreML** [comment]
While the new donut sprites very clearly look better than our current ones, I'm worried they'll stand out too much because of that.
Almost the same sort of situation as the old baguette.

Speaking of which, you should probably see about doing muffin sprites too while you're at it. They have the same ***photorealism*** problem that the baguette has.

Also I personally think the current orange sprite is fine as-is; but that might just be me.

**Comment by AffectedArc07** [comment]
image
Goon uses a different licensing scheme than us, please check with goon that the licensing actually allows this.

**Comment by PacifistDalek** [comment]
Will do!

**Comment by Carthusia** [comment]
the current muffin is also HUUUUUUUUUUUUUUUUGE for some reason

**Comment by Cocacolagua** [comment]
a baguette sprite that isn’t ripped straight from google images, no way

**Comment by ZeWaka** [comment]
Goon sprite author: @binarysudoku / `<@189446772513308672>`

**Comment by PacifistDalek** [comment]
> Goon sprite author: @binarysudoku / `<@189446772513308672>`

Thank you Zewaka!

**Comment by PacifistDalek** [comment]
> image
> Duplicated I assume?

Yep, only deletions I did were for duplicates

**Comment by Dumbdumn5** [comment]
If the goon shit goes over well, 👍 , I hope it does because I need that melon sheen.

**Comment by PacifistDalek** [comment]
I changed a BUNCH more food sprites, please let me know what you think!
foodtheft2

(Goon stuff is all worked out for those sprites!)

**Comment by Mitchs98** [comment]
Obligatory 'Egg' comment here.

Honestly, these sprites are awesome. I definitely like them quite a bit! Glad Goon let us use 'em.

**Comment by Kiyahitayika** [comment]
Please ensure that the file names are the same or change the code to the appropriate file names before this gets merged. 

**Maints, I mean you.**

**Comment by PacifistDalek** [comment]
> Please ensure that the file names are the same or change the code to the appropriate file names before this gets merged.
> 
> **Maints, I mean you.**

which file names did I miss? (unless you mean in chart i made of edits, those were before i went through and changed all the names to match)

**Comment by ZeWaka** [comment]
> (Goon stuff is all worked out for those sprites!)

Confirming. ✅

**Comment by Kiyahitayika** [comment]
> > Please ensure that the file names are the same or change the code to the appropriate file names before this gets merged.
> > **Maints, I mean you.**
> 
> which file names did I miss? (unless you mean in the image chart I made to show off the changes, those were before i went through and changed all the names to match)

Aaaah you scared me, @PacifistDalek  <3

**Pull request merged**
