### PR TITLE
The Flagbearer - Custom Item Fixes

### PR DESCRIPTION
**Pull request by TheFlagbearer**
Reverts ParadiseSS13/Paradise#1158. I made multiple errors and in an attempt to make a patch, encountered a merge conflict that I could not solve. The only fix I can see is to remove the item and re-add it.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
So this is a revert of your preview PR and a new commit that fixes everything correctly?

**Comment by TheFlagbearer** [comment]
Correct.

**Comment by ZomgPonies** [comment]
MERGE ERRORS DUE TO MY MONKEY PR. Gotta fix it! uniform.dmi and uniforms.dmi

**Comment by TheFlagbearer** [comment]
Merge conflicts, the bane of my existence. I've yet to successfully resolve one.

**Comment by TheFlagbearer** [comment]
Ready to merge.

**Pull request merged**
