### PR TITLE
Removes the obligatory tie from Blueshields and Detectives coat.

### PR DESCRIPTION
**Pull request by TheBeoni**
HOLA! 

This is again small PR. The name is self explanatory so that is that.

And i added black tie to detectives closet. 

scrnshot2

e94cc8fd499c99752228c8507346d72f

### CODE REVIEW

**Comment by Cobradude** [comment]
All of my yes.

**Comment by LittleBigKid2000** [comment]
Post a screencap of the sprites or Fox/TheDZD/someone will probably get angry.

**Comment by Fox-McCloud** [comment]
>Post a screencap of the sprites or Fox/TheDZD/someone will probably get angry.

Too late.

**Comment by TheBeoni** [comment]
> Too late.

NO...NOOOO i was so close.

**Comment by KasparoVy** [comment]
pff, puush.

MS PAINT LIFE

**Comment by TheBeoni** [comment]
scrnshot2

HERE put that ugly tag away

**Comment by TheBeoni** [comment]
Uhhh....COMMENT is too close to Close Request.

**Comment by Fox-McCloud** [comment]
Ehhh, think it looks better, for detective, at least, with the tie.

**Comment by Cobradude** [comment]
Thing is, you can have a tie. They exist. This just stops it from forcing it on you, especially with Blueshield, the obligatory tie makes the blue tie redundant.

**Comment by TheBeoni** [comment]
@Fox-McCloud Do you want me to add black tie into Detectives closet?

**Comment by Cobradude** [comment]
It'd still make more sense to make the tie an option.

**Comment by counterfeitguise** [comment]
Ties are illegal. :+1:

**Comment by Fox-McCloud** [comment]
Pics of what it looks like with a a tie, and please, not a tiny 32x32 that no one can make out.

**Comment by Cobradude** [comment]
Y'know if you click it, it opens in another tab where you can zoom in and shit.

**Comment by Fox-McCloud** [comment]
>Y'know if you click it, it opens in another tab where you can zoom in and shit. 

It's still a 32x32 sprite when most submitted to the git are ~64x64 (what most players view the game in).

**Comment by TheBeoni** [comment]
> Pics of what it looks like with a a tie, worn on a jumpsuit---and please, not a tiny 32x32 that no one can make out like in your OP.

Done...and yes i made it bigger

**Pull request merged**
