### PR TITLE
Medbay Secondary Storage change

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
This implements some of the objectives of #10339 by changing medbay's secondary storage somewhat. Specifically:

- The room now just requires medbay access to enter, so that the medkits and so on there are useful for doctors
-  A pillbottle box, box of emergency autoinjectors, box of empty syringes and box of bodybags was added. Also added 3 syringes of spaceallin and a super-capacity power cell for the cell recharger
- Removed the grenade parts to make space for that.
- Replaced rad suits with a rad closet, which contains the suits
- Moved the two two hardsuits to be behind a windoor which requires CMO access. This addresses the fear that doctors would just nab them at roundstart, while still leaving them accessible in emergencies (smash the glass) or for thieves.

**Images of sprite/map changes :**
untitled

**Changelog:**
:cl: 
tweak: Medbay secondary storage is now accessible to everyone with medbay access, hardsuits were put behind a windoor with CMO access to keep them at the same level of accessability.
tweak: Added and removed some items from medbay secondary storage.
tweak: Medical storage and secondary storage were renamed to be more accurate.
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Changed the area names as in #10339

**Comment by Pennwick** [comment]
Not sure Medbay should start off with a super capacity cell. As it is they might start with the highest charge cell on station unless any APCs are preloaded with them. A high capacity cell would be a better fit, thats what comes in Defibulators.

**Comment by KasparoVy** [comment]
I agree that there probably shouldn't be a supercell here. It should be the same as whatever starts in the defibs (unless that is actually a supercell, which I feel it probably isn't)

**Comment by datlo** [comment]
agreed that the cell should be replaced with a high cap, I didn't realise it wasn't.

**Comment by KasparoVy** [comment]
Personally, I'd love to see the suit storage containers as well, but I can recall there being some arguments against it.

**Comment by TDSSS** [comment]
Sorry on the power cell, forgot that the tier above normal is high and not super. I'll fix that in a moment.

As for SSUs...I think it would look kind of silly to put one behind glass. Ideally, we'd make id-locked SSUs and make them hackable, IMO. But that's a bit out of scope.

**Pull request merged**
