### PR TITLE
Fixing butcher chainsaw not knockdowning targets

### PR DESCRIPTION
**Pull request by HMBGERDO**
## What Does This PR Do

Fixes butcher chainsaw not knockdowning target

## Why It's Good For The Game

Bugs bad

## Testing

Compiled, attacked someone, knockdowned, tried parrying attack, not knockdowned

## Changelog
:cl:
fix: Butcher chainsaw knockdowns again
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
"//necessary check, successful attacks return null, without it target will drop any shields they may have before they get a chance to block"
h m m m 🤔

**Comment by HMBGERDO** [comment]
> "//necessary check, successful attacks return null, without it target will drop any shields they may have before they get a chance to block" h m m m 🤔

it just shouldnt be in attack proc
afterattack only applies if the attack was not blocked

**Comment by S34NW** [comment]
> > "//necessary check, successful attacks return null, without it target will drop any shields they may have before they get a chance to block" h m m m 🤔
> 
> it just shouldnt be in attack proc afterattack only applies if the attack was not blocked

Please test the described scenario thoroughly

**Comment by HMBGERDO** [comment]
boop

**Pull request closed without merging**
