### PR TITLE
Adds/Updates Some Vulp., Taj. & Unathi (Facial) Hair/Head Accessory Styles

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
rscadd: Adds a Tajaran facial hair style.
rscadd: Adds a few new frill styles for Unathi.
rscadd: Adds some new horn styles for Unathi.
rscadd: Adds a couple new facial hair styles for Vulpkanin.
rscadd: Adds a few new hair styles for Vulpkanin.
tweak: Updates Vulpkanin Adhara & Kajam hairstyles.
/:cl:

I've been sitting on this one for way too long, decided to split it off from some other PR so I could post it before I forgot.

No more 'soghun' in sprite_accessories.dm.

**Adds for Tajara:**
- Tajara Faded Goatee

Much of the Unathi stuff is ported from Polaris. (* = OG)
You'll see duplicates in sprite_accessories.dm so people can have combinations, like how Vulpkanin can have combinations of facial markings by using facial hair, head accessories and head markings.
**Adds for Unathi:**
- Side frills
- Dorsal frill*
- Spined webbed aquatic frill*
- Double horns*
- Lower horns*
- Big horns
- Alt. Ram horns
- Small horns
- Chin horns
- Horn adorns
- Spikes

**Adds for Vulpkanin:**
- Punk braided hairstyle (has 2ndry theme)
- Short alt. hairstyle
- Rough-cropped mane hairstyle (has 2ndry theme)
- Alt. nose head marking (like regular nose except the side-on view isn't any brighter)

**Edits for Vulpkanin:**
- Adhara hairstyle (making the side-on view look like the south-facing view implies)
- Kajam hairstyle (better fits head shape)

_Tajara faded goatee._
tajfadedgoatee

_New Unathi frills._
unathifrills
_New Unathi horns._
unathihorns

_New Vulpkanin (facial) hair_
vulphair
_Updated Vulpkanin hair_
vulphaircompare

### CODE REVIEW

**Comment by taukausanake** [comment]
These would be so much easier to see if you used neon colors and I'm only half joking there. It would be nice to see how the hair contrasts against the body

**Comment by Dinarzad** [comment]
I will never not +1 cosmetic options.

**Comment by IcyV** [comment]
Could we get a before/after for the tweaked ones?

**Comment by Fox-McCloud** [comment]
Needs a before and after.

**Comment by KasparoVy** [comment]
Added a comparison picture to the main post.

**Comment by Fox-McCloud** [comment]
👍

**Pull request merged**
