### PR TITLE
pAI Candidates can now see who requested them

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Allows pAI candidates to see who actually requested them

:cl: Fox McCloud
Add: pAI candidates can now see who requested them
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
Why not include their job, too?

A pAI for a sec officer will likely play different from one for a scientist, etc.

**Comment by taukausanake** [comment]
@Kyep the ghost can just teleport to the user and check for themselves before accepting. Then again the same can be said for the name of the person. This isn't a bad addition but I can think some ghosts might just swarm to their meta buddy as pAI faster with this. Bad excuse but it's on my thought.

I don't even care who my pAI owner is, I play either way

**Comment by Spacemanspark** [comment]
Might wanna give this to posibrains too.

**Comment by Fullofskittles** [comment]
> the ghost can just teleport to the user and check for themselves before accepting.

Sadly anything that requires me to click on a link to jump to something or respond to something (even ahelps) will likely cause byond to freeze/crash.

That said, i think this is pretty awesome and helpful since it's frustrating not knowing if it's multiple different people requesting pAIs or just one person. Is this changing it to a similar type of pop-up as event antags/golems/sentience potions?

**Comment by LittleBigKid2000** [comment]
Also showing antag status would probably be a great/horrible idea.

**Pull request merged**
