### PR TITLE
Fixed runtime error related to deleting worn items

### PR DESCRIPTION
**Pull request by DamianX**
## What does this PR do?
Fixed this:

```
Runtime in storage.dm,263: Cannot modify null.screen_loc.
  proc name: standard orient objs (/obj/item/storage/proc/standard_orient_objs)
  usr: Hannah Murphy (damianq) (/mob/living/carbon/human)
  usr.loc: The floor (119,134,2) (/turf/simulated/floor/plasteel)
  src: the box (/obj/item/storage/box/survival)
  src.loc: the floor (119,134,2) (/turf/simulated/floor/plasteel)
  call stack:
  the box (/obj/item/storage/box/survival): standard orient objs(0, 6, null)
  the box (/obj/item/storage/box/survival): orient2hud(Hannah Murphy (/mob/living/carbon/human))
  the box (/obj/item/storage/box/survival): remove from storage(the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency), the floor (119,134,2) (/turf/simulated/floor/plasteel))
  the box (/obj/item/storage/box/survival): Exited(the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency), the floor (119,134,2) (/turf/simulated/floor/plasteel))
  the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency): forceMove(the floor (119,134,2) (/turf/simulated/floor/plasteel))
  the box (/obj/item/storage/box/survival): remove from storage(the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency), null)
  the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency): Destroy(0)
  the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency): Destroy(0)
  qdel(the emergency glowstick (/obj/item/flashlight/flare/glowstick/emergency), 0)
  the box (/obj/item/storage/box/survival): Destroy(0)
  ...
  qdel(the box (/obj/item/storage/box/survival), 0)
  the captain\'s backpack (/obj/item/storage/backpack/captain): Destroy(0)
  the captain\'s backpack (/obj/item/storage/backpack/captain): Destroy(0)
  the captain\'s backpack (/obj/item/storage/backpack/captain): Destroy(0)
  the captain\'s backpack (/obj/item/storage/backpack/captain): Destroy(0)
  the captain\'s backpack (/obj/item/storage/backpack/captain): Destroy(0)
  Hannah Murphy (/mob/living/carbon/human): Destroy(0)
  qdel(Hannah Murphy (/mob/living/carbon/human), 0)
  DamianQ (/client): [Admin] Delete(Hannah Murphy (/mob/living/carbon/human))
```

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Is this PR still required with the merge or https://github.com/ParadiseSS13/Paradise/pull/17667 ?

**Comment by DamianX** [comment]
This now obsoletes #17665
As far as I can tell, with this latest commit I addressed the actual root cause of the issue. `remove_from_storage` was being called twice, both here and by `storage/Exited`, which is called by `forceMove`. With this code removed, it's now only called by the latter, once, preventing the error.

**Comment by AffectedArc07** [comment]
> This now obsoletes #17665 As far as I can tell, with this latest commit I addressed the actual root cause of the issue. `remove_from_storage` was being called twice, both here and by `storage/Exited`, which is called by `forceMove`. With this code removed, it's now only called by the latter, once, preventing the error.

What about https://github.com/ParadiseSS13/Paradise/pull/17506

**Comment by DamianX** [comment]
The latest commit fixes the hard del that was fixed by that PR. The issue was `handle_item_insertion` being overly optimistic, assuming the object being inserted would survive being `forceMove`d.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
