### PR TITLE
[Delta] Adds grounding rods to SM chamber

### PR DESCRIPTION
**Pull request by Shadow-Quill**
**What does this PR do:**
title
fixes: #10207

**Images of sprite/map changes (IF APPLICABLE):**

**Changelog:**
:cl:
add: Added two grounding rods to the SM chamber.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
But why though?

**Comment by Shadow-Quill** [comment]
@Fox-McCloud #10207

**Comment by Fox-McCloud** [comment]
Should happen less with the SM update---and if it's arcing electricity, it's supposed to be "dangerous", as that's something known as "Running it hot".

**Comment by Shadow-Quill** [comment]
*shrug*
I'm fine with this being closed if that's the case.

**Comment by BakKeener** [comment]
_Should happen less_? I don't think NT would leave such a safety hazard there especially if SMs are known to arc lethal amounts of electricity and I don't see a issue with adding these two to prevent a round start SM from destroying a good chunk of equipment that you won't be seeing again until RnD gets rolling if they do at all.

**Comment by Fox-McCloud** [comment]
Yeah, going to close this then; the SM rework and the fact that arcing is meant to be a "don't do that" as opposed to "yeah it's fine, just compensate for it'.

**Pull request closed without merging**
