### PR TITLE
Fix toxins launch room

### PR DESCRIPTION
**Pull request by Luthix**
Separates the two rooms in toxins mixing with a new room named toxins launch room in order to avoid conflicts that occur between the two air alarms and to further comply with the mapping guidelines outlined on the wiki (Each area should have EXACTLY one air alarm (Exceptions are only possible if a room has scrubbers or vent pumps on different frequencies)).

tox1

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This isn't explained very well; are you purely stating that you've split off the areas into two, or have you done more than this and added an additional room.

If the latter, pics.

**Comment by taukausanake** [comment]
It sounded like two separate areas. However looking at the first diff in the map file, and I don't know how map editing or mapmerge works, but it looks like something might have died there?

**Comment by Luthix** [comment]
Nothing added to the station except an APC to the toxins launch room; this area is separated from the toxins mix room by an airlock normally but it was all one area. I made it two areas so that the air alarms would not conflict.

**Comment by Fox-McCloud** [comment]
Right. Thanks for clarifying!

**Comment by FlattestGuitar** [comment]
Start including screenshots, people, for the love of God!

**Comment by Luthix** [comment]
http://imgur.com/5SguyO7
http://imgur.com/Bf5wga5

**Pull request merged**
