### PR TITLE
Support 30 additional hats for corgis.

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
This PR adds support for thirty existing items for corgi head slots. The following items can now be worn.

```
- /obj/item/clothing/head/HoS
- /obj/item/clothing/head/HoS/beret
- /obj/item/clothing/head/beret/sec
- /obj/item/clothing/head/bowlerhat
- /obj/item/clothing/head/caphat/parade
- /obj/item/clothing/head/hardhat/dblue
- /obj/item/clothing/head/hardhat/orange
- /obj/item/clothing/head/hardhat/red
- /obj/item/clothing/head/helmet/roman
- /obj/item/clothing/head/justice_wig
- /obj/item/clothing/head/soft/black
- /obj/item/clothing/head/soft/blue
- /obj/item/clothing/head/soft/green
- /obj/item/clothing/head/soft/grey
- /obj/item/clothing/head/soft/mime
- /obj/item/clothing/head/soft/purple
- /obj/item/clothing/head/soft/rainbow
- /obj/item/clothing/head/soft/red
- /obj/item/clothing/head/soft/sec
- /obj/item/clothing/head/soft/solgov
- /obj/item/clothing/head/soft/solgov/command
- /obj/item/clothing/head/soft/yellow
- /obj/item/clothing/head/surgery/black
- /obj/item/clothing/head/surgery/blue
- /obj/item/clothing/head/surgery/green
- /obj/item/clothing/head/surgery/purple
- /obj/item/clothing/head/wizard/black
- /obj/item/clothing/head/wizard/magus
- /obj/item/clothing/head/wizard/marisa
- /obj/item/reagent_containers/glass/bucket
```

The icon file was generated automatically: once a list of candidate items was selected, their existing hat sprites were exported, alongside the corgi base sprites, and modified according to the existing items in corgi_head.dmi (positioning, cutting out soft cap sprites so ears show up, etc.). Then the resultant sprites were grafted onto the existing icon file, and its metadata regenerated. I mention this just in case there's any weirdness with the resultant .dmi file.

I believe this also solves an issue where some items, mostly berets, could be worn but would not be visible.

I actually didn't check if bucket contents prevent them being worn; I just kind of assumed that logic already existed for crew wearing them.

## Why It's Good For The Game

dog hat

## Images of changes

Paradise Station 13-02_56_06
Paradise Station 13-02_55_43
Paradise Station 13-02_55_34
Paradise Station 13-02_55_38

## Changelog
:cl:
add: Corgis can now wear additional items on their head.
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
The ear showing in front of the hat for the baseball caps looks a bit odd in my opinion.
image
I'm not sure if this was an intentional choice or not but it does look more like a layering issue than anything else, even if it does actually make more sense.

**Comment by warriorstar-orion** [comment]
The ears for the baseball caps follows the pre-existing style for the cargo tech cap as can be seen here
Screen Shot 2021-03-05 at 11 37 56

**Comment by LightFire53** [comment]
> The ears for the baseball caps follows the pre-existing style for the cargo tech cap as can be seen here
> Screen Shot 2021-03-05 at 11 37 56

I wonder what the difference is if the ears were covered by the cap? It does seem odd looking at it from the side, though it makes some logical sense. If the other style looks better though, could adjust the old sprites to match.

Either way, always more options for dog fashion.

**Comment by Gatchapod** [comment]
Call me pedantic, but those berets are placed on his head differently. 
pedantic

The red one is also missing a pixel for north-looking sprite.

**Comment by warriorstar-orion** [comment]
> Call me pedantic, but those berets are placed on his head differently.
> pedantic
> 
> The red one is also missing a pixel for north-faced sprite.
> EDIT: Naturally, you might as well say the black one has one pixel it shouldn't have. It kind of does make sense right now given how the black beret covers his ear entirely while the red one only partially. It just probably should be addressed one way or another, if you decide to change the south-faced sprite.

This should be fixed now.

output



> > The ears for the baseball caps follows the pre-existing style for the cargo tech cap as can be seen here
> > Screen Shot 2021-03-05 at 11 37 56
> 
> I wonder what the difference is if the ears were covered by the cap? It does seem odd looking at it from the side, though it makes some logical sense. If the other style looks better though, could adjust the old sprites to match.
> 
> Either way, always more options for dog fashion.

Here's a version with the cap "pulled over" the ears. I'm not much of a pixel-pusher, but I widened the north and south facing versions to match the profile view.

preview2

**Comment by LightFire53** [comment]
> Here's a version with the cap "pulled over" the ears. I'm not much of a pixel-pusher, but I widened the north and south facing versions to match the profile view.
> 
> preview2

I think this looks better, imo

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — COMMENTED** [review]
While some of these may make sense, like for example the HOS beret, how often are things like solgov berets even on station... is it worth having sprites for corgis wearing those hats? I am fine with the PR I'm just questioning whether supporting never-on-station hats is worth it from a sprite file size point of view.

**Comment by warriorstar-orion** [comment]
I can remove the rarer ones no prob. Besides the solgov beret, which other ones should go?

**Comment by S34NW** [comment]
> 
> 
> While some of these may make sense, like for example the HOS beret, how often are things like solgov berets even on station... is it worth having sprites for corgis wearing those hats? I am fine with the PR I'm just questioning whether supporting never-on-station hats is worth it from a sprite file size point of view.

there isnt a solgov beret...

**Comment by warriorstar-orion** [comment]
I think Kyet meant the solgov softcap.

**Comment by warriorstar-orion** [comment]
Okay, solgov soft-caps are no longer dog fashions. I think the rest of the hats are still available at loadout/in vendors on-station.

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
