### PR TITLE
Removes the teleportation function from tracking implants

### PR DESCRIPTION
**Pull request by Accinator50**
## What Does This PR Do
As mentioned in the title, this PR removes the ability to teleport to people who have had a tracking implant implanted. You can still monitor the user's location.

## Why It's Good For The Game
Tracking implants are mostly used by security for permanent prisoners. They make escape attempts even more difficult than they already are.

Not only do you have to survive space or fight security without any equipment to escape from perma, but you also have to deal with the fact that the security officers know your location AND are able to teleport to you.

This makes successful escape attempts almost impossible, as security can simply teleport to the EoCs and kill them in an instant.

By removing the ability to teleport to prisoners who have had a tracking implant implanted, sec can no longer simply click on the teleporter console and end the prisoners escape attempt. They will either need some coordination because someone will have to tell them the location of the perma-escapee, or they will have to grab the tracking device from the armoury.

This gives the perma-prisoners the opportunity to escape from security, because sec actually has to track them. At the same time, however, the function of the tracking implants - namely tracking - is preserved. 

## Testing
Ran and tried to teleport to an implanted person.

## Changelog
:cl:
del: Removed the ability to teleport to tracking implants.
/:cl:

### CODE REVIEW

**Comment by matttheficus** [comment]
I think I would only support this if the locator wasn’t such a useless device. Actually tracking an escapee is a massive pain 90% of the time.

**Comment by Accinator50** [comment]
> I think I would only support this if the locator wasn’t such a useless device. Actually tracking an escapee is a massive pain 90% of the time.

Chap suggested that tracking implants send out GPS signals instead. I think this is a good solution. I will look into it and add it if I have enough time/knowledge.

**Comment by Rurik123** [comment]
> Not only do you have to survive space or fight security without any equipment to escape from perma, but you also have to deal with the fact that the security officers know your location AND are able to teleport to you.
> 
> This makes successful escape attempts almost impossible, as security can simply teleport to the EoCs and kill them in an instant.

Why is this a bad thing? 

The EOC was caught, they had their chance. The deck should be massively stacked against them unless they have outside help. Sec teleporting onto you is part of the two obstacles set up to make it a uphill struggle. 

You also have to consider non-solo escapes. It is not uncommon for a greentexted EOC to use their sec ID to free every perma prisoner just because they can. I don't want the three loose vampires that were previously caught to be even more of a pain in the ass for security.

However, if you believe the deck is too stacked, perhaps giving the trackered EOC a warning the teleporter is locking on to them would be a better option? That would keep sec's prowess in reacquiring prisoners, while also giving the EOC a chance to prepare or run.

**Comment by Accinator50** [comment]
> Why is this a bad thing?

It's not bad per se that it's difficult. It's bad that it's almost impossible for most players.

With the teleport function it's currently the case that apart from the exceptions mentioned (Biohazard, ...) most players no longer have a second chance. I agree that it should be difficult, but it shouldn't be impossible. With a fully upgraded teleporter the entire security team can simply teleport to you and kill you. In most cases you yourself have at most a spear as a weapon. It doesn't help much if you know 5 seconds beforehand that it's going to happen. 

Certainly, some veterans have more chances because they are simply more robust, but from the rounds I have observed and/or played as a security officer, these people are definitely in the minority.


We don't have to make everything super easy for Antags, but I at least find it boring when I'm playing a security officer and a prisoner escapes and the first thing one of my colleagues does is to use the teleporter and kill the unarmed prisoner with gamer gear. It would be more exciting (at least for me) to spend a few minutes chasing the prisoner and catching them again. That is certainly more exciting for the antags as well.

> You also have to consider non-solo escapes. It is not uncommon for a greentexted EOC to use their sec ID to free every perma prisoner just because they can. I don't want the three loose vampires that were previously caught to be even more of a pain in the ass for security. 

However, this point is also my concern with the PR. On the one hand, the vampire could just remove the implant, but on the other hand, you might still have time to try your luck with a teleport at least once. However, such cases are rare, at least in my experience. For those rare cases, I don't think one should prevent an otherwise (subjectively) good change. Nevertheless, one must also consider them.

Do you think that the GPS function mentioned above would be a solution?

It would still be very difficult to escape, because on the one hand you have to overcome the already existing hurdles (the loss of all your equipment, ...) and then on top of that you have to cope with the fact that security now has some kind of pinpointer that they can use in a coordinated way to catch you. This might even be better for your mentioned scenario as when teleporting to vampires, they can simply glare you, making GPS tracking the better option.

**Comment by Coolrune206** [comment]
Adding on to what Rurik said, Antags know that Security can and will teleport to them eventually. This gives them the opportunity to set up ambushes, as sec is teleporting blind, and may net the antag some gear to recover their position.

I'm also not particularly a fan of making perma'ing people even less appealing. Far too many seccies are already quite willing to lethal anyone that space law allows them to and DNR them, instead of bothering with perma. After all, it just takes one bald officer walking into perma to beat up a prisoner for no explicable reason _(far more common than you may suspect)_ for the antag-man to escape.

**Comment by Komrad822** [comment]
The thing about this feature is..... it RARELY gets used. IN FACT, its used more by antags than it is security. I like the idea of setting up a teleporter somewhere or going to the teleporter ruins and just hot dropping gear on a perma inmate. While yes the few times sec does use this feature, it makes for easy capture and kill, lots of times sec appears, is disorientated by their surroundings and gets looted. If I had a nickel for every time sec teleported to an EOC into space just to die in the vacuum, Id have like 25 cents but still, the teleporter doesn't say WHERE they are so its a leap of faith when you enter.

I insist though, in agreement with Matt, this is a great opportunity to address the tracker cause god damn is it horrid. GPS is the way to go.

**Comment by matttheficus** [comment]
Honestly, on thinking about it more, Perma really should be one of the largest uphill battles an Antag has to crawl out of. You got caught, that’s the game. Escaping Perma successfully should be a massive skill issue moment. This would just increase Security executing prisoners so they wouldn’t have to deal with it.

I’d love to see it swap to GPS signals, but I’d prefer if the teleport stayed.

I’ll be objecting.

**Comment by Accinator50** [comment]
As requested: #20687 adds a GPS signal to tracking implants. 
That way it wouldn't be too much of a nerf.

**Comment by farie82** [comment]
Closing this PR receiving enough objections with the following reasons:
"the design of tracking implants not to mention how we handle them, rule wise, is such that they're not typically used except on highly suspect individuals. I'm all for giving antags an advantage, but I don't view this particular change as being part of the problem of the imbalance that exists."
"Agreed with the above, this is one of the purposes of the tracking implant"

**Pull request closed without merging**
