### PR TITLE
Fixes merchandise vendor's description grammar

### LINKED ISSUE #22181: Grammar issue with the Merchandise Vendor description
**Issue Description**:

The Nanotrasen Merchandise Vendor (```code/game/machinery/merch_vendor.dm```) has a missing dot at the end of its description and the word ```Swag``` is capitalized.
image

**What did you expect to happen**: 

For there to be no grammar issues with it.

**What happened instead**:

The world is in chaos

**Why is this bad/What are the consequences**:

Bad grammar is bad

**Steps to reproduce the problem**:

Go to a merchandise vendor and examine it

**When did the problem start happening**:

Since it was added

**Extra information**:

Free GBP

### PR DESCRIPTION
**Pull request by aditya-garg-09-01-2002**
Fixes merchandise vendor's description grammar

## What Does This PR Do
The grammatical issue was resolved, it fixes #22181 as instructed.

## Why It's Good For The Game 
Fixes #22181

## Testing

Basic Grammar PR, not much testing was required.

## Changelog
:cl:
spellcheck: Added a period to the merchandise vendor's description
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

Account linked

**Comment by Henri215** [comment]
One last thing, update the PR title to something like "Fixes mechandise vendor desc grammar"

**Comment by Henri215** [comment]
image
By title i mean this, theres an edit button near it.

**Comment by aditya-garg-09-01-2002** [comment]
oh okay @Henri215 , I misunderstood that

**Review by Henri215 — APPROVED** [review]
LGTM

**Review by Burzah — APPROVED** [review]

**Comment by aditya-garg-09-01-2002** [comment]
@Henri215 , I supposed by now since I have approval from you and @Burzah, my PR would have been successful but is there something that's left?

**Review by farie82 — APPROVED** [review]

**Pull request merged**
