### PR TITLE
Cocoa Spelling and Relative Pathing Cleanup

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Standardized the spelling of "Cocoa", as this was inconsistent
- One spot refers to it as cacao still, but that is because it is in the
actual Latin scientific name. Everything else is now cocoa (not coco).

Chocolate now will provide some nutrition (and make you fat if you eat a
lot)
- Cocoa Powder (the arguably main component of chocolate) provided
nutrition, but that nutrition mysteriously vanished when you combine it
with milk and sugar. Now chocolate provides the same nutrition as the
cocoa powder in it

Merged a number of cases where foods had both chocolate and cocoa to now
have just chocolate
- In the case where both were present, the volumes were combined to
maintain food sizes

Renamed cocoa pile to Pile of Chocolate, as this was wrong
- The cocoa pile claimed to be a pure cocoa powder pile, but was
actually just chocolate that was dumped on the floor.

Removed a fair amount of relative pathing, but there's still more to go.
- This is a big undertaking, I'm planning to just do a bit here and there as I touch the offending files rather than try to plow through it all in one go. Some of the relative pathed files are huge.

:cl:
tweak: Chocolate can now make you fat, as expected.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Hardcore changelog. :+1: 

I'd be in favour of  making hot chocolate and chocolate just one reagent, but I'm not quite sure how that would impact things.

**Comment by Gummin** [comment]
Love the 2000 code change for Cocoa Cleanup :+1:

**Comment by TullyBurnalot** [comment]
Choco-Science will resume shortly. :+1:

**Comment by FalseIncarnate** [comment]
The reason this seems like such a huge code change is because removing relative pathing requires adjusting the indenting on lines. The actual cocoa stuff is WAY smaller, probably not even 50 lines.

**Comment by Keilden** [comment]
Is it toxic to vulpa yet?

**Comment by Fox-McCloud** [comment]
>Is it toxic to vulpa yet?

No, that was shot down.

**Comment by Spacemanspark** [comment]
>Shot down.
Fox, the only one really against that was you.

**Comment by FalseIncarnate** [comment]
Actually, I was thinking once the organ PR is finished, we could potentially give Vulps and Tajarans special stomaches that make them sick when they eat chocolate. A transplant could then cure them of this affliction, and perhaps instead of toxins damage they instead just vomit. This would cause a short stun and then extra nutrition loss rather than kill them.

**Comment by VampyrBytes** [comment]
@FalseIncarnate 
I'm in the middle of a refactor of eating and drinking atm. Just an fyi as you're in a similar area, in it I've sorted out the relative pathing in oldchem's drinks.dm, so no need to do that one.
BTW, with my refactor what you said about special stomachs will be easy to implement and involve no snowflaking :smile_cat:

**Comment by FalseIncarnate** [comment]
I didn't touch drinks.dm, so you should be fine there (unless you meant chemical_reactions_drinks.dm in which case sorry). Make sure you account for the species diet stuff in your refactor if you change that area. It was a bit messy in spots but I did try to keep it contained. We'll probably shift that to organs too at some point.

This PR is done though, in case there was some confusion about the relative pathing comment in the description. That would be too time-consuming to include in this PR and thus wasn't planned for this.

**Comment by VampyrBytes** [comment]
Nah, we haven't touched the same files, it was just in case you had reason to go into drinks and saw the relative pathing there, didn't want you spending time doing work I've already done.
I'm not touching the regent processing in this refactor, which is where species flags comes in. I'm working on the snacks/attack and drinks/attack procs, moving stuff so the mob deals with the eating rather than the food which means more overriding and less if clauses, and breaking them down into smaller procs so they can reuse code rather than having 2 70+ line procs doing very similar things.

I did look at the on_mob_life's in food reagents, and thought there was probably a better way of doing it, but couldn't spot it straight off, so decided against it in this refactor. Different species having different stomachs and letting them deal with it definately sounds a good way to go

**Pull request merged**
