### PR TITLE
Food refactor/reorganization

### PR DESCRIPTION
**Pull request by FalseIncarnate**
This PR is largely a refactor / reorganization of food item declarations and icons into multiple smaller files instead of one or two very large files.
- Food item declarations have been split out of snacks.dm into multiple files such as pizza.dm, junkfood.dm, etc. to reduce the size and clutter of snacks.dm
- New food files have been placed into a new subfolder for organizational purposes, moved seafood.dm, candy.dm, and meat.dm into this same folder
- Split some icons out of food.dmi into new files such as pizza.dmi and custom.dmi (updated code to point to new locations as appropriate)
- Removed some duplicate sprites from food.dmi that were present in other files (such as containers.dmi) to reduce clutter

There are a few minor grammatical changes that are player-visible:
- Standardized capitalization on a few food items, many more still need to be standardized (started in this PR but will likely end up being completed in separate PR(s) due to number of items to standardize)
- Removed a duplicate definition of the poppy pretzel, combined the two different descriptions into one.

This PR is a refactoring and reorganization in preparation for future PR(s), and makes no changes to in-game behavior or balance of any food items. No changelog as only player-facing changes are grammatical or a small change to an existing description to account for duplicate removal.

### CODE REVIEW

**Comment by RyanSmake** [comment]
I-i-i-improper!

**Comment by FalseIncarnate** [comment]
Hmm, Travis failed because the nanoui part stalled. Will look into that later, probably just need to close/reopen to restart the check

**Comment by taukausanake** [comment]
So is there a good reason why the file paths are now "food_and_drinks/food/foods"? I would imagine that having them in the first "food" directory would be enough.

Maybe give junk food their own dmi file as well? There's no problem making too many files vs having too much in a file, is there?

**Comment by Fox-McCloud** [comment]
What do you mean, having all the food items in one gigantic file isn't a good thing?!

**Comment by taukausanake** [comment]
I can only grep so much before I have to quit.

If that's the case then just put EVERYTHING into one file. That should be fun :)

**Comment by FalseIncarnate** [comment]
I'll probably split the food.dmi file up further in the future, but removing what I did de-cluttered it fairly significantly.

As for the folder naming: I put the food type files in their own folder simply for organizational purposes for coders. There is no functional difference between them being in the food folder versus the new foods subfolder other than when you are expanding folders in the dreammaker sidebar or in file explorer. I can rename the folder if desired, I just used "foods" because it was a simple folder name for a simple folder.

**Comment by taukausanake** [comment]
It just seemed a bit weird is all. I would see no conflict with the files in /foods being with the other things in /food

**Pull request merged**
