### PR TITLE
ERT Armory rework

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds ERT armor/helmets (currently not on the map), as well as ERT backpacks and ERT jumpsuits (the ERT members now spawn with them). By MrSnapwalk: https://github.com/Baystation12/Baystation12/pull/6075.
2) Changes the Central Command access levels so they make more sense for the map we use, and so there's no more references to Creed. Also ensures all Central Command jobs are up-to-date, and adds some procs for syndicate access levels.
3) Reworks the ERT shuttle so it has a communication computer on board (in case the shuttle is called or needs to be called and the station's communication computers are broken), or the ERT needs to send a message to the station, and also adds some mounted rechargers.
4) Reworks the ERT armories. The medical and engineering armories now contain less filler equipment. The equipment's not too powerful, so that it's much more likely for an admin to open the engineering/medical armories in case of emergency. The security armory is fairly powerful due to the pulse weaponry (also present on the old map), and should mainly be opened for heavy Xeno threats or blobs. Also re-adds the heavy weaponry armory, so admins still have the option of sending in the really big guns without spawning them manually or calling a deathsquad (convenience).
5) Also adds two portable turrets to the ERT starting area. Now that they've been updated they should aid the ERT in securing areas, defeating blobs, etc.
6) Renames all instances of "plastique" to "c4".

It's not beautiful, but it's functional. If anyone has better design ideas, let me know. The corner tile in the airlock in the image below has been fixed.

2mhb33i

### CODE REVIEW

**Comment by Markolie** [comment]
@SamCroswell - heads up.

**Comment by SamCroswell** [comment]
Heavily disagree with the changes to the armory. The only filler content that's been removed is in the Engineering area -- And I've got plans to fill it with more useful items soon. It also adds a lot of needless items (Specifically in the weaponry area) that I made an active attempt to remove with my previous update.

Are the access-restricted doors behind the blast doors now?

I'll write a full response when I get home, but this'll have to do for now.

**Comment by Markolie** [comment]
The doors are behind the blast doors, as players will want to know whether or not the doors are open.

The heavy weaponry isn't pointless, as that armory isn't open that commonly. But when it is, the admins are in need of [b]heavy[/b] weaponry. As the old heavy weaponry armory was removed, admins have no way to provide the ERT with very heavy weapons except for spawning them manually, which doesn't make much sense. As such, having the armory on the map is better than removing it completely.

As you said, the old engineering armory was filler. The security armory was hardly useful either - the night vision goggles have been incorporated into the standard armory, and C4 isn't that useful to the ERT. The hand teleporter, combined with loyalty implants and thermal goggles isn't useful either - you need the implants during rev, but opening that door during rev would provide access to a pulse pistol. As for the current medical armory, well, there's no use in requesting it to be opened except for the combat hyposprays. Two bottles of chloral hydrate, a box of syringes, two syringe guns and two stasis bags are fairly useless and not worth the effort.

**Comment by SamCroswell** [comment]
I'd argue that the point of the current ERT armories is for when heavy weaponry is needed. Agreed, they needed adjusting -- But I ultimately think that implementing this new armory in such a way would be detrimental to ERT response times in the extreme. Simply too much crud to choose from, as was the issue with the previous ERT setup.

In short: If more firepower than what is available in our current ERT armory is needed I advise a DeathSquad.

Regarding the medical armory: What you said was mostly true, but nothing has changed with your update of that armory. Almost all of the equipment is exactly the same in there, minus the vending machine.

Regarding the engineering armory: I admit, most of the content there is filler. I've got plans to fix it, but I also have other things on my to-do list.

I request that, at least for the meantime, the map changes be left out of the PR pending changes to the current ERT armory.

**Comment by fj45** [comment]
Blergh, armour and helmet sprites are not very nice at all. ERT should ALWAYS be using their full hardsuit anyway.  Rest of that gear looks good though, a proper combat uniform would be a great change.

Portable turrets need a new sprite but should be fun to use. 

ERT area really needs to be bigger so there is more room to move. ERT shouldn't be crawling over eachother to grab gear or hop onto the shuttle,

**Comment by Fox-McCloud** [comment]
Ehh, not a big fan of this, to be honest; I really like the direction Dave was taking this in; specialized teams with low equip time and fairly limited access to equipment; would personally much rather give him the chance to fully flesh out his vision of how to make it rather than completely halt the process midway through.

**Comment by Markolie** [comment]
Regarding the jumpsuits, I'll leave those out if we're giving them to the Blueshield, I'm fine with that.

Regarding the map changes: I would argue that this is in line with where we want to go with the ERT: the recent changes that have been made have further improved the speed at which they can deploy. This map change does not change that: only if the doors are opened the deployment will slow down, but that doesn't happen very commonly, and admins would only open the doors if speed is not an issue. So when the doors are actually opened, the equipment inside should be worthwhile, and not just a collection of semi-useful items.

The ERT is still fully specialized  with low equip times and limited access to equipment, unless an admin chooses otherwise. And that is the point of the armory (and it is that way with Dave's armory). This just increases the number of options admins have.

Regarding the vision: I have always been and will continue to be against phased releases of features. Changes should not be made just for the sake of making them. The current armory is not up to standards and needs to be updated, and it should've been in the first place (as it's been nine days now). I'm fine with Dave creating a new PR after this one to to change the armory to his liking, but until then I'd rather have a more serviceable armor.

**Comment by SamCroswell** [comment]
My ERT change was never intended to be a phased release feature; I created the armories and knew they were lacking, but I didn't know _what_ exactly to put in them. The people I spoke to about it also couldn't provide any real answers or suggestions, so I put some filler gear (In the Engineering and Command armory specifically) until I could observe ERTs and see what they actually needed.

**Comment by Markolie** [comment]
Wait, you can equip them manually? Is that intended?

**Comment by SamCroswell** [comment]
Yeah, I did that intentionally. ERT suits are really only children of RIG suits so the flashlight functionality doesn't have to be copied, so far as I know, and the helmet retraction is a functionality for RIG suits. They can still be mounted on the suit, but it isn't mandatory.

**Comment by ZomgPonies** [comment]
Merge conflict, and I don't know if you two have reached a consensus on how to approach ERTs yet?

**Comment by Markolie** [comment]
Right now, I think we're best off making these map changes, and then Dave can put up a new PR with any changes he'd like to see afterwards. As it stands, this set-up is in line with what we're going for with the ERT, plus the map changes also include the CentCom access fixes. Nothing wrong with having these armories for the time being, as it also allows us to see how it's received by the community.

**Comment by ZomgPonies** [comment]
Fix the merge conflicts and I'll merge it in.

**Pull request merged**
