### PR TITLE
Makes goats female

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Makes all goats female.

## Why It's Good For The Game

All goats can be milked and have udders. They shouldn't ever be male. Very similar PR to #14025

## Changelog
:cl:
fix: All goats are now female.
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
#14025

**Comment by Carthusia** [comment]
wait...I could milk the goat in the kitchen this whole time?

I mean its not like id have risked it kicking my knees sideways for it, since i always toss that thing into maints to be someone elses problem for the shift.

But REALLY?! This whole time i COULD have?!

**Comment by SabreML** [comment]
...what about Pete? :eyes:

**Comment by KozackWolf** [comment]
Oh god... what have we been drinking from pete the goat... OH GOD!!! WHY DID I HAVE TO KNOW THIS IS A THING!?! Please merge this!

**Review by dearmochi — APPROVED** [review]

**Comment by S34NW** [comment]
g o a t

**Pull request merged**
