### PR TITLE
Removes red slime speed potion, adds slime speed treat

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do

- Removes the red slime speed potion
- Adds a slime speed treat
- Refactors some code to remove copy-paste

## Why It's Good For The Game

**Removes the red slime speed potion**

I believe it is a problematic item that causes a lot of issues when it comes to balancing armor. If a piece of gear has a slowdown, it (usually) has a very good reason for it; and if a hardsuit has no slowdown whatsoever, it is because the hardsuit itself is a rare one. 

Take the blood-red hardsuit for example. The user can remove its slowdown with a single click, but the trade-off is that it paints them a huge target in the eyes of security. The red potion removes such a constraint from _everything,_ it can be mass-produced, and heavily tips the balance in favour of anyone who has access to xenobiology versus those who do not (including the ERT).

In case of the latter, we could just make the ERT armor not slow them down, but then we make the ERT armor way stronger against other threats, like biohazards (where speed is not as important as against humanoid threats).

**Adds a slime speed treat**

To avoid just removing stuff from the game without contributing to it, introducing the **slime speed treat** (or monkey snacc), idea originally by @Edan52, I sprited it and coded it.

Adding water to red slime extracts, it results in a slime speed treat. You can tap a slime with it or if you are a slime, you can eat it.

It sets the slime's body temperature to 550 (allowing them to zoom around for about 20 seconds), sets them jittery for 15 seconds (it was a good treat!), and give the following visible message: `"As the grey baby slime (335) gobbles the slime speed treat, it starts buzzing with joyful energy!"`

The temperature gun can do the same, I am aware, but this is an alternative.

Feeding the slime:

https://user-images.githubusercontent.com/33333517/192590097-a070bc1b-3b6d-41c3-b7c5-73b19376dafa.mp4

Slimes can consume it themselves:

https://user-images.githubusercontent.com/33333517/192590534-707e9ec5-b5c6-4868-aef3-e5fba36288ed.mp4

**Refactors some code to remove copy-paste**

Removed some unnecessary `icon =` declarations, made a parent `attack()` proc to remove copy-paste from the other potions.

## Images of changes

**Monkey snacc**

image

**Slime speed treat:**

Videos above

## Testing

Slime speed treat:

1. Spawn in as a scientist
2. Spawn a `/obj/item/slime_extract/red`
3. Fill syringe with water, add to extract
4. Tap slime with the treat or be a slime and click on it

Spawned the following and hit slimes with it, to ensure my refactor did not break anything:

- `/obj/item/slimepotion/slime/docility`
- `/obj/item/slimepotion/sentience`
- `/obj/item/slimepotion/slime/steroid`
- `/obj/item/slimepotion/slime/stabilizer`
- `/obj/item/slimepotion/slime/mutator`

## Changelog
:cl: Miraviel, CornMyCob
del: Removed the slime speed potion from red slimes.
add: Added slime speed treat in its place, add water to a red slime extract to spawn it. Humanoids can feed it to slimes or sentient slimes can click on it to eat it.
/:cl:

### CODE REVIEW

**Comment by Norwes1** [comment]
Thumbs up. If some armor really needs a boost (ERT hardsuits, say), then let's consider this a wake-up call to do so. Either way, in a game where speed is life, being able to alter speed like this is literally paradigm-changing. Xenobio and Science have enough goodies already; they don't need to be able to make absurdly capable goliath-boosted Mining hardsuits to boot.

**Comment by lewcc** [comment]
One thing I'd like to note is that while armor is the clear beneficiary of slime speed potions (and I agree that red pot armor is problematic), this also applies to vehicles like ambulances and the janicart. Both of these could be sped up using red potions, making them slightly faster than before (which, for the ambulance, is near-uselessness). These vehicles will now have no sort of way forward in terms of speed increases. I know vehicle speed is a problematic issue for many reasons, but removing the only way to make them slightly more usable leaves them in the dust, so to speak.

That being said, I am still in favor of this since the armor issue *by far* outweighs the vehicle concerns.

**Comment by Miraviel** [comment]
> One thing I'd like to note is that while armor is the clear beneficiary of slime speed potions (and I agree that red pot armor is problematic), this also applies to vehicles like ambulances and the janicart. Both of these could be sped up using red potions, making them slightly faster than before (which, for the ambulance, is near-uselessness). These vehicles will now have no sort of way forward in terms of speed increases. I know vehicle speed is a problematic issue for many reasons, but removing the only way to make them slightly more usable leaves them in the dust, so to speak.
> 
> That being said, I am still in favor of this since the armor issue _by far_ outweighs the vehicle concerns.

This is a valid concern, if this PR is accepted by the balance team, then we definitely need to speed them up - one way or another (either by increasing their default speed or making an upgrade available via RND/cargo).

**Comment by komihe-ss13** [comment]
can slime people eat this or just the slime creatures?

**Comment by Leanfrog** [comment]
> can slime people eat this or just the slime creatures?

I want this even if it does nothing other than a bit of hunger, where my monki snacks at.

**Comment by Miraviel** [comment]
> can slime people eat this or just the slime creatures?

Sadly they cannot eat it, for all intents and purposes, these treats are potions.
I was considering making it into food, but the effects are so disruptive, force-feeding anyone with it would be problematic.

**Comment by hal9000PR** [comment]
> One thing I'd like to note is that while armor is the clear beneficiary of slime speed potions (and I agree that red pot armor is problematic), this also applies to vehicles like ambulances and the janicart. Both of these could be sped up using red potions, making them slightly faster than before (which, for the ambulance, is near-uselessness). These vehicles will now have no sort of way forward in terms of speed increases. I know vehicle speed is a problematic issue for many reasons, but removing the only way to make them slightly more usable leaves them in the dust, so to speak.
> 
> That being said, I am still in favor of this since the armor issue _by far_ outweighs the vehicle concerns.

someone could make vtec speed up vehicles. but vehicle code isnt great.

**Comment by Christasmurf** [comment]
>_It's all fun and games until you have to mute the game because some moron is trying to make half a million sentient slimes to test his stupid gimmick item on and you get notified every. Single. Time. With a loud sound._ 
image
problem solved

**Comment by AffectedArc07** [comment]
No more fast table

**Pull request merged**
