### PR TITLE
Makes security officers/ warden start with disablers.

### PR DESCRIPTION
**Pull request by Spacemanspark**
Ohhhhhh this is going to suck.

Players:
 -Security officers and wardens will now start with disablers instead of advanced tasers. There are still three in the armory.
The Head of Security will keep their instastun, mostly due to the fact that they SHOULD be strong, and until further changes to remove instastun happen (If ever), they should keep it.
Admins:
-Enjoy the large wave of adminhelps of "WHERE'S MY TASER?!"

Everyone knows my opinion on this, so I'm not going to comment even once in here.
Edit: Yes, I'm pretty aware this likely isn't happening. Also, before I forget: @tigercat2000

### CODE REVIEW

**Comment by TheDZD** [comment]
A lot of the arguments brought up in #1174 are going to be relevant here.

**Comment by FalseIncarnate** [comment]
:-1:

I'd support switching the default mode of the advanced/hybrid taser (whichever name it goes by now) to start in disable, but effectively removing the electrode stun from officers (especially late-joiners) is going to cause more problems than it fixes.

**Comment by Fox-McCloud** [comment]
This was literally shot down here quite hard: https://github.com/ParadiseSS13/Paradise/pull/1174

**Comment by ZomgPonies** [comment]
:-1:

**Comment by fj45** [comment]
This is not how it should be done. Any removal of insta-stun needs to be a complete overhaul, not removal of one or two sources.

I support removal of insta-stuns but not this way.

**Comment by KasparoVy** [comment]
:-1:

**Comment by ZomgPonies** [comment]
This PR is DOA.

**Pull request closed without merging**
