### PR TITLE
Floor Tile Updates

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
Ports over the floor tile sprites from OracleStation, *F*
This was done for a few reasons:
- They have a cleaner aesthetic
- They are easier on the eyes
- They fit this game more (In my opinion)
- I was porting the bluespace tiles and thought it looked better with all of them

**Images of sprite/map changes:**
Instead of pasting **EVERY** single tile diff, I made a before and after webmap of the station with the new tiles. https://affectedarc07.co.uk/IconDiff/
***NOTE: This will take a while to load as its hosted on my own connection, not GitHub***

Bluespace floors (Cant be conveyed on a webmap):
dllxalxzny

**TODO:**
- [x] Port floor sprites
- [x] Update inhand sprites
- [x] Mech charger floors (In 2 files for some reason?)
- [x] Outpost floors (Again, 2 files for some reason)

**Changelog:**
:cl: AffectedArc07
tweak: Floor tiles have been given a new coat of paint
tweak: Bluespace floor tiles no longer look like they will kill you
/:cl:

### CODE REVIEW

**Comment by Mithrandalf** [comment]
The bluespace tiles seem weirdly cut off on one side each; what's up with that?

**Comment by KasparoVy** [comment]
BS tiles missing a side is a bit wack but I support cool floors

**Comment by Dinarzad** [comment]
I like most of these better, and bluespace not having the eye fuckingly green flashing is very pleasent.

The only one I don't care much for, is the reinforced floors. I prefer the hexagonal lookin' one we got already, but aside that, I think these are pree good.

**Comment by AffectedArc07** [comment]
@Mithrandalf @KasparoVy The reason the tile looks like that is because of standard tile design. They have black lines on the right and bottom
image
In the bluespace tile, I followed this through, but do think it looks a little jarring:
image

I could do this on the bluespace tiles though:
image

**Comment by AffectedArc07** [comment]
Updated to change brig tiles

New bluespace tiles:
v5cncs6ins

Outpost tiles (Didnt post before)
image


Inhand tiles:
rrwrjoskaa

**Comment by KasparoVy** [comment]
Nice, yeah that 1 side made the difference, looks a lot better imo in the configuration you just showed

**Comment by Shadeykins** [comment]
Not a fan, personally. I don't mind the high-contrast tiles for some areas, but having all the tiles be high contrast like that is just, well.. Blah?

**Comment by Ty-Omaha** [comment]
I like the bluespace tiles in the + shape

I don't like any of the other tiles and think they look worse compared to the current ones which have shading

**Comment by Agameofscones** [comment]
Having the bluespace tiles not be that horrid green flash (and also a HS reference, since the style is copied lazily from the cueball hat) is very nice. I'm all for.

**Comment by taukausanake** [comment]
You know what might be crazy (and horrible if it works) is if you could make tiles smooth like how carpets do to get the blue glow line all around a tile even if different tiles. Just a stupid idea I had.

But I do like the blue glow effect. Almost think they should have a low light value but not sure if Bluespace stuff actually glows

**Comment by variableundefined** [comment]
I agree with Ty that most of these tiles are visually inferior.

**Comment by Bram961** [comment]
Oh for the love of god these plating tiles are back. Just no, we've already gone over them in a smoothing PR by Sam where they were changed in a fixing PR. The fixed icons were then reverted when the code to shade the tiles and give them depth was causing issues.

The rest of the tiles have a simplified shading that just doesnt fit the rest of the game.

**Comment by Mithrandalf** [comment]
No sir, I don't like it

**Comment by Aurorablade** [comment]
yeah. Really. Really do not like the tileings..espically the maint tiles..or the fact they look like no slip floors. I mean bluespace tiles..okay. Rest of them. No.

**Comment by variableundefined** [comment]
The PR will be closed as the floor tiles are mostly visually inferior and lose details, most of them has worse or no shading at all. Similar floor tiles have been rejected and reverted in a PR made by Purpose previously.

**Comment by KasparoVy** [comment]
Maybe we should see if Polaris/Bay and Co. Have any.

**Pull request closed without merging**
