### PR TITLE
Resprites the Defibrillator

### PR DESCRIPTION
**Pull request by roarbark**
## What Does This PR Do
resprites the defibrillator from the ground up. overlays for charged, emagged, no cell, charge meter, most of them animated. also fixes some of the overlays not updating properly.

## Why It's Good For The Game
ueeeeeee duuduuuduuduu bzzzzzt

## Images of changes

https://user-images.githubusercontent.com/41054538/190252704-189a741e-9fae-44df-a5fe-1645a05366f2.mp4

## Testing

https://user-images.githubusercontent.com/41054538/190252906-a1a7c6ed-ecec-4331-8942-048a4bbb1379.mp4

## Changelog
:cl:
imageadd: new sprite for the defibrillator
/:cl:

### CODE REVIEW

**Comment by Hematoma** [comment]
While this is more detailed it's uglier, no longer matches the in-hand sprite, and how dose this look like equipped to the backpack slot?

**Comment by McRamon** [comment]
While its good that it brings the defib to a top-down view, this is not really an enough of an upgrade in quality. I would prefer defib to be less flat and have more interesting shape, this is basically a squrare with a black single pixel wide wire, which is not a great thing to use in sprites.

**Comment by Miraviel** [comment]
> While this is more detailed it's uglier, no longer matches the in-hand sprite, and how dose this look like equipped to the backpack slot?

"Uglier" is not constructive feedback, it's like saying "your code is bad". Be more descriptive about your comments, otherwise you are just being mean.

When it comes to sprites, what is wrong with it? The shape? The colour palette? Its size?

**Comment by Calyxman** [comment]
Charge bar should be a bar like the original. This one has less depth, less bulk and shock paddles are thin. Looks more like a radio or boombox than a defibrillator.

**Comment by roarbark** [comment]
@Hematoma 
> While this is more detailed it's uglier, no longer matches the in-hand sprite, and how dose this look like equipped to the backpack slot?

oh, yeah. i'm currently looking into inhands and back sprites. whoops.

also when you say "it looks ugly" with absolutely zero argumentation behind it what most spriters hear is "this sprite isnt familiar to me and i havent taken the time to properly criticize it beyond that bias."

@McRamon 
> this is not really an enough of an upgrade in quality

image

but like have you *seen* the old defib sprite?

> less flat

i feel i gave it enough plasticity with the colour contrast between the sides.

> more interesting shape

google "monitor defibrillator" (as opposed to an AED, which is our handheld defi), you get two pages of white rectangles, exactly this shape. i think sprites are allowed to be rectangular some times. crates, lockers, frames, walls. i feel like forcing this into another shape somehow in 3/4ths would hurt the sprite a lot. beside that, the sprite has more than just the strap to break up the box: feet, a handle, paddle mounts.

i distinctly chose against making the monitor slanted because i would have to sacrifice the ecg, which i feel adds a lot more to the sprite.

@Calyxman 
> charge bar should be a bar like the original

it is. its just not a whole rainbow plastered on the front like in the original

> This one has less depth less bulk and shock paddles are thin

yes, the intention was to reduce the size of the sprite. defibrillators are not that big, and even to scale its still too large.

> Looks more like a radio or boombox than a defibrillator

*despite the ecg, shock paddles and general colour choice?* like, does this really look like a boombox to you?

**Pull request closed without merging**
