### PR TITLE
Rebalancing of Blob Factory

### PR DESCRIPTION
**Pull request by Robertha89**
Reverts https://github.com/ZomgPonies/OldParadise/pull/260 to give blob's that early threat to people without internals, and as a balance due to explosive decompression not being thing anymore. Blob Spores can be cured via 45 units of atrazine. Also will cause shorter blob rounds, and as an random event give it a real threat. Also reducing blob spore health, cause, they just spores, blob zombies are the real threat.

### CODE REVIEW

**Comment by TheDZD** [comment]
If anything, I would reduce the damage per hit on blob zombies rather than nerf the spores, blob zombies are incredibly powerful for how simple it is to obtain them, while spores are reasonably weak.

**Comment by Earthdivine** [comment]
yea, a big reason I believe the Regent was taken out was "FREE ANTAG GIVE ME!" while also making it look legitimate.

I honestly think the blob zombies are fine and the spores should have the reduced health, as it is incredibly easy to spam the spores and have them slaughter the crew. This makes that first kill for blob super important rather then just "only build factories"

**Comment by Iamgoofball** [comment]
:-1: to reducing the health

:+1: to everything else

**Comment by Fox-McCloud** [comment]
I don't think this should should have a disease reagent in it.

People will literally hang around to deliberately infect themselves so they can help kill the crew.

**Comment by Robertha89** [comment]
This here should fix that issue. with spores being higher chance, i did consider adding space lube, also i would like feedback on some of the reagents.

**Comment by Fox-McCloud** [comment]
Eh--not a fan of this to be honest---Blob needs to be updated, for sure, but I don't think that's the best way to go about it, especially when blob has largely already been balanced elsewhere.

**Comment by fj45** [comment]
https://github.com/ParadiseSS13/Paradise/issues/826

**Comment by Iamgoofball** [comment]
Uh, aren't blob zombies NPCs though?

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

They are.

**Comment by ZomgPonies** [comment]
#968 is a better way to balance them, keep the discussion going there, especially with regards to some sort of 'infection' thing the AI has to watch out for.

**Pull request closed without merging**
