### PR TITLE
[WIP] Dog Borgs

### PR DESCRIPTION
**Pull request by tigercat2000**
This adds three new borg modules, refered to as Dogborgs. They
look like giant dogs, and have a 64x32 sprite. These dogs currently come
in three varieties: Security, Medical, and Janitorial.

Features common to all dogs:
 - A pair of jaws which serves as a melee attack.
   - Secborgs and emagged mediborgs/janiborgs have a more powerful
   version of this.
 - Boop Module
   - This allows them to detect reagents in a container, and detect any
   oddities in the atmosphere around them (same as an atmospheric
   scanner). They can also boop people.
 - Synthetic Tongue
   - This functions basically as a mop. You can clean up cleanable
   decals, eat trash & energy cells for energy, and lick people's faces.
   - This can be converted into a stunbaton for emagged borgs.
 - Built-in sleepers.
   - These come in three variants for each dog module:
    - The Portabrig
    - The Medbelly
    - The Garbage Compactor.
   - The medbelly acts as a sleeper, it stabilizes patients and allows
   you to view their critical information. It can also inject things
   like a sleeper can.
     - The portabrig functions similarly, but it is unable to inject
     reagents.
   - The garbage compactor is able to consume ~~both people~~ One person at a time as well as items.
   There is a maximum of 32 items in the compactor at any one time.
   - The sleepers have a built-in self-cleaning mode, which fills the
   chamber with acid to destroy biological material and nonorganic
   material alike. However, unless overridden with an cryptographic
   sequencer, this is unable to be triggered while the sleeper is
   occupied by a living being.
   - You can resist out of any of these on a 1 minute timer, so long as you aren't incapacitated (stunned/weakened/dying).

Module specific features:
 - k9 is the security model of dogborg.
   - Cyborg zipties.
   - 10 force big dog jaws.
   - A stunbaton linked to it's internal power cell.
   - Police tape.
   - Cyborg disabler.
   - EMAG: Mounted laser.
 - Medihound is the medical model of dogborg.
   - Small jaws.
   - Health Analyzer.
   - Mini fire-extinguisher.
   - Borg hypo.
   - Syringe.
   - Beaker.
 - Custodial Hound/Scrubpup is the janitorial model of dogborg.
   - Light replacer which recharges in a charging station.
   - Holosign creator.
   - Cleans the turfs it walks over like a normal janitor borg.

Powergamer's wet dream section:
 - Small jaws do 5 damage when not emagged, 10 when emagged and toggled. Mediborg/Janiborg.
 - Large jaws do 10 damage. Secborg.
 - Emagged tongue has a 4 tick stun.
 - It takes almost exactly 2 minutes for an unarmored full-health human to expire to the cleaning cycle.

This includes a significant refactor to how cyborg modules are handled-
They are no longer hardcoded into a switch() in the pick modules
function, but rather are based on the module object itself. This
shouldn't break anything.

Gifs:
https://i.imgur.com/ThL1kFL.gifv
https://i.imgur.com/k8YZlv8.gifv

https://github.com/VOREStation/VOREStation/pull/28
:cl:
add: Dog borgs! Bork some more! Medicla, Security, and Janitor flavored in stores now.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
img

**Comment by Fruerlund** [comment]
These rock. 

Only downside is the huge sprite. Love to have them proper dog size

**Comment by scrubmcnoob** [comment]
Man's best friend in space.
This obviously conflicts with Fox's PR of wanting to nerf sec borgs.
Maybe make these modules a RnD board along side a normal sec borg if Fox goes through with the compromise? Either way, these look cool.

**Comment by tigercat2000** [comment]
@scrubmcnoob I'll probably just include the K9 module under the security borg config option if that goes through before this.

**Comment by EldritchSigma** [comment]
This looks really cool. Only issue I have with those is that the secdog-borg might obsolete the regular sec-borg due to its immense utility of a porta brig. The others look really good though. Medidogs could help the Paramedic getting people and the Trashcompactor dog could help the janitor, or just drive him into suicide. I really like it.

**Comment by tigercat2000** [comment]
@EldritchSigma I am open to suggestions on balance- I want these dogs to be reasonable alternatives to their normal borg counterparts with their own advantages and disadvantage.

**Comment by Allfd** [comment]
I think if we may want to reconsider all the things that have people in the things.

**Comment by tigercat2000** [comment]
@Alffd I can see perhaps changing the janitor borg, but the sleeper is pretty much the core part of the security and medical modules. The ability to transport people around is intended to be the main reason why anyone would ever use these over the normal borgs.

**Comment by scrubmcnoob** [comment]
@tigercat2000 Maybe include a section in the OP describing how these things have different trade offs compared to a normal borg?

**Comment by KasparoVy** [comment]
What a beast. I think they're utterly fantastic, but I do wonder if they have a place here (as much as I'd love to see them). I wonder... As some form of trade-off, would it be possible to make these borgs vulnerable to some sort of 'mobility damage' as they've got four somewhat vulnerable limbs?

**Comment by Kyep** [comment]
What the heck is going on here?

We just had a big debate about whether secborgs were too powerful, including a PR to nerf them. Now we're considering introducing a whole group of new borg types with abilities borgs have never had before? What?

The really crazy part, though, is that these are literally furry vore-borgs. Introduced by someone known to have a thing for vore, with the unique ability to put people in their stomachs for various reasons. More space is devoted to the vore/sleeper feature in this PR's feature list than literally every other feature in the list combined. Even the sprites, I suspect, may be from vorestation. This really looks like someone with a thing for vore, porting vore-borgs to Paradise, and spending lots of space describing all the neat reasons they have for keeping crew members in their stomachs. 

I'm not sure if the world has gone mad, or I have. But there is definitely something mad going on here.

**Comment by KasparoVy** [comment]
:rofl: I was wondering where that comment was.

**Comment by Spacemanspark** [comment]
What

**Comment by granodd** [comment]
There are some things better left un-ported, Tiger...

Honestly if we're going to port anything from Virgo (or Bay Code for that matter) it should be mufuggin ninjas.

**Comment by SheepFighter** [comment]
My Imp of the Perverse really wants these to be merged...

I mean, it's the egalitarian thing to do. We have plenty of humanoid borgs. It's time for vulps to get some representation!

**Comment by Allfd** [comment]
I mean, the sprites are detailed and great and all... But.. That gif...  🤢

**Comment by SheepFighter** [comment]
> I mean, the sprites are detailed and great and all... But.. That gif... 🤢

What? You'd rather we resort to the old Bluespace canard? The borg has to store that chap *somewhere*. It's more immersive this way!

**Comment by Necaladun** [comment]
Absolutely love the idea of K9 robots in theory, as per the cyberdogs of the Adeptus Arbites, K9, etc. Siccing even one of these on someone is great.

The 1x2 sprite is weird. I don't know how that will go. It'd be great if it could just be fixed to 1x1 and still maintain the look but I don't think thats possible.

It looks great, but the organic nature of the belly is...well, more xeno than borg, and kinda body horror. I think a more hard-edged look of a sleeper would be better suited. More of a robot storage device and less....swallowy.

As for their balance when it comes to regular sec borgs, crew, etc, all these values can be tweaked and discussed here. Having different abilities to regular borgs doesn't necessitate them being more powerful. I personally picture something lighter (less health, etc) than regular borgs, but faster. How the sleepers, bite, etc, can all work can be changed and discussed. 

The bite doing regular damage could be something unlocked on code red/by robotics/the robotics console/etc, as with crewsimov laws there's no need to use them except against blobs/xenos/etc. It'd be cool to see some kinda..."off the leash" ability for the RD to give them, at a risk of course.

**Comment by Bram961** [comment]
I like the idea of different borgs but looking at it I don't think this is the way. Especially since some of the features are so obviously from vore and the 1x2 icons are both a bit odd and animated in to much detail strangely enough, it doesn't feel like it fits on the server.

**Comment by alexkar598** [comment]
Why should somebody choose secborg instead of k9?

**Comment by SheepFighter** [comment]
@alexkar598 
https://www.youtube.com/watch?v=Hu7OiJpnlUs

**Comment by Earthykiller127** [comment]
Hey, I know you just did this to further satisfy your dog fucking fantasies but if you really want a dog just throw a paper with links to furry porn in the central hallway and wait 45 seconds

**Comment by MrFroztee** [comment]
I can't WAIT to play as a family friendly Janidog and consume people for fun on our medium RP server! 

Hopefully, you implement a feature where the crew that are placed into the sleepers can be deposited into some sort of egg vessel, so you can make dropoffs of patients and prisoners.

**Comment by Necaladun** [comment]
@MrFroztee
Drop the passive aggressive snipes there. If you have an objection to this, state is plainly and simply. This'll be your only warning here.

**Comment by deep-fried-faceplant** [comment]
These seem really unbalanced for paradise, especially the security borg. I don't see any downsides to picking a borg unit over the standard one. It's cool, but rule of cool doesn't mean we should have it.

**Comment by TullyBurnalot** [comment]
@deep-fried-faceplant This is still very much unfinished and up for discussion, so take it with a reddit's pinch of salt.

**Comment by deep-fried-faceplant** [comment]
I need more than a pinch for reddit, honestly.

**Comment by DesolateG** [comment]
Ah yes, the vore dogs..

Well hey at least people will stop complaining about sec borgs of these are added.

**Comment by FlattestGuitar** [comment]
The modules are straight up upgrades over regular borgs. Why would anyone *not* pick these?

The sprites. Don't at all fit the style of the server. They are inconsistent with everything but the darn xenobio panther which shouldn't even be there.

Also vore.

**Comment by Qustinnus** [comment]
*scream

**Comment by Aurorablade** [comment]
I think they can be made to fit.

**Comment by LightFire53** [comment]
Some potential balance thoughts: Could make them more fragile than regular borgs. Maybe reduce the escape time on the belly feature (currently 1 min, maybe halve that.)

The main concern is that we have to keep regular borgs relevant, but make these dogbots not irrelevant.

**Comment by SheepFighter** [comment]
Also, for all those who are horrified at this thing's existence, may I draw your attention to the following PRS?
https://github.com/ParadiseSS13/Paradise/pull/7000
https://github.com/ParadiseSS13/Paradise/pull/3333

This PR is, in all probability, no more serious than those were.

**Comment by LightFire53** [comment]
@sheepfighter exceat this is a serious PR. That said, it's in a very malleable state right now. Numbers are good to be changed, ideas on modules, that kind of thing. Give us input, not dismissal/memes. Or if you are giving dismissal, explain why. Why does X not work?

**Comment by SheepFighter** [comment]
> exceat this is a serious PR. That said, it's in a very malleable state right now. Numbers are good to be changed, ideas on modules, that kind of thing. 

I'm confused. Where is there any indication that this is serious? Tiger's playing it straight, but he did that with the two I linked as well.

> Give us input, not dismissal/memes. Or if you are giving dismissal, explain why. Why does X not work?

Anyhow, assuming you're right, I'll give input: 
The uh... Digestive elements are borderline rulebreaking. The borgs from a server literally dedicated to the vore fetish. I'm not against porting non-erotic features from ERP servers, but these are implicitly sexual. 
Yes, you could remove the eating bit, but that seems to be the whole point of this. As Tigercat said:

> The ability to transport people around is intended to be the main reason why anyone would ever use these over the normal borgs.


Additionally, they're just too powerful. No other borg modules have lethal weapons at roundstart. Nor do they have sleepers. That's reserved for the Odysseus mech. If these are merged, it might well be obsolete.

Additionally, while I'm not an enthusiastic proponent of porting Peacekeepers (they really need a testmerge,) I think there's general, albeit not universal, concern over Secborgs' being OP. This will only worsen that.

**Comment by Necaladun** [comment]
This PR is serious. The whole WIP and open to discussion part was to see how the idea of robotic dogs, ala cybermastiffs etc, could be implemented and what reception they've had. We're in no way attached to the vore aspects of it that people are flipping out over, which is all able to be changed. A lot of that depends on spriting.

It does seem that people won't be able to get over the origins of this and the connotations, which has meant any serious discussion about how to balance them in regards to modules, speed, health, etc, has been ignored in favour of cheap shots.

To get things back more on track, my major concerns with them are:

A: The sprite seems too big. I don't know how much these can be trimmed down to keep the general look. Input from sprites would be welcome.
B: I don't think the animations will mesh well with everything. They'll really stand out.
C: It'll be very difficult to make these equals to borgs, not so much better no-one players regular borgs, or so much worse no-one bothers. They'd need to have their own niche that is separate but equal.
D: Being able to delete someone has some serious concerns for balance (And yes, some pretty gross connotations.)

**Comment by SheepFighter** [comment]
> It does seem that people won't be able to get over the origins of this and the connotations, which has meant any serious discussion about how to balance them in regards to modules, speed, health, etc, has been ignored in favour of cheap shots.

It doesn't help that Tiger has a history of ERP-related joke PRs, nor that he has said that the eating bit is the whole point of this one. I can only speak for myself, but I wasn't trying to make cheap-shots. I genuinely thought he was joking (and I'm still not entirely sure that he isn't.)

> A: The sprite seems too big. I don't know how much these can be trimmed down to keep the general look. Input from sprites would be welcome.
B: I don't think the animations will mesh well with everything. They'll really stand out.
C: It'll be very difficult to make these equals to borgs, not so much better no-one players regular borgs, or so much worse no-one bothers. They'd need to have their own niche that is separate but equal.
D: Being able to delete someone has some serious concerns for balance (And yes, some pretty gross connotations.)

All good points, these. 

Out of curiosity, couldn't these just be reskins of their non-canine counterparts? Borgs already come in all shapes and sizes. Why do these need to be functionally different? Yes, they're a tile wider than regular borgs, but that's just a drawback.

**Comment by Aurorablade** [comment]
They don't have lethals at round start unless they are emagged that fast

**Comment by SamHPurp** [comment]
I don't think I can object more highly.

This looks ridiculous, has no place.

I didn't initially reply because I assumed this was yet another meme PR from @tigercat2000 ... but then saw the refactoring as well.

**Comment by SheepFighter** [comment]
> They don't have lethals at round start unless they are emagged that fast

They do have them, unless I'm missing something. Their jaws can do damage. I don't believe any other borg model has that capability. 

> Small jaws do 5 damage when not emagged, 10 when emagged and toggled. Mediborg/Janiborg.
Large jaws do 10 damage. Secborg.

**Comment by SirBloodBuske** [comment]
Why not add a clown module while were at it.

**Comment by MrFroztee** [comment]
> They do have them, unless I'm missing something. Their jaws can do damage. I don't believe any other borg model has that capability.

@SheepFighter
Janiborg has a mop for a weapon, but that's about it

**Comment by SheepFighter** [comment]
@MrFroztee

I knew that some servers had that, but I didn't think we did. What are the stats on it?

**Comment by MrFroztee** [comment]
@SheepFighter

Not sure, but I know I killed a guy pretty good once, with it.

**Comment by MrFroztee** [comment]
@SheepFighter

https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/mop.dm

Standard mop does 3, advanced mop does 6

**Comment by SheepFighter** [comment]
@MrFroztee Good to know. 3-5 doesn't seem so unreasonable, though I'm not sure about 10. The fact remains that this would make them an improvement over their counterparts.

**Comment by Necaladun** [comment]
I don't see a particular problem with 10 damage jaws compared to the damage of engi borgs tools, harmbatons, etc.

**Comment by MrFroztee** [comment]
Certainly seems lesser in comparison with what the Peacekeeper can do when emagged

**Comment by SheepFighter** [comment]
@Necaladun Good point.

**Comment by Da-Dman234** [comment]
I'm still taking this PR with a grain of salt since I really have no idea if it's serious, but I'll toss in an offhand suggestion/observation. I'd like to know what exactly the difference between a medical K-9 and Odysseus is? I kinda have a problem with the fact it pretty much completely invalidates it while probably costing a fraction of the price. The only upside I see an Odysseus having is its' ability to synthesize chems, which in reality is only ever used for nefarious purposes. If this is a real thing honestly I would only even consider adding the Security K-9 as that's the only thing I could really see lore even remotely making sense for (if that's a thing we even still care about)

**Comment by ProperPants** [comment]
If this PR is real, I'm moving to Baystation.

**Comment by SamHPurp** [comment]
Not to be so dramatic as ProperPants, but.... genuinely this and the peacekeeper borg is making me want to go somewhere else... with blackjack and hookers.

That might count as a pro for some in merging these.

**Comment by Necaladun** [comment]
The Ody is pretty lacking as it is IMO, and is rarely actually that useful - it generally arrives later it the round if at all, has limited amounts of people using it (generally locked to the damn CMO from what I see), and is only really useful for niche situations. Compare the mining borg to the ripley. 

As it is, I see it's niche being a search-and-rescue borg, as opposed to the current borg which is more of a surgeon and medbay assistant. Giving it less ability to heal (hypospray, etc) might be needed for balance there.

**Comment by Necaladun** [comment]
I'd again like to remind people to focus on discussing the actual merits of the PR and how to make it fit with the station, balanced, etc. Threats to leave the server over this PR are quite ridiculous, and does not make for good discussion on the git. If it's so terrible that you won't want to play on the server with it at all, then it should be easy to succinctly state it without being toxic.

This is the last time I'll be asking.

**Comment by taukausanake** [comment]
I personally LOVE this. Those sprites are amazing even if the movement sprites look out of place on the server. I will agree that the belly sprite is way out of place though. That is literally VORE all up in there and really doesn't fit. I would imagine the extra wideness of the sprite/borg to more than make up for the size a mob would take up in there.

The loadouts for each one sound fair to me. I think they all work. Kind of sound more like an antag's best friend but I can see them working for their other departments.

Can mobs see outside from inside a robodog's insides? Need to ask as we don't see this in the gifv images.
(is gifv an image or video...)

I'd almost think of these as being borgs that need a human master along with if not besides the AI. Might not go well but it is a dog after all. Could be interesting.

Not sure if these should be round start. Like said above, might limit the use of normal borg modules. R&D but printable only in Robotics would be best.

@tigercat2000 
> Medicla

**Comment by Dinarzad** [comment]
Here's the thing, I have seen this server turn it's nose up at a lot of interesting PRs or mechanics because "It doesn't fit the vision we want for the server."
And that's cool, can't have everything on a single server, it'd be a jumbled mess if you did.

But if we're seriously about to implement the Vore-Dog borgs, I am going to have a very public conniption fit about what that vision ACTUALLY is, because at this point I don't see how this fits ANY of the previous changes or PRs done. Especially when in another PR the whole 'fat people can eat people' thing was being removed, due in large part both to balance concerns and "Fetish" concerns, and now we're here adding a robot dog that eats people and gets a belly sprite in the process, as a primary function.

> It does seem that people won't be able to get over the origins of this and the connotations, which has meant any serious discussion about how to balance them in regards to modules, speed, health, etc, has been ignored in favour of cheap shots.

There is no connotation or implication though. This is not implied or vague in any respect. The robot dog shoves someone down his throat and into his "stomach". As well,  Notions about how to balance them or doing number crunching is all a very moot point if they're not even added to BEGIN with, and that isn't a finished discussion as far as I know.

**Comment by SirBloodBuske** [comment]
what is happening to this server

**Comment by SamHPurp** [comment]
The fact that people find this so offensive to their sensibilities that it could be a deal breaker is something that should factor in, Neca, so I am going to have to disagree with you.

However you wanted a blow by blow, so here you go:

----

Two tile wide sprites look fucking awful, and behave even worse code/gameplay wise. Remember all the outrage about the growth serum? Its that times 100.

Adding vore-dogs is going to do wonders for public perception of a furry station. Now while that isn't a problem in and of itself, ignoring the public image is a mistake a lot of people are making right now, its in vogue. Do at least give half a mind to it.

These vore 'dogs' eat players, **swelling their stomach's sprite**, again something vore fetishists adore. The PR author, and maintainer, have said that the point of this PR is entirely the eating of players. Someone who very recently spent ages getting merge-ready a full on vore system. This was clearly done to gauge opinion, and since being elevated to maintainer have decided to push further with it.

Obvious conflicts with the Peacekeeper PR's intention of 'removing sec borgs', which is entirely un-addressed, and if anything makes things worse?

The animations look so out of place with the entire rest of the server. Just go watch the gifs.

There is still a huge amount of balance tweaks and more importantly situational differentiation between why you'd pick a sec borg, vs this vore animal borg, which has not been clearly defined in any way in the PR. Looking at the modules, I cannot see a single reason I'd pick the regular borgs over these clearly upgraded borgs.

There have been recent PRs / annoyance that fat people can eat people... so now we want to add even more vore mechanics?

----

This culminates in the fact that if this is indeed the direction the server wishes to take, understand that its a stepchange that may cause a further hemorrhaging of players, degradation of public opinion, and actively promoting sexual fetishes that many consider perverse.

**Comment by Da-Dman234** [comment]
Alright, since this seems to be being taken seriously.

I don't really see any way to balance these other than by forcing them to serve a very niche role. For the Medi-K9 making it a search and rescue I feel is appropriate. I still have concerns regarding completely invalidating the Ody, but that's for another time. I would remove the Hypospray, syringe, beaker and give its' Medibelly (which DEFINITELY needs to be resprited btw) the ability to dispense inaprovaline. If it's also going to fufill a search and rescue role I don't think a crew moniter is unreasonable as well.

As for the Jani-K9, I would say scrap it. All it's going to do it present a powergamier alternative to our current janiborg which does its' job incredibly well. Nothing it can do will even come remotely close to being as easy as simply driving over dirt in order to clean it up. I see nothing but the potential for abuse in adding it unless it's majorly changed.

And finally the Secu-K9. I don't really see this as ever being able to serve a niche as most every sec officer is equipped to deal with any situation they come across, so I have a different proposal (while keeping them at roughly the same strength). Severely limit access to these. I would suggest one of two ideas, either make a new karma class that starts with a single one as a companion, or create a new area in sec that serves as a sort of kennel to be activated in emergencies, the idea being that CC (or whoever) is able to activate the dogs remotely in order to buff the sec force when needed (something I see being particularly useful during sling rounds). It would pull from the ghost pool like a regular posibrain does, and I believe addresses every problem brought up so far, though I do still have concerns about the port-a-brig.

**Comment by taukausanake** [comment]
> growth serum? Its that times 100

That's literally a lie and you know it. You can have so many more problems with growth serum than with double wide sprites. I haven't seen anyone complain about the panther sprite (but I will say it is rare to see)

> very recently spent ages getting merge-ready a full on vore system

Wasn't that on April 1st...? I thought it was funny.
So are we saying that Tiger is secretly a VORE sympathizer?

**Comment by Rapidvalj** [comment]
🤔 x 💯

**Comment by Necaladun** [comment]
I'd like to remind people this is a WIP so such issues can be discussed. This won't be speedmerged in less than 24 hours, will unlikely be merged within a week, if at all. It's here so we can look at the possibilities such code will allow and see what people think.  

The removal of sec borgs has never been decided on, agreed on, or merged. As things look, I doubt we'll be removing them all together. 

As for public perception of a furry station, I'm really not fussed what people on reddit think. That's irrelevant to me. If people use this to indulge in a sexual fetish, they'll be banned, just like with fat cannibals, and just like xeno hunters. Vore isn't the only sexual fetish out there. There's fetishes for almost everything. 

Tiger has no particular attachment to the eating/swallowing aspects, and is more interested in the mechanics of a borg being used to transport things. The current implementation we have for that is the sprites you see there. This is subject to change. That's up to discussion on how they should look at the spriters we can get to do it.

However, it's clear that the current sprites and way it's done makes people uncomfortable and that's fair enough - it does have a very organic, voresque feel to that, and I'd like that aspect to be removed. If a sprite is possible that would avoid that appearance, such as by mounting it on the back and having it loaded in more, and having it appear more like a regular sleeper, then I think that'd be for the best. Renaming it to "mounted sleeper" or the like would be best too.

**Comment by taukausanake** [comment]
I'd say for the sprite to just not have the belly part show. Isn't the sprite big enough that it would logically fit a human-sized being inside it? Wouldn't it also make logical sense that the borg loaded the mob inside it by opening up like a mech/suit? Those are literally the first things I thought before I even tried opening the gifv image/videos and didn't have any problems other than how fluid and majestic the moving sprites are. I find it hard to believe we don't have anything that looks that good on here already

**Comment by uraniummeltdown** [comment]
You should separate the refactor from the dog stuff
These are overpowered compared to regular borgs, the med dog having a built-in sleeper takes away one of the unique Odysseus features. The huge sprite looks very stupid compared to everything else in-game, the vore shit is disgusting and perverse, they're just better borgs that are also animals. Do we seriously need more animals in this game? The joke where we port things from ERP servers has gotten stale

**Comment by Bram961** [comment]
The icons don't fit the style of the server. 
The organic names for different parts (belly, boop module, tongue) sound very cringy in the context of these being borgs.
The jaws are pretty much useless as the modules that have them also have a baton and a fireextinguisher which do more or less the same damage.
The whole eating things part of this, no.
The subsequent qdel of items and people is unbalanced.
And this all boiling down to a step in the wrong direction because it will mostlikely alienate a major part of our players while making the at times cringeworthy people who take their furry RP to far more cringeworthy.

In my opinion dog borgs could have been implemented if they were our code/icons instead of being a vore port that contains references to vore, doesn't fit the server and is just so conceptually wrong.

Big no from me 👎

**Comment by deep-fried-faceplant** [comment]
What is the purpose of this addition? What niche do these new cyborg modules fill that wasn't already filled? Is there a demand for what these cyborgs can do? Will these cyborgs promote mechanical gameplay or roleplay?

I have enough of an open mind to consider reworking and balancing these cyborg modules in order to work on Paradise, but it feels like this pull is motivated more by "rule of cool" rather than gameplay. Ignore the vore aspect for a minute, and consider what these cyborgs are. They're cool, they're futuristic cydogs that can do cool futuristic shit. But what does that really matter? We should port features with gameplay in mind, not how cool it would be to play as a cyber dog in space.

@tigercat2000 Please, ask yourself the aforementioned questions. You want to port this from virgo, I want to know how you think they'll fit in on Paradise, before we work on finishing them.

**Comment by karmapay2win** [comment]
Why not just add more regular borg sprites instead of piss trees?

**Comment by tigercat2000** [comment]
Considering the general response to this PR and the concept behind it, it was seen fit to close it, and it appears to be unfeasible. The borg module refactor included may be submitted as a separate pull request at a later time.

**Comment by Aurorablade** [comment]
No. This pr was very feasible and I am currently upset at some members of the community.

**Comment by optimumtact** [comment]
remember this lol

**Comment by Spacemanspark** [comment]
Who let the dogs out

**Comment by taukausanake** [comment]
I still like the idea of dog cyborgs that are slaved to a human and not the AI. Not so much the vore parts

**Comment by Spacemanspark** [comment]
We have pAIs

**Pull request closed without merging**
