### PR TITLE
Title2 Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates Title2

Stumbled upon a really really nice remix of the Robocop GG title theme (did you know that SS13's iconic title theme is from this game?) that fit in very very well with the existing SS13 music's general vibe and theme (especially Title3).

I contacted LMan (Markus Klein), one of the original remixers, for permission to use this, and he was more than happy to oblige.

In any event, give it a listen: http://www.remix64.com/track/andy-gilmour-lman/robocop-title/

All credit goes to Andy Gilmour & LMan (Markus Klein).

Some small alterations were made:

- Volume normalized to be very very close to the same as our current Title2
- Song duration cut in half with a fade-out added towards the end
 - Makes the song the same duration and cut off at the same point as our current Title2, not to mention keeps the size down.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I don't like this as a replacement for title2. 
As a new thing? Sure, it's a nice remix, I like the sound of it.
But replacing title2 entirely, I don't like.

**Comment by Fox-McCloud** [comment]
It's literally the same, exact, song, only not in a midi played format.

We can't have both.

**Comment by tigercat2000** [comment]
Why the fuck not? One is a very different sounding track, even if they are 'the same song'.

**Comment by Fox-McCloud** [comment]
Because there's no sense in having redundant music. It serves no purpose other than to waste space.

**Comment by tigercat2000** [comment]
Adding a new track that's definately different than another, regardless of them having the same origin point, is not wasting space.

**Comment by Fox-McCloud** [comment]
Yes, it is; it's why we don't have 5 variations of puking, or slipping, or "X" action--it's a waste of space to have duplicates when they're the same, effective, thing (even if they sound different from each other).

**Comment by tigercat2000** [comment]
But two different remixes of the same track are not the `same effective thing`.
Whatever, if you insist on this, I'll leave it for other's opinions, I've already given mine.

**Comment by Spacemanspark** [comment]
...Why not have both?
We have multiple versions of "Put a bangin' donk on it." at the end of the round.
If we can have both, :+1:

**Comment by HereticChurch** [comment]
I really like the sound of the mix, and I'm glad you've shared it, but personally I prefer the version we have. :-1: from me.  This is a nice track though.

**Pull request closed without merging**
