### PR TITLE
Nerfs Buckshot

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/tgstation/pull/23088

Yeah, buckshot is insanely strong, no matter how you slice it; the fact that it's a two-shot kill at point blank is a bit much, not to mention the argument made in the PR above.

:cl: Fox McCloud
tweak: Buckshot now does a max of 70 damage, down from 90
/:cl:

### CODE REVIEW

**Comment by Anasari** [comment]
Makes it a "can't miss with this" weapon instead of always the superior choice to slug. I support this.

**Comment by Fox-McCloud** [comment]
Admittedly, it's still going to be numero uno at point blank range, but I think that's ok--that's the trade off; it's better at close range, but terrible at long range...problem is, it's awfully damn good at long range right now, too.

**Comment by scrubmcnoob** [comment]
yee haw

**Comment by DesolateG** [comment]
Ever shot 000 buckshot?

**Comment by Ssirius** [comment]
We needed this for a long time.

💯x 👍

**Comment by shazbot194** [comment]
I know this is outside the scope of this PR, but why do we just have generic (00) buckshot and not also add more specialized shells like bird shot, flechette, and 000 buckshot? I can think of at least a couple scenarios where having a lot of smaller shot would be helpful, a handful of less powerful but more accurate and slightly armor piecing mini-darts, or a couple big shot would be more useful. A prime example for all three being Nuke Ops.

**Comment by Aracino** [comment]
Because shotguns already have asloafs of ammo types compared to any other.
They have so many types of ammo that its not needed to add more to make it even more viable than it is.

**Comment by taukausanake** [comment]
We should get more ammo types for other guns then. That could be fun

**Pull request merged**
