### PR TITLE
Map fix PR 2: Electric Boogaloo

### LINKED ISSUE #6285: Undeconstructible bar stool
There's a bar stool in the maint old bar backroom of main station that cannot be deconstructed with a wrench or otherwise.

There's actually several of such stools that can't be deconstructed throughout the station, while others can be.

### LINKED ISSUE #7476: Oldbar maint airlock and security pod airlock
The security pod airlock has the exact same tags as the old bar maint airlock a few tiles right of it, this makes the two controllers fight each other and sometimes leads to one of the two airlocks becoming non functional.

### LINKED ISSUE #7852: Unconnected Scrubber, Central Primary Hallway
**Problem Description**:
The scrubber in Central Primary Hallway is connected to a broken section of pipe that doesn't connect to the waste loop.

**What did you expect to happen**: 
The pipes should be properly layed down so the scrubber is connected.

**What happened instead**:
They aren't.

**Why is this bad/What are the consequences:**
Mostly because the hallways are already relatively low on scrubbers, so having one of the most central locations unable to filter any gases can be troublesome.

**Steps to reproduce the problem**:
Just walk up to the Central Primary Hallway Air Scrubber #1 and follow the pipe. It is unconnected 3 tiles up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I got a capture if that helps, with the relevant piping.
pipes1
pipes2

### PR DESCRIPTION
**Pull request by Citinited**
Because map conflicts are reaaaaaaally awkward to fix unless they're in a small PR, or something. (See #7735) I should have really done it this way initially, as multiple smaller PRs instead of one large one.

Fixes #6285 - Fixed that one indestructible bar stool in the old bar (which for some reason was mapped as the weapon version of the stool);
Fixes #7476 - Security and bar maintenance airlocks are now decoupled;
Fixes #7852 - Added piping so that one scrubber works again.

I changed / fixed the following map issues:

- Rearranged the camera and light fixture in the prisoner transfer centre so that they're wall-mounted, not attached to the blast doors / grilles. Before: http://i.imgur.com/ugP98MA.png. After: http://i.imgur.com/FFt80uo.png;
- The air vent at the fore of AI satellite now starts turned on;
- Engineering equipment now only has one air vent, not three (including one with no pipe leading to it);
- Added a missing bit of plating underneath the engineering shuttle's window.
- Fixed the scrubber in central primary hallway.

:cl:
fix: You can now deconstruct the indestructible stool in the old bar's back room.
fix: Security and bar maintenance airlocks are now decoupled.
tweak: The air vent at the fore of AI satellite now starts turned on.
tweak: Engineering equipment now only has one air vent, not three.
fix: Added a missing bit of plating underneath the engineering shuttle's window.
fix: Added a missing scrubbers pipe in Central Primary.
tweak: The camera and light fixture in the prisoner transfer centre are now wall-mounted instead of being attached to the blast doors.
/:cl:

### CODE REVIEW

**Comment by FalseIncarnate** [comment]
Since you are fixing some things anyways, please check that the public showers (just south of the boxing ring) are actually stuck to the walls. I noticed in my plumbing PR that they seemed to be incorrectly offset, so they kinda just float behind the curtains. Removing their pixel_x offset should fix it.

**Comment by Citinited** [comment]
They're not stuck to the walls, but setting `pixel_x = 0` moves them behind the curtains, thus hiding them from view. I think aesthetically they look better with the offset when there are curtains

**Comment by FalseIncarnate** [comment]
Or change them to be the south state rather than east/west. The fact that they are just floating mid-tile looks bad.

**Comment by Citinited** [comment]
@FalseIncarnate I'll play around with it; given I need to fix those merge conflicts anyway

**Comment by Citinited** [comment]
Oops, I accidentally this branch...

**Comment by Citinited** [comment]
Seems that this had some weirdness - oops. I'll make a new PR to fix this stuff that isn't broken...

**Pull request merged**
