### PR TITLE
Adds the ability to attach a remote signaler to a telesci computer

### PR DESCRIPTION
**Pull request by monster860**
I looked at the original PR, #3847, and apparently the reason fox closed it was due to a lack of response, and not because of a "This is too op!" opinion. Luckily, I don't delete my branches, so I'm reopening this.

:cl: monster860
rscadd: A telesci console can have an assembly attached to it, like a remote signaling device.
/:cl:

### CODE REVIEW

**Comment by QQCucumber** [comment]
JESUS CHRIST NO

**Comment by fludd12** [comment]
I'd love it. We need everything to be signaller-compatible.

**Comment by theColdflame** [comment]
telesci doesn't need a buff

**Comment by pipextiny1** [comment]
Unironically buffing science.

**Comment by monster860** [comment]
What many people fail to realize is that science will literally give you anything if you ask for it.

Once, as a civvie, I asked Science for all the parts to build a telescience lab. The RD happily printed off the parts and gave them to me.

Features that you'd think are limited to Science are actually usable by anyone, because Science is pretty lax about what they give out.

**Comment by Spacemanspark** [comment]
My personal opinion is that we need to strip Telescience from the code completely.
:-1:

**Comment by AceMcLazer** [comment]
You' can't generalize like that. honestly

**Comment by Fox-McCloud** [comment]
This wasn't just closed because of that, it's because telesci is already horrendously overpowered, and this pretty much means you can one-man telesci even the most dangerous of locations, by yourself.

**Comment by billbillson** [comment]
i personally think that tele science is way too complicated for a ingame mechanic and requires way too much math in a game. If anything a buff is needed after how nerfed telesci has been, look at how crazy it is to understand even if you are semi decent at math. The wiki passed right over my head  and right now it required a spreadsheet and or calculators to even begin to set it up .Not to mention it needs bluespace crystals which mining needs to find .#4641 is a idea which can be refined and used to help keep science from being a lair of lurking memelords in my opinion.

**Comment by TheDZD** [comment]
> Unironically buffing science.

Basically this. Scientists don't need to be able to teleport themselves in and out of anywhere at will, telescience is more than powerful enough as-is.

**Comment by Davdichan** [comment]
1 man telescience is not something we need. It's bad enough you can pop shit out almost at will. Now you have a sec terminal and see the cap is in his office minding his own business? Port in, stunprod/stab the shit out of him and strip all his shit, tp back out in under 2 minutes. FOR THE LOVE OF GOD NO.

**Comment by monster860** [comment]
Orrrrr you can type in the coordinates of the captain and teleport him in, and then stunprod him and strip all his shit.

**Comment by Davdichan** [comment]
@monster860 Nuke disk prevents teleports.

**Comment by Spacemanspark** [comment]
Either way that's still pretty much an "I win" button.

**Comment by monster860** [comment]
Fair point, I guess I'll flush myself down the disposals conveniently located in the captain's office

**Comment by Spacemanspark** [comment]
At least security has a clear idea of where you'll end up.

**Comment by Fox-McCloud** [comment]
Yeah, closing this. This wasn't *just* closed because of lack of response, it was opposition to the feature itself as a balance mechanic. @TheDZD and myself's position on this is unchanged, and...well, not surprisingly, not many individuals support this either because telesci is already ridiculously OP.

**Pull request closed without merging**
