### PR TITLE
Adds a cooldown progress bar to Cryocells

### PR DESCRIPTION
**Pull request by CinnamonSnowball**
## What Does This PR Do
Adds a simple progress bar to indicate the cooldown period of Cryocells.
Additionally makes a minor UI shift (putting the beaker label and volume on the same line) to compensate for the extra space used.

## Why It's Good For The Game
Having decent feedback is good - previously there was no indication for why a cryocell might not work, leaving you to guess it was used recently and is on cooldown.

## Images of changes
[2023-02-02 02_31_57.webm](https://user-images.githubusercontent.com/100448493/216209195-e0adf9a7-5b51-4c79-9fae-018efa119c14.webm)

## Testing
See: video above

## Changelog
:cl:
add: Cryocell UI now has a progress bar to indicate the injection cooldown
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
I really like the idea of labelling the cooldown -- I didn't even know it was a thing.

One thing I'd like to note is that it's not really clear what the cooldown is referring to at a glance, at least from the screenshots. I think it needs a label, and could maybe use some spacing from the elements above it, since it somewhat looks like it's related to the beaker.

**Comment by CinnamonSnowball** [comment]
Well, it kinda _is_ - the cooldown is specifically for the beaker injections, so I figured putting it right up close with the other beaker info would be self-explanatory enough

**Comment by Miraviel** [comment]
At a glance it looks like the beaker is 100% full or 24% full based on the bar's positioning

But it is a very good idea. Maybe add a `content` var with "Cooldown"? Or similar to that, afaik `content` writes inside the bar. Or add a label below "Beaker" saying "Cooldown".

**Comment by CinnamonSnowball** [comment]
If you mean binding the progress bar to a separate UI block with its own label (like `Power`, `Temperature`, and `Beaker` do), yeah, that could be done - the only question is what should the label be. Personally I'm not super fond of "`Cooldown`" as it feels a bit OOC, but it'd work I suppose

**Comment by CinnamonSnowball** [comment]
Moved the bar to a proper separate subsection labelled `Dosage interval`, expanded the whole window a tiny bit vertically to avoid weird scrollbars, upgraded the two screencaps into a breathtaking live-action video

**Review by S34NW — APPROVED** [review]
Fix TGUI conflicts and this can go :)

**Pull request merged**
