### PR TITLE
Fixes autopsy reports description

### PR DESCRIPTION
**Pull request by Citinited**
How is it filled when there's nothing in it?!

:cl:
fix: The autopsy drawer's description makes more sense.
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
Can you please just rename the drawer the Schrodinger's Drawer?

**Comment by Citinited** [comment]
🤔

**Comment by Fox-McCloud** [comment]
Make this an instance of an item, instead of it being map var-edited.

**Comment by deep-fried-faceplant** [comment]
"A large drawer, possibly filled with autopsy reports."
Why not:
"A large drawer for holding autopsy reports."
Tighter description, as it tells you what the drawer is for, rather than implying "Oh well there might be reports in that drawer".

**Comment by Citinited** [comment]
@deep-fried-faceplant Makes sense, will change

@Fox-McCloud Ehh, sure why not.

**Pull request merged**
