### PR TITLE
Metastation Adds Hallway

### LINKED ISSUE #22636: Metastation Bridge Hallway controls SPACE
**Issue Description**:
Metastation's bridge hallway is missing an area
j1t8QC7JVI

**What did you expect to happen**: 
For it to have an area

**What happened instead**:
OBeUkGyH28
LSlQks4sVB

**Why is this bad/What are the consequences**:
Areas should have Areas

**Steps to reproduce the problem**:
1. Log on Metastation

**When did the problem start happening**:
No clue

### PR DESCRIPTION
**Pull request by Oyu07**
## What Does This PR Do
Fixes #22636 

## Why It's Good For The Game
every place needs an area/name

## Images of changes
**OLD**
image
**NEW**
image

## Changelog
:cl:
fix: Metastation: Hallway sandwiched between bridge now has an area
/:cl:

### CODE REVIEW

**Review by Contrabang — CHANGES_REQUESTED** [review]
Personally, I would not consider this a primary hallway. Also, this did use to have an area, you just replaced it, not added one where there wasn't one.

The problem here is that the area `/area/station/hallway/secondary/bridge` is called "space" because it has no name overridden. Personally, I recommend you make no mapping changes and just the name of the area.

Or you can keep the changes as they are, and delete `/area/station/hallway/secondary/bridge` from the codebase because it is used nowhere else. Although this means that the theres a central part of the central hallways, which makes less sense to me.

**Comment by Oyu-De** [comment]
> Personally, I would not consider this a primary hallway. Also, this did use to have an area, you just replaced it, not added one where there wasn't one.
> 
> The problem here is that the area `/area/station/hallway/secondary/bridge` is called "space" because it has no name overridden. Personally, I recommend you make no mapping changes and just the name of the area.
> 
> Or you can keep the changes as they are, and delete `/area/station/hallway/secondary/bridge` from the codebase because it is used nowhere else. Although this means that the theres a central part of the central hallways, which makes less sense to me.

So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.

The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.

I will check on the `secondary/bridge`

**Comment by Contrabang** [comment]
> So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.

There is an area there, its just using the default icon. If there was no area there, it would be completely transparent
image

> The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.

The central hallways are not currently differeniated by name, hence why I am hesitant on adding more, we do not need more areas on station under the central hallway name IMO

**Comment by Oyu-De** [comment]
> > So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.
> 
> There is an area there, its just using the default icon. If there was no area there, it would be completely transparent image
> 
> > The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.
> 
> The central hallways are not currently differeniated by name, hence why I am hesitant on adding more, we do not need more areas on station under the central hallway name IMO

ok I need to check the secondary/bridge more carefully, new to mapping etc.

and as for adding a new area, I get the reluctance, so
1. secondary/bridge is only used for metastation, so that is gone with this
2. the central hallway should be broken up imo because it is a massive area where in which a single air alarm controlls for example
3. if in the future meta/delta have their sections divided, this would allow it to have all sections as a subtype rather than having to use the big /central/hallway/ to be used. although I assume it can be used as the center part like how cerestation does it, in this instance because the entire hallway is central, I personally thought that it should be a seperate section.

**Comment by Contrabang** [comment]
> > > So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.
> > 
> > 
> > There is an area there, its just using the default icon. If there was no area there, it would be completely transparent image
> > > The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.
> > 
> > 
> > The central hallways are not currently differeniated by name, hence why I am hesitant on adding more, we do not need more areas on station under the central hallway name IMO
> 
> ok I need to check the secondary/bridge more carefully, new to mapping etc.
> 
> and as for adding a new area, I get the reluctance, so
> 
> 1. secondary/bridge is only used for metastation, so that is gone with this
> 2. the central hallway should be broken up imo because it is a massive area where in which a single air alarm controlls for example
> 3. if in the future meta/delta have their sections divided, this would allow it to have all sections as a subtype rather than having to use the big /central/hallway/ to be used. although I assume it can be used as the center part like how cerestation does it, in this instance because the entire hallway is central, I personally thought that it should be a seperate section.

Yes, I agree with that, and thats why it should be renamed to "Bridge Hallway" instead of adding more central-hallway space

**Comment by Oyu-De** [comment]
> > > > So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.
> > > 
> > > 
> > > There is an area there, its just using the default icon. If there was no area there, it would be completely transparent image
> > > > The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.
> > > 
> > > 
> > > The central hallways are not currently differeniated by name, hence why I am hesitant on adding more, we do not need more areas on station under the central hallway name IMO
> > 
> > 
> > ok I need to check the secondary/bridge more carefully, new to mapping etc.
> > and as for adding a new area, I get the reluctance, so
> > 
> > 1. secondary/bridge is only used for metastation, so that is gone with this
> > 2. the central hallway should be broken up imo because it is a massive area where in which a single air alarm controlls for example
> > 3. if in the future meta/delta have their sections divided, this would allow it to have all sections as a subtype rather than having to use the big /central/hallway/ to be used. although I assume it can be used as the center part like how cerestation does it, in this instance because the entire hallway is central, I personally thought that it should be a seperate section.
> 
> Yes, I agree with that, and thats why it should be renamed to "Bridge Hallway" instead of adding more central-hallway space

So, from `/hallway/primary/central/center` to `/hallway/primary/central/Bridge Hallway`?

**Comment by Contrabang** [comment]
> > > > > So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.
> > > > 
> > > > 
> > > > There is an area there, its just using the default icon. If there was no area there, it would be completely transparent image
> > > > > The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.
> > > > 
> > > > 
> > > > The central hallways are not currently differeniated by name, hence why I am hesitant on adding more, we do not need more areas on station under the central hallway name IMO
> > > 
> > > 
> > > ok I need to check the secondary/bridge more carefully, new to mapping etc.
> > > and as for adding a new area, I get the reluctance, so
> > > 
> > > 1. secondary/bridge is only used for metastation, so that is gone with this
> > > 2. the central hallway should be broken up imo because it is a massive area where in which a single air alarm controlls for example
> > > 3. if in the future meta/delta have their sections divided, this would allow it to have all sections as a subtype rather than having to use the big /central/hallway/ to be used. although I assume it can be used as the center part like how cerestation does it, in this instance because the entire hallway is central, I personally thought that it should be a seperate section.
> > 
> > 
> > Yes, I agree with that, and thats why it should be renamed to "Bridge Hallway" instead of adding more central-hallway space
> 
> So, from `/hallway/primary/central/center` to `/hallway/primary/central/Bridge Hallway`?

No, you have to define the name under the typepath definition where the path is defined, in this case public_areas.dm

**Comment by Oyu-De** [comment]
> > > > > > So, on SDMM, it shows absolutely nothing, no area for there, we saw that it changes the `secondary/bridge` but absolutely no idea about that or why that area was referred as that.
> > > > > 
> > > > > 
> > > > > There is an area there, its just using the default icon. If there was no area there, it would be completely transparent image
> > > > > > The central hallway - center, I thought that as it may have its 4 cardinal directions on the exterior, but this goes through it, so naming it "center" sounded just to me, ALSO it could be used on delta because currently "south" refers to the middle section instead of the actual south, but again it has the entire hallway as a single piece unlike cyberiad.
> > > > > 
> > > > > 
> > > > > The central hallways are not currently differeniated by name, hence why I am hesitant on adding more, we do not need more areas on station under the central hallway name IMO
> > > > 
> > > > 
> > > > ok I need to check the secondary/bridge more carefully, new to mapping etc.
> > > > and as for adding a new area, I get the reluctance, so
> > > > 
> > > > 1. secondary/bridge is only used for metastation, so that is gone with this
> > > > 2. the central hallway should be broken up imo because it is a massive area where in which a single air alarm controlls for example
> > > > 3. if in the future meta/delta have their sections divided, this would allow it to have all sections as a subtype rather than having to use the big /central/hallway/ to be used. although I assume it can be used as the center part like how cerestation does it, in this instance because the entire hallway is central, I personally thought that it should be a seperate section.
> > > 
> > > 
> > > Yes, I agree with that, and thats why it should be renamed to "Bridge Hallway" instead of adding more central-hallway space
> > 
> > 
> > So, from `/hallway/primary/central/center` to `/hallway/primary/central/Bridge Hallway`?
> 
> No, you have to define the name under the typepath definition where the path is defined, in this case public_areas.dm

I have named the area "command hallway", inherited from the existing

**Review by Contrabang — CHANGES_REQUESTED** [review]
still need to delete the old area, otherwise looks pretty good. Some weird map key shifting it looks like though

**Comment by Contrabang** [comment]
> > still need to delete the old area, otherwise looks pretty good. Some weird map key shifting it looks like though
> 
> Gonna delete the old area from the code, but a question before `/area/bridge/hall : /area/station/hallway/secondary/bridge{@OLD}` what is this? out of curiosity

That looks to be from an update paths file. You can just ignore those. It replaces old paths with new paths when run across all maps.

**Comment by Oyu-De** [comment]
> > > still need to delete the old area, otherwise looks pretty good. Some weird map key shifting it looks like though
> > 
> > 
> > Gonna delete the old area from the code, but a question before `/area/bridge/hall : /area/station/hallway/secondary/bridge{@OLD}` what is this? out of curiosity
> 
> That looks to be from an update paths file. You can just ignore those. It replaces old paths with new paths when run across all maps.

thx
So, it should be good right now. 
1. Given area
2. Given name
3. Deleted the no longer used area from the dm

**Review by Contrabang — CHANGES_REQUESTED** [review]
I'm gonna be honest, because it would be a massive pain to look through the giant map diff outside of github (which has a 10k line diff limit). I think you should revert the mapping changes, and just move `name = "Command Hallway"` to be the name of the `/area/station/hallway/secondary/bridge` area. It would be functionally the same fix without needing to make a 13k line map change.

If you want to, you can also change the icon_state of the area to be corresponding to other hallways so it looks good in the editor

**Review by S34NW — CHANGES_REQUESTED** [review]
I agree with contrabang, please implement his suggested changes by simply adding a proper name and icon to the existing area.

**Comment by Oyu07** [comment]
> I'm gonna be honest, because it would be a massive pain to look through the giant map diff outside of github (which has a 10k line diff limit). I think you should revert the mapping changes, and just move `name = "Command Hallway"` to be the name of the `/area/station/hallway/secondary/bridge` area. It would be functionally the same fix without needing to make a 13k line map change.
> 
> If you want to, you can also change the icon_state of the area to be corresponding to other hallways so it looks good in the editor

image
image
used the hullC icon state

**Comment by Oyu07** [comment]
I have no idea why it got closed
reopened

**Review by Contrabang — APPROVED** [review]
LGTM

**Pull request merged**
