### PR TITLE
Remaps Perma

### PR DESCRIPTION
**Pull request by Kyep**
Goals:
- Make perma more interesting. IE: not just a good excuse to suicide or ghost.
- Add useful things perma prisoners can do. IE: botany, reading books.

Additions:
- Botany area: 6 plots, plant analyser, mini hoe, biogenerator, 3 bottles EZ nutrient, 3 bottles pest spray, 2 buckets, seed extractor, seeds (3x apple, corn, rice, orange)
- Basketball court: 1 basketball
- Toilet/shower area: 1 rubber ducky
- Reading area: 1 safe library computer, 1 book of space law
- Eating area: 1 microwave, 1 box of donk pockets
- Cells: 3 individual cells, individually separatable from main perma, with their own beds/lights/flashers.
- Misc: 1 space cleaner in the atmos control room

History: 
- Based on perma remap portion of https://github.com/ParadiseSS13/Paradise/pull/4403
- Remade from scratch, with some further improvements based on metastation

Screenshot:

:cl: Kyep
tweak: adds botany, basketball court, individual cells, library computer and more to perma. Makes it far less boring.
/:cl:

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
Everything looks good to me, except that gameboard and the two stools around it, they look horribly separated from the other stuff. Other than that, :+1:

**Comment by Davdichan** [comment]
I would keep laundry personally. Its been ages since I've done it and I don't know if our code bases supports it, but you used to be able to shove people in the machine and turn it on to kill them.

A wonderful hazing exercise for new blood or clever way to dispose of a sec guard or warden whose harassing them.

**Comment by Fox-McCloud** [comment]
Still has the same problem your previous remap did; it's overly huge and sprawling, feels like it's tacked on, and still has those windows.

**Comment by Ar3nn** [comment]
I don't see a problem with the windows. If anyone gets into perma with tools to disassemble them, sec's being lazy as fuck and deserves the escape attempt

I do agree that its pretty large, though. Remove the potted plants, the space law book (nice fluff, but nobody's going to read it in prison) and shrink the bedrooms up one tile and move the whole room up one tile so the corridor isn't so huge in the middle. I also don't know what those machines are, the white ones with the tubing? Thus I feel them unnecessary, so remove those, too. Just some ideas, not saying you have to implement all or any of these suggestions.

**Comment by Kyep** [comment]
@Davdichan You'd have to stun/etc them first, surely? I've never actually seen someone kill using a washing machine.

@Fox-McCloud To me, it looks closer to cramped than huge and sprawling. Re: windows, are you talking about the windows by the sustenance vendor? Would you prefer them swapped for maint like in the old version: http://i.imgur.com/HvAVS8O.png ?

**Comment by TullyBurnalot** [comment]
I like this concept, actually. A few things to take into consideration:

1) Yes, please keep laundry. It's prison, someone is bound to get dirt/blood on their clothes eventually. Nothing is worse than having blood smeared all over you and being unable to clean it.

2) Yeah, just... remove the Space Law book and potted plants. Nice fluff, no function. Realistically, no one is going to read Space Law in the Permabrig.

3) @Fox-McCloud If the windows are a problem, then I wonder why they were never removed in literally years. If Security lets people into Perma with tools, that's their fault. If they leave someone who's spaceproof, also their fault. If they get someone to come break them out of jail, then hey, more fun for the whole party. Also Security's fault, I mean, Perma has cameras, c'mon.

4) Maybe add DnD figurines?

**Comment by Aurorablade** [comment]
KEEP TREADMILLS 2016

**Comment by Da-Dman234** [comment]
I'm still against having the laundry machine, since in my eyes it just takes up space. I've quite literally never seen anyone use it even once, and if you want to clean yourself there's now a shower. Speaking of which, I think it'd be nice to add a mirror to the bathroom. It'd give prisoners a nice tiny little buff of being able to change their haircut in the off chance they get a chance to attempt to escape.

Also, not sure how I feel about those Donk pockets. I guess I'm not personally against it, but with them any ol greytide mcshitter can break out of perma without any tools. Granted, they'll probably end up addicted to Omnizine, which seems fairly balanced to me, I guess?

**Comment by TullyBurnalot** [comment]
As an addendum to my previous commentary, I would say to KEEP the potted plant. After all, that at least gives prisoners some way to Solid Snake the hell out of Perma. Which would be hilarious.

Also what @Da-Dman234 said in their first paragraph. Prison makeovers!

**Comment by IcyV** [comment]
Perma is rather boring most of the time really no matter what you add to it. The majority of the time a single person will be locked in there and probably won't really be super interested in most things available. I'd personally prefer to see something along the lines of http://puu.sh/oLs9t/773e30879c.png

Minor additions for helping someone pass the time and mess around with some things rather than a full rework that extends out way more than it needs to.

I'd rather see Perma smaller and not used as much in favor of more interesting things happening to a player.

**Comment by Kyep** [comment]
@TullyBurnalot @DaDman234 @Aurorablade 
Decisions:
- Laundry: 2/4 commenters favor keeping it. If it gets heavy support I'll map it back in. Right now, though, I am trying to save space. The shower handles all hygiene needs in a fraction of the space, so the laundry room is unnecessary. Unlike laundry machines, showers get used.
- D&D figurines: I looked in the code, but did not find them, and adding them just for this is out of scope for this PR.
- Treadmills: not re-adding, as they’re ugly, tedious and useless.
- Bathroom mirror: added.
- Potted plants: currently 1/1 on support for these, leaving them in for the moment.
- Chess table: moved it down a square.
- Space law book: deleted.
- Donk pockets: these are intended to help prisoners self-treat a little in the event of prison fights, and thus reduce the amount of time sec needs to spend managing them. They’re not intended to facilitate escapes.
- Cardboard boxes: I have debated adding a cardboard box for prisoners to hide in, but given how strong cardboard boxes have been I am reluctant to do it as it might change the balance of perma significantly. I think the potted plants will already add some hilarity without this.

Image in first post updated accordingly.

@IcyV: That map has many issues:
1) Big white air scrubbers are tucked away in a corner, limiting their effectiveness.
2) Normal scrubbers are placed together in a group.
3) Botany/toilets have no scrubbers/vents.
4) No separate cells, no way to isolate prisoners, hard to handle multiple prisoners at once.
5) Multiple windows afford views of walls.
6) No books, basketball court, limited arcades, etc.
7) Botany area lacks seed extractor, biogenerator, etc.
8) Anyone entering botany area may trigger armory motion sensor alarm. Also in botany there are two cameras only a few spaces from each other.
9) Shower is fully visible to the rest of perma.
10) Holopad coverage is dubious.
Those are just the first 10 issues that come to mind. I am sure I’d find more if I tested it in-game. Point is: I’m not comfortable using as a template any map/image that has so many obvious issues.

**Comment by Da-Dman234** [comment]
It's well and good that they're not meant to facilitate escapes, yet they will. If you reaaally wanna help with prison fights (Which I imagine most people won't walk out of alive) then just toss a brute/burn pack in there.

That being said though I actually kind of like the donk pockets placed there. If you load up on them and bust a window, I'd say you're probably sitting very near 100% chance of making it to arrivals alive, but addicted to Omnizine. With the new addiction system you'll be pretty sketchy for what I wanna say is around 8 minutes, giving the AI plenty of time to notice the breach and sec to press what is a massive advantage on you.

If you're against perma being so easy to break out of though... well, those people are gonna have to problems with this.

**Comment by Kyep** [comment]
@Da-Dman234 I just loaded up the map and tried it. I died. Not even halfway to arrivals. Apparently you can't consume all the donk pockets at once like that.

**Comment by IcyV** [comment]
@Kyep It's not meant to be a perfect example of what I'd want to see, just the rough idea. Something smaller and compact that offers prisoners more instead of a larger Perma that encourages more people being shoved in.

**Comment by Kyep** [comment]
@IcyV Ignoring the basketball court, they're roughly comparable in size, but this version has a lot more prisoners can do (library, better botany, another arcade, etc). The basketball court is the biggest single piece, and it was added in direct response to lots of requests on the previous PR / the forums. Also, when trying to make a prison space fun for the prisoners, "make it smaller" doesn't seem like the right direction to go in.

**Comment by IcyV** [comment]
@Kyep Which is where I still hesitate on Perma needing any changes at all. People being done with the round once they're in perma is due to the, essentially, full cut-off from the rest of the round. Save for a major accident or someone breaking them out, it's likely they're going to be alone with nobody to talk to for any potential amount of time. I'd argue that most people don't find the individual little games and such entertaining for more than a few minutes at most. A proper way would be to somehow integrate more player-interaction instead of relying on more space and more games.

**Comment by johannhawk** [comment]
I used to use the washing machines in perma to recolor my prison jumpsuits and bedsheets, but the arcade machines only spew tickets now, then again, i could ask a officer to bring me some crayons.

**Comment by Kyep** [comment]
@IcyV Check out: https://github.com/ParadiseSS13/Paradise/pull/4766 We can do both.

@johannhawk There was a discussion in the past about making them give items, or including a prize machine, but there was some concern about prisoners having some of the prizes.

**Comment by Dumbdumn5** [comment]
I'd actually love to see this thing in action, looks more fun than just sitting on your ass or playing the same card or arcade game with yourself and the ghosts who decide to mess with you in your cell.

**Comment by TheDZD** [comment]
Oh god mapping merge conflicts.

**Comment by Kyep** [comment]
@TheDZD Map merge conflict fixed.

**Comment by Kyep** [comment]
@TheDZD Map merge conflict resolved.

**Comment by tigercat2000** [comment]
I think this looks aesthetically awful.
 - It's very boxy and feels tacked onto the side of security, not part of it at all.
  - The sharp edge on the left is a big part of this.
 - The basketball floor design is just what???
 - There are multiple areas that N2O won't go if released.
 - Two rows of dirt means you have to stomp on the plants to harvest anything, and looks repetitive.
 - Toilet isn't sectioned off from the rest of the bathroom.
 - The game board is just randomly hanging around in the center of the room, it looks completely out of place.
  - Same with the table below the only window.
 - Not enough windows for such a large room.
 - The independent cells releasing into the bigger area are pointless. They have no timer attached to them, making them non-functional as regular cells. Bay/Polaris have the entire brig being communal, not just permabrig, which makes way more sense to have actual independent cells.
 - No seperate bedding area. Permabrig shouldn't be limited to just three people, and you can't turn off the lights in each cell.
 - For that matter, there's no lightswitch anywhere in the room.
 - There's no APC either. I'm assuming you just extend the perma hallway all the way through the permabrig, that's pretty awful.
 - Multiple box-areas are only 2 wide. 2 wide areas feel cramped because you can never be centralized in them.

**Comment by SpaceTimeNow** [comment]
I believe this PR misses its mark. Perma Brig in itself is a very weird concept in a video game, you will never be able to make it "fun". It only serves one real purpose, giving the option of rescue and let's be honest, that is exactly the reason why it's not used. 

What we need is this improved "perma birg" replacing the standard 3x3 cells, with the option to escalate a prisoner temporary to a solitary confinment. Of course it needs to be a little bigger, but with perma out of the way we have a lot of space in security to built a propper prison.

The only replacement i can see for perma to be accepted is a exile to another self contained z-level. A fucked up rock with an old science station with just enough equipment on it to get stuff going. Here you can allow the prisoners to mine, built stuff, be creative and start their "second life". And you don't have to dance around giving them something that could be used as a weapon. The only teleporter control to get there is in security, so rescue is technically possible but much less likely. Perma prisoners are just teleported down there and left to their own.

**Comment by Da-Dman234** [comment]
@Kyep 
I actually just tried it, you were right. The damage from space rapidly outpaces the damage healed, I don't really know why I thought it'd work. My usual method is broken lightbulb to glass shard to metal rod, and I'm usually able to escape perma if I set a falsewall "airlock" up for myself prior to getting caught.

@tigercat2000 

- I'd just like to point out our current perma is quite literally a box as well, albeit a quite smaller one.

- I was the one who suggest the game board be moved, and that's only cause I don't like everything hanging on the sides of the walls, as it's not like you're going to see a lot of foot traffic in perma. In the end this is probably more a preference that varies from person to person.

- I've never seen more than 3 prisoners in perma at once, but you've been around a lot longer than maybe so maybe you've seen it happen. Still, I think that's a bit of a needless concern.

- It's pretty hard to see in dreammaker, but as far as I see there's no lightswitch in our current perma, and there most certainly isn't an APC. Not saying that that shouldn't change (As the zoning on our current perma is god awful and I could honestly care less if they were in or out), but I assume that's why Kyep chose to leave them out so far.

All the other complaints are totally valid though, except maybe the 2x2 walkway thing, but I think that again probably comes down to preference.

**Comment by GelatinousGlob** [comment]
It needs a local PA system to call prisoners to the cells to speak.

**Comment by Kyep** [comment]
@tigercat2000
- Re: boxy, I think it looks fine. In a game where everything is made up of square tiles, "boxiness" is a matter of perception. Also, we are talking about a prison.
- Re: basketball, its almost identical to the holodeck basketball court, which has never been a problem. If this design for a basketball court is really so bad, why have we never changed the holodeck one? 
- Re: N2O, the N2O is not intended to cover the whole area automatically. It is just intended to stop riots in the shared space. Big difference. I could make it cover the whole area, but it would complicate an already significant remap, by requiring me to add significantly more atmos-related systems. I'm trying to keep complexity to a minimum. Also, the AI can simply open doors and let the N2O into any area it doesn't reach naturally, making this a non-issue anyway.
- Re: Dirt, the alternative is to spread it out, and I'm not sure people would go for that. Nobody else seems to have mentioned the trampling. If other people think this is a legitimate issue though, I will change it.
- Re: Toilet, look at any bathroom in RL. They generally don't have a separate mini-room for the toilet.
- Re: Game board, people asked for it to be moved there. Not just Da-Dman, either. Other people wanted the middle space broken up as well. 
- Re: Windows, there are issues with adding windows. Makes perma easier to break (render unusable), easier to break out of, harder to repair, etc. Also, its a prison. Its meant to be heavy on the metal with small windows. Adding lots of windows (ie: glass walls) to an area meant to contain dangerous people does not make a lot of sense to me, especially given prior comments in previous PR that people did not like the use of windows/walls. There's nothing to see out of any windows either, except the armory to the south, and creating an easier path between perma and the armory seems like a very bad idea. I don't mind adding extra windows if the consensus goes that way, but right now I do not see any reason to add windows.
- Re: Individual cells, their purpose is so you can put prisoners into perma, and take them out, without risking being mobbed by everyone in perma grouping up. You get a single prisoner into a cell, use the button to shut the north entry to that cell, then take them out via the south entry. It reduces the chances of sec getting mobbed by perma prisoners. It gives each prisoner their own little space, and is safer for sec.
- Re: Separate bedding area: the old bedding area was terrible, individual cells are better, and a head of staff asked me to reduce the cell count from 4->3. For all of these reasons I'm not getting rid of the separate cells.
- Re: APC, I have not changed anything about the APC placement for perma in this PR. Could it be closer? Sure. But there's also an argument that keeping it away from perma (more noticible, easier to fix, etc) is smarter. It has been this way forever and I don't see a compelling case for changing this.
- Re: Lighting, are you suggesting it is a good idea to give perma prisoners the ability to turn off the lights, letting them hard in the darkness? 
- Re: Cramped: its a prison, its meant to feel at least a little cramped. Also people would complain about it being 'too big' if I made it any bigger. There are some people who seem to be against ANY size increase, so I feel like I have to be highly averse to size increases if I want this to pass.

@SpaceTimeNow
- You can already move a prisoner to solitary. This PR does not change this at all. Actually it makes it slightly easier with isolatable perma bedrooms.
- Consider the flak this perma remap PR is getting. Now think: would a PR that makes an even bigger change, like moving perma to effectively a new zlevel, cut off from the station, be able to pass on github? Consider that this would have all the controversy of a perma remap PLUS gateway changes PLUS labor camp changes. All together. I agree with you that it is a neat idea, and I even agree it could be more fun / better. But I also think it would have a slew of issues that would need to be worked out, and most likely it would be too controversial to pass even if it had merit and the issues were all adequately addressed. Even if it could be made to pass, it would require so much debate/argument to convince everyone that it is just too much hassle for me to be willing to do. Sorry. 

@Da-Dman234
- Thank you for testing it. I appreciate it. :)

**Comment by SpaceTimeNow** [comment]
@Kyep What i meant is to merge normal cells and perma brig, nothing more. The whole new z-level idea was just something that came to mind while i was writing and i honestly didn't expect it to happen, i just thought it was a neat idea.

Currently we have the issue, that perma is not being used, for multiple reasons and sometimes very valid reasons. I mean my vox could just space walk out of there, perma brig is just a leftover that was never touched while more and more races and different ideas were intodruced. Additionally we are kinda missing the customers for perma brig, everything that warrants perma brig cannot be done by non-antags because it's forbidden by server rules and every antag that is found will most likely be killed. 

On the other hand the "normal" cells are just rage inducing, especially so since the usual powergamer security officer will just remove everything that could be used to escape and will just leave you there completly ignored. Being mostly alone in a 3x3 room with no chance of escape for like 30 minutes just sucks.

So if we take the unused perma brig and merge it with the normal cells than we could actually get something that fits the server.

**Comment by Kyep** [comment]
@SpaceTimeNow 
- Merging temp and permabrig is an interesting idea. I'll have to give it more thought. I don't think its really in scope for this PR, but I'll have to think about it over the coming weeks.
- I have to say, I do think perma is used more than the alternatives for capital crimes. I generally won't authorize execution for capital crimes unless the person is a clear serial murderer. In shifts I Captain at least, perma sees more use than the execution chamber or borging table. I'd actually prefer more gateway exiles too, but this option is not considered on par with the other three. It would be rather like your exile z-level idea, just using gateway missions for this purpose.
- I 100% agree with you that the normal brig cells are rage-inducing. It isn't just that they're tiny, and have nothing to do. Its a whole slew of reasons, from over-long holds in processing, to sec not letting you out on time, to sec stripping you of everything but your underwear for a 5-minute lightbulb vandalism sentence. I would like to do more to address that, but I know of at least one person who'se thinking about changing tempbrig - they're just waiting for remaps like this one to get merged before they do it. If they don't do it I might have another go - I had a previous PR where I remapped tempbrig too and I might bring that back. It had various enhancements to make tempbrig less terrible. If I bring it back as its own PR maybe I'll do it with a shared tempbrig area and other more radical changes.

**Comment by Aurorablade** [comment]
@Kyep 
(baseing off current screenshot)
Re:Re: boxy, no hes right, even if made up of square tiles it can still defy its boxy nature if you are clever enough.
Re:Re: Basketball, Cuase the holodeck is made to fit the holodeck space, this could reflict a one hoop court design..yes those exists i have one a block away from me IRL.
Re:Re: N2O,The design is already getting complex in some degree..it needs to be able to hit some areas even if its a slow spread.
Re:Re: Dirt, do a 2 - gap - 2 design..or steal metastaions.
Re:Re: Toilet,Our current one has on the map has the split.
Re: Game board, might need to close the gap/push the botany area IN or set up a window devision between the botany area and the rest of the room via windows..and move the bored else where.
Re:RE: Windows, as an aesthtic you need windows..if anything make them full reinforeced with electrified grills and have a lock down shutter system in place.
Re:Re: Individual cells, if you do it for that purpose you may need to remove the double door entry area to the left of the cells and just leave the individual cells as a security entry area.
Re:Re: Separate bedding area: It needs to be there, either the cells need to be made into a vistor area/transfer areas and a small room made for bedding or the cells need to be reduced in tile size.
Re:Re: APC,I would need to double check this...
Re:Re: Lighting, Yes, if anything add a lightswitch on the outside that a officer could use to turn them back on.
Re:Re: Cramped: its a prison, Don't make it bigger but the layout could be changed in a way to make it feel less cluttered..or things could be removed.

**Comment by Kyep** [comment]
@Fox-McCloud  @DaveTheHeadcrab @Plotron @tigercat2000 @Aurorablade 

New layout uploaded. Looks nothing like the previous layout.
Image: http://i.imgur.com/D6MZ9bz.png

Re: Boxy, see updated image. Way less boxy.
Re: N2O: added
Re: Dirt: changed
Re: Toilet: changed
Re: Windows: added
Re: Game Board: moved
Re: Cells: layout changed
Re: APC: moved
Re: Lighting: Added

**Comment by FreeStylaLT** [comment]
oh god i hope this doesn't conflict

**Comment by Kyep** [comment]
Updated to even include roughed up edges, and a few more improvements.

Naysayers, take a second look please.

**Comment by tigercat2000** [comment]
This looks a lot better now. The edges jutting off into space reduce the boxy look, along with the non-perfect rectangular rooms like the garden.



This bit is still a bit odd- having a perfectly clear rectangle from the window to space.


Other than that, I suppose it's at least mildly better than our current permabrig, so :+1:

**Comment by IcyV** [comment]
I don't really mind this new take on it all that much. I think botany might stick out a little far, but it's not the biggest thing ever.

Personally I'd go with not giving perma a full set of botany machines. I'd leave it at more of a basic gardening tier with some pre-selected seeds and just enough to get the work done.It's a hobby for them to kill their time on, not full on botany. It'll mark the third full garden on the station.

**Comment by IcyV** [comment]
@Kyep Ah, for some reason I thought I had seen more in there earlier when I glanced over it. The botany seems good to me then, save for still seeming like it sticks out.

I do still have a mixed opinion on the cells after thinking on it, but I dunno. I always kinda like the aspect of needing to control prisoners well when you had to bring them in there. It probably shouldn't be a solo job in most cases as well. Making people process through little airlock cells takes that fun out of it. The tight main airlock that currently exists has made so many interesting fights and near-escapes with how its setup. That's extremely unlikely to happen in this one.

**Comment by Fox-McCloud** [comment]
Botany has no seeds? Also the double windows with the clown mask is really weird.

**Comment by TheDZD** [comment]
Might need to view the full size image to read the text, but here are my opinions
image

**Comment by Fox-McCloud** [comment]
conflicts

**Comment by Kyep** [comment]
@Fox-McCloud @TheDZD 
- Conflicts resolved
- DZD, your changes were made.

**Comment by Fox-McCloud** [comment]
@FreeStylaLT map edit takes precedence here.

**Comment by Kyep** [comment]
Merge conflict. Will resolve after @FreeStylaLT 's PR is merged. Don't feel like having to resolve the same map merge conflict twice.

**Comment by Kyep** [comment]
@Fox-McCloud @TheDZD map merge conflict with sec remap PR fixed, this is ready for review again.

**Comment by Kyep** [comment]
@Fox-McCloud @TheDZD Merge conflict fixed. Please review.

**Comment by Fox-McCloud** [comment]
conflicts

**Comment by Kyep** [comment]
@Fox-McCloud @TheDZD Conflicts fixed. Please merge before more conflicts. :/

**Comment by FreeStylaLT** [comment]
Will Kyep get his perma merged? Will it conflict again?

find out next time on Githuball Z

**Comment by Kyep** [comment]
@Fox-McCloud @TheDZD Conflicts fixed. Time #5? 
Please consider merging this.

@FreeStylaLT The answers were "I hope so" and "yes".

**Pull request merged**
