### PR TITLE
Adds an alternate, heavier NOBLE cyborg chassis. 

### PR DESCRIPTION
**Pull request by TravellingMerchant**
**Brand new from Shellguard Munitions Manufacturing:**
Introducing the latest iteration of the popular NOBLE Cyborg chassis, The NOBLE-H! This new and improved body has increased protection and a heavier, more intimidating style. New legs have been installed to accommodate the increased weight of the new parts.

___________________________________________________________________________________________________________

Adds a new type of the NOBLE cyborgs with a heavier frame to every department besides service. 

Also capitalises the names in the selection list to fit for the original NOBLE's. 

heavy dronetypesbig

Medical and mining also have extra very minor animations, being a small blue strip light on the mining borg and a turning saw on the medical borg.

BEEP BOOP.

### CODE REVIEW

**Comment by KasparoVy** [comment]
Quite a few of us were convinced this was a full-on mech

**Comment by TravellingMerchant** [comment]
@KasparoVy Only one I saw was birdtalon, no one else even mentioned mechs when I showed them off? 

Anyway, these should still be quite clearly identifiable as the NOBLE cyborgs.

**Comment by Crazylemon64** [comment]
This kinda looks "mech-shaped" to me, as nice as it looks

**Comment by SamHPurp** [comment]
Sorry, absolutely not, this looks like a Mech.

**Comment by KasparoVy** [comment]
If this is more mech-like than the original noble borgs, and THOSE were called mech-like, I think that makes these basically autonomous mechs

**Comment by HereticChurch** [comment]
Nobody will mistake these for mechs since everybody already knows what the mechs look like and we've never added new ones and likely won't.

**Comment by FalseIncarnate** [comment]
These would make great mech skins, but I think they are far too bulky for borgs. That yellow one (mining?) looks like a really cool alternative to the standard RIPLEY, and that white one looks like a minor adjustment to the standard ODYSSESUS.

**Comment by taukausanake** [comment]
We need borg mechs like tachikomas. How awesome would it be to pilot a mech that is also a borg?

**Comment by Fox-McCloud** [comment]
These look too much like mechs *and* these really aren't differentiated enough from the originals.

**Comment by Dinarzad** [comment]
Unless mechs have implemented silent running rigs and no longer make screen wide stomping noises.
You can't mistake these for mechs.

**Comment by taukausanake** [comment]
> silent running rigs

Well there's the mime mech but that's not a good argument by itself. Also you can see past borgs; you can't with mechs

**Comment by IcyV** [comment]
It feels like you're trying to put in too much detail. The sprites *look* fairly good but it feels way too big. A classic borg sprite matched up against a human isn't all that much bigger. They are usually taller but not all that wide. It has plenty of empty space in the tile. This sprite takes up basically the whole tile, much like a mech. If you shrunk them down some more I think they could work out great. 

The beauty of classic borg and mech sprites is that they stand out as what they are at an easy first glance. When I came into the game and saw a borg, there was no doubt in my mind that it was some kind of robot. When I saw a Ripley, I had no doubt that it was a large suit of some kind that could fit a person inside.

With some tweaks I think these could be absolutely amazing skins for a lot of things but I just don't see them as matching what a borg should be in their current iteration.

**Comment by TravellingMerchant** [comment]
I agree with what some of the others are saying. There's no way these can be mistaken for mech suits just because of how they work. I'm not even sure if mech skins even exist. 

@dinarzard makes some excellent points. 

Currently my NOBLE borgs certainly feel like the most commonly used borgs next to bloodhounds and occasionally the floating arm medical droid. These retain just enough of the original NOBLEs so they won't be confused with mechs at all.

**Comment by Rurik123** [comment]
Great sprite work. While it does resemble a mech in a small way, its not very hard to view it as a borg either. I'm not seeing the issue.

**Comment by SamHPurp** [comment]
Are you honestly saying that these cannot be mistaken for mechs because they don't look similar to existing mechs? Ignoring silhouette etc? Is that really your arguement here @TravellingMerchant ?

**Comment by TravellingMerchant** [comment]
You're twisting my words and getting it wrong. I'm saying they look similar enough to the NOBLE borgs, which are seen around the station all the time, to be confused with mechs. 

You're also ignoring the argument that they don't act like mechs. You can see through them, they don't make huge clunky mech sounds and they move differently.

**Comment by ZomgPonies** [comment]
How about creating a new mech type using these sprites instead of trying to justify that they fit the theme of borgs? I've been pushing for more 'Civilian' style mechs in general, this would be a good example. Of course, you'd need to create additional 'broken' and 'in-construction' states, but that would seem to be the best use for them.

**Comment by taukausanake** [comment]
> How about creating a new mech type using these sprites instead
more 'Civilian' style mechs

TACHIKOMAS. These would be perfect for them! Why does no one think so too? 😞 The only problem is the additional coding to make a borg and human share control of the mech but it could be so cool to have around

**Comment by FalseIncarnate** [comment]
@taukausanake you could probably make AI/human shared control things work similar to borers or AI-override RIGs, where the current "pilot" can hand off control willingly or the "backseat pilot" takes over if the current one goes inactive.

However, that is a topic best left to a suggestions forum thread and not this PR's comments.

I like the sprites, but feel they are simply too bulky for your average cyborg, but would work quite well as a mech alternative. The lack of stomping, vision blocking, and other things simply doesn't do enough to communicate that they are meant to be (roughly) human-sized synthetic constructs and not full-sized mechas.

Whether or not your last iteration of this line of borg chassis truly is the most used does not change that these are significantly blurring the line between borg and mech when it comes to visual identification. Yes, there are still some differences which can visually (and audibly) distinguish the two, but they are rather easy to miss (wearing mesons/xray glasses can lessen or negate the vision blocking, having other loud sounds or muted sounds can do the same for the auditory cues). Make these available as mecha customization kits so you can reskin the existing mechs to use these versions and I think you've got a solid PR that few will oppose.

**Comment by TravellingMerchant** [comment]
working on slimmer designs.

**Comment by TravellingMerchant** [comment]
Not dead, still working. Been very busy.

**Comment by TravellingMerchant** [comment]
Here we go, preview of the slimmer versions. What do you think? 

heavy dronetypesthin

**Comment by taukausanake** [comment]
They look better for borgs but I really was pleased with the previous design. I see you scrunched them down the center. I'm just not feeling it with these new ones

**Comment by KasparoVy** [comment]
I think both designs look fantastic. I hope the powers that be are happy with at least one of them.

**Comment by SamHPurp** [comment]
@TravellingMerchant in your mind these are still cyborgs and not mechs?

**Comment by TravellingMerchant** [comment]
Very much still cyborgs. Size wise they don't take up nearly as much of the sprites room as mechs.

**Comment by SamHPurp** [comment]
They are without a shadow of a doubt, mech-like in appearance. I cannot condone...

**Comment by IcyV** [comment]
Could we get some views like in the main post of what they look like on a normal tile? It'd be nice to have the easy comparison.

**Comment by Dinarzad** [comment]
@SamHPurp  No, you have to compromise somewhere. You asked for changed, cited your reasons, reasons that were frankly kind of flimsy to begin with, but regardless now those changes have been made. You have to give a little to get a little.  Taking this hard lined "All or nothing" approach to something as small and unimportant as cosmetics is asinine and serves no purpose other then to make a simple matter excrutiatingly complicated unecessarily.
No player in their right mind would honestly mistake these for mechs aside maybe the newest of new players, and I hate to be the one to say it but if that's the big lynch pin argument point here, then we better start slashing out all sorts of shit that might be awkward on new players (God forbid they join in a Changeling round amirite?).
Any other EXPERIENCED player will: Notice they can see through them. Notice it isn't making stomping noises and notice "Oh hey, these look color-coded to a department."

**Comment by SamHPurp** [comment]
@Dinarzad I refuse to spend the time burning down your straw man... but I will say that I've given more detailed feedback in other mediums, and a headmin just gave his feedback, which was identical to mine.

**Comment by TravellingMerchant** [comment]
I don't see any head admin feedback on the newer versions yet. What on earth are you talking about?

**Comment by SamHPurp** [comment]
image

**Comment by TravellingMerchant** [comment]
Ah, I missed that because no one pinged me.

**Comment by Dinarzad** [comment]
@SamHPurp I don't think you fully understand what a strawman is, if you're trying to dismiss my argument as a strawman.
At no point did I misrepresent, exaggerate or fabricate what your response was. Your very own words were "They are without a shadow of a doubt, mech-like in appearance. I cannot condone..."
So yes, your argument is that you are taking a hard-lined stance on imposing unecessarily strict limitations onto something.
And I frankly don;t care if a headmin agreed with you, the President of Zimbabwe could walk into this argument and agree with you, just because another human being agrees with a flawed argument doesn't make it LESS flawed. Two people saying the Sky is purple does not make the Sky purple.

**Comment by SamHPurp** [comment]
> No player in their right mind would honestly mistake these for mechs aside maybe the newest of new players, and I hate to be the one to say it but if that's the big lynch pin argument point here

image

Ignoring you outright calling me crazy in your opening statement, take a look at this image.

It looks too much like a mech, because it looks like a slimmer mech. It doesn't look like existing robots in any way... and I didn't cherry pick the smaller cyborgs, I easily could have.

See how the arms come off the side? See the wide stance?

Just because I've not personally explained my thoughts on this directly to you @Dinarzad , doesn't mean that I'm taking a "hard-line approach". I've given my thoughts, I've explained ways to get around this to improve.

My referencing a headmins comment (which was missed by the author, so I'm glad I was able to show him it), was to show that I'm certainly not alone in my criticism of this, the headmin is one of the deciding votes on this even!

Stop getting butt-hurt over someone disagreeing with you. This is the internet, its going to happen a lot.

**Comment by Dinarzad** [comment]
> Stop getting butt-hurt over someone disagreeing with you. This is the internet, its going to happen a lot.
Long post on the internet? must be butt-blasted, Better assume intent. That's always the smart way to argue. Yessir, nothin' like Mama's Ol' Fashioned Assumptions before breakfast, like God intended.
Also might not be the best position to assume things, if the common turn of phrase "No one in their right mind" makes you immediately assume I am ACTUALLY calling you insane. It's a turn of phrase. Lots of people say it. It's actually okay, I promise.

As for the image and meat of the response, Yes it doesn't look like existing cyborgs. I... I thought that was the point of making NEW icons... To be different and provide aesthetic options and styles. "Stance" isn't justification for anything, yes it is wider, that's an objective fact. But again, you're trying to force SUBJECTIVE opinion as an OBJECTIVE Goal. "This is mech-like to me, ergo, I cannot condone it." It looks mech-like to YOU.
I, the author and apparently several other people so far don't really agree with that stance as has been made extremely evident already in this very PR so *I'm* not alone in MY argument either. And yes. The headmins can over-rule and do whatever they jolly well please. That doesn't make them infallible or any more right or wrong, it just means they have the final say. I don't have to bend over and kiss people's asses if I think they're making an asinine choice just cuz they're making the final call and they don't have to bend over and kiss my ass just because I disagree.

And just because you've explained your thoughts doesn't make it LESS of a hard-line approach, but I never asked you to write me a thesis on the intricacies of shitty space game mech designs in pixel art form, so Iunno where you're getting that line from.
Just because you have elaborated on your stance, doesn't make it more or less strict. You're just explaining why you feel something. It is still pushing your own subjective tastes as an objective statement "This is too much like a mech."
You explained your reasons it is mech-like and I explained MY reason that there's WAY more to Identifying a mech then sprites.

Stop assuming you're the center of the world and other people who disagree with you are just butt blasted. It's the internet, people are going to disagree with you a lot you know.  =^)

**Comment by SamHPurp** [comment]
@Dinarzad You are the one that has decided that this is their hill to die on.

You are the one that has specifically called out my objections to the PR.

You are the one that has decided they wish to try to start some asinine argument over something so simple as a proposition of a sprite for a cyborg/mech.

I replied giving my updated view on the updated 'slimmer' sprites, as was requested by the author who specifically sought out an opinion on Discord, that Discord image cuts off where the author specifically @'d my name to request it.

I'm not acting as some PR executioner, that curse is for other unfortunate men. I'm honoured you seem to believe I have such power.

I shall always give my opinion while I am still free to do so - especially when it is asked for. I'm not sure what you're getting out of your original message and the subsequent ones designed to attack me and my opinion.

This is subjective, yup, as is everything with visuals and sprites. However, you concede the sprite visually looks more like a mech, but 'there are other things to tell it apart from a mech'. As you seem to communicate in strawmen, then maybe you'll understand this: In the same way could I not have a Cyborg Sprite that looks like a pint of beer? I mean, it'll be obvious I'm not a pint when someone tries to imbibe me?

**Comment by taukausanake** [comment]
You know that image comparison that was put up... You do realize that there are many design similarities that separate borgs and mechs. You notice then that these sprites match up with the borg design and not the mech. More blended colors, no solid outline, less armor parts. Just adding my two cents into the mix

**Comment by Dinarzad** [comment]
>  In the same way could I not have a Cyborg Sprite that looks like a pint of beer? I mean, it'll be obvious I'm not a pint when someone tries to imbibe me?

Except that metaphor and example doesn't work on a hilarious number of levels. Not the least of which is a Cyborg and a mech are not that dissimilar, they are both large bulky machines. One piloted, the other autonomous.
A Cyborg and a pint of beer are entirely different classes of ojects, share no similarities (I guess both are manufactured?) and are a nonsensical comparison.

I also REALLY think you should review what a strawman is, you keep using that word and I don't think it means what you think it means. A strawman fallacy is misrepresenting, exaggerating or outright fabricating someone's argument in the process of making your own argument seem the more reasonable one.
I have at no point, argued anything you have not outright said yourself. I HAVE used Metaphors or hyperbole, saying something is like something else in a method of providing an example. There is a very real difference between those two things.

> You are the one that has decided they wish to try to start some asinine argument over something so simple as a proposition of a sprite for a cyborg/mech.

I would fucking laugh, but I am just so much more confused. You DO realize you posted your insistence *before* I argued that very point, right? The sprites were too mech-like. I and others disagreed. They were tweaked anyway. You persisted. And I told you, you had to compromise somewhere and you were taking an unnecessarily strict stance on something as simple as sprites.  I REALLY think you should review your timetable here before you start spouting these kinds of claims, man.

> I shall always give my opinion while I am still free to do so - especially when it is asked for. I'm not sure what you're getting out of your original message and the subsequent ones designed to attack me and my opinion.

So you can argue and give YOUR opinion just fine. But when someone argues a clashing opinion that you don't like, well hot dog, they must just be butt hurt and mad and thus completely dismissible. I have never in the course of this debate attacked you personally, I made VERY careful sure of that actually.
Well that's not true.
As soon as you started to act like a smarmy prick, I DID start attacking you, but... I mean play stupid games, win stupid prizes.
Other then that you LOOKED for offense in a common turn of phrase, that's on you not me.

> This is subjective, yup, as is everything with visuals and sprites. However, you concede the sprite visually looks more like a mech, but 'there are other things to tell it apart from a mech'. 

I never really argued otherwise, but yes, I concede it looks a little mech-ish. That was my stance even from the beginning, in fact my initial post was that was okay for it to look slightly mech-like because of the myriad of other distinguishing features it was lacking, and the fact it already adheres to the standard existing right now. Things look like things a lot in this game, and in fact NOBODY has answered THAT part of my claim, funnily enough.
If we're going to follow this logic of "This looks like X ergo it has to be changed, can't allow it."
Then I expect a post haste fix to the APLU Firefighter unit and the red ripley. I mean those are literally just recolors, and could be confused together, right?
Or how about those syndie suits and sec suits, with the same black/red color scheme? Those look extremely similar (And people initially were confusing them together but have since adjusted. Almost like... people learn...)
Or that Maintenance drone sprite and the pAI recolor sprite.
The fact of the matter is, this adheres to standard on all fronts, and if you're going to persue this train of logic that similarity in appearance even slight ones, are god awful and must be rectified, and that's the path of logic taken on the PR, then I expect that standard to remain true, else it's creating and enforcing a double standard.

**Comment by Spacemanspark** [comment]
Would you chill out a bit.
Dear lord I'm getting a headache reading this.

**Comment by Dinarzad** [comment]
I COULD chill out if I was actually mad.
What is it with you people and going "Long post = mad" have you seriously NEVER had an honest to God debate about something like.... ever? You don't have to be furious to have one, in fact a genuine debate can be a GOOD thing.
It's a non-instant medium, where people have plenty of time to formulate a response.

But I'll keep in mind going forward that anything over 2 sentences is a raging frothing loony.

**Comment by Rurik123** [comment]
> See how the arms come off the side? See the wide stance? See the 'pod' like thing, big enough for a human to enter it? 

I could be wrong, but judging by the pic, I don't think a human could even fit in that. The 'pod' would only be big enough to contain the upper body and head, while the limbs would have no where to fit. Unless the arms and legs somehow fit into the wide stance of the borgs arms and legs, which Id imagine; if not impossible, highly uncomfortable.

And as taukausanake added, there is a lack of armor plating and no solid outline, as well as not having _as wide_ of a stance as the other mechs do. 

That being said, it would look to be a civilian mech/slimmer mech if a human could reasonably fit in it. But of course I haven't seen a side by side comparison so I could just be imagining human sprites to be bigger than they are. ¯\_(ツ)_/¯

**Comment by Spacemanspark** [comment]
>But I'll keep in mind going forward that anything over 2 sentences is a raging frothing loony.

Yes, let's twist my words.
I was referring to the ad hominium you were shit slinging at everyone.

**Comment by TravellingMerchant** [comment]
Uh... big old argument aside, which I certainly appreciate Dinarzad  doing...

Here is a comparison for the slimmer versions. 
comparison

**Comment by Dinarzad** [comment]
> Yes, let's twist my words.
I was referring to the ad hominium you were shit slinging at everyone.

[citation needed]

**Comment by FalseIncarnate** [comment]
The image @SamHPurp posted really offers a better perspective than the side-by-side with a human. Being able to easily compare the sprite to both borgs and mechs (and not just the RIPLY, but also stuff like a GYGAX and ODYSEUS) really highlights how this better fits the theme of the mechs than the theme of the borgs.

Both maintainers have agreed and stated that the sprites are more befitting of a mech, which has been also stated by myself and a number of other comment posters. The re-done versions are less bulky than the initial version posted, however they still suffer the concern Fox raised of not being different enough from your original NOBLE borg designs.

The main difference between the two versions (as illustrated in your latest picture) is that the head and torso have been replaced with what appears to be quite similar to the open cockpit of an unoccupied ODYSEUS, which is why a lot of people are saying it looks like it is meant to hold a person. If a person can fit in an ODYSEUS cockpit (which is roughly equal in size to the "face" of the heavy NOBLE), it isn't too unreasonable to apply that same logic to these borgs. The extra plates and longer claws are honestly too small of a difference to really set these apart on their own.

While I respect the fact that @Dinarzad approves of these sprites and supports your PR, I would like to request that they refrain from attempting to initiate a flame war in this PR any further with personal attacks like the ones their recent replies have been rife with. Even if you did not intend to make any, your attitude and choice of words makes it quite easy to view your statements as attempting to belittle or insult the other posters.

I still firmly maintain my opinion that these skins are well done but befit a mecha better than a borg, and that they should be made available as mecha customization kits (link to those included in my last reply in case @TravellingMerchant missed that) instead of as a borg option. You can even make those kits available in the mech fab for little-to-no cost, since there is currently no way to obtain a mecha customization kit as a normal non-donating player that I can think of at the moment (might be wrong, but i'm too tired/lazy to check that at roughly right now).

Everyone is entitled to their opinions, and I respect that, but please do not fall under the false assumption that your opinions are worth any more than those of someone who may disagree with you. In the end, opinions are like assholes: everyone has one, and you might not want to see it...

**Comment by TravellingMerchant** [comment]
I think the issue was that purple was just saying a straight up "NO NEVER!" rather than giving me a chance to edit them until they fit.

Artwork goes through revisions no matter what you're doing. If it's not right the first time, then I update and improve them. Which I'm doing.  I can't get everything right first time.

The direction I'm trying to make it look is impact resistant, fixed forward sensor like head. Think along the lines of the Fallout 4 sentry bots enclosed non moving head variant.

**Comment by Crazylemon64** [comment]
Sensor dome still looks a bit too much like a cockpit - is there some other detail you can add to make this not look like one?

**Comment by TravellingMerchant** [comment]
Read post above

**Comment by Dinarzad** [comment]
> While I respect the fact that @Dinarzad approves of these sprites and supports your PR, I would like to request that they refrain from attempting to initiate a flame war in this PR any further with personal attacks like the ones their recent replies have been rife with.

Citation needed.
IF my posts are rife with them as people keep somehow saying, please list them. Because to check myself I forwarded this very thread to two people I know that have had past experience in and that I trust to call me out on stuff of that nature and have done so with no shyness about it. Neither one of them plays this server or has any vested interest.
And neither one of them can tell what you guys are on about.

So I'm gonna need actual EXAMPLES of "Ad hominems" and "Personal attacks" I made past calling someone a prick a single time (Which is far from 'rife with') which by itself occured AFTER I was out of hand dismissed and chided, when no initial attack was made. I responded, did not instigate.
So if what I did was somehow a "Personal attack", cool. Understood. But I trust that same standard is going to be held to other participants, correct?

**Comment by Rurik123** [comment]
From what I read there was no "Personal Attack." Just a couple unneeded aggressive remarks and a couple other things that could have been worded differently. I can shoot ya a message via forums for citations and specifics if you'd like.

**Comment by FalseIncarnate** [comment]
`What is it with you people`
`Stop assuming you're the center of the world and other people who disagree with you are just butt blasted. `
These statements, combined with your increasingly agitated-sounding attitude, make it come off as you are attempting to belittle and insult the other participants of the discussion.

Plus, the whole `As soon as you started to act like a smarmy prick, I DID start attacking you` probably didn't help convey the message of "not personally attacking anyone"...

Let's leave the rest of discussion along that topic for a different medium such as discord or private messages rather than this thread. I expect everyone to act respectfully towards the other participants, that request was not meant to be directed specifically at any one individual (I meant to address that part to everyone but 5AM me apparently was not the cunning linguist he thought he was).

Keep it civil or we'll have to start deleting replies or locking the comments... which we'd really rather not have to do when advice and honest feedback is being given by some just because some others want to argue.

**Comment by TravellingMerchant** [comment]
Fixing the current NOBLE borgs, once their fixes are applied I'll start on a different variation.

**Comment by TravellingMerchant** [comment]
Closing PR, will remake as better soon.

**Pull request closed without merging**
