### PR TITLE
Gibson1027 Fluff items

### PR DESCRIPTION
**Pull request by TheDZD**
- Bear pelt hat subtype that is instead a polar bear pelt that has its nedges covered in blood.

Thanks to @tigercat2000 for recoloring the regular bear pelt icon.

### CODE REVIEW

**Comment by fj45** [comment]
Sprite?

**Comment by monkeysfist101** [comment]
"Thanks to @tigercat2000 for recoloring the regular bear pelt icon." But I did the recolor... I can give you guys the non bloody version too if you want.

**Comment by tigercat2000** [comment]
@monkeysfist101 DZD was refering to the item_state, not the on-mob icon.

**Pull request merged**
