### PR TITLE
cyborg rechargers

### PR DESCRIPTION
**Pull request by orelbon**
Adds cyborg recharger in security meeting room, and one in medical break
room.

meeting room
break room

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Could you give some pictures of the new chargers?

**Comment by Crazylemon64** [comment]
Well, I grabbed some pictures of the chargers:
Security:
security_recharger
Medical:
medical_recharger

It looks like some pipes and floor stripes were added here and there, too. What other changes did you make, @orelbon?

**Comment by Crazylemon64** [comment]
Also, :+1:. It really stinks running out of charge when you're working in a place too far away from the chargers, and being able to get back to work immediately when you finish is a good perk too.

**Comment by orelbon** [comment]
@Crazylemon64 i have no idea why its showing i added more, all i did was add the chargers.

**Comment by Fox-McCloud** [comment]
well, you don't have 170+ delitions/additions for adding literally 1 thing.

**Comment by orelbon** [comment]
Ill see if i can make a commit with a brand new map

**Comment by Spacemanspark** [comment]
:+1:

**Comment by orelbon** [comment]
Im gonna close this and open a new one, don't know why its giving me so much trouble.

**Pull request closed without merging**
