### PR TITLE
Adds a fluff item for Duckchan

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Your byond key: **Duckchan**
The name of the character you want to have the item: **Rybys Romney**
The specific jobs you want the character to have the item for: **all of them**, if that's possible.

It's a zippo. It does zippo things. It zippoes.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
What a wonderfully spooky lighter :ghost:

**Comment by Spacemanspark** [comment]
Too OP

**Comment by Fox-McCloud** [comment]
@FreeStylaLT

**Comment by FreeStylaLT** [comment]
👌

**Pull request merged**
