### PR TITLE
Researchable Medical Tools

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over Baystation's researchable laser scalpels and incision manager, a port of : https://github.com/Baystation12/Baystation12/pull/4487

What are they?

Basically, the three laser scalpels are an R&D item that can make an incision AND clamps bleeders at the same time--they have a higher failure rate of regular scalpels; the higher the level of the scalpel, the less chance it has of failing.

The fourth item is "Incision manger". This is an ultra high-end R&D item that creates and incision, clamps bleeders, AND retracts the incision--all without fail, every time; surgery will be a breeze with this tool.

Other
- Updated some edge+sharp vars on surgical tools
- surgical drill now uses the "drill" sound

Map Edits
- added some shutters to the bar counters for when things get too rowdy or he wants to step out for a few minutes and not get everything stolen.

Fix Related
- removed some carp spawns near Viro so the virologist can actually *do* his job
- Fixes some errors in door access in science (this will reduce Roboticist's GIGANTIC unneeded access)

### CODE REVIEW

**Comment by fj45** [comment]
How about you also get the nice sprite for saw back? No idea why we got the black one.

**Comment by Fox-McCloud** [comment]
I fixed that about 2-3 weeks ago =p

**Comment by fj45** [comment]
Ah great.

**Comment by FalseIncarnate** [comment]
Loving the laser scalpel, and the incision manager sounds incredibly handy! Do these still work for steps like preparing organs for removal where you need to use the scalpel to cut the connections and a hemostat to actually remove it?

Also, do they take the same amount of time as just a single step to complete 2-3 steps? If so, MASSIVE time-saver on those rushed surgeries.

Gonna have to make an energy knife for the chef now to slice and sear meat to perfection in one simple step!

**Comment by Fox-McCloud** [comment]
It does two (or in the incision manager's case three) steps in the time it takes to do one...and yes, you can use it for removing organs (or scalpel surgical steps) AFTER the initial open up as all of these are children of the regular scalpel.

**Comment by KasparoVy** [comment]
Exactly what access did the roboticist lose? Access to tech storage (insulated gloves), the chem lab, telescience?

**Comment by Krausus** [comment]
> "Researchable Medical Tools"
> Two commits
> Bar shutters
> Carp spawns
> Door access changes

Uhhhhh...
> * Your pull requests should be atomic. Balance changes, bug fixes and new features should all be in separate pull requests.
> * Your commits should be atomic. Make one commit for each distinct change, so if a part of a PR need to be removed/change, you can simply modify that single commit.
> * Please document and explain your pull requests thoroughly. What each commit changes and why. We do not want to have to read all of your commit names to figure out what your PR is about.

A lot of these changes aren't even tangentially related to each other, let alone to the title of the PR. Cramming them all together doesn't make any sense.

> removed some carp spawns near Viro so the virologist can actually do his job

No, you "removed **all** carp spawns anywhere near Viro", including one in range of atmos and one in range of the AI sat. Four spawns in range of virology is maybe a bit much, but being a nuisance is why carp exist - you can't just wipe them from part of the map because you don't want virology getting depressurized.

> Fixes some errors in door access in science (this will reduce Roboticist's GIGANTIC unneeded access)

Well, these "errors" aren't listed, so let me take a look...
* Telescience? I don't see why not, but they'd just go through the window if they wanted in.
* RnD? No - they need access to the autolathe and protolathe for robotics purposes, and there's no reason to prevent them from doing research. Also, adding an access req to the console doesn't do anything.
* Test lab? This finally gave them convenient access to acid. Access to *everything else* in here is maybe a bit much, but, ehh... is it really a problem?

This removes a **ton** of autonomy from robotics. They wouldn't even be able to make their dumb little cleanbots without breaking into RnD. Which, by the way, they could just do, because they get easy access to insulated gloves. But if they don't bother, they'd end up spending (even larger) chunks of the shift just sitting around twiddling their thumbs.

> Adds black card deck to bar

Unlisted change. I guess there's nothing really wrong with this, though they're one of the shady items that already spawn in the abandoned bar, so why add another to the real bar?

> Replaces roboticist's FixOVein with a surgical drill

Unlisted change. Also, why? The drill is only used on cavity surgery. I'm not sure if roboticists really have any use for the FixOVein, but I don't understand replacing it.

The new RnD surgical tools sound neat. All the other changes that got crammed into the same commit for no apparent reason, not so much.

**Comment by Robertha89** [comment]
map edited id locks on machinery is bad, infact, id locked machinery is mostly bad in some cases, cause if you deconstruct it, and set it up again it will change, but since the consoles have rnd access for that, it won't be much of an issue since roboticist got that access already.

**Comment by tigercat2000** [comment]
Uh, I agree with @Krausus. The robotics changes shouldn't even be near this PR, and for that matter, they shouldn't exist at all IMO. 
Robotics has access to all of those areas for a very specific reason- when RnD is unoccupied or every scientist has gone off to ERP at the science outpost, they don't have to smash a window to make their RIPLEY board or whatever. 
I believe telescience has always had generic RnD access, so that even the geneticist could get in. 
The test lab, I see absolutely no reason to prevent them from accessing their only source of acid, since chemistry will obviously throw a fit "why don't you just use the test lab, you are wasting my time"

**Comment by KasparoVy** [comment]
Horrified by the huge loss of robotics stuff. I find myself, often playing roboticist, doing all of the research as wel-- and being able to make acid for the machines is mucho importanto

**Comment by ZomgPonies** [comment]
I also agree with Krausus that this seems a step back into old shadowmerges, 'convenience' balancing for the bar (There's literally nothing to worth stealing from the bar that would mandate shutters) and virology, and other shenanigans that led to trouble and drama in the past.

:-1: This PR until you remove the shadow features, the map edits and the convenience 'fixes'

**Comment by Necaladun** [comment]
Yeah, this isn't atomic at all.

I like the laser scalpels, been waiting for those, but the rest of the stuff is questionable. I'd love those added, but without it being atomic that can't happen.

**Comment by Fox-McCloud** [comment]
I made this PR very shortly before going to bed and it really shows. Lol

I changed the space carp because it was related to medical then kept on going.

**Pull request closed without merging**
