### PR TITLE
Makes spinning a character spin the character's screen in the opposite direction

### PR DESCRIPTION
**Pull request by monster860**
Basically, when a flip effect is involved.

Anything with an infinite amount of loops is not affected.

[https://gfycat.com/CaringMintyKingfisher](https://gfycat.com/CaringMintyKingfisher)

:cl: monster860
rscadd: Spinning a character now spins the character's screen in the opposite direction
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Please no; this is going to make anything that makes you spin annoying as hell.

Fliptonium will go from being as silly chem to a something that will induce motion sickness into a good number of people and/or make them horrendously dizzy.

@monster860 pls.

**Comment by TheDZD** [comment]
This is going to result in horrible horrible disorientation when an admin uses `SpinAnimation()` with -1 for a time on people, or when fliptonium smoke grenades go off.

**Comment by monster860** [comment]
The screen won't spin unless there's a finite amount of loops.

**Comment by Fox-McCloud** [comment]
It's still going to make the ever popular *flip emote a horrendous headache.

**Comment by taukausanake** [comment]
You mean this is affecting basic flip? I thought this was going to be a new verb/command. No, don't like. You're not flipping in first person so your screen shouldn't flip while you seem stationary

**Comment by KasparoVy** [comment]
LMFAO dude that's bonkers, I love it. Sucks that I'm the only one with this opinion but I think it's dope.

**Comment by Fox-McCloud** [comment]
This also means anyone you *throw* would also flip around, which would make throwing people an incredibly disorienting combat tactic.

**Comment by Ar3nn** [comment]
well this could become the new thing since tabling is gonna be out with that grab refactor. Or do you need an aggressive grab to throw? I don't know, I don't do shitty things often enough to need advanced melee combat shenanigans.

**Comment by Regen1** [comment]
It looks fucking hilarious, but from a visual "gameplay" view it's also just too much.

**Comment by CrAzYPiLoT-SS13** [comment]
Please no.

**Comment by ProperPants** [comment]
This is fucking horrendous and I love it. Turn it into a preference if you really want it to go through, so anyone who doesn't want it doesn't have to be subject to it.

**Comment by Vivalas** [comment]
I really like it. Sucks all the cool things you make get instantly shot down.

**Comment by Injazz** [comment]
muh headache

**Comment by Ar3nn** [comment]
I do like some of monster's ideas.

**Comment by Gummin** [comment]
I really like it, but if this were ingame I would literally NEVER flip again.

**Comment by SpaceTimeNow** [comment]
Why? No.

**Comment by TheDZD** [comment]
Screen effects are good for visual feedback, but shouldn't be excessive to the point where they cause people to actually feel motionsick.

**Comment by Fox-McCloud** [comment]
Generally very negative response here, and I'm going to concur with @TheDZD on this one, too.

Sorry @monster860

**Pull request closed without merging**
