### PR TITLE
Esword visual update

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
:cl: Tayyyyyyy
tweak: Energy swords, energy daggers, energy cutlasses, and energy axes emit light. Toy versions do not.
/:cl:

Game engine footage:

purple

blue

green

red

edagger

vader

Rainbow is just white light.

### CODE REVIEW

**Comment by KasparoVy** [comment]
I feel like this is going to get hella downvoted because bad memes and the "it doesn't have to make sense" argument. Screw that. :+1: :100:

**Comment by SamHPurp** [comment]
This is great, I had it on my list of things I was gonna add to Para aaaages ago.

👍

**Comment by granodd** [comment]
I mean, it's a blade made of energy, the fact that it wasn't emitting some form of light is confusing. Though another thing that kind of baffles me about energy swords is the fact that they do brute damage instead of burn 🤔

**Comment by alexkar598** [comment]
Why rainbow is not rainbow light?

**Comment by Tayyyyyyy** [comment]
> Why rainbow is not rainbow light?

Because the rainbow sprite flashes between different colors, and there's no way to programatically tell which color it's currently flashing. So if I made the light flash different colors, it just wouldn't look right.

I want to also look into adding muzzle flashes to firing ranged energy weapons, but I'm afraid to look at the code for that...energy melee weapons are already a tad bit snowflakey.

**Comment by Denthamos** [comment]
@Tayyyyyyy I love this.  Its atmospherics for the game that adds to its depth and feel.  The muzzle flashes for ballistics and light for the lasers would be amazing as well but yeah, that seems a lot more complicated in such.

I was thinking though, should stun batons when sparked provide a small amount of lit around them as well?

**Comment by Tayyyyyyy** [comment]
There's a lot of things, now that I think about it, that could use some lighting. I wonder if it'd be possible to have flashbangs for example also briefly light up an area.

**Comment by KasparoVy** [comment]
@Denthamos There's a PR up for that on Bay's github.  Worth looking at

**Comment by Vivalas** [comment]
It looks great, even if it changes balance a bit.

**Comment by davidchan13** [comment]
TOY Eswords are a weapon against slings. Short of adminbus or nigh impossible RNG involving mining or a good gateway mission, you're never going to fight a sling with a real esword.

As for it being less stealthy, the sword already makes a unique and easily identifiable noise when being drawn, used to attack or disabled. The only people this meaningfully would affect are those rare syndies who buy thermal implants or thermal goggles.

Would definitely like to see glowing holoparasites though.

**Comment by Ralta** [comment]
@davidchan13 From the perspective of stealth, it would make you visible in maint for the purposes of disarming / attacking (or even running away). Not that I think this is a bad thing, but just something to consider.

Personally, I love it. The idea of drawing someone into a corner of maint and just activating the esword; the glow would be very atmospheric.

**Comment by davidchan13** [comment]
@Tayyyyyyy Apply this to toy eswords too!

**Comment by Tayyyyyyy** [comment]
Okay, because the single esword is a bit more snowflakey than the dual esword, right now, dual toy eswords do have light, but toy single eswords don't. I think it'd be best make the toys not have any light so that slings aren't affected, plus it kind of makes sense since the toy esword is plastic. That or make the sling veil retract toy eswords.

**Comment by Fox-McCloud** [comment]
https://github.com/tgstation/tgstation/pull/24765 recommend this implementation.

**Comment by Tayyyyyyy** [comment]
> tgstation/tgstation#24765 recommend this implementation.

TG's sprites look way better actually. I'll see if I can port them over too.

**Comment by Vivalas** [comment]
@davidchan13

Not exactly, you can navigate maint easily and stealthily with nothing but mesons in the dark, and most experienced players can probably do it just by memory as well.

Not that I really care, if anything it's probably good. Doesn't make sense to be able to hide in the shadows with a.... lightsaber.

**Comment by tigercat2000** [comment]
@Tayyyyyyy Are you going to change to /tg/'s implementation?

**Comment by Tayyyyyyy** [comment]
I think so! I'm gonna add a brightness_on variable and disbable the glow on the toy dual esword. Should be ready for another review on the next commit.

**Comment by Cactus2388** [comment]
Does this add color to the energy dagger as well?

**Comment by Tayyyyyyy** [comment]
> Does this add color to the energy dagger as well?

Good catch! It doesn't. I'll add this to energy daggers too.

**Comment by Tayyyyyyy** [comment]
Okay, things are a little better now. Energy axe has white light and pirate energy cutlass has red light. Toy versions should no longer emit light. Haven't had the chance to test the energy dagger so that's not pushed yet. Will update in a bit...

**Comment by Denthamos** [comment]
Do not forget the E-Saber glow which can be found in certain gateway missions + admin events.

**Comment by Tayyyyyyy** [comment]
> Do not forget the E-Saber glow which can be found in certain gateway missions + admin events.

Can you tell me the name of this item? I can't find it in the code.

**Comment by Tayyyyyyy** [comment]
New tg sprites are fully ported! Let me know if you all want more screenshots:

tgsabers

**Pull request merged**
