### PR TITLE
Fixes #9510

### LINKED ISSUE #9510: Atmospherics external access airlocks are not usable by AI and Borgs.
**Problem Description**:
The atmospherics external access airlocks (Just above the transit tube to the AI sat) are vardited to have AI control disabled and hack proof enabled. 

**What did you expect to happen**: 
I expected the airlocks have the same settings as all other external airlocks on the station.

**What happened instead**:
Airlocks are neither controllable nor hackable by AI/Borgs

**Why is this bad/What are the consequences:**
Cyborgs can not use these airlocks to enter or exit the station.

**Steps to reproduce the problem**:
Be cyborg or AI, click on the airlock.

### PR DESCRIPTION
**Pull request by TDSSS**
Fixes #9510 

First ever map edit so let's hope I didn't horribly fuck up.

:cl:
fix: Atmospherics external airlocks can now be controlled by borgs and AIs
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Might want to check if there's any others like this. If there are...this may be intentional.

**Comment by alex-gh** [comment]
@Fox-McCloud 

There are others like this, but only as a shuttle airlock. This is the only external airlock that has this.

**Comment by Taaketa** [comment]
This must be a recent change to this airlock because I swear only a couple of months ago as a borg I was unbolting those doors.

**Comment by TDSSS** [comment]
Conflict might be with #9438 since that was merged in after I made this and they're both map edits but not a mapper so 🤷‍♂️

**Comment by TDSSS** [comment]
Uhhh, that's a lot of diff...I guess I'll just start over and do it again.

**Comment by TDSSS** [comment]
There, all fixed again.

**Comment by SamHPurp** [comment]
My understanding is that this is intentional design decision. So changing this is a balance change, not a fix.

**Comment by alex-gh** [comment]
Do you happen to know the reason for it?

**Comment by TDSSS** [comment]
I really don't see why you'd make this one airlock out of all of them not controllable as an AI. If it is intentional, it must have a really weird reason.

**Pull request merged**
