### PR TITLE
[IDB Ignore] Refactor icon smoothing to use 8-bit bitmasking

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR ports a number of tweaks from TG, mainly:
https://github.com/tgstation/tgstation/pull/52864
https://github.com/tgstation/tgstation/pull/53906
https://github.com/tgstation/tgstation/pull/54441
https://github.com/tgstation/tgstation/pull/54129

**It also ports TG smooth table sprites, that themselves are ported from Sunset station (Credits to Quantum-M for the sprites).**
https://github.com/tgstation/tgstation/pull/50753

To quote Rohesie from his PR, who explains bitmasking very well:

This is a backend refactor on icon smoothing, using 8-bit bitmasking ( https://gamedevelopment.tutsplus.com/tutorials/how-to-use-tile-bitmasking-to-auto-tile-your-level-layouts--cms-25673 ).
This shows the 47 combinations, given that we only smooth diagonally if the cardinal components are present: http://www.cr31.co.uk/stagecast/wang/blob.html
The actual values for the directions are not the same because BYOND already has its own definitions and there's no reason not to piggyback on that.

The idea here is to, instead of assembling the icons at runtime from the cut corners, to pre-bake them in order to diminish both memory cost (all the image objects and the extra variables) and processing (less runtime icon operations), at the cost of a little size in the .rsc file.

## Why It's Good For The Game
This makes spriting **MUCH** easier to sprite smoothed objects, as the icon files move from looking like this:

image

To looking like this:

image

If you are in the middle of a sprite PR using the old system, worry not. Rohesie also made a small rust-based tool to automatically port your sprites, with some small initial config setup. https://github.com/Rohesie/icon-cutter

## Images of changes

> The ones changed are: Normal Table, Glass Table, Poker Table, and Wooden Table.
> dreamseeker_2020-04-29_13-40-27
> dreamseeker_2020-05-01_11-03-28
> dreamseeker_2020-04-29_13-41-06
> dreamseeker_2020-04-29_13-45-30

## Changelog
:cl:
tweak: New table sprites from Sunset station (Credits to Quantum-M for the sprites)
tweak: Grass creeps over turf edges like alien weeds
add: Jungle grass
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
image
image

Fed up of posting the same shit. A bigass refactor none of the maints replied to your singular ping in design chat with is exactly what we need right now.


Its a good PR, but this isnt going to be seen to for literal months.

**Comment by AffectedArc07** [comment]
```
[2021-09-01T11:51:55] Runtime in icon_smoothing.dm,156: /obj/structure/alien/weeds called smooth_icon() without being on a z-level
  proc name: smooth icon (/atom/proc/smooth_icon)
  src: the resin floor (/obj/structure/alien/weeds)
  src.loc: null
  call stack:
  the resin floor (/obj/structure/alien/weeds): smooth icon()
  Icon Smoothing (/datum/controller/subsystem/icon_smooth): fire(0)
  Icon Smoothing (/datum/controller/subsystem/icon_smooth): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)
```

**Comment by S34NW** [comment]
There are still issues with water I need to fix with this, and it requires some testing to make sure I've not missed any edge cases, but it's effectively ready.

**Comment by S34NW** [comment]
Issues to resolve:

Alien weeds doing this:
image

Invisible glass floors.

Carpets not properly smoothing.

**Pull request merged**
