### PR TITLE
Blueshield Balance Changes

### PR DESCRIPTION
**Pull request by ZomgPonies**
Blueshield loses a lot of the HoP access he has. As his job is STRICTLY to defend heads, he keeps the following access:
- Basic access to the main departments (Sec, Med, Sci, Eng)
- Bridge Access
- Blueshield Office Access

He also loses access to the sec channel on his headset, but keeps access to the command channel.

Hopefully these changes will encourage Blueshields to stick to their jobs guarding heads, and stop acting like supercops or station management. Additionally, we will be clamping down on Blueshields acting like shitlords and issuing tempjobbans as warning to offenders.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:
Does this mean I can start cracking down on Blueshits that start acting like security officers and irritating everyone else?

**Comment by ZomgPonies** [comment]
Absolutely.

**Comment by Spacemanspark** [comment]
Hell ya.

**Comment by JarlBrolaf** [comment]
Long overdue, I like this change.

**Comment by TheDZD** [comment]
The long overdue death of Blueshitcurity. :+1:

**Comment by SamCroswell** [comment]
Marry me, Ponies.

**Comment by Fox-McCloud** [comment]
Yeah, access_construction is the most basic engineering access; access_ engine is going to give Blueshield access to everything minus atmos.

Half ponder if Blueshield should get an egun instead of the revolver; will give him a lethal way of dealing with threats that doesn't involve dealing 60 damage per shot+illegal modification.

**Comment by Earthdivine** [comment]
I like the idea of the Blueshield having he pistol over the Egun because it means he can handle threats to heads that use EMP's. If he needs a lethal weapon he can bug people for an Egun.

**Comment by Earthdivine** [comment]
I apparently can't edit comments on the phone version of GitHub. The Blueshield REALLY should get cracked down on for modifying his pistol, other jobs get arrested for illegal modification, he shouldn't be the exception

**Comment by Fox-McCloud** [comment]
Hard to crack down on something that takes all of 2 seconds to do and isn't known until after it's done; it's the same problem with cracking down on chemists with polyacid spray bottles--you don't know it until way after the fact.

**Comment by Earthdivine** [comment]
Making the gun lethal doesn't make the rounds it starts with lethal, does it? If not then cargo/science should be telling sec when they are asking for lethal rounds. If it does make the existing ammo lethal then yea, agree with ya

**Comment by ZomgPonies** [comment]
Nope, it requires brand new lethal rounds.

**Comment by Finalsong** [comment]
While some people might think I wouldn't want this, because Blueshield is one of two jobs I play, I actually don't mind this being added. However, I think due to cargo access being removed, that the Blueshield should just spawn with extra ammo. The detective does, and they're not really supposed to use the revolver all too much. Only makes sense that the Blueshield gets some to. Other than that, I'm fine with this.

**Comment by Necaladun** [comment]
Considering the blueshield isn't meant to guard the QM, removing cargo access is fantastic.

**Comment by SamCroswell** [comment]
As of the current build I'm fairly certain the Blueshield starts with an advanced tazer. I'll verify this when I get home.

**Comment by Spacemanspark** [comment]
Ya, but people like the revolver more for some bizarre reason. Not sure why, it should be removed from them, imo.

**Comment by SamCroswell** [comment]
I'd rather them start with an egun, personally. The revolver fits the detective due to the noir theme, but it makes no sense for the Blueshield to have because it allows definite lethal and nonlethal options. As opposed to the revolver which has always sat in the grey area of more than nonlethal but less than lethal.

**Comment by Markolie** [comment]
Yes, I'm very much in favour of the Blueshield getting an egun. Preferably a unique one like the HoS's (with comparable stats, perhaps?).

**Comment by sasanek12** [comment]
when we are speaking about radio access. HoP shouldn't hear security radio too then

**Comment by Finalsong** [comment]
Without muh cargo access, I think an e-gun sounds like a good idea. Even if ballistics are better.

**Pull request merged**
