### PR TITLE
More book sprites

### PR DESCRIPTION
**Pull request by TheBeoni**
More book sprites for library Checkout console and bookbinder. Enjoy
zenavlak

### CODE REVIEW

**Comment by Draconic-saint** [comment]
muh booksprites

**Comment by TheBeoni** [comment]
@Draconic-saint you ended the Xenoarch project so i thought why not use these for something

**Comment by Draconic-saint** [comment]
I know, fair note that I might end up using these anyway...

**Comment by TheBeoni** [comment]
@Draconic-saint god damn it jedr ill make you a new ones.

**Comment by TheBeoni** [comment]
Does anyone has any points to make or argue anything about this since 24 hours have passed it could be merged when the maintainers will have time :)

**Comment by taukausanake** [comment]
Make a yellow book with an orange buckle and a rainbow book

**Pull request merged**
