### PR TITLE
Makes robotics red.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## What Does This PR Do
Turns all the purple tiles in robotics into red ones.

This also resprites whitered tiles to better fit robotics - they were barely used anyways so I don't believe it's an issue.

## Why It's Good For The Game
After PRs #21212, #22178 and #22425, robotics now have unique colors. Either black+red, or white+red, instead of old white+purple.
This PR changes that for their workplace.

## Images of changes
Cyberiad:
obraz

Kerberos:
obraz

obraz

Cerebron:
obraz

Farragus:
obraz

Mining Outpost:
obraz

## Testing
I took the screenshots above.

## Changelog
:cl:
tweak: Robotics floors are now red.
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
While it makes it look a bit secy, I kinda like it, though why not spruce up delta and meta a tad more? There's lots of empty tiles that could be painted

**Comment by ATP-Engineer** [comment]
probably would be cool if there was reddish/orange floor tiles for robotics.

**Comment by Sadhorizon** [comment]
> probably would be cool if there was reddish/orange floor tiles for robotics.

As I mentioned in discord, I'd rather not add brand new floor tile type.
I resprited whitered, as they basically weren't used as is, but that's about it.

**Comment by Sadhorizon** [comment]
May be finished, may be not, I honestly don't feel like deconflicting this if something happens.

**Pull request closed without merging**
