### PR TITLE
New Medical Directive - Colored Pillbottles!

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
This PR consists of two parts regarding pillbottles:

1) Pillbottles are now colored according to their intended medical use. For example, anti-toxin medication like charcoal will end up in green colored pillbottle and so forth. This is howerer rather minimal, as there are not that many pre-filled pillbottles, and even the few we have are rather rare. This is mostly ported from Baystation12, example of some colored pillbottles below:

ColoredPillBottles

2) ChemMaster3000 now has an option to re-wrap inserted pillbottle to change their wrapper, which you can use to give them desired color. As a chemist, you can for example use this to recolor pillbottle full of salbutamol to a blue color, to signify what it contains and distinct it from other pillbottles. Also contains minor facelift of the interface.

ChangeWrapper

Also adds generic description to patch packs, as they lacked one and inherited the default one from normal pillbottles - "It's a container for storing medical patches."

Tested locally without any issue.

**Changelog:**
:cl: Arkatos
imageadd: Added colored pillbottles
add: Added an option to change color of the pillbottles to ChemMaster3000
add: Added new description to patch packs
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
it bothers me that the pink is not centered in the screenshot like the other ones

**Comment by Mitchs98** [comment]
God now I can't stop noticing the offcenter pink. I didn't see it at first but now I can't unsee it.

**Comment by taukausanake** [comment]
How about instead of magic color changing pill bottles you use a crayon to change the color? Also, please rainbow pill bottle

**Comment by Ralta** [comment]
It'd be really neat to be able to change these without having to use the ChemMaster; I usually label my pill bottles, but having them a certain colour would make things much easier.

Either way, it's +1 from me.

**Comment by Dinarzad** [comment]
Behold, the truest form of powergaming there is.

Organized inventory!
*Insert thunder crack*

**Pull request merged**
