### PR TITLE
Species with oldcrit no longer go unconcious at 0 HP

### PR DESCRIPTION
**Pull request by BiancaWilkson**
## What Does This PR Do

This PR adds an in-between phase for species that use oldcrit, where from 0 to -50 HP, they'll be in a forced knockdown state instead of immediately going unconscious. This affects IPCs, Abductors, Golems, Skeletons, and Shadows.
## Why It's Good For The Game

Oldcrit has not been touched since crawling was added, and I feel like it is a worthwhile change. The game is much more forgiving than it used to be, so I think this change lines up with these new game design decisions.

The major pushback that I can see is that that this is a major buff to IPCs and abductors. Abductors are currently getting nerfed, but they're still in a very strong position. IPCs are already quite weak, and they cannot repair themselves without nanopaste if they are floored. 

With these numbers, it would take a maximum of 102 seconds to go from 0 to -51, given that

## Testing

Attacked myself and others into crit as IPCs, skeletons, and abductor. Also made sure I didn't somehow break normal crit too.
## Changelog
:cl:
tweak: Species that previously died at 0 HP now get knocked down until -51 HP, then they go unconscious.
/:cl:

### CODE REVIEW

**Comment by TravisAngeI** [comment]
In the forced knockdown state are they able to use/pick up items or are they just gonna be crawling away?

**Comment by BiancaWilkson** [comment]
It works the same as a standard knockdown, so you can't use items with a timer bar. Otherwise they can though.

**Comment by Inferno1882** [comment]
> In the forced knockdown state are they able to use/pick up items or are they just gonna be crawling away?

I believe the logic would be anything you can do while laying down, which means things with a do_after (like welding yourself) wont be possible. So, effectively, like everyone else. Except a tiny bit worse.

could be wrong.

**Comment by TravisAngeI** [comment]
> The major pushback that I can see is that that this is a major buff to IPCs

I'm just sayin, you can still kill them super easy they just get like 3 more seconds to crawl away or shout for help

**Review by S34NW — APPROVED** [review]

**Pull request merged**
