### PR TITLE
Port and update delta station shuttle to cyberiad

### PR DESCRIPTION
**Pull request by datlo**
Since free's engineering remap doesnt seem to be happening in the near future, I'm reviving this PR.

This ports the larger escape shuttle from the delta map to the cyberiad, with updates.

Fixed since last PR : The new shuttle can now be properly loaded and unloaded with the shuttle manipulator. The current escape shuttle is saved in templates and can be loaded in by admins.

New stuff in this shuttle : 

- More space, more chairs
- Antags who sit in the cockpit windows are no longer near innaccessible. All windows can be reached and deconstructed by jumping over tables.
- New space-side entry, see below for details.
- No more wall lockers. Extremely annoying for antags/secs to deal with people hiding in those.
- Some extra emergency/medical/oxygen supplies.
- A mech charger that actually works.

Screenshots :

Overview of the shuttle :

image

Shuttle cockpit : 

image

Blueshield going for the hijack syndi (outdated bridge consoles): 

shuttlehijack

Brig : 

image

Cockpit foyer. Both command and security have access to the foyer. Comes with a chair for the Blueshield/security officer on guard to strap in.

Shuttlecockpitlobby

The one room that is entirely new : The emergency external airlock. The external airlocks are public access and can be entered by any crewmember, however the internal white doors are security/command only and are see-through glass, meaning it will be difficult for antags to sneak in without being noticed that way. This also provides an alternative entrance to hijack antags who dont mind going loud to emag the shuttle away. The external airlocks (and only those) have atmos blocking tiny fans so the pressure doesnt get fucked whenever someone enters or exits the shuttle using them.

shuttleemergency

Cargo. Contains crates with emergency/engineering/med supplies. Mech and cyborg rechargers are upgraded.

shuttlecargo

Medical 

shuttlemed

Public seating area

shuttleplebs

:cl:
add: Added a new emergency shuttle based off Delta station map, updated for the cyberiad.
tweak: The old emergency shuttle can still be loaded by admins using the shuttle manipulator.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Is this the same shuttle cloned across all the maps? If so this makes my life during map standardisation even easier.

**Comment by datlo** [comment]
Unfortunately not, although this shuttle should fit the escape docks of both delta and metastation if you use it for them re-oriented. I havent touched delta/meta in this PR.

**Comment by FreeStylaLT** [comment]
💓

**Comment by SteelSlayer** [comment]
This shuttle is so much nicer. I've always wanted this.

**Comment by Mitchs98** [comment]
Everything else looks nice, not a fan of the wall lockers being removed though.

**Comment by Carthusia** [comment]
I like this alot, and while I will miss hiding in the lockers I can get why their not in its design.

**Comment by MRgaty** [comment]
Onlu problem I see is that you cant really hide in that shuttle, which is necessary when for example a hijacker tries To kill everyone or there are terrors aboard...

**Comment by datlo** [comment]
This is intentional design. The shuttle has more space so you can actually fight/evade the antags, for example by going through the interconnected cargo/medical.

Also there are potted plants you can hide behind and pray. Honk.

**Comment by Tokorizo** [comment]
My current complaint with our current shuttle is its too small, too crowded. Now this problem isn't going to be 100% fixed with this PR, BUT it will improve it, and improvements over time are always welcomed, support and love it.

**Comment by taukausanake** [comment]
> not a fan of the wall lockers being removed

I agree with that, but only if you can make it so wall lockers can't house a human. I always saw them as small little holes in the wall with covers. Cabinets if you will. Nothing that should fit a body

**Comment by Carthusia** [comment]
> > not a fan of the wall lockers being removed
> 
> I agree with that, but only if you can make it so wall lockers can't house a human. I always saw them as small little holes in the wall with covers. Cabinets if you will. Nothing that should fit a body

Vox would probably fit.

Though i get the need for their removal from the shuttle, as their purpose is seemingly just to hide.

If you took away that ability from all those lockers and put them on the shuttle anyways, their kind of pointless as the locker just houses a couple tanks, masks and crowbars which on the station is usefull, but on the shuttle its kind of moot considering how your only there at round end.

**Comment by datlo** [comment]
I will update this with some of the changes you suggested,  however this can be merged as-is and I can just open a new PR to update the shuttle later down the line.

**Comment by datlo** [comment]
Tested/reviewd the changes suggested.

1. Adding cameras would let the AI see into z2 which I'm not comfortable with, even if its only the escape shuttle. Would prolly need some extra code to ensure AI cant see into z2 cameras.

2. I dont think that we should establish a standard that the AI is to be taken with you to the escape shuttle, AI usually stay on station and, well, are meant to. They arent crew, their shift isnt over. The empty AI looks pretty out of place on the bridge. AIs that wants to be taken can be carded as it currently is.

3. I will add a couple chairs to brig, removing the reinforced tables. Actually expanding it would mess with the shuttle overall look, not a fan.

4. I'm leaving cargo as-is, I feel like a bar/other social stuff is a better fit for alternative shuttles and not for the standard one that will be used most shifts. I'll upgrade the rechargers, both borg and mech.

5. Tried using colored comfy chairs but it doesnt look great in my opinion... the shuttle chairs are just a better fit for a shuttle. I'll see if I can find a layout that better fits, but leaving as-is for the moment.

**Comment by datlo** [comment]
Tested the shuttle again after changes and works fine, this should be ready for merge.

**Comment by Carthusia** [comment]
Two things, not sure if its to late to give this imput but:

https://i.gyazo.com/c804a2cc4cd603ab050c217012d378ff.png

My OCD is driving me nuts with the upper right screen being misaligned and lacking its fire extinguisher.

and is it possible to add a defib into the medical room?

**Comment by Crazylemon64** [comment]
Let's see - is the cyberiad map edit mapmerged? The line count looks a bit on the big side

**Comment by datlo** [comment]
This is mapmerged, the shuttle is just completely different so the line count is high. I'll doublecheck to be sure.

I dont think the shuttle medbay needs a defib, you can bring one over from medical if you wish to. 
I'll see if I can placate your OCD :eyes:

**Comment by datlo** [comment]
Fixed merge conflicts and changed the display/added extinguisher for muh symmetry

image

I consider this complete and ready to merge, any further work other than fixing merge conflicts will likely be for a future PR

**Comment by Carthusia** [comment]
Muh symmetry! Balance is restored!

**Comment by Fox-McCloud** [comment]
I have one request; please add in a few wall O2 closets along right wall (where the main passengers are); it's kinda a fun little quirk for old time's sake.

**Comment by AffectedArc07** [comment]
Also three quick questions which I have some concerns over. Docking ports are finnicky bastards, does the shuttle still fully function moving from CC, to the space transit area, and then to the station, then from the station, to the transit area, then to either CC or syndiebase?

Two, how close does this shuttle come to the egde of the zlevel when docked? Z-level barriers are within 7 tiles and I fear this shuttle may be a bit wide and come very close (or even overlap) the transition border

Three, has the shuttle transit hyperspace on Z2 been expanded so no matter where you are on the shuttle you dont see static space? Or was it big enough already.

**Comment by datlo** [comment]
1. I've tested shuttle docking at station, CC, and syndi area and found no issues.

2. Not all that close, escape is pretty far from the actual zlevel border, shouldnt be an issue on cyberiad

3. I dont recall expanding the transit area but saw no issues using the currently existing one.

When/if I get around to updating this, I will test everything again to make sure it works properly.

AA talked about taking over this PR as its useful for his map standardisation and I'm currently busy, and I'm okay with it, just make your own PR and feel free to use any of the code/commits here. If you do, I recommend you test this all works properly.

**Comment by datlo** [comment]
Closing this PR as affected arc is taking this over.

**Pull request closed without merging**
