### PR TITLE
Adds a new Gateway (Away) Mission.

### PR DESCRIPTION
**Pull request by AffectedArc07**
First of all. I am sorry about all the commits everywhere, I uploaded in the wrong place. Now for the actual PR.

This is a gateway set on a Syndicate Mothership.
Its along the wild west level of difficulty, but has great rewards.
Basic map is this:
image

Left side:
left side

Right Side:
right side

Far Right:
far right

I made this because I didnt have anything else to do, Wanted to try make a map, Thought of this idea, Then made this.

:cl: AffectedArc07
rscadd: New gateway mission "Syndicate Mothership" added.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Might make sense to turn the mechs into actual mechs-- but have them be DNA-locked and have a string of random DNA stored.

**Comment by AffectedArc07** [comment]
> Might make sense to turn the mechs into actual mechs-- but have them be DNA-locked and have a string of random DNA stored so they can only be destroyed, never used.

I might do that, Although that would mean more commits and stuff like that. I already made enough. Nice idea though.

**Comment by alexkar598** [comment]
But if by luck the random DNA is one of a player

**Comment by TravellingMerchant** [comment]
I am still going to say that I think the emag should be removed, but the rest is pretty good. Maybe add some decoration, like contraband posters, monitors, so on.

**Comment by sothangel** [comment]
Why does there need to be so much powerful loot? I don't really care much for gateways in general and never use them; but I can't help but feel this has far too much loot on offer.

**Comment by ZomgPonies** [comment]
I'd like to see a maybe 1% chance per mech of NOT being DNA locked.

**Comment by AffectedArc07** [comment]
I might replace the emag with a broken emag. @TravellingMerchant

**Comment by DarkPyrolord** [comment]
I like the general design idea of it, and the actual challenges it offers, but I feel like the armoury room might be a bit much as I can see people cheesing that for loot with chem grenades and such, not actually using them on the mission then bringing them back onto the station for their own personal gains or to carry around for self-defence, maybe I'm just being nitpicky, overall I like it, since it isn't a free loot pinata like most other away missions were before Kyet's set of PRs.

**Comment by SamHPurp** [comment]
Like having new missions, but that is a /lot/ of ridiculously good loot...

Remember that the e-sword was even removed from Wild West...

**Comment by sothangel** [comment]
Would I be correct in thinking that one could simply make grenades in the chemistry room to kill the mobs near-on instantly?

**Comment by SamHPurp** [comment]
@sothangel or just release a plasma cannister, light it... and wait...

Theres loads of ways to simply do this mission, and for far too good loot.

**Comment by AffectedArc07** [comment]
I am tempted to make all the guns have no ammo, and the turrets exist so if you do chemkill the commandos, you cant get in. Turret is delibratley placed on that tile so you cant cheese it with a computer frame

**Comment by AffectedArc07** [comment]
After testing this a few things are being removed:
- The bee room is a log and chat spam, as well as an instakill.
- The access adding machine does not work
- The armory will be inaccessable

**Comment by AffectedArc07** [comment]
Changes:
- ID Access now works
- Doors removed on terror spiders and syndi bees
- Armory can now be opened, Does not have an ARG or pinpointer, you need to kill about 9 commandos to get in.
- Windows now have floor underneath them

The map has been tested with a few people and found to be very difficult.

**Comment by jughu** [comment]
>make new gateway mission map
>litteraly gives the whole mission awau

**Comment by AffectedArc07** [comment]
For some reason, all objects duplicated and I cant open the map in DM. Going to try FastDMM to see if that works but for now do not merge this.

**Comment by bigfatbananacyclops** [comment]
I think this is okay but you should remove alot of loot, this is WAYY alot of loot, and there isnt this many enemies from what i can see, you dont have to enter the spider room if you know, all you gotta do is straight go for the super guns and win win, i think you should remove the emag and sword, and atleast other guns, its way too much, if you want people to get the loot, they have to go through a journey, like put that the explorers have to go through the test labs of terror spiders in order to get to the bridge and armory, but i mean, we already have a syndicate base, i'd like to see a more horror gateway, or a hostile clown base, or pirate base. With horror gateway, i mean like probably a damn maze filled with hostile angels

**Comment by bigfatbananacyclops** [comment]
If there is gonna be ALOT of powerful loot, atleast put more enemies, because this haves to be a hardcore gateway

**Comment by AffectedArc07** [comment]
There are 52 syndicates just in the corridors of this map.

**Comment by AffectedArc07** [comment]
This PR is going to be abandoned and a new one made with fewer commits, and just generally better formatting.

**Comment by Necaladun** [comment]
I'd test this as lings/cult/vampires/slings etc, as a few things in here could get cheesed pretty easily. Don't worry about wizards, but you want to make sure you can't just mistform through it all, etc. Changling regen can also whittle through mobs, especially as a team - and changlings have hivemind, ofc.

**Pull request closed without merging**
