### PR TITLE
Suspicious Crate Sprite (for surplus crate)

### PR DESCRIPTION
**Pull request by ShinaHoonkins**
- Added a sprite for the syndicate surplus crate.

I kept close to the style of the suspicious toolbox/dufflebag.

First contribution here, so feel free to point out errors.

edit:
- Added images of the sprite.
- Added changelog.
- Added icon-names in .dmi-file.

further edit:

- Added coding

Thanks to the pointers in the comments! You helped a lot!

Also many thanks to Fox for the massive help with the coding and with explaining Github to me. Whether this change gets made or not, I learned a lot - so I consider this a good experience either way.

SuspiciousCrate

:cl: ShinaHoonkins
add: Surplus crates now get a unique, suspicious look!
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
inb4 'stealth' argument

**Comment by Citinited** [comment]
You need to give your icon an appropriate name in the .dmi file

Not sure I'm for this given it's not meant to be obvious that someone bought a suspicious supply crate (otherwise the crate would be named as such). That sprite is pretty nice, though

**Comment by Spartan6** [comment]
Couple things.
You’ll need to provide an image in the opening post of any sprites.
You’ll also need to add a changelog.

**Comment by Citinited** [comment]
Oh also, your 🆑 is misleading as it doesn't actually change the in-game look. I'd remove it unless you update the in-game sprite to show your new icon.

**Comment by Spartan6** [comment]
@Citinited They’re getting to it, this is their first PR, they’re getting their footing part by part.

**Comment by Citinited** [comment]
@Spartan6 Indeed, I'm just providing feedback for them to take in and do whatever with it 😄

**Comment by Crazylemon64** [comment]
Not sure how I feel about a syndicate crate leaving a conspicuous fingerprint that can't be either concealed on your person or easily disposed of, instead of a standard crate that looks like any other crate one would find scattered across the statoin

**Comment by Citinited** [comment]
Suspicious crate decals when? 😄

**Comment by ShinaHoonkins** [comment]
I can quite understand the stealth concerns, especially due to the fingerprints and the surplus crate being very expensive and risky without the added danger.

The sprite could maybe also go well with the null crates you can order via cargo? Those are rather easy to get and are an addition to your TP. The risk lies more with the console and papers than with the crate itself - you should send the shuttle back quickly anyway after ordering those.

**Comment by bigfatbananacyclops** [comment]
already people can meta by seeing a ''extra crate'' in a room where its not supposed to be. also the crate is supposed to be sent stealth, that crate just gives away the traitors, a valid reason to go red.

**Comment by taukausanake** [comment]
Maybe if you have one of these crates added to the maint loot but only have some minor things in it, could be considered a false positive

**Comment by tigercat2000** [comment]
Hey there, sorry for the long waiting period. Thank you for your sprite contribution,
However, we have decided to decline this PR. This is primarily due to the concerns about making the crate a significantly less stealthy option for traitors to use.
We don't currently believe this would be a positive addition to the null crates in cargo, either.

**Pull request closed without merging**
