### PR TITLE
Rock walls become 3/4ths

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Ports the rock base texture from TGMC, slaps a colour on it to make it look nice.

Adjusts some of the wall files to remove old rock-related crap, and tweaks the icon behaviour for rock to cut down on sprites.

## Why It's Good For The Game
Let's be honest, we became blind to how bad our current rock texture is. It's flat, noisy, and not really obvious what it is. This new texture is clearly a wall,

## Images of changes
image

Comparison:
image

image

Comparison:
image

image

## Testing
Look at the rocks above I looked at

## Changelog
:cl:
tweak: Rock walls are now 3/4ths
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Colour for this wall is handled by the `color` var, so can be changed with a single code edit.

**Comment by OctusGit** [comment]
Now do station walls next

**Comment by S34NW** [comment]
> Now do station walls next

One step at a time

**Comment by Denthamos** [comment]
Provide a picture please of the new 3/4ths rocks touching our current walls in situations like the space bunker ruin and other such spots where they touch on planetside with other ruins.

**Comment by matttheficus** [comment]
Could the comparison pictures also include wearing Mesons?

**Comment by S34NW** [comment]
> Provide some pictures please of the new 3/4ths rocks touching our current walls in situations like the space bunker ruin and other such spots where they touch on planetside with other ruins.

It currently does not smooth with them, although this can be changed with a simple tweak to one line
image

**Comment by warriorstar-orion** [comment]
This looks really fucking good, and it's great there's so many unused icons being removed. Could you show a screenshot of how the high/low ore probability/labor color overlays look like in SDMM?

**Comment by S34NW** [comment]
> This looks really fucking good, and it's great there's so many unused icons being removed. Could you show a screenshot of how the high/low ore probability/labor color overlays look like in SDMM?

It's the same rock icon, but coloured in the same scheme as the old icon states were.

I'm not at my computer so hope this helps in the meantime

**Comment by S34NW** [comment]
> This looks really fucking good, and it's great there's so many unused icons being removed. Could you show a screenshot of how the high/low ore probability/labor color overlays look like in SDMM?

image

**Review by Edan52 — APPROVED** [review]
rock solid

**Pull request merged**
