### PR TITLE
Changes every single item's tech level's location in code

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Moves all origin_tech levels from every item into a separate, single .dm file for far _far_ easier readability, testability and customization/balance of levels.

**No actual levels were changed, only their location**

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Oh my goodness
my condolences 💐

**Comment by fludd12** [comment]
The only complaint I have is that now there won't be a very easy way to adminbus something with radical techlevels.

Chrissake, the work you had to put into this, though, it's a worthwhile loss.

**Comment by Asmerath** [comment]
I was about to come on heare and no the fuck outa this idea just because of the title. but now that I read it its not a big change. If it helps in the future with coding, then go for it.

**Comment by Crazylemon64** [comment]
@fludd12 Adminbus will work just fine - vars are still declared, even if in a different file.

**Comment by TullyBurnalot** [comment]
The clickbait is real.

**Comment by fludd12** [comment]
Oh, I see.

I'm a dumb.

**Comment by Fox-McCloud** [comment]
item properties should be defined in the item itself. Duplicate item definitions should be avoided, when necessary and generally kept as close to the item definition as possible.

:-1: 

This is unnecessary and something that's being done for personal reasons.

**Comment by Alex6511** [comment]
Please use proper titles for your PR's, it makes it difficult to find the PR later if we have to lookup information.

**Comment by LittleBigKid2000** [comment]
But muh clickbait Alex

**Comment by tigercat2000** [comment]
@Fox-McCloud On a completely opposite side:
 This would make the research module _much_ more portable, less ingrained and shoved everywhere in the code.

**Comment by Kyep** [comment]
Normally, I would agree that the properties of an item should be defined on the item itself.

There are some exceptions, though. With Events, for example, its considered so important to be able to compare them all in one place, that event probabilities are all defined in https://github.com/ParadiseSS13/Paradise/blob/ecd12bee630c24d0a272c5ca5ea5176aea1d894f/code/modules/events/event_container.dm
Events only have a few dozen items. R&D has *over 160 files* containing items, and I don't even want to know how many items.

If Events deserves its own file, so all events can be compared in one place, then R&D tech levels deserves its own file, where all R&D item tech levels can be compared in one place.

**Comment by tigercat2000** [comment]
@Kyep That's very different, the event controller creates events via that

**Comment by Crazylemon64** [comment]
I agree, making R&D changes require modifications to only a single file seems like a sound idea indeed

**Comment by Kyep** [comment]
@tigercat2000 
The event controller could have created events via some other method. I'm sure there is a way for that information to be defined on the event datums themselves, rather than being in a centralized list.
IMHO, it looks like someone did the event controller the way they did because they wanted there to be a centralized list of all events you could easily compare against each other. If that sort of reasoning is valid, then its probably even more valid for R&D items than it is for Events. If that sort of reasoning is not valid, then why has nobody changed the event controller?

**Comment by monster860** [comment]
You know what we need?

Code symlinks.

**Comment by Krausus** [comment]
On the one hand, the amount of effort that probably went into this is commendable.

On the other hand, you've separated one of the properties of all these items from the item definitions they belong in. This is handy in the very specific scenario where you're working with the research levels of a bunch of items, but it's a nightmare if you just want to see what the properties of a single item are.

Imagine if you had to open one file to see an item's name, another file for the tech levels, another to see its force, another to see its weight class, and so on, and you had to search for the item's type in each of these files, and you had to do that for every item you wanted to look up the properties for. Sounds pretty awful, right?

> far *far* easier readability, testability and customization/balance of levels.

Readability and testability are easy; you can simply write a proc that verifies and outputs the tech levels of every item that exists. Conveniently changing them is a different story, of course, since more sophisticated scripting would be necessary to extract and then update the tech levels in the code files, but it's feasible.

**Comment by FreeStylaLT** [comment]
There has to be a better way to do this without re-defining every item. I hope. I'll also spare the Maintainers from sounding cruel as they invalidate my all nighter of copypasting.

I'm keeping the list, though. :eyes:

**Pull request closed without merging**
