### PR TITLE
Nanomed Plus: Half the amount, double the contents

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

The amount of Nanomed Plus vendors inside of medbay has been cut in half (box/delta: 6 -> 3, meta: 5 -> 3).
Nanomed Plus: Amount of contents has been multiplied by 2.
Moved the wall vendor out of the medical vending crate to its own crate (50 credits)
Increased the cost of the NanoMed Plus crate (100 -> 150 credits) and medical supplies crate (400 -> 450 credits).
## Why It's Good For The Game

This PR aims to help with the following issues:
1. Doctors having to check six vendors to find the one where the item they want to acquire has not yet run out.
2. Some vendors are mostly ignored because of their bad placement inside medbay.

With fewer vendors to oversee, it should be easier to manage those resources and know when to acquire more restocks.
The medical restock crate cost has been increased to reflect the increase in content that one nanomed plus vendor has received.
## Testing

- Compiled and verified the mapping changes
## Changelog
:cl:
tweak: The amount of Nanomed Plus vendors inside of medbay has been cut in half
tweak: Nanomed Plus: Amount of contents has been multiplied by 2
tweak: Split up the medical vending crate contents into two new crates
tweak: Increased the cost of the NanoMed Plus crate (100 -> 200 credits) and medical supplies crate (400 -> 450 credits)
/:cl:

### CODE REVIEW

**Comment by Sadhorizon** [comment]
As a person who put a lot of hours into medical, I can see one, major problem with this change. That being, every vendor _will_ be dogpiled like crazy. Be it roundstart or mid round, it's gonna be harder to use them.

> Some vendors are mostly ignored because of their bad placement inside medbay.
This is very much not true. Faraway vendors are used at roundstart, specifically **not** to drain vendors near healing area. Brighter doctors usually do, in fact, use them, so they don't have to run a marathon to resupply later on.
Their "weird" placement also gives easier access to them to jobs that are not an MD, best example of it being virologist (on cyberiad at least)

And last but not least, it's definitely easier to steal from a vendor if there is more of them. Is it positive? Is it not? Up to personal judgement, but it definitely is a valid point to bring up.

**Comment by Henri215** [comment]
> As a person who put a lot of hours into medical, I can see one, major problem with this change. That being, every vendor _will_ be dogpiled like crazy. Be it roundstart or mid round, it's gonna be harder to use them.
> 
I could see this problem happening with one vendor, not three.
> > Some vendors are mostly ignored because of their bad placement inside medbay.
> 
> This is very much not true. Faraway vendors are used at roundstart, specifically **not** to drain vendors near healing area. Brighter doctors usually do, in fact, use them, so they don't have to run a marathon to resupply later on. Their "weird" placement also gives easier access to them to jobs that are not an MD, best example of it being virologist (on cyberiad at least)
> 
Vendors are not the medical storage, all their contents should be consumed and resupplied when the time calls for it. With fewer vendors i expect that medbay takes more care of them, making sure they are well supplied/not broken instead of using it as some sort of medicine sink.
This is by no means a marathon, its located inside in the same department and doctors do have plenty of storage options to carry most of the medical supplies that they need.
> And last but not least, it's definitely easier to steal from a vendor if there is more of them. Is it positive? Is it not? Up to personal judgement, but it definitely is a valid point to bring up.

That is a corcern i have too and the reason why i chose to keep the most "public" vendors.

**Comment by Miraviel** [comment]
Pretty much echoing everything here:

> As a person who put a lot of hours into medical, I can see one, major problem with this change. That being, every vendor _will_ be dogpiled like crazy. Be it roundstart or mid round, it's gonna be harder to use them

>> I could see this problem happening with one vendor, not three.

It is a real issue on highpop. Highpop medbay with only 3 vending machines is going to be painful.

Another issue is that people tend to over-vend resources when there is a lot of them. For example, sensible players might leave 1 hypospray in the machine if there are 2, but if there are 6 hyposprays, then they'll go "oh, there are so many, I could just start using 2". We already have people hogging resources, this'd reinforce this behaviour.

This will be also problematic on nukie rounds, when, after everyone gets AA, they swarm medical for healing stuff.

...

As for the medical vending crate, if you wish to increase its cost, I'd suggest splitting its contents. Currently, it comes with a NanoMed Plus and a wall NanoMed refiller, and honestly, most of the time the wallmed refiller is just trashed, because nobody knows how useful gauze is (and nobody uses wall nanomeds in medbay, why would they, when they have the big box).

If your intention is to manage vending machine resources more precisely, then I'd still recommend trying to code in population-scaling contents (I think we discussed this in another PR). This PR shows that a solution that works for lowpop does not work for highpop; pop-scaling contents might do. CM has such a feature, but it probably needs a rewrite over porting.

If the idea is to ensure medical is always stocked, that should be the CMO's responsibility. If the CMO is too busy to do so, they should appoint someone to keep an eye on it. At the end of the day, NanoMed Pluses are just a roundstart tool to kick off medbay, ultimately, it's chemistry's job to keep doctors supplied.

**Comment by Carthusia** [comment]
Overall, im not for this.

The nanomeds had their resources halved per vendor, which is what caused this problem to begin with.

To me: The nanomeds just need their resources put back to what it used to be, and bam, problem solved

**Comment by Henri215** [comment]
> Overall, im not for this.
> 
> The nanomeds had their resources halved per vendor, which is what caused this problem to begin with.
> 
> To me: The nanomeds just need their resources put back to what it used to be, and bam, problem solved

Having only the most convenient placed vendors being used is something that did happen before, why keep the distant/not convenient ones?
Round after round, even during chaotic highpop ones, the same vendors are always mostly intact while the ones inside the treatment areas are empty, i want the crew to easily utilize all the resources they have available without being tricked by the red colors at the most popular vendors.

**Comment by SpringSkipper** [comment]
I think this change is fine, as long as at least one vendor is at least a bit out of the way where tiders can't easily get to it.

**Comment by hal9000PR** [comment]
4 design team objections. filing as closed

**Pull request closed without merging**
