### PR TITLE
Add access restriction removal to keycard auth device

### PR DESCRIPTION
**Pull request by datlo**
This PR adds two new functionalities to the keycard authentification device : Disable and enable access requirements on station airlocks.

While this feature is meant to be used during war ops, it can be used during any emergency that causes airlock ID restrictions to be more harm than help.

After two heads swipe for it, all airlocks on station will have their emergency access setting turned on, so anyone can go through.

Reenabling requirements disable all emergency access settings.

image
image

The benefits of this is : 

1. Reduce tedious workload on the HOP who's told to give all access during war ops, and allow crew more time to prepare instead of waiting in line
2. By setting emergency access instead of granting all access, vital station machinery such as the cargo console, RND, the ORM, medical vendors, and brig cell doors remain functional and ID locked. This allow each department to do their actual job without everyone meddling. If cargo's being shit and not ordering any guns, the HOP (who's conveniently not busy giving out all access anymore) can give access to cargo as needed.
3. Each member of command (and the QM) can decide to override this for their own department by using their door remote and unset emergency access on the relevant airlocks.
4. This avoids confusion when the HOP sets multiple people as "Captain" without using a custom job title and keeps the chain of command clear.

This has balance implications when it comes to war ops, as the HOP and crew won't have to be waiting in line anymore, granting them extra time to prepare. On the other hand, this setting also allow nukies to pass any unbolted airlock without emagging/hacking.

Perhaps war ops should be allowed to arrive sooner if this feature is added? I'm not sure, and this PR does not change the arrival time as of now.
 
🆑
add: Added the ability for command to set emergency access on all station airlocks with the keycard authentification device. (ID swiper)
/🆑

### CODE REVIEW

**Comment by Birdtalon** [comment]
Pretty cool but I worry that adding just a single button to essentially give everyone all access is too "easy"? Although the nuke ops would also benefit from it.

I would personally augment the HoP console if I was to approach this concept to allow them to create cusotm jobs with bespoke access still meaning that the HoP is still the bottleneck.

Not 100% sure on whether I would 👍 or 👎 so settling with a 😕

**Comment by datlo** [comment]
This is ultimately a balance change to war ops, so I'll let the admins/maintainers discuss on whether or not a button to give all access to everyone is appropriate or not. It's not like this took hours to code, anyway.

**Comment by Kyep** [comment]
I would suggest calling the options 'Activate Station-Wide Emergency Access' or similar. So its clear that its station-wide, and that it sets airlocks to emergency access mode rather than strips access restrictions.

**Comment by datlo** [comment]
Yeah I was struggling to find something that was clear and sounded good, that's good wording, i'll go with that.

**Comment by KasparoVy** [comment]
RIP, now I can't tell what the roundtype is by counting the Captains.

**Pull request merged**
