### PR TITLE
Nerfs Space Lube

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Nerfs Space lube

@TheDZD and I were waiting for the other slip PR to be changed a bit, but it never happened, so we opted to make an independent PR.

- Damage Removed
- Duration reduced from 7 to 5

:cl: Fox McCloud
Tweak: Space lube damage removed and duration reduced from 7 to 5
/:cl:

### CODE REVIEW

**Comment by IcyV** [comment]
Doesn't feel like something that really needs to happen. Lube really isn't that dangerous in the first place with how obvious it is to see and predict. Most of the time you can just stop as someone sprays it and you'll be fine, assuming you aren't just hugging and chasing them from a tile away.

The duration also isn't really all that long in the first place. See when people have to actually cross a lubed floor for real. It takes quite a bit of effort and time just to get back up from falling, god forbid trying to staying up after that.

It also does virtually no damage anyway, why take it out? You just slipped hard on a slippery floor and slammed into a wall/ground. It'll sting just a tiny bit. This just makes lube essentially water that's the most miniscule amount different.

**Comment by Kyep** [comment]
All my yes.

**Comment by Sky-Ping** [comment]
All my yes, clumped in with Kyeps yes.  We plan and pray to make a giant yes ball.

**Comment by Ar3nn** [comment]
:+1: to damage removal
Indifferent to the time reduction. Lol-lubing the halls is literally the only time I see it used in-game, there is no not-griefy application, so it doesn't matter how long it slips for, it'll probably still be used for that.

**Comment by M3hillus** [comment]
Thumbs down, its now just glorified water at this point. 

Though, seeing as its getting a nerf, why not give it a legitimate use?

First thing that comes to mind is Ipc's and robotic limbs, maybe even borgs. Use a dropper on limb, heals for a teeny bit?

**Comment by Ar3nn** [comment]
There's already the ultra lube effect, could just weaken it some and add it to this /shrug

**Comment by theColdflame** [comment]
keep the damage, removing it means sec can't stop people with lube under space law

:+1: to reducing the stun though

**Comment by Necaladun** [comment]
The damage being even 1 is great for what coldflame said. 

Lube I've always seen as intended to be for pranks, not a powerful combat ability and area denial. I support nerfs for it.

**Comment by Belario** [comment]
This is a bit harsh :-1:  

Lube is rightly feared, if abuse is a problem a hard counter to it would be nice (space grit when?).
Stun is king and all but with these levels people may as well just use meth smoke.

**Comment by IcyV** [comment]
Personally I'd love to see a way to clear lube instead of just making it worse. Give people the ability to take a moment and clear a tile of lube so they can keep moving through. It'll take slightly longer than, say, swapping to walk and walking over water floors. It deals with the issue of people trying to lube off doorways and you only having the option of waiting.

**Comment by Belario** [comment]
Have lube be clearable with a rag/soap, or instantly with an application of space grit.

That'd be far preferable to further reducing the station's lethality.

**Comment by Davdichan** [comment]
Given that I've seen lube completely swing nuke ops rounds and cult rounds, can't say I'm infavor of making it complicated water. If this was accomponied with a nerf to all slipping items and chems, it'd be understandable, but plain water, clown pda and bananas are used far more for slipping, just feels like lube is being targetted because it has a reputation.

**Comment by theColdflame** [comment]
Lube is unconditional area denial, whilst other methods can be avoided (water) or not easily spread over an entire area (peels, clownPDA).

**Comment by Kevak** [comment]
Lube is not unconditional area denial. Floor tiles or a crowbar will get rid of it easy.

**Comment by Davdichan** [comment]
You can also mop space lube with a wet mop or spray space cleaner over the tile to get rid of it. It's about as unconditional area denial as a portable flasher.

**Comment by Lady-Luck** [comment]
@Davdichan You can't walk on lube, and the stun is twice as long as water.

**Comment by IcyV** [comment]
@Lady-Luck "and the stun is twice as long as water."

It's...not though.

**Comment by Lady-Luck** [comment]
@IcyV Water stun is 4, Lube stun is 7. Duration is roughly (x*2)-1 seconds, so you have 7 seconds for water and 13 seconds for lube.

Yes, that's one second below being 'twice as long', I was rounding.

**Comment by IcyV** [comment]
A second makes a pretty big difference. Even if off just a tiny bit, once lag comes into play you don't really want to just make blanket "twice as long."

**Comment by Lady-Luck** [comment]
Lube is almost twice as long a stun as water.

**Comment by TheDZD** [comment]
@theColdflame @Necaladun Sec can still arrest them over 207, Creating a Workplace Hazard. Slipping hazard is even mentioned on there explicitly. If it's an excessive amount of lube, you could probably justify it as Sabotage.

**Pull request merged**
