### PR TITLE
Fix airless plating map issue

### PR DESCRIPTION
**Pull request by Markolie**
Fixes https://github.com/ParadiseSS13/Paradise/issues/6318
The floors were regular plasteel floors with a different icon state.

Also removes a duplicate catwalk type entry, moves the airless plasteel floor to its proper file and fixes an incorrect floor type in a debug map.

Also removes the newscast from AI/request consoles which I forgot to disable in the announcement PR after removing the global variable.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Do you, like have a single branch that you reuse each time you make a fix PR

**Comment by Markolie** [comment]
I usually use the branch that I'm still active on if it's currently unused.

**Comment by taukausanake** [comment]
Yay, I called it before this PR came up. Too bad I can't go about fixing things right now

**Comment by Markolie** [comment]
Appended another fix to remove two remaining newscasts I forgot to remove in the announcement PR and the newscast fix that came after that.

**Pull request merged**
