### PR TITLE
Cyberiad: Gateway, EVA, MimeclownIAA!

### PR DESCRIPTION
**Pull request by tigercat2000**
Changed shit:
 - Gateway moved to arrivals
 - EVA expanded
 - Mime/clown office wrapped around corner, IAA office nudged over
  - This was probably unnecessary to be honest but whatever yell at me
    later

eva
gateway
alltheshit

### CODE REVIEW

**Comment by Spacemanspark** [comment]
I love the look.
:+1:

**Comment by Fox-McCloud** [comment]
Eww, no :-1: 

EVA is already huge for what little it has, it doesn't need to be a wide empty sprawling danceroom floor =p.

**Comment by Aurorablade** [comment]
I could accept it...only if you put a glass view to space from the IAA office...and/or a fishtank...

**Comment by tigercat2000** [comment]
@Fox-McCloud It actually doesn't feel that empty, in game. At least, not to me.
ingame

**Comment by Fox-McCloud** [comment]
@tigercat2000 

That makes it seem *even worse*.

**Comment by Alex6511** [comment]
Not a fan of this one.

**Comment by tigercat2000** [comment]
eh, oh well. I might try aurorablade's suggestion.

**Comment by Bad-Apple797** [comment]
EVA does look pretty empty, and what are the plans for the now empty chunk were IAA used to be?

**Comment by tigercat2000** [comment]
@Bad-apple797 Are you trying to imply I _thought this through_!?

I mostly wanted to make EVA bigger, because I was hoping it would look nice. I really shouldn't be a map developer.

**Comment by TheDZD** [comment]
Honestly, it looks like EVA just has far too much empty space.

**Comment by Spacemanspark** [comment]
I still like the gateway in arrivals.

**Comment by veganzombeh** [comment]
Not a fan of the gateway jutting out into space so much. Perhaps it look better on the other side of the escape pods?

**Comment by FalseIncarnate** [comment]
EVA is huge and the gateway just looks like tacked on. I'm guessing we can't put the gateway in that empty slot where the IAA office used to be at the corner of the security hall without cutting out pretty much all of it's staging area?

**Comment by Robertha89** [comment]
gateway looks fine, because NT is a shait company that would just tack a room onto the station in a horrible manner, but giving eva so much spess? no please. Don't even understand why they are behind secondary doors to begin with. also, random space in station is bad m'kay

**Comment by Plotron** [comment]
What the hell?!
EVA not only is too big, it's also harder to see into, meaning that it's going to be easier to rob.
That big empty chunk of space in place of old IAA is just atrocious - it adds nothing.
Gateway is too far, medevac will be harder (at least it positively reminds me of the old Arrivals we used to have).
I like that you tackled the mime/clown office 'issue', but that's really the only thing I dislike about our current map in this area.

I agree with Fox.

**Comment by KasparoVy** [comment]
I think EVA could lose a row of tiles in the middle to compress everything together, and at least 4 columns. I love what was done with the offices but I think something should be done about this extra space. Maybe an extra maintenance room?

**Comment by taukausanake** [comment]
I really don't like any of these changes to be honest. The Gateway just look ugly way over there. Too out of place. EVA has too much empty space now. Looks more like a bomb shelter. Maybe if the hall was smaller it could work but I rather it not be done. The Mime and Clown offices stick out too much to the security shuttle there. It should all be moved back to how it was. That empty hole does not need to be there for any reason at all

**Comment by Dumbdumn5** [comment]
Eh, I liked it. *shrug*

**Comment by Aurorablade** [comment]
yeah its not bad, i mean if the rigsuits got balanced and put in could make a spot for them behind a secure door or what not in eva

**Comment by orelbon** [comment]
Won't this make it easier to break into EVA via maintenance since you have more walls to work with?

**Comment by veganzombeh** [comment]
@orelbon Blue X's are blobspawns. They're the locations random events spawn blobs and some other antags at.

**Comment by orelbon** [comment]
@veganzombeh thanks

**Comment by Fox-McCloud** [comment]
@orelbon 

Because hardsuits are meant to be limited, not something everyone gets to run around with; there's already an overabundance of engineering hardsuits, at the moment.

**Comment by tigercat2000** [comment]
Not everyone shares my enjoyment of open rooms. Closing this so rigsuits are my only PR left to deal with.

**Comment by Aurorablade** [comment]
Awwwwww

**Pull request closed without merging**
