### PR TITLE
Removes Aurora Caelus (Green space) event

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Removes the aurora caelus event (The one that used to make space green). But why, you may ask.

Well
- It doesnt do anything ever since we implemented StonedMC lighting instead of PS Lighting
- It puts a tremendous strain on SSlighting even though it does nothing
- The soundfile is a full 5mb in our RSC (The largest sound file we have, and its only 2 minutes long!)

NOTE: If anyone comments "Improve, dont remove", then you will be asked yourself to improve this event, and I will gladly look at your suggestion if you make a tangible code change. However, if you throw "Improve, dont remove" around yourself with no intention of improving it, you will be ignored.

## Why It's Good For The Game
Smaller RSC means its easier for people to download, and were not wasting large amounts of CPU for no reason on a random event

## Changelog
:cl: AffectedArc07
del: Removed Aurora Caelus event (Green space lighting). It barely worked and the music bloated the game resource files.
/:cl:

### CODE REVIEW

**Comment by Cocacolagua** [comment]
improve don’t remove, event should crash the server

**Comment by FreeStylaLT** [comment]
Remove, don't improve.

**Comment by AffectedArc07** [comment]
For context, this has been broken since the 8th of May, **2019**.

**Comment by SteelSlayer** [comment]
Got a couple other things you can remove if you want that was a part of the original PR #8908

- `GLOBAL_LIST(station_level_space_turfs)` was added there, but now its completely unused.
- This text in `Attributions.txt` can be removed: "ambience/aurora_caelus.ogg is Music for Manatees by Kevin Macleod. It is under a CC-BY 3.0 license. It has been cropped and fades out."

**Comment by Varghh** [comment]
I'm going to miss this song, it was my favorite relaxing event

**Comment by Pennwick** [comment]
For those that just like the music its 'Music for Manatees' by Kevin MacLeod. 

I'll be sad to see it go. I haven't had the chance to actually verify it doesn't work since my character has usually been a borg or super busy but it was by far my favorite event.

**Comment by kenken244** [comment]
Am I allowed to say fix don't nix?

**Review by Kyep — APPROVED** [review]
When something is broken for over a year, nobody notices or cares, and its putting a CPU strain on our lighting system for no benefit.... then yeah, its probably time to axe it.

**Comment by shmabuu** [comment]
It’s nice to have the music and imagine cool star stuff when it’s say, extended. But when this happens during the middle of a cult summoning or spider infestation and lags the entire server for something that cannot ultimately be seen, why have it? Especially when it’s just gone under the radar for so long

**Comment by Aurorablade** [comment]
The entire reason is dosn't work from a lighting perpective is due to the DYNAMIC_LIGHTING_IFSTARLIGHT thats the config for starlight..if starlight is off..it dosen't work. now i can't tell you the light strain issue besides that on TG it uses SORTED areas rather then all but that shouldn't make a diffrence.

Now when i just ran test code with starlight on in the config it worked. IE on solars, windows to space..Etc Etc. not on space itself howerver as even with starlight on the dynamic lighting of a spacetile is a big fat 0. so i got it to work just not changing the color of space itself..just the colors of objects in space itself.

**Comment by taukausanake** [comment]
Why can't this just be ported over to the weather system like how Solar Flares are being done? They seem similar enough, besides the Aurora Caelus changing colors. Maybe a new weather overlay could be used in place to make the illusion of changing colors. It would just be a shame to lose this event

**Comment by AffectedArc07** [comment]
> i can't tell you the light strain issue besides that on TG it uses SORTED areas rather then all but that shouldn't make a diffrence.


This wouldn't do anything to SSlighting since that only handles updates of light sources, corners and objects, and has nothing to do with area sorting. That itself would have load on SSevents since it's the event doing the area stuff

> Now when i just ran test code with starlight on in the config it worked. IE on solars, windows to space..Etc Etc. not on space itself howerver as even with starlight on the dynamic lighting of a spacetile is a big fat 0. so i got it to work just not changing the color of space itself..just the colors of objects in space itself.

This is true, but when I have seen it on the live server all that happens is the solars change colour and **a small portion** of the external walls, but it's definitely a lot less pronounced than it used to be. Again though, it's not my single decision to make, other maints exist

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
