### PR TITLE
Podbay expansion

### PR DESCRIPTION
**Pull request by monster860**
image

So, I've expanded the escape podbay to be able to hold 5 spacepods. I had a shift recently where there was 2 spacepods crammed in there, and there was another 2 spacepods outside of there.

I did remember to shift the mass driver 2 tiles up. This involved shifting the bar maint and electrical maint as well. 

I also remembered to reconnect the cables and pipes after doing so. Also, to appease you I did mapmerge it so that it doesn't to the fastdmm stuff, Fox McCloud. However you may inspect my work here:

image

:cl: monster860
tweak: expands the escape shuttle podbay
tweak: moves some of bar maint and electrical maintenance, and the mass driver 2 tiles up
/:cl:

### CODE REVIEW

**Comment by Shadeykins** [comment]
There's presently an escape remap up, so this is kind of moot. Please reference #8870

**Comment by Plotron** [comment]
True.

**Comment by taukausanake** [comment]
I like this either way. You need more space for pods and parking spaces

**Comment by Plotron** [comment]
Now this will have to be re-done due to the remapped Escape/Chapel. I'm waiting for the new design!

**Comment by taukausanake** [comment]
My suggestion: put the pod bay back where it was (relative to the edit) and block out the windows in the security waiting area. If you need to you might have to switch the mass driver and the coffins around so the bay doesn't get in the way of funerals. Maybe after that you can add a row of chairs or something pretty where the pod bay was in the edit

**Comment by Crazylemon64** [comment]
I don't imagine you're going to redo this, since you've been booted from the server, again.

**Comment by SamHPurp** [comment]
In related news though.... Delta Station has a pod bay similar to this, if anyone is going to be taking up that mantle from where I've left it off.

**Pull request closed without merging**
