### PR TITLE
Added Teddy Bear Plush Sprites and Atoms

### PR DESCRIPTION
**Pull request by MxtrOwl**
## What Does This PR Do
Adds Teddy Bears to the Plushies and Toys available to collect.

## Why It's Good For The Game
My fiancee is a long time player, and irl has a personal philosophy that everyone needs a teddy bear. In a recent round, one of the players wanted a bear plush. One of my friends who also plays wanted a bear plush. I asked deadchat and everyone there said they would love a bear plush. So I added bear plushes.

## Images of changes
BEARS

[use this link if the image doesn't load](https://imgur.com/W7uC0gT)

## Testing
Code compiled, ran locally. Teddy bears can show up with obj/random/plushie and all stuff that uses it.

## Changelog
:cl:
add: Added teddy bears
tweak: Tweaked toys.dmi to make the teddy bears actually inherit everything
imageadd: Added teddy bear sprites
/:cl:

### CODE REVIEW

**Comment by MxtrOwl** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

Fixed! All accounts now linked (I'm Chikori or Lorekeeper in game. I made the Cozi'i religion)

**Comment by Scribble-Sheep** [comment]
Was this preapproved by the coding team? There's a feature freeze rn, so it might not get in rn.

**Comment by MxtrOwl** [comment]
> Was this preapproved by the design team? There's a feature freeze rn, so it might not get in.

Oh. I didn't know that. No it wasn't. Hecc. :/

**Comment by MxtrOwl** [comment]
If it does get denied please tell me why so I can do better in the future <3

**Comment by S34NW** [comment]
Hi, as explained in https://github.com/ParadiseSS13/Paradise/pull/26085, [on discord here](https://discord.com/channels/145533722026967040/499000353312735233/1256632472196878337) and on the top of the [repo home page here](https://github.com/ParadiseSS13/Paradise/blob/master/README.md). We are currently in a period of "quality releases" where only refactor or fix PRs are permitted unless you have prior approval for another PR type. This is commonly referred to as a feature freeze.

As such, this PR is going to be closed. You are welcome to revisit the idea once the freeze has been lifted, but we encourage all contributors to get stuck in with fixes for items on the issue list!

**Pull request closed without merging**
