### PR TITLE
Improve emagged borgs and syndicate MMI

### PR DESCRIPTION
**Pull request by datlo**
This PR reworks the syndicate MMI to be a reliable mindslaver, and improves messages related to emagged cyborgs.

----- EMAG CHANGES -----

You can now tell if a cyborg is emagged (Or has an illegal upgrade!) by scanning it with a robot analyser. You can no longer do so by swiping the borg with an ID.

Improved messages during emagging to make it clear you need to crowbar the borg open to emag its internals. Also improved various messages/code around the code I touched in this, adding spans.

Emagging a cyborg now adds a clause binding it to obey syndicate agents in its law zero, as emagged cyborgs are able to modify their own lawset except for the zeroth law.

----- NEW ROBOTICS BOARD -----

A new cyborg upgrade board can be printed in robotics, 'Purge', at a medium tech/metal requirement which will remove all effects of emagging/illegal upgrades, remove all cyborg laws if not synced to an AI, and reset its module. Nuke ops syndi cyborgs are immune.

----- SYNDICATE MMI CHANGES -----

Syndicate MMI were changed. They are now a stealthy way to subvert cyborgs into your control. Still cost 2 tc.

Previously, they only installed a basic Syndicate lawset into any cyborg you install it into. 

They now mindslave whoever is placed into one, no matter if you put them into an IRC, a Mech, a cyborg, or your backpack, for as long as they remain in the MMI. Removing the brain from the MMI will unslave the mind.

You still cannot use a syndicate MMI to make an AI. 

Cyborgs with a syndicate MMI will function exactly like a standard cyborg, showing as linked to station AI, with laws that can be modified, and standard tools from their modules (No emag stuff) They however get a permanent law zero mindslaving to the owner of the syndie MMI. This law can only be removed or modified by removing the brain from the syndicate MMI.

You can emag a cyborg with a syndicate MMI, which will work the same as emagging a standard cyborg but will not touch the zeroth law, keeping the cyborg enslaved to the MMI's owner.

----- MISC -----

Fixes a bug where mindslaves (From mindslave implant or this new MMI) wouldnt lose their mindslave objective on losing the mindslave antag datum

AI can no longer move to deactivated cameras using 'Show Camera List'. The deactivated cameras (Including emagged borgs) still show on the list.

<details>
<summary>
<i>Guide on fixing rogue cyborgs, add to wiki robotics guide once merged </i>
</summary>
<p>Sometimes, you will be brought 'Rogue' cyborgs and are told to fix em. There are three main ways to subvert a cyborg : 

1. Emagging. Emagging a cyborg will cut connection its Master AI, aswell as enable illegal items to be used on the cyborg and slave it to the emagger. You can tell a cyborg is emagged if it shows 'ERROR : INTERNAL SYSTEMS COMPROMISED' when scanning it with a robot analyser, however this can also be a side effect of an illegal upgrade. You can deconstruct the cyborg entirely, and rebuild it anew, or use a 'Purge' upgrade board if the tech has been researched. Make sure the borg is synced to an AI if you do so, or it will end up lawless after the purge!

2. Syndicate MMIs. Syndicate MMIs are a roboticist traitor item that will stealthily mindslave the cyborg to the owner's will, while leaving its laws and connection to AI intact. The only way to fix it is to deconstruct the cyborg entirely, remove the brain from the Syndicate MMI, and place it in a standard MMI. You should interrogate the MMI to see if they even wanted to be a cyborg in the first place, they might be an unwilling crewmember! They should be handed off to medical, if possible with their original body, for reviving if they are.

3. Law subversion. Either due to being linked to a rogue AI, or due to having laws uploaded directly to it, the cyborg's laws have been modified to act against the station. To fix it, first ensure that the cyborg isn't linked to an AI by cutting the AI Link wire (See Cyborg Maintenance/Modifications). Now apply a cyborg 'Purge' board, which will remove all laws from the Cyborg. Ensure the cyborg is locked down, then hand if off to command to upload a new lawset to the cyborg, or if you are the RD/Acting RD, use the Cyborg Upload Console in AI upload to apply a standard lawset to the cyborg. It is recommended you stop cyborg production if the AI is declared hostile, until Security has given you the all-clear to resume doing so.

</p>
</details>

:cl:
tweak: Emagged cyborgs and cyborgs with illegal upgrades can now be detected with a robot analyser.
tweak: You can no longer tell if a cyborg is emagged/has an illegal upgrade by swiping it with an ID.
add: Added a new cyborg upgrade board, Purge, which will remove all side effects of emagging on a cyborg, remove all laws if it not synced to an AI, and reset its module.
tweak: Syndicate MMIs will now mindslave brains put into it, for as long as they remain in the MMI. This mindslave keeps working if put in a cyborg.
tweak: AIs can no longer move their AI eye to deactivated cameras using 'Show Camera List'
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
`('Its limbs are sparking and its status indicator is blinking red!')`

I'll have to think about the other, in more detail, later---but I don't like this.

Goon has an overlay if borgs are emagged; while this isn't *that* bad, it's going to make using borgs, stealthily, against even semi-experienced players, impossible.

**Comment by daylight2** [comment]
The addition of a way to un-emag borgs without creating a new body for them is defiantly needed.
The syndicate MMI thing is cool
Not the biggest fan of the emagged examine text - if you want to buff emagged borgs against the robotics console, add the ability to emag the console to hide all unsynced borgs / make the lockdown and destroy buttons duds

**Comment by datlo** [comment]
'it's going to make using borgs, stealthily, against even semi-experienced players, impossible.'

The point is to discourage emag uses if you want to be stealthy and adding alternative tools to do so. For roboticists, syndicate MMI are perfectly stealthy unless you deconstruct the entire borg, for other traitors, you can still subvert a borg/its master AI using an upload console.

**Comment by TheSardele** [comment]
Right now, you can already check an emagged borg by whacking it with your ID, it will tell you that the cover is broken. That does require you to be looking for the emagging more actively though, and nobody does this.

**Comment by daylight2** [comment]
It's possible to emag a borg without breaking the cover, if you have Robotics access

**Comment by datlo** [comment]
still shows as broken.

**Comment by Fox-McCloud** [comment]
I'm still opposed to making it easier to tell if a borg is emagged.

This is going to push AI's and borgs even further into the territory of "100% trusthworthy/reliable". There's very little plausible deniability here, at all--it's just "nope, no message, he's safe, lulz".

For a roleplay game that's largely built around paranoid and uncertainty, this is a step in the wrong direction.

**Comment by Spacemanspark** [comment]
Outside of the examine text, I'm overall fine with this.

**Comment by datlo** [comment]
There is plausible deniability in that illegal upgrades will also show the message, and that emagging isnt the only way to subvert a borg, but fine, I'll remove the emag gameplay changes.

**Comment by datlo** [comment]
You can now tell if a cyborg is emagged/has an illegal upgrade by scanning it with a robot analyser (used to be a prob(5) chance to do so... which is kinda irrelevant when you can tell by swiping an ID on the borg.)

You can no longer tell if a cyborg is emagged by examining it or by swiping an ID on it.

**Comment by datlo** [comment]
Added a guide on fixing rogue cyborgs to be added to the wiki at the bottom of the PR desc

**Comment by datlo** [comment]
I'm getting mixed messages here. Do we want emagged borgs to be stealthy or to be easy to detect?

I'm just going to scrap all of the changes besides the syndi MMI rework.

**Comment by datlo** [comment]
Emagging no longer disconnects the cyborg from robotics console and the camera network, and mostly works as it currently does. I've updated the PR description to reflect the current changes.

**Comment by datlo** [comment]
Alright the code works fine and is ready to be merged.

**Comment by Kyep** [comment]
datlo, poke me on discord at some point so I can discuss this PR with you.
I'm debating updating my vote but I want to talk to you about it first.
Oh, and before you poke me: update the PR description to be sure it fully reflects all the changes you've made to the PR.

**Comment by datlo** [comment]
This PR will be divided into multiple PRs in the coming days, as the changes are no longer directly linked to each other. Keeping this open for now so I dont forget, will close when it's done.

**Comment by datlo** [comment]
Git is a fucking massive PITA and I can't get it to work. I'm done for now.

**Pull request closed without merging**
