### PR TITLE
Reduces speed bonus from Meth

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
tweak: Meth (and ultra-lube, its equivalent for synthetics) now grant less of a speed bonus.
/🆑
This affects meth (organic variant), ultra-lube (synthetic variant of same chem) and /obj/effect/mine/pickup/speed (an as-far-as-I-can-tell unused 'powerup' item left in the codebase).

### CODE REVIEW

**Comment by Birdtalon** [comment]
By half?

**Comment by Fox-McCloud** [comment]
Why even have two flags if you're going to reduce one of them.

**Comment by Crazylemon64** [comment]
@Fox-McCloud The distinction is that the two stack

**Comment by Denthamos** [comment]
So I have to ask what is the reasoning behind this nerf of two chems commonly used by antagonists.  Is this meant to be a direct nerf to all antags that use this to their benefit?  

Security already has something in their armory to directly counter organic meth users.

Meanwhile this directly nerfs what borers can do for you combat effectiveness wise, traitor chef with their meth donks, nukies that make use of their box of meth donks, and any other antag (or hell security if they decided to use meth implants/pills) in their actions.  Have people been having issues dealing with meth users?  Hell, I have not seen any complaints about meth anywhere in the past few months, so again wondering where the reasoning behind this started.

**Comment by Shadeykins** [comment]
@Denthamos Yes, people have been having issues with dealing with meth users for the past several years--especially with the proliferation of adrenals in general. The issue is that a lot of our mechanics as they are support a certain type of 'meta' strategy (instastun, for instance) and meth spam is one of those things.

Anything that gets us away from the meta (and instastun/its counters in general) is honestly a breath of fresh air. The game should be about clever strategy and skill, mechanics that distill the game down to "who can spam click the fastest" involve neither of those.

**Comment by Keluandrie** [comment]
Meth's rarely used for the speed it gives you, it's used because of how game over stuns are to an antag. A fully stocked security department, capable of putting you down all round with one hit shot, against a typically lone antag will typically force people into it. I'd say meth abuse is moreso a product of the environment, not the cause of the environment. But, fixing the environment would need a change in combat itself. I'd say that nerfing meth, assuming it still gets you up in a decent amount of time, won't change too much.

**Comment by Keilden** [comment]
So you are saying that the cops are forcing criminals to do meth?

**Comment by AquaVirus** [comment]
> Anything that gets us away from the meta (and instastun/its counters in general) is honestly a breath of fresh air.

@Shadeykins I'd like to know how buffing intastuns _(by nerfing one of its counters)_ gets us away from the meta.

**Comment by Kyep** [comment]
Fixed merge conflict.

**Comment by Shadeykins** [comment]
@AquaVirus You're talking about a system that is pretty much entrenched in our code, it's not going to go away in the span of a PR. Reducing some of the meta is a good first step at dislodging the "I click, I win" strategies.

Ultimately this PR is addressing a symptom of the system (instastuns), but I would much rather have some focus on the symptoms (and maybe a shift from there to root causes) rather than no changes at all.

Either way, if you want to push away from memey combat removing ludicrous speed buffs is one of the ways to do that.

**Pull request merged**
