### PR TITLE
Updates the syndicate combat borg to a cool spider borg

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do
Updates the syndicate combat borg sprite to a cool spider borg.
This sprite, as far as I can tell, came from
image
image

I have updated it to have animated movement.
This borg can be selected by the carborg outfit, though the old nukie borg skin remains there as well

## Why It's Good For The Game

The vertical pill borg, while perhaps realistic, is a bit dated.
A combat spider on the other hand, I feel will mark a bit more fear into the crew, while being a bit nicer to look at.
You can also still choose the old sprite or the heavysyndicate module

## Images of changes

https://imgur.com/a/OKcSR1H look on discord though I'll post again in coding chat as imgur compresses

https://imgur.com/a/732Y5FE

## Testing

See above
<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

image

## Changelog

:cl:
tweak: The syndicate combat borg has a new spider sprite. You can also choose the old sprite, or another heavysyndicate borg module
/:cl:

### CODE REVIEW

**Comment by PopeDaveThe3th** [comment]
While this borg does look very cool, I personally prefer the old one. Will the old shell remain as an option or is this just the new only option?

**Comment by Fordoxia** [comment]
> While this borg does look very cool, I personally prefer the old one. Will the old shell remain as an option or is this just the new only option?

Seconded on wishing for the ability to choose.

**Comment by Qwertytoforty** [comment]
give me 30 minutes

**Review by Burzah — APPROVED** [review]
Code looks good.
Pending categorization and voting.

**Pull request merged**
