### PR TITLE
Craftable Crusader Kite Shield: Spicy Conga Edition

### PR DESCRIPTION
**Pull request by Xantholne**
Adds a crafted Crusader Kite shield made with a wooden buckler+Pen.
Definitely using this as a precursor to see how much people would enjoy resprited items that they could make.
e04c8f40-d9af-11e6-9ec8-9100c7038af5

### CODE REVIEW

**Comment by DesolateG** [comment]
Heh.. How about a stop sign shield? Trash can lid shield?

**Comment by jughu** [comment]
6d337c4e72dc8edb8641b96aeeb973a9

**Comment by KingPhilipIII** [comment]
DEUS VULT

**Comment by LightFire53** [comment]
Deus vult. Now to add more shields...

**Comment by Xantholne** [comment]
I'm considering having this one closed while I make the new ones. Already have several other shields people have requested. Definitively taking any other requests.

**Comment by Dumbdumn5** [comment]
DEUS VULT, INFIDEL!

**Comment by KingPhilipIII** [comment]
WHY AREN'T YOU ON A HOLY CRUSADE TO DRIVE THE SARACENS FROM THE HOLY LAND?!

**Comment by taukausanake** [comment]
Man, if you were taking requests I have a Hylian Shield I sprited who knows when. Then again it's Nintendo so maybe not...

**Comment by Spacemanspark** [comment]
...I actually asked Xantholne to make a hyrulian shield.

**Comment by taukausanake** [comment]
Awwwwww

**Comment by Spacemanspark** [comment]
My point was that it's quite coincidental and you could probably give them your sprite :P

**Comment by taukausanake** [comment]
Oh okay :)

**Pull request closed without merging**
