### PR TITLE
Tweaks demon spawn rate

### PR DESCRIPTION
**Pull request by Coolrune206**
## What Does This PR Do

Changes shadow demon spawn weight from 50 -> 20
Changes slaughter demon spawn weight from 10 -> 20
There will be less shadow demons, and more slaughter demons, but they will now appear with the same frequency.
## Why It's Good For The Game

Hal said to do it - 
Uh, I mean, Shadow Demons had a high spawnrate when they were introduced - this was meant to be toggled down eventually, to be in line with Slaughter Demons, but that never happened, so we may as well do it now.
However, Slaughter Demons are absurdly rare, and could honestly stand to spawn more frequently, so their weighting will also be increased.
## Testing

Numbers change.
## Changelog
:cl:
tweak: Slaughter Demons spawn more frequently, and Shadow Demons now have the same chance as Slaughter Demons
/:cl:

### CODE REVIEW

**Comment by Leanfrog** [comment]
I don't know about boosting slaughter demon spawn rates, unlike shadow demons they're a nightmare to actually take down and also have a much more significant impact due to the fact they consume dead bodies rather than just leave them on the floor.

I've seen time and time again that a slaughter demon in the right hands can cause serious lasting damage (eating command members, etc), in fact the only reason I see slaughters die for the most part is because they misplay or are simply just inexperienced (inexperienced in general, it doesn't take much to understand the basics of what a slaughter demon does).

**Comment by Henri215** [comment]
The rarest events should be terrors/xenos, the most round disruptive ones.

**Comment by meow20** [comment]
Boosting slaughter demon weight would be cool after their nerf.

**Comment by Ordosian** [comment]
Yes, Slaughter demons are powerful in the right hands and can cause a serious lasting effect. However, so can Terrors, Xenos and Blob. All three can cause a nuke. And well, any midround antag in the right hand can cause serious lasting effects. Not to mention that the Demon can easily be blocked by cleaning the blood.

**Comment by Cocacolagua** [comment]
Shadow demon is in multiple leagues below the other major midround antagonists, I disagree with making them the **same** chance as terrors, slaughter and xenos. Either they have a higher chance of rolling, or they've bumped down to the medium midround pool with revenant and morph.

**Comment by hal9000PR** [comment]
> I don't know about boosting slaughter demon spawn rates, unlike shadow demons they're a nightmare to actually take down and also have a much more significant impact due to the fact they consume dead bodies rather than just leave them on the floor.
> 
> I've seen time and time again that a slaughter demon in the right hands can cause serious lasting damage (eating command members, etc), in fact the only reason I see slaughters die for the most part is because they misplay or are simply just inexperienced (inexperienced in general, it doesn't take much to understand the basics of what a slaughter demon does).

a major event should be a major event

**Comment by hal9000PR** [comment]
> I don't know about boosting slaughter demon spawn rates, unlike shadow demons they're a nightmare to actually take down and also have a much more significant impact due to the fact they consume dead bodies rather than just leave them on the floor.
> 
> I've seen time and time again that a slaughter demon in the right hands can cause serious lasting damage (eating command members, etc), in fact the only reason I see slaughters die for the most part is because they misplay or are simply just inexperienced (inexperienced in general, it doesn't take much to understand the basics of what a slaughter demon does).

a major event should be a major event



> Shadow demon is in multiple leagues below the other major midround antagonists, I disagree with making them the **same** chance as terrors, slaughter and xenos. Either they have a higher chance of rolling, or they're bumped down to the medium midround pool with revenant and morph.

could buff them

**Review by farie82 — APPROVED** [review]

**Pull request merged**
