### PR TITLE
Refactors Species Bitflags into Traits List

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors species bitflags to instead be list based. Idea and species list name taken from TG.

Why? Simple, we can run out of bitflags very quickly, but when it comes to a list, then the amount of traits we can have skyrockets.

This also removes a few unused species bodyflags, and one that was literally only used for single item description (there's just too few bodyflags to go around to warrant it).

Also fixed an instance where it was checking for `HAS_SKIN_COLOR` in the species `flags` as opposed to its `bodyflags`.

Also made lips default on all species, since they were, anyway (and not having them would generate odd runtimes).

Lastly fixes a runtime with assigning eye color if the person doesn't have eyes.

This has been lightly tested; it's a bit much to test every single thing here, but, for the most part, it's more of a "it works and doesn't runtime on the surface"; this just needs looked at very closely.

No CL as this is all back end.

### CODE REVIEW

**Comment by KasparoVy** [comment]
My hero!

**Comment by Allfd** [comment]
Stop nerfing runtimes!

**Comment by SheepFighter** [comment]
> This also removes a few unused species bodyflags, and one that was literally only used for single item description (there's just too few bodyflags to go around to warrant it).

Which ones, if you don't mind my asking?

**Comment by Fox-McCloud** [comment]
taping someone's mouth shut and ripping it off.

The flag literally existed just to add "is that fur?" to the description. Not worth it.

**Comment by SheepFighter** [comment]
Yeah, that's horribly pointless. Why did it exist in the first place?

**Comment by taukausanake** [comment]
Because furries. I think it's funny though, like a small detail put in there

**Comment by Allfd** [comment]
I think it would be great to have different fire effects or gibing based off of this, however it can just be re added if that ever is made so it does not really matter.

**Comment by Fox-McCloud** [comment]
Forrrr whatever reason, resolving the conflicts on this caused some issues, so I"m going to close it and resubmit it, especially with it having 14 different files conflicts.

It's awfully old, anyway.

**Pull request closed without merging**
