### PR TITLE
Lets you convert people to text and back again

### PR DESCRIPTION
**Pull request by Crazylemon64**
This gives admins 2 procs: 1 to let them get a string that they can store for later, and another to take that string and use it to re-create the object they used to create the string.

Currently, the only things it has a well-defined functionality for are humans, ID cards, clothes/backpacks/belts, and organs. Everything else has a rudimentary system that just spawns in a new instance of that type.

Also, ID photos are not saved for now, at least until I find out how to turn base 64 strings back into icon datums.

:cl:Crazylemon
rscadd:Admins are now able to convert people into strings for later re-creation
/:cl:

### CODE REVIEW

**Comment by Crazylemon64** [comment]
What
Heresy
Consarn it this compiled on my own end

**Comment by Crazylemon64** [comment]
For those who might be wondering, what exactly one might do with this: With this implemented, it would be easy to add an "Ironman" system via SQL to keep augments and missing limbs between rounds. I am not sure the server is quite balanced around such a system, however.

**Comment by Necaladun** [comment]
If it's optional, awesome. Fuck balance, if people wanna play hardmode ironman, good on them.

**Comment by Dinarzad** [comment]
If it's optional, then like NEca said, that's awesome and I would totally indulge in that feature.

**Comment by PJB3005** [comment]
> at least until I find out how to turn base 64 strings back into icon datums.

I guess you can try to inject the base64 into a savefile with `savefile.ImportText()`, then reading that as normal to get the icon.

**Comment by Dumbdumn5** [comment]
> If it's optional, awesome. Fuck balance, if people wanna play hardmode ironman, good on them.

**Comment by Fox-McCloud** [comment]
>I am not sure the server is quite balanced around such a system, however.

It definitely wouldn't be--someone with all the augments, 1-2 genetic powers, a beneficial virus, and a few other things would be nigh unstoppable if they could merely survive 1-2 shifts.

**Comment by Necaladun** [comment]
Ooooh, now I understand.

That's....scary. Taking things from one round to another is a horrifying prospect.

**Comment by Crazylemon64** [comment]
This PR has other applications than "ironman", of course - it can also be used to save a region's state and keep it for later use as a map template - meaning, admins could finally preserve their mid-round creations for later.

**Comment by Crazylemon64** [comment]
This system already carries over limbs and appearance - viruses, implants, and powers are not included right now. Augments, as a type of organ, ARE carried over, but it would also be possible to strip those out as well.

**Comment by KasparoVy** [comment]
That's hella cool. Glad to hear it's feasible, thanks a bunch for clearing that up
I think, at that point, it'd be an interesting mechanic to have for the people who are most hardcore about round-to-round continuity without being hella broken

**Pull request merged**
