### PR TITLE
Obliterates Zombies

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
This PR removes zombies. They are so incredibly terribly coded, that they somehow manage to not only perform worse than the atmospherics and lighting subsystems, but also manage to make the GC go haywire and have a deletion queue of 5.6 thousand. Put shortly, thats **VERY BAD**

*sorted by total CPU usage*
```
                                                       Profile results (total time)
Proc Name                                                                                   Self CPU    Total CPU    Real Time     Overtime        Calls
---------------------------------------------------------------------------------------    ---------    ---------    ---------    ---------    ---------
/datum/controller/master/proc/RunQueue                                                         0.128       55.824       55.834        0.000         2691
/datum/controller/subsystem/proc/ignite                                                        0.074       55.680       55.693        0.000        19660
/proc/qdel                                                                                    12.951       28.229       28.235       12.814        34313
/mob/living/carbon/human/proc/set_species                                                      0.010       25.909       25.906        0.010           72
/obj/item/organ/Destroy                                                                        0.007       13.904       13.903        0.003         1063
/obj/item/organ/internal/zombie_infection/Destroy                                              0.000       13.672       13.672        0.000           23
/obj/item/organ/internal/zombie_infection/remove                                               0.002       13.672       13.672        0.001           48
/datum/species/proc/create_organs                                                              0.006       12.204       12.207        0.004           67
/datum/controller/subsystem/air/fire                                                           0.001       11.157       11.158        0.000          603
/datum/controller/subsystem/lighting/fire                                                      0.631       10.551       10.550        0.000         1883
```

*Deletion queue of 5.6 thousand items*
image

## Why It's Good For The Game
These are literally the most broken thing the server has seen

## Changelog
:cl:
del: Zombies
add: Performance
/:cl:

### CODE REVIEW

**Comment by CornMyCob** [comment]
ImpROve doN'T REMOVe

**Comment by AffectedArc07** [comment]
@CornMyCob wHen You coDE IT

**Comment by Hyper721** [comment]
i disagree with this, being a zombie is the most fun i've had in this game

**Comment by Fox-McCloud** [comment]
Normally I'd agree with not removing, but this is just a ticking time bomb and liability for admins who don't know the problems it has.

It can come back, one day, when it actually works, of course---but today is NOT that day.

👍

**Comment by AffectedArc07** [comment]
Some players may find these interesting, some may not. The bottom line is, the process of converting a player to a zombie hangs the server for a full 45 seconds. Thats not ok.

**Pull request merged**
