### PR TITLE
Creates the Ruin of Lust

### PR DESCRIPTION
**Pull request by VileReviled**
## What Does This PR Do

This PR adds the Lust Ruin, the sixth Sin ruin. The intention here is to fill the void of the sin ruins (Wrath coming Soon™) while avoiding the breaking of Rule 9 and inspiration of players to break Rule 9 via this ruin. 
It's a small, wooden library. It's carpeted and stocked with books. One stands out: The Unholy Compendium, a dreadful collection of **thankfully forgotten** literature.  Complete a bookcase related minigame (Current iteration: sorting random, book database books into the categories they were assigned by the author.) and the tome is yours, but the price isn't physical in this ruin...

Current relic effects: Upon reading the book, gain a unique spell that knockdowns sentient creatures you can see for a very short amount of time in a very flavor texty way. Has negligible effects on sentient Megafauna (since it's miners that find it, they should be able to use it on more than the crew as a funny haha.)

To Do (Keep drafted until done!): 

- [x] Create the structure and observe it spawning in a lavaland generation.
- [ ] Sprite the Unholy Compendium (Working title!).
- [ ] Create the Unholy Compendium.
- [ ] Create book minigame.
- [ ] Final polishing.

## Why It's Good For The Game

It's always irked me that the sin ruins are incomplete. [The person who created them in 2016 was planning on adding more, but went inactive.](https://github.com/tgstation/tgstation/pull/15708) More content in Lavaland is great on it's own. Those guys are starving down there!

## Images of changes
As seen in map editor, pre-bookshelves + loot
image_2024-10-27_172337989
As seen in game, pre-bookshelves + loot
image_2024-10-27_222503651

## Testing

Ruin generates in Lavaland (see above screenshot.)

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

image_2024-10-27_151545749

  
  
  <hr>

## Changelog

:cl:
add: The Ruin of Lust is manifested! It took on the form of the previously well-hidden past of the Librarians. Find it in lavaland!
/:cl:

### SUGGESTIONS VERY WELCOME!

The nature of this ruin is obviously that of dancing around the rules and keeping it silly, so the current iteration is that of a community reference most are familiar with. However, I would be glad to change things. The Unholy Compendium is the main WIP aspect of this; balance perspectives are extremely welcome.

### CODE REVIEW

**Comment by VileReviled** [comment]
On Hold can be removed and Map Edit added. Working on the sprite for the lootbook next.

**Comment by Crazyhair213** [comment]
I don’t really see how this fits a ruin of lust as it only knocks someone down? Whole sin of lust is about a strong desire for something you crave or "lust" for. Usually associated with after night activities. Now if you ask me for a suggestion with zero balance make them take something that turns them into a quasi vampire that needs to drink blood regularly. Strong desire for to feed to fit their desire of blood.

**Comment by matttheficus** [comment]
Oh boy miner Balance!

personally not a fan of items that can only be used in combat being added to Lavaland, miners get plenty of that already. I would highly prefer that it be something QoL or a neat interaction that isn’t a mindbatterer: Lavaland edition. As such, will be objecting at the current power’s use.

**Comment by autocephalophagy** [comment]
holy shit its the s*x update.

**Comment by VileReviled** [comment]
> I don’t really see how this fits a ruin of lust as it only knocks someone down? Whole sin of lust is about a strong desire for something you crave or "lust" for. Usually associated with after night activities. Now if you ask me for a suggestion with zero balance make them take something that turns them into a quasi vampire that needs to drink blood regularly. Strong desire for to feed to fit their desire of blood.

The main gimmick I'm going for is WGW / Lusty Xeno references (apology for being intentionally vague in the PR itself), and the spell would share your pain (possible brain damage as a cost for reading it) with another, unlucky person. Though...

> Oh boy miner Balance!
> 
> personally not a fan of items that can only be used in combat being added to Lavaland, miners get plenty of that already. I would highly prefer that it be something QoL or a neat interaction that isn’t a mindbatterer: Lavaland edition. As such, will be objecting at the current power’s use.

I agree that this is a probably bad way of implementing the spell. Drawing board, fellas.

While I sprite this up, how would a spell that can grab items at range? E.X. grabbing your dropped pka or grabbing something through glass. Not Instant Summons, because that's intentionally rare through tendrils and works at any range.

**Comment by VileReviled** [comment]
This is abandoned until I or anyone who wants to pick this up thinks of a better idea as a reward. Feel free to use the structure

**Pull request closed without merging**
