### PR TITLE
Adds a helper proc to calculate luminance

### PR DESCRIPTION
**Pull request by Ty-Omaha**
Adds a proc to calculate the perceived brightness of a color
getLuminance

:cl:
add:Adds getLuminance() helper proc
/ :cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Changelogs are for players, not coders.

**Comment by FlattestGuitar** [comment]
Also why add a proc you don't need when you could add it when you need it?

**Comment by Ty-Omaha** [comment]
>Changelogs are for players, not coders.

afaik that's outdated

>Also why add a proc you don't need when you could add it when you need it?

so it's there for other people to use if they need it for something

**Comment by Crazylemon64** [comment]
it's kinda weird to just add a helper like that on its own with nothing that uses it

but I figure it could come in handy for sdql hijinks

**Pull request merged**
