### PR TITLE
Adds a laser carbine!

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Admin only for now.

:cl: FlattestGuitar
rscadd: adds an admin-only laser carbine
/:cl:

Shoots lasers, but is loaded with magazines. 20 lasers in each of those. Uses a two-shot burst if you want it to.

Original sprites by @Regen1 from #3667

Dunno if I should tweak those or not.

### CODE REVIEW

**Comment by Regen1** [comment]
Probably needs some sprites based on how much ammo it has left etc

Shitty recolored Ion carbine looks good though 👌

**Comment by Allfd** [comment]
From a gameplay perspective this could be fun.

From a lore perspective,

A power source for a far future laser weapon has a number of difficult design requirements, it must be reliable, it must have high energy density, it must also have a high power density (rate of power transfer) and it needs to have a long shelf life (in decades).  Recharging is nice but not practical or needed.

A current IRL technology fits this need, molten salt batteries.

These are (usually) use once batteries that are completely inert before use (with a shelf life measured in decades, sometimes upwards of 50 years) and use molten salt as an electrolyte.

When its time for use, a pyrotechnic charge in the battery ignites and melts the salt which then becomes a conductive electrolyte. 

This technology has been around for decades but has seen its uses restricted to space flight/science  and military applications that will need a ton of power immediately.

Anyways from a lore perspective while a rechargeable laser is more likely to appear in science fiction, a magazine based weapon is a better fit to current real life engineering approaches used in this type of situation.

**Comment by KasparoVy** [comment]
That is some DEEP lore. Sounds sick.

**Comment by FlattestGuitar** [comment]
Actually, don't merge this. I need to find some slave to sprite me a proper magazine.

**Comment by Regen1** [comment]
Molten salt gun?

Did Alffd just weaponize salt? Good god paradise is going to be rich

**Comment by Spacemanspark** [comment]
I like the idea, but I don't particularly care for the carbine sprite itself.
Since this is admin only for now, it could just stay there until someone has the time to make a neat sprite for it though.
So :+1:

**Pull request merged**
