### PR TITLE
Fix: paradise_schema missed migration

### PR DESCRIPTION
**Pull request by Furrior**
## What Does This PR Do
Adds missed migration (42-43) to the main schema file

## Why It's Good For The Game
Now you wont get sql errors on death on your local server

## Changelog
:cl:
fix: If you are running a local server with sql enabled: now default sql schema works correctly on player's deaths
/:cl:

### CODE REVIEW

**Comment by Furrior** [comment]
This time intentionally here, lol

**Review by AffectedArc07 — APPROVED** [review]
How did CI not pick up on this

**Comment by Furrior** [comment]
> How did CI not pick up on this

How did somebody merged a pr that breaks tests

**Comment by Furrior** [comment]
@AffectedArc07 tests got fixed

**Pull request merged**
