### PR TITLE
Creative coding lattice sprite update

### PR DESCRIPTION
**Pull request by DogsParadise**
It changes the lettuce, I mean lattice in game.

## What Does This PR Do
Changes a sprite for lattices
-Adds depth
-Changes color to fit more with the new one we are importing of TG.
-Errors in sprite been fixed, like overlapping pixels etc.

It looks like a minor change, it wasn't - spoilers

## Why It's Good For The Game
Making better creative coding, makes the game look nicer.

## Images of changes
Old:
image

New:
image

Old:
image

New:
image

image

Old:
image

New:
image

Old:
image

New:
image

## Changelog
:cl:
tweak: Tweaks Lattice
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Looks really smart

**Comment by DogsParadise** [comment]
> Looks really smart

No you are smart

**Comment by Mitchs98** [comment]
I too like crispy and refined lettuce.

**Comment by procdrone** [comment]
im definitely not a coder or reviewer, but shouldn't changelog entry be "changed lattice sprite" ? tweak doesn't mean much unless you say what the tweak is.

**Comment by DogsParadise** [comment]
> I too like crispy and refined lettuce.

image

lettuce

**Review by Kyep — COMMENTED** [review]
Side-by-side before and after images, please.

**Comment by DogsParadise** [comment]
> Side-by-side before and after images, please.

Added some old sprites for comparrison

**Comment by maxymax13** [comment]
might backport this 👀

**Review by Necaladun — APPROVED** [review]
Beautiful! Approved.

**Comment by SabreML** [comment]
Is it possible to try a variant without the pointy bits? It may look better if it's smoothed.

Current version:
image
PR version:
image

**Comment by DogsParadise** [comment]
> might backport this 👀

To TG, you mean?
If so, go ahead.

**Comment by DogsParadise** [comment]
> Is it possible to try a variant without the pointy bits? It may look better if it's smoothed.
> 
> Current version:
> image
> PR version:
> image

If people want to see this. I can pr a new one, but i think the pointy bits add a bit of depth

**Review by dearmochi — APPROVED** [review]
You gotta eat the lettuces, right, just straight up eat the lettuce.

**Comment by DogsParadise** [comment]
I am closing this, i prefer my sprites not being merged in paradise atm.

**Pull request closed without merging**
