### PR TITLE
New Airlock Sounds

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Port of: https://github.com/tgstation/-tg-station/pull/16109

- Doors play an actual sound when bolts are dropped/lifted instead of a message of "you hear a click from the bottom of the door"
- Doors play an access denied sound when you don't have access to a door

Related
- Cutting wires will play the wirecutter sound
- Pulsing wires will make a click sound

Code Wise
- More OOP handling of unique door open/close sounds

:cl: Fox McCloud
soundadd: Added in sounds (instead of a chat-based message) for when airlocks are bolted/unbolted
soundadd: Added in sound for when airlocks deny access
tweak: cutting/pulsing wires will play a sound
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
This will encourage door fetishes!

**Comment by tigercat2000** [comment]
Don't like the sounds. :-1:

**Comment by Spacemanspark** [comment]
I'm a bit mixed. I was on /tg/ a bit ago and was able to hear these noises myself.
I kinda like the sounds, but something about them seemed... off, to me. Can't really put my finger on it.
I'll give it a tentative :+1: for the time being.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Have you tried cycling airlocks with them yet? It makes them sound really cool.

**Comment by Kerroman** [comment]
Classic DOOM door sound effects when!?

https://www.youtube.com/watch?v=el72n7U4Pos

**Comment by ProperPants** [comment]
These all sound like somebody trying to make the noises an office printer from 1990 makes without using an office printer. The "access denied" buzz also sounds _exactly_ like an oinking pig toy. I'm not even joking on that one. Watch the video I give and try to tell me it doesn't.

https://www.youtube.com/watch?v=_84xgLO1FG8

**Comment by KasparoVy** [comment]
Sounds just fine to me. Wicked stuff, glad to have the extra sounds for closing and bolting now

**Comment by Tastyfish** [comment]
I think the denied sound sounds more like a frog.

**Comment by YeAdventurer** [comment]
https://youtu.be/OdLRZzCf_kk?t=7

**Comment by tigercat2000** [comment]
I don't like *any* of the sounds, to be clear. They don't seem in spirit with SS13.

**Comment by Necaladun** [comment]
Overall, :-1:. I love the idea of having sounds for these things for sure - especially bolts -but these don't fit at all - the close does not match the open at all, the bolts down has a weird frog-fart at the start, the beep at the start of bolts up is annoying and too high pitched, and the denied one is one "whoop" too long, should be more of a "dun dun" rather than "boop boop boop" imo.

Overall they just seem to...not match the general feel of other sounds, and would be out of place.

**Comment by Dumbdumn5** [comment]
After a live test, the sounds fit perfectly well, denied and bolt sounds meshed well with the aesthetic, but the woosh close sound seemed a bit off when compared to the opening sound in terms of style. The two sounds seem to be completely different in terms of how the style and type of airlock it seems to be sounds when closing. Still, :+1:

**Comment by Tastyfish** [comment]
Personally, I liked the denied and bolts sounds, just not the close sound.

**Comment by Aurorablade** [comment]
agreend i liked the denied and bolt sounds. The problem with the opening/close sound, the door opening useing the woosh/swish the door closing now uses a kinda of click/mechnical interlocking noise. I like the feel of the interlocking-click but it does not mesh with the swish. If we could find a sound to match the interlock noise for doors opening, we would be golden. But it would require someone good at finding or making sounds...

**Comment by Spacemanspark** [comment]
I suppose they feel off in the sense that they don't really fit into the game's spirit, perhaps.
After having spent a bit more time really listening to these sounds, both live and here, I'm gonna change to a :-1:.

**Pull request merged**
