### PR TITLE
Axes NTTC

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This PR removes NTTC. Reason for this is its too expploitable, and also hard to explain in-character. Personally I dont fully want this, but maintainers said so.

Tested and comms still works fine, so I call this good.

**Changelog:**
:cl: AffectedArc07
del: Removes NTTC
/:cl:

I would be happy to make a version of the regex that bans all HTML if this is deemed too far

### CODE REVIEW

**Comment by dovydas12345** [comment]
Big F
May NTTC rest in peace.
(If the PR gets merged of course)

**Comment by taukausanake** [comment]
I _STILL_ miss NTSL, but NTTC was so lousy compared to it. RIP in pieces

**Comment by AffectedArc07** [comment]
Nothing happened there

**Comment by Tayyyyyyy** [comment]
We could always do a tiny hack like in #8830 if we still want job tags.

**Comment by AffectedArc07** [comment]
@Tayyyyyyy off topic, if we remake that can we have it be part of the multitool UI? Having two seperate UIs isnt the most convenient thing, from a user or code perspective.

**Comment by Fox-McCloud** [comment]
Good riddance.

**Comment by Aurorablade** [comment]
This really does not need to be removed just the HTML needs to be setup to be sanitized and according to mark there's various libraries for that

**Comment by Ty-Omaha** [comment]
I think it would be interesting to explore a CM style of chat text where important people get larger text on the radio.

**Comment by Spacemanspark** [comment]
About time we got rid of this completely.

**Comment by Tayyyyyyy** [comment]
@AffectedArc07 yeah sure, the interface I made was buggy and not really finished anyways. Multitool UI sounds much better.

**Comment by Kyep** [comment]
I'm against removing NTTC outright, as there are certain features of it (like job indicators) that I find incredibly useful.

I agree that it is probably a good idea to keep regex search/replace features disabled, though.

**Comment by Shadeykins** [comment]
Job scripts are useful, sure, they also completely invalidate any clever usage of the voice changer. Telecomms scripting in general has been an incredible headache that needlessly forced words into peoples mouths or entirely removed a vital element of social ambiguity from the game.

You shouldn't know the exact position of 100+ people on station at all times without at least checking a manifest just because they talked on the radio. Likewise, you shouldn't know someone is using a voice-changer or possesses a stolen ID because they talked on radio.

Perhaps this will also force Command to consult the manifest once in awhile and familiarize themselves with who's who (and, in the process, see which jobs need to be filled).

**Comment by Kyep** [comment]
I'm fine with making the voice changer display your job as whatever job the person you're impersonating has. E.g. if you impersonate the Captain with a voice changer a job script should list your job as Captain.

I'm also fine with making job script not display any job for civilians, so even if you impersonate the voice of someone who has no entry on the manifest, you'd still display the same as a civilian, so it wouldn't be totally obvious your name was fake.

I think it should be possible to have a a job script that doesn't cripple the utility of the voice changer.

If it turns out it isn't... then frankly I think the job script is more valuable to the game than the voice changer is, so while I don't think we have to choose one or the other... if we do have to chose, I think the job script is better.

The job script provides such utility for pretty much every member of the crew, that not having it makes ALL radio communication much more difficult. The benefits of voice changers would have to be insanely good to outweigh that, and they aren't. Most of the time they just get used for light trolling/impersonation. I can't remember the last time anyone even attempted to use them for anything I'd consider interesting... certainly not anything that justifies gutting job scripts for their sake.

Again, I think its perfectly possible for us to have job scripts AND functional voice changers. But, if we have to chose one of the other, I think job scripts are better.

**Comment by Shadeykins** [comment]
> 
> 
> I'm fine with making the voice changer display your job as whatever job the person you're impersonating has. E.g. if you impersonate the Captain with a voice changer a job script should list your job as Captain.
> 
> I'm also fine with making job script not display any job for civilians, so even if you impersonate the voice of someone who has no entry on the manifest, you'd still display the same as a civilian, so it wouldn't be totally obvious your name was fake.
> 
> I think it should be possible to have a a job script that doesn't cripple the utility of the voice changer.
> 
> If it turns out it isn't... then frankly I think the job script is more valuable to the game than the voice changer is, so while I don't think we have to choose one or the other... if we do have to chose, I think the job script is better.
> 
> The job script provides such utility for pretty much every member of the crew, that not having it makes ALL radio communication much more difficult. The benefits of voice changers would have to be insanely good to outweigh that, and they aren't. Most of the time they just get used for light trolling/impersonation. I can't remember the last time anyone even attempted to use them for anything I'd consider interesting... certainly not anything that justifies gutting job scripts for their sake.
> 
> Again, I think its perfectly possible for us to have job scripts AND functional voice changers. But, if we have to chose one of the other, I think job scripts are better.

The bulk of my statement isn't about the voice changers, it's the fact that radio communication being difficult is an integral feature of the game that has important ramifications for antagonists who are supposed to be using social manipulation. Everyone knowing everyone else's job with 0 active involvement and having them thrown around in passing makes it far more difficult to do such a thing.

**Comment by Fox-McCloud** [comment]
Conflicts.

**Pull request closed without merging**
