### PR TITLE
Rearranges the captain's desk area so it's less cramped.

### PR DESCRIPTION
**Pull request by orelbon**
captain edit

### CODE REVIEW

**Comment by orelbon** [comment]
@Fox-McCloud Sorry for the reupload but it's easier for me.

**Comment by Davdichan** [comment]
I like it, though the consoles should be next to the/a chair for immushions sake.

**Comment by orelbon** [comment]
capture

@Davdichan Hows that.

**Comment by Davdichan** [comment]
@ orelbon Literally the opposite of what I asked.

I mean closer to computers/comm console, not the edge of the desk.

**Comment by FreeStylaLT** [comment]
You made it more spacious, but sacrificed having the consoles be within reach when seated. I don't think exchanging practicality for more room is a good idea for the area Captain is meant to spend most time in. 
You don't have the bridge consoles one tile away from the chairs.

**Comment by Fox-McCloud** [comment]
Any plants on updating this?

**Comment by taukausanake** [comment]
> Any **plants** on updating this?

You've been working on Botany code too much

**Comment by Fox-McCloud** [comment]
Going to close this. No updates, responses, or anything from the submitter despite people requesting changes/providing feedback.

**Comment by monster860** [comment]
Git FOXBLOCKED.

**Pull request closed without merging**
