### PR TITLE
Space Ruins: blowntcommsat Rework

### PR DESCRIPTION
**Pull request by Venuska1117**
I know, i know, blowntcommsat is relict of the past and how it looked before (discord people enlightened me) but i believe it need rework, now you need do some "hacking" before getting other EVA gear, so its not "easy" reward for lack of risk.

## What Does This PR Do
Change old look of blowntcommsat to new version.

## Why It's Good For The Game
Now this ruin require some work to get free EVA gear, its good place for antags to make base (if they ever find this ruin)

## Images of changes
Old
New

High Resolution to check up closer (need download and open on pc):
High_Res

## Testing
Used Debug to upload and spawn space ruin in space, it come out not 100% good, but it didnt create errors or issues when running private server.

## Changelog
:cl:
tweak: Rework blowntcommsat Space Ruin.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
`ERROR: Non-TGM formatted map detected. Please convert it using Map Merger!`

If you edited this map with the default BYOND editor, please run `tools/mapmerge2/I_Forgot_To_Map_Merge.bat`

**Comment by Venuska1117** [comment]
> `ERROR: Non-TGM formatted map detected. Please convert it using Map Merger!`
> 
> If you edited this map with the default BYOND editor, please run `tools/mapmerge2/I_Forgot_To_Map_Merge.bat`

issue is, i used StrongDMM

**Comment by AffectedArc07** [comment]
> > `ERROR: Non-TGM formatted map detected. Please convert it using Map Merger!`
> > If you edited this map with the default BYOND editor, please run `tools/mapmerge2/I_Forgot_To_Map_Merge.bat`
> 
> issue is, i used StrongDMM

Set your map format in settings to `TGM` and save again.

**Comment by Contrabang** [comment]
Could you please make sure that all the wall segments are connected together like this?
image
All other maps follow this standard of mapping walls

**Comment by Venuska1117** [comment]
> Could you please make sure that all the wall segments are connected together like this? image All other maps follow this standard of mapping walls

Done
image

**Review by S34NW — APPROVED** [review]

**Comment by Venuska1117** [comment]
image

**Comment by AffectedArc07** [comment]
> 

Not required

**Pull request merged**
