### PR TITLE
Revert "Wizard Rod Form"

### PR DESCRIPTION
**Pull request by SamHPurp**
Reverts ParadiseSS13/Paradise#6448

This is too unbelievably strong currently. It is un-escapable, un-fun - removes the need for things like knock.

And is ported from a codebase where people run way faster.

I've observed two rounds now where the wizard has had this, even the un-upgraded form and it caused no end of salt from the playerbase.

We'd be better without this spell until it can be balanced - if - it can be balanced for Paradise gameplay.

### CODE REVIEW

**Comment by LightFire53** [comment]
Would {#6558} be viable to test first?

**Comment by SamHPurp** [comment]
@LightFire53 Sure. Something needs to be done about it and soon. It isn't fun for anyone other than the Wizard - which is the wrong type of thing we should be adding to the game. But hopefully at half speed and a warning, it more enjoyable to play against?

**Comment by jughu** [comment]
SORRY I CANT HEAR YOU OVER THIS EI NATH

**Comment by jughu** [comment]
plus why wouldnt the wizard get strong spells hes the only antag litteraly if he dies the game is over(unless raging mages) and considering you can down a wizard in 2 buckshots

**Comment by Fox-McCloud** [comment]
Closing. This is kneejerk for something that's only been around a couple of days.

**Pull request closed without merging**
