### PR TITLE
Moves gloves of the north star to dangerous items

### PR DESCRIPTION
**Pull request by Anasari**
This moves gloves of the north star to highly visible and dangerous weapon.

🆑 
tweak: Gloves of the north star is now categorized under highly visible and dangerous weapon instead of pointless badassery. (Because it's actually good)
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Them being under badass is fine; the bundles, crates, cards, and cash are "dangerous" on some level (to an extreme). The category is largely there for gimmick items, items that are unconventional, or ones that are random.

The gloves lean strongly towards the gimmick category.

**Comment by Spartan6** [comment]
They’re hardly gimmick, or badass. Badass items are largely useless that make you a badass for actually using them and doing your objectives. Most of them are jokes, with the only one not being that the Surplus, which has a badass title since you literally don’t know what you’ll get.

These gloves on the other hand have valid combat use. They can be combined. They can be very powerful. Hardly a gimmick or badass, they’re a good weapon.

**Comment by Spacemanspark** [comment]
@Fox-McCloud Considering what I've seen them alone accomplish today alone, I have to disagree.

**Comment by Aurorablade** [comment]
not all bad ass items are useless..you just have to be celver...if the issue is hulk..Fox is addressing that or making it easier to address.

**Comment by granodd** [comment]
I wouldn't put them under "Highly Visible & Dangerous" items, but I would put them under the stealthy weapons. They just look like gloves at first glance, but are deadly once in action.

**Comment by taukausanake** [comment]
Maybe simple answer is for hulk to not be able to wear gloves

**Comment by Spartan6** [comment]
@taukausanake That doesn’t mean they’re still not a dangerous weapon.

**Comment by Fox-McCloud** [comment]
>not all bad ass items are useless..you just have to be celver...if the issue is hulk..Fox is addressing that or making it easier to address.

This; the hulk PR addresses this, but it being merged is dependent on another PR being merged first.

**Comment by tigercat2000** [comment]
These gloves fit better in the dangerous category. They're rather useful in combat, and just because they're a funny meme doesn't really mean they're badass. @Anasari Fix the merge conflicts and I'll merge this.

**Comment by KasparoVy** [comment]
I seriously regret the merge of this weapon.

**Pull request merged**
