### PR TITLE
AI Lawset Change: 'Minimize expenses' becomes 'Maximize profits'

### PR DESCRIPTION
**Pull request by Lady-Luck**
Does anyone care for those rounds when the AI decides that the infinite power the station is generating needs to be preserved at all costs?

This lawset should be more fun, and I think a good way to do that is shifting the focus away from trying to keep costs down to trying to generate as much profit as possible. You have to spend money to make money, after all.

:cl: Lady-Luck
tweak: Corporate AI's 4th law is now to 'maximize profits' rather than 'minimize expenses'. Rule of Acquisition 62: The riskier the road, the greater the profit.
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
I like the intent of the change.

I just worry that bad AIs will continue being jerks, and just find some new way to justify it with this lawset.

Old lawset: "Sorry, I cannot let you into the teleporter room, RD. It is depowered to reduce expenses."
New lawset: "Sorry, I cannot let you into the teleporter room, RD. It is depowered because operating the teleporter does not increase profits."

**Comment by Alex6511** [comment]
I think you're missing the point. It's something for the AI to do other than open doors and generally be walked all over. Every lawset has downsides, that's part of the idea.

**Comment by Lady-Luck** [comment]
>I just worry that bad AIs will continue being jerks, and just find some new way to justify it with this lawset.

Jerky AIs are going to be jerky AIs. But this should be more fun. Why not try it?

**Comment by Lady-Luck** [comment]
>I think you're missing the point. It's something for the AI to do other than open doors and generally be walked all over. Every lawset has downsides, that's part of the idea.

This would have similar downsides, it would just be more fun.

**Comment by Fox-McCloud** [comment]
This pretty much gives the AI excuse to be a jerk to anyone who isn't "maximizing profits"...probbbbabbly not a good idea.

**Comment by Lady-Luck** [comment]
>This pretty much gives the AI excuse to be a jerk to anyone who isn't "maximizing profits"...probbbbabbly not a good idea.

The AI is already a jerk to people who are generating expenses. It just inverts the problem. It's just generally, the AI trying to make things more profitable is going to be more fun than trying to turn things off around the station.

**Comment by Lady-Luck** [comment]
To the people who dislike the PR, what would you suggest? I just think shifting the focus to profits to expenses will GENERALLY make things more fun. There's still going to be cases where the AI is just a dick, sure, but some ways of being a dick generate more fun than others.

**Comment by Alex6511** [comment]
> what would you suggest

Leaving it alone, don't fix what isn't broken.

**Comment by Lady-Luck** [comment]
>Leaving it alone, don't fix what isn't broken.

It's not a 'fix', it's changing it based on the idea that this will be more fun.

**Comment by Lady-Luck** [comment]
Welp, people don't like this idea.

**Pull request closed without merging**
