### PR TITLE
^^^Map Freeze in Effect Above This Point^^^

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes human mob code, as this is the problem with 99% of all code.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
GOSH DAMN IT WHY DIDN'T THIS PASS TRAVIS.

SHIT!

**Comment by monster860** [comment]
Is this a joke PR or something?

**Comment by TheDZD** [comment]
Nope, map freeze is in effect so #2719 can actually be finished without a metric ton of map conflicts.

**Comment by tigercat2000** [comment]
kek

**Comment by Fox-McCloud** [comment]
accidental deletion FTL.

**Pull request closed without merging**
