### PR TITLE
Adds new riot shotty sprites

### PR DESCRIPTION
**Pull request by FlattestGuitar**
**CURRENT SPRITES**:

**NEW SPRITES:**

Port from Stratus. Original sprites by Machofish, whose GitHub account remains unknown to me.

I won't be tweaking any of this; feel free to just make this a :+1:/:-1:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Not a fan. These are lower quality than the current shotgun sprites, with less detail, less fidelity, and worse shading.

**Comment by Spacemanspark** [comment]
I like the sprites, honestly.

**Comment by Fox-McCloud** [comment]
Ok, these replace the riot shotgun. 

Yeah, going to definitely give this a 👎. The combat shotgun is the one with the "meh" sprite, and this looks like the combat shotty with a stock glued onto it. It no longer looks like a Benelli M4 and has lost the wonderful shading it previously had.

reference: img1

**Comment by scrubmcnoob** [comment]
Wait the Riot shotgun is supposed to look like a Benelli m4? That doesn't make much sense as the Bennelli is semi-auto, not pump. And the pump bar is resting at the front of the barrel, not by the receiver.

In regards to the combat shotgun, I like as it is now.

And this suggested sprite is really dark, hard to make out the different designs. I feel as if the current riot shotgun is more detailed.(Assuming this is a replacement for the riot-shotgun)

**Comment by FlattestGuitar** [comment]
I've added comparison pics to the description.

**Comment by Codydozer** [comment]
Keep current Combat Shotgun, change the riot one to the PR @FlattestGuitar

**Comment by FlattestGuitar** [comment]
Literally what this PR does, Cody.

**Comment by Draconic-saint** [comment]
All that guff about what it's based on etc is irrelevant.

the new sprite is too dark IMO, and you lose shading on the pump(is that what it's called? I'm not a gun person.) and the main body. The contrast on the barrel looks weird to me aswell.

Just my opinion, but I'd prefer to keep the Originals over this.

**Comment by tigercat2000** [comment]
Yeah, I definitely don't like the new sprites. I like all of our current shotgun sprites as-is.

**Comment by Fox-McCloud** [comment]
General consensus is not positive on this, and due to the submitter not wanting to tweak it, going to close this.

**Pull request closed without merging**
