### PR TITLE
Preference Screen Overhaul

### PR DESCRIPTION
**Pull request by tigercat2000**
Reorganized the character preference screen.
pictures speak
or something

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Body accessory should be under `Hair & Accessories`

**Comment by tigercat2000** [comment]
@Fox-McCloud i considered that, but it would have extended the entire left side too much

**Comment by monster860** [comment]
@tigercat2000 I can clearly see that there's space for that.

**Comment by tigercat2000** [comment]
@Fox-McCloud I can see the point about moving body accessory, but the character records are fairly closely tied to the job (and prevent there from being an entire section for just one button)

**Comment by tigercat2000** [comment]
did 2/3 @Fox-McCloud 
pictures speak
or something

**Comment by Fox-McCloud** [comment]
Think it would be best to move flavor text below the nanotrasen relation (due to it being huge)?

**Comment by tigercat2000** [comment]
@Fox-McCloud done, but i'm not rebooting the server to make new screenshots

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Literally the /worst/

:stuck_out_tongue:

**Comment by KasparoVy** [comment]
Looking wicked, excellent work and good decisions

**Comment by QQCucumber** [comment]
Could antagonist settings be tied to character slot?

**Comment by tigercat2000** [comment]
@QQCucumber probably, but that's not for this PR, and would require mysql changes

**Comment by Regen1** [comment]
Personally i'd like to see the "Load character" part to be centered and under the line, then under that again you have the name preferences etc

Makes it look more tidy and centers everything a bit

**Comment by tigercat2000** [comment]
eh give it a few days after the next patch and see how it is

**Pull request merged**
