### PR TITLE
Removes Mindshield from Brig Phys

### PR DESCRIPTION
**Pull request by TDSSS**
## What Does This PR Do
This PR removes the Mindshield implant from Brig Phys and allows them to be antags besides blob. It also fixes an oversight in their access when not using minimal access (we always use minimal access) wherein they didn't actually have any sec access

## Why It's Good For The Game
The intent of the Brig Phys when it was added was that he would _take care of prisoners_ first and maybe patch up a sec officers second. Instead, Brig Phys has turned into Security's private medbay, with full surgery setups, sleepers, precloning and cloner, implantation of all kinds of powergaming implants and so on. 

Security never has any reason to go to medbay with a competent Brig Phys around and often do rely on the Brig Phys because they know he can't be an antag. Sometimes, I even see command members get treated by the Brig Phys because they trust him more than medical doctors.

Distrust and betrayal are a fundamental part of this game. Brig Physicians are not officers and should (baring extreme circumstances) never fight antag or have weapons more dangerous than a flash, so I think there are no major power issues with letting them be traitor.

**But he has access to Brig, antags shouldn't have Brig access!**
Do you know who else has access to brig? Heads, who all have basic Brig access, as well as the HoP.

**But he'll kill an officer getting surgery, this is unfair!**
Yes, getting surgery is always a risk. I added surgery pain specifically so that you have that moment of vulnerability when getting surgery.

**But he'll help perma prisoners escape!**
So can other antags, too. How often do they go out of their way to free their buddies in perma? Especially as the Brig Phys would be risking his cover by just opening a bunch of doors and letting a prisoner walk out. On the other hand, he might do something subtle like fake needing to give a prisoner a treatment, smuggle in tools to allow the antag to escape later on his own, etc. I think the interesting stories this might generate are well worth it.

## Changelog
:cl:
del: Removed Brig Phys mindshield
tweak: Allows Brig Phys to be antag
fix: Fixes Brig Phys access when not using minimal access
/:cl:

### CODE REVIEW

**Comment by MRgaty** [comment]
I cant support any antag with basic sec access at roundstart, plus this will just make the brig phys useless as they cant be trusted to cut you anymore.
Rather get the implants yourself and let the warden do the surgery.
I dont like this

**Comment by TDSSS** [comment]
> this will just make the brig phys useless 

See, this is _exactly_ the kind of attitude I mean. People regarding the Brig Phys as sec's private 100% trustworthy powergaming doctor when their actual purpose should be taking care of prisoners.

**Comment by Quantum-M** [comment]
I strongly disagree with this, if they can become a antag, might as well remove the job all together, due to the amount of access they have around the brig, and that _all_ security staff are supposed to be trusted.

> But he has access to Brig, antags shouldn't have Brig access!
Do you know who else has access to brig? Heads, who all have basic Brig access, as well as the HoP.

The CE, RD, CMO only have _Brig_ access, meaning the hallway areas and the processing area of the brig, the HoP has extended access to most of the brig by default. These roles are the only ones that has brig access and can be antags, and if any of them loiter around the brig for too long, especially without security supervision, it ends up raising red flags.

> But he'll kill an officer getting surgery, this is unfair!
Yes, getting surgery is always a risk. I added surgery pain specifically so that you have that moment of vulnerability when getting surgery.

Why not just remove their surgery access and/or give them some SOP thing dictating that they shouldn't do medbays job, or remove their office all together? I agree that the whole "Brigbay" setup they tend to make is very annoying and undermines medbay. Removing their access might make it much harder for the Brig Physician to legitimately have stuff that they can now not have, and if you remove their office, that means they have no "legitimate" place to build up their medical equipment.

> But he'll help perma prisoners escape!
So can other antags, too. How often do they go out of their way to free their buddies in perma? Especially as the Brig Phys would be risking his cover by just opening a bunch of doors and letting a prisoner walk out. On the other hand, he might do something subtle like fake needing to give a prisoner a treatment, smuggle in tools to allow the antag to escape later on his own, etc. I think the interesting stories this might generate are well worth it.

This will make the job for Security much more painful. If antags are trying to break out other antags, they have to steal a security officer level ID, break in, or emag their way. With the Brig Physician, they can just open the doors towards the courtroom, _a area of low traffic and a maintenance door_, and call it a day.

You also have to keep in mind that with their access, they can easily access _round start stuns from the very beginning_ along with medical items that can prove to be deadly in themselves, e.g. surgery.

If one argues that the HoP can do the same, keep in mind that they have no business in having the stuff I mentioned, and they have to go through several people, or put in a lot of effort to keep things hidden, to get said stuff.

**Comment by Mitchs98** [comment]
Disagreeing with this for the concerns raised above. While I see no reason to remove Brig Phys' office/add SOP for them stating they can't do so and so, I also see no reason to remove their mindshield. All this will end up doing is allowing antags a free pass out of perma through the courtroom unless the AI just so happens to be watching which they likely won't be.

**Comment by Ty-Omaha** [comment]
>Do you know who else has access to brig? Heads, who all have basic Brig access, as well as the HoP.

Heads running around the brig is abnormal. People pay more attention to them, whereas the Brig Physician is supposed to be in the brig all the time.

>But he'll help perma prisoners escape!
So can other antags, too

Yes, the other antags with the job to run around the brig for the whole shift as nobody bats an eye. /s

>risking his cover

This is a gross exaggeration on how closely watched perma is. The warden is busy processing people and doesn't have time to babysit perma for the whole round.

**Comment by Blackmage198** [comment]
This would kill the Brig Phys job, no player would sit 2 hours, only applying bandaids on the occasional prisoner if sec doesn't trust 'em to do basic medical on the rest of the security staff.
Besides, setting up the BrigBay is basically 70% of the fun of Brig Phys

**Comment by MRgaty** [comment]
I want to add, that I don't see what is wrong with the brig phys treating security, or with security having a safe spot to heal/upgrade themselves.

**Comment by TDSSS** [comment]
>The CE, RD, CMO only have Brig access, meaning the hallway areas and the processing area of the brig, the HoP has extended access to most of the brig by default. These roles are the only ones that has brig access and can be antags, and if any of them loiter around the brig for too long, especially without security supervision, it ends up raising red flags.

There's one more role that can be antag and that has full brig access, including the ability to easily open doors. The AI. Any malf AI could easily just open said doors remotely, or have a sec borg do it (who's going to notice a sec borg moving in brig?). Does this mean sec has to deal with perma prisoners being freed every time there's a malf AI? Definitely not.

**Comment by Mitchs98** [comment]
Malf AI's are semi-rare, comparing them to a role that's almost always on station isn't really very valid in my opinion.

**Comment by TDSSS** [comment]
> Malf AI's are semi-rare, comparing them to a role that's almost always on station and would have a higher weighted chance to be an antag(more than likely) isn't really very valid in my opinion.
> 
> Not to mention a being with hands is much more a pain in the ass to deal with than an AI or its borgs unless you have the rare circumstance where one or both are fairly robust.

Uh, from what I can tell in code, an AI's odds of getting traitor are equal to those of anyone else, and there is basically always an AI due to how AIs are selected. Malf AIs are semi-rare because it is literally just a single job that a single person fills, same as brig phys. There's gonna be more antag scientists for example because there's 5 scientists per round but only 1 AI, etc.

**Comment by MRgaty** [comment]
Other jobs also having easy brig access does not really adds to the reason as to why you want to add one more.
I just think that this will more likely kill the role and be an excessive pain in the ass for security, I really dont see why the brig phys helping sec is that bad.

**Comment by TDSSS** [comment]
>I just think that this will more likely kill the role and be an excessive pain in the ass for security, I really dont see why the brig phys helping sec is that bad.

Nobody says they can't help sec after this. They'll just be a traitor sometimes. You can get help from people that you do not 100% ooc know are definitely on your side.


Also on the they're too powerful angle, I can probably just remove their access to security lockers, no real reason they should be able to grab stun batons or whatever in the first place. The access on lockers isn't really used for much else.

**Comment by Fox-McCloud** [comment]
I've always viewed brig physician as a mistake to be added. From the start, I figured it would eventually devolve into "100% trusted doctor who does everything for security"---and that's exactly what it's become.

I'd definitely favor full removal, but this idea here is a distant "2nd place" if removing brig phys is just too unpopular.

Medical is meant to be the knee that everyone has to bend to when it comes to receiving treatment---science should absolutely not be held up as the ideal of what a department is capable of in terms of self-sufficiency. Overall--this is a game about paranoia, uncertainty, and distrust--and that's been lessened significantly, over the years.

I strongly support any attempts to return to the level of paranoia we enjoyed during 2013-2014.

**Comment by S-CR** [comment]
Brig physician is a massive violation of the precept that departments should be reliant on the other major departments for their respective specialties. Brig phys exists as something of an insult to medbay players in the same way that a dedicated medbay maintenance tech would be an insult to engineering. Brig physician also stands as tacit approval for the frame of mind that security ought to be megacombat valid-getting juggernauts who exist for the primary purpose of getting antags first and enforcing space law second - after all why would they have a combat medic otherwise?

I understand why, especially with higher population, the role is stressful bordering on self harm. There are problems that need addressed, but what that problem shouldn't permit is a break in the basic set of principles that the station should be more-or-less reliant on the rest of the whole.

**Comment by Shockpoint** [comment]
Honestly, I disagree with this. This is a terrible balance issue for this role. 

We already have a lot of people not trusting each other, and it creates issues all around. This will simply result in the brig phys being roundstart evicted from the brig by paranoid warden/HoS players if they know they can't outright trust the brig phys.

> Brig Phys has turned into Security's private medbay, with full surgery setups, sleepers, precloning and cloner, implantation of all kinds of powergaming implants and so on.

Make it so they can't place these things in the brig, or something. 

> But he'll help perma prisoners escape!
So can other antags, too. How often do they go out of their way to free their buddies in perma? Especially as the Brig Phys would be risking his cover by just opening a bunch of doors and letting a prisoner walk out.

This is a moot point with the easy access out of the brig by the execution chamber. They'd never be seen. It'd more just be a "get out of jail free card".

Simply put, I believe doing this would make more issues rather than fix them. I would instead support a full removal of the role.

**Comment by Carthusia** [comment]
I mean...why would we not want the brig phys to add proper medical equipment to their securitys medbay?

Disallowing that would make little sense.

**Comment by Fox-McCloud** [comment]
It being stressful is unrelated to if they have their own personal doctor, and leaning into that for justification for an unbalanced and terrible design being in play is not kosher.

Playing shaft miner is difficult--they don't get their own doctor. Playing medical when things have gone awry is the single most stressful thing, arguably, in the entire game---but they don't get their own personal guard/security staff to handle everything at their beck and call (nor should they).

Brig phys existing, at all, doesn't lower security's stress level that much--as it doesn't remove the stressors, at all.

Brig phys not being 100% able to be relied upon adds an additional avenue for *attack*, sure---but it's not going to suddenly increase the amount of greytide or number of people who disrespect and harass security *constantly*.

**Comment by Rurik123** [comment]
Best to either remove brig doc completely or keep the mindshield. Hashing it out halfway with removing their trustworthy factor is the worst of both worlds. 

I'm willing to bet most sec players would prefer no brig doc over a potential traitor with that much access in sec. I for one would.

**Comment by MRgaty** [comment]
I agree with rurik, if having brig phys is REALLY that much of a problem and something has to be done about it, better removing it entirely.

**Comment by Aquilar** [comment]
Like a traitor/vampire/changling as brig phys would cause absolute havoc with keeping perma prisoners locked up or alive, or massacre the officers under the guise of helping. It effectively circumvents traditional road blocks to prevent that happening as well as the least checked hiding spot in the station.

Traitor brig phys runs into different problems entirely too, if they not in the brig for long provides of time they will fall under suspicious immediately. Where's other departments don't really care that much. They could end up being valid-ed harder than any other job type just due the paranoia they flick. 

I rather brig phys be removed than let a security department antag exist.

**Comment by Carthusia** [comment]
I don't like the idea of it being removed at all, and i dislike the idea of it being an antag.

Why not just leave the brig doc as is? Seems to be working fine and people enjoy it being around?

**Comment by Mitchs98** [comment]
As Carthusia said, I see no reason to remove it or change it at all. It's sometimes problematic depending on who plays it, but the vast majority of people at best get sleeper, scanner, and a surgery bay set up. At most. Some don't even do that. I see no reason Security shouldn't have their own doctor that they know they can trust when they already have to deal with the stress of everyone on the station possibly being out to kill them, and malpractice bay to revive them when and if they die.

**Comment by Dinarzad** [comment]
Don't really have a dog in this fight, I don't play the role to care if it was removed, but also don't see it as a problem as is either.

But, that said a few notes here.  People have said the job reduces interactivity between Security and other departments, Security no longer dependent on Medicaa, etc.

That's... not -entirely- true as the Brig Phys has to -build- all these machines in the Brig bay to begin with.  To make a super brig-bay set up, a Brig Phys has to either get someone to let him into Tech Storage for boards or get Science to print them, then needs either Science or Cargo for components to build them and if making a Cryo tube, needs Chemistry to get him Cryoxadone.  Additionally will need surgical tools either from a crate from cargo or printed from the autolathe or upgraded tools from science.

If this was all roundstart equipment, I could see it as a problem, but it isn't.  And we similarly don't crack down that hard on other departments for doing the same kind of construct-a-thon, so I am confused as to why we should make an exception here.  Science can build themselves almost anything, and Cargonia is infamous for becoming it's own nation, to the point it's a universal SS13 meme.

If someone is willing to go through the hoops and work to construct this stuff, and people agreed to give them the mats then... well what's the problem? That was inter-department cooperation and roleplay, no? If it must be changed, I don't think making them antag capable is the right decision. It goes contrary to all other security roles and serves as an exception to a generally hard an fast rule that you can trust security, if nothing else, to at least not be antags, competency not withstanding.  A possible alternative would be ID restrictions on some of the medical machinery, such as the cloner.  That has the negative side-effect of malpracticebay being that much worse as random competent crew can't just step in, but it makes people in general dependent on medical for revival, which seems to partially be the desire here.
Again, that's -if- it's changed at all, this is just how it looks from over here sitting on this fencepost.

**Comment by procdrone** [comment]
I have a feeling people saying that brigphys being the only place for sec to heal didn't play the game for at least few years.

Brig bay almost **never** gets any action. players ramp up the upgrades to the bay to be more relevant, and they **still** get ignored.

The only use brigbay ever sees is occasional implant work and healing prisoners. 
Most of the time brigbay is abandoned with the doctor SSD, because he is always sidelined.

The dream brigbay you speak of happens like once in 100 rounds. Its an anomaly, not a norm.

Almost everyone defaults to going to medbay.  Me as well. 
You never know if brigbay is prepared to treat you (likely isnt), and is far away from medbay enough you cannot really take the risk of dying somewhere midway between both.

---

Also, I agree. Security is the most unrewarding and un-fun role to play on the server. doing more to alienate and make people NOT want to play security even more wont have **any** benefit for the server.

I would even suggest a buff to brigbay, but I know with how heads and maints feel here it will never happen.

Either remove, or leave alone.

**Comment by Alex1222003** [comment]
I bougth the Brig Phys because i wanted to play medical withouth stressing out after half an hour into the round. If Sec Officers would look at me funny and eventually only be trusted to give out healing patches, i'd stop playing and go back to playing Maintenance Drone only. In my experience with Brig Phys so far, not many officers ask me to do healing surgeries to them. If they do, it means Medbay is just overwhelmed and/or is known to have antags. They mostly ask me to deconvert prisoners or inplant them.

Besides, Brig Phys does anything but prevent cross department interaction. As Dinarzad said, the fancy setup Physicians have were worked hard for. Pushing around to get meds from medbay, poking an Engineer/Scientist to get that sweet Body Scanner, and begging cargo for the surgery tools. Also, when I play as Brig Phys, i don't just go to Robotics to stock up on inplants. If a Sec Officer wants an inplant, they must get to Robotics themselves. I'm here to shove it in them, this isn't a souvenir shop. How much more department interaction do you want?

In my opinion, if the Brig Phys was no longer mindshielded, i would probabily stop playing it altogether, so i'd rather see it get removed and get my karma back.

**Comment by TDSSS** [comment]
^that's a good catch. Though from what I can see this PR has two against votes from heads so not going to get merged for the time being. If there's an active interest I can make that change but if not I'll probably just close this soon anyway.

**Comment by Kyep** [comment]
This is likely to be closed, as it has objections from two heads.

**Pull request closed without merging**
