### PR TITLE
New Barber HUD icon

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
New barber HUD icon to bring it in line with the style of other members of the service department

## Why It's Good For The Game
Consistency

## Images of changes
Before:
image

After:
image

## Changelog
:cl:
tweak: Changes the barber sec/skill HUD icon to a comb in the service colours
/:cl:

### CODE REVIEW

**Comment by TrashDoxx** [comment]
Oh no, I loved the old icon. It enhanced the comic effect between the absolute uselessness of the role and its exclusivity. And it's more stylish.

**Comment by MRgaty** [comment]
Without colours the icon kinda looks like a wrench

**Comment by TORE01** [comment]
What if you use the old icon and the new background?

**Comment by Christasmurf** [comment]
The alternative option is like a comb kinda icon
image

I just went with this one instead as it more resembled the existing icon and I didn't wanna change it so much

> What if you use the old icon and the new background?

Problem is all the icons (except the original barber one) fit the theme of "solid colour background showing department and then solid colour white foreground to signify rank" which is why I decided against just using the original icon on the new background, I would've done this is more than just the barber had multiple colours for the foreground icon (I'm not counting the SolGov icon as they are not station roles)

**Comment by MRgaty** [comment]
If I have to choose between the two I prefer the alternative option, I think is more identifiable than the wrench looking one

**Comment by lewcc** [comment]
Yeah, I think the comb would be good. It's really tough to tell that those are scissors without the two colors.

**Comment by shmabuu** [comment]
While consistency is good, I don't think either of the icons work very well. Both of the green icons are hard to tell what they are meant to be without knowing what they are meant to be. I don't know what would be better, but I don't think it really needs to change. If it does, comb would work best and it'll be recognized as the barber icon eventually.

**Comment by Christasmurf** [comment]
Alright we finally did it the PR is updated to have the comb icon instead of the scissors I will update the PR shortly

**Pull request closed without merging**
