### PR TITLE
Event Role Feature

### PR DESCRIPTION
**Pull request by Kyep**
This PR lets admins flag a mob as having an 'event role', which is effectively a generic version of all existing antag/special roles.

Why would we want to do this? 
Several reasons, actually:
- To mark a character as an antag for the purpose of attack logs. Yes, we could just set them to be a traitor, but for some characters (e.g: centcom officers) this has amusing results.
- To make a character show up in "check antagonists" so you can keep an eye on them. Again, we could just set them to be a traitor, but that notifies them that they're a traitor, which is possibly not what we want when setting up an event.
- To make a character show up on antaghuds, so that ghosts with antaghud enabled will know they're neither a normal crew member, nor a normal antag.
- To make a character (and their objectives) show up on the end-round score screen.

# Antaghud appearance:
antaghud_eventrole

# Check Antags (admin tool) appearance
eventrole_checkantags

# Round-end score appearance
eventrole_objectives

:cl: Kyep
add: Admins can now flag characters as having an event role, which makes them show up when admins look at the antag list, in admin attack logs, on antaghuds, and on the end-round score screen.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
How about an exclamation mark instead of a question mark? Showing "hey this guy is important! You should keep an eye on him" rather than "oh this guy seems mysterious, he might do something later". I would also maybe make it a more stand-out-ish color than just black

**Comment by Ty-Omaha** [comment]
or E for event

**Comment by Agameofscones** [comment]
What Ty-Omaha said,

**Comment by Kyep** [comment]
@Ty-Omaha @Agameofscones Icon has been changed to a red 'E' on a dark background. Screenshot posted in the PR description. Also includes a view of the traitor panel showing the new event role option.

**Comment by Agameofscones** [comment]
Absolutely excellent

**Comment by Kyep** [comment]
@Agameofscones I don't see it as a problem if Traders board the Cyberiad. They'll stick out like a sore thumb to security as-is, because their job titles are not recognized by sec huds, meaning they'll have a big "?" over their head to all members of security.

**Pull request merged**
