### PR TITLE
Airlocks now smooth with walls and windows.

### PR DESCRIPTION
**Pull request by QuacksQ**
## What Does This PR Do
Title. 
This makes Airlocks smooth with walls and windows properly instead of them not smoothing. Nothing else really.

## Why It's Good For The Game
Looks nicer to have a wall continue properly as it meets an airlock and smooth with it rather than not.

## Images of changes

<details>
<summary>Before</summary>

### Cargo Lobby

</details>

<details>
<summary>After</summary>
 
### Cargo lobby

</details>

## Testing

It ran and it works as intended.

## Changelog
:cl:
tweak: Walls, windows and reinforced walls now smooth with airlocks.
/:cl:

### CODE REVIEW

**Comment by QuacksQ** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

what in the 1984 is this

**Comment by GDNgit** [comment]
> > Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> > Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> > _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_
> 
> what in the 1984 is this

this is just like gejorg orwells book, animal famr

**Comment by Contrabang** [comment]
Actual PRs during april fools? Impossible

**Comment by QuacksQ** [comment]
I linked my account tf do I do now? Wait for my data to be stolen by AA?

**Comment by Contrabang** [comment]
> I linked my account tf do I do now? Wait for my data to be stolen by AA?

Yes, the On Hold tag will be removed whenever a label assigner gives a label to this PR

**Comment by AffectedArc07** [comment]
> I linked my account tf do I do now? Wait for my data to be stolen by AA?

yes

**Comment by QuacksQ** [comment]
> > I linked my account tf do I do now? Wait for my data to be stolen by AA?
> 
> yes


yippee-happy

**Comment by KirbyHasAGun** [comment]
> 

Yipeeeeee

**Comment by KirbyHasAGun** [comment]
> > > I linked my account tf do I do now? Wait for my data to be stolen by AA?
> > 
> > 
> > yes
> 
> yippee-happy [ yippee-happy ](https://user-images.githubusercontent.com/79924768/229347508-6c0a5f43-ef3f-4140-b396-1c53c0e79fc3.gif) [ ](https://user-images.githubusercontent.com/79924768/229347508-6c0a5f43-ef3f-4140-b396-1c53c0e79fc3.gif)

https://user-images.githubusercontent.com/121024620/229347582-0aa1c7c2-1a51-4545-8060-8a85dd879206.mp4

**Comment by KirbyHasAGun** [comment]
https://user-images.githubusercontent.com/121024620/229347603-ba100597-45dc-4f1d-972d-90744bf48243.mp4

**Review by S34NW — COMMENTED** [review]
This could really do with having directional airlock sprites that fit in with the wall profile. I sadly doubt we will ever get ramon walls but the end-vision was for walls and airlocks to smooth but look like they belong. (see: TGMC, Bay)

I'm not sure it's fair to ask you to do this here, but it really needs to be done soon if we're doing this now.

**Comment by TrashDoxx** [comment]
I like what it used to be :(

**Comment by QuacksQ** [comment]
> This could really do with having directional airlock sprites that fit in with the wall profile. I sadly doubt we will ever get ramon walls but the end-vision was for walls and airlocks to smooth but look like they belong. (see: TGMC, Bay)
> 
> I'm not sure it's fair to ask you to do this here, but it really needs to be done soon if we're doing this now.

If you want bay airlocks you're gonna need a completely different wall perspective to make those fit. Short term solution could be to port the airlock sprites from skyrat since those fit in alot better with the current walls.

**Comment by S34NW** [comment]
> > This could really do with having directional airlock sprites that fit in with the wall profile. I sadly doubt we will ever get ramon walls but the end-vision was for walls and airlocks to smooth but look like they belong. (see: TGMC, Bay)
> > I'm not sure it's fair to ask you to do this here, but it really needs to be done soon if we're doing this now.
> 
> If you want bay airlocks you're gonna need a completely different wall perspective to make those fit. Short term solution could be to port the airlock sprites from skyrat since those fit in alot better with the current walls.

I wasn't asking for specifically bay airlocks, but bay-style ones. As in, airlocks that smooth with walls neatly, and look like they belong.

**Comment by QuacksQ** [comment]
> > > This could really do with having directional airlock sprites that fit in with the wall profile. I sadly doubt we will ever get ramon walls but the end-vision was for walls and airlocks to smooth but look like they belong. (see: TGMC, Bay)
> > > I'm not sure it's fair to ask you to do this here, but it really needs to be done soon if we're doing this now.
> > 
> > 
> > If you want bay airlocks you're gonna need a completely different wall perspective to make those fit. Short term solution could be to port the airlock sprites from skyrat since those fit in alot better with the current walls.
> 
> I wasn't asking for specifically bay airlocks, but bay-style ones. As in, airlocks that smooth with walls neatly, and look like they belong.
> 
> Edit: Skyrat use TauCetiClassic doors. They've recently had a wall sprite update, but we use the walls they previously used. I don't really see how they fit any more than our current doors do, so that's not really a great choice.

I'm not a spriter so don't be expecting completely new and original sprites from me please.

**Comment by Sirryan2002** [comment]
how does this look when the airlocks are open?

**Comment by QuacksQ** [comment]
> how does this look when the airlocks are open?

https://user-images.githubusercontent.com/79924768/233749692-7c982c0e-23f4-4c34-867d-b9205b4334b8.mp4

image

image

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Contrabang** [comment]
Can you add the smoothing groups to `/obj/structure/falsewall/reinforced` also?

**Comment by QuacksQ** [comment]
> Can you add the smoothing groups to `/obj/structure/falsewall/reinforced` also?

Has already been done.
image

**Comment by Contrabang** [comment]
> > Can you add the smoothing groups to `/obj/structure/falsewall/reinforced` also?
> 
> Has already been done. image

Ah, sorry. I was looking through the individual commits and missed it. LGTM

**Review by farie82 — APPROVED** [review]

**Pull request merged**
