### PR TITLE
Fixes Stool Pixel Offsets

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes the pixel offsets of all stools.

It will no longer look like stools are up near the middle of your torso, but near the floor and like you're actually sitting on them.

This got messed up a long time ago, and I'm not sure how---all z-levels have consistent pixel offsets on their stools (0,0,0), but the ones on station and on z-level 2 all have an errant offset of +8 Y.

Likely a horrendous copy-paste error that's persisted because of more copy-paste.

Marked as high priority because of mapping conflicts this will cause.

:cl: Fox McCloud
Fix: Fixes on map stools having the wrong offsets, making it look like you're not sitting on them
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
It's at times like these that I get disappointed at mapmerge.

**Comment by taukausanake** [comment]
So when do we get to throw stools again for best bar fights?

**Comment by KasparoVy** [comment]
Or steal them for trade as Vox Raiders?

**Comment by Ar3nn** [comment]
You can totes steal them by disassembling them and taking the metal iirc?

**Comment by taukausanake** [comment]
Yeah but then you're just stealing metal. It's not the same as stealing the chair itself

**Comment by Spacemanspark** [comment]
Why does this have the high priority tag

**Comment by Ar3nn** [comment]
Fox already said it was high priority for reasons he stated above

**Comment by Spacemanspark** [comment]
Shhhh I saw that an hour before you made that comment and deleted it go away

**Comment by Ar3nn** [comment]
No you

**Pull request merged**
