### PR TITLE
Replace Curse of the Cluwne by new spell Banana Touch

### PR DESCRIPTION
**Pull request by datlo**
Curse of the Cluwne can be an amusing spell, but unfortunately not as much for the target. 
It is in practice a permakill for whoever was affected (arguably even more so than desintegrate, at least desintegrated people can theoretically be saved because the brain isn't affected). 
For slime people, it's a straight up kill due to them taking extra brain damage (or so I've been told).

This PR replaces the spell in the spellbook by "Banana Touch".  (Cluwne is still spawnable for adminbus)

Like curse of the cluwne/desintegrate, it is a touch based spell and is applied the same way, however the effects of the spell are different.

- The spell only cost 1 spell point and has half the cooldown, 30 seconds
- The spell stuns the target on hit with a loud HOOOOONK
- Instead of turning the target into a cluwne, the spell forces the target to put on a clown costume/mask/shoes. This clown costume is a standard one, not cursed and can be removed as soon as the target isn't stunned anymore. The target's previously worn items are dropped on the floor; which will also cause them to drop their ID/pockets/etc due to changing jumpsuits.
- The targets get the Clumsy and Comic Sans mutation. These mutations can be removed by mutadone.

While this new spell is obviously less effective if you only look at it from a lethal point of view, it is (I hope!) much more entertaining for both the wizard and the target, and is still useful as a stun for a cheaper cost and lower cooldown; aswell as weakening the target's combat capabilities due to clumsy. Desintegrate is still an option for touch-based instant round ending.

Combine with Staff of Slipping for maximum non-lethal honks!

Sprite by Ionward, thanks again.

🆑
del: Removed "Curse of the Cluwne" from wizard spellbook.
add: Added "Banana Touch" to wizard spellbook, a cheaper, less lethal and honkier spell.
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
The point was for it to be a permakill. This really takes alot of the fun out of it, plus wizard rounds are pretty much high chaos fests anyway so.

**Comment by datlo** [comment]
What's the point of having two spells that do the same thing, with the exact same cooldown, and the exact same method of application then?

**Comment by Mitchs98** [comment]
I don't see how this takes the fun out of it at all. Not by a long shot. If anything, combining this with the staff of slipping can lead to much more interesting things. There really was nothing interesting with the old cluwne spell beyond being able to 'wield admin powers' so to say. If anything it was only fun for the wizard. Disintegrate is much the same way, but at the very least it's easier to come back from it. High Chaos or not, this allows for more diverse wizard play. Which, as was with the Staff of Slipping, a good thing.

**Comment by Aurorablade** [comment]
How do you mean? There dosen't need to be a point just what spell you want to take over the other.

**Comment by Mitchs98** [comment]
Er. Because some people play antags to have fun and do gimmicks as opposed to minmaxing what build/items will be able to murderbone the easiest?

**Comment by Fox-McCloud** [comment]
This misses the fundamental point of Cluwne.

A silly spell that takes out a target but also gives him the opportunity to lethally defend himself, if necessary; both parties gain something in *some* form.

We generally frown on friendly wizards; spells that don't really accomplish anything other than existing for their own sake is...kinda eh.

**Comment by Dinarzad** [comment]
I'm fine with this being ADDED as a spell, see no problems with it. But not replacing Cluwne Curse.
That thing is an SS13 classic, it's been around since olden days, and it won't kill people to suffer it in a round-type that lasts on average like 20 minutes.

Additionally, being able to just take off the clown outfit an fix everything about the spell almost immediately after being hit by it seems kinda... meh to me, but /shrug.  Like I get it, it's for giggles, but 's also ... really lame use of a wizard spell? If the clown outfit was permanent or something would at least have the entertainment value of making the entire crew into clowns.  As it is now you can just casually redress yourself after being hit by it. On a spell with a 30 second cooldown.

**Comment by datlo** [comment]
Just because youre doing a gimmick loadout instead of murderboning doesnt mean youre friendly

Wizards goal is "cause chaos", murder is one way to do it but not the only one

**Comment by Fox-McCloud** [comment]
Occasionally making someone have to get mutadone isn't....exactly what I'd constitute as chaos.

This spell is pretty much just "oh, you have to take some clothes off and put some others on and go to medbay for mutadone". on a high cooldown.

Even for a gimmick, it's pretty lame.

Contrast this with the horsemask, which is also pretty gimmicky (and also almost *never* picked); this has an actual downside to it that can't really be fixed and actively hinders communication without being full out lethal. It's gimmicky, but still fulfills its intended purpose and role.

Something designed more along those lines would be better.

Cluwne being removed is a huge "**no**" form me.

**Comment by taukausanake** [comment]
I kind of thought this was going to be an interesting spell to replace Cluwne curse, not that I want it to be replace just thought it would be interesting. A cheaper, weaker version of cluwne is not interesting and honestly kind of boring. Banana touch sounded like something that would make the cursed slip around instead of walk or run

**Comment by datlo** [comment]
Ill think bout it and come up with a better alternative

**Pull request closed without merging**
