### PR TITLE
Adds russian revolvers to the belts of dead russians

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds a Russian Revolver to the belt of all 'Russian' simple mobs.

## Why It's Good For The Game

~immersion~
I thought it was a funny idea, maybe someone else will too.

## Changelog
:cl:
tweak: All Russian corpses now have a Russian Revolver on their belt
/:cl:

### CODE REVIEW

**Review by SteelSlayer — APPROVED** [review]

**Comment by McRamon** [comment]
i would not call that immersion, i would rather call that "extend the meme" but, well, whatever

**Comment by Necaladun** [comment]
Might be funny for an admin to spawn once, but bit too much of a meme to me

**Review by Kyep — CHANGES_REQUESTED** [review]
Objection.
Russian revolver generates a lot of salt/ahelps, having more of them is a bad thing. Sometimes I question why we even have one in the bar.

**Comment by AffectedArc07** [comment]
Two heads against this, and no one in favour.
It will be closed.

**Pull request closed without merging**
