### PR TITLE
Xenobio heavy containment (Fixed)

### PR DESCRIPTION
**Pull request by Darkmight9**
**What does this PR do:**
Adds a brand new heavy containment pen to xenobio allowing for the study of more dangerous specimens or just to be used as a kill area for slimes. Can be useful for gold slime cores and for admeme events, which one such event inspired this idea.

**Images of sprite/map changes (IF APPLICABLE):**
image

**Changelog:**
:cl:
add: Adds a new heavy containment pen to xenobio. Comes complete with slime killing features and new public turrets to shoot at rowdy specimens. Remember secure contain protect.
add: Public turrets, this turret has been rigged to harmlessly self destruct if destroyed to prevent the theft of the turret's gun.
/:cl:

### CODE REVIEW

**Comment by Mitchs98** [comment]
Throw the RD in. He threatens to fire you, he dies. :dagger:

**Comment by Quantum-M** [comment]
no, @Mitchs98 , throw all of science in there if they begin to get uppity towards the captain/security/station in general.

**Comment by Citinited** [comment]
Can't wait for xenobio to move these to outside the containment pen and set them to neutralise everything

**Comment by Pennwick** [comment]
Repeating my comment before. Giving Xenobio a free kill pen that just requires building one grille to make fully automatic takes a lot of the nuance out of Slimekeeping. Taking some of the live, die, learn, improve out and just lowering the skill ceiling to a trivial level.

**Comment by Ziiro** [comment]
1) Plasma glass is excessive
2) Turrets are excessive (If they want them, they can build them)

Most "modern" stations just have a cold room that kills slimes and a different room for heavy containment.
dreamseeker_2019-02-13_11-08-54

**Comment by variableundefined** [comment]
We believe turrets and plasma glass containment is unneeded. And we don't believe that the layout is exactly good either. As a result, the PR will be closed.

**Pull request closed without merging**
