### PR TITLE
Replace most (if not all) output << operators with to_chat(user, message)

### PR DESCRIPTION
**Pull request by tigercat2000**
Currently, to_chat is literally just a proc that does user << message.
But it'll let us do output modification in the future, especially for
something like Goon's HTML chat.

Big thanks to @PJB3005 for his to_chat script, see
https://github.com/d3athrow/vgstation13/pull/6625 for more details.

@TheDZD @Fox-McCloud Going to have to ask you two to try to make this quick, it touches basically every file, it'll merge conflict at the thought of dropping a hat.

### CODE REVIEW

**Comment by PJB3005** [comment]
Just saying but my script has a ton of places where it screws up.

You'll have to go through this and fix all the screwups (unless you already did):
* savefiles
* regular files
* images
* sounds
* probably more things that I can't think of off the top of my head.

**Comment by tigercat2000** [comment]
@PJB3005 
 - the maploader is the only thing we have that uses savefiles, i just reverted all changes to it because maploader
 - pretty sure i got all of the files
 - not sure what you mean by images, normally those are handled by browse_rsc()
 - sounds are probably fine to keep for now

**Comment by PJB3005** [comment]
@tigercat2000 with images I mean `/image` datums.

They're used (for example) in the antag icons above people's heads in say nuke ops.

**Comment by tigercat2000** [comment]
@PJB3005 ah, i think our huds are handled here https://github.com/ParadiseSS13/Paradise/blob/master/code/datums/hud.dm#L64-L69

**Comment by PJB3005** [comment]
@tigercat2000 that was 1 example.

**Comment by Tastyfish** [comment]
Every instance where it changes sound output lines is going to be screwed if you actually make to_chat do anything different.

**Comment by tigercat2000** [comment]
@Tastyfish it would work fine even with goon chat, provided there is an
```
if(istext(second_arg))
   goon chat stuff here
else
   first_arg << second_arg

**Comment by Tastyfish** [comment]
@tigercat2000 Yes, that would technically work, it's just the name doesn't make much sense if somebody's going back and reading `to_chat(M, 'sound/misc/notice1.ogg')`.

**Comment by tigercat2000** [comment]
@Tastyfish It would be a really big pain in the ass to actually find all of the sounds sent to the client at this point. There are at *least* 20 free-floating, and a completely untraceable amount stored in variables.

**Comment by tigercat2000** [comment]
fixing the damn sounds

**Pull request merged**
