### PR TITLE
Makes additions to world.Topic() to make the in-game PR announcer work

### PR DESCRIPTION
**Pull request by TheDZD**
Don't have a preference for this due to lack of a local SQL server.

:cl: TheDZD
rscadd: Adds world.Topic() handling so that users are notified in-game when pull requests are opened, closed, or merged on the Github repo.
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
Closing and re-opening to test the webhook.

**Comment by TheDZD** [comment]
Looks good, meaning that that inline changelogs should function now as well.

**Comment by TheDZD** [comment]
@ParadiseSS13/paradise-maintainers You can yell at people to put changelogs using the format in the OP here.

**Comment by MrStonedOne** [comment]
````
Format:

:cl:
prefix: text
prefix: text
prefix: text
/:cl:

Placed in the body of the PR.

You can even add the name to file it under by adding it after the :cl: tag (it will default to your github username if omitted)

Prefixes are directly from the changelog system, see the example changelog file in html/changelogs for more info.

Example: (taken directly from the example.yml file)
:cl: N3X15
rscadd: Added a changelog editing system that should cause fewer conflicts and more accurate timestamps.
rscdel: Killed innocent kittens.
/:cl:

Once your PR is merged, the website will get a notification of such and add a new commit adding the changelog file.

You can also use add as a shortcut for rscadd, del for rscdel, and fix/fixes for bugfix.
````

**Comment by KasparoVy** [comment]
Just to confirm: Every PR after this should be using inline changelogging?

**Comment by TheDZD** [comment]
@KasparoVy Yup, it's much simpler to do, although the effect is the same.

**Comment by tigercat2000** [comment]
@TheDZD now i fully intend on making yml files just because you said that

**Comment by KasparoVy** [comment]
@TheDZD Super duper handy! Saves the trouble of having to push an extra commit just to make sure the name of the changelog file is correct lol

**Pull request merged**
