### PR TITLE
Ports Accelerator Laser Cannon

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports: https://github.com/tgstation/-tg-station/pull/16470 by @KorPhaeron

A rework of the laser cannon: The Accelerator Laser Cannon

Instead of the laser cannon being a super pew pew laser gun (that does 2x damage to , it now does a pitiful amount of damage, a point blank, but does more and more damage the further and further the projectile travels.

Things not impemented:
- The projectile getting bigger
 - Our pixel projectile system uses transform, which makes the projectile getting larger/smaller a no go for this...sadly

:cl: Fox McCloud
tweak: Updates the laser cannon to be range based: the further its projectile travels, the more damage it does. Base damage greatly reduced.
/:cl:

### CODE REVIEW

**Comment by QuinnAggeler** [comment]
Wouldn't this make more sense for the sniper rifle?

**Comment by taukausanake** [comment]
@QuinnAggeler Not for a laser weapon I would think. I dare not think of the Science or Bluespace behind anything getting more powerful the longer it travels however

**Comment by Fox-McCloud** [comment]
The problem with the laser cannon is that it's not niche or a sidegrade...it's just a boring laser gun that does 2x damage compared to regular lasers. 

This makes it into a side grade that nuances gameplay around how you use it--you have to maintain a sensible range (and keep maintaining it) for it to be good. You can't just walk up and start point-blanking someone with it for insane damage.

**Comment by QuinnAggeler** [comment]
Still, when I think cannon, I think "big and slow," whereas this mechanic sounds absolutely perfect for a sniper weapon.

How does this interact with turrets? IIRC certain ones, like on the crashed ship away mission, use laser cannons instead of eguns. Though, having looked at turret code recently, they seem to brute force projectile selection instead of referring to the actual projectile of the weapon loaded, so they'll probably still use the heavy laser projectile. Still, might be good to test that, just to be sure.

**Comment by mrturkeytoe** [comment]
You could just give the base laser cannon a cooldown between shots so people still need to keep their distance. cause dealing insane damage is kind of the point of the laser cannon.

**Comment by QuinnAggeler** [comment]
Well, it can technically do even MORE damage now, provided you shoot from more than 5 tiles away.
~~Now add this to xray lasers. _You know you want to_~~

**Comment by mrturkeytoe** [comment]
How quickly does the damage scale for range?

**Comment by QuinnAggeler** [comment]
7 more damage with every tile

**Comment by Fox-McCloud** [comment]
+7 per tile travelled.

**Comment by QuinnAggeler** [comment]
So, at usual engagement distances, you won't notice too much of a drop

**Comment by mrturkeytoe** [comment]
I am a little worried this'll make xenos even more robust and insta-win if they know how the game works at all since laser cannons were one of the most decent weapons against them and they usually fight in close quarters, but whatever, i suppose we'll see.

**Comment by mrturkeytoe** [comment]
I suppose 5 tiles between you and the target gets you back to 40.

**Comment by QuinnAggeler** [comment]
> Well, it can technically do even MORE damage now, provided you shoot from more than 5 tiles away.

**Comment by mrturkeytoe** [comment]
Yeah it has the potential in certain circumstances to be considerably better.

**Comment by Fox-McCloud** [comment]
Yes, that's the design goal behind it---for more nuanced gameplay, not just "pew pew, this is better in all circumstances, pew pew".

**Comment by QuinnAggeler** [comment]
I think we ought to do something similar with the sniper rifle, which currently works rather like a cannon (slow, high damage, low capacity).

**Comment by ProperPants** [comment]
Well, snipers shoot bullets, which are "static," so to say. You could bullshit up some explanation for the laser doing more damage with distance, but how would you create a logic for snipers doing that? Maybe if an energy-type ammunition existed, it could fill this function for a sniper, but IMO snipers shouldn't have this function at all times.

**Comment by KorPhaeron** [comment]
It's a bullet with tiny rockets in it or something equally silly obviously

**Comment by Fox-McCloud** [comment]
Likely because I didn't think it through and I also wasn't aware of @KorPhaeron overall design philosophy decision by making tweaks to R&D (and its items), back then.

**Comment by Fox-McCloud** [comment]
oops >.>

**Comment by QuinnAggeler** [comment]
It's okay, I've done that too

> Well, snipers shoot bullets, which are "static," so to say. You could bullshit up some explanation for the laser doing more damage with distance, but how would you create a logic for snipers doing that? Maybe if an energy-type ammunition existed, it could fill this function for a sniper, but IMO snipers shouldn't have this function at all times.

We don't have a bullet sniper rifle though, we only have a laser one.

**Comment by TheDZD** [comment]
Damage just scaling linearly might be a bit too powerful if you shoot spray it down a hallway, it should probably have some cap or have it increase at a decreasing rate.

**Comment by ProperPants** [comment]
>have it increase at a decreasing rate

I don't know how the codebase handles formulas, but a logarithmic function would perfectly meet that criterion.

**Comment by Fox-McCloud** [comment]
cap the projectile's damage at `100`

**Comment by taukausanake** [comment]
So we can't melt something from across the map? Lame, but I guess some sanity would be needed

**Comment by Fox-McCloud** [comment]
*shrug* I don't think it's a big deal because of pixel projectiles making lining things up very difficult (because of drift), but eh, 100 is still a lot, I suppose.

**Comment by Necaladun** [comment]
Yes, cap for damage is always needed. Someone will always find a way around it.

Cannon seems about right - seem like something that would be used in space craft and the like over those ranges. Maybe name it "portable laser cannon" or the like? Give the idea that R&D has miniaturized something that was formerly not portable.

**Comment by QuinnAggeler** [comment]
> Give the idea that R&D has miniaturized something that was formerly not portable.

I like this idea

**Pull request merged**
