### PR TITLE
Legions Skulls Block Shots

### PR DESCRIPTION
**Pull request by 13spacemen**
## What Does This PR Do

Legion skulls now block mob movement and block shots. So you no longer have to pinpoint accurately melee them which is impossible on Help Intent; and you don't have to click on their tile specifically. You can click behind them and they will block the shot and get hurt.

## Why It's Good For The Game

Legion skulls are incredibly lethal, Paradise is the only server where they are this insane to fight. On all other servers you can just shoot behind the legion skulls to kill them.
Also legion skulls have a swarming component so what happens is 3-4 skulls will all swarm you and they're all on the same tile too so you can't even tell if it's 1 skull or 5 and you end up getting critted in 1 second
Now that they block movement they are easier to deal with. You can still die to them easily but they are less BS to fight. It's still harder to fight them on Para than other servers but it's much more fair

Fixes https://github.com/ParadiseSS13/Paradise/issues/13706
I guess

## Changelog
:cl:
tweak: Legion Skulls now block movement and shots. You can now also click behind legion skulls with your PKA to kill them.
/:cl:

### CODE REVIEW

**Comment by moxian** [comment]
The ore box sprite is completely unrelated to the skulls change; these two should ideally be two independet PRs.

**Comment by 13spacemen** [comment]
@moxian Yeah I know it's unrelated but I decided to put it in since every other server is using this sprite I thought it would be uncontroversial
I didn't sneak it in I noted it in the PR and commits

**Comment by dearmochi** [comment]
> Pull requests should be atomic; Make one commit for each distinct change, so if a part of a pull request needs to be removed/changed, you may simply modify that single commit. Due to limitations of the engine, this may not always be possible; but do try your best.

Please make sure to follow our [contribution guidelines](https://github.com/ParadiseSS13/Paradise/blob/master/.github/CONTRIBUTING.md#guidelines-2).

**Comment by Sirryan2002** [comment]
Legions are easy enough to kill already, part of the lavaland experience is that it has some difficulty and threat of death, debuffing arguably one of the easiest mobs to kill on lavaland isn't something I think would be a positive change to balance/fun.

**Comment by matttheficus** [comment]
Legions are quite literally the easiest non-mega critter to deal with, and I play with a KC. Simply dont run head-first into them and get swarmed, bait them on-by-one. Dont see a reason to nerf them especially when they drop a legion core.

**Comment by 13spacemen** [comment]
When Lavaland was merged legions were like this PR
It was a later PR that changed legions to be non-dense and to not block mob movement
This PR just restores legions density back to how it was when Lavaland was added

**Comment by Xsingular** [comment]
At the same time, you should be prioritizing the Legion which is spawning all these skulls, because it can make more skulls faster than your KA can shoot them down.

Not to mention, that the Legion in question also has a "run away" behavior when aggro'd so it's going to be constantly making distance from you, with its skulls closing any venue of approach or retaliation.

I can easily see Legions becoming extremely hard to handle after this, especially with Para movespeed.

**Comment by 13spacemen** [comment]
None of the mining mobs will be an easy kill on Para due to the movespeed
The problem with current legion skulls is that you have to pinpoint click your mouse on the exact edges of the tile they are on to shoot them
It's very awkward, you shoot right through them.

Yes currently it's easier to target the legion spawning the skulls but as you said

- they run away
- if you do kill the legion, you're still being attacked by 5 skulls who will crit you before you can even get to the legion core

This PR isn't as big a balance change as people think it mainly makes it so you can actually shoot the little skulls and makes it so they don't pile up on 1 tile

**Comment by Hematoma** [comment]
Feel free to correct me if I'm wrong but I think legion skulls are the only stackable hostile mob in the game. Space bees, Syndicate-bees, Feral-cats, and man-hacks all seem to be dense and non-stackable. Yes you can prioritize the legion if you have a Ka, but if your using anything else it becomes a lot harder. The legion skulls do enough damage that the average miner cant ignore them. The legion can produce skulls faster than the Ka can kill them with shots alone, but with shooting/melee it cannot.     
    
    The real issue is having multiple able to attack you at one time. If you are not able to take down the legion fast enough and don't deal with the skulls one can quickly become 3-5 all attacking you at the same time from the same tile. There is no disengaging away from this as they are very fast, and with 3-5 you will be quickly slowed from the damage if you are not already. If there are multiple legions they become impossible to fight at the same time as you can rapidly become swarmed with 10 skulls attacking you at the same time probably from the same tile which will be impossible to deal with before they deal with you. These legion can also be easily weaponized via a miner with an E-mag, who can collect as many legion as he can well hold, proving a nightmare for security.
 
    Currently I think non dense Legion skulls only adds to the Ka meta as you can melee the skulls while shooting the Legion which all of the other mining tools do not have the ability of doing. Making Legion skulls dense would allow non-Ka users to deal with them one at a time in the case their is only one Legion, and allow the ability to disengage from the fight if there is more. For miners, other Lavaland roles, as well as security officers should they end up on the station I think this will be a step in the right direction.

**Pull request closed without merging**
