### PR TITLE
Adds more Vox helmets and ERT suit sprites

### PR DESCRIPTION
**Pull request by shazbot194**
This PR was partly made for Spartan who wanted me to start working on species suits, and this was meant to be they the first part, but a lot of the work for Vox a at least appears to have already been done.

So this PR does two big things, both relating to sprites. The first is add some missing helmets and replacing one. These are all the bio-hoods and bombsuit helmets.

cough_cough_skreee

For the most part, these sprites did not exist before me adding them, however, there is the exception of the science bomb suit.

bomb_reeeeeeee2

I started making my sprite before I knew this was already in. I personally think that my sprite is better, however I can change it back and leave my sprite in, or remove it altogether. However, this PR does add in the white bombsuit and security bombsuit helmets, with matching collar for the latter.

The second thing this PR does is add in ERT suits for Vox. Vox already cannot hide in ERT suits since they have such a differently shaped sprite, so this should not alter balance. I say this because of PR #7990, which was denied over Vulp getting ERT suits. However, PR #8381 did add in a drask suit, and #7675 added in Grey ERT helmets, so please do consider this. If this part of the PR will cause the rest to be denied, I am willing to remove it, but I will still fight to keep it in.

reeeeeeeee2

### CODE REVIEW

**Comment by taukausanake** [comment]
inb4 the ERT sprites are removed because reasons, but I like it

**Comment by Regen1** [comment]
ERT sprites causes bloat, because ERT will always be human

**Comment by shazbot194** [comment]
But isn't it more then possible to have a Vox steal an ERT suit?

**Comment by Regen1** [comment]
True, but that's also true for every other species, I think we declined a PR in the past of adding tajaran / vulp specific suits before, if so then I don't see why this would go through.
I could be wrong though, so honestly I'd look for that PR to see how this would go.

**Comment by shazbot194** [comment]
You should read the PR, I mentioned that PR, and another one that added in drask ERT suits, that got accepted.

**Comment by Regen1** [comment]
Must be the fact that I haven't finished my morning coffee.

I rest my case, I don't see the need to make special ERT suits for every species.

**Comment by shazbot194** [comment]
[I will point to this bit of code I have been referencing, Drasks already have their own suit](https://github.com/ParadiseSS13/Paradise/blob/604f26f2ecec8b8a2e5d878b9e2e27ade2e17618/code/modules/clothing/spacesuits/ert.dm#L46) and [if you look up, Greys have their own helmets](https://github.com/ParadiseSS13/Paradise/blob/604f26f2ecec8b8a2e5d878b9e2e27ade2e17618/code/modules/clothing/spacesuits/ert.dm#L14)

**Comment by Birdtalon** [comment]
>I rest my case, I don't see the need to make special ERT suits for every species.

Just to respond to that, I like the idea because it adds a lot more variety to what you see on your screen, as long as the suits maintain each species' unique and distinguishable silhouette

**Comment by KasparoVy** [comment]
Oh my God yes man these sprites are sick. The ERT zuits are utterly fantastic.

**Comment by uraniummeltdown** [comment]
@shazbot194 Sprites are good, but I kind of prefer the older bombsuit sprite. I like the prominence of the beak and how the helmet is more bulky, the newer bombsuit looks like a mummy
Also if you're ever up for it, doing Vox sprites for the Syndicate softsuits would be great, since right now Vox can't wear them due to a lack of sprites

**Comment by shazbot194** [comment]
I think someone already made the sprites for them, they were just missing the full spectrum of colors, but when I get time, I would be happy to bring them back, with all the colors.

**Comment by SkeletalElite** [comment]
I occasionally get the chance to use ERT suits as a vox and would appreciate them not being glitchy as fuck, personally

**Comment by shazbot194** [comment]
> However, if we do - The red sprites are way too bright, they come out as flatly colored because they're such a bright color with the highlights being somewhat fucky.

I'll look into it when I get a chance to, finals and all that fluff, but they should be just as bright as the current ERT suits, as I quite literally used the same colors, but something easily could have happened to make them different.

**Comment by KasparoVy** [comment]
The brightness is 'cause of the additional colour in the shoulders and the legs. Perhaps they could have dark bands/seams to break the pattern? *shrug*

Looks great to me as is, but that'd probably address the criticism.

**Comment by shazbot194** [comment]
going to see if opening and closing this PR makes travis work

**Comment by shazbot194** [comment]
There it goes

**Comment by bigfatbananacyclops** [comment]
Amazing sprites.

**Comment by shazbot194** [comment]
After talking to Tiger, new, slightly darker suits
security_ree

**Comment by tigercat2000** [comment]
New decision made: Spritesheets for every suit are fine, while gross, because it's the way it's gotta be.

**Pull request merged**
