### PR TITLE
Camera Update+Camera Bugs

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Camera Update 2.0

Adds in TG's camera code, which effectively is the same, but with a few differences:

- Can't go around killing every single camera in 1-2 seconds with a pair of wirecutters
- Can upgrade cameras with various devices when the panel is open (no new camera construction required for this process anymore):
 - Analyzers grant the camera X-Ray Vision
 - Proxy sensors grant the camera motion sensitivity
 - Plasma sheets grant the camera EMP proofing
- Each camera on the first z-level has a 3% chance of starting off deactivated; gives engineers and borgs something to do and prevents "oh noes obviously someone is up to no good because camera is cut" meta nonsense.

- Adds in the camera bug
 - Camera bug is an ultra cheap traitor device (2 TC) that can be used to place bugs on on various cameras; you can upgrade it with a number of devices to have unique effects, ranging from tracking of people, to camera EMPing--to tapping into the entire station's camera network.

Other
- Kills off the old camera bug+handheld TV monitor.

### CODE REVIEW

**Comment by Earthdivine** [comment]
In before the RNG decides "fuck the AI" and has every camera off.

On topic, I'm glad to see not only the camera bugs coming back but them ACTUALLY WORKING this time. And the switch from carrots to analyzers is great too.

**Comment by Fox-McCloud** [comment]
@Earthdivine 

After some testing, in practice, it only really knocks out 1-3 cameras

In either case, I think you'll like the camera bug; the only one was limited use (this one is unlimited) and only let you see specific cameras you bugged---you can upgrade this camera bug's bug type to get different effects--it's really really cool and powerful for a 2 TC item.

**Comment by fj45** [comment]
"Can't go around killing every single camera in 1-2 seconds with a pair of wirecutters"

Its still possible to kill them with a screwdriver+wirecutters right?

**Comment by Fox-McCloud** [comment]
@fj45 

Of course! I have no problem with that; that's *disabling* a camera; you just have to re-open the panel and use wirecutters again to fix it.

On live you can walk up to a camera and hit it with anything that does 5 or more damage and you can break the camera; once it's broken, there's no way to repair it other than building a new one from scratch--so staff assistants can literally herp derp destroy every camera, permanently without even a hair of effort.

**Comment by fj45** [comment]
Ah, yeah that sounds crap.

(although very, very useful to a certain someone with a fireaxe...)

**Pull request merged**
