### PR TITLE
Fixes Collar Runtime (Resolves #5043), Fixes North Dir. Vulpkanin Patch Sprite

### LINKED ISSUE #5043: Icon Generation is Runtimming like mad
@KasparoVy 

Been getting some nasty runtimes with icon generation when wearing certain items.

When I put the mining hardsuit on as a vulp, I got this runtime error:

```
Runtime in ,: bad icon operation
   proc name: New (/icon/New)
   usr: Onnsamlichuk Nictzch (foxpmccloud) (/mob/living/carbon/human)
   usr.loc: The floor (172,78,5) (/turf/simulated/floor/plasteel)
   src: /icon (/icon)
   call stack:
   /icon (/icon): New("icons/mob/species/vulpkanin/co...", null, null, null, null)
   Onnsamlichuk Nictzch (/mob/living/carbon/human): update collar(0)
   Onnsamlichuk Nictzch (/mob/living/carbon/human): update inv wear suit(1)
   Onnsamlichuk Nictzch (/mob/living/carbon/human): equip to slot(the mining hardsuit (/obj/item/clothing/suit/space/rig/mining), 13, 1)
   Onnsamlichuk Nictzch (/mob/living/carbon/human): equip to slot if possible(the mining hardsuit (/obj/item/clothing/suit/space/rig/mining), 13, 0, 1, 1)
   Onnsamlichuk Nictzch (/mob/living/carbon/human): equip to appropriate slot(the mining hardsuit (/obj/item/clothing/suit/space/rig/mining))
   Onnsamlichuk Nictzch (/mob/living/carbon/human): quick-equip()
```

### PR DESCRIPTION
**Pull request by KasparoVy**
Collars still fully function (tested by wearing a Sec bombsuit as a Vox and as a Human, the correct collars rendered) and wearing a hardsuit as a Vulp (the situation provided in the bug report) and it didn't cause a
runtime.

Fixes #5043.

Also a sprite fix. Noticed an issue with the Vulpkanin patch facial hairstyle when testing the mining hardsuit.

_Vulpkanin 'Patch' facial hair style's north direction sprite hanging a pixel too far to the right._
vulpear

_After the fix._
vulpearfix

:cl:
fix: Wearing a suit will no longer cause runtimes due to the way suit-collars are handled.
fix: The north direction sprite of the Vulpkanin 'Patch' facial hair style won't hang a pixel off the head anymore.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Pictures of the Vulp ear fix coming momentarily.

**Comment by Spacemanspark** [comment]
I was actually considering making a PR to remove wearing collars entirely, and leave them for pets only.

**Comment by KasparoVy** [comment]
This isn't collars in that sense, it's collars as components for suits-- like the collar on the Security bomb suit. I used that as an example because it's the ONLY suit-collar in the game (not the pet collar)

**Comment by Spacemanspark** [comment]
Aah, I shouldn't read PRs while I'm tired

**Pull request merged**
