### PR TITLE
Cyberiad: Fixes some minor issues

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Perma no longer has a pipe missing a vent.
Custodial office no longer has a duplicate pimpin'ride key.
Maintenance old television type is now correct.
## Why It's Good For The Game

Fixes https://github.com/ParadiseSS13/Paradise/issues/21768
Fixes https://github.com/ParadiseSS13/Paradise/issues/21113
Fixes the maintenance television being of the wrong path, causing its screen to change to the entertainment monitor one once a video camera was activated.
## Images of changes

vent

key

television

## Testing

- compiled and verified the changes as one can see over images of changes
## Changelog
:cl:
fix: Cyberiad: perma no longer has a pipe missing a vent
fix: Cyberiad: custodial office no longer has a duplicate pimpin'ride key
fix: Cyberiad: maintenance old television type is now correct, no longer having issues with its screen
/:cl:

### CODE REVIEW

**Review by Git-GoR — APPROVED** [review]
Looks good. I really hope that varedit of the TV was made before the actual item existed.

**Comment by Henri215** [comment]
> Looks good. I really hope that varedit of the TV was made before the actual item existed.

https://github.com/ParadiseSS13/Paradise/pull/20224
Fixed by me but reverted to a varedited item by the "recent" cyberiad map PR

**Comment by Henri215** [comment]
image

I dont remember doing that 0-0

**Comment by Henri215** [comment]
image

New timeline: https://github.com/ParadiseSS13/Paradise/pull/22302

**Pull request closed without merging**
