### PR TITLE
Removes moonshine from Nethiafins donator item

### PR DESCRIPTION
**Pull request by Regen1**
Strongest alcohol in the game not counting ethanol.

Was brought up with the heads, still got merged for some reason, this amount of alcohol will do a lot of damage to a normal human

Image of damage

If @AndriiYukhymchak want's to suggest something else then perhaps it can be discussed, as of now this is the best option.

### CODE REVIEW

**Comment by fludd12** [comment]
@Regen1 Perhaps instead lower the amount of moonshine in the bottle to a non-damaging amount, and add to the flavor text that someone seems to already have taken a few swigs.

**Comment by Krausus** [comment]
Instead of emptying the bottle, you could just make a moonshine fluff subtype with a reduced potency.

**Comment by Lady-Luck** [comment]
You could also have it contain moonshine and another, weaker alcohol to dilute it. Or water.

**Comment by Jovaniph** [comment]
I agree with the removal. We can't be pack rats. That's the problem with Paradise we add stuff but cry when things get removed.

**Comment by Lady-Luck** [comment]
Uh. The item isn't getting removed. It's a fluff item.

It's just the reagent contents being changed.

**Comment by Jovaniph** [comment]
I didn't say item

**Comment by Lady-Luck** [comment]
...What does that have to do with being pack rats then?

**Comment by Jovaniph** [comment]
probably a misunderstanding?

**Comment by AndriiYukhymchak** [comment]
I see the point...
In my defence, I requested it to be availible only on security roles (blueshield, HoS, Captain, etc).
If it is against guidelines, then remove it. I will come up with better item with less functionality

**Comment by Regen1** [comment]
@AndriiYukhymchak One of the issues is that moonshine is 0.8 in alcoholic percentage (in the code anyways), so it's incredibly strong when you give someone 100 units.

Having it filled with 50 units of something that's not as strong could be a good compromise.

**Comment by AndriiYukhymchak** [comment]
I'm okay with it being 50/50 water

**Comment by Regen1** [comment]
50/50 water won't do you any good i'm afraid, it'll still give you 50 units effective of moonshine, and adding water to it will slow don the process of you drinking it, but not "remove" the side effects of drinking moonshine.

If you are absolute that you want moonshine, then we have to reduce it to such an amount that it doesn't incur any real slide effects (such as bury vision, vomiting etc), which in turn means that you'll not get that many units of it.

**Comment by Fox-McCloud** [comment]
The consensus on this is that it being available on a limited job set and being Vodka is ok, but not moonshine.

@Regen1

**Comment by AndriiYukhymchak** [comment]
Yeah... Let's remove it. I will come up with a better item that caused less
controversy. Regen, can you just remove it for now. I allow usage of this
sprite for future cases

**Comment by Fox-McCloud** [comment]
Alrighty, well, if you don't want it anymore/want to make something new.

**Pull request merged**
