### PR TITLE
[Sprites]Cultist rave AkA 'Fethas Stop making pull requests!'

### PR DESCRIPTION
**Pull request by Aurorablade**
THIS ONE IS SIMPLE I SWEAR!!
Okay i was browsing some sprites one day, trying to find neat examples of things..and i saw 'hey VGStation has cult construct glows!'

So i was all 'HEY WE NEED CONSTRUCT GLOWS' cuase there is nothing worse then wandering in the dark and seeing a glowing red objecting coming STRAIGHT AT YOU!

space station 13 2015-07-11 221616
space station 13 2015-07-11 221549
(the harvester was missing in the dark shock...it was an LoS issue with one of the behemoth mobs)

'But Fethas, Those glows were on the mob dmi on VG!'

....Mob dmis conflicts make me cry..i can move them back to the mob dmi..but conflicts make me cry.

(PS:VG did some rather interesting updates to thier cult gamemode flow...if anyone wants to use it..later..i mean now that we almost have the blob overhual...the flow is outlined in comments here https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/gamemodes/cult/cult.dm)

### CODE REVIEW

**Comment by KasparoVy** [comment]
That looks absolutely killer. Gr8 port m8 8/8

**Comment by Fox-McCloud** [comment]
Bay did this better: https://github.com/Baystation12/Baystation12/blob/dev/code/modules/mob/living/simple_animal/constructs/constructs.dm#L239 

It glows and emits a tiny amount of light.

**Comment by Aurorablade** [comment]
@Fox-McCloud THANK YOU! i was gonna add a light to it..but i couldn;t get it right!

**Comment by Fox-McCloud** [comment]
@Aurorablade 

No problem; also recommend moving the overlays to the same file as the constructs, for a more logical/ease of access thing for future coders/spriters.

**Comment by Aurorablade** [comment]
And i see what they did too! I did not think of the negative value!

**Comment by Bad-Apple797** [comment]
I thought they were gonna have negative light values, which would fit with other cult powers and make their glowing more prominent

**Comment by Aurorablade** [comment]
yeah the effect is kind of neat, its like they are making thier own shadow and oooo spoopy.

**Comment by veganzombeh** [comment]
Can we get a screenshot of them emitting light? I feel like it would detract from the effect.

**Comment by Aurorablade** [comment]
Its actually an INVERSE light, almost, probaly juse due to the color, its like casting its own shadow
heres shots of various lighting, did my best:

space station 13 2015-07-14 200102

space station 13 2015-07-14 200127

space station 13 2015-07-14 200151


space station 13 2015-07-14 200206

space station 13 2015-07-14 200239

space station 13 2015-07-14 200315

**Comment by Fox-McCloud** [comment]
don't recommend this being named update_icon() and I'll tell you why.

That proc is used by a lot of mobs for various things; by redifining it, you're going to override what it does, normally, for hostile/simple animals.

**Comment by Aurorablade** [comment]
yeah i was copying the other file there, will name it UpdateGlow or some such.

**Comment by tigercat2000** [comment]
@Fox-McCloud It was actually updateicon, not update_icon, but whatevs.

**Pull request merged**
