### PR TITLE
Replaces all var/const with #define

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
This PR kills off most instances of `var/const` with `#define`. The reasons for doing this are many

- BYOND constants are awful
- Use of defines is convention for this code (And many others)
- Defines dont eat extra memory when the server is running
- Defines process faster than constants

## Why It's Good For The Game
The code quality will increase, as well as the server performing slightly faster with lower ram usage.

## Changelog
:cl: AffectedArc07
tweak: Killed off a lot of var/const for #define in the game code
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
@AffectedArc07 @Fox-McCloud 
I testmerged this today for one round at Fox's request.

Issue 1: admin log got spammed with this at regular intervals:
ADMIN LOG: UI DATA CALLED
ADMIN LOG: UI DATA 424
ADMIN LOG: UI DATA 451
ADMIN LOG: UI DATA 465
ADMIN LOG: UI DATA CALLED
ADMIN LOG: UI DATA 424
ADMIN LOG: UI DATA 451
ADMIN LOG: UI DATA 465

Issue 2:
Using the 'FILL' map mode with a welding tank resulted in the entire zlevel being filled with tanks, not just the shuttle area. Possible bug where build mode fill tool doesn't get the correct boundaries.

Provided runtime log for comparison:
aa_runtime

**Comment by AffectedArc07** [comment]
I don’t recall adding any message admin lines but they are written in the way that I write them so I’ll investigate in a bit

**Comment by AffectedArc07** [comment]
One issue fixed, but I was unable to reproduce the issue of fill mode filling the entire Z level
image

**Comment by shawnhind** [comment]
When this was test merged I was the CE for the round.  I used the engine delivery device to order the tesla.  In the chat log it had the normal message of "Engine delivery detected: Tesla" or however it's worded.  Then right as I was getting ready to turn on the PA, noticed it was a tesla.  I ahelped but the admin got annoyed at me for not noticing until containment was up and I'm not sure if he was realizing that I was trying to point out that I thought it was a bug so I'm not sure if he already reported this or not.  Sorry if this is already known.

**Comment by AffectedArc07** [comment]
Will test now to see if thats reproducable

**Comment by shawnhind** [comment]
@AffectedArc07 I looked through the PR out of interest and couldn't find any values being changed related to engine types.  I'm starting to doubt myself on this so am interested in what you find.

**Comment by AffectedArc07** [comment]
image
Appears to work fine for me

**Comment by shawnhind** [comment]
@AffectedArc07 was curious so I ended up testing this myself as well to see if I can reproduce it and could not.

**Pull request merged**
