### PR TITLE
TG Supermatter Port

### PR DESCRIPTION
**Pull request by Fox-McCloud**
There's been some issues with the supermatter of late...namely that it runtimes, doesn't function well with LINDA, etc.

In any event, @ZomgPonies seemed alright with getting the base supermatter into a workable state with LINDA/our codebase, then implementing the other effects (supermatter walls/shards/etc) at a later date (if I've misinterpreted what you said, Ponies, I apologize, but that seems to be what you indicated). Either case...

Implements TG's Supermatter

- This is basically the same as our supermatter, but is better suited now that we have LINDA
 - Technically speaking there's just a supermatter shard instead of a full supermatter now--functionally, having two is pretty pointless.
- Some features have been lost--namely the supermatter walls/effect spreading stuff
 - These can be re-added in the future when the supermatter is more relevant than it currently is; for now, having a functional, non-runtiming supermatter is more important.
- Better logging and notifications for admins than the current SM
- Doesn't fill out the runtime logs like crazy

Related
- Moves supermatter-related files to "power/supermatter"

Fix
- Fixes the pathing of the TEG supply pack

### CODE REVIEW

**Comment by tigercat2000** [comment]
I still don't get why it's renamed to a "Shard" of supermatter. But whatever, it's rare to see it at all.

**Comment by Spacemanspark** [comment]
Does this mean we'll eventually put the supermatter back on the map.

**Comment by fj45** [comment]
Looks good.

Its a very small thing, but could the "shard of supermatter" be turned back into a proper supermatter? I just feel that the old one looked better sprite wise.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

It's not in the plans, per se, but this does better pave the way for it to return.

**Pull request merged**
