### PR TITLE
Beach Biodome remap

### PR DESCRIPTION
**Pull request by ExusA**
## What Does This PR Do
Remaps the lavaland beach biodome.
1. Gives the bartender cooking supplies, a few more ingredients, and a cozy miniature restaurant where they can serve drinks to guests. The door to the cooking area is now locked to bartender ID.
2. Adds some sandy paths that connect both doors and the bar area.
3. Adds a tracking beacon (for teleporting) in the centre of the ruin to allow teleporting in, similar to the space bar ruin. Unlikely to be used regularly, but could result in interesting situations like an RD linking the two areas with a quantum pad, giving the spawner characters more to do and interact with. If they don't want this, they can easily throw the tracker away. (this COULD possibly be seen as an easy way for antags to get to lavaland, but there's already a tracking beacon on the mining base at roundstart which lets them do just that easily enough.)
4. ~Varedits the disco machine to be immovable. (i know it's gross, but adding an immovable subtype for this one ruin seems even ickier)~
Adds a new disco machine subtype that can't be unwrenched, and replaces the one in the beach biodome with it.
5. Not sure if this is relevant, but the remap shouldn't be affected by anything in the mapping pipeline since it uses permanent powered areas and fake atmos.
## Why It's Good For The Game
Very few people enjoy this ruin and the spawner roles that come with it. This PR aims to improve that somewhat by giving the bartender and beach bums more to do and hopefully promote the ruin as an RP area for players from both the station crew and the miners.

## Images of changes
biodome remap
(forgot to include the tracking beacon in that screenshot, but it's two tiles below the dance machine)
## Changelog
:cl:
add: adds more things for beach bums and bartenders to do
add: adds a tracking beacon to the beach biodome
/:cl:

### CODE REVIEW

**Comment by datlo** [comment]
I think a subtype for the discoball would be better. Varedits are infinitely more frustrating if they cause issues than single-use subtypes.

This is interesting, though.

**Comment by ExusA** [comment]
travis c'mon

**Comment by AffectedArc07** [comment]
If you read the travis error log, you will see why its failing
```
$ tools/travis/check_grep.sh
file ./code/game/machinery/dance_machine.dm is missing a trailing newline
The command "tools/travis/check_grep.sh" exited with 1.
```

**Comment by ExusA** [comment]
SHOULD be good now...

**Comment by ExusA** [comment]
Tested locally, all seems to work properly.
Teleporter reads "Beach Bar" when targeting the tracker
The ruin can spawn successfully, both naturally and with the place template command
The disco subtype is immovable and anchored
The spawners work as usual
The sandy path decals get deleted properly by explosions

**Comment by variableundefined** [comment]
@ExusA Will merge when deconflicted within 14 days.

**Comment by ExusA** [comment]
DNM while i make sure i deconflicted this properly! 😅

**Comment by ExusA** [comment]
Seems I managed to break another one of my PRs with Github nonsense, aaagh. Will have to reopen when I can figure it out!

**Comment by nukularpower** [comment]
I thought the best part of this ruin was getting the disco ball - its the prize of prizes :(   sad to see it stuck there

**Pull request closed without merging**
