### PR TITLE
Adds sysadmin job

### PR DESCRIPTION
**Pull request by monster860**
15 karma, access to teleporter and telecomms. Starts with a cup of coffee in hand.

Also, I could really use some ideas on the side of having things break that this guy can fix. For example, PDA's.

Here's the office I made for it.

:cl: monster860
rscadd: Adds a new sysadmin job
rscadd: Adds an NTSL manual.
rscadd: Makes it so you can reboot telecomms machines in an ionospheric anomalies.
/:cl:

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
Lolnope.

Please, for the love of god, stop trying to make Telecomms fuckery easier.

**Comment by Taaketa** [comment]
I don't like it. What's the purpose of the job?

**Comment by monster860** [comment]
Have yet another person that can ensure no one uploaded fucked up scripts.

Also, feels like the RD or CE never have time to fix the place when it gets kaboomed. The shuttle ends up getting called, and it never gets fixed.

**Comment by Fox-McCloud** [comment]
Be an annoying ass: The Job

**Comment by TullyBurnalot** [comment]
This entire job is centered around having access to Telecomms.

1) Telecomms being bombed is such a rare occurrence that they make Atmos Techs looks super useful and busy by comparison.

2) The only thing this job can do by default is Telecomms scripts.

3) Potential for Abuse = Potential for Positive Contribution X 3.69e10^100

**Comment by Taaketa** [comment]
The reasons Tcomms never gets fixed is becasue to repair a place that goes boom requires a tonne of resources to make it work again. Pretty sure the entire comms unit requires bluespace crystals or the equilviant of.

**Comment by monster860** [comment]
There's also a room conveniently located on the tcomms sat that contains most of the shit you need to fix it.

**Comment by FlattestGuitar** [comment]
Guys, I hate to say it, but I think this is a meme PR.

**Comment by Taaketa** [comment]
Which usually gets bombed along with the sat.

**Comment by monster860** [comment]
I have never seen it get bombed.

**Comment by Taaketa** [comment]
Because one bomb will do it.

**Comment by monster860** [comment]
The guy with the syndiebomb *never* thinks about that place. They all go "Welp, I doubt whoever has the access to fix this place will bother."

**Comment by Mijhead** [comment]
:+1: i like it, long live the information

**Comment by tigercat2000** [comment]
never

**Comment by MarsM0nd** [comment]
The problem kinda is, it currently would be crtl+c, crtl+v, then you are jobless and have access to teleporter and a spacesuit, maybe you would need to add some problems for machinery first, or expand NTSL so you don't just have it on Tcomms, maybe some programms on the laptops.

**Comment by Mijhead** [comment]
imagine if the sysadmin had access to a message monitor too, which i dont think he has now. the information could _truly_ flow!

**Comment by monster860** [comment]
> never

Typical tigercat.

**Comment by Regen1** [comment]
I actually like it, but because of the shitstorm that I can smell brewing 

Nope.avi

**Comment by Deanthelis** [comment]
This would be a more interesting job if Telecomms ever did anything but explode or stop working.

This could be a serious PR if the sysadmin had a tool to fix ion storm comms blackouts, since those often happen at really horrible times, and patching them up would probably make up for whatever dumb scripts they decided to run. This could be a whole real actual job if Telecomms had specific kinds of anomalies and errors that could be fixed by specific means - and it'd mean the RD or CE could step in to fix them if need be as well. I, for one, get frustrated when I can't fix ion anomalies because they're so annoyingly hardcoded to fuck everything up with no solution besides wait.

**Comment by monster860** [comment]
@Deanthelis I have implemented your suggestion. Turning the machines off and on again makes them work again.

**Comment by Lady-Luck** [comment]
I like it!

**Comment by Da-Dman234** [comment]
Other than reboot TComms I see no point to this, as the AI can already freely mess with TComms, no?

**Comment by theColdflame** [comment]
I'd suggest they also have access to the R&D server.

**Comment by monster860** [comment]
That would mean them getting access to science.

**Comment by Mijhead** [comment]
You could consider moving the message monitor room right next to the gravity generator (why is it there) to telecomms.

**Comment by Spacemanspark** [comment]
I see no reason for this, like Da Dman said.

**Comment by Lady-Luck** [comment]
Looks like this is gonna need a Controversial tag!

**Comment by Norgad** [comment]
This is just more NTSL powergamey stuff 👎

**Comment by Glorken** [comment]
I mean, if we get a sysadmin and constantly have one, we could remove TComms from RD.

**Comment by Magikarpet** [comment]
I really dislike the trend of uploading a gorillion tcomms scripts, not to mention waving a giant fuck you infront of malf ais/nukies/general antagonists who decide to mess with telecomms

if the role had something else to do outside of fuck with comms it'd be potentially hilarious and interesting, but I seriously hate people who upload their retarded scripts to tcomms every damn round and play rd/ce just so they can clog up comms with their flashy memey tcomms scripts 

That all ignores how laggy/buggy tcomms is more so with scripts, and how most of the playerbase wonder how to build/fix tcomms when it's generally a 5-10 minute job to do a fix as a greyshirt breaking in after a bombing(I have personal experience)

**Comment by monster860** [comment]
If NTSL abuse is a big problem, I can just remove the telecomms servers, and replace them with hubs

**Comment by Iamgoofball** [comment]
Now, I like the concept of a sysadmin.

BUT i don't like it being locked to karma.

**Comment by Lady-Luck** [comment]
>BUT i don't like it being locked to karma.

Specialty jobs are locked to karma on Para. That's just the way it is.

**Comment by Iamgoofball** [comment]
@Lady-Luck html UIs were "just the way it was", that didn't mean it was good

**Comment by Lady-Luck** [comment]
>sticking to shit because "thats how its always been" is fucking horrible dear god never ever

Not saying I agree with the philosophy, but it's something the administration will never change their minds on for as long as they live, so there's not much use criticizing a PR for using the karma system appropriately.

**Comment by Iamgoofball** [comment]
good thing it's not the administration's call, and is the codebase's call?

because this is basically "start with access to destroy tcomms/teleport into high security areas/access multiple steal objectives no hassle"

**Comment by Lady-Luck** [comment]
>good thing it's not the administration's call, and is the codebase's call?

I've never seen a PR passed that a majority of the administration disagreed with.

**Comment by tigercat2000** [comment]
>Specialty jobs are locked to karma on Para. That's just the way it is.

>Not saying I agree with the philosophy, but it's something the administration will never change their minds on for as long as they live, so there's not much use criticizing a PR for using the karma system appropriately.

who told you that lol
the issue we have is when _vanilla jobs_ are suggested to _become_ karma locked, that will never happen

**Comment by Spacemanspark** [comment]
Paramedic isn't a karma job, yet not vanilla, either.

**Comment by taukausanake** [comment]
> Paramedic isn't a karma job, yet not vanilla, either.
Huh. That is right. Why isn't it? I think it would have made a decent karma job, aside from being actually useful to the station if the player knows what they are doing

**Comment by Davdichan** [comment]
Paramedic should be a karma job, I don't know why it's not. Probably cause of how often the ambulance breaks the laws of the universe and doesn't work right. Always wondered if it would be possible to make the medicart just have a deployable morgue slab-like function that would allow the cart to nap someone up without having the damn tow behind trolly.

**Comment by taukausanake** [comment]
> Always wondered if it would be possible to make the medicart just have a deployable morgue slab-like function that would allow the cart to nap someone up without having the damn tow behind trolly.

Oh! Maybe make that an upgrade it could use. Medicart should get the same love janicart gets

**Comment by Allfd** [comment]
:-1: x:100:

No to the office, make them a corner in maintenance and fill it with boxes.  They also need a poster reminding them that their job will be removed from the station the moment CentCom figures out how to move the PDA messaging server to the cloud.   Otherwise my immersions.

**Comment by QQCucumber** [comment]
Is this a protected job? I could see this being extremely annoying with a traitor.

**Comment by tristan1333** [comment]
Probly better than someone being a head just to mess with t-comms

**Comment by Ar3nn** [comment]
@QQCucumber NO. A thousand times, no. If this were legitimate, it would be stupid to be protected, because that's 100% guaranteed, the moment someone messes with tcomms, they just go to that guy and say "fix nao" and he does and that ruins tators plans.

**Comment by Citinited** [comment]
Job goes as follows:

1. Teleport to telecomms to upload script you copypasted
2. Fuck around in the bar

:-1:

**Comment by Necaladun** [comment]
Alternate Title: BOFH.

More seriously, I kinda like it in theory, but with how NTSL is and used, and the problems with it, I just see it made worse. 

Additionally, no job should be added like this without some clear guide to exactly what their powers and responsibilities are. Who their boss is, what they can be fired for, etc etc.

**Comment by Iamgoofball** [comment]
BOFH please go

**Comment by taukausanake** [comment]
I kind of like the Sysadmin title though

**Comment by Faryaa** [comment]
Give him some nerdy outfit as well. Some checked shirt or striped sweater with pants.

**Comment by Fox-McCloud** [comment]
Closing this as I'm pretty sure it's a meme PR, and as an actual job...well, it's one that's kinda already filled by the RD and CE.

**Comment by Glorken** [comment]
So, Telecomms is too OP because only a few people have access, but we can't
add more jobs with access because there are already a few.

**Comment by TheDZD** [comment]
It's not OP because a few people have access, telecomms in general is just open to a lot of shittery.

**Comment by Kevak** [comment]
Telecoms is one of the few ways someone could crash the server with minimal effort involved. Aka a griefer's wet dream. Giving _More_ people the potential to do that is a bad idea.

**Comment by taukausanake** [comment]
@Kevak Not to beat a dead horse but if a griefer wanted to use this as a means to kill the server they'd actually have to RP it up and get karma for this job. By then they would have committed suicide or meta out the butthole to get to telecomms

**Pull request closed without merging**
