### PR TITLE
Secures the Kitchen--Retains Interaction

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds windoors to the kitchen counters.

Essentially allows the chef to keep his shutters up and do his job as he please while being able to see the outside world and interact/talk with people without the worry of people just hopping his counters as at a moment's notice, all the while easily still being able to place food out.

kitchen

### CODE REVIEW

**Comment by Robertha89** [comment]
Not sure how I feel about this, I mean, on one side, I like it cause it was annoying... on the otherside i dont like it cause i can't table climb, and I would have to break down the table or wall instead...

are the doors locked to the chef? cause I sure hope not, if it's open to all, it's basically fine, but again eh. I don't know where i stand with this.

**Comment by Fox-McCloud** [comment]
It's a better alternative than the chef just locking down the kitchen and refusing to open it because of everyone just rudely climbing his tables and stealing his shit.

**Comment by Plotron** [comment]
I've got mixed feelings.
Can't count the times the chef was incompetent and/or absent.

But hey, you can always ask AI/Captain to unlock the windoors! In this case, I guess, the downside isn't really a downside.

**Comment by FalseIncarnate** [comment]
My main issue with this is that i'll have to leave windoors open (thus negating their security) to be able to throw tacos from the microwave to the counter, or walk over there like a normal person. Otherwise perfectly fine with this.

**Comment by Fox-McCloud** [comment]
@FalseIncarnate 

I wonder if more people will use the trays, as a side effect of this, for that very reason?

**Comment by orelbon** [comment]
so many windoors together looks ugly, but what can you do.

**Comment by ZomgPonies** [comment]
This makes sense. A lot of cafetarias has this kind of window setup.

**Comment by tigercat2000** [comment]
I don't like this, for two reasons
one, windoor spam- windoors are a pain in the ass for everyone involved, whether it's deconstruction, B&E, or just regular use
two, it makes the kitchen damn near impossible to break into when the chef is off fucking himself in maintnance or whatever, which, I don't know about anyone else, but I have had to do many many times

**Comment by Fox-McCloud** [comment]
@tigercat2000 

I understand that, but that's just the inherent nature of the way jobs are; I don't think medical, chemistry, R&D, etc should be open access in case that particular job isn't around to do their duty--in the instance that job is now, it's pretty easy to ask the AI to open "X" department (which happens a lot for chemistry, for instance).

And I dare say that the chef is a less important job than those (considering you can just eat at the vendors).

**Comment by TheDZD** [comment]
I do think that the chef needs something to keep people from breaking in and stealing knives/rolling pins, but I really dislike the way the windoors look stacked next to each other.

**Comment by Fox-McCloud** [comment]
Changed the door orientation so they open up opposing each other.

**Comment by TheDZD** [comment]
Looks better, worth a shot to try this at least.

**Comment by orelbon** [comment]
yes looks much better now

**Pull request merged**
