### PR TITLE
Removes Unused Settings From Game Preferances

### PR DESCRIPTION
**Pull request by Daylight2**
## What Does This PR Do
Removes space ninjas, positronic brains and giant spiders from the special role settings list in preferences.

## Why It's Good For The Game
The gamemode does not exist. You cannot play as a space ninja. They have been unplayable for as long as I can remember - this just removes confusion from the antag list.
The posibrain and giant spider preferances were unused, along with /obj/item/mmi/robotic_brain/proc/question(client/C).

## Testing
image
Became a posibrain and robotic brain.

## Changelog
:cl:
del: Updated the antag preferences list to be up to date. 
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
IMPROVE DONT REMOVE
#bringninjasback

**Comment by Daylight2** [comment]
> IMPROVE DONT REMOVE #bringninjasback

I wish they were playable. You can equip the full ninja set from the admin shuttle right now, and it would do literally nothing. Stuff's borked.

**Comment by GDNgit** [comment]
> IMPROVE DONT REMOVE #bringninjasback

I got good news for you 

Anyways if you're gonna do this go the whole way. ROLE_POSIBRAIN and ROLE_GSPIDER are also both unused

**Comment by GDNgit** [comment]
> > IMPROVE DONT REMOVE #bringninjasback
> 
> I wish they were playable. You can equip the full ninja set from the admin shuttle right now, and it would do literally nothing. Stuff's borked.

it works it's just stupid

**Comment by Daylight2** [comment]
> > IMPROVE DONT REMOVE #bringninjasback
> 
> I got good news for you
> 
> Anyways if you're gonna do this go the whole way. ROLE_POSIBRAIN and ROLE_GSPIDER are also both unused

There you go

**Review by DGamerL — COMMENTED** [review]
Please deconflict, LGTM otherwise

**Comment by DGamerL** [comment]
> I'm just going to hope the CL failing is a problem with the tests and not my attempt at deconflicting borking something.

Doesn't seem to be your problem, you're safe 👍

**Review by S34NW — APPROVED** [review]

**Pull request merged**
