### PR TITLE
Removes gold core nurse spiders and spider sentence continueation.

### PR DESCRIPTION
**Pull request by MarcellusPye**
Removes nurse spiders from the list of mobs spawnable via gold slime cores and changes it so that sentient nurse spiders do not produce sentant children.
:cl: MarcellusPye
tweak: Sentient giant spiders no longer produce sentant offspring.
del: Nurse spiders cannot be produced via gold slime core reaction.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Sentient

**Comment by MarcellusPye** [comment]
Shh, I can spell, possibly.

**Comment by Kyep** [comment]
Problems:
- This PR has 3 leading merge commits. Consider using git rebase to get rid of them.
- Wouldn't this mean that they then produce normal, hostile spider children? So, a xenobiologist with a sentience potion could hit a nurse spider with it, give her monkeys, and spawn an army of always-hostile spiders? Perhaps making it so nurse spiders cannot have sentience potions used on them would be a better option. Unless you want traitor scientists to still be able to create hostile spider armies.

**Comment by MarcellusPye** [comment]
It would allow them to make a permanently hostile army, however finding a wild spider, sentencing it, breeding it, and managing the wild spiders that result is much more difficult than simply using a gold slime core and waiting. I made the decision not to remove the ability to make nurse spiders sentient upon the recommendation of PurpleGenie, I can change it if another solution is prefered.

**Comment by adamkad1** [comment]
yer mad at getting killed by sentient spiders or what? anyway, the only thing you will achive here is limit traitor creativity, forcing them to use less complex and more boring ways to kill people. like bombs, chems and such. spiders atleast let ghosts come back and have fun, not to mention its sometimes used by nontraitors to like, fight xenos or terror spiders (i did the former once).

**Comment by Shadeykins** [comment]
@adamkad1 The number of times green spiders hatching hasn't caused a huge shit storm on station is somewhere around 0. I have _never_ seen them used by antagonists in the three years I've been here. They have only ever been used by regular xenobiologists, who let them get out of hand, then a bunch of new players get spider'd and assume they're NPC spiders with free reign to murder people.

What this PR achieves is removing a massive headache of having to bwoink sixteen different people for attacking crew as sentient spiders every other day. Newly hatched spiderlings aren't even bound to the xenobiologist in question, which makes the antagonist comment moot - if your argument is "chaos!", you're relying on people to _break the server rules_ to try and greentext.

If you actually manage to get a nurse spider now, you can utilize it antagonistically since you could flood the station with _actually hostile_ spiders.

**Comment by uraniummeltdown** [comment]
@Shadeykins How are you supposed to get the nurse spider for antagging if Marcellus is removing it from gold cores? 

This PR is lazy, it would be better to have the nurse spider's spiderlings display the same xenobio text of "Remember X is your master" if sentienced

**Comment by MarcellusPye** [comment]
A: You can get them from the random spider events.
B: Simply adding sentence text would allow for the easy creation of an exponentially expanding army, where as simple mobs actually have to be corralled and controlled. You can also continue gold slimeing and sentenceing all other types of giant spider to your hearts content.
C: As Shady mentioned I made this after complaints from several members of the administration team about the negitave effect this was having on rounds and the headaches that resulted.

**Comment by Shadeykins** [comment]
@uraniummeltdown The issue is they're not bound to _anyone_ to begin with. You couldn't use them as an antagonist in the first place because they don't have to listen to you, and in fact if they do listen to you (since you're not their master) that would be self-antagging (whereas if they were properly slaved to you, that's another story).

It has never been, and never was, a viable tactic to use as a traitor.

As Marcellus has said repeatedly, this doesn't prevent you from sentience potioning a nurse spider that spawns as part of the all-too-common spider event (or spiderling spawn from changelings) and creating a veritable horde of hostile spiders. It also doesn't prevent you from using gold slime to generate all other types of spiders.

**Comment by adamkad1** [comment]
i remember that the offspring was once bound to you, dont remember when they changed it. and they usually listen to the 'mother'. and as i said, they make decent xeno fighting force, assuming they follow the rules... but then again, you could make sentient spiders birth sentient bound spiders because that would be more fun.

**Comment by Kyep** [comment]
IMHO, one of the big issues with sentient spiders is that it was never sufficiently clear who your master was, if you grew up as a sentient spider. You had a master defined in /master_commander but I don't think that was obvious enough, maybe even announced at all, to the player.

**Comment by Vivalas** [comment]
"Because people abuse it" is a false reason for removing anything in my eyes. This argument can be extended to anything in game and is almost entirely anecdotal. If you're tired of new people not knowing how to play them, add bolded scary text-- or better yet, let sentient spiders make sentient decisions. They are spiders after all.

That and the fact admins exist for a reason. Any type of PR along these lines always pisses me off because of how subjective it is.

**Comment by MarcellusPye** [comment]
I'm not removing it because people abuse it, if that was the issue I'ed fix the message and start banning people who did. I'm removing it because a single sentence core and a few gold cores should not be able to get you a self repairing and expanding army that is often bigger than security or the antag population.

**Comment by Fullofskittles** [comment]
I'm pretty sure that babies of sentient/tame spiders are _supposed_ to inherit loyalty from their parent. Wouldn't it be better to just fix the issue that they aren't doing that instead of outright removing something? A giant red message would probably do a lot to help with any confusion and people who run around self antagging can be delt with then.

Also, just because you haven't seen people use sentient spiders for proper antagging doesn't mean it doesn't happen. I've done it, I've seen other people do it as well and even for non antags you can use sentient spiders to help with things like swarmers/xenos/terror spiders.

**Comment by MarcellusPye** [comment]
Ok, let's go through all the circumstances this would apply to if we made 2nd gen spiders sentient and slaved to the original xenobiologist.
1. Xenobiologist does not give orders.
You have allot of players in mobs that can do nothing but fight getting bored and looking for things to do, something we want to avoid.
2. The xenobiologist is not an antag.
2a. There are no antags.
See 1.
2b. There are stealth antags such as clings, trators, vamps, ect.
The antags get valided out of existence. Something we want to avoid.
2c. There are station destroying antags.
2ci. There are blobs.
Midround blobs are allredy barely a threat, more people searching for them will not help.
2cii. There is a rouge AI.
Giant spiders are unable to attack the AI directly, however they could easily overwhelm the borgs. While they could help in this case it leaves the borgs almost no chance.
2ciii. There are xenomorphs.
The spiders would have to fight the much more powerful and generally more interesting xenos for ghosts.
2civ. There are terror spiders.
We have the same problems encountered with xenomorphs in 2ciii expanded by terrors being objectively more powerful and the interesting version of giant spiders and the giant spider corpses feeding the terror army.
2cv. There are swarmers.
Swarmers cannot hurt the spiders and the spiders cannot get access or crawl in the vents to hunt them, just extending the game of hide and seek most allredy find tireing.
3. The xenobiologist is an antag
3a. The xenobiologist does not have hijack.
3ai. The xenobiologist does nothing with them.
See 1.
3aii. The xenobiologist orders them to murder sec.
Sec is almost completely distracted by the self replicateing army and cannot focus on the other antags or gets murdered. This is something we want to avoid.
3aiii. The xenobiologist orders them to murder a target.
Someone defends the target, go to 3aii.
3aiv. The xenobiologist has hijack.
In addition to toxins bombs and the fruits of RnD science can now make a self-sustaining army, further crushing any chance the crew has against a scientist hijacker.
While this may not happen every time it's what I feel they would most often act as, and while they have some positive sides the underlying issue I have is that a self-sustaining army is a major power, and gaining one should not be as simple as a few cores. Also note that an army is still creatable by farming sentance potions, all this does is prevent it from being self replicateing. If you have any questions, issues with my analysis or other solutions to these issues please share them. This is mearly the thought process that lead to the decisions in this PR.

**Comment by Kyep** [comment]
From my POV, normal space spiders aren't really suitable mobs for players to play as.
Unlike Terror Spiders:
- They have no ventcrawl, wallsmash or door-opening ability, thus are prone to getting stuck in rooms they cannot escape from. Even in combat, they cannot hit and run, or retreat easily.
- They have no regeneration, and most have weak health values, thus they're prone to being killed very quickly in combat, even with Civilians. Even if they do fight and live, their minor injuries are still a problem, as they did not have much health to start with, and they cannot heal up between fights.
- They have no hivemind or radio access, thus are very lonely to play.
- They suffer from a lack of directions/goals, especially if their creator is not an antag. Nobody wants to sit in a xenobio pen for two hours.
- They are typically assumed to be NPCs, so random people you aren't attacking might kill you for no reason in the hallway.
- They're quite annoying with the number of DINGs and popups they create for ghosts.
- From an admin POV, mass space spiders usually ends in chaos, and someone getting bwoinked.

For all of these reasons, normal space spiders should probably not be playable en masse. One or two is fine, but mass-producing them should probably not be possible.

**Comment by Vivalas** [comment]
I would say one or the other then, if Xenobio lucks out and gets a sentience potion on a spider, then that should be allowed. Its an iteresting antag device.

Gold cores spawn hostile mobs, spiders included. Can't xenos also be made from gold cores? This PR just seems so damn selective and anti-fun.

**Comment by MarcellusPye** [comment]
Could you please clarify what you mean by one or the other? The xenomorphs created by gold slime cores are simple mobs different from regular xenomorphs, lacking many functions including the ability to breed. Preventing sentient nurse spiders from breeding was also a discussed option, I did not take this route in order to leave the opportunity to create a spider army via this method. The difference being that work would be required to catch a nurse spider and corall/make sentance potions for all their offspring, rather than a few gold cores and one potion being all that is needed for an army.

**Comment by Fullofskittles** [comment]
> Ok, let's go through all the circumstances this would apply to if we made 2nd gen spiders sentient and slaved to the original xenobiologist.

I just want to point out that they already are supposed to be. The fact that they're not is a bug. I also want to point out that you have to click a prompt to become a sentient spider. It's a player's choice to do that and is limited by the number of ghosts that want to be one.

How exactly are spiders more of a problem than other xenobiology mobs with sentience potions? How are they more of a problem than a golem army? If you've got a xenobiologist who manages to get gold slime extracts and pink slime extracts the odds of them having a surplus of those extracts is pretty good. There is absolutely nothing stopping them from raising an army of any other mob type. 

Green Eyed spiders may be able to breed but even with an overwhelming amount of spiders they're still non-hostile to the crew unless a ghost actively decides to play a spider.

> It would allow them to make a permanently hostile army, however finding a wild spider, sentencing it, breeding it, and managing the wild spiders that result is much more difficult than simply using a gold slime core and waiting

This just sounds impossible. It's not like sentience potions are automatic and instant. They require a ghost clicking a prompt to play one. How exactly is a player supposed to secure a spider, stand next to it to bap it with a potion and somehow not die horribly? Since spiders inherit their faction flags from their parents wouldn't doing this to a hostile spider just make hostile babies which would be actually worse than what we have now?

**Comment by MarcellusPye** [comment]
Closing due to the large amount of disagreement and the merging of #8438

**Pull request closed without merging**
