### PR TITLE
Гироскутеры

### PR DESCRIPTION
**Pull request by sswwyyaatt**
Воруй убивай

### CODE REVIEW

**Comment by taukausanake** [comment]
So is this going to be a regular thing or...

I wish I wasn't at work so I could look over all this

**Comment by LightFire53** [comment]
How do they always get their PRs wrong...

**Comment by KasparoVy** [comment]
@sswwyyaatt Привет, пожалуйста убедитесь что ваши запросы на изменение предназначены для правильного репозитория.

Shameless Google translation of "Hi, please make sure that your change requests are for the correct repository."

**Comment by Vivalas** [comment]
I'm mildly surprised there are only two conflicts.

**Comment by SamHPurp** [comment]
@tigercat2000 no fun

**Comment by tigercat2000** [comment]
As Kasparov said, please be careful with your merge requests.

**Pull request closed without merging**
