### PR TITLE
Fixes Bee Briefcase killing traitors regularly

### PR DESCRIPTION
**Pull request by Kyep**
Prior to this PR, traitors double-clicking a bee briefcase without first injecting it with blood, will spawn 5 syndiebees that then immediately kill them. This might be fair for people who explicitly order the bee briefcase as botanists, and thus *hopefully* know how the bees work. It is definitely not fair, though, for the traitors who get the bee briefcase in surplus crates, bundles, etc. These traitors have no idea what the briefcase is, have probably never used it before (its botanist-only normally) and nothing about the briefcase itself tells them. They only find out when they go to open it, curiously... and die horribly as a result.

With this PR, traitors attempting to open the briefcase will get a warning about what they must do to open it safely. Non-antags won't get this warning - for them, opening it will still likely be fatal.

For traitors trying to open the briefcase without first training the bees, the warning is: "You must inject some of your blood into this briefcase, using a syringe, to train the bees not to attack you. Only then can the briefcase be opened."

:cl: Kyep
fix: Safeties added to Bee Briefcase, to prevent it accidentally killing traitors get it in bundles and crates.
/:cl:

### CODE REVIEW

**Comment by AceMcLazer** [comment]
:bee: :+1: :bee: :+1: :bee: :+1:

**Comment by theColdflame** [comment]
new traitor test confirmed

**Comment by Kyep** [comment]
Doubtful.
What's sec going to do? Hand a bee briefcase to a suspected traitor and ask them to open it?
If the bees inside are untrained, they kill everyone.
If the bees inside are trained by that traitor, they kill sec, and leave the traitor alone.
If the bees inside are trained by sec and NOT the traitor, they kill only the traitor - which is murdering a prisoner in sec custody.
None of these outcomes seem good for sec.

**Comment by FalseIncarnate** [comment]
:-1:

The briefcase is identifiable by examine, so if a traitor is randomly opening them through surplus crates, that traitor is an idiot. You just got a crate of dangerous stuff from a shadowy group bent on causing havoc, so randomly trying to open the stuff inside should be done at your own risk.

**Comment by FalseIncarnate** [comment]
Additionally, this means the traitor MUST inject some blood into the crate or else it doesn't work: bad for those wanting to use the briefcase for Die a Glorious Death and Assassinate objective combos. They'd have to make some random person or monkey immune just to open the case.

**Comment by TheDZD** [comment]
You could set the bee briefcase's `description_antag` to something that makes it plainly obvious that a traitor should inject blood into it to keep the bees from attacking completely indiscriminately.

**Comment by Spacemanspark** [comment]
I don't think a traitor would really be allowed to use it for a glorious death objective, it gets a bunch of people killed.

**Comment by CrAzYPiLoT-SS13** [comment]
And that makes it glorious :^)

**Comment by FalseIncarnate** [comment]
Under suitable circumstances, I'd definitely allow it. Using it on the shuttle is not one of those, but using it when you've got your self and/or target alone is. The bees are still easily killed with a fire extinguisher or even a couple solid punches, so it's not too unreasonable to handle. Plus, bees are a good deterrent to passerbys who might drag the victim to cloning without messing with atmos and such like a bombed area.

**Comment by fludd12** [comment]
A common complaint on the 'do you like the direction ss13 is going' forum post is that the game is getting less punishing. I have to agree with False, in that if you're dumb enough to screw with synditech without knowing what it is, you should get bee'd in the face, not tapped on the shoulder.

**Comment by Fox-McCloud** [comment]
Do what DZD said, not this.

**Comment by Kyep** [comment]
@TheDZD @Fox-McCloud Changed to DZD's suggestion.

**Comment by FalseIncarnate** [comment]
You forgot to change the changelog to reflect the final version. Not sure what can be done about that now.

**Comment by Tastyfish** [comment]
@Kyep, what do you want the changelog to say, since that one no longer matches the PR?

**Comment by Kyep** [comment]
@Tastyfish "added antag-only warning to bee briefcase, to reduce chances of traitors killing themselves with it"

**Pull request merged**
