### PR TITLE
Adds Butt Hats

### PR DESCRIPTION
**Pull request by TheDZD**
:cl:
add: Adds butt hats, you can order them from cargo for 150 points for a crate of 3 hats. All credit goes to Goonstation for the sprites.
/:cl:

image

### CODE REVIEW

**Comment by Tastyfish** [comment]
I will integrate this with the buttbot branch I still have from April.

**Comment by tigercat2000** [comment]
merge immediately

**Comment by Ar3nn** [comment]
I knew it. I knew #5000 would be a meme pr

**Comment by Fox-McCloud** [comment]
Oh gosh, these *actually* have in-hand icons?

**Comment by theColdflame** [comment]
please no

**Comment by Fox-McCloud** [comment]
Butt, @theColdflame, this PR cannot be held posterior any longer---and besides we don't want to be behind the other codebases...that'd make us all look like asses.

**Comment by theColdflame** [comment]
I think you're just being backwards about this, @Fox-McCloud.  Backporting all these features from the ass-end of other codebases is pretty shitty.

**Comment by Fox-McCloud** [comment]
:wink:

**Comment by Lady-Luck** [comment]
Actually merge it.

**Comment by FreeStylaLT** [comment]
I'm tired of getting the butt end of all these jokes

**Comment by Belario** [comment]
:+1:  It's abutt time we saw the rear-end of this controversy.

**Comment by Davdichan** [comment]
Ask not what your station can do for you, butt what you can do for your station! :+1: :100:

**Comment by Vivalas** [comment]
This literally needs to be merged right fucking now. This is not the PR this server needs, it's the PR this server DESERVES.

**Comment by Spacemanspark** [comment]
no

**Comment by Lady-Luck** [comment]
yes

**Comment by Necaladun** [comment]
Butt.

**Comment by KasparoVy** [comment]
Holy shit bahaha, this thread
:+1: I think it's pretty jokes

**Comment by Fox-McCloud** [comment]
Only an hour to go....

**Comment by Necaladun** [comment]
why not speedmerge?

**Comment by TheDZD** [comment]
I think the joke has gone on long enough now. RIP in spess.

**Comment by Tastyfish** [comment]
rip in peace sweet prince

**Comment by Ar3nn** [comment]
buttbots-soon-tm as in never

**Comment by theColdflame** [comment]
o7

**Pull request closed without merging**
