### PR TITLE
fixes #3497

### LINKED ISSUE #3497: Deathsquad Borg Pulse Rifle broken
It only fires lasers on all three modes, while maintaining the modes' sound effects. Stun still makes the taser noise, and DESTROY still makes the pulse noise, but it's all lasers.

Deathsquad borgs in general are shit and need to be buffed to actually be threatening/useful but that's another issue altogether.

### PR DESCRIPTION
**Pull request by VampyrBytes**
Deathsquad borg pulse rifle now fires correct round type

### CODE REVIEW

**Comment by VampyrBytes** [comment]
Erm, what just happened? And how do I fix it? It's working fine on my local version

**Comment by Earthdivine** [comment]
Closing and Opening sometimes fixes it, might just be Travis

**Comment by Crazylemon64** [comment]
@VampyrBytes Close and reopen, travis is sometimes unreliable.

> <a href=https://travis-ci.org/ParadiseSS13/Paradise/jobs/107046643#L72>No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.</a>

**Comment by VampyrBytes** [comment]
Thanks guys :smile:

**Pull request merged**
