### PR TITLE
Makes modsuits acid proof and virus immune

### PR DESCRIPTION
**Pull request by ppi13**
## What Does This PR Do

This makes the engineering, atmospheric, advanced, loader, medical, security, safeguard, syndicate, and responsory modsuits acid proof.
It also makes them as virus immune as biosuits.

## Why It's Good For The Game

While acid smoke is rare, having your modsuit automatically retract due to those rare occasions does not feel good in anyway.
And the fact that nearly every modsuit is hermetically sealed, they should block out viruses, unless you ingest em, or get RNGed.

## Testing

Used a lot of facid smoke grenades

## Changelog
:cl: ppi
tweak: Acid smoke does not cause the engineering, atmospheric, advanced, loader, medical, security, safeguard, syndicate, and responsory modsuits to retract.
tweak: Fully wearing a modsuit now protects you against viruses, while wearing internals.
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
Please merge `upstream/master` into your branch to fix CI failing due to external factors.

**Comment by matttheficus** [comment]
Not a fan of the acid-proofness. Its designed to be a proper counter to the suits if you use it. Objecting on that basis.

I dont mind them being virus-proof (as long as the suit looks "sealed" sprite-wise. Loader is the main one that doesnt look as such to me)

**Comment by ppi13** [comment]
> Not a fan of the acid-proofness. Its designed to be a proper counter to the suits if you use it. Objecting on that basis.
> 
> I dont mind them being virus-proof (as long as the suit looks "sealed" sprite-wise. Loader is the main one that doesnt look as such to me)

They are already acid proof againsts sprays, and its just the smoke that got this extremely deliberating effect.  
Which still does not protect gas masks, nor does it protect against acid damage, so its still a viable counter, facid grenade + n2o grenade = victory.
As for viruses, as long as every body part is covered, they will be virus immune, so the mining hardsuit which has no face cover needs a mask that is also 100% virus proof.

**Comment by DGamerL** [comment]
> Which still does not protect gas masks, nor does it protect against acid damage, so its still a viable counter, facid grenade + n2o grenade = victory.

Wouldn't a better solution be to fix acid smoke doubling up on this then?

**Comment by Denthamos** [comment]
> > Not a fan of the acid-proofness. Its designed to be a proper counter to the suits if you use it. Objecting on that basis.
> > I dont mind them being virus-proof (as long as the suit looks "sealed" sprite-wise. Loader is the main one that doesnt look as such to me)
> 
> They are already acid proof againsts sprays, and its just the smoke that got this extremely deliberating effect. Which still does not protect gas masks, nor does it protect against acid damage, so its still a viable counter, facid grenade + n2o grenade = victory. As for viruses, as long as every body part is covered, they will be virus immune, so the mining hardsuit which has no face cover needs a mask that is also 100% virus proof.

I would say - they should only be acid proof to smoke if internals are enabled with the suit.  If internals are off and you are taking air from the environment, then it makes sense the acid smoke would get into your suits systems.

**Comment by DGamerL** [comment]
> Not really, losing your gasmask is fine as you usually have a breathing mask handy, losing all your armor cause lol facid smoke is just silly, especially if it just exists as a counter, when EMP is already really strong against them.

Something I said in the discord which might've been missed is a small tweak to how MODsuits helmets are retracted. Instead of being instant, it'll be a small timer after which the helmet will retract.
Along this, you could implement a check for internals to not be melted if the helmet covers the face enough.

**Comment by S34NW** [comment]
Please see design team comments outstanding for 2 weeks.

**Comment by S34NW** [comment]
Stale PR, no changes made in requested timeframe. Please re-open this once changes are made or make a new PR.

**Pull request closed without merging**
