### PR TITLE
Space Cleaner tweaks: nerf, advanced version and availability

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Nerfed space cleaner spray range (3 -> 2 tiles).
Adds advanced space cleaner to janitors and places in which it would make sense (spray range = 3 tiles).

Mapping changes (amounts are WIP):
Medbays: space cleaner amount has been decreased to 5.
Removed 1 space cleaner from workplaces that had 2 of them (in example: chemistry having two cleaners).

## Why It's Good For The Game

Non janitors shouldnt have the same cleaning capacity as janitors.
The amount of cleaners that science and especially medbay has was enough to keep their departments clean for the entire round (that is, if it didnt get stolen or if the round has a biohazard that goes on for a long time).
Having a nerfed version that can only clean 2 tiles each spray should be enough to accomplish their main purpose in these departments, and in cases where two tiles feels too weak for the situation then you should be calling the janitor or even ordering a janitorial crate.
## Images of changes

cleaners

## Testing

- Looked into janitor equipment to see if it had the correct cleaner
- Used both cleaners to compare their differences
- Did look around the map looking for any mistakes or duplicated cleaners.
## Changelog
:cl:
add: Added advanced space cleaners (spray range = 3 tiles). Available to janitors
tweak: Decreased the basic space cleaner spray range to 2 tiles
tweak: Decreased the amount of space cleaners available to science and medical departments
/:cl:

### CODE REVIEW

**Comment by Daylight2** [comment]
I feel like the space cleaners in medchem and (especially) scichem are less for cleaning things and more for filling them up with fun chemicals - you can do some funky stuff with them. This is a minor nerf to departments cleaning ability, but a major one to anyone who wants to use these to antag.

**Comment by Henri215** [comment]
> I feel like the space cleaners in medchem and (especially) scichem are less for cleaning things and more for filling them up with fun chemicals - you can do some funky stuff with them. This is a minor nerf to departments cleaning ability, but a major one to anyone who wants to use these to antag.

You are right, but its mostly a nerf to Cyberiad.
It still is the station with the most cleaners (counting maints) and is the only map where one cleaner has been removed from medchem and scichem, having thereby the same amount as the others.

**Comment by Daylight2** [comment]
The reduction in range still makes it a bit of a nerf to antag shenannigains - 2 tile range makes it more difficult to hit people with the spray, for example. Perhaps remove space cleaner bottles from scichem entirely and replace them with one or two empty, "advanced" spray bottles? Or perhaps add a rnd or screwdriver mechanic to extend their range. Would achieve the goal of making the janitor more important without nerfing antag tomfoolery.

**Comment by Henri215** [comment]
> The reduction in range still makes it a bit of a nerf to antag shenannigains - 2 tile range makes it more difficult to hit people with the spray, for example. Perhaps remove space cleaner bottles from scichem entirely and replace them with one or two empty, "advanced" spray bottles? Or perhaps add a rnd or screwdriver mechanic to extend their range. Would achieve the goal of making the janitor more important without nerfing antag tomfoolery.

The inclusion of a few empty advanced cleaners is a good idea that i even thought about when making it, its still a draft until i am certain about these mapping changes amounts and i might consider this option.

**Comment by Carthusia** [comment]
I like the nerfing of space cleaner since its ALWAYS relied on and i almost feel the cleaner filler in the janitor closet needs a reduction as well, but i feel adding an advanced version by default to the janitor closet kind of makes the change moot entirely in a way.

All in all, if you could use a mop, advanced mop, a jani cart with buffer upgrade or space cleaner filled sprayers, in the end, the sprayers be it backback or hand held, are better than all the others due to their portability and speed, with their only downside being a limited capacity, though this can be nullified entirely by just carrying refills.

I use an advanced mop by choice for personal preference, but i fully accept that it sucks compared to cleaner sprayers

**Comment by Henri215** [comment]
> I like the nerfing of space cleaner since its ALWAYS relied on and i almost feel the cleaner filler in the janitor closet needs a reduction as well, i think it has like 5,000 spray at round start?
> 
> But i feel adding an advanced version by default to the janitor closet kind of makes the change moot entirely in a way.
> 
> All in all, if you could use a mop, advanced mop, a jani cart with buffer upgrade or space cleaner filled sprayers, in the end, the sprayers be it backback or hand held, are better than all the others due to their portability and speed, with their only downside being a limited capacity, though this can be nullified entirely by just carrying refills.
> 
> I use an advanced mop by choice for personal preference, but i fully accept that it sucks compared to cleaner sprayers, even though the advanced mop really should be better, its an RND locked item thats only real bonus is its condenser which slowly fills it with water

I agree with everything you said, the cleaner balance with other cleaning equipment is broken, but i didnt want to touch this balance because the main focus of this PR is to nerf the non janitor cleaning capacity.
If janitors were to start with basic cleaners then where advanced ones could be acquired? Cleaners can only be acquired with janitorial crates currently and i dont know if giving science the ability to produce lots of them would be good for balance in general.

**Comment by Carthusia** [comment]
I still feel no one should have an "Advanced sprayer" in the hand held variant

To me, the sprayers should be 1 tile, they clean stuff instantly with no effort and are meant for small jobs, not just spraying down an entire bay in seconds entirely nullifying an entire departments workload.
For that we got cleaning grenades people can order in or craft in RND

We already technically have an "Advanced" sprayer, its the backpack version, janitorial starts with 2 of them, though they are rarely used due to hand sprayers being better in every way and in larger numbers. Maybe even lower their spray count to 50 units from 100 to encourage its usage.

Perhaps the backpack sprayers could remain 3 tile range, its a big pressurized tank on your back, and even though it slows you down, as a tradeoff you get your 3 spray range and carry 500 untis of cleaner with ya.

You can also empty it and fill it with acid and other horrible stuff.

This makes each piece of equipment have their purpose

Hand Sprayers: 1 tile range, but instant cleaning, potentially low liquid capacity

Backpack Sprayers: 3 tile range, instant cleaning, high liquid capacity, but it takes a backpack slot and slows you down

Mopping/Advanced Mop: Takes time, leaves wet floors, but is the most resource efficient of all the cleaning types when 
accounted for resupplies and time spent getting more stuff.

Soap: Slowest of all the cleaners, but is infinite, no wet floors and a good fallback when all else fails.
Red Soap: Fastest of all the cleaners, infinite, no wet floors, but is a syndicate TC item and if your lucky a maint loot drop, keeping its usage rare

**Comment by Henri215** [comment]
Will be opening another an alternative PR with different tweaks (and because i created a mess while trying to remove merge conflict).

**Pull request closed without merging**
