### PR TITLE
Fixes malf AI

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Fixes malfunctioning AI game mode.
2) Re-enables malfunctioning AI jobbans.

No, this does not mean I'm back - Raeth kept bothering me about fixing this, so here we are :P.

Fixes https://github.com/ParadiseSS13/Paradise/issues/1513.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Oh. Well, that's a remarkably simple solution I didn't see. Thanks Mark.

**Comment by Fox-McCloud** [comment]
Oh my gosh, it's @Markolie ! Hey there, how have you been? Really appreciate this fix; its' been bugging us for a long time and @tigercat2000 had no idea what to do to fix it.

**Comment by Markolie** [comment]
:wave: Quite well, not too much going on! And you're very welcome.

**Comment by Fox-McCloud** [comment]
@Markolie 

Great to hear, and thanks, once again!

**Comment by Spacemanspark** [comment]
Holy fuck Mark's back.

**Comment by Regen1** [comment]
MVP
Nice to see you again Mark, hope you can return to us soon

**Pull request merged**
