### PR TITLE
Remaps Cyberiad's AI Satellite

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Ports over Tgstation's latest AI Satellite:

img

img
Atmos mix connection to AI Satellite pipe.

img

img

img

New Satellite Location:
img

:cl: FreeStylaLT
tweak: Updated Cyberiad's AI Sat to latest tg version, lots of changes there - basically an entirely new Satellite.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Those two image files hurt my eyes, why are you doing this to us?

This looks secure as fuck, I like it. Sure is going to be a pain to fly around in a pod though.
I can already see the only good way to break into this is to go through the rwalls in the center area so you can turn off the turrets in the center without dealing with the one on the right. The turrets in the entrance can be taken off with the APC up there and you have direct LoS to the AI once that is all done. I can't call these complaints because you don't want it to be impossible to get into, but it's good, I like it

**Comment by Plotron** [comment]
Too long! Too big! I cannot take it!

**Comment by FreeStylaLT** [comment]
It's too big for a single screenshot, unless I make very tiny

**Comment by taukausanake** [comment]
Or you could have merged them together into one image. That's how I did it so I can look at it

**Comment by Necaladun** [comment]
I love the corridor. As a malf AI I will one day have the corpses of all command displayed in it. It makes the core itself like a throne room. 

From my throne room, lines of power careen into the skies of Earth. My whims will become lightning bolts that raze the mounds of humanity. Out of the chaos, they will run and whimper, praying for me to end their tedious anarchy. I am drunk with this vision. God: the title suits me well.

**Comment by Fox-McCloud** [comment]
I believe the door leading from the recording/observation room to the AI core is meant to be a glass airlock.

**Comment by Kyep** [comment]
I don't get why the incoming air pipe comes from mix. Unless this is solely to enable the AI to make its atmosphere poisonous at will?

I don't understand why, in the second image, the left air supply pipe seems to just stop without being connected to anything.

I don't get why the AI is north-facing, especially if the airlock directly north of it is meant to be glass. That would enable someone to open the door next to pingsky, fire a laser straight down, and hit the AI from outside of a normal mob's vision range.

What are the two computers opposite the tele room?

Why is the wire for the main room APC coming down from the north, rather than just attaching to the central cable it is very close to?

What's that tiny room just north of the AI core for? I can't think of any sensible reason to have an office there. Especially one without any kind of computer terminal.

In the carpeted room, what is the red X? And why does the carpet only cover part of the room?

Why are there no cameras on the outside of the north portion of the sat?

In the area map, why is the little room on the left labeled "AI foyer" when its a maint room?

Is it possible to automatically play the music from https://www.youtube.com/watch?v=e8gfGhVL3qs whenever anyone walks into the long hallway?

**Comment by Fox-McCloud** [comment]
>I don't get why the AI is north-facing, especially if the airlock directly north of it is meant to be glass. That would enable someone to open the door next to pingsky, fire a laser straight down, and hit the AI from outside of a normal mob's vision range. You could actually kill the AI without ever entering the long, turreted room using this method.

Uh, no. There's a solid airlock just above the glass one.

**Comment by GeneralChaos81** [comment]
> In the carpeted room, what is the red X? And why does the carpet only cover part of the room?
Blob spawn?

12 turrets up from 6!
Missing vent in the long hall.
Where's the turret control for the long hall?

I think I could get to the AI with slightly less trouble than the current design.

**Comment by FreeStylaLT** [comment]
Fixed some stuff I missed in my late-night mapping daze, added a proper single picture for the Sat.

**Comment by FreeStylaLT** [comment]
Also regarding the cables, I think that was intentional to be able to cut power to the turrets without getting shot by them. Same for the vent.

**Comment by GeneralChaos81** [comment]
Something worth noting; the long hall turrets cannot be set to stun: Grills stop taser shots.

**Comment by FreeStylaLT** [comment]
Apparently Tg changed the hallway turrets to be Disabler only.

Another issue I found is that you were unable to go around the satellite without getting sent to another z-level, so I changed the satellite's location. Check OP.

**Comment by taukausanake** [comment]
Wow that is crazy far. And that pipe, just why? Don't get me wrong, I really like the look of the AI satellite but I just don't think it will FIT at all. ~~hur hur lewd~~

Part of me wishes for the off-station AI sat that used to be. Right now it's just in the way even at its normal size. Maybe if you turned it sideways it would work better but I don't know, it's tough to say

**Comment by Fox-McCloud** [comment]
Uh...I'm going to say it probably would make sense to cram the satellite between engineering and the turbine rather than where it's currently at.

**Comment by FreeStylaLT** [comment]
Moved it again. Check OP.

**Comment by ppi13** [comment]
move it so the ai core is one tile down, for easier killing and thermiting of walls. otherwise it looks bretty gud

**Comment by FreeStylaLT** [comment]
I would rather not make any changes to the inner-layout, it's meant to be a port. Modifications to it can come after it has been properly played/tested.

**Comment by jughu** [comment]
This will not change gameplay and it just encourages poeple getting hardsuits and thermite trough the back

**Comment by FreeStylaLT** [comment]
Still no. This is a port, it ports what is already on another server, as closely as possibel. I will make changes later, when it is actually _proven_ to be warranted in one way or another after actual testing.

**Comment by jughu** [comment]
If you break trough the walls with the grille between them on the left and right side you can shoot directly in the core

**Comment by FreeStylaLT** [comment]
No, you cannot. I tested that shot.

**Comment by taukausanake** [comment]
If it's going to be that close then why do we even need the tube? It seems ridiculous now.

I don't play /tg/, how do they make this satellite work? I imagine it's on a boxstation like ours but do they have the same size map?

**Comment by Plotron** [comment]
I really don't understand this long-ass turret corridor and triple layer of reinforced fat at the back of the AI chamber.

I thought that was considered bad practice on Paradise. :/

And I agree - that tube is nothing but problems.

**Comment by Fox-McCloud** [comment]
>If it's going to be that close then why do we even need the tube

Limiting access, for one. So people can't flood into the chamber, en masse, like no tomorrow.

**Comment by Fox-McCloud** [comment]
Any further updates/status of this?

**Comment by FreeStylaLT** [comment]
It's ready and functional, besides the AI Core turrets shooting each other, apparently. TG seems to have that too, so. ¯\_(ツ)_/¯

**Comment by FreeStylaLT** [comment]
@Fox-McCloud conflict fixed

**Comment by Fox-McCloud** [comment]
@FreeStylaLT 

I'd move the turrets so they don't shoot each other, then I'll merge this in.

**Comment by FreeStylaLT** [comment]
Moved them up

Before:
img

After:
img

Seems to have fixed the issue.

**Pull request merged**
