### PR TITLE
Fixes a grave mistake

### PR DESCRIPTION
**Pull request by CrAzYPiLoT-SS13**
Replaces the welder sound the recycler makes when recycling (why?) with a more suitable one. Literally unplayable.

:cl: CrAzYPiLoT
tweak: Replaced the current recycler sound with a new one.
/:cl:

### CODE REVIEW

**Comment by Gummin** [comment]
Speedmerge when?

**Comment by Fox-McCloud** [comment]
This could get potentially annoying; keep in mind that a recycler processing everything one at a time, so if someone sends a stack of 50 items down the chut, it's going to just be "BUZZZZZZZZ" for the next 100 seconds straight.

**Comment by Spacemanspark** [comment]
But... nobody really goes near the thing anyways.

**Comment by KasparoVy** [comment]
At least it won't be 'SWARMERS ARRIVALS' everytime a newjoin walks by the recycler on the way to get changed and they hear it going off on a pile of stuff

**Comment by CrAzYPiLoT-SS13** [comment]
I literally made it as not-annoying as possible, but yeah, no one comes
near it, and people who do, they stay there for a minute at most. This is
just for immurshuns.

**Comment by TheDZD** [comment]
I like the sound, but it seems like 100 volume is too loud given how the compressor can get a lot of items at once and will be nearly constantly playing the sound.

**Comment by CrAzYPiLoT-SS13** [comment]
In game, I could barely hear it. On 50 volume, I was wondering what was
going wrong because I couldn't hear it. Maybe it's just my speakers though.

**Comment by Fox-McCloud** [comment]
going to address what @TheDZD stated?

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, as I said, in my testing I can barely hear it even at this setting. I
guess it's a sound convertor error or something. I am willing to re-test
and tweak it after I'm done with the ruins.

**Comment by Fox-McCloud** [comment]
re-tested this yet?

**Comment by CrAzYPiLoT-SS13** [comment]
No, sorry. I don't want to cause problems with my ruins branch, as I'm not
that experienced with Git. Also, tomorrow is my last day of finals, so I'll
be able to get back to work soon.

**Comment by TheDZD** [comment]
Tested this locally, it's actually fairly quiet.

**Pull request merged**
