### PR TITLE
Hyposprays and Injectors resprite

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do

Resprites injectors and hyposprays. Also adds sprites for some injectors that didnt have unique sprites.
Also updates the sprites of the medical belt attachments for hypo and injector.

## Why It's Good For The Game

Old sprites get updated

## Images of changes

image

## Testing

Started th game, looked at sprites.

## Changelog
:cl:
imageadd: New sprites for injectors and hyposprays
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
Does this update their associated sprites in medical belts, or do you think they're good enough as-is?

**Comment by McRamon** [comment]
> Does this update their associated sprites in medical belts, or do you think they're good enough as-is?

oh i didnt think of a belt, thanks for reminding me! ill update it too

**Comment by Miraviel** [comment]
They look really cool. The ERT hypo does not look stabby enough for me, it's too cube-y I think, but they all look really sleek

**Comment by McRamon** [comment]
> They look really cool. The ERT hypo does not look stabby enough for me, it's too cube-y I think, but they all look really sleek

ERT hypo is medical hypo but with omnizine, currently they use same sprite

**Review by S34NW — APPROVED** [review]
bro the star trek lore CMO hypo has been removed, no more soul in paradise

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
