### PR TITLE
Recitence mech makes no sound when turning

### PR DESCRIPTION
**Pull request by Jovaniph**
Okay round two.

I believe the mime mech could be a bit more silent. It already doesn't make a sound when moving around the station so why stop halfway and not remove the turning sounds as well? This is what this PR does. It now makes no sound when it makes those 90 degree turns.

🆑 Jovaniph
tweak: Recitence no longer makes a sound when turning
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
`:cl:Jovaniph
`tweak: Recitence no longer makes a sound when turning
`/:cl:

This looks like a sensible change.`

**Comment by Jovaniph** [comment]
shit I fucked up

**Comment by ktoma36** [comment]
Ooooh yes, now I can terrify nuclear operatives even more by bursting silently from a maintenance tunnel with out all the obnoxiously loud turning sounds.

**Comment by Anasari** [comment]
Good change

**Pull request merged**
