### PR TITLE
Adds trashcans, adds them to the metal construction menu.

### PR DESCRIPTION
**Pull request by veganzombeh**
They're essentially a copy-paste of disposals units that aren't connected to disposals. They can be made with metal and anchored/unanchored with a wrench. They'll probably make it a little easier for janitors to cope with the trash that is inevitably everywhere by the end of the shift.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
copy paste = bad. It would be better for these to be the parent object, and then have the disposal-specific behavior in a child?

**Comment by Fox-McCloud** [comment]
Errr---there's...already trashcans in the code.

**Comment by Spacemanspark** [comment]
Why don't we use them?

**Comment by veganzombeh** [comment]
What are the existing trash cans called? I checked if there were any before making the PR and couldn't find any.

**Comment by Keilden** [comment]
One of the away missions have them. Think its the one with a xeno nest

**Comment by veganzombeh** [comment]
Yep, we already have trashcans, although they're essentially crates, whereas the ones I made are a bit more like disposal units. I'm going to go ahead and close this PR until I get around to making the improvements Ponies suggested.

**Comment by veganzombeh** [comment]
Yep, we already have trashcans, although they're essentially crates, whereas the ones I made are a bit more like disposal units. I'm going to go ahead and close this PR until I get around to making the improvements Ponies suggested.

**Pull request closed without merging**
