### PR TITLE
Updates Sprites for Wrapped/Present Objects + A Few other containers 

### PR DESCRIPTION
**Pull request by Sirryan2002**
## What Does This PR Do
#17502 gave us a lot of awesome crate sprites, however stuff like wrapped crates were missed. Additionally, I touched up a few other boxes to be consistent with the new style.

## Why It's Good For The Game
Consistency between sprites for crates is awesome.

## Images of changes
LEFT OLD; RIGHT NEW
160302448-6c741de4-bf7a-4d0f-893d-db563584682a

## Changelog
:cl:
imageadd: Sprite updated for wrapped objects
imageadd: Sprite updated for presents
imageadd: Sprite updated for Ship Packs
imageadd: Sprite updated for Large Boxes
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
converting to draft to come up with a few sprites b/c locker/gift stuff is also inconsistent :D

**Comment by atteria** [comment]
Ah shit, I missed this.

**Comment by Sirryan2002** [comment]
> Ah shit, I missed this.

oh well, I'm having fun with it so no harm done

**Comment by Sirryan2002** [comment]
Now out of draft, updated all information + added all the sprites.

**Comment by Sirryan2002** [comment]
petcrate
considering adding this to the PR aswell

**Comment by Sirryan2002** [comment]
CritterCrateDemo
adding this to the PR

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
