### PR TITLE
Qol improvements for the ghost bar

### PR DESCRIPTION
**Pull request by Fluffyzack21**
## What Does This PR Do

 Made the ghost bar kitchen a bit bigger and added a vender and added a couple of Trash bins

## Why It's Good For The Game
 QOL improvements for the ghost bar are good, they have nowhere to put trash and the kitchen is a bit small

## Images of changes
 
Screenshot 2023-11-30 140647

## Testing
 Spawned myself in at ghost bar and saw everything was working fine and had air to breath

## Changelog
:cl:
tweak: increased ghost bar kitchen size and added some trash bins
/:cl:

### CODE REVIEW

**Comment by Jaredw224** [comment]
Oh yeah and updated picture of ghost bar so no one complains 
Screenshot 2023-11-30 150247

**Comment by S34NW** [comment]
Please merge `upstream/master` into your branch to fix CI failing due to external factors.

**Review by Sirryan2002 — APPROVED** [review]

**Review by S34NW — CHANGES_REQUESTED** [review]
image
I think you may have messed something up with the merge master

**Comment by Fluffyzack21** [comment]
> image I think you may have messed something up with the merge master

when I merged the master on it fucked the entire PR

**Pull request merged**
