### PR TITLE
One-way Airlocks!

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
Adds unrestricted access to certain airlocks when approached from a certain direction.

**What does this mean?**
It means you can now leave brig once your timer has ended without security escorting you out, you can also leave the surgery rooms once your surgery is finished and no longer need to rely on the AI every five steps as a lot of the common areas people get stuck are now possible to exit.

Credit to TG coder zxaber for this one!
**Images of sprite/map changes (IF APPLICABLE):**
The arrows show the directions you can go even if you don't have access. You can now exit maints if you do not have an ID but you cannot enter maints without maint access.

Brig:
image
Medbay:
image
image
image
science:
image
image
cargo & engineering:
image
image
Blueshield & NT reps office:
image

**Changelog:**
:cl:
add: After many complaints about being stuck in medbay. NT has modified all the airlocks on the station to allow leaving certain departments without requiring an respective ID. This new modification is indicated by a white light near the airlocks in the direction of unrestricted access.
add: New unrestricted access can be built by NT engineers through modification of the airlock electronics.
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
Wasn't there a PR that already did this recently?

**Comment by Couls** [comment]
It was affected's turnstile PR but I don't think it went through

**Comment by Kyep** [comment]
This is great. I love it, and support it.

My only suggestion (and it is a suggestion, not a requirement) is that the airlocks be marked somehow in-round. Perhaps a yellow arrow in the relevant direction? The green chevron would work too if it was maybe a little smaller and always in a fixed position on the airlock.

**Comment by AffectedArc07** [comment]
@Citinited @Couls I did turnstiles but they looked awful and werent constructable IC, so thats what held it off

**Comment by Couls** [comment]
@Kyep 
image does this look like a good enough indicator? the floor light to the south means you can approach from the south to open the door without access

**Comment by Citinited** [comment]
I don't like the look of the floor light - I see what you're going for but it's too bright and big, and doesn't make sense in certain situations. (like if the door was unlit).

Not sure what I'd suggest instead, but what about a set of green lights on the side that has all-access?

**Comment by Kyep** [comment]
Citi is correct, its too big and too bright.
You'd be better off with a green light or icon on the door itself.

**Comment by taukausanake** [comment]
Maybe something that shows in the middle of the door would be better. Having it on the edges doesn't look good.
Can you set doors to do this when constructing them? I don't think it would be a best merge unless you can first

**Comment by Couls** [comment]
It would take me a bit to figure out to add the code to airlock electronics as that’s UI stuff which I haven’t really learned yet which is kinda the only reason I didn’t already implement it, I’ll see if i can figure it out, worse case scenario I’ll make a PR in the future for it seperately once I get more comfortable with coding the UI

**Comment by Couls** [comment]
New sprites, let me know if the glowing is too noticeable, I could just leave it as a lime or dark green light if that's the case
5d1986c7b67bc086299271

**Comment by taukausanake** [comment]
These are better. Not sure if they're the best but they are better

**Comment by TDSSS** [comment]
those lines don't look like a part of the door, imo. I think it would look better if they were connected.

**Comment by Couls** [comment]
They're meant to be on the floor near the doors and not actually part of them

**Comment by Couls** [comment]
@taukausanake 
image
image

**Comment by Couls** [comment]
Updated the sprites a bit more, put them closer to the airlocks and removed the flickering
image

**Comment by taukausanake** [comment]
I like these. These are great. The flickering wasn't bad I don't think but that's to personal opinion then.

I don't know if Blueshield and NT Rep should have one-way doors. They are offices and you don't normally have other people inside there. Plus, if you do have someone inside there then you can allow anyone else to walk in. I would reserve these for main hallway accesses, the foyers for departments and not really the rooms inside them. In the case of surgery, I understand that someone might be left inside there but then that's at the fault of the doctor and they failed to complete their job of making sure you are healed. They should have to let you out of the room and you can walk the rest of the way out. But maybe you have someone, maybe an antag or victim of an antag, who doesn't want to be in surgery and now they can just run away. I'm still for this, but maybe some of these rooms should have internal lock buttons that drop and raise the bolts.. Just a thought

**Comment by Couls** [comment]
I don’t know if you want to trap someone inside surgery it’d be much easier to just put them to sleep with anathesia and the like, and the blue shield and NT rep offices aren’t that high value areas, the reason I left it in the blue shields office is because he doesn’t have a door button and the NT reps office might see a lot of visitation by people with SOP complaints and requests, thankfully there’s a mapping helper and it’s quite easy to modify this and even remove it in future PRs if you’d like to do so

**Comment by Couls** [comment]
If the sprites are good then this is ready

**Comment by craftxbox** [comment]
If im to be honest, the one-way light thing doesnt really give the feeling that 'oh i can go this way but not the other'

**Comment by Ralta** [comment]
I uh...I don't understand why you actually _need_ any indication that you can go through a door from a direction.

This is a game where the door literally buzzes at you if you can't open it; it would become extremely obvious to someone that they can leave when they invariably try to open the door and it opens. I don't see the need for extra sprites which, in my opinion, detract from the look of airlocks.

One-way airlocks are a good alternative to Turnstiles (of which I am a fan). That said, the reason turnstiles were good for brig areas is because you couldn't walk back through the turnstiles the wrong way. If someone opens a one-way door, they can just sit there and hold it open. Or equally, they could open the door and get shoved out the way by someone on the other side. 

I fully appreciate that's how doors _normally work_, but in situations where someone might be trying to leave the brig after their sentence is up, they could reasonably hold the first door open to the brig and make it inside Sec much more easily.

In spite of my nitpicking, I do really like this concept.

**Comment by Citinited** [comment]
I think you need the lights as otherwise it can be confusing as to why the door didn't open for you. Was it directional, or do you just not have access, or is there something else stopping the door from opening for you? The default state for a door is to not be directional, so therefore seeing at a glance that a door isn't on the default setting is IMO a good thing.

**Comment by Couls** [comment]
> I fully appreciate that's how doors _normally work_, but in situations where someone might be trying to leave the brig after their sentence is up, they could reasonably hold the first door open to the brig and make it inside Sec much more easily.

This is why I only made the doors leaving brig from the cells one-way, any further than that and you need access so breaking into security is still going to be a challenge and security will certainly see you coming if they're in processing or in the hall

**Comment by AffectedArc07** [comment]
Port of: https://github.com/tgstation/tgstation/pull/39147

**Comment by Evankhell561** [comment]
I would prefer that this be limited to med, brig and maint

**Comment by Couls** [comment]
This is just the first commit and it’s quite easy to add and remove unrestricted access, I think we should just see how it plays for now before deciding the places that do and don’t need unrestricted access

**Comment by Ralta** [comment]
Fair point. I'd like to see it test-merged and as you say, it can always be amended.

**Comment by SomeSortaSquid** [comment]
The only issue I have with this idea is that what's a really cool convenience thing will be used for trespassing and stealing.
My point is that sometimes I'd rather have a talk with Baldie McGrey as to why he's holding a set of engineering tools, up to and including a hardsuit, or what did he take out of chemistry.
These changes allow them to ignore the dreaded talking. Once you break in, there's no way for the department personnel to stop you. And they know that once they pass that airlock, they're free, because Security will never bother even searching them if they aren't caught trespassing.

It's a really great and convenient idea, especially for engineers and paramedics (less hacking/screaming at AI). It also makes taking people into departments more appealing, as you don't have to open every single airlock on their way out.
The question is, is it great enough to warrant empowering people who will abuse it to make stealing everything behind one-way unrestricted airlocks even more trivial?

**Comment by Couls** [comment]
Areas that greytide wouldn’t normally found in still have restrictions, sci chem and medchem can’t be left from the inside same goes for all command areas and most parts of brig. Meaning you can still catch trespassers in the act, it’s only on doors that lead to public areas like lobbies and the like

**Comment by Allfd** [comment]
> It means you can now leave brig once your timer has ended without security escorting you out,

It also means, if the officer goes SSD, or slips, or you have a handsfree stun ability, you can now just run out of the brig.

Does this check for handcuffed status?

**Comment by Couls** [comment]
I doubt that’s that big of an issue, you can’t run from perma and you’re asking for trouble if you escape from a 5 minute sentence using anti stuns, as I said earlier there’s no unrestricted doors on the processing or perma side of the station just the area with the four cells can be exited from the inside I also have no clue how it treats handcuffed so I’ll check that when I get the time

**Comment by Allfd** [comment]
> and you’re asking for trouble if you escape from a 5 minute sentence using anti stuns,

This is what tide is all about.  Asking for trouble.

**Comment by Couls** [comment]
Unrestricted airlocks do not open while handcuffed

**Comment by TDSSS** [comment]
Doesn't tg have something like this, maybe you can take sprites from there?

**Comment by Couls** [comment]
the TG sprites were the original ones that people didn't like

**Comment by Allfd** [comment]
The tg ones are pretty awful

**Comment by variableundefined** [comment]
Multiple map conflicting PR at the moment. I'll get to this one as soon as possible.

**Pull request merged**
