### PR TITLE
Disable IPC Genetics, Revert Incendiary Mitochondria

### PR DESCRIPTION
**Pull request by SamCroswell**
- Instead of incendiary mitochondria being an uncounterable and
untraceable method of dealing massive mounts of burn damage to someone,
it has been reverted to what the power was originally.  It will now
ignite the user when cast. I realize this isn't very useful, but the
alternative is the power being removed altogether.

- IPCs can no longer gain genetic powers, or use injectors. It was
requested I make them unable to use injectors at all because they take
toxins damage they can never fix from using the injectors, and it would
be pointless for them to use them with genetics powers not working on
them anymore.

### CODE REVIEW

**Comment by SamCroswell** [comment]
My apologies to @TheDZD, who created the admins logs for this genetic power. I've also left his logging system in the comments, in the event we decide against using my changes for the power.

**Comment by Markolie** [comment]
Probably better to check for if(ishuman), and if so typecasting carbon/human to, say, H. You can then check for H.species.flags and IS_SYNTHETIC without having a snowflake check for machine people.

**Comment by SamCroswell** [comment]
My mistake, not sure how I missed that.
I'll have it fixed in a moment.

**Comment by TheDZD** [comment]
You might want to include a message to the IPC injecting themselves that it would have no effect on them, considering a majority of people don't look at Github commits, and would assume genetics is broken.

**Pull request merged**
