### PR TITLE
Anti-Meta Paraphernalia

### PR DESCRIPTION
**Pull request by TheDZD**
- Adds in bite sounds and attack verbs to the space carp plushie as per tgstation/-tg-station#8777.
 - These trigger upon clicking the carp in hand, or attacking something with the carp.
- Adds in foam armblade as per tgstation/-tg-station#7387.
 - Has its own unique item sprite, but the in-hand is the same as normal changeling armblades, however it shows up as "foam armblade" when examined.
- Makes the improvised stun prod w_class 4, meaning it can no longer fit in backpacks.
 - This is mainly to remain consistent with spears, which are assembled from similar materials, and have a w_class of 4.
 - People will without a doubt dislike this change because they love having a free instant stun weapon hidden in their bag. I'd be more than willing to remove this change if the maintainers ask.

### CODE REVIEW

**Comment by tigercat2000** [comment]
:+1: :heavy_multiplication_x: 100

**Comment by fj45** [comment]
Stunprods were OP.

**Comment by Spacemanspark** [comment]
And just like that, we avoided the shitstorm /tg/ had when a coder attempted to remove spears, stun prods, and cable cuffs.
How do people carry around stun prods now? Do they fit on a belt or in the backpack slot?
Or do they not carry them around at all? (Preferable.).

**Comment by TheDZD** [comment]
@Spacemanspark They need to be carried in-hand.

**Comment by Spacemanspark** [comment]
Perfect.

**Comment by jack-fractal** [comment]
I am happy to hear this. The number of greytide with stunprods in their bag...

**Comment by Cheridan** [comment]
@Spacemanspark To be fair, that coder's intention was to create a discussion about the item. Which he kinda did, though discussions on /tg/ resemble shitstorms from a distance.

**Comment by Spacemanspark** [comment]
@Cheridan I agree with that, I more or less mean that there would have been a shitstorm here as well if we'd done the same thing.

**Pull request merged**
