### PR TITLE
Mech Balance Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just a few mech balancing tweaks from TG

- Slightly lowers the speed of the Oddy
- Slightly lowers the speed of the HONKER
- Mining RIPLEY starts off with a mining scanner and ore box--has a chance to start off with a plasma cutter.
 - This is the RIPLEY that's a prize for miners in some artifact rooms.
- Increases the amount of tool slots for the RIPLEY and firefighter RIPLEY
- Updates the armor values for the RIPLEY and firefighter RIPLEY (generally an increase, though the regular RIPLEY's initial bomb armor is lower).
 - Maybe people will actually spend the extra time and resources for firefighter RIPLEY's now.
- Increases the health, armor, and temperature resist of the Death RIPLEY.

### CODE REVIEW

**Comment by tigercat2000** [comment]
I really don't think the Ody should be slowed down at all.

**Comment by Robertha89** [comment]
I don't see why any of those mechs should have a speed slowdown.
Odysseus does what it does best, and that is all it need to do.
The Honker is supposed to be fast, so it can also be annoying.
and the Death Ripley is adminspawn only, a rare one and that.

Also, do mechs even take fire damage at all?

**Comment by Fox-McCloud** [comment]
It's still fairly quick and allows it to accomplish its purpose--it's just not cross the station in 10 seconds quick anymore; it'll be the same speed as the Gygax (without the boosters activated).

**Comment by Robertha89** [comment]
Yes, it's called earsmuffs for the honker, and from 3 to 2 is not 'slightly' lowering the speed, it's drastic lowering of speed. Another thing that stops the honker is the fact that using the air horn eats a large amount of power. Not to forget that people tend to attack the honker en-mass when they see it.

**Comment by Earthdivine** [comment]
Very much yes for the Firefighter buffs, that's a very underused mech for how good it is.

The Death RIPLEY feels odd to me, it's an admin spawn so its meant to be stupid, and if we want to give it to the crew we generally edit it's values anywas.

>Yes, it's called earsmuffs for the honker

It's there only one pair on the station, and that's in security?

**Comment by KasparoVy** [comment]
And the pair in the science lab

**Comment by TheDZD** [comment]
Death RIPLEY nerfs aren't really that needed, considering it's admin-spawned only, and it is more of a joke mech than anything else.

**Comment by Spacemanspark** [comment]
To be fair, engineering has a pair or two of earmuffs.
:+1:

**Comment by Fox-McCloud** [comment]
I'll revert the DEATH RIPLEY one--as that's a more than valid point.

**Comment by Fox-McCloud** [comment]
Reverted+buffed the stats on it.

**Pull request merged**
