### PR TITLE
Removes Ancient Storage Codersprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the sprites for the backpack close icon.

It's an ancient codersprite that looks atrocious and doesn't blend in or match the rest of the inventory.

This updates it--it now actually looks like it belongs.

New:
img

Yes, it's smaller, no it doesn't really make all that much of a difference, especially considering the whole entire box is solid, as opposed to just the "X" letter itself being solid.

:cl: Fox McCloud
add: updates the close icon for storage to not be a trashy  codersprite
/:cl:

### CODE REVIEW

**Comment by Citinited** [comment]
❌

**Comment by FreeStylaLT** [comment]
🦊 🚫 ❌

Fox hates the red cross, confirmed.

**Comment by TDSSS** [comment]
Huh. I didn't think it looked that out of place, didn't know it was a coder sprite. Well, replacement looks fine so whatever.

**Comment by TDSSS** [comment]
Honestly, I'm not sure a small left-pointing triangle actually tells you anything about what the button does. Like...why is that close? You can probably figure it out through trial and error but a nice big X is a much more universally accepted way of saying close.

**Comment by JKnutson101** [comment]
I remember the feeling of first working with the interface and how much of a convoluted mess the whole thing felt no matter which server I was on. X or < won't change that new player experience I feel, and I do think the < looks slightly nicer.

**Comment by taukausanake** [comment]
> I remember the feeling of first working with the interface and how much of a convoluted mess the whole thing felt

omg the feels from when I first started playing. Thank you for reminding me

**Comment by AffectedArc07** [comment]
What about other themes?

**Comment by KasparoVy** [comment]
The oldschool theme should keep the codersprite lol, for sure.

**Pull request merged**
