### PR TITLE
Prize Counters and Metastation Fixes

### LINKED ISSUE #2932: Metastation: There are NO security belts in Brig Equipment Room

### LINKED ISSUE #2939: Metastation: Turbine room, turbine access doors are bolted
There is no switch to open or cycle the doors correctly. The AI or an engineering has to unbolt them.

### LINKED ISSUE #2946: Metastation: Atmos pipes - connectors scattered in maint aren't connected
I don't think TG use supply/scrubber pipes do they? Connectors scattered around maint that are meant to be connected to the supply system are not connected to the supply pipes they are located at:

Aft Starboard Solar Access
Aft Port Solar Access - Storage Room
Storage Room above Vault
Storage Room beside Recreation area
Central Emergency Storage beside Bridge
Medbay Emergency Storage
Aft Emergency Storage above Robotics
Research Emergency Storage
Storage Room beside Atmos
Port Emergency Storage beside Arrivals
Possible connector on AI sat?
Starboard Emergency storage beside Engineering

### LINKED ISSUE #2947: Metastation: External Air Injectors
External Injectors are off by default and are not connected to the scrubber system. They are located:

South Virology
Toxins Mixing Chamber
Turbine Room (2) External and Internal - As gas pump is offline outside the Turbine room

### LINKED ISSUE #2948: Metastation: Turbine room lacks a Turbine
Presumably the expectation is that science would build it I guess.

### LINKED ISSUE #2949: Metastation: Account database / ATM's
There isn't an account database computer, or ATM's.
* Due to the former, you can't use vending machines, slots, etc.
* The cause of #2938

### LINKED ISSUE #2951: Metastation: Bridge, command halls missing tiles
The bridge & neighboring command halls use some dark blue striped floor tile that doesn't exist so it's falling back to the underfloor sprite.

### LINKED ISSUE #2952: Metastation: missing fax machines
IAA room doesn't have fax machine, many (all?) heads missing them too.

### LINKED ISSUE #2959: Metastation: Custodial Closet Lacks a Space Cleaner Dispenser
This means they have to use water. Slippery, shitty water.

### LINKED ISSUE #2964: Metastation: No Vending Machine in Cargo.
Had a look about, couldn't seem to find one.

### LINKED ISSUE #2967: Metastation: Showers don't have curtains.
ERP is banned, needs correcting.

### LINKED ISSUE #2968: Metastation: No Psych Office
Squishy would be disappointed. Not sure where to slot it in, though. Maybe remove a maint room near Medbay, they're big enough.

### LINKED ISSUE #2976: Metastation: Brig phys has no locker and no sleeper
about the sleeper, I'd replace the useless morgue tray with a sleeper.

### LINKED ISSUE #2977: Metastation: Surgery rooms don't have bone gel, setter, and fix-o-vein

### LINKED ISSUE #2983: Metastation: Incorrect display case in captain's office
Display case should be /obj/structure/displaycase/captains_laser instead of /obj/structure/displaycase.

### LINKED ISSUE #3514: [Metastation]Chemistry lacks welding fuel tank
While making a change, I noticed that medchem lacked a welding tank. Is this deliberate?

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Temporarily adds a prize counter to the station
- Cyberiad: Bar
- Metastation: Dorms / Fitness Room
 - Also moved around the arcade machine and some lockers to accomodate

Adds a FULLY UPGRADED prize counter to the Ninja Holding Area/Bar
- This one is not temporary

Fixes a TON of Metastation issues
- Fixes #3514
- Fixes #2983
- Fixes #2977
- Fixes #2976
 - Had to shift some structure around with maint, but it should work fine
- Fixes #2968
 - Moved the Medbay Surplus Storage to off of a maint tunnel north of viro (no longer connected to medbay directly), and put the psych office where that had been
- Fixes #2967
- Fixes #2964
 - Wasn't sure if this was referring to the merch store computer or the PDA cartridge vendor, so I went ahead and added the merch store to cargo's lobby and the PDA cartridge vendor to tool storage (re-organized there too)
- Fixes #2959
- Fixes #2952
 - Magistrate's machine is in the courtroom, everyone else has their machine in their respective office
- Fixes #2951
 - Just replaced the problem tiles completely. Probably will want to make it prettier another time
- Fixes #2949
 - Account's database is in the meeting room, as the one on Cyberiad apparently could be reached by anyone with that access
 - Scattered a few ATMs around, including in the bar, near the HoP's desk, Mr. Changs, Arrivals, and some other spots.
- Fixes #2948
- Fixes #2947
 - The report mentioned toxins mixing among others, but that one seemed correct already so I didn't mess with it
- Fixes #2946
 - Had to re-pipe a couple spots to compensate for the added adapters
- Fixes # 2942
 - Moved some stuff around to accommodate, put the food cart in the freezer
- Fixes #2939
 - Also reinforced the floor like how it is on the Cyberiad
- Fixes #2932
 - Well, not exactly. Added a megaphone and EFTPOS to sec (as mentioned in the comments), since they have a secVend and their lockers for the belts, but it was already agreed that this wasn't really an issue, so this is mostly to close it.

Also fixed a couple double-pipe issues on Metastation and Metastation's z5 (asteroid) that were spamming up the chatbox when started up with pipenet errors.

There are still a couple map issues left with Meta, but they are things that might not be map issues (see #2953), the missing sec podbay (#2926, need a good spot for that), stuff that was incredibly vague (see #2933), potentially IC things that are not bugs (#2950), or require sprites (#2937)

:cl:
rscadd: Temporarily adds a prize counter to the bar (Cyberiad) or dorms (MetaStation), and adds a max upgrade one to the Ninja Holding Area (Cyberiad z2)
fix: Fixes Metastation. Seriously fixed a lot, just read the PR description for the full list.
/:cl:

Map-merged (even for metastation stuff)

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Regarding #3154, which form of welding tank did you place within the chem lab?

**Comment by ProperPants** [comment]
Does this mean we can finally have another test of Metastation? I greatly enjoyed the variety provided by it, and I feel that others would also like playing on it (maybe we could switch between Meta and Box every so often if Meta gets totally fixed).

**Comment by Gummin** [comment]
I don't like Metastation, pretty much at all but some nice changes I suppose. :+1:

**Comment by FalseIncarnate** [comment]
I put in a normal one due to not wanting to mess with offsets and rearranging existing wall items. I replaced a table that had a single folder with the tank. Not quite parity with Cyberiad, but does the trick.

**Comment by Taaketa** [comment]
4 months later. Nice work.

**Pull request merged**
