### PR TITLE
Gives Warden Krav Maga Gloves

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Gives Warden a pair of Krava Maga gloves, just like on TG.

No, not giving this to the HoS; he already had plenty of unique and insanely powerful stuff.

This is also wayyyy too good for regular officers--the damage on it is crazy and the status effects are insanely powerful.

Also adds in a new steal objective: steal the warden's krav maga gloves.

:cl: Fox McCloud
add: Warden starts off with a pair of Krav Maga Gloves
add: New Steal objective: steal the warden's krav maga gloves
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Won't this just encourage the Warden to be an Officer? I see that plenty already.

**Comment by Lady-Luck** [comment]
Not saying I'm opposed, but won't this just encourage the Warden to be an Officer? I see that plenty already.

**Comment by TullyBurnalot** [comment]
There are plenty of ways of, ICly, curbing a Warden who wants to get their Officer on.

This seems like a good addition for handling unruly prisoners. Guess they will have to think twice before trying to take on an "unarmed" Warden.

**Comment by Earthdivine** [comment]
Wishful thinking, but if this could only work on say, people with leg cuffs, it could fulfill the role of it being used by the Warden on unruly prisoners and keep him from going supercop with it on regular crewmembers.

That said I can't think of a good reason a martial art style would only be used on people with leg cuffs. Still seems cool.

**Comment by AceMcLazer** [comment]
:+1: for me. Warden is in disarm/punch range of brig prisoners more than anyone else. A bit of extra defense should help.

**Comment by Magikarpet** [comment]
The armory provides the warden a better way to become "Officer with better gear".

The gloves are strong, but they aren't going to turn the warden into a one man valid machine

**Comment by theColdflame** [comment]
:-1: sec don't need a buff

**Comment by TheDZD** [comment]
Sounds like something that should be a steal objective.

**Comment by LittleBigKid2000** [comment]
:+1: A non-lethal weapon that can't be stolen via disarming would be great for handling prisoners

**Comment by Davdichan** [comment]
inb4 the HoS just takes them from the Warden every round just cause he can.

**Comment by Aurorablade** [comment]
@Fox-McCloud want i should do a nerfed version for regular security?

**Comment by QQCucumber** [comment]
>inb4 the HoS just takes them from the Warden every round just cause he can.

It could be protected by SOP?

**Comment by Davdichan** [comment]
Most HoSs don't care about SoP and Space Law as it applies to them. This week alone I saw a HoS with a holoparasite, one using a eshield as a personal item. One using an energy cutlass as a personal weapon, and having the balls to say it wasn't contraband because it came from mining and was called a cutlass, not a sword. I've seen HoSs take every egun from the armory while in green, HoSs who execute antags who haven't commited a violent crime or were even resisting, and then those who use their medical access to loot every first aid kit they can carry from medical like its their right. We already have problems with HoSs taking the detectives revolver if no detective is active, put something like these gloves in security and you can bet a majority of hos players will swipe them given a chance to

**Comment by Bigtimetripod** [comment]
Some HoS players are... well god... 


Heard HoS once killed a person for being in maintenance...

Woo! Epic stuff for one of my fav. Roles!

**Comment by Lady-Luck** [comment]
report that behavior, that's jobbannable

**Comment by Davdichan** [comment]
@Lady-Luck I have, and been told it was strictly an IC issue. I stopped caring.

**Comment by Lady-Luck** [comment]
>@Lady-Luck I have, and been told it was strictly an IC issue. I stopped caring.

Sadly that's usually the sort of response I get too, even though they're supposed to enforce Security SOP on an OOC level.

**Comment by Citinited** [comment]
The HoS taking them from the Warden would count as theft, given they would be unique and meant for the Warden.

**Comment by Bigtimetripod** [comment]
As IC situations have shown, people think heads are above the law... specially HoS and Captain

**Comment by Spacemanspark** [comment]
They aren't, for I shall smite them with my baton of robotic justice. :^)

**Comment by pipextiny1** [comment]
I play ward a lot of the time I think this is fucking stupid considering the fact that you have easy access to a brig full with stun weapons.
I will only use this for the novelty

**Comment by Bigtimetripod** [comment]
Gloves cannot be disarmed... its much more dangerous to go to into an cell holding baton than it is holding nothing. Ye can just give em to a officer, do not shit in others sandbox per say.

**Pull request merged**
