### PR TITLE
Revival: Return Of The Foodening

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
All credit goes to shadeykins for this PR which they gave me permission to revive

Revival of: #11575 refer to PR for information on what this changes
**Changelog:**
:cl:
tweak: food values
/:cl:

### CODE REVIEW

**Comment by Corocan** [comment]
Why was the original pull closed/deleted in the first place?

**Comment by Couls** [comment]
The original author retired from this community

**Comment by taukausanake** [comment]
Kind of curious why but okay then

**Comment by Kyep** [comment]
Objecting to this for the same reasons as I objected to #11575 (see my post there).

**Pull request closed without merging**
