### PR TITLE
Added new box sprites props to Shazbot for the sprites

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Replaces the default boxes from the crew with the new fancy ones.
Mining, engineering and ERT/CC officials have their own version.
The evidence box and the badge box also got some love.
The handcuff box is changed.
Two unused boxes, box_cross1 and box_cross2. Reply if you have an idea for them.

**Images of sprite/map changes (IF APPLICABLE):**
image

Goes in order from left to right:
ERT, Internals, Internals Eng,
Internals mining, cross1, cross2
evidence, badge, cuffs

**Changelog:**
:cl: Shazbot
imageadd: Some fancy new box sprites, props to Shazbot for the sprites
imagedel: Old cuff box is gone
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
image

**Comment by Agameofscones** [comment]
Use the green cross box for the Latex glove box.

**Comment by shazbot194** [comment]
Hey, if you guys want any more box sprites, I am more then happy to oblige. Here are just a couple examples of some other boxes I have made, and I am always looking for more.
image
_There are a lot of syndi red and NT blue boxes because I like the look of them._

**Comment by Shadeykins** [comment]
z
You're welcome.

**Comment by farie82** [comment]
@shazbot194 Ian box! But I think this will do for now. Thanks though for the offer and the amazing sprites!

**Pull request merged**
