### PR TITLE
Removes External Shield Generators

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ahhhh...It's always great to get to removel Cael code...maybe we'll eventually be rid of it all.

Either case, I know @TheDZD DZD was planning on this, and it was brought up, before, as something that would need to be done due to its very negative impact on a few game modes (nations, potentially gang, etc).

And well, it's Cael code. Need I say more?

These aren't the localized shield gens; these are the huge ones that can over half the station.

Engineering storage changes:
- moves the lamps up to where these shield gens use to be+gave one extra
- put 2 fire closets down where the lamps use to be.

### CODE REVIEW

**Comment by Plotron** [comment]
Meteor RIP.
I'm going to miss that thing! Maybe.

**Comment by Regen1** [comment]
Yay, finally removing the shield that could be abused to the extend of ruining literally every nuke ops round.

**Comment by taukausanake** [comment]
Are these things really that bad? Yeah they do seem impossible to get through but for meteor rounds, would have been nice. Is there something that could replace them in the future?

**Comment by Earthdivine** [comment]
I asked to have them removed because they break so so much, and with Gang coming up they would break even more things.

**Comment by taukausanake** [comment]
No, I understand why they're getting removed. I messed with them just a while ago. Some kind of shield generators would be nice to have after these are gone however

**Comment by Regen1** [comment]
@taukausanake http://puu.sh/mJmmK/53ad233344.png They still exist

**Comment by NTSAM** [comment]
These are the ones I never see used that look like they have a tray stuck to them, yes?
Huh.

**Pull request merged**
