### PR TITLE
Facehugger and Embryo Fixes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
- Fixes dead facehuggers infecting people
- Fixes facehuggers attempting to re-infect people who are already infected
- Fixes lack of in-hand icons for facehuggers (maybe feature? Dunno)
- Fixes up some behavior of embryo's based on TG
- Fixes embryos developing twice as fast as they should
 - Big thanks to @Tastyfish for this one.

:cl: Fox McCloud
bugfix: Fixes facehuggers hugging already infected people
bugfix: Fixes facehuggers hugging people while dead
bugfix: Fixes Embryo's developing twice as fast as they should
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
@Fox-McCloud `/obj/item/organ/internal/body_egg/New()` inserts the egg, and then calls `..()`, where `/obj/item/organ/internal/New()` inserts the egg again. Inserting an egg adds it to processing. You can just cut out `/obj/item/organ/internal/body_egg/New()` completely, as all it does is duplicate the effort of the parent call.

**Comment by Fox-McCloud** [comment]
Thanks, @Tastyfish!

**Comment by Aurorablade** [comment]
> Fixes facehuggers attempting to re-infect people who are already infected

Yo dawg...we heard you liked infections....

**Comment by Kerroman** [comment]
Does this fix the ridiculously short timer between infection and asploding?  Because that's a pretty big issue with xenos right now as well.

**Comment by Fox-McCloud** [comment]
>Does this fix the ridiculously short timer between infection and asploding?

>Fixes embryos developing twice as fast as they should 

Yes.

**Comment by Spacemanspark** [comment]
Thank God, that was horrible.

**Pull request merged**
