### PR TITLE
Replaces the changeling fleshmend skill's red cross icon with a new one, changes epinephrine overdose skill icon

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do
- Replaces the changeling's fleshmend skill's red cross with a new icon.
- Replaces the epinephrine overdose skill's icon (because it was too similar to the new fleshmend one).

kép

If the fleshmend one is not satisfactory, I have these ones as possible alternatives (with the old colours):

kép

If the epinephrine overdose's is not good enough, I am more than open to feedback on how to change it.

## Why It's Good For The Game
We should not have red crosses in the game.

## Images of changes

kép

kép

## Changelog
:cl:
tweak: The changeling's fleshmend and epinephrine overdose skills' icons were updated.
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
Thanks for doing this!

**Comment by LightFire53** [comment]
Initial red heart looks good to me

**Comment by hal9000PR** [comment]
only concern is that it might get confused with epi OD. these types of icons need to be recognisable at a glance.

**Comment by Miraviel** [comment]
> only concern is that it might get confused with epi OD. these types of icons need to be recognisable at a glance.

I'll try to come up with an icon for epi OD as well, and either add it to this PR or another one.

**Comment by Miraviel** [comment]
Added an epi overdose icon, if is it not satisfactory, I am open for suggestions. @hal9000PR

**Comment by atteria** [comment]
These are leagues better than any of the other changeling ability sprites. Nice work.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
