### PR TITLE
Fixes weird offset with beds when buckled.

### PR DESCRIPTION
**Pull request by Vivalas**
Makes it so beds and child objects have two offset vars, for x and y. Beds now use -6, so that the buckled mob doesn't look like it is lying on the side of the bed.

Before:
image

After:
image

:cl: Vivalas
fix: Buckling mobs to beds now displays them correctly.
/:cl:

### CODE REVIEW

**Comment by Anoonki** [comment]
>Insert "There has to be a better way!" commercial involving rolling the dice with the Rest verb over and over and ending up with your head under the blanket every time

**Comment by taukausanake** [comment]
So is this working as it should for every time you buckle into a bed? Sometimes you do buckle in correctly but others you don't, as well as what @Anoonki said about laying upside-down

**Comment by Vivalas** [comment]
I've never experienced those issues, but using rest to lie down isn't related to buckling in.

**Comment by taukausanake** [comment]
@Vivalas I think I've had to rest first sometimes to align myself better before buckling. Maybe check how it works with resting too or mobs that are in the laying down position?

**Comment by Vivalas** [comment]
I guess I could look more in depth to how all that w

**Comment by Vivalas** [comment]
Alright I integrated the buckle_offset behavior into get_standard_offset_y(), instead of being a snowflake feature for beds. This is what resting did it just skipped it and returned initial(pixel_y) because the mob was buckled.

**Comment by Crazylemon64** [comment]
LGTM

**Pull request merged**
