### PR TITLE
Newbies can always join as Civilian

### PR DESCRIPTION
**Pull request by Kyep**
This PR does two very simple things:

- It ensures that new players (under 10 hours of playtime) can ALWAYS join as Civilian, no matter what. This is needed because all the other jobs they might be able to join as are regularly full, resulting in them getting a blank 'choose your job' screen, and having a not-so-great first impression of the server.
- It tidies up the IsJobAvailable proc a little.

🆑 Kyep
tweak: New players (under 10 hours playtime) are now always allowed to join as Civilian.
/🆑

### CODE REVIEW

**Comment by RyanSmake** [comment]
Maybe change them to `FALSE` instead of `0`?

**Comment by FalseIncarnate** [comment]
For the sake of those who might not understand exactly what this does:

This allows brand-new players to bypass the limit on the total number of civilians that can be in a single round so they can always join as a civilian up until they reach 10 hours playtime. After the 10 hour mark, they lose this special treatment and are subject to the same limitation on total civilians as everyone else who is above 10 hours.

This does not respect the limitations imposed based on the number of sec officers. Currently, for every sec officer on station, the number of civilian roles increases. After 5 officers are on board, the limit is removed.

This PR effectively allows new players to take advantage of a understaffed security force and does nothing to higher population rounds where security is actually staffed.

**Comment by theColdflame** [comment]
does this account for alt accounts

**Comment by KasparoVy** [comment]
No

**Comment by taukausanake** [comment]
I'm kind of okay with this, because greytide server wide, but no one else will be okay with this. I don't think admins have the desire to give themselves more work to deal with shitters.

Now if there was a thing that made assistants valid over a certain population of them, you know like what some other servers have, then maybe. Too bad Paradise doesn't do that though

**Comment by Spacemanspark** [comment]
"hey ya there's a lot of jobless crew let's go on a genocide"
No.
As for the PR, I'm willing to try it.

**Comment by taukausanake** [comment]
I feel like this is going to become a nightmare.

What is the system currently? I was under the assumption that you could always play as Assistant/Civilian because you need to get game hours in somehow. What do new players do already for 5+ rounds before they can get a job?

**Comment by KasparoVy** [comment]
Observe, play as an npc or play somewhere else

**Comment by FalseIncarnate** [comment]
@taukausanake They currently can play as an assistant/civilian (or support jobs like botanist) as long as there is a job slot open for that role.

This PR effectively turns new accounts into special snowflakes that can outright ignore if there are open civilian roles for their first 10 hours on the server, after which they lose their snowflake status and will find that they can't bypass the restriction anymore.

As I stated before, current code dictates that as long as security has 5 or more officers, there is no cap on civilians for ANYONE. This PR makes it so that if there are 4 or fewer officers, new player are given exemption from this limit, meaning they are effectively being given preferential treatment over existing players since they are allowed to join as a role when others are not.

We aren't hurting for players enough to justify this kind of special treatment for new players. Even if we were, we'd be better off simply removing the limits for everyone and keeping things fair for the players who DO return after 10 hours.

**Comment by taukausanake** [comment]
Yeah, this sounds awful. I almost think five security officers isn't enough for max assistant population but that's for another PR. Even if just for about five rounds getting that many players doesn't sound good

**Comment by tigercat2000** [comment]
There's a reason we have a config option for disabling the civilian ratio cap.
This is unfair to older players, introduces concerns about fighting against smurfing, and almost seems to directly encourage "new player greytide".
This is unnecessary.

**Pull request closed without merging**
