### PR TITLE
Syndicate Hardsuit elaborations

### PR DESCRIPTION
**Pull request by Spacemanspark**
Players:
-Explains a bit further on what happens when you switch from combat mode to travel mode, and vice versa. Hopefully this will keep newer Nuke Ops players from dying less often.
http://nanotrasen.se/forum/viewtopic.php?f=12&p=34708#p33996 relevant thread.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
no strong opinion, but this seems pointless, as this has been brought up literally *once* in the allllll the months we've had nuke ops.

**Comment by Earthdivine** [comment]
It helps with newer Nuke Ops, as they will know to actually USE the combat mode for combat.

**Comment by Spacemanspark** [comment]
I see Operatives that are new forget about it and either die or take a lot of damage before figuring it out.

**Comment by Necaladun** [comment]
I've seen quite a few people ask about it, either in LOOC or ahelps - I'm all for giving people more information!

**Comment by ClaytonKelly** [comment]
This is very good information to have.

**Pull request merged**
