### PR TITLE
Add playtime option to "offer control to ghosts"

### PR DESCRIPTION
**Pull request by Kyep**
This is a tiny PR that offers a customizable minimum number of days requirement to VV -> Offer Control To Ghosts command.

This means that, for example, when admins need to replace a SSD nuke op, we can choose someone with 5, 10, 20, or 30+ days of account age. Rather than potentially getting a day 0 new person.

This is intended to help with setting up characters for events, replacing antags, etc.

No CL since it is an admin tool, invisible to users.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
You might as well hook up the XP counter into this thing. At this point we have people with over 24 hours of game experience and by the time the PR gets merged it will be even higher. I think we should be safe there.

**Comment by Kyep** [comment]
If that's what people would like, I'm happy to do that instead.

**Comment by KasparoVy** [comment]
I concur with Flattest, hooking up the XP counter would probably be a good idea.

**Comment by Kyep** [comment]
@FlattestGuitar @KasparoVy changed

**Pull request merged**
