### PR TITLE
Adds Direction signs around the station.

### LINKED ISSUE #13764: Escape sign hidden by other two signs
**Issue Description**:
There is a useless "Escape" sign to the left of the bar entrance.

**What did you expect to happen**: 
A sign that's not visible without knowing its there defeats its purpose.

**What happened instead**:
The sign is hidden under the others.

**Why is this bad/What are the consequences**:
Not much outside of it being useless.

**Steps to reproduce the problem**:
Join the server and go to the place where sign is. (central primary hallway, left of the bar on the wall)

**When did the problem start happening**:

**Extra information**:
https://imgur.com/a/uqzWvNR

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Adds some new Direction Signs around the station.
Fixes #13764 

## Why It's Good For The Game

Direction signs help new players to get around, and there's now a direction sign to every department.
Also adds to the """realism""" of the station, in my opinion.

## Images of changes

NSS Cyberiad 2020-07-25 180550
NSS Cyberiad 2020-07-25 180555
NSS Cyberiad 2020-07-25 180601
NSS Cyberiad 2020-07-25 180606
NSS Cyberiad 2020-07-25 180614
NSS Cyberiad 2020-07-25 180620

## Changelog
:cl:
add: Added new Direction signs around in the Port, Starboard and Central hallways.
tweak: Moved a few existing signs around.
tweak: Moved an APC slightly to make room for signs.
fix: Fixed Science Direction sign being one pixel off from the others.
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
This is a minor and fluff-y convenience, but uh.. I doubt this will get merged *anytime* soon, due to the current map situation. This is cool, though!

**Comment by SabreML** [comment]
> This is a minor and fluff-y convenience, but uh.. I doubt this will get merged _anytime_ soon, due to the current map situation. This is cool, though!

What's the current map situation?

**Comment by KasparoVy** [comment]
I thought we had these lmao! I guess it's just something I expected to be there but never realized it wasn't.

**Comment by SabreML** [comment]
> I thought we had these lmao! I guess it's just something I expected to be there but never realized it wasn't.

There's a few on the station already, but they're all in various states of buggyness.

**Comment by AffectedArc07** [comment]
> > This is a minor and fluff-y convenience, but uh.. I doubt this will get merged _anytime_ soon, due to the current map situation. This is cool, though!
> 
> @FreeStylaLT What's the current map situation?

All map PRs are currently on hold for a bit because we have a few high priority map PRs which need to go through first, and without conflicts. Last time I checked, the order was

Alarm Refactor (#13751) --> Supermatter Port (#11311) --> Map Standardisation (#12071) --> Everything else

**Comment by SabreML** [comment]
> All map PRs are currently on hold for a bit because we have a few high priority map PRs which need to go through first, and without conflicts. Last time I checked, the order was
> 
> Alarm Refactor (#13751) --> Supermatter Port (#11311) --> Map Standardisation (#12071) --> Everything else

Ah, fair enough.

**Comment by Fox-McCloud** [comment]
Personally, I think TG's directional pinpointer is the better way to handle this.

It only spawns on players who have less than X hours and can select any area on the station, thus allowing the person to follow the arrow to get to that particular area.

**Comment by SabreML** [comment]
> Personally, I think TG's directional pinpointer is the better way to handle this.
> 
> It only spawns on players who have less than X hours and can select any area on the station, thus allowing the person to follow the arrow to get to that particular area.

That would certainly work, but it only affects people that are new.

While people who have been playing for a while are very unlikely to actually _need_ direction signs, I feel they still add something to the atmosphere of the game. A bit like the coloured floors around departments.

**Comment by SabreML** [comment]
**begone**, conflict!

**Comment by SabreML** [comment]
I'm going to close this for now, just to help with the PR backlog a bit.
I'll reopen it once the mapping freeze is over, since it's not getting merged anyway until then.

**Pull request closed without merging**
