### PR TITLE
Supports +1 Janitor Job Slot

### PR DESCRIPTION
**Pull request by Kyep**
- Adds 2nd custodial closet, and biohazard suit closet, to janitor's
office. The basic gear that janitors need to function.
- Also adds 2nd janitor start position, and 2nd roundstart job slot.
- Does not add second mop or cart. There is a spare cart in maint already.

🆑 Kyep
tweak: janitor office now supports two janitor slots.
/🆑

### CODE REVIEW

**Comment by davidchan13** [comment]
Lack of second cart irks me. Having to rely on public area gear is bad taste (imagine if engineers didn't spawn with belts but had to scrounge tools from tool storage!)

**Comment by Kyep** [comment]
Realistically, I could not fit a second cart in there. And I would prefer there to be some differences in loadout between the two janitors.

**Comment by FreeStylaLT** [comment]
I am not entirely against this, a Janitor's job is never done, especially in higher pop rounds, however, I would highly suggest integrating either a larger closet, or two of them in two separate locations, as opposed to your current apparent solution of doubling the lockers, but not the rest of the equipment.

If you wish to have specific equipment / gear be fought over by the two janitors, that can be proposed, though, I would really recommend having the closet's interior support it, like having the janicart be in the center and the regular Janitor gear put to the sides.

However, I am not sure if limiting a single Janitor's equipment to what is.. shared, or not, by your comrade is a good approach, assuming that the current equipment is what a Janitor should have to be most effective, splitting it among two in an inconsistent manner which is based on either kindness or speed may cause frustration to players as they then _must_ trek out into maint and find that one cart tucked away _somewhere._ 

If you wish, I could see about increasing the Janitor slot in a similar way I've described, though, you are absolutely free to try and tweak the current PR, if you find my comments acceptable.

**Comment by Kyep** [comment]
@FreeStylaLT 
In a prior forum thread, I tried moving the custodial closet, but it generated controversy. It also left an empty room near the center of the station. Adding items and streamlining the existing closet seemed to be less controversial, and more likely to get merged. So that's what I did here.
As to splitting the items, I think it would introduce some variety to have the different janitors have different loadouts. They have mostly the same items - except that one uses the cart, and the other uses backpack/etc. The janitor's cart is a very powerful item (fast move speed, no slip). It is comprable to the secway, which is an armory item. I did not want to add another one.

**Comment by ZomgPonies** [comment]
Absolutely, a janitor's job is never done and some people actually care about keeping the station clean.

**Comment by Fox-McCloud** [comment]
With the recent downward pressure on player population, this longer is really necessary.

**Comment by Fruerlund** [comment]
A bit iffy on this one..

**Pull request closed without merging**
