### PR TITLE
Gives Mining Drills an Edge

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Givers miners an extra edge on things

That is to say, their drills now have an edge.

:cl: Fox McCloud
tweak: Mining drills now have an edge
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
I think I see the point of this.

**Comment by Fox-McCloud** [comment]
Sharp observation @Tastyfish

**Comment by Regen1** [comment]
I guess you could call it

Cutting edge technology

**Comment by Fox-McCloud** [comment]
>Cutting edge technology

What barbed accusations.

**Comment by Regen1** [comment]
I am just unsure if this will put people fighting miners on edge.

**Comment by FalseIncarnate** [comment]
I hate you all.

( :+1: for the mining buff)

**Comment by Fox-McCloud** [comment]
@FalseIncarnate 

Come on, we just want to sharpen our wits

**Comment by NTSAM** [comment]
fucking edgy

**Comment by Earthdivine** [comment]
I picked the wrong time to come back.

**Comment by Fox-McCloud** [comment]
>I picked the wrong time to come back.

Looks like you've drilled down to the root of the problem and cut straight to the chase; that's requires a pointed wit!

**Comment by fludd12** [comment]
We should also add some better suits for the miners.
Being sharply dressed always cuts through the competition.

**Pull request merged**
