### PR TITLE
Free golem Ship changes

### PR DESCRIPTION
**Pull request by DeveloperLoser**
## What Does This PR Do
Makes the Free Golem Ship larger overall, Re-Formats it and adds some things like a dedicated botany area and a nice meeting table of sorts.

## Why It's Good For The Game
I feel like the current ship is cramped. If the golems gain any traction you'll end up with 4-8 golems, all doing their own thing, as well as Mech-fabs, RND, Botany, Mechs, and Chem-machines all over the place, in addition to any trash and miner gear that gets dragged in. While it’s somewhat ugly in this state and has lots of dead space, it should be better overall for golems.

Any wanted changes as well as positive and negative criticism is welcome.

## Images of changes
Look at Map Diffs

Adds:
1 Recycler
2 Lights
2 Personal lockers (for backpacks)
4 Light tiles
4 Comfy Chairs
4 Golem ID's
6 Directional windows
7 Machine frames and a computer frame
9 Wooden tables
12 Full tile windows
14 Tiles of space overall (excluding walls/windows)
100 Wood planks

Removes:
1 Normal Resonator
2 Engine igniters
2 Engine exhausts
2 Mining Gear crates
8 Ore boxes (In favor of 100 planks, 10 planks make 1 box)

## Changelog
:cl:
tweak: Heavily tweaked the Free Golem Ship ruin on lava land.
/:cl:

### CODE REVIEW

**Comment by Sirryan2002** [comment]
Right out of the bat, there's a few problems with this map change that will need to be fixed.
- Over 50% of the equipment crates the old shuttle had are being removed. This poses a problem since that means there's now only 3 golem IDs available along with only 3 sets of miner equipment. 2 ore crates is not enough either(they're fragile you know)
- It's likely a xenobio setup will never get used and there's not actually any slimes to experiment on. I've never actually seen free golems experiment with xenobio anyway
- Having a pod is cool, but I have concerns about it being abused on Lavaland
- Mining Vendor is in a weird and hard to access spot
- There is no Welding Tank(I know it's usually blown up, however its very useful for welders)

Things I really like about this and probably should be expanded in some cases
-  Splitting up the shuttle into a few rooms, Golems should be able to split up their different setups
- Adding a recycler, trash usually become a serious problem late into the round

**Comment by Coolrune206** [comment]
> Right out of the bat, there's a few problems with this map change that will need to be fixed.
> 
> * Over 50% of the equipment crates the old shuttle had are being removed. This poses a problem since that means there's now only 3 golem IDs available along with only 3 sets of miner equipment. 2 ore crates is not enough either(they're fragile you know)
> * It's likely a xenobio setup will never get used and there's not actually any slimes to experiment on. I've never actually seen free golems experiment with xenobio anyway
> * Having a pod is cool, but I have concerns about it being abused on Lavaland (I really like the idea though)
> * Mining Vendor is in a weird and hard to access spot
> * There is no Welding Tank(I know it's usually blown up, however its very useful for welders)

To address some of these concerns:

- Golem IDs can be purchased from the Mining Points Vendor, as can some extra bits of mining equipment - though most of the more important Golem mining equipment is made in a Protolathe. The Ore Boxes can additionally be made from wood, which would incentivize Golems to either use their SeedVendor to create a small botany setup, or just create Mining Satchels of Holding like they tend to do anyways.
- Golems can acquire a grey slime extract from the Mining Points Vendor, which can be injected with liquid plasma to create a grey slime, which is all that's needed for a Xenobio setup really (monkeys can be generated from Biomass, or from more grey slime extract)
- Pod being abused on Lavaland is a legitimate enough concern, could either work it into rules to not do it or could just be coded to not function there anyways (doubt there's ever a legitimate reason someone would use it there)
- Agreed, Mining Points Vendor should probably just be near the ORM
- The Golems can avoid the need for Welding Fuel by creating Experimental Welding Tools with their easy to set up RnD, as the Experimental Welders don't need all too much technology and the Golems will have access to the materials needed anyways. If they somehow can't get Experimental Welders and desperately need welding fuel, they can always Autolathe some Welders which come prefilled. Having a Welding Fuel Tank on Lavaland is just how things go boom :P

I personally really like this PR, I play a good bit of Free Golems and think this would breathe some life into the role by giving a more clear picture to other Free Golems of what the role is capable of, that being Xenobiology, Botany, and some Space Construction/Exploration 👍

**Comment by DeveloperLoser** [comment]
@Sirryan2002 @Coolrune206 
Added 2 more mining crates and golem ID's on the table. 1 welding tank. Moved Point Vendor to the central area. And replaced the Xenobio area with a botany area, as IIRC you cannot use the Xeno console without the Xeno area, and would need a camera anyways which the station AI could use (I think).

Gonna wait on some more comments about the Space-Pod before I do anything with it

**Comment by PidgeyThePirate** [comment]
I have set up xenobiology on the golem ship before, and it works fine. You do need an AI-visible camera though.

**Comment by DeveloperLoser** [comment]
> I have set up xenobiology on the golem ship before, and it works fine. You do need an AI-visible camera though.

I have an idea and I want to know what people think of it, what if I edited the space docking location to have a decently small, heavily damaged space base with a xeno setup, the one that I had on the shuttle is pretty small and shitty, the space base would give you something to fixup, power, re-supply atmos (if you have guests) and maybe more, one issue is cult using it but I don't think that's to bad given the damaged state I'm gonna make it in, and that it spawns in the spam spot in the same Z-Level every round.

**Review by Kyep — COMMENTED** [review]
This PR should give a clear and exhaustive list of everything that was added.
Given the issues we've had before with space pods on lavaland, I'm not inclined to allow any spacepod in any lavaland ruin.

**Comment by S34NW** [comment]
Is the ORM operable in its location? Or can ores be put in from any side?

**Comment by DeveloperLoser** [comment]
> Is the ORM operable in its location? Or can ores be put in from any side?

Good spot, gonna move it in a moment because I don't believe it does.

**Comment by variableundefined** [comment]
There has been no maintainer nor head approval for 90+ days, and one head objection. 

Closing.

**Pull request closed without merging**
