### PR TITLE
Ajit Pai is no longer designing our mugs.

### PR DESCRIPTION
**Pull request by IK3I**
Makes mug sprites less obnoxious by request of a certain shady community manager.

:cl:
tweak: Comically sized mugs are slightly less comically sized
/:cl:

Imgur

### CODE REVIEW

**Comment by Shadeykins** [comment]
More like "Shadeykins is secretly Ajit Pai and made mugs the size of bar-stools"

**Comment by IK3I** [comment]
travis is hanging so I'll reopen this in a bit

**Comment by SamHPurp** [comment]
Also, fuck Ajit Pai

**Comment by IK3I** [comment]
just did a test on this and it seems to runtime, Hold off merging till I find the erroneous iconstate

**Comment by IK3I** [comment]
Ignore me, there is no runtime, something was probably assaulting my files with padlocks elsewhere to cause the runtimes. Recompiling and running it on a fresh instance made the runtime go away.

**Pull request merged**
