### PR TITLE
Baystation12's Lighting Overhaul

### PR DESCRIPTION
**Pull request by tigercat2000**
Baystation12/Baystation12#8903

>Coloured, animated, object-based lighting system with fancy luminescence.

This system is absolutely beautiful.

Entire overhaul of the lighting system, basically.

Gif's don't really do this justice, so here is some MP4's.
http://puu.sh/hIn4e/78df641df2.mp4
http://puu.sh/hIn9r/c3200e30fd.mp4

Screenie
Fireeee

More fire
Ooohh firee
Fireeeee
FIRE

Syndie base with lighting:
hehe
Todo list:
 - [X] Mapping (Shuttles require LIGHT)
 - [x] Tweaks
  - Aahhh I'll call it intentional, who doesn't like a dark station
 - [x] Figure out a few odd bugs

### Extras
Starlight system
Space turfs will now give off actual light if setup in the config

space
Those walls would normally be pitch black.
This is set to '2'.

### CODE REVIEW

**Comment by Mloc** [comment]
*steals vids*

**Comment by Mloc** [comment]
also what are the odd bugs? might be something on my end.

**Comment by tigercat2000** [comment]
@Mloc Two things so far; Not sure if it's caused by my port or not, but lighting overlays show up in the right click menu, the alt click menu, and this somehow happened bugz

**Comment by Mloc** [comment]
Right clicking thing is a debugging oversight, I'll fix that thanks.  Can you show me the light layout in the lit room?

**Comment by tigercat2000** [comment]
kitchen
I think this is what you meant. And I fixed the alt-click weirdness by just adding the lighting overlays to the rune ignore list, if you run into the problem.

**Comment by Mloc** [comment]
I mean the room next to it, where it's fully lit in the previous picture.

**Comment by tigercat2000** [comment]
Ah, okay, heh. easily confused

**Comment by Mloc** [comment]
Working as intended unfortunately.
The only lights that are strong enough to shine into the dark room are the two next to the window, but byond's view() doesn't let them see into the room. You can test this yourself by standing on top of the lights as a mob that doesn't have xray.

**Comment by tigercat2000** [comment]
That's actually pretty funny, guess I can cross it off my bugs list. The system is still pretty :P

**Comment by Mloc** [comment]
happens in the old system too :p

**Comment by Spacemanspark** [comment]
:+1:

**Comment by tigercat2000** [comment]
@Mloc also you said that the right-click stuff was debugging? Not to rush you, but if you remember where it is :P

**Comment by Mloc** [comment]
See the edit of that comment.

**Comment by ZomgPonies** [comment]
Merge conflicts.

**Comment by tigercat2000** [comment]
*cri

**Comment by Fox-McCloud** [comment]
Pics of different fire colors would be great---if it's true Goon-style colored fires, it'll look awesome.

**Comment by tigercat2000** [comment]
@Fox-McCloud Sorting out merge conflicts will do next

**Comment by M3hillus** [comment]
Do cameras properly interact with this lighting system? I know previously if you had taken a photo near a computer that emitted light, it ended up looking like a tile of that lights color.

**Comment by Mloc** [comment]
no, that'll need to be fixed by someone who knows camera code better than me.
Basically the blending isn't respecting the new blend_modes, so it shouldn't be -too- hard to plug them into Blend().

**Comment by tigercat2000** [comment]
@M3hillus It actually just entirely ignores light now. Interestingly.

**Comment by M3hillus** [comment]
@tigercat2000 chalk it up to camera flash.

**Comment by tigercat2000** [comment]
@Fox-McCloud Fire colors are in the top post, they are pretty but it requires around 20,000 temp to get to blue. So probably won't happen often.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

Yeahhhh that's pretty much Goon-styled fires to a "T"; I take it it smoothly transitions from one color to the other as opposed to specific cutoffs (like False's)?

**Comment by tigercat2000** [comment]
@Fox-McCloud Yep, it calculates the RGB based on a temperature-to-color algorithm and then uses animate to boot, it's smooth lighting like the rest of this system.

**Comment by ZomgPonies** [comment]
Also we'll need to start looking at the overall station lighting. I tend to think we are currently over-lighting the station. We'll probably be able to optimize and remove some of the lights once this is merged.

**Comment by tigercat2000** [comment]
@ZomgPonies The station is actually pretty dark with this enabled. The central hallways aren't even 100% lit (but they mostly are)

**Comment by Fox-McCloud** [comment]
My big fear with this port, though, is explosions.

Lighting already runtimes and is fairly expensive with explosions (to the point where all lighting calculations are delayed a few seconds to deal with it)--given that this system seems quite a bit more CPU intensive...I do have some performance concerns about it.

I'm not concerned, at all, from a feature standpoint.

**Comment by tigercat2000** [comment]
In my experience, Lighting runtimes from explosions because no one ever bothered to code a sanity check for what happens when an area doesn't have a lightswitch

**Comment by fj45** [comment]
Tiger, this is amazing. Thank you so much.

**Comment by tigercat2000** [comment]
@Mloc Ah, I just saw, thanks. Also:
>There's no real way to remove it in the webclient unfortunately.

We aren't webclient compatible at all anyways, :P

**Comment by Fox-McCloud** [comment]
Question, is this going to kick out players who don't have hardware acceleration? While I wouldn't say no to this feature if it did, I'd still like to know, ahead of time, so I can inform players.

Goon switched to a new lighting system about 1.5 years ago and it *requires* hardware acceleration--if you don't have it, everything looks black.

**Comment by tigercat2000** [comment]
@Fox-McCloud I didn't actually test that, but if I recall correctly, some of our other things force people to use hardware acceleration anyways.

**Comment by Fox-McCloud** [comment]
@tigercat2000 

That's fine--it almost never comes up in most cases (as even a lot of really crappy integrated cards are starting to have hardware acceleration), but would still be nice to test out.

**Comment by tigercat2000** [comment]
@Fox-McCloud I'd say playing without hardware acceleration is a no-go.
looool

**Comment by Fox-McCloud** [comment]
lol. Yuuup--thought so.

**Comment by fj45** [comment]
Its err..."art."

**Comment by tigercat2000** [comment]
Not suprising, it abuses the hell out of animate() and alpha variables (which is beautifulll)

**Comment by Fox-McCloud** [comment]
@Mloc 

You plan on making any changes to species and vision since this makes things absolutely dark if there's no light? This pretty much means any species vision modifiers are not 100% moot and pointless.

**Comment by tigercat2000** [comment]
@Fox-McCloud / @ZomgPonies / @TheDZD I'm going to consider this merge-ready, since it is already merged on Bay12.

**Comment by ZomgPonies** [comment]
6 hours baby ;)

**Pull request merged**
