### PR TITLE
Converts the verbs you get as a guardian host, to action buttons

### PR DESCRIPTION
**Pull request by SteelSlayer**
## What Does This PR Do
Converts the three verbs you get as a guardian host (Communicate, Recall Guardian, and Reset Guardian Player) to action buttons.

## Why It's Good For The Game
Using verbs is clunky. Improved code. No more having to loop through the hosts contents (or worse) to find the guardian every time you clicked one of the verbs.

## Images of changes
From left to right: Communicate with guardian, Recall guardian, and Replace guardian player. The sprites for the first two are identical to the buttons guardians themselves have. The third is a new created one.

holo actions

## Changelog
:cl:
tweak: Guardian host's guardian-related verbs have been replaced by action buttons.
imageadd: Added a new sprite that is used by the "Replace guardian player" action button.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Please keep the verb variants. I like to macro `Communicate`, and this removes the ability to do so

**Comment by SteelSlayer** [comment]
Eh, the goal was to cut down on verb tabs, but I'll admit, macroing communicate is useful.

**Comment by SteelSlayer** [comment]
Actually, there's no way, with verbs, to avoid searching the host's contents *every* time you want to speak or recall your guardian, which makes these shitcode in my book.

The point of this PR was to purge this stuff so, I'm going to have to say.. I won't be re-adding them. If that gets the PR denied, so be it.

**Comment by Spacemanspark** [comment]
I wish the action buttons had a method of macroing for at least a few of them.

Toggle-helmet for example.

**Review by Kyep — APPROVED** [review]

**Pull request merged**
