### PR TITLE
Changes the look of the station intercom

### PR DESCRIPTION
**Pull request by orelbon**
inter
Suggestions appreciated.

### CODE REVIEW

**Comment by LightFire53** [comment]
Looks nicer than the current one

**Comment by orelbon** [comment]
Its supposed to be a gif, i dont know why its not showing the animation.

**Comment by taukausanake** [comment]
You somehow didn't set it to loop. It animates but doesn't loop over

**Comment by Markolie** [comment]
👍

**Comment by KasparoVy** [comment]
@orelbon This is what Taukausanake was talking about, IDK if the animation is working properly rn or not but if you want it to animate continuously, you're going to need 'infinite' looping selected

Also, is the jagged wave-form supposed to extend off to the right, retreat to the left and then extend out to the right again or extend out to the right then start from the left and extend out to the right again?

If the former, rewind being kept on is fine. If the latter, rewind needs to be turned off

See picture below
intercom

**Comment by taukausanake** [comment]
@KasparoVy I was referencing the actual gif image rather than the dmi icon, but good find. Really shouldn't be rewind in my opinion

**Comment by orelbon** [comment]
@KasparoVy yes it's supposed to be on rewind and i do think i have it set to indefinitely, ill check.

**Comment by orelbon** [comment]
@KasparoVy Thanks, that was it.

**Comment by taukausanake** [comment]
Really though, rewind? I thought it would look better just going forward, like a sound bar or something, can't remember what they are called

**Comment by orelbon** [comment]
@taukausanake without rewind it just looks like it's starting the animation over again without any smooth transition.

**Comment by taukausanake** [comment]
@orelbon Yeah, I kind of think that would be the point for sound waves in an intercom but I might be missing something

**Comment by orelbon** [comment]
@taukausanake My take on it is that its increasing because of detected sound then drops back down once the sound stops

**Comment by gt33** [comment]
merge this please

**Comment by orelbon** [comment]
Seems like not everyone is sold on the idea. Any suggestions?

**Comment by gt33** [comment]
Give air alarms and APCs a similar texture. Also, i've ported this PR over to my paracode fork.

**Comment by orelbon** [comment]
@gt33 Maybe leave that for another PR, it's just gonna make for more disagreements.

**Comment by Crazylemon64** [comment]
It might be a bit nicer if the waveform had some time to flatten out and fade away, instead of constantly being in a state of creation
(not a requirement though)

**Comment by orelbon** [comment]
@Crazylemon64 hows this?
inter

**Comment by Fox-McCloud** [comment]
You need to post a picture of it from in-game, otherwise, it's not an accurate portrayal.

**Comment by orelbon** [comment]
My ports don't let me host a server so i cant. Unless you're good with a screenshot from the map editor. 
capture

**Comment by gt33** [comment]
You COULD host a local server, you can still access it from your own PC, even if you can't port forward.

**Comment by orelbon** [comment]
@gt33 How could i do it?

**Comment by gt33** [comment]
@orelbon Just run the .dmb file you get from compiling

**Comment by orelbon** [comment]
I did try that before, i get errors.

**Comment by LordJike** [comment]
I just use Dream Dameon then join through Dream Dameon without caring about connectivity, it works.

**Pull request closed without merging**
