### PR TITLE
Makes blobs less cheesable

### PR DESCRIPTION
**Pull request by Kyep**
Tweaks blob to be less likely to die before a player can get control of it.

🆑 Kyep
tweak: blobs now spawn with a player in control, instantly. There is no longer a 30 second period where they exist, but nobody is controlling them.
tweak: blobs now get extra time after spawn, before they are announced.
/🆑

### CODE REVIEW

**Comment by Xantholne** [comment]
This is really going to help against the meta knowledge of where blobs spawn

**Comment by SamHPurp** [comment]
Firstly, awesome, glad its getting fixed.

Secondly, probably worth another PR to change the order in which blob selects happen. Currently the blob physically spawns, and the crew gets notified before the ghost is selected and inserted.

**Comment by Crazylemon64** [comment]
Hmm, not sure about the toxins spot, but we'll see how that cookie crumbles

**Comment by Spartan6** [comment]
I think you should move the announcement of when the random event blob spawns, so it happens three minutes after. Currently, if I remember correctly, the blob is immediately announced when the random event is spawned, so the blob has no time to actually grow before the greytide storms it. Giving it up to three minutes to grow undetected would help the blob a lot.

**Comment by DesolateG** [comment]
Kyep... have you thought of the basket ball court in permabrig?

**Comment by SamHPurp** [comment]
@Spartan6 Its not even that, The blob spawns and the crew get alerted before the ghost even gets put into control of the blob.

**Comment by Fox-McCloud** [comment]
This will solve the problem---for all of 10 rounds.

Players are always going to check the "known spots"; you can't really stop that; it's the fact that the announcement is *immediate* that is more of the problem.

Yes, a few of the spawn points aren't the best (mostly the bathroom one), but it's really the announcement that's the issue.

Also, keep in mind, you're not just changing blob spawn points, you're changing *nuke disk* spawn points.

**Comment by SomanBat** [comment]
The problem is not the location, it's entirely the announcement.

Either delay the announcement, Or give the blerp some starting resources so it can quickly barricade the tide.

**Comment by taukausanake** [comment]
Yeah, I'm kind of okay with the locations as they are but also like these new locations too for blob. You have some good places pre-PR because they are high traffic and/or important places. R&D server room can take out R&D quickly if they are fast enough. Bye bye x-ray lasers. HoP office? You could go for the gravity generator perhaps and make moving a bit more difficult. Tech storage could try taking out engineering and cutting off power but I don't know if that's a good idea with either singlo or tesla active. The toilet is just ironic but seems kind of defensible next to a lot of maint. EVA maint and library aren't so good spots I guess.

Yeah, I agree with the others. If the event announcement is that soon it doesn't matter where it spawns in at, it will be found. That announcement needs to be delayed. Maybe the blob can also be silent for a bit after spawning? It is kind of small at starting, could go without too much noise

**Comment by Kyep** [comment]
Addition: blob announcements moved from 24s after spawn, to 120s after spawn.
This means mobs get almost 100 extra seconds after spawn before they are announced.

**Comment by SamHPurp** [comment]
Sounds great @Kyep !

This is only for event blob, not round blob - I'm assuming?

**Comment by Kyep** [comment]
@SamHPurp Correct. Roundstart blobs are crew members who burst. They can burst anywhere they happen to be when their timer counts down. They don't use the landmark/placement system that event blob uses.

**Comment by Spartan6** [comment]
@Kyep You should remove the command report and delay the announcement for burst crewmembers if it hasn't already.

**Comment by Fox-McCloud** [comment]
@Kyep 

Would you be willing to try out *just* the intercept report for a few weeks to see how it handles then make the position changes? I honestly think it's a better resolution and doesn't screw with nuke disk spawn points nearly as badly.

**Comment by SamHPurp** [comment]
Honestly, I'd keep both changes. Neither are too extreme, and will make late-game blobs actually slightly more interesting than the quick dogpile of all crew with xray guns.

**Comment by Kyep** [comment]
@Fox-McCloud I'd really rather keep them together, because I feel both are necessary. Moving the announcement won't help if the blob spawns next to the bar (for example) and is seen by everyone who walks by in seconds. I don't think changing the nuclear disk spawn locations is significant. Everyone who might want to find them (Captain, nukeops, heck, even regular traitors) either start with or can cheaply buy a pinpointer that will lead them right to it. If you're dead-set against moving the blobstart landmarks just because of the nuclear disk, then I'm willing to change the way nuclear disk respawn works to use a different set of landmarks, so the two aren't linked anymore. We do need to move the blobstart landmarks, though. Some of them are crazy-obvious.

**Comment by KingPhilipIII** [comment]
I think another problem still remains in that before we implemented the system of asking ghosts if they wanted to be ghosts (random drop into blob, sometimes we got AFKs) the blob wasn't left uncontrolled for a full thirty seconds, unable to defend itself. Is there any way to make the blob drop when it's controlled and not the current thing we have going.

**Comment by Fox-McCloud** [comment]
Yup, that's a good point that KingPhillip brings up.

I'd still prefer that we try out early announcements *first* and see how that goes rather than doing both, at the same time; Blob is an incredibly high impact entity when given the chance---and typically, it wins more often than it loses (for the mode).

Currently, event blobs don't do jack most of the time, but I kind want to see a gradual approach to ratcheting up its power due to just how high of impact blob is---I don't think it's necessarily a good thing for blob to be as high impact as Xenos are, but it should definitely still be more than what it is currently.

**Comment by SamHPurp** [comment]
... That is literally the point I brought up 3 days ago.

**Comment by Kyep** [comment]
@SamHPurp @KingPhilipIII @Fox-McCloud Updated so that it asks ghosts who wants to be a blob, picks someone, *then* spawns the blob with that player in control instantly.

**Comment by Kyep** [comment]
@Fox-McCloud Its changed. No more map edits. Now just puts someone into the blob instantly, and slightly delays announcement. Take a look.

**Comment by Doukhan** [comment]
Is there an alert sound when the player-blob gets spawned in like with revenents?
I alt-tab a lot when ghosted, last thing anybody wants is an AFK blob.

**Pull request merged**
