### PR TITLE
Adds Lazarus Injector emag_act()

### PR DESCRIPTION
**Pull request by Spacemanspark**
:cl:
rscadd: Lazarus Injector's can now be emagged to activate their special features, alongside using EMPs on them.
/:cl:

### CODE REVIEW

**Comment by NTSAM** [comment]
:+1: It seems a little too inconvenient (and maybe slightly unexpected or weird or something) to have to EMP a thing to make it do something that will actually help you.

**Comment by sasanek12** [comment]
:+1:  Makes much more sense than EMP

**Comment by Tastyfish** [comment]
Makes sense.

**Comment by Fox-McCloud** [comment]
No :-1: 

This is hardly a problem that people are abusing, and there's definitely cases and instances where non-traitors could hypothetically utilize this; if Xeno-bio can have their crazy powerful loyal attack minions (which are arguably better and more powerful as they're player controlled), there's no reason for mining's pets to be locked to traitors only.

**Comment by Spacemanspark** [comment]
My issue isn't that they're being abused, it's that it isn't used at all. Nobody wants to EMP anything. IPCs can't use this at all. Nor does it really make sense that an EMP would cause loyalty to purely the owner.
What non traitor purposes do you see? All this really allows is for mobs to attack things that aren't bound to the owner. Any non antag that releases that is gonna get a BWOINK.
Xenobio player creatures, last time I checked, also required to ahelp before blatantly murdering on command.

**Comment by Fox-McCloud** [comment]
>My issue isn't that they're being abused, it's that it isn't used at all. Nobody wants to EMP anything.

There's this little cheap item that's called an emp flashlightt that anyone can safely use without generating an emp near anything. Likewise, this cuts out the ability for miners who are not impacted by EMPS (ie: 95%+ of miners) to utilize an EMP, themselves. 

Yes, they can get bwoinked for it--so can scientist who utilize gold slimes, people who make the life reactions, use hostile mob spawners in hallways, and people who set off bombs. We don't bubblewrap things for such reasons, unless there's overwhelming evidence at hand that it's having a hugely negative impact on the round.

**Comment by NTSAM** [comment]
No one uses it for good either though

**Comment by Spacemanspark** [comment]
>There's this cheap little item that's called an emp flashlight


Let's not be passive aggressive. I'm well aware of what the EMP flashlight is. The emag makes doing this easier, regardless. It's also a traitor item, so I'm not seeing where you're going with this.

>We don't bubblewrap things for such reasons

Let me re-iterate: This isn't "bubblewrapping". Heck, when I first wanted to add in mob capsules, I wanted to make lazarus injectors consistent with /vg/, which makes them only behave exactly as they would when EMP'd currently on Paradise. I didn't because, when I was getting help with it and asked around, I was told this was a bad idea. No, this change is because literally nobody ever utilizes this feature at all. I've never seen it used once. If I actually saw people using EMPs on these things and doing this every so often, I probably wouldn't have even bothered making this change.

**Comment by Fox-McCloud** [comment]
>Let's not be passive aggressive. I'm well aware of what the EMP flashlight is. The emag makes doing this easier, regardless. It's also a traitor item, so I'm not seeing where you're going with this.

Um. What. You STRONGLY suggested here wasn't a safe way to EMP things, and I informed you there was---then you attack me and accuse me of being passive aggressive? 

Objectively, the flashlight and the emag are the same "difficulty" to use; you click the item on lazarus and it does its thing.

If you really have a problem with it not being used much (which I doubt will change under it being an emag thing--considering lazaruses aren't purchased much, even by non-traitors), then add an antag description to it that only antags can see (since we have such a system), and mention what EMPs do to it.

This isn't the only thing int he code that has something that enables emag-like functions if you EMP it--glasses and defib units are very similar.

**Comment by Spacemanspark** [comment]
> and I informed you there was---then you attack me and accuse me of being passive aggressive?

when you start off with

>There's this cheap little item

That looked pretty rude to me. I'm exhausted at the moment, and I'm looking at things more critically than I should. I apologize.

The EMP flashlight does, indeed, create a 1x1 EMP field. This is still obnoxious, as you have to lay them on the ground and do this. With an emag, it's literally just a click.
>considering lazaruses aren't purchased much, even by non-traitors

I see Lazarus injectors being used quite frequently, actually. Especially in the past week or so, which was one of the final points that prompted me to do this.

>This isn't the only thing int he code that has something that enables emag-like functions if you EMP it--glasses and defib units are very similar.

And those are rarely utilized, unfortunately. More used than this, granted, but still rarely utilized.

I still don't see what the problem is. If nobody is using this in the first place, and the only 'safe' way of really doing this anyways was with traitor items, this makes sense.

Personally, I'd still rather make the 'malfunction' part the sole function of lazarus injectors, but I don't think people really want that.

**Comment by Fox-McCloud** [comment]
>The EMP flashlight does, indeed, create a 1x1 EMP field. This is still obnoxious, as you have to lay them on the ground and do this. With an emag, it's literally just a click.

It doesn't. IT calls `emp_act` directly on what's clicked.

> and the only 'safe' way of really doing this

This only applies to IPCs. The vast majority of the crew can utilize EMPs effectively and completely safely without repercussions (especially miners).


Now, if you want to have both an `emp_act` AND and `emag_act`, I wouldn't be opposed to that, either.

**Comment by NTSAM** [comment]
Oh yeah, just add emagging too instead of removing emp

**Comment by Spacemanspark** [comment]
That works, give me a bit and I'll get on it.

**Comment by Spacemanspark** [comment]
There we go.

**Comment by Fox-McCloud** [comment]
edited the tittle a bit.

**Comment by Robertha89** [comment]
Sweet, I mean, emping them is all great and all, but this will make it convenient as a tator.

**Pull request merged**
