### PR TITLE
New beginner-friendly traitor kit

### PR DESCRIPTION
**Pull request by E-MonaRhg**
_Certainly not a late april fools PR, certainly not._

## What Does This PR Do

This PR adds a new traitor kit designed for beginner traitors. It has all the necessary equipment you would need for 16 TC so you can still get some low-cost items.

## Why It's Good For The Game

Being a traitor can be an intimidating task for new players, this kit makes it less stressful because of all the things in it.

## ~~Images~~ Videos of changes

Presentation:

https://user-images.githubusercontent.com/71735193/113331503-56d57b80-9320-11eb-89d4-85dea8324f55.mp4

## Changelog
:cl:
add: Added a new beginner friendly "Suspicious" traitor kit, not an april fools thing, certainly.
/:cl:

_Can't have april fools in 2021 without an Among Us joke, now can we?_

### CODE REVIEW

**Comment by hal9000PR** [comment]
sus

**Comment by shmabuu** [comment]
68A5A8B4-56A3-4D3B-98D8-FDCE278B40C8

**Comment by E-MonaRhg** [comment]
Sadness,
image

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
Objecting because amongus is awful

**Comment by E-MonaRhg** [comment]
> Objecting because amongus is awful

Yeah fair enough

**Comment by datlo** [comment]
amogus

**Pull request closed without merging**
