### PR TITLE
Tail Fix Take 2

### PR DESCRIPTION
**Pull request by KasparoVy**
After the colossal failure of the last attempt at fixing tails, I decided to take a slightly different approach.
Icon updating is finicky at best and it took a little bit of trial and error to get the last piece of the puzzle to fit as I wanted.

This iteration accomplishes what the last could not.
First and foremost: Peoples' limbs still render.
Secondly: There are no longer any duplicate tails, each wagging at different rates. Only one wagging at the correct rate. No more nine-tailed fox.
Thirdly: Damage, mutation and husk and other such overlays still work.
Fourthly: Limbs now overlay tails when facing east and west, no matter what you do (Read as: Functionality cannot be broken by updating icons, sawing off limbs, rejuvenating, spamming *wag and *swag, switching characters (with different species) repeatedly, hulking and dehulking rapidly, possessing and unpossessing another player rapidly, etc).

The main focus was to route out each individual issue comprising #3183 and eliminate them one by one. What gave me the most trouble was finding the correct place in update_icons to set overlays_standing[LIMBS_LAYER]. That was the trial and error bit. I still don't quite understand why exactly it works only in that one location, but I'm satisfied nonetheless

Anyway,

**FIXES:**
- Tails will now render in ID cards correctly.
- Tails will now render in the character creation menu correctly.
- Tails overlapping arms(+ gloves, etc.) when facing east/west.
- Ensures tails will overlap stuff as normal only when facing north so as to avoid unwanted interference with the base sprite.
- The above still works even when tails are wagging, while starting to wag and stopping wagging as well.
- Corrects minor errors with Unathi sprites (recolours bad pixel in right arm east direction sprite, fixes wagging tail floating, fixes an issue with the north direction static tail sprite not attaching to the body in the correct location).
- Adds species flag to check if a user's species' tail needs to be overlapped by limbs. If not, standard cheap icon generation is used. If the tail needs to be overlapped, then per-direction icon generation and the diversion of limbs into their own layer is used.
- Vulpkanin body accessory alternate tails now work in full, added in a separate animation template for body_accessory as the tails there have one less frame than the tail animations in /effects/species.dmi
- Accommodates admin-overrides to body_accessory species checks, using the Vulpkanin animation template as the default since there's no other body accessory tails to worry about at the moment

**CHANGES:**
 - Position of tail layer so tail north-direction sprite overlays backpacks

**COMMENTS:**
While this does not fix the body colour issue for Vox tails, this does completely fix the tail layering issue with tails overlaying arms and gloves and such as reported in #3138.

What I did was I split limbs into their own layer and left it to be generated with the base icons in update_icons as per usual.

I split tails into two layers: One that could be overlaid by the new limb layer, and one that remained in the regular position, so tails could continue to work as intended while not covering arms and other things when viewed from the side.

What this did in the end was allow tails, wagging and not wagging, to be overlapped by arms and such when the player is facing east or west. But, as soon as they face NORTH, the tail overlays like it used to: Overlapping the body, clothes, etc.

With Vox as an example, where now their tail overlaps their arms and everything, after this PR it will look exactly the same as it did pre-#3107, except Vox tail wagging still works just fine.

PLAYER ICONS STILL GENERATE

Furthermore, in order to eliminate the tails rapidly wagging bug, I ended up having to put in blank (but animated on a per-species basis) sprites to .Insert() directional sprites into
I don't have a .gif but this bug was pretty funny to see in action. Tajara ended up wagging their tails in a circle when facing north or south, haha. They don't anymore, thankfully.

In the long run, what this means is that if other races get implemented with limbs that hang over their tails or whatever, it won't look janky. If new tail sprites are implemented, so long as the spriters use the same animation style as every other tail in that species (or just uses the blank animation template sprite as a ref) it'll be just fine

**EXAMPLE PHOTOS:**
*Character Creation - Please disregard the non-Vox name.*
tailfixpoc3

*ID Card - Please disregard the non-Vox name.*
tailfixpoc2

*Player Icons - This time, I tested everything.*
tailfixtake2

*Overlays in Action - Just making sure everything still works.*
tailfixtake2blood

*Wagwagwagwagwagwagwagwagwagwagwagwagwag - BEWARE, this .GIF is not a perfect loop.*
tailfixtake2tails

*Unathi* **POST SPRITE-FIX** *- Compare with the above .GIF (still not a perfect loop).*
*THIS IS WHAT UNATHI WAGGING TAILS LOOK LIKE IN THE MOST CURRENT VERSION OF THIS PR*
*Gyazo .GIFs don't really do these animations much justice. :cry:*
tailfixtake2tunathifix

*Cyborg Limbs*
tailfixtake2cyborg1 tailfixtake2cyborg2 tailfixtake2cyborg3

*Vulpkanin Alt Tails and Admin Overrides in Action
Featuring super-fluffy tails that aren't covered by satchel-straps!*
tailfixtake2admin1 tailfixtake2admin2 tailfixtake2admin3

*Unathi Tails - Before and AFTER Tweak*
tailfixtake2unathistatic

**If anyone else wants to test (I really really welcome it, just tell me when and I'll try to accommodate), I'll get that going**
I ran out of ideas for stuff to test, if you have any suggestions (something you don't see tested here that's part of the PR) please comment

### CODE REVIEW

**Comment by Plotron** [comment]
That wag .gif, last row... are you sure that Unathi tail isn't kind of detached?

**Comment by KasparoVy** [comment]
If you're referring to the *wagwagwagwag* .gif-- that was pre-fix, which is why I put 'Unathi POST SPRITE-FIX - Compare with the above .GIF" as the heading for the next (albeit smaller) gif which displays the current (fixed) tailsprites

It took me a while to make that big gif and I really wasn't feeling going back to redo it after discovering that the sprite was an issue, so I instead posted that and then the updated version of the unathi tail animations separately

**Comment by tigercat2000** [comment]
did you try a vulvakin tail on an IPC to make sure that works

**Comment by KasparoVy** [comment]
Lmao, good suggestion. BRB

**Comment by KasparoVy** [comment]
Got it! Going to do some testing to make sure EVERYTHING still works then I'll push.

**Comment by KasparoVy** [comment]
@tigercat2000

*Vulpkanin Alt Tails and Admin Overrides in Action*
tailfixtake2admin1 tailfixtake2admin2 tailfixtake2admin3

**Comment by Fox-McCloud** [comment]
I have concern about this---to a degree, I'd kinda rather revert Vox tails altogether than implement this--mostly because this creates sooo many icons for such a simple features utilized by literally a single race. I'd really like for Vox to wag their tails, but I'm reallyyy not sure it's worth making update_icons() even *more* expensive than it already is.

**Comment by KasparoVy** [comment]
It's an esoteric solution but it's the only one I found seriously worth pursuing
If there's any ideas on how to reduce the cost of this implementation I'm all ears

**Comment by KasparoVy** [comment]
It's an esoteric solution but it's the only one I found seriously worth pursuing
I agree with you, but I'm unsure of exactly how much impact this will have (I just don't know, lol)

If there's any ideas on how to reduce the cost of this implementation I'm all ears! :ear:


Here's one I had: 
:arrow_down: :arrow_down:
>**Perhaps adding a flag that's assigned to a species to check if a tail should go below their arms, check for that and THEN use a decision structure in update_icons and pursue either THIS PR's method of tail generation OR the standard one (currently in use, not from this PR)? (having both of them exist but only one used depending on whether a species tail sprite overlaps arms or not), thus reducing cost(?)**
*With this suggestion in place, update_icons.dm would be larger in size, but it means that this PR would only make it more expensive to generate tails for players who choose a species flagged to have a tail that should be overlain by arms (i.e. Vox), while keeping cost the same for everyone else instead of the current state of this PR where it's more expensive for everyone. The difference would be pretty big.*

:arrow_up: :arrow_up:

Just an idea, but I don't know enough about how all this works to determine whether or not doing that would reduce cost enough to make this worthwhile. What do you think, @Fox-McCloud?
I'm more than willing to pick work on this back up to get that functionality in if makes this more reasonable

**Comment by KasparoVy** [comment]
I tested my idea and it didn't break anything (that's always nice).

Should be significantly cheaper (if I'm understanding how this works correctly).

Now, it will only generate tail icons on a per-direction basis if the user's species is flagged to have a tail that is overlapped by limbs (TAIL_OVERLAPPED). Which, at the moment, is only Vox.

Otherwise, it just uses the traditional cheapo method of icon generation.

This way, we have fixed wagging Voxtails at a much lower cost.

**Comment by KasparoVy** [comment]
I went ahead and tested my idea and it didn't break anything (that's always nice). The whole lot still works as advertised.

Should be significantly cheaper (if I'm understanding how this works correctly).

Now, it will only generate tail icons on a per-direction basis if the user's species is flagged to have a tail that is overlapped by limbs (TAIL_OVERLAPPED). Which, at the moment, is only Vox.

Otherwise, it just uses the traditional cheapo method of icon generation.

**That way we can have fixed wagging Voxtails at a much lower cost than the initial implementation.
However, it will still cost marginally more than what we have right now, but it shouldn't be too much of an increase**

**Comment by Fox-McCloud** [comment]
quick question before I review this.

what's this?

img1

**Comment by KasparoVy** [comment]
That was what the unathi tails looked like before I implemented the sprite fix

This is what they look like now
tailfixtake2tunathifix

**Comment by Fox-McCloud** [comment]
Ah, right, thanks.

**Comment by Fox-McCloud** [comment]
Just a quick review (I'll have to do a more thorough one and likely consult with someone else on this, as icons are not my specialty), but yeah, what you've done limits the extra icon generation to Vox only--meaning, on the whole, icon regeneration isn't going to be that much more expensive 95%+ of the time (a good thing; human icon updates are stupidly expensive).

**Comment by KasparoVy** [comment]
Yeah, I feel silly for not realizing this and implementing the workaround sooner. I'm really glad you brought it up haha

**Comment by Fox-McCloud** [comment]
@TheDZD 

@tigercat2000

**Comment by TheDZD** [comment]
Looks good, although you may want to squash your commits.

**Comment by KasparoVy** [comment]
Hey @TheDZD, trying to squash those commits. Am I right in doing git rebase -i HEAD~11 Tail-Fix-A2 in the git terminal, using pick on the first commit in the list and squash for all the others?

**Comment by tigercat2000** [comment]
@KasparoVy I don't think the last argument (`Tail-FixA2`) is necessary, but yes, your first commit should be pick, the rest should be `squash` or `s`

**Comment by KasparoVy** [comment]
Alright, cheers

**Pull request merged**
