### PR TITLE
Adds some new OOC emoji

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Adds some new emoji for use in OOC chats.

:pregman: by synthtee

## Why It's Good For The Game
I keep trying to type these and am let down every single time. We have the technology.

## Images of changes
image

and some others

Yes these are codersprites and compressed images but so are the rest of our emoji. Smork is also supposed to be a little fucked up, as a treat.

## Changelog
:cl: Lewcc, synthtee
add: Adds some new OOC emoji.
/:cl:

### CODE REVIEW

**Comment by AyIong** [comment]
WTF
image

**Comment by lewcc** [comment]
> WTF image

image
I have no idea

**Comment by 1080pCat** [comment]
finally, gatto is here....

**Comment by 1080pCat** [comment]
image
why pregman...

**Review by Henri215 — APPROVED** [review]
I wonder how many times THAT emoji will be used.

**Review by Burzah — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
