### PR TITLE
The Freeze is Back...

### PR DESCRIPTION
**Pull request by Fox-McCloud**
for your every day spessmen going SSD that is...

Dramatically expands the amount of cryodorm pods, so as to deal with a much busier Cyberiad.

img

:cl: Fox McCloud
add: Expands the amount of cryodorm pods
/:cl:

### CODE REVIEW

**Comment by Aurorablade** [comment]
you are a dirty dirty troll

**Comment by FalseIncarnate** [comment]
Part of me wants to suggest 2 tiles between the pods, but there isn't much room to work with in that spot so it'll have to do. Everything on the walls are still interact-able as normal, right? Not that I've ever seen the need to, but if you were to need to mess with that APC, hopefully the sleeper beneath it wouldn't block access to the terminal in the floor.

**Comment by swordsith** [comment]
The only issue i foresee with this is not being able to reach the modules on the left wall behind the pods.

**Comment by Aurorablade** [comment]
well they are intercomms. not alot of people will use those in thecrydorm.  the APC and Firealarm are bot in accessable spots.

**Comment by Kyep** [comment]
This layout is a bit cramped, no? Might be better to expand the room to 4 tiles wide.

**Comment by KasparoVy** [comment]
Way better alternative. This'll work nicely.

**Comment by Spacemanspark** [comment]
I was about to go ballistic.

**Comment by Norgad** [comment]
I like this solution more than the other.
However, #6076 has the map-edit token right now.


ᵖᶫᵉᵃˢᵉ ᵈᵒᶰᵗ ᵐᵉʳᵍᵉ ᶜᵒᶰᶠᶫᶦᶜᵗ ᵐᵉ ᴵ ʷᵒᵘᶫᵈ ᵈᶦᵉ

**Comment by swordsith** [comment]
my ideas get stolen like me memes ;c gg tho

**Comment by Davdichan** [comment]
Question: How hard would it be to make a 'revolving' cryopod sprite that would just animate and move the pod to the background of the sprite giving the illusion that it's moving the pods below deck/behind the walls out of sight?

Could have a hatch on the side to crawl out if they got cryo'd and changed their mind.

I ask because Cryodorms takes up what could be used maint space around the dorms and security where SOMETHING entertaining could be, and having a smaller cryodorm room would make it easier to put people into cryo without having to walk up and down what is effectively a hallway with glass tubes.

**Pull request merged**
