### PR TITLE
Mimes get department backpack

### PR DESCRIPTION
**Pull request by datlo**
## What Does This PR Do

Mimes with department backpack/satchel in character creation get the mime backpack. Department duffel mimes get regular dufflebag due to no item existing.

## Why It's Good For The Game

Consistency with all other jobs, convenience
Ideally we should get a mime dufflebag and satchel added but this is a step in the right direction
## Testing

Spawned as a mime with department backpack, satchel, dufflebag, grey backpack, everything works as expected 

## Changelog
:cl:
tweak: Mimes spawn with the mime backpack if department backpack or satchel is selected in character setup
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
Why force them the mime backpack if they have a satchel selected?

**Comment by Christasmurf** [comment]
> Why force them the mime backpack if they have a satchel selected?

That's how the clown backpack functions currently - Duffel and backpack select the right thing, no satchel exists so it defaults to backpack

**Comment by Henri215** [comment]
> > Why force them the mime backpack if they have a satchel selected?
> 
> That's how the clown backpack functions currently - Duffel and backpack select the right thing, no satchel exists so it defaults to backpack

Yeah, this is not exclusive to this PR but the question still stands, it would be a problem to give them the common satchel if they have it as their preference?

**Comment by datlo** [comment]
There's no gameplay difference between backpacks and satchels, and as explained this is the current standard set by the clown job who uses clown backpack for departmental satchel

**Review by Henri215 — APPROVED** [review]

**Review by lewcc — APPROVED** [review]

**Pull request merged**
