### PR TITLE
Fixes acid peels

### PR DESCRIPTION
**Pull request by lewcc**
## What Does This PR Do
Fixes acid peels. They'll now slip you for multiple tiles and chain like they used to.

## Why It's Good For The Game
Acid peels are very funny. It's good to have them back.

## Images of changes
vLVyaSrk

## Testing
Slipped on some banana peels

## Changelog
:cl:
fix: Banana peels now chain-slip again.
/:cl:

### CODE REVIEW

**Review by DGamerL — APPROVED** [review]
Truly amazing

**Comment by Mitchs98** [comment]
Y'know. I wondered what happened, I thought it was intended.

**Comment by ATP-Engineer** [comment]
Can you make it so certain acceleration can result in thrown effect so people can fly out windows or get crushed by a soda machine and horribly die

**Comment by ArcticValor** [comment]
> Can you make it so certain acceleration can result in thrown effect so people can fly out windows or get crushed by a soda machine and horribly die

hear me out, what about space man banana powered railgun?

**Comment by lewcc** [comment]
> Can you make it so certain acceleration can result in thrown effect so people can fly out windows or get crushed by a soda machine and horribly die

I feel that but it's probably better (at least for now) if that isn't the case. Let's get them fixed first.

**Review by S34NW — APPROVED** [review]
amazing fix

**Comment by Probablyjay19** [comment]
Local assistant reaches mock speed after fellow assistant creates particle accelerator machine in departures, more at 6.

**Pull request merged**
