### PR TITLE
Admin unban panel overhaul

### PR DESCRIPTION
**Pull request by ZomgPonies**
Cleans up the admin unban panel stuff, makes manual bans properly pick up on a mob's IP even if it leaves, limits how many results show to unlag the system, etc.

panel

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Have pics, Ponies?

**Comment by ZomgPonies** [comment]
https://cloud.githubusercontent.com/assets/4064061/6557287/f448d818-c684-11e4-9091-8ebfc95f737f.png

**Comment by Fox-McCloud** [comment]
name of image here

**Comment by tigercat2000** [comment]
[Same thing works for links, if you don't use the exclaimation.](https://guides.github.com/features/mastering-markdown/#syntax)

**Pull request merged**
