### PR TITLE
A proposed way to make barricades dismantlable sanely.

### PR DESCRIPTION
**Pull request by Tastyfish**
This change would allow them to be dismantled by crowbars after 15 seconds.
* It has a progress bar.
* It also alerts everyone in LOS and makes a crowbar noise that you're starting to take it apart, and when you've finished.
 * This makes it reasonably noticeable, if somebody is concerned about it more easily being stealth dismantled. No idea what anyone's conceptions on the game-play use of them is.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Those commits.

**Comment by TheDZD** [comment]
You really shouldn't have merge commits on a PR unless you've had merge conflicts some time after submitting it.

**Comment by Robertha89** [comment]
Merge commits, correct me if I am wrong, but it should not be a problem, right?

**Comment by TheDZD** [comment]
They don't do anything, but having many of them is generally bad practice, as they clutter the commit log.

**Comment by tigercat2000** [comment]
as if our commit log was in any readable state as is

**Comment by Tastyfish** [comment]
Yeah, I accidentally let the commit sit locally for a few days, and pulled updates, forgetting about pushing the commit. Oh well.

**Pull request merged**
