### PR TITLE
Colored Light Tiles

### PR DESCRIPTION
**Pull request by tigercat2000**
d3athrow/vgstation13#4718

Light tiles (item) can now have their color changed by attacking them with a
multitool. These colors have special sprites and glow a color similar to
their sprite.

fancy

### CODE REVIEW

**Comment by Robertha89** [comment]
can you make em cheaper to construct too?

**Comment by tigercat2000** [comment]
@Robertha89 Not within the scope of a feature PR, really.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by SamCroswell** [comment]
:+1:

**Comment by Bad-Apple797** [comment]
yay

**Comment by ZomgPonies** [comment]
:+1:

**Pull request merged**
