### PR TITLE
Lets you ghost-follow any movable atom

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
tweak: Relaxes the check on what atoms you can follow to any movable atom
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
>Now follow the potted plant.

**Comment by Crazylemon64** [comment]
I mean, if a ghost follows something BORING, that's on them

**Comment by Tastyfish** [comment]
That's definitely simpler than special casing the singulo, nuke disk, etc.

**Comment by Dumbdumn5** [comment]
Gon' follow all the foodstuffs.

**Comment by Gummin** [comment]
I was going to make a joke like 

> Now following the potted plant.
But fox beat me to it.

**Pull request merged**
