### PR TITLE
Adds module-connotated versions of the standard robot to each module

### PR DESCRIPTION
**Pull request by Ar3nn**
This is my first attempt to add something to the code, so hopefully this went okay! I thought this looked like a small enough change, and I'd been talking about it for a while and decided to attempt to do it myself. This is supposed to add color-coordinated versions of the basic robot model that spawns before a module is chosen to each module so if you want you can keep it.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Literally changes nothing.

**Comment by Spacemanspark** [comment]
Must you be so negative, man?

**Comment by Ar3nn** [comment]
@Spacemanspark no no at the time, he was perfectly correct, I forgot to commit the changes and so I had to hack around and push the commit in afterwards.

**Comment by Spacemanspark** [comment]
Oh, alright.
Wasn't able to tell because I'm on mobile, my bad.

**Comment by Ar3nn** [comment]
@Fox-McCloud okay now it actually changes things

**Comment by Fox-McCloud** [comment]
Please post pics of each model.

**Comment by Ar3nn** [comment]
image of all icons
image of security model
image of medical model
image of engineering model
image of janitorial model
image of service model
image of mining model

**Comment by IK3I** [comment]
The Purple and Green versions seem to change color slightly depending on orientation. May want to fix that quick.
Other than that, 10/10 would be default medical droid

**Comment by Ar3nn** [comment]
I kept thinking I saw that, too! I kept thinking it was the white background fucking with me, because my eyes have recently started hating oversaturation of white. I'll totally retouch those right now.

**Comment by Fox-McCloud** [comment]
Some of these seem really low res or the color seems out of place; the color is very flat and looks like it was added on via MSPaint, no offense.

**Comment by Ar3nn** [comment]
@Fox-McCloud were any of them acceptable, or should I redo all of them?

**Comment by DaveTheHeadcrab** [comment]
Like the idea, will have my :+1: when the quality of the icons increases.

**Comment by Ar3nn** [comment]
group of sprites mk 2
security borg mk 2
medical borg mk 2
engineering borg mk 2
janitor borg mk 2
service borg mk 2
mining borg mk 2

**Comment by Ar3nn** [comment]
I'll just not push them up until they're approved, seems like a lot of hassle and bogging down with multiple commits.

**Comment by Fox-McCloud** [comment]
Most of them look very very flat and unshaded---the brown one is the worst though.

**Comment by Ar3nn** [comment]
I don't even really want the mining one, its just for completeness. I'll try again.

**Comment by Ar3nn** [comment]
image of group mk3
image of sec mk3
image of medical mk3
image of engineering mk3
image of janitor mk3
image of service mk3
image of mining mk3

**Comment by TheDZD** [comment]
Really difficult to actually look at the sprite when the screenshots are of the very tiny Dream Maker preview images. Not sure if it's the brighter color, but the engi one looks even flatter now.

**Comment by Ar3nn** [comment]
I could screenshot the larger editing frames if you like.

**Comment by QuinnAggeler** [comment]
If you have Photoshop, GIMP, or even paint, here's what I recommend:
1) select the icon state and ctrl+c
2) Make a large canvas in one of the above programs, ctrl+v it into there, arrange
3) Do this with all the directional frames of each sprite
4) When they are arranged, trim the canvas (if need be) and then export at 300-500% size

**Comment by Ar3nn** [comment]
image214523
Not big enough?

**Comment by QuinnAggeler** [comment]
It'd look better for presentation without the checkered background, and if it were a bit smaller. Again, try ctrl+c from the dmi editor into paint/photoshop/GIMP and arranging them as a sprite sheet, then exporting at around 300%. You can get a very good presentation that way

**Comment by Ar3nn** [comment]
sprites
Then...like this.

**Comment by QuinnAggeler** [comment]
:ok_hand: There ya go.
Looks fine to me. The cyan (medical?) one is perhaps too bright, could use a darker tone or two to offset it, as the shading isn't apparent. The green one could probably be darker and more saturated.

**Comment by Ar3nn** [comment]
If the green one's darker, it'll look like an alternate janitor design. I specifically made it that bright to keep the tone similar to service green (aka puke green)

as for the mediborg, I could darken it a bit. If that's all that needs to be done, I'll gladly throw that in just a mo'.

**Comment by Ar3nn** [comment]
sprites2

**Comment by QuinnAggeler** [comment]
I wasn't clear, the word I was looking for was _contrast_. The mediborg needs more contrast, which is to say, the difference between the dark and light tones of its cyan needs to be greater, so that the shading is more apparent. As is, it looks almost like one solid color.
The green one looks kinda odd, like it's desaturated. Try sampling some green from the botanist clothes.

**Comment by Ar3nn** [comment]
I took a screenie of the botanist jumpsuit and I'll work on those sprites tomorrow again probably

**Comment by DaveTheHeadcrab** [comment]
:+1:

**Comment by Dumbdumn5** [comment]
:+1:

**Pull request merged**
