### PR TITLE
Add material decomp and cyborg analyzer to respective cyborg modules

### PR DESCRIPTION
**Pull request by matt81093**
Modifies cyborg modules slightly by adding the material decomp to janitorial and service cyborg modules to assist in cleanup, as well as adding the cyborg analyzer to the medical modules to allow medical cyborgs to assist their robotic buddies.

Corrects: #7902 

🆑 matt81093
adds: material decomp to janitorial and service module
adds: cyborg analyzer to cyborgs
edits: Altered cyborg examine somewhat and added a reference cyborgs without a key for some reason
/🆑

### CODE REVIEW

**Comment by matt81093** [comment]
Welp, didn't mean to do that.. hopefully that fixed it. Also.. any thoughts on cyborg analyzers being for all cyborg?

**Comment by ProperPants** [comment]
Cyborgs already have self-diagnostic, so they don't really need cyborg analyzer. The only cyborg that can really repair other cyborgs is the engineering module, and roboticists need something to do.

**Comment by alexkar598** [comment]
why put a cyborg analyser in medical robot?

they cant heal other borgs anyways

**Comment by matt81093** [comment]
The express purpose I added the analyzer for, is for cyborgs to know when another is SSD. If there is a method that I am unaware of, please enlighten me, and I can easily remove that unnecessary addition, though personally, I do enjoy the thought of cyborgs being able to diagnose others of their kind and request assistance when needed from trusted meat bags, or to drop off them off at the roboticist and explain the malady or SSD'ness.

**Comment by ProperPants** [comment]
You can examine a cyborg and see when it's SSD. It gives a message, but I'm afraid I can't remember what it says exactly at this time. It's the same idea as the SSD message for players though.

**Comment by alexkar598** [comment]
You removed the health analyzer from the standard which Is an undocumented change and its a change I don't think would be good to have

**Comment by alexkar598** [comment]
Il say what I think of this pr even if I'm no maintainer.

Adding a robot analyzer to all Borge makes the self diagnostic system redundant so I don't think it's a good idea

Adding matter decompile to medical Borg is out of context

Janitor borgs have trash bags so they don't need the matter decompiller

Why remove Heath analyzer from standard borgs? This is an undocented change and no a one I'm fan of

Changing the examine message is just useless since if you we're confused before you will still be confused

From my perspective this pr is total crap and should not be merged(no offence to you or your coding skills)

**Comment by alexkar598** [comment]
This change log represent what is in this pr better :

🆑 matt81093
del: Removes the health analyzer from the standard cyborg module
adds: Added a matter decompiler to the medical and janitor cyborg module
adds: Adds robot analyzer to all cyborg modules
edits: Altered cyborg examine somewhat and added a reference cyborgs without a key for some reason
/🆑

**Comment by alexkar598** [comment]
This changeling represents better what is in this
Pr : 


🆑 matt81093
del: Removes the health analyzer from the standard cyborg module
adds: Added a matter decompiler to the medical and janitor cyborg module
adds: Adds robot analyzer to all cyborg modules
tweak: Altered cyborg examine somewhat and added a reference cyborgs without a key for some reason
/🆑

**Comment by shazbot194** [comment]
I can see a good reason in adding the cyborg scanner to the medical Borg so it can treat IPCs with nano-paste, but I''snot sure if adding it for scanning cyborgs is such a great reason.

**Comment by Taaketa** [comment]
Self Diags are a thing.

Medical borgs already a highlt comprehensive toolkit.

Nanopaste works on repairing borgs and it just works, no need for scan or open the hatch.

Janiborgs do not need a matter decomplier. They have theor trash bag for most objects. The fact they can't pickup everything with it is like their only weakness.

All borgs should have an area where they cannot accomplish a task. They aren't meant to be good as a crew member.

**Comment by FalseIncarnate** [comment]
Not necessarily agreeing or disagreeing with the borg analyzer addition, but that DOES also work for IPCs, not just borgs. It theoretically could be useful for medical borgs to at least diagnose the issues with an IPC before kicking them out of medbay.

The matter decompiler is an alright addition to the jani-borg. It can't decompile a ton of stuff, so it's not like you're gonna have them decompiling important equipment. The only potential issue I see is that (at least with drones) it technically recycles materials which the jani-borg doesn't normally have access to. It won't really affect anything since the code to actually then replenish stocks from those recycled materials is handled specifically on drones, so borgs wouldn't benefit from them anyways.

All-in-all, pretty neutral on this PR.

**Comment by matt81093** [comment]
@alexkar598 Whoops! That wasn't an intended change. Thanks for pointing that out.

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by matt81093** [comment]
Hmm, I think I'm going to close this. Might look at changing the trash bag code though? I might make a new PR with just the addition to the medborg.. cause IPC's, as mentioned. Although, actually... Janiborgs with a decompiler, I don't think would be a bad addition. Instead of treating everything as trash... Actually wait.. is there a machine in the trash area that deals with materials, or one that could be built in that area? If so.. probably a sufficient solution right there.

**Comment by Jountax** [comment]
@matt81093 The incinerator (which the disposals system leads to in the end) reduces any recyclable item into glass or metal, if that's what you mean. Everything else gets piled up to be spaced.

**Pull request closed without merging**
