### PR TITLE
Cigarette Pack Functionality

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds the ability to put cheap lighters and individual matches into cigarette packs at the cost of cigarette slots.
- A cheap lighter takes up the space of 2 cigarettes.
 - Zippos won't fit, they are too boxy.
- A match takes up the space of 1 cigarette.

Increases the w_class of all lighters (cheap, zippo, and special zippos) and cigarette packages
- Previously 1, now 2
 - Still fits in pockets, just can't shove as many into a box as they take up more space

Adds the ability to light and put out matches on your shoes.
- Good for when you lose that matchbox (or shove matches into a cig pack) and need a light.
- Works on all shoes, from the humble brown shoes to the devious syndicate magboots, and even the clown shoes.

Based on the suggestion from:
http://nanotrasen.se/phpbb3/viewtopic.php?f=12&t=6880

### CODE REVIEW

**Comment by Plotron** [comment]
More power to the people. :+1:

**Comment by Fox-McCloud** [comment]
don't personally think the weigh class increase is necessary. Cig packs nad lighters aren't big at all.

**Comment by FalseIncarnate** [comment]
The lighter one was to avoid a hackysolution to the storage space.

The cig pack... I forget why. Probably something silly like placing items that are "larger" (small vs tiny) into it seeming illogical.

I can return cig packs to w_class 1, but doing the same for lighters will require a hacky / snowflakey solution to them taking 2 slots of space in a pack.

**Comment by Fox-McCloud** [comment]
I don't really see the point of adding a snowflaked thing to make lighters take up multiple slots (as opposed to one) when that's not really consistent with any other storage container---when just adding in lighters to the can_hold list accomplishes what needs to be done.

**Comment by FalseIncarnate** [comment]
I'm going to hate myself for this next line, but...

The lighters taking up 2 slots (which this PR does without actual snowflake currently) is more for realism than storage concerns.

As of the writing of this comment (as this could change with a new commit), the only "snowflaking" in this PR is to give different rejection messages for a lit match or lighter into a cig pack, and to avoid trying to equip matches and lighters to your mask slot if you hit yourself in the mouth with the pack.

Increasing the w_class of the lighter to 2 allows the basic storage code regarding max_combined_w_class to make the lighter take up the same storage space as two cigarettes (which are w_class 1). The can_hold and cannot_hold lists were updated to allow the right objects, and the w_class was adjusted to make them take the right amount of space. This is not confined to their interaction with cig packs, all bags and boxes will hold fewer lighters because they are slightly bulkier than before.

**Pull request merged**
