### PR TITLE
Getting rid of aimbotmode

### PR DESCRIPTION
**Pull request by Spacemanspark**
https://www.youtube.com/watch?v=Sa8NREI_IPs
^The reactions of players that use Aimbot.^

Players:
This basically turns Aimbotmode into a mere overlay. Because fuck instastun + aimbotmode, learn some skill.

### CODE REVIEW

**Comment by TheDZD** [comment]
:+1:

**Comment by tigercat2000** [comment]
:+1:

This is going to start controversy, isn't it?

**Comment by Spacemanspark** [comment]
Probably.

**Comment by veganzombeh** [comment]
:+1: Honestly though, I'm not sure I see the point in just having an overlay. People are going to assume it's unchanged and still works like before, causing a lot of confusion. I'd say either remove the firing mode completely or leave it as is.

**Comment by Fox-McCloud** [comment]
Screw aim mode and the horse it rode in on.

:+1: 

I'm still ok with the overlay, because it's a good way of getting people's attention.

**Comment by FreeStylaLT** [comment]
:+1: fucking thing doesn't actually work as well as you might imagine nowadays

**Comment by Allfd** [comment]
:+1:

**Comment by fj45** [comment]
RIP stupidly broken game mechanic. About damn time.

**Comment by Krausus** [comment]
So, this obviously gets rid of the "move and get shot" feature of aim mode. Does it serve any other function?

If the only thing it will do after this change is apply an overlay, it should really be removed entirely, because *not* removing it will just cause confusion when it doesn't appear to work.

**Comment by Fox-McCloud** [comment]
@Krausus 

People will adjust to it, eventually. Mechanics change all the time and require adjusting to; this is no different.

**Comment by Krausus** [comment]
But the "Auto" icons, "Allow item use" button, and "You will now take people captive" text will be changed, right? They can't be left in a state where they'd be blatantly misleading.

**Comment by veganzombeh** [comment]
I suggest removing the "Allow item use" and "Allow walking" buttons, making the overlay go red instantly, rather than taking ~2 seconds to lock-on, and changing the name of the firing mode to "Single Target mode", or something and changing the text to "You can now only fire at the target you aim at."

**Comment by Fox-McCloud** [comment]
go ahead and remove the "use items" button, and I"ll merge this.

**Comment by Krausus** [comment]
It **must** be obvious that aim mode no longer does anything but place an overlay - we cannot have anyone getting screwed over because aim mode stopped shooting for no apparent reason. A few possibilities:
* Replace the icon with a new one.
* Remove the aim button entirely until a new icon can be made for it in a later PR.
* Make it so, the moment you click the button, you get an obnoxiously large warning in the chat box that you will only aim, _not_ automatically shoot.

> changing the name of the firing mode to "Single Target mode", or something and changing the text to "You can now only fire at the target you aim at."

I am almost positive that aiming at someone does not prevent you from firing wherever.

**Comment by veganzombeh** [comment]
@Krausus If you click on someone while aiming at someone else, you will aim at them, rather than shoot them, which is what I was getting at. It wouldn't be particularly useful, as people could easily move in front of your targets, though.

**Comment by ZomgPonies** [comment]
:+1:  with one of the changes Krausus mentioned.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

How goes this?

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Haven't even heard from you----is this still something you'll be working on?

**Comment by CrAzYPiLoT-SS13** [comment]
I can change the icon, but I really don't know how it should look like
after the icon we are currently using has been here for such a long time.

**Comment by Spacemanspark** [comment]
Too many issues going on IRL; couldn't respond.
I think this should be left to a more experienced coder.
If someone sees this before tomorrow, close it.

**Pull request closed without merging**
