### PR TITLE
Assorted security changes

### PR DESCRIPTION
**Pull request by Vivalas**
Updated image:
image

Adds blast doors near courtroom access, to make security lockdown less redundant, and gives magistrate a security records console, because it's kinda useful to them.

Update: also changes the shutters buttons in magistrate office. The "Privacy Shutters" button closes the hallway-facing ones, and the "IA Privacy Shutters" button now closes only the IA office facing ones, as well as a prisoner management console to make access to cell logs more easy.

Update 2: Adds special security records laptop that is red!

### CODE REVIEW

**Comment by Citinited** [comment]
You need a changelog, and you also you used your master instead of making a branch REEEEEEEEEEE

The two consoles seem like they'd make the magistrate's office really cramped (and are just placed in the middle of the room, which seems like the worst place for them). I think a redesign of the magistrate's office to incorporate the two consoles would be a good idea.

**Comment by Vivalas** [comment]
I suppose doing a smal remap of the office isn't too out of scope, it is a bit cramped already as is. This PR is just small issues I noticed over the course of a round.

**Comment by Birdtalon** [comment]
Perhaps give the magistrate a laptop?

**Comment by KingPhilipIII** [comment]
These aren't sec changes you liar. These are magistrate changes REEEEEEEEEE.

**Comment by Vivalas** [comment]
Is there a security records "laptop"? I would prefer that, but modular laptops don't have a security records program.

**Comment by Spartan6** [comment]
Why not put a recharger in his room and like, let him buy a laptop? It's what the detective used to do before his scanner could tell him everything.

**Comment by Vivalas** [comment]
If sec records existed for modular laptops, I would just do that instead as magistrate. The thing is they don't, and magistrate probably needs easy access to sec records.

Now, if there is not a security stationary la

**Comment by Citinited** [comment]
@Vivalas There isn't currently a security laptop, but it wouldn't be too difficult to sprite a new one and make a subtype of security computer that's a laptop. (Not suggesting you should do that)

**Comment by Vivalas** [comment]
Alright I reformatted the office, and added a red security records laptop to the magistrate's desk.

**Comment by Fox-McCloud** [comment]
Conflicts.

**Comment by Vivalas** [comment]
Huh, it's almost as if letting minor map changes sit in hiatus for 2 weeks causes that.

**Comment by tigercat2000** [comment]
This can be merged when the conflicts are fixed.

**Comment by Vivalas** [comment]
@tigercat2000 @Fox-McCloud @Crazylemon64 Conflicts fixed, sorry for the wait.

**Comment by tigercat2000** [comment]
👍

**Pull request merged**
