### PR TITLE
Dead/unconscious examine text rework. Can't see if somebody is dead now

### PR DESCRIPTION
**Pull request by farie82**
## What Does This PR Do
For the living:
- Makes it so that you can't see (examine) if somebody is dead or unconscious from a distance.
- Getting closer to them (2 tiles away) will show that they are not moving. Maybe unconscious. You will actually have to use the ingame technique "check pulse" to see if they are still alive or not.
- Rotting examine text also depend on range now. Early stages only show examine text from close range. 2 tiles for the first stage and 4 tiles for the second stage (it smells yo).
- You now can't see through somebodies skull to see if the brain is still in there.
- The catatonic message only shows on conscious humanoids now. Now you can try to pretend you died!

Observers and people with medical HUDs can still see who is actually dead and what not.

A medical health scanner will now show if the person still has a soul in them or not.

I left in the SSD notice since that's an OOC warning.

Idea originally from https://www.paradisestation.org/forum/topic/18693-remove-death-confirmation-text-from-examine-text/ with some tweaks.

## Why It's Good For The Game
Makes running towards a body a bit more of a risk. An antag can now pretend to be dead to trick somebody to come nearby. 
It will also make way for some interesting plays that a creative antag can do now.

## Images of changes
AAMjGPgPmq
Examine distances in action. Top ones are sleeping. Right ones are resting. Left ones are dead.
Bottom ones are dead and rotting. B is the first stage and A the second stage.

kIl4NXsXEL
Using a HUD will still show the text like before. The analyzer will show if they lack a soul. The examine text here shows that he's SSD but that's due to an already fixed logical mistake. It should show nothing since he's catatonic and sleeping.

## Changelog
:cl:
tweak: You now can't see if somebody is dead and will have to check his pulse. Unless you have a medical HUD
tweak: If somebody is dead or unconscious then you will only see this if you stand within 2 tiles of them. Unless you have a medical HUD
tweak: You can't see if somebody is missing a brain now. Unless you have a medical HUD
tweak: Dead catatonic humanoids now don't display the catatonic message if dead or unconscious
tweak: Rotting examine text now depend on distance which is 2 tiles in the first stage and 4 in the second stage. Unlimited in the stages after.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This needs to be split into two, as these two things really don't have anything to do with each other, remotely.

**Comment by FlattestGuitar** [comment]
You deserve all the hate you're going to get for forcing people to use a BYOND verb.

**Comment by farie82** [comment]
> You deserve all the hate you're going to get for forcing people to use a BYOND verb.

I can make it a hotkey if really needed. The people who know it exists will also come up with the tricks to use this system

**Comment by farie82** [comment]
> This needs to be split into two, as these two things really don't have anything to do with each other, remotely.

The resting does have something to do with this as it reduces the cheese you can achieve with the system. I'll split it up though

**Comment by SteelSlayer** [comment]
Only thumbing this down because it locks the ".. and their soul is departed" message behind being an observer. I know it wouldn't really make sense to have only that portion be visible to living mobs but still, that's my reason.

 I think it's very important for people to determine if they spend their time to revive some or not. Maybe you could put it in the health analyzer text or something maybe.

**Comment by farie82** [comment]
> Only thumbing this down because it locks the ".. and their soul is departed" message behind being an observer. I know it wouldn't really make sense to have only that portion be visible to living mobs but still, that's my reason.
> 
> I think it's very important for people to determine if they should spend their time to revive someone or not. Maybe you could put it in the health analyzer text or something.

Putting both the ability to see it on the Med HUDs and on the health analyzer.

**Comment by Regular-Joe-SF** [comment]
Neat stuff! The idea of having a radius on the visibility of the state of the body and apparent consciousness is great. Adds to the mood.

**Comment by farie82** [comment]
> At resting, the visiblemessage informing somebody of attempting to stand up probably wants to be ”...is attempting” pro ”is attempted”, typo?

Oh wew yeah that's a typo. I've moved those changes to #13429 now

**Comment by Carthusia** [comment]
Just to confirm: The "Their soul is departed" message is still visible?

This alone is extremely important for medical to be able to determine if the body they are trying to SR/SM/Borg is even a viable candidate and if they need to move onto the next patient.

**Comment by farie82** [comment]
> Just to confirm: The "Their soul is departed" message is still visible?
> 
> This alone is extremely important for medical to be able to determine if the body they are trying to SR/SM/Borg or just conduct surgery on is even a viable candidate for any procedure and if they need to move onto the next patient.
> 
> Ive had patients go soulless on me during mid surgery, at which time they are moved to the morgue and the next viable patient is moved into surgery.

It will be visible to those with Medical HUDs. You can also use a health scanner on the body now to see it.
For those without those tools it won't be visible without using a cloner.

**Comment by Carthusia** [comment]
Ah, im still kind of iffy on it not being visible to everyone.

Its more for OOC reasons than anything, the player is no longer in game, and thus is no longer able to interact with anything, if their SL and dead, they get pushed to the back of any priority list, similar to SSD players, but to a far greater degree, as at least an SSD may return.

Bomb goes off, 10 people wounded or killed, people are collecting the bodies for medical resurrection, guy logs out after he dies, civilians pulling the bodies to mebay have to pick the ones still viable to get to medical as fast as possible, but now that he cant see players who are no longer viable, drags an unviable body to medical, wasting their time and potentially putting active players at risk of becoming unsalvageable without extreme measures taken.

Overall, players should always be able to tell if a player is no longer there, be it a potential temporary SSD or a permanent soulless for the sake of flow.

**Comment by Fox-McCloud** [comment]
Even the "old" system didn't go this far.

If you were adjacent to them, you could still see their status. 


I get wanting to add more paranoia (which I support), but I  don't think this is really going to do it; most of the paranoia comes from how difficult (or easy) it is to engage in "metachecks" for antags or their actions.

This plays into that a *little*, but how useful it'll actually be is pretty debatable--making it so you can deliberately falsify the text for being dead would allow for similar end-goals while not messing with being able to sort out, in chaotic situations, who's dead or not.

Not being able to see who's soul has departed without a medhud is really bad though.

**Comment by Mitchs98** [comment]
I didn't support the idea when the idea was if they're dead or not on examine only, I don't support it further if the 'soul departed' text is locked behind a medical scanner for the reasons above. I also don't support the lack of a brain being there. I sincerely doubt traitors take the time to mend their incisions and fix up the skull when they steal a brain, so it's less seeing through a skull and more noticing the persons' skull is open and a brain is missing. 

Beyond that. I don't see this accomplishing paranoia as already stated. All I see it doing is making it harder for civilians/people in general to haul bodies/dying people to medbay, on top of my concerns I already stated on the forums.

**Comment by farie82** [comment]
In most cases you will know who is dead. Are they not moving and have a ton of brute damage during a nukie attack? Must be dead. Can also aid the people trying to fight the nukies. By just laying down and resting. Hoping they go away since you are probably dead.

Medical personel won't have an issue with this due to them having medical HUDs on at all times. And I've yet to see people not drag away a dead body from a place because his soul is not in his body. That is a bit meta in my opinion.

I was thinking about making the check pulse verb check if their soul is still there. But seeing a medical scanner and HUD can do it now I don't think it is required.

I am mostly seeing the potential in antagging with this that you now cannot do. Using bodies to cover yourself in the open. Trying to sneak into the coroners office then faking death to get to him. Luring the officer to go check you out and have another agent jump him because he is your target. 

I also see some improvements down the line like ketchup or such faking brute damage on a person without a medihud.

**Comment by Regular-Joe-SF** [comment]
I would not see rescuing bodies from a mass casualty event as so big an effort that the examine text's preserence would affect it significantly. They have to get the bodies to medical and morgue either way, sooner or later.

> Medical personel won't have an issue with this due to them having medical HUDs on at all times. And I've yet to see people not drag away a dead body from a place because his soul is not in his body. That is a bit meta in my opinion.

In my opinion this change is very interesting due that, why should you know all this, death, state of consciousness, even the preserence of the brain, by just one glance, in the first place? 

To not be able to see those things would enable some minor tactics that you can't really pull by now, while the change would not take away (but this is the matter of controversy here sofar) from the game. I'd back the latter with the thing that reviving the dead is up to the medbay, that has the tools to do the triage quickly, as well as it's the job of theirs to do the triage. That for I'd think this could have a net good fo the game. A test would reveal the effect better?

By the way I got to confess, I thought I knew how medical works well, but I just realized I've never paid attention to that 'soul departed' text, but only utilized the cloner and morgue trays for judging the dead. I haven't experienced lacking that knowledge as a problem while working in medbay or rescuing bodies, though that's just my opinion.

**Comment by farie82** [comment]
Things people tend to forget is that people who are dying sound like somebody from an elderly home. They are constantly gasping very loudly every few seconds. Dead people do not do that.
Sleeping people also snore every now and then also suggesting they are not dead.

Only place where I can see this happening is in medbay where tons of people are on the floor. Yet medbay can see who is dead and who is not by just using their HUD and their examine text using said HUD.

**Comment by AffectedArc07** [comment]
Having to use a verb to check if someone is dead or not is not good. Put shortly, I dislike this.

**Comment by farie82** [comment]
A test to see if people can see if somebody is dead or not. Since I am sure that most people will recognize most of the dead. It being a verb is annoying that's true. But if somebody is dead you will still bring them to medbay 9/10 times.

Which of these are dead and which are not?
1.
image

2.
image

3.
image

4.
image

5.
image

6.
image

<details>
<summary>Answers</summary>

1. Still alive. Very hurt though

2. Dead.

3. Dead

4. Dead

5. Alive not hurt

6. Dead due to toxins

Here it was sort of hard to see who is dead and who not for 2, 5 and 6. Since IPCs don't gasp when dying it's a bit harder. Toxins also leave no trace other than maybe puke under them but that's also due to booze. But then again they snore if they are passed out drunk
</details>

**Comment by AffectedArc07** [comment]
After a vote, this has 2 maintainers and a head against it, and no one in favour. Closing.

**Pull request closed without merging**
