### PR TITLE
Updates headcoder list

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Removes Charlie from Headcoder team and adds him to CA and Review Team.
Removes me from CA and Review team and adds me to Headcoder team.

## Why It's Good For The Game
Charlie is a known serial finger biter, after winning court costs against him we traded jobs.
https://www.youtube.com/watch?v=_OBlgSz8sSM

### CODE REVIEW

**Review by GDNgit — APPROVED** [review]
SEAAAAAAAN

**Review by Burzah — APPROVED** [review]

**Review by JimKil3 — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]

**Review by AffectedArc07 — COMMENTED** [review]
Could you alphabetise the lists while you're at it?

**Review by AffectedArc07 — APPROVED** [review]

**Review by Contrabang — APPROVED** [review]
merge it

**Review by SteelSlayer — APPROVED** [review]

**Review by lewcc — APPROVED** [review]
ship it

**Comment by AffectedArc07** [comment]
NO HALF SENDS

**Pull request merged**
