### PR TITLE
EKatana Changes, Removes Ninja Eye Implant

### PR DESCRIPTION
**Pull request by SamCroswell**
- Adds a belt icon for the energy katana

- Modifies the code for the energy katana to bring it in-line with /TG/

- Removes the obsolete ninja eye implant. (Yeah, I might've had an ulterior motive to my vision update.)

Only creating the PR this early because it's the only modification to major icon files I should need to do in the project. No ETA on completion.

### CODE REVIEW

**Comment by KasparoVy** [comment]
What did the eye implant do, anyway? Thermals+NV?

**Comment by ZomgPonies** [comment]
Your map edit is failsauce, you need to use the maptools.

**Comment by TheDZD** [comment]
Yep, as Ponies said, map merge.

**Comment by SamCroswell** [comment]
@ZomgPonies @TheDZD @Fox-McCloud 

Fixed.

**Pull request merged**
