### PR TITLE
Make robot talk easier to read

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
Replaced the IBM font with the browser default monospace font. I think this looks less pixelated, less jarring, and more readable, while preserving the original intent of #8425 to make robot talk more robotic.

### Before

robot_before

### After

robot_after

### CODE REVIEW

**Comment by MarcellusPye** [comment]
Could we have comparisons with normal chatter/comms/logs for the different versions?

**Comment by Tayyyyyyy** [comment]
Okay, here's hopefully a better comparison:

### Before
robot_before

### After
robot_after

**Comment by MarcellusPye** [comment]
It seems like it's slightly larger than normal text, which is also an issue.

**Comment by Tayyyyyyy** [comment]
I've normalized the height, and in fact, it's still slightly shorter, but you're right, this font has letters that are particularly wide and thick. If this is an issue I can look for a better font or just revert the change altogether, depending on what staff think is best.

**Comment by davidchan13** [comment]
@MarcellusPye The entire point is to make it stand out.

**Comment by Ty-Omaha** [comment]
I'd rather have it look slightly larger rather than half the size of normal text. I'd also rather just revert it but I don't speak on behalf of all the staff.

**Comment by Tayyyyyyy** [comment]
How does this look? I applied the monospace font family rather than using the custom font:

robot_monospace

This has the advantage of not needing an extra font, and I think it fits a little better.

**Comment by Tayyyyyyy** [comment]
Okay, changed it to the generic monospace cause this is a much cleaner solution to the issue, imo. Can change it back if people don't like it.

**Comment by Vivalas** [comment]
Eh, this is just an opinion PR I guess, I like the old one.

**Comment by Shadeykins** [comment]
As a suggestion for a font, there are plenty of robotic looking fonts which use digital letters (IE: digital clock-style letters) that would make a nice choice.

I personally think the one we have looks the best, even with the sizing issue.

**Comment by tigercat2000** [comment]
Rather than straight up ditching the other font, could you please experiment with more font-size modifiers? I think that, with enough tweaking, we could make a value that fits into the chat better than the 1.3em did. Perhaps make a bunch of screenshots of nearby numbers for people to compare and vote on? 1.2em, 1.15em, 1.25em, etc

**Comment by Tayyyyyyy** [comment]
Sure! I'll put up a few screenshots in a bit...

**Comment by Tayyyyyyy** [comment]
Okay, sorry for the delay in screenshots. Here they are! I've labeled them with emojis too in case people want to vote.

### 1.1em 👍
1 1em

### 1.15em 👎
1 15em

### 1.2em ❤
1 2em

### 1.25em 😆
1 25em

**Comment by Ty-Omaha** [comment]
What if you want to vote for none of them? I don't know why robot font gets special treatment to be bold while everything else isn't. The image you posted before these ones seems adequate enough for people to see robot talk - if people can't see that then that's really on them.

**Comment by tigercat2000** [comment]
@Tayyyyyyy Let's go with 1.15em and see how that goes on live.

**Comment by Tayyyyyyy** [comment]
@tigercat2000 I probably should've said something earlier but I pushed a revert commit that I had ready for a while, so it doesn't show up after your comment saying 1.15em. But it's 1.15em now.

**Comment by Tayyyyyyy** [comment]
Another thing to consider: apparently IE8 doesn't support ttf fonts?

**Comment by DarkPyrolord** [comment]
👍

**Comment by tigercat2000** [comment]
To be clear, this PR makes robot talk look like this:

**Pull request merged**
