### PR TITLE
[BUGFIX] Add report_alerts variable to areas, zeroth law fix, cameranet code update

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds a report_alert variable to areas, and sets it to 0 for the Syndicate station, so the station isn't informed of atmos alerts there anymore.
2) The AI's OneHuman and quarantine laws can now be removed by using their respective boards on the upload.
3) Updates our camera code.
4) Reverts back from old viewpoint code to the system both Bay and /tg/ use. This was done for a number of reasons. Firstly, maintainability: if we stick closer to the two major codebases rather than using a system only we use, it'll be easier to stay up-to-date. Secondly, the old cameranet code didn't properly update areas when cameras were removed, whereas the new code does. This means that disabling a camera actually works now. Thirdly, the only reason we were using the viewpoint code was so we could have a complicated viewpoint system for the Mask of Nar'Sie. Obviously, this limits the mask a bit: it can now only jump to and follow cultists, but it is able to see all around it within nine tiles (meson + thermal, basically), so it'll be able to warn cultists that danger is coming.

The camera update includes better performance, as well as caching for the camera console. The AI can now also store camera locations, and jump to them.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Lemme know when this is ready.

**Comment by Markolie** [comment]
It's ready.

**Comment by fj45** [comment]
What exactly does four change?

**Comment by Markolie** [comment]
Players won't notice - it's mostly a backend change (aside from the AI actually being unable to see an area when cameras are depowered/destroyed). It does affect the Mask of Nar'Sie though, as it can only follow cultists now. That thing is in need of an overhaul anyway.

**Comment by fj45** [comment]
Yeah, got no idea what is with the mask. Broken cameras stopping the AI sounds very good.

**Pull request merged**
