### PR TITLE
Adds a new Medical Doctor alt title

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
Adds a new medical doctor alt title for use with PR #6969 when it gets merged.

This alt title spawns with nitrile gloves for protection during their procedures.

🆑 DaveTheHeadcrab
rscadd: Adds a new alt title for the doctor job, spawns with relevant gear.
/:cl:

### CODE REVIEW

**Comment by Rapidvalj** [comment]
I fully support this PR. Speed merge.

**Comment by DaveTheHeadcrab** [comment]
Also four merge commits for the express purpose of pissing tiger off.

**Comment by Crazylemon64** [comment]
What are you doing, you're legitimizing the meme AIs that call for "ass inspections in medical"

**Comment by DarkPyrolord** [comment]
"Captain report to medical for ass inspection."

**Comment by Xantholne** [comment]
I see we're embracing our new Vore lifestyle

**Comment by Lady-Luck** [comment]
actually merge it for real tho

**Comment by Screemonster** [comment]
https://www.youtube.com/watch?v=W2gABYTmXos

**Comment by Fox-McCloud** [comment]
o7 

It's a shame we never knew you.

**Comment by king5327** [comment]
The worst part about it is that this could actually work if it was an alternate title for the Psychologist instead.

**Pull request closed without merging**
