### PR TITLE
Removes z-levels

### PR DESCRIPTION
**Pull request by Robertha89**
Map size have increased from 255x255 to 1000x1000 giving space for future expansions.

image

Requires some changes regarding linking of z-levels.

:cl: PPI
rscdel: Removes z-levels
rscadd: Increases size of map, and adds the stuff from the z-levels there, with tons of open space for expanding to your hearts content
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
:-1: x :100: 

Just...no.

**Comment by Crazylemon64** [comment]
uhhh


uh

**Comment by CrAzYPiLoT-SS13** [comment]
Just..what?

**Comment by Crazylemon64** [comment]
Reasons not to remove Z-levels
* They allow space to feel more fluid, rather than a static map each shift, thanks to the "space toruses" that causes each loop
* This also prevents strategies which involve deliberate self-spacing based on calculated destinations
* They play a huge part in determining which parts DO and DON'T have radio communications
* Z-level separation defeats suit sensors

Also, it looks like your megamap still has a few old items, preventing compilation.

**Comment by Fox-McCloud** [comment]
Inb4 this causes DD to crash for people when you try to edit the map.

**Comment by Crazylemon64** [comment]
@Fox-McCloud DM, you mean?

**Comment by Fox-McCloud** [comment]
@Crazylemon64 

Yeah--DM.

**Comment by NTSAM** [comment]
why

**Comment by Stian0604** [comment]
Uh, won't this break a lot? Stuff like the admin Z level, etc.

**Comment by Regen1** [comment]
Won't this break a lot of stuff like the admin Z level, etc?

**Comment by tigercat2000** [comment]
jesus christ what? No

Do you have any idea how badly DD lags with huge map sizes?

**Comment by NTSAM** [comment]
Away missions would be pretty much non-existent as I don't see why the hell you'd put a beach in the middle of space.

**Comment by TheDZD** [comment]
Yeaaah, nope. Space transitions serve to differentiate space travel between rounds, which is a nice little touch and keeps people frok easily gaming space loot without any sort of effort. Not to mention the fact that DM is already shitty enough with 255x255 map sizes.
Additionally, this would make every PR fail Travis because it doesn't edit Travis.yml to compensate for the map changes.

**Comment by Robertha89** [comment]
Due to negative opinions, lets scrap this for now.
Also, the admin z-level would remain unchanged.

**Comment by Plotron** [comment]
wtf

**Comment by NTSAM** [comment]
wtf?

**Pull request closed without merging**
