### PR TITLE
Alexio's Cream/Lime/Orange Juice and Tomato Resprite

### PR DESCRIPTION
**Pull request by Eric6426-Blossom**
## What Does This PR Do

Resprites Cream, Lime, Orange and Tomato Juice
This was /not/ resprited by me, I am simply the one doing the PR, since the spriter cant - Alexios from the discord is the spriter

## Why It's Good For The Game

Soul removal c:  (And pretty sprite)

## Images of changes

image

## Testing

Spawned the 4 items, game did not explode, sprites look good.

## Changelog
:cl:Alecksohs
imageadd: Resprites Cream, Lime, Orange and Tomato Juice.
/:cl:

### CODE REVIEW

**Comment by Alecksohs** [comment]
ey its me

**Comment by matttheficus** [comment]
note, you can put them in the CL proper like this if you'd like them to appear as the author:

🆑Alecksohs
imageadd: Resprites Cream, Lime, Orange and Tomato Juice.
/🆑

**Comment by Eric6426-Blossom** [comment]
> note, you can put them in the CL proper like this if you'd like them to appear as the author:

Did it!

**Review by Sirryan2002 — APPROVED** [review]
sprite diffs are fine

**Comment by Alecksohs** [comment]
Lessfuckingooooo

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
