### PR TITLE
Adds croissant

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do

_Bonjour_

This PR adds croissant to the game, can be made via the oven. I made the sprite with the useful feedback of @McRamon and Crumpaloo in #spriting.

Recipe:
- 1 dough
- 1 egg
- 5u milk
- 5u sugar
- 1u salt

## Why It's Good For The Game

- More original food for Paradise
- Weakens the British

## Images of changes

image

image

croissant

<details>
  <summary>Process</summary>

  croissantprocess  
</details>

## Testing

1. Spawn in as chef
2. Put ingredients into oven
3. Start oven
4. Receive croissant

## Changelog
:cl:
add: Adds croissant to the game. You can make it via the oven by adding 1 dough, 1 egg, 5u milk, 5u sugar, and 1u salt.
/:cl:

### CODE REVIEW

**Comment by McRamon** [comment]
But what about chocolate glazed croissants!

**Comment by Miraviel** [comment]
> But what about chocolate glazed croissants!

They are super yummy but I don't trust myself I can sprite glazing properly without just making it muddy

**Comment by datlo** [comment]
We also need chocolatines (which is the right word for em and dont let any heretics say otherwise) for the paradise boulangerie experience, good start though

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Review by farie82 — APPROVED** [review]
A duly needed buff for the french on the server

**Pull request merged**
