### PR TITLE
Updates wooden floor sprites

### PR DESCRIPTION
**Pull request by DogsParadise**
## What Does This PR Do
Changes the current wooden floor sprites into a new one.
The old one is rather lacking, i imagine people are a tad used to them tho.

## Why It's Good For The Game
Better sprites that will fit more with the new sprites

## Images of changes
--See sabre post for new darker shade

Old:

image

image

New:

image

image

image

image

image

## Changelog
:cl:
tweak: Tweaks woodenfloor sprite
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
They look superb

**Comment by ppi13** [comment]
Holy fuck, this actually looks fucking great.
The old wooden tiles look so damn shitty in comparison, this is sexy, downright sexy.

**Comment by LordShekelstein** [comment]
This is some Stardew Valley shit, this is genuinely incredible. **BIG** step up, BIG.

**Comment by McRamon** [comment]
Definitely better than current so i don't mind it but i am disappointed you didn't try anything else

**Comment by DogsParadise** [comment]
> Definitely better than current so i don't mind it but i am disappointed you didn't try anything else

I am going to. 
But it's an alternate PR.
Still working on other versions

**Comment by FlattestGuitar** [comment]
I feel they might be just a tiny bit too shiny. I'd tone down the highlight a little bit.

**Comment by DogsParadise** [comment]
> I feel they might be just a tiny bit too shiny. I'd tone down the highlight a little bit.

Removed the highlight at right top corner. That is what is causing that.

**Comment by DogsParadise** [comment]
Here are some different versions for wood, i concepted:
image

**Comment by Carthusia** [comment]
So with all the new wood floor types, why not just make them craftable varients? So people can pick and choose

**Comment by DogsParadise** [comment]
> So with all the new wood floor types, why not just make them craftable varients? So people can pick and choose

Could do.. potentially

**Comment by Carthusia** [comment]
It would allow for a MASSIVE amount of customisation to areas, because i LOVE the new sprites, but it would be cool to have them each be a new type that people can pick and choose and arrange the, the potential here is huge.

**Review by S34NW — APPROVED** [review]

**Comment by SabreML** [comment]
Personally, I feel like it's slightly too bright when compared to the rest of the current 'Wooden x' sprites. (Chairs, tables, bookshelves, etc.)
That's not necessarily a *bad* thing of course, it could just be a different kind of wood, but I do think that a darker version would fit in better with everything else.

**Comment by DogsParadise** [comment]
> Personally, I feel like it's slightly too bright when compared to the rest of the current 'Wooden x' sprites. (Chairs, tables, bookshelves, etc.)
> That's not necessarily a _bad_ thing of course, it could just be a different kind of wood, but I do think that a darker version would fit in better with everything else.

This really is just as easy as changing the shade 1 tone darker. A fix that would take me only a few mins. I'll get back to spriting and showcase some examples when I am not over my neck in work.

Thanks for the feedback!

**Review by Dumbdumn5 — APPROVED** [review]
Apologies for the lack of review or comment here in a bit, but I really like the way 3 and 4 in the concepts look when paired up with the other furniture and wooden structures. Chances are those would need a recolor or a bit of an update to mesh better with the floors, but as a backdrop then the more faded look with a muted color makes it stand out really nicely.  Giving this my :+1:

**Comment by variableundefined** [comment]
Please deconflict @DogsParadise

**Comment by DogsParadise** [comment]
> Please deconflict @DogsParadise

Will do tomorrow, got a slightly darker tint as well if it's prefered

**Review by SabreML — APPROVED** [review]
Since I suggested that the wood should be made slightly darker, definite 👍 from me.
Like others have been saying, this really is a big step up from the current sprites.

**Before:**
Before
**After:**
After

**Comment by variableundefined** [comment]
Closing due to two maintainers objection - 
Those sprites are very nice looking in and of itself, but thematically, they look out of place relative to everything else on SS13 - too high details and nice looking.

**Pull request closed without merging**
