### PR TITLE
Make it easier to slide into DMs

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
**What does this PR do:**
It can be tricky to keep track of PM conversations and reply to them when there's a lot of stuff going into chat, when handling an incident involving multiple players, or when you need to go investigate stuff. This adds a window that keeps track of all of your PM conversations and allows you to reply to a conversation.

- Auto updates when receiving/sending new messages if it's open, but doesn't pop up or anything if you don't have it open
- Opens to your most recent conversation when you open the window.
- You can archive conversations to clear up your window.
- It adds a verb in the OOC tab so players can use this as well.
- Also allows for easier copy pasting of conversations for notes and stuff.
- Admins get the buttons.
- Unread indicator for new messages in other tabs (italics + *)
- Can be extended to things like asay
- Admins can use the ping button to force open a user's messages window to the conversation with that admin
- Typing indicator (works whether the other person is using the messages window or not)

window5

Updated interface with ping button:
image

Typing indicator:
typing

**Changelog:**
:cl: Tayyyyyyy
add: Messages window (My PMs in OOC tab)
/:cl:

### CODE REVIEW

**Comment by Couls** [comment]
it'd be easier if we could work it into a third tab after <info> and <text> like up here but I don't know how viable that is
image

**Comment by Ty-Omaha** [comment]
needs better formatting imo

**Comment by Tayyyyyyy** [comment]
@Couls I'm not sure that this is important enough to go all the way up there. I was just planning to put a macro on this if it gets merged

@Ty-Omaha I copied the formatting from the tickets system. It just looks more bare because it doesn't have the extra buttons (PP VV and all that). I can add them along the top if you think they would be useful. I was afraid it would make it look cluttered.

**Comment by Ty-Omaha** [comment]
well there's a different font and the text is blue iirc

**Comment by Tayyyyyyy** [comment]
Found a screenshot of the tickets detail UI. I'll make more stuff blue and the text bold when I get the chance.

**Comment by AffectedArc07** [comment]
@Tayyyyyyy we already have this in the ticket system, showing all messages in a ticket
image
*Simulated two users with [m] and [u]*

These also keep per ticket so we can see whats coming from where, and users can view their own tickets

**Comment by Tayyyyyyy** [comment]
@AffectedArc07  I'm aware of the tickets system and use it all the time. The ticket system is for a different purpose. If two potential metacommers are beating up someone, you can't really make them open tickets so that you can talk to them. This is for admin to player conversations rather than player initiated tickets.

**Comment by AffectedArc07** [comment]
Surely a way for admins to open tickets makes more sense right. Have an open ticket verb, pick the ckey/mobname, bam

**Comment by Tayyyyyyy** [comment]
That's what I initially set out to do, but the ticket system is really designed as a system for asking for help. The way messages are added to tickets is different from how they're added to a PM conversation. We also don't want to clutter the ticket system with things that are already being handled by an admin. It's just much more complicated to hack the ticket system into a conversation system.

**Comment by Shadeykins** [comment]
> 
> 
> Surely a way for admins to open tickets makes more sense right. Have an open ticket verb, pick the ckey/mobname, bam

If a ticket is opened it's between myself and the ticket opener. The person who opens the ticket is pretty much never the person you actually end up talking to.

More often than not, I have to completely turn off all logs and ghost ears every time I PM a person just to neatly keep track of the conversation. This would completely resolve the issue by creating a running page with a transcript of that conversation (meaning I can still keep logs on without worrying that the 30 messages a second spam out the person's response).

Hopefully that explains what this resolves.

**Comment by AffectedArc07** [comment]
image
why

**Comment by KasparoVy** [comment]
Lmfao it was a prime opportunity to crack that joke, I can aporeciate

**Pull request merged**
