### PR TITLE
Support holoparas can now also heal IPCs and robotic limbs.

### LINKED ISSUE #3814: Support Guardians cannot heal synthetics (IPCs)
**Problem Description**:
Support guardians, which can heal people, cannot heal IPCs.

**What did you expect to happen**: 
I expected my support guardian to heal my injuries, whilst playing as IPC

**What happened instead**:
The guardian was shown to heal me but nothing happened.

**Why is this bad/What are the consequences:**
Support guardians are supposed to be of great utility to its master and unless they are working in a team, half of an IPC's guardian is useless.

**Steps to reproduce the problem**:
1: Spawn IPC
2: Gain support guardian
3: Damage self
4: Have them try to heal you.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### PR DESCRIPTION
**Pull request by alex-gh**
Depends on #9519. Do not merge before it!
Fixes #3814

EDIT: Alright, was able to test it. Works for me.
:cl:uc_guy
Support holoparas can now also heal IPCs and robotic limbs.
/:cl:

### CODE REVIEW

**Comment by shazbot194** [comment]
Looks like this can have the do not merge tag removed, as the PR it depends on was merged.

**Comment by alex-gh** [comment]
It has, but this PR still has not been tested yet. 
Don't get me wrong, it compiles and should be trivial enough, but I was not able to get the multi-key login that I need to test it to work.

**Comment by shazbot194** [comment]
An easy way to test this is to make another account, load up the server with your host account, log out of your account on the byond menu, and log into the other account. If you didn't close your game when you log out, you will still be logged on in on that window, and you can now log in with the second account. It will bring up a popup every time you enter a new body, but otherwise works perfectly. It is how I tested xeno to MMI to borg for PR #9465.

**Comment by alex-gh** [comment]
Yep, that worked, thanks!

**Pull request merged**
