### PR TITLE
Removes warcrimes from the Syndicate medical dufflebag and brig physician's vest

### PR DESCRIPTION
**Pull request by E-MonaRhg**
## What Does This PR Do

Removes red crosses from the Syndicate medical dufflebag and brig physician's vest

## Why It's Good For The Game

Warcrime bad ~~apparently~~.

## Images of changes

From:
image
To:
image

And from:
image
To:
image

_Onmob sprites included_

## Changelog
:cl:
tweak: Removed warcrimes from the Syndicate medical dufflebag and brig physician's vest
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]

**Comment by ManiacalSymphony** [comment]
I believe the brig doctor's jumpsuit itself has a red cross too

**Comment by datlo** [comment]
I think changing the syndicate bag to a black cross would be more thematic.
👍 still tho

**Comment by Wojz** [comment]
I agree that green looks wrong on syndi duffel. I'd go with black.

**Comment by E-MonaRhg** [comment]
The question is, how black?
image
Would this be good enough or is it too dark?
I myself think that the green cross doesn't look all that bad on it.

**Review by dearmochi — APPROVED** [review]

**Comment by TheYeetster1** [comment]
I like green it has a nice contrast.

**Comment by shawnhind** [comment]
Is this a joke PR?  Why is a red cross a war crime?

**Comment by E-MonaRhg** [comment]
> Is this a joke PR? Why is a red cross a war crime?

https://www.pcgamer.com/uk/how-the-prison-architect-developers-broke-the-geneva-conventions/

Better safe than sorry?
Also still on the fence of making the cross black, green looks fine to me.

**Comment by shawnhind** [comment]
Oh that's really interesting.  I feel like that context would be useful in the description of the PR.  the way it's phrased "Removes warcrimes from X and Y" makes it sound like a meme but if it's actually a protected symbol that shouldn't be there that makes sense to change it.

I like the black better just my opinion.

**Comment by E-MonaRhg** [comment]
Honestly someone with more spriting know-how should replace the red crosses, and do a more through search while at it.

**Pull request closed without merging**
