### PR TITLE
Genetic Instability Refactor & Minor Genetics Rebalance

### PR DESCRIPTION
**Pull request by TheDZD**
:cl:
tweak: Lowered genetic instability damage thresholds by 5 across the board. Effectively meaning that you can have one additional minor power without shifting into the next threshold.
tweak: Lowered the rate at which damage scales with instability, and the decreased upper cap on each damage type.
tweak: The base activation probability for powers is now 100%, rather than 45%. Abilities affected include everything except Cloak of Darkness, Chameleon, No Breathing, Hulk, Telekinesis, and X-Ray Vision, which all have their own independent activation chances (varying from 5% to 10%).
tweak: Increases activation chances of TK (10% to 15%), No Breathing (10% to 25%), Cloak of Darkness (10% to 25%), Hulk (5% to 15%), X-Ray Vision (10% to 15%), and Chameleon (10% to 25%).
/:cl:

Reasoning for most of the changes is to tone down some of the prior nerfs to genetics to make it less of  dead department, as I definitely overnerfed it. Reasoning for that last change in particular was because when I made #4797 I thought all powers except those noted above were guaranteed to activate.

Code-wise, changed some numbers to defines, and also changed some instances of division use to multiplication.

### CODE REVIEW

**Comment by Lady-Luck** [comment]
I personally would much rather see the genetic instability thresholds left how they are right now, but getting rid of the power activation chances altogether since it's inherently a very frustrating mechanic. Imagine if we tied RNG to everything that needed to be nerfed.

And yes.. I know it was originally intended to have this RNG and it was broken for a long time. That doesn't mean the original intention was good.

**Comment by uraniummeltdown** [comment]
It would be much better to just revert that PR entirely, the Genetics issue was exaggerated by Sec/Command players who were annoyed that the almighty taser couldn't stop a superpowered antag who spent his entire round working for powers. It wasn't a nerf but an outright removal. Genetics has 55 blocks, it takes ages to get through that. The addition of RNG to power activation (yes TG has it but they have half our blocks) made it even more time consuming, having to test yourself multiple times for a power, and the instability means you have to cure yourself of any powers you find or you'll die. Did you even take into account that the DNA Machine has a cooldown on DNA Injectors? You can't just spam them. Genetics, a job taking from 50 minutes to 100 minutes depending on skill and RNG, was made even more time consuming, and now you can't even benefit from all your powers you worked for. There was no need to gut Genetics just because a few whiny Sec players can't aim with lethals at hulks. If you absolutely MUST nerf Genetics keep the activation RNG but remove the godawful instability system.

**Comment by Fox-McCloud** [comment]
May just want to bump up all the outliers to 10-20% or something like that.

**Comment by KasparoVy** [comment]
I'll play Genetics regardless, but I'm glad we're taking a step back in what I feel is the right direction here. Hopefully it strikes an agreeable middle ground.

**Pull request merged**
