### PR TITLE
Makes all bitflags use bitshifting

### PR DESCRIPTION
**Pull request by Adrer**
## What Does This PR Do
Make all bitflags use bitshifting to define the flags rather than numbers.

## Why It's Good For The Game
It's good to have a single style for bitflags and bitshifts are more readable than numbers.

## Changelog
NPFC

### CODE REVIEW

**Review by DGamerL — APPROVED** [review]
LGTM, the contributing.md part does need a HC vote still

image

Also, github online is showing this weirdly, I assume it looks fine in VSC?

**Comment by Adrer** [comment]
> LGTM, the contributing.md part does need a HC vote still
> 
> image
> 
> Also, github online is showing this weirdly, I assume it looks fine in VSC?

Yes looks properly spaced in VSC.

> LGTM, the contributing.md part does need a HC vote still
> 
> image
> 
> Also, github online is showing this weirdly, I assume it looks fine in VSC?

Yes, looks normal on VSC

image

**Review by Contrabang — APPROVED** [review]
Lets get this merged

**Comment by FunnyMan3595** [comment]
> Also, github online is showing this weirdly, I assume it looks fine in VSC?

Yeah, for some reason, Github's PR view uses a tab width of 8, but if you go to `... -> View file`, the full file view uses a tab width of 4, which is what we use.

**Review by Contrabang — APPROVED** [review]
lets get this merged

**Review by S34NW — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
