### PR TITLE
Revenant resprite

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
Resprites revenant

## Why It's Good For The Game
Revenant is outdated

## Images of changes
image
dreamseeker_Ra9DXr50B6
gVq5utve7Y

I have also resprited effects that revenant is using, however they are not a major upgrade. just to bring the colors more in line with the resprite.

## Testing
Spawned revenant, used abilities to see if all sprites look as intended.

## Changelog
:cl: McRamon
tweak: resprites revenant
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
megahype

**Comment by DogeDogIs** [comment]
damn this revenant looks pretty pretty good

**Comment by ItsMarmite** [comment]
Goodbye lean flavoured dorito

Bring on the trenchcoat flasher ghost

**Review by Sirryan2002 — APPROVED** [review]
both icon diff bots appears to be struggling horrendously, checked the DMIs and it appears that the sprite changes are all fine. Looks good to me

**Pull request merged**
