### PR TITLE
Adds hud compability

### PR DESCRIPTION
**Pull request by improvedname**
Adds hud compability, you can now wear multiple huds at the same time.

images
**New sechud**
https://i.imgur.com/KL8U0n6.gifv

**New medhud**
https://i.imgur.com/ct20jV7.gifv

**All huds**
https://i.imgur.com/gj1FOGx.gifv

**All huds + Antag hud**
image

Tweaks in icons are the following. (mostly made smaller)

New mindslave master hud
image

New mindslave hud
image

New vampire hud
image

New vampire thrall hud
image

New rev hud
image

new head rev hud

image

**Changelog:**
:cl:
tweak: Mindshield implant, is now shown by a green flashing outline of your job hud
tweak: Moves some huds around to make them not overlap
tweak: changes some icons
fix: fixes two missing pixels on execute status
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
Maybe also update the ghost HUD verb so it just shows all of them at once? Or at least, has that as an option?

**Comment by Ty-Omaha** [comment]
I would prefer if the mindshield wasn't flashing, seems distracting, but that's just me

**Comment by improvedname** [comment]
@ty-omaha any other suggestions? The flashing is so its noticable since a officer without a mindshield is a big deal

**Comment by improvedname** [comment]
@kyep thats a scoop for another pr

**Pull request merged**
