### PR TITLE
Remove unused syndicate sprites from the custom-synthetic.dmi file

### PR DESCRIPTION
**Pull request by variableundefined**
**What does this PR do:**
As per title.

This morning, I was contacted by a player about an issue with their syndicate borg sprite. Upon further investigation, it was found out that syndicate borg was never accompanied for in code (Or policy) - bloodhound, peacekeeper & syndicate borg icons were added even though they did not function.

Because syndicate borg should be recognizable at first glance, they should not have custom sprite in the first place. The reason this wasn't brought up in the PRs that added them was that we weren't aware that -bloodhound (or syndicate, for that matter) PR were never meant to function. Bloodhound was never a modtype in game, and they were added in for unknown reasons. It is assumed to be a sort of syndicate sprite.

This PR also performs some clean-up by removing peacekeeper sprites and TUC's unused fluff AI screen, which is entirely redundant with the alien AI screens already present in our codebase.

A future PR might be made to enable the alien AI screen for everyone.

Affected included:
1. FullOfSkittles' Bloodhound & Peacekeeper Sprites
2. Driker's Bloodhound
3. TUC's AI sprites
4. Desolateg's service & peacekeeper sprites
5. Sniperfairy's syndicate-medical, syndicate & peacekeeper sprites
6. Banangarang's syndicate sprite.

**Changelog:**
🆑
remove: Unused syndicate & bloodhound, peacekeeper custom fluff borgs sprites. No actual effect.
tweak: Desolate's peacekeeper fluff cyborg sprite is now his service sprite.
/:cl:

### CODE REVIEW

**Comment by variableundefined** [comment]
Turn out this PR is incomplete - Bloodhound sprites are also unused.

**Comment by granodd** [comment]
I wouldn't disallow fluff sprites for Syndicate borgs.. Rather I would say we should be enforcing a sort of standard that fluff borgs of this sort follow. For example: a distinct black body paint with red highlights, and grey as a secondary color. Alongside that, fluff borgs on the non-Syndicate side should be disallowed these schemes.

**Comment by variableundefined** [comment]
The sprites has not been included before on the previous custom borgs' sprites. They started to be included when Driker's PR added in a -Bloodhound sprite customization with a nuke op head and slight black colourization. This was followed by Fullofskittles' -Bloodhound sprite.

Then it was followed by Banangarang's PR where a syndicate one was included, possibly due to them being mistaken that it worked, then it was followed by Shazbot adding in a -Syndicate and -SyndicateMedical sprite.

At no point did -Bloodhound or -Syndicate modtype ever functioned.

**Comment by tigercat2000** [comment]
The way I see this;
1. These sprites have never worked. Even if the one PR made to allow them to work had actually been merged - these sprite icon_states were made under false assumptions and would have never actually functioned. 
2. This doesn't actually represent any policy change. If someone deliberately tried to add a "syndicate borg sprite" today, it would not be accepted, due to the concerns we've brought up about balance. The syndicate borg should be extremely obvious, and the only way to ensure that is such is by making sure that it's visual appearance is consistent. It should not have alternative sprites nor custom sprites. The borg is a "go loud" tool, it is not meant for stealth missions, especially not when the only way to take it on stealth missions would be for the player manning the borg to have paid real life money to us.

**Pull request merged**
