### PR TITLE
Adds the Supply radio channel to Generalist cyborg

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

Title.

## Why It's Good For The Game

Generalist cyborgs have mining equipment and can be suited to help Cargo staff in a pinch. Therefore, having access to the Supply channel would be useful to communicate.

## Changelog
:cl:
add: Generalist cyborgs can now talk in the Supply (:u) channel
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
P sure you can already give a cyborg a radio key as is. Not really a fan of this.

**Comment by Kyep** [comment]
Generalist cyborgs were never really designed/intended for mining or other off-station activities.
That's why they don't have a supply radio key. The actual mining module is a better fit for that.

**Comment by dearmochi** [comment]
Following that logic, why do they have Engineering, Medical or even Security radio?

**Comment by Kyep** [comment]
Eng/Med/Sec are things they can do on station. They're intended to be general assistants _on station_.
When I added them, I did not intend them for off-station stuff.

That said, I don't really mind either way on this PR. I'm not objecting here. I'm just pointing out that if someone wants to do mining, the mining module is better. Generalists can do multiple things on station, but that breaks down a bit on Lavaland.

**Comment by dearmochi** [comment]
Mining aside, Generalist cyborgs can also help around Cargo Bay with crates and such - they aren't limited to mining when it comes to fulfilling Supply roles.

**Comment by Kyep** [comment]
I guess. Don't cargo techs usually end up idle half the shift, though?

**Review by Dumbdumn5 — APPROVED** [review]
Considering their all-arounder purpose and consistency with their role in other departments, :+1:

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
