### PR TITLE
Nerfs sentient AI in our code

### PR DESCRIPTION
**Pull request by tigercat2000**
IT PASSED THE TURING TEST! ABORT! ABORT!

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
If we're removing this, I don't see why leave the brain damage memes intact.

They're awfully confusing for new players and they're not funny the 60th time you see them.

**Comment by tigercat2000** [comment]
@FlattestGuitar We have to wait for that to ripen until someone gets permabanned over it too

**Comment by FlattestGuitar** [comment]
Can do!

🔨

**Comment by Spacemanspark** [comment]
Wait someone got perma'd?
Also yaaaa we really don't need this. :+1:

**Comment by Fox-McCloud** [comment]
Ehh, I'd rather see it stay, but I'm not attached to it, either.

**Comment by Crazylemon64** [comment]
```
Permanently banned - Charles Baum shouts, "FURRIES ARE OPPRESSED!" Charles Baum asks, "WHAT DO YOU MEAN xX360noscopeXx ISN'T AN ACCEPTABLE NAME?" Charles Baum yells, "SHITMINS! SHITMINS! SHITMINS!" Charles Baum says, "I OWN THIS SERVER NOW, I JUST BOUGHT IT." Come back when you are ready to play seriously. by _____ on 2017-02-19 17:43:12 (Server: Paradise Station)```
(the person in question has been since unbanned, though)

**Comment by FlattestGuitar** [comment]
Also, let's not nuke the thing but replace it with lines that do actually make sense in-character, somehow.

**Comment by SamHPurp** [comment]
If written better IC-like... I kinda enjoy it. I'd rather keep but re-write.

**Comment by Spacemanspark** [comment]
Hahahahahaha poor Charles

**Comment by tigercat2000** [comment]
IT LIVES! Those fucking mad scientists revived it! But they bothered to include a filter this time.

**Comment by FalseIncarnate** [comment]
Not my fault an admin fell for this.

Keep it as-is.

**Comment by SamHPurp** [comment]
@FalseIncarnate its a cheeky fourth-wall breaking easter-egg, but might be better to at least theme it ICly.

**Comment by FalseIncarnate** [comment]
It's also something that passed review with no complaints. So again, not my fault our admin fell for this when it was something that had been in the code for a while. The lines were added in https://github.com/ParadiseSS13/Paradise/pull/5075 back in July 2016, so there has been plenty of time for this to be known.

**Comment by tigercat2000** [comment]
@FalseIncarnate Would you please stop saying "not my fault" in this PR? No one is blaming you, but this code is very unserious and literally lead to out of game consequences for a player.
Don't take it personally.

**Comment by taukausanake** [comment]
I am curious as to what happened. Kind of like the funnies that is this drink

**Comment by FalseIncarnate** [comment]
A player drank (or was otherwise made to have the reagent in their body) and an admin noticed their shouting, mistaking it for intentional shouting.

And tiger, I know no one is blaming me. I'm merely stating that if an admin doesn't understand something, they shouldn't ban without a PM, such as in this case. The messages were chosen to best reflect the greytide "mentality" (or lack thereof), and were actually in many cases (such as ones you are removing) direct quotes or references to things actually said.

Also, I am very un-serious. (not my fault) ((totally my fault))

**Comment by tigercat2000** [comment]
@FalseIncarnate Well, alright, that's just the vibe I got off your comments. My bad.

**Comment by tigercat2000** [comment]
@FalseIncarnate Well, alright, that's just the vibe I got off your comments. My bad.

**Comment by Anasari** [comment]
Most of the original quotes were way too meta/memey for a MRP server, so I support the changes made here.

**Comment by Crazylemon64** [comment]
@FalseIncarnate If we let things stay in because they "Passed review", we'd still have the joy mask.

**Comment by uraniummeltdown** [comment]
joy mask did nothing wrong

**Comment by Spacemanspark** [comment]
It existed

**Pull request merged**
