### PR TITLE
Rod Of Asclepius Nerf

### PR DESCRIPTION
**Pull request by Leanfrog**
## What Does This PR Do
This PR nerfs the RoA drastically by reducing the healing it does as well as removing the ability for it to heal clone, stamina, and internal damage (I.E broken bones, IB)

## Why It's Good For The Game
Currently the RoA is incredibly powerful, it heals all damage types, mends internal damage, it even heals cyborgs and simple mobs, and works in AOE. All this while pulsing every 2.5 seconds, this makes it incredibly powerful against biohazards and for general use, a non antag doctor essentially has no reason to not use the RoA as it effectively has no downside besides losing a hand (you can still use non conventional self defense methods, slips and such). 

## Changelog
:cl:
tweak: Reduces the healing done by the Rod Of Asclepius from 3.5 to 2.5 for carbon mobs, removes the ability to mend internal damage and heal clone and stamina damage, also reduces the healing done to cyborgs from 3.5 to 2. Also reduces the AOE to a 4 tile radius
/:cl:

### CODE REVIEW

**Comment by nukularpower** [comment]
seems weird to me that it works on synthetics at all...

**Review by SteelSlayer — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Review by variableundefined — COMMENTED** [review]
Code looks fine to me. 

I have no opinion either way, might change my mind if persuaded.

**Comment by Leanfrog** [comment]
Changed the amount of healing done to 2.5 from 1.5 and also reduced the AOE from 7 tiles to only 4

**Review by Kyep — APPROVED** [review]

**Comment by Edan52** [comment]
Very strong nerf, considering its downsides. I can't see why you'd want to use this at all anymore.

**Comment by Marginalorb** [comment]
If the RoA gets touched at all IMO it should either be a complete rework to it or a removal. The thing's a buggy piece of junk that literally cannot be deleted from a person even with admin commands short of some VERY extensive var edits.

**Comment by variableundefined** [comment]
Changing my vote to an objection because this is too strong of a nerf. Closing due to two maintainers objection.

**Pull request closed without merging**
