### PR TITLE
Add myself to review team in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by FunnyMan3595**
## What Does This PR Do
A wild FunnyMan appears!

## Why It's Good For The Game
Less reviews needed for other PRs, so mine can get reviewed and merged sooner.

## Images of changes
image

## Testing
I ran a simulation of the universe, and it didn't end for at least 10 minutes after this PR was merged. LGTM.

## Changelog
add: Yet another role to FunnyMan.

### CODE REVIEW

**Review by DGamerL — CHANGES_REQUESTED** [review]
Please run that simulation for at least 10 minutes

**Review by Contrabang — APPROVED** [review]
looks funny to me

**Comment by DGamerL** [comment]
Untested PR, I just checked with ChatGPT, there is no machine that can handle the sheer absurdity of SS13 code (yet)

**Review by Burzah — APPROVED** [review]

**Comment by Contrabang** [comment]
let the ci run you nerds

**Comment by FunnyMan3595** [comment]
> Please run that simulation for at least 10 minutes

Done.

**Review by DGamerL — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]
LETS GO FULL SEEEEEEND

**Pull request merged**
