### PR TITLE
Lavaland: Remaps the Mining Outpost

### PR DESCRIPTION
**Pull request by DogeDogIs**
This PR remap the entire mining outpost.  The old mining post
his time was already counted. A new outpost was made from scratch WITHOUT that bridge.

## What Does This PR Do

This PR remakes the miners' outpost from scratch, so with a new atmos and some new implementations. The old outpost had some flaws, so instead of just fixing those flaws, it was completely redone.

## Why It's Good For The Game

With this new outpost, which we want to add more stuff in the future, antags can see new opportunities to do new things, and at the same time, miners can also take advantage of the new space.

## Images of changes

image

## Testing

It was tested at my local host server.
## Changelog
:cl:
tweak: Remap Mining Outpost.
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
image

image

**Comment by S34NW** [comment]
Your CI is failing because there are two window spawners on a turf.

Also disposals is a bit messy and could do with a touchup <3

Nice to see someone giving lavaland some love.

**Comment by DogeDogIs** [comment]
> image
> 
> image [ image ](https://camo.githubusercontent.com/7b5f389e3d468a499a78c10e23a4f77367429f12fe7dd22c1358fcb75629be4f/68747470733a2f2f632e74656e6f722e636f6d2f6b48636d73786c4b48454141414141432f726f636b2d6f6e652d65796562726f772d7261697365642d726f636b2d73746172696e672e676966) [ ](https://camo.githubusercontent.com/7b5f389e3d468a499a78c10e23a4f77367429f12fe7dd22c1358fcb75629be4f/68747470733a2f2f632e74656e6f722e636f6d2f6b48636d73786c4b48454141414141432f726f636b2d6f6e652d65796562726f772d7261697365642d726f636b2d73746172696e672e676966)

MISSCLICKS AND MORE MISSCLICKS!

**Comment by DogeDogIs** [comment]
> Not sure if my PR #18663 gets accepted, but if so, you can safely remove the GPSs from the table. :D
> 
> I'll give this a review tomorrow or so, mapping-wise!

Sure!

**Comment by AffectedArc07** [comment]
This PR currently has 3 design objections. Reasons include:

- This is change just for the sake of change, which is against our mapping guidelines
- This will encourage even more use of the outpost as a metabuddy hideout
- The full maintenance area is highly superfluos and will just encourage an even worse mining station cult paradigm 
- Its a mining outpost on a hostile world, it should have the bare essentials and nothing more.

I myself would not be opposed to a removal of the dorm rooms and a shrinking of the canteen to just a small chill room.

**Comment by RagingLemons1** [comment]
>     * This is change just for the sake of change, which is against our mapping guidelines
cough medsci remap cough 
>     * This will encourage even more use of the outpost as a metabuddy hideout
metabuddy hideout? explain?
>     * The full maintenance area is highly superfluos and will just encourage an even worse mining station cult paradigm
doesn't seem any worse than mining station dorms cultwise
>     * Its a mining outpost on a hostile world, it should have the bare essentials and nothing more.
seems like it's the same essential supplies plus some tools, another mechsuit charger (which it needs), and more bar dispencers

**Comment by AffectedArc07** [comment]
> cough medsci remap cough

The medsci remap is designed to fix inefficiencies and other issues in 2 of the most widely used area on the station, and handle one of the most contentious design isses we have had (genetics departmental ownership). Cobmine this with many needed upgrades such as a more impactful scichem room, the addition of a maints robotics bay, as well as a xenobio kill room, the remap has reason to exist. I dont know why you went with this as an argument

---

> explain? 

I have seen several instances where people just use the mining outpost as a place to cart their metabuddies off to in disasters and establish a culture of "you're not special enough to be my friend, and thus you aren't going to be taken to safety". Its a toxic gameplay culture and I do not want anything which will further encourage that

---

> doesn't seem any worse than mining station dorms cultwise 

You are comparing a 2x2 room which usually gets knocked to a flat area to an entire maze of maintenance walls which can easily be falsified and made even more convenient, not to mention have people bola-camping around blind spots, and dont even get me started on the single-tile walkways with 0 shot dodge change

---

> seems like it's the same essential supplies plus some tools, another mechsuit charger (which it needs), and more bar dispencers

Where do bar dispensers fall under bare essentials?

---

None of these arguments hold any weight, they just seem like whining over change that isn't going in. And on that note, given this PR has 4 design objections now, with pretty much everyone being against it (no one is in favour), this PR will be closed.

**Pull request closed without merging**
