### PR TITLE
SSprojectiles - smoother and saner projectiles

### PR DESCRIPTION
**Pull request by dearmochi**
## What Does This PR Do

- Ports part of TG's `SSprojectiles` subsystem.
  - Instead of `sleep`, projectiles are processed in a ticker subsystem. This comes at an increased performance cost but allows for smoother and more accurate hit detections.
  - Hitscan has not been ported since we don't use it.

## Why It's Good For The Game

Saner projectile handling, uses a subsystem instead of BYOND's timing system. On the visual side, smoother projectile movement.

## Images of changes

brwnLCIz7j

w0e8c8G8qL

https://cdn.discordapp.com/attachments/145700319819464704/910546021824745522/YmjTgl0SgZ.mp4

## Changelog
:cl:
add: Rework the movement of projectiles, allowing them to move more smoothly
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
> This comes at an increased performance cost but allows for smoother and more accurate hit detections.

I am ok with the more accurate hit detections but I worry a lot about the performance, especially on highpop nukies when theres bullets flying everywhere.

**Comment by AllStickyGithub** [comment]
The way emitter projectiles interact with reflectors looks weird.

**Comment by AffectedArc07** [comment]
> The way emitter projectiles interact with reflectors looks weird.
qcbmceCZYw

**Comment by dearmochi** [comment]
TM went without a hitch

**Comment by dearmochi** [comment]
Need to check why projectiles don't respect flipped tables

**Review by AffectedArc07 — APPROVED** [review]
This has been TM'd for long enough

**Pull request merged**
