### PR TITLE
Added flashers + fixed HoP's flasher

### PR DESCRIPTION
**Pull request by Jazz23**
**What does this PR do:**
Include a small to medium description of what your PR changes. Feel free to give it a little flourish if you want to show off a new feature more completely.

Fixes https://github.com/ParadiseSS13/Paradise/issues/10223. As stated in the issue, the mounted flashers in perma don't have buttons to trigger them. This PR simply adds buttons that are connected to these flashers to allow security to activate them from outside the prison. Furthermore, this PR fixes the HoP's flasher button not triggering the mounted flash in the HoP line, as mentioned by @Eniraz .

**Images of sprite/map changes (IF APPLICABLE):**
image

**Changelog:**
:cl: Jazz23
add: Added flasher buttons in security's perma brig that allow for the mounted flashes near the beds to be triggered from the outside (not possible before). This is described in #10223 when they mention "flashes in perma don't even have buttons to activate them."
fix: HoP flasher button now triggers the mounted flash in the HoP's line. This is a reponse to "The HoP line flash button does nothing"
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
Few things,
Did you mapmerge this? This feels like it should not mapmerged.
You need pictures of any map edits.
Your changelog is very vague.

**Comment by variableundefined** [comment]
1. PLease make sure it doesn't conflict it.
2. You need a much more informative changelog - What, where, why, etc. are all missing.
3. There's literally no description of what this PR does besides the description. Fixes [insert number here] is a good idea for fix PR, however it does not suffice on its own as a description. 
4. You did not remove the template - Please do so

**Comment by variableundefined** [comment]
Your paragraph is not readable at all.

Please fix that.

**Comment by Ty-Omaha** [comment]
> I thought maybe yall would simply see the 4 lines of code (which includes coordinate points) then understand.

Click "files changed" at the top of this PR and then hit "Load diff"

If you don't map merge things won't show up as the "4 lines of code"

https://github.com/ParadiseSS13/Paradise/pull/9437/files

There is an example of a map-merged PR

Map merge is a tool found here with instructions: https://github.com/ParadiseSS13/Paradise/tree/master/tools/mapmerge

Your changelog is still not great, it should specify what map this is for
 Additionally: "add: Flasher Buttons that allow for the moutned flashes to be triggered from the outside (not possible before)." is very uninformative. Where are these flasher buttons added? In the bridge? In botany?

**Comment by Jazz23** [comment]
> Your paragraph is not readable at all.
> 
> Please fix that.

I have no Idea what else to add, also which part of my paragraph? I extended the changelog as much as I could, I have no idea what else to say for the description bit since its a direct response to another existing post, If you want me to rewrite what Eniraz said in his bug report I'd be happy to do so but I thought that might be a waste of time. I honestly don't know how much more I could elaborate, but I will map merge as well as fix a couple of other Delta issues I saw some people posting.

**Comment by variableundefined** [comment]
Your entire paragraph is unreadable. You shouldn't string together multiple unrelated ideas into the same paragraph.

**Comment by Jazz23** [comment]
> Your entire paragraph is unreadable. You shouldn't string together multiple unrelated ideas into the same paragraph.

Is that references my changelog or my "Fixes #10223 "?

**Comment by variableundefined** [comment]
To the comment posted that started with "Yikes man".

Anyway, please fix the merge conflicts.

**Comment by Jazz23** [comment]
yea, I'm adding a few more fixes along with a map merge right now

**Pull request closed without merging**
