### PR TITLE
Space-proofs Perma from Vox / Plasmamen

### PR DESCRIPTION
**Pull request by FreeStylaLT**
This was suggested as a possible alternative to a full-fledged Perma remap as a possibly solution. I did do the same thing before, but I went a bit _too_ far there. This time it's a far more conservative and simpler approach.

The essence here is to make sure that escape-by-help-or-prep is still possible, but restricts the Space-proof species from being able to do it by default.

BEFORE:

img

AFTER:
img

### CODE REVIEW

**Comment by alexkar598** [comment]
storage implant with wrench in it as vox is new meta 👍

**Comment by tigercat2000** [comment]
>leaving windows only behind indestructible objects.
Free.

Free. :eyes:

Free..... :eyes::knife:

**Comment by FreeStylaLT** [comment]
img

**Comment by EldritchSigma** [comment]
Please add some cryostorages so you can cryo if that change goes through so perma is atleast bearable... Now its pretty much impossible to escape for anyone... while its more realistic its more unfun for the people in there aswell... 

Solitary works for Vox and plasmaman... Maybe add more solitary cells instead of making perma unuseable.

**Comment by FreeStylaLT** [comment]
Solitary is far worse for Vox / Plasmamen - they have nothing to do there _at all_. Perma provides _something_ for the prisoner and the preparation needed to escape Perma with this PR is less intensive than the one needed to escape solitary.

**Comment by Citinited** [comment]
You should replace all the rwalls with windows that have girders inside them, just to troll everyone who gets perma'd 👀

**Comment by EldritchSigma** [comment]
Really please just add a cryostorage unit so some people are not forced to use a gib on caught implant/grenade... I dont mind this add all its just the lack of any cryostorage unit to get out and spectate without *suicide or ghost...

**Comment by Tayyyyyyy** [comment]
@EldritchSigma you can just request execution or borging, I think, though a cryostorage unit is probably more character friendly.

I don't know about this. It's harder to look inside as pilot and it makes perma harder to escape for everyone. I don't think permabrig should be designed to accommodate space proof species. It's a human designed station. It's on sec if they perma a vox.

**Comment by Pennwick** [comment]
How about maybe mashing all the ideas together?

You could Girder the Garden windows, meaning that prisoners always have a view to space, and then for the rest of the windows include airtight blast doors that can be shut from the Warden's office when a Spaceproof perma prisoner is brought in. That way a spaceproof prisoner can escape if security is careless or they smuggle in a wrench/crowbar, a human can escape if they're not in with a spaceproof prisoner and somehow get through space, and they can both be broken out somewhat easily with outside help.

**Comment by taukausanake** [comment]
Aren't the electrified window grilles enough to keep prisoners inside? Unless they bring in a pair of yellow gloves but then they should be more than free to escape.

Here's my two cents then. Make a new object that is basically iron bars. Use 5 plasteel to make, wrench and then weld down, function just like directional windows but are metal. Place them outside perma in space so when the windows are broken they need next to try and get past metal. Best, outside help can get them removed with tools or use jaws of life to open them up and walk through-able.

Or maybe turn the gulag into perma instead. Taking all the dangerous criminal off-station might be safer to the crew and better for the prisoners to escape

**Comment by DesolateG** [comment]
Right, this simply makes it a lot harder for non space proof species. 

No thanks.,

**Comment by alexkar598** [comment]
About the windows,follow these simple steps to escape:

Take spade in perma garden

Throw at window

Rince and repeat as you laugh at the warden for thinking 1 sec electricity will stop you

**Comment by taukausanake** [comment]
@alexkar598 I thought electrified grilles shot thunderbolts at people when they threw stuff at them? Then again I first thought that was a stupid idea. Here it might not be that dumb anymore

**Comment by granodd** [comment]
@taukausanake if you stand far enough away and throw the spade, it won't arc to you.

This PR also sort of completely eliminates any chance of escape for people who prepare to escape from perma. More specifically, the strategy of having a storage implant with a boxed space suit and a box with tools+insulated gloves+emag inside. I've not done it on live, but it is very possible to escape without much hitch from perma as any race with that setup. Space proof races have it easier, but without proper tools, fastmos will bork you if you're not careful.

**Comment by alexkar598** [comment]
Are you sure you can buy storage implant emag and suit for 20 tc?

Also only metal items arc and the spade doesn't arc if I remember

**Comment by alexkar598** [comment]
Also with the storage implant,you can put in the box an experimental and very dangerous item called a WRENCH,this very dangerous item can move the machines/vendors to allow you to escape in space!

**Comment by taukausanake** [comment]
@alexkar598 I remember people making a paper engine where they threw a sheet of paper at a grille until it arced to tesla rods. I don't think it was effective but it arced with paper if I recall.

We don't really have defines for "metal" items. It would be cool for something like that but ultimately not worth the implementation

**Comment by Citinited** [comment]
@taukausanake the `CONDUCT` flag is for metal items

**Comment by Ziiro** [comment]
Other options include:
1) Make vox and plasma men not spaceproof
2) Make firelock shutters that close at the moment of depressurization
3) Having security have the foresight to not perma species with free space suits
4) Make it plasma glass instead (much harder to break, iirc)

**Comment by Shadeykins** [comment]
>  Make vox and plasma men not spaceproof
    Make firelock shutters that close at the moment of depressurization
    Having security have the foresight to not perma species with free space suits
    Make it plasma glass instead (much harder to break, iirc)

1. Requires an entire species rebalance.
2. Firelocks don't close instantly, there's a pressure threshold (which will probably take 15-20 seconds with how big permabrig is).
3. Arbitrarily stuffing people into a 3x2 room for an hour+ because they had the misfortune of rolling traitor isn't good game design.
4. Plasma glass is resistant to fire and explosives, and severely complicates other game-modes (such as nuclear emergency) where people may need to breach into permabrig for access.

**Comment by Fox-McCloud** [comment]
Personallyyyy not a big fan of this, if only because it takes away from the epic escapes from non-Vox/Plasmamen.

**Comment by RyanSmake** [comment]
I love how you left the cables below the removed windows.

**Comment by davidchan13** [comment]
And the window behind the seed extractor isn't even powered.

**Comment by Fox-McCloud** [comment]
Yeah, we don't want this; it's punishing an entire group of traitors for the bonuses possessed by two races.

**Comment by tigercat2000** [comment]
Additionally, it's kinda gamey bullshit to put windows behind effectively immortal objects (the arcade machines) for this purpose

**Pull request closed without merging**
