### PR TITLE
Adds Greyshield Uniform

### PR DESCRIPTION
**Pull request by StreakyHaddock**
First ever Commit, never done this before, dunno if I've done this properly. My understanding is that all I had to do was cut the sprites into individual .pngs, import them into dream maker, assign them to the grey/species/uniform.dmi under the ert_uniform_s name (since that's the icon state name of the uniform) and since the blueshield uniform is already fully coded to use the grey uniform sprite sheet; I should only have to upload a sprite for the uniform to use.
If I've fucked this up miserably, i'm sorry.

Not a lot of guides on the actual mechanics of uploading and committing sprites/pull requests other than errorage's dense as fuck /tg/ spriting guide and guesswork.

greyblueshield

Getting Grey consistent from front and sides is tricky since Greys are hourglass shaped from the front but regular human paunchy from the sides.

### CODE REVIEW

**Comment by Ralta** [comment]
Woah, I think that's the first sprite I've seen that makes greys look more visually striking! I like it.

**Comment by StreakyHaddock** [comment]
I have aspirations to revamp all the grey uniforms since... their front/backs don't leave a lot of room for clear detail, but at the moment I'm just going to settle for revamping all of the missing sprites until I feel comfortable with this stupid and overly complex asset pipeline. Yes, I know it's an old game but I can still salt about it.

**Comment by Necaladun** [comment]
Yayyy!
(also do coroner uniforms for me some time plz)

**Comment by StreakyHaddock** [comment]
wat

Bugger. I've worked out how to set up a private server to test on, but I've been unable so far to give myself testing permissions. Not entirely sure what's going on here. Certainly not without vars. I'll try to work it out tomorrow but if someone has insight in the mean time that'd help.

**Comment by IK3I** [comment]
@StreakyHaddock 
To give yourself admeme powers, just copy the example config into the config folder (it's in .gitignore so no worries there) From there, open up the admins file and at the bottom on a new line enter this:
[ckey] - Hosting Provider
As an example, this is what my entry looks like:
IK3I - Hosting Provider

This will unlock everything for you, you are now the god of the server and can do anything at any time to anyone.

**Pull request closed without merging**
