### PR TITLE
Sanitize all inputs

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
**What does this PR do:**
Sanitizes all text input. Admins can no longer send arbitrary html via global narrate/pms/direct message, but they can use pencode.

**Changelog:**
:cl: Tayyyyyyy
tweak: Inputs sanitized
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
@Tayyyyyyy merge conflict

**Comment by Couls** [comment]
goodbye germs

**Comment by Ty-Omaha** [comment]
Will this remove the functionality of PMing people in **BIG BOLD RED TEXT** to get their attention?

**Comment by Tayyyyyyy** [comment]
It'll remove your ability to use html to do that. But you can still use [large] or other pencode to send formatted PMs. Or ping them with the PM chat window.

**Comment by Ty-Omaha** [comment]
We use HTML formatting a lot, such as <font color = red><i>Headset pings blah blah blah <i></font> and other in game descriptors.

There's no benefit to this because it tries to solve a problem that isn't there. Admins aren't malicious with HTML use.

**Comment by Tayyyyyyy** [comment]
We can introduce more admin pencode tags if necessary, but the reason this is needed is because if a single admin is compromised, everyone is compromised, since you can control anyone online via html/js.

**Comment by Ty-Omaha** [comment]
>if a single admin is compromised, everyone is compromised

Byond doesn't just let people access account passwords with HTML and JS

**Comment by Tayyyyyyy** [comment]
It doesn't, but remember the last time we were attacked? It was through sending everyone HTML via NTTC, which allowed them to do admin actions. Allowing people to send other people HTML means that our roles and permissions are useless. As long as anyone can get an account that can send HTML, they can make people online execute arbitrary code, which isn't really ideal if we want to be secure.

**Comment by Ty-Omaha** [comment]
> As long as anyone can get an account that can send HTML

But these people already have access and are admins, they don't need HTML to gain access

**Comment by Tayyyyyyy** [comment]
If an attack requires more advanced permissions, like headmin or maintainer permissions, then they just need to compromise a low level coder/trialmin/GA. Why have roles and permissions at all if everyone is effectively headmin/maintainer anyways?

**Comment by Ty-Omaha** [comment]
>Why have roles and permissions at all if everyone is effectively headmin/maintainer anyways?

"Why should we ban people if everyone is effectively a ban evader anyways?"

**Comment by Tayyyyyyy** [comment]
The point is that this is making it so that everyone _isn't_ a headmin/maintainer, just like how we have ways to prevent people from ban evading. I can bring back span classes for admin messages later. The risk of arbitrary JS execution just isn't worth the benefit of occasionally making text red.

**Comment by Kyep** [comment]
@Tayyyyyyy For the sake of admins not familiar with pencode, could you please do an admin forum thread explaining the new system? A brief guide? I'll announce it to the admin team. To get a head start on all the "how do we make text big/red/whatnot now" questions.

**Comment by Markolie** [comment]
I think this is causing issues with apostrophes being escaped to &#39; values in, among other things, admin private messages.

**Pull request merged**
