### PR TITLE
Engineering/Atmos beret changes

### PR DESCRIPTION
**Pull request by FreeStylaLT**
This PR does several things:
1) Adds in a new Engineering beret ( beret1 beret2 beret3 beret4 beret5)
2) Renames the current Engineering beret to "atmospherics beret", adds a new description for it
3) Adds the new Engineering beret to list of item spawns in Engineering's and CE's lockers, making them spawn there.

More berets for the beret god!

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Hate berets, but I know a lot of players like them.

:+1:

**Comment by fj45** [comment]
Eh, while more berets are great, it just doesn't look right. Why not just make the current beret (that looks great on techs, the CE and engies) spawn properly?

**Comment by ZomgPonies** [comment]
Looks fine to me. I know you've had a lot of feedback recently on art stuff fj45, but for all of us non-artists it's hard sometimes to distinguish what's 'wrong' with something. At that point, providing before/after pictures or being extensively more descriptive might be the best option.

**Comment by fj45** [comment]
Err, I'm a non-artist as well.

The best reason I can give as to why it doesn't look right is that its yellow on yellow.

**Pull request merged**
