### PR TITLE
Remove stockholm syndrome

### PR DESCRIPTION
**Pull request by PJB3005**
:cl:
del: Removed BYOND membership benefits.
/:cl:

[why]: #

Alright. Hear me out on this one.

I hate BYOND. We all do. Yes, they gave us the engine so "oh you should be grateful without BYOND SS13 wouldn't exist". But that's not the whole story.

Tom was going to actually release the BYOND code after 507. He didn't because Lummox bought it. As such you can directly relate all misery like lack of CEF, proper profiler, and a bunch of other crap, to Lummox.

Lummox is a fucking idiot. A productive idiot. 511 is already horribly unstable. You don't need to read on the BYOND forums or look at the recent changelogs for very long to see *why* he's an idiot. He clearly has no understanding of normal programming practices and every thing he has added since he became owner of BYOND is nice, but a shit hack around a larger problem.

508: exception handling? Ah yes try catch is fucking worthless.
509: color matrices? Yeah it's nice but if you're gonna fucking rework the renderer at least do it in OpenGL and give us proper shaders for the love of god.
510: planes: Yeah it's nice but they're also pretty fucking restrictive and once again there should be a better way to handle this.
...

Lummox is more catering to solving problems than actually solving the engine. Countless times new, terrible APIs have been added *alongside* the shit old ones. BYOND is fucking falling apart more than ever and fragmenting everything with terrible designs that any sane programmer would call "shit" is not the solution. You want to fix BYOND first step is to bump the fucking version number to 600 and be prepared to ruin all forms of backwards compatibility.

But no. Lummox is a productive idiot. He solves shit like lighting, planes, etc... All on top of a shitty framework, and now bugs like icon corruption and black screen exist more than ever and all we can do is hope we can provide a test case because Lummox can't be bothered to leave a DS window open on an SS13 server for an hour.

Side note: oh we'll get appearance -> icon conversion [SHOULD'VE BEEN IN 511]. Ah yes good thing it's technologically impossible to do efficiently on the server because of lack of hardware rendering. Yes it'll be better but not great and I can smell the amount of inconsistency bugs it'll have from here.

Now, all these cool fancy features are getting done, but actually important shit like open sourcing the compiler, fixing DLL calls, debuggers, client side code, threading, x64_86, cross-platform, etc... isn't getting done. These are *actual* big issues.

**BYOND is not moving in the right direction. All Lummox is doing is keep SS13, and codebases who have member benefits like TG and Paradise, stuck with their stockholm syndrome.**

If you actually believe that BYOND is improving rather than being *maintained* then you're dead fucking wrong.

Now, BYOND is a company, and Lummox is the boss. Lummox has to pay his bills and works full time. Getting in more donator money isn't gonna fucking make him work faster. **This isn't a patreon for a free program.** It's a company, and we're the fucking product. The bitches that keep clinging onto their stockholm syndrome to keep BYOND alive while getting all the negatives.

So. More money isn't gonna help anything. What does?

Oh I know.

Less money.

Vote. With. Your. Wallets.

The only fucking way we're gonna knock some sense into Lummox, is to hurt his bottom line.

Worst (best?) case scenario he fucking bankrupts, and I'll be laughing. BYOND dies and it's remake time.

Best case scenario he gets his shit together and actually fixes BYOND properly.

Both of those are positive.

What do you say. Prepared to *fucking save SS13?*

### CODE REVIEW

**Comment by Tayyyyyyy** [comment]
If you want people to "vote with your wallets", then why are you making people stop their donations by removing the donation incentive? That's not really voting if it's coerced.

So many remakes have been tried and failed that it's become a meme. BYOND dying is not good for the community.

**Comment by PJB3005** [comment]
> So many remakes have been tried and failed that it's become a meme.

Yeah because we don't *need* them and Stockholm syndrome exists.

> If you want people to "vote with your wallets", then why are you making people stop their donations by removing the donation incentive?

Did you even read the PR body?

**Comment by Tayyyyyyy** [comment]
I did read the whole PR. You may be right that Lummox is the worst person in the world, but taking away people's donation benefits is a separate thing. If your arguments are good, then people will listen to them and stop donating without the need for the stick. Some people may have purchased a year long BYOND membership and may not be expecting this.

This isn't Stockholm syndrome. There just isn't anything better right now.

**Comment by Aurorablade** [comment]
I did and while i admire your passion on the subject, the choice to remove the option for a code base would be up the headmins. You also seem to be going on a bit of a rant here on the subject. This is not the place for it.

**Comment by Aurorablade** [comment]
Escpially considering you are spamming the same PR on various codebases with the same rant.

**Comment by PJB3005** [comment]
@Aurorablade it's not spamming if multiple PRs are needed for multiple codebases, and "read my reasoning in the TG PR" isn't exactly a good PR body.

**Comment by Kyep** [comment]
Salt, salt, as far as the eye can see:


More seriously though:
- BYOND is an ancient program, with a ton of games based on it. Anything that throws out backwards compatibility at this point would probably cause huge numbers of games to forcibly exit the platform, possibly leading to a death spiral.
- Do you really think that he cares about whether BYOND donors get perks on Paradise? >90% of his revenue probably comes from ads, not memberships (it is this way for most F2P games). Thus, I highly doubt he cares about memberships on our one server. Even if he did, the most likely response would be: more aggressive ads, which is something that I at least would hate with a passion.
- If you really want to push for better updates to BYOND, have you considered taking this to reddit, or host chat, or something? I can't believe that revoking BYOND member perks on our server is the most effective way to go about this.

**Comment by PJB3005** [comment]
> Do you really think that he cares about whether BYOND donors get perks on Paradise?

Every cent counts.

> Anything that throws out backwards compatibility at this point would probably cause huge numbers of games to forcibly exit the platform, possibly leading to a death spiral.

Make BYOND ship with an old backwards compatibility client as fallback. Problem solved. You can't even compile code from a few versions back anymore.

> have you considered taking this to reddit

Oh good idea.

> or host chat

I don't have access there.

> I can't believe that revoking BYOND member perks on our server is the most effective way to go about this.

I did it on TG too.

**Comment by FalseIncarnate** [comment]
While I appreciate your enthusiasm, I must admit it seems misplaced. You are attempting to replace a leaky faucet by switching from well water to city water, IE doing nothing that will change what you view the problem to be.

If your issue is BYOND being closed source, removing member benefits won't change that. You can't hold something you don't possess hostage. Many donators support BYOND not for the perks (OOH, A LITTLE ICON NEXT TO MY NAME IN CHAT!) but for the sake of supporting what is responsible for them being able to connect to at least one game they want to play. Removing that icon isn't going to make a big difference there, you might see like 3 people stop donating because they no longer have the BYOND icon next to their names on a given server.

No one forces you to use BYOND or Dreammaker. If you have that serious of a hate-boner for it, you could always try tagging on to one of those SS13 remakes, maybe you'll get somewhere before you abandon it.

**Comment by outbools** [comment]
@Tayyyyyyy
This PR is not for players to decide. It's for staff to stop providing any benefits from BYOND Membership, because if player's choose to throw money at Lummox to get more unstable shit, he should do it for himself and not for any kind of benefits.

**Comment by outbools** [comment]
@PJB3005 yet if you look at this page http://www.byond.com/fundraising

you will find only a fuckton of weaboos and maybe a little amount of spessmen

**Comment by PJB3005** [comment]
@FalseIncarnate every. cent. counts.

@outbools  every. cent. counts.

**Comment by outbools** [comment]
@PJB3005 But you can't make a PR that will disable ads on BYOND...

**Comment by PJB3005** [comment]
You could make a custom client that uses DD and a redirect to prevent ads from popping up.

**Comment by Necaladun** [comment]
Im sure you'll write me off as a bitch with stockholm syndrome, but i have no interest in your salty crusade. 

The member benefits are barely worth calling a benefit. It's a token and im fine with that.

**Comment by TullyBurnalot** [comment]
I've got no idea why people are even giving this the time of day.

PR is getting shut down. No memes, please.

**Comment by outbools** [comment]
@Necaladun so there is almost no benfits from it and yet you reject to delete them, because... ?

**Comment by PJB3005** [comment]
> memes

Well on TG they're definitely considering it serious and I'm serious too.

You are quite literally supporting the man that is keeping this engine hostage. Even if it's not much it's something.

**Comment by Earthykiller127** [comment]
Only here in this pr will you hear the sound of bydiots gagging on Lummox's gigantic shaft from across the globe

**Comment by Citinited** [comment]
I... can't tell if this is serious.

But if it is, people don't donate to BYOND merely to get a crappy pixel by their ckey in SS13.

**Comment by PJB3005** [comment]
No, but we still need to show that we do not endorse BYOND.

**Comment by Crazylemon64** [comment]
0xk0f5w

**Comment by outbools** [comment]
@Crazylemon64 im okay with this PR getting closed, yet i fail to see the reason to repoban PJB

**Comment by Bram961** [comment]
@outbools whatever side is correct doesn't matter here. If you attempt to start your holy crusade in the ballpit you're going to get kicked out of the ballpit. This is not the place for these things this is a place to make PR's for code adjustments and improvement to the server. Not to speak out about your vendetta against another person.

**Comment by outbools** [comment]
@Bram961 that's was a code adjustment - delete old /tg/ legacy code about "treating byond like our father". I'm agree that's should be discussed by heads in their own channel though. 
Yet it was a single PR without an rude offence against any member of Paradise stuff and there is no reason to repoban person who makes you your shiny lighting system.

**Comment by Necaladun** [comment]
Making shiny lighting systems doesn't mean you get relaxed rules in regards to insulting people.
Github is also not the place to discuss polict changes like this.

**Comment by Bram961** [comment]
@outbools if we didn't want byond membership benefits which on our server is only a different OOC color and a little icon we would have opted out months ago. It's not a code adjustment as much as it is a policy change and a very untastefull one at that.

**Comment by SamHPurp** [comment]
Wait, PBJ got repo-banned for this?

**Comment by MrStonedOne** [comment]
Poorly managed communities assume that anything going against the grain is trolling.

So they then insult the assumed troll, and then when the person naturally responds with insults, they ban them for trolling and insults.

It shows the hypocrisy quite nicely.

**Pull request closed without merging**
