### PR TITLE
Removes the cooldown on spook misclicks

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Removes the 12 second cooldown if you misclick when trying to spook something as a ghost, and adds a failure message instead.

## Why It's Good For The Game

You shouldn't be punished for misclicking.

## Changelog
:cl:
tweak: Removed the 12 second cooldown if you try to spook a non-spookable object.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Why is there a misclick cool down at all?

**Review by Kyep — CHANGES_REQUESTED** [review]
Just make it not have a cooldown when you attempt to use it, and it fails. Look into revert_cast.
Keep the 2m cooldown for after successful use.

**Comment by Necaladun** [comment]
> Just make it not have a cooldown when you attempt to use it, and it fails. Look into revert_cast.
> Keep the 2m cooldown for after successful use.

This.

**Comment by AffectedArc07** [comment]
2 heads and a maintainer objecting. No one in favour. Closing.

**Pull request closed without merging**
