### PR TITLE
Taperecorder Rework

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over TG's taperecorders

Features:
- Has tapes instead of internal digital memory
 - Means that once the tape is full you can remove it and store it elsewhere instead of clearing the taperecorder's internal memory
 - Re-live your childhood and yank out ALL of the magnetic tape!*
 - Tapes are made in the autolathe just like the taperecorder itself.
- Can hack the taperecoder to disable playback/recording or trigger either (set up things like prox sensors playing a recorded message every time someone passes by!)

*experiences may vary, being a child of the 80's likely to enhance your re-lived experience.

### CODE REVIEW

**Comment by fj45** [comment]
"David Buck starts pulling the magnetic tape out of the cassette!"
"David Buck starts eating the magnetic tape...???"

**Comment by Earthdivine** [comment]
Why must you make us feel old, fox.

**Comment by Spacemanspark** [comment]
Do they still translate things?

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Of course! Same old recording/playing/transcript printing function as always.

**Comment by Spacemanspark** [comment]
:+1:

**Pull request merged**
