### PR TITLE
Make dicebag not a pillbottle subtype.

### PR DESCRIPTION
**Pull request by Adrer**
## What Does This PR Do
Make dicebag not a pillbottle subtype, instead making it a bag subtype.
Fixes: #23120
Fixes: #23142

## Why It's Good For The Game
Why is this a pillbottle subtype.

## Testing
Have a dice bag.
Empty the dice bag.
Fill the dice bag.

## Changelog
:cl:
fix: You can no longer put dice bags in medical belts.
/:cl:

### CODE REVIEW

**Comment by ATP-Engineer** [comment]
You can no longer eat all your dice whenever the DM asks you to roll for damage

**Review by Henri215 — COMMENTED** [review]
LGTM, just need to solve the conflict to check the map diffs, that are crazy right now because of it (have fun with the queue).

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Badoniondev** [comment]
As the original writer of the "But why is this a pill bottle", i consider this an epic win.

**Review by S34NW — APPROVED** [review]
Deconflict for merge

**Pull request merged**
