### PR TITLE
Makes Wallrechargers Buildable

### PR DESCRIPTION
**Pull request by reschreiter1311**
## What Does This PR Do
This Pull request makes Wallrechargers Buildable.

## Why It's Good For The Game
So that we can build Rechargers like those in Brig that are on the wall, its mainly for ease of use of rechargers so that they dont take up a whole floor tile.

## Changelog
:cl:
adds: Wallrecharger Boards
/:cl:

### CODE REVIEW

**Comment by reschreiter1311** [comment]
theres 1 thing that is not working yet: the Sprite of the Wallchargers isnt on top of a wall if the Wallrecharger is on the tile before that wall, suggestions on how to fix this would be appreciated

**Comment by Mitchs98** [comment]
Are you referring to the recharger not attaching to the wall at all, or? Because if so you could look at both how lights attach themselves to the walls as well as defib holders, possibly.

**Comment by reschreiter1311** [comment]
im currently trying a way with Sink code

**Comment by reschreiter1311** [comment]
Closing this Pull request so that i can republish it as WIP

**Pull request closed without merging**
