### PR TITLE
Modifies science and robotics objectives

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
rscadd: Science members now get compensated when they ship tech disks to centcomm.
rscdel: Science crew are no longer paid when they "max" research.
bugfix: Roboticists now get credit for making RIPLEYs and Firefighters
/:cl:

### CODE REVIEW

**Comment by Yukiona** [comment]
This makes the science balance PR so much easier to cope with :D

:+1:  x :100:

**Comment by Crazylemon64** [comment]
The idea of "Maximizing" research sounds silly to me.

> "Alright, guys, we've learned EVERYTHING! We can go home now!"

**Comment by Fox-McCloud** [comment]
I like this, as it also encourages science to *co-operate* with cargo and it makes people less concerned about "greentexting" science.

**Comment by ProperPants** [comment]
How exactly do scientists get compensated by shipping the disks? With space credits that are worth nothing outside of buying a soda?

**Comment by Fox-McCloud** [comment]
>a free shipment of materials from another station (lore-wise).

Hell no. What's up with you guys and wanting to make science even less dependent on mining.

Mai powergamezzzzz

**Comment by ProperPants** [comment]
Well, I'm just telling you that credits aren't going to encourage anyone.

**Comment by Crazylemon64** [comment]
@ProperPants Centcomm cares about the actual data, not the disks themselves - once you ship, say, materials 7 to centcomm, you will need to ship something more advanced in that category to get centcomm to care and pay you.

**Comment by ProperPants** [comment]
@Crazylemon64 I don't mind that the old objective of maxing science is gone because credits were useless before. I just don't think this disk objective is much better. No objective at all is perfectly fine - after all, engineering doesn't have an objective to set up the tesla, and security doesn't have an arrest quota or anything. Although, it doesn't harm anyone that this exists, but in a way it's still kind of a max research objective. Your goal would be to get higher tech levels to ship better disks until the point where there are no higher tech levels. So I guess nothing changes. :/ 

Something I want to just mention, I know it's ambitious and maybe impossible, is a science system that persists between rounds but progresses much more slowly to make up for it. I know persistence code does exist somewhere. It always seemed bizarre to me that research would be reset every shift. Again, obviously now is not the time for this, but I just want it to be in the backs of people's minds.

**Comment by TullyBurnalot** [comment]
@ProperPants It allows for more interaction with Cargo, though.

The reward doesn't change, the overall atmosphere does. Have to say I enjoy this change, goes in line with what Cargo is also supposed to be doing (shipping useful crap to Central).

**Comment by Crazylemon64** [comment]
@TullyBurnalot They already do!

**Comment by ProperPants** [comment]
@Crazylemon64 That's it. It's perfect then. :+1: :+1:

**Comment by mrturkeytoe** [comment]
Maybe once you get high tech levels there's a *chance* they send back something with high tech levels  for you to research? So there's a small chance you could get something like a mech teleporter or a lockboxed high tech weapon. So you have a small chance of getting meaningful rewards for sending in the disks.

**Pull request merged**
