### PR TITLE
Spaceacillin changes

### PR DESCRIPTION
**Pull request by Vivalas**
Since I think "nerf " is the wrong word here.

This change makes spaceacillin 2/3 as effective for treating infections and 1/3 as effective for treating organ infections.

Acute infections now require about 15u of spaceacillin to be treated, and acute internal infections require about 30u of spaceacillin to be treated.

Septic infections require 45u and 90u, for internal and external, respectively, but these tend to take a long time to form and are somewhat rare. 

These amounts will still completely cure any infections at the same rate, and does not increase with the number of infections in the patient.

As a tradeoff, injecting 5u of spaceacillin into a target area during organ manipulation surgery instantly and completely cleanses all organs in that area of infection, which is much more economical in the long run. Dumping alcohol in still works too, and using syringes now in alcoholic disinfection carries a 100% chance of success.

#7623 was perhaps a bit too much of a nerf to spaceacillin, and I think this is a much better tradeoff between surgery being more effective at treating infections, but spaceacillin injections still being practical to treat infections (even internal ones). I mean, if you really fuck up and someone has a septic infection to their heart, you can jam 6 syringes of spaceacillin in them, but it will probably be easier just to cut em open and inject 5u.

:cl: Vivalas
tweak: In an effort to cut costs, Nanotrasen has diluted their proprietary Spaceacillin :tm: brand super antibiotic to be somewhat less stronger, and require more than just two syringes worth to completely cure the patient of any bacterial infection. This new blend, however, is stable enough to be injected directly into internal organs, for maximum treatment potential.
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
Just to make sure you are aware:

Surgery already allows you to dump ethanol onto someone's infected organs. I do welcome the syringe though... getting a dropper in surgery and ethanol was a pain.

Now if we could do that with mitocholide too!

**Comment by Vivalas** [comment]
I noted alcohol somewhere in the OP, but the idea for spaceacillin injection seemed somewhat popular from the other PR, and also seems somewhat intuitive.

I'm going to add actual effects to necrotic limbs soon-ish and will probably add that in when I get to that.

**Comment by karmapay2win** [comment]
You would think those giant syringes penetrate all the way to internal organs.

**Comment by FlattestGuitar** [comment]
Medical procedures already take up a horrible amount of time. Following a list of things you have to do is neither challenging nor interesting for the surgeons and just waiting and looking at a black screen is not fun for the people being operated on.

As I said on your earlier PR, adding more complication to medicine seems completely unwarranted to me and I really don't understand the motivation behind this PR.

**Comment by outbools** [comment]
@FlattestGuitar that's the problems more deep and out of scope of the idea put into this PR. Please, stop listing ancient global design problems of SS13 itself as an excuse to downvote PRs, you know if someone ever start to resolve them there would be fucking shitstorm as usual.

Our version of baymed is one of those thing which makes Paradise good codebase, believe it or not. Design choice to not treat everything with cryo and patches is what makes our medbay a well populated place. Im okay with QoL changes but can't stand casual balancing and neebie babysitting. As a medbay main (same like vivalas) this balance PR is okay to me.

**Comment by Vivalas** [comment]
Medical procedures don't take horrible amounts of time currently, except for maybe surgery. And even surgery, compared to baymed surgery, is already extremely tame from the decreased delay and things like this, where surgery is irrelevant anyways because 25u of spaceacillin cleanses you completely of any and all infections.

Medbay should be more than a few patches, an injection, cryo, and a pat on the back when you get shot in the chest 5 times and were too busy engaging in virtual violence than to get it fixed before it became a septic infection. Actions have consequences and infections is one of them.

**Comment by EvadableMoxie** [comment]
> Medical procedures already take up a horrible amount of time. Following a list of things you have to do is neither challenging nor interesting for the surgeons and just waiting and looking at a black screen is not fun for the people being operated on.

> As I said on your earlier PR, adding more complication to medicine seems completely unwarranted to me and I really don't understand the motivation behind this PR.

This PR does not add an additional lists or needless complexity.  It balanced the surgical option with the medical option for the treatment of infections, which creates interesting decisions for doctors and awards system mastery.

**Comment by GunDOSMk1** [comment]
Personally, this is as someone who is a medical regular. I say that instead of nerfing chemicals. We should be making the whole process more fun, say adding more surgeries of different forms. At this current point in time, the problem with medical is the fact that it's too easy. Only when something goes wrong, say we loose cloning. Or say we lose chemistry is when medical get's challenging, and for me at least fun. 

As an end note. Referencing what @FlattestGuitar said. Adding a longer list to surgery to fix trivial things does not make it harder. And is not fun for the surgeon, nor the player currently immobile.

**Comment by Vivalas** [comment]
This PR is specifically targetted to the "medical is too easy" deal. Spaceacillin in its current state is incredibly hugbox. If you have suggestions or ideas I could incorporate into medical in general to try to peel away the hugbox, feel free to suggest them since currently I'm on a medical altering trend.

**Comment by Ralta** [comment]
As a surgery regular/main, I'm very against this. I grab three spaceacillin syringes per OR at roundstart, and that is usually enough to deal with the odd infection here and there. For patients with worse infections, or for several one after another, it runs out _very_ quickly. It's a pain to use as it is in any form of surgery (especially when you've taken the time to wash your hands, clean the blood, close the doors and _still_ get a minor infection). 

I appreciate the idea of making medical harder; I love the challenge that comes with two internal bleeds, four broken bones and a debridement but adding tedium into the mix with spaceacillin shenanigans is not the way to go, in my opinion.

**Comment by Vivalas** [comment]
Mild infection would still be around 5u treatment, after normal surgical treatment for infections or whatever else. Maybe it's just bad luck when you operate or you're doing complex long operations but I don't tend to have issues with infections during surgery when I follow procedure.

Unless all your patients have septic infections it shouldn't run out quickly since at *most* you currently would need 5u per patient for acute infections.

**Comment by Fox-McCloud** [comment]
This isn't going to really change much.

Patient's demand for spaceacillin will remain unchanged; likewise, there will still be spaceacillin in the vendors; back when it was less functional than it currently is, it didn't suddenly make doctors want to do the surgical method; they just ended up using up [i]way[/i] more of the injectable spaceacillin.

**Comment by Fox-McCloud** [comment]
After a discussion between the Heads of Staff and the Maintainers, it was decided to close the PR. Reducing the effect of spaceacillin would merely lead to doctors using up more of the supply faster in treating the same conditions, as it happened before spaceacillin was given a boost.

**Comment by Anticept** [comment]
I would, however, love to still see the direct injection method in a new PR. While I appreciate what @pinatacolata has done with surgery, I would love to see spaceacillin injections directly into septic organs be a thing since it is so readily accessible.

In time I hope we can come up with a better answer as well for encouraging people to keep surgery clean. A space cleaner dispenser like im the janitor's closet would be AMAZING.

**Comment by Vivalas** [comment]
There's no point in the injection method if spaceacillin is the answer to all your problems.

shrug

**Comment by Anticept** [comment]
You would use a hell of a lot less when applied directly to the organ.

**Pull request closed without merging**
