### PR TITLE
Buckets can be worn as hats

### PR DESCRIPTION
**Pull request by IcyV**
Allows for buckets to be worn as a hat.

Bucket hats picture
Sprite by FullOfSkittles

:cl: IcyV
add: Buckets can be worn as hats.
/:cl:

### CODE REVIEW

**Comment by CrAzYPiLoT-SS13** [comment]
How was the server even running without this?!

**Comment by Fox-McCloud** [comment]
I'd add 10 melee armor to this and also make it dump its contents on the person when equipped to the head.

**Comment by IcyV** [comment]
@Fox-McCloud Can do on the armor. I considered the dumping as well but don't really know quite how to apply that after looking around for a while. Not familiar enough with most of the procs and such to quite pull that off.

**Comment by Fox-McCloud** [comment]
```
/obj/item/weapon/reagent_containers/glass/bucket/equipped(mob/user, slot)
	..()
	if(slot == slot_head && reagents.total_volume)
		to_chat(user, "<span class='userdanger'>[src]'s contents spill all over you!</span>")
		reagents.reaction(user, TOUCH)
		reagents.clear_reagents()
```

**Comment by Fox-McCloud** [comment]
Have merge conflicts in your sprites file.

**Comment by IcyV** [comment]
I'm not actually seeing what's supposedly conflicting anymore. I updated everything just fine and they seem to match up perfectly now.

**Comment by Fox-McCloud** [comment]
In you local branch deliete icons/mob/head.dmi entirely.

download this: https://github.com/ParadiseSS13/Paradise/blob/master/icons/mob/head.dmi

and put it in the same folder...then add the bucket sprite into the newly downloaded file---then push changes. 

That *should* fix the conflicts.

**Comment by IcyV** [comment]
Exactly what I did.

**Comment by Fox-McCloud** [comment]
Hum. Not sure what's up; that's generally how everyone handles sprite conflicts. Not sure what to tell you.

**Comment by IcyV** [comment]
Well, unless someone else has a suggestion, I'm totally stumped on where to go from here without re-opening it.

**Comment by Fox-McCloud** [comment]
Given how small this PR is, it may be less work to just re-open, to be honest.

**Pull request closed without merging**
