### PR TITLE
Would the real QM stamp please stamp up?

### LINKED ISSUE #2781: QM Stamp  - wrong texture
The QM's stamp; the one from his office, is using "large_stamp-ok" instead of "large_stamp-qm" when applied to a paper.

It is using the same smaller version on a piece of paper instead of a (presumably) intended reddish circle stamp.

### LINKED ISSUE #3278: QM - Stamp
The QM -Stamp is the same like the normal granted one. We need a new icon for this.

### PR DESCRIPTION
**Pull request by Tastyfish**
Replaces the approval stamp labelled as a QM stamp with the actual QM stamp, an approved stamp, and a denied stamp. No idea why the stamp situation was what it was.
* Fixes #2781 
* Fixes #3278

### CODE REVIEW

**Comment by KasparoVy** [comment]
Lmao, 10/10 PR name
Thanks for sorting this out!

**Comment by Plotron** [comment]
Thank you.

**Comment by TheDZD** [comment]
Quality PR name.

**Comment by Spacemanspark** [comment]
I'm Stamp Shad all you other Stamp Shady's are just imitating, so won't the real Stamp Shady please stand up, please stand up?

**Comment by Tastyfish** [comment]
I couldn't help not naming it that once I typed the phrase "the real QM stamp".

**Pull request merged**
