### PR TITLE
Floor tiles, etc..

### PR DESCRIPTION
**Pull request by orelbon**
Finishes putting in some department floor tiles, kinda looked like someone got tired halfway and never finished. adds warning stripes to corresponding areas, added a few warning signs.

finishes putting blue edge tiles in the hallway under the break room, and gives the recovery room pink floor tiles, also adds a few no smoking signs 
medbay

puts in green floor tiles in virology, and fixes warning stripes
virology

rearranges radioactive signs, and puts in high voltage signs, fixes warning stripes.
engineering 

fixes warning stripes, adds missing exterior access button to airlock.
escape

 added warning stripes to toxins mixing chamber
toxins mixing

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
the way you're updating isn't being done properly, so you have previous PRs' commits in your PR, which isn't good.

Also, no pics.

**Comment by orelbon** [comment]
@Fox-McCloud those are just updates from the the upstream branch aka this, also im taking screen shots now.

**Comment by Fox-McCloud** [comment]
I know, but they shouldn't be here, it's bloating up the commits for a map change--a freshly submitted PR shouldn't have commits on it other than what's changed---if it's up for a while and merge conflicts result, because of, THEN that's understandable, but a freshly created PR should never have commits that don't relate to your newly committed changes.

You should be updating your upstream, via command line, before you make a new branch--then make changes and commit them specifically to that branch...after that, then you can push out the PR.

**Comment by orelbon** [comment]
@Fox-McCloud i use the github desktop app, from what ive seen its not very good but its simple and to the point, i use it because it easy to understand. mind telling me how to update using command line?

**Comment by Fox-McCloud** [comment]
You need to make sure you're on your master branch, first off. Click on the cog in the upper right-hand corner and click "Git Shell". YOu'll want to follow the instructions here: https://help.github.com/articles/configuring-a-remote-for-a-fork/ to set up your new upstream (which would be https://github.com/ParadiseSS13/Paradise in this case).

Once it's set, just do "git fetch upstream" then "git merge upstream/master". (https://help.github.com/articles/syncing-a-fork/)

Sync up the changes to to your own master, then you can safely create a new branch, on your master, and it'll be up to date...plus if you commit anytihng to it, it won't have all those ugly and unnecessary commits.

**Comment by orelbon** [comment]
@Fox-McCloud i seriously have no idea what they ask you to do.
gitshell

**Comment by orelbon** [comment]
I'm gonna get back to you with this tommorow, I'm going to bed.

**Comment by Fox-McCloud** [comment]
err, dunno how to more clearly explain it than what they've already outlined, particularly in the first link.

If you follow the instructions to a "T" and you specify the upstream as https://github.com/ParadiseSS13/Paradise, then things will be fine.

**Comment by orelbon** [comment]
@Fox-McCloud still have no luck, im doing everything by the guide, and it just tells me upstream is not a git repository.

**Comment by Fox-McCloud** [comment]
@orelbon 

Yes, please.

**Pull request closed without merging**
