### PR TITLE
Minor fixes/QoL changes request PR, also genetics windows

### PR DESCRIPTION
**Pull request by FreeStylaLT**
put your nitpicky map requests here and I'll do 'em

also adds a missing firelock to genetics cloning. Let's make that tourettes-filled corner a bit more visible to everyone eh

Photocopier is per request of some meganerd who wants to print things while never leaving his department cus library is too far for that lardass apparently

img
img

:cl: FreeStylaLT
add: Added windows and a missing firelock to Genetics/Cloning
tweak: Tweaked layout of Genetics slightly
add: Added photocopier to R&D.
tweak: Tweaked RD's office layout slightly
tweak: Changed access on Tcomms' external airlocks' buttons to be same as general Tcomms access
fix: fixed the airless tiles in Assembly Line's windows
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
Time to E.X.P.E.R.I-Ment on ass pics!

**Comment by FreeStylaLT** [comment]
found an even better spot, also fixed the timey-wimey-temporary thing being on the table rather than the wall, where it should be.

**Comment by monster860** [comment]
You should probably also add a window between cloning and cryo

**Comment by FreeStylaLT** [comment]
I wanted to, but wasn't exactly in favor of letting anyone with a fire extinguisher get into cloning and start cloning their dead pals themselves by smashing the windows

**Comment by monster860** [comment]
If someone is using a fire extinguisher on the window, then your problem is in the competency of the AI and/or the medical staff.

**Comment by monster860** [comment]
Besides, electrifying the grilles would fix the issue

**Comment by tigercat2000** [comment]
please do not add electrified windows to medbay

**Comment by Kevak** [comment]
While you are on the topic of minor map changes. Scooch the RD's photocopier up one tile so he can actually use his filing cabinet without having to climb into and out of his disposals

**Comment by FreeStylaLT** [comment]
post your minor tidbits that you want fixed here and I'll get around to them unless they're sec


you really don't want me to map anything relating to sec here

**Comment by monster860** [comment]
Give the RD office, CE office, and QM office privacy shutters.

Change the access on the external telecomms airlock to be the same as the rest of the telecomms doors

Fix the engi shuttle so that instead of shuttle walls, you have shuttle heaters with windows next to the engines. Basically, make it like the science shuttle.

**Comment by FreeStylaLT** [comment]
1) - I'd bet some sort of argument could arise from that shit and I don't want this to turn into a balance PR

2) - yeah sure why isn't it already

3) - I don't see why not

**Comment by Belario** [comment]
There's a bit of a drought when it comes to fax machines, they're all either in a head's office or locked away somewhere.

Put one in the library perhaps? Either in the librarian's private study or just behind the front desk.

**Comment by FreeStylaLT** [comment]
oh god no just any crewmember isn't meant to be able to send faxes, and those who can already have one in their offices

**Comment by Belario** [comment]
But muh right to butt fax :(

No reason why the librarian can't have one in his super special ERP bunker though right?
Him being emergency fax guy might see a few less people never play it is all.

**Comment by Kyep** [comment]
@Belario Faxes are intended to be restricted to important job roles (heads, magistrate, IAA, NT Rep) and should stay that way. Butt faxing isn't a right and shouldn't be.

**Comment by Magikarpet** [comment]
Only thing I could really add is to allow the bottom left genetics machine a view of the cloners somehow, as without x-ray they're generally left in the dark about cloning.

**Comment by FlattestGuitar** [comment]
@FreeStylaLT the Detective should have sec belt instead if a seclite in his locker. Where do I keep my donuts?

**Comment by FreeStylaLT** [comment]
@FlattestGuitar :gun::eyes:

**Comment by Ar3nn** [comment]
@Belario not to mention, using a fax machine is tied to some sort of access on your ID, nobody that doesn't already have access to a fax is going to be able to fax.

**Comment by FreeStylaLT** [comment]
@Kevak img

**Comment by Ar3nn** [comment]
I do like the windows into cloning. That's always been at least SOP-wise, genetics responsibility. So those are good, so they can't just claim they cant see in anymore.

**Comment by FreeStylaLT** [comment]
Did the Monster's request regarding those airlock cycling buttons.

Did the RD's office tweak as in the pic above.

Further tweaked Genetics, as shown above.

**Comment by Fox-McCloud** [comment]
That genetics change is icky.

Woudl be better if there was just a window on the same plane as the cloning scanner.

**Comment by FreeStylaLT** [comment]
Well, what if I shrunk the pen by one tile and made shrink's office bigger by one tile instead?

**Comment by Davdichan** [comment]
Requesting a cloning door button (like the ones on the medbay doors) so people can get out of cloning if forgotten. Putting windows around one of the other cloning doors wouldn't be a bad idea, they are regular walls so anyone with a welder can break into cloning about as fast as someone with an extinguisher.

**Comment by Belario** [comment]
I'll go a step further than @Davdichan and suggest opening up cloning to cyro fully.
Cut out the airlock between cyro/cloning and the two walls next to it so there's a 3 tile wide entrance?

I'm assuming the reason it's locked away is so genetics has some job integrity and the so the tide don't loot all the dead people, but the vast majority of the time that extra airlock is a real annoyance.

**Comment by Taaketa** [comment]
@FreeStylaLT There is a weird event that takes place on 3 tiles of floor in the Abandoned Robotics lab above Engineer. If you go to the far left and crowbar up the 3 floor tiles beside the door. The tile instantly looses atmosphere and goes into minus temperatures.

Also the walls on the Abandoned Robotics lab are flagged as exterior walls still after the Maintenance remap and swarmers cannot eat them. I believe it only affects the walls and windows beside the maintenance windows and possibly related to the above error.

**Comment by FreeStylaLT** [comment]
look at all these nitpicks :hamster:

**Comment by FreeStylaLT** [comment]
@Belario img like that?..

**Comment by FreeStylaLT** [comment]
also fixed @Taaketa 's issue regarding assembly window tiles, they were airless_plating for whatever reason. Fixed.

**Comment by Ar3nn** [comment]
Oh, while we're on the topic of nitpicks, the fucking newscaster in the AI sat. Please move it so it isnt blaring my ears off when someone actively posts on a news channel.

**Comment by Fox-McCloud** [comment]
Photocopier is going to be used for nothing more than ass-copies 99% of shifts =p

**Comment by Kevak** [comment]
There's a turf called "Old Note #6" In the assembly line. There are no other Old Notes. Perhaps pull some out of your arse and add them?

**Comment by Davdichan** [comment]
No cloning released button? Sigh

**Comment by Spacemanspark** [comment]
No dank memes?

**Pull request merged**
