### PR TITLE
fluff items for Birdtalon and Ssscratches

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Birdtalon: Kahkiri
```
/obj/item/device/fluff/bird_painter

Orb of Onyx
Paints anyone who uses it a very dark color.
Does weird shit to different species, but looks cool enough on Vox.
Won't spoil that here, though. One-time use.
```

Ssscratches: Lasshy-Bot
```
/obj/item/weapon/storage/backpack/fluff/ssscratches_back

CatPack
Just a backpack with a cat face. Does not meow.
```

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Something something, needs pics.

**Comment by Birdtalon** [comment]
@Fox-McCloud 

Sprites used for my item.
https://cdn.discordapp.com/attachments/303865228892831755/321279621247270916/Blueorb.png
http://puu.sh/wbzp7.png

**Comment by KasparoVy** [comment]
Birdtalon's fluff item is somewhat dependent on https://github.com/ParadiseSS13/Paradise/pull/7410. The picture from that PR can be used here as well, as that's 100% what they wanted their fluff item to do after seeing the PR.

**Comment by Necaladun** [comment]
LGTM

**Comment by Rapidvalj** [comment]
WHERES THE EMOJI

**Comment by Birdtalon** [comment]
@Fox-McCloud @Crazylemon64 @tigercat2000 Any update on this?

**Comment by KasparoVy** [comment]
Waiting on 7410 and 7410 is waiting on the end of everything.

**Comment by taukausanake** [comment]
7410 was closed. This was dependent on it and might be closed too, unless partially implemented

**Comment by tigercat2000** [comment]
@taukausanake Birdtalon was notified, I believe Flattest is talking to them.

**Comment by FlattestGuitar** [comment]
For the record, this is how it looks.

**Comment by taukausanake** [comment]
Dark Griffin confirmed

**Comment by TravellingMerchant** [comment]
Happy to have helped with more item sprites!

**Pull request merged**
