### PR TITLE
Gives Quartermaster a new identification sprite

### PR DESCRIPTION
**Pull request by ItsMarmite**
## What Does This PR Do
Gives Quartermaster a new ID sprite.

## Why It's Good For The Game
I forgot we even updated these to be unique for Command.

## Images of changes
image

## Testing
Logged in. ID changed.

## Changelog
:cl:
imageadd: New ID sprite for QM.
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
"imageadd:" instead of "del:" over your changelog.

**Review by Henri215 — APPROVED** [review]
LGTM

image

Just try moving the QM ID sprite next to these instead of leaving it at the end of the file.

**Review by Burzah — APPROVED** [review]

**Comment by ItsMarmite** [comment]
> LGTM
> 
> image
> 
> Just try moving the QM ID sprite next to these instead of leaving it at the end of the file.

That should be done now.

**Comment by ItsMarmite** [comment]
> "imageadd:" instead of "del:" over your changelog.

Woops sorry did that when tired.

**Review by Sirryan2002 — APPROVED** [review]
approved for code, requires Sprite Team approval before merge however

**Review by S34NW — APPROVED** [review]

**Pull request merged**
