### PR TITLE
Prevents vampires getting fat by drinking too much blood.

### LINKED ISSUE #881: Vampires get fat off of drinking blood from one person, makes them burst out of their clothes with nutriment change.
Messed with it in private test, this miiight be a bad idea/unintentional even though weight loss drinks exist.

### PR DESCRIPTION
**Pull request by veganzombeh**
Fixes #881, vampires should no longer get fat from drinking too much blood.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Might I suggest adding in a snowflake check for actually eating blood if you're a vamp?

Meaning--you know, like putting blood int a bottle and drinking it and stuff; should probably have a rating similar to nutriment for them.

**Comment by veganzombeh** [comment]
Should bottled blood add accumulated blood, usable blood, or just nutrition? If it adds to their accumulated blood their objectives may need to be increased a bit.

**Comment by Fox-McCloud** [comment]
Just nutrition, IMO, at least for now.

**Comment by veganzombeh** [comment]
Blood goes into the mob's vessel, rather than their reagents, so on_mob_life is never called for blood. This now makes vampires "eat" all blood that isn't their own in handle_blood.

**Pull request merged**
