### PR TITLE
No more multitool mutilation

### PR DESCRIPTION
**Pull request by Adrer**
## What Does This PR Do
Sets multitool force from 5 to 0 so it no longer does any damage on attack.

## Why It's Good For The Game
Lightly tapping someone with a small piece of electrical equipment shouldn't hurt that much. 

_Even if it is really funny to break someone's bones with it._

## Changelog
:cl:
tweak: Multitool no longer does any damage
/:cl:

### CODE REVIEW

**Comment by Wojz** [comment]
NOOOOOOOOOOOOO

**Comment by ManiacalSymphony** [comment]
Time to strike this off my to-do list.

**Comment by Carthusia** [comment]
wait...a voltage tester was able to break bones?

HOW?!

**Comment by MRgaty** [comment]
I-I think I'm crying... I will miss this thing.

**Comment by datlo** [comment]
I feel like you could change this to 1 instead and achieve the same effect while keeping the hilarity of a multitool kill theoretically possible.

**Comment by Dumbdumn5** [comment]
> I feel like you could change this to 1 instead and achieve the same effect while keeping the hilarity of a multitool kill theoretically possible.

I am absolutely in support of a man dedicated enough being able to slap a guy 200 times to kill him with a multitool.

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Comment by Dafrek** [comment]
I always thought that the multitool had a pointy metal piece on the end for pulsing wires though, shouldn't that do some damage?

**Pull request merged**
