### PR TITLE
Adds the Legit IPC-Butt QR Code Sprite

### PR DESCRIPTION
**Pull request by KasparoVy**
The sprite's been done for quite some time but it just hasn't been put in for whatever reason. An actual functioning QR code to replace the placeholder sprite representing IPC butts at the moment!

Sorry for the long long wait FoS, I don't know what that was about.

## --> Sprite by FullOfSkittles. <--

:cl:
tweak: Old placeholder IPC butt sprite replaced with the finished QR-code sprite.
/:cl:

_New IPC Butt._
newipcbuttfos

_New IPC Butt in game._
newipcbuttfos2

### CODE REVIEW

**Comment by taukausanake** [comment]
"Bite my shiny metal a"
Man, and I was actually hoping for an image. At least it works

**Comment by NTSAM** [comment]
man it took my shitty free QR reader 15 scans to actually get a message.

**Comment by Spacemanspark** [comment]
IPC QR

**Comment by taukausanake** [comment]
@NTSAM I got it first try on my QR reader on my Surface. I was surprised actually

**Comment by Regen1** [comment]
I actually identify as a QR code and I am offended

**Comment by CrAzYPiLoT-SS13** [comment]
Personalized QR code butts when?

P.S. I really want them ;_;

**Comment by Fox-McCloud** [comment]
Is this a butt PR.

**Pull request merged**
