### PR TITLE
[READY FOR TM] R&D Rework Part 2 - Death to the experimentor

### LINKED ISSUE #10774: EXPERIMENTOR fails to produce intended items due to flaw populating valid_items
**Problem Description**:
When irradiation is selected as the correct test for one of the few critical items (e.g. slime cores), the EXPERIMENTOR's code is meant to transform it into a random food, stock part, chemical grenade or kitchen item. It has been failing to do so for a couple years, producing instead the same set of booze bottles.

The cause (tested on local server) is the way valid_items is populated in experimentor.dm. valid_items gets populated first with a large number food items. When calculating the item that will be produced, it succeeds at finding one way before it gets to any non-food items in the valid_items list.

It behaves as expected by shuffling the items beforehand, e.g. replacing:

`for(var/I in typesof(/obj/item))`

with:

`for(var/I in shuffle(typesof(/obj/item)))`

Note that valid_items is a list of probability, item, probability, item, probability, item, value pairs, so it can't be shuffled directly.

Shuffling the list of items makes it not affected by changes in the order items are loaded into valid_items / changes in the number of items in those categories. The items already have a probability weighting in the EXPERIMENTOR code to control how often they appear.

**What did you expect to happen**: 
EXPERIMENTOR used to produce the intended items when irradiating valid critical items, and should still be doing so.

**What happened instead**:
EXPERIMENTOR ceased to produce the items at some point a couple years ago. The way valid_items is populated makes it sensitive to any change in the order for the global list of items, and any change in the number of food items, so it was very likely victim of changes elsewhere.

**Why is this bad/What are the consequences:**
The feature itself is supposed to provide an alternative way of boosting research by obtaining some higher level items from it. It's balanced by requiring critical items that are already high level themselves, and by the chance of actually getting higher level items having a high RNG component. Without it Research progress is more linear and involves fewer complicated / risky mechanics.

EXPERIMENTOR is already on life support due to few people ever exploring the critical items feature. The feature being broken makes it more likely to be removed altogether, despite the EXPERIMENTOR being along toxins a main risk/events source working the science department.

Antagonists have to break into the visible research room to source chemical grenades, when the EXPERIMENTOR is more accessible, though slower/harder to use for the purpose.

Currently the EXPERIMENTOR is also the main way to restart xenobiology from used grey slime cores, as the duplication feature will produce fresh grey cores from used ones. This would be lost if the EXPERIMENTOR was removed due to having broken features.

**Steps to reproduce the problem**:
1. Load slime core into experimentor (or any of the other critical items)
2. Irradiate the slime core.
3. If the experiment fails, rebuild the experimentor and try again until it rolls irradiate as the valid test for that core type.
4. Observe the item the core has been transformed to. It'll be one of a set of booze bottles, a holy water flask or a unholy water flask.
5. Eject till the EXPERIMENTOR is empty and repeat again.
6. Observe that the result is still the same few bottles.
7. Repeat on different rounds. Observe the same results.

**When did the problem start happening**:
It worked approximately two years ago, roughly around the time the feature to increase tech levels was removed from the EXPERIMENTOR. I stopped then messing with irradiating critical items with the EXPERIMENTOR as it was now producing identical uninteresting results every round.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Although EXPERIMENTOR was already nerfed when this feature was working, and this feature was balanced by requiring critical items that aren't common / are already high tech level, if it required rebalancing due to the passage of time it should happen by tweaking the probWeight formulas. A single change on an integer is enough to increase the chances of obtaining relatively useless food items.

### PR DESCRIPTION
**Pull request by AffectedArc07**
## What Does This PR Do
Part 2 of my R&D rework. This kills off the experimentor.

Closes #10774

Strange objects can now be discovered in the destructive analyser, which now goes by the name of the scientific analyser since that will be part of the upcoming rework (I want part 3 to not have any map edits - hope this is doable).

When you insert a strange object, you have the choice to discover it, or destroy it. Note that if you discover it, it will lose its origin tech values, so gamble wisely (be more wise than me on fbm for gods sake)

PR progress:

1. [x] Kill the experimentor
2. [x] Rename and repath the destructive analyser to the scientific analyser
3. [x] Make the strange objects work in the new one
4. [x] Do the map changes better (I did enough to make it compile, help is VERY MUCH wanted)

## Why It's Good For The Game
EXPERIMENTOR MUST DIE

Also its about time I do this rework

## Images of changes
See MDB

## Testing
- Tested TGUI for the analyzer post rename and repath, all still works.
- Tested destroying a strange object - works fine.
- Tested discovering a strange object - works fine.

You get this button now
image

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

Approval was split over like 40 messages of convo in coding chat, so have these shotgun snippets
image

image

## Changelog

:cl: AffectedArc07
del: Removed EXPERIMENTOR
tweak: Destructive analyser is now scientific analyser
tweak: Strange objects can now be discovered in the scientific analyser
tweak: Note that you must gamble on if you want an activated strange object or the research levels
/:cl:

### CODE REVIEW

**Comment by silverplatedelta** [comment]
Merging will 'fix' [#10774](https://github.com/ParadiseSS13/Paradise/issues/10774) as the experimentor will no longer be around to cause said issue.

**Comment by AffectedArc07** [comment]
Deconflicted after the conflict bomb from lowercasing.

Still need to apply the maps Onyx sorted for me, current maps are codermaps just so CI can run [and fail].

**Review by 1080pCat — CHANGES_REQUESTED** [review]
Map review stuff

This disposals unit here has two trunks(bin and decals removed for clarity), on delta (surprised this wasn't caught by CI?)
image


Emerald station has a removed disposals inlet here
image
And a random unrelated change here?
image
image

Box station has the ai boards removed here, for no apparent reason?
image

On cere station, the action figure here is "floating"(on other stations like emerald, they're ontop of the SSU)
image
Also lacks a rd locker D:
image

**Comment by AffectedArc07** [comment]
> Map review stuff @Onyxarias 
> 
> This disposals unit here has two trunks(bin and decals removed for clarity), on delta (surprised this wasn't caught by CI?)
> image
> 
> 
> Emerald station has a removed disposals inlet here
> image
> And a random unrelated change here?
> image
> image
> 
> Box station has the ai boards removed here, for no apparent reason?
> image
> 
> On cere station, the action figure here is "floating"(on other stations like emerald, they're ontop of the SSU)
> image
> Also lacks a rd locker D:
> image
> 
> 

Casing repath ruined me hardcore

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
## Cerestation

All of these tile appearances need fixing:

1. Change to a normal light tile.
2. Add a purple corner square.
3. Reduce all these from full purple tiles to lined purple.
4. Keep the purple squares one square away from the airlock as per the rest of the hall.
5. Ditto.

2024_12_02__17_36_57__paradise dme  cerestation dmm  - StrongDMM

Move the fire alarm to the more barren northern wall and move the light to its place; lighting falls off in the southwest corner of the hall.

2024_12_02__17_47_05__paradise dme  cerestation dmm  - StrongDMM

Both of these cameras have the same name.

2024_12_02__17_52_26__paradise dme  cerestation dmm  - StrongDMM

## Delta

Add caps to the fences.

2024_12_02__17_49_40__paradise dme  deltastation dmm  - StrongDMM

The decals here are a little confusing. I'd think the caution lines would be where the person stands, but there's also the yellow square which suggests that? Needs some tweaking to be a little clearer.

2024_12_02__17_51_11__paradise dme  deltastation dmm  - StrongDMM

## Box

"break" in the camera name should be capitalized.

2024_12_02__17_51_44__paradise dme  boxstation dmm  - StrongDMM

## Meta

Remove the varedited name from this airlock.

2024_12_02__17_56_04__paradise dme  metastation dmm  - StrongDMM

The top walls all face the hallway but are inconsistent whether they're reinforced or not, similarly with the bottom walls all facing maintenance. The north and south r-walls aren't really part of the range backstop either, so there's really no reason for them to be reinforced.

The walls adjoining xeno and toxins are fine.

2024_12_02__18_08_07__paradise dme  metastation dmm  - StrongDMM


## Emerald

Remove the varedited name from this airlock and add an autonamer.

2024_12_02__17_58_19__paradise dme  emeraldstation dmm  - StrongDMM

Could you move this camera? Having protruding wallbumps on top of a disposals chute can be annoying when trying to click.

2024_12_02__17_59_07__paradise dme  emeraldstation dmm  - StrongDMM


All of these walls only face maints but are inconsistent if whether they're reinforced or not.

2024_12_02__18_00_03__paradise dme  emeraldstation dmm  - StrongDMM

**Review by warriorstar-orion — APPROVED** [review]
Just going to get this moving, we can clean any mapping issues up later.

**Pull request merged**
