### PR TITLE
Adds windows to evidence storage

### PR DESCRIPTION
**Pull request by FreeStylaLT**
As per the request of a Sec player.
Due to the fact that a _lot_ of contraband that can be extremely valuable is going into a single room bordering maint, some additional security measures were requested to be added.

Lockers have same access as the airlock to Evidence.
Before:
img

After:
img

🆑 FreeStylaLT
tweak:Evidence Storage in Brig got secure lockers and windows
/🆑

### CODE REVIEW

**Comment by Varghh** [comment]
Evidence was too easy to break in, i love this change.

**Comment by taukausanake** [comment]
I wouldn't have the windows. You want someone to kind of have a chance of breaking in if they're an antag. The lockers being locked isn't as bad though, nothing an emag can't get through

**Comment by alexkar598** [comment]
Stop thinking every antag has emags

**Comment by Kyep** [comment]
Can you force open those lockers with EMP? 
Changelings and cult both have access to EMP.

**Comment by FreeStylaLT** [comment]
@Kyep Yeah, EMPs should be able to unlock those like any other ID-locked locker.

@taukausanake I actually do agree that one of the two things should probably go, either the lockers should have locks or the room should have windows, but not both. I'm not quite sure on which to remove, though.

**Comment by KingPhilipIII** [comment]
I imagine the windows would be most damning. Worst case scenario you're forced to steal the lockers to pry them open later but if they can see you you're already going to have to act fast before they rush in and tase you.

**Comment by Necaladun** [comment]
Yup nice, LGTM

**Comment by FreeStylaLT** [comment]
Lockers are back to being boring, windows stay. It _was_ admittedly too much security for security. Irony intended.
OP Updated
img

**Comment by taukausanake** [comment]
I was more for the removal of the windows rather than the locks. You don't want people looking inside (even if outside view range) what's going inside these lockers. I guess it is a fair balance like this though, you just got to be more quick and run when/if you get caught

**Pull request closed without merging**
