### PR TITLE
Makes RnD console use NanoUI

### PR DESCRIPTION
**Pull request by monster860**
Sooooo.... I redid the RnD ui in NanoUI.

This removes some code duplication (Protolathe material lists, I'm looking at you...), and makes the interface look purdy.

:cl: monster860
tweak: RnD console now uses NanoUI! Sweet!
bugfix: Fixes tranquillite being outside the box in the materials list. Mimes are supposed to be trapped inside a box, not outside one.
tweak: Replaces the weird unicode "x" character in some design names with the actual letter "x" so that it doesn't fuck up NanoUI
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
"Mimes are supposed to be trapped inside a box, not outside one."
:ok_hand:

**Comment by monster860** [comment]
@Fox-McCloud @TheDZD Soooo...

**Comment by PJB3005** [comment]
👌

Meanwhile on TG a UI this size would take 5 seconds to load.

**Comment by TheDZD** [comment]
Just curious as to how the RnD console benefits from using NanoUI over its current UI, considering it looks fairly nice as-is (unlike a lot of other non-nano UIs).

**Comment by monster860** [comment]
It's all in neat columns.

**Pull request merged**
