### PR TITLE
Resprites Holobadges for security

### PR DESCRIPTION
**Pull request by ATP-Engineer**
## What Does This PR Do

Resprites holobadges, ALL OF IT. It will MOST CERTAINLY look better with this.

## Why It's Good For The Game

OLD...

## Images of changes

(OUTDATED CHANGES)
image

(CURRENT CHANGES)
image

image

## Testing

Works.

## Changelog
:cl: ATP Engineer, McRamon
imageadd: Resprites holobadges
/:cl:

### CODE REVIEW

**Comment by ATP-Engineer** [comment]
Uploading new badges by McRamon.
image

**Review by Contrabang — CHANGES_REQUESTED** [review]
ties.dmi only has a forward facing sprite it seems, no other directional ones

**Comment by ATP-Engineer** [comment]
Original mob sprite is not visible from directions either

**Comment by Contrabang** [comment]
> Original mob sprite is not visible from directions either

I mean that the directions are not actually assigned in your sprites. Please test your PRs.
image

**Comment by ATP-Engineer** [comment]
Fixed, idfk why it wasnt updated and was only ONE ICON for the mob

**Review by Henri215 — APPROVED** [review]
LGTM

**Review by Contrabang — CHANGES_REQUESTED** [review]
the "armorsec" icon_state in suits.dmi needs to be updated too

**Comment by ATP-Engineer** [comment]
Going to likely close and reopen because of issues caused by conflicts, going to do that tomorrow most likely.

**Comment by ATP-Engineer** [comment]
All previous issues resolved (confident this time, unless I somehow forgot an obscurely named ties.dmi file which I am CERTAIN I DIDNT, regardless it works)

**Comment by ATP-Engineer** [comment]
Sec armor with badge is also updated now.
image

**Review by S34NW — APPROVED** [review]

**Pull request merged**
