### PR TITLE
Updates the kitchen across all maps

### PR DESCRIPTION
**Pull request by Miraviel**
## What Does This PR Do

Gives a facelift for the kitchen/chefs as I have noticed some noobtraps for newer chefs.

Couldn't make it into separate PRs, as most of them are largely dependant on each other, sorry!

### Code changes

- Moves the **milk cream** into the kitchen cabinet: Not necessary to have it out in the open, just confuses new chefs. They keep mistaking it for milk.
- Updated the "**Cooking advice from Morgan Ramslay**": Added some extra tips, reworded it, some extra formatting. Basic content is the same, make cheese bread, don't leave stuff on the floor, keep learning. I have seen new chefs actually reading this, which is heartwarming, so I tried to make it even better.
- The **kitchen cabinet** always starts with 3 bags of flour: It used to be a 1-3 random thing which is dumb. Let chefs bake stuff while botany is setting up their ultra gamer setup for warcriming.
- Adds **package wrapper** to the dinnerware vendor, removes it from the table: Vend it if you need it, otherwise don't clutter the kitchen with it. Added two as most items in the dinnerware vendor are prepared for two chefs.
- Adds "**eggbox**" to craftable recipes, made of two cardboard sheets.

### Mapping changes, all maps

- Adds **Chef Recipes**: while chefs spawn with this, manifest-hires might want to know recipes as well in the not-so-rare case of the chef being an antag.
- Removes **mint**: 1) clutter 2) only used for candy cane and gibbing fat people. You can make mint if you want to gib fat people with mystery soups.

### Mapping changes, delta

- Adds "**service SOP**" book to kitchen: It was simply missing.
- Replaces all reinforced tables with **normal tables** inside the kitchen: part of being chef is redesigning your own kitchen, having reinforced tables greatly hinder this.
- Adds a **small beaker**: Seems to be standard across all maps, was missing here.
- Removes **chef apron** from the table, **hat** from the racks: we have a clothing vendor now.
- Replaces clipboard with **paper bin**: Clipboard makes little sense gameplay-wise, you can make paper sacks with a paper bin.

### Mapping changes, meta

- Adds **service SOP and chef recipes**.
- Removes an extra **donk pocket box**.
- Swaps the food processor with a rack: The food processor was on top of a table (makes little sense), the rack's contents can be just moved around.
- Nudges reagent grinder back to 0 x, it had a strange offset.

## Why It's Good For The Game

Makes the kitchen more newbie-friendly, removes some inconsistencies, allows more cooking at roundstart, adds one more use for cardboard sheets.

## Images of changes

Cooking advice reformatting, slight rewriting:

image

Cardboard crafting:

image

Dinnerware package wrapper:

image

Cyberiad:

image

Delta:

image

Meta:

image

## Testing

Compiled all three maps, took the screenshots above.

## Changelog
:cl:
add: Eggboxes can be now crafted from cardboards.
add: Chef Recipes and service SOP books were added to the kitchen on all maps.
add: A missing small beaker was added to Delta kitchen.
tweak: Milk cream now spawns in kitchen cabinets instead of a table.
tweak: The "cooking advice from Morgan Ramslay" paper was reformatted, slightly expanded.
tweak: Kitchen cabinets now always start with 3 bags of flour, instead of 1 to 3.
tweak: Package wrappers were added to the dinnerware vendor, removed from the kitchen table.
tweak: Delta kitchen tables on the inside are no longer reinforced, meaning you can easily re-design your kitchen.
tweak: Meta kitchen's food processor and reagent grinder were moved around and slightly adjusted.
del: Removed the clipboard from delta kitchen, replaced it with a paper bin.
del: Removed chef apron and hat from Delta kitchen, you can find these in the clothing vendor.
del: Removed an extra donk pocket box from meta kitchen.
del: Removed "mint" from all kitchens, but it is still craftable by strictly chef means.
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
_Mirroring my comments here from discord:_
Having the chef spawn with a recipee book but also having one in the kitchen is weird
The books should probably be stacked and not shifted, for consistency with other books.
image
I think the mint should stay in the kitchen, its a funny reference. But yeah it shouldnt start on the table, perhaps in the contraband/premium area of one of the chef vendors?

**Comment by Miraviel** [comment]
> _Mirroring my comments here from discord:_ Having the chef spawn with a recipee book but also having one in the kitchen is weird The books should probably be stacked and not shifted, for consistency with other books. image I think the mint should stay in the kitchen, its a funny reference. But yeah it shouldnt start on the table, perhaps in the contraband/premium area of one of the chef vendors?

Need others' input on this as well, so please do comment if you agree/disagree with them.

**Comment by PacifistDalek** [comment]
I’d put the mint in as a coin vendor item, but im weird like that. May want to i offset the salt and pepper shakers, they look like they’re falling off the table! Love everything else about this tho!!

**Comment by Carthusia** [comment]
Awwww, was hopin when I saw the title that it would rework the design of Meta and Deltas kitchen, both of those kitchens are in need of a serious redesign to make them workable such as delta lacking any shutters to let the chef pick which area he wishes to focus on or tintable windows to allow for privacy like the cyberiad.

The changes here look good though, perhaps they could use 2 moulds in the vendor instead of 1, its extremely easy for someone to mix up the recipie and instantly loose their one and only coin mould.

**Comment by Miraviel** [comment]
Closing it until I'm further working on it! Thanks for the feedback

**Pull request closed without merging**
