### PR TITLE
Adds tits to Tajara

### PR DESCRIPTION
**Pull request by tigercat2000**
Six nipples. The debate is settled.

### CODE REVIEW

**Comment by Magikarpet** [comment]
REEEEEEEEEE

**Comment by Elysian-Prince** [comment]
Well, might as well. Sure.

**Comment by LittleBigKid2000** [comment]
https://www.reddit.com/r/SS13/comments/4d25zm/april_fools_prank_gone_wrong/d1nqahv?context=1

**Comment by tigercat2000** [comment]
@LittleBigKid2000 it's a changelog PR

**Comment by LittleBigKid2000** [comment]
@tigercat2000 I'm aware

**Comment by Spacemanspark** [comment]
The horror

**Pull request merged**
