### PR TITLE
Maps in Slime Consoles

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Now that the major refactor map edit PRs are merged in...

Maps in the Xenobio Slime Consoles

Also adds in the kill chamber that goes with it

Reduces monkey cube boxes from 4 to 2

img

:cl: Fox McCloud
add: Maps in the slime management console and adds in a kill chamber
tweak: Reduces Xenobio monkey box count from 4 to 2
/:cl:

### CODE REVIEW

**Comment by StaticMeow** [comment]
I quite like this, as it removes the slow, boring part of Xenobiology(that is moving all of the monkeys and slimes around), while also allowing you to better handle several slimes at once, and to more easily work towards breeding the slimes you want.

**Comment by Dinarzad** [comment]
Personally, I'm in favor of it.
for people who wanna do it the 'Ye olde way' You still can, nothin' stopping you. Just like people who preferred to do slime surgery when we first added in the processor.

For those who wanna get to the job a little faster, they have this. Options are 2 pro 4 me

**Comment by Rumiluntti** [comment]
This makes xenobio yet another, press button--->recieve stuff, kind of job for sience.
Unneeded buff for xenobio to make it even more lazy

**Comment by tigercat2000** [comment]
I mean, I still don't support the processor, let alone a magic teleport system. So. :-1:?

**Comment by Spacemanspark** [comment]
:-1: for things said above, makes it too easy.

**Comment by tigercat2000** [comment]
I believe my previous comment doesn't fully state my opinion of this.
Personally, I prefer the good old "move, feed, cut the slimes by hand" methods, and I question if giving them a teleport button within xenobio is a good idea.
However, the abductor style camera consoles are pretty much fucking awesome. Moving mobs around is pretty damn cool, and moving slimes is normally not really *dangerous* on it's own, unless you are being a dumbass. It's just time consuming. 
I don't like the kill chamber, though. It feels very cheap to just drop them in a freezing room and go "lol job done".

**Comment by TheDZD** [comment]
I'm okay with the moving slimes around, but the kill chamber just seems a bit boring.

**Comment by fludd12** [comment]
Personally, I think this revitalizes xenobio pretty well, and it actually allows you to get xenobio stuff done a bit faster than now, where you can really only get one or maybe two higher tier slimes if R&D gives you a pat on the head.

Also, kill chamber never seemed too overpowered to me when I used it, but you could leave an empty room and force players to make a kill chamber with frozen O2 if people complain.

**Comment by tigercat2000** [comment]
@fludd12 Well, I haven't used the advanced camera consoles- but I have been told:
 - no cooldown on picking up/dropping mobs
 - no limitation of not placing something down on a filled turf
so I think with the kill chamber, you could easily grab all the slimes you don't want, drop them all in as fast as possible, then wait for them to freeze and harvest anywhere from 9 to infinity corpses

**Comment by fludd12** [comment]
You can only hold a max of 4 slimes at a time, IIRC. It isn't much, but having to move back and forth to collect slimes and put them in the kill chamber slows it down slightly from "instant corpse party"

**Comment by Magikarpet** [comment]
The camera's a nice quality of life thing. Balance wise, I'm not sure it'll be too bad due to a few things like the  monkey cube count nerf being a thing that'll force xenobiologists to actually use grey baby slimes for once to make monkey cubes(which literally isnt needed currently because 4+ monkey cube boxes is more than enough to keep you going to get at least ~3-4 tier 3-4 slimes), ignoring RnD actually preforming any upgrades. 

The console also incentivises mixing up your approaches instead of being a one-size-fits-all, as not being near your slimes will make them inherrently hostile later if you wish to handle the monkies to use the muuuch more efficient upgraded monkey recylcer(Ratios on the actual slime consoles are absolutley disgusting in comparison to an upgraded monkey recycler).

**Comment by Fullofskittles** [comment]
I still don't like this. I feel it makes an already easy job that much easier while also removing a pen that quite often is needed. Not to mention the 'danger' element for inexperienced xenobiologists is toast too! Running out of space is a bigger issue and this would reduce the already limited pens to raise slimes in.

I don't think this will make people more likely to do xenobiology. We might see an increase due to new things being added but I expect it wont last. This seems like it will mostly make one of the easy parts even easier. The most boring part of xenobiology isn't that it takes time - it's that it doesn't offer much that other departments cant provide better.

If there's one thing that prevents me personally from doing xenobiology right now it's that xenobiology is not its own job slot anymore. This means having to potentially compete with every other scientist wanting to get sentience potions (as that's what 90% of them want to do) and truthfully it's a job that should at most have two people doing it. I imagine if it was made its own job slot again we'd probably see more people actually doing it.

:-1:

**Pull request closed without merging**
