### PR TITLE
A few Overdose Reagent Tweaks

### PR DESCRIPTION
**Pull request by Fox-McCloud**
- Makes all remaining reagents properly use the overdose process
- Changes the nicotine flavortext messages to be more realistic/like the effects of nicotine rather than the psychological perceptions of smoking.
- Adds in nicotine patches
 - For sale at smoking vendors; each patch has 20 units (10 actually put into your bloodstream) and costs 15 credits.
- Removes the overdose notification when you go over the limit
 - Why? A person wouldn't really be able to tell when they're actually overdosing on a chemical let alone what they were overdosing on, plus, this ruins the stealth of a few poison types when thresholds are crossed.

### CODE REVIEW

**Comment by Crazylemon64** [comment]
As it stands, the `overdosing` variable is redundant, since the only thing that determines whether you're suffering from an overdose or not is whether you're over the threshold. Should the `overdosing` variable be removed entirely?

**Comment by Fox-McCloud** [comment]
Not sure what you're referring to, exactly.

**Comment by FalseIncarnate** [comment]
I purposefully left the overdosing var in place on the off-chance we wish to introduce a chem that will overdose until fully purged (old OD) or an expansion on the overdose system that utilizes a "soft" OD that ends at the threshold and a "hard" OD that starts at a higher threshold and lasts until fully purged

**Comment by Plotron** [comment]
Silly/dumb/unrealistic messages? I liked them, though! And they're making fun of smoking, too.
Now you made it look as if smoking was *actually* good for your health!

**Comment by fludd12** [comment]
Pretty much what Plo said- I'm a huge fan of the funny smoking messages, but knowing what I've overdosed on is a little weird.

**Comment by Fox-McCloud** [comment]
I'll explain this.

So, first off, nicotine isn't inherently carcinogenic---there's been a lot of studies on this and very few of them link a strong link to cancer----there's definitely a strong link between smoking and lung cancer, but that has absolutely nothing to do with the nicotine.

Secondly, reagents should give messages fitting the reagent itself and not so much messages based on *how* you ingest them. I'm pretty sure that most of the time you take sugar, it would generate a sweet flavor, but this shouldn't be a standard message for it because that assumes only one way of ingesting it (eating).

For example, if I were to add in nicotine patches (which I plan on doing so), then a lot of the messages I removed wouldn't make any sense---while others (like the relaxed ones) would.

If it would be acceptable, I could add in a few more flavortext messages about more realistic effects while removed the last two ones that are more psychologically linked with actual smoking.

**Comment by Fox-McCloud** [comment]
updated the flavortexts so its' more indicative that it's the impacts of using the nicotine rather than smoking.

**Comment by Fox-McCloud** [comment]
went ahead and added in nicotine patches.

**Comment by Spacemanspark** [comment]
I would prefer we kept the funny messages.
:+1: on everything else, however.

**Comment by Fox-McCloud** [comment]
>Not quite sure why it really matters.

Condensed version, to explain:

if you drank saline glucose, it would taste really sweet to you---if you injected it, you wouldn't feel anything. Regardless of method though, what you *woud* feel would be the effects of saline-glucose in your body.

It wouldn't make much sense to feel rugged/lung cancer forming/your lungs dying when applying a nicotine patch, as that's associated with *method* of using the nicotine rather than actual effects of nicotine.

**Comment by Spacemanspark** [comment]
Then remove the messages about smoke forming in your lungs and leave the others. Don't remove all of them.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

I did remove those; it still gives you messages about feeling relaxed, calmed, etc--ie: actual effects of nicotine; I didn't remove every single one, just the ones that directly reference smoking.

It still gives these messages:

"You feel relaxed.", "You feel calmed.", "You feel less stressed.", "You feel more placid.", "You feel more undivided."

**Comment by Spacemanspark** [comment]
I know. But the ones that say "You feel the money you wasted" or the space cowboy one were amusing.

**Comment by Plotron** [comment]
Seeing the latest tweaks and reading @Fox-McCloud's responses, I think I can approve of this. Since so far we could only smoke nicotine, I kept thinking about messages *specific* to smoking. The changes you proposed do make sense.
The problem is the smoking-stuff part, not mere intake of nicotine, and it became apparent when you introduced nicotine patches.

I'm glad we could get rid of the Space Cowboy nonsense.

**Pull request merged**
