### PR TITLE
[READY] [SQL CHANGE] DB Based Ticket Logging

### PR DESCRIPTION
**Pull request by AffectedArc07**
Requested by @Kyep 

**What does this PR do:**
This PR introduced logging of admin tickets to the SQL backend. It will log what round it is, what ticket it is, who opened it, who closed it (If anyone), what the first message was, when it was opened, when it was closed (if at all), how long it was open for, and its final state.

image

As well as this, a web-based ticket viewer has also been included (tools/ticketwebview). This helps better represent how many tickets are being forgotten in rounds. An example of it is here: https://affectedarc07.co.uk/ParaTickets/?p=1

A small tweak that was needed for round tracking. There is now a global variable for when the server was started, which can be used for other logging procs as well.

**Changelog:**
:cl: AffectedArc07
add: Admin tickets are now logged in the DB
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
> DB Based

> Database Based

I mean it's a sound statement but I got to point it out still. I like keeping a list of redundant put-togethers like that

**Comment by AffectedArc07** [comment]
@taukausanake I dont see an issue here
You and your grammars

**Comment by Kyep** [comment]
For context, I want this so that I (and future heads of staff) can identify which admins are active, and which are not, using a SQL query like this:
SELECT count(db_ticketid) as numtickets,closing_ckey from ss13_tickets where roundstart_time > (DATE_SUB(CURDATE(), INTERVAL 3 MONTH)) group by closing_ckey;
A query like that would tell me, for each admin who processed tickets, how many tickets they handled in the last 3 months. The idea being that it helps quantify how active admins are. Not just how much they're on the server, but how active they are actually handling tickets. I know it isn't perfect, but right now we have no way to quantify this at all.

Anyway, so, that's the primary goal of this system.
It could also be used for fancier stats generation (how long does your average ticket stay open? who creates the most tickets? etc) but the primary use is identifying active v inactive admins.

The main questions I have are:
1) How much storage space does each mysql row take?
2) Assuming we get say 30 tickets/round, they're all resolved, and each round lasts 90 minutes, how much is that going to increase the DB size over a 3 month period?

**Comment by Fox-McCloud** [comment]
I definitely have concerns with how bloated this could make the DB become.

**Comment by Kyep** [comment]
@Fox-McCloud 
I have concerns about that too, which is why I want a size estimate for this.
I'd also like to plan on pruning this table regularly, effectively capping its size.

**Comment by AffectedArc07** [comment]
@Fox-McCloud I dont see this bloating out the DB in a huge way. My reason for this is the feedback table also exists, and that gets about 400 rows added to it **EVERY** round. Rows on this take up less than 1kb, so I dont see a huge issue here.

I have also spoken to this to @Kyep on discord, and he says feedback has never been pruned (to his knowledge), so I dont see the bloat issues here.

If you really want, I can add a verb to prune tickets older than 3 months or so

**Comment by Kyep** [comment]
I think we get around 150 ahelps per day (24 hours).
I doubt that 150 rows/day of that data will amount to much, size-wize, but even so, having a hook that auto-prunes this data once per round (delete everything from >4-6 months ago, say) or simply having a cron job do the same direct in mysql, should be pretty easy.
The database size problem should be easy to solve.

**Comment by AffectedArc07** [comment]
IMG_5264
This PR is now on hold

**Comment by AffectedArc07** [comment]
I will fix the conflicts when SQL change PRs can be done again

**Comment by AffectedArc07** [comment]
Deconflicted

**Comment by AffectedArc07** [comment]
Deconflicted (Again)

**Comment by Shadeykins** [comment]
> 
> 
> For context, I want this so that I (and future heads of staff) can identify which admins are active, and which are not, using a SQL query like this:
> SELECT count(db_ticketid) as numtickets,closing_ckey from ss13_tickets where roundstart_time > (DATE_SUB(CURDATE(), INTERVAL 3 MONTH)) group by closing_ckey;
> A query like that would tell me, for each admin who processed tickets, how many tickets they handled in the last 3 months. The idea being that it helps quantify how active admins are. Not just how much they're on the server, but how active they are actually handling tickets. I know it isn't perfect, but right now we have no way to quantify this at all.
> 
> Anyway, so, that's the primary goal of this system.
> It could also be used for fancier stats generation (how long does your average ticket stay open? who creates the most tickets? etc) and later making open tickets visible across rounds, but the primary use is identifying active v inactive admins. It could also be useful for, say, identifying times of day where we have a shortage of admins handling tickets, which would be helpful for ensuring adequate admin coverage on the server.

This is probably the single worst method of tracking admin activity. It unduly punishes administrators who run events, administrators who also enjoy playing occasionally, admins who investigate complex tickets over simple ones.

It genuinely doesn't take anything into account other than "did you answer the ticket and click a button." I'm all in favour of metrics, but this is a hell of a lot worse than how we used to track admin activity. If you want to see if admins are active, track playtime and don't include idle periods.

**Pull request closed without merging**
