### PR TITLE
Removes Slime Blood Slipping

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes slime's dripping actual water onto turfs.

It's frustrating when slimes slip on their own blood when they're being attacked and it's just as frustrating when fighting against a slime---either case it can generated very very one-sided fights for both sides as the slip pretty much means death.

Giving slimes slip immunity to everything (or even just water), but lube just because of this is feature would be a massive powerspike for slime people, so that's not a good way to balance this feature out.

### CODE REVIEW

**Comment by tigercat2000** [comment]
Yes, because balancing a feature out means *removing it entirely*
Do I even have to say fuck no to this? :-1:

**Comment by Fox-McCloud** [comment]
Then please explain a balanced approach to this that doesn't give an unfair advantage to slime people and doesn't make them completely frustrating to engage in while also not being frustrating to slime people themselves.

**Comment by tigercat2000** [comment]
How about not fucking touching them? They've been fine with this since they were fucking implemented, why don't you try shooting them next time?

**Comment by Fox-McCloud** [comment]
Because slimes themselves have been frustrated by slipping on their own blood as have other who have recently attacked them.

"Don't attack them with melee" is a poor justification for that frustration.

**Comment by tigercat2000** [comment]
Why just fucking recently?
First, their slip protection was removed, because "oh no that's not balanced!"
Now you want to remove their fucking water spawning because "oh no that's not balanced either!"

**Comment by Fox-McCloud** [comment]
Because players have been recently frustrated by it and have been expressing that frustration? 

Built in slip immunity *is* ridiculous when it's something that's not commonly available, let alone without downsides (unless you're a traitor or the CE).

**Comment by Regen1** [comment]
I.... Have not seen any recent outrages come up about slipping on slime blood.
Sources please

**Comment by HereticChurch** [comment]
I'll admit that I've complained a few times about it. I've not seen many other players up in arms about it though. While slipping is kinda annoying, and it's really depressing to see fights with slime people just looking like a silly slip fest after the first punch, I would like to see an attempt to see the feature balanced or fixed before being removed entirely. Slime people would lose another feature unique to them, and their 45 karma price is seeming a bit steep to their features compared to Vox already. Unfortunately I can't think of a non-snowflakey way to balance/fix this feature. Regardless, :-1: from me unless we can't come up with a way to fix it.

**Comment by Earthdivine** [comment]
I only see church complaining about this really, and this is a terrible way of trying to even it out. Who rightly cares if they get immunity to water and lube, your making it sound like those are extraordinarily prevalent on the server. If the complaint is "You have to change how you approach it!", then why homogoginze it even more? :-1:

**Comment by Spacemanspark** [comment]
:-1: I reeeeeeeeeeeeeally don't like us making the races human. They should be unique.

**Pull request closed without merging**
