### PR TITLE
Adds debug verb to save 1:1 copies of mobs to a save file

### PR DESCRIPTION
**Pull request by Iamgoofball**
# hey admins
# next time you see a player you can't examine
# use this verb and save them

### CODE REVIEW

**Comment by Crazylemon64** [comment]
Prolly like 500% less janky than that wacky JSON thing I rigged up a while ago

**Comment by Krausus** [comment]
> less janky than that wacky JSON thing I rigged up

Not quite the same. BYOND's save system is *really* aggressive, so this will pull in tons of stuff that you absolutely do not want loaded back in. Handy for debugging a snapshot of a mob, but not for persistence.

The DME is missing the new file, by the way.

**Comment by Iamgoofball** [comment]
sik

**Comment by Fox-McCloud** [comment]
@Iamgoofball plan on finish this out?

**Comment by Iamgoofball** [comment]
idk lol

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

Please do so.

**Comment by Fruerlund** [comment]
Is this something that allows saving of modified vars on some of the players items such as changed icons,  icon_state and icon_color? 

That would help with events requiring different character loadouts without having to manually edit them! 

Or did I miss the point?

**Comment by Crazylemon64** [comment]
It's been 5 days as "stale", shutting down

**Pull request closed without merging**
