### PR TITLE
Bar-Remap

### PR DESCRIPTION
**Pull request by NookBook**
**What does this PR do:**
This PR is a rework of the bar mostly. Small edits made to the kitchen and bathrooms as well as dorms. 

The Bar was changed with a gambling table, metal tiles, a stage, and connection to dorms being the major things.

The Bathrooms ended up having the cyborg recharger pushed out of the small locked room into the less-public area of the bathroom.

The kitchen had some of its items moved around.

**Images of sprite/map changes (IF APPLICABLE):**
https://media.discordapp.net/attachments/550456425072295966/611015334077399061/d087e4cb90304b2e8ab769c2e0161faa.png

**Note: This is my first mapping and PR project ever, take this with a grain of salt.**

**Changelog:**

Bar Maint Access Added:
image

Slot machines moved together, 
Dorm bathroom fixed, 
No access from bar to dorm anymore.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
I personally consider teh maintenance linking directly to the bar to be quite quintessential, as it's kinda the universal, no access meeting place.

**Comment by NookBook** [comment]
There was maint access before, though I changed it to dorm access since the only maint access allowed with the space was a single corridor that only allowed 1 person through.

**Comment by taukausanake** [comment]
Looks kind of interesting. I'm not against it. Few things I noticed though, you still have wooden plating (at least in the image) under the tables next to the kitchen as well as under some of the tables next to the bartender.

Seeing those stair turfs being used, makes me think we should make some handrails to keep people from falling (read: walking) over the wrong side of the steps but that's another thing

**Comment by NookBook** [comment]
I see that, thanks for bringing that to my attention.

**Comment by Couls** [comment]
why did you capitialize the M in Remap?

**Comment by NookBook** [comment]
OCD :)

**Comment by datlo** [comment]
Honestly I am a not a fan of this remap due to 1. the removal of the door from bar to maint 2. how it generally looks. I wish I could give advice on how to improve it but as I am also a terrible mapper I cant. I am sure you could improve this and get it merged, tho, there are some good ideas there.

**Comment by NookBook** [comment]
Will make some edits tomorrow.

**Comment by Ty-Omaha** [comment]
I like the front layout with especially with the gambling table area. 

The major thing that looks super weird is the back room.  Most of the backroom shouldn't be a 1 tile width hallway. That is too narrow and it just looks all sorts of weird. Maybe you could move the cola and vending machine that is protruding beside the clown office?

**Comment by NookBook** [comment]
I've broken this somehow and I don't know what is wrong so rest in peace.

**Comment by realtaac** [comment]
Yeah.. I'm really not a fan of this bar. I think bar is fine the way it is. this looks like a mess, there is a floating security camera. the back room is a very odd shape and needlessly big, the bar tending area is far too big. the floor should stay wood imo, why would a bar have a soda machine and a hot drink machine? it's a bar and there is a kitchen right there, why is the locker in the freezer? and why is it in such an odd space. and it just closed as i was typing this.

**Pull request closed without merging**
