### PR TITLE
Xantholne pAI Fluff

### PR DESCRIPTION
**Pull request by Xantholne**
My pAI fluff I spent a while workng on. this would be Flatty uploading but I'm super impatient from really loving it.

79fd42c3e25cb8d25cce2e9ed075c4ee
South facing Idle 

19ff30ea2683d44b072b699f15d86477
In hand, righthand is reversed

58d9ad75402cb4def7c59aa88b5cd1c7
On head sits ontop of your left shoulder.

https://i.gyazo.com/ebb105494ec6e2abdb65316d67f60ee4.mp4
All sides animations

https://i.gyazo.com/ddfd5b8646f079f58b17c15b633f392e.mp4
Rest Animation

551a6127513d91454326d136892e1c84
Pai Dead Sprite

### CODE REVIEW

**Comment by TravellingMerchant** [comment]
That is god damn adorable. Black and red is normally reserved for syndicate, but I'd be lying if I said that wasn't awesome.

**Comment by Xantholne** [comment]
I don't think there is a color restriction on pAIs considering the only other fluff is white and blue

**Comment by Fox-McCloud** [comment]
Could you please upload better pics; I need to get out my microscope to see the directional ones.

**Comment by taukausanake** [comment]
Showing your age there @Fox-McCloud, I can see them just fine.

But yeah, bigger images would be good, and what's with the mp4 out of curiosity? Why not gif?

Such a cute foxy!

**Comment by Xantholne** [comment]
Gyazo gif sorta just saves it as a mp4 instead of gif, don't ask me why. I don't know.

**Pull request merged**
