### PR TITLE
Added Medical Marijuana Packets for the Psychologist

### PR DESCRIPTION
**Pull request by PigeonLord**
I thought that the psychologist needed some sort of relaxant, and what better relaxant there is than space drugs laced cigarettes?
So i added the packet and three packets to the psych locker.
:cl: Piccione
rscadd: Added marijuana cigarette packets to the Psych's locker.
/:cl:

### CODE REVIEW

**Comment by EldritchSigma** [comment]
Isnt there a reagent named Tetrahydrocannabinol/THC which you can find in weed? Would use that instead of space drugs

**Comment by Fox-McCloud** [comment]
If you're going to add medical marijuana, yeah, use the right reagent here, please. @EldritchSigma pointed it out.

**Comment by tigercat2000** [comment]
Space Drugs are more equivalent to LSD than Marijuana.

**Comment by taukausanake** [comment]
I'd cut back on three cig packs and maybe have a few patches as an alternative to turning your lungs into cancer. That's just me though

**Comment by tigercat2000** [comment]
The THC reagent is perfect for this, mostly harmless and makes you seem like a stoner. Plus, it cures a disease, so there's actually a reason for the psych to have it. :+1:

**Pull request merged**
