### PR TITLE
Better Gas Scans (Chatbox and Colored!)

### PR DESCRIPTION
**Pull request by larentoun**
## What Does This PR Do

* Now a single atmos_scan() proc is used to analyze air and return to chat. No more duplicates of code
* Added additional info to atmos scans
* Added colors for gases in chat, so they are more dinstict now!

~~Ignore the first commit name~~

TODO:
* [x] - Choose better colors. It's defaulted to TG-colors right now and seem to not be good for our tgchat.

## Why It's Good For The Game

Pretty chatbox and colored gases!

## Images of changes

Screenshot_8
Screenshot_9

## Testing

Scanned a turf, a canister and a tank.

## Changelog
:cl:
add: Gas Scan now is in a nice box
tweak: Added additional info for gas analyzers
tweak: Color coded gas names for chat outputs
fix: Ghost's gas scans overrides ui_interact if the gas scan is enabled. In other words, you can scan canisters and portable scrubber/pumps!
/:cl:

### CODE REVIEW

**Comment by Oyu07** [comment]
The colors for Nitrogen, Plasma and Nitrous Oxide on light mode are hard to read
Oxygen on dark mode is hard to read and that the colors were clearly designed for darkmode.

**Comment by larentoun** [comment]
Need help with choosing the colors

**Review by Contrabang — COMMENTED** [review]
I recommend you get the colors from the corresponding air canisters they spawn in, and make sure to make the light mode colors darker, so that they are readable

**Comment by larentoun** [comment]
Screenshot_4
Screenshot_5

What about these?

**Comment by Contrabang** [comment]
Looks way better

**Comment by larentoun** [comment]
Screenshot_6
Screenshot_7
Also decided to add identation (if it's the right word) instead of an empty line to separate gases from misc info

Also, what about the order of the output?

**Comment by larentoun** [comment]
Updated 'Images of Changes' and ready for review then

**Comment by 1080pCat** [comment]
wowzers, i LOVE this pr. everything down to how the gases are offset slightly, adds so much readability. 10/10

**Review by S34NW — APPROVED** [review]

**Review by Burzah — COMMENTED** [review]
Sorry for the delay in getting to this. I like it, but I am concerned about the color of Carbon Dioxide with dark mode. I think it may be a little too dark? Color can come across looking different from user to user. I think something that provides a bit more contrast is warranted.

**Comment by larentoun** [comment]
I would appreciate an input about what color to use

**Comment by Burzah** [comment]
> I would appreciate an input about what color to use

Maybe something more along the lines of #CCCCCC
Just to improve the visibility on a dark background, while still staying in theme.

**Comment by larentoun** [comment]
Screenshot 2024-04-28 034222
Screenshot 2024-04-28 034240
Updated CO2.

**Review by Burzah — APPROVED** [review]

**Review by Contrabang — APPROVED** [review]
send it

**Pull request merged**
