### PR TITLE
Rebalances XRay

### PR DESCRIPTION
**Pull request by Dave-TH**
As requested, rebalances xray instead of removing it.

:cl:
balance: Tweaks xray to be more balanced.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Really makes you think

**Comment by ScratKnapp** [comment]
...so what does it do

**Comment by Kyep** [comment]
If I'm reading this right, it:

1. Changes the activation/deactivation messages for the power to less serious ones.
2. Changes the way the XRAY power works such that having it also gives you the same effect as blindness. So you can see through things... but only out to a few feet.

**Comment by Birdtalon** [comment]
```
if(stat || disabilities & BLIND || (XRAY in mutations && mind.assigned_role == "Security Officer"))	//blindness from disability or unconsciousness doesn't get better on its own
		EyeBlind(1)
```

**Comment by Dave-TH** [comment]
Someone give this man a medal. He's a genius.

**Comment by Quantum-M** [comment]
Make x-ray see the trueness of the universe, that being only numbers, code, and a somewhat crappy engine the universe runs on.

**Comment by Dave-TH** [comment]
@tigercat2000 Boo, bad pun.

**Pull request closed without merging**
