### PR TITLE
Discord linking and roundstart notifications!

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
Since the loss of CyberiadAI, we have not had a round notify system. This PR fixes that and also adds discord account linking to the game

Linking Discord Account:
zs3aptv6dh
*The bitly link links to a page on the Discord help centre of how to get IDs.*
 https://bit.ly/2AfUu40
*Ignore the error line, thats because I cancelled it*

If you press the link button when you already have an account linked, you will get this popup:
image
Pressing unlink does this:
image
It also removes the row from the DB
image

Pressing update simply re-runs the store code, but with `UPDATE` instead of `INSERT`

The notify verb will toggle between the two states when click
image
image
image

At roundstart, the code that notifies the webhook of server starting will ping everyone who has requested notify on the server. It will also set their notify status to 0, to avoid a notification every round. The BYOND link has also been updated to make it clickable inside discord.

**Extra notes**
- The commas in the numbers are just my SQL client, they are not saved like that
- This will require an SQL change if that wasnt already obvious
- This is extremely shitcode but oh well, its a notify system

**Changelog:** 
:cl: AffectedArc07
add: You can now link your discord account and BYOND account together
add: With the accounts linked, you can get roundstart notifications within discord!
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
that font in the pop up looks funky

**Comment by AffectedArc07** [comment]
@Ty-Omaha thats just my laptop font being broken, it should look fine on anyone else's client. I can test it on my main PC in about 8 hours

**Comment by AffectedArc07** [comment]
Also @variableundefined can you tack `SQL Change` to this?

**Comment by AffectedArc07** [comment]
We have a bot that does this now. I can remove the notify part if we just want discord linking to integrate with bans, but for now I feel this is due closure

**Comment by AffectedArc07** [comment]
Re-opened because the other bot doesn’t really... work...

**Comment by AffectedArc07** [comment]
Also does this count as a “Discord Bot” PR? It doesn’t change any of the stuff that void’s PR did that hanged the server on start, and I don’t think it counts, but do correct me if I am wrong

**Comment by AffectedArc07** [comment]
@v0idp thats not a discussion to be had on this PR. Take it up with a maint

**Pull request merged**
