### PR TITLE
Floor tiles and edits.

### PR DESCRIPTION
**Pull request by orelbon**
1.Finishes adding the blue and white floor tiles to arrivals that were there already, and fixes the warning stripe floor tiles on the airlocks. Also changed the little rest area in front of the security post to wooden floors and a better looking carpet.
arrivals
2. Probably fixes the messed up floor tiles in virology.
3. Added an AI status monitor to engineering, and tool closets so that engineers can put away tools somewhere instead of leaving them laying arround. 
engineering

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
conflictssss

**Comment by orelbon** [comment]
Can you even fix map conflicts?

**Comment by tigercat2000** [comment]
depends on how big the conflict is
one line maybe you could fix it

In general though it's easier to just reset your branch and redo the work

**Comment by orelbon** [comment]
alright

**Pull request closed without merging**
