### PR TITLE
Fixes exploding backpacks

### PR DESCRIPTION
**Pull request by chopchop1614**
Fixes issue with putting the X4 (issue #5140) into the backpack starts the activation. Thanks to CrazyLemon for helping me out with this.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
What exactly was the problem here?

Does this also fix the exploding labcoats? I've heard those were an issue.

**Comment by Earthdivine** [comment]
@FlattestGuitar 

I believe the problem is you cant put X-4 into your backpack because it will attach to the bag rather then being put inside it (wasting the bag and everything in it), meaning you need to have a hand open to open the bag menu then click a slot in there to insert the X-4.

**Comment by FlattestGuitar** [comment]
Yes, that's how you normally go around it.

But why does making the proc return the parent's value fix this?

**Comment by chopchop1614** [comment]
That is a great question. Its because the parent code has a return value of one where the backpack code has a default return code of 0 (because there was no return at all). By returning and calling on the parent value, you are returning the parents value of one. Which is returned to the click.dm file where it is called.

**Comment by KingPhilipIII** [comment]
What if I want to actually plant X4 on my bag though?

**Comment by FlattestGuitar** [comment]
Strapping a directional charge to your forehead never felt so *refreshing!*

**Pull request merged**
