### PR TITLE
New laser carbine icons

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Credit to @Draconic-saint, also known as Jedr.

👌 

No cl, because this isn't there for players.

### CODE REVIEW

**Comment by Spartan6** [comment]
I still don't like the fact it leaves cartridges. Maybe make it sorta more like the Mass Effect 2-3 guns, where essentially you put in a magazine and it pops out a spent one at the end.

**Comment by Spacemanspark** [comment]
:+1:

**Comment by DesolateG** [comment]
@Spartan6 Thermals clips. They're removable heat sinks.

**Comment by Draconic-saint** [comment]
I like what you did with the sprites 👍

**Comment by Fox-McCloud** [comment]
The sprite is *ok*. It's better than the last one though, for sure.

**Pull request merged**
