### PR TITLE
Updates Fake Disintegrate and Spell Icons

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates spell icons so they're more consistent/some aren't missing.

img

Updates the fake Ei' nath spell to be more consistent with the actual Ei Nath. It will now make your hand look like it's on fire, just like the actual Ei Nath---likewise, when you hit someone with it, it will play the spell and the gib sounds as well as generate sparks----obviously doesn't do any damage or have any real impact.

Other
- Removes old+ugly+unused spell icons

:cl: Fox McCloud
rcsadd: Updates Fake Ei Nath spell to behave more like the actual Ei Nath, complete with fake sounds and animations
tweak: Updates some spell icons with better/higher quality icons
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Wicked! Going to be fun fooling about with the fake ei'nath now.

**Comment by Crazylemon64** [comment]
Your PR got me thinking of wizard spells, so I made the fireball something readied in-hand before firing, so you don't accidentally self-immolate as much.

**Comment by Tastyfish** [comment]
So there still isn't a timestop icon, correct?

**Comment by Tastyfish** [comment]
Here's an icon I quickly threw together time stop

**Comment by Gummin** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
https://github.com/tgstation/-tg-station/pull/15382

Adds the time icon.

**Pull request merged**
