### PR TITLE
Improves pet collars

### PR DESCRIPTION
**Pull request by Tastyfish**
##### Collars have been improved.
- Any domestic mob, including pets and livestock, can now wear collars, not just sub-types of `/mob/living/simple_animal/pet`, which now just has the code to make the collar render on those. Being able to put a collar on an animal is controlled by a var for `simple_animal` called `can_collar`. 
- Collars now act as death alarms because why not.
 - _**Ian's Death Alarm** says, "Ian has been vandalized in Head of Personnel's Office!"_
- You can now also clip ID's to collars, which will be checked on door bumping. Might end up needing to be SoP for not going crazy with that, we'll see.
- Some missing collar sprites for cats and dogs were fixed.
- You can now add and remove collars via the click-drag inventory screens.

##### Also...
- This PR also brings the click-drag screens for all mobs into visual parity with the human one because I wasn't about to change one of them when they were that ugly.

:cl:
rscadd: Pet collars now act as death alarms and can have ID's attached to them.
tweak: All domestic animals can now wear collars.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Neat idea.

Unfortunately, I have a feeling this is going to result in a lot of metagrudging and "validhunting" pets who patrol maintenance or players who become a pet only to "conveniently" sniff out their previous dead body.

**Comment by LiquidNightfury** [comment]
Couldn't people who were willing to recover their body that way use posibrains or maintenance drones? Respawn methods aren't exactly difficult to access on Para. It's just a matter of ruling it properly.

**Comment by Tastyfish** [comment]
@Fox-McCloud Possibly, but doing that requires that a human player go out of their way to give the animal a collar with maintenance access, and for the person to be willing to metagame that much. It of course wouldn't even be advantageous to do that, since they've already disconnected themselves from their old player's mob, preventing cloning from ever taking place so it would only serve to grudge the antag, which, well people can already do via posibrains, drones, pAI's etc, as LiquidNightfury stated. At the very least, we have NPC job bans for a reason.

**Comment by tigercat2000** [comment]
@Fox-McCloud metagaming to that level is bannable :wink:

**Comment by tigercat2000** [comment]
@Tastyfish ya didn't make it so humans with collars had access :P

**Comment by Tastyfish** [comment]
@tigercat2000 I'm not about to snowflake in accessories granting access :p. You can hold them in your hand for that though.

**Comment by tigercat2000** [comment]
@Tastyfish The entire get_access() system is currently built around snowflaking shit in, which will be a problem eventually, but for now, one more condition won't hurt. There's not exactly an easy way to make it work "cleanly", without something like /vg/'s brand new event system.

**Pull request merged**
