### PR TITLE
Hair Request

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This was a request.

No opinion. On more hairstyle doesn't hurt

img

:cl: Fox McCloud
add: Adds in a new hairstyle
/:cl:

### CODE REVIEW

**Comment by AceMcLazer** [comment]
:+1: I've also been working on one I may submit for review to you, Fox. If you're down for even more

**Comment by QuinnAggeler** [comment]
Can you give us a screen of it on a person?

**Comment by Dinarzad** [comment]
Oh sweet. I know that hair style and I am kinda happy to see it swing in, if it's the one I think it is.
I will never not upvote cosmetic options.

**Comment by NTSAM** [comment]
pretty 👍

**Comment by TheDZD** [comment]
Conflicts

**Comment by QuinnAggeler** [comment]
I'm guessing due to the recent IPC thing, since that changed a bunch of appearance and dmi stuff.

**Comment by KasparoVy** [comment]
Yeah, that'd be the cause, sorry

**Comment by Fox-McCloud** [comment]
conflicts fixed.

**Comment by Fox-McCloud** [comment]
conflicts fixed 2.0

**Pull request merged**
