### PR TITLE
Makes Fires Much Cheaper

### PR DESCRIPTION
**Pull request by Fox-McCloud**
##### Better Performing Fires

Fires are incredibly expensive on our server, but not because of LINDA; turns out it's the lighting system.

This cuts the cost of fires significantly by eliminating the constant light range changing values.

### CODE REVIEW

**Comment by Gummin** [comment]
Anything that makes the game run better gets my vote. :+1:x:100:x:8ball*

**Comment by Regen1** [comment]
Leave colored lighting from fire
I have not noticed any significant lag on the server because of fires in a good while, and it usually burns out within 5 minutes

Having colored fire based on how hot it is, is a lot of the charm and fun you get from plasma

**Comment by FalseIncarnate** [comment]
:+1: to reducing lag by removing the light range shifting

:-1: to removing colored fire (and not because I initially implemented it back in ZAS), because it is a nice and also somewhat useful aesthetic feature. I mean, fire is gonna mess you up pretty bad either way, but seeing a hot pink fire is a good sign that you need to get off-station fast.

**Comment by Fox-McCloud** [comment]
Colored fire is still a thing--that wasn't touched; it's only the <b>light</b> emitted by the fire that has been removed.

**Comment by Regen1** [comment]
I still like the intensity of the first one, I like that fire gives such an aesthetic feeling, and I think we should keep it

**Comment by taukausanake** [comment]
I agree with Regan, it just looks nicer with the burning light. It's just not the burning inferno that it's meant to be without it

**Comment by FalseIncarnate** [comment]
I meant colored light from fire (and correctly said so a couple times), but forgot the world "light" in a spot or two. I was tired while typing.

**Comment by tigercat2000** [comment]
Colored light is very difficult to notice under orange fires. Raise the temperature to blue and compare between colored and uncoloured light, there is a big difference.

**Comment by Vivalas** [comment]
I remember playing on Bay as a toxins researcher and watching the fire glow so insanely bright, and cast the entire room in red light, to the point where I think the walls would burn out and I would die.

(They did.)

Seriously though colored lighting from fires is one of those things that you don't notice how cool it is until you play with it for the first time.

Also I must add that the full charm of colored fire is not appreciated from a closed room where all the colored lighting is on the same tiles as the fire that is covering the entire room.

Try observing fire from behind a window and take screenshots and you will see the difference.

Also fires are very rare and usually short-lived, no point in making the most interesting part of being an atmos tech less interesting.

**Comment by Robertha89** [comment]
Fires can still grow fairly big, keeping them resources intensive because of looks is kinda counter productive. 
:+1: Colored lights, while neat, brings more issues, like the light turning into a solid white, or it being more expensive then it could be.

**Comment by Yukiona** [comment]
For a 8600% (ish) increase in performance, for fires to not have a colour or to give things a slight hue change. Personally, I think the benefits outweigh the cost. :+1:

**Comment by Spacemanspark** [comment]
I prefer the first picture's aesthetic, but eh, if it really helps the performance, and it's not terribly noticeable, then sure.

**Comment by tigercat2000** [comment]
A considerable increase in performance can be gained by making the light range changes and color updates only happen once every 4 ticks. I would support trying that, over nuking all colored fires just for performance.

**Comment by TheDZD** [comment]
The hastebin links seem to have expired by the way.

**Pull request merged**
