### PR TITLE
Sleeper Changes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Another road paving PR :wink: 

Makes some adjustments to sleepers, largely to pave the way for future PRs and making them far more mapper friendly. The biggest change in this PR are these changes:

- Removal of sleeper consoles
 - Just click on the sleeper itself now
- Addition of Silver Sulfadiazine to sleepers
- Addition of syndicate sleepers
 - user can inject chems into themselves while inside it
- 2 more cryopods to cryodorms
 - Removed the cryopod tubing to make this possible, which was unsightly and non-functional

img1
img2
img3

:cl: Fox McCloud
tweak: Sleepers no longer require a console to build, only the sleeper itself
tweak: Clicking on the sleeper brings up the menu that was previously brought up for the console
add: Adds in syndicate sleepers--these sleepers are not only syndie themed but also allow the user to inject chems into themselves while inside the sleepers
tweak: Sleepers can now inject silver sulfadiazine
tweak: removes cryofeeds from cryodorms and adds in 2 more cryopods
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
My only issue is that I think sleepers look kinda bland without the console part.

**Comment by Magikarpet** [comment]
Fixes the ghetto surgery room's sleeper, woop woop!

**Comment by EpicCharger** [comment]
Silver Sulf in the sleepers? Praise be! Will the sleeper sprite be changed a bit without the console part? As in, changed from what it looks like now without the console. I personally like the looks of the sleepers as is, but it would save some time for clicking functions.

**Comment by Fox-McCloud** [comment]
@EpicCharger 

Sleepers still look the same, though a few of them have different oriented directions now--for example, the sleepers on the shuttle are flipped so the flat part is up against the walls.

That's another advance is that we can have north and south facing sleepers now, where...previously we couldn't, because of the consoles.

The base sleeper looks the same, the sydnipod looks similar, but is black and red.

**Comment by Davdichan** [comment]
Are the body scanners going to receive similar treatment?

**Comment by Dinarzad** [comment]
Awwww shit, Silver sulfa in sleepers an those fuckin consoles removed.
I have wanted those consoles gone for ages, many yesses.

**Comment by EpicCharger** [comment]
@Fox-McCloud  There is already a sprite for north and south sleepers, right? Seen them on that one gateway mission of the crashed ship. Never looked at them closely, going to assume they were totally useless due to the lack of a console then?

**Comment by FreeStylaLT** [comment]
Can we rotate Sleepers 360 now and have them function properly with this PR?

**Comment by Fox-McCloud** [comment]
>Are the body scanners going to receive similar treatment?

Eventually I plan on doing so, yes, but won't be doing that in this PR.

**Comment by LittleBigKid2000** [comment]
I prefer having the console, but it might just be because I'm used to having one.

**Comment by Davdichan** [comment]
I can honestly say single tile sleepers are lovely. 4 directions they can be faced, can be lined against a wall without negative effect, If you can push a person into the sleeper you can instantly use it without having to maneuver to the console, the amount of fights that have started because I had to disarm shove an idiot out of my way to properly heal a patient in crit is better left uncounted.

 Imagine how much nice the escape shuttle would be without those damn consoles in the way of the medbay, people who need healing can actually APPROACH the damn sleeper without someone needing to tackle the idiot standing in the middle blocking the only path. 

Hell you could put 4 sleepers on the bottom wall, move the roller bed and table of medkits to either side of the door and you'd still have more net useable space in the emergency medical area.

**Comment by monster860** [comment]
Pics or it didn't happen

**Comment by TullyBurnalot** [comment]
:100: :clap:

**Comment by Fox-McCloud** [comment]
conflicted with my own PR. GG WP @Fox-McCloud

**Comment by monster860** [comment]
:100: :clap:

**Comment by Fox-McCloud** [comment]
conflicts resolved, pics added

**Pull request merged**
