### PR TITLE
Colored Computers.... WIP

### PR DESCRIPTION
**Pull request by Chakirski**
PR on vacation leave. Something about polls...

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Not a fan, those sprites look really low res and icky compared to current ones.

**Comment by IcyV** [comment]
>Not a fan, those sprites look really low res and icky compared to current ones.

Pretty much that. I like the idea of colored computers but not so much the execution with these sprites.

**Comment by tigercat2000** [comment]
With the above, don't really like the look of the sprites, don't even _really_ support colored frames.

**Comment by Chakirski** [comment]
I see that they are infact, 1x1 pixel smaller than the original, i'll update tomorrow and see how they look then.

**Comment by Chakirski** [comment]
Alright, new pics. Bigger, badder, hopefully not worse.

If you think the bigger keyboards are 'ehhh', i'm thinking of redoing them all together.

**Comment by FreeStylaLT** [comment]
from flatscreens to CRT thickness

space stations sure are backwards

**Comment by IcyV** [comment]
Still not entirely feeling them. The frames feel a bit too thick, especially with them being on stands. The panels also feel like way too much and don't blend with the computer overall. e.g. The RD computer looks like a rainbow keyboard.

If anything a light recoloring of the currently existing sprites might be the best way to go.

**Comment by Chakirski** [comment]
I must ask, would you like the added wires at the bottom of the frame in the current computer sprites? It's more than just empty space.

**Comment by PJB3005** [comment]
I think they could look good if the colours are a lot more subtle.

**Comment by KasparoVy** [comment]
I think it looks dope. Interested in seeing how this ends up.

**Comment by Chakirski** [comment]
I'm going to open up a poll for current computers vs colored current computers vs colored and thick computers.

I liked the extra thickness, just because it gave it depth and room for extra detail.

**Comment by IcyV** [comment]
The wires ain't too bad. A touch repetitive and numerous though.

I think my main problem with the thicker frame is that it makes it a very forced perspective. It feels like it's sticking straight out and that you'd have to be a tile below it to make any sense in using it. Current sprites are a bit more ambiguous in that regard given how they're more flat. 

A better frame isn't a bad idea by any means, I just think this one takes it a notch too far and doesn't quite fit.

**Comment by Chakirski** [comment]
http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=8212

**Comment by Chakirski** [comment]
So... what if I made directional computers?

**Comment by tigercat2000** [comment]
I think our computer sprites are fine tbh

**Pull request closed without merging**
