### PR TITLE
Fixes outstanding Metastation issues

### PR DESCRIPTION
**Pull request by SamHPurp**
Another requested PR:

Fixes: #7938
Closes: #7573 (I fixed in a past PR)
Fixes: #8518
Fixes: #8317
Fixes: #8553
Fixes: #8311
Adds missing containment door to the engine room.
Uses correct signage for Medbay

:cl: Purpose
fix: Metastation: Escape shuttle windows are now breakable.
fix: Metastation: Powernet problems resolved in Medbay.
fix: Metastation: Removes magical flying camera.
add: Metastation: Adds a component analyser to Robotics.
add: Metastation: Fungus now spawns in certain parts of maintenance.
fix: Admin's move-to-cryo buttton now works on Metastation too.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
As per @FreeStylaLT 's request, there is now fungus spawning in parts of maintenance. Typically around walls that might get wet higher than average (walls adjacent to sinks, etc)

**Comment by KasparoVy** [comment]
Are the escape shuttle windows now also deconsctructable @SamHPurp? Another quirk I've just noticed in a meta test round was that they couldn't be deconstructed with tools as standard (or Boxstation shuttle) windows can.

**Comment by SamHPurp** [comment]
@KasparoVy yep

**Comment by KasparoVy** [comment]
Hallelujah

**Comment by FalseIncarnate** [comment]
Map conflicts

**Pull request closed without merging**
