### PR TITLE
Removes ballgag and assless chaps

### PR DESCRIPTION
**Pull request by TDSSS**
**What does this PR do:**
Was requested in coder_chat on discord, removing both the ball gag and the assless chaps from the code, the map and the icon files.

**Changelog:**
:cl: 
del: Removed ballgag and assless chaps
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
The assless chaps, perhaps, though keep in mind they're a fluff item.
The ball-gag, absolutely not. Why? Just because "it's a ballgag that's lewd reee!"?

**Comment by Birdtalon** [comment]
Fetish content.

**Comment by Birdtalon** [comment]
Also. Farts have to be removed but a ballgag is fine?

**Comment by tigercat2000** [comment]
`Fetish content.`
What in the world makes you think that your witty two word comment is even a slight justification for this PR? Tajaran and Vulpkanin are fetish content. The captain's whip is fetish content. Anything I don't like is *someone's* fetish. 

When I think of the ballgag, the thing it reminds me of is pulp fiction and the gimp. Sure, you can call that was 'fetish content', but there's two issues with that. First- it was in a rated R movie, not NC-17. Secondly, the way it was used in the plot was for a proper "JESUS WHAT THE FUCK" reaction, which is something that SS13 also takes leverage of all the time. That's the point of it existing, and especially being in security's walls. It exists in tandem with the fluffy cuffs, which aren't being approved for removal for some reason?

If people are *using it* for lewd reasons, we *ban them*. That's how the rules work. It's stupid to remove it from the codebase.

`Also. Farts have to be removed but a ballgag is fine?`
Oh no, I have different opinions on entirely different subjects! Should I even bother pointing out both the false equivalency and ad hominem fallacies in this one comment, not to mention the fact that you're only posting it to be an asshole?

**Comment by TDSSS** [comment]
🤷‍♂️ 
Ansari said:

> Request supported by Neca, Fox and I:
>Remove ball gags & assless chap from sprite, code and map.

>Don't include fluffy handcuffs

Take it up with them.

**Comment by Birdtalon** [comment]
I really fail to see how you managed to turn comparing your opinions in this subject and farts into ad hominem. 12 words I wrote and not a single one insulted your character.

Type "ballgag" into google and the top five results are all referring to BDSM in some shape or form. A fetish. I'm really not sure why you think this is some kind of personal attack on you?

And I'm not posting it to be an asshole. I'm posting it because I find it silly that childish humour like farts is slated for removal whereas something pretty much entirely used for BDSM is fine.

**Comment by tigercat2000** [comment]
@Birdtalon I'm not sure you're actually using `ridicule` there right, because `the subjection of someone or something to contemptuous and dismissive language or behavior.` is generally also `being an asshole`

`I'm really not sure why you think this is some kind of personal attack on you?`
`I really fail to see how you managed to turn comparing your opinions in this subject and farts into ad hominem. 12 words I wrote and not a single one insulted your character.`

You're right; I named the wrong fallacy and perhaps assumed a bit too much hostility from you then is actually present in your comment. It would be more appropriate to say that you're contrasting two unlike things as a way to attack/discredit my opinion. I mean, I don't see any other reason why you would bring this up? Is it a legitimate question, as to why I think farts are stupid but ballgags not stupid? If so, the short answer is simply... one is bathroom humor, the other has a lot of nuanced meanings and I find the type of humor it could be considered to portray more entertaining, though I think the serious aspects of horror that it can be associated with are a better reason to keep it than just "lol".

**Comment by Birdtalon** [comment]
@tigercat2000 The difference here is; as you state in your post:

` It would be more appropriate to say that you're contrasting two unlike things as a way to attack/discredit my opinion.`

Attacking and/or discrediting your opinion is completely different to attacking **you**.  I would have said the same thing to anyone who shared that opinion, however you were the person who posted the first comment and so of course it's in reaction to your post.

https://www.vocabulary.com/dictionary/ridicule
```
When you ridicule someone, you mock or make fun of them.
They become the object of your ridicule or mockery.
Your bad behavior might bring ridicule on your parents, who raised you to know better.
```

Sure, I'll give you that it makes me an asshole, but it still doesn't make it an attack on you personally.

In my opinion the ballgag is first and foremost a BDSM toy and contributes to a "wink wink nudge nudge" culture which I strongly dislike. You say that the fart removal and this are two completely different things, however they are juxtaposed by the fact that there are two simultaneous removal PRs up for these two things.

I still believe and will continue to do so that this **video game** shouldn't contain fetish content. For the record I don't believe Vulpkanin and Tajaran are fetish content although they can be used in that respect. Vulpkanin and Tajaran have plenty more merits than the ballgag has.

The article on wikipedia even has (BDSM) in its title https://en.wikipedia.org/wiki/Gag_(BDSM) and while you may argue that it can be used in other contexts that doesn't change the fact that it is a BDSM toy.

My argument is not coming from a "this game has kids in it" standpoint but from a "I don't want fetishes in the game" one. There are servers on which this kind of content is acceptable and more power to them. However, the server I play on and the community I am part of is Paradise and therefore that is where my opinion lies.

I also think that potty humour is a lot more acceptable than things associated with BDSM.

**Comment by Pennwick** [comment]
I think its important to consider the source of these two PRs. The Fart removal PR came from 'Based on a discussion over the last few weeks on the admin forums' while this one came from 'Was requested in coder_chat on discord'. I get the impression that maybe someone tried to piggyback off the other idea to remove something they didn't like.

And wanting to remove something you feel doesn't fit the tone of the game or 'Mid-Rp' is fine just because one or several people on discord don't like it kind of feels like its jumping the gun. I at least hope the admin thread was a bit more thought out and debated. As this PR isn't related to a bug, ballance issue, or refactor I'm not sure coder_chat and github are the place to hash this out.

My personal opinion is I see these things so rarely, and usually for absurd purposes that its never really sexual, always a joke. If you're getting upset by a rubber bit and some butts in a game where people can be thrown through a trash grinder, get xeno face-hugged, or decapitated via guillotine, then you're being somewhat selectively sensitive. I'd survive if the items were removed but if this is used for a launching point to remove pink fluffy cuffs, which just as much are explicitly fetish gear, you'll have to pry them for my cold dead hands.

**Comment by AffectedArc07** [comment]
Ok time to throw my stance on this:
Why are these even in the code still, much less available on the regular station. I get this on something like Citadel or Vorestation, but here?

Going back to what birdtalon said, the Wikipedia page for this literally has BDSM in the title, and last time I checked this is something that we don’t allow here, though correct me if I am wrong. 

Also, I believe one of these exists in the admin level, so make sure that’s removed (in the torture room at the admin base). 

Also if anyone tries to defend this by saying it’s useful for executions, we have muzzles for that. They aren’t entirely lewd and are actually something that would be used to shut someone up.

**Comment by tigercat2000** [comment]
`Wikipedia page for this literally has BDSM in the title`
`The article on wikipedia even has (BDSM) in its title `
Those are used for disambiguation, kek. It's not even an article on specifically ball-gags, it's about all the different kinds of gags usually used in BDSM. 
Here's an article that uses a ballgag as well, actually, without the `_(BDSM)` disambiguation in the title.
https://en.wikipedia.org/wiki/Gag
Your point means literally nothing. 
Should I point out that `Tape Gag` is also on that page? 

` I at least hope the admin thread was a bit more thought out and debated.`
Nope, came as a surprise from the heads and maints.

`last time I checked this is something that we don’t allow here`
We don't allow ERP or explicit sexual themes. It's based on what the players actually do, not anything else. The ball-gag alone doesn't violate our rules, what people do with it may. The argument mostly presented here is that players only end up using it to violate our rules and it's therefore redundant compared to just using the regular medical muzzle (also on that BDSM page, because people use a ton of things for the fetish, lmao)

**Comment by AffectedArc07** [comment]
>The ball-gag alone doesn't violate our rules, what people do with it may.

What the fuck can you even do with the ball gag that isnt lewd in some form of way

**Comment by Ziiro** [comment]
Duct tape serves the same purpose as the ballgag, without the baggage. Just use duct tape.

>Make it extra humiliating when officer bungles walks around the brig with his taser out by swiping it from the hidden security room and leaving him bound up with it and the fuzzy cuffs

A ballgag and fuzzy cuffs for "humiliation purposes" is literally something people get off to. I would ahelp that I am being subjected to someone else's fetish if this happened to me.

A ballgag is **inherently** fetish material, unlike other types of gags. Considering the administration's harsh stance on ERP or explicit sexual themes, I'm shocked this has lasted as long as it has.

**Comment by ScratKnapp** [comment]
What's up with various things being declared a nono and worthy of purging as of late

**Comment by tigercat2000** [comment]
> A ballgag and fuzzy cuffs for "humiliation purposes" is literally something people get off to. I would ahelp that I am being subjected to someone else's fetish if this happened to me.

See... I said a few times "maybe we should try getting our minds out of the goddamn gutter", which sounds silly of me to say, but I'd argue it's exactly the problem with what you're saying here. Humiliation isn't inherently sexual, despite the fact that it's apparently quite the common fetish to have now. Consider kids pantsing each other, or stealing their clothes while they're in the gym shower. These are also instances of 'humiliation' without the sexual connotations that you associate to it. Perhaps this is a bit less arguable when dealing with the ballgag and fuzzy cuffs, given that both of the items are inspired by bondage gear, but it's still a point to be made.

**Comment by tigercat2000** [comment]
>To you, as your mind is already made up. I'm sure it will mean something to others though. Anyway, continuing this is pointless as I've said my piece. Have a good day.

That isn't my point, I'm not saying "well this doesn't change my opinion!"
I'm saying that your point is invalid and *shouldn't* mean anything to others, because you're misrepresenting (intentionally or not) how Wikipedia's page naming system works. This title is used as part of the way they `disambiguate` different terms - For instance, if there's both a Video Game and a TV show named "The Monkey's Legs", one would be titled `The Monkey's Legs_(TV Show)` and the other `The Monkey's Legs_(Video Game)`. 

The reason this one is disambiguated as `_(BDSM)` is because it is specifically talking about all the different types of `Gags` used in a BDSM context. My refute to your point that "Ballgags are on this page and therefore they are BDSM" is in two halves: The first half is that while they are present on this page, they are also used in the wikipedia page that is generically describing all types of `Gag` as the sole example image, with no reference to BDSM. The second half is that on this page is a bunch of other examples of gags that people can use in BDSM, _including_ medical tools and even duct-tape over the mouth, both of which are items that are being argued to be fine in the game.

**Comment by KasparoVy** [comment]
Steady as she goes, number one

**Comment by variableundefined** [comment]
These items existence blatantly violate server rules. It should've been removed a long time ago.

**Comment by davidchan13** [comment]
Why would you remove the ballgag but not the fuzzy handcuffs?

**Comment by KasparoVy** [comment]
No more ideas.

**Comment by Mitchs98** [comment]
Yeaaah don't remove fuzzy cuffs.

**Comment by Spacemanspark** [comment]
My toes can be considered fetish content. It's what the item's intended purpose is... and there's quite literally only one reason fuzzy cuffs are used, and what they're made for.

Yes, handcuffs can be used for shenanigans, but it doesn't directly _encourage_ it.

**Comment by AffectedArc07** [comment]
1) Handcuffs are an essential part of gameplay, do you **REALLY** want to make security resort to stunlocks? Regular cuffs are vital for sec to play properly, fluffy cuffs are only good for being *that kind of person*
2) We are we still discussing on a closed PR? We have a discord for this shit

**Comment by davidchan13** [comment]
I could care less about the chaps being gone (there is no such thing as 'assless' chaps, all chaps have no groin by design as they go over another pair of pants), the ballgag on the other hand did actually have it's use considering muzzles were in short supply and the ballgag was a spare. Handcuffs on the other hand are not in any sort of limited supply, fuzzy cuffs only exist as fetish content.

**Comment by variableundefined** [comment]
Add more muzzles.

Simple solution.

**Pull request merged**
