### PR TITLE
Asmerath's fluff item update

### PR DESCRIPTION
**Pull request by Asmerath**
## What Does This PR Do
Adds a new donator fluff mask for Asmerath, Removes donator accordion.

## Why It's Good For The Game
Donator fluff change approved by Doc

## Images of changes
mask icon
mask inhand
mask sprite

## Testing
Tested on a private server.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

PR author has since linked account.

**Comment by hal9000PR** [comment]
We don't do changelogs for fluff items as its a change for a single person.

**Comment by Asmerath** [comment]
> We don't do changelogs for fluff items as its a change for a single person.

oh, do I remove that bit then?

**Comment by Asmerath** [comment]
> > > We don't do changelogs for fluff items as its a change for a single person.
> > 
> > 
> > oh, do I remove that bit then?
> 
> Yes please

done! hope I did it right

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
