### PR TITLE
LIGHTING - Fixed divide by zero, optimize performance

### PR DESCRIPTION
**Pull request by ZomgPonies**
- We were missing schecks in the overlay file.

### CODE REVIEW

**Comment by TheDZD** [comment]
Can this be merged already?

**Comment by TheDZD** [comment]
Can this be merged already?

**Comment by ZomgPonies** [comment]
I've already got it running on prod, merge it post-haste it seems to have a pretty noticeable effect.

**Comment by PJB3005** [comment]
that scheck is actually causing an issue where some lights don't update under heavy load.

This is because the lights get added to the update lists WHILST the process is being slept by scheck, and this causes the process to straight up empty the update list without getting to the new ones.

**Pull request merged**
