### PR TITLE
Adds the cluwne goblin

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
Adds the cluwne goblin
1/20 chance for it to spawn as the leader when a honknomoly event occures
Higher damage, higher speed, and higher health than the normal clown goblin. Made out of every unfunny bone in someones body. Won't die to space either.
Drops some fake variants of the cluwne equipment.
Leaders are also dynamic for tears now

## Why It's Good For The Game
I mean it's just funny and makes sense that if clown goblins exist a horrific cluwne goblin would exist too.
Gives people the ability to look like a complete idiot rarely 

## Images of changes
840a205cbd067b210d5f14b9acf63db1
get ready to see this in game (Made by ATP engineer)
dreammaker_yCVCPLOnj1

## Testing
Compiled, ran, lost my soul to a cluwne goblin. 

## Changelog
:cl: GDN, ATP engineer
add: The cluwne goblin. It's coming for you (sprite by ATP engineer)
/:cl:

### CODE REVIEW

**Comment by ATP-Engineer** [comment]
MY BABY BOY!

**Comment by Adrer** [comment]
Thanks I hate it

**Comment by Pennwick** [comment]
It might be better to just have it drop a real Cluwne Mask and regular Clown shoes. With only a 5% chance of spawning per honknomaly it might as well be the real thing.

Not to mention the existence of fake Cluwne gear could cause some rule issues. Anything Cluwne related tends to send bystanders into a valid frenzy. I can see people getting beaten for just wearing the fake mask.

**Comment by GDNgit** [comment]
> It might be better to just have it drop a real Cluwne Mask and regular Clown shoes. With only a 5% chance of spawning per honknomaly it might as well be the real thing.


> Not to mention the existence of fake Cluwne gear could cause some rule issues. Anything Cluwne related tends to send bystanders into a valid frenzy. I can see people getting beaten for just wearing the fake mask.

Neither item are supposed to be able to actually be put on so both are pretty damn buggy.
Cluwne shoes don't do anything on their own, and cluwne mask will cause invis jumpsuits, duplicated masks, and other oddities. I don't really see a need to fix these issues. 
I also think that people won't go postal for no reason as people already do this with chameo stuff

**Comment by Carthusia** [comment]
> It might be better to just have it drop a real Cluwne Mask and regular Clown shoes. With only a 5% chance of spawning per honknomaly it might as well be the real thing.
> 
> Not to mention the existence of fake Cluwne gear could cause some rule issues. Anything Cluwne related tends to send bystanders into a valid frenzy. I can see people getting beaten for just wearing the fake mask.

I mean, at least fake cluwne gear wont curse you into being a cluwne, if you even touch a real cluwne item, it fuses to you, and i think turns you into a cluwne over time if its not cut off.

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Pull request merged**
