### PR TITLE
Fixes NTRep's cane

### PR DESCRIPTION
**Pull request by Chopchop1614**
Fixes the NTRep's cane so it now works the same as the cane with injury supporting. The issue page is #5362
:cl:
Fix: fixed NTRep's cane
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
:snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake:

**Comment by monster860** [comment]
:white_large_square: :white_large_square: :white_large_square: :white_large_square: :snowflake: :white_large_square: :white_large_square: :white_large_square: :white_large_square:
:white_large_square: :white_large_square: :white_large_square: :white_large_square: :snowflake: :white_large_square: :white_large_square: :white_large_square: :white_large_square:
:snowflake: :snowflake: :white_large_square: :white_large_square: :snowflake: :white_large_square: :white_large_square: :snowflake: :snowflake:
:white_large_square: :white_large_square: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :white_large_square: :white_large_square:
:white_large_square: :white_large_square: :white_large_square: :snowflake: :snowflake: :snowflake: :white_large_square: :white_large_square: :white_large_square:
:white_large_square: :white_large_square: :snowflake: :snowflake: :snowflake: :snowflake: :snowflake: :white_large_square: :white_large_square:
:snowflake: :snowflake: :white_large_square: :white_large_square: :snowflake: :white_large_square: :white_large_square: :snowflake: :snowflake:
:white_large_square: :white_large_square: :white_large_square: :white_large_square: :snowflake: :white_large_square: :white_large_square: :white_large_square: :white_large_square:
:white_large_square: :white_large_square: :white_large_square: :white_large_square: :snowflake: :white_large_square: :white_large_square: :white_large_square: :white_large_square:

**Comment by tigercat2000** [comment]
a better solution would be making some kind of var on items

**Comment by TheDZD** [comment]
Pretty much what Tiger said.

**Comment by Fox-McCloud** [comment]
Either a var or a proc that returns 1 or 0

**Pull request closed without merging**
