### PR TITLE
Reworks chameleon flag

### PR DESCRIPTION
**Pull request by datlo**
This PR aims to make the chameleon flag a more versatile tool, while keeping the functionality of the current Chameleon flag.

List of changes : 

- Moved to Stealthy Tools from Explosives

- Cost reduced from 7 TC to 1

- Now start without an explosive, but can be boobytrapped with any grenade. This explosive still detonates once the flag is done burning, as with the current flag.

- The grenade can only be removed by the person who installed it.

- Added admin logging (let me know if this is too much logging, it logs on boobytrapping the flag and on being lit on fire)

Non-exhaustive list of stuff to do with this new flag : 

- Buy a syndicate minibomb and install it in the flag, resulting in the exact same behaviour and TC cost (6 +1) as the old chameleon flag. Wow! It's like nothing changed!

- Use the flag without an explosive to decorate your evil autism fort at an affordable price.

- Buy 20 clown flags.

- Buy less clown flags but traps one of them with a banana grenade instead for extra hilarity.

- Label your flag "Kingdom of the Rumba Beats" and booby trap it with a 300/300 potassium water grenade.

And more! The possibilities are endless! Or at least more than the current chameleon flag.

🆑
add: Chameleon flag reworked : Now cost 1 TC from 7, but starts without an explosive. It can be boobytrapped using any grenade or a syndicate minibomb.
tweak: Chameleon flag moved from "Explosives" to "Stealthy Tools" in the uplink.
fix: Fixed description of syndicate flags on the suspicious supply depot.
/🆑

### CODE REVIEW

**Comment by Nicaragua1** [comment]
This is awesome. I love it. I would only change the explosion to denote when the flag is put on fire. Not when its done burning. That way it works lile a pizza bomb

**Comment by datlo** [comment]
I'm keeping the behaviour working as it was originally designed for now. I've done some thinking and it allows more usage out of it that way, especially with custom grenades.

**Comment by Denthamos** [comment]
Keep in mind this will effect the syndicate depot so you should talk with @Kyep about this as well.  The flags are generally placed in specific spots as explosives.

**Comment by datlo** [comment]
Oh, the depot has cham flags mapped in? I'll look into that.

**Comment by datlo** [comment]
depot flags are now armed with a minibomb on spawn

**Comment by datlo** [comment]
Depot flags are now armed with a plasmafire grenade since they are meant to start a chain reaction of flags exploding.

**Comment by Kyep** [comment]
So long as the depot camo flags still function as traps (ie: kill people who get them lit on fire) I'm fine with this PR.

**Comment by datlo** [comment]
Yeah they start a plasmafire instead of exploding now, but they're definitely still deadly.

**Comment by TDSSS** [comment]
They used to cost 7 TC !?!
Pff, no wonder they were as underused as they are, you could almost get an esword for that.

**Pull request merged**
