### PR TITLE
[WIP] Revert 11305 and adds additional features.

### PR DESCRIPTION
**Pull request by datlo**
## What Does This PR Do

Revert https://github.com/ParadiseSS13/Paradise/pull/11305, update the code to modern standards, and implement pony crewmembers.

TODO : 
- Revert Fox's PR, readding ponies and Equestria's flag. ✔️ 
- Add Portal to Equestria to Arrivals on all stations, to be used by pony crewmembers to join the station. ✔️ 
- Update the flag's sprite to match Equestria's canon flag, as seen here : 
image

- Add Starlight Glimmer.

image

- Refactor pony mobs into carbon subtypes.
- Add pony character creation.
- Add pony inventory system.
- Implement pony subspecies.
- Add telekinesis to unicorns.
- Add flight to pegasi.
- Add super strength to earth ponies.
- Add all three to alicorns, admins only.
- Add MLP-themed gateway expeditions.
- Implement Canterlot as the new Central Command, and replace references to Nanotrasen by Ponytrasen.

## Why It's Good For The Game

I often hear people complain that Paradise is too similar to other codebases, and that we might aswell rebase to TG. 
This is the opportunity to truly set ourselves apart by embracing a part of our codebase that was mistakenly deleted : Ponies. 

By going all-in on ponies, Paradise can combine the furry and MLP fandom into an unstoppable force that will forever stay on top of the hub, leaving all other servers in the shade for centuries to come.

## Images of changes

image

## Changelog
:cl:
add: adds [ponies](https://derpicdn.net/img/2017/10/28/1571884/large.png)
/:cl:

### CODE REVIEW

**Comment by Wojz** [comment]
Jesus wept.

**Comment by LordShekelstein** [comment]
https://www.youtube.com/watch?v=0RFwyobtnKA

**Comment by MRgaty** [comment]
NO! TAKE AWAY THOSE EVIL CREATURES!! I !DONT WANNA BE PINK AGAIN!!!

**Comment by shmabuu** [comment]
The bad ending

**Comment by datlo** [comment]
image

**Pull request closed without merging**
