### PR TITLE
Robotics oil tank replacement

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Replaces the Robotics oil tank with a welding fuel tank, and the welding fuel tank with a water tank.

## Why It's Good For The Game

Oil isn't actually used for IPC maintenance anymore, so it makes a lot more sense to have a fuel tank instead.

## Images of changes

**Before:**
old

**After:**
new

## Changelog
:cl:
tweak: Removed the oil tank from Robotics, and replaced it with a welding fuel tank.
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
Robotics has welding tools to fix robots, as well as repair and build mechs. Should probably keep the welding fuel tank, or give them a wall tank like chemistry has.

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Comment by Spacemanspark** [comment]
Not like it's a problem that I'd say would be reason to say no to the PR, but why a water tank? Robotics already has a sink and there's nothing robotics really needs water for.
May as well not have it there tbh. Not a big deal, though.
+1

**Comment by SabreML** [comment]
This'll be invalidated by the big MedSci remap, but I'll leave it open until then anyway.

**Comment by SabreML** [comment]
Changed my mind. Closing to reduce the number of open PRs.

**Pull request closed without merging**
