### PR TITLE
More Lighting Tweaks and Optimizations

### PR DESCRIPTION
**Pull request by Fox-McCloud**
More lighting optimizations, courtesy of @Mloc

https://github.com/Baystation12/Baystation12/pull/10269
https://github.com/Baystation12/Baystation12/pull/10070

Still requesting review by @PJB3005 as a "just in case".

- Makes lighting overlays perform better for clients
 - This also kills of lighting transitions entirely (they're already disabled for performance reasons)
- Optimizes dview() for faster performance

### CODE REVIEW

**Comment by tigercat2000** [comment]
@Fox-McCloud I don't think you should completely rip out the lighting transitions. They might have a better solution later, or a downstream that doesn't care about performance could re-enable them.

**Comment by Fox-McCloud** [comment]
Considering this is @Mloc's system and he's ripping it out himself, I see no reason to keep it, especially when the problem is inherently with animate(). Again, performance is more important, as is a better experience (and likely less crashes) for clients.

If a downstream wants to re-enable them, they're more than welcome to re-implement the code themselves and take the performance hit.

**Comment by tigercat2000** [comment]
@Fox-McCloud But it isn't going to increase performance to rip out a disabled system, that's my point here.

**Comment by Fox-McCloud** [comment]
And the system that Mloc put in place, to help client performance, isn't compatible with transitions. To quote him:

>Removes lighting transitions- they don't work with the new system.

**Comment by tigercat2000** [comment]
@Fox-McCloud Don't work or couldn't be bothered to reimplement? 

Suppose it doesn't matter. They aren't getting reenabled and no one thinks animate() will ever get any better, so.

**Comment by PJB3005** [comment]
@tigercat2000 I assume couldn't be bothered, I myself can come up with a way to reimplement it.

not that I would do it because well, `animate()` is really slow.

:+1:

**Pull request merged**
