### PR TITLE
Readds the mining podbay

### PR DESCRIPTION
**Pull request by monster860**
image

It got removed when we switched over to metastation z-5.

:cl: monster860
add: Adds the mining podbay (again)
/:cl:

### CODE REVIEW

**Comment by davidchan13** [comment]
Is there a reason mining doesn't have a pod bay at the mining dock on the station?

**Comment by Denthamos** [comment]
@davidchan13 It is something I would love to see added at cargo on the station.  A podbay that can fit 1-2 pods for the miners.  One of the issues with making pods for miners as pod mechanic have been the fact they really have no place to put them so this PR and such an idea would help alleviate that.

**Comment by monster860** [comment]
Merge conflicts fixed

**Comment by Crazylemon64** [comment]
LGTM

**Pull request merged**
