### PR TITLE
Announces the Station name, fixes the hashes...

### PR DESCRIPTION
**Pull request by SamHPurp**
:cl: Purpose
add: CyberiadAI Discord Bot now announces which station is being used.
/:cl:

### CODE REVIEW

**Comment by tigercat2000** [comment]
This could be an issue with our server tools, we rely on IRC messages being pretty specific. CyberiadAI just checks for `Server starting up`, but other tools might not. @Allfd confirm if this is alright?

**Comment by SamHPurp** [comment]
🤔 that makes things more difficult. Without knowing how those work / them being open source, I can't exactly tweak/improve those.

**Comment by Allfd** [comment]
Should not be a problem, its only looking for "Server starting up"

**Comment by SamHPurp** [comment]
Great thanks for confirming @Allfd

**Pull request merged**
