### PR TITLE
Makes Paradise 60 FPS

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Note: you need Byond 511+ for this to work
:cl:
add: You can now change your client FPS in Game Preferences
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
Well Goddamn, this isn't something I expected to see. Very cool! 

Are there any further implications for this affecting stuff in the future? Presumably not since it's a client's choice?

**Comment by StreakyHaddock** [comment]
60fps is smoother, but it triggers motion sickness in some people, and just feels plain weird to others since it's generating more frames than the tick rate so you're quite aware of the stuttering nature of movement.
Although I do like the smoothness of it a whole lot.

**Comment by uraniummeltdown** [comment]
It's not 60 fps by default, you have to change it manually

**Comment by Necaladun** [comment]
As long as people can choose, LGTM.

**Comment by KasparoVy** [comment]
Fantastic.

**Pull request merged**
