### PR TITLE
Thrown Stunbatons have a low chance to stun

### PR DESCRIPTION
**Pull request by SamHPurp**
For @KasparoVy 

image

:cl: Purpose
add: Thrown stunbatons & improvised batons have a low chance to stun.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
What happens when you catch them? Is `thrown_impact` not called then-- leading to no stun?

**Comment by tigercat2000** [comment]
We are in a feature freeze according to #9426 you know...

**Comment by Crazylemon64** [comment]
@SamHPurp please cite the code improvements you are cashing in here

**Comment by Fox-McCloud** [comment]
This will require all your active fix/refactor PRs to be merged before this can be.

Your spelling fix PR is too minor to count (as detailed in the feature freeze PR).

**Comment by SamHPurp** [comment]
As this is flagged minor: #9653

**Pull request merged**
