### PR TITLE
Code Alpha

### PR DESCRIPTION
**Pull request by Kyep**
This PR adds a new alert level, Code Alpha, in between Red and Gamma.
It can only be set by CC, and exceeds red, but unlike Gamma it doesn't unlock the Gamma Armory.

It is intended to be used for situations where you want a higher alert than red, but don't want to unlock Gamma weapons. 
For example:
- Nuclear Ops declare war (gamma armory is too powerful, since war ops usually lose anyway, but arguably this is a beyond red situation)
- Biohazard out of control (sort of a warmup to potential epsilon, and a 'hey, this is a serious crisis' alert)
- Admin Events (as a "unusual stuff is happening, assume brace positions")

The status display indicator flashes between blue and yellow 'ALPHA':
alpha_alert

🆑 Kyep
add: Added 'Code Alpha' security level, in between Red and Gamma. Intended to be used for War Ops, Events, etc.
/🆑

### CODE REVIEW

**Comment by DesolateG** [comment]
But... what mechanical purpose does Alpha have over Red?

**Comment by Kyep** [comment]
Lots of people are desensitized to red. They somewhat ignore it.
Alpha is intended to make people sit up and pay attention. To mark things that aren't just "confirmed threats" but are "serious thing that all crew should pay attention to". It also functions as a big hint from CC that crew should be taking something seriously. Sometimes, sadly, even blobs get mostly ignored.

**Comment by taukausanake** [comment]
That doesn't really make it worth anything though. At easy as you can get Red (which isn't sometimes) you can just as well get Alpha in this case. I do like the sound of having an Alpha level however but it needs a purpose. We have Gamma and Delta, just give it a real purpose besides Code Red+ and it might be good. Are there any alert fields not touched yet by the other codes?

**Comment by Kyep** [comment]
I did consider having nuclear ops declaring war automatically set alpha... but I wasn't sure how people would take this.

**Comment by DesolateG** [comment]
The problem with code red is a lack of proper use for it. You're not supposed to STAY on red, it's meant for immidiate threats.

If the player base was encouraged to go back down to blue when it's not an immidiate threat this wouldn't be an issue. As such I don't feel Alpha is needed. If the crew wants to ignore obvious problems well then, kudos to the antag.

**Comment by Kyep** [comment]
You can't expect Command to drop back down in security levels when they have no incentive to do so.

Code Alpha is more a RP alert level, set by admins/CC, in response to certain events where red doesn't feel sufficient, and gamma is too much. Blobs eating the station as most crew are ignoring them. Nuclear ops (where you want to recognize it, but obviously, you don't want to give the crew gamma as gamma is too strong vs. operatives). Etc.

**Comment by taukausanake** [comment]
Well if an RP level, in that it's set by CentComm, then maybe Code Alpha can be for ERT. I would almost argue by that point though that the ERT members, granted they have enough and a competent leader (or admin) would basically become a military police and assume command until the threat is removed. That might not work well

**Comment by Kyep** [comment]
Yeah, we could use Code Alpha to mean "ERT are on station and have assumed Command of the Cyberiad". 

That's just one use, though. Centcom can accompany an Alpha declaration by a note explaining what it means. It is a good catch-all like that.

**Comment by taukausanake** [comment]
The less work for the admins the better I think. Pretty sure they won't like the idea further expanded. Part of the reason I don't think even ERT will work out because shitlers

**Comment by Regen1** [comment]
The name "Alpha" doesn't make any sense.. at first glance I though it'd be something akin to green.

Really, none of these do, green -> blue -> red -> Gamma -> Delta -> Epsilon?

I don't know, Alpha doesn't sound like a "high alert" level to me, more like a low alert, on par with green.

**Comment by Ralta** [comment]
Personally, I'd rather we went to Green > Yellow > Red > Delta > Epsilon > Gamma

Just makes more sense. If Alpha gets added, I'd like to see a fleshed out alert announcement explaining what that means, and what the difference is between Red and Alpha. If Red currently means "Alert, something bad is happening! Stay in your departments!" then does Alpha mean "Alert, something bad is happening! It's really bad we promise! Still stay in your departments!" ?

As others have said, it's the mechanics that I'm concerned about. If the system gets a bit of an overhaul where the alert descriptions, announcements and corresponding staff expectations are updated then I'd be all for it. 

Otherwise, as much as I hate to say it, this would just be fluff.

**Comment by Kyep** [comment]
@Regen1 There are a few reasons I went with 'Alpha':
- It is the first, lowest, and starting point of the CC alert levels. So, 'alpha' makes sense. It also sounds cool, IMHO at least. "Code Alpha!"
- It shares many letters with 'Delta', which helped me when I was making the status monitor sprites for it (blue/yellow, as opposed to the yellow/red of delta). When I did a PR ages ago to add sprites to the gamma/delta/epsilon levels, someone else kindly helped me with the sprites, but I had to assume I'd need to do the sprites for this myself.
- I considered a few other letters (theta, omicron, rho, sigma, phi, psi, omega), that sounded like they could make badass alert levels. However, some of them make more sense for specific cases (omega = some 'your only objective is to survive' utter insanity, etc), and if you look at the existing ones (gamma, delta, epsilon) they're the 3rd, 4th and 5th letters, respectively. Neither 'zeta' (6th) or 'eta' (7th) sound great. 1 and 2 are 'alpha' and 'beta'. "beta alert' sounds... uninspired. 

@Ralta 
- I'm not looking to change the other alert levels in this PR. I don't want to muddy this with arguments about changing blue to yellow, or renaming other levels. That'll just get confusing and distracting real quick.
- Alpha does get an alert level change announcement. Currently it is: "_Central Command has ordered the Alpha security level on the station. All hands are to prioritize handling the crisis._" I made it as generic as possible so it can work for a wide variety of things. The SOP for it is still being worked out, but I think of Alpha as more like Gamma without the armory, than just "Red II". IE: martial law is declared.
- I don't think it is necessarily a bad thing if this is fluff. We regularly see cases where 'fluff' like this would be immersive. For example... nukies declare war. We want to make clear its a massive emergency, but we DON'T want to give gamma armory because then nukies will certainly lose. Alpha would fit that niche very well. Similarly, it would fit when blob/terrors/xenos are out of control and Cyberiad is being given a few minutes to see if they can hold out / make a push for it before epsilon is declared. It would fit that as well. Not to mention the custom uses during events. There are lots of places it could fit, even if it is a bit generic - that's part of the point. The more specific I make it, arguably the less useful it is because every detail I add to it limits its usage to a narrower and narrower set of cases. Alpha is intended to be CC's catch-all, what they use when the situation has reached major crisis point and they want the alert level to reflect this - but no other, more specific alert applies.

**Comment by Aurorablade** [comment]
I am gonna have to go with regens in that while it sounds neat, the jump to Alpha actually dosen't make alot of sense, It really does not seem like a high alert level. as for an incentive for dropping level, with the way some of our antags go sometimes theres no NEED to drop level and i have seen the level drop plenty of other times in moments of calm.

How long before palyers just treat Alpha(or whatever we would end up calling it) as 'adminbus is happening' instead of something serious? I have seen people take red serious..but its a mindset people with alot of people.

I mean i see how a special admin level is good for events, but thats all it is...To use it on war ops or ERT is something red could handle.

**Comment by alexkar598** [comment]
Code alpha should never be called automatically as it will make people insensitive to it as people do with code red

**Comment by Kyep** [comment]
@alexkar598 There is nothing in this PR currently that sets alpha automatically. It is a manual thing by admins.

**Comment by Fox-McCloud** [comment]
Following discussion between the Heads of Staff and Maintainers, it was decided to close this PR; if the issue is the playerbase becoming desensitized to an alert level, adding another one will do little else other than cause the playerbase to slowly become desensitized to the new alert, especially if it's meant to be used in situations like Nuke Ops or Blob, which are still a common occurrence. Additionally, it being Admin-only would introduce an element of unreliability, leading to situations where some Nuclear Operatives have the new Alert called, and others don't, and so forth with every applicable situation.

**Pull request closed without merging**
