### PR TITLE
initializes obj/random

### PR DESCRIPTION
**Pull request by GDNgit**
## What Does This PR Do
title

## Why It's Good For The Game
I ran into this while testing some GC stuff and I needed to init these else I'd get a couple of runtimes, so I'm also putting a PR up for it

## Testing
compiled and ran

## Changelog
NPFC

### CODE REVIEW

**Comment by GDNgit** [comment]
This PR doesn't need to be TMed, it was just something that was noticed during testing of some GC debugging tools. It *should* be safe to just be full merged.

**Review by S34NW — COMMENTED** [review]
TM was requested by host, will be required for merge due to stability concerns.

**Review by S34NW — APPROVED** [review]
Not been made aware of any issues in the week of TMing

**Review by hal9000PR — APPROVED** [review]

**Comment by AffectedArc07** [comment]
TM'd with 0 issues

**Pull request merged**
