### PR TITLE
Adds a Flora Garden left of Arrivals

### PR DESCRIPTION
**Pull request by gt33**
🆑 Reeeeimstupid
rcsadd: A flora garden west of Arrivals.
/🆑

pic

### CODE REVIEW

**Comment by pinatacolada** [comment]
While the idea of a garden is nice, this is completly out of place at arrivals, and comes out as a big boring box with a tree. You can probably find a more suitable area near the holodeck, and flesh out the garden itself too, dont let it just be a square with nothing more

**Comment by LightFire53** [comment]
I'm with pinata here. It is completely out of place, plus it is where the sol government traders ship docks. And super boxy. Would probably be a nice addition over in dorms.

**Comment by Crazylemon64** [comment]
Pros
* In abstract, not considering where it is in relation to the rest of the station, it looks nice

Cons
* This is a corridor into formerly empty space with a room tacked to the end of it
  * The lack of surrounding infrastructure that the rest of the station has makes it feel out of place
  * How much it "sticks out" from the station seems disconcerting
* It's very far from where the "action happens" on the station


thanks for including a snapshot though

**Comment by LightFire53** [comment]
Right. Not where the traders dock, but still out of place.

**Comment by gt33** [comment]
Well, not supposed to be where the action happens. It's supposed to be a calm, relaxing place.

**Comment by gt33** [comment]
But i'll try to find a better place for it.

**Comment by SamHPurp** [comment]
.... This looks entirely tacked on... because it is.

No location for Sol Traders to dock, removing an EVA airlock... This just doesn't work for me.

**Comment by Fox-McCloud** [comment]
That doesn't look good at all.

**Comment by KingPhilipIII** [comment]
>New cult base, hidden where nobody sees it.

>Just make it a little less terrible please.

**Comment by fludd12** [comment]
You could put it north of the bar + Botany, where the big maintenance hall with the odd shutter doors are. Making a path to it might be a bit weird, though.

**Comment by Birdtalon** [comment]
Doesn't look like much thought has gone into this at all. Horrible location and looks ugly as hell for something being added for aesthetic purposes only.

**Comment by gt33** [comment]
There was no airlock where it was.

**Comment by Spartan6** [comment]
I could go into more detail, how this should be its own room with an APC and there is no airlock or even firelocks and I'm pretty sure no security camera...

But overall this seems rather poorly executed.

**Pull request closed without merging**
