### PR TITLE
Fixes violin and guitar missing hitsounds

### PR DESCRIPTION
**Pull request by tigercat2000**
also reduces the damage because wooden instruments simply don't hurt as much as a metal 20 pound  fire extinguisher

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Iffy about the damage dealt, but meh, it's not a big deal

:+1:  to the sound.

**Comment by Bram961** [comment]
Tiger are you prepared to take a hit to your left arm with a fire extinguisher and a guitar on the right arm to see what the hospital says about the amount of damage? we need to verify this.

**Comment by TheDZD** [comment]
Could be worth keeping the force as it was, it's not like force 10 items are hard to find. The main problem was that these were completely silent.

**Comment by tigercat2000** [comment]
force 10 wooden instruments were annoying me, it was easier to make them 5 force than to add them breaking after the first hit. And like you said, f10 items are easy to find.

**Comment by Fox-McCloud** [comment]
I'm inclined to say leave it at 10--seconding what DZD said.

**Pull request merged**
