### PR TITLE
Removes "toy" guns from under Christmas trees

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Santa accidentally distributed riot dart toy guns to the station, what a doozy.

Good thing we were all responsible adults and did not cause any mischief with those guns, 
## _riiiight?_

🆑 Santa's Lawyer
del: Removed riot dart toys from under Christmas trees.
/ 🆑

### CODE REVIEW

**Comment by awesine** [comment]
i ded

**Comment by KingPhilipIII** [comment]
Fun police

**Comment by taukausanake** [comment]
I mean are they even that dangerous? What is stamina damage anyways?

Would it be possible for presents to have non-riot darts in them but have a _chance_ to have riot? I'd think of it as a "naughty" gift personally

**Comment by KingPhilipIII** [comment]
I think it's just kinda funny. Two whole riot dart weapons aren't even that big of a deal.

**Comment by davidchan13** [comment]
What makes you think it was an accident?

**Pull request merged**
