### PR TITLE
Replaces one crew monitor console in medlobby by crew records

### PR DESCRIPTION
**Pull request by datlo**
Okay, okay. I know. Nobody cares about medical records. The thing is, MAYBE people would care at least a little more if they weren't shoved all the way back into the medical break room.

I literally thought regular medical staff didn't have a medical record console to access before searching the map for one today.

This PR replaces one of the two crew monitoring consoles at the front desk by medical records.

🆑
tweak: Replaces one of the two crew monitor consoles in medical front desk by a medical record console.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
You're not wrong, but that doesn't mean they shouldn't be accessible at the front desk. That's in theory where you'd actually need to access medical records. Besides, there's two consoles right next to each other that do the same thing (and do the same thing as the portable monitor available for free to med) so it's not like the crew monitor's going to be missed.

**Comment by Dinarzad** [comment]
> Currently, I am not sure what, if anything, people would use medical records for.

I don't think I've ever used 'em as a doctor, but I've used them as a coroner before. Print out someone's record or copy the information down onto the autopsy report, most importantly the fingerprint hash.
That's about it though.

**Comment by datlo** [comment]
They can also be used to get DNA for your advanced pinpointer as a traitor.

**Comment by taukausanake** [comment]
Records might be nice if we actually _"recorded"_ data instead of doing the time warp every time but we aren't Persistence so there's that. Kind of would be nice if there was some stuff that carried on between rounds

**Pull request merged**
