### PR TITLE
Removes the x-ray genetic mutation, makes the implant admin-only

### PR DESCRIPTION
**Pull request by Superhats**
Theoretically, completely removes the x-ray mutation. Removes x-ray implants from nuke ops uplinks and protolathe design.
I've seen many people complain about x-ray, and how it made things unfair for the antagonists. X-ray is now only available for cameras, or through admins.

:cl: Superhats
del: Removes x-ray from the list of genetic mutations
tweak: X-ray implants are no-longer available through protolathes, or uplinks.
/:cl:

### CODE REVIEW

**Comment by Superhats** [comment]
Edit: PR closed because I messed up and I'm lazy

**Comment by FreeStylaLT** [comment]
well.. well then

**Comment by Shadeykins** [comment]
Not sure how I feel about removing it from nukies, though arguably thermals perform a similar function.

Largely it's crew/regular antagonists wherein xray is a massive issue.

**Comment by Spartan6** [comment]
You're stepping onto a mine field with this...

**Comment by taukausanake** [comment]
Perhaps genetics should be a little more difficult to work, but that's a refactor for another never most likely

**Pull request closed without merging**
