### PR TITLE
Adds five new IPC accessories

### PR DESCRIPTION
**Pull request by TravellingMerchant**
Adds five new IPC accessories, had to re-make the whole PR to fix the conflicts.

Exactly the same as https://github.com/ParadiseSS13/Paradise/pull/7033#issuecomment-292084170

Just fixed conflicts.

Edit: I owe @Crazylemon64 a lot and so do all of you. He is a real godsend and we are lucky to have him.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This still isn't done properly; there's sprites missing that were added in @KasparoVy's PR.

**Comment by Crazylemon64** [comment]
@Fox-McCloud This is rebased to include those sprites - let me verify

**Comment by Crazylemon64** [comment]
Ah, at the moment this does overwrite the previous PR. 1 moment

**Comment by Crazylemon64** [comment]
There I fixed it

**Comment by TravellingMerchant** [comment]
Perfect! Let's get these babies in!

**Pull request merged**
