### PR TITLE
Fixes Mutadone

### LINKED ISSUE #3383: mutadone doesn't fix mutations

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes mutadone not working with some genetic mutations

Fixes #3383

@Crazylemon64 

:cl: Fox McCloud
bugfix: Fixes mutadone not working with some genetic mutations
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Will this auto-close #3383?

**Comment by Fox-McCloud** [comment]
Will now.

**Comment by Crazylemon64** [comment]
Looks good - perhaps checking the length of `active_genes` might be more sure-fire, but all these mutations should now be treated with mutadone... Should the monkey block count as a mutation?

**Comment by fludd12** [comment]
I believe it did at one point - I was rather sad when that was, intentionally or not, removed, as it made testing stuff in the test lab on an actual human require help from genetics or competent R&D

**Comment by Crazylemon64** [comment]
@fludd12 Try giving the monkey unstable mutagen, first

**Pull request merged**
