### PR TITLE
Cleanbot oversight

### PR DESCRIPTION
**Pull request by Bram961**
This fixes them not cleaning blood trails

🆑 Kluys
Fix: Cleanblots not cleaning /obj/effect/decal/cleanable/trail_holder (blood trails)
/🆑

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Not keen on buffing cleanbots, to be honest.

The fix though is appreciated, for sure.

**Comment by Bram961** [comment]
Ill leave the PR as is to give it some time for more feedback (like a few hours or so) and if nobody likes the idea of giving cleanbots a slight buff (on avarage since this would double cleanspeed but keep their movespeed as is) I will just rip that bit out 😃

**Comment by Spartan6** [comment]
I would rather you change their behaviour to check if another cleanbot is trying to clean that tile, as multiple cleanbots tend to move onto a single tile and clean the same spot of blood, where as if they fanned out and did it at their normal speed, this would be a quicker affair.

Of course, I have no idea if this is possible.

**Comment by Aurorablade** [comment]
yeah keep the speed as is. otherwise the janitors will get more lazy.

**Comment by alexkar598** [comment]
image
fix your pr

**Pull request merged**
