### PR TITLE
Protects Comdom, Head of Shitcurity, and security from enthralling

### PR DESCRIPTION
**Pull request by RyanSmake**
:cl:Bxil
tweak: We are pleased to announce that Nanotrasen has managed to create a better mindshield implant which prevents shadowlings from enthralling your colleagues.
/:cl:

PS: Apologies for doing this from the webeditor, won't happen again

### CODE REVIEW

**Comment by Aurorablade** [comment]
It's like that intentionally and makes them take longer to thrall.

**Comment by FlattestGuitar** [comment]
@Aurorablade this makes implanted people **impossible** to thrall.

**Comment by KasparoVy** [comment]
Make minds shielded again. 👽

**Comment by Aurorablade** [comment]
This is a bad concept really cause it just presents a mind shield everyone meta. Now you can do that on cult but cult has a bit more freedom to rebound back. Shadowlings on the other hand can only thrall when hatched and need to rely on thralls to get a foot hold. As the moment they hit light they are fuckdiddlered.

**Comment by alexkar598** [comment]
Thanks for making the pr

**Comment by Tayyyyyyy** [comment]
I think there are better ways to balance a game mode than to make it more similar to other game modes.

**Comment by bigfatbananacyclops** [comment]
You're forcing shadowlings to perma kill all mindshielded people, this is not fun to take out players out of the game.

Vampire thralling also doesnt work against mindshield.

**Comment by RyanSmake** [comment]
What everyone forgets to consider here is, once a single mindshielded person is thralled, it is basically over. A single person losing can win the entire round for the shadowlings.

**Comment by Shadeykins** [comment]
I'd rather see how things shake out if the icy veins removal passes.

Shadowlings are tremendously overpowered either way and--while powers are a contributing factor--pretty much as soon as you get a thralled sec officer it's game over. This does mean slings/thralls will probably kill mindshielded people, but as it stands if you manage to get a mindshielded anyone (Captain, Blueshield, HoS, Sec Officer) the slings immediately snowball.

Whether or not removing Icy Veins or thralling Mindshielded people is the solution, I'm not sure--but we should certainly be attempting something.

**Comment by SkeletalElite** [comment]
Well time for every sec officer that walks into maint to be get swarmed by a shadowling and 5 thralls that will space their corpse

**Comment by RyanSmake** [comment]
What I am thinking now is, maybe it's worth it to try.
If this gets merged and maybe after one month of waiting it turns out that shadowlings are basically dead because of this, then I will revert myself.

**Comment by Shadeykins** [comment]
@Kyep To play devil's advocate, mindshields are already leveraged in Shadowling rounds--either to tell who's legit or by shadowling thralls themselves who steal the mindshield and implant themselves to trick everyone.

**Comment by davidchan13** [comment]
Stop using 'command' when describing Loyalty implanted crew. Only 2 Heads of staff have them.

**Comment by RyanSmake** [comment]
Silly me, let me fix that.

**Comment by RyanSmake** [comment]
Whoops, silly me.

**Comment by davidchan13** [comment]
'Makes Mindshield prevent Thralling' might be a better title since they can be implanted mid round, and will if this PR goes through.

**Comment by Aurorablade** [comment]
if people didn't single file into dark tunnels when shadowlings were called we might not have a issue.

**Comment by RyanSmake** [comment]
I've had another idea recently. How about having both a mindshield and a tumor causing you random stuns over time?

**Comment by Vivalas** [comment]
Putting up a bunch it shadowling nerf PRs separately is going to make balancing shadowlings difficult as everyone is just going to throw their different solutions up instead of one PR where people can pick and choose various options

**Comment by tigercat2000** [comment]
This is going to be closed. Disallowing security from being thralled is too large of a nerf, and means that Shadowlings wouldn't really have any way to combat sec aside from trying to conventionally killing them.

**Pull request closed without merging**
