### PR TITLE
adds a swanky sweater

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Sprites from Hippie.

It's in the loadout.

JUST LOOK AT HOW CUTE IT LOOKS.

### CODE REVIEW

**Comment by Aurorablade** [comment]
.....No,

**Comment by FlattestGuitar** [comment]
Why not?

**Comment by Aurorablade** [comment]
we apprently have diffrent definitions of the term cute...

**Comment by The-Boogie** [comment]
_Rattle me bones_
a_skeleton_wearing_a_christmas_sweater_lol_by_thegregorythomas-d6xk4b8

**Comment by Necaladun** [comment]
Found where to buy these.
http://www.uglychristmassweater.com/
Can we add a fashion police role to sec now?

(Actually seriously)
See no problems, more loadout stuff is fun, more fashion to express yourself with is good.

**Comment by TravellingMerchant** [comment]
That _is_ swanky.

**Comment by ModDownloading** [comment]
Now, all we need is a white trenchcoat to match the fedora!

**Comment by PhantasmicDream** [comment]
It kind reminds me of a sweatervest more... And I think this station could use sweatervests

**Comment by LightFire53** [comment]
>swanky

:scream: :skull:

**Comment by Anoonki** [comment]
New cosby sweater?
Instant +1 best loadout item

**Comment by scrubmcnoob** [comment]
Yes please.

**Comment by Fox-McCloud** [comment]
This isn't Hippie. This is Goonstation; they should be given the credit.

This is the "Cosby Sweater".

**Comment by Cactus2388** [comment]
We need more cute sweaters

**Comment by MrFroztee** [comment]
@Fox-McCloud It's also on Hippie under the same. The difference likely being that when you scream while wearing it on Hippie, your character screams "ZIP ZOP ZOOPITY BOB!"

**Comment by tigercat2000** [comment]
@MrFroztee Just because Hippie failed to attribute the sprite source to Goonstation does not suddenly mean that the sprites are fine to use everywhere. 

This won't be merged until what @Fox-McCloud said is done.

**Comment by MrFroztee** [comment]
Well, there was no need to take that tone, I wasn't aware that it originated on Goon.

**Comment by Spacemanspark** [comment]
Fox literally just told you it was from Goon, dude.

**Comment by FlattestGuitar** [comment]
Making the proper Goonstation file locations work with custom Vox sprites would require a refactor of icon code for humans, which I'm really not in the mood for dealing with. Apologies.

**Comment by KasparoVy** [comment]
@FlattestGuitat Can't you just specify the icon location in the clothing object???

**Comment by KasparoVy** [comment]
@FlattestGuitar Can't you just specify the icon location in the clothing object???

**Comment by FlattestGuitar** [comment]
Not for the on-mob sprite. `icon_override` should point at a goonstation sprite, but it also overrides the species-dependent icons, so I'd  have to change the code around that to accommodate.

**Pull request closed without merging**
