### PR TITLE
Makes a bunch of UI's use /datum/browser

### PR DESCRIPTION
**Pull request by monster860**
Here's the full list:

- Atmos devices
- Area Atmos Computer
- General atmos control
- Holodeck control
- Medical and sec records
- Airlock electronics
- Brig Timers
- Guest Pass
- Kitchen Machinery
- Newscaster
- Pipe Dispenser
- Suit Storage Unit
- Podfab and Mechfab
- Sheet construction
- Assemblies
- ATM
- Ore Box
- Filing Cabinet
- Photocopier
- Virology "pandemic" machine

Also fixes a few instances where people forgot to close an `<a>` tag

:cl: monster860
rscadd: A bunch of interfaces now use /datum/browser.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
What are the actual visual impacts of this?

**Comment by monster860** [comment]
The visual impacts is that it uses the fancy stylesheet.

**Comment by TheDZD** [comment]
Could you include a few screenshots, for reference?

**Comment by Fox-McCloud** [comment]
side by side would be nice, yeah.

**Comment by monster860** [comment]
I have some screenshots.

**Comment by Krausus** [comment]
I'm pretty sure all of these should be using `open(0)` rather than `open()`, since the default behavior is for each closed window to trigger the `.windowclose` verb.

**Comment by Fox-McCloud** [comment]
@monster860 

Could you please change those to `open(0)`

**Comment by monster860** [comment]
@Fox-McCloud Done

**Pull request merged**
