### PR TITLE
Adds a netherworld ruin to lavaland

### PR DESCRIPTION
**Pull request by Emanthealmighty**
**What does this PR do:**
Adds a new ruin in lavaland which contains a portal that spawns netherworld creatures.
Updated netherworld creatures' sprites.
Adds some commented out features that cultists can use regarding the netherworld portal.

**Changelog:**
:cl:
add: Added a new lavaland ruin containing the netherworld creatures.
tweak: Resprited the netherworld creatures.
add: Full directional sprites for the "creature".
/:cl:

### CODE REVIEW

**Comment by Mocha-Not-Latte** [comment]
*Minecraft intensifies*

**Comment by Leanfrog** [comment]
So, while not every ruin should have some kind of reward I'm wondering what this will contain besides the portal or what the portal will give to whoever clears it.

**Comment by Fox-McCloud** [comment]
I told you to wait on this until lavaland was more completed.

**Comment by Emanthealmighty** [comment]
@Fox-McCloud
I can remove the ruin from this PR and bave it just be code and sprite improvements for the portal and the mobs spawned from it.

Either way, I would like to know if the ruin itself was done correctly or not, for when I actually make the ruin again or something similiar.

**Pull request closed without merging**
