### PR TITLE
Fixes #7324

### LINKED ISSUE #7324: Typo in gibber messages
**Problem Description**:
In code/modules/food_and_drinks/kitchen_machines/gibber.dm, line 126, message reads "This is not suitable for the [src]]!" <- note extra square bracket.

**What did you expect to happen**: 
The string should probably read "This is not suitable for the [src]!" without the spurious square bracket.

**What happened instead**:
The message displays to the players as "This is not suitable for the gibbber]!"

**Why is this bad/What are the consequences:**
It's ugly.

**Steps to reproduce the problem**:
Try to chuck something nonhuman in the gibber; observe error message.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Just derping around with my sandbox and found this one. I would have submitted a PR instead, but I'm still setting up my environment.

### PR DESCRIPTION
**Pull request by SamHPurp**

### CODE REVIEW

**Comment by SamHPurp** [comment]
What the fuck is this

**Comment by TullyBurnalot** [comment]
@SamHPurp We may or may not have created a sentient AI that keep contaminating other PRs.

Nothing to worry about, though, it's totally not out of control or anything.

**Comment by SamHPurp** [comment]
@TullyBurnalot if you didn't want me doing PRs anymore

All you had to do was ask

**Comment by TullyBurnalot** [comment]
@SamHPurp I wasn't kidding.

We actually have a bit of a problem with rogue commits right now. This ain't on you.

**Comment by SamHPurp** [comment]
@TullyBurnalot sorry Tully, I missed my `</s>` tag. :)

**Comment by TullyBurnalot** [comment]
@SamHPurp I'd honestly recommend re-opening this as another PR, see if the issue persists. If it does, well, not much we can do except manually unfuck it.

**Pull request closed without merging**
