### PR TITLE
Adds SSD warning pop-up on stripping items

### PR DESCRIPTION
**Pull request by datlo**
If the player you're stripping is SSD, you will now get a pop-up warning telling you to ahelp before doing so. This can be disabled by a config option.

You can either cancel (default option), or acknowledge the warning. You will not strip the item in either case. 

Once acknowledged, admins get a message informing them with a FLW link to jump, and you may now proceed with stripping the SSD player (and get :hammer: if you're not actually permitted to do so)

You will have this pop-up for every SSD player you try to strip.

If an SSD player comes back online, the warning is reset for that mob, and you'll get the pop-up again if you try to strip them.

The pop-up : 

ssdwarning

Message sent to admins : 

ssdwarning

🆑
add: Added a warning pop-up when you try to strip an SSD player.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
This feature (and the content of the pop-up warning) was requested by Spartan.

**Comment by Citinited** [comment]
Hmm. Shouldn't the buttons be the other way round? I know why they're like that for stuff like antag popups, but accidentally pressing space shouldn't be an issue here

**Comment by FalseIncarnate** [comment]
This seems rather annoying for medical and security who might be handling someone who went SSD during surgery (or needs immediate attention to save) or a brig sentence. While these are definitely less an issue than a random civ stripping an SSD in the halls, I feel this still is worth pointing out.

Acknowledging it requiring you then initiate a new strip just feels like wasting time when someone has essentially said they already are aware of what they are doing. The warning and ability to cancel is nice though.

**Comment by TDSSS** [comment]
Will this potentially be an issue with downstreams that have more lax rules around SSDs or something? I mean they can always revert the change but I've seen other PRs add config options for that kind of stuff.

**Comment by Spartan6** [comment]
@FalseIncarnate It's not requiring you to close the menu and re-open the strip menu, it's just requiring you to click the same item again. You can still strip in the same 'session'.

@TDSSS Probably a good idea.

**Comment by FalseIncarnate** [comment]
I wasn’t suggesting it closed the window, just that it was taking extra time for something that might not necessarily be subject to the rule it is enforcing. At least it doesn’t make them sit through the strip delay before the message, so it isn’t wasting a ton of time, but is still wasting some

**Comment by Citinited** [comment]
> Was requested to be that way so pressing space to dismiss the pop-up will not acknowledge it.

I'm just worried that this will become the norm for all in-game popups (having the buttons flipped), which is counterintuitive to anyone who's used a GUI in the past.

**Comment by datlo** [comment]
Added a config option to disable the SSD warning popup

**Comment by Ty-Omaha** [comment]
I mean, if people hit space / enter on a popup that they didn't read it's entirely their own fault

**Comment by Ty-Omaha** [comment]
>In a potentially fast-paced game where you dont get the luxury of having everyone and everything going on around you pause because you're reading a prompt that you cant ignore....i'd say it's not always entirely their fault if they dont want to be caught in the crossfire of something and ignore the message.

If they're in the middle of a shootout stripping an SSD person they'll have to spend more time clicking the right button for the action to actually go through, which is actually counter intuitive to the point you are trying to make

**Comment by Bram961** [comment]
Don't exactly like the current iteration here.

I've been playing this game for years, I don't want to be told and hit extra buttons when stripping an SSD. I've spent enough time here to asses wether or not someone is SSD and examine when in doubt.

I would be all for it if it was a preference option I could just turn off myself.

**Comment by KasparoVy** [comment]
Or just have it disable, SQL-tracked based on how many times you acknowledge it. 5-10 acknowledgements = you won't see it again

*shrug*

**Comment by Pixelzilla** [comment]
> 
> 
> > In a potentially fast-paced game where you dont get the luxury of having everyone and everything going on around you pause because you're reading a prompt that you cant ignore....i'd say it's not always entirely their fault if they dont want to be caught in the crossfire of something and ignore the message.
> 
> If they're in the middle of a shootout stripping an SSD person they'll have to spend more time clicking the right button for the action to actually go through, which is counter intuitive to the point you are trying to make. Not to mention to strip something from someone you'd have to stand still in a spot anyways and wait for the strip timer
> 
> And still. It is their fault. If there is a prompt and they hit yes that's their fault for not reading it. They said they read it. If they didn't - then that's on them.

The point i'm trying to make is that adding extra steps and hoops to jump through ruins immersion and punishes people who likely already know the rules. There are plenty of situations where precious seconds might mean you save someone and it's annoying when that time is wasted with prompts that do not need to exist. The people who do not know about stripping SSD  are likely not the ones that are going to be hindered by a confirmation message that they can apparently dismiss easily. If someone didn't take the time to read the rules they're not likely going to take the time to read a confirmation message. It isn't going to change anything in a positive way.

**Comment by variableundefined** [comment]
I echo the points above, this penalize players who already know the rules in favour of giving them a warning.

A compromise I can accept is to limit this to players with 10 - 20 hours or less or playtime because otherwise you'll just annoy 95% of the playerbase who already know it.

**Comment by datlo** [comment]
I'll add a playtime limit with a config option to how many hours, I'll let you know when I get around to it.

**Comment by datlo** [comment]
Closing this because database stuff gives me a headache. If somebody wants to take this code and add a check for playtime as suggested by ansari, feel free to do so.

**Pull request closed without merging**
