### PR TITLE
Shows shock and cardiac failure as medical emergency instead of viral pathogen in body scanner and pandemic

### PR DESCRIPTION
**Pull request by tiggypuff**
## What Does This PR Do
During a round it was noticed that the medical conditions shock and cardiac failure show up as a viral pathogen in the body scanner and the Pandemic. This is due to them internally being handled as diseases, which allows them to reuse code.
This PR changes the behaviour of the body scanner and the Pandemic so they no longer detect shock and cardiac failure as diseases. Instead the body scanner will report shock and cardiac failure as Medical Emergencies in the UI and the printout.

Also, the PR fixes several issues with the body scanner printout where line breaks were ignored.

## Why It's Good For The Game
Shock and cardiac failure are only for technical reasons diseases, and therefore shouldn't be erroneously detected as viral pathogens. Doing so could confuse players and cause them to waste time investigating the virus. Showing a more accurate message about a medical emergency  can aid inexperienced players in taking the necessary steps to heal a patient.

## Images of changes
Body scanner UI with message about a medical emergency
bodyscanner

Fixed body scanner printout formatting. The reported disease is an actual disease.
printout

## Changelog
:cl:
fix: Shock and cardiac arrest will no longer by reported as viruses
tweak: Diseases can be flagged as medical emergencies and will be shown as such in the body scanner
fix: fixed some formatting issues in the body scanner printout
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
making an entire disease flags (which largely exist to govern behavior of how diseases operate) is not the appropriate way of handling this. 

There's very specifically a var that relates to what kind of disease a disease datum is; that should be used and not this method; what exists here is really gross.

**Comment by datlo** [comment]
Arent crit-related diseases their own subtypes? Why not just check for those?

**Comment by tiggypuff** [comment]
Thank you for your comments. I'm new to the codebase, and as such have only limited knowledge about it. This is why I also depend on getting useful feedback.
It was nice telling me that there is a variable better suited for the task, however, in my opinion it was not as nice not telling me what the name of the variable and instead calling my solution gross. It was rather off-putting.
But again, thank you for your input. I've removed the flag, and changed the checks to use the form var.

**Comment by Fox-McCloud** [comment]
Very stale and not updated, despite requests. Closing.

**Comment by tiggypuff** [comment]
Requested update was commited on 2020-02-22.
See https://github.com/ParadiseSS13/Paradise/pull/13011/commits/27e982906426d4fe33b37c1dc378a91754e8deba and https://github.com/ParadiseSS13/Paradise/pull/13011/commits/b9707138909855d7fd50a017175915358af8c005

**Pull request closed without merging**
