### PR TITLE
Adds Telescience lab

### PR DESCRIPTION
**Pull request by Norgad**
*some assembly required

2016-07-27 21_23_43-greenshot

:cl: Norgad
add: Added an area in science for telescience (or whatever) to be built
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This was tried before and turned down.

**Comment by TheBeoni** [comment]
I actualy like it. You got YUP frome.

**Comment by Norgad** [comment]
@Fox-McCloud Wasn't it turned down because they had glass leading directly into maint?

**Comment by Fox-McCloud** [comment]
>@Fox-McCloud Wasn't it turned down because they had glass leading directly into maint?

Not at all.

**Comment by Norgad** [comment]
@Fox-McCloud Could you actually be not-vague then and tell me the reasons then?

**Comment by Da-Dman234** [comment]
As someone who only plays scientist I have only two things I hate, the EXPERIMENTOR and Telescience. 

I feel telescience is in a good state as is, and I certainly feel we shouldn't have any room dedicated to it. As of right now it's forced to be built in a cramped, unsecure area that's usually right in the public's eye, or atleast at a workstation in science which gives it atleast SOME downside/danger if you incorrectly use it; even then the risk is basically nil. 

All opening up a free room would do for science is encourage people to build every powerful machine they can. I have no doubt that room would turn into it's own medbay/telesci powergaming circlejerk by the end of every shift.

**Comment by Norgad** [comment]
@Da-Dman234 Thanks for view on that, that's actually quite helpful.

**Comment by Rumiluntti** [comment]
Science doesn't need anything made any easier.

**Comment by Belario** [comment]
This is something that actually gets build almost tile for tile in any shift science feel like being constructive in.

:-1:  no reason to make it any easier.

**Comment by monster860** [comment]
It's a fucking EMPTY ROOM. What is your problem? All this is about is making shit not look ghetto.
===

**Comment by fludd12** [comment]
I understand concerns about making science more powerful...

But seriously guys, it's literally an empty room.
An empty room that might, possibly be used for telescience?
Even though, most of the time, they just put telescience in R&D anyway.

Unless unbalanced power is decided by how much of the stations turf a department takes up, I'd say this won't make science any more powerful or any easier.

**Comment by tigercat2000** [comment]
I don't really see a point in adding a random empty room to science, especially for machinery that we want built **less**. 
It's also inconsistent with every other "building area" of the station, because it has a fully functional APC and tiling. 

Also, walls bordering space need to be reinforced walls on Cyberiad.

**Comment by Belario** [comment]
@monster860 Because if science wants telesci they can build themselves a telesci without great difficulty.
There's no point hugboxing it for them.

**Comment by Dinarzad** [comment]
@Belario It is not even slightly like either of those things. An Empty room does not even partially equate to "Why don't we just pre-build the engine and give Sec an armor of mechs!"

This is more like protesting Engineering should have the construction room removed, because it's OP/hugbox that they don't have to build a new room to construct stuff in.
Science still has to research Telesci, it still has to build telesci. The only difference is, there is a dedicated spot for Science to build shit. Shit they can ALREADY build at no effort.
Everyone in here seems to think this is "Making science easy! no hugbox!"
They already just toss everything down in the hallways or in RnD, few people bother to deconstruct the Experimentor, they just throw it on the fuckin floor.

Science doesn't need buffs or power creep but **it's just an empty fucking construction room**, Sweet jesus.

**Comment by tigercat2000** [comment]
it's silly to argue this is hugboxing science
but it's not silly to argue that this is completely unnecessary and, worse, inconsistent with the idea of `construction area`s
even on metastation, anything that is supposed to be construction has no plating and is a bit scuffed up

**Comment by Norgad** [comment]
@tigercat2000 

2016-07-28 16_10_50-greenshot

**Comment by FreeStylaLT** [comment]
If it's an empty room, why does it have to exist

**Comment by monster860** [comment]
Same reason every other empty room in this game exists.

**Comment by Fox-McCloud** [comment]
This is pretty much the same PR as was previously attempted with very similar reactions to it. As such, I will be closing this--science already has plenty of space to build a telesci lab.

**Pull request closed without merging**
