### PR TITLE
IPC Feet sprite

### PR DESCRIPTION
**Pull request by orelbon**
ipc feet

Deletes one pixel that bulges out of shoes.

### CODE REVIEW

**Comment by tigercat2000** [comment]
That one pixel actually looks pretty good when not wearing shoes. Eh, whatever.

**Comment by orelbon** [comment]
@tigercat2000 when do you see a shoeless IPC

**Comment by Spacemanspark** [comment]
@orelbon 
Pretty often, actually.

**Comment by orelbon** [comment]
@Spacemanspark i have never really seen a barefoot ipc.

**Comment by NTSAM** [comment]
I constantly lose my foot :(

**Pull request merged**
