### PR TITLE
Adds genderless as a gender option for all races

### PR DESCRIPTION
**Pull request by Daylight2**
## What Does This PR Do
Adds genderless as a gender option for all races, and removes some checks that forced most species to be male/female only

## Why It's Good For The Game
This was requested in [on the forums](url), as well as by a friend of mine. Allowing non-binary people to more freely express themselves in game seems good.

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/18598676/4f6a181c-fb31-46e7-897c-34918e39e49c

## Testing
Spawned in as genderless.

## Changelog
:cl:
tweak: All races can be genderless now.
/:cl:

### CODE REVIEW

**Comment by SynthTwo** [comment]
LET'S TRY THIS AGAIN BABY!!

**Comment by Henri215** [comment]
If you wanna do this then do like https://github.com/ParadiseSS13/Paradise/pull/16007 did, by having a body and gender options.
Doing like this you are going to:
1. Remove flavor from some species, that have the characteristic of their body not having a defined sex.
2. Break the NT Recruiter arcade, since all species could be genderless that check would always be true, thus making the chance for the "HIRE" option to be the correct one more often.

**Comment by Daylight2** [comment]
> If you wanna do this then do like #16007 did, by having a body and gender options. Doing like this you are going to:
> 
>     1. Remove flavor from some species, that have the characteristic of their body not having a defined sex.
> 
>     2. Break the NT Recruiter arcade, since all species could be genderless that check would always be true, thus making the chance for the "HIRE" option to be the correct one more often.

I just looked into that PR, and yeah, it does this way better than what I'm doing right now. It's also 
a) absolutely massive, at least compared to what I'm used to working with. It seems like I can copy paste almost all of this, since it had no open code conversations, but I'm definitely not a big enough expert on DM to verify that everything works as intended, and
b) making changes to TGUI, which is frozen right now. 

I can make an effort to port that PR over verbatim whilst fixing things that have changed since 2021 once the freeze is over, but until then, what I have right now should work as just a quick button to change what your gender is displayed as.

**Comment by Coolrune206** [comment]
My perspective on our playerbase has shifted to the point I think we could probably have this without too much trolling.

That said, proper implementation is probably important, so I'll ask:
Does this use a specific spriteset by default or does it pick randomly? If so, it may be worth implementing a body and gender option instead of merging them together to give players more control. It would also allow the examine function to continue displaying strictly observable information while allowing for records to support a character's identity.

**Comment by PopGamer45** [comment]
> That said, proper implementation is probably important, so I'll ask: Does this use a specific spriteset by default or does it pick randomly? Either way, it may be worth implementing a body and gender option instead of merging them together to give players more control. It would also allow the examine function to continue displaying strictly observable information while allowing for records to support a character's identity.

Personally i feel like the gender option should be displayed atleast somehow in the examine, if the gender option is only gonna show up in records then the players who´s characters are gonna have a different gender option than the body option are gonna have to constantly correct other players. I think maybe the gender option should be displayed in the examine when you are wearing your id, like your characters gender option is gonna be on your id too instead of just in records and when you wear it its gonna use that in the examine instead

**Comment by Coolrune206** [comment]
> I think maybe the gender option should be displayed in the examine when you are wearing your id, like your characters gender option is gonna be on your id too instead of just in records and when you wear it its gonna use that in the examine instead

I like this idea, not just for this specific PR but also overall - perhaps by examining someone near to them while they're wearing their ID you could look at the details of it, instead of having to take it off to do. Kinda makes sense.

**Review by lewcc — CHANGES_REQUESTED** [review]
This has been sitting without updates for a while -- continuing what I said earlier, I think this needs to incorporate some of the larger changes for it to be mergeable. 

Again, please reach out if you need help with this.

**Comment by Daylight2** [comment]
I got a bit busy recently, and lewcc kindly offered to take over! Go check out #23910 for his version

**Pull request closed without merging**
