### PR TITLE
ERT Rework

### PR DESCRIPTION
**Pull request by SamCroswell**
Changes:

 - Change how ERT deployment works, now you pick your class as you are spawned, and are instantly geared up for that class. My thanks to /TG/, I used and modified their ERT gear up proc for this purpose.

 - Remap ERT armory. All additional gear is now behind blast doors that must be admin-opened.

 - Add support for different kinds of RCD ammo and different RCD capacities.

 - Add the 'Combat RCD', an RCD with a matter capacity of 500. Engineering Response Team members have these.

 - Add 'Nanites'. (No, not the kind that borg people.) These are a child of admorinazine, and act in the same manner.

 - Add the nanite Combat Hypospray. This is a hypospray that contains nanites. These hyposprays are in the medical ERT armory, and admin action is needed for them to be able to acquire them.

- Add two new pulse weapons: The Carbine and Pistol. They both function in a similar manner to the pulse rifle, but at a much lower power cell capacity.

- Re-icons all pulse weaponry, as seen below:

rifle

carbine

pistol

- Add two new cells for exclusive use in the pulse pistol and carbine.

- Add the 'Response Team' security belt. This belt comes equipped with two flashbangs, a telebaton, a seclite, and a pair of handcuffs. The ERT lead and ERT security officers come equipped with these.

 - Change ERT unit spawn landmarks - They now spawn on the 'Response Team' landmark as opposed to the 'Commando' landmark. I believe this was causing issues with DeathSquad deployment, as the ERT delete the landmarks after they spawn.

 - Remove the ability for the user to customize their ERT's name and appearance. This is to speed up ERT response times, and to prevent people from claiming 'They're from CentComm' by making their character an ERT member.

The remapped Specops room, for reference:

new ert

### CODE REVIEW

**Comment by SamCroswell** [comment]
This PR /should/ be good to go, but I've still got local testing to do. I expect to be able to remove the do not merge soon.

**Comment by Earthdivine** [comment]
Removing the ERT's customize able name seems to be a bad thing to do, I don't see people trying it at all and a lot of players have ERT exclusive characters, myself included.

Do the ERT also get the Pulse weapons? If they do, isn't that a bit much giving them the Deathsquads signature weapon but on a smaller scale?

**Comment by tigercat2000** [comment]
I agree with EarthDivine, I don't think the customizable names and appearances should be removed.

**Comment by SamCroswell** [comment]
Alright, preliminary testing is done. No major bugs spotted. I'll continue testing, but this should be safe to merge once the time limit is up.

**Comment by SamCroswell** [comment]
Regarding the removal of customization:

The less persistence between ERT and crew the better, in my opinion. While it doesn't happen often, I do see it happening, and I do believe that not being one of your own special characters when being in the response team tends to encourage players to do their jobs rather than metabuddy from CentComm.

This is the same reason that Nuke Ops characters, and why DeathSquad characters aren't able to be customized.

**Comment by tigercat2000** [comment]
Last time I checked, Nuke Ops characters just pulls the appearance from your selected character slot, unless it was changed.

**Comment by SamCroswell** [comment]
That was changed. For this specific reason.

**Comment by ZomgPonies** [comment]
I agree with the removal of ERT customization. It adds huge delays to them actually becoming useful to the station. Be a special snowflake on your main, not event characters that have important missions.

**Comment by Spacemanspark** [comment]
I'll raise the same issue I had when /tg/ made this:
Why do they have freaking pulse weaponry?
I'd like to keep the customization capability, but that's likely not going to happen.

**Comment by Spacemanspark** [comment]
Can't edit my posts via mobile, dammit.
I'd make a poll on the forums, and ask what the community wants.
Prayfully it isn't HOLY FUCK PULSE WEAPONRY YA SHOOT EVERYTHING.

**Comment by SamCroswell** [comment]
The pulse rifle has a cell capacity of 20000, and as such can burn through 100 pulse rounds or 200 lasers before it needs to be recharged.

In comparison, the pulse carbine has a cell capacity of 5000 (And I'm partial to lowering this number even more)
That's 25 pulse shots or 50 lasers before it needs to be recharged.

The pulse pistol has a total of 10 pulse shots or 20 lasers before it needs to be recharged at a cell rating of 2000.

I would argue that the OP nature of the pulse rifle comes not from the ability to have a pulse setting, but because it can fire so many rounds of pulse shot before it even comes remotely close to needing a recharge. (In addition to the DS having unarguably the best armor in the game)

I'm not claiming that these weapons aren't going to be powerful, but the Syndicate LMG the ERT currently have access to under the same circumstances is harder to dodge, does more damage, holds more shots than the carbine, and doesn't require access to a recharger to be reloaded. The only difference is the LMG doesn't break walls, and the ERT is supplied with plenty of plastic explosives to do that currently.

**Comment by Spacemanspark** [comment]
The LMG is rarely used, since it's locked in the secure armoury.
Pulse weaponry is STILL op, especially since the purpose of ERT is /not/ to shoot shit up (well, not shoot everything up.), but, rather, to assist the station.
I would just stick to energy guns. That's all the firepower they need.

**Comment by SamCroswell** [comment]
Once again:

The pulse weapons are locked in a secure armory as well. There are blast doors behind the regular doors in each of the 3x3 rooms. ERT CANNOT access them by default.

**Comment by Markolie** [comment]
:thumbsdown: To the map change. You should never have to walk over a chair to get to a different place in the same room. I'd say expand the room south and west by two tiles and ensure there's one free tile around the entire table.

The starting equipment needs to have the PDA's re-added (see the old code), as those allowed the crew to privately contact the ERT. The starting equipment also lacks extended double capacity extended oxygen tanks that are vital to ERT operations (these should start 100% full). I'd personally also prefer them to spawn with night vision goggles, as these allow them to properly combat nuke ops and Xenos, who already have a huge advantage over the ERT.

Regarding the equipment in the starting rooms: I presume there's six of each in every stack? Otherwise, ERT will have to fight over who gets certain equipment. Aside from that, I can't say I entirely agree with some of the equipment in these rooms (a hand teleporter?) but we can re-balance that once the change is live.

Ideally, we'd let the heads of staff or the admin calling the team pick which equipment will be available to the ERT, and only when the equipment was selected by the heads of staff/admin the ERT will be able to pick that equipment from the list. Ideally, in that case we'd also have the janitorial ERT added. That's probably for a later PR though, and I can look into implementing that once this is live.

Aside from this feedback (once it's implemented), :thumbsup:.

**Comment by SamCroswell** [comment]
There are two of each in every stack, except for the commander's room which contains only one item in each stack. This is because each door has a separate access requirement unique to each ERT class's assigned ID, and as such only that class should be going in there to retrieve gear. I'm OK with there being a shortage of advanced gear on the team if all six members decide to spec into security. I'd consider adding one more to each pile to have a total of 3 sets of gear in each secure armory, but any more and I fear we'll encourage people to just grab everything from every class's armory.

I'll look into having the PDAs re-added, and change their oxygen tanks from extended to double-extended.

As for the map changes -- What if I removed the chairs instead? I don't want the operations room to get bloated, and I fear that's what will happen if I expand it like you suggested.

**Comment by Markolie** [comment]
Ahh, I thought you could only access those rooms if the admins let you. If they can open it based on their ID, I guess it'll work.

As for the mapping change, I'm fine with that.

**Comment by SamCroswell** [comment]
I feel like I'm not clarifying how the armory is accessed, so I'll try to do it from scratch:

In the doorway to the 3x3 armory rooms, there are two doors.

The black airlocks are ID-locked, and only the ERT member from that class can open them.
Underneath the black airlocks there are blast doors, which are un-openable without admin intervention.

**Comment by Markolie** [comment]
I think removing the chairs would be a good solution as well. Not like anyone ever uses them.

**Comment by SamCroswell** [comment]
The map on the PR description has been updated to reflect the lack of chairs.

**Comment by IDTia** [comment]
The way it currently looks feels really constricted in the picture as of posting this. Going to be a lot of pushing and shoving. Table is too big and having the map just takes up more space. (Functionality wise, if you are signing up to be ERT, you should know the station layout) 

As for ID restricting the doors, that's going to end up with even more time wasted, as people are going to be asking for the doors to be opened so they can grab other additional equipment, (Jetpacks from engineering, medkit/cryobag from medical, a gun from security) 

IMHO all ERT members should have a way of defending themselves. (Spiders and blob zombies come to mind as a reason everyone should have at least an energy gun)

Lastly, at least keep the ability to pick your own name, it just makes it a bit easier on communication. Picking your skin color, hair, eye color, all that jazz, that I would be more alright with restricting. It is covered by your sit already, and the only time you are without your suit is when the clown is taking if off your headless corpse.

**Comment by Fox-McCloud** [comment]
@IDTia 

Not picking your own name is intentional and it really needs to go; people who play as their station characters as ERT is self-aggrandizing as hell and doesn't make sense the vast bulk of the time.

Nukies don't really have a problem with communication--why? They have their own special channel; so do ERT members.

**Comment by IDTia** [comment]
Nukies have their own channel, only have to communicate with their own people, and usually have time to familiarize themselves with everyone. They can also change their ID to whatever name they want.
ERT members have to communicate with the heads of staff and anyone tagging along. They should ideally be picking codenames from the NATO Phonetic alphabet, not using an actual first name last name.

**Comment by fj45** [comment]
How hard would it be to just have the ERT get random words from the NATO Phonetic alphabet? Seems like it would solve a good deal of issues.


The table is awesome but it really needs more room around it. Should be atleast two tiles on every side.

For everything but the commanders room, just remove the doors and have the tables far more open. Currently it seems like gearing up would be a complete mess, plus with smaller ERT teams or during high combat missions, having gear locked away would cause massive issues.


ERT also need a supply of atmos equipment and assorted heavier stuff. Maybe wouldn't hurt to put the tool machine back somewhere as well.

**Comment by ZomgPonies** [comment]
Bring up your snowflake justification on the forums. For now I think it's worth testing if this revision of ERT improves the event and makes them more useful.

**Pull request merged**
