### PR TITLE
New Rollerbed Sprites

### PR DESCRIPTION
**Pull request by TrashDoxx**
**Original PR:** https://github.com/Baystation12/Baystation12/pull/31914

## What Does This PR Do
• I just updated the rollerbed sprites but didn't add hand sprites cause I'm lazy, there weren't any anyway as I can see.

## Why It's Good For The Game
• think the new sprites are more stylish and interesting.

## Images of changes
• Look at IconDiff or original PR.

**UPD:**
image

## Testing
• Just runned local server & checked new sprites.

## Changelog
:cl:
imageadd: Added new rollerbed sprites
imagedel: Deleted old rollerbed sprites
/:cl:

### CODE REVIEW

**Comment by TrashDoxx** [comment]
wherrea my soUUL??!

**Comment by McRamon** [comment]
why can't you simply include image in the pr so people dotn have to go around links? its a 2-second task

**Comment by TrashDoxx** [comment]
idk.

**Comment by S34NW** [comment]
The image was even right ther ein the bay PR for you to steal when you made this one 😞

**Comment by matttheficus** [comment]
Neat sprite, should be in the PR description as said above.

**Comment by Denthamos** [comment]
> idk.

@TrashDoxx 
Not an attitude I appreciate nor will it be accepted here on Paradise or its github.  Follow the wiki instructions for coders and properly detail your PR's here or do not trouble us with your PR's.

**Comment by TrashDoxx** [comment]
> > idk.
> 
> @TrashDoxx Not an attitude I appreciate nor will it be accepted here on Paradise or its github. Follow the wiki instructions for coders and properly detail your PR's here or do not trouble us with your PR's.

ok.

**Comment by matttheficus** [comment]
Additionally, there should really be a sprite shown for when a person is on the bed as well, since that'll be its main show.

**Comment by Bm0n** [comment]
the rollerbed icons exist in bays right/left hand.dmi folder. called "rbed"

**Comment by TrashDoxx** [comment]
ok, I'll finish my work when I get home cause I've been in another city without access to a computer for the last couple of days.

**Comment by Carthusia** [comment]
I like them, though feel the color isnt quite right.

Its meant to be a medical stretcher bed, which generally are in blue or white colors to allow for easy spotting of filth. Black just makes it look like it should be in the morgue...which theres an idea.

This colorscheme for a morgue rollerbed, while the other is the usual white or blue colorscheme

**Comment by TrashDoxx** [comment]
oh hi there.

**Comment by TrashDoxx** [comment]
> This colorscheme for a morgue rollerbed, while the other is the usual white or blue colorscheme

is an interesting idea.

**Comment by McRamon** [comment]
Agree with Carth, it doesnt really feel like part of the retrofuturistic medbay on space station. Could work as morgue bed (though without this white stripe in the middle), but for general medbay they should be white and clean.
Quality wise the sprite is good, the colors just need to be changed

**Review by Sirryan2002 — CHANGES_REQUESTED** [review]
I will leave an approval on this is Ramon's requests are fulfilled

**Comment by hal9000PR** [comment]
Over 3 weeks no response to requested changes. Closing

**Pull request closed without merging**
