### PR TITLE
Grab Fix

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes hotkeys not working for grabs.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Wait so if we press Z (Or CTRL + Z, for unrobust scrubs.), we'll now tighten our grip?

**Comment by Fox-McCloud** [comment]
Not positive if it works with alternate hotkeys, but it works with standard.

**Comment by tigercat2000** [comment]
pretty sure this was intentional, to make tabling a bit harder

**Comment by Fox-McCloud** [comment]
It's a bug: https://github.com/tgstation/-tg-station/issues/7130

The traditional shortcut also works on Goon.

**Comment by Spacemanspark** [comment]
We really should find a way to prevent permatabling.

**Pull request merged**
