### PR TITLE
Removes red crosses from doctor's delight drink sprite

### PR DESCRIPTION
**Pull request by AzuleUtama**
## What Does This PR Do
Updates the sprite for the doctor's delight drink to have purple crosses rather than red.

## Why It's Good For The Game
We had a PR some time ago to remove all red crosses in the game files, this is an extension of that.

## Images of changes
image

ddredone

## Changelog
:cl:
imageadd: Reworked doctor's delight sprite
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
less war crimes

**Comment by Cocacolagua** [comment]
i'm not really sure the warcrime applies here but whatever

**Comment by procdrone** [comment]
damn i liked committing war crimes with my dietary drinks. Duh!

**Comment by AffectedArc07** [comment]
The war crimes only apply when its being associated with a medical area. Having a red + itself is fine, just not if you associate it with medical things.

**Comment by Wojz** [comment]
change taste to warcrimes

**Comment by AzuleUtama** [comment]
> The war crimes only apply when its being associated with a medical area. Having a red + itself is fine, just not if you associate it with medical things.

Yeah I wasn't completely sure on whether it was needed, but given the name of said item and the fact it heals toxin damage I figured it was better safe than sorry.

**Comment by Sirryan2002** [comment]
I think this is a good sprite change anyway, if people prefer this over the other one, I say go ahead.

**Review by dearmochi — APPROVED** [review]

**Review by Kyep — APPROVED** [review]

**Comment by AffectedArc07** [comment]
Mistake?
image

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
You removed a sprite thats still in use
image

**Comment by AzuleUtama** [comment]
Yeah sorry, that's been resolved and should now be back in the drinks.dmi file.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
