### PR TITLE
Refactors say code

### PR DESCRIPTION
**Pull request by alexkar598**
💯 % legit

not meme

### CODE REVIEW

**Comment by Birdtalon** [comment]
Low effort 👎

**Comment by Citinited** [comment]
This isn't how you do meme PRs

**Comment by FlattestGuitar** [comment]
rip @alexkar598. I usually don't stick around this git, but this one really is low-effort. I'm sorry.

🕯 🕯 🕯 🕯 🕯 🕯

**Comment by Aurorablade** [comment]
Can you not do this shit?

**Comment by alexkar598** [comment]
im sorry ;,(

**Pull request closed without merging**
