### PR TITLE
Spesspod Mining Laser - "Fuck You Git" edition

### PR DESCRIPTION
**Pull request by monster860**
Fox has asked me to squash all the commits of #3772 into one and create a new PR. 

Map edit:

Spesspod Pod Bay

:cl: monster860
rscadd: Mining station now has a podbay.
rscadd: Ore scooping module for the spacepod.
rscadd: Three mining lasers for spacepod: Basic, normal, and burst.
bugfix: Shooting weapons south or west of spacepod will actually hit adjacent targets now, and won't shoot through walls anymore.
/:cl:

### CODE REVIEW

**Comment by Kevak** [comment]
I approve. Gives the mechanic something to do when he gets bored.

**Comment by monster860** [comment]
Could someone give me a quick guide to resolve this merge conflict with mapmerge?

**Comment by TullyBurnalot** [comment]
More love for the mechanic AND a cool way to mine.

:+1:

**Comment by monster860** [comment]
Merge conflicts fixed

**Pull request merged**
