### PR TITLE
Locks the bluespace wormhole generator

### PR DESCRIPTION
**Pull request by Regen1**
It's too powerful, serving as a master key to any room with windows, and
does damage when you hit other people, so a potential lethal weapon.

Just a personal opinion, might be controversial, but hey its a proposed change.

### CODE REVIEW

**Comment by fludd12** [comment]
If you could, maybe lock it to RD access? It's not exactly a very lethal weapon, but I agree that at least one Command member should be in on it.

**Comment by Regen1** [comment]
I wouldn't know how to do that, it would need some snowflake coding, making a new type of lockbox or something.
Perhaps @tigercat2000 has an idea.

**Comment by DaveTheHeadcrab** [comment]
:+1: 
It's a fun weapon, but I see it abused way too often to not be in a lockbox.

**Comment by Crazylemon64** [comment]
First, you'll want to add a field to the <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/research/designs.dm#L36>design datum</a> which will be a list of IDs that will unlock the design.

Once that's done, in rdconsole.dm, <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/research/rdconsole.dm#L425>here</a> you'll want to, in the portion of code where the lockbox is added, you'll want to set the lockbox's "req_access" list to that of the design datum. Once you've done that, it should have the custom permissions you want. @Regen1

**Comment by Earthdivine** [comment]
As I am sad to see things get locked behind Lockboxes, what about not letting it pass through Grilles and/or Reinforced glass (Since it's made with metal). This would probably solve the B&E issue without resorting to the lockbox?

**Comment by Regen1** [comment]
@Earthdivne I would rather limit access than limit functionality

**Comment by Robertha89** [comment]
Doesn't it do like 3 damage? Less then a punch... make it behind bridge acess instead. Inly two people with rd acess.

**Comment by Spacemanspark** [comment]
I'd rather just see it do no damage to someone, honestly.
Maybe have it on a cooldown.

**Comment by Regen1** [comment]
Fuck that, damage or no damage its still a master key to 90% of the station being abused to no end, I'll look at locking it to RD only, because that's who it is made for, not the blueshield or HoS.

**Comment by Regen1** [comment]
@Crazylemon64 Could you come on the IRC to guide me a bit on your suggestion?

**Comment by Fox-McCloud** [comment]
https://github.com/ParadiseSS13/Paradise/pull/2980

**Pull request closed without merging**
