### PR TITLE
Directional APC/Air Alarm/Intercom/Fire Alarm

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Ports Bay's sprites for APCs, Air alarms, Intercoms, and Fire Alarms
Remaps and adds a script to move all existing standard placements of these objects to properly sit on a wall with a direction.

Note: Custom placement APC/Air Alarm/Intercom/Fire Alarm objects will not be caught by this script and will require a follow-up PR to correct, this is especially so with intercoms and they are all over the place when it comes to placement.

## Why It's Good For The Game
Since we got wall sprite with slants, our wall furniture has started to look really strange.
This ports decent looking sprites that support directionality on slanted wall sprites. Eris and a few others do something similar but their style for these objects is not suitable with the rest of our sprites.

## Images of changes
image

## Changelog
:cl:
tweak: Ported directional bay sprites for APC/Air Alarm/Intercom/Fire Alarm
/:cl:

### CODE REVIEW

**Comment by Inadvizable** [comment]
Oooh, these look real pretty. And it's way more clear which side of the wall they're on.

**Comment by GDNgit** [comment]
Although these sprites are very pretty, they really suffer from readability issues

Pretty much every sprite in this image looks to some extent, extremely similar. This is a bad thing if you're running through a hallway and can't see the difference between a newscaster and an APC. 

APCs- Both blend into the wall and stick out, it's also just my opinion but it's got a really ugly shade of red on it, and when it meshes with the yellow it looks like something you would see when the APC is emmaged, not just lacking charging. It also seems to stick out a lot less in the dark than the current APC sprite. 

Air alarms- The alarms themselves alright, but the lack of the AIR on them just makes me sad really, still decently readable, but it's likely gonna take longer to understand what they are to a new player.

Fire alarm- The sideways sprite is very, very flat, and to someone without 20/20 eyesight I can see people easily missing it, outside of that the alert level color is very small and hard to look at for an extended period of time.

Intercom- I thought these were newscasters, these don't look like intercoms at all. If you are going to alert any sprites, please add a more obvious speaker section, because these are not readable at all.

Still good-looking sprites, but they're hard to interpret

**Comment by S34NW** [comment]
Will be back once other, better, sprites can be found

**Comment by Bm0n** [comment]
NO WAIT I NEEDED THESE FOR FOR MY BAY WALLS

**Pull request closed without merging**
