### PR TITLE
*squish emote for Slime People.

### PR DESCRIPTION
**Pull request by tigercat2000**
-Credit to DrMinky(Freesound.org) for the sound

Adds the emote *squish for slime people, which can either have a parameter for squishing at someone, or just squishing.

EX:
Squishy Larkens squishes.
Squishy Larkens squishes at Fox McCloud.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
We really need a cooldown system for emotes.

**Comment by tigercat2000** [comment]
Placing a DNM on this until have worked out some overhead things with FalseIncarnate.

**Comment by Fox-McCloud** [comment]
Fox McCloud screams!

**Comment by FalseIncarnate** [comment]
The overhead stuff Tiger mentioned is the Emote Cooldown System. This pretty much only affects sound-playing emotes like scream to avoid people spamming the emote. This is being delayed by other PRs also editing the emote files, but should hopefully be up shortly after #396 is merged.

**Pull request closed without merging**
