### PR TITLE
[DELTA] Atmos Remap Revival

### PR DESCRIPTION
**Pull request by Oyu07**
## What Does This PR Do

Revives https://github.com/ParadiseSS13/Paradise/pull/22987
Read that pr for description

No big changes
Reviews + Fixes

## Why It's Good For The Game

Current kerberos atmos has incredible small usable space to pipe around for custom setups, also in general very annoying.
Check the linked PR description for more details

## Images of changes

More on the linked PR

<details>
<summary>Atmos and Turbine room</summary>

image

image

</details>

## Testing

Checked wiring and piping
~~Opening as draft while I double check any APC, fire alarm etc.
CI should give me an idea of missing / duplicate pipes etc.~~

CI checks

## Changelog
:cl:
tweak: [DELTA / KERBEROS] Atmos Remap
/:cl:

### CODE REVIEW

**Comment by Oyu07** [comment]
So, the commits are gone, surely its fine

**Review by 1080pCat — COMMENTED** [review]
This floating wall at x102 y158 looks very janky, and also has three entire lights on it, two being inside the wall.
image

This air scrubber being under a table was something that was brought up on the original PR iirc. And hiding them can be rather frustrating later down the line. 
image

Im aware this is a atmos remap, but while you're editing this area, would you mind swapping this apc for the super version? It has a bigger cell, thus not needing a cell change/tesla to be already going get safely started.
image

Theres two tables and two decals on this window tile
image

This sign isn't bumped, its just on top of the wall, wasn't caused by this pr, but since you're here, could probably remove/replace it with a fire warning sign since there isn't actually a vacuum here
image

This sign just isn't visible from station side, also in a wall
image

same goes for all of these signs actually, all in walls
image

and the three here..
image

these four signs too.. They should probably be visible on the space side?
image

Could you drop the nitrogen naming here? the 'nitrogen to loop' is flat out incorrect, its the pure to engine line.
image

And im not even entirely sure what this filter is meant for it mixes the gases back together almost instantly, you could probably loose the filter for a T pipe. 
image

**Comment by Oyu07** [comment]
> "Quote"

Thanks for reminding / pointing stuff out

Noted, will update later

**Comment by Oyu07** [comment]
> ga

image
About this image. are you sure them being on the wall tile makes them not visible? seems like cyberiad also has them like this?

**Comment by Oyu07** [comment]
There are some weird CI failures. APC warnings but there are APC's in there

active turf alerts but its not touched?

**Comment by DGamerL** [comment]
image

Could you maybe reroute these supply pipes around like this? This'll prevent any accidental linking with the supply network if you will work with the filter side of the SM

**Comment by Oyu07** [comment]
image
Newly editted
Added T valve, previously there was literally nothing so both pipes sorta just merged after filter

**Comment by Oyu07** [comment]
image

**Review by S34NW — CHANGES_REQUESTED** [review]
Awaiting changes as discussed on discord regarding floor lights and moving walls

**Comment by Oyu07** [comment]
> Awaiting changes as discussed on discord regarding floor lights and moving walls

Will update tomorrow night. expect around 7pm utc

**Review by 1080pCat — COMMENTED** [review]
looks unintentional changes from food repath?
image

Missing wall here
image

Also is this strange jutting out area marker bit needed?
image

**Comment by Oyu07** [comment]
Food repaths yes, though they appear to be there so idk.

Will fix area and the wall thx

**Comment by 1080pCat** [comment]
> Food repaths yes, though they appear to be there so idk.

mapdif moment.

**Comment by Oyu07** [comment]
latest resolved

**Review by S34NW — APPROVED** [review]

**Pull request merged**
