### PR TITLE
Improved sprites for Donut Boxes

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Changes the sprites of the Donut Box to show each donut individually rather than just cutting parts off of the full sprite.

## Why It's Good For The Game

The new sprites look _slightly_ less ugly when you have less than six donuts in the box.

## Images of changes

Old:
Old Display

New: (Edited)
New Display
First time spriting anything (even though it was only an edit), so please feel free to suggest improvements.

## Changelog
:cl:
tweak: Changed Donut Box sprites.
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
Whoops, messed up there.
First commit fixed a sprinkle moving on Donut 5.

**Comment by AffectedArc07** [comment]
I think you may have made a minor mistake. The donut has gone sour and grey.
image

**Comment by SabreML** [comment]
That one's meant to have a hole in it, but it does admittedly look a bit odd.
I'll try changing the colour and see how it looks.

**Comment by taukausanake** [comment]
I don't think you should try visualizing a hole in there. The donut is at an angle in the box and I doubt you would see a hole that way. Just keep it the color as the other donuts like in the first image

**Comment by SabreML** [comment]
Having stared at it for about five minutes, I agree.

New sprite:

**Pull request merged**
