### PR TITLE
Allow silicons to shift-click to examine

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
rscadd: You can now shift-click to examine as silicon, instead of ctrl-shift-clicking, which is something absolutely no one would guess.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Does airlock opening remain intact?

**Comment by monster860** [comment]
It remains quite intact.

**Comment by Spacemanspark** [comment]
Does it examine the door as well?
I would find it fairly obnoxious if I were door crushing someone, for example, and it spammed me with examination messages.

**Comment by monster860** [comment]
No, it does not examine the door as well.

**Comment by Spacemanspark** [comment]
:+1: don't see why not, then.

**Comment by taukausanake** [comment]
Why was this never a thing before? Did it conflict with something?

**Comment by Earthdivine** [comment]
Because of fear with conflicts with door opening I believe.

**Pull request merged**
