### PR TITLE
[Goonchem] No Mix Messages

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Adds in support for chemical reactions not having a mix message.

Current Reactions that won't have a message:
- Ash
- Neurotoxin
- Black Powder

### CODE REVIEW

**Comment by Krausus** [comment]
Wouldn't it be more straightforward to just handle `mix_message = null` instead of adding a whole new "ignore the mix message" flag?

**Comment by Fox-McCloud** [comment]
It'll still display the icon of the holder the chemical reaction took place in...so no.

**Comment by Krausus** [comment]
You wouldn't just jam a null `mix_message` into the mix message. You'd check if it was null, and if it is, not display the message at all.

**Comment by Fox-McCloud** [comment]
Both work--both accomplish the same thing--one uses an additional var--the other uses a pre-existing one.

*shrug*

**Pull request merged**
