### PR TITLE
[DNM] I rebased TG and am now porting paradise features backwards

### PR DESCRIPTION
**Pull request by Couls**
**What does this PR do:**
Properly rebases this time! 

things I have to do:

- [x] Port over spacepods
- [ ] Port over our races

- [ ] Port over terror spiders

- [ ] Port over our karma system

- [ ] Old goonchem

- [ ] Possibly more?

**Changelog:**
:cl:
add: TG code
/:cl:

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
no don't port over spacepods pls 

and this in general has been opposed to my knowledge

**Comment by Couls** [comment]
Wow apparently no one liked spacepods huh

**Comment by Shockpoint** [comment]
This has a high opposition rate within the staff afaik as rebasing has never been something we wanted to do.
I'd suggest making this a personal project for something else rather than Paradise.

**Comment by taukausanake** [comment]
I like spacepods :(

**Pull request closed without merging**
