### PR TITLE
Adds sprites for Beepsky and Buzzsky, adds a new move animation for Buzzsky

### PR DESCRIPTION
**Pull request by FreeStylaLT**
@Aurorablade Updated the sprites and added the Buzzsky animation, thank them for the awesome tweaks!

Beepsky:
img img
img
img
img
img
img

Buzzsky:
img img
img
img

**His new walk cycle:**
img

### CODE REVIEW

**Comment by Norgad** [comment]
What about back?

**Comment by IcyV** [comment]
Not the biggest fan ever of those sprites. Doesn't feel entirely accurate or similar to the core Beeps.

That and I'm just a sucker for keeping Beeps eternally in his single-sprite glory.

**Comment by Fox-McCloud** [comment]
Don't really like those ...and this echoes my exact thoughts: 

>That and I'm just a sucker for keeping Beeps eternally in his single-sprite glory.

**Comment by FreeStylaLT** [comment]
Then let's let the single-sprite legend live on :trumpet:

**Comment by Aurorablade** [comment]
Dsmmit but I liked it it just needed touch up

**Comment by tristan1333** [comment]
Delet north sprite

**Comment by FreeStylaLT** [comment]
@Aurorablade Provided some wonderful sprite updates, along with a Buzzsky update + new walking animation, so I am re-opening this to see if any opinions were changed by ~finer art~

**Comment by Jaywings** [comment]
The animation is 10/10

**Comment by Aurorablade** [comment]
yes its inspirted by goon..but i did it by hand by just messing some spirte rotation buttons by clicking alot..

**Comment by IcyV** [comment]
I'm gonna stick with my same argument still. It's a bit of an improvement but it just seems off. It's very inaccurate and inconsistent compared to the original sprite.

**Comment by Aurorablade** [comment]
@IcyV my goal was to incorperate as much accuracy as i could between the front and side views. I would be willing to take some suggestion on how to improve it.

**Comment by IcyV** [comment]
@Aurorablade I don't really know how else to put it. Your style of doing it just isn't all that similar to the original sprite. This isn't a bad thing in any form. It's very mismatching and doesn't look right when he turns. There would either need to work and improvement on it, since it's not the easiest thing ever, or you'd probably need to touch up the original sprite to better fit your style and match the feel of the turns.

**Comment by Aurorablade** [comment]
@IcyV iactually called a cheeseburger in on this (not to say theres not plenty of good spriters hes just the one i feel most comfortable bugging and shoveing in a box)

**Comment by Gummin** [comment]
Sprites are pretty good in my opinion, but 
>muh bidirectional beepsky

**Comment by Fox-McCloud** [comment]
People don't seem to like this either @FreeStylaLT 

I don't think people would mind Goon's spinning berserk beepsky though.

**Comment by FreeStylaLT** [comment]
Goon has two I saw, one for spinning, one for flailing the baton everywhere. That could be an attack animation.

**Comment by Fox-McCloud** [comment]
Closing this due to opposition.

**Pull request closed without merging**
