### PR TITLE
[Refactor/Balance] Ammo Box and Casing price

### PR DESCRIPTION
**Pull request by larentoun**
## What Does This PR Do

Fixes:
- Fixes an issue where inserting from one Ammo Box to another didn't update the price of the first one. Duping.

Refactor:
- When ammo box is printed, the price of each bullet is recalculated depending on the parts
- Every usual ammo casing now has its own price which depends on its damage or printing price
- Ammo Box now has a price of 500 metal, a magazine and speed loaders have a price of 2000 metal
- Ammo Box with ammo now calculates its price as [Ammo Box cost + Each ammo casing cost]

Balance:
- Empty ammo casing have a value of 0
- WT550 and Laser ammo have greatly increased price (roughly 5 times more)
- Rubber ammo have slightly decreased price'

### Designs:
- Beanbag: 250 -> 1000
- Rubbershot: 4000 -> 1000
- Box of Foam: 500 -> 900
- Box of Sniper Foam: 900 -> 1300
- Shotgun Dart: 4000 -> 500 + 200 glass
- Foam Riot: 1000 -> 650
- Foarm Riot Sniper: 1800
- Box Foam Riot: 50000 -> 26500
- Box Foarm Sniper Riot: 90000 -> 72500
- .357 box: 30000 -> 28500
- 10m box: 30000 -> 30500
- .45 box: 30000 -> 30500

- 4.6x30 empty: 10000 -> 2000
- 4.6x30 box: 4000 -> 20500
- 4.6x30 ap box: 6000 + 600 silver -> 30500 + 3000 silver
- 4.6x30 ic box: 6000 + 600 silver + 1000 glass -> 30500 + 3000 silver + 4000 plasma
- 4.6x30 tox box: 6000 + 600 silver + 2000 uranium -> 30500 + 3000 silver + 4000 uranium
- Laser mag: 4000 + 600 plasma -> 42000 + 4000 plasma
- Laser box: 4000 + 600 plasma -> 40500 + 4000 plasma

### Defaults:
- Ammo casing:  0 -> 1000 (default value)
- Ammo Box: 30000 -> 500 (default value)
- Magazine: 30000 -> 2000 (default value)

### Ammo Boxes:
- speed loader (.357): 0 -> magazine default (2000)
- shotgun speedloader: 28000/1750 -> magazine default (2000)
- Foambox riot: 50000 -> defaut (500)
- Foam Sniper: 900 -> default (500)
- Foam Sniper Riot: 90000 -> default (500)

### Casings:
- 357: 0 -> 4000
- 9mm rubber: 0 -> 650
- 7.62: 0 -> 4000
- 7.62 ench: 0 -> 100
- .50AE: 0 -> 4000
- 10mm: 0 -> 1500
- 9mm: 0 -> 1000
- 9mm ap: 0 -> 2000 + 200 silver
- 9mm tox: 0 -> 2000 + 200 silver 300 uranium
- 9mm inc: 0 -> 2000 + 200 silver 300 plasma
- 4.6x30: 0 -> 1000
- 4.6x30 ap: 0 -> 1500 + 150 silver
- 4.6x30 tox: 0 -> 1500 + 150 silver 200 uranium
- 4.6x30 inc: 0 -> 1500 + 150 silver 200 plasma
- .45 rubber: 0 -> 650
- .45: 0 -> 1500
- .45 nostamina: 0 -> 1500
- 7.62x38: 0 -> 4000
- Buckshot: 0 -> 4000
- Rubbershot: 4000 -> 1000
- Beanbag: 250 -> 1000
- Techshell: 0 -> 1000 + 200 glass
- Dart: 0 -> 500 + 200 glass
- Tranq: 250 -> 500 + 200 glass
- 5.56: 0 -> 3250
- 5.45: 0 -> 1500
- Rocket shell: 0 -> 10000
- .75: 0 -> 8000
- 40mm: 0 -> 8000
- Foam dart: 0 -> 10
- Foam riot: 0 -> 650
- Foam sniper: 0 -> 20
- Foam riot sniper: 0 -> 1800
- Assassin. shell: 0 -> 1500 + 200 glass
- Cap: 0 -> 10
- Laser: 0 -> 2000 + 200 plasma

### Magazines:
- foam force META mag: 30000 -> 500

## Why It's Good For The Game

Ammo Boxes now calculate its cost based on ammo inside, which is good.

I'm not sure of that current balance of WT550 and Laser, so the input is pretty much required.

## Testing

- Printed every possible ammo_box and inserted it back into an autolathe
- Combined discounted ammo with normal cost ammo and inserted combinations back into an autolathe

## Changelog
:cl:
fix: Fixes an issue where inserting from one Ammo Box to another didn't update the price of the first one.
tweak: Ammo Box prices now are based on ammo inside AND box cost
tweak: WT550 and Laser ammo cost is greatly increased (roughly 5 times more)
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
Might be worth including how much specifically WT and Laser ammo prices have changed in the PR.

**Comment by Edan52** [comment]
Please include specific numbers as Coolrune said, so that we can compare the values.

**Comment by larentoun** [comment]
Updated description

**Comment by larentoun** [comment]
No reason to support upstream if they can't do a little thing to support downstream.

**Pull request closed without merging**
