### PR TITLE
Make can_inject deterministic; fix odysseus syringes sometimes not working [PR #12858, take two]

### LINKED ISSUE #12857: Odysseus syringe gun does not work properly
**Issue Description**:
the odysseus syringe gun does not work properly 

**What did you expect to happen**: 
for the syringe to hit the target and transfer its reagents to it, saying in admin log that it transferred the reagent

**What happened instead**:
the syringe hits the target but no reagents get transferred, also no admin log

**Why is this bad/What are the consequences**:
it makes the syringe's use impractical.

**Steps to reproduce the problem**: 
the situation where the launcher did not inject the syringe was the one in the image(notice for the syringe beneath the vulpin 
image ).

**When did the problem start happening**:
no idea.

**Extra information**:
it seems that the failure is random.

### PR DESCRIPTION
**Pull request by moxian**
I can't reopen #12858 , so filing this a new one.
Copy-pasting description:

## What Does This PR Do
Fixes #12857 by passing in targeting_zone that the mecha occupant aims at.
The problem here is that when neither targeting zone nor the user are passed to `can_inject()` , it picks a random zone (which is weird, since one would expect `can_inject()` to be deterministic), and many of those random choices are not really zones (`"left leg"` is not a zone, but `"l_leg"` is).
Anyhow, now all callers to `can_inject` pass in either non-null user or properly pass in targeting zone (or both).

Also added test for #12857  . It probably doesn't add much value at this point, but I think this time is as good as any to start building up a test suite.

Separately, my previous pr of #12697 was overly cautions with not closing the bugs it fixed, so I'll do it here:
Fixes: #12685
Fixes: #7132

## Why It's Good For The Game
Bugfix good
Automated testing good

## Images of the changes
B8g9ZeWIaH

## Changelog
:cl:
fix: Odysseus syringes now inject the victim consistently
/:cl:

### CODE REVIEW

**Comment by moxian** [comment]
Addressing @Kyep's comment https://github.com/ParadiseSS13/Paradise/pull/12858#pullrequestreview-404498623:

Spiders are not broken by the change; added test to ensure that to be the case.
Merge conflicts resolved.

**Review by variableundefined — COMMENTED** [review]
Not sure about leaving so much testing code in relative to actual production code - It is likely to sit there unmaintained after a while. 

I'll test this out and then ask to remove.

**Comment by moxian** [comment]
The intent of the testing code is to (eventually) be integrated into CI (travis or what have you), and be checked on every PR, to make sure that new changes don't break old edge-cases.
I admit that *these specific* tests are unlikely to be broken by future code, but I still think it's a good idea to set up CI "properly", and this (I hope) gives us some direction of doing so.

**Review by variableundefined — CHANGES_REQUESTED** [review]
Affected has requested on Discord that this should be converted over to a unit test or removed.

**Comment by Kyep** [comment]
When I asked for a test to make sure this doesn't break spiders, I meant I wanted you to test and confirm it.
I wasn't asking for you to make an automated test.

**Comment by moxian** [comment]
I know. I did both, mostly because I could.

**Comment by variableundefined** [comment]
Please implemented requested change by tommorow.

**Comment by moxian** [comment]
Removed the tests.

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
