### PR TITLE
Gives cargo a pet

### PR DESCRIPTION
**Pull request by Allfd**
Ports 'Paperwork' the sloth to cargo office as a starting pet from TG.

tj3smbu - imgurteyidsw - imgur

🆑 Alffd
Add: Adds Paperwork the sloth to cargo.
/🆑

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
lmao

**Comment by Regen1** [comment]
badmin
This is by headmin request

**Comment by LightFire53** [comment]
Toppest kek. Still think a turtle is better from cargo.

**Comment by Dumbdumn5** [comment]
Dear God, it's an anorexic monkey demon from hell. :+1:

**Comment by taukausanake** [comment]
I can't believe you're trying to replace Lisa. You're all monsters

**Comment by SheepFighter** [comment]
Lisa's not round-start though, is she? You order her.

**Comment by Allfd** [comment]
Lisa is not round start.

**Comment by taukausanake** [comment]
She should be round start

**Comment by Keilden** [comment]
Is he/she playable by ghosts?

**Comment by Allfd** [comment]
Lisa is not replaced, Ian will be refactored soon (tm)

**Comment by ZomgPonies** [comment]
I'm not a fan of the sprite. I think a turtle would be just as good and would look better. Also Lisa <3

**Comment by alexkar598** [comment]
Am I the only person who thinks paperwork is ALWAYS in the way when your dragging crates?

**Comment by Krausus** [comment]
Should probably add him to Metastation, too. And mapmerge.

**Comment by Allfd** [comment]
Ick, I thought I did.  How odd.

**Comment by Fox-McCloud** [comment]
>Should probably add him to Metastation, too. And mapmerge.

He may have; due to a major revert of a huge mapping PR, it's ...caused interesting ...things.

**Comment by Fox-McCloud** [comment]
Where is this located at? The main area or cargo bay? Cargo bay would probably be best.

**Comment by FlattestGuitar** [comment]
I gotta say, following staring at the sprite for a good half minute, I really don't like it. It doesn't fit our theme and its ugly. 

Sloths can be beautiful.

**Comment by Fox-McCloud** [comment]
>Sloths can be beautiful.

. . .

**Comment by Rurik123** [comment]
> I gotta say, following staring at the sprite for a good half minute, I really don't like it. It doesn't fit our theme and it's ugly.

> it's ugly.

That's the point! Why have a beautiful sloth when you can have one that resembles a demon incarnate!

**Comment by ProperPants** [comment]
> sloths can be beautiful

ugly sloth

**Comment by taukausanake** [comment]
> The only thing worse than a sloth is a koala.

Honestly, a koala would be a better creature than a sloth. Still not in for Cargo getting a shitty pet like this though

**Comment by Allfd** [comment]
That green is the mold growing in its fur.

**Comment by jughu** [comment]
Or give cargo lisa...
So i can make my Ian and Lisa romance novel

**Pull request merged**
