### PR TITLE
Cable/pipe fixes - Cyberiad Edition

### PR DESCRIPTION
**Pull request by monster860**
So, while working on my fancy map editor "FastDMM", I added in the ability to have filters more detailed than turf/obj/mob/area. I noticed some errors in the disposal nets, so I made a PR to fix them.

CYBERIAD

Disposals:
- Removes extraneous disposal pipe under RnD door
- Removes several extraneous disposal pipes in Xenobio
- Removes extraneous disposal junction under HoS door
- Removes extraneous disposal pipe under Sec Maint door, across from the escape pod
- Removes extraneous disposal pipe under north Morgue door
- Adds missing disposal trunk under disposal tube in engineering control room
- Fixes OR1 disposals going into OR2

Pipes:
- Adds missing scrubbers pipe under window in Exam Room
- Removes 2 extraneous scrubbers pipes under windows in windows in AI minisat access
- Removes row of extraneous supply pipes going across Xenobiology airlock
- Removes supply pipe branch going off into nowhere in Xenobiology

Cables:
- Removes extraneous cable under northwest morgue tray in Morgue
- Removes extraneous cable under north Toxins Storage door
- Removes cable branch going off into nowhere south of Vault
- Removes extraneous if you are reading this you don't have a life
- Removes extraneous calbes under labor camp shuttle windows

METASTATION:

Disposals:
- Remove extraneous disposals pipe under west surgery observation door
- Remove extraneous disposals pipe under south mining office door
- Remove extraneous disposals pipe under south courtroom door
- Adds missing disposal pipe under incinerator window
- Hooks up blueshield and nt rep office disposals

Cable:
- Remove extraneous cables under mech bay consoles
- Remove extraneous cable under medbay desk door
- Removes extraneous cable on the space cleaner refiller's tile in Janitor's Closet
- Removes extraneous cable under secure tech storage door
- Adds missing cable under table with "Greetings from Billy Bob" paper in permabrig

Pipes:
- No pipe errors! Yay!

Obligatory screenshot bragging about my fancy new map editor (editing not yet implemented) (startup time is 11 seconds):

image

### CODE REVIEW

**Comment by SamHPurp** [comment]
Don't suppose you want to also un-map the OR rooms disposals to each other? You currently disposal things and they fly out of the other disposal...

**Comment by LittleBigKid2000** [comment]
The junction in front of the ORs is the reason why. The arrow is pointed to the right, while it should be pointed up.

**Comment by monster860** [comment]
@LittleBigKid2000 @SamHPurp Fixed medbay disposals

**Comment by Fox-McCloud** [comment]
>you don't have a life

Rude.

**Pull request merged**
