### PR TITLE
Fixes doors-on-wall issue

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
fix: The red mining airlocks in the terror spider away mission no longer have walls underneath them.
/🆑

ts_map_oversight_fix

The red doors in this picture incorrectly had walls underneath them, due to a mapping mistake.
Now, they have floors as you'd expect.

### CODE REVIEW

**Comment by ktoma36** [comment]
Mmm now I dont have to try and RCD them down in combat :D

**Comment by Twinmold93** [comment]
For being a simple fix, it's taking a while.

**Comment by taukausanake** [comment]
Away missions might not be that important

**Comment by tigercat2000** [comment]
LGTM

**Pull request merged**
