### PR TITLE
Fixes unintentional mapping errors

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Read the title, look at the images.

## Why It's Good For The Game
Mapping errors are bad.

## Images of changes
Two floating light switches on Delta from #17989 removed.

pr1

pr2

Now on Box. A light was removed in PR  #17714 making viro hallway very dark. This is now fixed.

pr3

## Changelog
:cl: Bmon
fix: Delta no longer has floating light switches
fix: A missing light in viro hallway has been readded on Box
/:cl:

### CODE REVIEW

**Review by S34NW — APPROVED** [review]
Good

**Review by S34NW — CHANGES_REQUESTED** [review]
There appears to be two airlocks on this tile on Delta, can you fix while you are making fixes? 
image

**Comment by Bm0n** [comment]
...how did that fail

**Comment by S34NW** [comment]
`_maps/map_files/Delta/delta.dmm:148342:error: undefined map symbol: "iwk"`

**Comment by Bm0n** [comment]
> `_maps/map_files/Delta/delta.dmm:148342:error: undefined map symbol: "iwk"`
> 
> image
> 
> You seemingly delete this key while it is still in use... somehow

I used SDMM, what?

**Review by S34NW — APPROVED** [review]

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
