### PR TITLE
Adds Nianen Species Flags

### PR DESCRIPTION
**Pull request by roarbark**
## What Does This PR Do

This PR adds two sprites, one for a Nianen species flag and one for its rolled up version. Adds the Flag to the cargo store.

The standards depict a set of Nianen eyes crying gold over a desert planet under a red star. Refers to their way of life, the way they've shaped their home planet and alludes to the main trifecta in their religion.

## Why It's Good For The Game

Nianae currently don't have a flag, I thought it's a good way to add some interesting fluff and to help tie their really well made lore a bit more into the game.

The standards are supposed to be intricate and well crafted, so I decided to price them more accordingly, at 1500 credits.

## Images of changes
nianflagshow

nianflagdesc

nianflagstore

## Changelog
:cl:
add: nianen flags to the cargo vendor
imageadd: nianen flag sprite
/:cl:

### CODE REVIEW

**Comment by roarbark** [comment]
stupid question, is there a reason this labeled as a feature instead of sprites? 
where's the difference to #17497 which was labelled as such, i'm asking because i don't have an easy way to get gbp and i dont want any future sprites i spend time making shot down because they get labelled unexpectedly

**Comment by hal9000PR** [comment]
>$1500 for a flag?

its made of gold

**Comment by Carthusia** [comment]
> > $1500 for a flag?
> 
> its made of gold

Even with the gold trim, its purely a fluff item with no mechanical impact, making it so much more expensive than the others just feels counter intuitive to the purpose of the flags existence where people desire to use it, similar to when all flags cost 1,000 EACH and the cost was lowered because it was to high along with basically all other items in that vendor.

I just feel that it being almost 3x more expensive than the rest isnt a good idea and that it should be on par with the others to allow its usage to be on par as well.

**Comment by roarbark** [comment]
the idea was that i thought it to be cool to have the flag of the artisan race stand out, and, well not be used like the others. people would have to put together or borrow money to buy more than one, and they would be more precious ans careful with the flags.

if thats not what people want, i'm not against reducing the price

**Comment by Carthusia** [comment]
I fully get that and if it stayed 1500 its no issue in the grand scheme, just for me personally feels high.

The flag sprite itself is damn impressive and kudos to you for it. Puts the old ones to shame honestly, perhaps an idea for a future a PR, updating the old flags to be more in line with the this new aesthetic.

The vox flag as an example is just blue with a vox face sprite instead of somthing more symbolic of the race, same with alot of the flags like skrell, slimes, unathi, plasma, the taj and vulp are 90% identical baring a color scheme swap and 3 minor changes.

Would be awesome to see them all done up to this level of quality.

**Comment by atteria** [comment]
I would love to see rest of the flags be actually representational flags.
If we are going to update the old flags in the future, we should make the flagstand appear more 3/4ths. (Not implying this should happen in this PR, it would either be out of scope or introduce inconsistency.)

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
The flag's should be inline with the others. The fact it has a gold trim and costs 3x the others is going to lead to toxic amounts of species supremacy that would rival our past issues with vox.

**Comment by Carthusia** [comment]
> The flag's should be inline with the others. The fact it has a gold trim and costs 3x the others is going to lead to toxic amounts of species supremacy that would rival our past issues with vox.

I agree that the cost should be more inline, though considering the quality of the flags spritework, I kinda feel that the old flags should be brought inline with this flags quality overtime, rather than downgrading it to fit the older ones.

**Comment by roarbark** [comment]
i changed the flag to cost 500 credits, like the others. its not my vision for it, but it makes a lot of sense to make the flags accessible and to keep credits a non-issue. bumped the flag up a bit, is now in order with ascending price and changed the vendor description from "expensive" to "well-crafted"

> The flag's should be inline with the others. The fact it has a gold trim and costs 3x the others is going to lead to toxic amounts of species supremacy that would rival our past issues with vox.

the other flags kind of, well, "proudly proclaim the superior heritage" of their race in their description, to no proper consequence in the actual game with actual people. i do not think that the flag having a gold trim is going to have a negative impact.

**Comment by AffectedArc07** [comment]
> i changed the flag to cost 500 credits, like the others. its not my vision for it, but it makes a lot of sense to make the flags accessible and to keep credits a non-issue. bumped the flag up a bit, is now in order with ascending price and changed the vendor description from "expensive" to "well-crafted"
> 
> > The flag's should be inline with the others. The fact it has a gold trim and costs 3x the others is going to lead to toxic amounts of species supremacy that would rival our past issues with vox.
> 
> the other flags kind of, well, "proudly proclaim the superior heritage" of their race in their description, to no proper consequence in the actual game with actual people. i do not think that the flag having a gold trim is going to have a negative impact.
> 
> i also really dont want to bother with this kind of comment. genuinely. but i still feel that this PR is mislabeled. is there a resource i can read up on what makes a sprite i add cost me 9 gbp?

--

image

None of the other flags have gold trims, and this one shouldnt either. PR has been given the `GBP No Update` label so your PR wont get penalised, but the premise stands. You are adding something, so it is a feature.

**Comment by DoctorDrugs** [comment]
I personally think the design is good for the species flag, makes me think of a proper standard or banned that would be carried in formal/battle kinda ways. Very cool design much better than a few of the species flags I’d consider low quality but art is subjective to those that behold it.

**Comment by Necaladun** [comment]
I like it! Also gold fringed flags have special meaning to sov-cits which I find hilarious.

**Review by AffectedArc07 — APPROVED** [review]
screw it

**Pull request merged**
