### PR TITLE
Modular Computers Screen Sprite Sharing & New Tablet PC Sprite

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Allows the screen sprites to be shared between base sprites by offsetting them to fit into the screen. This means you don't need to make an entirely new set of screen sprites to add a new variant of modular computer, so long as it's screen is the same size.

Using this, I added a new tablet computer sprite which uses the same screens as the laptop.

image

🆑
add: New sprite for tablet computer.
/🆑

### CODE REVIEW

**Comment by AndrewMontagne** [comment]
It's worth mentioning I also made some alternate sprites for the console which also share the same sprites, which **aren't** implemented in this pull request (didn't want it to be _too_ controversial). This is the sort of thing this is intended for.

image

**Comment by FalseIncarnate** [comment]
That console is definitely smaller but I don't necessarily think that's a bad thing...

:+1: to the standardization though, I'm sure would-be spriters/coders will appreciate not having to make a version for each computer type.

**Comment by Fox-McCloud** [comment]
I don't like the tablet sprite at all, especially compared to the new set that TG released that's reallyyyyy nice:

img
img

**Comment by AndrewMontagne** [comment]
I agree that the sprite could be shinier, and I'd be open for the sprite to be replaced with something else.

However, my goal with replacing the tablet sprite was having consistency across all the modular computer displays so that players can tell at a glance what program is running on the device without having to re-learn a new set of display sprites from scratch and what programs they correspond to.

**Comment by Aurorablade** [comment]
Consistency is not always better in case of the tablet sprite as I much prefer the tg one fox linked. As I am sorry but the tablet one you have is horrid.

**Comment by FalseIncarnate** [comment]
@Fox-McCloud those frankly look like replacements for the PDAs, not a tablet. Perhaps its the apparent departmental-seeming colors though.

The table Andrew made looks like something you might see in a service area at a car dealership, with handles on the side and a solid looking frame. It's blander and lacks the detail of the sprites you linked, but definitely feels like a tougher piece of equipment. Throw some rubber grips on the handles and some detailing to the outer case and you go from bland to Toughbook-level ruggedness.

**Comment by taukausanake** [comment]
> Toughbook-level ruggedness

+1 if you can beat someone to death with it :P 

Yeah, as pretty as those tablets from /tg/ are I don't think it's worth whatever trouble it is compared to what this PR does. Plus consistency is sexy. Means you're making things work in a balanced way.
Yeah, give the tablet a little more meat to it ~and toolbox level robustness~ and this would be a nice addition

**Comment by AndrewMontagne** [comment]
I'm going to get some help from someone who has more artistic talent than I do (read: none) to make an improved sprite for the tablet PC. Will leave the PR open in the interim, and will update it when better sprites are procured.

**Comment by taukausanake** [comment]
I mean compared to the other sprites in here I see nothing wrong with it. Maybe it's a bit too small but otherwise I'd have this merged as-is and get different sprites for it in the future, granted the important part, the code, is all working

**Comment by Aurorablade** [comment]
just go with TGs, I honestly like those and consistancy is not always sexy...

**Comment by AndrewMontagne** [comment]
Something else worth noting. If we go with sprite consistency, I can start going through and porting the standard computers to modular computers, without having to track someone down to re-sprite everything.

**Comment by taukausanake** [comment]
What would turning standard computers (what I'm thinking all the normal computers we have) mean if they are turned into modular computers? I don't really understand the difference between them

**Comment by Jovaniph** [comment]
I don't even understand why we have modular computers in the first place. Why can't we fix PDAs instead and remove the laptops and tablets? Maybe even change the PDA sprite to look like a miniTablet or something.

**Comment by taukausanake** [comment]
I like how PDAs look. Don't take that away

**Comment by tigercat2000** [comment]
Following discussion between the Heads of Staff and Maintainers, it was decided to close this PR, as the tablets recently released by /tg/ were seen as being preferable.

**Pull request closed without merging**
