### PR TITLE
An experiment with allowing firebug debugging when working with NanoUI

### PR DESCRIPTION
**Pull request by Crazylemon64**
firebug
This PR is largely experimental, though not entirely functional
What it does, is allow admins to enable firebug debugging for themself under their "Debug" tab, then they can hit `F12` while viewing a NanoUI to pull up firebug's in-browser debugger. However, it keeps throwing script errors one way or the other for me, so I'll put this here so that either people can point me in the right direction, or yell at me for being so silly.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
What's the status on this? Plan on working on it some more, or should we got ahead and close this?

**Comment by Crazylemon64** [comment]
I'm not sure. I was hoping someone could offer help, but as it is, I'm not getting anywhere.

**Comment by Fox-McCloud** [comment]
Just going to close this, for now, then--hopefully ya can get some help on this down the road, though!

**Comment by Crazylemon64** [comment]
(no i wont)

**Pull request closed without merging**
