### PR TITLE
Good Window Sprites (And Grille)

### PR DESCRIPTION
**Pull request by uraniummeltdown**
New grille and brokengrille sprites from /tg/, new sprites have shading
New window, reinforced window, tinted window sprites from /tg/
New plasma directional (pane) window sprites from /vg/
newwindowsprites
newjoinedwindows

:cl:
imageadd: Window sprites look a lot better
/:cl:

### CODE REVIEW

**Comment by HugoLuman** [comment]
Can we see what they look like all joined up? It's had to tell how they'll look ingame fully with just isolated 1-tile windows

**Comment by FalseIncarnate** [comment]
Is it VG or TG that has the window damage sprites? We'll probably want those at some point.

**Comment by uraniummeltdown** [comment]
Both of those servers have some form of damage overlay (I don't think they use the same ones) and yeah I had it in mind too

**Comment by taukausanake** [comment]
I don't think I can tell the difference between these and the ones we have already. Can we get some comparison image?

**Comment by tigercat2000** [comment]
New ones on top.





I don't care for most of these, it reduces the details on the full windows and adds weird rounded corners to the panes. The normal glass panes are the only ones I kinda like, and they're still pretty meh.

**Comment by taukausanake** [comment]
I kind of agree with Tiger on this. There's nothing wrong with them but the rounded edges do look a little sore

**Comment by uraniummeltdown** [comment]
Hmm I'll take a look at unrounding the edges
As for the full windows, the current ones look absolutely awful it had to be done

**Comment by uraniummeltdown** [comment]
Going to do this later

**Pull request closed without merging**
