### PR TITLE
(Almost fully) re-done: Remaps Brig, EVA, Dorms and Law Area. Adds a few new maint rooms and areas.

### PR DESCRIPTION
**Pull request by FreeStylaLT**
**Conflict-free and re-done almost completely!**

Core goals this time around were:
* Remove / rework superfluous, awkward hallways (the one under the courtroom and the prison wing one)
* Consolidate Brig processing / cell block areas for better flow
* Allow for more opportunities for escape for Perma & fix its species compatibility
* Make the hallway that's left feel more like a proper, central hallway by opening it up
* Expand the station's general space for its pop, but without artificial hallways

Big Map-viewer summaries:

## BEFORE:
img

## AFTER:
img

### DORMS:
img

*Moved Cryo to a corner, reduced the number of pods by 4 (now it's 16 total), to save some space.
*Moved the Clown & Mime offices to dorms
*Removed Chang's walls
*Re-done / expanded a few other things
***Turned the holodeck sideways, z2 instances have also been changed.**
*Overall, Dorms are shaped the same, but should have a better general atmosphere and more pleasing to look at (Honestly, what more can you want from dorms?)

As you can see, the main goal here was to streamline its layout and reshuffle things in a more practical and (hopefully) aesthetically appealing way. The clown & mime were also the couple of jobs that seemed to fit spawning in this area as well.

### COURTROOM / IAA / MAGISTRATE:
img

img

* IAA, Courtroom and Magistrate have been connected into a Law / Courtroom area
* There's a dedicated lobby for the Magistrate / Courtroom
* Courtroom now has privacy shutters, private entrance for Sec, dedicated accused box
* IAA is now in Security's lobby.

Instead of that god-awful hallway, there's now a dedicated little lobby area going into the courtroom and Magistrate, and a re-mapped courtroom that will never get any use, but looks nicer anyway. The whole point here was to essentially turn these three things into an inter-connected complex, which is what it always should have been.
As for IAA, it was moved into the lobby directly to have the design of the map tell both them and anyone else what their primary job is -- taking care of any issues regarding Security.

### BRIG / PERMABRIG:
img
img
img

The big one.

*Remapped the Lobby
*Remapped the prison wing to be left of the Lobby
*Remapped Perma - it can now support space-proof species
*Moved the Firing Range, toilets
*Moved the cells
*Added slightly tiered cells
*Detective's office is now in public and part of / right next to the Security Lobby

As you can see, half of it is how it's always been, while the other half is.. completely remapped.

This is because the Prison Wing never fit into the brig, or really anywhere, as it was a separate, long hallway with a bunch of crap wildly attached to it. This instead, again, consolidated the prison wing into a cohesive, integrated part of Brig, more or less as how it "should" have been two years ago.

Perma is probably the biggest change - it's less isolated now and slightly less secure, as now ground-based break-outs are easier - as you no longer need to have a space suit for those. 

**The trays in front of windows in Perma also have their irrigation system turned on - meaning you can't break out to space all on your own.**

Execution:
Removed the silly gas chamber and space-shutters, added dedicated tiles for a firing-squad execution.

Also added lightly-tiered cells, with two of them having couches and carpets. The automatic leaving proved to be too problematic / aesthetically unappealing to be implemented properly, unfortunately.

### EVA / GATEWAY:
img

img

Shrunk that oversized POS of a room and used the newly made space to make an Office Supply closet and a new small closed maint area.

Beyond that, moving onto more minor changes I also modified the Gamma Armory to fit the new layout:

BEFORE:
img

AFTER:
img

###MAINT:
Added three new distinct rooms to Arrivals North, EVA and Sec maint:
img
Bootleg Detective in Arrivals North maint, the floor safe's contents:
img

img
Mafia-run poker room, complete with walled-off goodies and mafia suits. In EVA maint (right under the courtroom)

img

Decommissioned dorms area, turned into a DnD playground. Located in Security Maint.

img
A small graffiti / poster gang area that also serves as an alternative entrance to the maint bar.

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Why is there space koi in the barber shop

**Comment by FreeStylaLT** [comment]
is there a space koi in the barber shop?

**Comment by FreeStylaLT** [comment]
There is no space koi in the barber shop 😠 
img

**Comment by AffectedArc07** [comment]
Image

**Comment by Mitchs98** [comment]
Koi want to get haircuts too, dammit!

That said. I love all of this. Very much so. I seriously hope it's merged for real this time. I loved it before, but it's even better now. 

Did I also mention...Winter is coming?

**Comment by Pennwick** [comment]
I'm super stoked about everything else but I just can't get excited about the new permabrig. Yes it means that Vox and Plasmamen can get put in but it also means that non-space proof races have an extra step that they didn't have to do before. I'd rather have some regular non-blocked windows that could be shut by a button in the security room to give some more space views.

Also RIP the basketball court. No more shall two convicts dunk it out for the last piece of candy corn in the sustenance vendor.

**Comment by datlo** [comment]
Still like this, but could you add carrot seeds to perma?

**Comment by Quantum-M** [comment]
I think that maintanance room connected to the permabrig should be removed, or moved to the north.

It will prove to be a pain for security, especially the Warden, if the prisoners ends up with a single pathway that can be a bit difficult to remove.

**Comment by Pixelzilla** [comment]
- Change for the sake of change
Is this really needed? What does this PR actually fix and improve upon? What is its goal?

- Everything is being moved inwards to create a more cluttered/claustrophobic design.
Why are we moving things IN and making things smaller when the station/server population is fairly large

- Too many windows. Everywhere.
Everything is SUPER open! There is pretty much no privacy in the dorm areas and that certainly complicates things for anyone who might have a job in one of those areas and intends to do traitory things. Barber executions? Unlikely with both the location and the high visibility layout. Clown and mime next to each other with their known rivalry only separated by easily breakable windows? RIP.

-Repetition/Job Invalidation
There's one of the soda/booze machines in the dorms now when mere tiles away is the bartender who's entire job is to make drinks. Why are we invalidating their job by providing one of the machines for their job just a few tiles away from where people should be going to enjoy their drinks?

-One-tile maintenance halls
Why are we making one-tile maintenance halls? Not only does it look terrible but it also means you cant go around anyone pulling something and increases the chances of mulebots trapping people or each other. It's also bad for antags and a benefit for security since it's much easier to disabler/taser down a single-tile straight hallway.


-Dead End Maintenance
Security maintenance having no doorway near the secpod makes little design sense. There should at the very least be a doorway into cryodorms near the security pod. Having to backtrack through a literal dead-end is not good a good flowing design.

-Cryodorms & Explosions
Cryodorms being so close to security is absolutely going to cause issues if/when security is ever bombed. This has always been an issue but in the handful of times I've seen this remap played in testing both times security was easily devastated by bombs and the dorms went with it. Having security pushed in so close to the station seems to not consider how easily you can take out a significant amount of the station with this consolidation.

-Keeping 'em closer
I always assumed the reason perma and prisoners were so spread out was to make it more fair for prisoners/antags to have a chance to escape without being seen/overheard. With everything moved the way it is that balance seems to be thrown out the window in favor of security having an extreme advantage. With perma being closer and the lesser used buildings being further away there is certainly more chances for security to see and overhear any attempts at escape.

- 5 whole cells
There are only five cells for prisoners? That doesn't seem like enough for the population of paradise. I also admit that the weird asymmetrical design is not appealing at all to me. There's also so many rwalls and windows for maximum visibility in security's favor.

- Area Shrinking
I get that you wanna do all these revamps but with every revamp the areas you revamp have less and less space for people to build new rooms or do cool/fun things because there seems to be an overall goal of shrinking the departments and crushing them into an already cluttery station instead of pushing them outwards to give us more room for more fun. A lot of the spaces that I previously used for creating new rooms and wireart are being removed and destroyed. This one is no exception with the only remaining large floorspace for wireart being absolutely gone in this revision. I know that's not really something most people care about but it's the last large workable spot and it's frustrating to see another revision that is approached from the perspective of only one playstyle.

**Comment by AffectedArc07** [comment]
Anyone want a webmap-style rendering of this so you have a better viewing of the changes?

**Comment by taukausanake** [comment]
> increases the chances of mulebots trapping people

That sounds like an amazing way to die. You're walking in a narrow maint hall and a mulebot is in your way. You turn back and two more are back there.
_"You walked into the wrong neighborhood."_
They then proceed to knock you down and run you over multiple times before they leave you for dead

**Comment by Mitchs98** [comment]
> 5 whole cells
That's down one cell from what we currently have. While adding a temporary holding area.

Honestly I see nothing wrong with the map changes, everything you brought up seems awfully nitpicky except maybe the maint being 1 tile wide. There's also plenty of space for wireart? Just uproot Mr. Changs or the barber area.

**Comment by Mitchs98** [comment]
> Just gonna point out it’s rare for the brig to use more than two-three cells at a time.

Also this. God help you if you have a full brig something is wrong..

**Comment by Pixelzilla** [comment]
> 
> 
> > 5 whole cells
> 
> That's down one cell from what we currently have. While adding a temporary holding area.
> 
> Honestly I see nothing wrong with the map changes, everything you brought up seems awfully nitpicky except maybe the maint being 1 tile wide. There's also plenty of space for wireart? Just uproot Mr. Changs or the barber area.

Sorry you feel that i'm being needlessly critical. I'd love to further explain my concerns but i'm not sure we're even on the same page regarding my criticism. I do believe I have plenty of valid concerns that I detailed in my post. Which of them do you think is nitpicky and could you elaborate on why you believe all of them (except the 1 tile maintenance issue) to not be an issue?

**Comment by FreeStylaLT** [comment]
> 
> 
>     * Change for the sake of change
>       Is this really needed? What does this PR actually fix and improve upon? What is its goal?
I summed my main goals of the remap in the beginning of the OP. At least those were the broad strokes.

>     * Everything is being moved inwards to create a more cluttered/claustrophobic design.
>       Why are we moving things IN and making things smaller when the station/server population is fairly large
The northwest brig hallway did very little (if anything) for helping manage population because it led nowhere and had nothing there -- there was no reason to go there. The hallway was removed and its space optimized to flow better for general movement from A to B. Pointless, but large space does (IMO) very little to help the map manage population.

As for the permabrig hallway, it most definitely had nothing at all to do with the population, but rather brig design, which I explain in a later point.

>     * Too many windows. Everywhere.
>       Everything is SUPER open! There is pretty much no privacy in the dorm areas and that certainly complicates things for anyone who might have a job in one of those areas and intends to do traitory things. Barber executions? Unlikely with both the location and the high visibility layout. Clown and mime next to each other with their known rivalry only separated by easily breakable windows? RIP.

Although I think you mean general room transparency rather than actual space, I do like how you say that I've crammed everything in, but managed to also make it feel very open.

As for the dorms themselves, I do agree that the current design needs to be re-done, which is what I am planning on doing next. Otherwise, I don't see Clown / Mime being separated by windows necessarily a bad thing.

>     * Repetition/Job Invalidation
>       There's one of the soda/booze machines in the dorms now when mere tiles away is the bartender who's entire job is to make drinks. Why are we invalidating their job by providing one of the machines for their job just a few tiles away from where people should be going to enjoy their drinks?

This is a fair criticism and goes back to my previous comment about Dorms needing to be re-designed.

>     * One-tile maintenance halls
>       Why are we making one-tile maintenance halls? Not only does it look terrible but it also means you cant go around anyone pulling something and increases the chances of mulebots trapping people or each other. It's also bad for antags and a benefit for security since it's much easier to disabler/taser down a single-tile straight hallway.

I tried to make them as wide as I could, but other rooms forced some sections of maintenance to end up 1-tile wide, there's little I can do about it other than possibly fix it when I re-do dorms.

>     * Dead End Maintenance
>       Security maintenance having no doorway near the secpod makes little design sense. There should at the very least be a doorway into cryodorms near the security pod. Having to backtrack through a literal dead-end is not good a good flowing design.

I personally do not think that maintenance should ever _flow_ well, that is what the hallways and actual rooms are for, but this is more up to personal taste. I'll probably add an access point to that maint area through Cryodorms or another location.

>     * Cryodorms & Explosions
>       Cryodorms being so close to security is absolutely going to cause issues if/when security is ever bombed. This has always been an issue but in the handful of times I've seen this remap played in testing both times security was easily devastated by bombs and the dorms went with it. Having security pushed in so close to the station seems to not consider how easily you can take out a significant amount of the station with this consolidation.

To my knowledge, the most common brig explosion locations are either the lobby, or somewhere close to equipment storage (disposal bombs). Both of these would end up damaging Cryo as it is on the server right now because it was ultimately far closer to the center of brig than it is in this PR. 

>     * Keeping 'em closer
>       I always assumed the reason perma and prisoners were so spread out was to make it more fair for prisoners/antags to have a chance to escape without being seen/overheard. With everything moved the way it is that balance seems to be thrown out the window in favor of security having an extreme advantage. With perma being closer and the lesser used buildings being further away there is certainly more chances for security to see and overhear any attempts at escape.

The perma was moved specifically to allow a larger variation of escape possibilities and make it all-species-compatible. The attached maintenance, an isolated, closed-off maintenance section only one tile away and random loot generated _in_ Permabrig should allow for far easier _aided or prepared_ escapes.
>     * 5 whole cells
>       There are only five cells for prisoners? That doesn't seem like enough for the population of paradise. I also admit that the weird asymmetrical design is not appealing at all to me. There's also so many rwalls and windows for maximum visibility in security's favor.

The cell block was designed with flow of movement and practicality in mind over looking fancy, prioritizing gameplay resulted in.. well, less appealing iterations than what is currently on the server, but that is because it is extremely difficult to align 5-6 independently accessible 4x3 boxes in a good-looking way, especially when 1-2 of them need to have public access due to their VIP nature.

>     * Area Shrinking
>       I get that you wanna do all these revamps but with every revamp the areas you revamp have less and less space for people to build new rooms or do cool/fun things because there seems to be an overall goal of shrinking the departments and crushing them into an already cluttery station instead of pushing them outwards to give us more room for more fun. A lot of the spaces that I previously used for creating new rooms and wireart are being removed and destroyed. This one is no exception with the only remaining large floorspace for wireart being absolutely gone in this revision. I know that's not really something most people care about but it's the last large workable spot and it's frustrating to see another revision that is approached from the perspective of only one playstyle.

I believe that creating a large, cumbersome department that has long distance travel should only be used for maintenance, not the actual station proper. Most, if not all, of my remaps have focused on reducing unnecessary walking time and making sure that you can walk from A to B with as few turns as possible.

While I do understand that building new rooms or making wireart can be fun, I hardly consider those things to be a priority while mapping -- an abandoned or open, empty space accessible through a primary hallway or a department w/o adequate reason (i.e. not in Engineering / (Maybe) Science) would literally only interfere with its design -- you wouldn't be able to put actual functional rooms in that place, yet it would still be taking up the same prime real estate. 

Likewise, adding odd, useless connections to existing rooms only for them to connect to the same abandoned / empty space can be equally disruptive to the overall flow or design of a department.

I managed to fit in the abandoned guillotine room in Brig, but that was only because it was a dead space left from other designing other rooms.

**Comment by Spartan6** [comment]
Where’s my plastic bag conveniently placed in execution?

**Comment by TDSSS** [comment]
Few comments:

Can you add a few folders to the office supply room? I find them very useful for organising things (and making fake secret document folders). Maybe one of each colour? Also some tape wouldn't hurt.

That closet behind a separate door in the execution chamber feels very weird. It is already a lockable closet.

Getting a prisoner to the court room will be a pain now. Considering how rare trials are, that's not too bad.

That one tile of space between maint and perma maint looks weird, but I can see why you don't want to connect them.

**Make sure to remove the ballgag! Ballgags were removed from the code and map, but your picture still shows it. You might run into issues otherwise.**

Can anyone now grab clown/mime eva? I thought it was locked behind clown/mime access previously.

**Comment by Anoonki** [comment]
Having a direct access route from Perma to the Court room would be pretty cool. 
It might actually enable court room use for parole stuff instead of the magistrate just declaring "I'm granting parole to this vampire who's killed 3 people!!1!"

**Comment by AffectedArc07** [comment]
Got enough commits there?

**Comment by FreeStylaLT** [comment]
I'M JUST GETTING WARMED UP

**Comment by IIWOLFII** [comment]
You forgot to update that map with camera icons from security camera terminal or whatever its called, theres still old one

**Comment by Decemviri1** [comment]
I'll admit I was skeptical at first but from just one round it's really grown on me. Great work!

Query/Observations:
Has there been any testing to see just how more/less resistant key parts of the brig (armory, gear room, pod bay etc) are to an inbound meteor storm compared to the old brig?

Gamma access door via the brigbay seems a little off. May be worth moving it to the shuttle corridor.

Finally...

**Fluffy cuffs or riot.**

**Comment by FreeStylaLT** [comment]
Commits squashed, pictures updated.

**Comment by Mitchs98** [comment]
I agree. Re-add fluffy cuffs.

**Comment by Quantum-M** [comment]
I can't tell well from the picture, but does the magistrate office has the new magistrate stamp from #10633?

**Comment by Nicaragua1** [comment]
The clown and mime offices place make much more sense now
Also i love detective office being outside brig
The courtroom is finaly easy to acces i love that too.
Perma isnt HUGE like it used to be.

This are all amazing changes. Its like you read player's mind

**Pull request merged**
