### PR TITLE
[IDB IGNORE] [MDB IGNORE] One of the PRs of all time

### PR DESCRIPTION
**Pull request by S34NW**
https://www.youtube.com/watch?v=dQw4w9WgXcQ

### CODE REVIEW

**Comment by Stoniest** [comment]
Ground breaking PR.

**Comment by ATP-Engineer** [comment]
image

**Comment by AffectedArc07** [comment]
I am a tyrant

**Comment by AffectedArc07** [comment]
Was absolute chaos while it lasted - but we may rest now.

**Pull request closed without merging**
