### PR TITLE
Fixed the research server room requiring admin intervention for ventcrawlers

### LINKED ISSUE #14910: Ventcrawlers can get perma-stuck in server room
**Issue Description**:
Ventcrawling entities who enter server room air scrubber are doomed to forever stay in pipes.

**What did you expect to happen**: 
Be able to exit.

**What happened instead**:
Can't.

**Why is this bad/What are the consequences**:
The round is RUUUUINEEDD

**Steps to reproduce the problem**:
1) Be a ventcrawler (i.e. a drone)
2) climb into Server Room Air Scrubber #1
3) try to exit
4) be sad

**When did the problem start happening**:
Probably since forever.

**Extra information**:
How it looks with floor tiles removed:
20201116-094927-eJMoEcWLsg

Please note that the scrubber visually connects to the white pipe, not red (even though the piping is shown as red):
dreamseeker-20201116-094040

This might be fixed by #14432 , but i haven't checked, and honestly it's out of scope.

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Moves around some pipe stuff in the research server room in order to fix #14910.

*I do realise this will be on the mapping queue but I figured it'd be better to get it out there anyway.*

## Why It's Good For The Game

Currently if a maintenance drone (or any other ventcrawler) tries to enter the rightmost scrubber they get permanently stuck in a low pressure low temperature ventcrawling hell until an admin is kind enough to move them.

### Old:
NSS Cyberiad 2020-11-19 203948
old

### New:
*(No, I don't know why the windows changed colour)*
NSS Cyberiad 2020-12-17 152529
thing

## Changelog
:cl:
tweak: Slightly tweaked the layout of the research server room
fix: Fixed the research server room being a death trap for all ventcrawlers
/:cl:

### CODE REVIEW

**Comment by Kyep** [comment]
Can we please just build this into Free's med/sci remap and avoid having yet another PR in the boxstation map edit queue.

**Comment by SabreML** [comment]
> Can we please just build this into Free's med/sci remap and avoid having yet another PR in the boxstation map edit queue.

That has the same sort of issue currently, although you'll just get kicked out of the pipes rather than stuck in them.
thing

Should be pretty easy to fix though if @FreeStylaLT is up to it.

**Comment by FreeStylaLT** [comment]
Oh, I see. That's been fixed on the remap.
image

**Comment by SabreML** [comment]
Closing this cause map conflicts are scary. I'll make a fixed version if it's still an issue in a few days.

**Pull request closed without merging**
