### PR TITLE
Makes security records console emaggable.

### PR DESCRIPTION
**Pull request by monster860**
Right now, agent ID's are fucking useless. The only way to antag is to powergame. This is definitely *not* OP.

"But agent ID's need to have some vulnerability?"

Tators are underpowered as shit right now. This isn't the time to have drawbacks for identity-changing items.

:cl: monster860
rscadd: Security records console can now be emagged
/:cl:

### CODE REVIEW

**Comment by Earthdivine** [comment]
Agent ID's would have a lot more power to them if people stopped using TComm scripts that make them completely worthless. Same with Voice Changers. Just saying.

Also actually say what this change will do rather then just giving an reason FOR the change.

**Comment by monster860** [comment]
It says what the change does. Look at the changelog.

**Comment by Kyep** [comment]
An agent ID is not the same thing as an emag.

If you want to buff agent ID, perhaps make it easier to copy access using them?

**Comment by BiberDark** [comment]
Maybe let the player stay at a range of 2 - 5  tiles  ( for a certain time 15 seconds) to make a copy (RFID System).

**Comment by monster860** [comment]
The whole point is that you have agent ID and it shows up on the crew manifest.

**Comment by FalseIncarnate** [comment]
Gonna result in science traitors being even MORE powerful, since they'll just build a console and set themselves to free or officers to arrest to use beepsky against them while they use their emagged lockbox stuff to cause havoc.

Wow, this really felt like a stereotypical "buffs sci traitor" post, but it's going to just get used for adjusting wanted status instead of records.

**Comment by monster860** [comment]
Exactly, the arrivals checkpoint will become a popular tator place.

**Comment by Krausus** [comment]
> It says what the change does. Look at the changelog.

Actually...

> rscadd: Security records console can now be emagged

... you *don't* say what the change does. You forgot to mention that the emagging overrides the console to be authenticated for use. Also, your code tries to prevent logging out of an emagged console, but the `emagged` var doesn't actually get set, so that doesn't work.

**Comment by Doukhan** [comment]
Agent ID DNA lock when.

They're a complete liability ATM, only real use for them is negating the AI tracking you which a half dozen other things are better at anyway.

**Comment by Rumiluntti** [comment]
Second time you whine how you must powergame furiously to do well on traitor, second time I tell you "git gud"

**Comment by monster860** [comment]
Easy for you to say, you don't have to deal with lag caused by being very
far away from the server.

**Comment by Fox-McCloud** [comment]
Multiples requests were made to clarify what this does and to fix this; no response---nothing was done. PR is super stale. Closing.

**Pull request closed without merging**
