### PR TITLE
qdel refactoring part 1

### PR DESCRIPTION
**Pull request by Robertha89**
Part 1 of refactoring, point out any glaring issues.

### CODE REVIEW

**Comment by tigercat2000** [comment]
While this is very nice, you need to make sure that whatever you are qdelling can actually handle being deleted- it needs to have a Destroy() proc to clean itself up, not a Del() proc.

**Comment by Robertha89** [comment]
Currently everything works with qdel.

**Comment by Fox-McCloud** [comment]
A lot of these lack Destroy() procs =V

**Comment by Krausus** [comment]
> Currently everything changed now works with qdel.

What? Most pipes do not successfully garbage collect when they get qdel'd, which means they **do not** work with qdel. You can pass them into qdel, it'll try to garbage collect them, and when that doesn't work, they get deleted 30 seconds late - which means 30 seconds that something can be, and probably is, going wrong. This is fine for things that are qdel'ing a lot of pipes, because you probably won't notice the pipe network acting weird while you're running away from the singularity or the gaping hole left by an explosion, but you absolutely do not want the people working in atmos having to wait 30 seconds for their pipes to get their act together.

As for the pipe-related datums, qdel'ing those effectively does nothing without actually making them support qdel. They don't "work with qdel" in any meaningful sense.

The thing is, qdel isn't a magic "delete things good" proc. It's one step of the garbage collection process, and all the steps need to work right, or things will go wrong. Unless you understand all the steps, and what other changes you'll need to make for them to work, it's neither safe nor a good idea to replace dels with qdels.

**Comment by Robertha89** [comment]
True enough, i kinda jumped the gun on this.

**Pull request closed without merging**
