### PR TITLE
stamps sound thicc

### PR DESCRIPTION
**Pull request by thatdanguy23**
## What Does This PR Do
adds a nice chunky sound when you stamp papers

EDIT: although not _as_ chunky as its predecessor, this version is at least free to use. it's very quiet though, and im not exactly gifted at audio manipulation, so i can't make it sound as impactful as the original.

## Why It's Good For The Game
makes stamping papers cathartic, also blame @Landerlow 

## Changelog
:cl: thatdanguy23
add: a chunky stamp sound effect
/:cl:

### CODE REVIEW

**Comment by moxian** [comment]
Where does the sound file come from? Is it OC?

**Comment by thatdanguy23** [comment]
> Where does the sound file come from? Is it OC?

oh shit right, its the stamp noise from papers please, probably should mention that in the thimgy

**Comment by moxian** [comment]
Please make sure the source license allows reuse in our project.

**Comment by Carthusia** [comment]
mmmmm, chunky stamp sounds, now we just need a suitably chunkly yet soft boxing glove sound

**Comment by kenken244** [comment]
will this work when stamping people?

**Review by Kyep — APPROVED** [review]

**Review by AffectedArc07 — CHANGES_REQUESTED** [review]
Holding objection until its confirmed we can actually use this. License stuff is scary and maints are the ones who have to deal with it since we govern the codebase.

**Comment by thatdanguy23** [comment]
> Holding objection until its confirmed we can actually use this. License stuff is scary and maints are the ones who have to deal with it since we govern the codebase.

could probably just close it until we're sure about license stuff. i changed it to a duty free sound effect after moxian's concern, but it's shit compared to the paper's please one and i'm not super happy with how it turned out anyway.

**Comment by Fox-McCloud** [comment]
Closing, as per  requested.

**Pull request closed without merging**
