### PR TITLE
Security pride month update

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Security can now kill EOCs ... with style

## Why It's Good For The Game
A funny little thing for pride month, can either be on TM or fullmerged and later fully reverted (Or closed ofc)

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/108773801/dcf21fb0-49a4-4e87-bb02-a0f1e3281efa

https://github.com/ParadiseSS13/Paradise/assets/108773801/7928abe1-9939-4ba8-a4c8-4ba10dbd8fe2

https://github.com/ParadiseSS13/Paradise/assets/108773801/416430bf-f1b6-42b8-bfd9-94385d30d150

## Changelog
:cl:
tweak: Nanotrasen energy weaponry has gotten a colourful update!
/:cl:

### CODE REVIEW

**Comment by Cress67** [comment]
Did you get the idea from the cmagged energy weapons PR? That also gave rainbow lasers.

**Comment by AffectedArc07** [comment]
No way, gaysers

**Comment by ItsMarmite** [comment]
Gay Wrath

**Comment by TravisAngeI** [comment]
is this a direct replacement for the lasers or is this an optional thing? i think itd be neat if you could multitool to do this or something for a silly.

**Comment by DGamerL** [comment]
> is this a direct replacement for the lasers or is this an optional thing? i think itd be neat if you could multitool to do this or something for a silly.

Direct replacement!

**Comment by DGamerL** [comment]
Pride month is over, NT thanks you for your service 🫡

**Pull request closed without merging**
