### PR TITLE
Removes all monkeys and monkey cubes from the science outpost

### PR DESCRIPTION
**Pull request by FreeStylaLT**
As per request of Earthdivine:

Why: So if antag scientists want to get humanized monkeys, they'd have to steal them from places that require them, or order them, basically leaving SOME trail over just going to the outpost with mutadone pills/SEs and going to town on fifteen cubes + 4 loose monkeys in there.

:cl: FreeStylaLT
rcsdel: Removes all monkeys and monkey cubes from Science Outpost
/:cl:

### CODE REVIEW

**Comment by Kevak** [comment]
I use the monkeys there regularly as a cultie. I also regulalry loot the outpost for the cubes as a xenobiologist.

**Comment by FreeStylaLT** [comment]
Just another argument for removal regarding cult, cargo is a thing for xenobiologists

In general the outpost is a weird thing on our server since it literally has no actual use other than being a shelter during apocalypse or for antags

**Comment by Davdichan** [comment]
Wouldn't it just be easier/smarter/better to just remove the ability for vampires to feed off mobs that don't hold a ckey? Probably need to add in a flag or something so that if a mob ever held a ckey in case people ragequit/ghost while being munched on.

**Comment by FreeStylaLT** [comment]
That's a different issue, really. This PR is about making antags leave some clues behind before having a blood feast, same for cult. 

Having vampires only able to feed off of ckey players would cause different issues, seeing how terribly weak vampires are before they get any blood and how our players like to hunt them.

**Comment by Ar3nn** [comment]
I am for this change for quality of life reasons more than anything. Since there's cameras on the research station, the monkeys show up as mobs you can track using the track mob on camera verb as AI. On top of this, a chemical researcher will without fail burn 2-3 monkeys and just LEAVE THEM IN THE TEST CHAMBER, thus causing 3 unknown tracks to confuse me if I'm trying to track someone with no ID. I'd love it if simple mobs couldn't become Unknowns, but that's outside the scope of this if its even possible.

**Comment by tigercat2000** [comment]
```
I'd love it if simple mobs couldn't become Unknowns, but that's outside the scope of this if its even possible.
```
monkeys are subtypes of carbon/human, not simple animals

**Comment by Davdichan** [comment]
@FreeStylaLT That's the entire friggen point of Vampires and Changlings. They start out weak and are supposed to have a slow gradual power creep based upon how stealthily they can pick off members of the crew. Being able to just hack into an often neglected department, change one SE (that's super obvious if you know anything about genetics) and then make a bunch of injectors to eat unmonkeys.

Genetics is isolated enough that most people don't even know someone is in there. It has no windows outside of the doors to cloning, people rarely go into cloning to begin with unless they are stocking biomass or cloning a body. So, unless the AI happens to be keeping tabs on a room it has no reason to believe is being used, Vamps/Clings can easily powergame to their max potential with minimal risk. Where is the risk/reward gameplay these antags are supposed to be allow about?

**Comment by FreeStylaLT** [comment]
ohh windows in genetics

y'all forget you're talking to a guy who has a brig remap PR open in another PR


brb

**Comment by Fox-McCloud** [comment]
:+1: Outpost is literally what @FreeStylaLT laid it out to be.

With how Xenobiology works now, there's no point to giving them even more cubes than they otherwise have.

Genetics, too, quite frankly, has way too many monkies, but that's for another PR (and there's legitimate reason for it, as well).

**Comment by fludd12** [comment]
Xenoarch when


(/s)

**Comment by Belario** [comment]
The outpost has no use whatsoever ATM other than as a special project site/spare bomb testing range/antag lair.

Why not just nuke it from existence for the time being?

**Comment by FreeStylaLT** [comment]
cus that's like nuking a huge part of the assteroid and I've no idea what I'd put there instead

**Comment by Spacemanspark** [comment]
>I use it as a cultie.

Yes, that's powergaming.
:+1:

**Comment by tigercat2000** [comment]
i was working on a replacement for the sci outpost but egh mapping is awful 
so it's been delayed

**Comment by Kyep** [comment]
I really see no reason not to delete the Sci outpost. Just delete it outright. Its shuttle, too.
Maybe add a room or two to the science division on-station to compensate, but there is no reason to give it a whole off-station base that is only good for antag stuff, like harvesting blood and making endless constructs.

However, failing that, at the very least the monkies there should be removed. There are already at least 3 monkey cubes in science. We don't need more. And if we do, cargo exists.

I would like to see antags be more powerful - but at the same time, I don't think the right path to that power is an hour-long private ritual on the sci outpost, while everyone else in the round gets bored.

**Pull request merged**
