### PR TITLE
Replace Cling shriek sfx with new ones

### PR DESCRIPTION
**Pull request by Scribble-Sheep**
## What Does This PR Do
Adds two new sound effects composed of various ingame screams, and replaces the Resonant and Dissonant shriek sounds for Changelings.

## Why It's Good For The Game
As of right now, the sounds that play for these abilities is the generic emp "woosh" sound, and an ear-bleeding shriek noise. I think having these sounds not only adds a bit more character to the abilities, but in the case of Resonant Shriek, also makes it a bit less...painful to use.

## Images of changes

https://user-images.githubusercontent.com/46016730/192497730-2046e72d-8b6b-4786-af9a-af10a56ecac7.mp4

https://user-images.githubusercontent.com/46016730/190839461-ded90ae0-d922-4ba3-a4ca-072e47b75ea2.mp4

## Testing
I loaded up a test server, turned myself into a changeling, bought the abilities, and used them to ensure the sounds played.

## Changelog
:cl: Sciuridian
soundadd: Both Cling shriek abilities now have a unique new sound.
/:cl:

### CODE REVIEW

**Comment by roarbark** [comment]
pretty good, i think this has a lot of charm

**Comment by alex-gh** [comment]
Subjective opinion, but I wish they were a bit more distinct. 

They sound very samey at the beginning of the shriek.

**Comment by Scribble-Sheep** [comment]
> Subjective opinion, but I wish they were a bit more distinct.
> 
> They sound very samey at the beginning of the shriek. Maybe get rid of the guy screaming on one of them?

I mean, there is a difference. Resonanting shriek has a very wet reverb coming in, and loops the male portion a few times, while the dissonant shriek only plays the male portion once before being cut off by the distorted vox shriek.

If it ends up being an issue for people, I could try changing the Resonating shriek to another, more clear effect, but idk.

**Comment by komihe-ss13** [comment]
is it possible to make the EMP woosh sound effect trigger a little later in the voiceline? i think itd sound a littler cooler if the woosh came in just as the vox screech started

**Comment by Scribble-Sheep** [comment]
> is it possible to make the EMP woosh sound effect trigger a little later in the voiceline? i think itd sound a littler cooler if the woosh came in just as the vox screech started

Interestingly enough, the emp-woosh is actually just generically called by anything that triggers an emp, so I can't actually change the timing on it very easily. I initially had the shriek sound play after the emp started, but it caused the empscream to sound really delayed, so I moved them around.

**Comment by Scribble-Sheep** [comment]
It's been a while, and I'm not sure I'm really feeling these new sfx anymore. Closing.

**Pull request closed without merging**
