### PR TITLE
Adds office door buttons to the rest of head of staff's offices.

### PR DESCRIPTION
**Pull request by dovydas12345**
**What does this PR do:**
Adds office door buttons, which open the office doors, to RD, CMO, HoS, HoP, CE, BS, NT Rep offices.

**Images of sprite/map changes (IF APPLICABLE):**
RD office:
rd

CMO office:
cmo

HoS office:
hos

HoP office:
hop

CE office:
ce

BS office:
bs

NT Rep office:
ntrep

**Changelog:**
:cl: Dovydas12345
add: Added office door buttons, which open the office doors, to CE, HoP, CMO, HoS, RD, BS, NT Rep  offices.
/:cl:

### CODE REVIEW

**Comment by Denthamos** [comment]
Something for the future.  It would be nice if some of these door buttons could get different colors tied to them to signify their importance and more easily differentiate between them at a glance.

**Comment by dovydas12345** [comment]
I would do something like that but i am not a huge fan of spriting.

**Comment by Citinited** [comment]
Small point, but your changelog is missing the RD's office too

**Comment by davidchan13** [comment]
NT Rep button please.

**Comment by AffectedArc07** [comment]
^ that seems like one of the most useful ones

**Comment by dovydas12345** [comment]
Uh.... had headaches with conflicts but finally got it to work... Hopefully done with conflicts... (Probably can tell from the commits)

**Pull request merged**
