### PR TITLE
Fixes Rubber Duck

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes the rubber duck sounding like a damn bike horn.

### CODE REVIEW

**Comment by Robertha89** [comment]
Oh, rubber ducky, you will be missed, you where always the poor mans bikehorn.

**Comment by TheDZD** [comment]
Even more nightmare fuel for Hawke.

**Comment by Robertha89** [comment]
all thats missing is being able to replace the clowns heart with the rubber ducky, and all will be right with the world.

**Comment by tigercat2000** [comment]
B-BUT HONK!!
:cry:

**Pull request merged**
