### PR TITLE
Fixes Several Injections

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes several injections not properly procing INGEST when they occur.

Things impacted:

- Bees
- Mech Syringes
- Darts

:cl: Fox McCloud
fix: Fixes bees, mech syringes, and darts not properly calling INGEST for a reagent
/:cl:

### CODE REVIEW

**Comment by TheDZD** [comment]
Aren't bees supposed to be a touch reaction?

**Comment by Bigtimetripod** [comment]
Don't bees inject victims with chemicals?

**Comment by FlattestGuitar** [comment]
They don't really touch you with their stings, they sting you. Makes sense to me. :+1:

**Comment by Fox-McCloud** [comment]
@TheDZD 

I think it was an oversight that they were TOUCH, to be honest.

**Pull request merged**
