### PR TITLE
The Great Atmosian Fixes for DeltaStation

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do

It's here, the fix that I keep promising Atmosians:

- Repipes Atmospherics to make atmos techs happy by attaching a freezer, as well as adding piping so you can now "Pump N2 into the main mix line and the air mix line"
- Gives Atmospherics a bigger power cell
- Lets Atmos Techs close the SM radiation shutters
- Lets Atmos Techs also enjoy the Engineering Breakroom
- Replaces an electrical supplies locker and welding supplies locker in Atmospherics Maintenance with an atmospherics wardrobe and a generic tool closet due to Atmos Techs not having that access
- Also removes a "magic pump that manages to make air disappear from distro" in Atmospherics Maintenance
- Connects Atmospherics Solars to the rest of the grid

Also does the following:

- Toxins mixing now can use the burn chamber ~~without igniting themselves~~
- Remaps Experimentor to actually work
- Also throws Experimentor a bone, by giving them a single strange object
- AI Transit Tube blast doors now start opened

## Why It's Good For The Game
Make atmospherics not more-or-less require an instant overhaul at round start, plus other mapping fixes. Atmospherics changes were made with consultation from Dafrek (Zeke Elliot), Krossarn (Sticky Bomb), and Henr (P'aul).

## Images of changes

Old Atmospherics piping:
image

New Atmospherics piping
image

Old Toxins/Experimentor
image

New Toxins/Experimentor
image

## Changelog
:cl:
tweak: DeltaStation Atmospherics has new piping regarding the N2 Line
tweak: DeltaStation Atmospherics now has a bigger power cell round start
fix: Atmos Techs can now interact with the SM rad shutters on DeltaStation
tweak: Atmos Techs can now use the breakroom on DeltaStation
tweak: Atmos Maintenance no longer has welding supplies/electrical supplies lockers on DeltaStation, now an atmos wardrobe and tool closet
tweak: Removes a pump from Atmos Maintenance
fix: DeltaStation Toxins burn chamber won't burn scientists on it's own
fix: Remaps DeltaStation Experimentor to connect with the R&D console
add: DeltaStation Experimentor now gets a strange object
tweak: AI Sat Transit Tube blast doors are now open round start
fix: DeltaStation Atmospherics Solars now are connected to the rest of the powergrid.
/:cl:

### CODE REVIEW

**Comment by Dafrek** [comment]
I just realized that the atmos solar SMES does not connect to the main power gird, instead it only powers the APC in the solar access room.

**Review by S34NW — CHANGES_REQUESTED** [review]
Looks good, I'd request one tweak please to ensure pipenets don't fuse.

image
Move these vents to areas not already occupied by a pipe. (Yes, atmos can break and fuse the pipenets, bloody atmos code.)

Also, the fulltile window conducting heat seems to be a code issue, will have to replace it later when that issue is fixed.

**Comment by LightFire53** [comment]
> Also, the fulltile window conducting heat seems to be a code issue, will have to replace it later when that issue is fixed.

This is the same set up that Box has now, and someone told me that in testing that it worked this way.

**Comment by S34NW** [comment]
> 
> 
> > Also, the fulltile window conducting heat seems to be a code issue, will have to replace it later when that issue is fixed.
> 
> This is the same set up that Box has now, and someone told me that in testing that it worked this way.

Yeah, its not meant to, but it does. So the way you've done it here is best until the window itself can be fixed.

**Comment by LightFire53** [comment]
Found my missing commit on my other PR. For some reason, it's in here. Well, updating to master fixed it anyway.

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
