### PR TITLE
Some atmos fixes

### PR DESCRIPTION
**Pull request by Jovaniph**
This fixes the broken pipe north of the bridge around maintenance

before
pipeb
after
pipea

This also fixes the air injector outside west of turbine.

🆑 Jovaniph
fix: Broken pipe leading to the scrubber north of the bridge/maintenance
fix: Air Injector not working outside west turbine
/ 🆑

### CODE REVIEW

**Comment by Taaketa** [comment]
That air injector breaks on nearly every map merge.

**Comment by SamHPurp** [comment]
I keep fixing this, but people keep `-f` pushing their map ignoring changes. Its driving me batshit.

**Comment by Citinited** [comment]
The broken scrubber in central primary hallway is fixed in #7856 (which is taking forever to merge I'm sorry), but the other one looks good to fix

**Comment by SamHPurp** [comment]
So this contains superfluous fixes.

I don't think its your fault that a several month old PR hasn't been merged @Citinited

**Comment by Jovaniph** [comment]
Aright well, I forgot about the PR you made. These are generally fixes that are atmos related. I'm still waiting for many of the maps to get merged to do a Pipe Cleanup.

**Comment by Citinited** [comment]
You can still have the injector fix (I didn't touch that), just remove the scrubber fix 😄

**Pull request closed without merging**
