### PR TITLE
Ports TG's Fultons

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports TG's fultons.

Fultons are 3-use extraction device that can be linked to an extraction beacon; you can use them to move moderately sized non-anchored items or mobs from an outdoor location to a fulton beacon (the beacon doesn't have to be outside). Useful for moving things like the dance machine or rescuing dead miners without having to interrupt your mining adventures.

Fultons are available as a mining vendor purchase, or you can spend your voucher to get a kit that has 30 marker beacons, a fulton beacon, and a fulton extraction pack.

I thought these would be a royal pain to implement---nope. One of the easier ports I've done

:cl: Fox McCloud
add: Add fulton extract packs to the mining vendor; rescue precious valuable or dead miners!
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
feel pretty silly and memey for Paradise, personally.

**Comment by Fox-McCloud** [comment]
You do realize it's an actual, real thing, right? https://en.wikipedia.org/wiki/Fulton_surface-to-air_recovery_system

**Comment by JKnutson101** [comment]
Cool! Now if only Miner's didn't disconnect when they died so we could actually recover them. 👀

**Comment by Lunaimon** [comment]
Can these carry things across z-levels?

**Comment by Leanfrog** [comment]
Will you be able to fulton yourself to get on out of there in a bad situation?

**Comment by Fox-McCloud** [comment]
>Will you be able to fulton yourself to get on out of there in a bad situation?

Yes, but there's a long delay; jaunters are better for poofing out of danger.

Fultons are better for rescuing.

**Comment by Citinited** [comment]
Finally, a better way than the RCS to send stuff back to the station!

**Comment by TDSSS** [comment]
>You do realize it's an actual, real thing, right?

I thought metal gear made that one up, lol. Fair enough.

**Comment by JohnBigless** [comment]
Would it be possible to fulton another player who is still alive?

**Comment by Melloreaper** [comment]
This may be needed sense the only other method of extracting off z levels is gone.(tele science)

**Pull request merged**
