### PR TITLE
Prevents -lathes from producing infinite power via cells

### PR DESCRIPTION
**Pull request by Inadvizable**
## What Does This PR Do

Newly printed power cells are empty. This is the case for autolathe, protolathe, and mech fabricator. Someone else made a PR like this but they seem to have deleted their github account.

~Requires #18465 to be merged first to not be obnoxious.~ It has been merged.

## Why It's Good For The Game

Infinite power generation should probably be reserved to xenobio's special slime cells. Cargo and science shouldn't be able to continue working by printing new cells after they are cut off from the grid.

Thermodynamics are pretty cool and it's nice to obey their laws.

## Testing

1. Print some cells from either machine.
2. Check their power level.

## Changelog
:cl:
tweak: Newly printed power cells are empty.
/:cl:

### CODE REVIEW

**Comment by Leanfrog** [comment]
Said this before on the last one, but I feel this is tedium for the sake of tedium, I don't feel like writing the whole thing out again so I'm just going to stick to bullet points.

- Cells coming out fully charge can be rationalized by saying they're charged in the process of construction
- "Infinite power" from printing cells isn't exactly that egregious, power is basically unlimited currently regardless of cells coming out fully charged
- If this was part of a power generation overhaul then I'd be more likely to support it

**Comment by roarbark** [comment]
can the power not just be deduvted from the apc supplying the lathe

**Comment by Inadvizable** [comment]
> can the power not just be deduvted from the apc supplying the lathe

It can. You will power sink the room you're in.

> Cells coming out fully charge can be rationalized by saying they're charged in the process of construction

See above.

> "Infinite power" from printing cells isn't exactly that egregious, power is basically unlimited currently regardless of cells coming out fully charged

Power being mildly meaningless really doesn't justify making it more meaningless in my opinion.

**Comment by Leanfrog** [comment]
> Power being mildly meaningless really doesn't justify making it more meaningless in my opinion.

I don't see how leaving things as they are makes it more meaningless.
And in regards to the first two responses for me at least I was implying that, if anything the power should be deducted from the APC while the cell is crafted, this would remove the "infinite power" aspect while avoiding the need to sit around and wait while a cell is charged. 
Also this wouldn't affect weapons production since every gun sci can make has since been replaced with weapon kits, and all newly arriving weapons are already charged, exos though? Sure I guess it would slow down their production but people would still just turn to yellow cores as they do now anyways.
Finally, I feel that if anything, this is just going to further push people towards yellow cores which basically invalidate any sort of power management, the only thing they can't really be used in are prods, which despite their recent tweak don't really need a colossal amount of power to begin with.

**Comment by Miraviel** [comment]
I would love to see this, I think this is a good first step to making power more relevant. Given that we are based on an atmosphere/engineering simulator, it's strange how irrelevant engineering can get with one (1) active RND boi and two presses of a button.

I have seen this done on other servers, it is not as tedious as it sounds.

**Comment by Sirryan2002** [comment]
I disagree with the criticism that this is unnecessary added tedium. This is an unregulated resource tap for power that allows players to circumvent short term power scarcity issues where there's a proto/autolathe. Free power needs to go and this is a great step in the right direction.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
