### PR TITLE
Adds clicks to flashlights 🔦 

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: FlattyPatty
tweak: Improved Nanotrasen click manufacturing procedures now allow the flashlights to make that classic clicking sound you know and love.
/:cl:

### CODE REVIEW

**Comment by Dinarzad** [comment]
click-clack

**Comment by Regen1** [comment]
👌

**Comment by Birdtalon** [comment]
Sounds good. *Click clack*

**Comment by Fox-McCloud** [comment]
More ways for players to annoy the crap out of each other.

**Pull request merged**
