### PR TITLE
Fixes some grammar mistakes, changes the \red to <span class> formatting

### PR DESCRIPTION
**Pull request by FreeStylaLT**
:cl:FreeStylaLT
typo: changed its to it's in lockbox description
fix: changed \red to <span> formatting
tweak: changed stetchkin's price from 9 TC to 4 TC, suppressor's from 3 TC to 1 TC
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
>changed stetchkin's price from 9 TC to 4 TC, suppressor's from 3 TC to 1 TC
?

**Comment by FreeStylaLT** [comment]
forgot to include the changelog in that last PR, so am making up for that mistake here

**Comment by TheDZD** [comment]
You shouldn't have a space after declaring a span class.

**Comment by VampyrBytes** [comment]
> fix: changed \red to formatting

iirc changelogs only include stuff that has an effect in game

wow, speedmerge, too late now anyway lol

**Pull request merged**
