### PR TITLE
Updated Direction sign sprites.

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Updates the sprites for the Direction signs to be more consistent and adds the Bridge direction sign, since there was already a sprite for it.

I have a map edit PR that I'm working (#13924) on that adds more of theses around the station, and I figured I'd update the sprites a little bit while I'm at it.

## Why It's Good For The Game

Direction signs are pretty inconsistent, this fixes most of the issues.

## Images of changes

Old:
gif

New:
Gif

Edit: Added gifs.

## Changelog
:cl:
add: Added consistent lighting to all signs.
del: Removed duplicate Medical direction sign.
tweak: The Supply direction sign now says CARG rather than SUPP.
fix: Capitalised some sign descriptions.
fix: Recentered the Science direction sign.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
image
Thats a no from me. This hurts my eyes and makes it difficult to read.

**Comment by SabreML** [comment]
Personally I found that it doesn't look so bad in-game
NSS Cyberiad 2020-07-25 151745
But yeah, it really does need to be a bit darker.

**Comment by AffectedArc07** [comment]
The colours are fine already, in my opinion, especially the engineering one.

**Comment by SabreML** [comment]
The colours are, yes, but the shading is very inconsistent.

The Medbay sign is lit from the bottom left.
The Evac sign isn't lit at all.
And all the rest are lit from the bottom up.

I wouldn't mind going and changing them back, though. With new shading.

**Comment by Kyep** [comment]
Does this fix the invisible escape sign at 131,131,1?

**Comment by SabreML** [comment]
This one doesn't, but the map edit I mentioned does.
I figured I should seperate it into two, one for map changes and one for sprite changes.

**Comment by SabreML** [comment]
Alright, attempt two.

Old colours, new lighting direction:
Display NewOld

**Comment by AffectedArc07** [comment]
Colours are fine now

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
