### PR TITLE
Adds a Sysadmin Alt Title for the RD

### PR DESCRIPTION
**Pull request by TheDZD**
Idea I had as an alternative to #4684. Not particularly attached to this idea, and generally heads don't have alt titles, but here it is anyway.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Uh, :-1: we shouldn't have alt head titles and I can guarantee that 8/10 people won't even know who a sysadmin is.

**Comment by monster860** [comment]
Alt head titles? Fuck no, that's just gonna cause confusion :-1:

**Comment by Lady-Luck** [comment]
No alt head titles :-1:

**Comment by theColdflame** [comment]
:-1: 
I'M NOT THE RD IM THE SYSADMIN STOP EXPECTING ME TO DO THINGS

**Comment by TheDZD** [comment]
As I said, not particularly attached to this, and now that I think about it, what @theColdflame just said would almost certainly happen.

**Pull request closed without merging**
