### PR TITLE
Ghost bar cash increase

### PR DESCRIPTION
**Pull request by Rayforx**
## What Does This PR Do

It adds a zero to the amount of money that a ghost bar person get
## Why It's Good For The Game

Currently, a ghost bar person does not have enough money to do a bit of dress-up, or buy a single pack of smoke.
## Images of changes

image

## Testing

Spawned myself in, and saw that I could buy myself some bling with my monopoly money
## Changelog
:cl:
tweak: Added more money to the ghost cafe
/:cl:

### CODE REVIEW

**Review by Contrabang — APPROVED** [review]
code LGMT

**Review by DGamerL — APPROVED** [review]
The code agrees that's 1000 credits now

**Comment by Rayforx** [comment]
I love flashing my monopoly money

**Review by 1080pCat — APPROVED** [review]
21nims

**Review by Henri215 — APPROVED** [review]
image

**Review by Burzah — APPROVED** [review]

**Pull request merged**
