### PR TITLE
A museum's finest: Statues tweaks

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds monkey and corgi as silver statues.
Kidan warrior statue now can be made using plastitanium.

All statues now take 2.5 seconds to be made.

## Why It's Good For The Game

We had some unused statues and sprites in code that could be tweaked and added to the game, i am sure players will want to worship statues of corgi/monkey.

It doesnt make sense that you can build heavy statue, that can be anchored, in 0 seconds.

## Images of changes

cogi

kidan

## Testing

- Spawned all the necessary sheets and built the statues.
## Changelog
:cl:
add: Added monkey and corgi as silver statues
tweak: Kidan warrior statue now can be made using plastitanium
tweak: Statues: Time to build is now 2.5 seconds
/:cl:

### CODE REVIEW

**Comment by lewcc** [comment]
I think the bust feels a little out-of-place, but the rest of them look pretty good.

**Comment by McRamon** [comment]
Yeah bust is out of place

**Comment by Sirryan2002** [comment]
I'd prefer the sandstone bust be removed or resprited to better fit the world, it's too realistic compared to our human sprites

**Comment by Henri215** [comment]
Bust has been removed.

**Review by Sirryan2002 — APPROVED** [review]
code looks good

**Pull request merged**
