### PR TITLE
Adds robotic cryopod to mechbay

### PR DESCRIPTION
**Pull request by Kyep**
🆑 Kyep
add: The mech bay next to Robotics now has a robotic storage unit (cryopod for cyborgs).
/🆑

Old mech bay:
mechbay_old

New mech bay (cryopod at bottom left):
mechbay_new

### CODE REVIEW

**Comment by alexkar598** [comment]
why was it even removed?

**Comment by Aurorablade** [comment]
it wasn't removed. its just on the AI Sat. there was never a crypod in the robotics area to start with.

**Comment by Kyep** [comment]
This PR doesn't remove the one on the AI minisat. It just places a far more convenient one in the mech bay.

**Comment by uraniummeltdown** [comment]
I think a better solution is to just let borgs use the existing cryopods in Cryodorms as its already known as the "off limits to bombing" area

**Comment by Kyep** [comment]
Not sure it makes sense for borgs to use normal cryopods. Also would prefer not to complicate the main cryopod code.

**Comment by Jountax** [comment]
There could be a Cyborg storage thingy in the cryodorms, rather than just making the cryopods also work on borgs. How often are all the pods even in use anyway?

**Comment by SamHPurp** [comment]
@Kyep unlikely to be too complicated to combine the two. We've done so over on Oracle if you wanted to checkout that code.

My preference, as you'd guess, is just to combine the functionality into the regular cryopods.

**Comment by davidchan13** [comment]
Putting one or two robo-cryopods in Cryodorms seems a far better solution. Lots of borgs don't cryo cause many players aren't even aware that the borg cryo is on the sat, you usually find a bunch of them in mechbay in standby mode and it's too much of a hassle to drag a borg to the AI sat for 99% of our player base to bother.

**Comment by Kyep** [comment]
That's why I placed the borg cryopod in mechbay. It is where borgs naturally go to stand down.

**Comment by SamHPurp** [comment]
Related thought, albeit outside scope, but humour me:

There are a lot of resources in these borgs that vanish when cryo'd (popping out the posibrain etc).

Perhaps there should be a way to reclaim some of this metal etc.

**Comment by tigercat2000** [comment]
Seems good to me.

**Pull request merged**
