### PR TITLE
Robotics now has anesthetic, cleaner, sterile masks/gloves, sink

### PR DESCRIPTION
**Pull request by Crazylemon64**
robo-surgery
now with 300% less malpractice

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
ermmm--considering 99% of the time they're just yanking out someone's brain, this seems highly unnecessary.

Also, that sink placement is really bad, no offense.

**Comment by tigercat2000** [comment]
unnecessary sure
but so is anesthetic in surgery
it's literally pointless

**Comment by Fox-McCloud** [comment]
Actually, @tigercat2000, that's not true; if a patient isn't anesthetize for certain surgeries, their bones will shatter.

**Comment by tigercat2000** [comment]
@Fox-McCloud Care to point out where? Because I am 101% sure that's not a thing and never has been.

**Comment by Crazylemon64** [comment]
Yeah, I was iffy about some of the things here. Wasn't sure where to put the sink - maybe at the top of the room would do better?

**Comment by taukausanake** [comment]
I just cut off the head of the future borg and from there crack the skull open. I don't see why Robotics needs anesthetic but a sink is nice even though there's two in Science Access

**Comment by Crazylemon64** [comment]
Anesthetic is so that the live brain extractions don't have someone conscious while you cut their head open or through their neck. Given all the screaming I get from me doing that, I thought it'd be nice to at least have that, the sink being to wash up, though the presence of sinks in showers in access is probably enough. Sterile gloves and masks, for dealing with the bodies, but you already have body bags for that. So, I think the only thing that sticks for me, personally, is the anesthetic. Cleaner, can be co-opted mostly by cleanbots except for directly under the surgery table itself. The actual push, however, will be tomorrow or something because it's late and map-editing takes a while.

**Comment by Regen1** [comment]
:-1: :100: 

Screw making robotics medbay number 2.
There's a reason there is no anesthetic there for over two years.
Reason for this is because borging is either done to people who are dead, and has chosen to be a borg upon death, usually in their death note whatever, or because medbay has no capacity to clone.
The other reason is borging as a death sentence.

Both of these does not require anesthetics, because either you're sentenced to death, or you're dead anyways.

**Comment by ZomgPonies** [comment]
:-1:  Yeah not a fan of giving robotics more tools. They already have enough to do.

**Comment by Crazylemon64** [comment]
Alright, fair enough. I'll shut this down, then.

**Pull request closed without merging**
