### PR TITLE
Adds the Holy Hand Grenade

### PR DESCRIPTION
**Pull request by datlo**
Added the Holy Hand Grenade to chaplain hijack uplinks for 18 TC.

After 5 seconds, plays a Hallelujah. 2 seconds after that, explodes with maxcap strength.

Sprites by Ionward, it glows once you activate it. The fake grenade does not have the glow at all.

holyhandgrenade-i-glow

(Can't see the glow very well here but it's pretty clear in game)

Added the fake Holy Hand Grenade to arcade prizes.

Repathed the holy water clusterbuster to avoid confusion.

🆑
add: Added the Holy Hand Grenade to hijack chaplain uplink for 18 telecrystals, sprited by Ionward.
add: Added the fake Holy Hand Grenade to arcade prize counter.
tweak: Repaths the cluster holywater grenade to avoid confusion.
/🆑

### CODE REVIEW

**Comment by KasparoVy** [comment]
Fuck that's funny. Nicely done

**Comment by Citinited** [comment]
This grenade is sure to make the station more holy! honkhonk

**Comment by datlo** [comment]
This is pretty much as close a "port" as it can be to the original item inspiration, the Holy Hand Grenade from worms armageddon.

The chaplain blessing mechanic was ultimately designed to have no direct gameplay effect other than letting admins know your piety, I'd rather keep it that way myself. Also, chaplain types were not implemented.

**Comment by Pennwick** [comment]
The original item would be the The Holy Hand Grenade of Antioch from Monty Python and the Holy Grail.

**Comment by datlo** [comment]
I know. Hence why i said "the original item inspiration", aka what I based the item on when I coded it.

Also, fuse timer =/= how much you count before you throw it. If you count to how long the fuse is before throwing a grenade, you can kiss your hand/arm goodbye.

In any case, I'm pretty sure this is the design I want to go with for this item. You don't need complex and deep mechanics for every item, and sometimes what you want is a grenade that goes "hallelujah" and makes a big fucking hole in the station. Or, at least, it's what I want.

**Comment by Fox-McCloud** [comment]
I really don't think Chaplain needs yet another hijack only item.

Also, I'd much prefer something have unique mechanics rather than just be "huge giant explosion 2.0".

I'm all for adding a holy hand grenade as a gag (though it being more of a reference to the original would probably be better), but just as a huge boom for hijack chaplains? Too boring.

**Comment by datlo** [comment]
Hmm.

I'll think about it and see if I can come up with something.

**Pull request closed without merging**
