### PR TITLE
Adds recharge stations to the permabrig for IPCs

### PR DESCRIPTION
**Pull request by PopGamer45**
## What Does This PR Do
Adds cyborg recharge stations to the permabrig for IPCs. Now with the map queue dead i believe i can add these to all station at once with only 1 PR, please correct me if iam wrong.

## Why It's Good For The Game
In the permabrig all species can make/get their food themselves except for IPCs who need a secoff to let them charge outside of permabrig, would be good to make all species able to survive on their own in the permabrig without security needing to care for them.

## Images of changes
0MhC37U9p3
I5ZCZNKSsi
MddxxJe75w
NqkxwRm8aM

## Testing
Checked if the recharge stations are there, you never know

## Changelog
:cl:
add: Added cyborg recharge stations to the permabrig, making IPCs able to charge themselves
/:cl:

### CODE REVIEW

**Review by 1080pCat — APPROVED** [review]
im not the *biggest* fan of faragus, and deltas charger locations? but looks fine none the less

**Comment by 1080pCat** [comment]
looks like in the processes of committing [d11329e](https://github.com/ParadiseSS13/Paradise/pull/24605/commits/d11329e7f4ddd32432e660f2095af17996f6389f) you've unintentionally reverted a heap of other mapping prs.
a fix i've found that works is to make sure your main branch is upto date, then copying the map files, going back to your branch, then replacing the map files with the ones you've copied, then redoing the changes

**Review by Henri215 — APPROVED** [review]
looks good to 1080pCat

**Comment by S34NW** [comment]
!merge_upstream

**Review by S34NW — APPROVED** [review]

**Pull request merged**
