### PR TITLE
Updates Syndicate Strike Team gear, ready room, and shuttle

### PR DESCRIPTION
**Pull request by datlo**
This PR is intended to make the SST actually look and feel like a part of the current Syndicate, instead of a squad of syndicates from the previous century that got lost in time or something.

I'll make PRs to update the SST ready rooms of metastation and whatnot if this is merged.

Changes to SST gear
- Added syndi internals box
- Replaced pressurized oxy tank by nukie jetpack
- Replaced reinforced spacesuit by reinforced elite hardsuit. Armor is below dsquad armor, however you can turn it to combat mode, making you much more mobile. Looks the same as the nukie elite hardsuit, for now, I don't think it's a problem tho.
- Replaced pistol and pistol mag by syndicate revolver and mag. SST can now print extra ammo at hacked autolathes to keep the fight going if they run out due to this.
- Added a spare mag for the SAW
- Added a military belt (different color to match the hardsuit)
- Now start with a dusting implant, same as SIT
- Removed flashlight and EMP grenade
- Removed all access on SST IDs. They still get access to maintenance and station exterior airlocks so they don't have to break in to enter the station. They're still agent IDs, so you got syndi access, can copy access, customize, etc.
- A lot of this gear no longer spawns on the SST at spawn, and is instead in the new SST lockers.
- Admin outfitted SST are spawned with their full gear, which was also updated. They don't need to have a gear locker spawned.

Map changes
- Added 3 syndicate bombs beacons, a bomb detonator, 2 upgraded health analyser, a syndi toolbox, 2 multitool to the SST ready room
- Added 6 SST lockers, containing EVA gear and SAW + ammo
- Fixed issues with the blast doors for the SIT and SST shuttles, both sets of blast doors now open and close together, they can also be opened from inside and outside the shuttle now. This lets you lock your shuttle safely from anyone that doesn't have syndicate access, an emag, or can just bypass the blast doors somehow.
- Added atmospherics blocking fans to the SIT and SST shuttle since they don't have a cycling airlock and do not usually dock at a designated docking station. This helps prevent the SIT (who do not start with EVA gear) spacing themselves by going through the wrong door.
- Added an oxygen cannister and two syndicate sleepers to the SST shuttle, removed the obsolete toxin bombs spawner (replaced by syndicate bomb beacons in ready room)
sstchanges1
sstchanges2
sstchanges3

🆑
Add: Updated the Syndicate Strike team's gear and ready room. Syndicate commandos will now be wearing reinforced black elite syndicate hardsuits and pack more ammo and supplies.
Del: Syndicate commandos no longer start with all access.
Fix: Fixed some issues and improved the usability of the SIT and SST shuttle blast doors. They can now be reliably used to lockdown your shuttle from NT would-be intruders, and can be opened from inside and outside.
/🆑

### CODE REVIEW

**Comment by datlo** [comment]
Yeah, they get the full gear.

**Comment by Ty-Omaha** [comment]
I feel like SST suits should be visually different from nukeop elite, even just a visor change to blood red

**Comment by datlo** [comment]
Agreed but I'm terrible at sprites, i'll see if I can get something

**Comment by datlo** [comment]
I've fixed the map conflicts and added the ops hud to SST.

Also, free forgot that the SIT shuttle needs to land next to a wall, cuz SIT don't have spacesuits, they're meant to cut through a wall with a false door. I've adjusted the shuttle landing location, and slightly adjusted arrivals maintenance to fit it.
image

**Pull request merged**
