### PR TITLE
Skateboard Nerfs - The Bigger One

### PR DESCRIPTION
**Pull request by matttheficus**
## What Does This PR Do
**Pre-Approved: MattTheFicus, Komrad, Dudley**

- Skateboards and Pro Skateboards no longer fit in Bags. Hoverboard can still fit in a bag since its expensive. They can now fit on your back slot.
- Craftable Skateboard completely removed from crafting.

- [ ] TODO: Back Slot Sprites

## Why It's Good For The Game
Skateboards are oppressive and frankly needed a Balance pass in hindsight. Security should not be rolling around at mach six arresting people. Speed is, after all, king in SS13.

## Images of changes
TBA

## Testing
Logged in, couldnt equip boards in my bag anymore.

## Changelog
:cl:
tweak: skateboards no longer fit in bags, fit in back slot. Hoverboard unchanged.
del: you can no longer craft the improvised skateboard.
/:cl:

### CODE REVIEW

**Review by Spaghetti-bit — APPROVED** [review]

**Comment by GreatGatherer** [comment]
thank god

**Comment by 1080pCat** [comment]
> Pre-Approved: MattTheFicus,

obvqaa0lhn841

**Comment by Carthusia** [comment]
Perhaps an idea for another PR after this, but one to update the SecWay

Its currently woefully slower than a normal person running and serves no purpose.

Perhaps increaseing its speed to a bit faster than a run to make it a useful, if limited in number, resource for security to use

**Comment by 1080pCat** [comment]
> Its currently woefully slower than a normal person running and serves no purpose.

you can put a vtech on it

**Comment by Carthusia** [comment]
> > Its currently woefully slower than a normal person running and serves no purpose.
> 
> you can put a vtech on it

Does that bring it up to run speed or faster?

**Comment by SynthTwo** [comment]
!wiki_label

**Comment by matttheficus** [comment]
> > Pre-Approved: MattTheFicus,
> 
> obvqaa0lhn841

I use my powers for good i swear :xdd:

**Comment by 1080pCat** [comment]
> > > Its currently woefully slower than a normal person running and serves no purpose.
> > 
> > 
> > you can put a vtech on it
> 
> Does that bring it up to run speed or faster?

same speed as default running

**Comment by Carthusia** [comment]
> > > > Its currently woefully slower than a normal person running and serves no purpose.
> > > 
> > > 
> > > you can put a vtech on it
> > 
> > 
> > Does that bring it up to run speed or faster?
> 
> same speed as default running

Awww, so its still worthless

No real purpose in spending that much in resources just to be able to move at normal speed, when you can just use normal speed on foot, or get a skateboard or scooter that goes faster

**Review by Sirryan2002 — APPROVED** [review]

**Review by DGamerL — APPROVED** [review]

**Pull request merged**
