### PR TITLE
Updates Panther Sprite

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Updates the horrendously shitty panther sprite we currently have.

New Sprite:
panther1
panther2
panther3
panther4

Sprites by @FullOfSKittles 

Thanks, Skittles!

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
:sunglasses: 
:fearful: 
:eyeglasses: 

my god :+1:

**Comment by tigercat2000** [comment]
Well, this is obviously much better than the current sprite, but it still looks kinda odd, especially from the side and front. Does it have a movement animation or something?

**Comment by Fox-McCloud** [comment]
Nope.

**Comment by tigercat2000** [comment]
kinda odd then to see that thing sliding around
Not a big problem I guess just rambling, definately better than the current one

**Comment by ZomgPonies** [comment]
Movement animations would make this :100: 

No movement animations make this :+1:

**Pull request merged**
