### PR TITLE
infinite loop detection in projectile code.

### PR DESCRIPTION
**Pull request by Jey123456**
not sure why it happened nor do i plan on finding out but i know for a fact it did happen. This fix allow round to continue if it happen again.

### CODE REVIEW

**Comment by TheDZD** [comment]
Do you happen to remember the date/time of the round this infinitely looped during? Would be better to address the problem directly rather than implement a bandaid fix for it.

**Comment by Jey123456** [comment]
about 10minutes before my PR

**Comment by Jey123456** [comment]
If youd rather get a callstack in the event of an infinite loop detected, its pretty easy to achieve as well (then iirc the process scheduler would detect the proc died and restart it)

**Comment by TheDZD** [comment]
Huh, looked back and this is #1629 coming back from the grave to haunt us.

**Comment by Iamgoofball** [comment]
why was this closed

**Comment by Jey123456** [comment]
so i take it the issue is fixed and sure to never come back again ?

**Comment by Fox-McCloud** [comment]
Because we're going to be addressing the problem at its base level and fixing that rather than implementing a bandaid fix for it.

**Comment by Jey123456** [comment]
but as i said, its not a fix, its a loop detection. If allows for the problem to be fixed in time, provide data to admins / logs (and can be changed to include call stacks) all the while not causing the issue to be round ending. And also ensure that if another different problem cause an infinite loop in here, then its also caught and provide info for devs to work with without ending rounds.

**Comment by tigercat2000** [comment]
a runtime error because of an infinite loop is infinitely more helpful than "hey so this had an infinite loop and terminated because of it"

**Comment by Jey123456** [comment]
and a runtime can be obtained, just that noone asked for it when i offered it.

**Comment by tigercat2000** [comment]
that wasn't my point, my point was that if a projectile breaks like it did, it _should_ be unhandled, and generate a runtime or crash shit rather than silently fix itself

**Comment by Jey123456** [comment]
and my point is, it can runtime, print a pretty runtime error message in log with all the stack info, give a message to admins and let the round continue once an admin delete the object causing it.

**Comment by tigercat2000** [comment]
@Fox-McCloud said DZD was working on making sure projectiles don't infinitely loop rather than just having a saftey check inside of it's loop to quickly fix an issue whenever it crops up

**Comment by Jey123456** [comment]
well, suit yourself, i did my part in providing a way for the round to continue after i had it happen. any future case of this one are on you.

**Pull request closed without merging**
