### PR TITLE
[READY] TOGGLEABLE DARKMODE

### PR DESCRIPTION
**Pull request by AffectedArc07**
First of all a **HUGE** thanks to @Terilia for helping me actually make this work properly, and for the darkmode chat

**What does this PR do:**
This PR is a better version of #10550 
This one adds a new verb, `Toggle-Darkmode`. Pressing it will toggle darkmode on or off. Preference is stored in SQL. This PR uses existing tables and does **NOT** require any SQL changing. It also adds darkmode chat, thanks Teri

**Images of sprite/map changes (IF APPLICABLE):**
trek1irb1q

Title bar with new icon:
image

Taskbar with new icon:
image

Darkmode chat:
image

All examples of darkmode and lightmode chat:
https://affectedarc07.co.uk/ColorDiff

Changelog button is a little finicky to do without rewriting the whole proc, and will change to a darker theme if you start the game with darkmode

**Changelog:**
:cl: AffectedArc07 & Teri
add: There is now a toggle-darkmode verb to switch darkmode on and off
add: Chat settings also has a dark mode
tweak: The icon for the server is now the paradise palm tree

/:cl:

### CODE REVIEW

**Comment by Nicaragua1** [comment]
Dark UIS are my favourite. I love this thanks:smiley:

**Comment by FlattestGuitar** [comment]
Looks neat.

**Comment by Ty-Omaha** [comment]
1 virgin coder vs 1 chad rpane.rpane

**Comment by KasparoVy** [comment]
rpain***

**Comment by AffectedArc07** [comment]
@KasparoVy I am thinking of a way to make toggleable dark chat box

@Ty-Omaha I will rpane you in a minute

**Comment by variableundefined** [comment]
@AffectedArc07 Conflicted.

**Comment by AffectedArc07** [comment]
DNM, this isn’t done yet

**Comment by AffectedArc07** [comment]
I will make pictures of this when I am home, but a difference of chat colours is at https://affectedarc07.co.uk/ColorDiff

**Comment by AffectedArc07** [comment]
Sample of new chat:
image

Toggles from within chat menu:
w6xo3tqe89

And before you all scream, this is why it disconnects
image

If anyone knows a better solution please tell us

**Comment by KasparoVy** [comment]
HOOOLY fuck yes that's dope

**Comment by variableundefined** [comment]
Is it possible to indicate that the disconnection will happen when darkmode is toggled?

**Comment by variableundefined** [comment]
(Fix will come a bit later)

**Comment by KasparoVy** [comment]
YEEEEEEEEEESS!! LIGHTS OUT BABY

**Pull request merged**
