### PR TITLE
Mapmerge2 2

### PR DESCRIPTION
**Pull request by AffectedArc07**
# DUPLICATE OF #10945 
**What does this PR do:**
This PR replaces our map file layout, and replaces mapmerge with mapmerge2. Regular mapmerge seems very intermittent, and hardly works for a lot of users. The maps themselves have no edits apart from a file layout change. 

Example of lesser diff:
image
*This was me covering multiple rooms in closets*

**Changelog:**
:cl: AffectedArc07
tweak: Mapmerge has been replaced with mapmerge2
tweak: Maps are now the TGM format. This means nothing for people who do not make map edits
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
If anyone makes another map PR I swear to god

**Comment by KasparoVy** [comment]
Sometimes you just gotta know when to hold 'em and when to fold 'em

RIP #10945

**Comment by AffectedArc07** [comment]
I mean tbf I was told to wait
image

**Comment by Citinited** [comment]
Why do you keep on reuploading PRs when you can easily fix map merge conflicts through the git shell

🤔

**Comment by AffectedArc07** [comment]
@Citinited 2 things:
1: These conflicts have new items added to them that arent in my local code. To add them into this would require updating my working tree, and spamming a **LOT** of commits, or travis failing which isnt optimal
2: The conflicts dont show locally, only on github itself, which is fucking broken

**Comment by TDSSS** [comment]
>Mapmerge2 2

Eagerly waiting for Mapmerge 2 2 New (2) FINAL.copy

**Comment by craftxbox** [comment]
~~electric boogaloo~~

**Comment by AffectedArc07** [comment]
ayy

**Pull request merged**
