### PR TITLE
New Boo! spell icon

### PR DESCRIPTION
**Pull request by Arkatos1**
**What does this PR do:**
This PR adds a new icon for Boo! spell, example image below. Currently, Boo! uses generic scroll icon, which is assigned to all spells by default if they do not have any icon on their own.

**Images of sprite/map changes (IF APPLICABLE):**
NewBooIcon

Tested locally without any issue.

**Changelog:**
:cl: Arkatos
imageadd: Added new Boo! spell icon
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I'd almost say write "Boo!" on that somewhere in red but this is good by itself

**Comment by Citinited** [comment]
Excellent!

**Comment by variableundefined** [comment]
I like it

**Comment by KasparoVy** [comment]
Stay spooky my dudes

**Pull request merged**
