### PR TITLE
Gives those crybabies in Medical a screwdriver

### PR DESCRIPTION
**Pull request by SamHPurp**
"Oh I can't charge my defibber in the convinently located Cell Charger, because I can't get the cell out."

Cry babies!

:cl: Purpose2
add: Adds screwdrivers to Medical by the cell chargers for recharging the defibs.
/ :cl:

### CODE REVIEW

**Comment by ProperPants** [comment]
~~Dreams~~ Forum suggestions really do come true.

**Comment by Anasari** [comment]
At least we won't be screwed over anymore

**Comment by taukausanake** [comment]
Personally, I'd make a special Medical Screwdriver just because of the meme that is the Medical Wrench. Hell, even give them slightly better chances at surgery even if that's not acted on the object but the surgery directions.
Besides, a white and blue screwdriver, I think that would look pretty

**Comment by KingPhilipIII** [comment]
What is the meme of the medical wrench exactly?

**Comment by MoreRobustThanYou** [comment]
@KingPhilipIII suicide with the medical wrench in your hand

**Comment by SamHPurp** [comment]
@MoreRobustThanYou its not in our codebase (or well, it is, but its unobtainable through non-admin means)

**Comment by Fox-McCloud** [comment]
sure, why not.

**Pull request merged**
