### PR TITLE
Fox Fluff Item Coat

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just my fluff item. An old rugged brown military jacket with an embroidered "A" on the back. I wonder what it could mean?

img

:cl: Fox McCloud
add: Adds Fox's fluff coat
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Fox has defected to the side of Andross. Deploy the deathsquad

**Comment by KasparoVy** [comment]
A-yy lmao

Looks good.

**Comment by Shadeykins** [comment]
A is for Admin.

**Comment by AffectedArc07** [comment]
It means ***AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA***

**Comment by KasparoVy** [comment]
Or perhaps it's simply a remix of [E](https://www.youtube.com/watch?v=7uPu7rLZWGc)?

**Pull request merged**
