### PR TITLE
Reverts Kissing

### PR DESCRIPTION
**Pull request by SabreML**
## What Does This PR Do

Removes the 'Kisser' item and 'Kiss' projectile, and replaces them with a standard text-based *kiss(es) emote.

## Why It's Good For The Game

Kissing has been a feature for about 3 months now (#15539), and in that time I've genuinely not seen *anyone* who thinks that adding it was a good idea.

The biggest issues it's caused that I can think of off the top of my head are:
1. [It breaks the shields on hardsuits.](https://github.com/ParadiseSS13/Paradise/pull/15716)
2. [It was, until recently, infinitely spammable.](https://github.com/ParadiseSS13/Paradise/issues/16019)
3. [It's 'disarmable' by krav maga.](https://github.com/ParadiseSS13/Paradise/pull/15722)
4. It can be used to give away people with Sleeping Carp, since it's a projectile.
5. It has an incredibly long range. (Half way across the z-level in space)
6. It triggers reactive armour.
7. The ability to kiss people through camera consoles. (Allegedly)
8. It feels, in my opinion, *incredibly* out of place on the server, and really just lowers the RP standard either through kiss spamming down a hallway, or being (arguably) [workplace harassment](https://www.paradisestation.org/forum/topic/20439-make-unwanted-kissing-battery).

On top of that, while it *has* died down a little since the PR was merged, there are still people lying down outside the bridge firing kisses at anyone who walks past for the entire round. For me personally this can go from breaking my 'immersion' at best, to making me feel genuinely uncomfortable at worst.

I just... honestly can't think of a single redeeming feature here.

## Changelog
:cl:
del: Replaced the 'Kiss' item and projectile with a standard emote.
/:cl:

### CODE REVIEW

**Comment by LordShekelstein** [comment]
I can see this _at least_ being minorly cool once the lipstick of death gets added in but right now it's just a hot garbage fire that needs to be removed.

**Comment by S34NW** [comment]
Yeah, while the concept is neat, it's just been encouraging LRP behaviour and workplace harassment.

**Comment by Wojz** [comment]
I haven't seen people do it much anymore.

**Comment by SabreML** [comment]
> I haven't seen people do it much anymore.

Not nearly as often as when it was first added, no, But it does still happen.
Even if nobody used the emote at all, that'd still be a decent reason to remove it.
If people *are* using it, then it lowers the RP standard and makes people uncomfortable (admittedly with some exceptions). If people *aren't* using it then that brings up the question of why it's still a feature, considering the general dislike of it.

In those exceptions where it's actually used properly and IC, the replacement emote would (in theory) still have the same effect, with none of the downsides.

**Review by AffectedArc07 — APPROVED** [review]
I have seen just too much lowRP spam of this for me to want it here anymore.
As I said in my original merge
image
So instead of grinding bones its revert time

**Pull request merged**
