### PR TITLE
Alters brain damage lines, removes slurs from tourette's and sechailer

### PR DESCRIPTION
**Pull request by TheDiode**
## What Does This PR Do
Alters some brain damage lines or outright removes them.

- NYA~ to NYA : OOC text
- grifing to hiting/kiling : Griefing is a gaming term
- THe saiyans screwed : Dragonball Z reference, makes no sense, and it's sexual
- Bi is THE BEST OF BOTH WORLDS : This is making a joke out of a sexual orientation
- FUS RO DAH : Skyrim reference, Skyrim has nothing to do with SS13 unlike WH40K or Dwarf Fortress
- >my face : 4chan reference, OOC text

I also removed the word "cocksucker" from Genetics Tourette's and the emagged sechailer. It's a homophobic slur.

Side note: The sechailer text is way too sexually graphic.

## Why It's Good For The Game
There was an earlier PR to remove OOC text from these phrases, like ";_; LIFELIKE TEXTURE".
The removed references have nothing to do with SS13 at all, except the /tg/ one, we are not /tg/.
Also, homophobic slur removal is always a good thing.

## Changelog
:cl:
spellcheck: Removed some brain damage lines referencing other servers and games, and removed homophobic slurs.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
> I also removed the word "cocksucker" from Genetics Tourette's and the emagged sechailer. It's a homophobic slur.

No. Its a standard insult you can throw at anyone, man or woman. It is not a homophobic slur.

**Comment by Bm0n** [comment]
damn, you want to remove the dragon ball and skyrim references? I hope you're also ready to remove the hundreds of other pop culture references this game has in it

But I do find it funny that you think warhammer and dwarf fortress are fine, both of which arguably also have absolutely nothing to do with ss13

**Comment by Sirryan2002** [comment]
Hey before this PR blows up with discussion over the semantics of alleged slurs, I'd like to remind people that having a discussion over what words are and aren't suitable for our community is good, but should be respectfully held somewhere else other than in the Pull Requests comments. This is needed to keep the focus of the discussion on the contents of the PR, code review, and inputs from leadership (who will have the final say on this). Furthermore, everyone should keep an open mind about this kind of stuff as our playerbase and staff all come from wildly different cultures, backgrounds, and social identities, so an insult that may seem menial and harmless to you may also be incredibly offensive to somebody else. 

Do keep in mind this section from our repositories code of conduct aswell:
```
Under no circumstances are users to be attacked for their ideas or contributions.
While constructive criticism is encouraged, toxicity or general mean-spirited behaviour 
will not be tolerated. All participants on a given PR or issue are expected to be civil. 
Failure to do so will result in disciplinary action.
```

**Comment by Bm0n** [comment]
@TheDiode I can literally use your argument against you by saying 'We're not Baystation, remove the Bay references!' which is what you're doing captain is a comdom line by saying it's from TG so it should be removed(even though it's a Goon reference).

I don't think you quite grasp how many references to pop culture are already in this game. If you're removing these you should be prepared to remove them all.

**Comment by TORE01** [comment]
Hi. I'm a little afraid of putting my opinion here because I couldn't care less about social justice etc. I will be as respectful as I can be because I know some of you are LGBT and I can honestly say I judge people more for what they do, not who they are. 

One could argue that cocksucker is not only homophobic but also misogynistic as well. However, this is one of the lines that you might blurt out if you get the neurodevelopmental disorder tourettes. I don't care about the hailer, but you can't exactly tell someone with tourettes not to say a perticular word because it's homophobic. 

I wouldn't say that tourettes was added to the game to poke fun of people with tourettes either. It's a genetical disorder added in a role playing space simulation game. If you screw up genetics, you might get tourettes. It stuns you and make you say obscene things.
Context matters. I'd say keep it.

Sorry for my not so good English.

**Comment by S34NW** [comment]
I don't think we should be downplaying tourettes to appease another group. It's not intentional on the part of the user and no malice is meant by it, why would people take offense?

Also, calling `THe saiyans screwed` sexual is a bit daft. "Screwed" can mean that in some contexts but this instance is more akin to "ruined" or "harmed" See entry 2:
image

Where do we draw the line with this? Are we going to remove `wanker` because all men might take offense to being categorised as such? You remove `cocksucker` but leave in `MAN EAT A DONG FUCKING ASS RAMMING SHIT FUCK EAT PENISES IN YOUR FUCK FACE AND SHIT OUT ABORTIONS OF FUCK` so I'm generally confused by your logic.

This is political correctness gone too far.

**Comment by AffectedArc07** [comment]
Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.

Please link your account at [https://www.paradisestation.org/forum/custom/link_github_account.php](https://www.paradisestation.org/forum/custom/link_github_account.php)

*If you are seeing this multiple times due to multiple PRs you only have to link once*

**Comment by AffectedArc07** [comment]
No response from PR author in 7 days. Closing.

**Pull request closed without merging**
