### PR TITLE
Makes carrots processable into wedges and makes said wedges fryable into carrot fries

### PR DESCRIPTION
**Pull request by LordJike**
We already fixed potatoes, but we cannot leave carrots behind, can we.
...also, I'm including the changes for my previous PR, as I forgot to give that one a changelog.
:cl:
tweak: Space Fries are now made by deep-frying potato wedges instead of processing them.
add: Introducing carrots inside the food processor gives you carrot wedges now.
tweak: Now you can make carrot fries by deep-frying carrot wedges instead of formerly processing the whole carrots.
/:cl:

I will soon follow this up by applying said tweaks to the wiki as well.

This should be the last of these tweaks I will be making, unless something else starts bothering me badly again.

Actually used proper git tools instead of web editor for this one, p-please praise me.

### CODE REVIEW

**Comment by Anasari** [comment]
I'm hungry

**Comment by Ionward** [comment]
removing carrot shivs = bad

**Comment by LordJike** [comment]
@Ionward Dunno if you are being serious, but carrot shivs might as well be a meme feature, and to be honest, if you have the ability to make carrot shivs, you probably already have a weapon that's more effective.

Also, I've never seen them being used, I'd be surprised if more than 10% of players knew about them until now.

**Comment by Fox-McCloud** [comment]
Yeah, don't remove carrot shivs purely just for this.

**Comment by LordJike** [comment]
Hmm... what would you guys recommend?
Here's a few things I can think about from the top of my mind:

1) Make carrot wedges a processor product and let carrot shivs still be cut by sharp things.
2) Make it so that when you use a sharp thing on a carrot it gives you the option to decide either to make it into a shiv or into wedges (I don't really know how to do this, but I think I can figure it out by looking at other code).
3) Make it so when you use a sharp thing on a carrot, you first turn it into a shiv, then into wedges.

**Comment by taukausanake** [comment]
I was thinking 3 before it was typed. That might be a good choice but two can work too

**Comment by LordJike** [comment]
T-there, fixed, can I get a pass now?

**Comment by taukausanake** [comment]
Aaaaaactually, might be better for wedge and THEN shiv. Wedges are the general shape but shiv is sharper and more finalized. Not to be nitpicky but it would also be nicer to chef.

Carrot shiv fights when?

**Comment by LordJike** [comment]
I'd like to have @Fox-McCloud 's confirmation before making any other changes regarding that, I think that it is a little unfeasible to cut a carrot into thin wedges, then merging said wedges into a shiv.

**Comment by taukausanake** [comment]
I thought they were more like the steak fries you get. The ones that are basically large slices of potato. Let's see what he says then

**Comment by Fox-McCloud** [comment]
Why can't processing carrots just produce carrot wedges and you deep fry those?

**Comment by LordJike** [comment]
@Fox-McCloud It sort of bothers me as it would be asymmetrical compared to cutting potatoes into wedges, would you suggest making potatoes into wedges a processor thing as well?

**Comment by Fox-McCloud** [comment]
You'd have to remove tator-tots to do that.

**Comment by LordJike** [comment]
That's true... the inconsistencies do rub me the bad way though, if you feel like pulling it like this then I'm okay with it, but otherwise I will update it tomorrow/this afternoon

**Comment by LordJike** [comment]
Sorry for the delay, made the change now.

**Comment by Fox-McCloud** [comment]
Remove the changelog and implement it the proper way, in your PR; we don't use that system anymore, and haven't, for nearly a year now.

**Pull request merged**
