### PR TITLE
Custom peace keeper cyborg

### PR DESCRIPTION
**Pull request by The-Driker**
Good Evening 

Due to player request, I have modified and am resubmitting my personal skin for the Peace Keeper borg. 

BEHOLD **DEPUTY DOGER**!
untitled

ezgif-4-a5761a624e

_`Also yes I'm aware I forgot to color the burger light on the still images. It's correct on the sprites, I'm just lazy`._

### CODE REVIEW

**Comment by FreeStylaLT** [comment]
I.. I am okay with this

**Comment by KingPhilipIII** [comment]
*scream

**Comment by taukausanake** [comment]
Please never stop :heart:

**Comment by The-Driker** [comment]
I can't believe Fox gave this a thumbs down. This is completely in line with the server and perfectly fitting.

**Comment by Keilden** [comment]
We really need a Chef module for Borgs  just because a burger Borg making burgers should be a thing. I love your burger Borgs!!

**Comment by The-Driker** [comment]
@Keilden 
Unfortunately with how worried they are about organic crew being replaceable by synthetics, I don't see that happening. Which honestly saddens me and kills a chunk of my love for the place. I would absolutely love to have a Chef Borger and make all of the burgers.

**Comment by taukausanake** [comment]
> organic crew being replaceable by synthetics

lol IPC crew when? Honestly it would be in NT's favor to turn crew into borgs that have a less likely chance to turn against the corporation unless they are tampered with. Robots with laws are harder to mess with than humans with free will and don't even bother with ion laws or rouge AI. Robots are also easier to "fix" after they're not a threat anymore.
Sure would be interesting to have a station run by nothing but borgs. Heck, even the NPC borgs too, like that one space station story has, you know the one about the robot in charge of the trees and a human that teaches it things before he dies and the robot lives on forever or something? Was that Ringworld? I can't remember

**Comment by Jountax** [comment]
Having nothing but borgs on a station seems to me like just asking for the place to turn into a madhouse when enough ionic anomalies pile up. But the place is a madhouse already so...

**Comment by The-Driker** [comment]
Imagine if we replaced cyborgs/androids/robots with player versions of the gateway automatons. All of the bonuses of being a borg, except you look like crew and can be knocked over. 
`-and farted on if it was on goon-`

**Comment by TullyBurnalot** [comment]
Apologies for this taking so long; it's currently being conditioned by the Peacekeeper Revert PR, which unfortunately has not been decided on as of yet; this is to avoid providing a fluff, only to then have to potentially revert/change it.

**Comment by taukausanake** [comment]
Even though I _positively love_ the sprite you made, if for Peacekeeper borg I would have it keep the same "head" for them. You know how each PK borg has a different variant like Sec Officer, Detective, and such. I'd just make this into a burger version for consistency.
Also as a visibility/functionality stance. No one will know what this borg is unless they shift-click it first. I think it's kind of important to know what some things are at first glance and borgs are one of them. But that's just an opinion and not me saying to change the sprite

**Comment by The-Driker** [comment]
@taukausanake 
I considered making it look more like the regular peace keeper, but after looking at Peace Keepers, I found their overall design to be hideous and completely unappealing. I tried and couldn't find a way to combine a peacekeeper and burger in such a way that I was happy to look at it. 

I did try though.

**Pull request closed without merging**
