### PR TITLE
Re-bushes escape 🌳

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Old bushes:

New bushes:

You never knew you wanted these bushes there so badly.

Also, you can walk through these.

:cl: FlattestGuitar
tweak: Escape has been re-bushed.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Now it's utterly impossible to retrieve anyone who gets stuck in the middle without teleporting them back out or using bombs to destroy the bushes.

**Comment by LightFire53** [comment]
That there is a nice bush.

**Comment by Anoonki** [comment]
@FlattestGuitar  What's being said is that from an IC standpoint, that's just really poor decoration and design.
You'd need to push through a bush to actually read the plaque.

**Comment by Fox-McCloud** [comment]
I like!

👍

**Comment by FlattestGuitar** [comment]
Hey, that comment was edited after I posted my passive-agressive response! That's not-cookie-deserving behavior.

Changed to have that one bushy bush free; I didn't think of that.

**Comment by tigercat2000** [comment]
@Anoonki @KasparoVy I think you two need to think more *abstractly.*
What if, we are actually seeing a top down representation of a horizontal plaque that would be viewable by the spess men? 👽

**Comment by taukausanake** [comment]
I always thought of it as a floor plaque. They have those after all and they are just as good as mounted plaques

**Comment by FlattestGuitar** [comment]
It's actually a two-sided ceiling plaque that we can see from a different side than the spessmen.

**Comment by pazneria12** [comment]
BRING ME A SHRUBBERY

**Pull request merged**
