### PR TITLE
Tweaks Flashing from Welding Metal

### PR DESCRIPTION
**Pull request by Aligotess13**
## What Does This PR Do

Removes the first immediate flash when welding metal. Provides a brief moment for the person to stop welding if unintended.
## Why It's Good For The Game

From what I've read and seen, the blinding flash when the welder first hits metal was an unintended Nerf that greatly limits its use. It greatly hinders both conventional and blob combat, as well as being unintuitive. Welders are already limited by fuel use, and the experimental welder is about as advanced as other tools that can deal similar amounts of damage, like the advanced plasma cutter.
In real life, if you graze metal with the tip of a blowtorch's flame, it wouldn't immediately start burning your eyes. This tweak would still make welding realistic/balanced without influencing much except slightly improving combat and QOL.
## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/89031914/4b0e67cf-35e5-4d7b-965b-88d637c07849

## Testing

Tested welding on walls and vents.
## Changelog
:cl:
tweak: Tweaked welding tool's flashing
/:cl:

### CODE REVIEW

**Comment by A-Medster** [comment]
Seems like a really good idea, gos knows ive been blinded wnough because im clicking as fast as i can and start welding something
Though it may be of use if you added in some footage of what happens if you keep welding the wall for longer than a split second

**Comment by 1080pCat** [comment]
This makes sunglasses protect against all welders, since the primary flash is the main one that only the research/proto welder don't do with sunglasses.

**Comment by Contrabang** [comment]
How long is it before the next flash?

**Comment by BasilTamaya** [comment]
Thank god, I can actually kill bats in maints without accidentally blinding myself.


Farragus.

**Comment by matttheficus** [comment]
Balance wise I think making there be a downside to not having eye-pro for welders is good.

Does it match 1-to-1 for IRL? No.

But SS13 aint IRL. Stuff can exist solely for Balance or gameplay reason.

Imma say I'm against this.

**Comment by Bjamcham** [comment]
In its current implementation, you only weld down walls if you use the welder on harm intent. If you swap to help, you will only begin welding if the wall/floor is damaged. I don't really see a need for this change with regards to using welders as a weapon when you can already avoid this by swapping your intent.

**Comment by Aligotess13** [comment]
> Balance wise I think making there be a downside to not having eye-pro for welders is good.
> 
> Does it match 1-to-1 for IRL? No.
> 
> But SS13 aint IRL. Stuff can exist solely for Balance or gameplay reason.
> 
> Imma say I'm against this.

Funny enough, my reference to reality was in response to if **MY** PR was thought to be unrealistic. Either way, the downside to not having eye-protection is getting your eyes burned out, the unintentional buff to sunglasses has been solved. For the most part, this is a quality-of-life change that will make combat slightly less debilitating and more intuitive.

**Comment by Aligotess13** [comment]
> This makes sunglasses protect against all welders, since the primary flash is the main one that only the research/proto welder don't do with sunglasses.

This has been solved. Flashes are now more intense but occur less often. It takes two welding attempts to burn out unprotected eyes like before. Sunglasses are also flashed again now, two times, in fact.

**Comment by Aligotess13** [comment]
> Seems like a really good idea, gos knows ive been blinded wnough because im clicking as fast as i can and start welding something Though it may be of use if you added in some footage of what happens if you keep welding the wall for longer than a split second

> How long is it before the next flash?

It was shorter before but after the new commits.

https://github.com/ParadiseSS13/Paradise/assets/89031914/3c279459-948f-4a87-a468-9ac6d9951397

**Comment by Aligotess13** [comment]
This will remove flashing from welding rods to make metal or similar. However, considering the fact that the initial proc had code to not flash when repairing prosthetic limbs. I think flashing from welding rods doesn't contribute much to balance or the overall experience of the game either. I consider this a QOL change too.

**Comment by Aligotess13** [comment]
> After looking into how the welder flash functions, the changes alter a lot more than you're either aware of or have updated on the PR.
> 
> Removing the initial weld flash means that any item that does not require a welding time no longer flashes the user, this includes rods, false walls, glass, any sort of damage repair to walls or floors, and more. Increasing the time between flashes from 1 second to 4 also drastically reduces the white flash malus a player sees. Additionally, anything 4 seconds or under won't blind the user at all, such as AI core deconstruction, girder deconstruction, railing repair, and shower removal, just to name a few examples. Objects with weld times that aren't 10 seconds will have varying degrees of blindness damage caused when compared to the 1 second 1 intensity flashes.
> 
> Personally I'm not a fan of drastically reducing the maluses of using a tool without proper equipment solely to increase its capabilities as a weapon. If you really want to remove the initial blind from walls, you'd likely need to find some way to differentiate between `welder_act`s that require time and those that don't.

Right, I have tried to resolve some of these problems. There is now a heavy flash and light flash proc. Heavy is still 4 seconds and light is 1.9 seconds. With this addition, most structures referenced will again do light intensity 1 flash, which is the weaker variant currently being used for after flashes. This means sunglasses are slightly more useful in this aspect, however, welding walls now does more damage more quickly, flashing sunglass users 2 times. Although, a human would still be blinded at the 2nd welding.

Welding procedures that require the initial flash procedure, like rods, I don't believe add much to the game experience.

With this reform, the initial intent to make welders more intuitive is kept without obstructing much else. I hope there are no other major oversights in balance.

**Comment by Aligotess13** [comment]
This is the welding procedure now.

https://github.com/ParadiseSS13/Paradise/assets/89031914/d8cee769-eab6-4661-8d49-fdd5948c0a94

**Comment by Burzah** [comment]
Hello! Since this PR has now passed the 30 day period and does not meet the requirement for approval, I am reaching out as a member of the development team. Currently there are 4 objections and no approvals listed on this PR. The general consensus from the balance team is that these changes will make the welder too strong of a tool and that players should exercise more caution when choosing to use the welder as a weapon. The concern being that the balance team does not want the welder to become the go to tool for fighting without any real drawback, and that if you are using it in desperation there should be some risk. 

Going forward, I would say that if you intend to make changes to the welder through this PR, that you work with the balance team to see if there is something that can be implemented that they will find acceptable. You can either try to do that here, or reach out to them on discord. At this point if no activity is seen to make this going forward, this PR may be closed by the appropriate staff member.

If you have any questions, feel free to ask.

**Pull request closed without merging**
