### PR TITLE
Adds more graffiti and updates current graffiti sprites

### PR DESCRIPTION
**Pull request by IcyV**
Graffiti

Sprites courtesy of FullOfSkittles

Edit:
Graffiti Fixes
Changed how other graffiti was done so they can be colored as well instead of stuck being black.

:cl: IcyV
add: Adds in an amount of new graffiti
fix: Fixes the issue of other graffiti only being able to be done in black.
/:cl:

### CODE REVIEW

**Comment by Lady-Luck** [comment]
Wait, is the ability to choose graffiti colors fixed?

**Comment by Fullofskittles** [comment]
> Wait, is the ability to choose graffiti colors fixed?
It was broken? When?

**Comment by IcyV** [comment]
@Lady-Luck I didn't know it was ever broken in the first place. I did all of the ones visible with a spraycan but confirmed they also work with crayons just fine.

**Comment by Lady-Luck** [comment]
#4692 mentions that only black graffiti is functioning. Did this change at some point and I missed it?

**Comment by Fox-McCloud** [comment]
Not all graffiti has that issue; it's only some---the ones that came from VG.

**Comment by Fullofskittles** [comment]
> #4692 mentions that only black graffiti is functioning. Did this change at some point and I missed it?

I noticed this when we tested the graffiti. I originally made all the graffiti in very dark black but color must work different with graffiti than it does with player icons. I adjusted the coloring on all the graffiti i made to be lighter (or in some cases pure white) and they're perfectly colorable. I expect the reason some graffiti doesn't change color is due to the fact that some of them are solid black which absolutely will not change color.

**Comment by Necaladun** [comment]
Love seeing these in actually graffiti styles.

**Comment by Regen1** [comment]
should add spray paint cans for extra gang oriented warfare

**Comment by Iamgoofball** [comment]
holy shit these are really fucking pretty

@Regen1 You guys dont have spraycans and gang mode yet?

**Comment by Regen1** [comment]
@Iamgoofball We don't have gangs, no

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

We have spraycans, but not gangs.

**Comment by KasparoVy** [comment]
@ any of you guys who're wondering why the graffiti has to be as white as possible, please check the Byond documentation [here](http://www.byond.com/docs/ref/info.html#/atom/var/color) that explains how object colouration via the colour var works, particularly the section that says 

> This color is multiplied by the icon, so that a white icon will become this color. The color multiplier is also applied to maptext.

If you want to learn more about color multiplication, please check [here](http://www.byond.com/docs/ref/info.html#/icon/proc/Blend). I know it's the page for the blend proc, but it explains the difference between icon addition, subtraction, multiplication etc. etc. a bit better.

**Pull request merged**
