### PR TITLE
Fixes some typos

### PR DESCRIPTION
**Pull request by BiancaWilkson**
## What Does This PR Do

Fixes some typos in certain lists
## Why It's Good For The Game

Typos are bad (if funny) and Contra will give me 30 paracoin for this
## Testing

Spawned all the outfits and species, had a fashion show
## Changelog
NPFC

### CODE REVIEW

**Review by Contrabang — APPROVED** [review]
LGTM

**Review by DGamerL — APPROVED** [review]
Ah yes, a list

**Review by Contrabang — APPROVED** [review]
Code updated, reviewing again. LGTM

**Review by DGamerL — APPROVED** [review]
Remind me, do we have review GPB and if so, can I see how much I have?

**Review by lewcc — APPROVED** [review]

**Pull request merged**
