### PR TITLE
Expands Chief Engineer Office, makes Engineering foyer less clustered, makes engineering hallway more like a lobby.

### PR DESCRIPTION
**Pull request by Quantum-M**
## What Does This PR Do

Expands the Chief Engineer's office to be a bit more open (with it also getting a filing cabinet), along with making the foyer and it's entrance a bit less clustered with items. Along with that, makes the outside area look more like a lobby.

Along with that, runs a wire through the foyer entrance airlock instead of through a wall.

The maintenance tunnels and assembly line were shortened a bit to take into account of the changes.

## Why It's Good For The Game

Gives the Chief Engineer a much nicer/expanded office area, makes it easier to go through the engineering foyer, and gives the outside area a more lobby look instead of another desolate hallway area.

## Images of changes

<b>Before:</b>
image

<b>After:</b>
image

## Changelog
:cl: Quantum-M
tweak: Expands Chief Engineer Office and gives it a filing cabinet.
tweak: Shuffled some things and added a small extra space in Engineering Foyer for more ease of movement
tweak: Made the hallway outside engineering look like a lobby.
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
You appear to have done something to the xenobio slimes while you're at it, could you see what's happened for me?

**Comment by Quantum-M** [comment]
This would be a Cyberiad map edit, not a Delta one, sorry, should had specified it on the title.

**Review by S34NW — CHANGES_REQUESTED** [review]
Okay, overall I like this but there are a few issues:

First:
image
As seen here, the floor is a lighter colour than the rest of the area, it would be nicer to have them match or give it some more life somehow. Feels a bit bland currently. Perhaps you could put yellow edging on the turfs?

Second:
image
Please avoid running scrubbers pipes over vents/scrubber structures like is seen here, it leads to issues randomly with atmos piping.

Third:
image
The chairs in the middle of the room here feel a tad awkward, perhaps you could put a small grass square/area enclosed in railings as a soft obstacle that also looks nice?

**Comment by DoctorDrugs** [comment]
Honestly you really should be doing a before and after set of screen shots to show the exact differences between areas in this PR, It's standard practice to show exactly what is changing with map edits

**Comment by Quantum-M** [comment]
Requests implemented and before and after pictures posted on the main body.

@S34NW

**Comment by LightFire53** [comment]
With the polish from Sean's suggestions, it looks rather nice! 

You have the same tag on both of the CE's doors which means when you click on that button, both doors will open at the same time. Considering they are "aimed" at 2 different part of engineering, not sure if that was intentional or not?

In addition (I know it wasn't you, it's like that on live), is it possible to fix the disposal pipe heresies? They are technically breaches of our mapping guidelines (barring extreme cases), and should be adjusted. Since you are in the area, maybe you can take a crack at it? Unfortunately, due to how much disposal routing occurs there, there isn't a 100% clear way to clean it up.

image
image

My only thought would be maybe something like this to clean up, not sure what @S34NW thinks? I personally don't like running pipes under windows, but it's the lesser evil compared to walls.

image

**Comment by Quantum-M** [comment]
New picture of new changes on the main body of PR

Implemented your suggestions, @LightFire53 

Along with that, rotated the consoles and chair placements to be opposite to the east door.
Made the door control only open the east door, and moved the button that can control it to the desk.

**Comment by S34NW** [comment]
> Honestly you really should be doing a before and after set of screen shots to show the exact differences between areas in this PR, It's standard practice to show exactly what is changing with map edits 

You can see a before and after in map diff bot, there is no need to spam the PR with images

**Comment by dearmochi** [comment]
image

This wiring is *not good at all.* Please run them under the airlocks and make sure they go straight to the APC.

**Comment by Quantum-M** [comment]
Wiring updated, @dearmochi

**Comment by AffectedArc07** [comment]
After a discussion within server leadership, we have decided to halt your PRs due to your use of multiple ckeys without informing server administration

```

Using multiple accounts for yourself during a round (Multikeying) is not allowed. Simply having multiple accounts, by itself, is permitted - but we require you to inform us so we can add a note that these accounts are both yours.
```

This block will be removed once the server administration have been informed of your alternative ckey.

**Comment by AffectedArc07** [comment]
Info has since been added. PR block removed.

**Comment by dearmochi** [comment]
> Wiring updated, @dearmochi

I think you forgot to push your commit.

**Comment by Quantum-M** [comment]
Commits pushed, sorry about that, @dearmochi

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
