### PR TITLE
Enhances the Delta Supermatter Engineering Experience

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
The pipework has been completely redone, it is now colour-coded and built consistently with the other 3 stations.

The SM waste can now be pumped into the waste loop (like on Cyberiad).

There are now N2 canisters and empty canisters pre-installed in the appropriate ports.

Removed the random fans and scrubbers that used to occupy the ports.

The cooling loop has been expanded from 45 to 80 HE pipes (compare: Cyberiad has 72).

There is now an emitter chamber complete with reflector boxes, consistent with the other 3 stations.

The radiation collectors are now pre-anchored (who the hell thought that not anchoring them was a good idea).

Removed an atmos suit storage unit.

Added 2 extra showers and high traction flooring.

The solar array has been moved to give the cooling loop space to breathe. It also has an extra cable coil now.

The left arrivals docking area has been pushed upwards by 2 tiles so the ERT shuttle can breathe (due to the new position of the meteor wall).

The optical meson scanners have been moved from the top left corner of the engine room to outside the engine room so you do not need to hallucinate to get them when the engine is active. The high pressure water tank had to be moved to make room.

Added 2 RPEDs to the engine room.

Added some plant pots.

Added a single pair of engineering scanning goggles.

Added a geiger counter.

Relocated the thermomachines.

A vent and scrubber have been placed in the turbine room.

The Atmos APC is now a critical APC due to power being lost near-instantly due to the high level of machine power draw in the room.

The solar array now has the correct area designation.

## Why It's Good For The Game
The engine room on delta is uhh, kind of not great, especially compared to the other 3 stations. This should hopefully bring it up-to-spec and make people more willing to actually use the engine despite the tesla being there.

## Images of changes
image
image
image
image
image
image

## Testing
Spawned in.
Checked everything was there and that all filters were correct.
Set up the engine.
Waited for a 10 minutes, nothing delaminated, so it probably works.

## Changelog
:cl:
tweak: Tweaked the Delta SM. Read the full changelog for details.
/:cl:

### CODE REVIEW

**Review by Sirryan2002 — APPROVED** [review]

**Comment by Sirryan2002** [comment]
What did you change in the latest commit?

**Comment by Fordoxia** [comment]
> What did you change in the latest commit?

Oh, I added a pair of vents in the room south-west of the SM, where the airlock to access the solars are.

**Comment by warriorstar-orion** [comment]
@Fordoxia 

When I spawned in and started the round, Atmos proper ran out of power basically instantly. Is this expected or should this area also have a critical APC?

2024_07_03__10_33_11__Paradise Station 13

2024_07_03__10_33_46__Paradise Station 13

**Comment by Fordoxia** [comment]
> @Fordoxia
> 
> When I spawned in and started the round, Atmos proper ran out of power basically instantly. Is this expected or should this area also have a critical APC?

It's expected due to high power draw and tiny APC. but also really annoying. I have replaced the APC with a critical one.

**Comment by warriorstar-orion** [comment]
@Fordoxia 

The decal usage here seems inconsistent

2024_07_04__12_43_47__paradise dme  deltastation dmm  - StrongDMM

Are both of these firealarms necessary?

2024_07_04__12_51_26__paradise dme  deltastation dmm  - StrongDMM

Please fix this piping

2024_07_04__12_42_59__paradise dme  deltastation dmm  - StrongDMM

All of the airlocks in this screenshot are keyed to atmos access only, meaning engineers can't work on this SM at all. 

2024_07_04__12_50_51__paradise dme  deltastation dmm  - StrongDMM

**Comment by Fordoxia** [comment]
Issues in above comment addressed. After discussion with Warriorstar in coding chat, it was decided that access should be atmos only.

**Review by warriorstar-orion — APPROVED** [review]
LGTM, thanks for discussing and working through all the requested changes

**Review by Burzah — APPROVED** [review]
Approved. On a side note, please fix your master if you haven't already.

**Pull request merged**
