### PR TITLE
Ports Metastation's latest AI Satellite to Cyberiad (Doesn't port Meta's tcomms)

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Major changes:

- The walls are thick af now.

- Way more liquid dispensers

- Additional, 5th turret in the AI Core chamber

- Shutters for both the AI Core and the entrance to it

- Transport tubes got dat loop :loop:

- Connects the AI Satellite via atmos and power to the station, AI Core remains independent, however, except for vents.

img

img

img

img

img

:cl: FreeStylaLT
tweak: Ports Metastation's AI Sat's non-tcomms half to Cyberiad.
tweak: Consequently made the AI Sat more secure by various changes made with the port (more walls, liquid dispensers, additional turret, etc.)
/:cl:

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
-1 for the commit pun.

Screw you, Free.

**Comment by FreeStylaLT** [comment]
I'm sorry for having.. upsat you. @TullyBurnalot

**Comment by FalseIncarnate** [comment]
The shutters on that door probably should be blastdoors to match other lockdown areas' doorways.

That being said, I REALLY don't care for the blastdoor/shutter bit because that is going to be even more of a pain on malf rounds since they can't really be opened short of a button or somehow getting the power to the door offline and using a fireaxe/crowbar.

**Comment by Taaketa** [comment]
I do like everything Metastation so I automatically like this.

**Comment by KasparoVy** [comment]
Max cap tox bombs booyeeeee

**Comment by Kyep** [comment]
I like this. 

My only suggestion would be to have a feed from station power into the AI chamber's SMES. An in-only feed, so the station tops up the AI core's SMES, but turning off station power won't lead to the AI dying. Basically just a fluff thing which explains why the AI core SMES is topped up at the start of every shift.

Also not sure about the shutters versus windows directly north of the AI core, but I assume there's a good reason why there is one to the north but only windows on the sides.

**Comment by taukausanake** [comment]
@Kyep It has to be in-only otherwise a powersink would kill the AI as fast as any other part of the station.

Does the other end of the transit tube have da loop?

**Comment by Fox-McCloud** [comment]
Not too keen on this. Don't mix the maps. Keep Metastation with Metastation and boxstation with boxstation.

Meta generally gives people access to more tools, power, direct access, etc. As such, that design is consistent with meta, but *not* Boxstation.

TG did, however, update Boxstation's satellite to address some of its current design issues; *that* would definitely fit, but not this.

**Comment by IcyV** [comment]
More or less what Fox said. Keep the maps separate. There's less value in each map if they share some of the exact same areas.

**Comment by FreeStylaLT** [comment]
oh crap did I port this to Cyberiad? My mistake! :smirk:

**Pull request closed without merging**
