### PR TITLE
Heat Proofing Glass Airlocks

### PR DESCRIPTION
**Pull request by uraniummeltdown**
Currently only glass research airlocks block all heat, now you can make a glass airlock heat-proof by using 1 sheet of reinforced glass on the assembly during construction instead of regular glass

:cl:
add: You can now create heat-proof glass airlocks by using a sheet of reinforced glass on the assembly during construction. Regular glass airlocks just require a sheet of glass.
/:cl:

### CODE REVIEW

**Comment by Taaketa** [comment]
Would it not be better to use Plasma glass to stop a borg using the sheets of reinforced glass it starts with to make all the station firelocks safe?

**Comment by uraniummeltdown** [comment]
This is only for airlock assemblies not firelocks or firelock frames

**Comment by Citinited** [comment]
Plasma glass makes more sense for fireproofing, but this is a nice addition regardless

**Comment by KingPhilipIII** [comment]
It was to my understanding it already used rglass for air locks?

**Comment by Citinited** [comment]
Indeed, but reinforced glass isn't fireproof

**Comment by DesolateG** [comment]
@uraniummeltdown what glass airlocks do the incinerator and turbine use? Standard glass airlocks right? Those stop heat.. or are they mapedited to do that?

**Comment by uraniummeltdown** [comment]
They're varedited standard glass airlocks, they have``` heat_proof = 1```

**Comment by DesolateG** [comment]
I assume 0 is no 1 is yes?

**Comment by Crazylemon64** [comment]
Plasma glass would make more sense here

**Comment by Dinarzad** [comment]
Yi. I think being able to construct or reconstruct heat-proof airlocks or glass airlocks is a good thing, but it should need the use of plasma glass, it fits more thematically, and it's more consistent with how you fireproof walls as well (Needing an extra sheet of plasteel on an R-wall.)

**Pull request merged**
