### PR TITLE
Upgrades Combat

### PR DESCRIPTION
**Pull request by IK3I**
No one likes a fist to the face. That could leave a mark. The boys down in research say they've got a solution. Now they wouldn't go into too much detail, or maybe I just wasn't listening, but there was somthing about fat storage and hands.

Now I know what you're thinking, "I didn't agree to this" or "Why are my hands swelling?!?"
Don't be alarmed, that's just the gene therapy, we put it in the air supply to make sure you all get to see the benefits first hand.

Anyway, you all have fun down there and bring us back some good research material, I hear the team has some grand plan for a new AI model they want to show me. Think they said the name was APRIL? I woulda gone with ALICE myself, but I know better than to go after some old fools.

:cl:
tweak: Genetic modification of your hands makes your punches hurt but not wound, It's like you're wearing boxing gloves all the time!
/:cl:

### CODE REVIEW

**Comment by Spartan6** [comment]
Not as clumsy or random as a blaster.

**Comment by DarkPyrolord** [comment]
Removal of disarms and grabs by default, I'm all for this PR.
👍

**Comment by SkeletalElite** [comment]
Wait, so no more 1 shot push through a 75% block chance? Hooray

**Comment by taukausanake** [comment]
I hate April Fools. I'm too autistic for it.

So this just makes everyone punch like they have boxing gloves whenever or not they have them on? I'm only asking because I'm trying to read code better

**Comment by IK3I** [comment]
@taukausanake that is indeed exactly what it does. The default martial art style becomes boxing.

**Pull request closed without merging**
