### PR TITLE
Connects Cargo Maintenance with Engineering Maintenance on BoxStation

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
Adds a new maintenance wing that connects the (former) disposals maintenance to engineering maintenance, inspired by #12119.

## Why It's Good For The Game
More maintenance, more loot, more places to antag, more paths to get around.

## Images of changes

image

## Changelog
:cl:FreeStylaLT, LightFire53
add: New maintenance wing connecting Cargo maintenance to Engineering maintenance
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
This is really cool!! I always wanted these two maintenances to connect. A little feedback:

### Abandoned crate
This crate is a 4-digit locked crate, I have two concerns about it:
1) It can spawn some _very_ powerful items like a **hand tele or a usable soul stone**. If you add it here, especially as a guaranteed spawn, expect people bumrushing this place every single round. I would replace this with a regular crate with a spawner in it, but it is up to you!
2) If people fail to open it, it explodes. It is right next to a welder tank. Now, most regular players know these things explode, but cargo is the de facto beginner department in which CTs are often sent out to "hunt for crates". You can keep it there as a "trial by fire" gameplay for newer CTs, but I expect frequent breaches in there!

image

### Cigarette vendors
Starting from cargo and going aft, in less than 30 seconds I found two cigarette vendors. That is a little too often, I think... Especially since vending machines in maintenances is not frequent. I would suggest making this one or both starting out with cut wires, so they are depowered - that way they would have a reason to be "abandoned" (but they are still easily fixable)!

image

### Stacking machine console
Not sure if you intended this to be visible from the outside. For me, it would be more logical to be above the stacking machine, only visible from the inside, but if this is deliberate, then please ignore this!

image

### Disposals are venting
The blast door on my left is missing a "tiny fan". Without it, with every ejection, this room is getting vented.

image

### Disposals fire alarm does nothing
Apart from beeping, nothing happens, there are no firelocks.

image

### Large crate has an old sprite
Not a mapping issue, but this crate has an old sprite and it is quite jarring. Consider adding a different crate or a locker here?

image

### Bonus
This painting says "mech painting". It depicts an ED. Literally unplayable.

image

**Comment by SteelSlayer** [comment]
Can you make that var edited closet where old disposals was a `closet/cabinet` so we don't get the purple/white square showing up?

**Review by S34NW — CHANGES_REQUESTED** [review]
As it currently stands, as we discussed on discord, I feel the long corridor design isn't great. At least one secondary path is really required here, even if it is suboptimal compared to the main corridor. I am not sure a single linear hallway is the best way to handle it when we have enough room for variety.

I also have issue with the gambling room, considering one just like it exists to the south of the abandoned vault a mere 2 rooms away.

I'm really glad someone is picking the "interconnected maints" torch again, but I really feel these points do need addressing. (As a note this was discussed on discord with Light, but discussions get buried there fast so noting it here too)

**Review by S34NW — COMMENTED** [review]
This design is an improvement over the one I left a comment on previously. The dual walkway thing is unique but will have to see how it works in practice I think. Will review actual mapping stuff soon.

**Comment by Qwertytoforty** [comment]
My one main concern is for nukies, blocking off their access to cargo, requiring nukies to go through 4 windows / walls, _presuming_ crew doesn't start rcding more baracades down in that area / setting up guards there to warn crew they are coming. Just a thought.

**Comment by LightFire53** [comment]
> My one main concern is for nukies, blocking off their access to cargo, requiring nukies to go through 4 windows / walls, _presuming_ crew doesn't start rcding more baracades down in that area / setting up guards there to warn crew they are coming. Just a thought.

It's why I was trying to keep it as a single hallway done in glass, but there were concerns from other that it made it too linear in options. An option that I sort of looked at was Meta's death maintenance bridge, but once you open it once it spaces all the atmosphere

**Comment by Bm0n** [comment]
this cobweb here is going to be oddly placed if it does actually spawn.

image

This landmark is varedit named "blobstart". we don't have blobstart landmarks anymore

image

not really a full review because I just don't have the time tonight but man... I am not a fan of the dual glass hallway, that left side will never be used. I think just connecting the two hallways and making a bigger more dynamic maints area with walls and grinders would be better.

also most of the new maints areas are just 2x2 and that's it, there's little in the way of pullable things or cover to block shots wth most of the crates being down by disposals

One of the maps that does a good 2x2 maints is Delta(at least the tg version). Should look at it for some inspiration as I did for Meta. Delta tends to break up a lot of the 2x2 with girders and other pullable objects

**Review by S34NW — APPROVED** [review]
map is fine

**Review by SteelSlayer — APPROVED** [review]

**Review by Bm0n — CHANGES_REQUESTED** [review]
This blob start spawner needs to be removed and replaced with the NAD respawner

image

And this random cobweb spawner isn't placed right 

image

These are actual mapping errors, not opinion

**Comment by LightFire53** [comment]
> This blob start spawner needs to be removed and replaced with the NAD respawner
> 
> image
> 
> And this random cobweb spawner isn't placed right
> 
> image
> 
> These are actual mapping errors, not opinion

Woops I recall reading these, but thought I had implemented them

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
