### PR TITLE
Tweaks Black Market Packers Away Mission

### PR DESCRIPTION
**Pull request by Kyep**
Changes:
1) Adds carp around the ship, which have to be dealt with creatively by manipulating the ship powergrid. 
2) Adds a hidden syndi smuggling post on the away mission asteroid.

🆑 Kyep
tweak: Adjusted Black Market Packers away mission. It now has some danger to it (carp), some more interesting stuff to find (syndi lab) and a challenge (fix the ship powergrid).
/🆑

### CODE REVIEW

**Comment by Aurorablade** [comment]
again, enhance the puzzles aspects/exploreing aspects. not add combat.

**Comment by Kyep** [comment]
The issue with that, @Aurorablade, is that this is pretty clearly established to be a crashed ship, crashed due to pilot drunkenness. What could we add as a puzzle/exploration element, within the confines of a ship that crashed for that reason? Atmos issues aren't really a challenge. We could have the ship depowered... but that would simply mean people crowbaring open the doors. I struggle to think of anything that would work as a puzzle/exploration aspect with this theme, in this map size. 

I did have an idea to put a little syndicate base on the asteroid the ship crashed into, which you could find via space exploration. Wasn't sure what I could put in there that would be fun to explore, though.

**Comment by taukausanake** [comment]
Depower the ship with bolted doors. Find a way to repower the ship and then go through it. Might need some more mapping but what harm could that do?

**Comment by Kyep** [comment]
@taukausanake Fixed map merge conflict. Depowered doors by default. Made power actually work for these missions. Power is now much more interesting a question throughout the ship. Added a little syndi area that dedicated explorers can find.

**Pull request merged**
