### PR TITLE
Mining Outpost remap v1.1

### PR DESCRIPTION
**Pull request by M3hillus**
Major overhaul to the main outpost

- Adds a Mechbay for both maintenance, parking, and ease of ingress/egress from the outpost for those ripley pilots.
- Adds a breakroom, complete with the station's only garbage can!
- Moves the Telepad, RCS, and Mint to a loading dock style room.
- Removes all the unused mining equipment; Stacking machines, Smelter, Belts.
- Adds a light to the dorms side of the bridge, fixing that dark area that has evaded mapping for ages.

m3himap

Questions, Comments, and Input appreciated.

### CODE REVIEW

**Comment by Markolie** [comment]
Both rooms need a light switch. And do they have unique areas?

**Comment by M3hillus** [comment]
They do.

**Comment by SamCroswell** [comment]
That looks awesome. Wholeheartedly support this.

**Comment by Markolie** [comment]
Yea, lookin' good!

**Comment by taukausanake** [comment]
I understand the not-need for the smelter and stacker in mining but I think I'm going to miss the purpose they served

**Pull request merged**
