### PR TITLE
Adds updated bluespace tile sprites (you know, the ones that make you run really fast?) Mk2

### PR DESCRIPTION
**Pull request by GunDOSMk1**
What it says on the tin! Spirtes courtesy of @Very-Soft

bluespace_floor

EDIT: In a normal hallway
screenshot 2017-07-20 22 43 54
screenshot 2017-07-20 22 43 54

🆑
rscadd: Adds an updated sprite to bluespace tiles, no more is it icky looking!
/🆑

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Question: Whats wrong with the current sprites?

**Comment by shazbot194** [comment]
It's ultra bland, and there is literally no reason not to update it to something interesting like this.

**Comment by Birdtalon** [comment]
I actually prefer this sprite to the current ones.

**Comment by Balthusdire** [comment]
YES PLEASE! Those look nice and I hate the current seizure tiles we have.

**Comment by GunDOSMk1** [comment]
> Question: Whats wrong with the current sprites?

Personally, when I first saw the things, I thought they were dangerous. This clears up the sprite quite a bit. And overall makes it nicer looking.

**Comment by Very-Soft** [comment]
The current sprites have a couple problems imo:

With how suddenly and brightly they flash, when placed in large amounts it's rather ugly and hurts my eyes a bit.

Also, they look dangerous, electrified. I remember avoiding them when I first played.

**Comment by SamHPurp** [comment]
Can we get a screenshot of a full row of these in a hallway please?

**Comment by Birdtalon** [comment]
28436898-8effb980-6d90-11e7-82b8-06f3e6b8a06b28436898-8effb980-6d90-11e7-82b8-06f3e6b8a06b28436898-8effb980-6d90-11e7-82b8-06f3e6b8a06b28436898-8effb980-6d90-11e7-82b8-06f3e6b8a06b28436898-8effb980-6d90-11e7-82b8-06f3e6b8a06b

**Comment by Citinited** [comment]
They remind me of the warp tiles from generation 1...

**Comment by GunDOSMk1** [comment]
> Can we get a screenshot of a full row of these in a hallway please?

Done!

**Comment by Very-Soft** [comment]
@Citinited I actually wanted to make it look like a boost pad, I wasn't sure if one could easily change the direction of a floor tile, and that would probably require coding to achieve anyway. So I made the arrows go in all 4 of the available directions and then decorated it some.

A diamond wasn't the necessarily the intention, but that's sorta what happens when you make a 4 way boost pad.

**Comment by taukausanake** [comment]
I always wondered why bluespace wasn't always, you know, **blue**. These looks nice and I approve. That begs the question though, what about all the other "cueball" styled bluespace icons?

**Comment by Very-Soft** [comment]
@taukausanake What do you mean, "cueball" styled bluespace icons?

**Comment by taukausanake** [comment]
The main example of the bluespace animation that I use for reference is a mob head icon called "cueball" that is basically the bluespace lightning thing around the whole human mob body. It is not used anywhere in the code as far as I know. It has existed before most of the other animated bluespace icons as far as I am aware, along with the bluespace slime which also wasn't in use for quite a while back then

**Comment by Very-Soft** [comment]
@taukausanake Well, if you know of any other ones specifically that you think might be done better, please do feel free to contact me on discord with them, and I can poke at trying to make them better. I'm afraid as is, I'm not sure what sprites your're talking about, how they look, or why they might need improving.

**Comment by Ar3nn** [comment]
The old sprite, while annoying to look at, was also pretty fun-looking at first, and I think this makes it a bit less fun. Any way you could animate it still? Maybe have the edges pulse darker blue (and brighten up the center diamond for contrast) or vice versa? That'd get my full support, I know how irritating those must look to people at times, despite how seldom they end up used.

**Comment by Jountax** [comment]
I believe the cueball helmet is a reference to Doc Scratch from homestuck, if that's one of the things Tau is talking about.

**Comment by taukausanake** [comment]
If [this](https://i.ytimg.com/vi/7KaaiTQjKeg/maxresdefault.jpg) is any kind of proof then I think you may be correct @Jountax

**Comment by KingPhilipIII** [comment]
@Jountax @taukausanake 

Can confirm. The cueball helmet is a reference to Doc Scratch, matched with a white suit.

**Comment by Very-Soft** [comment]
@Ar3nn The sprite is animated though, it defaults to a darker blue, and pulses a blue-green from the inner blues to the outer edges

**Comment by Fox-McCloud** [comment]
These are a bit rough/fuzzy compared to the sprites around them.

The base level design looks good, but the style/sharpness of the sprites leaves a bit to be desired, IMO.

**Comment by Fox-McCloud** [comment]
The original spriter of this posted some updates to it; may want to talk with them, again.

**Comment by SamHPurp** [comment]
Gave this critique directly, but worth noting here for transparencies sake: To me they look like something on the floor, and potentially impassable.

I'm not a fan, and don't think the style is right.

**Comment by Spacemanspark** [comment]
These honestly look a lot better.

**Comment by tigercat2000** [comment]
PR is stale, hasn't been updated since July 20th. As Fox detailed, the sprites could be better, and the original artist may have further developed them. Feel free to resubmit this PR with new sprites.

**Pull request closed without merging**
