### PR TITLE
Change max character slots to 20

### PR DESCRIPTION
**Pull request by tigercat2000**
Refer to title.
@Necaladun

:cl:
rscadd: You can now have up to 20 characters.
/:cl:

### CODE REVIEW

**Comment by NTSAM** [comment]
sexy :+1:

**Comment by ProperPants** [comment]
I don't even use two character slots. Is there something wrong with me?
:tada:

**Comment by Spacemanspark** [comment]
...
Do you know how many times I've had to erase a character slot for a new character?
oh God.
Tiger you're amazing.
:+1:

**Comment by tigercat2000** [comment]
100% not influenced in any way of needing more larkens.

**Comment by KasparoVy** [comment]
I've got a goddamn excel spreadsheet full of characters

kek

This'll be very useful, thank you!

**Comment by Dumbdumn5** [comment]
Why the hell not?

**Comment by Necaladun** [comment]
<3 ty Tiger

**Pull request merged**
