### PR TITLE
Removes the HOP's second locker from Cyberiad and Kerberos

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do
Alternate to #19316. Removes the HOP's second locker, which right now only stores their garment bag.

## Why It's Good For The Game
The second locker used to be used for clothes, now it only has a garment bag in them. You could be using it to store random items, but now that we have the ID/PDA compartmentalizer for HOP, there is no real reason to give the HOP an empty locker anymore.

## Images of changes

image
image

## Testing

Compiles, lockers are gone on both maps

## Changelog
:cl:
del: HOP's second locker has been removed, its contents moved to the main locker.
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
im personally against, because i like having a second locker as the HoP, which I can use to store various lost and found items, like PDAs that are turned over to me.

**Review by S34NW — APPROVED** [review]
Map edits are fine here.

Opinion wise, this option is preferable as it declutters the room and opens up some more space for mapping things.

**Comment by procdrone** [comment]
I just went ahead and made this the only alternative, it was going to win anyway, lets goooo

**Review by SteelSlayer — CHANGES_REQUESTED** [review]
Can you restore the light and lightswitch for Delta's HOP office? Otherwise good to go.

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
