### PR TITLE
Fix for broken wall graphic (when walls dont properly merge on server load)

### PR DESCRIPTION
**Pull request by Jey123456**
small fix for the bug that randomly cause wall to not have the proper tile on map load (walls not merging their graphic with neighboring walls)

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
You should be updating your branch *before* pushing your changes--we don't want or need unneeded merge/updates in a newly minted PR.

If conflicts arise, that's fine and usually unavoidable, but a completely new PR? No-go.

**Comment by Jey123456** [comment]
uh, no conflicts are detected that i can see.

**Comment by Fox-McCloud** [comment]
I didn't say there were, I'm saying that you have a merge/update commit in your PR because you updated and made your own commits all in the same go--this shouldn't be done; you should update your fork/branch first---THEN make changes to it so that the amount of commits you make isn't bloated up for no reason at all.

Merge/update commits are fine *if* conflicts do arise, but otherwise, a completely newly submitted PR should never have an update/merge commit in it.

**Comment by Jey123456** [comment]
I did check the logs to be sure before doing the PR, the only file modified in that PR was last modified on the master on jan 3, my last merge was from yesterday so it was still perfectly fine for it. No point in spamming my logs with merge for no reasons when my last one was still fresh

**Comment by Jey123456** [comment]
I think i see what you mean, altho im unsure how to not have that merge in the commit. I did not do it on this branch but on the parent from which i branched to (so that it would be updated to the latest master code).

**Comment by Fox-McCloud** [comment]
https://github.com/Jey123456/Paradise/commit/62bf69d7342521305a82d1a0573baeb116053cc0 this commit shouldn't be in your PR. I'm not sure how else I can phrase this or make it more clear---though maybe you're manually updating your own fork with the webclient (which would cause this).

If that's the case, then you need to be following something like this (if you're using Github for windows), to update your branch to avoid needless commits: https://help.github.com/articles/configuring-a-remote-for-a-fork/ and https://help.github.com/articles/syncing-a-fork/

**Comment by Jey123456** [comment]
i did use the webclient for that merge yes. Ill see about using the commandline approach next time.

**Comment by Fox-McCloud** [comment]
A problem with this; if an air datum is ever null, then it will fail silently with this---andddd that would be a very bad thing; we'd absolutely want to know if air is ever null.

Also, I'm really not sure how this would resolve the issue with overlays.

**Comment by Jey123456** [comment]
if you check your server logs, youll see that on most loads during the initialisation you get an error with null air exactly there. As for the impact if for whatever reason it happen during gameplay, its also very minimal since thats only the icon of the tile. So worst case scenario, no overlay from the air will appear on the specific turf with no air. There is no other impact from that, its not a critical part of the code either. If another part is critical and require air to not be null, it will error there.

**Comment by Tastyfish** [comment]
@Fox-McCloud air is always null for walls.

**Comment by Fox-McCloud** [comment]
>if you check your server logs, youll see that on most loads during the initialisation you get an error with null air exactly there.

I have literally never gotten this error, ever.

**Comment by Jey123456** [comment]
Check the server log next time you see a glitched tile. I'm willing to bet it will be here just after the initial load.

**Comment by Jey123456** [comment]
it happen on live and it happen on my test machine (which is pretty close on spec and hardware to live), if it doesnt happen for you, maybe its caused by a timing issue that fast machine are more likely to experience.

**Comment by Tastyfish** [comment]
I've been getting a pile of runtime errors in that proc more than half the time I run a test server, it's definitely a thing.

**Comment by Fox-McCloud** [comment]
I'm going to guess that this is happening only with things on the 8th z-level and only happening with walls?

**Comment by Jey123456** [comment]
It happen on the station z level, i believe its 1 ? but i suppose it could also be 8

**Comment by Fox-McCloud** [comment]
I suspect this is a larger problem. We had issue with null air in walls before, results in in null.react() runtimes---this was caused by the initialization of LINDA and away missions.

Recently, as many of you have probably noticed, the boot time for Paradise has been *dramatically* increased---I strongly suspect that this new hang is causing problems with initializations somewhere and delaying things more than they should, thus generating this issue.

I'm not sure what's causing the issue though.

**Comment by Jey123456** [comment]
i would not be surprised. But in either case, this fix is harmless and fix the issue players can see.

**Comment by Fox-McCloud** [comment]
Going to guess this isn't a problem anymore, considering that initialization is happening in a more timely manner now. Should this prove problematic, in the future, this may be able to be re-opened, but, as discussed with @Tigercat---we generally want to know when this goes berserk, as that means something bad wrong is happening with LINDA.

**Pull request closed without merging**
