### PR TITLE
Pepperspray now applies knockdown instead of stun

### PR DESCRIPTION
**Pull request by FloFluoro**
## What Does This PR Do
A very late advancement of #18179

This PR changes the "weaken" instastun on pepperspray to a knockdown. All other status effects that pepper spray inflicts (confusion, blindness, eyeblur, disarm) are unchanged.

## Why It's Good For The Game
Paracode has almost entirely migrated away from instastun combat, and pepperspray is one of the last holdouts. It's still a very effective tool for neutralizing someone (12 seconds of confusion, 10 seconds of knockdown, 4 seconds of blindness, 10 seconds of eyeblur, and a forced disarm). You will be able to appreciate these other debuffs more now that you aren't paralyzed for 90% of the pepperspray's duration.

## Testing
Compiled and tested on local debug server. My eyes are burning but my body keeps squirming

## Changelog
:cl:
tweak: Pepperspray now knocks down its victim, instead of stunning them.
/:cl:

### CODE REVIEW

**Comment by hal9000PR** [comment]
I am putting my objection down on this one for a couple of reasons.

Pepperspray is incredibly easy to counter for anyone but perma prisoners. the reason why this is good is it makes securities life much easier on high pop when they have to deal with multiple perma prisoners. nerfing that ability just makes security shitter to play during the time periods when security is the shittest to play. 

the `Stun()` and `Weaken()` procs arent forbidden from use, but they should be heavily gated

**Comment by FloFluoro** [comment]
> Pepperspray is incredibly easy to counter for anyone but perma prisoners

It's easy to counter _if you preempt its use and put on protection_ (or just happen to be wearing sunglasses), but otherwise it's a 10 second stun that immediately ends whatever confrontation might have happened. Pepperspray's use is also not restricted to sec, and it can be used opportunistically by antags for effortless abductions against people with no eyewear. You can say "that's useless against people wearing masks/sunglasses", but I think it's a little unhealthy to have a mechanic which encourages people to preemptively rush certain cosmetics at round start "just in case".

Against perma inmates, pepperspray would still be an instant 10 second knockdown + disarm + blind + confusion with no cooldown, is this really not adequate for crowd control? Is a ten second stun which shuts down any potential for counterplay really the only thing that will do for inmate management?

**Comment by Edan52** [comment]
> it can be used opportunistically by antags for effortless abductions against people with no eyewear

I think this is a fairly good point, however while not exclusive to security, it's not an extremely easy chemical to acquire and weaponize, so you would either have to go through the process of acquiring it yourself or by getting it from an officer. Security on highpop has to deal with a lot of rowdy prisoners and this is actually one of the few uses this chemical has as security, I just can't see it being used much by them after this and it was already rarely used. If you really don't want to get kidnapped by an antag with this which is a very rare occurrence which I have almost never seen (though that's not a good argument for not nerfing something) then you are able to spawn with equipment to eliminate that possibility, I think the benefit security gets by having this in its current state outweighs what this PR achieves.

**Comment by Peakwastaken** [comment]
besides what Edan and Charlie said, perma prisonners can also craft tattered blindfolds to fully protect themselves from it with no downsides, so it's really not an issue imo.

**Comment by hal9000PR** [comment]
3 balance objections with reasons stated, filing as closed.

**Pull request closed without merging**
