### PR TITLE
Removes Hitblips

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fairly simple.

- Removes hit-blips

Now that we have attack animations, these really aren't necessary anymore--likewise, they're a bit overly cartoonish and distract from the appearance of the mob that's being attacked (ie: obscuring damage overlays or other body parts temporary). 

Hit Twitching replaces the blips:

chop

### CODE REVIEW

**Comment by ZomgPonies** [comment]
I'm wondering if the damage overlays will be enough to visually indicate who is the victim during hectic combat.

**Comment by tigercat2000** [comment]
I'm not entirely convinced about this. Those attack animations aren't always 100% clear, as well as considering that the main way to see when someone gets hit by a bullet when the attacker is out of sight, is noticing the sudden random hit-blip.

**Comment by veganzombeh** [comment]
I'm not quite sure about this either. The hitblips help to indicate who is actually being attacked in combat with multiple people. Hit twitching would definitely do that too though.

**Comment by Fox-McCloud** [comment]
Hitsounds, attack animations, and--most importantly, the in-game text all definitively confer who is being attacked with a great amount of clarity. The hitblips themselves distract from the model (and the damage overlays which show up from getting hit) while adding an overly cartoonish/comic-book style element to getting hit. While silly and SS13 go hand in hand, it's not typically *that* kind of silly.

Hitblips already don't exist for anything that doesn't deal brute damage--Tox, Burn, and Oxy all do not not incur the overlay---and none of these are problematic from a 'lack of feedback'.

**Comment by CrAzYPiLoT-SS13** [comment]
I agree with fox this time. I support this.

**Comment by Spacemanspark** [comment]
I really liked the hitblips, it gave combat a more 'comical' feel, as well as showed who was being attacked at a small glance, without deciphering the chat.
I still find it useful.

**Comment by CrAzYPiLoT-SS13** [comment]
Deciphering? I don't know if you are really some kind of spaceman, but it really doesn't take more than a look to know who was attacking who. Moreover, the 'comical' fell is not really suitable for SS13.

**Comment by Spacemanspark** [comment]
Between chat, emoting, gunfire, and attacking, it can be difficult at times.
And yes, the comical feel does fit in with SS13. The game is meant to have humor like that.

**Comment by CrAzYPiLoT-SS13** [comment]
I disagree, but whatever rocks your boat. By the way, could you give me another example of this 'comical feel' in SS13?

**Comment by veganzombeh** [comment]
I'd agree hitblips are a bit too comical, but I do think they are useful. Perhaps they could be toned down a bit to be less blatantly cartoonish, rather than removed completely?

**Comment by CrAzYPiLoT-SS13** [comment]
That could be a good idea, if they were made so that they aren't too big and they are serious. After all, you are hitting a person. Imagine hitting someone and someone gets a sticker, puts it on the victim, you read it and it says 'bang'. Really?

**Comment by adrkiller59** [comment]
Personally I like the hitblips and they never bothered me, but I guess a hit-twitch will get the job done too.
And about the comical style in SS13, I will say one word, just one: honk.

**Comment by Iamgoofball** [comment]
I prefer the hit blips, personally.

**Comment by CrAzYPiLoT-SS13** [comment]
Not that kind of comical. Comic sans is k.

**Comment by Spacemanspark** [comment]
Even before the comic sans.

**Comment by CrAzYPiLoT-SS13** [comment]
Could you explain that last message. I don't get it.

**Comment by Spacemanspark** [comment]
Even before Comic Sans was a thing here, SS13 was very comical, especially with the clown.

**Comment by Fox-McCloud** [comment]
@Spacemanspark 

Not that kind of comical; you could make a very strong argument that hitblips appear if the *clown* gets punched or punches someone, but for regular crew it's a bit 'out there' so to speak.

**Comment by fj45** [comment]
They look awful but have a place in making who is getting hit obvious. I would much prefer they are replaced with something else then just ditching them.

**Comment by Fox-McCloud** [comment]
@fj45 

That can be looked into in the future, but that's beyond the scope of this particular PR.

**Comment by tigercat2000** [comment]
I'm not sure it is beyond the scope of this PR. Systems shouldn't be removed with absolutely nothing to replace them if players don't want them gone.

**Comment by CrAzYPiLoT-SS13** [comment]
I agree with the idea that maybe clowns should use the current hitblips.

**Comment by ZomgPonies** [comment]
Yeah I'm definitaly concerned that removing them without finding an alternative will lower the quality of combat.

**Comment by Fox-McCloud** [comment]
Added in basic twitching.

This isn't how I *want* it to work, but it accomplishes the same purpose--pinning get_dir() to your attacker (or the atmo that hi you)---ehhh.

**Comment by tigercat2000** [comment]
Correct me if I am wrong, but won't a 9-pixel range look similar to caffeine shaking?

**Comment by ZomgPonies** [comment]
Close enough for now. We can adjust as needed.

**Comment by fj45** [comment]
Sorry to say, but on a chaotic shuttle without hitblips, it is impossible to tell who is hitting who. A combination of the three would be best.

**Pull request merged**
