### PR TITLE
Directional Locking

### PR DESCRIPTION
**Pull request by tigercat2000**
This adds the ability to lock your mob towards facing either a certain
direction or a certain atom. Direction is done by shift-middleclick,
atom is done by shift-ctrl-middleclick.

https://s3.us-west-1.amazonaws.com/katherine.sharex/2018/04/2018-04-19_18-58-49.webm

Works on literally every mob. I might make it so that it only works for living mobs, but eh.
:cl:
rscadd: You can now lock a facing direction with shift+middle mouse button, or lock your direction towards an object by clicking on it with shift + ctrl + middle mouse button.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
FUCK yes holy shit this feature is great. Thank you

**Comment by DarkPyrolord** [comment]
I can see the the smooth criminals already.

**Comment by matt81093** [comment]
This feature.. sounds amazing. Enough said.

**Comment by Regen1** [comment]
Can we add 180 degree vision now as well? So people have a reason to direct their character, and for this to have a combat mechanic

**Comment by Chronarch2954** [comment]
Oh my this is good!

**Comment by KasparoVy** [comment]
Fov modifier on species would be a cool ass balancing mechanic, but I din't foresee management wanting us to go that direction.

**Comment by Fox-McCloud** [comment]
Trying to think of a few specific cases where this could be abused, mechanically. If I can't think of any (or they're ultra situational), I'll give a thumbs up, for now, neutral. If this can be abused, mechanically, then I'm definitely sour on it.

**Comment by KasparoVy** [comment]
The only situations would be any directional shields.

**Comment by tigercat2000** [comment]
@Fox-McCloud I'd rather remove directional-based mechanics more than anything... they're usually unwieldy as hell, since you change directions so rapidly and easily.

**Comment by mattroks101** [comment]
I'm not advocating for vision cones to be added but @Fox-McCloud how long ago was that attempted? Because if you're talking about the one from last year then first off, vision cone code has come a long way in a year and second off to say it was "attempted" on TG is an over statement, more like "thought about and then before anyone did any work besides the base system, thrown out because they realized it was gonna be work to implement". Very little disaster happens when you quit long before you start which is what TG did.

**Comment by granodd** [comment]
The only thing that this would affect balance wise is shields while retreating, though I would say the interaction with this PR and that is really finicky, as it has some pros and cons. The pro is that you can keep yourself facing towards your rear while you retreat 100% of the time. The con is that, should the threat you're blocking against somehow flank you, you'd have to quickly cancel your direction lock and adjust your facing, as otherwise you're still looking where they used to be, and they're now behind you.

In a loose translation: people who were already spamming click to retreat with shields will likely be the same people who are able to successfully use the direction lock to do the same thing while also not getting shafted by a flank.

**Comment by tigercat2000** [comment]
@granodd Shields have no directional component.

check_shields calls hit_react on every possible shield type
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/human_defense.dm#L138-L157

/obj/item/shield/hit_reaction doesn't care about the user's direction
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/shields.dm#L6-L11

There's no parent proc that cares about the user's direction
https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items.dm#L314-L318

**Comment by KasparoVy** [comment]
Great, so I guess it doesn't matter. Go go go!

**Comment by granodd** [comment]
@tigercat2000 that's really strange, I could have sworn that riot shields cared which direction you were facing, or that at least alien jumps did.

**Comment by matt81093** [comment]
Odd.....

**Comment by bigfatbananacyclops** [comment]
When facing at someone without ID on a a mask on, would it show like ''You're now facing at Unknown''
Or their actual name, like ''You're now facing at Jimmy Pepperson''?

**Comment by KasparoVy** [comment]
Reeeeally looking forward to it.

**Comment by KasparoVy** [comment]
Yeeeeesssssss

**Comment by Fox-McCloud** [comment]
Moonwalking used to mean something.

Now every single n00b scrublord can do it.

😭

**Pull request merged**
