### PR TITLE
Quartermaster Can Make Announcements

### PR DESCRIPTION
**Pull request by 13spacemen**
## What Does This PR Do
QM can now make announcements from the request console in his office

## Why It's Good For The Game
QM spends the entire round managing Cargo and Mining, he should at least be able to make announcements from his office.
The QM Office is basically never visited after roundstart, this gives it some purpose
This PR does not make QM a head, just lets him do announcements from his office

## Images of changes
qm

## Changelog
:cl:
tweak: The Quartermaster can now make announcements from the request console in his office.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Yeah no.

QM really doesn't need this. They aren't a real head, and have no real use for this.

**Comment by 13spacemen** [comment]
How does it have no use? QM can make an announcement for people to send crates and plasma, come for guns during War Ops/Blob, anything. Cargo is the backbone of the station
I'm not arguing that he should be the head but QM has always been this pseudo-head who rules Cargo and takes care of his miners.
Also you hardly see a round where every single head uses the Announcement System. It's not really spammy or abuseable.

**Comment by procdrone** [comment]
what AA means, is that cargo already has a real head that already can do these announcements from his office. the head of personell

**Comment by 13spacemen** [comment]
Why does the QM have a supply door remote in his locker then?
In fact why does the QM even have an office? Why does he even exist? Isn't he just a Cargo Tech with access to Mining? Can't the HoP do that? HoP doesn't have much else to do after roundstart anyway

I really think this is a harmless change. Yes HoP is the head of Supply but QM is the pseudo-head and it's been like that for years

**Comment by procdrone** [comment]
> Why does the QM have a supply door remote in his locker then? In fact why does the QM even have an office? Why does he even exist? Isn't he just a Cargo Tech with access to Mining? Can't the HoP do that? HoP doesn't have much else to do after roundstart anyway
> 
> I really think this is a harmless change. Yes HoP is the head of Supply but QM is the pseudo-head and it's been like that for years

Its similar to warden in security. he also has their own office, and semi "control" of brig but aren't a head.

**Comment by AffectedArc07** [comment]
2 heads and a maintainer objecting, no one in favour.

Closing.

**Pull request closed without merging**
