### PR TITLE
Removes Z-level 8

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes the 8th z-level, the so called "traitor station".

This has been inaccessible for literally months now and there's nothing on it anymore that anyone would want that's not already in science or the research station. The removal of telesci is kinda the final nail in the coffin for it.

Performance wise, this reduces total instances from 720,000 to 650,000--a 10% reduction.

Related
 - Fixes improperly named define.

Discussion from here: https://github.com/ParadiseSS13/Paradise/pull/2142

re-uploaded because Github was being a butt about resolving merge conflicts on something that should have been super easy to resolve.

### CODE REVIEW

**Comment by Markolie** [comment]
Again, really, I strongly support this. The Syndicate Station is a pain in the ass to maintain, and we're really better off without it until takes proper time to completely re-map it. Because, again, currently it's powerless most of the time anyway. 

This change going through does *not* mean that we won't have a syndicate station in the future: if someone maps a really good one and adds a proper Syndicate way of travelling there (an uplink item, perhaps?) then that's certainly not off the table.

**Comment by Spacemanspark** [comment]
I'd rather something like that be done /now/ then put it off until later, when it will likely be forgotten for three months.

**Comment by Markolie** [comment]
No-one I know of has any intention of doing it... anytime soon, really. And I don't expect anyone to come up and volunteers to do it.

**Comment by Iamgoofball** [comment]
@Spacemanspark Thanks for volunteering! Get right on it.

**Comment by Fox-McCloud** [comment]
@TheDZD 

Your input, if you don't mind?

Also, my two cents, in addition to what was said in the original: It's something we have to maintain that's not used 99.9% of the time---and is only a personal playground for, at most, three people

I have no plans to fix it up myself, either---I don't think a "traitor haven" should have its own *entire* z-level dedicated to it.

**Comment by taukausanake** [comment]
Is it accessible from spacing yourself? Randomly going through z-levels? If not then I see no reason aside from lessening server load to removing it. I'd still like a training or maybe even an admin testing ground. I know I did a lot of stupid things when I was badmin/devmin on friend's server and took a bit of time var-editing anything I thought would be useful. It has to be made into something else. Otherwise I guess it can be removed from the server but the map file saved at least. Just don't get rid of it

**Comment by Fox-McCloud** [comment]
There is already an admin testing grounds.

**Comment by taukausanake** [comment]
@Fox-McCloud I was not aware. Alright, but I still request just keeping the map file around

**Comment by Plotron** [comment]
All I can say is: Yaaay.

**Comment by SamCroswell** [comment]
Also you can't reach it by spacing yourself right now, @taukausanake .

**Comment by TheDZD** [comment]
While I like the idea of a safe area for traitors, the current Z8 isn't really worth keeping unless somebody bothers to re-map it.

**Comment by Markolie** [comment]
The new space_levels.txt will need to be updated in this PR - z-level 8 needs to be removed from the list.

**Comment by Fox-McCloud** [comment]
@Markolie 

Done.

**Comment by Markolie** [comment]
As per our previous reasoning, we'll be moving forward with this pull request. Anyone is welcome to re-design the traitor station and open a pull request for that though.

**Pull request merged**
