### PR TITLE
Make some guns REAL auto

### PR DESCRIPTION
**Pull request by AyIong**
## What Does This PR Do
Makes IK-60 (RED ERT), Disabler SMG and L6-SAW full auto
Time to use new component
Rate of fire values were taken from TG

## Why It's Good For The Game
Full-Auto

## Images of changes
Record is laggy a little, potato PC
UPD. WT full-auto removed, but it still on video, ignore it

https://github.com/ParadiseSS13/Paradise/assets/69762909/58c327ce-dc99-464c-a488-a44817bcc650

## Testing
Above

## Changelog
:cl:
tweak: IK-60 (ERT), Disabler SMG and L6-SAW now real automatic guns (Have full-auto)
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
dunno about the autorifle but this is sick. can you also give this to the gas flamethrower and maybe the cycler shotgun?

**Comment by AyIong** [comment]
> dunno about the autorifle but this is sick. can you also give this to the gas flamethrower and maybe the cycler shotgun?

Not in this PR i think

**Comment by Stoniest** [comment]
I like these changes, the L6 Saw and SMG disabler should be full-auto, I do believe there are also other guns/weapons that are intended to be full-auto as well, but I think the IK and WT shouldn't be full-auto. I'd say either make their full-auto much slower or just don't make them full-auto, I think going the "just not full-auto" route will be for the best for these weapons.

**Comment by Coolrune206** [comment]
May be worth adding it to the IK-30 Laser Rifle to keep it in line with the WT. Also lowering fire rate for WT to reflect current pew pew.

**Comment by Fordoxia** [comment]
> dunno about the autorifle but this is sick. can you also give this to the gas flamethrower and maybe the cycler shotgun?

Not the cycler. It's a KSG-12. It's an actual pump action shotgun with 2 mag tubes. It cannot fire in full-auto.

**Comment by Fordoxia** [comment]
Question: Will you be able to swap these weapons into burst/semi-auto mode as well?

**Comment by AyIong** [comment]
> Question: Will you be able to swap these weapons into burst/semi-auto mode as well?

No

**Comment by 1080pCat** [comment]
> IK-60

the ERT version? or the one crew can get?

**Comment by AyIong** [comment]
> IK-60

ERT

**Comment by Fordoxia** [comment]
> > Question: Will you be able to swap these weapons into burst/semi-auto mode as well?
> 
> No, only manually clicking (tapping)

I don't really like that. I would like to be able to choose to use alt fire modes.

**Comment by TORE01** [comment]
> > > Question: Will you be able to swap these weapons into burst/semi-auto mode as well?
> > 
> > 
> > No, only manually clicking (tapping)
> 
> I don't really like that. I would like to be able to choose to use alt fire modes. Especially on the SAW.

This can be tweaked later seeing as some firearms (mainly the Thompson SMG) already has a firemode swap.
Rome wasn't built in one PR.

I love this full auto in stations PR even if it might get rough for loud antags. There are more guns that can be full auto such as the NF10 and the C20R. As a gun nut I am looking forward to the test merge (if it is approved).

**Comment by GreatGatherer** [comment]
> dunno about the autorifle but this is sick. can you also give this to the gas flamethrower and maybe the cycler shotgun?

Gas flamethrower has the issue of not actually having a firerate. If you can click fast enough (or if you're dumb and use an autoclicker), you can dump the entire tank in fractions of a second, effectively turning it into a portable plasma fire if you use a plasma tank.

**Comment by GDNgit** [comment]
> > dunno about the autorifle but this is sick. can you also give this to the gas flamethrower and maybe the cycler shotgun?
> 
> Gas flamethrower has the issue of not actually having a firerate. If you can click fast enough (or if you're dumb and use an autoclicker), you can dump the entire tank in fractions of a second, effectively turning it into a portable plasma fire if you use a plasma tank.

yeah that's a good reason for it to have it so you don't need to jackhammer your mouse

**Review by Burzah — APPROVED** [review]

**Pull request merged**
