### PR TITLE
Lavaland has had rivers this whole fucking time.

### PR DESCRIPTION
**Pull request by warriorstar-orion**
## What Does This PR Do
Pass a z-level to /proc/spawn_rivers.

Probably a copy-and-paste mistake from the line above, /proc/spawn_rivers
was being passed a list instead of an integer, causing there to never be
any acceptable locations stored in `possible_locs`.

## Why It's Good For The Game
Lavaland will now have considerably more lava. It works fine with ruins and the other tunnels generated in rock.

## Images of changes
Paradise Station 13-07_33_27
Paradise Station 13-07_34_55

## Changelog
:cl:
fix: Lavaland mapgen now has a higher chance to spawn rivers.
/:cl:

### CODE REVIEW

**Review by AffectedArc07 — APPROVED** [review]
How has this slipped us for 2 years?

**Comment by FlattestGuitar** [comment]
lol

Do you *want* more rivers though?

**Comment by hal9000PR** [comment]
I very much do want a higher lava to land ratio on my lavaland.

**Comment by AffectedArc07** [comment]
I cite this a fix

**Comment by FlattestGuitar** [comment]
tyrant

**Pull request merged**
