### PR TITLE
Nuke kills everybody (On the station Z-level).

### PR DESCRIPTION
**Pull request by KasparoVy**
Even IPCs.
Tested by arming and blowing the nuke as an IPC.

:cl:
tweak: No-one escapes nuclear hellfire.
rscadd: Secure fridges/freezers are now lead-lined and have thus become nuke resistant.
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
Badmin cluster emp when?

**Comment by sothangel** [comment]
Can you make it so that hiding in the freezer-closet the chef has makes you survive, for that sweet Indiana Jones reference?

**Comment by KasparoVy** [comment]
If it won't get this instantly closed for memes, I don't see why not

**Comment by Anasari** [comment]
Clearing up more space for useful organics.

I support.

**Comment by FlattestGuitar** [comment]
Nothing like the smell of nuclear holocaust in the morning.

**Comment by Fox-McCloud** [comment]
I'd test this with 60-120 mobs.

`dust` is considerably more expensive than `death`

**Comment by Taaketa** [comment]
But how will I claim my IPC superiority after the Nuke goes off?!?

**Comment by KasparoVy** [comment]
@Fox-McCloud Sure thing, I'll test it when I get home

**Comment by KasparoVy** [comment]
With my machine specs being i7-3930k @ OCed to 4.7 GHz under max load & 8GB 1600MHz G.SKILL RipjawX 7 CAS latency RAM, EVGA GTX 980 ACX 2.0 and 120 `/mob/living/carbon/human/human` mobs spawned, it took between 3-5 seconds for the mass dusting to be done.

**Comment by tigercat2000** [comment]
@KasparoVy you should probably add the fridge thing to the OP
also, try adding a `CHECK_TICK` right after dust(), see if that reduces the lag without any major problems

**Comment by KasparoVy** [comment]
@tigercat2000 Thanks for the tip, had no idea CHECK_TICK was a thing. Testing that now.
Fridge thing added to OP.

**Comment by tigercat2000** [comment]
@KasparoVy Ah, that'd be because getting dusted makes you into a ghost, and mob/Login() resets client.screen in order to reset the HUD. There are a few things you could do, easiest would probably be just adding a second loop after the dust() loop, to show the animation to everyone in the world. Or, perhaps change it to something like
```dm
for(var/mob/M in mob_list)
	M.buckled = temp_buckle
	if(M.stat != DEAD)
		var/turf/T = get_turf(M)
		if(T && is_station_level(T.z) && !istype(M.loc, /obj/structure/closet/secure_closet/freezer))
			var/mob/ghost = M.ghostize()
			M.dust()
			ghost.screen += cinematic
	M.screen += cinematic

**Comment by KasparoVy** [comment]
@tigercat2000 Thanks a bunch for clearing that up, I'll sort it tonight. Much appreciated :+1:

**Comment by KasparoVy** [comment]
Alright, got the CHECK_TICK and cinematic changes in and all seems well! People who get dusted get an uninterrupted cinematic same as people who live.

**Comment by Fox-McCloud** [comment]
Memes

**Pull request merged**
