### PR TITLE
Converts Mob Colours to Hexadecimal

### PR DESCRIPTION
**Pull request by KasparoVy**
Been holding onto this for a couple months. I recall someone suggesting this on one of my PRs ages ago and I figured I should follow up on it eventually.

Anyway, there are no noticeable front-end changes. This just means that mob colours now take up less database columns, require less processing, less code and are handled more simply.
No changelog because it's all backend.

_In-Game Preview: Showcases Mob, Character Creation and ID Preview colours working properly._
hexcolourpreview

_In-Game Testing of CMA: Mob colours can still be changed exactly as before, nothing breaks._
cmahexcolourpreview

_Cloning myself after spawning in and using CMA to change all of my colours. All DNA stuff works._
hexcolourcloningpreview

## Required SQL Query
This query adds all the required columns, populates them by converting all mob colours to hexadecimal, updates the new columns with said values and finally deletes the old columns.

```
#Adding new columns to contain the hex values (will be converted from RGB).
ALTER TABLE `characters`
	ADD `hair_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `language`,
	ADD `secondary_hair_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `hair_blue`,
	ADD `facial_hair_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `secondary_hair_blue`,
	ADD `secondary_facial_hair_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `facial_blue`,
	ADD `skin_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `skin_tone`,
	ADD `head_accessory_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `marking_colours`,
	ADD `eye_colour` varchar(7) NOT NULL DEFAULT '#000000' AFTER `alt_head_name`;

#Converting RGB colours to HEX colours and transferring them to the new columns.
UPDATE `characters`
	SET `hair_colour` = CONCAT("#", LPAD(HEX(`hair_red`), 2,'0'), LPAD(HEX(`hair_green`), 2,'0'), LPAD(HEX(`hair_blue`), 2,'0')),
	`secondary_hair_colour` = CONCAT("#", LPAD(HEX(`secondary_hair_red`), 2,'0'), LPAD(HEX(`secondary_hair_green`), 2,'0'), LPAD(HEX(`secondary_hair_blue`), 2,'0')),
	`facial_hair_colour` = CONCAT("#", LPAD(HEX(`facial_red`), 2,'0'), LPAD(HEX(`facial_green`), 2,'0'), LPAD(HEX(`facial_blue`), 2,'0')),
	`secondary_facial_hair_colour` = CONCAT("#", LPAD(HEX(`secondary_facial_red`), 2,'0'), LPAD(HEX(`secondary_facial_green`), 2,'0'), LPAD(HEX(`secondary_facial_blue`), 2,'0')),
	`skin_colour` = CONCAT("#", LPAD(HEX(`skin_red`), 2,'0'), LPAD(HEX(`skin_green`), 2,'0'), LPAD(HEX(`skin_blue`), 2,'0')),
	`head_accessory_colour` = CONCAT("#", LPAD(HEX(`head_accessory_red`), 2,'0'), LPAD(HEX(`head_accessory_green`), 2,'0'), LPAD(HEX(`head_accessory_blue`), 2,'0')),
	`eye_colour` = CONCAT("#", LPAD(HEX(`eyes_red`), 2,'0'), LPAD(HEX(`eyes_green`), 2,'0'), LPAD(HEX(`eyes_blue`), 2,'0'));

#Dropping the old columns now that the hex colour columns are in place.
ALTER TABLE `characters`
	DROP `hair_red`, DROP `hair_green`, DROP `hair_blue`,
	DROP `secondary_hair_red`, DROP `secondary_hair_green`, DROP `secondary_hair_blue`,
	DROP `facial_red`, DROP `facial_green`, DROP `facial_blue`,
	DROP `secondary_facial_red`, DROP `secondary_facial_green`, DROP `secondary_facial_blue`,
	DROP `skin_red`, DROP `skin_green`, DROP `skin_blue`,
	DROP `head_accessory_red`, DROP `head_accessory_green`, DROP `head_accessory_blue`,
	DROP `eyes_red`, DROP `eyes_green`, DROP `eyes_blue`;
```

The above worked fine on my local DB with existing characters.
**_I tested this query 2017-05-20 on an up-to-date database and it worked (as in: added columns where they should be, converted colours, updated new columns, dropped old columns properly and functioned with the game)._**

### _**I highly recommend the above SQL query be tested before use by creating a DB from the current live schema, creating some test characters then using said query in order to be 100% certain.**_

### CODE REVIEW

**Comment by KasparoVy** [comment]
666 deleted lines totally coincidental.

**Comment by Dumbdumn5** [comment]
Dear GOD you DID IT!
HOLY SHIT! TAKE MY MONEY! :a: +

**Comment by granodd** [comment]
So what does this mean in a nutshell? You can change your skin tone in game? Does this change anything out of game in the character customization?

**Comment by KasparoVy** [comment]
I'm just going to go ahead and quote the PR description: "Anyway, there are no noticeable front-end changes."

Players won't notice anything. This is backend

**Comment by taukausanake** [comment]
360 additions/edits and 666 deletions. No way it's not intentional

**Comment by KasparoVy** [comment]
I've gotten really lucky with my PRs lately lmfao. This one, and then the last one was net 100 edits :thinking:. I'm tempted to make an issue report for this glitch in the matrix

**Comment by Crazylemon64** [comment]
This is kinda overdue, but as the maintainer responsible for updating the database and making sure stuff doesn't break,
ow

**Comment by KasparoVy** [comment]
Yeah I'm sorry about this one. I wrote a little blurb about testing it at the bottom-- one I repeated just after putting the PR up to make absolutely sure myself. Queries like that on databases like ours make my palms sweaty :rofl:

**Comment by Allfd** [comment]
✔️ SQL conversion testing passed on a copy of the production DB, ready for whenever this is merged.

**Comment by taukausanake** [comment]
Before this gets done I just want to say @KasparoVy that swampy Vulp you have in the bottom two images is lovely ❤️

**Comment by KasparoVy** [comment]
I had to destroy the perfect diff because of conflicts.

Needless to say, conflicts resolved...

**Comment by KasparoVy** [comment]
Conflict resolution again.

**Comment by tigercat2000** [comment]
With the merge of #7755 you will need to update this branch to the latest version of the repo and follow the directions set out within it.

**Comment by KasparoVy** [comment]
@tigercat2000 So in the .sql file I'd just paste my query in there and it'll be mint?

**Comment by tigercat2000** [comment]
@KasparoVy Correct: 
 - Change `#define SQL_VERSION 0` in `code\__defines\misc.dm` to `#define SQL_VERSION 1`
 - Change `DB_VERSION 0` in `config\example\dbconfig.txt` to `DB_VERSION 1`
 - Make a file in the `SQL/updates` directory named `0-1.sql`

**Comment by KasparoVy** [comment]
Much appreciated!

**Comment by KasparoVy** [comment]
@tigercat2000 Updated and tested, nothing seems to've been busted. Thanks for the instruction.

**Comment by KasparoVy** [comment]
*shrug*

**Comment by Allfd** [comment]
@KasparoVy 
@tigercat2000 is on vacation, he is back Saturday and hopefully this gets merged then.

**Comment by KasparoVy** [comment]
Thanks for the update!

**Comment by KasparoVy** [comment]
I know very well not to hold out :joy:.

**Comment by tigercat2000** [comment]
@KasparoVy Sorry, I've been busy since I got back, this is the first time I've had a chance to look at this again.

**Comment by KasparoVy** [comment]
All good. Welcome back and thank you!

**Pull request merged**
