### PR TITLE
Makes bible farting less predictable

### PR DESCRIPTION
**Pull request by Allfd**
Due to the controversy surrounding removing bible farting I would propose this alternative.

Who can say what will happen if you anger the gods?
 

🆑 Alffd
rscadd: Farting on a bible now puts you at the mercy of the gods.
rscdel: Removed automatic biblefarting gibbing.
/🆑

### CODE REVIEW

**Comment by Jovaniph** [comment]
THIS!!! I say this is one of the best solutions.

**Comment by FlattestGuitar** [comment]
I already sigh at butt faxes, adding something even less diversive won't really net the players a lot of admin interaction, I'm afraid.

On top of that, admin logs are for things that are expected to require administrator's reply, or at least acknowledgement. This stuff is...not that.

**Comment by Lady-Luck** [comment]
Remove it entirely.

**Comment by Allfd** [comment]
@FlattestGuitar removes the admin log
@Lady-Luck I agree it should be gone entirely, however the high level of controversy makes that unlikely.  This is a compromise that allows for admin desecration to prevent the most immersion breaking aspects of bible farting.

**Comment by Crazylemon64** [comment]
evil_grin

**Comment by Anoonki** [comment]
This is going to get used to spam the admins out of protest.
I just know it.

**Comment by Allfd** [comment]
@Anoonki They risk being a click away from gib,  the smite button at the end allows for a quick selection of a number of interesting deaths, gib is included.

**Comment by Anoonki** [comment]
I suppose.
The thing is that people will just spam it until they get what they want, and they'll probably get more than they do now.

**Comment by Necaladun** [comment]
Good compromise IMO. Brain death is a good quick, boring death, and allows gibbing of clowns doing it amazingly

**Comment by taukausanake** [comment]
Is one of the punishments admin brig? Maybe something a little more painful? Could be a type of prison hell where monsters keep attacking you but you heal up before dying. Only for it to repeat again.
Could get rid of a few shitters that way

**Comment by sothangel** [comment]
I still feel it should be made into a suicide effect - Use the suicide command and you gib like you've farted on it.

**Comment by taukausanake** [comment]
We could use more suicide acts. Give everything a suicide_act but make them all special

**Comment by Allfd** [comment]
image

These are the options the admins have if they choose to use a pre-defined smite,  I am a fan of more creative options but these are the premade ones.

**Comment by taukausanake** [comment]
What do the cookies do? And Cluwne seems more like a reward than a punishment, unless the cluwne also has everyone aggro it. In fact that might be a nice punishment too in itself, aggro everyone around until the victim is dead, if not also a little too dangerous

**Comment by Allfd** [comment]
@taukausanake 

The cookies either cause death through mutation or from catching fire, they are a bit dangerous to use as they could always be given to someone other then the person who got them summoned.

Cluwnes are always valid as I understand it.

**Comment by taukausanake** [comment]
> Cluwnes are always valid

Need a quote in the rules to back that up, or an admin stating so. Otherwise I might agree

**Comment by Allfd** [comment]
@taukausanake 

I will run it past the admins,  this is always what I have been told but it would be great to get some clarity.

**Comment by Fox-McCloud** [comment]
>Need a quote in the rules to back that up, or an admin stating so. Otherwise I might agree

This was established quite a while ago that Cluwnes are, in fact, always valid.

**Pull request merged**
