### PR TITLE
Clean Up In Sprites: Root Directory

### PR DESCRIPTION
**Pull request by TrashDoxx**
## What Does This PR Do
* I simply deleted the files that I did not find in the code.

## Why It's Good For The Game
* I think this junk is of no value and will never be used.

## Changelog
* No player-facing changes.

### CODE REVIEW

**Comment by TrashDoxx** [comment]
Any mistakes, comrades?

**Comment by TrashDoxx** [comment]
My little force-pushes, I love you.

**Comment by TrashDoxx** [comment]
It's not a pretty history of changes, but I don't think that's a problem.

**Comment by TrashDoxx** [comment]
It's not a pretty history of changes, but I don't think that's a problem.

**Comment by TrashDoxx** [comment]
My little force-pushes, I love you.

**Review by AffectedArc07 — APPROVED** [review]

**Pull request merged**
