### PR TITLE
Cargo Technician resprite + some hazard vests

### PR DESCRIPTION
**Pull request by Christasmurf**
## What Does This PR Do
Resprites the cargo technician jumpsuit, jumpskirt, delivery uniform, cargo bomber jacket, cargo softcap and cargo armband.
Adds cargo overalls and cargo beret.
Removes the delivery uniform softcap as it was covered by the addition of the cargo cap.
Part of a larger scheme to rebrand cargo and resprite all departmental clothing as a whole

Ports the hazard vest, cargo vest, QM vest and CE vest from this closed PR https://github.com/ParadiseSS13/Paradise/pull/22307
Ports the hazard vest item from eris, recoloured to fit the above https://github.com/discordia-space/CEV-Eris/pull/4971

Notes: The standard hazard vest is available through all public-access means. Intended for assistants/visitors to the station.
The cargo vest is now a "staff vest" and is consistent across all non-command employees (cargo technician, explorer, engineer, atmospherics, janitor)
The QM and CE vests are almost identical to the previous PR.
The price of the hazard vest in the engidrobe has been reduced from 75 credits to 50 credits (same as it is in every other vendor)

## Why It's Good For The Game
Better sprites, more clothing customisation for cargo technician (and other roles affected by the vests)

## Images of changes
Before:
image
image

After:
image
Includes a more up-to-date version of the cargo tech jumpsuit also:
image

Vests:
image
image
image
image

Cargodrobe (this is how it is in the editor; it is animated in game)
image

## Testing
Above images, spawned magic mirror and tested all species sprites.

## Changelog
:cl:
add: Adds cargo overalls, cargo beret for cargo techs
add: Adds staff, QM and CE hazard vests. Staff hazard vests are available for engi, atmos, janitor, cargo and explorer so far
del: Removes the delivery boy cap
imageadd: Resprited cargodrobe, cargo tech jumpsuit, jumpskirt, softcap, armband, bomber jacket, delivery boy uniform and standard hazard vest
/:cl:

### CODE REVIEW

**Comment by spacegeese** [comment]
vests are neat but the tech looks too brown, the yellowish vibe is iconic

**Comment by ATP-Engineer** [comment]
Ah man, you got rid of cargo shorts. Sellout.

**Comment by Christasmurf** [comment]
> Ah man, you got rid of cargo shorts. Sellout. Brown should be saved more for explorers, I agree that the yellow is good.

QM is brown, explorers will be brown, if this gets through cargo techs will be brown, and I have plans to make the miners brown too. Also I was debating keeping the shorts as an alt but idk I don't vibe with the shorts

**Comment by ATP-Engineer** [comment]
This cannot continue

**Comment by evilmattyg** [comment]
>QM is brown, explorers will be brown, if this gets through cargo techs will be brown, and I have plans to make the miners brown too. Also I was debating keeping the shorts as an alt but idk I don't vibe with the shorts

CT drip needs to stay yellow to have a visual distinction between the QM and CT (The old QM uniform was a darker shade of yellow to accommodate this) since it would line up with the CMO, CE, RD and HOS standing out from their department due to the different colour of their uniform, and removing the signature cargo shorts is not a good idea either, because you're removing recognisability of a CT. People associate jobs with uniforms, and these new sprites are visually too similar to other uniforms, or do not convey anything visually. The yellow of the CT uniform designated you as a cargo tech since it matches the colour of cargo. What does brown convey? It has no departmental colour that matches it, and the top left ones look like brown jumpsuits. 

Overall, new uniform variations are nice but the iconic yellow cargo shorts need to stay, and brown should be reserved for the QM.

**Comment by Christasmurf** [comment]
> > QM is brown, explorers will be brown, if this gets through cargo techs will be brown, and I have plans to make the miners brown too. Also I was debating keeping the shorts as an alt but idk I don't vibe with the shorts
> 
> CT drip needs to stay yellow to have a visual distinction between the QM and CT (The old QM uniform was a darker shade of yellow to accommodate this) since it would line up with the CMO, CE, RD and HOS standing out from their department due to the different colour of their uniform, and removing the signature cargo shorts is not a good idea either, because you're removing recognisability of a CT. People associate jobs with uniforms, and these new sprites are visually too similar to other uniforms, or do not convey anything visually. The yellow of the CT uniform designated you as a cargo tech since it matches the colour of cargo. What does brown convey? It has no departmental colour that matches it, and the top left ones look like brown jumpsuits.
> 
> Overall, new uniform variations are nice but the iconic yellow cargo shorts need to stay, and brown should be reserved for the QM.

The brown is going to be the departmental cargo colour, this is just one of four roles. I'm going through and doing ALL the uniforms, and colours will match between heads of staff and their underlings with the exception of service, as they don't have a unified outfit style.
Regarding yellow being for cargo techs - I'd argue that engineering, the department where every role has a majority of yellow on all their clothing, (as well as their HUD and IDs and lockers and vendors) would be the yellow department.

The employment HUD for cargo roles is brown, as are the ID cards and PDAs and lockers. 
Quartermaster is brown, black and gold.
Cargo technician is brown, black and grey.
Explorer is brown, black and blue.
Mining will be brown, black and purple.

Likewise, for example on later plans I have, research director and scientist will share purple and white, chief medical officer will share blues and whites with other medical staff, same with CE and the engineers. 
Also HoS is majority red or black, same as the rest of the security department.

Regarding the shorts - I have, so far, been using two main styles of uniform. 'Lower crew' and 'higher crew'.
Lower crew is a solid colour jumpsuit with custom trimming per role, the main colour being that of the department. These are one-piece jumpsuits, pulled up from the legs over the entire body and zipped up at the front. 
The higher crew style are two-piece uniforms, a shirt (coloured and trimmed by department or role) with trousers.
I could have made them shorts, however that would have required deviating from my plan on having a unified shape and style between the basic jumpsuits of every role - Miscellaneous outfits, such as the delivery boy outfit or the overalls are still role dependent, but due to already having shorts existing with the delivery boy outfit, I didn't feel it was necessary to make another set of shorts.

Here are some examples:
Higher crew uniforms (HoP, QM, planned RD, planned CMO)
image
image
image
image

Lower crew uniforms (Blueshield, janitor, unfinished hydroponics, cargo technician from this PR)
image
image
image
image

On its own, this PR may seem like it's just randomly changing cargo technician from yellow to brown, but in the larger vision I have for the department and the clothing as a whole on the server it fits a lot more the way it is.

As for visual distinction - Outfits have more parts than just these uniforms. Many different suit slot items and hats can be combined - hell this PR even adds some to help with distinction between these roles.

**Comment by evilmattyg** [comment]
>On its own, this PR may seem like it's just randomly changing cargo technician from yellow to brown, but in the larger vision I have for the department and the clothing as a whole on the server it fits a lot more the way it is.

Didn't know this looking at the PR, but if this is a single part of a larger overhaul you are thinking about, could you perhaps make it a bit clearer? My misgivings were mainly if this PR was only in a vacuum, however if this part of a larger overhaul, I'm all for it! Your vision definitely goes way beyond this PR, and looking at the examples above, I love the standardisation of the new uniforms.

**Comment by TORE01** [comment]
Hazard vest looks too much like a life jacket.
Everything else looks nice.

**Comment by ATP-Engineer** [comment]
THESE ARE MY CARGO SHORTS, THERE ARE MANY LIKE IT BUT THIS PAIR IS MINE.

**Comment by Christasmurf** [comment]
As per popular request - Shorts will remain. Ramon has asked me to resprite the delivery boy outfit (and remove the cap) and change it to better match the rest of the cargo plans, so that outfit will be resprited and will remain as shorts as intended so there will be a shorts option for people who prefer that look for their cargo technician gameplay

**Review by Burzah — APPROVED** [review]
These look great, nice work!

**Pull request merged**
