### PR TITLE
Add Jaws of Life to Paramedic locker

### PR DESCRIPTION
**Pull request by Ty-Omaha**
**What does this PR do:**
Adds the Jaws of Life to the Paramedic locker to allow for quick entry in emergencies where every second counts

credit to Mischievous#3759 for the idea

if merged, Space Law should have an exception for Paramedics responding to medical emergencies.

:cl:
add: Paramedic's Locker now has the Jaws of Life
/ :cl:

### CODE REVIEW

**Comment by Markolie** [comment]
I'm not a fan, as paramedics are already disruptive enough when people are doing... illegal things. Somebody's  who's constantly watching suit sensors shouldn't also effectively get access to everything at roundstart.

**Comment by Lunaimon** [comment]
I'm not sure Jaws of Life are the best option for this. Atmospherics has a fire axe for opening doors which is bulky and needs to be carried on the back or in both hands- I think the Paramedic should have something similarly difficult to carry if they need to get into areas they don't have access to.

**Comment by Couls** [comment]
I'm with lunaimon on this, I think if they need easier access they'll need to bring a fireaxe along just like an atmos tech would

**Comment by Quantum-M** [comment]
I don't think the Paramedic should get this from round start (let alone anyone that isn't the CE but that's a different thing) since it also includes the wirecutter and crowbar functions, along with being able to pry open airlocks, which also has some implications in terms of usage of antag paramedics, with more easy ways to enter a area without having to worry about hacking a airlock.

If this does goes through though, it should at least spawn on the paramedic, similar to the CE's tools, because it will probably end up being emagged into by traitors (since the paramedic closet seems very ignorable) or end up being taken by the CMO or anyone with default access to the closet.

**Comment by Denthamos** [comment]
Instead of a jaws of life, a different item with only the jaws function could work for them with it being a size larger at a minimum than its current small size.

**Comment by davidchan13** [comment]
This doesn't make any sense. Paramedics don't run into burning buildings or active crime scenes to save people. 

"Paramedics are standing by" doesn't mean they'll lock pick your door to give you the heimlicch when you are choking.

**Comment by Ty-Omaha** [comment]
>Also, why are you upvoting your own PR :P?

I like it

>This doesn't make any sense. Paramedics don't run into burning buildings or active crime scenes to save people.
"Paramedics are standing by" doesn't mean they'll lock pick your door to give you the heimlicch when you are choking.

Paramedics will very much break down a door if they know that the person inside is in trouble and the scene is safe, also this isn't real life

**Pull request closed without merging**
