### PR TITLE
The (formal CC) blueshield drip is back in town

### PR DESCRIPTION
**Pull request by ElorgRHG**
## What Does This PR Do

Fixes https://github.com/ParadiseSS13/Paradise/issues/19419

Fixes the lack of the formal CC suit in the blueshield's locker.

## Why It's Good For The Game

Drip.

## Images of changes

image

## Testing

Spawned as blueshield, took a screenshot for `Images of changes`, put the uniform on, had positive drip,

## Changelog
:cl:
fix: The formal blueshield's uniform is back in the blueshield's locker.
/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
Thats why I was not fiding this...

Please we need the drip back.

**Comment by Sirryan2002** [comment]
I'm confused to how changing the type path is making this work all of a sudden

**Comment by ElorgRHG** [comment]
> I'm confused to how changing the type path is making this work all of a sudden

In the DMI split I repathed blueshield's uniforms to `.../under/rank/centcom/blueshield`.
Thing is the formal uniform already was a  `.../under/rank/centcom/blueshield`, I forgot about it so the locker has the regular uniform, not the  `.../under/rank/centcom/blueshield/formal`, which the formal uniform was repathed to.

**Review by Sirryan2002 — APPROVED** [review]
makes semse

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
