### PR TITLE
Lavaland - Remaps Labor Camp

### PR DESCRIPTION
**Pull request by DogeDogIs**
## What Does This PR Do

This PR Remaps the Labor Camp in lavaland.

## Why It's Good For The Game

The remap was made with the idea mainly focused on updating the style and improving the security on the map, because our current one contains several problems, which are where the secs need to frequently access the location to bring something new, or need to control something with just one flash, however with this remap I placed a system that we have in perma where the airlock cycles and I also placed more flashers around the prison, establishing a safer climate for the secs.

With the remap, the map was updated, bringing a more modern and beautiful look. I tried to leave the feeling of claustrophobia I had as much as possible, because if you're there, you're not good...

There will be a PR in the future that will add mining suits to the secs, so those 3 tables at the bottom are for that.

## Images of changes

image

In the paper: 

image

## Testing

LocalHost, Buttons, cams, air injectors, and thoses stuffs.

## Changelog
:cl:
tweak: Remap Labor camp
/:cl:

### CODE REVIEW

**Comment by DogeDogIs** [comment]
I don't know why thoses are failings 👍

**Review by DGamerL — CHANGES_REQUESTED** [review]
image

Clean this piping up please

**Review by S34NW — COMMENTED** [review]
https://discord.com/channels/145533722026967040/876666051297935410/1206970783503487086

Changes requested around this message on discord

**Comment by Sadhorizon** [comment]
Hello! As a resident outpost enthusiast, I couldn't help myself but give some feedback.

1. There is a lot of empty space. Sec locker room, sec office, main area, canteen, medical. Some decor wouldn't hurt. Sec office could maybe get some basic floor art or something, idk. Main prisoner room and sec office totally need SOMETHING tho.
2. Kitchen/canteen area feels very awkward. Could try making it less of a rectangle maybe? Shorten it and expand a bit to the left? Maybe make outside more interesting too?
3. In my outpost remap, I added NT signs. I feel like placing them on the outside would add to the feel. Just make sure they don't burn in the lava and are not reachable from the inside.
4. Bathroom has a camera... but a bedroom doesn't? I feel like one is invading privacy more than the other!
5. Location of the ORM feels super awkward. Why not just put it in the box hallway thing?
6. Shuttle could also use some more life. Intercomms, floor decals, maybe more seats. Something to make it more interesting.
7. Does the security airlock need plasma windows? Main sec room has normal ones, if you break there, you are out anyways.
8. Engineering is also an awkard shape. Could bend it to the right maybe? Also, what is that maint door? HERESY!!!!!! It is a proper engi area!!!! Needs a PROPER engi door!!!!!!
9. Generally, nothing is really happening outside most windows. Could use some basic rocks, shrooms or anything really.
10. SMES and PACMAN are kinda far away from each other. They totally could be closer.
11. Does it really need such a big bathroom? Miners don't get one at all, and prisoners get two whole stalls? I feel like showers could be moved somewhere else, and whole room turned into something more fun. Not sure what, but yea.

That's all I see for now!

**Comment by DogeDogIs** [comment]
> Hello! As a resident outpost enthusiast, I couldn't help myself but give some feedback.
> 
> 1. There is a lot of empty space. Sec locker room, sec office, main area, canteen, medical. Some decor wouldn't hurt. Sec office could maybe get some basic floor art or something, idk. Main prisoner room and sec office totally need SOMETHING tho.
> 2. Kitchen/canteen area feels very awkward. Could try making it less of a rectangle maybe? Shorten it and expand a bit to the left? Maybe make outside more interesting too?
> 3. In my outpost remap, I added NT signs. I feel like placing them on the outside would add to the feel. Just make sure they don't burn in the lava and are not reachable from the inside.
> 4. Bathroom has a camera... but a bedroom doesn't? I feel like one is invading privacy more than the other!
> 5. Location of the ORM feels super awkward. Why not just put it in the box hallway thing?
> 6. Shuttle could also use some more life. Intercomms, floor decals, maybe more seats. Something to make it more interesting. Take a look at the main outpost to see what I mean.
> 7. Does the security airlock need plasma windows? Main sec room has normal ones, if you break there, you are out anyways.
> 8. Engineering is also an awkard shape. Could bend it to the right maybe? Also, what is that maint door? HERESY!!!!!! It is a proper engi area!!!! Needs a PROPER engi door!!!!!!
> 9. Generally, nothing is really happening outside most windows. Could use some basic rocks, shrooms or anything really.
> 10. SMES and PACMAN are kinda far away from each other. They totally could be closer.
> 11. Does it really need such a big bathroom? Miners don't get one at all, and prisoners get two whole stalls? I feel like showers could be moved somewhere else, and whole room turned into something more fun. Not sure what, but yea. Toilets could just die.
> 12. Adding a newscaster or two wouldn't hurt!
> 13. The N2O pipe could go under the floor way earlier. Looks ugly.
> 14. Mapdiffbot shows the APC rotated to the right. Please make sure it's not the case.
> 15. Is that an unconnected vent under the table in the bedroom?
> 16. Sec area should PROBABLY get a fire extinguisher. Reminder that there is lava literally in the name of the planet. I understand why prisoners don't get em tho (you can try convincing design/balance people, it'd be dope if they got fire protection too)
> 
> That's all I see for now!

I liked your ideias, I will make them. I just don't know what to put exactly on the empty spaces and what room could I replace the bathroom.

Fire extinguishers for prisioners is probably a nono, since its pretty easy to get out with it, only secs may be enough.

I wanted to remake the shuttle from scratch but I am afraind of touching this, but I can try.

About bedroom not having cams, I tought about one room doens't having cams for fun vampiric things, but I can but a cam in there.

**Comment by DogeDogIs** [comment]
> > About bedroom not having cams, I tought about one room doens't having cams for fun vampiric things, but I can put a cam in there.
> 
> I more am pointing out that a bathroom, a more intimate place, has one. Also, I dunno if it'd be needed. Gulag also has the upside of large unmonitored plains outdoors.
> 
> Speaking of, do the prisoners get gas analyzers? They can check time till next storm. Could be used for said vamp shenanigans. Half-certain those are in the vendor!
> 
> I think you could leave a paper somewhere explaining how it works. More interactive than just a room with no cams, y'know?

About the paper, you mean how the gas analyzer work or something like that?

**Comment by Sadhorizon** [comment]
> About the paper, you mean how the gas analyzer work or something like that?

Moreso, explaining that you even can check that stuff with one, as it's pretty niche knowledge.

**Comment by DogeDogIs** [comment]
image
@Sadhorizon 

So the piping coming hidden earlier fells more akward than having then visible until the door

**Comment by Sadhorizon** [comment]
> So the piping coming hidden earlier fells more akward than having then visible until the door

Hide it and cover with catwalks?

**Comment by DogeDogIs** [comment]
> > So the piping coming hidden earlier fells more akward than having then visible until the door
> 
> Hide it and cover with catwalks?

image
like that?

**Comment by Sadhorizon** [comment]
> like that?

Not needed under the first three. 
But yea, essentially what I meant.

**Comment by DogeDogIs** [comment]
> > like that?
> 
> Not needed under the first three. But yea, essentially what I meant
> 
> Another bit of review:
> 
> * Some of that stuff seems to look weird rotation-wise. Can't recall if ORM and flashers have directionals. If they do, use em.
> * Why are there two baseturf thingies? Isn't it one area?
> * Engi could probably use a portable scrubber (or pump), in case you need to fix air and the large ones get broken.

The ORM and flashers do not have a rotation, sadly. The ORM only have output_dir and input_dir, that I already got them correctly.

No, it's 2 areas, Sec and Brig

Yea, I will add that.

**Review by Henri215 — COMMENTED** [review]
1. You can replace this with the sovietsoda vendor, they shouldnt get free space colas for their crimes.
image

2. This is the best place for the cryogenic oversight console?

3. Probably not a good idea to have light switches available to prisoners.
image


4. Good idea to give this guide paper a name and to create it properly instead of varediting it on the map.
image

5. A prisoner can control this, is it fine?

image

**Review by Henri215 — APPROVED** [review]
Lewcing good to me

**Comment by Sadhorizon** [comment]
Engi lacks a camera. Not sure if you intend it to have one but yea. I think it should! Unlike in perma, it ain't a maint, it's a proper area. But ultimately, up to you.

**Comment by Sadhorizon** [comment]
Shouldn't security windows be electrified? I don't think they are currently.

**Comment by Sadhorizon** [comment]
Yea, looks good for the most part!

**Review by S34NW — APPROVED** [review]

**Comment by DogeDogIs** [comment]
Waiting for Octus reesponse for updated version.

**Review by Henri215 — APPROVED** [review]
Confirming that latest changes are looking good

**Review by S34NW — APPROVED** [review]

**Comment by Sadhorizon** [comment]
👏👏👏

**Pull request merged**
