### PR TITLE
[Feature] Fire Hot! Color Coded Fires

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Adds new color coded fires, determined by the temperature of the air.
This will allow you to roughly approximate the temperature of fires even
from the other side of walls based on their glow. A fire will adjust it's color every time it updates to ensure it is the proper color, so you can watch fresh fires shift through the scale as their conditions change.

In order from coolest to hottest (all temperatures are in Kelvin):
- "Black fire": Below 75K
- Red fire: Between 75K and 1100K
- Orange fire: Between 1100K and 1300K
- Yellow fire: Between 1300K and 1500K
- White fire: Between 1500K and 1800K
- Cyan fire: Between 1800K and 5300K
- Blue fire: Between 5300K and 7150K
- Dark Blue / Purple fire: Between 7150K and 9000K
- "Rainbow Fire": Over 9000K

image
This is an (admittedly poor) example of the "Rainbow Fire". Each fire tile randomly selects it's own color every time it updates.

Due to some issues with sprite editing, I temporarily disabled the use
of 2/3 of the fire tile sprites until I can properly update them while
maintaining their transparent portions. Until this is done,, all fires
will use the highest firelevel sprite set.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Ahahaha this looks awesome.

**Comment by Fox-McCloud** [comment]
Goonfire is best fire.

big :+1: from me.

**Comment by Del1m** [comment]
:thumbsup: :100:

**Comment by TheDZD** [comment]
This looks great, huge :+1: here as well.

**Pull request merged**
