### PR TITLE
Removing a few unused dmi files

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Deletes unused dmi files.
Deleted one random small notes txt file.

<details>
  <summary>List of files removed</summary>
<br>targeted.dmi <br/>
mech_fab.dmi<br/>
o_peg.dmi<br/>
r_armalis.dmi<br/>
r_lshadowling.dmi<br/>
r_nucleation.dmi<br/>
r_plasmaman_pb.dmi<br/>
tatt1.dmi<br/>
hierophant.dmi<br/>
otherhuman/human.dmi and txt file next to it<br/>
spirits/mask.dmi<br/>
mob/32x64.dmi<br/>
clowncar.dmi<br/>
gimmick_head<br/>
livestock.dmi<br/>
roaper.dmi<br/>
mob/vox.dmi<br/>
floors/ash.dmi<br/>
rocky_ash.dmi<br/>
snow_turf.dmi<br/>
icedmetal_wall.dmi<br/>
materialwall.dmi<br/>
mountain_wall.dmi<br/>
red_wall.dmi<br/>
riveted.dmi<br/>
snow_wall.dmi<br/>
turf/catwalks.dmi<br/>
doors/doorf.dmi<br/>
door_fire2.dmi<br/>
doorgold.dmi<br/>
doorhazard2x1.dmi<br/>
doorhazard3x1.dmi<br/>
doorhazard.dmi<br/>
doorsand.dmi<br/>
implantchair.dmi<br/>
metal_detector.dmi<br/>
power_local.dmi<br/>
swarmer_catwalk.dmi<br/>
tram_rail.dmi<br/>
syndieweapons.dmi<br/>
lattice_clockwork_large<br/>
ulicons.dmi<br/>
imap.dmi<br/>
turf/mining.dmi<br/>
atmospherics/mixer.dmi<br/>
atmospherics/outlet_injector.dmi<br/>
pinion_airlock.dmi<br/>
pipes/large.dmi<br/>
pipes/regular.dmi<br/>
catwalk_clockwork_large.dmi<br/>
</details>

## Why It's Good For The Game

There is no reason to keep old unused dmi files on the code.

## Testing

- Compiled and did observe over a few places
## Changelog
No player facing change

### CODE REVIEW

**Comment by Sirryan2002** [comment]
Pretty much all of this are good, I'd double check that the following stuff is not used in the code anywhere:

- icons/mob/livestock.dmi
- Any of the DMI's that have armalis sprites in them
- The santa hat

**Comment by Henri215** [comment]
> Pretty much all of this are good, I'd double check that the following stuff is not used in the code anywhere:
> 
> * icons/mob/livestock.dmi
> * Any of the DMI's that have armalis sprites in them
> * The santa hat
> 
> I've definitely seen all of this in-game before but I'm not sure if that's just cause they're duplicates

All good including the list of the ones i am in doubt that are candidates for removal too?

I did double check livestock, its good to go.
We removed Armalis, should be good to go no?
Santa hat is good to go, confirmed it is a hat that pulls its icon from hats.dmi

**Comment by OctusGit** [comment]
> > Pretty much all of this are good, I'd double check that the following stuff is not used in the code anywhere:
> > 
> > * icons/mob/livestock.dmi
> > * Any of the DMI's that have armalis sprites in them
> > * The santa hat
> > 
> > I've definitely seen all of this in-game before but I'm not sure if that's just cause they're duplicates
> 
> All good including the list of the ones i am in doubt that are candidates for removal too?
> 
> I did double check livestock, its good to go. We removed Armalis, should be good to go no? Santa hat is good to go, confirmed it is a hat that pulls its icon from hats.dmi

Armalis are removed from the code, yes
(Guy who removed them) 👍

**Review by Sirryan2002 — APPROVED** [review]
looks good sprite diff wise

**Review by DGamerL — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
