### PR TITLE
[Fix] Ghost in the Swarming Shell

### PR DESCRIPTION
**Pull request by Aurorablade**
fixes https://github.com/ParadiseSS13/Paradise/issues/2561

based on TG PR

https://github.com/tgstation/-tg-station/pull/12933/files

includes the new sprites for the Reverent (here come the merge conflicts with my other PR). Also includes changes to reveal/stun procs but thats as far as i went.

Bonus: Reverent updated to TG

Alerting: @Fox-McCloud as he did the orignal port

fixes https://github.com/ParadiseSS13/Paradise/issues/2524
and
fixes https://github.com/ParadiseSS13/Paradise/issues/2539
and
fixes https://github.com/ParadiseSS13/Paradise/issues/2560

fixes https://github.com/ParadiseSS13/Paradise/issues/2491 so swarmers cannot understand you fools

### CODE REVIEW

**Comment by Aurorablade** [comment]
I think i fixed the cable bug anyway, what i figured was going on was it was taking in the distance of the cable compared to the pai every life tick while the cable existed..so null out the cable value and it will not spam...IN MY HEAD THIS WORKS.

**Comment by Fox-McCloud** [comment]
If you would like to update revenant to whatever TG currently has it as, feel free to. You're by no means obligated to, and if you just want this to be a fix--that's *more* than ok. Just sayin', if you want to, go ahead.

**Comment by TheDZD** [comment]
If you want the issues to automatically close, each one needs its own line with `fixes #WXYZ`.

**Comment by Aurorablade** [comment]
@Fox-McCloud noted and may do that.

@TheDZD noted and will do that when i change everything else for the ghosty ghostys.

**Comment by Aurorablade** [comment]
making a commit here, worked backwards using https://github.com/tgstation/-tg-station/pulls?q=is%3Apr+Revenant+is%3Aclosed MORE THEN LIKELY MISSED SOMETHING

Did not port the blight spell cuase i got confused on how to translate somethings to para.

things to fix (with help):
GHOSTS DO NOT STEP ON GLASS SHARDS HOW FIX SO NOT STEP ON GLASS SHARDS
lights need to stay purple on the overload bit longer....

**Comment by Aurorablade** [comment]
Edited shards so if it has incorporal move or flying you do not step on them...as you are incorporal and flying.
Was going to try to fix the AI hud issue but got confused trying to figure it out (did find out its like its not hitting its sensor_mode switch at all in its Life call..i think)
Did fix the observer medhud issue...i think it was an issue...someone said it was an issue but i can't find and issue for the issue...

**Comment by TheDZD** [comment]
Looked through it and couldn't find any issues. Going to wait for @Fox-McCloud to have a look though, since he is more familiar with Revenant code.

**Comment by TheDZD** [comment]
Had @ZomgPonies go through this, as he is about to patch. Also went through it again, neither of us could point to any major issues. Merging this as revenant is currently quite broken as-is.

**Pull request merged**
