### PR TITLE
Adds more lobby music and space ambience

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR adds AA's remix of the classic SS13 lobby music for use in our pre-round lobby, and adds 5 new space exploration ambience tracks from Eris.
The tracks have been compressed from the original to avoid bloating the resources we send players, but they are still more than suitable.

Also deleted "music help.txt" because it is just wrong and old and useless.

## Why It's Good For The Game
A broader range of tracks adds extra spice to a long-stale roster, without removing any of the classics.
Space exploration, especially, is terribly repetitive when it comes to ambience, this freshens that up with some creepy tracks, wonderous tracks, and unnerving tracks.

## Included tracks

These are mp4s due to github limitations, unmute them and listen.

https://user-images.githubusercontent.com/12197162/118187212-91a9f380-b436-11eb-8171-b26d623ce842.mp4

https://user-images.githubusercontent.com/12197162/118187213-92428a00-b436-11eb-8893-4835f92c2de3.mp4

https://user-images.githubusercontent.com/12197162/118187214-92db2080-b436-11eb-831c-e37995dd72f6.mp4

https://user-images.githubusercontent.com/12197162/118187216-92db2080-b436-11eb-8d64-aaad70c577fe.mp4

https://user-images.githubusercontent.com/12197162/118187218-9373b700-b436-11eb-895b-e1e0ce419ab4.mp4

https://user-images.githubusercontent.com/12197162/118191277-41359480-b43c-11eb-8316-cb91ba8c78e0.mp4

## Changelog
:cl:
soundadd: Added a new lobby music track and 5 new space ambience tracks
/:cl:

### CODE REVIEW

**Comment by SabreML** [comment]
Just to clarify, are the example tracks in the PR description from before or after the compression in the second commit?
There's been a few PRs messing with audio file compression before and they all tended to be pretty lossy.

**Comment by E-MonaRhg** [comment]
As much as I like Eris's lobby music I _feel_ like it should remain where it is... and well I dont know how to say it word it better but it does not fit Paradise all that much, Eris is a cyberpunk-ish (I dont know genre names all that much) type of server while Paradise is almost entirely just the normal SS13 experience.

Not really in favor of this myself.

Ambience is pretty cool though.

**Comment by S34NW** [comment]
> 
> 
> Just to clarify, are the example tracks in the PR description from before or after the compression in the second commit?
> There's been a few PRs messing with audio file compression before and they all tended to be pretty lossy.

after

**Comment by S34NW** [comment]
Alright, I decided to remove the Duke Gneiss stuff due to people worrying about taking iconic Eris music. I still plan to expand the lobby music roster, but for now we can bump the space ambience roster a bit.

**Comment by Drobe50** [comment]
I like the uneasy feeling of the space ambience, something that has been needed IMO in a while.

**Review by dearmochi — APPROVED** [review]
Approved for code

**Comment by Fox-McCloud** [comment]
Nearly 6 MB of additional music tracks for one location and one new title song---and the quality is significantly lower than our existing ones.

Not particularly convinced of this.

**Comment by S34NW** [comment]
> it

The big chungus was AA's lobby remix, it was 9MB before compression

**Comment by AffectedArc07** [comment]
Yeah I dont see this going anywhere, atleast not in its current state.

My lobby music is a lot of RSC bloat for just a remix of the same song, and the space ambience just sounds "weird" to me for some reason.

I'll let others post their opinions, but I dont consider myself in favour.

**Comment by S34NW** [comment]
Alright, this has gone stale. Closing.

**Pull request closed without merging**
