### PR TITLE
Adds vox quill rustling emote

### PR DESCRIPTION
**Pull request by ExitGame**
Adds in the vox quill rustle emote (backed by lore 100%)
And also updates some instances of if(species.name == "") to if(get_species() == "") 

🆑 
fix: terrible species check
add: vox quill rustle
/ 🆑

### CODE REVIEW

**Comment by Rapidvalj** [comment]
Y A Y A

**Comment by Rapidvalj** [comment]
can confirm, backed by lore

**Comment by tigercat2000** [comment]
The diff for this file is horribly mangled. What text editor did you use for this?

**Comment by ExitGame** [comment]
DM, but I copy-pasted because no desktop GitHub, should be fixed now. @tigercat2000

**Comment by tigercat2000** [comment]
It's definitely not, and the tabbing in the file is mangled as well, it doesn't compile.

**Comment by ExitGame** [comment]
I'll get myself desktop Git and re-do it completely and then update it. We'll see.

**Pull request closed without merging**
