### PR TITLE
You can cuff people with atleast one hand now + refactor of handcuff code

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Makes it so that you can handcuff people with atleast 1 hand. Also refactors the handcuff code.
Alternative to #11122
I myself prefer this one over the alternative.

Fixes: #10644

**Changelog:**
:cl:
tweak: You can cuff people with at least one hand now
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
This makes no sense

**Comment by farie82** [comment]
It currently is near impossible to contain somebody who has only one arm. So people with one arm are legit targets for lethals if they resist. New officers will kill them or let them escape. Either way getting the blame and get called shitcurrity. Experienced officers will get called shitcurrity for hitting somebody to a pulp because they were uncontainable. Yeah I've had this happen a few times.

It's more a gameplay thing than a fully makes sense thing. You can cuff somebody to their belt or to their own arm.

**Comment by KasparoVy** [comment]
> can't find a place to cuff the dude's hand
> cuffs it to their own ankle

alternatively...

> dude has no ankles to cuff single hand to
> cuffs it to their neck

**Comment by Ralta** [comment]
Much prefer this method. 

One-armed crew should not be perm-stunned in order to get them to the Brig. Hell once they're in the Brig, good luck keeping them buckled to a chair etc. Allowing you to cuff them in spite of only having one hand makes far more sense.

**Pull request merged**
