### PR TITLE
Ports TG direction signs

### PR DESCRIPTION
**Pull request by Bm0n**
## What Does This PR Do
Replaces the old direction signs with newer TG ones that look better.

The Supply sign has had its examine texted updated to reference Supply instead of Cargo.

## Why It's Good For The Game

Newer signs that don't have a weirdish 3D popout look to them and better less neon colours.

Plus no more red medbay sign! Red hasn't been used as a colour for medbay in a lonnnng time.

the CARG sign now points to SUPP, the department is called Supply and direction signs are to point towards departments/evac.

## Images of changes

image

image

## Testing

tested locally

## Changelog
:cl: Bmon
imageadd: Ported new direction signs from TG station.
/:cl:

### CODE REVIEW

**Comment by GDNgit** [comment]
The biggest bonus of this PR is gonna be the clown potential of using the "supp" sign
- "Hey, what does that sign say?" "Supp" "Not much, what's up with you?"
- "Hey, what does this sign say?" "Su-up" "No, the brig gets sued and it's in a totally differen't area"
- "Hey, what does that sign mean to you?" "Su-uup" "Well, head to the kitchen if you're so sure of that..."

**Review by Sirryan2002 — APPROVED** [review]
code and sprite diff changes look good

**Review by S34NW — APPROVED** [review]

**Comment by farie82** [comment]
image
The evac sprites got switched around in direction. Can ya fix this?

**Comment by Bm0n** [comment]
> image The evac sprites got switched around in direction. Can ya fix this?

good catch, it's fixed now

**Review by farie82 — APPROVED** [review]

**Pull request merged**
