### PR TITLE
Edits Ice overlay

### PR DESCRIPTION
**Pull request by orelbon**
Changes the ice overlay so it doesn't look like one big square.
icefloor
icefloor2

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Should post pics of this, in game.

**Comment by orelbon** [comment]
alright

**Comment by orelbon** [comment]
how can i set myself invisible in game so i dont die....

**Comment by Iamgoofball** [comment]
@Fox-McCloud have you made cryostal use this yet?

**Comment by orelbon** [comment]
How can i create the ice floor in game i'm having a hard time creating it.

**Comment by tigercat2000** [comment]
depressurization seems like an easy way

**Comment by orelbon** [comment]
I've already deleted like 5 floor tiles and they aren't showing up

**Comment by Fox-McCloud** [comment]
Did you update your branch before making changes

**Comment by orelbon** [comment]
yeah that branch was made today.

**Comment by Plotron** [comment]
I still do not like that it's a regular shape, a cross.
Ice doesn't form like that! Should be something rough all over the tile, in a way that would differentiate it from flour/eggs/whatever white stuff there is IG.

**Comment by orelbon** [comment]
Ice can form like that if it follows the space in between the tiles.

**Comment by orelbon** [comment]
Actually nevermind the current one is pretty good.

**Pull request closed without merging**
