### PR TITLE
Chemistry and Research Balance

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Balances a few chems and R&D a bit more

Removes Potassium Chloride and Potassium Chlorophoride
 - These really didn't serve any purpose other than to be an extremely OP knockout chem that chemists could make 10 seconds into the round; they're from Bay, so it's no shock that these weren't balanced

Reduces the Materials tech origin on plasmaglass and nanopaste from 4 to 3. 
 - This should help gate R&D just a little more and force them to get a little more sulfuric acid before moving onto the next tier level of research

Beepsky Smash now has the stun property instead of Amasec
 - Screw the Imperium; Beepsky is THE Law.

Neurotoxin drink reworked
 - No longer the perfect traitor chem (weaken+silence); still weakens (but not as much/as long), but now has quite a few unique effects tied to it based on how much you consume/how long its been in your system; can make make you dizzy, make your screen shake, or even druggy

Removed Carpotoxin from the carp chinese food; nerfs the zombie powder recipe
- Zombie powder is pretty devastating if you get hit by it; was largely a traitor only chem; this change will require a decent amount of effort invested before you can acquire this (Koi beans)

Glycerol Recipe nerf
- Just returning this to its previous value (I made the original change). Too much glycerol for too little effort, to be frank

Disables Syringe stabbing
- Essentially this gave anyone the ability to have a nigh unlimited amount of parapens/hyposprays; this is easily abuseable by more people than should be.

Rapid Syringe Gun Buff
- Removes the lock on the syringe gun and increases ammo count to 6. With the nerfs to chem explosions and the further nerfs to chems in this patch, this weapon is a lot less abuseable than it used to be; the further slowdown to R&D helps this along further. That said, if this becomes a problem it can be re-locked quite easily.

### CODE REVIEW

**Comment by Earthdivine** [comment]
I question the removal of Syringe Stabbing, it's not as useful as you make it out to be, anyone with any sort of melee resistance is immune to the stab and even breaks the syringe if you do so, making it worthless against sec and command.

**Comment by Markolie** [comment]
:-1: To the nanopaste change. The only thing it'll achieve is slowing down R&D by five minutes, which serves absolutely no purpose. If we keep changing research values as to change the natural progression of R&D we might as well remove it, as R&D was designed to work like that. It's not like those five minutes of running to the outpost for acid are fun or serve even the slightest purpose.

**Comment by TheDZD** [comment]
I have to agree with Markolie on the nanopaste change, there's frankly no purpose for it outside of adding needless slowdown.

**Comment by Regen1** [comment]
Agree with both Mark and Earth

**Comment by Spacemanspark** [comment]
I agree with Mark and Earth as well.

**Comment by Fox-McCloud** [comment]
I'd be more than happy to explain the rationale behind Syringe stabbing; willing to concede on Nanopaste.

For syringe stabbing: 

Instantaneous injection of chemicals is overpowered; everyone knows how BS the hypospray is when you come up against it; syringe stabbing is literally the same exact thing as reloadable autoinjectors (which were also axed); if the target has no armor they get injected with 8 units of what's in the syringe; no matter how much armor they have, however, it's still only a 50% chance of the stab working (and quite frankly, it's not use against command staff/sec that I'm worried about anyway). At the end of the day, syringe stabbing is on the same power level as the hypospray and parapen, and it shouldn't be because of the sheer amount of people that have access to it.

**Comment by Spacemanspark** [comment]
And how often do you exactly see people abusing this?

**Comment by Fox-McCloud** [comment]
Wrong question to ask; if it's abusive, it's abusive; the amount it's used doesn't necessarily make something abusive; it's what that feature is innately capable of. The amount of times it's abused doesn't impact how abusive something is or not.

For example, I only know of one person who ever abused the fact that chemical explosions bypassed the bomb cap, but that doesn't make it any less abusive that it could be (and was) done.

There isn't a legitimate function for it other than to inject someone with nasty stuff against their will as a non-antag (and it makes antagging easier as it alleviates reliance on telecrystals); that's worst case--best case it's annoying when you end up stabbing patients during high-stress situations because you forgot to switch your intent off.

**Pull request merged**
