### PR TITLE
Paramedic Tweaks and Improvements

### PR DESCRIPTION
**Pull request by ConflagratedCanine**
The Paramedic aboard the Cyberiad is _literal_ life saver, but has to jump a few hoops that may impair the productivity of the medbay, and also faces some unique dangers that other, non-security related roles have protections against. In addition, I have made their garage safer to rest in while studying the crew monitor. 

Please discuss balance in the comments - I understand some of these changes might toe a few lines.

Edit: I'll fix the map conflicts (whoops!) once I receive feedback on the latest changes from the maintainer.

## Paramedic Inventory Changes
dreamseeker_2017-03-14_16-00-04
- The Paramedic no longer has to steal a defibrillator from medbay storage or the operating rooms, and       now have one in their secure locker.
- ~~The Paramedic now begins with a box of autoinjectors.
- Paramedic now spawns with their vest.
- Paramedic spawns with a light pen in their pocket, in addition, they get an auto-injector in their suit slot.
- Paramedic no longer spawns with a cigarette in their face slot.
- Paramedic now starts with a first-aid kit, replacing their lone health scanner.

## Garage Changes
dreammaker_2017-03-14_14-42-44
- They also now have a table with a medical belt, medical HUD, and first-aid kit in their garage. 
- Glass has been added to the airlock from medbay, increasing visibility by 100 percent and decreasing medic mortality rate by 12.5 percent.
- Moved the cigarette to the wardrobe locker. Please don't smoke in the medbay.

## Other Changes
- Paramedic can now select 'EMT' as a job title.

:cl: [ConflagratedCanine]
rscadd: Added a defib to paramedic EVA locker
rscadd: added paramedic vest to spawn inventory 
rscadd: added an auto-injector to the paramedic's suit slot
rscadd: added a box of injectors to the paramedic wardrobe
rscdel: paramedic no longer spawns with a cigarette
tweak: made layout changes to paramedic garage in cyberiad.dmm
tweak: paramedic penlight moved to their right pocket.
tweak: paramedic no longer spawns with a medical scanner, instead, they get a first-aid kit with one included.
/:cl:

### CODE REVIEW

**Comment by tylerh95** [comment]
@ConflagratedCanine Nice PR. I don't like the hypospray just because it is a traitor objective, and meant to be "hard" to get.

**Comment by scrubmcnoob** [comment]
Everything besides the hypospray seems good.

**Comment by Fox-McCloud** [comment]
>giving the paramedic a literal hypospray.

Yeah, no; this is unique item that is incredibly powerful; it definitely doesn't belong in the paramedic's hands by default.

Also the 15 melee armor is patently ridiculous, for a class that doesn't need it, what-so-ever.

**Comment by Regen1** [comment]
>Gives the paramedic a hypospray

Give the paramedic a traitor objective that's supposed to be an unique item and fill it with one of the best healing chems in the game from the start..

**Comment by ConflagratedCanine** [comment]
@Fox-McCloud I agree with the hypospray, I included it mostly for the sake of discussion - I also have a version prepared that's loaded with epinephrine instead of omnizine, however this is all balanced around the idea of the medic keeping a limited inventory space. They have a defib now, which is probably more interesting for resetting the clock on someone in hard crit.  
How do you feel about a similar, albeit less powerful item?

As for the suit - The Paramedic spends a lot of time running _into_ danger. It's not uncommon for them to get killed by frustrated antags or bored greyshirts for doing their job. Dropping it to 10 so it's in line with engineering suits, however, seems like a fair parallel. 

I'll change the door back for consistencies sake. The glass door in medbay should be enough to help against spontaneous murder, at any rate.

Any consistency reason for the medkit going into their bag? It's not a problem to change, but I'd like to know going forward.

**Comment by LightFire53** [comment]
Instead of a hypo spray,  why not just get a box of auto injectors? Epinephrine is the ideal chem for them, as someone who is transporting injured to medical.

I agree that the defib could be handy, but the airlock is a no. Not unless you plan on changing the security doors, the command doors, every other departments doors...

Dealing with the hypo, it doesn't need to be a protected job anymore. Oh, and the armour can go. It is meant to be a fancy soft suit. Or you can give it the same stats as the medical hardsuit.

**Comment by Necaladun** [comment]
Keep the penlight, I love it. It's a light source that fits in the ear slot and is very...doctorish.

Apart from that I agree with all the points Fox made. A box of autoinjectors would be nice though they aren't hard to get at all.

**Comment by ConflagratedCanine** [comment]
@LightFire53 

> I agree that the defib could be handy, but the airlock is a no. Not unless you plan on changing the security doors, the command doors, every other departments doors...

Well... I mean - yeah I kinda do want to see department doors like that. But maybe in another PR.

>Instead of a hypo spray, why not just get a box of auto injectors? Epinephrine is the ideal chem for them, as someone who is transporting injured to medical.

How do we feel about a box with three omnizine autoinjectors? 5 units, which is readily available about the station in the form of donk-pockets, and the autoinjector means nobody can abuse it in chemistry.

@Necaladun I had no idea that went in the ear slot! I'll put it back in the locker or pockets.

**Comment by taukausanake** [comment]
For the doors, that should be something Engineering should consider doing literally any round. That or the AI to set but come on, the AI can do literally everything else. I would have Engineering set all the outside department airlocks to fast closing. Hate when a grayshit gets in and does whatever, even if not un-welcomed in

**Comment by MrFroztee** [comment]
There's some assumption that they're going to be in combat, and furthermore, that it's the assistants that would be dealing damage to them, and both are fallacies. If anything, it's the Brig-Medic that would be getting an armored vest, not the Paramedic.

The weird little easter egg of a cigarette in the locker doesn't really make sense, and I think that Paramedic's garage is better known to be a good spot for antagging, which is why I don't like having the airlock be windowed.

On top of all of this, making Paramedic a protected job is the ultimate buff, because you're now confirming 100% that the Paramedic will be a good guy with super good life saving gear, which just doesn't sit well with me for any number of reasons. There are just excessive things that are wrong with this buff that don't seem right to me.

**Comment by Lady-Luck** [comment]
Paramedics need QoL buffs. Most of these changes are not a good way to go about it. The only one I agree with is giving them their own defib.

First of all, vehicles like the paramedic's cart need to not require you to hold the key. While not a big deal for the janitor or the secway, it's a big deal for the paramedic because of the defib they have to lug around if the CMO doesn't want to give them their compact defib.

Second, they're SOL if medbay itself is in a state of chaos. A common criticism is that they don't have surgery access. I believe that a nice QOL change would be to make their unique bed just as good as a surgery table for surgery. Paramedics will need to get their own surgery tools still but they'll no longer feel pressured to turn their garage into their own special OR.

Third, latejoin Paramedics don't have access to a health scanner HUD to my knowledge. Considering all the prep work they have to do already to be effective, this is really major. I would add a health scanner HUD to their locker, or even make them spawn with the health scanner HUD implant. (The latter would be a nice, unique perk to help differentiate them.)

**Comment by ConflagratedCanine** [comment]
@MrFroztee The cigarette isn't an easter egg, it's because I took the cigarette out of their starting equipment.

Also, paramedics are still capable of being antags, they just can't get an objective to steal the hypospray they (were) carrying.

**Comment by FalseIncarnate** [comment]
TRAVIS failed. Not sure if I read the output right, but something involving step_x or step_y i think?

**Comment by KingPhilipIII** [comment]
Omnizine at all is a bad idea. Last I checked any amount(Such as a single bite from a donk pocket) of it is enough to get you addicted now. And then you're screwed without immediate treatment.

**Comment by Fox-McCloud** [comment]
The paramedic is not getting a hypospray, period. It doesn't matter what it has in it or in what about; it's a very high end medical item that is meant to be unique and only in the hands of the CMO or whoever he decides to give it to.

**Comment by ConflagratedCanine** [comment]
@Fox-McCloud

Alright that's sound enough. I'm replacing it with a box of auto-injectors. I had considered doing something else with omizine, but perhaps that's best introduced as a separate item some other time.

**Comment by jughu** [comment]
If anything a paramedic should get is a choose between a compact defib or a back one

**Comment by Necaladun** [comment]
No compact defibs either. Traitor objectives are meant to be unique items that generally only a head of staff has.

**Comment by jughu** [comment]
1-2 unique items are fine if they just dont become common 
Like the hand tele

**Comment by Necaladun** [comment]
Not at all. The intent of all of those items is to get them off a head of staff. The paramedic is a low-level employee who is rarely noticed to go missing.

The hand tele is a bit of an exception with 2, but it's again, in an area that only the heads have access too.

No traitor objective items should be added to anyone else at all without the PR being more specifically about that. There is absolutely no need for those items.

**Comment by ConflagratedCanine** [comment]
@Necaladun how do you feel about limited, non - transferable amounts of omnizine for the Paramedic for use in absolutely direct situations?

**Comment by ConflagratedCanine** [comment]
The lobby defib sits in storage, outside of a locker,  it's picked up by folks that can't find the cyro defib (in use/lost/stolen) or folks trying to bring brute/burn below 200 at the fridge. It also serves as a replacement for any other defibs that go missing in busier rounds.

**Comment by ConflagratedCanine** [comment]
Whoops. Butt-closed the request on my phone.

**Comment by ConflagratedCanine** [comment]
Okay, committed changes relevant to the discussion - I'll fix the map conflict once we get more feedback.

**Comment by Necaladun** [comment]
I'm not opposed to a defib, it makes a lot of sense. I generally grab one asap as a paramed anyway.

Starting with a kit as per other doctors is fine, just don't have it spawn in the paramedic office or it'll become part of the general medbay supplies to be stolen by the CMO.

(I normally just raid the exam room for spare medkits)

**Comment by ConflagratedCanine** [comment]
Yeah, I moved the first aid kit into the paramedics inventory as per @Fox-McCloud request

**Comment by Fox-McCloud** [comment]
Conflicts and fails Travis.

**Comment by ConflagratedCanine** [comment]
@Fox-McCloud Aye, easy fix. I was waiting for more input to make the best use of my time

**Comment by ConflagratedCanine** [comment]
I did something really silly to my original fork, closing this and opening a new, cleaner PR for the sake of discussion and cleanliness when I get more time aaaaaaaa

**Pull request closed without merging**
