### PR TITLE
SSlighting

### PR DESCRIPTION
**Pull request by AffectedArc07**
**What does this PR do:**
This takes the lighting engine away from the ProcessScheduler and hands it off to the StonedMC with a subsystem. This is the start of my journey to kill off the PS so we only have the SMC. It still functions in the *exact* same way, its just handled a lot better now.

**Changelog:**
:cl: AffectedArc07
add: SSlighting
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
When this gets label'd up, can this get the StonedMC Milestone tacked to it?

**Comment by Fox-McCloud** [comment]
Conflicts.

**Comment by AffectedArc07** [comment]
Deconflicted

**Comment by Fox-McCloud** [comment]
Right, so there's a number of problems with this.

(1) It can't delay processing, so it can potentially consume the entirety of the CPU
(2) I have concerns about the returns to huge lists. This was a major improvement @Krausus engaged in with: https://github.com/ParadiseSS13/Paradise/pull/6528

This is going to have to be properly integrated into the SMC with proper deferral, or else this could very easily crush the entire server (lighting is easily the most expensive process we have now, at the moment, and that's with atmos running every 0.5 seconds).

**Comment by KasparoVy** [comment]
God bless krausus

**Comment by AffectedArc07** [comment]
I attempted this earlier. I managed to slow down the stat updates, but attempting to add tick checks to SSlighting then broke it at roundstart, and lights needed to be manually updated. If anyone has any ideas please share

**Comment by Fox-McCloud** [comment]
Only thing I can think of is having args for `fire` that prevent it from tick_checking during the very first `fire` during `initialize`, but it defaults to tick checking from then on out.

**Comment by KasparoVy** [comment]
Nat 20'd that stab!

**Comment by Markolie** [comment]
I've created https://github.com/ParadiseSS13/Paradise/pull/11357 so we're up-to-date with /tg/'s lighting system, which in turn allows us to fully rely on their implementation of the lighting subsystem. That way we won't have to re-implement Krausus's improvements (I would assume).

**Pull request closed without merging**
