### PR TITLE
Removes vox... from vox accesories (hair, markings)

### PR DESCRIPTION
**Pull request by png103**
## What Does This PR Do

Removes the word "vox" from vox hair/beard styles and body/tail markings
## Why It's Good For The Game

It would be annoying if every human hair style was called
"Human bald" "Human Long hair" "Human fade"
## Images of changes

image

## Testing

Started the game and went to the character build thingie and wow it worked

### CODE REVIEW

**Comment by GDNgit** [comment]
My disappointment is immeasurable

**Comment by S34NW** [comment]
This actually might cause issues, as the admin "change my appearence" menu has many overrides to let you choose things you shouldnt be able to, removal of the "Vox" terminology might cause someone to try and apply "Pigtails" thinking it's normal hair only for it to be super wonky

**Comment by png103** [comment]
ok honestly that is a good point

**Comment by ppi13** [comment]
Rename Pigtails to Pigtail Quills

**Pull request closed without merging**
