### PR TITLE
Removes a random pipe and cable from engineering

### PR DESCRIPTION
**Pull request by LittleBigKid2000**
There's a disposal pipe and cable in engineering under and next to the
door to the hardsuit storage. Neither connect to anything or seem to
serve any purpose.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Pics?

**Comment by LittleBigKid2000** [comment]
Before change:


After change:


(The airlock is still there, don't worry about it. I just removed it for the screenshot so that the cable and lack of said cable would be more visible)

**Comment by LittleBigKid2000** [comment]
Phew, no problems this time. At least, no problems after the PR was made.

**Comment by FlattestGuitar** [comment]
And suddenly **problems!**

**Pull request merged**
