### PR TITLE
Fixes Battle Arcade Rupturing Eardrums

### PR DESCRIPTION
**Pull request by Robertha89**
Reduces sound range from 12 to 3.

### CODE REVIEW

**Comment by Robertha89** [comment]
Technically a bug fix.

**Comment by Plotron** [comment]
Finally some justice.

**Comment by KasparoVy** [comment]
Used to be so damn loud, SO DAMN loud

T_T

**Comment by Fox-McCloud** [comment]
Don't think this is going to make much of a difference, to be honest. Could be wrong; may want to adjust the volume of it on playsound, directly.

**Comment by tigercat2000** [comment]
This isn't actually doing fuckall except changing the range, so chemistry won't be able to hear it. Change the third values for everything lower, it's currently `50`

**Comment by Robertha89** [comment]
this is as ready as it can be.

**Pull request merged**
