### PR TITLE
Add the Feminine Jumpsuit to the Suitlord9000

### PR DESCRIPTION
**Pull request by PigeonLord**
37097427-082cccc6-21e1-11e8-94f5-56f2f9624577
Again, self explanatory. I added the Feminine Jumpsuit to the Suitlord9000.
🆑 Piccione
rscadd: Added the Feminine Jumpsuit to the Suitlord9000
/:cl:

### CODE REVIEW

**Comment by DesolateG** [comment]
Pictures of it please

**Comment by PigeonLord** [comment]
Done

**Comment by Aurorablade** [comment]
No. I play female characters and no

**Comment by DesolateG** [comment]
So? This isn't Aurorablade Station is it?

**Comment by DarkPyrolord** [comment]
Going to be a no from me, jumpsuit doesn't really look all that good in the first place, would love to see a sprite PR to make it look a little better though before another version of this PR is made if you want it to try again.

**Pull request closed without merging**
