### PR TITLE
Makes the Code Compile for 508.1287+Travis Update

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Preps for moving to 508.1287

- Throw is an actual proc in that version of BYOND, therefore we can't exactly use it in the code anymore.

- Updates Travis to be based around 508.1287.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
:+1: 

Did you bother checking is any of the code uses the 'appearance' var, which is now a BYOND var like color? This also needs to be accounted for.

**Comment by Fox-McCloud** [comment]
no var specifically named "appearance".

**Comment by tigercat2000** [comment]
Should probably make it minor 1288

**Comment by Fox-McCloud** [comment]
Yup; was just released today.

**Comment by tigercat2000** [comment]
508.1288 apparently doesn't have a compiled linux build on the download site.

**Pull request merged**
