### PR TITLE
Better Portable Generator Sprites

### PR DESCRIPTION
**Pull request by uraniummeltdown**
pacman
New pacman sprites from -tg-
I know the old sprite in the picture isn't exactly the same as ours but they're still bad compared to these new ones

:cl:
imageadd: New PACMAN portable generator sprites
/:cl:

### CODE REVIEW

**Comment by Ty-Omaha** [comment]
At first I was like "eh"

and then I saw the flashing lights 👍

**Comment by taukausanake** [comment]
But the old Pacman sprites. I like them. Can't we have these new sprites as upgraded generators or something? They look more like processing machines too.

This is making me wish the old Pacmans made smoke every once in a while and better ones could be more clean. Factorio these things a little

**Comment by tigercat2000** [comment]
I actually like our pacman sprites, they're not as fugly as /tg/'s.

**Comment by Fox-McCloud** [comment]
Oh, I really like these.

**Comment by Rumiluntti** [comment]
tg ones look like a generic boxes with blinking lights and shit slapped on to distract you from the fact

**Comment by Ralta** [comment]
I really like the new ones, but I almost feel like they don't fit the aesthetic of Para...

**Comment by Shadeykins** [comment]
Not a fan of the blinking lights on them at all. I would rather see a more industrial looking aesthetic than these - they don't really fit with the general style of Para.

**Comment by uraniummeltdown** [comment]
Paradise doesn't even have a consistent aesthetic or style, the vast majority of our machine sprites are just -tg- and Bay sprites made by many different people over the course of the years. The new sprites are a lot more visually interesting and detailed than the old boring black box ones.

**Comment by Spacemanspark** [comment]
I kinda like the old ones better honestly.

**Pull request merged**
