### PR TITLE
ViewMods - Allows custom view ranges.

### PR DESCRIPTION
**Pull request by tigercat2000**
The primary function of this is a new button in the "Preferences" tab -
Set View Range. This functions similarly to the admin verb "Change View
Range", but it only allows you to set view ranges lower than the normal
world.view.

Full changelog:
 - Added ViewMods system to clients.
   - Everything that wants to change client.view should do it through
   this system.
   - Currently used by the Set View Range button and Marauders.
   - Stretch mode is set to stretch when active, but the original
   setting is preserved, as long as you set it with no ViewMods enabled.
   - The basic way this works is that it keeps track of /datum/viewmods
   on /clients, and whenever one is added or removed, it picks the
   highest view range out of all of them and sets the client's vision to
   that. This effectively means that, if you, say, set your view range
   to 5x5, and get into a Marauder and use the "zoom" button, it will
   always go to the marauder's zoom level.
   - The HUD is set to minimal mode for any view ranges below
   world.view, which means you only get absolutely critical buttons.
   	- It's set to invisible if you go down to view range 1 or 2,
	because the buttons can't fit on the screen at those view
	ranges.
 - Removed canvas examine option. Just zoom in yourself!

:cl:
rscadd: You can now zoom in with the Set View Range option in your Preferences tab!
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
Soooo not that this doesn't look like an idea but what purpose would this serve in-game? I can already seen no one using this for any reason. Less view range means more chance someone is going to murder you

**Comment by tigercat2000** [comment]
@taukausanake Painting is obviously a reason, due to how small the canvases are, but no one probably does that anyways- You could also use it for a bigger target if you're in the glass boxing arena. Or, you could just use it for pretty screenshots.

**Comment by taukausanake** [comment]
@tigercat2000 I was thinking screenshots initially but sounded kind of niche. Canvases and hitboxes are good reasons though. Very casual I have to comment however

**Comment by HereticChurch** [comment]
Not every feature has to have a mechanical benefit to it.

**Comment by KasparoVy** [comment]
Really nice. No reason not to have it, not to mention there's a ton of potential here.

**Comment by DesolateG** [comment]
Good for screenshots.. thumbs up

**Pull request merged**
