### PR TITLE
Upgrades ID Computer

### PR DESCRIPTION
**Pull request by Kyep**
Job transfer buttons in ID computers are now color-coded:
- The job the ID currently has shows up with a gray background and white text.
- Jobs that are totally full (no free positions) show up with gray text.
- Karma jobs the ID's owner has not unlocked also show up in gray text. IDs with no clear owner (spare/shared/blank/agent/etc) treat all karma jobs this way.
- Jobs that have NOBODY in them currently (and hence are probably a good idea for a job transfer) are highlighted with green text.

id_computer_explanation

Note: this doesn't actually force you to pick any job in a job transfer, nor does it prevent you from assigning any job to a card. All it does do is color-code the jobs, giving HoPs the information they need to make better decisions.

Job transfers via an ID computer now generate a log which can be viewed on any other ID computer, including modular ones, and laptops/tablets with the ID computer program. These logs can be deleted as well.  Currently both "delete my entries" and "delete all entries" are supported, but I plan to remove one of them depending on feedback. Deleted logs can still be viewed on centcom computers.

job_transfer_log

Additionally:
- Someone being transferred to a job they seem to be job banned from now generates a warning to online admins.
- Inserting an ID that has been demoted or terminated into the ID computer generates a special "(name) has already been (demoted|terminated)!" instead of the normal demote/terminate buttons. This serves as a heads up to the HoP/Captain regarding individuals demoted/terminated by others. To make this work, demoting an ID now gives it the "Demoted" rank, so it can be distinguished from blank IDs (which start as "Unassigned").
- Crew who transfer from one department to another will now properly accrue playtime for their new department, rather than continuing to accrue playtime for their old department. This does NOT give them any of the other perks of their new department, like the ability to buy traitor items based on their new job.
- These changes apply to both proper ID computers, and modular computers.

Overall, these changes should:
- Make it easier for HoPs to find a suitable job to place job transfer seekers into, with less risk of assigning too many people to a job.
- Make it possible for HoPs to grant transfers to karma-locked positions, because they can now find out if someone has the position unlocked without having to contact CC. Asking them to do that was a problem, because nobody except heads of the staff team could do the database queries necessary to find out if someone really had unlocked a certain job, which, in practice, was leading to transfer requests to karma job positions NEVER being granted.
- Make it less likely that people get away with using the HoP to evade a job ban.

:cl: Kyep
add: The ID computer now color-codes potential job transfer options, highlighting good choices for a job transfer in green, and bad ones in gray.
fix: Taking a job transfer now gives you playtime based on your new job, instead of incorrectly still giving you playtime based on your old job.
tweak: Job transfers to karma jobs are now possible - if you have the job unlocked.
add: Attempting to bypass a job ban via a job transfer now generates a warning to all online admins.
/:cl:

### CODE REVIEW

**Comment by TDSSS** [comment]
Will HoP SOP be adjusted since there is no need to fax CC about karma jobs anymore?

**Comment by Kyep** [comment]
That's the idea.

**Comment by Kyep** [comment]
Updates:
- Fixed a nasty previously existing bug with centcom ID computers.
- Added a log for job transfers. Viewable on any ID computer, including the modular ones and department management consoles. The log can also be deleted if you're up to no good. Admins can use a centcom ID computer to see the log even if its deleted.

**Comment by Twinmold93** [comment]
Actually, under the playtime system you implemented, regular admins could see what roles people had unlocked with Karma as it would appear in that list as unlocked roles.

I see no issues with this PR's concept.

**Comment by Kyep** [comment]
@Twinmold93 The jobs unlocked / jobs unlocked list in the playtime panel only shows jobs with playtime requirements, and only considers playtime requirements. Karma jobs do not even show up in the list.

**Comment by Twinmold93** [comment]
I thought it had all unlocked positions as well, as I could have sworn I had seen them before somewhere.

**Pull request merged**
