### PR TITLE
Radio resprite

### PR DESCRIPTION
**Pull request by McRamon**
## What Does This PR Do
resprites radio.dmi

## Why It's Good For The Game
resprite of old

## Images of changes
image

## Changelog
:cl:
imageadd: new sprites for radios of all kind
/:cl:

### CODE REVIEW

**Review by DGamerL — APPROVED** [review]
Looks Good To Mcramon

**Comment by 1080pCat** [comment]
might be worth noting that the station bound radio, the big one thats usually used as the nukie uplink *is* used elsewhere, like ert gets real centcom bound ones, and theres one that spawns on meta
image
so it being red may be a little weird?

**Comment by McRamon** [comment]
> might be worth noting that the station bound radio, the big one thats usually used as the nukie uplink _is_ used elsewhere, like ert gets real centcom bound ones, and theres one that spawns on meta image so it being red may be a little weird?

What do you mean red? The screen part is orange and its just a color that i found to work well within palette, its not referencing anything

**Comment by 1080pCat** [comment]
> What do you mean red?

Oh, sorry, it looks red to me ~~colour blind~~, figured it was meant to be red since syndicate

**Review by S34NW — APPROVED** [review]

**Pull request merged**
