### PR TITLE
Skin-tone in Tail Icon Generation

### PR DESCRIPTION
**Pull request by KasparoVy**
This will most likely conflict with https://github.com/ParadiseSS13/Paradise/pull/7366, but resolving it on either end won't be an issue.

Tails can now coloured by skin-tone as regular limbs can be.
However, no species currently uses this _**outside of adminbus.**_
Was missing for so long due to my own oversight.

:cl:
rscadd: Tails now have the potential to be coloured by skin tone (not currently used by any species).
/:cl:

_In example: A Vox varedited to skin tone -115._
darkvox

Before this PR, the tail would just be green (default Vox colour).

### CODE REVIEW

**Comment by taukausanake** [comment]
Nice demon Vox. Do they come in neon pink?

**Comment by KasparoVy** [comment]
Anything I've missed..?

**Comment by KasparoVy** [comment]
I don't understand why something this small should wait a month.

**Comment by tigercat2000** [comment]
After discussion between the Heads of Staff and Maintainers, it was decided to close this PR, as it adds yet another layer of complexity to the human/update_icons code, which is already a massive maintanability issue, in addition to yet again complexifying a system that is already in such a state that it makes it frustratingly hard to refactor into something more workable.

**Pull request closed without merging**
