### PR TITLE
Adds color to debug text

### PR DESCRIPTION
**Pull request by Contrabang**
## What Does This PR Do

Adds a custom span class for debug logs, while still trying to keep them non-intrusive.

## Why It's Good For The Game
Its hard to tell debug logs against normal chat messages

## Images of changes

image
image
Debug logs compared to science comms, server announcement, and deadchat

## Testing

See above

## Changelog
:cl:
nothing player facing
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
See how the same span used for [Server] messages looks compared to science and other channels.

The purple on black hurts to read.

**Comment by Contrabang** [comment]
image
image
Heres it compared to server currently, and science is in the current PR images, I'll get a better darkmode color

**Comment by Contrabang** [comment]
image
image
Heres the new colors, with debug, science, server announcement, and deadchat in that order

**Comment by AffectedArc07** [comment]
> image image Heres the new colors, with debug, science, server announcement, and deadchat in that order

Much prefer this

**Review by Sirryan2002 — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
