### PR TITLE
medbeams now heal ipcs since it is the future

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Medbeams now heal robotic limbs

## Why It's Good For The Game

medbeams heal borgs for god sake and this is a gamma item or nukie weapon it can heal robotic limbs please.

(this is not an I ded please nerf this is a why moment)

## Testing

It worked.

Then we scoped it to human so it would pass checks

## Changelog
:cl:
tweak: medbeams now heal ipcs / robotic limbs
/:cl:

### CODE REVIEW

**Comment by OctusGit** [comment]
Reposting my personnel criticism I wrote in coder channel on this PR

> you know im of the opinion that i dont really see why the beam should actually heal IPCs, i thought that was the whole point. Hardmode race and stuff etc plus how does healing fix metal. Bit inconsistent.

Cyborg limbs should not be fixable from the beam to fix the inconsistency ngl

**Comment by Gaxeer** [comment]
To be logical, you also must make healing beam work for borgs.
But overall I don't like the idea, tbh

**Comment by Qwertytoforty** [comment]
> To be logical, you also must make healing beam work for borgs. But overall I don't like the idea, tbh

they already heal borgs

**Comment by Gaxeer** [comment]
> > To be logical, you also must make healing beam work for borgs. But overall I don't like the idea, tbh
> 
> they already heal borgs

ye, I was told that in discord :D So it's logical

**Review by Burzah — APPROVED** [review]

**Review by S34NW — APPROVED** [review]

**Pull request merged**
