### PR TITLE
Thickmaterial

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Thickmaterial Update

Adds in the "THICKMATERIAL" flag. This is a quick way of giving syringe/hypospray/parapen/dart/bandage/ointment immunity to particular articles of clothing instead of snowflaking out specific protections in the code itself. I admit, I'm not a fan, _at all_, of parapen checking for THICKMATERIAL, but protection from the hypospray and syringes is fairly logical.

Things that pierce through THICKMATERIAL anyway: 
 - auto-injectors
 - combat hypospray

Fixes
 - Shotgun darts now finally work!

New Feature (because of shotgun dart fix)
 - Syringe gun is now an actual gun instead of a hacky piece of crap; as such the projectiles it fires will obey the THICKMATERIAL flag and bounce off people who are wearing hardsuits.

Other Changes:
 - unified the sleepy pen and paralysis pen; there really wasn't a reason for both of them and the code for them was really ugly and sloppy

No idea why DZD's changes are showing up in my PR--oddly enough his changes, despite being patched properly aren't in the codebase, so perhaps that's why?

### CODE REVIEW

**Comment by fj45** [comment]
Wait, will this mean that anyone in hardsuits will have a very hard time getting medical help? Even not being able to use burn/brute patches can be near deadly.

**Comment by Fox-McCloud** [comment]
Yes, it means you're going to have to either take the hardsuit off or toggle the helmet down for them to inject you in the head/neck.

Auto-injectors (what you should be using for those "deadly situations") pierce right through a hardsuit though.

**Comment by fj45** [comment]
That really should be changed, the "They hunt for an injection port" was fine. Having it like that will simply make it damn near impossible to get any kind of healing in certain situations.

**Comment by Fox-McCloud** [comment]
It's not that hard to toggle the hardsuit helmets, and it's not that hard to remove a hardsuit; players already had to do that with bruise/burn packs---now the behavior is consistent across the board

**Comment by adrkiller59** [comment]
I STRONGLY AND HEARTFULLY APPROVE FOR HARDSUITS TO PROTECT FROM SYRINGE GUNS, PARAPENS AND THE GORKDAMNED CHLORAL HYPOSPRAY.

**Comment by Fox-McCloud** [comment]
Update: Medical stacks now obey THICKMATERIAL instead of having a snowflake check for spacesuits.

**Pull request merged**
