### PR TITLE
Adds a bunch of new drinks and bottles (Fixed Sprite Edition!)

### PR DESCRIPTION
**Pull request by LilyCandyKitten**
## Note
Credit to @Dovixx and @PidgeyThePirate for the code.
I made all of the sprites.

## What Does This PR Do
- Adds about 90 new drinks and bottles combined. (Some improved from the previous closed branch.)
- Fixes spelling in descriptions of wine, ale and cognac.

## Why It's Good For The Game
Adds a lot variety to the game making it more unique. More fun for the bartender and bar visitors.

## Images of changes
fixed sprites

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
image
Im not one to normally complain about sprites, but the inconsistencies on the corner of the juiceboxes are **REALLY** jarring and just look bad.

(For reference, the brown in the background of this image is the same shade that wooden tables use)

**Comment by McRamon** [comment]
I am also not really satisfied with sprites, they may have different names, but many are very repetitive, having only color of liquid changed. Inconsistency too, as AA noticed, some glasses have highlight, some don't, and so on.
Quality of sprites too. Some are just flat, boring, or with weird glass shape.
Screen Shot 05-27-20 at 03 56 PM 001
Screen Shot 05-27-20 at 03 56 PM

Others repeat original drink sprites, which are not great and need improvement. However originals have some good examples (nuka cola, demon's blood, beepsky smash, and a few others), while among the drinks in this PR i can't really point out a single interesting drink. No animations used anywhere as far as i can see to support cool "complicated" (lore-wise) drinks.
I highly recommend you continue working on sprites, and i am willing to provide help with that (and others i am sure too). 
PR by itself is good, having more drinks to be able to make is good for RP (however there should not bee too many of drinks, especially those which don't really do anything, to avoid overwhelming). I would rather half the amount the drinks in this PR, remove a few most boring/bad drinks from the existing list and combine the results. Also interesting effects added to some of the drinks is a good idea also.

**Comment by AffectedArc07** [comment]
Also quick tip for the future
image

Using your master branch is a bad idea, for future PRs you'll want to make separate branches, to avoid lumping everything together

**Comment by MRgaty** [comment]
Not a fan of those sprites either, they really dont fit with the quality of the current drinks sprites.

**Comment by Spacemanspark** [comment]
I think a bit of shading would go a long way to improving many of these sprites.

**Comment by LilyCandyKitten** [comment]
Note: I will be working to improve these with your criticism. I will be working with McRamon to improve them.

**Comment by Krysonism** [comment]
As someone who has done a lot of drink sprites for tg, I think I can give you some advice on how to improve these if you want.

Feel free to contact me, I am Kryson on the spriter discord and the tg discord.

Here is a quick respite of on of the sprites.

resprite

**Comment by MRgaty** [comment]
Am sure you will get them look very nice eventually, keep trying!!

**Comment by AffectedArc07** [comment]
This PR will be closed, due to it having objections from a head and maintainers, and changes were requested in may and it is now august.

**Pull request closed without merging**
