### PR TITLE
New Lavaland Outpost (First Time Mapping)

### PR DESCRIPTION
**Pull request by Venuska1117**
Add new lavaland outpost for lavaland, but have issues.

## What Does This PR Do
New Look For Lavaland Outpost

## Why It's Good For The Game
It will create better experience on lavaland outpost

## Images of changes
Before:
image

After:
image

## Testing
Tested on local server:
All Catwalk dissapear, and catwalk what go across lava seem to be burned down every time its rendered.

## Changelog
:cl:
Add: whole new outpost.
Add: missing AI pads
Add: Rust and webs in maintences
Change: Switched 2 computer consoles to unbuild computers and 1 charging port to unbuild machine frame.
/:cl:

### CODE REVIEW

**Comment by warriorstar-orion** [comment]
The People Have Spoken

17_29_05__#coding_chat _ Paradise Station - Discord-

**Comment by S34NW** [comment]
I'll give this a look over soon, but it looks very promising.

**Comment by procdrone** [comment]
in my opinion, mining doesnt need 4 mech recharger ports roundstard.

also, are we sure miners now getting a sleeper desired, balance wise?

**Comment by Venuska1117** [comment]
> in my opinion, mining doesnt need 4 mech recharger ports roundstard. (which is double what robotics has, mind)
> 
> also, are we sure miners now getting a sleeper desired, balance wise?


There was discussion on discord with others, and they say that sleeper is not like "ground breaking" and you need other person to apply medicine in it, miners rarely use "medbay" on outpost.

About 4 mech charging stations, its in case if more miners want exosuits for mining, but they don't need to be used.

**Comment by Sadhorizon** [comment]
> also, are we sure miners now getting a sleeper desired, balance wise?

As I was one to suggest it, here is my reasoning:
First off, every shelter pod already comes with one. Nothing stops miners from using those

In addition, as stated above, it is a reliable healing source, that needs second person to work

**Comment by Sirryan2002** [comment]
Don't miners already get sleepers in mining pods? The mining outpost having a sleeper isn't something that seems unbalanced to me because of that. Also when miners receive enough damage for pods to be actually useful it's also likely they're about to be demolished by a drake or megafauna

**Pull request closed without merging**
