### PR TITLE
Fixing Door names (and other stuff) at new Lavaland outpost.

### PR DESCRIPTION
**Pull request by Venuska1117**
## What Does This PR Do
Fixing my lack in english and some issues from previous map management.

## Why It's Good For The Game
It will less likely to make people annoyed (ones who dislike wrong spellings) and labor camp issues fixing

## Images of changes
Before:
image

After:
image

## Testing
Will be tested when all issues are gone.

## Notes
- Changed names to fitting ones
- Now Labor camp have fixed cables
- Make labor camp escape more possible (before it was nealy impossible without someone else help)

## Changelog
:cl:
fix: Doors are named correctly now
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
Looks like there's one more problem that was missed when you made the change to the Lavaland outpost, in the Gulag's power room.
Before:
image
After:
image
Electricity is generally a positive to the labor camp so it may be worth just fixin' the cables.

**Review by S34NW — CHANGES_REQUESTED** [review]
> Why did you make it easier for gulag prisoners to escape the gulag without mentioning it at all in this PR?
> 
> image

Hard no from me until this is addressed

You also have two wire nodes under this generator now:
image

This door needs proper capitalisation:
image

These 4 could be renamed from "Mining Station Bridge" (as it isn't a literal bridge anymoe) to something generic such as "Mining Station"
image

**Comment by S34NW** [comment]
image
In addition to the above, please restore _all_ the wires for gulag.

**Review by S34NW — APPROVED** [review]
Changes made as requested, approving.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
