### PR TITLE
Make the l6 shoot .308 rather then 5.56

### PR DESCRIPTION
**Pull request by shazbot194**
This PR makes the L6 shoot 308 rounds. This has no mechanical change, but makes it so you can't have a situation where you can have 5.56 ammo that can't load into a 5.56 gun. The reason why its not 7.62 like it originaly was, because we already have 2 different 7.62s, 7.62x54rr and 7.62x38mmR, and adding in 7.62x51mm would be rather confusing to someone who isn't gun/ammo savvy.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Conflicts my dude

**Comment by shazbot194** [comment]
Ya, I am fixing them already, and I get the map conflict, but how did the uplink conflict? It is literally changing a description.

**Comment by SamHPurp** [comment]
New jammer tot item got merged inbetween your push and pull

**Comment by shazbot194** [comment]
Ahh, that would explain it.

**Comment by shazbot194** [comment]
Due to the conflict happening from me having a slightly old code and it being a lot cleaner If I do, I am closing this PR, updating my master, and remaking this pull.

**Pull request closed without merging**
