### PR TITLE
Fixes Blind Player Preference Doing Nothing

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes the blind player disability preference not doing anything

:cl: Fox McCloud
fix: Fixes the blind player preference not doing anything
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
Time to make a blind, mute captain.

**Comment by KasparoVy** [comment]
That's 17

**Comment by monster860** [comment]
And has no limbs.

**Comment by Fox-McCloud** [comment]
>has a floor-length braid

Never change, @KasparoVy

**Comment by Spacemanspark** [comment]
remove floor length braids when

**Comment by Earthdivine** [comment]
@Spacemanspark Over my dead body :C

**Pull request merged**
