### PR TITLE
Added anti-hobo spikes

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds anti-hobo spikes, hurts a little when you walk over it. Anti hobo measures are activated when you crawl on it :).

Could be mapped in front of the bridge if its possible to avoid map conflicts.
## Why It's Good For The Game

NT is losing too much money by paying useless workers, its time to do something about it!
## Images of changes

https://user-images.githubusercontent.com/77684085/229167837-c2cdcae9-a0a0-4606-bafc-948ae29dff73.mp4

## Testing

video above
## Changelog
:cl:
add: Added anti-hobo spikes, hobos are no longer allowed by Nanotrasen
/:cl:

### CODE REVIEW

**Comment by Screampuff** [comment]
Oh my god

**Comment by Gatchapod** [comment]
What do you mean "meme PR"?

**Comment by Henri215** [comment]
> What do you mean "meme PR"?

image
No idea, april fools is tomorrow, this is a serious PR :)

**Comment by lewcc** [comment]
I earnestly believe this would be really funny to implement with like lever support or something after AFD

**Comment by Henri215** [comment]
> I earnestly believe this would be really funny to implement with like lever support or something after AFD

A lever that could be activated by admins, alternative to rods :D

**Comment by Gatchapod** [comment]
> > I earnestly believe this would be really funny to implement with like lever support or something after AFD
> 
> A lever that could be activated by admins, alternative to rods :D

Make it a station goal!

**Comment by AffectedArc07** [comment]
Were NYC now

**Pull request merged**
