### PR TITLE
Changes Area Classification of Farragus Science & Cargo Solar Arrays, Standardizes Solar Areas.

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
Changes Farragus Cargo Solar Array from "Aft Starboard" to "Fore-Starboard"
Changes Farragus Science Asteroid Solar Array from "Aft Port" to "Aft"
Names of all solar locations are properly hyphenated.

Not player facing:

All solar array and solar maintenance areas are now properly named and have their own individual icons. Icon names are all in `snake_case`.

All solar arrays and solar control rooms are now each subtypes of a general parent type so they aren't spread all across the selection menu when map making.

## Why It's Good For The Game
Cargo solars being "aft" is just plain incorrect.

Science solars are roughly central on the map, not to the left.

snake_case is desirable, correct names and icons for all the areas are good.

All 8 cardinal directions can now be chosen from when placing a solar array, good for future map edits or entirely new maps.

## Testing
- [x] Visit all solar arrays on Box and verify areas are correct.
- [x] Visit all solar arrays on Delta and verify areas are correct.
- [x] Visit all solar arrays on Meta and verify areas are correct.
- [x] Visit all solar arrays on Cere and verify areas are correct.

<hr>

### Declaration
- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/feature_freeze/CODE_OF_CONDUCT.md#currently-changes-to-the-following-types-of-content-reuires-pre-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.

<hr>

## Changelog
:cl:
fix: Changes Farragus Cargo Solar Array from "Aft Starboard" to "Fore-Starboard"
tweak: Changes Farragus Science Asteroid Solar Array from "Aft Port" to "Aft"
/:cl:

### CODE REVIEW

**Review by Miraviel — CHANGES_REQUESTED** [review]
> Changes Farragus Cargo Solar Array from "Aft Starboard" to "Fore Starboard"
All good

> Changes Farragus Science Asteroid Solar Array from "Aft Port" to "Aft Starboard"
This is not right, aft starboard should be southeast. If I was told to look for aft starboard solars, I'd look around arrivals. I'd suggest to either simply create an "Aft Solars" area to avoid confusion or leave this be - both "aft port" and "aft starboard" are equally wrong in this situation I think.

> Changes the tiny useless Arrivals Solar Array from "Aft Starboard" to "Starboard"
Starboard implies east, around medbay, this is the southeast(-central) section of the station, I'd leave it be (whatever awkward spot it is in).

**Review by FunnyMan3595 — APPROVED** [review]

**Review by DGamerL — CHANGES_REQUESTED** [review]
Not ready for merge yet, PR is being looked over by the mapping team

**Review by warriorstar-orion — APPROVED** [review]
Thanks for those icon cleanups/renames especially, those were awful

**Review by DGamerL — APPROVED** [review]
Map team approval aswell, LGTM

**Pull request merged**
