### PR TITLE
Adds cinematic verb

### PR DESCRIPTION
**Pull request by Regen1**
This will add the cinematic verb to the Event panel, will work like anormal nuke / AI override, meaning it will kill everyone (ending theround)

### CODE REVIEW

**Comment by tigercat2000** [comment]
This is really intended to be more of a debug thing than an admin tool, it's buggy as all hell.

**Comment by Regen1** [comment]
It does kill everyone on station, so it should be used to end the round anyways, but what kinds of bugs are we talking?

**Comment by tigercat2000** [comment]
Last I checked, a couple of the cinematics did not work.

**Comment by Regen1** [comment]
I checked them all locally, worked for me

**Comment by Fox-McCloud** [comment]
I've used them multiple times.

That said, this may be better to lock behind a debug verb, to be honest, just to cut down on the "oops"es.

**Comment by Regen1** [comment]
Ready for merge @Fox-McCloud @TheDZD @Markolie

**Pull request merged**
