### PR TITLE
Removes the Radiation Laser

### PR DESCRIPTION
**Pull request by Inadvizable**
## What Does This PR Do

The medical-specific traitor radiation laser item, that you never heard about aside from people joking about it, is now gone from the game.

## Why It's Good For The Game

This easily is a contender for the title of single most useless item in the game currently. Behind an awful UI that explains nothing of the item's functions - only code comments do by the way, it's nowhere else - hides what is effectively a bad sleepy pen. The item works as follows: after "analyzing" someone with it, it is meant to apply radiation to the target depending on the intensity and wavelength settings, and after a delay, depending on the settings, put the target to sleep - not for particularly long at all. It goes on a cooldown that depends on the settings aswell. 

This is not a good item. As far as I can tell the radiation part does not even seem to work after radiation changes, and with how the new system works, the amount of rads it'd have to give to someone to be threatening would be both immediately obvious, which destroys the stealth aspect of the item, and... would put the user themself in danger. Also, while it is disguised as a health analyzer, examining it betrays its nature, and it does not actually function as a health analyzer, so the doctor would have to carry two, making it even more obvious. All this item does is get newbies caught... It's the type of item you pretend you didn't see because you feel bad for the person who bought it.

Medical antags already have access to both poison bottles and stimulants in their job-specific item category, and potentially extra items depending on their job. Stimulants are an amazing item, and poison bottles... get too much crap, they are actually pretty okay. The radiation laser's job is better done by the aforementioned sleepy pen, too, which medical personnel get many opportunities to modify and/or refill with whatever they can grab in their own department. And that is a lot of things, from the hacked vendor toxins, to whatever they cook up in chem, as noone is realistically going to question them walking in there... And they might be the chemist to begin with.

## Changelog
:cl:
del: Removed the traitor radiation laser.
/:cl:

### CODE REVIEW

**Comment by Contrabang** [comment]
Emagged Geiger counter is already way better than this, even though even that isnt very good. I agree that this should go

**Comment by Inadvizable** [comment]
> Emagged Geiger counter is already way better than this, even though even that isnt very good. I agree that this should go

I can imagine myself using emagged geiger counters for a hijack at least. I can't for the life of me come up with an excuse to ever use the rad laser.

**Comment by matttheficus** [comment]
The only time I've ever seen this are surplus crates and even then theyre never actually used.

**Comment by Inadvizable** [comment]
> The only time I've ever seen this are surplus crates and even then theyre never actually used.

Surplus buff. My plan all along. This is the "gay agenda" they told you about.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
