### PR TITLE
Donator Fluff Item - Plapatin drone Sprite

### PR DESCRIPTION
**Pull request by The-Driker**
**Donator - Plapatin 
**Byond Key - plapatin**
Fluff Item Type – Drone Skin**

I present to you the Salt Drone! All of the complex circuitry that goes into your standard maintenance drone, now drowning in a large salt shaker. 
ezgif com-gif-maker Salt is a way of life! ezgif com-gif-maker

sprite work salt

### CODE REVIEW

**Comment by Aurorablade** [comment]
...Okay as funny as it is. I have to put my own foot down here on this. Just no.

**Comment by Aurorablade** [comment]
To also elaborate, Drones are a ghost role that has to be re spawned more then once more then often. The person who wants this needs to go either PAI or Borg with it. REGARDLESS STILL, Just no. This is too memery for its own good.

**Comment by LightFire53** [comment]
Fethas echos my opinion here. Plus it is significantly larger than the normal sprite, from what I can tell, where maintenance drones are supposed to be small and unnoticed.

**Comment by taukausanake** [comment]
Man, no one likes fun anymore here. (insert lowRP/highRP complaining)

That being said I can't agree with the sprite. It needs to be something not in the way, ignore-able. Drones aren't supposed to stand out. Even more than that it doesn't look salty enough for my tastes. I need to see some sense of grains inside that shaker.

Yeah, @The-Driker it would be best to close this yourself to deny the pleasure to any of the maintainers. It's just not going to go through. Try some other sprite

**Comment by The-Driker** [comment]
@taukausanake 
Yeah, I'm just waiting for the person that asked me to make it to say something, or decide if there was another idea he wanted me to try.

**Comment by Spartan6** [comment]
Ya kept pushing the boundaries, I’ll give you that, but now the boundaries have fallen off a cliff.

It’s too noticeable for a role you’re not meant to even notice.

**Comment by Aurorablade** [comment]
"it would be best to close this yourself to deny the pleasure to any of the maintainers" the tone of that may be coming off in a way you did not intend. And fluff item acceptance goes into the realm of headmins.

**Comment by Plapatin** [comment]
ok well shit
@TullyBurnalot opinions, please?

**Comment by Allfd** [comment]
Yeah, this is getting a bit farther into the meme end of the spectrum then is comfortable for a medium RP server.

**Comment by Ty-Omaha** [comment]
If the salt shaker was just removed _(and added a bit of a top to it)_ it'd look pretty cool imo

**Pull request closed without merging**
