### PR TITLE
Simple Animal Loot Refactor

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Refactors simple animal's loot drops on death to be based on a loot list rather than put in every `death` proc. This comes from TG.

changes:
- Swarmers drop an artificial bluespace crystal
- Orion trail guards drop an energy shield+C20R on death
- Reviving simple animals with strange reagent will prevent them from dropping any further loot (lazarus injectors will still allow them to drop further loot) @FreeStylaLT 

:cl: Fox McCloud
tweak: swarmers will drop an artificial bluespace crystal on death
tweak: Orion Trail guards now drop an energy shield and C20R on death
tweak: Reviving simple animals with strange reagent will prevent them from dropping any further loot
/:cl:

### CODE REVIEW

**Comment by QuinnAggeler** [comment]
What's the problem with syndicate mobs dropping loot, though? They're very rare (IIRC there's only two gateway misisons with them, and they're nowhere on the normal z-levels), and using their own weapons against them is the only chance that people who wind up in those missions usually have of getting back to the gateway

**Comment by Fox-McCloud** [comment]
To help cut down on free loot in away missions, for one--especially considering players cheese syndicate mobs to kill themselves a good portion of the time.

Consistency is another. Syndicate Operatives have an explosion implant in them--it would be fairly logical for their foot soldiers to have one too.

**Comment by QuinnAggeler** [comment]
How about make it chance based? That would help serve both ends. Like, a 50/50 to gib or to drop their gear. If they don't drop anything ever, the first person to go through and find it's Wild West on the other side is pretty much screwed.

**Comment by Gummin** [comment]
Lazarus Injector + Syndimob
Repeat for infinite Syndicate gear.
^no

**Comment by QuinnAggeler** [comment]
That's not how syndiemobs work at all. When they die, they become a dead human, and thus are not able to be lazarus'd. The only way you can revive a dead syndiemob is if an admin puts someone's ghost into it, and then you either clone it (since they become skeletons instantly) or the admin then rejuvenates it

**Comment by ScratKnapp** [comment]
:-1: 

Since the only weapons given in the wildwest mission are really a 10mm pistol and some ammo (and jack shit in the cult maze), you pretty much rely entirely on the ammo dropped from the dead syndies, and if this were to be removed, so would any way of being able to stand a chance (unless you drag a cardboard box along and do the cheap method).

**Comment by lolzyking** [comment]
this doesn't fix wild west cheese
 it encourages it

**Comment by Spacemanspark** [comment]
:-1: for the reasons listed above.

**Comment by KasparoVy** [comment]
Thanks for keepin' it real homies

**Comment by Fox-McCloud** [comment]
syndicakes drop loot again

**Pull request merged**
