### PR TITLE
Fixes missing APC in CMO's office and server room, fixes misplaced scrubber in brigbay

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Do the APC refactor they said, it won't be so hard they said. There won't be cats hiding cables they guaranteed.
Before (currently): img

After: img

🆑 FreeStylaLT
fix: Fixed missing APC in CMO's office, oops
fix: Fixed misplaced scrubber in brigbay
fix: Fixed missing APC in server room
/🆑

### CODE REVIEW

**Comment by Markolie** [comment]
If you're up for it, https://github.com/ParadiseSS13/Paradise/issues/5590 is also an easy mapfix

**Comment by FreeStylaLT** [comment]
Done, also fixes #5590

**Comment by Markolie** [comment]
Awesome, thanks.

**Comment by Markolie** [comment]
There's also an APC missing in the right side of the server room, if you're down for fixing that as well :P.

**Comment by FreeStylaLT** [comment]
OH MY GOOOOOOOOOO

**Comment by FreeStylaLT** [comment]
..fixes that, too. I am starting to regret doing that refactor, the station has too many APCs.

**Comment by Markolie** [comment]
Yay!

**Comment by mrturkeytoe** [comment]
I think interrogation also lost a APC.

**Comment by Anticept** [comment]
@Fox-McCloud interrogation and/or interrogation hallway is missing an apc.

**Comment by Markolie** [comment]
Permabrig toilet needs its APC re-added too.

**Comment by FreeStylaLT** [comment]
:joy: :gun:

**Pull request merged**
