### PR TITLE
Fastest linda

### PR DESCRIPTION
**Pull request by Allfd**
This PR modifies the atmospherics controller to control both pipe networks and atmospheric machines in addition to its current role of handling LINDA. The amount of energy released is increased which when combined with a decrease in the scheduled interval results in a speed increase of LINDA of approximately 5x.
🆑Fox McCloud and Alffd
add: Merge all LINDA and atmos machine functions into the air controller subprocess.
add: Air alarms in scrubbing mode will shut off when alarm enters danger state. If this occurs simultaneously with a max2 temperature alarm panic siphon will automatically activate.
add: High air pressure differences will throw objects and knock over station species.
add: Add magpulse to syndicate and death squad borgs.
tweak: Change all volume pumps to regular pumps in atmospherics to accommodate new LINDA speeds.
tweak: Change LINDA interval from 2 seconds to 400 milliseconds.
tweak: Removed unused control from flamethrower.
tweak: Set flamethrower release equal to fuel used.
tweak: Increased Reinforced Wall HP from 200 to 600.
tweak: Buff aliens against space wind.
tweak: Buff Terror Spiders against space wind.
tweak: Buff some blobmobs aginst space wind.
tweak: Frost requires heat to remove.
/🆑

### CODE REVIEW

**Comment by MarcellusPye** [comment]
Fastmos is back!

**Comment by taukausanake** [comment]
Does this have any similarities with #7213?

**Comment by Allfd** [comment]
@taukausanake It is exactly the same as #7213, except 13 commits are now 1 and it does not have the massive amount of comments from months of changes.

**Comment by Regen1** [comment]
Ahem, I'd like to report one Allfd and Fox, it's obvious at this point that they dabble in black magic.

**Comment by Jovaniph** [comment]
> add: Air alarms in scrubbing mode will shut off when alarm enters danger state. If this occurs simultaneously 

This is so annoying when you are trying to refill a room back up again. Because of fastmos, there is no reason to fill the room with "refill" mode on. Just set it to scrubbing and it fills up by the time you return to your work place. If it possible to fix refill mode or fix the scrubbing from continuously shutting down, that would be great.

**Comment by alexkar598** [comment]
I'm sure you broke the cycle mode as it dose : empty air > set to scrubbing mode > disables air alarm because pressure is too low

The air alarm scrubbing change should be kept to an other pr, fastmos is big enough as is

**Comment by Crazylemon64** [comment]
Fastmos is getting merged to allow for a longer, more consistent testing period. This way we can make sure all the crashes are ironed out, and see how it works out in practice during regular gameplay.

**Comment by taukausanake** [comment]
Is this actually happening?

**Comment by KasparoVy** [comment]
Congrats!

**Pull request merged**
