### PR TITLE
Replaces duplicate labor shuttle console by mining console

### LINKED ISSUE #8813: There are 2 Labour camp shuttle consoles on the bridge
**Problem Description**:
What is the problem?

There are 2 Labour camp shuttle consoles on the bridge

**What did you expect to happen**: 
Why do you think this is a bug?

There should be 1, engineering shuttle, 1 mining shuttle and 1 labour camp shuttle console on the bridge.

**What happened instead**:
How is what happened different from what you expected?

There are 2 labour camp shuttle consoles on the bridge.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

The bridge cannot control the mining shuttle from the bridge.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Change 1 labour camp shuttle to Mining camp shuttle console.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

### PR DESCRIPTION
**Pull request by datlo**
Fixes #8813

There are two labor shuttle consoles on the bridge, this replaces one of them by a mining shuttle console.

consolebefore
consoleafter

🆑
fix: Replaced duplicate labor shuttle console on the bridge by a mining shuttle console.
/🆑

### CODE REVIEW

**Comment by Denthamos** [comment]
Labor camp was removed, so that console should be removed entirely.

**Comment by datlo** [comment]
AFAIK the labor camp removal was not merged yet and the labor camp is still functional, even if never used.
In any case, I think removing the labor shuttle consoles entirely should be left to the PR removing the labor camp itself.

**Comment by datlo** [comment]
Added pics of changed console; the other labor console is next to the comms console near the center of the bridge

**Comment by Crazylemon64** [comment]
I'm noticing a lot of other changed tiles - what's up with those?

**Comment by datlo** [comment]
AFAIK none of those tiles are actually changed despite the file difference. Those differences come when I edit the map file with Dream Maker and are just re-ordered lines. It's possible I fucked up, though, it's my first map edit. If you know how to do it more cleanly, I'd appreciate the advice

**Comment by taukausanake** [comment]
You have to use the map merge tool. That might be the issue here. It's okay, I barely know how to use it myself, the only time being when all I had to do was change a turf in the text rather than the map. It never did get merged...

**Comment by datlo** [comment]
Used the mapmerge tool to cut all the extraneous file changes. Worked great!

This should be ready for merging.

**Comment by Crazylemon64** [comment]
LGTM

**Pull request merged**
