### PR TITLE
Swarmer cryodorm fix

### LINKED ISSUE #3243: Cryodorms may be eaten by swarmers
It's old news. It's not a big deal if only one or two pods are missing, especially on lowpop rounds, but it's probably safer to prevent swarmers from deconstructing that.

### PR DESCRIPTION
**Pull request by Deanthelis**
Fixes #3243.

### CODE REVIEW

**Comment by tigercat2000** [comment]
deaaaaaaaaaaaan you made the merge stuff again

**Comment by Deanthelis** [comment]
I am going to kill a small child.

**Comment by Regen1** [comment]
Use git rebase -i upstream/master to fix it

Might have to do git push -f to make it work as well

**Comment by Fox-McCloud** [comment]
merge conflicts

**Pull request closed without merging**
