### PR TITLE
Updates Meta's z5, replaces current z5 with Meta's

### PR DESCRIPTION
**Pull request by FreeStylaLT**
It seems like _this_ was the intended change the Maints wanted me to make, but I dun goofed up.

Some minor changes:
img

- Removed Pod dock
- Ported over Cyb's initial outpost
- Other minor updates to keep it in-line
- **Secondary outpost now has two medkits, same as it used to be on Meta's z-level**
- Updated the abandoned xeno base to Cyb's standard

🆑 FreeStylaLT
tweak: replaces generic Mining z-level with Meta's
/🆑

### CODE REVIEW

**Comment by Kyep** [comment]
Does this have as many mining hardsuits as box's z5 does?

**Comment by SamHPurp** [comment]
Please tell me this is closed because this was in error. We should **not** be using Meta's original asteroid. It is awful and out of date to the n'th degree.

**Comment by FreeStylaLT** [comment]
Nope! This got closed as I wanted to properly update it to Cyb-established standards first.

**Comment by Fox-McCloud** [comment]
This was on us; we should have noticed in the initial PR. OOPS.

**Pull request merged**
