### PR TITLE
Final major 516 fixes

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
Ports
https://github.com/VOREStation/VOREStation/pull/16713 and
https://github.com/VOREStation/VOREStation/pull/16734

## Why It's Good For The Game
Fixes 516 chat flicker, considering its literally about to come out of alpha

## Testing
spammed chat, no flicker.
saved chat log, no crash.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl: ShadowLarkens, S34N
fix: Fixed chat flicker for 516 clients
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Sean porting vorecode 2024

**Comment by S34NW** [comment]
> Sean porting vorecode 2024

delwedd

**Comment by Burzah** [comment]
> Sean porting vorecode 2024

The fix we needed.

**Review by Burzah — APPROVED** [review]
Tested on both 515 and 516 clients without issues.
Looks good to me.

**Pull request merged**
