### PR TITLE
[DNM] [WIP] - Additional Species Food

### PR DESCRIPTION
**Pull request by Kiyahitayika**
## What Does This PR Do
This is a place-holder PR for a Work-in-Progress on Species Food.

It's in progress. Teslium is _**not**_ going to be the final product. I just wanted this up on Github so people will stop asking me to put it on Github.

Planned Changes:
- **Skrell Sushi (sushi)**
- **Phish and Microchips (uses deepfryer)** - To be Removed - doesn't make sense
- Candied Kidan (uses candy maker)
- Unathi-on-a-Stick

## Upcoming Changes

- **Skrell Meat** will be removed. It was an a step I used in learning how sushi recipes functioned. I'm going to just replace that with a Skrell limb.
- **Phish & Microchips** will be removed

## Why It's Good For The Game
Is it good for the game? Wait...
Oh! Yeah!
It adds a ... variety of new foods for the chef and other culinary entrepreneurs. It teaches the importance of being resourceful and considerate of what you offer to your fellow space travelers. Consider becoming a banquet for your friends post-death today! Please sign [here].

(same reason as https://github.com/ParadiseSS13/Paradise/pull/13114)

## Images of changes
Look! Video! Happy post-death clients!
https://imgur.com/a/U9GZju1

## Credits
Idea credits go to various people.
Spriting credit goes to Chikitita! 

## Changelog
:cl:
add: Sprites (skrell sushi, skrell meat, phish and microchips), Food types, Attack_By for sharp object on Skrell limbs to create Skrell meat.
wip: Working on other foods
/:cl:

### CODE REVIEW

**Comment by PacifistDalek** [comment]
Ping me on discord when this is merged and I'll help add them to the wiki!

**Comment by Kiyahitayika** [comment]
I'm not a fan of Skrell essentially having **two** food items come out of this. At first, I thought it was necessary to make the sushi. Now I'm realizing I was missing the obvious. 

Skrell Meat is unnecessary. That's going to be removed. Instead, we're just going to use a Skrell limb in the `sushi_skrell` recipe.

**Comment by Fox-McCloud** [comment]
Kentucky Fried Vox has a fairly distinct quality about it in that it was an emergent joke that circulated for *years*---it wasn't really forced and had a fairly direct connection (ie: horses and glue).

These feel a bit forced.

**Comment by Kiyahitayika** [comment]
> Kentucky Fried Vox has a fairly distinct quality about it in that it was an emergent joke that circulated for _years_---it wasn't really forced and had a fairly direct connection (ie: horses and glue).
> 
> These feel a bit forced.

The person who created KFV, @Ty-Omaha, seems to approved of the concept of adding additional race-based foods in a comment on https://github.com/ParadiseSS13/Paradise/pull/14155
image

Here's a direct comment from Ty-Omaha on the same PR:
image

I had a conversation on Discord last night where people seemed on-board with the concept if each species were treated the same (i.e. unspecific limbs being used for the food items). We talked about how requiring a torso for slimes would essentially encourage griefing and gibbing for a "funny food" and that's not fun. 

@Fox-McCloud At the same time, I definitely appreciate your input. Right now, I agree. These feel a bit forced. I want to hear more from more people. I want to have people say, "these things are too bland" "there's too much of the same" "why is it all food?" "why why why" "I don't like this" "I'd rather have <that> instead" "this is a bad idea". Maybe this WIP won't happen. Maybe we'll decide that it's too much - that KFV is enough and we'll leave it at that. I'm eager to hear from folks and I'm not going to push through on something that makes people unhappy.

**Comment by Kiyahitayika** [comment]
> "Right now, I agree. These feel a bit forced."
What I mean is more that it feels rough. The idea didn't come up over night and didn't wasn't the product of one person's work. When we saw the responses on the PR to remove KFV, we thought, "Oh, huh. Maybe we should actually try it." The concepts for the food items came from a group of people working together (as you can see, we used ideas from @Carthusia and @VeteranKyl ), the sprites came from Heather, and I worked on the coding. I floated the concepts by several people, including a Maint to feel things out. 

These comments also come from the KFV PR (https://github.com/ParadiseSS13/Paradise/pull/13114):
image
image

These comments come from the Paradise Discord server:

image
image
image
image

**Comment by Kiyahitayika** [comment]
That said, my name is "Salt" on the Discord for a reason: 
image

**Review by variableundefined — COMMENTED** [review]
Echoing Fox here, I am unsure on adding more species food. This feel forced to me too.

**Comment by Kiyahitayika** [comment]
> Echoing Fox here, I am unsure on adding more species food. This feel forced to me too.

I started working this because people were sharing ideas and sprites of species food after it was seemingly encouraged on other PRs to add more species food. I've seen people asking for more species food in the Discord. I've seen some people saying "no species food at all", but not "no more species food specifically". I apologize for my lackadaisical language in the "Why It's Good for the Game" section. Again, as I said, it's a work-in-progress and I'm doing the coding. There are other people involved in this as well.

## Narrow Scope of PR
@Fox-McCloud @variableundefined 
I think redefining this project from "species food for all races" too "additional species food" would be better.
\-
Skrell Sushi is something that makes sense, many people compare them to being fish-like. I want to remove the intermediary "Skrell Meat" step and that will be simple. 
\-
Candied Kida/Candied Kidan - candied/chocolate-covered insects are foods that exist in real life and would also exist in the real of SS13.
\-
Unathi-on-a-Stick - I think Unathi already have **clothing** items.  That said, this is a shoutout to the Fallout series with Iguana-on-a-Stick. We've been running this past the "Unathi Gang" on Paradise and they seem keen on it.
\-
Slime People -When https://github.com/ParadiseSS13/Paradise/pull/14665 goes through, maybe we could add a **drink** like a Jello Shot for Slime Jelly.

## Remove Aspects
**I think I agree with you and Fox that it does feel a bit forced in places. There's _reaching_ here for foods.** 
\-
Drask Snowcone - It's sprited, but how does that make sense. I guess they're pretty chill (oh wow I'm soooo clever). 
\-
Tajaran Lasagna, that's memery. It took me a while to figure out what people meant by this one. Apparently...Garfield? Yeah, this feels one is forced to me, too.
\-
Vulpkanin Kibble - I think this is a bit meme-ish, but what are the standards? It's hard to know with KFV -- and this isn't a dig! Please don't take this the wrong way. We're trying to feel out what's acceptable, not say "Well, we have KFV, so this OTHER thing should therefore be justified!"
\-
Phish & Microchips - _oof_ I love that sprite. That said, it doesn't make a lot of sense. You can't digest metal. You can eat it sure, but digest it? Heh...good luck trying. It shouldn't be a food.
\-
Plasmamarrow Chocolates - I don't get this one.
\-
Soilent Grey - I would want something more unique since we already have Soylent Green

**Comment by variableundefined** [comment]
Two maints objection, no one in favour. Closing.

**Comment by Kiyahitayika** [comment]
> Two maints objection, no one in favour. Closing.

Addressed both the maints' feedback, did not receive responses. Elaborate on your objections, please. Closing PRs based on this is not encouraging contributors to continue coding and absolutely turns me off from coding projects for Spriters.

Based on your feedback, I will go tell people that Paradise is only interested in memes and LRP and _not_ the hard work of several members of its playerbase.

**Comment by Kiyahitayika** [comment]
> Two maints objection, no one in favour. Closing.

Despite my changing of the PR in response to the objections and the people in favor of the PR.

**Pull request closed without merging**
