### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Markolie**
Changes:
1) Adds a missing wire to the R&D server room so the APC powers.
2) Fixes the cult sacrifice objective so it actually works.
3) Cult Survive objective now scales with the population (one additional escapee per 10 players), base of 4).
4) Disabling streaming will now stop the active music.
5) Updates the revenant role candidacy so it's not capitalized (for consistency) and fourteen days minimum age (also for consistency).

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Looks great; maybe cutlists will finally have a challenge when they have a crew of 70+

**Comment by Robertha89** [comment]
can you fix the bug where they don't get the SUMMON NAR'SIE objective too? I mean, they are supposed to get it, irregardless of other objectives, or they should, i mean, what is the point if you don't?

**Comment by Fox-McCloud** [comment]
@Robertha89 

They're not meant to get it every time; sometimes they just have to have people "live on" and other times they have to summon Nar-Sie.

**Comment by Taaketa** [comment]
I know it's late to add this to the branch. But the prisoner holding cell APC has a disconnected wire to it as well. Could someone fix tghat?

**Pull request merged**
