### PR TITLE
Refactors barsigns and allows them to be constructed/deconstructed.

### PR DESCRIPTION
**Pull request by Divulf**
## What Does This PR Do
Refactors barsigns into a machinery subtype and allows them to be constructed/deconstructed, as well as turned on/off.  The frame can be made with 4 sheets of metal in-hand and the electronics can be obtained from the autolathe or in the bar starter kit.  Also adds support for, but not sprites of, alternative emagged barsigns.

## Why It's Good For The Game
Further bar customization options.

## Images of changes
https://github.com/ParadiseSS13/Paradise/assets/134484326/85799061-503c-41ea-af2f-39c247694b13

The sprites could be better, but I am not a spriter.

## Testing
I did.

## Changelog
:cl:
tweak: Barsigns are now able to be constructed and deconstructed.  Use 4 metal in-hand to make a frame that can be attached to a wall.  The required electronics are found in autolathes and bar starter kits.
/:cl:

### CODE REVIEW

**Comment by Henri215** [comment]
It would fix this issue right? https://github.com/ParadiseSS13/Paradise/issues/14884

**Review by Henri215 — COMMENTED** [review]
image

items.dmi is not the best place for the barsign frame, move it to barsign.dmi or another place you can find that fits it.

**Comment by McRamon** [comment]
sprites are very underwhelming, you can contact me on discord for help and generally consult on spriting channel

**Comment by Divulf** [comment]
closing due to further improvements requiring #24252 to be merged

**Pull request closed without merging**
