### PR TITLE
Restores mentor's ability to PM people

### PR DESCRIPTION
**Pull request by SteelSlayer**
## What Does This PR Do
Restores mentor's ability to use:
- The "Admin PM mob" verb
- The "Admin PM key" verb
- The "Admin PM name" verb

This was accidentally removed as a result of #14024.

## Changelog
:cl:
fix: Restores mentor's ability to PM people
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Should clarify. Mentors can still reply to tickets but they can't directly bwoink people through admin verbs. I think they *might* still be able to do it through right click though.

**Comment by CornMyCob** [comment]
Right click PM doesn't work either sadly.

**Comment by SteelSlayer** [comment]
Yes this affects verbs only (which includes the right click one). Updated description to be more clear.

**Comment by AffectedArc07** [comment]
Travis is currently not existing

**Comment by AffectedArc07** [comment]
Lets try this

**Pull request merged**
