### PR TITLE
Updated Corgi pAI Sprite (take 2)

### PR DESCRIPTION
**Pull request by Aurorablade**
Now that i fixed it to not upload some things i did to make it compile cuase git was being silly with me...

What it does: Updates the Corgi pAI sprite to a modified version of EN in the pAI color scheme. I am not the best spriter nor am i utterly fermillier with byond code so i hope i did everything right (tried to test..fumbled with it..so heres hoping)

I would not be offended at all if one of the better spriters tweeked it...nope not at all...>.>

Also i did keep the old corgi sprite in the file as it seemed better then deleting and never know when you need a Green Mecha Corgi.

### CODE REVIEW

**Comment by TheDZD** [comment]
Would it be possible to get screenshots of the new sprites?

**Comment by Aurorablade** [comment]
My Apologies there!  
borgipai

borgiani
borgibutt
borgiside
borgipairest  The 'rest' state, just one in the animation set with the 'light' dimmed. The dead stat is a copy over of the current corgi pai sprites dead state (and renamed properly)
I did just however notice a one pixel anomly near the belly on the side animation that i MAY want to fix.

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by ZomgPonies** [comment]
Tell me when it's ready for merge.

**Comment by Aurorablade** [comment]
Well if you are fine with how it lookes its okay to merge, I think i got the pixel issue straightend out and i assume my logic with the code is sound. So if it looks okay with you guys hit it! *is hit with a toolbox in the head*
Aurorablade's head explodes in a shower of gore!

**Pull request merged**
