### PR TITLE
Refines the Farragus Security/Command Asteroid

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
This PR remaps the Security/Command asteroid on Farragus to achieve several outcomes:

### Improved Maintenance Tunnels
* The connectivity of the maintenance tunnels has been improved to avoid one-way tunnels. Interconnectivity is strongest in the command and command/security section.

* The tunnels have been decorated, new rooms have been added, and overall distinctiveness has improved. 2 new airlocks allow traversal to and from space without having to travel to the space bridges.

* Atmospheric checkpoints have been added with air alarms to control the ventilation in the tunnels.

* A redundant SMES room that just gave power to the locker room area has been removed.

* The escape pod area has been given a big improvement. In addition to looking great, it also doesn't get spaced when the shuttle leaves.

### New and Improved Permabrig
Farragus had a truly depressing permabrig. Whilst the dismal state of it may have been fully intentional, the gimmick of it being a hole wears off pretty fast. The permabrig has been equipped with amenities that it lacks compared to other stations that will make it better for both the prisoners and security, including:

* Decent Lighting
* An IPC toilet that isn't in full view of everyone.
* The pet lizard "Greentext" now appears in this permabrig.
* A kitchen (on par with the one found on Cyberiad).
* A well-lit, properly equipped garden with greenery.
* A bigger selection of recreational outlets.
* An actual dedicated entry airlock, not serving double-duty as isolation.
* An emergency nanomed vendor.
* A full laundry room.
* A place you can go to escape from perma via space.
* A bucket and mop.

### New and Improved Rest-of-the-Brig
The rest of the brig has also gotten some love:
* There is now a front desk that can be manned to allow officers to interact with the public better and exchange items using the desk shutter. Includes a desk bell for getting attention.
* Processing/evidence is now adjacent to the cell block to make turnaround times for non-perma inmates faster.
* The warden office/armoury is now adjacent to where the gamma armoury will land. The armoury is now stocked with an EOD suit and 2 security biosuits. It is harder to breach from maintenance, but it can be breached from space now.
* The break room is now in the middle, where all the big rocks used to be, and is equipped with vendors for an enhanced break room experience.
* The equipment room now features an additional drip vendor and two items of medical supplies.
* The firing range has been expanded to accommodate the full set of nuclear training gear.
* The courtroom has been redecorated and given a proper holding cell for the accused (which will be used exactly once in the next 3 years).
* The Head of Security now has a bedroom and his pet spider (along with a spider bed to keep the spider in).
* A number of cigarettes and ashtrays have been added.
* Execution has been improved with the addition of several execution methods. The random bat room was removed.
* The locations that the gamma armoury and labour shuttle will dock have now been marked with beacons.
* There is now a bathroom for security to use.

### Hallways/Command Plaza
* The bridge/HOP line has been shifted up and a plaza has been added. In addition to providing a space to meet, greet, and roleplay, a large statue of the captain watches over the crew from his spot of greenery.

* A camera blindspot was removed from the Command/Cargo/AI bridge.

* A pet store has been added to the plaza area west section.

* The Vault has now been given a space gap on its sides, consistently with other stations.

* Due to the Command atmos checkpoint being moved into command maintenance, the left command-engineering space bridge airlock access is now accessible to all the crew.

### Other Changes
* The NT Rep office has been slightly expanded in lieu of a pay rise.

* A bunch of random items have been moved to the former APC room of the bridge, this is now the bridge storeroom.

* The disposals loop got slightly simplified.

* The IAA got their desk moved a bit. Paperwork now has a bed.

* All eligible role workplaces now have action figures and novelty mugs.

* The Dorm Toilets and Dorms are now separate areas from the Locker Room.

* I think I managed to get rid of all the wallbump conflicts on the asteroid.

## Why It's Good For The Game
Massive improvements to maintenance make it more usable for travel, more interesting to explore.

Permabrig doesn't suck so much, people won't want to riot as much because they have other things they can do. Escaping from space no longer sucks.

Brig layout feels nicer. You can now wash the blood off your hands in the new bathroom.

## Images of changes
Full map
image
Permabrig focus
image
Left brig
image
Right brig
image
HOS office and bedroom
image
IAA office
image
Left brig maintenance
image
Upper right brig maintenance
image
Brig/Bridge maint transition
image
Upper Bridge Maint
image
Lower Bridge maint
image
Vault
image
Bridge plaza and pet shop
image
NT Rep office
image
Bridge and Store Room
image

## Testing
- [x] Ensured camera coverage is correct.
- [x] Checked lighting.
- [x] Ensured door access is correct.
- [x] Verified that the new perimeter of the asteroid is cold ancient rock.

<hr>

### Declaration
image
image

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
  
  
  <hr>

## Changelog

:cl:
tweak: The Farragus command/security asteroid has been remapped. The brig has seen the heaviest amount of remapping, along with the maintenance tunnels.
add: 2 security biosuits, 1 EOD suit have been added to the armoury.
add: Pet shop added to new command plaza.
add: Extra camera coverage in command/cargo/AI bridge to fill in a blind spot.
/:cl:

### CODE REVIEW

**Review by Burzah — COMMENTED** [review]
Quick first pass walk-through. It looks pretty good so far! I just have a few comments.

There are two holopads in processing.
image

This kind of looks a little odd here with how the pipes are, just to have the one manifold hidden while everything else is exposed.
dreamseeker_Gf2CqqobTe

This one is more of a personal opinion, but now that this looks a lot nicer and has some use, I think putting some basic floor tiling in here would be good.
dreamseeker_3Td7b3kKeP

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
I'm very happy with the maints areas here especially, I don't think we've ever had abandoned brig/bridges in maints before, and it's so obvious in retrospect. One thing I'd ask is to add a few vendors in those areas of maints, it's always nice to have one or two vendors that people forget about completely for brand intelligence.

Other small changes:

Maint loot spawners can spawn anywhere from 2-4 items, so having three of them will almost guarantee a bunch will pile up on top of the shelf instead:

2024_11_23__10_59_16__paradise dme  cerestation dmm  - StrongDMM

2024_11_23__10_59_11__Paradise Station 13

These airlocks have engineering/general access, not engineering/maintenance, and all the other entrances to the waste belt have the latter:

2024_11_23__10_58_31__paradise dme  cerestation dmm  - StrongDMM

I kind of liked the glass T-junction here in the hall, now the glass inserts kind of look like mismatched road paint markers:

2024_11_23__10_55_54__paradise dme  cerestation dmm  - StrongDMM

This SSU is missing a decal under it:

2024_11_23__10_28_51__paradise dme  cerestation dmm  - StrongDMM

This manifold is hidden:

2024_11_23__10_19_26__Paradise Station 13

The decal transition here between these two areas is a little jarring:

2024_11_23__10_18_44__Paradise Station 13

The KAD here is placed directly on the wall:

2024_11_23__10_16_13__Paradise Station 13

Only one of these windows has a firelock under it:

2024_11_23__10_08_00__paradise dme  cerestation dmm  - StrongDMM

Could you move one of these bulbs a bit further north to even out the lighting coverage?

2024_11_23__10_03_43__Paradise Station 13

**Comment by Fordoxia** [comment]
> Other small changes:
>`snip`
I've gone over Burzah's and your points and fixed those. About to throw in a small handful of maintenance vendors as well.

**Comment by Fordoxia** [comment]
Added a few vendors:
Sustenance vendor in the old brig:
image

Coffee machine in the soda bar:
image

(paid) vendomat in the bridge maint engineering section:
image

In addition, the old detective office and the service-sec bridge maint airlock section already had a pair of vendors.

**Review by Burzah — APPROVED** [review]
Looks good to me. Nice work!
It is nice to see Farragus getting more love.

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
Maints camera:

2024_11_30__10_04_43__paradise dme  cerestation dmm  - StrongDMM

Could you push these pickaxes so they're more centered on the rack?

2024_11_30__10_07_36__paradise dme  cerestation dmm  - StrongDMM

This QM access shouldn't be necessary

2024_11_30__10_10_58__paradise dme  cerestation dmm  - StrongDMM

Missing floor tile?

2024_11_30__10_12_33__paradise dme  cerestation dmm  - StrongDMM

One of the processing cameras has the word "Prisoner" in its tag, the other doesn't

2024_11_30__10_19_37__paradise dme  cerestation dmm  - StrongDMM
2024_11_30__10_19_48__paradise dme  cerestation dmm  - StrongDMM

"West" is in all caps on this camera tag

2024_11_30__10_20_42__paradise dme  cerestation dmm  - StrongDMM

There's only one labor camp camera but it's tagged "North"

2024_11_30__10_22_08__paradise dme  cerestation dmm  - StrongDMM

Courtroom camera has a trailing space in its tag name

2024_11_30__10_22_24__paradise dme  cerestation dmm  - StrongDMM

**Comment by Fordoxia** [comment]
> Maints camera
> Could you push these pickaxes so they're more centered on the rack?
> This QM access shouldn't be necessary
> Missing floor tile?
> One of the processing cameras has the word "Prisoner" in its tag, the other doesn't
> "West" is in all caps on this camera tag
> There's only one labor camp camera but it's tagged "North"
> Courtroom camera has a trailing space in its tag name

All issues addressed.

**Review by warriorstar-orion — APPROVED** [review]
LGTM

**Pull request merged**
