### PR TITLE
Gives some armor to Combat Gloves and Jackboots

### PR DESCRIPTION
**Pull request by AzuleUtama**
**What does this PR do:**
It was brought up in coder chat that neither of these items have any armor values on them, despite the "combat" nature of both of them.

The gloves state in their description they are "impact resistant", yet won't protect from any kind of damage except shocks from doors. I've given them a small amount of resistance to the 3 basic damage types (melee, bullet, laser) since they are usually used by traitors and nukies who can run into all of these.

The jackboots have been given a small amount of melee resistance to match the armor value of the security jumpsuit. This is to give sec officers a small incentive to keep the boots on since there's no reason to wear them over anything else as it stands.

**Changelog:**
:cl:
balance: Combat Gloves and Security Jackboots now have some basic protection from damage.
/:cl:

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
😱 5 Merge commits

Either case, I'd rather not get in the habit of armoring gloves/shoes, with particular exception.

I'd much rather the description be changed if it's really that much of a problem.

**Comment by variableundefined** [comment]
Agreed, I'd support a description change.

**Comment by JohnBigless** [comment]
🤔

**Comment by variableundefined** [comment]
Closing for reasons stated above

**Pull request closed without merging**
