### PR TITLE
Clowns are too sweet to understand death

### PR DESCRIPTION
**Pull request by S34NW**
## What Does This PR Do
This PR makes dead people appear to clowns as if they are sleeping. (Yes, this applies to antag clowns.)
This is a port, credit goes to Ryll/Shaps from TG for the code.

## Why It's Good For The Game
Quite frankly, I was browsing TG PRs and saw this one: https://github.com/tgstation/tgstation/pull/48863
I realised how much we've been missing out. It's time to shelter our clowns from the horrors of space.

### Pardon the obvious death message here, not much can be done about that.

image

## Changelog
:cl:
tweak: Clowns now think dead people are sleeping
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Is this a joke PR?

**Comment by S34NW** [comment]
> 
> 
> Is this a joke PR?

No, although it is quite humorous in nature.

**Comment by AffectedArc07** [comment]
Yeah, No.

**Review by variableundefined — COMMENTED** [review]
Adding an objection to Affected's. Closing.

**Pull request closed without merging**
