### PR TITLE
Plant Age, Weeds, and Pest Tweaks

### PR DESCRIPTION
**Pull request by FalseIncarnate**
Makes plants die when they get old again.
- Plants begin dying once they age past 5 times their TRAIT_MATURATION value.
 - This means a plant with TRAIT_MATURATION 5 will begin dying when it reaches age 26 and higher
- Plant death will occur over time as it loses health each process.
 - Can be slightly deferred with health restoring reagents, but is unavoidable in the long run.

Weed growth in trays has been returned to pre-#980 chances.
- Chance for weedLevel to increase is 6% if no seed planted, 3% otherwise
 - With #980, this was unintentionally dropped to 5% / 1%

Pest growth in trays has received a buff
- Now a 5% chance per process to increase pestLevel by 0.5
 - Previously was 3% chance to increase by 0.1
 - Pre-#980, this was a 3% chance to increase by 1.0

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Gosh damn Baycode and their retarded RNG for "balancing" things.

**Comment by Spacemanspark** [comment]
...You don't need to insult them every time, you know.

**Comment by Fox-McCloud** [comment]
I actually didn't plan on saying anything, but @FalseIncarnate grumped at me and was shocked that I *didn't* leave a comment, so, I felt the need to oblige him =p

**Comment by Spacemanspark** [comment]
I don't think that should mean you insult them.

**Pull request merged**
