### PR TITLE
Adds an Escape Pod to the left side of DeltaStation Maintenance

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
Adds an escape pod to the left side of DeltaStation, since it actually only has 3. This pod is placed by engineering, but isn't accessed through engineering. As a result, this also adjusts a space pod over by arrivals, so we can have 2 north facing pods and 2 east facing pods without having to cause any shuttle flips.

## Why It's Good For The Game
 More ways to escape ~~if you are a filthy antag~~ if you are at the wrong side of the station and command is about to emergency card swipe.

## Images of changes

Old arrivals:
image

New arrivals: 
image

Old maintenance:
image

New maintenance+pod:
image

## Changelog
:cl:
add: Adds an escape pod to DeltaStations Aft Port side maintenance
tweak: Modifies arrivals Fore Starboard escape pod
/:cl:

### CODE REVIEW

**Comment by LightFire53** [comment]
image
This was fixed in my last commit

**Comment by Wojz** [comment]
Is that maintenance mop moved somewhere? Not a big thing but it does help with cleaning stuff when you're trying to build something in maint, box has one of these in medmaints.

**Comment by LightFire53** [comment]
> Is that maintenance mop moved somewhere? Not a big thing but it does help with cleaning stuff when you're trying to build something in maint, box has one of these in medmaints.

Ducky and his friends have returned.

**Review by S34NW — CHANGES_REQUESTED** [review]
Please remove this area of nearstation that has snuck in, same with the arrivals pod 4

image



image

Also, making this awkward setup to accommodate one flip happening per round is a bit excessive. I think you should keep it as is and just let the pod flip.

**Comment by LightFire53** [comment]
> Please remove this area of nearstation that has snuck in, same with the arrivals pod 4
When I was looking at box, it had the weird near space in front of them. I can pull out though

**Review by variableundefined — APPROVED** [review]

**Pull request merged**
