### PR TITLE
Enables AI holograms to move between holopads

### PR DESCRIPTION
**Pull request by Kyep**
Prior to this PR, if an AI using a hologram gets too far away from the holopad, the holopad simply deactivates.

With this PR, if the AI hologram moves too far from the holopad, it still deactivates that pad - but it also looks to automatically transfer the hologram to another pad if one is in range.  Using this, an AI can walk around the station more or less seamlessly as a hologram - so long as they don't go into an area that's outside of the range of *any* holopad. Inspired by: https://github.com/tgstation/tgstation/pull/21720

🆑 Kyep
tweak: AI holograms now transfer between holopads as the AI moves around.
/🆑

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Fucking
Yes please.

**Comment by Dinarzad** [comment]
AI Holo Tour of Cyberiad to greet CC officials.
Pls.

**Comment by Spacemanspark** [comment]
"Greetings, this is the incinerator room. Please jump in."

**Comment by taukausanake** [comment]
So do we have enough holopads around the station to support this? At least with the main halls, might need to map some in so this is used best.
Is there any sort of blinking out and back into existence when traveling between pads?

**Comment by Spacemanspark** [comment]
We have a lot more holopads than most servers.

**Comment by Kyep** [comment]
@taukausanake I was able to zoom from Eng to Sec without issues. 
There is no blinking out when moving between pads.

**Comment by SamHPurp** [comment]
Now this is a good feature, I like it!

**Comment by Spacemanspark** [comment]
Can this be merged?

**Pull request merged**
