### PR TITLE
skittles borg fluff

### PR DESCRIPTION
**Pull request by Aurorablade**
ckey:fullofskittles
fluff type: borg

Engie:

sec:

Janitor:

Medical:

Service:

mining:

syndie:

combat:

Standard for example:
https://puu.sh/ztGil/b3fc4298be.gif

:cl: Fethas
rscadd: Full of skittles borg fluff
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
~~Resomi when~~.

They look like raptors? Be nice for more directions but I guess not being lazy and looking at the dmi wouldn't kill me...

**Comment by Aurorablade** [comment]
Look at the gif linked

**Comment by taukausanake** [comment]
That gif was way too long for me to spend even two seconds on it. But I see the directions. It's nice

**Comment by StreakyHaddock** [comment]
it does look nice, and that... is different enough from a Vox that I don't think you'd confuse it for a real one.

**Comment by Regen1** [comment]
Same issue here, the borgs don't show what job they are, it should be discernible at a glance if you're up against a security borg or an engineering borg, having that trait hidden is an advantage, and should not be a part of something considered "fluff"

**Comment by Aurorablade** [comment]
regens it shows it i just have a front view only thing going...

**Comment by Aurorablade** [comment]
just..let me get a bunch of shots...damn people...

**Comment by taukausanake** [comment]
@Aurorablade or you could just post the raw PNG-ified version of the icons you're adding. A blown up version of it mind so it's not tiny

**Comment by Fullofskittles** [comment]
microbot8181

I don't really know how to show what "job" a borg is besides having them be different colors that are commonly associated with that job type. As far as I could tell from the other custom borg sprites this seemed to be acceptable. I suppose I could alter them further but i'd definitely want suggestions as to what i could do that would make it clear without ruining or drastically changing their design.

**Comment by Aurorablade** [comment]
oh i just updated the OP also

**Comment by Aurorablade** [comment]
the colors should be fine.

**Comment by tigercat2000** [comment]
@Fullofskittles These look rather sharp around the edges - have you considered adding some slightly blurred pixels to the outline? It might make them look a little nicer. (disclaimer: just my personal opinion, the heads are in charge of approving the fluff item)

**Comment by KasparoVy** [comment]
Really loving the sprites. The hard edges are really the only nitpick I have.

**Pull request merged**
