### PR TITLE
Various DeltaStation Fixes/Tweaks

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 General map fixes and tweaks on DeltaStation.

- Reconnects Clown and Mime to the station power supply
- Re-links window tinters with their appropriate windows
   - IA Office
   - Robotics Surgery
- Gives the Detective's Office a solid airlock
- Adds a wall to the opposite side of the Gamma shuttle to prevent accidental space walks
- Adjusts the position of the lightswitch in the paramedic office to allow the paramedic to use the garage button
- Adjusts supply/scrubber pipes so they don't go under walls/windows in multiple places
   - NT Rep and BS office
   - Aft maintenance over by Escape
   - Supply Breakroom
- Adjusts disposal pipe in Science Breakroom so it no longer runs under a window
- Adds vents and scrubbers to the science test range so the air alarm can actually do something
- Relocates a vent and a scrubber in Escape to spread them out better (and not have 3 pairs in the same corner)
- Areas the DeltaStation SMES to use the `engine_smes` area, and adds the appropriate infrastructure
- Areas the DeltaStation Engineering Secure Storage to use the `equipmentstorage` area and adds the appropriate infrastructure
   - This is changing it from the `engine_smes` area it was before for some reason
- Areas the DeltaStation Hardsuit Storage to use the `hardsuitstorage` area
   - This was also using `engine_smes` for some reason
- Adds a few more light tubes to the main area of Engineering to make it less dark during nightshift lighting
- Cleans up the Atmospheric technician locker area so the lockers are one side and the hardsuit storage is on the other 
- Removes firelocks underneath the psychiatrist office windows

If I missed something, I apologize as I tend to fix first, document significantly after

## Why It's Good For The Game
If I had to pick a hill to die on, it would be not running pipes under walls and windows when it's not necessary. As well, making things actually work (like tinters) is not a terrible idea. In addition, the weird areaing in engineering was driving me mildly nutty (we have these areas for a reason, someone patched this together willy nilly reeeee)

## Images of changes
Not many obvious/visual changes besides Atmospherics stuff, but here is engi area stuff and escape as well for visual pleasure.

image

image

image

## Testing

<strike>Damn it, I don't wanna test my shizzle</strike>

Loaded up on a local server, ensured there were no runtimes regarding pipes, made sure that the new areas worked appropriately regarding APCs, fire alarms, and air alarms.

## Changelog
:cl:
tweak: Scrubber pipes and supply pipes no longer run under windows/walls in various spots on DeltaStation
fix: IA and Robotics surgery window tinters work again
tweak: Detective now has a solid airlock for appropriate privacy
tweak: Adds a wall to prevent people from accidentally walking off of the Gamma Armory into space
tweak: Engineering areas are now a bit more sane
tweak: Engineering has more lighting
tweak: Atmospherics locker area has been re-organized
fix: Mime and Clown offices now have power at round start
tweak: Science breakroom disposal pipe no longer runs under a window
tweak: Science test range now has a scrubber and vent
tweak: Escape scrubbers and vents are spaced out a bit more
/:cl:

### CODE REVIEW

**Comment by Miraviel** [comment]
As per the contribution guidelines, pull requests should be atomic. Map edits always enjoyed some leeway with this, but this change touches:
- clown and mime office
- ia office
- robotics surgery
- detective
- science
- atmos...

I can't even list it. It is too much.

Please, please, please make smaller map edit PRs.
It is difficult to review changes when they are all over the place and with fewer and less accurate reviews, issues tend to slip into production.

**Comment by LightFire53** [comment]
> As per the contribution guidelines, pull requests should be atomic. Map edits always enjoyed some leeway with this, but this change touches:
> 
> * clown and mime office
> * ia office
> * robotics surgery
> * detective
> * science
> * atmos...
> 
> I can't even list it. It is too much.
> 
> Please, please, please make smaller map edit PRs. It is difficult to review changes when they are all over the place and with fewer and less accurate reviews, issues tend to slip into production.

These all fall under what are.minor map fixes. I could very easily of up the queue with 13 i-2 line changes (as it is add a cable or two here, fix a variable there), but we have done mass map minor fixes like this in the past.

**Comment by hal9000PR** [comment]
from #development-news in the discord
image
not sure if we want to apply this to maps, but it does make it much harder to review

**Comment by LightFire53** [comment]
> from #development-news in the discord image not sure if we want to apply this to maps, but it does make it much harder to review

Very well, I can break it down into individual fix PRs if it's what is really desired.

**Pull request closed without merging**
