### PR TITLE
Whaddya mean I can't saw off my boomstick - Fixes #22893

### LINKED ISSUE #22893: Improvised sawn offs don't look sawed.
**Issue Description**:

Improvised sawn-off shotguns don't look sawed after sawing.

**What did you expect to happen**: 

Because the sprite should look different.

**What happened instead**:

The shotgun sprite looked the same.

**Why is this bad/What are the consequences**:

Because the sawn-off improvised shotgun looks cool and should be the intended sprite.

**Steps to reproduce the problem**:

Saw an improvised shotgun.

**When did the problem start happening**:

10/14/23

**Extra information**:

N/A

### PR DESCRIPTION
**Pull request by PollardTheDragon**
## What Does This PR Do

Fixes #22893
Gives sawn-off improvised shotguns their sprite back.

## Why It's Good For The Game

Bug fixes are good fixes.

## Images of changes

image

## Testing

Loaded game, spawned improvised shotguns, sawed off one

## Changelog
:cl:
fix: Sawn off shotguns have their sprites back
/:cl:

### CODE REVIEW

**Comment by 1080pCat** [comment]
you'd want the `Fix:` thing to not have anything between the 'fix' and '`#`22893'for it to correctly link and close the issue

**Comment by PollardTheDragon** [comment]
> b

Thanks for that. Adjusted accordingly.

**Comment by Henri215** [comment]
You still didnt do it correctly, and the changelog must be changed to describe what has been fixed

**Comment by PollardTheDragon** [comment]
I see where I made that mistake. Resolved, hopefully.

**Review by Henri215 — APPROVED** [review]

**Review by SteelSlayer — APPROVED** [review]

**Pull request merged**
