### PR TITLE
Paradise Station: Episode V - The Laserslug Strikes Back

### PR DESCRIPTION
**Pull request by SchrodingersWolf**
## What Does This PR Do

Readds Laser Slugs that were removed in #19552 - These are shotgun shells that fires one 20 damage laser beam per shell, much like a normal laser gun.

They are also now printable in a hacked Autolathe as well, and uses the currently unused improvised shell sprite to denote their somewhat hacky nature.

## Why It's Good For The Game

The improvised weapon category has been quite lacking and stagnant ever since the removal of improvised shells and overloaded improvised shell - While they are indeed problematic for balance, now shotguns mostly have nonlethal ammunition or techshells, with the latter requires Science to be manned, the Scientist on duty to understand what you are asking for, and also a lengthy crafting process. Incendiary slugs are okay but are difficult to use, so they are very underutilized.

Laser slugs would fill the niche that was previous occupied by improv shells, but without the associated issues with brute damage - So no bone breaks or internal bleeding. Critical burns are less debilitating so I wouldn't be too worried about that either.

And Qwerty has expressed a desire for laser muskets as well - This is in my opinion a good stopgap measure for now.

I'm also open to changing these too - Either by adding a misfire chance or lowering the damage if it becomes way too powerful, but I have been assured by many that it wouldn't overshadow other options so let's see how it goes.

## Images of changes

Images to come

## Testing

It really shouldn't break anything, but I'll test it tonight.

<hr>

### Declaration

- [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
image
  
  
  <hr>

## Changelog

:cl:
add: Readds Laser Slugs and make them printable in hacked autolathes.
/:cl:

### CODE REVIEW

**Comment by SchrodingersWolf** [comment]
> worried about combat shotguns and this, lots of burst damage they can just have without rnd now

Do note that combat shotgun fires as quickly as a normal laser gun, so it isn't as much burst damage as you think

**Review by silverplatedelta — APPROVED** [review]
Code looks good! No balance objections either.

**Review by BiancaWilkson — APPROVED** [review]
Code looks good, confirmed with the author that it was sufficiently tested.

**Comment by Burzah** [comment]
Looks good! Make sure to update your testing after you have completed it, in the future.

**Pull request merged**
