### PR TITLE
Paradise's soul removal part four and five: jumpsuits and caps resprite simple as

### PR DESCRIPTION
**Pull request by ElorgRHG**
<h2>end my misery</h2>

_this was very painful to make_

## What Does This PR Do

Ports https://github.com/tgstation/tgstation/pull/65264 and https://github.com/tgstation/tgstation/pull/66202
Resprites generic jumpsuits, and softcaps.
Another PR relying on https://github.com/ParadiseSS13/Paradise/pull/19058
Technically also https://github.com/ParadiseSS13/Paradise/pull/19333 too, but not required, I used the sec palettes used in that PR for sec softcaps in this one, will look out of place if not merged together but its not a requirement.

## Why It's Good For The Game

REMOVES SOUL HELL YEAAAAAAAAAA

but beside that, new sprites, new feel, fresher looking codebase, nothing more, nothing less.
The _ancient_ jumpsuit retains its old sprites since its... ancient, duh.

## Images of changes

All species have their variants, I'm just not arranging them all here, its painful 💀 

image

image

^ uses sprites from the sec resprite.

All sprites have rolled variants, and caps flipped versions

image

## Testing

Arranged the images in `Images of changes`

## Changelog
:cl:
imageadd: Resprited generic colored jumpsuits.
imageadd: Resprited softcaps.
/:cl:

### CODE REVIEW

**Comment by Coolrune206** [comment]
The side sprites in the last image seem to be suffering from missing hand syndrome. Might need to cut hand holes in the jumpsuit.
Other than that, these look nice. Is the ancient jumpsuit left unchanged, for the nostalgia?

**Comment by McRamon** [comment]
I am not a big fan of cap item sprites. They probably won't be resprited in this pr, and still better than what we have right now, but still want to point out they could be improved in certain aspects.

**Comment by Bm0n** [comment]
I personally don't like the newer style of TG jumpsuits. The colours seem off, especially for like yellow which looks shiny.

**Comment by ElorgRHG** [comment]
> Might need to cut hand holes in the jumpsuit.

Waiting on a different PR to remove the need to do that, its linked in the description.

> Is the ancient jumpsuit left unchanged, for the nostalgia?

Yes :)

> I am not a big fan of cap item sprites.

Changed them to a _modernised_ version of the old sprites, no more box caps 😔
Hopefully that's better. 

> I personally don't like the newer style of TG jumpsuits.

Subjective opinion, but need to standardise on _something_, my sec resprite already uses the so called "jumpsuit 3.0 style", better for the generic jumpsuits to follow that style too for coherency. But well, all depends if any of these gets merged, hell if some get rejected we'll be left with a similar unorganised mess as before I started this, we'll see I guess.

> The colours seem off, especially for like yellow which looks shiny.

Okay I'm not going to tell exactly what happened but I majorly fucked up with palettes, had to recolor almost every jumpsuit by hand... again, but hey, the yellow one is less shiny now at least.

**Comment by ElorgRHG** [comment]
The prerequisite PR has been merged, while this PR is ready for a merge, the security softcaps will look a bit weird with our current jumpsuits as they've been made more in mind that the security jumpsuit resprite would get merged before this one, but its not required.

**Comment by roarbark** [comment]
these look much better than what we have. sec jumpsuits have really pronounced zipper colours though, which is gonna make jackets look bad with them

**Review by S34NW — APPROVED** [review]

**Review by farie82 — APPROVED** [review]

**Pull request merged**
