### PR TITLE
Fixes a few Bugs with PR #5416

### PR DESCRIPTION
**Pull request by KasparoVy**
:cl:
fix: Fixes a bug where changing your alt head required two icon updates to show.
fix: Fixes a bug where you couldn't choose head marking styles that would ordinarily be available regardless of your alt head.
fix: Fixes a bug where Tajara couldn't choose undergarments.
fix: Resolves an issue with the Vulpkanin Jagged hairstyle missing a pixel.
/:cl:

-----------------
First bug: Changing your alt head in CMA wouldn't update it correctly.
You had to proc update_body(1, 1) twice in order to do it because of where the head_organ.handle_alt_icon() proc call was placed in organ_icons. It would just set up the head's new icon but would require a second pass of update_body(1, 1) to show on the mob.

Reproduced by going into CMA (whether it be the admin verb or using a nanomirror) and trying to change your alt head when you're an Unathi.
Resolved

-----------------

Second bug: Lack of sanity and inability to select head marking styles with "all" alt heads allowed.

Reproduced by going into CMA (whether it be the admin verb or using a nanomirror) as an Unathi with the 'sharp' alt head and trying to click 'tiger head' head marking.
Resolved

-----------------

Third bug: Some species were absent from undergarment allowed species definitions and, as such, weren't able to choose undergarments in character select or at dressers.

Reproduced by going into character select or to a dresser as a Tajara and trying to change your undershirt/pants/socks

-----------------

Vulpkanin Jagged hairstyle sprite:
pixelfixel

-----------------
I must've had a hardcore brainfart when I was resolving some conflicts because there was a whole part of an if statement missing. Ack!

Tested on local environment and all's good now.

### CODE REVIEW

**Comment by Aurorablade** [comment]
i cannot change my undershirt on my tajaran on char setup..it might be just me..

**Comment by KasparoVy** [comment]
@Aurorablade Isn't just you, nice catch. Found the issue and fixed it, just gonna test it and push it to this PR as well

**Comment by Aurorablade** [comment]
@KasparoVy also jay winglers tail is listed under body accessorys....its related to his fluff item i think but may want to make sure it locked down. mght be related to our DB so i dunno if you can local test that.

**Comment by Fox-McCloud** [comment]
@KasparoVy 

On the `Jagged` vulp hair style there's an errant pixel when facing north. Could ya fix that?

**Comment by KasparoVy** [comment]
@Fox-McCloud Sure thing, on it

@Aurorablade Sorry for my ignorance but what's your rank on the server right now? What species were you when you saw that bug, and were you in character creation or using a nanomirror?

**Comment by KasparoVy** [comment]
@Fox-McCloud Could you please take a snip of the hairstyle and point out the errant pixel please? By looking at the sprite, all seems in order from what I can tell

@Aurorablade Sorry for my ignorance but what's your rank on the server right now? What species were you when you saw that bug, and were you in character creation or using a nanomirror?

**Comment by Aurorablade** [comment]
@KasparoVy codermin but if its locked down thats okay. and Tajaran..and char select. it might be just admin only visable...i didn't deadmin

**Comment by KasparoVy** [comment]
@Aurorablade Yep, that's why it's showing up for you then. It's admin-only visible and totally locked down for non-mins from what I can tell

Thanks for bringing it up though!

**Comment by Fox-McCloud** [comment]
Uh, I saw it on Jagged when the hair was pitch blank and the person was standing north (ie: you could see the back side of the head).

I'll try to get a pic soonish.

**Comment by KasparoVy** [comment]
Thanks a bunch

**Comment by Aurorablade** [comment]
@KasparoVy I KEEP ADDING SHIT..fur patch patterns show over robo limb.s...

**Comment by KasparoVy** [comment]
@Aurorablade The markings showing over robolimbs is intentional, as robolimbs are treated just like regular limbs and as such if the markings didn't cover them that means they wouldn't be covering fleshy parts

**Comment by Aurorablade** [comment]
...ehhhhhh i wish there was a way around that....

**Comment by Fox-McCloud** [comment]
@KasparoVy 

img

**Comment by KasparoVy** [comment]
Got it, thanks!

pixelfixel

**Comment by KasparoVy** [comment]
@Fox-McCloud Got it, thanks!

pixelfixel

**Pull request merged**
