### PR TITLE
Fancier solars by sec/service.

### PR DESCRIPTION
**Pull request by fj45**
solars

Shouldn't change anything apart from how the solars look. I hope.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Did you make sure that no ship docking areas are impacted by this?

Also are the total amount of solar tiles (blue ones) the same?

**Comment by fj45** [comment]
None of the shuttles conflict and it has the exact same number of solars. Just fixed some areas I missed.

Thanks for getting the pic working.

**Comment by SamCroswell** [comment]
:+1:

I'd love for you to do the other solars as well at some point.

**Comment by fj45** [comment]
Bugger, conflicted with DZDs carp spawn change. Any ideas?

And yes Dave, I will do the rest when I can, this was mostly just a test. Although I might leave the engie one as that area might change.

**Comment by Fox-McCloud** [comment]
@fj45 

Best suggestion is to take what you've done and copy-paste it onto the most up to date version of the map.

No idea why this would create conflict unless a carpspawn was in the area.

**Comment by fj45** [comment]
Alright, how do I get an updated map?

**Comment by Fox-McCloud** [comment]
@fj45 

you could just manually download it right from the git and shove it into your repository.

**Comment by fj45** [comment]
Welp, messed that up, I'll just try to redo it fully.

**Pull request closed without merging**
