### PR TITLE
Axes prescanning.

### PR DESCRIPTION
**Pull request by Qwertytoforty**
## What Does This PR Do

Prevents cloners from scanning alive people.

One could in theory die, then get defibed after being scanned, but that is not possible to fix without checking each record each process to see if the record is alive, which sounds horrible, but can be done if needed. We can just bwoink people for doing that on purpose.

## Why It's Good For The Game

Prescanning is bad. It makes assassinations a pain, we do not have CMD, so people will remember what killed them... even when they scanned at start of shift, which logically is the last thing they should remember. It can make people rush in to get themselfs killed, as they do not fear death as they *will* be cloned. Also prevents something like an off station cloner + teleporter setup to endlessly attack the station.

## Changelog
:cl:
tweak: You can no longer prescan people with the cloner.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Ideally, we gut the whole records thing from the cloner as well, its overcomplicated for what it is, and is part of the prescanning memes.

**Comment by S34NW** [comment]
If someone dies, is scanned and revived, this does not prevent them from being revived later if they die a second time

**Comment by Qwertytoforty** [comment]
Disk stuff for cloners removed

**Comment by SteelSlayer** [comment]
This will "fix" #18055.

**Pull request merged**
