### PR TITLE
Removes 'lusty xenomorph maid' mobs

### PR DESCRIPTION
**Pull request by Kyep**
Reasons:
1) They're a mob named "lusty xenomorph maid". We wouldn't let a player have a name that started with "lusty". We shouldn't admin-spawn mobs with this name, either.
2) They're a reference to a porno. It should be obvious why we don't want porno references in Paradise.
3) They're too silly. They cheapen Xenomorphs in general.
4) If we want to clean things, we have a ton of better options. Janitors, Janiborgs... and the upcoming janitorial ERTs in another PR. There are plenty of better options than this.

🆑 Kyep
rscdel: Removed xenomorph maids.
/🆑

### CODE REVIEW

**Comment by SamHPurp** [comment]
Keeping them in is indefensible, I'd love to see people's reasoning for it.

**Comment by Aracino** [comment]
Eh, I don't mind. It's just something funny.

**Comment by tigercat2000** [comment]
It's an admin-spawn only mob. I see this the same as removing ponies, and this establishes a bad, bad principal. :-1:

**Comment by Fox-McCloud** [comment]
No. These are admin only, and there's already existing references to them in the game itself.

Are we going to remove the maid outfits next because of them being a "reference".

These aren't even accessible via Xenobio gold cores.

**Comment by SheepFighter** [comment]
I don't think our standards are so strict that we'd ban an oblique reference to the Lusty Argonian Maid.
Heck, we still have the bondage things hidden in the walls.

If we saw xenomaids every shift, I'd want them gone. But we don't, and as such they're an entertaining bit of occasional silliness.

**Comment by Aurorablade** [comment]
Admin spawn only.

**Comment by Aracino** [comment]
...The name change doesn't change my stance.

**Comment by scrubmcnoob** [comment]
look man i'm working off a parental restricted internet browsing history and i'm already scraping the barrel for 'reference' material at night
this is my only outlet man

**Comment by Doukhan** [comment]
No fun allowed.

**Comment by Anticept** [comment]
I don't see them enough to be crazy about removing them, even though I'd still prefer there to be far less "cheap" fun such as memes (which in general is done **so much**, it's become tired).

**Comment by Fruerlund** [comment]
I'd rather see we remove xenosuit and wizard clothes. In my opinion these are supposed to be dangerous and rare creatures and not some baldy running around each shift. I could understand reasons for keeping the wizard/witch clothes but not the xeno. Antags are supposed to be dangerous not toys

**Comment by SamHPurp** [comment]
@Fruerlund I agree, but the amount of salt I'd get for submitting that PR would overdose and kill me.

**Comment by uraniummeltdown** [comment]
The players are not idiots, if they think the lusty xeno maid means that ERP is a-ok then they're too young/immature to play here, why do we have to act like paranoid mothers and remove this funny fluff

**Comment by Anoonki** [comment]
It's good for a giggle for one of these to get spawned in and just start polishing the Captain.

But for real.

>The players are not idiots, if they think the lusty xeno maid means that ERP is a-ok then they're too young/immature to play here, why do we have to act like paranoid mothers and remove this funny fluff

**Comment by Kyep** [comment]
Threw this up quickly because someone asked for it in staff voice.

Turns out the votes on github are 2 in favor, 9 against.
Fox and Neca are against it, which is half the maintainer/head vote right there.

Probably won't pass, and not a big deal, so, closing.

**Comment by Anticept** [comment]
@samhpurp @fruerlund Aren't these under "anti-valid"? I do like the idea of fake wizards and fake xenos to curb a bit of the "ITS A WIZARD RED ALERT" at the first sight.

**Comment by SamHPurp** [comment]
@Anticept @Fruerlund these are xenos in a maids  outfit, that 'polish' things.

**Comment by jughu** [comment]
Never forget skyrim reference

**Comment by Anticept** [comment]
@SamHPurp we're talking about the xeno outfits.

**Comment by SamHPurp** [comment]
@Anticept oh, as in, don't robust every wizard you see, it might just be an idiot assistant?

Meh. I guess.

**Comment by TravellingMerchant** [comment]
If you remove this, we riot.

**Pull request closed without merging**
