### PR TITLE
New End-Round Sounds

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Credit to Goonstation for these.

[Ending1](https://raw.githubusercontent.com/Fox-McCloud/Paradise-1/b12bc6d7fc053bc124cf6f967364155b713c7f25/sound/goonstation/misc/NewRound1.ogg)
[Ending2](https://raw.githubusercontent.com/Fox-McCloud/Paradise-1/b12bc6d7fc053bc124cf6f967364155b713c7f25/sound/goonstation/misc/NewRound2.ogg)

:cl: Fox McCloud
add: Adds in two new end-round sounds
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
As much as I'd love new stuff to spice things up, these two sound files are not that stuff.

:-1:

**Comment by HugoLuman** [comment]
I like the first one, but I'm a bit mixed on the second one. I mean, don't get me wrong, I love Rocky Horror, but the sound file goes on a bit long. Maybe truncate it at the 5 second mark?

**Comment by taukausanake** [comment]
I don't like either of them. Neither sound as if they belong on the server. I think we could go for some new round-end sounds but not these two

**Comment by TheDZD** [comment]
Yeah, they both seem out of place.

**Comment by Fox-McCloud** [comment]
I find it odd these are viewed out of place when we have "put a banging donk on it" and "APC DESTROYED MISSION ACCOMPLISHED", which are...well, about as non-sensical.

**Comment by Ty-Omaha** [comment]
IDK what they're saying I need better ears can someone tell me what they say please

**Comment by HugoLuman** [comment]
@Fox-McCloud Well to be fair the other two are at least SS13 memes (and donks and APCs are both in game). I know there's a clip somewhere that says something like "Preparing to purge Central Command reception area..."

**Comment by Plotron** [comment]
I am fine with the first sound. It's short and to the point. And it's quite cheerful.

Sound no. 2 doesn't fit.

**Comment by Fox-McCloud** [comment]
@Ty-Omaha 

"Let's do the time warp again"...in context of SS13, it's a less-than-subtle jab at the fact taht you do the same thing over and over and over and every shift is the same, essentially (minus random variations).

**Comment by Iamgoofball** [comment]
stop throwing a fit over muh reels and muh immuhlsions on a station with clowns, mimes, and devils

:+1: not everything has to be super edgy blood on screen so reel grimdark

**Comment by Dumbdumn5** [comment]
I dislike the first one just because it doesn't seem to fit, but, as a fan of Rocky Horror, I'd die before saying no to another time warp.

**Comment by Plotron** [comment]
So I see opinions are very mixed here.

**Comment by Fox-McCloud** [comment]
Yup, seems that way x3

**Comment by Ty-Omaha** [comment]
@Fox-McCloud Ohhhh lol

**Comment by taukausanake** [comment]
Would the time warp clip even finish playing once the server closes? I don't know how sound clips work but it seems pretty long

**Comment by Aurorablade** [comment]
yeah it would

**Comment by GeneralChaos81** [comment]
Moar diffrunce pls

**Comment by Fox-McCloud** [comment]
@taukausanake 

Yup, and usually things continues to play, even if the game closes out fully.

**Comment by IcyV** [comment]
The end-round clip of all thing doesn't have to make any sense in any regard, really. It's literally just a sound to let people know the round ended. I'm all for more so I don't have to listen to the same two every single time.

**Comment by Dinarzad** [comment]
We should do the Time Warp.

**Comment by Lady-Luck** [comment]
I like sound 1, not so much sound 2.

**Comment by taukausanake** [comment]
I think I'd be okay with Time Warp if Chrono Legionnaire was ever used. I mean that's the only connection I'd see that would be of use when IC is taken into account. That's only because I don't consider the station to be Groundhog Day however

**Comment by Fox-McCloud** [comment]
>That's only because I don't consider the station to be Groundhog Day however

You don't have to consider it Groundhog Day to still arrive at that conclusion though---every shift, everything resets--even those who maintain consistency and such between rounds (the vast majority of the players, even the super low RPers) acknowledge this quirk from time to time ICly (R&D resetting, slimes resetting, pharmaceuticals needing to be re-made, the station getting re-built quickly after a nuke).

**Comment by taukausanake** [comment]
Yeah, that's a fair point. Still not too keen on Time Warp however. It'll be considered salt on my part because these are from Goon and I really don't want to become Goon. Any argument can be made that sounds won't make that happen but again, it's salt on my part

**Comment by HugoLuman** [comment]
I think people would be better with Time Warp if you trimmed it at the 5 second mark

**Comment by Twinmold93** [comment]
I'm not against new sounds, that added variety. I really couldn't care less if these were added to the rotation of possible sounds. The only thing of any notice is if they are too loud compared to the others, which could take people at more a surprise and flinging their headsets off their heads to suddenly get a blast in the ear. I suggest a few people note how loud (or perfectly fine as is) it sounds to them so it can be decided if one or both need turned down, volume-wise, a little.

I can't say too much on that, due to my headset being set to something like 8% right now of max volume and the game STILL sounds a bit loud at times. Normally I run at around 4%, so as they are now shouldn't be bad, if implemented, but definitely people should note on.

**Pull request merged**
