### PR TITLE
Updates Enforcers

### PR DESCRIPTION
**Pull request by shazbot194**
This PR primarily updates the Enforcers to make them a bit more acceptable. This is done by making the Enforcer 9mm rather then .45 cal. This means that the lethal ammo isn't nearly so powerful, doing only 20 damage, with no stamina damage. In addition, this PR also address the fact that .45 rubber does less stamina damage then the lethal, by upping the stamina damage to 75, still needing two hits to down someone though. 

🆑 Shazbot
Change: The Enforcer is now 9mm.
Change: .45 Rubber now does 75 stamina damage.
/🆑

### CODE REVIEW

**Comment by variableundefined** [comment]
I think it is better to keep the stamina damage for .45 as is. One way to view it is to view midbullet as an OP ammo designed specifically for the syndicate (And the Adminbus M1911). I have no issue with the inconsistency personally.

**Comment by variableundefined** [comment]
Also, regarding the sprites - I don't like the shading, it is worse than the original one.

The original has a subtle, light source, coming from the top left of the sprite that give it some depth.

The new sprites has its handle shaded from left to right, while the top of the gun (receiver? I am not good with pistol term) is shaded uniformly from top to bottom - starting with the lightened side first. It is shaded as three distinct line. This is nonsensical pillow shading.

**Comment by shazbot194** [comment]
> I think it is better to keep the stamina damage for .45 as is. One way to view it is to view midbullet as an OP ammo designed specifically for the syndicate (And the Adminbus M1911). I have no issue with the inconsistency personally.

This only effects the rubber ammo, and ups the stamina damage from 30 to 75, which should be compared to the normal's 65 stamina damage, which means that both the rubber and lethal ammo take two shots to down someone.

> Also, regarding the sprites - I don't like the shading, it is worse than the original one.

I can edit the sprites to do a similar style shading, as I made both, but I do like the brighter colors of this new sprite. 

> top of the gun

I think you are looking for slide.

**Comment by variableundefined** [comment]
> This only effects the rubber ammo, and ups the stamina damage from 30 to 75, which should be compared to the normal's 65 stamina damage, which means that both the rubber and lethal ammo take two shots to down someone, as opposed to the original 4.

I'm still not convinced it is necessary to buff the non-lethal's stamina damage. Normal c45 is meant to be an outlier. Making it so powerful would only make coder reluctant to use it in "non-lethal only" gun by giving it two-hit knock down ability without all the vulnerability & disadvantage of a taser.

> I can edit the sprites to do a similar style shading, as I made both, but I do like the brighter colors of this new sprite.

I prefer the original way over this one. For one, I still believe the shading is way worse. For two, I think an overly bright colour is not too fitting compared to most other guns on the station, which generally use a slightly dulled colour

**Comment by shazbot194** [comment]
> I'm still not convinced it is necessary to buff the non-lethal's stamina damage. Normal c45 is meant to be an outlier. Making it so powerful would only make coder reluctant to use it in "non-lethal only" gun by giving it two-hit knock down ability without all the vulnerability & disadvantage of a taser.

This would only be used in guns like the C45, as the big part of this PR makes the enforcer 9mm, which means only the M1911 and the C45 can use the .45 ammo anymore. Effectively, upping the non-lethal damage makes the non-lethal a better pick, as you don't now need to hit twice as much with either gun to down someone.

**Comment by Kyep** [comment]
Whenever I look at an enforcer, my first thought is "now, which one of the 13 different color variants am I dealing with, and how is that variant different from all the others?".

**Comment by KasparoVy** [comment]
Just throw it at them. At least then you have some sort of guarantee. Just what, though, is up for interpretation

**Comment by FreeStylaLT** [comment]
🔫

**Comment by shazbot194** [comment]
Well, since few to no-one in the community nor the admins seems to like the sprites, even the ones updated with new shading, I'm just going to remove the icon part of this PR.

**Comment by Allfd** [comment]
I love this.

When I run a gun round I do this with the spawned ammo (I was setting to 15)   The only thing I would add is lethal should probably be the default (although I can do this in a different PR)  Rubber is inferior to a taser and the purpose of the weapon is really to not deal stamina damage but to deal real damage. 

While they are not standard loadout, I have a script that takes care of all of that at roundstart, the only problem being that bullets show up as rubber instead of lethal, but are lethal (I should probably just add more to the script to change that);.

Overall security starting with an enforcer, has not really had any appreciable balance changes (other then security ends up fully staffed... which does not make sense unless... someone is sharing round information 🤔 )

**Comment by shazbot194** [comment]
Personally, I see the benefits of the enforcer is that it can switch back and forth from lethal and stamina damage, not quite good at either, but it’s better then a laser rifle at non lethal and better at lethal then a disabler, and if there ever is any added specialty ammo, like flash rounds, or a tranquilizer round, or whatever someone can come up with, the enforcer is ready to accept them. But this is also why I see the 9mm is better for them, so neither lethal nor non lethal is outright better.

**Comment by Allfd** [comment]
Yeah, I agree, its not a super relevant change anyways as these will remain admin only with this PR.

**Comment by variableundefined** [comment]
This has been approved by a head and a maintainer.

Merging.

**Pull request merged**
