### PR TITLE
Fixes Startup-Lockup and Slow UI

### PR DESCRIPTION
**Pull request by Puckaboo2**
This fixes my lockup problems after I log in like I have been talking about for weeks! Please accept this! It really works!

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This isn't even properly spaced and it makes the proc literally do nothing. Going to break asset sending.

**Comment by PJB3005** [comment]
> This is going to break asset sending.

Assuming you didn't horrendously blow the implementation of the asset cache, nah.

> Also, I suspect this was made using the github web interface editor---don't do that, please.

Please we've gone over this before, web editor is not evil in and of itself.

**Comment by Crazylemon64** [comment]
Yeah, asset sending is *still* going to work with this change, but it'll be done right when the corresponding UIs are interacted with, instead of the start of the game. Primarily:
* Paper
* All NanoUI-dependent devices (a long list)
* Chess

I *do* wonder if it might be wise to add a client preference to enable/disable passive asset sending, if this is such a dramatic issue.

**Comment by Shadowlight213** [comment]
Inb4 this causes people to complain that tgui is slow even MORE

**Comment by Spacemanspark** [comment]
Why was this closed

**Comment by Fox-McCloud** [comment]
This doesn't fix the particular issue, at all, and there's been no indication he'll be working on it further.

**Pull request closed without merging**
