### PR TITLE
Adds Resomi/Teshari/Seromi

### PR DESCRIPTION
**Pull request by tigercat2000**
Ports Resomi/Teshari/Seromi from Polaris PolarisSS13/Polaris#777

They're cute little things that can see through walls. When no one is near them, they get depressed, and suffer debuffs until they are within view of someone again.

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
*CHANGELOG*

See. I can do it too.

**Comment by KasparoVy** [comment]
:)

**Comment by Xantholne** [comment]
They sound adorable, I want them.

**Comment by Lady-Luck** [comment]
So we're patching without the PDA slot re-added huh?

**Comment by Earthdivine** [comment]
ERT Fixes take far more priority then a silly slot :p

**Comment by Spacemanspark** [comment]
Just wait a few days for the PDA slot

**Pull request merged**
