### PR TITLE
Port and modify delta escape shuttle to cyberiad

### PR DESCRIPTION
**Pull request by datlo**
Deconflicted version of #11971, with new shuttle chairs added to the shuttle from #11696

See linked PR for details on the shuttle and comments

newshuttle

:cl:
add: Replaced the current escape shuttle with a larger, improved one modified from Delta station.
tweak: Modified the escape pod bay layout so that the dock isnt blocked when the new larger shuttle is docked
/:cl:

### CODE REVIEW

**Comment by craftxbox** [comment]
What about the mech recharger?

**Comment by datlo** [comment]
I dont really see the need for a mech recharger on the escape shuttle imo

Also ree this is conflicted again

**Comment by taukausanake** [comment]
I see the mech recharger as a docking port for mechs. A place meant for them to be placed. You can fit one right next to the windows in the cargo section.

Can I ask what those external airlocks are doing on the top-ish right? Where are they meant to go to and I can see them as a potential entrance into the shuttle besides the main doors. They also aren't shuttle doors so really wondering what they are doing there

**Comment by datlo** [comment]
from the linked PR : 
'The one room that is entirely new : The emergency external airlock. The external airlocks are public access and can be entered by any crewmember, however the internal white doors are security/command only and are see-through glass, meaning it will be difficult for antags to sneak in without being noticed that way. This also provides an alternative entrance to hijack antags who dont mind going loud to emag the shuttle away. The external airlocks (and only those) have atmos blocking tiny fans so the pressure doesnt get fucked whenever someone enters or exits the shuttle using them'

**Comment by Kyep** [comment]
What happens if an admin loads one of the alternate escape shuttle templates?

**Comment by datlo** [comment]
Shuttle is loaded as you'd expect however you will not be able to switch back to this new escape shuttle because the code for the shuttle loader cant handle its size

**Comment by taukausanake** [comment]
Maybe that should be fixed first? Loading of different sized ships?

**Comment by datlo** [comment]
I was told its fine

However with the new transit system that I believe was merged it should be much easier to fix I will look into it when I get around to updating this.

**Comment by datlo** [comment]
This PR needs more work that I dont really want to deal with right now. It WILL be reopened eventually, ideally after Free's engineering remap is merged.

If anyone wants to pick up the files and make their own deconflicted PR they are free to do so, ideally also with a fix for shuttle loading (it cant be loaded right now because its too big for the shuttle manipulator).

**Pull request closed without merging**
