### PR TITLE
Adds chickenman and clown statues

### PR DESCRIPTION
**Pull request by ZomgPonies**
- Adds bronze chickenman statues to Mr. Chang's. Thanks Nienhaus for sprite!
- Adds golden bananium clown statue to the clown office. Thanks Hippiestation for sprite!
![] (http://i.imgur.com/aLbAmOF.png)
clownstatue

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Pics of the statues?

**Comment by Nienhaus** [comment]
Chicken statue is my sprite.

**Comment by tigercat2000** [comment]
:+ WAIT IS THAT A CHICKEN SUIT AHHHHHHHHHHHHHHH :scream_cat: :runner: :cry:

**Comment by Iamgoofball** [comment]
>bananium

that looks like bronze

**Pull request merged**
