### PR TITLE
Species now can have reagent-specific reactions

### PR DESCRIPTION
**Pull request by Crazylemon64**
This is a first go of a system to give each species the ability to react uniquely to each reagent!

For demonstration purposes, chocolate-type reagents act as tabun to Vulpkanin - this might be a bit too intense. Let me know your thoughts!

:cl:
tweak: Species can now respond uniquely to reagents
rscadd: Chocolate reagents are now terrible for Vulpkanin
/:cl:

### CODE REVIEW

**Comment by NTSAM** [comment]
I will begin serving nothing but hot chocolate in the bar now just to see everyone's reactions :smiley:

**Comment by Crazylemon64** [comment]
Eh I'll just squash this into the other one

**Comment by Crazylemon64** [comment]
Oh whoops this would've made chocolate like tabun for EVERYBODY

kek

**Comment by NTSAM** [comment]
holy fuck memed

**Pull request closed without merging**
