### PR TITLE
Made the Psych spawn in their office

### LINKED ISSUE #8682: Roundstart psychologist spawns in the arrivals shuttle
**Problem Description**:
The psych spawns in the arrivals shuttle if the job is chosen at round start.

**What did you expect to happen**: 
The psych has an office. They should spawn in their office...

**What happened instead**:
They did not spawn in their office, but instead did on the arrivals shuttle.

**Why is this bad/What are the consequences:**
It's kind of annoying to have to walk all the way across the station every round start when every other job spawns where they're supposed to. (AKA in their workplace)

**Steps to reproduce the problem**:
Have psychologist set to high. Declare ready and spawn as psych at round start. Notice you spawn in arrivals instead of your office.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
I haven't tested this with the other two therapist job titles yet (Therapist and psychiatrist) so I don't know if this happens to them too, but I'm going to assume it does unless someone tests it, since they're all just the same job renamed...

### PR DESCRIPTION
**Pull request by PigeonLord**
Self Explanatory. I added a spawning landmark in the Psych's office.
Fixes #8682 
:cl: Piccione
rscadd:Psych now spawns in their office instead of the arrivals shuttle
/:cl:

### CODE REVIEW

**Comment by Birdtalon** [comment]
You need to use map merge.

**Comment by PigeonLord** [comment]
Ah, i was pretty sure i did. Although maybe i shouldn't have tried to use it manually.

**Comment by PigeonLord** [comment]
Ok, it works now. Sorry for my faux pas.

**Comment by Birdtalon** [comment]
No harm done!

**Comment by taukausanake** [comment]
How long has the Psych not had their spawn?

**Comment by alexkar598** [comment]
Since medbay remap I assume

**Pull request merged**
