### PR TITLE
advanced medkikits replaces gauze with splints

### PR DESCRIPTION
**Pull request by jughu**
because having gauze for only bleeding damage was really useless when the trauma kits already fixes bleeding damage

### CODE REVIEW

**Comment by Lady-Luck** [comment]
gauze also disinfects

**Comment by jughu** [comment]
Oke i removed the epi pen from the advanced kit and put back the gauze so it can focus on more advanced injuries with the splints

**Comment by Plotron** [comment]
No need, damn it. That medkit just works, don't touch it!

**Comment by Lady-Luck** [comment]
Until splints have some sort of penalty associated with them (which should probably wait until the life refactor is completed) I'm against this.

**Comment by Fox-McCloud** [comment]
Splints were intentionally removed for a reason; to actually force you to go to medical for them, given how they work.

**Comment by jughu** [comment]
I close this then untill the refactor is done

**Pull request closed without merging**
