### PR TITLE
[s] Revert "Vulpkanin & Tajara mod. Colour Vision, Darksight to Eyes, Internal Mech(assist) Organ Icons"

### PR DESCRIPTION
**Pull request by tigercat2000**
Reverts ParadiseSS13/Paradise#6123

😎

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
Tiger is trying the pullout game, but it's too late

**Comment by Rumiluntti** [comment]
Is this one of them may-mays the kids talk about?

**Comment by DarkPyrolord** [comment]
Yes it is Rumi, yes it is

**Comment by Crazylemon64** [comment]
Danke 👌

**Pull request closed without merging**
