### PR TITLE
[DNM] Janitor can now access medical

### PR DESCRIPTION
**Pull request by Anticept**
Medbay's a mess. Time to clean it up. Gave janitor access to main medical only.

Reasoning:
- I hate playing janitor.
- I love playing janiborg.
- I can clean the bloodiest place on the station without beating my face against the door trying to get in. Thus, making me like janitor quite a bit more.
- Closes the gap a little bit on janitor and janiborg.
- Surgery changes and infection changes means its more important to keep the place clean, and I think the janitor having an easier time getting into medbay means the surgeons can see the janitor more easily, but still be able to decide if he should be let into the ORs.
- Mildly buffs janitor antags.

We'll see how much this helps. I'm sticking in line with my philosophy of small changes at a time, we'll see how much this benefits.

This goes not grant access to anywhere except main medbay only. Surgery, cloning, chemistry, virology, these are all still off limits, as they should be. Nor does it give access to any of the other departments, mainly because its either rare for bloody messes, or it needs to remain controlled access (security).

EDIT: realized there's a lot of issues giving janitor medical level access. Too many. Will varedit and mapmerge the doors instead in the next couple days.

### CODE REVIEW

**Comment by Anticept** [comment]
Potential issue, medical vendor access. Might have to go a different route and change the medical door access to include janitor instead.

**Comment by taukausanake** [comment]
Personally I'd like the janitor to have basic department access but then you just brought up the issue of extra access they shouldn't have. I don't like the idea of putting the access on each door because they will potentially be forgotten and require a hotfix. But I'm also not much of a mapper and don't like the requirement to varedit things in

**Comment by FlattestGuitar** [comment]
All you gotta do is change the right variable on the door to let the Janitor into medbay. No need to fiddle around with their default access.

**Comment by Anticept** [comment]
@FlattestGuitar I was thinking that, but its a bit of a snowflaking case that map makers would have to remember. I think I would much prefer an access level. But that's kind of snowflaking too...

**Comment by SamHPurp** [comment]
Best way to do it is varediting the doors in question to add the access imo.

**Comment by taukausanake** [comment]
You then also end up with a bunch on instances of types of doors and that's what kind of make me stay away from mapping in the early days. It got confusing when you had 40 APCs and 20 different doors for each department. I know APCs were changed but I don't think the same can be said for doors and some if not most share the same name so you don't know which door is for what purpose without looking at the vars

**Comment by Anticept** [comment]
@SamHPurp That probably will have to be the route that I go. There's other issues that I am realizing as well, like access to the isolation ward, the storage near the front desk, access to some medical lockers... Adding a new access level in the manner that the brig does it would be a LOT of changes.

I'll varedit and mapmerge in the next couple days.

**Comment by Fox-McCloud** [comment]
Janitor doesn't need the additional access like this; it's an ultra low level job and is meant to be treated as such. This won't help out with the new germiness of surgery, one bit, as this doesn't give him surgery access, nor should he have that.

At best this helps out with medbay general, and that's all, really. It's not that hard to communicate with the crew over public comms, PDA, or even asking the AI. If that doesn't work, then medical should be punished for their poor gameplay decisions.

Borgs beat janitors because all borgs beat humans at the jobs they are spec'd into at the cost of being less diverse; a janiborg beats the janitor at janitor-ing, but isn't able to perform a quick patch up for someone they find injured in the hall.

Likewise an engiborg is better equipped to deal with a hull breach when he happens upon it, compared to a regular engineer, but falls flat on his face if he's trying to do something outside his field.

These are generalization; I know you can nitpick specific scenarios where, technically, humans beat borgs at a specific task, but..as a generalization, where a borg excels, it's better than what a human is capable of.


This same justification for medical access could be extended to just about any department or area (likewise the same logic has been applied to paramedic). That's the big problem I have with it--it's essentially a "hyper efficient, autonomous jobs are the best", which that has clearly demonstrated, in the past, that this can and does cause interactivity problems (ie: see current R&D).

hyper efficiency is not a desirable thing.

**Comment by Anticept** [comment]
> Janitor doesn't need the additional access like this; it's an ultra low level job and is meant to be treated as such. 

I don't think we should use this as an argument for or against changes, as it's a really poor metric to use. Rather, it should be based on the merits of the tasks in which they perform.

> This won't help out with the new germiness of surgery, one bit, as this doesn't give him surgery access, nor should he have that.

Agreed, and I didn't push for giving him surgery access for two reasons:

- Janitors barging into surgery with the germiness will just piss off the doctors.
- He can sit at the window and be seen pretty clearly. If the surgeon is busy, he can come back later.

I agree there is little point to keeping any part of medbay except surgery clean, but would this really be appropriate to use this as a design decision? It's a medical facility, and even if cleanliness doesn't really affect anything directly, a dirty medbay sure does make players judge the hell out of them.

> At best this helps out with medbay general, and that's all, really. It's not that hard to communicate with the crew over public comms, PDA, or even asking the AI. If that doesn't work, then medical should be punished for their poor gameplay decisions.

The time the janitor is needed most, is when medbay is least able to answer his calls or make them. Their job, first and foremost, is treatment. Medical would hardly be considered a secure section of the station anyways, compared to the others.

> Borgs beat janitors because all borgs beat humans at the jobs they are spec'd into at the cost of being less diverse; a janiborg beats the janitor at janitor-ing, but isn't able to perform a quick patch up for someone they find injured in the hall.

They *shouldn't* be patching anyone up. It's a janitor. **We shouldn't be using this as a design consideration except in the most extreme circumstances.**

> Likewise an engiborg is better equipped to deal with a hull breach when he happens upon it, compared to a regular engineer, but falls flat on his face if he's trying to do something outside his field.

This is incredibly false. Being an engineering main both in borg and in biological, I can tell you that engineers can handle most things better than engie borgs can. Where engineers are especially better at it is that we can carry extra stacks of material to a job site, and even stick materials and items into engi-carts, toolboxes, and dufflebags. Borgs can't and have to make multiple trips to the charger for anything more than basic tasks.

The only advantage a borg would have is being immune to space, but the fact there's hardly a drawback to just wearing the hardsuit around the station, means this is pretty moot as well.

> These are generalization; I know you can nitpick specific scenarios where, technically, humans beat borgs at a specific task, but..as a generalization, where a borg excels, it's better than what a human is capable of.

For most of the borg types, they are actually pretty close to their humanoid version. Sec borgs can be crazy powerful, but at the same time, quite vulnerable too to the right preparation. Meanwhile, there isn't really a downside to a janiborg. They do their job amazingly well, while the janitor... not so much. The upgraded buffer for his cart helps a whole lot, but it's still a lesson in extreme frustration due to access.

> This same justification for medical access could be extended to just about any department or area (likewise the same logic has been applied to paramedic).

No, it can't. The purpose of access is for both gameplay considerations and something similar to the "principle of least privilege." The only reason I'm even suggesting this for medical is because cleanliness in a medical facility is a must, and we're making progress towards increasing punishment for unclean care.

It's not medical's job however, to scrub the floors. That's a janitor's job. I don't mind a little bit of job crossover, which is why I don't object to the spray bottles of space cleaner sitting around, but as CMO I often have to be the one cleaning up medbay. I'd prefer to just let the janitor have access and clean the place as able so I can stay focused on medical care.

> That's the big problem I have with it--it's essentially a "hyper efficient, autonomous jobs are the best", which that has clearly demonstrated, in the past, that this can and does cause interactivity problems (ie: see current R&D).

> hyper efficiency is not a desirable thing.

The janitor has one job, and one job only: clean. Being efficient at it will only be a benefit. That said, giving access to medical is hardly "hyper efficient"

R&D is a problem because it's being abused. It's not a hyper efficiency problem, it's an abuse of mechanics problem. Or at least that's how I see it. I couldn't care less if someone is finishing R&D in 10 minutes; it is a horribly designed shit job that is hated, boring, and should be shitcanned. Research levels are something that should be rewarded as the science department performs their jobs doing tasks those players actually enjoy; right now it's basically a case of "not it!" if you don't get a player who actually wants to do that shit job.

**Comment by Anticept** [comment]
I just got linked to this: https://github.com/vgstation-coders/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/game/objects/items/devices/deskbell.dm

It has caught my interest, and it seems to be a much, much better solution to port that. Though it's beyond my skill level at this time and I'm going to be busy for a month before I can really sit down and learn this.

**Comment by Birdtalon** [comment]
While I largely agree with your PR, as we were discussing on discord. I believe the main areas of Medbay are areas that should be more open and accessible for all crew as it is the principle place to get yourself healed up and being stuck outside because you almost force one player to AFK at the front desk and wait for people is never pleasant.

However I must call you out on this statement, which I have to note my overwhelming disagreement with.
>They shouldn't be patching anyone up. It's a janitor. We shouldn't be using this as a design consideration except in the most extreme circumstances.
Players being able to take on multiple roles as and when required is absolutely a design consideration if we want to maintain a game in which players have freedom to play without being restricted by game mechanics which they cannot cross.

Other than that. Sure I like this PR.

**Comment by Anticept** [comment]
> Players being able to take on multiple roles as and when required is absolutely a design consideration if we want to maintain a game in which players have freedom to play without being restricted by game mechanics which they cannot cross. This is actually quite fundamental if we wish to remain appealing to the largest group of players on SS13 and continue to compete,

Which goes against the ongoing roleplay considerations. This is one of the sources of a lower standard of roleplay; people aren't playing their roles, they are playing everything. It SHOULD NOT be considered.

**Pull request closed without merging**
