### PR TITLE
Increase range of ERT skin tones

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
Also adds a few common hispanic/asian last names to the list of possible last names. And removes duplicate ones (whoever made this list was huge fan of Bill Murray).

### CODE REVIEW

**Comment by Birdtalon** [comment]
I hope Donald Trump doesn't see you adding all those Hispanic names to ERT members!

**Comment by Tayyyyyyy** [comment]
When Nanotrasen sends their ERTs, they're not sending their best. They're unrobust, they're shitcurity, they're greytiders. And some, I assume, are good people.

**Comment by Ty-Omaha** [comment]
Brb building a wall

**Comment by KingPhilipIII** [comment]
Make the Cyberiad great again.

**Comment by RyanSmake** [comment]
*Rascism intensifies*

**Comment by taukausanake** [comment]
Just out of curiosity, _and purely such_, do we have darker skin tones for ERT or prior to this are they all white?

**Comment by LightFire53** [comment]
RNG hair and skin for ERT when

**Comment by Tayyyyyyy** [comment]
@taukausanake before, the code for ERT skin tones picked between these: `-50, -30, -10, 0, 0, 0, 10`

Which, to me, looked like: tan, kiiiiinda sorta tan, white, white, white, white, white 😄

For reference, this is skin tone -50:

middle

Here's -120:

darkest

**Comment by granodd** [comment]
I wonder if there's any Russian ones in there? Probably not, what with the whole CCCP thing. Very nice though.

**Comment by Tayyyyyyy** [comment]
@granodd There are a few Russian names in there! This list of names is really interesting because I think it predates the server split. tg and paradise have the exact same list of last names, except tg has Goebbels 😒

Anyways, I generated some stats on how this changes the distribution of the nationalities of last names:

| Name  | Before | After |
| ------------- | ------------- | --- |
| United States | 411 | 414 |
| Germany | 30 | 30 |
| England | 29 | 29 |
| Mexico | 1 | 29 |
| India | 13 | 16 |
| Russia | 12 | 12 |
| Nigeria | 8 | 8 |
| Brazil | 8 | 8 |
| China | 1 | 7 |
| South Africa | 7 | 7 |
| France | 6 | 6 |
| Japan | 0 | 5 |
| Vietnam | 0 | 5 |
| Italy | 4 | 4 |
| Ghana | 3 | 3 |
| South Korea | 0 | 3 |
| Philippines | 2 | 3 |
| Bangladesh | 1 | 3 |
| Indonesia | 3 | 3 |
| Australia | 3 | 3 |
| Canada | 3 | 3 |
| Haiti | 2 | 2 |
| Algeria | 2 | 2 |
| Pakistan | 2 | 2 |
| Netherlands | 2 | 2 |
| Spain | 1 | 2 |
| Kenya | 1 | 1 |
| Israel | 1 | 1 |
| Nepal | 1 | 1 |
| North Korea | 0 | 1 |
| Peru | 0 | 1 |
| Egypt | 1 | 1 |
| None | 1 | 1 |
| Northern Ireland | 1 | 1 |
| Zimbabwe | 1 | 1 |
| Ukraine | 1 | 1 |
| Ireland | 1 | 1 |
| Czech Republic | 1 | 1 |
| Greece | 1 | 1 |
| Uganda | 1 | 1 |
| Hungary | 1 | 1 |
| Austria | 1 | 1 |
| Malaysia | 0 | 1 |
| Poland | 1 | 1 |

**Comment by Tayyyyyyy** [comment]
And just for fun, here's the list of the top 10 weirdest last names in SS13 (least popular in the world):

| Name  | Pop |
| ------------- | ------------- |
| Eckhardstein | 0 |
| Sealis | 1 |
| Aggley | 1 |
| Joghs | 1 |
| Sidower | 1 |
| Rathens | 1 |
| Sulyard | 1 |
| Digson | 2 |
| Jyllian | 2 |
| Knapenberger | 2 |

**Comment by taukausanake** [comment]
> Eckhardstein

NOW HOLD ON THERE. I have a character that uses that exact same name. It was the first character I made when joining the server (first time returning to SS13 in general) and I like him! Kind of weird that it's the only one with a 0 though

**Comment by Tayyyyyyy** [comment]
Nice! You got the only "made up" name. I was surprised too. I totally thought "Staymates" was a made up last name, but nope, turns out it's totally real?! Now I'm curious where this original list of names came from.

**Pull request merged**
