### PR TITLE
Laser Projectile Sprite Changes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This changes the *laser* projectile sprites back to what they originally were. They have been altered a bit so they behave properly with our current pixel-projectile system.

This does *NOT* impact pixel projectiles one bit or their functionality; this only changes the sprites. Likewise, it doesn't delete the currently used sprites; they'll be retained for future *potential* use.

This also does not touch the bullet sprites

Why the Change? 

- Physically the current sprites are a bit unrealistic; they're a blob with a phase out tail on them
- The current sprites are dull and muted and do not show up well to players
 - Old pulse even has a flashing animation to it.
- Current laser sprites are inconsistent with other laser sprites
- Old sprites better communicate direction and location, on the fly, due to their bright and vivid colors

Gifs:

Changing to:
yay
Current (on live):
crappy

Related
- Updates the red laserpointer icon so it doesn't have a weird grey-ish white center.

### CODE REVIEW

**Comment by tigercat2000** [comment]
can we please add a note to the contribution guideline that sprite PR's should include a screenshot :V

**Comment by Fox-McCloud** [comment]
Can't really get a pic--but will get a crappy gif up soon.

**Comment by orelbon** [comment]
can the laser sprite get a bit of white in the middle so it looks hotter.

**Comment by Fox-McCloud** [comment]
Don't think that personally communicate things very well, @orelbon 

It has similar problems to the current one; it's too faded and not well enough defined; with projectiles, generally the simpler they are, the better; they exist for only a few moments and quickly disappear; they need to catch your eye, but a huge amount of detail is rather pointless.

**Comment by FalseIncarnate** [comment]
:+1: for lasers actually looking like lasers and not some sort of photon torpedo. Too bad we can't have continuous beams too, so that lasers actually are beams and not pulses.

**Comment by Fox-McCloud** [comment]
@FalseIncarnate 

Eventually I'd like to see Bay's laser overlay system, but that's for another day.

**Comment by orelbon** [comment]
What does bays looks like?

**Comment by Fox-McCloud** [comment]
Like the top one.

**Comment by orelbon** [comment]
yeah that one does look better, looks more lasery

**Pull request merged**
