### PR TITLE
Remaps and Refines the Farragus Science Asteroid

### PR DESCRIPTION
**Pull request by Fordoxia**
## What Does This PR Do
This PR remaps the Farragus Science Asteroid.

### Important changes
- **Maintenance expansion**: Science maintenance has been enlarged and now fully encircles Research, removing the cul-de-sac that used to exist below Toxins. 1-tile wide hallways have been eliminated. The mostly featureless tunnels have now been populated with rooms and clutter that is themed around the science department. Airlocks and vents have been added throughout to make it harder to vent the atmosphere from a single breach. The solar array airlock and SMES rooms have been merged.
- **Relocation of the Electronics Den**: The electronics den has been moved from Service maintenance to Science maintenance in order to consolidate the theming. It has been expanded to include a small morgue area and is now equipped with more substantial tools.
- **Redesign and Expansion of Research**: Most rooms are now at least slightly larger. Science chemistry has been completely redesigned and placed into the area formerly occupied by the experimentor chamber. The experimenter itself now has a dedicated laboratory room which is accessible to anyone with science access. The room outside scichem is also on general science access in order to allow quick access to maintenance. Xenobiology has been expanded and given additional camera coverage. Toxins has been shifted outwards to make room for a maintenance checkpoint.
- **Relocation of the Escape Pod**: The escape pod has been relocated from the main hallway a short way into maintenance, matching the other asteroids. 

### Other changes
- **More Separation of Science and Service**: The airless sand connecting the science asteroid with the service asteroid has been mostly removed, more clearly delineating the boundaries between the two areas and giving a better view from the space bridge.
-**The AI Upload Slightly Moved**: The AI upload has been moved slightly east so there is now 2 tiles of rock between it and Robotics. The hidden mining room also was moved by the same amount as well.

## Why It's Good For The Game
Despite being on the biggest station, science is quite cramped and several amenities that all the other stations have are absent. This gives more usable space to researchers.

Fully encircling science with accessible tunnels will help increase maintenance connectivity, making it a better experience for antagonists, security, and maint explorers alike. Adding airlocks to maint ensures that a tiny hole doesn't have the ability to space ALL of maints.

The addition of vents and pipework makes the asteroid easier to navigate by ventcrawling, which can still easily be blocked off by diligent crew.

It is once again possible to mine around the entire perimeter of the AI upload without breaching into Robotics.

The locations within science maintenance are now a lot more varied, breaking up what used be a rather dull one-way hall into a much more thematic and interesting series of spaces that mostly carry the identity of the science department.

## Images of changes
image
image
image
image
image
image
image
image
image
The area that the electronics den was formerly located has been backfilled with asteroid rock. Further mapping attention shall be given to service in a dedicated PR.
image

## Testing
- [x] Lighting is good.
- [x] Full departmental AI camera visibility.
- [x] Airlock access verification.
- [x] Ancient rock fully encloses the minable areas of the asteroid.
- [x] Verify all 3 MULE delivery points in science function correctly.
- [x] Verify the escape pod still launches correctly. 

## Changelog
:cl:
tweak: The Farragus Science asteroid has been remapped.
tweak: The Farragus Science escape pod has now been relocated inside science maintenance.
tweak: Farragus Science Maintenance now fully encircles the department.
tweak: Farragus Science Maintenance has had multiple new rooms added.
tweak: Farragus Electronics Den has been moved from Service to Science maintenance.
/:cl:

### CODE REVIEW

**Comment by Fordoxia** [comment]
> You moved all the APCs within the department, this is against the standard established for cere.

I was told by Warriorstar that we are to move APCs out of maint (as has been done in their cargo remap) because we don't want maint APCs anymore due to balance reasons.

**Comment by S34NW** [comment]
> > You moved all the APCs within the department, this is against the standard established for cere.
> 
> I was told by Warriorstar that we are to move APCs out of maint (as has been done in their cargo remap) because we don't want maint APCs anymore due to balance reasons.

After discussion internally we think this should be done in one go for all departments to avoid major confusion, as opposed to bit by bit.

**Comment by S34NW** [comment]
Apologies if that was not properly communicated

**Comment by Fordoxia** [comment]
> Apologies if that was not properly communicated

Will do.

Due to the change in layout for some rooms, not all the APCs can be put back into their original positions. Should I keep those in their current altered locations?

**Review by warriorstar-orion — CHANGES_REQUESTED** [review]
Can you put walls on the ends of the asteroid struts, like this?

2024_08_02__16_37_45__paradise dme  cerestation dmm  - StrongDMM

**Comment by Fordoxia** [comment]
> Can you put walls on the ends of the asteroid struts, like this?

It is done.

**Review by S34NW — APPROVED** [review]
I'm pretty happy with how this looks now, good work.

**Review by warriorstar-orion — APPROVED** [review]

**Review by Burzah — APPROVED** [review]

**Pull request merged**
