### PR TITLE
Removes Organs

### PR DESCRIPTION
**Pull request by Fox-McCloud**
I decided to remove organs as they were unbalanced and mostly just full of empty processes that didn't do anything anyways.

HUE

what this actually does: removes an unused file that's empty.

### CODE REVIEW

**Comment by Plotron** [comment]
What about the chems that heal organ damage?

**Comment by Fox-McCloud** [comment]
>What about the chems that heal organ damage?

Maybe in a later PR, for now though, they don't hurt anything by being in.

**Comment by Plotron** [comment]
Does it mean that robotic heart will stop existing/making a difference?

**Comment by CrAzYPiLoT-SS13** [comment]
I really hope this is a joke PR...

**Comment by Xperia15** [comment]
I am highly against this. You are rushing PR way too fast.

**Comment by Earthdivine** [comment]
Uh, I dont know what to make of this because wouldn't it cause big issues with #2903?

**Comment by Robertha89** [comment]
this pr amuses me, it removes the old empty organ code file, actual organs are not even touched in it.

**Comment by Earthdivine** [comment]
Darn it fox.

**Comment by Regen1** [comment]
Goddamnit

Rused by the slick mr.fox again bois

**Comment by CrAzYPiLoT-SS13** [comment]
Gr8 b8 m8

**Comment by MindLeaker** [comment]
This is a terrible idea, it removes an integral part of Surgery that's meant to be there to necessitate people to get to Surgery quickly. Not to mention this causes conflicts with things such as the new revolver nerf, that was done specifically because of ruptured lungs being a thing.
:-1:

**Comment by Regen1** [comment]
Should also look into removing all damage except brute, I think it's taking up way to much space in our code, and we could use it for better things such as more fluff items and toys in game.

@TheDZD Should take a look at the carbon code, there's loads of things that makes the server run slower there, see if you can't remove some shit we don't need.

**Comment by Aurorablade** [comment]
Is it bad I am giggling?

**Comment by Spacemanspark** [comment]
We should remove atmos, walls, floors, and the security department, while we're at it.

**Comment by CrAzYPiLoT-SS13** [comment]
Security department - worst thing that's ever happened to SS13 and this server

**Comment by Crazylemon64** [comment]
I'm wondering how this is even compiling...

**Comment by mrsdobbins** [comment]
Nice meme.

**Comment by Fox-McCloud** [comment]
HUE

**Comment by LittleBigKid2000** [comment]
WE'VE BEEN BAMBOOZLED

**Pull request merged**
