### PR TITLE
You can now light cigarettes off of burning mobs

### PR DESCRIPTION
**Pull request by Crazylemon64**
:cl:Crazylemon
tweak: You can now light cigarettes off of burning mobs.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Hah, I really dig that flavour text. Great work

**Comment by FlattestGuitar** [comment]
Savage.

**Comment by Gummin** [comment]
:+1: Need to drag around my victims burning corpse now.

**Comment by CrAzYPiLoT-SS13** [comment]
Absolute madman.

**Comment by NTSAM** [comment]
Finally, a use for my fireplace monkeys!

**Pull request merged**
