### PR TITLE
Spirit Boards! (from -tg-)

### PR DESCRIPTION
**Pull request by tigercat2000**
Ports Spirit Boards! (tgstation/-tg-station#4633)

Copied description:
`Known more popularly by the brand name of Quija board, spirit boards let a group of people communicate with the dead, maybe!`
`To use:
The area must be dimly lit.
At least 2 active people must be standing around it.`
`Letters can be selected by either the live players or by ghosts.`
`"Are you moving it??"
"No way, man!!"`
`http://i.imgur.com/9IEpf2u.png`

Basically, this adds Ouija boards (not actually obtainable for non-admins), which allow ghosts (and people) to move the planchette, provided that 
* Two living, active, unrestrained mobs are next to the board
* The Board is located in a dark room

While one can claim 'but metaaa', I feel it should be pointed out that either of the mobs next to the board can also interact with it, and there is 0 ways to tell the difference between the mobs and an actual ghost. Not to mention ghosts screwing with other ghosts, and ghosts just tending to lie.

### CODE REVIEW

**Comment by SamCroswell** [comment]
:-1:
A -really- bad idea, in my opinion.

**Comment by tigercat2000** [comment]
Also, a note: As of right now, it is only avalible to admins- it hasn't been added to the map or.. well anywhere by this PR. Mainly because it may need further discussion about player avalibility

**Comment by fj45** [comment]
While a little fun...seems a bit pointless.

**Comment by ZomgPonies** [comment]
I'm alright with this, since they are admin-spawned I can imagine some spoopie events using them.

**Pull request merged**
