### PR TITLE
Removes Unused Gamemodes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Removes two unused gamemodes from the code.

Borer is copy-pasted from meme and doesn't have enough content to stand on its own feet (borers are better suited as an event anyway)...and I'm not sure it even works properly.

Xenos is completely broken; the Xenos required their own shuttle and special mechanics to even work, as a game-mode, which both no longer exist. Not only that, event Xenos have a number of hefty balance issues---having them as a game-mode, where Xeno resources are guaranteed, is only bound to end in the Xenos winning the vast vast majority of the time (and in the short time this game mode did work and was played, that's exactly what happened).

Related
- Updates example config to be more accurate to the server

Not changelogged because this doesn't impact anything visible, one bit.

### CODE REVIEW

**Comment by TullyBurnalot** [comment]
RIP mem-I mean, borers.

**Comment by Fox-McCloud** [comment]
>RIP mem-I mean, borers.

They're still around, and still and event, please don't imply otherwise.

**Comment by LittleBigKid2000** [comment]
>Borers are still around, and are still and event, please don't imply otherwise.

WHAT DO YOU MEAN YOU'RE REMOVING BORERS?

:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by Taaketa** [comment]
No one like Borings.

**Comment by TullyBurnalot** [comment]
@Taaketa Borers can be fun if played adequately. Just... takes a while to find a good one.

**Comment by Taaketa** [comment]
@TullyBurnalot Any time I've played Borer and spoken to someone I've managed to slip into. Straight to the vending machine and hot chocolate they down.

**Comment by taukausanake** [comment]
I once got a borer in me as captain and no one managed to save me until after shuttle left. It made all borers on the station crew and illegal to harm them. That was a painful round for me

**Pull request merged**
