### PR TITLE
Adds Tajaran hiss.

### PR DESCRIPTION
**Pull request by iantine**
## What Does This PR Do
Adds Tajaran hiss, not pitch-variable. Can be made soundless via a muzzle, similarly to unathi hiss. Tested to work.

## Why It's Good For The Game
Brings Tajaran up to date with other species as far as having sound-specific emotes.

## Changelog
:cl:
add: Adds Tajaran hiss.
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
_somethingsomethingreeeefurries_

I'm skeptical on this. That is all

**Comment by SteelSlayer** [comment]
I don't really like this either. But, if they are to get some new audible emotes, they should be better quality.

**Comment by iantine** [comment]
Asking for concrit to take this pr in a new direction. 

If we were to give Taj a single sound, what would it be? I'm looking at getting rid of meow and purr and giving them a hiss, but replacing the current hiss sound in the pr with something clearer and more audible. Thoughts?

**Comment by SteelSlayer** [comment]
My thoughts exactly. I think giving them a hiss and getting a a cleaner sound would be fine. I just didn't like the meow and purr.

**Comment by iantine** [comment]
Hopefully a bit better this time around.

**Comment by Aurorablade** [comment]
I would actually LIKE the meow and purr or at least the meow. We have other odder sounds on other races. Slime squish anyoneone? I have honestly be wanting a meow for ages just can't get a good sound for it.

**Comment by iantine** [comment]
Closing this, the sound is still mediocre. I'll come back and look at giving Taj sounds when I have better-quality sounds and ideas for sounds to give them.

**Pull request closed without merging**
