### PR TITLE
Ports TG's Cursed Hearts

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Ports over @RemieRichards cursed hearts from TG.

The cursed heart is a wizard item that heals a massive 25 oxygen, 25 brute, and 25 burn per use...it just has one catch, if you miss out on pumping the heart, you'll lose 100 blood.

Pumping is done by clicking the heart's action button; a successful pump will restore 50 blood.

You can't spam the heart-pump or heart-pump too soon--you can click up to 1 second before the time you'd normally lose blood.

Grab it as a defensive item on the wiznerd's spellbook for 1 point.

Changes from TG:

- Species with no blood OR exotic blood cannot utilize this organ (outside of adminbus).

:cl: Fox McCloud
add: Adds in cursed wizard heart, purchase it from the wizard's spell book for 1 point, but be wary of not keeping the heart beating...
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
The title of the PR is misspelled

**Comment by Fox-McCloud** [comment]
Aare yoou impling thet I cannt speel vury wheel, @Tastyfish

**Comment by Plotron** [comment]
... pumping the heart? What da fak?!

Anyway, sounds interesting...

**Comment by KasparoVy** [comment]
Lmao, this is going to be a pretty hilarious (and hella interesting) tool for wiznerds to use. Seriously looking forward to some cursed heart antics.

**Comment by RemieRichards** [comment]
Do you guys have the little heart beat monitor display for health? if so I'll just say it's very useful for knowing when to pump the wizard's cursed heart (the 6 second one) :P

**Comment by Fox-McCloud** [comment]
@RemieRichards 

We do.

**Comment by RemieRichards** [comment]
Pay close attention to it then :P

**Pull request merged**
