### PR TITLE
Moves the clown's office to the permabrig

### PR DESCRIPTION
**Pull request by LittleBigKid2000**

### CODE REVIEW

**Comment by monster860** [comment]
Is this a meme pr?

**Comment by Chakirski** [comment]
:+1: :x: :100:

**Comment by Xantholne** [comment]
Absolutely required

**Comment by Kevak** [comment]
This is hilarious. Yes.

**Comment by Earthdivine** [comment]
Right where he belongs.

**Comment by FlattestGuitar** [comment]
*you hear a sad honk in the distance*

**Comment by Davdichan** [comment]
Needs a disposal chute to the execution chamber.

**Comment by Necaladun** [comment]
The original office had shutters to lock it down when the brig lockdown was on. Some funhater removed that.

**Pull request closed without merging**
