### PR TITLE
Tweaks DeltaStation AI Sat

### PR DESCRIPTION
**Pull request by LightFire53**
## What Does This PR Do
 Tweaks the layout of the AI core chamber on DeltaStation to provide more security to the AI's.

## Why It's Good For The Game
 @Denthamos was mentioning that the primary AI core didn't really receive proper turret protection in the current layout, and as a result of a discussion we came up with a new layout that provided the protection while securing the supplemental AI cores as well. This new layout is the one proposed by @procdrone below, as Denthamos likes that approach and has suggested to possibly moving the other maps to something similar.

This also adds a few missing pieces, like an air alarm and a light switch to the main core room, and light switches to the antechamber and telecomms

## Images of changes
 

**Current**

image

**New**

image

## Changelog
:cl:
tweak: DeltaStation AI Chamber now has increased security
/:cl:

### CODE REVIEW

**Comment by S34NW** [comment]
4 AI slots?

**Comment by LightFire53** [comment]
> 4 AI slots?

AI statue, 2 triple AI, and 1 standard

**Comment by LightFire53** [comment]
image

**Comment by S34NW** [comment]
> > 4 AI slots?
> 
> AI statue, 2 triple AI, and 1 standard

sus

**Comment by procdrone** [comment]
The old one looks better, to be honest.

**Comment by Denthamos** [comment]
@procdrone One of the main issues with the old one is the primary AI has no way to defend itself from an intruder direction in front of its core as the two reinforced walls in the corner blocks laser shots.  You could say "just replace them with windows" but then the turrets would hit the core as well.  Keeping to a standard of turrets facing pathways along side AI core sightlines is how this design has come about.

If you have an alternative idea to solve the issue then feel free to post a design that would.

**Comment by S34NW** [comment]
Will review this in the next 24-48 hours

**Comment by procdrone** [comment]
> @procdrone One of the main issues with the old one is the primary AI has no way to defend itself from an intruder directly in front of its core as the two reinforced walls in the corner blocks laser shots. You could say "just replace them with windows" but then the turrets would hit the core as well. Keeping to a standard of turrets facing pathways along side AI core sightlines is how this design has come about.
> 
> If you have an alternative idea to solve the issue then feel free to post a design that would.

This is my idea to preserve the original design and keep it "in line" with other stations. (not that change from the standard isn't welcome)

It is my belief that "triple AI" mode shouldn't dictate the whole design, and I simply don't like it (to clarify, as long as the design proposed by LightFire is fulfilling the desired function, it does NOT matter if I like it or not, I'm just a pleb git commenter trying to share my opinion).

It's simply my spin on the redesign, to increase security. (I apologize in advance, im a MS Paint mapper)

I've tried to contact Denthto to establish what exact issues were, but sadly it appears I contacted in a busier time, and the PR itself doesn't go into details about what these issues exactly are, so this is purely my speculation.

issue

Turrets, these are the presumed blindspots that make approaching the AI easier (and if you get into the "internal airlock", completely safe).

So the idea itself, based on these presumptions would be this.
solution
(the squares in paint are optional additions to increase security even more, apologies, but were too lazy to prepare a second image)
(all bases covered. no turret can shoot directly at AI while allowing protection to most blindspots)

DISCLAIMER, I am only posting this because Dent asked me for my alternative, I initially only wanted to share that I didn't like the triple AI dominated design initially, so please, if you find my idea not fulfilling the goal or unwelcome, feel free to ignore me. I by no means intend to presume I have superior knowledge of the issue or know all the answers. I am just a vocal idiot.

**Review by S34NW — APPROVED** [review]
LGTM

**Review by S34NW — APPROVED** [review]
this looks fine now, there could always be a third intercom on the main AI position but not a biggie

**Review by AffectedArc07 — APPROVED** [review]
I dislike the lack of a liquid slipper at the entryway now but I aint about to mergeblock a PR over something so minor

**Pull request merged**
