### PR TITLE
Fixes Courtroom camera network to Toxin and Research Consoles

### PR DESCRIPTION
**Pull request by Jovaniph**
This is my first pull request. I thought I would get my feet wet and maybe help contribute to the server a bit here and there.

This PR fixes the problem which the Courtroom camera network was linked to the Toxin and Research camera network. I simply removed those two networks from the list, tested it, and it seemed to work on my end. I hope this doesn't break the game. I only made one simple change.

Don't know how to do the CL thingy so you might have to bother me here or on Discord about it.

### CODE REVIEW

**Comment by pinatacolada** [comment]
wont this break the toxins camera monitors? the ones used to view the bomb range and the test cage thing?

You should set the court room cameras to the SS13 network instead.

Also this doesn't look like it's map merged

**Comment by Jovaniph** [comment]
Well that's what I did...The courtroom had the network to SS13, Toxin, and Research...I just removed Toxin and Research from the courtroom camera's network. Now it only has SS13.

**Comment by pinatacolada** [comment]
Ah I understood you removed the entire toxins network, nevermind then

**Comment by Luthix** [comment]
Needs to be mapmerged and it's more easy to create branches on your fork to make your changes on so that your master branch stays the same as the paradise master. I can help on discord if you want.

**Comment by Jovaniph** [comment]
Yeah maybe I should of done something lighter with dm files instead of an entire map merge. I'll do something else instead. Maybe someone else will fix my OCD problem with that camera network.

**Comment by Luthix** [comment]
Well the whole dmm file will get edited there's no way around that but the mapmerge tool will change those 18000 revisions to 1 or 2 you can do this!

**Comment by Markolie** [comment]
I'll take care of this in https://github.com/ParadiseSS13/Paradise/pull/6693

**Comment by Markolie** [comment]
Sorry :(. Plenty of bugs left to fix though!

**Pull request closed without merging**
