### PR TITLE
Removes Mining Guardian from Necropolis Chests

### PR DESCRIPTION
**Pull request by Inadvizable**
## What Does This PR Do

Title.

## Why It's Good For The Game

Guardians are 12 TC items for traitors - 60% of a traitor's telecrystals, and S-class. They are also a wizard item worth 2 points - 20% of a wizard's points. They are also, apparently, possible tendril loot. The thing that most moderately robust people learn to kill after a few rounds in mining. Great. 

What use do guardians have for miners? Well, they can use Protector to cheese megafauna, or support for healing/teleportation... the others are not really useful for anything else than killing people. The rest of the crew has no use for the rest either, except for security and antags. Security should not, realistically, be running around with what's considered S-class contraband when used by traitors. Antags should probably not get 12 TC from a tendril.  Sometimes, command gets the deck from a miner Just in Case™, so they can absolutely obliterate an antag in "self defense". None of these things are good for game balance. The removal of this has been floated as an idea over and over for years, time for someone to pull the trigger.

## Changelog
:cl:
tweak: Tendrils now do not drop guardian decks.
/:cl:

### CODE REVIEW

**Comment by Inadvizable** [comment]
> I'm not against removing guardians, but giving miners access to infinite fireballs is kind of replacing one problem with another. It's a slim chance but damn.

Charge has a high chance to permanently decrease max charges of a wand, and yeah, the miner would have to get both items to begin with. That or wand of slipping. If this ends up being a problem it can still be changed, though.

**Comment by Denthamos** [comment]
Personally, will be objecting to this for this reason - the spellbook of charge has such a miniscule impact on anything mining related that its use is basically null outside of very rare and specific circumstances.  Loot miners get from the tendrils should benefit them in some way in mining and on lavaland.

**Comment by Inadvizable** [comment]
> Personally, will be objecting to this for this reason - the spellbook of charge has such a miniscule impact on anything mining related that its use is basically null outside of very rare and specific circumstances. Loot miners get from the tendrils should benefit them in some way in mining and on lavaland.

I can replace it with something else, or nothing at all (which just means they get a higher chance for all other loot) if that's preferable. I added spellbook of charge because it's something they could give to the station instead of hoarding all loot and never interacting with anyone.

**Comment by Inadvizable** [comment]
@Denthamos I have removed the spellbook of charge from the loot table. It now contains 25 items, rather than 26.

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
