### PR TITLE
Powersink costs 1 TC more

### PR DESCRIPTION
**Pull request by DGamerL**
Alright, as I've given this a bit more thought and responded to feedback, I have now edited the PR
## What Does This PR Do
Increases the price of the powersink by 1 TC

## Why It's Good For The Game
Powersink costs 1 TC more, makes it so you can only buy per uplink in an albeit crude way.

## Testing
Yes

## Changelog
:cl:
tweak: The powersink now costs 11 TC
/:cl:

### CODE REVIEW

**Comment by AzuleUtama** [comment]
Hijack only items are almost always items that cause mass murderbone or destruction with no other real benefit, hence why they're only available to hijackers ordinarily.

Turning off the power for a while doesn't really fall under that category and no hijacker is ever going to invest TC into this when they have much more destructive options available.

**Comment by DGamerL** [comment]
PR and description is updated now

**Comment by lewcc** [comment]
I'll be real, I think you might want to re-open the PR with a different title; I get the feeling that most of the reactions and such are related to its previous form and it might be good to start anew if you're serious about this change

**Comment by Edan52** [comment]
I get what this does, but why?

**Comment by DGamerL** [comment]
Closing, and will reopen soonish so nothing of the first change will be taken with

**Pull request closed without merging**
