### PR TITLE
Greentext

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Chaplain can now select the appearance of his holy book to be that of a green book, aka greentext :stuck_out_tongue: 

:cl: Fox McCloud
add: Chaplain can now select a green book as his Bible
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
How meta

**Comment by Spacemanspark** [comment]
We get to validhunt chaplains now!

**Comment by johannhawk** [comment]
also a red book, and then a book with both.

**Comment by KasparoVy** [comment]
HIGH PRIORITY MUST MERGE NOW

ALL HAIL, ALL PRAISE, ALL GLORY TO THE GREEN TEXT

**Comment by Necaladun** [comment]
Memetext is the greater religion.

**Comment by Tastyfish** [comment]
All Hail Lord Validhunt

**Pull request merged**
