### PR TITLE
FEATURE FREEZE

### PR DESCRIPTION
**Pull request by Fox-McCloud**
We are now under a full feature freeze. It's time to chill out on the many feature and balance PRs that have cropped up. Mmaintainers, will really be trying to put a lot of the PR backlog on ice. During this frosty time, all balance and feature PRs will **not** be normally be accepted (Note, a SOLE exception exists for Fluff Items. We **will** accept fluff items during this freeze). This is a time for fixes and non-balance altering refactors. Cool off a sec, this won't be a complete and total freeze as it was last time. We will be instituting a points system whereby if you thaw 3 acceptable bugs or do 3  acceptable refactors* (or a mixed combo there-of), you can submit a feature PR if you so desire. If a major highly needed refactor can be submitted, but it has a minor balance implication attached to it, then we may consider it, but you should talk to either of the maintainers, first, before submitting it. I can't stress this enough, do not submit a major refactor that impacts balance without discussing it with us first; if you do, and it gets closed quickly, the fault lies with you for not discussing it with the maintainers first.

*What is defined as an acceptable fix/refactor is 100% up to maintainer discretion, at the end of the day. That said, what we are looking for in terms of meaningful fixes are resolving problems that are on the github or present as a major problem on the live server. Correcting a couple of minor spelling errors/spacing problem is not a meaningful fix (though we still appreciate it). Likewise, for refactors, changing something trivial (ie: making a single 4 line proc be absolutely pathed when it was previously relatively pathed) here, will also not be advised. These are not hard and fast rules--for example if you were to conceivably solve every single spelling error in the entire codebase, that would be meaningful. 

Along with this, submitting trivial issues to the Github ("a stop-sign sprite is 1/10,000th of a shade off from the official designated Federal Highway Administration's guide of the proper shade of red") then immediately fixing that trivial problem is, likewise, not likely to earn you any points for submitting a feature PR. Submitting actual bugs that are a negative legitimate impact on players, then fixing them, however, is acceptable.

Again, everything is ultimately up to maintainer discretion if you earn points towards a feature PR, so if you want to be sure, don't hesitate to ask either of us.

Existing PRs can and will be merged (feature or fix) and discussion will continue on them. Please note that attempting to circumvent the freeze by utilizing an pre-existing pre-freeze PR by expanding it dramatically outside of the scope of what the original PR submission was will be met with consequences; don't try it.

### CODE REVIEW

**Comment by Birdtalon** [comment]
❄️

**Comment by TravellingMerchant** [comment]
How long will the freeze be?

**Comment by Aurorablade** [comment]
The freeze will be until a backlog is cleared and/or we get enough other bugs and stuff fixed more then likely.

**Comment by Birdtalon** [comment]
Will you be making a list of things which you think are at the top of the priority list that need to be resolved? The issues tab is full of things from bugs which are trivial and things which haven't been able to be reproduced.

I'm happy to work on things but it would be good to have some direction about what kind of things you as maintainers want doing with regards to bugs etc.

**Comment by taukausanake** [comment]
I think this is messing a few labels

**Comment by Taaketa** [comment]
Approaching 100 PRs could see this coming a mile off and I'm not surprised.

**Comment by Agameofscones** [comment]
ice is nice

**Comment by KasparoVy** [comment]
Seems to be working out really well. It's been great seeing so many long-standing issues just knocked out one after the other in rapid succession. Lots of reviews ongoing, etc. etc.

Very good

**Comment by Citinited** [comment]
Yep, feature freeze plus a fourth maintainer has been really beneficial for the github. 10/10 would recommend 

Also I bet people are contributing so they can get back to meme feature PRs :smile:

**Comment by Fox-McCloud** [comment]
The freeze has officially ended.

**Pull request closed without merging**
