### PR TITLE
[READY] [SQL CHANGE] P A R A L L A X

### PR DESCRIPTION
**Pull request by Tayyyyyyy**
**What does this PR do:**
See #11342

**Changelog**:
:cl: AffectedArc07
add: P A R R A L A X (That fancy space thing)
/:cl:

### CODE REVIEW

**Comment by farie82** [comment]
Is permission given by the previous coder for the revival?

**Comment by Tayyyyyyy** [comment]
Just to clarify for future reference, under AGPL, permission is unnecessary to copy or modify code. But yes I did check.

**Comment by AffectedArc07** [comment]
Allowed

Also conflicted

**Comment by Tayyyyyyy** [comment]
Closing this one. Will just add/cherry pick the sql changes to  #11615 when it's been test merged and approved.

**Pull request closed without merging**
