### PR TITLE
Fix #4793

### LINKED ISSUE #4793: Toggle Darkness as ghost changes other ghosts
**Problem Description**:
Toggling darkness while being a ghost (in my case observing) changes the icons of all other ghosts into the generic white ghost or naked human icon.

**What did you expect to happen**: 
To be able to see normal ghosts and ghost brains.

**What happened instead**:
Old sprite ghosts and naked males everywhere.

**Why is this bad/What are the consequences:**
Not bad, but it's a weird thing I noticed and counts as a bug.

**Steps to reproduce the problem**:
Join as observe. Toggle Darkness under Ghost tab.

**Possibly related stuff**: 
Wizard gamemode.

### PR DESCRIPTION
**Pull request by monster860**
:cl: monster860
bugfix: Fixes ghosts having a generic icon when darkness is toggled off
/:cl:

I didn't test this, but mostly because it's really late, and also it's kind of hard to get other ghosts to test this, but it should work

### CODE REVIEW

**Comment by tigercat2000** [comment]
IT'S NOT A FUCKING BUG

**Comment by monster860** [comment]
Sure it is.

**Comment by Fox-McCloud** [comment]
:+1: never liked the static ghost image.

**Comment by FlattestGuitar** [comment]
My dreams involve changing the weird clothes ghosts always get. Possibly something randomized? Wouldn't be too hard, would it?

**Comment by Spacemanspark** [comment]
:+1:

**Comment by KasparoVy** [comment]
Wierd ghost clothes? It's the tourist outfit, and the only way you can get it is by being an observer who never spawned in.

**Comment by Spacemanspark** [comment]
On Bay/ Polaris servers your ghost wears the gear from the highest setting occupation for that character.

**Comment by Krausus** [comment]
> I didn't test this
> it's kind of hard to get other ghosts to test this

Nah, you just need to make a second account to test with.

Doesn't work.

**Comment by Fox-McCloud** [comment]
@monster860 

Going to work on this futher?

**Comment by monster860** [comment]
This should work

**Comment by Krausus** [comment]
Let's see...

Yep. They're stuck facing south, but I think this is as good as it's gonna get.

While you're poking around in ghost code, could you set up the icons with the KEEP_TOGETHER appearance flag? It turns this
dreamseeker_2016-07-01_11-09-33
into how it's supposed to look
dreamseeker_2016-07-01_11-09-39
Though I think you need to tweak the alpha on the ghost image then, since setting that flag on the regular icon seems to stop it from inheriting the alpha.

**Comment by monster860** [comment]
And it is now PERFECT.

**Comment by Krausus** [comment]
I'm too busy to test this again right now, but don't you need to put KEEP_TOGETHER on the standard icon's flags, too?

**Comment by Krausus** [comment]
Alright, turns out KEEP_TOGETHER also has to be set on the ghost ima-- oh.

**Pull request merged**
