### PR TITLE
Adds many new Nanomobs to capture and battle with.

### PR DESCRIPTION
**Pull request by DesolateG**
Adds multiple new Nanomobs to the Nanomob Go! system and trading card game to battle with. 

Here are some examples of the new mobs you'll be able to see!

Look a wild Hewef!
dreamseeker_2018-03-18_07-35-10

Furweh is battling Fewher!
dreamseeker_2018-03-18_07-41-52

Boy they sure do level fast!
dreamseeker_2018-03-18_07-44-01

Oh this one thought he was going to go under the radar too.. not today!
dreamseeker_2018-03-18_07-35-28

:cl: Desolate
Feature: 16 new nanomobs to capture!
/:cl:

### CODE REVIEW

**Comment by Noober84555** [comment]
nice

**Comment by Spacemanspark** [comment]
This would be funny if I hadn't taken the title seriously at first :^(

**Comment by Aurorablade** [comment]
What did we tell you people about meme prs?

**Comment by taukausanake** [comment]
I think this is Clovermon level of fakemon now. We should keep pushing it.

In seriousness, I'd make at least one of these into a real one out of whatever amounts to respect. Hell, make one for each of the controversial SS13 people. Goofball Nanomob anyone?

**Comment by Aurorablade** [comment]
No. No and no.

**Comment by tigercat2000** [comment]
the feweh cabal has deemed this pr unacceptable. expect assassins shortly.

**Pull request closed without merging**
