### PR TITLE
Adds a 6th Vulpkanin tail option

### PR DESCRIPTION
**Pull request by Allfd**
Adds a 6th Vulpkanin tail option.

4e1635013757818cad65403956b2887d

:cl: Alffd
rscadd: Added a 6th Vulpkanin tail option.
/:cl:

### CODE REVIEW

**Comment by Spacemanspark** [comment]
You did something wrong.

**Comment by Allfd** [comment]
Wow that was fast.

**Comment by FlattestGuitar** [comment]
You want to make a new branch and make a PR from there, without the old commits.

**Comment by IcyV** [comment]
I'm not sure I see the difference to the other tails.

**Comment by Spacemanspark** [comment]
As for the PR itself; kind of agreeing with IcyV.

**Comment by Fox-McCloud** [comment]
you'll want to create a new branch on github, make the changes and push the changes to that branch--then make a pull request off of that.

You generally want to keep master clean.


:+1: a shorter tail is nice--kinda looks like a German Shepherd's tail.

**Comment by Allfd** [comment]
Closing,

Will reopen after cleaning up the commit history.

**Pull request closed without merging**
