### PR TITLE
Heavily reduces explosion smoke amounts

### PR DESCRIPTION
**Pull request by DGamerL**
## What Does This PR Do
Heavily reduces the amount of smoke that appears from explosions
Also makes sparks disappear faster

## Why It's Good For The Game
I think that one wizard round with a fireball showed that these were very overtuned

## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/108773801/29cfe553-2fdc-465b-9c75-203cee493b5b

## Changelog
:cl:
tweak: Explosions now release a lot less smoke
/:cl:

### CODE REVIEW

**Comment by Dafrek** [comment]
Having them a bit smaller is nice, there are also some things that use the explosion effect that seem really out of place, such as changelings head-slugging.

**Comment by spacegeese** [comment]
> there are also some things that use the explosion effect that seem really out of place, such as changelings head-slugging.

changelings whenever they use last resort
th-54927066

**Comment by DGamerL** [comment]
> Having them a bit smaller is nice, there are also some things that use the explosion effect that seem really out of place, such as changelings head-slugging.

Will fix that in a different PR

**Review by Contrabang — APPROVED** [review]
send it

**Review by Burzah — APPROVED** [review]

**Pull request merged**
