### PR TITLE
Power Fist Rework

### PR DESCRIPTION
**Pull request by SpringSkipper**
Reworks power fist to have only one power setting, more punches per tank, and much better knockback. It can also clamp to your arm like a proper power fist, and calls the normal attack routine to check for things like melee force bonuses.

## What Does This PR Do
Reworks the power fist quite heavily.

- now does 10 damage on hit when unpowered (or not worn), rather than refusing to attack at all.
- there is only a single mode; a wrench no longer does anything with it.
- does 15 damage on a hit while powered and worn; due to the knockback damage change, it also does an additional 13 damage if they collide with something. The knockback has been increased to 8 meters at a normal, reasonable speed.
- to be used properly, it must be clamped to your arm. This is instant and gives it antidrop, but it takes 3 seconds to take it off. It can still be used as a bludgeon while not clamped but only does toolbox damage.
- costs 2 moles of gas per hit, down from the absurd 9 moles of gas for the original at highest setting. This gives 8 punches when using a standard maintenance fire closet air tank. It still can't use the small emergency O2 tanks.
- comes pre-loaded with a standard O2 tank when purchased.
- now attempts an actual attack and respects things which modify attacks, rather than doing its own thing. This means it can be affected by things like Rod of Asclepius pacifism or the Bath Salts melee damage boost
- you can no longer punch yourself in order to fly.

I'm open to tweaking the exact values of this for balance.

## Why It's Good For The Game
The only thing worse than no option is a trap option. The current power fist is more or less a waste of 8 TC

## Testing
Spawned it in with a traitor uplink, bapped various mobs with it both carbon and otherwise. It doesn't knock back simple mobs, but I'm not sure how I would make it do so and I fear it would break something if it did. Tested adding/removing air tank, made sure a shield fully blocks it, tried wacking people with it in all configurations to be sure nothing would crash.

## Changelog
:cl:
tweak: Reworks power fist to be more viable and less wonky.
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
> Your PR has been put on hold as your GitHub account is not linked to a Paradise forums account.
> 
> Please link your account at https://www.paradisestation.org/forum/custom/link_github_account.php
> 
> _Headcoders may ignore this in specific circumstances (Minor fix PR, trusted contributor from another codebase, anything at their discretion)_

PR author has now linked their account

**Comment by Bm0n** [comment]
I don't like the fact that this PR is halving the max damage of the power fist, it's already a very niche item and its main draw was the massive amount of damage it could output in a short time which was limited by an air tank.

Also the no-drop thing is already being done by PR https://github.com/ParadiseSS13/Paradise/pull/18798

**Comment by Edan52** [comment]
This is being objected to due to the fact that another PR already exists to buff the powerfist, which was already approved of, and is preferred to this.

**Comment by SpringSkipper** [comment]
While I'm aware of the other PR, I'll point out that this PR is much more comprehensive with 80-ish line changes instead of just 5, nor are those empty changes. The two are also not compatible, since this is a full rework and not just a few changed variables.

Importantly, this PR handles edge cases like dropping the powerfist due to limb removal, and integrates normal attack logic into the powerfist hitting things instead of being some sort of weird, melee-range spell that ignores shields, melee bonuses, the pacifism trait, and so on. It also knocks things back at a reasonable speed in comparison.

The reason for the change to damage is the recent-ish change to knockback that makes knockback cause damage when you collide with things. I could buff it up to above 30 damage if people really think that's necessary, but at 40+ damage it becomes a one-click pain slow against unarmored enemies which seems extreme.

Keep in mind it's already a one-click knockback, knockdown, and disarm WITH NODROP
With that in mind I don't feel like it needs more damage than the esword just because the esword has block and better armor penetration. The esword **should** be better at damage.

That said, I'm not really sure who makes these sorts of balance decisions in any official capacity.

**Comment by hal9000PR** [comment]
this has 3 balance team objections and the alternate PR was merged. feel free to re-open a PR with the QOL changes.

**Pull request closed without merging**
