### PR TITLE
Adds Medical beret

### PR DESCRIPTION
**Pull request by Xantholne**
Medical beret now available via loadout. 
3c70c170ed22f9a1f9539562fd594546
Changed from previous CMO style beret to be an exact color scheme match with regular medical doctors, personally I think it looks even better now. Also features a medical cross to be easily distinquished from the CE beret even further which is a pure white as well.

🆑  Xantholne
rscadd: Adds Medical Beret available via loadout menu
/🆑

### CODE REVIEW

**Comment by Anoonki** [comment]
Perhaps make this one CMO unique (Like how the HoS and CE have their own unique on top of their departmental ones) and add a primarily white recolour for standard MDs and such?

Just for the sake of identifying by headgear/colour easier.
It'd be pretty simple to be mistaken for the CMO while wearing *that* shade of blue on you.

**Comment by Xantholne** [comment]
You already get mistaken as CMO by just wearing the winter coat, which is odd

**Comment by Anoonki** [comment]
Yeah, but that's at least *a little lighter* (Not to say it's not an issue too)
This is actually the exact same colour.

**Comment by Fox-McCloud** [comment]
If this is to follow the standard, then it would make more sense for these to be white or green and not blue.

We never made the transition to "medical is white and blue" instead of white and green, like TG did.

This color really only works for geneticists, to be honest, and maybe the CMO.

It's really only the CMO (and surgeons) that are associated with blue in medical.

Chemist shouldn't have access to this one; theirs should be orange.

**Comment by Xantholne** [comment]
Gonna remove chemist from it and whiten it up to a more baby blue later today.

**Comment by deep-fried-faceplant** [comment]
After this, no more berets please. Civilian jobs don't need berets.

**Comment by taukausanake** [comment]
Can the berets be white with their section color as a badge on it? Solid colors for the berets seems off for a job that is primarily white save for the CMO's hat here looking.

**Comment by Xantholne** [comment]
> Can the berets be white with their section color as a badge on it? Solid colors for the berets seems off for a job that is primarily white save for the CMO's hat here looking.

That was more along the lines of what I am doing tonight. Just not making it so the CE beret isn't unique.

**Comment by Xantholne** [comment]
Updated to a MD standard colorization. Saving old blue style beret for a later PR.

**Comment by taukausanake** [comment]
The paramedic maybe doesn't deserve one I'll agree, but it's kind of sad seeing it being left out.
I was thinking that each section was going to get it's little cross a color similar to the job's secondary color. Like MDs get the normal green, Chemists get an orange one, Geneticist get a light blue one, Virologists get a limey one, and even the Psychiatrist gets a cyan one. Overuse of sprites I'm sure but that's what I was expecting. Something a but special for each job. Or maybe that's what you're doing and I'm jumping the gun here.
I almost think the Brig Physician should get something similar to a Sec beret but I forget how they look. Maybe a red cross if not Sec?

**Comment by Xantholne** [comment]
We actually can't use red crosses because of well; The Red Cross. It's a real big thing but hte whole icon would get us into a lot of trouble on a scale we'd best avoid. 

I did have plans for the others currently not listed with the job selection however; but that is in a later PR down the road.

**Comment by taukausanake** [comment]
Wow. Now I care even less about other humans than I previously did. On that note, I DID use a red cross on my Hydroponics HUD. Might need to get that changed if it's such a big deal

**Comment by Xantholne** [comment]
If it's relating to anything medical related it has to be changed. Hud icon is probably fine.

**Pull request merged**
