### PR TITLE
Adds Whistles to the game

### PR DESCRIPTION
**Pull request by Henri215**
## What Does This PR Do

Adds whistles to the game.
4 seconds cooldown on usage and available from sol traders and security mails.

Sound from https://freesound.org/people/strongbot/sounds/568995/.
## Why It's Good For The Game

Its a fun little item that everyone would love to get from their mail or traders.
## Images of changes

https://github.com/ParadiseSS13/Paradise/assets/77684085/11f17a5e-2e2c-44ac-ba75-ba49a757f427

## Testing

- Did whistle with it on my hand and mouth.
## Changelog
:cl:
add: Whistles have been added, available from mails and traders
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
sec officers chasing people with whistles instead of hailers? good

**Comment by Carthusia** [comment]
Hah, i can just picture sec dressed as an old british bobby, blasting their whistle as more bobbies come flooding in from every corner, all blasting that whistle about to beat their ass with batons

**Review by JimKil3 — APPROVED** [review]
lgtm

**Review by DGamerL — COMMENTED** [review]
How does it look on non-human species with different head placements like vox?

**Comment by Henri215** [comment]
> How does it look on non-human species with different head placements like vox?

image
Added sprites for different species, i totally forgot that 😆

**Review by DGamerL — APPROVED** [review]
LGTM - I assume Drask have the default mask sprites?

**Comment by Henri215** [comment]
> LGTM - I assume Drask have the default mask sprites?

Yeah, and have yet to add back the tajaran sprite, just waiting until that error goes away :(

**Review by Contrabang — CHANGES_REQUESTED** [review]
Code is fine, but the sound clips at certain points, which makes a weird "cutting out" noise. 
image
If you could find a different whistle sound effect, or a better version of this sound effect, it would be good.

**Comment by Henri215** [comment]
Draft until a new sprite is made.

**Review by Contrabang — APPROVED** [review]
Code LGTM, just needs sprite changes as requested by sprite team

**Comment by McRamon** [comment]
Ill give sprite soon, pls wait

**Comment by Henri215** [comment]
> Ill give sprite soon, pls wait

Don't worry, its set to draft.

**Review by S34NW — APPROVED** [review]

**Comment by S34NW** [comment]
PR is still awaiting updated sprites, however has passed vote. Dev policy is clear in this instance: `If a PR adds a sprite, but the sprite is not the main focus of the PR (e.g. adding a new gun to the uplink), then they are permitted to vote on it, however any sprite team objections in such cases will NOT block merging.`
Sprite team can add new sprites later to resolve their concerns.

**Review by S34NW — APPROVED** [review]

**Pull request merged**
