### PR TITLE
Science changes(Remapping/Departmentalizing)

### PR DESCRIPTION
**Pull request by Da-Dman234**
Alright, I suppose I'll start off by saying this is my first Git Pull Request, so I hope to gods I did it correctly. Feel free to correct me as you see fit, as this is a learning experience for me (But be gentle please).

Anyways, on to the fun stuff. I imagine this will be a somewhat controversial issue, but my proposal is the division of science into three sub-departments : Technology, Explosives Research, and Biology. I've made my arguments more than once on the forums, so I'll make the summary here short and to the point.

**Technology**
((This current commit contains a fully working and tested *albeit locally* rendition of the new technology department, screenshots below))

http://prntscr.com/ay681w
http://prnt.sc/ay62yn

Right, so the biggest change here is the merging of Robotics and RnD. This department would have access to the EXPERIMENTOR, Mech Bay, and the newly designed Robotics lab. This is going to be the most powerful sub-department by a large margin, but in my opinion is still millions of times more manageable than science in its current state. 

For those who argue against the merging of robotics and RnD due to the separation of Roboticist and Scientist previously, I ask you, how often do you see Science build an Exosuit Fabricator in RnD? I can tell you from experience I see it pretty damn often, since all it takes is 5 metal, cable, and parts from RnD. Now, how often do you see rolling deathmechs built and used from these machines? The answer for me is not often, although it does occasionally happen. I'm sure some of you have probably seen it more often than I have, but I honestly think mechs are in a pretty balanced state right now. You have the Ion gun, trackers, SoP, and how hard it is to build one secretly (especially with my new map changes so that robotics has a **huuuuge** window to the north with no shutters.) I also took the liberty of adding a recharge bay lockdown button in the RD's office.

Here are a few reasons as to why I think the merge of RnD and Robotics is a good idea

1. It keeps whoever is manning the department plenty busy.
2. It gives scientists incentive to complete research, since as of this moment no one other than dedicated science players bother to touch it, as sad as that is to say.
3. Stops fights over resources.
4. Centralizes two powerful parts of science in the very front, in front of a non-obstructable window.
5. Stops scientists from becoming chem wielding, undroppable monsters of destruction, as I feel most of the complaints against science players is the power of the combination of chems and goodies/implants received from research.

Anyways, should this look like it will actually be merged, I'd like to rename the roboticist to a different job title (I was thinking of the title Lab Technician) and I'd get work started on the other two departments. I don't see the harm in giving a quick rundown as to what I'd like to do for the other departments should this gain support.

**Explosives Research**
Easiest and least controversial change most likely. Give them access to Toxins, Chem Research, and the Outpost. Only mapping change I'd most likely do for this is redesign Chem Research to be more similar to the Chemlab in Medical, so they can take requests for chems.

 **Biology**
I'm unsure what to do with this department. I've heavily considered adding Xenobotany again, but I don't really feel very comfortable with that. On the other hand I don't feel comfortable leaving Xenobio as its' own job again either. I had an idea of using a mining points system between the Kitchen and Xenobotany, where getting more points can unlock free bottles of unstable mutagen, saltpetre, ect. I have no idea how to code this though, and would definitely need help.

 **Miscellaneous**
I'd also like to redesign/move the: RD's Office, EXPERIMENTOR Room, Server Room, and Toxins Storage. As well as adding a small bathroom/shower section since I removed the shower in the entryway of science.

Anyways, merge or not it was interesting designing this, thanks for the read.

### CODE REVIEW

**Comment by QQCucumber** [comment]
Screenshots!

**Comment by QQCucumber** [comment]
I'm not sure if Biology really needs any major restructuring, they've been given a LOT of toys to play with this month.

**Comment by Mijhead** [comment]
I'd be for adding xenobotany to Biology.

**Comment by Aurorablade** [comment]
I much perfer what fox had in mind in his pr. While i appreciate the effort you put in to this and thought, I do not feel spliting science up would actually help it might just lead to people being factionlized and unhelpful to thier own department...BUT ANYWAY....Its my opinion, good effort on the mapping though, a bit jumbled up but things could be improved.

**Comment by QQCucumber** [comment]
I think this is a far more logical approach than Fox's to be honest, I like it a lot more.

**Comment by Da-Dman234** [comment]
While I certainly can't tell you how players would act at the end of the day, Medbay is "factionalized" and works reasonably well.

Also, I don't think we should be picking and choosing between Fox's PR and mine, as I feel they address two different completely different things, both of which just happen to be related to science balancing.

**Comment by IK3I** [comment]
There is one glaring issue with this change that I can see. The power requirements of running all that equipment will drain an APC in minutes if there is power failure. It may be even more draw than the engineering APC with full powered emitters. I would upgrade the battery to at least a high capacity if you intend to have that much equipment running

**Comment by Da-Dman234** [comment]
There are two APCs, both with the exact same equipment load as what you would normally see as of right now.

**Comment by Fox-McCloud** [comment]
:-1: from me.

Science is different from medical in terms of how the department flows into itself; it augments itself and functions in such a way that heavily departmentalizing it is going to make the department not be able to function as well as a whole unit. This would be similar to if coroner and surgeon were broken off as sub-departments (that only they had access to); it would negatively impact medical's "progress" and its ability to flow into itself for some things.

This also makes the worst and most powergamey aspect of science all that much worse; R&D. Now everything they need is available to them in one huge, blobbed together sub-department. As I mentioned, before, science's big problem is that it has progress and advancement with no goals or things to advance to---therefore, it can only impact the round in limited ways.

I guarantee that this is incentivize R&D players to validhunt *even more* than they currently do. Why? Because once R&D is finished, there's nothing else for them to do. As it stands now, they can start messing around with Toxins, Xenobio, and/or sci-chem once it's done. Now? They can either twiddle their thumbs, or assist/hinder the current antags of the round.

Map wise, there's a large number of problems and inconsistencies here:

- Plasma glass shouldn't be used willy nilly.
 - Plasmaglass is for high pressure, high temperature containment of gasses; it has no place in a department like robotics or R&D
- placement of tables/tools is awkwark/inefficient
 - If you're working in a single area, you'll often have to leave that little section to go place a tool down/pick it up--sometimes awkwardly so (walking all the way out and behind the glass to get to the latex gloves)
- This strongly reduces interaction between the station and science
 - If I'm in R&d doing my thing, I'm not going to notice someone who wants to make a request; conversely, it's even harder for me, as a requestee, to get R&D's attention, even if they're in their department
- There's a lot of little subtle things added here that are speeding up progression of both robotics and R&D, which is only going to make the most OP/powerful aspects of science even worse...to name a few:
 - round-start access to flashes
 - pre-built stunprod
 - pre-built medibots
 - I suspect (not 100% sure about this), more materials 
- It's one giant bit, open room, with a lot of wasted space
 - Huge square rooms with things set out around the perimeter is generally not a good design, aesthetically or mechanically, except where absolutely necessary (ie: atmospherics)
- science is now stupidly easy to break into
 - screwdriver+wirecutters+crowbar+wrench means you can get into science in about 10 seconds.
- bombing genetics is going to be even stronger now, as you can damage R&D, the research server, genetics, and cloning all at the same time.


Science is OP--making the single most powergamey aspects of it even faster and stronger, then crushing the other sub-departments is not the way to go about balancing it or reducing its round impacts.

**Comment by Da-Dman234** [comment]
I'm pretty tired, so forgive me if this ends up messy. But regarding the "flow" of science, I don't believe it's utterly essential for science to flow upon itself. The only thing that will be regularly needed is orders filled from the chemlab, which can be done by either medchem or scichem seeing as how it's really only going to be acids and other simple things.

As for the validhunting compared to scientists now a days? I'm going to disagree with that point, as most of the time now a days RnD is simply ignored/neglected by all the scientists who decide to man the chemlab (Which in my opinion is where most validhunters spawn from) or Xenobio instead and just leave the RD to do all the work, as quite frankly RnD is seen as a chore by most people. If you want to put a serious hamper on RnD validhunters restrict the use of bluespace equipment (AKA Bags of Holding, ect.) outside of science.
Automatically assuming that people will validhunt when they have nothing to do seems like somewhat of a jump to me, since as of right now Roboticists spends pretty much the whole shift doing nothing and I've very rarely ever seen problems with them. If the roboticist is its own job now, why isn't it considered something to do when merged with another?

Regarding your mapping comments, I completely agree with most of them.
1. I'll get to changing the plasma glass.
2. With the latex gloves, those are something you really only need to pick up once, but I'll consider what you said. Could you maybe provide a few other examples?
3. Half the time people end up calling for RnD over the radio anyways, but I agree with you on this one.
4. Granted, this is all stuff I'm totally willing to remove, minus the flashes as that's crucial to Robotics. I just didn't see it as a major problem when I originally placed them. Also, the material count is exactly the same, bar the single plasma piece I placed.
5. I guess it's just my design preference, but I like the room, well... roomier, especially when dealing with building mechs that take up a bit of space. I'd be happy to make changes that people point out
6. Thoughts on what I should regarding this? I felt this was the one place where plasma glass was actually suitable. Should I replace it with RWalls or just run wire under it?
7. Also, should this be accepted it was already within my plans to relocate the Research Server.

As for the merge conflict, I suspect because it's because I'm awful with git or the mapping tools. Anyway, I'll sit down and edit the map and look at the conflict sometime before the week ends. I'm fairly busy currently and really need to go to bed for the night.

**Comment by IK3I** [comment]
The merge conflict is caused by the map file you pulled being modified in the master branch during the time it took to make your changes and subsequent PR. To fix it, you'll need to copy pasta your new section onto a freshly downloaded map and then merge that.

**Comment by CrAzYPiLoT-SS13** [comment]
I like it. No arguments, as I really don't want to get caught up in the
stream of the, possibly, overly aggressive discussion. :+1:

**Comment by tigercat2000** [comment]
@Fox-McCloud You forgot a few mapping problems.
 - Two areas should never share a continuous room. This will cause very odd issues with ambient sounds and jukebox music (although the jukebox is probably not even worth considering)
 - The floor patterns are seven kinds of screwed up. The RD primary hallway has a weird grey pattern that only goes south, R&D has a nasty amalgamation of white, white blue, and grey blue tiles at the door (patterns should switch over at the door), the door markings aren't consistant with any other part of the station (half-stripe on left of door, stripe facing door, half-stripe reversed on right of door), there are random patterns on the floor next to the exosuit fabs, the surgery room doesn't actually have a complete warning stripe, there's arrow warning lines that don't quite fit indicating the seperation in areas, the grey tile randomly placed right next to the sci hallway -> sci shuttle hallway door

**Comment by QQCucumber** [comment]
I'd like to remind everyone that the community **overwhelmingly** voted in favor of splitting up scientists into more jobs, 75+%

**Comment by Regen1** [comment]
uhm, where do you get those numbers from @QQCucumber

**Comment by QQCucumber** [comment]
http://nanotrasen.se/phpbb3/viewtopic.php?f=48&t=7661

**Comment by Iamgoofball** [comment]
Good thing that poll doesn't matter.

Please keep the airlock door setup science has now. There's a reason people just waltz into medbay easily no problem.

**Comment by tigercat2000** [comment]
35 votes is far from everyone in the community

**Comment by QQCucumber** [comment]
Uh, why exactly does it not matter?

**Comment by QQCucumber** [comment]
>35 votes is far from everyone in the community

And yet it's a much larger sample size than you're going to get in this git thread, is it not?

**Comment by Regen1** [comment]
A poll is not a complete representation of the community's feel about the matter, and shouldn't be used as such

**Comment by QQCucumber** [comment]
>A poll is not a complete representation of the community's feel about the matter, and shouldn't be used as such

It is still a representation that shouldn't be ignored.

**Comment by Iamgoofball** [comment]
@QQCucumber because democracy has no place in code, the only people who matter here literally are the maintainers

**Comment by QQCucumber** [comment]
Wonderful.

**Comment by Regen1** [comment]
@Iamgoofball which is completely wrong

This isn't TG

**Comment by Iamgoofball** [comment]
@Regen1 Nope, this is true of every single codebase. Technically speaking, the only people with any authority are the people able to merge PRs on the repo.

Plus, democracy makes code shit. Any coder learns this after their first rodeo with a "m-muh democracy!!!" codefest where they spend a long amount of time handcrafting a feature just for some nerdlord they've never met to tell them it's a bad feature and that they're crap, and proceed to have their CODE PR closed on non-code grounds, often by people who are literally just a peanut gallery who either A. don't play much, B. wouldn't use or be affected by the feature anyways, or C. dont care and are in it for memes.

Why don't you try coding something big and exciting @Regen1 and have it rejected because some bartender main whined it ruins his immulshions when its an engineering feature.

**Comment by Regen1** [comment]
The power to press a button != The only people who matters and has a say in codebase matters

your view of it is screwed and completely wrong.

**Comment by CrAzYPiLoT-SS13** [comment]
I have actually experienced the exact thing Goofball is talking about a
multitude of times. Not only here, but at BRP and UT too.

**Comment by Da-Dman234** [comment]
> Why don't you try coding something big and exciting Regen1 and have it rejected because some bartender main whined it ruins his immulshions when its an engineering feature.

Honestly, it sounds like you're just angry that something you made was rejected. Not sure if that's the case or not but the fact that this PR remains open even though Fox disagrees with it says something upon itself. In the end of the day this is a 2d spessman game people play for fun, and should be treated as such.

Anyways, to anyone suggesting changes (Mainly Tiger and Fox, and Goof's one suggestion) It's truly appreciated, this is the kind of feedback I'm looking for to improve the map. With that being said though, I'm fairly busy until around Sunday. Since it seems more coders/git members are against this than for, I"ll leave this for now. Unless it gains some good support by Sunday I'll go ahead an close this PR on that day. If it somehow does gain support, that'll be when I sit down and redo the map with the suggested changes.

**Pull request closed without merging**
