### PR TITLE
Turns UO45 mission's external atmos to vacuum, heavily remaps the outside of MO19's for better Linda performance

### LINKED ISSUE #2336: LINDA: Too Many Active Turfs and Excited Groups
Simply put, at round start there's something like 2000-3000+ active turfs and around 30+ excited groups; this shouldn't  be the case as the map starts out in a relatively default state---while there will be some areas this is unavoidable (such as the server room or the plasma+N2O mix tanks), most of the active turfs are NOT in these areas.

This is likely a mapping errors due to custom values that are set when they shouldn't be.

Just a basic exploratory examination by me seems to reveal the vast vast majority of these are occurring because of z-level 5.

Furthermore, this is happening: 

turfs

@tigercat2000 

Relevant PRs: 
https://github.com/tgstation/-tg-station/pull/10593
https://github.com/tgstation/-tg-station/pull/10864
https://github.com/tgstation/-tg-station/pull/10669
https://github.com/tgstation/-tg-station/pull/10785

### PR DESCRIPTION
**Pull request by FreeStylaLT**
Some major changes to those two Away missions to reduce Linda load. You may have noticed that this was a different PR before, but that is because the previous one failed.

Here is what I have done:

- In UO45, I have turned all external (outside) tiles to a vacuum. No more plasma anywhere on the Away mission. This was done to reduce the load on Linda when any one of those windows or airlocks would get breached.

- Heavily remapped the outside of MO19. I replaced almost every external tile there with rock, for the same reason.

Pics:
Before: img After: img

img

img

img

img

img

As you can see, most of it is now simply rock, along with vacuum tiles where the breaches/asteroid tiles are located. A rather.. drastic change, but the evidence shows that it works. Two pickaxes were scattered around the place to fix the possibility of getting stranded.

Results:

Linda load *currently* on the server when this Away mission has been passed, about an hour into the round, with some general chaos having ensued (explosions, etc).
img
As you can see, there are over 5 thousand active turfs Linda is calculating and processing.  Considering a chaotic round, you can count off around one, maybe two thousand tiles from the Station activity. This happens every time this Away mission is passed, as any new breach on the Away mission gets spread out and calculated across _every single tile_ in that vast plane. It is not acceptable to have around 3 fricking thousand active tiles over a few busted windows.

Linda load with my previous (vacuuming every tile on MO19) fix, after having beaten the Away mission and waiting for about an hour for Linda to set in:
img
This is from the Away mission alone. It seems to either have not fixed the problem (Hence me closing this PR previously) or not doing enough to fix it properly.

And now here is the Linda load from this newest version of this PR, after having beaten the Away mission by visiting every area and tunneling about and waiting for around an hour for Linda to process:
img
As you can see, the difference is huge. I believe this fixes a portion of #2336 . I cannot.. think of a way of fixing this entirely, as some Linda activity will always be in the mission when you pass it, considering the aspect of pre-breached rooms, along with an active atmos system being present on the outpost.

:cl: FreeStylaLT
tweak: Changed UO45's and MO19's away missions' external tiles to  just airless ones.
tweak: Changed MO19's exterior to be more rock than ground, this is to make Linda cry less when this mission is passed.
/:cl:

### CODE REVIEW

**Comment by monster860** [comment]
Needs pi.... Oh.

**Comment by taukausanake** [comment]
This means we won't have plasma away missions? I guess we can't farm the gas for turbine /R-Ust engines that we will never have

**Comment by FreeStylaLT** [comment]
Yeah. No more plasma/CO2. Only vacuum.

**Comment by FreeStylaLT** [comment]
img
NOPE NEVER MIND UO45 NOT FIXED. The problem was not the actual atmos of the tiles, but the fact that there are an absolutely staggering amount of simulated tiles for the gases to spread out over. I need to fix this using a different approach.

**Comment by FreeStylaLT** [comment]
@TheDZD @Fox-McCloud Due to rather heavy changes, I'd suggest looking at re-labelling this, as it no longer just changes properties of tiles, but changes a _lot_ of tiles as a whole. Intention, though, is to lessen the burden on Linda from these two (MO19 primarily) Away missions.

**Comment by Fox-McCloud** [comment]
This makes it impossible to leave, once you enter, unless you specifically have a drill.

**Comment by Spacemanspark** [comment]
>Two pickaxes were scattered around the place to fix the possibility of getting stranded.

**Pull request merged**
