### PR TITLE
Gives shadowlings awesome hair

### PR DESCRIPTION
**Pull request by Aurorablade**
:cl: Phantasmic Dream Art, Fethas PR
rscadd: Updates the shadowling sprite. Sprite by Dreamy
/:cl:

### CODE REVIEW

**Comment by taukausanake** [comment]
I can't see the difference. Before and after please?

**Comment by PhantasmicDream** [comment]
I'm not sure if this will work @taukausanake, but we'll see.
https://ibb.co/gxHE85

**Comment by taukausanake** [comment]
@PhantasmicDream Yeah, that worked. So what is Nurn'Kal?

**Comment by PhantasmicDream** [comment]
@taukausanake Nurm'Kal is the fabulous Ascendant I draw, I only did a Sprite of him because I was already editing the Ascendant.
http://pre06.deviantart.net/f553/th/pre/i/2017/116/5/6/nurn_kal_by_phantasmicdream-db78jpd.jpg

**Comment by taukausanake** [comment]
inb4 Dreamy gets a fluff character. I would be all for that though

**Comment by PhantasmicDream** [comment]
>:3c

**Comment by Fruerlund** [comment]
Can we get the option for number 3 aswell? 

Way more scary looking.

**Comment by HereticChurch** [comment]
For those asking for a Before/After who don't want to click a link.

**Comment by Aurorablade** [comment]
the only reason i did not include nurny-kun is cuase its oc and it wouldn't be right unless dreamy gave permission to let it be the new shadowling

**Comment by Dinarzad** [comment]
It seems like a pretty drastic quality increase to me, especially that side sprite.

**Comment by KasparoVy** [comment]
Easy enough to bus in the sprite anyway for special events.

**Comment by PhantasmicDream** [comment]
Could be interesting to have both in, and people could have a small chance of spawning as the Nurn'Kal version

If that's possible

**Comment by Aurorablade** [comment]
I can look at the code if you are fine with the sprite use and try it

**Comment by PhantasmicDream** [comment]
Mhmm, or else the sprite is just going to sit there and not be used... Or Churchy will rarely be running around using it.

**Comment by KasparoVy** [comment]
Hah, just have something in the New() for shadowling ascendants that has a 10% chance or something of setting the icon state to Nurn'Kal.

**Comment by Aurorablade** [comment]
done

**Comment by KingPhilipIII** [comment]
Gonna look so fabulous now. I can flip my hair while I'm making punks explode.

**Comment by KingPhilipIII** [comment]
It would be fun if each of the differantly named slings had different ascended appearences, but that would be an obscene amount of work for such a small thing.

**Pull request merged**
