### PR TITLE
Makes cryogenic oversight console emaggable.

### LINKED ISSUE #7961: E-mag is unable to unlock cryostorage
**Problem Description**:
Emag can't unlock cryostorage

**What did you expect to happen**: 
To be allowed to retrieve the HoS' gun from cryostorage

**What happened instead**:
I couldn't

**Why is this bad/What are the consequences:**
Because you then need to get an HoP level ID to dispense whatever you need

**Steps to reproduce the problem**:
>Be traitor with goal to take HoS gun
>Have HoS gun in cryostorage
>Buy emag
>Try emagging the oversight console

### PR DESCRIPTION
**Pull request by Birdtalon**
Cryogenic Oversight Console can be emagged to remove the access requirements.

Fixes #7961 

🆑 Birdtalon
add: Cryogenic oversight console can now be emagged.
/🆑

### CODE REVIEW

**Comment by alexkar598** [comment]
This means a supply of tasers and sometimes shotguns for traitors.i don't think this sort of machinery should be emaagable

**Comment by Birdtalon** [comment]
And an emag in science means an unlimited supply of AEG. The idea here is that getting traitor objectives from the cryogenic oversight requires you to obtain an ID with access. The emag allows you to bypass this access requirement on plenty of other things so why not here too.

**Comment by alexkar598** [comment]
Rns is an area with 2 windows one of them have no shutters,requires having a role to have a reason to be in there,needs research and requires materials while cryo storage will have tasers 10 minutes in the round and have nobody apart from people who wants to quit(which won't bother with a tags at that point)

**Comment by Ty-Omaha** [comment]
The majority of people who take guns from RND do not care about being seen. The armory can also be broken into 10 minutes into the round with: tasers, shotguns, lasers and more.

With that being said, I main sec and can see this being abused, perhaps make it so only traitor-specific items can be retrieved such as krav maga gloves, HoS gun, etc.

**Comment by Aurorablade** [comment]
Nothing involeing cryo needs to be touched. i mean cryogenic for round exiting..not medical cryo.

**Comment by alexkar598** [comment]
Maybe make so traitors items go where they where when round started?

**Comment by Spacemanspark** [comment]
That would make no sense.

**Comment by Birdtalon** [comment]
The point that this was designed to address is that emags are used to open most "locked" things without the ID. If an objective item has gone into cryo then you need armoury or head access. Which probably will result in the owner of that ID being killed, or an attempted kill. The whole idea of the emag is to subvert, unlock, hack etc - and if you're a stealthy antag there's no way of continuing in that playstyle if you have to steal an ID from someone in order to do a theft objective.

**Comment by Regen1** [comment]
This is a shoddy implementation, there's nothing to display that it's been emagged, it just out and out removes the access requirement.

Not to mention, your argument is just stupid, cryo is without windows, accessible for everyone, and usually not an area people are going to be in, RnD is fully viewable by the main hallway in the ship, is constantly manned by other scientists, and requires RnD Access to get into.

Your argument completely misrepresents what you are comparing.

**Comment by Birdtalon** [comment]
I am comparing it to the RnD console because emagging it removes the access requirement. If you have an alternative proposal I would love to hear it.

**Comment by taukausanake** [comment]
> is constantly manned by other scientists

Hahahahaha, that's a good joke. But I agree with Birdtalon in argument that the emag is needed for this. Subvert and such makes sense. Do you really need to know that something was stolen from it when most other machines don't show error or can be fixed?

**Comment by Kyep** [comment]
I don't think this is a good idea.

While IC-wise it might make sense, OOC-wise, it doesn't.
With this in place, the only way to stop traitors getting sec gear from cryoing officers, is for sec to first ahelp, then strip, every officer they find SSD before throwing them in cryo. That gets back to status quo... but to do it, it generates a lot of ahelps and SSD attack logs.
The alternative is that, every shift, traitors can get a full set of sec gear simply by emagging the cryo console. That doesn't seem balanced.

**Comment by taukausanake** [comment]
@Kyep makes some good points. I didn't think about them. You'll need a different solution to get traitor steal objectives. Personally I'd think it would be procedure to turn in your gear before you go into cryo, but then you got SSDs to deal with and you can't loot them. Maybe make it someone's job to return items from the machine every so often.
Idea: Cargo could have the responsibility to cycling out and returning the gear. They don't have nearly enough to do but then those access requirements are an issue. Not like you can get a Head to do it though. Maybe HoP? They seem to busy themselves enough however...

**Comment by alexkar598** [comment]
Being an sometimes an hop player I can say that hops don't have a shit ton of things to do after the round start rush. After that its just 1-2 person every 10-30 minutes but I always forget to loot...I mean return things from cryo

**Comment by taukausanake** [comment]
Best solution then it to make it HoP responsibility to return those items to their rightful places/department. Need a SOP edit for that maybe

**Comment by Fox-McCloud** [comment]
Suggestion: make it so that if emagged, it spits out all traitor-objective items, instead.

It'll have to be a list (less than ideal), but there's so few theft objective items, it shouldn't be *too* bad.

**Pull request closed without merging**
