### PR TITLE
Improved Lethal Injections

### LINKED ISSUE #12306: Lethal Injections Syringes aren't lethal
**Issue Description**:
Lethal injection syringes don't kill

**What did you expect to happen**: 
For someone to die when injected with a lethal injection syringe
They didnt

**When did the problem start happening**:
Probably newcrit

### PR DESCRIPTION
**Pull request by PidgeyThePirate**
## What Does This PR Do
Fixes #12306
- The lethal injection syringe used for nothing else is no more.
- Added a set of 3 numbered syringes used for lethal injection for a faster and more humane(-looking) kill.
- Put them all in a kit in a custom box with an accompanying leaflet and replaced the old lethal syringes with them.
- There was one empty ld50 syringe on metastation z3. I replaced it with a normal one. The ld50 syringe sucked anyway.

## Why It's Good For The Game
The lethal syringe was made just for the purpose of giving lethal injections and it was bad for both executions and as an item for antags to steal and use. These new kits have some fairly nasty stuff in them, especially Thiopental, which may make them worth stealing (but maaaybe too worth stealing? Might want to make it so there's only one kit in the locker and another in the armory or something).

Also 3 syringes means a higher chance of botched executions, which is always... fun?

## Images of changes
[The contents of each syringe and their position.](https://imgur.com/a/m704s7O)

## Changelog
:cl:
add: A new box, a new paper, 3 new syringes as part of a Lethal Injection Kit, two of which have been placed in security instead of the two lethal injection syringes.
del: The snowflakey lethal injection syringe.
tweak: replaced the empty lethal injection syringe on metastation z3 with a regular one.
/:cl:

### CODE REVIEW

**Comment by Bigtimetripod** [comment]
I like the touch of adding some rare chemicals to the mix. Making it even worth to break into executions and stealing them if it benefits your gamestyle.

**Comment by datlo** [comment]
Really like this for both antags and security to use. :+1:

**Comment by Leanfrog** [comment]
Do they still take eons to inject or are they at a reasonable speed now?

**Comment by Couls** [comment]
normal syringe speed, the old huge syringes are removed from the code entirely

**Comment by Fox-McCloud** [comment]
Giving security antag-only chems is a no-no. This should generally be common chems.

I'm refactor syringes and have a high familiarity with reagents, so I'll handle the chem mix for syringes.

**Comment by PidgeyThePirate** [comment]
Suit yourself.

**Pull request closed without merging**
