### PR TITLE
Supply crates medical

### PR DESCRIPTION
**Pull request by Robertha89**
Adds Brute Trauma Treatment Kits to cargo.
not to be confused with the Advanced Brute Trauma kit

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Fine with the trauma kits, but the access for virus crate should really be a separate PR as that's a bitttt controversial and not really related to medical crates at all.

**Comment by FalseIncarnate** [comment]
I'd recommend rewording both your description and the crate name to say "Brute Treatment Kits" instead of including the words "Trauma Kits" which may lead people to believe that it contains the green packs commonly found in the Nanomeds and Advanced First Aid kits.

Aside from that, :+1: to the new crate.

**Comment by Robertha89** [comment]
Will put up the viro crate change after this has been merged.

**Comment by Fox-McCloud** [comment]
:+1:  from me--it's definitely consistent.

**Pull request merged**
