### PR TITLE
Replaces between() With Native clamp()

### PR DESCRIPTION
**Pull request by Arvenius169**
## What Does This PR Do
Replaces a global proc with a native proc that does the same thing.
Removes the global proc.

## Why It's Good For The Game
There's absolutely no reason for between() to exist.

### CODE REVIEW

**Comment by hal9000PR** [comment]
CL isn't needed here as it isn't a player focused change.

**Comment by Arvenius169** [comment]
> CL isn't needed here as it isn't a player focused change.

Noted. If I should remove the now empty changelog alongside the contents, let me know.

**Review by S34NW — APPROVED** [review]
why someone made their own proc for this is beyond me, implementation of clamp() looks good.

**Comment by AffectedArc07** [comment]
> why someone made their own proc for this is beyond me, implementation of clamp() looks good.

Clamp only became native in 513 so it's likely someone didn't notice the helper.

**Review by farie82 — APPROVED** [review]
Ensure to fully remove the CL tags if you have no CL entries

**Review by SabreML — APPROVED** [review]

**Review by dearmochi — APPROVED** [review]

**Pull request merged**
