### PR TITLE
adds xenomorphs back to the rotation

### PR DESCRIPTION
**Pull request by Edan52**
## What Does This PR Do
Re-adds xenomorphs back to the major event rotation, with the same requirements and rarity as terror spiders

## Why It's Good For The Game
They've had quite a few changes to make them more balanced, and people are more unwilling to contribute to their changes if they aren't actually a part of the game

## Testing
I forced the event, forgot there was a preference for it, tried again and succeeded.

## Changelog
:cl: CornMyCob
tweak: Xenomorphs are back in the rotation.
/:cl:

### CODE REVIEW

**Comment by procdrone** [comment]
Aren't we moving away from hard-stun mechanics? AFAIK xenos core mechanic is still hardstuns.

**Comment by Edan52** [comment]
> Aren't we moving away from hard-stun mechanics? AFAIK xenos core mechanic is still hardstuns.

#18888

**Comment by FloFluoro** [comment]
> Aren't we moving away from hard-stun mechanics? AFAIK xenos core mechanic is still hardstuns.

Xenomorph disarm and abilities have been refactored to inflict stamina damage and knockdown, instead of instastunning.

**Comment by procdrone** [comment]
> > Aren't we moving away from hard-stun mechanics? AFAIK xenos core mechanic is still hardstuns.
> 
> #18888

I see, basic work was already done(must have missed it), in this case, I wish you good luck, that's a big project to take on

**Review by hal9000PR — APPROVED** [review]

**Pull request merged**
