### PR TITLE
Added morgue access for the chef.

### PR DESCRIPTION
**Pull request by giblinator1337**
You're welcome.

### CODE REVIEW

**Comment by Aracino** [comment]
Soylent green, ho!

**Comment by FlattestGuitar** [comment]
The tray lights stand for meat quality.

**Comment by Taaketa** [comment]
@flattestguitar Green for the freshest meat right?

**Comment by Aracino** [comment]
Freshly sloughed corpses

**Comment by HereticChurch** [comment]
Please no, this is an awful idea. Go bug the HoP to satiate your cannibalistic fantasies, NT wouldn't be promoting it by standardizing the access there.

**Comment by Aracino** [comment]
@HereticChurch Well not like chaplain ever creamates corpses.

**Comment by davidchan13** [comment]
Yeah, Chappie is too busy chasing valids with his snowflake stick and armor, the chef is just sitting back with a meat cleaver dreaming of better days.

**Comment by HereticChurch** [comment]
Chaplain has access there because it makes sense, they can cremate/space the corpses that medbay can't recover and are expected to do that, it works in an RP perspective. Why the hell would NT give the chef access to the morgue and promote cannibalism of crewmembers? I think it's more fun for the chef to break in and do that, possibly being arrested for it, rather than making it the norm.

**Comment by taukausanake** [comment]
@HereticChurch because fuck it. That's what I would think. NT is only as professional as it concerns them, not those who work for them. But I'm not an admin or lore team so what do I know?
As for the chef breaking into the morgue, that edges on self-antaging almost, at least doing something you really shouldn't be doing for whatever reason. Also what do you end up doing once the morgue is full of dead, probably non-respawnable players and the body count just keeps on piling?

**Comment by SigholtStarsong** [comment]
This is a hilariously bad idea, mostly for the reasons that Churchy stated. We are not Reavers, and all I can see this being used for is an excuse to gib clonable players/steal shit.

**Comment by Allfd** [comment]
Outside of this being an important part of Vox culture, probably not a great idea.

**Comment by SamHPurp** [comment]
ANY1 ELSE WANT 2 EAT DEAD PPL?

**Comment by tristan1333** [comment]
Someone has to use the old clone corpses

**Comment by Taaketa** [comment]
Chefs used to have morgue access way back in the day.

**Comment by Twinmold93** [comment]
The chef doesn't need this access... It's a bad idea for the reasons state above, but also from an RP perspective, makes zero sense and will make people less likely to trust the chef if they think they are eating people.

**Pull request closed without merging**
