### PR TITLE
Blindfolds are now craftable from 3 cloth

### PR DESCRIPTION
**Pull request by farie82**
**What does this PR do:**
Makes blindfolds craftable from 3 cloth

**Changelog:**
:cl:
add: Blindfolds are now craftable from 3 cloth. For those vampire prisoners you want to keep in check
/:cl:

### CODE REVIEW

**Comment by Bookdrizzt** [comment]
Finally, my dreams of kidnapping someone and not letting them know their location come to fruition. The only issue: where the heck do you even get cloth? I never see it.

**Comment by farie82** [comment]
Botany ane the public gardens biomass generator can make them

**Comment by TheSardele** [comment]
At long last, the previously one of a kind technology of "putting something opaque over somebodies eyes" that could previously only be found in the execution room is now within our reach.

**Comment by Couls** [comment]
The era of birthday bashes is upon us

**Comment by taukausanake** [comment]
~~Ah, if only we had a ballgag to go with that blindfold.~~
Maybe put a small stack of cloth in the maintenance loot spawns so this will be more viable than going to Hydroponics/the arrivals garden. I think a stack of five would be nice

**Comment by Tayyyyyyy** [comment]
> Maybe put a small stack of cloth in the maintenance loot spawns so this will be more viable than going to Hydroponics/the arrivals garden. I think a stack of five would be nice

If we really want cloth to be more easily accessible, maybe just make it craftable with piece of clothing and wirecutters.

**Comment by taukausanake** [comment]
I had a whole refactor/module in my head for a job that's basically in the same vein as Barber but for clothes. They would have a sewing machine (autolathe but for clothes) and could make them using cloth and some medals for special clothing. Recycle unused clothing for more material and raid/break all the clothes vendors like how the Barber breaks all mirrors.
Basically a bastardization of Barber and R&D minus the research bit

**Comment by Ralta** [comment]
> I had a whole refactor/module in my head for a job that's basically in the same vein as Barber but for clothes. They would have a sewing machine (autolathe but for clothes) and could make them using cloth and some medals for special clothing. Recycle unused clothing for more material and raid/break all the clothes vendors like how the Barber breaks all mirrors.
> Basically a bastardization of Barber and R&D minus the research bit

So...a tailor? :eyes:

**Comment by taukausanake** [comment]
As I didn't say the name of the job, yes exactly that a tailor. I thought it would be a neat sort of karma job addition if Paradise would support it. It wouldn't be an important job in the least, but neither is the Barber

**Comment by KasparoVy** [comment]
I'm stoked. I was happy to see blindfold being introduced for the blind disability in the traits PR but this'll do.

**Comment by farie82** [comment]
If somebody else wants to take on the PR feel free.

**Pull request merged**
